### ISSUE TITLE
Entity glowing is broken

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10004]
##### Minetest version
```
Minetest 5.3.0-dev-850af8008-dirty (Windows)
```

##### OS / Hardware

Operating system: Windows 10
CPU: Ryzen 3200G

GPU model: XFX ATI Radeon RX 580
OpenGL version: 4.6

##### Summary
Entity glowing is broken.

##### Steps to reproduce
Create an entity that glows, it will not glow in the dark.

**Comment by SmallJoker** [comment]
8fc9e7eb1

**Comment by oilboi** [comment]
:D
