### ISSUE TITLE
Minetest doesn't start android 10

### ISSUE THREAD

**Issue by SeBarosanul** [minetest/minetest#10001]
##### Minetest version

```

```

##### OS / Hardware

Operating system: Android 10
CPU: Exynos 9820 

GPU model:
OpenGL version:

##### Summary
On first launch, a loading screen appears. Once the bar reaches 100%, the game crashes and reopens, and the same thing happens, making it impossible to get into the game and very hard to exit the game.

##### Steps to reproduce
1. Open F-Droid
2. Download Minetest
3. Open it

**Comment by SmallJoker** [comment]
Duplicate of #9413.

Please try a build from here: https://minetest.rubenwardy.com/android/
