### ISSUE TITLE
Pressing F5 with inventory open turns it yellow

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10016]
##### Minetest version
```
Minetest 5.3.0-dev-8fc9e7eb1 (Windows)
```

##### OS / Hardware
Operating system: Windows 10
CPU: AMD Ryzen 3 3200G

GPU model:  8192MB ATI Radeon RX 580 Series (XFX Pine Group)
OpenGL version: 4.6

##### Summary
If you press F5 when an inventory is open it turns yellow.

##### Steps to reproduce
Open an inventory and press F5.

**Comment by sfan5** [comment]
Intentional debug feature, see #9423
