### ISSUE TITLE
Build on macOS catalina+homebrew fails, _iconv* undefined symbol

### ISSUE THREAD

**Issue by stephenaa** [minetest/minetest#10014]
##### Minetest version

```
0ab580810c6ccebfd57497b9565e3e396d250d70
```
...

##### OS / Hardware

Operating system: macOS Catalina 
CPU:10.15.4

GPU model: N/A
OpenGL version: N/A

##### Summary

Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_iconv_open", referenced from:
      __nl_find_msg in libintl.a(dcigettext.o)
  "_libiconv", referenced from:
      convert(char const*, char const*, char*, unsigned long, char*, unsigned long) in string.cpp.o
  "_libiconv_close", referenced from:
      convert(char const*, char const*, char*, unsigned long, char*, unsigned long) in string.cpp.o
  "_libiconv_open", referenced from:
      convert(char const*, char const*, char*, unsigned long, char*, unsigned long) in string.cpp.o
  "_libiconv_set_relocation_prefix", referenced from:
      _libintl_set_relocation_prefix in libintl.a(relocatable.o)
ld: symbol(s) not found for architecture x86_64

I guess CMake picks up the wrong iconv library?
CMakeCache.txt:ICONV_LIBRARY:FILEPATH=/usr/lib/libiconv.dylib
mdfind -name libiconv:

/usr/lib/libiconv.2.dylib
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/libiconv.rb
/opt/local/share/doc/libiconv
/opt/local/lib/libiconv.a
/opt/local/lib/libiconv.2.dylib

##### Steps to reproduce
cmake . -DRUN_IN_PLACE=TRUE 
make

**Comment by sfan5** [comment]
Looks like the libintl.a you're linking to wants to be linked to a specific libiconv, probably the one from brew not from /usr/lib.
Or is `/opt/local/lib` not the path brew installs to? And another question: From where did you install gettext (libintl)?

**Comment by paramat** [comment]
@stephenaa ^ Perhaps you can answer the questions?

**Comment by dwelch2344** [comment]
Not one to muddy up other's issues, but think we're seeing a similar thing. I'm running OS X 10.15.6 with a fresh fork of master from earlier today, and ran the following:

```sh
brew install cmake libvorbis irrlicht jsoncpp
```

then 
```
cmake . -DRUN_IN_PLACE=TRUE -DBUILD_CLIENT=TRUE
make -j4 
```


And received the following:
```
Undefined symbols for architecture x86_64:
  "irr::core::IdentityMatrix", referenced from:
      setBillboardTextureMatrix(irr::scene::IBillboardSceneNode*, float, float, int, int) in content_cao.cpp.o
      GenericCAO::updateTextures(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) in content_cao.cpp.o
      RenderingCore::draw3D() in core.cpp.o
  "irr::video::IdentityMaterial", referenced from:
      irr::scene::ISceneNode::getMaterial(unsigned int) in clientmap.cpp.o
      irr::scene::ISceneNode::getMaterial(unsigned int) in clouds.cpp.o
      irr::scene::ISceneNode::getMaterial(unsigned int) in particles.cpp.o
      irr::scene::ISceneNode::getMaterial(unsigned int) in sky.cpp.o
      irr::scene::ISceneNode::getMaterial(unsigned int) in wieldmesh.cpp.o
  "Json::ValueIteratorBase::deref()", referenced from:
      ServerList::getOnline() in serverlist.cpp.o
      ToolCapabilities::deserializeJson(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in tool.cpp.o
  "Json::StreamWriterBuilder::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      fastWriteJson(Json::Value const&) in convert_json.cpp.o
  "Json::Value::operator=(Json::Value&&)", referenced from:
      ClientLauncher::launch_game(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, GameStartData&, Settings const&) in clientlauncher.cpp.o
      ModMetadata::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mods.cpp.o
      ModMetadata::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in mods.cpp.o
      read_json_value(lua_State*, Json::Value&, int, unsigned char) in c_content.cpp.o
      ModApiUtil::l_parse_json(lua_State*) in l_util.cpp.o
      fetchJsonValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in convert_json.cpp.o
      fastWriteJson(Json::Value const&) in convert_json.cpp.o
      ...
  "Json::Value::operator=(Json::Value const&)", referenced from:
      read_json_value(lua_State*, Json::Value&, int, unsigned char) in c_content.cpp.o
      ServerList::getOnline() in serverlist.cpp.o
      std::__1::vector<Json::Value, std::__1::allocator<Json::Value> >::insert(std::__1::__wrap_iter<Json::Value const*>, Json::Value const&) in serverlist.cpp.o
      ServerList::serializeJson(std::__1::vector<Json::Value, std::__1::allocator<Json::Value> > const&) in serverlist.cpp.o
      ToolGroupCap::toJson(Json::Value&) const in tool.cpp.o
      ToolCapabilities::serializeJson(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const in tool.cpp.o
  "_createDevice", referenced from:
      RenderingEngine::getSupportedVideoModes() in renderingengine.cpp.o
      RenderingEngine::getDisplaySize() in renderingengine.cpp.o
  "_createDeviceEx", referenced from:
      RenderingEngine::RenderingEngine(irr::IEventReceiver*) in renderingengine.cpp.o
      RenderingEngine::print_video_modes() in renderingengine.cpp.o
```

The JSON issues didn't show up until I tried `brew install jsoncpp` so I'm betting it's similar to #10082 and I've just got the wrong version. 

Haven't built a CPP project in about 10+ years (thus the brew installs) so not sure what would be helpful for diagnosis. I'll dig in tomorrow to try and debug, but would love some insight / help on what to do.

**Comment by rubenwardy** [comment]
No response from OP
