### ISSUE TITLE
Valid texture modifier use showing me my memory

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10011]
##### Minetest version
```
5.3-dev
```

##### Summary

I have used `"progress_bar_bg.png^([lowpart:50:(progress_bar.png^[transformR90)^[transformR90])"` (`"[lowpart:50:(progress_bar.png^[transformR90)"` is enough for reproduction) for emulating a progress bar using a CSM.
This was the result:

![Screenshot](https://user-images.githubusercontent.com/34514239/84044534-ff88a800-a9a7-11ea-97c6-f78df46d2315.png)

**Comment by sfan5** [comment]
No idea about this issue but it is certainly interesting that `[transform` is entirely unable to deal with images that aren't square.

**Comment by appgurueu** [comment]
The issue is with lowpart - it doesn't properly handle things which are not files.
