### ISSUE TITLE
Entities disappear in 3rd person mode when running set_attach()

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10010]
##### Minetest version
```
Minetest 5.3.0-dev-8fc9e7eb1 (Windows)
```

##### OS / Hardware
Operating system: Windows 10
CPU: Ryzen 3200G

GPU model: 8192MB ATI Radeon RX 580 Series (XFX Pine Group)
OpenGL version: 4.6

##### Summary
Entities do not appear/disappear in 3rd person mode when running set_attach() to a player.

##### Steps to reproduce
Run code which runs ```entity:set_attach(player,"Body",vector.new(0,0,0),vector.new(0,0,0)) ``` and they will disappear until camera change.

##### Fun Fact
10010 is binary for ```?```

**Comment by SmallJoker** [comment]
Feel free to adopt #8342.
Similar issue: #8038
