### ISSUE TITLE
UBPorts port?

### ISSUE THREAD

**Issue by Qiangong2** [minetest/minetest#10023]
## Problem

The pinephone has finally been shipped and with it comes ubports. Minetest cannot be run on Ubports as of now without compiling through libertine unfortunately

## Solutions

 An official app published through openstore would be ideal

## Alternatives

Compiling directly from the terminal without libertine doesn't work, so maybe that?

**Comment by rubenwardy** [comment]
We can barely support Android, and I doubt any devs have a pinephone

Closing this, but feel free to send PRs that fix support on platforms we don't fully support (as long as the PRs aren't too invasive)

**Comment by sfan5** [comment]
Note that the touchscreen is supported on Linux thanks to a contribution by @TheBrokenRail (#10729), so if built correctly it should work just as well as on Android.

**Comment by TheBrokenRail** [comment]
> We can barely support Android, and I doubt any devs have a pinephone
> 
> Closing this, but feel free to send PRs that fix support on platforms we don't fully support (as long as the PRs aren't too invasive)

I have a PinePhone and I'd be willing to test Minetest on it if needed. (It's actually what I tested my touch PR on along with my laptop.)

**Comment by sfan5** [comment]
Feel free to submit Minetest to UBports then. (is that how it works?)

**Comment by rubenwardy** [comment]
It's hard to port to a platform when you don't have a device, even if you have someone else to test. And supporting requires a lot more effort from us than just a port
