### ISSUE TITLE
CSM randomly fail to load after quitting game after loading on server

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10024]
##### Minetest version
```
Minetest 5.3.0-dev-fe3e69eb4 (Windows)
```

##### OS / Hardware
Operating system: Windows 10
CPU: Ryzen 3200G

##### Summary
If you exit the game after joining a remote server with CSM mods loaded they will not reload until joining singleplayer or hosting a local server from the client.

##### Steps to reproduce
Explained above.

**Comment by SmallJoker** [comment]
CSM is constructed in the client:
https://github.com/minetest/minetest/blob/80d9e9c1834fdc78588ffe2842766c0177227786/src/client/client.cpp#L153-L155

CSM is destructed together with the client:
https://github.com/minetest/minetest/blob/80d9e9c1834fdc78588ffe2842766c0177227786/src/client/client.cpp#L293-L294

> If joining a server for the first time they will load and then will not reload

The code tells other stories. Please create a CSM that creates log entries on load and `on_shutdown`. If the mods are not loaded, the server likely forbids them. In this case you'll see following warning in the logs:

> Client-provided mod loading is disabled by server.

**Comment by oilboi** [comment]
> CSM is constructed in the client:
> https://github.com/minetest/minetest/blob/80d9e9c1834fdc78588ffe2842766c0177227786/src/client/client.cpp#L153-L155
> 
> CSM is destructed together with the client:
> https://github.com/minetest/minetest/blob/80d9e9c1834fdc78588ffe2842766c0177227786/src/client/client.cpp#L293-L294
> 
> > If joining a server for the first time they will load and then will not reload
> 
> The code tells other stories. "reload" is a confusing term because it implies running the scripts multiple times per instance, which is not the case here.
> Please create a CSM that creates log entries on load and `on_shutdown`. If the mods are not loaded, the server likely forbids them. In this case you'll see following warning in the logs:
> 
> > Client-provided mod loading is disabled by server.

I figured out the issue: If you join a remote server with CSM loaded they will not reload until joining singleplayer. Here is a video on it that shows you it happening: https://youtu.be/0v_q1f6cEnc

**Comment by SmallJoker** [comment]
Could you please apply following diff to check what's called when?
I tried to reproduce the bug by doing the same steps as in your video, but the client mods always load according to the server's restriction settings (`0` or `1`).

<details>
<summary>Diff spoiler</summary>

```diff
diff --git a/src/client/client.cpp b/src/client/client.cpp
index c03c062c6..6e6c6d7cf 100644
--- a/src/client/client.cpp
+++ b/src/client/client.cpp
@@ -137,6 +137,7 @@ void Client::loadMods()
 	// Don't load mods twice.
 	// If client scripting is disabled by the client, don't load builtin or
 	// client-provided mods.
+	printf("Client::loadMods: %lX\n", getCSMRestrictionFlags());
 	if (m_mods_loaded || !g_settings->getBool("enable_client_modding"))
 		return;
 
@@ -153,6 +154,7 @@ void Client::loadMods()
 	m_script = new ClientScripting(this);
 	m_env.setScript(m_script);
 	m_script->setEnv(&m_env);
+	printf("Client::loadMods: set env\n");
 
 	// Load builtin
 	scanModIntoMemory(BUILTIN_MOD_NAME, getBuiltinLuaPath());
@@ -213,6 +215,7 @@ void Client::loadMods()
 		m_script->on_camera_ready(m_camera);
 	if (m_minimap)
 		m_script->on_minimap_ready(m_minimap);
+	printf("Client::loadMods: done\n");
 }
 
 bool Client::checkBuiltinIntegrity()
@@ -280,6 +283,7 @@ const ModSpec* Client::getModSpec(const std::string &modname) const
 void Client::Stop()
 {
 	m_shutdown = true;
+	printf("Client::Stop: loaded?=%i\n", (int)m_mods_loaded);
 	if (m_mods_loaded)
 		m_script->on_shutdown();
 	//request all client managed threads to stop
@@ -331,6 +335,7 @@ Client::~Client()
 
 	delete m_minimap;
 	delete m_media_downloader;
+	printf("Client::~Client\n");
 }
 
 void Client::connect(Address address, bool is_local_server)
@@ -1785,6 +1790,8 @@ void Client::afterContentReceived()
 	text = wgettext("Done!");
 	RenderingEngine::draw_load_screen(text, guienv, m_tsrc, 0, 100);
 	infostream<<"Client::afterContentReceived() done"<<std::endl;
+
+printf("afterContentReceived done\n");
 	delete[] text;
 }
 
diff --git a/src/script/cpp_api/s_base.cpp b/src/script/cpp_api/s_base.cpp
index f965975a3..3cb82b1b5 100644
--- a/src/script/cpp_api/s_base.cpp
+++ b/src/script/cpp_api/s_base.cpp
@@ -129,6 +129,8 @@ ScriptApiBase::ScriptApiBase(ScriptingType type):
 
 ScriptApiBase::~ScriptApiBase()
 {
+	if(m_type == ScriptingType::Client)
+		printf("ScriptApiBase::~ScriptApiBase: client\n");
 	lua_close(m_luastack);
 }
 

```
</details>

**Comment by oilboi** [comment]
Here are the results:
```joining singleplayer:
Client::loadMods: 0
Client::loadMods: set env
Client::loadMods: done

leaving singleplayer:
Client::Stop: loaded?=1
ScriptApiBase::~ScriptApiBase: client
Client::~Client

joining multiplayer with the bug:
afterContentReceived done
Client::loadMods: 0

leaving multiplayer with the bug:
Client::Stop: loaded?=0
Client::~Client```

**Comment by SmallJoker** [comment]
> joining multiplayer with the bug:
> afterContentReceived done
> Client::loadMods: 0

If there's no `Client::loadMods: set env` line below what you wrote, it's basically limited to following possibilities:
 * `enable_client_modding` setting is `false` (minetest.conf changed)
 * `ClientScripting` throws an error that is somehow caught by the network packet handler

Please step through the code (debugging tools or `printf`-alike) and find out where exactly it stops executing.
Additionally, use following code to figure out whether an exception is thrown:
```
try
	loadMods();
catch (BaseException &e)
	std::cout << e.what() << std::endl;
```
in
https://github.com/minetest/minetest/blob/0a1181f7637adab6fe1ba5d3c09038912a06b37f/src/network/clientpackethandler.cpp#L1461

**Comment by oilboi** [comment]
This is closed because Client -> Network -> enable_client_modding is disabled by default and what I'm showing is actually a bug to load client mods even if the setting is disabled.
