### ISSUE TITLE
Android: Missing settings and tree structure in "All Settings"

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10045]
##### Minetest version
https://github.com/minetest/minetest/commit/a1b444bb61e6c9dcb0581a8550fd7795a3555cec

Build: https://github.com/rubenwardy/minetest/releases/tag/5.3.0-rc1 

##### OS / Hardware
Operating system: Android

Samsung S7 Edge

##### Summary

Only a sub-set of settings are present in All Settings, and the tree structure is missing for engine settings. Mod settings still appear in a tree node.

debug.txt contains errors about invalid lines for each section header. It also contains errors about invalid bool settings and such, with newlines being kept in the error message

I'll copy the error messages in a sec

**Comment by MoNTE48** [comment]
I can confirm.
The most interesting thing is that it worked in previous (0.4.17) versions. But I have no idea what the reason is.

- LuaJIT? I can rebuild it.
- Compiler optimization flags? Hardly, they are the same as in MultiCraft and everything works there...

**Comment by rubenwardy** [comment]
It worked a while back, and I'm pretty sure I tested the touchscreen PR. Perhaps there was a rebase issue that broke the touchscreen changes after merging? Or perhaps something else broke this

**Comment by rubenwardy** [comment]
I suspect the issue is to do with line endings, as I made the Android build on Windows 10

**Comment by rubenwardy** [comment]
```
2020-06-17 20:57:31: ERROR[Main]: Invalid line in /storage/emulated/0/Minetest/builtin/settingtypes.txt "[**Noises]
"
2020-06-17 20:57:31: ERROR[Main]: Invalid line in /storage/emulated/0/Minetest/builtin/settingtypes.txt "[*Advanced]
"
2020-06-17 20:57:31: ERROR[Main]: Invalid boolean setting in /storage/emulated/0/Minetest/builtin/settingtypes.txt "enable_mapgen_debug_info (Mapgen debug) bool false
"
2020-06-17 20:57:31: ERROR[Main]: Invalid line in /storage/emulated/0/Minetest/builtin/settingtypes.txt "[Online Content Repository]
"
```

**Comment by MoNTE48** [comment]
@rubenwardy, try packing the archive manually (using WinRAR/7zip). Before that, disable archive creation in app/build.gradle

**Comment by rubenwardy** [comment]
Not an issue when the repository is checked out to preserve line endings

```
git config --global core.autocrlf false
```
