### ISSUE TITLE
Hand over player to another server

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest#10041]
## Problem

You cant make sth like a network, because there is no way to put a player on a differrent server.

## Solutions

Add a Feature in LUA Api to request the player to change the server. The client would then be disconnected and ask the user to enter username and password. Then it will connect

## Alternatives
Direct Overheading but that would require a shareable to auth database

## Additional Context
This feature would open up so many possabilties, just think about subgmaes servers without having to hassle with height and position validation

**Comment by sfan5** [comment]
I am 100% this is a duplicate but can't find the issue right now.

**Comment by Niwla23** [comment]
Can someone please link the issue? I also cant find it

**Comment by sfan5** [comment]
#5813

**Comment by Niwla23** [comment]
That has not much to do with this, I am not directly asking for a network feature, it would just make them possible.
I am for a simple feature that disconnects player with the payload to connect to another server. The user needs to manually enter the Username and password

**Comment by ClobberXD** [comment]
> That has not much to do with this, I am not directly asking for a network feature, it would just make them possible.

#5813 is exactly what you're looking for. Did you go through the entire issue? It's just a feature request, and the first post only *suggests* an implementation. There's all sorts of other implementation discussion there as well. But it looks like that issue has been folded into #4428 (which doesn't seem to be directly related server-to-server player transfer).
