### ISSUE TITLE
Android asset upgrade fails

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10049]
When updating from 5.0.1 to 5.3.0, the app will crash due to a LICENSE.txt folder

The contents are as follows:

```
minetest/
└──  LICENSE.txt/
    └── lgpl-2.1.txt
```

##### Steps to reproduce
Install the app from the play store, then install the release candidate

##### Solutions

1. Don't include LICENSE.txt, as it's not especially needed anyway
2. Delete everything that shouldn't be saved before updating, to remove old files
3. ...

**Comment by MoNTE48** [comment]
Well be fixed today. Probably, ZIP will changed in SDK 29 (Android 10).

**Comment by rubenwardy** [comment]
The bug is in 5.0.1 - it's moving the license file to a folder called license.txt rather than renaming it. I'm not sure if including the license is a legal requirement

**Comment by MoNTE48** [comment]
The user should not open this folder at all. If he is interested in the source code, he should open the official website or github, get a copy of the license and source code.
