### ISSUE TITLE
Android: Can only strafe right

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10044]
##### Minetest version
https://github.com/minetest/minetest/commit/a1b444bb61e6c9dcb0581a8550fd7795a3555cec

Build: https://github.com/rubenwardy/minetest/releases/tag/5.3.0-rc1 

##### OS / Hardware
Operating system: Android
Samsung S7 Edge

##### Summary
I can only strafe right, and cannot walk left, forward, or back.

(A strafe is a sideways movement, perpendicular to the look direction)

**Comment by MoNTE48** [comment]
The main question is - did it work in 5.1?
Not sure I understand the essence of the movement. Virtual joystick issue, right?

**Comment by rubenwardy** [comment]
It worked in previous builds of 5.3.0-dev, both in my and your builds. I'm pretty sure I tested it in the touchscreen fixes PR too. Perhaps it broke due to a rebase issue when merging that PR, or something else broke it

**Comment by MoNTE48** [comment]
Hmm, very curious. https://github.com/minetest/minetest/commit/756dc89ede7daa640fe6391ee2c51e78864c0d5c

**Comment by rubenwardy** [comment]
> Hmm, very curious. Try revert it: 756dc89

Doesn't fix it. I'll try an older version, and then bisect

**Comment by rubenwardy** [comment]
```
b9f618746c0f673ea1f851bb2473fb3ca9410093 is the first bad commit
commit b9f618746c0f673ea1f851bb2473fb3ca9410093
Author: MoNTE48 <MoNTE48@mail.ua>
Date:   Thu Apr 16 17:37:40 2020 +0200

    TouchScreenGUI: fix some bugs, cleanup
```

**Comment by rubenwardy** [comment]
I've found the issue

**Comment by MoNTE48** [comment]
Are you sure? Can you clarify which direction the joystick is? I'll see tomorrow.
Maybe a video or a screenshot...

**Comment by rubenwardy** [comment]
See PR
