### ISSUE TITLE
Right-clicking a dropped item should place a block instead of doing nothing

### ISSUE THREAD

**Issue by koi-ghoti** [minetest/minetest#10040]
##### Minetest version

```
Minetest 5.2.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/share/minetest"
```

##### OS / Hardware

Operating system: Ubuntu 20.04
CPU: Intel® Core™ i3-8109U CPU @ 3.00GHz × 2 

##### Summary

Currently, if the ground has dropped items on it, whether it be from mining with a full inventory or from manually dropping the blocks, the dropped items can be a hindrance to building. Imagine someone mining out a staircase and dropping lots of cobble on the stairs, and then trying to place stairs where the dropped cobble is. It's really hard to do because right-clicking on the dropped item does nothing — you have to kind of squeeze between the dropped blocks when you're aiming with the mouse.

##### Steps to reproduce

1. Drop blocks or items
2. Attempt to build on the block that the item/block has been dropped on.It won't be done unless you right-click on a spot that is not covered by the dropped blocks/items

**Comment by rubenwardy** [comment]
I'm not sure this behaviour really makes that much sense. Perhaps you should drop your discarded items in a hole, or install a trash can mod

**Comment by Kimapr** [comment]
This is a MTG issue and should be moved there

**Comment by appgurueu** [comment]
I agree. This is fairly game-specific behavior which doesn't belong in the engine IMO.

**Comment by paramat** [comment]
It may be a little inconvenient in rare situations (inventory is rarely full), but if the player is pointing at an entity then the entity should be selected, this is fairly obvious.
I agree this is best done in games if they want.
:-1:

**Comment by SmallJoker** [comment]
This behaviour needs checking against `on_rightclick` of the clicked entity - a task that can currently only be done by the server. No node prediction if the client isn't aware of it.
Additionally, holding Sneak/Shift would be a requirement for entities that make use of `on_rightclick` - same behaviour as regular nodes.
Generally, I don't think the nodes would be placed where you actually want them: selection boxes occlude the shooting line and the clicked object position might be barely on another node position, causing misplacing. Running a second Raycast to ignore all selection boxes would be possible, but IMO not worth the effort to get it working properly
