### ISSUE TITLE
Provide solid milestones

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10057]
## Problem
Right now milestones are basically bugfixing and things looking nice on the spot. Also, there is usually just one milestone at a time

## Solutions
It'd be nice to have an actual roadmap to better understand what the engine is aiming at. So at least two, three milestones saying "we're going to focus on this", "we're going to focus on that". Even one feature per milestone, like the main menu rework for instance. This can help both the devs and the users, because the former knows where to focus, and the latter knows what to expect.
If you want a head start: https://forum.minetest.net/viewtopic.php?f=3&t=24742

## Additional context
I obviously don't know what it's like to manage a project this big, but I do know good planning is even more required when something gets bigger and bigger, in order to not waste energies, time and (according to the case) money. I also know is pretty useless developing something without any idea in mind, and I do know it can be frustrating sitting there thinking what's a good move and what's not. But I also know the sensation after that moment has been overcome (spoiler: amazing)

**Comment by sfan5** [comment]
duplicate? #3476

**Comment by Zughy** [comment]
> duplicate? #3476

That sounds more of a generic view of MT per se (what it is, what it should be, what it may become etc), I'm referring to specific points *towards* that goal

**Comment by LoneWolfHT** [comment]
I'd say https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3A%22Supported+by+core+dev%22 works quite well for this

**Comment by Zughy** [comment]
> I'd say https://github.com/minetest/minetest/issues?q=is%3Aopen+is%3Aissue+label%3A%22Supported+by+core+dev%22 works quite well for this

Yes, but there is no order and it's quite scattered. I'd use that tag if I want to implement something because I know I'm basically scoring (if the code works), but it's not a roadmap. It's like having the map with all these useful dots, yet with no line connecting them

**Comment by SmallJoker** [comment]
The only planning that exists and will persist are
 * Meeting notes
 * Bugfix PRs for releases (i.e. milestones)
 * Spontaneous IRC discussinos

If someone is not sure about the concept, they may request feedback in an issue - or better - directly in the development IRC channel. It's hard to figure out what people expect from Minetest overall (see #3476), thus a roadmap as you imagined would be pretty much made of empty words.

After all this is volunteer work - I highly doubt there will be anything more than the three points listed above. There's no order. Similar topics are grouped using tasks. If there's a large project going on, it's also possible to add PRs and issues to this: https://github.com/minetest/minetest/projects

**Comment by rubenwardy** [comment]
The last few releases we have assigned purposes to - 5.3.0 was Android and collision, 5.2.0 and 5.1.0 were both formspec improvements. I'm not sure how best to organise or plan this

Also, see https://dev.minetest.net/TODO

**Comment by Zughy** [comment]
> It's hard to figure out what people expect from Minetest overall

Well, that's not true: you can ask them and then pick what you prefer. I literally provided a survey in the first post; which I spammed three times in three different occasions on IRC trying having people participating. But I'm not you: I'm pretty sure if any of you asked something similar, more people will take part to the survey

> The last few releases we have assigned purposes
And this is great, really. What I'm proposing with this issue is to try planning a few milestones ahead (ie. 5.4.0, 5.5.0 and 5.6.0)

**Comment by paramat** [comment]
Zughy, the repository projects section linked earlier somewhat does what you suggest.
We also have celeron55's roadmaps which are linked from the contributing file https://github.com/minetest/minetest/blob/f2c73def4b0c7fcfab521c0c54ada82a94b065c5/.github/CONTRIBUTING.md
And the TODO section on the wiki mentioned above.

I think we already have plenty of roadmap/major milestone organisation going on and do not need even more.
> What I'm proposing with this issue is to try planning a few milestones ahead (ie. 5.4.0, 5.5.0 and 5.6.0)

It is impractical and actually impossible to plan in detail that far ahead, this is fairly obvious. The way development progresses cannot be forseen beyond the next few weeks, so any specific long term plans of what each release will contain would inevitably quickly become invalid.
We have intended developments but those cannot be fixed to a particular time.

**Comment by ClobberXD** [comment]
This is another page I've bookmarked: https://dev.minetest.net/TODO. It's been edited by rubenwardy very recently, so I expect it to still be somewhat relevant.

**Comment by Zughy** [comment]
> It is impractical and actually impossible to plan in detail that far ahead

No one said "in detail". I literally said "even one feature per milestone". An example off the top of my head using the page linked by Clobber and my survey:

* 5.4.0: new main menu
* 5.5.0: MapGen: support for CaveGen and DungeonGen
* 5.6.0: first step for a big, long term goal
* 6.0.0: Entities API

So let's say 60 urgent issues come in the way while working on the 5.4.0. Perfect, let's solve them. How about people making useful PRs, no matter if they're related to the main menu or not? They're fine too, let's add them. But AT LEAST till the new main menu is not ready, 5.4.0 won't be shipped. Will it take weeks? Months? Who cares, but at least the community knows what's coming up next. Is the community asking for that entities API? Fine: the community knows it'll take time and it won't happen that soon

Clobber list and celeron55 roadmap prove my point: there is a huge map with all these useful dots but there is no line connecting them. You have the dots already, why not drawing a line? It's helpful both for the core devs and the users. Also, small psychological trivia: when people have too many choices (950+ issues and 160+ PRs), they can't *really* decide and also they're not as absorbed into the task as they would when they have no choice (deciding a milestone). Also they tend to be [more dissatisfied](https://invidio.us/watch?v=4q1dgn_C0AU)

**Comment by paramat** [comment]
Sorry, i should not have added the 'possible close' issue label.
My opinion has not changed though.
