### ISSUE TITLE
VS 2019 x86-portable action failing

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10053]
##### Summary
The "VS 2019 x86-portable" build action is failing for all recent PRs.

##### Steps to reproduce
Open a PR or just look at any recent (or recently updated) PR, for example #10003 - while [this commit](https://github.com/minetest/minetest/pull/10003/commits/0a0994c3784e340d72a40e2285297dcf7b8b9c32) compiled just fine, [this one](https://github.com/minetest/minetest/pull/10003/commits/6a07c647bdf20879bde0f8a6fc5f1dac4040c71f) didn't, despite the C++ code being left untouched.

**Comment by MoNTE48** [comment]
https://github.com/minetest/minetest/issues/10048
