### ISSUE TITLE
Wielditem entities are broken

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#10051]
##### Minetest version

Any after #10021 was merged

##### Summary
When switching between items of a similar type in your hotbar (node-node, tool-tool, etc) the texture doesn't update

##### Steps to reproduce
This GIF was made in Nodecore.
With Minetest Game's wield3d it's even worse. It doesn't seem to change at all unless the wielded item has texture modifiers, and then it only rotates the wielditem entity

![Peek-2020-06-17-19-20](https://user-images.githubusercontent.com/28972859/84971092-dca97280-b0d0-11ea-93c9-b50cf4e1fa4e.gif)
Pay attention to the hotbar and the item displayed in the player's hand

**Comment by Kimapr** [comment]
confirming this
