### ISSUE TITLE
Android: Failed to download from ContentDB

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10050]
##### Minetest version
https://github.com/minetest/minetest/commit/a1b444bb61e6c9dcb0581a8550fd7795a3555cec

Build: https://github.com/rubenwardy/minetest/releases/tag/5.3.0-rc1 

##### OS / Hardware
Operating system: Android

Samsung S7 Edge

##### Summary
Downloading from ContentDB fails with no error message

> ERROR[AsyncWorker-1]: downloading "https://content.minetest.net/packages/Wuzzy/mineclone2/releases/4085/download/" failed

This may be related to https://github.com/minetest/contentdb/issues/209

##### Steps to reproduce
* Attempt to download MineClone2

**Comment by rubenwardy** [comment]
It fails when checking the result file is good at src/gui/guiEngine.cpp:559, _before_ downloading

url = `"https://content.minetest.net/packages/Jeija/mesecons/releases/1771/download/"`
target = `"/storage/emulated/0/Minetest/tmp//MT_9871_MODNAME_mesecons.zip"`

**Comment by MoNTE48** [comment]
Who uses "tmp" instead of default cache dir???
