### ISSUE TITLE
ABM "time budget" interferes with game mechanics and cannot be adjusted

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#10068]
##### Minetest version

```
Minetest 5.2.0 (Linux)
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=0
USE_SOUND=0
USE_CURL=1
USE_FREETYPE=0
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: `Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2 (2020-04-29) x86_64 GNU/Linux`
CPU: `Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz`

##### Summary

ABM time "budget" is fixed and slows down the game mechanics, even while spare CPU is available.

##### Steps to reproduce
- Download a copy of the NodeCore Community server world at rsync://nodecore.mine.nu/world/
- Install NodeCore ALPHA from CDB, change the game in world.mt to nodecore_alpha.
- Load and run the world.
- Monitor logs and CPU usage.
- You may have to run this on a sufficiently resource-constrained VM before you start to see the performance issues (or run a server and get lots of people actively playing).

_Observed:_
The game starts dropping ABMs way early (you get messages like `WARNING[Server]: active block modifiers took 205ms (processed 163 of 643 active blocks)`) while CPU is still relatively low; on the actual server we start to see ABM loss when CPU is under half of 1 core.

_Expected:_
The game should use the resources it has available to keep the game running smoothly.

The time budget for any part of the game should expand dynamically to fill the available resources to keep the game running as correctly as possible.  At the very least, even if the budget is static, it should be tunable.  20% is also extremely low for what is supposed to be a sane default.

**Comment by rubenwardy** [comment]
Note that ABMs are intended to be unreliable, as they should be used for things that don't need to be exact. However, a large deviation from the requested interval is certainly a problem :)

**Comment by paramat** [comment]
@lhofhansl

**Comment by lhofhansl** [comment]
Just catching up on stuff. There's not magic. There was a (badly handled) budget before my latest change: After 200ms, there would long periods with no ABMs executed at all based on how far over the previous run was over the budget. I've seen paused of dozens of seconds before.

The latest change is not perfect, but at least it smooths things out.

The budget *is* hardcoded to 20% of a server step as it was before (but the new way makes it nice, you can lower the server step and will automatically process fewer ABMs per each step - but do so more frequently.)

I'm happy to make the per step budget configurable. There's absolutely no scientific basis to the 20%.

**Comment by lhofhansl** [comment]
Also note that the set of ABMs is randomly shuffled each time. So it won't process the same ABMs over and over and starve the others, eventually all ABMs are processed.

**Comment by lhofhansl** [comment]
Oh. Last note. The server step and ABMs are single threaded. The most you can get out of it is one core being utilized (some other things are multi-threaded, but the Lua stuff is not.)

So two options:
1. Just close this. All Lua in Minetest is single threaded anyway.
2. Make the allowed budget (per single threaded serverstep) configurable. Then folks can play around with it. (Still can't use more than one Core for this.)

**Comment by lhofhansl** [comment]
Any interest? Otherwise I'm gonna close. @Warr1024

**Comment by Warr1024** [comment]
Yeah, making the time budget configurable instead of fixed at 20% would be really helpful.  The problem isn't the inability to use multiple CPU cores, it's the inability to use a single CPU core.  Right now ABM processing can only use 0.2 cores.

**Comment by lhofhansl** [comment]
Cool. I'll create a PR.

**Comment by lhofhansl** [comment]
Created a PR. Note that ABM time is also taken away from map gen, etc.

**Comment by lhofhansl** [comment]
Closing since #10290 was merged.
