### ISSUE TITLE
ContentDB uninstall button slightly too small for translation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10069]
##### Minetest version
```
0a1181f7637adab6fe1ba5d3c09038912a06b37f
```

##### Summary
The button size in ContentDB is a little bit too small for the German translation.

Specifically, the “Uninstall” button (“Deinstallieren”). The button is just a few pixels short, so it's only a minor problem. Please fix this by giving more space.

BTW: ContentDB as a whole could be stretched fullscreen instead of leaving ca. 50% of screen width empty. But this true for most of the main menu, so it's semi-off-topic.

##### Steps to reproduce
* Activate German
* Open ContentDB
* Scroll to a thing that is already installed (or install one if nothing is installed)

**Comment by An0n3m0us** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/49789044/85697717-f1d66080-b6d1-11ea-878c-814015c5de43.png)

**Comment by Wuzzy2** [comment]
I can confirm. At this resulution, the word barely fits in. But if you lower the resolution just a little bit, it clearly bleeds over.

**Comment by An0n3m0us** [comment]
That is true, but then this issue is unfixable at any lower resolution:
![image](https://user-images.githubusercontent.com/49789044/85709940-a88c0e00-b6dd-11ea-8b18-f44120172314.png)

**Comment by LoneWolfHT** [comment]
Maybe change wording to 'remove', not sure how much less space that would take up

**Comment by ronoaldo** [comment]
What about having icons like a cross or trash icon instead of just text?

**Comment by ronoaldo** [comment]
I would like to start contributing to minetest. If possible, kindly give me some instructions on where the code is located and if possible some docs pointers. I already downloaded, compiled and ran the program from sources so I'm almost ready to get hands on coding.
