### ISSUE TITLE
Sneaking while on climbable node placed on ground triggers footstep sound spam

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#10065]
##### Minetest version

```
Minetest 5.3.0-dev-debug-495f7198e (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu Linux 20.04 LTS
CPU: Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary

Placing a climbable node such as a ladder at feet level and sneaking while on it triggers footstep sound spam. Placing it higher then foot level does not trigger it. Can be reproduced on devtest world too. 
Video: https://youtu.be/P9gLfvFEuEU

##### Steps to reproduce

1. Place a climbable node such as ladder at feet level
2. Use the sneak key while on it
3. Hear multiple footstep sounds while doing that (w/o using other keys at all)

**Comment by sfan5** [comment]
duplicate #1460
