### ISSUE TITLE
Android media takes a long time to load

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10061]
##### Minetest version
https://github.com/minetest/minetest/commit/495f7198ef8336048fd3a03a9705fe45dbd57574

##### OS / Hardware
Android 8,  Samsung S7 Edge

##### Summary
This is caused by #9107 

This issue can be fixed by:

* Disabling 64-bit on Android without breaking the Play Store's rules
* Some other workaround
* Fixing #9107

**Comment by sfan5** [comment]
duplicate #9107

**Comment by rubenwardy** [comment]
![image](https://user-images.githubusercontent.com/2122943/85062105-d1714800-b19f-11ea-9821-351c5dcfbd34.png)

**Comment by rubenwardy** [comment]
> duplicate #9107

The time spend in runTimeouts means this is probably true

**Comment by MoNTE48** [comment]
The issue is only in the ARM64 assembly.
Debug/release, gcc/clang, various versions of NDK. All options have been tried.

**Comment by sfan5** [comment]
Slow media loading is also reproducible on desktop depending on circumstances, not arm64-specific.

**Comment by MoNTE48** [comment]
@sfan5 "on desktop depending on circumstances" or on android arm64 always.

**Comment by rubenwardy** [comment]
It's taking me 10s of minutes to load a game. This needs to be fixed sooner than later

Will the Play Store allow us to cheat the 64-bit requirement, and ship a 32-bit NDK .so for 64-bit?
