### ISSUE TITLE
Allow switching between touchscreen and other input on Desktop and Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#10062]
## Problem

Now everything is bad. Minetest does not handle the presence of a hardware keyboard. Entering text is inconvenient.
Touch control is not hidden depending on the availability of a keyboard and mouse
The mouse pointer is not captured or hidden in the game.
The mouse pointer simply simulates finger presses...

Requires #10738 

## Solutions

To do something. Chromebooks seem to be popular in the USA.

## Alternatives

Even now, everything is fine, there are other more priority problems.

## Additional context

1) https://github.com/MultiCraft/MultiCraft/commit/bd13027ac336c60b497bd489293e2f33f44902c9
2) On Android, it seems you can't just hide the pointer. But starting with Android 7, possible to make it icon transparent.

**Comment by rubenwardy** [comment]
To achieve this, it might be an idea to split the idea of a touchscreen away from Android, and have an `enable_touchscreen` setting. This would allow ChromeBooks and other laptops with touchscreens to use the touchscreen interface or keyboard and mouse as they prefer.

A simpler way would be to allow normal controls when compiled for Android and just hide the touchscreen interface

**Comment by MoNTE48** [comment]
> split the idea of a touchscreen away from Android

And make the touch interface option available for Windows 10 tablets...

**Comment by sfan5** [comment]
> To achieve this, it might be an idea to split the idea of a touchscreen away from Android

This should also be done code wise. Touchscreen-relevant code should <b>not</b> be inside a `#ifdef __ANDROID__`.

**Comment by PrairieAstronomer** [comment]
I play minetest on a chromebook, and there are a few issues.
1. If you turn around too far, you can't go further, you have to move your mouse or finger in the other direction.
2. You can't use the number keys on the right, just the usual top row if you want to type numbers that aren't zero.

Other than that, I can play it just fine, I just need to keep view range low.
