### ISSUE TITLE
Available in Xbox and Playstation

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10066]
## Problem

Hi, I'd like be available to xbox
ie: I think it would be nice to see this awesome game in console
Ex: I play in pc with my brother in Android and I'd like to play with my uncle too. But he only likes to play in xbox

## Solutions

Makes minetest availabe to consoles video games like Xbox one and Playstation 4

**Comment by SmallJoker** [comment]
Gamepad support is incomplete. #4153

**Comment by rubenwardy** [comment]
Also note that console SDKs tend to be expensive and restrictive, requiring both approval and NDAs

**Comment by Df458** [comment]
Another important question is: Would a game capable of executing arbitrary code, even if sandboxed, pass cert?

As cool as it would be to have console support. I think it's infeasible.

**Comment by BruceMoustache** [comment]
> Also note that console SDKs tend to be expensive and restrictive, requiring both approval and NDAs

What if start a donation to get money to buy SDKs

**Comment by hecktest** [comment]
I suggest that you fix your uncle. Start by telling him that he's already using a weak, overpriced, locked down computer.

**Comment by paramat** [comment]
We do not have the time or resources to make MT available on gaming consoles.
