### ISSUE TITLE
Collision issues depending on bounding box size.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10078]
##### Minetest version
```
Minetest-5.3.0-dev and below.
```

##### Summary
If any of edge coordinates of the collision box > 3.0 value the box gets to be penetrable for players or entities. Also if any of edge coordinates > 2.5 it gets to be possible to go through the box`s corners. 

###### 1. First Issue.
1. Set any of coordinates (x, y, z) of any of two box edges to or above '3.0' or '-3.0' value. 
2. Try to break into any of the box sides.

###### 2. Second Issue.
1. Set any of coordinates (x, y, z) of any of two box edges to or above '2.5' or '-2.5' value.
2. Try to break into any of the box corners.

**Comment by SmallJoker** [comment]
#2612
