### ISSUE TITLE
Mesh faces look like transparent.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10079]
##### Minetest version
```
Minetest-5.2.0 -> Minetest-5.3.0-dev
```

##### Summary
Some of mesh faces look like transparent in-world in spite of applying 'Recalculate Outside' for outer faces and 'Recalculate Inside' for inner faces of the mesh operations in Blender. Also, I checked the faces look like transparent on both sides with no texture overlay:

_In Blender_
![Screenshot_20200620_215711](https://user-images.githubusercontent.com/25750346/85209645-467c8300-b342-11ea-8d80-74785224af3e.png)

_In-game_
![Screenshot_20200620_215622](https://user-images.githubusercontent.com/25750346/85209663-5e540700-b342-11ea-963d-ee631066c2c3.png)

**Comment by rubenwardy** [comment]
Check your normals

**Comment by Extex101** [comment]
An easy way to test how it would look in game is by pressing 'p' as long as you're in a version of blender that has bge

**Comment by Andrey2470T** [comment]
I checked the normals and after editing their in a needed direction it doesn`t change a look, though I did properly:
![Screenshot_20200622_132652](https://user-images.githubusercontent.com/25750346/85277730-8a7b9f00-b48c-11ea-8517-38ac753bf412.png)




> An easy way to test how it would look in game is by pressing 'p' as long as you're in a version of blender that has bge

I don`t know what you mean. Press 'p' in the game? Or if in blender this is quite other operation, 'Separate'.

**Comment by hecktest** [comment]
- Ensure that you are only using one material, assign it to all faces just to make sure
- Check vertex color, maybe that's contributing transparency
- Try another export format for comparison

**Comment by hecktest** [comment]
Oh, and another thing you can try is "Merge by distance", this can remove degenerate geometry that could prevent proper normal calculation. (recalc outside again after that)

**Comment by Andrey2470T** [comment]
> * Ensure that you are only using one material, assign it to all faces just to make sure
I`ve made sure I use the only one material.
> * Check vertex color, maybe that's contributing transparency
Not sure how to check. Couldnt you please explain?
> * Try another export format for comparison
Which? x3d?

**Comment by Andrey2470T** [comment]
> Oh, and another thing you can try is "Merge by distance", this can remove degenerate geometry that could prevent proper normal calculation. (recalc outside again after that)
I dont think I need for it. All volumetric meshes are closed and so normals should be calculated correctly.

**Comment by hecktest** [comment]
If this isn't skinned, you can try .obj for a start. That's a text format, irrlicht understands it, and you can inspect it manually to see if everything is right.

You check for vertex color in the mesh properties.

x3d is not .x in case you were wondering; 2.8 does not ship with an .x exporter but here's my port of the old one if you want (still has the same issues as the 2.7 version)
[io_scene_x.zip](https://github.com/minetest/minetest/files/4812743/io_scene_x.zip)

**Comment by hecktest** [comment]
Another important question, are the broken faces always the same, or do you get a different set after restarting Minetest?

**Comment by Andrey2470T** [comment]
Checked with obj exporter, it works properly. It`s strange because I used io_scene_b3d that was ported to blender 2.8.





> Another important question, are the broken faces always the same, or do you get a different set after restarting Minetest?

The same.

**Comment by Df458** [comment]
Out of curiosity, what version of io_scene_b3d are you using?

**Comment by Andrey2470T** [comment]
> Out of curiosity, what version of io_scene_b3d are you using?

v0.01

**Comment by Andrey2470T** [comment]
I downloaded from here: https://github.com/joric/io_scene_b3d and like this has the single version.

**Comment by Df458** [comment]
Can you try to repro with this one: https://github.com/GreenXenith/io_scene_b3d ?

**Comment by Andrey2470T** [comment]
This version works correctly, thanks!

**Comment by Andrey2470T** [comment]
No, it also doesn`t work, I just mistook.

**Comment by GreenXenith** [comment]
This is user error. Both the original and my version of the b3d exporter should work fine in this case (my fixes pertain to useless settings and broken selection exporting -- not related to this).

Your normals are not correct (which I can see from your screenshot). In Blender, switch to edit mode on the model, select all (A), and make normals consistent (ctrl+N or F3->Make Normals Consistent). Then re-export.

**Comment by Andrey2470T** [comment]
@GreenXenith yeah, it didn`t solve the problem:
![Screenshot_20200622_210750](https://user-images.githubusercontent.com/25750346/85320995-9e46f580-b4cc-11ea-8c89-f73f47ac4b2c.png)

**Comment by GreenXenith** [comment]
Please provide your blend file.

**Comment by Andrey2470T** [comment]
[bmw_fw.zip](https://github.com/minetest/minetest/files/4814933/bmw_fw.zip)

**Comment by NathanSalapat** [comment]
I see bad normals on the windows, and likely the problem with the panels around the wheels is that they are N-gons, try manually converting them into quads or tris. It looks like the exporter is messing that step up.

**Comment by GreenXenith** [comment]
Nathan is correct, the issue is with n-gons. Triangulating fixes the problem. This is technically more of an engine problem than anything else, since Minetest is supposed to triangulate meshes already -- but it sounds like it isn't doing so for b3d or something.

This isn't really a bug I guess, more of a missing feature. Triangulating in Blender is best modelling practice anyway. Secondary to that would be triangulating in the rendering engine. I will only add triangulation to the exporter if the feature is too difficult to implement in the engine.

**Comment by Andrey2470T** [comment]
Yes, that really fixes the problem. Henceforth I will triangulate the complex faces like those which in my model. Thanks much!
