### ISSUE TITLE
Wrong scaling in Mac OS 

### ISSUE THREAD

**Issue by bugbuka** [minetest/minetest#10074]
##### Minetest version

```

```

##### OS / Hardware

Operating system: macos
CPU: macbook pro 16, 2019

GPU model: AMD Radeon Pro 5300M 4 GB
Intel UHD Graphics 630 1536 MB
OpenGL version: 

##### Steps to reproduce

<img width="1025" alt="Screen Shot 2020-06-20 at 20 39 41" src="https://user-images.githubusercontent.com/4723950/85202160-ff3cc500-b336-11ea-9c8c-80f620cfbbe6.png">

**Comment by bugbuka** [comment]
[build.txt](https://github.com/minetest/minetest/files/4807882/build.txt)

**Comment by SmallJoker** [comment]
What exactly does not run? Minetest starts up, so is this issue mainly about the wrong scaling?

**Comment by bugbuka** [comment]
so is this issue mainly about the wrong scaling? => yes

**Comment by bugbuka** [comment]
any feedback?

**Comment by rubenwardy** [comment]
Duplicate of #10654
