### ISSUE TITLE
minetest.PLAYER_MAX_BREATH_DEFAULT change to 10 breaks mods

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10076]
##### Minetest version
```
a36c9c3e930608386b983ea76158793fe9d622f6
```

(5.3.0-dev)

##### Summary
a36c9c3e930608386b983ea76158793fe9d622f6 changed the value of `minetest.PLAYER_MAX_BREATH_DEFAULT` from 11 to 10.

`minetest.PLAYER_MAX_BREATH_DEFAULT` is official part of the Lua API because it is mentioned in `lua_api.txt`, so changing this value should NOT be done lightly.

This is a breaking change because mods depended on the special value 11 (or max+1, to be precise) to hide the breath bar. I think the breakage could have been avoided.
Namely, mods that overwrite the built-in breathbar but keep the default player breath number are screwed now unless they get updated to fix the breakage that was not their fault. Repixture is directly affected by this. It's possible that mods and other games are affected, but I did not analyze everything.

Sadly, the commit mixes two unrelated things into one, so a simple revert is not possible. The commit also contains a legit but unrelated bugfix, namely related to the scaling of the breath bar.

I ask you to undo the value change.

Since this issue reports a regression from 5.2.0, this should be marked as Blocker.

@ClobberXD

**Comment by sfan5** [comment]
What is the point of a named constant when modders rely on its exact value anyway? This is not a breaking change in any way.

> This is a breaking change because mods depended on the special value 11 (or max+1, to be precise) to hide the breath bar

Setting the breath value to breath max hides the bar just like before.
The only argument that can be made here is that you no longer have to set breath_max one higher than intended to get correct looking bar hiding behaviour, but it's not like that is not fixable.

**Comment by Wuzzy2** [comment]
It's not about relying on exactly on the value 11, but it's about the assumption that

`minetest.PLAYER_MAX_BREATH_DEFAULT` means that “breath at max, and hide breath bar” and `minetest.PLAYER_MAX_BREATH_DEFAULT-1` means “breath at max, do not hide breath bar”.

That was the old behavior. The new behavior is:

`minetest.PLAYER_MAX_BREATH_DEFAULT` “breath at max, and I'm not telling you whether you should hide the breath bar or not”.

That's a loss of information, and it is breaking assumptions. That's why I call it breaking change.

**Comment by sfan5** [comment]
That's not exactly correct.
`max-1` did not mean "breath at max", before the change the player effectively had one more breath bubble.
After the change `max` still means "do not hide breath bar", but since the hiding is delayed there is no way to tell if the bar is still visible or not.

But that doesn't make a difference in your case anyway. Repixture ships an old (modified) copy of builtin/statbars.lua, which only works with `breath_max == 11` since it uses the old hiding mechanism.
Setting the max to 11 was a workaround itself and there was no guarantee that it would stay.

**Comment by paramat** [comment]
Does not seem a blocker to me, but some mods might need adjustment, which seems acceptable for cleaning up the mess we had before.

**Comment by nerzhul** [comment]
we just fixed a very old constant bug, and yeah the side effect is it breaks mods which fixed the bug themselves, but it's needed at a point i think

**Comment by oilboi** [comment]
Why is breath even handled in the engine?

**Comment by Wuzzy2** [comment]
It's handled in the engine because it's simpler for everyone, but especially because it's lag-free since you need to detect if the player is in a drowning liquid or not. The second reason is because a ton of games and mods depend on it; removing it now would be very VERY wrong and would definitely require a major release (6.0.0). My opinion is that, even if you argue the current implementation is not ideal, current breath should NOT be removed from the engine if no equally good or better alternative is available. We have no such alternative.

But this discussion is off-topic.

**Comment by rubenwardy** [comment]
It's no more lag free than a Lua implementation. It's still server side, running at an interval

**Comment by Wuzzy2** [comment]
If you are serious about destroying breath, I suggest to open a new issue.

Back to topic: So is the new value for the global variable the accepted one, and you are not going to change it back?

**Comment by rubenwardy** [comment]
Back on topic: The value of PLAYER_MAX_BREATH_DEFAULT was not documented, neither was the hiding behaviour. The point of a named constant is to allow it to be changed, PLAYER_MAX_BREATH_DEFAULT is still the max breath before and after, it's just that they are both consistently 20 now

**Comment by oilboi** [comment]
> It's no more lag free than a Lua implementation. It's still server side, running at an interval.
> 
> No alternative exists because the engine supports it, implementing an alternative would be less than 300 lines.
> 
> Yes, we can't remove it before 6.0. But that doesn't make it suck less. It should never have been added as an engine feature

Cough cough cough cough https://github.com/oilboi/Crafter/blob/master/mods/drowning/init.lua

**Comment by SmallJoker** [comment]
The bubble counter contained the extra step (11) solely to hide the bar when it's full. Constants should not be adjusted to visuals, but visuals to the given values (now 10 steps of breath).
Updating mods to take the new, corrected value into account should be somewhat trivial. We could not fix some bugs if there weren't at least some tolerance from the modder's side.
Closing.
