### ISSUE TITLE
Server sending high amount of data

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#10088]
##### Minetest version

```
Client: 5.2.0
Server: 5.1, 5.2 (seems to be not important)
```

##### Summary
Server sends very high amount of data to a client only answering reliable packages and ignoring all others and sending no own stuff.
In extrem cases this can get very, very bad.
Bad means server sends a lot of data by default like on technic servers with high metadata changes
![grafik](https://user-images.githubusercontent.com/18502734/85304260-d4c04880-b4ab-11ea-909b-69371e7051bd.png)Just one client sending almost nothing -> 440mbit/s

##### Steps to reproduce
That's the complicated part:
Join using a client and than only answere to reliable packages. Changing stuff near by to trigger it is needed(Just go on a technic server with a lot of meatdatas changing very often)

So you ghost the normal client. I did it using a proxy you join throught which than cuts the connection and only answers to reliable packages.
Can send the script on request(Just don't want server owners to get problems for dosing others unwanted...)

**Comment by Lejo1** [comment]
Network Log(cut of about 100000lines... A lot of traffic):
[out.txt](https://github.com/minetest/minetest/files/4814245/out.txt)

**Comment by SmallJoker** [comment]
How about 5.3.0-dev? There were quite some changes in the networking part (mainly optimizations).

**Comment by Lejo1** [comment]
> How about 5.3.0-dev? There were quite some changes in the networking part (mainly optimizations).

CTF is 5.3.0-dev and it's same there, just less than on technic servers.

The [file](
https://www.file-upload.net/download-14152812/output.pcap.html) for @sfan5 
It also includes the normal client connection and the last part is the script.

**Comment by sfan5** [comment]
Wireshark shows lots of resends happening. Since you client code doesn't correctly ack packets, this is entirely expected behaviour.
![grafik](https://user-images.githubusercontent.com/1042418/85317922-756c3380-b4bf-11ea-9c6d-82d3c86f195d.png)

　
Unrelated to that, there are a lot of split packets which surely isn't good for overall server performance.

**Comment by BuckarooBanzay** [comment]
> Wireshark shows lots of resends happening. Since you client code doesn't correctly ack packets, this is entirely expected behaviour.

I had a deeper look into this and this behaviour does have some implications:
You can trick a remote server into sending you its full bandwidth worth of upload, which can be a residential line (clogged upload -> denial of service) or a VPS.
In the VPS case there are always traffic limits you can (as a client) exhaust in a matter of hours in the worst case!
This makes the whole serverlist potentially vulnerable to this kind of DoS attack... :confused:

**Comment by Lejo1** [comment]
> Wireshark shows lots of resends happening. Since you client code doesn't correctly ack packets, this is entirely expected behaviour.

True, but shouldn't there be a limit? A client just sending trash acks shouldn't be kept connected!

> Unrelated to that, there are a lot of split packets which surely isn't good for overall server performance.

Isn't this pretty much the same thing as they are also sent as reliable packages(requesting acks)?

A limitation is needed for resending packages. If you fail too much you just should get disconnect instead of getting spammed with packages.

**Comment by sfan5** [comment]
> True, but shouldn't there be a limit?

Sure. Currently only the explicit ping packets are used to track timeouts.
It would be possible to additionally consider failed reliable packet delivery as a timeout condition.

**Comment by KaylebJay** [comment]
> This makes the whole serverlist potentially vulnerable to this kind of DoS attack... :confused:

This is really bad.

**Comment by hecktest** [comment]
I think I know this... I've observed something like a client being choked with reliable packets, attempting to replay actions as old as a minute, after a temporary network hiccup on the server's part. The server recovered fine while the client was stuck and had to reconnect. Would this be the same thing?

**Comment by Lejo1** [comment]
Maybe, just that here the client triggers the spamming and keeps the connection alive by sending trash acks

**Comment by Lejo1** [comment]
@sfan5 where pretty much right, the main cause for it was that I counted the sequence numbers up for all channels and not for each channel on it one. I also sent all acks on the same channel back.

So we need to **only** reset the timeout if the received ack-package contained a valid sequence number

Anyway it will be needed to add a maximum resend limit for a reliable package.
