### ISSUE TITLE
CPU Usage Constantly 100-200% in Singleplayer

### ISSUE THREAD

**Issue by mmstick** [minetest/minetest#1008]
Latest daily developer builds on Ubuntu, as usual.
Occurs in minetest minimal with all graphics options disabled so mods and minetest_game is ruled out.
Tends to cause an extreme amount of lag as you begin building things in singleplayer.
Considering this is a 4GHz AMD FX-8120, that's quite a lot of CPU.

**Comment by nerzhul** [comment]
No news, and confirmed that it's not very actual, new builds are required.
If you always have this issue, please tell us.
