### ISSUE TITLE
mod_channel doesn't work

### ISSUE THREAD

**Issue by metacoma** [minetest/minetest#10087]
Hello, 

Client:
`Minetest 5.3.0-dev-e99415e0c-dirty (Linux)`

Server:
`Minetest 5.2.0 (Linux)`

##### Summary
I try to create an interaction channel between client and server, I decide to use mod_channel functionality but seems it doesn't work properly, on client-side I always get the channel is not writable.

##### Steps to reproduce
Server-side mod code: 
```lua
local mod_channel = minetest.mod_channel_join("xxx2")
minetest.log("mod_channel enable:  " .. tostring(minetest.settings:get("enable_mod_channels"))
minetest.log("Channel is writeable " .. tostring(mod_channel:is_writeable()))
```
Client-side mod code:
```lua
minetest.log("mod_channel enable:  " .. tostring(minetest.settings:get("enable_mod_channels"))

minetest.register_on_punchnode(function(pos, node)
  mod_channel = minetest.mod_channel_join("xxx2")
  if mod_channel:is_writeable() then
    mod_channel:send_all("preview talk to experimental")
    else
    minetest.log("channel is not writable!!!!!!!!")
  end

end)

```
I always got "channel is not writable" 

Also, example from https://github.com/minetest/minetest/blob/master/clientmods/preview/init.lua (client-side) and https://github.com/minetest/minetest/tree/083b285f4319c470f307f0b52f03a2fb68facd38/games/devtest/mods/modchannels (server-side) doesn't work too

**Comment by metacoma** [comment]
Looks like the problem in timings, code in below works (i need punch something twice)

```lua
minetest.register_on_punchnode(function(pos, node)
  if (mod_channel == nil) then
    mod_channel = minetest.mod_channel_join("xxx2")
    minetest.log("join to xxx2 channel")
  end
  if mod_channel:is_writeable() then
    mod_channel:send_all("preview talk to experimental")
    else
    minetest.log("channel is not writable!!!!!!!!")
  end

end)
```

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/4cb18d4874126b384ad5faa1b10a208c8fdce4db/src/network/clientpackethandler.cpp#L1555-L1559

The server must first accept the client's `mod_channel_join` request. `is_writeable` will be usable after the packet is received. As a workaround, put the actions into a queue which is then processed as soon the channel is writable (see `register_globalstep`).

**Comment by metacoma** [comment]
Thank you @SmallJoker

**Comment by metacoma** [comment]
I think I can propose a more elegant way to handle connect action, maybe it will be useful for someone.

server-side: 
```lua
local channels = {} 
minetest.register_on_joinplayer(function(player)
    local player_name = player:get_player_name()
    channels[player_name] = minetest.mod_channel_join(player_name)
    minetest.chat_send_player(player_name, "CONNECTED")
end)
```
client-side:
```lua
minetest.register_on_receiving_chat_message(function(message)
  if (message == "CONNECTED") then
    mod_channel = minetest.mod_channel_join(minetest.localplayer:get_name())
  end
end)
```
