### ISSUE TITLE
Do not join the game with broken shaders

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#10097]
##### Minetest version

```
Minetest 5.3.0-dev-d7a211389 (GNU/Linux)
```

##### OS / Hardware

Operating system: lubuntu 18.04
CPU: intel

GPU model: intel
OpenGL version: core profile 4.5, version string 3.0

##### Summary

If the shaders are broken, Minetest shows everything in dark and gives an error message.
I think nobody wants to play game with broken shaders, so it could be better to abort joining and go back to the main menu if shaders are broken.
In the settings menu it is then possible to disable the shaders.

##### Steps to reproduce

* Change the nodes fragment shader so that it cannot be successfully compiled 
* Join a world in Minetest

**Comment by SmallJoker** [comment]
Possible solution:
https://github.com/minetest/minetest/blob/3a6dfda358112e2fb5d6f887a1a1e936eacddadd/src/client/shader.cpp#L797
https://github.com/minetest/minetest/blob/3a6dfda358112e2fb5d6f887a1a1e936eacddadd/src/client/shader.cpp#L819

1) Include the `addShaderMaterial` return value in `ShaderInfo`
2) Abort loading in `Client` when one of them failed.

**Comment by paramat** [comment]
> If the shaders are broken, Minetest shows everything in dark and gives an error message.
I think nobody wants to play game with broken shaders, so it could be better to abort joining and go back to the main menu if shaders are broken.

This seems a bizarre and bad idea :-1: 
We should not start a precedence of exiting to menu for bugs in MT, this would add unnecessary complexity.
Besides, it is far more useful for bugfixing andn testing if it does not auto-exit a world when a bug occurs.
If a bug occurs, an error message is enough, a player will then know an error has occurred and will exit the world anyway, so your suggestion has no benefit.

**Comment by hecktest** [comment]
I'm not a fan of how this is being handled right now either; the shader compilation error is dumped to stdout and chat, so after you see the red gibberish on the top of your screen, you need to look in the terminal in order to see what actually went wrong.
I want a formspec to tell me what happened, just like how lua errors are shown.

And since a failed shader can't actually draw anything, what use there is for a client to stay connected in this broken state? Isn't it better to tell the player up front that a shader is broken, instead of dumping the player into this cryptic blue box of death?

**Comment by rubenwardy** [comment]
I think exiting with a clear user error is much better user experience than some red text and a blood world

**Comment by dcbrwn** [comment]
Maybe not exiting, but falling back to a basic material is better idea. This way developers won't be forced to launch minetest in "special" mode to test their work and players wont be kicked off because of (probably hardware-specific) bugs.

**Comment by paramat** [comment]
I have no objection to improving the feedback when shaders do not compile, such as a clear error message.
I was wondering whether the visual result of broken shaders is useful to see for future bugfixing? Or are the resulting visuals always completely useless to see?
The user will exit to menu when the bug happens anyway, so auto exiting a world is unimportant.
Users of MT are not the only important people, developers fixing bugs are too, working on MT is already hard enough =)

**Comment by HybridDog** [comment]
> I was wondering whether the visual result of broken shaders is useful to see for future bugfixing? Or are the resulting visuals always completely useless to see?

I think when the shaders do not compile, the visual result should always be the same independent of the shader code; broken shaders means that the code of the respective glsl file is unused in the game. I assume that similar visual results can be achieved by simply removing the shader compilation from the code, and I doubt that the results are useful for bugfixing.

> The user will exit to menu when the bug happens anyway, so auto-exiting a world is unimportant.
Users of MT are not the only important people, developers are too.

Now and then some user with broken shaders asks a developer why the shaders look weird (If I remember correctly, this has happened often); exiting to the menu with an error message could avoid this.
If a developer forgets a semicolon in the glsl code and Minetest does not auto-exit, he/she would need to wait until the joining has finished before exiting to the main menu or somehow abort the rest of the joining manually. Exiting automatically can save time, especially when there are many typos in the shader code and the error messages do not reveal all of them at once.

**Comment by dcbrwn** [comment]
Just kicking user out to main menu seems a bit harsh. Automatically turning shaders off for the current session would be more friendly. Minetest supports that, and there are people who even like the game that way better.

**Comment by HybridDog** [comment]
Disabling the shader setting automatically while an error message is shown is fine for me if Minetest does not render with broken/not loaded shaders but with the Irrlicht default (or whatever is used when shaders is disabled) instead.
