### ISSUE TITLE
There should be a setting to force glass blocks to draw all sides

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#101]
The title pretty much says it all.  In normal use, a glass block used as a window or light wall is transparent of course, but also all six sides of the block are generally visible (if distorted by the shape of the glass).  I have yet to see a glass block that managed to make the far sides invisible.

In the game there should be an option to make the game always draw all six sides of a glass block.

In the current state, glass blocks only show the sides closest to the player, which makes walls with any kind of corner look weird.  This screenshot should explain it:

http://digitalaudioconcepts.com/vanessa/hobbies/minetest/screenshot_3587399990.png

Note how the top side of the top block in the corner is of course displayed along with its neighbors, while the two blocks that I placed directly below it are hidden from view.  If it weren't for the black selection box, this glass wall looks like it's made of some kind of 2-d glass panes rather than solid blocks.

**Comment by nerzhul** [comment]
Is this issue already relevant ?

**Comment by VanessaE** [comment]
Probably not anymore, and possible to fake it with nodeboxes.
