### ISSUE TITLE
fullscreen custom resolution not working

### ISSUE THREAD

**Issue by CDGDVD** [minetest/minetest#10108]
##### Minetest version

```
5.2.0
```

##### OS / Hardware

Operating system: Windows 10
CPU:
i7 2630qm

GPU model: GT 540M
OpenGL version:
3.1
##### Summary

I'm trying to run minetest in 720p for more fps... but it doesn't go actually go full-screen :/
##### Steps to reproduce

go to your minetest.conf and add:
```
screen_w = 1280
screen_h = 720
```
then this happens:
![image](https://user-images.githubusercontent.com/37805980/85860568-4c011f80-b7bf-11ea-8a35-6319548ba9da.png)

**Comment by SmallJoker** [comment]
Minetest does not change the screen resolution, though you can add or change following setting to render a smaller scene, which is then upscaled.
https://github.com/minetest/minetest/blob/7be082f9a8bb6bd46c226d7ef4c42f0fd9fe7314/minetest.conf.example#L577-L582

In Minetest, "Fullscreen" is equal to "borderless" starting at position (0,0). It might make sense to change the screen resolution to cover this case -> would be a feature request.

**Comment by paramat** [comment]
CDGDVD,
But, is your monitor resolution 1280x720?
If not, there is no bug here, the custom game window size is exactly that, in monitor pixels, it does not scale up the game window to be fullscreen, it is not 'custom fullscreen resolution'.

**Comment by SmallJoker** [comment]
No answer for over a month. Closing.
