### ISSUE TITLE
Block breaking animation stuck after using pause menu

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#10107]
##### Minetest version

```
Minetest 5.3.0-dev-debug-7be082f9a (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu Linux 20.04 LTS
CPU: Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary

Hiting a pause key while mining (w/o releasing the mouse button) and returning to game shows a stuck animation frame of block breaking overlay. Moving mouse away from affected block removes the overlay. Happens in both devtest & full mt game. Video of devtest: https://youtu.be/5LLdKcNB7Vs
##### Steps to reproduce

1. Load a devtest/full/etc world
2. Try to mine a solid block
3. Hit pause key before block breaking animation finish and block is mined
4. Hit pause key again to return to the game
5. Observe the block break animation being stuck with last frame before pause shown on block all times (bug)
6. Move the mouse away, stuck frame dissappears, block under cursor is hilighted properly (normal behavior)

**Comment by SmallJoker** [comment]
#5611
