### ISSUE TITLE
Connected textures don't work properly

### ISSUE THREAD

**Issue by ZatroxDE** [minetest/minetest#10104]
##### Minetest version

```
5.2.0
```

##### OS / Hardware
I guess this will happen anywhere

##### Summary
The connecting of glass textures (for example) does not work properly if the block uses param2.
Example: the stained glass mod uses param2 to save the color of the glass. I made a version with connecting textures (https://github.com/ZatroxDE/stained_glass), but there are two problems:

1. the glass only connects horizontally not vertically
2. the glass connects even though the colors are different (not really a bug)

**Comment by sfan5** [comment]
duplicate of #9542
