### ISSUE TITLE
Player model size becomes a gigantic if attach to object.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10102]
##### Minetest version
```
Minetest-5.3.0-dev-80d9e9c18
```

##### Summary
Surprisingly, if you attach to object your model size will be significantly increased. My code doesnt change either a player model, nor texture, nor visual size. It just attaches and change eye offset.

![Screenshot_20200625_214821](https://user-images.githubusercontent.com/25750346/85781336-3f80b680-b72e-11ea-8846-744e78c3ca52.png)

**Comment by SmallJoker** [comment]
#419
