### ISSUE TITLE
minetest.get_us_time overflow

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#10105]
_Slackware Linux 14.2 x86_

get_us_time() will overflow and reset to zero every now and then. Had it happen several times in one day.
This should probably be documented, or ideally caught and worked around.

Update: This actually happened on a Linux server, not Windows. Oops.

**Comment by hecktest** [comment]
Oops, the admin actually gave me a x86 machine. Correcting.
Now the overflow doesn't seem all that bizarre.

**Comment by hecktest** [comment]
Somebody please correct the OP, because Microsoft® Github™ is completely fucked and even the edit button is broken.

**Comment by appgurueu** [comment]
What the actual heck? Documenting this is not a fix at all.
