### ISSUE TITLE
LuaEntity:get_yaw() randomly returns nil

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10117]
Using minetest 5.2.0, luaentity:get_yaw() returns nil sometimes. Sometimes it does not. I have to make sure that my value is 0 instead of nil to prevent errors. It was not like this in previous versions.

**Comment by rubenwardy** [comment]
The methods on objects will return nil when the object has been deleted. You should avoid using deleted objects.

Also see #9528
