### ISSUE TITLE
[Meta] Transparent donations: Liberapay account for Minetest

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10116]
## Problem

There is no donation profile for Minetest on any site. On the main site there is a direct PayPal donation button for celeron55, and a couple core devs have their own Patreon account (ruben and paramat), but that's it

## Solutions

I think it'd be nice to have a donation page for Minetest. Both for transparency and for being reached more easily (also meaning more possibility to earn something). My first choice is [Liberapay](https://liberapay.com/) because:
* is open source and run by a non-profit
* charges no fees
* supports both PayPal and Stripe

## Alternatives
There is KoFi too but their privacy policy is [quite arguable](https://more.ko-fi.com/privacy), and Patreon charges about [5-6%](https://support.patreon.com/hc/en-us/articles/360027674431) in fees.  

It can also be self-hosted on the official site [as Krita does](https://krita.org/en/support-us/donations/) but I guess it'd mean more work

**Comment by rubenwardy** [comment]
We don't have a legal body to accept donations, currently. I've been wanting to do this for a while, as it decentralises things away from celeron55, allowing an non-profit to own the infrastructure. Above paying for infrastructure, I'm not sure what good more donations would be. We're a relatively small project, and so will not be able to gain enough to hire anyone to work on Minetest.

I try to be transparent with my donations - the amount is public, as are my expenses

**Comment by hecktest** [comment]
Other than paying for the website and master server, everything else can be done with bounties if you really want to throw money at developers.
Lumping it into one generic donation box increases the chances of the money being spent on things you didn't want.

**Comment by mnh48** [comment]
If I remember correctly, you don't need a legal entity to accept donation on Liberapay?

You can just create a team for Minetest, then invite the devs as members of the team. Team is not a legal entity, it's just a way to split donation, it by itself don't hold any money. The donation received via that team will be split based on the amount set by team members and go to each members' own personal bank accounts.

**Comment by runsy** [comment]
Money for developers, easy.

**Comment by rubenwardy** [comment]
> The donation received via that team will be split based on the amount set by team members and go to each members' own personal bank accounts (Stripe) or balance (PayPal).

I don't think this is an especially good way to do it, it doesn't help further the project that much. Bounties or full-time developer would be much better

**Comment by paramat** [comment]
The current personal donation routes are transparent, you know for sure the exact individual destination of the donation. A centralised donations route is no more transparent. 

I agree with rubenwardy that a centralised donations route is only good for supporting general MT infrastructure, not for giving donations to developers.
Trying to decide how to split centralised donation money between individual developers will be a very difficult and unpleasant headache that is best avoided. The current individual donation routes avoid this headache and seem optimal.

So for now, things seem fine, having celeron55's donation button, for MT infracstructure, on the MT donations page.
No hurry for a change as celeron55 still pays for all MT infrastructure, perhaps this will change in future.

**Comment by rubenwardy** [comment]
> No hurry for a change as celeron55 still pays for all MT infrastructure, perhaps this will change in future

To clarify:
celeron55 hosts the forums, the wikis, and the minetest.net domain
sfan5 hosts the serverlist, I host ContentDB

See https://www.minetest.net/get-involved/#reporting-issues

**Comment by hecktest** [comment]
Who runs the master server?

**Comment by Mte90** [comment]
Maybe use [opencollective](https://opencollective.com/) or https://sfconservancy.org/ that can give the umbrella support to gather donation?
