### ISSUE TITLE
Make Node Metadata fields private by default

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10127]
## Problem

Currently, you need to opt-in to making node meta private. The vast majority of node metadata doesn't need to go to the client - only `infotext` and `formspec` does. This will cause unnecessary data being sent to the client, including entire map blocks (there's still an issue to fix this somewhere)

## Solutions

Make node meta private by default, add `:mark_as_public(name)`, and make `infotext` and `formspec` public by default.

I don't think this would break anything, practically, as existing public fields won't be being used on the client unless they have one of those few keys. Having the ability to manually whitelist variables will be useful in the future for CSM access

**Comment by SmallJoker** [comment]
> I don't think this would break anything

Signs that use in-line `${text}` placeholders in the formspec, to name one.

**Comment by rubenwardy** [comment]
Ahh, I forgot about that feature

**Comment by rubenwardy** [comment]
I can't see that feature documented anywhere in lua_api.txt, which means that support for it doesn't need to be maintained

**Comment by BuckarooBanzay** [comment]
@rubenwardy wouldn't that make client-side mapsaving totally unusable? There are quite a few mods out there that use the `owner` field (`protector`, chests-mod, etc) and the `travelnet` mod for example stores stations and network in the metadata.
As far as i understand this would make those fields unavailable in the client "backups".

**Comment by Warr1024** [comment]
If we're worried about backwards compatibility, we could have an API for toggling this, e.g. minetest.set_default_meta_private(true) or minetest.set_meta_public({infotext = true, formspec = true, default = false}) or something.  It could then be a game/mod decision whether to do this or not, and such packages will need to be responsible for the consequences of their own choice.

Currently I am _already_ doing this for NodeCore, and it's working fine so far:
https://gitlab.com/sztest/nodecore/-/blob/master/mods/nc_api/nodemetahack.lua

**Comment by HybridDog** [comment]
Why is this closed?

**Comment by rubenwardy** [comment]
Because it's not possible without breaking backwards compat
