### ISSUE TITLE
'is_visible = false' property doesn`t make an attached player invisible in third-person view

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10124]
##### Minetest version
```
Minetest-5.3.0-dev-80d9e9c18
```

##### Summary
It happens when player is attached.

##### Steps to reproduce
1. Attach player to something.
2. Set `player:set_properties({is_visible=false})`
3. Toggle the third-person view.

**Comment by SmallJoker** [comment]
Invisible objects cannot be attached, hence it's not unexpected that Minetest either forces visibility or detaches the affected object.

**Comment by Andrey2470T** [comment]
But why can they not be invisible when attached? Is it hard to implement?

**Comment by SmallJoker** [comment]
> https://github.com/minetest/minetest/blob/7be082f9a8bb6bd46c226d7ef4c42f0fd9fe7314/src/client/content_cao.cpp#L582-L587

Not too difficult to implement, but you'd not only need transparent textures but also do special handling to render the "invisible" objects correctly, so that they're really invisible.

**Comment by oilboi** [comment]
Why not just have a sprite which is 1 pixel of nothing as a visual?

**Comment by LandonAConway** [comment]
Then what is the point of this property? If it is not doing what it suggests, and nobody is using it, and the core devs don't want to make it do what it suggests, then why not just rid of it? I wondered this too about a week ago after modifying a mod that makes players invisible.

**Comment by sfan5** [comment]
The property does what it says, just not when attachments are involved for reasons explained above.

**Comment by hecktest** [comment]
Why is the object being deleted if this line also exists?
https://github.com/minetest/minetest/blob/0a1181f7637adab6fe1ba5d3c09038912a06b37f/src/client/content_cao.cpp#L1034

**Comment by hecktest** [comment]
> 
> 
> Why not just have a sprite which is 1 pixel of nothing as a visual?

Fillrate.

**Comment by rubenwardy** [comment]
This is clearly a bug, regardless of the implementation reason

**Comment by rubenwardy** [comment]
closing in favour of more general issue: #12403
