### ISSUE TITLE
Reshowing formspec prevents receiving events

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10126]
##### Minetest version
```
5.2.0
5.3-dev
```

##### Summary
Formspecs which are reshown using `minetest.show_formspec` don't receive events (button presses).

##### Steps to reproduce
Register a form and reshow it (e.g. show it inside a globalstep). Register a corresponding `on_receive_fields` function. Notice that even if pressing a button, the button field is not sent.

**Comment by SmallJoker** [comment]
For whatever reason you could possibly run into this issue - please check that the mouse button is also released in the same formspec. Also enable the profiler to figure out whether the client is just laggy due to re-building formspecs nonstop.
Just don't do this.

**Comment by v-rob** [comment]
Can't reproduce.  Might be the same internal issue as #10201.

**Comment by SmallJoker** [comment]
No reply from the author for longer than a month. Closing.
