### ISSUE TITLE
'minetest.is_nan' is broken!

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10121]
##### Minetest version
```
Minetest-5.3.0-dev-80d9e9c18
```

##### Summary
If a passed number to `minetest.is_nan` is NaN actually (you know it e.g. from debugging), it won`t return true. If you check so: 'v ~= v', the way will work fine instead. In my case it was -nan.

##### Steps to reproduce
1. Make sure your number is NaN.
2. Try to call `minetest.is_nan` with passed as its arguments that value.
3. Now try to check via `number ~= number` way.

**Comment by rubenwardy** [comment]
Probably compiled with fast math

Weird how that's even a function, though

**Comment by oilboi** [comment]
Hahaha, what the. Why is this a function?

**Comment by HybridDog** [comment]
> Why is this a function?

@nerzhul wrote: [i need it because core engine itself should not crash like a coward because a mod owner has forgotten this line.](https://github.com/minetest/minetest/pull/7380#discussion_r191439692)

**Comment by rubenwardy** [comment]
Such BS

**Comment by oilboi** [comment]
Now I'm even more confused :(

**Comment by sfan5** [comment]
This can be fixed by removing `-ffinite-math-only` from the optimization flags:
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 3d6d1b0ea..07ce3697a 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -752,8 +752,8 @@ else()
 
        # Use a safe subset of flags to speed up math calculations:
        # - we don't need errno or math exceptions
-       # - we don't deal with Inf/NaN or signed zero
-       set(MATH_FLAGS "-fno-math-errno -fno-trapping-math -ffinite-math-only -fno-signed-zeros")
+       # - we don't deal with signed zeros
+       set(MATH_FLAGS "-fno-math-errno -fno-trapping-math -fno-signed-zeros")
 
        set(CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG ${RELEASE_WARNING_FLAGS} ${WARNING_FLAGS} ${OTHER_FLAGS} -Wall -pipe -funroll-loops")
        if(CMAKE_SYSTEM_NAME MATCHES "(Darwin|BSD|DragonFly)")

```

But since `-ffast-math` was the old default, this also means that it should have been broken since the day it was added.

**Comment by Zughy** [comment]
Uhm, is the function useful at all? Like, where's the difference from doing `if type(number) == "number" then ...` ? Also, it's not called anywhere internally, so can't it be simply removed?

**Comment by rubenwardy** [comment]
A NaN number still has a type of "number". It's a specific value of the number

**Comment by Zughy** [comment]
Right. Still, trivia thing, the call before this line is useless as it's called inside readParam too
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_object.cpp#L898

**Comment by Andrey2470T** [comment]
This is a excessive function and should be removed. You can check for whether given number is NaN by an easy condition: 'if number ~= number then'.

**Comment by appgurueu** [comment]
> This is a excessive function and should be removed. You can check for whether given number is NaN by an easy condition: `if number ~= number then`.

Just do:

```lua
function core.is_nan(num) return num ~= num end```
