### ISSUE TITLE
"Exit to menu" button causes Minetest to close/crash

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#10137]
##### Minetest version

```
5.3.0-rc2 (Windows 64-bit)
```

##### OS / Hardware

Operating system: Windows 10 (64-bit)
CPU: AMD Ryzen 7

##### Summary
In the 5.3.0 [release candidate](https://forum.minetest.net/viewtopic.php?f=18&t=24935), pressing the "Exit to menu" button causes the program to exit/crash unexpectedly. The issue does not seem to occur when I compile from the latest master on Win64.

Nothing useful is printed to debug.txt:
```
ACTION[Main]: World at [C:\games\minetest-5.3.0-rc2\bin\..\worlds\testworld]
ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:52544.
ACTION[Server]: singleplayer [127.0.0.1] joins game. List of players: singleplayer
ACTION[Main]: Server: Shutting down
```

##### Steps to reproduce
Download the release candidate from the forum, create a world, then exit using "Exit to menu."

**Comment by v-rob** [comment]
"Exit to OS" and Alt-F4 also crash the game and no settings are saved.  Lua crashes also crash Minetest.

**Comment by sfan5** [comment]
If it doesn't affect [these builds](https://forum.minetest.net/viewtopic.php?f=42&t=1523) it's fine since those are the ones that also go into release.

**Comment by SmallJoker** [comment]
Could you please run the binaries in windbg to try to figure out whether it was a proper shutdown or crash (access violation).

**Comment by random-geek** [comment]
The problem is not present in the latest of sfan5's builds (a2199bf). I also installed WinDbg and ran the broken executable, this is what it gives me when I try to exit:

```
(49f4.525c): Unknown exception - code e24c4a02 (first chance)
(49f4.111c): Unknown exception - code e24c4a02 (first chance)
(49f4.111c): Unknown exception - code e24c4a02 (first chance)
(49f4.111c): Unknown exception - code e24c4a02 (first chance)
(49f4.111c): Unknown exception - code e24c4a02 (first chance)
(49f4.111c): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify timestamp for C:\games\minetest-5.3.0-rc2\bin\libwinpthread-1.dll
minetest+0x6f8cd5:
00af8cd5 8b5908          mov     ebx,dword ptr [ecx+8] ds:002b:00000008=????????
0:015:x86> g
(49f4.111c): Access violation - code c0000005 (!!! second chance !!!)
wow64!Wow64pNotifyDebugger+0xded0:
00007fff`96dfcce0 c644242001      mov     byte ptr [rsp+20h],1 ss:00000000`0fa1e450=00
0:015>
```

I don't really know how the program works, so this is all I can provide for now...

**Comment by sfan5** [comment]
It turns out that this only affects the 32-bit build (there was no 64-bit build linked in the forum post), but it *does* affect normal release builds so we have a problem now.

**Comment by hecktest** [comment]
This actually happens in 64 bits *if* the server we're trying to leave has dropped the connection first. (or simply crashed)

**Comment by sfan5** [comment]
That sounds like a different bug.
