### ISSUE TITLE
Texture Packs - Add support for overriding special_tiles

### ISSUE THREAD

**Issue by Df458** [minetest/minetest#10132]
## Problem
`override.txt` allows texture packs to override node textures, primarily the `tiles` field. However, certain node drawtypes use a secondary field, `special_tiles`, in order to provide additional textures. It is currently impossible to override these texture slots on nodes.

To my knowledge, this affects the following drawtypes:
- `glasslikeliquidlevel` - Liquid texture
- `allfaces_optional` - Texture used when 'simple leaves' is enabled
- `plantlike_rooted` - The plant drawn above the 'root' node
-  `flowingliquid` - Undocumented, seems to provide top/side textures?

## Solutions

The only viable solution that I see is to add support for replacing the `special_types` field from a texture pack. I see a couple possible ways of doing this:
- Provide special_tiles_1, special_tiles_2, etc. targets to allow texture pack makers to replace specific entries in the table (simple and 'forward-compatible' with new drawtypes, but not particularly user-friendly)
- Provide custom target names for the affected drawtypes, with names that make the purpose of the replaced texture clear

Both options have their benefits and drawbacks and they aren't really mutually exclusive, but I think we should probably just pick one to keep things simple.

## Alternatives

The only real alternative is to do nothing, and let texture pack makers try to persuade mod authors to change their nodes in a way that permits them to be retextured properly. IIRC, the method to do this is really dirty and not ideal for code quality (and also requires the modder to care enough to make the change). I don't see it as an ideal or even particularly viable solution.

**Comment by Df458** [comment]
I should also make this clear--having added features to `override.txt` in the past, I'm fully prepared to implement the PR for this. I'm starting with an issue both to ensure that this would be accepted and to determine which of the two available options would be preferred.

**Comment by sfan5** [comment]
> Provide special_tiles_1, special_tiles_2, etc. targets to allow texture pack makers to replace specific entries in the table (simple and 'forward-compatible' with new drawtypes, but not particularly user-friendly)

This would be my preferred option.
