### ISSUE TITLE
Deprecate HUD API, support HUD formspecs

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10135]
## Problem

The only way to currently add elements is using the fairly limited HUD API. Proper layouting is hardly possible and there are few elements using rather "unclean" syntax. On top, those elements are not interactive.

## Solutions

In the meanwhile, formspecs have *dramatically* improved. There currently are various layouting options, many pre-built components, and the syntax is IMO acceptable. Very likely formspecs will continue to improve. Formspecs also are interactive and pretty much ready-to-use.

I therefore propose **HUD formspecs**:

```lua
player_ref:show_hud_formspec(formspec)
```

Those would be show on-screen to the client, with no offset, being capable of taking up the entire screen if needed. Buttons and other interactive elements would not be disabled, allowing mobile users interactions without gameplay interruption. To be able to offer a proper mobile experience requires the client to notify the server whether a touchscreen or a keyboard is being used.

## Alternatives

Extend the current HUD API, clean it up, add layouting options, all of which would be too much work and duplicate formspec code whatsoever...

## Additional context

Somehow related to the requests regarding custom keybinds (#8437), as HUD formspecs would allow interactive onscreen buttons for mobile users.

**Comment by LoneWolfHT** [comment]
Would be neat if keybinds were controlled entirely game-side.

**Comment by v-rob** [comment]
I've considered this myself.  First off, this really isn't a good idea with the current formspecs since they are static and cannot be modified collaboratively by multiple mods at a time nor modified at runtime except by rehowing the entire formspec.  They don't support custom z-indexes.  Also, they don't support scalable units besides the coordinate, which is fine for a rectangle in the middle of the screen, but not stretching across the entire screen.  Interactive elements like buttons would make no sense on desktop where the mouse is bound to the window.  Lastly, they don't support some HUD elements like statbars.

Certainly, if formspecs are improved to fix these problems, this sounds like a plausible idea.  But for the present, I think that this is completely infeasible.

**Comment by Df458** [comment]
Yeah, I'd also chalk this up as "good idea, but still before its time". Once we have some of the major long-term features such as layout containers, partial updates/databinding, etc. merging the two APIs will start looking more viable. For now though, I think it's best to leave things as-is.

**Comment by rubenwardy** [comment]
Big :-1: :-1: for this

This would be a good idea when formspecs are replaced, but spreading the crap that is formspecs further is not a good idea

**Comment by appgurueu** [comment]
> Big -1 -1 for this
> 
> This would be a good idea when formspecs are replaced, but spreading the crap that is formspecs further is not a good idea

But you prefer to keep the crap that is the current HUD API instead?

**Comment by rubenwardy** [comment]
Yes, because that would need to be kept anyway

**Comment by hecktest** [comment]
This idea is very touchscreen biased, it makes little sense on PC unless you had a mouse lock button.
Drawing and input features in SSCSM would obsolete this.

**Comment by paramat** [comment]
I agree with rubenwardy. Not a good idea when formspecs are messy and have an uncertain future, and i doubt they are up to the task compared to dedicated HUDs.
:-1:

**Comment by SmallJoker** [comment]
A single string (in `show_hud_formspec`) is not useful for mod interactions. HUDs may be added and removed at any time from its parent mod. Also scaling and alignment would need to be handled differently, introducing more issues for various DPI settings and might overload small screens.

Request rejected by multiple core devs.
