### ISSUE TITLE
Minetest installed by flatpak shows incorrect worlds path

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10149]
##### Minetest version

```
Minetest 5.2.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/app/share/minetest"
```

##### OS / Hardware

Operating system: Linux Mint 19.3 64 bits
CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz  (8th Generation)

##### Summary

Minetest log of world created path is wrong
```
2020-07-03 14:12:54: ACTION[Main]: World at [/home/bruce/.minetest/worlds/Unnamed82055]
```
Checking path:
`ls /home/bruce/.minetest/worlds/Unnamed82055`
Output:
`ls: cannot access '/home/bruce/.minetest/worlds/Unnamed82055': No such file or directory`

##### Steps to reproduce

1. Install minetest using flatpak:
`flatpak install flathub net.minetest.Minetest`
2. Run it in terminal:
`flatpak run net.minetest.Minetest`
3. Create a world
4. Click on **Play Game**
5. Check the output of the terminal and look for something like:
`2020-07-03 14:12:54: ACTION[Main]: World at [/home/bruce/.minetest/worlds/Unnamed82055]`

**Comment by sfan5** [comment]
What do you expect Minetest to do here? It is transparently sandboxed by the runtime (Flatpak).

**Comment by BruceMustache** [comment]
So where is my .minetest folder?

**Comment by sfan5** [comment]
I've never used Flatpak myself but Google says the folder is at `/home/YOUR NAME/.var/app/net.minetest.Minetest/.minetest/`

**Comment by BruceMustache** [comment]
thanks
