### ISSUE TITLE
Setting the expected map block size to 1 in the client can crash a server

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#10155]
I only experienced this once, and I do not remember what server it was on, but I was messing with the block size source code and I joined a server on accident and then it was no longer listed as online in the server list when I reverted my changes. I'm also unsure if this is server env or lua api without expectations of a player instantly becoming nil as the join the world.

**Comment by sfan5** [comment]
> I was messing with the block size source code

Which line(s) exactly?

**Comment by oilboi** [comment]
https://github.com/minetest/minetest/blob/master/src/constants.h#L77

**Comment by SmallJoker** [comment]
Not supported. It must be >= 0 or you'll run into division by zero errors.

**Comment by oilboi** [comment]
Well that's very funny, even though it's not supported I was able to crash the server that I'm not running with my client

**Comment by rubenwardy** [comment]
A client should not be able to crash the server

**Comment by oilboi** [comment]
It was 1, I didn't want to check again after what happened
