### ISSUE TITLE
Allow laying textures on mesh polygons bilaterally.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10159]
For nodes and entities. It may be achieved by setting a new definition property `allow_bilateral_texture = true` if 'mesh' drawtype used.

**Comment by rubenwardy** [comment]
I have no idea what this means. Do you mean disable backface culling?

**Comment by Andrey2470T** [comment]
No, I meant to allow to render textures on mesh faces bilaterally. Currently the engine renders on them only unilaterally. The usecase of that is if your model has internal hollows and they must be seen outside. Otherwise, they would look just transparent. Making an additional copy of the outer mesh polygons obviously leads to creating more number of vertices, especially many if the model has complicated shape is what negatively will affect the performance.

**Comment by rubenwardy** [comment]
That looks like a term you've made up, what's the OpenGL or common name for the technique?

**Comment by rubenwardy** [comment]
> I have no idea what this means. Do you mean disable backface culling?

Here's backface culling off (left) and on (right):

![image](https://user-images.githubusercontent.com/2122943/86540786-78bfe000-beff-11ea-90f9-82966557ce7e.png)

**Comment by Andrey2470T** [comment]
I`ve searched out that property with that term name in lua_api.txt, I didn`t just know what`s this and that`s why omitted before. Thanks for the demonstrative pics to understand!
