### ISSUE TITLE
Entity moveresult: collides = true but collisions = {}

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10158]
##### Minetest version
```
5.3-dev
```

##### Summary
`moveresult` sometimes returns `collides = true` but `collisions = {}`

##### Steps to reproduce
Register some bouncy entity and write an on_step with `assert((not moveresult.collides) or #moveresult.collisions > 0, dump(moveresult))`

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/da71313e1df3326c2b9ddb410b963ec25682319e/src/collision.cpp#L526-L527

or

https://github.com/minetest/minetest/blob/da71313e1df3326c2b9ddb410b963ec25682319e/src/collision.cpp#L566-L567

Should probably just be documented (not a bug)

**Comment by appgurueu** [comment]
Well, you usually need the old velocity, and a common way of obtaining it is to use `moveresult.collisions[1].old_velocity`
