### ISSUE TITLE
Major memory leak when joining several worlds/servers without closing the client

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#10157]
##### Minetest version

```
5.3.0-dev
```

##### OS / Hardware

Operating system: Xubuntu 20.04
CPU: Intel Dual Core

GPU model:
OpenGL version:

##### Summary

If you leave your client open and connect to multiple servers or start multiple singleplayer worlds the memory usage will rise each time. Only some memory gets freed when exiting to the main menu.

Example: When opening the client memory usage on my PC is 90 MB and after joining and leaving my singleplayer world with *just* MTG 10 times in a row Minetest eats up over 200 MB of RAM.
##### Steps to reproduce

1. Join any world/server from the client
2. Leave that world/server
3. Join and leave the same world/server or another (doesn't matter) over and over again
4. Watch the RAM usage rise

**Comment by appgurueu** [comment]
Can confirm, when joining IhrFussel's server for instance, it jumps from ~60 MB to ~700 MB. After leaving, it stays at ~700 MB.

**Comment by oilboi** [comment]
I can make the client hit 7 gb then it does a memory flush and goes to 0 crashing the whole game

**Comment by MoNTE48** [comment]
This is a very old bug. He was at 0.4 as well, although probably not so much.

**Comment by SmallJoker** [comment]
#7235
