### ISSUE TITLE
Mods increase loading time to 30 min

### ISSUE THREAD

**Issue by Adnan1091** [minetest/minetest#10168]
##### Minetest version
5.3.0 Armv8

##### OS / Hardware
Operating system:Android 10

##### Summary
When you enable mods.The loading screen get stuck on media... screen and it does not move unless you wait a very long time.It happened after i moved to 5.3.0.This was not happened to me in 5.2.I even did clean install but it doesn't help.It takes 1.5 hours to me to load a new world with mods.After that,it does not get stuck unless you add a new mod.

**Comment by sfan5** [comment]
This is unfortunately a known issue #9107
