### ISSUE TITLE
Mod loading time profiling

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10167]
## Problem

Short load times are desirable to quickly restart the server in the event of crashes or memory/processing leaks (increasing lag).

## Solutions

The profiler should support loading time profiling and record each mod's loading time.

## Alternatives

Mods *could* do this themselves, but this belongs into the built-in profiler.

**Comment by sfan5** [comment]
The engine already prints load times with `--verbose` you just don't get a nice list of them.

**Comment by appgurueu** [comment]
> The engine already prints load times with `--verbose` you just don't get a nice list of them.

Good enough. `minetest --worldname modlib-test --server --verbose 2>&1 | grep "loaded after"` does the job:

```
$ minetest --worldname modlib-test --server --verbose 2>&1 | grep "loaded after"
2022-08-16 13:55:04: INFO[Main]: Mod "strictest" loaded after 1 ms
2022-08-16 13:55:04: INFO[Main]: Mod "dbg" loaded after 1 ms
2022-08-16 13:55:04: INFO[Main]: Mod "modlib" loaded after 3 ms
```

and so forth
