### ISSUE TITLE
Add per-ItemStack point range

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10164]
## Problem

This is a problem. As a modder, I and probably many others as well, have wanted a way to change the range (distance for digging and placing nodes, and punching) of the hand tool at runtime. However, it can only be set by overriding the hand tool while loading a mod. I know this isnt something a whole lot of nodders may take advantage of, but it could definitely help with custom games.

## Solutions

For stacks and stack meta refs, you can use

ItemStack:get_toolcapabilities()
 and
ItemStackMetaRef:set_toolcapabilities(tool_caps)

IT would be nice to also have

ItemStack:get_range()
 and
ItemStack:set_range(range) --or nil to reset it to default

## Additional context

The point of this is also to be able to change the range of an ItemStack at runtime.
I know that you could just create a tool that has a farther range but this is very different and does not solve the problem. Please consider this. Thanks.

**Comment by SmallJoker** [comment]
This would best be moved to the toolcaps. It fits well to the other params and could be changed using the existing API functions.

**Comment by rubenwardy** [comment]
Things that don't have toolcaps may also have range, however, such as wands that can't dig nodes

**Comment by hecktest** [comment]
Range also affects entity pointability.
