### ISSUE TITLE
Add '/lua' command under 'server' priv

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10163]
## Problem

Downloading several mods for simple server commands is annoying. We could implement a chat command called '/lua' where you can execute lua code that can also use the code from the minetest API and from loaded mods.

This would be very useful on online servers and would prevent the need to shut servers down in certian situations.

## Solutions

Add a chat command called '/lua'. The server privilege is required.

## Additional context

A great example of what Im looking for is this mod here.
https://wiki.minetest.net/Mods/LuaCmd

**Comment by hecktest** [comment]
It's a pretty dangerous feature. If a mod can provide it, is it necessary in core?

**Comment by FriendlyGamer** [comment]
> It's a pretty dangerous feature. If a mod can provide it, is it necessary in core?

I agree it's seems too dangerous to include at the core level and if a mod could easily do it then i can be easily added per owner basis.

**Comment by SmallJoker** [comment]
For server admins I can imagine that it's helpful to debug, but opens a wide door for people to abuse the server privilege given by careless/unknowing admins.
I think this is best installed as a separate mod when needed. That mod could also be adjusted to fit the needs - either a textarea to copy&paste, or text-only for access through CLI.

**Comment by paramat** [comment]
sfan5 and i agree with SmallJoker, closing.
