### ISSUE TITLE
Non-English Characters are not working in the Snap-Version

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#10178]
##### Minetest version

```
5.3.0
5.2.0
```

##### Summary
I can't write characters like öüä or € when using the Minetest-Snap

##### Steps to reproduce
Just try it :)

**Comment by sfan5** [comment]
You should report this bug to whoever distributes the Snap.

**Comment by Lejo1** [comment]
Oh, Ok thought it was kind of official:
snapcrafters/minetest/issues/10
