### ISSUE TITLE
RUN_IN_PLACE build broken on macOS, only works as bundle

### ISSUE THREAD

**Issue by syimyuzya** [minetest/minetest#10170]
##### Minetest version

```
Minetest 5.3.0 (OSX)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

(AFAIK when I first tried to build 5.1.0 the problem was already present)

##### OS / Hardware

Operating system: macOS Mojave 10.14.6
CPU: 1.4 GHz Intel Core i5

GPU model: Intel HD Graphics 5000 1536 MB
OpenGL version: 4.1

##### Summary

When built run-in-place (`-DRUN_IN_PLACE=1`) on macOS:

- Keyboard input not working (looks like it cannot acquire keyboard focus)
- Cannot enter native fullscreen mode

These problems are only present with a _run-in-place_ build. The _package build_ (minetest.app without `RUN_IN_PLACE`) works fine (either by `open minetest.app` or by `minetest.app/Contents/MacOS/minetest`), but only the system-wide user directory (`$HOME/Library/Application Support/minetest`) can be used, which makes it hard (if not impossible) to have multiple versions of Minetest or multiple profiles (games, mods) at the same time. Developing games and mods would also be much harder without a run-in-place build for testing.

##### Steps to reproduce

Just compile and run Minetest according to the README (with or without minetest_game):

```
cmake . -DRUN_IN_PLACE=1
make -j4
.bin/minetest
````

Then:

- Try maximizing the window (the window fills the desktop, but does not enter native fullscreen mode as minetest.app does)
- Try creating a world (world name or seed cannot be typed in)

**Comment by syimyuzya** [comment]
Update: After some more experiments, I have also found a _very weird_ hack as a workaround:

- Rename `bin` to `MacOS` (or copy/symlink)
- Create a `Contents` folder at the same level as the minetest top directory (or just rename the minetest top directory)
- Run `MacOS/minetest` in terminal from anywhere outside the `MacOS` directory

This is basically _tricking_ macOS, making it think the executable is in a bundle.

**Comment by bugbuka** [comment]
i got the same issue. 
and after applying the above workaround 
i got following error
![image](https://user-images.githubusercontent.com/4723950/115121246-24947100-9fe4-11eb-9fe1-e753aadc76e0.png)

**Comment by sfan5** [comment]
You're running Minetest 5.2.0 with minetest_game 5.3.0 (or later), this is not supported. Only install matching versions.

**Comment by bugbuka** [comment]
After changing both minetest, and minetest_game to v5.4.1, applying above workaround, it is runnable now, thanks
