### ISSUE TITLE
Failed to write to file

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [minetest/minetest#10176]
##### Minetest version

```
Minetest 5.3.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10
CPU: AMD E1-2500 APU with Radeon HD Graphics 

##### Summary

Found a bug that crashes the game in a single player world. Not sure what is causing it. Seems to only happen when player is idle. Here is the error:
```
2020-07-11 22:44:07: WARNING[Server]: Failed to write to file: C:\Users\chris\Downloads\minetest-5.3.0-win64\bin\..\worlds\Dinos\env_meta.txt
2020-07-11 22:44:07: ERROR[Server]: An unhandled exception occurred: Couldn't save env meta
2020-07-11 22:44:07: ERROR[Server]: In thread 8:
2020-07-11 22:44:07: ERROR[Server]: /home/stefan/mt-build/build/minetest_64/minetest/src/server.cpp:7d: run: A fatal error occurred: Couldn't save env meta
```
##### Steps to reproduce

I have a bunch of mods enabled, so it may be triggered by one of them. But it is going to be a pain trying to figure out which one is causing it. Until I figure out which one, I won't be able to explain well how to reproduce it. This has happened 2 or 3 times, with the common factor being the player is idle and probably the unknown problematic mod. I am assuming it is a mod that is causing this issue, since I am not seeing it in a world where there are no extra mods, just the minetest game mods. I have only seen it while the player was in a village, so one of the village mods I have may be causing it, idk. I haven't been able to reliably reproduce it.

To help figure this out, what could potentially cause the above error?

**Comment by SmallJoker** [comment]
Relevant code - last touched 4 years ago:
https://github.com/minetest/minetest/blob/d80def5bbf58c9ddf1ab3d62e2e456b8dc824c98/src/serverenvironment.cpp#L646-L651

Please add the minetest\worlds\ path to your Antivirus whitelist to ensure it does not cause this strange behaviour.

**Comment by HeyITGuyFixIt** [comment]
@SmallJoker I have no idea what I'm looking at, I am not familiar with C++ all. The only antivirus I have is Windows Defender (or whatever Microsoft is calling it now). I'm not aware of any way to add it to a whitelist, but I'll look into it.

**Comment by HeyITGuyFixIt** [comment]
If that is the relevant code (which it appears to be) why is it referring to [server.cpp](https://www.github.com/minetest/minetest/tree/master/src%2Fserver.cpp)?

**Comment by SmallJoker** [comment]
@HeyITGuyFixIt That's because `server.cpp` calls to the function in `serverenvironment.cpp` but does not handle the exception, hence the crash.

**Comment by rubenwardy** [comment]
Needs reproducing

**Comment by xeruf** [comment]
Had this error on debian because I copied in my world with wrong permissions, fixed with:

    sudo chown -R Debian-minetest:games /var/games/minetest-server
