### ISSUE TITLE
Properly document all known non-working features

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#10172]
## Problem

There are a number of features in the newly released 5.3 that are documented as working yet the functionality is broken.

#9445 Calling get_bone_position causes unwanted side-effects
#10032 Setting use_texture_alpha only renders translucency when alpha channel is > 50%
#10017 Changing the scale of an object restarts its animation
#9529 Line-breaks in HTML-like element render as a new paragraph instead of a new line

## Solutions

I think with each stable release, all features that were reported as non-working should be documented either directly in `lua_api.txt` or within an ancillary release notes file.

## Additional context

As a mod developer, I find it rather concerning that end-users are are expected to problem solve why documented features do not work as described and/or as expected.

**Comment by SmallJoker** [comment]
Rather than proposing PRs to fix the bugs, the spent time would go into documenting bugs. This is IMO not the right approach here, especially because all issues are tracked here on GitHub. The only tricky part is to provide a generic reference from the documentation to this issue tracker - filtering by a specific tag to list all features that are reported to have a bug (also closed ones).

**Comment by sorcerykid** [comment]
To clarify, I'm not proposing that all issues be mentioned, but only those features in lua_api.txt and menu_lua_api.txt that are known to be broken at the time of release, yet nonetheless are still officially documented as working.

This could be as simple as adding a special tag next to the feature description, denoting it as non-functional. Perhaps there could even be a cross-reference to the GitHub issue via a footnote. I think that would require minimal investment of dev time, and it would save a lot of headaches for modders.

**Comment by paramat** [comment]
> only those features in lua_api.txt and menu_lua_api.txt that are known to be broken at the time of release, yet nonetheless are still officially documented as working.

This clarifies the suggestion and it now makes more sense.
I am concerned about the workload created in having to document every known bug at every release. Boring task too.
When encountering a problem a modder can already search MT issues on GitHub to confirm if a feature has bugs, so i am not sure this is worth doing.

**Comment by Zughy** [comment]
I agree both with SmallJoker and Paramat, this issue should be closed and people should focus on fixing the related issues instead
