### ISSUE TITLE
Right-clicking a node with sneak does not work as intended.

### ISSUE THREAD

**Issue by neoh4x0r** [minetest/minetest#10179]
commit: 28f5b55643080e07a89af5a2e21ffadf3781be19 **Dont call on_rightclick() if sneak is pressed**
```
function core.item_place(itemstack, placer, pointed_thing, param2)
	-- Call on_rightclick if the pointed node defines it
	if pointed_thing.type == "node" and placer and
		not placer:get_player_control().sneak then
```
**Breaks mods with nodes that have an on_rightclick handler and will do something special when sneak is pressed.**

**Comment by SmallJoker** [comment]
Don't wield a node to trigger that callback. `sneak`-place is reserved for nodes, thus mods should not use that to implement special functions.

**Comment by paramat** [comment]
That commit does not 'break mods', as that commit was added in 2013, so mods will already be written accordingly.
So this is a request to remove that restriction.
It seems that commit was added to allow 'sneak-placing' a node onto another node without triggering a rightclick callback.
For example, the MTG chest where holding 'sneak' prevents the rightclick callback that opens the chest and so allows a node to be built onto a chest.
Many mods use the sneak-place feature to avoid the rightclick callback, so we cannot revert that commit, it would break a lot of mods.
