### ISSUE TITLE
Confirmation dialog broken on Android

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10175]
##### Minetest version
```
5.3.0
```

Posted on behalf of this user: https://twitter.com/SoBrasov/status/1282035117662273536

##### OS / Hardware
Operating system: Android 10
CPU: ?

##### Summary

> [there was] a major issue on Android 10 - usernames and passwords could not be submitted from any text field. With the latest update this was fixed. Except for new users which need to confirm the password. And that field has the same issue.

##### Steps to reproduce
Unknown

**Comment by MoNTE48** [comment]
IMHO this dialogue should be removed.
It is better to ask someone who fixed touch support in volume / keys dialogs...

**Comment by SmallJoker** [comment]
I don't see any Minetest version mentioned there. Are they really using 5.3.0?

**Comment by MoNTE48** [comment]
I fixed text input on Android 10. 
Only confirmation dialog, possibily, broken. Not tested 😬

**Comment by MoNTE48** [comment]
Tested. The inputfield of this dialog does not receive text. The Register / Cancel buttons work. Android 10.
(_"Unconfirmed bug" label can be removed..._)

**Comment by rubenwardy** [comment]
> I don't see any Minetest version mentioned there. Are they really using 5.3.0?
> 
> EDIT:
> 
> > usernames and passwords could not be submitted feom any text field.
> 
> So this also applies to all inputs, not just the confirmation dialogue.

It's 5.3.0.

Editing text was broken on all Android 10 in 5.0, it's now been fixed. The tweet mentions an update

**Comment by SmallJoker** [comment]
How about the password change dialogue? I think the same issue would persist there.
To test this, an existing account (or one created on PC) has to be used. I can't believe this is limited to a single dialogue when other ones use the same API.

**Comment by MoNTE48** [comment]
Input field in password change dialogue broken, too...
Tested on Android 10. Worked on Android 8.1. I can check it later... Or you will be faster than me. The fix is pretty simple.

**Comment by MoNTE48** [comment]
Good evening 🍺
https://github.com/minetest/minetest/pull/10182

**Comment by BruceMustache** [comment]
I can reproduce that on my moto g1 Android 10
