### ISSUE TITLE
Incorrect error message for missing PostgreSQL connection string

### ISSUE THREAD

**Issue by Hawk777** [minetest/minetest#10187]
##### Minetest version
```
Minetest 5.3.0 (Linux)
BUILD_TYPE=Gentoo
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=0
USE_CURL=0
USE_FREETYPE=0
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/minetest/locale"
```

##### OS / Hardware
Operating system: Linux
CPU: VM

##### Summary
I wanted to migrate to PostgreSQL for authentication, to consolidate all my Minetest data. I ran `minetestserver --migrate-auth postgresql`. I received the error message `Set pgsql_connection string in world.mt to use the postgresql backend`. However, that settings was already set! The actual problem was that I needed to set `pgsql_auth_backend`, not `pgsql_backend`. The error message should show the proper setting name based on which kind of database backend failed to initialize.

##### Steps to reproduce
Set `auth_backend = postgresql` but do not set `pgsql_auth_backend`. Start the server.

**Comment by Taywee** [comment]
I hit this recently too.  Doing an internet search for "Set pgsql_connection string in world.mt to use the postgresql backend" only shows this issue.  It appears the relevant settings are `pgsql_connection`, `pgsql_player_connection`, and `pgsql_auth_connection`, at least on Minetest version 5.4.1.
