### ISSUE TITLE
Android app lost age rating, it's now PEGI 12

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10188]
Minetest was PEGI 3 on Google Play, Google has overridden that rating and made it PEGI 12. This happened sometime between 5.0.1 and 5.3.0-dev.

Minecraft is PEGI 7.

Remember that PEGI only applies to singleplayer, and does not rate multiplayer. I'm unsure of whether it applies to downloadable content, but it probably does.

@nerzhul will need to share the information on why this decision was made, it will have been sent to him via email.

**Comment by MoNTE48** [comment]
You need to pass an assessment and answer some questions after each major update. This is the responsibility of the developer.

**Comment by rubenwardy** [comment]
We've already done that, Google override the rating

**Comment by paramat** [comment]
Seems reasonable considering the variety of in-game downloadable content.
Of course, depending on what game is downloaded it can be suitable for much younger ages, but a parent/guardian can and should judge and organise that.

Perhaps we could add some text to the Play store page explaining that it is cautiously rated according to the variety of downloadable content and that it can be suitable for much younger ages according to what games/mods are used.

**Comment by rubenwardy** [comment]
I resubmitted the rating form the other day, which gave PEGI 3.

The review came back today with the rating being overridden back to PEGI 12:

![image](https://user-images.githubusercontent.com/2122943/87822637-b27ed800-c869-11ea-9aa1-73d2e85ae7d8.png)

![image](https://user-images.githubusercontent.com/2122943/87822684-cb878900-c869-11ea-812a-f7d121a23647.png)

The report says that they've found mild to moderate violence with blood. This may be for multiplayer servers or for ContentDB - although, from what I can see, user-generated and online content _shouldn't matter_. I wonder if the app was reported or there's an erroneous automated check

**Comment by FriendlyGamer** [comment]
> This may be for multiplayer servers or for ContentDB - although, from what I can see, user-generated and online content _shouldn't matter_. I wonder if the app was reported or there's an erroneous automated check

That the only way(s) they are downgrading it as such as even mods like Mobs Redo modules can be literally bloody if server admins like me don't disable that "feature". Thus...  

Someone or their parents reported the content _because there are such in servers/in ContentDB_ even though the app store does not _asses such_.

**Comment by hecktest** [comment]
Only 12? Challenge accepted.

**Comment by paramat** [comment]
See https://pegi.info/what-do-the-labels-mean
PEGI 12 is suitable by their own criteria, and seems about right to me, i would not want 7-12 year olds being allowed unsupervised access to MT online content. The next rating down is PEGI 7 which would be too low in my opinion.
Perhaps we got away with PEGI 7 in the past because there was no CDB and MT was primarily judged on vanilla Minetest and similarity to MC.
I cannot see how downloadable online content can be ignored in their assessments, as it is the vast majority of the MT experience.
Apparently some mods have blood splatter particles. Then there are FPS type gun mods.

**Comment by LoneWolfHT** [comment]
Minecraft Bedrock, the version that is compatible with mobile devices, also has downloadable content https://www.minecraft.net/en-us/marketplace/

**Comment by FriendlyGamer** [comment]
> i would not want 7-12 year olds being allowed _unsupervised_ access to MT online content.
That's on the parental end and I would say that have no bearings on this scope of the issue.  

It's up to the parent to figure out what game(s) to allow their childern, if they can view the ContentDB and/or on server(s). Not Minetest or it's devs.

**Comment by LoneWolfHT** [comment]
Minetest and its devs need to set up a default that assumes minimal parent involvement from what I can tell

**Comment by rubenwardy** [comment]
> Perhaps we got away with PEGI 7 in the past because there was no CDB and MT was primarily judged on vanilla Minetest and similarity to MC.
> I cannot see how downloadable online content can be ignored in their assessments, as it is the vast majority of the MT experience.

I still don't think it's cdb. It's more likely that someone reported it based on online gameplay

A few days ago, I added content ratings to ContentDB. This means that everything with moderate violence is hidden from the Android client, including any guns or blood splatters

**Comment by numberZero** [comment]
MultiCraft is 3+ though. Did they disable ContentDB?

**Comment by rubenwardy** [comment]
They just haven't been noticed yet, I guess

**Comment by numberZero** [comment]
They have more downloads than Minetest. But they have ads...

**Comment by paramat** [comment]
> That's on the parental end and I would say that have no bearings on this scope of the issue.
It's up to the parent to figure out what game(s) to allow their childern, if they can view the ContentDB and/or on server(s). Not Minetest or it's devs.

No. The PEGI rating informs parents whether or not they should be concerned about supervising access to a game, this is why it is important for MT to attempt to get it set it suitably. If it is set too low, a parent might (and many will) assume they can not worry, leading to no supervision and a child too young accessing unsuitable material.

If the choice is PEGI 12 or PEGI 7, PEGI 12 is more suitable for general MT material.
A parent can always supervise and decide MT is suitable for a child under 12, which is another reason why a rating slightly too high is better than a rating slightly too low.

**Comment by numberZero** [comment]
@paramat Then report MultiCraft as rated too low. Such huge difference in rating has a reason, and I’m pretty sure that’s not the content.

**Comment by Zughy** [comment]
> The PEGI rating informs parents whether or not they should be concerned about supervising access to a game

According to this, every game with an online component should be at least PEGI 12, as you can always find someone swearing against people or telling you that they love to do gymnastic with your mum. Minecraft is currently PEGI 7, while Multicraft is PEGI 3.

The PEGI 12 rating here is absurd, as by default MT(G) doesn't even have creatures to slain. It completely lacks the PvP component, meaning it's actually even more peaceful than Minecraft. Also, as Ruben stated, 

> everything with moderate violence is hidden from the Android client, including any guns or blood splatters

Honestly, this looks like shadowbanning. I think it's time to appeal and see

**Comment by MoNTE48** [comment]
Just a clarification.
1) There is no CDB in MultiCraft.
2) All mods used are checked to match the rating.
3) There is no violence against human-like characters. (You cannot damage NPCs. This is the main problem with the rating.)
4) All servers undergo strict moderation before being included in the MultiCraft server list. Any server that violates the rules is immediately removed from the list until the problem is resolved. The main servers also have very strict chat filtering.
