### ISSUE TITLE
PR #8770 breaks formspec

### ISSUE THREAD

**Issue by syimyuzya** [minetest/minetest#10180]
## Problem

#8770 makes a meta field `nil` when set to 0 using `set_int`, but often we DO want a "0" to show up in a textbox, showing that _it is a number field with value = 0_ instead of just a blank textbox telling the player _nothing_.

A workaround to make the "0" show up in a form is to test the value and `set_string(<name>, "0")` when updating the meta field, which makes no sense because we have to treat 0 _as a special case_ every time. If we _really_ want to delete a field in some cases, testing the value and `set_string(<name>, "")` does the job just fine, and it shows that _this is a special case_ and _value type is no longer integer_.

## Solutions

Just revert that change.

## Alternatives

Or consider adding a function to the API for _explicitly_ removing a meta field.

## Additional context

See PR #8770.

**Comment by SmallJoker** [comment]
@Lejo1. Relevant report.

Thanks for the report. I feared this would happen somewhere, even though chances seemed very low. I highly recommend modders to use development builds - in this case the issue hadn't reached a stable build (5.3.0) if ti were reported earlier.

**Comment by Lejo1** [comment]
Hmm,
This is more problematic than I thought.
In the end either the mods have to add extra code to remove unused 0's
Or do an fix to prevent this.

As it breaks the stuff, I agree, reverting would be the best solution.
About stable-build: Could this be simply done in the next patch version or will we have to wait for 5.4.0?

**Comment by sfan5** [comment]
Deleting the meta value when it's set to zero is a convenience feature and can be reverted just fine.

> Could this be simply done in the next patch version or will we have to wait for 5.4.0?

Unless there are any breaking problems, there will not be a 5.3.1 and any fix for this will only make it into 5.4.0.

**Comment by tuedel** [comment]
> Unless there are any breaking problems, there will not be a 5.3.1 and any fix for this will only make it into 5.4.0.

I'd actually consider this issue a "breaking problem". It changes previous engine behavior in a way that breaks stuff in several commonly used mods (e.g. digtron, technic) and makes temporary workarounds necessary in order to maintain their functionality, for no real gain.

**Comment by syimyuzya** [comment]
> I thought it returned 0 when the value was nil?

Yes, and Lua's string concatenation works fine with numbers, but what is unintuitive is that `get_int`/`set_int` must be used _exclusively_ without any `get`/`set` on the same field, e.g. one of the gotchas when doing so is that `get` won't always give the string representation of the number previous set with `set_int`.
