### ISSUE TITLE
document minetest.register_item()

### ISSUE THREAD

**Issue by Tcll** [minetest/minetest#10191]
I'm trying to work on creating a 3D arm model (b3d file), but it seems there isn't any documentation for the function to tell me how to implement it... :/
is it the same as `minetest.register_craftitem()` with the same item definition, or are there differences in attributes or where items are registered to compared to craftitems??

**Comment by rubenwardy** [comment]
A craftitem is an item. Tools and nodes are also items.

This function is intentionally not documented as you should use register_node, register_craftitem, or register_tool instead

**Comment by Tcll** [comment]
alright, so would registering a hand count as a tool??

I still think it should be documented though just to provide the info
but it should probably also be documented that it's **recommended to use the frontend functions instead**

**Comment by rubenwardy** [comment]
You shouldn't even know that it exists unless you're digging around the built-in code. We don't document internal functions, it should probably just be made into a local function.

The difference between items and nodes, craftitems, and tools should be documented. You can use any of those three types for a hand, but you'll want to use a node for a 3d hand. The difference between tools and craftitems is that tools can only ever stack to 1 despite their stack max, and can have wear

**Comment by Tcll** [comment]
> You shouldn't even know that it exists unless you're digging around the built-in code.
as someone designing a highly simplistic API for my own program, this is hardly a good approach :/
everything should be documented so people can get the most info they need for the API they're using...

but anyways, thanks for the tip.

**Comment by SmallJoker** [comment]
It might help to mention publicly accessible functions in the lua_api as "Not documented on purpose, for internal (builtin) use only". Until now I don't think this was a problem - only use the documented API.

**Comment by Tcll** [comment]
> unless you're digging around the built-in code

also I want to add, I found it by logging the attributes of `minetest` since an API reference pretty much doesn't exist for anything other than player, object, and luaentity instances, and even that's sparse.
(how am I supposed to mod if I don't even know half of what I'm supposed to use)

sure I know how to build a definition for registration, but a static "definition" and an active "instance" are 2 entirely different things

but getting back to the note of `register_item`
what harm would it do if an advanced mod developer knows how to use it??
is it because you don't have a solid interface yet that you're so protective of it??

personally I feel that if you provide it in a frontend language like LUA, that it **should** absolutely be documented.
if it's not a solid function like the more abstract functions that use it, then it should be warned as such.

**Comment by rubenwardy** [comment]
The risk is that we can remove it or change its behaviour without warning, as it's undocumented

**Comment by Tcll** [comment]
okay fine you got me there
I could see possible optimization improvements from removing it and provided the abstractions in C/++
but at the same time, regarding what you just tipped me on,
wouldn't that break things if a mod forced a node as a hand and then you separated nodes from items >.>
not to mention limit things much further :/

the reason I'm so strongly focused on documenting it is because I see potential for mods to add further support for a possible new item type.
like maybe a quantum node that could transfer states between nodes at the engine level (like the tesseract from EnderIO)
or even a sort of GL node that could forward rendering functionality for some certain purposes.

welcome to my autism.

**Comment by Zughy** [comment]
I'd like to fix this but I can't understand whether I should go with @SmallJoker approach or just suggest to close it as @rubenwardy said. Please provide practical inputs
