### ISSUE TITLE
Multi-threaded download

### ISSUE THREAD

**Issue by wzy2006** [minetest/minetest#10190]
## Problem
The download speed in "Online content DB" in minetest is very slow and sometimes the download fails.

In some countries, the speed of network access to foreign countries is limited. 

The average speed of a connection is only 10-30kb / s. 

But in the case of 8 threads, the download speed can reach about 200KB / s.
## Solutions

Using multithread download can effectively improve the speed

**Comment by nerzhul** [comment]
that should very low, not sure threading is the issue here

**Comment by wzy2006** [comment]
I download mod from minetest of GitHub in the browser, but whether to enable multithreading or not affects the download speed

**Comment by rubenwardy** [comment]
Yeah, threading is not the issue, your internet is. Try increasing the timeout

**Comment by SmallJoker** [comment]
Downloads are already multithreaded.
https://github.com/minetest/minetest/blob/82731d0d3d8bfe9e56f89466991f13c037f3a61e/src/client/clientmedia.cpp#L230-L235
