### ISSUE TITLE
how to host a minetest server on heroku

### ISSUE THREAD

**Issue by arydevy** [minetest/minetest#10200]
I seen that is posible to host a minecraft server on heroku but i want one for minetest

**Comment by sfan5** [comment]
Considering all the workarounds I see here (https://github.com/jkutner/heroku-buildpack-minecraft), it's obvious that Heroku is not meant to be a platform for game server hosting.
That said if you manage to tunnel out the UDP traffic you could probably successfully run a Minetest server from Heroku.

**Comment by FriendlyGamer** [comment]
> Considering all the workarounds I see here (https://github.com/jkutner/heroku-buildpack-minecraft), it's obvious that Heroku is not meant to be a platform for game server hosting.
> That said if you manage to tunnel out the UDP traffic you could probably successfully run a Minetest server from Heroku.

Indeed, best to get a standard VPS if not dedicated unit (this thing can eat quite a bit of RAM at times if configured to cache as much of it as possible to ensure performance).
