### ISSUE TITLE
File select dialog messes up localization/formspecs

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#1020]
![bug](https://f.cloud.github.com/assets/1042418/1606914/c2186ad8-5462-11e3-834b-bd6b6bee69d8.png)

**Comment by nerzhul** [comment]
Is this issue valid @sfan5 ?

**Comment by celeron55** [comment]
Confirmed to be valid on IRC: http://irc.minetest.ru/minetest-dev/2015-02-10#i_4149622

**Comment by ThomasMonroe314** [comment]
@sfan5 @paramat has this been taken care of?

**Comment by sfan5** [comment]
No, why would it?

**Comment by ThomasMonroe314** [comment]
I was just checking because the dialog for shader paths works fine for me.

**Comment by sfan5** [comment]
seems like 8fe753c3d96957cb9d58d9f82677b993effe3652 fixed this
