### ISSUE TITLE
Can i run two (or more) versions of minetest on the same device?

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10205]
If i can [run tow (or more) server on the same device](https://github.com/minetest/minetest/issues/10204), can i run two versions on the same device?
The two version that i want:
 - 5.3.0 (Download from ppa:minetestdevs/stable)
 - 5.4.0-dev (build from source code)

RAM: 4GB
Ubuntu Version: 20.04

**Comment by FriendlyGamer** [comment]
> If i can [run tow (or more) server on the same device](https://github.com/minetest/minetest/issues/10204), can i run two versions on the same device?
> The two version that i want:
> 
> * 5.3.0 (Download from ppa:minetestdevs/stable)
> * 5.4.0-dev (build from source code)
> 
> RAM: 4GB
> Ubuntu Version: 20.04

I believe you can, just have a process nameA and process nameB. Such as mainserv and devserver for example.  

On Linux this means making a server1.service and a server2.service file. Then you can simply do systemctl enable server1 
systemctl enable server2 
etc, etc etc

**Comment by Emojigit** [comment]
> > If i can [run tow (or more) server on the same device](https://github.com/minetest/minetest/issues/10204), can i run two versions on the same device?
> > The two version that i want:
> > 
> > * 5.3.0 (Download from ppa:minetestdevs/stable)
> > * 5.4.0-dev (build from source code)
> > 
> > RAM: 4GB
> > Ubuntu Version: 20.04
> 
> I believe you can, just have a process nameA and process nameB. Such as mainserv and devserver for example.
> 
> On Linux this means making a server1.service and a server2.service file. Then you can simply do systemctl enable server1
> systemctl enable server2
> etc, etc etc
> 
> Oh yea don't forget to assign DIFFERENT ports OR IPs.

I never use systemd to start the server, I always use command to start it.
How to set up a server that use systemd to start?

**Comment by FriendlyGamer** [comment]
> > > If i can [run tow (or more) server on the same device](https://github.com/minetest/minetest/issues/10204), can i run two versions on the same device?
> > > The two version that i want:
> > > 
> > > * 5.3.0 (Download from ppa:minetestdevs/stable)
> > > * 5.4.0-dev (build from source code)
> > > 
> > > RAM: 4GB
> > > Ubuntu Version: 20.04
> > 
> > 
> > I believe you can, just have a process nameA and process nameB. Such as mainserv and devserver for example.
> > On Linux this means making a server1.service and a server2.service file. Then you can simply do systemctl enable server1
> > systemctl enable server2
> > etc, etc etc
> > Oh yea don't forget to assign DIFFERENT ports OR IPs.
> 
> I never use systemd to start the server, I always use command to start it.
> How to set up a server that use systemd to start?

So firstly you will want to with your text editor under your ROOT user create a file for each of your server and input the following.... 
Server1:/etc/systemd/system/server1.service  
```
[Unit]
Description=Minetest Server1
After=network.target

[Service]
Type=simple
User=youruser
Group=yourgroup
WorkingDirectory=/home/minetest
ExecStart=/usr/bin/minetest --server
Restart=on-failure

RestartSec=5s
[Install]
WantedBy=multi-user.target
```
Server2:/etc/systemd/system/server2.service 
```
[Unit]
Description=Minetest Server2
After=network.target

[Service]
Type=simple
User=youruser
Group=yourgroup
WorkingDirectory=/path/to/minetestserver2
ExecStart=/path/to/server2/executable/minetest --server
Restart=on-failure

RestartSec=5s
[Install]
WantedBy=multi-user.target
```
_Just as long you configure the second one properly it should allow you to run both versions properly_. NOW to make these systemd files executable (and works on boot)... 
systemctl enable minetestserver1.service
systemctl enable minetestserver2.service 

To start/stop/restart them just replace the "enable" on the server(s) you wanna start/stop/restart on.  

Hope this helps you out!

**Comment by sfan5** [comment]
You can only have one system-wide installed version of Minetest, but you can have as many "portable" versions of Minetest installed as you want.
To get a "portable" variant make sure to configure the source code with `-DRUN_IN_PLACE=1`.

**Comment by paramat** [comment]
Feel free to continue discussing here if you want, but i will close this as it does not belong in MT issues, should be a forum topic instead, or you could ask on IRC.
