### ISSUE TITLE
Formspecs can not be showed further after explicit closing.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10201]
##### Minetest version
```
Minetest-5.4.0-dev-cfaef5b1c
```

##### Summary
If you call `minetest.show_formspec()` and then explicitly close by `minetest.close_formspec` or its equivalent `minetest.show_formspec(playername, formname, "")` calls, any further opening any formspec won`t happen. New formspecs will be opened only if you avoid calls of those functions.

##### Steps to reproduce
1. Open any formspec.
2. Then close (explicitly) that by calls of functions listed above.
3. Try to open other or the same formspec.

**Comment by Andrey2470T** [comment]
I`ve discovered if you set a timer (e.g. by minetest.after() with duration e.g. '1.5') after closing, at the expiration of that a new or the same formspec will be opened yet. As I understand does actual showing process require a time and that`s why can next openings not be implemented meantime?

**Comment by sorcerykid** [comment]
There needs to be a 1 tick delay.

https://forum.minetest.net/viewtopic.php?p=369696#p369696

**Comment by v-rob** [comment]
The way to update formspecs (how basically all mods do it, as far as I know) is to immediately open another formspec right over the first.  Closing the formspec before opening another is unnecessary.

Of course, this still is a bug and should be treated as such, but it's not a huge problem.  Unless the solution is simple (I know nothing about the packets code), then adding documentation to `lua_api.txt` showing how to update a formspec by not closing might be a second best.

**Comment by sorcerykid** [comment]
There can definitely be corner cases where that methodology is effectively impossible. A good example is if you develop a formspec-based debugging console, that allows for calling arbitrary routines that show their own formspecs. When the user exits those formspecs by pressing ESC or clicking `button_exit[]`, the  debugging console should be restored.

**Comment by v-rob** [comment]
Do escape and `button_exit[]` have the same problem?  I think the only problem is when there are multiple `minetest.show/close_formspec` calls in the same tic.  Escape and `button_exit[]` on the client make a round trip through `minetest.register_on_player_receive_fields` on the server back to the client with `minetest.show_formspec`, so it sounds like that would work fine (although I haven't explicitly tried it myself).

Regardless, it does need fixing.  There are other corner cases, such as if another mod closes a formspec and yours happens to open one on the same tic.

**Comment by sorcerykid** [comment]
The example I gave above is actually from a real world application I developed for debugging on my server. So I can confirm it doesn't work (this is under 0.4.x, but I imagine it's still the same). If a formspec is closed by the end-user, and I try to immediately open another formspec within the receive fields callback, it will not show unless I put it inside `minetest.after` with 0.0 delay.

**Comment by Andrey2470T** [comment]
Hmm, if I explicitly call `minetest.close_formspec' and then 'minetest.after' with '0.0' delay and put inside the callback `minetest.show_formspec', will it actually show? After all, it is equivalent to just call a show the formspec without the timer?

**Comment by sorcerykid** [comment]
A delay of 0.0 waits for a single server step (or at least it's always worked that way for me).

**Comment by v-rob** [comment]
Confirmed to be the same base issue as #11907, closing in favor of that one.
