### ISSUE TITLE
Can i run two (or more) server on the same device?

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10204]
I want to run two minetest server on my Mac Mini that installed Ubuntu. Can i do it?
Minetest Version: 5.3.0 (Download from ppa:minetestdevs/stable)
RAM: 4GB
Ubuntu Version: 20.04

**Comment by rubenwardy** [comment]
Yes, but you need to run on a different port and use a different world

**Comment by Emojigit** [comment]
> Yes, but you need to run on a different port and use a different world

Thank you!
