### ISSUE TITLE
Organising mods into modpacks from the main menu

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10211]
## Problem

Currently can be difficult to find some mods to put in your world. This issue is to discuss the best way to organize then in the GUI
ie: With mods organized will be better to find them
Ex. I like to put my mods organized into catergories modpacks. But would be awesome if could do this using the GUI. Another problem is GUI disable all my nested modpacks and I have to manually enable then editing world.mt

## Solutions

User can create own modpacks using a graphical way and GUI can enable/disable nested modpacks

## Alternatives

Add search field to search for mods inside modpacks or a way to expand all modpacks and cycle through mods pressing its first letter

## Additional context

Organizing mods using modpacks:
![image](https://user-images.githubusercontent.com/46538696/88041213-74f7a480-cb20-11ea-9063-54b4d68845d0.png)

**Comment by NathanSalapat** [comment]
This looks worse to me. I'd have to know what category a mod belongs to. I already know the name of the mod I want to enable, looking for the name seems much easier to me.

Additionally who/what decides what category a mod falls in? If the mods are expected to declare a category this wouldn't do any good until every single mod author added that data to their mod.

**Comment by rubenwardy** [comment]
I think the idea is that the user can create modpacks from the GUI

**Comment by BruceMustache** [comment]
Ok, so I pick the @rubenwardy idea

**Comment by LoneWolfHT** [comment]
If you click on a mod in that form you can then type the first letter of the mod you are looking for in your keyboard and your selection will jump to a mod beginning with that letter, you can press the letter multiple times to go to the next results

**Comment by paramat** [comment]
I do not think adding a complex feature that allows GUI creation and organisation of titled categorised mod folders is justified :-1: 
I think users should manually sort mods into folders in the computer's filesystem instead (but see below for something that seems to need doing).

I think this issue exaggerates the problem of 'finding mods'.
You would have to memorise what category a mod is in to open that folder to find the mod, it is often not obvious what category a mod falls into.
Currently mods are sorted alphabetically, so finding a mod from its name is already fast and easy even if all mods are in 1 list, so a search field does not seem needed.
Overall i doubt this saves any time, or is of much use to a user.

The only thing i consider worth working on is this:
> Another problem is GUI disable all my nested modpacks

> a way to expand all modpacks

Working on this was suggested by rubenwardy in the recent issue https://github.com/minetest/minetest/issues/10195#issuecomment-660314629 :
> The better solution is to allow nesting modpacks. Minetest does support nested mod packs in the backend, it's just the GUI that doesn't. So you can have nested modpacks in games

If we work on this, then users can manually sort their mods into folders if they want to, and this sorting is then displayed in the GUI.

**Comment by hecktest** [comment]
What about a tagging system? That would be useful for searching in the CDB, but also for managing a world's mod set.

**Comment by rubenwardy** [comment]
CDB supports tags in the web interface, but it's not used in the client (yet)

**Comment by BruceMustache** [comment]
> The only thing i consider worth working on is this:
I like that @paramat 
How can I help implement this? I want to make pull request

**Comment by AntumDeluge** [comment]
I think this would be solved simply by fixing nested modpacks. Currently, individual mods cannot be enabled/disabled from the GUI if they are inside a nested modpack.

![client_nested_modpacks](https://user-images.githubusercontent.com/3631473/120058251-7b876000-bffe-11eb-89ab-ecbedc021826.png)

**Comment by rubenwardy** [comment]
> and cycle through mods pressing its first letter

Please note that you can already do this by typing the name with the table selected
