### ISSUE TITLE
can't load textures that in the modpath/textures folder 

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10217]
##### Minetest version

```
Minetest 5.3.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50 GHz 2.60 GHz

GPU model: Intel(R) HD Graphics 520
OpenGL version:4.4.0

##### Summary
I added the "elements_3_metal_block.png" to the textures folder, and use on elements:element_3_metal_block node.
but the node still use the dummy image!
The mod: https://github.com/Emojigit/elements

**Comment by sfan5** [comment]
Your file is named "elements_3_metal_block.png.png", if you rename it correctly Minetest will find it.

**Comment by Emojigit** [comment]
> Your file is named "elements_3_metal_block.png.png", if you rename it correctly Minetest will find it.

Orz
