### ISSUE TITLE
DFSG (and similar) compliance

### ISSUE THREAD

**Issue by onpon4** [minetest/minetest#1022]
Minetest now has the mod database. One problem: freedom standards, such as those of Debian, Trisquel, Fedora, and some other operating systems, will now (rightly) deem Minetest to be non-free. The database includes these licenses, all of which are proprietary:

CC BY-ND: https://forum.minetest.net/mmdb/license/7/
CC BY-NC: https://forum.minetest.net/mmdb/license/8/
CC BY-NC-SA: https://forum.minetest.net/mmdb/license/9/
CC BY-NC-ND: https://forum.minetest.net/mmdb/license/10/

I don't know if the mod database accepts other licenses; if it does, that exacerbates the problem.

To fix this problem, Minetest ought to have a "DFSG" or similarly-named option which causes mods read from the mod database that are non-free to be not shown to the user, or alternatively (my preference, being a free software guy), the mod database should have strict standards to match the DFSG and similar guidelines.

**Comment by est31** [comment]
I'll close this, as the mmdb is disabled in the client, the service doesn't run. If there will be future service similar to this, it can be discussed at another place.

**Comment by est31** [comment]
(my opinion is to disallow anything non-free / disallowing commercial use)

**Comment by 0-afflatus** [comment]
We should strongly encourage people to use unambiguously free licenses. However, as long as minetest passes the DFSG it's a non-issue for me.

**Comment by mquinson** [comment]
A nice solution could be to show the license explicitly / prominently, as does  https://f-droid.org/ 
This collection of software for android sometimes distribute some less-free software if no good free alternative exists. But when it does so, a red warning appears.

Likewise, a filtering feature allowing to show only free software of the collection would solve the issue from my POV. I will simply ensure that this option is ticked by default in the Debian package, and I'd say that we would all be good.

**Comment by est31** [comment]
f-droid doesnt distribute content that isn't actually under a free license. They do show the license, but they only allow freely licensed software. The red things you talk about are antifeatures, that can affect software thats free itself.

**Comment by mquinson** [comment]
https://f-droid.org/wiki/page/Antifeatures
Some distributed software have their author distribute a non-free version while f-droid patches the code to free it. Also, promoting non-free addons (as the mods we are speaking about) is an antifeature of f-droid ;)

**Comment by rubenwardy** [comment]
I disagree that just because you can install non-free mods in Minetest means that Minetest is non-free. That's a stupid statement. Sorry, it is.

MMDB isn't even online anymore, so this issue is voided.

**Comment by mquinson** [comment]
I did not state that distributing non-free mods makes the software non-free, but only that this could be seen as an anti-feature by some people.
I'm sorry to hear that MMDB was shut down.

**Comment by est31** [comment]
Discussion on that is in #3289.

**Comment by rubenwardy** [comment]
I was replying to OP.
