### ISSUE TITLE
HUD text size declared as a number and not as a table

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10234]
## Problem

Declaring something like
```
my_txt = {
          hud_elem_type = "text",
          size      = { x = 3 },
          text      = "Hey there"
        }
```
is not great in terms of straightforwardness

## Solutions
```
my_txt = {
          hud_elem_type = "text",
          size      =  3,
          text      = "Hey there"
        }
```

## Alternatives

A plus: being a multiplier, it'd make sense having the field called `size_multiplier` more than `size`, even if I understand it's the `size` from the `statbar` type being recycled

**Comment by LoneWolfHT** [comment]
I was trying not to add any extra fields, since that seems to be the norm with HUD options

**Comment by SmallJoker** [comment]
The HUD format sucks. It should be rewritten to do it similar to the GenericCAO network packet handler.
https://github.com/minetest/minetest/blob/f948e2c58570df6bc77226b6066fec5ed90051ee/src/client/content_cao.cpp#L1553-L1559

Per-HUD-type Lua field names would be possible, and the network only sends what's needed.

**Comment by rubenwardy** [comment]
Even if all HUD types were required to use the same fields, it shouldn't be exposed to the Lua API

**Comment by Zughy** [comment]
@SmallJoker so, working on a PR to improve this is quite useless and it'd be better to rework the whole HUD format system? 
(also, guys, you forgot to label it)

**Comment by Zughy** [comment]
Well, hoping that #14263 becomes reality, this is not even worth it anymore
