### ISSUE TITLE
World configuration screen: makes enter key behave like save button

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10230]
## Problem

When configuring a world currently if you press enter key it toggle selected button
While is more natural to make it behave like save button
ie: This is need in #10147 

## Solutions

Makes it behaves like save button

## Alternatives

Any alternative can be put here

## Additional context

In this video the enter key don't let me rename the world's name
https://streamable.com/cp5zq2

**Comment by SmallJoker** [comment]
Use `field_close_on_enter`
https://github.com/minetest/minetest/blob/808fa5ecb3ddfd5d993000cc6b4c972257e182db/doc/lua_api.txt#L2305-L2311

**Comment by BruceMustache** [comment]
Thanks
