### ISSUE TITLE
All text in main menu invisible

### ISSUE THREAD

**Issue by rabadimeshal** [minetest/minetest#10249]
##### Minetest version

```
minetest 5.3.0
```

##### OS / Hardware

Operating system: windows 10 64 bit
CPU: intel(R) penitum(R) CPU G620 @ 2.60Ghz 2.60 Ghz

GPU model: intel(R) HD graphics family
OpenGL version: 3.1.0

##### Summary

Annoying 
##### Steps to reproduce

when my First time open this game the main menu was broken , missing something and  Annoying
![main menu](https://user-images.githubusercontent.com/65845044/89113007-ef56eb80-d473-11ea-9344-b398dc70ede1.png)

**Comment by rubenwardy** [comment]
What language is your computer set to?

It looks like Minetest's font can't handle it, and it's not using the fallback font.

One way to fix this is to set english as your language. Add `language = en` as a new line in minetest.conf

**Comment by paramat** [comment]
@rabadimeshal ^

**Comment by sfan5** [comment]
Judging by the [numerals](https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system#Glyph_comparison) in the taskbar, it's Arabic (`ar`).

**Comment by ResuUman** [comment]
This is what I used:
https://forum.minetest.net/viewtopic.php?p=312467#p312467

Same (?) problem mentioned here:
https://forum.linuxiarze.pl/index.php?topic=3123.0
https://forum.minetest.net/viewtopic.php?t=23769
https://ubuntu.pl/forum/viewtopic.php?t=182986

**Comment by sfan5** [comment]
Arabic was excluded from being automatically chosen by 97aefe9b81414fa560d1ff37a3060266ac9735a9.
