### ISSUE TITLE
Support for vulcan

### ISSUE THREAD

**Issue by DonFlymoor** [minetest/minetest#10244]
I recently stumbled across a `Vulcan`, a renderer faster then normal `OpenGL` . Some comparison between the two [here](https://www.androidauthority.com/opengl-vs-vulkan-performance-706408/). I believe that Minetest could benefit from Vulcan's speed, especially on low-powered computers. I read that `Irrlicht` already supports Vulcan [here](http://irrlicht.sourceforge.net/forum/viewtopic.php?f=6&t=52371), so I don't know if this has already been implemented in Minetest, or if only `OpenGL` and `GLES` are supported.

**Comment by nerzhul** [comment]
not possible yet, it's just a incomplete fork, and we wait irrlicht 1.9 since ages

**Comment by farooqkz** [comment]
Has anything changed in 6 years to reconsider adding a Vulkan backend?

**Comment by appgurueu** [comment]
There is merit to a Vulkan backend, but it is not something we currently have the resources for. As far as rendering performance improvements go, there are lower-hanging fruits to pick first, such as proper instancing of objects. Once our OpenGL 3 backend is up to acceptable standards, we can consider Vulkan.

**Comment by sfan5** [comment]
see https://github.com/minetest/irrlicht/issues/253 and https://github.com/minetest/irrlicht/issues/107#issuecomment-1362680829, too

**Comment by farooqkz** [comment]
Thanks folks. Do I open a new issue to track Vulkan support  with proper labeling and the history till now? Maybe someone would be found to be interested to add basic experimental support for it. And later, it could evolve over time.
