### ISSUE TITLE
Language switching function of Android

### ISSUE THREAD

**Issue by 18296565196** [minetest/minetest#10248]
I found Chinese language files on Android version, but I can't switch Chinese. I hope that in the future version, I can support multi language switching and be able to identify the system language to make changes. When can developer documentation(dev.minetest.net) be available in Chinese.
Thinks for you watching!
Wish you well
My English is not very good. Sorry

**Comment by 18296565196** [comment]
I hope I can make some contribution to translation

**Comment by SmallJoker** [comment]
Not implemented yet. Bug: #6093
PR: #10019
