### ISSUE TITLE
Add login at the in-game ContentDB

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10252]
## Problem

I can't see my not approved package in contentdb(both web and in-game), That make i can't test the mod easyily on all platform.
## Solutions

Add a login option to in-game ContentDB, if you logged in, you will see your packages that not approved

**Comment by paramat** [comment]
I assume you mean in-game login to the CDB website?
This sounds quite complex, as a way to display unapproved packages would also be needed.
Seems an odd request though, if a CDB package is not yet approved, it should not appear in-game to anyone, including yourself, you should not be allowed to test it in-game surely? that is why it is unapproved.
I cannot see sufficient need or usefulness either, it seems like an unnecessary luxury.

**Comment by Zughy** [comment]
Why not simply moving your package in your local `minetest/mods` folder instead, like anyone else? It's faster and it doesn't require further coding

**Comment by paramat** [comment]
Closing. You should not be able to see, download or use unapproved packages in-game. You can test your unapproved content on other platforms in other ways.
