### ISSUE TITLE
Add storage (meta) related to current server and not just mod storage.

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10251]
## Problem

We need a solution to creating storage when modding, that is relevant to the entire storage.

We currently have mod storage (mod meta), node storage (node meta), and player storage (player meta). We can access storage in these metas by using meta:get_string("stringname") and set it by using set_string(). It would be convenient to access storage between other mods becuase currently a mod can only access its own storage.

## Solutions

An idea of what could be done is to create a method like
minetest.get_server_storage() which could access a global 'meta' like the other metas. This would obviosly be relative to the current server which is running the code.

## Additional context

I understand that this type of method could seen excessive and unnecessary but modding can be difficult and confusing when having to create many tables that other mods can access when you just need a value. Please think.

**Comment by rubenwardy** [comment]
What usecases are there for this?

It's typically better for a mod to expose an API, as that's nicer than using arbitary meta keys

**Comment by appgurueu** [comment]
# Alternatives

Make a mod which exposes it's mod storage to all mods if you need shared storage, already neatly possible. I think this is what ruben is referring to?

Also note that you should only be using meta for persistence and not for sharing variables between mods due to performance (and neatness) reasons.
