### ISSUE TITLE
Repeat in my code not work

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10271]
##### Minetest version

```
Minetest 5.3.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel Core i7

GPU model: ?
OpenGL version: 4.4.0

##### Summary
I made a mod that make drop item *3000. 
The code:
```
x3000 = {}
x3000.real_item_drop = core.item_drop

function core.item_drop(itemstack, dropper, pos)
   --[ local variable definition --]
   a = 1

   --[ repeat loop execution --]
   repeat
      x3000.real_item_drop(itemstack, dropper, pos)
      a = a + 1
   until( a > 3000 )
end
```
But this code not work. Why?

##### Steps to reproduce
Use the code above to make a mod, then drop an item.
You can see the item drop normaly, not x3000.

**Comment by SmallJoker** [comment]
```Lua
for i = 1, 3000 do
   minetest.add_item(pos, item)
end
```

Please ask such questions in the [Modding Discussion forum](https://forum.minetest.net/viewforum.php?f=47), or freenode/#minetest or some Lua help channel.
