### ISSUE TITLE
Bug when i punch a object

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10277]
##### Minetest version

```
Minetest 5.4.0-dev-abfea69e5 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04
CPU: Intel Core 2 Duo

GPU model:? 
OpenGL version: 2.1

##### Summary
I made a **Fake Unknown object** mod, if you punch the unknown object, it will disappear then add a spawner to your inventory.

But there have a bug: Sometimes, if I repeat click it quickly, the object is still here but you will get a spawner.

##### Steps to reproduce
1. Install https://github.com/Emojigit/unknown_object
2. Open a new world with `devtest` then enable this mod
3. Grant you `give` then give you a `unknown_object:unknown_object`
4. Place it
5. try to look at it then repeat left-click quicky, you may still see the object here, but you still can get spawners.

**Comment by NathanSalapat** [comment]
Probably not a bug, maybe destroy the entity in the on_punch callback.

**Comment by Emojigit** [comment]
> Probably not a bug, maybe destroy the entity in the on_punch callback.

How to do it?

**Comment by paramat** [comment]
Looks like a code error to me. If you want the entity to be destroyed when punched, you have to code that to happen, but you have not.
Rapid punching reduces damage done due to 'full punch interval', so perhaps you end up triggering 'on_punch' but without doing enough damage to destroy the entity?

Also, this field is for players only.
`hp_max = 1,
        -- For players only`

**Comment by NathanSalapat** [comment]
```self.object:remove()```
You should really ask coding questions elsewhere though, IRC or the forums.

**Comment by paramat** [comment]
^ Yes.
If one of your mods does not work properly, please first ask for code help elsewhere, do not immediately assume an engine bug.
