### ISSUE TITLE
Title of a dev minetest window

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10270]
When I start a dev minetest's GUI, The title of the window is like this:
<pre>
Minetest 5.4.0-dev (some text like hash, what is this?)
</pre>
What is the text after `5.4.0-dev`?

## More Infomation
 - minetest version by `bin/minetest --version`:
<pre>
Minetest 5.4.0-dev-6b69d0e
</pre>
 - The real hash of my commit: `47998857f8f2769d4a6cd106c4a79968fab6b590`
 - The repo of my version: https://github.com/Emojigit/minetest/tree/patch-1

**Comment by sfan5** [comment]
That's the commit hash the code was built from.

**Comment by Emojigit** [comment]
> That's the commit hash the code was built from.

@sfan5 My commit is hash is `47998857f8f2769d4a6cd106c4a79968fab6b590`, but the hash on the title is `6b69d0e`, why?
