### ISSUE TITLE
Translated strings in hypertext fields are broken if they contain spaces

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10286]
##### Minetest version

Tried both with 5.3.0 and with the dev one

##### Summary
With "broken" I mean they won't get translated, creating a huge space between the first and the second word, as it was justified (then it goes on a new line). If spaces are removed, it then works.

I've also tried declaring the translated string first and then putting the variable inside the formspec, but same result. If I do `minetest.chat_send_player`, the translated string is correct, but it's not when it reaches the formspec

##### Steps to reproduce
Create a formspec having a string ie
`"hypertext[3.1,2.9;3,1;test;" .. S("Try to translate me") .. "]"`

and a translation linked to it (ie `Prova a tradurmi` in Italian)

EDIT:
same with `minetest.formspec_escape(S(etc))`

**Comment by rubenwardy** [comment]
you need to use formspec_escape when putting arbitrary text into formspecs

You might find this function helpful:

```lua
local function FS(...)
	return minetest.formspec_escape(S(...))
end
```

In which case, it will be:

```lua
"hypertext[3.1,2.9;3,1;test;" .. FS("Try to translate me") .. "]"
```

**Comment by Zughy** [comment]
Huh, I didn't know that. Yet, it still doesn't work, same issue

**Comment by kilbith** [comment]
Use [`minetest.get_translated_string`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3289-L3291)

**Comment by Zughy** [comment]
@kilbith according to that though:

> IMPORTANT: This functionality should only be used for sorting, filtering or similar purposes.
You do not need to use this to get translated strings to show up on the client.

**Comment by SmallJoker** [comment]
In-line translations should really work. I presume this is a hypertext formspec element bug unless this can be confirmed for textareas as well.

**Comment by kilbith** [comment]
@pyrollo

**Comment by pyrollo** [comment]
> Use [`minetest.get_translated_string`](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3289-L3291)

That's a bad idea. Better fixing hypertext.
