### ISSUE TITLE
Lua API: add ItemStack wear_percentage

### ISSUE THREAD

**Issue by BruceMustache** [minetest/minetest#10281]
## Problem

Currently wear goes from 0 (new tool) to 65535 (Close to die)
I think this isn't trivial

## Solutions

Create a new properties called wear_percentage a float number that goes from 0 (new) to 1 (totally broke)
With methods to set, get, add

**Comment by SmallJoker** [comment]
Just divide or multiply by 65535 when needed. It's simple maths. This could be put into a constant for easier memorizing, but I don't think a new property is needed here.

**Comment by BruceMustache** [comment]
Ok it was just a suggestions. Initially I don't thought it trivial
After I discover 65535 is because this is the max interger a 16-bit number can reach
