### ISSUE TITLE
Formspec: possibility to hide the default background

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10288]
## Problem

There is apparently no way to hide the default background of a formspec if you have a picture partly transparent like [this](https://gitlab.com/zughy-friends-minetest/skins-collectible/-/blob/master/textures/skinscollectible_gui_bg.png). Better said, I don't know why it worked on Manjaro a few weeks ago but it doesn't on Mint. I tried bisecting, still nothing. I'm starting to think it was a Manjaro bug at this point..?
Basically, `bgcolor[whatevercolor;true]` doesn't hide it. I've also tried specifying the formspec version such as `formspec_version[4]`, putting blank.png as background, putting neither, both, false, whatever instead of `true` in bgcolor; still nothing.

![](https://i.imgur.com/tyUgxT0.png)

If you want to try the mod yourself: https://gitlab.com/zughy-friends-minetest/skins-collectible

If you want to try something minimal:
```
local function get_formspec(p_name)

    local formspec = {
        "size[13,8]",
        "background[0,0;12.927,8;bgtorender.png]",
        "bgcolor[#FFFFFF;true]"
    }

    return table.concat(formspec, "")    
end




minetest.register_tool("test:object", {

  description = "object",
  inventory_image = "thiswillcreateanerror.png",

  on_use = function(itemstack, user, pointed_thing)
    local p_name = user:get_player_name()
    minetest.show_formspec(p_name, "test:GUI", get_formspec(p_name))
  end

})
```

## Solutions

Implement it please (or tell me where I'm wrong :D)

**Comment by NathanSalapat** [comment]
```### `no_prepend[]`

* Must be used after the `size`, `position`, and `anchor` elements (if present).
* Disables player:set_formspec_prepend() from applying to this formspec.```
This is probably what you are looking for.

**Comment by Zughy** [comment]
@NathanSalapat love ya, thanks! I guess this can be closed (in my defence, it wasn't THAT intuitive)
