### ISSUE TITLE
Low-latency mouse smoothing

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#10282]
## Problem

As far as I know, it might be possible that a mouse, touchpad or touchscreen movement input is not sent every frame but with a lower frequency. If a player has this problem and rotates the camera, the rotation could look jittery and not smooth. 
Minetest already has `cinematic` settings for mouse smoothing, but I think those are unsuitable because they have a high latency. When I have tested them with a low smoothing value, the rotation looked unintuitive.

## Solutions

I have thought about a very simple smoothing method which delays the visual rotation with at most one frame:
Use the average rotation of the current and previous input-based rotation, for example
if the inputs are (0, 0, 0, 1, 1, 1, 2, 2, 3, 4, 4), it's smoothed to (0, 0, 0, 0.5, 1, 1, 1.5, 2, 2.5, 3.5, 4)

## Alternatives

It is possible to use a more complicated smoothing, e.g. a configurable lowpass filter. However, this would either delay the rotation more or predict the future, which is unintuitive because human (desired) mouse rotation is not always continuous.

**Comment by paramat** [comment]
> As far as I know, it might be possible that a mouse, touchpad or touchscreen movement input is not sent every frame but with a lower frequency. If a player has this problem and rotates the camera, the rotation could look jittery and not smooth.

Ok, but does this problem actually happen to anyone? Seems like speculation, so seems low priority.

**Comment by SmallJoker** [comment]
Camera smoothing is currently done as follows:
https://github.com/minetest/minetest/blob/abfea69e5f68c0f2c946bfcd4444f8cb32e781cf/src/client/game.cpp#L1125-L1128
The only issue I can see here is that it does not take `dtime` into account.

**Comment by HybridDog** [comment]
I have tested it; the camera movement looks a bit more smooth to me:
```diff
diff --git a/src/client/game.cpp b/src/client/game.cpp
index 0d3a0ca15..c5f3a7fd7 100644
--- a/src/client/game.cpp
+++ b/src/client/game.cpp
@@ -1068,6 +1068,7 @@ void Game::run()
 	ProfilerGraph graph;
 	RunStats stats              = { 0 };
 	CameraOrientation cam_view_target  = { 0 };
+	static CameraOrientation cam_view_target_prev  = { 0 };
 	CameraOrientation cam_view  = { 0 };
 	FpsControl draw_times       = { 0 };
 	f32 dtime; // in seconds
@@ -1110,6 +1111,7 @@ void Game::run()
 		//  + Sleep time until the wanted FPS are reached
 		limitFps(&draw_times, &dtime);
 
+
 		// Prepare render data for next iteration
 
 		updateStats(&stats, draw_times, dtime);
@@ -1129,10 +1131,11 @@ void Game::run()
 		processUserInput(dtime);
 		// Update camera before player movement to avoid camera lag of one frame
 		updateCameraDirection(&cam_view_target, dtime);
-		cam_view.camera_yaw += (cam_view_target.camera_yaw -
-				cam_view.camera_yaw) * m_cache_cam_smoothing;
-		cam_view.camera_pitch += (cam_view_target.camera_pitch -
-				cam_view.camera_pitch) * m_cache_cam_smoothing;
+		cam_view.camera_yaw = 0.5f * (cam_view_target.camera_yaw +
+			cam_view_target_prev.camera_yaw);
+		cam_view.camera_pitch = 0.5f * (cam_view_target.camera_pitch +
+			cam_view_target_prev.camera_pitch);
+		cam_view_target_prev = cam_view_target;
 		updatePlayerControl(cam_view);
 		step(&dtime);
 		processClientEvents(&cam_view_target);
```
