### ISSUE TITLE
ld: error: undefined symbol: Json::Value::operator=(Json::Value&&) when compiling 5.3.0 on FreeBSD

### ISSUE THREAD

**Issue by PaddyMac** [minetest/minetest#10289]
##### Minetest version
```
5.3.0
```

##### OS / Hardware
Operating system: FreeBSD 12.1-STABLE r363327
CPU: Dual Intel Xeon X5680

##### Summary

I had to delete libevent temporarily from my system to circumvent issue #9078 . The only configuration option I passed was:

cmake .. -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib"

so that the build system would bind libintl. I ran make, and I got the following error output:

[100%] Building CXX object src/CMakeFiles/minetest.dir/voxel.cpp.o
[100%] Building CXX object src/CMakeFiles/minetest.dir/voxelalgorithms.cpp.o
[100%] Linking CXX executable ../../bin/minetest
ld: error: undefined symbol: Json::Value::operator=(Json::Value&&)
>>> referenced by clientlauncher.cpp
>>>               CMakeFiles/minetest.dir/client/clientlauncher.cpp.o:(ClientLauncher::launch_game(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, GameParams&, Settings const&))
>>> referenced by clientlauncher.cpp
>>>               CMakeFiles/minetest.dir/client/clientlauncher.cpp.o:(ClientLauncher::launch_game(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, GameParams&, Settings const&))
>>> referenced by clientlauncher.cpp
>>>               CMakeFiles/minetest.dir/client/clientlauncher.cpp.o:(ClientLauncher::launch_game(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, GameParams&, Settings const&))
>>> referenced by clientlauncher.cpp
>>>               CMakeFiles/minetest.dir/client/clientlauncher.cpp.o:(ClientLauncher::launch_game(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, bool, GameParams&, Settings const&))
>>> referenced by mods.cpp
>>>               CMakeFiles/minetest.dir/content/mods.cpp.o:(ModMetadata::save(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))
>>> referenced by mods.cpp
>>>               CMakeFiles/minetest.dir/content/mods.cpp.o:(ModMetadata::load(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))
>>> referenced by c_content.cpp
>>>               CMakeFiles/minetest.dir/script/common/c_content.cpp.o:(read_json_value(lua_State*, Json::Value&, int, unsigned char))
>>> referenced by c_content.cpp
>>>               CMakeFiles/minetest.dir/script/common/c_content.cpp.o:(read_json_value(lua_State*, Json::Value&, int, unsigned char))
>>> referenced by c_content.cpp
>>>               CMakeFiles/minetest.dir/script/common/c_content.cpp.o:(read_json_value(lua_State*, Json::Value&, int, unsigned char))
>>> referenced by c_content.cpp
>>>               CMakeFiles/minetest.dir/script/common/c_content.cpp.o:(read_json_value(lua_State*, Json::Value&, int, unsigned char))
>>> referenced 45 more times
>>> did you mean: Json::Value::operator=(Json::Value)
>>> defined in: ../lib/jsoncpp/libjsoncpp.a(jsoncpp.cpp.o)

ld: error: undefined symbol: Json::Value::operator=(Json::Value const&)
>>> referenced by c_content.cpp
>>>               CMakeFiles/minetest.dir/script/common/c_content.cpp.o:(read_json_value(lua_State*, Json::Value&, int, unsigned char))
>>> referenced by c_content.cpp
>>>               CMakeFiles/minetest.dir/script/common/c_content.cpp.o:(read_json_value(lua_State*, Json::Value&, int, unsigned char))
>>> referenced by serverlist.cpp
>>>               CMakeFiles/minetest.dir/serverlist.cpp.o:(ServerList::getOnline())
>>> referenced by serverlist.cpp
>>>               CMakeFiles/minetest.dir/serverlist.cpp.o:(ServerList::serializeJson(std::__1::vector<Json::Value, std::__1::allocator<Json::Value> > const&))
>>> referenced by serverlist.cpp
>>>               CMakeFiles/minetest.dir/serverlist.cpp.o:(std::__1::vector<Json::Value, std::__1::allocator<Json::Value> >::insert(std::__1::__wrap_iter<Json::Value const*>, Json::Value const&))
>>> referenced by tool.cpp
>>>               CMakeFiles/minetest.dir/tool.cpp.o:(ToolGroupCap::toJson(Json::Value&) const)
>>> referenced by tool.cpp
>>>               CMakeFiles/minetest.dir/tool.cpp.o:(ToolCapabilities::serializeJson(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const)
>>> referenced by tool.cpp
>>>               CMakeFiles/minetest.dir/tool.cpp.o:(ToolCapabilities::serializeJson(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const)

ld: error: undefined symbol: Json::StreamWriterBuilder::operator[](std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
>>> referenced by convert_json.cpp
>>>               CMakeFiles/minetest.dir/convert_json.cpp.o:(fastWriteJson(Json::Value const&))
ld: error: undefined symbol: Json::ValueIteratorBase::deref()
>>> referenced by serverlist.cpp
>>>               CMakeFiles/minetest.dir/serverlist.cpp.o:(ServerList::getOnline())
>>> referenced by tool.cpp
>>>               CMakeFiles/minetest.dir/tool.cpp.o:(ToolCapabilities::deserializeJson(std::__1::basic_istream<char, std::__1::char_traits<char> >&))
>>> referenced by tool.cpp
>>>               CMakeFiles/minetest.dir/tool.cpp.o:(ToolCapabilities::deserializeJson(std::__1::basic_istream<char, std::__1::char_traits<char> >&))
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- ../bin/minetest ---
*** [../bin/minetest] Error code 1

make[2]: stopped in /usr/home/patrick/work/minetest/minetest-5.3.0/build
1 error

make[2]: stopped in /usr/home/patrick/work/minetest/minetest-5.3.0/build
--- src/CMakeFiles/minetest.dir/all ---
*** [src/CMakeFiles/minetest.dir/all] Error code 2

make[1]: stopped in /usr/home/patrick/work/minetest/minetest-5.3.0/build
1 error

make[1]: stopped in /usr/home/patrick/work/minetest/minetest-5.3.0/build
*** [all] Error code 2

make: stopped in /usr/home/patrick/work/minetest/minetest-5.3.0/build
1 error

make: stopped in /usr/home/patrick/work/minetest/minetest-5.3.0/build

**Comment by sfan5** [comment]
try with `-DENABLE_SYSTEM_JSONCPP=1` in your cmake options.

**Comment by PaddyMac** [comment]
I had tried that previously, and the program failed to run. So I thought it was a no-go. It turned out that it failed to run because I didn't have minetest_game installed yet. So upon trying it again after installing the game, it does appear that using the system jsoncpp works fine for the server.

My only concern is that CMake warns that this, "May cause segfaults and other memory errors!".

**Comment by sfan5** [comment]
That warning text is old and should probably be removed.

**Comment by PaddyMac** [comment]
I've been doing some testing. Apparently the build failures I was experiencing were resulting from enabling the PostGreSQL or SpatialIndex backends while using the bundled jsoncpp. Enabling either of these feaures will build successfully if using the system jsoncpp.

The only other issue I found which I wanted to bring up is that if gettext is enabled for native language support, and only the server is built but not the client, Minetest will build but the installation will fail due to missing minetest.mo files.

**Comment by smeagolthellama** [comment]
Having the same issue on devuan, with postgres installed. trying the `-DENABLE_SYSTEM_JSONCPP=1` thing now.

**Comment by savilli** [comment]
Can't reproduce, it builds with `-DENABLE_SYSTEM_JSONCPP=1` and with `-DENABLE_SYSTEM_JSONCPP=0`. Guess some jsoncpp update has fixed it.
