### ISSUE TITLE
What does the client EXACTLY do when requesting remote media?

### ISSUE THREAD

**Issue by FriendlyGamer** [minetest/minetest#10287]
As the title state, I am trying to work with BunnyCDN to deliver over 60MB of files to players as snappy as possible. But they are requesting on what the Minetest client software does when requesting them as they believe it's that what blocking the requests (generating 405s). Despite them being POST and HTTPS compliance.  

If we can understand what the client EXACTLY does, I may be able to relay it to BunnyCDN to help them understand what's going on here and maybe they can help me figure out a CDN strategy that will actually works for Minetest clients.

**Comment by sfan5** [comment]
It sends a `POST` request to `/index.mth` with a hash set[1] of the hashes it is missing, in response it expects a hash set[1] of files the server has. To not waste bandwidth it would make sense for the server to only send the subset of its own hashes that the client needs, but this is not a requirement. You can configure the server to ignore the post data and serve a static[2] mts file.

Then, it requests each media file by hexadecimal hash (e.g. `GET /adc83b19e793491b1c6ea0fd8b46cd9f32e592fc`).

[1] Documented [here](https://github.com/minetest/minetest/blob/715a123a33db7b0f191259ba68cbc9c565d0d4e8/src/client/clientmedia.cpp#L572-L583)
[2] A script for generating such a static file (and moving files where they belong) can be found here https://gist.github.com/sfan5/6351560

**Comment by rubenwardy** [comment]
Off topic: I don't think how this works is particularly nice. Could it make more sense for the client to just request every file using HTTP/2? There would be minimal overhead for missing files due to HTTP/2
