### ISSUE TITLE
Regression? Point collision boxes do not work anymore

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10294]
##### Minetest version
```
5.3.0
```

##### Summary

Players (entities?) with `collisionbox = {0, 0, 0, 0, 0, 0}` (a single point) fall indefinitely; collisions are disabled. Older versions used to apply point collisions in that case.

##### Steps to reproduce
Use the `/vanish` command of the catcommands mod (a member of the UMTD discord discovered that bug this way).

**Comment by SmallJoker** [comment]
There's no volume to cause collision so that seems to be legit, though no physics should be applied since there's zero mass.

**Comment by benrob0329** [comment]
Honestly this seems like a really useful behavior.

**Comment by rubenwardy** [comment]
I can confirm that this used to happen on CTF, even after the collisionbox is set back to the original value

**Comment by paramat** [comment]
Perhaps this change is due to recent collision changes @TheTermos 
I do not see this as a problem, both old and new behaviours seem acceptable.
Hopefully mods can use a workaround.

**Comment by appgurueu** [comment]
> Honestly this seems like a really useful behavior.

Absolutely not. It is redundant with the `physical` and `collide_with_objects` object properties.

**Comment by benrob0329** [comment]
Thats some necroposting, but forbidden magics aside my reading of your OP suggests that players who's collision box is set to a single point fall through the world as well, does `physical` replicate this?

**Comment by appgurueu** [comment]
> Thats some necroposting, but forbidden magics aside my reading of your OP suggests that players who's collision box is set to a single point fall through the world as well, does `physical` replicate this?

Pretty sure it does (if it doesn't, the `noclip` priv & enabling it clientside have the same effect). If it doesn't, that's a bug as well.

**Comment by Zughy** [comment]
It's been two major versions in which this problem has not been addressed. My minigame mod uses `collisionbox = {0}` for the spectator mode, so changing it back to what it used to be would cause incompatibilities in every mod developed after MT 5.3 which introduced this aspect. I get that this change was an incompatibility in the first place, but causing two of them... not a great choice? Also because I'd also need #10139 to be implemented to actually have uncollidable players again

**Comment by Zughy** [comment]
Possible close due to what sfan said: https://irc.minetest.net/minetest-dev/2022-05-04#i_5969232

**Comment by appgurueu** [comment]
Note: An acceptable workaround exists (setting very small collisionboxes); mods like "vanish" will just have to apply it.
