### ISSUE TITLE
Particle performance

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10298]
##### Minetest version
```
5.3.0
```

##### Summary
So I recently played around with particlespawners. I used them to emit smoke particles at fire nodes. Thing is, if there is a lot of fire, there's a lot of smoke particles and the performance drops rather quickly below 20 FPS.

The game doesn't seem to act very efficient when there are a lot of particle spawners (think of the Underworld with fire everywhere).

https://satoshiupload.com/images/W1ljHwnGUu.png

This issue is to discuss how to improve performance on particles and particlespawners in general.

----

The first thing I noticed is that the rendering distance for particles is infinite. It seems that once a client has "found" a particlespawner, it will handle and render it even if the player is very far away. So my first suggestion to boost performance is to limit the rendering distance of particles. Particles and particles that appear more than X nodes away from the player are ignored. You don't need to simulate particles of a block of fire over 1000 nodes away. ;-)

https://satoshiupload.com/images/UMZYItK8y5.png

Maybe the modder can be permitted to set a flag in the particle definition to overwrite the distance limit regardless (useful for large particles).

There are probably many other ways to improve performance, please add your own suggestions.

**Comment by SmallJoker** [comment]
#1414
#8461

**Comment by sfan5** [comment]
The code that handles particle<i>spawners</i> is a bit different:
https://github.com/minetest/minetest/blob/5bda36143f9bd332b6ba420d9b91be1713092eae/src/server.cpp#L1561-L1563

> The client cannot render what's not sent by the server. Though if it were sent, it would still render them.

I think that's what Wuzzy meant. If the particles are known to the client, it will always render them no matter how far.
