### ISSUE TITLE
'replacements' table returns higher count of replacing items than necessary.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10325]
##### Minetest version
```
Minetest-5.4.0-dev-542df11be
```

##### Summary
If your `minetest.register_craft` contains `replacements` table with some replacing itemstack with items count `count`, actually in result of a crafting you get `count+6` items replaced in the grid. It doesn`t depend on a size of the stack, this number is constant.

**Comment by SmallJoker** [comment]
Related: #9250

Could you please provide the `minetest.register_craft` code that you used to get this issue?

**Comment by Andrey2470T** [comment]
Yes, please:
`
minetest.register_craft({
        type = "shapeless",
        output = "luxury_decor:wooden_board 3",
        recipe = {"stairs:slab_wood", "luxury_decor:saw"},
        replacements = {
            {"", "luxury_decor:saw 1"}  -- or just {"", "luxury_decor:saw"}
        }
    })
`

**Comment by NathanSalapat** [comment]
Unless I'm mistaken you're replacing every empty slot with the saw with that code. Your replacement should be the item you want to replace, and what to replace it with.

```{"luxury_decor:saw", "luxury_decor:saw"}```

**Comment by Andrey2470T** [comment]
Why every empty slot? I replace only those that are filled with those items: `{"stairs:slab_wood", "luxury_decor:saw"}` should be replaced correspondingly to `{"", "luxury_decor:saw"}`

**Comment by NathanSalapat** [comment]
```    {
        output = 'default:pick_stone',
        recipe = {
            {'default:cobble', 'default:cobble', 'default:cobble'},
            {'', 'default:stick', ''},
            {'', 'default:stick', ''},  -- Also groups; e.g. 'group:crumbly'
        },
        replacements = <list of item pairs>,
        -- replacements: replace one input item with another item on crafting
        -- (optional).
    }```
You need to define what should be replaced with what. Using "" as the first item means all empty slots will be replaced with the second entry.

**Comment by SmallJoker** [comment]
As correctly mentioned above, `""`will replace empty slots by `"luxury_decor:saw"`. There are 7 free spots, so you'll get 1+6 outputs. The API is working correctly.

**Comment by Andrey2470T** [comment]
It got worked when I had replaced to `{"luxury_decor:saw", "luxury_decor:saw"}`. However, it is just even weird since it should replace each input itemstack to the saw by a logic. '{"", "luxury_decor:saw"}' should have replaced to an empty stack and the saw what is logical. Interestingly to know, how to replace each stack to the saw then?
