### ISSUE TITLE
Pressing ESC in the main menu error screen should not close the client

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#10332]
##### Minetest version
```
Minetest 5.3-stable
```

##### Summary
Pressing ESC in an error screen of the main menu to quickly dismiss the message instead closes Minetest. This is very unintuitive and destructive behavior. In Windows and Mac operating systems, the ESC key is not customarily used to quit an application.

For the longest time I figured this was just a personal nuiscance, so I didn't report it. But then I noticed the same concern raised in https://github.com/minetest/minetest/issues/8930#issuecomment-531357588, so I decided to go ahead and open an issue.

**Comment by paramat** [comment]
:+1:
