### ISSUE TITLE
Edit the MTEngine repository 'About' text: remove 'infinite', remove link to MTG

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#10344]
Currently:
```
About

Minetest, an open source infinite-world block sandbox game engine with support for survival and crafting.
Also see https://github.com/minetest/minetest_game
```
'Infinite-world' drives me nuts as it is nonsense, and gives the wrong impression to those used to MC or otherwise large sized voxel games.
I request removing the link to MTG as part of the intention to move focus and attention away from it and no longer consider it the primary MT game. The MTG repo is already part of the MT GitHub organisation so that is plenty of focus already.

Not sure if any core dev can edit this text, might need @celeron55 to do it.

**Comment by rubenwardy** [comment]
ok, I'll change it to "near infinite-world* block sandbox game engine"

**Comment by paramat** [comment]
LOL =D Even worse.

Perhaps we can mention modding. The README decription is:

"Minetest is a free open-source voxel game engine with easy modding and game creation."

**Comment by rubenwardy** [comment]
I'm not too sure that we should be removing hints to MTG before the menu is changed to make it more obvious to install new games

**Comment by paramat** [comment]
I cannot see any harm for users, as this text is irrelevant for users.
The text is only really seen by contributors and developers. As MTG is feature-frozen, it seems wrong to have links that direct contributors to it, as if it were still in full development.

**Comment by rubenwardy** [comment]
it will also be seen by users cloning Minetest

**Comment by paramat** [comment]
Thanks =)
