### ISSUE TITLE
Rethink use_texture_alpha changes

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#10342]
(see also https://github.com/minetest/minetest/pull/10122#issuecomment-678461977, this is mostly a reminder to myself)

### Summary
Unlike I previously assumed, `use_texture_alpha` does not just decide between opaque and transparent.

Depending on drawtype, it:
* switches between opaque and transparency (`normal` and since the PR: `mesh`, `nodebox`)
* switches between "basic" alpha and transparency (all others)
* is ignored (unclear if this actually happens, for liquid maybe?)

Where:
name | mt | irrlicht | description
---- | -- | -------- | -----------
opaque | `TILE_MATERIAL_OPAQUE` | `video::EMT_SOLID` | opaque regardless of any texture alpha
basic alpha | `TILE_MATERIAL_BASIC` | `video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF` | opaque if pixel alpha < 128, fully see-through if alpha >= 128 
transparency | `TILE_MATERIAL_ALPHA` | `video::EMT_TRANSPARENT_ALPHA_CHANNEL` | pixel alpha = how much see-through it is

### Possible fix

First, the behaviour should be accurately documented (obvious).

<b>Option 1:</b>
Revert the change, easy but doesn't achieve the initial goal.

<b>Option 2:</b>
Give mods full control if material should be opaque, basic or transparent.

Requires backwards compatibility both on the protocol level (`alpha` in tiledef) and mod level (`use_texture_alpha` in nodedef).
firelike, plantlike, allfaces, glasslike should default to "basic"; normal to "opaque" (like before).
mesh, nodebox should default to "opaque" (this is different) and mods should be required\* to explicitly declare if they want transparency for those.

\* With backwards compatibility period as added in the PR

**Comment by Emojigit** [comment]
I think the option 2 is better, here is my suggestion:
 - add `EMT_way` option to node, that can use `solid`, `alpha_ref` and `alpha` (Follow the naming rules that using on irrlicht.
 - Mark `use_texture_alpha` outdate, give a warning to user, then suggest use `EMT_way = alpha` instead.

**Comment by SmallJoker** [comment]
I wonder whether there's not already enough information provided with the current options.

Sorted by lua_api appearance:
 * normal, signlike, fencelike
    * "opaque" only
 * liquid
    * default "transparent"
    * "opaque" depending on liquid alpha setting
 * glasslike, allfaces, torchlike, plantlike, firelike, glasslike, raillike, nodebox, mesh
    * default "basic"
    * "transparent" depending on `!backface_culling || use_texture_alpha`
