### ISSUE TITLE
Make nodes dynamic as entities.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10347]
I suppose this topic was probably already discussed before. For now nodes are quite static. It is really weird and uncomfortable, especially when you want to change only some properties, e.g. textures, model, lighting level and etc. Instead, you need to register new nodes and sometimes even a whole bunch of them. It only senselessly clutters up a space in a file, blowing out in few times than necessary, a senseless waste of memory and time. If they were dynamic, it would allow to access and change their properties right at run-time, maybe via a metatable like entities.

I don't know how hard it would be to implement, but I consider this will be a breaking change.

**Comment by numberZero** [comment]
That seems to be total rewrite. Currently, all node properties (except of rotation, etc.) are stored in a single place: node definition (ContentFeatures in C++). Map node itself only contains a (16-bit) reference there (node meta is stored separately, and isn't even available in mesh generation), plus two (8 bit each) parameters for light levels (day and night) and special property (rotation, color, etc.).

**However,** it's totally possible to allow e.g. 256 different models for a node type in the current system. Or arbitrary "facedir" rotation *and* 8 different texture sets. Take a look at colored_facedir for a similar example. See also #2746 for one of your requests.

**Comment by paramat** [comment]
Nodes are meant to be static, and the simplicity of nodes enables MT to do what it can do. Entities are there for the less common occasions where dynamism is needed. So how things are is good design.
Registering alternative nodes and swapping nodes to change properties may seem inconvenient to a modder, but is far outweighed by the advantages of engine simplicity.

Altering node properties in-game has been requested many times. Implementations have been tried, although there have been problems. See #36 #3528 #7848 (your issue) #9019 #2107 #5420 #323
