### ISSUE TITLE
Enable warnings and fix them

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10346]
Minetest uses a pitiful warning level that doesn't really reveal any issues.

The following warning flags are the set I use in my projects:

* Basic set: `-Wall -Wextra -Wnon-virtual-dtor -Wnull-dereference`
* Disable pointless warnings: `-Wno-unused-parameter -Wno-reorder -Wno-sign-compare`
* GCC-only warnings: `-Wmisleading-indentation -Wlogical-op`

Here's a commit where I enable the warnings: https://github.com/rubenwardy/minetest/commit/68978b80958ea19711e94060c14ccbb39dec352d

This would be a easy first task to learn the code base (albeit boring)

**Comment by rubenwardy** [comment]
This is probably a lot of work which may only fix a few bugs. It's a shame it can't just be enabled for new code

**Comment by sfan5** [comment]
Since I wondered, here's what `-Wnon-virtual-dtor` complains about: https://stackoverflow.com/questions/8764353/#answer-8764393

**Comment by rubenwardy** [comment]
Yeah, that can detect memory leaks when you destruct a polymorphic class. It's found a few memory leaks in my game

**Comment by numberZero** [comment]
To clarify:

* What you call "memory leak" is in fact UB. It will manifest itself e.g. if the child class makes some references to itself that it cleans in the destructor (in particular, if it starts a thread that accesses the object, and is joined in the destructor).
* On sign compare, sure it doesn't matter if both operands are in fact positive (including zero). But remember that while `-1 < 1` obviously, `-1 > 1u` according to the C(++) rules.
* Initialization order may only matter if there are references involved
* Unused parameters may only appear validly if the signature is defined from the outside, and invalidly if e.g. something is misspelled. It may be silented by not naming the parameter, or by something like `void(parameter_name)` which stands for an explicit mark that the parameter is in fact not needed.

Enabling warnings for some files only is possible but not straightforward:
* It's possible to group related files into object libraries, and set compiler parameters for each separately. The grouping should be logical and not age-based, however, or that will only increase mess.
* It's also possible to disable warnings for too noisy files using `#pragma`. It may not be trivial to add such pragmas and not cause more warnings in e.g. MSVC, though.

**Comment by rubenwardy** [comment]
CMake allows you to set flags on specific C++ files, I use it in the branch to disable warnings on jsoncpp.cpp

**Comment by HybridDog** [comment]
Here is another gcc warning: `-Wdouble-promotion`
It shows warnings when a float is implicitly converted to double because of a multiplication with a constant number without `f` suffix. (#6974)

**Comment by HybridDog** [comment]
Some generated warnings: [make_errs.txt.zip](https://github.com/minetest/minetest/files/5190420/make_errs.txt.zip)

**Comment by darnuria** [comment]
I suggest also gcc10 `-fanalyzer` option great at finding bugs at compile time, may need a warning it consume a LOT of memory on C++. :)
