### ISSUE TITLE
Mesh looks like fully darkened.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#10354]
##### Minetest version
```
Minetest-5.4.0-dev-1eaff3dfa
```

##### Summary
Title says about all. 
![Screenshot_20200830_193254](https://user-images.githubusercontent.com/25750346/91664457-15fe5580-eaf8-11ea-99de-d703a1e645a3.png)

My registration code: https://pastebin.com/HAN0JqGX

Blend file: [grand_piano_new.zip](https://github.com/minetest/minetest/files/5147131/grand_piano_new.zip)
Texture: [luxury_decor_grand_piano.zip](https://github.com/minetest/minetest/files/5147132/luxury_decor_grand_piano.zip)

**Comment by rubenwardy** [comment]
Have you set the normals correctly?

**Comment by Andrey2470T** [comment]
Yes, they are always facing outside:
![Screenshot_20200830_194931](https://user-images.githubusercontent.com/25750346/91664769-f6682c80-eaf9-11ea-8252-e2b6d29e510d.png)

**Comment by paramat** [comment]
Seems like yet another "my mesh does not work therefore i assume an engine bug" issue, you have opened a few of these, all of which were not engine bugs: #9013 #10079 
Did you ask for help and discuss in the forum first? if not this should be closed.
Close in 1 month if no reproduction by others.

**Comment by Andrey2470T** [comment]
Firstly, such issue has not been created neither by me nor by another members yet, therefore I created it. I would not create if similar issues were already here. Secondly, those issues which you listed don't quite concern to this, they are about other problems. And thirdly, it can not be closed, even if I didn't ask for it on the forums, because *potentially* it may be really an engine bug ad the problem is not to me.

**Comment by NathanSalapat** [comment]
![screenshot_20200830_172214](https://user-images.githubusercontent.com/8930456/91670697-64562900-eae5-11ea-89f0-dc8e1387c8ce.png)
Works just fine for me.
I did export the piano as an OBJ, and used this code.
```minetest.register_node('new_mod:piano', {
   description = 'piano',
   drawtype = 'mesh',
   mesh = 'grand_piano_new.obj',
   tiles = {'luxury_decor_grand_piano.png'},
   groups = {oddly_breakable_by_hand=2},
   paramtype = 'light',
   paramtype2 = 'facedir',
   selection_box = {
      type = 'fixed',
      fixed = {-.5, -.5, -.3, .5, .15, .4},
      },
   collision_box = {
      type = 'fixed',
      fixed = {-.5, -.5, -.3, .5, .15, .4}
      },
})
```
