### ISSUE TITLE
Allow disabling pointing altogether

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10355]
## Problem

Pointing can not be disabled for tools: `range = 0` or `range = nan` result in pointing still working inside nodes

## Solutions

`range = nan` or `range = false` should disable pointing

## Additional context

Sometimes one wants to disable pointing for i. e. magazines

**Comment by sfan5** [comment]
> `range = nan`

NaN is never a valid value for any property. For this feature request I suggest `range = -1`.

**Comment by appgurueu** [comment]
> > `range = nan`
> 
> NaN is never a valid value for any property. For this feature request I suggest `range = -1`.

Fine by me.

**Comment by paramat** [comment]
Good feature.

**Comment by paramat** [comment]
See duplicate #6651 and note:
> There's also a bug: If you set range=0 for the hand, it does not work at all. The range remains at the default 4 if you have the hand selected, but the range is 0 if you have an item on hand (e.g. cobblestone).

**Comment by appgurueu** [comment]
Closing this then.
