### ISSUE TITLE
Chat may overlap with infotext if recent_chat_messages is greater than 8

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10364]
##### Minetest version
```
5.3.0
```

##### OS / Hardware
Operating system: GNU/Linux

##### Summary
If you increase the setting `recent_chat_messages` to a value greater than 8 or 10, the chat will overlap with the infotext. It's 8 when you have debug mode enabled.

For all practical purposes, this basically means you cannot set this setting higher than 8, otherwise, you get an annoying overlap. This is not much higher than the current value of 6.

##### Steps to reproduce
* Set `recent_chat_messages` to 10
* Start game
* Spam the chat
* Optional: Enable debug mode (Adds an offset to the chat messages)
* Point to a node that has an infotext set

Expected: Infotext and chat do not overlap
Actual: Infotext and chat overlap

**Comment by LoneWolfHT** [comment]
PR that fixes this https://github.com/minetest/minetest/pull/10361

**Comment by Wuzzy2** [comment]
This was just a huge coincidence. I didn't see your PR before I wrote this.

**Comment by paramat** [comment]
I guess the maximum value of `recent_chat_messages` that avoids overlap with infotext depends on game window size, so any enforced maximum would be incorrect for many users.
This suggests we should not set a maximum and just let users set the value that avoids overlap with infotext.
Perhaps this is why the 2 elements can overlap?

So, do users need a chat element long enough to overlap with infotext?
If not, there is no problem here and it is fine as it is.
If they do, i guess the least harmful change would be to just move infotext text box downwards to be to the left of the cursor, which visually seems more suitable. Does anyone know of mods or games that use that area at a time when infotext must also be seen? I suspect this would be a rare occurrence, so it might be worth a little breakage.

**Comment by Wuzzy2** [comment]
As I said, a collision occurs at 10 already (only 4 more than the default) and if debug mode is on, it collides at only 8. This is extremely low and makes the `recent_chat_messages` setting practically useless.
The window size is mostly irrelevant, as the infotext seems to be placed at a constant pixel offset from the top of the window.
This can be easily verified by just testing it in Minetest.
Window size might only become a problem theoretically for very small windows (tiny height), but that's not how Minetest is supposed to be played anyway.

I am worried that placing the infotext too close to the cursor might make it too distracting. Not sure about that. Needs testing. I don't think there are any mods that need this area to be empty, however.

But then, games should eventually be able to customize ALL HUD positions (chat, minimap, status text, infotext) anyway instead of hardcoding them. But this is off-topic. Even with customization, a sane and functional (!) default is obviously required.

**Comment by Wuzzy2** [comment]
Just to be clear: Yes, there is definitely at least one player who wants longer chat: Me. I think the current `recent_chat_messages` default value of 6 is too low on very busy servers (>50 players), because the chat scrolls past so fast, you have no chance of reading, and pressing F10 every time gets tiresome very quickly. :P So for those servers I'd like to set it to 12 or so, but I can't really do that because of infotext overlap, and I am practically limited to 8 only.
