### ISSUE TITLE
Increment formspec/protocol version at every release to indicate client version

### ISSUE THREAD

**Issue by Bastrabun** [minetest/minetest#10368]
##### Minetest version
```
5.3.0
```

##### Summary
As of https://github.com/minetest/minetest/pull/8616 there should be a version_string in the player information, indicating the client version (or at least of what version the client believes to be). At least in 5.3.0 this doesn't show up in the table returned by get_player_information

If that information is meant to be present only in the debug-build, then ... why? Hardly anyone runs debug builds and we need that information to sanely address different client versions. Neither protocol version nor formspec version can stand in for that. See reasons.

##### Steps to reproduce

minetest.chat_send_all(dump(minetest.get_player_information("singleplayer"))

##### Reasons

We need a way to tell client versions apart. I ran into this problem when I wanted to know whether a client could make use of a scrollcontainer. This control was added in 5.3.0 and I want a way to deliver fs1 to 5.2.0 and fs3 to 5.3.0. How would I do this?

A fellow modder added: for example: how do I tell whether entity attachments are actually working?  They were broken badly in 5.0, broken mildly in 5.1-5.2, and finally work in 5.3, and there aren't protocol version bumps that correspond to those points.  Whether or not I use attachments may be affected by how well I expect them to work.

Another example: image_waypoints were introduced in 5.3, and are ignored in 5.2-.  I may want to display image waypoints to 5.3 clients, but fall back to text ones for 5.2, but again this feature did not result in a protocol bump, so how can I tell which one I need to use?

The client should send the server a version string, and the server should make it available to mods, and mods should test it against known formats, and expect unknown formats and try to do something sane for those (i.e. don't crash the whole server) but that's the modder's responsibility.

##### Alternatives

Another fellow modder (who also happens to be a core dev) added: Or we could bump formspec version everytime we a add a new feature to formspecs and protocol version everytime we add client features.

**Comment by SmallJoker** [comment]
The best approach for this is to check against the client's supported formspec version:
https://github.com/minetest/minetest/blob/6dcc9e63318f815a3de8c9db2ee7b845066e0135/doc/lua_api.txt#L4341

For other features, check against the network version. Both numbers are increased every now and then, but aren't entirely reliable. However, in this case you can safely check against version 4.

https://github.com/minetest/minetest/blob/6dcc9e63318f815a3de8c9db2ee7b845066e0135/src/network/networkprotocol.h#L236-L240

Relevant: #6114
There should not be any way to check the client's version. It can be manipulated and Minetest forks will somewhat dislike it.

**Comment by Bastrabun** [comment]
That's what I thought, but I did check against the clients supported formspec version.

5.2.0 doesn't have scrollcontainers, but returns formspec_version3
5.3.0 returns formspec_version 3 and has scrollcontainers

I had something along 

`if formspec_version >= 3 then use scrollcontainers else don't.`

Same goes for protocol version. Currently, there is no way to tell 5.2.0 and 5.3.0 apart serverside.

You can try yourself, open this in 5.2.0 and 5.3.0 

I dare you come up with a check that let's me avoid it:

```
local function fs()
    local formspec = {
        "formspec_version[3]",
        "size[20,15]",
        "container[2,0.75]",
        "scrollbaroptions[min=0;max=14;smallstep=1;largestep=2;arrows=show]",
        "scrollbar[0.2,5;0.2,5;vertical;scr0;0]",
        "scroll_container[0,5;20,5;scr0;vertical;1]",

        "button[1,2;5,1;;Text Button 1]",
        "button[1,3;5,1;;Text Button 2]",

        "scroll_container_end[]",
        "container_end[]"
    }
    return table.concat(formspec, "")
end



minetest.register_chatcommand("testfs", {
    params = "",
    description = "",
    privs = {},
    func = function( name , param)
  

      minetest.chat_send_all(dump(fs()))
      minetest.chat_send_all(dump(minetest.get_player_information("singleplayer"))
      minetest.show_formspec(name, "wth:fs", fs())
  
    end,
  })
```

Btw, I can check against "version 4" ? If you mean formspec_version 4, then I'm sorry there is no such thing in any of the released clients or I was too stupid to find it. If formspec version is in 5.4.0, then how does that help me to tell 5.3.0 and 5.2.0 apart?

I don't mean to detect dirty clients or non-standard or anything. I want a "mostly reliable" value whether something is in or out. Should a client fake its version string and tell me it's 5.3.0 while in fact its 5.0.0, then things go awry. But that's to be expected and needs to be dealt with mod-side.

I'd prefer a non-100% reliable information that no information at all. I'd like to be able to choose myself. Make a big red warning sign on that feature, but in some cases, such as mine, I don't see any other way - except bumping formspec_version EVERY time a new feature is added.

**Comment by Warr1024** [comment]
> ...Perhaps it would make sense to introduce more rules _when exactly_ a version number has to be increased.

I would be happy with this as an alternative.  For example, any time a public release is made that include _any_ change (including bug fixes or cosmetics) the proto version would get a bump.  We have 64ki of these so it's not like we're gonna run out.  Then becomes possible for mods to tell what state a particular feature is in, or how they can expect each client to interpret or present certain things.

The 5.3.0 release, which fixed a number of existing features such that I can actually safely use them, is a good example.  If the proto version had been bumped then, that would have been enough to differentiate when certain features, like image_waypoints, can be used.

Not having a way to differentiate versions forces modders to either NOT use new features until they're ready to retire support for old versions, or require users to upgrade immediately to support those features (but without having a way to actually enforce this upgrade).  Both of those options make the experience worse for the players than being able to support the new feature with an automatic sane fallback based on version detection would.

**Comment by hecktest** [comment]
Some form of version detection is clearly needed.
Ideally I'd like to boot every player who isn't on latest stable and then tell them to update, because they're going to get a very nasty experience otherwise and maybe even incorrectly blame it on the server.

**Comment by sorcerykid** [comment]
This applies to issue #10172, as there are a number of non-working features that may be essential to gameplay. And not only is there no documentation about whether certain features actually work in any given version (apparently you have to download each client and test for yourself), but also there is no way to detect whether the client version is adequate.

**Comment by paramat** [comment]
Getting client version string was discussed and disapproved by 2 core devs in #8616

**Comment by rubenwardy** [comment]
I support adding rules to update formspec_version / protocol_version on every applicable release, to allow mods to reliably detect client version. It doesn't fix the issue of telling 5.2/5.3 apart, but is cleaner for the future

**Comment by paramat** [comment]
^ That is a better approach for this request.

This issue should be closed soon as it is previously disapproved. Perhaps a new issue could be opened for rubenwardy's suggestion?

**Comment by Bastrabun** [comment]
formspec_version obviously failed to tell 5.2.0 and 5.3.0 apart, what's the official Minetest solution to this use case?

If the engine does not provide a version_string, mod makers need to resort to trickery to find out that version, most likely resulting in a bad experience for users and mod makers.

Can clients lie about their formspec_version and protocol_version? If so, this invalidates the "clients can lie about their version_string" point.

It is no weakness to be able to deliver different content to different clients, be they multicraft, official minetest or whatever.

By closing this issue, the problem won't go away. Please do not build future Minetest on the Holy Decisions made in the past.

For future releases, bumping formspec_version on every formspec change (bugfix/feature/documentation/...) and protocol_version alike will solve the problem for future versions, so I'd be happy if you did that additionally to providing a version_string.

**Comment by v-rob** [comment]
As for `scroll_container`, it is a mistake to allow new elements to be created without increasing the formspec version.  This has also happened with `background9` and will happen for `model` and other PRs if nothing is done.  The best solution (IMO) is to increase the formspec version for each new element and use `errorstream` instead of `infostream` for unknown elements.

**Comment by paramat** [comment]
> Can clients lie about their formspec_version and protocol_version? If so, this invalidates the "clients can lie about their version_string" point.

I think the reason this is suggested is because these are much less likely to be faked by a client, as doing so affects the server-client communication and can break things.
> If the engine does not provide a version_string, mod makers need to resort to trickery to find out that version,

A client version string will be faked by clients and useless anyway.

We will not close this without some record of the discussion and new suggestion. That is why i asked for a new issue for that. However ...
> For future releases, bumping formspec_version on every formspec change (bugfix/feature/documentation/...) and protocol_version alike will solve the problem for future versions, so I'd be happy if you did that additionally to providing a version_string.

As you are also requesting formspec/protocol version incrementing at every release, and as client version string is disapproved twice, i will change the issue title and keep this open.

**Comment by paramat** [comment]
Took me a while, but i now realise the reason why a client version string is not useful. See https://github.com/minetest/minetest/pull/8616#issuecomment-509574692 :
> The problem is that the version string can be any arbitrary string.

As there is no standard or required format a mod cannot know how to interpret the string.
If a MT fork uses one format now it might change that format, and is highly likely to change that format if we provide the client version string to mods as forks will then suspect they are being discriminated against.

Formspec/protocol version has a specific format, an integer, so mods know how to interpret it.

**Comment by Bastrabun** [comment]
While the version_string CAN be any arbitrary string, it usually isn't - at least I hope on official builds the version_string is a representation of the version.

If I went to my car dealer and asked for a spare part for GenericCar 5.3.0 while in fact I only had a GenericCar 5.0.0, I doubt I could hold the dealer, the manufacturer or anyone else liable but me if the spare part did not work. Also, if I told my car dealer I needed a spare part for UnknownCar 9.13, they'd probably take a guess and give me the fallback one.

With a version_string I could deliver not only customized formspecs but any specific content to any other forks as well, as long as they stick to some versioning scheme and I want to support them. If not: fallback.

Not having a proper version_string prevents me from serving official clients and forks to the best of my ability. I'd even go as far and kindly ask to include other values like screenwidth/height or platform (pc, android, gameboycluster, ...). I assume you want  a separate issue for those?

If the formspec_version and the protocol_version can be lied about, they're no better than a version_string. When a client says they use protocol_version 200 while in fact talking 39, they will not be served to the best their client could take. Same for a client string. But that's up to the one who lies about their client then, right?

**Comment by v-rob** [comment]
I don't quite see why lying about version strings/protocol/formspec version numbers is a problem... If someone changes the version string, then they will get the wrong personalized content.  Are there security issues that I can't see?

**Comment by paramat** [comment]
You are ignoring what has already been explained earlier in the issue.

**Comment by Bastrabun** [comment]
I am not convinced by your points, you are not convinced by my points. Let's leave it at that. You are a core dev and I am not.

Given the choice to keep harassing you about a feature request on the one side and saving you time so you can make 5.4.0 awesome, I choose the latter.

**Comment by v-rob** [comment]
I support incrementing the formspec_version, so the issue shouldn't be close completely.

**Comment by Bastrabun** [comment]
May I advise against keeping it open? This issue should be resolved after you write "Increment that thing!" into your release procedure.

Keeping it open will not only add clutter to the open issues, even worse, until the very last version of Minetest this issue has no chance of ever being resolved.

**Comment by rubenwardy** [comment]
I've updated https://dev.minetest.net/Releasing_Minetest#Before_releasing
