### ISSUE TITLE
CLI Server Console

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10379]
## Problem

If i want to run server commands on a server, i need to use the GUI to login.

But if my server is laggy because a lot of media, or i have no GUI access now, i can't run any chatcommands now.

## Solutions

The solution is to make a CLI console. Only those user with `cli_access` privs can access the CLI conosole.

### How it works
Use `/path/to/minetest/bin/minetest --cli_console --address server.host.name --port 30000` to access it.

Players will recive this join message:
```
** FooBar joined the game (via CLI Console)
```

In the CLI Console, you can talk to other player (even they are in CLI too), and run chatcommands. Like this (virtual thing):
```
Minetest CLI Console 5.4.0
Server Address: server.host.name port 30000
> (Type chat or command here)
```
User can use `Ctrl-C` To cancel the thing that you currenty typing. Use `Ctrl-D` to disconnect.
### More Details
 - I hope the CLI console can apply without change the server part.

**Comment by sfan5** [comment]
`minetestserver` offers a curses console for exactly this usecase.

**Comment by rubenwardy** [comment]
`minetestserver --terminal` when built with NCURSES
