### ISSUE TITLE
Custom URL Scheme

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10373]
It would be nice to have `minetest://...` links to simplify actions such as selecting a server or a package. Example routes:

* `minetest://select_server?address=&port=`: Navigates to server list & selects the server with matching address and port
* `minetest://package_info/<author>/<package>`: Shows the CDB package info for the given package. Useful for online "install" buttons.

**Comment by rubenwardy** [comment]
Duplicate of #7400
