### ISSUE TITLE
on_player_hpchange can't see true amount of damage if damage > hp

### ISSUE THREAD

**Issue by anon55555** [minetest/minetest#10377]
Because result hp is capped to 0 before hp change is calculated.

This means trying to implement armor that adsorbs >=50% of damage would make the player immortal.

**Comment by SmallJoker** [comment]
For other situations (static protection) you'd best use the built-in armor feature:
https://github.com/minetest/minetest/blob/0d128ab344e3d04d2b30dbd5e047f4ac700013b7/doc/lua_api.txt#L1917-L1928

Is your callback registered as a modifier? Those callbacks should be executed first, means you can return a value like `math.max(1, hp_change / 2)` to avoid immortal players.

**Comment by anon55555** [comment]
Yes it's a modifier, I'm experiencing the bug in MineClone 2. 

In MineClone 2 armor doesn't adsorb a constant percentage of damage, the percentage adsorbed depends on the amount of damage.

The callback is registered here: https://git.minetest.land/Wuzzy/MineClone2/src/commit/7bbb7438aefb30b12e4b998f6b40392e328f2f22/mods/ITEMS/mcl_armor/armor.lua#L492.

**Comment by anon55555** [comment]
The bug is in this function:
https://github.com/minetest/minetest/blob/0d128ab344e3d04d2b30dbd5e047f4ac700013b7/src/server/player_sao.cpp#L458-L480

`hp` is put through `rangelim` before `hp_change` is calculated.

**Comment by anon55555** [comment]
Isn't this a bug?

**Comment by anon55555** [comment]
Deleting the line `hp = rangelim(hp, 0, m_prop.hp_max);` fixes the issue, this patch is used on Clamity.

**Comment by SmallJoker** [comment]
This behaviour was reported as incorrect in #8462 and changed in #8494.
> Punching a dead player executes all the punch code, the on_punchplayer callbacks, and subsequently the on_hpchange callbacks, which is a bug, IMHO.

Both sides bring good arguments, but perhaps it would be more consistent to only skip the callback when the player's HP (`oldhp`) is already 0.
