### ISSUE TITLE
Distinguishing 5.2 and 5.3 clients

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10387]
## Problem

5.3 has added a variety of neat features to Minetest, which modders would like to take advantage of *while providing workarounds* for 5.2 and lower.

## Solutions

5.2 can be distinguished from 5.1 and below using the protocol version. This does not work for 5.3 and 5.2 however, as the protocol version has not been bumped.

## Alternatives

- Handle 5.3 the same as 5.2. Does not work for some cases (set_bone_position breaking changes), unnecessarily restricts 5.3 players.
- **Hopefully some hacky method to distinguish the two**

## Additional context

#10368 provides a solution for the future, but I need a solution for the past

**Comment by Desour** [comment]
>**Hopefully some hacky method to distinguish the two**

You can show the players a formspec with a scroll container with a button that is clipped away if the client doesn't know scroll containers (pre 5.3 clients), and only allow players to play that can press the button.

**Comment by appgurueu** [comment]
> > **Hopefully some hacky method to distinguish the two**
> 
> You can show the players a formspec with a scroll container with a button that is clipped away if the client doesn't know scroll containers (pre 5.3 clients), and only allow players to play that can press the button.

Yes, that is one option, but ideally I'd want something which does not require the players to do anything...

**Comment by paramat** [comment]
What about distinguishing 5.0.x from 5.1.x? Just doing this for 5.2.x/5.3.x is odd, if distinguishing past versions is so important (which it is not, as we have never been able to before), surely it should be done for all 5.x.x?

As this is not particularly important and a workaround exists, this is low prioriy and i am not convinced it is worth the effort.
Probably, by the time anything is merged, 5.4 will be released and this will not be of much usefulness.
Instead, how about we divert this effort into getting #10368 implemented in time for 5.4?

**Comment by appgurueu** [comment]
> we have never been able to do this before

Wrong. 5.1 and 5.0 can be told apart this way, same for 5.1 and 5.2. Only 5.2 and 5.3 can not be distinguished.

> a workaround exists

No, it doesn't.

> 5.4 will be released and this will not be of much usefulness

Except that either 5.3 or 5.2 and lower users will have a terrible experience (broken playeranim mods).

**Comment by v-rob** [comment]
This really isn't a feature request as it requests a feature that cannot be added (we can't time travel) and therefore doesn't belong on GitHub; asking on the forums would be more appropriate to find a workaround solution.

**Comment by sorcerykid** [comment]
I agree, this is not in the scope of the Minetest issue tracker. It's a general support request, more suitable for the Modding Discussion subforum.

**Comment by SmallJoker** [comment]
Do not distinguish between client versions. Please check against supported features to get it working properly for -dev versions and forks of Minetest.

-> #10368

**Comment by paramat** [comment]
> Wrong. 5.1 and 5.0 can be told apart this way, same for 5.1 and 5.2. Only 5.2 and 5.3 can not be distinguished.

What i meant by "we have never been able to do this before" is the general ability to distinguish for all client versions. I accept it might have been possible between certain version pairs.
> No, it doesn't.

I was referring to the workaround described above in https://github.com/minetest/minetest/issues/10387#issuecomment-691673827 , which you agreed was a workaround.
> Except that either 5.3 or 5.2 and lower users will have a terrible experience (broken playeranim mods).

The reason i suggested it becomes less important when 5.4.0 is released is because, apart from a group of servers/clients that are stuck at 0.4.16/0.4.17, most clients update to the latest version of MT quickly.
