### ISSUE TITLE
Add media alias

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10392]
## Problem

When I rename a media in my mod, other mods that use my media can't read that media then show a dummy image to the client.

## Solutions

If there have a media alias function, I can solve that problem without copy the file.
 - `minetest.register_media_alias(alias, original_name)`: just like `minetest.register_alias`, but make allias on media not item.

**Comment by NathanSalapat** [comment]
I have to wonder what the usefulness of this is, wouldn't it make more sense to just not rename media files?

**Comment by Emojigit** [comment]
For example, I have `technic` and `streets` mod on my server.

`streets` require a concrete image from `technic` mod, but the image was renamed or deleted

If that image was renamed, I can use the media alias to fix it.

**Comment by pyrollo** [comment]
As you still need to update your code (for adding alias), why not performing a global search/replace ?

**Comment by paramat** [comment]
Aliases are messy things to have to use, i do not like the idea of adding another type of alias. I think it is probably better to solve your issue another and more proper way, like just editing the mods.
The usecase explained above seems invalid and very low priority.

Recently i keep seeing requests for engine features that are workarounds for bad design or incorrect code in mods or games, or are based on unreasonable expectations. Some people seem to be lazy and are requesting engine features when instead the right thing to do is improving, rewriting, editing or forking mods or games.
This laziness pushes too much workload onto core devs and too much complexity into the engine, and also avoids mods and games being forced to improve.
