### ISSUE TITLE
Make "cannot connect" messages configurable

### ISSUE THREAD

**Issue by Bastrabun** [minetest/minetest#10390]
## Problem

The messages on the "some error occurred, you can't connect" dialogs are not configurable.

I'd like to show players who try to connect to my 5.x server with a 0.4.x client another message than the default

```
Access denied. Reason: Your client's version is not supported.
Please contact server administrator
```

I'd like to add in a message where this server administrator can be contacted, change the wording or simply add a "the" in the second line.

This has already been done for 
```

#    A message to be displayed to all clients when the server shuts down.
#    type: string
# kick_msg_shutdown = Server shutting down.

#    A message to be displayed to all clients when the server crashes.
#    type: string
# kick_msg_crash = This server has experienced an internal error. You will now be disconnected.
```

I'd like to be able to configure the messages on ALL other "error, can't connect" dialogs. 

## Solutions

Please make the messages configurable, much like the kick_msg_shutdown or kick_msg_crash.

**Comment by SmallJoker** [comment]
Some of the messages could be customized, though I wonder why you need this. If the wording is unclear, it should be corrected for all users and added to the client translations (locale).

**Comment by Bastrabun** [comment]
They are not unclear - they do state what's going on.

But they do not say what can be done to resolve the problem in general (like download a new MT version) or specifically for my server (contact this and that email address and describe your problem)

That's only one example of many cases where it comes in handy to inform a player of what's going on, especially when the player does not have any other means of contact except by asking an admin of the server - which they can't if they can't connect.

Imagine your train is not on time and you're told to ask the train conductor - who is ON the train :D

**Comment by SmallJoker** [comment]
> like download a new MT version

Yet this approach only works in one way. You'd need an old client to play on an old server - the correct text would be to notify the server owner about the update.

Custom texts could be implemented, but in particular for following error:
> Access denied. Reason: Your client's version is not supported.

..means that the server and client cannot establish a commonly accepted communication (there's no way to the train station). It is one of the first and most important information that's exchanged between server and client to ensure compatibility. Everything that follows after this version check can be added, changed or removed in a backwards-compatible manner.
