### ISSUE TITLE
Add Lua get game info function

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10391]
## Problem

If a mod wants to detect the gameid and the game version, it needs to detect the mods that only appear at that game.

## Solutions

Add these Lua function:
 - `minetest.get_game_id`: get the current game id, for example if i am playing MineClone2, The function returns `Mineclone2`.
 - `minetest.get_game_version`: get the current game's version from game.conf. If the game has no version value, use `nil`.
 - `minetest.get_game_path_by_id`: get a game's path by its id. For example, `minetest.get_game_by_id(minetest.get_game_id())` will return the current game path.

**Comment by Andrey2470T** [comment]
I prefer more something like single `minetest.get_game_info(gamename)` function that would immediately return a whole table with all important info about it (game_path, game_version, game_modslist and etc).

**Comment by sorcerykid** [comment]
The `game_id` should be all lowercase based on convention. If the human readable name is needed, then perhaps that could be provided as `game_name`. And yes, all of this information should be returned as a single table.

In my fork of the engine, this is how I retrieve the game ID: `config.game_id = core.get_gamepath( ):match( "^.+/(.+)$" )`

**Comment by rubenwardy** [comment]
This is already supported in the main menu, it would be a matter of adding it to the server env as well

**Comment by Emojigit** [comment]
> The `game_id` should be all lowercase based on convention. If the human readable name is needed, then perhaps that could be provided as `game_name`. And yes, all of this information should be returned as a single table.
> 
> In my fork of the engine, this is how I retrieve the game ID: `config.game_id = core.get_gamepath( ):match( "^.+/(.+)$" )`

You can't use this way to get minetest game's game ID. It's game id is minetest but usually it's game path is call minetest_game.

**Comment by sorcerykid** [comment]
This is news to me. Perhaps I missed the memo on that one.

According to this Wiki article, the game ID is the exact name of the game's subdirectory under "/Minetest/games/":

https://wiki.minetest.net/Setting_up_a_server

**Comment by rubenwardy** [comment]
It's always been that case - the `_game` is ignored when determining the game id

**Comment by SmallJoker** [comment]
What use-cases would those particular functions have? Currently you can check whether optional dependencies exist and use those to decide whether to add Mineclone2 content.

**Comment by chaojian-zhang** [comment]
> What use-cases would those particular functions have? Currently you can check whether optional dependencies exist and use those to decide whether to add Mineclone2 content.

Which function is that (for checking whether dependencies exist)?

I would like to know game name (either "devtest" or "minetest_game") so my mod can automatically switch between node names that it references.

**Comment by SmallJoker** [comment]
1. Put `mcl_somespecialmod` into your mod.conf -> `optional_depends`
2.
```Lua
if minetest.get_modpath("mcl_somespecialmod") then
	-- MineClone99 game detected
else
	-- default
end
```

**Comment by rubenwardy** [comment]
You should use the mods that contain the nodes as the modname there. For example, `default` for MTG

**Comment by sfan5** [comment]
Mods should not rely on the gameid to detect games and instead check for mods (and games should name the mods in some unique way, Minetest Game is the unfortunate exception to this).
But I support adding this API for informational purposes.

The only part that doesn't make sense is `minetest.get_game_path_by_id`: There is only one running game and any other installed games should be of no concern.

**Comment by rubenwardy** [comment]
The only API that's needed is `minetest.get_game_info()`, it should return a table with all the information in `game.conf` plus derived info like `id`
