### ISSUE TITLE
2 null bytes are appended to every TOCLIENT_BLOCKDATA packet

### ISSUE THREAD

**Issue by anon55555** [minetest/minetest#10403]
##### Minetest version

```
5.3.0
```

##### Summary
https://github.com/minetest/minetest/blob/9ec75d77651c333eca3c5b46a3a56c8353fed464/src/server.cpp#L2336
2 null bytes are appended to every TOCLIENT_BLOCKDATA packet because this line of code adds an extra 2, it only needs 3 * 2 for a v3s16.

##### Steps to reproduce
Look in Wireshark while playing Minetest on a server, there's always `00 00` on the end of every `TOCLIENT_BLOCKDATA` packet.

**Comment by luk3yx** [comment]
Can this be closed?
