### ISSUE TITLE
on_generated gets called multiple times with the same chunk if "num_emerge_threads" is greater than 1

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/minetest#10409]
##### Minetest version
```
5.4.0-dev-3fb1f4530
```

##### Summary

Currently if you increase the `num_emerge_threads` to a value greater than 1 the lua mapgens get called multiple
times with the same chunk.
The call-count is usually less or equal to the number of emerge-threads but not really consistent.
This has some lag-inducing aspects if there are quite a few lua-mapgens registered.

##### Steps to reproduce

Add the following mod besides the default game (any version):
```lua
-- table of minp-hashes<int> => count<int>
local already_generated_chunks = {}

minetest.register_on_generated(function(minp, maxp)
  -- hash minp edge
  local hash = minetest.hash_node_position(minp)
  if already_generated_chunks[hash] then
    -- minp already processed before
    -- increment call count
    already_generated_chunks[hash] = already_generated_chunks[hash] + 1
    print("Already generated chunk at: " .. minetest.pos_to_string(minp) .. " count: " .. already_generated_chunks[hash])
  else
    -- initialize call count
    already_generated_chunks[hash] = 1
  end
end)
```

Observe how the chunks are passed multiple times to the `on_generated` function:
```
Already generated chunk at: (-192,-112,-272) count: 3
Already generated chunk at: (-272,48,-272) count: 2
Already generated chunk at: (-192,48,-272) count: 2
Already generated chunk at: (-32,-32,-272) count: 2
Already generated chunk at: (-32,-112,-272) count: 2
Already generated chunk at: (-32,-112,-272) count: 3
Already generated chunk at: (-32,-112,-272) count: 4

```

**Side-note**: i added a few log-statements to the engine-emerge thread and it looks like those get called only once with the same mapblock.

##### Related issues

* #9627

**Comment by paramat** [comment]
Interesting, and yes this would be a disaster considering how intensive Lua mapgen stuff can be. We have noticed some other bugs caused by num_emerge_threads > 1. Until recently it was advised to set this to 1.

**Comment by FriendlyGamer** [comment]
> Until recently it was advised to set this to 1.
Interesting, I thought it was still recommended to stick it at one. I have four total cores (400%) to this server alone, is it now considered safe and efficient to increase this for further mapgen performance?

**Comment by sfan5** [comment]
Can't reproduce inside devtest or minetest_game.

**Comment by BuckarooBanzay** [comment]
> Can't reproduce inside devtest or minetest_game.

Interesting: i tested it again with the repro-mod above on c47313db65f968559711ac1b505ef341a9872017 and could only provoke it twice while flying around about 5 minutes (and "pausing" the singleplayer game, not sure if relevant though)

Anyway, looks like the situation has been improved, closing this until i can reproduce this reliably.

Thanks for all the work :heart:

**Comment by sfan5** [comment]
It should happen exactly zero times not "only twice". But if you find more details on how this can be reproduced I'd appreciate them.
