### ISSUE TITLE
Customize HUD properties of chat, infotext, status text, minimap

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10400]
## The problem

Currently, the GUI positions and other properties of chat, infotext, status text and the minimap are hardcoded.
This is a problem because it limits games in how they design the GUI.

## Suggested solution

I suggest to make it possible for games to customize these positions on a per-player basis.

## Implementation

One possible implementation for this is by extending the `player:hud_replace_builtin` function.
Introduce the builtin builtin HUD names `chat`, `infotext`, `statustext` and `minimap`.
For `hud_definition`, only the following fields are accepted (all other fields are ignored
and can't be changed):

* `pos`, 
* `offset`
* `z_index`
* `alignment` for text-based HUD elements
* `size` for changing the pixel size of minimap

## Why not debug screen?

The debug info is intentionally NOT included in this suggestion. This is intentional. Why? Because debug info must always be functional, in every game, and games should not be given the chance to break debug. A game that manages to break debug would be really nasty.

**Comment by pyrollo** [comment]
My opinion is that all HUD element should be Lua driven. With a default in `builtin`. There

Minimap is already on its way : https://github.com/minetest/minetest/pull/9079

**Comment by paramat** [comment]
Related #7632 #10364 #10372 
I support at least some of this.

**Comment by Zughy** [comment]
Closing this since there are already specific issues for chat and infotext (what's status text? In case, just open a new issue). Minimap is already available
