### ISSUE TITLE
Weird slowdowns with Minetest client

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#10418]
##### Minetest version
```
5.3 -> Minetest 5.4.0-dev-9ec75d776-dirty (Linux)
```

In case you need my system specs:
![image](https://user-images.githubusercontent.com/28972859/93840339-efd65c00-fc44-11ea-9ee9-bd98a3e6bf94.png)
```
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.0.8
```

##### Summary

My client suddenly slowed down to the point where it was like the whole thing was running at 1 FPS while I was playing Nodecore.
Opening things like the chat or pause menu took 1+ seconds. Letters typed into chat took 1 second to appear.
Debug menu also took a few seconds to pop up. This is what it showed:
![image](https://user-images.githubusercontent.com/28972859/93839645-6de53380-fc42-11ea-98ad-1400bc66b492.png)

My FPS still displayed as a pretty steady 75 (My monitor is 75Hz and my GPU won't let Minetest go past that).
The screen was going at 1FPS or less.
Sounds seemed to be on time.
My main menu is also limited like that after exiting the game.

The problem goes away when I turn off my internet connection. And it returns when I reconnect to the internet
#
Here's a GIF I took of the issue in action. The FPS I recorded at is fine. That's what my client actually looks like.
Also note the debug info saying I'm running at 75 FPS
![Peek 2020-09-21 19-49](https://user-images.githubusercontent.com/28972859/93840004-b0f3d680-fc43-11ea-8fc3-1c65327df5aa.gif)

**Comment by SmallJoker** [comment]
After which time does this slowdown occur?
 - Always, also in main menu?
 - After a certain time?
 - Only when you are/were crafting?
 - Always 4 days after reboot?

Since when does it occur?
 - Since 20.04 upgrade/install
 - Somewhen last week

I find it very strange that these delays aren't reported in the debug graphs - which might be caused by bad Irrlicht timers. Could you please check whether Irrlicht 1.9-dev works better?

**Comment by LoneWolfHT** [comment]
> After which time does this slowdown occur?

This has never started in the mainmenu
This has only happened twice over the space of a few months, usually after at least 10 minutes of gameplay I think.
I don't think uptime/crafting is related.

> Since when does it occur?

Minetest 5.3, or before and after my upgrade to 20.04. Note that the upgrade was actually a complete reinstall of my OS.

**Comment by LoneWolfHT** [comment]
Not sure where I can get my hands on Irrlicht 1.9

**Comment by lhofhansl** [comment]
I've never seen a slowdown that was not also reflected in the FPS counter. This is strange, indeed.

Is there anything strange in the tracing numbers? (the ones you get by pressing F6)
Larger number of entities or active objects?

**Comment by LoneWolfHT** [comment]
> Larger number of entities or active objects?

Don't think those would affect the main menu

**Comment by hecktest** [comment]
Next time this happens, check the memory usage.
