### ISSUE TITLE
Custom Theme

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10435]
## Problem

If a new default theme (for example minetest/minetest#6733), you may want to change to another theme (or you can change to the new theme while the theme now is the default)

## Solutions

I think we can have some "theme pack", that with a lot of file contains theme.

For example:
 - `mainmenu.txt` Contains main menu formspec
 - `default_back.png` replace the default background (which default == cloud)
 - `mainmenu.lua` contains the lua script need to run before show the main menu

### TXT Special Methold
 All of these Methold have `$<` Prefix
 - `get_txt_content(filename`: Get file content
 - `get_theme_path`: Get the theme Path
 - `setvar(varable_name`: Set a varable
 - `getvar(varable_name`: Return a varable content
 - `nil`: get a nil content (Useful To delete a varable)

### Special prefix
 - `$!`: Comment
 - `$#(log_level)`: Show log to console and `debug.txt`
 - `$![[`: Long coomment, use `]]!$` to end

**Comment by rubenwardy** [comment]
:-1:

Users can change the mainmenu by replacing the scripts, using the mainmenu script path setting. In the future, I intend to allow games to provide Lua scripts for the main menu. This scripts will be able to customise their main menu, adding or changing pages, etc.

**Comment by SmallJoker** [comment]
Please not yet another format. If even, then try implementing a function to customize formspec prepends in the main menu.
