### ISSUE TITLE
Server: Received TOCLIENT_SRP_BYTES_M.

### ISSUE THREAD

**Issue by anon55555** [minetest/minetest#10434]
##### Minetest version

```
5.3.0
```
##### Summary
`Server: Received TOCLIENT_SRP_BYTES_M.`
Me: No you didn't, you received TOSERVER_SRP_BYTES_M.

##### Steps to reproduce
Look for `Server: Received TOCLIENT_SRP_BYTES_M.` in logs (log level must be verbose).

**Comment by paramat** [comment]
Confirmed:
https://github.com/minetest/minetest/blob/0d128ab344e3d04d2b30dbd5e047f4ac700013b7/src/network/serverpackethandler.cpp#L1659
A simple mistake in the message string, easily fixed.
