### ISSUE TITLE
Regression: / key not working anymore

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10440]
##### Minetest version
```
Newest Ubuntu 20.04 dev build (5.4-dev)
```

##### Summary
Using <kbd>/</kbd> to toggle the chat no longer works, despite having proper keybinds configured: instead, it switches to the seventh hotbar slot (<kbd>/</kbd> is </kbd><kbd>shift</kbd> + <kbd>7</kbd></kbd> on my keyboard).

##### Steps to reproduce
Try entering a chatcommand.

##### Additional Info

I suspect #10419

**Comment by NathanSalapat** [comment]
I had the same issue. I changed the keybinding via the menu and the / key reported itself as being OEM2, and started working again.

**Comment by lhofhansl** [comment]
I can confirm. Re-entering the key solved it... Names the key "OEM2" as @NathanSalapat mentions.
US laptop keyboard in case that matters,

**Comment by Seirdy** [comment]
Same issue, as of 65c15e1

**Comment by Emojigit** [comment]
This bug was awful which makes me have a lot of trouble while testing mods with chat commands.

**Comment by rubenwardy** [comment]
I can reproduce this, weird

**Comment by hecktest** [comment]
yup, OEM2 instead of /, happens on a plain USB keyboard too

for what it's worth, numpad + and - also stopped working and must be manually bound

**Comment by paramat** [comment]
I can confirm.
> numpad + and - also stopped working

Yes i noticed that too.

Also, a while ago, while numperpad + and - were still working, i found i could no longer hold down + or - to continuously adjust view range, you now have to repeatedly press changing by 10 each time.

So 3 annoying changes =)

**Comment by hecktest** [comment]
Not long before this, num + and - would stop working entirely after one press until the focus was reset. You had to do something like open the chat and close it to make them work again, over and over.
