### ISSUE TITLE
Add option to have shift-click not move items to hotbar.

### ISSUE THREAD

**Issue by johalun** [minetest/minetest#10452]
## Problem

Shift-click is a wonderful feature that moves stacks of items to/from inventory and chests or crafting interfaces. However, I don't like that it is filling up my hotbar first. I'd like to keep the hotbar space reserved for the things I choose to move there.

## Solutions

Make the default behavior of shift-click avoid moving items to the hotbar and instead prioritize the 24 inventory slots.  

## Alternatives

Add an option in settings to toggle this behavior.

**Comment by paramat** [comment]
I prefer to not add a setting as it seems too low priority to do so. So i prefer we choose either hotbar or inventory to prioritise.
My preference is what you request for the reason you give.
:+1:

**Comment by Zughy** [comment]
I disagree with Paramat. If I want to easily retrieve something from creative inventory, I'll just shift-click on it. Same if I'm playing a minigame like skywars where time is crucial. Things should go into the hotbar first

**Comment by rubenwardy** [comment]
I prefer it going into the hotbar by default, as that is usually what I want - and what I imagine most players will want

**Comment by jamesalexanderstevenson** [comment]
Use style[] to specify listring[] destination?

**Comment by paramat** [comment]
I am not sure anymore, both behaviours seem useful, but i also disagree with adding complexity with making it optional.
I think we should leave it as it is, which is probably the majority preference, there have been few or no requests to change this.
Removing by support.

**Comment by johalun** [comment]
For creative maybe yes, for survival it's quite annoying that it populates the hotbar first. Hmm, maybe like someone suggested, a shift-right click or some other combination could prioritize the inventory?

**Comment by hecktest** [comment]
You have to understand that shift-click is just utilizing the generic "list ring" feature, it doesn't know what a hotbar is. In fact, the hotbar isn't really a thing either, it's just the first few entries of the "main" invlist.
It is possible to force the shift-click to target the pack by having two separate views of the "main" inventory. However, this might cause extra side effects.
A special shift-right-click idea doesn't fit this model at all.

**Comment by johalun** [comment]
Is this something that a mod can override? For example, override a generic "put in inventory" function and search for a free slot in the non-hotbar part of the inventory first (slot 9-32 in the main inventory?) ?

**Comment by Desour** [comment]
>Is this something that a mod can override?

No. `listring`s are handled client-side and we do not have sscsm yet, so arbitrary stuff is not possible.
Btw. see also:
https://github.com/minetest/minetest/blob/f43d1cfa81aa496174af6cdfa648dab9dd17288c/src/gui/guiFormSpecMenu.cpp#L4308

**Comment by johalun** [comment]
Alternatively, is it possible for a mod to listen to key presses and move a stack in case of a key press like "G" or whatever is configured? If so, I can write a mod to quick-move stacks from the crafting interface and creative menu to the inventory. Also a key shortcut to throw stacks, and put stacks in trash would be nice. Like Q for throw, shift-Q for trash.

**Comment by rubenwardy** [comment]
> Is this something that a mod can override?

Yes, you can use an invisible inventory list and inventory callbacks to do complex routing

**Comment by Desour** [comment]
>listen to key presses and move a stack in case of a key press

#8679 might make such things possible (or not, idk if captured input events are also sent).

Anyway, such things (as suggested in the two comments above) would not work as smoothly as listrings currently do: the user would have to wait after pressing the key to get results, which is not acceptable imho

**Comment by johalun** [comment]
> wait after pressing the key to get results

You mean server round-trip? Yeah that makes sense.. But if listrings are all handled client side it shouldn't add noticeable latency with lua hooks to customize behavior. Maybe it would also make it easier to add behavior such as intelligently decide where to move things like burnables to the lower slot and smeltables to the upper slot in case of the furnace.

**Comment by Desour** [comment]
Yes, I agree, csm features would be great.

**Comment by TuringZauber** [comment]
Having this would be really great. What is CSM?
