### ISSUE TITLE
Minetest only use one CPU

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10457]
##### Minetest version

```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04 LTS
CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 processer)

##### Summary
My minetest just use 1 CPU core, that was not enough for my server.

Sometimes it uses 101%(A little bit more then 1 CPU core), but it was still not enough.

**Comment by SmallJoker** [comment]
Intel: Enable hyper-threading -> Results in more vulnerabilities (see Spectre, Meltdown) but might make use slightly more of your CPU
AMD: I've seen reports where Minetest can use all cores - though I don't know the details there.

Also check whether a higher `num_emerge_threads` setting value improves anything. Perhaps more threads can be spread better (?).

Minetest does not spawn child-processes to make use of multiple processors (unlike Firefox, Chrome). Implementing such a thing is non-trivial and not really worth the efforts (as of now).
It's up to your CPU architecture how much processing power a single process can use.

PS: This was requested a few times already, but sadly I cannot find any duplicate issue.

**Comment by rubenwardy** [comment]
Throwing more threads or cores at a problem does not necessarily make it faster. You need to design a solution such that it can be made parallel. Minetest's server does not aim to be parallel because it's harder to do and is not needed, a single threaded server should be efficient enough to handle 100 players. There are lower hanging fruits to optimise

**Comment by Emojigit** [comment]
OK. If multi CPU cores can't make my server faster, that multi CPU cores are useless and dangerous. I am using advtrains and I made a Dos attack to my server with careless LuaATC codes, and a single CPU core rescued my server.
