### ISSUE TITLE
Formspec ItemImage rendered without color for palette index 0

### ISSUE THREAD

**Issue by Konfuz** [minetest/minetest#10462]
Related to #10459 
##### Minetest version
```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```
##### Summary
Items with a color palette do get rendered without color by the Formspec element ItemImage (and probably ItemImageButton) if the index is `0` 

##### Steps to reproduce
- build a palette without white (at least not at the 0 index) 
- make a node with a color neutral texture using said palette  
- use the formspec element itemImage with an item string generated by `minetest.itemstring_with_palette(node.name, i)`
- see that the item image gets generated without color exactly when the index `i` is 0

##### Workaround

Put white as the first element of your palette - if you dont need white that will reduce your availiable colors by one.

**Comment by v-rob** [comment]
Since this is already mentioned in #10459 and is very similar, I think it would be better if they stayed together.  Multiple issues aren't necessary if they're this similar.
