### ISSUE TITLE
Add CJK Support

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10466]
## Problem

When I use a mod to allow me to send Unicode to the chatroom, I can't send CJK to the chatroom(both in-game or discordmt)

## Solutions

I don't know, but please add CJK support

**Comment by paramat** [comment]
"In internationalization, CJK characters is a collective term for the Chinese, Japanese, and Korean languages"

**Comment by rubenwardy** [comment]
duplicate of #9198

**Comment by sfan5** [comment]
This is not necessarily a duplicate.

> When I use a mod to allow me

Which mods is that?

> I can't send CJK to the chatroom

Be more precise. Do the characters not show up? Is there any other error?

**Comment by Emojigit** [comment]
> This is not necessarily a duplicate.
> 
> > When I use a mod to allow me
> 
> Which mod is that?
> 
> > I can't send CJK to the chatroom
> 
> Be more precise. Do the characters not show up? Is there any other error?

my mod https://github.com/Emojigit/smod_colored_chat

the char turn to some strange char in game, and turn to other CJK when send to discord.

**Comment by rubenwardy** [comment]
Mod does raw string manip, that will be where the issue is

**Comment by sfan5** [comment]
No that's not it, but this is a duplicate of #7643 anyway.
