### ISSUE TITLE
This app can't open

### ISSUE THREAD

**Issue by donno2048** [minetest/minetest#10474]
##### Minetest version
```
5.3.0
```

##### OS / Hardware
Operating system: Window 10 home
CPU: Intel Core i5 (1035G1)
##### Summary
When I start the game this prompt appears:
<img width="509" alt="Screenshot 2020-10-08 173530" src="https://user-images.githubusercontent.com/61805754/95473708-0a227080-098d-11eb-895b-883ecf0d8b98.png">
Not completely sure what cousing it, but the app starts anyway.

**Comment by rubenwardy** [comment]
Minetest is not in the windows store and does not use game bar. Where did you get minetest from, and how are you starting it?

What does "copy.to clipboard" give you in the clipboard?

**Comment by donno2048** [comment]
I downloaded Minetest from [the download site](https://www.minetest.net/downloads/)

I'm using the portable 64-bit version

To start it, I  just double click the _minetest.exe_ in the bin folder

When I press the "copy to clipboard" it just pastes `Check the Windows Store for more info about Xbox Game Bar.`

> Minetest is not in the windows store and does not use game bar.

I know this is strange

**Comment by rubenwardy** [comment]
Is this still a problem?

Is there anything in the game bar settings that could help?

What's your debug.txt? Perhaps this weirdness is game bar telling you Minetest crashed
