### ISSUE TITLE
Hi!i dont know how to open this file

### ISSUE THREAD

**Issue by SDRStuff** [minetest/minetest#10481]
I am using a raspberry pi and I cannot figure out how to run this!  #Thanks!

**Comment by Emojigit** [comment]
I don't know what does "run this" means, but if you mean you don't know how to install and run, The guide is here: 
1. download `git clone https://github.com/minetest/minetest` for the latest version, or https://github.com/minetest/minetest/releases/latest to find the latest stable version.
2. Install: https://github.com/minetest/minetest#compiling
