### ISSUE TITLE
Lua API: Add minetest.raw_disconnect

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10490]
## Problem

I need to use `minetest.kick_player` to disconnect a player now, but it will add a `kicked` before the kick message.

## Solutions

Add `minetest.raw_discoonect(name,[reason])`, use the same format like `minetest.kick_player`

**Comment by rubenwardy** [comment]
When kick_player is used, the player sees this:  "Access denied: Kicked. Reason: REASON". Only REASON can be specified by a mod.

This issue wants it to be possible to set the entire string, not just the reason there

**Comment by sorcerykid** [comment]
This is a feature I've long wanted and needed. Perhaps it could be named either `minetest.disconnect_player()` or `minetest.remove_player()` for consistency.

**Comment by IceDragon200** [comment]
I had some freetime at work, so I did a quick implementation, not sure if it satisfies the request fully however

**Comment by numberZero** [comment]
> When kick_player is used, the player sees this: "Access denied: Kicked. Reason: REASON". Only REASON can be specified by a mod.

Actually, “Access denied. Reason: Kicked REASON”
I think prepending “kicked” should be enforced for the chat command but not for the Lua API function.
