### ISSUE TITLE
stratum_thickness is ignored when noise param is not used

### ISSUE THREAD

**Issue by Zeus-TheDev** [minetest/minetest#10496]
##### Minetest version
5.3.0

##### OS / Hardware
Operating system: Windows 10
CPU: Intel i7

##### Summary
According to the documentation  A parameter `stratum_thickness` can be provided instead of the noise parameter
`np_stratum_thickness`, to create a constant thickness.

However, stratum_thickness is not used and the generated stratum is not correct.

Analysis:

In l_mapgen.cpp the stratum_tickness is read but **no flag is set** if the noise param is not present

		case ORE_STRATUM: {
			OreStratum *orestratum = (OreStratum *)ore;

			lua_getfield(L, index, "np_stratum_thickness");
			if (read_noiseparams(L, -1, &orestratum->np_stratum_thickness))
				ore->flags |= OREFLAG_USE_NOISE2;
			lua_pop(L, 1);

			orestratum->stratum_thickness = getintfield_default(L, index,
				"stratum_thickness", 8);

			break;

So then in mg_ore.cpp the simple horizontal stratum is selected

		if (flags & OREFLAG_USE_NOISE) {
			float nhalfthick = ((flags & OREFLAG_USE_NOISE2) ?
				noise_stratum_thickness->result[index] : (float)stratum_thickness) /
				2.0f;
			float nmid = noise->result[index];
			y0 = MYMAX(nmin.Y, std::ceil(nmid - nhalfthick));
			y1 = MYMIN(nmax.Y, nmid + nhalfthick);
		} else { // Simple horizontal stratum
			y0 = nmin.Y;
			y1 = nmax.Y;
		}

##### Steps to reproduce
Use the following ore generation on the void game. Apply noclip and fly to look at the result

	minetest.register_ore({
		ore_type        = "stratum",
		ore             = stone,
		wherein         = {"air"},
		clust_scarcity  = 1,
		y_max           = 46,
		y_min           = 10,
		noise_params    = {
			offset = 0,
			scale = 16,
			spread = {x = 128, y = 128, z = 128},
			seed = 90122,
			octaves = 3,
			persistence = .5,
			lacunarity = 2
		},
		stratum_thickness = 2,
	})

##### Simple solutions

Option 1) Define a new flag and set it when only stratum_thickness is defined, then use it in mg_ore
Option 2) Change the documentation

**Comment by paramat** [comment]
I will investigate this, i created this ore type.

**Comment by Zeus-TheDev** [comment]
Works as expected. Sorry

Note to self: do not try to debug cpp code after 10 hours of your normal daily job (that does not involve looking at cpp code since at least 10 years) and without a build chain that does what it should.
