### ISSUE TITLE
Disallowed characters on world name

### ISSUE THREAD

**Issue by Vilzku** [minetest/minetest#10500]
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Windows 10 Pro 1903
CPU: Intel(R) Core(TM) i7-6700K

##### Summary

When creating a world with a name containing disallowed characters such as 'ä' or '£' the world cannot be loaded. The creation of the world is successful, but loading the world grants a database error as following:

```AsyncErr: ServerThread::run Lua: Runtime error from mod '*builtin*' in callback on_prejoinplayer(): Failed to open SQLite3 database file C:\Users\ville\AppData\Local\Temp\Rar$EXa0.877\minetest-5.3.0-win64\bin\..\worlds\ääääää\auth.sqlite: unable to open database file
stack traceback:
	[C]: in function 'read'
	...a0.877\minetest-5.3.0-win64\bin\..\builtin\game\auth.lua:133: in function <...a0.877\minetest-5.3.0-win64\bin\..\builtin\game\auth.lua:129>
	...77\minetest-5.3.0-win64\bin\..\builtin\game\register.lua:429: in function <...77\minetest-5.3.0-win64\bin\..\builtin\game\register.lua:413>
```

##### Steps to reproduce

For example:
1) Creating a world named "testissä tänään"
2) World creation is successful
3) When loading the world, it grants the error. In the worlds -folder, the world can be found named as "testissÃ¤ tÃ¤nÃ¤Ã¤n"

##### Suggested solution

In the following file a function can be modified to check for disallowed characters:
> minetest/builtin/mainmenu/dlg_create_world.lua

On line 357 function create_world_buttonhandler() can be found. A condition can be added a check for disallowed characters inside an if clause on line 383. 

```            local message
            if string.match(worldname, '[^%w%P%s!]') then 
                message = fgettext("A world named \"$1\" contains illegal characters", worldname)
            elseif not menudata.worldlist:uid_exists_raw(worldname) then
                core.settings:set("mg_name",fields["dd_mapgen"])
                message = core.create_world(worldname,gameindex)
            else
                message = fgettext("A world named \"$1\" already exists", worldname)
            end
```

**Comment by sfan5** [comment]
As far as I know this is a limitation (or rather bug) with Windows and Lua, so the menu should only limit the world naming on Windows.

It'd be even better to fix the bug since it's the same that causes Minetest to be unable to function if you extract it at an Unicode path.
