### ISSUE TITLE
Background escape sequences don't set the background for tooltips (item descriptions)

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#10505]
5.4.0 dev f43d1cfa8

According to the documentation, minetest.get_background_esape_sequence should be able to change the background color of an ItemStack's description. However, this doesn't seem to work; I can't get any description to change the background from the default green.

**Comment by velartrill** [comment]
i've noticed the background escape sequence works on android, but not on desktop. no idea what's up with that.

**Comment by verymilan** [comment]
this indeed vanished for me too, which is sad, because my server uses it for event items for example :(
