### ISSUE TITLE
Shader uniform API

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10503]
## Problem

#9907 allows for advanced server-sent shaders. Those are fairly limited though, as long as there is no support for server-sent uniform variables.

## Solutions

Allow providing uniform variables to the shaders.

### Shader uniform types (as supported by [Irrlicht](http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_i_material_renderer_services.html))

* Texture ("sampler"). Represented in Lua as a string identifying the texture, for example `"blank.png"`. Texture modifiers are supported.
* Array type (matrix, vector, array). Table, for example `{1, 2, 3}`. Type of table is determined by the type of the first element.
* Numbers. Only float support, integer (`s32`) support would be a hassle. Lua number type.
* Booleans. `true` or `false`.

#### Per-player

`player:set_shader_uniform(shader, name, value)`, accordingly `player:get_shader_uniform(shader, name)`

* `shader` is either `"vertex"` or `"fragment"`
* `name` is the name of the constant (for example, `"glowmap"`)
* `value` is of one of the types described above

#### Per-entity

Equivalent to per-player.

#### Per-node

Low-priority and nontrivial. Possibly: Meta field.

## Alternatives

If we want full rendering control for modders, none. Else just implementing every single feature and bloating the shaders, still keeping rendering limited.

## Additional context

Closely related: #8854 - if this was to be implemented, shaders could use custom materials (textures)

**Comment by hecktest** [comment]
Just one concern: a function named set_shader_uniform on ObjectRef might, in the future, be confusing if per-object materials and shaders are a thing.
If this is only for setting uniforms on the "global" shaders for a whole client, it should be called differently.
Since there are several of those shaders, you also need a parameter stating which shader you want to touch: object, node, minimap, selection...

**Comment by lhofhansl** [comment]
Generally I'm a fan. We just removed a bunch of the hardcoded shader stuff, so now is a good time to nail down what shader could and should do.

**Comment by numberZero** [comment]
What do you mean by “per-player”, those visible to a particular player, or those applied to the player entity?

> shader is either "vertex" or "fragment"

There is no such distinction in OpenGL (including ES), only in DirectX.

> Per-node
> Low-priority and nontrivial. Possibly: Meta field.

`param2`, passed as a vertex attribute and not as uniform.

**Comment by sfan5** [comment]
I think this is better closed in favor of #15145

**Comment by appgurueu** [comment]
This is essentially one aspect of that issue, yes. Custom shaders require custom uniforms to be really useful.
