### ISSUE TITLE
can_dig can change position of node dug

### ISSUE THREAD

**Issue by Schoggo** [minetest/minetest#10514]
##### Minetest version

```
f43d1cfa81aa496174af6cdfa648dab9dd17288c
```

##### OS / Hardware

Operating system: Linux (Arch, BTW ;))
CPU: AMD FX 8370

GPU model:
OpenGL version:

##### Summary

A node's can_dig callback can modify the position of the node that gets dug. This could lead to a mod (accidentally) making a node that cannot be mined and instead mines another node.
File: `builtin/game/item.lua`
Function: `core.node_dig`
For all other callbacks, the position and node are copied and a copy is passed (see, eg, line 633).

##### Steps to reproduce

Give a node the following `can_dig`:
```
can_dig = function(pos, player)
		pos.y = pos.y + 1
		return true
end
```

Place another node above the modified node and mine the modified node. See how the top node instead of the modified one disappears.

##### Solutions
I can see 2 solutions here:
- copy the position for can_dig as well
- save all the (potentially unnecessary) copying and warn in the api doc that callbacks should not modify the position

##### Other stuff
I'm just working on #10504 and I was wondering if I should copy the pointed_thing every time as well.

**Comment by SmallJoker** [comment]
Just `table.copy` it, or `vector.new` in this case. No big deal.
