### ISSUE TITLE
Some bold ideas

### ISSUE THREAD

**Issue by Pevernow** [minetest/minetest#10510]
Nowadays, the engine of minetest is Irrlicht, which is very slow to update. Moreover, it does not support new rendering modes (such as Vulkan, Dx11) and does not supports input dependent on and ime

Some people suggest using sdl2 + OpenGL to rewrite the underlying engine, which I think is good. However, OpenGL limits the type of rendering backend.

Maybe ogre next would be better?

It is the next generation version of Ogre and improves performance over ogre1. Support Dx11, OpenGL, Vulkan and other languages. And it supports shaders across platforms very well

Maybe try to organize some people to write minetest 6 based on OGRE next.

I know this may not be accepted by most core developers,

But it may be able to push this idea forward

**Comment by SmallJoker** [comment]
Please post this request in the Irrlicht issue tracker. Changing the framework would be too much work at this point, thus it will stay like that.

Many other requests or Irrlicht issues: https://github.com/minetest/minetest/issues?q=label%3A%22Upstream+issue%22+irrlicht

**Comment by rubenwardy** [comment]
In theory, I support switching backend. In practice, I don't have time to be involved in doing this and I doubt anyone else will either

**Comment by Pevernow** [comment]
@SmallJoker  It is not an Upstream issue.

I don't want to fix the Irrlicht problem. I want to change the backend.

I think we can keep this issue open

So that more people can see and consider the idea.

**Comment by LoneWolfHT** [comment]
Maybe start by slowly replacing Irrlicht functions with MT ones that you can hook any engine up to.
