### ISSUE TITLE
increased light range / LIGHT_MAX

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest#10519]
With the introduction of set_eye_offset and collision box for players it is now possible to make subgames that have block sizes other than 1 meter cubed. In subgames that have blocks smaller than 1 meter cubed eg "1 foot cubed", light can't travel very far. It would be nice to have LIGHT_MAX > 14 or something to extend a light sources range.

**Comment by SmallJoker** [comment]
The maximal light level is 15 (sunlight). This is an engine limitation. You cannot get any higher than that.

Related, because they would require a total light system change:
Colored light: #2670
Spherical light: #8818

**Comment by paramat** [comment]
SmallJoker is correct.
Light spread is limited by mapblock size, which would be an extreme amount of rewriting work to increase above 16 nodes.
