### ISSUE TITLE
Correctly publish https://minetest.gitlab.io/minetest

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#10517]
## Problem

This page exist already since more than a year. 
It's super useful in comparison to the lua_api.txt as it has a search function and is well ordered.
Anyhow there are only two PRs linking to it, so it's not quiet famous and unused.

## Solutions

- Grant it an own domain like docs.minetest.net
- Push it to the Readme, website and everywhere lua modding is done. (kind of replace it with the referring to lua_api.txt)

PS: Enforce https should also be enabled.

**Comment by paramat** [comment]
+1

**Comment by sfan5** [comment]
> It's super useful in comparison to the lua_api.txt as it has a search function and is well ordered

Does your browser not have a search function?
My issue with the mkdocs rendering is that you cannot quickly search for all mentions of e.g. `use_texture_alpha`, you need to click the search bar and wait for results to arrive *or* click through to the right section manually

**Comment by Lejo1** [comment]
> Does your browser not have a search function?

Of course and I also used it for that.
I just think that such a ReadTheDocs website is much more user and especially beginner friendly.

**Comment by paramat** [comment]
I should clarify, i probably do not support removing references to the raw document, as that is also useful and more reliable.
I do support linking to the hosted version more.
So, perhaps best to refer to both.

**Comment by rubenwardy** [comment]
https://api.minetest.net/
