### ISSUE TITLE
Remove 'Clang Format off/on' lines from code, whitelist files instead

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#10518]
I can understand the reasoning behind adding these but they cause big problems:

The configuration of Clang Format (CF) needs improving, this is obvious and high priority.
However, each time configuration is altered every 'CF off/on' line in code will need to be re-assessed, removed, added, moved. This creates a large amount of extra work.
The more of these lines we add the more work is generated, so we need to stop this officially now.
Adding these lines itself generates extra work for contributors and reviewers.

Eventually, a file will probably end up with very many CF off/on lines, with perhaps a majority of lines whitelisted. This is not worth the effort and visual mess, it would be better, and far less work, that the whole file is whitelisted.

If entire files are whitelisted, altering configuration only requires re-assessing the whitelisting of entire files, which is a do-able task.

The other problem of these lines is the visual mess created.

We have to consider the eventual outcome of the current method, not just consider the relative harmlessness of doing it in one reviewed PR.
If we continue like this, eventually files will be full of many ugly CF off/on lines, and there will be thousands of these lines throughout MT code.

The CF situation is a seemingly unresolvable insane mess, discussed for years and with no solution (it seems CF unfortunately cannot be configured to ignore code alignment for readability, which is everywhere in code, so most files will always be in the whitelist).
It is insane to add so much mess to MT code just because of the inherently and understandably limited capability of one particular automated format checker.
We might change the format checker, or stop using it, we will certainly reconfigure it, doing any of these will make all CF off/on lines potentially invalid.

**Comment by JosiahWI** [comment]
Could I convince us to come to a decision on this? It shouldn't be so difficult; if we aren't intending to fix this, we could just remove it, and it would close 2 issues and make the code base cleaner. If we do intend to fix it, just talking about fixing it won't go anywhere.

**Comment by sfan5** [comment]
Well the `//clang-format on|off` comments probably have to go regardless of what they new solution looks like. Is that what you're referring to?

**Comment by JosiahWI** [comment]
I can do that. I was referring to making a decision about whether to fix clang-format, or get rid of it, and I had looked at multiple relevant issues and accidentally posted on the wrong one.
