### ISSUE TITLE
minetest.decode_base64 returning nil for valid base64

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10513]
##### Minetest version

```
5.3.0
```

##### Summary
Encoding a base64 buffer of a glTF failed due to Minetest's decoder not working properly.

##### Steps to reproduce

Try decoding [base64.txt](https://github.com/minetest/minetest/files/5396803/base64.txt) (source: character.b3d)

**Comment by SmallJoker** [comment]
f34abaedd2
