### ISSUE TITLE
A way to get if a node is in active block radius

### ISSUE THREAD

**Issue by Hume2** [minetest/minetest#10523]
## Problem

There is a way to get if a node is loaded by get_node_or_nil. When it returns nil, it's not loaded. I don't like this solution because it returns the node even if I don't actually need it. But well.

There is a way to get if a node is in the active block radius. You calculate the distance to all players and if there is a player who is close enough, the node is in the active block radius. But... why shall I do all of that when Minetest somehow has to calculate the same thing anyway? Can't there be just a way to obtain this result from Minetest directly without calculating it again? Moreover, there's even no standard mod function to calculate this so each mod calculates it again for itself. It's a waste of resources.

## Solutions

Add a function is_node_active(pos) which returns true if it's in the active block radius.

## Alternatives

Like we have LBMs, there can be modifiers which would be ran each time a block gets active or inactive. I'd like to see that too eventually because these can be also useful.

## Additional context

I tweaked pipeworks to obtain this information so I don't need to calculate it in each mod extra.

**Comment by rubenwardy** [comment]
Get node or nil will return nil if a node isn't loaded. I'm not sure if this is always equal to active, I'm not familiar with this area of the code

**Comment by Hume2** [comment]
I want to know whether or not the block is actually active, not only loaded.

**Comment by fluxionary** [comment]
this has been solved by #11247, has it not?
