### ISSUE TITLE
Devtest: Player has minimap marker by default

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10526]
##### Minetest version

```
4f2303849e0f929524695a9e3719ec486b47ddd1
```

##### Summary
If you start `devtest`, the player will have the red minimap marker dot on the minimap.

This does not happen for other games.

##### How to Repro

1. Start `devtest`
2. Activate minimap

**Comment by sfan5** [comment]
The local player you mean?

**Comment by Wuzzy2** [comment]
Yes.
