### ISSUE TITLE
Player sprite is visible in 1st person

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10525]
##### Minetest version
```
4f2303849e0f929524695a9e3719ec486b47ddd1
```

##### Summary
If the players use the default 2D sprite, you can see your own player sprite in the 1st person camera.

##### Steps to reproduce
1. Start `devtest`
2. Walk
3. Tilt your camera up and down and walking

You will see your own player sprite, and this looks quite bad.

**Comment by sfan5** [comment]
probably regression from #10360

**Comment by paramat** [comment]
I could not reproduce, then realised the camera intersects the sprite so the sprite is only visible with view bobbing enabled due to camera movement.

**Comment by lhofhansl** [comment]
I've seen that too. Kinda annoying :)

**Comment by Jordach** [comment]
Weirdly enough between the merge commit and the current commit, the camera's origin doesn't seem to be exactly in the center of the node itself. This wasn't spotted in the merge, because it couldn't be seen at all.
