### ISSUE TITLE
Do not accept new CSM features until SSCSM is implemented

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#10530]
It is uncertain whether SSCSM will ever happen, or if it does it could be years away, it is already 3 years overdue.
In the recent roadmap brainstorm no core dev directly stated implementing SSCSM as a priority for the medium to long term, there were only indirect references to it.
IRC:
> 18:36 rubenwardy    I find it interesting that no one put SSCSM or CSM in their roadmap lists 👀
18:36 sfan5         too much work
18:36 Krock         CSM were a thing in 2017/18 and generally neglected now
18:37 Krock         not surprising IMO

SSCSM requires co-ordinated work by the most experienced core devs, but there is no indication of this happening in the short to medum term.

The core devs might collectively decide that CPCSM is now an official self-justified MT feature (even though that was never intended by anyone) ('self-justified' meaning justified whether or not SSCSM happens), but we are in a weird situation where we claim it is not, but continue to add new CSM features even though SSCSM is uncertain or at least years away.

If CPCSM is not intended to be an official self-justified feature, no new CSM features should be added until SSCSM is implemented, because they are only justified by SSCSM. New CSM features might be wasted effort, and they might make SSCSM more difficult to implement.
One of the original CSM devs, red-001, themselves halted CSM feature work because they considered more would just make SSCSM more difficult to implement.

If a CSM feature is only valid for SSCSM is certainly should be delayed until SSCSM is implemented.

**Comment by sfan5** [comment]
> delay new CSM features until SSCSM is implemented

As a quick counterpoint:
An experimental development variant of SSCSM or another solution that involves loading mods the server wants could surely be implemented. The point here is that implementing CSM features *now* allows server owners, modders and users to test and improve the features and the end result will be better that way.
However before server authoritative APIs can be added to CSM, some design decisions need to be made. I'll elaborate on that in a later comment.

**Comment by paramat** [comment]
> The point here is that implementing CSM features now allows server owners, modders and users to test and improve the features and the end result will be better that way.

Yes, this was the questionable and unroadmapped intent of the original CSM developers. However, we surely have more than enough CSM features now to do this. This being useful is not an argument for endlessly adding more features.
There are also people (rubenwardy, red-001) stating that adding more CSM features makes SSCSM more difficult to implement.

**Comment by sfan5** [comment]
> There are also people (rubenwardy, red-001) stating that adding more CSM features makes SSCSM more difficult to implement.

You can add me to that list, but it depends on *what* will be be done for SSCSM and what changes need to potentially be undone.

<hr />

The promised elaboration:

To make CSM truly useful it needs APIs that do things without waiting for the server, unlike the sorta read-only access it has presently. One example for this would be node placement/dig prediction, see #8057 for more.
And assuming that CPCSM is kept (I personally think it should be), it needs to be **denied** access to those APIs for obvious reasons.

This is where one design decision still needs to be made and implemented. The options are:
* Keep CPCSM and SSCSM in the same Lua environment, using a solution similar to `minetest.request_http_api()` (this is <b>almost certainly insecure</b>, don't do this)
* Have one Lua environment for CPCSM and one for SSCSM, this provides strict security boundaries and separation of APIs

(There is a closely related problem of how restrictions such as the the node or itemdef lookup can be made to apply only to CPCSM, to which the latter is a very obvious answer.)

Once that is done, APIs that accommodate the server mod's interests can be added and subsequently tested by server owners and users who are willing to opt into SSCSM in an experimental stage.
Securing builtin (#6925) should follow soon, but is not strictly necessary to move SSCSM to a testing phase (since it's all opt-in, server owners who wish to test SSCSM can opt in with the knowledge that it (currently) also allows cheats).

<hr />

Now that I've written this I have to say I mostly agree with "If a CSM feature is only valid for SSCSM is certainly should be delayed until SSCSM is implemented" in the post. SSCSM-only features should be put in the right place when possible, **but** I think SSCSM should be made viable (just in an experimental stage, see above) soon so features don't have to be delayed.

**Comment by jamesalexanderstevenson** [comment]
Four years ago we voted for recreational marijuana in my state.  It was not
until just the other day that the first stores opened and began sales.

Kinda a strange comparison, but some things take time.  I'm sure it will
all work out in the end.

My best wishes,
jas

**Comment by paramat** [comment]
jas, that is good to know. But "some things take time. I'm sure it will all work out in the end" is just a vague platitude, inapplicable to a detailed debate.

> And assuming that CPCSM is kept (I personally think it should be)

Does that mean you support CPCSM being an official independent feature? It is not quite clear.

I want to emphasise how much effort will have been wasted if SSCSM never happens and we decide CPCSM is not an official feature. This is potentially very damaging to the project and i think this damage outweighs the benefits you describe.
That is why we need to decide what is in the title of this issue.

All core devs apart from myself are already acting as if CPCSM is an official independent feature, because everything is being sleepily accepted without question in an uncertain CSM situation. So i am suggesting we be honest about this.
It seems to me that we have accepted CPCSM as an official feature and have accepted that until SSCSM happens, or if SSCSM does not happen, people will be manually distributing CSM mods to their clients, which is what people are doing now as a workaround.

I am not too bothered by the outcome of the decision, it seems likely CPCSM will be accepted as an official independent feature due to being in use for 3 years and the inevitable unpopularity of not making it an official feature (and this is why the way CSM was implemened was a mistake, it made this end situation of CPCSM-only probable even though it was never intended and is considered crazy by celeron55).
But we should be honest and clear about this, and it is critical for the consideration of new CSM features.

**Comment by Wuzzy2** [comment]
As a player, I would not miss CPCSMs at all if they would be removed.

**Comment by v-rob** [comment]
CSM is basically used for colored chat (there's about a billion of those floating around), and if that's really a wanted feature, then we can add it to the engine; no need for CSM for that.  A lot of other things are like in-game notes and calculators (things any self-respecting OS has) or abuses like a SSM that requires a CSM to be installed to work, which is SSCSM's job.

Honestly, I don't see many use-cases for CSM.  They're mostly abuses, cheats, or really basic tools, and I don't think adding more features will really change that.  Assuming #10524 was used for a CSM (not its main purpose), it wouldn't be very much use unless it was linked to a SSM with mod channels, and that's what SSCSM would be for.  Basically, CSMs are for looking at the world or making something look fancier or jury-rigging SSCSM.

So, I would go for the side of the argument that says that CPCSM is not a justified feature.  The use-cases do not justify the large amount of code that goes into CPCSM.  That code would be useful for SSCSM later, but there's no point in maintaining the virtually worthless CPCSM alongside the much more useful SSM and future SSCSM.

(Hmm, how about Client-Provided SSM?  That way, I can force my colored chat on _everyone_!  :P)

**Comment by LoneWolfHT** [comment]
CPCSM was really useful on HOMETOWN and the other servers I played on. It let me do things like create moderation tools (https://github.com/LoneWolfHT/modform) that I didn't need to beg the admin to add. (In the HOMETOWN case they were working on their own moderation tool that was never finished)
With a little source code modification to allow some insecure functions it also allowed for a client-side chat translation system via a google/yandex API. That allowed for pretty good multi-lingual moderation without putting any load on the server.

#
>  A lot of other things are like in-game notes and calculators (things any self-respecting OS has)

Via CSM you can have per-server notes (Possible with a notepad but not as clean), it's also nicer having it ingame. I say this as someone who has had to use their OS notepad

With CSM you can/could also modify your out-chat. So you can send `{35 * 10}` in chat and it will send `350` to the server. 
Or you could have  `~` insert your current coordinates like in Minecraft (I think there was an issue for that somewhere, did it ever get added? I coded it in under an hour and was able to use it on all servers before CSM restrictions)

**Comment by sfan5** [comment]
> Does that mean you support CPCSM being an official independent feature? It is not quite clear.

What exactly will stay is subject to discussion, but I generally think CPCSM is an useful feature (e.g. chat-modifying mods which do not and shouldn't require server-side support).

**Comment by Desour** [comment]
Something that will be impossible (or at least very inconvenient for users) is remote SSCSMs that need access to an insecure environment, eg. to read out chat via speech dispatcher or to open a locally installed code editor. (It might be possible to trust the hash of a certain version of a SSCSM, but this would invalidate on every new version -> hence inconvenient.)
Also, I like the idea of more customisation via CPCSMs, ie. not having to ask each admin to install a mod that translates the chat (which will be denied, ignored or accepted but with inconsistencies to other servers).
Anyway, SSCSM is imo far more important than CPCSM.

**Comment by sfan5** [comment]
CSM will never get access to an insecure environment, zero exceptions.

**Comment by paramat** [comment]
v-rob, i agree with your post.

My opinion is that CPCSM should not be considered an official independently-existing MT feature, as has always been the intention of all the plans and roadmaps, and of celeron55. It was even the intention of the original CSM devs, CPCSM was only ever meant to be a step towards SSCSM.

What concerns me is that we are not clear to contributors about this and they are still contributing CSM features expecting them to be merged.
Many core devs are also accepting new CSM features when they probably should not be.
I am currently disapproving all CSM features, which makes me feel bad because we are misleading them.
Our actions are inconsistent with the official stance on CSM, which is that it is unstable, unsupported, unfinished and only a stage towards SSCSM.

I think we should freeze all CSM feature development until SSCSM is near to being implemented, and make this official and inform contributors of this,
Because SSCSM is so uncertain we are possibly wasting a lot of contributor and developer time and effort, as well as bloating the code and making SSCSM even more difficult to implement.
I do not think CPCSM justifies adding additional new CSM features, users already enough to play with and we are probably not going to remove that, as we will probbaly always be hoping for SSCSM to be implemented eventually.

**Comment by paramat** [comment]
Changed the issue title as i do have a preference for what happens.

**Comment by Wuzzy2** [comment]
I agree with paramat, I never liked the idea of CPCSMs. Some of the supposedly more useful CSMs could be turned into engine features, but tbh, I don't consider any of the current released CSMs to be that important. Don't let CPCSMs hold you back.
I think it's a design flaw to have mods add missing client features instead of just adding them into officiail.

I'd like to add that CPCSMs also make things more complicated for the player as well, because it is another type of mod they have to learn and manage.

**Comment by LoneWolfHT** [comment]
> I'd like to add that CPCSMs also make things more complicated for the player as well, because it is another type of mod they have to learn and manage.

They don't have to learn it if they don't want to. If they're willing to go through the trouble to learn and manage it though that means there's something appealing about it

**Comment by v-rob** [comment]
If we keep CPCSM, it should be no more than a subset of SSCSM.  Any more than that, and it's just extra stuff to maintain.  And, we should have no worries about making breaking changes to it until SSCSM has a stable release.  If it did stay as a subset, I wouldn't have much problem with keeping it even though I don't see a whole lot of use for it.

If we did keep CPCSM, then I would envision the client Lua to have three levels:
* Internal Client Lua: This is stuff that is internal to the engine and necessary for it to work properly.  If my Lua-side GUI idea goes through, the GUI code must always be loaded regardless of whether CSM or SSCSM is enabled, and therefore this level would be needed.
* CPCSM: Can be enabled or disabled just like now and is a superset of the Internal Client Lua and runs in the same environment.
* SSCSM: Can be enabled or disabled for security reasons and is a superset of CSM but runs in a different environment.

So, I think that code-wise, it is possible to manage CPCSM alongside SSCSM with little extra work assuming it was just a pure subset of SSCSM's API and nothing more, meaning it would need zero maintenance as it would be maintained by maintaining SSCSM.  Should we keep CPCSM on principle is still up for debate.

But more to the topic, I think that CPCSM features should not be added until SSCSM is stable.  That way, we can implement SSCSM without having to worry about CPCSM at all, and then if we decide that we do want CPCSM, we just move some SSCSM functions and userdata to the CPCSM level instead so they are shared with both.  But, internal client Lua features (assuming my Lua-side GUI idea is accepted and we do have such a concept) should be exempt as they are necessary features for the engine.

**Comment by hecktest** [comment]
The only way CPCSMs would make any sense is if they were chain-loaded by SSCSMs, that is, if a game could optionally expose a client-side API. (custom huds, macros, etc.) Anything else is just a cheat engine.

**Comment by nerzhul** [comment]
i am totally okay with @sfan5 comments, both technical and political
