### ISSUE TITLE
ß Support / All german letters

### ISSUE THREAD

**Issue by qawsedrftgzh** [minetest/minetest#10533]
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Linux (Manjaro 20.1 KDE
CPU:Intel

GPU model:Intel
OpenGL version:4.6

##### Summary

When typing the German letter „ß“ only „character conversation appears“ , but ä,ö and ü are included since 5.3.0
##### Steps to reproduce

Include full german support.

**Comment by sfan5** [comment]
Works for me on Linux XFCE

**Comment by qawsedrftgzh** [comment]
Do you use 5.3.0 or Git?

**Comment by sfan5** [comment]
Git, but I'm pretty sure this hasn't changed recently.

**Comment by SmallJoker** [comment]
Does #10458 fix your issues?

In 5.3.0 stable there was no notable change, whereas #10440 appeared in 5.4.0-dev.

**Comment by Wuzzy2** [comment]
Works for me under XFCE as well.

**Comment by qawsedrftgzh** [comment]
Sorry It works In minetest game but not ij mineclone, why is this game depending
