### ISSUE TITLE
Minetest shows unreviewed versions from mmdb

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1053]
Minetest shows an install button ingame for unreviewed mods, this, combined with mods being allowed to use the io module is a security problem and should be solved before the next release.

**Comment by paramat** [comment]
mmdb seems to have been abandoned so can this be closed?

**Comment by rubenwardy** [comment]
Can be closed and combined into the one "get mmdb back up" mega issue. #3289

**Comment by paramat** [comment]
Agreed, that issue is by the same author too.
