### ISSUE TITLE
deprecated functions should appear by default in the log

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10544]
[API](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6248) says they're deprecated, but [in the code](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_object.cpp#L2320) they're only aliased

**Comment by rubenwardy** [comment]
Aliased and deprecated are the same thing - there should be a warning for this, I'll look into it

**Comment by Zughy** [comment]
this happens (at least in devtest) with every aliased function, such as getpos, setpos etc.

**Comment by sfan5** [comment]
Works for me on c7aa92aaed27ad8e10af7463b154b5b580c86da5, so some commit after that much have broken it. #10512 perhaps?

**Comment by Zughy** [comment]
Uhm, I detached at your commit and I still can't see anything in the log. Code:
```
minetest.register_on_joinplayer(function(player)
	minetest.after(3, function()
		player:add_player_velocity(vector.multiply(player:get_look_dir(), 5))
		minetest.chat_send_player(player:get_player_name(), dump(player:getpos()))
	end)
end)
```

I didn't change any default settings, I can see general "action" messages

**Comment by rubenwardy** [comment]
Have you enabled deprecation logging? There's.a setting to do so

I intrnd to make them log by default, but a bug needs to be fixed first

**Comment by Zughy** [comment]
> Have you enabled deprecation logging? There's.a setting to do so

I swear I thought it was something enabled by default. Then no, it's set on `legacy`, my bad. But yes, I agree, they should be enabled by default

**Comment by SmallJoker** [comment]
> they should be enabled by default

With the current deprecation implementation that's not possible due to tail call optimizations. See #8322

**Comment by Zughy** [comment]
Huh. LuaJIT 5.3 can't be implemented because.. ?

**Comment by sfan5** [comment]
LuaJIT 5.3 does not exist. Or do you see it anywhere?

**Comment by SmallJoker** [comment]
Closing. As soon #8322 is solved, this will be changed for sure (example attempt: #10174).
