### ISSUE TITLE
Fix Android build numbers and update script

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10540]
The script to release 5.3.0 failed, and didn't update the Android version code or version name. I needed to set it manually

**Comment by sfan5** [comment]
see also https://github.com/minetest/minetest/commit/057f0b82c23d5ad4efe044fe0f0d8753eb3a8bcf#r40491552

**Comment by ronoaldo** [comment]
The util/bump_version.sh script is going to ask interactively for the version, or it should use env vars in order to update it? I'll check the script to try figure out why it failed.

**Comment by ronoaldo** [comment]
If I got this correctly, the issue was not removing the "-dev" from "versionExtra" in build/android/build.gradle? The rest was ok right?

**Comment by sfan5** [comment]
Yes.
