### ISSUE TITLE
Wiki: Plaintext password emailed in confirmation

### ISSUE THREAD

**Issue by Jonta** [minetest/minetest#10557]
Maybe it's a problem, maybe it's not. See https://security.stackexchange.com/questions/61215/the-registration-confirmation-email-contains-my-password-do-they-keep-it-in-pla

If passwords _are_ stored in plaintext: please fix, of course

And if they _aren't_: please alleviate our worries in that same email. :)

**Comment by SmallJoker** [comment]
Thanks for notifying, but this is should be reported in the forums.
The Minetest repository here does not cover any external web services.
