### ISSUE TITLE
Wiki: How and where to report issues with it?

### ISSUE THREAD

**Issue by Jonta** [minetest/minetest#10556]
I'm reporting it here, as I'm not finding a better place

**Comment by SmallJoker** [comment]
https://forum.minetest.net/viewforum.php?f=6
Freenode IRC (Calinou or celeron55)
Not fitting well, but better than reporting to minetest/minetest: https://github.com/minetest/minetest.github.io/issues

**Comment by Jonta** [comment]
Other issue mentioned is, for posterity: https://github.com/minetest/minetest.github.io/issues/223
