### ISSUE TITLE
Mapgen settings in a game's minetest.conf get ignored

### ISSUE THREAD

**Issue by CasimirKaPazi** [minetest/minetest#10555]
Version is Minetest 5.4.0-dev-61a196378 (Linux)

As the title says, mapgen v6 settings get ignored.

To reproduce past the following in minetest.conf, create a world with mg v6 and seed "mapgen". At -300,0,-300 there should be a mountain range at least 100 nodes above zero.
```
mgv6_np_terrain_base		= 10,	60,		(800, 800, 800),	82341,	7,	0.65,	2.0
mgv6_np_terrain_higher		= 8,	75,		(750, 750, 750),	85039,	8,	0.65,	2.0
mgv6_freq_desert			= 0.25
mgv6_freq_beach				= 0.25
mgv6_np_steepness			= 0.70,	0.2,	(60, 60, 60),		-932,	5,	0.8,	2.0
mgv6_np_biome				= 0.1,	1,		(600, 600, 600),	9130,	3, 	0.50,	2.0
mgv6_np_trees				= 0.3,	2,		(125, 125, 125),	2,		4,	0.70,	2.0
```

**Comment by SmallJoker** [comment]
Would you please be so nice to bisect this issue? There was a back-and-forth of bugs and bugfixes related to mapgen flags, whereas the noise params might now be affected as well.

**Comment by paramat** [comment]
Do the custom parameters appear in map_meta.txt?

**Comment by paramat** [comment]
Also, do you mean that this problem only occurs in V6?

**Comment by CasimirKaPazi** [comment]
It is broken since d28f1b0. The problem only occurs when loading from the minetest.conf of a game. For the users mintest.conf it works.
I only tested mgv6. Params do not appear in map_meta.txt.

**Comment by paramat** [comment]
Although this might not make a difference, you should use the form shown in minetest.conf.example for noiseparams:
```
mgv6_np_terrain_base = {
    offset      = -4,
    scale       = 20,
    spread      = (250, 250, 250),
    seed        = 82341,
    octaves     = 5,
    persistence = 0.6,
    lacunarity  = 2.0,
    flags       = eased
}
```

**Comment by pyrollo** [comment]
In `map_settings_manager.cpp`:
```
m_map_settings->overrideDefaults(user_settings);
```
Here, only _settings_, not _defaults_ from `user_settings` will override `m_map_settings` defaults.
But values read from `minetest.conf` (from game), are stored as `user_settings` defaults (`subgames.cpp` l339):

```
	Settings game_defaults;
	getGameMinetestConfig(gamespec.path, game_defaults);
	game_defaults.removeSecureSettings();

	g_settings->overrideDefaults(&game_defaults);
```

(pointer to `g_settings` is passed to `MapSettingsManager` as `user_settings`)

I'm wondering what would be the best solution. Cleanest one would be to have something to manage these multiple levels of default and overrides. Simplest one would be to re-add `readParams(m_user_settings)` in `makeMapgenParams`.

**Comment by SmallJoker** [comment]
The cleanest would be to re-write the entire Settings class to introduce a proper hierarchy. That's still an open point on my TODO list but it would avoid such settings priority-related issues in the future.

**Comment by pyrollo** [comment]
I'm going to change `Settings::overrideDefault` behavior so it will override defaults with settings **and** defaults from other settings. It sounds normal that it could do like that.

It is used only twice, in map settings manager and in subgame settings where overriding settings have no defaults.

There is still a piece of code I don't clearly understand in `Settings::overrideDefault` [settings.cpp:996](https://github.com/minetest/minetest/blob/master/src/settings.cpp#L996-L1004):
```
		if (flagdesc) {
			// Flags cannot be copied directly.
			// 1) Get the current set flags
			u32 flags = getFlagStr(setting.first, flagdesc, nullptr);
			// 2) Set the flags as defaults
			other->setDefault(setting.first, flagdesc, flags);
			// 3) Get the newly set flags and override the default setting value
			setDefault(setting.first, flagdesc,
				other->getFlagStr(setting.first, flagdesc, nullptr));
```

It looks like `overrideDefault` modifies `other` defaults and IMO this is not expected.

**Comment by SmallJoker** [comment]
#10661 merged.
