### ISSUE TITLE
hud_change and hud_remove now crash the game when id is nil

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#10568]
##### Minetest version

```
Minetest 5.4.0-dev-33b2c5f5b (Linux)
```

##### OS / Hardware

Operating system: Debian 10 Buster

##### Summary
Since 33b2c5f5b1c565171296f26395d803b08f4575e9 (found with `git bisect`), it appears like there is a breaking change in `hud_change()` and `hud_remove()`.

Before this commit, the id parameter of the mentioned functions was actually optional, using -1 as a fallback.
The mentioned commit removed this fallback, so mods will now crash when nil is supplied as an ID.

| Before | After |
|-|-|
| **`hud_change`** | |
| https://github.com/minetest/minetest/blob/9d370b78da61997f46f228cb3e4b54b8ee9295ff/src/script/lua_api/l_object.cpp#L1552  | https://github.com/minetest/minetest/blob/33b2c5f5b1c565171296f26395d803b08f4575e9/src/script/lua_api/l_object.cpp#L1517 |
| | |
| | |
| **`hud_remove`** | |
| https://github.com/minetest/minetest/blob/9d370b78da61997f46f228cb3e4b54b8ee9295ff/src/script/lua_api/l_object.cpp#L1532-L1534 | https://github.com/minetest/minetest/blob/33b2c5f5b1c565171296f26395d803b08f4575e9/src/script/lua_api/l_object.cpp#L1499 |

As far as I can see, this is no breaking change as far as `lua_api.txt` is concerned because one could assume that a correct `id` is required in the provided functions; however, I think that in reality this could be seen as a breaking change since it appears that some rather well-known mods depend on the old behaviour.

##### Steps to reproduce

You can reproduce the crash by using the [stamina](https://github.com/minetest-mods/stamina) mod (tested with version https://github.com/minetest-mods/stamina/commit/e4e456a3c9a46a1965322766da11ad0959f70fd1; a bugfix might be submitted there soon) in Minetest Game.

**Comment by sfan5** [comment]
Does calling hud_change or hud_remove with `nil` do anything useful?

**Comment by Thomas--S** [comment]
I'd guess that it usually did nothing as I assume that the ID `-1` is normally not assigned to a HUD element. The only thing it did was to prevent a crash.

**Comment by Zughy** [comment]
@sfan5 should I make a PR where it only checks for positive numbers and if it's negative it crashes?

**Comment by sfan5** [comment]
I don't think there's anything needed to be changed here.

**Comment by Zughy** [comment]
I suggest to close it then

**Comment by SmallJoker** [comment]
This error properly highlights mod errors, thus I think it's justified to keep it.
