### ISSUE TITLE
games crashes with error in item_identity.lua : 'on_step'

### ISSUE THREAD

**Issue by gramsey** [minetest/minetest#10565]
##### Minetest version

```
Minetest 5.3.0-dev-debug-c1ce4be75 (Linux)
```

##### OS / Hardware

Operating system:
CPU:Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

GPU model:
OpenGL version:

##### Summary

Existing Game working fine on 5.2.0. I then built 5.3.0 (tagged). Initially played ok, then crashed with message below. I then re-created with a new map, and **without any additional mods on basic 'minetest_game'** - same thing happened. Played fine for about 10 minutes then crashed. Trying to re-enter map results in same crash. I pulled down the latest master and ran in debug - same results. 

Error message is 

> 2020-10-27 14:14:22: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback luaentity_Step(): ...am/game/minetest/bin/../builtin/game/item_entity.lua:203: Collision info missing, this is caused by an out-of-date/buggy mod or game
> 2020-10-27 14:14:22: ERROR[Main]: stack traceback:
> 2020-10-27 14:14:22: ERROR[Main]: 	[C]: in function 'assert'
> 2020-10-27 14:14:22: ERROR[Main]: 	...am/game/minetest/bin/../builtin/game/item_entity.lua:203: in function 'on_step'
> 2020-10-27 14:14:22: ERROR[Main]: 	.../../games/minetest_game/mods/default/item_entity.lua:43: in function <.../../games/minetest_game/mods/default/item_entity.lua:42>

(for more detailed log - see 'gdb_log.txt' attached)

##### Steps to reproduce
[cmake.txt](https://github.com/minetest/minetest/files/5446091/cmake.txt)
[gdb_log.txt](https://github.com/minetest/minetest/files/5446093/gdb_log.txt)

1. Compile with following options (attached) 
2. Run minetest
3. Create a new game for minetest_game (with no additional mods)
4. Play game normally (collecting stone wood etc, nothing out of the oridinary) for approx 10 minutes
5. Suddenly game crashes - not clear what action if any actually causes crash.
6. Any attempt to re-enter map allows you in, but will crash after approx 1 second of play. 

Please let me know if you want anything else from me. Thanks!

**Comment by LoneWolfHT** [comment]
> Collision info missing, this is caused by an out-of-date/buggy mod or game

You need to update minetest_game https://github.com/minetest/minetest_game/

**Comment by gramsey** [comment]
OH doh!, sorry i thought that was contained in *this* project, thanks!
