### ISSUE TITLE
Client may unload blocks it shouldn't

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#10567]
5.4.0 and earlier

This is a bug I've observed while attempting to improve map rendering, I'm posting it because it's a separate issue and someone might have a better idea what's going on.

The client will often forget mapblocks that are still within its sight range, then re-request them from the server, and repeat.
You can repro it by playing minimal on a perfectly flat world, freezing the time, and watching the mesh updates in the profiler. If you're not moving at all, no liquids or ABMs are present, and time does not flow, no mesh updates should ever happen, yet they regularly do. The MapBlocks loaded counter will also appear to rise, then get flushed, and repeat.

If you look in one direction for a long time, blocks outside the view frustum will randomly start disappearing, creating holes in the world and causing unnecessary resends and remeshes. I do not know if this aggressive unloading is the whole issue, because even when you don't touch the mouse, remeshes still happen. Curiously, blocks at the edge of the vision range are not unloaded.

**Comment by paramat** [comment]
@lhofhansl

**Comment by lhofhansl** [comment]
The client cache has a size (5000 blocks by default) and time (10 minutes) limit. Is it possible you're just seeing that?

**Comment by hecktest** [comment]
You mean, it's waiting until all cached blocks expire?

**Comment by hecktest** [comment]
Oh, sorry, I thought this was the other issue.

Okay, so setting the cache size to -1 stops the holes from appearing. The phantom resends and remeshes are also gone.
Some math reveals that a draw distance of 200 results in a visible cube of about 14000 blocks. 5000 is definitely not enough then, it should be bumped. Related: #10571

Alternatively, the cache size should be determined based on the draw distance and available memory. As it is, you get no warning that increasing the draw distance from 100 without also increasing the block cache will result in holes in a map.

A third option is making it so that blocks in the visible range don't count towards the cache, and the point of the cache is to store already visited areas. That way the setting would actually make some sense.

**Comment by lhofhansl** [comment]
A good rule of thumb number for the number of blocks needing to be cached on the client is (viewing_range/16) ^ 3 / 2 (assuming the server is setup to send up to viewing_range/16 blocks)

You do _not_ need 14000 blocks for a viewing_range of 200, you'll need about 1000.
When reach viewing_ranges of 400 or 500 (with the right server configs) do you need that many blocks cached

**Comment by lhofhansl** [comment]
Also note that before #10537 the server would routinely not add blocks already sent to the client already to its sent set, and then send them again (again not adding them to the sent list). This does not sounds like that problem, but could be related.

**Comment by hecktest** [comment]
But (r/16)³ would only roughly cover what's in front of you. If you want to reliably cache all the blocks within the range, you need (2r/16)³. Setting the cache to only cover the view frustum is asking for trouble, that's exactly why there are holes in the map when you turn around.
1k/200 is absolutely not enough, I had the cache at 2k when opening the issue. The default 5k supports a range of roughly 130.
It's trivial to test this so I did:
- 1k/200: Holes appear very quickly.
- 2k/200: Holes in the map.
- 4k/200: Holes take a little longer to appear, but still present.
- 8k/200: No more holes within sight, but there's still block activity in the profiler.
- 16k/200: Very little profiler activity related to blocks.
Estimating the block cache needed as the volume of the visible sphere gives us a bit over 9k blocks for a distance of 200. This should be enough to handle a player who looks around and doesn't move, and seems consistent with the test results. My original estimate of 14k was based on a cubic volume, though it should be noted that a moving player might need a tiny bit more than the minimum spherical volume to avoid glitches for sure, so I'd still recommend 10k to 16k to have a comfortable buffer.

#10537 may have fixed something because I remember getting unnecessary resends regardless of the draw distance.

**Comment by lhofhansl** [comment]
I just tried. The /2 part was wrong.

viewing_range of 300. Looked around in all direction, then checked the number of cached block (F6) and it's 6090.
3565 at viewing_range of 200.

In the end we should derive the cache size from the viewing_range anyway.

**Comment by hecktest** [comment]
I just tried it your way, reading the profiler, and I got 12k which is closer to my original estimate. Disable server side culling and try again.

And no, you should never ever count on blocks being culled by the server or, worse, out of the frustum. The client has to support the worst case, which is a full sphere around the camera.

**Comment by lhofhansl** [comment]
Well if you disable the culling you'll get a sphere - or 1/2 sphere roughly above ground. :)
But that's not realistic, IMHO, and will lead to giant estimated caches.

14800 at viewing_range of 400.
And at 500 it's about 23700 cached blocks.

I think we can estimate with something like (r/16)^2.2 * 15:

r | cache
-|-
100 | 845
200 | 3884
300 | 9477
400 | 17846
500 | 29158

**Comment by lhofhansl** [comment]
> And no, you should never ever count on blocks being culled by the server or, worse, out of the frustum. The client has to support the worst case, which is a full sphere around the camera.

I disagree. For a viewing_range of 500 you'd then need 127k blocks in the cache. This is clearly *not* needed for any actual game, where the actual need a less than 1/5 of it - and that is assuming you have some vantage point where you can see the entire world to the horizon. That's in fact why I added occlusion culling to the server back in the day (#5320).

**Comment by hecktest** [comment]
Not realistic? If you're on the surface, you will see on average about half of the whole sphere. Rise above the surface at all and you will see more. Some games have huge caverns, and at least one I've played generates a huge dungeon with a 400 node thick layer made almost entirely of glass, where you can't count on culling reducing anything.

Server side culling enabled, simple v7 map in a simple game, 200 range, cache unlimited. I'm standing on the top of a tree and rotating the camera in every direction. The blocks stopped loading at exactly 8135. I never moved from my log-in position. I don't know where are you getting your math from, but you're not getting it right.

There are exactly two options to handle this right:
- The client maintains a static cache that covers its vision sphere entirely and then some.
- Blocks within the vision sphere do not count towards any cache and the client is forbidden from unloading them.

**Comment by hecktest** [comment]
More weirdness: telling the client to unload things frequently also causes blocks outside of the frustum to get dropped, causing holes in the map and an artificially low loaded block count.

This means that the frustum (and maybe other things) is being used to determine whether a block is still relevant, when in reality all blocks within euclidean range should be considered as still in use. Any attempts at being clever about this are just asking for trouble.

**Comment by lhofhansl** [comment]
4/3*pi*(200/16)^3 = 8181 (I can calculate the volume of a sphere - thank you very much. But that's not the point here.)

That literally means that your client loaded almost _every single_ block in range, and server side occlusion culling just filtered 46 blocks. Really?

**Comment by hecktest** [comment]
Go back to my earlier test where I got 12k in the same circumstances, with server culling off. Now take your volume calculation, round the radius to a full mapblock and add one or two for good measure, because the draw distance is just the point where the fog starts being saturated. With a padding of two blocks you get 14k, with one you get 11k. 12k sounds plausible.

The tree was on a hill so I got to see a bit more than a perfectly flat horizon, and it's unlikely that server culling is airtight. About one third of the blocks was culled. This seems reasonable.

We are arguing about roughly 200 MB of memory, which we shouldn't be arguing about at all, because the engine ought to support the worst case without bugging out.

If you think that's too expensive, you know what's really expensive? Invalidating 40 MB of cache for dumb reasons and expecting the server to resend it all to us within one frame, when the player decides to turn his mouse. All because the client has amnesia and can't even remember its surroundings. Gigabytes of bandwidth are being wasted on this.

If you don't have 256 megs of ram to spare for 16k blocks of cache, you shouldn't be running 200 range. Then again I think that without fixing the frustum issue first, blocks will keep disappearing if you travel, even with enough cache.

**Comment by lhofhansl** [comment]
Hmm... Fair enough on the math... ceil(200/16) = 13. 4/3*pi*13^3 = 9202.
You may setup the server to allow extra padding of at most 1 extra block distance, so 14 in this case. Volume: 11493. That was meant for moving around a lot so that the horizon "loads" in more smoothly. Both number are without any culling.

Aaaanyway... It's a trivial change to change caching code to reset the usage timer of a block within the sphere around the player rather than just the view cone. It's also easy to remove the artificial size limit, and simply cache blocks until the expire (out of range) for a short time - perhaps 1m instead of 10m.

Caching large number of blocks and their meshes has other side-effects too. Just recently I fixed a problem where all these cached blocks held on to their VBO buffer (HW-buffers in Irrlicht speak) so these invisible blocks slowed down rendering the scene.

**Comment by paramat** [comment]
A setting for an upper limit of blocks cached is still required to limit memory use, it cannot be unlimited because block meshes use a huge amount of memory.
For me, with the default of 5000, MT uses 2GB of memory in total, and i only have 8GB RAM. For me i would consider 4 GB the maximum i can allow MT to use, which i guess would be a cache of approx 10000.

Perhaps due to the large memory use we need to be more cautious with the new defaults discussed in #10571 , maybe view range should be 160 not 190.

**Comment by lhofhansl** [comment]
Frankly I think we can just leave it the way it is. It's client-side configurable after all. Blocks time out after 10 minutes by default; if you sit somewhere and haven't looked around in 10 minutes, it's fine (IMHO anyway) to re-retrieve the blocks.

That said, the currently visible blocks absolutely **must** fit in the cache. Otherwise the client is going to hammer the server retrieve the same blocks over and over again for every frame. This is not just a client optimization. In the fact I'd go as far as suggesting that the server automatically ban you in that case. We can calculate that with 2/3 * pi * block_radius^3 * (1 - cos(fov)).

I also agree with @hecktest that visible blocks in the sphere around the player **should** fit into the cache as well (4/3 * pi * block_radius^3).

**Comment by hecktest** [comment]
Lucky for us, most of the blocks in the range sphere will not have a mesh - air blocks and solid blocks alike. The amount of mesh data will vary too. Therefore it's incorrect to assume a linear relationship between the vision range and the mesh data volume. An LOD system could reduce this further.

You can still collect mesh data if you're short on memory, the mesher is fairly fast - it's re-sending blocks that is absolutely forbidden. Another thing you can do is zlib things that aren't in use, and thaw the data when you need it - it's still probably faster than a remesh and definitely faster than a resend.

Of course, excessive remeshes should be avoided too as first, they lead to microstutter, and second, they would interfere with many strategies for map rendering optimization.

@lhofhansl
"Leave it as it is" is an absolutely nuts decision. This is a broken setting that should not exist in its current state. Frustum culling (or even occlusion culling) should never decide whether a block is kept alive, and blocks within the vision range should never be collected. So what if someone AFKs? The OS can swap that out. A healthy buffer beyond the vision range is also useful, a player doing things in most games will generally roam between a few blocks.

The fact that you can set the cache low enough to drain server resources means that it's a broken system, and the correct thing to do is to fix it, not autoban anyone who sets it too low. That would be the dumbest thing in computing since the VIA C3.

**Comment by lhofhansl** [comment]
@hecktest 

- It's fine (and healthy) to disagree.
- That does not make other opinions "nuts" nor "dumbest thing in computing since the VIA C3". I would prefer a cordial discussion.
- The comment about banning to point out the severity of the issue to @paramat
- As you can see from my recent PRs I have been thinking about these things and how to best optimize them.
- What I want to do is avoid unloading blocks that where very recently (in the last view seconds, or so) referenced/shown. That will avoid any thrashing between client and server.
- I'll start with the visible view cone, then we can discuss further whether we want to extend this to the sphere around the player.
- Sound good?

**Comment by hecktest** [comment]
The trashing happens when a player with *either* a small cache *or* a frequent drop time keeps spinning the camera. This is what made me notice and open this issue in the first place.

You have to understand that making any memory and network management dependent on the camera frustum is an objectively bad idea. You can never, ever make it work. The player can always move the mouse faster than the server can respond, and they will see holes in the world, which makes the game look like utter crap, and they will re-request blocks they should've held on to, wasting tons of bandwidth and CPU time on both ends.

You also have to understand that a cache must be large enough to fit the player's entire surroundings. Failing to meet this need will also result in nearby level data being collected when it shouldn't, causing the same visual and performance problems.

There's nothing to really argue about here, this isn't about opinions, this is just math. Our time could be better spent discussing how to trim the memory footprint after properly dealing with this.

I will restate the problems:
- Client uses frustum culling to determine the relevance of blocks, when euclidean distance should be used
- The default cache can not fit map data with a radius greater than 130 nodes
- The user is expected to configure the cache manually to match the radius, when it could just be a function of the radius
- The user may reserve an unreasonably small cache, causing the client to malfunction even harder and drain more server resources

Solutions:
- Use euclidean distance to keep blocks alive
- Remove the cache setting in favor of a good heuristic, _or_
- Change the purpose of the cache setting to either a minimum cache or a cache for blocks outside of the vision radius

**Comment by lhofhansl** [comment]
I would add some smart opportunistic pre-fetching of blocks to the list.

**Comment by hecktest** [comment]
That's fine to do if there's spare RAM for it. If a player is travelling in a predictable direction, buffering ahead could mitigate potential underruns and lag spikes.

**Comment by mk-pmb** [comment]
Any progress on this? I'd prefer to set the cache size as a fraction additional to the minimum required.
