### ISSUE TITLE
DISCUSS: Increase default viewing_range and server send distances

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10571]
Now with #10537 merged, the server and handle farther distances much better and handles server load better (load hooks are not repeated). So now we can discuss increasing various MT setting related to distance.

The current defaults are:
- viewing_range (client): 100
- max_block_send_distance (server): 10
- max_block_generate_distance (server): 8

And (somewhat related):
- active_object_send_range_blocks (server): 4
- active_block_range (server): 3

Even on moderate or old H/W these are quite low by now.

**Lemme throw a proposal out:**
- viewing_range: 200
- max_block_send_distance: 14
- max_block_generate_distance: 14

14 matches the new 200 viewing_range; the can load one extra block distance for smoothing revealing the world and the horizon.
I never thought that having send and generate distance set to different values.

- active_object_send_range_blocks (server) : 8
- active_block_range (server) : 5

Thus objects (entities) are handled at least up 1/2 the block distance.

--

For comparison on my machine (which is just a Laptop, no over-the-top gaming PC) I have the following:
- viewing_range = 400
- max_block_send_distance = 26
- max_block_generate_distance = 26
- active_object_send_range_blocks = 32 (larger than block distance to handle zoom)
- active_block_range = 8

And everything still works perfectly fine.

**Comment by paramat** [comment]
But, viewing range affects client rendering performance due to the amount of visible world, your recent improvements do not alter that, this constraint still applies.
I have a good desktop computer but my practical maximum with good FPS, shaders off, opaque leaves, is 190 nodes.
100 is rather small though. As 'max_block_send_distance' is 10 = 160 nodes, perhaps view range default can now be 160?

Similarly, some other settings you discuss here are not necessarily now okay to increase. I am sure you are aware of this =)

For example, 'active block range' has a huge performance impact due to ABMs, which are very intensive.
I disapprove of increasing the default, 3 is already large and has caused a large load increase over the previous 2. 5 or 8 will cause an extreme ABM load increase.
> I never thought that having send and generate distance set to different values.

There is good reason for that, i set those values the way they are. It is due to the default mapchunk size of 5 mapblocks, this is why the 'generate' distance is 2 less, that is half a mapchunk. For these settings to be equivalent, the 'generate' distance should always be 2 less than the 'send' distance.

The problem with increasing 'max_block_generate_distance' is that it will greatly increase the load of Lua mapgen code (which most servers use) due to generating a much wider volume around a player as they travel.

**Comment by lhofhansl** [comment]
Thanks @paramat . All good points. Hence "discussion" :)  I wanted to stir thing up by the stuff I threw out there.

Interesting on send vs generate distance, I haven't realized that. Do we really need both then? Or can generate distance just always be send distance - 2?

The PR listed does reduce Lua load - or disentangles it better from loading the blocks. Hence I included the object and active_object distances as well since we should have a bit more budget on the server, even though they "somewhat" related only.

I like viewing_distance at 160. I'd suggest than increasing both send and generate distances by 1 to 11 and 9, resp. (to allow the server to send another block beyond the distance, so it's loaded at the client when the player moves - see code in clientiface.cpp).

active_block_range, and especially active_object_send_range_blocks bugs me a lot. Entities just disappear when you have enough distance, and then pop into existence again. Very annoying. Note that active_object_send_range_blocks only covers the visible fov area (unlike active_block_range which covers the sphere around you).

So perhaps we leave active_block range, and increase active_block_range to 5, 6, or 7 (since it is scaled with the fov anyway, so if you zoom you'll see same number entities, albeit at higher distances)

**Comment by lhofhansl** [comment]
Some tests on my Linux laptop, resolution 1920x1080, 24 bit color depth, 60hz display:

With Intel-Iris Graphics only:
FPS | viewing_range
--- | -------------
9 | 500
17 | 400
37 | 300
46 | 200
52 | 180
60 | 160

And with the NVidia card switched on:
FPS | viewing_range
--- | -------------
18 | 500
33 | 400
57 | 300
60 | 280

Nice Laptop, but no high-end gaming PC.

**Comment by appgurueu** [comment]
I vote 250

**Comment by hecktest** [comment]
200 is fine, remember that some mods have more intense and diverse node graphics.
Your GPU doesn't matter much, Minetest is CPU bound at the moment due to many drawcalls.

**Comment by paramat** [comment]
My desktop is an Intel i5, but integrated graphics, no card.

I must admit that i find around 190-200 the minimum satisfying view range, so something between 160 and 200 is ok with me.
I certainly think the view range should be increased to at least the current 'block send distance', so 160 minimum.
> Interesting on send vs generate distance, I haven't realized that. Do we really need both then? Or can generate distance just always be send distance - 2?

I think we need them both, having these independent is useful. Also, how one is set according to the other depends on chunksize which may not be 5.
So i suggest setting 'block send distance' to just clear 'view range', then set 'block generate distance' 2 less than 'send distance'?

Perhaps i am overcautious with 'active block range', i might be judging it on MTG which is ABM-heavy. Perhaps that could go up to 4? No objection to that, but no higher. The ABM load is proportional to the cube of the radius, i think we need to be cautious with this one.
I do not mind an increase in 'active object send range', i cannot judge that one well.

**Comment by lhofhansl** [comment]
,active block range is an interesting one. As you say the work is cubed with distance, setting it from 3 to 4 causes 2.37x as much ABM work, and to 5 it would cause 4.6x as much work; so, yeah, should be cautious.

active_object_send_range_blocks works as follows:
ABMs and entities/objects are always handled within the **active_block_range** (i.e. in the sphere around the player).
**active_object_send_range_blocks** extends entity/object (but not ABMs) handling to that distance in the player view-cone. So it's fine - I think - to make that larger, ideally matching the max_block_send_distance so the entities/objects do not disappear as long a player can see them. (I have it larger even than the send distance so that I can see entities/objects when I zoom, but we do not need to do that)

(Just like with real zoom (i.e. where zoom actually loads farther blocks) I could derive **active_object_send_range_blocks** from **active_block_range** and get rid of the former.)

How about this:
- viewing_range: 190
- max_block_send_distance: 12 (needed for 190, I'd like 13 even so that the client can preload one extra block)
- max_block_generate_distance: 10 (-2)
- active_object_send_range_blocks (server) : 10 (or even 12, so that entities never disappear from view)
- active_block_range (server) : 4

That would certainly be a good improvement of the defaults.

**Comment by paramat** [comment]
> active_object_send_range_blocks extends entity/object (but not ABMs) handling to that distance in the player view-cone. So it's fine - I think - to make that larger

Yes we have more freedom to increase this, although a large increase might cause problems. I am a little concerned about 4 -> 10.
Apart from that, your latest suggestion seems good to me, although i would like to see some input from other core devs.

**Comment by lhofhansl** [comment]
Entity density is usually low - though there are exception (for example see the issue I filed about TNT explosions leaving so many objects around that collision detection becomes expensive).

Taking the volume of the cone: 2/3*pi*r^3*(1-cos(fov)).
The volume of the active_object_range sphere is 4/3 * pi * r^3 = 268 (r = 4)
If we wanted roughly the same size of object view cone we could set the object send range to **6**, so that 2/3*pi* 6^3 * (1-cos(72)) ~= 312, which is close enough.

Another line of reasoning: Currently the viewing_range is 100, object send range is 4 so right now the send range covers 64% of the viewing range. If we wanted to keep that we'd 64% of 190 rounded to blocks = **8**.

Still, unlike active blocks the entities are very much visible to the player and entities disappearing and re-appearing as you move around looks like a bug (I'm seeing that in many MT videos, and it always looks like there's something wrong with MT).

A setting of 6 is only 96 nodes, or roughly 1/2 of the new viewing_range is better but still makes it _very_ visible. I'd vote at least for 8 here. 8*16 = 128, which is starting to look reasonable. (and I should file a PR to fov-adjust that setting, just like it's done for zoom - the math is already there :) )

Let's let some other folks weigh in. Since this is configurable anyway, it's not that important. It's just that there so many settings that need to be adjusted together that many client and even servers just get it wrong.

**Comment by paramat** [comment]
> Can we have generate_distances = send_distance - floor(chunksize/2)? I really would like to start removing settings.

Nuuuu, absolutely not =) Having these 2 independent settings is extremely useful, essential actually for certain uses.
Generate and send distances are very different things, not remotely redundant. The difference of half a mapchunk (which itself is debateable and a case of personal needs) is only a default for standard usage.

**Comment by lhofhansl** [comment]
Ok... I'll file a PR. I'll also increase the default client block cache to 7500.

**Comment by lhofhansl** [comment]
Should we discuss Android defaults here, or better to open a new issue?

These are overridden on Android:
```
	settings->setDefault("viewing_range", "50");
	settings->setDefault("max_block_generate_distance", "5");
	settings->setDefault("client_mapblock_limit", "1000");
```

IMHO, we can just double all of them. Modern Android devices are pretty powerful. :)

**Comment by lhofhansl** [comment]
I'll file a new issue for Android defaults.

**Comment by paramat** [comment]
I made a mistake in this issue. I now prefer that 'max block send distance' and 'max block generate distance' are left unchanged, as i consider them to already be a well chosen moderate balance.
Also i prefer 'viewing range' is increased to 160 to match the send distance. 160 was earlier accepted by lhofhansl.
No objections to the other changes.
