### ISSUE TITLE
Minetest chooses the wrong video chip to render the game on, chooses Intel iGPU by default. 

### ISSUE THREAD

**Issue by jconnolly837** [minetest/minetest#10576]
##### Minetest version

Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"

```

```

##### OS / Hardware

Operating system: Fedora Workstation 33 Wayland, kernel 5.8.16-300.fc33.x86_64
CPU: Intel Core i5 4590

GPU model: Radeon RX 560 4gb used for all video on the system, Intel iGPU enabled but not setup as a video output device
OpenGL version: OpenGL 4.6 with the Radeon, OpenGL 3.1 when using the iGPU, found using --verbose

##### Summary
When launching Minetest without giving it any environment variables(such as launching it with the .desktop launcher), it will use the Intel integrated video chip to render the game, bringing the frame rate lower than 10, making the game unplayable. Same result when using the DRI_PRIME=1 env variable. 
Lauching Minetest with the DRI_PRIME=0 env variable, the game will use the Radeon to render graphics and have no trouble keeping 60 fps. 
This is on a Dell Optiplex 9020 desktop, but I would expect the same from any PC that allows the iGPU to be used by the OS while using a dedicated GPU as the primary video device. Applications launched with DRI_PRIME=1(iGPU) will report that the video device is just "llvmpipe"
I believe the issue is Minetest expects the highest number DRI to be the video device it should use, because dual graphics laptops are fairly common and they are setup like that. But my PC shows the dedicated GPU as DRI 0, and iGPU as DRI 1. 
Minetest is installed through the flatpak flathub repo, and there were no mods being used during the testing. 

A very easy work around is to just add "env DRI_PRIME=0" to the .desktop file to avoid having to launch through the terminal, but I believe Minetest should be smarter than it is now and save less technical users from headache. 

##### Steps to reproduce
*Use a PC that shows the dedicated video card as the primary video device and shows the iGPU as a secondary video device
*Login to a Gnome Wayland session on a recent version of Fedora(I tested 32 and 33 with same result)
*Launch Minetest without environment variables that specify graphics device
*Notice that the animated background of Minetest lags, and playing in a world will have very low frame rate

**Comment by lhofhansl** [comment]
It depends a lot on how you setup your Primus setup. If you just installed the NVidia drivers you can set these three shell variables and offload to the NVidia card:

```
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only
```

For MT you actually only need the first one.

**Comment by sfan5** [comment]
I don't think those variables are relevant since the report says they're using a Radeon GPU.

Anyway, I don't think the engine *chooses* a GPU to render one, it asks for a rendering context and uses what it gets.
I think this is up the desktop environment / app launcher to enforce and our desktop file already includes `PrefersNonDefaultGPU=true`.

**Comment by lhofhansl** [comment]
@sfan5 Arrghh. Yes, I missed that somehow, even though it's mentioned in the 2nd paragraph. Sorry for the noise.

**Comment by uramer** [comment]
Same issue for me on Windows. Even if I force the high performance GPU in Windows graphics settings, the menu uses it, but after launching the actual game it switches back to the integrated GPU. Literally unplayable.

**Comment by programmerjake** [comment]
> Same issue for me on Windows. Even if I force the high performance GPU in Windows graphics settings, the menu uses it, but after launching the actual game it switches back to the integrated GPU. Literally unplayable.

See also #11981

**Comment by rubenwardy** [comment]
@sfan5  is this fixed by 22f0c66abbd02c8d7a66a81cf853f7c7fb84fe17 ?

**Comment by Zughy** [comment]
Is this still an issue?

**Comment by uramer** [comment]
Tried the current 5.5.1, Windows 10, the game defaulted to the dedicated GPU, didn't even have to manually set it. So I guess this is solved.

**Comment by rubenwardy** [comment]
good to hear this is resolved for you on Windows

On Linux, this seems like an upstream issue and the OP hasn't replied to this issue. So closing for now
