### ISSUE TITLE
Add hacktoberfest topic to repo

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest#10578]
## Problem

You can't submit MT PRs to hacktoberfest

## Solutions

Add the topic 'hacktoberfest' on repo-level

## Alternatives
Don't

## Additional context
Nothing

**Comment by rubenwardy** [comment]
We already decided not to do this, as it results in low quality submissions

**Comment by SmallJoker** [comment]
In addition, the last Hacktoberfst tag was removed just a few weeks ago. Also the deadline would be tomorrow - I don't think it makes sense to add this tag for a few free T-Shirts.
