### ISSUE TITLE
Can't connect to singleplayer server

### ISSUE THREAD

**Issue by niwla23** [minetest/minetest#10575]
##### Minetest version
5.1.1 and ~5.4.1~ 5.4.0-dev (latest commit, approx. 2dff3dd)

##### OS / Hardware
Operating system: Ubuntu Server with KDE (a buggy kubuntu)
CPU: Intel i5

##### Summary
The server says it binds to the specified port on startup but I cant connect to it. This happens when clicking start game, host game and even with the --server flag and external client.

##### Steps to reproduce
Install Minetest on the described device

**Comment by rubenwardy** [comment]
http://irc.minetest.net/minetest/2020-10-29#i_5747547

**Comment by lhofhansl** [comment]
Works fine for me...
