### ISSUE TITLE
Extreme change in server load time.

### ISSUE THREAD

**Issue by daytonnvpaul** [minetest/minetest#10581]
After moving my game to a new VPS, my server load time has gone from 1 minute, to almost 7 minutes.

Only major change was upgraded 5.3.0-stable to 5.4.0-dev.

It seems that the long delay happens _after_ all mods have loaded.

During game play, there's also a tremendous delay when using the digtron mod, as well as the technic digging tools.

Migrating backend to leveldb helped load time a little, but only by 30 seconds.

OS Ubuntu 20.04

**Comment by lhofhansl** [comment]
Can you describe the delay more? Are the blocks not loaded on the client? Is it the plain time it takes the server to start without any client attached? Or anything else you have observed?

**Comment by daytonnvpaul** [comment]
This is happening totally server side.  I do have to admit that I have a lot of mods, and my registered node count is approx 29,000.  However, it loaded in just about 1 minute with 5.3.0.

The longest wait, is after the server connects to the announce server.

I was wondering if 5.4.0-dev is having issues with an increased stack_max of some items. I do have a few that stack to 250.

**Comment by sfan5** [comment]
Please start your server with `--verbose` and see if you notice anything (or better post the log here), the server prints load times per-mod.

**Comment by daytonnvpaul** [comment]
Rather than post the entire 'nohup' file here, I've created a symlink to my webserver for the entire file.  Here's the spot where the load time is shown.
[verbose_log.txt](https://github.com/minetest/minetest/files/5471574/verbose_log.txt)

**Comment by daytonnvpaul** [comment]
Don't think the past worked correctly.

2020-11-01 10:49:48: ACTION[Server]: [advtrains][load_all]Loaded advtrains save files 
2020-11-01 10:49:48: ACTION[Server]: [advtrains]Train 572299 : Can't initialize: Waiting for the (yet unloaded) node at (-3454,-161,1097)  to be loaded. 
2020-11-01 10:49:48: ACTION[Server]: [advtrains]Train 011639 : Can't initialize: Waiting for the (yet unloaded) node at (-1946,-1699,3185)  to be loaded. 
2020-11-01 10:49:48: ACTION[Server]: [advtrains]Train 882916 : Can't initialize: Waiting for the (yet unloaded) node at (-1936,-1699,3185)  to be loaded. 
2020-11-01 10:49:48: ACTION[Server]: [advtrains]Train 267518 : Can't initialize: Waiting for the (yet unloaded) node at (-4604,-161,1264)  to be loaded. 
2020-11-01 10:49:48: ACTION[Server]: [advtrains]Train 854175 : Can't initialize: Waiting for the (yet unloaded) node at (-3474,-161,1078)  to be loaded. 
2020-11-01 10:49:48: ACTION[Server]: Announcing start to servers.minetest.net
2020-11-01 10:49:48: INFO[Server]: Server: Maximum lag peaked to 1.44 s
Unified Inventory. inventory size: 13861
2020-11-01 10:54:34: VERBOSE[Server]: Server::peerAdded(): peer->id=2
2020-11-01 10:54:34: VERBOSE[Server]: Server::deletingPeer(): peer->id=2, timeout=0
2020-11-01 10:54:34: VERBOSE[Server]: Server: Handling peer change: id=2, timeout=0
2020-11-01 10:54:34: VERBOSE[Server]: Server: Handling peer change: id=2, timeout=0
2020-11-01 10:54:34: INFO[Server]: Server: Maximum lag peaked to 284.661 s
2020-11-01 10:54:34: INFO[Server]: Saved 1 modified mod storages.
2020-11-01 10:54:34: ACTION[Server]: IRC: Connected!

**Comment by daytonnvpaul** [comment]
@sfan5, I can send you the https link in irc pm

**Comment by sfan5** [comment]
You didn't include the part with the mod load times, it looks like this:
<pre>
2020-11-01 21:36:48: VERBOSE[Main]: Loading and running script from [...]/games/minetest_game/mods/player_api/init.lua
2020-11-01 21:36:48: INFO[Main]: Mod "player_api" loaded after 0 ms
2020-11-01 21:36:48: VERBOSE[Main]: Loading and running script from [...]/games/minetest_game/mods/default/init.lua
2020-11-01 21:36:48: VERBOSE[Main]: NodeDefManager: registering content id "1": name="default:stone"
2020-11-01 21:36:48: VERBOSE[Main]: NodeDefManager: registering content id "2": name="default:cobble"
[...]
2020-11-01 21:36:48: INFO[Main]: Mod "default" loaded after 13 ms
2020-11-01 21:36:48: VERBOSE[Main]: Loading and running script from [...]/mods/test2/init.lua
[...]
2020-11-01 21:36:48: INFO[Main]: Mod "test2" loaded after 0 ms
</pre>

**Comment by daytonnvpaul** [comment]
The file is over 5M. wasn't sure i should upload the entire file here.  BTW, all mod load times are very low.

**Comment by daytonnvpaul** [comment]
Here's the entire file.  I wasn't aware that it created a link to to a text file.
[nohup.txt](https://github.com/minetest/minetest/files/5472087/nohup.txt)

**Comment by lhofhansl** [comment]
$> grep -i "loaded after" nohup.txt | awk '{ sum += $8 }END {print sum}'
32480

So mod load times account for **32.5s** only. The time is spent somewhere else.

Just out of curiosity... 20 slowest loading mods:
$> grep -i "loaded after" nohup.txt | awk '{ print $8, $5 }' | sort -nr | head -n 20
```
15310 "skinsdb"
3819 "coloredwood"
1658 "blox"
1263 "moreblocks"
1149 "signs_lib"
1140 "minerdream"
605 "labels"
526 "technic"
330 "moretrees"
268 "simplyslopes"
259 "bakedclay"
257 "infrastructure"
242 "castle_masonry"
237 "pipeworks"
229 "ethereal"
199 "mymillwork"
179 "bridger"
175 "letters"
164 "food_basic"
159 "gloopblocks"
```

**Comment by rubenwardy** [comment]
You should use the setting in moreblocks to stop it registering variant nodes in the creative inventory. This results in slow load times if creative or a craft guide is used

**Comment by daytonnvpaul** [comment]
Unfortunately, there's no indications of what's being done between these lines.

2020-11-01 10:49:48: INFO[Server]: Server: Maximum lag peaked to 1.44 s
Unified Inventory. inventory size: 13861

>>>> Notice the 5 minute time between these lines in the log <<<<<

2020-11-01 10:54:34: VERBOSE[Server]: Server::peerAdded(): peer->id=2

Another point I failed to mention.  After the server finally loads, and joins the IRC channel, I log to the gamebot, and run 'cmd status', and a max_lag of 250 or higher is always displayed. It will generally even out around 0.5 to 0.9, and only increase with exploration, or the use of technic tools or digtron use.

I've added "moreblocks.stairsplus_in_creative_inventory = false".  Thanks for pointing this out.

**Comment by sfan5** [comment]
> So mod load times account for 32.5s only.

That's still way too high, but it indeed doesn't explain the 5 minutes.

> Looking at the log above it really looks like announcing the server took 5 minutes.

Announcing happens in the background and there is no log message when it completes either, so that's not it.

<hr />

Here's my next suggestion:

Run the server in gdb: `gdb --args ./bin/minetestserver <rest of the args>`
Then when the mods have loaded and the server is stuck, interrupt with Control+C and enter `thread apply all bt`.
That should hopefully tell you (or us) what it was doing.

**Comment by daytonnvpaul** [comment]
Pardon my ignorance, but I have no idea how to prepare or use "--args" with gdb.

**Comment by daytonnvpaul** [comment]
I may have gotten a very basic quick start with gdb.

This was just after the line "Unified Inventory. inventory size:"

Note, this was run on a copy from backup in a non-production directory.

[gdb_01.txt](https://github.com/minetest/minetest/files/5479913/gdb_01.txt)

**Comment by daytonnvpaul** [comment]
And .....
[gdb_02.txt](https://github.com/minetest/minetest/files/5479960/gdb_02.txt)

**Comment by sfan5** [comment]
The gdb_02.txt looks good already, except you should have pressed Return a few times or "c" to see the whole output.

**Comment by daytonnvpaul** [comment]
I had let the server run too far before stopping.  I'm still learning how gdb works.  I'll do another run later today.

BTW, did gdb_01.txt indicate the possibility of a missing library?

**Comment by red-001** [comment]
No GDB just couldn't find the source file, you can safely ignore it, it's just CRT code.

**Comment by daytonnvpaul** [comment]
@sfan5 , I was finally able to get to the console. I stopped gdb about 30 seconds after the console display paused.

[gdb_03.txt](https://github.com/minetest/minetest/files/5485671/gdb_03.txt)

**Comment by daytonnvpaul** [comment]
Sorry to be such a pain. This is all new to me.

I think this is the one you want to see though.

[gdb_04.txt](https://github.com/minetest/minetest/files/5485756/gdb_04.txt)

**Comment by sfan5** [comment]
Yes the latter file is the right one.
The backtrace reveals that the server is busy running any of the functions registered with `minetest.register_globalstep`, which of them it is is unfortunately not visible.

At this point I'd safely say that it is a mod issue.
The server starts fine but then something is doing lots of work. If you'd like to debug which mod that is I suggest [the profiler](https://github.com/minetest/minetest/blob/627c22c36e32185d48d2faf8197e22cbaa4c50b2/minetest.conf.example#L1603-L1609).

**Comment by daytonnvpaul** [comment]
We've tried profiler, but nothing shows until after the server is fully loaded.  The part that has me concerned, is that there were 2 major changes at the same time, with my game.  A brand new VPS host, with a newly compiled 5.4.0-dev.

Please note:
On the old host, running the same OS, and with 5.3.0-stable_5, the game loaded in just about 1 minute.

When running /status from the irc gamebot, leaving only about 20 seconds from full loading, the 'max_lag' has been displayed as high as 260.xxx.  Profiler shows nothing that could be causing it.

Latest compile on Oct 12, was from github /minetest/minetest and using /minetest/minetest_game from the same date.

**Comment by daytonnvpaul** [comment]
sfan5, once again you were correct.  I updated my advancedtrains mod, and my load time is back to less than 2 minutes.  Time to close.

Thanks for pointing me to a better understanding of gdb.
