### ISSUE TITLE
Compatibility unexpectedly broken for set_physics_override

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest#10584]
##### Minetest version
Minetest 5.4.0-dev-89dd05fdf (Linux)

##### Summary
Using the bed in survival mode shuts down the server with the following message:

`
AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...t/bin/../games/minetest_game/mods/beds/functions.lua:115: bad argument #1 to 'set_physics_override' (table expected, got number)

stack traceback:

	[C]: in function 'set_physics_override'

	...t/bin/../games/minetest_game/mods/beds/functions.lua:115: in function 'lay_down'

	...t/bin/../games/minetest_game/mods/beds/functions.lua:185: in function 'on_rightclick'

	...inetest/bin/../games/minetest_game/mods/beds/api.lua:110: in function 'on_rightclick'

	...oo/development/minetest/bin/../builtin/game/item.lua:426: in function <...oo/development/minetest/bin/../builtin/game/item.lua:419>

	(tail call): ?
`

##### Steps to reproduce
Use a bed.

**Comment by SmallJoker** [comment]
Broken by https://github.com/minetest/minetest/commit/33b2c5f5b1c565171296f26395d803b08f4575e9#diff-5cdd53776d4918652568f88b8e6a83b016edfffb0029a53e30cd3095f9e14f96R1426

I'll propose a patch for both repositories because this API was never documented or removed long time ago.

**Comment by ozcodex** [comment]
It's also happening to me, if this can help here is the error message that I get:
```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'default' in callback item_OnPlace(): ...t/bin/../games/minetest_game/mods/beds/functions.lua:115: bad argument #1 to 'set_physics_override' (table expected, got number)
stack traceback:
	[C]: in function 'set_physics_override'
	...t/bin/../games/minetest_game/mods/beds/functions.lua:115: in function 'lay_down'
	...t/bin/../games/minetest_game/mods/beds/functions.lua:185: in function 'on_rightclick'
	...inetest/bin/../games/minetest_game/mods/beds/api.lua:110: in function 'on_rightclick'
	...e/ozcodex/Code/minetest/bin/../builtin/game/item.lua:426: in function <...e/ozcodex/Code/minetest/bin/../builtin/game/item.lua:419>
	(tail call): ?
```
