### ISSUE TITLE
PvP sword block

### ISSUE THREAD

**Issue by Code-Sploit** [minetest/minetest#10599]
## Problem

Could you guys add the possibility to block attacks (Not fully, you will still take damage) with swords in pvp?

**Comment by SmallJoker** [comment]
This feature can be implemented using the callback `on_punchplayer` in a mod. I don't see a necessity to include this as a core feature.

**Comment by Code-Sploit** [comment]
How?
Could you give me a small code snippet of what you mean?
Cause i am a bit of a noob in lua.

**Comment by 0-afflatus** [comment]
@Code-Sploit dodge, block and parry would be interesting ideas to explore once you have more experience coding with Lua and the minetest Lua api. Six years on, I'm still dealing with mapgen and other core issues. It could be trivial, but it could also involve a secondary wieldhand, who knows? It can probably be done without any engine changes, but yeah. If I Were You I Wouldn't Start From Here.

**Comment by Code-Sploit** [comment]
Okay, and thanks for the advice anyway!

**Comment by KaylebJay** [comment]
This should be closed, it is something already possible with the engine.

**Comment by SmallJoker** [comment]
@Code-Sploit Not directly code, but I'll try to explain it:

1) Assuming rightlick can block sword attacks
2) Register a `on_globalstep` callback to check the key input and cache that for other callbacks
3) Check against the cached value in a `register_on_player_hpchange` callback. (not `on_punchplayer`)
4) If the player holds a sword in his hand (`get_wielded_item()`), reduce the HP change
