### ISSUE TITLE
extract_zip fails for unknown reason

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest#10590]
##### Minetest version

"5.1.0-5.3.0"

##### OS / Hardware

Operating system: windows
CPU: 64 bit

not a graphical issue

##### Summary

mod https://content.minetest.net/packages/Hybrid%20Dog/sumpf/ fails when downloading in the engine
https://cdn.discordapp.com/attachments/670080638002528257/772568489637707836/unknown.png
![image](https://user-images.githubusercontent.com/24964441/97816700-efc67480-1c64-11eb-8e83-6dfa686e5d5f.png)

##### Steps to reproduce

boot up windows, start minetest, try to download the mod

**Comment by rubenwardy** [comment]
The zip file exists, but `core.extract_zip` returns false. The C++ code for extracting should be edited to give a better error message

**Comment by red-001** [comment]
Was able to replicate using wine. Zip downloaded fine and is valid. Looks like it's a filename issue
```    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/mapgen_sw_try.lua   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/old_functions.lua   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/old_mapgen.lua   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_16x16/   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_16x16/sumpfgrass.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf2.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_leaves_test.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_pilz_item.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_pilz_item2.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_pilz_oben.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_pilz_seite.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_pilz_unten.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_swampstone_tree_test.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpf_swampstone_tree_top_test.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/^J/textures_alternative/sumpfstein.png   OK
    testing: sumpf-9bb25afef283290f4e9ac19b41a17e4e99d6f29a/sumpf/birke.lua   OK
```
Windows isn't ok with just a space as a filename (or at least the API fs:: uses isn't). I suggest mod devs choose paths that work on all operating systems. @HybridDog could you rename the directory? Maybe call it `backup` or something.

**Comment by rubenwardy** [comment]
Where's the space in the path? Is it in Hybrid Dog's name?

**Comment by red-001** [comment]
well technically a line feed `^J` is apparently the way you display those on the linux. My bad it displays like a space for me when it's extracted.

**Comment by red-001** [comment]
![Screenshot from 2020-11-03 21-50-32](https://user-images.githubusercontent.com/12450071/98044372-acb00100-1e1e-11eb-9445-4a27fd2c8e9d.png)
I suppose I should have made the connection

**Comment by HybridDog** [comment]
I moved the old code to a separate branch and created a new release now.

**Comment by rubenwardy** [comment]
Closing in favour of https://github.com/minetest/contentdb/issues/379
