### ISSUE TITLE
New GLSL code is broken for me

### ISSUE THREAD

**Issue by Montandalar** [minetest/minetest#10605]
##### Minetest version
```
Minetest 5.4.0-dev (Windows) 707c8c1e95d8db2d84909e7957b4dc9138e05599
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system: Windows 7 Ultimate SP1
CPU: AMD Ryzen 3 2200G
GPU model: [Gigabyte Radeon™ RX 570 GAMING 4G](https://www.gigabyte.com/Graphics-Card/GV-RX570GAMING-4GD/sp#sp)
OpenGL version: 4.5
Driver dated: 2020-04-01 (I realised this is out of date)

##### Summary
GLSL fails to compile the shader program. All plantlike nodes render incorrectly as two solid planes of flat colour. The nodes of the world render at the same apparent brightness with no respect to day or night-time. A full log of minetest from boot to shutdown is provided.
[shaderfail_2020-11-06.log](https://github.com/minetest/minetest/files/5496061/shaderfail_2020-11-06.log)

[PR #10506](https://github.com/minetest/minetest/pull/10506) seems to have introduced the problem, as discovered by git bisect (commit 707c8c1e95d8db2d84909e7957b4dc9138e05599).

##### Steps to reproduce
The errors happen when a world is loaded. I loaded minetest game. I will update my graphics drivers soon and let you know if there is any change.

![screenshot_20201106_045557](https://user-images.githubusercontent.com/13659694/98278246-6dcfa600-1fec-11eb-9197-eac5d664fe5e.png)

**Comment by sfan5** [comment]
`MATERIAL_TYPE` and `DRAW_TYPE` are definitely converted to string incorrectly, that might be the problem.

**Comment by numberZero** [comment]
Pretty sure you compiled it with MSVC which seems to treat `char` and `unsigned char` as the same type (that’s forbidden by the standard but who cares...)

**Comment by sfan5** [comment]
I'm pretty sure I've seen `u8` turn into a char before with gcc/clang.

**Comment by numberZero** [comment]
btw why that `u8` is there at all? why it is not an `int` or some enum?

**Comment by sfan5** [comment]
No idea.

**Comment by Montandalar** [comment]
Yes, I did indeed compile with MSVC/visual studio, that's the easiest way on windows.
