### ISSUE TITLE
Discuss: Scale emerge limits with the number of clients.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10606]
Currently emergequeue_limit_total, emergequeue_limit_diskonly, emergequeue_limit_generate (and num_emerge_threads) are fixed.

It seems - at least to some extend - these should be scaled with the number of client.
Perhaps we have a min/max config a vary within that with the number of players.

Or we make the actual limit something conservative like: `<newlimit> = floor(<limit> * sqrt(#players))` or something.

**Comment by lhofhansl** [comment]
It's just this actually:

```diff --git a/src/emerge.cpp b/src/emerge.cpp
index 0ac26a682..b73cb3e58 100644
--- a/src/emerge.cpp
+++ b/src/emerge.cpp
@@ -415,18 +415,20 @@ bool EmergeManager::pushBlockEmergeData(
void *callback_param,
bool *entry_already_exists)
{
+       if (peer_requested == PEER_ID_INEXISTENT)
+               return false;
+
u16 &count_peer = m_peer_queue_count[peer_requested];
+       float adjust = std::sqrt(m_peer_queue_count.size());

if ((flags & BLOCK_EMERGE_FORCE_QUEUE) == 0) {
-               if (m_blocks_enqueued.size() >= m_qlimit_total)
+               if (m_blocks_enqueued.size() >= m_qlimit_total * adjust)
return false;

-               if (peer_requested != PEER_ID_INEXISTENT) {
-                       u16 qlimit_peer = (flags & BLOCK_EMERGE_ALLOW_GEN) ?
-                               m_qlimit_generate : m_qlimit_diskonly;
-                       if (count_peer >= qlimit_peer)
-                               return false;
-               }
+               u16 qlimit_peer = (flags & BLOCK_EMERGE_ALLOW_GEN) ?
+                       m_qlimit_generate * adjust : m_qlimit_diskonly * adjust;
+               if (count_peer >= qlimit_peer)
+                       return false;
}

std::pair<std::map<v3s16, BlockEmergeData>::iterator, bool> findres;
@@ -469,6 +471,8 @@ bool EmergeManager::popBlockEmergeData(v3s16 pos, BlockEmergeData *bedata)
u16 &count_peer = it2->second;
assert(count_peer != 0);
count_peer--;
+       if (count_peer == 0)
+               m_peer_queue_count.erase(it2);

m_blocks_enqueued.erase(it);
```

**Comment by lhofhansl** [comment]
The other part we should scale the emerge configs with are the server's send and generate distances.
There are *way* too many (IMHO, anyway) config option in MT, that we could instead replace with simple heuristics.

**Comment by lhofhansl** [comment]
After some more reading the code... The disk/generate are per peer, but they are ignored for any block requests on behalf of ABMs.

So the only one in need of scaling is emergequeue_limit_total. Perhaps we can get rid of that entirely and calculate instead, similar to we do that for blocks to send:

```
	// Maximal total count calculation
	// The per-client block sends is halved with the maximal online users
	u32 max_blocks_to_send = (m_env->getPlayerCount() + g_settings->getU32("max_users")) *
		g_settings->getU32("max_simultaneous_block_sends_per_client") / 4 + 1;
```

**Comment by paramat** [comment]
> num_emerge_threads

It is essential to be able to set an upper limit for this, as any value > 1 causes various minor bugs.

**Comment by lhofhansl** [comment]
@paramat I was not planning to touch that.

I think there should be a new and separate limit for ABM block request (which is per server). Those ABM requests can starve out the other requests, and no limit other than the total limit.

So we'd have:
- (per server) ABM block queue limit
- (per client) disk queue limit
- (per client) generate queue limit
- total limit = `ABM limit + ((#players + max_users) * disk/generate limit) / 4 + 1`.

What I'd really want is everything per client, but ABM enqueue request cannot be attributed to a specific client.

**Comment by hecktest** [comment]
This makes a lot more sense than having a fixed size queue.

**Comment by paramat** [comment]
> I was not planning to touch that.

Ok good =) I misunderstood your first comment.
