### ISSUE TITLE
Music / large sound files significantly slow down game startup

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10603]
If your game (or mod) includes large sound files such as a couple of music tracks, the startup of the game is being significantly slowed down.

How to reproduce:
* Create a dummy mod with an empty `init.lua` and a `sounds` directory with 10 random music tracks from your favourite album (In `.ogg` format)
* Start DevTest (or any minimal dummy game) with this mod enabled
* Compare startup time of DevTest without this mod enabled

Version: 5.3.0

**Comment by Wuzzy2** [comment]
Similar, but subtly different issue: #7139 (concerned about the *main menu*, not games).

**Comment by sfan5** [comment]
This seems like an XY problem (sorta).

Adding music makes the media to be transferred larger. Media transfers (even over localhost!) can sometimes stall due to protocol issues, so the root issue here is not related to sound at all.
The issue for that is #9107.

**Comment by kay27** [comment]
Is there a reason to wait for sounds to be loaded before the game starts? Comparing to roblox, I think there's no reason.

**Comment by hecktest** [comment]
Vorbis files are all being uncompressed to memory during the media load phase. That could be slowing things down if lots of big files are involved, ideally you'd rather stream anything longer than a few seconds from disk.

**Comment by paramat** [comment]
> Is there a reason to wait for sounds to be loaded before the game start?

Yes, obviously.

**Comment by hecktest** [comment]
There's a good reason to preload short sounds, but not music or ambient textures, because that's a ton of decoding work and wasted RAM.

Game engines usually give you both options. Unity for example lets you choose between preloaded ADPCM in memory for short clips, and Vorbis decoded on the fly for longer sounds. We could autodetect this based on the clip length, something like 10 seconds should disqualify a sound from being preloaded.

The first few seconds of streamed clips could still be cached to give the decoder some time to build a buffer.

**Comment by kay27** [comment]
> Game engines usually give you both options.

I agree, it might be very helpful for game developers if there were background load as an option, or some separate function like ```minetest.emerge_area()```, for Vorbis media files. E.g. before some moment there might be no jukeboxes in the world, you know what I mean.

**Comment by hecktest** [comment]
Preloading a "header" for each streamed file should be enough to mitigate any delay that a streamed file might cause. Every audio clip would have a mandatory PCM part, and an optional stream reference that is used if the PCM part reaches its maximum length.
