### ISSUE TITLE
Third person view gone?

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10617]
##### Minetest version

5.3.0

##### OS / Hardware
Windows 10

##### Summary
What in the world happened to 3rd person view. I used to be able to press F7 and it would appear. However this no longer works. I also checked in the setting of Minetest, to see if the setting or key binding was moved or changed and it appears NOWHERE. Was it removed from Minetest? If so, it is the dumbest decision to have ever been made! End or story!

##### Steps to reproduce
Obviosly just try to use 3rd person view.

**Comment by LoneWolfHT** [comment]
It was changed to 'C' for 'Camera' IIRC

**Comment by rubenwardy** [comment]
imo, changing this keybind was dumb and never should have happened

**Comment by 0-afflatus** [comment]
> this keybind was dumb
I found out about it due to finger stumbling.
X, C & V shouldn't be used for anything other than copy / paste functions.

**Comment by samarth-ramesh** [comment]
+1.
The key switch was annoying, ~~ngl, while i did change them back to old, it was very irritating~~. Years of muscle memory down the drain...
also, the issue of ctrl + (c|v|x) having special meaning in most desktops
