### ISSUE TITLE
on_use doesn't work when pressing the mouse too fast/soft, but its animation runs anyway

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10626]
##### Minetest version
```
master branch (on 5.3 too)
```

##### OS / Hardware
Operating system: Linux Mint
CPU: Intel Core i7-7700

##### Summary
Title. Proof:
https://imgur.com/a/GUunBKR

##### Steps to reproduce
That's the code
```
minetest.register_tool("test2:a", {
	description = "a",
	inventory_image = "test2_test.png",

	on_use = function(itemstack, user, pointed_thing)
		minetest.chat_send_all("you clicked me")
	end
})
```

**Comment by SmallJoker** [comment]
Lower the punch interval.
https://github.com/minetest/minetest/blob/be8d1d2d99ad835b5de7277b7b518c334113e795/doc/lua_api.txt#L1873-L1877

**Comment by Zughy** [comment]
Not a matter of punch interval, even with 0.1 doesn't change

**Comment by Zughy** [comment]
Can't really reproduce it anymore, closing
