### ISSUE TITLE
minetest i need help on making my server a remote server instead of a hosting server im in settings idk what to do 

### ISSUE THREAD

**Issue by joshthepheonix** [minetest/minetest#10628]
and if possible i would like for someone so in my server they join and they can help me since im brand new to coding ik how to fix a coding mistake but thats basically nothing

**Comment by joshthepheonix** [comment]
so anyone here

**Comment by SmallJoker** [comment]
General help: https://forum.minetest.net/viewtopic.php?f=10&t=17373
Windows tutorial: https://forum.minetest.net/viewtopic.php?f=10&t=8924

If you still have questions, please ask [here](https://forum.minetest.net/viewforum.php?f=6) or [here](https://forum.minetest.net/viewforum.php?f=3).
Please use this GitHub page only for development-related questions.

**Comment by joshthepheonix** [comment]
huh

**Comment by joshthepheonix** [comment]
why did this get closed

**Comment by joshthepheonix** [comment]
im on android
