### ISSUE TITLE
Use opaque and simple leaves at a distance

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10629]
Current Minetest Master

Leaves are a major contributor to the number of the meshes that need to be rendered - as anybody in a scene with many trees will have experienced.

Opaque leaves everywhere looks dull, and also the moving leaves show gaps to adjacent nodes since they are not transparent.

Instead we could show fancy leaves nearby the player, simple leaves at a distance, and opaque leaves at even a greater distance.

It's perhaps not 100% trivial to incorporate, since this is decided at the nodedef level, but it should not be too hard.

**Comment by lhofhansl** [comment]
Hmm... This is all in the fast face logic, and done at the time a block is loaded by the client, so not straightforward, and probably needs a general LOD framework.

**Comment by lhofhansl** [comment]
Responding to my own issue... After #10501 the impact of leaves on the rendering speed (at least on my H/W) is much lower. So perhaps I should just close this.

**Comment by sfan5** [comment]
Something like this has been on my TODO list to look into for some time.

My idea was that you could swap out the `SMaterial` the block uses before rendering.
This wouldn't be identical to if they were opaque in the first place, but turning the material opaque should(?) still make rendering faster.

**Comment by lhofhansl** [comment]
I tried to hack that. It does not look right (much darker when set to EMT_SOLID).
Strangle it also did not improve the frame-rate, even when I put the cut off point close.

**Comment by hecktest** [comment]
This might actually slow things down with the extra state changes.
