### ISSUE TITLE
Game minimap textures are ignored by Minetest

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10625]
##### Minetest version
```
5.3..
```

##### Summary
If you place a custom minimap texture (see `doc/texture_packs.txt`) into your game, it doesn't work. You will still see the default minimap textures.

##### Steps to reproduce
1. Place some minimap textures like `minimap_overlay_square.png` or `player_marker.png` into any mod of a game
2. Start the game
3. Activate the minimap

**Comment by SmallJoker** [comment]
Duplicate of #7325
