### ISSUE TITLE
Chinese cannot be entered or displayed in chat console

### ISSUE THREAD

**Issue by cosoc** [minetest/minetest#10634]
##### Minetest version

Minetest v5.4.0

##### OS / Hardware

Operating system: centos8

CPU: 2

##### Summary

Chinese cannot be entered or displayed in chat

##### Steps to reproduce

Chinese cannot be entered or displayed in chat

**Comment by sfan5** [comment]
Minetest currently lacks support for IMEs, there is an issue already open for this but I can't find it right now.

Regarding display, Chinese displays fine in the "normal" chat but is invisible in the chat console (F10). That's a bug.

**Comment by SmallJoker** [comment]
Could you please test whether this PR allows you to input more characters: #10458 ?

**Comment by ZhiZe-ZG** [comment]
@SmallJoker Still can't input Chinese in 5.4.0-dev. When paste Chinese characters in chat, them turn into mistaken code.

**Comment by ZhiZe-ZG** [comment]
@SmallJoker And I just tested your key_mess_less edition. Still has the same problem. I think it's not a key thing because Ctrl+V doesn't work too.

**Comment by r1bnc** [comment]
@ZhiZe-ZG can you test at the 5.4.0 stable?

**Comment by ZhiZe-ZG** [comment]
@r1bnc My system is Windows 10. When I select Chinese (Simplify Chinese characters), the system uses GBK encoding by default. So “我” save as 0XCED2 and show as ÎÒ. Then I open the beta feature, use UTF-8 as default encoding. I have no idea what encoding is using in the clipboard. But this time, I paste “我” in Minetest show as "?". The good part is that this character is not treated as two characters this time.

**Comment by ZhiZe-ZG** [comment]
@r1bnc If the problem is missing fonts, is there any way to make Minetest support Unifont fonts or choose fonts by myself?

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/75eb28b95994781d52eb2c09303b1cd04e32b6c5/minetest.conf.example#L1000-L1005

https://github.com/minetest/minetest/blob/75eb28b95994781d52eb2c09303b1cd04e32b6c5/minetest.conf.example#L1048-L1053

**Comment by ZhiZe-ZG** [comment]
@sfan5 
I put unifont.ttf in fonts folder and I modified the configuration and the game crashed.

**Comment by SmallJoker** [comment]
@ZhiZe-ZG Very helpful. Try again, but with absolute font paths (use forward slashes if in doubt). If that does not work either, run Minetest within `windbg` and/or look out for a minidump file which contains the crash information. "the game crashed" does not provide any information.

**Comment by ZhiZe-ZG** [comment]
@SmallJoker I use absolute font paths and it works but still can't show Unicode Characters. The char number of  string is right, but only show "?" instead.

**Comment by sfan5** [comment]
On Linux IME support is added by minetest/irrlicht@3ef59028155ba4cab0f734aecb6bdfc2aa90cbf4 and #11156.
