### ISSUE TITLE
hud_get doesn't return precision for waypoints (returns it as item + 1)

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10630]
...

**Comment by SmallJoker** [comment]
It does return "precision" as "item + 1":

HUD read:
https://github.com/minetest/minetest/blob/ad58ece18062d4c545432b45d71ce6dbe841746b/src/script/common/c_content.cpp#L1880-L1884

HUD write:
https://github.com/minetest/minetest/blob/ad58ece18062d4c545432b45d71ce6dbe841746b/src/script/common/c_content.cpp#L1933-L1934

Easy fix.

**Comment by appgurueu** [comment]
> It does return "precision" as "item + 1":
> 
> HUD read:
> 
> https://github.com/minetest/minetest/blob/ad58ece18062d4c545432b45d71ce6dbe841746b/src/script/common/c_content.cpp#L1880-L1884
> 
> HUD write:
> 
> https://github.com/minetest/minetest/blob/ad58ece18062d4c545432b45d71ce6dbe841746b/src/script/common/c_content.cpp#L1933-L1934
> 
> Easy fix.

I know (I implemented the precision thing), but it's modder-unfriendly.
