### ISSUE TITLE
Brainstorm: Break the big Server::m_env_mutex lock

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10644]
Currently all access to maps and blocks is guarded by a single mutex.

This severely limits useful concurrency on the server. We **emerge/generate** blocks under this lock, we **save** blocks under this lock, we **collect** blocks to be sent to the client(s) under this lock. So all these activities are essentially single threaded.

For example when I just try to do block saving outside of the lock block generation is over 2x faster! 90s -> 40s for a large scene. Because generating blocks does not have to wait for saving unrelated blocks to disk.
(there're bugs and it doesn't actually work 100% so I can't post a PR, but it shows what's possible.)

So I'm looking from some brain storming on what we can do. Perhaps we can lock sectors or another subset of the map rather than effectively the entire map. We can buffer things and map and save in bulk. Etc. None of these turn out to be straightforward.

Other ideas?

**Comment by lhofhansl** [comment]
Some more data points... Map saving sometimes takes multiple seconds (even with the dummy backend - it's the serialization that takes time). I've seen save-times up to **5s** when a large number of blocks were just generated.

Since is happening under lock no blocks can be sent to the client, no blocks can be loaded, no active objects/blocks can be processed.

_The server just stalls!_ We need to come up with a better solution for that.

I tried making a copies of the blocks to be saved and then saving the copies asynchronously, but that quickly spirals out of control, you need to copy the block data (that's doable), but then also all contained objects and whatever they contain, like the NodeMetadataList, which is updated all over the place, pointers being deleted, etc.

I also tried to to do just the serialization asynchronously and cache the result, but that too has too many dependencies.

We can also try to time-box the map-saving per AsyncServerStep. That will not solve the overall problem, but will smooth things.

**Comment by sfan5** [comment]
I'd first investigate why saving takes so long in the case you described.
Does it wait for the disk by flushing? Are you running the map on an SSD? SQLite backend? If yes, have you tried `sqlite_synchronous = 1`?

**Comment by lhofhansl** [comment]
Totally agree.

I have `sqlite_synchronous = 0` (since I have battery backed laptop)... Which should be even faster.
Much of the time is spent in the ZLib compression.

**Comment by lhofhansl** [comment]
More ideas: Can add a read-write lock to each mapblock. Most ops would take a read lock, some a write lock.
ServerMap::m_sectors would turn into a vector<shared_ptr<MapBlock>>, and hence can be cloned before iterating.

With that (and probably some other stuff) ServerMap and MapBlock would be threadsafe and we can remove the large env mutex.
Then it would possible to serve clients with multiple threads, save maps asynchronously, etc.

If locks are too heavy-weight for simple machine, could place locking in a set of macros and make it a compile time options...

**Comment by sfan5** [comment]
Sounds like this idea is worth a try.

> Then it would possible to serve clients with multiple threads,

For map sending at least, pretty much everything else still relies on the env mutex.

> vector<shared_ptr>

Is this really needed? Since write-locks are exclusive you could use those to ensure the MapBlocks are not deleted while in use.

**Comment by lhofhansl** [comment]
> Is this really needed?

Do you have general concerns with shared_ptr? I was thinking that in any event it might be generally better/safer. But perhaps I am missing something.

In this case specifically I want to be able to iterate all the sectors without locking the m_sector collection for the entire iteration. So one would make a copy under lock, then iterate the copy.

**Comment by sfan5** [comment]
No general concerns, just wondering if wrapping every MapBlock in it could be avoided.

**Comment by lhofhansl** [comment]
Oh I meant just the MapSectors, not the MapBlocks.
