### ISSUE TITLE
Get objects inside cube

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10641]
## Problem

We have `minetest.get_objects_inside_radius` which gets all objects within a sphere.

But what if I want to get all objects inside a cuboid? Then I am apparently out of luck.

## Solutions

Add `minetest.get_objects_inside_area` which gets all objects enclosed in a cuboid (between two positions `pos1` and `pos2`).

**Comment by sorcerykid** [comment]
This would be a welcome addition, as I wouldn't have to emulate this functionality in my [Advanced Rangerfinder Mod](https://forum.minetest.net/viewtopic.php?t=24287).

**Comment by hecktest** [comment]
In the meantime, use a position that is the center of the cuboid, and a radius that is half its diagonal, then filter the results using a simple AABB test.

**Comment by Wuzzy2** [comment]
This feature has been implemented! #10668

Thank you!
