### ISSUE TITLE
Absurdly high resource usage and low FPS

### ISSUE THREAD

**Issue by ucodelukas** [minetest/minetest#10648]
![Jn4rsa7](https://user-images.githubusercontent.com/66177541/99675015-02b7b200-2a77-11eb-9caa-b85fdeb8a50e.png)
![xFvwfzb](https://user-images.githubusercontent.com/66177541/99675030-051a0c00-2a77-11eb-95d0-6ae65bda79d2.png)

**Comment by sfan5** [comment]
More information needed, fill out the issue template.

**Comment by ucodelukas** [comment]
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Windows 10
CPU: i7 8700K


GPU model:3x Radeon VII
OpenGL version: 4.6

##### Summary

FPS on 27
##### Steps to reproduce

use minetest

**Comment by ucodelukas** [comment]
@sfan5  any way to fix ?

**Comment by pyrollo** [comment]
> use minetest
I guess you load a game, which game ?
Have you any custom or downloaded mods / textures / maps / anything ? Or just downloaded / installed / created world / played ?

**Comment by ucodelukas** [comment]
both vanilla and modded is affected

**Comment by ucodelukas** [comment]
update was tested with linux too and no diff

**Comment by hecktest** [comment]
Is it any faster when you play on a server as opposed to single player?
What is your draw distance?
Are VBOs enabled in the advanced settings?

**Comment by ucodelukas** [comment]
no
100
makes no difference

**Comment by ata-star** [comment]
news?

**Comment by lu-ccc** [comment]
I can confirm, really bad FPS

**Comment by v-rob** [comment]
This issue is really too vague to be helpful.  I have never encountered such memory usage or bad FPS on default settings.  Unless more information can be provided, there's no point in keeping this PR open any longer.

**Comment by SmallJoker** [comment]
This issue seems to be limited to new Radeon cards on Windows 10. I'd recommend to check for driver updates first. Please check whether following applications have the same issue:
 * https://forum.minetest.net/viewtopic.php?f=14&t=20171 (SAM Viewer)
 * https://github.com/rubenwardy/NodeBoxEditor/ (NodeBox Editor)
 * Any Unity or UnrealEngine game (GOG, Steam, ....?)
     * Yes: AMD driver or Windows issue
     * No: Irrlicht issue

**Comment by sfan5** [comment]
You might want to test a 5.5.0-dev build (e.g. [from here](https://forum.minetest.net/viewtopic.php?f=42&t=1523)) to see if the switch to IrrlichtMt happened to fix this.

Testing a build with the GLES2 driver might also be worth a try: https://kitsunemimi.pw/tmp/minetest-5.5.0-52c0384-gles-win64.zip
