### ISSUE TITLE
View scaled down to 1/4 size of window under Big Sur

### ISSUE THREAD

**Issue by uprince** [minetest/minetest#10654]
**For workaround: https://github.com/minetest/minetest/issues/10654#issuecomment-731368698**

##### Minetest version

```
5.3.0
```

##### OS / Hardware

Hardware: MacBook Pro (Retina, 13-inch, Mid 2014)
Operating system: macOS Big Sur 11.0.1
CPU: 3 GHz Dual-Core Intel Core i7

GPU model: Intel Iris 1536 MB
OpenGL version:
according to /System/Library/Frameworks/OpenGL.framework/Versions/Current/Resources/version.plist : 3
according to minetest client : 2.1

##### Summary

In the client, the view is scaled down to occupy only the bottom-left quadrant of the window.
<img width="1680" alt="Screenshot 2020-11-20 at 12 21 54" src="https://user-images.githubusercontent.com/9484563/99796474-d3b04780-2b2d-11eb-931c-b2c25faf7138.png">
<img width="1680" alt="Screenshot 2020-11-20 at 12 37 46" src="https://user-images.githubusercontent.com/9484563/99796482-da3ebf00-2b2d-11eb-8ea9-147ccbb1f110.png">

##### Steps to reproduce

- upgrade to Big Sur
- `brew install minetest`
- run

**Comment by sfan5** [comment]
That's likely an Irrlicht bug, I remember that @MoNTE48 has done a lot of work on this, but it's not clear if the fixes can be imported into Minetest.

**Comment by MoNTE48** [comment]
Just recompile Minetest with my Irrlicht fork and everything will be work
https://github.com/MoNTE48/Irrlicht/commits/master

**Comment by uprince** [comment]
I ended up downloading the latest build from https://github.com/neoascetic/minetest/releases instead of the brew cask and it seems to work fine.

**Comment by MoNTE48** [comment]
@uprince, you have Retina resolution, or 1/4 of the real resolution, upscaled to your screen?

**Comment by uprince** [comment]
I have tried both 'default' (four-for-one) and 'more space' (one-for-one) pixel resolutions in System Preferences > Displays and the effect was the same (even after quitting and restarting minetest). I don't think it made a difference but I'll just add that the setting was still on one-for-one when I got the nigthly from neoascetic and remains so. Let me know if more tests would help.

A side note about the solution you suggested previously :
I did replace `/usr/local/Cellar/irrlicht/1.8.4/lib/libIrrlicht.a` with the one I built from your fork, and then compiled minetest as explained on https://forum.minetest.net/viewtopic.php?t=9190, but it would segfault on startup. First it was because I had not provided a game in `~/Library/Application Support/minetest/games` so that was easily solved, but the next segfault came without a log and the reason might have been just as simple but I was stumped ant that is when I went for a nightly.

**Comment by MoNTE48** [comment]
My fork is based on the latest Irrlicht 1.9. Therefore, you also needed to replace headers (include folder).
I'm not very familiar with this on macOS. I just provided fixes.
I've always worked in Xcode, while Minetest prefers to use only CMake and only command line (**best for user friendly in 2020 year**)...
Maybe @sfan5 can help you more.

**Comment by Sraime** [comment]
I have exactly the same problem :(

**Comment by jasikpark** [comment]
> I ended up downloading the latest build from https://github.com/neoascetic/minetest/releases instead of the brew cask and it seems to work fine.

Same - this works fine for me as well.

**Comment by fnetX** [comment]
My brother ran into the very same issue after upgrading from 5.3.0 to 5.4.0_1. Is there something else one can do without "upgrading" to an apparently unmaintained unofficial release provider?
Is there any information missing I can try to provide?

**Comment by WeirdCircumstances** [comment]
The bug still affects me.
Minetest is in Version 5.0.4_1, OS is BigSur, nothing changed.
Same question as @fnetX : I don't want to use a unmaintained version.

**Comment by sfan5** [comment]
This will be fixed officially in 5.5.0 once it is released, you can either install 5.5.0-dev (from source, there are no builds I'm aware of) or use whatever else there is.

**Comment by WeirdCircumstances** [comment]
> This will be fixed officially in 5.5.0 once it is released, you can either install 5.5.0-dev (from source, there are no builds I'm aware of) or use whatever else there is.

Perfect, thank you!

**Comment by sirnewton01** [comment]
At a quick glance I'm not seeing from the README how to compile for Mac. It's only Linux/Windows. Any guidance? Thanks.

**Comment by Emojigit** [comment]
You can use homebrew. See it's doc to install the minetest package.

Chris McGee ***@***.***> 於 2021年8月14日週六 下午10:25 寫道：

**Comment by sirnewton01** [comment]
I'm not seeing how to install the 5.5.0 version of minetest using homebrew or how to use it to compile for macOS.

> You can use homebrew. See it's doc to install the minetest package. Chris McGee ***@***.***> 於 2021年8月14日週六 下午10:25 寫道：

**Comment by Emojigit** [comment]
You can download depended via homebrew then compile irrlichtmt and minetest
dev yourself

Chris McGee ***@***.***> 於 2021年8月15日週日 下午8:09 寫道：

**Comment by sirnewton01** [comment]
Thanks, yes, I have the the 5.4.0 minetest installed through homebrew, so I probably have the dependencies. To compile irrlichtmt and minetest, how do I compile them? Is it cmake/ninja or something? What options do I need for them?

> You can download depended via homebrew then compile irrlichtmt and minetest dev yourself

**Comment by sfan5** [comment]
> At a quick glance I'm not seeing from the README how to compile for Mac. It's only Linux/Windows. Any guidance?

This should do it, untested as I don't own a Mac:
```bash
brew install cmake curl freetype gettext libjpeg libogg libpng libvorbis luajit
git clone https://github.com/minetest/minetest
cd minetest
git clone https://github.com/minetest/irrlicht lib/irrlichtmt
cmake . -DRUN_IN_PLACE=0
make -j$(nproc)
make package
# there will be an .app inside the created ZIP file
```

**Comment by sirnewton01** [comment]
Thank you, I managed to successfully compile and run it. However, it looks like 5.5.0-dev has another bug where the camera spins out of control on macOS.

**Comment by crazyss** [comment]
Is there any plan for the 5.5.0 release?

**Comment by sDaniel** [comment]
Jus want to confirm this issue with the current version installed via brew 5.4.1 on mac os Big Sur 11.6 (20G165)
