### ISSUE TITLE
Unable to download mods from browse online content (Download Denied, Temp folder isn't a allowed path)

### ISSUE THREAD

**Issue by Malteusa** [minetest/minetest#10657]
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Windows 10

##### Summary
As the title says, I am unable to download mods/content from Minetest's "Browse online content". I have also tried to run Minetest as an administrator and still gives an error. I am however able to download the content from the website through a browser.
Log :
```
ERROR[AsyncWorker-0]: DOWNLOAD denied: I:\AppData\Temporary Files\Temp\sag4._MODNAME_mobs.zip isn't a allowed path
ERROR[AsyncWorker-0]: downloading "https://content.minetest.net/packages/TenPlus1/mobs/releases/5530/download/" failed
```
I had moved the Temporary Files folder's location from the default C-Drive to another drive in order to save space. However moving the folder back to the default location doesn't work and still gives me the error. Moving the Temp folder in the same drive as Minetest still gives the same error. As said earlier I have tried running the app as administrator and that didn't work. Other applications can access the folder normally.

##### Steps to reproduce
1. Open Minetest
2. Click on Browse online content
3. Click Install on any mod
4.  `An Error Occurred:`
   `Failed to Download (modname)`
And the logs are the same.

**Comment by SmallJoker** [comment]
C++ uses `GetTempPath` to check whether it's an allowed path
  * Depends on env variables https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettemppatha

Lua uses a custom `os.tempfolder()` function to download the files.
  * minetest.conf setting `TMPFolder` (if specified)
  * or function `os.getenv("TEMP")`

This is an interesting bug where the path permission check in Minetest uses slightly different functions than Lua. 

As a workaround, create the directory "downloads" in "path\to\Minetest\cache\" and add the following minetest.conf setting:
```
TMPFolder = path\to\Minetest\cache\downloads
```

**Comment by rubenwardy** [comment]
@Malteusa please may you try #10892 to see if it fixes your problem?

Download: https://github.com/minetest/minetest/suites/1943672677/artifacts/38416220
