### ISSUE TITLE
The Itch.io page does not mark the game as running on platforms other than Windows and Android

### ISSUE THREAD

**Issue by Wilker-a** [minetest/minetest#10655]
##### Minetest version

current Itch.io page as of 21/11/2020 (https://red-001.itch.io/minetest) ([archive page](https://web.archive.org/web/20201121155957/https://red-001.itch.io/minetest))

##### Summary
the current available page on Itch.io, a platform for publishing various drm-free games, has the download section making available only versions for Windows and the store page for the game at the Google Play Store.

i think this might be more of a suggestion: it would be good to include in the page, either files or instructions for installing the game on the other platforms, as well as include the [F-Droid page](https://f-droid.org/en/packages/net.minetest.minetest/) of the game. it can help make it easier for people to even find different platforms like F-Droid in a way.

what do you think? :3

**Comment by sfan5** [comment]
We do not run this page and the version offered on it is outdated too.
Judging by the subdomain the page is likely owned by @red-001

**Comment by rubenwardy** [comment]
Fixed
