### ISSUE TITLE
MapBlocks rendered too late on screen bounds

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#10665]
Git HEAD.

Due to the recent @lhofhansl changes, the MapBlock meshes are rendered too late on the border of the screen when moving the camera.

Watch the left border of this video: https://youtu.be/XHOvpA8nmJI

**Comment by sfan5** [comment]
My guess goes towards 521a04222a71325ef217d1214febf5591919e169

**Comment by kilbith** [comment]
I confirm that reverting 521a042 **does** fix the issue. No glitches.

**Comment by lhofhansl** [comment]
Happy to revert that one.

I will say that it *is* very wasteful, just to avoid a bleep when panning the camera. These extra blocks are always loaded, HW buffers allocated, etc, reducing FPS, even when you do not pan around just to be there in case you do pan the camera.

If you move the camera faster you'll still see glitches, right? So how much buffering should we do? This one loaded ~10% extra block, in order to avoid more bleeps we could load 20% more blocks.

Not complaining, just asking how much extra work and FPS performance is that effect worth?

If you want to revert, I'll do that.

**Comment by kilbith** [comment]
I will say that accepting these glitches for a relatively small performance boost is not on-par with the high-quality standards we aim for a game engine. The scene doesn't look good, and that is all that matter.

**Comment by lhofhansl** [comment]
I agree. But that wasn't quite the nature of my question. Even with 20% extra blocks you still get these artifacts if you pan too quickly. So should we increase that? Or is 10% good enough?

**Comment by lhofhansl** [comment]
Also weird that these only appear on the left side. Hmm...

**Comment by kilbith** [comment]
> Even with 20% extra blocks you still get these artifacts if you pan too quickly

No

**Comment by lhofhansl** [comment]
:)

So anything magic about 20% extra fov?

**Comment by kilbith** [comment]
I didn’t get any glitches with 20% extra blocks, that’s just plain wrong. I’m willing to take a video tomorrow

**Comment by kilbith** [comment]
Also please have the intellectual honesty to mark this issue as a [bug]

**Comment by lhofhansl** [comment]
That all said... I can see the effect. But even when I extend the FOV bu 5% it seems to go away.

@kilbith Could you just try with 1.05 and 1.1 as multiplier once?

Then I'll restore it.

**Comment by lhofhansl** [comment]
I to not see any glitches with 1.1 as the multiplier.

You might feel this is pithy, but a 20% larger FOV leads to 35% more blocks are rendered. Whereas 10% causes 17% of more blocks.

Volume of the view cone = 2/3 * pi * r^3 * (1 - cos(FOV)). Taking r as the default if 12 blocks, you get 3391 vs 2500 blocks. That is not a small difference. With a 10% increase in FOV you'd get 2940 blocks.

> Also please have the intellectual honesty to mark this issue as a [bug]

I hear rumors of a sinister conspiracy where the core devs are hiding MT bugs from the public.

**Comment by hecktest** [comment]
So either the frustum culling function is wrong, or it's being done using stale data. The 20% hack was bad, and whatever is happening now is bad as well. Gotta do this right, folks.

**Comment by kilbith** [comment]
> I do not see any glitches with 1.1 as the multiplier.

Tested and neither do I. `1.05` is barely glitchy. `1.1` is a good value.

**Comment by lhofhansl** [comment]
Thanks @kilbith 

@hecktest Not sure what it "right" here. It seems we need to "pre-render" blocks in the edge of the view cone in order to avoid these glitches.

For now I'll restore this with 10%.

**Comment by hecktest** [comment]
"Right" means doing a collision test between the frustum and the bounding boxes of meshes, after the frame step and before doing any rendering. You know, a frustum cull, that's what it's called. A proper frustum cull should not display those glitches. If it does, our culling function is wrong, or we're feeding it bad data. Culling functions should never, ever trip false positives.
The issue may be stale input like #10027.
Voodoo magic like padding the frustum is just a bad solution to already bad code. The only thing that actually needs padding is the bounds of waving meshes.
I think Irrlicht has frustum culling built in, and we should be using that, but ClientMap is a single monolithic ISceneNode and that breaks it. We're using Irrlicht but we're not actually _utilizing_ it.

**Comment by lhofhansl** [comment]
Fixed. (Albeit by reinstating the hack)
