### ISSUE TITLE
Fun with "sphere mapping".

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10672]
I was playing around with how to reveal the edges of the world in a graceful way.

Have a look:

This is with a strong effect to just see it:
https://www.youtube.com/watch?v=XTndl4PxL6I

This is a softer effect:
https://www.youtube.com/watch?v=RbhvpQ5hDso

It can be varied easy and made softer.

I wish I could say I did some super complex sphere mapping. The actually logic is shader only, very simple, and essentially free in terms of performance.
I am making use of the fact that a parabola for low x approximates a section of a circle.

Mostly for fun.

**Comment by SmallJoker** [comment]
That looks very familiar.
https://www.youtube.com/watch?v=ztAg643gJBA

**Comment by hecktest** [comment]
#9907 before someone makes this a silly global feature

**Comment by lhofhansl** [comment]
@SmallJoker That one does actual sphere mapping. :)
@hecktest Agreed. But that one is not in and there's still discussion.

**Comment by lhofhansl** [comment]
Works with entities, but not with particles - I think.
And it's not compatible with tiling, since it adjust vertices, and hence you sometimes see small gaps between tiles.

In any case it's literally 8 lines of code, I have no intentions of filing a PR, unless someone wants to see/try it.

**Comment by hecktest** [comment]
There will be trouble as soon as you feed it a mesh with any T-junctions or intersections.

**Comment by numberZero** [comment]
Wow, this looks great!

> And it's not compatible with tiling
> There will be trouble as soon as you feed it a mesh with any T-junctions or intersections.

If a mesh is not a mesh, there will always be troubles. See https://github.com/minetest/minetest/pull/7514#issuecomment-422945774 and https://github.com/minetest/minetest_game/pull/1528 as examples.

**Comment by lhofhansl** [comment]
Anyway. Closing. Was just showing it here.
