### ISSUE TITLE
Include Posgresql by default on minetestserver

### ISSUE THREAD

**Issue by AugTop** [minetest/minetest#10677]
My classmate and myself are trying to set up a server using as a database for the map and postgresql players. 
However, each time we update the server, we have to recompile the whole minetestserver in order to activate postgresql support, wouldn't it be possible that postgresql support is activated by default on the minetestserver and to set this parameter in the minetest.conf ?

**Comment by MoNTE48** [comment]
This is very specific lib and many systems do not have this package. Or the package version is different.
You probably don't need to use such a high performance database for multiple people. Postgres is great if you have 50-100+ players online on your server.

**Comment by sfan5** [comment]
Whether postgresql is included by default depends on your distribution (or are you using Windows? that'd would've been useful to write in this issue). We don't make this choice, packagers of your distributions do.
