### ISSUE TITLE
#7924 causes unwanted rightclicking in certain situations

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#10675]
##### Summary
See https://github.com/minetest/minetest/pull/7924#pullrequestreview-433633357 and https://notabug.org/TenPlus1/mobs_redo/issues/78

>  When rightclicking with the hammer in my hand it instantly rightclicks the spawned entity instead of requiring a second click
    My LMB check doesn't work (Called when the player holds LMB while the hammer is lifting nodes around) https://github.com/LoneWolfHT/hammer_of_power/blob/master/init.lua#L493

##### Steps to reproduce
The code below or https://notabug.org/TenPlus1/mobs_redo/issues/78

 Copypasta:
```Lua
minetest.register_node("test:testnode", {
	description = "testnode",
	tiles = {"air.png"},
	groups = {oddly_breakable_by_hand = 3, snappy = 1},
	on_secondary_use = function(_, user, _)
		local name = user:get_player_name()
		local pos = user:get_pos()
		pos.y = pos.y + 1.5

		local obj = minetest.add_entity(
			vector.add(pos, vector.multiply(user:get_look_dir(), 2.5)),
			"test:entity"
		)
	end,
})

minetest.register_entity("test:entity", {
	initial_properties = {
		physical = true,
		collide_with_objects = false,
		selectionbox = {-0.25, -0.25, -0.25, 0.25, 0.25, 0.25},
		pointable = true,
		visual = "cube",
		visual_size = {x = 0.5, y = 0.5, z = 0.5},
		textures = {},
		is_visible = true,
		automatic_rotate = 20,
		glow = 4,
		static_save = false,
	},
	on_punch = function(self, puncher, _, _, dir)
		self.object:remove()
	end,
	on_rightclick = function(self, clicker)
		minetest.chat_send_all("REMOVING")
		self.object:remove()
	end,
})
```

**Comment by LoneWolfHT** [comment]
Updated the code. Apparently it would also spawn a new entity after removing it, so it looked like nothing was wrong. You will now see a chat message whenever the entity is removed

**Comment by hecktest** [comment]
Possibly the same issue: Right clicking the air, releasing and then moving the cursor over an interactable entity will fire the interact event as soon as that entity is pointed at. Something isn't eating this event when it should, and it sticks around until there's an entity to receive it.

**Comment by SmallJoker** [comment]
3176dae Confirmed working by @LoneWolfHT
