### ISSUE TITLE
Cannot change to third person view

### ISSUE THREAD

**Issue by AlanReviews** [minetest/minetest#10678]
##### Minetest version
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/share/minetest"
STATIC_LOCALEDIR="/share/locale"
```

```

##### OS / Hardware

Operating system: Ubuntu 18.04
CPU: Intel Core i7-5600U Processor (4M Cache, up to 3.20 GHz)

GPU model:
OpenGL version:

##### Summary

I cannot change to third person view in Minetest. I tried to press F7 and it does not work.

##### Steps to reproduce

1. Instal Minetest
2. Install Minetest tutorial or game
3. Try press F7 in Minetest tutorial or game.

**Comment by LoneWolfHT** [comment]
Press C @AlanReviews

**Comment by wsor4035** [comment]
changed in https://github.com/minetest/minetest/pull/9779 may wish to change you minimap key binding back as well
