### ISSUE TITLE
document mod_origin in node def ?

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest#10689]
## Problem

minetest.registered_nodes["name"].mod_origin is not documented
source: https://github.com/minetest/minetest/blob/master/builtin/game/register.lua#L178

## Solutions

asking to see if this should be documented, and if so where. (i personally believe it should be documented as it may be useful to moders)

## Alternatives

not documenting it

## Additional context

if it is wanted, should it be listed under https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L7241 ?

if it is wanted, I will make a PR for it, asking here first to check

**Comment by LoneWolfHT** [comment]
**modname**:node?
Why does that even exist?

**Comment by randomMesh** [comment]
My 2 cents: I consider missing documentation a bug rather than a missing feature

**Comment by rubenwardy** [comment]
> **modname**:node?
> Why does that even exist?

Because mods can register items in the namespace of other mods. For example, when you register with ":default:thing", the nodename will say "default" but mod_origin will say "mymod"
