### ISSUE TITLE
CSM: core.localplayer is nil

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#10682]
##### Minetest version
```
5.3
```

##### OS / Hardware

Operating system: Windows
CPU: Core i7

##### Summary
core.localplayer is nil

**Comment by SmallJoker** [comment]
Mods are loaded before the player is ready. Similar to Camera, it'll only be available after a while:
https://github.com/minetest/minetest/blob/3176daee79a8e91bd16fc275704f49fe1648db32/doc/client_lua_api.txt#L968-L970

**Comment by AFCMS** [comment]
> 
> 
> Mods are loaded before the player is ready. Similar to Camera, it'll only be available after a while:
> 
> https://github.com/minetest/minetest/blob/3176daee79a8e91bd16fc275704f49fe1648db32/doc/client_lua_api.txt#L968-L970

But, then, how to call the core.register_globalstep() who use core.localplayer ?

**Comment by v-rob** [comment]
> But, then, how to call the core.register_globalstep() who use core.localplayer ?

```lua
minetest.register_globalstep(function(dtime)
    if not minetest.localplayer then
        return
    end
    -- Do your stuff here...
end)
```

**Comment by AFCMS** [comment]
@v-rob Yes, but it's heavy. For graphical mod, it make the refresh time bigger.
Is it possible to solve the availability of player ?

**Comment by appgurueu** [comment]
> @v-rob Yes, but it's heavy. For graphical mod, it make the refresh time bigger.

Not heavy at all. Using a `register` call is neat, but doesn't improve performance all that much. On a different note, you can replace the globalstep by accessing `minetest.registered_globalsteps`, keeping performance at max:

```lua
function register_globalstep_on_mods_loaded(func)
    local function wrapper_func(dtime)
         if not minetest.localplayer then return end
         func(dtime)
         for i, globalstep in pairs(minetest.registered_globalsteps) do
              if globalstep == wrapper_func then
                  minetest.registered_globalsteps[i] = func
              end
         end
    end
    minetest.register_globalstep(wrapper_func)
end
```

**Comment by v-rob** [comment]
It's a single if statement only runs ~10 times per second.  That's such a small time that it's impossible to notice.  Heck, I'm working with code that runs every _frame_ and the effects of an if statement are completely unnoticeable.  It's really not worth worrying about the performance of an if statement.
