### ISSUE TITLE
libretro port?

### ISSUE THREAD

**Issue by DartPower** [minetest/minetest#10680]
Hi there, i have a idea, you want to port to libretro?
This is will be cool.
I'm true fan of open-source gaming and love your project & RetroArch :D 
(Sorry for my bad english)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by rubenwardy** [comment]
Minetest is open source software, you're welcome to make an (unofficial) port to libretro. We're even willing to accept code to fix support on lesser used platforms providing that they're not too overreaching (we do this for HaikuOS). 

We only officially maintain a minority of Minetest ports, most are third-party and managed by distro maintainers.

Releasing Minetest is painful enough for the platforms we currently support, and we have enough work that takes higher priority. Therefore, I'm closing this issue. Don't let this dissuade you from porting as a third-party, though!
