### ISSUE TITLE
Storing of binary string as mod storage doesn't work as expected

### ISSUE THREAD

**Issue by joe7575** [minetest/minetest#10685]
##### Minetest version

```
5.4.0-dev-33b2c5f5b
```

##### OS / Hardware

Operating system: Linux / Xubuntu 20.04
CPU: Intel Core i3-4170

GPU model:
OpenGL version:

##### Summary

A binary string gets longer, when stored in the mod storage. See the code below.
 
##### Steps to reproduce

```
local storage = minetest.get_mod_storage()

-- generate a binary string
local tbl = {}
for i = 0,255 do
	tbl[i] = string.char(i)
end
local s = table.concat(tbl)
print("origin length of s is", #s)

minetest.register_on_mods_loaded(function()
	local s = storage:get_string("teststring")
	print("register_on_mods_loaded: No the length is", #s)		
end)

minetest.register_on_shutdown(function()
	print("register_on_shutdown: the length is", #s)		
	storage:set_string("teststring", s)
end)    
```
Run this piece of code and check the output:

```
origin length of s is	255
register_on_shutdown: the length is	255
register_on_mods_loaded: No the length is	274
```

**Comment by randomMesh** [comment]
You can't save binary strings in the mod storage due to limitations of JSON.
I quote lua_api.txt

> WARNING: This storage backend is incaptable to save raw binary data due
to restrictions of JSON.

**Comment by joe7575** [comment]
Ok thanks, I did not realized that.
But then i need a solution for #10684 :=)
