### ISSUE TITLE
Ability to crouch and sprint

### ISSUE THREAD

**Issue by AlanReviews** [minetest/minetest#10691]
## Problem
Can we have the ability to crouch and sprint in Minetest?

## Solutions
Crouching where a player moves closer to the ground. Sprint can be helpful for running from one place to another quickly.

## Alternatives
One alternative I considered is Minecraft

**Comment by SmallJoker** [comment]
Sprint: W + E, check for `fast` privilege and whether it's enabled (configure hotkeys)

Crouching: either duplicate of #2063, or can be implemented using mods. No need to hardcode this into Minetest.

**Comment by domsson** [comment]
Too bad this was closed - `fast` privilege is nothing like what one would expect from sprinting. Sprinting is therefore not yet implemented.
