### ISSUE TITLE
DISCUSS: Change default compression to 3

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10696]
See IRC discussion: https://irc.minetest.net/minetest-dev/2020-12-03#i_5757559

I looked at the zlib code, and compression level 3 is highest level that internally uses deflate_fast, 4-9 use deflate_slow. Zlib's default is 6.

Between level 6 and level 3 I see a 3x improvement in save times (that is with SQLite stored in SSD), and about 1/3 increase in storage size. That seems to be an acceptable trade off. My machine is pretty fast, so on slower machine I'd expect an even more significant relative improvement.

Note that map saving is done with a global lock - the env lock, and so the entire server will essentially hang during mapsave. Ultimately we should allow this to be threadsafe and happen asynchronously, but until then we can at least reduce the CPU overhead. The the work in chunks also helps with server-latency spike, but obviously does not reduce the aggregate work to be done.

So... I'm proposing changing the default to 3. Everything is backwards compatible, zlib can decode at any compression level. People especially with older machine will be thankful. We can do with for disk and network, or disk only.

If that is too radical, we can add a (or two, disk and network) config option(s) - but I'm really not a fan of yet more config options.

**Comment by SmallJoker** [comment]
If this should be changed, it should really be configurable so that server admins can decide what to prioritize.
Some might want to have least write cycles on their MicroSD card in a Raspberry PI server.

**Comment by hecktest** [comment]
Add the option for the map, loosen up the default to 3, keep compression tight for network.
I hate config bloat too but this particular option would be useful and easy to understand.

**Comment by sfan5** [comment]
> Ultimately we should allow this to be threadsafe and happen asynchronously, but until then we can at least reduce the CPU overhead.

Since map saving is not a bottleneck for most people I disagree with this "add a workaround until it can be fixed properly" way.
I'd be fine with making this a setting though for the people whose usecase requires it.

**Comment by lhofhansl** [comment]
There're schematics as well, specifically serializing to/from mts. It's also using the default compression, perhaps we'll just leave that.

**Comment by lhofhansl** [comment]
@sfan5 I think many people just expect their server (i.e. lua entities, block loading, etc) to be laggy.
