### ISSUE TITLE
Gnome 3.8 Overview bug

### ISSUE THREAD

**Issue by davidgumberg** [minetest/minetest#1071]
Fedora 19 i686
Gnome 3.8.4
Minetest 4b31a38ae9

When Minetest is the active window, if you go to overview mode, everything behaves as should, but if you select another workspace, and then switch back to the minetest workspace, Minetest will take over the mouse input, and begin taking input while still in overview, also making the pointer stuck in its original position. This doesn't occur if minetest isn't the active window, or if minetest is paused or inventory is open. This is more easily shown than explained.

http://youtube.com/watch?v=wX89674Yd4A

**Comment by nerzhul** [comment]
This bug isn't related to minetest but irrlicht (and some other proprieraty games too) (problem with gnome 3.14 too)
I close the issue
