### ISSUE TITLE
Menu is very small, cannot navigate it as well

### ISSUE THREAD

**Issue by jasonhan-vassar** [minetest/minetest#10718]
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: macOS 11.0.1
CPU: 2.3 GHz 8-Core Intel Core i9

##### Summary
The main menu is small and only takes up a small fraction of the window. Resizing the screen does not seem to fix things. Here are some screenshots below:

<img width="1680" alt="Screen Shot 2020-12-12 at 12 52 57 PM" src="https://user-images.githubusercontent.com/34594853/101991252-69487e00-3c79-11eb-8e60-42576f583499.png">

<img width="1680" alt="Screen Shot 2020-12-12 at 12 52 31 PM" src="https://user-images.githubusercontent.com/34594853/101991253-6c436e80-3c79-11eb-8ad7-9dc025f607d4.png">

It seems that I cannot directly hover over menu items as well. However, if I hover around where the buttons are supposed to be if the menu were normal size, they glow and can be pressed.

##### Steps to reproduce
Install minetest from homebrew and open `minetest.app`. The issue should be apparent immediately.

This does not occur on 5.4.0.

**Comment by Zughy** [comment]
> This does not occur on 5.4.0

So it has been fixed already. Not an issue then

**Comment by jasonhan-vassar** [comment]
Whoops, sorry about that. I thought giving it some visibility would be nice since 5.3.0 is supposed to be a "stable" build.
