### ISSUE TITLE
Can't find locale after compile

### ISSUE THREAD

**Issue by ZhiZe-ZG** [minetest/minetest#10710]
##### Minetest version

```
Minetest 5.4.0-dev-6d7067fd3 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system:
CPU: Intel core i7 

GPU model: Nvidia RTX 2060
OpenGL version:

##### Summary
I build minetest 5.4.0-dev using cmake, vcpkg and vs2019 on windows10. The game can run but no locale file was generated and changing language setting has no effect.

I did it according to the steps in README.  What could I do wrong?

##### Steps to reproduce
According to the steps in README.
The game can start normally.

**Comment by LoneWolfHT** [comment]
Sounds similar to this https://forum.minetest.net/viewtopic.php?p=385056#p385056

**Comment by SmallJoker** [comment]
> USE_GETTEXT=0

You'll need gettext support for locales. According to https://github.com/minetest/minetest/pull/8317#issue-258228144 it's supported, but not tested yet. Check your cmake flags (`-DENABLE_GETTEXT=1` or similar) and check what happens.

**Comment by randomMesh** [comment]
In addition to the cmake switch to enable gettext, you need to install the corresponding package.
On Debian-like systems it's `apt install gettext`. This part is missing from the installation docs.
