### ISSUE TITLE
No zh_CN and zh_TW locale in the setting list but they are usable

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10717]
##### Minetest version

This problem happens on both 5.3.0 and 5.4.0

##### Summary
I can't see `zh` lang options in the settings list, I can't use them by edit `minetest.conf` without edit `builtin/settingtype.txt` either.

I can use it in 5.4.0 with default lang, but I can't use it normally in 5.4.0 windows

##### Steps to reproduce
1. Try to find `zh_TW` or `zh_CN` in the lang list
2. You can't find them
3. Then, change the lang to `zh_TW` or `zh_CN` in `minetest.conf`
4. After you restart, the language change to blank
5. Change `builtin/settingtype.txt` , add two zh to it: `language (Language) enum   ,ar,ca,cs,da,de,dv,el,en,eo,es,et,eu,fil,fr,hu,id,it,ja,ja_KS,jbo,kk,kn,lo,lt,ms,my,nb,nl,nn,pl,pt,pt_BR,ro,ru,sl,sr_Cyrl,sv,sw,th,tr,uk,vi,zh_TW,zh_CN`
6. You can now use Chinese now
7. If you are using a Chinese computer, you can use Chinese without any change, but I don't know why my Chinese windows computer can't use it normally.

**Comment by sfan5** [comment]
I'm pretty sure this will automatically be updated when `settingtypes.txt` and `minetest.conf.example` is regenerated.
So this should be fixed once 5.4.0 is released.

**Comment by Pevernow** [comment]
I have the same question.

**Comment by sfan5** [comment]
Still not fixed, looks like this has to be manually updated:
https://github.com/minetest/minetest/blob/285ba74723695c4b51192dac0e1e17c5d8f880db/builtin/settingtypes.txt#L1398
