### ISSUE TITLE
Browse online content - Deinstall button too small if language is German

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest#10712]
##### Minetest version
```
Minetest 5.4.0-dev-6d7067fd3 (Linux)
```

##### Summary
The button to deinstall packages is too small if language is German:

![2020-12-09-010530_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/101604373-1fedf980-3a01-11eb-93f2-6d5ef3c3a591.png)

**Comment by sfan5** [comment]
duplicate of #10069
