### ISSUE TITLE
Shift key state of the Inventory/chests/etc. menus stuck on after shift-clicking and then releasing the shift key

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#10720]
##### Minetest version

```
Minetest 5.4.0-dev-e18b6c5a2 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu Linux 20.04 LTS
CPU:  Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary

Holding shift anywhere in any inventory menu while clicking on an item and then releasing the key does not turn off the shift key state for the menu. Clicking on an item just drops it on different location w/o actually holding shift. Some times the state can be restored by going from one type of inventory to another (such as e.g. from chest to user (crafting) inventory)

##### Steps to reproduce

1. Open a chest or your inventory
2. Shift-click an item
3. Try to click on another item w/o holding Shift, it will go to another place as if shift clicked, item would not be selectable for manual placement
4. (Optional) Go to different type of inventory (if on a chest go to your inventory, otherwise go to chest), click on item: it behaves normally
5. (Optional) Go back to previous inventory type, inventory should behave normally until Shift-clicked again

**Comment by sfan5** [comment]
The culprit: e18b6c5a21880125284d2a1e9dfb5471d5bc2bec
