### ISSUE TITLE
Clientside prediction needs to be improved

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1072]
To deliver a smoother experience the client should try to predict at least some actions:
1.) moving items in or between inventories takes a whole roundtrip, because the client tells the server that it wants something moved, in turn the server tells the client that something has been moved. This could easily be predicted in the client.
2.) Minecarts: Will always follow tracks, given a quite limited set of rules, basic prediction should be possible
3.) Abstract mounts (boats, ostrich, those flying thingies constructed from nodes): either fly (do not fall) swim (do not fall below water) or "walk" (will fall). follow input by the player, acceleate to a given maximum, change direction with a given speed. should be predictable, too.

Maybe there are even more things which could be predicted, those just came to my mind first. Until the network situation has been improved those things are painfully laggy/slow/delayed, even with sapiers fixes (and i assume thats true for enet, too as nothing can beat the rtt) its just too slow to be comfortable and or usable.

**Comment by hunter688** [comment]
Prediction inventory action will be best. Now is inventory actions like on lagged minecraft server. Nigthmare.

**Comment by Zeno-** [comment]
See also #1988 and #1374

**Comment by nerzhul** [comment]
I'm closing this as we now have Client Side Modding in core which will permit to solve many lag issues in the future

**Comment by rubenwardy** [comment]
We still have client side prediction issue, csm doesn't change that yet

**Comment by sofar** [comment]
https://github.com/minetest/minetest/pull/3891

**Comment by Zughy** [comment]
Client node dig prediction was implemented 5 years ago: https://github.com/minetest/minetest/commit/5b3fbf9cf75f9f637c666d34e2489fef0cc035d9

Is this still a valid issue?
