### ISSUE TITLE
Separate viscosity into "move resistance" and "spread speed"

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10736]
## Problem

Currently, liquid nodes can have a `liquid_viscosity`. This thing actually controls two things at once:

1) Move resistance: The speed in which you can move through the node (the higher the viscosity, the slower you move)
2) Spread speed: How fast the liquid spreads to other nodes (the higher the viscosity, the slower it spreads)

Both things are inherently linked. If you increase the viscosity, you always increase *both* the move resistace and the spread speed. But it is not possible to e.g. have a slow spreading liquid in which you also can move through fast, or a fast spreading liquid in which you move through slowly. This is a bit inflexible.

## Solutions

Split the `liquid_viscoity` into two features:

* `move_resistance` for move resistance and
* `liquid_spread` for the liuqid spread speed. (The field names are just examples, feel free to think of better ones).

To make things simple, the values will have the same meaning as for current `liquid_viscosity`. E.g. a `liquid_spread` of 4 will have the same spread speed as if when you set `liquid_viscosity` to 4. Same for `move_resistance`, of course.

For backwards-compability, continue to support `liquid_viscosity`. This can be done like this:

If this field `liquid_viscosity` is specified and neither `move_resistance` or `liquid_spread` are specified, this value will automatically set `move_resistance` and `liquid_spread`. If either `move_resistance` or `liquid_spread` were specified explicitly, then `liquid_viscosity` is ignored.

## Additional context

Related: #1822, which suggests to make viscosity settable for non-liquids. I like to alter this suggestion: Allow `move_resistance` to non-liquid nodes, but not `liquid_spread` (since it does not make sense for non-liquids).

**Comment by randomMesh** [comment]
Imho the original behaviour is correct since move resistance and spread speed are dependent on each other in real life physics.
I can't think of a liquid which has a high spread speed and a low move resistance or vice versa.

I'd leave it as it is. Separating these two values would complicate things for little to no gain.
