### ISSUE TITLE
Improve the analog stick deadzone implementation

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#10730]
@m42uko 
The current implementation of the analog deadzone has the following problems:
- It's not normalized
- It's done on each individual axis
- The deadzone setting is (probably?) an unsigned short - 0.0 to 1.0 would be much easier to understand.

Here's a lousy drawing that illustrates what's going on:
![deadzone](https://user-images.githubusercontent.com/42101236/102701250-51629280-4255-11eb-8e73-570974faa325.png)

In short, the character will either tend to walk diagonally or in the cardinal directions, depending on the deadzone setting. The camera behaves oddly too, not letting itself be turned slowly if a higher deadzone is set. There's probably gremlins related to the camera's turning direction but I couldn't get a second axis working so I can't test it.

Low deadzone (biased towards diagonals):
https://user-images.githubusercontent.com/42101236/102701356-8cb19100-4256-11eb-96be-aee7cd5a8814.mp4

High deadzone (biased towards cardinals, camera snaps):
https://user-images.githubusercontent.com/42101236/102701363-a226bb00-4256-11eb-9426-7f7dbea1a031.mp4

## Solution

Do all analog stick math in polar coordinates, that is, represent the input as angle and magnitude. Remap the magnitude so that the output magnitude is always in the 0-1 range, and partition the angle evenly into 8 sections to simulate directional input. (Player movement should be analog, but that's due for another issue)

**Comment by m42uko** [comment]
I am aware of this problem, and have already worked a little bit on it in regard to #10031. I will be ~updating~ entirely rewriting that PR over the next few days, probably based on polar coordinates just as you suggested, which will then also resolve this issue.

**Comment by rubenwardy** [comment]
Fixed in #11262
