### ISSUE TITLE
Server shuts down with error message "AsyncErr: ServerThread::run Lua: Runtime error from mod '??' in callback item_OnPlace()"

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest#10732]
##### Minetest version
```
Minetest 5.4.0-dev-664f5ce96 (Linux)
```

##### Summary
Don't know if it's the fault of the Minceclone2 mod or the engine, but the server shuts down with the following error message if i right-click a Jukebox which currently plays a music disc:
```bash
AsyncErr: ServerThread::run Lua: Runtime error from mod '??' in callback item_OnPlace(): .../../games/MineClone2/mods/ITEMS/mcl_jukebox/init.lua:165: bad argument #1 to 'hud_remove' (number expected, got nil)
stack traceback:
	[C]: in function 'hud_remove'
	.../../games/MineClone2/mods/ITEMS/mcl_jukebox/init.lua:165: in function 'on_rightclick'
	...oo/development/minetest/bin/../builtin/game/item.lua:426: in function <...oo/development/minetest/bin/../builtin/game/item.lua:419>
	(tail call): ?
```
In any case, a faulty mod should never be able to shut down the server by accident.
##### Steps to reproduce

- Install MineClone2
- Right click Jukebox with music disc in hand to insert disc
- Right click again

**Comment by SmallJoker** [comment]
> number expected, got nil

Wrongly used API, uncovered by stricter checks added in 33b2c5.

**Comment by randomMesh** [comment]
I don't get the "Not a bug" label.

Is not crashing the server a feature request now?

**Comment by SmallJoker** [comment]
@randomMesh Just because the mods work does not mean they're written correctly. The correct solution here is to fix MineClone 2 because it relied on kinda undefined behaviour.

**Comment by randomMesh** [comment]
I understand that the culprit is MineClone2, but imho, in light of separating the engine from the content, the engine should sanitize its inputs if performance doesn't suffer.

@Wuzzy2 : You might want to fix this.

**Comment by sfan5** [comment]
Ignoring errors can cause more errors and has the possibility of corrupting the game state even more, so that's not an option.

**Comment by Wuzzy2** [comment]
It is indeed a terrible idea to just make the game chuck along *after* a clear error condition has occured, this is actually much worse because it allows us to accumulate lots of critical bugs without even really noticing them. Critical bugs *must* hurt. That's the point. ;)

So I agree 100% with sfan5 here. It's not that Minetest *itself* is crashing (that would indeed be a problem in Minetest, not MCL2).

That having said, can you please test if MCL2 commit `b0dc0ecc9cbe9aa4bc35a146a82ca37626a54cc2` fixes this?

**Comment by randomMesh** [comment]
Ok guys, thank you for your feedback. I'll close this issue then.

> That having said, can you please test if MCL2 commit `b0dc0ecc9cbe9aa4bc35a146a82ca37626a54cc2` fixes this?

Yes, the error has been fixed. Thank you!
