### ISSUE TITLE
 Crash on Android 10

### ISSUE THREAD

**Issue by M4r5ha11** [minetest/minetest#10749]
https://user-images.githubusercontent.com/68496774/103107018-1ab8bd80-4643-11eb-9d5b-107f582fd929.mp4

All in the video
Device: Huawei P40, Android 10

**Comment by rubenwardy** [comment]
How did you install Minetest?

The version on F-Droid is outdated and doesn't support Android 10. The issue for this is #10529

You should install from Google Play or from [an APK](https://github.com/minetest/minetest/releases/download/5.3.0/app-armeabi-v7a-release.apk) instead

**Comment by M4r5ha11** [comment]
I installed with F-Droid

**Comment by M4r5ha11** [comment]
https://github.com/minetest/minetest/releases/download/5.3.0/app-armeabi-v7a-release.apk
It apk work, I close issue...

**Comment by NSTAdventure** [comment]
> https://github.com/minetest/minetest/releases/download/5.3.0/app-armeabi-v7a-release.apk
> It apk work, I close issue...

how to make outdated version work?
download and instal app cloner
on app clone setting check clone option turn on increase compatibility and clone the minetest
signature may invalid
no guarantee from developer
i test them on latest f-droid.org latest build and version
it work well :)
