### ISSUE TITLE
[Code Style] Increase line length limit

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10740]
The Minetest coding style has a soft line length limit at 80 characters and a hard line length limit at 90 characters. I really hate this.
Guys, we're not in the 1970's anymore. I think it's safe to raise the line length limit to … i don't know, 140 maybe? (feel free to suggest another number)

So many PRs get delayed because some lines are slightly too long. So annoying. -_-
I also think this low line length limit sometimes makes code readability *worse* because it sometimes forces too many linebreaks.

Anyway, note this issue is only a policy suggestion. I do not suggest to touch existing code, but only to reconsider the policy for *future code*.

**Comment by randomMesh** [comment]
> 125 characters per line is the real de facto coding standard for maximum line length these days, because this is the maximum number of characters that you can see in the GitHub diff view.

https://hilton.org.uk/blog/source-code-line-length

**Comment by Wuzzy2** [comment]
Yeah, 125 sounds fine to me, too.

**Comment by v-rob** [comment]
I personally never go above 130ish in my own code, so I would be in favor of 125.  I would also suggest that continuation lines be indented two tabs instead of one since that's a lot more standard, at least in most of the code I've seen.

**Comment by KaylebJay** [comment]
125 seems reasonable.

**Comment by lhofhansl** [comment]
+1 on 125.

**Comment by celeron55** [comment]
This comes to personal preference so I'm going to state my personal preference these days: 95 character soft limit and no hard limit at all. I use a tab width of 4.

I think it's necessary to allow people to have multiple views of the same file or different files side by side and 125 is in my opinion a bit too long for that. With my current screen and font size 115 characters would be the hard maximum for viewing two files side by side.

**Comment by rubenwardy** [comment]
Two tab continuation is also easier to implement in clang format

**Comment by SmallJoker** [comment]
![grafik](https://user-images.githubusercontent.com/1497498/103209574-bbd59b80-4903-11eb-85e9-c6b66e5d5d9f.png)

This is how it looks for me. Each tab is counted as 4 characters, and the tail comment is counted as well. The longest line is too long when working with multiple open windows on the editor's sides.
125 is the absolute maximum I would agree on, where ~110 would be my preference (exception: repetitive lines that need alignment).

**Comment by randomMesh** [comment]
> a line should fit into 95 characters unless there's a reason not to, and then if there's a reason not to, there's no length limit.

I like the idea of no length limit. I mean, there are scrollbars after all. Vi users should upgrade. ;)

**Comment by LoneWolfHT** [comment]
The 70 and 106 char lines look fine to me but not the 131 char line
#
> I like the idea of no length limit. I mean, there are scrollbars after all. Vi users should upgrade. ;)

I avoid creating code that requires me to use the horizontal scrollbars. It makes the code harder to read in any areas where you have a long line. (IIRC I set my editor to just wrap long lines instead)

> A line of code is a statement, an idea, and it should not be artificially demolished (unless it improves readability).

A long line of code (~100+ chars) is almost never a single idea that can't be split up into smaller parts with equal or greater readability

**Comment by andrenete** [comment]
Not a Minetest dev, but my points on shorter lines in C++ and in general:
- encourage code refactoring
- can indicate suboptimal algorithms earlier than long lines, for example in code with many nested levels
- easier to spot an error visually when reviewing
- can be viewed in side by side diffs
- works better for laptops with UI scaling enabled, especially when editor window doesn't take all vertical screen space

80 or 100 are OK.

No length limit is acceptable only for markup languages where there is a lot of text.

On the indentation: tabs to indent, spaces to align.

> So many PRs get delayed because some lines are slightly too long.

I'm sorry, but is that a reason to change the limit? It only means that `clang-format` is doing a good job 😄.

> https://hilton.org.uk/blog/source-code-line-length
> 125 characters per line is the real de facto coding standard for maximum line length these days, because this is the maximum number of characters that you can see in the GitHub diff view.

Not an argument at all. What about side-by-side or non Gihub? Also, the article is mostly about Scala.

Anyway, sorry for intruding on this discussion and feel free to make decisions that you and other MT developers think are right.

**Comment by paramat** [comment]
The '80 soft limit, 90 hard limit, with tab size 4' current documented is actually not what we do.
I agree the documented '80' is impractically short and actually bad for readability.

A year or so ago we discussed this and informally-vaguely-partially-agreed to increase to approx 90-100 soft limit, i have been coding and reviewing to 90 since then.
We actually have no 'absolute hard limit' because occasionally it is absolutely essential to have long lines for code readability.

> I think it's necessary to allow people to have multiple views of the same file or different files side by side and 125 is in my opinion a bit too long for that.

This is important in my opinion, the max on my setup is therefore around 90-100.
So i agree with celeron55's suggestion:

> 95 character soft limit and no hard limit at all.

**Comment by Desour** [comment]
>I would also suggest that continuation lines be indented two tabs instead of one

Isn't the one tab indentation rule just for continuation lines in function declarations?
https://dev.minetest.net/Code_style_guidelines

Btw. it looks like clang-format currently uses 8-sized tabs, which isn't guidelines conform.

Imho what really decreases readability is less the line-length, but more the amount of non-whitespace characters in a line. Therefore, it might make sense not to count the leading tabs to the line-length.
Some maximum column value is still useful of course, for side-by-side view and similar.

Anyway, :+1:  for more softness.

**Comment by v-rob** [comment]
If I have two windows next to each other, this is about the maximum I can make my lines (including the comment):

![image](https://user-images.githubusercontent.com/31123645/103321744-ea30a500-49ef-11eb-8e3b-e1fae829fdb9.png)

I commonly have two windows next to each other, but I also use word wrapping, so I have no problem with a larger line size.

(Funny thing: on IRC, there was a bit of talking about how the "standard" size for tabs is eight spaces, whereas there are also four and two spaces used.  Well, on typewriters, the standard for indentation was _five_ spaces.  I'm not suggesting we use that, but I find it rather funny :) )

**Comment by randomMesh** [comment]
> A long line of code (~100+ chars) is almost never a single idea that can't be split up into smaller parts with equal or greater readability

These are 4 actual lines of code in a project of mine (183 characters including the leading tabulator):
```cpp
glVertexAttribPointer(this->map_shader->getAttributeLocation("vertexPosition"), 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), reinterpret_cast<const void*>(offsetof(Vertex, position)));
glVertexAttribPointer(this->map_shader->getAttributeLocation("vertexNormal"),   3, GL_FLOAT, GL_FALSE, sizeof(Vertex), reinterpret_cast<const void*>(offsetof(Vertex, normal)));
glVertexAttribPointer(this->map_shader->getAttributeLocation("vertexColor"),    4, GL_FLOAT, GL_FALSE, sizeof(Vertex), reinterpret_cast<const void*>(offsetof(Vertex, color)));
glVertexAttribPointer(this->map_shader->getAttributeLocation("vertexTexCoord"), 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), reinterpret_cast<const void*>(offsetof(Vertex, texCoord)));

```
I would never split these up because now they are as readable as it can get. And i neither would write
`m_shader->getAL(vP)` instead of `this->map_shader->getAttributeLocation("vertexPosition")`

Sometimes the code HAS to be long to be readable.

**Comment by LoneWolfHT** [comment]
What that looks like in my editor (And also at least github's diffs)
![image](https://user-images.githubusercontent.com/28972859/103370645-2e6c8580-4a82-11eb-9e6d-6e0411bb0598.png)

**Comment by Zughy** [comment]
So can we all agree about the 95 soft limit, no hard limit and 2 tabs indentation, close this one and edit https://dev.minetest.net/Code_style_guidelines consequently?

**Comment by Wuzzy2** [comment]
ok

**Comment by nerzhul** [comment]
Current we are at 90 chars looking on the clang-format configuration
```
ColumnLimit: 90
```

If we want upper i suggest **100**, it's fine in most case, more is hard on some laptop resolutions i have (but i don't develop much on it currently)
100 is 11.1% more line length that can be fine, if we switch remember that we must clang-format all non ignored files and hop problem solved (yes it can break some MR, anyway rebase is intelligent on git and can understand code reformat)

**Comment by Zughy** [comment]
Done, please close

**Comment by nerzhul** [comment]
@Zughy don't put 95 char on the wiki whereas clang-format check is configured to 90. If we can 95 and majority of coredevs agree we need to upgrade this limit & pass clang-format on non ignored files

**Comment by Zughy** [comment]
Three core devs agree already, Celeron does too, SmallJoker said he's ok around 110, so don't say "if". I did that because waiting for any of you, sometimes, is pure pain. This is something any of you can do without any PR, it's about changing 90 to 100, c'mon

**Comment by SmallJoker** [comment]
Nonetheless, rule changes are done after discussing the topic in a meeting so that
1. it's all going in an ordered manner and
2. everybody is informed about the change

**Comment by Zughy** [comment]
I mean, the only active core devs missing here are sfan5 and Pyrollo (and this one is missing in general, so I don't even know whether considering him active), and I've lurked a couple meetings: there's never all of you. I think that *in this specific case* is an over-complication of the process, considering basically everyone spoke his mind and he's receiving mail notifications about these messages

**Comment by sfan5** [comment]
I have given a :+1: in support of celeron's comment https://github.com/minetest/minetest/issues/10740#issuecomment-751491249

**Comment by Desour** [comment]
Could please be made more clear, where the continuation line indentation rule applies, eg. by moving it out of the **Function declarations** wiki section?

**Comment by numberZero** [comment]
Oh no, I can’t view code wider than 70 columns side-by-side! So please don’t do that, reduce the limit to 70 instead!
![20210121_23h56m17s_grim](https://user-images.githubusercontent.com/7352626/105411696-c5250000-5c44-11eb-9dc5-d9d58209a199.png)

Seriously, if a line is long, probably either the code is bad and there are reasons beyond line length to reject it, or there is a reason for the line to be long. And for people with narrow screens, there is word wrapping (sadly it doesn’t work well everywhere, but we don’t refuse to use tabs due to the fact Phabricator renders them as 2 spaces which makes the code unreadable).

**Comment by sfan5** [comment]
With clang-format being disabled this is pretty much done business.
And for completeness, this is the new rule as written in the guidelines:
> * <b>Try to keep lines under 95 characters.</b> It's okay if it goes over by a few, but do not exaggerate. (Note that this column count assumes 4-space indents.)
