### ISSUE TITLE
Health & breathbar ignore max properties

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10741]
```lua
local health_bar_definition = {
	hud_elem_type = "statbar",
	position = {x = 0.5, y = 1},
	text = "heart.png",
	text2 = "heart_gone.png",
	number = core.PLAYER_MAX_HP_DEFAULT,
	item = core.PLAYER_MAX_HP_DEFAULT,
	direction = 0,
	size = {x = 24, y = 24},
	offset = {x = (-10 * 24) - 25, y = -(48 + 24 + 16)},
}

local breath_bar_definition = {
	hud_elem_type = "statbar",
	position = {x = 0.5, y = 1},
	text = "bubble.png",
	text2 = "bubble_gone.png",
	number = core.PLAYER_MAX_BREATH_DEFAULT,
	item = core.PLAYER_MAX_BREATH_DEFAULT * 2,
	direction = 0,
	size = {x = 24, y = 24},
	offset = {x = 25, y= -(48 + 24 + 16)},
}
```
`number` & `item` should be changed depending on the player properties `hp_max` and `breath_max`.

**Comment by SmallJoker** [comment]
This already happens. 
https://github.com/minetest/minetest/blob/535557cc2e972c555bc5a294b95f2c2974b81eea/builtin/game/statbars.lua#L30-L37

**Comment by appgurueu** [comment]
No it doesn't. Even if it did, the code is incorrect - it shouldn't take the max of the nominal value, as that will break if the hp max value is below that, causing empty hearts to be permanently shown. Please reopen.

**Comment by appgurueu** [comment]
This can be reproduced using the code from #10569 and a TP with grey heart BGs (such as soothing32).

**Comment by appgurueu** [comment]
I think I see the issue now. The given code is used to update just the `number`, but not the `item`.
