### ISSUE TITLE
gcc 8.0 and less doesn't compile MT

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10743]
##### Minetest version
```
5.4.0-dev
```

##### OS / Hardware

Operating system: Linux Manjaro

##### Summary
I was testing Minetest with several gcc versions to investigate a bug, which I installed through the AUR. And it doesn't compile at the very end. I didn't test with gcc 9.0

##### Steps to reproduce
- delete `CMakeFiles` folder, `CMakeCache.txt`, `CMakeDoxyfile.in`, `CMakeDoxygenDefaults.cmake` and `cmake_install.cmake`
- run `export CC=pathotfgccver`
- run `export XCC=pathofg++ver`
- run default cmake and make

It's basically an error with GLIBCXX, and I have no idea if this is because of MT or because I missed something. This is what happens in gcc 6, 7 and 8
```
[100%] Linking CXX executable ../bin/minetest
ld: /usr/lib/gcc/x86_64-pc-linux-gnu/6.5.0/../../../../lib/libspatialindex.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()@GLIBCXX_3.4.26'
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:4429: bin/minetest] Errore 1
make[1]: *** [CMakeFiles/Makefile2:531: src/CMakeFiles/minetest.dir/all] Errore 2
make: *** [Makefile:171: all] Errore 2
```

while gcc 5 adds a few lines before
```
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/../../../../lib/libopenal.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/../../../../lib/libopenal.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/5.5.0/../../../../lib/libopenal.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
```

**Comment by randomMesh** [comment]
According to [this post on Stackoverflow](https://github.com/ddovod/jet-live/issues/6#issuecomment-452748685), there's something wrong with cmake's [FindThreads](https://cmake.org/cmake/help/latest/module/FindThreads.html).

**Comment by sfan5** [comment]
I don't see how this would be MT's fault.

You're linking a program compiled with gcc 5.5/6.5 (and whatever defaults it had at that time) with your system libraries which were likely built by gcc 9 or 10. This doesn't *need* to break, but if it does then that's how it is.

The issue title is also factually incorrect since we have [CI successfully building](https://github.com/minetest/minetest/runs/1582649517#step:4:1) with gcc 6.
