### ISSUE TITLE
Trusted mod apis are not implemented for client side mods

### ISSUE THREAD

**Issue by JustABanana** [minetest/minetest#10755]
## Problem

minetest.request_insecure_environment is nil when trying to access it in a client side mod. It doesn't return nil, it simply is nil. It would be useful if we were able to interact with the os from client side mods. 

My use case is a mumble positional audio mod, which needs to use shared memory for communicating with mumble. I can't require a library to do this.

## Solutions

Implement the trusted mod apis for client mods. It would make sense to only give access to this api for mods explicitly installed by the user for security reasons

## Alternatives

I could implement a wrapper similar to https://github.com/chipgw/minetest-mumble-wrapper/ which would use an external program that would receive the data from my mod for example by reading minetest's stdout but that requires running a separate process which is generally not user friendly, requires a lot more code and doesn't work in every case(for example a mod that needs to read a file on the disk can't use a hack like this)

**Comment by rubenwardy** [comment]
For security reasons, we can't do this. The client side scripting API is intended to be used with scripts sent from the server. Any trusted mods makes the environment less secure

**Comment by JustABanana** [comment]
Sorry for making this into a separate issue, I tried to find a previous discussion about this but couldn't.

Regardless I feel like if https://github.com/minetest/minetest/issues/7041 is implemented and privileged mods run in a separate lua_state with no way to interact with privileged mods this wouldn't be a security issue and I think that if user accepts the risk they should be able to do it.

I understand if you don't want to spare the resources to implement this, but if someone were to make a sufficiently secure implementation would you be willing to accept a PR?
