### ISSUE TITLE
Clients shouldn't be able to choose options such as creative and enabling damage. Games should

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10754]
## Problem
Alternative to #8927 

If I create a game, I expect total control of what the player can and can't do. In no way they should be able to have cheats featured right in the main tab (creative, enable/disable damage). In fact, this is what happens already in servers: admins choose what the players experience is going to be. The same goes for privileges as fly and noclip, with no exception for the option to play online, as Wuzzy stated in the aforementioned issue. I expect to choose whether my game can be played online or not, whether players can go `/giveme something` and such.

Practical example: create a well-structured long RPG. Now watch people enabling creative, get the most powerful weapon in the game at the very beginning and fly around breaking all the quests.

## Solutions
Get rid of those game-breaking freedoms, starting from the main menu. If game creators want people to cheat, they'll develop specific commands/actions in order to do that (e.g. GTA).

Beware: I'm also referring to commands such as `/grantme` and `/giveme`. We all know where they're coming from. Maybe make a mod for MTG and DevTest to avoid breaking any compatibility?

> But they can still cheat modifying the code of the game

When you're on a diet, there is a difference between being supportive without any restraint and shoving every day in your face some sweets

> What if they want to debug something?

Game creators can create some sort of `/debug_game` command, asking players if they're sure yadda yadda. In short: up to game creators

**Comment by Wuzzy2** [comment]
:-1:

This is clearly inferior to #8927. You want to remove the checkboxes entirely, while #8927 wants to give games the option to remove those checkboxes *at their own choice*. Your suggestion makes things worse.

Banning `/grantme` and `/giveme` sounds way too extreme. If you use `/grantme` in singleplayer that can already be considered cheating. And you can only use `/giveme` if you know the itemstring which is usually only possible if you actually looked into the source code. Also, you are breaking the entire privilege system if you ban `/grantme`. You need `/grant` and `/revoke` for admins.

Forcing games to add these commands back manually (which will certainly lead to 1000 incompatible implementations as well) is a recipe for desaster.

Also, you can already circumvent all of that right now. You can force-set any setting, including damage and Creative Mode, at init time (this is a workaround for now, the real solution is to be able to remove the checkboxes). You can also unregister chatcommands. Although I strongly advice against unregistering commands like `/grantme`. `/grantme` is cheat mode anyway.

Finally, I do agree with your basic premise, in that Minetest is making it way too easy to "cheat". I know that players might tend to "optimize" the fun out of the game if you let them, so I totally agree that Minetest should not allow "1-click cheats" (unless the game doesn't care anyway). But I disagree completely with your solution which will just break too many things.
