### ISSUE TITLE
Custom item drops based on tool meta

### ISSUE THREAD

**Issue by Mooncarguy** [minetest/minetest#10759]
## Problem
Currently it is impossible to change the drops ofnodes based on the tool used or it's meta.

## Solutions

core.node_dig should pass the itemstack on to core.get_node_drops

core.get_node_drops should then check the itemstack for a meta string called "droptype". If the droptype isn't nil or an empty string instead of it's normal operation core.get_node_drops should then call a function called get_node_drops_[droptype] and return that value instead. The get_node_drops_[droptype] functions would be defined in the individual mods.

**Comment by rubenwardy** [comment]
Seems better to have a callback for this instead, rather than using meta

**Comment by Mooncarguy** [comment]
Like node_drop_modifier = function (pos, tool, stack)?

**Comment by Mooncarguy** [comment]
I don't think a callback is useful, because then you'd have to register one callback per node, not allowing for things like enchants.

**Comment by Mooncarguy** [comment]
Since MT is apparently on feature freeze and there is actually a way for mods to bypass this I close the issue..

**Comment by rubenwardy** [comment]
Minetest isn't on feature freeze currently. Also, you don't have access to player name or the full tool stack in get node drops, so it's not very helpful to override with
