### ISSUE TITLE
Get rid of variety of custom file formats

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10766]
## Problem

Minetest uses various custom file formats, each with it's own problems:

* `settingtypes.txt`
* `minetest.conf`, `world.mt` (which should be renamed to `world.conf`) with a Python-style multiline extension
* `force_loaded.txt` already uses Lua but isn't named accordingly
* `env_meta.txt` uses a custom text format
* `ipban.txt` is a newline-separated list of IPs, which should be replaced with a DB table
* `map_meta.txt` uses a Lua-ish format

## Solutions

Use Lua (or JSON) where possible, rename files accordingly, deprecate those file formats but continue to support them.

## Additional context

Related: #10085 slaying another custom file format

**Comment by sfan5** [comment]
Getting rid of our config file format is nonsense IMO if you're suggesting that.

> force_loaded.txt already uses Lua but isn't named accordingly

Adding support code _just_ to get the naming right is wasted work.

> env_meta.txt uses a custom text format

No it does not, it's the config file format with a terminating string constant at the end.

> map_meta.txt uses a Lua-ish format

No, same as above.

**Comment by appgurueu** [comment]
> Getting rid of our config file format is nonsense IMO if you're suggesting that.
> 
> > force_loaded.txt already uses Lua but isn't named accordingly
> 
> Adding support code _just_ to get the naming right is wasted work.
> 
> > env_meta.txt uses a custom text format
> 
> No it does not, it's the config file format with a terminating string constant at the end.
> 
> > map_meta.txt uses a Lua-ish format
> 
> No, same as above.

I see. I had completely forgotten the ability of the config file format to store mapgen params, IMO also making it a candidate for removal.

This pretty much only leaves `settingtypes.txt`.

**Comment by DeltaNedas** [comment]
settingtypes.txt is pretty redundant imo, the defaults shouldn't have to be specified on the lua end as well. you shouldn't need to tonumber() either for numbers, a simple minetest.settings:get("my.cool_setting") should return say a number that automatically falls back to its default

**Comment by SmallJoker** [comment]
I think you are missing the point *why* `settingtypes.txt` exists. Its purpose is **to document** the settings behaviour and to categorize them in the Main menu / Settings formspec. The fact that defaults are still contained there is due to the fact that they're yet not generated automatically (IIRC numberZero made a PR a few years ago).

The very same file is also used for translation strings and to generate `minetest.conf.example`, although doing that is currently not user-friendly.

In general, I think it's not worth to change anything in this structure unless there's a real benefit (as in features) for it. The Settings format holds well so far and offers (in opposite to JSON serialization) incremental updates and preserves user-made comments.

**Comment by 0-afflatus** [comment]
Ultimately it would be neater if all files that use config file format are renamed .conf
settingtypes.txt could just become settings.conf
But apart from that, is anything actually broken here?

**Comment by appgurueu** [comment]
> Ultimately it would be neater if all files that use config file format are renamed .conf

Yes! Same for other file types, such as serialized Lua.

> settingtypes.txt could just become settings.conf

Settingtypes don't use the config file format.

> But apart from that, is anything actually broken here?

Nothing is "broken", as this is a feature request and not a bug report.

**Comment by sorcerykid** [comment]
I think there should be a migration path toward Lua replacing the ".conf" file format including minetest.conf, mod.conf, etc. After all, Lua itself began as a configuration language. So it only makes sense to take advantage of the fact the engine already has Lua support builtin. Keeping around a secondary parser just for config files seem redundant at this point.

All of my mods currently use Lua files in conjunction with my Configuration Panel mod for their settings. I've completely abandoned minetest.conf for everything other than engine settings.. Lua allows for a lot more sophisticated data structures, as well as arithmetic operations, variable interpolation, etc. none of which are possible with the ".conf" file format.

Here's an example of the config.lua used by my GiftBox mod:
https://github.com/sorcerykid/giftbox/blob/master/config.lua

This of course, is not a top priority. But it should at least be considered as a long-term goal within the roadmap for Minetest 6.0.

**Comment by appgurueu** [comment]
> All of my mods currently use Lua files in conjunction with my Configuration Panel mod for their settings. I've completely abandoned minetest.conf for everything other than engine settings.. Lua allows for a lot more sophisticated data structures, as well as arithmetic operations, variable interpolation, etc. none of which are possible with the ".conf" file format.

I've done the same with modlib. The main issue I have with the conf file format is that nested structures become really ugly, as well as structures like lists:

```lua
return {a_1 = {b_1 = {c_1 = 1, c_2 = 1}, b_2 = {c_1 = 1, c_2 = 1}, b_3 = {c_1 = 1, c_2 = 1}}, a_2 = 1}
```

is equivalent to

```conf
a_1.b_1.c_1 = 1
a_1.b_1.c_2 = 1
a_1.b_2.c_1 = 1
a_1.b_2.c_2 = 1
a_2 = 1
```

which is a lot uglier. Additionally, lists have to be represented quite dirty:

```
conf = a,b,c
```

is a format commonly used for string lists of e.g. items which may not contain `,`. But what if you want to use table values, or your strings may contain the delimiter? It becomes trickier. One has to do:

```conf
list.1 = first item
list.2 = second item
# ...
```

which isn't exactly beautiful either.

**Comment by appgurueu** [comment]
Please at least close such issues as "Won't fix/add" rather than "Completed".
