### ISSUE TITLE
Fix Irrlicht 1.9 support

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#10763]
## Problem

Minetest does not compile with the latest Irrlicht 1.9-trunk. It contains many fixes and improvements for various platforms.

## Solutions

Since my fork focused on the latest version of Irrlicht 1.9, I have a fix for (probably) all the problems.
I could do a PR if Core Devs are interested in it and nobody else is working on it.

## Alternatives

Irrlicht 1.8 still works for Desktop. Who cares about using the newer version?

**Comment by sfan5** [comment]
see https://github.com/minetest/minetest/issues/10738#issuecomment-751404478 and/or #10729

**Comment by lhofhansl** [comment]
Are there fixes we can do that would have MT work with both Irrlicht 1.9 and 1.8.x? That way 1.8 still works and we'd be "futureproof" for 1.9.

**Comment by TheBrokenRail** [comment]
> Are there fixes we can do that would have MT work with both Irrlicht 1.9 and 1.8.x? That way 1.8 still works and we'd be "futureproof" for 1.9.

That is how my fixes work. I used ``#if``.
