### ISSUE TITLE
MTS is video/MP2T right now

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10767]
##### Minetest version
All version that supports `.mts`

##### OS / Hardware
All

##### Summary
The `.mts` file is `video/MP2T` right now. I suggest using `.mtsh`

**Comment by sfan5** [comment]
This isn't a problem at all.

`.mts` files don't need to be associated with Minetest so that they're openable, so it' doesn't matter that the same extension is already used by something else. Changing the extension only means extra work.

**Comment by MoNTE48** [comment]
Does it make a difference how I name the file with the schema (`myschema.mtsh123`)?
It's just a matter of recommended format name in the documentation, isn't it?

**Comment by v-rob** [comment]
Ever looked at how many applications use the extension `.obj` for different things?  For instance, 3D modelling applications use it as a static model format (and some applications use the same extension for different encodings) while Visual Studio uses it as the object file extension, and many other applications use it for things no one has ever heard of.  Some extensions have the same meaning, like `.zip` and `.pk3`.  So yes, this can lead to misunderstandings, but as long as distributed `.mts` files are associated with Minetest, there should be no problem.

**Comment by nerzhul** [comment]
depends on the mime type exposed. We don't expose one, then extension is used by browsers
