### ISSUE TITLE
Viewrange is not applied to players

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10761]
##### Summary
Players are visible outside of viewrange if fog is disabled. This allows easily determining the locations of other players in PvP servers which is detrimental to gameplay.

##### Steps to reproduce
Join a server with two clients, distance yourself from the other player, decrease your viewrange to minimum, turn off fog.

![Screenshot](https://user-images.githubusercontent.com/34514239/103282334-b9dc0d00-49d5-11eb-918b-f00e1959da9b.png)

Related: #9315 should be merged too for this to have proper impact, as wireframe still allows for a form of X-ray.

**Comment by hecktest** [comment]
Uh oh.
Unfortunately, some form of wallhack will always be possible. One could attempt to fix this by not rendering any object that doesn't belong to a loaded mapblock, but it's trivial to undo such fix on a cheat client. Nothing short of server side culling of objects can truly fix it, and that's another can of worms.

**Comment by appgurueu** [comment]
@SmallJoker this is high-priority for PvP. This "poor man's glitch" allows players to easily determine the locations of other players by reducing viewrange.

**Comment by appgurueu** [comment]
Closing as this is an instance of #8952
