### ISSUE TITLE
Allow determining client window info (possibly just the DPI)

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10762]
## Problem

The Minetest HUD currently offers a screensize relative layout, which can be adjusted using pixel offsets.

This simple layouting works fine for numerous purposes, but also fail for simple things:

- a circular scope spanning the entire screen is not possible (an "ellipsis" scope is, though)
- hardcoded offsets don't work with different textures, using relative sizes is not an option due to unknown screensizes
- hardcoded pixel stuff might be too small on high-DPI displays or too big on low-DPI ones

## Solutions

Allow modders to determine client screen information such as resolution and dpi in order to allow implementation of more complex layouting. Rough proposal: `player:get_window_info(): returns {width = in px, height = in px, dpi = px / inch}`

## Alternatives

#10524 rendering current HUDs pretty useless

**Comment by SmallJoker** [comment]
Closely related #10632

**Comment by sfan5** [comment]
As written in the closely related issue I supporting exposing the DPI (or equivalent measure). https://github.com/minetest/minetest/issues/10632#issuecomment-727211865:
> It'd make sense to expose screen resolution and/or DPI to get_player_information.
> Or better yet, maybe some combination (window size adjusted by DPI?) so modders don't have too many variables they need to work with.

**Comment by sorcerykid** [comment]
This issue is a duplicate of #7658, which was shot down by multiple core devs.

As an alternative, I proposed only exposing screen DPI since at least it is persistent. But there was no further action taken.

https://github.com/minetest/minetest/issues/7658#issuecomment-493558980

**Comment by sfan5** [comment]
I still support exposing the DPI and this is worth discussing as it's not an exact duplicate.

**Comment by sorcerykid** [comment]
This issue aims to provide screen resolution, which is not useful under any circumstance. The other issue aims to provide window canvas size, which has far more utility for modding. Also there's valuable discussion and counter-points already in the other issue, including my proposal of including DPI. So I suggest the other issue, being older, is the one that should be re-opened.

**Comment by appgurueu** [comment]
> This issue aims to provide screen resolution, which is not useful under any circumstance.

Indeed. I was thinking of window size for my use cases, no idea why I was speaking of screen. The size of the entire display of course is useless.

> The other issue aims to provide window canvas size, which has far more utility for modding. Also there's valuable discussion and counter-points already in the other issue, including my proposal of including DPI. So I suggest the other issue, being older, is the one that should be re-opened.

I agree. I did not know of that issue when opening this feature request, but it basically is the same.
