### ISSUE TITLE
Nametag cannot be hidden for players

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#10778]
Caused by #10152

A nil or "" nametag on a player will display the player's name rather than a blank. This has always been the case.
The workaround to hide the player's nametag was to make it whitespace, but the recently added dim background has made the space visible:
![hidenametag](https://user-images.githubusercontent.com/42101236/103527370-86402d80-4e82-11eb-8666-2bfbfb2393cf.png)

We need a reliable way to hide nametags for all entities, including players. Can't be too sneaky with that thing above your head.

**Comment by rubenwardy** [comment]
Set the alpha to zero

**Comment by Zughy** [comment]
^

That's what I've been doing for months on my `arena_lib` mod: https://gitlab.com/zughy-friends-minetest/arena_lib/-/blob/master/api.lua#L2021

**Comment by hecktest** [comment]
Oh, there's an alpha param. But that doesn't turn off the tag itself, right? That's still an extra drawcall to render that quad, and drawcalls are bad. (so is overdraw, even if you write 0 alpha)

**Comment by sfan5** [comment]
Tags with zero alpha are not drawn:
https://github.com/minetest/minetest/blob/dd5a732fa90550066bb96305b64b6648903cc822/src/client/camera.cpp#L699-L704

**Comment by hecktest** [comment]
Cool. Guess that's it then.

**Comment by rubenwardy** [comment]
This should be documented

**Comment by appgurueu** [comment]
TBH that is an issue with Zughy's nametag background PR which is to be trivially addressed. See #5021 - it used to be possible to remove a nametag this way.

**Comment by Zughy** [comment]
Actually this happens on players only, entities work fine with `""`. The PR already has 2 approvals, I suggest to merge it and then investigate this behaviour (which was not implemented by me)

**Comment by appgurueu** [comment]
> Actually this happens on players only, entities work fine with `""`. The PR already has 2 approvals, I suggest to merge it and then investigate this behaviour (which was not implemented by me)

It was certainly introduced by your PR, as the only thing visible is the background, both if setting an empty string or a space-only one.

**Comment by Zughy** [comment]
> It was certainly introduced by your PR

It was not. If the empty background is showed only on players' heads, it means that nametags were already rendered, even if empty, on players' heads. Check the diffs: I only touched the `camera.cpp` code. You can say my PR brought to light an already present issue, but this is *not* something I've implemented
