### ISSUE TITLE
Speeding up formspec parsing.

### ISSUE THREAD

**Issue by loosewheel** [minetest/minetest#10776]
I’ve noticed that formspecs seem to take a while to parse. In a mod I made, measuring time across the call to update the formspec took ~0.9 seconds. Disclaimer: The formspec had a lot of elements and I have a 10 yo laptop.

Although all this time is probably not spent on parsing, I had a look at the code in ‘minetest/src/gui/guiFormSpecMenu.cpp’. I rewrote your code as best I could outside of your environment, to simulate the performance. I also wrote some alternative code to do the same thing to test against. This is the terminal output of the tests:

---
Search for type match tests (GUIFormSpecMenu::parseElement)
 current 4635 msecs
 proposed 1374 msecs
 simpler 1674 msecs

Parsing button element tests (GUIFormSpecMenu::parseButton)
 current 4174 msecs
 proposed 1019 msecs

---

I’ve run the operations 1000s of times in the above to get meaning time values.

The alternative uses a ‘switch’ to effectively do an indexed search for a match, and interprets the given string instead of doing a lot of slicing and dicing.

I’ve posted the code here if you’re interested.
https://pastebin.com/CrBzFyAm

The code in not a drop in replacement but should be obvious how it can be adapted.

Cheers

**Comment by kilbith** [comment]
@v-rob

**Comment by loosewheel** [comment]
Sorry, back again. I had a go at rewriting the split function. This versions runs over 5 times faster than the current.

Terminal output.

---------------------------------
Splitting string tests (split)
 current 1977 msecs
 proposed 351 msecs
 split and trim 368 msecs

---------------------------------

The code is here https://pastebin.com/1xuEJP3L

There are 2 versions, split_new and split_and_trim.  The split_new is compatible with the current. The split_and_trim might be more suitable for parsing formspecs. It trims the white space before the line and omits out of place closing brackets and empty lines. I don’t know how extensively split is used throughout as to which one is more suitable.

Also I made an error in the top post. It’s taking ~0.09 secs, not 0.9. It made it seem worse than it actually is.

*I’ve run these functions 1000 to 1000000 times to get the times in these tests. The split functions are processing ~123MB. The form I’m using has 1991 elements. To process this form once this is still only saving milliseconds. The slowdown must be somewhere else.

**Comment by v-rob** [comment]
Formspec parsing definitely isn't optimized for speed, that's for sure.  Someone made a raycaster with thousands of formspec `box[]` elements, and it took a few seconds each frame to render (which a substantial part of might have been parsing).  I've never had a problem with it myself, but maybe I haven't made big enough formspecs.

I wonder if these switch statements or a hash map lookup would be faster.  In earlier refactors, I attempted something like the following, but never actually tested it out:
```c++
std::unordered_map<std::string, GUIFormSpecMenu::*(const std::string &name, const std::string &element)> parsers = {
    {"container", &GUIFormSpecMenu::parseContainer},
    {"container_end", &GUIFormSpecMenu::parseContainerEnd},
    {"button", &GUIFormSpecMenu::parseButton},
    /* etc */
};

auto it = parsers.find(name);
if (it != parsers.end())
    this->*(it->second)(name, element)
else
    errorstream << "Unknown element \" << name << "\"" << std::endl;
```

I don't know which would be faster.  Hash maps are O(1) if there are no conflicts, which there probably aren't with as few elements as we have.  Then again, switch statements are blazingly fast.  It warrants some testing, although hash maps are definitely cleaner.

Another way things might be sped up is by not using as many `std::vector<std::string>`s all over the place (which usually happens through the `split` function).  They're used for nearly everything, and it's not necessary at all for many things.  Constant heap allocation could be slowing things down, and the `split` function itself could be slow as well.  Things might be faster and cleaner if we used a better version of `scanf` since that would remove essentially all intermediate strings and vectors.

**Comment by kilbith** [comment]
> Someone made a raycaster with thousands of formspec `box[]` elements

That was me: https://github.com/minetest-mods/raycast

**Comment by loosewheel** [comment]
Hi v-rob,

It’s been about 10 years since I played with C++, I’m not so familiar with these class templates.

These classes are made to be used generically, and for that they’re good. They make the coding a lot easier, but at the expense of maybe not being the best at performance. The example above would likely (in compiled code) be the same as the current parseElement. A lot of if (str == str). With possibly some overhead for the iteration.

Strings are processor intensive, much more than processing integral types. It’s probably best to do the processing work at the byte level. Dealing with the strings as byte data rather than as strings or classes.

The major speed up in the parseElement was the use of the switch. A switch deals in integral types, moving the test value into a register and then jumping to the first case and comparing it. If it doesn’t match it jumps to the next and compares it. An if (str == str) calls the classes == operator function, which probably calls compare, which probably calls strcmp. Even though strcmp should return at the first miss-match, all the function calling and string walking results in a lot of processor instructions. Much more than the couple produced by the switch. And the switch then narrows the search possibilities down to about 5%.

To get the best performance it’s probably best to drop down to C and do the byte crunching, or write your own very specific classes. Doing only what you need and no more.

Agree with the constant heap allocations. The major speed improvements were from reading the given string rather than forming lots of littler strings to process them.

Sorry I’m not familiar with the rest of the process, constructing and operating the form elements.

**Comment by loosewheel** [comment]
I gave the unordered map a try.

Terminal output.

----
Search for type match tests (GUIFormSpecMenu::parseElement)
 current 4574 msecs
 proposed 1228 msecs
 simpler 1569 msecs
 map 2443 msecs

-----

**Comment by hecktest** [comment]
Things to try:
- Don't copy any strings, use range slices (`substr` performs a copy!)
- Make sure the string comparer works with entire registers, not individual bytes

**Comment by loosewheel** [comment]
I wrote a class that does as v-rob suggested. A table of { “type name”, parseFunc } is used to parse the elements of the formspec with a single call to GUIFormSpecParser::parseFormSpec. This should give an ~70% increase in performance.

The .h file is here https://pastebin.com/QMYAwaKa
The .cpp file is here https://pastebin.com/czDxJaUC
Examples of individual element parsing function are here https://pastebin.com/0W2n66Xb

But this is not a drop in, much of the parsing code would need to be re-coded to accommodate.

**Comment by loosewheel** [comment]
I downloaded the source and had a little play around. The example form I'm using was parsing at the C++ end well under 1 millisecond. Improving this code wouldn't have any real effect. The slow down was at the lua end. Improving the string handling at that end made a much bigger difference. Sorry for wasting your time.
