### ISSUE TITLE
Bug: Auto enable of dependencies in Select Mods menu is broken

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10785]
## Problem

I can see mods' depending on when I click on it.

But there may be a lot of mods that make me forget to enable some depends.

## Solutions

Auto enable mods' depending on when the user enable it at the world settings

**Comment by HybridDog** [comment]
Mods should already be enabled automatically. #3473

**Comment by rubenwardy** [comment]
I can reproduce this

**Comment by erisMT** [comment]
> Mods' dependencies should already be enabled automatically. #3473
Hard dependencies aren't enabled automatically now.

The problem persists in current master for me. Please re- open.

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/commits/master/builtin/mainmenu/pkgmgr.lua

I fixed this in 7c321ad7f52eeefcd249f4268a2bf18ec12058cd and rubenwardy broke it again in 128f6359e936bcdc5e26409ddd73438bce9c6dd6. :anger:

**Comment by Emojigit** [comment]
:anger:

**Comment by erlehmann** [comment]
> I fixed this in [7c321ad](https://github.com/minetest/minetest/commit/7c321ad7f52eeefcd249f4268a2bf18ec12058cd) and @rubenwardy broke it again in [128f635](https://github.com/minetest/minetest/commit/128f6359e936bcdc5e26409ddd73438bce9c6dd6). anger

… which you approved yourself though. :laughing:
