### ISSUE TITLE
DISCUSS: Store a "protocol" version with each map

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#10784]
Clients already send the protocol version they understand.

We should allow the same for maps.
A simple way is store the protocol version at the time the map is created in map_meta.
After that we would read and write from and to the map with this particular version.

Upgrades are still possible, in addition to what we do now we would also change the protocol version store in map_meta.

Thoughts?

**Comment by sfan5** [comment]
The network protocol has nothing to do with the map format or any other data at rest.
Whether it's the protocol version or a different one I don't really see the need for doing this. What reason would there be for users not to upgrade?
Also consider that we do have a per-mapblock version already (which "auto-upgrades" when written by a newer MT version), nobody has ever complained about that.

For the usecase of zlib vs. zstd a setting in map_meta.txt could be added if necessary. However this potentially also introduces weird error cases where the setting value in the meta doesn't reflect what's actually inside the mapblocks.
In the end I'm wondering why do users need this choice at all?

**Comment by lhofhansl** [comment]
I realize the network protocol version is independent from the map format. I just used the term to illustrate the point.

Hmm... My aim was to allow newer servers to write an old map, while not preventing old server from reading the map. Maybe there is indeed no point.

**Comment by lhofhansl** [comment]
Lemme close this.
