### ISSUE TITLE
Minetest Crash On Android Q

### ISSUE THREAD

**Issue by NSTAdventure** [minetest/minetest#10790]
##### Minetest version

```
5.2.0.26
```

##### OS / Hardware

Operating system: Realme 5i
CPU: QualCom Snapdragon 666

GPU model:
OpenGL version:

##### Summary
App Instantly Crash When i Tried To Open It

##### Steps to reproduce

 Download And Instal This Game From F-droid.org
Launch It And They Crash

**Comment by sfan5** [comment]
See https://github.com/minetest/minetest/issues/10749#issuecomment-751128636:

> The version on F-Droid is outdated and doesn't support Android 10. The issue for this is #10529
> 
> You should install from Google Play or from [an APK](https://github.com/minetest/minetest/releases/download/5.3.0/app-armeabi-v7a-release.apk) instead

**Comment by NSTAdventure** [comment]
well that's is very unfortunate :-(

Pada tanggal Min, 10 Jan 2021 pukul 08.39 sfan5 <notifications@github.com>
menulis:
