### ISSUE TITLE
Create new world map preview/overview

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#108]
When the player hits the 'New' button to create a new world, it would be beneficial for the game to display some kind of small, false-color image derived from the currently-generated seed, so that the user can see generally what the map will look like (at least if seen from overhead).  An option should definitely be included to generate a new seed and map before the user commits to creating the world.

The seed being used should also be displayed, and options to change it (including putting in a new one directly) should be provided.

This way a user can decide if a given seed produces a world they want to play, without mucking about with the game's world configuration files.

**Comment by paramat** [comment]
Theoretically a cool idea but difficult, complex and not much needed. I certainly wouldn't want to work on it or see it as worth the effort, i doubt hmmmm would either, but it would need someone who understands the use of noise. So forgive me closing this as it is an old issue.
