### ISSUE TITLE
Shift-clicking reports the wrong number of items to callbacks

### ISSUE THREAD

**Issue by OgelGames** [minetest/minetest#10805]
##### Minetest version
```
5.3.0 and 5.4.0-dev-4b0128282 (and older versions too AFAIK)
```

##### OS / Hardware
Operating system: Windows 10 64-bit
CPU: Intel Core 2 Duo

##### Summary
When shift-clicking items to or from a node inventory, the total number of items reported to the `allow/on_metadata_inventory_put/take` callbacks doesn't match the actual number of items put or taken.

For example, if you have a stack of 90 items in a chest, and 50 in your inventory, and shift-click the items from the chest, the callbacks are called as follows:
```
allow_metadata_inventory_take - 90 items
on_metadata_inventory_take - 90 items
allow_metadata_inventory_take - 41 items
on_metadata_inventory_take - 41 items
```
Which totals 131 items taken, not the 90 that was actually taken.

##### Steps to reproduce
* Create a mod with this code, and place the node into the world:
```lua
minetest.register_node("test:inventory", {
	description = "Inventory tester",
	tiles = {"default_gold_block.png"},
	groups = {oddly_breakable_by_hand = 1},
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		meta:set_string("formspec", "size[8,9]list[context;main;0,0;8,4;]list[current_player;main;0,5;8,4;]listring[]")
		meta:get_inventory():set_size("main", 32)
	end,
	allow_metadata_inventory_put = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Allow put: "..stack:get_count())
		return stack:get_count()
	end,
	allow_metadata_inventory_take = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Allow take: "..stack:get_count())
		return stack:get_count()
	end,
	on_metadata_inventory_put = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Put: "..stack:get_count())
	end,
	on_metadata_inventory_take = function(pos, listname, index, stack, player)
		minetest.chat_send_all("Take: "..stack:get_count())
	end,
})
```
* Put a full stack of items into the node's inventory, and a partial stack of items in your own inventory.
* Shift-click the items from the node into your inventory.
* The total number of taken items reported will not equal the number actually taken.

**Note:** not a duplicate of #7239

**Comment by SmallJoker** [comment]
Before #9923 some callbacks were not executed at all. This report is strange because I remember testing this exact case in the PR.

**Comment by SmallJoker** [comment]
@appgurueu
Can reproduce. This happens **only** when the shift-clicked stack does not fit on a partial stack, i.e. when the moved stack is split.

Modified code, variants of: `print("Allow put: "..stack:to_string())`
Example when moving from player inventory to node inventory:
```
Allow put: default:chest_locked 10 <-- Middle mouse click
Put: default:chest_locked 10
Allow put: default:chest_locked 99 <-- Shift-click stack of 99, should be 89
Put: default:chest_locked 99
Allow put: default:chest_locked 65457 <-- 78, but 16-bit underflow, should be 10
Put: default:chest_locked 10
```

Your example, moving from node inventory to player inventory:
```
Allow take: default:chest_locked 10 <-- Middle mouse click
Take: default:chest_locked 10
Allow take: default:chest_locked 99 <-- Shift-click stack of 99, should be 89
Take: default:chest_locked 99
Allow take: default:chest_locked 10 <-- OK
Take: default:chest_locked 10
```
