### ISSUE TITLE
Allow HTML5 GUI design

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10804]
## Problem

The formspec language is hard to learn.

## Solutions

Allow using HTML5 to do formspec-like GUI, also allow inline SVG ( https://github.com/minetest/minetest/issues/10770 )

There should add extra HTML tags to support the minetest GUI display

**Comment by rubenwardy** [comment]
#6527

**Comment by numberZero** [comment]
WTF?????????????????????????????????? Maybe just port MT to Electron? That wouldn’t be any harder.
