### ISSUE TITLE
[Android 10] unable to join new servers because of retype password form

### ISSUE THREAD

**Issue by TEbinger** [minetest/minetest#10807]
On Android 10 the "retype password" form does not accept inputs so You can't connect to new servers. 
My phone is a Galaxy S9.

**Comment by SmallJoker** [comment]
Which Minetest version? Does it occur in [5.3.0 (or newest stable)](https://github.com/minetest/minetest/releases) ?

**Comment by TEbinger** [comment]
Thank you, this should come very soon
