### ISSUE TITLE
Minetest Launcher

### ISSUE THREAD

**Issue by Zander200-glitch** [minetest/minetest#10817]
I think there should be something like a minetest launcher to launch older versions of the game ditectly by for example by clicking "new installation" ant then the launcher live-downloads it from minetest.net. Just like minecraft has a launcher too.

I made a beta-launcher in Java that the Minetest Launcher could be based off of.

Comment your opinion please.

My beta-launcher in java: https://github.com/Zander200-glitch/ExtendedLauncher/

**Comment by rubenwardy** [comment]
Thanks for the suggestion, but we've already decided not to add a launcher

Duplicate of #7102 #4917

**Comment by Zander200-glitch** [comment]
I'll keep updating it anyway. I'll use it for my own stuff
