### ISSUE TITLE
Let's make our docs compatible with github pages

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#10821]
## Problem
I'd like to use the github pages feature to easily browse the docs.

## Solutions
* Rename the `doc` folder to `docs`.
* In there, rename those `*.txt` that are markdown-formatted to `*.md`.
* Verify that mkdocs recognizes the markdown files, maybe configure it so it does.

## Alternatives
Solutions that will work for my repo copy only. (Would be ok with me.)

## Additional context
We should refactor `doc/mkdocs/build.sh` some time, it's full of pitfalls.

**Comment by randomMesh** [comment]
Won't happen, see #1919

**Comment by mk-pmb** [comment]
Thanks for the pointer. I'd close this issue, but the GitHub website currently fails to do so.

**Comment by rubenwardy** [comment]
See https://minetest.gitlab.io/minetest
