### ISSUE TITLE
In my LUA CSM, os.getenv == nil

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#10822]
##### Minetest version

```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware

Operating system: Ubuntu focal 64bit
CPU: x86_64

##### Summary

`os.getenv == nil` in my client-side LUA mod.

It needs to figure out where to save chatlogs.
Ideally I'd have some API to query the `$user_path` (so my mod will auto-adapt if MineTest changes its paths), but for now I'm ok with assuming current defaults and supporting Linux only.
Nevertheless, `os.getenv` could be useful for many other things.

##### Steps to reproduce

My `init.lua` is `error('os.getenv type: ' .. type(os.getenv))` and the error message is "os.getenv type: nil".

**Comment by rubenwardy** [comment]
CSM runs in a strict sandbox, protecting the client computer from any scripts. You're not allowed to save files are access any OS things like environment variables

You can persist data on the client using mod storage or by logging to debug.txt

**Comment by mk-pmb** [comment]
Is there another way to easily wire up accessibility tools? Easy as in, not having to continuously maintain a modified codebase. Should I try to hook the relevant functions with `LD_PRELOAD`? (Hoping that their API won't change too often.)

**Comment by mk-pmb** [comment]
Or maybe could we introduce some trusted mode for CSM?

**Comment by rubenwardy** [comment]
> Is there another way to easily wire up accessibility tools? Easy as in, not having to continuously maintain a modified codebase. Should I try to hook the relevant functions with LD_PRELOAD? (Hoping that their API won't change too often.)

What do you mean by accessibility tools? Client-side mod storage is written using JSON, so you can read this externally fairly easily to get the chat logs.

LD_PRELOAD won't effect how the client-side Lua API behaves, unless you can use that to modify the C++ somehow (I don't have any experience doing this)

> Or maybe could we introduce some trusted mode for CSM?

Unfortunately, adding trusted mods completely compromises the sandbox which is why that feature doesn't exist in the client environment.

What could be done is a separate state for trusted client mods, but generally the consensus is that client-provided client-side mods aren't an intended feature - the main intention behind CSM is to allow servers greater ability to change client behaviour such as rendering or prediction.

**Comment by mk-pmb** [comment]
Maybe my approach with CSM is the wrong one then.
Basically I'd like to remote-control everything that has to do with text input/output, later formspecs also. I'd like to make an adapter where external programs can hook in to connect arbitrary alternative I/O devices.
I could probably abuse debug.txt for that, but it seems ugly to write bytes to disk first, when actually I want them in a pipe or a unix domain socket.
For the input part I currently use xinput keyboard emulation, but I was planning to try and interface chat separately later, so I wouldn't need to detect whether MineTest is in chat mode or normal game input mode.

LD_PRELOAD was my next straw in case the CSM approach turns out futile. I'd find the C++ functions that receive the texts to be displayed, and wrap them with a function that logs their arguments to a file descriptor. (The program that launches MineTest would be responsible for opening that FD.)

I'm open for any ideas of approach, however it would be nice if they could be plugged into the official MineTest releases for Ubuntu via a somewhat-stable API.

**Comment by mk-pmb** [comment]
Sorry for the confusing turn from

> It needs to figure out where to save chatlogs.

to

> it seems ugly to write bytes to disk first

. In my struggle to learn CSM, as a first step I tried to write chatlogs to a separate directory on a small tmpfs, with another logfile each hour or even minute, so they wouldn't grow too large. It looked rather easy in [the mod-chatlog mod](https://github.com/AntumMT/mod-chatlog/blob/master/init.lua), unfortunately then I learned that CSM are totally another beast.

**Comment by mk-pmb** [comment]
I discivered this is a dupe of [this forum discussiion from 2019](https://forum.minetest.net/viewtopic.php?f=53&t=23668). I had the same hopes. that MineTest would allow all kinds of interfaces.
