### ISSUE TITLE
Use bitsets for ABM

### ISSUE THREAD

**Issue by xyzz** [minetest/minetest#1082]
According to my profiler ABM handling was taking too long. This set of patches improves the situation by using bitset instead of std::map for required_neighbors.
https://github.com/freeminer/freeminer/commit/b1a64f466226dd8c2086fd2b0358661543ec9080
https://github.com/freeminer/freeminer/commit/e226c9f6d4ae9efdd77a93858737bb3ece07f54e

The following patch gets rid of `std::map` for `m_aabms`
https://github.com/freeminer/freeminer/commit/7ae8f655b2ef3e8db58aab094fd079b1b82915e5

**Comment by paramat** [comment]
@est31 is this useful for your ideas on improving ABMs?

**Comment by nerzhul** [comment]
We now use a vector instead of a map, which fixes this issue.
