### ISSUE TITLE
When server have a segfault, the client receive no quit message then time out

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#10826]
##### Minetest version
 - Client: Any
 - Server: Unknown, `linux-forks.de:30000`

##### OS / Hardware
 - Client: Any
 - Server: Unknown, `linux-forks.de:30000`

##### Summary
Sometimes I time out without any server response, then I see everyone quit. The server admin told me that was a segfault.

##### Steps to reproduce
No. Or try to make your server have a segfault.

##### More Info
 - Tested on clients:
    - 5.3.0 Windows
    - 5.4.0-dev Linux

**Comment by SmallJoker** [comment]
Segfaults are handled by the OS which then results in a forced termination of the process. This is not an exception where `try {} catch {}` can be used to capture it.

Report the segfaults so they can be fixed.
