### ISSUE TITLE
Allow to configure file descriptors for interacting with CSMs.

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#10823]
## Problem
I'd like to efficiently inter-process communicate with my user-provided client-side mod.
(ref: my chatlog attempt in #10822, someone else's [old forum thread](https://forum.minetest.net/viewtopic.php?f=53&t=23668))

## Solutions
Let's add a CLI option that declare that certain file desrciptors inherited from the parent process are meant to be used for communicating with a certain CSM.

How about `--csm-io-fd <mod_name>:<fd_list>`? `<fd_list>` would be a colon-separated list of non-negative integers in decimal. To make bash scripting easier, we'd just ignore empty strings between the colons (see example).

The CSM would then have an API like `minetest.get_csm_io_fd(i, mode)` which would give a LUA file for the i-th FD in the list, and `get_csm_io_fd(nil, '#')` would give the number of FDs provided to the CSM.

Example: `minetest --csm-io-fd chat_aux_input:15 --csm-io-fd chat_tts:::17::16: --csm-io-fd not_today::::`

CSM `chat_aux_input` would then
`minetest.get_csm_io_fd(1, 'r')` to get a readable LUA file for FD 15,
and CSM `chat_tts` would
`minetest.get_csm_io_fd(1, 'w')` for a writable LUA file for FD 17, and 
`minetest.get_csm_io_fd(2, 'a')` for an appendable LUA file for FD 16.
The OS will probably treat modes `w` and `a` the same for already-open FDs, but our code shouldn't care about that.

CSM `not_today` would not receive access to any FDs. Early in its initialization code, it will discover that `get_csm_io_fd(nil, '#') == 0` and will thus do nothing except maybe write a log message "Successfully loaded but nothing to do." Same for CSM `some_other` because it wasn't listed at all.

Some day in the future we might add a special `mode` that accept()s a new connection (the file on FD would need to be a socket) and provides an r/w LUA file or a pair of LUA files. However, for now, let's reap the (hopefully) low-hanging fruit.

## Alternatives

For CSM output:

* Reading back the logfile from disk.
  * Now that I discovered `debug_log_size_max`, this might actually be a good stopgap.
  * Wastes machine power on throwing away all the noise.
  * Requires extra code to detect logfile renaming.
* Capture stdout/stderr. This seems to be what mumble currently resorts to.
  * Not easily chainable: The capturing programs need to cooperate in setting up the pipes, and if anyone gets their IO buffering wrong, the pipes clog.

For CSM input:

* Send chat commands via keyboard emulation.
  * Hope that there are no race conditions with other CSM (or a human!) trying to type at the same time.
  * Use screen capture to detect whether the chat console is open, open it if necessary. Check whether the attempt to open chat succeeded (not available in all game states) and maybe retry later.

**Comment by appgurueu** [comment]
I would rather prefer a setting `secure.trusted_csms` or the like for allowing CSMs access to insecure functions like `require`, which allows use of libraries like `luasocket`.

**Comment by hecktest** [comment]
Whitelists are a bother to maintain though. Why not ask for individual permissions like phone apps do?

**Comment by mk-pmb** [comment]
@appgurueu Whitelisting a CSM for arbitrary socket operations is an entirely different approach, so I'd prefer you open a new issue for that idea. "All or nothing" security permissions on a per-program basis have a long history of problems.
