### ISSUE TITLE
Texture pack extension

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#10829]
## Problem

Texture pack needs to be extended
Ex. I don't like the default textures of a game, so, I look for a cool texture pack.
Then, I decide to create a mod for this game, but how to make my mod have textures according to the style of the cool texture pack?

- I create my mod for a specific texture pack (ugly! and how to share it?)
- I fork the texture pack to add my textures (and if I want to install another mod who have also a fork of the texture pack?)
- I contact the texture pack creator and ask him to add my texture (and if my mod add thousand textures? This will have a big impact on the size of the texture pack. The texture pack creator can also refuse to include my textures.)

## Solutions
Create texture pack extension:

- Extend a texture pack by adding more textures => can textures override the main texturepack? or only add new one?
- Shown in the content tab like mods in a modpack, but under the main texture pack
- Add a field called `depend` to `texturepack.conf`

## Additional context

Sorry for my english, I am not a native speaker.

**Comment by AFCMS** [comment]
No reactions ????!

**Comment by 0-afflatus** [comment]
No, you will not get any.
Texture packs are really easy to create.
You haven't explained well and it _sounds_like_ you don't understand how the game works.
I can usually work out what L2 English speakers are trying to say, I have a lot of experience in rendering documentation written by L2 speakers into idiomatic English. This really doesn't make sense and honestly sounds like you are confused.
I don't mean to be harsh, but this is probably why no-one has reacted or even closed this fr yet.

**Comment by SmallJoker** [comment]
The user has the final word about which textures they want to see. It's not the idea to force a texture on them.

1. Add textures to your mod that fit to the theme of the game (no texture pack enabled)
2. Add textures to your texture pack that fit to the theme of your texture pack
3. Let the users decide whether they want to use your texture pack

**Comment by AFCMS** [comment]
>     2. Add textures to your texture pack that fit to the theme of your texture pack

It seems you don't understand that the texture pack is not mine, so I can't easily add textures to it.

**Comment by AFCMS** [comment]
> 
> 
> No, you will not get any.
> Texture packs are really easy to create.
> You haven't explained well and it _sounds_like_ you don't understand how the game works.
> I can usually work out what L2 English speakers are trying to say, I have a lot of experience in rendering documentation written by L2 speakers into idiomatic English. This really doesn't make sense and honestly sounds like you are confused.
> I don't mean to be harsh, but this is probably why no-one has reacted or even closed this fr yet.

Sadly, I am not a good speaker :(

**Comment by An0n3m0us** [comment]
. . . enabling multiple texture packs over each other?
So like, one can enable two texture packs?
And there are texturepack dependencies on other texturepacks?

It's a bit hard to understand, so why not try explaining it in your first language?
Google translate tends to work very well, so the devs can translate the text to English and get a possibly better idea of what you mean.

**Comment by AFCMS** [comment]
@An0n3m0us 
French:
_Quand on crée un mod pour un jeu spécifique, on doit accorder les textures de son mod avec le jeu.
Mais si on n'aime pas les textures d'origine du jeu, la seule solution est d'utiliser un pack de textures.
Le problème est que les pack de textures existants ne supportent généralement que peu de mods, et uniquement des mods simples ou très utilisés. Si votre mod est trop gros/spécifique, jamais l'auteur du pack de textures ne le supportera.
Je pense que la solution est de permettre aux packs de textures d'avoir des dépendances, ou alors de pouvoir en activer plusieurs à la fois._

**Comment by An0n3m0us** [comment]
Oh, I think I fully understand now. The texture style of ones mod has to match the texture style of the games own textures.
Like if we were to put default_stone in Minecraft; it would look odd (stand out) xD

>  Le problème est que les pack de textures existants ne supportent généralement que peu de mods, et uniquement des mods simples ou très utilisés. Si votre mod est trop gros/spécifique, jamais l'auteur du pack de textures ne le supportera.

Yeah, that makes sense. Your explanation does the job, but I'll expand just a little;
So, (let's just say) you made a mod with textures that follows the style of a (custom) texture pack in Minetest.
And with default Minetest textures, it wouldn't match.

>  Je pense que la solution est de permettre aux packs de textures d'avoir des dépendances, ou alors de pouvoir en activer plusieurs à la fois.

Hmm, I think . . . dependencies on other texture packs?
I personally much prefer the latter idea, like I mentioned in my previous comment.

It would be good to be able to add 'soft dependency' for texture pack(s) so that the player knows which texture pack(s) to enable to make it match the style of the textures in mods.

**Comment by 0-afflatus** [comment]
D'accord, je comprends un peu mieux maintenants
I have spent a lot of time designing custom textures to make obscure mods fit in with my theme.
Many players don't care about mismatching textures, so I'm not sure any kind of dependency is the way to solve this.
I have seen so many huge texture packs (VanessaE's for example) that try to cover all bases, which also seems sub-optimal.
It's a legitimate concern, but it is hard to imagine a simple way to resolve the issue.

**Comment by mk-pmb** [comment]
I think Minecraft sets a good example here, albeit I'm sure this method was invented long before:

* Have a list of installed resource packs, ordered by name. Then to the side, a prioritized list of enabled resource packs.
* Optional: In the installed list, show the priority number, so users can easily see while browsing that list, which RPs are enabled. (I think MC instead hides them.)
* Whenever the game looks up a resource (texture, image, sound, …) the first RP that has a match, wins.

**Comment by Zughy** [comment]
It seems to me that (after having translated the French message) #11786 proposes the same thing and with a better rationale. I'm gonna keep that open, closing here
