### ISSUE TITLE
Untangle basic packet operations from irrlicht

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#10827]
## Problem

I'm trying to make a packet crafting and parsing utility, for which I'd like to utilize `src/network/networkpacket.h`, but I'd like to avoid Irrlicht as a dependency.

```text
In file included from ../3rd-party/minetest_src/util/pointer.h:22,
                 from ../3rd-party/minetest_src/network/networkpacket.h:22,
                 from dump_packet.cpp:23:
../3rd-party/minetest_src/irrlichttypes.h:33:10: fatal error: irrTypes.h: No such file or directory
   33 | #include <irrTypes.h>
      |          ^~~~~~~~~~~~
compilation terminated.
```

## Solutions

Let's try and factor out a base class of the NetworkPacket that provides the operations for basic data types and has very few dependencies.

## Alternatives

Doing crazy pointer vodoo on the packet pointer, guessing the location of `m_data` based on assumptions about its effective data structure.

## Additional context

I'd be willing to try, shall I? However, it seems that lots of our utility libs share that dependency on irrlicht:

```text
util/container.h        :22    #include "irrlichttypes.h"
util/directiontables.h  :22    #include "irrlichttypes.h"
util/ieee_float.h       :22    #include "irrlichttypes.h"
util/numeric.h          :23    #include "irrlichttypes.h"
util/pointedthing.h     :22    #include "irrlichttypes.h"
util/pointer.h          :22    #include "irrlichttypes.h"
util/serialize.cpp      :25    #include "irrlichttypes.h"
util/thread.h           :22    #include "irrlichttypes.h"
util/timetaker.h        :22    #include "irrlichttypes.h"
```

… so I'm not sure how much impact it will have on the codebase. Still I think it's a good idea to try and separate the network protocol stuff from the game engine, to the extent it's possible.

**Comment by sfan5** [comment]
Irrlicht is needed as a *build time* dependency by the server since it provides number types and vector maths.
The former are easy to replace, the latter aren't which means for us there is no tangible advantage to replacing the number types with an internal header.

**Comment by Oblomov** [comment]
Would it be possible / make sense to replace those bits with something like the Eigen library? (I'm not sure how optimized the irrlicht vector math is, but Eigen is _very_ optimized, and will make use of hardware vector instructions whenever possible.)

**Comment by rubenwardy** [comment]
> I'm trying to make a packet crafting and parsing utility, for which I'd like to utilize src/network/networkpacket.h, but I'd like to avoid Irrlicht as a dependency.

It shouldn't be too hard to provide your own fake implementation of the types required

**Comment by mk-pmb** [comment]
> Irrlicht is needed as a build time dependency by the server since it provides number types and vector maths.

I see. So all the vector read/write functions would need to be split out, too.

> It shouldn't be too hard to provide your own fake implementation of the types required

Indeed, it's easy as a one-off action. For maintenance however, it would be easier if I could build with sources from this repository.

**Comment by rubenwardy** [comment]
You can build with the sources from this repository. You just provide your own irrlichttypes.h

**Comment by mk-pmb** [comment]
> You can build with the sources from this repository. You just provide your own irrlichttypes.h

That's a neat idea. Thanks!

**Comment by randomMesh** [comment]
> I'm not sure how optimized the irrlicht vector math is, but Eigen is _very_ optimized

According to [this thread](http://irrlicht.sourceforge.net/forum/viewtopic.php?f=7&t=50237) Irrlichts (fast) math is terrible. I am all for replacing the vector math with [Eigen](https://gitlab.com/libeigen/eigen) or [GLM](https://github.com/g-truc/glm).

I really like GLM, i use it for all my projects.

**Comment by mk-pmb** [comment]
Seeing that there are different preferences, it might make sense to put the vector math API on top of a native basic data types API, so forked projects can more easily git rebase.

**Comment by sfan5** [comment]
> According to this thread Irrlichts (fast) math is terrible.

We don't define `IRRLICHT_FAST_MATH` and I'm not aware of any other configuration where Irrlicht itself is built with it.
gcc hopefully does a good job with -O3.

There *are* some issues I'm aware of (and probably more if I take a closer look) but if we're forking Irrlicht anyway I think it'd be easier to fix these ourselves.

**Comment by Oblomov** [comment]
The main objective of the switch to Eigen (or GLM) would be to completely decouple the server from the irrlicht dependency. Improved speed and accuracy would be a bonus. Forking Irrlicht doesn't really solve that (although the forked irrlicht could forego its own vector math and use the aforementioned Eigne or GLM instead, thus solving the issue).

**Comment by SmallJoker** [comment]
Write your own header to fix the holes caused by removing the Irrlicht dependency. The typedefs are helpful and are unlikely to change until the framework is replaced (unlikely to happen).

What's the actual issue? I don't see anything to change in Minetest.

**Comment by mk-pmb** [comment]
Meanwhile the original issue has evaporated. I had wrong assumptions about how I could compile my parser to hook it onto MineTest directly.
