### ISSUE TITLE
Forward all cheat-prone actions to the server to process

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#10835]
Title says everything.

**Comment by corarona** [comment]
That would be the preferable solution for "the cheat problem"

**Comment by EliasFleckenstein03** [comment]
I've added a custom version string to dragonfireclient, in case that helps.

**Comment by TechDudie** [comment]
Ok no rude language until the the minetest devs decide about it at least

**Comment by corarona** [comment]
> Ok no rude language until the the minetest devs decide about it at least

errrm!? maybe i'm just desensitized but WHAT ?

**Comment by TechDudie** [comment]
This is a stupid reason to get kicked from GitHub

**Comment by corarona** [comment]
What i meant is who has used "rude" language ... is the word cheat rude ? I have really no idea what you're talking about.

**Comment by corarona** [comment]
Also the thread in the df repo shows that you dont need to use "foul language" to be rude. You can be perfectly rude while using clean language. On the other hand "foul language" isnt necessarily rude.

**Comment by sfan5** [comment]
No, the title does not say everything.

What are exactly "cheat-prone" actions? Give examples. Have you seen `register_on_cheat`? If yes, why does not satisfy your usecase?
https://github.com/minetest/minetest/blob/e86c93f0bfe6c094014705fd659f186e2723522d/doc/lua_api.txt#L4639-L4647

**Comment by corarona** [comment]
I guess fly and noclip is what most admins struggle most with ? At least thats what some of them said in the thread in question.

**Comment by rubenwardy** [comment]
This sounds like an issue for this Old PR: #6219

I'm surprised there's not already an issue for this

**Comment by TechDudie** [comment]
I have no idea @sfan5

**Comment by TechDudie** [comment]
I got into this issue because of my favorite minetest server

**Comment by TechDudie** [comment]
Because of this

**Comment by TechDudie** [comment]
If servers allow anarchy server they can use the original server

**Comment by TechDudie** [comment]
I’m gonna try it out myself in a while

**Comment by sfan5** [comment]
If you have no idea we will consider this issue invalid.
