### ISSUE TITLE
Add a mostly-ocean mapgen

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#10830]
## Problem

For hours Iv been playing with map_meta.txt to try to change the seeds and noise settings to make less land and more water. I have edited the water level but this does not accomplish the problem, it just raises the water level and then you have a bunch of decorations and grass underwater. Not to mention, what if I wanted my water level at 1. So after doing this for a while I realized that what im trying to do is impossible and requires a engine tweak. I'm at my ends and I'm so frustrated right now.

Minecraft has the ability to create easily do this but unfortunately, the MT engine makes it impossible.

Its very frustrating when you cannot be creative and im shocked this has never been implemented. We have so many mapgens but none for making mostly-ocean maps?

I know this feature request is likely to be shut down becuase my opinion doesn't really matter. I'm just a needle in a haystack and someone will think this is a dumb idea.

Please just think about this hard and why it may add creativity to the game. I.E. making an island in the middle of an ocean and building on it!

## Solutions

Create a noise that is less bright and mostly dark and use it to generate maps so it generates less land (maybe islands here and there but almost only ocean). This would be the only way.

**Comment by rubenwardy** [comment]
## Mapgen v7

Change the offset of these two noises, like so:

```
mgv7_np_terrain_base = {
	flags = eased
	lacunarity = 2
	persistence = 0.6
	seed = 82341
	spread = (600,600,600)
	scale = 70
	octaves = 5
	offset = -10
}

mgv7_np_terrain_alt = {
	flags = eased
	lacunarity = 2
	persistence = 0.6
	seed = 5934
	spread = (600,600,600)
	scale = 25
	octaves = 5
	offset = -10
}
```

## Valleys

Try changing the offset of `mgvalleys_np_terrain_height`.

--------

Also, there's a GUI for this:

![image](https://user-images.githubusercontent.com/2122943/105107055-18654a00-5aaf-11eb-9ab6-e051e2ab0193.png)

**Comment by TheTermos** [comment]
There's also my lua mapgen dedicated for that kind of thing https://github.com/TheTermos/islands.
It's very simple so porting it to cpp should be trivial.

But I'd prefer a more efficient mapgen modding interface.

**Comment by LoneWolfHT** [comment]
They also asked on Discord and I think we sorted it out with them

**Comment by SmallJoker** [comment]
Mods can change any mapgen setting before the map is generated. The feature exists, hence what you need is a mod to satisfy your wishes.
Not a bug.
