### ISSUE TITLE
Experiencia con Minetest y la programación con Python

### ISSUE THREAD

**Issue by Survivalwar** [minetest/minetest#10839]
## Problem
Hope to Support Python
For Rapid Construction;
is powerful… and fast;
plays well with others;
runs everywhere;
is friendly & easy to learn;
is Open.

## Solutions
https://github.com/sprintingkiwi/pycraft_mod

## Alternatives

https://pythonator.com/
https://miney.readthedocs.io/en/latest/

## Additional context

https://youtu.be/5qwQ1lD_E24?t=1287

**Comment by SmallJoker** [comment]
Duplicate of #69
Nice.
