### ISSUE TITLE
minetest.settings:to_table() error if a settings group is modified

### ISSUE THREAD

**Issue by 0siribix** [minetest/minetest#10831]
##### Minetest version

```
Minetest 5.3.0 (Linux)
```

##### OS / Hardware

Operating system:
CPU:
AMD TR 1900X
##### Summary

Using minetest.settings:to_table() produces an error and exits the server if a settings group is modified using the gui

Setting [xxx] is a group.
stack traceback:
	[C]: in function 'to_table'
##### Steps to reproduce

1. Open Minetest (GUI)
2. Click Settings tab
3. Expand Mapgen > Mapgen V7 > Noises
4. Change any value in any of the groups and save (I tested mgv7_np_dungeons, mgv7_np_cavern, and mgv7_np_floatland)
5. Create a new world
6. Enable a mod that uses minetest.settings:to_table() (I tested modlib and I created a single-line mod with only that function)
7. Start game/Host game

Workaround: Manually edit the noises in map_meta.txt

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/e86c93f0bfe6c094014705fd659f186e2723522d/src/script/lua_api/l_settings.cpp#L265-L267

Missing handling for groups. This function should be recursive.
