### ISSUE TITLE
Android: text input box not easy to use

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest/minetest#10840]
## Problem
Android MInetest Chat input box  Not Easy to use

## Solutions

1. Adjust the size of the Chat input box, width: 720 height: 180
2. Background Transparency Chat input box
3. We don't need , IME enter full-screen editing
![Screenshot_20210121-123838](https://user-images.githubusercontent.com/42504385/105434329-d824e800-5cb7-11eb-8e3c-46d6001475ee.jpg)

**Comment by SmallJoker** [comment]
Do you mean the chat input box or the chat history dialogue?
Would you mind uploading a screenshot to show the problem?

**Comment by wwar-XeStro** [comment]
If you mean '/help' by 'command box' i see that it is annoying to use beacuse of the "+"s are too small
![help_window](https://user-images.githubusercontent.com/72745616/105402675-c94b2080-5c38-11eb-97cd-00dc79599b5b.png)

**Comment by Survivalwar** [comment]
> Do you mean the chat input box or the chat history dialogue?
> Would you mind uploading a screenshot to show the problem?
Chat input box
Screenshot has been uploaded

**Comment by Survivalwar** [comment]
> Do you mean the chat input box or the chat history dialogue?
> Would you mind uploading a screenshot to show the problem?

Chat input box
Screenshot has been uploaded

**Comment by srifqi** [comment]
I can not understand the issue here. For my device, the IME will enter full-screen editing instead.

**Comment by Pantyhose-X** [comment]
> I can not understand the issue here. For my device, the IME will enter full-screen editing instead.

We don't need , IME enter full-screen editing.

**Comment by oong819** [comment]
sometimes on my device, its dont automatically enyer fullscreen

this probally caused by `` requestFocus() `` ordering?

**Comment by grorp** [comment]
I guess this is fixed by #13521. Please reopen if not.
