### ISSUE TITLE
moveresult.touching_ground value is incorrect or misleading

### ISSUE THREAD

**Issue by juanibiapina** [minetest/minetest#10849]
##### Minetest version

```
Minetest 5.3.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/nix/store/lyl5b6q7rvv7pp6szn0krddy7102fnx6-minetest-5.3.0/share/minetest"
STATIC_LOCALEDIR="/nix/store/lyl5b6q7rvv7pp6szn0krddy7102fnx6-minetest-5.3.0/share/locale"
```

I've also tested with commit `4fcd000e20a26120349184cb9d40342b7876e6b8` from January 21st.

##### First of all

Thanks for all the hard work. I'm loving writing mods for minetest.

##### Summary

The collision info table received during the `on_step` function has a wrong or misleading value for `touching_ground`. This value only seems to be `true` if the entity has just moved. For instance, you can spawn a physical entity in the air and set it's velocity to negative y. It will fall and `touching_ground` will be `false`, which is correct. Once it touches the ground, `touching_ground` becomes `true`, which is also correct, and the velocity seems to be reset to 0 because of the collision. The problem is that on the next `on_step`, `touching_ground` is now `false`, even though the entity is literally on the ground.

My guess is that collisions were not calculated because there is no movement, but somehow the engine didn't account for the fact that the entity is *already* on the ground.

This seems like a weird behavior to me, and I couldn't find a good way to determine that an entity is on the ground from Lua. Am I missing something here? If there's a good solution for this, I'm happy to write documentation about it.

**Comment by sfan5** [comment]
This is expected, without movement there will be no collisions and hence an entity cannot *literally* touch the ground. Just missing some documentation.

The way this is usually solved is by applying acceleration equal to gravity. That way the entity will collide with the ground every step and record what you expect.

**Comment by TheTermos** [comment]
The name could be better though, standing_on_ground might sound more adequate.
There's standing_on_object already.

**Comment by juanibiapina** [comment]
That makes perfect sense. Thanks for the guidance!

Is there any way I can contribute or should I just close this?

**Comment by sorcerykid** [comment]
I have a PR which provides an `is_standing` field for the move result. Your rationale is spot on, and that's one of the main reasons I decided on that name when designing the API.

**Comment by juanibiapina** [comment]
linking here: https://github.com/minetest/minetest/pull/9717
