### ISSUE TITLE
Voice chat on servers

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest/minetest#10847]
## Problem

It is helpful to be able to talk by voice in addition to text chat, which is built into Minetest.
For Educators Awesome Features

## Solutions

Use [Distributed hash table](https://en.wikipedia.org/wiki/Distributed_hash_table) 
Use [Blockchain](https://en.wikipedia.org/wiki/Blockchain)

**Comment by mk-pmb** [comment]
Mumble is already trying to provide this. Let's help them by providing better inter-process communication between MineTest and 3rd-party programs.

**Comment by Extex101** [comment]
Can confirm Elkien3 mumble works, I know people that use it

**Comment by midn1** [comment]
> Use Distributed hash table
> Use Blockchain

I feel like you don't know what you're talking about
