### ISSUE TITLE
Some shaders are missing

### ISSUE THREAD

**Issue by IFRFSX** [minetest/minetest#10848]
5.4.0-dev:

![图片](https://user-images.githubusercontent.com/34205903/105449493-795d6f80-5cb3-11eb-8b77-a9bede2b233c.png)

5.3.0:

![图片](https://user-images.githubusercontent.com/34205903/105449543-92662080-5cb3-11eb-8d2b-be73a38915d4.png)

**Comment by SmallJoker** [comment]
Intended. Removed in #10487 because the code needs a redesign.
