### ISSUE TITLE
Link error, undefined symbol: PcgRandom::PcgRandom

### ISSUE THREAD

**Issue by lorecast162** [minetest/minetest#10858]
##### Minetest version

```
Commit hash 4c7623981 from the master branch
```

##### OS / Hardware

Operating system: macOS Catalina 10.15.7 with XCode 12.3
CPU: 2.4GHz Intel Core 2 Duo (my machine is a MacBook7,1)

GPU model:
OpenGL version:

##### Summary

Upon reaching the linking phase CMake prints out this error:
```
[ 27%] Linking CXX executable ../../../bin/minetest
Undefined symbols for architecture x86_64:
  "PcgRandom::PcgRandom(unsigned long long, unsigned long long)", referenced from:
      Sky::updateStars() in sky.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../bin/minetest] Error 1
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
make: *** [all] Error 2
```
(the build is in `<repo root>/build/macOS/`)
##### Steps to reproduce

1. Clone repository
2. Create `build/macOS` directory and `cd` into it
3. Call cmake to generate make stuff
 * `cmake ../.. -DBUILD_CLIENT=1 -DBUILD_SERVER=0 -DENABLE_FREETYPE=1 -DCMAKE_EXE_LINKER_FLAGS='-L/usr/local/opt/freetype/lib' -DENABLE_GETTEXT=1 -DCUSTOM_GETTEXT_PATH=/usr/local/opt/gettext`
4. Call make to compile
 * `make -j4`
5. Build compiles successfully but errors out at the Link stage.

Notes:

Additionally here are [CMakeOutput.log](https://privatebin.mentalabs.eu/?33bc62ed146b5fbf#PcTVtbttXUo88MjNSKSiGbkuJcvSVa4bRQDJjQKW9hW) and [CMakeError.log](https://privatebin.mentalabs.eu/?8347deb46843b809#E8nDiu6jWhquZGntCEkQeMvabMuCBmgtJ8Uq795NwpSW).

I used the `cmake` command that the Homebrew formula uses as I thought that was going to work.

**Comment by lorecast162** [comment]
BTW I also tried using Homebrew's version using `--build-from-source` and it does build but it doesn't launch due to `illegal hardware instruction` (known issue when using catalina on unsupported models, which is why I'm always building from source) so I guess it goes further. I have a tarball with Homebrew's logs up [here](https://mentalabs.eu/downloads/Misc%20Documents/homebrewLog_minetest.tar.gz) on my website.

**Comment by sfan5** [comment]
This is also reproducible on FreeBSD (https://irc.minetest.net/minetest/2021-01-23#i_5776482), which is should be more accessible to any devs willing to fix this.

Do you happen to know if this is a regression?

**Comment by lorecast162** [comment]
I'm sorry but I have no idea at all. It's my first time compiling minetest.

**Comment by numberZero** [comment]
This is upstream bug, Irrlicht guys refuse to `#include <cstdint>` referring to some 20-years-old (maybe 10-years-old at the time of reference) platforms on which it might not exist. A workaround is in #10872.
