### ISSUE TITLE
problem running multiple minetest docker-container

### ISSUE THREAD

**Issue by PatrickJRed** [minetest/minetest#10857]
Hello,
I set up docker and portainer.io like their websites recommended.

then pulled your official docker-image (registry.gitlab.com/minetest/minetest/server:latest)
$:~ docker pull registry.gitlab.com/minetest/minetest/server:latest

then created created a docker-volume "minetest_data" for "/var/lib/minetest" and a bind-mount "/docker.d/minetestconf.bind" for "/etc/minetest" (creating this means i created the dir /docker.d/minetestconf.bind on my host

via portainer created container1 for your image
-name: minetestserver_main
-Portmap 30001:30000 UDP
-access control: no
-autoremove : no
-network is the default "bridge" (this is used by portainer and my other containers)
-Command and Logging
 i added "' --worldname' 'world'" to your Command : "'/usr/local/bin/minetestserver' '--config' '/etc/minetest/minetest.conf' ' --worldname' 'world'" (and yes i put a world in to the corresponding folder)
 User: "minetest:minetest"
 Workdir : "/var/lib/minetest"
 Console: none
-Restart Policy: Unless Stopped
 the rest is what portainer/docker set as defaults

via portainer created container2 for your image
-name: minetestserver_myprivateworld
-Portmap 30002:30000 UDP
-access control: no
-autoremove : no
-network is the default "bridge" (this is used by portainer and my other containers)
-Command and Logging
 i added "' --worldname' 'myprivateworld'" to your Command : "'/usr/local/bin/minetestserver' '--config' '/etc/minetest/minetest.conf' ' --worldname' 'myprivateworld'" (and yes i put a world in to the corresponding folder)
 User: "minetest:minetest"
 Workdir : "/var/lib/minetest"
 Console: none
-Restart Policy: Unless Stopped
 the rest is what portainer/docker set as defaults

the i tested a few times to start both of them at ones or one at a time.
doing only one worked, but when i added the other one, i could see in portainer that both had now their ports not published anymore. (no matter which i start first)

and that was yesterday - today i cant even get with only one running that the port is published.

so i got this question: how do i set up containers correctly so i can use the same volume/bindmount for all of them and each having their own world (of which i have 4 - but i cant even get 2 running)?

thx in advance

**Comment by PatrickJRed** [comment]
BTW. i am using Lubuntu 20.04. LTS and latest docker/portainer and minetest docker-image

**Comment by PatrickJRed** [comment]
stopped all minetest-containers.

trying to create one from scratch - 1. try strating it - no published ports.

what am i doing wrong / what am i forgetting or miss-configurating ?

**Comment by PatrickJRed** [comment]
trying from terminal

"docker container ls -a"
bebf82f77099   registry.gitlab.com/minetest/minetest/server:latest   "/usr/local/bin/mine…"   About an hour ago   Exited (1) 31 seconds ago                                                       minetest_test

"docker start minetest_test"

"docker container ls -a"
bebf82f77099   registry.gitlab.com/minetest/minetest/server:latest   "/usr/local/bin/mine…"   About an hour ago   Restarting (1) 6 seconds ago                                                    minetest_test

so it doesnt even start

**Comment by PatrickJRed** [comment]
So as i just tested running/creating via terminal, i found out that the volume isnt writable even though i set it to mount writable
(on host : ls -Ahl /var/lib/docker/volumes/minetest_data/_data shows owner+group = 30000).

how do i fix that ?

**Comment by PatrickJRed** [comment]
idk what i did - but starting and stopping one/both like 10 or more times worked - there both up and running correctly

maybe for newbies (on minetest and docker) like me it would be a good idea to give some basic examples of running multiple instances each having different worlds or mods
-> like 1x production + 1x testing

**Comment by PatrickJRed** [comment]
i try to reboot the pc later - maybe that fix isn't permanent

**Comment by mk-pmb** [comment]
Try binding the UDP port to an IP explicitly. Docker [seems to have a bug with listening for UDP globally](https://github.com/moby/libnetwork/issues/1729).

**Comment by PatrickJRed** [comment]
I think i change the setup of that docker-network stuff so that each container on my dockernetwork gets an IP from my HWRouter (https://docs.docker.com/network/macvlan/ i think)

**Comment by mk-pmb** [comment]
That's ok. You can get the IPs any way you like, as long as docker sees that IP on a network interface. The important thing is to tell docker, in the portmap, to explicitly use that exact IP, rather than "any" IP.
