### ISSUE TITLE
While a mod is being installed, the "search" textbox is reset to a value before the installation

### ISSUE THREAD

**Issue by SuperLeaf1995** [minetest/minetest#10854]
##### Minetest version

5.3.0
```

```

##### OS / Hardware

Operating system: Ubuntu
CPU: Intel Pentium E380

GPU model:
OpenGL version:

##### Summary
Title

##### Steps to reproduce
- type ABCDEF
- install some mod
- while it installs type FOOBAR
- textbox goes back to ABCDEF

**Comment by v-rob** [comment]
This is an unfixable formspec issue: it's not possible to get the value of a field without the user pressing enter, using a button, or interacting in some other way.  The same issue is present if you type text into a field and then resize the window -- the text will be reset.  There's absolutely no simple solution to this and needs resolving through the formspec replacement.
