### ISSUE TITLE
Add string-collecting utility for .tr translations

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10852]
Minetest does not have an official utility script for collecting all those strings on the server side (mods, etc.), in order to generate and update the `.tr` files.

So an utility script to deal with `.tr` files is badly needed.

Thankfully, there is already a very good candidate. It's a Python script, LGPLv2.1'ed, and can be found here:

https://github.com/minetest-tools/update_translations

I have used this script a lot of times already, e.g. for MineClone 2. It's very useful. It can:

* Generate new `.tr` files and `template.txt`
* Update existing `.tr` files

I suggest to review this script and decide on whether to include it.

**Comment by rubenwardy** [comment]
s/server-side/mod/ ?

**Comment by Wuzzy2** [comment]
I said “server-side” for everything from a `.tr` file. This is only mods for now, but soon (haha!) will also include builtin, which is server-side, but not a mod.

**Comment by Wuzzy2** [comment]
> which is server-side, but not a mod.

Well, mostly. Builtin has server-side strings. Not all of them, but still. You get the point, I hope.

**Comment by rubenwardy** [comment]
`server-provided` or `mod-provided`? Because `client-side translation` is already a thing :)

Or perhaps just ".tr translations"

**Comment by Wuzzy2** [comment]
So … Any comments about the script then? This script is about updating `.tr` files.

**Comment by ronoaldo** [comment]
I support this being integrated into the main distribution. Having tooling to help/easy mod translation would be very handy.

**Comment by Wuzzy2** [comment]
I have a question: Should this script be dumped right into the Minetest repository (perhaps under the `util/` directory)?
Or would it be smarter to create a completely new repository, but under the `minetest` GitHub organization?

Note this is a Python script, not sure if this is a problem. But as far I know, this is bascially the only script we have right now.

**Comment by Wuzzy2** [comment]
Sadly, a PR that implemented this (#13464) was closed due to "not being on the roadmap" although this particular issue is "supported by core dev". It is very sad that this very important tool for development, something which I have been using productively and has saved so much time, has been rejected just because of a formality.

It does not make sense. Either the script is desired, or it is not. If it is not desired, this issue should be closed; keeping it open would not make sense. But if I can get green light (again!) from the devs, I will probably post a new and updated PR for a much-improved version of the script.

Context: I am talking about this script: https://codeberg.org/Wuzzy/minetest_update_translations

@Zughy

**Comment by Wuzzy2** [comment]
So it seems like a string collection script is still desired due to the re-opening of #13464. Cool.

So I think I should create a brand-new PR soon-ish then because #13464 was badly out of date. Stay tuned for further updates. In the meanwhile, you can play around with my new repo here: <https://codeberg.org/Wuzzy/Minetest_Translation_Tools>. I think the updater should now be more stable than ever.

Just one more question: Are you OK with my new PR also including the translation checker script (to check TR files for syntax errors)? Or should I only include the updater? (If there is no response, I assume "only updater".)
