### ISSUE TITLE
Mapgen: Lots of lighting calculation errors

### ISSUE THREAD

**Issue by TheTermos** [minetest/minetest#10874]
##### Minetest version
```
5.3.0
```

##### Summary
Noticed this when fiddling with light curve settings. Lots of errors happen at block boundaries, probably related to decorations.
This happens with built in mapgens as well as with lua mapgens that call `calc_lighting()` and `write_to_map(true)`
The only way around this I found is to call `minetest.fix_light()` on chunks after on_generated.
![lightbug](https://user-images.githubusercontent.com/55103816/106123134-d6e13880-6159-11eb-9565-17af22271ebf.jpg)

##### Steps to reproduce
Make shadows more visible (e.g by setting gamma way low) and check out lighting generated near decorations that don't propagate light.

**Comment by lhofhansl** [comment]
TNT explosions also cause lighting bugs.

**Comment by TheTermos** [comment]
That isn't related to mapgen though. TNT is an MTG thing, so might even be a MTG issue.

**Comment by SmallJoker** [comment]
Does this also happen in 5.4.0-dev? The mapgen was touched there to make it more multithread-safe.

**Comment by TheTermos** [comment]
As of the release candiate: minetest-5.4.0-d1ec5117d-win64
Errors still there.
