### ISSUE TITLE
Any plans for network compatibility in the future?

### ISSUE THREAD

**Issue by Dev380** [minetest/minetest#10875]
## Problem

I really like this project, however the only problem is that it isn't compatible with minecraft servers, so are there any plans to make multiplayer api-compatible with Minecraft: Java Edition servers?

## Solutions

Make multiplayer use the same API as Minecraft's multiplayer.

## Alternatives

I can't do this because I don't know Java, but maybe we can make Minetest a Minecraft clone because we get free updates, since Minecraft singleplayer is basically UI + Rendering + Integrated server and Paper is a free as in freedom Minecraft server and Sodium is a free as in freedom rendering engine.

**Comment by rubenwardy** [comment]
Nope, there are no plans

Minetest has drastically different features from Minecraft - our mods are mostly server side, we have content and registration sending, and many other differences.

Implementing things like network compatibility is hard without compromising our copyright, it's hard to keep to a clean room implementation - as far as I know, none of the Minetest devs have read Minecraft source code

You could implement this yourself using a proxy / adapter which speaks both Minetest and Minecraft protocols, it wouldn't be a great experience though
