### ISSUE TITLE
LUA API: minetest.register_tree

### ISSUE THREAD

**Issue by Zander200-glitch** [minetest/minetest#10888]
Adds the ability to create custom trees more easily.
#### Usage
minetest.register_tree(tree_definiton)

the tree definiton contains:
- biomes: table to specify the biome names the tree can generate in
- stem_node: node reference to what will be the stem of the tree
- stem_height_min: minimum stem height
- stem_height_max: maximum stem height
- leaves_node: node reference to what will be the leaves of the tree

**Comment by Extex101** [comment]
This would be more suited for Minetest Game

**Comment by Zander200-glitch** [comment]
should i post it there?
