### ISSUE TITLE
Block send range is not large enough for high-end but is already unnecessarily high for  low-end computers

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest#1088]
The viewing range needs to be sent from the client to the server, which means something like this:

https://github.com/freeminer/freeminer/commit/f86ef3a14ffdcc432029a153f14854fd9298c4d0

But that packet isn't suitable for this; a new packet has to be created, the purpose of which will be sending 1) just this, or alternatively 2) some kind of generic client configuration options to the server.

Additionally both the emerge manager (in addition to having a bug) and networking is unsuitably configured for larger viewing ranges. A larger range is best handled with something like this:

max_simultaneous_block_sends_server_total = 10000
max_simultaneous_block_sends_per_client = 100
emergequeue_limit_diskonly = 50
emergequeue_limit_generate = 50

which probably does not cause regressions on low-end systems or connections.

Taking care of this issue shall wait until sapier's server and connection fixes land in upstream.

**Comment by paramat** [comment]
#4811 merged.
