### ISSUE TITLE
Mods On Android?

### ISSUE THREAD

**Issue by NSTAdventure** [minetest/minetest#10893]
(Before Start Do Not Blame me why I didn't create this on disscussion there is no disscussion thread here)

How to instal mods on minetest android?

**Comment by rubenwardy** [comment]
Go to Content and then click Browse Online Content. You can then install mods

You need at least 5.0 for this

**Comment by NSTAdventure** [comment]
> Go to Content and then click Browse Online Content. You can then install mods
> 
> You need at least 5.0 for this

🤦 I need detailed instruction how to instal it i mean which folder?
