### ISSUE TITLE
Expose 'ores' mapgen flag in "new world" dialog?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10900]
The 'ores' mapgen flag was added for this version. And now a release is imminent. What do you think about exposing the 'ores' mapgen flag to the "New world" dialog before 5.4.0 release (or in general)?

Or do you consider this flag to be not important enough for this?

@paramat

**Comment by Beanzilla** [comment]
So something like a xray or something like that where it shows the locations for various ores?

**Comment by 0-afflatus** [comment]
> So something like a xray or something like that where it shows the locations for various ores?

lol no. He's talking about the dialog for setting up a new game.

**Comment by Wuzzy2** [comment]
Note to core devs: This was more of a question than a feature request. I am myself neutral about having the 'ores' flag exposed. You can safely close this if you are against it.
