### ISSUE TITLE
More clicks per second for more damage

### ISSUE THREAD

**Issue by Code-Sploit** [minetest/minetest#10904]
## Problem

CPS does'nt matter.
CPS == clicks per second

When you click in-game you only have full_punch_interval.
I would like that the faster you click the faster you can do damage.

## Solutions

Add a feature to the engine/lua that makes sure that cps matters.

## Alternatives

None.

## Additional context

I would just like that it'd be added. (I'm not really familiar with minecraft but i think it works the same way there).

**Comment by Code-Sploit** [comment]
Better @sfan5?

**Comment by sfan5** [comment]
No, not at all.
You do not explain what CPS is or what effects it would have in-game(?).

**Comment by Code-Sploit** [comment]
Updated

**Comment by randomMesh** [comment]
Reminds me of the good ol' Summer Games battles...
![DxxbjNUXgAYruvJ](https://user-images.githubusercontent.com/32773707/106756012-1367d500-662f-11eb-928f-d261ed92dda1.jpg)

**Comment by randomMesh** [comment]
Friction produces heath. This means if i stir my coffee fast enough, it gets hotter!

**Comment by SmallJoker** [comment]
This will only motivate people to use autoclicker utilities. I don't see any reason to implement bonus damage for rapid clicking.

**Comment by rubenwardy** [comment]
the purpose of full_punch_interval is to limit damage the faster you click. You can reduce the full_punch_interval if you want to be able to click faster

**Comment by Beanzilla** [comment]
In Minecraft, at least above 1.9 in the "Combat Update" they implemented... oh hey look full_punch_interval. So I guess to be more flexible you could make some mod that reduces that... though PVP would be insane then. (But it would be up to you I guess)

But I agree with SmallJoker on the issue of that would promote technically "cheating", those who don't use a utility would always be at a disadvantage, and vice versa, those with a auto click utility (hack if you want to call it that) would almost always rule the playing field.

I feel like it would be a side step to implement this... however there are Minecraft mods that reverse the "Combat Update" so it's not like we would be doing something only we do.

**Comment by DeltaNedas** [comment]
since you can already reduce full_punch_interval, what is the issue?
