### ISSUE TITLE
Please un-deprecate get_player_velocity and add_player_velocity

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10901]
Why were `get_player_velocity` and `add_player_velocity` functions deprecated for 5.4.0-dev? This seems completely unneccessary and just adds pointless annoyance to game devs because they now have to actively repair their games again for no apparent reason. I only saw this when I read the changelog.

While it's not technically a breakage (yet), deprecating these functions shows the intent of removing these functions eventually. So I still think it's annoying.
It's also done inconsistently, we still have `get_player_name` for some reason. \*shrug\*

I propose to revert this deprecation and bring those functions back to their former glory. It's not too late to un-deprecate these functions, 5.4.0 is not released yet.

@rubenwardy.

**Comment by rubenwardy** [comment]
It makes no sense to have both get_velocity and get_player_velocity. Entities don't have names which is why it's get_player_name. Note that it's also get_pos not get_player_pos

The engine needs to make changes to improve the API. You can literally just find and replace in multiple files to update this

**Comment by Wuzzy2** [comment]
Not convincing. Yes, it might be true that "get_player_velocity" is slightly uglier than "get_velocity" but that alone is a pretty weak justification for the rename IMO. The name is not *wrong*, after all. Don't you have a stronger reason for the rename? Is there maybe a technical reason or is it really just about optics?
I don't care how "easy" it is to rename it in games, game authors still need to be "activated" to do this, this will be an issue for unmaintained games. It will become a breaking change when those functions are removed eventually.

I think a game made in 5.0.0 should still work in 5.9.0 without any changes neccessary. Compability is good. I understand compability is not always possible, but this seems to be an case where it's completely unneccessary to throw out the compability just for a very minor optics gain.

**Comment by rubenwardy** [comment]
I want Minetest to have the best API it can, and having stuff like this is confusing and inconsistent

**Comment by ExeVirus** [comment]
Hey there is actually a great idea tucked in here. Depreciated stuff should only be removed after a major version upgrade from 5->6 and so on. That makes perfect sense.

**Comment by rubenwardy** [comment]
> Hey there is actually a great idea tucked in here. Depreciated stuff should only be removed after a major version upgrade from 5->6 and so on. That makes perfect sense.

This is actually our current policy, but we have discussed removing some deprecated things after a few versions. I think that should be limited to situations where it's actually needed, keeping support for `get_player_velocity` is a single line of code

**Comment by benrob0329** [comment]
>  will become a breaking change when those functions are removed eventually.

Isn't that why such a release would be a "breaking release" (ie 6.0)? You assume these will be removed anytime soon, but MT has actual breaking releases for exactly this sort of thing.

**Comment by Wuzzy2** [comment]
Yes, why not delaying the removal/rename of these functions to 6.0.0? This deprecation is just a minor optics change in my opinion, and doesn't justify a deprecation at all in a feature release. The reasoning behind this is too weak. The teeny-tiny benefit doesn't outweight the annoyance.

NOTE: I am not against deprecations in feature releases per se. For example, I was completely fine with the removal of bump mapping and other shader stuff for 5.4.0. I completely accept this because the justifaction is good (pretty broken features). I would also be fine with a deprecation if a function name would be e.g. *completely* misleading (e.g. function named “add”, but it subtracts), or some feature was very poorly designed or implemented. That is not the case here.

**Comment by randomMesh** [comment]
The longer you keep `get_player_velocity`, the more people use it in their mods. It's better it's removed sooner than later.

**Comment by rubenwardy** [comment]
The benefit is that you can use `get_velocity()` for both players and entities. They're both ObjectRefs. This is less confusing and more consistent.

I am :-1: :-1: for reverting it, this would be a dumb precedent to set.

```bash
find . -type f -print0 | xargs -0 sed -i 's/get_player_velocity/get_velocity/g'
find . -type f -print0 | xargs -0 sed -i 's/add_player_velocity/add_velocity/g'
```

**Comment by Wuzzy2** [comment]
That … That's actually a good argument. Alright, I am no longer convinced the deprecation is an issue.

Closing.

**Comment by kay27** [comment]
Hi @rubenwardy , can you please suggest some resolution you think right when we still need to support both 5.3 and 5.4 in code sections like this, because some mods still doesn't support minetest version 5.4 and there is a problem for servers' onwers to update the engine because of this:
```lua
if player:get_velocity().x + player:get_velocity().y < .5 and c_x + c_y > 0 then
	player:add_velocity({x=c_x, y=0, z=c_y})
end
```
My candidate is:
```lua
if (player:get_velocity() or player:get_player_velocity()).x + (player:get_velocity() or player:get_player_velocity()).y < .5 and c_x + c_y > 0 then
	player:add_velocity({x=c_x, y=0, z=c_y}) or player:add_player_velocity({x=c_x, y=0, z=c_y})
end
```
But it looks a little crazy for me.

Should I open separated issue for this?

**Comment by sfan5** [comment]
You can continue using `get_player_velocity` and `add_player_velocity` and just live with the warnings (they should only show up once per code line).

**Comment by kay27** [comment]
Sadly, this code "as is" cause crashes because it indexes the coordinates.
I need to rewrite it somehow. I can redesign it entirely but this code isn't mine, I'm in doubts.
Live example:
![image](https://user-images.githubusercontent.com/2028802/114898726-6cb86580-9e23-11eb-8840-b3f1f8af6509.png)

**Comment by sfan5** [comment]
Yes, I'm saying you can use `if player:get_player_velocity().x + [...] then` and it will work on both 5.3 (or older) and 5.4.

**Comment by kay27** [comment]
Okay, now I realize what you mean.
Thanks, first of all.

But it promises to be hard :( These warnings are visible for everyone, and continuously cause things like this:
https://git.minetest.land/MineClone2/MineClone2/issues/952
https://git.minetest.land/MineClone2/MineClone2/issues/954
https://git.minetest.land/MineClone2/MineClone2/issues/1203

When I wrote my first comment pinging rubenwardy, I thought about maybe some initial aliasing of old function names for old engine versions. Aren't some things like this possible?

**Comment by rubenwardy** [comment]
Worth noting that Wuzzy's policy for Mineclone2 was only to support the most recent Minetest engine version

You can use `minetest.features.direct_velocity_on_players` as a Boolean to check whether you can use the new functions, rather than trying to call them
