### ISSUE TITLE
Reduce "Empty translation" debug log message level from error to info or action

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10905]
##### Minetest version
```
5.3.0
```

##### Summary
If you have a translated game or mod and the translation has any string with an empty translation (like `Apple=`), there is an ugly big red ERROR in the console and chat. If there are a lot of empty translations, your chat is completely spammed with this error.

This can be very annoying. It should be perfectly normal for a translation to be empty, this just means it was not finished yet. Throwing out an ERROR is overkill and too aggressive. Players shouldn't be bothered with this at all.

I propose to reduce the level of this message to `info` only, or `action` at most. If translators want to test their translations, they should look into the logfiles.

**Comment by sfan5** [comment]
Depends, when a translation is empty will it fall back to the original string?
If it does, then this should be downgraded to a warning (or even less).

**Comment by randomMesh** [comment]
> when a translation is empty will it fall back to the original string?
> If it does, then this should be downgraded

And if it doesn't, it should be made so. That's de facto standard.

**Comment by Wuzzy2** [comment]
Yes, it will fall back to the original string, I tested. That's *really* important. :D

**Comment by rubenwardy** [comment]
If it falls back to the original string, I think it shouldn't even log at all

**Comment by Wuzzy2** [comment]
Yes, or just a low log level like `action`, `info` or even `verbose`.
`warning` would be too high IMO. And `error` is definitely too high.

**Comment by Wuzzy2** [comment]
Let's decide what to do with the messages. Should they:

* Be removed completely?
* Be reduced to the log level `action`?
* Be reduced to the log level `info`?
* Be reduced to the log level `verbose`?

Personally, I prefer `info`, but I have no strong opinion of that, and would be OK with any other of the above options.
