### ISSUE TITLE
Bone position and rotation shared on all objects

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#1091]
d76957ee22c27adab89cee551e3ab1c85d8717cc fixes the shared light value, but bone rotation and position (set via obj:set_bone_position()) is still shared on all objects with the same model.
(If you need a mod to test it: https://github.com/PilzAdam/nodetopia/blob/a27833f2b801e34a1d5aaecd00046c0adfc2c46d/mods/mobs/init.lua#L55)

**Comment by est31** [comment]
A user has said they couldn't reproduce this. Has it been fixed since?

**Comment by paramat** [comment]
@PilzAdam still an issue?

**Comment by PilzAdam** [comment]
@paramat haven't checked in a while, but I also haven't seen a commit that is supposed to fix it.

**Comment by paramat** [comment]
Needs reproducing.

**Comment by rubenwardy** [comment]
closed as unreproducable, if you can reproduce please comment
