### ISSUE TITLE
Check noise_params ore error

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10914]
After #10846, certain ores types ("sheet", "puff", "blob" and "vein") will shows errors and be ignored if they're missing noise_params.

It should be checked what the old behaviour was, and consider changing this to a warning

**Comment by Wuzzy2** [comment]
It would be very useful to know what the old behavior was, so it's easier to fix on the game side.

Also, changelog should be updated after the research is done, obviously.

**Comment by rubenwardy** [comment]
OK, the old behaviour was to use the default noise params which are as follows:

```lua
noise_params = {
    offset  = 0,
    scale   = 1,
    spread  = {x=250, y=250, z=250},
    seed    = 12345,
    octaves = 3,
    persist = 0.6,
    lacunarity = 2,
    flags = "defaults",
}
```

This error should be changed to a deprecation warning, and these defaults used
