### ISSUE TITLE
use_texture_alpha warning spam

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10915]
Relevant IRC convo: https://irc.minetest.net/minetest-dev/2021-02-03#i_5780882

PR: #10819 

## Boolean values

use_texture_alpha prints the same line over and over again:

	WARNING[Main]: Field "use_texture_alpha": Boolean values are deprecated; use the new choices

This is printed 110 times by Mineclone2, notice how there's no modname/stack.

This, at least, is fairly easy to fix using a find/replace.

## Assuming clip

Mineclone2 prints lines like this 400+ times:

> WARNING[Main]: Texture "cake_top.png" of mcl_cake:cake_4 has transparency, assuming use_texture_alpha = "clip".
> WARNING[Main]:   This warning can be a false-positive if unused pixels in the texture are transparent. However if it is meant to be transparent, you *MUST* update the nodedef and set use_texture_alpha = "clip"! This compatibility code will be removed in a few releases.

Can this be reduced? For example, is it already only shown for meshes and nodeboxes?

**Comment by sfan5** [comment]
> is it already only shown for meshes and nodeboxes?

Yes. the behaviour of all other drawtypes was not changed and doesn't need a deprecation warning.

**Comment by rubenwardy** [comment]
I think this is a rather tedious API. 

This is a change purely (from reading the PRs) for optimisation reasons. Detecting whether the texture contains alpha and setting the transparency mode based on that seems like a good API to me.

It seems the problem with incorrectly assuming clip would be:

* It could result in reduced performance
* It could allow cheating - node boxes and meshes nodes aren't used that much in the world, and I believe they can't cause seethrough world hacks anyway

I'm not sure those are as bad as an annoying API for this, but I'm on the fence

**Comment by sfan5** [comment]
> Detecting whether the texture contains alpha and setting the transparency mode based on that seems like a good API to me.

The server can't do this so the client would have to. This wouldn't fix problem 2 and I also think it's wasted effort/CPU time when the modder could just specify what they want.

> node boxes and meshes nodes aren't used that much in the world

...have you recently visited any popular Minetest server?

> I believe they can't cause seethrough world hacks anyway

Correct, you can "only" turn them entirely invisible

**Comment by ExeVirus** [comment]
Can confirm that there are a lot of potential bugs with how we use meshes in minetest, I can't confirm any exact behaviors, but see through, lighting glitches, etc. all occur when using lots of larger than a node meshes. As I release and use more mods/games with lots of meshes, these problems will come to light.
