### ISSUE TITLE
Regression: can't override game textures from mod's textures folder anymore.

### ISSUE THREAD

**Issue by TheTermos** [minetest/minetest#10936]
##### Minetest version
```
minetest-5.4.0-d1ec5117d-win64
```

##### Summary
In 5.3.0 textures put in a mod's textures folder used to override game textures, doesn't seem to work with 5.4 RC

##### Steps to reproduce
Create a mod dependent on default and put a modified default texture (e.g. default_dirt.png) in the mod's textures folder. Compare the behavior in 5.3 and 5.4

**Comment by rubenwardy** [comment]
PR: #10752
