### ISSUE TITLE
Bump protocol version

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#10933]
Under the decision made in #10368, the network protocol should be bumped to 40 before releasing 5.4.0

**Comment by rubenwardy** [comment]
Although, I'm now wondering if we couldn't do better than protocol versions. The protocol version returned by get_player_information is limited by the current server version

**Comment by SmallJoker** [comment]
Which feature needs such an identification? All formspec stuff can be detected using its increased version. Also server-side-only features are handled using feature flags (where needed). This limits the use-cases already a bit to perhaps the following features:

 * Compass HUD (minimap has backwads compat)
 * Visible attachments in 1st perspective
 * ??? cannot find more in the changelog

**Comment by sfan5** [comment]
Formspec version was bumped during 5.4.0 (b1ff04e06da531dc52f6ee91e2967b39743033e6) so identification is already possible and bumping the protocol unnecessary.
So despite the previous decision (which I also think was not discussed properly enough) I vote :-1: for doing this for this release.
