### ISSUE TITLE
make install doesn't work.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#10945]
Basically make install doesn't work, not sure if it ever did.

Compiled Minetest with
```
cmake ../minetest/ -DWARN_ALL=0 -DREQUIRE_LUAJIT=1 -DENABLE_SYSTEM_JSONCPP=1 -DENABLE_SYSTEM_GMP=1 -DENABLE_CURL=1 -DBUILD_SERVER=1 -DBUILD_CLIENT=0 -DCMAKE_INSTALL_PREFIX=/home/minetest/Minetest-Server -DBUILD_UNITTESTS=0 -DCMAKE_BUILD_TYPE=Release
```

Checking files and directories "installed".
```
/Minetest-Server$ ls
bin  share
```
As you  can see, everything is missing.

This is the stuff that should be copied over("installed")
```
/Minetest-Server$ ls ../minetest/
bin  build  builtin  client  clientmods  cmake  CMakeLists.txt  doc  Dockerfile  fonts  games  lib  LICENSE.txt  minetest.conf.example  misc  mods  po  README.md  src  textures  util
```

I did try to manually copy files over.
```
cp -R builtin doc games lib minetest.conf.example misc mods po textures util ../Minetest-Server/
```

But then still, server wouldn't start, because it couldn't find its files.
```
2021-02-12 04:27:14: ERROR[Main]: Game "minetest_game" not found
```

Even though the game is clearly there.
```
/Minetest-Server$ ls games/minetest_game/
game_api.txt  game.conf  LICENSE.txt  menu  minetest.conf  minetest.conf.example  mods  README.md  schematic_tables.txt  screenshot.png  settingtypes.txt
```

It was also complaining about no admin name defined.
```
2021-02-12 04:35:50: ERROR[Main]: No name given for admin. Please check your minetest.conf that it contains a 'name = ' to your main admin account.
```

But again, it's clearly there.
```
/Minetest-Server$ cat minetest.conf | egrep "name = Megaf"
server_name = Megaf Server 5,0
name = Megaf
```

So yeah, basically minetest server, and likely the client too, will not work when using the standard `make && make install` procedure.

The only way to get it to work is by using `-DRUN_IN_PLACE=1` flag and run it from the source directory.

**Comment by sfan5** [comment]
With `RUN_IN_PLACE=0` you are required to install Minetest at the system-wide path before running it, you cannot run it from any folder. Allowing that is the entire point of `RUN_IN_PLACE=1`, so use that.

> As you can see, everything is missing.

There clearly are two folders.
