### ISSUE TITLE
Issue when trying to access online content

### ISSUE THREAD

**Issue by WulftheNordicRanger** [minetest/minetest#10942]
##### Minetest version
Minetest 5.4.0-dev-9736b9cea-dirty

##### OS / Hardware

Operating system: Arch linux
CPU: intel i3 8th gen

##### Summary
When I try to access the online content in the content db, I get this error:

2021-02-11 04:30:48: ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): /usr/share/minetest/builtin/mainmenu/dlg_contentstore.lua:586: attempt to compare number with nil
2021-02-11 04:30:48: ERROR[Main]: stack traceback:
2021-02-11 04:30:48: ERROR[Main]: 	/usr/share/minetest/builtin/mainmenu/dlg_contentstore.lua:586: in function 'update_paths'
2021-02-11 04:30:48: ERROR[Main]: 	/usr/share/minetest/builtin/mainmenu/dlg_contentstore.lua:992: in function 'create_store_dlg'
2021-02-11 04:30:48: ERROR[Main]: 	/usr/share/minetest/builtin/mainmenu/tab_content.lua:157: in function 'handle_buttons'
2021-02-11 04:30:48: ERROR[Main]: 	/usr/share/minetest/builtin/fstk/ui.lua:142: in function 'handle_buttons'
2021-02-11 04:30:48: ERROR[Main]: 	/usr/share/minetest/builtin/fstk/ui.lua:186: in function </usr/share/minetest/builtin/fstk/ui.lua:172>

##### Steps to reproduce
1, go to the content tab
2, hit browse online content

**Comment by xenonca** [comment]
Can confirm this bug using the freshly released version MT 5.4 on KDE neon.

**Comment by rubenwardy** [comment]
What content do you have installed? You can share a screenshot of the content tab

**Comment by xenonca** [comment]
Me a lot, this would be lot of screenshots probably. How would this help if I may ask?

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/225e69063fa0c3dc96f960aa79dfc568fe3d89a8/builtin/mainmenu/dlg_contentstore.lua#L585-L589

There appears to be a mod that specifies `author` in its `mod.conf`, hence Minetest assumes it's installed by ContentDB even though there's no `release` value present. You could find the affected mod by changing those lines to the following:
```Lua
	for _, mod in pairs(pkgmgr.global_mods:get_list()) do
		if mod.author and not mod.release then
			core.log("error", "Bad mod: " .. dump(mod.name)
		end
		if mod.author and (mod.release or 0) > 0 then
			mod_hash[mod.author:lower() .. "/" .. mod.name] = mod
		end
	end
```

**Comment by rubenwardy** [comment]
Release should default to 0 when the key isn't present

**Comment by xenonca** [comment]
Could this be a reason to see a 5.4.1 patch release? Not sure if I want to touch the builtin code and possibly stumble across more consecutive bugs.
(I guess this is not an unconfirmed bug anymore?)

**Comment by rubenwardy** [comment]
> Release should default to 0 when the key isn't present

for texture packs in [pkgmgr.lua](https://github.com/minetest/minetest/blob/master/builtin/mainmenu/pkgmgr.lua#L93)

for mods in [pkgmgr.lua](https://github.com/minetest/minetest/blob/master/builtin/mainmenu/pkgmgr.lua#L138)

for games in [l_mainmenu.cpp](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_mainmenu.cpp#L316)

So I don't know where the nil would be coming from

**Comment by rubenwardy** [comment]
> Me a lot, this would be lot of screenshots probably. How would this help if I may ask?

I'd like to know what content is triggering it. It'll be one which wasn't installed from ContentDB, you could try a binary search to narrow it down

**Comment by rubenwardy** [comment]
I can reproduce this crash with the following mod.conf:

```
name = crash
author = rubenwardy
release =
```

The problem is with the following line:

```lua
release = tonumber(conf.release or "0")
```

if conf.release isn't a valid number, then tonumber will return nil

**Comment by xenonca** [comment]
Thank you! The Content Tab seems to work again after applying the changes in your commits.
