### ISSUE TITLE
Attachable waypoints/Live waypoints

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#10947]
## Problem

There's no way to attach a hud `waypoint` to an entity or player
I suppose it's possible to just edit the players nametag to act as a `waypoint` but then it'd be global and still it's still not possible to attach `image_waypoint`s

## Solutions

Maybe if the `world_pos` value is a playerRef or entity ref then attach it to the object

## Alternatives

I have worked out a way to change the waypoint position in a globalstep but it's extremely costly

## Additional context
Uses
 - Tracking devices
 - A guide to a player's location (A "you have to travel there" alternative to the /tpr mod)
Ect.

**Comment by SmallJoker** [comment]
Clients may not know the position of far-away players due to the sending limit. If there's no entity sent to the client, the existing nametag is updated each step. Unless the other player is known to the client, your globalstep approach is the only sane approach.
