### ISSUE TITLE
Mods with no dependencies to install still show the dialog

### ISSUE THREAD

**Issue by DeltaNedas** [minetest/minetest#10944]
## Problem

When installing mods with dependencies, if they are already installed the "download dependencies now" dialog still shows.

![Screenshot_01:43:26](https://user-images.githubusercontent.com/39013340/107723338-c9d75400-6cd8-11eb-8374-4299075e63d9.png)

Yeah it's nice to know that it depends on farming, but I already have it installed so why do I need to be told this?
I can check the description if I am curious.

## Solutions

Only showing the confirmation dialog if there are any *extra* dependencies to download.

## Alternatives

no

**Comment by sfan5** [comment]
The "Install missing deps" could be grayed out but I don't think having the confirmation dialog is bad in itself.

**Comment by rubenwardy** [comment]
The idea is that you may wish to change the base game. However, I guess there's not too much harm in not showing it

**Comment by DeltaNedas** [comment]
in that case a specialized window that *only* shows a list of dependencies, along with an ok button to close it, would be nice.

**Comment by AntumDeluge** [comment]
I like the confirmation dialog.

**Comment by SmallJoker** [comment]
Keep it stupid simple. A confirmation dialogue is good to have in all cases which also makes the whole process consistent.
