### ISSUE TITLE
please add support for priv dependent craft recipes

### ISSUE THREAD

**Issue by imre84** [minetest/minetest#10940]
## Problem

There might be multiple examples out there but I'm aware of the advtrains mod where this would make sense. In order to do stuff in advtrains mod you need certain privileges, however there are few items/nodes that wouldn't be wise to let anybody unconditionally own, therefore there's no craft recipe for them.

If there would be a way to have privilege dependent craft recipes, the privileged players would be able to craft those without any admin intervention

## Solutions

make a construct to register priv dependent craft recipes: that is, a recipe that only works for players having ALL the privileges enumerated

I hope that makes sense, thank you for the feature in advance.

**Comment by Montandalar** [comment]
I suggest a new property be added to the 'crafting recipes' table format^ called `priv`. `priv` is a string that if present must name a registered priv that is required for the crafting recipe. Can anyone think of a reason privs might be a table that requires multiple privs? I don't think I can. Anyway in case logic of that level is needed, a callback `can_craft(recipe, crafter)` or similar would be needed, but I don't think we need to go to that level.

Refs
^(lua_api.txt, it was line 7101 in 5.2)

**Comment by Thomas--S** [comment]
You're proposed solution may indeed be more comfortable, but the callbacks that are already available actually allow to implement your suggested behaviour.

See the following link for an example:  
https://github.com/Thomas--S/ts_police/blob/51b204f541ad826eb9b88a546ac6b830f82b5eba/init.lua#L292-L313

**Comment by sfan5** [comment]
As pointed out above the API already provides you with means to do this (and more). Closing.
