### ISSUE TITLE
A packet to notify the client about world coordinates shifting

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#10951]
## Problem

I'd like to decouple the server's coordinate system from the client's, so our clients and network protocol can continue to believe the world is a (62 km)³ cube, independent of the server's oponion about its world shape.

## Solutions

1. Server announces that the world origin will very soon move to a new position, relative to its old position.
1. Client acknowledges that the offset is big enough to be distinguishable from nearby stuff (makes sense later below), and it has started preparing for that change.
1. Client re-labels cached chunks, drops those that are outside its horizon cube, does other preparations.
1. Client acknowledges that it is ready to accept the new origin, begins auto-translate grace phase (defined below).
1. Server starts speaking in the new coordinates, begins auto-translate grace phase.
1. As soon as the client sees auto-translation grace triggering, it starts speaking in the new coordinates as well.

The auto-translate grace phase is a short duration of time in which coordinates that are too far away to seem useful, are deened to be late-arriving old packets and are translated to the new offset.

## Alternatives

* Use bigger numbers in lots of other network packets. Would waste lots of bits all the time.

**Comment by rubenwardy** [comment]
Thanks for the suggestion, but I think this is too complicated for your usercase. We need to be selective about the functionality we include, more functionality is harder to maintain and is more likely to have bugs.

If the server sends a mapblock, it'll overwrite the client's mapblock. When the player gets near the edge, I suggest teleporting them to the center and sending the mapblocks again. If you pre-send the mapblocks, the impact would be minimised - it would look more like an anti-cheat position reset

**Comment by mk-pmb** [comment]
Thanks for the idea, I'll try that then.
