### ISSUE TITLE
There should be a compiled version RUN_IN_PLACE for download as tar.gz or zip

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#10958]
a compiled RUN IN PLACE variant oft minetest should be offered for download on every release.

self-compiling actually produces many errors if you cant provide irrlicht src files over the default repos.
disabling client build in make process wont help, too, so compiling on centos 8 (stream) is very difficult without getting irrlicht sources.

goal for this RUN IN PLACE build is that all program+data should stay in /home/gameserveruser/minetest (and optional in a database managed by an DBMS like postgresql).

RUN IN PLACE is already supported if compiling by yourself.

**Comment by codeandfix** [comment]
i tried to use it, it was terrible as i was not able to edit files inside snap with WinSCP access.
also it did not go complete to /home/gameserveruser which makes it hard to remember all the important data to backup years later.

**Comment by Calinou** [comment]
I suggest using a Docker container if you want to host a server on a machine that can't compile recent Minetest versions.

**Comment by codeandfix** [comment]
why do you doubt, a common build wont work on any distribution?
in this case, the irrlicht src depedencies should be removed or changed so that its much easier to build.

**Comment by Calinou** [comment]
> in this case, the irrlicht src depedencies should be removed or changed so that its much easier to build.

Did you pass `-DBUILD_CLIENT=0 -DBUILD_SERVER=1` to CMake? Last time I checked, you don't need Irrlicht to build the server.

**Comment by sfan5** [comment]
You do need Irrlicht to build the server, but *only* the headers.
That means you can (and should) download irrlicht-1.8.4.zip, extract it somewhere and run cmake with `-DIRRLICHT_INCLUDE_DIR=.../irrlicht-1.8.4/include`.

**Comment by codeandfix** [comment]
i have the irrlicht-devel package from centos, so i think i have headers except source inside /usr/include/irrlicht/irrlicht.h
irrlicht-devel 1.8.4 from epel-testing
but there are some troubles when compiling without src dir.

maybe i need to run sth. like make clean..
