### ISSUE TITLE
Upgrade build to Modern CMake

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest#10953]
## Problem
There's no major problem with the existing build system that I know of. It works well; however, it is not as modular and maintainable as CMake that follows modern practices.

## Solutions
I am teaching myself CMake and I'm working on build systems wherever I have an opportunity. I am offering to modernize the current build system, if there is sufficient interest. A major caveat might be that the version might need to be increased depending on how far I take it and some package managers (Debian Apt to name one) don't provide very updated versions of CMake, but some things can be improved without increasing the version.

## Alternatives

The alternative is to not upgrade it.

## Additional context

I can provide an example find script that I have written for GMT that should work fine under the current CMake version to demonstrate the concept of modern CMake.

**Comment by sfan5** [comment]
Can you give some examples / explanations of what modernizations you think should be done to our build system?

> A major caveat might be that the version might need to be increased depending on how far I take it

I recently increased the minimum version to 3.5 (to get rid of some warnings only) and that version looks like about as far as we can go without impacting compatibility negatively.

**Comment by JosiahWI** [comment]
Yeah gladly. Modern structure of CMake is designed around targets, in contrast to using lots of variables. It keeps things concise and easy to understand, and perhaps most importantly, it has each target keep track of its parts and dependencies. For a practical example, the current FindGMT script makes variables that contain a library location and a include directory location. My new version takes those variables and creates a target GMT::GMT which keeps track of the library location, the include directory location, and any other settings you want to put on the target. Using that kind of structure gives a high level of flexibility while ensuring that each step has the specific requirements it needs and no extras.

**Comment by randomMesh** [comment]
> I recently increased the minimum version to 3.5 (to get rid of some warnings only) and that version looks like about as far as we can go without impacting compatibility negatively.

Debian Stable has _cmake 3.13.4_. Debian is known for ancient (but stable) software. I can't think of a distribution with an older version of cmake.

**Comment by JosiahWI** [comment]
That's a recent addition to Debian Stable. Debian 9 has a lower version (3.1 or 3.4?) I believe and Debian 8 is < CMake 3.0 I think. There might be concerns for systems that haven't updated to the new stable, although I assume most users would have. I don't know what versions Mac and Windows use.

**Comment by Calinou** [comment]
> I don't know what versions Mac and Windows use.

On Windows and macOS, the CMake versons can be updated at will, so you can generally run the latest version easily.

**Comment by JosiahWI** [comment]
Whatever versions may be available, I think it's mostly irrelevant to the general changes I'm proposing because targets are supported in CMake version 3.5. I think the best way to update the build would be to implement a target based structure with minimal changes to the rest of the CMake code, and update the find scripts to handle options in a uniform, predictable way. It can be done pretty quickly with a little effort, would work with the current version, and would be a foothold for anyone else who wanted to update parts of the build.

**Comment by sfan5** [comment]
Closing due to age. I think whatever we have currently is fine.
