### ISSUE TITLE
Left-handed keybinding support

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#10954]
## Problem

A left-handed player asked me if my mod could be "left-handed friendly" today, and long story short, this person explained to me it's very hard to use the mouse with your non-dominant hand, especially in fast-paced games like shooters. And, even if they change the keybinding, they can't remap the hotbar

## Solutions

It'd be cool to have a default keybinding on PC also for left-handed people. More precisely, looking at [this](https://raw.githubusercontent.com/vaemendis/qwaccent/master/images/qwaccent-layout.png):
* invert LMB/RMB
* PL:@ instead of WASD
* AUX1 on `[`
* hotbar goes =, -, 0, 9 etc. instead of 1, 2, 3, 4 etc. ~without mirroring it~

^ these are only a guess of mine trying to put my right hand as I had to do what I usually do with the left hand. Left-handed people know better than me

**Comment by rubenwardy** [comment]
Settings you requested:

```
keymap_left = KEY_KEY_L
keymap_backward = KEY_OEM_1
keymap_forward = KEY_KEY_P
keymap_right = KEY_OEM_7
keymap_special1 = KEY_OEM_4
keymap_place = KEY_LBUTTON
keymap_dig = KEY_RBUTTON
keymap_slot1 = KEY_KEY_5
keymap_slot2 = KEY_KEY_6
keymap_slot3 = KEY_KEY_7
keymap_slot4 = KEY_KEY_8
keymap_slot5 = KEY_KEY_9
keymap_slot6 = KEY_KEY_0
keymap_slot7 = KEY_MINUS
keymap_slot8 = KEY_PLUS
```

**Comment by Zughy** [comment]
It's not only a matter of keybinding: I think the hotbar first slot should start to count from the right, it's like it was mirrored

**Comment by rubenwardy** [comment]
Do you mean default item selection?

**Comment by SmallJoker** [comment]
The requested hotbar change is counter-intuitive. The leftmost key should trigger the leftmost slot, and vice-versa.
Mouse, and all keybindings can already be customized.
