### ISSUE TITLE
Check duplicate login before trying to connect to a server

### ISSUE THREAD

**Issue by kneekoo** [minetest/minetest#10957]
The client does all the loading up to 100%, then:

> An error occured:
> 
> Access denied. Reason: Another client is connected with this name. If your client closed unexpectedly, try again in a minute.

Duplicate logins should be checked in advance. Ideally, the user would be presented a Retry button that would only be enabled after a set amount of time. Or enabled but still denied (client-side) to connect before the cooldown is over, to avoid spamming the server.

**Comment by Zughy** [comment]
Solved by #11017
