### ISSUE TITLE
remember password

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#10965]
## Problem

the biggest problem in minetest is, that the password is not remembered.
i have to reenter my password again and again.

## Solutions

all userpasswords should be stored in the minetest local config.
like browsers password manager does but without a masterpassword.
this must be optional,
but in most cases player have their own computer or useraccount so its terrible to enter a password by hand.
also multiple playernames for testing etc should be storeable.
also multiserver credential support would be nice.

## Alternatives

allow favorite entries (not unique per host) with fixed username+password.
so i can choose   mainuser@host1  or testuser@host1  or griefer@host2 ;-)

**Comment by rubenwardy** [comment]
#1566
