### ISSUE TITLE
plus/minus keys work inconsistently

### ISSUE THREAD

**Issue by TheTermos** [minetest/minetest#10969]
##### Minetest version
```
minetest-5.4.0-7832b6843-win64
```

##### OS / Hardware
Operating system: win 8.1 pro
Dell Latitude E5530

##### Summary
plus/minus keys seem to work inconsistently now:
- numpad +/- and normal +/- seem to be recognized as different now, but it's not that numpad +/- don't always work, they still work sometimes.
- with this keyboard, the 'normal' plus key is only accessible with shift depressed, even though MT menu lists the keybinding as +, it's actually '=' - if I press actual + (with shift held) nothing happens (again, most of the time, sometimes it registers the key as plus)
- with this keyboard the minus key is accessible by a single press, but in MT it only works with shift depressed, which is actually an underscore (again, this behavior changes)

It seems that pressing either numpad +/- messes up 'normal' +/- key recognition.
Entering the menu briefly seems to reset this behavior and after that the normal +/- keys seem to work regardless if shift is held.
Numlock mode doesn't seem to make a difference.

**Comment by sfan5** [comment]
On my keyboard + and - do not require shift, but I can confirm one inconsistency: shift + and shift - work identically to + and - but they shouldn't (those keys produce `*` and `_` respectively).

**Comment by sfan5** [comment]
This fixes the inconsistency for me, does it fix them for you?

```diff
diff --git a/src/client/keycode.cpp b/src/client/keycode.cpp
index ce5214f54..e5fce572e 100644
--- a/src/client/keycode.cpp
+++ b/src/client/keycode.cpp
@@ -91,10 +91,6 @@ static const struct table_key table[] = {
        DEFINEKEY3(X)
        DEFINEKEY3(Y)
        DEFINEKEY3(Z)
-       DEFINEKEY2(KEY_PLUS, L'+', "+")
-       DEFINEKEY2(KEY_COMMA, L',', ",")
-       DEFINEKEY2(KEY_MINUS, L'-', "-")
-       DEFINEKEY2(KEY_PERIOD, L'.', ".")
 
        // Keys without a Char
        DEFINEKEY1(KEY_LBUTTON, N_("Left Button"))
```

**Comment by TheTermos** [comment]
I'm on different hardware now and don't ever have the environment configured here so I can't  verify this easily.

As to regression:
+/- working regardless if shift is depressed is not a regression (works the same in 5.0.3)
numpad +/- messing things up is a regression (numpad +/- works fine with 5.3.0)

**Comment by waxtatect** [comment]
for me +/- keyboard keys work fine. With shift pressed and +, view range increases, and doesnt decrease with shift pressed and - 
about numpad, pressing +/-, increase/decrease only once the view range, pressing again has no effects. Open/Close any formspec i tried so far makes the numpad +/- works again, also sending a message in chat "fix" it too
