### ISSUE TITLE
e-mail account verification for new players (+ captchas)

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#10963]
## Problem

players can register anonymous. thats good!
but many griefers are out there and disturb gaming.
especially in creative worlds, this is a big problem.
by adding e-mail verification and captchas (one time per first registration) we could steal some time from griefers.

## Solutions

a) add optional e-mail address to players account & force e-mail confirmation
b) protect a by captcha to reduce spam and automatic account creation
c) give users with verified email a special priv to show the mods or admin, that this user is a bit more trustworthy than an anonymous user.

## Alternatives

add a time rating, that a player needs to spend n hours playing (active) on the server.
this should be considered as an option to the solution above.
so if griefers have to verify first and have to spend much time, they tend to stop griefing.
also add an option to rollback and delete griefer accounts at once.
actually you have to fly around in the world, check the node coord and watch debug.log for the player who made this "grief".
if you found out the name, you can rollback him.
this should be much easier, like touching a griefed node inside the game as admin and then showing the node history on player basis. means we need an complete changelog for every node with the player or abm or abm activated by a player.

**Comment by SmallJoker** [comment]
This is best left to servers/modders to implement a verification system on their own which than could also make use of commercial/closed-source APIs. For griefing prevention, you should make use of an area protection mod and the rollback feature (see `/help` and `settingtypes.txt`).

**Comment by 0-afflatus** [comment]
Again, this is not an engine issue.

**Comment by rubenwardy** [comment]
Here's a mod for this: https://forum.minetest.net/viewtopic.php?p=307359

It does a bit more than asked for

**Comment by codeandfix** [comment]
rubenwardy, for your mod, i need a "trust-server" or rely on a third party trust server?
i prefer to keep all playerdata on my server only. seems that its possible, but a bit confusing, as readme talks about registering server+server ip. normally server ip wont change or needs to be trusted. it is just the player who is "bad" ;-)
