### ISSUE TITLE
Convert Minecraft maps to Minetest worlds

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest/minetest#10972]
## Problem
How do Convert Minecraft maps to Minetest worlds
* I'm dumb and don't know code
## Solutions

https://forum.minetest.net/viewtopic.php?f=12&t=13709

## Alternatives

https://forum.minetest.net/viewtopic.php?p=211743
## Additional context
Enable GitHub [Discussions](https://docs.github.com/en/github/administering-a-repository/enabling-or-disabling-github-discussions-for-a-repository)  for a repository

**Comment by rubenwardy** [comment]
This can and should be done using a third-party tool. We don't have any intention of supporting this

See https://forum.minetest.net/viewtopic.php?f=12&t=13709 as you've linked

**Comment by Pantyhose-X** [comment]
> This can and should be done using a third-party tool. We don't have any intention of supporting this
> 
> See https://forum.minetest.net/viewtopic.php?f=12&t=13709 as you've linked
The conversion has failed.Bug https://forum.minetest.net/viewtopic.php?f=12&t=13709 
* We can't give up Minecraft maps，This is also Minetest user number can not exceed Minecraft is the reason
* You can open a new project Repositories
* Make a Convert Minecraft map to Minetest map tool
