### ISSUE TITLE
Add database backends for mod_storage

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#10978]
## Problem

Mod storage is currently stored using JSON files (one per mod). This is bad for performance if mod storage grows significantly. Mods like sban have accordingly started to require their own database backend.

## Solutions

Convert mod storage to use the available database backend for performance boost.

## Alternatives

None. We have a database, so we should use it for the simple key-value mod storage.

**Comment by AFCMS** [comment]
This feature is NEEDED. It will avoid the pain of messing with insecure envs and libraries.

**Comment by rubenwardy** [comment]
This doesn't affect the API of mod storage

A related issue is the one about adding a database API for mods to use

**Comment by AFCMS** [comment]
ok srry xD

**Comment by AFCMS** [comment]
> A related issue is the one about adding a database API for mods to use

You mean this issue? 
https://github.com/minetest/minetest/issues/10371

**Comment by rubenwardy** [comment]
Yes that's the one

**Comment by appgurueu** [comment]
@TurkeyMcMac if you want to implement this for SQLite, you might want to abstract the `PlayerMetaData` implementation, which already properly implements SQLite as a backend for a similar k/v store.
