### ISSUE TITLE
Crashed when start app

### ISSUE THREAD

**Issue by c4dr01d** [minetest/minetest#10977]
##### Minetest version

```
5.2.0.26
```

##### OS / Hardware

Operating system: Android 10
CPU: HiSilicon Kirin 9.7.0

GPU model:
OpenGL version:

##### Summary

I download minetest and install it from app store, open the app, give permission let minetest can access storage, then crashed
##### Steps to reproduce

1. Download app from F-Droid
2. Install
3. Open minetest at launcher
4. Give access storage permission
5. Crashed...

**Comment by rubenwardy** [comment]
F-Droid is outdated due to a build issue: #10529 

This bug should be fixed in 5.3.0, which is available from Google Play or as an APK from the Minetest website
