### ISSUE TITLE
Audio: Error opening file for decoding

### ISSUE THREAD

**Issue by kneekoo** [minetest/minetest#10979]
Minetest 5.3.0 **and** 5.4.0
Linux Mint 20.1
Using the stable PPA: ppa:minetestdevs/stable

> 2021-02-18 19:26:06: INFO[Main]: 
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.1.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.2.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.3.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.4.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.5.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.6.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.7.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.8.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.9.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.0.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.1.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.2.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.3.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.4.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.5.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.6.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.7.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.8.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.9.ogg for decoding
> 2021-02-18 19:26:06: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.ogg for decoding

I'm not sure about 5.3.0, but in 5.4.0 I also noticed this after the failed audio files opening:
> 2021-02-24 00:21:06: INFO[Main]: OpenALSoundManager: "main_menu" not found.

Minor thing, but if the game first tried to check the existence of the /sounds/ directory, there would be less attempts to open files. For whatever reason, the PPA packages don't include sounds.

**Comment by kneekoo** [comment]
Tested again from the same PPA, under Linux Mint 20.2, with Minetest 5.4.1.

`minetest --info`

> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.0.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.1.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.2.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.3.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.4.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.5.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.6.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.7.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.8.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.9.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /home/nicu/.minetest/sounds/main_menu.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.0.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.1.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.2.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.3.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.4.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.5.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.6.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.7.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.8.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.9.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: Audio: Error opening /usr/share/minetest/sounds/main_menu.ogg for decoding
> 2021-07-15 03:26:39: INFO[Main]: OpenALSoundManager: "main_menu" not found.

**Comment by sfan5** [comment]
I don't know why these log messages exist but they certainly do not signal a error, there is no bug.

**Comment by kneekoo** [comment]
The files do not exist and the game tries to open them. So the solution is to either add the files to the game, or the game should not try to open them.

**Comment by sfan5** [comment]
Of course it should try to open them, these files can be optionally installed by the user.

**Comment by kneekoo** [comment]
But why not check if the sounds directory exists at all, as well as the files individually? If it's not worth doing that, it's not worth logging the failed attempts either.
