### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#10982]
Please add undo last action(or two last actions). Shoud be enough for 99% cases

**Comment by NathanSalapat** [comment]
rollback is a thing....
`Rollback
--------

* `minetest.rollback_get_node_actions(pos, range, seconds, limit)`:
  returns `{{actor, pos, time, oldnode, newnode}, ...}`
    * Find who has done something to a node, or near a node
    * `actor`: `"player:<name>"`, also `"liquid"`.
* `minetest.rollback_revert_actions_by(actor, seconds)`: returns
  `boolean, log_messages`.
    * Revert latest actions of someone
    * `actor`: `"player:<name>"`, also `"liquid"`.`
