### ISSUE TITLE
Minimap modes aren't translated

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#10987]
##### Minetest version

```
5.4 rc1
```

##### OS / Hardware

Operating system:windows 7
CPU:

GPU model:
OpenGL version:

##### Summary

Minimap modes shows only in english. For example, russian po file contains: 
#: src/client/minimap.cpp
msgid "Minimap hidden"
msgstr "Миникарта скрыта"
Yet the translated string doesn't appear
I tested with de, es, fr, ru language settings
##### Steps to reproduce

Start minetest with another language than english
Join a game
Press v and read the differents minimap modes in english

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/051e4c2b00a30c496b5545a6f0b01c9a14e937a4/src/client/minimap.cpp#L333
They're marked in the script for translating, but aren't actually translated by gettext:
https://github.com/minetest/minetest/blob/051e4c2b00a30c496b5545a6f0b01c9a14e937a4/src/gettext.h#L43

Replacing `N_` with `_` (normal gettext translator) should work. I will test this later.

**Comment by SmallJoker** [comment]
bce875fad
