### ISSUE TITLE
String too long for serializeString(16) caused by mod

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#10981]
```
2021-02-19 19:48:01: ERROR[Server]: An unhandled exception occurred: String too long for serializeString
2021-02-19 19:48:01: ERROR[Server]: In thread 8:
2021-02-19 19:48:01: ERROR[Server]: /home/stefan/mt-build/build/minetest_64/minetest/src/server.cpp:7d: run: A fatal error occurred: String too long for serializeString
```
Client version: 5.3.0
Mode: Singleplayer, no cmd.exe, no compilation

I was making a village with ```mcl_villages:tool``` [(MineClone2)](https://git.minetest.land/MineClone2/MineClone2) and i clicked on a villager. Then, i was just about to do some command, when i saw some error output and the game window closed abruptly. I dont know whether this has to do with the game or the client/server.

This happened on a
Intel Core i7-6800 x64 bit OS and processor.

EDIT: maybe worth noting im on Windows 10 Enterprise version 1909 build 18363.1316

**Comment by SmallJoker** [comment]
Can you reliably reproduce this error? If so, please run Minetest in `windbg` to get a sane stack backtrace. I don't think a minidump file is created, but you could check whether there's a crash report generated within the working directory.

**Comment by TechDudie** [comment]
First I’ll try to reproduce it, don’t think it’ll take that long.

**Comment by TechDudie** [comment]
yep it happened again

**Comment by TechDudie** [comment]
though this time i had a village, i did click on them, but i was flying away and entering commands when this happened.

**Comment by TechDudie** [comment]
I don’t think I can get minetest running in windbg due to certain technical and non-technical parent-related limitations. :(
