### ISSUE TITLE
Movement of attached player is jerky sometimes.

### ISSUE THREAD

**Issue by TheTermos** [minetest/minetest#10985]
##### Minetest version
```
minetest-5.4.0-7832b6843-win64
```

##### Summary
#10952 seems to have fixed the biggest problems, particularly player attachments detaching, but there's still room for improvement.
Player attachment's movement is sometimes jerky, probably based on the sequence of objects on the object list.

##### Steps to reproduce
1. create an entity with this callback:
```
on_rightclick = function(self,clicker)
	local pos = self.object:get_pos()
	local at1 = minetest.add_entity(pos,self.name)
	at1:set_attach(self.object,nil,{x=0,y=0,z=-20})
	clicker: set_attach(at1,nil,{x=0,y=10,z=0})
	self.object:set_velocity({z=30.0,y=0,x=0.0})
end,
```
2. spawn your entity and immediately right click it. player should attach and they start moving smoothly.
3. spawn your entity, then leave the game, then log in again and right click the entity, now the movement is jerky.

Now we know that it is expected that an attachment's position equals the parent's position, but based on the sequence on the list, attachment's position may be one server step late, so server position updates are outdated sometimes, so the hypothesis is this is the cause of the issue.

Maybe instead of attachments setting their own position, the parent should set position on behalf of their children recursively? That should get them in sync.

**Comment by lhofhansl** [comment]
This is pretty annoying when this happens. IMHO it makes moving, attached entities useless.

**Comment by lhofhansl** [comment]
This possibly has to do with different sort orders on client and server.

As a test I used an regular map and I have not observed this issue since.

At same time I haven't proved to myself that this actually is the problem... Maybe someone else can try.
@TheTermos @sfan5 

```
diff --git a/src/activeobjectmgr.h b/src/activeobjectmgr.h
index aa0538e60..034f32e7a 100644
--- a/src/activeobjectmgr.h
+++ b/src/activeobjectmgr.h
@@ -19,7 +19,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,

#pragma once

-#include <unordered_map>
+#include <map>
#include "irrlichttypes.h"

class TestClientActiveObjectMgr;
@@ -38,7 +38,7 @@ class ActiveObjectMgr

T *getActiveObject(u16 id)
{
-               typename std::unordered_map<u16, T *>::const_iterator n =
+               typename std::map<u16, T *>::const_iterator n =
m_active_objects.find(id);
return (n != m_active_objects.end() ? n->second : nullptr);
}
@@ -62,5 +62,5 @@ class ActiveObjectMgr
return id != 0 && m_active_objects.find(id) == m_active_objects.end();
}

-       std::unordered_map<u16, T *> m_active_objects;
+       std::map<u16, T *> m_active_objects;
};
```
