### ISSUE TITLE
Mod/game translations fail for 3-letter language codes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#10988]
##### Minetest version
```
5.4.0-dev
```

##### Summary
If you translate a game or mod into any language with a 3-language letter code (e.g. `jbo` for Lojban), Minetest will fail.

##### Steps to reproduce
1. Go to Minetest Game
2. Copy `mods/butterflies/locale/butterflies.de.tr` to `mods/butterflies/locale/butterflies.jbo.tr`
3. (optional) edit the translation file  so you can see differences
4. Set Minetest language to `jbo`
5. Force your system langauge to be `jbo` (to make sure the correct translation file will be used)
6. Restart Minetest
7. Start Minetest Game in singleplayer

(but you can of course use any other 3-letter language code)

Expected: Minetest Game starts and applies the correct translation
Actual result: Game startup fails with this error: “Access denied. Reason: Server authentification failed. This is likely a server error.”

##### Notes
Minetest itself deals with 3-letter codes just fine (engine translation). There is a `jbo` translation for Minetest. 
However, it seems that when it comes to games and mods, Minetest has a hiccup.

Random guess: Somewhere in the code there is a hardcoded assumption that language codes for game/mod translations can only be 2 letters long.

**Comment by sfan5** [comment]
wfm

![Bildschirmfoto_2021-02-22_17-55-24](https://user-images.githubusercontent.com/1042418/108741716-4b2fb180-7537-11eb-8bfb-2754dec106bb.png)

> 5. Force your system langauge to be jbo (to make sure the correct translation file will be used)

This step should not be necessary.

**Comment by Wuzzy2** [comment]
Then I don't know what I did wrong.

Maybe someone else has this bug, too? More testing appreciated.

I did it on a GNU/Linux system by the way.

**Comment by srifqi** [comment]
I can _not_ reproduce this bug, too. I am running Minetest (recent `master` branch) on Windows 10 (10.0.18363).

![screenshot showing Lojban translation](https://user-images.githubusercontent.com/4017302/108833766-deccb500-75ff-11eb-9fa2-115ec9806345.png)

**Comment by Wuzzy2** [comment]
After I recompiled the 5.4.0 release, it worked flawlessly on my side.
So looks like I used some old version or something like that.
Closing ...
