### ISSUE TITLE
Calling hud_change right after hud_add doesn't change hud

### ISSUE THREAD

**Issue by savilli** [minetest/minetest#10996]
##### Minetest version
```
5.5.0-dev-b5eda416c
```

##### OS / Hardware
Operating system: Linux Ubuntu 20.10
CPU: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz

##### Summary
Calling hud_change right after hud_add doesn't change hud

##### Steps to reproduce
-    Create a mod with this code:
```lua
minetest.register_chatcommand("test", {
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		if not player then
			return false
		end
		local def = {
			hud_elem_type= "text",
			text = "OLD",
			number = 0xFFFFFF,
			position = {x = 0.5, y = 0.6},
		}
		local id = player:hud_add(def)
		player:hud_change(id, "text", "NEW")
		return true
	end
})
```
-    Use /test command
-    See OLD on the screen instead of NEW

**Comment by savilli** [comment]
We search for hud in m_hud_server_to_client here https://github.com/minetest/minetest/blob/b5eda416cea3157ae3590fb7d229cd2cd17c3bf9/src/network/clientpackethandler.cpp#L1134 before it is added here https://github.com/minetest/minetest/blob/b5eda416cea3157ae3590fb7d229cd2cd17c3bf9/src/client/game.cpp#L2638 so handleCommand_HudChange fails

**Comment by SmallJoker** [comment]
Makes sense. Even though the packets are guaranteed to be sent & received in order
https://github.com/minetest/minetest/blob/b5eda416cea3157ae3590fb7d229cd2cd17c3bf9/src/network/serveropcodes.cpp#L199-L203
.. the client event queue isn't processed immediately.
