### ISSUE TITLE
Android: Selecting an item in craft menu shows it stuck in last touch location instead of showing it in proper place

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#10993]
##### Minetest version

```
5.4.0 (Android, installed from the play store)
```

##### OS / Hardware

Operating system: Android 7.0
CPU: HiSilicon Kirin 650

##### Summary

Selecting an item on crafting menu by clicking and releasing the finger shows it being stuck on last touch location. Dragging and item and releasing the finger shows the same behavior too.
Video showing the bug described above: https://youtu.be/01zpimT3MXs

##### Steps to reproduce

1. Start minetest on device with Android 7.0
2. Open a world or connect to server
3. Open crafting menu, drag or select an item
4. Observe the item getting stuck on last touch location, as shown in video above

**Comment by MoNTE48** [comment]
This is the correct behavior and I am glad that the item no longer hangs in the upper left corner (at pos 0,0)

**Comment by AntumDeluge** [comment]
> This is the correct behavior and I am glad that the item no longer hangs in the upper left corner (at pos 0,0)

I agree that this is the desired bahavior.
