### ISSUE TITLE
Better support for in-game LUA source editing in formspecs

### ISSUE THREAD

**Issue by hlqkj** [minetest/minetest#11009]
## Problem

Some great mods are providing in-game LUA scripting (e.g. mesecons, pipeworks, advtrains). Since recently there were no effective ways to provide a decent source code editor, until monospaced font styling was introduced for the textarea element, that has been an huge improvement.

There still are a few (minor) things that could be improved in this context, and since there is/will be a huge formspec rework I thought to drop a few ideas, like:

- make the editor accept tab input (tab keys moves the focus now)
- display line numbers
- perhaps some very basic form of syntax highlighting (I see this very low priority though)
- render whitespaces where appropriate (even lower priority)
- ...

## Solutions

I see two options available:
- add some source code editing-oriented features to the textarea element, to be enabled via styling, or
- create a new specific formspec element starting from the current textarea.

**Comment by v-rob** [comment]
* Making textarea accept tabs is likely pretty easy.
* Line numbers wouldn't be too difficult.  However, textareas already have word wrapping issues, so the word wrapping would need fixing before this (#10853 might be good there)
* Syntax highlighting is more tricky (both parsing and changing color/style of text in the middle), but not impossible.
* Not sure what rendering whitespace means

Theoretically, hypertext could also be modified to have editing capabilities, but it has quite a few problems of its own.

However, apart from the current formspecs, the formspec replacement will certainly have rich text abilities (i.e. changing the style of text in the middle), so syntax highlighting will be much easier.

**Comment by rubenwardy** [comment]
I think 1) shouldn't be too hard and could be done

The rest of these are low priority and should wait until a formspec replacement

**Comment by hlqkj** [comment]
>     * Not sure what rendering whitespace means

I mean rendering whitespaces in such places where they should be seen, like for example trailing spaces before line endings. As said this (along with other things) would really be lowest priority, after all minetest is not meant to be an IDE!

What this issue tries to address is mainly 1) decent in-game editing and 2) being able to at least reference lines (hence line numbers) to help understanding each other when two or more players are working on the same component, like the case where someone is tutoring a newbie.

**Comment by lychees** [comment]
> * Line numbers wouldn't be too difficult.  However, textareas already have word wrapping issues, so the word wrapping would need fixing before this ([Add WordWrapper util (with unit tests, ellipsis truncation, and fixes) #10853](https://github.com/minetest/minetest/pull/10853) might be good there)

I think the IDE's editor probably doesn't need this feature. :)

![UO@X %QWNVMB4VE6@9Q5B}T](https://user-images.githubusercontent.com/2507027/215961473-e89ce47d-50cd-4340-806e-850af77e2940.png)

There is a mini IDE implementation in [a famous javascript meta game —— untrusted](https://github.com/AlexNisnevich/untrusted).
It looks like it was created by using lower-level elements rather than text textarea.
