### ISSUE TITLE
Scale mouse sensitivity when changing FOV or zooming

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#11005]
## Problem

When changing the FOV the mouse sensitivity does not change. This means that the mouse feels a lot more sensitive when zoomed in. This can make it hard to aim when looking down the scope of a sniper rifle in a weapons mod for example. It also feels wrong when using items such as binoculars from Minetest game.

## Solutions

Scale the mouse sensitivity with the FOV. I propose it is scaled by multiplying with `tan(vertical_fov / 2)`. That should preserve the exact mouse feel when changing the FOV. I also propose that this change is applied in a way that the mouse sensitivity is exactly the same from before this is added when playing with 72 degree FOV (which is the default value) and 16:9 aspect ratio. That would minimize the disruption of existing mouse sensitivity settings.

## Alternatives

The mouse sensitivity could be changed only when zooming and not when switching FOV in general. I do however think it is best to do it when changing the FOV in general since different servers could have different FOV settings and changing the FOV settings should not affect how responsive the mouse feels.

## Additional context

I've already made a patch for this for people to try out. Going to create a pull request soon.

**Comment by ryvnf** [comment]
The pull request is there for people to try it out. It also should not matter if vertical or horizontal FOV is applied in the formula.

`tan(vertical_fov / 2) / tan(horizontal_fov / 2)` should be a constant for the same aspect ratio.

**Comment by Soupborsh** [comment]
Hello, touchscreen also needs this. It is almost unusable at the moment.

Example with ranged weapons:
https://youtu.be/g5_vN5ryiR8
