### ISSUE TITLE
Move view angle while breaking or punching nodes

### ISSUE THREAD

**Issue by Thewisem** [minetest/minetest#11003]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: android 7 Nougat
CPU: Samsung Exynos

GPU model:
OpenGL version:

##### Summary

I can't change the direction I look at while punching. I have to pick either punching or changing my viewpoint. I wish to do both

##### Steps to reproduce

1) Open the app and click on the world
2) Punch nothing
3) Use another finger to change viewpoint

**Comment by SmallJoker** [comment]
Could it be that the crosshair is enabled? If so, disable it in the main menu (extended) settings and re-try.

**Comment by Thewisem** [comment]
Sorry didn't have any crosshairs

**Comment by Thewisem** [comment]
When I press for punch and move ky finger

**Comment by Thewisem** [comment]
It stops punching but doesn't move the direction player is facing

**Comment by MoNTE48** [comment]
This is the correct behavior. The behavior you're asking is not comfortable, trust me.
@SmallJoker Not a bug! Question or Feature request.

**Comment by Thewisem** [comment]
Is it an engine limitation or implementing it is extremely hard?

**Comment by wwar-XeStro** [comment]
What makes the android controling too hard is the equivalent of left-clicking in PC....

I think it'd be way easier if they add an option to add a button on the screen + crosshair that button will work as left clicking....
Or if #11404 gets looked at :þ
