### ISSUE TITLE
Game is only in bottom 3/4th of the screen

### ISSUE THREAD

**Issue by Nv7-GitHub** [minetest/minetest#11021]
##### Minetest version

```
Minetest 5.4.0 (OSX)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
```

##### OS / Hardware

Operating system: MacOS
CPU: Intel Core i7

GPU model: Intel Iris Pro 1536 MB
OpenGL version: How do I find this?

##### Summary
When I updated to minetest 5.4, the display was only showing up in the bottom left quarter. All the buttons still work as if the screen was normal, so if I put my mouse in the middle of my screen, buttons in the middle of the minetest quarter get hovered over/pushed down. I have attached an image.
<img width="1440" alt="Screen Shot 2021-03-04 at 2 04 47 PM" src="https://user-images.githubusercontent.com/50369270/110037407-37343e80-7cf3-11eb-816f-fb1934ea977a.png">

##### Steps to reproduce
This issue is only occurring when I update minetest to minetest 5.4

**Comment by rubenwardy** [comment]
Fixes #10654
