### ISSUE TITLE
Building attempts to write into the bin directory in the source code.

### ISSUE THREAD

**Issue by Golutazem** [minetest/minetest#11026]
stable-5
commit 07903949ec329c4856e15a020bb3c48f851405d8
(Presently current)

Building attempts to write into the bin directory in the source code rather than in the build or object directory. The source code can be kept clean of build files. Some procedures can require it. The directory may be read-only.

**Comment by SmallJoker** [comment]
> Some procedures can require it

.. for example? The build system on GitHub and Travis CI has no problems with that. It's also convenient for `RUN_IN_PLACE=1` builds to run them directly from the output directory (same directory structure, all files present).

Relevant:
https://github.com/minetest/minetest/blob/ac8ac191691a13162667314358e96f07a65d0d1a/src/CMakeLists.txt#L529

**Comment by sfan5** [comment]
If the concrete problem is that your source folder is read-only I'm sure we can add some code that checks and avoids that.

**Comment by rubenwardy** [comment]
It could also be a CMAKE param. I prefer the current behaviour

**Comment by Golutazem** [comment]
Usually all necessary files for running are copied or linked to the build directory. I ran into it this time being 1 of 2 users working on it and building it, i did not have write permission into the other person's source directory.

**Comment by rubenwardy** [comment]
if multiple users are working on it, you should have different clones of the source code

**Comment by sfan5** [comment]
Ultimately this is a feature since Minetest will not run outside the source folder unless it's installed system-wide (`RUN_IN_PLACE=0` only).
