### ISSUE TITLE
Only show mod.conf warnings for enabled mods

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#11037]
> Shouldn't such warnings only be shown for mods that are activated for the world?
> 
> I get 720 lines on stderr just by starting a singleplayer game and closing immediately afterwards. And I don't want to maintain all the old mods that I have lying around.
> (I've set the deprecation handling mode to none now. :/)

_Originally posted by @Desour in https://github.com/minetest/minetest/issues/10753#issuecomment-792362906_

**Comment by rubenwardy** [comment]
Also: it might be worth removing the `name` warning, as it's less useful with ContentDB. And an officially linked tool to update mod.conf from depends.txt and description would be nice

**Comment by sfan5** [comment]
> Shouldn't such warnings only be shown for mods that are activated for the world?

Yes please

**Comment by wsor4035** [comment]
> Also: it might be worth removing the `name` warning, as it's less useful with ContentDB. And an officially linked tool to update mod.conf from depends.txt and description would be nice

https://github.com/wsor4035/mt_convert

**Comment by rubenwardy** [comment]
was implemented
