### ISSUE TITLE
Can´t start minetest libIrrlicht.1.9.0 not found.

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#11047]
##### Minetest version

```
Minetest 5.5.0-dev-75eb28b95-dirty (Linux)
Using Irrlicht 1.9.0mt0
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```
That works only after `export LD_LIBRARY_PATH=/usr/local/lib`.
##### OS / Hardware

Operating system: Ubuntu 18.04.5 LTS i686
CPU: Intel i5-7500T (4) @ 3.300GHz

GPU model: NVIDIA GeForce GTX 1070 Mobile
OpenGL version: 4.6.0 NVIDIA 390.141

##### Summary

If I try to run minetest from /usr/local/bin I get the
`minetest: error while loading shared libraries: libIrrlicht.so.1.9: cannot open shared object file: No such file or directory`
error. After `export LD_LIBRARY_PATH=/usr/local/lib` minetest starts without problems.
How can I set the path correctly?
##### Steps to reproduce

It begins with not compiling anymore this morning.
Tere wer two errors.
A. That minetest now uses an own fork off libIrrlicht.
After cloning, compiling and installing the new Files appear in /usr/local/lib and /usr/local/include/irrlicht.
B. That the Parameter OLD is deprecated and wont work anymore.
After commenting out the Line 3 in the CMakeLists.txt The error was gone.
I´ve used this Command line to Configure minetest.
`cmake . -DENABLE_GLES=FALSE -DENABLE_GETTEXT=TRUE -DENABLE_REDIS=TRUE -DENABLE_FREETYPE=TRUE -DENABLE_SOUND=TRUE -DENABLE_IRRLICHT_INCLUDE_DIR=/usr/local/include/irrlicht -DENABLE_IRRLICHT_LIBRARY=/usr/local/lib/libIrrlicht.so -DENABLE_IRRLICHT_SOURCE_DIR=/usr/local/lib`
followed by make and sudo make install.

**Comment by sfan5** [comment]
`/usr/local/lib` should usually be in the default linker search path, if it isn't you can edit `/etc/ld.so.conf` and add it there (might have to run `ldconfig` for the change to take effect).

Alternatively for local usage I can suggest such a setup, no installation necessary:
```
cd irrlicht
cmake . -DBUILD_SHARED_LIBS=OFF
make
cd ../minetest
cmake . -DIRRLICHT_INCLUDE_DIR=$PWD/../irrlicht/include -DIRRLICHT_LIBRARY=$PWD/../irrlicht/lib/Linux/libIrrlicht.a
```

**Comment by JPRuehmann** [comment]
Thanks, that helped.
The path was in it but the libIrrlicht produced an linking error. (FileSystem)
after deleting the incorrect link and the App files in /usr/bin it works.
