### ISSUE TITLE
When loading a specific b3d model, minetest exits abnormally

### ISSUE THREAD

**Issue by Pevernow** [minetest/minetest#11046]
The extension of #11034 

Following his advice, I used blender to export the model to b3d format.

The exported model is loaded normally in blender.

But minetest exits directly when the model is generated.

I inspected "debug.txt" ,but there is nothing errors were found.

 ### How to test

Try loading the model in minetest and you will find the same error.

[untitled.b3d.zip](https://github.com/minetest/minetest/files/6108647/untitled.b3d.zip)

**Comment by Pevernow** [comment]
@SmallJoker What do you think of this problem?

**Comment by SmallJoker** [comment]
I think this is a segfault within Irrlicht.
```C++
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.

#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:312
#1  0x00007ffff7dd9eee in irr::io::CMemoryReadFile::read(void*, unsigned long) ()
   from <>/irrlicht/lib/Linux/libIrrlicht.so.1.9
#2  0x00007ffff7b8c1dd in irr::scene::CB3DMeshFileLoader::load() ()
   from <>/irrlicht/lib/Linux/libIrrlicht.so.1.9
#3  0x00007ffff7b8c790 in irr::scene::CB3DMeshFileLoader::createMesh(irr::io::IReadFile*) ()
   from <>/irrlicht/lib/Linux/libIrrlicht.so.1.9
#4  0x00007ffff7cb705a in irr::scene::CSceneManager::getUncachedMesh(irr::io::IReadFile*, irr::core::string<char, irr::core::irrAllocator<char> > const&, irr::core::string<char, irr::core::irrAllocator<char> > const&) () from <>/irrlicht/lib/Linux/libIrrlicht.so.1.9
#5  0x00007ffff7cb73b1 in irr::scene::CSceneManager::getMesh(irr::io::IReadFile*) ()
   from <>/irrlicht/lib/Linux/libIrrlicht.so.1.9
#6  0x000055555565eeb9 in Client::getMesh(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) ()
#7  0x00005555556a5c51 in GenericCAO::addToScene(ITextureSource*) ()
#8  0x00005555556705bc in ClientEnvironment::addActiveObject(unsigned short, unsigned char, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#9  0x00005555558e619f in Client::handleCommand_ActiveObjectRemoveAdd(NetworkPacket*) ()
#10 0x00005555556620fa in Client::ProcessData(NetworkPacket*) ()
#11 0x0000555555662332 in Client::ReceiveAll() ()
#12 0x0000555555668678 in Client::step(float) ()
#13 0x00005555556d51a3 in Game::run() ()
#14 0x00005555556d5f64 in the_game(bool*, InputHandler*, GameStartData const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, ChatBackend&, bool*) ()
#15 0x0000555555679399 in ClientLauncher::run(GameStartData&, Settings const&) ()
#16 0x000055555564c3b0 in main ()
```

**Comment by Pevernow** [comment]
How to fix it?

**Comment by NathanSalapat** [comment]
Have you tried re-exporting the file, or changing some of the export options? Everybody else is using .b3d for animated meshes without issue, which makes me think it's a problem with your file.

**Comment by sfan5** [comment]
The crash is fixed by https://github.com/minetest/irrlicht/commit/a3d848ff8b47bfe6b1649342a6ea54e095aa7af4 but that doesn't mean the model loads correctly, Irrlicht has some kind of problem reading file.

Which B3D exporter did you use?

**Comment by sfan5** [comment]
Okay I looked into this a bit more and I can confidently say that the file you posted is not a valid B3D file, the [brush names](https://github.com/joric/io_scene_b3d/blob/master/b3dfile_specs.txt#L108) are not null-terminated. Whatever exporter you used is doing it wrong.
