### ISSUE TITLE
Minetest - failed to generate "default_shader", addHighLevelShaderMaterial failed

### ISSUE THREAD

**Issue by mmmsued** [minetest/minetest#11041]
Making a new world with Minetest 5.4.0 (local, Windows 10) without any additional mods, but allways getting an error:

[debug.txt](https://github.com/minetest/minetest/files/6102019/debug.txt)

**Comment by SmallJoker** [comment]
Driver bug. Cannot fix in Minetest. Disable shaders as a workaround.
https://github.com/minetest/minetest/issues/10844#issuecomment-765059877

**Comment by mmmsued** [comment]
Thanks!

**Comment by TheTermos** [comment]
Confirmed. 
Win64, gpu Intel HD4000

Despite the message all shaders seem to work allright.

> Driver bug. Cannot fix in Minetest. Disable shaders as a workaround.

Quite a drastic workaround for a misleading error message.

**Comment by SmallJoker** [comment]
@TheTermos Please suggest solutions in #10844. This issue is a duplicate.

**Comment by sfan5** [comment]
> Despite the message all shaders seem to work allright.

The default_shader is in used by the node selection, are you sure that works?

**Comment by TheTermos** [comment]
> Please suggest solutions in #10844. This issue is a duplicate.

Ah ok, thought that the other one was closed as well

> The default_shader is in used by the node selection, are you sure that works?

Interesting.
Yes, it works as far as I can tell, both node selection modes, but the message pops up only if node outlining is selected.

**Comment by mmmsued** [comment]
I got the message right after starting the world as chat message without selecting anything ...

**Comment by TheTermos** [comment]
> I got the message right after starting the world as chat message without selecting anything ...

Sure, node outlining is the default.
Please enable shaders, turn on  node highlighting and report back if the message still appears.

**Comment by mmmsued** [comment]
Yes, that works. Thanks for helping!
