### ISSUE TITLE
Pixel font and GUI

### ISSUE THREAD

**Issue by Yutyo** [minetest/minetest#11043]
## Problem

Absence of a pixel font and GUI is an inferiority compared to the engine's overall success. Finding a readable free pixel font with decent unicode support was always a problem on the other hand.

## Solutions

I suggest [Pixel Font Mono](https://fontlibrary.org/en/font/pixel-operator), a public domain mono pixel font that has good unicode support.

About the GUI, its serious work. I am also among the people who whine about the logo but don't come up with a better one. That type of graphical updates generally require long time of brainstorming and I definitely get that after personally thinking how the Minetest GUI and logo can look better, like Minecraft but not being a copy of it.

PS: I don't write that to whine to other contributors to make a change. I will actually try something and make commits but currently I have an exam week + some homework weeks afterwards so I will be offline for a timespan.

**Comment by SmallJoker** [comment]
Duplicate of #8948. Closed due to inactivity and lack of support.

**Comment by sfan5** [comment]
For completeness the direction we'll want to move in here is to allow games to provide their own fonts (#10416).
