### ISSUE TITLE
Revisit Irrlicht workarounds

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#11040]
With Irrlicht 1.9 now merged, we should revisit workarounds for Irrlicht bugs that were added in MT and identify
1\) if these are still applicable and 2) consider fixing it directly in [minetest/irrlicht](https://github.com/minetest/irrlicht) and dropping the workaround.

Here are some candidates:
- [x] https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/client/game.cpp#L3921-L3938
- [ ] https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/client/content_cao.cpp#L1523-L1532
- [x] https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/client/shader.cpp#L513-L514
- [x] https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/gui/guiEditBox.cpp#L212-L229
- [x] https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/gui/guiChatConsole.cpp#L610-L614
- [x] Do we still need [intlGUIEditBox.cpp](https://github.com/minetest/minetest/blob/master/src/gui/intlGUIEditBox.cpp) at all?

This one likely requires a few more changes in Irrlicht:
(related: https://irc.minetest.net/minetest-dev/2020-12-19#i_5766693)
https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/client/sky.cpp#L843-L846

**Comment by hecktest** [comment]
This too:
https://github.com/minetest/minetest/blob/176f5866cbc8946c55a0a9bd0978a804ad310211/src/client/content_cao.cpp#L1537

**Comment by Zughy** [comment]
@sfan5 updates on this? Since a lot has been going on with MTirrlicht

**Comment by sfan5** [comment]
The points that are left are still applicable.

**Comment by sfan5** [comment]
Closing since the bone problems are being addressed.
