### ISSUE TITLE
Field and textarea background colours are broken

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#11051]
##### Minetest version

```
Minetest 5.5.0-dev-75eb28b95 (Linux)
Using Irrlicht 1.9.0mt0

```

##### Summary

The "borderless cyan text" field of devtest's /test_formspec has a background in 5.5.0-dev:

![image](https://user-images.githubusercontent.com/3182651/110718994-f0a18f80-8270-11eb-8a49-afea6884ba0b.png)

The same UI in 5.4.0 for comparison:
![image](https://user-images.githubusercontent.com/3182651/110719052-0c0c9a80-8271-11eb-9128-73755b6249d0.png)

##### Steps to reproduce

1. Open Minetest 5.5.0-dev
2. Join a devtest world
3. Run /test_formspec

**Comment by sfan5** [comment]
There clearly is a regression here, but the behavior is correct: https://github.com/minetest/minetest/blob/75eb28b95994781d52eb2c09303b1cd04e32b6c5/src/gui/guiFormSpecMenu.cpp#L1588-L1594

<pre>
	style[one_f2;border=false;textcolor=cyan]
	field[0,5.75;2.5,0.8;one_f2;Field Two;Borderless Cyan Text]
</pre>
The field has no border but it still has its' background, to get a result as in 5.4 the style should say bgcolor=transparent.

@v-rob is this correct?

**Comment by luk3yx** [comment]
The documentation says `border=false` is supposed to hide the background as well as the border:
https://github.com/minetest/minetest/blob/051bc9e6624c63c3612e041644ec587b328bae55/doc/lua_api.txt#L2886-L2891

The `bgcolor` style for fields/textareas is undocumented and seems to be ignored if it's anything other than `transparent`.

**Comment by rubenwardy** [comment]
Border is the irrlicht term for the 3d background of buttons and other built in skins

**Comment by v-rob** [comment]
I don't know why the `bgcolor=transparent` exists, it sounds inconsistent and is undocumented.  A quick search on GitHub turns up no repositories using it, so it can safely be removed, I think.

However, `border=false` should certainly remove the background.  In buttons, `border=false` doesn't remove the button outlines and gradient while leaving the color, and fields should be the same.  I don't know why the behaviour changed (including on our own `IGUIEditBox` derivatives -- it's probably either nerzhul's recent changes or the upgrade to Irrlicht 1.9), but it seems trivial to fix:

```C++
bool border = style.getBool(StyleSpec::BORDER, true);
e->setDrawBorder(border);
e->setDrawBackground(border);
```

**Comment by appgurueu** [comment]
Looking at the screenshot, black left arrows appear to be missing as well?

**Comment by kilbith** [comment]
Any progress on this? @v-rob

**Comment by sfan5** [comment]
> Looking at the screenshot, black left arrows appear to be missing as well?

Despite the confusingness this appears to be a feature: If you can't go back the left arrow disappears, if you can't go forwards the right one disappears.

**Comment by Git-Forked** [comment]
Is it possible those arrow buttons could be made a little bigger?  Sometime they are hard to click on accurately.
