### ISSUE TITLE
Player position not updating on the server

### ISSUE THREAD

**Issue by anon55555** [minetest/minetest#11057]
##### Minetest version
5.4.0

##### Summary
The client sometimes doesn't send the updated position to the server. I've confirmed with Wireshark that this isn't packet loss, no TOSERVER_PLAYERPOS packets are sent. I noticed this started happening after updating to 5.4.0.

**Comment by sfan5** [comment]
More information would be useful but I can guess what this is anyway.

#10885 was merged in 5.4.0, this doesn't work in the following situation:
* your client is 5.4.0
* your server is 5.3.0 (5.4.0 protects against mods messing this up)
* and **most importantly**: [2 years](https://github.com/minetest-mods/3d_armor/commit/a05eae3782acf680b28e1928c238ae53f15977e5) after it was fixed, you are still using a broken version of 3d_armor.

Not an engine bug either way.

**Comment by anon55555** [comment]
The server and client are both 5.4.0 and the server is running MineClone2.

**Comment by sfan5** [comment]
Looks like I guessed wrong then but you'll still need to provide proper reproduction steps.

**Comment by anon55555** [comment]
Oh it's a bug in my proxy, sorry.
