### ISSUE TITLE
"M" key not working on MacOS X french keyboard

### ISSUE THREAD

**Issue by b3** [minetest/minetest#11058]
##### Minetest version
```
Minetest 5.4.0 (OSX)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

##### OS / Hardware

Operating system: MacOS 10.15.7
CPU: 2,6 GHz Intel Core i7 4 cores
Keyboard: french layout keyboard

##### Summary

The `m` does not work at all on minetest. Pressing the `m` key does not produce any input.

##### Steps to reproduce

1. Start minetest
2. Try to input an `m` in any input
  1. in one of the menu field
  2. in the chat area
  3. during the game try to mute the game by pressing the `m` key

**Comment by sfan5** [comment]
Aside from likely being a duplicate, can you retest this with 5.5.0-dev? It might already be solved.

**Comment by b3** [comment]
Duplicate of which bug (I try to find one without success before filing this one)?

**Comment by sfan5** [comment]
I was thinking of #302 but that's specifically for Linux. Did you have a chance to test with 5.5.0-dev?

**Comment by b3** [comment]
I would like to try but am not sure how to compile it with the good packages (for instance adapted irrlicht version).
Any links will be appreciated.
Another question is which branch should I compile (which one is 5.5.0-dev I didn't find any called that way)?

**Comment by b3** [comment]
Unfortunately it seems that the trouble is still here with version 5.5.0-dev.

Here is what I tried: 

```bash
git clone https://github.com/minetest/irrlicht.git
cd irrlicht
cmake . -DBUILD_SHARED_LIBS=OFF
make -j4
cd ..
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
cmake . -DIRRLICHT_INCLUDE_DIR=../irrlicht/include -DIRRLICHT_LIBRARY=../irrlicht/lib/OSX/libIrrlicht.a
make -j4 package
unzip minetest-5.5.0-dev-osx.zip
open -a minetest.app
```

The `m` key is still not usable in any text field. Pressing the key still does not produce anything.

**Comment by b3** [comment]
Doing this test I tried all keys from my french keyboard. I found that two others keys do not work at all (typing on them do not produce anything). These are the two dead keys `^¨` and `` `£ `` (used on french keyboard to add stuff on letters such as in ô, ö or ò or simply access the back quote).

**Comment by b3** [comment]
Something very strange is that `M` (I mean `Shift`+`m`) is accessible in text fields and in the game itself and produce what is expected. The trouble seems to be the access to the key **alone**.

In text fields I am able to produce `M` but not `m`. In the game I am able to produce `M` (which seems to be binded to the `mute` function) but pressing `m` produce the same result as pressing `F10` (seems to be binded to access the console function).

**Comment by b3** [comment]
I can confirm some links with the #302 but switching the OS to using a US keyboard layout move the problem to another key: the `ù%` on the physical keyboard, which is the `'"` key on the US layout and is the one just right to the `m` physical key.

Same behavior: key alone does not produce anything but `Shift`+the key produce what is expected.

**Comment by Zughy** [comment]
Since Irrlicht development is now handled by Minetest core devs, please reopen this issue (if it still persists) in the specific repo: https://github.com/minetest/irrlicht
