### ISSUE TITLE
You can see inside player model 

### ISSUE THREAD

**Issue by danil275487** [minetest/minetest#11052]
##### Minetest version
5.4
##### OS / Hardware
Operating system: Windows 10 Pro 64-bit (10.0, Build 18363)
CPU: Intel Core i5-4310M (4 CPUs)
GPU model: Intel HD Graphics 4600 (integrated graphics)
DirectX version: 9, or 11 (running mt mainly on direct3d9)

##### Summary
Every sub-game I try to play doesn't hide the player model, wich means I will see the inside my own player model, wich makes the game unplayable, and only way to play is either in third person or manually remove the model.

##### Steps to reproduce
None, as far as I am aware.

##### Images
Game without player model (only visible if looking down)
![1](https://user-images.githubusercontent.com/78205681/110792546-9a3e4c00-8284-11eb-8a87-1f08b479059c.png)

Game with player model (looking straight)
![2](https://user-images.githubusercontent.com/78205681/110792727-ca85ea80-8284-11eb-83bd-68d90a3d1e29.png)

**Comment by sfan5** [comment]
> DirectX version: 9, or 11 (running mt mainly on direct3d9)

If it works on OpenGL, you're out of luck. We do not actively support D3D.

**Comment by v-rob** [comment]
Tested; happens in D3D9 but not in OpenGL or Burning's Video.  Seems to be a D3D-exclusive problem.

**Comment by danil275487** [comment]
Windows issue, Linux gaming
