### ISSUE TITLE
Suggestion: Don't use system-wide irrlicht build when building against forked irrlicht version

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#11062]
When using Irrlicht fork to build minetest I suggest to use local build of it instead of system-wide ~as such installation might break other software and packages if installed globally. By not installing globally any problems/incompatibilities/etc coming from irrlicht fork might be avoided when used on other software or earlier minetest versions and also it avoids any possible bugs in other software that might come from using this fork. Some package managers might even replace the forked version with one used by software being installed if program excplicitly depends on such verison.~ The global intallation might not work as the cmake does not detect the correct file name of renamed library (since minetest/irrlicht@f05f84b33b19ed11fc1d6eef48286a06c59b06ce) the time I'm writing this edit (as of commit 437d01196899f85bbc77d71123018aa26be337da)

To tell cmake to **not** use system wide version on linux add parameters like in below example to it's command line:
` -DIRRLICHT_LIBRARY=/home/user/irrlicht/lib/Linux/libIrrlichtMt.a -DIRRLICHT_INCLUDE_DIR=/home/user/irrlicht/include/`

I also suggest adding similar suggestion in readme if not already done, this might avoid confution for other users too.

**Edit:** since minetest/irrlicht@f05f84b33b19ed11fc1d6eef48286a06c59b06ce the correct library name is libIrrlichtMt.a, as the library got renamed, I updated the example command line to reflect this.

**Comment by sfan5** [comment]
The decision to install our Irrlicht fork system-wide or not is made by the user.
We can add suggestions to the REAMDE but we can't prevent the user from doing what they want to do.
