### ISSUE TITLE
Connection timeout in GUI local server when mods take >10s to load

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#11085]
##### Minetest version

```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

When it takes longer than ten seconds to load mods I get a "connection timed out" error. This happens intermittently when I use [dreambuilder_game](https://gitlab.com/VanessaE/dreambuilder_game), however I can get the same error using this code:

```lua
local t = minetest.get_us_time() + 10000000
while minetest.get_us_time() < t do end
```

##### Steps to reproduce

1. Create a mod with the above code
2. Enable this mod in a world
3. Check "Host Server"
4. Press "Host Game"

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/285ba74723695c4b51192dac0e1e17c5d8f880db/src/client/game.cpp#L1544-L1548

This means that `start_data.isSinglePlayer()` is not working properly... needs investigation. Or are you hosting a local server uding the "start game" menu? I think that use-case is yet not covered there.

**Comment by luk3yx** [comment]
> This means that `start_data.isSinglePlayer()` is not working properly... needs investigation. Or are you hosting a local server using the "start game" menu? I think that use-case is yet not covered there.

I was and it looks like it works in singleplayer.

**Comment by sfan5** [comment]
Perhaps more interesting here would be to know which mods suddenly take a long time to load. The 10s loadtime limit has always been there.
Any ideas?

**Comment by kneekoo** [comment]
Does Minetest report this in the log? If not, it could do it by adding mod names to an array, and remove them from there once the mods are successfully loaded. Whatever lingers in that array would obviously not have been loaded properly, so that can be added to the log.

**Comment by anezka-tvorilka** [comment]
I have this issue too and I found a workaround. In singleplayer, the game started, when I didnt check option "start server" in GUI. Instead I started server from command line. After that I joined to the server with GUI, on the same computer under the same user (I am using Linux Mint).  After that, I was also able to connect to server from different computer as another player.
