### ISSUE TITLE
How to separate the stacked items on the mobile phone for synthesis?

### ISSUE THREAD

**Issue by cosoc** [minetest/minetest#11086]
##### Minetest version
minetest v5.4.0

##### OS / Hardware

Operating system: Android

##### Summary
How to separate the stacked items on the mobile phone for synthesis?

**Comment by Emojigit** [comment]
> ##### Minetest version
> 
> minetest v5.4.0
> ##### OS / Hardware
> 
> Operating system: Android / ios
> ##### Summary
> 
> How to separate the stacked items on the mobile phone for synthesis?

afaik IOS is not supported, if you just tested on IOS, please also test on android.

**Comment by AntumDeluge** [comment]
To split item stacks, pinch/spread with two fingers.

There are two methods of splitting:
1. Hold down on slot containing item. Use second finger to pinch/spread. This will pick up all but one of the items.
2. Touch item to pick up. Touch & hold down on target slot. Use second finger to pinch/spread. This will drop half of the held items into the target slot.
