### ISSUE TITLE
Make serialized JSON metadata more space efficient

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#11087]
## Problem

Currently data in item metadata is serialized quite inefficiently. This is especially noticable for `tool_capabilities` which is serialized as JSON.

This is the serialized JSON for `tool_capabilities` in an efficiency 5 enchanted pickaxe for Mineclone2:

```
{
	"damage_groups" : 
	{
		"fleshy" : 5
	},
	"full_punch_interval" : 0.83333331346511841,
	"groupcaps" : 
	{
		"pickaxey_dig_default" : 
		{
			"maxlevel" : 0,
			"times" : 
			[
				null,
				0.0,
				0.10000000149011612,
				0.10000000149011612,
				0.15000000596046448,
				0.15000000596046448,
				0.15000000596046448,
				0.20000000298023224,
				0.25,
				0.25,
				0.30000001192092896,
				0.30000001192092896,
				0.44999998807907104,
				0.55000001192092896,
				0.75,
				3.3499999046325684,
				7.4000000953674316
			],
			"uses" : 1562
		},
		"pickaxey_dig_diamond" : 
		{
			"maxlevel" : 0,
			"times" : 
			[
				null,
				0.0,
				0.0,
				0.0,
				0.0,
				0.0,
				0.0,
				0.10000000149011612,
				0.10000000149011612,
				0.10000000149011612,
				0.10000000149011612,
				0.10000000149011612,
				0.15000000596046448,
				0.20000000298023224,
				0.25,
				1.0,
				2.25
			],
			"uses" : 1562
		}
	},
	"max_drop_level" : 5,
	"punch_attack_uses" : 781
}
```

It is completely unnecessary for the serialized JSON to include formatting because it is not meant to be read by a human. The formatting is also unreadable because the tab and newline characters are escaped in the itemstring. So I had to replace `\t` with tab, `\n` with newline and `\"` with `"` to make the example more readable.

These characters are just wasted space in the item metadata. This increases the network traffic between client and server. It probably also has some effect on the serialization/deserialization time.

## Solutions

We change the code so the serialization does not output whitespace characters. This gives us the following data

```
{"damage_groups":{"fleshy":5},"full_punch_interval":0.83333331346511841,"groupcaps":{"pickaxey_dig_default":{"maxlevel":0,"times":[null,0.0,0.10000000149011612,0.10000000149011612,0.15000000596046448,0.15000000596046448,0.15000000596046448,0.20000000298023224,0.25,0.25,0.30000001192092896,0.30000001192092896,0.44999998807907104,0.55000001192092896,0.75,3.3499999046325684,7.4000000953674316],"uses":1562},"pickaxey_dig_diamond":{"maxlevel":0,"times":[null,0.0,0.0,0.0,0.0,0.0,0.0,0.10000000149011612,0.10000000149011612,0.10000000149011612,0.10000000149011612,0.10000000149011612,0.15000000596046448,0.20000000298023224,0.25,1.0,2.25],"uses":1562}},"max_drop_level":5,"punch_attack_uses":781}
```

Which is 723 bytes (each `"` becomes 2 bytes when escaped using `\"`). Before the change the data took 1274 bytes.

## Alternative solutions

If we want to go one step further we can probably improve the serialization to not include as many decimal digits in floating point numbers. Then we would get the following:

```
{"damage_groups":{"fleshy":5},"full_punch_interval":0.8333,"groupcaps":{"pickaxey_dig_default":{"maxlevel":0,"times":[null,0.0,0.1,0.1,0.15,0.15,0.15,0.2,0.25,0.25,0.3,0.3,0.45,0.55,0.75,3.35,7.4],"uses":1562},"pickaxey_dig_diamond":{"maxlevel":0,"times":[null,0.0,0.0,0.0,0.0,0.0,0.0,0.1,0.1,0.1,0.1,0.1,0.15,0.2,0.25,1.0,2.25],"uses":1562}},"max_drop_level":5,"punch_attack_uses":781}
```

Then the metadata only requires 415 bytes. So with both these changes it is more than 3 times more efficient compared to the current code. I do however think that this might be a bit complicated to do for little gain.

Not including the whitespace however seems like a very simple change (probably just change a setting in the JSON serializer) for a big gain (almost 50 % less space for the same amount of data).

## Additional context

The size of the `tool_capabilities` metadata has been a very serious problem for the subgame Mineclone2. This is not a big problem anymore after [recent changes](https://git.minetest.land/MineClone2/MineClone2/pulls/1285) to how it handles digging times. Even though this is no longer a big issue for Mineclone2 we can still implement one or both of these suggested techniques to lower the data usage of items. This will not only benefit Mineclone2 but other subgames and mods which use `tool_capabilities`.

**Comment by SmallJoker** [comment]
Metadata was originally a single string, which was serialized to `default:book_written 1 0 "metadata text"`.
For legacy reasons, and also future extension potential, metadata is still serialized to a string, but using delimiter bytes to separate the key/value fields.
I totally see your request for dropping the escape sequences, but this is not possible without dropping compatibility to older clients. However, the JSON could be serialized using single quotation marks ( `'` ) if possible, and condense the format to machine readable only (basically what you wrote in Solutions). Floating point precision could be addressed too, but I am uncertain where this precision loss comes from - maybe there's a float/double conversion somewhere in between.

**Comment by ryvnf** [comment]
I think I might not have been clear. I am not requesting that we remove escape sequences. I just wanted to point that the escape sequences for tab and newline make the itemstrings unreadable by a human anyways which makes any formatting like indentation and newlines useless.

What I am primarily advocating for is to removing the whitespace from the serialized JSON text. I think that should be a simple change which would have noticeable benefits. But your idea of using single-quotes instead of double quotes in the JSON serialization also sounds good.

You are probably right that the unnecessarily long floating point constants have something to do with precision. All those values should be a multiple of 0.05 because Mineclone2 does the following to round them up to the nearest Minecraft tick value using the following code:

```lua
digtime = math.ceil(digtime * 20) / 20
```

I agree it would be nice if that could be addressed too.
