### ISSUE TITLE
Can glitch through ceiling with Sneak Glitch

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11081]
##### Minetest version
```
5.4.0
```

##### Summary
If a player has `sneak_glitch=true` and `new_move=false` physics, they can glitch through the ceiling with sneak ladders with ease. This issue is basically a revival of #3045, except this time, it depends on specific player physics settings.

Sneak Glitch with New Move seems to work, however (phew!).

This image shows it perfectly:

https://user-images.githubusercontent.com/55103816/109354355-f74a0300-787d-11eb-9d9b-8e2a41ccd4bd.gif

##### Steps to reproduce
* Install and enable the `luacmd` mod
* `/lua me:set_physics_override({sneak_glitch=true, new_move=false})`
* Build a sneak ladder with a solid node ceiling at the top (see image above)
* Go to the bottom
* Hold down the sneak and jump key and climb the sneak ladder

If there's a bug, you glitch through the ceiling. If not, the ceiling stops you.

##### See also

<b>Originally reported here</b> https://github.com/minetest/minetest/issues/7107#issuecomment-786896145

**Comment by Wuzzy2** [comment]
:-(

Unfortunately, I have to inform you that I just managed to glitch through the ceiling in New Move (+Sneak Glitch) as well. However, it is much harder to pull of. I don't know exactly how, but you have to try multiple times, sneak walk at the top and wiggle the camera around a lot, until you glitch through.

I also noticed the camera shakes a lot while you try to glitch through the ceiling with New Move.

Note that when Sneak Glitch is off and New Move is on, it is not possible to glitch through the ceiling because sneak elevators don't work without the Sneak Glitch.

**Comment by SmallJoker** [comment]
> To summarize:
>
> *   Don't touch Old Move (for historic reasons)
> *   [...]
> *   Fix glitching through the ceiling (#11081)

This does not make sense. I'd also prefer to not touch the old code and find/fix this the step-up ceiling glitch in the new code.

**Comment by Wuzzy2** [comment]
Well, after I read the other issue, it looked like there was a consensus to keep Old Move for historic reasons. So I changed my mind. So this issue is no longer about Old Move.

However, you can glitch through the ceiling with `sneak_glitch=true, new_move=true`, and I think this can be considered a bug, right? Even if Old Move is not touched.

**Comment by Extex101** [comment]
This is a well known and used bug in a server I used to play, so I can confirm it's been around since 2018

**Comment by archfan7411** [comment]
It was always my understanding that this was part of the sneak glitch, and was often used as a feature. 

I agree that it's a glitch/bug, but so was the sneak glitch - a bug which became a well-used feature for many of us :)

**Comment by Wuzzy2** [comment]
Well, being able to glitch through the ceiling causes a lot of problems for game design as well, so it's better to fix it. If a game really wants a way to "teleport" through walls, it better implements it as a proper feature in its own right, rather than depending on bugs. Depending on bugs is never a good idea.

**Comment by voxel-minetest** [comment]
> This is a well known and used bug in a server I used to play, so I can confirm it's been around since 2018

Probably even longer, I remember that I have done this already severeal years ago (+-2015?)
