### ISSUE TITLE
Minetest doesn't compile due to official irrlicht engine despite installing minetest's fork

### ISSUE THREAD

**Issue by Maniues** [minetest/minetest#11094]
I have a problem compiling the minetest.
I'm getting an error with cmake:
`-- *** Will build version 5.5.0-dev ***
-- Looking for IRRLICHT_VERSION_MT
-- Looking for IRRLICHT_VERSION_MT - not found
CMake Error at CMakeLists.txt:78 (message):
  Irrlicht found, but it is not Minetest's Irrlicht fork.  The Minetest team
  has forked Irrlicht to make their own customizations.  It can be found
  here: https://github.com/minetest/irrlicht

  Building the client with upstream Irrlicht is no longer possible.`

I uninstalled irrlicht and downloaded and compiled the minetest version with the following commands:
`git clone https://github.com/minetest/irrlicht

cd irrlicht

cmake . -DBUILD_SHARED_LIBS=OFF

make -j3

make install`
Despite this, the error keeps receiving.
[CMakeError.log](https://github.com/minetest/minetest/files/6175235/CMakeError.log)
[CMakeOutput.log](https://github.com/minetest/minetest/files/6175236/CMakeOutput.log)

**Comment by SmallJoker** [comment]
Wrong cmake configuration, although the paths for the Irrlicht fork detection could be extended a bit. What do you think about this @sfan5 ?

Here's a configuration that should work after building Irrlicht.
`cmake . -DIRRLICHT_INCLUDE_DIR=$PWD/../irrlicht/include -DIRRLICHT_LIBRARY=$PWD/../irrlicht/lib/Linux/libIrrlicht.a`
Source: https://github.com/minetest/minetest/issues/11047#issuecomment-795180135

**Comment by sfan5** [comment]
Installing our fork system-wide when you have 1.8.4 still installed is a bad idea, we'll improve this soon by renaming the libraries to avoid conflicts. (#11062)

In your specific case CMake is still looking in `/usr/include/irrlicht` and picking up Irrlicht 1.8.4.
This would probably work: `cmake . -DIRRLICHT_INCLUDE_DIR=/usr/local/include/irrlicht -DIRRLICHT_LIBRARY=/usr/local/include`

**Comment by Maniues** [comment]
> Installing our fork system-wide when you have 1.8.4 still installed is a bad idea, we'll improve this soon by renaming the libraries to avoid conflicts. (#11062)
> 
> In your specific case CMake is still looking in `/usr/include/irrlicht` and picking up Irrlicht 1.8.4.
> This would probably work: `cmake . -DIRRLICHT_INCLUDE_DIR=/usr/local/include/irrlicht -DIRRLICHT_LIBRARY=/usr/local/lib/libIrrlicht.a`

I used your command and it's working. Thanks. The problem was probably that minetest looked for irrlicht in usr / include and was actually in usr / local / include

**Comment by SwissalpS** [comment]
For those finding this after this method isn't working anymore (5.5), using symlink worked for me. [Similar to what this post describes.](https://forum.minetest.net/viewtopic.php?p=403331)
