### ISSUE TITLE
Allow building Irrlicht automatically when compiling Minetest

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#11108]
## Problem

I noticed I have to compile both Irrlicht and Minetest to get the latest Minetest version to work (because Minetest no now requires a separate fork). Compiling this separate dependency quite annoying for someone who just wants to get the latest Minetest version. I do not think people have any use of the Irrlicht fork other than for minetest so I think it would make sense to allow it to be built automatically when compiling Minetest.

## Solutions

Change the build script to default to automatically clone and compile the Minetest fork of Irrlicht when Minetest is compiled. Include a flag for people who want to use a manually system-wide installed Minetest compatible version of Irrlicht. The Minetest fork of irrlicht could also be included as a git submodule in the Minetest repository.

## Alterantive solutions

Include the Minetest fork of Irrlicht in the `lib` directory (maybe as a submodule) like `gmp`, `jsoncpp` and `lua` and default to using that version if not using a separately compiled version of Irrlicht.

**Comment by nerzhul** [comment]
i agree it's not so easy. Also for Dockerfile for servers they are not using the irrlicht fork either. We should fix that. I take the point on the docker file

**Comment by sfan5** [comment]
IRC discussion -> https://irc.minetest.net/minetest/2021-03-31#i_5806055

> Change the build script to default to automatically clone and compile the Minetest fork of Irrlicht when Minetest is compiled. 

As I've stated on IRC I think this is an awful idea <i>unless</i> it's an opt-in thing. 

> Include the Minetest fork of Irrlicht in the lib directory (maybe as a submodule)

Importing the fork into our repo, submodule or not, is definitely not happening.

**Comment by celeron55** [comment]
I believe this is sufficiently handled by #11276 which closed #11264.
