### ISSUE TITLE
Minetest --help and --version dont work correctly on Powershell

### ISSUE THREAD

**Issue by samarth-ramesh** [minetest/minetest#11106]
##### Minetest version
5.40, also seen as early as 4.17.1

##### OS / Hardware
Operating system: Win 10
CPU: AMD Ryzen 5 5500

##### Summary
``minetest --help``, ``minetest --version`` incorrectly work with powershell. With cmd it works correctly (but does not appear to return). 
Also included in the link is a video that shows it not working. 

Terminal: Windows Terminal (pictured). Also tried on stock powershell, and on stock cmd

http://cddo.cc:1580/6c053a158dd7bfa74017bd8e969b2ed7.mp4

**Comment by sfan5** [comment]
I think this is because Minetest is compiled as a GUI application (`-mwindows`) but writes to the terminal anyway.
This is a Windows limitation, not something we can fix.

**Comment by samarth-ramesh** [comment]
Fun, so no way to fix? Or is there something I can to to help?

**Comment by AFCMS** [comment]
@samarth-ramesh link is broken

**Comment by srifqi** [comment]
I can confirm this using Minetest 5.4.0 on Windows 10 (10.0.19042). Minetest's output is printed to the position which should be user input.

<details>
<summary>using Command Prompt</summary>

![screenshot using Command Prompt](https://user-images.githubusercontent.com/4017302/120059340-32c1bc80-c07b-11eb-96c3-03374dc4e76f.png)
</details>

<details>
<summary>using Windows PowerShell</summary>

![screenshot using Windows PowerShell](https://user-images.githubusercontent.com/4017302/120059350-43723280-c07b-11eb-955f-37ef3e74daf4.png)
</details>
