### ISSUE TITLE
Embed widget toolkit on cubes

### ISSUE THREAD

**Issue by vanillajonathan** [minetest/minetest#11100]
## Problem

Players are limited in how they interact with creations in the world.

## Solutions

Embed a widget toolkit (such as GTK or Qt) on cubes.

This would allow players to do things such as:
- Pick color on objects and other stuff such as light
- Toggle on/off for light in houses
- Toggle start/stop for things such as trains and carts
- Edit texts
- Pick font for text
- Set integers such as speed of train or carts
- Edit lists of invited characters to houses
- All kinds of fancy cool player interaction with scripts, mods and in-game content as well as bridges to the outside world

## Additional context

This mockup example shows the [`GtkColorChooserDialog`](https://developer.gnome.org/gtk4/stable/GtkColorChooserDialog.html) from the GTK toolkit on the surface of a cube in Minetest.

![image](https://user-images.githubusercontent.com/10222521/111906864-18ec7380-8a53-11eb-92a7-b0cdef1439e5.png)

**Comment by rubenwardy** [comment]
Thanks for the suggestion. If we're not using Qt/GTK as a GUI, it's definitely not going to be added for nodes. Additionally, it makes much more sense for the node to open a GUI rather than display a GUI

**Comment by vanillajonathan** [comment]
> Additionally, it makes much more sense for the node to open a GUI rather than display a GUI itself.

It could do both. Render on the surface, then open up a dialog when you bash the surface.
