### ISSUE TITLE
Embed YouTube videos on cubes

### ISSUE THREAD

**Issue by vanillajonathan** [minetest/minetest#11101]
## Problem

Players are limited to in-game content. This make many things such as museums, art galleries, event arenas, as well as let players and communities arrange conferences, conventions, concerts, release parties, cinemas, etc impossible.

## Solutions

Implement functionality to allow players to embed YouTube videos (and perhaps other media such as photos, cartoons, paintings, and music from other hosted services). The players should be able to embed such content as YouTube videos on the surfaces of a cube.

This would allow creations of museums, art galleries, event arenas, as well as for players to arrange conferences, conventions, concerts, meetups, release parties, cinemas, etc

## Additional context

This mockup example features [Rick Astley - Never Gonna Give You Up](https://www.youtube.com/watch?v=dQw4w9WgXcQ) on YouTube.

![image](https://user-images.githubusercontent.com/10222521/111906394-ada1a200-8a50-11eb-82d4-a321d423b987.png)

**Comment by hlqkj** [comment]
I'd be skeptical on letting players add content to my own game...

**Comment by daytonnvpaul** [comment]
Does anyone every think of licensing issues using 3rd party media?

**Comment by vanillajonathan** [comment]
> I'd be skeptical on letting players add content to my own game...
> 
> Edit: not sure on who will and/or should be responsible for copyright infringements, but at least that makes content moderation very hard.

If the server admin don't want to let regular players embed content the admin could configure the server to restrict that feature only to admins.

> Does anyone every think of licensing issues using 3rd party media?

How is this any different from embedding a media clip on your blog with an iframe or in a tweet on Twitter or a post in any other social media. YouTube even has an [iframe embed API](https://developers.google.com/youtube/iframe_api_reference) to make it easy to embed YouTube clips.

**Comment by v-rob** [comment]
Licensing issues aside, it would be hard to implement YouTube videos in specific since that would kind of necessitate a web browser.  However, a generic video library is possible, #9430 was an attempt (and closed more for controversy than implementation AFAIK).  Even with that, and assuming the video's source could be found, Minetest has no way to stream video/audio.

**Comment by daytonnvpaul** [comment]
Please consider this.  What if a player was to embed a non-family friendly media on a family friendly server?  Do you really expect admins to verify every embedded media.  I can only imagine the doors of abuse this could open.

Also, if media contained copyrighted material, it could make the server own liable for royalties or other penalties.

**Comment by AFCMS** [comment]
@vanillajonathan Valid feature request, but a bit strange... Why not asking way to stream video/audio instead of just embedding YouTube? I would be definitely more useful.

**Comment by vanillajonathan** [comment]
@AFCMS That could be something too, but then server would need the additional bandwidth to stream the videos, and then only the server admin could add videos by uploading to them to the server where it is stored on the server. With YouTube any player could just embed the video on a cube surface with a hyperlink code and then the Minetest client would stream it directly from YouTube.

**Comment by Andrey2470T** [comment]
The videos on surfaces of nodes may be played with using the tile animation definition, however you want players could switch videos. It means they have to change that original tile animation to other one, but... the nodes are fully static and I doubt it is currently possible.

However, there is a workaround for that: you can attach a special entity with the flat shape to the node surface and as entities are almost fully dynamic, you can switch textures (I don't know whether the tile animation definitions can be used in 'textures' table for entities?).

Second problem is a need to convert the format that uses the video to png with the set of the vertical frames of that is what MT certainly can't do.

**Comment by vanillajonathan** [comment]
I want players to be able to create a house to fill the role of a cinema or museum. In the house there can be a cubes (or maybe even cover multiple cube surfaces) where the player can walk up to the cube, bash it and get a dialog where the player can enter a code such as [dQw4w9WgXcQ](https://www.youtube.com/watch?v=dQw4w9WgXcQ) or a full URI and click on a save button.

**Comment by daytonnvpaul** [comment]
@vanillajonathan, and what will you do when they embed a porn video, and an 8 year old kid sees it, shows their mom?

**Comment by hlqkj** [comment]
> If the server admin don't want to let regular players embed content the admin could configure the server to restrict that feature only to admins.

I admit I didn't think at that possibility, still I think it's a bit strange/out-of-topic in the minetest context. Why not adding audio streaming support for (e.g.) background music then...?

**Comment by daytonnvpaul** [comment]
BTW, the song video you refer to, requires a license to use in a video game.

https://www.songfacts.com/licensing/rick-astley/never-gonna-give-you-up

**Comment by vanillajonathan** [comment]
@daytonnvpaul, any server admin who worry about that can just chose not to enable the video embedding feature or restrict that feature to admins only or a few select trusted players.

As for the copyright, it is up to the server admin to deal with any such issues and decide what he wants to link or have linked. The server doesn't host any copyrighted content, it just contains a URI to it, a pointer where to find it. The client doesn't contain any copyrighted media either, it just streams it from a third-party (example YouTube) that hosts and distributes it.

**Comment by daytonnvpaul** [comment]
With so many new Minetest Server Owners, being under the age of 16, you are are putting a lot of faith in their understanding of legal responsibilities and  capabilities.  Sorry, but I think this could open more than just a can of worms.

With this comment, I'm not going to post more on this idea.

**Comment by v-rob** [comment]
Adding a "Possible close" label since YouTube videos in specific really aren't feasible to implement.  I'm not talking about licensing or responsibility or whatever, only whether or not it can be implemented in the engine reasonably.  Now, if someone opens an issue about normal videos, that sounds much more like a possibility.

**Comment by vanillajonathan** [comment]
@v-rob, yeah maybe it would be useful too with just a URI that ends with `.avi`, `.mkv` or `.webm` or something. Not as easy to find content then, and not as easy to use for players, but it still could open up cool possibilities of what is possible inside Minetest.

**Comment by rubenwardy** [comment]
Adding support for playing YouTube videos definitely won't happen, it's too vendor specific. The ability to stream videos from the server or a web address may be added, but is low priority enough that it shouldn't be added for a while

If you have a use case for this, you should consider compiling Minetest yourself and cherry picking from that ffmpeg pull request

**Comment by MisterE123** [comment]
If a minetest server was also a web server, you could host *your own* or public domain videos from your website, and link to it in the minetest world. Then the player's minetest client would stream the video from the host. 

I think its a great idea.

**Comment by v-rob** [comment]
Closing for reasons previously stated by myself and rubenwardy.  Opening an issue about video libraries or streaming is fine (assuming there aren't any other issues for that already), but YouTube in specific won't happen.

**Comment by MisterE123** [comment]
maybe, instead of closing, it would be better to rename it?

**Comment by vanillajonathan** [comment]
The benefit of YouTube is that it is so easy to use and accessible. Gamers might not know how to upload videos to private servers or such, for them it is much easier just to find a clip on YouTube and get the URL.

**Comment by NathanSalapat** [comment]
@vanillajonathan if somebody is already running the server I expect they'd be able to figure out how to upload a video to a private server as well.

**Comment by vanillajonathan** [comment]
@NathanSalapat But I would imagine this being usable for players too, not just for server admins. So regular players can have a house in the world where they click on the cubes to attach a video, simply by just pasting the URL, then the players can be bring in friends to his house and show them.

**Comment by NathanSalapat** [comment]
@vanillajonathan As previously mentioned that brings up all sorts of potential legal issues.

**Comment by vanillajonathan** [comment]
@NathanSalapat I am not aware of any legal issues arising when users post links to YouTube videos on instant messengers and the app shows a thumbnail of the video, or when you post a link on social media and it lets you play it from the social media website. Either way, if there is any legal issues then that is for the server admins not for the developers. The server admin can just chose to not enable this disabled-by-default feature if he/she worries about any legal issues.

**Comment by v-rob** [comment]
I'll give my reasons for closing this.  It's not because there aren't use-cases, and it's not even because of licensing.  The reasons are practical:
* To embed YouTube videos, Minetest would need to essentially embed a web browser because YouTube relies heavily on web technology.  Embedding a web browser is **_not_** feasible in the slightest for many, many reasons.
* Even assuming you found the source of the video from the YouTube webpage, we'd need a video library.  Positional sound would probably be pretty hard to combine with this.
* But, since the whole video can't be downloaded at once due to immense memory and speed requirements of doing that, we'd need streaming, which is rather hard.
* Even besides all of that, it can't be put on a node surface because nodes can't do that sort of thing (although entities would be annoying).

**Comment by voxel-minetest** [comment]
> Please consider this. What if a player was to embed a non-family friendly media on a family friendly server? Do you really expect admins to verify every embedded media. I can only imagine the doors of abuse this could open.
> 
> Also, if media contained copyrighted material, it could make the server own liable for royalties or other penalties.

Exactly... 
I hope such function will never get into the engine.
