### ISSUE TITLE
Updated Packages for ARM 32bit - Raspberry Pi 4B

### ISSUE THREAD

**Issue by Pythonic456** [minetest/minetest#11116]
## Problem

The packages in the RPi 4B 32bit repos are too old to play on MP servers.

## Solutions

Either these packages could be updated, or an ARM 32bit executable could be provided for Linux.

## Alternatives

Even a x86 32bit package could work, with [Box86](https://github.com/ptitSeb/box86), but a native package
would be better for performance and stability.

Thank you in advance!

**Comment by NathanSalapat** [comment]
Last time I tried compiling Minetest on a Pi there were graphics issues. I forget what exactly they were, but they prevented me from building a client. Likely whomever or whatever is responsible for the Minetest packages for the pi repos had the same issues.

**Comment by sfan5** [comment]
We don't maintain the packages contained in Raspberry Pi OS' repositories.
The current version of Raspberry Pi OS is based on Debian 10, which intentionally only updates packages to new versions on the next major release (that would be Debian 11). For people wishing to use newer software they have a `backports` repository which currently contains [Minetest 5.3.0](https://packages.debian.org/buster-backports/minetest), but I don't know if it's possible to use that on an RPi.

That said I have proposed that we provide official RPi builds before and I should be able to make you one pretty quickly.

**Comment by sfan5** [comment]
Okay here it is: https://kitsunemimi.pw/tmp/minetest-5.4.0-rpi%2B.tar.gz

* Works on Raspberry Pi 2 upwards
* Install these packages first: `zlib1g libjpeg62-turbo libbz2-1.0 libpng16-16 libx11-6 libopenal1 libvorbisfile3 libvorbis0a libogg0 libsqlite3-0 libxxf86vm1 libgles2 libegl1 libcurl3-gnutls libfreetype6`
* only OpenGL ES 2.0 supported as video driver

**Comment by Painadath** [comment]
I will compile and pack it as .deb format later tommorow hope it will work see you tommorow

**Comment by Painadath** [comment]
@Pythonic456 Here is my onoffical build of minetest 5.4.0 for armhf or raspberry pi
it is .deb package which you can install with a package manager .first you have to remove the old minetest completly  and install all the dependencies which @sfan5 commented before.
[minetest_5.4.0_armhf.zip](https://github.com/minetest/minetest/files/6205705/minetest_5.4.0_armhf.zip)

PS:(removed all the docs to reduce size and there is no game by default so you have to install one to /usr/local/share/minetest/games to play)
if you find any issue contact me on samuelpainadath@gmail.com

**Comment by Painadath** [comment]
now it is zip nad you have to rename it to deb format (github dont support .deb format

**Comment by Pythonic456** [comment]
Thanks for the help!

It works ok, but install a 8px texture pack and it works even better. Seems to have problems
with LAN servers but other than that it is good. ~30FPS with terrain in view - the highest I got was 60FPS.
Could the packages in the apt repo for `Raspberry Pi OS - Buster 32bit` be updated with this?

Thanks again!

**Comment by sfan5** [comment]
Glad to know it works.

> Could the packages in the apt repo for Raspberry Pi OS - Buster 32bit be updated with this?

Again: We don't maintain the packages contained in Raspberry Pi OS' repositories.

**Comment by Pythonic456** [comment]
Ok, thanks for your help!
