### ISSUE TITLE
Cannot type 1, 3, 5 in the console anymore

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#11117]
Version: https://github.com/minetest/minetest/commit/437d01196899f85bbc77d71123018aa26be337da

I'm unable to type 1, 3 and 5 (from number row, not numpad) in the console. 1 acts like arrow up (returns the previous command), 3 doesn't do anything and 5 acts like arrow down (empty the command line).

I use a AZERTY keyboard.

**Comment by sfan5** [comment]
fixed by https://github.com/minetest/irrlicht/commit/7f0e0a57b8e54b3e1bff7a0606a1a376a50c36a8
