### ISSUE TITLE
CMake should detect the renamed irrlicht library (as of minetest/irrlicht@f05f84b33b19ed11fc1d6eef48286a06c59b06ce) when possible

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#11123]
##### Minetest version

```
437d01196899f85bbc77d71123018aa26be337da
```

##### OS / Hardware

Operating system: Linux
CPU: Pentium(R) Dual-Core  CPU  E6300  @ 2.80GHz

##### Summary

Cmake does not detect the renamed irrlich library file name correctly (as of minetest/irrlicht@f05f84b33b19ed11fc1d6eef48286a06c59b06ce). It should try to find libIrrlichtMt when it is available instead of libIrrlicht as it does now. Also the cached variable should be renamed to avoild future build failures upon file rename, also warning/error/etc should be shown if file mentioned in configuration variable is not found or is not symlinked to existing file or the version of it it not supported.

##### Steps to reproduce

1. Build forked irrlicht (commit minetest/irrlicht@f05f84b33b19ed11fc1d6eef48286a06c59b06ce or newer), install system wide
2. Run cmake on fresh mt clone, after git clean -d -x -i or just unset cached irrlicht variables by providing `-UIRRLICHT_LIBRARY -UIRRLICHT_INCLUDE_DIR` to command line
3. Observe cmake not finding renamed library and complaining about wrong version and subsequent failing build

**Comment by sfan5** [comment]
We're obviously aware and this will be fixed as part of #11090.
