### ISSUE TITLE
Add custom player-hand models

### ISSUE THREAD

**Issue by danil275487** [minetest/minetest#11148]
I want people to be able to easily make player-hand item have a mesh model, which then could have a texture on each side.

**Comment by SmallJoker** [comment]
This should already be feasible using a mesh model inside the item or node definition. The hand cannot be placed, and only its tool properties and visuals are applied to the game mechanics.
See `"hand"` slot documentation in `lua_api.txt`-

**Comment by Wuzzy2** [comment]
I can confirm this is already possible. MCL2, for example, is using the exact method that SmallJoker describes. It's kind of an ugly hack, but does exactly what is requested.

I am now using my closing powers for the first time to close this issue.
