### ISSUE TITLE
Shaders not loading textures

### ISSUE THREAD

**Issue by Git-Forked** [minetest/minetest#11146]
##### Minetest version

```
Minetest 5.5.0-dev-024d47e0d (Linux)
Using Irrlicht 1.9.0mt1
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"

```

##### OS / Hardware
Operating system:  Manjaro Linux
CPU: Quad Core Intel Core i5 750

GPU model: Graphics:  Device-1: NVIDIA GT216 [GeForce GT 220] driver: nvidia v: 340.108 
Display: x11 server: X.Org 1.20.10
OpenGL: renderer: GeForce GT 220/PCIe/SSE2 v: 3.3.0 NVIDIA 340.108 

##### Summary

Shaders are not loading textures. 1 texture per NPC or mob is loaded and the rest are left black.

Using (latest as of this writing) git build: 
https://github.com/minetest/minetest/commit/024d47e0d38c382c6b1974bb4d019058acd77e67

##### Steps to reproduce

git clone latest MT irrlicht, make,
git clone latest Minetest, make.
login to a server with NPCs or mobs.

The server I use is: minetest.servegame.com port 42000

**Comment by SmallJoker** [comment]
Is this a machine-specific issue, or did you write a mod which does not work as expected?
If latter is the case and you're using `.obj` or perhaps `.x` model formats, then it's a file format limitation and not a Minetest bug: #11034.

**Comment by Git-Forked** [comment]
Not machine specific, and I did not write a mod.

**Comment by sfan5** [comment]
Please provide exact reproduction steps including which mod(s) you installed.

**Comment by Git-Forked** [comment]
![screenshot_20210405_070856](https://user-images.githubusercontent.com/66106762/113568114-e8bddc80-95dd-11eb-8258-a7adddbb924c.png)

Everything was previously working a build or two ago.  The issue seems to be since Minetest started requiring the MT version of irrlicht, but I'm not certain that has anything to do with it. 

The NPC's have one texture showing, the chain mail, and the rest of the textures failed to load, and appear as black as seen in the photo. 

These NPC's are from the mod installed on the server, called Wilhem's People mod.

The same effects are also seen from the mobs mod by TenPlus1 Mobs Redo. 

Steps to reproduce: 

git clone latest MT irrlicht, make, 
git clone latest Minetest, make.
login to a server with NPCs or mobs.

The server I use is:  minetest.servegame.com port 42000

**Comment by Git-Forked** [comment]
I did some more testing, and using the 5.4.0 build there are no issues, but returning to the 5.5.0-dev build the issues are present.

**Comment by sfan5** [comment]
I briefly tested this using mobs redo (no idea if that's affected too) at multiple opportunities and couldn't find anything broken. On an NVIDIA system too but with a much more recent GPU and driver (465.27).

**Comment by Git-Forked** [comment]
sfan5: Thanks for continuing to look into this issue.  
I update each time a new minetest dev version is commited, and the issue is still present.
I keep hoping that with each new update the issue may have been resolved, but no luck so far. 
If it does resolve in a future update, I will be sure to report it here.

**Comment by erlehmann** [comment]
I can confirm this also happens without shaders, but with white textures instead of black ones.

**Comment by erlehmann** [comment]
@sfan5 have you tried wilhelmine's people mod?

**Comment by EliasFleckenstein03** [comment]
> I can confirm this also happens without shaders with the people mod – but with white textures instead of black ones.

This also happens on Minetest 5.4.0 - the problem _without_ shaders is an older one, but now it also happens with shaders enabled.

**Comment by erlehmann** [comment]
New thing: The oak boat model in Mineclonia (forked from MineClone2 0.71) is okay – but the oak boat model in MineClone2 git HEAD seems to be affected by this bug, since it got re-exported from Blender in commit 97424f7d0a5ed634177ac7e972a2453f3e32c4b (to fix a visual size bug, by scaling the boat model).

**Comment by Git-Forked** [comment]
So glad to see this issue has finally been tracked down and will be resolved.  It's been plaguing me for awhile now. 
A big thank you to all the supporters.
