### ISSUE TITLE
Contentdb in the launcher should show what content it would like to update, if updates are available

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#11155]
At the moment users can only find out what was updated, when they start the launcher from a terminal, then they get an output like: 
`ACTION[Main]: Installed package to /home/USERNAME/minetest/5.4.0/mods/MODNAME` 
but only **after** the update. 

Mostly I check out first what comes with a new version of a mod, texture or game and then I decide to update it or not. 
At the moment it is intransparent.

**Comment by rubenwardy** [comment]
You can go through the list to see packages with updates. Installed packages are always first

**Comment by voxel-minetest** [comment]
Ok thank you for this hint, but at the moment (and I just begun to use the contentdb a few days ago) I have already 12 pages of installed mods, that is already a lot of clicking to check what has updates and I definetely will add more mods and this will result in a lot of more mods.

**Comment by voxel-minetest** [comment]
Maybe it would be an easy solution to display the packages first that got updates, alphabetically sorted?
