### ISSUE TITLE
Split MOTD and player list from /status?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11151]
Currently, `/status` prints out several server status related information. But that's not everything: It also prints out a list of players and the MOTD (if set). So actually, `/status` does three things.

I suggest to move the MOTD into a separate `/motd` command and the player list into a separate `/players` command.

**Comment by SmallJoker** [comment]
Three separate things which are all used quite rarely. I don't think client mods depend on this, also the MOTD is often quite short and not a nuisance when checking the status only.

I don't think this needs to be split. Keep it simple.

**Comment by Wuzzy2** [comment]
Yeah, I think you are right. It's not too important.
