### ISSUE TITLE
Combined node drawtypes

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#11153]
## Problem

There can only be a single node drawtype. I want to make minecraft bamboo with leaves, but it its consists of the trunk part (normal node drawtype) and the leaves part (plantlike drawtype)

Is there a way to combine two types together? This would result in interesting things, for example, not only bamboo with leaves, but also, say, embedded objects in glass (normal node and glasslike node)

You can close if you want or if theres some way i dont know about

**Comment by SmallJoker** [comment]
Either create an entity or an attached node that's created automatically on place or on mapgen.
Nodes have by definition only a single drawtype, and if you need variations, ("degrotate") meshes are a possibility.

**Comment by TechDudie** [comment]
Entities are laggy, i dont know how to make a entity, and they need models which i dont want to do. Id like for beginners to be able to create nodes like this.

**Comment by Wuzzy2** [comment]
The best workaround for now is to register a new node for each different “appearance”, and add a group to each of nodes you consider to be “equal” (like `bamboo_stem=1` or something like this). I have used this approach successfully plenty of times in MCL2.

Also “Minecraft bamboo with leaves” sounds like something a mesh could do. There is nothing wrong with meshes. Adding a drawtype specifically for this node feels like mega overkill to me.

As this issue has no well-thought out suggestions on its own, just a vague description of an even vaguer problem, and a perfectly valid workaround exists, I strongly propose to close this issue.

**Comment by TechDudie** [comment]
Fine, then.
