### ISSUE TITLE
Sound Muffling

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#11164]
## Problem

I was startled by a zombie moaning underground when I was above ground a few blocks up in MineClone2 

## Solutions

Add sound muffling for certain nodes see https://sciencing.com/objects-absorb-sound-8140985.html

**Comment by Desour** [comment]
:+1: For nice sound effects.
(OpenAL can do such things, I think, see https://www.openal.org/documentation/ and http://zhang.su/seal/EffectsExtensionGuide.pdf.)

**Comment by AFCMS** [comment]
:+1: I would love this feature to be implemented! It would be very useful.

**Comment by rubenwardy** [comment]
Duplicate of https://github.com/minetest/minetest/issues/11164
