### ISSUE TITLE
minetest 5.4 multiplayer search server

### ISSUE THREAD

**Issue by IIIullaIII** [minetest/minetest#11168]
Hello, I found an error in the search for online servers, in windows 10 minetest 5.4 . When searching for a server ,servers are shuffled during selection, meaning that if I select a server I am looking for, the description of the next or previous server is displayed, and the server in description is selected ,although visually it seems selected the right one

**Comment by sfan5** [comment]
This bug indeed exists in 5.4 but it was already fixed in the meantime, closing.

**Comment by IIIullaIII** [comment]
ok thanks, I’m waiting for new update, as I downloaded it today for windows, while on the server for linux a few days ago and I didn’t find any problems even for the client
Sorry for my english XD
