### ISSUE TITLE
Build instructions fail to mention that doxygen and libirrlicht-dev need to be installed

### ISSUE THREAD

**Issue by readyready15728** [minetest/minetest#11177]
##### Minetest version

5.4.0

##### OS / Hardware
Operating system:
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

CPU:
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 126.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 126.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 126.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 126.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : c03130
Serial          : 10000000f78fe8af
Model           : Raspberry Pi 400 Rev 1.0

GPU model: n/a
OpenGL version: n/a

##### Summary
Build instructions fail to mention that doxygen and libirrlicht-dev need to be installed.

##### Steps to reproduce
Attempt current build on Debian/Ubuntu/Raspberry PI OS with current `sudo apt install [packages]` recommendation.

**Comment by Desour** [comment]
- Don't you need doxygen only for `make doc`?
- You should use the forked irrlicht version (https://github.com/minetest/irrlicht), not apt's `libirrlicht-dev`.

**Comment by LoneWolfHT** [comment]
> * You should use the forked irrlicht version (https://github.com/minetest/irrlicht), not apt's `libirrlicht-dev`.

For post-5.4 at least

**Comment by readyready15728** [comment]
> * Don't you need doxygen only for `make doc`?
> * You should use the forked irrlicht version (https://github.com/minetest/irrlicht), not apt's `libirrlicht-dev`.

Oh OK, I see I made a mistake. It compiled though. What are the consequences if I use the bog standard one?

**Comment by rubenwardy** [comment]
> What are the consequences if I use the bog standard one?

You should use the upstream Irrlicht for 5.4.0, but 5.5.0(-dev) requires the forked Irrlicht. You cannot build with the upstream/"standard" Irrlicht
