### ISSUE TITLE
GOTO Supported on JIT but not non-JIT

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#11178]
##### Minetest version

```

```

##### OS / Hardware

Operating system: KDE Neon User
CPU: Ryzen 5600x

##### Summary
Goto is supported when using a game compiled with luajit, but not regular lua.

##### Steps to reproduce
Run goto in a statement on jit, then try it in non-jit.

**Comment by SmallJoker** [comment]
This is not a Minetest issue. We cannot change the bytecode generator within LuaJIT. Do not use `goto` if you want to ensure compatibility across builds.
