### ISSUE TITLE
Implement destructibility fall damage for vehicles

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#11182]
# Problem: 
A post from user LibraSubtilis on the forum ( https://forum.minetest.net/viewtopic.php?p=393339#p393339 ) reminded me, that players are immortal when mounted to a vehicle like a boat (also I know of animals like horses with the same problem). 

While mounted, you can jump from any height without taking any damage. 
This highly unbalances all games with mountable stuff. 

# Solution: 
It should be possible for modders to set fall damage for any mountable vehicle/entity when a player is mounted. 
And a second possibility to also damage the player when the mount she or he is attached to got damaged.

**Comment by appgurueu** [comment]
> It should be possible for modders to set fall damage for any mountable vehicle/entity when a player is mounted.
> And a second possibility to also damage the player when the mount she or he is attached to got damaged.

Since the introduction of moveresults possible without engine change.

**Comment by wsor4035** [comment]
closing based on the above
