### ISSUE TITLE
Default spawnpoint can cause player death right after joining

### ISSUE THREAD

**Issue by voxel-minetest** [minetest/minetest#11183]
##### Minetest version
5.4.1 and vanilla mtg-5.4.0

##### Summary
When you type in no seed at world creation minetest will randomly create one. 
The default spawn point is 0,0,0. 
I have created a world like this and was spawned inside a mountain, stucking in nodes I couldn't break with bare hands. 
I thought maybe something crashed in minetest while generating the world (but no output at all on the terminal). 
I created another world the same way and spawned in the air, falling down 55 nodes and died.

##### Steps to reproduce (the second world I created)
Create a new world with carpathian with the seed: 3839021250245569243  
Default spawnpoint. 

##### Solution 
I've red in the Minecraft wiki, that Minecraft ckecks if the spawn is safe (solid nodes under the player):  

"When the player first loads into the world or respawns, the game searches within the world spawn area and tries to place the player on a random grass block. 
Any non-solid such as grass and flower that are placed directly above a grass block causes the block to become a invalid spawn point. 
However, if there are no valid grass blocks within the world spawn area, the player spawns directly at the world spawn point.

Upon spawning, the player is placed on the highest block of the X and Z spawn coordinates, even if this would set the player above the maximum build height. This area does not consider the existence of a block on which to spawn, and this can result in players spawning above the Void if there are no blocks at that X and Z location. However, if there are valid grass blocks within the world spawn area, the player spawns on the grass block with solid blocks above." 

Source: https://minecraft.fandom.com/wiki/Spawn#World_spawn

**Comment by LoneWolfHT** [comment]
Unset your static spawnpoint and you won't have this issue.

Static spawnpoints are for when you want to set a specific spawnpoint that you know to be safe. I think it's intended to be used for servers.

Per-world settings would be nice for this though

**Comment by SmallJoker** [comment]
If you did not specify a spawn point manually, it is selected randomly including safety checks by default using mapgen heightmaps. If you're using a Lua mapgen you might have to implement that yourself in case it does not work.

**Comment by voxel-minetest** [comment]
> Unset your static spawnpoint and you won't have this issue.

> If you did not specify a spawn point manually, it is selected randomly including safety checks by default using mapgen heightmaps.

It is the default setting, so only when I use a custom setting it will choose sa fase spawnpoint automatically? 
This really should be the default behaviour then. 
For me it is not a problem but for newcomers... 

> If you're using a Lua mapgen you might have to implement that yourself in case it does not work.
The mapgen.lua from default
