### ISSUE TITLE
Game crashes right after starting in a new v6 world

### ISSUE THREAD

**Issue by voxel-minetest** [minetest/minetest#11193]
##### Minetest version
5.4.1
and
vanilla mtg 5.4.0

Only output: 
`Segmentation fault `

**Comment by SmallJoker** [comment]
Pleas provide more information.
```
gdb minetest
r   (stands for run)
(reproduce the error until segfault)
bt  (stands for backtrace)
```

**Comment by voxel-minetest** [comment]
It works again now. 
It seems that this was somehow connected to [this here](https://github.com/minetest/minetest/issues/11194).
