### ISSUE TITLE
Broken mapgens

### ISSUE THREAD

**Issue by voxel-minetest** [minetest/minetest#11194]
##### Minetest version
minetest 5.4.1
vanilla mtg 5.4.0

##### Problem 
Was already mentioned here: 
[minetest 5.4 glitch snow in the desert and kelp](https://forum.minetest.net/viewtopic.php?f=6&t=26510)

Also there's is no default:water anymore, I've tested this with the following mapgens: v7, v5, flat, carpathian. 
In valleys I couldn't find any default:water either, but riverwater, but I know that there are oceans too in valleys, I once played a valleys map with an ocean or at least a huge lake with default:water.

v6 crashes minetest everytime I join into a new world ([see here](https://github.com/minetest/minetest/issues/11193))

See my posts [there](https://forum.minetest.net/viewtopic.php?p=393531#p393531) to view exampe images of the different mapgens. 
The seeds are visible in these images, so you can reproduce.

**Comment by voxel-minetest** [comment]
I forgot to mention, that I already discovered this behaviour in minetest 5.4.0.

**Comment by v-rob** [comment]
What's the value of your `water_level` setting?  If it's lower than 1, you can get the behaviour described.

**Comment by voxel-minetest** [comment]
I've red that [here](https://forum.minetest.net/viewtopic.php?p=392903#p392903), but didn't checked that, becuase I definetaly did not changed that. 
It is at -31000 
That's totally weird, i have a precise overview over my custom settings and that isn't in there and was never in there... o_0

**Comment by sfan5** [comment]
This is definitely not reproducible in the default configuration.
What is possible however is that games/mods set mapgen settings globally (hence affecting new worlds) even when they are not supposed to, you might want to check that.

**Comment by voxel-minetest** [comment]
The water_level setting isn't in my custom minetest.conf 

You mean even if I run a new world with only vanilla mtg another mod that is in the mod directory affects that world, cause it has some global settings in it, that override the default ones, even if this mod is deactivated, or maybe even it wasn't deactivated ever before?

**Comment by sfan5** [comment]
The scenario is a bit different:
* You run a world using <some other game>
  * it mistakenly sets `water_level = -31000` in your minetest.conf
* You start a new world using MTG
* The setting is still in your minetest.conf -> mapgen ends up broken

**Comment by voxel-minetest** [comment]
A world...
I've probably found the evildoer here it is Wuzzy's Tutorial, it's the only world I've played since the last compiling that was not created by myself.

And viola: 
[minetest.conf of Tutorial](https://repo.or.cz/minetest_tutorial_subgame.git/blob_plain/HEAD:/minetest.conf)

I didn't know that other worlds can override my configs permanent, so thank you very much for that info @sfan5 ;-) 
Hmm.. but maybe it would be good to implement something that allows worlds/games/mods only override the global settings temporarily?

**Comment by sfan5** [comment]
`minetest.conf` is the correct way for games to temporarily set settings so if water_level indeed persists beyond that this is an engine bug.

**Comment by voxel-minetest** [comment]
I see.

**Comment by leekz-my** [comment]
> `minetest.conf` is the correct way for games to temporarily set settings so if water_level indeed persists beyond that this is an engine bug.

I'm not sure if I should necrobump this or not as I'm new to GitHub.
But anyway, this bug is reproducible for me.

Minetest Version: 5.4.1
- Tutorial by Wuzzy indeed set a global water_level of -31000 in minetest.conf and persists there.
