### ISSUE TITLE
Add an opposite for the builtin command emergeblocks

### ISSUE THREAD

**Issue by voxel-minetest** [minetest/minetest#11191]
## Problem
After a while of exploring a world (and this can also mean checking for something while testing a mod with teleporting to and loading large areas), the fps drops extremly when looking back with high viewing range, to already loaded blocks.

## Solutions
Add an unloadblocks or whatever you want to call it command (I don't get the sense of the name "emergeblocks").

**Comment by sfan5** [comment]
Commands are server-side, while keeping once-sent blocks in RAM is client-side. So this doesn't make sense as proposed.

If you want to clear cached mapblocks either rejoin the game or if you want to cache less edit this setting:
https://github.com/minetest/minetest/blob/a106bfd456509b676ccba0ac9bef75c214819028/minetest.conf.example#L1169-L1171
or this one:
https://github.com/minetest/minetest/blob/a106bfd456509b676ccba0ac9bef75c214819028/minetest.conf.example#L1173-L1176

**Comment by voxel-minetest** [comment]
Yeah I know that rejoin and I always do this, but it is annoying and wastes my lifetime... 

Anyway thx for the settings.

**Comment by NathanSalapat** [comment]
Couldn't you just turn down your viewing range?

**Comment by voxel-minetest** [comment]
> Couldn't you just turn down your viewing range?

Yeah sure but I need a high viewing range if I look for something like biomes, or mobs or whatever.
;)
