### ISSUE TITLE
Shaders don't work on Android 10

### ISSUE THREAD

**Issue by z0rti** [minetest/minetest#11208]
Shaders don't work on Android 10 (Samsung Tablet) with 5.4.0
The menu is disabled.
Is this because of Android drivers, Irrlicht engine or Minetest not supporting it?

**Comment by sfan5** [comment]
The default video driver on Android is OpenGL ES 1.0, which does not support shaders.
You can use them with ogles2, enable it by editing `video_driver` in advanced settings.

**Comment by z0rti** [comment]
I switched to ogles2, it says 'experimental'
Now the animals are black instead of white.
Testing with https://github.com/Skandarella/animalworld

**Comment by AbduSharif** [comment]
Could you provide information about your "GPU" you can see it using CPU-Z app.

**Comment by z0rti** [comment]
"Qualcomm Adreno 506"
It's the same on Amazon Fire Tablets, can't use CPU-Z there, because FireOS doesn't have play store.

**Comment by wwar-XeStro** [comment]
My android which is roughly 4 years older can run the shaders properly... with ogles2

I get a slight fps reduction but that is expected and it is good that it works...

**Comment by Zughy** [comment]
We run GLES 2.0, closing
