### ISSUE TITLE
Fix HW buffer release (10501) in Irrlicht

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11203]
With our own fork of Irrlicht #10501 can be fixed there instead of the hack.

Not sure I'll get to that any time soon, filing here to remember (or for someone to pick up)

**Comment by sfan5** [comment]
technically a duplicate of #11040 but doesn't hurt to track separately I guess.

**Comment by lhofhansl** [comment]
Sorry missed the other one. Happy to close this one.

**Comment by SmallJoker** [comment]
Closing because #11040 is a better overview for a maintenance PR.
