### ISSUE TITLE
Screenshot in fullscreen mode is all black

### ISSUE THREAD

**Issue by SolidBlock-cn** [minetest/minetest#11204]
##### Minetest version

```
5.4.1
```

##### OS / Hardware

Operating system: Windows 10
CPU:

GPU model: OpenGL
OpenGL version: 4.6.0

##### Summary

In fullscreen mode, the screenshot is totally black.
##### Steps to reproduce

In the "settings", search for "fullscreen" and set it "ON".
Use the shortcut (F12 by default) to get a screenshot.

**Comment by SmallJoker** [comment]
Duplicate of #6649 but using Windows this time.
