### ISSUE TITLE
Custom Servers not Added to Server List

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11200]
Minetest client v5.4.0 on Android OS 10 (Lineage OS 17.1)

After joining a custom server, it does not get added/saved to the server list.

[![Screenshot-20210415-170524-Minetest.png](https://i.postimg.cc/59nWNRs4/Screenshot-20210415-170524-Minetest.png)](https://postimg.cc/7bGWKmvd)

This is only an issue on my Android device. Windows client working as expected.

**Edit:** `client/serverlist` directory is not created by default on Android. After manually creating the directory, the client is able to generate the `favoriteservers.json` file & display favorite servers in the list. It appears the fix would be to have the client automatically create the directory if it isn't found.

**Comment by sfan5** [comment]
This was already fixed in 5.4.1.

**Comment by AntumDeluge** [comment]
Thank you. Any idea when 5.4.1 will be available in Google or F-droid app store?
