### ISSUE TITLE
Realistic mapgen

### ISSUE THREAD

**Issue by vladtcvs** [minetest/minetest#11213]
## Problem

Landscape is unrealistic, even with carpathian mapgen, the most unrealistic on surface is mountains

## Solutions

Use better mapgen for mountains

**Comment by vladtcvs** [comment]
Using diamond-square for mountain generation gives good results

![image](https://user-images.githubusercontent.com/3390973/115246811-e22b7b00-a12e-11eb-8d3d-263cce3e3068.png)

**Comment by SmallJoker** [comment]
I like concepts different to plain (interpolated) perlin noises. For now this mapgen is very jittery with few flat plains which are a welcome mapgen feature for people who would like to build cities. I see potential of this method when used for mountain generation, but would prefer to see it to be combined with a smoother generation as well to cover the building aspect.

Feel free to open a PR so that players can test it and give you feedback.

**Comment by vladtcvs** [comment]
Now it is just a lua prototype, it allows user to place a mountain peaks with special tool. https://github.com/vladtcvs/lord/tree/mountain.  So it works very slow now.

I'm planning to rewrite this code to c++

**Comment by vladtcvs** [comment]
> but would prefer to see it to be combined with a smoother generation as well to cover the building aspect.

Yes, of course it's a mountain generation algorythm, not the whole world

**Comment by sorcerykid** [comment]
Several years ago I posted v7 mapgen settings that I've been using to produce much more realistic terrain, equally suitable for both building and exploring.

![image](https://user-images.githubusercontent.com/24327224/115445327-54f23000-a1db-11eb-9992-d77ffab80ec3.png)

![image](https://user-images.githubusercontent.com/24327224/115445916-17da6d80-a1dc-11eb-8120-048a9cf9bed6.png)

https://forum.minetest.net/viewtopic.php?f=3&t=16792

About the only parameter that needs to be tweaked is `mgv7_np_height_select`. For one world I use `octaves = 2` and ` scale = 3`, whereas for another world I use `octaves = 4` and scale `scale = 6`. This basically controls the overall height and sharpness of mountains. In the case of all the parameters, of course, the `seed` can be customized as well.

**Comment by vladtcvs** [comment]
Yes, v7 can create good hills, but not mountains

**Comment by sorcerykid** [comment]
Yes, that is a good point. I wonder how feasible it would be to support multiple, sequential mapgens. That way v7 could be used in tandem with this mapgen for more realistic mountainous terrain.

**Comment by RichardTry** [comment]
mg_tectonic is also creates realistic mountain range.

**Comment by FreeLikeGNU** [comment]
> Yes, that is a good point. I wonder how feasible it would be to support multiple, sequential mapgens. T

Wow! This could open many possibilities, terrain gen, then generate buildings/dungeons.  Could subsequent map gens have awareness of the previously generated terrain?

**Comment by rubenwardy** [comment]
This is quite a vague issue, realistic is very subjective. I don't think there's any plans for more map generators, we already have quite a few. This doesn't mean we won't add any more, but I think this issue should be closed
