### ISSUE TITLE
New generated mapblocks contains a lot of air holes

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11212]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```
##### Mapgen details
Mapgen: v7
Seed: `7548458533891295516`
Mods that provides biomes: `ethereal`

##### OS / Hardware

Operating system: Ubuntu 20.04 LTS
CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz 4 cores

##### Summary
When I try to access some not generated map blocks at C&C City Server, I found that that map block contains a lot of air holes.
![screenshot_20210418_212207](https://user-images.githubusercontent.com/55009343/115237107-bcae6980-a14e-11eb-8c7c-a05c47ad41c9.png)
![screenshot_20210418_074521](https://user-images.githubusercontent.com/55009343/115237114-bf10c380-a14e-11eb-8f78-0261287fca39.png)
Map blocks without problem were generated at `5.4.0` or earlier, those map blocks with air holes are generated at `5.4.1`.

**Comment by sfan5** [comment]
Nothing mapgen-related was changed between 5.4.0 and 5.4.1, sounds like it's an issue with Ethereal.

**Comment by Emojigit** [comment]
Ethereal devs suggest checking the `num_emerge_threads` setting. What does this setting actually do?

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/a24899bf2dcd58916922d671ee8761448b6876e5/minetest.conf.example#L3368-L3379

Not explained there: An "emerge thread" will either load blocks from disk or run the mapgen to generate them.
