### ISSUE TITLE
Android: Can't Input Line Breaks in Formspec Multiline Text Fields

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11225]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: Android 10 (Lineage OS 17.1)

##### Summary

On the Android app, the "Enter" key is used for closing the popup editor window. So it is not possible to key in newlines when editing formspec multiline text input fields.

There is a workaround, but it is cumbersome: If you are using a keyboard, such as [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard), that can be opened without touching the formspec text input area, you can edit the formspec directly without opening a window.

A solution may be to have a setting to disable popup text input. Or dedicate the enter key to newlines instead of closing the popup (at least for multiline fields). The "Esc" key & Android action bar can always be used to close the popup window.

**Edit:** I think a simple workaround would be to have an option to disable the popup (if that doesn't already exist, I haven't checked). It would still be a bit cumbersome on small screens, but usable.

**Comment by srifqi** [comment]
How about this for multiline text input fields? We need a way to submit the text (not using Enter key), so I add a button.

![a screenshot of multiline text input dialog with done button at bottom](https://user-images.githubusercontent.com/4017302/119804053-31bd4d80-bf0a-11eb-9c3c-500ac36bf73d.png)

<details>

<summary>Code</summary>

```diff
@@ -28,11 +28,13 @@ import android.os.Bundle;
 import android.text.InputType;
 import android.view.KeyEvent;
 import android.view.View;
 import android.view.WindowManager;
 import android.view.inputmethod.InputMethodManager;
+import android.widget.Button;
 import android.widget.EditText;
+import android.widget.LinearLayout;
 
 import androidx.appcompat.app.AlertDialog;
 
 import java.util.Objects;
 
@@ -83,13 +85,16 @@ public class GameActivity extends NativeActivity {
 		runOnUiThread(() -> showDialogUI(hint, current, editType));
 	}
 
 	private void showDialogUI(String hint, String current, int editType) {
 		final AlertDialog.Builder builder = new AlertDialog.Builder(this);
-		EditText editText = new CustomEditText(this);
-		builder.setView(editText);
+		LinearLayout container = new LinearLayout(this);
+		container.setOrientation(LinearLayout.VERTICAL);
+		builder.setView(container);
 		AlertDialog alertDialog = builder.create();
+		EditText editText = new CustomEditText(this);
+		container.addView(editText);
 		editText.requestFocus();
 		editText.setHint(hint);
 		editText.setText(current);
 		final InputMethodManager imm = (InputMethodManager) getSystemService(INPUT_METHOD_SERVICE);
 		Objects.requireNonNull(imm).toggleSoftInput(InputMethodManager.SHOW_FORCED,
@@ -101,20 +106,31 @@ public class GameActivity extends NativeActivity {
 			editText.setInputType(InputType.TYPE_CLASS_TEXT |
 					InputType.TYPE_TEXT_VARIATION_PASSWORD);
 		else
 			editText.setInputType(InputType.TYPE_CLASS_TEXT);
 		editText.setSelection(editText.getText().length());
-		editText.setOnKeyListener((view, KeyCode, event) -> {
-			if (KeyCode == KeyEvent.KEYCODE_ENTER) {
+		editText.setOnKeyListener((view, keyCode, event) -> {
+			if (keyCode == KeyEvent.KEYCODE_ENTER && editType != 1) {
 				imm.hideSoftInputFromWindow(editText.getWindowToken(), 0);
 				messageReturnCode = 0;
 				messageReturnValue = editText.getText().toString();
 				alertDialog.dismiss();
 				return true;
 			}
 			return false;
 		});
+		if (editType == 1) {
+			Button doneButton = new Button(this);
+			container.addView(doneButton);
+			doneButton.setText("Done");
+			doneButton.setOnClickListener((view -> {
+				imm.hideSoftInputFromWindow(editText.getWindowToken(), 0);
+				messageReturnCode = 0;
+				messageReturnValue = editText.getText().toString();
+				alertDialog.dismiss();
+			}));
+		}
 		alertDialog.show();
 		alertDialog.setOnCancelListener(dialog -> {
 			getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN);
 			messageReturnValue = current;
 			messageReturnCode = -1;
```
</details>

(If it is okay, I will create the PR.)

**Comment by sfan5** [comment]
Looks good.

**Comment by AntumDeluge** [comment]
There are still some problems with smaller screens. If text extends past edges of input popup, button is hidden.

(can't upload images with Octodroid app, will edit in browser)

**Comment by srifqi** [comment]
I tried to limit the amount of lines to be eight lines maximum. This maybe a wrong approach, but fixes nicely (at least for my device).

**Comment by AntumDeluge** [comment]
It looks good on my device now.
