### ISSUE TITLE
Vertically flip in crossview mode on Android

### ISSUE THREAD

**Issue by playduin** [minetest/minetest#11223]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system: Android

OpenGL version: ogles1

##### Summary

Vertically flip in crossview mode on Android. How to fix it?
![bug](https://user-images.githubusercontent.com/42139865/115741376-5e74c700-a398-11eb-872e-7a76ee758cf0.jpg)

**Comment by rubenwardy** [comment]
Closing in favour of the mega issue #4874, as it has useful technical content
