### ISSUE TITLE
windows build of cmake 3.20.1 does not detect compiler & make version correctly while running from wine 6.7 on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#11236]
##### Minetest version

latest commit (4e1dcce1b145177b4b872c318e2a630cb959cc7e) from #9776 PR, also latest master

##### OS / Hardware

Operating system:  Wine 6.7 emulating Windows 7 running under Ubuntu 20.04 LTS
CPU:  Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary

Trying to run windows version of cmake 3.20.1 running under 32bit wine 6.7 prefix with mingw installed and in path fails with cmake not detecting correct toolchain (`MSYS Makefiles`), compiler and make programs even if mingw gcc/g++ compiler and msys make (providing make executable) is installed and already in path.

**PATH on wine prefix:** `C:\windows\system32;C:\windows;C:\windows\system32\wbem;C:\windows\system32;C:\windows;C:\windows\system32wbem;C:\MinGW\bin;C:\MinGW\msys\1.0\bin;C:\upx;C:\cmake\bin`
**gcc:** gcc (MinGW.org GCC Build-2) 9.2.0
**g++:** g++ (MinGW.org GCC Build-2) 9.2.0
**make:** GNU Make 3.81, i686-pc-msys

Invoked with default command line (cmake .) it fails with following errors in output:
```
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    cl

  is not a full path and was not found in the PATH.

  To use the NMake generator with Visual C++, cmake must be run from a shell
  that can use the compiler cl from the command line.  This environment is
  unable to invoke the cl compiler.  To fix this problem, run cmake from the
  Visual Studio Command Prompt (vcvarsall.bat).

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "F:/minetest/CMakeFiles/CMakeOutput.log".
See also "F:/minetest/CMakeFiles/CMakeError.log".
```
Might be wine bug as `CMakeError.log` shows `File not found` many times, shown in the log below
[CMakeError.log](https://github.com/minetest/minetest/files/6397988/CMakeError.log)

##### Steps to reproduce

1. Setup wine environment or use native windows 32 bit environment (vm, etc., untested)
   - Install wine 6.7 (winehq-devel) from winehq repository on Ubuntu 20.04 LTS
   - Run `mkdir -p /home/yourname/path/to/prefix`, replace /path/to/prefix with with actual path to prefix
   - create new wine 32bit prefix: run `WINEPREFIX=/home/yourname/path/to/prefix WINEARCH=win32 wine wineboot`
   - run `WINEPREFIX=/home/yourname/path/to/prefix WINEARCH=win32 wine cmd`
2. Install 32 bit version of mingw-get into prefix, add mingw bin directory to path env. variable, use mingw-get to install gcc, g++ & msys-make (or alternatively mingw32-make) packages
3. Install cmake to some location e.g. C:\cmake, add to bin dir to path
4. Check-out minetest using git outside of wine, optionally fetch PR commits by running git fetch origin pull/9776/head and checking out into new branch
5. Try to run cmake as long as cmake, gcc, make, etc are in path, see incorrect toolchain being detected and a subsequent cmake error complaining about compilter.

**Comment by juozaspo** [comment]
Fix: use MSYS Makefiles toochain when building using mingw under wine, it fixes many problems. running `cmake . -G "MSYS Makefiles"` avoids above error.

**Comment by juozaspo** [comment]
The fact that cmake does not detect "MSYS Makefiles" correctly is still an issue, it's better keep it open.

**Comment by sfan5** [comment]
I doubt that running under wine is a configuration supported by either MSYS or CMake. This has nothing to do with us regardless.
