### ISSUE TITLE
Visual feedback when healthbar is filled.

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#1123]
Idea: The healthbar could have a border or frame around the hearts, so the player can easily (without counting) see if the bar is full.

Would prevent waste of food. I always eat an apple to much :)

**Comment by lightonflux** [comment]
Any updates? I think i saw some server that had something like this. But i am not sure if they implemented it as a hackish mod.

**Comment by paramat** [comment]
For simplicity it could be a colour change when full.

**Comment by ObaniGemini** [comment]
A second heart image would be easy to make. Do you need one ?
Also shouldn't this be handled by mods ?

**Comment by C1ffisme** [comment]
What about instead of a red flash for when you are hurt, a green flash for when you are completely healthy?

**Comment by ObaniGemini** [comment]
no. Think about it. no

**Comment by C1ffisme** [comment]
Eh... I'm brainstorming.

Particle Effects?

**Comment by ObaniGemini** [comment]
no. Think about it. no. Really think about what you tell.
Particles would mess the game as it's a third plan feature and not instinctive.
Green screen would be hurtful for eyes and really ugly. Also maybe with a jump-scare effect.

I think the idea of just modifying the health bar a bit would be enough for such a low priority feature. Also it would be more apropriated

**Comment by C1ffisme** [comment]
@ObaniGemini Sorry for my lack of thought...

**Comment by paramat** [comment]
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by jastevenson303** [comment]
The borders around the hearts make it easier to see whether you're at full health.  Disallowing consumption of food when full would prevent the waste of precious apples.

**Comment by ThomasMonroe314** [comment]
@rubenwardy @jastevenson303 what about an effect similar to that of getting damage, but rather green instead?

**Comment by ObaniGemini** [comment]
This idea is as good as keeping the damage indicator an engine hardcode. Which obviously means it's a great one.

**Comment by ThomasMonroe314** [comment]
That and the modders can do what they please with the health bar itself without worry about mesing up with the effect

**Comment by Fixer-007** [comment]
>Would prevent waste of food. I always eat an apple to much :)

It is not just visual feedback, but other question comes up: Why the hell you are allowed to eat if you healthbar is at maximum?

**Comment by Fixer-007** [comment]
>Would prevent waste of food. I always eat an apple to much :)

It is not just visual feedback, but other question comes up: Why the hell you are allowed to eat if you healthbar is at maximum? This is partially a minetest_game problem.

**Comment by paramat** [comment]
Any core dev support?

**Comment by paramat** [comment]
> but other question comes up: Why the hell you are allowed to eat if your healthbar is at maximum?

That seems a more better solution to this.
No core dev support for 3+ years so closing. Core devs feel free to reopen if you support it.
