### ISSUE TITLE
Allow Customizing Paths for Mods, Worlds, etc.

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11235]
I don't think the client currently supports this, but I would like to be able to configure custom paths for mod, game, world, etc. directories. This would be especially helpful on Android devices that have little internal storage space. The paths could be changed to point to directories on external storage.

**Comment by sorcerykid** [comment]
> The paths could be changed to point to directories on external storage.

Can't this already be accomplished with symbolic links under Linux?

For example, on my production box the world directory for the JT2 server resides on a tmpfs filesystem. I have a symbolic link from `/home/minetest/.minetest/worlds/jt2` pointing to `/pub/worlds/jt2`. The advantage of this approach is it doesn't necessitate any changes to the Minetest configuration, as long as permissions are set correctly of course.

**Comment by wsor4035** [comment]
not sure about android, but linux/windows/macos minetest --help will literally tell you how to do this
--config, --logfile --map-dir --world further more you have the option of storing mods in /mods or /worldname/worldmods so you have some control over where mods are stored. really, the only things minetest doesnt support you giving it a directory path to is games

**Comment by AntumDeluge** [comment]
> Can't this already be accomplished with symbolic links under Linux?

Yes, but Android's storage filesystem (*sdcardfs*) does not support symbolic links.

> not sure about android, but linux/windows/macos minetest --help will tell you how to do most of them

Unfortunately, Minetest cannot be run from a command line on Android. So it cannot be executed with any arguments.

**Comment by rubenwardy** [comment]
This is now possible with the `MINETEST_MOD_PATH` env variable

Further support would be nice, I'd like to wait until some refactoring of the content management code though

**Comment by michieal** [comment]
> Can't this already be accomplished with symbolic links under Linux?

I just tried this with Ubuntu using the developers ppa version of minetest, and I can confirm that it does *NOT* follow symbolic links. 

So, I am guessing that it's a hard coded thing?

I'd really like it if it was possible for me to move it to my ssd drive without having to completely redo the mapping for my home directory.
