### ISSUE TITLE
Crash thats not related to game (i think) something abont mesh

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#11230]
##### Minetest version

```
5.4.0 
```

##### OS / Hardware

Operating system: raspbian
CPU: arm, built mt from source, raspberry pi 4 b+
##### Summary

crash, was playing on 2b2t.minetest.land, and the __*client*__ crashed
![2021-04-24-175028_1680x1050_scrot](https://user-images.githubusercontent.com/73961295/115974924-f522be80-a525-11eb-95a1-214c64d4fc93.png)

**Comment by sfan5** [comment]
`std::bad_alloc` indicates that the application ran out of RAM.

**Comment by TechDudie** [comment]
> `std::bad_alloc` indicates that the application ran out of RAM.

Oh XD ok thx
I’m not good at c
Closing
