### ISSUE TITLE
Fullscreen mode forces lowest refresh rate advertised by monitor

### ISSUE THREAD

**Issue by Hiradur** [minetest/minetest#11239]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"

Installed via Flatpak.
```

##### OS / Hardware

Operating system: Debian Buster
CPU: Core 2 Quad Q6600

GPU model: AMD Radeon HD 7770
OpenGL version: 4.6

##### Summary
When Minetest is set to run in fullscreen mode it seems to force the refresh rate of the monitor to the lowest the monitor is advertising. In my case this is 24 Hz making for a sluggish experience. I didn't find an obvious way to change the refresh rate. Even worse, the refresh rate remains set to this low value even after I quit Minetest, so it affects the desktop experience as well. I have to go to the system settings and change the monitor refresh rate after exiting the game to fix it for the desktop.

Both my laptop and desktop are affected, the laptop using an Intel HD 520 iGPU and the desktop an AMD dGPU. I also tested two different monitors, one advertises 30 Hz for the native resolution as it lowest supported refresh rate, while the other advertises 24 Hz.

I suggest to default to the refresh rate the desktop is set to and offer controls for the user to change it should he so desire.

##### Steps to reproduce
1. Use a monitor which advertises at least two supported refresh rates for the desired resolution
2. Run Minetest in fullscreen mode
3. Check the refresh rate reported by the monitor, it should be the lowest it supports

**Comment by neoh4x0r** [comment]
This is an Irrlicht issue and 1.8.4 is outdated.

Minetest 5.5.0 will use (or is using) a forked version of irrlicht v1.9.0
https://github.com/minetest/irrlicht

@Hiradur Can you try the latest development version of minetest and irrlicthMT ?

**Comment by sfan5** [comment]
Irrlicht(Mt) 1.9 still does the undesirable thing of switching the video mode.
We won't be fixing that and instead throwing it away and replacing it with borderless fullscreen.

Closing this in favor of #4921
