### ISSUE TITLE
Add function to delete player file(s)

### ISSUE THREAD

**Issue by mauvebic** [minetest/minetest#1124]
To keep the number of player files at a manageable level. 
ex: 5K after first week of server operation is not reasonable, the folder is hard to load and navigate in thunar to find the dozen or less files you want to preserve when cleaning up.

Already tried setting up a mod that would clean up the files and while it does work, minetest recreates them. (alternatively id have to rig a script that does it when it's called on server shutdown).

Use(s): so server owners can write mods that distinguish between recurring players and one-time or multiple-handle visitors, and eliminate the excess files which would otherwise remain constantly loaded.

**Comment by YuGiOhJCJ** [comment]
Awesome feature request, I hope it will come soon.
I have a lot of files for each player connected to my server and I would like to write a mod to automatically remove old players not connected since 1 year.
The delete function should remove the player file located in ~/.minetest/worlds/world/players but also remove the corresponding line stored in ~/.minetest/worlds/toto/auth.txt.

**Comment by 0-afflatus** [comment]
Good idea

**Comment by rubenwardy** [comment]
:+1: I'd like this. Should optionally remove entry from auth.txt

**Comment by C1ffisme** [comment]
It makes since, though it should only run if an insecure enviroment is given, so that mods do not start deleting people's inventories willy-nilly.

**Comment by ShadowNinja** [comment]
I wrote a program for this in C(89): http://ix.io/oyc/c

**Comment by nerzhul** [comment]
We will move our current backend to database, this issue should be closed at this point

**Comment by SmallJoker** [comment]
@mauvebic Is this request still actual when the players will be stored in a database? If yes, then we should keep this open.

**Comment by paramat** [comment]
The issue author is long gone from MT.

**Comment by nerzhul** [comment]
@SmallJoker the issue is adressed in #5475 i will expose the database feature to player files during the transition period
