### ISSUE TITLE
`inventory_overlay` ignored in inventories, HUDs and formspecs

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#11248]
##### Minetest version

```
Minetest 5.5.0-dev-7c2826cbc (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

##### OS / Hardware

Operating system: Debian 10 Buster
CPU: Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz

GPU model: NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2
OpenGL version: OpenGL 4.6.0

##### Summary

The `inventory_overlay` texture seems to be ignored in inventories, HUDs and formspecs. It seems to work fine for objects.

See the following image for an example:

![grafik](https://user-images.githubusercontent.com/7414098/117360347-f86c6180-aeb8-11eb-8764-dd07fc0ad149.png)

It works fine inside the itemframe (as an object); but the overlay texture isn't used for the item in the hotbar (note that the bands of the hoodie are wrongly colored there).

##### Steps to reproduce

1. Register the following item:
```lua
minetest.register_craftitem(":test:overlay_test", {
	description = "Test Overlay Bug",
	inventory_image = "default_cobble.png",
	inventory_overlay = "default_apple.png",
	color = "#0000aa"
})
```
2. In places, where you only see the the blueish cobble as image, you experience the described bug.
3. In places, where the (uncolored) apple is visible above the blueish cobble, it works fine.

If you prefer a real mod as an example, feel free to test it with the colorable items of the [ts_skins](https://github.com/Thomas--S/ts_skins) mod.

Unfortunately, I wasn't able to search (with `git bisect`) for the commit that caused this regression because of the various different Irrlicht versions and names. (Switching between the various Irrlicht(Mt) versions causes some trouble on my PC.)

If I recall it correctly, it worked fine in the 5.4.0-dev versions in the autumn 2020.

**Comment by sfan5** [comment]
With this fixed (simple regression, just a few lines) I see another bug with the wield mesh:
![screenshot_20210506_233309](https://user-images.githubusercontent.com/1042418/117368411-ca404f00-aec3-11eb-80a1-53e0ee17e455.png)

**Comment by Thomas--S** [comment]
Thank you for fixing this bug so quickly! :+1:
