### ISSUE TITLE
Aliased Items Don't Work with Cooking Craft Type

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11256]
##### Minetest version
```
5.4.1
```

##### OS / Hardware
Operating system: Windows 10 64-bit

##### Summary
*This might be more of a feature request than a bug.*

<del>Overriding/Replacing craft items breaks craft recipes.</del> *Overriding/Replacing craft items breaks cooking craft recipes.* Crafting does not respect aliases. Though, the craft guide mods display the recipes correctly, actually attempting the craft does not work. <del>It doesn't work in the regular crafting formspec, nor default:furnace.</del>

<del>**Edit:** The furnace things is probably not related to the regular crafting, as that seems to be an issue with the formspec field not accepting the new item.</del>

**Edit:** Sorry for lack of examples. Added some [here](https://github.com/minetest/minetest/issues/11256#issuecomment-836993845).

**Comment by AntumDeluge** [comment]
I'm sorry, I was very tired when I opened this. I seem to be mistaken, I overrode `default:coal_lump` to `mineral:coal_lump` & could still craft a torch with it. I thought it wasn't working on my local server, but I must have been dealing with an unrelated issue.

Though, the furnace does not accept the `mineral:coal_lump`. But that is obvious why. The formspec field filters explicit names & doesn't respect aliases.

Again, sorry. I should have waited until I had done more testing & hadn't been so tired.

**Comment by AntumDeluge** [comment]
I am going to re-open this because even though I was mistaken about the regular crafting, it does seem to be valid in regards to the furnace as that is defined by the "cooking" craft type. And that is [managed by the engine](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_craft.cpp).

**Comment by Zughy** [comment]
Fixed by #12310
