### ISSUE TITLE
About multilingual issues on Android

### ISSUE THREAD

**Issue by CPXMC** [minetest/minetest#11250]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

Operating system:Android
CPU:HUAWEI Kirin 710F

##### Summary

There is no zh_CN language on Android, but the pc version has

**Comment by SmallJoker** [comment]
Outdated Minetest version. This option will be included in the settings in the next release (5.5.0). As a workaround, open the Settings tab, and change the language manually to  `zh_CN`. Afterwards restart Minetest.

Further information: #10717
