### ISSUE TITLE
register_on_dieplayer is called twice if punch damage is handled by lua

### ISSUE THREAD

**Issue by savilli** [minetest/minetest#11266]
##### Minetest version
```
5.5.0-dev-69c70dd31
```

##### OS / Hardware
Operating system: Linux Ubuntu 20.10
CPU: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz

##### Summary
If you punch a player and kill them and punch damage is handled by lua mod then register_on_dieplayer callback is called twice

##### Steps to reproduce
-    Create a mod with this code:
```lua
minetest.register_on_punchplayer(function(player)
	player:set_hp(player:get_hp() - 1)
	return true
end)

minetest.register_on_dieplayer(function(player)
	local pname = player:get_player_name()
	minetest.log("warning", "Player " .. pname .. " died")
end)
```
-    Join the server as two players
-    Kill one player
-    See "Player died" message twice

```
2021-05-14 19:00:26: WARNING[Server]: Player a died
2021-05-14 19:00:26: ACTION[Server]: player b (id=2, hp=20) punched player a (id=1, hp=0), damage=1 (handled by Lua)
2021-05-14 19:00:26: WARNING[Server]: Player a died
```

**Comment by savilli** [comment]
The first call is from there https://github.com/minetest/minetest/blob/93f43c890bf53dcdfccdd87601bea60e43862861/src/script/lua_api/l_object.cpp#L242
The second call is from there https://github.com/minetest/minetest/blob/93f43c890bf53dcdfccdd87601bea60e43862861/src/network/serverpackethandler.cpp#L1135
Probably we don't need the second one if a punch is handled by Lua

**Comment by Emojigit** [comment]
> Probably we don't need the second one if a punch is handled by Lua
This WILL cause bugs, for example, after the change, if a player was blow up by a TNT, he will not receive the death message, because TNT damage is Lua-handled.

**Comment by neoh4x0r** [comment]
I would say the problem is with adding this code:
```lua
minetest.register_on_punchplayer(function(player)
	player:set_hp(player:get_hp() - 1)
	return true
end)
```
You shouldn't call **player:set_hp** inside the callback.

For example; **register_on_punchplayer** is used to calculate the player's knockback force.
https://github.com/minetest/minetest/blob/a106bfd456509b676ccba0ac9bef75c214819028/builtin/game/knockback.lua#L25

**Comment by savilli** [comment]
> because TNT damages are Lua-handled.

It's not exactly true. TNT damage is produced by Lua, not Lua-handled, and it still uses player:punch() to deal the damage. If TNT damage isn't handled by Lua, the player still will receive the death message from l_punch()

**Comment by savilli** [comment]
>  You will probably need to check if the HP is greater than 0 before calling set_hp:

Doesn't help. The issue happens when the HP == 1
