### ISSUE TITLE
Add server name, description, address and url fields to server tab

### ISSUE THREAD

**Issue by mauvebic** [minetest/minetest#1126]
I dont know why these settings aren't per-world, but i'd be nice to be able to change them on the fly when testing out different maps, mods, settings, etc.

**Comment by paramat** [comment]
Very old issue and author has long since left MT. Is this relevant or wanted anymore?
Closing in 1 month if not.

**Comment by jastevenson303** [comment]
Most game's multiplayer screens have more options, such as "description" and "max_users", which here we must enter minetest.conf or advanced settings.  Author wants these few server creation options on "Server" tab, which is no more.

**Comment by SmallJoker** [comment]
Server name and description is only relevant for public servers, which are almost always started using `minetestserver` (CLI). Unlike PvP games, the world/playground is open all the time, which leads to dedicated servers.
For the temporary server hosters, we've got a nice advanced settings dialog with a search box to find these settings easily. The server tab is no more, so I don't see a big potential in this (quite old) request.

**Comment by rubenwardy** [comment]
:-1: for said reasons
