### ISSUE TITLE
Can not fetch the serverlist for the short timeout 

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#11269]
##### Minetest version

```
Minetest 5.5.0-dev-d44f1aa (Linux)
Using Irrlicht 1.9.0mt2
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04.2 LTS
CPU: Intel(R) Xeon(R) CPU E3-1230 v5

##### Summary

```bash
ERROR[AsyncWorker-2]: servers.minetest.net/list?proto_version_min=37&proto_version_max=39 not found (Timeout was reached) (response code 200)
```
The network speed to the server here is relatively slow, so it takes about 3 minutes to retrieve the serverlist.

But the default timeout is only 3 seconds: https://github.com/minetest/minetest/blob/d44f1aabbb25a68e915a4bd5c20b72ca393ba34c/src/script/lua_api/l_http.cpp#L50

**Comment by snowyu** [comment]
Need add a new setting `http_timeout`(second) to config.

The unit of the existing `curl_timeout` setting is milliseconds(ms): https://github.com/minetest/minetest/blob/d44f1aabbb25a68e915a4bd5c20b72ca393ba34c/src/httpfetch.cpp#L45-L48

**Comment by sfan5** [comment]
We can't accommodate extremely slow networks with default settings, __but__ `curl_timeout` should work.
The http code overwriting the default value is a bug.
