### ISSUE TITLE
Sneaking while jump causes teleporting

### ISSUE THREAD

**Issue by RichardTry** [minetest/minetest#11261]
##### Minetest version
```
5.5.0-dev
```
##### Summary
If you jump and move into another node, being in air, pressing Shift teleports you to the edge of node, even if it is far from you.
Not work if node above is not air, so it seems obvious that this is a consequence of "use sneak to not to fall from edge" mechanic.

##### Steps to reproduce
Build a slab (better 1/16) tilted 90° and jump towards it from non-occupied side, pressing Shift

**Comment by appgurueu** [comment]
Could this be the cause of https://github.com/minetest/minetest/issues/11171?

**Comment by RichardTry** [comment]
I'm not sure. In you video you are not even inside the destination node. But I don't know how "use sneak to not to fall from edge" mechanism works, so maybe it triggers even from neighbour node.
P.S. It seems obvious that this is a consequence of this mechanic.

**Comment by Emojigit** [comment]
Cannot reproduce on client `5.5.0-dev-2443f1e23` and server `5.4.1`

**Comment by NeroBurner** [comment]
can't reproduce with given instructions. Could you make a video? Maybe I'm doing something wrong. I don't understand the slab 1/16 tilted 90deg instructions

**Comment by NeroBurner** [comment]
can reproduce on Minetest 5.4.1 as well

**Comment by SmallJoker** [comment]
This is intentional.
https://github.com/minetest/minetest/blob/46f42e15c41cf4ab23c5ff4cd8a7d99d94d10d7b/src/client/localplayer.cpp#L341-L348

Change `0.49` to `0.5` to get rid of this "teleporting", at the risk of falling down when releasing sneak.

**Comment by NeroBurner** [comment]
changed it to 0.5, but still get the teleporting, but falling down when releasing sneak as you predicted
