### ISSUE TITLE
Setting a default value for max_simultaneous_block_sends_server_total isn't enough.

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#1127]
``` C++
//TODO: Calculate limit dynamically
if(total_sending >= g_settings->getS32
                ("max_simultaneous_block_sends_server_total"))
        break;
```

A fixed default value causes map to load very very very slow on servers with a lot of players online.
This value seems to be somehow related to current player number.

suggested formula (current_player_number+1)*4

This formula is based on experience a t a 30+ server as well as current default value 8. Not sure if it's correct for servers with a lot more or less players.

**Comment by rubenwardy** [comment]
bump.

Any opinions on this, @nerzhul?

**Comment by nerzhul** [comment]
@rubenwardy yes this setting is not optimal, and the map loading/transfer is currently the mt core engine bottleneck when using only core + minetest_game without more mods
