### ISSUE TITLE
Can't copy text from read-ony textareas [formspec, regression]

### ISSUE THREAD

**Issue by hlqkj** [minetest/minetest#11273]
##### Minetest version

```
Minetest 5.4.0 (Windows)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10 x64 (20H2 Build 19042.985)
CPU: Intel Core i5-8250U

GPU model:
OpenGL version:

##### Summary

Since 5.4.0 the `textarea` formspec element doesn't allow to copy the selected text (via `CTRL+C` on Windows, not sure if it worked on other OSes but I assume so) if the textarea is read-only, works fine for editable ones. The 5.4.1 version seems affected too.

Note that this is a regression because it always worked in version 5.3.0 (tested) and going by memory it always did in previous ones too.

##### Steps to reproduce

Either one of the following:
- run the `/test_formspec` in a devtest game then try `CTRL+C` on the editable and read-only textareas: the attempt on the read-only one will not copy the selected text
- talking about my specific case, try to copy the item:name string from the "Result: " textarea of the unified_inventory crafting guide (upper left corner)
- or create a simple formspec with a read-only text area...

EDIT: added test on 5.4.1.

**Comment by sfan5** [comment]
> run the /test_formspec in a devtest game then try CTRL+C on the editable and read-only textareas

Which would that be? All of the text areas are editable and I can copy from all of them (tested on 5.5.0-dev).

**Comment by hlqkj** [comment]
If things didn't changed in -dev there should be one in the "Real Coords" tab, highlighed in red in the image below.

Sorry, I still don't have tested on 5.5.0-dev, will do. Also (forgive me if it's too obvious) be sure to clean your clipboard after each attempt, because if you first try on an editable one it'll appear later that also the read-only worked, as demo texts are the same.

![test_fs](https://user-images.githubusercontent.com/63740606/118522493-6a0ba180-b73c-11eb-9ac2-48dea1bf80dd.png)

**Comment by hlqkj** [comment]
Just replicated this on 5.5.0-4152227f1-win64 (latest dev I could find).

**Comment by sfan5** [comment]
Ah, I was looking in the "Styles" tab. Can reproduce.

**Comment by v-rob** [comment]
Caused by @nerzhul's refactoring on `GUIEditBox`.  Relevant lines:

https://github.com/minetest/minetest/blob/61a78cbc95e5d6be0fdb273e1493b652ed37ef4f/src/gui/guiEditBox.cpp#L250-L252

It blocks all key input for read-only elements.
