### ISSUE TITLE
Some feedback if block can't be place (e.g. because of colision with player)

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#1128]
![2014-01-30-15 21 38-minetest opengl 3 0](https://f.cloud.github.com/assets/1377943/2040661/32477c72-89ba-11e3-9775-862db340a5a0.png)
It would be nice if the player had an feedback if he/she can't place a block. E.g. when the block collides with the player.

I have no good idea for that. But i think a red box selection would be easy to implement and not interfere with mods or games like e.g. a sound.

But i think it is not the best option for colour blind player. :(

**Comment by lightonflux** [comment]
Playing a sound would be nice. Like a high pitched placing sound. 

A visual clue could be a secondary highlight or the removal of the highlight.

**Comment by PilzAdam** [comment]
I like the idea. This should somehow be changeable by mods and games.

**Comment by BlockMen** [comment]
2a12579fab7803fdee2fac2fa8a6837f131dde7a
