### ISSUE TITLE
dual monitor+fullscreen

### ISSUE THREAD

**Issue by soshimee** [minetest/minetest#11291]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/share/minetest"
STATIC_LOCALEDIR="/share/locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04
CPU: Intel Core i9-10900K

GPU model: 
OpenGL version: 

##### Summary

when enabling fullscreen and using dual monitor, the minetest window forces single display, which glitches everything out
using higher resolution for game forces the use of the left monitor, which I use as a secondary monitor and I do not want to play minetest on

##### Steps to reproduce

use two monitors with fullscreen

**Comment by sfan5** [comment]
These are all known issues which we're aware of. They'll hopefully be solved soon-ish.
Closing in favor of #4921
