### ISSUE TITLE
Certain InvRef/NodeMetaRef methods crash with invalid inventory list names

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#11294]
##### Minetest version

```
69c70dd319532f7860f211f4a527a902b0386e49
```

##### OS / Hardware

Operating system: MacOS 11.2.1
CPU: 2.3 GHz Quad-Core Intel Core i7

##### Summary

Names of inventory lists are seemingly not ~~sanitized at all~~ checked by some methods, and certain names (such as those containing spaces) either crash Minetest or cause it to freeze indefinitely. Node, player, and detached inventories are all vulnerable.

**Edit:** This applies to `InvRef:set_list`/`set_lists` and `NodeMetaRef:from_table`. `InvRef:set_size` is not affected.

The issue seems to be with [`read_inventory_list`](https://github.com/minetest/minetest/blob/master/src/script/common/c_content.cpp#L1348) not handling a `nullptr` return from `Inventory::addList`.

As a minimal reproducible example, trying to use a single space as a list name causes a crash.

##### Steps to reproduce

Start a world, teleport to the origin, and execute any of these lines of code:

```lua
minetest.get_meta({x=0, y=0, z=0}):get_inventory():set_lists({[" "] = {""}})
minetest.get_meta({x=0, y=0, z=0}):from_table({inventory = {[" "] = {""}}})
minetest.get_inventory({type="player", name="singleplayer"}):set_list(" ", {""})
minetest.create_detached_inventory("foo"); minetest.get_inventory({type="detached", name="foo"}):set_lists({[" "] = {""}})
```

**Comment by Wuzzy2** [comment]
OK, the crash is obviously a bug, and should be replaced with proper error handling. Obviously.

Minetest should not "sanitize" inventory list names at all? Inventory list names are assigned by the programmer, not the player. So if the programmer chooses a bad name, that's their fault. The game should be shut down in such a case, without crashing Minetest (of course).

I suggest:

1. The documentation should specify which list names are valid
2. If Minetest detects an invalid inventory list name, shut down the game (not Minetest) with an error message
3. Don't sanitize anything

**Comment by random-geek** [comment]
I agree, "sanitize" was probably the wrong word to use; perhaps "check" or "verify" would be better. However, there *are* some places within Minetest where strings are sanitized rather than checked (such as `ItemStackMetadata`), so I wasn't sure which was more appropriate.

**Comment by random-geek** [comment]
It seems that `NodeMetaRef:from_table` also has this issue.

Rather than returning an error on failure, would it be better for `set_list`/`set_lists` to return true/false depending on whether the operation was successful? `set_size` already does this, as does `NodeMetaRef:from_table`.

**Comment by Wuzzy2** [comment]
No, it would definitely NOT be better. It is bad practice to let the system chug along with obvious error conditions in the code, like invalid names, and try to come up with some guesses what the programmer might actually have meant. That's a bug factory. PHP does this a lot. Minetest should not become PHP.

Just stop the game. And the programmer who accidentally entered an invalid list name can quickly fix the mixtake in under a minute, just write it out clearly in the error message.
