### ISSUE TITLE
Cannot copy mod errors shown in GUI

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11293]
##### Minetest version
5.4.1

##### OS / Hardware
Linux Arch-based
##### Summary
Cannot copy paste log on screen

##### Steps to reproduce
get error windows after crash

**Comment by Emojigit** [comment]
You should copy it from `debug.txt` instead of the log in-game.

To devs: Please add the `Question` and `Possible Close` tags to this issue.

**Comment by Ygarr** [comment]
There was nothing in debug.txt in my case . How to enable logging to debug.txt?

**Comment by DeltaNedas** [comment]
its enabled by default, just make sure that you checked the right directory (e.g. if you run minetest as root for some reason /root/.minetest instead of /home/xyz/.minetest)

**Comment by SmallJoker** [comment]
Obscure description.

Which  "log on screen" are you talking about? Could you please provide an image to clarify what you mean?
If the crash itself is the problem, run the server using
```
gdb --args minetest --server (your regular options here)
r
bt
```

**Comment by Ygarr** [comment]
E.g. I got such error 
![mt2021-07-06_04-07](https://user-images.githubusercontent.com/14309871/124528353-a5f3e680-de10-11eb-9563-d9d20853558a.png)

**Comment by Ygarr** [comment]
I can select the text but CANNOT "Ctrl+C", "Ctrl+V" it.
![mt_2021-07-06_04-07](https://user-images.githubusercontent.com/14309871/124528414-c9b72c80-de10-11eb-8448-db16de826bb9.png)

**Comment by Ygarr** [comment]
Yes. This particular error is present in the file debug.txt (also there is debug.txt.1). 

But in some cases it`s not. So suggest to copy it from UI to  "caught in the act" for usability and ergonomics.

In my experience, may be depending on the debug level, not everything ends up in the file debug.txt. I will supplement this issue when I reproduce-catch a specific error.

**Comment by sfan5** [comment]
Works for me. If copy-pasting itself fails that was #7830, which is already fixed.
