### ISSUE TITLE
set_pos silently fails for attached objects

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11292]
##### Minetest version
```
5.4.0
```

##### Summary
If you use `set_pos` to move an object, this function will be a no-op if the object was attached to anything. Also, this happens silently, there's no return value. This behavior is also completely undocumented.

While it is intentional the object doesn't move while being attached, the fact that it fails *silently* is a problem.

##### Possible solutions
1) Return `false` on failure, and `true` on success
2) Set the absolute position of the attached object in the world (suggested by @hecktest)
3) Set "local position" of attached object, whatever that means (suggested by @hecktest)

2) and 3) probably require some additional work. I think with 2) you need to update offset positions to the parent, otherwise you'll end up with inconsistent data.
And for 3), there needs to be a way to get the local position. Although I think 3) feels wrong to me, since `set_pos` now suddenly means that the coordinates you input are interpreted as global OR local, and you have to awkwardly check if the object is attached before calling `set_pos` ... That doesn't sound right.

I think the only viable options are 1 or 2. I have no strong preferrence to either yet. Please discuss.

For either solution, documentation of `set_pos` must be updated.

**Comment by erlehmann** [comment]
> I think the only viable options are 1 or 2. I have no strong preferrence to either yet. Please discuss.

I want to remind everyone that existing gameplay relies on the existing behaviour, so it must not change to not break gameplay.

Simple example: In MineClone2 / Mineclonia / MineClone 5 there exists a teleporting mob called an “Enderman”. You can catch mobs using boats, as they enter a boat that you place near them automatically and can then not get out. Players rely on that to catch the Endermen.

Complex example: In MineClone2 / Mineclonia / MineClone 5 there exists a teleporting item called an “Enderpearl”. You can throw it and get teleported to the place where it lands. If the behaviour would actually change so the player position might be anywhere else while a player is attached to a mob or boat they can control, it is easy to get into some remote-control situation.

**Comment by erlehmann** [comment]
Btw, you can get an idea of how many mods would break in hilarious ways if `set_pos` would do something here by testing what happens if a player manages to die while attached to an entity that they can control and respawns in the same area. Quite a few remote control opportunities there!

**Comment by Wuzzy2** [comment]
Yeah, you're right. So that means the only sensible answer is solution 1 then. Just return true/false on failure/success (and also document current behavior, of course) because this is the only one that is backwards-compatible.

**Comment by Wuzzy2** [comment]
Possible solution 5) Do nothing, just document that `set_pos` is a no-op for attached objects.

**Comment by Wuzzy2** [comment]
I have decided for solution 5. The simplest solution.
Will be fixed in #13239.
