### ISSUE TITLE
Problem with joining a Server

### ISSUE THREAD

**Issue by Ineva-A** [minetest/minetest#11304]
##### Minetest version 5.4.0 Android
Hi im a often Player with Android but yesterday it was crazy.
For me it's like this, since I'm a moderator on a server, I also just go into the game for a short time just to help. This I have also done after about 3 hours I wanted to go back online and had to reload all the media again. As far as I know it takes only 1 time a little longer and then it goes faster.

I had this problem yesterday 2 times that I had to reload the media from scratch. My internet was great there was also no reboot.
A few days ago I also had the problem that I wanted to join and it either hangs at 0% media or hangs at 100% media.
I had to reinstall the game 3 times.

**Comment by DeltaNedas** [comment]
post your /sdcard/Minetest/debug.txt

**Comment by Ineva-A** [comment]
I have now looked through all my debug.txt and find only problems with textures or with irrlicht but nothing that indicates problems with reloading all the media. Could it be my internet after all? Or maybe my cell phone?

**Comment by Ineva-A** [comment]
Good friend helped me, 4 eyes better than 2.
And he found just this:

2021-05-29 14:03:37: WARNING[Main]: Map::getNodeMetadata(): Block not found
2021-05-29 14:03:37: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2021-05-29 14:03:37: WARNING[Main]: Map::getNodeMetadata(): Block not found
2021-05-29 14:03:37: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2021-06-01 12:15:57: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.

My phone is an Huawei p30 lite and i can use to 128gb. Playing on Android

**Comment by Emojigit** [comment]
> ##### Minetest version 5.4.0 Android
> 
> Hi im a often Player with Android but yesterday it was crazy.
> For me it's like this, since I'm a moderator on a server, I also just go into the game for a short time just to help. This I have also done after about 3 hours I wanted to go back online and had to reload all the media again. As far as I know it takes only 1 time a little longer and then it goes faster.
> 
> I had this problem yesterday 2 times that I had to reload the media from scratch. My internet was great there was also no reboot.
> A few days ago I also had the problem that I wanted to join and it either hangs at 0% media or hangs at 100% media.
> I had to reinstall the game 3 times.

1 time a little longer: download media
shorter: using cached media

**Comment by Ineva-A** [comment]
Yes I know that.  For me, however, it often charges longer and, above all, again during the day

**Comment by SmallJoker** [comment]
Locate your media directory and check whether the files are updated there after joining a new server.
What's the file system of the drive where you installed Minetest? FAT32 has a very low file limit per directory, hence could be the reason why you need to re-download often.

**Comment by rubenwardy** [comment]
Does this still happen in 5.4.2? There's been some changes to media sending and where media is stored

**Comment by wwar-XeStro** [comment]
hmmm... For me it only loads slowly the first time or if i clear cached data...

Well actually, there are servers that load slowly everytime as they use huge mods that android devises can't handle easily (nssm for example) but the first time is always slower.

Minetest 5.5.0 (was the same in previous versions. probably faster a bit.)

**Comment by Zughy** [comment]
No response from the original author after months, and wwar-XeStro comment is a bit too generic. Closing
