### ISSUE TITLE
i965: Failed to submit batchbuffer: Input/Output Error

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11309]
###### Client Version
```
Minetest 5.5.0-dev-673c29f7e (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```
###### Server Version
`5.4.1`
###### Game
MineClone2 (`mineclone5` branch)

##### OS / Hardware

Operating system: Ubuntu 20.04.2 LTS
CPU: Intel® Core™ i5-2410M CPU @ 2.30GHz × 4 

GPU model: Intel® HD Graphics 3000 (SNB GT2)
OpenGL version: OpenGL 3.0

##### Summary
```
i965: Failed to submit batchbuffer: 輸入/輸出錯誤
程式記憶體區段錯誤 (核心已傾印)
```
Translations:
輸入/輸出錯誤: Input/Output Error
程式: Program
記憶體區段錯誤: Segment Fault
核心已傾印: Core Dumped

**Comment by DeltaNedas** [comment]
you should provide a backtrace for the program (using minetest compiled with debug symbols):
```
$ gdb minetest
```

**Comment by Emojigit** [comment]
> you should provide a backtrace for the program (using minetest compiled with debug symbols):

I will provide it when I face this problem again
