### ISSUE TITLE
worlds integrated package

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest/minetest#11311]
## Problem
Make world sharing easier

## Solutions
Hope the directory structure can be recognized.
>
directory structure
* minetest-5.5.0-win64\worlds\
  * my_world
    * worldmods
    * worldtextures
    * map.sqlite
    * world.mt

**Comment by hlqkj** [comment]
I think you can already save your world-related mods in `my_world/worldmods` directory.

About textures, related issue #11295.

**Comment by SmallJoker** [comment]
wolrdmods already exists, and textures is covered by the issue mentioned above. Duplicate.
