### ISSUE TITLE
Android: builtin Scripts Aren't Updated with Update

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11317]
##### Minetest version
```
5.5.0-40acfc938
```

##### OS / Hardware
Operating system: Android 10 (LineageOS 17.1)
CPU: arm7

##### Summary
After installing update .apk, the scripts in `builtin` folder do not get updated/extracted from the new .apk. In order for them to extract, user has to go into app settings & delete app data then start client.

##### Steps to reproduce
1. Change the contents of one of the scripts in `builtin`.
2. Re-install .apk or update .apk.
3. Check if edited script has been overwritten.

There is a caveat to fixing this though: If the scripts are automatically re-extracted with an update, any customizations that a user had made to the scripts will be lost.

**Comment by rubenwardy** [comment]
The only way to detect an update is if the app version code changes. I suspect that this hasn't happened, and you've updated with the same version code
