### ISSUE TITLE
Maybe a Bug with the map

### ISSUE THREAD

**Issue by Ineva-A** [minetest/minetest#11310]
##### Minetest version 5.4.0 Android 

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Steps to reproduce
 For me, the Android app closes again as soon as I open the map. As a single player and also on the server.

**Comment by SmallJoker** [comment]
Device model?
Amount of free RAM?
Please provide the last few relevant lines in your debug.txt file.
Check logcat.

**Comment by Ineva-A** [comment]
Apparently it is indeed due to my RAM. Since I use discord in the background and have minetest open.
Thanks for the tip :)
My phone is an Huawei p30 lite.

**Comment by SmallJoker** [comment]
Minetest cannot do anything about lack of RAM, even on a model which has 8 GiB RAM. Close unnecessary background tasks and applications to free some memory. Use a low-resolution texture pack if it still crashes on "medium" modded servers.
Good luck. Closing as Minetest-unrelated issue.
