### ISSUE TITLE
Feature Request: External clipboard adapter

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#11325]
## Problem

Let's establish an interface for external clipboard adapter programs.

Clipboard may not always be reliable. While we should still address specific scenarios like #7830 , each case will take some time (in above case, 2+ years). Also there might be exotic edge cases where users don't want to run a clipboard manager at all, or quirks in other programs force them to use one that's incompatible with irrlicht.

## Solutions

Add string option `clipcopy_logfile`. When it is non-empty, all attempts to copy text to clipboard shall, in addition to their usual action, create a file whose path is the result of `strftime` on the option value, and write the to-be-copied text into that file.

## Alternatives

All that I can think of are more complicated.

**Comment by sfan5** [comment]
Why?
Once clipboard bugs in Irrlicht are (correctly) fixed Minetest will behave just as any other application and such hacks are unnecessary.

**Comment by mk-pmb** [comment]
Then maybe as a temporary feature until irrlicht is fixed?

**Comment by sfan5** [comment]
Any time spent on this is better spent on fixing clipboard operations in Irrlicht.
