### ISSUE TITLE
Artificial light increases shadow strength at night.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11321]
I noticed that artificial light (form a torch, say) increases the shadow cast by the moon,

![screenshot_20210606_211557](https://user-images.githubusercontent.com/446130/120958277-276e3100-c70c-11eb-9f05-d4e093a9ecfe.png)

@0xLiso

**Comment by Emojigit** [comment]
Please provide the minetest version and (if it is necessary) provide the log file.

**Comment by lhofhansl** [comment]
@Emojigit The shadow feature was just merged yesterday... It's the tip of the master branch.

**Comment by 0xLiso** [comment]
Hi @lhofhansl , thank you for testing it.

I did the same test and I'm not getting the same results:

![imagen](https://user-images.githubusercontent.com/25007150/121699938-b0e87f00-cacf-11eb-90e1-082a735bec21.png)

But you are right, artificial light must reduce more the shadow intensity.

Same image with the intensity adjusted:

![imagen](https://user-images.githubusercontent.com/25007150/121701454-36206380-cad1-11eb-9f51-94530d54c40b.png)



Can someone mark tag this as bug?

**Comment by lhofhansl** [comment]
Hmm... Lemme test this again. Any settings I should try?

**Comment by 0xLiso** [comment]
> Hmm... Lemme test this again. Any settings I should try?

Default medium quality
