### ISSUE TITLE
floating point exception

### ISSUE THREAD

**Issue by TechDudie** [minetest/minetest#11332]
##### Minetest version

```
5.4.0
```

##### OS / Hardware

raspberry pi 4 B+

##### Summary

I was joining tunnler's abyss when the internet seemd slow because the server list wasnt loading. I wanted to check the server ip so i cound ping test it, but the client was already connecting and i didnt know the ip address. I repeatedly CTRL-Ced and clicked X when the window closed while in the stage of Initilizing Nodes and said Floating Point Exception.
![2021-06-10-204951_1680x1050_scrot](https://user-images.githubusercontent.com/73961295/121619187-cb6a1c00-ca2d-11eb-8517-b2a5bfc9432e.png)

**Comment by sfan5** [comment]
Please run Minetest in gdb (e.g. via `gdb -ex 'set pagination off' -ex 'r' -ex 'bt' -ex 'q' --args ./bin/minetest`) and post the backtrace.

**Comment by TechDudie** [comment]
ok will do once i get gdb

**Comment by TechDudie** [comment]
hmm my first try got
[log.txt](https://github.com/minetest/minetest/files/6641326/log.txt)

**Comment by neoh4x0r** [comment]
@TechDudie That backtrace does not seem to be very useful
```
Thread 1 "minetest" received signal SIGFPE, Arithmetic exception.
raise (sig=8) at ../sysdeps/unix/sysv/linux/raise.c:50
```
> I repeatedly CTRL-Ced and clicked X when the window closed while in the stage of Initilizing Nodes and said Floating Point Exception.

I think this error occurred because you closed the client while it was **Initializing Nodes** and it crashed.

If you try to re-connect to the server (and allow it to complete)....do you still get the error?

**Comment by sfan5** [comment]
There is no backtrace at all, it only points to the code location in the libc. You need to type `bt` at the prompt to receive one (or just use the command I suggested...).

**Comment by TechDudie** [comment]
oh ok

**Comment by neoh4x0r** [comment]
@sfan5  @TechDudie Even if **bt** is used it won't give a useful backtrace unless minetest was built in debug mode.

**Comment by TechDudie** [comment]
yeah it isnt a dev version, its the official 5.4.0 release

ill build 5.4.0-dev before i reproduce the bug and hopefullt i can with luck :)
