### ISSUE TITLE
Flip "opaque water" setting to "translucent water"

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11330]
## Problem

The setting name "opaque water" is a bit inconsistent with other effect settings since enabling it disables a more complex effect. Normally, it's the other way round. This is not a bug, it's only an annoyance about inconsistency, that's all.

## Solution
Invert the setting: Rename it to "translucent water" and invert its meaning, meaning "true" stands for translucent water. There are two possible ways to do this:

1) Rename the setting completely to `translucent_water`, even internally. This will cause a minor "break" in existing Minetest installations since the old setting name won't be read anymore, thus it reverts to the default. But it's very minor since for the user it only takes a few clicks to restore it.
2) Only rename the setting at GUI level, in the main options menu page and invert the setting before presenting it to the player; leave the internal setting unchanged

Which solution do you prefer?

## See also
https://forum.minetest.net/viewtopic.php?f=3&t=26648

**Comment by sfan5** [comment]
> Which solution do you prefer?

2

**Comment by hlqkj** [comment]
> > Which solution do you prefer?
> 
> 2

Less work but more confusion in the long term imho...

**Comment by Wuzzy2** [comment]
Yeah, that's the downside of solution number 2 because of inconsistency between "All Settings" and main settings. :-(

**Comment by hecktest** [comment]
Problem: A game's liquids might already be opaque, and checking "translucent water" will not change them, possibly causing confusion. On the other hand, enabling opaque water does in fact guarantee that liquids will be opaque. (right?)
Maybe it's fine as it is.

**Comment by Warr1024** [comment]
Could just do what we did with leaves and leave it vague: "fancy" water.  Enabling it will never make water _less_ fancy than intended by the game designer.

I have seen people get tripped up by this multiple times.  They have a powerful gaming machine so they just flip all the graphic settings to "max" blindly and then dive in, only to discover later that we actually have a mix of "make the game fancy" and "make the game infancy" settings.  A little consistency would be nice.

Alternatively we could convert this (or maybe all) checkboxes to dropdowns and make it clearer in the text.  Water could be "opaque" and "normal" to make it clear we don't guarantee translucency.

Of the proposed options I like the cheaper and less disruptive option 2 better.

**Comment by Wuzzy2** [comment]
That's an interesting idea!

**Comment by weather-tracker** [comment]
like #1 
less confusion for editing code later on since all references are the same along with what the box will actually do. will need to be inverted so that if check box fancy /translucent water, it will be see-through.

**Comment by mnh48** [comment]
I support the first alternate version written by warr1024, as in, using 'fancy' for the setting

**Comment by TechPersonYT** [comment]
The only downside to option 1 seems to be compatibility with older configuration files. Perhaps `translucent_water` could be used internally and on the UI while any occurrence of `opaque_water` is replaced with its `translucent_water` inverse.

In any case, the following might be useful:

Potentially relevant line in `settingtypes.txt`: [838](https://github.com/minetest/minetest/blob/48e508052ad477eda1142f08990d523c8b9701ea/builtin/settingtypes.txt#L838)
Relevant lines in `tab_settings.lua`: [155-156](https://github.com/minetest/minetest/blob/48e508052ad477eda1142f08990d523c8b9701ea/builtin/mainmenu/tab_settings.lua#L155-L156), [265-267](https://github.com/minetest/minetest/blob/48e508052ad477eda1142f08990d523c8b9701ea/builtin/mainmenu/tab_settings.lua#L265-L267)

I'm new to this repository, so I may have missed something.

**Comment by TechPersonYT** [comment]
Pull request for option 1: #12012

This is actually my first PR on GitHub, and as such it is a draft.

**Comment by pecksin** [comment]
"**Allow** translucent liquid" would be the _correct_ label, but there is limited screen real estate.

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/pull/14660
