### ISSUE TITLE
Mapped shadows grow faint with distance from the player.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11331]
This might be by design, but I noticed that the shadow are softer the further they are from the player - this is independent from the fog setting.

The lower shadow_map_max_distance is set, the more pronounced that effect is. As I said perhaps by design, but it looks unnatural. The effect also increases when you use zoom (i.e. using binoculars in standard MT games)

**Comment by lhofhansl** [comment]
So this is by design. What threw me off is that the shadow distance is lower when zooming, which is caused by the code here:
https://github.com/minetest/minetest/blob/master/src/client/shadows/dynamicshadows.cpp#L56

**Comment by 0xLiso** [comment]
Yes it's intentional. to avoid the abrupt cut of the shadow on the limit. This is done exactly at:
https://github.com/minetest/minetest/blob/master/client/shaders/nodes_shader/opengl_fragment.glsl#L480
