### ISSUE TITLE
Cannot Connect to "localhost"

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#11337]
##### Minetest version

```
5.4.0 - 5.5.0-dev
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel x86-64

##### Summary

If I remember correctly, I used to be able to set server name to `localhost` to connect to my server from the same machine. A few years have elapsed since I was actively using Minetest, but now it does not interpret `localhost`. I have to use `127.0.0.1` or `0.0.0.0`. Is this normal, or can I assume something is messed up on my system?

Server startup:
```
...
...
        .__               __                   __
  _____ |__| ____   _____/  |_  ____   _______/  |_
 /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
|  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |
|__|_|  /__|___|  /\___  >__|  \___  >____  > |__|
      \/        \/     \/          \/     \/
2021-06-11 12:52:49: ACTION[Main]: World at [C:/Users/antum/GameData/Minetest/worlds/Antum]
2021-06-11 12:52:49: ACTION[Main]: Server for gameid="antum" listening on 0.0.0.0:30000.
```

Client input:
```
Address: localhost
Port:    30000
Result:  Connection timed out.
```

Ping test:
```cmd
C:\Users\antum>ping localhost

Pinging DESKTOP-Jordan [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

**Comment by sfan5** [comment]
`localhost` and `127.0.0.1` are not the same, `localhost` resolves to both `::1` (usually preferred) and `127.0.0.1`.
By default Minetest only listens on IPv4 which means you can only connect using `127.0.0.1`. This is normal.
