### ISSUE TITLE
Reshade download with default settings

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11347]
![screenshot_20210614_100812](https://user-images.githubusercontent.com/14309871/121963958-7e5eb080-cd73-11eb-8bbc-b59cea1a4f63.png)
![screenshot_20210614_100920](https://user-images.githubusercontent.com/14309871/121963960-7f8fdd80-cd73-11eb-9ca4-5a7347520a53.png)

Suggest feature to install reshade within Minetest (https://reshade.me/) with pre-defined comfortable settings of "tone", "tilt", "hex lens flare", "ray tracing" and "bloom" shader parameters

**Comment by lhofhansl** [comment]
Windows only, right?

**Comment by Ygarr** [comment]
Yes. At least for windows

**Comment by rubenwardy** [comment]
Hi, Minetest is cross-platform so supporting Windows-only features like this would be a no-go. Additionally, this type of tool is more of a hack than an actual good graphics practice - see how it changes the font
