### ISSUE TITLE
When mining stone got cobble

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11340]
##### Minetest version
5.4.1, 5.5.0 for Windows

After breaking node default:stone - got in inventory default:cobble. It can be considered as feature but not convenient. So need to choose stone in list by hand manually. 

Also solution can be to add "F" button to add material in inventory as in Minecraft without breaking node

**Comment by hlqkj** [comment]
It isn't considered as a feature. It *is* a feature... A feature of `minetest_game` to be precise, so you should post your _feature request_ (not bug report!) in it's own repository: https://github.com/minetest/minetest_game.

**Comment by sfan5** [comment]
duplicate of #9781
