### ISSUE TITLE
Shadows are not filtered at distance (apparent with zoom)

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11341]
Latest build from master.

![screenshot_20210612_142623](https://user-images.githubusercontent.com/446130/121789338-fff2ea80-cb89-11eb-8caa-3fab3f158caa.png)

Default "high" setting, but darkened the shadows to 0.3 and reduced shadow map texture size to 1024 to see the effect more clearly.

**Comment by lhofhansl** [comment]
Should we file one issue and collect the ongoing work there?

(Perhaps we did merge this too early...?)

**Comment by SmallJoker** [comment]
> (Perhaps we did merge this too early...?)

No. Whereas it might not work perfectly in all cases, it does work well enough to get a nice impression. Take the attachment API as example - after so many years, it's still broken in various edge-cases.

**Comment by lhofhansl** [comment]
@SmallJoker Agreed. Didn't mean it in a discouraging way. This is a great feature.

**Comment by lhofhansl** [comment]
I think zoom (i.e. smaller FOV) is general hard to get right:

![screenshot_20210613_124820](https://user-images.githubusercontent.com/446130/121820058-7ef92900-cc45-11eb-9b88-53aa5a0f70b3.png)
(Person shadow is not continuous)

![screenshot_20210613_124851](https://user-images.githubusercontent.com/446130/121820059-802a5600-cc45-11eb-9068-ed20c3f6ca84.png)
![screenshot_20210613_124853](https://user-images.githubusercontent.com/446130/121820060-815b8300-cc45-11eb-8a91-056a1f22baa1.png)
(zooming into the exact same position has the shadow vanish)

@0xLiso FYI (and again thanks for working on this and adding the first major graphics improvement to Minetest in years)
(If you tell me where to look I might have a look myself)

**Comment by lhofhansl** [comment]
I guess the part I do not quite understand is why the resolution of the shadow map texture would reduce the with the distance from the _player_, and why the FOV would have effect the rendering (other than the perspective being different).

**Comment by lhofhansl** [comment]
Looked at the code a bit more. To test I had also increased the shadow map distance. Since that sets the far clipping plane of the shadow frustrum it is now clear that it needs to be configured together with the shadow map size.

350 works well enough with a 8192 map size. So that is explained. For smaller map size, the distance has to be reduced.
For that reason I would suggest increasing the max map size. On my machine up to 10.000 worked fine. 16384 was getting quite sloe.

Still does not explain why the the far clipping plane is _closer_ with zoom - I assume this has to do the perspective calculation.
Also does not explain the shadow distortion of the player that I show above. 
And it does not explain that the shadow map texture is not filtered at a distance.

Still digging more. :)

**Comment by lhofhansl** [comment]
@0xLiso Why do we adjust for the fov here:
https://github.com/minetest/minetest/blob/master/src/client/shadows/dynamicshadows.cpp#L56
?

That reduces the distance to the far corner the smaller the fov is, I don't think that is intentional...?

**Comment by lhofhansl** [comment]
Isn't the frustrum bounding sphere diameter just the min on zFar and wanted_range (the viewing range)?

**Comment by 0xLiso** [comment]
Sorry about the delay, I'm quite busy at IRL job

> @0xLiso Why do we adjust for the fov here:
> https://github.com/minetest/minetest/blob/master/src/client/shadows/dynamicshadows.cpp#L56
> ?

No, this is to get the direction to the far frustum corner.  Anyway the calculation of the frustum is based in "stable shadow mapping"  slightly modified to match our needs.

You can see here why we use the fov/2

![imagen](https://user-images.githubusercontent.com/25007150/121950134-8873b580-cd59-11eb-82de-c8c87d16a4d7.png)

https://docs.microsoft.com/en-us/windows/win32/direct3d9/viewports-and-clipping

> That reduces the distance to the far corner the smaller the fov is, I don't think that is intentional...?
> If I remove that adjustment the radius of the shadow sphere remains the same and that shadow do not suddenly faint when I zoom.
> 
> In fact we might want to adjust in the opposite way: The smaller the fov, the larger the sphere should be (i.e. divide the tangent), but it seems fine to just remove this, and do not change the shadow strength based on the fov.
> 
> Edit: Dividing by the tan leads to a fairly natural zoom result. Just like you can "peek" through the fog with zoom, you can then also see further shadows.





I'm not sure, but I think the way to solve this is adjusting the  0.05 (5%) by something bigger related to fov in :
https://github.com/minetest/minetest/blob/master/src/client/shadows/dynamicshadows.cpp#L43

**Comment by lhofhansl** [comment]
Thanks @0xLiso. I'm also doing in between meettngs :)

I get the tan(fov/2).
What I do not get is that we use that to calculate the radius of the frustrum bounding sphere. That radius is at best independent of the FOV and it actually should be adjusted to be larger when zooming, right?

**Comment by lhofhansl** [comment]
I thought about this a bit more - between meetings :)

For a constant FOV and far plane the frustrum sphere size calculated in the code above is a constant (i.e. is does not change with camera position or orientation), and it is solely dependent on the FOV and far plane of the shadow volume.

I did some tests, and the best results I got was when it just related to the far plane (i.e. the shadow mapping distance).
So as I stated above we should be able to replace this with the zFar * <constant>. 10 worked well for the constant. That way the shadow starts to fade at the configured distance, which is what we want.
That would remove that strange behavior that shadows vanish in the zoom view and remove any dependencies on the FOV setting.

**Comment by lhofhansl** [comment]
And the main question remains: Why is the shadow map texture not filtered at a distance? :)
I see the filtering code in the shader and it is not immediately obvious why this is so.

**Comment by 0xLiso** [comment]
Can you try my dev branch ? I fixed some frustum creation issues, and I think the problem is the frustum size with so tight fov.

**Comment by lhofhansl** [comment]
Sure thing!

**Comment by 0xLiso** [comment]
Just dev 😉

https://github.com/0xLiso/minetest-shadowmap/tree/dev

**Comment by lhofhansl** [comment]
I made a similar screenshot with filtering applied at distance (texture resolution is still 1024).

![screenshot_20210617_125146](https://user-images.githubusercontent.com/446130/122463473-7e74d100-cf6a-11eb-9791-fb3ab87f4636.png)

This is a hack. I basically remove getDeltaPerspectiveFactor, not saying we should do it this way. This is just to demonstrate that I would expect the filtered shadow to look like (compare this with the first picture I posted)

**Comment by x2048** [comment]
@lhofhansl @0xLiso  I think this is connected to my work on soft shadows. I added delta perspective factor into the filtering code in fragment shader, e.g. [here](https://github.com/minetest/minetest/blob/51bf4a6e26f9eca461ae88181b06b517afc4d656/client/shaders/nodes_shader/opengl_fragment.glsl#L408) to fix many cases of distorted shadows when soft shadow radius is more than 1.

The idea is to make PCF and Poisson sampling work in world coordinates rather than SM coordinates, so that e.g. 5.0 blur radius is reduced correctly with distance. This removes the shadow artifacts but, yeah, kills filtering at large distances what SM precision is low.

**Comment by x2048** [comment]
@lhofhansl, can you take a look at whether #11385 improves your scenario?

Thank you.
