### ISSUE TITLE
Jagged north-to-south-aligned shadow edges

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#11358]
##### Minetest version
Minetest engine/client is at git commit dc165fe9, master branch, and was built thusly:

<details><summary>[Show build script...]</summary>

```bash
#!/bin/bash

# If needed, compile and install MT Irrlicht
# ~/Scripts/build-Irrlicht-MT.sh

pushd .

export CXXFLAGS="-O3"

cd /home/vanessa/Minetest-related/minetest-engine
rm -f CMakeCache.txt

make clean
cmake . -DRUN_IN_PLACE=0 -DCMAKE_BUILD_TYPE=Release \
	-DENABLE_FREETYPE=true -DENABLE_LEVELDB=true \
	-DENABLE_GETTEXT=true \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DIRRLICHT_LIBRARY=/usr/lib/x86_64-linux-gnu/libIrrlichtMt.so \
	-DIRRLICHT_INCLUDE_DIR=/usr/include/irrlichtmt/
make -j8

# install them

echo "sudo make install..."
sudo make install

popd
```
</details>

MInetest-Irrlicht is at git commit `d7127df9`, master branch, and was built thusly:
<details><summary>[Show build script...]</summary>

```bash
#!/bin/bash

pushd .

export CXXFLAGS="-O3"

# Build MT's fork of irrlicht first

cd /home/vanessa/Minetest-related/irrlicht-mt-fork/
rm -f CMakeCache.txt

cmake . -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr
make clean
make -j8
echo "sudo make install irrlicht..."
sudo make install

popd
```
</details>

##### OS / Hardware

Operating system:  Debian "bullseye"
CPU: Phenom II X6 1055T, 2.8 GHz

GPU model: AMD R9 280X (official `amdgpu` driver)
OpenGL version: 4.6

##### Summary

(In all images below, my player model is facing east, and the game time is locked at 06:00 am, unless otherwise indicated)

The edges of shadows which run north-to-south, that is, shadows cast by a horizontal strip of nodes such as a ledge or wall running north-to-south, have a rather bad jagged look.

Shadow edges running east to west, such as that produced by a tall column or pole, mostly look okay, with only a slight ripple that probably wouldn't be noticeable in a normal game setting, if one isn't looking for them.

For example:

![image](https://user-images.githubusercontent.com/1733537/122493438-afc6be80-cfb5-11eb-9a65-3557d9a87d55.png)

Here, I'm looking straight down from a height of about 27 meters from the surface.  Near the top of the image, you can see jagged north-to-south edges formed by the terrain, while closer to the bottom of the image, you can see two columns casting shadows with long east-to-west edges.

Reminds me of a cross-section of a Fresnel lens:

![image](https://user-images.githubusercontent.com/1733537/122496507-e4d51000-cfb9-11eb-83c1-2d6f384ff13f.png)
<sup>(Image credit:  https://en.wikipedia.org/wiki/Fresnel_lens#/media/File:Fresnel_lens.svg )</sup>

Getting a little closer to one of the jagged shadows:

![image](https://user-images.githubusercontent.com/1733537/122493474-c3722500-cfb5-11eb-80ee-e45f7fa73e36.png)

On all edges where it's apparent, that central bit (i.e. the center of the "Fresnel lens cross-section" effect) where the direction of the jaggies switches) follows when I move around, but always stays aligned along north-to-south shadow edges.

The higher-up I am, the more jagged the edges look, because the on-screen size of the jaggies stays the same while the terrain shrinks away "under" them (that is, compared to the nodes themselves, the jaggies are proportionally huge at larger distances).  Conversely, the closer I am, the less-pronounced the jaggies get (i.e. proportionally smaller relative to the odes).  For example:

![image](https://user-images.githubusercontent.com/1733537/122495334-d259d700-cfb7-11eb-87fd-c533bf195d19.png)

The closer the game time is to noon, the straighter the jagged edges become.  Here, for example, is a small overhang at 11:00 am:

![image](https://user-images.githubusercontent.com/1733537/122494509-8149e300-cfb7-11eb-8f5a-32cb66185229.png)

The smaller the object, the fewer jagged peaks there are, so on small stuff like signs, the shadows look bent or curved, even though they technically are not.  For example (game time is set to 08:00am):

![image](https://user-images.githubusercontent.com/1733537/122497160-f0750680-cfba-11eb-8f13-0de68211a1e9.png)

##### Steps to reproduce

Set your shader settings thus:
```
enable_waving_water = true
enable_waving_plants = true
enable_waving_leaves = false

enable_dynamic_shadows = true
shadow_map_color = false
shadow_filters = 1
shadow_levels = 3
shadow_map_texture_size = 2048
shadow_strength = 0.4
shadow_map_texture_32bit = true
shadow_map_max_distance = 350
shadow_soft_radius = 1
```

Load any world.  Shown above is just a random minetest_game test world.

**Comment by Jordach** [comment]
Shadows produced by a non directional light source tend to produce curved shadows. In this case, a point lamp is used to generate shadows, as Liso has on occasion mentioned distorting the shadowmap for no reason. It's also why nodes of the same type no longer get merged.
