### ISSUE TITLE
Entity view distance

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#11359]
## Problem

Entities disappear when they get far enough away, this can be rather troublesome for large entities such as boss mobs or large vehicles

## Solutions

Add variable into entity definition setting the max disappear distance
e.g. `max_view_distance = 500`

## Alternatives
I can't think of any alternatives

**Comment by tenplus1** [comment]
Changing active_objects_send_range_block to a higher number should fix this:

https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1436

**Comment by Extex101** [comment]
Yes but that is user defined, which really limits the game, perhaps have active_object_send_range_blocks as the default value for the client, but the server can increase it?

**Comment by sfan5** [comment]
That *is* a server-side setting.
