### ISSUE TITLE
Problem compiling Minetest on 

### ISSUE THREAD

**Issue by metropolis-nostalgia** [minetest/minetest#11356]
I seeing this while compiling Minetest 5.4.1 on Debian GNU/Linux 

I try to follow [this guide](https://github.com/minetest/minetest/blob/master/README.md#compiling) and cmake returned this message:
```

-- *** Will build version 5.5.0-dev ***
-- Could NOT find Irrlicht (missing: IRRLICHT_LIBRARY IRRLICHT_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:63 (message):
  IrrlichtMt is required to build the client, but it was not found.


-- Configuring incomplete, errors occurred!
```
I have clone the minetest source and complied the Irrlicht engine. I put the `minetest` directory in the `irrlicht` directory and run `cmake . -DRUN_IN_PLACE=TRUE` in `minetest` directory to compile the game. That is when I get the error.

**Comment by NathanSalapat** [comment]
I'm not sure if those instructions have been updated since Irrlicht was forked. Try the instructions from the forums, here: https://forum.minetest.net/viewtopic.php?f=42&t=26509

**Comment by neoh4x0r** [comment]
@metropolis-nostalgia 
That happens because cmake looks for irrlichtMT in the system path and not the source folder.
You can see that here: https://github.com/minetest/minetest/blob/master/cmake/Modules/FindIrrlicht.cmake

You probably didn't run make install after compiling irrlicht (assuming it was built as shared library).


**The following instructions were tested with the latest versions on Debian/Linux**
```
# Build IrrlichtMT as a static library (there is no need to install irrlichtMT in this case)
mkdir irrlichtMT && cd irrlichtMT
git clone https://github.com/minetest/irrlicht .
mkdir ./build && cd ./build
cmake .. -DBUILD_SHARED_LIBS=off
make -j$(nproc)
export IRRLICHT_BUILD_ROOT=$(readlink -f ..)

# Build minetest with irrlichtMT compiled in statically
cd ../../ && mkdir minetest && cd minetest
git clone https://github.com/minetest/minetest .
mkdir -p ./build/linux/ && cd ./build/linux/

export MINETEST_INSTALL_PREFIX=$HOME/minetest-build

cmake ../../ -DRUN_IN_PLACE=TRUE -DCMAKE_INSTALL_PREFIX:PATH=$MINETEST_INSTALL_PREFIX \
-DIRRLICHT_LIBRARY=$IRRLICHT_BUILD_ROOT/build/lib/Linux/libIrrlichtMt.a \
-DIRRLICHT_INCLUDE_DIR=$IRRLICHT_BUILD_ROOT/include
make -j$(nproc)
make install

# run minetest (in-place)
$MINETEST_INSTALL_PREFIX/bin/minetest
```

**Comment by metropolis-nostalgia** [comment]
At least @NathanSalapat method works in compile the source, but then I can't play minetest because Irrlicht can't call Xserver.
I think I need to start over and do again.
And I will try @neoh4x0r method.

**Comment by metropolis-nostalgia** [comment]
No, I mean I type `minetest` in Konsole (I'm a KDE fan) and have a segmentation fault of Irrlicht can't find Xserver to launch the GUI. But it work now. I launched it successfully.
