### ISSUE TITLE
Allow server to send files to clients

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11364]
## Problem

My `copier` mod wants to send save codes to the client, but it is now impossible to send it in a text file.

## Solutions

Add a server-side Lua API (also needs C++ changes) to send files to the client.
 - `minetest.send_binary_to_client(client_player_name,binary_or_string)`
 - `minetest.send_file_to_client(client_player_name,file_path)`

If the server wants to send files to old clients, the Lua function will not work and return `false`. If an old client received a file accidentally, they will just ignore that.

## Alternatives

It can also be a chat message with special characters (which cannot type from keyboards normally) with the downloading URL. Clients that support this will ask for users to download, the rest will just treat them as normal chat messages.

**Comment by sfan5** [comment]
You're missing half the story here.

The server sends a file to the client and what happens then? Does the client asks the user to save the file somewhere?
Why does this have to happen inside Minetest?

**Comment by rubenwardy** [comment]
This is better done by a web server and a link sent to the player, which becomes easier with #11092

**Comment by Emojigit** [comment]
> This is better done by a web server and a link sent to the player, which becomes easier with #11092

#11092 , why not merge? (two approves)

**Comment by rubenwardy** [comment]
> > This is better done by a web server and a link sent to the player, which becomes easier with #11092
> 
> #11092 , why not merge? (two approves)

I need to fix the code style
