### ISSUE TITLE
VS 2019 compile error

### ISSUE THREAD

**Issue by Alad53** [minetest/minetest#11363]
The error I get when compiling with visual studio 2019:

![223](https://user-images.githubusercontent.com/86076716/122624086-58088000-d0a7-11eb-8e18-c10e44866f62.JPG)

**Comment by sfan5** [comment]
That's a linking error and it looks like you have the wrong or are missing the IrrlichtMt library.

**Comment by Alad53** [comment]
Hi @sfan5,

My CMake Settings:

![234](https://user-images.githubusercontent.com/86076716/122646941-74013580-d12a-11eb-8d5e-6934e6fe45e5.JPG)

**Comment by Alad53** [comment]
CMake Cache and Log

[CMakeCache.txt](https://github.com/minetest/minetest/files/6680936/CMakeCache.txt)
[minetest.log](https://github.com/minetest/minetest/files/6680937/minetest.log)

**Comment by sfan5** [comment]
Where did you get that `libIrrlichtMt.dll.a`?
If it's from the release section of the repo it won't work: Libraries built by MinGW are not cannot be linked by MSVC.

**Comment by Alad53** [comment]
@sfan5,

What path should I follow?

I didn't use MinGW, I build with CMAKE and compile with Visual studio

libIrrlichtMt.dll.a => https://github.com/minetest/irrlicht

![235253](https://user-images.githubusercontent.com/86076716/122648409-e0336780-d131-11eb-965f-87f24ffac234.JPG)

**Comment by Alad53** [comment]
@sfan5,

New Problem :(

![123](https://user-images.githubusercontent.com/86076716/122655622-62388600-d15c-11eb-9383-76d5178481b3.JPG)

**Comment by sfan5** [comment]
What you should do here is clone https://github.com/minetest/irrlicht and build it from source.
Currently it's necessary to download WGL headers manually -> https://github.com/minetest/minetest/pull/11176#issuecomment-845156947
After that you can point Minetest's CMake to the include folder and `.lib` you have.

> libIrrlichtMt.dll.a => https://github.com/minetest/irrlicht

Yes that's exactly what I meant: If you download the compiled library from there it will <b>not</b> work.

**Comment by Alad53** [comment]
I did what you said but when building I get this error:

![235](https://user-images.githubusercontent.com/86076716/122658251-9bc8bb80-d173-11eb-83e3-5722cd556f72.JPG)

![Uploading 32.JPG…]()

**Comment by sfan5** [comment]
Since Irrlicht needs dependencies too you should build it with the VCPKG toolchain file.
