### ISSUE TITLE
/clearinv broke

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11373]
##### Minetest version
```
2db6b07de1e45c56f6135363939dbb3781336514
```

##### Summary
`/clearinv` doesn't clear inventory anymore.

##### Steps to reproduce
1. Start Development Test and do `/clearinv`.

**Comment by sfan5** [comment]
Can't reproduce on dc165fe94

**Comment by Wuzzy2** [comment]
Bug started to happen in 2db6b07de1e45c56f6135363939dbb3781336514.
@SmallJoker

**Comment by Wuzzy2** [comment]
With above commit I mean, this is the first commit which contains the bug. The commit BEFORE that does not contain the bug.

**Comment by Wuzzy2** [comment]
Also reproduced in a7143c2a8c48b234d78ec666193b942ae0b62ca3.

**Comment by sfan5** [comment]
Probably
```diff
-	size_t listsize = (forcesize > 0) ? forcesize : items.size();
+	size_t listsize = (forcesize >= 0) ? forcesize : items.size();
```

**Comment by Wuzzy2** [comment]
Nope, that change didn't do anything.

BTW, I also noticed other "fun" things that started to happen. The trash slot in DevTest and MTG stopped working as well.

**Comment by hlqkj** [comment]
L1370-1372 in src/script/common/c_content.cpp removed by 2db6b07?

**Comment by hlqkj** [comment]
> Probably
> ```diff
> -	size_t listsize = (forcesize > 0) ? forcesize : items.size();
> +	size_t listsize = (forcesize >= 0) ? forcesize : items.size();
> ```

Also this, the behaviour is now different when forcesize is zero (the old check was `!= -1`...)

**Comment by SmallJoker** [comment]
Ah yes of course. The list is only cleared when the list size changes. Totally obvious behaviour. /s
I'll simply re-add the removed `invlist->deleteItem(index);` and fix the `forcesize` condition to not break anything more.
https://github.com/minetest/minetest/blob/cec0dfcbbda1e11e5ff2f45e58ea393d0437d7c6/src/inventory.cpp#L944-L950
