### ISSUE TITLE
Clouds sometimes disappear while directly overhead

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#11381]
##### OS / Hardware

Operating system: Windows 10
CPU: Ryzen 5600x

GPU model: Radeon 5700 xt
OpenGL version: 4.6.14757

##### Summary
The clouds randomly pop out of existence sometimes, close this if that's intentional behavior

##### Steps to reproduce
Just stand there and look up

**Comment by Wuzzy2** [comment]
This sounds like a revival of #8340 which I believe was fixed.

In which version did you test this?
Try to do it in the latest dev build (please post the commit ID then).
