### ISSUE TITLE
Player model visible in first person on DirectX 9

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#11386]
Writing this down before I forget.

Setting the video driver to `direct3d9` makes the player model visible in first person (I have to set `is_visible` to false to see anything).

Version `5.4.1`, Windows (only tested on VM and WINE). Possibly happens with `direct3d8` as well.

I suspect this may have something to do with 3068853e8a58ccc7370a5ce977c08223601c497a @Jordach and even looks identical to a [previous issue (comment)](https://github.com/minetest/minetest/pull/10360#pullrequestreview-484365382) @SmallJoker experienced with it. But the fact that it only happens outside of OpenGL could point to being an Irrlicht issue.

**Comment by sfan5** [comment]
duplicate of #11052

**Comment by hecktest** [comment]
About time for #11395

**Comment by hecktest** [comment]
The D3D driver has just been removed for its lack of utility, along with other non-GL drivers.
