### ISSUE TITLE
Documented function minetest.colorspec_to_colorstring is not aviable in mod lua.

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#11397]
##### Minetest version
```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale

```

##### OS / Hardware
Operating system: Arch linux
CPU: i7

##### Summary
```lua
return minetest.colorspec_to_colorstring(color)
```
cause problem:
```
2021-06-28 10:35:45: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'staged_rocket' in callback luaentity_Step(): /home/sfence/.minetest/mods/staged_rocket/rocket_screen.lua:13: attempt to call field 'colorspec_to_colorstring' (a nil value)
```
Function is documented in [lua_api.txt](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4551)

##### Steps to reproduce
Use function minetest.colorspec_to_colorstring in mod.
For me, when I do print(dump(minetest)), I do not see colorspec_to_colorstring function. But I see sha1 function for example.

**Comment by sfan5** [comment]
You're reading the documentation for 5.5.0-dev but using 5.4.1, it's obvious there would be a mismatch at times.
