### ISSUE TITLE
Enabling anti-aliasing also enables shadows, even if shadows are disabled

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#11394]
##### Minetest version

```
Minetest 5.5.0-dev-c60a146 (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."

```

##### OS / Hardware

Operating system: Ubuntu 20.04
CPU: Intel® Celeron(R) N4100 CPU @ 1.10GHz × 4 

##### Summary
The antialiasing setting seems to collide with the dynamic shadow setting
Cant describe this bug better :-/ See the video.
https://youtu.be/VPFZCUWFWTA

##### Steps to reproduce
See the video.

**Comment by hecktest** [comment]
Confirmed. What the hell?

**Comment by sfan5** [comment]
Menu bug, I tried to be too clever:
https://github.com/minetest/minetest/blob/63fc728a84a5ba97240233ad1c5d94f1ade2deb1/builtin/mainmenu/tab_settings.lua#L369-L387

`core.settings:set("enable_dynamic_shadows", "true")` has to be moved into the last if

**Comment by AFCMS** [comment]
> Confirmed. What the hell?

Sorry, I am not very good at english, I didn't know how to name the issue :confused:
