### ISSUE TITLE
World Recording

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11390]
## Problem
On the CaptureTheFlag server, I want to monitor the server to find hackers or players trapping teammates. But it is impossible when nobody sees his hacks.

## Solutions
If the engine can provide a function to record the whole (or a part of) world and save it into a 3D animation file, it will be very easy.

**Comment by SmallJoker** [comment]
The server cannot do this. There's no rendering or whatsoever in the server.
Non-trivial issue which requires a ton of work to implement for a very special use-case. Not worth it :-1:
