### ISSUE TITLE
Scaled, world-aligned textures are aligned inconsistently for non-normal drawtypes

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#11401]
##### Minetest version

```
5.5.0-c47313db6
```

##### OS / Hardware

Operating system: Windows x64
CPU: AMD Ryzen 7 1700

GPU model: AMD Radeon RX 550
OpenGL version: 4.6.13587

##### Summary

For normal nodes, scaled and world-aligned textures behave as expected: the edges of the texture are aligned with the edges of the mapblock. For other drawtypes, however, the texture edges are not aligned with the mapblock or with the normal node textures. There seems to be some inconsistent offset applied to these textures, depending on the face:

- X+, Y+, and Z- faces: texture is translated 1 node upward.
- X- and Z+ faces: texture is translated 1 node up and 1 node to the left.
- Y- face: texture is aligned properly.

See this screenshot as an example. The two nodes have exactly the same tile definition, only one is a `nodebox` and the other is `normal`:

![image](https://user-images.githubusercontent.com/35757396/123754548-de734d80-d86f-11eb-8d9b-7ada61a0c3ec.png)

I'm guessing the issue is with [this function](https://github.com/minetest/minetest/blob/master/src/client/mapblock_mesh.cpp#L405), but I'm having trouble compiling right now, so I can't test my hypothesis.

##### Steps to reproduce

Open a devtest world, get both a tiled stair (world-aligned) and a tiled node (world-aligned) and place them side-by-side in different configurations. You will see that the two nodes' textures are not aligned relative to one another.

**Comment by celeron55** [comment]
Here's a devtest screenshot just because I happened to try it: ![tscrot-2021-06-29_10-39-14](https://user-images.githubusercontent.com/115571/123757217-6ab05f80-d8c6-11eb-86c4-173768796a0d.png)

**Comment by hecktest** [comment]
If you can't compile at the moment then please at least try to explain where you think the bug is, if you've got some sort of guess about it. Someone else could try it.
