### ISSUE TITLE
Display the registered node count when the maximum amount of registered nodes (32k) is exceeded. 

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11406]
Show actually quantity of nodes that exceeds max value

**Comment by Andrey2470T** [comment]
So what else should it show if not actually exceeded number of registered nodes?

**Comment by hlqkj** [comment]
> So what else should it show if not actually exceeded number of registered nodes?

Plain nothing in that case, no? Only show this info when needed (that is, node limit exceeded).

This is more a Feature request than a bug. But could be useful when having to plan what actions to take when a server isn't starting for that reason...

**Comment by Andrey2470T** [comment]
I seemed just to misunderstand the request itself before. Yes, it would be nice to output a current registered count of nodes.

**Comment by sfan5** [comment]
This sounds pointless since presumably registration is aborted as soon as the 32769th node is registered, thus the shown count would always be "32768".

**Comment by hlqkj** [comment]
@hecktest, changing the title has changed radically what the request was.

And about that, I had a thought and I think this should be closed. The engine _stops_ loading mods after the limit is reached, so there is no way of telling what would've come next (that is, the *exceding* number of nodes) and surely isn't worth changing this behaviour just to display that count.

**Comment by hecktest** [comment]
Well, the title was saying one thing and the post another, both quite poorly so I made a guess. The only difference is whether or not you subtract the 32k limit from the reported number.
And if sfan5 is correct, it's moot either way because it fails instantly. The counter itself might be 16 bit.

**Comment by hlqkj** [comment]
But, I assume the displayed number would be 1 if you subtract 32767 from it, no? I thought the engine stops loading in the moment the limit is reached?

**Comment by hecktest** [comment]
Yes, that's why it's useless either way.

**Comment by Ygarr** [comment]
The main problem use case is :

1. You enable one mod and get the <<maximum amount of blocks is exceeded>>
2. You began to disable other mods(almost all enabled before).
3. You still got the same error.

**Comment by celeron55** [comment]
What the engine could do is count the nodes registered so far by each mod separately and display that. Then you could see what the node hogs are and can make more informed decisions.

**Comment by Ygarr** [comment]
I think this solution is quite suitable

**Comment by SmallJoker** [comment]
> What the engine could do is count the nodes registered so far by each mod separately and display that. Then you could see what the node hogs are and can make more informed decisions.

`debug_log_level = verbose` gives
```
2021-07-17 16:39:54: VERBOSE[Main]: NodeDefManager: registering content id "1733": name="beds:fancy_bed_bottom"
2021-07-17 16:39:54: VERBOSE[Main]: NodeDefManager: registering content id "1734": name="beds:fancy_bed_top"
2021-07-17 16:39:54: VERBOSE[Main]: NodeDefManager: registering content id "1735": name="beds:bed_bottom"
2021-07-17 16:39:54: VERBOSE[Main]: NodeDefManager: registering content id "1736": name="beds:bed_top"
```

is that good enough?
