### ISSUE TITLE
"Mod not loaded due to missing dependencies" errors sometimes are hidden

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11419]
##### Minetest version
```
5.5.0
```

##### Summary
Sometimes mods don't load because they miss dependencies. This triggers errors, which are normally visible in chat. Sometimes they aren't. This is quite fun to debug, especially for game mods.

**Comment by SmallJoker** [comment]
How about other warning, such as deprecation logs? I think this issue is about more than just dependencies in specific, but rather for the entire chat scrollback which might be incomplete sometimes.

**Comment by rubenwardy** [comment]
This is fixed in 5.7.0
