### ISSUE TITLE
Flower pots sometimes get invisible in Hades Revisited

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11410]
##### Minetest version
```
062fd2190e0ac617499b19c51db609d3a923347e
```
(5.5.0-dev)

##### Summary
If Hades Revisited 0.9.2, flower pots no longer render correctly since MT 5.5.0-dev. They worked in MT 5.4.0 before just fine. If you put multiple flower pots on the ground, sometimes neighboring flower pots are made invisible (partially).
Since this bug started to happen in -dev, I don't think this is a bug in Hades Revisited. The relevant mod in Hades Revisited is `flowerpots`.

Screenshot: https://satoshiupload.com/images/SaWoEWSKuE.png

**This is a regression, please mark this for the 5.5.0 milestone.**

##### Steps to reproduce
1. Start Hades Revisited 0.9.2 in Creative Mode
2. Use the creative inventory to get some flower pots and flowers
3. Put some flower pots on the ground next to each other
4. (optional) Put some flowers into the flower pots
5. Walk in circles around the flower pots and look at them

Eventually you will notice some flower pots visually disappearing. To me, the bug will occur with and without flowers.

**Comment by sfan5** [comment]
Confirmed, but note that there is no reason for flowerpots to use alpha blending. Setting it to `clip` causes the issue not to appear.

**Comment by hecktest** [comment]
Alpha blend means no Z write so artifacts like this shouldn't be surprising. By the look of it, the pot is being partially occluded by some more transparent geometry that it's being drawn together with. (due to block batching?) Is there a transparent placeholder plant in the pot, or any other invisible cards?
We actually need a proper wireframe preview that uses a visible color instead of drawing with the same material.

**Comment by Wuzzy2** [comment]
Yes, there is an empty placeholder plant (it is a meshnode), but even if not: The bug also occurs with a flower inside. I confirmed that setting it to clip fixes it. Thankfully, I do not have any semitransparent flowers, so this is an acceptable workaround … *for me*.

I just noticed the bug also occurs with windows (in Hades Revisited): Place multiple windows behind each other and look through them, and sometimes the window behind is completely invisible. Placing a pot behind a window has the same result. Windows do use alpha blending and it is intentional (there are a few semitransparent pixels to hint at the glass design).

In 5.4.0 the nodes do not become invisible when looked behind each other. But I did note that the semitransparent pixels of the window DO make flower pots and windows behind it invisible sometimes. It's fairly subtle. This seems to be the same bug as https://github.com/minetest/minetest/issues/11119 (not new). So basically, 5.4.0 is not perfect either, but you might say it is "less broken".

However, what is new in 5.5.0-dev is that ENTIRE nodes are disappearing, even behind fully transparent pixels. There seems to be some similarity with #11119.


This PR will fix a ton of transparency-sorting related issues, so it might help: #11130

**Comment by sfan5** [comment]
Wireframe view:
![a](https://user-images.githubusercontent.com/1042418/124352076-5fc73900-dbfe-11eb-9f0d-0cdffcc72e54.png)
Bug isn't visible here because on ogles2 the shader discards fragments with zero alpha.

> Place multiple windows behind each other and look through them, and sometimes the window behind is completely invisible.

That just sounds like the old lack of depth sorting. No idea why the flower pots work in 5.4.0 but don't in 5.5.0 though.

**Comment by hecktest** [comment]
>Place multiple windows behind each other and look through them, and sometimes the window behind is completely invisible

#11130 should fix the glass-through-glass issue, I've tested it with Exile moonglass and it renders nicely.

Now keep in mind that misusing alpha blend can still lead to gremlins so the flower pot thing is definitely not something to get alarmed about. The correct thing to assume is that drawing a self-occluding alpha blended mesh is at best a precarious effort.

**Comment by sfan5** [comment]
Please re-test with Irrlicht from git (specifically 401e769114ac752dd9273c3d037b67c5a6512c98).

**Comment by Wuzzy2** [comment]
I have not seen this bug in a while now, so this seems OK.
