### ISSUE TITLE
Incomplete Documentation of 'params' sound parameter table, used by minetest.sound_play()

### ISSUE THREAD

**Issue by loffren174** [minetest/minetest#11414]
## Problem

In the lua doc, a list of all available parameters for a 'sound parameter table' is missing, as is used by the function 'minetest.sound_play()'
Even with the supplied examples, this is lacking compared to the information provided on SimpleSoundSpec in the same section, and leaves several open questions. These can only be answered by looking at least at 3 different places in the source code.

Details:

In the minetest namespace reference section of the docs, the following is written:

```
...
minetest.sound_play(spec, parameters, [ephemeral]): returns a handle

    spec is a SimpleSoundSpec
    parameters is a sound parameter table
    ephemeral is a boolean (default: false) Ephemeral sounds will...
    ...
```

In the 'Sounds' section of the docs, the following is included:

- List of all parameters available in SimpleSoundSpec tables
- Examples of SimpleSoundSpec tables
- Examples of various Sound-Parameter tables for the 'parameters' table (second argument in 'minetest.sound_play')

The following is missing:

- List of all parameters available in 'parameters' table (second argument in 'minetest.sound_play')

There is no other section in the docs which details this 'parameters' table.

Source:
     https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L848-L896
     https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L5498-L5504

Version for easier reading:
     https://minetest.gitlab.io/minetest/sounds.html
     https://minetest.gitlab.io/minetest/minetest-namespace-reference.html

## Solutions

Add more clear documentation of available values to set, whether said list is complete, and details on the meaning of individual values.

When simply combining the list of all parameters used in the examples provided for the 'parameters' table of the 'Sound' section in the lua docs, we get the following:
```
--This is a combined list of all parameters used in the examples in 'Sounds' section:

{
to_player=name, 	--play locationless to one player
pos = {x = 1, y = 2, z = 3} -- play at a spot
object = <an ObjectRef>  --play connected to an object
gain=1.0, 		--default
fade=1.0, 		--default
pitch=1,0, 		--default
loop=true,
max_hear_distance=32, 	--default, uses an euclidean metric
exclude_player=name	--heard by anyone *but* the given player
}
```
Even with the above list, there remain the following questions:

1. Are these all parameters that are available? If yes, can we add this list to the documentation? 
2. Can several players be excluded/included?
3. Do the gain and pitch values of this table... override/get replaced by/combine with ...the values given in SimpleSoundSpec?

Results of digging into the code, and answers to the questions above:

1. _Are these all parameters that are available?_
   yes, these are all available parameters for the Sound-Parameter-Table. Source:
       https://github.com/minetest/minetest/blob/master/src/server.h#L94

2. _Can several players be excluded/included?_
    only one player can be specified to be excluded from sound. Source:
        https://github.com/minetest/minetest/blob/master/src/server.cpp#L2085
    one player can be specified to be directly played the sound to. Source:
        https://github.com/minetest/minetest/blob/master/src/server.cpp#L2066

3. _Do the gain and pitch values of this table... override/get replaced by/combine with ...the values given in SimpleSoundSpec?_
    First, the input variables are taken from 'params', and then the values from SimpleSoundSpec(='spec') are taken. ~~Which means, the **pitch** of params is overwritten by the **pitch** defined in SimpleSoundSpec - while it is an optional field to define in SimpleSoundSpec, it is set to '1' (float) by default, so it _should_ always overwrite the pitch in params. _(This is something I'm not 100% certain of.)_~~
    EDIT: actual ingame tests confirmed the opposite: SSS' 'pitch' is completely ignored. SP (sound parameter table)'s 'pitch' value works as expected. When providing both tables with a 'pitch' value, SSS's is still completely ignored and does not alter the result. Thats because while the initial pitch value of SP is overwritten by SSS', when the packet gets created a few lines below, the pitch value is directly taken from SP again.
     Source:
    https://github.com/minetest/minetest/blob/master/src/server.cpp#L2116
    https://github.com/minetest/minetest/blob/master/src/server.cpp#L2123
    https://github.com/minetest/minetest/blob/master/src/sound.h#L29
    
    For the **gain**, it's a different story however: there is an additional line undoing this 'overwriting', which multiplies the **gain** set in the 'params' table with the **gain** set in the SimpleSoundSpec table (='spec'). 
    EDIT: ingame tests confirm this works as expected, both values are taken and multiplied for the result.
    Source:
    https://github.com/minetest/minetest/blob/master/src/server.cpp#L2119

## Alternatives

Keep the current documentation and let everyone search for these things when they come upon it, with a contrast between the documentation quality of 'SimpleSoundSpec' and the sound 'params' table, directly next to each other in the docs. Since there's a lot of files which touch audio, a simple search through the source is also not immediately giving the answers until you narrow it down to these three places. 

This is fine if noone ever uses the minetest.play_sound effect but only uses the inbuilt sounds functionality from node definitions etc., but incomplete when it comes to actually using the command.

EDIT NOTES: correctly included some missing values in the list as sfan5 pointed out.

**Comment by sfan5** [comment]
> Are these all parameters that are available?

You're missing `pos` and `object`.
It's also not as simple as putting the table in the docs because not all combiations are allowed:
* `max_hear_distance` does not apply to object-bound sounds (not 100% on this one)
* `loop` doesn't work with positional sounds
* only one of `object`, `pos` or `to_player` may be present

**Comment by loffren174** [comment]
> You're missing pos and object.
Ah, somehow I missed adding those from the examples they're used in. I'll correct that right away.
>  It's also not as simple as putting the table in the docs because not all combiations are allowed:
I think that reinforces the need of clear documentation.

**Comment by loffren174** [comment]
I'll work on some basic PR later to include the info I found out so far, to document this in a similar shape as 'SimpleSoundSpec', but it seems there's more to know, as sfan5 showed, and I'm not sure when I can test all of the cases.
