### ISSUE TITLE
Warn and check for conflicting incompatible mods

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11420]
Warn about different in content mods with similar names
, old mods 
and new incompatible, inconsistent mods after updates
.
Also check
 conflicting new fresh installed mod
  with worlds built-in mod 
  or inside Mod-packs

**Comment by Ygarr** [comment]
Checking module can be disabled within "All settings" check mark
Choose one of conflicting mods, conflict resolving. Or choosing last working, in order variant.

**Comment by SmallJoker** [comment]
How can conflicts be detected?

**Comment by Ygarr** [comment]
I think that the system should not give a 100% message about the conflict, but by indirect indications - such as naming and structure of files, content. report possible ambiguity in execution

**Comment by SmallJoker** [comment]
Could you please give an example of such a file structure or ambiguity? What you're requesting is very vague, and hence seemingly impossible to implement in a logical manner.
