### ISSUE TITLE
CMake: Improper set argument for VERSION_EXTRA

### ISSUE THREAD

**Issue by TSafa-23** [minetest/minetest#11428]
##### Minetest version
```
e9bc59e
```

##### OS / Hardware

Operating system: Linux Mint 19.3 Cinnamon
CPU: Intel Xeon X5680

GPU model: RTX 2060
OpenGL version: 4.6.0

##### Summary

CMakeLists.txt, line 22 should have parentheses so the value is properly set (otherwise it isn't applied). The corrected line is: `set(VERSION_STRING "${VERSION_STRING}-${VERSION_EXTRA}")`

**Comment by sfan5** [comment]
I use `VERSION_EXTRA` and know that it works so clearly it can't be as bad as you're saying.
Yet it's still better if this was quoted.

**Comment by TSafa-23** [comment]
Maybe I have an older version of cmake (still in support though) but it won't work for me at all, maybe it's handled better in newer versions
