### ISSUE TITLE
SEGFAULT when removing detached inventory during load time

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11433]
##### Minetest version
```
5.5.0-dev
```

##### Summary

Removing a detached inventory during load time causes a segmentation fault.

##### Steps to reproduce

Place the following in your mods `init.lua`:

```lua
InvRefMT = minetest.create_detached_inventory("test_detached_inv", {})
minetest.remove_detached_inventory("test_detached_inv")
-- minetest.register_on_mods_loaded(function() minetest.remove_detached_inventory("test_detached_inv") end) triggers a SEGFAULT
-- minetest.after(0, minetest.remove_detached_inventory, "test_detached_inv") will not trigger a SEGFAULT
```

**Comment by SmallJoker** [comment]
Needs the same as this
https://github.com/minetest/minetest/blob/a106bfd456509b676ccba0ac9bef75c214819028/src/server/serverinventorymgr.cpp#L134-L138

right in here
https://github.com/minetest/minetest/blob/a106bfd456509b676ccba0ac9bef75c214819028/src/server/serverinventorymgr.cpp#L160-L164

**Comment by SmallJoker** [comment]
b93bbfde2
