### ISSUE TITLE
`3d_mode = anaglyph` is broken

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#11437]
##### Minetest version

```
Minetest 5.5.0-dev-e9bc59e (Linux)
Using Irrlicht 1.9.0mt2
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu 20.04.2 LTS
CPU: Intel® Celeron(R) N4100 CPU @ 1.10GHz × 4 

GPU model: Mesa Intel® UHD Graphics 600 (GLK 2)
OpenGL version: 4.6

##### Summary
Switching 3d_mode setting to something different than "none" lead into a weird image.
Re switching 3d_mode to "none" needs a restart to get the normal image

See the video for more details.
https://youtu.be/V24gQRaigqY

##### Steps to reproduce
Switch 3d_mode to something different than "none"

**Comment by AFCMS** [comment]
I forgot to say that 3d_mode works PERFECTLY with minetest 5.4.1

**Comment by appgurueu** [comment]
@x2048 @0xLiso could this be related to the shadow PR?

**Comment by x2048** [comment]
I'm doing a bisect to confirm it.

**Comment by x2048** [comment]
I've done some testing and bisect on my side, here are the results:
* When shadow mapping is disabled, most 3D modes work fine on current master. Crossview and pageflip modes seem to be broken by something else.
* Enabled shadow mapping breaks 3d rendering. Sidebyside mode would not render anything on my machine, and anaglyph mode would render only the blue pass, not the red one.

**Comment by x2048** [comment]
Since 3d mode is only broken when dynamic shadows are enabled (which is not the default in 5.5.0), I would treat is a normal bug for shadow mapping, not a 5.5.0 regression bug.

**Comment by lhofhansl** [comment]
I find this broken even with shadow mapping disabled. Did you mean you removed the code @x2048 ?
While I do not use this often I can say this is something recent - maybe within the past 6 months or so.

**Comment by lhofhansl** [comment]
Interestingly this remains broken even after I set 3d-mode back "none" :(
Now I need to disable shaders. So probably some shaders loading issues...?

**Comment by x2048** [comment]
@lhofhansl Changing the options without restarting Minetest leads to unstable behavior of shaders. In clean starts, I have seen consistent behavior when 3d rendering was broken by shadow mapping and worked fine without on the tip of the master branch.

**Comment by lhofhansl** [comment]
@x2048 Do you know what causes this?

**Comment by x2048** [comment]
So it looks like #11491 fixes majority of the 3d modes, with only anaglyph mode causing problems.
I have checked on AMD Ryzen 7 4800H and Intel Core i5 HD 4000 on Ubuntu 20.04, and anaglyph works fine.

@sfan5 and @lhofhansl still report problems with rendering of the materials in anaglyph mode (black output).

@AFCMS would you be able to check if #11491 works for you?

@hecktest Maybe you have ideas what can cause the issue with materials / shaders in anaglyph mode, which is essentially using irrlicht video::SOverrideMaterial (see below)?

```
void RenderingCoreAnaglyph::setupMaterial(int color_mask)
{
	video::SOverrideMaterial &mat = driver->getOverrideMaterial();
	mat.Material.ColorMask = color_mask;
	mat.EnableFlags = video::EMF_COLOR_MASK;
	mat.EnablePasses = scene::ESNRP_SKY_BOX | scene::ESNRP_SOLID |
			   scene::ESNRP_TRANSPARENT | scene::ESNRP_TRANSPARENT_EFFECT |
			   scene::ESNRP_SHADOW;
}
```

**Comment by AFCMS** [comment]
> @AFCMS would you be able to check if #11491 works for you?

Not sure if I will be able to test soon :/

**Comment by AFCMS** [comment]
@x2048 I finally got the time to test (was on vacation) and sadly, my screen is still all black. :disappointed:

**Comment by Wuzzy2** [comment]
Lazy solution for 5.5 release: Ignore the `3d_mode` setting (until it is fixed). Or mark it as "experimental".

**Comment by appgurueu** [comment]
> Lazy solution for 5.5 release: Ignore the `3d_mode` setting (until it is fixed). Or mark it as "experimental".

Unacceptable. The `3d_mode` feature used to work, this is a regression.

**Comment by Wuzzy2** [comment]
OK.

**Comment by x2048** [comment]
Is Shadow Mapping is disabled, the bug should not manifest itself. @AFCMS @lhofhansl can you confirm this?

**Comment by sfan5** [comment]
Just tested with OGLES2 (where shadows don't work anyway) and `3d_mode = anaglyph` works.

**Comment by srifqi** [comment]
I tried recent master branch (206e131854392ed2d39b3456f7a1b5a54bd1bff9) using 64-bit Windows 10 (10.0.19042). Enabling or disabling `enable_dynamic_shadows` does not help.

| `3d_mode`    | Result        | Requires restart to recover? |
| ------------ | ------------- | :--------------------------: |
| `none`       | ✔️ normal      | - |
| `anaglyph`   | ❌ black (shader)/white (no shader) scene, clear blue sky | ❌ Yes |
| `interlaced` | ✔️ as intended | ✔️ No |
| `topbottom`  | ✔️ as intended | ✔️ No |
| `sidebyside` | ✔️ as intended | ✔️ No |
| `crossview`  | ✔️ as intended | ✔️ No |
| `pageflip`   | ❌ "Invalid rendering mode: pageflip" | ✔️ No |

**Comment by AFCMS** [comment]
Thanks!
