### ISSUE TITLE
Remove "You died." message from chat

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11440]
When you die, you see the message "You died." in chat. This comes from Minetest, and not the game or mod.

For game development, this is kinda annoying since you cannot get rid of this message or at least modify it. For example, if you want to do custom death messages, you are now in the awkward situation in pushing your custom death message on top of Minetest's …

I suggest to remove this hardcoded message complely. This just seems to be better design as Minetest does not interfere with game development. It should be up to the game to decide what and whether to put something in chat. This message is redundant anyway because there's a full-screen death screen.

**Comment by wsor4035** [comment]
something like https://github.com/minetest/minetest/pull/8014 would be best

**Comment by Wuzzy2** [comment]
This is literally just a one-line fix (I know what to do), this issue is actually just looking for concept approval, and if anyone has objections to the removal.

**Comment by v-rob** [comment]
Seems to make sense.  I don't think there's really any need for the chat message seeing as there's a whole formspec.

**Comment by Wuzzy2** [comment]
#11443.

**Comment by hecktest** [comment]
Deprecate builtin death already. Why is this a part of the engine?

**Comment by v-rob** [comment]
@hecktest: thoughts on how to deprecate such hardcoded features as death ~~and taxes~~?  Because compatibility must be maintained so as to not break nearly every Minetest game in existence.  I do like the idea of making many hardcoded things optional because they don't necessarily make sense at all in many games.

One possibility is to dump all hardcoded features into a table that can be removed by games, like
```lua
minetest.disable_hardcoded_features({
    death = true,
    damage = true,
    -- ...
})
-- or
minetest.disable_hardcoded_features(true) -- Disables all hardcoded features.
```

**Comment by hecktest** [comment]
That would do. I was also thinking of some interaction with `deprecated_lua_api_handling` to auto-disable everything on start but it doesn't sound right, maybe we need a better deprecation mechanism than that one. Something like OpenGL core profiles.
