### ISSUE TITLE
Add Join with Invite Code Feature

### ISSUE THREAD

**Issue by Barthdry** [minetest/minetest#11448]
## Problem

The Problem is because they don't want their ip address to leak for this reason
ie: Why is this needed?
Ex. It is quite bad i can't join my friends server easily with the code as he plays multicraft.(It is too instable)

## Solutions

Add some sort of feature into it

**Comment by rubenwardy** [comment]
This is a Multicraft specific feature, we can't add support for this - and even if we did, then Multicraft would change how it works to block us from connecting

The invite codes cost Multicraft money
