### ISSUE TITLE
"Creative Mode: Off" is shown in Esc menu when Creative Mode is actually On for you

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11458]
##### Minetest version
```
5.4.0
```

##### Summary
It is possible that in your Esc menu you see "Creative Mode: Off" when in reality the Creative Mode is actually on for you. How? Well, it could be that the game added some kind of per-player creative mode that is activated via privilege. Minetest Game does this. Hades Revisited does this, too. And probably many many MTG forks.

So, if in Minetest Game you got the Creative Mode via a priv, the Esc menu still claims that Creative Mode is off.

##### Why this is happening

The Esc menu only looks at the `creative_mode` setting, ignores anything else. This behavior is probably intended, but wrong. For players, this is still confusing, obviously, because Minetest is sending contradctionary messages.

If `creative_mode` setting is disabled, but you, the player, got Creative Mode via other means (e.g. priv), the Esc menu will be wrong.

##### Steps to reproduce
1. Start MTG with `creative_mode` setting being off
2. Grant yourself `creative` priv
3. Press Esc

##### Possible solution
The core of the problem is that Minetest is not telling the truth about Creative Mode sometimes, ignoring everything the game actually does.

I suggest: Remove the "Creative Mode: Off/On" from the Esc menu completely. This seems to be the easiest solution.

**Comment by sfan5** [comment]
Games will soon be able to get rid of the mainmenu buttons and I think hiding this text should be part of that.

**Comment by Wuzzy2** [comment]
Wait, so how is this a solution then? A per-player Creative Mode 100% makes sense and it is absolutely reasonable for games to have this. Note you cannot have a per-player Creative Mode AND also stay true to whatever is in the Esc menu, because that stuff's hardcoded. How can games possibly solve this dilemma? I don't see how. The only way to solve this on the game side is to drop per-player Creative Mode and revert back to the awful global Creative Mode. This is bad.

Putting the blame entirely on games is wrong in this case.

IMHO the global creative mode setting in Minetest is basically just a giant design flaw that we unfortunately have to deal with. The only reason we keep it is for compability, that's all. There's no good reason why games should obey the global Creative Mode paradigma, because it's a bad paradigma.

> They however will soon be able to get rid of the mainmenu buttons and I think hiding the creative / damage text should be part of that.

No, it won't be a part of that. The most easy to do in my opinion is to just drop the "Creative Mode" line in the Esc menu entirely. I don't have any idea how I know the game.conf state once I entered the game, this seems quite complex to figure out. And frankly, not even worth it.
It's much simpler to just remove the unneccessary clutter. Then games can do whatever without getting annoyed by Minetest's quirks. Minetest should be as neutral as possible.

I don't think we really *need* to have that info in the Esc menu anyway, it's not like we would be really losing anything. I highly doubt players will miss it, because it's obvious if you're in Creative Mode (just open your inventory).

Finally, I think the `creative_mode` setting should be phased out in the long term because it's inherently poor design. This might be tricky because of compability tho. :(

**Comment by sfan5** [comment]
> the global creative mode setting in Minetest is basically just a giant design flaw that we unfortunately have to deal with. 

No we don't. Like I'm saying if we give games a way to get rid of the setting and Esc menu text (or just remove that unconditionally like you're proposing) they can create whatever system they want without the engine butting in and sending contradictory messages.

**Comment by Wuzzy2** [comment]
PR: #11670
