### ISSUE TITLE
Add callback to detect when a time-of-day is reached

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11474]
## Problem

It is currently not really practical to detect when a certain time-of-day (e.g. 14:00) in the game has been reached or passed. If you want something to happen at exactly 12:00 every day, your current only option is to constantly poll the time, which isn't nice.

## Solutions

Add a callback `minetest.register_on_time_of_day_reached(func, time_of_day, accept_time_skip)`.

The function `func` is called with no arguments if the given `time_of_day` is reached.

If `accept_time_skip` is `true` (default), the time of day is also interpreted as being "reached" when said time was "skipped" by the `/time` command (e.g. if it was 14:00, you want an alert at 16:00 and you do `/time 12:00`, you have essentially jumped forwards 22 hours, skipping over 16:00, thus triggering the callback).

## Use cases

* Change the season every 10 days on midnight (Hades Revisited)
* Make a bell tower ring its bells on exactly midday and midnight (like in JT2)
* Change the moon style at midday (for moon phases)
* Update some HUD date display at midnight (without need for polling)

Note there's a nice side-effect to this callback: You can detect day changes if you set `time_of_day` to 0, this doesn't require a new function.

Note all of these things are already kinda possible, but with lower precision, as you currently have to constantly poll the time.

**Comment by Df458** [comment]
For my game I've had to build a polling-based solution for this... it would be very nice to simplify it with such a feature.

**Comment by sfan5** [comment]
I wonder if this is worth it, they only argument I can see if convenience but performance clearly isn't an issue (1 function call + some math comparisons even if multiple mods do it is *nothing*).

**Comment by Wuzzy2** [comment]
Precision is another argument. Polling is bad if you want to catch a time *exactly*. If there's a callback, you will get the expected time, with polling, there is always an impression unless you poll like crazy.
And in general, I really hate it when I have to poll anything in my code when it could be avoided.

**Comment by sfan5** [comment]
I'm suggesting to poll every server step, it doesn't get any more exact than this. Even if you implement this proposal it will just be the engine checking which callback needs to be called every step.
