### ISSUE TITLE
Please include Lithuanian translation (lt.po) from http://translate.minetest.ru/projects/minetest/core/ 

### ISSUE THREAD

**Issue by Baltix** [minetest/minetest#1148]
Please include Lithuanian translation (lt.po) from http://translate.minetest.ru/projects/minetest/core/ into https://github.com/minetest/minetest po/lt folder - currently there is untranslated lt.po file, but we already translated Minetest to Lithuanian language almost 2 months ago.

Btw, Minetest translation site http://translate.minetest.ru/projects/minetest/core/ isn't working now and I can't finish the translation :(
I only see this test at http://translate.minetest.ru/projects/minetest :
502 Bad Gateway
 nginx/1.2.1

**Comment by nerzhul** [comment]
I close the issue, translation is included at this time
