### ISSUE TITLE
Add wildcard matching support for formspec style selector

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#11481]
## Problem

Use wildcard matching can quickly apply styles to similar elements.

Such as `Title1`, `Title2` and `Body` element etc.

## Solutions

```lua
local formspec = "style[title*;border=false]" ..
  "style[title1_*;font_size=26]" ..
  "style[title2_*;font_size=24]" ..
  "button[0.5,2;3,2;title1_project;Project"
```

BTW: The [Wildcards: C++ header-only template library](https://github.com/zemasoft/wildcards) may be useful.

**Comment by v-rob** [comment]
As opposed to wildcards, I prefer an explicit "grouping" selector, like CSS `class`.  I had a PR to do this a while back, #10259, but it was closed to apparent lack of interest (or, reviewers' lack of time, depending on whom you ask).  If there was interesting in it again, I could get it back into working order.

**Comment by snowyu** [comment]
It's great. Now I have a new idea about #10259. Why not use HTML and CSS instead of formspec? Make the GUI more easy to write. And keep the `formspec_version[4]` stupid and simple for the formspec is very hard to read,  It is even more difficult to understand if many new concepts are added.

```lua
local formspec = "formspec_version[html] <button .../>"
```

This is [The fast C99 pure C library for html and css parser](https://github.com/lexbor/lexbor).

**Comment by v-rob** [comment]
HTML and CSS have been suggested many, many, many times in the past, and have been rejected because they're way too heavy for Minetest.  You can look around the issues and #6527 if you want to for more detailed reasons why.

**Comment by rubenwardy** [comment]
I concur with v-rob and would like to see a class selector instead
