### ISSUE TITLE
Can't build Minetest since latest update

### ISSUE THREAD

**Issue by randomMesh** [minetest/minetest#11497]
##### Minetest version
Latest master branch.

##### OS / Hardware
Raspberry Pi OS / Raspberry Pi 400

##### Summary
I `git pull` the latest changes to the master branch today and i can't build Minetest anymore

##### Steps to reproduce
I `git clone`d Minetest to ~/development/minetest and the fork of Irrlicht to ~/development/minetest/irrlicht

I then build Irrlicht, which works fine.
```
xxx@xxx:~/development/minetest/irrlicht $ cmake . -DBUILD_SHARED_LIBS=OFF
xxx@xxx:~/development/minetest/irrlicht $ make -j$(nproc)
```

Then i want to build Minetest and this happens:
```
xxx@xxx:~/development/minetest $ cmake . -DRUN_IN_PLACE=TRUE -DBUILD_UNITTESTS=FALSE -DIRRLICHT_INCLUDE_DIR=./irrlicht/include/ -DIRRLICHT_LIBRARY=./irrlicht/lib/Linux/libIrrlichtMt.a 
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- *** Will build version 5.5.0-dev ***
CMake Error at CMakeLists.txt:78 (message):
  IrrlichtMt is required to build the client, but it was not found.

  The Minetest team has forked Irrlicht to make their own customizations.  It
  can be found here: https://github.com/minetest/irrlicht


-- Configuring incomplete, errors occurred!
See also "/home/xxx/development/minetest/CMakeFiles/CMakeOutput.log".
```

The same procedure worked a few days ago, so i believe this must be the fault a very recent commit, maybe [this one](https://github.com/minetest/minetest/commit/cf136914cf421ee52f6806eda2fa97740d0ee552)

**Comment by sfan5** [comment]
`IRRLICHT_INCLUDE_DIR` and `IRRLICHT_LIBRARY` no longer exist for specifying the library location (since CMake needs to read some package metadata now).
For your usecase it's much easier to clone Irrlicht to `~/development/minetest/lib/irrlichtmt`, the rest will automatically be taken care of, you don't have to build the irrlicht checkout either.

**Comment by randomMesh** [comment]
> For your usecase it's much easier to clone Irrlicht to `~/development/minetest/lib/irrlichtmt`, the rest will automatically be taken care of, you don't have to build the irrlicht checkout either.

Ok, thanks. This works.

But how would i proceed if i wanted to have only one Irrlicht checkout and multiple Minetest checkouts / different branches side by side? Do i need to have mutiple Irrlicht checkouts as well or can i use a single one?

**Comment by sfan5** [comment]
> But how would i proceed if i wanted to have only one Irrlicht checkout and multiple Minetest checkouts / different branches side by side? Do i need to have mutiple Irrlicht checkouts as well or can i use a single one?

You can already use a single IrrlichtMt if you install it (this doesn't mean system-wide, it can be inside a folder), a convenient way to use an Irrlicht _checkout_ is being worked on.

> There are still these variables under "CMake options".

Yep those were missed.

**Comment by randomMesh** [comment]
Thanks for clarification, i gonna close this issue then.
