### ISSUE TITLE
Minetest Engine Not responds when switching Windows while joining servers

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#11506]
## Minetest Version
minetest 5.4.1 -win64
I have seen this problem many times, while switching between windows it just becomes not responding and i should restart the engine. I think it shouldn't cut connection while changing the window

**Comment by Emojigit** [comment]
You have to click on to the minetest window in order to re-focus on the window.

**Comment by SmallJoker** [comment]
Can anyone confirm this?

**Comment by LoneWolfHT** [comment]
Probably a duplicate issue? I can confirm Minetest (on Windows) stops responding when loading servers, it responds again fine when the loading is done though.

**Comment by Wolf1098** [comment]
seems to be back with larger mod packed servers
