### ISSUE TITLE
DualShock 4 controller L2 mapping conflict

### ISSUE THREAD

**Issue by johnsonb2** [minetest/minetest#11504]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware

Operating system: Arch Linux

##### Summary
With controller support enabled:
```
enable_joysticks = true
joystick_type = generic
```

The L2 trigger on my DualShock 4 controller maps to both selecting the previous item slot and to opening the pause menu. 

##### Steps to reproduce

In the game, pressing L2 first brings up the pause menu, then pressing it again exits the menu and then selects the previous item slot.

**Comment by rubenwardy** [comment]
We don't fully support controllers currently, and not dualshock specifically at all

See #4153
