### ISSUE TITLE
Segfault with shadow mapping on world close

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#11501]
##### Minetest version
```
Any after shadowmapping was added
```

##### OS / Hardware

Operating system: Manjaro Linux x86_64
CPU: AMD Ryzen 7 2700 (16) @ 3.200GHz

GPU model: Radeon RX 570
OpenGL version: 4.6

##### Summary
![image](https://user-images.githubusercontent.com/28972859/127699164-62384187-0739-47f4-afb9-155185f2221d.png)

##### Steps to reproduce
Join and leave a world a few times, the segfault occurs as you are exiting

**Comment by SmallJoker** [comment]
I suspect the shadow map was already freed when the client removed the wield scene node.
You could test whether this fixes your problem: `wieldmesh.cpp` in `WieldMeshSceneNode::~WieldMeshSceneNode`:
```C++
	// Remove node from shadow casters
	if (auto shadow = RenderingEngine::get_shadow_renderer())
		shadow->removeNodeFromShadowList(m_meshnode);
```

**Comment by LoneWolfHT** [comment]
> I suspect the shadow map was already freed when the client removed the wield scene node.
> You could test whether this fixes your problem: `wieldmesh.cpp` in `WieldMeshSceneNode::~WieldMeshSceneNode`:
> 
> ```c++
> 	// Remove node from shadow casters
> 	if (auto shadow = RenderingEngine::get_shadow_renderer())
> 		shadow->removeNodeFromShadowList(m_meshnode);
> ```

This seems to fix it, thanks!

**Comment by SmallJoker** [comment]
b3b075e
