### ISSUE TITLE
particle improvements proposal

### ISSUE THREAD

**Issue by velartrill** [minetest/minetest#11505]
i'd like to contribute some simple improvements to the minetest particlespawner API. i wanted to open an issue before writing any code to see if the core devs would be interested in such a feature in the first place, and if so to get feedback on my proposed improvements. please feel free to offer any suggestions or shout down in horror any and all ideas that shouldn't be implemented.

since this issue seeks to improve engine graphics, i assume it would fit on the roadmap?

# the problems

right now the minetest particle API is exceedingly barebones, and a modder is frequently forced to choose between fancy effects that are extremely costly, and dumbed-down effects that the engine can handle on its own. there are a number of reasons for this, but the biggest is that the particlespawner API offers very limited means for controlling individual particles. they can only be positioned in a uniform cube-shaped region, and given random velocities and accelerations in the same manner. this means it's possible to have particles explode outward from a point in any random direction, or to create a "planar jet" of particles in one specific direction, e.g. an energy beam or rain. however, if one wishes to generate particles in a spherical region, or assign the velocity vector of individual particles based on their distance to a specific point within that region (for instance, to create a "charging"-type effect where particles appear in a spherical region around the player and move inwards towards a point, rather than in any random direction), or a wide variety of other simple effects, the only option is doing so manually with `minetest.add_particle`.

emulating a particlespawner through this method would look something like this:

```lua
local duration = 5
local amount = 300
local interval = 0.05
local particles_per_interval = (interval / duration) * amount
local function add(timeleft)
    for p = 1, particles_per_interval do
        minetest.add_particle { --[[ calculate individual particle properties ]] }
    end
    if timeleft > 0 then
        minetest.after(interval, function() add(timeleft - interval) end)
    end
end
add(duration)
```

_for an irl implementation, [see line 252 here](https://c.hale.su/sorcery/artifact?udc=1&ln=on&name=936cc31413cf9e59)._

this is terrible for a number of reasons. firstly, it requires executing lua code over and over again at a very high frequency. secondly, every single individual particle will need its position, trajectory, and lifetime calculated by lua; every individual particle will then be transmitted over the wire to every connected client. this also means that network issues could disrupt the animation.

particlespawners address all of these issues, but at a cost of drastically lowered flexibility. (a small number of problems can be mitigated by adding multiple particlespawners in the same place but that's a hack imo.) i would therefore like to improve the flexibility of particlespawners.

# specific proposals
these are the main features i would *like* to try to implement. i'm not entirely sure i actually have the ability to implement any of them, because i haven't worked directly on the engine before and have only a passing familiarity with parts of the source code. in particular i'm not sure which (if any) of these can be implemented without breaking backwards compatibility. so no promises. if people like this idea, i'm happy to add any other reasonable, *small* suggestions others have to this list. if anyone else wants to work on this *with* me i would be super happy.

* **lifetime-animation length sync.** one of the most obnoxious problems with the current API is that, while particles can be given random lifetimes, there is no way to sync the length of a particle's animation to its lifetime. this means varying lifetimes are useful only for rapidly looping animations where the terminal frame does not matter, or for completely static particles.
* **multiple textures.** being able to specify multiple textures, or multiple texture pairs (see next) for a single emitter to pick from at random for each particle (possibly with an associated weighting value). this would save developers from having to create multiple particlespawners in the same place, possibly reducing the amount of network traffic necessary to implement such effects. alternately, a frame could be picked from a sprite sheet and used as a particle.
* **particle tweening.** there's a minor issue regarding efficient use of network bandwidth and animation smoothness. a common problem i've encountered is having a static particle that i wanted to fade out over its lifetime, and having to manually create an animated texture to achieve this. this has two problems: a much larger texture must be transmitted to each client, and the smoother the fade-out effect is to be, the larger the texture must be. ~~consequently i would like to allow the user to include an alternate texture spec which is faded in over the lifetime of the particle as the original texture is faded out.~~ (edit: i'm only going allow animation of the particle alpha; anything else will still require a sprite sheet) a new parameter could also be added to allow looping this effect, if desired. changing particle size over its lifetime would also be helpful.
* **emitter tweening.** another common problem i've encountered is wanting some aspect of the particlespawner to vary over time, such as for emission frequency to decrease over time, or for the area of the spawner itself to increase. i don't propose adding any massive keyframe system here, just a simple starting condition → ending condition blend, maybe with an ease factor, and possibly allowing this to be looped over the lifetime of the emitter. in particular, changing `{min,max}pos` over the lifetime of the emitter would be useful; parenting the emitter to an entity is fine for complex cases but for simple cases, position tweening would be a helpful addition.
* **emitter shapes.** spherical, or possibly ovoid emitters are very desirable for many effects. i would propose adding something like `float/vector emit_radius` and `vector emit_center` fields that allows a particle to be positioned within a spherical volume
* **bias.** being able to bias the random number generators for particle properties would be helpful, for example to create a spherical emitter where the density of particle generation decreases along the radius.
* **drag.** using acceleration to simulate drag breaks down when you can't know the direction or lifetime of individual particles to begin with. i would like to add a `drag` parameter that saps absolute velocity from the particle over time (only ever bringing it closer to zero), possibly as a vector so it can be prevented from interfering with e.g. gravity.
* **attraction and repulsion**. i would like to add an `attractor` field that specifies a point the particles will be oriented towards, as an alternative to selecting a uniform random velocity, and an intensity factor to control velocity magnitude that, when negative, will cause the point to repulse particles instead. (i'm not proposing adding force fields here, although that would be very useful, since it's way too complex and the math is beyond me anyway; all i'm suggesting is a mechanism to coordinate the initial orientation and velocity of the particles.) an option that causes the particles to die once they cross the attractor would be usefulf for creating charging effects. if present, the attractor/repulsor would be used instead of `{min,max}vel` on clients that support it.

# API considerations
if this proposal moves forward, it will be necessary to modify the lua API to enable access to the new features. one of three routes could be taken:

1. a new emitter creation function could be added, and mods could test whether this function was available, falling back manually to the old `minetest.add_particlespawner` function if necessary.
2. a feature flag could be created, and mods could test for the existence of this flag, structuring their call to `add_particlespawner` appropriately.
3. new fields could be added to the particlespawner definition that would simply be ignored on older servers, so that emitter definitions automatically gracefully degrade. (e.g. the provided `minpos` and `maxpos` would be sent to clients too old to support `emit_center` and `emit_radius` when a spherical emitter is used, and ignored for newer clients.) a feature flag could optionally be added to enable mod developers to fine-tune their animations on older servers.

i am weakly inclined to favor (3) just because i want to mess with as little of the engine as possible, and because it requires a minimal amount of work on the part of mod makers.

# alternatives

we could do all sorts of fancy things allowing vastly more complicated particle effects using SSCSM, but since that still isn't implemented and i see no particular sign at present that it ever will, as cool as it would be, i personally don't think there's any point in waiting for godot when we can make a meaningful improvement to the engine now. nothing about improving emitters will prevent creating SSCSM-based particle effects later, and will in fact allow for both graceful degradation and better optimization in simpler cases if and when SSCSM lands.

another possibility would be revamping the particle engine entirely to allow complex keyframe-based effects and maybe other fancy things like emitters that emit emitters; from a modder's perspective, that would be very cool and i'd be all for it in principle, but i don't remotely have the time or energy to invest in such a massive undertaking (especially without a guarantee of other coders to work with on it), so at the moment i'm only interested in offering incremental improvements.

# meta

should these new features be added all in one go, or as individual pull requests? does it matter? if no one has an opinion on this i'll do the former.

**Comment by sfan5** [comment]
Of the proposals the following sound immediately useful and doable to me: lifetime animation sync; multiple, random textures; start-end blend of parameters; shapes; attraction, repulsion

> just a simple starting condition → ending condition blend, maybe with an ease factor, and possibly allowing this to be looped over the lifetime of the emitter

The most flexible way to do this would be to just duplicate every parameter and interpolate between two sets of `ParticleSpawnerParameters` in the code but I don't know how feasible that is.

> i would like to add an attractor field that specifies a point the particles will be oriented towards, as an alternative to selecting a uniform random velocity

Instead of hardcoding this to be a point I think it'd make sense to allow lines and flat surfaces for more flexibility. This is easy to do if you take the closest point of a given volume and then calculate the velocity using it.

> if this proposal moves forward, it will be necessary to modify the lua API to enable access to the new features. one of three routes could be taken:

The way this usually works is a mix of (2) and (3).
* A feature flag is added so mods can tell whether the server even understands what they want to do. This is mostly useful to yell at the player in singleplayer to upgrade their engine.
* In Lua, new parameters get added to the table (an older server simply ignores these)
* The network protocol is extended in a backwards-compatible way, older clients just ignore the additional data and effects degrade automatically

**Comment by velartrill** [comment]
@sfan5 thanks for the feedback, i'll get started! :) i was thinking the same thing in regards to multiple sets of `ParticleSpawnerParameters` structs so i'll see if that'll work.

> Instead of hardcoding this to be a point I think it'd make sense to allow lines and flat surfaces for more flexibility. This is easy to do if you take the closest point of a given volume and then calculate the velocity using it.

at the moment i'm considering adding an `EmissionVolumeBounds` tagged union that implements box/plane/line volumes and ovoid volumes, and giving it methods that pick random points within its volume and so on. this way, emitter volumes, attractor volumes, and any other volumes that may come up in the future can all reuse the same code and adding new kinds of bounds will be trivial.

however, my original intent was to just select a random point within this volume. i'm not clear on what purpose would be served by picking the nearest point within a volume, since this isn't a force-field implementation; all it's intended to do is set the initial velocity of a particle towards or away from a point, and while i can see uses for picking the point randomly within a volume, it's harder for me to see use cases for non-point volumes -- wouldn't that effectively be equivalent to setting the attractor to the geometric center of that volume?

apologizes if i'm not getting something obvious, i have dyscalculia so i'm really really stupid when it comes to math sometimes.

> The network protocol is extended in a backwards-compatible way, older clients just ignore the additional data and effects degrade automatically

ah, does this mean in the serializer i should just unconditionally write the extra data without any version checks?

also, i noticed that currently minetest is using libc `rand(3)` as its randomness source. i wanted to ask if anyone would see any value in replacing this with the new-ish C++ STL `<random>` interface, as the libc interface is, last i heard, known to be low-quality in a number of implementations, and in particular the `rand()%delta*min` technique is biased towards smaller values due to the properties of the modulo operator. if no one thinks it matters, i'll leave it alone.

**Comment by sfan5** [comment]
> however, my original intent was to just select a random point within this volume. i'm not clear on what purpose would be served by picking the nearest point within a volume,

The case I was thinking of is you have a rod and you want particles to spawn around it(\*) and move towards it in a straight line (Y would stay constant), picking a random point wouldn't do it. Picking the closest would.

I can't think of an usecase for random point but there's pretty much always an use for such things.

(\*) No higher or lower than the rod extends.

> for non-point volumes -- wouldn't that effectively be equivalent to setting the attractor to the geometric center of that volume?

You're correct. What I'm proposing only makes sense for points, lines or surfaces so maybe "volume" is the wrong word.
The three I mentioned would fit into a minpos+maxpos, if you need more than that a helper class sounds useful.
Plus the picking of a random point (instead of closest) could be automatically enabled when the volume is non-empty.

> ah, does this mean in the serializer i should just unconditionally write the extra data without any version checks?

Yep.
On the client you'll find that it tries to unconditionally read the data and breaks out via try-catch or EOF checks (often such code already exists in the place you're looking).

> [randomness source]

We have a `myrand_range` in `src/util/numeric.h` that's hopefully better than whatever the libc has and handles the range bias problem. No idea why it wasn't used here, I could see it not mattering that much being a reason.

**Comment by velartrill** [comment]
> I can't think of an usecase for random point

mostly to add a bit of angle variation while keeping things pointed in roughly the same direction, but that's not particularly crucial

> You're correct. What I'm proposing only makes sense for points, lines or surfaces

gotcha. i'll try to process this and once i have my head wrapped around it i'll find a way to implement it as you suggest

> We have a myrand_range in src/util/numeric.h that's hopefully better than whatever the libc has and handles the range bias problem

excellent, thank you. i'll switch it over.

**Comment by velartrill** [comment]
status update: i spent most of today refactoring the particle code, since it was a bit messy, extremely verbose and repetitive. i wrote some template infrastructure that makes the code much DRYer, drastically speeding up the process of adding and removing fields of various different types.

i determined early on that reusing `ParticleSpawnerParameters` wasn't an option for many reasons, the least of which was that it would involve duplicating a lot of data that cannot be tweened. what i did instead was create a `TweenedParameter` template, which takes a type and a blending function and automatically generates a struct with fields `start` `end` and a `blend` method that takes a floating point value between 0 – 1. it doesn't handle easing yet, all transitions are purely linear, but this should be relatively trivial to add.

i wasn't sure how to handle tweening in immortal particlespawners. for now, their values never advance beyond the `start` value.

i replaced all the duplicated `min`,`max` fields with `RangedParameter` template structs. so `p.minpos` is now `p.pos.{start|end}.min`. adding new fields should require significantly less typing now. :) i also added fields for drag and attractors, but they don't do anything yet. both `RangedParameter` and `TweenedParameter` come with `serialize(std::ostream&)` and `deSerialize(std::istream&)` methods so writing such values to or reading them from a packet requires only a single call (except in the case of the newly-tweened properties that predated this change, whose start and end have to be split up in order to preserve binary protocol compatibility).

the lua API was the thorniest part. there was massive code reduplication between `src/scripts/lua_api/l_particles.cpp` and `src/scripts/lua_api/l_particles_local.cpp`. i ended up adding a new header `src/scripts/lua_api/l_particleparams.h`, where i put the templates which generate the code that inspects the parameter table. this reduced the length of both files despite the added complexity -- a single invocation of `LuaParticleParams::readTweenTable(L, "vel", p.vel)` scans for the fields `vel_tween`, `vel`, `minvel`, and `maxvel`, automatically inferring types (although new types need to be implemented in `l_particleparams.h`) and setting `p.vel` appropriately. there is still a great deal of reduplication between `l_particles.cpp` and `l_particles_local.cpp`, but i'm leaving that alone for now as i feel it's out of scope.

the new API retains total backward compatibility with the old API. old mods that add particlespawners will work exactly as before. new mods are given access to two new methods of setting parameters. every `TweenedParameter` can be set to a constant or tweened variant. e.g. the field `vel` can be defined by setting either the `vel_tween` or `vel` field. (if multiple such fields are present, the table reader assigns priority in the order `vel_tween`, `vel`, `{min|max}vel`, allowing mods to gracefully degrade.) the `vel`-type table field is added primarily for the sake of consistency, and takes a table of the form `{min = vector.new(…), max = vector.new(…)}`. the `vel_tween` field instead takes a list of such tables. it assigns the `start` property to the value indicated at `tween_table[1]` and `end` to `tween_table[#tween_table]`. any list entries between these two are ignored for the purpose of enabling forward-compatibility with a proper keyframe system if one is ever added.

an example of a new particlespawner definition is given below:

```lua
local one = vector.new(1,1,1)
local zero = vector.new(0,0,0)
minetest.add_particlespawner {
    time = 5, amount = 400;
    texture = 'fnord.png', glow = 14;
    -- values for modern clients (proto version >= 41)
    pos_tween = {
        {min = zero, max = zero};
        {min = one * -5, max = one * 5};
    };
    vel = {
        min = one * -0.5;
        max = one * 0.5;
    };
    acc = { min = zero, max = zero };
    exptime_tween = {
        {min = 0.5, max = 0.7};
        {min = 1.3, max = 3.4};
    };

    -- legacy fallback values
    minpos = one * -2.5, maxpos = one * 2.5;
    minvel = one * -0.5, maxvel = one * 0.5;
    minacc = zero, maxacc = zero;
    minexptime = 0.5, maxexptime = 3.4;
}
```

once i've finalized the API, i'll update the docs accordingly. if anyone dislikes the names i picked for new datatypes or table fields please share your objection and i'll fix them.

so far everything i've tested works perfectly, including tweening of both `range<f32>` and `range<v3f>` properties. i have yet to try connecting to a patched server from an older client, but connecting to an older server from a patched client works fine. i took pains to keep the packet structure a strict superset of the old structure (even though doing so involved scattering data around kind of awkwardly), so i don't expect major problems with back-compat.

**Comment by rubenwardy** [comment]
I would like to note the priority for particles is fixing performance by batch drawing rather than drawing each particle individually. Any new features that make this harder to do should be rejected for now

**Comment by hecktest** [comment]
@rubenwardy 
This doesn't seem to conflict with performance improvements though, that's a separate concern. Just be sure to keep the drawing logic separated from particle management logic, and it'll be fine. Drawing should be downstream from the simulation, and the simulation should not be aware of drawing.

We have two rather obvious problems with perf: one is that we spawn a scene node per particle, another is that inside that scene node, we remake the mesh in `draw()` every frame and that's just stupid. Shouldn't be hard to turn it into one scene node that caches a mesh buffer, updates it, and draws it once in draw(). It's just low on my to-do list.

@velartrill 
Would it be possible to generalize the tweeners and ranged params from start-end to an animation curve with any amount of keys? That would be a lot more powerful. Sorry if this sounds like scope creep but it might be harder to turn it into curves later if the API is only aware of a start and an end value. Animation curves would also be useful for other things.
It may also be better to separate the idea of a parameter from how it's animated, so instead of `RangedParameter<T>` it would be `AnimatedProperty<T>` or such.
Could you upload a draft PR? Maybe I'd get a better idea if I saw the code.

**Comment by velartrill** [comment]
@rubenwardy @hecktest if any of the features i've suggested sound like they would impact performance, please let me know, the last thing i want to do is make the engine any slower :) fwiw my laptop is fairly mid-range and i haven't noticed any changes so far. but yes, so far i've only touched the particle management logic; the only performance impact should be mildly more memory use per-spawner and per-particle (obviously unavoidable), and additional textures loaded when the game dev/modder chooses to make use of that feature. i haven't dug deep enough yet to figure out how to go about blending from one end of the particle transition to another, but i think that will require at most calling `setTexture` on the material on certain particle steps. (the call would be conditional on an actual change taking place, ofc.) if there's a better way to go about that please let me know, i'm not familiar with irrlicht.

> Would it be possible to generalize the tweeners and ranged params from start-end to an animation curve with any amount of keys? That would be a lot more powerful. Sorry if this sounds like scope creep but it might be harder to turn it into curves later if the API is only aware of a start and an end value. 

yes, it would, and i would love to have such a feature, i'm just not confident i can implement it. i've been keeping this in mind however. right now the engine side of things only tracks a start and end value, but i designed the new lua api parameters so that adding keyframes later won't require any changes. here's an example call from my test code. (the `L.image…:render()` calls just generate a normal texture string)

```lua
	return minetest.add_particlespawner {
		amount = 300;
		time = 4;
		-- for legacy servers
		minpos = vector.subtract(tgt.under, 0.5);
		maxpos = vector.add(tgt.under, 0.5);
		minvel = minvel, maxvel = maxvel;
		minexptime = 1, maxexptime = 2;
		minsize = 0.5, maxsize = 2;
		texture = L.image('sorcery_spark.png'):multiply(color):render();

		-- for new servers
		pos = {
			min = vector.subtract(tgt.under, 0.5);
			max = vector.add(tgt.under, 0.5);
		};
		vel_tween = { 
			{min = minvel, max = maxvel}; -- first frame
			{min = minvel * 5, max = maxvel * 5}; -- last frame
		};
		exptime = { min = 1, max = 2 };
		size = { min = 1, max = 2 };

		texpool = {
			L.image('sorcery_spark.png'):multiply(color):render();
			{
				img = {
					L.image('sorcery_spark.png'):multiply(color):render();
					L.image('sorcery_spark.png'):multiply(L.color(255,0,0)):render();
				};
			};
		};
		animation = {
                        -- this will probably need to be moved to the
                        -- individual image specs, haven't touched that yet
			type = 'vertical_frames';
			aspect_w = 16, aspect_h = 16;
			length = 2;
		};
		glow = 14;
	}
```

(`texpool` here contains a list with one string and one table. the string specifies a static texture with no additional properties, the table specifies a transition between two images with no additional properties, but things like frame positions and easing values could easily be added.)

as you can see in `vel_tween` and `texpool`, the engine is given a list of values, rather than a `{start, end}` table. currently what it does is animate between the first and last value and ignore everything between, so if we later add keyframes those won't require a table syntax change and older engines will still be able to make some sense of the keyframed table.

i'll give some thought to how difficult it would be to implement a basic keyframe system, but my gut says that should wait for a later PR unless someone else wants to work on this one with me. i will at least try to make sure switching to a keyframe system later takes as little work as possible. unfortunately i have a _really_ hard time with math so anything involving curves is going to have to be implemented by someone else, sorry >_<

> It may also be better to separate the idea of a parameter from how it's animated, so instead of RangedParameter<T> it would be AnimatedProperty<T> or such.

that's what i did :) a `RangedParameter<T>` is a T with a min and max value; e.g. instead of a `v3f minpos, maxpos` there's now a `RangedParameter<v3f> pos`. for animation, you wrap the property in an extra template `TweenedParameter<RangedParameter<v3f>, v3fBlend>` (tho there's actually an additional template in there that binds "primitive" types to serialization functions). the template gunk is hidden behind type definitions in `particles.h` so you don't actually have type this all out whenever you define a tweened vector range, it's just `ParticleParamTypes::tween_range_v3f`.

(should i rename `TweenedParameter` to `AnimatedParameter` btw?)

once i've got random texture selection hammered out (it should work already but i'm missing something) i'm going to push what i've done so far to https://github.com/velartrill/minetest so you can get some idea what the code looks like or try a test build if you want. if you like i can let you know when that's up.

**Comment by velartrill** [comment]
should i leave zwrite alone for now and wait for #10398 to be merged?

**Comment by velartrill** [comment]
i've decided i'm going to skip particle blending and instead just implement a couple different alpha animation strategies (fade out, fade in, flash, etc). the current architecture makes drawing multiple textures as part of a single particle kind of impossible and i don't know enough about irrlicht to completely rip it out and redo it. a few alpha animation options will still be a dramatic improvement

**Comment by hecktest** [comment]
That looks fine, I won't burden you with any grand generalizations; f-curves can be added later.
Performance wise, I don't think you could make particles any worse even if you tried. =]

> - `fade_freq`: how many times the fade will be repeated
That would be a count, not a frequency.

**Comment by velartrill** [comment]
@hecktest ack, you're right, will rename

**Comment by appgurueu** [comment]
The main issue is that you can't just spawn lots of them until #1414 is closed.

**Comment by velartrill** [comment]
i was unfortunately not able to figure out a good way to implement @hecktest's request for attraction lines/planes and just went with points instead for now. if anyone else wants to tweak #11545 or just suggest an API design for it + explain the necessary math to my dumb ass, we could add it now; otherwise, someone else is going to have to make a separate PR for it at some point in the future

**Comment by x2048** [comment]
@velartrill 

If I understood @hecktest 's request correctly, you can define line as two spatial vectors, origin and direction:

```
line = {
	origin = { X = 0, Y = 0, Z = 0 },
	direction = { X = 0, Y = 1, Z = 0 }
}
```

Then the math for direction of a particle towards the line would be as follows (written in Lua):

```
function direction_to_line(point, line)
	line.direction = vector.normalize(line.direction)

	local origin_to_point = vector.subtract(point, line.origin)
	local scalar_projection = vector.dot(origin_to_point, line.direction)
	local point_on_the_line = vector.add(line.origin, vector.multiply(line.direction, scalar_projection))
	return vector.normalize(vector.subtract(point_on_the_line, point))
end
```

In a similar way, a plane can be defined as origin and normal:

```
plane = {
	origin = { X = 0, Y = 1, Z = 10 },
	normal = {X = 0, Y = 1, Z = 1 }
}
```

Then the math for particle direction towards the plane would be:

```
function direction_to_plane(point, plane)
	plane.normal = vector.normalize(plane.normal)

	local point_to_origin = vector.subtract(plane.origin, point)
	local factor = vector.dot(plane.normal, point_to_origin)
	if math.abs(factor) == 0 then
		return plane.normal
	end
	factor = factor / math.abs(factor)
	return vector.multiply(plane.normal, factor)
end
```

Looking at he examples above, the API would be:

```
minetest.add_particle_spawner {
  ...
  attractor = {
    point = { ... } 
    -- or
    line = { origin = { ... } , direction = { ... } }
    -- or
    plane = { origin = { ... }, normal = { ... } }
  }
}
```

Hope this helps, and I'll be glad to help when needed.

**Comment by velartrill** [comment]
@x2048 yes thank you so much! i'll implement this as soon as i can; my grandfather just passed away so it hasn't been a great time to work on FOSS stuff unfortunately

**Comment by x2048** [comment]
Oh, sorry so much for your loss. Sure, this will wait for a better time.

**Comment by sorcerykid** [comment]
I'm so excited to have a fully fledged particle animation system officially implemented in Minetest! I can already see countless applications for this API even within my own mods and games. Given the degree of control over particle movement and texture rendering, the possibilities are almost endless.

**Snowfall Mod**
I engineered a full-scale weather simulator which makes extensive use of particle spawners for precipitation like rainfall and snowfall. For more complex phenomena like tornadoes and windswept leaves, however, I must resort to hacky workarounds using the existing API. 

**Fireworks II Mod**
Fireworks serve as a centerpiece for New Years Eve celebrations on JT2. The aerial explosions themselves are implemented with a combination of particles and particle spawners. But even with sophisticated algorithms, I'm running up against the limitations of the existing API.

**Festival Mod**
Confetti cannons launch a colourful array of confetti into the air based on the direction the cannon is aimed and the current wind speed. While the effect itself is convincing, it still doesn't account for air resistance which is very difficult to reproduce using the existing API.

**Emoji FX Mod**
By using the /e chat command, players can express themselves with a burst of emoji particles around their character. Ideally these particles would project outward in a circle or upward in a spiral, while gradually fading away, but this is not supported by the existing API.	

**Festival Mod**
Balloons are implemented as particles rather than entities since they must be spawned in large numbers for the NYE balloon drop. Despite the performance advantage, particles can't bounce off walls or weave their way to the ground, which is a shortcoming of the existing API. 

**Virtual Nightclub Game**
Through the use of enchanted drinks, players can spawn an array of glowing particles around the dancefloor. These consist of predefined (albeit quite limited) patterns unique to each specific elixir. Ideally the particle animation would be fully synchronized to the rhythm of the music. 

The fog machine emits a stream of vapor-like particles onto the dancefloor with a positive velocity and a negative acceleration. This is an attempt to emulate air resistance. Of course, a native deceleration vector would give a more favourable effect so the particles don't reverse course.

**Thievery Game**
I'm developing a fantasy steampunk game for Minetest called Thievery, which is heavily inspired by _Thief: The Dark Project_. It includes steam-driven machinery as well as a variety of magical items (potions, talismans, arrows, wands, etc.). Feature-rich particle emitters are therefore central to the game design; e.g. sparks emanating from a fire-arrow in flight or glowing orbs circling around a magic scroll.

Suffice it to say, you've provided all the necessary properties that I need to complete the projects I described above -- including interpolation, attraction, repulsion, deceleration, elasticity, etc. I'm beyond impressed, and I look forward to finally giving this a test run!

**Comment by rubenwardy** [comment]
@sorcerykid I'd love some gifs/videos of this API in use to show it off in the July blog post. Maybe you'd be interested in making some tech demos?

**Comment by velartrill** [comment]
@sorcerykid this is awesome to hear, i'm really glad someone's going to be taking advantage of the new features! :) please feel free to let me know if you encounter any bugs or difficulties with the new API, or need help figuring out how to create a particular effect. fyi i'm going to be focusing on #5686 now that this is finally merged but once that's done i hope to eventually circle back around and add full keyframing support to the new particles API (assuming nobody else has done it by then)

**Comment by appgurueu** [comment]
Finally I can have spiralling particles.

**Comment by sorcerykid** [comment]
> I'd love some gifs/videos of this API in use to show it off in the July blog post. Maybe you'd be interested in making some tech demos?

Good idea, I can certainly see if I can put something together. What is the deadline for the newsletter?

**Comment by rubenwardy** [comment]
> > I'd love some gifs/videos of this API in use to show it off in the July blog post. Maybe you'd be interested in making some tech demos?
> 
> Good idea, I can certainly see if I can put something together. What is the deadline for the newsletter?

It's usually the first week of the next month, so August in this case
