### ISSUE TITLE
Creative mode | water no longer in bucket after use

### ISSUE THREAD

**Issue by aha999** [minetest/minetest#11517]
## Problem

When players, like myself are in a creative mode, i want to use a bucket of water/lava for example on a world surface, to create a pool, and since i'm in creative mode, the bucket should probably stay full after use, so i can quickly do what i must, but it empties every time, like in survival mode. So even in creative, the bucket behaviour stays the same, or limited.

## Solutions

When the players are in a creative mode, it would be preffered, that when a bucket with liquid is used, it doesn't empty itself, but instead stays full after use by default.

**Comment by aha999** [comment]
I realized there is "Water Source element" so essentially water bucket is not needed for this.

**Comment by 0-afflatus** [comment]
Yes, you could use a water_source node in creative.
For future reference this is not the right place for bugs against MTG mods; this is a (non-) issue with the Creative mod, not the game engine.
