### ISSUE TITLE
Injected native code plug-in support

### ISSUE THREAD

**Issue by Pevernow** [minetest/minetest#11514]
## Problem

At present, Lua mod has the advantages of cross platform and relatively high performance.

However, it is also obvious that the minetest engine is written in C + +, but mod uses the Lua environment.

Mod cannot access and modify the content in the engine (rendering part or network transmission part).

Executing some code that requires higher performance in Lua will greatly reduce performance.

## Solutions

Referring to the relationship between minecraft and forge, they are executed in the same language and support modification engines (such as optifine and sodium), which can greatly improve the customizability of users.

In my opinion, it seems that the native plug-ins can modify the engine functions by using C + + injection.

If we can develop an external injection engine similar to forge and provide methods similar to Lua API and modification engine, this may be changed.

**Comment by sfan5** [comment]
This has been discussed, please see #4064
