### ISSUE TITLE
About project IDE Configuration for newbies

### ISSUE THREAD

**Issue by yili001** [minetest/minetest#11522]
## Problem
Hey, I used to be Web developer, so I barely how a cmake-managed C++ project works,  Can you guys provide a tutorial about how to setup a develop/debug/test environment and tell us about how to debug the project code? so the newbie like me can set some breakpoints to understand how it works?

## Solutions
I think a development/debug/test tutorial based on **Visual Studio Code** would be great.

## Alternatives

Or post a video of it, maybe?

## Additional context

Since I never touched CMake before, When I set the breakpoint and try to start the debug session, the IDE gives me tons of error, I would really appreciate it if you guys can tell us how to set the **IDE configuration** right.

**Comment by rubenwardy** [comment]
Yeah, it would be good to have a guide on this - even if it was a link to a webpage.

I consider myself fairly adept at C++, but I wasn't able to set up VSCode to work nicely as a C++ IDE with all the debugging and intellisense features expected last time I tried. So I gave up and use CLion, which worked out of the box

It would be good to find/write a guide for this

**Comment by yili001** [comment]
Thanks for the suggestion, I will give it a try

**Comment by xlxs-1** [comment]
Are there any free IDEs that work out of the box (or with small configurations)? I tried eclipse (after using cmake's eclipse files generator) but there were some unresolved inclusions errors. Tried different configurations but errors persisted.

**Comment by sfan5** [comment]
Depends on what "IDE" means to you.
With the [`CMAKE_EXPORT_COMPILE_COMMANDS`](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) enabled you can easily import(\*) those into VS code and let the C++ plugin give you suggestions and highlight errors in realtime. Supposedly vscode can also use these to compile the project by itself but have never tested.

(\*) You can also do this manually, for example this is my `c_cpp_properties.json`: (I don't suggest doing this)
```js
{
	"version": 4,
	"configurations": [{
			"name": "Default",
			"includePath": [
				"${workspaceFolder}/src",
				"${workspaceFolder}/src/script",
				"/home/username/irrlicht/include",
				"/usr/include/luajit-2.0",
				"/usr/include/freetype2"
			],
			"defines": ["NDEBUG", "USE_CMAKE_CONFIG_H"],
			"forcedInclude": ["${workspaceFolder}/src/config.h"]
	}]
}
```

**Comment by numberZero** [comment]
> Are there any free Linux IDEs that work out of the box (or with small configurations)?

KDevelop does IIRC, it understands CMake natively.
