### ISSUE TITLE
You can move your hotbar selection into a section of the inventory that doesn't exist

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#11525]
##### Minetest version

```
5.5.0 - 2866918f3
```

##### OS / Hardware

Operating system: windows 10
CPU: ryzen 5600x

##### Summary

You can move your hotbar selection into a section of the inventory that doesn't exist if the set_size is less than hud_set_hotbar_itemcount which creates a hard crash when you press the drop button with no error catch

##### Steps to reproduce

player:get_inventory():set_size("main", 1)
player:hud_set_hotbar_itemcount(10)

press drop button

**Comment by NeroBurner** [comment]
could you help me out to reproduce your problem? Where do I have to add/type in the commands you have in "Steps to reproduce"? Do I need to create  a mod?
