### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by NSTAdventure** [minetest/minetest#11520]
Using minetest 5.4.0 android

I try to download and install mods then it's successfully installed with some dependencies

Another issues is some of dependencies are missing (can't found on internet) what should i do?
Or it's safe to ignore?

Here are my SS for reference issues:
![Screenshot_2021-08-08-08-34-16-59](https://user-images.githubusercontent.com/50813528/128617941-a4ad9112-6ae1-4c8d-9b46-300919093221.jpg)

**Comment by rubenwardy** [comment]
That mod is for Hades, not for Minetest game. You need to install the Hades game and then select it as the base game

**Comment by NSTAdventure** [comment]
But how do i find old version?
Visit minetest.net? Or contentDB?

**Comment by rubenwardy** [comment]
You don't need the old version, you need a different version

**Comment by NSTAdventure** [comment]
> You don't need the old version, you need a different version - it'll be a different package in the list of mods. Search for paleotest, you want the first one not the second one if you're using Minetest Game:
> 
> ![Screenshot_20210808-113104](https://user-images.githubusercontent.com/2122943/128629015-8d0dcdb4-3251-40eb-ba16-ecae41639ed4.png)

Alright buddy thanks for your help 🙏😊
