### ISSUE TITLE
Similar to sneak glitch, with different block configuration

### ISSUE THREAD

**Issue by xlxs-1** [minetest/minetest#11532]
##### Minetest version

```
eefa39e47b4ef1f6a51854461efee99777ae20fd
```

##### Summary
Sneak glitch happens on default settings when the blocks are set in a certain way as shown in the image. (There are 2 dirt blocks on top of each other, then 1, then 2.) If the player touches all of them, then sneak and jump, he will jump 2 blocks.
![bug](https://user-images.githubusercontent.com/25713123/129108960-fa5109d7-dd44-4f4d-8c9a-45aeafdd0de6.png)

**Comment by appgurueu** [comment]
Perhaps the same as #11171?

**Comment by Zughy** [comment]
Merging with #12702
