### ISSUE TITLE
Size of `Join Game` tab in main menu is inconsistent

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#11540]
##### Minetest version

```
Minetest 5.5.0-dev-b3b075e (Linux)
Using Irrlicht 1.9.0mt3
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."

```

##### Summary
The `Join Game` main menu tab is smaller than the other tabs.
Its a regression introduced by 5.5-dev (tested with 5.4.1)
I suspect #11078 

##### Steps to reproduce
Look at the bottom (or the top) of the menu formspec.
Switch between `Join Game` and other tabs.
You should see that the `Join Game` tab is sightly smaller.

**Comment by sfan5** [comment]
This is a byproduct of switching to real coordinates for the tab and I don't consider it a problem.

**Comment by AFCMS** [comment]
Aren't all tabs using real coordinates?

**Comment by sfan5** [comment]
No, only the join game one and only since this PR.
