### ISSUE TITLE
Camera spins out of control

### ISSUE THREAD

**Issue by sirnewton01** [minetest/minetest#11541]
##### Minetest version
```
Minetest 5.5.0-dev-b3b075e (OSX)
Using Irrlicht 1.9.0mt3
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
```

##### OS / Hardware
Operating system: macOS Big Sur
CPU: x86_64

GPU model:
OpenGL version:

##### Summary
When launching the game the camera spins looking at either the sky or the floor in a circle at high speed.

##### Steps to reproduce
1) Launch the game with the version above on macOS built from sources
2) Create or join a world
3) Click Play Game
4) Notice that the camera is facing the ground and spinning uncontrollably

**Comment by SmallJoker** [comment]
Similar issue, but on LInux: #8539

**Comment by sirnewton01** [comment]
I should point out that this is some kind of regression since minetest installed through homebrew 5.4.0 doesn't exhibit this problem at all. So, either something has changed in the dev version of minetest/one of its dependencies, or the way that I'm compiling this on macOS is not the same as the way that it is compiled via homebrew.

**Comment by appgurueu** [comment]
This can also be reproduced on non-mac systems, albeit in a different fashion: if the cursor is outside the MT window and MT believes it has focus, it treats this as if the cursor had moved there every step, because it believes that it has reset the cursor to the center of the MT window (which it hasn't).

**Comment by appgurueu** [comment]
This might be a user error and thus invalid. See if the steps described [here](https://forum.minetest.net/viewtopic.php?p=406510#p406510) help.

**Comment by sfan5** [comment]
Although giving Minetest that permission might work there should really be a better solution (I bet other games do not require this permission).

**Comment by bgold-cosmos** [comment]
Maybe it's something to do with confusion between the old and new versions, but I have tried granting Minetest control permissions and it has *not* affected the spinning issue at all.

**Comment by bgold-cosmos** [comment]
OK, it works!  To clarify the instructions above, I needed to delete the old executable, then remove and re-add permissions for both "Accessibility" and "Input Monitoring".  

I have run into games that *do* require "Input Monitoring", so it's not completely unusual, but there's some API they use to pop up a notification requesting you add it and restart the game.  I'm not sure if both permissions are actually required, apparently Apple moved some things to "Input Monitoring" in Catalina (see thread: https://developer.apple.com/forums/thread/122492).  It's also very confusing that permissions appear to be specific to the Minetest version and don't carry over -- I don't know if there's an update process that would fix this .  I haven't done GUI dev for MacOS in a while, so I'm not really up to speed on all this.

**Comment by verymilan** [comment]
Thanks, for me it started after the recent release. I have dragged my executable installed from Homebrew into Input Control. After that I was asked for one more permission and now everything looks healthy 🎉

**Comment by IrrlichtMt4** [comment]
This also happens on windows but only happens rarely.
