### ISSUE TITLE
Rounding error means (for example) wrong node is read

### ISSUE THREAD

**Issue by CiaranG** [minetest/minetest#1154]
Example lua code:

   node1 = minetest.get_node({x=34,y=-56,z=-108.49999951571})
   node2 = minetest.get_node({x=34,y=-56,z=-108.49})

These ought to read the same node, but they don't.

**Comment by rubenwardy** [comment]
I suggest flooring positions given to get/set_node.

**Comment by paramat** [comment]
^ Seems to have potential.

>  A real solution would be using doubles in Minetest
I think that using doubles would be a solution,

> If you want to fix this issue, you could maybe modify the relevant C++ parts to use double.

:-1: Not justified for a minor issue, we try to use floats instead of doubles for performance and memory reasons.

**Comment by paramat** [comment]
#6818 merged.
