### ISSUE TITLE
mainmenu dlg_config_world.lua can not show enabled unified_inventory mod

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#11552]
##### Minetest version

```
Minetest 5.5.0-3b842a7e0 (Linux)
Using Irrlicht 1.9.0mt3
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### Summary

Set the `load_mod_unified_inventory = true` in the `world.mt`.
But it is not enabled in the dlg_config_world.

##### Steps to reproduce

1. Put the [unified_inventory](https://github.com/minetest-mods/unified_inventory) mod into mods directory
2. Put the [techage_modepack](https://github.com/joe7575/techage_modepack) modpack into mods directory too.
3. Set the `load_mod_unified_inventory = true` in the `world.mt`.

   ```ini
   load_mod_unified_inventory = true
   ```

run the minetest , switch to local game tab, click the mod config of the world.
You will see the `unified_inventory` mod is not enabled.

I found the reason is the [techage_modepack](https://github.com/joe7575/techage_modepack) has the `unified_inventory` mod too and not enabled(nil).

**Comment by rubenwardy** [comment]
Fixed by #11784
