### ISSUE TITLE
ObjectRef:hud_remove(nil) crashes server

### ISSUE THREAD

**Issue by Konfuz** [minetest/minetest#11551]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
```
##### Summary
Calling hud_remove with a nil-value crashes the engine. While it *should not* be called with a nil value in the first place, perhaps the function can be a bit more defensive to reduce the occurrence of server-crashes. 

##### Steps to reproduce
call hud_remove(nil) on an ObjectRef

**Comment by randomMesh** [comment]
I had a similar issue and i was told that wrongly used API is not a bug. See #10732

**Comment by nerzhul** [comment]
yep, it's a mod code error, sorry, duplicates #10732
