### ISSUE TITLE
Consider a separate repo for requesting and discussing new features

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11568]
## Problem
Of 994 issues (995 with this meta one), half of them are feature requests => https://github.com/minetest/minetest/issues?q=is%3Aissue+is%3Aopen+label%3A%22Feature+request%22 . Most of them don't even fit in the roadmap, meaning they'll remain here for years.

## Solutions
Create a separate repo like Godot does https://github.com/godotengine/godot-proposals/issues so to keep only bugs here and make it easier to track/solve them. I remember when a few months ago rubenwardy went all through the issues by himself to find "deprecated" ones closing more than 50 issues, and I guess it wasn't that funny

## Alternatives
Well, don't, and watch them piling up using labels to filter them

## Additional Context
Discussions might go in the new repo as well

**Comment by appgurueu** [comment]
> ## Alternatives
> 
> Well, don't, and watch them piling up using labels to filter them

And what's the problem with that?

**Comment by Zughy** [comment]
Well, the mess in seeing 1k+ issues knowing that most of them are not really issues (yet conveying the idea that Minetest has 1k+ problems). It might overwhelm people

**Comment by v-rob** [comment]
I think I'd prefer a separate area for feature request myself, and I think at least one other core dev has expressed as such as well (maybe @rubenwardy?  I'm not sure).

**Comment by erlehmann** [comment]
> Well, the mess in seeing 1k+ issues knowing that most of them are not really issues (yet conveying the idea that Minetest has 1k+ problems). It might overwhelm people

I think the recent problems with irrlichtmt (removal of stuff that worked previously, in a separate repo, out of view of many who interact with Minetest) shows that less visibility of issues is a big problem. As long as you can filter, it is good to know where all the stuff can be found.

I see no issue with people concluding “Minetest has 1k+ problems.” – non-trivial software projects that do not have issues are either finished (i.e. feature-complete and bug-free) or have developers that think that “auto-closing” issues makes them go away somehow, which leads to people reporting either the same bugs over and over again or just fewer and fewer bugs. Minetest is neither finished nor seem the developers overly concerned with faking looking good through artificially low issue counts.

**Comment by Zughy** [comment]
Any other core dev take on this?

**Comment by rollerozxa** [comment]
This would be a good way to separate actual bugs and issues with (sometimes very out there) feature requests, but the consensus seems to be "just filter by labels" unfortunately.

**Comment by GreenXenith** [comment]
GitHub has a [discussions feature](https://docs.github.com/en/discussions/quickstart) that should be used for this, not a separate repo.

**Comment by Zughy** [comment]
@GreenXenith GitHub discussions are poorly implemented, we tried them with LibreSprite and it was a solid no

**Comment by Zughy** [comment]
UP: just wanted to say that if there is some agreement between core devs, I'm happy to volunteer to move the issues one by one (last time I checked, there was no way to do that in bulk)

**Comment by Zughy** [comment]
Closing due to lack of interest

**Comment by Zughy** [comment]
I'm core team now and I've got two core devs agreeing :^] reopening as I'd like to discuss it in the next meeting

**Comment by SmallJoker** [comment]
> rubenwardy went all through the issues by himself to find "deprecated" ones closing more than 50 issues, and I guess it wasn't that funny

How exactly would a separate tracker fix this problem? I'm asking this because it's in the "Solution" section, thus probably meant as a "pro" argument.

**Comment by Zughy** [comment]
> As long features and bugs can be reliably filtered by tags (how it's currently done), I currently don't see any benefit in splitting or moving the tracker

See this and next page https://view.matrix.org/room/!jGawCGhycfrYboDVtV:tchncs.de/?anchor=$WDrCm3GZnIKRwqeiWEkzUM54_E5EVvlUeY_IfiLm5HY&offset=-42

> Fixes #prnumber to automatically close [feature] issues

This is doable between repos, see https://github.com/LibreSprite/LibreSprite/pull/264 as an example

> Embedded code references (to a few specific lines) that would be potentially relevant for the feature implementation

Gg Github. Another reason to migrate to something that it's actually free software where people can suggest edits to actually implement useful things

**Comment by sfan5** [comment]
Chiming in to say that i'm in the "don't" camp.

**Comment by Zughy** [comment]
Closing as this would be either controversial or staling for a lot of time
