### ISSUE TITLE
[solved] [build/CMake] Compiling server-only isn't possible / IrrlichtMt detection broken

### ISSUE THREAD

**Issue by debagos** [minetest/minetest#11562]
https://github.com/minetest/minetest/commit/a72d13064fcbddaf332c7d53e6f34b74d8781586

I am unable to compile Minetest from scratch using `-DBUILD_SERVER=TRUE` 

CMake stats: `Using user-provided IrrlichtMt at subdirectory 'lib/irrlichtmt'`
But then a few lines later: `Cannot specify include directories for imported target "IrrlichtMt::IrrlichtMt"`

This even happens when I specify the IrrMt include dir with `-DIRRLICHT_INCLUDE_DIR=IrrMTIncDirBla`

**Comment by sfan5** [comment]
Sounds like you have cached stuff left over from when IrrlichtMt was (unnecessarily) also built with the server.
Delete CMakeCache.txt and try again.

**Comment by debagos** [comment]
I'll try that, but as I said, I compile from scratch. It's even a whole new user (I want to create a new server).

**Comment by sfan5** [comment]
Some googling suggests there may be issues with what we're trying to do on CMake versions older than 3.11, what's yours?

**Comment by debagos** [comment]
3.10.2
Well well
But I wonder why this happens now, because last time I built from scratch was almost exactly one month ago, and everything went smooth.
Okay, I will get a recent CMake and report back :)

**Comment by sfan5** [comment]
cc @JosiahWI 
the issue I found by googling is https://github.com/ginkgo-project/ginkgo/issues/234#issuecomment-465611403

**Comment by debagos** [comment]
Now, with the latest stable CMake (3.21.1), **it works**. Good job @sfan5, Thank you. :+1: 
Could be a good idea to change the CMake dependency version to `3.11+` in the [README.md](https://github.com/minetest/minetest/blob/master/README.md).
