### ISSUE TITLE
Content Browser fails downloads/updates/installs/dependency checks when ContentDB username contains special characters

### ISSUE THREAD

**Issue by Df458** [minetest/minetest#11576]
##### Minetest versions
5.3, 5.4.1, 5.5.0-dev (0c1e9603db32b4281974fdd8b8e3b505148be47e)

Running on Arch Linux with curl 7.78.0-1 installed

##### Summary
When attempting to do anything to a package from ContentDB that would involve web requests (ie. downloading, updating, checking package deps), and the package uploader's username contains a non-url-safe character (ie. my current username on CDB is `Hugues Ross`), the relevant curl requests fail with an error like:
> 2021-08-27 17:44:00: ERROR[Main]: https://content.minetest.net/api/packages/hugues ross/rpg16/dependencies/?only_hard=1&protocol_version=40&engine_version=5.5.0-dev not found (URL using bad/illegal format or missing URL) (response code 0)
2021-08-27 17:44:00: ERROR[AsyncWorker-0]: https://content.minetest.net/packages/Hugues Ross/rpg16/releases/9135/download/?reason=new not found (URL using bad/illegal format or missing URL) (response code 0)
2021-08-27 17:44:00: ERROR[AsyncWorker-0]: downloading "https://content.minetest.net/packages/Hugues Ross/rpg16/releases/9135/download/?reason=new" failed

I _suspect_ this relates to a curl update (more specifically, https://github.com/curl/curl/pull/7073), simply because this issue didn't exist in the past but seems to affect past versions. I'm looking into getting a name change as a backwards-compatible fix, but ideally we should properly fix our urls before passing them to curl.

##### Steps to reproduce
1. Open the content browser
2. Attempt to download or update any of [my packages](https://content.minetest.net/users/Hugues%20Ross/)

**Comment by appgurueu** [comment]
Should be pretty easy to fix; a simple `url:gsub(" ", "+")` at a few places should do the job. On it.
