### ISSUE TITLE
Tab with Images

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#11573]
I would like tabs in formspecs with images. Only caption, only image or a combination of both.

**Comment by sirrobzeroone** [comment]
@runsy I faked image tabs recently, its very much in workaround territory. I used sfinv as a base the trick was to disable the actual tabs and use image buttons that sent the same data structure as tabs so on press the formspec return thought it was tab being pressed - I was trying to reuse as much of sfinv as I could....probably butchered it horribly sorry Rubenwardy 

In sfinv - api.lua adjust function "sfinv.get_nav_fs", 
naturally remove all pre built tab code then:
First up you need to style the image buttons so the font size is zero at the beginning so the idx(tab number) is hidden.:
```
sfinv_image_tabs = "style[sfinv_nav_tabs;border=false;alpha=true;font_size=0]" 
```
The button label ended up as the idx (tab number) and the image button name as sfinv_nav_tabs. so example tab button this sits inside a loop ("for idx,name in pairs(nav) do") which runs through the registered tabs - sorry I cant just copy my whole code in as I have a bunch of other code in there like highlighting the clicked image/tab but if your intrested just ask i'll post more complete code:

```
sfinv_image_tabs =sfinv_image_tabs..
"image_button[X,Y;H;W;.
"some_image_name.png;"..
"sfinv_nav_tabs;"..
idx..";"..
"true;false;"..
"some_image_name_pressed.png]"..
"tooltip[X,Y;H,W;tab_name;#color;#color]"
```

+1 for this functionality though, just providing the workaround in case Runsy or someone else stumbles on this issue

**Comment by v-rob** [comment]
The other PR was closed because it didn't use `style[]` and was getting old, and furthermore, like I said before, styled `image_button[]`s can do essentially everything tabs can; they can even emulate the same look.  I don't think that it's worth putting the time and effort into adding such a feature into formspecs when there's an easy enough workaround.

**Comment by runsy** [comment]
Anyway this is a requested feature, not an issue.

I would prefer to remove Formspec completely and use the planned replacement: LUA objects.

**Comment by Zughy** [comment]
Closing due to @v-rob answer, who's the one taking care of formspecs
