### ISSUE TITLE
Documentation for shared utilities: Split off in separate file

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11577]
## Problem

The client API, server API and mainmenu API all share common utilities. Their documentation belongs in a different file.

**Comment by sfan5** [comment]
This would unfortunately break the ability to ctrl+f in `lua_api.txt` and be guaranteed to find something. I don't have a better suggestion though.

**Comment by appgurueu** [comment]
> This would unfortunately break the ability to ctrl+f in `lua_api.txt` and be guaranteed to find something. I don't have a better suggestion though.

If we want the Lua API to be complete, we might have some kind of script/CI action which copies the file contents. I'm thinking:

`lua_api.txt`:
```markdown
# Some stuff
...
# Utilities
<!--startutils-->
<inserted content>
<!--endutils-->
```

`utils.md`:
```markdown
* `table.indexof`: ...
...
```
