### ISSUE TITLE
Proposal: A new way to allow game or world settings to rewrite global settings items

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#11580]
The current configuration levels are: `default settings`, `game settings` and `global settings`.
The priority of configuration is: `default settings` < `game settings` < `global settings`.

Therefore, we must first add the `world settings`:
`default settings` < `game settings` < `world settings` < `global settings`.

Sometimes we also need certain games or world configurations to be unaffected by global settings under conventional circumstances. Therefore, it is agreed that if the configuration item name is preceded by an asterisk, it means that the value of the item will not be overwritten by the conventional item configured at a higher level, unless the item also has a prefix asterisk on the higher level configuration. E.g:

```ini
# game.conf
*static_spawnpoint=(0,0,0)
*enable_damage=true
*mg_flags=dungeons,caves,decorations,biomes,light
```

```ini
# minetest.conf
static_spawnpoint = (0,1,0)
```

Then the final `static_spawnpoint` value should be: `(0,0,0)`. If you need to force the global configuration to take effect, you must manually add a prefix asterisk to the configuration item name in the global configuration(note:the game or the world may not support this configuration item):

```ini
# minetest.conf
*static_spawnpoint = (0,1,0)
```

Added lua api: `settings:get_disabled_names()` return all special configuration item names if any.

Related #8927, #11010.

I would pr if need.

**Comment by appgurueu** [comment]
I am against the asterisk addition. Another configuration level is fine by me; modlib's abstracted configuration utilities have had these levels for a while (global config, world config, mod config, defaults).

**Comment by rubenwardy** [comment]
This is overcomplicated - much better to add world setting which override global settings, and Lua APIs write to it rather than global settings

**Comment by snowyu** [comment]
> This is overcomplicated.

No, It's simple and clear. It only takes a few lines of code if lua_api is not counted.
For ordinary users, there is no need to know the existence of asterisk.

> much better to add world setting which override global settings, and Lua APIs write to it rather than global settings

@rubenwardy  So if there are global settings that need to rewrite the world configuration, how to deal with it?

> I am against the asterisk addition. Another configuration level is fine by me; modlib's abstracted configuration utilities have had these levels for a while (global config, world config, mod config, defaults).

@appgurueu I only agree that the mod settings should also support hierarchical configuration. Your modlib just a workaround for mods. But the Settings class needs to be refactored if it wants to support different formats.

**Comment by rubenwardy** [comment]
> @rubenwardy So if there are global settings that need to rewrite the world configuration, how to deal with it?
> I think most configuration items should follow the priority: default settings < game settings < world settings < global settings Only a few configuration items have exceptions.

This would not be supported - any fixed settings like `water_level` would need to be copied into the world settings

**Comment by snowyu** [comment]
> My priority would be: default settings < game settings < global settings < world settings

If so then most of the references to g_settings in the code need to be changed to g_world_settings. I think this is a big change, afraid of omission.

> This would not be supported - any fixed settings like water_level would need to be copied into the world settings

I think the user can share their worlds too, just like sharing games. And the world also has worldmods. The world is based on game development. Therefore, the world settings may not be under the control of the player. The only configuration the player can control is the global settings.

> By doing this, you fix the issue of mods setting global settings just to change something for their world.

1. The mods do not know the world unless the world has been created.
2. This still does not solve the problem: 
    * after adding a mod to the world, the world get problem, and after deleting the mod, the problem still exists because the world settings has been changed and can not be restored. 
    * It just limited the scope of the problem. Previously, all game worlds had problem(the global settings was changed), but now only this world has problem.

@rubenwardy 

Perhaps these terms should be defined and agreed for further better discussion:

* Engine Settings: engine-specific configuration items
* Mod Settings: mod-specific configuration items, can overwrite engine settings, dependent mod configuration or specfied games settings(the game mod), do not know the world settings.
* Modpack Settings: modpack-specific configuration items, like mod settings.
* Game Settings: game-specific configuration items, can overwrite engine settings, dependent mod settings, modpack settings, or dependent games settings.
* World Settings: world-specific configuration items, can overwrite engine settings, dependent mod settings, modpack settings, or dependent games settings.
* Global Settings: configure everything. Controlled by the player.

**Comment by snowyu** [comment]
I've almost done the codes and unit-test here:
https://github.com/minetest/minetest/compare/master...snowyu:feat/settings/rewrite_global?expand=1

But I've found a question:

https://github.com/minetest/minetest/blob/d1624a552151bcb152b7abf63df6501b63458d78/src/content/subgames.cpp#L340

Is this code(copying all configuration from global settings) really need? Why?

**Comment by snowyu** [comment]
The next todo:

1. Change the static hierarchical configuration to dynamic hierarchical configuration.
2. Keep backward compatibility? I have no idea so far.

**Comment by rubenwardy** [comment]
> > My priority would be: default settings < game settings < global settings < world settings
> 
> If so then most of the references to g_settings in the code need to be changed to g_world_settings. I think this is a big change, afraid of omission.

This isn't true - `g_settings` isn't the user's minetest.conf, it's the current settings object which includes the game's minetest.conf as well. So you'd just need to modify the settings hierarchy

The one caveat is that the server and the client both use the same `g_settings` in singleplayer, but this is already the case and not too much of a problem
