### ISSUE TITLE
Add support for a sound to be played on tool use

### ISSUE THREAD

**Issue by nn0ble** [minetest/minetest#11586]
## Problem

The only way to easily play a sound on tool use is to use the on_use function, the problem with this is that it overrides the basic uses of the tool and only does what you define inside the function.

## Solutions

I would suggest either another item definition function for playing a sound on_use as not to override the basic actions, 
Or to add an event under the [sound](https://pastebin.com/gUY1fLDV) function such as "hits = \<SimpleSoundSpec\>"

## Example

An example of the current on_use function can be seen here, this works for playing a sound when the lmb is clicked but again, it overrides the basic uses of the tool such as attacking, digging, or picking up items.

```lua
minetest.register_tool("example:tool", {
     description =  "tool",
     inventory_image = "tool",
     wield_image = "tool",
     stack_max = 1,
     tool_capabilities = {
        full_punch_interval = 1.0,
        max_drop_level = 0,
        groupcaps = {
            -- For example:
            choppy = {times = {[1] = 2.50, [2] = 1.40, [3] = 1.00},
                     uses = 128, maxlevel = 2},
        },
        damage_groups = {fleshy=5},
        punch_attack_uses = 256,
    },
   
    on_use = function(itemstack, user, pointed_thing)
      minetest.sound_play(
        {name = "default_place_node"},
        {
          object = user,
          gain = 1.0,  -- default
          max_hear_distance = 32,  -- default, uses an euclidean metric
          loop = false,
        },
        true
      )
      return
  })
```

**Comment by Andrey2470T** [comment]
Accordingly to [lua_api.txt](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L7535) `on_use` callback does nothing (default returns nil), so you don't override any code inside that function that is going on default in a case if it is not defined when you register an item.
