### ISSUE TITLE
Impossible to set child object`s position after attaching.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#11582]
##### Minetest version
```
Minetest-5.5.0-dev-4a3728d828fa8896b49e80fdc68f5d7647bf45b7
```

##### Summary
After attaching object to other object (`set_attach()`), you can not set its relative position. The object is always attached to the object`s centre point not depending on whether you call `set_pos()` or directly set in `set_attach` itself or not.

##### Steps to reproduce
1. Attach any object to other object. Step 2 can be skipped if you set position directly as an argument in `set_attach`.
2. Set child`s position.

**Comment by sfan5** [comment]
You can always set the relative position by calling `set_attach` again, can't you? I don't see the problem.

**Comment by SmallJoker** [comment]
Use `set_attach` to adjust the relative position. `set_pos` is only for absolute position changes for non-attached entities.

**Comment by Andrey2470T** [comment]
Problem is `set_attach` does *not* set new relative position for attached entity. As I already said, this method always sets child's position to the parent`s centre point (the same would be `set_attach(parent, bone, {x=0, y=0, z=0})`) regardless it may be different from the null vector.

**Comment by SmallJoker** [comment]
In this case you should create a bone for your parent object to attach a child object to the correct position.

**Comment by sfan5** [comment]
Are you saying `set_attach`'s offset does not work _at all_? Or does it not work to _update_ the offset? Something else?

**Comment by Andrey2470T** [comment]
Doesn't work at all.

**Comment by sfan5** [comment]
Nope, sure works:
![grafik](https://user-images.githubusercontent.com/1042418/131553916-61354ecf-d758-4918-8ebb-8be00fe09c47.png)

**Comment by Andrey2470T** [comment]
Can you show your code please? Also, do you use 5.5.0-dev version?

**Comment by sfan5** [comment]
I am running 5.5.0-dev, the code is the object attacher tool from devtest:
https://github.com/minetest/minetest/blob/040aed37abcc929137fb9729f2526d6a15d2d51a/games/devtest/mods/testtools/init.lua#L584-L610

**Comment by Andrey2470T** [comment]
It seems the problem has been fixed after I multiplied by 10 the relative position. As I understood, attached objects use other metrics than non-attached ones, volume '1x1x1' is not equal to volume of actual cube area in such case.
