### ISSUE TITLE
improve player xperience, support mobile, mientest 5.X servers are less played, mostly 0.4 ones

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/minetest#11593]
## Problem

**every mt-server has just 0.55 gamer in average**,  this ridiculizes in average that 1 gamer use 2 servers at same time??¡?¡? this is **happened since release of minetest 5 and raised of multicraft**

is clear that minetest developers not are really minetest gamers.. in fact are the worse gamers! (no skills in pvp, ctf, etc)

| server type   |  players (active/total) | servers (active/total) | versions |
| Minetest       | 428/1291                 |  303/365                  |  5.X  avg= 252 servers, 0.4 only 4 servers |
| Multicraft      | 321/880                    | 15/40                       |  2.X has 20 to 30 servers in avg |

* Multicraft gamers are 64% of all gamers in minetest server list
* Most active minetest are 0.4.x with 30 gamers each day in average (see list the tops ones)
* The minetest only most played servers are 0.4.X ones (sub.nasa-g0v ones in fact, i have one)
* Every multicraft server has avg 15 gamers, most registered protocol is from 0.4.16 compatible clients

A quick picture ilustrates all more easyle: (and sad maybe)
![image](https://user-images.githubusercontent.com/1571724/132130481-37a3245f-adb9-4c8c-a28d-5e4ff4129f2c.png)

## Solutions

1. improve and only focus in the minetest mobile (not just androit/iphone) client UI, in sync with the computer
2. do not raised the compilation requirements, you guys must **learn from minecraft, all the releases since 1.8.8 works and still suported in limited way** by wide range of plugins (in fact 1.8.8 is used for pvp and 1.14 for survival)

## Additional context

I have also noticed this, and **the fault lies with the developers**, mostly fans of programming without seeing two important factors:

1. **Today the vast majority of gamers use mobiles** and not consoles or computers
2. **Movement from mt 0.4 to mt 5 was merely technical, something that nobody cares about**

only 24 server are 0.4.x with 41 gamer = 1.7 gamer each 0.4.x server
but then 252 server are 5.x ... with left (428 - 274 - 41) = 113 gamer = 0.448 gamer each server ... lolol

I would say 5.0 FAILED !!!?

## Alternatives

not really a liked one but join the both multicraft and minetest project? noo! but is clear multicraft focus the effors in players not in technicalls things!

* 5.0 has 83 % of all servers ... but only 26% of gamer
* 0.4.x has just 6% of all servers, but near 10% of gamer
* 2.0.0 has a bit over 6% of all server, but 64% of all gamer.

**Comment by LoneWolfHT** [comment]
Go play Multicraft, Minetest is doing fine as it is IMO.

I don't think most of the 0.4.x players have a choice about what version they play, iOS only has outdated clones of Minetest on the app store, and IIRC the Multicraft serverlist favors 0.4.x/Multicraft servers

**Comment by rubenwardy** [comment]
Thanks for raising this issue - but we already have issues for this else where (such as #11404 #8241 #2761)

If you have any concrete suggestions on improving Android, please open issues for those.

Please note that we cannot support iOS's app store due to licensing restrictions. However, I plan on porting Minetest if/when I get a Steam Deck

**Comment by rubenwardy** [comment]
How many players that Multicraft has is largely irrelevant. Minecraft has 3,415,940 online players currently, which means that Minetest is only 0.018% of all voxel players!

The most important thing is to make our own experience better, rather than worrying about what other games are doing. Minetest 5.5 will have a replaced graphics and input engine, which will increase stability and allow for performance optimisations and improved graphics in the future

**Comment by SmallJoker** [comment]
You're just analyzing the server list without providing any precise suggestions on what exactly to improve. There's already plenty issues to make Minetest better, but this one does not help in any way.

**Comment by mckaygerhard** [comment]
I see that minetest developers are not very smart, the **answers are haters style like "we're fine thanks"** .. multicraft will always use them as usual, :+1: :smile: 

**interesting response.. only @rubenwardy  give one mostly familiar..**

**Comment by sfan5** [comment]
Calling other people dumb is not an acceptable interaction style on this issue tracker.
Rubenwardy has pointed out that your suggestions regarding Android already tracked in various other issues. The point about "compilation requirements" appears to be too vague (nothing prevents people from using older versions).
If you have constructive suggestions feel free to open another issue.
