### ISSUE TITLE
Allow custom interval in minetest.register_globalstep

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11590]
## Problem

Mods always wants a globalstep function to not run in every server step, so they have a workaround, but it is wasting our energy, ~~making the world's water level increases~~.

The current workaround is:
```lua
local total_dtime = 0
minetest.register_globalstep(function(dtime)
 total_dtime = total_dtime + dtime
 if total_dtime > 1 then -- If run per second
  total_dtime = 0
  -- Do stuffs
 end
end)
```

## Solutions

Add one more param into `minetest.register_globalstep`

`minetest.register_globalstep(func[,dtime])`
* dtime: Optional, the lease delta time between globalstep calls (default: 0.1)

This add a function ~~thats saves the world~~ while keeps the compatibility.

Maybe we can do the workaround c++ side thats ~~only save penguins a bit but it is better then nothing~~.

**Comment by wsor4035** [comment]
you also can make a minetest.after function that calls itself

**Comment by appgurueu** [comment]
> you also can make a minetest.after function that calls itself

That's less efficient actually.

**Comment by appgurueu** [comment]
> Maybe we can do the workaround c++ side thats ~only save penguins a bit but it is better then nothing~.

No it's not "better than nothing". You're greatly exaggerating this. Adding to a *local variable* and *comparing it's value against a number* are about the fastest things you can do in Lua. This is certainly not a performance bottleneck, not even with possibly hundreds of globalsteps. If a globalstep executes rarely, an `after`-based solution may be preferrable if a *priority queue* was used to implement `minetest.after` (`modlib` has such a feature, but doesn't use it for globalsteps yet as there is no need to).

The code you are presenting is not a workaround IMO, it's a clean solution. Library mods have long abstracted this away anyways. It is preferrable if the modder gets to do this themselves: That way, they may decide the specifics of the timing. Consider:

```lua
local timer = 0
minetest.register_globalstep(function(dtime)
  timer = timer + dtime
  if timer < 42 then
    return
  end
  timer = timer % 42
end)
```

Does this do the same as the code you have shown? No. You simply reset the timer to zero. 1.69 seconds might have passed and even if your globalstep was supposed to run 0.69 seconds ago, it runs exactly once; there is no catchup for the 0.69 seconds. What I have shown will execute the next step 0.31 seconds later, making up for the "lost" time. Depending on the use case, both are valid.

**Comment by erlehmann** [comment]
I assume this is a MineClone2 / MineClone5 issue? If so, at least those two games could greatly benefit by *doing less* in globalstep, or not doing stuff at all. Mineclonia has demonstrated this is totally doable.

**Comment by SmallJoker** [comment]
`minetest.after` is good enough for this job. If you need precision, rely on `minetest.register_globalstep` directly. The amount of code required to implement that is trivial.
