### ISSUE TITLE
segmentation fault when running minetest --random-input with joystick plugged in

### ISSUE THREAD

**Issue by NeroBurner** [minetest/minetest#11591]
##### Minetest version
```
minetest --version
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.0.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

still happens on current master ff9945dc6eb33d054059fc48605ffea7c4b515d3 `Fix falling mesh nodes being half size (#11389)`

##### OS / Hardware

Operating system: Arch Linux
CPU: AMD Ryzen 5 1600

##### Summary
Trying to reproduce #11589 with random input using `minetest --random-input` and getting a segmentation fault.

Segfault is gone when unplugging my Xbox360 controller

Segfault in following line https://github.com/minetest/minetest/blob/1d69a23ba48d99b051dcf2a6be225edd7c644c7b/src/client/joystick_controller.cpp#L198

With the following call-stack (compiled with current master mentioned above)

```
JoystickController::handleEvent(JoystickController * const this, const irr::SEvent::SJoystickEvent & ev) (/home/nero/repos/minetest/minetest/src/client/joystick_controller.cpp:198)
MyEventReceiver::OnEvent(MyEventReceiver * const this, const irr::SEvent & event) (/home/nero/repos/minetest/minetest/src/client/inputhandler.cpp:145)
irr::CIrrDeviceStub::postEventFromUser(irr::CIrrDeviceStub * const this, const irr::SEvent & event) (/home/nero/repos/minetest/minetest/lib/irrlichtmt/source/Irrlicht/CIrrDeviceStub.cpp:231)
irr::CIrrDeviceLinux::pollJoysticks(irr::CIrrDeviceLinux * const this) (/home/nero/repos/minetest/minetest/lib/irrlichtmt/source/Irrlicht/CIrrDeviceLinux.cpp:1679)
irr::CIrrDeviceLinux::run(irr::CIrrDeviceLinux * const this) (/home/nero/repos/minetest/minetest/lib/irrlichtmt/source/Irrlicht/CIrrDeviceLinux.cpp:1089)
RenderingEngine::run(RenderingEngine * const this) (/home/nero/repos/minetest/minetest/src/client/renderingengine.h:120)
ClientLauncher::run(ClientLauncher * const this, GameStartData & start_data, const Settings & cmd_args) (/home/nero/repos/minetest/minetest/src/client/clientlauncher.cpp:211)
main(int argc, char ** argv) (/home/nero/repos/minetest/minetest/src/main.cpp:232)
```

##### Steps to reproduce
- plug in joystick (xbox 360 controller in my case)
- start `minetest --random-input`
- get segfault

**Comment by sfan5** [comment]
A null check is probably missing here:
https://github.com/minetest/minetest/blob/ff9945dc6eb33d054059fc48605ffea7c4b515d3/src/client/inputhandler.cpp#L140-L145

**Comment by NeroBurner** [comment]
Opened PR fixing that https://github.com/minetest/minetest/pull/11592

**Comment by sfan5** [comment]
When you fix the other bug please put that in the same PR.
