### ISSUE TITLE
Support signals with Lua API

### ISSUE THREAD

**Issue by xyzz** [minetest/minetest#116]
Something like that would be really useful (for example, reloading auth.txt by just sending some signal to minetestserver)

```
minetest.register_on_signal(signal, function)
```

**Comment by taikedz** [comment]
Will this be reconsidered for a future milestone, at least from a sysadmin point of view, even if it is without Lua bindings?

Reloading auth.txt is a specific use case I would be after

**Comment by everamzah** [comment]
What's /auth_reload do?

**Comment by taikedz** [comment]
Logged-in admin-player can reload auth from within the game. But what about another process telling the game it needs to reload the auth file?

**Comment by nerzhul** [comment]
Lua should not have access to signal which is for core engine only, closing. For the auth reloading, when moving to database yourreloading problems will be solved
