### ISSUE TITLE
Node meta no longer updates?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#11610]
##### Minetest version
```
75bf9b75caba5fc876f20eabea3fabc142d1b51e
```

##### Summary
It seems like node metadata is no longer properly updated when it is changed.  This will break various nodes.

If this is true, this is a serious regression that must be fixed before release.

##### Steps to reproduce
1. In DevTest, place a Chest of Everything, open formspec and click on ">" once
2. Place a node next to chest and open its formspec again

Expected: After step 1, the page updates immediately, and step 2 does nothing to the formspec
Actual: After step 1, nothing happens, but after step 2, the page is updated.

You can also try by changing the page multiple times. You can also try to use the Node Meta Editor (a test item) to edit node metadata directly to see what happens. (note: The Chest of Everything stores its formspec in meta).

I did not test actual games yet, but I strongly suspect those will be horribly broken as well atm. I suspect all nodes with user-facing metadata (formspec, infotext) are broken by this big.

**Comment by SmallJoker** [comment]
Suspect #11597 @TurkeyMcMac

**Comment by sfan5** [comment]
Can't reproduce on based on 766e885a1 so it only be https://github.com/minetest/minetest/commit/75bf9b75caba5fc876f20eabea3fabc142d1b51e#diff-592338f1bfb0275512da218625ce67e993b91984c175f70fe376825ab4e0aad2
