### ISSUE TITLE
Discuss: allow true multithreaded Lua mapgen

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11619]
## Problem

As is, mapgen with Lua is single threaded (even with multiple emerge threads), since the on_generated is executed in `EmergeThread::finishGen`, which takes the envlock (`MutexAutoLock envlock(m_server->m_env_mutex);`) in the beginning.
That leads to slow mapgen even in cases where the server has plenty of free CPU resources. You can observer that - for example - with the various Mineclone*.

## Solutions

There are multiple options:
* The simplest: add a `register_on_generated_no_lock(...)` where the Lua code promises (which is lame) not to manipulate the map, or we can find a way to disallow manipulating the map in that case (maybe by hiding the map object so that all calls would fail). The `register_on_generated` callback would then be responsible for doing map manipulation. That way _no_lock could create a voxelmanip, do all its work there, but do not touch the map. The on_regerated calledback could then just write the vmanip to the map. The advantage is that this is strictly optional for a mod developer, the disadvantage is the promise to not touch the map in no_lock.
* Add a new callback `on_generated_voxelmanip, that is passed the voxelmanip, and the server code later moves the changes into the map.
* Probably more...

**Comment by erlehmann** [comment]
> That leads to slow mapgen even in cases where the server has plenty of free CPU resources. You can observer that - for example - with the various Mineclone*.

As a developer on Mineclonia, I think that the slowness in the map generator we inherited from MineClone2 does not necesarily seem like an engine feature to me, more like a misuse of the engine. Something cursed is going on in the village generator for example, as it stalls the map generator, while other mods with village generators do not do this.

You can probably ask @kay27 what is going on there?

**Comment by sfan5** [comment]
#3182 btw

> The simplest: add a `register_on_generated_no_lock(...)` where the Lua code promises (which is lame) not to manipulate the map

This won't work like you think it does. First off not accessing the map is pointless, the env lock covers more than just the map.
If you substitute "no map" for "no env" then you still can't run the same Lua state from multiple threads.
So you create a second Lua state at which point you have arrived at what I proposed here: https://github.com/minetest/minetest/issues/10800#issuecomment-758866967

> Add a new callback `on_generated_voxelmanip`, that is passed the voxelmanip, and the server code later moves the changes into the map.

(same reasons apply)

**Comment by erlehmann** [comment]
`register_on_generated` is known to be buggy btw (maybe due to having several emerge threads?): https://github.com/minetest/minetest/issues/8232

**Comment by lhofhansl** [comment]
Thanks @sfan5 I faintly remembered filing an issue some time back on this but could not find it. (I searched for emerge thread Lua, etc).

**Comment by lhofhansl** [comment]
And I do apologize that these days I have so little time for Minetest (and so each time I come back it's like I'm starting from scratch).

**Comment by sfan5** [comment]
No worries.
