### ISSUE TITLE
sound_play warnings

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#11617]
##### Minetest version

```
5.5-dev
```

##### OS / Hardware

Operating system:windows 7
CPU:i7-3610qm

GPU model:
OpenGL version:

##### Summary

Sometimes, i noticed the console is filled with lines like these: 
![image](https://user-images.githubusercontent.com/52937829/133113398-17209ab0-d8db-4c1d-a52f-e5e5fc296b85.png)
while this happens the game feels really slow; player movements tend to freeze
##### Steps to reproduce

//lua for i=1,500 do minetest.sound_play("default_break_glass") end
this will produces similar warnings

After some testing, on my laptop the limit of sound played is 256, more than this and the warnings appear. It seems to be a relatively high number, yet it happens in game with basic_machines and rather large factory and potentially others mods too. Also, even with sound muted the warnings occur.
I'm not sure, related lines of code: 
https://github.com/minetest/minetest/blob/b480a3e9fd7036208068c4fad410f0cae8fc9c4f/src/client/sound_openal.cpp#L433
https://github.com/minetest/minetest/blob/b480a3e9fd7036208068c4fad410f0cae8fc9c4f/src/client/sound_openal.cpp#L85
Is there anything that could be done to improve performance with sound_play? Thanks for reading

**Comment by sfan5** [comment]
Fixing #10603 would help with this, other than that we can't fix OpenAL running out of memory. Closing.
