### ISSUE TITLE
Unexplained "Could not create ITexture, texture needs to have a non-empty name"

### ISSUE THREAD

**Issue by IceDragon200** [minetest/minetest#11648]
##### Minetest version

```
5.5.0-dev-debug-844627ae1-dirty
```

It's really just the master branch of minetest with the PR 10486 (I'm purposely not linking it to this issue)

##### OS / Hardware
Operating system: Arch Linux x86_64
CPU: Intel i7-2710QE

GPU model: N/A
OpenGL version: N/A

##### Summary

Unexplained texture warning without further context:

```
2021-09-20 10:09:42: WARNING[Main]: Irrlicht: Could not create ITexture, texture needs to have a non-empty name.
```

Without any further information from the engine on why this warning happened it is impossible to diagnose properly without chasing every texture declaration on the mod side or digging through the ui code.

It's only a minor nuisance at the moment as worlds load with it.

##### Steps to reproduce

Load any world, it is usually the first client side warning

**Comment by randomMesh** [comment]
Should be fixed with commit 9f85862
