### ISSUE TITLE
CMake doesn't acknowledge custom zstd library path while configuring

### ISSUE THREAD

**Issue by onlytruethomas** [minetest/minetest#11647]
##### Minetest version

```
Minetest 5.5.0 (2628316)
```

##### OS / Hardware
Host operating system: macOS 10.13.6 High Sierra
Host CPU: Intel Core i5-2400S
Target operating system: Mac OS X 10.4 Tiger
Target CPU: PowerPC G3

##### Summary
While configuring the project using CMake, specifying a custom path (`ZSTD_LIBRARY`, `ZSTD_INCLUDE_PATH`) for the zstd libraries does not change the behaviour of CMake. In other words, it fails to search in the correct location and errors saying it cannot find zstd. This is using a cross compiler to build for Mac OS X 10.4 running on PowerPC.

##### Steps to reproduce
I had configured using the command `cmake .. -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_PREFIX_PATH=/opt/irrlichtmt/ppc -DCMAKE_TOOLCHAIN_FILE=/Users/thomas/Documents/minetest/ppctoolchain.cmake -DCMAKE_INSTALL_PREFIX=/Users/thomas/Documents/minetest-built -DZSTD_INCLUDE_DIR=/opt/zstd/ppc/include -DZSTD_LIBRARY=/opt/zstd/ppc/lib -DBUILD_UNITTESTS=FALSE -DENABLE_CURL=OFF -DENABLE_CURSES=OFF -DENABLE_FREETYPE=OFF -DENABLE_GETTEXT=OFF -DENABLE_LEVELDB=OFF -DENABLE_POSTGRESQL=OFF -DENABLE_REDIS=OFF -DENABLE_SPATIAL=OFF -DENABLE_SOUND=OFF -DENABLE_LUAJIT=OFF -DVERSION_EXTRA="powerpc"` from within a clean build directory.

```
-- Looking for ZSTD_initCStream
WARNING: Target "cmTC_808c1" requests linking to directory "/opt/zstd/ppc/lib".  Targets may link only to libraries.  CMake is dropping the item.
-- Looking for ZSTD_initCStream - not found
CMake Error at /opt/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Zstd (missing: ZSTD_LIBRARY ZSTD_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindZstd.cmake:24 (find_package_handle_standard_args)
  src/CMakeLists.txt:244 (find_package)


-- Configuring incomplete, errors occurred!
```

Noticing the "targets may link only to libraries" message, I tried setting `ZSTD_LIBRARY` to the exact path of the library (`/opt/zstd/ppc/lib/libzstd.dylib`), but that did not change anything either.

Interestingly, looking at `CMakeError.log` reveals CMake is not even attempting to link zstd into its test program, as `-lzstd` or similar is not specified...
```
Linking C executable cmTC_808c1
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_808c1.dir/link.txt --verbose=1
/opt/gcc/ppc/11/bin/powerpc-apple-darwin8-gcc --sysroot=/Developer/SDKs/MacOSX10.4u.sdk -fPIC -fpermissive -O3 -mmacosx-version-min=10.4 -isysroot /Developer/SDKs/MacOSX10.4u.sdk -static-libgcc -static-libstdc++  -Wl,-headerpad_max_install_names CMakeFiles/cmTC_808c1.dir/CheckSymbolExists.c.o -o cmTC_808c1 
ld: warning: object file compiled with -mlong-branch which is no longer needed. To remove this warning, recompile without -mlong-branch: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.4u.sdk/usr/lib/crt1.o
Undefined symbols:
  "_ZSTD_initCStream", referenced from:
      _ZSTD_initCStream$non_lazy_ptr in CheckSymbolExists.c.o
     (maybe you meant: _ZSTD_initCStream$non_lazy_ptr)
ld: symbol(s) not found
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_808c1.dir/build.make:99: cmTC_808c1] Error 1
gmake[1]: Leaving directory '/Users/thomas/Documents/minetest/game/minetest/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_808c1/fast] Error 2
```

Lastly, I figure I should mention that I ran `nm` on `libzstd.dylib` to ensure the missing symbol was present, and it is.

**Comment by sfan5** [comment]
`ZSTD_LIBRARY` does indeed need to be the path to the library, everything else won't work.

> Interestingly, looking at CMakeError.log reveals CMake is not even attempting to link zstd into its test program, as -lzstd or similar is not specified...

It should however:
https://github.com/minetest/minetest/blob/2628316842e9c3fc1c54c6d57505c7851fa83490/cmake/Modules/FindZstd.cmake#L11-L15

This check works everywhere else I know so this can't possible be. Which CMake version do you use?

**Comment by onlytruethomas** [comment]
> `ZSTD_LIBRARY` does indeed need to be the path to the library, everything else won't work.

I set `ZSTD_LIBRARY` to `/opt/zstd/ppc/lib/libzstd.dylib`, the path of the library, still no difference.

> This check works everywhere else I know so this can't possible be. Which CMake version do you use?

I'm using CMake 3.21.2 from the MacPorts repository.

**Comment by onlytruethomas** [comment]
I think I found the problem. When specifying the exact library path, looking in `CMakeError.log` reveals the following.
```
Linking C executable cmTC_a9c74
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a9c74.dir/link.txt --verbose=1
/opt/gcc/ppc/11/bin/powerpc-apple-darwin8-gcc --sysroot=/Developer/SDKs/MacOSX10.4u.sdk -fPIC -fpermissive -O3 -mmacosx-version-min=10.4 -isysroot /Developer/SDKs/MacOSX10.4u.sdk -static-libgcc -static-libstdc++  -Wl,-headerpad_max_install_names CMakeFiles/cmTC_a9c74.dir/CheckSymbolExists.c.o -o cmTC_a9c74  -Wl,-rpath,/opt/zstd/ppc/lib /opt/zstd/ppc/lib/libzstd.dylib 
ld: -rpath can only be used when targeting Mac OS X 10.5 or later
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_a9c74.dir/build.make:100: cmTC_a9c74] Error 1
gmake[1]: Leaving directory '/Users/thomas/Documents/minetest/game/minetest/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_a9c74/fast] Error 2
```

It says that `-rpath` is only supported for linking to Mac OS X 10.5 or later, and again, I am targetting 10.4 Tiger. This is not the case of an outdated linker either, this is GCC 11.2.0. Running `grep` on the source files doesn't seem to reveal a way to change the behaviour of the linker.

**Comment by sfan5** [comment]
Sounds like a CMake thing, is it even supposed to still support 10.4?

Closing since we can't fix this.

**Comment by kencu** [comment]
I fixed this in MacPorts a while ago

https://github.com/macports/macports-ports/commit/51496245e108d51ce8cdeb510fd1efef29430123#diff-6c980de79be44a8c7fd4783770b0e7c2d4256e5224ba2c0c10f0c7ec07bb8e43

and the fix was upstreamed into cmake. 

cmake uses rpath only on 10.5+ now.
