### ISSUE TITLE
Add a way read textures, with support for texture modifiers

### ISSUE THREAD

**Issue by OgelGames** [minetest/minetest#11697]
## Problem

With the additions in https://github.com/minetest/minetest/pull/11498 and https://github.com/minetest/minetest/pull/11485, there is one thing that is still missing: a way to read textures.

## Solutions

Add a function to read textures, including any texture modifiers, and return a table with the same data needed for `minetest.encode_png`.

For example:
```lua
-- Read the texture
local texture = minetest.get_texture_data("default_stone.png^default_mineral_coal.png")

--[[
texture = {
	width = 16,
	height = 16,
	data = {
		{r = 97, g = 94, b = 93, a = 255},
		-- etc...
	}
}
--]]

-- Add noise to the texture
local new_data = {}

for i, pixel in ipairs(texture.data) do
	local n = math.random(-10, 10)
	new_data[i] = {
		r = math.max(0, math.min(255, pixel.r + n)),
		g = math.max(0, math.min(255, pixel.g + n)),
		b = math.max(0, math.min(255, pixel.b + n)),
		a = pixel.a
	})
end
	
-- Save the new texture
minetest.safe_file_write(
	textures_path .. "new_texture.png",
	minetest.encode_png(texture.width, texture.height, new_data)
)
```

## Alternatives

Use a pure Lua solution to read textures (e.g. [png-lua](https://github.com/Didericis/png-lua)) and implement texture modifiers, which would be very slow and limiting.

## Additional context

Some possible uses:
* Reading node textures to generate in-game maps. (or to get the colors for an online map, e.g. `mapserver`)
* Combining multiple textures more efficiently than texture modifiers.
* Modifying textures in ways not possible with existing texture modifiers. (like the example above)

**Comment by appgurueu** [comment]
Tricky. I could use this too, but a few considerations must be made: This would usually be serverside, meaning it could not support texture packs etc. properly. See also: https://github.com/minetest/minetest/pull/10454 which is clientside.

I already (partially) tried the alternative you mentioned: I wanted to be able to calculate texture dimensions serverside, so I read PNG headers (I didn't need a full PNG reader). I even partially implemented texture modifiers, but eventually gave up as their syntax is plain gross.

**Comment by SmallJoker** [comment]
Modifiers are more portable and does not require the server to deal with graphics stuff. A library could be used to process textures if necessary, but it is IMO not the right approach.
