### ISSUE TITLE
Async "mapblock version mismatch error" seems to be stuck in deadlock sometimes

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11698]
##### Summary

As 5.5 now uses a different compression, you should get a shutdown with reason "mapblock version mismatch error" when trying to join with an older client which doesn't support the new compression. What happens sometimes is that the "shutting down..." progress bar stays there infinitely and MT becomes unresponsive - presumably some kind of deadlock in the background.

##### Steps to reproduce
Try joining a world created (and played on) using the newest 5.5-dev with an older 5.4 client.

**Comment by Zughy** [comment]
Since we're now reaching 5.8, I'd say this is becoming less and less relevant as new versions are released
