### ISSUE TITLE
Clientside formspecs are broken

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#11700]
##### Minetest version

```
5.5.0-f504070 (sfan5's build)
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel Core i7-4796

GPU model: Nvidia GTX 750 Ti
OpenGL version: 4.6.0

##### Summary

These problems **are regressions**: it worked a while ago (around august) with minetest 5.4

###### Part 1
Formspec prepend no longer work with clientside formspecs:
```lua
cs_menu.formspec_prepend = table.concat({
	"bgcolor[#100E1DBB;true]",
	"listcolors[#00000069;#5A5A5A;#141318;#30434C;#FFF]",
	"background9[5,5;1,1;gui_formbg.png;true;10]",
})

minetest.register_on_joinplayer(function(player)
	player:set_formspec_prepend(cs_menu.formspec_prepend)
end)
```
Server formspec:
![image](https://user-images.githubusercontent.com/61794590/137636639-3af9471a-98d2-4092-883d-08517f34c428.png)

Client formspec:
```lua
local menu_form = table.concat({
	"formspec_version[4]",
	"size[18,10]",
	"box[0.25,0.25;1,1;gray]",
	"style_type[button;border=false;content_offset=0]",
	"style[play;fgimg=cs_menu_play_base.png;fgimg_hovered=cs_menu_play_hovered.png;content_offset=0]",
	"image_button[0.25,1.4;1,1;;play;;false;false;]",
	"tooltip[play;Play Open CS]",
	"button[0.25,2.6;1,1;inv;I]",
	"tooltip[inv;Inventory]",
	--"button_exit[0.25,8.75;1,1;quit;Q]",
	"style[quit_game;fgimg=cs_menu_shutdown_base.png;fgimg_hovered=cs_menu_shutdown_hovered.png;content_offset=0]",
	"image_button[0.25,8.75;1,1;;quit_game;;false;false;]",
	"tooltip[quit;Quit Game]",
})
```
![image](https://user-images.githubusercontent.com/61794590/137636705-85186d80-af81-4767-a759-b6635b49b1d1.png)

###### Part 2
`background9` element don't work clientside:

(after disabling formspec prepend serverside)

```lua
local menu_form = table.concat({
	"formspec_version[4]",
	"size[18,10]",
	"bgcolor[#100E1DBB;true]",
	"listcolors[#00000069;#5A5A5A;#141318;#30434C;#FFF]",
	"background9[5,5;1,1;gui_formbg.png;true;10]",
	"box[0.25,0.25;1,1;gray]",
	"style_type[button;border=false;content_offset=0]",
	"style[play;fgimg=cs_menu_play_base.png;fgimg_hovered=cs_menu_play_hovered.png;content_offset=0]",
	"image_button[0.25,1.4;1,1;;play;;false;false;]",
	"tooltip[play;Play Open CS]",
	"button[0.25,2.6;1,1;inv;I]",
	"tooltip[inv;Inventory]",
	--"button_exit[0.25,8.75;1,1;quit;Q]",
	"style[quit_game;fgimg=cs_menu_shutdown_base.png;fgimg_hovered=cs_menu_shutdown_hovered.png;content_offset=0]",
	"image_button[0.25,8.75;1,1;;quit_game;;false;false;]",
	"tooltip[quit;Quit Game]",
})
```
![image](https://user-images.githubusercontent.com/61794590/137636891-4291d110-9f6d-445c-8b81-5fe6ec815752.png)

**Comment by sfan5** [comment]
It would help a lot if you could narrow this down to a range of commits that caused this.
Just testing a few different build from [here](https://minetest.kitsunemimi.pw/builds/) would be good enough.

**Comment by AFCMS** [comment]
I am going to bisect the commit that causes the bug

**Comment by AFCMS** [comment]
Ohhh....

The bug seems to only happens on windows.

The above (working) screenshot comes from my Linux pc, and it still works atm. The screenshot (not working) from the first post comes from a windows one.

**Comment by AFCMS** [comment]
Will try to confirm the regression on windows with 5.4.1

**Comment by SmallJoker** [comment]
![grafik](https://user-images.githubusercontent.com/1497498/144297428-53b7043a-b55b-42c3-b73d-6bda8cb65300.png)
Works for me. 5.5.0-dev.

**Comment by AFCMS** [comment]
> ![image](https://user-images.githubusercontent.com/61794590/137636891-4291d110-9f6d-445c-8b81-5fe6ec815752.png)

Here is how it looks now on linux:
![screenshot_20220114_101014](https://user-images.githubusercontent.com/61794590/149489569-e1601f1a-e904-40a9-8400-ffa046ffa5d4.png)

(exact same formspec)

**Comment by Zughy** [comment]
@AFCMS were you able to bisect and find the culprit?

**Comment by Zughy** [comment]
Feel free to reopen if the problem persists (and provide the culprit)
