### ISSUE TITLE
Android app closes when using the "Back" button on error dialogues

### ISSUE THREAD

**Issue by NSTAdventure** [minetest/minetest#11711]
## Problem
If mods clash or something why need to quit from app? (Minetest will say shutdown and quit) that's so frustrating

## Solutions
Instead of quit from game why not taken back to main menu m

## Additional context

Sorry for issues titles is a bit vague English is not my native language 🙏😊

Yes i am using android 10 Realme UI 1.0
Realme 5i RMX 2030

I am using latest minetest from play store v5.4.1

Thank you 🙏😊

**Comment by NSTAdventure** [comment]
> Does the game also quit when you click the "Okay" or "Close" button within that error dialogue?

No example if mods have problem maybe clash or something after trying to connect to world minetest will automatically shutdown this annoying since you need re open the game again and again -_-

**Comment by wwar-XeStro** [comment]
For me, in singleplayer, if there is a Syntax error somewhere, the game will crash while loading, without giving an error (only in debug.txt)
But when there is another kind of errors (Attempt to index nil value idk what... for example) the world will open but crash later and give the error, and pressing the buttons there lead to main menu.

**Comment by grorp** [comment]
`Android app closes when using the "Back" button on error dialogues` isn't true on the latest `master` branch (and maybe never was true). I think the author of this issue was actually trying to describe the problem that is fixed by #13484.

**Comment by grorp** [comment]
Please close this issue. Depending on how you interpret the reports, it's either invalid or was fixed by #13484.

**Comment by NSTAdventure** [comment]
> Please close this issue. Depending on how you interpret the reports, it's either invalid or was fixed by #13484.

closed until further notice
