### ISSUE TITLE
Allow importing/exporting worlds as zip files

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#11710]
## Problem

Due to Play Store policy changes, on Android it's no longer possible to copy worlds to/from the device and other devices

## Solutions

- Add the ability to export a world as a zip file, which is then given to the Share Intent. This will allow the user to email/add to file system/google drive/etc
- Add the ability to import a world from a zip file

## Alternatives

Unsure

## Additional context

#11466

**Comment by NSTAdventure** [comment]
Agree I don't want lose my world progress 🙏😩😩😩😩😩😩😩⚰️
