### ISSUE TITLE
Segfault crash on old server

### ISSUE THREAD

**Issue by basilgohar** [minetest/minetest#1172]
I am attempting to build & run minetestserver on an older server that's currently running Fedora 13 (yes, it's very old).  While everything builds and starts just fine, when attempting to connect with a client, the server immediately segfaults.  I will post a full gdb backtrace in a reply to this issue.

**Comment by nerzhul** [comment]
Is the problem already present ?

**Comment by Zeno-** [comment]
Closing this because so much has changed since it was reported.
