### ISSUE TITLE
Setting gui_scaling=128 in minetest.conf hangs entire computer

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11738]
##### Minetest version
commit 80d12dbed

##### OS / Hardware

Operating system: GNU/Linux
CPU: Intel Core i7-8565U

GPU model: Intel something?
OpenGL version: 3.0?

##### Summary

Setting gui_scaling to 128 in minetest.conf the game hangs the entire computer upon starting.
(I used a high-end computer – a Thinkpad X390 – to test this, so that it is taken seriously.)

##### Steps to reproduce

1. Set gui_scaling to 128 in minetest.conf.
2. Start game.
3. Observe hang.
4. ???
5. Restart.

**Comment by rollerozxa** [comment]
Can't reproduce either a hang or crash when setting it to 128 through the advanced settings menu, not even after restarting the game after having changed the setting. UI elements are responsive, even if a bit ridiculous. (Linux, Radeon RX 560 with OpenGL 4.6, commit c82ec8b21)

![image](https://user-images.githubusercontent.com/60856959/140618497-79c39657-4c02-440b-958c-b47df00acb98.png)

**Comment by Montandalar** [comment]
Same result as rollerzxa for me. Setting it through the in-game menu adds a little bit of CPU load for a second or two, then the whole thing ends up looking a bit dopey and you have to reset your settings by editing minetest.conf, but no serious breakage.

Tested on:
Minetest versions: c510037e9a built from source with LuaJIT and 5.4.1 available through debian testing repositories.
CPU: Ryzen 3 2200G
Graphics: Gigabyte Radeon™ RX 570 GAMING 4G
Recent AMDGPU-PRO drivers.

Still, I have managed to make my computer churn so hard that my power supply failed while playing minetest. That was when trying to run the advtrains files from linuxworks under Windows 7. I wouldn't rule out some deep-seated issues at some level in the computer system that I can't determine.

**Comment by erlehmann** [comment]
@Montandalar maybe the difference is the integrated graphics vs gaming GPU?

**Comment by HybridDog** [comment]
I also have an intel GPU. When I try it, Minetest crashes with SIGKILL; here is the end of the trace log: [trace_in_gdb.txt](https://github.com/minetest/minetest/files/7532144/trace_in_gdb.txt)
Here are images generated with mprof for the case with gui_scaling=128 and without gui_scaling setting:
![Figure_1](https://user-images.githubusercontent.com/3192173/141645254-d0715936-3bb0-42f5-bfab-907fbe153f5e.png)
![Figure_2](https://user-images.githubusercontent.com/3192173/141645257-84f9aaf1-8b7e-4778-9a0f-92fc2494a74d.png)

**Comment by NathanSalapat** [comment]
I can't reproduce on Linux Mint 20. Gtx1060 nvidia card. Can't click any buttons, but no hanging.

**Comment by erlehmann** [comment]
> According to comments, this only happens with Intel GPUs. Labelling as "Upstream issue",

This is most likely not an upstream issue, the other GPUs just have higher limits that Minetest does not exceed (yet).

**Comment by erlehmann** [comment]
I can confirm that this no longer happens. Instead, Minetest takes several seconds to start and the interface is scaled up, but to less than 128 times its size.
