### ISSUE TITLE
Setting gui_scaling=512 in minetest.conf makes game crash (division by zero)

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11739]
##### Minetest version
commit 80d12dbed

##### OS / Hardware

Operating system: GNU/Linux
CPU: Intel Core i7-8565U

GPU model: Intel something?
OpenGL version: 3.0?

##### Summary

Setting gui_scaling to 512 in minetest.conf the game crashes (division by zero) upon starting.
(I used a high-end computer – a Thinkpad X390 – to test this, so that it is taken seriously.)

I think the crash happens here, near line 190 of `src/irrlicht_changes/CGUITTFont.cpp`:
```
	core::vector2di page_position(
		(page->used_slots % (texture_side_length / font_size)) * font_size,
		(page->used_slots / (texture_side_length / font_size)) * font_size
		);
```

I guess `font_size` became zero somehow?

##### Steps to reproduce

1. Set gui_scaling to 512 in minetest.conf.
2. Start game.
3. Observe crash.

**Comment by rollerozxa** [comment]
I can reproduce this. Worth noting though that when attempting to set it through the advanced settings menu it will be reset to its previous setting as the game crashes before the new value can be saved, making this only an issue on next startup when editing the minetest.conf file directly.

**Comment by Zughy** [comment]
Considering that this is fixed when restarting MT and that I personally see no reason why someone should set the scaling to such high number (128 is already unreadable https://github.com/minetest/minetest/issues/11738#issuecomment-962484451), I'm labelling this as possible close

**Comment by rubenwardy** [comment]
Possible solution/duplicate: #8979

**Comment by erlehmann** [comment]
I can confirm that this no longer happens. Instead, Minetest takes several seconds to start and the interface is scaled up, but to less than 512 times its size.
