### ISSUE TITLE
A shader fails to compile if shadows activated and shadow_soft_radius is set to NaN

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11740]
##### Minetest version
commit 80d12dbed

##### OS / Hardware

Operating system: GNU/Linux
CPU: Intel Core i7-8565U

GPU model: Intel something?
OpenGL version: 3.0?

##### Summary

Setting shadow_soft_radius to NaN in minetest.conf makes no shadows appear and produces error messages.
(I used a high-end computer – a Thinkpad X390 – to test this, so that it is taken seriously.)

```
2021-10-28 16:29:20: ERROR[Main]: Irrlicht: GLSL (> 2.x) shader failed to compile: shaderType: 35632
2021-10-28 16:29:20: ERROR[Main]: Irrlicht: 0:311(47): error: `nan' undeclared
0:311(15): error: operands to arithmetic operators must be numeric
0:311(15): error: operands to arithmetic operators must be numeric

2021-10-28 16:29:20: ERROR[Main]: generate_shader(): failed to generate "object_shader", addHighLevelShaderMaterial failed.
```
##### Steps to reproduce

1. Set shadow_soft_radius to NaN in minetest.conf.
2. Enter a world while shadows are activated.
3. Observe shader compile error messages.

**Comment by Zughy** [comment]
Can't reproduce anymore
