### ISSUE TITLE
CMake does not capture all dependencies, causing erroneous incremental builds & build failures

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11749]
##### Minetest version
probably all, up to and including commit 8dfeba02b

##### OS / Hardware
Operating system: probably all, only encountered on GNU/Linux so far

##### Summary
The dependency information generated by CMake does not actually capture all dependencies between parts of minetest. This can lead to make creating a binary not corresponding to the source code and issues like https://github.com/minetest/minetest/issues/11748 – i.e. make will fail to do the right thing even when asked to rebuild everything (using the `-B` option).

Preface: This is a quite complex issue consisting of at least three bugs that interact with each other in a way that might make it seem unimportant for people not having worked on build systems. Therefore, developers who comment on this without having worked on actually implementing a build system (I have implemented DJB redo and have witnessed many people give up on doing the dificult parts of an implementation) should take great care to actually understand what does happen here and why it is A Bad Thing™ and should also try to actually encounter the bug. Please try to actually understand and reproduce the issues instead of telling me they do not exist or are not important. In particular, you should know that developers usually do not notice when their binary does not correspond to the source code.

The build system bugs I could identify so far are:

###### Neither CMake or make can track non-existence dependencies
* A non-existence dependency exists when the non-existence of a file is a prerequisite for a target to be up to date. The impact of this is that sometimes a target that needs to be rebuilt will not be rebuilt. As far as I know, all build systems that require a full list of dependencies before a build can not track these kinds of dependencies, despite C and C++ projects having a lot of them.
* A peculiar thing about non-existence dependencies is that while embedded programmers and release managers I have encountered usually immediately understand the issue, non-embedded programmers usually immediately dismiss not handling non-existence dependencies being an issue until shown specific examples where it breaks something. However, every person I encountered who spent some time (5 minutes to 2 hours) thinking about the issues arising from not handling non-existence dependencies came to the conclusion that this is an important problem for incremental builds.
   * If you (the reader) are asking for an example of breakage here, you might not have understood what not keeping track of an entire class of dependencies entails – similar to those people who only accept undefined behaviour (UB) is an actual problem once someone demonstrates breakage (as they tend to conflate UB with “implementation defined”).

###### Dependency information provided by CMake is incomplte
* The impact of this is that sometimes targets are not rebuilt due to being outdated when invoking make, even though their prerequisites change, because CMake did not tell make about all prerequisites that are necessary.
* This bug is *almost* fully masked by the next one, but, as https://github.com/minetest/minetest/issues/11748 shows, this does not always happen, which is why I suspect that there exists a CMake bug that I have not yet identified.

###### make unnecessarily rebuilds targets
* Due to make relying on timestamps, it rebuilds a lot of files even if it is not necessary to rebuild them.
* The effect of this is that incremental build times are prolonged – on my main machine by tens of minutes.
* You can reproduce this bug by switching to a different commit or git branch and back, then typing `make`.
* This bug almost entirely masks the previous two bugs – therefore people rarely notice it.
* Fixing this bug reveals the first two bugs (though mainly the second one).

##### Steps to reproduce
A workaround for the last bug is to create a post-checkout git hook to assign the timestamp of a checked out file to the timestamp of the newest commit that changed that file. I originally tried this to speed up the build process – and while that works as intended, it breaks in cases where dependencies are erroneously not specified. This means that any effort to speed up incremental builds by rebuilding less (e.g. caching parts of the build) is likely to trigger the first two bugs – right now, *only* a full rebuild can be considered correct.

Note that this is not the only way to encounter those dependency issues – it is merely a very obvious demonstration of the interplay between those bugs.

1. Copy the following code to `.git/hooks/post-checkout` of your minetest repository:

```
#!/bin/sh
# This post-checkout git hook sets the timestamp of a file to the
# timestamp of the newest commit. This can be useful to prevent a
# useless build system like make to rebuild literally everything.

# Copyright ⓒ 2021  Nils Dagsson Moskopp (erlehmann)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.

# Dieses Programm hat das Ziel, die Medienkompetenz der Leser zu
# steigern. Gelegentlich packe ich sogar einen handfesten Buffer
# Overflow oder eine Format String Vulnerability zwischen die anderen
# Codezeilen und schreibe das auch nicht dran.

set -eu

# Find out which files git just wrote
git diff --name-only "${1}" "${2}" |\
 # Put filename into a variable
 while read -r CHANGED_FILE; do
  # If file does not exist … do nothing
  test -e "${CHANGED_FILE}" || continue
  # If file exists, set filesystem timestamp to commit timestamp now
  COMMIT_TIMESTAMP=$( git log '--pretty=%ct' -n1 "${CHANGED_FILE}" )
  touch --date=@"${COMMIT_TIMESTAMP}" "${CHANGED_FILE}"
 done
```

2. Switch between commits and branches, until you encounter a compile error after invoking both cmake & make. In issue https://github.com/minetest/minetest/issues/11748 I switched between commit 8dfeba02b and commit 53e126a.
3. Note that for some situations, forcing make to rebuild everything (`make -B`) solves the problem, but it does not do that for others.
4. ???
5. Delete CMakeCache.txt, invoke cmake, then force make to rebuild everything (`make -B`) to get to a good state.

**Comment by erlehmann** [comment]
@sfan5, why is “the build system does not actually keep track of all dependencies and you do not always get the binary you actually want, often without noticing it” immediately a possible close for you? Don't say it never happened to you – the “fun” thing is that ppl only notice this bug when it breaks the build (which is why I included an example that does this), but that does not actually mean that it usually actually *works*.

**Comment by sfan5** [comment]
Leaving aside the nature of the bug for a moment consider this: what concrete measures should we take to solve this?

**Comment by erlehmann** [comment]
@sfan5 a possible way to catch newly introduced dependency errors for any commit would be to fully rebuild the previous commit in the CI, then go forward one commit while having my post-checkout hook listed above active & do an incremental build. If the incremental build fails (or the result of the incremental build is different from a full build), the commit likely introduces a new dependency that the build system does not know about, but that fact is masked only by the “unnecessary rebuilding” bug.

**Comment by erlehmann** [comment]
Regarding non-existence dependencies: Not only can `make` not handle them – due to the way the `make` build process works, it is impossible to fix it, i.e. you can not track them while using `make`. All build systems that can handle non-existence dependencies share one property: They produce a full dependency tree as a side effect of the build, instead of needing it before the build. Therefore, the only way to solve the issue 100% would be to use a different build system than `make` at some point in the future.

In case you wonder about the extent of the problem … years ago I wrote the build scripts for the RTS game “Liberation Circuit” https://github.com/linleyh/liberation-circuit and used using my own implementation of DJB redo (as it consists just of a few shell scripts). Liberation Circuit has over 62k lines of C code (or so `sloccount` claims) and the build system currently tracks 326 dependencies (i.e. filenames), but also 206 non-existence dependencies that `make` can never track. For context, Minetest without irrlicht is over twice the size, which to me implies that several hundred dependency relations are *probably* not handled currently.

**Comment by erlehmann** [comment]
> Suppose this approach finds a newly introduced issue in a commit, how would it be fixed? We do not have hand-written Makefiles, interfering with the build process on this level is not possible.

I do not know CMake well enough for that. I do, however, think figuring out how to tell the build system about a new dependency that it can not figure out by itself is the responsibility of the person making a commit that introduces it, just like with hand-written makefiles (or any other kind of build script).

> More importantly this would not help fix any existing dependency issues that may exist.

Why? For starters, existing issues could be diagnosed by doing that procedure for any existing commit.

**Comment by sfan5** [comment]
> I do, however, think figuring out how to tell the build system about a new dependency that it can not figure out by itself is the responsibility of the person making a commit that introduces the new dependency

It sure is. The reason I am asking ahead of time is because I want to make an argument that fixing this is not possible.

> Regarding non-existence dependencies: Not only can make not handle them – due to the way the make build process works, it is impossible to fix it, [...]

...which you've just confirmed here.
Would you prefer this issue to be tagged "Won't fix" or "Can't fix" before it's closed?

**Comment by erlehmann** [comment]
> The reason I am asking ahead of time is because I want to make an argument that fixing this is not possible.

Why would it not be possible to tell a build system about new dependencies? It has been done in the past.

>> Regarding non-existence dependencies: Not only can make not handle them – due to the way the make build process works, it is impossible to fix it, [...]
> Would you prefer this issue to be tagged "Won't fix" or "Can't fix" before it's closed?

I would prefer this issue to be not closed at all, for several reasons:

1. Non-existence dependency handling can be done correctly, even if `make` can not handle them. The easiest way is to just avoid having non-existence dependencies altogether in a project. Other ways involve not using `make` as the only build system, which seems already the case (if I understand the role of CMake correctly).

2. The missing handling of non-existence dependencies is only one of several dependency bugs – probably the one with the least impact on build speed even. The others prevent having fast incremental builds that are actually correct much more – my efforts to prevent unnecessary rebuilds failing hint at that some actual dependencies are not correctly specified, i.e. incremental builds can not work reliably until they are.

**Comment by sfan5** [comment]
> Why would it not be possible to tell a build system about new dependencies? It has been done in the past.

How? Where? I am not aware of this being done in Minetest.

> The easiest way is to just avoid having non-existence dependencies altogether in a project. Other ways involve [...]

Well if you say it can be done I'd like to see it done. I have no idea how to do any of that myself.

> incremental builds can not work reliably until they are

They can and do in practice for people who don't use a git hook that resets file timestamps (and yes, I am aware this means more rebuilding than necessary). The reason I am being so dismissive is that this issue details a largely theoretical problem with small impact to most developers workflow.

**Comment by JosiahWI** [comment]
The post-checkout script does not work properly with Makefiles. If I need to use a different generator such as Ninja, I can do that, but until a workaround is found, I am unable to reproduce this issue.

**Comment by JosiahWI** [comment]
Reproduced with Ninja. CMake does not reconfigure test_config.h.in

We should probably consider this a bug, should a separate issue be opened for it, or should we try to catalogue this here?

I will attempted to fix this particular issue.

**Comment by JosiahWI** [comment]
Further investigation shows that there is currently no good way to do an incremental build with CMake. However, an alternative solution may be ccache, which I am now using with no problems, and am very pleased with. I do not believe fixing this is practical or high priority.

**Comment by erlehmann** [comment]
> Further investigation shows that there is currently no good way to do an incremental build with CMake.

Oof, that's worse than I expected. Any idea how to *force* CMake to rebuild everything? Deleting CMakeCache.txt is one thing I do – but sometimes it does not fix the issue.

**Comment by JosiahWI** [comment]
The cleanest solution is to use out of source builds. e.g.
`cmake . -B your_build_dir`
and then `rm -rd your_build_dir` will completely clear the build. This is a good idea anyway because it will keep clutter out of the source tree and allow you to save multiple build configurations.

**Comment by neoh4x0r** [comment]
> The cleanest solution is to use out of source builds. e.g. `cmake . -B your_build_dir` and then `rm -rd your_build_dir` will completely clear the build. This is a good idea anyway because it will keep clutter out of the source tree and allow you to save multiple build configurations.

Just to add: It will also make merges and checkouts less of a headache.
Eg.  git could refuse to do those operations because you have unstashed changes that need to resolved.

**Comment by kab0u** [comment]
The information stated in the above comments should be reflected in README.md.  The build instructions need a big warning added about cleaning the build tree before rebuilding.  Instructing people to do out of tree builds by default would also be generally helpful. 

These rebuild bugs are driving people crazy and potentially even [alienating](https://irc.minetest.net/minetest/2022-03-19#i_5951773) them from minetest.

**Comment by sfan5** [comment]
This being brought up again has convinced me that this issue is not worth keeping open.
Key points:
* Build systems have ongoing testing, support and maintenance costs. They are not free.
* Getting rid of CMake is not an option
* We will not add a second build system
* Even if, a replacement build system would have to match CMake in platform/environment/OS support

**Comment by erlehmann** [comment]
For future reference:

1. None of the dependency bugs pointed out in this issue are resolved. **Incremental builds are still unreliable.**
2. This means: to be guaranteed get a known-good Minetest binary you have to rebuild entirely every time.
3. Some of the issues I brought up could be fixed while retaining cmake. So far no one has done so.
4. I did offer to add the redo build system because that is the only way I know to solve this.

Also, I am kinda pissed at how this went.

**Comment by neoh4x0r** [comment]
> For future reference:
> 
> 1. None of the dependency bugs pointed out in this issue are resolved. **Incremental builds are still unreliable.**
> 2. This means: to be guaranteed get a known-good Minetest binary you have to rebuild entirely every time.
> 3. Some of the issues I brought up could be fixed while retaining cmake. So far no one has done so.
> 4. I did offer to add the redo build system because that is the only way I know to solve this.
> 
> Also, I am kinda pissed at how this went.

Points (1) -(4) are basically the reason why this was closed as **won't fix**.

In a nutshell:

+ It would require a lot of time and work to support incremental builds and/or to introduce a new build system
+ There would need to be time carved-out (and developers assigned) to test/verify all of it and then even more time to fix any problems, etc, that might come up as a result

Doing a complete rebuild (even if some of it is unnecessary or repetitive) is 100% reliable and it does not require any more work to be done (other than doing the rebuild).

From the point-of-view of a benefit analysis -- introducing/making incremental builds (as well as a new build system) doesn't really provide a benefit that is proportional to the amount of work involved. 

In other words, it requires too much effort to make it happen and the resultant benefit is largely not worth it since this can be resolved by rebuilding from scratch.

**Comment by erlehmann** [comment]
> Using a specific build system (cmake, meson, ninja, etc, etc) won't provide incremental building, and this is because the build system invokes the compiler to do the building (and it must support incremental complication).
> 
> Basically the compiler must support incremental compilation and most of the newer compilers have their own language (such as rust, go, forth, etc)
> 
> See https://en.wikipedia.org/wiki/Incremental_compiler#List_of_incremental_compilers See also https://blog.rust-lang.org/2016/09/08/incremental.html
> 
> In order for minetest to support incremental complication it requires porting the minetest server, client, games, and mods, to a completely different language/compiler, that supports incremental compliation (such as rust, go, forth, etc, etc).
> 
> This is, IMHO, a totally unacceptable proposition for such a trivial matter (a matter which can be solved by doing a complete rebuild and which is 100% reliable).
> 
> I think the issue should be more clear now..... the benefit of having incremental building/compilation is just, unfortunately, not a worthwhile endeavor (and is the reason why it was closed as **won't fix**).

I think this is a misunderstanding. What I want is to not have to rebuild everything every time. This is possible with C++.

**Comment by eli-schwartz** [comment]
@erlehmann

> Preface: This is a quite complex issue consisting of at least three bugs that interact with each other in a way that might make it seem unimportant for people not having worked on build systems. Therefore, developers who comment on this without having worked on actually implementing a build system (I have implemented DJB redo and have witnessed many people give up on doing the dificult parts of an implementation) [......]

Speaking as a developer of a build system (Meson) I hope I'm not disqualified from commenting here, but...

> * A non-existence dependency exists when the non-existence of a file is a prerequisite for a target to be up to date. The impact of this is that sometimes a target that needs to be rebuilt will not be rebuilt. As far as I know, all build systems that require a full list of dependencies before a build can not track these kinds of dependencies, despite C and C++ projects having a lot of them.

I'm actually having a hard time understanding exactly what this means?

Say you have a build edge which takes a file called `input1` and emits a file called `output1`. The most basic node of a build graph. It can be made more complex by:
- depending on another node producing `output2`; in this case, a first-time build will almost certainly not work unless it's listed as an explicit input. 
- depending on a non-node, an implicit input named input2 that exists and doesn't appear on the compiler command line, usually e.g. a header file. First time builds work correctly, incremental rebuilds are not functional... unless you use depfiles to augment the dependency relationships.

What's the non-existence of a file though? If file input3 exists, then output1 is considered up to date, but if you *delete* input3 then output1 must be regenerated without it? I don't think I've seen a dependency concept like this before.

> Dependency information provided by CMake is incomplte

Yes, this is a classic problem of lacking depfiles for augmented dependency tracking. Clean builds work, incremental ones don't rebuild, because the command that created the output nodes didn't communicate what inputs it made use of. This is not cmake's fault, quite frankly.

> make unnecessarily rebuilds targets

Indeed, timestamps are a quick and dirty and *usually* reliable way to track incremental rebuild changes, but a version of Make (or ninja) that was designed to use checksums instead could circumvent that. See e.g. https://neugierig.org/software/blog/2022/03/n2.html by the original author of ninja.

(Ninja *does* dirty an output if its generator command line changes, which Make does not do without quite a bit of extra help.)

**Comment by eli-schwartz** [comment]
> In order for minetest to support incremental complication it requires porting the minetest server, client, games, and mods, to a completely different language/compiler, that supports incremental compliation (such as rust, go, forth, etc, etc).

You *must* be joking. C/C++ incremental compilation has worked quite well for an extremely long time, GCC et al. ***invented*** the concept of a generator program emitting a depfile as a side effect of compilation to augment dependency tracking.

In comparison, rust and golang are from the school of thought where, at a minimum, you must always run a (slow) program in your Makefile to calculate the world and then finally figure out whether the final artifact is out of date, you cannot possibly check whether it's time to incrementally recompile on your own.

And you may simply forget about building, let alone incrementally building, anything that isn't a literal rust/golang source code file, no mixing languages, no running custom commands to build manpages or whatever, no defining installation rules... if you try then you have to manually code your own build system which doesn't work well and repeats every mistake that build systems have made in 30 years.

For that, you need to use meson or cmake or make or autotools, which of course means you pay the "run cargo / go build every single time whether you need to or not" tax.

**Comment by erlehmann** [comment]
> Speaking as a developer of a build system (Meson) I hope I'm not disqualified from commenting here, but...

No, this is exactly the type of person I want to discuss such issues with!

> > * A non-existence dependency exists when the non-existence of a file is a prerequisite for a target to be up to date. The impact of this is that sometimes a target that needs to be rebuilt will not be rebuilt. As far as I know, all build systems that require a full list of dependencies before a build can not track these kinds of dependencies, despite C and C++ projects having a lot of them.
> 
> I'm actually having a hard time understanding exactly what this means?

Consider a C header file that is included somewhere.

During a build, the preprocessor searches for it in `$pwd/A`, in `/usr/local/include/B` and finally finds it at `/usrt/include/C`.

That last path is a dependency. If it gets meaningfully changed, the target needs to be rebuilt.

The first two paths, where the header file was not found, are non-existence dependencies.
If at these non-existing paths in the future a file sstarts to exist, the target needs to be rebuilt.

Otherwise, an incremental build of the project including that header file would be different than a full rebuild.
Make can not handle this and can not be fixed to handle this. A bunch of other systems can handle this case.

Some build systems have special handling for C and C++ header files. This is useful, but ultimately a wrong approach.

> > Dependency information provided by CMake is incomplte
> 
> Yes, this is a classic problem of lacking depfiles for augmented dependency tracking. Clean builds work, incremental ones don't rebuild, because the command that created the output nodes didn't communicate what inputs it made use of. This is not cmake's fault, quite frankly.

This is why I think that some of this is fixable while still using CMake.

> > make unnecessarily rebuilds targets
> 
> Indeed, timestamps are a quick and dirty and _usually_ reliable way to track incremental rebuild changes, but a version of Make (or ninja) that was designed to use checksums instead could circumvent that. See e.g. https://neugierig.org/software/blog/2022/03/n2.html by the original author of ninja.
> 
> (Ninja _does_ dirty an output if its generator command line changes, which Make does not do without quite a bit of extra help.)

My  implementation of redo seems to do what the article suggests (and a bit more) in about 400 lines of shell script.

Last I checked, Ninja explicitly rejected hash-based dependency checking: <https://github.com/ninja-build/ninja/pull/929>
… which is why a shell script build system that hashes if an inode timestamp is not up to date can run circles around Ninja.

**Comment by neoh4x0r** [comment]
> Consider a C header file that is included somewhere.
> 
> During a build, the preprocessor searches for it in `$pwd/A`, in `/usr/local/include/B` and finally finds it at `/usrt/include/C`.
> 
> That last path is a dependency. If it gets meaningfully changed, the target needs to be rebuilt.
> 
> The first two paths, where the header file was not found, are non-existence dependencies. If at these non-existing paths during a future incremental build a file is detected, the target needs to be rebuilt.
> 
> Otherwise, an incremental build of the project including that header file would be different than a full rebuild. Make can not handle this _and can not be fixed to handle this_. A bunch of other systems can handle this case.
> 
> Some build systems have special handling for C and C++ header files. This is useful, but ultimately a wrong approach. **Edit:** The correct approach is to handle non-existence dependencies, obviously.

This sounds like a modular/conditional approach to complication rather than incremental (at least as far as checking if some dependency is not present).

**To me an incremental approach is**

1. Compile some things and save your place
2. Stop compilation

3. Come back some time later, find the saved place, and continue at step 1

**and a modular/conditional approach is**

1. Enable some functionality based on whether a dependency was found or not.
2. Continue with compilation 

Probably in truth...it is actually a hybrid of the two (and others).
But, cmake can handle checking if a dependency is present or not and either enable/disable some function.

**Comment by erlehmann** [comment]
> This sounds like a modular/conditional approach to complication rather than incremental (at least as far as checking if some dependency is not present).

Please read my post again. This is not about conditionals, it is about the fact that creating a file might make a target out of date.

**Comment by neoh4x0r** [comment]
> Non-existence dependencies are not non-existing dependencies. They are a separate category of dependency relation that build systems usually do not handle, despite them being incredibly common.

Non-existence is, by definition, something without existence (which means that is does not exist).

So it very much is a non-existing dependency.

```
Existence clause:
if(A->exists()) then enable_a;

Non-existence clause:
if(!A->exists()) then disable_a;
```

**Comment by erlehmann** [comment]
> > Non-existence dependencies are not non-existing dependencies. They are a separate category of dependency relation that build systems usually do not handle, despite them being incredibly common.
> 
> Non-existence is, by definition, something without existence (which means that it does not exist).
> 
> So non-existence dependencies are missing dependencies.

I see how you get to that point, but this not true.

If they were missing dependencies, they would need to be built.

A non-existence dependency relation represents a *possible* dependency nelarion.

Just try implementing non-existence dependency handling and you will see the difference.

**Comment by neoh4x0r** [comment]
> > Non-existence dependencies are not non-existing dependencies. They are a separate category of dependency relation that build systems usually do not handle, despite them being incredibly common.
> > Non-existence is, by definition, something without existence (which means that it does not exist).
> > So non-existence dependencies are missing dependencies.
> 
> I see how you get to that point, but this not true.
> 
> If they were missing dependencies, they would need to be built.
> 
> A non-existence dependency relation represents a _possible_ dependency nelarion.
> 
> Just try implementing non-existence dependency handling and you will see the difference.

If the dependency was missing, and was not built, you would get a build error when that dependency is referenced.
Such as the errors you posted about originally (such as TEST_MOD_PATH, etc).

The thing is this issue really only impacts developers who are currently working on the code

**The development cycle**
1. Introduce changes
2. Build
3. Test
4. Repeat step 1, until the desired state is reached.

Most users will likely not benefit from this....they will just either (a) download a pre-built binary or (b) compile the code at most once.

The question then becomes:

1. How much (time / work / and personnel) does all of this involve ?
A: too much...

2. How many users does this impact and what benefit will it provide ?
A: 
impacts: only developers who are rebuilding multiple times, and only for small stretches of time)
benefit: faster development in a change, rebuild, test, and repeat scenario (none otherwise)

3. Is there a way to workaround this, so that it all becomes moot ?
A: yes

Moreover, to boil all of this down into its essentials......it sounds like all you want is a faster build.

You can use ccache to make the build process faster.
See https://stackoverflow.com/questions/1815688/how-to-use-ccache-with-cmake
```
$ cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
```

Long story short -- changing the compiler to ccache is far easier then jumping off the cliff of completely overhauling the build-system and makeing sweeping changes (all for such a trivial issue) -- also at this point, it's beating a dead horse.

**Comment by erlehmann** [comment]
@neoh4x0r I am sorry, but you are misunderstanding this issue to a comical extent.

I plan to no longer reply to anything you say about build systems or dependencies, because almost everything you wrote was wrong – and despite you having little to no domain knowledge regarding these things. You appear like one of these people on reddit or hacker news who read about a problem and immediately know better than everyone.

In case you want to be educated about this stuff, you can read the paper ”build systems a la carte”: https://www.microsoft.com/en-us/research/uploads/prod/2018/03/build-systems.pdf

If you can prove that you have read http://news.dieweltistgarnichtso.net/bin/redo-sh.html and at least some of the linked texts, I am willing to continue the conversation on IRC or via email, but the Minetest issue tracker is no place for acting like a know-it-all when you obviously do not know.

**Comment by eli-schwartz** [comment]
> During a build, the preprocessor searches for it in `$pwd/A`, in `/usr/local/include/B` and finally finds it at `/usrt/include/C`.
> 
> That last path is a dependency. If it gets meaningfully changed, the target needs to be rebuilt.
> 
> The first two paths, where the header file was not found, are non-existence dependencies.

Ah, thanks for the explanation.

Meson uses ninja, and configures it to automatically use GCC depfiles. Consider the following project:
```
foo.c
a/foo.h
b/
```

And a compile line:
```
gcc -MD -MF foo.o.d -Wall -Ia -Ib -c foo.c -o foo.o
```

The depfile contains:
```
foo.o: foo.c /usr/include/stdc-predef.h a/foo.h
```

GNU make, when reading this depfile, will make a hard error if a/foo.h is moved to b/foo.h.

```
make: *** No rule to make target 'a/foo.h', needed by 'foo.o'.  Stop.
```

But Meson does not support Make, only ninja, and ninja will simply notice that the file is gone, and rebuild.

However, this only works if the header that was used, disappears. If it records b/foo.h, and you create an additional file in a/foo.h, it will not notice anything.

This covers some cases fairly well. If you have a header that *moved* in a `git checkout otherbranch`, it triggers a rebuild when a file *existence* dependency dirties the output (again, GNU make simply errors out). It cannot solve the case where you have the same header implementation name in two different locations (inside your project and in the system) but arguably that's a namespace bug fixable by renaming. Nor can it solve the case where you have two copies of headers installed on the system, one in /usr/include and one in /usr/local/include.

It sounds like file non-existence dependencies are primarily useful for the combination of:
- build edges use search paths (e.g. C headers)
- there can be environment states where there are more than one version of the dependency, simultaneously, in different directories

**Comment by erlehmann** [comment]
> However, this only works if the header that was used, disappears. If it records b/foo.h, and you create an additional file in a/foo.h, it will not notice anything.

I suspect this means that if you add, for example, a precompiled version of a header, the build system is not going to pick it up automatically.

> It sounds like file non-existence dependencies are primarily useful for the combination of:
> 
>     * build edges use search paths (e.g. C headers)

Yes, search paths with fallbacks are a problem – for big C++ programs like Minetest. Eembedded C code often gets it right.

>     * there can be environment states where there are more than one version of the dependency, simultaneously, in different directories

People tend to focus very much on C and C++ headers when I tell them this example, but the problem happens a lot in many other contextst. A much more common case for a non-existence dependency is that if a target is built using a general build rule and then a more specific build rule appears.

Another quite common case is generating an index for a list of things that is append-only. For example: You have a HTML file with links to chat logs for an IRC channel, where each linked chat log covers a day. The overview page should have a non-existence dependency on the log file for the next day – if that log file is created, the index needs to be rebuilt. Many systems would rebuild the index every time, because they can not handle this case. How would Meson do it?

**Comment by eli-schwartz** [comment]
> I suspect this means that if you add, for example, a precompiled version of a header, the build system is not going to pick it up automatically.

Meson's support for PCH assumes that you have a separate PCH file with the list of headers to precompile, and then passes that in via `-include` (this works fine as long as you have include guards) so it is bound to a PCH -specific filename that can only find the PCH, and is also bound to the "command line" dependency.

> For example: You have a HTML file with links to chat logs for an IRC channel, where each linked chat log covers a day. The overview page should have a non-existence dependency on the log file for the next day – if that log file is created, the index needs to be rebuilt. Many systems would rebuild the index every time, because they can not handle this case. How would Meson do it?

I would probably have the next day's log be created at the same time a stamp file is updated. If new files are continually added, then the generator program probably has to glob them -- they can't all be listed in the meson.build or CMakeLists.txt or Makefile or build.ninja. The generator program would also have to guess what the next day's log will be, which is probably reliable but perhaps there are loggers that don't write a logfile on days where no one says anything. (I don't know, I've never written an IRC logbot.) Also what happens if the logbot goes offline for a day and skips that file?

Note I'm not saying that this is the best solution -- non-existence dependencies do sound interesting, and a more elegant way to solve this same problem if they are supported.

**Comment by eli-schwartz** [comment]
> A much more common case for a non-existence dependency is that if a target is built using a general build rule and then a more specific build rule appears.

This sounds like Makefile stuff where you can have two rules to create one target, and the latest definition wins, usually meaning something that has a much more specific command line overriding a built-in/default rule.

Wouldn't this already be handled by command line dependencies? The more specific build rule isn't the same rule that originally created the output target, so the target is dirtied and ninja or redo will rebuild it (but make won't due to not supporting command line dependencies).

**Comment by erlehmann** [comment]
> > I suspect this means that if you add, for example, a precompiled version of a header, the build system is not going to pick it up automatically.
> 
> Meson's support for PCH assumes that you have a separate PCH file with the list of headers to precompile, and then passes that in via `-include` (this works fine as long as you have include guards) so it is bound to a PCH -specific filename that can only find the PCH, and is also bound to the "command line" dependency.

Look at the dependency graph in my redo PR here, it shows the compiler looking for quite a few precompiled headers in locations that I never told it about: https://github.com/minetest/minetest/pull/12592#issuecomment-1194969039

(Btw, I would be interested what you think of my approach in that PR and if you see some optimization potential in the code.)

**Comment by erlehmann** [comment]
> Wouldn't this already be handled by command line dependencies? The more specific build rule isn't the same rule that originally created the output target, so the target is dirtied and ninja or redo will rebuild it (but make won't due to not supporting command line dependencies).

I guess what you are saying is that target files need to depend on their own build rules. That is trivially true, but I doubt that anyone except DJB is making  targets depend on a `Makefile` in their projects – mainly because in the simplest case (all build rules exist in one `Makefile`) every change of a build rule would rebuild everything (I know you can work around that).

To solve this, redo does not have a concept of “command line dependencies”: A file `foo.bar` will be built using `foo.bar.do` or, if that is not found, `default.bar.do` in the current or any parent directory. This means that if `foo.bar` is built using `default.bar.do`, it has a non-existence dependency on `foo.bar.do`, so that it can be rebuilt using a more specific build rule if it ever comes into existence in the future.

**Comment by eli-schwartz** [comment]
> Look at the dependency graph in my redo PR here, it shows the compiler looking for quite a few precompiled headers in locations that I never told it about: [#12592 (comment)](https://github.com/minetest/minetest/pull/12592#issuecomment-1194969039)

My understanding is that GCC will first look in one directory for a *.h.pch, and then in that directory for a *.h, before progressing to the next directory if it needs to. It can only use one pch overall per compilation unit.

It's sort of moot, if pch files have a different name that isn't directly included, and aren't added as `-Idir` anyway -- only the actually compiled version is available and is used with `-include`. GCC does a wasted lookup for something that in theory cannot ever exist.

> I guess what you are saying is that target files need to depend on their own build rules. That is trivially true, but I doubt that anyone except DJB is making targets depend on a `Makefile` in their projects – mainly because in the simplest case (all build rules exist in one `Makefile`) every change of a build rule would rebuild everything (I know you can work around that).

You might be surprised. The Linux kernel kbuild infrastructure has this -- it stores command lines in `*.cmd` files and build rules check that to see if it's out of date. Make cannot natively do it, so kbuild has gone to great lengths to implement it themselves in what amounts to a complex build system that merely happens to be implemented mostly in Make.

But ninja does something different -- it contains a log file mapping the `foo.bar` output to the most recent command line it was successfully built with, and marks any rule that doesn't match as dirty, even if it's otherwise up to date.

> To solve this, redo does not need a concept of “command line dependencies”: [non-existence dependency stuff]

But that *is* a command line dependency, it just happens to be implemented using non-existence dependencies. :) It doesn't have to be, and for something that wants to list all build rules in a single file it is more convenient to implement it separately.

**Comment by erlehmann** [comment]
> GCC does a wasted lookup for something that in theory cannot ever exist.

File a bug against GCC then? Also, does this mean I can ignore some, most, or all of the compiled system header lookups?

> Make cannot natively do it, so kbuild has gone to great lengths to implement it themselves in what amounts to a complex build system that merely happens to be implemented mostly in Make.

I did not know about that. I just saw Make and assumed it was the discipline of the embedded devs that it does not come crashing down.

>> To solve this, redo does not need a concept of “command line dependencies”: [non-existence dependency stuff]

> But that is a command line dependency, it just happens to be implemented using non-existence dependencies. :)

If a “command line dependency” is a dependency on all commands something was built with, then that is indeed true. I had only considered the single invocation that generates the output – and redo cares about quite a bit of setup and teardown code too, since they might affect the build results and/or the dependencies.

> It doesn't have to be, and for something that wants to list all build rules in a single file it is more convenient to implement it separately.

What reasons do you actually know to have all build rules in a single file? To me iit often looks like it is done just because it simplifies the collection phase where you try to figure out what build rules are there – which is most important in bottom-up toposort builds, but less so in top-down recursive builds that sometimes generate build rules even during the build.
