### ISSUE TITLE
v5.4.2 Books don't save text

### ISSUE THREAD

**Issue by Dee23Gaming** [minetest/minetest#11745]
Minetest 5.4.2 on Windows 10 and Android has introduced a bug in which books are unable to save text.

**Comment by rubenwardy** [comment]
Can't reproduce, I can write books fine on Android in 5.4.2

**Comment by Emojigit** [comment]
Which Android version are you using?

**Comment by BobOmbuzal** [comment]
I got the same problem, i think it has to do with the Virtual Keyboard
It DOES work on my Android 10 Samsung Tab, when i hit Enter, the input window disappears and i can hit save)
It DOESN'T work on the Amazon Fire Tablet with FireOS (It is based on Android 9)
When i hit Enter i get a newline instead, no way to end the input window, so i hit back and all is gone.
(5.4.2 on the Samsung, but 5.4.1 on the FireOS)
