### ISSUE TITLE
Shadows are waving along the edges when moving.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#11743]
##### Minetest version
```
Minetest-5.5.0
```

##### Summary
There are waves at the edges of the shadows when they are moving, particularly which casted from leaves creating an effect as if they are quivering (waving leaves option in the settings is disabled):

https://user-images.githubusercontent.com/25750346/139532464-b6189ae0-02c2-4318-84b4-fc587c8387a9.mp4

##### Steps to reproduce
1. Enable the dynamic shadows.
2. Observe moving of the shadows, e.g. of leaves.

**Comment by SmallJoker** [comment]
Set the quality to very high if you want to reduce this "staircase" movement.
