### ISSUE TITLE
Android apk x86 build

### ISSUE THREAD

**Issue by paju1986** [minetest/minetest#11744]
Hello.
Would be possible to have a x86 apk build for android, so it can be used on x86 tablets. Thanks you!

**Comment by sfan5** [comment]
It would be possible yes.
This depends on #11690, which will allow easily building all the dependencies for x86.

**Comment by linsui** [comment]
I failed to build x86. Other abis build fine. https://gitlab.com/linsui/fdroiddata/-/jobs/2927041458 Could you please take a look? Thanks!

**Comment by rubenwardy** [comment]
Minetest doesn't support Android x86 currently. The PRs to fix this are #12700 and https://github.com/minetest/minetest_android_deps/pull/2
