### ISSUE TITLE
Give a priv to all existing player

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#11756]
## Problem

Now if I update my Minetest version and/or add a mod with basic privs, I have to grant them to players one-by-one (nearly impossible).

## Solutions

If a command or an API to access the player DB is available, then the case will be very simple. Just type a command to do so.

**Comment by NathanSalapat** [comment]
You could do this with an on_player_join callback, although a method to grant and revoke a priv for every player at once could be nice.

**Comment by Emojigit** [comment]
possible. I don't want to give a priv repeatedly (since the privs may be revoked from a player)

**Comment by wsor4035** [comment]
you dont give it repeatedly, register_on_player_join has the player ref and last_login, if its nil, do nothing as they are a new player. check the last-login date against the date you started the mod, if older, grant the priv. this can be completely solved by a mod in lua and i dont see any reason to support it in the engine

**Comment by rubenwardy** [comment]
You can modify auth data when the player is offline. Simply get an iterator from the auth handler

**Comment by appgurueu** [comment]
IMO this is too specific to be added as engine functionality.

**Comment by Emojigit** [comment]
Also a Lua API with `minetest.authDB:get_player_list()` that gives a list of all players included in the database is better than directly adding a callback to grant privs, since that allows more usages on it.

**Comment by appgurueu** [comment]
> Also a Lua API with `minetest.authDB:get_player_list()` that gives a list of all players included in the database is better than directly adding a callback to grant privs, since that allows more usages on it.
`iterate` is fully sufficient (as rubenwardy has already pointed out) and better than a list

**Comment by appgurueu** [comment]
Here are [two commands](https://gist.github.com/appgurueu/eb25c91f74b05208ac5a28401dc5cb65 that do just this. It might be worth extending the builtin grant/revoke commands to support this too.
