### ISSUE TITLE
broken icon graphics with "preload item visuals"

### ISSUE THREAD

**Issue by OBdA** [minetest/minetest#1175]
When

+ using Linux and
+ enable option "preload item visual" and
+ using mods eg. "moreblocks"

The item graphics in the inventory are broken. Either there is no graphic or there is random bit field on some (not all) items.

This bug is recreatable:
+ activate none but "moreblocks" mod
+ start client with "preload item visuals" enabled
+ try crafting a simple stair block

This bug happen only on Linux (tested on Debian jessy with gcc (Debian 4.8.2-15) 4.8.2)
On Windows with official Client I could not recreate this bug.

On Linux this bug are found on stable release and on development, last tested with commit 28d6326bd42a88d5a9245c70d7044d19e4d07954 (Sat Mar 8 11:34:46 2014 -0500)

Following my compile script:
>	${DRYRUN:+echo DRYRUN} cmake . -DRUN_IN_PLACE=0 \
>		-DCMAKE_INSTALL_PREFIX=/opt/minetest-$branch \
>		-DENABLE_FREETYPE=ON \
>		-DENABLE_GETTEXT=ON \
>		-DVERSION_EXTRA= \
>		-DBUILD_CLIENT=1
>
> ${DRYRUN:+echo DRYRUN} make -j2

**Comment by est31** [comment]
Commit 2f4cf0bcca1ce5941dd3d2625fe4636e86e73e75 removed the option, and we use meshes now for inventory icons, so I'm closing this report.
