### ISSUE TITLE
Images in formspecs use "smooth" linear instead of nearest neighbor filtering

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11753]
##### Minetest version
```
5.5.0-dev-2ee427871
```

##### Summary
All images in formspecs are scaled smoothly now (no hard edges). This is a regression. While it looks good for some image buttons, it looks quite odd for items.
![Bildschirmfoto von 2021-11-03 17-29-16](https://user-images.githubusercontent.com/34514239/140102648-aa199083-621d-476e-a480-7cbdacb06955.png)
(nodes still appear "crispy" as they are rendered as models, and not upscaled as images)

##### Steps to reproduce
Simply open the creative inventory.

##### Additional context
[IRC logs](https://irc.minetest.net/minetest-dev/2021-10-13#i_5886291). Most likely related to `draw2DImageFilteredScaled`.

**Comment by sfan5** [comment]
> This is a regression.

Would be useful to know whether this is a 5.4 -> 5.5 thing or more recent.

**Comment by appgurueu** [comment]
> > This is a regression.
> 
> Would be useful to know whether this is a 5.4 -> 5.5 thing or more recent.

5.4.1 doesn't show the issue. I assume it is (like many "changes"/bugs/features in rendering behavior) related to the switch to IrrlichtMT.

**Comment by erlehmann** [comment]
@appgurueu have you tried bisecting the issue?

**Comment by appgurueu** [comment]
> @appgurueu have you tried bisecting the issue?

Bisecting this issue is a PITA for two reasons:
* Compilation errors: Older commits fail to compile using a newer IrrlichtMT. I'd have to checkout & compile the corresponding IrrlichtMT version each time.
* Full recompilation: After each checkout, MT is recompiled fully, which takes a while.

**Comment by erlehmann** [comment]
> Older commits fail to compile using a newer IrrlichtMT. I'd have to checkout & compile the corresponding IrrlichtMT version each time.

The CI configuration contains a hardcoded version of IrrlichtMT, maybe that helps you.

> Full recompilation: After each checkout, MT is recompiled fully, which takes a while.

I interpret this as evidence that the following issue affects more people than me:
https://github.com/minetest/minetest/issues/11749

**Comment by sfan5** [comment]
I couldn't reproduce on ogles2 earlier but I tried it on opengl now and I can't reproduce it there either.

**Comment by appgurueu** [comment]
> I couldn't reproduce on ogles2 earlier but I tried it on opengl now and I can't reproduce it there either.

The issue appears with opengl set as video driver.

**Comment by sfan5** [comment]
```
19:38 <+MTDiscord> <luatic> I'll have another look
19:42 <+MTDiscord> <luatic> Alright, it seems to be gui_scaling_filter
19:42 <+MTDiscord> <luatic> If I disable that setting, everything is back to normal
19:43 <+sfan5> uh
19:43 <+sfan5> that's literally what it's meant to do
19:44 <+MTDiscord> <luatic> sfan5: But it didn't do this on 5.4
19:45 <+sfan5> items were always rendered as 3d models in 5.4, wasting lots of perf
19:45 <+MTDiscord> <luatic> Also the description doesn't say anything about smooth vs. hard scaling
19:46 <+MTDiscord> <luatic> It only says hardware vs. software, not smooth vs. hard.
19:46 <+MTDiscord> <luatic> consider fixing the setting description
```
