### ISSUE TITLE
Debug information screen displays not the entire info.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#11755]
##### Minetest version
```
Minetest-5.5.0-dev
```

##### Summary
When you want to enable the first debug information screen ('F5' key), it displays only the upper line, discarding the lower one. It happens in minetest-5.5.0-dev and it doesn't in the stable minetest-5.4.1. Here are screenshots:

**Minetest-5.4.1-stable** (the underlined line with red color is absent in 5.5.0-dev).
![Снимок экрана от 2021-11-04 16-19-34](https://user-images.githubusercontent.com/25750346/140321630-594f07dd-e7ba-4ef1-bd44-44e5acbe2ba5.png)

**Minetest-5.5.0-dev**
![Снимок экрана от 2021-11-04 16-20-08](https://user-images.githubusercontent.com/25750346/140322003-2f41ee3d-2c73-4bf9-b810-4139687a496e.png)

Maybe is this not a bug and is anything just changed here?

##### Steps to reproduce
1. Install and compile minetest-5.5.0-dev from the github repo.
2. Join the game and enable the first debug information screen (F5).

**Comment by rollerozxa** [comment]
This is a feature, not a bug. See #9315

**Comment by rubenwardy** [comment]
This is intentional. You now need the basic_debug priv to see this info

**Comment by Andrey2470T** [comment]
Ok, thanks.
