### ISSUE TITLE
Signed integer underflow in src/unittest/test_utilities.cpp

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11751]
##### Minetest version
commit 80d12dbed

##### Summary
In the last loop iteration from 1 << 31 (INT_MIN) the value of 1 is substracted here:
```
        for (int exponent = 2; exponent <= 31; ++exponent) {                         
                UASSERT(is_power_of_two((1 << exponent) - 1) == false);
                UASSERT(is_power_of_two((1 << exponent)) == true);
                UASSERT(is_power_of_two((1 << exponent) + 1) == false);
        }
```

I believe this to be illegal.

I verified that 1 << 31 was actually INT_MIN with this program:
```
#include <iostream>
#include <climits>

int main() {
  int i = 1 << 31;
  std::cout << i << std::endl;
  std::cout << INT_MIN << std::endl;
  return 0;
}
```

It prints:
```
-2147483648
-2147483648
```

**Comment by erlehmann** [comment]
@sfan5 it might be a good idea to compile minetest in the CI with `-fsanitize=undefined` and `-fnosanitize-recover=undefined` by default, to catch undefined behaviour that happens when the unit tests are run.

The following program `test.cpp`
```
#include <iostream>

int main() {
  int i = 1 << 31;
  std::cout << i - 1 << std::endl;
  std::cout << "success!" << std::endl;
  return 0;
}
```
when compiled with `g++ '-fsanitize=undefined' '-fno-sanitize-recover=undefined' test.cpp -o test && ./test`, will output
```
test.cpp:5:20: runtime error: signed integer overflow: -2147483648 - 1 cannot be represented in type 'int'
```
and exit with a status code indicating error.

@sfan5 would you concept-approve a change like that?

**Comment by sfan5** [comment]
> @sfan5 would you concept-approve a change like that?

Enabling UBSan in CI sounds useful. However making it fail on the first error should only be done after existing bugs are fixed first (otherwise you have a CI that always fails, not useful).
Just by the way, I am not the sole gatekeeper to things that are or aren't done, you can also ask other devs for the opinion.
