### ISSUE TITLE
Could mod storage be put in a SQLite database?

### ISSUE THREAD

**Issue by TurkeyMcMac** [minetest/minetest#11761]
## Problem

Saving the mod storage as JSON has some problems. If Minetest crashes before the next writing of the JSON data, the changes could be lost. JSON serialization also imposes a practical size constraint on the data, as mentioned here: https://rubenwardy.com/minetest_modding_book/en/map/storage.html#deciding-which-to-use

## Solutions

Mod storage could be put in a SQLite file called `mod_storage.sqlite` or something. I don't know what the performance implications would be, but saving the data could be made more robust this way. The size limit would also be removed.

## Alternatives

I don't know.

## Additional context

None.

**Comment by wsor4035** [comment]
sort of a duplicate of https://github.com/minetest/minetest/issues/10371

**Comment by rubenwardy** [comment]
> sort of a duplicate of #10371

It's not a duplicate as this issue doesn't affect the API, just how mod storage is stored. #10371 improved the API by allowing SQL-like structured data and quering

**Comment by appgurueu** [comment]
DBMS-specific instance of #10978

**Comment by TurkeyMcMac** [comment]
Thanks, I'll close this then.
