### ISSUE TITLE
Proper tag for 5.4.2?

### ISSUE THREAD

**Issue by AMDmi3** [minetest/minetest#11765]
There's a tag `5.4.2-android` in the repo. Is this an official release? In the case it's an official release, can we have a proper `5.4.2` tag to simplify packaging and recognizable by automated tools? Otherwise, can it be renamed to not cause confusion?

**Comment by rubenwardy** [comment]
5.4.2 is only intended to be released for Android. Desktop platforms should ignore it

**Comment by AMDmi3** [comment]
Got it, thanks! However it looks like it also contains some useful optimizations from @sfan5, could be a normal patch release...

**Comment by SmallJoker** [comment]
Question answered, and is deprecated since 5.5.0.
