### ISSUE TITLE
Two signed integer overflows in porting.h, line 251

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11771]
##### Minetest version
Minetest 5.4.1
commit b2596eda3

##### OS / Hardware
Operating system: GNU/Linux
CPU: x86 – Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

GPU model: Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)
OpenGL version: 1.4

##### Summary
There exists a signed integer overflow when using `os.clock()` in mods.

The offending code seems to be in porting.h:
```
inline u64 getTimeNs()
{
struct timespec ts;
os_get_clock(&ts);
return ts.tv_sec * 1000000000 + ts.tv_nsec;
}
```

##### Steps to reproduce
Compile Minetest with `-fsanitize=undefined`, then use a mod that calls `os.clock()`.

You should get an error similar to:
```
minetest/src/porting.h:251:19: runtime error: signed integer overflow: 528888 * 1000000000 cannot be represented in type 'long int'
minetest/src/porting.h:251:32: runtime error: signed integer overflow: 1432203264 + 988204080 cannot be represented in type 'long int'
```

**Comment by sfan5** [comment]
duplicate of #10105 which was fixed more than 6 months ago.
Why are you reporting a bug in 5.4.1?

**Comment by erlehmann** [comment]
@sfan5 sorry, I should have looked for it before!
