### ISSUE TITLE
New handling of direction key bits is not fully backwards-compatible

### ISSUE THREAD

**Issue by AsumFace** [minetest/minetest#11775]
##### Minetest version

```
1d69a23ba48d99b051dcf2a6be225edd7c644c7b and ongoing
```

##### OS / Hardware
Desktop, not sure if and how this affects the android version. 

##### Summary

Commit https://github.com/minetest/minetest/commit/1d69a23ba48d99b051dcf2a6be225edd7c644c7b deprecates the key direction bits but retains a way to still read them for "full" backwards compatibility. 
However, the `keypress_bits` are computed from the movement direction now, meaning that contradicting keypresses like forward+backward and left+right cancel each other out, in movement as well as `keypress_bits`, which did not happen for latter before and breaks the "full backwards-compatible" promise.
This may be a rather obscure corner case, but it is used by the Draconis mod for example (left+right switches view).

##### Steps to reproduce

In your debugger of choice, add a logpoint to `keypress_bits` at the end of `Game::updatePlayerControl` in `src/client/game.cpp` and press random keys in-game. Observe that cancelling directions produce a `0` starting from mentioned commit.

**Comment by sfan5** [comment]
relevant https://github.com/minetest/minetest/pull/11262#issuecomment-903343575

**Comment by APercy** [comment]
This impacted on the Nautilus mod the function of shooting light. In demoiselle and hydroplane to centralize commands and turn the HUD on/off
