### ISSUE TITLE
Cls command to clean messages on the top for Screenshot

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#11773]
Please add some tool to clean screen from messages, notofications, error logs etc ( e.g. before creating screenshot  with clean screen without redundant text information on it)

**Comment by Ygarr** [comment]
![screenshot_20211011_232223_2](https://user-images.githubusercontent.com/14309871/141761360-1c01a98a-0764-461f-98e1-a083e55de0ec.png)

**Comment by erlehmann** [comment]
Press F2.

**Comment by erlehmann** [comment]
Press F2.

**Comment by 0-afflatus** [comment]
F1 hides the HUD
F2 hides chat
