### ISSUE TITLE
Make the map generatior seed in Minetest use all unsigned 64-bit seed for randomization

### ISSUE THREAD

**Issue by SymphonyDawn3** [minetest/minetest#11780]
## Problem

There's a 1 in 2^32 -1 chance that you can play the same world without knowing it. The likelihood of this happening is slim but still more common than using an unsigned 64-bit seed.

These worlds are technically different because they use different seeds but Minetest uses the lower 32-bit of the unsigned 64-bit seed for randomization, instead of the whole bits.

## Solutions

In Minetest, regardless of using the 32-bit or the 64-bit version or using the PC or mobile version, it will use all the bits of the 64-bit seeds, making each seed of a world being different rather than having two 2^32 -1 seeds resulting the same world.

## Alternatives

If it doesn't work on 32-bit CPUs, I think it's possible to implement it on the source code to use 64-bit integers (IIRC C++ supports it out of the box or a library.)

## Additional context

Seed 4294967295:
![screenshot_20211120_182926](https://user-images.githubusercontent.com/86187686/142723415-21d200b8-02e5-439b-beb7-0a121980f3e7.png)

Seed 18446744073709551615:
![screenshot_20211120_182947](https://user-images.githubusercontent.com/86187686/142723506-ef7e25a9-62a7-4540-917d-1f3d5f41e3aa.png)

**Comment by SmallJoker** [comment]
> The likelihood of this happening is slim but still more common than using an unsigned 64-bit seed.

The likelihood is so slim that you likely never experience that in your entire lifetime, even if you create worlds on an hourly basis for 80 years. There's absolutely no need for 64-bit seeds.

**Comment by SymphonyDawn3** [comment]
What's the use of the implementation of 64-bit seeds then if it's that were the case?

**Comment by anon55555** [comment]
> The likelihood is so slim that you likely never experience that in your entire lifetime, even if you create worlds on an hourly basis for 80 years. There's absolutely no need for 64-bit seeds.

That's not true, however I think the probability of equivalent seeds is <1% for daily worlds for 10 years.

P.S. This is the birthday problem.

**Comment by SymphonyDawn3** [comment]
I still don't see the logic of having exactly the same world by using a 32 bit seed and the 64 bit seed having the same but 4,294,967,295 possibilities of the same world, just that the implementation a 64-bit seeds being used still questions me because you're only using the lower part of them to generate.

**Comment by SymphonyDawn3** [comment]
I understand if this is a limitation if it's planned to actually support 64 bit on a few versions later.

**Comment by Zughy** [comment]
No interest after ~5 months, for something that nobody will probably ever notice, with a "possible close" label. Closing
