### ISSUE TITLE
Player collides with itself

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11783]
##### Summary
If `collide_with_objects` is set to `true` for players, they do not only collide with other players, but also with themselves. This appears to only become noticeable at high speeds though. Fix should be pretty trivial.

**Comment by Andrey2470T** [comment]
Lol. Though, it is interesting to know how this bug happens visually. Does your model just immediately stop (the velocity is nullified at some moment) or does it start hesitating/twitching around itself trying to stop?

**Comment by appgurueu** [comment]
> Lol. Though, it is interesting to know how this bug happens visually. Does your model just immediately stop (the velocity is nullified at some moment) or does it start hesitating/twitching around itself trying to stop?

Nullification of a component.

**Comment by Zughy** [comment]
Could you provide a minimal test? It'd make my life easier :)
