### ISSUE TITLE
Add support for nickname being different from username

### ISSUE THREAD

**Issue by TuringZauber** [minetest/minetest#11794]
It would be helpful to have a `/nick` command to change ones display name similar to how it's done on IRC.
This can be helpful e. g. properly type out your preferred unicode name or showing clan alliance or just changing into a fresh identity or something.

Surely some server admins might not like this.
Thus it's probably for the better if the feature is _supported_ by minetest and _enabled_ via some sort of mod or plugin. 
If there's already a mod/plugin out there for creating an IRC-like `/nick` command then surely this is already possible and this issue can be closed.

**Comment by wsor4035** [comment]
there does not exists a mod for this, but there is enough methods already exposed via the api for this. specifically minetest.register_on_chat_message(function(name, message)) returning true so the engine doesnt handle it, and then using minetest.chat_send_all(<newnick> message)

**Comment by TuringZauber** [comment]
It's not just about chat but also display name in the multiplayer world, properly keeping track of area protections, all that user management related stuff

**Comment by wsor4035** [comment]
this also can be done by mods, it is not something thats needs to be in the engine

**Comment by TuringZauber** [comment]
When this is do-able without engine change then this is a non-issue, thanks for answering!
