### ISSUE TITLE
Playermodel visible from inside when using Direct X 9

### ISSUE THREAD

**Issue by H4x0r-000** [minetest/minetest#11790]
##### Minetest version

```5.4.1

```

##### OS / Hardware

Operating system: Windows 7
CPU: Amd Athlon II

GPU model: Onbrord
OpenGL version:

##### Summary
 When using Direct X 9 as graphics driver, the playermodel is visible from the inside, wich is not playable.

##### Steps to reproduce
 Settings -> Advanced Settings -> Search for "driver" (or navigate to it manualy) -> set it to Direct X 9

**Comment by rollerozxa** [comment]
Switch to OpenGL.

onsdag 24 november 2021 skrev H4x0r_000 ***@***.***>:
> Minetest version
>
> OS / Hardware
>
> Operating system: Windows 7
> CPU: Amd Athlon II
>
> GPU model: Onbrord
> OpenGL version:
>
> Summary
>
> When using Direct X 9 as graphics driver, the playermodel is visible from
the inside, wich is not playable.
>
> Steps to reproduce
>
> Settings -> Advanced Settings -> Search for "driver" (or navigate to it
manualy) -> set it to Direct X 9
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. <
https://ci6.googleusercontent.com/proxy/cYZ5vIYD7opIAvyruUviNd9SbM4L11KLbnqjL8GOeJtX15Bvrc7Qj5rNFGBrySmbJ8jx2aMRjbWX-t8qnmTl08SBUhZx3lLRbmNKQreCBfU4eFtDRzupvLMNlCh68fufp9CdzUEyPWnSQzxhuovUJwSHSVoVbRcIStPEnCMtCj3YgK4TIrRj5Ux4c2VQ1PvVTT_Ri6YhAmdje23N1kd_73zTItc=s0-d-e1-ft#https://github.com/notifications/beacon/AOQJU754YDVNQTCQQRLGLQDUNTIF5A5CNFSM5IV4P2UKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4P2SDBXA.gif>

**Comment by rollerozxa** [comment]
Switch to OpenGL.

**Comment by rubenwardy** [comment]
As rollerozxa said, we no longer support Direct X

**Comment by H4x0r-000** [comment]
The Problem with that is that Direct X9 is the driver wich works best on older Hardware and one thing I realy liked on mt is that you could run it on almost everything

**Comment by rollerozxa** [comment]
OpenGL works perfectly fine on old hardware, but if your OpenGL drivers on
Windows are bad just switch to Linux. You'd be better off anyways with a
lightweight Linux DE on old hardware like this.

tisdag 7 december 2021 skrev H4x0r_000 ***@***.***>:
> The Problem with that is that Direct X9 is the driver wich works best on
older Hardware and one thing I realy liked on mt is that you could run it
on almost everything
