### ISSUE TITLE
Empty passwords

### ISSUE THREAD

**Issue by juanroman74454811** [minetest/minetest#11792]
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
I'm always frustrated when it closes me out of the game when i don't have a password

## Additional context

and add minigames!

**Comment by SmallJoker** [comment]
This is a feature for server owners who would like to enforce passwords on players. Join another server if you are annoyed by this.

https://github.com/minetest/minetest/blob/206e131854392ed2d39b3456f7a1b5a54bd1bff9/builtin/settingtypes.txt#L1172-L1173

^ relevant configuration option server-side.

**Comment by juanroman74454811** [comment]
![Icons](https://user-images.githubusercontent.com/92176733/143499466-f075f122-68e6-49c1-a9cc-f76dc7e3a44d.png)
Thanks now look at Tanrie's icons today.
