### ISSUE TITLE
New drawtype requests

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#118]
Just writing these down here for the record.  Two drawtypes requested:

1) (the first one has long since been covered by nodeboxes)

2) A variant of the raillike draw type where the texture is _always_ drawn at an angle, sticking out and down from the surface the player is facing when the object is placed against it, even if there isn't anything nearby that would cause the existing raillike draw type to do this.   This would be useful for awnings over a window or door.

3) A second variant of the raillike draw type where the texture will fill inside and outside corners when there are enough similar objects surrounding it - for example when using this drawtype to draw angled roof shingles.  This image should explain it why it's needed: 

![roof](https://f.cloud.github.com/assets/1733537/906411/1792932a-fc9e-11e2-9886-b3ff83b7e3ce.png)

**Comment by paramat** [comment]
I don't feel these are fundamental or needed enough to add a new drawtype.
