### ISSUE TITLE
Benchmark Utility for custom mods and plugins

### ISSUE THREAD

**Issue by Ubiquity5** [minetest/minetest#11801]
## Problem

Minetest as an engine is supposed to be expanded by custom Lua/C++/Python/whatever.
We want to incentivize the writing and the using of mods. Perhaps even _many_ mods.

Contemporary MT servers (e. g. your-land.de:30000) are facing performance issues most likely due to custom plugins. They're already using Lua-JIT but it's not helping enough.

## Proposed solution

We need to assist server-admins in evaluating the performance of mods and resources.
This utility should be really easy to read even for novices. Perhaps a report in the form of of "this mod weights ... units" and "this mod weights ... units" with all technical details hidden would be really great!

Further (I don't know if this exists for Lua) developers need tools to benchmark their mods against real-life minetest server usage in order to improve the design and performance of the mod.

![example image of an profile tool. Image courtesy of https://stackify.com/three-types-of-net-profilers/](https://user-images.githubusercontent.com/6533815/144131269-8b1c22e0-ce5a-4333-af94-92968013b8c9.png)
<sub>(image only for illustrative purposes. The copyright is believed to be belong to Stackify LLC)</sub>

**Comment by erlehmann** [comment]
@TuringZauber check out https://monitoring.minetest.land/

If you develop a mod, you could debug network performance issues using this script I made:
https://git.minetest.land/Mineclonia/Mineclonia/src/branch/master/tools/analyze-packet-spam

**Comment by wsor4035** [comment]
>We need to assist server-admins in evaluating the performance of mods and resources.
this already exists, see profiler.setting in minetest.conf such as https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1680-L1695

also see mods such as https://github.com/minetest-monitoring/monitoring

**Comment by wsor4035** [comment]
prometheus support was merged in here https://github.com/minetest/minetest/pull/9719

however a pr to add abilities for minetest mods to use it by @rubenwardy was closed https://github.com/minetest/minetest/pull/10980
