### ISSUE TITLE
Entities/Objects darken with increasing shadow strength

### ISSUE THREAD

**Issue by Arbertor** [minetest/minetest#11804]
##### Minetest version

```
Minetest 5.5.0-dev-1dc1305
```

##### OS / Hardware

Operating system: Ubuntu 20.04.3 LTS
CPU: Intel® Core™ i5-6300HQ CPU @ 2.30GHz × 4 

GPU model: NVIDIA Corporation GM108M [GeForce 940MX] / NVIDIA GeForce 940MX
OpenGL version: 4.6.0

##### Summary
 
The default dynamic shadows are almost imperceptible, and I think increasing the strength helps a lot to add a more realistic atmosphere, but that makes all entities look black (players, items, mobs...).

Dark objects:
https://user-images.githubusercontent.com/86980167/144214222-a1a8f306-a3a1-488f-b37c-ffd5bf514ff7.png

##### Steps to reproduce

Activating dynamic shadows at any quality and increasing shadow strength

Shadow strength:
https://user-images.githubusercontent.com/86980167/144214228-c2584500-d23a-4c9b-a535-2458644dd7e5.png

**Comment by x2048** [comment]
Should be fixed by #11747. @Arbertor can you check on a more recent build?

**Comment by x2048** [comment]
Just checked. This is resolved.
