### ISSUE TITLE
Error message resulting from pixel font regression is useless

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11809]
##### Minetest version
Commit 1dc1305ada07da8c2a278b46a34d58af86184af9

##### OS / Hardware
Operating system: Debian GNU/Linux
CPU: Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

##### Summary
I wanted to upgrade from Minetest 5.4.1 to the latest dev version on my computer.

I started Minetest compiled at commit 1dc1305ada07da8c2a278b46a34d58af86184af9 and got the following result:

```
; ./bin/minetest
2021-12-01 18:22:42: ERROR[Main]: Minetest cannot continue without a valid font. Please correct the 'font_path' setting or install the font file in the proper location.
abort
# exited sigabrt
```

##### Steps to reproduce
1. Have the following settings in your minetest.conf that work fine in Minetest 5.4.1

```
font_size = 16
font_path = ${MINETESTDIR}/fonts/mono_dejavu_sans_16.xml
freetype = false
```
(`${MINETESTDIR}` is a placeholder for the Minetest repository folder.)

2. Start Minetest.
3. Get an error message and no Minetest.

**Comment by erlehmann** [comment]
Future people, note that this issue is only for the error message being not helpful at all!

Minetest started for me when I commented out `freetype = false` like this: `#freetype = false`.
This is probably because I had a TTF font configured as a fallback font.

Issue for the pixel font regression: https://github.com/minetest/minetest/issues/11611

**Comment by erlehmann** [comment]
It seems I did not clearly explain why I consider the error message useless:

1. The font file is actually valid, but Minetest stopped supporting it.
2. The font file is at the proper location (look at the repository).
3. My solution requires something else than suggested (FreeType).

**Comment by sfan5** [comment]
I see no sense in keeping this open in addition to #11611, thus closing.

**Comment by erlehmann** [comment]
@sfan5 I assume that this error message will be encountered by users of pixel fonts regardless of if https://github.com/minetest/minetest/pull/11767 is merged or not. Do you think that is not the case?
