### ISSUE TITLE
It is possible to ban 127.0.0.1 using /ban singleplayer, forbidding yourself to play a singleplayer game in the world where you are banned

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11819]
##### Minetest version
commit 1dc1305ada07da8c2a278b46a34d58af86184af9

##### Summary
It is possible to ban 127.0.0.1 from playing a singleplayer game in a specific world using /ban singleplayer

This is entirely expected, obvious, and hard to revert without editing the world folder.

##### Steps to reproduce
`/ban singleplayer` (don't do this in your favourite world)

##### Remedy
Edit the file `ipban.txt` in your worlds folder to remove the ban.

I could not find any way in the GUI to do this.

**Comment by TechPersonYT** [comment]
The code for the `/ban` command can be found [here](https://github.com/minetest/minetest/blob/48e508052ad477eda1142f08990d523c8b9701ea/builtin/game/chat.lua#L1122-L1145). It seems reasonable that a failsafe should be included to prevent inexperienced or misguided players from locking themselves out of their world, especially if the only remedy is through the manual editing of game files (which could seem cryptic and unintuitive to some).

A simple solution would be adding an edge case for when `/ban` is run while in singleplayer:

```lua
core.register_chatcommand("ban", {
	params = S("[<name>]"),
	description = S("Ban the IP of a player or show the ban list"),
	privs = {ban=true},
	func = function(name, param)
		if param == "" then
			local ban_list = core.get_ban_list()
			if ban_list == "" then
				return true, S("The ban list is empty.")
			else
				return true, S("Ban list: @1", ban_list)
			end
		end
		if minetest.is_singleplayer() then  -- New code
			return false, S("You cannot ban players in singleplayer!")
		end
		if not core.get_player_by_name(param) then
			return false, S("Player is not online.")
		end
		if not core.ban_player(param) then
			return false, S("Failed to ban player.")
		end
		local desc = core.get_ban_description(param)
		core.log("action", name .. " bans " .. desc .. ".")
		return true, S("Banned @1.", desc)
	end,
})
```
