### ISSUE TITLE
minetest.dig_node not calling on_drop handler

### ISSUE THREAD

**Issue by loosewheel** [minetest/minetest#11818]
##### Minetest version

```
5.4.1
```

##### OS / Hardware

Operating system: Linux Mint
CPU: i5 M520

##### Summary

minetest.dig_node (pos) does not call the on_drop handler for the item when dropping, only the digging handlers.

##### Steps to reproduce

Not sure what to put here, just call the function. I've made a dummy mod whose handlers scream out to chat for debugging purposes.

##### Note
I don't know if this function is used much. Dug items are generally place in the player's inventory, not dropped. Perhaps it would be better for this function to return an ItemStack of the dug item, rather than dropping it. This would leave the modder the opportunity to do something with the dug item, rather than lose control of it. Perhaps an optional second parameter for whether to drop the item, or return the entity containing the drop, and returning nil on failure, to maintain backwards compatibility.

**Comment by sfan5** [comment]
`minetest.dig_node` is not special in this regard, in the very end `minetest.handle_node_drops` is called which behaves just like if a player dug the node. By default items are also only dropped when the inventory is full.

Looking at the documentation it's not specified at all when on_drop should be called. In reality it was only ever called for explicit drop actions from the player (pressing Q or dragging item out of the formspec).

**Comment by loosewheel** [comment]
Ok, thanks.
