### ISSUE TITLE
Builtin /time command does not validate input, causes Lua error

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11816]
##### Minetest version
Commit 1dc1305ada07da8c2a278b46a34d58af86184af9

##### OS / Hardware
Operating system: Debian GNU/Linux
CPU: Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

##### Summary
The following commands all crash Minetest:

```
/time NaN
/time -Inf
/time 1e30
```

This happens, very broadly speaking, because the function that handles the `/time` command does not fully validate its arguments before processing them.

##### Steps to reproduce
Enter one of the following commands:

```
/time NaN
/time -Inf
/time 1e30
```

**Comment by TechPersonYT** [comment]
The code for the `/time` command is [here](https://github.com/minetest/minetest/blob/48e508052ad477eda1142f08990d523c8b9701ea/builtin/game/chat.lua#L1017-L1057).

These checks seemed to be enough to eliminate the error in all 3 listed cases:

```lua
if new_time ~= new_time or new_time == math.huge or new_time == -math.huge or new_time >= 1e30 then
	return false, S("Invalid time.")
end
```

However, times very close to `1e30` (but not exceeding it) might still crash, and there may be other conditions where this occurs as well.
