### ISSUE TITLE
Limit texture dimensions to sane sizes

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11823]
##### Minetest version
Commit dc1305ada07da8c2a278b46a34d58af86184af9

##### Summary
I used the texture `[combine:16x999999999:0,0=default_cobble.png:0,16=default_wood.png` and got a `std::bad_alloc` when starting the game in the GUI. The client did not crash, it just could not join the world.

I would have expected to be able to play the game with a message that the texture could not be generated.

##### Steps to reproduce
See above.

**Comment by sfan5** [comment]
Minetest doesn't really handle `std::bad_alloc` anywhere and I don't think it should. We could however limit texture dimensions.

**Comment by erlehmann** [comment]
> We could however limit texture dimensions to sane sizes.

Yes please.

**Comment by Zughy** [comment]
Can't reproduce it anymore, closing
