### ISSUE TITLE
Client hangs on startup if too many texture modifiers are used in a game or mod

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11829]
##### Minetest version
commit 1dc1305

##### Summary
See title. But just how many is too many? No idea really. 10k are definitely enough.

##### Steps to reproduce
1. Append the string `^[` to some texture modifier for a node texture like 10000 times.
2. Try to join a world. Observe the game hanging during the “block definitions” step.
3. Wait forever.

**Comment by sfan5** [comment]
Do you want arbitrary limits to be added to absolutely each and every part of Minetest or how do you propose this to be fixed sensibly?

**Comment by erlehmann** [comment]
> Do you want arbitrary limits to be added to absolutely each and every part of Minetest

In principle, no. As seen in https://github.com/minetest/minetest/issues/11828 adding *arbitrary* limits makes for new bugs (or, at the very least, for unexpected behaviour). In my opinion, limits must be very carefully chosen (and not roughly estimated) to match the capabilities of the underlying data types and algorithms.

I therefore want the limits of Minetest input handling to be exactly the limits of what the implementation can actually handle. Only that way you can avoid crashes, hangs, and security issues.

This means that each functions input needs to be checked against a regular, context-free or calc-regular grammar before the engine attempts to process it – and Minetest should only process values that are valid according to the grammar. It should not

In the case of this bug, I have no idea how to fix it sensibly yet. But I am sure that adding arbitrary limits would just mask the bug instead of fixing it.

I will now research how it comes to be. It may have to do with string length or nesting modifiers or maybe a bad regex – how to fix it in a good way depends on that.

**Comment by erlehmann** [comment]
I may have found the cause: In the function `TextureSource::generateImage()` in the file `src/tile/client.cpp` the so-called “shotgun parser” technique is used to create an image. The parser contains both validation and business logic and seems to allow for unbounded recursion, as it recurses on itself whenever it encounters a circumflex character.

I have no idea *how* that hangs the engine without producing a crash or running out of memory, but it should be obvious to anyone that this kind of parsing & business logic mixing – the shotgun parser – is a highly fragile construct and refactoring it into a non-shotgun-parser (i.e. first parsing input completely, then acting on it) is likely to improve the situation.

**Comment by appgurueu** [comment]
Related: #11588

**Comment by Zughy** [comment]
> Append the string ^[ to some texture modifier for a node texture like 10000 times.

That's not something someone would ever do though, as highly unpractical. As a modder since 2020, the maximum amount of texture modifies I've ever appended on a single texture is 3. Is the stalling visible with, I don't know, 5 texture modifiers?

About https://github.com/minetest/minetest/issues/11829#issuecomment-985932414 : I lack the technical knowledge to evaluate what you're saying, but it seems the case for a separate issue

**Comment by appgurueu** [comment]
> > Append the string ^[ to some texture modifier for a node texture like 10000 times.
> 
> That's not something someone would ever do though, as highly unpractical. As a modder since 2020, the maximum amount of texture modifies I've ever appended on a single texture is 3. Is the stalling visible with, I don't know, 5 texture modifiers?

It is sometimes done though when generating larger textures. Now we have [png for that, but if modders want to support older versions there is still a need for this.

**Comment by erlehmann** [comment]
> About https://github.com/minetest/minetest/issues/11829#issuecomment-985932414 : I lack the technical knowledge to evaluate what you're saying, but it seems the case for a separate issue

Using a proper parser for texmods is the only guaranteed way to ensure that every texmod that is processed is processed without causing a crash or hang. It would also make it easier to expand texmods later.

> As a modder since 2020, the maximum amount of texture modifies I've ever appended on a single texture is 3.

> It is sometimes done though when generating larger textures. Now we have [png for that, but if modders want to support older versions there is still a need for this.

The `[png` texmod is relevant here only in the context of making the parsing situation even worse.

Mod-wise, my version of `mcl_maps` generates a map overlay with points of interest. This means having an image in the player HUD which at minimum has a background (piece of paper), a 128×128 map rendering, a player position/direction overlay and a bunch of POI markers.

You can see a demonstration screencast here: https://mister-muffin.de/p/YDsb
