### ISSUE TITLE
Configurable internal render resolution

### ISSUE THREAD

**Issue by clavinet** [minetest/minetest#11825]
## Problem
Many devices, especially phones, have ridiculously high resolution screens that make text look really great but are a completely overkill for watching videos or playing games.

## Solutions
Implement a configurable internal resolution that's lower than the native screen resolution.
SuperTuxKart has this as a percentage slider for example.

## Alternatives
Use OS settings to drop the overall screen resolution while gaming. Some Android ROMs can do this, but unfortunately not all of them.

## Additional context
Can't think of much here, except the fact that resolutions like 3200x1440 are wasteful at normal viewing distances for games on a 6-7" screen.
With a lower resolution, you could have better graphical effects and/or longer battery life.
This could also be useful for high res laptop screens of course.

**Comment by rubenwardy** [comment]
This is already supported, it's called undersampling

**Comment by clavinet** [comment]
Thanks, that's exactly what I meant.
Unfortunately every game seems to call this same functionality differently, so it can be hard to find...
