### ISSUE TITLE
Emerge threads aren't started for two seconds for no reason

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11837]
`server.cpp`:
```c++
	/*
		Trigger emergethread (it somehow gets to a non-triggered but
		bysy state sometimes)
	*/
	{
		float &counter = m_emergethread_trigger_timer;
		counter += dtime;
		if (counter >= 2.0) {
			counter = 0.0;

			m_emerge->startThreads();
		}
	}
```
After the first call, which takes 2s to happen, the event manager will set a flag to true; all subsequent calls are no-ops. The call should be done instantaneously, without a timer, and ideally outside of the game loop.

**Comment by sfan5** [comment]
The comment suggests this is a workaround for the emerge thread sometimes getting stuck so I expected there to be a `m_emerge->startThreads()` somewhere else but there doesn't seem to be one.

**Comment by erlehmann** [comment]
@celeron55 can you please explain the purpose of the 2 second delay introduced in 2010 in the commit c707e00195f1035ae535f3fc8697af42e73190c0? The commit message is “sitä sun tätä tekeillä, toimii kivasti”.

**Comment by celeron55** [comment]
https://irc.minetest.net/minetest/2021-12-05#i_5905184
