### ISSUE TITLE
InvalidPositionException in src/map.cpp is not caught, making it possible for players to crash the server

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11835]
##### Minetest version
commit 1dc1305a

##### Summary
A common user action, if done in a particular malicious way, can make Minetest invoke `createSector()` with a position that lies over the maximum mapgen limit. In that case, Minetest will not catch the exception and therefore crash:

2021-12-05 08:39:30: ERROR[Server]: An unhandled exception occurred: createSector(): pos. over max mapgen limit
2021-12-05 08:39:30: ERROR[Server]: In thread 7f9525e8e700:
2021-12-05 08:39:30: ERROR[Server]: /tmp/minetest/src/server.cpp:82: virtual void* ServerThread::run(): A fatal error occurred: createSector(): pos. over max mapgen limit

##### Steps to reproduce
I am purposefully leaving this out. I have five reasons for that:

1. Griefers might abuse any information on how to crash servers … to crash servers.

2. The above information should be enough to prevent the crash from happening. Note that code should only catch exceptions it can actually handle – and I have absolutely no idea how to handle this one cleanly except for ways that will surely be rejected.

3. I am curious about what other people come up with. I think whoever deals with this bug might come up with a different way of triggering it. I hereby promise I will post reproduction steps once someone comes up with a way to reproduce the crash.

4. Giving reproduction steps for bugs that happened beyond mapgen boundaries has lead to faulty bugfixes in the past as soon as someone saw an opportunity to compare some value to MAX_MAP_GENERATION_LIMIT to break the reproduction steps:

* https://github.com/minetest/minetest/pull/11770 → merged with faulty limit, despite my warnings, leading to https://github.com/minetest/minetest/issues/11828 & some other bugs
* https://github.com/minetest/minetest/pull/11831 → not yet merged, may still become a correct bugfix

5. @sfan5 recently told me to “bugger off” [1] and called me a “fucker” on #minetest-dev IRC [2] (and then silenced me there [3] [4]). This has nothing to do with the bug I have reported in this issue, but I have little interest to do more than the bare minimum when people insult me.

[1] https://github.com/minetest/minetest/pull/7629#issuecomment-974610899
[2] https://irc.minetest.net/minetest-dev/2021-12-02#i_5904059
[3] https://irc.minetest.net/minetest/2021-12-04#i_5904716
[4] https://irc.minetest.net/minetest/2021-12-04#i_5904727

**Comment by sfan5** [comment]
Please provide a meaingful backtrace and/or verifiable reproduction steps. If this does not fall under your "bare minimum" we can close this issue.

**Comment by erlehmann** [comment]
> Please provide a meaingful backtrace and/or verifiable reproduction steps.

@celeron55 has convinced me to help you. I want to provide a backtrace, but I have to learn more about gdb and get a debug build, so in the meantime, here the instructions:

1. Make a `minetest_game` TNT node explode at the border of the outermost mapblock (e.g. where x is >31000).
2. Get the above error message.

Please do *not* break what happens in the outermost mapblock more by adding another superfluous check for x>31000.

**Comment by NathanSalapat** [comment]
For fun I thought to try this out, in singleplayer I teleported to 31000, which was out of the map, so I had to fly, with noclip back into the map(30927). Once on the ground I placed a bunch of TNT on the world edge, blew it up, absolutely no crash. I am unable to place any TNT nodes outside of the map edges. with noclip and fly I can exit the map, but can't place any nodes.
I am using the latest build as of this morning, d9d219356. OS is Linux Mint 20, 64bit.

**Comment by SwissalpS** [comment]
did you try pushing TNT out of bounds with pistons, movestones or similar?

**Comment by NathanSalapat** [comment]
Reproduction steps didn't say anything about that, but I can give it a try.

**Comment by erlehmann** [comment]
> For fun I thought to try this out, in singleplayer I teleported to 31000, which was out of the map, so I had to fly, with noclip back into the map(30927). Once on the ground I placed a bunch of TNT on the world edge, blew it up, absolutely no crash.

That is definitely the wrong location, as there should be an entire mapblock past x=30927 that is just usually not sent to the client. As mapblocks are 80×80×80 (or so I heard), this means in the default configuration you can go to 31007 … which is one among several reasons why putting in checks for 31000 is stupid by the way, but no one is willing to listen to me.

The behaviour at that map border (invisible mapblock) has been carefully engineered and anyone fiddling with it is going to create a shit ton of bugs unless they are very very careful (which developers have not been regaring OOB isues in the lasts few weeks).

**Comment by erlehmann** [comment]
> Nope, that just deletes the TNT

You can push a TNT into the invisible map block and retrieve it with a piston.

You can also use worldedit to move nodes there and back I guess?

I hope that convinces you the map does not end at x=30927.

(I figured out how to make the mapblock visible btw.)

**Comment by erlehmann** [comment]
> For fun I thought to try this out, in singleplayer I teleported to 31000, which was out of the map, so I had to fly, with noclip back into the map(30927). Once on the ground I placed a bunch of TNT on the world edge, blew it up, absolutely no crash.

What part of my reproduction steps suggested that anything bad would happen at x=30927 by the way?

**Comment by erlehmann** [comment]
> I am unable to place any TNT nodes outside of the map edges. with noclip and fly I can exit the map, but can't place any nodes.

To be clear: You can indeed place them, but you will probably not see them at the client with default settings.

**Comment by NathanSalapat** [comment]
> > For fun I thought to try this out, in singleplayer I teleported to 31000, which was out of the map, so I had to fly, with noclip back into the map(30927). Once on the ground I placed a bunch of TNT on the world edge, blew it up, absolutely no crash.
> 
> What part of my reproduction steps suggested that anything bad would happen at x=30927 by the way?

I think you missed the entire point of what I was saying. I meant your reproduction steps don't work.... You don't mention what needs to be done to be able to get mapgen to create the world that I could get to at the location your mentioned the error happening at.

**Comment by erlehmann** [comment]
@NathanSalapat the probably easiest way to get Minetest to show the normally invisible outer mapblock would be to generate a world in a version modified to have a higher MAX_MAP_GENERATION_LIMIT, visiting the place at the edge of the map, saving the world, then opening that world with the vanilla version. There are other ways (that could be done in vanilla), but if you can not figure them out yourself, it does not matter for reproduction of this bug.

**Comment by NathanSalapat** [comment]
> @NathanSalapat the probably easiest way to get Minetest to show the normally invisible outer mapblock would be to generate a world in a version modified to have a higher MAX_MAP_GENERATION_LIMIT, visiting the place at the edge of the map, saving the world, then opening that world with the vanilla version. There are other ways (that could be done in vanilla), but if you can not figure them out yourself, it does not matter for reproduction of this bug.

So the reproduction steps you gave don't actually work, good to know. >.<
shooting yourself in the foot with this aren't you. If this isn't an issue unless you do stupid stuff you shouldn't be doing in the first place I don't see why you are reporting it. Shouldn't bug reports only be for bugs of the stable or dev codebase, not bug reports of a different (modified) codebase.

**Comment by erlehmann** [comment]
> So the reproduction steps you gave don't actually work, good to know. >.<

That is not true. My reproduction instructions were:

> 1. Make a minetest_game TNT node explode at the border of the outermost mapblock (e.g. where x is >31000).

This crashes vanilla Minetest. Using a modified version was a suggestion I made to that people can see what is going on, as a vast majority of players & developers assert that if they can not see a node, it does not exist.

> If this isn't an issue unless you do stupid stuff you shouldn't be doing in the first place I don't see why you are reporting it.

There exist people that are called “griefers” wo love to do “stupid stuff you shouldn't be doing in the first place” if that means they can crash some other peoples servers.

> Shouldn't bug reports only be for bugs of the stable or dev codebase, not bug reports of a different (modified) codebase.

This bug report is for the vanilla Minetest version with a MAX_MAP_GENERATION_LIMIT of 31000. Please read this discussion and, if you can spare the time, the code dealing with map boundaries and sector creation carefully before asserting again that the crash is a non-issue.

**Comment by erlehmann** [comment]
Just for reference, a way to reproduce this was:

1. Get a world in which the outermost mapblock is visible on the client, so you can see what you are doing. The easiest way is to compile Minetest with a much larger `MAX_MAP_GENERATION_LIMIT` than usual, then go a bit over the normal bounds, then load that World with a vanilla Minetest client and go to the same spot.

2. Make a `minetest_game` TNT node explode at the border of the outermost mapblock (e.g. where x is >31007).

IIRC the modified Minetest client is only necessary so you can see what you are doing on the client – as clients can interact with invisible mapblocks, but never see the results … so any 100% vanilla reproduction would be both difficult to pull off and harder to believe for many.

**Comment by Zughy** [comment]
> The easiest way is to compile Minetest with a much larger MAX_MAP_GENERATION_LIMIT than usual

Such as? Please be more specific, I don't want to spend time trying to guess what number is high enough

**Comment by erlehmann** [comment]
@Zughy I remember building Minetest using a `MAX_MAP_GENERATION_LIMIT` of 32000, exploring from (x=30000,y=0,z=0) outwards in the x+ direction until at least two mapblocks over the original limit of the visible map, then loaded that world in the regular client. You were correct btw – I should have specified the value to make this easier to reproduce.

@NathanSalapat to clarify: When people talk about the map border, they usually talk about the boundary where the map becomes invisible. The outermost mapblock is usually invisible on the client, which means that the *real* end of the map is a bit further out. It is possible to interact with this invisible mapblock for a client the same way they can interact with any other part of the world that is unloaded on the client, i.e. it is difficult, but possible.

This crash concerns the boundary between that usually-invisible part of the world and the not-world void beyond. By using a modified client, you can get direct access to the boundary and crash the game (probably in many other ways than the one I reported here).

**Comment by Zughy** [comment]
Trying to understand these instructions yet again is giving me a headache. Closing as invalid, if anyone wants to create a new issue with clear and simple instructions, be my guest
