### ISSUE TITLE
Node burning handler that does not delete node lags server, produces 2.5MB logs / second

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11839]
##### Minetest version
commit 1dc1305

##### Summary
A user can trivially goad Minetest into creating an entity in a part of the map that lies over the maximum mapgen limit (31000). In that case, Minetest will complain about that entity with 2.5 Megabytes of log messages per second, but apparently not remove it (?).

This is how I filled up storage here: https://github.com/minetest/minetest/issues/11836

More seriously, the server being occupied with logging stuff seems to lag it so hard that in minetest_game sand does not even fall down anymore and the map generator seems to stop working (though that may have been due to the disk filling up).

Having 2.5MB of this message is totally unnecessary:
```
2021-12-05 21:51:52: WARNING[Server]: Server::ActiveObjectMgr::addActiveObjectRaw(): object position (310020,50,720) outside maximum range
```

I suggest to complain a little bit less than 18140 times per second about OOB entities. If the server log less often, it will also have time for other things, like making sand fall or generating the map or whatever else.

##### Steps to reproduce
I do not want to give any reproduction steps, for the same reasons I have listed already in https://github.com/minetest/minetest/issues/11835 – this bug is *way* too easy to abuse and can most likely be fixed without reproducing the condition.

##### Advice
Since entities can already exist in the space exceeding 31000 (the code does its best to try to have them not be created there, but moving entities there is legal and IMO it has to stay that way to not introduce new bugs), it might be wise to not complain about creating entities there. I suspect they will be gone eventually as they usually can not be saved in the map out there anyway.

**Comment by sfan5** [comment]
The engine correctly deletes objects that are spawned outside bounds, I have verified this.
Lacking reproduction instructions I can only assume you managed to trigger a situation where mod tries to recreate the same entity 18140 times per second. This would be a mod bug.

**Comment by erlehmann** [comment]
> Lacking reproduction instructions I can only assume you managed to trigger a situation where mod tries to recreate the same entity 18140 times per second. This would be a mod bug.

You seem to be right: In this case the problem happens with the mod `tnt_revamped`. The code that ignites burning TNT only removes a TNT node if it can create an entity … since nodes can exist past x=31000, but entities can not be created there, the `on_burn` handler is called way too much.

I expect other burning nodes to have similar issues in areas where you can have nodes but can not have entities. IMO the areas should align to prevent such bugs, i.e. entities must be allowed to spawn wherever nodes can exist, not only up until x=31000.

**Comment by erlehmann** [comment]
I have tried reproducing this with @sfan5's own nuke mod and that mod does not enable players to lag the server.

However, I think it is still not a good idea to let a single mod lag a server. Logging should be ratelimited.

**Comment by Zughy** [comment]
As privately agreed with the author who stated that this specific thing cannot happen again, I'm closing the issue

**Comment by erlehmann** [comment]
To add something: I think this thing can not happen again with default settings since #11866. For it to happen, a node must be able to exist outside of mapgen limits, which is only possible if the outermost mapblock goes partially over the mapgen limit. As players or mods or games can changes the chunksize, this thing could happen again, but with the exception of MineClone5 I do not know any game or mod that does that – and MineClone5 is not affected by this issue AFAIK.
