### ISSUE TITLE
It's possible to freeze the server if you start raycast with coords out of the map

### ISSUE THREAD

**Issue by savilli** [minetest/minetest#11830]
##### Minetest version
```
5.5.0-dev-80c3c7e64
```

##### OS / Hardware
Operating system: Linux Ubuntu 20.10
CPU: Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz

##### Summary
Raycast code doesn't have any boundary checks and doesn't handle s16 overflow so it's possible to hang up the server for example there https://github.com/minetest/minetest/blob/80c3c7e642749f9316a3eee2c235df3ce8be1666/src/environment.cpp#L173 with `new_nodes.MinEdge.X = new_nodes.MaxEdge.X = 32767`.

##### Steps to reproduce
- Create a mod with this code:
```lua
minetest.register_chatcommand("raycast", {
	func = function()
		local pos1 = {x=-32767, y=0, z=0}
		local pos2 = {x=-32768, y=0, z=0}
		local ray = minetest.raycast(pos1, pos2, true, true)
		ray:next()
	end
})
```
- Join the server
- Run /raycast command
- Watch how the server stops responding
- Listen to "Where is my mind"

**Comment by erlehmann** [comment]
Note to devs / griefers: Relevant items to induce this crash are things similar to MCL2 arrows, bows, buckets.

I would guess a lot of the following code is affected: https://github.com/search?q=minetest.raycast&type=code
