### ISSUE TITLE
It is possible to fill server storage through debug.txt

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11836]
##### Minetest version
commit 1dc1305

##### Summary
Some bugs make Minetest repeat the same message so often that it is possible to run out of storage space.

##### Steps to reproduce
https://github.com/minetest/minetest/issues/10769 is a particularly useful example, though I actually encountered this bug debugging a thing that was a lot less spammy.

**Edit:** I have found a simple method to spam server logs using a repeated message that can probably be done easily by unprivileged payers, but I need to figure out why it happens.

**Comment by sfan5** [comment]
This simply a side effect of logging. Not a bug.
Administering the Linux/Windows/whatever system MT runs on is the owners responsibility.

**Comment by erlehmann** [comment]
You probably have no idea how bad this can get. Please reopen.

**Comment by tuedel** [comment]
Just use `--logfile ''` to disable logging to a file, log output will still be written to stdout and can be filtered however you see fit.
