### ISSUE TITLE
`get_bone_position` changes bone position if it wasn't previously set

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11840]
Reported by fatalerror420 on Discord:
![bug](https://user-images.githubusercontent.com/34514239/144766411-6a2fde63-e94e-4391-91f7-6a945bdc56c3.png)

##### Minetest version
`5.4.1`

##### Summary
Title says it all. `get_bone_position` doesn't seem to handle the case where there is no corresponding map entry properly (is this undefined behavior?).

##### Steps to reproduce
```lua
minetest.register_on_joinplayer(function(player)
  player:get_bone_position("Arm_Right")
end)
```
in MTG; no playeranim mod may be enabled.

**Comment by sfan5** [comment]
It's perfectly defined behavior, just wrong: https://github.com/minetest/minetest/blob/ff934d538c00518476c31f5df6ebc4be5ca79591/src/server/unit_sao.cpp#L85-L89
