### ISSUE TITLE
When installing mods from contentdb while /tmp is full, error message is not helpful

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11842]
##### Minetest version
Commit 80d12dbe

##### OS / Hardware
Operating system: Debian GNU/Linux

##### Summary
The error message claims that the downloaded zip file is corrupt, which may be correct.

However, the actionable information is that there is too little storage space available on `/tmp`.

##### Steps to reproduce
1. Install something from contentdb while `/tmp` has too little space for the downloaded file.

**Comment by rollerozxa** [comment]
tmpfs can't run out of space, it just makes room for it by writing over the oldest created files since it's not meant for permanent storage.

**Comment by erlehmann** [comment]
@rollerozxa might be, but my `/tmp` is an ext4 filesystem in an encrypted LVM.

**Comment by neoh4x0r** [comment]
@rollerozxa /tmp is not a tmpfs filesystem 

@erlehmann How much space is being used on your llvm partition?

```bash
$ df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1       428G  288G  119G  71% /

$ sudo df -h | egrep "Filesystem|^tmpfs"
Filesystem                                     Size  Used Avail Use% Mounted on
tmpfs                                          1.6G   11M  1.6G   1% /run
tmpfs                                          7.8G  448M  7.4G   6% /dev/shm
tmpfs                                          5.0M  8.0K  5.0M   1% /run/lock
tmpfs                                          4.0M     0  4.0M   0% /sys/fs/cgroup
tmpfs                                          1.6G  272K  1.6G   1% /run/user/1000

```

**Comment by erlehmann** [comment]
@neoh4x0r wHat is a “llvm partition?”

**Comment by neoh4x0r** [comment]
> @neoh4x0r wHat is a “llvm partition?”

> @rollerozxa might be, but my `/tmp` is an ext4 filesystem in an encrypted LVM.

LLVM should have been LVM partition -- this is your main drive.

**Comment by rollerozxa** [comment]
> @rollerozxa /tmp is not a tmpfs filesystem
Every Linux distribution I've installed has had /tmp mounted as tmpfs without any additional configuration. Why a Linux distribution wouldn't do this is beyond me (offloads disk I/O and improves performance, permanent storage isn't needed anyways for **temporary** files).

**Comment by neoh4x0r** [comment]
> > @rollerozxa /tmp is not a tmpfs filesystem
> 
> Every Linux distribution I've installed has had /tmp mounted as tmpfs without any additional configuration. Why a Linux distribution wouldn't do this is beyond me (offloads disk I/O and improves performance, permanent storage isn't needed anyways for **temporary** files).

I'm not sure what other distros do (and yes /tmp can be mounted as tmpfs, or even moved to another partition of drive).
Howevr, this debian mailing list (from 2012) has some more information.
https://lists.debian.org/debian-devel/2012/06/msg00311.html
Also refer to here: https://rwmj.wordpress.com/2012/09/12/tmpfs-considered-harmful/

Per that mailing list titled: **Summary: Moving /tmp to tmpfs makes it useless**
The belief is that it could be a useful hack in some cases, but could cause more problems than it solves to do it by default (and therefore, it's not done in Debian by default)

@erlehmann I recommend checking how much free space you have your hard drive and then either (1) cleanup files, etc to recover space or (2) buy a drive with more capacity.

IMHO: There isn't really anything that can be done in minetest to fix or address a system that is running out of available space.

**Comment by erlehmann** [comment]
> IMHO: There isn't really anything that can be done in minetest to fix or address a system that is running out of available space.

I was complaining in particular that the error message does not point this out.

**Comment by neoh4x0r** [comment]
> > IMHO: There isn't really anything that can be done in minetest to fix or address a system that is running out of available space.
> 
> I was complaining that the error message does not point this out.

Yeah I got as much.

But.,...Are you actually running out of space ?

If you are not running out space (eg. do a $ df -h) -- then reporting a "low disk" error would be a red-herring (and the real problem is something else).

Moreover, the operating system (Debian) should be reporting low disk space usage (letting you know of the issue).
