### ISSUE TITLE
Changing font paths during runtime causes a SEGFAULT

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11864]
##### Minetest version
```
5.4.1
```
##### Summary
Minetest SEGFAULTs if you change it's font settings during runtime. I stumbled upon this while trying to make my font changing less invasive (ideally cleaning itself up right after Minetest has read the font, so right on_mods_loaded).

##### Steps to reproduce
```lua
local function reset_font_settings()
	minetest.settings:set("font_path", "")
	minetest.settings:set("mono_font_path", "")
end
minetest.after(1, reset_font_settings)
```
##### Side notes
Don't take the ability to hackily set fonts away from modders as long as there is no alternative.

**Comment by yamanq** [comment]
This could be related to #4532. I get the same strange behavior as this when testing this bug: https://github.com/minetest/minetest/issues/4532#issuecomment-248175037
