### ISSUE TITLE
Minetest.net is blocked!

### ISSUE THREAD

**Issue by ViofLe** [minetest/minetest#11861]
Minetest.net is blocked on my computer and I can't get the github installation to work. Please help!
I'm on windows 10 and I use opera gx, if that helps.

**Comment by rubenwardy** [comment]
The website just links to builds on GitHub, found here: https://github.com/minetest/minetest/releases/tag/5.4.1

It's not our responsibility to help you work around school/parent/government restrictions though. Consider talking about it to your teachers/parents
