### ISSUE TITLE
allow games to set backend to dummy

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest#11883]
## Problem

allow games to set the backend to dummy from game.conf. this is useful for games that dont need to save the map and allows games to do it much cleaner than they already do (see alternatives)

## Solutions

allow games to set the backend to dummy from game.conf.

## Alternatives

change the backend on first player join and restart the server like https://github.com/AFCMS/Subway-Miner/blob/0950b4cc038c304ab874287b7d366df886868e57/mods/sm_game/init.lua#L47 does

## Additional context

core dev views: sfan5 on irc has agreed that it has a use https://irc.minetest.net/minetest-dev/2021-11-24#i_5901174 as well as warr1024 on discord

**Comment by Warr1024** [comment]
The 2021 game jam has revealed a lot of demand for this kind of feature, and it would enable expanding MT's horizons into different kinds of games.  We've already seen some use of this for e.g. CTF, but we now see some significant use-cases for singleplayer, and especially for mobile users, where it's impractical to expect a user to set this up themselves, hacks around it are really fragile and ruin the user experience, and the consequences of not using it may be significant (storage on mobile may be limited, slow, and hard to manage).

**Comment by sfan5** [comment]
As an addition to this I can also imagine a setting that says "this game does not need a persistent world".
The mainmenu would hide the entire world stuff and just plaster a big start game button.

**Comment by lhofhansl** [comment]
Related to: #7544 . Would be nice to have these work together.

**Comment by wsor4035** [comment]
bumping this since its currently the next game jam and was brought up again as a nice to have

**Comment by SmallJoker** [comment]
> The mainmenu would hide the entire world stuff and just plaster a big start game button.

I believe that should be a separate setting. Games might still need some persistent stuff, such as player metadata or inventory. The current method of creating separate worlds works well enough because the game progress can be backed up or deleted easily.
