### ISSUE TITLE
Improve main menu gamebar scrolling

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#11886]
## Problem
Right now when you want to scroll through the list of games in the Minetest main menu you need to repeatedly click the left or right arrow, moving at one game per click. This quickly becomes extremely frustrating if you have many games installed.

## Solutions
Make it faster to scroll through the list, to which I can find two options:
1. Preferrably it would be through scrolling with the mouse while being over the list, but this would require a lot more effort as I don't know if formspecs is able to intercept this kind of input.
2. Make it scrollable at 10 games per click. This would turn it more into pages of games, as games are shown 10 at once, and is probably the easier option to implement. ([I have a personal patch](https://github.com/rollerozxa/minetest-rollerozxa/blob/master/faster_gamebar_pagination.patch) that does this, but it might be considered too hacky due to the fact FSTK buttonbars can have different sizes and the patch would mess up those)

## Alternatives
Main menu revamp I guess? Although there really needs to be stop-gap fixes to the current one as the main menu revamp is still a far way into the future.

## Additional context
Currently there are about 80 games total on ContentDB. If you were to install all of them and wanted to scroll to the last one, it would require 70(?) clicks to get to it. If option 2 were to be implemented, it would only require 7 clicks.

**Comment by appgurueu** [comment]
May I propose a third solution:
3. Use the newly added [scroll container](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2358)

**Comment by Wuzzy2** [comment]
I did a simple PR to "scroll" a whole "page" per click a while ago, thus solving the issue, but sadly it was rejected. :-(

#10549
