### ISSUE TITLE
Either save mapgen choice per-game or not at all

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#11880]
##### Steps to reproduce
1. Play a game that only allows `singlenode` mapgen (e.g. because it's a minigame)
2. Go back to MTG
3. Create a new world, mapgen is now set to singlenode
4. The newly created world is now "broken", the average user will never figure this out (= **awful UX**)

##### Suggested solution
The mapgen choice could be saved per game *or* simply not at all.
If saving the current choice is considered important this situation could also be alleviated by discarding the choice only when the set of supported mapgens changes.

**Comment by wsor4035** [comment]
> The mapgen choice could be saved per game or simply not at all.

i dont mind either of these, however i agree the current behavior is terrible. also to note that seed numbers are saved across the board (perhaps something people want to change between games, mapgens, etc)

**Comment by lhofhansl** [comment]
I'd say whatever is more expedient - which seems to be not saving the mapgen at all.
On the other hand now a user has to set the preferred mapgen every single time.

**Comment by sfan5** [comment]
Added the fix for this (not saving the mapgen choice) to #11887.

> On the other hand now a user has to set the preferred mapgen every single time.

The way I implemented is so that the user can still set `mg_name` and various other settings in their config and have those selected by default in the creation dialog.
