### ISSUE TITLE
Make get_sky consistent with set_sky

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11890]
## Problem

As for now, the non deprecated `set_sky(...)` asks for a table containing the following optional fields:
- base colour
- sky colour
- type
- textures
- clouds

I expect `get_sky()` to return the same table, but it doesn't. Actually, it doesn't even return a table but a series of values. Namely:
- a table (base colour)
- a string (type)
- another table (textures, in case `type == "skybox"`) 
- and a boolean (clouds)
 
Relevant code:
https://github.com/minetest/minetest/blob/0c4929f0252811d9715b96379973929053d32ef0/src/script/lua_api/l_object.cpp#L1871-L1893

(or to test, just do `minetest.chat_send_player(p_name, dump(player:get_sky()))` and see it crash).

Also, if you've noticed, sky colour is missing from the values returned by `get_sky()`. In fact, there is a separate function for that, called `get_sky_color()`. [Me](https://www.pngkey.com/png/detail/905-9053332_confusedguyvine-meme-vine-ripvine-questionmark-confused-confused-nick.png)

## Solutions
Make `get_sky()` exactly return what `set_sky()` asks for, and remove `get_sky_color()`. If this is a problem of keeping the now deprecated old implementation alive, a couple options:
- `get_sky(as_table)` (default false)
- find another name
- just break the old implementation

I'm personally a fan of the last one, as the name fits perfectly and I don't think that, because of an uncompleted previous implementation, the new one should suffer

**Comment by sfan5** [comment]
Just breaking the API is not an option.
Adding the table variant would have been a good idea when the sky changes were made but nobody thought of it.

I suggest doing the following:
* add the proposed `table` parameter
* deprecate the redundant `get_sky_color`
