### ISSUE TITLE
Reshowing a formspec immediately in on_receive_fields doesn't work

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11898]
##### Minetest version
```
5.4.1
```

##### Summary
A formspec with an exit (image) button will submit it's field if said button is pressed. Attempting to reshow the formspec using the same in `minetest.show_formspec` will silently fail; no formspec will be shown. As a workaround, the "reshowing" can be delayed with `minetest.after` - opening up the possibility of rat races; another workaround is to turn the button into a non-closing button, manually closing the formspec in `on_receive_fields`.

**Comment by v-rob** [comment]
Closing since #11907 is more general.
