### ISSUE TITLE
FPS is consistently below fps_max even when drawtime is well below the limit

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#11891]
##### Minetest version

```
Minetest 5.4.1 (Windows)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel Core i7-9700 Pro

GPU model: NVIDIA GeForce RTX 2070
OpenGL version: OpenGL 4.6.0

##### Summary

The fps_max setting is inaccurate, and the actual limit seems to depend on how long it takes to draw a frame. A drawtime close to the limit allows rendering FPS to reach values near (but not quite) fps_max. A low drawtime causes FPS to be consistently limited to a value much lower than fps_max (~40 for fps_max = 60, and ~64 for fps_max = 90).

Turning off vertical sync through the Minetest setting does not affect the bug. Turning off vsync in the NVIDIA Control Panel does not have any effect either.

Bug occurs on several Minetest versions on Windows 10.
Bug does not seem to occur in Minetest 5.5.0-dev or 5.4.2 on Ubuntu 21.10 (using OpenGL 4.3).

##### Steps to reproduce

This happens on all singleplayer worlds I tried, and also when hosting on one window and joining 127.0.0.1 in a second window. Joining a server had the same effect. Here is the best way to demonstrate the problem:
1. Join any performance intensive world (lots of mods, nodes with complex meshes, etc.).
2. Walk into a wall so that Minetest renders as little as possible. Drawtime plummets, but FPS is much lower than fps_max.
3. Slowly back away from the wall so that, gradually, more of the performance intensive world is rendered.
4. FPS will increase up until your computer is only just able to render at fps_max. Past that point, the effect will disappear and FPS will decrease as usual.

**Comment by kilbith** [comment]
I can confirm: https://irc.minetest.net/minetest-dev/2021-12-15#i_5909230

**Comment by jordan4ibanez** [comment]
There was a pause thing that had a comment "stop wasting cpu resources when maxing out FPS" or something like that, I don't quite remember. It's in the main loop. I made a build that removed that bit of code which paused the main loop of the game, a literal wait cycle which went against the GL vsync code bit and made it go even slower

**Comment by wadim-al** [comment]
I can reproduce this too, so please remove the 'Unconfirmed bug' tag.

The only way to play with near 60 FPS is to enable vsync in Nvidia control panel, disable vsync in the game, then set the fps_max>90 (All Settings, ingame). This doesn't give the stable 60 FPS. Settings for 90, 120, 144 Hz monitors should be adjusted higher.

Different settings test results were:
With fps_max=60 the top left white FPS counter shows 35 FPS, while the bottom left red graph shows 62.5 FPS.
With fps_max=99 the top left white FPS counter shows 55-59 FPS, while the bottom left red graph shows 100 FPS.
With fps_max=99999 the top left white FPS counter shows 57-60 FPS, while the bottom left red graph shows 83.3-143 FPS.

[Video reproduction](https://youtu.be/JZm9e37hvg4)

**Comment by sfan5** [comment]
> Turning off vertical sync through the Minetest setting does not affect the bug.

Note that vsync is turned off by default.
Turning it on can actually *improve* the situation because the fps limiter code should become inactive in that case.
