### ISSUE TITLE
Minetest doesn't update entity selectionbox while selected

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11904]
##### Minetest version

```
5.4.1
```

##### Summary
If the `selectionbox` is changed using `set_properties` while the entity is being pointed at, the change will only be reflected in the displayed selectionbox if the pointed thing is changed. I wonder whether the same applies to nodes as well.

**Comment by SmallJoker** [comment]
Cannot reproduce. Testing code:
```Lua
local function modify(pointed, factor)
	print(dump(pointed))
	if pointed.type ~= "object" then
		return
	end
	minetest.after(2, function()
		local box = pointed.ref:get_properties().selectionbox
		for k, v in ipairs(box) do
			box[k] = v * factor
		end
		pointed.ref:set_properties({
			selectionbox = box
		})
	end)
end

minetest.register_tool(":lab:shrink_grow", {
	description = "Shrin/Grow",
	inventory_image = "default_stick.png",

	on_secondary_use = function(itemstack, placer, pointed_thing)
		return modify(pointed_thing, 2.0)
    end,
	on_use = function(itemstack, user, pointed_thing)
		return modify(pointed_thing, 0.5)
	end,
})
```

**Comment by appgurueu** [comment]
The issue still persists. I've used the same code as Krock to verify this, *except* I haven't used a delay of two seconds: The entity selectionbox must be changed immediately. Enable halo / outline and verify that Minetest *still shows the same* halo/outline *despite* the tool use which has changed the properties. Point away from the entity, point back at it and note that the displayed selectionbox has changed.
