### ISSUE TITLE
Moon texture is upside down

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11901]
##### Minetest version
```
5.4.1
```

##### OS / Hardware

Operating system: Pop!_OS 21.10
CPU: i7 7700

GPU model: GTX 1060
OpenGL version: 4.6.0

##### Summary
Sun rising (about 6:00, ignore the size)
![imagen](https://user-images.githubusercontent.com/63455151/147669788-f8a927f6-536f-4401-846a-6cb6f56c0084.png)

Moon rising (about 20:00, same texture)
![imagen](https://user-images.githubusercontent.com/63455151/147669818-1dca1738-d7b1-4e4b-af04-48b02218bcf1.png)

##### Steps to reproduce
Apply the same texture both to sun and moon. Moon is upside down

**Comment by sfan5** [comment]
Unfortunately we can't just fix this or it'll be broken for everyone else who is already successfully using the moon texture.
The best we can do is document that the texture is upside down (relative to what though?).
(`^[transform2` can rotate your existing texture without needing a new one btw)

**Comment by Zughy** [comment]
I don't agree. If nobody has ever noticed that the moon was upside down (there are no issues in here), is either because they didn't notice - say, they put a symmetrical picture - or because they didn't care enough to open an issue. Either way, saying that it can't be fixed because it's already in a stable release, it's like saying "yes, 2 + 2 should be equal to 4, but it's too late, people can find a workaround to do sums". Also, we're not talking about something that will make game crashes.  

> relative to what though?

To common sense. If the sun rises displaying the "R" in the right order, I expect the rising moon to display the same identical rotation

**Comment by savilli** [comment]
I agree with Zughy. It doesn't make sense to keep backward comparability for a broken feature. Moon and sun should behave the same. If someone workarounded that instead of making an issue, well, shame on them.

**Comment by appgurueu** [comment]
> If someone workarounded that instead of making an issue, well, shame on them.

Shame on Minetest mod development you say?

**Comment by rubenwardy** [comment]
I haven't checked, but I assume that the moon is upside down for half of the transition either way - so it doesn't matter which way around it is. Making it consistent with the sun makes sense

If this isn't true and it's upside down the entire time, then this is an obvious bug

**Comment by Zughy** [comment]
@rubenwardy I confirm your assumption

**Comment by erlehmann** [comment]
> If nobody has ever noticed that the moon was upside down (there are no issues in here), is either because they didn't notice - say, they put a symmetrical picture - or because they didn't care enough to open an issue.

If you look at the several moon phase mods that would be affected by changing this, you can clearly see that multiple mod authors must have noticed this behaviour, but have not necessarily considered it a bug.

@Zughy not only are you the first person complaining about this – multiple people who actually use non-trivial moon textures this did not! See here: https://github.com/minetest/minetest/pull/11902#issuecomment-1007167796

To be clear: I myself would not have filed a bug myself for this if I had noticed, the reason being that at each of sunrise/moonset and sunset/moonrise the moon and sun seem to have the same orientation – if you start a day at sunrise/moonset, it makes perfect sense to have both textures not rotated.

**Comment by appgurueu** [comment]
> @rubenwardy I confirm your assumption

Then this issue is not a bug though.

**Comment by erlehmann** [comment]
> Making it consistent with the sun makes sense

I have written this on dev IRC already, but to spell it out here too:

Consider sun and moon as stickers that you put on the inside of a box in which the player is on opposite ends.

Imagine rotating that box around the player. Surely you see how the current orientation of the moon came to be.
