### ISSUE TITLE
Toggles are triggered periodically on key press

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11900]
##### Minetest version
```
5.4.1
```

##### Summary
Minetest toggle keys trigger the toggle periodically in the client step as the key is held. They should be triggered on key release instead.

##### Steps to reproduce
Hold the camera mode toggle key (usually <kbd>C</kbd>) (**epilepsy warning!**)

**Comment by Zughy** [comment]
I don't think they should work on key release, but the epilepsy effect should be avoided indeed. I suggest avoiding triggering the camera change more than once per key press

**Comment by Zughy** [comment]
I've created a more specific issue: #13868. Closing here
