### ISSUE TITLE
NSSM (and presumable other) models are broken in latest Minetest/Irrlicht

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11908]
##### Minetest version
Latest Trunk

##### OS / Hardware
Operating system: Linux
CPU: Intel

GPU model: NVidia
OpenGL version:

##### Summary
NSSM mobs are displayed completely garbeled.
(I'll attache some images tomorrow)

##### Steps to reproduce
Install NSSM looks at any mobs.

**Comment by sfan5** [comment]
Checked Mobs Redo and nothing is out of the ordinary.
Just a guess, but remember not to update IrrlichtMt without also recompiling MT.

**Comment by lhofhansl** [comment]
Thanks @sfan5 . Compiled both (always do), it's just the NSSM mobs. Haven't had to look what's special about them.

**Comment by lhofhansl** [comment]
Here's a shot of the Icelamander. All NSSM models are equally distorted, looks like the bones are misplaced now. Perhaps some recent Irrlicht changes...? These .x models.

![screenshot_20211230_082435](https://user-images.githubusercontent.com/446130/147769836-fa767c83-f8cc-4c76-9504-d27fb3a13df1.png)

**Comment by lhofhansl** [comment]
Other .x models are fine. Not sure what's wrong about these specific ones (all NSSM models seem to be broken)

**Comment by lhofhansl** [comment]
Rolled back IrrlichtMt to before @hecktest uncoordinated removal of stuff and it works again. I'll try to bisect the commit.

**Comment by lhofhansl** [comment]
See: https://github.com/minetest/irrlicht/issues/88

**Comment by lhofhansl** [comment]
I do not believe that this is fixed completely without the Irrlicht change.

**Comment by lhofhansl** [comment]
Arrghhh. NM, Irrlicht change was merged.
