### ISSUE TITLE
Strange bug in light spreading

### ISSUE THREAD

**Issue by Selat** [minetest/minetest#1190]
![screenshot_212202899](https://cloud.githubusercontent.com/assets/5287334/2564143/14e4a4fa-b897-11e3-9452-781c41684667.png)
You can download world here http://www.filehosting.org/file/details/444029/Test.tar.gz

**Comment by MT-Modder** [comment]
This should be considered a blocker. It looks horrible and is very hard to fix in-game, without worldedit of course. It makes minetest look bad to a first time user.

@RealBadAngel I remember paramat discussing these invisible caves with hmmm in a pull request at some point. I wonder if cave generation could be rewritten to help solve this bug?

**Comment by paramat** [comment]
> afaik those shadows are caused by invisible caves that are generated in the sky...
> and i dont remember that issue being fixed at all.
> so, its mapgen bug not the lighting code.

The screenshot seems to show shadows occuring along a mapchunk edge, the shadow shapes look like the shadows of edges of large caves that extend beyond a mapchunks edge. Sometimes the large caves cause bugs and this my be one of them. Caves are not deliberately generated above ground, there is a lot of code that tries to avoid that, not always successfully. Currently i don't know how to fix these shadows.

**Comment by MT-Modder** [comment]
That's unfortunate. These lighting artifacts make minetest look a bit unpolished.

**Comment by Zeno-** [comment]
These do seem to be more common lately, but I may be imagining it

**Comment by MT-Modder** [comment]
This sorta thing happened to me after mapgen once and it was kinda annoying because it happened right above my farm.

**Comment by paramat** [comment]
Mgv6 does not have a heightmap generated during mapgen, if i add one it would stop large caves being generate above ground, which might fix these shadows, i'll see what i can do.

**Comment by MT-Modder** [comment]
^I hope it works, these shadows are a very old bug.

**Comment by C1ffisme** [comment]
I can still remember this being posted as a bug, and someone thought the sun was casting a shadow. That seems pretty hillarious now. Anyway, I also really hope this gets fixed. Maybe minetest should update nearby chunk's lighting every few minutes? This would fix the problem, maybe...

**Comment by paramat** [comment]
Heightmap will not fix this, i will try reducing the size of large caves so they do not extend beyond the mapchunk borders.

**Comment by Zeno-** [comment]
Why do invisible caves cause lighting bugs anyway? I looked at the lighting code a fair bit when I was optimising it and can't recall anything that would indicate that a cave should cause lighting changes.

**Comment by C1ffisme** [comment]
@Zeno- Yeah, it's like air has a shadow now.

**Comment by MT-Modder** [comment]
@Zeno- I think it's just a theory.

**Comment by paramat** [comment]
Yeah it's weird. These shadows are now very common, possibly due to changes made by hmmmm to lighting code while fixing dark nodes at y = 47. These shadows run along the edges of mapchunks so like floaty dungeons seem to be an overgeneration problem.
Mgv5/v7 have large caves only so might have fewer or no shadow bugs, something to test.
This is a big problem so i will put a lot of work intio this.

**Comment by paramat** [comment]
Possibly realted commits by hmmmm:
https://github.com/minetest/minetest/commit/7233a1228eb161cbcbb46c6e801cabd89ef3d2ab
https://github.com/minetest/minetest/commit/3bdf3df22367ded04e3a0599f85262e3b538e6ac

**Comment by paramat** [comment]
Weird fact: flying up and down above a shadow and watching the lighting of the wieldhand, the dark air always changes to bright air above y = 30.

**Comment by paramat** [comment]
This is the best i can do and seems to work well, comments? https://github.com/minetest/minetest/pull/2410

**Comment by paramat** [comment]
#2410 is now merged, hopefully there will now be far fewer shadow bugs, i couldn't find any during testing, although i expect them to still occasionally appear. Preventing large caves being generated above ground will also improve mapgen speed.

**Comment by paramat** [comment]
No feedback, seems to be successful so closing.

**Comment by MT-Modder** [comment]
I haven't seen these sky shadows ever since the hightmap addition. Thank you so much!
