### ISSUE TITLE
Utilities to return and set every celestial vault settings in one function

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11917]
## Problem
If I want to get every celestial vault element of a player, to know the status of each element, right now I have to do
```lua
local p_cvault = {}

    -- TODO: Minetest ?.?: get_sky() doesn't work properly, instead of being
    -- able to do sky = player:get_sky(), I need to do all this.
    -- Relevant issue: https://github.com/minetest/minetest/issues/11890
    p_cvault.sky = {}
    p_cvault.base_color = (type(get_sky[1]) ~= "table") and get_sky[1] or table.copy(get_sky[1])
    p_cvault.type = get_sky[2]
    p_cvault.sky_color = player:get_sky_color()
    p_cvault.textures = table.copy(get_sky[3])
    p_cvault.clouds = get_sky[4]

    p_cvault.sun = player:get_sun()
    p_cvault.moon = player:get_moon()
    p_cvault.stars = player:get_stars()
    p_cvault.clouds = player:get_clouds()
```

## Solutions
Add a `player:get_celestialvault()` function returning a table containing all the different tables returned by the other functions such as  
`{sky = {...}, sun = {...}, moon = {...}, stars = {...}, clouds = {...}}`  

This could be done either by adding a Lua utility function in the builtin, or by hardcoding it in C++. Core devs choice (if they agree with the whole idea, of course).  

This can also apply to a `player:set_celestialvault()` function, requiring the same table structure.

### Usecase
Usecase: store all the celestial vault elements of a player in a temporary table to later re-apply them (i.e. when entering a minigame)

**Comment by appgurueu** [comment]
Low priority IMO as it can easily be implemented in mods or convenience modding libraries.
