### ISSUE TITLE
Inconsistent transparency in mesh nodes

### ISSUE THREAD

**Issue by aerkiaga** [minetest/minetest#11911]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware

Operating system: Linux Mint 20.2
CPU: AMD Athlon 5350

GPU model: Radeon R3 iGPU
OpenGL version: 4.5, Mesa 21.0.3

##### Summary

Mesh nodes with partially transparent faces are rendered inconsistently. As an example, here's a pair of glass panes from different angles, showing how some faces are only visible from some angles.
![image](https://user-images.githubusercontent.com/38228836/147828984-67bba0ee-bc76-4822-b379-0042e6ef47f7.png)
![image](https://user-images.githubusercontent.com/38228836/147828992-c7c205de-2d97-4a82-8ee9-8fbd9dad49be.png)

##### Steps to reproduce

The images above were taken in Nodeverse at [this commit](https://github.com/aerkiaga/nodeverse/tree/9b517dea99d0029f3f2a2be874c86ca7c01b8c97). The issue doesn't seem to depend on face normals in the model.

**Comment by aerkiaga** [comment]
So, here's a summary of the visual glitches:
| Face perpendicular to | "Outside" towards negative | "Outside" towards positive |
| -------------- | ---------- | ----------- |
| X axis | Blended with faces in front | Obscured by faces in front |
| Y axis | Blended with faces in front | Obscured by faces in front |
| Z axis | Obscured by faces in front | Blended with faces in front |

Node rotations by means of `facedir` seem to preserve blended/obscured faces. For example, a value of 3 reverses the behavior of faces perpendicular to the Z axis, as it moves the +X face to +Z and -X to -Z, while +Z is rotated into -X and -Z into +X, leaving the X faces identical.

**Comment by aerkiaga** [comment]
I'm not entirely sure what the default behavior should be, but it should definitely be the same for all faces. Back-face culling should in principle obscure all those faces by looking at face normals (that's the behavior I'd expect, and the one that is consistent with rendering of other drawtypes), but blending back-faces with front-faces is also a reasonable option if the former is impossible.

Meanwhile, I'll try nodebox drawtype as a workaround.

**Comment by sfan5** [comment]
This is unfortunately a well known problem which is already tracked in issue #95.

**Comment by aerkiaga** [comment]
Using a nodebox instead of a mesh improves the situation, as back-face culling is appropriately done, but yeah, #95 still remains and makes it look glitchy. Should I open a new issue for mesh nodes not getting back-face culling, @sfan5?

**Comment by wsor4035** [comment]
please try out PR https://github.com/minetest/minetest/pull/11696 which was linked to that issue

**Comment by x2048** [comment]
Never tested #11696 with mesh nodes, but technically it should work.

Nodeboxes have been tested and accounted for and are a better choice for primitive shapes.

**Comment by aerkiaga** [comment]
It produces some noticeable visual glitches both with nodeboxes and meshes, but at least in a consistent and non-intrusive way.

**Comment by aerkiaga** [comment]
Here's the nodebox version. While there's only one face separating the left and right arms, two symmetrical faces are drawn (which looks better imo but anyway).
![screenshot_20220101_154644](https://user-images.githubusercontent.com/38228836/147853257-f7f569bc-4cbf-415f-b592-c3385bc5bb16.png)

And here's the mesh version. It doesn't perform back-face culling (at least now it's the same on all faces), and now there's also this weird diagonal artifact separating the two arms (could improve by editing the model?).
![screenshot_20220101_154810](https://user-images.githubusercontent.com/38228836/147853291-71d19743-0a13-45ab-b40a-34b9050de2b8.png)

**Comment by aerkiaga** [comment]
What's the chance of having a drawtype that accepts a `node_box` but discards any duplicated faces plus faces that lie at any ±0.5 coordinate next to a connected node? Something like `glasslike_nodebox`? It would help immensely with glass panes of all sorts...

**Comment by aerkiaga** [comment]
`backface_culling = true` only works partially. A few faces are not culled and new visual glitches appear, but it's mostly consistent.

**Comment by aerkiaga** [comment]
Well, everything renders consistently, so I'd say #11696 should close this.
