### ISSUE TITLE
Custom clouds reset after a short while (but their colours)

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11915]
##### Minetest version

```
5.4.2
```

##### OS / Hardware

Operating system:
CPU: Pop!_OS 21.10

##### Summary
Custom clouds parameters, colours aside, get resetted after a short while

https://user-images.githubusercontent.com/63455151/147849070-8f942f0b-392a-4e7a-8af0-23687260b892.mp4

##### Steps to reproduce
Change one of those parameters on the go

**Comment by sfan5** [comment]
Are you using Minetest Game? The weather mod modifiers density, thickness and speed every 8 seconds.

**Comment by Zughy** [comment]
I had no idea such mod existed. I looked at the code and it's just all about cycling clouds, so `weather` is a bit of a stretch :thinking:  but anyway thanks, closing

**Comment by Sthhjchdhndn** [comment]
> ##### Minetest version
> ```
> 5.4.2
> ```
> 
> ##### OS / Hardware
> Operating system: CPU: Pop!_OS 21.10
> 
> ##### Summary
> Custom clouds parameters, colours aside, get resetted after a short while
> 
>  clouds.mp4 
> ##### Steps to reproduce
> Change one of those parameters on the go
