### ISSUE TITLE
Support keyfile as login method

### ISSUE THREAD

**Issue by mk-pmb** [minetest/minetest#11925]
## Problem

Some people are concerned that there may be servers with players who are incapable of secure-enough password management.

## Solutions

I'd like an easy way for server admins to require using a keyfile in addition to the password.

* Server option `login_keyfile_bytes_min` for the MT server. If it's positive non-zero, server requires keyfile challenge/response auth for login.
  * My gut feeling says that the keyfile should be checked either at the same time as the password or before checking the password.
* CLI option for keyfile path
* Client option `login_keyfile_bytes_min` (explained below)
* Client registration: If a keyfile is required by the server, and no keyfile path was given as CLI option, …
  * The registration confirmation dialog has a section for entering the keyfile path, with a "browse" button that brings up a "Save file as" dialog.
  *  A key file must be selected, and if it does not exist yet, it is created with random bytes, to a length that satisfies
  both the server's and the client's `login_keyfile_bytes_min` option.
  * The registration dialog should explain, with appropriate visibility enhancements, that loss of this file usually means loss of player character and thus game progress.
* All keyfile selection dialogs shall start in the previously used keyfile directory.
  * If that does not exist anymore, start in its closest existing parent directory.
* Client login form: If the client's `login_keyfile_bytes_min` option is positive non-zero, in addition to the password field, a keyfile path field is offered, with a "browse" button that opens an "Open file" dialog.
  * This dialog shall be titled "Select keyfile for (username) @ (host):(port)"
* Client login: If a server requires a keyfile, and it was neither selected by CLI arg nor in the client login dialog, launch the selection dialog as if the login form's keyfile "browse" button were used.

## Alternatives

* People will try all sorts of weird voodoo in desparate hope of making password authentification secure.

**Comment by NathanSalapat** [comment]
While this might sound good in theory, what if somebody wants to play on a server on a second computer, or a mobile device, now they're going to have to copy a keyfile. I don't use mobile at all, but copying a file onto a phone/tablet from a computer is probably far more difficult than it really should be, and would the Android app even be able to read a keyfile with file system restrictions?

**Comment by mk-pmb** [comment]
* For copying (bad solution):
  * You can probably send it by email both ways.
  * For transfer from PC to mobile, we could generate a QR code.
* Better idea though: New keyfile per device, and upon new device login, you must login with an accepted device to authorize the new one.

**Comment by Zughy** [comment]
Asked confirmation to rubenwardy for closing this, he agreed
