### ISSUE TITLE
set_sun/set_moon: setting textures to something and then to their default name again creates dummy broken images

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#11930]
EDIT: I wanted to create a bug report, but I'm stupid

## Problem

(this problem applies to both the celestial bodies, I'll use the sun as an example)
By default, `player:get_sun()` returns a table that contains, among other parameters, `texture = "sun.png"`. If you do something like this, nothing weird happens:

```lua
minetest.register_on_joinplayer(function(player)

    local sun = player:get_sun()
    
    minetest.after(3, function()
        player:set_sun(sun)
    end)
end)
```

However, if you do change the sun texture to something else in between these steps, even with the special empty string `""` (that, according to the documentation, `re-enables the mesh sun`), you'll obtain a dummy image error:

```lua
minetest.register_on_joinplayer(function(player)
       
    local sun = player:get_sun()
    
    minetest.after(1, function()
       player:set_sun({texture=""})
      --player:set_sun({texture="cdb_queued.png"}) pick your favourite
    end)
    
    minetest.after(3, function()
        player:set_sun(sun)
    end)
end)
```
![imagen](https://user-images.githubusercontent.com/63455151/148128097-125e93f9-a8fe-48c8-9b84-8696591b610b.png)

## Solutions

Let passing default parameters such as `texture = "sun.png"` avoid throwing a dummy image because they understand it's the default value, expanding this behaviour to sun and moon tonemap as well.

## Additional Context
This was me trying to bypass this mechanism inside my #11922  PR
![imagen](https://user-images.githubusercontent.com/63455151/148128616-8b0d7958-5616-449a-bfb1-f86b1b11e04f.png)
but it shouldn't be bypassed like that (also because I'm enabling the default mesh moon even if there is a `moon.png` file, so it's just wrong)

**Comment by sfan5** [comment]
The default values are actually just wrong, there is no sun or moon texture shipped with Minetest. That it works when the defaults are left unchanged is by accident.

Apply this:
```diff
diff --git a/doc/lua_api.txt b/doc/lua_api.txt
index 3edfd5bb1..58e91ee6d 100644
--- a/doc/lua_api.txt
+++ b/doc/lua_api.txt
@@ -6852,7 +6852,7 @@ object you are working with still exists.
         * `visible`: Boolean for whether the sun is visible.
             (default: `true`)
         * `texture`: A regular texture for the sun. Setting to `""`
-            will re-enable the mesh sun. (default: `"sun.png"`)
+            will re-enable the mesh sun. (default: `""`)
         * `tonemap`: A 512x1 texture containing the tonemap for the sun
             (default: `"sun_tonemap.png"`)
         * `sunrise`: A regular texture for the sunrise texture.
@@ -6867,7 +6867,7 @@ object you are working with still exists.
         * `visible`: Boolean for whether the moon is visible.
             (default: `true`)
         * `texture`: A regular texture for the moon. Setting to `""`
-            will re-enable the mesh moon. (default: `"moon.png"`)
+            will re-enable the mesh moon. (default: `""`)
         * `tonemap`: A 512x1 texture containing the tonemap for the moon
             (default: `"moon_tonemap.png"`)
         * `scale`: Float controlling the overall size of the moon (default: `1`)
diff --git a/src/skyparams.h b/src/skyparams.h
index 1de494d69..72fe8d818 100644
--- a/src/skyparams.h
+++ b/src/skyparams.h
@@ -92,7 +92,7 @@ class SkyboxDefaults
 		SunParams sun;
 		sun.visible = true;
 		sun.sunrise_visible = true;
-		sun.texture = "sun.png";
+		sun.texture = "";
 		sun.tonemap = "sun_tonemap.png";
 		sun.sunrise = "sunrisebg.png";
 		sun.scale = 1;
@@ -103,7 +103,7 @@ class SkyboxDefaults
 	{
 		MoonParams moon;
 		moon.visible = true;
-		moon.texture = "moon.png";
+		moon.texture = "";
 		moon.tonemap = "moon_tonemap.png";
 		moon.scale = 1;
 		return moon;
```
