### ISSUE TITLE
Android Move to SDcard doesn't work

### ISSUE THREAD

**Issue by Quasic** [minetest/minetest#11949]
##### Minetest version

```
5.4.2 for Android
```

##### OS / Hardware

Operating system: 32-bit Android 10
CPU: arm64

GPU model:
OpenGL version:

##### Summary

Moving to sdcard doesn't appear to work in that it doesn't seem to create a folder on the SD card. I used a new SD card, and after the move, it had <33MB on it, total. Android put some stuff on it, as well, so I don't think it moved much, if anything. I don't really know what the move did. I tried moving it back and to the card again. It changed the reported size of the app a bit each time, but not consistently.

##### Steps to reproduce

Settings > Apps > Minetest > Storage > Change > Move

**Comment by sfan5** [comment]
It's pretty much up to Android where to store app data (even if you tell it to move somewhere else), we *might* be able to influence it a bit, someone will have to re-check the documentation.

**Comment by Zughy** [comment]
@srifqi if you want to take a look at it. I have got no SD Card so I don't even have the "Change" option to verify it (or at least I guess that's the reason why I don't have any "Change" option) 😄

**Comment by Unacceptium** [comment]
> I still do not understand many changes on the newer Android versions. I can move Minetest to SD card on Android 6.0.1 (Samsung Galaxy J7), but I can not move Minetest on Android 13 (Samsung Galaxy A72).
> 
> Android 6.0.1
> Android 13

i am on android 12 and i find the option to enable the change button in Developer Settings. i know its already "can't fix" and you commented years ago but who knows if you figured this out. not sure if it is there on android 13 too.

<img width="720" height="1440" alt="Image" src="https://github.com/user-attachments/assets/fa6ae12a-9ef7-424c-b16d-251d8429738a" />
