### ISSUE TITLE
Awaiting a HTTP callback at load time doesn't work

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11945]
##### Minetest version

```
5.4.1
```

##### Summary
HTTP results can't be awaited at load time. Minetest presumably waits for the server to load because it calls the callbacks.

##### Steps to reproduce
Include the following code in `init.lua` and execute it at load time:
```lua
local completed = false
http.fetch({
	url = "https://example.com",
	timeout = 1,
	method = "GET"
}, function()
	completed = true
end)
repeat until completed -- Busywait
error"yay"
```
The busywait waits forever, as Minetest itself presumably waits on loading to finish.

**Comment by appgurueu** [comment]
Handles seem to work however:
```lua
local handle = http.fetch_async({
	url = "https://example.com",
	timeout = 1,
	method = "GET"
})
repeat
	local result = http.fetch_async_get(handle)
until result
```

**Comment by appgurueu** [comment]
Handles seem to work however:
```lua
local handle = http.fetch_async({
	url = "https://example.com",
	timeout = 1,
	method = "GET"
})
repeat
	local result = http.fetch_async_get(handle)
until result.completed
```

**Comment by rubenwardy** [comment]
This isn't a bug. Lua is single threaded, it's impossible for the callback function to run whilst your lua code (the repeat loop) is running

Additionally, the callback is implemented by checking the handle once per tick

**Comment by appgurueu** [comment]
> This isn't a bug. Lua is single threaded, it's impossible for the callback function to run whilst your lua code (the repeat loop) is running
> 
> Additionally, the callback is implemented by checking the handle once per tick

🤦 you're right, closing this. Shouldn't open issues past midnight.
