### ISSUE TITLE
dynamic_add_media crash provides empty stacktrace

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11947]
##### Minetest version
```
5.5-dev
```
![Bildschirmfoto_von_2022-01-09_17-42-25](https://user-images.githubusercontent.com/34514239/148691933-922f359d-75f6-4846-9d48-3691c20e4ef7.png)

**Comment by sfan5** [comment]
Assuming you set `error` as the callback there is exactly nothing missing. The trace to `dynamic_add_media` will never show up here because the callback happens at a later point.
