### ISSUE TITLE
Add movement acceleration

### ISSUE THREAD

**Issue by Froggo8311** [minetest/minetest#11954]
## Problem
Minetest does not currently have a good movement system. When a player moves, it is often not very fast, and using fast mode can sometimes be *too* fast.

## Solutions
Add slight movement acceleration when a player is moving (i.e. after a few seconds of a player moving, increase the speed slightly). This could also be used to allow players to make "running jumps" to jump slightly farther/higher.

**Comment by Df458** [comment]
I don't think this is something to do on the engine side. Movement speed (including fast mode speed, iirc) is exposed to mods and games, it's up to them to adjust movement speed. In fact, if I understand this request properly the acceleration solution you describe already exists--[in nodecore](https://content.minetest.net/packages/Warr1024/nodecore/).

**Comment by Froggo8311** [comment]
Ah, ok.
