### ISSUE TITLE
Mouse sensitivity, font size, mono font size options

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1196]
These should be added to the options menu, especially the first two ones, for high-resolution screens and some mice.

There is https://github.com/minetest/minetest/pull/844 which does part of this, but it's old.

**Comment by RobertZenz** [comment]
This is kinda part of the new options page...but it gets complicated because of the wish of many to bring back the old page alongside the new one.

**Comment by rubenwardy** [comment]
done in latest MT
