### ISSUE TITLE
`registered_on_placenodes` are called too late to stop falling entities

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11967]
##### Minetest version
```
5.5-dev
```

##### Summary
`minetest.registered_on_placenodes` are called after the node has been placed. It is usually possible to immediately revert the action by placing the old node again. However, if the placed node is a falling one - and if it is placed in air - a falling node entity will be spawned before the `registered_on_placenodes` callbacks get called, making it almost impossible to revert the action without relying on massive hacks.

Possible solutions:
1. Wait with spawning the entity until after `registered_on_placenodes` have been run;
2. Introduce another global callback that is called before the node has been placed

##### Steps to reproduce
```lua
minetest.register_on_placenode(function(pos, newnode, placer, oldnode, itemstack, pointed_thing)
	minetest.set_node(pos, oldnode)
	return true
end)
```

**Comment by sfan5** [comment]
The correct way to prevent node placement is via `<def>.on_place`, there is no global callback for this.
Regardless this happening with on_placenode is not a defect.

**Comment by erlehmann** [comment]
I also think that “reverting the action by placing the old node again” seems like needless busywork.

@appgurueu in which games or mods did this constitute a problem for you so far?

**Comment by appgurueu** [comment]
> I also think that “reverting the action by placing the old node again” seems like needless busywork.
> 
> @appgurueu in which games or mods did this constitute a problem for you so far?

See the linked MTG issue, https://github.com/minetest/minetest_game/issues/2786.
