### ISSUE TITLE
Noiseparams returned to Lua contain some numbers as strings.

### ISSUE THREAD

**Issue by Gael-de-Sailly** [minetest/minetest#11962]
##### Minetest version
Latest
```
5.5.0-dev-7c93b2d7a
```
##### Summary

Noise parameters returned by `minetest.get_mapgen_setting_noiseparams` and `Settings:get_np_group` contain some parameters as string and some others as numbers (only `octaves` and `seed`). Functions taking noise params as input seem to accept string values, but it gets confusing when doing math in Lua with these noiseparams.

The obvious way to workaround it is using `tonumber`, but the fact that this is needed is not documented anywhere (afaik?), and is not logically expected.

This string format has been introduced by a1e1a19 to fix issues in advanced settings formspecs (which need strings) but I consider it's the job of the settings tab to convert to string what it needs, and this should not surface to the modding API.

[c_content.cpp L1697-1719](https://github.com/minetest/minetest/blob/f66ed2c/src/script/common/c_content.cpp#L1697-L1719)

##### Steps to reproduce

```lua
local np_heat = minetest.get_mapgen_setting_noiseparams("mg_biome_np_heat")

local jsonstr = minetest.write_json(np_heat, true)
print(jsonstr)
```

Output in my case:
```json
{
   "flags" : "defaults",
   "lacunarity" : "2",
   "octaves" : 3,
   "offset" : "50",
   "persistence" : "0.5",
   "scale" : "50",
   "seed" : 5349,
   "spread" : {
      "x" : "1000",
      "y" : "1000",
      "z" : "1000"
   }
}
```

**Comment by erlehmann** [comment]
I believe that having stringly typed numbers could be important when a system does not have a proper data type for a number (like an integer type for an integer) by only an improper one (like a double type for an integer).

For example, it makes sense to have numbers in JSON be stringly typed, because JSON floating point numbers can lose precision: https://www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues

**Comment by Gael-de-Sailly** [comment]
Noise params are not represented by strings internally, only integers and 32-bit floats ([`NoiseParams` definition](https://github.com/minetest/minetest/blob/f66ed2c/src/noise.h#L110-L118)), and they are converted to string only when returned to Lua (in [`c_content.cpp`](https://github.com/minetest/minetest/blob/f66ed2c/src/script/common/c_content.cpp#L1697-L1719)). This leads to repeated conversions.

What happens when running this code, for example:
```lua
local np_heat = minetest.get_mapgen_setting_noiseparams("mg_biome_np_heat")
local nobj_heat = minetest.get_perlin_map(np_heat, {x=80, y=80, z=80})
```
1. Mapgen noise params are loaded from settings files beforehand, converting string to floats.
2. At line 1, floats are converted to strings before returning to Lua
3. At line 2, strings are converted back to floats when building the `PerlinNoise` object.

So we have 3 conversions where we only need one, and Lua manipulates strings instead of numbers, which is not expected and should at least be documented.

The usefulness of this conversion before returning to Lua is that the core can properly serialize its 32-bit floats with the appropriate precision, whereas Lua use 64-bit floats and would try (using basic `tostring` or string concatenation) to serialize it with an excessive precision. But I think this could be improved on Lua side, from my tests `string.format("%.7g", n)` does a great job serializing numbers that come from 32-bit floats to a human-readable form.

**Comment by appgurueu** [comment]
Oof, I guess said revert never happened: https://github.com/minetest/minetest/commit/a1e1a19ac355dbe7e1a2e060fd6b5fe082298eb6#r25125537
