### ISSUE TITLE
LuaEntitySAO::setHP doesn't check whether an entity should die

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#11975]
##### Minetest version

```
42839fa1db85ab6ce61c5a185f91919a5a9c067c
```

##### OS / Hardware

Operating system: Fedora Linux 35 (Workstation Edition) 
CPU: Intel® Core™ i7-4790K CPU @ 4.00GHz × 8 
(but I don't think this matters)

##### Summary

[LuaEntitySAO::setHP](https://github.com/minetest/minetest/blob/42839fa1db85ab6ce61c5a185f91919a5a9c067c/src/server/luaentity_sao.cpp#L402) doesn't check whether an entity should die. Only [LuaEntitySAO::punch](https://github.com/minetest/minetest/blob/42839fa1db85ab6ce61c5a185f91919a5a9c067c/src/server/luaentity_sao.cpp#L308) [does](https://github.com/minetest/minetest/blob/42839fa1db85ab6ce61c5a185f91919a5a9c067c/src/server/luaentity_sao.cpp#L346). So if you do `set_hp(0)` on an entity, it doesn't die.

##### Steps to reproduce

Try the following entity:

``` Lua
minetest.register_entity("test:test", {
    on_activate = function(self)
        self.object:set_hp(0)
    end,
})
```
It should die and be removed instantly.

**Comment by SmallJoker** [comment]
It might make sense to overwrite `virtual void removingFromEnvironment` to deal with the "dead" case there so that it's removed inside the ordinary object cleanup cycle (`ServerEnvironment::removeRemovedObjects()`)
