### ISSUE TITLE
Fall damage is based on vertical and horizontal speed

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#11974]
##### Minetest version
```
5.5-dev
```
##### Summary
Fall damage calculation takes into account horizontal speed. This is especially noticeable if going at high speeds and then falling. First hitting a vertical plane to get rid of vertical speed will drastically reduce fall damage. I believe fall damage should only take into account the vertical component.

##### Steps to reproduce
Enable "fast". Fall only the minimum height required for fall damage to appear. Note that fall damage is significantly increased if you're moving at high speeds vs. if you're not moving at all.

**Comment by lhofhansl** [comment]
I have observed that as well.
Physically the overall speed is what causes the impact upon collision, so from that angle this is correct.
In Minetest is might counter-intuitive.

**Comment by appgurueu** [comment]
> I have observed that as well. Physically the overall speed is what causes the impact upon collision, so from that angle this is correct. In Minetest is might counter-intuitive.

By this logic however, fall damage should also be applied when colliding vertically (i.e. not falling). What I take issue with is the following:

- If the player first collides with a XZ plane with XZ speed, their Y speed will be zeroed. If the player then collides with a XY or YZ plane, their X or Z speed will  be zeroed.
- If the player however first collides with a XY and/or YZ plane, their X and/or Y speed will be zeroed. If they then collide with a XZ plane, their Y speed will be zeroed. They will take less fall damage.

**Comment by buckket** [comment]
> I have observed that as well. Physically the overall speed is what causes the impact upon collision, so from that angle this is correct. In Minetest is might counter-intuitive.

Not correct. Athletes doing ski jumping are doing just fine with landing velocities that would be fatal in a frontal car crash. ;)

**Comment by SmallJoker** [comment]
The code tells other stories. Fall damage is only based on the Y component. The `v3f` vector is overkill for what it's used for, but in terms of functionality it does not matter.

https://github.com/minetest/minetest/blob/c31b3017222edd6e93bdeb02f05a3df7b6b23a1a/src/client/clientenvironment.cpp#L264-L279

**Comment by appgurueu** [comment]
The code does indeed remove those components. I've tried to reproduce this and I couldn't, so I'm closing this. I (seriously) assume the "feeling" that XZ components are taken into account is [just an illusion](https://www.youtube.com/watch?v=Vz5PDUVqY9M). Perhaps there is just a correlation because you're more likely to slip at higher XZ speeds.
