### ISSUE TITLE
Artifact at the border of artifical and sunlight with dynamic shadows.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#11977]
##### Minetest version
Latest master

##### OS / Hardware
CPU: Intel

GPU model: NVidia (does not happen with Intel Iris)

##### Summary
See screenshot
![screenshot_20220120_093032](https://user-images.githubusercontent.com/446130/150391397-51b37fe6-e278-4cf5-8791-31a7498f4075.png)

See the square artifact around the torch. What makes this annoying is that these are not affected by fog.

##### Steps to reproduce
Enable dynamic shadows
Just place a torch on a flat piece of earth. It easier to see when the ground is bright (i.e. sand)

@x2048 FYI, in case you have some spare cycles.

**Comment by lhofhansl** [comment]
Tracked it down to this: https://github.com/minetest/minetest/blob/master/client/shaders/nodes_shader/opengl_fragment.glsl#L515

If I add a clamp there, the artifact goes away. The clamp is not needed mathematically. Even `clamp(..., -1000, 1000)` fixes the problem. This seems to be a problem in NVidia's driver.

**Comment by grorp** [comment]
I'm having the same issue on my NVIDIA GPU, but I didn't try it with Intel.

**Comment by x2048** [comment]
Tested on Intel HD 4000. No border.

**Comment by x2048** [comment]
@lhofhansl Works with `pow(max(0, nightRatio), 0.6)` and `pow(nightRatio + 1e-3, 0.6)` on AMD.

I suspect, nightRatio is occasionally interpolated to small negative values during tesselation, which causes pow() to blow up. Looks like Intel prefers correctness over performance....

`clamp(..., 1.0, 100000000)` works on my AMD. This might be a driver/vendor-specific problem.

I would go for `max()` solution unless we are fighting for cycles in the shaders.
