### ISSUE TITLE
First-person camera is located inside player head on MNT Reform 2

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11987]
##### Minetest version
Unclear. I encountered this bug with whatever was on the master branch around 2021-12-30.

I do not have access to an MNT Reform 2 laptop right now, so I can not look up the commit.

##### OS / Hardware
Operating system: Debian GNU/Linux Sid
CPU: i.MX8MQ (Cortex-A53)

GPU model: Vivante GC7000
OpenGL version: opengl 2.1, mesa 21.2.0

##### Summary
When starting Minetest with minetest_game on the MNT Reform 2 laptop, the camera is inside the player head.

This makes Minetest basically unplayable in first-person mode, as players can not see the world very well.

##### Steps to reproduce
1. Start Minetest on the MNT Reform 2 laptop.
2. Enter a world with minetest_game.

##### Screenshots

![minetest-on-mnt-reform-fail-1](https://user-images.githubusercontent.com/60905/150857385-8dfbcc19-61e0-4286-a521-b49105cf6c3b.png)

![minetest-on-mnt-reform-fail-2](https://user-images.githubusercontent.com/60905/150857503-73fc0ddc-b93f-463d-a5c6-03c0681d0372.png)

**Comment by erlehmann** [comment]
According to @mntmn, Minetest 5.3.0 did not have this bug.

**Comment by NathanSalapat** [comment]
Possibly related. #11790 Not sure if these screenshots were taken with the Direct3D renderer.

**Comment by erlehmann** [comment]
I am pretty sure that these screenshots were taken with the OpenGL renderer.

**Comment by erlehmann** [comment]
The incredibly hacky workaround adopted for the MNT Reform 2 system image is now to make the player texture transparent. Does anyone have better ideas?

https://source.mnt.re/reform/reform-system-image/-/blob/sysimage-v3/reform2-imx8mq/mkuserland3.sh#L54

**Comment by Df458** [comment]
If I had to wager, the reason you don't see this in versions before 5.4 is due to #10360. We even see a very similar screenshot in the thread (albeit from an earlier version of the code with different circumstances), and follow-up fix #10525 also relating to first-person rendering of the player. Testing locally, I can see the `video::EMF_BACK_FACE_CULLING` and `video::EMF_FRONT_FACE_CULLING` values getting set on the player's mesh materials in first-person as expected, though turning this setting off gives me similar looking results to this bug.

I'd be interested in seeing if this hardware is respecting the culling flags that minetest sets on materials, the easiest way to test would be to remove the player model and examine some large mesh entities with backface culling.

**Comment by ftrvxmtrx** [comment]
@Df458 thanks for the pointers. I looked at the follow-up fix and saw both front and back face culling is used. After a short look at etnaviv driver (the one mnt reform 2 is using) in Mesa, I realized that particular mode isn't properly translated. This patch seems to fix it (double tested with and without locally). For reference:

```
diff --git a/src/gallium/drivers/etnaviv/etnaviv_translate.h b/src/gallium/drivers/etnaviv/etnaviv_translate.h
index 758a682d084..27b2e3a72f0 100644
--- a/src/gallium/drivers/etnaviv/etnaviv_translate.h
+++ b/src/gallium/drivers/etnaviv/etnaviv_translate.h
@@ -48,6 +48,8 @@ translate_cull_face(unsigned cull_face, unsigned front_ccw)
    switch (cull_face) {
    case PIPE_FACE_NONE:
       return VIVS_PA_CONFIG_CULL_FACE_MODE_OFF;
+   case PIPE_FACE_FRONT_AND_BACK:
+      return VIVS_PA_CONFIG_CULL_FACE_MODE_CW | VIVS_PA_CONFIG_CULL_FACE_MODE_CCW;
    case PIPE_FACE_BACK:
       return front_ccw ? VIVS_PA_CONFIG_CULL_FACE_MODE_CW
                        : VIVS_PA_CONFIG_CULL_FACE_MODE_CCW;
```

**Comment by Df458** [comment]
Interesting, good to know! Hopefully this is something the driver will accept... with that said, it makes me wonder if we could hide the player model by other means while still rendering attachments. Front _and_ back culling definitely seems like the kind of edge case that other drivers might skip.

**Comment by austriancoder** [comment]
A fix landed in mesa: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14779
