### ISSUE TITLE
QueryPerformanceFrequency() return value is not checked

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#11994]
##### Minetest version
commit 48e508052ad477eda1142f08990d523c8b9701ea

##### Summary
The Windows function `QueryPerformanceFrequency()` is used in porting.cpp without checking its return value:

```
; git grep -W 'QueryPerformanceFrequency'
src/porting.cpp=inline double get_perf_freq()
src/porting.cpp-{
src/porting.cpp-        LARGE_INTEGER freq;
src/porting.cpp:        QueryPerformanceFrequency(&freq);
src/porting.cpp-        return freq.QuadPart;
src/porting.cpp-}
```

According to documentation, the function returns a `BOOL` for success, but never fails on Windows XP or later:
https://docs.microsoft.com/de-de/windows/win32/api/profileapi/nf-profileapi-queryperformancefrequency

> If the function fails, the return value is zero. To get extended error information, call GetLastError. On systems that run Windows XP or later, the function will always succeed and will thus never return zero.

According to this StackOverflow post, this is false and the function can indeed fail on Windows XP or later:
https://stackoverflow.com/questions/27258698/why-does-queryperformancecounter-queryperformancefrequency-fail

> The issue happens if your Int64 memory address is not double-word (4-byte) aligned. For example, if you use a compiler that defaults to Byte or Word alignment for objects, or structures, or class member variables. In this case, QueryPerformanceCounter will return false.

> The function can fail with error code ERROR_NOACCESS (Invalid access to memory location) if the variable to not double-word (8-byte) aligned.

As a bugfix requires a recompilation, I suggest to exit with an error message if the return code is, indeed, false.

##### Steps to reproduce
`git grep -W 'QueryPerformanceFrequency' src/`

**Comment by sfan5** [comment]
> but never fails on Windows XP or later

Great

> The issue happens if your Int64 memory address is not double-word (4-byte) aligned

If Minetest is built with a compiler that cannot correctly align structures then we have far worse problems.

**Comment by erlehmann** [comment]
>> but never fails on Windows XP or later
> 
> Great

Not at all. According to the linked StackOverflow post, it can fail on, e.g. Windows 7.

> If Minetest is built with a compiler that cannot correctly align structures then we have far worse problems.

Probably true, as there are many moving parts. I just thought adding an assertion or similar here would not hurt.
