### ISSUE TITLE
Remove or revise the default FPS cap on Android

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#12009]
##### Minetest version
```
5.4.2 from Google Play Store (beta program enrolled)
```

##### OS / Hardware

Operating system: Android 12
CPU: Samsung Galaxy Z Fold2, Snapdragon 865 5G+, [full device specs](https://www.gsmarena.com/samsung_galaxy_z_fold2_5g-10342.php)

GPU model: Adreno 650
OpenGL version: OpenGL ES 3.2

##### Summary

[Minetest is capped at 30 FPS by default on Android](https://github.com/minetest/minetest/blob/66e8aae9f2a28ee31ffe30694fdb61a8fdceb8d7/src/defaultsettings.cpp#L480). However, most high-end devices should be able to manage consistent 60 FPS, if not more. I suggest removing the default FPS cap on Android, or perhaps setting it to 60 by default. V-Sync will cap the framerate naturally if needed anyway.

When power savings are desired, the user can enable their device's battery saving mode which will limit performance.

On other platforms, the default FPS cap could also be raised or removed to allow making use of high-refresh rate displays automatically. 144 Hz displays are slowly becoming the norm for PC gaming, and even non-gaming laptops are starting to feature 120 Hz displays.

##### Steps to reproduce

Run the game on a recent high-end mobile device.

**Comment by wwar-XeStro** [comment]
Ah, I agree. While i used to get 30 FPS at max, my devise could handle 60...

If any changes will be made to default settings then besides that, I'd suggest making FOV (Field of View) to something higher than 72 on Android as the screen is usually small and the player's eyes are closer to the screen than on PC so the default 72 FOV that is good on PC should be higher on Android in my opinion... (I'd suggest 100)Thanks.

**Comment by Calinou** [comment]
> I'd suggest making FOV (Field of View) to something higher than 72 on Android as the screen is usually small and the player's eyes are closer to the screen than on PC so the default 72 FOV that is good on PC should be higher on Android in my opinion... (I'd suggest 100)Thanks.

I think the default FOV is fine on Android, especially with modern devices having wider than 16:9 aspect ratios (typically between 18:9 and 20:9).
