### ISSUE TITLE
Game does not fully display on Samsung Galaxy Z Fold2's main (large) display

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#12007]
##### Minetest version
```
5.4.2 from Google Play Store (beta program enrolled)
```

##### OS / Hardware

Operating system: Android 12
CPU: Snapdragon 865 5G+, [full device specs](https://www.gsmarena.com/samsung_galaxy_z_fold2_5g-10342.php)

GPU model: Adreno 650
OpenGL version: OpenGL ES 3.2

##### Summary

Using a fresh Minetest installation with the default graphics settings, the game displays correctly on the (small) external display:

![Screenshot_20220127-152810_Minetest](https://user-images.githubusercontent.com/180032/151672432-e1dea863-e0d9-4e64-bce1-3eba262da392.png)

However, after killing the application, unfolding the main display and restarting Minetest, the screen is partly cut off:

![Screenshot_20220127-152732_Minetest](https://user-images.githubusercontent.com/180032/151672433-52e23848-33ef-4bf9-a4b7-50a8632a4fd4.png)

I've done pixel counting and it seems that only the bottom 960 pixels of the screen (out of 1768) are used by the game.

When forcing rotation to portrait mode in the device settings, the screen is also cut off on the main display, so this is not specific to the main display's aspect ratio in landscape mode:

![Screenshot_20220127-154024_Minetest](https://user-images.githubusercontent.com/180032/151672447-d367d240-152b-4d67-baab-6489c100f049.png)

Input coordinates are also messed up, as you need to aim much higher (and to the left) to be able to touch buttons in menus and the HUD.

<details>
<summary>More screenshots</summary>

### Main menu on the external display (good)

![Screenshot_20220129-191346_Minetest](https://user-images.githubusercontent.com/180032/151672644-bfbda953-ca5b-44d1-892f-0a0a01b6771b.png)

### Main menu on the unfolded display (bad)

![Screenshot_20220129-191401_Minetest](https://user-images.githubusercontent.com/180032/151672638-350666c0-fe19-48f8-b69a-8160c688de4d.png)

### In-game when starting on external display, then unfolding the device

*The Minetest app does not support run-time resolution changes, so the device will keep the external display's resolution on the unfolded display until you restart the app.*

*Viewport looks good, but the HUD is partially off-screen:*

![Screenshot_20220129-191446_Minetest](https://user-images.githubusercontent.com/180032/151672631-db922e77-c757-4dcb-a203-ec4189ba83ba.png)
</details>

##### Steps to reproduce

Start the game on a Samsung Galaxy Z Fold2's main (unfolded) display. This is likely reproducible on other models from the Z Fold line, but maybe not the Z Flip line (which folds on the other axis).

**Comment by nininik0** [comment]
Well, lots of minetest android stuff is glitchy including shaders and stuff #13580 #13519

**Comment by Unacceptium** [comment]
i wrote a comment on #13671 wich i believe can be useful here

**Comment by grorp** [comment]
marking this issue as "possible close" since the Android version is now based on SDL, which hopefully doesn't have such problems

**Comment by Calinou** [comment]
> marking this issue as "possible close" since the Android version is now based on SDL, which hopefully doesn't have such problems

Does the Android version of 5.9.0 use SDL? If not, is there a development build I can grab somewhere to test it?

**Comment by rubenwardy** [comment]
yes, Android is SDL only
