### ISSUE TITLE
Enabling fixed_virtual_joystick doesn't fix virtual joystick

### ISSUE THREAD

**Issue by wwar-XeStro** [minetest/minetest#12002]
##### Minetest version

```
5.5.0
```

##### OS / Hardware

Operating system: Android 4.4.4

##### Summary

Enabling the "fixed virtual joystick" setting doesn't really fix it.

![Screenshot_2022-01-28-18-34-56](https://user-images.githubusercontent.com/72745616/151607591-bc957148-b3f4-412a-91cc-51daadac96cb.png)

##### Steps to reproduce

1- Enable that setting.
2- Join a server or singleplayer.
3- Press above the joystick.
4- Enjoy the issue.

**Comment by wwar-XeStro** [comment]
Tested again in 5.5.0 stable and it still exists.

**Comment by sonolosoft** [comment]
Enabled/5.4.1/Android 10/20:9 aspect: only triggers if tap inside circle.
![minetest](https://user-images.githubusercontent.com/96827501/153720652-4382aeee-1bd4-4873-8c6d-21d27ff05f08.jpg)

**Comment by wwar-XeStro** [comment]
Yeah, that's correct, it worked fine in every previous version (5.0.0-5.4.2) The issue started with 5.5.0
@sonolosoft

**Comment by sonolosoft** [comment]
Enabled/5.5.0/Android 10/20:9 aspect: Bug!
