### ISSUE TITLE
Dtime Jitter (MT 5.5.0 - 5.6.0(Dev) / Windows / Multiplayer)

### ISSUE THREAD

**Issue by Sharpik** [minetest/minetest#12017]
##### Minetest version
minetest-5.5.0-66e8aae9f-win64

##### OS / Hardware
Operating system: Windows 11
CPU: Intel i5 - 11600K
GPU model: RTX 3070 Ti
RAM: 32GB
HDD: SSD

##### Summary
Problem is with the dtime jittering after approx. an hour of playing.
It keeps getting worse from initial connection to server.
To an approx. hour of playing when it's almost unplayable.

##### Steps to reproduce
Just connect on server hosted on Windows with Windows client an play for some time.
The dtime jitter will grow in time.

![minetest_dtime_jittering](https://user-images.githubusercontent.com/3375029/151703621-1d643fa5-82ae-4c3e-9598-d946daaca02d.jpg)

**Comment by Sharpik** [comment]
If anyone want to test it on my server, then just write me message and I'll whitelist You on server.

**Comment by wsor4035** [comment]
can confirm this issue

**Comment by sfan5** [comment]
What is the minimum playtime for this issue to appear?
Does the FPS actually jitter as much as the value suggests or is the value itself incorrect?
A screenshot of the F5 debug info that shows a bunch of colorful graphs would help too.

**Comment by Sharpik** [comment]
Start:
![screenshot_20220130_170954](https://user-images.githubusercontent.com/3375029/151708108-60c38858-6d97-4b84-96e2-5955b3ef67b6.png)

After approx. 5minutes with rapid moving:
![screenshot_20220130_171007](https://user-images.githubusercontent.com/3375029/151708109-d8c5bf25-5025-47ba-96a1-e3b976739161.png)

Rapid moving in unpredictable (random) directions:
![screenshot_20220130_171132](https://user-images.githubusercontent.com/3375029/151708110-8ac7f5ca-1211-4e39-a510-faa4af2327d0.png)

Video captured screen with readable values:
http://mc.sharpnet.cz/minetest/gallery/bugs/minetest_dtime_jittering.mp4

**Comment by lhofhansl** [comment]
@Sharpik Will it settle after a minute or two. When blocks are loaded into the client the meshing (although done on a separate thread now) can cause the client to slow down until meshing is completed. In a profiler you see entries related to fast faces.

**Comment by Sharpik** [comment]
I made another 2 short videos.. where is it more visible.

http://mc.sharpnet.cz/minetest/gallery/bugs/minetest_dtime_jittering2.mp4

http://mc.sharpnet.cz/minetest/gallery/bugs/minetest_dtime_jittering3.mp4

@lhofhansl  It starts when i connect to the server.. but the jittering is jumping from 14 to aprox. 60 .. And every minute the max jitter is bigger and bigger. After approx. 40 minutes the jitter is jumping from 14 to 1500.

**Comment by Sharpik** [comment]
The main lag spike appearing when client receive packet:

![client_recived_packets](https://user-images.githubusercontent.com/3375029/151719807-4b4a54d4-38d6-4860-95ea-e90ee62c5c4f.jpg)

**Comment by erlehmann** [comment]
@Sharpik shot in the dark, but;

1. Does it still happen if you [set a processor affinity](https://www.thewindowsclub.com/processor-affinity-windows) for Minetest?

2. Does it happen on commit fc161e757c14a0d0b86e69fb5ec631fae8b448de?

**Comment by lhofhansl** [comment]
Perhaps related I found that many (complex mobs) slow things down. In the profiler I see irr::scene::CSkinnedMesh::skinJoint as the main culprit - along with irr::scene::CSkinnedMesh::recoverJointsFromMesh, irr::scene::CSkinnedMesh::updateBoundingBox, and irr::scene::CSkinnedMesh::getFrameData.

Might be specific to me, and it affect rendering time more than the jitter, so might be a different issue entirely. In any case this quickly overtakes rendermap as the most expensive action.

**Comment by Zughy** [comment]
@wsor4035 is this still an issue? Since OP seems gone

**Comment by wsor4035** [comment]
> @wsor4035 is this still an issue? Since OP seems gone

in 5.5.1 or 5.5.0?, last i know this is still an issue in 5.5.0 at least

**Comment by sfan5** [comment]
For re-testing please use 5.5.1.

**Comment by Sharpik** [comment]
New test
Server version: minetest-5.6.0-35ad00623-win64
Client version: minetest-5.6.0-2183b35ba-win64

![obrazek](https://user-images.githubusercontent.com/3375029/180650690-cb01988b-d616-4a52-857e-763863e182f5.png)

It's still presented.. to have that big jittering I just need to run around for a while on small place.

**Comment by sfan5** [comment]
possible related fix #12622

**Comment by Zughy** [comment]
@Sharpik can you please re-test with the latest dev version? Since the PR sfan pointed to has been merged

**Comment by Sharpik** [comment]
> @Sharpik can you please re-test with the latest dev version? Since the PR sfan pointed to has been merged

Hi, I'd like to, but I'm unable to compile Minetest my self (Windows x64).

I need to wait till that fix will be included in build at https://gitlab.com/minetest/minetest/-/pipelines

Or are You able to share ready to test version (Wx64) of MT?
Thanks

**Comment by Zughy** [comment]
@Sharpik sorry, I've missed the message. Here: https://github.com/minetest/minetest/releases/download/5.6.0/minetest-5.6.0-win64.zip
