### ISSUE TITLE
Get rid of Mingw32 workarounds asap

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12022]
Multiple workarounds were added for crashing `thread_local` destructors on 32-bit MinGW:
* 70df3d54f37c280f7afe60f6e964b8406577f39f (before 5.3.0)
* 484a4b518f6025f2cdec9eb89fdf3883eb57fc28 (before 5.5.0)

**These should be reverted as soon as possible by means of upgrading MinGW to a newer, non-buggy version**

**Comment by erlehmann** [comment]
@sfan5 is it this? https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=7fc0f78c3f43af1967cb7b1ee8f4947f3b890aa2

**Comment by sfan5** [comment]
That looks like it, thank you for finding this.
