### ISSUE TITLE
Document to list all the things to break in the next major release

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12028]
## Problem

Sometimes breaking things is, well, necessary, but it happens that some changes get postponed to the next major release because of one reason or another. See for instance https://github.com/minetest/minetest/pull/11963#discussion_r789703686

## Solutions

Have a document in the repo to jot down these things, so they don't get lost

**Comment by rubenwardy** [comment]
- Attachment space (*10)
- get_sky() return a table
- game.conf name/id mess

low priority:

- remove depends.txt / description.txt (would simplify ContentDB and Minetest code a little, but supporting them is really not a big deal so not important)

**Comment by Desour** [comment]
> providing it doesn't go offtopic

This condition always evaluates to `false`.

Also, endusers (ie. modders) need this information, too, so an issue is the wrong place (if you don't want duplication).

What speaks against grepping for "deprecated"?

**Comment by Zughy** [comment]
@rubenwardy I think that with a document it's cleaner as it'd allow me to edit the document from the very `get_sky()` PR. An issue can get messy pretty fast, with people not agreeing with one breaking change for dozens of messages instead of debating the change in the relevant PR. It also means having a core dev in here updating the message with all the breaking changes every time, instead of leaving the burden to the user creating the PR. You already have a lot of things to do, don't put more work on your backs
