### ISSUE TITLE
Throw fatal error if enabled database backends are missing

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest#12026]
## Problem

CMake fails silently with a "not found" status message if any of the enabled optional database backends are not found. You should know when you want a feature whether it was successfully enabled.

## Solutions

1. Disable the optional database backends by default, and throw a fatal error if they're enabled and not found. I acknowledge this could be an inconvenience for people who always enable these, but there are also people who have to explicitly disable them on every build.

## Alternatives

1. Add a `REQUIRE_XXX` variable for each database backend that throws a fatal error if the respective backend was not found. I don't prefer this solution, because it adds more complexity to the build to solve something that should be straightforward.

2. Throw a fatal error when a backend is not found if and only if `ENABLE_XXX` is set in the cache. It would be possible this way to automatically enable or disable the backend on the first run based on its detection, and throw an error only if it was explicitly requested on the build. If I saw a build doing this, I would think "Ah, very clever solution, time to refactor this confusing cache abuse.", so I don't prefer this solution either.

## Additional Context

Unless someone else is excited to make a PR, I am planning on doing it. I opened this issue because there are multiple solutions and I am willing to PR any of them; we might as well get this part of the discussion out of the way before anyone throws code into review.

**Comment by JosiahWI** [comment]
As per IRC discussion with a core dev, my new approach will be to add options with a third value to request deciding automatically based on detection. I've decided to have the automatic value be the default, because that reflects the current default behavior.

**Comment by sfan5** [comment]
Yes, that was the intention. MT should pick up optional libs by default and optionally allow requiring *or* disabling them.
