### ISSUE TITLE
Forked Irrlicht not included in release.

### ISSUE THREAD

**Issue by limburgher** [minetest/minetest#12027]
5.5.0

Operating system: Fedora Linux

##### Summary
I'm one of the package maintainers for Minetest in Fedora. 5.5.0 requires IrrlictMt, which is not included in the release. Most Linux distribution build systems do not have network access at build time, so git clone --depth=1 https://github.com/minetest/irrlicht lib/irrlichtmt will fail.  Specifying IRRLICHT_INCLUDE_DIR to use system Irrlicht doesn't work. We need either a release that includes IrrlichtMt or a way to use system Irrlicht.

Thank you!

**Comment by rollerozxa** [comment]
Could the build system for Minetest on Fedora include downloading IrrlichtMt 1.9.0m4?

**Comment by limburgher** [comment]
No, it can't download anything. It needs to be produceable from released tarballs. If I simply extract that tarball into lib/irrlicht in the main source archive should that work?

**Comment by rubenwardy** [comment]
If you can grab irrlichtmt as a tarball, then that will work

**Comment by sfan5** [comment]
You can download and extract the irrlichtmt source to `lib/irrlichtmt` and have it be built automatically. Build-time network access or git is not a requirement.

> Specifying IRRLICHT_INCLUDE_DIR to use system Irrlicht doesn't work.

If you want to package IrrlichtMt separately (it does not conflict with upstream) then an installed copy will be picked up automatically. If that is for some reason not the case the right variable is `CMAKE_PREFIX_PATH`.

**Comment by limburgher** [comment]
> If you can grab irrlichtmt as a tarball and place it in lib/irrlichtmt, then that will work
> 
> https://github.com/minetest/irrlicht/archive/refs/tags/1.9.0mt4.tar.gz

This worked, thank you!
