### ISSUE TITLE
Compiled app bundle does not launch "Unknown error: 153"

### ISSUE THREAD

**Issue by animaux** [minetest/minetest#12033]
##### OS / Hardware

Operating system: macOS 12.2 (21D49) Monterey
CPU: Apple M1

Like with the 5.4.1-release, mentioned [here](https://github.com/minetest/minetest/issues/11233#issuecomment-1019369311), I tried to compile the current 5.5.0-release, but the process gets stuck at `make -j$(nproc)`. No progress after:

```sh
[ 99%] Building CXX object src/CMakeFiles/minetest.dir/voxel.cpp.o
```

A lot of CPU is used and the system becomes very slow. After quitting the process it’s instantly normal again. Not sure if it helps, but previously it was the item before, where it got stuck `Building CXX object src/CMakeFiles/minetest.dir/voxelalgorithms.cpp.o`.

**Comment by ivxvm** [comment]
I'm also using the same os / arch and compiled master yesterday and today many times.
Here is one of workflows that works for me:

```
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
mkdir cmakebuild
cd cmakebuild
cmake .. \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
    -DCMAKE_FIND_FRAMEWORK=LAST \
    -DCMAKE_INSTALL_PREFIX=../build/macos/ \
    -DRUN_IN_PLACE=FALSE -DENABLE_GETTEXT=TRUE
make -j$(nproc)
make package
```

All libraries and toolchains (like cmake) installed with arm64 brew.

**Comment by animaux** [comment]
Thanks @ivxvm, I tried that with a clean start with the same result. Will doublecheck the dependencies.

**Comment by animaux** [comment]
I just noted the following first output line after `make -j$(nproc)` is:

``` sh
zsh: command not found: nproc
```

**Comment by animaux** [comment]
Yes, fixed it by installing:

``` sh
brew install coreutils
```

Which includes the nproc command.

**Comment by animaux** [comment]
The App bundle builds, but wont open :(

```
open /Applications/Minetest.app 
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600003cb4d20 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

**Comment by sfan5** [comment]
Uh yeah putting nproc into the mac instructions is not a good idea when that is not installed by default.
It ends up being replaced by no text and `make -j` instructs it to spawn all tasks at once, which runs out of RAM really quick.

The last error you mentioned seems to be [related to missing code signing](https://developer.apple.com/forums/thread/666611?page=5).

**Comment by animaux** [comment]
@sfan5 many thanks for elaborating!

I tried signing the app with the methods described in the linked article, to no avail. `:(`

**Comment by animaux** [comment]
```
pkgutil --check-signature /…/cmakebuild/minetest.app 
Package "Minetest":
   Status: package is invalid (checksum did not verify)
```

**Comment by animaux** [comment]
BTW, when using the compile instructions provided by @ivxvm above, I get a `minetest-5.6.0-dev-osx.zip`-bundle. So I’d assume this is not the 5.5.0-release version that’s compiling.

**Comment by animaux** [comment]
The above check-result via pkgutil changes after trying to sign the app:

```
sudo codesign --force --deep --sign - /…/minetest/cmakebuild/minetest.app  
```

to 

```
pkgutil --check-signature /…/minetest/cmakebuild/minetest.app             
Package "Minetest":
   Status: invalid signature
```

**Comment by ivxvm** [comment]
This is what I used to sign packaged app:
```
codesign --force --deep --sign - /Applications/minetest.app
```
After doing so, I'm able to run the app, but it doesn't work as expected anyway. Maybe my problem with app freezing in the menu is somehow related to invalid signature, because I just checked and I get this too:
```
% pkgutil --check-signature /Applications/minetest.app
Package "Minetest":
   Status: invalid signature
```

**Comment by animaux** [comment]
For some reason the ad hoc signing doesn’t seem to be sufficient for me, or there is some other problem.

**Comment by Zughy** [comment]
@animaux is this bug still present with the new version?

**Comment by animaux** [comment]
@Zughy just did a quick check, seems like the signing problem persists, I compiled with a fresh repo clone and then:

``` sh
% open minetest.app 
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x6000038ef960 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}
```

**Comment by DigitalSolomon** [comment]
Did you ever end up finding a workaround for this? Running into similar issues it looks.

**Comment by animaux** [comment]
> Did you ever end up finding a workaround for this? Running into similar issues it looks.

I kind of »fixed it« by installing via homebrew:

```sh
brew install minetest
```

**Comment by superfloh247** [comment]
this works for me on MacOS 14.1, Xcode 15, Apple Silicon M1pro

`codesign --remove-signature macos/minetest.app && codesign --force --deep -s - macos/minetest.app
`

**Comment by siboehm** [comment]
I don't think you need the first command:
```
man codesign:

-f, --force
             When signing, causes codesign to replace any existing signature on the path(s) given.                     Without this option, existing signatures will not be replaced, and the signing operation                  fails. 
```
