### ISSUE TITLE
Compile with gles support

### ISSUE THREAD

**Issue by wolfallein** [minetest/minetest#12035]
##### Minetest version
```
Minetest 5.6.0-dev-8012b8
```

##### OS / Hardware
Operating system: Debian
CPU: Allwinner A64
GPU model: Mali 400 MP2

##### Summary
Hi,

I'm trying to compile with OpenGLES support instead of OpenGL but I'm having some problems.
I followed the instructions on README, but added `ENABLE_GLES=ON` to the options, so I compiled with:

````
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
cmake . -DRUN_IN_PLACE=TRUE -DENABLE_GLES=ON
make -j$(nproc)
./bin/minetest
````

In the first attempt it compiled but it falls back to OpenGL support so I edited `lib/irrlichtmt/include/IrrCompileConfig.h ` forcing:

`#define _IRR_COMPILE_WITH_OGLES2_`

I don't know if this is the correct thing to do.
Compilation runs ok.
Now when I ran minetest it looks for shader files that I don't know where to find it. It looks for:

````
../client/shaders/Irrlicht/COGLES2Solid.vsh
../client/shaders/Irrlicht/COGLES2Solid.fsh
../client/shaders/Irrlicht/COGLES2LightmapModulate.fsh
../client/shaders/Irrlicht/COGLES2SphereMap.vsh
../client/shaders/Irrlicht/COGLES2SphereMap.fsh
../client/shaders/Irrlicht/COGLES2Reflection2Layer.vsh
../client/shaders/Irrlicht/COGLES2Reflection2Layer.fsh
...
````
And I have errors on the terminal. Let me know what step I'm missing to get it to run well with Open gles support.

Thanks in advance.

**Comment by JosiahWI** [comment]
Perhaps this issue should be moved to https://github.com/minetest/irrlicht

**Comment by sfan5** [comment]
Those are found in media/Shaders in the Irrlicht folder, you can copy or symlink them to the expected path.

For completeness here's how all commands from start to finish:
```bash
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
sed '/#define _IRR_COMPILE_WITH_OGLES2_/ s|^//||g' -i lib/irrlichtmt/include/IrrCompileConfig.h
sed '/#define _IRR_COMPILE_WITH_OPENGL_/ s|^|//|g' -i lib/irrlichtmt/include/IrrCompileConfig.h
ln -s ../../lib/irrlichtmt/media/Shaders client/shaders/Irrlicht
cmake . -DRUN_IN_PLACE=TRUE -DENABLE_GLES=ON
make -j4
```

**Comment by wolfallein** [comment]
Thank you @sfan5 

It doesn't complain about the files, but something is still wrong. I get this on the terminal:

````
gpir: shader exceeds limit of 512 instructions
gpir: fail schedule block
...
````

and the game screen doesn't show anything:

![image](https://user-images.githubusercontent.com/15076592/152053650-269e3c8c-ae42-4c0e-a083-416d69126d22.png)

On the menu screen, I think I should have clouds as well.
![image](https://user-images.githubusercontent.com/15076592/152053753-ffce4bca-deb6-4a9a-89c9-a0a8e0be27ab.png)

**Comment by sfan5** [comment]
That sounds like a limitation/bug of your GPU driver (do you have Mesa or the proprietary one?). I regularly run the GLES build on my desktop for testing.

**Comment by wolfallein** [comment]
I'm using Mesa 21.3.5 with the open-source lima driver. It could be a driver issue, but I don't see any problems with another app.

When using Minetest with OpenGL it runs ok, but low fps. I wanted to see if I can increase performance when using only GLES (what the hardware is capable to do). OpenGL support is limited:

[https://docs.mesa3d.org/drivers/lima.html#supported-apis](url)

````
glxheads: exercise multiple GLX connections (any key = exit)
Usage:
  glxheads xdisplayname ...
Example:
  glxheads :0 mars:0 venus:1
Name: :0
  Display:     0x558e7d4190
  Window:      0x800002
  Context:     0x558e7fee50
  GL_VERSION:  2.1 Mesa 21.3.5
  GL_VENDOR:   lima
  GL_RENDERER: Mali400
````

**Comment by wolfallein** [comment]
Hi @sfan5 , 
I talked to Mesa developers and found that this problem (shader limit of 512 instructions) is a hardware limitation of the Mali 400 GPU.

They also stated that it is possible to improve performance if I get it to work only with GLES. OpenGL support on the Mali 400 is just for compatibility since the hardware itself only supports GLES. Minetest using OpenGL could try to send a job that the GPU cannot do or cannot do at a reasonable time.

Since this is a specific user case I don't expect to get much help, but I would like to know where I could mess in the code to try to decrease the number of instructions, if possible. It would be very helpful if you can give me a hint as to where I could start working.

Thank you

**Comment by sfan5** [comment]
Someone actually brought that limit up [the other day](https://irc.minetest.net/minetest-dev/2022-02-04#i_5933449) I didn't mention it here.

Since you described that ingame is affected the most it's likely one of the shaders in here: https://github.com/minetest/minetest/tree/master/client/shaders
Most relevant are `nodes_shader` and `object_shader`. Don't be surprised at the size, most of it is statically disabled.
