### ISSUE TITLE
Autoforward no longer allows sideways movement

### ISSUE THREAD

**Issue by Montandalar** [minetest/minetest#12048]
##### Minetest version

Self-compiled, I don't think debian bookworm (testing) is up to 5.5 yet
```
Minetest 5.5.0 (Linux)
Using Irrlicht 1.9.0mt4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

previously worked on 5.4

##### OS / Hardware

Operating system: Debian bookworm
CPU: AMD Ryzen 3 2200G

##### Summary
Under 5.4 and so far as I can recall ever since autoforward was added, you were able to press the sideways movement keys (A/D default) to move sideways while still continuing to move forward, without breaking autoforward. I used this a lot when being lazy to make small adjustments while being able to use only my left hand on the keyboard and take my hand off the mouse.

Since a certain point in 5.5.0-dev's development, this was broken. I don't see any reason to restrict it and I can't find anything that says it was deliberate in the git logs. However the changes in 291a6b70 seem somewhat related. The leap from Irrlicht to IrrlichtMt has made building 5.5.0-dev versions a pain otherwise I would have run a git bisect.

##### Steps to reproduce

1. Put autoforward on with the keybind.
2. Try to move sideways a bit with A/D/whatever bind
3. The keys will do nothing as of 5.5, but used to move you sideways as if you were holding forward+move left/right (W+A/D).

**Comment by SwissalpS** [comment]
tested on 5.5 and can confirm. I agree, I'd like the old behaviour back too.

**Comment by appgurueu** [comment]
Can confirm on 5.6-dev on Ubuntu 20.04 too.

**Comment by erlehmann** [comment]
This is relevant for long travels using boats and mountable mobs, or walking/flying long distances (e.g. on the Nether roof) without having to continuously press one key down (which hurts me after a while).

>  The leap from Irrlicht to IrrlichtMt has made building 5.5.0-dev versions a pain otherwise I would have run a git bisect.

This iis the sole reason I have not bisected this myself. Whoever does, please share how to properly bisect Minetest.

**Comment by appgurueu** [comment]
Pretty sure the commit to blame is https://github.com/minetest/minetest/commit/1d69a23ba4, which robbed autoforward of sideways directions:

```c++
	// autoforward if set: move towards pointed position at maximum speed
	if (player->getPlayerSettings().continuous_forward &&
			client->activeObjectsReceived() && !player->isDead()) {
		control.movement_speed = 1.0f;
		control.movement_direction = 0.0f;
	}
```

should be pretty easy to fix by setting `control.movement_direction` appropriately if `KeyType::(LEFT|RIGHT)` is set.

**Comment by sfan5** [comment]
...or by simply not resetting the movement_direction
