### ISSUE TITLE
Legacy OpenGL preference mismatch between Minetest and IrrlichtMt

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest#12041]
##### Minetest version

```
544b9d5
```

##### IrrlichtMt version

```
2fec5e5
```

##### OS / Hardware
Operating system: N/A
CPU: N/A

GPU model: N/A
OpenGL version: N/A

##### Summary
Minetest has a cache variable `OPENGL_GL_PREFERENCE` that determines whether Legacy OpenGL is preferred or not, but IrrlichtMt always prefers Legacy OpenGL regardless of Minetest's cache variable. Since IrrlichtMt always wants the Legacy version anyway, my suggested fix is to remove the cache option and let IrrlichtMt handle the OpenGL requirements entirely. The comments could be preserved by moving them to IrrlichtMt, or by requesting the Legacy version (no effect; for style only) with the appropriate comments before `find_package(IrrlichtMt)`.

**Comment by rubenwardy** [comment]
That variable was set to silence a CMake warning
