### ISSUE TITLE
Help me optimize Lua reimplementation of getBlockSeed2()

### ISSUE THREAD

**Issue by kay27** [minetest/minetest#12042]
When you process `register_on_generated callback`, you receive `blockseed` value which is more likely a chunk seed, but okay, if you want to process this chunk again later for any reason and make it deterministic again, then you have obviously to store these seeds in mod storage which is a weirdness, my storage is 20MB currently, or you have to reimplement seed calculation in Lua, which is cpp function [getBlockSeed2()](https://github.com/minetest/minetest/blob/master/src/mapgen/mapgen.cpp#L230) for v7 mapgen.

Currently my Lua implementation works but looks like a mess :( So I'd appreciate any ideas about how to clean it up:

```lua
local function unsigned(v)
    if v < 0 then
        v = 0x100000000 - (math.abs(v) % 0x100000000)
    end
    return v % 0x100000000
end

local function bitwise_xor_32(a, b)
    local a = unsigned(a)
    local b = unsigned(b)
    local c = 0
    for n = 31, 0, -1 do
        local mask = math.floor(2^n)
        if (a >= mask) ~= (b >= mask) then
            c = c + mask
        end
        a = a % mask
        b = b % mask
     end
     return c
end

local function getBlockSeed2(x, y, z, seed)
    local n = unsigned(unsigned(1619 * x) + unsigned(31337 * y) + unsigned(52591 * z) + unsigned(1013 * seed))
    n = bitwise_xor_32(math.floor(n / 0x2000), n)
    return unsigned((n * unsigned(n * n * 60493 + 19990303) + 1376312589))
end
```
Ref. https://git.minetest.land/MineClone5/MineClone5/issues/159

**Comment by appgurueu** [comment]
Why do you consider it "messy" though? You could try using the newly added `bitop` library, but you'll have to leave the polyfill in for older versions anyways. Besides, it seems to be implemented rather well - why the `math.floor` around the `2^n` though? I'd rename `unsigned` to `wrapping_u32` or something. You might want to introduce a comment referencing the engine code this reimplements in Lua (`u32 Mapgen::getBlockSeed2(v3s16 p, s32 seed)`).

Your title says "help me optimize", but I don't see how this could be reasonably optimized; replacing the xor with a bitop one would be slightly faster, but I don't think this matters at all for *a single xor operation* per mapblock - the mapgen running on these mapblocks will do much heavier lifting, optimize that instead.

**Comment by kay27** [comment]
> why the math.floor around the 2^n though?
It is surprising for me too, but 0^0 = 1.0 (float).

> Why do you consider it "messy" though? 
Well, when I come up with 20 lines from 5, I couldn't consider it fine.

> If you want getBlockSeed2 to be exposed to the Lua API, just say so.
Actually I could create a PR, but I'm not sure if someone will approve it, so we may discuss here the probability of it.

But for now it would be just good to make it slightly faster and clean.

Thanks for bitop, I'll maybe try for minetest 5.5.

**Comment by appgurueu** [comment]
> > why the math.floor around the 2^n though?
> 
> It is surprising for me too, but 0^0 = 1.0 (float).

2^0 is supposed to be 0 though? The `math.floor` has no effect here.

**Comment by kay27** [comment]
Let's try step by step :)
1. Could you please go https://www.lua.org/cgi-bin/demo
2. Could you please type there `print(2^0)`
3. Could you please then click "run" and then try print(math.floor(2^0))`

**Comment by appgurueu** [comment]
> 

The linked website uses a newer version of Lua that distinguishes between floats and integers. Lua 5.1 / LuaJIT only know doubles.

**Comment by kay27** [comment]
Well, locally I used this version too... But it doesn't look good to run the engine every time to run tests... If you're sure that we can safely remove floor - it should be fine then. Thanks again!

**Comment by kay27** [comment]
>> If you want getBlockSeed2 to be exposed to the Lua API, just say so.

> Actually I could create a PR, but I'm not sure if someone will approve it, so we may discuss here a probability of it.

Of course, it would be nice to use API function - it should be a single line, seed might be optional, etc. I'd be really happy if it was. There are two versions of the functions, I have no idea how to determine which of them current mapgen uses - it could be resolved too by C++ part. So, well, if you or someone else will write it, I'll say many thanks again. Times ago, when I only started to explore mapgen stuff, I found minor inconsistency and tried to add intentionally very minor PR to check what will happen then, and it was bad experience, so currently I more likely deal an engine given us from above.

**Comment by kay27** [comment]
OK, thanks so much, I optimized this function and now mcl_mapgen function set looks so:
```lua
local seed = minetest.get_mapgen_setting("seed")

local function uint32_t(v)
	if v >= 0 then
		return v % 0x100000000
	end
	return 0x100000000 - (math.abs(v) % 0x100000000)
end

local function get_block_seed(pos, current_seed)
	local current_seed = current_seed or uint32_t(tonumber(seed))
	return uint32_t(uint32_t(23 * pos.x) + uint32_t(42123 * pos.y) + uint32_t(38134234 * pos.z) + current_seed)
end

local function get_block_seed2(pos, current_seed)
	local current_seed = current_seed or uint32_t(tonumber(seed))
	local n = uint32_t(uint32_t(1619 * pos.x) + uint32_t(31337 * pos.y) + uint32_t(52591 * pos.z) + uint32_t(1013 * current_seed))
	n = bit.bxor(bit.rshift(n, 13), n)
	local seed = uint32_t((n * uint32_t(n * n * 60493 + 19990303) + 1376312589))
	return seed
end

local function get_block_seed3(pos, current_seed)
	local current_seed = uint32_t(current_seed or uint32_t(tonumber(seed)))
	local x = uint32_t((pos.x + 32768) * 13)
	local y = uint32_t((pos.y + 32767) * 13873)
	local z = uint32_t((pos.z + 76705) * 115249)
	local seed = uint32_t(bit.bxor(current_seed, x, y, z))
	return seed
end
```
I really didn't like what get_block_seed2() produced - there were too many blocks with THE SAME seed, it confirmed several times. Probably it could be not so bad for map chunks. But I often needed it for map blocks, e.g. last time - to decide it we should place amethyst geode which perfectly fits into a map block. There were trivial distribution function like `pr = PseudoRandom(seed + constant)` and `if pr:next(1, 140) == 52`, and this match never happened for 2000+ map blocks with seeds calculated by 2nd function.

I thought this function was something of value and tried to replicate it. Now I realize, that it's better not to use it ever.

Now I'd like to find better seed replacement for MineClone 5. There is still a question, should we use singlenode mapgen to write our own mapgen similar to Minecraft. I thought we shouldn't do that, now we use a [helper API](https://git.minetest.land/MineClone5/MineClone5/src/branch/master/mods/CORE/mcl_mapgen/init.lua#L222) which places structures only after full chunk with shell generation, so we restored broken structures and no need to rewrite the mapgen entirely any longer. But some people want that still, so it's kinda an open question. And bad mapgen seed algorithm could be an argument in favor of own lua mapgen.

Regards,
