### ISSUE TITLE
Find scripts for LevelDB and HiRedis

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest#12045]
## Problem

It is easier to work with libraries in the build when they are properly included with find_package, which LevelDB and HiRedis currently aren't.

## Solutions

1. Move the search logic from src/CMakeLists.txt into cmake/Modules/FindLevelDB.CMake and cmake/Modules/FindHiRedis.cmake.

## Alternatives

1. LevelDB and HiRedis both have their own configs now, but only since recently. We can't support older versions if we rely on these, unfortunately.

## Additional context

I'm planning to do this in the same PR as #12026.

**Comment by sfan5** [comment]
> It is easier to work with libraries in the build when they are properly included with find_package

You mean if they create a CMake target? Just moving them to another file doesn't change a whole lot.
