### ISSUE TITLE
Unexpected byte in MapBlock blob format

### ISSUE THREAD

**Issue by UgnilJoZ** [minetest/minetest#12053]
##### Minetest version

```
$ bin/minetest --version
Minetest 5.5.0-dev-9d3135a (Linux)
$ git log
commit 9d3135a21b31eea6dcec67b887243bcb6124b6a1
…
```

##### OS / Hardware

Operating system: Arch

##### Summary
I am trying to read the world format in version 29. I am happy to see zstd is now used for all the content except for the map format version number.

In this zstd data, I notice there is an additional zero byte between the `timestamp` (marked in below picture) and `num_name_id_mappings` (which has the value `00 0b`).
![grafik](https://user-images.githubusercontent.com/7910828/152605285-011cb5f8-c472-4abf-930d-71db17b88046.png)

In [the documentation](https://github.com/minetest/minetest/blob/master/doc/world_format.txt#L343-L349), there is no mention of this additional byte.

Does it have any meaning?

**Comment by sfan5** [comment]
It does have meaning but will never be not zero now or for the forseeable future: (version byte)
https://github.com/minetest/minetest/blob/be05c9022d8b6eff63f477bc8ca52efd7d631cb6/src/nameidmapping.cpp#L24-L32

Looks like this was forgotten in the docs.

**Comment by UgnilJoZ** [comment]
Thanks for the info, I'll ignore the byte!

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/pull/12061
