### ISSUE TITLE
Game crashes because of library libstdc++-6.dll

### ISSUE THREAD

**Issue by literallyMilk** [minetest/minetest#12058]
##### Minetest version
```
5.5.0
```

##### OS / Hardware
Operating system: Windows 7 Ultimate x64
CPU: AMD Athlon 64 X2 6000+

##### Summary
Hi, i downloaded the new version 5.5.0 because i wanted to play with my friend. I decided to test singleplayer out and tried to create a new world and join it, but the game crashed because of library libstdc++-6.dll. I tried porting game files from 5.4.1 and lowering graphics, but this error still occurs.
Here is the debug file and screenshots.
[debug.txt](https://github.com/minetest/minetest/files/8023993/debug.txt)
![изображение](https://user-images.githubusercontent.com/86829280/152993196-1777faaa-d643-4267-b9cd-59e52690e295.png)
![изображение](https://user-images.githubusercontent.com/86829280/152993223-ae611778-11e8-4b58-93bc-dca07505c0f7.png)

##### Steps to reproduce
1. Create new world
2. Try to join it

**Comment by rollerozxa** [comment]
I don't know if this is the case but it might be due to your Windows username containing UTF-8 characters. Can you try moving the Minetest directory out of your user folder (e.g. into C:\Minetest\) and see if that fixes the issue?

**Comment by literallyMilk** [comment]
Thanks, it helped.
