### ISSUE TITLE
Crashes QEMU on QEMU arm64

### ISSUE THREAD

**Issue by DUOLabs333** [minetest/minetest#12064]
##### Minetest version

```
5.5
```

##### OS / Hardware

Operating system:
CPU: arm64

GPU model: virgl
OpenGL version: `2.1`

##### Summary
Running `minetest` crashes QEMU

##### Steps to reproduce
1. Run QEMU arm64
2. Run minetest
3. See crash

**Comment by sfan5** [comment]
Aside from the reproduction steps being way too vague, if Minetest crashes QEMU why would that be our bug?

**Comment by DUOLabs333** [comment]
Well, it doesn't crash on other programs, but I'm not sure -- should I file it with QEMU?

**Comment by SmallJoker** [comment]
Get some log files and/or gdb backtraces and file them to QEMU. There could be an issue with Minetest somewhere, but I don't think QEMU should crash because of this.

**Comment by DUOLabs333** [comment]
It has now been fixed.
