### ISSUE TITLE
Minetest folder deleted recursively

### ISSUE THREAD

**Issue by sonolosoft** [minetest/minetest#12069]
##### Minetest version

```
5.5.0
```

##### OS / Hardware

Operating system: Android 10
CPU: 

GPU model:
OpenGL version:

##### Summary

- "/Minetest/" folder is deleted even if it contains files/folders not moved to scoped storage.
- "/Minetest/lua_api.txt" is deleted
- "/Minetest/sounds/" folder is deleted (https://wiki.minetest.net/Main_menu_music)

See #11466

Maybe after moving files, it can try delete "/Minetest/" dir, then leave it alone if it fails?

"The directory shall be removed only if it is an empty directory."
(https://pubs.opengroup.org/onlinepubs/009696799/functions/rmdir.html)

##### Steps to reproduce

- Put some extra files/folders in "/Minetest/" root folder
- Delete/rename "/Android/data/net.minetest.minetest/"
- Start Minetest

**Comment by rubenwardy** [comment]
Too late for this, most users will have already updated and Minetest doesn't have access to these directories on the latest Android SDK version
