### ISSUE TITLE
Per-player creative mode progress

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [minetest/minetest#12076]
* `minetest.is_creative_enabled(name)`: returns boolean
    * Returning `true` means that Creative Mode is enabled for player `name`.
    * `name` will be `""` for non-players or if the player is unknown.
    * This function should be overridden by Creative Mode-related mods to
      implement a per-player Creative Mode.
    * By default, this function returns `true` if the setting
      `creative_mode` is `true` and `false` otherwise.

This is what lua_api.txt says for creative mode, and I've seen this was implemented as a result of #8413 but how can the server remotely tell the client to go in creative? Is it possible enabling it remotely for a player POV without making them relog?

**Comment by rubenwardy** [comment]
Creative mode is entirely implemented and controlled by server-side mods and games. These mods and games need to override `is_creative_enabled`, as mentioned by the documentation

Minetest Game's creative mod provides a `creative` privilege, and overrides the function here:

**Comment by Zughy** [comment]
Answered, closing
