### ISSUE TITLE
Anticheat is too strict for connections from the same host

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [minetest/minetest#12078]
##### Minetest version
Server: 5.5
Client: 5.3
Same machine through containers

##### Summary
Anticheat wrongly assumes I'm too fast and resets my position

##### Steps to reproduce
Create an LXC container with minetest 5.5, select latest version and connect to it from the host using minetest 5.3, start walking a bit

**Comment by SmallJoker** [comment]
Related movement anticheat issue: #10880

**Comment by erlehmann** [comment]
@TanyaEleventhGoddess has this been fixed?

**Comment by TanyaEleventhGoddess** [comment]
> @TanyaEleventhGoddess has this been fixed?
Sorry I don't know, haven't logged in for a long while & haven't enough resources to recompile minetest rn
