### ISSUE TITLE
Getting back to menu on android client underdocumented

### ISSUE THREAD

**Issue by kab0u** [minetest/minetest#12070]
##### Minetest version
```
All versions
```
##### OS / Hardware
Operating system: android (obviously)

##### Summary
There is nowhere to be found any documentation about how to return to the menu from within a game. 

H/t to tech_exorcist on #minetest irc for mentioning that the android virtual back button (the left-pointing arrow at the bottom of the screen) does what the esc key does on keyboardful clients.

To restate more clearly for posterity and search engine indexing:

**Tap the "back" icon on the bottom of the touchscreen to return to the menu on minetest android clients.**

Really wish this were at least mentioned in the mt wiki and the regular mt README.  Ideally someone ought to fix up the mess that is the android mt interface, but yeah... not sending patches myself

**Comment by rollerozxa** [comment]
Isn't this pretty obvious? Most if not all games use the back button to return to the menu on Android.

**Comment by SwissalpS** [comment]
> Isn't this pretty obvious? Most if not all games use the back button to return to the menu on Android.

Yes, but if minetest is their first android experience, then it wouldn't be obvious.

**Comment by wwar-XeStro** [comment]
That's related to knowing how Android works not Minetest... i guess... I mean most games don't have the tutorial for the back button as far as i can see.

**Comment by SwissalpS** [comment]
> That's related to knowing how Android works not Minetest... i guess... I mean most games don't have the tutorial for the back button as far as i can see.

You are probably right since most games hardly have any tutorials if at all. That doesn't mean minetest can't mention it.

At the end of the day, we want players to enjoy the experience and return.

**Comment by Gamer-Kold** [comment]
I want to add that I spent quite frankly; an embarassing amount of time quitting the game by closing the app entirely before I figured out how to open the menu.

I'm not the biggest android gamer, but most of the one's I played had the menu button as part of the UI.

I like the way the menu is opened, but it wouldn't be that bad to have some text fade in for 3 seconds, right?

**Comment by rubenwardy** [comment]
I support adding onscreen buttons for opening the pause menu and closing formspecs on Android, and hiding the navigation bar. It's a lot more user friendly
