### ISSUE TITLE
find_nodes_in_area doesnt work with CSM

### ISSUE THREAD

**Issue by mrtechtroid** [minetest/minetest#12086]
##### Minetest version

```
Minetest Version 5.5.0
```

##### OS / Hardware

Operating system: Windows
CPU:

##### Summary
The `minetest.find_nodes_in_area()` function doesnt work and returns a nil always. 

##### Steps to reproduce
Just Enable CSM in Settings And Enable The preview mod in the mods.conf file
Then Load Up The World And You Will See That The Command Is Returning a Nil value even though nodes related to that type exist.
![image](https://user-images.githubusercontent.com/64828294/154808749-83531f11-e54d-4a3f-8aea-23f05813c785.png)

**Comment by sfan5** [comment]
Did you disable CSM restrictions using settings on the server?
Quoting minetest.conf.example:
<pre>
#    Restricts the access of certain client-side functions on servers.
#    Combine the byteflags below to restrict client-side features, or set to 0
#    for no restrictions:
#    LOAD_CLIENT_MODS: 1 (disable loading client-provided mods)
#    CHAT_MESSAGES: 2 (disable send_chat_message call client-side)
#    READ_ITEMDEFS: 4 (disable get_item_def call client-side)
#    READ_NODEDEFS: 8 (disable get_node_def call client-side)
#    LOOKUP_NODES_LIMIT: 16 (limits get_node call client-side to
#    csm_restriction_noderange)
#    READ_PLAYERINFO: 32 (disable get_player_names call client-side)
#    type: int
# csm_restriction_flags = 62

#    If the CSM restriction for node range is enabled, get_node calls are limited
#    to this distance from the player to the node.
#    type: int
# csm_restriction_noderange = 0
</pre>

**Comment by mrtechtroid** [comment]
im trying this on a singleplayer
i can see that except load_client_mods everything else is enabled. 
![image](https://user-images.githubusercontent.com/64828294/154809156-6109ee8c-060f-460f-ac45-1585d107f774.png)

**Comment by sfan5** [comment]
The same defaults also apply in singleplayer.
Also, `get_csm_restrictions` returns the features that are *restricted*. So according to your screenshot you did not disable the restrictions, therefore CSM cannot read any nodes.
