### ISSUE TITLE
Water is not rendered through clouds

### ISSUE THREAD

**Issue by Niklp09** [minetest/minetest#12082]
```
MT Version 5.5
Windows 10
Intel Core i5
Nvidia RTX 3060
OpenGL 4.6
```
-------
I happened to notice that water isn't rendered through clouds.

Repoduce:
If you fly over a sea or a river above the clouds, you no longer see the water just the bottom of the water.

![grafik](https://user-images.githubusercontent.com/89982526/154660221-0ce32e73-6445-4510-9472-1d2de548ff45.png)

**Comment by sfan5** [comment]
related #95

**Comment by lhofhansl** [comment]
Can't believe I haven't noticed this before. I can confirm this.

**Comment by Zughy** [comment]
@lhofhansl you forgot the "Bug" label

**Comment by Niklp09** [comment]
Seems to be fixed
![screenshot_20220523_203116](https://user-images.githubusercontent.com/89982526/169884152-d32de569-601b-4c03-b8ea-1a8b43ba614d.png)

**Comment by rubenwardy** [comment]
There was some changes to alpha sorting, so that makes sense!

**Comment by vvv112** [comment]
I'm more concerned about why you have 46 fps on RTX 3060
