### ISSUE TITLE
How to make a modern 5.5.0 mod.conf

### ISSUE THREAD

**Issue by BarthdryZ** [minetest/minetest#12085]
Can i get some clues on what all should we add for newer 5.5.0 suitable mod.conf when depends.txt and description.txt are depreciated. (I know it is needed for backward compatibility.) Also is there any more things to be added to the mod.conf

**Comment by rollerozxa** [comment]
[This section in lua_api.txt](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L198) contains all information about what can be in a mod.conf file. 

What used to be in depends.txt is now split into two mod.conf keys, one value which contains a comma separated list of dependencies and another one for optional dependencies (ones suffixed with question marks in depends.txt). What used to be in description.txt should be in a mod.conf key simply called "description".

**Comment by BarthdryZ** [comment]
Thanks for the information.
