### ISSUE TITLE
BUG: Minetest crashed on launch on Graphene OS

### ISSUE THREAD

**Issue by UnixPhonez** [minetest/minetest#12081]
##### Minetest version

Tested on both versions
F Droid - 5.2.0.26
Google play - 5.4.2

##### OS / Hardware
Running on google pixel 6 pro
Os - Graphene OS meaning No Google Play Services

##### Summary
App crashed upon launch

##### Steps to reproduce
Simply launch the app

**Comment by UnixPhonez** [comment]
> Do you have any chance to retrieve debug/crash logs?



-------------
  Separator
-------------

2022-02-18 16:36:49: ERROR[Main]: In thread c5930fe00000:
2022-02-18 16:36:49: ERROR[Main]: /home/ruben/dev/minetest/android/native/jni/../../../src/script/cpp_api/s_base.cpp:8c: static int ScriptApiBase::luaPanic(lua_State *): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (bad light userdata pointer)

**Comment by sfan5** [comment]
Ah yeah, there are issues with LuaJIT on arm64 which are only correctly solved on desktop (how did this ever work?).
Try the armeabi-v7a APK.

**Comment by UnixPhonez** [comment]
> Ah yeah, there are issues with LuaJIT on arm64 which are only correctly solved on desktop (how did this ever work?). Try the armeabi-v7a APK.

This version worked thanks and also any plans to update f droid versions

**Comment by sfan5** [comment]
Previous versions were not in F-Droid due to build issues, since 5.5.0 these are resolved and it's possible again. F-Droid is maintained by volunteers so it may take some time for someone to pick it up.

**Comment by UnixPhonez** [comment]
> Previous versions were not in F-Droid due to build issues, since 5.5.0 these are resolved and it's possible again. F-Droid is maintained by volunteers so it may take some time for someone to pick it up.

What do you mean by someone to pick it up? Do you mean I can update the f-droid version by uploading the GitHub release?

**Comment by sfan5** [comment]
F-Droid always builds from source, they don't accept APKs/binaries. Their build scripts need maintenance for 5.5.0 to become available.
