### ISSUE TITLE
request_http_api always returns nil

### ISSUE THREAD

**Issue by TamaMcGlinn** [minetest/minetest#12094]
##### Minetest version
```
Minetest 5.1.1 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/games/minetest"
```

##### Summary
Even after adding mod to http_mods, request_http_api returns nil

I have this in my ~/.minetest/minetest.conf

secure.http_mods = Computertest
secure.trusted_mods = Computertest
secure.enable_security = false

and the mod Computertest tries:

```
local http_api = minetest.request_http_api()
http_api.fetch({
	url = "http://localhost:7112",
	timeout = 1
}, function (res)
	if not res.succeeded then return end
	print(res.data)
end)
```

but upon starting minetest I get:

```
ModError: Failed to load and run script from /home/tama/.minetest/mods/Computertest/init.lua:
.../.minetest/mods/Computertest/entity/turtle.lua:17: attempt to index local 'http_api' (a nil value)
```

**Comment by rubenwardy** [comment]
Computertest is not a valid mod name. You probably meant `computertest`

**Comment by TamaMcGlinn** [comment]
Thanks ruben, I wouldn't have considered that as there was never any error about the mod name; the directory name is exactly Computertest and other than this code I inserted, the mod works.

**Comment by TamaMcGlinn** [comment]
I can confirm that after renaming the dir to ~/.minetest/mods/computertest it works.

**Comment by TamaMcGlinn** [comment]
@rubenwardy is there any way to make a fetch failure not show an error in minetest? I am fully expecting the fetch to fail often, and don't want to spam the player with that fact.

**Comment by rubenwardy** [comment]
I don't think that's possible. Sounds like a good new issue
