### ISSUE TITLE
"put" action from register_on_player_inventory_action doesn't work when picking up an item

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12108]
##### Minetest version
```
5.5.0
```

##### Summary
dropping an item calls `take`, but picking it up doesn't call `put`. 

##### Steps to reproduce
```lua
minetest.register_on_player_inventory_action(function(player, action, inventory, inventory_info)
  minetest.chat_send_all(action)
end)
```
and pick up some items

**Comment by SmallJoker** [comment]
This is because the feature in #12098 is yet not available. Picking up items is done by `InvRef:add_item()`.

**Comment by Desour** [comment]
Related: #7712

**Comment by Zughy** [comment]
Should this be closed? I find mine a lot shorter and straight to the point, but I'm not super partes

**Comment by SmallJoker** [comment]
#12098 provides more information and possible implementation ideas too. Closing because it's the same underlying issue.
