### ISSUE TITLE
spot when an item is added or removed from someone's inventory via code

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12109]
## Problem
There is no way to spot when an item is added or removed from someone's inventory via code. `register_on_player_inventory_action` doesn' get triggered in that case

## Solutions
Let `register_on_player_inventory_action` spot it

## Additional context
Usecase: receive a reward from an event (pushing a button, winning a minigame etc) and have a quest mod that checks for when that item is obtained

**Comment by SmallJoker** [comment]
Duplicate of #12098
