### ISSUE TITLE
Crash on Windows with unmodified 5.5.0

### ISSUE THREAD

**Issue by mbartlett21** [minetest/minetest#12100]
##### Minetest version

```
Minetest 5.5.0 (Windows)
Using Irrlicht 1.9.0mt4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: Windows 11 Pro 21H2
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz; 6 Cores; 12 Logical Processors

GPU model: NVIDIA Quadro T2000 / Intel UHD Graphics 630
OpenGL version:

##### Summary

When I click play game, Minetest loads until it gets to 'initialising nodes', then crashes.

Event viewer details:
```
Faulting application name: minetest.exe, version: 5.5.0.0, time stamp: 0x00000000
Faulting module name: minetest.exe, version: 5.5.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000000000046e884
Faulting process ID: 0x7b78
Faulting application start time: 0x01d82a47a35097f5
Faulting application path: C:\XXX\minetest-5.5.0-win64\bin\minetest.exe
Faulting module path: C:\XXX\minetest-5.5.0-win64\bin\minetest.exe
Report ID: 23343f3c-8bfd-4114-883b-caa20cfdde26
```

##### Steps to reproduce

1. Open Minetest
2. Click play game.
4. Open up Event Viewer to find out why it crashed.

EDIT: I probably should note, an older build of Minetest 5.1 works fine.
EDIT2: After testing versions, up to Minetest 5.3.0 works; 5.4.0 doesn't.

**Comment by Niklp-MT** [comment]
The debug.txt from that moment would be helpful

**Comment by SmallJoker** [comment]
1. Do newer 5.6.0-dev builds from https://gitlab.com/minetest/minetest/-/pipelines/ work?
2. If not, please narrow down the issue by finding a build before 5.4.0 that works for you -> https://gitlab.com/minetest/minetest/-/pipelines?page=19&scope=all (might be page 20, depending on when you check).
3. Run Minetest in windbg until the access violation occurs, then check the call stack. Hopefully there's meaningful information. Otherwise debug symbols would be needed, or some decompiling.

**Comment by mbartlett21** [comment]
@SmallJoker 

> 1. Try to start the game once with the Intel iGPU and again with the nvidia dGPU. Is there a difference?

No difference.

> 2. Do newer 5.6.0-dev builds from https://gitlab.com/minetest/minetest/-/pipelines/ work?

No :(

> 3. If not, please narrow down the issue by finding a build before 5.4.0 that works for you -> https://gitlab.com/minetest/minetest/-/pipelines?page=19&scope=all (might be page 20, depending on when you check).

When I go to those builds, it says that artifacts were removed a year ago.

> 4. Run Minetest in windbg until the access violation occurs, then check the call stack. Hopefully there's meaningful information. Otherwise debug symbols would be needed, or some decompiling.

I'm installing windbg now.

**Comment by mbartlett21** [comment]
> The debug.txt from that moment would be helpful

Unfortunately, it is *so* helpful:

```text
-------------
  Separator
-------------

2022-02-26 16:11:43: [Main]: Automatically selecting world at [C:\XXX\bin\..\worlds\test]
2022-02-26 16:12:09: ACTION[Main]: [experimental] on_mods_loaded()
2022-02-26 16:12:11: ACTION[Main]: World at [C:\XXX\bin\..\worlds\test]
2022-02-26 16:12:11: ACTION[Main]: Server for gameid="devtest" listening on 0.0.0.0:50551.
```

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/7db751df3bc4e3b3aff80cdacd2883f3a7a0940b/src/nodedef.cpp#L679-L682

According to Ghidra, the error is that `layer->texture` is `nullptr` for some reason. This means Minetest failed to generate a certain texture. Could you please test different games, such as Minetest Game or Devtest?

**Comment by sfan5** [comment]
I fixed this in 2020 0e698e63b3bc27551fda9bd4e66f72501413b4e6 and then accidentally(?) reverted the fix in the same year: 74762470b2aa11a5271b846549ff14b86c1705d2.
:thinking:

**Comment by Niklp-MT** [comment]
Better than if we didn't know what it was

**Comment by sfan5** [comment]
@mbartlett21 can you confirm that you have `autoscale_mode = enable` in your config? It should be the only condition under which this crash can happen.

**Comment by mbartlett21** [comment]
@sfan5 It seems I do. Is that meant to be the default configuration?

**Comment by sfan5** [comment]
It's not the default, you must have an entry in your minetest.conf.
