### ISSUE TITLE
Speed up ABMs using a node/groupname -> positions index

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12111]
## Problem

ABMs are known for their poor performance. Multiple ABMs can quickly get problematic as (I assume) a linear search needs to be done over all active mapblocks each time the ABM is executed.

## Solutions

Build a simple index of nodename -> list of active node positions. ABM performance will then become O(n) where n is the count of concerned nodes instead of O(m) where m is the count of all active nodes (usually a difference of at least 100x I'd estimate).

If memory usage of this is a major concern (only problematic with many, many groups and if this is applied to groups in the first place), this can always fall back in case the concerned nodes are "dense" (count is kept and list is only maintained if it falls below a certain percentage of all active nodes); although arguably an ABM executing for a major percentage of active nodes already sounds like a performance problem in itself.

## Additional context

Implementing this in Lua is a major hassle because there is no proper function that notifies mods of *all* node updates (including VoxelManip and `set_node`/`swap_node`/etc.). Checking for unloaded mapblocks would also have to be done periodically as there's nothing that notifies of that.

**Comment by sfan5** [comment]
> Multiple ABMs can quickly get problematic as (I assume) a linear search needs to be done over all active mapblocks

I don't think suggesting an optimization is useful before checking how the mechanism looks *right now* (I don't know either).

**Comment by TurkeyMcMac** [comment]
I think the set of node ids present in a block are cached if the block doesn't contain too many distinct node ids. So not all blocks are checked in full for every ABM.

**Comment by appgurueu** [comment]
> I think the set of node ids present in a block are cached if the block doesn't contain too many distinct node ids. So not all blocks are checked in full for every ABM.

Indeed. Albeit not exactly the same, this is most likely good enough (combined with additional optimizations found in the code such as ABMs by content ID or entirely skipping mapblocks). Let's not prematurely optimize this I guess...
