### ISSUE TITLE
Misleading documentation for minetest.encode_png()

### ISSUE THREAD

**Issue by doxygen-spammer** [minetest/minetest#12113]
The documentation for the new `[png` texture modifier says 
> #### `[png:<base64>` 
>  
>  Embed a base64 encoded PNG image in the texture string. 
>  You can produce a valid string for this by calling 
>  `minetest.encode_base64(minetest.encode_png(tex))`, 
>  refer to the documentation of these functions for details. 
>  You can use this to send disposable images such as captchas 
>  to individual clients, or render things that would be too 
>  expensive to compose with `[combine:`.

This reads as a way to convert a texture string (`tex`) to PNG data.
But this is wrong.
`minetest.encode_png()` only accepts pixel data, no texture strings.

See here:
https://github.com/minetest/minetest/blob/f2d1295fe646105f1b98b0c204f47f781336e211/builtin/game/misc.lua#L287-L298

I suggest to either support converting texture strings to PNG using this (or another) function, or to clarify this section of documentation.

**Comment by sfan5** [comment]
> This reads as a way to convert a texture string (`tex`) to PNG data.

It doesn't say that anyway, this is your interpretation.
To avoid this misunderstanding it could be reworded as "You can convert pixels to a valid string for this by calling [...]".

**Comment by doxygen-spammer** [comment]
> `minetest.encode_png()` and `minetest.encode_base64()` can be used
> together to convert pixel data to a valid string for this modifier.

This is what I have in mind instead.

Because the parameters for these functions are more complicated, I think they 
should not be given in this place.

Honestly, I do not see how I could have interpreted “tex” in any other way 
than that it accepts a texture string.

**Comment by velartrill** [comment]
specific pixel format (i assume raw array of RGBA sequences?) should also be documented

> Honestly, I do not see how I could have interpreted “tex” in any other way
> than that it accepts a texture string.

opengl dev vs modder thinking, perhaps? :) "texture" is a bit overloaded as a word, might be good to settle on consistent terminology (e.g. "tex(ture)" means a tex spec, "bitmap" means an actual raster image in whatever the standard pixel format is)
