### ISSUE TITLE
[feature] changing default permissions in singleplayer and multiplayer

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [minetest/minetest#12116]
## Problem

so yes. what makes me agry afff:
- 1 - when someone destroys blocks while im working on a map (and i need to do 2 times)
- 2 - on public servers messages are typed too fast and noone can mod it except of bans
- 3 - why i fricking dont get all privileges in singleplayer creative ?! s this game too blind that it doesnt see im working on something ?! 
- 4 - night in creative mode. WHYYYYYYYYYYYYY.................... i dont see blocks ;-;

## Solutions

yes. being able to normally disable interact and shout privs by default (they are prebuilt and even mods cant do anything)
and making mt detect if game opened in singleplayer creative and give the only player all privs
and third thing - being able to disable time in creative (in survival can be cuz there is survival)

## Alternatives

making api for these things so mods can change ALL perms (including these 'irrevokable') and pausing time from command

## Additional context

and a smol question also : someone know where is default landing point for incoming players? is it random or 0.0.0 ? is it possible to change?

PS: i cant make account on forum so im here. (got flagged as spam cause of server bugs. generally forum page is buggy. not only login)

**Comment by rollerozxa** [comment]
You can disable day/night cycle and make it permanently daytime using the [Perma Time](https://content.minetest.net/packages/_Xenon/ptime/) mod. Also, a static spawnpoint can be set and changed using the `static_spawnpoint` setting.

**Comment by hacknorris-aka-penguin** [comment]
so its static_spawnpoint? i was searching in google but didnt thought bout such name :'D thx. but anyways - guys keep joining and destroying everything while i have build-in-public... :/

**Comment by SwissalpS** [comment]
1-4 can be solved with mods and settings.

**Comment by hacknorris-aka-penguin** [comment]
yes? i can revoke modifying map by strangers? im on popos. where is da hecc file with default_privs cause sqlite editor doesnt see such rule in auth.sqlite (at me it gets saved in such). neither in map_meta.txt isnt such code...

**Comment by hacknorris-aka-penguin** [comment]
and world.mt contains only this : 
```
enable_damage = false
creative_mode = true
auth_backend = sqlite3
player_backend = sqlite3
backend = sqlite3
gameid = minetest
world_name = parkour
```
and list of disabled mods

**Comment by hacknorris-aka-penguin** [comment]
is this content of world.mt correct? (im not sure bout last line)
```
enable_damage = false
creative_mode = true
auth_backend = sqlite3
player_backend = sqlite3
backend = sqlite3
gameid = minetest
world_name = parkour
load_mod_visible_sneak = false
load_mod_techpack_stairway = false
load_mod_stairs = false
load_mod_respawn = false
load_mod_proxchat = false
load_mod_multihome = false
load_mod_mesecons_wireless = false
load_mod_mesecons_carts = false
load_mod_mesecons_torch = false
load_mod_postool = false
load_mod_mesecons_switch = false
load_mod_mesecons_wires = false
load_mod_mesecons_stickyblocks = false
load_mod_mesecons_solarpanel = false
load_mod_mesecons_random = false
load_mod_mesecons_receiver = false
load_mod_mesecons_powerplant = false
load_mod_mesecons_noteblock = false
load_mod_mesecons_mvps = false
load_mod_mesecons_microcontroller = false
load_mod_mesecons_luacontroller = false
load_mod_xconnected = false
load_mod_moreblocks = false
load_mod_home_vending_machines = false
load_mod_mesecons_detector = false
load_mod_computers = false
load_mod_nextgen_compass = false
load_mod_steles = false
load_mod_fs51 = false
load_mod_mesecons_insulated = false
load_mod_signs_road = false
load_mod_ontime_clocks = false
load_mod_mcl_chests = false
load_mod_formspec_ast = false
load_mod_mesecons_blinkyplant = false
load_mod_boards = false
load_mod_home_workshop_machines = false
load_mod_digiterms = false
load_mod_mesecons_movestones = false
load_mod_font_metro = false
load_mod_display_api = false
load_mod_controls = false
load_mod_unifieddyes = false
load_mod_mcl_util = false
load_mod_basic_houses = false
load_mod_digiscreen = false
load_mod_home_workshop_misc = false
load_mod_mesecons_delayer = false
load_mod_handle_schematics = false
load_mod_plasterwork = false
load_mod_mesecons_pistons = false
load_mod_signs = false
load_mod_coins = false
load_mod_led_marquee = false
load_mod_mcl_blackstone = false
load_mod_basic_materials = false
load_mod_lwcomputers = false
load_mod_mesecons_doors = false
load_mod_mcl_copper = false
load_mod_lwscratch = false
load_mod_maple = false
load_mod_maptools = false
load_mod_mesecons_commandblock = false
load_mod_mesecons_pressureplates = false
load_mod_mcl_deepslate = false
load_mod_mcl_glass_doors = false
load_mod_mesecons_materials = false
load_mod_mcl_more_ore_variants = false
load_mod_memeblocks = false
load_mod_mcl_raw_ores = false
load_mod_stairpick = false
load_mod_font_api = false
load_mod_mesecons = false
load_mod_mesecons_lightstone = false
load_mod_mesecons_alias = false
load_mod_mesecons_button = false
load_mod_mesecons_walllever = false
load_mod_digilines = false
load_mod_signs_api = false
load_mod_mesecons_extrawires = false
load_mod_mesecons_fpga = false
load_mod_mesecons_gates = false
load_mod_mesecons_hydroturbine = false
load_mod_mesecons_lamp = false
server_announce = true
static_spawnpoint = -191.6, 13.1, 265.3
```

**Comment by SwissalpS** [comment]
> yes? i can revoke modifying map by strangers?

There are protection mods which allow you to protect areas from being edited by unauthorized players.
[This one is quite popular: areas](https://github.com/minetest-mods/areas)

I don't understand the rest of that post. Why are you browsing the database? Players don't get individual access to it. Minetest server edits database independant from who is modifying nodes in world.

You can grant yourself creative priv in singleplayer by simply typing ``/grantme creative`` and revoke it again with ``/revokeme creative``

**Comment by rubenwardy** [comment]
> 1 - when someone destroys blocks while im working on a map (and i need to do 2 times)

You need to install an area protection mod, such as [areas](https://content.minetest.net/packages/ShadowNinja/areas/) or [protector](https://content.minetest.net/packages/TenPlus1/protector/).

> 2 - on public servers messages are typed too fast and noone can mod it except of bans

There is already a limit for number of chat messages per 10 seconds, and it defaults to 8. See the `chat_message_limit_per_10sec` setting in Settings > All Settings / minetest.conf.

> 3 - why i fricking dont get all privileges in singleplayer creative ?! s this game too blind that it doesnt see im working on something ?!

You need to use `/grantme all` to get all privileges. It doesn't give all privileges by default, as creative may be used on servers and so granting all privileges would allow players to take over the server

> 4 - night in creative mode. WHYYYYYYYYYYYYY.................... i dont 

You can use `time_speed = 0` in minetest.conf

> yes. being able to normally disable interact and shout privs by default (they are prebuilt and even mods cant do anything)

You can change `default_privs` to not give interact or shout. Doing this by default doesn't make any sense

> making api for these things so mods can change ALL perms (including these 'irrevokable') and pausing time from command

See minetest.registered_privileges and minetest.set_player_privs. You can change `give_to_singleplayer/admin` in the priv definition to true to make it irrevocable, or to false to make it revocable

**Comment by hacknorris-aka-penguin** [comment]
thx. (but if bout area protector. would you maybe make it preinstalled? pls)

**Comment by SwissalpS** [comment]
> would you maybe make it preinstalled

Minetest is the engine that provides the API for games to interact with.  
There are [several base games](https://content.minetest.net/packages/?type=game) you can install and [extend using mods](https://content.minetest.net/packages/?type=mod).

**Comment by hacknorris-aka-penguin** [comment]
your saying i should play in singlenode mode? :'D

**Comment by SwissalpS** [comment]
That is not what I'm saying, but feel free to do so.

I'm trying to explain how minetest (engine) relates to mods (modules) and games (preset base worlds).

This repo is about the engine which will not add mods at all. If anything, request mods to be added by default to your game's repo :)

**Comment by hacknorris-aka-penguin** [comment]
ok. fine =]
