### ISSUE TITLE
Minetest takes too long to launch, no audio

### ISSUE THREAD

**Issue by Montandalar** [minetest/minetest#12126]
**I have also tried Minetest from the Debian repositories and it's experiencing the same issues. I think I will have to report this at the debian-user mailing list...**

##### Minetest version
```
#Also occurs for 5.5.0
Minetest 5.6.0-dev-ad7c72c16 (Linux)
Using Irrlicht 1.9.0mt5
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

Debian package:
```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.5
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/usr/share/games/minetest"
STATIC_LOCALEDIR="/usr/share/locale"

```

##### OS / Hardware

Operating system: Debian Bookworm
CPU: AMD Ryzen 3 2200G

##### Summary
When building my own Minetest lately, the resulting executable takes a very long time (15 seconds?) to start, eventually fails to open the OpenAL device and then starts without audio. It also produces the line "BDB1539 Build signature doesn't match environment", which apparently relates to the Berkeley Database, not sure how it's related to Minetest. The BDB message comes before it tries to open the OpenAL device (see transcript below).

I am up to date for bookworm packages as of 2022-03-10 17:00 UTC, even for dist-upgrade items.

Now there's a few suspicions I have about some possible causes:

1. Debian Bookworm's gcc or Berkeley Database is just plain borked at the moment. It's debian testing after all, not stable. Not likely given I can build other C++ software like minetestmappergui.
2. Bookworm has borked OpenAL for certain usecases. I don't know if I use any other OpenAL applications. I mostly use YouTube on Firefox and games on Steam and sometimes VLC, but surely at least one of these applications uses OpenAL? Do the HDMI audio devices on my graphics card have any relevance?
3. Something went wrong with a recent update of Minetest via apt, that would have backdated 5.5.0 self-build and installed through `dpkg -i` back to the current 5.4.1-repack2. Not likely given that this issue is much newer than the latest commit by the [Debian Games Team](https://salsa.debian.org/games-team/minetest/).
4. My installation of Resynthesizer for GIMP (which may have been a dumb `make install`) is interfering with the removal of the Minetest package by having other files in `/usr/local/share/locale/*`. Unlikely since if the directory is still there surely apt can still complete the rest of the removal correctly?

##### Steps to reproduce
I've attached a terminal transcript of purging, git cloning, building with defaults, making a deb, installing it and hitting the error. Let me know and I could fire up a Debian VM and try to see if a new install of bullseye and then an upgrade to bookworm would work without problem.

[typescript.txt](https://github.com/minetest/minetest/files/8225656/typescript.txt)

**Comment by Montandalar** [comment]
In short: There was a regression in wireplumber, which made it so OpenAL using pulse-pipewire into Minetest was failing. It is fixed and will be in Debian unstable soon. In the meantime, you can ask OpenAL to use ALSA instead and Minetest and any other OpenAL applications that behave similarly will work fine. More info at the links below.

Debian Bug Report filed: [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007100)
Workaround: [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2189#note_1284590)
Fixed commit: [here](https://gitlab.freedesktop.org/pipewire/wireplumber/-/commit/afbc0ce57aac7aee8dc1651de4620f15c73dbace)

**Comment by sfan5** [comment]
> I mostly use YouTube on Firefox and games on Steam and sometimes VLC, but surely at least one of these applications uses OpenAL?

Not necessarily . Applications other than games do not have a reason to use OpenAL (especially not video players), proprietary games might have their own stuff or force ALSA.

Closing as it's been figured out.
