### ISSUE TITLE
--console not working in 5.5.0 (windows)

### ISSUE THREAD

**Issue by VorTechnix** [minetest/minetest#12121]
Calling `minetest.exe --console` does not run minetest within a cmd or powershell instance but launches it as a separate, external window just like calling `minetest.exe` by itself does.
![image](https://user-images.githubusercontent.com/45538536/156942082-6ebcae2c-aae1-4c52-8ae7-15af5ba007fe.png)
![image](https://user-images.githubusercontent.com/45538536/156942228-19ffffdf-bde3-49a1-aa91-de069f7b6bc6.png)

**Comment by wsor4035** [comment]
to clarify the above, the issue is that on windows, in minetest 5.4 you can do minetest.exe --console to launch a minetest instance from the terminal and can see the log there. in 5.5 this is broken as it just launches as a minetest instance like minetest.exe would with no terminal output at all.

**Comment by wsor4035** [comment]
additional testing has found out that minetest --help states --console is windows only as it runs on linux.

**Comment by sfan5** [comment]
possibly related https://github.com/minetest/minetest/issues/11106
it's unclear to me why `--console` would have worked at all or what would have influenced it

> additional testing has found out that minetest --help states --console is windows only, but it actually runs on linux as well

Not really. It doesn't do anything at all on Linux, but you're probably already running it from a terminal.

**Comment by VorTechnix** [comment]
I don't think this is related to #11106 because, as seen in my screenshots, `--version` works in powershell in 5.5 and this bug also shows up in cmd unlike 11106 where OP said "With cmd it works correctly (but does not appear to return).".

>it's unclear to me why --console would have worked at all or what would have influenced it

I don't think it did. On linux the default (possibly only) behavior is to run in console. When @wsor4035 tried it I think `--console` did nothing and minetest started as it normally would in linux.

Back to the original problem though: any ideas why `--console` isn't working in windows in version 5.5 in either powershell or cmd?

**Comment by VorTechnix** [comment]
Tried `minetest.exe --console` with minetest v5.5.1. Bug persists. Minetest opens outside of cmd and powershell as with 5.5.0.

**Comment by VorTechnix** [comment]
Seems to be working again as of latest version (5.7.0).
