### ISSUE TITLE
Odd shadows on slabs

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest#12127]
##### Minetest version
```
5.6.0-dev-ad7c72c16
```

##### OS / Hardware

Operating system: Linux Mint 20.2
CPU: Intel i7-8700K

GPU model: Nvidia GTX 1060 6GB
OpenGL version: 4.6.0

##### Summary
Shadows on slabs have odd banding, most noticeable in early morning in an area without artificial light. This seems to be a recent issue, as my build from a few days ago didn't have this issue.

##### Steps to reproduce
Enter Dev-test, or any game honestly, place slabs, set time to 6000 observe weird lighting artifiacts.
![screenshot_20220310_200408](https://user-images.githubusercontent.com/8930456/157788365-6b5b2ebd-f629-4f03-b038-68c3ed8977da.png)

**Comment by x2048** [comment]
Just for information, the issue is introduced in b651bbf44639b9bdd1d5ef581acb57fd47cc6b7a.

Right now I am re-tuning all shadow mapping for the new distortion function from #12166, with offset code changed in #12191. Filtering will change in #12195 and conclude the update, after which I will take a look at the issue if it is still there.

**Comment by IrrlichtMt4** [comment]
I remember something similar that would occur in 0.4.13 when some snow layers would have black edges on the sides of the blocks. This would happen also happen with slabs I think.

**Comment by x2048** [comment]
#12262 Reduces the impact of this issue on snow and other groups of slabs of the same time.

**Comment by x2048** [comment]
@NathanSalapat Do you still experience the problem or can we close the issue, as it is fixed for most cases of slabs?

**Comment by NathanSalapat** [comment]
Shadows look correct on slabs now, not sure how long they have, so this can be closed.
