### ISSUE TITLE
renaming singlenode mapgen

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [minetest/minetest#12136]
## Problem

so yes singlenode was meant to contain only one type of node at start. IT IS NOT.
why? every map in minetest is ending with other node named ignore which prevents moving outside of map. so even singlenode mapgen contains two types of nodes : air and ignore (at world boundaries). 

## Solutions

creating mapgen made only from ignore, so it'll be real singlenode and renaming singlenode to doublenode (or something like that) 

## Alternatives

just renaming singlenode to doublenode 

## Additional context

resources:

https://wiki.minetest.net/World_boundaries

https://wiki.minetest.net/Ignore

https://wiki.minetest.net/Map_generator

https://wiki.minetest.net/Map_Generator_Evolution

**Comment by hacknorris-aka-penguin** [comment]
jeez. biggest mistake ever...

**Comment by sfan5** [comment]
The singlenode mapgen does not place any ignore nodes, so what you said is technically incorrect.
This is a stupid suggestion regardless.

**Comment by Desour** [comment]
> just renaming singlenode to doublenode

What about "floatnode", because there's no ground, so every node that you place will float in the air?

**Comment by hacknorris-aka-penguin** [comment]
> The singlenode mapgen does not place any ignore nodes, so what you said is technically incorrect. This is a stupid suggestion regardless.

yes it places. at world boundaries. not even mapgen. minetest core by itself.

**Comment by hacknorris-aka-penguin** [comment]
and i dont think singlenode is infinite.... (probably have same size as other maps - aka 30927^3 nodes)
