### ISSUE TITLE
adding ignore node to development test game

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [minetest/minetest#12134]
## Problem

so yes. development test is a technical map. for the now didnt saw anyone sharing such server, so i think more risky nodes can be placed (its only for tests, yea? name says). i know ignore node is blocked in core of mt. i dont think that ignore is TOO MUCH risky tbh and could be placed in one test world. its just a wally air. there exist already mods for other worlds which work exactly the same (look for example at [this](https://content.minetest.net/packages/Truemmerer/invisible_blocks/) )

## Solutions

adding ignore node to minetest development test 'game' (only)  ¯\_(ツ)_/¯

## Alternatives

making a similar non-destroyable walkable and invisible node 

## Additional context

yes i know it'll be closed soon cause of your 'security' ;p just take it as idea, not as real important request

**Comment by rollerozxa** [comment]
There already exists an airlike test node in devtest.

**Comment by rollerozxa** [comment]
It's probably out of scope for devtest, as this would not be useful neither for testing the engine or mods, and also interferes with the fact devtest is supposed to give minimal interference by default (see [devtest design philosophy](https://github.com/minetest/minetest/tree/master/games/devtest#design-philosophy)), I feel overwriting core functionality such as a built in dummy node behaviour would not be a good idea in that regard.

**Comment by hacknorris-aka-penguin** [comment]
so why there exist unknown node to place? also air and few others...
