### ISSUE TITLE
Please, add nintendo switch version

### ISSUE THREAD

**Issue by vvv112** [minetest/minetest#12147]
(Sorry my bad english)
Minetest is not realesed on nintendo switch.

Please realese it if it's not difficult

**Comment by rollerozxa** [comment]
Someone was actually working on a Switch homebrew port of Minetest but I haven't heard any news about it recently.

**Comment by 3DSdev** [comment]
You can just make a Homebrew port (who cares about getting official?)

**Comment by vvv112** [comment]
This?

**Comment by vvv112** [comment]
sorry if I'm bored

**Comment by 3DSdev** [comment]
No, something like https://devkitpro.org where you can make your own Wii, 3DS, DS, Gamecube, and Switch Homebrew.

**Comment by Emojigit** [comment]
I think it's not logically difficult. We can just reuse a lot of current codes related to joysticks, the toughs tasks are the drivers and compiler-related stuff.

**Comment by rubenwardy** [comment]
I don't see this as being a priority right now, this is a fairly large task and has some big obstacles in the way.

From what I've heard, the Switch SDK requires signing an NDA and we wouldn't be able to open source the implementation. I also doubt any of the devs have a switch. As for any platform, we're open to receiving patches to fix issues on it - but we're unable to support Switch officially at this time

**Comment by rollerozxa** [comment]
> If we wanted to port this to the Switch we could just use ​something like [DevKitPro](https://devkitpro.org/) to port it to the Switch as open source homebrew without using any official SDK tools.

[This has already been done.](https://github.com/emmauss/minetest) (Or well, it was never finished but you can still in fact get to the main menu and potentially in-game albeit with some additional work needed to fix the SQLite database)

**Comment by vvv112** [comment]
you can create a separate closed source project (for example, switch test) and upload it to the nintendo Eshop

**Comment by DraconicNEO** [comment]
> you can create a separate closed source project (for example, switch test) and upload it to the nintendo Eshop

I think that's a horrible idea, minetest isn't the kind of project that suited for a closed source eShop release (we already have Minecraft for that and some of its other clones) minetest is more suited as a Homebrew app that way it could stay free and open source, and most importantly could retain the features that it has on other platforms that otherwise would not be allowed on switch due to security concerns from Nintendo.

**Comment by rollerozxa** [comment]
> > you can create a separate closed source project (for example, switch test) and upload it to the nintendo Eshop
> 
> I think that's a horrible idea.

It would just be straight up illegal.

**Comment by DraconicNEO** [comment]
> > > you can create a separate closed source project (for example, switch test) and upload it to the nintendo Eshop
> > 
> > 
> > I think that's a horrible idea.
> 
> It would just be straight up illegal.

Absolutely, minetest is GPLv2 so making a closed source version of it would violate the license.

Why is it that the OP and Minetest developers are so insistant on using the official SDK and publishing to the eShop? Why? Minetest is an open source app so therefore it should be implemented as open source, unofficial Homebrew. Don't have Homebrew and only want to get things from the eShop there are already closed source alternatives to minetest on there already.

**Comment by hopepill** [comment]
> Why is it that the OP and Minetest developers are so insistant on using the official SDK and publishing to the eShop? Why? Minetest is an open source app so therefore it should be implemented as open source, unofficial Homebrew.

this.
