### ISSUE TITLE
Saner settings UX proposal

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12140]
# In short

## Problem

Settings tab and advanced settings section have poorly designed UX

## Solution

![image](https://user-images.githubusercontent.com/2122943/175824254-7ea93ad4-f600-40ae-9d6e-02684291d36a.png)

Remove the settings/advanced settings difference, and implement something easily understandable and browsable like this:
<img alt="imagen" src="https://user-images.githubusercontent.com/63455151/159117646-7300d1bb-5019-40c2-8404-8e75db64e32f.png">
*Minecraft Bedrock Edition*

---

# In depth

## Preamble
This research was made by @G1ov4 and I, in a span of 3 days, trying to make sense of how the settings tab and the advanced settings section are structured. During our research, we discovered several things we had no idea Minetest could do, but also a poorly designed UX (and UI) that required us days to fully understand and try to clean up (a couple of hours per day). We believe that things like settings should be easy to grasp and navigate, simply communicating to the end user what they can and cannot tweak. We start by listing the problems we encountered, prioritising the ones relative to UX, followed by a couple questions always related to settings in general. We then proceed with our proposal to tackle the current situation, offering our help to make a mock-up in case the analysis is well-received (we won't code it though).
Last but not least, reported settings names can be slightly different, as we didn't use the English version of the client.

## UX problem(s)

1. **Current advanced settings are a poorly designed list of categories and subcategories**
A few examples:  
`+Server / Singleplayer > +Advanced > +Profiler > +Tools > +Advanced > stuff`
`+Graphics > +Menus > several screenshot settings`  
`+Graphics > +In game > +Filters > Bilinear filter (bool) AND Trilinear filter (bool)`

2. **Fields that need prerequisites to affect the engine appear even when those prerequisites are not met**
A few examples:
`enable_console` (for Windows only, but it appears on Linux too)  
`screenshot_quality` (for JPEG screenshots only, but it appears even when screenshots are set to PNG)

3. **Everything is listed, no matter the relevance or if there are more practical ways to edit an entry**
A few examples:  
`show_debug` (the one that changes pressing F5)
`enable_sound` (see #12138)

4. **Everything is listed in the same place**
Advanced settings doesn't only contain entries to change things like graphics and controls, but also entries to change things like ContentDB, terrain generators and installed games settings; making the list twice its actual length.

## Other related considerations

1. **Why things like default chat and formspec aspect are tweakable by the client?**
Shouldn't these things be up to the server? `+Graphics > +In game > +Advanced` contains several options to mess around with graphical elements of the game, like making default formspecs background transparent. Also, they don't seem to be coherent (screen sent by @wsor4035 on Matrix, where the default formspec background was set to blue)
![imagen](https://user-images.githubusercontent.com/63455151/159122354-60719cd8-8902-40b7-a7e2-c2d55294fcb4.png)

2. **Aren't parameters like changing block placing interval a way of cheating?**  
Editing `+Controls > Place repetition interval` to something like `0.05` makes people build like they were Flash. The same logic applies to the previous question.

## Proposal
Taking inspiration from the Minecraft Bedrock Edition screen, we'd like to introduce a cleaner implementation of the settings tab, merging that and the advanced settings section into one single entity.  
To tackle **problem n°1**, we thought of the following categories, appearing on the left part of the window (where the upper category is not a button but just the name of the section):
* Controls
  * General (no clip, jump twice to fly etc)
  * Keybindings
  * Mouse and keyboard (mouse sensitivity, invert mouse etc)
  * Joystick
  * Touch
* Graphics and Audio
  * Graphics (UI size, clouds no/2D/3D etc)
  * Audio 
  * Shaders (filter no/bilin/trilin, mipmap etc)
* Coding
  * Mods (client modding, safe mods only etc)
  * Developer area (whatever is advanced and the average user would probably never touch)
  
We could also add an "About" category to merge the "About" tab, but it's not that relevant right now, and of course names can be improved.  
Having a window like that would also spare Minetest from having custom formspecs in the in-game pause menu, like it currently does with the sound settings. Also, to make booleans more readable, we wanted to change the MC switches to something like this
![imagen](https://user-images.githubusercontent.com/63455151/159125485-6e5b92d5-9281-4b49-a314-45b58ccccc1b.png)

so that the green instantly tells the user that something is active.

To tackle **problem n°2**, we can simply hide parameters with unmet prerequisites, only showing them when met.  

To tackle **problem n°3**, we have written down a list of entries that in our opinion shouldn't appear in game:
* `show_debug` (the F5 boolean)
* `enable_sound` (#12138)
* `serverlist_file` the JSON containing the list of our favourite servers. Why not making it a standard like the `debug.txt` file and make this an internal variable only?
* options like the last server visited, last name used etc.: they already appear in the dedicated section, where are way easier to edit

And another list of things that we don't understand why they exist in the first place:
* all chat/formspec customisations due to consideration n°1 and 2. It remains the problem of Minetest accessibility (which is already very bad), but in our opinion it should be tackled with a different approach, like post-processing filters and UI scaling
* ~the placing nodes interval (`repeat_place_time`), due to consideration n°2~ fixed by #12450
* `aux1_descends`, to make AUX1 to behave exactly like the sneak button. Why?
* `texture_min_size`: why should someone use the bilinear/trilinear filter with small pixelated textures?

To tackle **problem n°4**, we suggest to move some settings in their respective place. For instance: CDB settings should be accessible from the CDB section, games settings from the single player tab, same for the local server settings, and terrain generator settings from the world creation menu, giving the possibility to save the current modified settings as the new default.

As said in the preamble, we'd like to know from you what you think, so that in case of a well-received sentiment, we can realise a mock-up to then discuss UI too.

---

NOTE: before you comment, we'd like to underline that this is not a graphical issue, it's a user experience one. Please don't fill the thread with comments that are not related to the UX

**Comment by Desour** [comment]
* All problems (currently) mentioned in the "UX problem(s)" section are just applying to the All Settings menu.
  That the basic settings menu needs to be improved and enlarged is well known.
  Something like the All Settings menu, that hides nothing, and hence ie. lists all settings descriptions, should stay there. But it should take in a role of being uninteresting to normal players.
* The only way to make the basic settings menu sufficient, even in the future, is to create it (semi-)automatic.
* > 2 . Aren't parameters like changing block placing interval a way of cheating?
  > Editing +Controls > Place repetition interval to something like 0.05 makes people build like they were Flash. The same logic applies to the previous question.
  
  `repeat_place_time` just influences the place interval when you hold the mouse button. You can still spam right-click.
  If a limited place interval is required, the server should tell that to the client and (if anticheat) check it itself. But that's offtopic here.
* Removing old settings, just because you and me don't understand why anyone would use them, is a bad idea, as it's mean to those that do use the setting, we should avoid to be that evil. Ie. `aux1_descends` is used by VanessaE, afaik.

**Comment by rubenwardy** [comment]
I've been thinking about this exact thing for a while, the layout there is common to most games not just Minecraft Bedrock

I agree that it would make a lot of sense to combine basic and all settings, and I'd like an advanced settings checkbox to hide the more complicated settings

**Comment by martin-desktops** [comment]
I would like to play with it and do some UI prototypes.
Is there a style I should stick to? If no, I think it would be worth to raise the issue of the UI style maybe in a different issue. Redesigning the interface would be a perfect moment for finding a better matching style for it.

**Comment by rubenwardy** [comment]
I've already implemented this, see the associated PR

**Comment by therealbluepandabear** [comment]
Minetest needs better ui
