### ISSUE TITLE
Accumulation of positions in the liquid queue client-side

### ISSUE THREAD

**Issue by TurkeyMcMac** [minetest/minetest#12144]
##### Minetest version

Not relevant.

##### OS / Hardware

Not relevant.

##### Summary

In `addNodeAndUpdate`, positions are sometimes added to the liquid update queue. However, on the client side, these positions never seem to be removed, so they just accumulate.

##### Steps to reproduce

Add a debug statement to the end of `addNodeAndUpdate`:

```cpp
if (mapType() == MAPTYPE_CLIENT)
    errorstream << m_transforming_liquid.size() << std::endl;
```

**Comment by sfan5** [comment]
:exploding_head:
