### ISSUE TITLE
ur site borked !!!

### ISSUE THREAD

**Issue by hacknorris-aka-penguin** [minetest/minetest#12151]
better check your forums before answering!!!

and make me an acc with my mail !!!

(i know why i ask)

**Comment by rubenwardy** [comment]
Hi, what's your username?

**Comment by hacknorris-aka-penguin** [comment]
im not having (means - banned)

**Comment by rubenwardy** [comment]
Ah, are you being rejected by the antispam? You can send me an email at rw@rubenwardy.com and I can take a look

**Comment by hacknorris-aka-penguin** [comment]
did alr

**Comment by rubenwardy** [comment]
closed as continuing in email
