### ISSUE TITLE
Command line window always start

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#12165]
##### Minetest version

```
5.6 dev
04bd253390cc6c67a555e4837e7e48d524fdf014 - Move the codebase to C++14 
```

##### OS / Hardware

Operating system: Windows 7
CPU:

GPU model:
OpenGL version:

##### Summary

Since the commit mentioned above, minetest always start with the command line window whether enable_console is true/false
##### Steps to reproduce

Just start minetest

**Comment by wsor4035** [comment]
windows 7 is EOL (end of life). additionally, according to https://www.minetest.net/downloads/ "Works on Windows 8, 8.1 and 10. May work on older versions, but not officially supported."

**Comment by waxtatect** [comment]
_for your satisfaction_

just tested on windows 11 (including all latest updates)
same issue

**Comment by IrrlichtMt4** [comment]
Can confirm.

**Comment by Niklp09** [comment]
Latest Windows 10, same problem

**Comment by sfan5** [comment]
Whether Windows makes the console window appear depends on how Minetest was compiled. Where did you get your build?

**Comment by waxtatect** [comment]
Using minetest gitlab artifacts
