### ISSUE TITLE
Feature flag for raw binary data in mod storage

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#12167]
## Problem

As noted [on the forums](https://forum.minetest.net/viewtopic.php?p=408567#p408567) by @Montandalar, the following documentation, about mod storage `StorageRef`s being incapable of holding raw binary data, is probably incorrect for sqlite and dummy backend since #11763 (correct?):
https://github.com/minetest/minetest/blob/837cea6b4a2315966b9670ae50cff9d3679bcff4/doc/lua_api.txt#L7233-L7234

## Solutions

Add a feature flag (in `minetest.features`) which states whether raw binary data is allowed in mod storage (true if sqlite or dummy backend is used).

## Alternatives

Idk.

## Additional context

(It might be worth noting that migrating back to json will then be able to fail.)

cc @TurkeyMcMac

**Comment by TurkeyMcMac** [comment]
The SQLite backend should be able to store binary data, since it stores data as `BLOB`s.

**Comment by rubenwardy** [comment]
Mod storage is a form of meta data, which is a string only key-value store. So the only way to have binary data is to make it into a std::string

What values are there that JSON can't contain? JSON has an escaping system with support for hex literals for bytes and code points

**Comment by TurkeyMcMac** [comment]
I haven't tested, but the JSON library might mangle bytes trying to fit them into UTF-16.

**Comment by Desour** [comment]
( #8914 introduced the doc.)

Tested, UTF-16 seems indeed to be a problem.

If I do for example:
```lua
local mod_storage = minetest.get_mod_storage()

local str = "baum\xe4birne"

local str_loaded = mod_storage:get_string("apfel")
print(str == str_loaded and "it's the same" or "different")
print("str:        ", str:byte(1, -1))
print("str_loaded: ", str_loaded:byte(1, -1))

mod_storage:set_string("apfel", str)
```
It stores:
```
{"apfel":"baum\u48a9rne"}
```
And prints:
```
different
str:        	98	97	117	109	228	98	105	114	110	101
str_loaded: 	98	97	117	109	228	162	169	114	110	101
```

-----------------------------

> Mod storage is a form of meta data, which is a string only key-value store. So the only way to have binary data is to make it into a std::string

But lua strings are arbitrary raw binary data.
And the strings are already converted into `std::string`:
https://github.com/minetest/minetest/blob/837cea6b4a2315966b9670ae50cff9d3679bcff4/src/script/lua_api/l_metadata.cpp#L116-L119

**Comment by Desour** [comment]
> A feature flag would be the wrong approach here, you don't want to burden mods with somehow manually checking which backend is being used.
> Ideally all backends or _no_ backends would be binary safe.

My thought was that mods would add something like this in their `init.lua`:
```lua
assert(minetest.features.mod_storage_raw_binary, "Mod doesn't work with old mod storage backend.")
```
And then they can be sure that saving binary data is possible.

AFAIK, it is already the case that all non-deprecated mod storage backends nowadays are binary safe. (It's a feature of new minetest versions. => feature flag)

What other approach than a feature flag would there be?

**Comment by TurkeyMcMac** [comment]
One option would be to document the discrepancy then do something like this:

```lua
local world_settings = Settings(minetest.get_worldpath() .. "/world.mt")
local mod_storage_backend = world_settings:get("mod_storage_backend") or "files"
assert(mod_storage_backend ~= "files", "Mod doesn't work with old mod storage backend.")
```

**Comment by sfan5** [comment]
> My thought was that mods would add something like this in their `init.lua`
> And then they can be sure that saving binary data is possible.

You want a feature flag that is set dynamically depending on the backend?

> One option would be to document the discrepancy then do something like this:

This is bad hack, not something we should tell modders to do. It exposes implementation details and is incompatible to future changes of backend settings, new backends or changed to existing backends.

This is why I said it should either be always or never supported.
Modders presumably do not want to make their mods incompatible to some mostly opaque detail of the world format so will need to add fallback code anyway. But if you have fallback code why have code that requires binary-safety anyway?

**Comment by TurkeyMcMac** [comment]
How about encoding binary data in base64 and differentiating binary strings from normal ones by putting `\u0000` (NUL) at the beginning of binary strings. I don't think this would mangle preexisting data since any such data that contained NUL would count as binary data and would thus have been invoking unspecified behavior before.

**Comment by Desour** [comment]
> You want a feature flag that is set dynamically depending on the backend?

Yes.

**Comment by Montandalar** [comment]
Seeing as all non-deprecated modstorage backends are deprecated as Desour said, we could just wait until those backends are completely dropped to then set the feature flag to true. That way it isn't dynamically changing.

**Comment by TurkeyMcMac** [comment]
Actually, I don't think mod storage can store arbitrary binary data, even with the SQLite3 backend. Consider mod storage with the following key-value pairs:

```
foo=1
bar=${foo}
```

Trying to get the value of the key `bar` here will return `1`, due to the special `${}` syntax. Therefore, mod storage cannot reliably store arbitrary binary data.

**Comment by Desour** [comment]
I always thought you could just use the `${foo}` thing in formspecs. (Also, I haven't found doc for it anywhere else than for the `field[]` formspec element.) How does that thing even actually work?

**Comment by TurkeyMcMac** [comment]
Yeah, I don't think it's documented anywhere. I found it by looking at the code. Basically, if the value of key `a` is set to `${b}`, then getting the value of `a` will return the value of `b`. Personally, I think the `${}` syntax should only work in formspecs, since it makes getting values less predictable. I guess it can't be removed now, though. I wonder what the original use-case was.

**Comment by Montandalar** [comment]
Variable references are only documented in one place in the documentation, which is in the docs for `field[]` formspec elements. It does seem strange that that logic should be applied outside of the context of formspecs - but you should file a separate issue for that.
