### ISSUE TITLE
Unneeded setters return

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12177]
## Problem

Half of the setters in `l_object.cpp` (and possibly in other API files) return a boolean (e.g. `set_sky`, `set_local_animation`) and half don't (e.g. `set_velocity`, `set_fov`)

## Solutions

As a modder, those booleans are useless. Being undocumented, I suggest to remove them

## Alternatives

Document it (please no)

**Comment by runsy** [comment]
I would prefer to be documented than remove them. Return values are useful in programming -> Ie you can set a var with a return value.

**Comment by appgurueu** [comment]
> I would prefer to be documented than remove them. Return values are useful in programming -> Ie you can set a var with a return value.

Yes, return values are useful. The point of this is not the removal of return values altogether, but rather the removal of useless *setter* return values which are *extremely uncommon* and (I assume) just dead copypasta code.

Even if you wanted a return value for "success" checking, you probably wouldn't want "no-op" to be the default on error; it should rather throw, forcing the modder to "catch" (pcall) if they want to hide the error.

These functions literally just return whether the player object is valid, which you can already check using `player:is_player()`.
