### ISSUE TITLE
Head Movement

### ISSUE THREAD

**Issue by DreamBoi8** [minetest/minetest#12175]
## Problem

I can't nod.
## Solutions

I want the players head to be able to me corresponding to the direction they are look. So I could look up then down and it'd look like I'm nodding.

## Alternatives

Maybe a mod?

## Additional context

Nothing

**Comment by rollerozxa** [comment]
> Maybe a mod?

Maybe a mod indeed, see: [headanim](https://content.minetest.net/packages/Lone_Wolf/headanim/)

**Comment by Zughy** [comment]
Duplicate of #1800

**Comment by rubenwardy** [comment]
Duplicate of https://github.com/minetest/minetest/issues/1800
