### ISSUE TITLE
Black Wield Item

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#12180]
##### Minetest version
v5.6 development

##### OS / Hardware
Linux

##### Summary

Black Wield Item when "inside" the node, but not really inside. I mean a node no 1x1x1, but a small one, in my example a centered door. In both sides, black.

![black wield item](https://user-images.githubusercontent.com/13217027/162046629-ebdb2622-7a44-425f-afda-f2c2f4796a6f.png)

Not in 5.5, but yes in new 5.6-dev.

Not shadows enabled.

##### Steps to reproduce
A centered door or another node not 1x1x1, but less.

**Comment by runsy** [comment]
Well this is due th wild item trespassing the object.

**Comment by sfan5** [comment]
Do you have `paramtype = "light"` set?
It would be useful to provide a minimal Lua example needed to reproduce.

**Comment by runsy** [comment]
Some not quare nodes appoears black in any siatuation too:

![black_wield_item](https://user-images.githubusercontent.com/13217027/162379466-116ff6f4-c953-4ac5-9119-b64b3376f132.png)

**Comment by runsy** [comment]
When I release The Samz. I put a link here to check it.

**Comment by runsy** [comment]
> Do you have `paramtype = "light"` set?

Yes.

**Comment by runsy** [comment]
I have not remote idea (only my intuition), but can be cause by this:

https://github.com/minetest/minetest/pull/11696

**Comment by appgurueu** [comment]
> I have not remote idea (only my intuition), but can be cause by this:
> 
> #11696

You can use [`git bisect`](https://git-scm.com/docs/git-bisect) to verify your theory.

**Comment by Zughy** [comment]
Can you please provide a minimal test so that we can try to reproduce it?

**Comment by runsy** [comment]
Yes, download The Samz game. And hold a Red Roof Corner triangle.

Or do the same in The Samz server.

**Comment by runsy** [comment]
Today Ive recompiled the very last minetest and irrlitch and it works fine.

So I close this issue.
