### ISSUE TITLE
"plantlike" nodes with alpha "blend" cause graphical glitches

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#12188]
##### Minetest version

5.6.0-dev since commit b0b9732359 @x2048

##### Summary

This affects `"plantlike"` nodes which are placed on "blend" (alpha channel) node types. The back of their transparent face is not longer rendered.
Note: Regular grass is not glitched due to `waving = 1`.

![grafik](https://user-images.githubusercontent.com/1497498/162587905-3f4de453-c3df-4c19-bc9e-3865ffec9936.png)

*Issue originally reported by nephele*

##### Steps to reproduce

```Lua
minetest.register_node(minetest.get_current_modname() .. ":grass_top", {
	description = "Grass",
	drawtype = "plantlike",
	paramtype = "light",
	--waving = 1,  -- Solves the issue
	tiles = { "default_stick.png" },
	use_texture_alpha = "blend",
	--sunlight_propagates = true, -- Does not matter
	groups = { snappy = 3 },
})

minetest.override_item("default:dirt_with_grass", {
	use_texture_alpha = "blend"
})
```

This code must be executed after `default`. For best experience, go to Y = 13.5 (feet pos) and place the grass (sticks) on Dirt With Grass.

**Comment by runsy** [comment]
Yes I have this issue too in The Samz with 5.6.

**Comment by IrrlichtMt4** [comment]
Some bug also happens in 5.5.0 development though players don't see the blue sky. Instead, they just see through the Stick when looking at it from different angles.

**Comment by Wuzzy2** [comment]
This might be related: #11410
