### ISSUE TITLE
Worldalign not working on nodeboxes anymore.

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest#12197]
##### Minetest version
5.6.0-dev-9aabd911e

##### OS / Hardware
Operating system: Linux Mint 20.2
CPU: Intel i7-8700K

GPU model: GeForce GTX 1060 6GB
OpenGL version: 4.6.0

##### Summary
Nodeboxes with a world_aligned texture no longer render world aligned. I checked and there is no difference with shadows enabled or disabled. I noticed this a while back, but thought it was just a shadow bug, however I don't believe that to be the case anymore.

##### Steps to reproduce
Register a nodebox and use a texture with align_style='world' Alternately visit the 'In Our Midst' server and look at the sidewalk outside of the spawn building.

![align_style](https://user-images.githubusercontent.com/8930456/163080886-3da4d3dd-1b44-4be0-a49f-8627503f6ae5.png)

**Comment by NathanSalapat** [comment]
I think I found the culprit; https://github.com/minetest/minetest/commit/b0b9732359d43325c8bd820abeb8417353365a0c Every commit before this the world aligned textures render correctly, which makes me think something broke here.
Unfortunately I'm too stupid to have any idea what any of that code is doing. @x2048 could you see what's going on?

**Comment by Oblomov** [comment]
I've gone over the change here on GitHub and a suspicious change that _migtht_ (or not) be relevant is the change in [src/client/content_mapblock.cpp](https://github.com/minetest/minetest/commit/b0b9732359d43325c8bd820abeb8417353365a0c#diff-b76715a8a8224ffb4118b092d53887bec3e236111ef85d15ad151dbc7984b39c), where the `box.{Min,Max}Edge` get updated after (rather before) the `generateCuboidTextureCoords()`. Without any additional knowledge about the code, this at least _looks_ like it might be relevant. It should be pretty easy to test if it's actually the responsible bit, by restoring the relative position of the   `!txc` conditional  and edge update

**Comment by Oblomov** [comment]
OK, I've done some testing on the server and I think this is really the issue. I'll submit a patch.
