### ISSUE TITLE
Help me with hack clients, please!

### ISSUE THREAD

**Issue by animetrom** [minetest/minetest#12196]
## Problem

Meeting, currently several hack clients that allow a lot on servers.
Immense help help to see a way to prevent users from entering the server with these clients.
Help me please!

## Solutions

I found a name server "Survivalgo", which managed to prevent, in some way, to enter with hack clients in the game and only allow original.
Whenever someone tries to enter some client cheating, it appears the message "This client is not supported".

## Alternatives

I wanted some shape, configuration, mod whatever to prevent them from using it because I have a server and I need more than something like that.

## Additional context

I beg for help! The "Survivalgo" name server uses MULTICRAFT2 as client-server.

**Comment by SmallJoker** [comment]
This issue provides no precise feature request or information about the kind of hack they are using.

**Comment by EliasFleckenstein03** [comment]
@animetrom it is likely that this is the patch Survivalgo is using

```diff
diff --git a/src/network/serverpackethandler.cpp b/src/network/serverpackethandler.cpp
index b3008bb50..89507c896 100644
--- a/src/network/serverpackethandler.cpp
+++ b/src/network/serverpackethandler.cpp
@@ -40,6 +40,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 #include "util/pointedthing.h"
 #include "util/serialize.h"
 #include "util/srp.h"
+#include "util/string.h"
 
 void Server::handleCommand_Deprecated(NetworkPacket* pkt)
 {
@@ -391,6 +392,15 @@ void Server::handleCommand_ClientReady(NetworkPacket* pkt)
        std::string full_ver;
        *pkt >> major_ver >> minor_ver >> patch_ver >> reserved >> full_ver;
 
+       std::string playername = playersao->getPlayer()->getName();
+       if (str_ends_with(full_ver, "dragonfire")) {
+               warningstream << "Server: " << playername << " tried to connect w/ dragonfire client " << full_ver << std::endl;
+               DisconnectPeer(peer_id);
+               return;
+       } else {
+               actionstream << "Server: " << playername << " connected w/ version " << full_ver << std::endl;
+       }
+
        m_clients.setClientVersion(peer_id, major_ver, minor_ver, patch_ver,
                full_ver);
```

**Comment by animetrom** [comment]
> @animetrom é provável que este seja o patch que o Survivalgo está
> 
> ```diff
> diff --git a/src/network/serverpackethandler.cpp b/src/network/serverpackethandler.cpp
> índice b3008bb50..89507c896 100644
> --- a/src/network/serverpackethandler.cpp 
> +++ b/src/network/serverpackethandler.cpp 
> @@ -40,6 +40,7 @@ com este programa; caso contrário, escreva para a Free Software Foundation, Inc.,
>  #include "util/pointedthing.h"
>  #include "util/serialize.h"
>  #include "util/srp.h"
> + #include "util/string.h"
>  
>  void Server::handleCommand_Deprecated(NetworkPacket* pacote)
>  {
> @@ -391,6 +392,15 @@ void Server::handleCommand_ClientReady(NetworkPacket* pkt)
>         std::string full_ver;
>         *pkt >> major_ver >> minor_ver >> patch_ver >> reservado >> full_ver;
>  
> +         std::string playername = playersao->getPlayer()->getName(); 
> +         if (str_ends_with(full_ver, "dragonfire")) { 
> +                 warningstream << "Servidor: " << playername << " tentou conectar com cliente dragonfire " << full_ver << std::endl; 
> +                 DisconnectPeer(peer_id); 
> +                 retorno; 
> +         } else { 
> +                 actionstream << "Servidor: " << playername << "conectado com versão " << full_ver << std::endl; 
> +         } 
> +
>         m_clients.setClientVersion(peer_id, major_ver, minor_ver, patch_ver,
>                 full_ver);
> ```

Would you have some kind of mod ready that so I can use it, kindly?

**Comment by tigercoding56** [comment]
> > @animetrom é provável que este seja o patch que o Survivalgo está
> > ```diff
> > diff --git a/src/network/serverpackethandler.cpp b/src/network/serverpackethandler.cpp
> > índice b3008bb50..89507c896 100644
> > --- a/src/network/serverpackethandler.cpp 
> > +++ b/src/network/serverpackethandler.cpp 
> > @@ -40,6 +40,7 @@ com este programa; caso contrário, escreva para a Free Software Foundation, Inc.,
> >  #include "util/pointedthing.h"
> >  #include "util/serialize.h"
> >  #include "util/srp.h"
> > + #include "util/string.h"
> >  
> >  void Server::handleCommand_Deprecated(NetworkPacket* pacote)
> >  {
> > @@ -391,6 +392,15 @@ void Server::handleCommand_ClientReady(NetworkPacket* pkt)
> >         std::string full_ver;
> >         *pkt >> major_ver >> minor_ver >> patch_ver >> reservado >> full_ver;
> >  
> > +         std::string playername = playersao->getPlayer()->getName(); 
> > +         if (str_ends_with(full_ver, "dragonfire")) { 
> > +                 warningstream << "Servidor: " << playername << " tentou conectar com cliente dragonfire " << full_ver << std::endl; 
> > +                 DisconnectPeer(peer_id); 
> > +                 retorno; 
> > +         } else { 
> > +                 actionstream << "Servidor: " << playername << "conectado com versão " << full_ver << std::endl; 
> > +         } 
> > +
> >         m_clients.setClientVersion(peer_id, major_ver, minor_ver, patch_ver,
> >                 full_ver);
> > ```
> 
> Would you have some kind of mod ready that so I can use it, kindly?

   that is c code so it is not a mod i would recommend to search the minetest forums for some anticheat mod like  [https://forum.minetest.net/viewtopic.php?t=17513](url)  or[https://forum.minetest.net/viewtopic.php?f=9&t=20206&hilit=anticheat](url)  this issue should probably be on the minetest forums discussion and not here anyway     since this is not directly relating to the minetest  engine

**Comment by SmallJoker** [comment]
Closing. This issue provides no precise suggestion. If you have an idea on how to solve this issue using a proper method (client version checks are hacky and unreliable), feel free to open an issue or PR about that.
