### ISSUE TITLE
Zip Path Traversal Vulnerability on UnzipService.unzip

### ISSUE THREAD

**Issue by RepeatAfterMe** [minetest/minetest#12199]
Minetest version

Operating system: ANDROID

Summary:
Google detected Zip Path Traversal Vulnerability on UnzipService.unzip

(https://github.com/minetest/minetest/blob/master/android/app/src/main/java/net/minetest/minetest/UnzipService.java)

Steps to reproduce:
Need to fixed, with recommendation document in https://support.google.com/faqs/answer/9294009

**Comment by sfan5** [comment]
The code unpacks game data from a ZIP file included in the APK, it does not process any untrusted data. There is no vulnerability here.
