### ISSUE TITLE
[combine images render incorrectly on older clients on 5.5+ server

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#12209]
### Repro:

- Use a 5.4 or earlier client
- Connect to a 5.5 or later server
- Find something with a texture that starts with `[combine`, such as NodeCore's Living Sponge or Amalgamation

*N.B. do not try to use the public NodeCore servers to repro this because some of them now have a workaround in place for this bug.*

#### Expected:

- Texture appears as expected on a 5.5+ client.  In the NodeCore cases above, it would be a 16x16 animated texture.

#### Observed:

- For the NodeCore cases above, the texture appears as a single solid color (1x1 texture).  The color is the same every time (it's not a "missing texture" auto-generated random color image).

## Cause:

This appears to be a regression introduced in https://github.com/minetest/minetest/commit/b2eb44afc50976dc0954c868977b5829f3ff8a19#diff-1a57c4608538ac1f37a6e032831761b99629522cea1d851ab0e0e455c21c83b8R213-R217.

The code there suggests that the author accounted for textures beginning with `[png` by assuming they would be the only textures beginning with `[`, and forgetting that `[combine` exists.

This workaround should probably at least be extended to look for `[png` specifically and not finding false positives on `[combine`.

**Comment by SmallJoker** [comment]
I see. Normally the combine operator `^` handles texture size changes, however `[combine` depends on the base image size and discards any pixels that are outside the range: (5.3.0 code)
https://github.com/minetest/minetest/blob/057f0b82c23d5ad4efe044fe0f0d8753eb3a8bcf/src/client/tile.cpp#L1292

I believe it would be best to whitelist this modifier in the code you linked above to be future-proof in case new modifiers are added.

**Comment by appgurueu** [comment]
Worth noting that `[inventorycube` exists too.

**Comment by appgurueu** [comment]
> I believe it would be best to whitelist this modifier in the code you linked above to be future-proof in case new modifiers are added.

I believe it would be best to explicitly check against `[png` as neither `[combine` nor `[inventorycube` have the issue and I wouldn't want texmods to be prepended with `blank.png` for no reason (even if it worked).

**Comment by SmallJoker** [comment]
@appgurueu It's not about missing modifier support but f018737. If the the tile string could not be generated, old clients would crash immediately. An explicit `[png` check would work but the crash would re-appear with each new modifier. Also modifiers are server-independent. This means nothing will guard mods from using new modifiers on old servers.

**Comment by Warr1024** [comment]
> It's not about missing modifier support but...

Okay, that's unfortunate, but it makes sense to me.  It sounds like we would need to exhaustively special-case check for all modifiers that can be at the start of an image that exist in earlier versions.  So that means the basic logic is about as correct as it could be, it just didn't cover all of the cases it needed to, and the fix would be just adding explicit checks for all those cases.
