### ISSUE TITLE
Lua messing with userdata metatables trivially leads to segfaults

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12216]
These three issues can easily be provoked from Lua (as demonstrated):
```lua
-- 1) double-free
local i = ItemStack()
debug.getmetatable(i).__gc(i)

-- 2) type confusion
local i = ItemStack()
local v = core.get_voxel_manip()
debug.getmetatable(i).__gc(v)

-- 3) memory leak
local i = ItemStack()
debug.setmetatable(i, {})
```

#### Possible solutions (individually)

1. Set internal pointer to `nullptr` on deallocation.
Lua code still has a way to generate empty objects in that case, but this is not a problem.
2. Add a type check in the `__gc` implementation.
3. (none)

#### Possible solutions (in general)

1. Remove `debug.getmetatable` / `debug.getmetatable` from sandbox
<i>Impact</i>: Will break mods that use these functions even if their use could be interchanged with `getmetatable`/`setmetatable`
zero impacted mods [were found](https://irc.minetest.net/minetest-dev/2022-04-24#i_5965701) in CDB
2. Remove `debug.getmetatable` / `debug.getmetatable`'s ability to work with userdata objects
<i>Impact</i>: ~~Mods may want to modify userdata metatables (in particular `ObjectRef`) to override/wrap/extend methods, this would stop working~~ apparently not true
3. #12118
<i>Impact</i>: nothing?
4. ???

**Comment by Desour** [comment]
>     2. Remove `debug.getmetatable` / `debug.getmetatable`'s ability to work with userdata objects
>        Impact: ~Mods may want to modify userdata metatables (in particular `ObjectRef`) to override/wrap/extend methods, this would stop working~ apparently not true

Btw. the reason why this is not true is that the userdatas' metatables have the same table set for `__index` and `__metatable`, so the table returned by `getmetatable` is the table with the methods (and this table can hence be modified).

**Comment by Desour** [comment]
>     1. Remove `debug.getmetatable` / `debug.getmetatable` from sandbox

This is the simplest, and therefore best, solution, unless someone states a concrete, useful and valid usecase for these functions.
