### ISSUE TITLE
Texture packs no longer show as enabled

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12219]
##### Minetest version
master

##### Summary
Minetest's Content no longer correctly determines whether a texture pack is enabled, it always shows them as disabled

Caused by #12192

\cc @GoodClover 

##### Steps to reproduce
Enable a texture pack, notice it still says "Use Texture Pack" and doesn't show "(Enabled)" in the list

**Comment by GoodClover** [comment]
whoops
