### ISSUE TITLE
Prevent loading a world with unresolved dependencies

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12217]
## Problem

Currently, Minetest will disable mods that have unfulfilled dependencies and then still load the game. This has two problems:

* It's a bad user-experience as players can end up playing a game without the mods they enabled
* This causes problems when a mod opt depends on another mod with unfulfilled dependencies, see #8601 
* It results in a complicated mod dependency algorithm

## Solutions

Mods being implicitly disabled when they have unfulfilled dependencies/cycles should be deprecated in 5.6.0.

In 5.7.0, we should throw a hard error when a mod doesn't have a fulfilled dependency, or if there's cycles. This will allow the algorithm to be greatly simplified. In the case given in the issue, Minetest will show an error and return to the menu - the user would need to disable mod E. The Config Mods menu should also show errors such as cycles by highlighting mods red.

The hard error is partially implemented by #8059

![image](https://user-images.githubusercontent.com/2122943/164996876-b2bf2d11-3ffd-4e0c-a649-92620a8774ca.png)

## Additional context

Supersedes #8601, #11438, and #10486

Related #9977

**Comment by IrrlichtMt4** [comment]
Suggestion: Add a button to continue with unsatisfied dependencies.

**Comment by rubenwardy** [comment]
And have broken mods? Absolutely not

**Comment by Wuzzy2** [comment]
Good idea. The idea that Minetest pretends it is still working when an entire dependency tree is missing was always bad, it should have been prevented from the start. Minetest is not PHP. xD
Better late than never. :-)

**Comment by rubenwardy** [comment]
Work for 5.6.0 done, moving to 5.7.0 milestone

**Comment by erlehmann** [comment]
I think it is a great idea to simplify mod dependency resolution algorithm by erroring out instead of trying to march on.

@rubenwardy just to be clear, disabling the mod with broken dependencies will allow users to load the world in any case? Or are there possible situations where the user will be unable to load the world due to it not being possible to disable a mod?

**Comment by rubenwardy** [comment]
That will only happen if a game contains a hard dependency. This is forbidden by ContentDB, and games should be updated to fix this

**Comment by tigercoding56** [comment]
> And have broken mods? Absolutely not

some people just want to have broken mods

**Comment by rubenwardy** [comment]
You can already do that by disabling the mod in the select mods menu

**Comment by tigercoding56** [comment]
> You can already do that by disabling the mod in the select mods menu

ah ok thx
