### ISSUE TITLE
Complex texture modifiers using [png may still crash older clients

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12214]
##### Minetest version

Minetest 5.3 and older _in combination with_ any newer version

##### Summary
Due to [the complex nature of texture modifier syntax](https://github.com/minetest/minetest/issues/11588) it is presumably still possible to build texture modifiers that crash older clients as they use `[png:...` nested within other modifiers which the client does not support. The simplest example would be `([png:...)`; more complex ones might use a `[png` escaped within a `[combine` or `[inventorycube`.

The only proper way to fix this would be for the server to have an abstract texture modifier syntax tree for texture modifiers - which would also allow basic lexical & syntactical analysis to raise syntax errors etc. server-side - in order to be able to replace `[png` AST nodes with `blank.png^[png:...`; our current clientside shotgun parser makes this a rather messy business.

**Comment by sfan5** [comment]
I vote for closure as wontfix:
1. this problem gets smaller every passing day when people upgrade to new versions
2. you can probably count the number of mods using `[png` in node tiles on a single hand

> more complex ones might use a `[png` escaped within a `[combine` or `[inventorycube`.

Note that it's not as clear as this makes it sound. Just *using* `[png` does not cause anything on old clients, you need to end up with a tile with a NULL image to actually cause the mention crash.
