### ISSUE TITLE
Resizing the screen too small causes a grey screen

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest/minetest#12212]
Minetest 5.5.0
Resizing the screen too small cause the screen to be grey.
Resize the screen very small (8 pixels) then resize it large (any size) then observe a grey screen -->

**Comment by appgurueu** [comment]
Can't reproduce.

**Comment by IrrlichtMt4** [comment]
Forgot to mention the grey screen happened when I pressed the / key while the screen was very small.

**Comment by appgurueu** [comment]
Can confirm. I don't get a grey screen though (rather a "black screen") that isn't repainted (small rect in top left corner remains the same) and my Minetest crashes. `debug.txt` isn't really useful here; the last messsage reads "not allowing focus change".

**Comment by IrrlichtMt4** [comment]
I get this message in debug:

2022-05-07 14:54:18: ERROR[Main]: Some exception: "basic_string::substr: __pos (which is 2) > this->size() (which is 1)"

**Comment by Zughy** [comment]
Can't reproduce

**Comment by IrrlichtMt4** [comment]
Did you resize it really small and then press the / key?

**Comment by Zughy** [comment]
@IrrlichtMt4 Italian keyboard has got no `/` key by default, I have to press shift to print it. Anyway, is the problem still there with 5.6?
