### ISSUE TITLE
Account Registration: Change from 'Re-Type Password' to simply 'Type Password'.

### ISSUE THREAD

**Issue by LikeGuyS** [minetest/minetest#12222]
## The Problem

As seen in [this video](https://user-images.githubusercontent.com/104377424/165126836-caa65f2f-ebdf-4846-b6da-da693da06d46.mp4), When you first register an account on a server, it requests that you "Re-Type" your password. Now.. I, as a new user, didn't type any password in the first place so I will be clueless about what password I should type.

## Solutions

Simply, if a user didn't type any password in the first place, instead of demanding they 'Re-Type' the password, ask them to type a new one.

## Alternatives

Make typing a password in the first place a requirment.

**Comment by rubenwardy** [comment]
We have decided to make the registeration process clearer by adopting #12185 

"Retype password" is correct because there is a password on the online tab. This isn't clear
