### ISSUE TITLE
Denial of Service caused by formspec interaction spam and other methods from mods used against various popular servers to promote sketchy makeworld purchases and playerbase

### ISSUE THREAD

**Issue by Baigle** [minetest/minetest#12237]
Methods unknown, contact server owners

**Comment by Baigle** [comment]
makeworld is a cryptominer that sends a reported 49 percent of profits to the Lakhann the developer

**Comment by Unknown-yay** [comment]
https://www.instagram.com/makeworld_official/ is the instagram link. They promote a "free" copy of the game if you follow them, most likely another trick.

**Comment by karlexceed** [comment]
Their itch.io profile: https://itch.io/profile/harsh-lakhan

And a thread in the itch.io forums discussing his game's takedown which contains some details of what they've done: https://itch.io/t/2054674/my-game-was-indexed-but-now-its-not

**Comment by rollerozxa** [comment]
> makeworld is a cryptominer that sends a reported 49 percent of profits to 'Lakhann' the developer. the game is reportedly hwid locked to a computer and the developer claims that their campaign cannot be stopped because they use VPNs, Tor, and Monero for connections and transactions, as well as the dragonfire modified minetest client.

Where's the malware build? Someone bought Makeworld back when it was still available for purchase and I found the binaries bundled to be one of sfan5's 5.5.0-dev Windows builds with the icon changed using Resource Hacker. i.e. It is (or was) completely safe.

**Comment by Baigle** [comment]
> > makeworld is a cryptominer that sends a reported 49 percent of profits to 'Lakhann' the developer. the game is reportedly hwid locked to a computer and the developer claims that their campaign cannot be stopped because they use VPNs, Tor, and Monero for connections and transactions, as well as the dragonfire modified minetest client.
> 
> Where's the malware build? Someone bought Makeworld back when it was still available for purchase and I found the binaries bundled to be one of sfan5's 5.5.0-dev Windows builds with the icon changed using Resource Hacker. i.e. It is (or was) completely safe.

Please upload the binaries for analysis so we can analyze them for proof that what the DoSser said about their own claimed game title was false about cryptomining

**Comment by rollerozxa** [comment]
Here is a [VirusTotal analysis](https://www.virustotal.com/gui/file/ce4137b7e8066abec92f91b0e0be52789c50a8951a1e08841e397109a123028f/summary) of the Makeworld.exe executable, which is the only binary file that differs from [sfan5's 5.5.0-dev-51cfb57 build](https://forum.minetest.net/viewtopic.php?p=402807#p402807). In addition, here is a diff of the executable against the unmodified executable which shows that all parts remain the same except for the resources (which was confirmed by Harsh himself to be done using Resource Hacker):
![](https://media.discordapp.net/attachments/959520409181651087/959557599748038686/unknown.png)

If you'd want a copy to analyse it yourself please contact me privately and I can provide a download link. I do not feel it is a good idea to link to it on a public forum like the Minetest bugtracker even if it's safe.

**Comment by LoneWolfHT** [comment]
> makeworld is reported to be a cryptominer that sends 49 percent of profits to 'Lakhann' the developer. the game is reportedly hwid locked to a computer and the developer claims that their campaign cannot be stopped because they use VPNs, Tor, and Monero for connections and transactions, as well as the dragonfire modified minetest client.

Where did you get this from? Your legs are either being pulled or you're trying to pull someone else's leg

**Comment by 0siribix** [comment]
I've been following alot of this discussion over several media. I am inclined to believe that it is in fact Harsh and possibly another actor whether they are collaborating or acting separately. It's difficult to tell by some of the activity. I agree that he/she doesn't seem like a strong coder but also not inept. I don't see any evidence of a cryptominer. I don't believe MT can execute anything from the resources section of the exe. If another section was modified then maybe I could see that being coded (by someone fairly competent) to execute from there but since the resources section is the only modified section, that indicates to me that only the icon is different

As for why I do believe it's actually Harsh involved in the attacks; Someone joined the MT discord with that name and claimed responsibility for some of this

**Comment by LoneWolfHT** [comment]
> As for why I do believe it's actually Harsh involved in the attacks; Someone joined the MT discord with that name and claimed responsibility for some of this

I checked the logs of their confirmed Discord account and didn't see this, so I think you may have been confusing them with one the spam/impersonation bots.

They did post links to tools on Github that might be possible to use for Discord spam bots (I haven't looked into them), but it was in the context of figuring out what the attacker used

**Comment by LoneWolfHT** [comment]
> Methods unknown, contact server owners

Could you be more specific as to which servers? CaptureTheFlag and a few other top servers haven't had any formspec-based attacks AFAIK
