### ISSUE TITLE
Stacktraces reported by Minetest blame the wrong mod

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12236]
##### Minetest version
```
5.5.0 and earlier; presumably 5.6-dev as well
```

##### Summary
See https://github.com/minetest-mods/wielded_light/issues/21: The stacktrace clearly shows `mesecons` is responsible, but the error message blames the `wielded_light` mod.

##### Steps to reproduce

```lua
//lua table.insert(minetest.registered_globalsteps, function() _ = nil + nil end)
```

**Comment by rubenwardy** [comment]
"From mod X" is saying the `get_current_modname` value - wielded_light is the mod that's currently loading. It's not based on stacktrace

**Comment by appgurueu** [comment]
> "From mod X" is saying the `get_current_modname` value - wielded_light is the mod that's currently loading. It's not based on stacktrace
> 
> It should probably say "error whilst loading mod" rather than "error from mod"

This should be after load time though, unless I misinterpret "in callback environment_Step()"?

**Comment by sfan5** [comment]
`core.run_callbacks` sets the correct mod origin on a best effort basis:
https://github.com/minetest/minetest/blob/480d5f2d51ca8f7c4400b0918bb53b776e4ff440/builtin/game/register.lua#L421-L425

As you can see if a callback doesn't have a mod origin set the last set one will stick around. But without a concrete reproducer there is nothing that can be done about this issue.

**Comment by appgurueu** [comment]
> `core.run_callbacks` sets the correct mod origin on a best effort basis:
> 
> https://github.com/minetest/minetest/blob/480d5f2d51ca8f7c4400b0918bb53b776e4ff440/builtin/game/register.lua#L421-L425
> 
> As you can see if a callback doesn't have a mod origin set the last one will stick around. But without a concrete reproducer there is nothing that can be done about this issue, since it _generally_ works.

That looks like an obvious bug to me. It should clear the "origin" using `core.set_last_run_mod"??"` or the like.

**Comment by appgurueu** [comment]
A simple way to reproduce this: `//lua table.insert(minetest.registered_globalsteps, function() _ = nil + nil end)

![Screenshot 2022-04-28 11-32-12](https://user-images.githubusercontent.com/34514239/165723489-c64e07b8-a4c4-4f59-b9d8-b315cde38d1f.png)
