### ISSUE TITLE
disallow_empty_password = true ... still allow client to change later to empty, what I don't want !

### ISSUE THREAD

**Issue by Festus1965** [minetest/minetest#12233]
##### Summary
the minetest.cond setting 'disallow_empty_password = true' allow server admin to block client without a password, or deny empty password,
BUT after join game, gamer can set in client a new password that is against my set rule no empty.

##### Steps to reproduce
login, press esc, press change password ...

IF we take the willing or rule from admin serious
set disallow_empty_password = true
then also a change from client / gamer must be checked over this rule and revoke if true and new password empty !

**Comment by sfan5** [comment]
The setting does exactly what is documented:
> If enabled, **new** players cannot join with an empty password.

But I agree that this is not useful and should be changed.

**Comment by Festus1965** [comment]
sorry, but

disallow_empty_password

does NOT indicate only for new players !!!
I read this rule basic, as there is not new ... or register... in this name
