### ISSUE TITLE
HWBufferMap causes periods of low framerate and stutter

### ISSUE THREAD

**Issue by paradust7** [minetest/minetest#12231]
##### Minetest version
```
8d55702d139db739f8bf43eaa600f41446b29a16
```

##### OS / Hardware
Operating system: Emscripten/Web
GPU model:  NVIDIA GeForce RTX 3090 (via WebGL2)
OpenGL version: OpenGLES2

##### Summary
After joining a server with a very busy map, observed that FPS would start out around 70fps, but gradually drop until it reached around 10fps. This would remain the case for up to 30 seconds, after which things returned to normal.

Profiling determined that the problem came from this situation:

https://github.com/minetest/minetest/blob/480d5f2d51ca8f7c4400b0918bb53b776e4ff440/src/client/game.cpp#L3995

This is what happens, in this order:

- The HWBufferMap gets excessively large after about 200 frames.
- Due to this, FPS shrinks from 70fps to 10fps as the overhead of map lookups dominates render time.
- At 10fps, it takes about 20 to 30 seconds before the 500 frame limit is reached.
- The buffer map is finally reset, and things return to normal after a second or two of buffering.

I have a proposed solution, which I will attach as a pull request to this issue.

**Comment by paradust7** [comment]
I updated the pull requests. Please let me know if you need anything else. (I'm very new to github, so please let me know if I've made any obvious mistakes)

FYI, I haven't tested this on anything except Emscripten. I made sure it built on vanilla Linux (using a VPS), but I haven't run it. I could setup a machine to do so later today if need be. (Are there automated tests?)

**Comment by sfan5** [comment]
I'll test the changes locally before approving them anyway.
There are two automated tests that run the client or IrrlichtMt itself though neither will run into the HW buffer changes for different reasons.

**Comment by paradust7** [comment]
fyi the irrlicht side of this still needs to be merged
