### ISSUE TITLE
I can't open Minetest on my Macbook

### ISSUE THREAD

**Issue by CodeBitesU** [minetest/minetest#12235]
##### Minetest version

```
Minesetversion:
Use [Homebrew](https://brew.sh/) to get the stable version 
```

##### OS / Hardware

Operating system:
CPU:

GPU model: irrelevant
OpenGL version: irrelevant

##### Summary
I have an Macbook Air, macOS Monterey.
I need Minetest for a project tomorrow and I tried to download it with Homebrew, I gave the commands and it started Downloading.
But at the end came this:

==> minetest
Put additional subgames and mods into "games" and "mods" folders under
"~/Library/Application Support/minetest/", respectively (you may have
to create those folders first).

If you would like to start the Minetest server from a terminal, run
"/usr/local/opt/minetest/minetest.app/Contents/MacOS/minetest --server".

What do I have to do now? I honestly thought it would appear as an app on launchpad. 
(And the language setting on my Mac is German if that effects the path)
Very thankful for any help.
##### Steps to reproduce
explained above

**Comment by rubenwardy** [comment]
If you still need help, please comment
