### ISSUE TITLE
Wield images not colored correctly

### ISSUE THREAD

**Issue by TurkeyMcMac** [minetest/minetest#12245]
##### Minetest version

```
5.6.0-dev
```

##### OS / Hardware

Not relevant, I don't think.

##### Summary

Wield images should be colored just like inventory images according to the set `palette_index` or `color`. They are not.

##### Steps to reproduce

Place and pick up a `testnodes:color` in devtest. The color of the wield image will not match that of the inventory image:
![screenshot_20220428_222922](https://user-images.githubusercontent.com/28828704/165876895-b02747aa-cdbb-48d4-ab04-df46accb24a9.png)

**Comment by sfan5** [comment]
I am pretty sure this works for wield *items* but it may not for wield nodes.

**Comment by TurkeyMcMac** [comment]
Apparently the bug is still there even when using `wield_image`:
![screenshot_20220429_135622](https://user-images.githubusercontent.com/28828704/165997775-a3ec34de-61dd-4ec5-9bb9-f04c5694dbb1.png)

I applied this patch to devtest to test the bug:

```patch
diff --git a/games/devtest/mods/testnodes/param2.lua b/games/devtest/mods/testnodes/param2.lua
index 5d64376fa..39d6e8b02 100644
--- a/games/devtest/mods/testnodes/param2.lua
+++ b/games/devtest/mods/testnodes/param2.lua
@@ -83,6 +83,8 @@ minetest.register_node("testnodes:color", {
 	tiles = {
 		"testnodes_node.png",
 	},
+	inventory_image = "testnodes_node.png",
+	wield_image = "testnodes_node.png",
 
 	groups = { dig_immediate = 3 },
 })
```

**Comment by sfan5** [comment]
Confirmed to be broken, this worked in 5.5.

**Comment by sfan5** [comment]
bisected to 54dccc480eb03adcf219a7add58f547284f40f76

@x2048

**Comment by TurkeyMcMac** [comment]
The bug does not manifest when I disable shaders. The problem is surely with this code: https://github.com/minetest/minetest/blob/a89afe1229e327da3c397a3912b2d43d2196ea2b/src/client/wieldmesh.cpp#L507-L521

**Comment by sfan5** [comment]
Well not necessarily, the shader code probably just forgets to apply the color.

**Comment by TurkeyMcMac** [comment]
True.

**Comment by x2048** [comment]
Shaders apply the color correctly, but that's the ambient light color. Item color information should have been stored in the vertices, but it never happens with shaders, because I moved that setColor() call into an 'else' (line 519 in @TurkeyMcMac 's reference). I've now added calls to initialize the colors once when the mesh is created.

**Comment by TurkeyMcMac** [comment]
@x2048 Flat wield images are still not colored for me.

**Comment by x2048** [comment]
@TurkeyMcMac can you open a new issue with a reproduction scenario?

**Comment by TurkeyMcMac** [comment]
@x2048 It seems the bug is now tracked by https://github.com/minetest/minetest/pull/12304. You can use the colored craftitems from that PR to reproduce the bug.

**Comment by Wuzzy2** [comment]
I, alongside with TurkeyMcMac can still reproduce this issue. Reopening.

#12304 does NOT track this issue, it is a PR that just accidentally uncovered the bug again. :D

**Comment by x2048** [comment]
@TurkeyMcMac The issue should be fixed in the master now, could you check? Thank you.

**Comment by TurkeyMcMac** [comment]
Thanks, it works now.
