### ISSUE TITLE
Logging Performance Improvement

### ISSUE THREAD

**Issue by paradust7** [minetest/minetest#12242]
## Problem

Much performance-sensitive code is decorated liberally with infostream, verbosestream, etc. This is vital for debugging, but most of the time the output is not written anywhere.

Ideally, there would be no performance penalty for these lines when these logging levels are not enabled. Unfortunately at present, almost the entire penalty is paid regardless of the logging configuration.

- All the text is rendered into a buffer
- To each line is appended a timestamp, thread name, and level label. (two allocations, time(), localtime(), and strftime())
- Grabs a mutex to iterate through output endpoints
- Only at this point finds there is no endpoint

## Suggested Solution

Replace the logging streams with a custom ostream proxy class, which checks the logging level before every operation.
A rough sketch:

```
class LogStream {

  LogStream(LogLevel level) {
    ...initializes backing_stream...
  }
  
  bool isEnabled() const { return m_enabled; }

  // Would forward every operator<<
  LogStream& operator<<(unsigned long n) {
    if (isEnabled()) {
      backing_stream << n;
    }
    return *this;
  }
  
private:
  ostream backing_stream;
  bool m_enabled; // updated from a global atomic on every std::endl
};

...
thread_local LogStream infostream(LL_INFO);
thread_local LogStream verbosestream(LL_VERBOSE);
...

```

**Comment by Oblomov** [comment]
May I recommend using an existing logging library such as [spdlog](https://github.com/gabime/spdlog)?
