### ISSUE TITLE
b3d mesh nodes are displayed much smaller in 5.6 than in 5.5

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest#12249]
##### Minetest version

```
5.6.0-dev (sorry, I dont have a git commit, because I have only used a fork of 5.6, and dont have the time to build from source again right now. But it occurs with https://minetest.dustlabs.io/mt/ which is also on 5.6, as well as jordach's mapgen fork)
```

##### OS / Hardware

Operating system: Win 11
CPU:

GPU model: Intel integrated
OpenGL version:

##### Summary

When you define a .b3d mesh as a node, in 5.5 it is displayed normally, but in 5.6, it is displayed as about 10x smaller.

I have not noticed any problems with entities.

This is affecting wormball in minigames galore.

[wormball_power.zip](https://github.com/minetest/minetest/files/8595222/wormball_power.zip)

##### Steps to reproduce

Attached is a .b3d model that is a voxel sphere (used as the food in wormball)
Make a mod or modify a devtest mod to use the .b3d file as a node.

View the node in 5.5, and in 5.6dev

in 5.5 the node will be normal size, in 5.6dev, it will be miniscule, both in-world and in-inventory

**Comment by Zughy** [comment]
I noticed this as well a few months ago (my server runs wormball too) but I was too lazy to open an issue

**Comment by MisterE123** [comment]
hmm... yeah that is a good question. Maybe the b3d is corrupted.
The other nodes in the mod are also b3ds. So, i guess, does anyone else notice this bug in other files? We need confirmation of that to call it a bug.

**Comment by Zughy** [comment]
I've imported your file and re-exported it without touching anything: it seems to work fine now.
![imagen](https://user-images.githubusercontent.com/63455151/166138085-df6aed84-3614-4418-bec9-0e143940612f.png)

So uhm... what?

**Comment by Zughy** [comment]
UPDATE: the error lies in the .blend file. The hierarchy of the file is wrong, with the 3D object nested inside the armature (which is also not needed, but anyway)

![imagen](https://user-images.githubusercontent.com/63455151/166139247-ef0ee6b2-5ebb-449f-bc02-fac176fc42d6.png)

Also, the scaling of the object is off, making it automatically 50% smaller when imported (which I don't consider a bug, it's responsibility of the artist to apply the scaling before exporting, with Ctrl+A)

![imagen](https://user-images.githubusercontent.com/63455151/166139484-deb80fb1-b2fa-4e75-984a-2f0f2461df55.png)

Removing the armature (as it's nested inside of it) + applying the scale makes the file correct.


@sfan5 I don't think this is a bug nor a regression; on the contrary it has revealed an error inside the very 3d file that it went unnoticed before. I'd close this with "Not a bug", but I guess it's your call

**Comment by sfan5** [comment]
It is still a regression if Irrlicht 1.8 parsed broken b3d differently than IrrlichtMt but I agree that this is a wontfix.

**Comment by MisterE123** [comment]
ok, closing.
