### ISSUE TITLE
Dynamic shadows don't enable

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest/minetest#12259]
Minetest 5.6.0 c7bcebb6 (gitlab).
Dynamic shadows don't enable when I enable any level of shadow quality in dynamic shadows.

**Comment by rubenwardy** [comment]
The game or a mod needs to opt into shadows 

Here's a mod: https://content.minetest.net/packages/ROllerozxa/enable_shadows/

**Comment by IrrlichtMt4** [comment]
Thanks for info :)
