### ISSUE TITLE
Improve performance of `deSerializeJsonString(IfNeeded)`

### ISSUE THREAD

**Issue by paradust7** [minetest/minetest#12250]
## Problem

`deSerializeJsonStringIfNeeded` shows up frequently in profiling during moments of stutter (emscripten build). Within this function, most of the time is spent inside std::stringstream methods.

Relevant code:

https://github.com/minetest/minetest/blob/ec4a789b4f56d7918b6c964e59b9903af5e17fcd/src/util/serialize.cpp#L249-L288

The main issue seems to be that std::stringstream has pathologically bad performance when reading/writing single characters. I'm not aware of the reasons this is the case.

Here's a benchmark to demonstrate the problem: https://gist.github.com/paradust7/a7597d92b4f2cdca0f54dd7ebc09b6fc

Benchmark results on Linux X86-64:

```
$ g++ -O3 benchmark.cpp -o benchmark
$ ./benchmark
use_string_stream with size = 1000000 and loops = 10 took 107 milliseconds
use_vector_char with size = 1000000 and loops = 10 took 13 milliseconds
use_string_stream with size = 10 and loops = 1000000 took 299 milliseconds
use_vector_char with size = 10 and loops = 1000000 took 89 milliseconds
```

Benchmark results on Emscripten running on Node:
```
$ em++ -O3 benchmark.cpp -o benchmark.js -sINITIAL_MEMORY=1000mb
$ node ./benchmark.js
use_string_stream with size = 1000000 and loops = 10 took 273 milliseconds
use_vector_char with size = 1000000 and loops = 10 took 19 milliseconds
use_string_stream with size = 10 and loops = 1000000 took 355 milliseconds
use_vector_char with size = 10 and loops = 1000000 took 97 milliseconds
```

## Solutions

I am investigating a solution. This issue is a placeholder to keep track of the discussion.

**Comment by sfan5** [comment]
The stringstream can be replaced with an `std::string`, it's possible to [reserve](https://en.cppreference.com/w/cpp/string/basic_string/reserve) enough storage in advance and it should perform just as well as a vector.

**Comment by sfan5** [comment]
Here's my suggestion: https://github.com/minetest/minetest/compare/master...sfan5:quicker

**Comment by paradust7** [comment]
@sfan5

I did some bench-marking to compare:
```
s.push_back('a');
s.push_back('b');
```
vs.
```
s.append("ab");
```
And the results are surprising. On Linux-x86-64 GCC:
```
use_string_push_back with size = 1000000 and loops = 10 took 33 milliseconds
use_string_push_back with size = 10 and loops = 1000000 took 64 milliseconds
use_string_append with size = 1000000 and loops = 10 took 50 milliseconds
use_string_append with size = 10 and loops = 1000000 took 73 milliseconds
```
On Emscripten (which is Clang) push_back is only marginally (~5%) faster. Apparently gcc struggles with optimizing this.

I did confirm that `std::string` using `push_back` is roughly the same performance as `std::vector<char>`.

**Comment by paradust7** [comment]
I can't seem to comment on your preview. But here are some notes:
------------------------
`assert(s.front() == '"' && s.back() == '"');`
Could this function ever be provided user/server-input that might be malformed?
------------------------
In deSerializeJsonStringIfNeeded, in the non-json string case, is it super important to not absorb that last space at the end?
Because if not, you could use: `std::getline(is, tmp, ' ');`
See: https://www.cplusplus.com/reference/string/string/getline/
Even if so, you could probably do `ungetc` after `getline`, as long as `!eof`

**Comment by paradust7** [comment]
More notes:

line 237: `s.erase(s.begin() + w, s.end());`
Could you just do `s.resize(w);` ?

line 186: assert(c != '"');
Wouldn't this fire if the string was exactly 2 characters? (two double quotes)

**Comment by sfan5** [comment]
> I did some bench-marking [...]

Is this regarding `serializeJsonString`? If so, did you test with enough space reserved in the string?
I'll switch to `push_back` for all others (missed that it exists...).

> Because if not, you could use: `std::getline(is, tmp, ' ');`

Yes, that's important. Using getline would also complicate the implementation a bit because I have to prepare a buffer and cut it to the right size afterwards, not worth it IMO.

> Could you just do `s.resize(w);` ?

Yes, will do.

> Wouldn't this fire if the string was exactly 2 characters? (two double quotes)

No, the last `"` is already excluded from `len`.
I'll add more tests though so edge cases like this aren't accidentally broken.

**Comment by sfan5** [comment]
Pushed more changes. Maybe you can test them and tell me if it performs better.

**Comment by paradust7** [comment]
FYI, it turns out that in my original profiling, I may have been seeing the starting edge of an attack (or at least abuse of a glitch).  I use the Catlandia server for profiling. Yesterday the server was almost unplayable near spawn. Clients' would freeze for ~20 seconds at a time. Profiling shows it was processing a single huge packet with huge itemstack metadata:

![Screenshot from 2022-04-30 21-53-15](https://user-images.githubusercontent.com/102263465/166163650-984552b0-f43e-429f-8a9b-a7c444aacfab.png)

There was a malicious item "printed_paper" in a printer in their "pc room" which had ~50MB of metadata attached.

**Comment by paradust7** [comment]
@sfan5

Would there be any problem with adding a https://github.com/marketplace/actions/continuous-benchmark workflow?

This would generate performance graphs (as a function of git revision) and make it easier to track performance gains or detect regressions. Starting with a benchmark for deSerializeJsonStringIfNeeded

**Comment by paradust7** [comment]
This is useful to this issue:

https://github.com/minetest/minetest/pull/12258

**Comment by paradust7** [comment]
FYI, this is what happens to the benchmarks (from https://github.com/minetest/minetest/pull/12258) when I apply your changes:
```
serializeJsonStringIfNeeded_small_alpha                      6.36338 ns  -->  5.92395 ns
deSerializeJsonStringIfNeeded_small_alpha                    337.405 ns  -->  28.8585 ns
serializeJsonStringIfNeeded_small_alpha_with_space           232.715 ns  -->  24.3067 ns
deSerializeJsonStringIfNeeded_small_alpha_with_space         658.079 ns  -->  77.3647 ns
serializeJsonStringIfNeeded_large_alpha                      2.49844 us  -->  2.49003 us
deSerializeJsonStringIfNeeded_large_alpha                    123.068 us  -->  155.951 ns
serializeJsonStringIfNeeded_large_alpha_with_space           83.0236 us  -->  19.8459 us
deSerializeJsonStringIfNeeded_large_alpha_with_space         241.263 us  -->  55.8048 us
serializeJsonStringIfNeeded_small_escaped                    286.258 ns  -->  74.3092 ns
deSerializeJsonStringIfNeeded_small_escaped                  816.461 ns  -->  145.65 ns
serializeJsonStringIfNeeded_small_escaped_with_space         290.089 ns  -->  66.352 ns
deSerializeJsonStringIfNeeded_small_escaped_with_space       781.735 ns  -->  137.95 ns
serializeJsonStringIfNeeded_large_escaped                    95.3566 us  -->  49.2491 us
deSerializeJsonStringIfNeeded_large_escaped                  428.354 us  -->  107.417 us
serializeJsonStringIfNeeded_large_escaped_with_space         94.7866 us  -->  46.6649 us
deSerializeJsonStringIfNeeded_large_escaped_with_space       420.399 us  -->  102.097 us
serializeJsonStringIfNeeded_small_nonascii                   513.952 ns  -->  1.8716 us
deSerializeJsonStringIfNeeded_small_nonascii                 3.39835 us  -->  2.21023 us
serializeJsonStringIfNeeded_small_nonascii_with_space        430.592 ns  -->  1.1553 us
deSerializeJsonStringIfNeeded_small_nonascii_with_space      2.30037 us  -->  1.37225 us
serializeJsonStringIfNeeded_large_nonascii                   327.478 us  -->  1.79535 ms
deSerializeJsonStringIfNeeded_large_nonascii                 2.90563 ms  -->  2.11714 ms
serializeJsonStringIfNeeded_large_nonascii_with_space        242.405 us  -->  1.21659 ms
deSerializeJsonStringIfNeeded_large_nonascii_with_space      2.06076 ms  -->  1.43006 ms
```

It looks much better. There are some notable regressions:

serializeJsonStringIfNeeded_small_nonascii_with_space
serializeJsonStringIfNeeded_large_nonascii
serializeJsonStringIfNeeded_large_nonascii_with_space

**Comment by sfan5** [comment]
> Would there be any problem with adding a https://github.com/marketplace/actions/continuous-benchmark workflow?

Sounds useful, Adding dependencies is not done lightly but if it's only for the sake of CI then that okay by me.

> FYI, this is what happens to the benchmarks

Thanks for testing!

> This touches the code that writes \u00XX. It would likely be much faster to do it directly (using push_back and a "tohex()" method) than relying on a stream.

I agree. I did not optimize that case at all.
