### ISSUE TITLE
Red screen on death

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1225]
When a player gets attacked in short delays the screen stays red longer than it should. 
The show-red-screen-time gets added on the already existing time, this way it takes too long for the screen to turn back to normal.

Bug found on Minetest 0.4.9 8b02a01 Windows XP.

**Comment by nerzhul** [comment]
@Calinou @sfan5 is this issue already present ?

**Comment by Megaf** [comment]
@nerzhul 

To reproduce, wear a admin armor from 3D armor or eat a lot of bread while swimming in lava. Your screen will remain red for a minute after you are no longer in lava.
