### ISSUE TITLE
State that dynamic shadows, even if activated, need games/mods to opt-in to be displayed

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12260]
See https://github.com/minetest/minetest/issues/12259#issuecomment-1114668138, possibly underneath the shadows option in the main menu

**Comment by rollerozxa** [comment]
All options in the settings menu could use a short description as a tooltip, I was actually working on writing them but I ran into an issue where tooltips for dropdowns don't show up.

**Comment by Zughy** [comment]
I think that in this case it should be a static always visible text more than a tooltip. Tooltips to me are more "in depth" descriptions of what something does. This is more like a warning

**Comment by Wuzzy2** [comment]
> All options in the settings menu could use a short description as a tooltip, I was actually working on writing them but I ran into an issue where tooltips for dropdowns don't show up.

Tooltips are broken for dropdown elements. This isn’t your fault. This is an ancient known bug known since 2014: #1577

Just write the tooltips anyway, ignoring the bug. You can make the tooltip show up if you place the cursor exactly on the frame.
