### ISSUE TITLE
minecart

### ISSUE THREAD

**Issue by richard627z** [minetest/minetest#12269]
## Problem

#### The minecart passes through the railway when it goes up. It can not go up correctly.

![210840](https://user-images.githubusercontent.com/77524662/166689213-e230d952-03ee-46aa-9823-abe9b6813284.png)

**Comment by Zughy** [comment]
Closing because of too little information. Please follow the form next time, but from what I can see this is not related to the engine - more of a MTG or whatever specific mode you're using issue.

**Comment by rubenwardy** [comment]
This looks like an issue with Minetest Game: https://github.com/minetest/minetest_game/issues/new/

**Comment by richard627z** [comment]
Thanks. I'm new here.
