### ISSUE TITLE
Is BigEndian CPUs are supported ? AmigaOS4 port in progress

### ISSUE THREAD

**Issue by kas1e** [minetest/minetest#12279]
## Problem

I want to port Minetest to AmigaOS4 , which is 32bit PowerPC based system so mean Big Endian byte orders. I already have ported Irrlicht Engine (and few games over it like SuperTuxKart, Night Of the Zombies, Worlds and H-Craft), and want to port Minetest too. 

Actually, i already made it compiles and links, and as it uses Irrlicht Engine i have working menu, etc :

https://kas1e.mikendezign.com/aos4/gl4es/minetest/minetest_4.jpg

But when i choose to start a game, be it local developed one, or connect to any exiting one everything freezes. Sometime it shown the  "create server" progress bar and then freezes.

So few questions then:

1). Is Big-Endian supported ? From Graphics size it seems ok as it use irrlicht, and at least network code kind of work (as i can see list of the server , so fetching work). But maybe something wrong with it in the "create server" part ? 

2). If i will made pull request with amigaos4 changes, will the be accepted ? (they are clean, and small, mostly adding few bits there and there).

3). How to debug this issue ? I didn't have there GDB, but only good-old "prinf()" way. But maybe there needs to do some tests somehow ? Maybe everything related to the threading code or something ? 

Any ideas/help/etc very welcome !

Thanks !

**Comment by sfan5** [comment]
> 1). Is Big-Endian supported ?

In general the code is written to be endian independent, but probably nobody has verified this to work in years.

> 2). If i will made pull request with amigaos4 changes, will the be accepted ?

Sure, we'll review them obviously but support changes are welcome.
Note that we no longer use Irrlicht but [our own fork](https://github.com/minetest/irrlicht) (which for example already has SDL2 support), if you spend work porting an older version that may be wasted work. Try with 5.5.0.

> 3). How to debug this issue ?

Are you sure amigaos has no debugger? That sounds incredibly inconvenient when you don't even access to a stacktrace. otherwise: a lot of `printf`'s.

**Comment by kas1e** [comment]
@sfan5 
> That sounds incredibly inconvenient when you don't even access to a stacktrace. 

We do have of couse little bits, like when things crashes, we have on serial stack trace and state of registers, etc, etc, but when crash is heavy, machine may simple freezes and nothing anywhere. Or , it can bring misleading crashlog with wrong line numbers, etc :)

**Comment by kas1e** [comment]
@sfan5 
Doesn't you mind if i will continue asking help there for amigaos4 port ? Just to not deral issues , and only made it all in one ticket ?

Currently i have one single freeze which prevent me to start a game. As i understand, even if i want to start a local game , even in "Development test" mode, it create a server and connect to it, that correct ? I mean network is used in any case all the time, and i can't start anything without creating a server ?

What i find now with prinfs, is that i freeze on amigaos4 happens right when i am about to call ```server->start();``` from game.cpp's ```Game::createSingleplayerServer``` (i have ther only ipv4, so it's only about ipv4).  Sadly i can't find where exactly it crashes in ```Server::start()``` because it always random. Sometime i can see half of ```ASCII art for the win``` ascii message, sometime i can see full, sometime none. 

That all point me out that there can be general issues with threading and/or mutexes on my side. Also we have custom libsemaphore for support posix semaphores which we also may to blame, but as far as i can see in ```server::init``` and ```server::start``` no semaphores used at all.

Currently what i may think of it maybe remove fully threading from network code, but then, how it will behave i don't know.. 

Also i may worth to create some simple test case to mimic the functionality of those things happens in the ```sever::init``` and ```serevr::start```..

Any help/idea/etc very apprecated. Thanks !

**Comment by kas1e** [comment]
Forget to add, one of our developers says about:

```
To stop another thread in a clean way on AmigaOS requires co-operation from the thread that is to be stopped, but the kill operation has to do this by force because of how it is designed.

It would be better if MineCraft used a semaphore or other similar construct to signal the threads to stop and then used join to wait for them to end similar to the SimpleThreadTest here:  https://github.com/minetest/minetest/blob/master/src/unittest/test_threading.cpp
```

But still we don't know cause of the crash..

**Comment by sfan5** [comment]
> As i understand, even if i want to start a local game , even in "Development test" mode, it create a server and connect to it, that correct ?

yes, networking is always used

> Sometime i can see half of ASCII art for the win ascii message, sometime i can see full, sometime none.

that sounds like some bigger underlying issue, you really need a debugger...

> Currently what i may think of it maybe remove fully threading from network code, [...]

this is potentially lots of work when an easier *fix* should be available.

if you're concerned that something basic may not be working I suggest running the unittests first and seeing if they pass on your platform. there's a few ones that test threads too.

**Comment by kas1e** [comment]
> if you're concerned that something basic may not be working I suggest running the unittests first and seeing if they pass on your platform. there's a few ones that test threads too.

Tested, I have the same hardcore freeze where do "minetest --run-unittests" . I then reboot checked debug.txt, and can see that socket and threading tests passed (except that i have no ipv6, and it says ipv6 test failed to create, but that expected). But then, after few seconds it freezes. And it the same random, can freeze on different tests after.

All of this point me out that something with threads or socket , which while say tests passed, leads later to issues.

Can i somehow run single tests ? Like "minetest --run-unittest=threads" or "minetest --run-unittest=socket" or something ? So i can just step by step checked everyone, to find out after which one i have problems.

Btw, i checked also win64 build on my win10 to run unittests on, and those ones failed:

```
[FAIL] testLowercase - 0ms
[FAIL] testCreation - 0ms
[FAIL] testGetModsWrongDir - 6ms
[FAIL] testGetMods - 4ms
Test assertion failed: sm.getModSpec("basenodes") != NULL
    at test_servermodmanager.cpp:138
[FAIL] testGetModspec - 4ms
Test assertion failed: result.empty() == true
    at test_servermodmanager.cpp:146
    actual:   0
    expected: 1
[FAIL] testGetModNamesWrongDir - 4ms
Test assertion failed: std::find(result.begin(), result.end(), "basenodes") != result.end()
    at test_servermodmanager.cpp:155
[FAIL] testGetModNames - 4ms
Test assertion failed: result.empty() == true
    at test_servermodmanager.cpp:163
    actual:   0
    expected: 1
[FAIL] testGetModMediaPathsWrongDir -
[FAIL] testPathStartsWith - 0ms
```

That ok to have the failed on win64 ?

**Comment by kas1e** [comment]
@sfan5 
I find out how to disable all the unit-tests (from cmakefile list in unittest dir), so by trial-and-hack i found the guilty one : it is test_connection.cpp , which contain 3 tests, and the one which fail on me, is ```TestConnection::testConnectSendReceive()```.

I added bunch of prinfs() with delays after each function, and found, that freeze happens right when i call ```server.Serve(address);```.  It is alwas and 100% reproducable.

Can it be some endian issues there ? Is threading involved there or absolutly not and only network code is here ?

**Comment by sfan5** [comment]
> Btw, i checked also win64 build on my win10 to run unittests on, and those ones failed:

I don't know about Windows but unittests pass on Linux at any time (we have them in CI).

> and prinfs/delays in Trigger() function point out that we crash on "m_send_sleep_semaphore.post();". Exactly on this one. [...] Maybe it may wort to wrote new "unit_test" for minetest, where experiment with different .post usage, so by this way we can see if something with our semaphores implementation or it only happens when it used with network.

Yes, it sounds like you need to find out what's wrong with your semaphore implementation before Minetest can start working correctly. If you have C++20 support in your toolchain you could look up `std::counting_semaphore` and compare its implementations.

**Comment by sfan5** [comment]
> Did it mean that it was removed in favor of support platforms which can't do "proper killing" ? Or it just was too ugly-hardcore and was getting rid off ?

The destructor of `Thread` still attempts to kill a thread if it has not exited. I don't know if this is used in practice, threads are usually cleaned up the normal way.
