### ISSUE TITLE
No `overlay_tiles` test nodes in devtest

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12286]
https://github.com/minetest/minetest/blob/87472150bcb83e9cbad2f567ac536de0456ceb70/doc/lua_api.txt#L809-L850

**Comment by Wuzzy2** [comment]
Working on this.

**Comment by Wuzzy2** [comment]
PR: #12304

**Comment by Wuzzy2** [comment]
By the way, the next time you have a feature request for DevTest, notify me.

**Comment by sfan5** [comment]
Sure.
