### ISSUE TITLE
Async Main Loop

### ISSUE THREAD

**Issue by paradust7** [minetest/minetest#12282]
## Problem

Minetest currently has 5 rendering/ui loops. These can be identified by places where `driver->endScene()` is called:

https://github.com/minetest/minetest/blob/87472150bcb83e9cbad2f567ac536de0456ceb70/src/client/clientlauncher.cpp#L544
https://github.com/minetest/minetest/blob/87472150bcb83e9cbad2f567ac536de0456ceb70/src/client/renderingengine.cpp#L495
https://github.com/minetest/minetest/blob/87472150bcb83e9cbad2f567ac536de0456ceb70/src/client/renderingengine.cpp#L516
https://github.com/minetest/minetest/blob/87472150bcb83e9cbad2f567ac536de0456ceb70/src/client/game.cpp#L4020
https://github.com/minetest/minetest/blob/87472150bcb83e9cbad2f567ac536de0456ceb70/src/gui/guiEngine.cpp#L307

Each of these locations needs a loop that draws frames, handles user input, possibly checks for network I/O and other events, and sleeps between frames. In at least one case, there is not even a loop, but a linear sequence of (i) do step A, (ii) draw a frame, (iii) do step B, (iv) draw a frame, etc. that attempts to approximate a responsive UI while doing blocking work.

Problems with this situation:

1. Blocking on the main thread blocks the ui/rendering and causes the app to become unresponsive for periods of time. This includes DNS lookups and the http fetch for the server list and content list.

2. Async network I/O must poll data populated by other threads. This involves a mutex lock/unlock on the main thread, and it delays the processing of network packets until specific points in the rendering loop. For example, while the main thread is sleeping for the next frame, it cannot be interrupted to start processing a packet that has just become ready.

3. It is incompatible with Emscripten, where blocking on the main thread can have undefined/unexpected behavior.

## Solutions

Proposal is to have the main thread use an asynchronous loop pattern. This would work by having a global loop object, which can be used to:

1. Schedule timeouts or periodic events (similar to setTimeout and setInterval in javascript)
2. Schedule methods to run on the main thread from other threads.
3. Schedule methods to run when a file descriptor becomes readable/writable
4. Schedule methods to run when no other work is pending. (e.g. for "background tasks", if needed)

Existing classes that expect to have direct control over program execution need to be refactored.
In particular, ClientLauncher, Game, GUIEngine, and RenderingEngine would be most affected.

All rendering would be handled from a single method (most likely of RenderingEngine). All irrlicht events would be handled from a single place, which would dispatch events to either the GUI or the game, whichever is active.

**Comment by sfan5** [comment]
> 1. [...] and the http fetch for the server list and content list.

These already happen on a different thread btw.

> For example, while the main thread is sleeping for the next frame, it cannot be interrupted to start processing a packet that has just become ready.

This is a good point. Though if desired I can think of an easier way for network packets to be processed ASAP while "sleeping".

> 3. Emscripten, where blocking on the main thread can have undefined/unexpected behavior

Question here: What is the main thread supposed to do then? Return control and wait to be called again? Or is sleeping allowed?
This sounds like it'd be incompatible with the way many existing applications work, so it'd be interesting to know how other projects handle this.

> 3. Schedule methods to run when a file descriptor becomes readable/writable

This wouldn't be needed since the networking code already has threads polling the network.

> Existing classes that expect to have direct control over program execution need to be refactored. In particular, [...]

Are you sure you can get away with "only" touching those classes? Specifically the client also runs a server for local games and IIRC the server code needs that too.

> All irrlicht events would be handled from a single place, which would dispatch events to either the GUI or the game, whichever is active.

There is an event receiver class so this should already be the case.

All in all this is a pretty large undertaking with an unknown scope of needed changes so perhaps it's easier to refactor just the problematic parts not to block on the main thread.

**Comment by paradust7** [comment]
> These already happen on a different thread btw.

But the main thread still blocks waiting for it to complete. Examples: [here](https://github.com/minetest/minetest/blob/master/builtin/mainmenu/dlg_contentstore.lua#L214), 
[here](https://github.com/minetest/minetest/blob/master/builtin/mainmenu/dlg_contentstore.lua#L596
), and [here](https://github.com/minetest/minetest/blob/master/src/network/address.cpp#L130).

For emscripten this is a fatal problem, since some browsers (e.g. firefox) cannot do any kind of network I/O while the main thread is blocked. On desktop, it means the app becomes unresponsive if internet is slow.

> This is a good point. Though if desired I can think of an easier way for network packets to be processed ASAP while "sleeping".

Doing things the easy way is not my strong point!

I haven't put time into debugging this yet, but I've observed some amount of packet loss and packet delay, even in single player mode on a high-end Linux desktop. Localhost+UDP should be nearly guaranteed delivery. This might be a trivial bug somewhere, but even so, queuing, locking, and context switching between threads has more of an impact than people usually expect. In my experience, when you put all the time-sensitive compute on the same thread and get rid of all locks (and extra allocations), you get the best performance. Single-threaded async servers are capable of handling tens of thousands of clients simultaneously, whereas multi-threaded applications grind to a halt (from lock contention and switching overhead) after a couple hundred threads.

> What is the main thread supposed to do then?

In the default mode, main() is expected to setup callbacks (for user input, rendering, etc), and then exit. The browser calls those callbacks (on the main thread) to interface with the app. This is similar to the message loop that a typical native Windows app would be based around. Also similar to how Lua mods interact with Minetest, by registering callbacks. You never really want to sleep() on the main thread for the same reason you'd never want to sleep in init.lua... it's just wasting time while the app is stalled.

Rendering (GL command, etc) has to happen on the main thread. And the browser must regain control of the main thread before it can flip the buffer, so nothing will display at all otherwise. There is an attempt to create a compatibility layer that runs main() on a separate thread, and proxies rendering calls to the main thread. I tried to get this working, but as far as I can tell it is still years away before being ready. (and there would still be a significant performance penalty)

Anything based around an event loop can be made compatible with the web, for example, this is Godot's main loop on Linux/BSD: https://github.com/godotengine/godot/blob/master/platform/linuxbsd/os_linuxbsd.cpp#L422-L447

And for their javascript build, they have a periodic callback instead: https://github.com/godotengine/godot/blob/master/platform/javascript/os_javascript.cpp#L82-L92

I'd want to setup something similar for minetest. The non-emscripten build would just have a basic while loop with a sleep (actually a poll, so that it could wait for a wake-up signal from another thread), while the web build would set it up as a callback.

> Are you sure you can get away with "only" touching those classes?

For single-player, there's no problem running the server in a separate thread. Although multi-player server performance could probably benefit from an async io model. I haven't read through the code, but would it be correct to guess the current server spawns a new thread for each connected user? If so, that is going to be quite busy.

**Comment by paradust7** [comment]
Corrections to above:
I misread the F5 debug info and thought I saw packet loss. That's not what I was seeing at all.
As for the server threads, I forgot that all traffic is through a single UDP socket. So the server only requires one extra thread.

**Comment by sfan5** [comment]
> But the main thread still blocks waiting for it to complete.

I was thinking of the [server list code](https://github.com/minetest/minetest/blob/master/builtin/mainmenu/serverlistmgr.lua#L64), it does that correctly and runs the http fetch in an async job. I don't know why the content code doesn't do this, that's a bug with it.

> This might be a trivial bug somewhere, [...]

The networking code is old so it ~~probably~~ has a lot of lurking bugs ;-)
Here's an example that I haven't been able to figure out #9107

> I'd want to setup something similar for minetest. The non-emscripten build would just have a basic while loop with a sleep (actually a poll, so that it could wait for a wake-up signal from another thread), while the web build would set it up as a callback.

That's sounds fine, I'm just wondering how few changes you are able to get away with. Of course it's possible to rewrite more parts but in principle you just need to "unwrap" the mainmenu, loading screen and in-game loops.

> but would it be correct to guess the current server spawns a new thread for each connected user?

There are two threads that handle low-level networking (sending & receiving), with the exception of map generation and the recently added async job API all business happens on the server thread.
In that sense our design is already quite async already.

**Comment by paradust7** [comment]
i won't be working/needing this anymore
