### ISSUE TITLE
Add "issue renaming rights" to triagers

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12302]
I propose that triagers get the right to edit the title of issues and PRs. Because sometimes people post issues with a bad / confusing / vague / misleading titles which is a problem if the issue itself is legit, but because of a poor title, it will tend to be overlooked. Being able to rename them to a more useful title will help.

Bad titles are things like "Improve feature XYZ" (how?) or "Minetest crashes" (when?).

**Comment by Zughy** [comment]
This have already been discussed on IRC, and the bottom line is that GitHub doesn't allow an in-between role for what you're asking. It goes from "triager" to granting us the right to push into the repo. Also, you already knew this, as you were present during the conversation on IRC, so I don't see the point of opening an issue asking for the same thing you've already received an answer for (even if I agree with you, it's sometimes frustrating). I'll ask a core dev to have this thing as a next meeting topic, but I don't see the point of keeping the issue open. Closing

**Comment by Wuzzy2** [comment]
Sorry, my memory is terrible. :-(

**Comment by rubenwardy** [comment]
Some existing threads/issues:

* https://github.community/t/why-cant-repo-triagers-rename-or-edit-issues-and-prs/167349
* https://github.com/github/feedback/discussions/5773

We have two options to fix this: we can use a bot to change the title, or we can give triagers write access to the repo. I'm not a fan of the latter, as it increases the number of people with higher permissions
