### ISSUE TITLE
Android: Hide keychange menu when there's no keyboard

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12305]
From #11404

**Comment by erlehmann** [comment]
AFAIK Android actually supports keyboards, so taking that away might be a bad idea.

**Comment by sfan5** [comment]
Android does but I don't think this has ever worked in Minetest due to missing Irrlicht support.

**Comment by rubenwardy** [comment]
> AFAIK Android actually supports keyboards, so taking that away might be a bad idea.

Minetest doesn't support it, and it should be hidden if there's no keyboard attached - unless you change to edit controls that is

**Comment by rollerozxa** [comment]
Minetest for Android does in fact support keyboard input (at least when I tested some time ago through scrcpy)... Only thing is that it doesn't support mouse input (breaking/placing blocks and moving the camera) so you wouldn't be able to get a full desktop control scheme on Android, however this would be a different issue.

**Comment by Oblomov** [comment]
I can confirm that external keyboards work as expected in Minetest for Android, so I am against removing the possibility to configure key bindings, although I agree that itwould be a good idea to support additional configuration options for the touchscreen controls (independently from the OS, in fact)
