### ISSUE TITLE
Trying to overwrite a package when installing from ContentDB causes a crash

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest/minetest#12303]
Minetest 5.5.0
How to reproduce: 
1. Install a mod that already exists in your mod folder.
2. Observe crash.
debug:
Failed to install awesome_monsters to C:\\Users\\noure\\Downloads\\minetest-5.5.1-win64\\mods\\awesome_monsters

**Comment by rubenwardy** [comment]
Regression caused by 6de8d77e17017cd5cc7b065d42566b6b1cd076cc

core.copy_dir no longer overrides content in dest
