### ISSUE TITLE
Replace core::list with std::list

### ISSUE THREAD

**Issue by paradust7** [minetest/minetest#12312]
This is to track both pull requests.

Biggest changes were made to IGUIElement and CGUITreeViewNode. I noticed they were doing linear searches for almost every operation touching the list. So I added a field (`ParentPos`) for both of them, to make list operations constant-time.

**Comment by sfan5** [comment]
Here's my plan on merging these refactors:
* (Test them)
* Merge all three into IrrlichtMt
* Merge all three into Minetest
* Tag IrrlichtMt 1.9.0mt6
* Update version used in CI to that so everything is green again
