### ISSUE TITLE
Make it clear what stuff is public and what is private

### ISSUE THREAD

**Issue by GrimPixel** [minetest/minetest#12320]
There is no standard of saying whether a thing that contains other things, like workbench and autocrafter, can be accessed by other people. My stuff were stolen because of that.

There should be a text to indicate the owner if it is owned by default.

**Comment by SmallJoker** [comment]
Wrong issue tracker. Please enable the F5 debug information to show the node name or find another way to determine the mods that register these nodes. Afterwards open an issue in their repositories.

For example, the workbench *might be* supplied by `xdecor` and the autocrafter by `technic`. Moreover, ensure that the mods are up-to-date and an area protection mod is active. Please consult the server admin for further help.

**Comment by GrimPixel** [comment]
I mean, there is no standard for modders, so some of them assume everything is public, some assume everything is private. As for Minetest, it lacks a guideline of how to explain the ownership. This has caused confusion.
