### ISSUE TITLE
Threats detected by Avast [version 5.5.1]

### ISSUE THREAD

**Issue by zhaolinlau** [minetest/minetest#12335]
![image](https://user-images.githubusercontent.com/68846168/168504951-e7e08369-ffa9-459c-89ee-c77a5a9f11ba.png)

![image](https://user-images.githubusercontent.com/68846168/168504973-7543014e-700e-4acb-82f2-445f60e60759.png)

**Comment by IrrlichtMt4** [comment]
This is an Avast issue.

**Comment by rollerozxa** [comment]
You probably should switch to Windows Defender.

**Comment by SmallJoker** [comment]
As mentioned, blame Avast like [this guy](https://support.avg.com/answers?id=906b0000000DvC7AAK).
Both libraries are commonly used open-source files. Please report this as a falsely detected case to avoid similar issues in the future or Windows Defender which is free and reliable as well.
