### ISSUE TITLE
Wieldhand lighting impacted by night regardless of other factors

### ISSUE THREAD

**Issue by pecksin** [minetest/minetest#12338]
##### Minetest version

```
Minetest 5.6.0-dev-8756b7a73 (Linux)
Using Irrlicht 1.9.0mt6
Using Lua 5.1.5
BUILD_TYPE=Release
```
*Bisect identifies https://github.com/minetest/minetest/pull/11747/commits/387546df53b04cab3a6442f68706a968f696dd97 as the first "bad" commit*

##### OS / Hardware

Operating system: xubuntu 20.04
CPU: Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz

GPU / OpenGL:
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
OpenGL core profile version string: 4.2 (Core Profile) Mesa 21.2.6
OpenGL core profile shading language version string: 4.20
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL version string: 3.0 Mesa 21.2.6
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 21.2.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
```
_(behavior is the same on my other machine, which is dualcore athlon64 with nvidia something gpu and nouveau driver)_

##### Summary

Anything in the wieldhand is dark purple at night, regardless of local light, depth underground, or whether dynamic shadows are enabled/disabled in conf.  It seems to be using MIN(current_surface_daylight, local_light)

This might be a duplicate of #12180 but it feels unlikely judging by the screenshots there.

##### Steps to reproduce

Observe the wieldhand item with/without local bright illumination, during day/night, deep underground.

**Comment by Niklp09** [comment]
Can I confirm

**Comment by Niklp09** [comment]
![unknown](https://user-images.githubusercontent.com/89982526/168894198-9e5e7a03-ed1c-4318-af43-5bb9c384077b.png)
![unknown1](https://user-images.githubusercontent.com/89982526/168894204-b7ab08e3-25ea-444b-972b-37bdb1f89482.png)
