### ISSUE TITLE
Minimap innaccurate when underground.

### ISSUE THREAD

**Issue by KollinsPlays** [minetest/minetest#12333]
##### Minetest version 

```
Minetest 5.5.0
```

##### OS / Hardware

Operating system: Windows 10
CPU: AMD Phenom II X4

GPU model:
OpenGL version:

##### Summary

The minimap doesn't match the area you are in when underground. It appears to show the area 128 (exactly?) blocks above you when you are underground.

I have a house built on the surface and a 2x1 hole with ladders going straight down below this and when I go down the ladder, my home is still on the minimap until right around 128 blocks below the home. The home aside, nothing matches what is on the map when I am underground. I found caves, water pools, lava pools and areas made of different blocks, such as sand areas or marble areas and while exploring these areas, the map shows something else, but if I go down my ladder roughly 128 blocks below these features, they will show up on the minimap.

##### Steps to reproduce

Craft the Mapping Kit and open the map with V,
Observe that the minimap matches the terrain while exploring the surface
Observe that the minimap doesn't match where you are when exploring underground cave and such.

**Comment by rubenwardy** [comment]
This is a limitation of this mode of the minimap, it's only designed for showing the surface.

You can use the radar mode instead underground

**Comment by KollinsPlays** [comment]
> You can use the radar mode instead underground

I honestly looked for this as a previous issue before posting, but without knowing about radar, found nothing related. Searching with the word radar shows me forum topics and github issues related to this same thing, but I still can't find a forum post, wiki article or other source for how to turn this on. I did find something that indicates it's not part of the basic system and you need privileges to enable it, so even if I figure out how to turn it on, the "fix" won't work on servers if you don't have the privileges?

**Comment by Wuzzy2** [comment]
Normally, radar mode appears when you cycle through the minimap modes pressing the minimap key.

However, In Minetest Game, Radar mode is disabled unless you're in Creative Mode.

**Comment by SwissalpS** [comment]
mods like https://github.com/OgelGames/minimap_radar can enable it for players with item in inventory

**Comment by KollinsPlays** [comment]
Looks like something complex to "solve." Radar mode is something close, but not accessible without creative or the minimap radar mod, but is just a green, washed out blur and no replacement for what one would expect, which is something like what the minimap shows when you are underground. only it being accurate to the current location, not 126 blocks above the current location.

I haven't been able to figure out how to make a wiki account, but the wiki needs a better description of this:
"press the minimap [key](https://wiki.minetest.net/Controls) to display the minimap and toggle between various modes."

s/b something like "press the minimap [key](https://wiki.minetest.net/Controls) , which is V by default on PC, to display the minimap and toggle between various modes. If the player has the creative privilege, or has the Minimap Radar mod, these modes will include a radar mode,  Holding shift with the minimap key will change the minimap from a circle to a square."

This is also a bold suggestion, as I am a nobody in the Minetest community, but it sounds like the whole minimap should be pulled from the core "game" and moved into a standalone mod, where it can be put on contentdb, have it's own github page and be more easily forked, modified or replaced.

Aside from the wiki clarification, I guess this can of worms I opened (this issue) can probably just be closed.

**Comment by Zughy** [comment]
Closing as requested by the author
