### ISSUE TITLE
5.5.1 compilation error: -Ttext-segment is not supported. Use --image-base if you intend to set the base address

### ISSUE THREAD

**Issue by AngryPenguinPL** [minetest/minetest#12342]
##### Minetest version

```
5.5.1
```

##### OS / Hardware

Operating system: Linux OpenMandriva Lx Cooker
CPU: ARMv8 aarch64

##### Summary

When compiling Minetest 5.5.1 on OpenMandriva Cooker with LLVM/Clang 14.0.3 and LLD Linker I see this build error on arm aarch64 builder. Worth to add it compiles fine on other archs like x86_64 etc.

```
make[2]: Leaving directory '/builddir/build/BUILD/minetest-5.5.1/build'
DEBUG util.py:444:  ld.lld: error: -Ttext-segment is not supported. Use --image-base if you intend to set the base address
DEBUG util.py:444:  clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
DEBUG util.py:444:  make[2]: *** [src/CMakeFiles/minetest.dir/build.make:4800: ../bin/minetest] Error 1
DEBUG util.py:444:  make[1]: *** [CMakeFiles/Makefile2:627: src/CMakeFiles/minetest.dir/all] Error 2
DEBUG util.py:444:  make: *** [Makefile:159: all] Error 2
DEBUG util.py:446:  RPM build errors:
DEBUG util.py:444:  error: Bad exit status from /var/tmp/rpm-tmp.KOOjLf (%build)
```

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/f6ac1f8d7081c197d32e5b6c84fac9c74e71042f.log?show=true

##### Steps to reproduce

Try compile Minetest 5.5.1 on Linux with Clang 14.0.3 and LLD Linker.
See build error.

**Comment by sfan5** [comment]
Same issue encountered here #11263 but there's no good(?) way to detect the used linker so we only have a test for `FreeBSD`.

**Comment by Zughy** [comment]
Does this happen on new versions as well?

**Comment by sfan5** [comment]
The relevant code was removed in af38bae57f4f0f77bf2c0cf029928567e554b60b, this no longer happens.
