### ISSUE TITLE
Provide default thumbnail for content that have none

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12344]
## Problem

![immagine](https://user-images.githubusercontent.com/63455151/169096344-b9f2f786-4df5-40e1-842e-8ec63a58b5d2.png)

## Solutions
Put a default thumbnail (slightly lighter colour + question mark?)

**Comment by rubenwardy** [comment]
There's already a default, it's https://github.com/minetest/minetest/blob/master/textures/base/pack/no_screenshot.png

The most I'd do is make it a solid color, optionally with a MT logo on it. I don't think that making it too noisy or look like an error helps
