### ISSUE TITLE
Physics: Acceleration is severely broken

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12340]
See https://github.com/minetest/minetest/pull/11855, which partially fixes this in relation to players.

**Physics are currently fundamentally and severely broken:** Acceleration does not work the way it should as outlined in the PR; objects accelerate faster than they should. This has consequences for all kinds of use cases where modders (and the engine) may use acceleration:

* Friction/drag of entities;
* Increase in speed of entities (i.e. towards a target);
* Most fundamentally: Gravity

First of all, the physical units can't be applied; an acceleration of `{x=0, y=-9.81, z=0}` does not have the same effect as the gravitational constant of an acceleration of `9.81m/s²`; acceleration is not the second derivative of location/position.

For the sake of simplicity, let's assume the object only has an acceleration `a` and initial position `s` and initial velocity `v` are both zero. Then the position of the object after the first step of duration `t` would be given as `s' = at²/2`; due to the currently used incorrect formula it's actually calculated as `s' = v't = at²`. The error (difference between these two values) can trivially be seen to be `s' = at²/2`: In the first server step, the position is off by 100%! In subsequent server steps however, as the velocity rises linearly, the percentual error shrinks; it can be calculated as `d/t` where `d` is the stepsize and `t` is the total time (hence 100%). 

Consequences:

* The percentual error with constant stepsizes `d` after a time `t` has passed is `d/t`
* The **larger the stepsize (i.e. "lag"), the larger the error** but also **the shorter the time, the larger the error** (which is why jump heights are off)
* This means that the absolute error after a time is `d/t * at²/2` = dat/2` - a constant velocity of `da/2` is constantly added
* It is impossible for modders to fix this as the size of the steps run client- & serverside is a factor in the equation; constantly setting position or acceleration manually would just yield larger errors.
* This leads to a client-server desync due to different stepsizes (different stepsizes, different errors, different final object positions)

In conclusion, most ballistics are severely broken: Objects travelling a long distance with the same initial velocity & acceleration hit at vastly different positions because **serversteps** become a factor in the calculation and these may vary based on factors like lag. Jump height is very broken too.

Now, what works properly in the current movement code and may not be broken?

* Linear movement (velocity) and the resulting change of position works just fine;
* Increase in velocity through acceleration works just fine

I thus demand this issue be assigned high priority and put on the roadmap immediately, even though fixing it either requires (1) a flag / object property for all entities (which may obviously only be respected by newer clients, causing all kinds of horrible issues on older clients) or (2) a major release of Minetest (6.0).

Below is a small Lua script that calculates both correct & incorrect position as well as the error, simulating entity movement for 10 secs:
```lua
local dt, a = ...
dt, a = tonumber(dt) or 0.5, tonumber(a) or 9.81
local v = 0
local s_correct = 0
local s_incorrect = 0
for t = 0, 10, dt do
	print("t", t, "s_c", s_correct,  "s_i", s_incorrect, "err", (s_incorrect - s_correct) / s_correct)
	local prev_v = v
	v = v + a*dt
	s_incorrect = s_incorrect + v*dt
	s_correct = s_correct + (prev_v + v) / 2 * dt
end
```
and the output for the first second:
```lua
t	0	s_c	0	s_f	0	err	-nan
t	0.1	s_c	0.04905	s_f	0.0981	err	1
t	0.2	s_c	0.1962	s_f	0.2943	err	0.5
t	0.3	s_c	0.44145	s_f	0.5886	err	0.33333333333333
t	0.4	s_c	0.7848	s_f	0.981	err	0.25
t	0.5	s_c	1.22625	s_f	1.4715	err	0.2
t	0.6	s_c	1.7658	s_f	2.0601	err	0.16666666666667
t	0.7	s_c	2.40345	s_f	2.7468	err	0.14285714285714
t	0.8	s_c	3.1392	s_f	3.5316	err	0.125
t	0.9	s_c	3.97305	s_f	4.4145	err	0.11111111111111
t	1	s_c	4.905	s_f	5.3955	err	0.1
```

**Comment by IrrlichtMt4** [comment]
How acceleration works have always felt weird in Minetest.
