### ISSUE TITLE
minetest.spawn_falling_node, return objectRef if successful.

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#12348]
## Problem

There is no clear way to get an ObjectRef of a falling node

## Solutions

Make it return the Object ref if successful and false if failed

## Alternatives
You can get_objects_inside radius but that runs the risk if picking up other entities, and running a loop to check if it's a falling node may cause performance issues

**Comment by appgurueu** [comment]
> ## Alternatives
> 
> You can get_objects_inside radius but that runs the risk if picking up other entities, and running a loop to check if it's a falling node may cause performance issues

Another hacky alternative: You can override `minetest.add_entity` to "catch" the spawned entity :-)

**Comment by sfan5** [comment]
Quoted from the docs:
> * `minetest.spawn_falling_node(pos)`
    * Change node into falling node
    * Returns `true` and the ObjectRef of the spawned entity if successful, `false` on failure

**Comment by appgurueu** [comment]
FWIW just returning the object ref would be slightly neater in terms of API convenience (but would be a breaking change).

**Comment by Extex101** [comment]
> Quoted from the docs:
> 
> > * `minetest.spawn_falling_node(pos)`
> >   * Change node into falling node
> >   * Returns `true` and the ObjectRef of the spawned entity if successful, `false` on failure

Oh, I was referring to the wrong lua_api.txt. I was looking at an old one. My bad.
