### ISSUE TITLE
Ladies and gentlemen, this is mambo n°5

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#12345]
https://youtu.be/watch?v=EK_LN3XEcnw

**Comment by Warr1024** [comment]
https://youtu.be/watch?v=a6iW-8xPw3k

**Comment by pecksin** [comment]
https://youtu.be/watch?v=_JNGI1dI-e8

**Comment by appgurueu** [comment]
https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by SmallJoker** [comment]
[Bullshit issue caused by a cool number. Continue with a closed one, if you really want to.](https://www.youtube.com/watch?v=2ocykBzWDiM)
