### ISSUE TITLE
Prefer internal GUIElement/formspec classes whenever possible 

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12366]
We have many (modified) copies of Irrlicht GUI code., yet sometimes code still references the Irrlicht implementation. These occasions should be changed to use our own class.
**Why?** -> So the formspec classes we don't need can be deleted from IrrlichtMt

### Button
internal ctor: `GUIButton::addButton`
uses:
<pre>
src/gui/touchscreengui.cpp
156:	IGUIButton *starter_gui_button = m_guienv->addButton(starter_rect, nullptr,
241:	IGUIButton *btn_gui_button = m_guienv->addButton(current_button, nullptr, button_id,
416:	IGUIButton *btn_gui_button = m_guienv->addButton(button_rect, nullptr, id, caption.c_str());
434:	IGUIButton *btn_gui_button = m_guienv->addButton(button_rect, nullptr, id, L"O");
</pre>

### StaticText
internal ctor: `gui::StaticText::add`
uses:
<pre>
src/client/clientlauncher.cpp
227:			guiroot = m_rendering_engine->get_gui_env()->addStaticText(L"",
</pre>

^ this one is weird, in theory we shouldn't be needing it at all

**Comment by Desour** [comment]
Reopening due to #13744.

**Comment by Desour** [comment]
Why close? Touchscreengui still doesn't use our guibottons.

**Comment by sfan5** [comment]
I think it doesn't make much sense to work on this now since formspecs should get a big rework anyway.
Also with irrlicht imported you could also just properly merge the gui code.
