### ISSUE TITLE
How can I connect a specific server by default directly with last login account automatically.

### ISSUE THREAD

**Issue by lychees** [minetest/minetest#12360]
## Problem
How can I connect a specific server by default directly with last login account automatically.

**Comment by SwissalpS** [comment]
When my client exits normally, the next time I start it up, last used server and username is already selected/filled in.
What platform/OS are you using?

**Comment by Zughy** [comment]
Is this about having the client memorising the last access for every specific server?

**Comment by lychees** [comment]
> When my client exits normally, the next time I start it up, last used server and username is already selected/filled in. What platform/OS are you using?

Hi, thanks for your help. 
I mean I want the client can direct connect to the last server automatally, without going to the server list menu.

**Comment by SwissalpS** [comment]
`minetest --password monkey123 --name myNick --address example.com --port 30000 --go`
worked for me.

**Comment by lychees** [comment]
Thanks, it works!
