### ISSUE TITLE
InvRef:get_list(listname) can return nil

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12361]
##### Minetest version
```
5.5.0
```

##### Summary
If you call `InvRef:get_list(listname)` but the inventory list `listname` does not exist yet (i.e. the size was not set with `InvRef:set_size`), the function will return nil.

However, the documentation does not say this function can return nil.

##### Steps to reproduce
* Call `player:get_inventory():get_list("a_list_that_does_not_exist")` in Lua

**Comment by Zughy** [comment]
What do you expect to return exactly? A hard crash? It seems the best output to me :\

**Comment by Wuzzy2** [comment]
It's a documentation issue. If some function can return nil, the documentation should state that.

**Comment by Zughy** [comment]
I mean, if it doesn't crash, I expect to turn nil by default, without no need to state it inside the documentation. Also because I'm pretty sure we should document a lot of functions if we apply this logic to the whole documentation
