### ISSUE TITLE
Can not use interactive terminal when use Ubuntu Snap version

### ISSUE THREAD

**Issue by Garfield550** [minetest/minetest#12376]
##### Minetest version

```
Minetest 5.4.1 (Linux)
Using Irrlicht 1.8.4
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
USE_FREETYPE=1
STATIC_SHAREDIR="/share/minetest"
STATIC_LOCALEDIR="/share/locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04.4 LTS
CPU: Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz

GPU model:
OpenGL version:

##### Summary

I installed Minetest from snap, and use it to run a Minetest server, but when I use `--server --terminal` command args, Minetest show an error message: `ERROR[Main]: Cmd arg --terminal passed, but compiled without ncurses. Ignoring.`.

```
2022-05-25 10:19:58: WARNING[Main]: system-wide share not found at "/share/minetest"
2022-05-25 10:19:58: WARNING[Main]: system-wide share found at "/snap/minetest/1744/bin/../share/minetest"
2022-05-25 10:19:58: WARNING[Main]: Couldn't find a locale directory!
2022-05-25 10:19:58: ERROR[Main]: Cmd arg --terminal passed, but compiled without ncurses. Ignoring.
```

##### Steps to reproduce

```
sudo snap install minetest
minetest --server --terminal
```

**Comment by Garfield550** [comment]
Ref: https://github.com/snapcrafters/minetest/issues/11

Hope can make `ncurses` builtin.

**Comment by rubenwardy** [comment]
Minetest needs to be compiled with ncurses to use this feature.

You have 2 options:

- Use another version, probably self-compiled. I don't think many distros have Minetest with ncurses enabled
- Ask the snap maintainers to compile with ncurses

The Minetest snap is maintained by the Snap team, not by us, so you'll need to [file an issue with them](https://github.com/snapcrafters/minetest/issues)

The snap version is also a year out-of-date

**Comment by Garfield550** [comment]
@rubenwardy Does Flatpack version had `ncurses` built-in or it contain Minetest Server? https://flathub.org/apps/details/net.minetest.Minetest

**Comment by rubenwardy** [comment]
Unfortunately not (source https://github.com/flathub/net.minetest.Minetest/blob/master/net.minetest.Minetest.yaml#L42 )

**Comment by Garfield550** [comment]
@rubenwardy I see a ppa at https://launchpad.net/~minetestdevs/+archive/ubuntu/stable, is it official?

**Comment by rubenwardy** [comment]
> @rubenwardy I see a ppa at [launchpad.net/~minetestdevs/+archive/ubuntu/stable](https://launchpad.net/~minetestdevs/+archive/ubuntu/stable), is it official?

That is official. I've just checked, it does include ncurses
