### ISSUE TITLE
Build Minetest Blockchain

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest/minetest#12371]
## Problem

Minetest Blockchain  Awesome Features

## Solutions

- [ ] Voice chat on servers
> It is helpful to be able to talk by voice in addition to text chat, which is built into Minetest.

- [ ] Game Server . Running on blockchain nodes
> We don't need to buy vps. we can play with people from other countries all over the world.
We like to run our own server, it's more free, with full permissions, add mods permissions.

- [ ] Minetest games run on the Blockchain cloud and do not require a download

**Comment by rollerozxa** [comment]
How would you ever be able to "Run a Minetest server on the Blockchain"?

**Comment by Pantyhose-X** [comment]
> How would you ever be able to "Run a Minetest server on the Blockchain"?

blockchain node

**Comment by Zughy** [comment]
Why exactly voice chat should be done using blockchain when it can already be built without? More broadly, why should Minetest use Web3 when it's already decentralised? Related: https://vimeo.com/677162808
