### ISSUE TITLE
Avoid typing everytime the password

### ISSUE THREAD

**Issue by amreo** [minetest/minetest#12384]
## Problem

I have to type every time a password for logging to the MT servers, and I tend to prefer simple and guessable(=in dictionary) password given the fact as a user I don't consider "user thief" a big security threat.

## Solutions

- Add the possibility to memorize the users credentials per server
- Add support to keepassxc password manager

## Alternatives

Type the password every time

## Additional context

I think the user tend to prefer simple and guessable/insecure passwords.

**Comment by Zughy** [comment]
Duplicate of #1566, closing
