### ISSUE TITLE
split screen for local multiplayer

### ISSUE THREAD

**Issue by Darin755** [minetest/minetest#12386]
## Problem

I would like to be able to play with a different person on the same machine. I have a computer connected to the TV and Xbox controllers connected via antimicrox.

## Solutions

I was thinking that one player could have the controls wasd and the other player could have the arrow keys. I could easily map the controllers to the respective keys.

## Alternatives

Minetest supports local multiplayer well but that does not work well on a TV with Xbox controllers.

**Comment by FatalError42O** [comment]
Most modern PC games don't have splitscreen support, it's un heard of, and frankly even on Xbox splitscreen is being phased out. I don't think this is a feature that should be prioritized in any capacity unfortunately. It's niche, practically nobody would use it, and it'd require a lot of implementation.

**Comment by Darin755** [comment]
I honestly think split screen is probably one of the best features a game can have

**Comment by FatalError42O** [comment]
_you_ do but I sincerely doubt anybody shares that opinion. It's just not practical or sensible for a PC game like this, especially one designed for online play. There'd be many challenges making it work for this game from what I understand, and it's a feature nobody needs or wants. In a perfect world there could be this feature, however I do not see this happening. If you want to play with someone else in your house, just set up LAN.

**Comment by Darin755** [comment]
All well . . . 
I'm going to close this issue since split screen does not seem like a high priority.

**Comment by rubenwardy** [comment]
I personally find it a shame how there are fewer split screen games these day. That being said, Minetest isn't really designed for this and I don't think it should be a priority

The workaround would be to set up a LAN party or look into software that allows using different keyboards for different processes/VMs

**Comment by rubenwardy** [comment]
"I don't think this should be a priority" + "non-trivial" = "won't add" typically

**Comment by Zughy** [comment]
That's a pity, but I understand

**Comment by Shadowblitz16** [comment]
> Most modern PC games don't have splitscreen support, it's unheard of, and frankly even on Xbox splitscreen is being phased out. I don't think this is a feature that should be prioritized in any capacity unfortunately. It's niche, practically nobody would use it, and it'd require a lot of implementation.

I would use it so that I can play with my freinds who don't have another computer.

**Comment by Cwpute** [comment]
I'd like to add my voice here. Multiple people playing this game in my household, usually two together. We only have two computers which is already TWO MORE than many other families cna afford, and couch-coop (or multiplayer splitscreen however you would want to call it) would definitely help us play together more easily. This will allow some of us to use another one of these computers for work while others play together. Also it does not weigh too much into this decision i think but having two computers running at the same time is twice the power consumption.
Another argument that could be made is that it would be possible to play together without an internet connection or a LAN connection. Frankly being able to play with Luanti in multiplayer completely OFFLINE would be a real treat.
Finally, please take into consideration how all prices for computer parts have had a hike in price, which makes new computers quite pricey, and will make capable smartphones real pricey as well.

**Comment by SmallJoker** [comment]
Native support is likely preferred by players but implementing that *in the same application* is somewhat difficult if it wasn't designed to handle multiple instances. Luanti was built from ground-up for one player. This is a very non-trivial request.

However, spawning multiple processes and assigning controls to them would be possible. What I found so far (but did not test):
* https://www.splitscreen.me/ (Nucleus Co-Op)
* https://universalsplitscreen.github.io/

**Comment by Cwpute** [comment]
Thanks @SmallJoker but these are solutions for Windows. I found however a promising alternative for Linux, doing essentially the same thing and called Partydeck: https://github.com/partydeck/partydeck

I'm not sure how it would work though, having two instances of the same game run on the same computer, how would the two of them communicate ? a mocked LAN connection ?

**Comment by SmallJoker** [comment]
> how would the two of them communicate ?

Host a server with one, join with the other. IP address 127.0.0.1 (localhost).

**Comment by Shadowblitz16** [comment]
This is not as simple as hosting a server and connecting to it.
It's about playing on a single tv with multiple players with controllers.

You can't really do that with servers or window (game window) arranging apps.
Also all the window (game window) arranging apps are windows (microsoft windows) only.
