### ISSUE TITLE
Items disappear when mod wasn't loaded

### ISSUE THREAD

**Issue by mase76** [minetest/minetest#12387]
After updating Minetest to 5.5.0 on my Debian Gnu/Linux server, all doors from a mod disappeared. No unknown nodes, simply gone. I restored a Postgresql dump, and everything was fine again.
Yesterday I updated to 5.5.1 and did a mod update in one run. After I restarted my server, a lot of items disappeared. I noticed a load_mod_mesecons_gamecompat = false at the end of the settings. This seems to me a new additional mod in mesecons. My logfile told me, that a huge amount of mods could not be loaded because of missing dependencies. See here: https://pastebin.com/JWn6enWE
After I enabled  load_mod_mesecons_gamecompat, all dependencies were ok again. However the items did not return. I restored a nightly Postgresql dump, and everything is fine again. But I think, this should not be the normal behaviour, when a mod could not be loaded, all items are deleted. I don't know, what could have gone wrong on my side.

**Comment by rubenwardy** [comment]
The new mod load thing is fixed by #12217 

Not sure why the items disappear

**Comment by mase76** [comment]
I mean nodes. Not sure about entities or inventories, because after my restore, everything is ok again. I will try to reproduce this on a local game later.

**Comment by mase76** [comment]
I reproduced the issue again on my server with Postgresql. I disabled the loading of mesecons. Nodes simply disappear completely and they will not return after enabling the mod again. Inventories are just shown as unknown.

**Comment by rubenwardy** [comment]
Can't reproduce with sqlite on the latest dev.

Are you using any mods which delete unknown nodes? Like, a clean up / server mod

**Comment by mase76** [comment]
Damned! You are right! Shame on me! I forgot to disable the servercleaner mod.
