### ISSUE TITLE
Minetest on a Mac OS X 10.14.6 crashes when connected to a server

### ISSUE THREAD

**Issue by sparky4** [minetest/minetest#12394]
##### Minetest version
5.5.1

##### OS / Hardware

Operating system: Mac OS X 10.14.6
CPU: Intel of a Mac Book Pro

##### Summary
minetest crashes when it's modded and connected to a server. but works with no mods

##### Steps to reproduce
connect to a server with mods. the server is Linux Forks. i think it might be the smart shops causing the crash.

here is the top of the crash report. i can ask for a full dump.
![Screen_Shot_2022-05-31_at_1 17 42_PM-](https://user-images.githubusercontent.com/8118902/171476042-6f60643b-604a-4523-b545-5eab68e28913.png)

**Comment by sfan5** [comment]
A complete crash report (hopefully including symbols) would be very helpful.
