### ISSUE TITLE
Graphical glitches with OpenGLES 2 when both shaders and fog is disabled

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#12390]
##### Minetest version
```
stable 5.5.1 and 5.6.0-dev (compiled 2022-05-24)
```

##### OS / Hardware
Device: Nokia 5.4
Operating system: Android 11
CPU: Snapdragon 662 
GPU model: Adreno 610

##### Summary
When the video driver is set to OpenGLES 2 and shaders are disabled, disabling fog (either by disabling the fog setting or enabling unlimited viewing range) makes both terrain and objects "foggy".

![bild](https://user-images.githubusercontent.com/60856959/171116545-027a945b-00ae-4a2d-bad6-a47f92cd8c04.png)

##### Steps to reproduce
1. Switch the video driver to ogles2 and restart Minetest.
2. Check so that shaders are disabled in the settings tab. (usually disabled by default on Android)
3. Go into a world and enable unlimited viewing range.

**Comment by mieu12** [comment]
Can confirm. There is also a similar bug with shaders enabled with OglesV2 builds when the renderer does not respect how high the render distance is when shaders are enabled

**Comment by AbduSharif** [comment]
I can't reproduce on stable 5.5.1, with whether fog is disabled or with "unlimited view distance" toggling.

I tested with both 50 and 120 view distance, with a ll graphics on or off too.

Do you see any errors in the debug.txt file? Is your build perhaps missing those shaders?
https://github.com/minetest/irrlicht/tree/master/media/Shaders

**Comment by AbduSharif** [comment]
Here's what I see:
https://user-images.githubusercontent.com/57298920/171140941-68ffec77-689a-44e4-a152-4493bd7f2c2c.mp4

**Comment by AbduSharif** [comment]
Here are my settings for the test I did right now:
```
smooth_lighting = true
enable_3d_clouds = true
enable_shaders = false
fps_max = 60
maintab_LAST = settings
menu_last_game = minetest
fps_max_unfocused = 25
viewing_range = 50
video_driver = ogles2
enable_mesh_cache = true
mesh_generation_interval = 5
meshgen_block_cache_size = 250
enable_waving_leaves = false
mip_map = false
trilinear_filter = false
enable_waving_plants = false
bilinear_filter = false
tone_mapping = false
fsaa = 0
leaves_style = simple
node_highlighting = box
enable_waving_water = false
touchscreen_threshold = 20
anisotropic_filter = false
fov = 65
selected_world_path = /storage/emulated/0/Android/data/net.minetest.minetest/files/Minetest/worlds/world1
mainmenu_last_selected_world = 2
enable_damage = false
cloud_radius = 15
transparency_sorting_distance = 10
falling_trees = true
biome_blend = true
enable_stamina = false
mcl_keepInventory = true
mcl_translucent_ice = true
mcl_generate_fallen_logs = true
mcl_node_particles = low
give_initial_stuff = true
screen_h = 720
enable_particles = true
screen_w = 1480
enable_fog = true
connected_glass = true
creative_mode = false
opaque_water = true
server_announce = false
```

**Comment by AbduSharif** [comment]
Here is mytest with the latest commit artifact (signed with an app, also made sure to install the shaders above since they're missing for whatever reason from the build artifact):

https://user-images.githubusercontent.com/57298920/171144879-fbf22829-aea3-4d5b-89e6-644042539525.mp4

Using the same config file with the settings above.

**Comment by AbduSharif** [comment]
My testing device is Samsung Galaxy Note 9 with Android 10.
CPU: Exynos 9810
GPU: Mali-G72 MP18

**Comment by mieu12** [comment]
You need to test with glesv2 builds: Example use Sfan5's build: https://kitsunemimi.pw/tmp/minetest-5.5.0-52c0384-gles-win64.zip

**Comment by AbduSharif** [comment]
I'm using Android not Windows.
And can't compile builds.

**Comment by rollerozxa** [comment]
GLES2 is on both, that's just a prebuilt Windows binary compiled with GLES2 support (normally it's compiled with only OpenGL support)

**Comment by Zughy** [comment]
Can't reproduce on Linux, it'd be nice to have at least another user confirming the bug on Android

**Comment by IrrlichtMt4** [comment]
I'm not good at doing builds but try building Minetest with GLESV2.

**Comment by rollerozxa** [comment]
> I'm not good at doing builds but try building Minetest with GLESV2.

Thanks for the unnecessary advice.

While this issue was bumped anyways, I wasn't able to reproduce this bug with OpenGLES2 on Mesa (Linux) a while back, so I assume it is something GPU specific.

...Of course, this also *only* happens with shaders disabled (my OGLES2 by default PR enables shaders), so the culprit would be in the non-shader fog implementation which is hopefully gonna go *poof* soon enough anyways. Most players even if their hardware were affected would not notice it unless they explicitly disable the shaders setting.

**Comment by wwar-XeStro** [comment]
hmmm.... android 4.4.4 galaxy tab E

Works fine here with and without shaders. Only some fps lag after using unlimited view range because you know a bit old...

**Comment by sfan5** [comment]
I can reproduce this on Linux with Mali-G31 GPU, the [drivers](https://github.com/Mesa3D/mesa/blob/main/docs/drivers/panfrost.rst) are however documented to be **non-conformant**.
Conversely with our own shaders enabled, the fog does not render and nodes just appear into the view cone:
![screenshot_20220802_185722](https://user-images.githubusercontent.com/1042418/182453023-bf70bd1b-2769-4fa4-a8a6-d259b6ce9406.png)

**Comment by IrrlichtMt4** [comment]
I'm not good at doing builds but try building Minetest with GLESV2. Was meant to be I'm not good at doing builds but try building Minetest with Windows...

**Comment by numberZero** [comment]
One note: GLES2 *requires* shaders, period. With it, “disabling shaders” in Minetest merely means using Irrlicht builtin shaders instead.

**Comment by AbduSharif** [comment]
Note that I have Irrlicht shaders installed too, I wonder if that's why they I don't get the issue.

**Comment by numberZero** [comment]
> the fog does not render and nodes just appear into the view cone:

That’s not what I see on the screenshot. I *do* see the fog. What I don’t see is smooth transition, it is abrupt instead. But it is definitely fog and not far plane clipping.

May there be not enough range in some variables involved in fog computation?

**Comment by AbduSharif** [comment]
We use highp for fog on OpenMW Android port, it causes issues otherwise.

**Comment by sfan5** [comment]
We have floats default to mediump so that might be it.
https://github.com/minetest/minetest/blob/6d45c243f85942b20dab58753e735ec89a68f710/src/client/shader.cpp#L645-L662

**Comment by numberZero** [comment]
@sfan5 That header is only used when shaders are enabled. But Irrlicht own shaders may very well have the same issue. Explicit `highp` keywords would solve it then and they are also allowed in e.g. GLSL 1.4 (GL 3) but cause problems in GLSL 1.2 (GL 2) IIRC.
