### ISSUE TITLE
Serialized Block Cache uses implicitly deleted hash function (gcc-10)

### ISSUE THREAD

**Issue by neoh4x0r** [minetest/minetest#12408]
**Operating System**: Debian 11 (Bullseye)
**Compiler**: gcc-10

Found in <some commits> prior to and including
```
minetest:381f84ee2788eb462999701e902bd22271cfcb2e
irrlichtMT:426730bf9196f92bcb5f317abb8d082e3a6bbba3
```

**Relavent commits (Minetest)**:
```
Cache serialized mapblocks during sending		1fa4f58080b068920d7611291709377072d0cd00 
Fix hash implementation for SerializedBlockCache	5daafc9d336d3f946854874e56a38ae9ac130811
```

**Relavent commits (IrrlichtMT)**:
```
Add hash for vector2d and vector3d			6928c7eb6f00a00df4efcf1a1ec8f2310609696b
```

**This is the error being generated**

```
In file included from /home/william/git_stored_files/minetest/externals/minetest/src/client/clientlauncher.cpp:22:

/home/william/git_stored_files/minetest/externals/minetest/src/server.h: 

In member function ‘size_t Server::SBCHash::operator()(const std::pair<irr::core::vector3d<short int>, short unsigned int>&) const’:

/home/william/git_stored_files/minetest/externals/minetest/src/server.h:433:28:

error: use of deleted function ‘std::hash<irr::core::vector3d<short int> >::hash()’

  433 |    return std::hash<v3s16>()(p.first) ^ p.second;
      |         
                         ^
In file included from /usr/include/c++/10/bits/basic_string.h:6797,
                 from /usr/include/c++/10/string:55,
                 from /home/william/git_stored_files/minetest/externals/minetest/src/util/string.h:25,
                 from /home/william/git_stored_files/minetest/externals/minetest/src/gui/modalMenu.h:24,
                 from /home/william/git_stored_files/minetest/externals/minetest/src/gui/mainmenumanager.h:25,
                 from /home/william/git_stored_files/minetest/externals/minetest/src/client/clientlauncher.cpp:20:
/usr/include/c++/10/bits/functional_hash.h:101:12:

note: ‘std::hash<irr::core::vector3d<short int> >::hash()’ is implicitly deleted because the default definition would be ill-formed:

  101 |     struct hash : __hash_enum<_Tp>
```

**Comment by sfan5** [comment]
It sounds like you don't actually have IrrlichtMt with the mentioned revision cloned/installed. Either `1.9.0mt6` or that revision will definitely work, our CI uses the tag and is all green.

**Comment by neoh4x0r** [comment]
> It sounds like you don't actually have IrrlichtMt with the mentioned revision cloned/installed. Either `1.9.0mt6` or that revision will definitely work, our CI uses the tag and is all green.

I built and installed irrlichtMT from the latest commit that you pushed on June 1 2022.
```
commit 426730bf9196f92bcb5f317abb8d082e3a6bbba3 (HEAD, origin/master, origin/HEAD, master)
Author: sfan5 <sfan5@live.de>
Date:   Wed Jun 1 23:31:50 2022 +0200
    Don't crash attempting to scale zero-sized images
    fixes minetest/minetest#12393
```

When I compile minetest, it says that it found IrrlichtMt 1.9.0.
After looking at the CI build log https://github.com/minetest/minetest/runs/6746154217

The only difference that I see is that I am using gcc-10.2.1 and the CI uses gcc-10.3.0.

**Comment by sfan5** [comment]
Please confirm the following:
1. open `irrlichtmt/vector3d.h` in your install location, search for `hash<T>`. there should be results.
2. check `CMakeCache.txt` and compare the value for `IrrlichtMt_DIR` with your installation path for irrlichtmt

**Comment by neoh4x0r** [comment]
> Please confirm the following:
> 
> 1. open `irrlichtmt/vector3d.h` in your install location, search for `hash<T>`. there should be results.
> 2. check `CMakeCache.txt` and compare the value for `IrrlichtMt_DIR` with your installation path for irrlichtmt

Well....it seems it was using some old files in /usr/local/ instead of the new prefix I had installed it to.

After deleting those old files, it was using the correct location and compiled successfully.
