### ISSUE TITLE
Strange Black Shadows with plantlike

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#12404]
Last Minetest Version

Pic is very descriptive:

![strange_black_shadows](https://user-images.githubusercontent.com/13217027/171996665-07766636-2ab6-4cbd-889f-8b0fc6f66f31.png)

**Comment by NathanSalapat** [comment]
Did you forget to add sunlight_propagates to the node def?
Looks like either that or a paramtyoe being set wrong, without code I can't be sure though.

**Comment by runsy** [comment]
> Did you forget to add sunlight_propagates to the node def? Looks like either that or a paramtyoe being set wrong, without code I can't be sure though.



> Did you forget to add sunlight_propagates to the node def? Looks like either that or a paramtyoe being set wrong, without code I can't be sure though.

Thanks, thre was that.

Closed.
