### ISSUE TITLE
Leveled `plantlike` or `plantlike_rooted` node with `visual_scale` is too high

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12400]
##### Minetest version
```
5.5.0
```

##### Summary
If you have a node that is `leveled`, and with drawtype=`"plantlike[_rooted]"` and has a `visual_scale ~= 1.0`, then the plant height is too high/too low (depending on whether `visual_scale` is larger or smaller than 1.0).

##### Analysis

This is a bug because the documentation explicitly states that `leveled` in combination with `plantlike_rooted` will increase the plant height by steps of 1/16. Therefore, the expected behavior is that `visual_scale` does not affect height.

##### Steps to reproduce

Create a mod with this dummy node:

```
minetest.register_node(
      "example:alga_on_dirt"
      {
         description = "Alga on Dirt",
         drawtype = "plantlike_rooted",
	 selection_box = {
            type = "fixed",
	    fixed = {
               { -0.5, -0.5, -0.5, 0.5, 0.5, 0.5 }, -- base
               { -6/16, 0.5, -6/16, 6/16, 1.5, 6/16 }, -- plant
	    },
	 },
         collision_box = {
            type = "regular",
         },
	 visual_scale = 1.5,
	 paramtype2 = "leveled",
	 place_param2 = 16,
         tiles = {name="default_dirt.png"},
         special_tiles = {{name="example_alga.png", tileable_vertical=true}},
         walkable = true,
         groups = {snappy = 2, dig_immediate = 3},
    })
```

This creates an "Alga on Dirt" node. Is is a leveled `plantlike_rooted` node. When placed, param2 is init'ed with 16, which should be equivalent to exactly 1 node. However, when you actually place this, the "plant" will have a height of 1.5 nodes because of the visual size. If you add this to DevTest, you can adjust param2 with the param2 tool. Compare the result when `visual_scale` is the default value.

What I expect is that the height is always fully determined by param2, and that `visual_scale` only affects the X and Z size in this special case, but not Y. This will be then in compliance with the documentation.

### Compatibility concerns

None. The documentation explicitly stated how the node should behave so if a node depends on the current broken behavior, that's their problem, not Minetest's.

**Comment by erlehmann** [comment]
@Wuzzy2 do you have any idea if this affects the kelp in MineClone2?

**Comment by Wuzzy2** [comment]
Yes.
It does *not* affect the kelp in MineClone 2 because `visual_scale` of the kelp nodes is not set, therefore it is the default value (1). The bug only triggers if ALL of the conditions mentioned in my summary are met.

**Comment by Wuzzy2** [comment]
I no longer like my proposed solution. Forcing the height of leveled nodes like this leads to a weird stretched appearance. So probably this should only be a documentation fix.

Also, as a more general solution, `visual_scale` could be changed to support all 3 axes for more flexibility.

**Comment by Zughy** [comment]
> Therefore, the expected behavior is that visual_scale does not affect height

To me, a parameter called `visual_scale` means it's gonna override whatever basic visual value of the node, so I personally see no bug nor documentation fix needed in here. It behaves like I expect it to behave

**Comment by erlehmann** [comment]
> EDIT: possible close label due to sfan like

Did you seriously both tag and close this due to a single thumbs up from a coredev? Or was there more to it?

**Comment by Wuzzy2** [comment]
To be fair, this idea wasn't the greatest to begin with.

**Comment by erlehmann** [comment]
It iwas just the level of apparent mind-reading that irritated me.
