### ISSUE TITLE
Proposal: Refactoring RenderingCore stack

### ISSUE THREAD

**Issue by x2048** [minetest/minetest#12411]
Refactoring rendering core

Goal
----

1.Create a rendering core that can support the following features:

  - Fixed rendering pipeline (opengles1 / OpenGL 1.4)
  - Optional postprocessing when shaders are supported
  - Stereo modes
  - Up- and down- scaling

2. Avoid complex in-memory arrangements and object dependencies.

Proposal (Alternative A)
--------

Convert current RenderingCore implementations into a hierarchy of RenderingStep implementations, for each high-level rendering step.

Each rendering step has roughly the following interface:
```
class RenderingStep
{
public:
	// update textures and internal state when rendering core state changes
	void update(... state) = 0;
	// draw recursively
	void draw(RenderingStep *next_step) = 0;
	// prepare render target for the previous step
	void prepareOutput() = 0;
	// submit rendered state from the previous step
	void submitTexture(video::ITexture *texture) = 0;
private:
	RenderingStep *previous_step;
};
```

Interface between rendering states:
* Each step calls previous_step->draw(this) every time it needs input from the previous step
* Each step calls one of the following in its draw():
	- `next_step->prepareOutput()` when it needs output to draw the final image
	- `next_step->submitTexture(texture)` when it has a texture to submit to the text step. This is used between shadow renderer and 3D step

Calling the pipeline is calling `final_step->draw(screen_output)` where screen_output sets the default render target.

Example arrangements of the pipeline:

| Arrangement | Linked list of steps               |
| ------------------ | --------------------------------------- |
| Fixed pipeline |  Screen Output -> HUD -> 3D |
| PostProcessing + Shadow mapping | Screen Output -> HUD -> Post-processing -> 3D -> Shadow Mapping |
| Anaglyph + PostProcessing | Screen Output-> HUD -> Anaglyph (left+right) -> Post-processing -> 3D |
| Side-by-side + PostProcessing + Shadow Mapping | Screen Output -> Side-by-side -> HUD -> Post-rocessing -> 3D -> Shadow Mapping |

Description of the changes
--------------------------

* Extract shared state of RenderingCore into RenderingCoreState
* Add RenderingStep interface
* Implement RenderingStep for each of the drawing operations:
  
  * 3D (scene, selection, wield, block boundaries)
  * 3D Post effect
  * Post-processing
  * HUD (inventory, minimap, chat, formspecs)
  * Up- and down- scaling
  * Stereo modes:
    
    * Anaglyph
    * Page flip
    * Side-by-side
    * Interlaced

* Create factory method(s) to construct the pipeline based on settings and hardware support.

**Comment by x2048** [comment]
Thinking about it, here is alternative approach:

Alternative B
-----------------

Introduce three new abstractions: 

* RenderInput represents a set of inputs for rendering, in the basic case, a set of `video::ITexture` objects
* RenderOutput provides render target for the rendering step
* RenderStep represents a single rendering operation and can bind to Input and Output

Introduce the following implementations of inputs and outputs:
* RenderBuffer represents a preconfigured `video::IRenderTarget` with a set of `video::ITexture` objects and can serve as both input and output
* Screen represents the screen frame buffer
* RenderInputBinding allows remapping textures from multiple inputs into a single input

Example pipeline arrangements:
**NB!** Arrows represent data flows, not references. Blue Arrow = input, Green arrow = output.

| Arrangement | List of steps |
| ----------------- | --------------- |
| Fixed Pipeline | ![image](https://user-images.githubusercontent.com/4933697/172486098-84e54059-874b-42c8-8ac6-4c3b21751d38.png) |
| PostProcessing + Shadow mapping | ![image](https://user-images.githubusercontent.com/4933697/172485797-e14216c0-d86d-43dc-b097-f603a9e8ff8d.png) |
| Anaglyph + PostProcessing | ![image](https://user-images.githubusercontent.com/4933697/172487595-d294a8f0-4ec7-4942-8185-415826a6b473.png) |
| Side-by-side + PostProcessing + Shadow Mapping | ![image](https://user-images.githubusercontent.com/4933697/172488477-91210d51-0b2e-4df9-adc2-363fdecca504.png) | 

Comparison to Alternative A
------------------------------------

Pros: 
* Less coupling between steps, giving more flexible framework
* Better options for reusing texture buffers
Cons:
* Pipeline configuration is more complicated
* Part of the logic is moved into pipeline configuration (e.g. left/right eye for stereo), making it harder to maintain.

@lhofhansl @sfan5 @SmallJoker @rubenwardy @hecktest

**Comment by sfan5** [comment]
The recursive design sounds like it'd be harder to reason about in the end but ultimately both are fine with me.

**Comment by rubenwardy** [comment]
Implementing in #12465
