### ISSUE TITLE
Ultra-Minor Lua_API.txt correction

### ISSUE THREAD

**Issue by ExeVirus** [minetest/minetest#12420]
https://github.com/minetest/minetest/blob/213d3562bd29805e0bc8549a4e9e3aa2bf0f0349/doc/lua_api.txt#L4554

The line should read instead: (note the added closing backtick)
```
* `on_deactivate(self)`
```

**Comment by Wuzzy2** [comment]
Ideally syntax-testing the `lua_api.txt` should be automated somehow.
