### ISSUE TITLE
Improve Android virtual joystick movement

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#12436]
## Problem
I'm always frustrated when moving around in the Android version of Minetest. You are given a D-Pad disguised as a shoddy joystick which makes it feel extremely stiff and unresponsive since it can only go at full speed in 9 different directions.

## Solutions
Rework the touchscreen joystick to give the user 360 degrees of freedom and the ability to control the fraction of the movement speed by how far out the joystick handle has been pulled. Essentially, bring it up to par with Minetest's regular joystick support on desktop.

## Alternatives
Don't, I guess.

**Comment by IrrlichtMt4** [comment]
I think it would be nice to have a setting like the old joystick (with the arrows). Or add a setting that combines the arrow mechanics with the newer joystick. Some players may not be comfortable with the new joystick.

**Comment by Pantyhose-X** [comment]
![image](https://user-images.githubusercontent.com/42504385/175897551-1bef5af0-fe70-4264-925f-e8ed6866eede.png) 

* [minetest Adds button press, hold and release events](https://github.com/mt-mods/controls)
