### ISSUE TITLE
Command help message is shown to player when the handler returns false, even after text output

### ISSUE THREAD

**Issue by doxygen-spammer** [minetest/minetest#12435]
##### Minetest version
```
Minetest 5.6.0-dev-7ffc0268d (Linux) (today’s git master)
Using Irrlicht 1.9.0mt6
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

##### OS / Hardware
Operating system: KDE Neon user edition
CPU: Intel Core i5 4300U

##### Summary
https://github.com/minetest/minetest/blob/7ffc0268dfd78647187554d6248015329e9f5d2d/doc/lua_api.txt#L8722-L8725 says that the help message of a chat command is displayed when the callback handler returns false without producing text output.

I noticed that the help message is printed even after the callback handler has done text output.

When the user has entered a bad command, it may be helpful to print a specific error message.
But returning `true` in response is not natural, so the documented behavior would make sense to me.

##### Steps to reproduce
```.lua

minetest.register_chatcommand("not_help", {
        params = "bla";
        description = "This should not be printed.";
        func = function(playername, bla)
            minetest.chat_send_player(playername, "You did it “wrong”, and this is a more specific error message.");
            return false;
        end;});
```

**Comment by sfan5** [comment]
The documentation says this happens if the handler "didn't _return_ text output", not if it "didn't _produce_ text output".
Not to mention that the code that handles this has no way to detect whether `chat_send_player` was ever called.

**Comment by doxygen-spammer** [comment]
I disagree.

It says neither “return” nor “produce”, it just says “without”.

It mentions “returns boolean success and text output”.
Does that mean it can return a boolean and a string, and the string is 
interpreted as a translatable string which is sent as chat message back to the 
player?
That is really not clear.
