### ISSUE TITLE
What settings do I need for building minetest using visual studios

### ISSUE THREAD

**Issue by IrrlichtMt4** [minetest/minetest#12454]
What workloads do I need to compile Minetest for windows 64 in Visual Studios

**Comment by rubenwardy** [comment]
Hi, have you read the instructions on compiling Minetest using Visual Studio? https://github.com/minetest/minetest#compiling-on-windows-using-msvc

**Comment by IrrlichtMt4** [comment]
Thank you, didn't notice that.
