### ISSUE TITLE
Scaling bug on android tablet

### ISSUE THREAD

**Issue by julius-d** [minetest/minetest#12457]
##### Minetest version

```
5.5.1
```

##### OS / Hardware

Operating system: Android 11
Galaxy Tab A 
SM-T510

##### Summary
When I open the app the shown menu is smaller then expected and not centered but shown in the lower left corner.
But the biggest problem is that the button and input fields can not be clicked/touched.

When touching arround randomly on the screen I found out that the buttons can be activated when clicking on the place where they should be placed.

**The game is completly unusable!**

![Screenshot_20220619-122655_Minetest](https://user-images.githubusercontent.com/30121440/174477086-7e1d0462-2678-484b-b4c9-8c9181d876b5.jpg)

##### Steps to reproduce
Just open the Mintest app on the Galaxy Tab A 

A while ago the bug did only happen when the tablet was hold in a certain way while opening the app. 
Stopping the app and restarting while holding the tablet in a different way helped.
But now this uggly work around stopped working and the game is always in this broken state

**Comment by IrrlichtMt4** [comment]
A similar issue was fixed in a dev version of Minetest 5.5.0. This issue may have come back after many commits.

**Comment by wwar-XeStro** [comment]
Never happened to me on my tablet (which is older) android 4.4.4 galaxy tab A

**Comment by Zughy** [comment]
@julius-d hello, is this issue still present in Minetest 5.7?
