### ISSUE TITLE
Settings tab can't deal with more than 4 flags

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12452]
##### Minetest version
5.6.0-dev, 5.5, whatever

##### Summary
![grafik](https://user-images.githubusercontent.com/1042418/174459755-9a78b5ef-6abf-40ca-96ee-ccb387c18cf7.png)

##### Steps to reproduce
Put into settingtypes.txt:
<pre>
example () flags aa,bb,cc,nodd,noee,noff aa,bb,cc,dd,ee,ff
</pre>

**Comment by Zughy** [comment]
Settings should be completely revisited, see #12140
