### ISSUE TITLE
(Reverse) Proxy support

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#12474]
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
Ex. I'm always frustrated when [...]

There's no way to specify the address (which may or may not be an IP family address - e.g. tor .onion) behind a proxy.

## Solutions

Easiest way would be to add a trusted proxy protocol, similar to how e.g. IRC has the [WEBIRC](https://ircv3.net/specs/extensions/webirc.html) command.

## Alternatives

Uhhh none?

## Additional context

N/A.

**Comment by farooqkz** [comment]
If anyone else wanted a proxy, you can use `socat` on the proxy machine to create a proxy for a server of your choice:

```
socat UDP-LISTEN:30005 UDP-CONNECT:luanti-server.com:30000
```

It'll create a proxy usable for a single player to connect to `luanti-server.com:30000`. It listens on port `30005` on the proxy machine.
