### ISSUE TITLE
WebAuthn key support

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#12477]
## Problem

A clear and concise description of what the problem is.
ie: Why is this needed?
Ex. I'm always frustrated when [...]

Passwords are awful.

## Solutions

Player should be able to login with a webauthn key (aka U2F/FIDO2 device - webauthn is for the web parts, FIDO2 is the low-level protocol).

## Alternatives

N/A

## Additional context

https://marc.info/?l=openssh-unix-dev&m=157259802529972&w=2

https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.u2f

only transphobes would do this one without tackling name changes first.

**Comment by rubenwardy** [comment]
Minetest isn't banking or system admin software, there's no need for this complexity. I also suspect that very very few people would actually use this

If I was to add new auth methods, I'd add more general ones that servers could use to integrate with their systems. For example, OAuth2 or OpenID, or something like LDAP. And maybe lighter weight ones like access tokens

**Comment by SoniEx2** [comment]
The problem with WebAuthn is that it's expensive, at $20 minimum (for 1 key, and you should always have at least 2 - one main key, and one backup). But that's also a problem of usage, as, of the things we regularly use, only Twitter and GitHub support it. The thing is, more usage = more demand for the things = more scale = lower cost. Minetest likely wouldn't drive usage up enough, tho this would also have the side benefit of requiring a new auth backend with multiple credentials - at which point LDAP, etc would be trivial to suppport.
