### ISSUE TITLE
get media file path

### ISSUE THREAD

**Issue by FatalError42O** [minetest/minetest#12470]
## Problem

There's no way to get the path of a model, image, sound, or any other type of media file. 
This is particularly frustrating when you need to read a file that cannot have its path specified (for example trying to find the path of a mesh that cant have its path provided, like one of an object)

## Solutions
There should be stored locations of pre-found media, and to not prevent the locating of media that did not previously exist- there needs to be a function that returns all the results of any given search. This should not be particularly difficult seeing as minetest already does this in nearly all of it's register functions. 

It should vaguely look like this:

> Alternatively, there should be methods of getting media on a per-object basis, as well as node... this of course would not account for client media, but that's not the point.
> 
> something like `object:get_mesh_filepath()` or `object:get_texture_filepath()` alternatively this could be stored in properties, but this really shouldn't be changed unless the object's texture/mesh is. For nodes and itemstacks, there should be a similar `minetest.get_texture_filepath("modname:item")` which accepts the name, this also could apply for objects that way you can get their default textures if you wanted- as well as `minetest.get_mesh_filepath()` which would do the same thing but for you know, meshes.

## Additional context

(it of course shouldn't be restricted to just certain filetypes)

**Comment by sfan5** [comment]
Note that trying to read media files from mod folders is flawed since the client (or server!) may have a texture pack that changes these textures to be wildly different.
Models are an exception to this since texture packs can't modify them.

**Comment by FatalError42O** [comment]
I didnt nessecarily only mean images first, secondly- this is why itd be a list of all of them, if a modder needs, they can select what they need.

**Comment by sfan5** [comment]
I don't think you understood the issue, it is **impossible** to know how a given texture looks on the client.
Also what does "all of them" mean? The server has exactly one file for each name, and if there were multiple how would the modder know which he wants?

Maybe it'd help if you explained your usecase.

**Comment by FatalError42O** [comment]
I'm not saying you need to know what image the user is using, because yes- this is impossible because of texture packs etc- when I wrote that I had a poorer understanding of how media works, I thought minetest selected media differently, but it seems I was wrong about this.

Alternatively, there should be methods of getting media on a per-object basis, as well as node... this of course would not account for client media, but that's not the point. 

something like `object:get_mesh_filepath` or `object:get_texture_filepath` alternatively this could be stored in properties, but this really shouldn't be changed unless the object's texture/mesh is.
For nodes and itemstacks, there should be a similar `minetest.get_texture_filepath("modname:item")` which accepts the name, this also could apply for objects that way you can get their default textures if you wanted- 
as well as `minetest.get_mesh_filepath()` which would do the same thing but for you know, meshes.

**Comment by FatalError42O** [comment]
also why was this tagged with possible close, just because it may not return accurate results for the textures the player may see, doesnt at all mean that it's not an issue- and not an API addition that needs to be made

**Comment by FatalError42O** [comment]
Its mainly more important for meshes anyway.

**Comment by NathanSalapat** [comment]
You still didn't give a usecase for this. I personally don't know why you'd ever need the file path of a piece of media, you never need to define a file path when using media, just the name of the media file.
If you want to see if a specific piece of media is available just see if the mod that contains that file is loaded. If you need the media file depend on the mod that provides it.

**Comment by FatalError42O** [comment]
> You still didn't give a usecase for this. I personally don't know why you'd ever need the file path of a piece of media, you never need to define a file path when using media, just the name of the media file. If you want to see if a specific piece of media is available just see if the mod that contains that file is loaded. If you need the media file depend on the mod that provides it.

Well, I can give my use case, but that won't cover all of the potential ones. There's a lot of things that can be done with this, and I think it's a bit stupid to not allow modders to explore and use all of the possibilities.

Personally, I'd use it to help get around engine inadequacies for getting the location of object attachments by reading the b3d files and doing math to find out the location of all relevant connected bones, in the end solving for the location of an object. 

I could see people using this for a number of different things though, overall it's necessary to read and access any model that is not tracked by your mod- that's a pretty basic building block if you ask me.

**Comment by FatalError42O** [comment]
and also if you want to read and modify a texture (in such a way that the limited texture modifiers don't provide), you need to access that said file to change it (sending it using dynamic media of course).
Also a use case for me, getting the player model and then modifying it- which is essential for the mod I'm currently working on.

**Comment by FatalError42O** [comment]
These are just things I _PERSONALLY_ would use it for, it's sort of annoying that it isn't built in... I mean, if you want to go down the "why would you need that" route, there's plenty of things that aren't needed- this however is something I think should be a basic tool, and one that is not particularly difficult to implement either way

**Comment by sfan5** [comment]
Reading meshes is an acceptable usecase.
Something like this should almost always(\*) work:
```lua
local get_model_path(filename)
    for _, m in ipairs(minetest.get_modnames()) do
        local p = minetest.get_modpath(m) .. "/models/" .. filename
        local f = io.open(p, "r")
        if f then
            io.close(f)
            return p
        end
    end
end
```

(\*) Dependent mods can override media files, this is not handled.

**Comment by sfan5** [comment]
Technically the server will also load models from the `textures` folder and the other ones.
But it won't load anything from `temp_models`, so what you're saying is that you use dynamic media for this?
