### ISSUE TITLE
Doesn't start when 3d_mode = pageflip

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12489]
##### Minetest version
Latest dev

##### OS / Hardware

Operating system: Manjaro
CPU: i7 something

GPU model:
OpenGL version:

##### Summary

> WARNING[Main]: Irrlicht: No doublebuffering available.

##### Steps to reproduce

minetest.conf

```
3d_mode = pageflip
```

**Comment by sfan5** [comment]
support for this was dropped, should probably be deleted 4f9c33de640a748d020e63c7c85ccbbe341ab7a7

**Comment by rollerozxa** [comment]
This was never removed, apparently.
