### ISSUE TITLE
Scrolling on dropdown inside scroll container shouldn't change its state

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12481]
##### Summary
Scrolling on dropdown inside scroll container shouldn't change its state

Optionally it should only change its state if scroll starts on dropdown

##### Steps to reproduce
Scroll on dropdown inside scroll container

**Comment by Montandalar** [comment]
I would say it should scroll when focused, such that if you click on it you can then scroll through it.

**Comment by grorp** [comment]
minetest/irrlicht#192 has long been merged. @rubenwardy can this be closed?

**Comment by rubenwardy** [comment]
Yeah this is fixed
