### ISSUE TITLE
Password entry field clears when server list updates

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#12491]
##### Minetest version

```
Minetest 5.5.1
```

##### OS / Hardware

Operating system: Devuan Linux
CPU: AMD

GPU model: 
OpenGL version: 

##### Summary

A pet peeve of mine in the interface is that if you start typing a password in and the server list updates, it will quietly erase anything you've typed so far, which leads to me attempting to log in with only the second half of my password.

##### Steps to reproduce

Open up MT on the join a server tab, quickly click the password field, and type a few letters, then wait for the server list to update. The asterisks disappear.

**Comment by Zughy** [comment]
Uhm, I've waited for about 10 minutes and I don't think my serverlist is updating.. however, if I press the refresh button the password disappears

**Comment by jeremyshannon** [comment]
It updates once about 1-2 seconds after MT opens, which  is long enough for me to have half my password typed in. After that you have to hit refresh to see the bug.
 I imagine most people don't notice because they don't start typing their password as quickly as me.

**Comment by wsor4035** [comment]
this is a known issue with formspecs, send a new/updated one, and it will reset all input fields

**Comment by jeremyshannon** [comment]
Is that why menu music restarts when you enter the "new world" tab, and then restarts again when you exit back out?

**Comment by rubenwardy** [comment]
> Is that why menu music restarts when you enter the "new world" tab, and then restarts again when you exit back out?

no, this is because the game theme only applies to the join world tab

**Comment by jeremyshannon** [comment]
?? Then shouldn't it stop when you enter the "New world" page? 'Cause it starts over instead. And I think you mean "start game" tab, the themes aren't applied on the server list tab.

**Comment by Niklp09** [comment]
#12383
