### ISSUE TITLE
Add the ability to sprint

### ISSUE THREAD

**Issue by domsson** [minetest/minetest#12498]
## Problem

As a player coming from Minecraft (or any other game, for that matter), one expects the ability to sprint. This is not present in Minetest unless added via a mod. Even Minetest Game does not add this ability.

## Solutions

Sprinting should be added natively to Minetest (engine) so that no mod is needed for this basic and expected functionality.

## Additional context

I am aware of [issue 10691](https://github.com/minetest/minetest/issues/10691) which was closed because there is already the `fast` privilege. However, I just tried it and that's nothing like sprinting - that's just going lightspeed. To get normal, expected sprinting, one still needs a mod. For the sake of user experience (in particular, new users), sprinting should be a basic feature that ships with the engine. It is just as essential as jumping or swimming.

Another reason to have this be a native feature is that this would allow to properly fix stair movement somewhere down the road. Seeing how the `fast` feature is already in the engine, it seems that having native sprinting wouldn't be hard to implement: give it a reasonable speed and make it available to every player without the need for a privilege.

**Comment by vvv112** [comment]
leave fast, it might be useful.
and create a sprint privilege
that will work when cntrl is clamped

**Comment by domsson** [comment]
> leave fast, it might be useful. 

Yes, no reason to remove `fast`. Sprinting and `fast` can co-exist. 

> and create a sprint privilege that will work when cntrl is clamped

Sprinting is basic movement ability in almost every game. Minetest already has jumping and it doesn't require a privilege, so sprinting shouldn't either.

**Comment by vvv112** [comment]
I was referring to the privilege available to all players.
maybe on some servers there will be mini-games according to the rules of which sprint cannot be used.

**Comment by Zughy** [comment]
Agree with OP here: if ever, modders should have the possibility to disable sprinting through `set_player_properties` (as @vvv112 is suggesting). Because in the end, 99% of the games are probably about being a creature able to jump, climb, run and swim

**Comment by rubenwardy** [comment]
Minetest is trying to leave as many game play features to game and mods to implement, as this increases flexibility. Adding a sprint feature raises questions like should it take energy, should it be time limited, etc

It's already possible to implement using mods. I personally use https://content.minetest.net/packages/sofar/stamina/

**Comment by domsson** [comment]
I'd like to say that I find this decision very unfortunate. As someone who is currently trying to get into and find its way around Minetest, me and my friends have now come across multiple aspects that make the initial user experience less than ideal. Lack of sprinting is very high up one the list.

While I agree that leaving most things up to mods is a great philosophy, I don't see why one aspect of basic movement (sprinting / fast walking) would not fit the bill, while others (walking, sneaking, jumping, swimming) do. 

Having to find and download a mod for this basic functionality is not optimal. 

Sure, there will be questions and implications, as every change to a code base, but that alone shouldn't be a reason to dismiss a suggestion. Answers to questions can be found and so can elegant implementations. For example, to keep things simple, why not leave stamina up to mods, but at least provide a fast walking (sprinting) mode? If possible and necessary, the mod API could be amended to where a mod could query for things like "is the player currently sprinting?" or "how long has the player been sprinting for?".

**Comment by rollerozxa** [comment]
"lack of sprinting" varies between game. nodecore has built in sprinting where your movement speed steadily increases, and the mineclones have minecraft-like sprint by default as well.

**Comment by domsson** [comment]
> "lack of sprinting" varies between game.

Good point, although I'm taking about lack of sprinting as core functionality. Again, I don't really see why these right here are in the engine:

 - Walking
 - Jumping
 - Walking at superspeed (`fast`)
 - Swimming
 - Flying

But this one is considered out of scope and needs to be handled by mods:

 - Running / Sprinting

That, plus it just feels odd for first-time users who try Minetest via the default Minetest Game. Now, to be fair, this could be fixed by including a sprint mod in Minetest Game; but my argument/ question about consistency still stands even then.

**Comment by domsson** [comment]
I gave this a go and while I had to touch more files than I thought (and probably still missed something), I did get native sprinting to work relatively quickly by introducing `movement_speed_sprint`. Doesn't add much code. Mods should be able to slap stamina functionality on top, no problem, so no need to add that in the engine. Existing mods might not even break (too badly)?

**Comment by vvv112** [comment]
> Согласитесь с OP здесь: если когда-либо моддеры должны иметь возможность отключить спринт `set_player_properties`(как@vvv112предлагает), но он должен быть активен по умолчанию. Потому что, в конце концов, 99% игр, вероятно, о том, чтобы быть существом, способным прыгать, карабкаться, бегать и плавать

I meant that this is a basic feature available to all players, which has the ability to be disabled on servers
