### ISSUE TITLE
Add a simple shader

### ISSUE THREAD

**Issue by vvv112** [minetest/minetest#12499]
please add a simple shader that will render shadows,
waves on the water (more beautiful than the built-in function) and so on... 

(please tell me if I wrote some bullshit)

**Comment by rollerozxa** [comment]
dynamic shadows has already existed for quite some time, they just haven't made their way into a stable release yet. and waving liquids already exists, see the settings page in the main menu

**Comment by vvv112** [comment]
I meant something like this https://minecraft-inside.ru/tag/%D0%A8%D0%B5%D0%B9%D0%B4%D0%B5%D1%80%D1%8B%20%D0%B4%D0%BB%D1%8F%20Minecraft/1.16.5/
I know about the built-in grass and water swings
