### ISSUE TITLE
Nodeboxes are not affected by smooth lighting and too dark

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#125]
Nodeboxes, most notably stairs and slabs are not affected by smooth lighting, they are also too dark unless using `sunlight_propagates = true` which lets light pass though.

**2014-08-15**: the bug is still here.

**Comment by nerzhul** [comment]
hi @Calinou already existing issue ?

**Comment by paramat** [comment]
Fixed by RBA converting nodeboxes to meshnodes.
