### ISSUE TITLE
Unimplemented preserve group functionality in crafting

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest#1250]
This modding API feature has stayed unimplemented for a long time:
```
### Groups in crafting recipes
An example: Make meat soup from any meat, any water and any bowl:

    {
        output = 'food:meat_soup_raw',
        recipe = {
            {'group:meat'},
            {'group:water'},
            {'group:bowl'},
        },
        -- preserve = {'group:bowl'}, -- Not implemented yet (TODO)
    }
```

Implementing it is important for making usage of groups possible in that type of recipes. Most recently wanted on 2014-04-18: https://forum.minetest.net/viewtopic.php?p=138327#p138327

This poses a risk towards mod interoperability.

**Comment by paramat** [comment]
Is this still relevant or has it been done?
The link is now incorrect, it refers to:
```
### Groups in crafting recipes
An example: Make meat soup from any meat, any water and any bowl:

    {
        output = 'food:meat_soup_raw',
        recipe = {
            {'group:meat'},
            {'group:water'},
            {'group:bowl'},
        },
        -- preserve = {'group:bowl'}, -- Not implemented yet (TODO)
    }
```

**Comment by rubenwardy** [comment]
What does this do?

**Comment by v-rob** [comment]
https://github.com/minetest/minetest/blob/8c19823aa7206e6c73a4ad00620365552c82d241/doc/lua_api.txt#L1681-L1689

The thing in reference.  I think it means that the bowl will not be consumed in the craft, so you get the meat soup while retaining the empty bowl as well.  It should either be implemented or removed from `lua_api.txt`.
