### ISSUE TITLE
Reminder to provide a macOS build this release

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12506]
TL;DR we can take the ZIP file created by github actions and release that
see #12422 for all details

**Comment by oong819** [comment]
a while ago i see a player said he playing on macbook or imac i dont remember, but how he can play minetest on MacOS? sorry if its already be answered before

**Comment by sfan5** [comment]
The most sucessful way of installing Minetest has been via [brew.sh](https://brew.sh/) for a while.

**Comment by cweiske** [comment]
Related: #3596, #9166.
