### ISSUE TITLE
Allow formspecs to open URLs

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12500]
## Problem

Lots of servers come with websites, for example wikis and fancy management system. It would be nice if mods had some way of opening URLs in a browser.

## Solutions

Security needs to be a core consideration. It shouldn't be possible to open a URL without user interaction, and they should be able to preview the URL first in a font that distinguishes different characters (eg: l I - L and i)

* `button_url[]` component that shows a open URL dialog with the URL
* ~~`player:open_url()` method that only works if the player has recently submitted a formspec due to user interaction~~

## Additional context

The code for opening a URL is already implemented as `porting::open_url`, there just needs to be modding API and GUI support

**Comment by sfan5** [comment]
> `player:open_url()` method that only works if the player has recently submitted a formspec due to user interaction

The potential for misuse here is clear if you've ever used the web before pop-up blockers became a thing.
I'd prefer if only `button_url[]` was implemented.

**Comment by rubenwardy** [comment]
That's also my preference

**Comment by kilbith** [comment]
How do you intend to link that to `hypertext`?

**Comment by sfan5** [comment]
I suppose it could get an `<url>` tag that works identically (not sure how hypertext works, so that may be inaccurate).

**Comment by rubenwardy** [comment]
It's much easier to implement a couple of elements to formspecs and hypertext than it is to implement a system of remembering when the last user interfaction/submission was
