### ISSUE TITLE
Change main menu icons style

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12508]
## Problem

The icons used in the main menu, especially in the server list, follow a style that is not very consistent. I think Minetest attempts to go towards some kind of "pixel"/"retro" style but the current icons are not in that style at all. First attempts to go pixel style can be seen at the loading bar.

## Solutions

Replace the icons used in the main menu (mostly server list) with "pixel style" ones, in order for a more consistent style.

## Additional context

This issue is part of the broader main menu rework attempts.

**Comment by Zughy** [comment]
Considering #6733 going on, I don't see why this should be a separate issue. Also, considering the current menu, if you put pixel icons, they're gonna just look ugly. I know because I've tried more than once. The whole main menu needs to be changed for them to fit. Closing

**Comment by Tim79000** [comment]
Just replace everything with Frutiger Aero, I could make a texture pack for this.
