### ISSUE TITLE
Cloud layer transitions are abrupt and too late

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#12501]
## Problem
Cloud transitions are a hard binary, it's either solid clouds or else fog.
 IRL clouds melt away into fog on approach, but in MT it's an opaque white sheet until the very last moment when you pop your head inside. 

Anyone who's gone mountain climbing near the cloud layer can tell you, the cloud layer as it stands is a funky obstacle. There's no way to see if the node beneath the clouds you're stepping on is a gentle slope, or a pit that will plummet you to your doom. Even turning on wireframe doesn't help, as the geometry on the other side is simply not drawn!
 It's a more common problem for players in Exile, as we use ground level clouds to create an otherwise lovely fog bank

## Solutions

I found that simply extending the radius of the m_camera_inside_cloud check in clouds.cpp:356 by about 5 nodes solves the gameplay issue at least, allowing you to see through the cloud when you start to get close, but while it feels a bit more realistic than the current situation, it's still a little weird and abrupt. 

## Alternatives

 An ideal solution would be to gradually raise the transparency of the nearest cloud face and the density of the fog as you get close to it, but this would be a much more invasive change. Between my rusty C skills and the fact that modern 3d is a foreign country to me, I'm not sure if I can manage to code that up without breaking things. (My last dive into 3d was coding up a raycaster in Turbo C for DOS. It sorta worked!) It would take some time for me to get up to speed in order to make this alternate proposal work.

## Additional context

![waist deep in cloud](https://user-images.githubusercontent.com/23157047/177017507-51499752-f074-4aaa-974b-8934c9feb949.jpg)
Standing waist deep in a fog bank on the edge of a steep hill. Is that next step safe, or certain death?

**Comment by sfan5** [comment]
I can't say I really get this issue.
Is the inside-cloud fog not almost as bad for visibility as a solid surface (as in, you barely see anything anyway)? Isn't it meant to be that way?

**Comment by Desour** [comment]
>Immediately beyond the cloud's edge, though, it's an opaque white sheet

Can not reproduce. On my machine, the cloud border is semi-transparent from outside and backface-culled from inside the cloud.
Do you maybe use some mod that changes this? If so, this looks like a mod issue to me.

**Comment by jeremyshannon** [comment]
Checking this again in devtest. It seems to involve having the clouds' color set to #FFFFFF, it breaks the transparency and somehow causes the engine to cull all geometry past the cloud boundary.
 Wait I see it now, Dokimi left out the alpha channel from the color! It should be #FFFFFF??, FE seems good. Closing this as solved. Thanks!
