### ISSUE TITLE
Add 'string.starts_with' and 'string.ends_with' to lua environment.

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#12511]
## Problem

You can check if a string contains a substring with 'gsub', but you cannot check if it starts, or ends with a specific string or not.

## Solutions

Add this code to the lua environment:

```
function string.starts_with(self, substring)
    return (self:sub(1,#substring) == substring)
end

function string.ends_with(self, substring)
    return (self:substring(0-#substring) == substring)
end
```

**Comment by SwissalpS** [comment]
doesn't ``string.match(s, '^starting with')`` work?
also ``string.match(s, 'ends with$')``

**Comment by wsor4035** [comment]
...please read up on lua patterns: https://www.lua.org/pil/20.2.html

**Comment by rubenwardy** [comment]
Patterns are the wrong way to do this, you should use string.sub instead

I'm in favour of extending our Lua with helpful utils like this

**Comment by wsor4035** [comment]
> Patterns are the wrong way to do this, you should use string.sub instead

patterns are a correct way of doing this, as they have special characters for this exact use case `^` and `$` as pointed out by SwissalpS.

in addition, this is a one loc (aka not boilerplate function that will be repeated all over mods) that can simply be done by anyone, and does not need an api method for it unlike per say something useful like string.split that the minetest api provides

**Comment by SwissalpS** [comment]
I don't see any harm in adding it even though it can be done by other means. It is something that is used fairly often in many languages. Not that I have needed it much in mods. I've needed more complex matches than just starts_with or ends_with.

**Comment by sfan5** [comment]
> In 99% of cases, `string.split` is actually useless and inferior when compared to `gmatch`.

Last time I checked gmatch did not return a table, allow skipping empty values or limiting their amount.
If your answer to this is "you can easily do it yourself in 5 LOC" then you're entirely ignoring the convenience aspect.

To the point: Although I would often have found these useful I think we can spare adding 1 LOC wrappers for these in Minetest.
Also I think many usecases for this have a constant substring you're looking for. In that case there's no issue with using `string.match`.

**Comment by appgurueu** [comment]
> Last time I checked gmatch did not return a table, allow skipping empty values or limiting their amount. If your answer to this is "you can easily do it yourself in 5 LOC" then you're entirely ignoring the convenience aspect.

I would argue that not building a table is an advantage, as often the table is only used to iterate anyways. In fact there should rather be another util that turns an iterator into a table.

Anyways, here's splitting by spaces, ignoring empty values:

```lua
for space_delimited_substr in str:gmatch"%S+" do ... end
```

to build a table you'd either have to use the aforementioned util as `table.to_list(str:gmatch"%S+")` or use `local t = {}` & `table.insert(t, space_delimited_substr)` yourself.

**Comment by rubenwardy** [comment]
I'd say that finding whether a string starts or ends with a substring is a common enough problem that it deserves a standard lib function. Patterns are slow, and painful if you need variable substrings. Having a method is also expressive and makes the code easier to read

It would also take about 5 minutes to make and review.

I'm generally in favour of expanding the standard library to match the sort of things you see in other languages. Lua's standard library is small but doesn't need to be.

But whatever, if other devs don't want to extend the standard library with sugary functions then I'm not going to push it

**Comment by appgurueu** [comment]
> I'm generally in favour of expanding the standard library to match the sort of things you see in other languages. Lua's standard library is small but doesn't need to be.

I'd say make this deserves [a more general issue](https://github.com/minetest/minetest/issues/12513), of which `starts_with` and `ends_with` is a specific instance. The standard library should be extended in bulk, not through salami-sliced small additions with little impact such as this one.

**Comment by SArpnt** [comment]
expanding the standard library just seems like easy feature creep and a way to confuse people that actually know lua as it is normally. you're not really adding one quick feature, you're making an entire superset of lua that would likely be poorly documented, or if it is documented an unnecessary timesink

if developers don't like lua, then just support languages other than lua with more bindings (for example wasm bindings to support most compiled languages), it would likely end up taking the same amount of effort in the long run and allow far more for it.
