### ISSUE TITLE
Lua standard library extension discussion

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12513]
## Problem

Lua's standard library is very minimalistic. Eventually the engine should provide utility functions that are currently either (1) duplicated across mods (2) stuffed in bloated library mods or (3) even worse, not abstracted away at all, but rather copy-pasted to the appropriate place.

## Solutions

Extend the standard library. [Very few extensions](https://github.com/minetest/minetest_docs/blob/master/doc/environment.adoc#standard-library-extensions) are currently provided by Minetest.

## Alternatives

Keep it as-is, telling mod authors to bring their own standard library extensions.

## Proposed extensions

* [`string.starts_with` and `string.ends_with`](https://github.com/minetest/minetest/issues/12511)
* whatever you propose

**Comment by Zughy** [comment]
I think it's best to open a specific issue about a specific need, rather than theorise on a general "Discussion" issue that will be likely be forgotten in a matter of days. Also because this one can go on for a long time

**Comment by Zughy** [comment]
well, one like from a core dev, closing

**Comment by appgurueu** [comment]
> I think it's best to open a specific issue about a specific need, rather than theorise on a general "Discussion" issue that will be likely be forgotten in a matter of days. Also because this one can go on for a long time, and it's not like core devs have the time to think about yet another (complex) thing

I disagree. I think the discussion about standard library extensions should be centralized in one issue to make one big PR that satisfyingly extends the standard library rather than being spread out in numerous smaller issues.
