### ISSUE TITLE
can't open in mac built for stable-5

### ISSUE THREAD

**Issue by movelikeriver** [minetest/minetest#12526]
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:
```
$ sw_vers
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62

sysctl -n machdep.cpu.brand_string
Apple M1

```

GPU model:
OpenGL version:

not supported
https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/OpenGL-MacProgGuide/opengl_intro/opengl_intro.html

##### Steps to reproduce

follow the readme here (stable-5 branch)
https://github.com/minetest/minetest/blob/stable-5/README.md

the compile/build was successful
but 
`open build/macos/minetest.app`

got "Minetest quit unexpectedly."

**Comment by sfan5** [comment]
Please try the brew.sh build, it has some patches that may be necessary for the stable build to function.
