### ISSUE TITLE
Somebody is making money off of this open source project!

### ISSUE THREAD

**Issue by nonperforming** [minetest/minetest#12529]
![image](https://user-images.githubusercontent.com/43197300/178204404-0ced14d1-b959-489b-bd2a-d0c1d199e9e4.png)

https://www.microsoft.com/store/productId/9NZ5P9FHDG1M

(this is not a bug, but I don't know where else to put this)

**Comment by rollerozxa** [comment]
There is nothing we can do about it unless the recent Microsoft Store policy changes lead to it being taken down. Selling free software is completely allowed, which leads to this kind of stuff unfortunately happening.

**Comment by rubenwardy** [comment]
We've reported this multiple times and there's nothing we can do. There's no problem witb making money off of minerest, the problem is that they're using our name and confusing users

Microsoft are changing the rules of the store and so it should be removed soon
