### ISSUE TITLE
No formspec "pixel perfection"

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12524]
##### Minetest version
```
5.6-dev
```

##### Summary
Formspec elements with the same coordinates & dimensions don't exactly overlap; ugly 1px borders are left. This makes pixel perfection an unreachable goal.

##### Steps to reproduce

```
/lua minetest.show_formspec("singleplayer","yay","formspec_version[2]size[1,1]background[0,0;1,1;yay.png]button[0,0;1,1;yay;Yay]")
```

where `/lua` is any Lua-executing chatcommand such as WE's `//lua` or dbg's `/lua`.

Expected: The button overlaps the background entirely - no border is visible.

Actual: A 1px border is visible at the bottom & right edges of the button.

![Bildschirmfoto von 2022-07-09 20-07-55](https://user-images.githubusercontent.com/34514239/178117974-a2fd4a4d-6ffe-4f15-a0e1-26df735ab9dd.png)

Bonus: Resize the window and observe that the - exactly 1px - border persists.

Even more bonus bonus: Make the window small enough for Minetest to die as it fills up your memory and slows your computer to a crawl, spitting out "Invalid size of image for texture" a few times.

![Bildschirmfoto von 2022-07-09 20-14-20](https://user-images.githubusercontent.com/34514239/178118074-613e9246-af39-4579-bbdf-64335e2d0f77.png)

**Comment by wsor4035** [comment]
i can confirm the pixel missalign, however usually this is hidden by turning off the buttons background, etc, where the 1px doesnt make much difference for clicking on it

**Comment by Skamiz** [comment]
Note that the issue described here is specific to the default button style. When using a custom button texture it covers the whole specified area.
My understanding is that the default button basically also covers the area, but the texture includes a strip of transparent pixels. When the button is pressed, the pressed texture fills up that area, helping the illusion that the button is pressed in. In the same way the buttons text is moved down and right a bit.

**Comment by v-rob** [comment]
This isn't a bug; just due to the ugly default styling of formspecs.  The 1px border is part of the button, and is very dimly opaque.  Make your own style if you want it to look better.
