### ISSUE TITLE
Allow disabling the node/entity selection outline

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#12522]
It would be nice if it was possible to change a node/entity property to disable the selection outline when pointing at that node/entity.
The node/entity should still be interactable, or at least not allow selecting the thing behind it.

Left: selection outline enabled. -|- Right: Selection outline disabled.
![image](https://user-images.githubusercontent.com/28972859/178088815-1bbb6be9-9860-4b0f-9761-fee5a4d41794.png)

## Usecases

- Non-sandbox games where you want to indicate what the player can/can't interact with
- Invincible nodes you can't point at or build on, that don't let you select the node behind them?

**Comment by GreenXenith** [comment]
This may be for a separate PR, but it would also be neat to add a new tile table (or similar) for the selection box as well. It is already a mesh with a material, so implementing the textured part should not be terribly difficult.

**Comment by erlehmann** [comment]
I rely on the node halo for gameplay due to my bad contrast vision and I suspect it is a bad idea to let the server decide the appearance of the selection, unless it can be easily overridden on the client for accessability purposes.

@LoneWolfHT could you please clarify why you think that something that is interactable should look like it is not? How would you hint to the user that stuff is interactable? What are your thoughts on accessability?

**Comment by LoneWolfHT** [comment]
> I rely on the node halo for gameplay due to my bad contrast vision and I suspect it is a bad idea to let the server decide the appearance of the selection, unless it can be easily overridden on the client for accessability purposes.

Idiotic misuse of this feature is up to the server. I don't think you need to worry about it though

> @LoneWolfHT could you please clarify why you think that something that is interactable should look like it is not? How would you hint to the user that stuff is interactable? What are your thoughts on accessability?

Might want to reread my post.
99% of the nodes in my game are *not* interactable, so I don't want your halo to show up when your cursor is over them

**Comment by GreenXenith** [comment]
> What are your thoughts on accessability?

This was not directed at me, but I will give my thought anyway: Accessibility, like **everything else**, should be up to the game. The **game engine** should _not_ force any sort of accessibility style (or even requirements) on the game developer. Different kinds of accessibility are needed for different types of games anyway.

**Comment by LoneWolfHT** [comment]
Fixed by https://github.com/minetest/minetest/pull/13992 ? I haven't looked to see what I can do with the feature yet but it seems like it would work for my needs

**Comment by appgurueu** [comment]
Yes, `pointable = "blocking"` resolves this feature request essentially and can be used e.g. for CTF map barrier nodes.

> The node/entity should still be interactable

This part of this request is currently technically not possible, but I don't think you need this for your purposes (it seems to me this was just a convoluted way to describe `pointable = "blocking"` as "the node is pointable, but you can't see that you're pointing it, *and* I can define `on_punch` etc. such that nothing happens). For interactable nodes, you would want the outline (or halo or nothing depending on settings).
