### ISSUE TITLE
Improve lighting

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12523]
## Problem

The world in Minetest lighting system is a bit boring

## Solutions

i think its really cool if Minetest have multi color light that can be blended together and glow effect, also i suggest that the every nodes will be grouped in each group have diffrient light reflect and special lighting effect (like PBR)

## Alternatives

idk

## Additional context

made it togglable because and dont make it too realistic or too heavy for CPU

**Comment by rubenwardy** [comment]
Thanks for the suggestion! These requests are already tracked by a number of issues. The first one is colored lighting, the second is a bloom feature which is a future enhancement to post processing effects

Duplicate of #2670 #9075 #5446

**Comment by IrrlichtMt4** [comment]
Something similar is already added into Minetest with dynamic shadows.

**Comment by IrrlichtMt4** [comment]
Though, it would be nice to have a setting for different colored shadows. Or maybe a to mod with colored shadows.
