### ISSUE TITLE
`preserve_metadata` passes fields, not a `NodeMetaRef`, for `oldmeta`

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#12531]
##### Minetest version
```
5.6-dev
```

##### Summary

Found by @lukasdragon.

Implementation: https://github.com/minetest/minetest/blob/8724fe6e3fc2b6c0b78123f1f95fd8c6c6817dd5/builtin/game/item.lua#L490

Docs: https://github.com/minetest/minetest/blob/8724fe6e3fc2b6c0b78123f1f95fd8c6c6817dd5/doc/lua_api.txt#L8294

**Comment by rubenwardy** [comment]
https://content.minetest.net/zipgrep/fdb51fc0-c2a4-405a-a774-1ffac265a605/

**Comment by appgurueu** [comment]
> screenshot for when the link breaks

*when* or *if*? does it eventually "time out"?

**Comment by SmallJoker** [comment]
Documentation issue. Node meta should only exist as the pointing node does,otherwise it would have to be a generic metadata object.

**Comment by rubenwardy** [comment]
> when or if? does it eventually "time out"?

It uses Redis to cache the results, not the database, so the link goes to 404 when Redis deletes its data
