### ISSUE TITLE
Misplaced leaves with visual_scale > 1

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#12536]
##### Minetest version

```
b55d7cd45a304a8a5b8337a3c61defb6e5c27dd9
"Fix worldaligned textures"
```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

At the actual position of the leaf, there is an invisible block, visible leaf appears misplaced.
It happens with visual_scale different than the default value, like 1.1, 2...

![image](https://user-images.githubusercontent.com/52937829/178754449-033ae15f-2b57-4e13-a220-fc7865871c8a.png)
a well known minetest game (5.5.1) tree
![image](https://user-images.githubusercontent.com/52937829/178754782-2947fb20-3bb3-407a-8747-293e01e12a7a.png)
this time with visual_scale = 1.1 for default:leaves
![image](https://user-images.githubusercontent.com/52937829/178755117-0fc399b9-8588-4aff-867c-5adce8ddd21a.png)
visual_scale = 2

(additional content: https://notabug.org/BlueBird51/musttest_game/commit/2116b78577eabeb45c036e0bc0d29d9bb0c47540)

**Comment by sfan5** [comment]
I can takes guesses but can you include a textual description of the issue?

**Comment by waxtatect** [comment]
Sorry, i thought the screenshots were enough to describe the trouble, description added

**Comment by sfan5** [comment]
Confirmed that this worked in 5.4.1

**Comment by BluebirdGreycoat** [comment]
I don't recall ever noticing that using "visual_scale" this way worked. However I usually always play with "simple leaves", and even after upgrading client and server to 5.6, I didn't notice it until one of my players told me they had to turn "fancy leaves" off. So it seems that this is affected by the client's fancy/simple/opaque leaves setting.

And now I'm wondering why all that code in the referenced commit from "musttest_game" was using "visual_scale" for leaves in the first place ... since it never made any difference for me. That's why I just went and deleted all of it.

**Comment by SmallJoker** [comment]
This seems to be  related to depth sorting. @x2048 Would you please be so nice to have a look at this?

**Comment by x2048** [comment]
b55d7cd45a304a8a5b8337a3c61defb6e5c27dd9 is the problem. Adding origin to the bounding box before applying the scale will cause the scaled nodes to 'fly away'.

I tested with b55d7cd45a304a8a5b8337a3c61defb6e5c27dd9 reverted, and I cannot reproduce #12197. I suggest reverting the offending commit.

The logic in drawAutoLightedCuboid is as follows:
1. If texture coordinates are supplied by the caller, these are used unchanged.
1. If visual_scale is different from 1.0, then (a) get the (unscaled, non-offset) texture coordinates and (b) and apply the visual scale.
2. Add node origin to the bounding box
3. If the texture coordinates not set yet (that is, if visual_scale == 1.0f ± 1e-3) calculate the (off-set) texture coordinates - this enables world-aligned and node-aligned tiled textures

Here are both tiled nodeboxes (stairs) and scaled plantlike nodes on the same screen with b55d7cd45a304a8a5b8337a3c61defb6e5c27dd9 reverted:
![image](https://user-images.githubusercontent.com/4933697/179607901-bc4518c7-0bf4-47ff-815c-2b8c4ee62330.png)

@Oblomov  @NathanSalapat
