### ISSUE TITLE
Lua API Regression: "minetest.punch_node(pos)"

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#12537]
I noticed that the bonemeal code started crashing my server after I updated to 5.6 a day or so ago. Culprit: `minetest.punch_node(pos)`. Resultant error: builtin/common/vector.lua:49: attempt to index local 'v' (a nil value).

You should be able to confirm this error by installing any Luacommand mod and trying to call `minetest.punch_node(whatever)` in the command string. I used the player's own position (fractional bits rounded off, of course).

**Comment by Emojigit** [comment]
Providing the entire Lua code helps a lot. The problem may be in the scripts getting the position, instead of `punch_node`.

**Comment by BluebirdGreycoat** [comment]
Hmm. I think that if vector.round(user:get_pos()) was failing, I would be seeing many, many, many, many, many crashes. However, that particular API was only used once in the entire "musttest_game", and after getting rid of it, everything's fine.

But I'll see about trying to reproduce with a simple mod.

**Comment by BluebirdGreycoat** [comment]
Here you go:

```
minetest.register_chatcommand("crashmeplz", {
	func = function(name, param)
		local pref = minetest.get_player_by_name(name)
		if pref then
			local pos = pref:get_pos()
			if pos then
				minetest.punch_node(vector.round(pos))
				-- Ahahahahaahahahaahaah!!!!!~~~1!!111111`~~
			end
		end
	end,
})
```

**Comment by appgurueu** [comment]
Regression introduced by #12516
