### ISSUE TITLE
Better Night Sky and more

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12534]
## Problem

The night sky is just a moon and stars plus clouds, boring

## Solutions

adding something rare and beautiful to night sky, like super moon, aurora, yellow moon

also make the world tinted blue in night

## Alternatives

set clouds texture to a green one in cold biomes
edit moon texture to a bit more impressive

## Additional context

today have supermoon in real life

**Comment by oong819** [comment]
hope its not too CPU power wasting

**Comment by rubenwardy** [comment]
Hi, thanks for the suggestion.

It's already possible for mods and games to change the appearance of the sun and moon. Minetest is a game engine, so adding hardcoded new game play features should be avoided. Instead, such features should be added to games

When shaders are enabled, there's already a blue tint at night
