### ISSUE TITLE
liquid flow leaves an air gap before reaching the end of another liquid flow

### ISSUE THREAD

**Issue by Lemente** [minetest/minetest#12549]
##### Minetest version
```
5.5.1
```
##### Summary
```
When a liquid flow reaches the end of a different liquid flow, it doesn't spread to the air node inbetween.
This only happen in specific directions.
```
##### Steps to reproduce
```
- place on liquid on a flat surface
- wait for it to fully flow
- place second liquid close enough in each directions
```

tested with the void game in a flat world, with this custom mod :
[void_liquid.zip](https://github.com/minetest/minetest/files/9128298/void_liquid.zip)

![screenshot_20220717_202419](https://user-images.githubusercontent.com/27686967/179419585-8412c3b6-b882-4d81-b5cb-51c90e4597a5.png)

similar issue : https://github.com/minetest/minetest/issues/2399

**Comment by SmallJoker** [comment]
I don't remember this being a problem. Would you please be so nice to check if it worked in 5.0.1 or other version? Try to bisect if possible. It's been a while since the last liquid changes.

**Comment by Lemente** [comment]
same issue in 5.0.1
![screenshot_20220717_213959](https://user-images.githubusercontent.com/27686967/179422136-9e2623ad-31de-4563-a12c-5c31e2b58fd8.png)

**Comment by erlehmann** [comment]
I think this – or something similar – also happens in 5.4.1 at least.

> I don't remember this being a problem.

The problem created by this is that player-built machinery that relies on liquids touching for something to happen may only work in some directions. Most prominently, this probably affects cobble generators across a wide range of games where flowing lava and flowinrg water can touch to form cobble.

**Comment by wsor4035** [comment]
can confirm this issue

**Comment by kab0u** [comment]
![screenshot_20230119_233124](https://user-images.githubusercontent.com/99147300/213578673-fd232f50-4325-445d-89cd-e276bfb45f3a.png)

Lava can flow into flowing water and creating stone in only two orthogonal directions, in the opposite directions the lava will not flow.

Minetest 5.6.1
Minetest Game 5.6.1

Also does this in MineClone, so it seems like an engine bug.

There is another bug/glitch that seems related:  It is possible to place a solid node near the player's head in such a way that it clips the player's head into the node, resulting in x ray vision.  This also only works only in two orthogonal directions, not in the opposite directions, just like the lava flow pictured above.

**Comment by dontfwiththestream** [comment]
can confirm this occurs for me too

**Comment by ZenonSeth** [comment]
So that was the cause, and I think I got a fix, this is how it looks now with OPs mod/setup:

![image](https://github.com/minetest/minetest/assets/118483769/f546694a-17f9-41a2-a7ed-036a9d35bfb3)

Just need to make sure it doesn't break anything else before making a PR
