### ISSUE TITLE
A fatal error occurs when I try many mods at the same time

### ISSUE THREAD

**Issue by MidnightPhantom** [minetest/minetest#12546]
When I tried these mods with a texture pack a fatal error occured

2022-07-14 14:31:32: ERROR[Main]: A serialization error occurred:
2022-07-14 14:31:32: ERROR[Main]: ServerEnvironment::loadMeta(): EnvArgsEnd not found!
2022-07-14 14:31:32: ERROR[Main]: The server is probably running a different version of Minetest.
2022-07-14 14:31:32: ACTION[Main]: Server: Shutting down
2022-07-14 14:31:32: ERROR[Main]: In thread 1:
2022-07-14 14:31:32: ERROR[Main]: /home/stefan/mt-build/build/minetest_64/minetest/src/serverenvironment.cpp:e9: createIntroductionTimesString: A fatal error occurred: attempted to query on non fully set up LBMManager

The mods which I used were
MTG default mods, mpd, morelights, morelights_dim, nextgen_bedrock, luxury_decor, and edit..
And lastly, the texture pack was soothing32.

The game suddenly crashed and the game closed itself. The world I created was created in 5.5.0 and I did not try to run it on any other engine but it still gave this error.

**Comment by rollerozxa** [comment]
#12543

**Comment by rubenwardy** [comment]
Hi, you open this same issue yesterday (#12543) and it was closed as it was a duplicate.

Did you try the suggestions I made? If an issue is closed but you're unable to resolve the problem, then you should reply to the closed issue and not make a new one

> This happens when env_meta.txt in the world folder is corrupted (perhaps you cut the computer power recently?).
>
> You can either restore the file from backup or delete it

**Comment by rubenwardy** [comment]
Do you have a file called `env_meta.txt.~mt` in the world folder? Does it have content in it? If so, you could rename that to `env_meta.txt`

**Comment by MidnightPhantom** [comment]
For the issue to be sent twice is because when I posted the issue first it got removed from the list

**Comment by MidnightPhantom** [comment]
I have a question does this error happens when you edit the Lua scripts for like changing the ore generation and use a lot of mods

**Comment by IrrlichtMt4** [comment]
The error happens if a world is not able to save properly which causes the file to be not read properly and causes errors like this.
