### ISSUE TITLE
Mods can no longer override textures/media based on load order (devtest error)

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#12557]
##### Minetest version
```
Minetest 5.6.0-dev-d400a98ef (Linux)
```

##### Summary
![screenshot_20220718_222429](https://user-images.githubusercontent.com/1042418/179611682-255b37e5-fbe7-4c70-89a1-0d29d3e3a202.png)

##### Background

The dirt texture exists twice, possibly to test mod loading order in combination with texture overrides:
<pre>
./games/devtest/mods/basenodes/textures/default_dirt.png
./games/devtest/mods/unittests/textures/default_dirt.png
</pre>

suspect change: 06de82fd86678e0a1c260c67792c5cd192863edd

**Comment by Desour** [comment]
See also: https://github.com/minetest/minetest/blob/master/games/devtest/mods/basenodes/textures/info.txt

**Comment by appgurueu** [comment]
As this seems to be a regression affecting mod load order I'm pinging @erlehmann since this may affect the hack used by `_mcl_autogroup`.

**Comment by erlehmann** [comment]
@corarona could this possibly affect MineClone2?

**Comment by appgurueu** [comment]
Can confirm that the suspected change is to blame: Works fine when checking out https://github.com/minetest/minetest/commit/1d512ef7f4071fadf10078825ce83e77a3707f06.
