### ISSUE TITLE
util/stress_mapgen.sh can execute “rm -rf /” if current directory name contains a space

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#12567]
##### Minetest version
Commit 2cf52642fa89a9497b0200f5a4637a25a82f9c3d and newer

##### OS / Hardware
It does not matter.

##### Summary
In `util/stress_mapgen.sh`, the variable `worldpath` is not quoted when given as an argument to `rm -rf`.

It looks like this: `rm -rf $worldpath`. This leads to the shell splitting `worldpath` with the characters in `IFS`.

https://github.com/minetest/minetest/blob/2cf52642fa89a9497b0200f5a4637a25a82f9c3d/util/stress_mapgen.sh

The correct way would be `rm -rf -- "$worldpath"`. The `--` argument prevents `rm` from interpreting filenames as options.

##### Steps to reproduce
I am not deleting my root directory LMAO.

**Comment by erlehmann** [comment]
I suggest to use `shellcheck` on all shell scripts: https://www.shellcheck.net/

**Comment by Wuzzy2** [comment]
I marked this as High priority because of the high danger this bug represents.

**Comment by SmallJoker** [comment]
`rm -rf /` requires `--no-preserve-root` in recent versions, and Minetest is unlikely to ever be installed in the root directory to even cause this issue.

Either way, paths with spaces should now work. 2351c9561
