### ISSUE TITLE
Everything in the HUD should be scalable by DPI

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest#1256]
Everything in the HUD should be scalable by DPI. The DPI should default to being automatically guessed and it should be configurable by the user.

It should work so that all HUD elements are sized similarly relative to the screen size independently of their source image sizes and the screen size. Statbars should be the same relative size to the hotbar no matter what the DPI setting is, what the screen size is and what the statbar image size is.

The fact that it is not so is a bug. Please link all related patches and branches and pull requests in the comments of this issue (it seems that some parts of this have been solved separately).

**Comment by SmallJoker** [comment]
Implemented in #1370.
Follow-up issues: #6735 and #6296
