### ISSUE TITLE
Activating shadows on some GPUs may lead to faulty rendering, unplayable laggy game

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#12569]
##### Minetest version
Commit 2cf52642fa89a9497b0200f5a4637a25a82f9c3d 

##### OS / Hardware
CPU: Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

GPU model: Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)
OpenGL version: 1.4

##### Summary
I activated shadows in settings and set them to the lowest quality level.
In devtest, I got a laggy & faulty rendering that was essentially unplayable.
Upon joining the world, Minetest printed the following error message four times:

```
COpenGLCoreTexture: Color format is not supported: R32F
```

Plenty of other software manages to draw shadows just fine on this (admittedly dated) hardware.
I think that if that color format is so important to the Minetest implementation, Minetest should not allow me to enable shadows if it is not supported.

##### Steps to reproduce
See above.

**Comment by erlehmann** [comment]
I found that when using another color format that is supported by the GPU, shadows still seem to work, but rendering performance is still abysmal in hardware rendering mode at <1fps with shadows (~30 fps without shadows). I get 4 to 7fps when using software rendering regardless of if shaders or shadows are on or off, which really confuses me. How can rendering via hardware be slower than rendering via software?

**Comment by rubenwardy** [comment]
Minetest shaders (including shadows) require at least OpenGL 2. It's completely unreasonable to expect fancy effects to work on hardware from 16 years ago.

OpenGL 1 doesn't even support shaders, it uses a fixed pipeline. Soon, we will require OpenGL 2 to run Minetest. OpenGL 2 was released in 2004, it's not practical for us to keep supporting hardware that old as we continue to improve the graphics code.

The fix for this is to disable shaders and the shader settings UI when OpenGL 1 is detected, and tell the user that their hardware will no longer be supported

**Comment by erlehmann** [comment]
> It's completely unreasonable to expect fancy effects to work on hardware from 16 years ago.

Indeed, but non-colored shadows are by no means a “fancy” effect. Irrlicht can do realtime shadows on the hardware just fine.

> OpenGL 1 doesn't even support shaders,

As I understand, OpenGL1.x does not require shader support. The Intel 945GM does support the following extensions though:

* GL_ARB_fragment_shader
* GL_ARB_shader_objects
* GL_ARB_vertex_shader
* GL_ARB_shading_language_100

To me this looks like it supportst the most ancient of shaders, just pre OpenGL-2.0. Is this useful for anything rendering-wise?

I noticed that the GPU also claims to support OpenGL ES 2.0 with GLSL ES 1.0.16 – but as we have seen in the Mali 400 GPU issue, Minetests shaders exceed the linstruction iimits guaranteed by OpenGL ES, so they do not work on all OpenGL ES GPUs.

> The fix for this is to disable shaders and the shader settings UI when OpenGL 1 is detected,

If there is no way to make it work via the above OpenGL extensions, I am totally in favor of that solution.
The issue is not “shadows do not work” – it is “users can make Minetest hang itself by enabling shadows”.

**Comment by erlehmann** [comment]
I have confirmed that the Intel 945GM can indeed do shaders by learning a bit of GLSL and using it:

The vertex shader:
```
varying vec3 normal, lightdir;

void main()
{
	normal = normalize(gl_NormalMatrix * gl_Normal);
	lightdir = normalize(vec3(gl_LightSource[0].position));
	gl_FrontColor = max(
		dot(normal, lightdir),
		0.0
	) * gl_FrontMaterial.diffuse;
	gl_Position = ftransform();
}
```

The fragment shader:
```
varying vec3 normal;

void main()
{
	gl_FragColor = vec4(
		gl_Color[0] * normal[0],
		gl_Color[1] * normal[1],
		gl_Color[2] * normal[2],
	1.0
	);
}
```

Here is a still frame of applying that to a rotating teapot lit from the side: https://mister-muffin.de/p/JKUR.png

Now I am definitely very far an expert on the topic – but thie result looks a bit like realtime shadowing to me.

**Comment by rubenwardy** [comment]
That's shading, not shadows - shadows requires casting and appearing on other objects

If it supports shaders then it's not OpenGL 1.4, it's at least OpenGL 2

**Comment by erlehmann** [comment]
> That's shading, not shadows - shadows requires casting and appearing on other objects

Ouch, indeed I obviously have very little idea of what I am doing.

> If it supports shaders then it's not OpenGL 1.4, it's at least OpenGL 2

Again, I am convinced this is wrong, given that I the GPU can do shaders.

> What does glinfo and the About tab in the Minetest mainmenu say?

```
; glxinfo |grep 'OpenGL.* version string'
OpenGL version string: 1.4 Mesa 20.3.5
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
```

The “About” tab says the renderingis done using OpenGL 1.4.

So what now?

**Comment by erlehmann** [comment]
I figured it out: When the number of instructions exceeds some limit by even one instruction, rendering becomes absurdly slow.
I tested this by adding instructions to the fragment shader I posted above, until my demo program stopped rendering in realtime.

This is very similar to the Mali 400 shader instruction limit issues: https://github.com/minetest/minetest/issues/12035

Unfortunately, this presents a problem: One can not rely on support for GLSL or the OpenGL (ES) version.
The most important information seems to be how many instructions the GPU can chew on without choking.

Maybe minetest could try rendering a single frame at load time and if that takes too long, disable shaders?

**Comment by SmallJoker** [comment]
@erlehmann Hardware limitations should be addressed by the driver, not end-user applications like Minetest. Unless someone's keen to implement this timeout feature, I don't see any point in caring about somewhat low performance and buggy iGPUs.

**Comment by erlehmann** [comment]
> @erlehmann Hardware limitations should be addressed by the driver, not end-user applications like Minetest. Unless someone's keen to implement this timeout feature, I don't see any point in caring about somewhat low performance and buggy iGPUs.

The GPU might be crappy, but this is not a driver bug. The hardware simply supports less instructions than some Minetest-provided shader is using.

I doubt any driver update can prevent an application from exceeding these limits. These are documented btw.

Regarding performance: Without shaders Minetest runs just fine (30fps).

I am willing to implement the timeout feature, if it does result in simply disabling shaders and not in telling users that their GPU is not supported and exiting. I simply do not know how to do it yet, though.

**Comment by rubenwardy** [comment]
The solution to this is to not allow enabling shaders when OpenGL < 2.0. Yes, there's partial support, but full support is required

**Comment by sfan5** [comment]
closing in favor of #10097

**Comment by erlehmann** [comment]
> Minetest shaders (including shadows) require at least OpenGL 2. It's completely unreasonable to expect fancy effects to work on hardware from 16 years ago.

@rubenwardy of course it would be unreasonable to expect fancy effects to work. But shadows do not necessarily have to be fancy effects, as this screenshot that I made just now on my Thinkpad T60 shows. Irrlicht could always do this, it is just that no one bothered to actually call `addShadowVolumeSceneNode()` on their meshes,

![minetest-580-dev-using-irrlicht-shadows](https://github.com/minetest/minetest/assets/60905/0b8cebca-0173-454f-8101-d06dc5449cff)
