### ISSUE TITLE
Add support for showing compatible mods for games in Select Mods

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#12565]
## Problem

A clear and concise description of what the problem is.
some base game is not compatible with additional addon will result in crash 

## Solutions
force user to not add  additional plugin / addon that are not compatible with current used base game

## Additional context
crash log will posted soon

**Comment by rubenwardy** [comment]
Related: #12034

**Comment by rubenwardy** [comment]
Duplicate of #13851
