### ISSUE TITLE
Android main menu doesn't render

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12573]
##### Minetest version
2cf52642fa89a9497b0200f5a4637a25a82f9c3d

##### OS / Hardware

Google Pixel 4a, Android 12

##### Summary

After extracting the assets, a  blank blue screen is shown

```
I/AdrenoGLES-0: Build Config                     : S P 10.0.4 AArch64
I/AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
I/AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
W/AdrenoUtils: <ReadGpuID_from_sysfs:197>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
W/AdrenoUtils: <ReadGpuID:221>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
I/libOpenSLES: Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
E/openal: [ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
E/Adreno-UNKNOWN: <glTexParameteriv:151>: GL_INVALID_ENUM
```

##### Steps to reproduce
APKs: https://github.com/rubenwardy/minetest/releases/tag/5.6.0-rc1

**Comment by rubenwardy** [comment]
Another thing to note is that I deleted deps and deps.zip. I didn't do this on previous releases

**Comment by oong819** [comment]
also i dont see minetest title on android

**Comment by rollerozxa** [comment]
> also i dont see minetest title on android (5.5.1)

this is because the Android version of Minetest used to not have the gamebar enabled, it has been enabled in 5.6.0 which means that the minetest logo will now show up in the main menu. (also irrelevant to this issue)

**Comment by rubenwardy** [comment]
I don't have it installed to lib/irrlichtmt and I deleted deps.zip/deps before running the build. I didn't change anything else

Is #12571 or some change to minetest_android_deps needed?

**Comment by sfan5** [comment]
I pushed to minetest_android_deps and changed some stuff, try again now.

By the way any NDK newer than r23c requires more changes on our side since Google dropped some old device support:
> Jelly Bean (APIs 16, 17, and 18) is no longer supported. The minimum OS supported by the NDK is KitKat (API level 19).

~https://github.com/android/ndk/wiki/Changelog-r24

**Comment by sfan5** [comment]
Still happens with the APK from the last CI run.

Note to self, here's how to get it to install:
```sh
.../android-sdk-linux/build-tools/30.0.3/apksigner sign --ks ~/.android/debug.keystore app-armeabi-v7a-release-unsigned.apk
# enter 'android' as password
```

**Comment by JayAsPro** [comment]
Hello there! I'm just a Minetest player, not a developer. (can I even comment here as a normal player? first time commenting on a Github issue!) I just want to try to contribute with my personal experience.
Sometime ago, I downloaded one of the Android CI builds from the master branch to test the new version. This exact bug happened when I changed the graphics API to OpenGL ES 2. With OpenGL ES 1 (the default, at least at the time) everything worked normally.
Does those things have some relation? You are working on some huge changes on rendering recently.
_Sorry for my bad English. Brazilian here!_

**Comment by sfan5** [comment]
Could be that the shader files were not copied/packaged correctly, the same accidentally happened on desktop for me.

**Comment by rollerozxa** [comment]
Just figured out the change that causes this issue through poor-man's bisecting (installing APKs from github actions): https://github.com/minetest/minetest/commit/051181fa6ee00d8379e8a7dc7442b58342d4352b clamped the screen width and height to be at least 1, which breaks with android where the settings need to be set to 0. See #12604
