### ISSUE TITLE
Inventory slots in Repixture look different in 5.6.0-dev (with gui_scaling_filter = true)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12581]
##### Minetest version
```
2cf52642fa89a9497b0200f5a4637a25a82f9c3d
```

This is 5.6.0-dev.

##### Summary

The inventory slots of Repixture 3.3.0 look a bit different after the update to Minetest 5.6.0-dev.

https://www.satoshiupload.com/images/Gz2DFb16jW.png

The correct way for the slots to look is without that thin extra border. In the -dev version, a slight "border" suddenly appeared, which looks mildly irritating, and I want to get rid of it, and I don't know how. Either way, this seems like a regression.

This screenshot was taken in Minetest 5.5.0 and 5.6.0-dev, playing Repixture 3.3.0, respectively. The left one is the behavior I want, the right one shows the undesirable behavior. Both screenshots were taken at a window size of 2560×1389 (excluding window decorations).

##### Steps to reproduce

1. Open the inventory in each of the 2 Minetest versions
2. Compare

**Comment by SmallJoker** [comment]
Which colors are supposed to overlap there? What's the list style and background color? I'd like to first make sure that the new behaviour is the incorrect result.

**Comment by Wuzzy2** [comment]
Here is the image used for a single inventory slot: https://codeberg.org/Wuzzy/Repixture/raw/commit/57e27bc5e215678bb41f67a3a3cc3cd7e511169e/mods/rp_formspec/textures/ui_itemslot.png
Note that alpha value for the inner part of the square is set to 12 (decimal) with the color black.

The list style colors are `listcolors[#00000000;#00000010;#00000000;#68B259;#FFF]`. In other words, the colors are transparent (except for the highlight which does not matter); so the color entirely comes from the slot image. The inventory background color is `#8c7c5b`. It's the same in both cases, no bug here.

The source code for the formspec code is here: https://codeberg.org/Wuzzy/Repixture/src/tag/3.3.0/mods/rp_formspec/init.lua

**Comment by Wuzzy2** [comment]
If you zoom in into that screenshot I posted, you will notice that the slot image is anti-aliased in the 5.6.0-dev image (the wrong one) but has sharp edges in the 5.5.0 image (the correct one). Maybe this strange 1px border comes from the anti-aliasing?

**Comment by x2048** [comment]
I could reproduce is with `gui_scaling_filter = true`, setting it to false renders without the dark border.

**Comment by sfan5** [comment]
recently commits that touched the filter implementation:
* f7bcf7fa46a634653e50f9e580faf2a53ab50e88
* 3ce5a68cd12e45d7b618c49e205936fb140ecbfe

**Comment by x2048** [comment]
Looks like the issue is introduced in f7bcf7fa46a634653e50f9e580faf2a53ab50e88. The commit before that does not have the problem.

**Comment by x2048** [comment]
As suspected, f7bcf7f replaces stock image implementation with GUIAnimatedImage in [GUIFormSpecMenu::parseImage](https://github.com/minetest/minetest/commit/f7bcf7fa46a634653e50f9e580faf2a53ab50e88#diff-d518daac1f5499b49517a02957e29771288333e58227308b7711cc5da6bd1544L811).

As GUIAnimatedImage uses NNAA filter that produces the artifact, stock image implementation does not use the filter and always produces NN-scaled image.

**Comment by x2048** [comment]
@v-rob Can you take a look and suggest a solution?

**Comment by v-rob** [comment]
Well, I guess the first question would be whether images should use the GUI scaling filter or not.  It's certainly weird in any case for animated images to use the filter and static images not to use it--they should both use the same thing.

I guess that it's probably best for all 2D images to use the GUI scaling filter since it can be turned on and off, whereas the other is always forced to be drawn one way.  After all, why have the scaling filter if things don't use it?  I'm not particularly fond of the scaling filter and prefer raw image drawing, but that's perhaps not the best reason.  Maybe someone who know why the filter exists could give a better explanation/rationale/solution?

**Comment by sfan5** [comment]
The gui scaling filter was added to resolve #2419 but it's kind of bolted on (intercepts draw calls) and has a few bugs.
And in fact, you could let the GPU do antialiasing even for 2d drawing so it can probably be simplified tremendously.

If applying the filter consistently fixes this issue then we should do that, if not then I'd just file this under bugs the filter has and not consider it essential to solve for 5.6.0.

**Comment by Wuzzy2** [comment]
But how will I work around this bug if it gets released into 5.6.0? :-(

**Comment by x2048** [comment]
I suggest that we keep previous image implementation for non-animated non-9-slice images until we fix the filter.

**Comment by Wuzzy2** [comment]
Can confirm the bugfix. Thank you. :-)
