### ISSUE TITLE
Delete favorite button texture missing

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#12583]
##### Minetest version

```
5.6-dev
03d86ea
```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

Delete favorite button texture missing
![image](https://user-images.githubusercontent.com/52937829/180484977-a2749dce-918b-410d-9913-da3b058ceb3e.png)

It seems enough to add core.formspec_escape around defaulttexturedir .. "server_favorite_delete.png" to fix it.
https://github.com/minetest/minetest/blob/2183b35ba4cda762e3176a7b442dd786e749b35d/builtin/mainmenu/tab_online.lua#L113

**Comment by SmallJoker** [comment]
8dcbca106
