### ISSUE TITLE
Minetest log file size limit: allow sizes < 1

### ISSUE THREAD

**Issue by MrRar** [minetest/minetest#12586]
## Problem

The minimum size limit for debug.txt is 1MB. It is not possible to have a limit smaller than this.

## Solutions

It would be nice to allow the limit to be a floating point number so you can use a size in-between 0 and 1

**Comment by sfan5** [comment]
What is your situation that an e.g. 100KB file is not too big but 1MB is?

**Comment by SmallJoker** [comment]
Use `debug_log_level = none` in your minetest.conf file and you should be good to go. If such small file sizes a problem to you, you might as well turn off logging anyway.

**Comment by MrRar** [comment]
> What is your situation that an e.g. 100KB file is not too big but 1MB is?
It is my preference. I don't want to keep 1MB+ of logs I just want to see what just happened and nothing else. 1MB is very large for a text file.

> Use `debug_log_level = none` in your minetest.conf file and you should be good to go. If such small file sizes a problem to you, you might as well turn off logging anyway.
My use case is debugging so I don't want no logs at all. But that is good to know.

You would agree, more options is better than less options no? And I believe this would be trivial to implement. You could even just change the  unit of the limit from MB to KB.

**Comment by MrRar** [comment]
Why was this closed? Is there a technical or practical reason why logs can't be less than 1MB? Please reopen. This was never fixed.

**Comment by Zughy** [comment]
It's "not planned", not "completed"

**Comment by MrRar** [comment]
@Zughy Some people want logs less than 1MB even if you don't. What is it to you if people are able able to have smaller logs? You are free to have your 10MB log. Making this change won't stop you from having your logs as big as you want.

I don't care that you personally aren't planning to make this change. Maybe someone else will. Problems need to be tracked whether they are fixed or not.

**Comment by SwissalpS** [comment]
Sometimes I redirect application output to a filter or just into another log file. Then I use 'tail -f' on that file to get only the most recent entries (and only filtered).

That way I don't have the overhead of opening huge log files in a text editor but still can c/p whenever needed.
