### ISSUE TITLE
Appdata not valid

### ISSUE THREAD

**Issue by farribeiro** [minetest/minetest#12597]
##### Minetest version

```
[📦 net.minetest.Minetestdevel ~]$ minetest --version
Minetest 5.6.0-dev-7e78c01 (Linux)
Using Irrlicht 1.9.0mt7
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"
```

##### OS / Hardware

Operating system: Fedora 36
CPU: Intel® Core™ i7-4790K × 8

GPU model: GTX650
OpenGL version: 4.6.0

##### Summary

Appdata validates fails

##### Steps to reproduce

```
[📦 org.freedesktop.Sdk misc]$ appstream-util validate net.minetest.minetest.appdata.xml 
net.minetest.minetest.appdata.xml: FAILED:
• tag-invalid           : <url> type invalid [unknown]
• attribute-invalid     : <screenshot> width too large [http://www.minetest.net/media/gallery/1.jpg] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [http://www.minetest.net/media/gallery/1.jpg] maximum is 900px
• attribute-invalid     : <screenshot> width (1920) did not match specified (1367) [http://www.minetest.net/media/gallery/3.jpg]
• attribute-invalid     : <screenshot> height (1080) did not match specified (832) [http://www.minetest.net/media/gallery/3.jpg]
• attribute-invalid     : <screenshot> width (1920) did not match specified (1280) [http://www.minetest.net/media/gallery/5.jpg]
• attribute-invalid     : <screenshot> height (1080) did not match specified (653) [http://www.minetest.net/media/gallery/5.jpg]
Validation of files failed
```

**Comment by sfan5** [comment]
> • tag-invalid           : &lt;url&gt; type invalid [unknown]

This is unfortunately not useful, which of the [eight url tags](https://github.com/minetest/minetest/blob/master/misc/net.minetest.minetest.appdata.xml#L71-L78) is it?

> &lt;screenshot&gt;

the screenshots were changed in https://github.com/minetest/minetest.github.io/pull/254
I would have preferred if they were still 1080p but I guess we can just change the appdata file.

**Comment by Wuzzy2** [comment]
So the screenshot ones seem to be obvious fixes. Just specify the correct screenshot size. And it seems like screenshot 1 needs to be resized itself first.

But the `<url>` bug does not make sense to me. The URL tags look all valid to me, and all of the types seem to exist:

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-filespec

Maybe your validator is outdated? Maybe one of the URL types was added in a later AppData version.

**Comment by farribeiro** [comment]
Need a downstream patch for flathub packaging while wait the upstream fix for next release, https://github.com/flathub/net.minetest.Minetest/pull/39

Cause not pass to publish

**Comment by sfan5** [comment]
Regarding these two:
<pre>
• attribute-invalid     : <screenshot> width too large [http://www.minetest.net/media/gallery/1.jpg] maximum is 1600px
• attribute-invalid     : <screenshot> height too large [http://www.minetest.net/media/gallery/1.jpg] maximum is 900px
</pre>

It's absolute nonsense to not permit 1080p screenshots and I have been informed that [the standard](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots) makes absolutely no mention of resolution limits.
Maybe someone should tell the Flatpak team that their validator is broken.
