### ISSUE TITLE
mouse event issue w/ inventory lists

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#12596]
##### Minetest version
```
0.4.17.1 through 5.5.1, 5.6.0-dev-de8ce9a8ff999c7ab9562528a972d5426a9f7cec
```

##### OS / Hardware
Operating system: linux, unsure about mac/windows/etc

##### Summary
There are separate mouse-click events triggered on both press and release. This allows a player to press and hold a mouse button over an item in one slot in an inventory list, drag it to another slot, and release the mouse button it, replacing the other item, and picking up what was in that slot.

There is a separate behavior, whereby a player can click and release the button, resulting in the item being "picked up", while allowing them to drag it around w/out having to hold down the mouse button. Another click will deposit it (or replace what's in the target slot). 

However, a player trying to pick up an item using the second mechanism can quite easily trigger the first behavior accidentally, if they are moving the mouse quickly. The result is that they end up moving the wrong item to the target location, which is a big problem if the target location is e.g. the "trash" slot in unified inventory. 

IMO the solution should be to add a minimum time before the release can trigger an event, some fraction of a second. 

##### Steps to reproduce
While moving the mouse fairly quickly, click on something and release the mouse button (it's easier to replicate if you pause ever-so-slightly before you release.

https://user-images.githubusercontent.com/25628292/181096647-5e93e322-b89b-415a-9c56-2771c0185ce5.mp4

 In this demonstration video, the problematic behavior only happens on the third attempt.

**Comment by erlehmann** [comment]
I can confirm that this happens in 5.4.1 and 5.5.0 at least. It happens more often, if there is client rendering lag.

**Comment by OgelGames** [comment]
> @OgelGames How did #13146 fix this?

This:
> - Moving an item over another item now requires an additional click to swap

**Comment by Desour** [comment]
Ah ok, thx!
(I mistakenly thought this issue included when you mistakenly (i.e. through lag) hold the button too long, oops, sorry!)
