### ISSUE TITLE
get "max_lag" without the whole server status

### ISSUE THREAD

**Issue by crazyginger72** [minetest/minetest#1259]
It would be very useful to be able to call "minetest.get_max_lag" for example to show lag time in-game or on a text addition to the hud!  "minetest.get_server_status" brings alot of information that isn't always needed and if there are more than 10 players on or the player names are very long it can crowd the chat area of the screen.  

I have already set up a in-game clock to show world time as text next to the hud, it has an option to show status as well but as i stated before it is too much/too long!

here is a screenshoot of my clock, the lag could be showed below it :)
![sshudtime](https://cloud.githubusercontent.com/assets/6799444/2812517/ebc8986e-ce5e-11e3-972a-881155a6117c.png)

I have tried to add the code myself but my c/c++ are limited to embedded platform at the moment :(

**Comment by rubenwardy** [comment]
related PR was closed
