### ISSUE TITLE
Cant pickup cart

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12610]
##### Minetest version

```
Tested on 5.4.2, 5.5.0, 5.5.1
```

##### OS / Hardware

Operating system: Android 6.0.1 (API Level 23)
CPU: Mediatek MT6734

GPU model:
OpenGL version: ES 3.1

##### Summary

I  cannot pickup cart on my phone
i tried double tap when sneaking and long tap when sneaking, both dont work

video:
https://youtu.be/v-CoUqEfAsY

##### Steps to reproduce

idk

**Comment by oong819** [comment]
API level 23

**Comment by oong819** [comment]
now have a video

**Comment by wwar-XeStro** [comment]
👀 nope you totally can.
Start long tapping before sneaking.


Start your long tap, shortly after that sneak without holding your finger you are tapping with :)


Also worthes notting that long tapping *after* starting to sneak, use aux1 or jump is impossible in android. It is also impossible to move the camera while long tapping....

**Comment by rubenwardy** [comment]
duplicate of #11404
