### ISSUE TITLE
[Question] How good of a pc do you need to run MineTest?

### ISSUE THREAD

**Issue by Tulip-0333** [minetest/minetest#12617]
I want to play this, but Idk if this can run on my computer.

**Comment by SmallJoker** [comment]
Why don't you just try it? Writing this post and waiting for an answer takes longer than downloading approx. 20 MB of data.

**Comment by rubenwardy** [comment]
The graphic card can be integrated (iGPU)

Minetest has pretty low requirements, it's one of its selling points

**Comment by erlehmann** [comment]
On Linux, I figured out the approximate answer using the Mesa environment variable `MESA_EXTENSION_MAX_YEAR`.

* Current MInetest (using IrrlichtMT) will not render the world if the `MESA_EXTENSION_MAX_YEAR` is lower than 2005.
* MInetest 5.4.1 (using Irrlicht) is able to render the world even with a value of 1990, but the rendering drops a bit in quality.

I strongly suspect this is another result of the “let's remove everything from Irrlicht we do not need to make IrrlichtMT” idea.
However, I doubt it matters: If you play a on computer that is that old, MInetest 5.4.1 should be able to join a modern server.

@Tulip-0333: You should know that this question does not belong in an issue tracker. Next time, ask on IRC or just try it out.

**Comment by sfan5** [comment]
Enabling a mesa option that messes with the extension string without changing the reported GL version is certainly not an accurate way to determine how new your hardware needs to be. I cannot reproduce your claims either.

**Comment by erlehmann** [comment]
I think rendering fails as color format `D24S8` is not supported by Mesa pre-2005. Minetest 5.4.1 seems to not require it.

You can set the OpenGL version as low as 1.0 • as long as that color format is missing, newer MInetest will tell you:
```ERROR[Main]: Irrlicht: COpenGLCoreTexture: Color format is not supported: D24S8```

Minetest will probably not run on a potato from 1990 – at the very least because that computer will not have the RAM.

**Comment by Tulip-0333** [comment]
Alrighty

**Comment by rubenwardy** [comment]
If you're having problems with your graphics card, you can try software OpenGL rendering. You can do that on Linux with `LIBGL_ALWAYS_SOFTWARE=1 minetest`   idk about other platforms

**Comment by erlehmann** [comment]
> If you're having problems with your graphics card, you can try software OpenGL rendering. You can do that on Linux with `LIBGL_ALWAYS_SOFTWARE=1 minetest` idk about other platforms

Are you aware of any hardware on which this yields a playable game, but utilizing the GPU does not?
