### ISSUE TITLE
Crash when trying to change font while clicking the browse button (VIDEO)

### ISSUE THREAD

**Issue by PalmTamino** [minetest/minetest#12627]
##### Minetest version
5.5.1

```

```

##### OS / Hardware

Operating system: Windows 11
CPU: Ryzen 5 3600

Video: https://streamable.com/qxr91k

**Comment by oong819** [comment]
look like you're not using Windows 11

**Comment by Zughy** [comment]
can't reproduce on Windows 10, neither on 5.5.0 nor on latest commit (https://github.com/minetest/minetest/commit/839600ed703ccffbdb71bd2f04fb379d0920da95)

**Comment by PalmTamino** [comment]
> can't reproduce on Windows 10, neither on 5.5.0 nor on latest commit ([839600e](https://github.com/minetest/minetest/commit/839600ed703ccffbdb71bd2f04fb379d0920da95))

Hmm, maybe its only Windows 11?

**Comment by Jordach** [comment]
Windows 11 may require elevated user rights to read/write to Program Files and it's ilk.

**Comment by rubenwardy** [comment]
`C:\Program Files` is not a writable location and I don't think Minetest supports non-portable builds on Windows. Please retest with Minetest installed somewhere like `C:\Minetest` or `C:\Users\username\`
