### ISSUE TITLE
Undersampling makes stars flicker

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12625]
##### Minetest version
```
5.5.0
```

(and 5.6.0-dev)

##### Summary
If you activate the `undersampling` setting, set it to `8` and look at the night sky, the stars flicker on and off. This does not happen if this is disabled.

##### Steps to reproduce
* Set `undersampling=8`
* Set `time_speed=72` (so the stars will move)
* Start the game
* Wait for night time
* Look at the sky

**Comment by appgurueu** [comment]
Can "confirm".

I'd say this is probably expected when rendering to such low resolutions. The stars can hardly be tweaked to be at least 1px on every resolution. For `undersampling = 8`, stars that are only a couple pixels large will always be at the brink of invisibility; small float fluctuations as the stars move probably make them flicker (technically they should always be the same distance and thus not flicker).

Possible fix: Calculate minimum star size based on resolution - discard smaller stars entirely.

**Comment by wwar-XeStro** [comment]
More undersampling stuff here #5929 if that helps.
