### ISSUE TITLE
Request to reconsider removal of finite liquid & weather

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1262]
I noticed that finite liquid was removed, as well as the weather system in minetest_game, the developers considering it too buggy and unsupported. I didn't consider finite liquid a feature anyone would miss, so I didn't find this important. But now I also found out that the entire temperature / humidity system, usable (and perhaps already used) by mods was also taken down with it! Luckily I didn't use it yet, but had plans to and there's a lot that could be done with it.

https://github.com/minetest/minetest/commit/0279f32db742f06d24a9d01c46f7d70c5e570eb2

I wish to call all developers, as well as users who want to have a say on the matter, to debate whether this removal was good and to what extent. As well as suggest reverting it if enough people agree it was not a good idea. I understand some bugs no one would fix were the reason behind this decision... what were they, and how bad and important?

I don't care about finite liquid myself... but would like the weather system back. At least the humidity and temperature system, even if freezing won't be added back to minetest_game without finite fluids. I planned and am planning to use these in my mods, and from my observations they were not buggy either. Having a temperature and humidity (which also influenced fog density) were great features and I see no reason for them to go!

**Comment by paramat** [comment]
Only proller's dynamic weather heat and humidity was removed, the static mapgen heat and humidity remain. You can already calculate these at point in lua by using perlin noise. Closing.
