### ISSUE TITLE
Field of view setting doesn't work

### ISSUE THREAD

**Issue by BeyondThe5D** [minetest/minetest#12635]
##### Minetest version

```
5.5.1
```

##### OS / Hardware

Operating system:
CPU:
Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

GPU model:
OpenGL version:

##### Summary

When changing the field of view it doesn't work and always appears the same no matter the value

##### Steps to reproduce

Go to "Settings"
Click "All settings"
Search "Field of view"
It should appear under "Graphics > In-Game > Advanced"
Change it to any value
Load up the game and compare it to other values, they are exactly the same

**Comment by Zughy** [comment]
Wait, so people can change their FoV if no mod is overriding it? W H A T ?

**Comment by rubenwardy** [comment]
Please note that FOV is vertical FOV, not horizontal. So you need to resize the window vertically to see a change. There's also a min of 45 and a max of 160. The server can also override your FOV

**Comment by Zughy** [comment]
Can't I use this to cheat in some games?

**Comment by rubenwardy** [comment]
You could also make your window wider to do that. Games where this matter can set the FOV manually

**Comment by Zughy** [comment]
How about there is a default FOV value that players can't touch and, if a game/server wants to change it, they do it on their own?

**Comment by wwar-XeStro** [comment]
Android here.

The fov always worked well for me since it was added... i'd have left munetest if i could not change it from... ugh 72

**Comment by IrrlichtMt4** [comment]
Try setting the FOV to very high and compare it to the FOV being very low. Could be a human bug.
