### ISSUE TITLE
Ugly wiki.

### ISSUE THREAD

**Issue by Soupborsh** [minetest/minetest#12634]
## Problem

Minetest wiki is ugly and unresponsive on small screens and android devices.
ie: I It is necessary to make it user friendly and beautiful. Now it seems that the site has not changed since 2000.

## Solutions

It is necessary to redo the site, it is simply possible to rewrite the CSS or redo everything from scratch.
I can help you with this, I know html, css and react app. 

## Additional context

I am a beginner frontend developer. Here is my first project: www.soupmine.ru . I'm 13 and won't have much time during the school year so I won't be able to help much.

**Comment by rollerozxa** [comment]
> It is necessary to redo the site, it is simply possible to rewrite the CSS or redo everything from scratch.
I can help you with this, I know html, css and react app.

The Wiki uses MediaWiki, Vector being the default skin but we could simply add the mobile skin that e.g. Wikipedia uses and switch to that on mobile, which is what most MW wikis do nowadays for a responsive mobile experience.

**Comment by IrrlichtMt4** [comment]
In my opinion, I think it would be nice to have a similar layout to the Minetest menu from the game in the wiki.

**Comment by Soupborsh** [comment]
> In my opinion, I think it would be nice to have a similar layout to the Minetest menu from the game in the wiki.

No, minetest menu is ugly and unresponsive too. We need something pixelated, user-friendly and responsive. Many menu items are hidden behind something, the text does not fit, they are hard to hit with a finger on a smartphone. It's a terrible menu, it's disgusting to look at. I think Maintest should look nice to attract players. People need to have the pleasure of the menu, and everything was clear where to click. I also suggest changing the font to something pixelated by default

**Comment by Soupborsh** [comment]
It's really ugly. Ok, I'm leaving I will play Minecraft. Play with this ugly menus and site if you like.

**Comment by rubenwardy** [comment]
Improving our UIs is one of our top priorities. The main menu is being redesigned, making the wiki match it makes absolutely no sense

**Comment by Soupborsh** [comment]
> Improving our UIs is one of our top priorities. The main menu is being redesigned, making the wiki match it makes absolutely no sense

Nice to hear this. Yes, the wiki should be different from the menu, I have no complaints about this. I just don't like the fact that the wiki is not beautiful and not convenient.

**Comment by Soupborsh** [comment]
![Screenshot_2022-08-02-18-00-36-15](https://user-images.githubusercontent.com/100529201/182369771-a141bf36-f36e-4940-bbb2-09168ff2e824.jpg)
![Screenshot_2022-08-02-18-00-52-77](https://user-images.githubusercontent.com/100529201/182369780-9b99a114-d1c7-460c-aff4-ddc93e7cf740.jpg)
![Screenshot_2022-08-02-18-00-04-80](https://user-images.githubusercontent.com/100529201/182369785-bd5fcb0e-12c8-4a1d-9e80-e5abaa6c2d3d.jpg)
I don't think that is convenient and beautiful.
