### ISSUE TITLE
Make relative number support for chat commands visible in syntax help

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12648]
## Problem

A few commands support relative numbers (by preceding the number with a tilde) now, but the chat command help does not mention that.

## Solutions

In the syntax reference (what you get with `/help`), add a tilde in the parameter name at the beginning if it supports relative numbers. So for example, instead of writing:

```/teleport <X> <Y> <Z>```

in the chat command syntax help, write:

```/teleport <~X> <~Y> <~Z>```

The tilde means "this parameter supports a relative number".

## Alternatives

One meh alternative is this: Maybe write this out in words in the regular command description? Downside this will make the text more bloated.

**Comment by GoodClover** [comment]
To me `<~X>` reads as "X is relative".
What's inside the angles is a label for the argument, so I think `~<X>` would make more sense. But either works 🤷

I'd be more in favour of not doing this at all, and making all built-in commands accept relatives (if they don't already?). That way it's consistent, I'm unaware of any reason not to accept relative numbers.

**Comment by SwissalpS** [comment]
I support the idea of generally accepting relatives then it only needs to be described once.

Otherwise, wouldn't it be more correct to output: ``<[~]x>``?
The ``~`` should not be outside the ``<>`` as it belongs to the parameter.

**Comment by Wuzzy2** [comment]
> I'd be more in favour of not doing this at all, and making all built-in commands accept relatives (if they don't already?). That way it's consistent, I'm unaware of any reason not to accept relative numbers.

This is not possible or reasonable because there must always be a value to which the number is relative to. For example, the `/shutdown` command can logically only accept an absolute shutdown timer, not a relative one (relative to what?). So a distinction makes sense.

I don't care about the exact syntax too strongly, but just to have some marker to make it more visible. I would like to hear core dev opinions.

I like my syntax the most because it is the most compact. Syntax is always kinda arbitrary, it just needs to be defined *somewhere*.

**Comment by GoodClover** [comment]
I meant for all commands that accept *locations*, where it'd usually be from the players's position.
`/shutdown` is already relative from the instant of invocation :P

**Comment by Wuzzy2** [comment]
After having played with this idea for a little, I think my idea as well as similar suggestions aren't really helpful. Sure, there is now that tilde in the command help, but people will likely not understand it. And in some cases like `/time`, it just looks very awkward.

I have a better idea now: Document every single parameter in chat commands. See #12842.

Closing.
