### ISSUE TITLE
RmlUi support

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#12644]
## Problem

The current UI framework is quite limited, doesn't support anymations and is quite annoying to use.

## Solutions

Use of the RmlUi framework for UI! Even tho it only supports *most* of HTML and CSS, it can still do a lot more than the current UI, like animations.

## Alternatives

CEF? Lol

## Additional context

[Add any other context or screenshots about the feature request here.](https://github.com/mikke89/RmlUi)

**Comment by Zughy** [comment]
We have an issue about formspec replacement in general, please suggest RmlUI in there => #6527
Closing here
