### ISSUE TITLE
Add favorite button

### ISSUE THREAD

**Issue by AspireMint** [minetest/minetest#12647]
## Problem

I can't add server to Favorites list.
When i move to new MT version, i have to quick visit each server to have it in favorites :/

## Solutions

Add button "Add to favorites" (image_button/whatever, same as Remove favorite)

## Additional context

Related #4028

**Comment by sfan5** [comment]
> When i move to new MT version,

You can copy the file that contains the favorites just like you copy your worlds or mods.

**Comment by Zughy** [comment]
I took this in consideration during my main menu redesign https://github.com/minetest/minetest/issues/6733#issuecomment-1130349592

**Comment by siliconsniffer** [comment]
I'd be willing to adopt #13446 and implement that while formspec is still around...
