### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by cyxv** [minetest/minetest#12649]
Having Minetest on iOS would be fantastic. It already has Android support, and the main reason I've seen people bring up is that Apple doesn't allow (L)GPL apps on their store. I've seen multiple apps with that license on the App Store, and they've done fine, but maybe I'm just not looking into it enough.

There is an app on the App Store called MultiCraft which is a fork of Minetest and uses the LGPL license (https://github.com/multicraft). It's quite limited in what it can do compared to normal Minetest (it seems to be aiming at the demographic looking for a free Minecraft clone) but it can connect to Minetest servers and might be able to serve as an example that Minetest could survive on the iOS App Store.

If it isn't able to live on the App Store, it could be sideloaded using something like AltStore or Sideloadly, but I can completely understand why nobody would want to put effort into a port that wouldn't even be put onto the official App Store.

I can imagine this has been brought up multiple times, sorry if it's a useless request / issue.

**Comment by Zughy** [comment]
Not planned, see #9154

**Comment by rubenwardy** [comment]
I've already talked many times about the licensing issues. Let's say hypothetically that those issues when away - we still have the problem that none of the core developers use a Mac, which is required to publish an app to iOS.

Another thing is that our Android port is already neglected, despite being much more accessible than iOS
