### ISSUE TITLE
Remove favorite is too small for image

### ISSUE THREAD

**Issue by AspireMint** [minetest/minetest#12646]
##### Minetest version
5.6.0-2cf52642f-win64

##### OS / Hardware
Windows 10

##### Summary
Remove favorite button is too small for image. It does not show image.
![del_fav](https://user-images.githubusercontent.com/37676291/182957185-b116f1c1-d433-48cc-97d0-24290b32bde8.png)

**Comment by AspireMint** [comment]
(change image_button to button and put image above it? ugly solution but may work :))

**Comment by rubenwardy** [comment]
Have you changed any settings, such as gui scaling?

**Comment by AspireMint** [comment]
No. Only language. Opened fresh new unzipped MT, it is same.

**Comment by Zughy** [comment]
Can confirm on Windows 10

**Comment by Zughy** [comment]
On Linux works though (Pop!_OS)

**Comment by sfan5** [comment]
if it's broken on Windows but works on Linux that suspiciously sounds like an escaping issue, and nothing to do with sizes.

**Comment by rubenwardy** [comment]
It's escaped: https://github.com/minetest/minetest/blob/master/builtin/mainmenu/tab_online.lua#L112-L114

I think it's probably a scaling issue which causes `padding=6` to make the icon invisible

**Comment by waxtatect** [comment]
![image](https://user-images.githubusercontent.com/52937829/183663666-5b0ed3b7-166c-4eeb-8a29-8d9ab29ea369.png)
Minetest version referenced in this issue "[Update translation files](https://github.com/minetest/minetest/commit/2cf52642fa89a9497b0200f5a4637a25a82f9c3d)", was before [Mainmenu: Escape server_favorite_delete path](https://github.com/minetest/minetest/commit/8dcbca1068225b6896c3630b390c64d5946d2c73)
i suggest AspireMint to try again with 5.6.0 release

**Comment by AspireMint** [comment]
Yup, in release version it is visible!
Thank you!
