### ISSUE TITLE
Add big red warning to bump_release.sh to check protocol version has been updated

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#12645]
Alternatively enforce it somehow

**Comment by sfan5** [comment]
Also this comment is totally useless and should go:
https://github.com/minetest/minetest/blob/2446ea5533c6d25050c64b2dbf306667fd5277ea/CMakeLists.txt#L19

<hr />

Comparing `git show upstream/stable-5:src/network/networkprotocol.h | grep LATEST` and the file on disk would allow the script to print the two versions or even refuse to continue if they match.

**Comment by sfan5** [comment]
Additional issue: the bump_version.sh currently can't automate patch releases, which led to me forgetting to change the Android-specific version numbers.
