### ISSUE TITLE
debug txt crash info only mode

### ISSUE THREAD

**Issue by tigercoding56** [minetest/minetest#12651]
## Problem

i turned on verbose mode to see why my minetest server was crashing and forgot to turn it off it ended 128 gigabite SD card in 2 weeks and made it unwriteable 
anyway that was my fault  
but debug modes have to much bloat if you only want to see the crash error message (like in singleplayer )
 ## Solutions

i thought it would be usefull to have a debug mode that only writes to debug.txt if the server crashes and writes the same crash message you would see in singleplayer once  your world crashes

## Alternatives

more detailed descriptions of what debug modes do

**Comment by tigercoding56** [comment]
with debug modes im referencing   log levels i just forgot the name

**Comment by sfan5** [comment]
Lua crashes are written as "errors", no need to enable verbose mode.
Log levels are also already documented:
https://github.com/minetest/minetest/blob/ec778508df3fc773367a7b2e2b0db100cc97983f/minetest.conf.example#L2483-L2493

**Comment by tigercoding56** [comment]
thx
