### ISSUE TITLE
Looking at a close wall abnormally cause a FPS drop

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#12660]
### Minetest version
`HEAD` (`5.7-dev`) with shadows enabled.

### Summary
https://irc.minetest.net/minetest-dev/2022-08-06#i_6004862
**Video:** https://www.youtube.com/watch?v=ptekcNolwwE

Broken occlusion culling?

#### Close wall view
![Capture d’écran du 2022-08-07 19-55-30](https://user-images.githubusercontent.com/7883281/183304633-daa7d2b6-42b0-4d9e-9539-012e31326038.png)

#### Far land view (next to the wall)
![Capture d’écran du 2022-08-07 19-55-23](https://user-images.githubusercontent.com/7883281/183304658-1cb4fe3f-d62d-4e12-a691-fd3868515a90.png)

### Steps to reproduce
1. Build a wall (example terrain: seed = `linux` mapgen = `v7`)
2. Compare the FPS between a close look at a wall and far land render. The latter brings +10 FPS on average.

Cc: @x2048 @lhofhansl

**Comment by NathanSalapat** [comment]
No issues for me. Using same seed and close to same location, get a smooth 60fps. Max is capped to 90. Tried with viewrange set to 150 as in your video and 300, my normal value, so no difference. Tried several different times as well, never saw the issue. I do have a decent system so could just be that the issue doesn't show itself for me.
System specs:
Linux Mint 20.2, 64-bit
Intel i7-8700K @ 3.70GHz
64GB ram
Nvidia GeForce GTX 1060

**Comment by sfan5** [comment]
Occlusion culling essentially ignores walls that are a single node deep, this is obviously bad but has been this way forever.
https://github.com/minetest/minetest/blob/4fbcc33ee08e521015529ba4f494fc9cff771ebb/src/map.cpp#L1169-L1172

You should however not get *lower* FPS when moving in front of the wall, this could indeed be a rendering bug.

**Comment by Zughy** [comment]
still happening? Since there have been a few changes in performances and code

**Comment by kilbith** [comment]
Yes, still happening and should have proper labelling.

**Comment by Zughy** [comment]
I can't repro either, latest dev, Pop!_OS

**Comment by Zughy** [comment]
Proof, same seed, same coordinates

https://github.com/minetest/minetest/assets/63455151/207c0c3b-66fc-4b10-b2d4-9a3d83e9f247
