### ISSUE TITLE
"autoscale" feature for world-aligned textures seems to have broken in 5.6.0

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#12672]
##### Minetest version
```
5.6.0, not 5.5.1
```

##### OS / Hardware

Operating system: Linux nail 5.15.55-1-MANJARO #1 SMP PREEMPT Fri Jul 15 09:45:39 UTC 2022 x86_64 GNU/Linux
CPU: i7-10850H

GPU model: nvidia TU117GLM
OpenGL version: 4.6

##### Summary
i've been working on [an update to moreblocks/stairsplus](https://github.com/minetest-mods/moreblocks/pull/191), and noticed that after updating to 5.6.0, all the shaped nodes (which now had world-aligned textures) looked very odd:

5.5.1: ![screenshot_20220808_125609](https://user-images.githubusercontent.com/25628292/183503696-b658c156-b47d-4292-8847-e244a98d6193.png)

5.6.0: ![screenshot_20220808_125710](https://user-images.githubusercontent.com/25628292/183503659-e2b534c0-3822-475e-9895-b3c00438a2ad.png)

##### Steps to reproduce
1. get a 5.6.0 client w/ minetest_game
2. put [this branch of this fork](https://github.com/fluxionary/minetest-moreblocks/tree/bugfixes) somewhere a world can get to it
3. set `world_aligned_mode = enable` and `autoscale_mode = enable` in minetest.conf
4. run in singleplayer/local server, cut some nodes in the saw

**Comment by sfan5** [comment]
Bisect would be helpful if you can.

**Comment by fluxionary** [comment]
> Bisect would be helpful if you can.

thanks for teaching me about this useful feature of git :)

here's the results:

```
051181fa6ee00d8379e8a7dc7442b58342d4352b is the first bad commit
commit 051181fa6ee00d8379e8a7dc7442b58342d4352b
Author: SmallJoker <SmallJoker@users.noreply.github.com>
Date:   Sat Jul 9 22:32:08 2022 +0200

    Enforce limits of settings that could cause buggy behaviour (#12450)
    
    Enforces the setting value bounds that are currently only limited by the GUI (settingtypes.txt).

...
```
