### ISSUE TITLE
Suggested changes to password implementation of logging into a server

### ISSUE THREAD

**Issue by Wolf1098** [minetest/minetest#12687]
## Problem
If when logging into a server for convenience, one might use the default password setting, which can work, but lessens the security that one could have if they used multiple different passwords for the different servers.

## Solutions

Allow saving of the password per server, or ...

## Alternatives

Another implementation is if the the password protected user exists on the server at connection attempt give an interactive login prompt. It would be cool to have both the solution and alternative implemented...

**Comment by Wolf1098** [comment]
if the alternative was implemented it would probably be best to have server side checks of the incoming logins, to rate limit to humanly possible rates of retry

**Comment by Zughy** [comment]
Duplicate of #1566
