### ISSUE TITLE
5.6 changed object glow drastically

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#12686]
##### Minetest version
```
5.6
```

##### Summary
![image](https://user-images.githubusercontent.com/28972859/184019052-ee2a304b-4f3c-4c4d-b7f2-b0738348fd00.png)

##### Steps to reproduce
Look at a glowing dropped item (like a MTG meselamp) with both 5.5.1 and 5.6, see the difference.

**Comment by GreenXenith** [comment]
Can confirm; Colors on entity shown should be pure white and red (glow = -1, `LIGHT_MAX`, or 1000; v5.6) 
![image](https://user-images.githubusercontent.com/24834740/184061448-f7008bb3-71d4-4676-a24e-5cd80336519e.png)

**Comment by sfan5** [comment]
Relevant discussion: https://irc.minetest.net/minetest-dev/2022-08-10#i_6005846

**Comment by Skamiz** [comment]
Also confirming. As far as I can tell an objects glow is basically being ignored completely.
![image](https://user-images.githubusercontent.com/48406239/184661328-179295da-ed09-49ed-9c26-163675db00cb.png)
Each side contains the same items. (Mese lamp and chalk for comparation) On the left sky light is blocked using glass from this mod: https://content.minetest.net/packages/StarNinjas/nextgen_tinted_glass/

**Comment by x2048** [comment]
Should be fixed by 464043b8abdbd936640757604ecb21662592043b, can you verify?

**Comment by sfan5** [comment]
Verified.
