### ISSUE TITLE
[liquid] liquid_move_physics = "nil" disables swimming for liquidtype = "none", but enables it for other types

### ISSUE THREAD

**Issue by Lemente** [minetest/minetest#12683]
##### Minetest version
```
5.5.1 and 5.6
```

##### Summary
if you define the liquidtype as "source" or "flowing" you will be able to swim with `liquid_move_physics = nil`,
but if you use `liquidtype = "none"`, you also need to define `liquid_move_physics = true` to be able to swim

(I have not tested if other parameters affected swimming)

##### Steps to reproduce
here is a mod (tested in void game)
[void_liquid_swim.zip](https://github.com/minetest/minetest/files/9303588/void_liquid_swim.zip)

place the two following nodes in the world : 
/give singleplayer void_liquid:source_can_swim
/give singleplayer void_liquid:none_cannot_swim

edit : I forgot to explicitely define ``liquid_move_physics = nil`` in the mod, but it it the base value
edit 2 : added

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/df1d215f4823b82f704b06eae0179c5e6c6b97af/doc/lua_api.txt#L8124-L8131

**Comment by Zughy** [comment]
Can you please provide a minimal test within devtest and that doesn't require any download (but rather some copy-pasting)? It'd make our life easier

**Comment by Lemente** [comment]
here it is, tested in devtest

```lua
--you can swim in that source node (blue)
minetest.register_node(":void_liquid:source_can_swim", {
	description = ("liquid Source Blue"),
	drawtype = "liquid",
	waving = 3,
	tiles = {"[combine:16x16^[noalpha^[colorize:#229:255"},
	special_tiles = {{name = "[combine:16x16^[noalpha^[colorize:#229:255"},{name = "[combine:16x16^[noalpha^[colorize:#229:255"}},
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = false,
	drowning = 1,
	liquid_range = 1,

--LIQUID TYPE = SOURCE
	liquidtype = "source",
	liquid_move_physics = nil,
--

	liquid_alternative_flowing = "void_liquid:flow",
	liquid_alternative_source = "void_liquid:source_can_swim",
	liquid_renewable = false,
	floodable = false,
	liquid_viscosity = 1
})

--you cannot swim in that "none" node (red)
minetest.register_node(":void_liquid:none_cannot_swim", {
	description = ("liquid Source Red"),
	drawtype = "liquid",
	waving = 3,
	tiles = {"[combine:16x16^[noalpha^[colorize:#922:255"},
	special_tiles = {{name = "[combine:16x16^[noalpha^[colorize:#922:255"},{name = "[combine:16x16^[noalpha^[colorize:#922:255"}},
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = false,
	drowning = 1,
	liquid_range = 1,

--LIQUID TYPE = NONE
	liquidtype = "none",
	liquid_move_physics = nil,
--

	liquid_renewable = false,
	floodable = false,
	liquid_viscosity = 1
})

--you can swim in that flowing node (pink)
minetest.register_node(":void_liquid:flow", {
	description = ("liquid Flow Pink"),
	drawtype = "flowingliquid",
	waving = 3,
	tiles = {"[combine:16x16^[noalpha^[colorize:#959:255"},
	special_tiles = {{name = "[combine:16x16^[noalpha^[colorize:#959:255"},{name = "[combine:16x16^[noalpha^[colorize:#959:255"}},
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = false,
	drowning = 1,
	liquid_range = 3,

--LIQUID TYPE = NONE
	liquidtype = "flowing",
	liquid_move_physics = nil,
--

	liquid_alternative_flowing = "void_liquid:flow",
	liquid_alternative_source = "void_liquid:source_can_swim",
	liquid_renewable = false,
	floodable = false,
	liquid_viscosity = 1
})```

**Comment by Lemente** [comment]
> Works as designed, then?
> 
> https://github.com/minetest/minetest/blob/df1d215f4823b82f704b06eae0179c5e6c6b97af/doc/lua_api.txt#L8124-L8131

well, I guess so!
I didn't knew a parameter could affect another in such a way, sorry

**Comment by sfan5** [comment]
The reason for this behaviour is backwards compatibility: all liquids nodes need to automatically gain liquid physics _and_ we still want the physics part to be individually controllable by mods.
Closing this then.
