### ISSUE TITLE
Update icon for macos to use the new design 

### ISSUE THREAD

**Issue by JDOG787** [minetest/minetest#12696]
## Problem

The current icon for minetest doesn't use the new icon design.

## Solutions

Redesign the icon to use the new design (eg box with rounded corners).

Example:

![image](https://user-images.githubusercontent.com/64325143/184520656-249554b5-7582-43dc-baf0-25fe8a552bf7.png)

**Comment by Zughy** [comment]
What's the current icon on MacOS? Because both on Windows and on Linux it has a transparent background, so I don't see how you can see the rounded corners (I guess because of the external shadow?)

**Comment by JDOG787** [comment]
The current icon has a transparent background. If you added a white background to it (and rounded the corners) it would match the other apps on MacOS. I can send an image of what I mean later.

**Comment by JDOG787** [comment]
![Group 1](https://user-images.githubusercontent.com/64325143/184545385-2f841051-6bcf-482b-a003-f2bedc6f367b.png)

**Comment by JDOG787** [comment]
Here's what I'm thinking
![Group 1 (1)](https://user-images.githubusercontent.com/64325143/184545396-70c1ef6c-edf2-469c-a060-99a834b57a86.png)

**Comment by Zughy** [comment]
Shouldn't be up to Mac devs to put some background to transparent icons rather than ask every software to put one so to fit their aesthetic?

**Comment by SmallJoker** [comment]
Not our bug, I suppose.
