### ISSUE TITLE
Can't type the 'o' key when using colemak on macOS

### ISSUE THREAD

**Issue by ratHippo** [minetest/minetest#12709]
##### Minetest version
`Minetest 5.6.0`

##### OS / Hardware

Operating system: macOS 12.3
CPU: M1

##### Summary
When I use the [colemak keyboard layout](https://colemak.org) and try to type the 'o' key in the online content browser or in the world creation menu, it simply outputs nothing. Note that the 'o' key in colemak is in the same position as a semicolon on a standard keyboard and all other keys are working properly
##### Steps to reproduce
1. Switch keyboard layout to colemak
    * for macOS: 
        * System Preferences > Keyboard > Input Sources > + > English > Colemak
        * Make sure that 'Show Input in Menu Bar' is checked
        * Navigate to your top menu bar
        * Switch layout to colemak
2. Open Minetest
3. Try to type 'o' while naming a world or searching for content

**Comment by Zughy** [comment]
I guess it's the same as #12507
