### ISSUE TITLE
Impossible "Invalid block data" situation in a map

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#1270]
On a hunch, I checked into an error I kept having with what I thought was a /teleport bug.  Turns out it's something else.  Two players somehow found themselves up at 0,30999,0 , probably by an admin having teleported one of them to that location, and then teleporting the second player up to meet the first one.

For reasons beyond my understanding, their presence in this location of the map has caused my server to crash and throw this error:
```
01:21:23: ERROR[EmergeThread1]: Invalid block data in database (-1,1937,0) (SerializationError): unsupported NameIdMapping version
terminate called after throwing an instance of 'ServerError'
  what():  Invalid data in MapBlock (-1,1937,0)
----
"Invalid block data in database"
See debug.txt.
You can ignore this using [ignore_world_load_errors = true].
```
Setting the above ignore flag to true stops the crash but then floods my log with similar errors (with additional messages that the errors have been ignored) when I teleport up to the location in question.  The thing is, there's nothing whatsoever up at those coordinates except air (I don't run any terrain mods on the affected server).

My client also stopped being able to send commands to the server e.g. /status or /teleport after I'd gone up to the location in question, or at least I got no responses to the commands. Incoming chat from other clients had gone completely dead as well.  In fact, the client behaved as if no communication were talking place at all (no player movement, I couldn't fall when I turned fly off because the map in all its airy glory :-) wouldn't "generate", etc).

At least one of the two users who ended up in the "suspect" area lost his ability to chat (as I did).  That second user who ended up there may have also lost communication, but I can't be 100% sure.  One of my admins who was trying to sort out the issue also lost the ability to communicate once she went up into the area, as well as having her client crash at least twice in the process (rather than simply ceasing to communicate).

When I first brought this up, I was advised to find "if (blockpos_over_limit(p)) continue;" in map.cpp and comment it out as a test. This seems to be the following few lines of code beginning at line 2539:
```c++
if(blockpos_over_limit(p))
    {
        infostream<<__FUNCTION_NAME<<": Block position over limit"<<std::endl;
        throw InvalidPositionException("generateBlock(): pos. over limit");
    }
```
However, that's not the error message that was printed in the log.  Nevertheless, commenting that code out stopped the crashes (or so it seemed), but I didn't leave that hack in place for long, as I don't know what the ultimate effect of it would be, and I didn't figure out by that point to try teleporting to the above 0,30999,0 coordinates to have a look around.  I can't be sure if this ultimately had any effect on the source of the crash.

For now, the server is operating with ignore-load-errors enabled to avoid it crashing.

**Comment by sapier** [comment]
Anything new on this one?
If not I'd close it in about a week and request to create a new issue if it happens again?
