### ISSUE TITLE
Shadowmapping draws backfaces

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#12712]
##### Minetest version

```
Minetest 5.7.0-dev-2d10fa786 (Linux)
Using Irrlicht 1.9.0mt7
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="some path"
```

##### OS / Hardware
Doesn't matter.

##### Summary

Shadowmapping draws the faces of nodes that are not seen by the sun. I suppose this is a bug?
(Just close this issue if it's intended behaviour.)

##### Steps to reproduce
* Enable shadows.
* Place grass or leaves.
* There are no shadows inside the nodes. And the stripes of the glass are only visible in the shadow:
![screenshot_20220819_201906](https://user-images.githubusercontent.com/7613443/185683076-1787a793-ac82-4d90-bc05-8a8c135c41e9.png)

**Comment by Zughy** [comment]
@x2048 is this intended or a bug?

**Comment by x2048** [comment]
This is the current design to avoid shadow acne on nodes

**Comment by x2048** [comment]
Changing to front faces requires recalibration of bias and filtering, and the problem may still stay on some cases, as can be seen on entities.

**Comment by Desour** [comment]
Ah, I see. Thanks!
Closing then.
