### ISSUE TITLE
Clickable Chat Links: Link ends before comma if present

### ISSUE THREAD

**Issue by Maverick2797** [minetest/minetest#12716]
##### Minetest version
5.6.0 Release
##### OS / Hardware
Operating system: Windows 10
CPU: Ryzen 5 5600G

GPU model: RTX 3060
OpenGL version: 4.6.0

##### Summary
The clickable part of url's posted in chat ends just before the first comma if a comma is present.

##### Steps to reproduce

1.  Send in chat (either as a general message or DM): `https://google.com/1,2,3` (example)
2. Click the hyperlink in chat. Resulting web page will only open to `https://google.com/1` instead of `https://google.com/1,2,3`

**Comment by appgurueu** [comment]
Can confirm. `,` is allowed in URL filenames. This is a bug in the RegEx used.
