### ISSUE TITLE
liquidtype = "none" causes north/east/up faces in contact with transparent nodes to not be drawn 

### ISSUE THREAD

**Issue by Lemente** [minetest/minetest#12718]
##### Minetest version
```
5.6
```

##### OS / Hardware
Operating system: Windows 10

##### Summary

liquidtype = "none" causes north/east/up faces in contact with transparent nodes to not be drawn 

##### Steps to reproduce

(red) node with liquidtype = "none", display incorrectly
![minetest_b7Ythad92q](https://user-images.githubusercontent.com/27686967/185807727-3c25f506-05fc-4242-a08f-29c96ea2c549.png)

(blue) node with liquidtype = "source", display correctly
![minetest_TjTIUrF9tD](https://user-images.githubusercontent.com/27686967/185807760-3f9d7ea2-e3c7-459d-85aa-1b525fd04a07.png)

![minetest_tY7ngoJ4bY](https://user-images.githubusercontent.com/27686967/185807737-ede52535-c870-4c84-89d8-b92523ecd787.png)

```lua
--  (blue) node with liquidtype = "source", display correctly
minetest.register_node(":liquid:type_source", {
	description = ("liquid Source Blue"),
	drawtype = "liquid",
	waving = 3,
	tiles = {"[combine:16x16^[noalpha^[colorize:#229:255"},
	special_tiles = {{name = "[combine:16x16^[noalpha^[colorize:#229:255"},{name = "[combine:16x16^[noalpha^[colorize:#229:255"}},
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = true,
	buildable_to = true,
	drowning = 1,
	liquid_range = 1,
	--LIQUID TYPE = SOURCE
	liquidtype = "source",
	liquid_alternative_flowing = "liquid:flow",
	liquid_alternative_source = "liquid:type_source",
	--
	liquid_renewable = false,
	floodable = false
})

-- (red) node with liquidtype = "none", display incorrectly
minetest.register_node(":liquid:liquidtype_none", {
	description = ("liquid None Red"),
	drawtype = "liquid",
	waving = 3,
	tiles = {"[combine:16x16^[noalpha^[colorize:#922:255"},
	special_tiles = {{name = "[combine:16x16^[noalpha^[colorize:#922:255"},{name = "[combine:16x16^[noalpha^[colorize:#922:255"}},
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = true,
	buildable_to = true,
	drowning = 1,
	liquid_range = 1,
	--LIQUID TYPE = NONE
	liquidtype = "none",
	--
	liquid_renewable = false,
	floodable = false
})

-- (pink) flowing node provided to avoid error
minetest.register_node(":liquid:flow", {
	description = ("liquid Flow Pink"),
	drawtype = "flowingliquid",
	waving = 3,
	tiles = {"[combine:16x16^[noalpha^[colorize:#959:255"},
	special_tiles = {{name = "[combine:16x16^[noalpha^[colorize:#959:255"},{name = "[combine:16x16^[noalpha^[colorize:#959:255"}},
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = true,
	buildable_to = true,
	liquid_range = 3,
	liquidtype = "flowing",
	liquid_alternative_flowing = "liquid:flow",
	liquid_alternative_source = "liquid:type_source",
})
```

**Comment by Desour** [comment]
Looks like a documentation issue. I doubt it makes sense to use the liquid drawtype with `liquidtype="none"`.
Plus one could add a warning in `core.register_node`.

**Comment by sfan5** [comment]
I thought the whole point of splitting them was that it doesn't have to _be_ a liquid to _look_ like one.

**Comment by Desour** [comment]
Oh, of course, you're right. #10737

**Comment by Wuzzy2** [comment]
Oh, this is not good. After the liquid decoupling, the liquidtype should no longer affect the rendering *at all* but be purely about declarating the flow behavior, not rendering.
For rendering, the drawtype and other params should be responsible.

Seems like I overlooked something, or it's a new bug, no idea. I'll look into it.
