### ISSUE TITLE
Why -ffinite-math-only ?

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#12722]
Minetest is built with `-ffinite-math-only`:
https://github.com/minetest/minetest/blob/2d10fa786792a27adb4097abe8c92f36cf47e6ce/src/CMakeLists.txt#L744-L747
(Since #9682. Before that, it was `-ffast-math`.)

But it is not true that we are not dealing with inf or nan. Lua mods can, for example, always pass nan or inf as argument.

This optimisation can for example change `std::isinf(num)` to a constant `false`, which makes checking for inf, nan and the like impossible.

I'm not aware of practical bugs caused by this.
But I once got problems with it in a PR when I've tried to add a setting that allows `inf` values ([code](https://github.com/Desour/minetest/blob/102e78f9e891f30ee3d37722baed93c0bcfd52b7/src/util/time_parsing.cpp#L43)).

**Comment by sfan5** [comment]
I'm aware but never got around to removing it: https://irc.minetest.net/minetest-dev/2021-07-18#i_5848637
