### ISSUE TITLE
Minetest refuse to launch on my M1-Based MacBook Air

### ISSUE THREAD

**Issue by Android-Piepaint** [minetest/minetest#12726]
##### Minetest version

```
5.6.0
```

##### OS / Hardware

Operating system: macOS 13.0 Beta 5
CPU: 8x Apple M1 @3.2GHz

GPU model: Apple Bulit-in GPU

https://user-images.githubusercontent.com/73344795/186896729-a3d44a66-ea65-40ff-a502-9513943670d1.mov

OpenGL version:2.1

##### Summary

The game refuse to launch.
##### Steps to reproduce

1. Open terminal
2. enter "brew install minetest"
3. Or download a release from GitHub.
4. Both version are refuse to launch.

**Comment by oong819** [comment]
do you have debug log?
