### ISSUE TITLE
Tradução para portugues

### ISSUE THREAD

**Issue by Theuzinho618826** [minetest/minetest#12736]
Oi,eu queria que tivesse tradução para português porque eu não sei nada de inglês. Seria legal traduzir porque vai ficar difícil jogar o jogo e ter que ficar traduzindo o tempo todo. Obrigado pela atenção;)

**Comment by rubenwardy** [comment]
There is already a Portuguese translation. Minetest should detect your language automatically, if not you can set it by going to Settings > All Settings and searching for Language. `pt` is Portuguese

**Comment by Theuzinho618826** [comment]
Eu to tentando mudar a tradução mais não consigo achar a configurações.

Enviado via Proton Mail para dispositivos móveis

-------- Mensagem Original --------
Em 31 de ago. de 2022 20:13, rubenwardy escreveu:

**Comment by SwissalpS** [comment]
em minetest.conf, procure por "language"
```language = pt```

ou procure nas configurações avançadas do cliente minetest por "language"

**Comment by Theuzinho618826** [comment]
Eu conseguir configura. Obrigado pela ajuda:)

Enviado via Proton Mail para dispositivos móveis

-------- Mensagem Original --------
Em 1 de set. de 2022 14:58, Luke aka SwissalpS escreveu:
