### ISSUE TITLE
"debug_log_level" in minetest.conf does not work.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#1273]
The latest build I tested was 6f511b1d05, I'm not sure since when this happen because I begun attempting to set that for about a week.
In minetest.conf there's the following.
```
# Level of logging to be written to debug.txt.
# 0 = none, 1 = errors and debug, 2 = action, 3 = info, 4 = verbose
# debug_log_level = 2
```

Problem is, no matter what I set there it will always log using default option, (2).
I set it to 1 and then to 0, nothing changed, it still showing timeouts and player actions.

**Comment by 1Nick1Name** [comment]
Please reopen.
Setting logging levels still does not work.

**Comment by Megaf** [comment]
We need ***separate config options to define the level of verbosity*** of log written to the console and written to the debug file.
Also, **debug should be a different file**, having then *debug.txt* and *server.log*.

**Comment by PilzAdam** [comment]
@Megaf The command line parameters control the log level to console independently of `debug_log_level`. Whats the difference between debug.txt and server.log except the name?

**Comment by 1Nick1Name** [comment]
The difference is that *debug.txt* will not contain the same text text that is logged to the console when using *debug_log_level* of 3 or 4.

**Comment by 1Nick1Name** [comment]
also *debug_log_level* can be read by mods.

**Comment by 1Nick1Name** [comment]
also the *minetest.log* levels *info* and  *verbose* would loose their usefullness.

**Comment by Megaf** [comment]
Maybe the server.log would show player actions and chat and debug mod information and debug info?

**Comment by ShadowNinja** [comment]
This isn't broken.  You could suggest a different way of handling the log levels in a seperate issue though.
