### ISSUE TITLE
Dont render things player dont see

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12733]
## Problem

The fence behind a wall still rendered but player cant see the fence ( see pictures)

while in some spot the fence dissappear when im not see it
![Screenshot_20220831-140344](https://user-images.githubusercontent.com/76146430/187615842-48fa25cd-de3b-4b25-8cd8-89565a13d5a2.png)
![Screenshot_20220831-140331](https://user-images.githubusercontent.com/76146430/187615927-7e4e1614-2eea-4eaf-b071-9d6ee7ccd7f9.png)

## Solutions

Dont render it, probally shoot some ray to test if player can see it but i think this wat even waste more power

## Alternatives

idk

## Additional context

i dont really know how wireframe work so just close this issue if its wrong

**Comment by Desour** [comment]
What you're referring to is occlusion culling (cull the occluded geometry). Minetest already culls occluded mapblocks, just not perfectly.
