### ISSUE TITLE
Floating Decoration...

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#1274]
Once a chunk has been generated in v7 maps it seems that the ridges feature cuts out part of the landscape and leaves behind floating decor like grass and plants...  Would it be possible to look into this and also add a way to DISABLE ridges...

Example: http://i61.tinypic.com/k3ooxs.jpg

**Comment by paramat** [comment]
I'm getting this in recent mgv7, will look into it.

**Comment by paramat** [comment]
Decorations are only placed on solid ground, so this is probably due to how large caves in mgv7 are generated out into previously generated neighbouring chunks and can therefore remove ground from under a decoration. Not easily fixable but should be rare.
