### ISSUE TITLE
Cannot Single-Hit Dig Nodes in Creative

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#12750]
##### Minetest version

```
5.6.0
```

##### OS / Hardware

```
Operating system: Ubuntu/Lubuntu 22.04.1
CPU: x86_64
```

##### Summary

I recently installed Minetest 5.6.0 & am running a minimal game with only the mods `default`, `creative`, `sfinv`, `flowers`, & `player_api` installed. "Creative Mode" is enabled. The creative inventory tabs are available. But I cannot break nodes with my hand (e.g. cannot single-hit any node to break it). If I start a game using `minetest_game` it does work. Is there another mod I need to be running?

**Edit:** This is probably not related to the core engine, but rather a modding issue.

**Comment by AntumDeluge** [comment]
I figured out why, & it is a modding issue. It occurred because I had removed `default` as a dependency from `creative`. So there is something in `default` that must be loaded first to enable the behavior.

**Comment by rollerozxa** [comment]
> So there is something in default that must be loaded first to enable the behavior.

Indeed. `default` is an (optional) dependency of `creative` because it needs to override the default survival hand by registering the creative hand last. So when it is not a dependency default gets loaded after creative and the creative hand gets overridden by the survival one.

**Comment by AntumDeluge** [comment]
@rollerozxa Thanks. Having a similar discussion on the Minetest Discord server.

I believe there is a core method that can be used to set the hand after all mods are loaded (`minetest.after`?). I believe this could be used to make `creative` independent of `default`.
