### ISSUE TITLE
Add dynamic media without using disk

### ISSUE THREAD

**Issue by GoodClover** [minetest/minetest#12755]
## Problem

When generating dynamic media at runtime, you have to go through an extra hoop of writing it to disk to then be read back again. This has a minor performance impact, requires an insecure environment & is just annoying to manage.

This does not add anything impossible with the current API,
This is mainly a QOL feature for mod devs. Along with #11640 this would make mods that generate temporary textures, or textures that update frequently (screens, maps, etc) miles easier.

## Solutions

Add a `data` property to `dynamic_add_media`, to hold a string of raw data.
If this property is set, use this rather than reading from disk.
A `filename` property is needed, so the server and client have a common name for the media.

## Alternatives

Using the `[png` texture modifier you don't have to write to disk.
For textures that change this would eat up RAM without #11531.
This is not texturepack-able.

Or the current pokery we have to do: ![image](https://user-images.githubusercontent.com/27222523/189523767-76be381d-2bec-4cc3-8680-139ba265a3d6.png)

**Comment by sfan5** [comment]
You don't need an insecure environment for this at all, fyi.
