### ISSUE TITLE
Some problems and suggestions for Android build

### ISSUE THREAD

**Issue by Anonymous1231-dev** [minetest/minetest#12754]
Unfortunately, Minetest on Android still stuck at 5.1.1 . I managed to get Minetest 5.6.0 on Android Minetest just CRASH when a new world is loaded. And according to @rubenwardy , it is the irrlichtMt problem. So I have some suggestions for devs.

- Fix irrlichtMt so it's compatible with Android
- Adding a crosshair in Android build #7865 (It's made my life easier) 
- made Minetest more stable (It constantly crash in Mt5.5.1)

**Comment by rollerozxa** [comment]
The issues with IrrlichtMt has already been fixed and will be included with 5.6.1, but the crosshair will have to wait until 5.7.0. 

And "make minetest more stable" is way too vague. I've personally only experienced OOM issues with large games on Android (no fix other than change your taste in games). Report any crashes as a separate issues with a stack trace included from `logcat` and reproduction steps.
