### ISSUE TITLE
Text not loading in main menu

### ISSUE THREAD

**Issue by LittleMC** [minetest/minetest#12756]
##### Minetest version

```
5.1.1

```

##### OS / Hardware

Operating system: Kubuntu 20.04.5 LTS x64
CPU: Intel Core i7 q840 1.8 ghz

GPU model: NVIDIA NVS  3100m
OpenGL version: 3.3

##### Summary

The text not loading in main menu

##### Steps to reproduce

I installed minetest from discover and when i started it the text not loaded

**Comment by sfan5** [comment]
5.1.1 is 2 years old, we don't support anything but the latest version.
Please visit the [website](https://www.minetest.net/downloads/) to find a newer version to install.

**Comment by LittleMC** [comment]
it working now thanks
