### ISSUE TITLE
asymmetric object visibility distance seems repsective to where the model is facing, not where the camera is facing

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#12770]
##### Minetest version
```
5.6.0
```

##### OS / Hardware

Operating system: linux

##### Summary
i can see more distant objects when looking forward, than looking "behind" the player using the 3rd person view. see attached screenshots:

![screenshot_20220914_123828](https://user-images.githubusercontent.com/25628292/190248629-6a40d75c-07c6-4218-9691-ef7546fd994c.png)
![screenshot_20220914_123846](https://user-images.githubusercontent.com/25628292/190248643-62d6146b-8a64-45e6-822c-46c7f3ababf2.png)

##### Steps to reproduce
i used https://github.com/fluxionary/minetest-test_object to create the field of objects

**Comment by IrrlichtMt4** [comment]
Confirmed and worlds don't generate when you look back unless you face the unloaded chunk with the character also facing it.

**Comment by sfan5** [comment]
More blocks are activated in the players view direction:
https://github.com/minetest/minetest/blob/f3f3b752f2b13e1edb6d495a161fe49e960453c9/src/serverenvironment.cpp#L343-L355

Who says this is a bug?
