### ISSUE TITLE
Some questions about modding

### ISSUE THREAD

**Issue by LuciusofLegend** [minetest/minetest#12783]
Hi, I found Minetest a month or so ago, and I've started making my own game called [Gateway](https://github.com/LuciusofLegend/Gateway).  That project has left me with these questions:

- What are the best resources for learning about Minetest modding?  I've found the [API Documentation](https://minetest.gitlab.io/minetest/) and the [Modding Book](https://minetest.org/modbook/) so far, but are there other, better resources for a beginner?
- What level of programming skill does Minetest cater to?  As a relatively inexperienced (but not completely new) coder, should I expect modding to be accessible, and if not, are there specific skills I should learn first?

Also, let me know if the issues page is not the place for this, I can move it to the forum if that's more appropriate.

**Comment by rubenwardy** [comment]
> Modding Book so far, but are there other, better resources for a beginner?

The official modding book can be found at https://rubenwardy.com/minetest_modding_book/
The link you posted is an outdated copy

**Comment by LuciusofLegend** [comment]
Thanks!  That will be extremely helpful.  Also, thanks for making such a nice modding guide.

**Comment by SwissalpS** [comment]
https://www.lua.org/ will help you get started with Lua in general. There is command documentation and also other guides and techniques explained there.

**Comment by LuciusofLegend** [comment]
Thanks for the tip.  I've got a [syntax reference](https://github.com/pohka/Lua-Beginners-Guide) already, and that's all I should need.  My skill level really depends on how you look at it.  I've done a lot of little projects (simple games in Unity, Minecraft datapacks and a bit of Java modding), so I actually don't know my own programming level XD.

**Comment by LuciusofLegend** [comment]
My questions have been answered well, so it's closing time.
