### ISSUE TITLE
Crafting recipe documentation is insufficient

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#12796]
#### Summary

Most of documentation of crafting recipes is just by example, and doesn't explain everything, i.e.:
* Do you always have to give a 3x3 grid in shapeless crafting? What other sizes are ok, and what do they do different?
* What does the multi-group thing (`"group:dye,basecolor_red"`) do?

#### Solution

Add better documentation.

#### Additional resources

Here is the documentation that I've found:

https://github.com/minetest/minetest/blob/1317cd12d74dba4ff765d6e18b0b30cdf42002a3/doc/lua_api.txt#L1828-L1848

https://github.com/minetest/minetest/blob/1317cd12d74dba4ff765d6e18b0b30cdf42002a3/doc/lua_api.txt#L8474-L8547

**Comment by Wuzzy2** [comment]
Ah, good find! I agree, documentation should not only be a list of examples. I am also annoyed by such documentation since it conveniently forgets a lot of edge cases.

I think I'm going to look at it. Please list other unresolved questions and confusions.

**Comment by Wuzzy2** [comment]
PR available: #12806
