### ISSUE TITLE
High memory usage results in crashes in latest git

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#128]
Hard to explain really, but for no apparent reason, the latest git has become very crashy, at least on Linux - I can go anywhere from 10-20 seconds to a minute or two.  Simply walking around or flying is sufficient to trigger this bug.  On the controlling terminal, all I get is:

"terminate called after throwing an instance of 'St9bad_alloc'
what():  std::bad_alloc
Aborted"

Link to debug.txt from the last run only (deleted before running this test):

http://digitalaudioconcepts.com/vanessa/hobbies/minetest/minetest-debug-20120618.txt

Link to strace output of this same run:

http://digitalaudioconcepts.com/vanessa/hobbies/minetest/minetest-strace-20120618.txt

(note:  it's big - 32.5 MB)

**Comment by tenplus1** [comment]
The same bug is happening on Xanadu server regularly and we are using 16x default textures and it hardly breaks to 500mb limit for memory use out of 4gb...  from 0.4.12 upwards this std:bad_alloc error always crops up for reasons unknown...

 2015-04-30 12:12:35: ACTION[ServerThread]: player G1127 crafts default:stick 4
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

**Comment by celeron55** [comment]
@tenplus1: This issue is about client-side crashes. Yours is server-side.

Also this issue is 3 years old. Open a new one instead of commenting here.
