### ISSUE TITLE
Translated Minetest update message puts backslash before commas

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12803]
##### Minetest version
```
5.6.0
```

##### Summary

If you launch 5.6.0 in German, the update message for the new version 5.6.1 contains backslashes where they don't belong. The message looks like this:

> Besuchen Sie https://www.minetest.net/download/\, um herauszufinden\\, wie man die neueste Version erhält und auf dem neuesten Stand mit Features und Fehlerbehebungen bleibt.

The backslashes are before the 2 commas. Both backslashes are wrong. They do not exist in the translation file.

##### My guess

Probably bad formspec escaping.

Note the English text has no commas which explains why it does not manifest in English.

##### Steps to reproduce

* Start 5.6.0 in German

**Comment by appgurueu** [comment]
> `fgettext`: same as fgettext_ne(), but calls core.formspec_escape before returning result
\- from https://github.com/minetest/minetest/blob/master/doc/menu_lua_api.txt

The current implementation calls `core.formspec_escape` on the results of `fgettext` (both `title` and `message`). This means they are escaped twice. The backslashes used to escape the commas are thus escaped a second time. The commas are escaped as well. A properly escaped `\,` becomes `\\\,` - a backslash and a comma. Fix is trivial.
