### ISSUE TITLE
Incorrect API spec or bad (sub)string match for velocity and acceleration in minetest.add_particle() call

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#1280]
For the non-deprecated version of the add_particle call in the Lua API, it says to use "velocity = " and "acceleration = " among the other values in the particle specification:

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3293

However, those don't work, because the code checks for "vel" and "acc":

https://github.com/minetest/minetest/blob/b5acec0a3c5701c53854ff7afdf4008863e6e8df/src/script/lua_api/l_particles.cpp#L67

Changing these in my mod's add_particle() call to just "vel" and "acc" makes things work as otherwise intended.

Was some call that does just a substring match actually what was wanted here, or is strcmp() intentional?

**Comment by est31** [comment]
dd2e08e11764e045f4eb7a25475a8ecaa77b58de
