### ISSUE TITLE
Devtest chest of everything needs a search field

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#12825]
## Problem

Finding the item I want in the devtest chest of everything is annoying and takes too much time.

## Solutions

Add a search field, like in mtg creative.

## Alternatives

Manually group items by their functionality.

## Additional context

No.

**Comment by Montandalar** [comment]
Wuzzy suggested re-using/porting the code from his Get Item mod - [forum link](https://forum.minetest.net/viewtopic.php?f=9&t=28889&p=418165#p418165)

**Comment by Wuzzy2** [comment]
#13064 will fix this.
