### ISSUE TITLE
Shaders won't compile on OpenGL ES 2.0+ after #12791

### ISSUE THREAD

**Issue by x2048** [minetest/minetest#12824]
##### Minetest version

```
5.7.0-dev-debug-5e7ea0664
```

##### OS / Hardware
Operating system: Android
CPU: Qualcomm

GPU model: Adreno 618
OpenGL version: OpenGL ES 3.2

##### Summary

Shaders won't compile after #12791.

##### Steps to reproduce

1. Compile and run Minetest on Android.
2. Start any game.
3. Whether `enable_bloom` is true or false, shaders will not compile, and the game is not playable.

**Comment by x2048** [comment]
Similar problem reported for Mac OS: https://github.com/minetest/minetest/pull/12791#issuecomment-1263520163

**Comment by x2048** [comment]
Proposed patch (@srifqi)
[second-stage-fix-opengles2.diff.txt](https://github.com/minetest/minetest/files/9687004/second-stage-fix-opengles2.diff.txt)

**Comment by superfloh247** [comment]
patch fixes the issue

**Comment by superfloh247** [comment]
patchfile is corrupted, applying it manually fixes the issue
