### ISSUE TITLE
Translation not available on official macOS build

### ISSUE THREAD

**Issue by cweiske** [minetest/minetest#12823]
##### Minetest version
```
Minetest 5.6.1 (OSX)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
```

##### OS / Hardware
Operating system: MacOSX 10.14.6
CPU: 2,8 GHz Intel Core i7

##### Summary
MacOSX is configured to use the German language (de), and when starting minetest, the game is in english.
Manually setting the language in the settings (Graphics and Audio > User Interfaces > Language) to "de" does not make a difference.

The file `/Applications/minetest.app/Contents/Resources/builtin/locale/__builtin.de.tr` does exist.

Minetest was installed with the official `minetest-5.6.1-osx.zip` file.

The previous version 5.5 was compiled manually on this computer, and the German translation worked there.

The log says:
> 2022-09-30 08:45:59: INFO[Main]: Message locale is now set to: de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

##### Steps to reproduce
1. Set MacOSX locale to German (de)
2. Start minetest
3. GUI labels should be in German

[minetest-log.txt](https://github.com/minetest/minetest/files/9681474/minetest-log.txt)

**Comment by sfan5** [comment]
The official build was simply built without i18n support so this is not so much a "bug" as a suggestion.
I agree it should be enabled though.

**Comment by rollerozxa** [comment]
Translations work on macOS now when the engine is installed into the directory structure of an app bundle, so official builds should come with translation support enabled now.

![image](https://github.com/minetest/minetest/assets/60856959/b32ca5ff-67e9-4206-9baa-af6204f18bfe)

**Comment by sfence** [comment]
Looks to be fixed.
Translation also works with 5.9.0 on my side.
