### ISSUE TITLE
Falling node with `float` group does not fall if liquid is gone

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12839]
##### Minetest version
```
5.6.1
```

##### Summary
If you place a node with the `falling_node=1` and `float=1` groups above a liquid node (`liquidtype ~= "none"`), the node should not fall into the liquid. This is fine.
However, if this liquid drains out and becomes air, the node doesn't fall.

##### Steps to reproduce

* Go into DevTest and create a flat world
* Place a Water Source anywhere and make sure it flows
* Give yourself `testnodes:falling_float` and place it above the flowing water
* Remove the water source and wait for the water to drain out below the test node

Expected: As soon the (flowing) water has drained out, the test node should fall.
Actual result: This does not happen.

**Comment by TurkeyMcMac** [comment]
This could be fixed by adding checks in the liquid update code or with an ABM. The ABM would probably be more performant, but I'm not sure.

**Comment by TurkeyMcMac** [comment]
I suppose the ABM would break some existing behavior though.
