### ISSUE TITLE
Ability to change mod settings on world mod selection window

### ISSUE THREAD

**Issue by FreeLikeGNU** [minetest/minetest#12859]
## Problem

It would be convenient to set the mod configurations on a per world basis and change them on the mod selection screen without having to sift through unused mods that are buried in the settings => all settings => mods.
We have per-world mods, so why not per-world settings for those mods?

## Solutions

Allow right click on mod and context menu to change config, use defaults, etc for that mod or a button to change a selected mods config in the world mods selection window please and thank you.

**Comment by rubenwardy** [comment]
I think this is a duplicate of https://github.com/minetest/minetest/issues/6966

With that feature, "Select Mods" would be renamed to Configure, and would have a tab for settings

**Comment by rubenwardy** [comment]
duplicate of #6966
