### ISSUE TITLE
Sprite ents invisible in high artificial light when shaders disabled

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#12853]
##### Minetest version

```
Minetest 5.7.0-dev-b3503e785 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware

Operating system: `Debian GNU/Linux 11 (bullseye) x86_64`
CPU: `Intel i5-3320M (4) @ 3.300GHz`

GPU model: `Intel 3rd Gen Core processor Graphics Controller`
OpenGL version: `[OpenGL 3.0]`

##### Summary

When shaders are disabled, entities using the `sprite` or `upright_sprite` visual type become invisible when they are in artificial light > ~10

##### Steps to reproduce

1. Register an entity with a `sprite` or `upright_sprite` visual.
2. Reduce the ambient light by either playing NodeCore (base sky light is ~10) or use MTG and set time to twilight/night.
3. Place an entity at this light level.
4. Note that it is visible whether shaders are enabled or disabled.
5. Place a light source nearby, or change the time of day to full daylight, so that the entity is at full brightness.
6. When shaders are enabled, it renders normally; when shaders are off, it disappears.
7. You can see the effect more dramatically in NodeCore if you /grantme all and /nckfa to get the "admin tool" that emits maximum brightness near the player; if you back away so the entity is only visible in ambient skylight, it's visible, but if you approach, it disappears as your light halo touches it.

I tried a few settings, like the filtering and smooth lighting settings, but it seems like Enable Shaders is the only one that affects this.

N.B. the ability to disable shaders and still have the game function correctly is still valuable for some setups, especially older machines, or automated streaming setups without GPU acceleration.  Enabling shaders on these systems can cut the fps, which might already be fairly low, in half.

**Comment by Zughy** [comment]
Cc @x2048

**Comment by x2048** [comment]
Confirmed with artificial light in devtest. Ambient light works as expected.

**Comment by Warr1024** [comment]
Good point, I was probably using "ambient" incorrectly; title adjusted.

**Comment by Wuzzy2** [comment]
Also affects the `cube` visual (see #12944).
