### ISSUE TITLE
Held items jumpscare on world startup

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#12852]
##### Minetest version
```
1317cd1 (post preprocessing)
```

##### OS / Hardware
Operating system: Arch Linux
CPU: AMD Phenom II X4 955

GPU model: AMD Radeon RX 560
OpenGL version: 4.6

##### Summary
Ever since the postprocessing pipeline was merged, usually when starting up a world your held items will fill the entire screen for a split second, similar to how it acts when an item in the hotbar goes off-screen if the window size is too small.

##### Steps to reproduce
Launch into a world, preferrably one where you have some items in your hotbar, and your hotbar items will fill the entire screen for a split second. Boo!

![image](https://user-images.githubusercontent.com/60856959/195434382-8cc9c622-3992-47f9-adde-5c7654e4a110.png)

**Comment by HexBugOrion** [comment]
minetest jumpscare (very scary)

**Comment by Desour** [comment]
Not sure if this is related, but I get a similar jumpscare when I decrease the window height fast enough.

**Comment by rollerozxa** [comment]
> Not sure if this is related, but I get a similar jumpscare when I decrease the window height fast enough.

Yeah it's slightly related, it does the same if you resize the window very small. Fixing it altogether would be nice but this issue in particular is that it has begun doing this on start-up after the postprocessing merge.
