### ISSUE TITLE
Add Android build to workflow

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12860]
Add Android build to workflow

Main

User on Android like me cant build Minetest using Gradle, cmake, Android Studio and terminal

As i see in Actions tab, the workflow in master branch dont have Android build

Root of the story

my device get hot when playing Minetest and make my finger sweat that act like water on the touch screen, made me die on a server

and i see the optimize lighting calculations commit, i thought that will help my device dont get hot

Issue type: Not a Feature Suggestion

**Comment by rollerozxa** [comment]
Can reproduce, playing Minetest on my phone does indeed make my hands sweaty. 

Anyways there is already an Android build workflow, and you can download the built APK files, but they will need to be signed before it can be used (there's ways to sign APK files on-device, I use some APK editor app that can also sign unsigned ones)

**Comment by oong819** [comment]
> Can reproduce, playing Minetest on my phone does indeed make my hands sweaty.
> 
> Anyways there is already an Android build workflow, and you can download the built APK files, but they will need to be signed before it can be used (there's ways to sign APK files on-device, I use some APK editor app that can also sign unsigned ones)

Thanks i did not know that!

i tried it and i know why the need a lot of testing before release now

BLANK SKY MENU
