### ISSUE TITLE
Allow mods to temporarily change key-bindings while inside formspecs

### ISSUE THREAD

**Issue by herbert-west2** [minetest/minetest#12878]
A place where this would be useful, for example, is in the MineClone2 game, where in order to accurately represent the behavior of MC the shift key should craft an entire stack when held down in the crafting area.

**Comment by SmallJoker** [comment]
Duplicate of #11392 and #12488

**Comment by herbert-west2** [comment]
My apologies, I saw those but they were very hard to read so I wasn't sure what they were saying
