### ISSUE TITLE
Auto jump does not work anymore

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#12872]
##### Minetest version

Latest from master

Likely culprit: #12626

Just enable auto jump in advanced options and notice how the character does not jump.

**Comment by fluxionary** [comment]
not trying to claim this isn't an issue, but what happens if you set `stepheight = 1.1` or something?

**Comment by fluxionary** [comment]
at what "step-height" does "auto-jump" no longer work?

**Comment by lhofhansl** [comment]
Nope was something I did.

Never mind me. You did not see this issue... This is not the issue you are looking.
