### ISSUE TITLE
NumPad doesn't work in chat console (Linux)

### ISSUE THREAD

**Issue by AspireMint** [minetest/minetest#12870]
##### Minetest version
Minetest 5.6.1

##### OS / Hardware
OS:
Ubuntu 22.04.1 (64-bit)

OpenGL version:
OpenGL 4.6.0

##### Summary
NumPad doesn't work in chat console, but i can use 2,4,6,8 to select slots (HUD).
NumPad in main menu works - i can type port number.

**Comment by fluxionary** [comment]
seems that it doesn't respect num-lock; i can still use the "arrow" mode of the numpad to move the cursor around.

**Comment by PrairieAstronomer** [comment]
its confirmed, I have it on ubuntu and on the linux container on my chromebook. Quite annoying, especially when I default to using the number pad for numbers. I have known about it for a while actually.
