### ISSUE TITLE
clang warning/error

### ISSUE THREAD

**Issue by waxtatect** [minetest/minetest#12875]
##### Minetest version

```
5.7
dafdb3edb4b65db144d72cd2274a657af671bdd1
```

##### OS / Hardware

Operating system: Windows
CPU: i7-3610qm

GPU model:
OpenGL version:

##### Summary

Compiling minetest with clang produces this:
![image](https://user-images.githubusercontent.com/52937829/196687186-cbb6e87a-cd68-436d-a280-01681e15f331.png)

Attempt to fix this:
Just commented those two lines
https://github.com/minetest/minetest/blob/dafdb3edb4b65db144d72cd2274a657af671bdd1/src/CMakeLists.txt#L756
https://github.com/minetest/minetest/blob/dafdb3edb4b65db144d72cd2274a657af671bdd1/src/CMakeLists.txt#L801
Adding -femulated-tls to cmake_cxx_flags fix the errors and it seems to work fine

##### Steps to reproduce

Using clang 14.0.6 from https://winlibs.com/ and mingw32-make command
![image](https://user-images.githubusercontent.com/52937829/196688141-d1120efb-91dd-4987-bdcb-470b5f439520.png)
through cmake gui, imitating buildbot script for 64 bit (i had to recompile openal lib probably because of ucrt runtime)

**Comment by sfan5** [comment]
This does not appear to be our fault: https://github.com/msys2/MINGW-packages/issues/5786#issuecomment-537438701

**Comment by waxtatect** [comment]
Sounds like similar to the comments on the issue you mentioned:https://github.com/llvm/llvm-project/issues/56135#issuecomment-1162854509
Also there is this about libc++: https://narkive.com/IyF1LRy2.5
I attempted to compile with libc++ instead of libstdc++, not totally a success ;)

So from what i understand of those comments, compiling minetest with clang and mingw, using libstdc++, seems to require -femulated-tls flag
Thanks for looking into this, feel free to close the issue
