### ISSUE TITLE
There is no way of checking if you have lost connection with the server

### ISSUE THREAD

**Issue by CraigyDavi** [minetest/minetest#1288]
You could loose the connection to a server for a few reasons, two are:
* The server has crashed
* You have lost connection to the internet

There used to be a feature which froze the player when the connection was lost but that feature seems to be gone now.
This is needed because the server you are playing on could crash unexpectedly and you would have no idea and might still be building - you might have lost quite a bit of progress.

Suggestions:
* Add back the client freezing feature
* Add a feature which sends the player back to the main menu with a message stating "Connection to server has been lost" (just like what happens when you get kicked).

**Comment by indriApollo** [comment]
+1 I use a sh*tty vpn to connect to some servers and it happens quite a lot where I'm a building a suppa fat tower but unfortunately my packets never reach the server :(

**Comment by SmallJoker** [comment]
I loved the old screen freeze when the connection was lost. It got removed about a year ago IIRC.

**Comment by neoascetic** [comment]
+1

**Comment by NathanSalapat** [comment]
In my experience when I crashed a server the game would no longer let me craft or pick up dug nodes. I do think that @Jordach idea is a good one. +1

**Comment by ExcaliburZero** [comment]
It would be quite useful to have a message sent to the user when they lose connection to a server. It's quite annoying to lose connection with a server and not realize it until a few minutes later when I try to build something.

**Comment by Megaf** [comment]
A message sent to player would be very welcome. So would the freeze feature. And so would the back to menu thing.

All three are great, the way it is now is not perfect.

**Comment by est31** [comment]
We have automatic kicking on shutdown and lua crashes, and timeout disconnections for network problems and server c++ crashes. Therefore, this is fixed.

**Comment by neoascetic** [comment]
May client be notified with an "network problems" icon or something?

**Comment by est31** [comment]
No, you will be logged out on timeout.
