### ISSUE TITLE
Dynamic shadows: Sun can be tilted only Northwards

### ISSUE THREAD

**Issue by CowboyLva** [minetest/minetest#12893]
##### Minetest version 5.6.1

Values allowed between 0 and 60, can't set the Sun to be Southward.
0 - Sun above
60 - Sun at a low elevation angle, North side of sky at noon

##### Pay attention to time and where shadow is

0 degrees (The shadow is south, which may actually not be an issue because the angle goes by +Z(axes) and a true zero might cause weird behaviour)
![screenshot_20221022_145006](https://user-images.githubusercontent.com/108756200/197337419-804e8087-5073-4610-9aee-e320c0bfdc22.png)
![screenshot_20221022_145013](https://user-images.githubusercontent.com/108756200/197337426-04f462ce-c6cf-4c50-a247-a1a3487a9b7e.png)

60 degrees
![screenshot_20221022_145200](https://user-images.githubusercontent.com/108756200/197337482-ef9fb35e-ac04-430d-ab45-b9224d12efeb.png)

**Comment by CowboyLva** [comment]
Tagging this as bug kinda feels wrong, but the description is the closest in tag selection.

**Comment by Zughy** [comment]
Wait, how ca you tilt the sun in the first place? I'm confused about what I'm looking at

**Comment by x2048** [comment]
@Zughy you can tilt the orbit of Sun and Moon. Positive values tilt towards North (like in Southern hemisphere on Earth), this request is about adding support for tilting towards South (like in Northern hemisphere).
