### ISSUE TITLE
Chinese

### ISSUE THREAD

**Issue by fly19992020** [minetest/minetest#12909]
Why can't I enter Chinese in the chat box?

**Comment by sfan5** [comment]
Which Minetest version and OS are you using?

**Comment by y5nw** [comment]
For record, I minetest/irrlicht#23 and minetest/minetest#11156 were X11-specific because it is the only platform I can test things on and Irrlicht did (does?) not have a dedicated backend for Wayland, as far as I remember.

**Comment by Emojigit** [comment]
Copy & Paste works well on MT, so as a temporary workaround, you can copy CJKs from elsewhere and then paste it onto MT. On my OS (Arch Linux, Wayland, KDE Plasma), this works.

**Comment by y5nw** [comment]
Found two issues that this is likely a duplicate of: #10634 and #302 (the latter might need to be reopened if this issue is reproducible)

> By the way, CJKs looks weird in `T`/`F10` chatroom, but looks well on the HUD. As long as the recipients have CJk fonts installed, they can see CJKs properly.

This seems to be fixed by #12867.
