### ISSUE TITLE
Chat console forgets what you were typing if you accidentally hit "up" or "down"

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#12918]
##### Minetest version
```
5.6.1, going back as far as i remember (0.4.17)
```

##### OS / Hardware
Operating system: linux

##### Summary
you can use the "up" and "down" keys to recall things you previously entered, but you lose anything you were typing

##### Steps to reproduce

* start the game (no content required). 
* open chat dialog (press "t", "/", ".", or "F10" w/ default keybinds)
* type some stuff
* press down, or press up then down

result: blank line

expected: what i was typing to still be there

**Comment by TurkeyMcMac** [comment]
Should all history be editable? Example:
1. Write some text without pressing enter.
2. Press up to change to previous history entry.
3. Edit text without pressing enter.
4. Press down.
5. Press up again.
6. Should you see the edited text?

The version of Bash I use seems to do this, but the history entry is reset once you press enter with the edited text in the prompt. I'm not sure of the intricacies.

**Comment by fluxionary** [comment]
i'm used to the bash behavior, but i'm not always a fan of it. sometimes i want it to remember edits i made to previous entries, sometimes i want it to go back to what i'd originally typed. probably there's some sequence of control keys i could press to bring back what i want, but i've never learned it. 

honestly, a viable solution for me, would be to entirely disable the up/down keys from scrolling through the history after i started typing, until i either hit enter or cleared the line (ctrl-u).
