### ISSUE TITLE
dtime_s behaviour

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#12915]
5.7-dev

I used "dtime_s == 0" to check new entities and  to differenciate from old ones.

But lately I get random issues with this, I get a random zero value in the game reloads. Any change in a recent PR?

I know about a lot of changes in deactivate and unload events in code.

**Comment by sfan5** [comment]
I don't think anything about this changed, regardless there are more reliable ways to tell if an entity is new or not.

**Comment by runsy** [comment]
I copy this method from mobs_redo.

So, close. I did it in another way.
