### ISSUE TITLE
Crash when 'bloom_intensity' is set to '1.0'.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#12920]
##### Minetest version
```
Minetest-5.7.0-9b24041394ecf8210514845372d965f8d65302c9
```

##### Summary
Client crashes after the game quit if `bloom_intensity` setting is set to the maximum value (1.0) not depending on a configuration of the remain bloom-related settings. This happens like because of the #12916 that was merged literally few hours ago. Also, there's no any error message output in debug.txt.

##### Steps to reproduce
1. Enable bloom.
2. Set `bloom_intensity` to `1.0`.
3. Join and leave the game.

**Comment by Andrey2470T** [comment]
Also, with `enable_bloom_debug = true` the client stops rendering the graphics (just gray screen):
 
![Снимок экрана от 2022-11-02 14-15-55](https://user-images.githubusercontent.com/25750346/199476999-be3f7179-5318-461e-ab9c-8a86fd8377ed.png)

**Comment by Zughy** [comment]
cc @x2048

**Comment by srifqi** [comment]
I can not reproduce the crash when using any valid value for `bloom_intensity`, but I can reproduce the second problem in the reply.

**Comment by x2048** [comment]
Moved the shader problem to #12922
