### ISSUE TITLE
Differencial behaviors in on_use / on_place mod callback on localhost and server

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#12933]
##### Minetest version
```
Minetest 5.6.0 (Linux)
Using Irrlicht 1.9.0mt7
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

But I also tested 5.6.1 and with/without LuaJIT, with the same results on two different computers. I test minetest from the arch package repository and from builds from source code.

##### OS / Hardware
Operating system: Arch Linux

##### Summary

Function [feed_buckets.use_bucket_of_feed](https://github.com/sfence/feed_buckets/blob/master/functions.lua#L16):

This part of code:
```
 if (feeds>0) then
    itemstack:take_item(1)
    local inv = user:get_inventory()
    local empty = inv:add_item("main", ItemStack(feed_data.empty_item))
    if (empty:get_count()>0) then
      minetest.add_item(user:get_pos(), empty)
    end
  end
```

Seems to work differently depending on it how the server is started or the player is connected.

https://forum.minetest.net/viewtopic.php?f=47&t=28842

##### Steps to reproduce
Create a world with creative privileges, enable feed_buckets mod and mobs_animal.
Join to the world from minetest menu" Play Game" (no host server enabled), spawn a chicken, get some feed_buckets of wheat seeds (```/giveme feed_buckets:bucket_wheat_seeds 99```), and use the feed bucket near to chicken/chickens. The number of feed buckets should be reduced by one peruse, and one empty bucket should appear in your inventory peruse.

Store remaining feed buckets in the chest is recommended.

Shutdown the world, start the server from the command line ``` minetest --server ... ````, join it by "Join Game" tab in minetest menu and try to feed chicken again. Number of feed buckets should be reduced, but NO empty bucket is added to the player inventory for me.

**Comment by SmallJoker** [comment]
Mod issue.
You are overwriting the wielded item here with [set_wielded_item](https://github.com/sfence/feed_buckets/blob/master/functions.lua#L34) and [the return value](https://github.com/sfence/feed_buckets/blob/master/functions.lua#L54) twice.

**Comment by sfence** [comment]
Confirmed. 

Removing set_wielded_item solved the problem.

Thanks.

PS: it was not a bug, it was meaning. I want to temporarily change wielded_item and I was calculating, that the return value from the function will overwrite the temporary wielded item stack back.

But I miss, that the add_item method can add an empty bucket to the empty place after wielded_item.
