### ISSUE TITLE
Killing mob 💀

### ISSUE THREAD

**Issue by NSTAdventure** [minetest/minetest#12938]
## Problem
Killing mob is really annoying because why in the world you need to tap and hold on screen to kill a mob in the minetest? 💀

## Solutions
Inspired by Minecraft allow user to Tap to kill mob instead need to tap and hold to kill mob

## Alternatives
N/A

## Additional context

**Comment by rollerozxa** [comment]
duplicate of #2761

**Comment by NSTAdventure** [comment]
> duplicate of #2761

Welp sorry about that :-(
