### ISSUE TITLE
Allow For Things To Stare At Your Mouse Pointer

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#12931]
## Problem

Whenever you open your inventory in MineCraft, the character in the inventory screen stares at your mouse pointer no matter where you move it, until you either close your inventory, or the game's window loses focus. This does not currently appear to be possible to do in MineTest as well.

## Solutions

Make it possible for things to follow your mouse pointer around, so something as stated above can be possible to do in MineTest.

**Comment by sfan5** [comment]
This should be implemented by the game on its own when SSCSM is ready, it's way too specialized to be coded into the engine.
