### ISSUE TITLE
Allow to see players names on the server list from the Minetest client

### ISSUE THREAD

**Issue by CrocodileCroco** [minetest/minetest#12935]
## Problem

When i want to see the players' names that are actually being used on the server, i need to open servers.minetest.net, do a CTRL+F to search the server and then hover the server player count.

I can't do this in the Minetest client itself.

## Solutions

Add ability to see players names when hovering player count in the Minetest client.

## Alternatives

I don't know.

## Additional context

None.

**Comment by SmallJoker** [comment]
#8782
