### ISSUE TITLE
String "Clear" is used twice with 2 different meanings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#12936]
The string "Clear" now is now used in 2 different meanings. The first one is for the keyboard key named "Clear", the second one is for clearing a search filter in the server list.

String found in:

* `src/client/keycode.cpp`
* `builtin/mainmenu/tab_online.lua`

This is a problem for translation because the string might need different translations due to the different context (as in German).

Suggestion: Either make use of a `gettext` context for all keyboard keys, or change one of the strings. Either solution will avoid a collision and make sure that Gettext sees two different strings instead of one. The first solution is better for long-term use as it will avoid possible future collisions.

**Comment by Desour** [comment]
I guess it's too late to fix this before the release.
At least the clear key seems to not be too common (only exists on (some?) apple computers).

Using a different gettext context for keyboard keys sounds good.

**Comment by srifqi** [comment]
As of the recent `master` branch, here is the list of strings that occur both in `src/client/keycode.cpp` and elsewhere.

```pot
#: builtin/mainmenu/dlg_config_world.lua builtin/mainmenu/dlg_contentstore.lua
#: builtin/mainmenu/dlg_create_world.lua
#: builtin/mainmenu/dlg_delete_content.lua
#: builtin/mainmenu/dlg_delete_world.lua builtin/mainmenu/dlg_register.lua
#: builtin/mainmenu/dlg_rename_modpack.lua
#: builtin/mainmenu/settings/dlg_change_mapgen_flags.lua src/client/keycode.cpp
#: src/gui/guiKeyChangeMenu.cpp src/gui/guiPasswordChange.cpp
msgid "Cancel"
msgstr ""

#: builtin/mainmenu/dlg_delete_content.lua
#: builtin/mainmenu/dlg_delete_world.lua builtin/mainmenu/tab_local.lua
#: src/client/keycode.cpp
msgid "Delete"
msgstr ""

#: builtin/mainmenu/settings/dlg_settings.lua builtin/mainmenu/tab_online.lua
#: src/client/keycode.cpp
msgid "Clear"
msgstr ""

#: src/client/keycode.cpp src/gui/guiKeyChangeMenu.cpp
msgid "Left"
msgstr ""

#: src/client/keycode.cpp src/gui/guiKeyChangeMenu.cpp
msgid "Right"
msgstr ""

#: src/client/keycode.cpp src/gui/guiKeyChangeMenu.cpp
msgid "Zoom"
msgstr ""
```
