### ISSUE TITLE
API get_current_modname can not used in a function

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#12948]
## Minetest version
```
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

## Summary

The `minetest.get_current_modname()` can only return mod name on `init.lua` file directly. So you can not write files into the mod folder too. 

### Background

I need to record student's learning in the same file instead of having the records scattered in each world folder.

## Steps to reproduce

```lua
-- Can work here:
local MOD_NAME = minetest.get_current_modname()

local function isWritenModDir()
  -- can not work here: 
  -- the modName is always nil
  local modName = minetest.get_current_modname()
  return not not modName
end
```

BTW I've writen a patch to parse the caller's mod name and check for forgery.

**Comment by rubenwardy** [comment]
You can open a file handle and then write to it afterwards. But do note: **any data written to a mod's folder will be lost when the mod updates**

**Comment by TurkeyMcMac** [comment]
`minetest.get_current_modname` can be called outside `init.lua`. Example: https://github.com/minetest/minetest/blob/00eb65915fb31539d747b57282f7383e8996af6a/builtin/common/mod_storage.lua#L17

The restriction is that it can only be called at load time. If you need it later, store the name in a variable at load time. For less reliable mod tracking, you can call `minetest.get_last_run_mod` after load time, but this function is undocumented.

**Comment by snowyu** [comment]
@TurkeyMcMac  This is just a workaround for static files. I need create the files(one file per student) dynamically on runtime.
@rubenwardy the `get_mod_data_path` is good enough to keep data for common mods.

I read the source, the current implementation is a very simplified implementation, as this implementation is no way to determine at runtime which mod the real caller is in. Therefore, even if it is trusted mod, the functions such as mkdir cannot be used to create files (folders).  The only way is to disable the security feature `secure.enable_security`, or rewrite mkdir etc functions with `insecure-env`.

**Comment by rubenwardy** [comment]
> I read the source, the current implementation is a very simplified implementation, as this implementation is no way to determine at runtime which mod the real caller is in. Therefore, even if it is trusted mod, the functions such as mkdir cannot be used to create files (folders). The only way is to disable the security feature secure.enable_security, or rewrite mkdir etc functions with insecure-env.

Are you referring to get_mod_data_path? The separation between mods isn't meant to be a security feature, but a safety feature. All the mod data paths are writable by any mod if they can construct the path

**Comment by snowyu** [comment]
@rubenwardy For security, this implemetation needs to be rewritten to determine at runtime which module the caller is in.  It can be done by analyzing the call stack.
