### ISSUE TITLE
Inventory search box does not handle inventory key correctly when using SDL driver

### ISSUE THREAD

**Issue by paradust7** [minetest/minetest#12941]
##### Minetest version
```
Minetest tip of tree (322c8cf270a6fe2cd6ac152af0f3f5d2963fa0b3)
Irrlicht tip of tree (a549d0bfed02801d642ef281697f8ac7c3dbc2cf)
```

##### OS / Hardware
Operating system: Linux

##### Summary
When the letter "i" is typed into the search box on the inventory/recipe page, the dialog closes, instead of inputting the letter. This happens in minetest_game and mineclone, and most likely any other.

The regression appears to have been triggered by this commit:
https://github.com/minetest/irrlicht/commit/67c0cb5740b253a64a92786fda22205e030266e0

##### Steps to reproduce
1) Build with SDL enabled by defining `_IRR_COMPILE_WITH_SDL_DEVICE_` in IrrCompileConfig.h
2) Open new world, go to Inventory, go to Recipes, and type into the search box.
3) Typing an "i" (the inventory key) into the search box closes the dialog. Every other letter works normally.

**Comment by sfan5** [comment]
This sounds like it should be filed as an issue on the Irrlicht repo.

**Comment by Desour** [comment]
Known issue (last point in <https://github.com/minetest/irrlicht/issues/137>). But nice work finding the regression commit.

**Comment by paradust7** [comment]
> This sounds like it should be filed as an issue on the Irrlicht repo.

Most likely. Feel free to close this, since it is a duplicate.

Fixing this bug (without introducing new ones) seems intractable, as SDL generates both TEXTINPUT and KEYDOWN events separately, in a platform-depedent way, with no way to know that the two events are generated by the same key press. Yikes.

**Comment by ndren** [comment]
Hi @paradust7, person who regressed the code here. Sorry about that.
> Fixing this bug (without introducing new ones) seems intractable, as SDL generates both TEXTINPUT and KEYDOWN events separately, in a platform-depedent way, with no way to know that the two events are generated by the same key press. Yikes.

Why is that? Shouldn't minetest be able to check if it is inside some form of menu (inventory or otherwise, since this bug also happens in others), and, if it is, do not exit in that case (that is, ignore the Irrlicht event)? What side effects/bugs would this approach have?

(Side note: I do not fully understand why the old code worked whereas the new code does not; is it because I have set irrevent.KeyInput.Char to 0? Is this similar to CGUIEditBox.cpp in that sense?)

**Comment by paradust7** [comment]
@ndren 
Yes, the immediate problem is that CGUIEditBox assumes keyboard events with Char == 0 are control keys, and so passes it to its parent instead of consuming it. My initial attempt fixed only this:

https://gist.githubusercontent.com/paradust7/94e1f0e302a584731453b75cb96ebc9a/raw/516e27eb564bc243a8be4c03db8cd5aab7f9c30a/gistfile1.txt

This works, but exposes another problem. When you hit "i" to open the inventory, SDL generates a KEYDOWN followed by a TEXTINPUT. These translate into EET_KEY_INPUT_EVENT followed by EET_STRING_INPUT_EVENT, both for "i". The first one (with Char == 0) opens the inventory menu. But then the second types the letter i. This means if you open the inventory and the inventory page happens to have an edit box, it will immediately type an "i" into it.

**Comment by paradust7** [comment]
@ndren
Looking at the Linux irrlicht driver, it emits EET_KEY_INPUT_EVENT with Char != 0 when possible, only emitting EET_STRING_INPUT_EVENT when the text is unicode. Never both at the same time. So it never needs to deal with this situation:

https://github.com/minetest/irrlicht/blob/master/source/Irrlicht/CIrrDeviceLinux.cpp#L942-L955

It would be nice to do the same thing in the SDL driver, but SDL does not provide any clean way of linking the KEYDOWN and TEXTINPUT events. For my purposes (keeping minetest-wasm up to date, which uses SDL), I threw in an ugly hack to connect the two:

https://github.com/paradust7/irrlicht/commit/262d3d0151feef2f36944cf785a96e9fc7588034

I'm not sure if this would work in general. It works in my case, because the SDL events are generated from browser events that occur in order.

**Comment by ndren** [comment]
@paradust7 Interesting, thanks! I'm not sure how to approach this...

Your patch from the gist does seem to provide better behaviour, so maybe consider sending a pull request. An extra "I" which can be deleted is much better than closing menus entirely.

**Comment by paradust7** [comment]
@ndren Feel free to use the code if you want. Note that there may be many other places where an extra character pops up, e.g., pressing "t" to talk.
