### ISSUE TITLE
Will Minetest support player made shader?

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12947]
Will Minetet support player made shader?
like easy shader install, documents for coding and ContentDB shader category

so player will have a wide range of shader to choose or made one

**Comment by rubenwardy** [comment]
Players can already install their own shaders by modifying client/shaders

I don't support specifically adding a type of content for shaders, but server-side mods and games should be able to customise a lot more about rendering - including providing shaders, in the future

**Comment by nerzhul** [comment]
i'd like to see when someone will publish a sharder working on nvidia and crashing android devices.... :(

**Comment by oong819** [comment]
OpenGL shader cant run OpenGL ES device and a shader run smooth on this device can burn some device...

solved with system requitment of shader
