### ISSUE TITLE
(Question) Why server no 521 got banned?

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12942]
Sorry if this are not place for issue like this

**Comment by sfan5** [comment]
Nobody here knows what "server 521" is, where it supposedly got banned from or how you came to this conclusion.

**Comment by oong819** [comment]
> Nobody here knows what "server 521" is, where it supposedly got banned from or how you came to this conclusion.

here what i mean: https://youtu.be/s13CGQkZmE8

also lunar eclipse happening right now!

**Comment by rubenwardy** [comment]
They've probably just messed up their config, causing the announce to fail. That's the more likely case than banning
