### ISSUE TITLE
(Question) Can i run a Minetest server with free hosting service?

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#12957]
Can i run a Minetest server with free hosting service? like awardspace, infinityfree, uhostfull and maybe ngrok, sish

and if yes, how to set up a server (like what file to upload, world file?)

**Comment by rollerozxa** [comment]
You can't host a Minetest server on a shared web hosting provider. Ngrok and sish are web tunnel services that require you to have a server at home (they're intended to circumvent CGNAT and such), but do not support UDP which is what the Minetest netcode uses.

**Comment by appgurueu** [comment]
@Zughy would you mind taking care of this question?
