### ISSUE TITLE
Minetest crash on Android 

### ISSUE THREAD

**Issue by Anonymous1231-dev** [minetest/minetest#12952]
##### Minetest version

```
00eb659
```

##### OS / Hardware

Operating system: Android 12 (API 31)
CPU: Snapdragon 685

GPU model: 
OpenGL version:

##### Summary

When I install and open the app, the app crash instantly 

https://user-images.githubusercontent.com/87801676/201289947-24f57499-2289-49d1-a680-e70d499e84a5.mp4

I'm sure a commit breaks it, but I'm not sure which was it ...

##### Steps to reproduce

- install from debug build
- open 
- crash :(

**Comment by Anonymous1231-dev** [comment]
Maybe [https://github.com/minetest/minetest/commit/987277de52633208fae027e9d3bd0f7affa79a66](this?)

**Comment by rollerozxa** [comment]
logcat logs would be useful. keep in mind if you're updating from one dev version to another you need to wipe built-in or it will most likely crash after a couple commits

**Comment by Anonymous1231-dev** [comment]
> logcat logs would be useful. keep in mind if you're updating from one dev version to another you need to wipe built-in or it will most likely crash after a couple commits

But how to use? I'm dumb :(

**Comment by oong819** [comment]
is this relative to #12863 ?

**Comment by Anonymous1231-dev** [comment]
No, it just happened in 1st open

**Comment by srifqi** [comment]
This might be caused by #12632, too.
