### ISSUE TITLE
Vertex normals of wavefront .obj meshes are ignored if the vertex has multiple UV coordinates

### ISSUE THREAD

**Issue by doxygen-spammer** [minetest/minetest#12965]
##### Minetest version

```
Minetest 5.7.0-dev-1a045da0d (Linux)
Using Irrlicht 1.9.0mt9
```

##### OS / Hardware
OpenGL version: 3.0
Operating System: KDE neon 5.26
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4300U CPU @ 1.90GHz
Memory: 7.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4400

##### Summary
Entirely correct smooth shading is not possible with the wavefront .obj file format, because certain vertex normals are ignored by Minetest.
This file format defines a face by 3 (or more) corners, which each have the format `<vertex_index>/<uv_point_index>/<normal_index>`.

Vertices often have more than one uv point associated, because you usually need some “UV seams”.

If you need certain combinations of smooth and flat shading (for example for a cylinder), the sharp edges need to use “split normals”, which is easy to do in Blender and accurately represented in .obj.
This means there is more than one UV point index per vertex index.

Minetest detects when a vertex of a face uses a different UV point index than in another face.
The normals of this vertex are then replaced by the face normal.

The result is that you can not use vertex normals and UV maps together, without rendering glitches.

##### Steps to reproduce
Make a mesh node with a solid color texture.
(For example, use `testnodes:mesh` from devtest.)
As mesh file, use the wavefront .obj export of the default cube of Blender.
Use this export configuration:
![Screenshot_20221114_183915](https://user-images.githubusercontent.com/76133492/201728622-55fff701-40ab-4c85-a2c5-94446f3838c9.png)

The cube will look like this.
Note that the left corners are shaded smooth, while the right corner is broken.
![Screenshot_20221114_182724](https://user-images.githubusercontent.com/76133492/201726260-bbdbb79f-5a62-452a-bd80-99127c34c034.png)

This is how it should actually look like.
UV coordinates have been removed here.
![Screenshot_20221114_183132](https://user-images.githubusercontent.com/76133492/201727020-26bc66b1-2dae-4688-8276-d1135ac9aaf9.png)

For convenience, the two .obj files are here:
[uv.obj.txt](https://github.com/minetest/minetest/files/10005607/uv.obj.txt)
[no_uv.obj.txt](https://github.com/minetest/minetest/files/10005609/no_uv.obj.txt)

**Comment by Zughy** [comment]
Can't reproduce it anymore, seems fixed

no shaders, `menu_bg.png`
![image](https://github.com/user-attachments/assets/f8ee948c-f0fb-4954-844e-d2e33d3675bc)

shaders, saturated version of `menu_bg.png`
![image](https://github.com/user-attachments/assets/f07fbba7-7e26-44fe-bcfb-e671ab4def0a)
