### ISSUE TITLE
Text overflow in parameters menu

### ISSUE THREAD

**Issue by Butineur** [minetest/minetest#12976]
##### Minetest version

```
5.6.1
```

##### OS / Hardware

Operating system:
CPU: 64

GPU model:
OpenGL version:

##### Summary

In the french version, the screen auto-save of screen size option text overflows from its box.
![immagine](https://user-images.githubusercontent.com/63455151/202904358-389b988d-79ac-432a-9f3a-56103b3d7978.png)

##### Steps to reproduce

Normal installation of Minetest, but with french language.

**Comment by Zughy** [comment]
#12480 will fix this

**Comment by kilbith** [comment]
It has to be said: french translations suck. They seem to be made by teenagers still in high school who don't speak their own language well. Translators write much more than necessary, or do literal translations when it's completely inappropriate.

**Comment by Zughy** [comment]
Same for Italian, there are basically two of us battling for having their version in the official release, every release. And - as someone with a degree in foreign languages and who translates from time to time - I can say that the worst one always wins. It's pretty annoying

**Comment by rubenwardy** [comment]
We have the ability to ban contributors or use a whitelist. If you give me the names of saboteurs, we can try the former

**Comment by oong819** [comment]
the openGL text on my device also overflow but got cut off and cant see
