### ISSUE TITLE
Default Game Brightness Too Dark

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#12973]
## Problem

The light in this game feels way darker than in Minecraft. When you reach light level 0, everything just becomes pitch black and you become unable to see anything at all. Not even Minecraft on 'Moody' brightness gets this dark.

## Solutions

Add some sort of setting that lets you change the brightness from 'Very Dark' to 'Very Bright', instead of having just this dark brightness by default.

## Alternatives

Change the default brightness of the game to something more bearable for lower light levels.

**Comment by Zughy** [comment]
Done some digging, the basically same request was closed years ago by a former core dev #4060, where *former* is the keyword. I personally approve this, the almost pitch black colour at night makes the experience very annoying, with people usually tweaking their physical screen settings to actually see something. This level of darkness shouldn't be the default value

**Comment by Zughy** [comment]
@lhofhansl @x2048

**Comment by fluxionary** [comment]
i think "0 light" wasn't pitch black before 5.0; i think the following PR was what introduced that?

https://github.com/minetest/minetest/pull/5279

when 5.0 came out, players seemed to think this was to prevent players from "cheating" by setting gamma very high, so as to be able to see in caves without needing torches or anything. at least one server owner considered that to be "cheating" and ban-able, though i'm certain some people did that anywat. server owners might be taken by surprise if things go back to the old status quo.

**Comment by MisterE123** [comment]
leave it to games, as always. Change minetest_game to default to something reasonable

**Comment by nephele-gh** [comment]
I am developing the orion gamemode and am quite annoyed by this behaviour aswell, the night simply isn't fun to play.

**Comment by fluxionary** [comment]
> Not just the night, but caves as well are plain unbearable with this brightness.

the general solution is to fill them up w/ torches, and to use a mod like [wielded_light](https://github.com/minetest-mods/wielded_light). there's also ways mods can create night-vision by setting a [day/night ratio override](https://github.com/minetest/minetest/blob/4da8a18c8c72a125a3ea4f3842e08757d8dbe321/doc/lua_api.txt#L7400-L7403), but i'm not aware of much that uses this in a general way in survival

* https://github.com/BlockySurvival/titanium
* elements from tunnelers' abyss (which is closed source)

i had a "sunlight" admin command hanging around, i've just added it to one of my debugging mods:
* https://github.com/fluxionary/minetest-debuggery/blob/main/README.md?plain=1#L113-L117

also, found another related issue from years ago: #6509, and a closed PR from more recently: #11499

**Comment by Montandalar** [comment]
Games and/or user settings should be able to set the gamma curve/constant as well as the minimum light level. Personally, I see no reason why you should be able to see anything at all in an underground cave with no light sources anywhere nearby; that's how the human eye works, but let game authors choose it if they don't like realism. On the other hand, yes, you should be able to see at night time, moonlight is adequate to see by on most nights, just not particularly well. Should we change the default? Yes, I suppose at least a bit brighter would help.

**Comment by sfan5** [comment]
I think we can close this in favor of #14900 instead of doctoring on the defaults.

**Comment by Zughy** [comment]
Default is actually too dark, I don't feel like this should be closed. Like, it's completely pitch black

**Comment by sfan5** [comment]
Why should the engine make the choice for this default if games want to customize it anyway?
What about backwards compat?
Isn't this the same situation as the "ugly by default" inventory formspec?

**Comment by Zughy** [comment]
> Why should the engine make the choice for this default if games want to customize it anyway?

Because basically we're asking 99% of games to tweak brightness, due of the parameter being a bad default

> What about backwards compat?

I understand the argument, but at the same time what's happening is, in order to avoid annoying a few, we make life harder for everyone else. I think saner defaults should be the way

> Isn't this the same situation as the "ugly by default" inventory formspec?

Definitely, but at least texture packs can have a saying there. ...Well, kinda, default button styling isn't tweakable, which is a pity because default is horrible

**Comment by Montandalar** [comment]
> Default is actually too dark, I don't feel like this should be closed. Like, it's completely pitch black

This feels like one of those author-player conflicts.

From a realism perspective it has always made sense to me that a cave with no light sources is pitch black. As for night time, a better gamma curve or a shader where the "eye" adapts to lower light would make sense.

However if you can show popular support for light level 0 being not completely black, then I'd happily accept that the default should not be completely black. Then if I wanted it black in my game/mod I wouldn't begrudge having to set that back.

**Comment by Zughy** [comment]
I don't think I have the energy to keep dealing with pros and cons, and most importantly I don't want to start a survey of sort. Closing as suggested by sfan5

**Comment by j-r** [comment]
> i think "0 light" wasn't pitch black before 5.0; i think the following PR was what introduced that?
> 
> [#5279](https://github.com/luanti-org/luanti/pull/5279)

I think it's #7693 that forced the lowest light level to zero. Just changing that loop to start at zero allows the lowest light level to be influenced by boost and gamma. With default settings it is still pretty dark, but it can become really bright by increasing the boost / moving it to the darker side of the light curve and using high gamma.
