### ISSUE TITLE
Add Additional Biomes Support For V6 Mapgen

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#12981]
## Problem

The v6 mapgen does not appear to support any mods that add any extra biomes, nor do subgames work correctly most of the time with this mapgen because of the current limitations it has in terms of biomes.

## Solutions

Make it so mapgen v6 is on par with all the other mapgens in terms of additional biomes support.

**Comment by Zughy** [comment]
Not happening, considering #8926 #8745, #6827 and the fact that the only core dev who used to focus on mapgen is gone

**Comment by SmallJoker** [comment]
@FossFanatic Mapgen mismatches generally result in flat walls and cliffs at the border from old <--> newly generated mapblocks. Biome mismatches would manifest as abrupt biome type changes. For demonstration purposes, modify `mg_biome_np_humidity` inside `map_meta.txt` inside a disposable map.

Don't get me wrong - if you somehow manage to match the mgv6 biomes, feel free to propose a PR. It's just that you might spend time on a rather uninteresting mapgen.

**Comment by TurkeyMcMac** [comment]
@FossFanatic You could try [Trailgen](https://forum.minetest.net/viewtopic.php?f=7&p=403148).

**Comment by rubenwardy** [comment]
> I would instead propose an alternative mapgen, such as v6_new that mimics v6 so that the map compatibility can be ensured.

I support doing this. Whether there's the interest or people available to do this is another matter

**Comment by TurkeyMcMac** [comment]
We might use Trailgen, provided the license is compatible.

**Comment by TurkeyMcMac** [comment]
I mean it should be LGPL v2.1+. IIRC LGPL v3 is incompatible.

**Comment by TurkeyMcMac** [comment]
TBH I don't know.

**Comment by TurkeyMcMac** [comment]
Yes, but it's something.
