### ISSUE TITLE
Remove forceload limit

### ISSUE THREAD

**Issue by Kimapr** [minetest/minetest#12990]
## Problem

A limit on the number of forceloaded blocks exists. It's unnecessary and way too strict by default (16 blocks? seriously? players activate more than that).

## Solutions

Remove it.

## Alternatives

Due to the way the limit is implemented, it can be easily bypassed from Lua:

```
local forceload_block_raw=minetest.forceload_block
local tonumber_raw=tonumber
local in_forceload_block=false
function tonumber(...)
        if in_forceload_block then
                return math.huge
        end
        return tonumber_raw(...)
end
function minetest.forceload_block(...)
        in_forceload_block=true
        local ret=forceload_block_raw(...)
        in_forceload_block=false
        return ret
end
```
Confirmed working with 9k+ forceloaded blocks with no issues (apart from lag).
How it works: `forceload_block` checks the forceload limit by reading a setting, calling `tonumber` on it and comparing it against the current number of forceloaded blocks. This check can be tricked by messing with `tonumber` or the settings object to return bogus values.

## Additional context

The limit was added in #1094 (along with forceloading itself) with absolutely no reasoning behind it.

**Comment by sfan5** [comment]
There is some dev channel discussion from that day: https://irc.minetest.net/minetest-dev/2014-01-11

the recurring points appear to be
* there are better ways than forceloading and it should be discouraged
* what if people abuse it and it kills their performance (not everyone agreed)

**Comment by TurkeyMcMac** [comment]
If the limit is lifted, I think it should be kept around as an optional feature. Some mods might depend on it in order to keep players from overloading the server.

**Comment by Wuzzy2** [comment]
Isn't forceloading entirely triggered by mod/game code anyway? Let them go wild, and if the performance goes the way of the dodo, that will be 100% their fault, not Minetest's. Just put a warning in `lua_api.txt`, it should be OK.

I am in favor of removing this limit.

Besides, `lua_api.txt` needs better documentation of forceloading, it doesn't mention *why* a forceload can fail, I wasn't even aware of this limit.

Maybe add an argument to the forceload function to fail if more than X forceloads are active.

**Comment by fluxionary** [comment]
maybe we could preserve the mechanic for the limit, while effectively disabling it by default? personally, i've been aware the limit existed because some mods (e.g. [techpack](https://content.minetest.net/packages/joe7575/techpack/)) actually allow survival players to forceload areas in a limited way. allowing players a way to keep *every* mapblock active *all the time* will create problems for some existing servers, and there should be a way to restore the old mechanics, if we go forward w/ removing the limit by default.
