### ISSUE TITLE
Custom renderer/connected texture support

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#1299]
I was talking to some ppl on IRC and I heard there's no custom renderer/connected texture support, so I'm opening this issue...

EDIT:
Here's what a custom renderer would probably look like:

``` lua
customRenderers = {
inventory = function(tessellator, node) -- inventory
tessellator.startDrawingQuads()
-- stuff
tessellator.draw()
end,
hand = function(...) -- hand
-- stuff
end,
world = function(tessellator, node, x, y, z, world) -- nodes
-- stuff
end,
item = function(...) -- dropped items
-- stuff
end
}
```

**Comment by paramat** [comment]
> connected texture support

@SoniEx2 Does this provide that? #6105

**Comment by rubenwardy** [comment]
custom renders will never be an option, and connected textures are covered in other issues

**Comment by SoniEx2** [comment]
What about baking quads on the server and sending them to the client?

**Comment by numberZero** [comment]
@SoniEx2 er, that sounds weird and seems ineffective.
@rubenwardy why?
