### ISSUE TITLE
Separately aligned text boxes for grouped objects

### ISSUE THREAD

**Issue by kneekoo** [minetest/minetest#13000]
Can/could Minetest support this kind of signposts with each "plank" as a separate object?
![signpost](https://e7.pngegg.com/pngimages/637/776/png-clipart-brown-wooden-sign-illustration-traffic-sign-arrow-crooked-arrow-planks-angle-sign-thumbnail.png)

It would be nice if each line of the textbox would automatically go to the corresponding plank, without worrying about alignment of text of different sizes. Maybe left or right alignment would be helpful, depending on the text and plank size, but having the vertical alignment done automatically per-plank would be great.

P.S. I didn't know how to give this a better title, feel free to shove more sense into it if you can.

**Comment by TurkeyMcMac** [comment]
Are you talking about a signpost node? If so, I'm pretty sure you could do that with a mod. I believe existing sign mods do text rendering themselves.

**Comment by TurkeyMcMac** [comment]
You could check out [display_modpack](https://content.minetest.net/packages/Pyrollo/display_modpack/), it might have an API you could use (I haven't used it.)

**Comment by rubenwardy** [comment]
You can use a mesh node or some sprite-based node to render the sign itself, I don't think this needs a specific drawtype.

As for the text, for now you need to use an entity like done by display_modpack. The issue for engine support is #1367

**Comment by kneekoo** [comment]
Thanks! :) That mod is worth looking at, but the 8-year old open issue looks like a dead end after so long. :P

**Comment by fluxionary** [comment]
> As for the text, for now you need to use an entity like done by display_modpack. The issue for engine support is https://github.com/minetest/minetest/issues/1367

[someone offered to pay $500](https://github.com/minetest/minetest/issues/9946#issuecomment-634538451) for implementing proper text rendering. 

this is very much a soluble problem (e.g. [cairo](https://www.cairographics.org/) exists), but it's outside my area of comfort. but that bounty is tempting. on the other hand, if i had money to give out, i'd pay for such a feature, the way text compositing is done in minetest causes me great sadness.
