### ISSUE TITLE
Allow Tilemaps To Scale With Texture Packs

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#13016]
## Problem

Some games may prefer using tilemaps to store all the textures of a game instead of multiple seperate images for each texture.
Using tilemaps, however, has the downside of not allowing you to use any texture packs that have a higher or lower resolution than the one specified by the (sub)game (16X in most cases). Because you have to specify the height and width of a tile in the code, which a texture pack cannot decide for itself.

## Solutions

Make it possible for texture packs of different resolutions to work with tilemaps of different resolutions.

**Comment by rollerozxa** [comment]
They are already able to scale up as you specify the amount of cell grids, not the resolution of each cell.

**Comment by rollerozxa** [comment]
I don't think so. Actually, you probably could cut out the animation strip from a texture atlas using the `^[combine` texture modifier but that would not scale with a differently sized atlas like `^[sheet` does.
