### ISSUE TITLE
Use minetest as a demo show in kruise-game.

### ISSUE THREAD

**Issue by ringtail** [minetest/minetest#13014]
Hi, I'm the maintainer of kruise-game(https://github.com/openkruise/kruise-game) which is an opensource cloud-native game server workload. I am a fan of minetest and want to use minetest as a demo to show how to containerize a game server and run on kubernetes. Could we use minetest in our docs and examples?

Thanks, Look forward to your reply!

**Comment by rollerozxa** [comment]
Minetest is free software licensed under the LGPLv2.1. You're free to do whatever under the terms of the license.

**Comment by ringtail** [comment]
> Minetest is free software licensed under the LGPLv2.1. You're free to do whatever under the terms of the license.

Whether the logo is under the license?

**Comment by qwerty123a2** [comment]
you do not need to ask.

**Comment by TurkeyMcMac** [comment]
Looking at the [license file](https://github.com/minetest/minetest/blob/master/LICENSE.txt), the default texture license is CC BY-SA 3.0. There are exceptions for those authored by Zughy and DS, but the author of the Minetest logo is erlehmann. Therefore, I believe the logo is CC BY-SA 3.0.

**Comment by TurkeyMcMac** [comment]
@ringtail Has your question been answered?

**Comment by ringtail** [comment]
> @ringtail Has your question been answered?

Thanks!
