### ISSUE TITLE
ItemStack clears all values when only one value is cleared. Documentation is missing this.

### ISSUE THREAD

**Issue by doxygen-spammer** [minetest/minetest#13021]
##### Minetest version

```
Minetest 5.7.0-dev-1a045da0d (Linux)
```

##### Summary

When you set the count of an otherwise valid ItemStack (as Lua value) to zero, all other information is cleared too.
The same happens when you set the name to an empty string.

For example, you can not reduce the count of an ItemStack (because the player has placed a node), and then read more detailed information about it (because the node has a palette, so you need `palette_index`).

For me this behavior is unexpected.
If you remove all values from a Lua table, it doesn’t automatically lose its metatable.

There is no indication in lua_api.txt that all values of the ItemStack are cleared when the count is set to zero.

Even if lua_api.txt says this:

> * `set_name(item_name)`: returns a boolean indicating whether the item was
>   cleared.
> * `set_count(count)`: returns a boolean indicating whether the item was cleared
>     * `count`: number, unsigned 16 bit integer

How do you imagine that “whether the item was cleared” indicates that these functions modify information they are not supposed to modify?

If you take all cars from a road, the road is cleared.
But that doesn’t make the road disappear, it will not even lose its name.

##### Steps to reproduce

```
local i = ItemStack("air");
local m = i:get_meta();
m:set_string("a", "abc");
assert(i:get_name() == "air");
assert(m:get_string("a") == "abc");

i:set_count(0);
assert(i:get_name() == "air");
assert(m:get_string("a") == "abc");
```

**Comment by Zughy** [comment]
Wait, I expect that, if I have a stack of items, and that stack is cleared, those items will cease to exist and that the data linked to them will be erased as well. I don't think of ItemStacks as they were an abstract conception. On the contrary, I picture them like the material container of items. If there are no items left, there is no stack left

**Comment by SmallJoker** [comment]
Empty ItemStacks are equal to lack of items, hence comparable to a vacuum, thus no properties (i.e. metadata). I don't think this needs documenting. Use common sense.

**Comment by fluxionary** [comment]
> Empty ItemStacks are equal to lack of items, hence comparable to a vacuum, thus no properties (i.e. metadata). I don't think this needs documenting. Use common sense.

while i generally agree, a wrinkle in that is that "player's hand" - `""` - can exist as an empty ItemStack that can still have custom metadata:

```lua
local s = ItemStack()
local m = s:get_meta()
m:set_tool_capabilities({
 full_punch_interval = 1.0,
 max_drop_level = 0,
 groupcaps = {
  choppy = {times = {2.50, 1.40, 1.00}, uses = 20, maxlevel = 2},
 },
 damage_groups = {fleshy = 1},
})

assert(s:to_string() == "")
print(dump(s:to_table()))
```

output:
```
{
	fields = {
		tool_capabilities = "{\"damage_groups\":{\"fleshy\":1},\"full_punch_interval\":1.0,\"groupcaps\":{\"choppy\":{\"maxlevel\":2,\"times\":[null,2.5,1.3999999761581421,1.0],\"uses\":20}},\"max_drop_level\":0,\"punch_attack_uses\":0}"
	}
}
```
