### ISSUE TITLE
Media Files Should Get Cached

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13027]
## Problem

Minetest currently redownloads media files from subgames when you join a world in said subgames. This can cause joining worlds to get very slow the more media files you have to download for the subgame.

## Solutions

Have the media files be cached instead, so joining worlds isn't as slow as it was before.

**Comment by rubenwardy** [comment]
This is incorrect. Media files are cached, look in the cache folder

**Comment by rubenwardy** [comment]
It caches between sessions, on the file system

**Comment by Desour** [comment]
Loading sounds takes long. See #12764 for a fix.

**Comment by michieal** [comment]
Okay, then I have this related question.
Why does it take the same amount of time with a brand new world as it does with rejoining a world, for the media portion of the progress bar?

I've timed it (mainly out of boredom... but still). I'm opening minetest up multiple times a day, and loading up worlds quite often, as I write lua for MineClone2.

**Comment by Desour** [comment]
>Why does it take the same amount of time with a brand new world as it does with rejoining a world, for the media portion of the progress bar?

Media is not cached per-world.
