### ISSUE TITLE
2x2 craft recipes are broken

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#13022]
So they are broken. For example, something like this:
```
	recipe = {
		{"", "item1"},
                {"item1", ""},
	}
```
It is a 2x2 matrix as indicated in the documentation.

Apart from that listing 2x2 crafting in a formspec is impossible, I mean if the list is 2x2:

https://github.com/BrunoMine/craft_table/blob/master/api.lua
https://forum.minetest.net/viewtopic.php?t=18926

**Comment by TurkeyMcMac** [comment]
I can't reproduce this. For example, the copper strips recipe from Basic Materials seems to work.

**Comment by runsy** [comment]
> I can't reproduce this. For example, the copper strips recipe from Basic Materials seems to work.

Yep, but is a 2x3 recipe, nor 2x2

	```
	{"", materials.copper_ingot, ""},
		{materials.copper_ingot, "", ""},
```

Try changing it to:
	```
	{"", materials.copper_ingot},
		{materials.copper_ingot, ""},
```

**Comment by runsy** [comment]
Frome the docs:

> recipe`: A 2-dimensional matrix of items, with a width *w* and height *h*.
>     * *w* and *h* are chosen by you, they don't have to be equal but must be at least 1

**Comment by runsy** [comment]
If 3x2 works I could use it for my game, but I would prefer 2x2 for a code aesthetic reason.

**Comment by TurkeyMcMac** [comment]
I tried changing copper strips to 2x2 and they still work. They show up in the default crafting guide and can be crafted.

**Comment by SmallJoker** [comment]
`inv:set_width("craft", 2)` should do the trick. Crafting needs to know how many columns there are in your grid.

**Comment by runsy** [comment]
> `inv:set_width("craft", 2)` should do the trick. Crafting needs to know how many columns there are in your grid.

inv:set_width("craft", 2) should did  the trick for me, thanks.

@desour and @TurkeyMcMac thanks too.

Closed.
