### ISSUE TITLE
Static binary builds for Linux on common architectures

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#13037]
## Problem

Sometimes I need to run Minetest, either client or server, on a shell server or my SBC. In shell servers, like those in [tildeverse](https://tildeverse.org) people don't have root access so they can't install Minetest using package manager. Also in both cases mentioned, the latest version would be old. And distro repos usually don't provide nightly channels for Minetest.

## Solutions

1. Publish static and fully self-dependent Minetest binaries in each release for common architectures. I'd say `i386`, `x86_64`, `arm64` and `armv6/7`.
2. Publish the same type of binaries for last 10 commits to the main/master branch.
3. There must be two separate binaries for server and client.

Github Actions can be used for this purpose.

## Additional context

The number 10 in the 2nd and the architectures in 1st must be discussed.

Edit:

I think server DB support must be discussed as well.

**Comment by NathanSalapat** [comment]
While having GitHub generate these files might be easier, nothing should stop you from doing this yourself.

**Comment by farooqkz** [comment]
Yeah sure. But my point is that it's not easy for individuals to prepare a development environment for compiling minetest. And even if they do, they need to have good enough computing power to compile it in a good time. The situation gets even worse when someone tries to compile for something like ARM. Compiling on the ARM device itself can be really time consuming and cross-compiling is even harder comparing to compiling for your own machine.

**Comment by sfan5** [comment]
(Real) static builds of the clients are impossible, the graphics driver needs to be loaded dynamically. Regardless, getting all the client deps working statically would be unreasonable work when we already have AppImage, Flatpak or Snap.

For the server this is a more achievable feat and I have thought about this idea before. But it's still a bit of work and I wonder if we should provide such builds officially _in addition_ to Docker (which is the other alternative for "I want this app and want it self-contained" deployment).

**Comment by farooqkz** [comment]
Well AppImage and/or Flatpak for each release would be good too.

Regarding docker, that's great. But it requires additional setup and on shell servers I don't think it's available.

**Comment by rubenwardy** [comment]
Docker absolutely is available on servers without a gui, it would be useless if it wasn't

**Comment by farooqkz** [comment]
> Docker absolutely is available on servers without a gui, it would be useless if it wasn't
> 
> One reason to have static Linux binaries would be for a Steam release

Yeah but in shell servers, only admins have root access and the rest of users don't.

**Comment by SmallJoker** [comment]
The Flatpak binaries are updated quickly after each release. Please let us know when there's an extraordinary delay. Additionally Docker can be set up so that regular users can start their containers too and #13078 is on a good way to provide AppImage builds if the current options are not enough.

Closing as discussed in https://irc.minetest.net/minetest-dev/2023-01-08#i_6046071
