### ISSUE TITLE
Set submodules for minetest_game and IrrlichtMt

### ISSUE THREAD

**Issue by ogor89** [minetest/minetest#13034]
## Problem

minetest_game and IrrlichtMt repositories are not linked properly with main minetest repo. Let's say new version of IrrlichtMt will break compatibility with minetest. Doind sumple `git clone` or `git pull` for IrrlichtMt will download newest, not compatible version.

Current linking of repositories:
```
minetest --- manual link --- minetest_game
        \--- manual link --- IrrlichtMt
```

Current set of download instructions:
```
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest/
git clone --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
```

Current set of update instructions:
```
git pull
cd games/minetest_game
git pull
cd lib/irrlichtmt
git pull
```

## Solutions

Git submodule is great way to add repository. It is pointing to other repos which are not cloned by default and not much additional data will be stored in the main repo. Also submodule can point to exact commit, so if compatibility will broke by, for example, IrrlichtMt git submodule will not checkout new commits. It will stay with last accepted by main repo.

New linking of repositories:
```
minetest --- git address & ID --- minetest_game
        \--- git address & ID --- IrrlichtMt
```

New set of download instructions:
```
git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest/
git submodule init
```

New set of update instructions:
```
git pull
git submodule update --recursive
```

## Alternatives

Not known by me.

## Additional context

Issue fastly closed 10 years ago without proper discussion: https://github.com/minetest/minetest/issues/73

If you ask I can prepare an example.

**Comment by lhofhansl** [comment]
Call me old-fashioned, but I prefer it as is... At least for IrrlichtMt, which I build separately.

Though I do not feel strongly about this.

**Comment by sfan5** [comment]
IrrlichtMt would make sense for a submodule given how tightly integrated it is but we plan to merge that into MT anyway.

Minetest Game would not because there is no "this commit of X only works with that commit of Y" relationship (which submodules enforce). Minetest Game is also not a strict requirement of the engine, just something *most* people want.

**Comment by TamaMcGlinn** [comment]
why would you plan to merge irrlicht into minetest? I'm here because I am actually trying to build an old version of minetest and I have to manually hunt by dates for the correct irrlicht; I'd be happy to do this submodule change for you, it's really trivial to do.

**Comment by wsor4035** [comment]
closing this as minetest no longer ships with minetest game, and irrlichtmt has been merged into minetest
