### ISSUE TITLE
Version Bug

### ISSUE THREAD

**Issue by souuz** [minetest/minetest#13033]
On my school server when i log on with an outdated minetest version, server crashes please help

**Comment by souuz** [comment]
Basically I join the server with an outdated version, and it crashes about one tenth of a second after displaying an error: your minetest version is outdated. Please update your game. This is only a problem with a mod as i can join other servers without said problem.

**Comment by rubenwardy** [comment]
You need to update your client to join that server. The server isn't crashing, it's saying you can't join because your client is too outdated
