### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by FazziCLAY** [minetest/minetest#13041]
# Minetest version
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  393
  Current serial number in output stream:  394

##### OS / Hardware

Operating system: Linux
CPU: intel x64

GPU model:
OpenGL version:

##### Steps to reproduce
Open

**Comment by FazziCLAY** [comment]
uname --all
Linux fazzi-pc 5.15.0-56-generic #62~20.04.1-Ubuntu SMP Tue Nov 22 21:24:20 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by SmallJoker** [comment]
When exactly does this error happen? Directly on startup or when you start a game (i.e. open a world)?

Rename `/.minetest/minetest.conf` to something else to start Minetest with the default configuration. If Minetest still does not want to start, check `glxinfo | grep "OpenGL version string"` / `glxgears` to make sure that you actually have working OpenGL libraries installed.

**Comment by fluxionary** [comment]
googling for `Major opcode of failed request: 152 (GLX)`:

* https://stackoverflow.com/questions/9694540/opengl-rendering-context-produces-opcode-of-failed-request-152-glx-mesa-8-0

which roughly correlates to my experience w/ similar errors, which usually were generated when using incompatible kernels and graphics drivers.

**Comment by FazziCLAY** [comment]
@SmallJoker
> When exactly does this error happen? Directly on startup or when you start a game (i.e. open a world)?

just installed, first cold start



The problem solved itself, coincidentally, the NVidia driver was updated in this session (auto-update in lubuntu).
After a simple reboot, the problem is solved
