### ISSUE TITLE
Switch between main menu tabs with Meta+number

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#13042]
## Problem

There are many users including myself who are more keyboard users. 
## Solutions

It would more convenient for these users if it was possible to switch between main menu tabs with Meta(a predefined key in Settings) and a number. For example 1 for the first tab from left.

## Additional context

Meta could be Alt by default and changeable via settings.

**Comment by Zughy** [comment]
I wouldn't personally bother, considering that the intent is to get rid of the current main menu (especially the tab system)

**Comment by farooqkz** [comment]
It's 2025 and we are still using the tab based system :)
