### ISSUE TITLE
(Question) should Minetest change some /* */ to //?

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13044]
Example: https://github.com/minetest/minetest/blob/aa2fdc6ef6300f6b6683f96305bb1d9e63ba8ebb/src/client/mesh_generator_thread.cpp#L39
https://github.com/minetest/minetest/blob/aa2fdc6ef6300f6b6683f96305bb1d9e63ba8ebb/src/client/mesh_generator_thread.cpp#L40
https://github.com/minetest/minetest/blob/aa2fdc6ef6300f6b6683f96305bb1d9e63ba8ebb/src/client/mesh_generator_thread.cpp#L41

will Minetest change
/*
Hello!
*/
to //Hello! ?

**Comment by Zughy** [comment]
Irrelevant, closing
