### ISSUE TITLE
Question: Imitating Minecraft Mapgen?

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13056]
### Question
Is it possible to recreate Minecraft's terrain generation in the Minetest engine?

Say, for instance, that I want to recreate the Beta 1.7.3 terrain. Would it be possible to recreate the "Glacier" seed almost perfectly? I am aware that it would probably have a different number to Minecraft's, but still, is such a thing possible?

If not, how close can you possibly get to recreating Minecraft's terrain? Which things are missing that prevent recreating it fully? Would there be copyright issues with copying terrain generation?

**Comment by rubenwardy** [comment]
Sure it's possible, but it wouldn't be very legal and reverse engineering Minecraft isn't a goal of Minetest

**Comment by sfan5** [comment]
Yes.
