### ISSUE TITLE
Windows 7 report [Success]

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest#13065]
https://github.com/minetest/minetest/releases/download/5.6.1/minetest-5.6.1-win64.zip
OS: Windows 7 SP1 64-bit.
I have launched and get main menu. I did not find issues in main menu.

Update: I have created new world with default settings and started new game. Success.
![screenshot_20221223_01](https://user-images.githubusercontent.com/24779886/209337171-6e5ad36d-c3a6-48b2-af2e-a44ff7186868.png)

Seems you can add Windows 7 to supported OS.

**Comment by appgurueu** [comment]
The core devs probably don't *want* to add Windows 7 to the list of supported OS's, because they can't or don't want to provide explicit support for it. This doesn't mean that you can't try to (and succeed in) running Minetest on Windows 7; it just means you're on your own if you do.

**Comment by JeanPaulLucien** [comment]
@appgurueu , I would provide testing for Windows 7, but if you don't need that I will not do.

**Comment by appgurueu** [comment]
> @appgurueu , I would provide testing for Windows 7, but if you don't need that I will not do.

The problem with providing support is not so much the testing as the resulting required maintenance (e.g. bugfixing) efforts.

**Comment by JeanPaulLucien** [comment]
> as the resulting required maintenance (e.g. bugfixing) efforts.
Windows 7 is well-known and stable OS. All support is "do not break". I contribute by coding if have a reason. If repository owners do not want accept info from Windows 7, I can't help.

Website:
> **Works** on Windows 8, 8.1 and 10. 
If I trusted, I was not here.
