### ISSUE TITLE
Multiple Textures For One Mesh

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#13067]
## Problem

I am trying to make a mesh in Blockbench which uses two seperate textures to get the full texturing, but it seems impossible to get said mesh to use both textures in-game. I can only seem to define one texture in the tiles, and trying to define more than one texture in the tiles just makes it use the first one that's listed.

## Solutions

Make it possible for a mesh to use multiple seperate texture files at once.

## Additional Context

I have a brewing stand mesh named `brewing_stand_000.obj` that I want to texture for MineClone 2, but `tiles = {"mcl_brewing_base.png", "mcl_brewing_side.png"},` doesn't seem to use both textures, only the first one that's defined.

**Comment by appgurueu** [comment]
Pretty sure multiple tiles can be specified just fine. Provide more details please.

**Comment by Zughy** [comment]
I'm still pretty sure that you can do it just fine

**Comment by Desour** [comment]
Minetest supports wavefront obj with multiple textures. You just have to use `g <groupname>` to put the faces into different groups.
You're just having issues with your mesh editor application.

**Comment by appgurueu** [comment]
> > Minetest supports wavefront obj with multiple textures. You just have to use g  to put the faces into different groups.
> > You're just having issues with your mesh editor application.
> 
> How exactly do I put the faces into different groups, then? I am not exactly good with these kinds of things.

Not a Minetest issue - this issue ought to be closed; you can ask elsewhere (please provide the model and the steps you went through to obtain it when asking).

**Comment by MrRar** [comment]
Maybe open and export the .obj file in blender. Check Material Groups when exporting the .obj file from Blender.
Below I have two cube examples. The first one won't work. The second one will work (I didn't test).

```
# Blender v2.93.5 OBJ File: ''
# www.blender.org
mtllib untitled.mtl
o Cube
v 1.000000 1.000000 -1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 1.000000
vt 0.375000 0.750000
vt 0.625000 0.750000
vt 0.625000 1.000000
vt 0.375000 1.000000
vt 0.375000 0.000000
vt 0.625000 0.000000
vt 0.625000 0.250000
vt 0.375000 0.250000
vt 0.125000 0.500000
vt 0.375000 0.500000
vt 0.125000 0.750000
vt 0.625000 0.500000
vt 0.875000 0.500000
vt 0.875000 0.750000
vn 0.0000 0.0000 1.0000
vn -1.0000 0.0000 0.0000
vn 0.0000 -1.0000 0.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn 0.0000 1.0000 0.0000
usemtl Material
s off
f 4/1/1 3/2/1 7/3/1 8/4/1
f 8/5/2 7/6/2 5/7/2 6/8/2
f 6/9/3 2/10/3 4/1/3 8/11/3
f 2/10/4 1/12/4 3/2/4 4/1/4
f 6/8/5 5/7/5 1/12/5 2/10/5
usemtl Material.001
f 1/12/6 5/13/6 7/14/6 3/2/6
```


```
# Blender v2.93.5 OBJ File: ''
# www.blender.org
mtllib untitled.mtl
v 1.000000 1.000000 -1.000000
v 1.000000 -1.000000 -1.000000
v 1.000000 1.000000 1.000000
v 1.000000 -1.000000 1.000000
v -1.000000 1.000000 -1.000000
v -1.000000 -1.000000 -1.000000
v -1.000000 1.000000 1.000000
v -1.000000 -1.000000 1.000000
vt 0.375000 0.750000
vt 0.625000 0.750000
vt 0.625000 1.000000
vt 0.375000 1.000000
vt 0.375000 0.000000
vt 0.625000 0.000000
vt 0.625000 0.250000
vt 0.375000 0.250000
vt 0.125000 0.500000
vt 0.375000 0.500000
vt 0.125000 0.750000
vt 0.625000 0.500000
vt 0.875000 0.500000
vt 0.875000 0.750000
vn 0.0000 0.0000 1.0000
vn -1.0000 0.0000 0.0000
vn 0.0000 -1.0000 0.0000
vn 1.0000 0.0000 0.0000
vn 0.0000 0.0000 -1.0000
vn 0.0000 1.0000 0.0000
g Cube_Cube_Material
usemtl Material
s off
f 4/1/1 3/2/1 7/3/1 8/4/1
f 8/5/2 7/6/2 5/7/2 6/8/2
f 6/9/3 2/10/3 4/1/3 8/11/3
f 2/10/4 1/12/4 3/2/4 4/1/4
f 6/8/5 5/7/5 1/12/5 2/10/5
g Cube_Cube_Material.001
usemtl Material.001
f 1/12/6 5/13/6 7/14/6 3/2/6
```
