### ISSUE TITLE
Chat messages sent by mods must be editable

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#13060]
## Problem

Mods use the chat system and `minetest.chat_*` to send message to all or specific players. But these messages are not editable and if the content is changed shortly after the message was sent, the mod will have to send another message.

## Solutions

`minetest.chat_send_all()` and `minetest.chat_send_player()` must return an object with which editing the sent message after it was send should be possible.

## Alternatives

The functions could also return a unique ID and there could be another function to edit a sent message given its ID.

## Additional context

The mods might not want to edit the message if a non trivial amount of messages are sent after this message, we need a solution for that also.

**Comment by sfan5** [comment]
What's the usecase for changing the content of a message after it was sent?

**Comment by farooqkz** [comment]
Imagine an event has happened and you want to tell all or some players and another related event happens while no other message has been sent in the chat. It will be nice if you could edit the sent message instead of sending a new one. Better UX.

**Comment by qwerty123a2** [comment]
CTF says if the flag is dropped or stolon in a hud in the top right-Conner

**Comment by farooqkz** [comment]
> CTF says if the flag is dropped or stolon in a hud in the top right-Conner

Nope. That HUD place only shows who has/have the flag(s). In the chat it says if a plan has been taken or dropped.
