### ISSUE TITLE
API docs: Build using GitHub and host under api.minetest.net

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#13072]
Currently lua_api.txt gets generated into a pretty HTML documentation hosted by Gitlab pages, available at https://minetest.gitlab.io/minetest/. However, I think it would be better if it existed under api.minetest.net, it'd be shorter, easier to remember and more intuitive (ah, it's the API documentation!) compared to previously.  [Gitlab pages does allow you to host sites under a custom domain](https://docs.gitlab.com/ee/user/project/pages/custom_domains_ssl_tls_certification/), just like Github.

**Comment by celeron55** [comment]
Setting up api.minetest.net to point to that does make sense to me.

It seems to be just a matter of adding the subdomain info to Gitlab, getting the verification code and then adding the CNAME and TXT DNS records. Is this correct?

**Comment by rollerozxa** [comment]
Yes, that would be correct I think.

**Comment by rubenwardy** [comment]
This requires moving to using GitHub Workflows instead. See https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/
