### ISSUE TITLE
Minetest client should expose an API to control the player

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#13070]
## Problem

Currently there is no separate well supported library for creating Minetest bots(Program-controlled clients). I think it's a good idea that the Matrix client expose an API(UDS or TCP/IP) to control player actions with this API as well as getting information from the environment the so called bot is.

## Solutions

Define an API to control client actions with and to get data about environment from it. Optionally, there could be an authentication method for clients connecting to this API.

## Alternatives

Defining and implementing an API would be too much work. Another possible solution is an endpoint with which one connected client could send and receive data to the server on the real client's behalf. This way bot-developers will have to learn the protocol but at least they can see how their bot behaves while the real client is doing the rendering job and possibly do some stuff manually.

## Additional context

It is obvious that this API exposure must be disabled by default. If it is to be enabled, it must listen to a UDS or a TCP or UDP port on localhost. Listening on an interface other than localhost must have authentication by default.

Edit: 
There can be usecases other than botting. For example a SpeechRecognition program to send whatever the player says to chat.

**Comment by qwerty123a2** [comment]
you can use sockets

**Comment by fluxionary** [comment]
i remember someone pointing me at a "programmable" client or client-side proxy at one point, but i've lost my notes on it. personally i've used [minetest go](https://github.com/minetest-go/minetest_client.git), which doesn't provide much an API currently, but does allow you to create real links client connections to a server for e.g. load testing.

as a point of reference, there's also the [irc_commands](https://content.minetest.net/packages/ShadowNinja/irc_commands/) mod, which allows players to "log in" from IRC and issue commands to the server, though it has some serious security bugs.

**Comment by rubenwardy** [comment]
This is a duplicate

An API to make bots is out scope for the Minetest project. This is something for third party project, see Dragonfire Hydra or various libraries (ie: minetest-go) available for this

**Comment by rubenwardy** [comment]
Duplicate of #13026

**Comment by farooqkz** [comment]
Bots are just one usecase. There can be other usecases like the one I've mentioned. Also CSMs could be implemented in this way with more flexibility.

**Comment by farooqkz** [comment]
ping @rubenwardy

**Comment by appgurueu** [comment]
This could be useful for writing proper in-game tests. Currently these tests pretty much have to be conducted manually.
