### ISSUE TITLE
Client/Server discontinuous movement functions

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13083]
I brought that up a few times before...

We have various places where we break client and server coordinated movement and collision prediction (i.e. client and server get out of sync and then has to be "reset", most visibly seen with entities/mobs or when attached).

As is, a server `asyncrunstep` frequently takes more than 0.5s and often more 2s. This is a problem by itself, and has gotten better in the past releases. A significant source of the lag remains Lua MapGen.

These are the three most egregious:
https://github.com/minetest/minetest/blob/89e7f72c929fbeef8ad755bc85db22ae6102787d/src/client/client.cpp#L379
https://github.com/minetest/minetest/blob/89e7f72c929fbeef8ad755bc85db22ae6102787d/src/server.cpp#L569
https://github.com/minetest/minetest/blob/89e7f72c929fbeef8ad755bc85db22ae6102787d/src/collision.cpp#L242

These should be removed or increased or we should find different solutions.

I had all these removed locally for months... MT still predicts movement and collisions correctly (as that takes dtime into account) and *significantly* reduces visible jumps on the client as the integration of acceleration, speed, position is mostly accurate between server and client - especially since we improved the integrals, where step size is less of a source of inaccuracies, as long as it is continuous.

**Comment by grorp** [comment]
I've left a review on #13093, it needs a response from lhofhansl now.

**Comment by rubenwardy** [comment]
linked PR
