### ISSUE TITLE
Per user hand digging speed

### ISSUE THREAD

**Issue by MrRar** [minetest/minetest#13086]
## Problem

There is no way to overwrite the tool capabilities of the hand tool per user.

## Solutions

There should be an API or something to set tool capabilities of the hand tool per user.

## Alternatives

One thing you could do is get the tool capabilities from the mesh hand node. The problem with this is that I think the mesh hand node should be replaced with something better. It is weird and hacky and once you get beyond hello word skins mods it becomes a problem. Also it's a node. I'm not sure nodes can have tool capabilities. It would also create a small hassle because you have to update the tool capabilities every time the skin changes.

## Additional context

MineClone2 is trying to make a /gamemode command. This command can be used to switch a player to creative or survival mode. In the creative mode fast digging should be used. Problem is, you can overwrite the tool capabilities of the hand tool but that will apply to all players.

MineClone2's current solution is to delete the node the user punches. This does not work well: https://git.minetest.land/MineClone2/MineClone2/issues/3171

**Comment by Zughy** [comment]
Just override the hand inventory list:
https://github.com/minetest/minetest/blob/89e7f72c929fbeef8ad755bc85db22ae6102787d/doc/lua_api.txt#L3331-L3333

**Comment by MrRar** [comment]
It doesn't work.

player:get_inventory():set_stack("hand", 1, "mcl_tools:pick_netherite")

Now my hand looks like a pickaxe but it does not dig like a pickaxe.

Please reopen this issue.

**Comment by Zughy** [comment]
Have you tried on DevTest to see if it's a MT issue or a MCL2 issue first?

**Comment by MrRar** [comment]
> Have you tried on DevTest to see if it's a MT issue or a MCL2 issue first?

No. Now I have. It works in DevTest. The issue is that MCL2 registers the hand tool ":". Apparently MT gets the hand capabilities from the hand tool if it is registered else it gets them from the mesh hand node. It also does not matter that the mesh hand node is not actually a tool.

This is not a Minetest issue sorry!

**Comment by SmallJoker** [comment]
Related: (how to overwrite the `"hand"` tool dynamically)
https://github.com/minetest/minetest/blob/89e7f72c929fbeef8ad755bc85db22ae6102787d/doc/lua_api.txt#L6877-L6889
