### ISSUE TITLE
Fragmentation kills perfomance 

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest#13085]
For desktop systems.

## Problem

Minetest is many small and tiny files. Perfomance will decrease with percent of fragmentation.

## Solutions

Package files. It should be visible for system like solid big files.

**Comment by rubenwardy** [comment]
The missing context is that Windows is slow when you have lots of small files, due to the overhead of each one

This may impact load times but won't during runtime, as Minetest loads things into memory

**Comment by JeanPaulLucien** [comment]
@rubenwardy just check HDD's tests. Reading speed is less for small files and random access.

**Comment by SmallJoker** [comment]
Related PR: https://github.com/minetest/minetest/pull/11567
Related issue: https://github.com/minetest/minetest/issues/10598 (not directly about small files but cleaning them up)

**Comment by Desour** [comment]
Wrong approach.
It makes no sense guessing that some thing causes performance issues before profiling.
And then, the issue described here is also not even a very minetest-specific thing. This is just worthless.

**Comment by JeanPaulLucien** [comment]
I watch how in-game world loads from HDD. The world exists at front of player, but at back... The void.

> some thing causes performance issues before profiling.
No quessing, just physics and experience of other developers: ID Software, Rockstar Games, Valve, Blizzard... Seriously, **all** is small and tiny files. 
@SmallJoker posted link to PR about database. You stores languages files inside files less 1 KBs. Replace language files by database is perfect way.

**Comment by fluxionary** [comment]
i know this is closed, but i was typing a response and had to AFK for a few hours. 

@JeanPaulLucien 
1. what exactly do you think should be packaged? the files that come w/ the game engine? mods/modpacks/games? 
2. what sort of performance benefit would you expect from doing that? e.g. server-side, client-side, network? 

minetest mostly does file access during server initialization, and i don't think loading individual files into memory is anywhere near the biggest contributor to startup time. and i very much agree that actual performance metrics should be part of any performance-related request. even if a mechanic is "industry standard", minetest has a very different architecture than most "industry standard games".
