### ISSUE TITLE
iOS support (Via sideloading, not App Store)

### ISSUE THREAD

**Issue by fakeronan2** [minetest/minetest#13084]
A way for iOS support is to use parts of the MultiMC engine, remove the MultiMC mods and add Minetest Game and add the download center.

Since Minetest is licensed under the LGPL and MultiMC is a fork of Minetest it has the source code avaiable and is avaiable for iOS.

Not much would be done on a Apple PC besides compilation and packaging and a Apple PC is also needed for the MacOS port of Minetest.

**Comment by Zughy** [comment]
iOS is not planned for now: https://irc.minetest.net/minetest-dev/2022-12-28#i_6043139

**Comment by fakeronan2** [comment]
*Craft not MC
