### ISSUE TITLE
Ratings in Content Browser

### ISSUE THREAD

**Issue by xeruf** [minetest/minetest#13094]
## Problem

When initially browsing Minetest, it took me a while to find a playable game.
There is so much that looks interesting in the ContentDB, but few are actually playable, making a bad impression

## Solutions

As a first step, one could have an indication of status (e.g. Early Dev, Playable, Stable, Maintenance) and a percentage and number of reviews as indicator, and sort by those.
This way new players immediately see some of the best games.
Some I even only discovered via the Arch AUR.

**Comment by Zughy** [comment]
#6733

**Comment by rubenwardy** [comment]
Duplicate of #11186
