### ISSUE TITLE
Perfomance: maximum distance for small and tiny objects.

### ISSUE THREAD

**Issue by JeanPaulLucien** [minetest/minetest#13090]
## Problem

Game draws objects like a grass too long distance. I really don't see that grass correct, because https://github.com/minetest/minetest/issues/13087. Grass like spot. But full size texture and eat my hardware resources.

My maximum distance is 200 meter. I don't know why nothing for 210 and more.

## Solutions

Limit maximum distance for objects like a grass, flowers, bees... 140 meters.

**Comment by appgurueu** [comment]
Grass/flowers and other plants are nodes with the "plantlike" drawtype and objects. Drawing grass requires 2 quads or 4 tris - that really isn't much, esp. if batched with the other faces of a mapblock. There is no reason to treat plantlike nodes any different than regular nodes (except that perhaps face batching optimizations aren't quite applicable to them). It'd be odd if, say, dirt or a sign were clearly visible but plantlike nodes weren't.

Objects are a different story; currently their rendering is rather inefficient, but their maximum distance is also limited (and IIRC there even are different limits for nodes and entities).

Close this already @minetest/triagers.
