### ISSUE TITLE
No Minetest Versions Before 0.4.8?

### ISSUE THREAD

**Issue by FossFanatic** [minetest/minetest#13095]
## Problem

There seems to be no downloads available for any Minetest versions before 0.4.8 in the releases.

## Solutions

Make all Minetest versions before 0.4.8 available in the releases as well.

## Alternatives

Give me a link to some sort of archive of Minetest versions before 0.4.8.

## Additional context

Some of the Minetest versions before 0.4.8 might contain certain files that I might find useful.

**Comment by Zughy** [comment]
As people [previously suggested you](https://github.com/minetest/minetest/issues/13056#issuecomment-1358243144), these questions are better suited for the forum, or even for IRC/Matrix/Discord. Please think twice before posting

**Comment by rollerozxa** [comment]
Actually answering the question asked, [celeron55 has an archive](http://packages.8dromeda.net/minetest/) of old versions that goes all the way up to 0.4.7. Of course, every version is also available in source form in the git history too.
