### ISSUE TITLE
Autoconnect to server always fails with connection error

### ISSUE THREAD

**Issue by TamaMcGlinn** [minetest/minetest#13097]
##### Minetest version
```
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/share/minetest"
STATIC_LOCALEDIR="/share/locale"
```

##### OS / Hardware

Operating system: Ubuntu 20.04
CPU: Yes, definitely have one

##### Summary
I am trying to use the appropriate flags to automatically connect to a server, for example `minetest --address your-land.de:30000 --name MyName --password MyPassword --go`

If I remove the --go flag, it automatically selects the right server and then I can press connect and it connects, so clearly the server is up and running just fine, and the password is also correct, but when I try it with the --go flag, I get:

```
ERROR[Main]: Couldn't resolve address: Name or service not known
```

**Comment by y5nw** [comment]
You need to specify the port in a separate `--port` argument, e.g. `--address example.com --port 30000`

I use a similar setup script for my MT client and do not have any problem with it.

**Comment by TamaMcGlinn** [comment]
Thank you, that works!
