### ISSUE TITLE
Cool

### ISSUE THREAD

**Issue by Kuwtzrk** [minetest/minetest#13109]

**Comment by ericsomto** [comment]
Did you forget to take your meds ?

**Comment by Kuwtzrk** [comment]
Nah, im just new and I’m. Trying to learn 😂😂🥲🙃😂 sorry if I did
anything wrong but can I  can you help me pls im lost

**Comment by MathPlusEnglish** [comment]
Click the close issue button to close this issue.

**Comment by fluxionary** [comment]
> Did you forget to take your meds ?

this "issue" is clearly a poorly thought out experiment by a neophyte, there's no need to respond nastily. though, i'm surprised the issue hasn't been closed by a core dev already.
