### ISSUE TITLE
Colorfacedir and Nodeboxes

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#13107]
It is broken, the color does not apply.

Test:

1) Put a nodebox.
2) Apply a color.

**Comment by jeremyshannon** [comment]
Seems to work here, I swapped our backpacks from colorwallmounted to colorfacedir to test, and 
it is colored, though It's applying the wrong color now. (Exile's dye code expects colorwallmounted)
What version is this?

**Comment by runsy** [comment]
> Seems to work here, I swapped our backpacks from colorwallmounted to colorfacedir to test, and it is colored, though It's applying the wrong color now. (Exile's dye code expects colorwallmounted) What MT version is this you're running?

5.7-dev

**Comment by jeremyshannon** [comment]
Huh, I just tried it with the very latest MT revision off git and colorfacedir still works, my backpack turned blue. Are you sure you've got the palette entry in your node definition and param2 all set right? Are you setting the metadata on the item so color is preserved in inventory?
 Check Exile's backpacks/init.lua for working example code. Or I guess devtest probably has some, right?

**Comment by runsy** [comment]
colorfacedir only accepts 8 colors. I use a 256 pixel palette, could this be an issue?

**Comment by runsy** [comment]
> Huh, I just tried it with the very latest MT revision off git and colorfacedir still works, my backpack turned blue. Are you sure you've got the palette entry in your node definition and param2 all set right? Are you setting the metadata on the item so color is preserved in inventory? Check Exile's backpacks/init.lua for working example code. Or I guess devtest probably has some, right?

colorfacedir only accepts 8 colors. I use a 256 pixel palette, could this be an issue?

**Comment by runsy** [comment]
Finally I use a palette with only uses 8 colors (pixels) and it works.

Thanks jeremy!

Closed.
