### ISSUE TITLE
Some UX Minecraft Parity Issues

### ISSUE THREAD

**Issue by xeruf** [minetest/minetest#13103]
- Crafting grid: Drag-dropping in grid to split evenly the plus double-click to pick up a full stack like in minecraft - see also https://github.com/minetest/minetest/issues/9456 and https://github.com/minetest/minetest/issues/5374

## Furnace (this is from LOTT, maybe modpack-specific issue)
- Shift-clicking from the furnace does not work - generally taking items from the furnace is a bit janky (sometimes I take something and can't swap it with an occupied inventory slot)
- Mining a furnace that is not empty should just drop the items, not make it unmineable

**Comment by Zughy** [comment]
About the former: I'm afraid I didn't get it

About the latter: please test things in Minetest Game (or even better DevTest, but I don't think there is a furnace there), we need to understand if it's game-related. In general, as I said previously, one issue per.. issue helps us a lot

**Comment by iliekprogrammar** [comment]
- zughy, the issues OP linked sufficiently explains how Minecraft's stack splitting works. this point can be considered a duplicate

- point #2 and #3 is game-related. try posting to LOTT's [issue tracker](https://github.com/minetest-LOTR/Lord-of-the-Test/issues/) first.

**Comment by xeruf** [comment]
There is still this unique, definite issue left: Double-click in the inventory interface to pick up a full stack like in minecraft.

For the others see: https://github.com/minetest-LOTR/Lord-of-the-Test/issues/183

**Comment by NathanSalapat** [comment]
You can pick up a full stack with single clicking, why would you want to have to click more times to do the same thing?
Also keep in mind this isn't minecraft, and doesn't aim to be.

**Comment by xeruf** [comment]
>  Also keep in mind this isn't minecraft, and doesn't aim to be.

I know, but one can take inspiration for better UX :)
In Minecraft, double-clicking an item stack collects all items of that type from across the (open) inventory, including chests or crafting grids, up to the maximum stack size.
