### ISSUE TITLE
Doesn't remember maximized window settings

### ISSUE THREAD

**Issue by xeruf** [minetest/minetest#13101]
##### Minetest version

```
5.6.1
```

##### OS / Hardware

Operating system: Windows & Linux

##### Summary
When I start the game on WIndows, it opens windowed, even when I opened it fullscreen beforehand and it was set to remember window size (the default).

~~Furthermore, when I am about to host a server, the username input field reverts whenever I change anything (announce, select a world, etc.) which can be quite frustrating.~~ EDIT by Zughy: see first comment

Related to https://github.com/minetest/minetest/issues/6733

**Comment by Zughy** [comment]
Hello, I can confirm both bugs, but I need you to open a second issue for the latter: having more problems raised in a single issue doesn't help navigation

**Comment by sfan5** [comment]
Oh actually this is a duplicate of #13101
