### ISSUE TITLE
server_description not shown in manually added servers

### ISSUE THREAD

**Issue by BobOmbuzal** [minetest/minetest#13106]
##### Minetest version
```
Minetest 5.6.1 (Linux)
Using Irrlicht 1.9.0mt8
Using Lua 5.1.5
```

##### Summary
server_description = foo
is set in dedicated server conf, but it is not shown in the client's favorite list

##### Steps to reproduce
configure a server, add IP to client

**Comment by sfan5** [comment]
Server descriptions are only available for servers on the public list.
Please be more specific in the steps you take to reproduce, what you see and what you expect to see.

**Comment by BobOmbuzal** [comment]
OK then this is a feature request:
When i'm listing my own non-public server, that i added manually, i would like to see the description.
The client could update the description from the server when connecting, or when clicked in the list?
Just a small thing, not really important, was just wondering why the public servers have descriptions and mine doesn't, now i know.

**Comment by Zughy** [comment]
@BobOmbuzal please open a new issue as a "Feature Request", so that reading the first couple messages won't generate any confusion. Closing here
