### ISSUE TITLE
Quick Move

### ISSUE THREAD

**Issue by BeastThe** [minetest/minetest#1311]
Minetest Should add a quick move option where you can press "y" on a item in a a chest and it will be put in your inventory same with a furnace. Also it should be made where is some thing in your inventory and you want to quick move something from your inventory you can press "y" on it,Then if you press "y" on coal or fuel it will go to the fuel slot in the furnace, If you press "y" on something that need to be Smelted it will go to the slot that ores/other things get smelted. And so on and include thing from mods like all Chest mods Locked furnace and Machines/ And any thing that you put thing in to.An Example is https://www.youtube.com/watch?v=u5Ohl6FMqRg

**Comment by nerzhul** [comment]
Duplicate with #521
