### ISSUE TITLE
Bad UX for Username field upon server hosting

### ISSUE THREAD

**Issue by xeruf** [minetest/minetest#13114]
##### Minetest version

```
5.6.1
```

##### OS / Hardware

Operating system: Windows & Linux

##### Description

when I am about to host a server, the username input field reverts whenever I change anything (announce, select a world, etc.) which can be quite frustrating.

supersedes https://github.com/minetest/minetest/issues/13101

**Comment by NathanSalapat** [comment]
Welcome to formspecs. Any text input field is reset when a formspec is updated, in the current state of things, I don't believe anything can be done about this issue.

**Comment by Wuzzy2** [comment]
This can be fixed without changing the formspec system itself, I believe. Clicking a checkbox is a formspec event and I believe this also sends all text fields. So the solution is to catch the text field and then use that as the text field value on the next formspec value.

**Comment by grorp** [comment]
Fixed by #13685.
