### ISSUE TITLE
Mac: state in the README that running the game from the terminal doesn't work

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13116]
See https://github.com/minetest/minetest/issues/5608#issuecomment-1339672042

(unsubscribing)

**Comment by Zweihorn** [comment]
https://github.com/minetest/minetest/issues/5608#issuecomment-1375489913

**Comment by rubenwardy** [comment]
Multiple users have come across this problem, mostly those that self-compile not those that use macports. From what I understand, you can run from the terminal as long as you run the .app and not the raw binaries

**Comment by Zweihorn** [comment]
My review and reply was addressing [MacPorts](https://ports.macports.org/port/minetest/) explicitly. It should be clear I was rather neutral on other builds and other findings.

> Multiple users have come across this problem, mostly those that self-compile not those that use macports. From what I understand, you can run from the terminal as long as you run the .app and not the raw binaries

THX for the extra clarification.

**Comment by rollerozxa** [comment]
I managed to get Minetest to run from the terminal when building from source. When RUN_IN_PLACE=0 the binary is in the wrong place to detect the in-source engine data and needs to be moved up one step, but works fine when RUN_IN_PLACE=1 to run it where it's outputted to. I'm doing it in an x86-based macOS VM, so I'm unsure if there's anything different on ARM macs that would make it not work there.

**Comment by Zweihorn** [comment]
THX - @rollerozxa  again and ref https://github.com/minetest/minetest/issues/13121#issuecomment-2114731021

Did not check myself due to current lack of resources. Thus would propose to be happily closed for the benefit of the doubt and regarding the new MT version available.
