### ISSUE TITLE
finishgen: Couldn't grab block we just generated

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13110]
##### Minetest version

```
Minetest 5.6.1 Android
```

##### OS / Hardware

Operating system: Android 6.0.1 (SDK/API lv 23)
CPU: MediaTek

GPU model: Mali
OpenGL version: ES 3.1

##### Summary

![Screenshot_20230103-154428](https://user-images.githubusercontent.com/76146430/210325192-7110c15f-0f57-45dd-8e31-48790a0c0541.png)
I see these error text keep appearing after some seconds, not only this world but other too and i dont see something like this happen in 5.5 or 5.4
##### Steps to reproduce

i dont know, try:
1. Install Minetest 5.6.1 on Android
2. Create a world and join
3. wait some seconds... (if still not, try build something)

**Comment by TurkeyMcMac** [comment]
Could you enable `enable_mapgen_debug_info`, set `debug_log_level` to `trace`, reproduce the error message, then share your `debug.txt` here?

**Comment by oong819** [comment]
[debug.txt](https://github.com/minetest/minetest/files/10341803/debug.txt)
here, the world i used to test are "bug test AGAIN (no floatland"

**Comment by mieu12** [comment]
This happens to me randomly. I also tested with Creatures-Mob-Engine and it seemed when I spawned many sheep I got this error. This info maybe useless as it could be caused by something else.

**Comment by fluxionary** [comment]
i'm not volunteering to look after this issue, but in general, do core devs have any advice for emulating (minetest on android) on linux, for those of us who don't have any devices that can run it natively?

**Comment by TurkeyMcMac** [comment]
Could you try reproducing the issue with this build then post the log? https://github.com/TurkeyMcMac/minetest/actions/runs/3875088290

**Comment by oong819** [comment]
sorry i ran out of storage

**Comment by Zughy** [comment]
Can't reproduce on 5.7, fairphone (I've also tried to spawn a lot of sheep)
