### ISSUE TITLE
Clickable links (improve copy/paste)

### ISSUE THREAD

**Issue by Ryan-Nolan** [minetest/minetest#1312]
Not entirely sure how this would be done. but ive lost count how many people have been annoyed at not being able to click on a link from within the game. even copying and pasting is near impossible.

Is it possible that either, Links become click-able or if that's not possible, maybe make it that when links are clicked they are copied to a users clipboard...

Nearly all server owners have  forums and websites, would be good if people didnt need to hand type the url.

**Comment by MoNTE48** [comment]
+1! It would be very convenient!

**Comment by C1ffisme** [comment]
:+1:

**Comment by 0-afflatus** [comment]
:+1: if it is indeed possible.

**Comment by paramat** [comment]
Can't see a need for this, and link addresses tend to change often.

**Comment by MoNTE48** [comment]
@paramat, A link to the site in the server description, a link to minetest.net, minetest wiki, etc. changes every day! WoW

**Comment by rubenwardy** [comment]
There is of course a security issue with this. A good compromise would be to make it possible to highlight and copy chat text somehow. Maybe when opening the pause menu you could do this.

**Comment by paramat** [comment]
Doesn't seem worth the security risks, it's not hard to enter a website address.

**Comment by Lillecarl** [comment]
@paramat https://arstechnica.com/science/2017/09/fda-slams-epipen-maker-for-doing-nothing-while-hundreds-failed-people-died/ Sure you type this URL manually into the browser while the chat window keeps scrolling by

**Comment by ExeterDad** [comment]
Either of rubenwardy's solutions would be excellent. I'm getting a constant barrage of links thrown into chat to "the perfect skin" and opt to disregard as it's just too much work. Making a mod that opens a "buffer" of previous chat in formspec to be selected and copied seems to work. It would be trivial to include something like that in core.

**Comment by paramat** [comment]
Lillecarl good point, i didn't realise this was for links in chat. I'd support being able to copy text.
Does the fullscreen chat window allow scrolling back to earlier chat?

**Comment by paramat** [comment]
:-1: But i support:

> A good, more useful, compromise would be to make it possible to highlight and copy chat text somehow.

**Comment by Ryan-Nolan** [comment]
Ive been away from the Minetest community for a good year or so now and i can see that nothing has changed with the people that have final say on these decisions.

rubenwardy suggested a very good idea that would work and addressed your security concern but that still wasn't good enough?

I'm finding it hard to understand how a dialog, warning of external links would be a security concern... how would it be any different to a user copying and pasting a piece of text. if said user is not responsible enough to read the warning then they shouldn't be on the internet.

Further more it would also open up the opportunity to potentially run the URL that was clicked through a URL scanner API to check if it is known to be malicious.

Also because this is a client thing not a server thing. you could also put an option in the client config to entirely disable this feature for those that don't want it.

**Comment by Megaf** [comment]
Clearly the community (server admins and players) and minetest developers, are totally out of sync and with different objectives.

**Comment by Ryan-Nolan** [comment]
@Megaf you are right

Although i don't know how much has changed over the last year but from what i remember...
The developers in charge of steering Minetest's development direction have never really listened to the rest of the community... its sort of like "Its not a good idea if it conflicts with their own ideology/thought process".

They hide behind "security" and "privacy" concerns.... but in reality its simply because they don't like the idea.  This request is a perfect example. the security concern was made aware by @paramat , the security concern was addressed by @rubenwardy and yet it still hangs in limbo.

The vast majority of community driven ideas face the same issue.

**Comment by rubenwardy** [comment]
Two developers responded to this request. I said yes given a warning dialog, paramat said no likely due to added complexity when copy+paste is almost as good.

Paramat isn't stubborn, he is just very wary against feature creep. He will listen to any arguments, you just need to persuade him that this feature is worth the extra code - which could be a fair amount given there's no concept of clicking chat currently.

> The vast majority of community driven ideas face the same issue.

The vast majority of community driven ideas face the issue that no one actually implements it

-----------------

I understand that there has been a big issue with community members not being represented particularly well, but I don't think it's the problem in this case.

**Comment by Ryan-Nolan** [comment]
@rubenwardy that's a pretty naive thing to say, this issue was posted in 2014 we are now in 2017 the vast majority of the comments in this post are in favor of it. not to mentions up votes so yeah i think this does fall under it.

@paramat said no even before he understood what the idea was about, and once he understood the idea at no point had he mentioned feature creep its mostly been down to the fact he doesn't like the idea and "security concerns".

> The vast majority of community driven ideas face the issue that no one actually implements it

that's more than likely because of people fearing it to be a waste of time, ive seen thousands of merge requests getting rejected over the years and yeah i understand that a portion of them are for good reason but not all.

Anyhow as things clearly haven't improved within the community my "comeback" will wait, Il check back in a few more years lol

**Comment by sfan5** [comment]
I like how the opinion of paramat apparently speaks for the entirety of the development team.
Also instead of continously complaining about how the dev team is totally out of touch, maybe do something useful and implement (or find somebody to implement) this feature.

**Comment by rubenwardy** [comment]
> Anyhow as things clearly haven't improved

I'm not sure sure if you're trolling or not. We've been working on improving on the PR rot situation by making sure the status of a PR is known. We've (or at least I've) been adopting some of the older PRs. We've gone from 160 (I think?) to 114 PRs in a few months. Paramat is well liked by server operators as he makes sure to listen to them, and avoid compatibility breakages. He is just very wary of complexity

>  that's a pretty naive thing to say, this issue was posted in 2014 we are now in 2017 the vast majority of the comments in this post are in favor of it. not to mentions up votes so yeah i think this does fall under it.

It's a relatively low number of upvotes, and there's one dev for and one dev against. 2 devs is hardly the development team, if you want to see what the actual stance is, post in #-dev.

**Comment by Ryan-Nolan** [comment]
@sfan5 like i said above i don't know how much has changed in the last year or so. 

but you all were pretty much the same and have been for years, I lost count how many time myself and so many others have got into heated debates in IRC and on GitHub over the way the Dev team handle the rest of the communities requests.

Fact is the Dev team is out of touch, they only care about what matters/interests to them(heck if i remember rightly, few years ago i was once told that "Dev team don't get paid so we do what we like or enjoy", 

I get that i do.... but when someone is promoted to an official position that's when it changes and they do whats best for the whole community not just themselves.

> maybe do something useful and implement (or find somebody to implement) this feature

yeah... few years ago i looked at those options, i came to the decision that i would be unable to do it myself because im not fluent in any of the C languages and to get somebody else to do it would cost me money that im not prepared to spend just for someone from the Dev team to knock it back because they don't like it. you want more people to contribute to the engine you need to start putting the confidence back into the community.

**Comment by Ryan-Nolan** [comment]
@rubenwardy 

> I'm not sure sure if you're trolling or not. We've been working on improving on the PR rot situation by making sure the status of a PR is known. We've (or at least I've) been adopting some of the older PRs. We've gone from 160 (I think?) to 114 PRs in a few months. Paramat is well liked by server operators as he makes sure to listen to them, and avoid compatibility breakages. He is just very wary of complexity

Like ive said multiple times, **"I've not been around for a good year or so, I don't know what the situation is at present"** in fact ive literally only just realized that your now the owner of the Minetest repo... so my opinion is based on my previous experience and also based on what ive read in my GitHub notification lately.

> It's a relatively low number of upvotes, and there's one dev for and one dev against. 2 devs is hardly the development team, if you want to see what the actual stance is, post in #-dev.

it is a relatively low number up votes, but the ratio of people in favor are higher than that of those against.

**Comment by nerzhul** [comment]
@Ryan-Nolan rubenwardy is backup owner of the repository. The real owner is @celeron55

**Comment by sfan5** [comment]
> "Dev team don't get paid so we do what we like or enjoy"

welcome to FOSS projects

> but when someone is promoted to an official position that's when it changes and they do whats best for the whole community not just themselves.

there is no explicit obligation of devs towards the community, but it's obvious that devs <i>shouled</i> handle in the interest of the community.

> just for someone from the Dev team to knock it back because they don't like it

just FYI: such a veto rule does not exist
concerns of the disagreeing devs are listened to, but generally a single 「:-1:」 can not block a whole PR.

**Comment by rubenwardy** [comment]
> you're now the owner of the Minetest repo

I'm a core developer who's also a backup owner of the organisation and repositories in case @celeron55 disappears

**Comment by Ryan-Nolan** [comment]
> I'm a core developer who's also a backup owner of the organisation and repositories in case @celeron55 disappears

> @Ryan-Nolan rubenwardy is backup owner of the repository. The real owner is @celeron55

@rubenwardy @nerzhul thanks for correcting me, still an important detail that i didnt realise.

> just FYI: such a veto rule does not exist
concerns of the disagreeing devs are listened to, but generally a single 「👎」 can not block a whole PR.

you are right... but there is a history, of features requests where 10 - 50+ none Dev members have up voted or supported an idea and because multiple Dev members don't support the idea. it gets shelved or left to go stale.

When that happens (i don't know if it happens much any more but it used to happen a lot) that's the Dev team directly ignoring the community.

@rubenwardy i genuinely hope that what you say about things improving is true but right now it still looks like "Dev's Vs the Community" anyway i think its all i have to say...

**Comment by twoelk** [comment]
I guess clickable links beyond jumping around within formspecs is too much of a can of worms than it is worth at the moment. There would have to be a lot done under the hood concerning security issues before this feature should be added. 

but a "copy to clipboard" feature that **works on all supported operating systems** is something that is really missing. 

aaaaand bashing devs hardly ever helps to get a feature done.

**Comment by SmallJoker** [comment]
Adding a dialog to confirm or deny opening the link could be quite tricky with our current formspecs, which only allow one to be displayed at a time. The previous formspec (or new incoming ones) would have to be cached as long that dialog is open.

Putting that aside, the request is good - as I've been annoyed already a few times when I couldn't simply follow a link in-game because they forgot that not all text can be marked and copied manually.
A feature like "copy to clipboard" (thanks @twoelk) is indeed quite simple, but requires an additional visual feedback to let the players know that it's in their clipboard now. Otherwise they assume it's not working at all.

**Comment by paramat** [comment]
Actually i'm not concerned about security anymore, that was just a silly comment of mine. It's because it's low priority and copypaste can ber used instead.

> i can see that nothing has changed with the people that have final say on these decisions.

No person has a final say, we decide together on dev votes.

> rubenwardy suggested a very good idea that would work and addressed your security concern

He also wrote that just copying text was 'good' and 'more useful'.

> Clearly the community (server admins and players) and minetest developers, are totally out of sync

Not so, sometimes some devs are to a degree yes.

> The developers in charge of steering Minetest's development direction have never really listened to the rest of the community

Actually we do a lot, exaggerations like this are usually written by people who disagree with the devs.

> the vast majority of the comments in this post are in favor of it.

> it is a relatively low number up votes, but the ratio of people in favor are higher than that of those against.

In the end though it's the devs that decide, taking opinions, MT priorities and their own knowledge into account. We're not a democracy, luckily.

> Fact is the Dev team is out of touch, they only care about what matters/interests to them(heck if i remember rightly, few years ago i was once told that "Dev team don't get paid so we do what we like or enjoy",

Nonsense.

>  i came to the decision that i would be unable to do it myself because im not fluent in any of the C languages

You could learn. We need more coders not more people suggesting ideas.

> you want more people to contribute to the engine you need to start putting the confidence back into the community.

We have lots of contributors, we can hardly keep up with review work.

> just FYI: such a veto rule does not exist
concerns of the disagreeing devs are listened to, but generally a single 「:-1:」 can not block a whole PR.

Yes.

> but there is a history, of features requests where 10 - 50+ none Dev members have up voted or supported an idea and because multiple Dev members don't support the idea. it gets shelved or left to go stale.

Yes, exactly as it should be, devs have the most knowledge and make the final decision. Bad ideas can be very popular with those without a deep knowledge of the code, or those who don't consider priorities and how limited dev time is (very many idea-suggesters don't, understandably).

> When that happens (i don't know if it happens much any more but it used to happen a lot) that's the Dev team directly ignoring the community.

We read every word of the discussions, it's not ignoring, just disagreeing. We're not a democracy (which would be an unbearable nightmare resulting in a mess of a game).

> i genuinely hope that what you say about things improving is true

It's not really improving because it never was as bad as you suggest.

If you dislike MT dev and are this negative and insulting, maybe you should stay well clear of it for your and our own sakes?

**Comment by paramat** [comment]
I think we can treat this as a request for 'copy to clipboard' as that seems to have more support and more usefulness.

**Comment by kilbith** [comment]
> Clearly the community (server admins and players) and **minetest developers**, are totally out of sync and with different objectives.

Just let the snotty kids and the impostors drown in their own mediocrity. The commercial forks are taking the relay.

**Comment by ExeterDad** [comment]
This issue is horribly off topic anyhow so I'll comment.
I feel a lot has changed in the last year. And from what I can see there has been a clear swing towards listening to people that actually play or maintain a server. I could go further with my observations that would back up how the devs are making efforts to work with the community, but I'll just leave it at that.

**Comment by rubenwardy** [comment]
It's worth noting that the reason that kilbith is so hostile is because somebody asked him to be nice

**Comment by kilbith** [comment]
I'm simply running for the Asshole of the Year Award. Although I already have a serious competitor...

**Comment by Megaf** [comment]
We have copy to clipboard, but it has been broken for several years already.
On Linux at times it crashes the game, sometimes the app you want to copy to/from, sometimes both. Sometimes it just doesn't work.

**Comment by twoelk** [comment]
kilbith couldn't you rather do some nice mods again? 
prove you are better at solving the features people request by writing superior code

**Comment by paramat** [comment]
I'll clarify my opinion.

The idea is fine in isolation of course.
Clicking a link in a program that isn't an internet browser and it opening a tab in your computer's browser is a luxury, i never expect a program to do this if it isn't a browser, why would it.

Coding a program to search your system for a browser and open a new tab in it is a fairly complex thing to do. Maybe if we were Mojang or a professional developer team it could be done, the pay would be incentive to do it if no dev is interested or inspired. But we have a continuous and somewhat inevitable (FOSS) severe limitation of dev time, so by necessity we have to prioritise and often not add non-essential luxury features. MT therefore is likely to be simpler than many other games.
Links are not often placed in chat, and players usually have other ways to communicate.

On the other hand, useful information that isn't internet links is often present in chat, so coding a 'copy to clipboard' feature would be much more useful, as well as being simpler to do.
So :-1: for clickable links, :+1: for sorting out 'copy to clipboard'.

**Comment by Megaf** [comment]
I think at this point most of us agree on a working copy to clipboard thing.

**Comment by CloudyProton** [comment]
>Paramat isn't stubborn, he is just very wary against feature creep. 

And Minetest is well protected against feature creep for it ...almost too well protected. If anyone wants to combat feature creep they should have a look at some of the available mods.

OT: This feature would have been beneficial on my public server where a serverguide was presented to new players which had a link to the server site url. Many of the players (especially phone/tablet users) really had no real option to follow that link unless they could memorize the whole address. Probably my own shortcoming for not pointing to a short and simple address.

**Comment by paramat** [comment]
Actually it's not feature creep i'm concerned about, i explained above my thoughts.

**Comment by that-other-guy123** [comment]
WOh eh I like

**Comment by paramat** [comment]
Copypaste discussion moved to #7830
