### ISSUE TITLE
"Undersampling" filtering option causes game to fail to render under opengl1.3

### ISSUE THREAD

**Issue by userse31** [minetest/minetest#13120]
##### Minetest version

```
5.3.0
```

##### OS / Hardware

Operating system: Debian 11.6 linux 5.10.0-20-686
CPU: (Almost certainly doesn't matter but...) Pentium M @ 1.7Ghz

GPU model:Intel 82852/82855GM
OpenGL version: 1.3

##### Summary

When running under opengl 1.3 the game fails to render when the "undersampling" option is set to a value larger then 1.

##### Steps to reproduce

1.) Insure minetest runs under opengl 1.3

2.) In the "minetest.conf" file set "undersampling" to "2" or larger.

Please note: undersampling works properly under opengl 3.0. This is not an issue with running under non-longmode (64bit) linux.

Possible solution: Issue a compatibility warning about "undersampling" when running under opengl1.3.

**Comment by TurkeyMcMac** [comment]
Could you test that the bug still exists with the most recent version of Minetest (and Irrlicht)?

**Comment by rubenwardy** [comment]
5.3 is not a supported version, please test with 5.6.1
