### ISSUE TITLE
Possible solution to stop ban evaders on servers.

### ISSUE THREAD

**Issue by mieu12** [minetest/minetest#13135]
## Problem

It is becoming more frequent with ban evaders ruining servers.

## Solutions

Add a player.txt in some folder location on that player's computer to stop them from ban evading on servers. E.g: Player_name, server name/ip:port

## Alternatives

Suggestions are welcome.

**Comment by NathanSalapat** [comment]
Nothing would prevent these people from just deleting that file.
If you are having such issues maybe look into a whitelist mod, or reduce the amount of damage a person can accomplish. I know there are some bucket mods that require players to have a privilege before being able to dump liquids. etc

**Comment by fluxionary** [comment]
> Suggestions are welcome.

@mieu12 you might be interested in https://content.minetest.net/packages/rheo/verbana/, though it is currently not compatible w/ IPv6.

**Comment by mieu12** [comment]
Thanks for the comments./suggestions.
