### ISSUE TITLE
itemstack meta lost after pickup item with same item

### ISSUE THREAD

**Issue by pandaro** [minetest/minetest#13134]
##### Minetest version

```
Minetest 5.7.0-dev-981d791 (Linux)
```

##### OS / Hardware

Operating system:ininfluent linux
CPU:i7

GPU model:gtx970
OpenGL version:unknow and ininfluent

##### Summary

all of the metadata are lost if a  item are picked up with another equal item

##### Steps to reproduce

I will confirm this:
[topic](https://forum.minetest.net/viewtopic.php?t=12644) 
so in order to reproduce:
- set a metadata in to a tool like default:steel_pick;
- drop the pick with metadata;
- use another default:steel_pick to pick up the first pick;
- check the metadata of the first modified pick, no metadata present.

Hope it is not a duplicate issues, but i think no.

**Comment by TurkeyMcMac** [comment]
I can't reproduce this with `basetools:pick_steel` from devtest.

**Comment by pandaro** [comment]
> I can't reproduce this with `basetools:pick_steel` from devtest.

what kind of meta you use? i have used a set_int('foo',1)

**Comment by pandaro** [comment]
maybe i'm wrong, and bad bug reporter, i close it until new confirmation, excuse for the disturbe

**Comment by TurkeyMcMac** [comment]
That's fine, the bug may be real. I set some metadata using devtest's `testtools:item_meta_editor`.
