### ISSUE TITLE
No damage_per_second while sneaking on top of the node

### ISSUE THREAD

**Issue by Phvli** [minetest/minetest#1315]
When user is sneaking on top of a node that has damage_per_second set, no damage is inflicted. Issue is reproducible both with 0.4.9 stable and current 0.4.9-dev build.

The node in question: prefab:electric_fence
https://github.com/ethic-rush/prefab/blob/master/init.lua#L329

This node has a node_box that does not reach the upper edge of the node area, very similar in appearance to technic cables and mesecon conductors.

**Comment by paramat** [comment]
@Phvli We have new sneak code now, this may be fixed.

**Comment by paramat** [comment]
New sneak places the player on the highest nodebox instead of hovering at a node border, so this should be fixed now. Also very old issue and no resonse.
