### ISSUE TITLE
Question: how to assign entity mesh textures through materials?

### ISSUE THREAD

**Issue by TamaMcGlinn** [minetest/minetest#13153]
In the documentation on [mesh nodes](https://rubenwardy.com/minetest_modding_book/en/items/node_drawtypes.html#mesh-nodes), it says this regarding assigning textures to meshes:

```
-- Holds the texture for each "material"
    tiles = {
        "mymod_meshy.png"
    },
```

This example evidently suffices to have a single png, so I am guessing that means the example mymesh.b3d being used has only one material, but should it be named mymod_meshy in order for to work? I was expecting a mapping from material name to png filename, but I guess there is some magic being used to determine which material is which. It could also be a fixed ordering, but everything I have tried so far just ends up with grey blocks as the texturing everywhere in place of the png I specified.

Hopefully someone has a working example to point to.

**Comment by TamaMcGlinn** [comment]
After looking through the examples, I noticed pictures such as `testnodes_mesh_stripes2.png` mentioned in `mods/testnodes/meshes.lua` which seem to indicate we should slap on an arbitrary png and then iteratively search for the UV coordinates that have been applied to each face. This is terrible, but at least it works:

![Screenshot from 2023-01-17 22-26-18](https://user-images.githubusercontent.com/5008897/213016542-caa424fd-6e54-4549-8bbb-7f9a32176e78.png)

**Comment by Desour** [comment]
Make sure you've really created the materials (i.e. in `.obj` files, you need the lines starting with `g`).

Then I'd guess the materials specified in `tiles` are assigned in the same order as the materials are given in the mesh. I'm pretty sure the name doesn't matter.


> After looking through the examples, I noticed pictures such as `testnodes_mesh_stripes2.png` mentioned in `mods/testnodes/meshes.lua` which seem to indicate we should slap on an arbitrary png and then iteratively search for the UV coordinates that have been applied to each face.

The UV coordinates are those from the mesh.
Please note that your cube's 3d coordinates might be transformed wrongly.

**Comment by NathanSalapat** [comment]
If you are creating your meshes via Blender I have a video on the subject.
https://www.nathansalapat.com/minetest/b3d4minetest-08
As Desour mentioned the materials specified in tiles should be in the same order that you assigned them in the software you used to create your mesh files. In some software you may need to check an export option to include the material groups.
