### ISSUE TITLE
mic support

### ISSUE THREAD

**Issue by Thepotato2** [minetest/minetest#13174]
Can mic support be added to minetest? so that you can talk with your friends ingame?

**Comment by wsor4035** [comment]
to answer your question, there is a csm that adds allows players to use mumble. previous (related) discussions: https://github.com/minetest/minetest/issues/10847 https://github.com/minetest/minetest/issues/7991 https://github.com/minetest/minetest/issues/1753

**Comment by rubenwardy** [comment]
Voice chat is out of scope for Minetest. You can use an external program, like Discord or Mumble. One thing that Minetest could do better is expose position information for these services (ie: Mumble) to do positional chat, but there is a mod for that as pointed out by wsor

**Comment by Thepotato2** [comment]
ok, thank you : )

**Comment by wsor4035** [comment]
question has been answered, so closing.
(one of the) mumble csm links for anyone reading this:
forum: https://forum.minetest.net/viewtopic.php?t=21586
git: https://github.com/Elkien3/minetest-mumble-wrapper
