### ISSUE TITLE
"Waiting for applyfiltersformesh timed out" error

### ISSUE THREAD

**Issue by Bituvo** [minetest/minetest#13188]
##### Minetest version
```
Minetest 5.7.0 6377ce9
```

##### OS / Hardware
Operating system: Windows 11
CPU: Intel i7-2600
GPU: GeForce GT 520

##### Summary
Sometimes when I dig a node, the face of it that faces me remains while the other ones disappear. This lasts for about two seconds, then it fixes itself and I get this error (in chat):
![image](https://user-images.githubusercontent.com/90872694/216831586-86f7976a-9935-4f20-a023-0bb321ad393e.png)
This happens in both singleplayer and on a server.

##### Steps to reproduce
1. Dig a node
2. Hope you are lucky

**Comment by rollerozxa** [comment]
I think this might has already been fixed in latest master with #13150

**Comment by Bituvo** [comment]
> I think this might has already been fixed in latest master with #13150

Thanks for pointing that out. I attempted a search on this topic and found no results, so I thought this was new...
