### ISSUE TITLE
Document deprecated Lua APIs

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13185]
a .md file listing all Lua API that have better alternate and will be removed in near future (Formspec for example) will help developers

so devs will know abiut deprecated APIs

also list things like fallling.lua will be turned to falling.cpp

**Comment by wsor4035** [comment]
it is impossible to predict the future. additionally, see the lua_api.txt which lists depreciated methods. if you have something specific that is depreciated, but not documented, please make an issue specifically for that

**Comment by rubenwardy** [comment]
We also post deprecations in the [changelog](https://dev.minetest.net/Changelog)
