### ISSUE TITLE
DISCUSS: Avoid sending distant air-only blocks to the client

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13180]
Testing #13133 I realized that the main saving from `block_send_optimize_distance` is avoiding sending air-only blocks to the client (for air nodes night and day lighting is identical).

But `block_send_optimize_distance` causes some needed/visible blocks to also be omitted (like deep ocean blocks and some blocks near ground boundaries).

It's not hard to track whether a block is air-only and simply not send it to the client (or only send the close ones).
As the block is deserialized just set a flag to false if any non-air node is found. Then in clientiface do not send distant air-only blocks.

Thoughts?

**Comment by SmallJoker** [comment]
1. The client still needs to know adjacent (3x3x3 cuboid) air-only mapblocks so that they don't collide with "ignore" nodes while jumping sideways.
2. The MapBlock content does not matter if there is no metadata. The MapNode data is 16 KiB for each. Is that too much to send?

**Comment by sfan5** [comment]
In addition to the concerned raised by Krock I'm also wondering, is *sending* them an actual issue? Air MapBlocks should be pretty small.

**Comment by lhofhansl** [comment]
Note that air-only blocks past `block_send_optimize_distance` (default 4 blocks) are already not sent to the client.

These blocks end up in various lists and caches on the client, which have to evicted, reset timers are reset, etc.
At large distances can be multiple 100k of these.

**Comment by lhofhansl** [comment]
@SmallJoker It would only do this for distant blocks (like `block_send_optimize_distance`).

Here's a simple test:
`block_send_optimize_distance` set to 4, `view_range` = 600. The scene loads ~3900 blocks in 17s
`block_send_optimize_distance` set to 40, `view_range` = 600. The same scene loads ~42000 blocks in 2m15s

So there is a very significant difference. `block_send_optimize_distance` also causes some other not to be sent, but the vast majority of these are air-only blocks.

Once loaded there seems to be no performance difference on the client. I have not measured extra load on the server, which I expect to be significant as it has to consider all these blocks for occlusion culling, et al.

**Comment by SmallJoker** [comment]
If this is about loading, it might as well be a network issue but skipping empty blocks that are really far away shouldn't hurt either.

**Comment by lhofhansl** [comment]
I'll do a PR and we can try it out. It actually can simplify the code as well, as the whole 'block_send_optimize_distance' shenanigans are no longer needed, and it is guaranteed to not lead to any visual glitches.

'block_send_optimize_distance' need to calculate the day-night diff of a block, which is so expensive that we actually store it with the block in the database. Only-air can be checked with a loop over the nodes (which, even without any caching, is so fast that it does not show in the profiler at all).

I think this is not so much about the network as it is about both server and client needing to juggle all these blocks.
That is not to say that there is not also parts of the networking that can be improved.

**Comment by lhofhansl** [comment]
#13201

**Comment by lhofhansl** [comment]
Close. See PR.
