### ISSUE TITLE
problem with certain doors and gates

### ISSUE THREAD

**Issue by daydream58** [minetest/minetest#13184]
##### Minetest version

```
5.7.0-dev-56d2567
```

##### OS / Hardware

Operating system:
CPU: 3800XT

GPU model: 3070ti
OpenGL version: 4.6

##### Summary

See compile instructions attached for this build for use in Win 11

Solid draw-bridge style gate WHEN LOWERED becomes slats and players fall thru if stop on surface (see pics)

Locked wooden door is fine (see pic) but locked steel door or jail door, I can walk right thru them like they're not even there. (see pic of white steel door and jail doors)

Switching to 5.6.1 everything shown works as expected.

##### Steps to reproduce

[minetestBuild.txt](https://github.com/minetest/minetest/files/10606706/minetestBuild.txt)

build info stated in summary above, objects affected are also well stated in summary above.

![solid gate UP](https://user-images.githubusercontent.com/8681228/216748597-5c353aff-e427-4dc5-850d-b7de18da5b86.png)drawbridge gate in UP position

![slat gate when DOWN](https://user-images.githubusercontent.com/8681228/216748333-d62f2b3f-6855-4a73-a33a-1d904c8695eb.png) drawbridge gate in DOWN position

![LOCK DOOR - fine](https://user-images.githubusercontent.com/8681228/216748342-8fed5855-bf59-410f-a1fe-a5d4e5a4282c.png) Locked wooden door - fine operating normally

![Steel Lock Door - malfunctioning](https://user-images.githubusercontent.com/8681228/216748348-2eb52ed9-369d-4acf-8080-21b3265ecf74.png)
Steel Locked Door - can walk thru like it's not there.

![JAIL DOORS](https://user-images.githubusercontent.com/8681228/216748355-5f69297e-77a4-4c2d-8b4b-d656f6456786.png)  Jail doors - can walk thru like they're not there

**Comment by SmallJoker** [comment]
This seems to be a mesh update issue. The last big change was 69fc206109 - does reverting it fix the problem? If not, would you please be so nice to run `git bisect` to find the commit that introduced this issue?

**Comment by daydream58** [comment]
The Windows compile continues to have the error, including in 69fc206 through to today's build.  The nightly cross compile does NOT have the issue.  Checked and rechecked (ok triple checked) 

I don't have the knowledge to go further as to what is the problem with the windows compile vs the cross compile so I'm afraid that's about all I can tell you on this.

**Comment by SmallJoker** [comment]
So the issue appears on MSVC but not GCC/MinGW? What if you go further back in history? Choose 5.6.0 as first good commit/tag for `git bisect` and use it to step through history to narrow down the first bad commit. That would help a lot to find the issue.
