### ISSUE TITLE
Callbacks For Schematic And Voxelmanip Nodes

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#13194]
## Problem

You currently cannot do the `on_construct` callback on nodes which were placed in bulk.

## Solutions

Allow the `on_construct` callback to work on nodes which were placed in bulk.

## Alternatives

Add a new `on_bulk_construct` callback, which is specific for any nodes which were placed in bulk.

## Additional context

If you wanted tree leaves to have a biome colour, for example, the tree leaves will not have said biome colour if you grew them from a sapling, since trees use schematics to be placed. You would need to use some likely heavy workarounds because of this.

**Comment by wsor4035** [comment]
re problem: the reason for this is to keep voxel manip fast and not slow it down
re solution: you can do this yourself in a mod
re alternative: see re solution
re additionally context: this is easy enough to do from a mod, not heavy work arounds as you claim.

additionally making on_construct be called in voxel manip would break the documented behavior https://github.com/minetest/minetest/blob/d3a6ee00e63cc0a4adcaa7598ad5614f1e419515/doc/lua_api.txt#L8544
