### ISSUE TITLE
Games start occasionally all white or black or with exaggerated bloom

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13190]
Last MT built from master.
Start any game, sometimes the window is white, sometimes black, sometime bloom seems extra strong.
Just starting the game again fixes it usually.

Happens in 5-10% of starts.

**Comment by lhofhansl** [comment]
@x2048 FYI.

**Comment by kilbith** [comment]
Can confirm. No easy way to reproduce to supply here.

**Comment by rubenwardy** [comment]
@LoneWolfHT posted this a few days ago:

![image](https://user-images.githubusercontent.com/2122943/216984169-f9eeffcd-207b-4dba-98ac-2c9772eb0d8f.png)

**Comment by NathanSalapat** [comment]
I've experienced the same thing, doesn't seem to be any sure way of reproducing the issue.

**Comment by LoneWolfHT** [comment]
When it happens for me it doesn't stop until I restart my client. Disabling bloom fixes it

**Comment by lhofhansl** [comment]
#13151 related?

**Comment by x2048** [comment]
Does disabling bloom or dynamic exposure avoid the problem?

**Comment by x2048** [comment]
@lhofhansl  #13151 was fixing a similar issue due to textures being uninitialized, but there might be more with e.g. uniforms

**Comment by lhofhansl** [comment]
I have dynamic exposure off, and it was still happening.

**Comment by x2048** [comment]
Can someone try to repro the white screen with `enable_bloom_debug` set to true and post screenshots here?

**Comment by x2048** [comment]
I have collected these cases (thanks to @kilbith):
![image](https://user-images.githubusercontent.com/4933697/217938295-4d8f9163-cfc9-482b-99a9-8148b796d7b0.png)
![image](https://user-images.githubusercontent.com/4933697/217938554-e6c8d238-edeb-4036-b6d3-8763d36b2fe8.png)
![image](https://user-images.githubusercontent.com/4933697/217938593-808be5cd-646d-4682-8a3f-417cf1bfd832.png)
![image](https://user-images.githubusercontent.com/4933697/217938632-e5b43a00-7247-40de-b587-9e5feeff7a92.png)

**Comment by kilbith** [comment]
One another special case:
![Capture d’écran du 2023-02-09 20-42-05](https://user-images.githubusercontent.com/7883281/217943265-7c01eab3-66e9-4c3d-82b9-078e2203b230.png)

**Comment by Zughy** [comment]
Closing, considering https://github.com/minetest/minetest/pull/13197#issuecomment-1425166521
