### ISSUE TITLE
Particle spawner tween properties for old fields are not sent to clients

### ISSUE THREAD

**Issue by OgelGames** [minetest/minetest#13199]
##### Minetest version
```
5.6.0 - 5.7.0-dev-4cd6b773b
```

##### Summary
The `style`, `reps` and `start` properties of `pos_tween`, `vel_tween`, `acc_tween`, `exptime_tween` and `size_tween` are not sent to clients, and thus cannot be changed from their defaults.

Relevant code:
https://github.com/minetest/minetest/blob/4cd6b773bb5de2594c682ae7e5793c80ad6a22e6/src/server.cpp#L1591-L1701
https://github.com/minetest/minetest/blob/4cd6b773bb5de2594c682ae7e5793c80ad6a22e6/src/network/clientpackethandler.cpp#L985-L1102

##### Steps to reproduce

1. Run the below code.
2. Observe that the spawn position only tweens forward and does not repeat.

```lua
minetest.add_particlespawner({
	amount = 50,
	time = 3,
	texture = "heart.png",
	pos_tween = {
		{x = 0, y = 1, z = 0},
		{x = 3, y = 3, z = 3},
		style = "pulse",
		reps = 5,
	}
})
```

WE command for convenience:
```
//lua minetest.add_particlespawner({amount=50,time=3,texture="heart.png",pos_tween={{x=0,y=1,z=0},{x=3,y=3,z=3},style="pulse",reps=5}})
```

**Comment by velartrill** [comment]
wow. how did we not catch this until now? this is *embarassing.* it's also going to be ugly to fix without breaking existing clients now that the broken code has been merged for a while

i seriously regret not just incrementing the protocol version number and restructing the format for the entire command. the legacy compat code is hideous and it was just begging for this kind of problem from the start

**Comment by velartrill** [comment]
working on a fix, hopefully will have a PR up in an hour or so

**Comment by sfan5** [comment]
ba2fee07518d9c6154799b61ba1b14a2cb43ace7
