### ISSUE TITLE
Jump at node edge doesn't work

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#132]
If you're walking around, and climbing up/down hills and such, occasionally you'll wind up right at the edge of a node after jumping, at which point you can't jump again (the key does nothing) until you step away from the edge slightly, even if there's nothing stopping the jump from happening.

**Comment by gregorycu** [comment]
The following changeset attempts to rectify this issue:
https://github.com/gregorycu/minetest/commit/e4498b05cd731fca7b42db96cd7a47fb8429514f

**Comment by gregorycu** [comment]
If the concerned parties wouldn't mind giving this a shot, hopefully we can nip this longstanding bug in the butt :)

**Comment by gregorycu** [comment]
#2224 attempts to fix this issue

**Comment by nanepiwo** [comment]
This also happens with nodeboxes, so for example standing at the edge of the top part of a stairsplus thin stair doesn't allow you to jump as well.

**Comment by ShadowNinja** [comment]
60dc01dc258db842e229351b871d0989e3e7d62c
