### ISSUE TITLE
buildwin64.sh error

### ISSUE THREAD

**Issue by giangduong** [minetest/minetest#13208]
##### Minetest version

```
minetest-5.7.0-4cd6b773b-win64
```

##### OS / Hardware

Operating system: Windows 10
CPU:

GPU model:
OpenGL version:

##### Summary

<img width="409" alt="image" src="https://user-images.githubusercontent.com/8393739/218986683-f4e63f65-0024-4a2e-a1b3-9163bd7c71a1.png">

##### Steps to reproduce

Run buildwin64.sh in Ubuntu 20.4 to build Minetest for Windows.

apt-get -y install mingw-w64

cd /opt
git clone https://github.com/minetest/minetest
cd /opt/minetest/util/buildbot
./buildwin64.sh

**Comment by sfan5** [comment]
This can happen if the mingw-gcc version used for the build differs too much from the gcc version used to build the prepared libraries the buildbot downloads. Can't really avoid this.

**Comment by giangduong** [comment]
Sfan5, thanks for your comment. Please let me know what mingw-gcc version i should use.

**Comment by sfan5** [comment]
You can try the mingw version used by our CI: https://github.com/minetest/minetest/blob/6e1c70e02b00df94a584bb4247cfa4f4c616c8d5/.github/workflows/build.yml#L172-L174

**Comment by rubenwardy** [comment]
Avoid installing things globally without a package manager, it can cause conflicts. Better to use a VM / container / install locally

**Comment by giangduong** [comment]
I confirm that using the mingw version used by your CI solves this problem.

Thanks for your support.
