### ISSUE TITLE
4dir Nodes Don't Work

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#13209]
##### Minetest version
```
5.6.1
```

##### Summary
Nodes that are `4dir` do not rotate at all.

##### Steps to reproduce
1. Place down a node with `4dir` as the `paramtype2`.
2. Notice that no matter how you place it, the node always faces the same direction, even if you manually edit the `param2` of said node, it looks the same at every `param2`.

**Comment by Desour** [comment]
>5.6.1

That feature didn't exist in 5.6.
Use https://github.com/minetest/minetest/blob/5.6.1/doc/lua_api.txt if you want to see the API for 5.6.1.

**Comment by Desour** [comment]
Yes.
