### ISSUE TITLE
[Task] Optimize trigonometry out of MapblockMeshGenerator::drawLiquidTop

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#13217]
https://github.com/minetest/minetest/blob/2a8becd650a8adaa86fd7f76122ea75f11f49dad/src/client/content_mapblock.cpp#L665-L675

Using `atan2`, `sin`, and `cos` (in `rotateBy`) is not necessary for rotation as $\frac{\sin(\mathrm{atan2}(y, x))}{\cos(\mathrm{atan2}(y, x))} = \frac{y}{x}$.

**Comment by arihant2math** [comment]
https://github.com/minetest/irrlicht/blob/cd3e7845344a413a73d2649e3e99d51f14eb12fb/include/vector2d.h#L178-192

Where does the division happen?

**Comment by numberZero** [comment]
> Where does the division happen?

It doesn’t. It’s just an equation that holds.

**Comment by numberZero** [comment]
Basically, treat `atan2` arguments as a vector, normalize it, and you get sine and cosine of the angle `atan2` would return.

**Comment by numberZero** [comment]
https://github.com/minetest/minetest/commit/5276c16e3740fbd10d636964ae2c8fee56635e71
