### ISSUE TITLE
Corrupted Screenshots

### ISSUE THREAD

**Issue by NA0341** [minetest/minetest#13221]
##### Minetest version

Initially noticed (may have been present before) `5.6.1`
Still present `5.7.0`

Happens with native installations & Flatpack Versions as well.

##### OS / Hardware

⮱ OS: `Manjaro Linux [rolling release][up to date]`
⮱ CPU: `Intel® Core™ i5-6300HQ × 4`
⮱ Laptop Model: `Dell Inc. Latitude E5470`

⮱ GPU model: `Mesa Intel® HD Graphics 530 (SKL GT2)`
⮱ OpenGL version: `4.6`

##### Summary

+ When saving a Screenshot in PNG format, the output image is ~~sometimes (partly)~~ corrupted.¹
+ Happens in both Singleplayer & Multiplayer.
+ Happens with custom & default Texturepack.
+ Isn't related to Hardware Load (taking (lots of) screenshots while the load is high doesn't cause corrupted output).
+ If you take the same screenshot again, it's usually not corrupt.

##### Steps to reproduce

+ Make a Screenshot. Sometimes it may be corrupted.
+ Exact steps needed are currently unknown.

Graphical settings that may cause this issue:
(checked entries are tested to be not affecting this issue)

- [x] Undersampling
- [ ] Custom FPS Settings
- [ ] Tradeoffs for Performance
- [ ] Node Highlighting type
- [ ] Fog

##### Workarounds

+ Use an external screenshot tool
+ Make multiple screenshots and delete corrupted ones

---

¹ The image is dimly visible (schemes), but textures are filled with grayish - colorfull noise.

![screenshot_20230213_233544](https://user-images.githubusercontent.com/26059513/219795568-ac8e864e-1725-4f41-823c-dd9fb3b70034.png)
![screenshot_20230212_171343](https://user-images.githubusercontent.com/26059513/219795595-71b0105b-b208-4779-a9b3-4b55372a5ffb.png)
![screenshot_20230212_031647](https://user-images.githubusercontent.com/26059513/219795638-0164c02d-c5aa-43f9-9998-93edc8510df4.png)

Sometimes small parts within the image are still intact.

![screenshot_20230214_065654](https://user-images.githubusercontent.com/26059513/219794975-7e1a57d1-3a37-427c-8cfb-2360b7ed790b.png)

**Comment by numberZero** [comment]
Irrlicht reads from the front buffer to take the screenshot. But as OpenGL wiki [states](https://www.khronos.org/opengl/wiki/Default_Framebuffer#Double_buffering),

> Rendering into, or reading from, the front buffer is not advisable. 

So that may be a problem. Fixing that, one would also need to move the call to `Client::makeScreenshot` to the point where the back buffer is ready, i.e. just before `IVideoDriver::end_scene()`.

**Comment by farooqkz** [comment]
I confirm this bug but only on wayland. What I have is:

Debian testing and ...

```
Minetest 5.9.0-dev (Linux)
Using Irrlicht 1.9.0mt15
Using LuaJIT 2.1.1700206165
Built by GCC 13.2
Running on Linux/6.7.9-amd64 x86_64
```

Unfortunately, I've downloaded `master.zip` and therefore I can't tell which commit is it.

This happens with shaders enabled or disabled.

**Comment by farooqkz** [comment]
Okay I managed to somehow fix this. It happens only when antialiasing method is set to `fsaa`.

**Comment by Zughy** [comment]
SDL might have fixed the issue, labelling as "possible close"

**Comment by appgurueu** [comment]
Also https://github.com/minetest/minetest/pull/14904

**Comment by NA0341** [comment]
@farooqkz said:
> It happens only when antialiasing method is set to `fsaa`.

Seems like there are multiple different causes for this issue.
I have antialiasing set to none (the default) ~ but am indeed on Wayland.

**Comment by appgurueu** [comment]
Can you still reproduce this on 5.9.0 or 5.9.1 at all? If so I will reopen this.

**Comment by NA0341** [comment]
I can.
For 5.9.1 I need to check but until 5.9.0 nothing changed for me.
(I'll update this on 5.9.1 tomorrow)
