### ISSUE TITLE
Inventory local and remote acting differently?

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#1322]
I am not shure if that is a Problem of Minetest itself or The used Inventory (unified_inventory) so I post it in Both.
If I am playing on my Server (Remote) only the first nine Fields of the Inventory are working.
If I am playing Local (Singleplayer or Server) all fields are working.
It makes no difference if I enable creative or not on the server I have the creative Priv.
I am using MT 0.4.9 232 in Kubuntu 14.04 LTS

**Comment by sapier** [comment]
Can you provide Information if this happens in plain inventory too?
If not I'd assume this bug to be fixed and close it due to old age in about a week.

**Comment by RobertZenz** [comment]
minetest-technic/unified_inventory#10 is the issue on the unified inventory side, which was caused by a corrupted file on the server end, so this can be closed.

**Comment by nerzhul** [comment]
Closing this, inventory object is exactly same on both parts.
