### ISSUE TITLE
World loading bar is glitched

### ISSUE THREAD

**Issue by Bituvo** [minetest/minetest#13235]
Minetest version: 56d2567b5dcf9556cef8352032cede48a5610801
Windows 11 Pro

My loading bar looks like this:
![image](https://user-images.githubusercontent.com/90872694/220174890-6825c3b8-0cad-4668-b83e-0a73154f3e66.png)

**Comment by sfan5** [comment]
This happens if you do not have a graphics driver installed and are using OpenGL 1.x.
