### ISSUE TITLE
Unrealistic time budget in client packet handler

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13236]
Here:
https://github.com/minetest/minetest/blob/master/src/client/client.cpp#L926

100ms is fairly unrealistic, when the client receives packets, processing can take a bit (especially with larger viewing_distances), during the which (1) the client is blocks, and (2) the client would not ack packets back, so that server is just waiting.

10ms leaves a much smoother picture. 10 is of course just as arbitrary as 100ms, and the best depends on a combination of client CPU, server CPU, network RTT, and network throughput.

I hate to make this configurable. It seems to me 10ms is far better hardcoded default than 100ms.

**Comment by sfan5** [comment]
Did you check how much is actually spent on packet processing?

> (2) the client would not ack packets back, so that server is just waiting.

Protocol level acking is done on the connection thread, so that doesn't block. Also not sure what "the server is waiting" refers to.

**Comment by lhofhansl** [comment]
> Protocol level acking is done on the connection thread, so that doesn't block. Also not sure what "the server is waiting" refers to.

Sorry, I should have been more precise: The blocks are acked in Client::step (see sendGotBlock towards the end). Until the server receives that it will not send more blocks (assuming the queue is full).

I saw the time spent on "non rendering" in the debug graphs. When changing that to 10ms, that time came down significantly. This is seen more prominently with mesh chunking. Instead of large spikes when blocks are sent then processed, there is now a smoother graph.

But regardless... Nothing should ever wait for _100ms on the main client thread_ (that by itself would be 10fps). Client:step is called from Game::step, which is called in the same loop as updateFrame.

(In fact even 10ms seems high.)

**Comment by sfan5** [comment]
> I saw the time spent on "non rendering" in the debug graphs. At first I couldn't understand where these large spikes are coming from. When changing that to 10ms, that time came down significantly. This is seen more prominently with mesh chunking. Instead of large spikes when blocks are sent then processed, there is now a smoother graph.

Sounds good.
