### ISSUE TITLE
mapblocks format and minetest version

### ISSUE THREAD

**Issue by efa** [minetest/minetest#13248]
## Problem
Looking in the changelog:
https://dev.minetest.net/Changelog
I cannot find the mapblocks version related to minetest version list.
Please made clear in the change log that mapblock format is changed with MT5.5 and World will be oneway converted, with no switch back possible.
In my case official Debian 11 package is 5.3, while installing the last 5.6 to test it will upconvert my worlds and so I cannot use anymore with official 5.3 package. There are no clear indication nowhere of this

## Solutions
I asked in the forum and a kind user answered me that 5.3 and 5.4 use mapblock format 28, while 5.5 and 5.6 use format 29.
Please put a clear note in the changelog

## Alternatives
In the forum a user speaks about a work around to convert back to format 28:
https://forum.minetest.net/viewtopic.php?f=6&t=27617&p=421802#p421802
with a script.
Can you please supply such script?

**Comment by sfan5** [comment]
There is a note in the [announcement post for 5.5.0](https://forum.minetest.net/viewtopic.php?f=18&t=27754).
It's worth noting that *any* Minetest version can change the map format in a way that is converted automatically and won't work on older versions, 5.5 was just the first time this happened in a while.

> In the forum a user speaks about a work around to convert back to format 28:

The way described there works fine, you will however have to compile Minetest from source to do this.

**Comment by efa** [comment]
> There is a note in the [announcement post for 5.5.0](https://forum.minetest.net/viewtopic.php?f=18&t=27754). It's worth noting that _any_ Minetest version can change the map format in a way that is converted automatically and won't work on older versions, 5.5 was just the first time this happened in a while.
please please add the clear note that is the announcement forum, in the changelog too for 5.5

> > In the forum a user speaks about a work around to convert back to format 28:
> 
> The way described there works fine, you will however have to compile Minetest from source to do this.

OK, thank you for confirmation. The user speak also about a conversion script for users that are not able to compile, is that available?

**Comment by sfan5** [comment]
> OK, thank you for confirmation. The user speak also about a conversion script for users that are not able to compile, is that available?

I don't know, you would have to ask them.

**Comment by efa** [comment]
I looked at the changelog from 5.4 to 5.5:
https://dev.minetest.net/Changelog#5.4.0_.E2.86.92_5.5.0
there are still no mention that the conversion is one way.

I cannot find the text from the forum announcement post for 5.5.0;
`Note: This isn't a first but to avoid surprises we want to point out that once you have loaded a map in Minetest 5.5 you will not be able to load it in previous versions. Make backups first. (Client-server compatibility is untouched by this.)`
