### ISSUE TITLE
Severe lag on Apple Silicon macOS when looking around while moving

### ISSUE THREAD

**Issue by johalun** [minetest/minetest#13258]
##### Minetest version

```
Minetest 5.6.1 (OSX)
Using Irrlicht 1.9.0mt8
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

##### OS / Hardware

Operating system: macOS 13.2
CPU: M1 Pro

GPU model: Apple M1 Pro
OpenGL version: ?

##### Summary

If I move using wasd I get extreme lag / frame drops when looking around with the mouse. If I stand still and look around FPS is good and smooth. I tried 5.6.0 and 5.6.1 with different games like dev world, minetest game and mesecraft, also disabling all fancy graphics options and reducing render distance down to 30. The problem still persists.
##### Steps to reproduce

Load up a new world, move while looking around and experience severe lag spikes / frame drops.

**Comment by hoodedice** [comment]
13" m1 macbook pro with 16GB RAM here running macOS monterey (12.5.1)

Cannot reproduce. Tried with various graphics settings on or off, and with laptop set to low power mode. If the fps does dip it is regardless of whether I am moving or not (ie: it is because there is more to render)

minetest runs in OpenGL 2.1 on macos btw

**Comment by johalun** [comment]
I tested on a different M2 MacBook and no issues there. The M2 is a brand new while the M1 with issues have a lot of stuff installed on it. Both these MacBooks have the same keyboard settings (key repeat rate = fast, delay until repeat = short). However, on the one with lag the more I move the sliders to the left the less lag I experience (key repeat rate = slow/off, delay until repeat = long).

I have some vague memory of this being an issue before but not sure that was related to Minetest or some other software. However, it seems to be related to keyboard input. I have tested both internal and external keyboards and the issue is the same.

**Comment by johalun** [comment]
After updating to 13.2.1 and rebooting the issue is gone. Not sure which of the actions solved it, might have been that just a reboot was needed. I barely ever reboot this computer so.

**Comment by johalun** [comment]
The issue came back. Reopening.

**Comment by MeseCraft** [comment]
How do other 3D applications work on your system? Is the fan working on your computer? reboot the system.

**Comment by johalun** [comment]
Minecraft works fine. The system is not loaded, I think it's keyboard/mouse input related lag, not caused by cpu/gpu being overloaded. It's like when I'm holding down a key on the keyboard (wasd) it interferes with moues input or vice verse.

**Comment by sfan5** [comment]
Can you post a screenshot of the F5 debug page plus graphs (press F5 twice) next time this happens? That should give some insight.

**Comment by johalun** [comment]
Here https://www.dropbox.com/s/hynr8zkbyl50qoa/minetest-input-lagg-1080p.mov?dl=0

The laggy part is where I move with WASD and look around at the same time. Let me know if it's too blurry and you need the 4K version.

**Comment by sfan5** [comment]
Thanks. The key takeaway here is that you're not getting frame drops or rendering but *input* lag.
Are you by chance using a touchpad? If so, did you try an external mouse?

**Comment by johalun** [comment]
I have tried all permutations of built-in keyboard/trackpap, wireless keyboard/mouse with usb dongle and wired mouse, all the same.

I will do a reboot soon and try again without any other applications open. It did fix itself last time I rebooted so could be some application interfering maybe.

**Comment by johalun** [comment]
Found the culprit!! It was AutoRaise https://github.com/sbmpost/AutoRaise
I updated AutoRaise to latest version and the issue is gone.

Thanks for the help everyone!
