### ISSUE TITLE
Drop ENABLE_GLES

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#13257]
`ENABLE_GLES` predates forking Irrlicht. Its primary use was to distinguish Irrlicht-ogles from mainstream version as Minetest could be compiled with either. That’s not necessary anymore, and gets in the way sometimes.

**Comment by sfan5** [comment]
I agree, most of the `#if` guards can be simply removed.
However:
* defaultsettings uses to it control some things
* the `near_plane` setting is only allowed on gles
* guiEngine.cpp does something suspicious that should probably be in an if guard
* shader.cpp defines some attributes that should be behind a runtime check instead

**Comment by numberZero** [comment]
> defaultsettings uses to it control some things

...and that is suspicious.

> the near_plane setting is only allowed on gles

In the current code that setting is allowed on regular GL too, as long as GLES support was compiled in.

> guiEngine.cpp does something suspicious that should probably be in an if guard

If you mean the `Align2Npot2` thing, it is a no-op on OGLES2.

**Comment by sfan5** [comment]
> In the current code that setting is allowed on regular GL too, as long as GLES support was compiled in.

Well yes, but that was the idea.

> If you mean the Align2Npot2 thing, it is a no-op on OGLES2. It is there for OGLES1.

Sure, but this looks suspicious:
![grafik](https://user-images.githubusercontent.com/1042418/221642405-279b9736-7794-4dfb-869e-38cf0d2606ee.png)

**Comment by numberZero** [comment]
> > In the current code that setting is allowed on regular GL too, as long as GLES support was compiled in.
> 
> Well yes, but that was the idea.

And what was the reason behind it?

> this looks suspicious:

Yes. Looks like the texture leaks if GLES is *not* compiled in, and might be freed prematurely if it is. If only it would be possible to, maybe, reference-count textures...

**Comment by sfan5** [comment]
> And what was the reason behind it?

cheating concerns #8749
