### ISSUE TITLE
Don't show controls in the pause menu

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13278]
## Problem
If I want to know what key does what, I can just hit "Change keys". It makes the pause menu more crowded for no reason, also because not every key is listed (e.g. zoom key)

## Solutions
Remove them

**Comment by sfan5** [comment]
I agree.

**Comment by Wuzzy2** [comment]
I'm not so sure if this is a good idea. Have actual user tests been done to verify the claim the controls in the menu are bad/good? Making claims about usability without testing it on real users is rarely a good idea because then you just make shots in the dark.

**Comment by kneekoo** [comment]
Thanks to "Controls", I almost never use "Change Keys". I only went there to look at the unlisted keybindings, or to assign a key to "Block bounds". They've been useful for me, but of course they become less useful once you know them by heart. But for players who are either new or don't play often, those are useful.

If anything, "Change Keys" should improve to also list F5 and F6, and maybe allow changing those too. And in the future, it could be called "Controls" and also allow changing the mouse speed and assign actions to more mouse buttons, like the middle/wheel, which is now common.

**Comment by SmallJoker** [comment]
It's a good overview of the most important keys. This might become even more helpful in the future when all key bindings can be changed in-game.

**Comment by rubenwardy** [comment]
I support doing this in the long term, can rename "Change Keys" to "Controls" and show a better interface there. As to whether this is useful with Change Keys in its current state is another matter

**Comment by Zughy** [comment]
@SmallJoker not all games are the same: a game like Slidespace doesn't need most of those commands. Same for PRANG, which only needs WASD. I think the error is thinking about commands by using MTG (or MC) as a starting point. Also, a good game tells you which key does what: it shouldn't be up to the pause menu.

That aside, in the long term, a customisable pause menu would definitely be the best solution

**Comment by rubenwardy** [comment]
The reason to do this is to reduce the clutter on the pause menu, leading users to instead use the Controls dialog which contains more complete information. This will have more of a benefit when the controls dialog is redesigned to cover more than key presses. Most games do this - to see the current controls, you click "Controls". 

>  not all games are the same: a game like Slidespace doesn't need most of those controls. Same for PRANG, which only needs WASD. I think the error is thinking about controls by using MTG (or MC) as a starting point.

This isn't that good a justification as the Controls menu still shows these keys

> Also, a good game tells you which key does what: it shouldn't be up to the pause menu.

This is not possible using the Minetest API currently. You'd need an `image_control[x,y;w,h;forward]` to show an icon for the current binding and/or a text escape code to show it in text like client-side translations.

**Comment by Wuzzy2** [comment]
Just wanna make clear I have no strong opinion one way or another.
