### ISSUE TITLE
Downloading a mod without a base game throws error instead of warning

### ISSUE THREAD

**Issue by Maverick2797** [minetest/minetest#13289]
##### Minetest version
```
Minetest 5.7.0-9ef3c8ce3-9ef3c8ce3 (Windows)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware
Operating system: Windows 10
CPU: AMD Ryzen 5 5600G

##### Summary
Trying to install a mod without any games installed throws an error instead of a warning.
```
Runtime error from mod '??' in callback handleMainMenuButtons(): ...c8ce3-win64\bin\..\builtin\mainmenu\dlg_contentstore.lua:316: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...c8ce3-win64\bin\..\builtin\mainmenu\dlg_contentstore.lua:316: in function 'resolve_dependencies'
	...c8ce3-win64\bin\..\builtin\mainmenu\dlg_contentstore.lua:367: in function 'get_formspec'
	...inetest-5.7.0-9ef3c8ce3-win64\bin\..\builtin\fstk\ui.lua:101: in function 'update'
	...inetest-5.7.0-9ef3c8ce3-win64\bin\..\builtin\fstk\ui.lua:145: in function 'handle_buttons'
	...inetest-5.7.0-9ef3c8ce3-win64\bin\..\builtin\fstk\ui.lua:186: in function <...inetest-5.7.0-9ef3c8ce3-win64\bin\..\builtin\fstk\ui.lua:172>
```

##### Steps to reproduce

1. Download a fresh install of Minetest with no pre-packaged Minetest Game or DevTest (from the Gitlab Pipeline, commit 9ef3c8ce3, win64 build.)
2. Try to download the "home decor" mod.
3. The above error is shown. I suggest a warning or something directing the user to install a base game first.

**Comment by rubenwardy** [comment]
Not having a base game breaks the dependency algorithm. This fix is either to force the user to install a game first, or to disable dependency installation with a warning
