### ISSUE TITLE
Mod bypassing Chat characters limit

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13295]
when i'm try to sent a too long message, Minetest will not send it and nothing happen

Howerver, by using Mesecon command block, using /msg command, Minetest seem to still  send it, is this intentional?

also this is dangerous and i can crash whole server with it (i send rubenwardy an email privately but not yet receive reply)

thanks Telesight && Swampturtle for helping testing this

**Comment by fluxionary** [comment]
@oong819 yes, it can crash the server, that issue is know: #9326.

not sure there's anything else actionable at the engine level, perhaps report this issue to the mesecons mod?
