### ISSUE TITLE
vm:get_light_data does not accept a buffer

### ISSUE THREAD

**Issue by Kimapr** [minetest/minetest#13294]
##### Minetest version

```
5.6.1
```
##### Summary

I've been working on a mod that uses VoxelManips and found that `vm:get_light_data` didn't use the buffer i passed to it, while `vm:get_data` and `vm:get_param2_data` did. While this is correctly described in the documentation, it's not something anyone would expect.

##### Steps to reproduce

```lua
local vm = ... -- acquire a voxelmanip
local data,data1,data2={},{},{}
vm:get_data(data) -- `data` is filled with data
vm:get_param2_data(data2) -- `data2` is also filled with data
vm:get_light_data(data1) -- `data1` is NOT filled with data (!!!)
assert(#data1>0) -- fails
```

**Comment by grorp** [comment]
Fixed by #12682?
