### ISSUE TITLE
MT 5.7 - wield scaled items are cropped on large screens

### ISSUE THREAD

**Issue by JurajVajda** [minetest/minetest#13293]
##### Minetest version
5.7

##### OS / Hardware
Operating system: macOS 13.2.1
CPU: X86-64

##### Summary

MT 5.7 - wield scaled items are cropped on large screens

![screenshot_20230306_155404_1920](https://user-images.githubusercontent.com/5089392/223290341-5beb3318-c1d6-49a3-9dc8-fca7b2db41ad.png)

##### Steps to reproduce
1. Get a big screen/resolution
2. Wield item with `wield_scale` larger than 1

**Comment by Desour** [comment]
Possibly related: #12826 
Maybe relevant: https://github.com/minetest/minetest/commit/ff6dcfea82974df6db5a557e31aaddb6bdb7a71f#diff-fcbec878e951f890e67374c1a267edc24407d94993e49343a84094831c952f98R634
cc @x2048
