### ISSUE TITLE
"About" screen is outdated because TurkeyMcMac ... :-(

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#13304]
##### Minetest version
```
5.7.0-dev
```

##### Summary

The "About" tab in the main menu is outdated because TurkeyMcMac (listed as "Jude Melton-Houghton") is still listed as an "active contributor". But this is false because ...

https://forum.minetest.net/viewtopic.php?f=18&t=29161

:-(

By the way, wasn't the upcoming release dedicated to him? I see no special mention in the About screen. Intentional?

**Comment by rubenwardy** [comment]
Hi, we update the About screen as part of the release process
