### ISSUE TITLE
MT 5.7 - Skybox broken when using setters from mods

### ISSUE THREAD

**Issue by JurajVajda** [minetest/minetest#13302]
##### Minetest version

```
Server: Minetest 5.6.1 (not sure if this matters)
Client: Minetest 5.7.0-dev-9ef3c8c (OSX)
```

##### OS / Hardware
Operating system: macOS 13.2.1
CPU: X86-64

OpenGL version: 2.1

##### Summary
Seems like when mods (event MTG) use some set methods for skybox (moon, sun, stars, clouds...) it is conflicting with something and sometimes the skybox gets broken. Shadows are where they should not be (due to missing sun), moon/sun skewed and visible (or not) where they should not be.

##### Steps to reproduce
How I can reproduce:
* I have all shaders, pre-post-whatever processing enabled
* login to the world, change the biomes to trigger the sky changes
* logout form world
* disable bloom
* log back in and repeat step 2

(i) not sure if steps 1-3 are really needed, thats just how I know I can reproduce

Video: https://youtu.be/CxICKE5W-HU

**Comment by Niklp09** [comment]
confirmed with a 5.6.1 server + 5.7 client
