### ISSUE TITLE
Frutiger Aero Icons

### ISSUE THREAD

**Issue by Tim79000** [minetest/minetest#13335]
## Problem

The new pixelated icons do not fit with the server list icons along with the plus button in the games menu.

## Solutions

Continue the server list style to fix this issue.

## Additional

This also looks nice, Frutiger Aero icons are highly resemble the user interface of Windows 7, XP, and Vista, and also resembles classic Linux distributions, it's a icon style that has long been unpopularized and Minetest could adopt this into it's identity.

**Comment by Tim79000** [comment]
This also fits the User Interface's buttons.

**Comment by Zughy** [comment]
Main menu needs a complete overhaul and there is an issue already about that (an issue you've already commented, including today). Closing
