### ISSUE TITLE
Make attached entities move more smoothly

### ISSUE THREAD

**Issue by SokolovPavel** [minetest/minetest#1334]
I found that attached entity take only pos of parent, instead of pos, velocity and acceleration.
(https://github.com/minetest/minetest/blob/master/src/content_sao.cpp#L495)

```
   if(isAttached())
   {
      v3f pos = m_env->getActiveObject(m_attachment_parent_id)->getBasePosition();
      m_base_position = pos;
      m_velocity = v3f(0,0,0);
      m_acceleration = v3f(0,0,0);
   }
   else
```

Additional characteristics will make movements of attached entities more smoothly.

**Comment by DS-Minetest** [comment]
the attached entities are already very smooth now, only if you attach it to a bone they are not

**Comment by paramat** [comment]
Is this an improvement? Surely if attached it will very soon take on the velocity and acceleration of the parent?

**Comment by paramat** [comment]
I assume this is referring to:
```
void LuaEntitySAO::step(float dtime, bool send_recommended)
{
...
...
	// Each frame, parent position is copied if the object is attached, otherwise it's calculated normally
	// If the object gets detached this comes into effect automatically from the last known origin
	if(isAttached())
	{
		v3f pos = m_env->getActiveObject(m_attachment_parent_id)->getBasePosition();
		m_base_position = pos;
		m_velocity = v3f(0,0,0);
		m_acceleration = v3f(0,0,0);
	}
```
Which seems correct?

**Comment by DS-Minetest** [comment]
>[...]we can't
// read and attach to skeletal bones.

https://github.com/minetest/minetest/blob/bf403b923ab4a1e11447b3f81d54d5d0c1124f65/src/content_sao.cpp#L179L182

**Comment by paramat** [comment]
So is this even an issue? The code seems correct to me.
Closing in 1 month.

**Comment by paramat** [comment]
There's no reason to suspect this is wrong, so closing.

**Comment by paramat** [comment]
Someone would have to test the suggestion @SokolovPavel

**Comment by paramat** [comment]
The code seems correct and the author has not tested his suggestion.
