### ISSUE TITLE
I can't walk

### ISSUE THREAD

**Issue by stepanzubkov** [minetest/minetest#13359]
##### Minetest version

```
5.6.1 (Linux)
```

##### OS / Hardware

Operating system: Arch Linux
CPU: Intel i3-2100 (4) @ 3.100GHz

GPU model: NVIDIA GeForce GT 440
OpenGL version: 4.3

##### Summary
When I create new world in minetest, I want to walk, but `wasd` keys and arrows aren't working. In settings, there are `wasd` keys for walking. I changed walking keys to arrows and it is working! But I can't change it back to wasd.

When I try to change it, there are empty rectangles:
![изображение](https://user-images.githubusercontent.com/83695097/227796810-b9ecd739-6bec-407f-9646-b498e834eb92.png)

I tried to remove my `~/.minetest/minetest.conf` file, but it takes no effect.
More in https://github.com/MeseCraft/MeseCraft/issues/55

##### Steps to reproduce

1. Launch Minetest on newer Arch Linux
2. Create new world in minetest game or development test game
3. Press W, A, S or D key

**Comment by stepanzubkov** [comment]
ALL letter keys are not working, But other, like `/`, `<Space>`, arrows are working.

**Comment by Desour** [comment]
This is probably some keyboard layout issue.
Maybe related: #13031
Are you using X11 or wayland?
You could try if compiling with SDL (`cmake -DUSE_SDL2=TRUE ...`) somehow magically fixes your issue.

**Comment by stepanzubkov** [comment]
I use wayland.

**Comment by stepanzubkov** [comment]
Thank you. I build minetest from source code with flag `-DUSE_SDL2=TRUE` and now I can use letter keys. :smiley:
