### ISSUE TITLE
Build problem with ZSTD

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#13368]
I recently had to recreate my build environment from scratch. After doing so, and running the 'make' command to build Minetest, I got this error:

```
minetest/src/script/lua_api/l_util.cpp:329:15: error: ‘ZSTD_CLEVEL_DEFAULT’ was not declared in this scope
```

I've confirmed that the library is installed, /usr/include/zstd.h exists, and the build system can find it.

I thought it somewhat interesting that I can't find the constant ZSTD_CLEVEL_DEFAULT anywhere in the library header except in comments, and zstd.h doesn't include any other headers in turn (except stddef.h) so I am stumped as to where this symbol is supposed to come from. The ZSTD header does say version 1.3.3.

I changed l_util.cpp to read as follows:

```
#include <zstd.h>
#ifdef ZSTD_CLEVEL_DEFAULT
#error It exists!
#endif
```

The compiler did not remark. I'm stumped.

**Comment by sfan5** [comment]
I have this on my system:
<pre>
/usr/include/zstd.h
128:#ifndef ZSTD_CLEVEL_DEFAULT
129:#  define ZSTD_CLEVEL_DEFAULT 3
242:ZSTDLIB_API int         ZSTD_defaultCLevel(void);           /*!< default compression level, specified by ZSTD_CLEVEL_DEFAULT, requires v1.5.0+ */
336:                              * Default level is ZSTD_CLEVEL_DEFAULT==3.
337:                              * Special: value 0 means default, which is controlled by ZSTD_CLEVEL_DEFAULT.
</pre>

whats your libzstd version?

**Comment by BluebirdGreycoat** [comment]
Here's what I got:

```
/usr/include/zstd.h
/*------   Version   ------*/
#define ZSTD_VERSION_MAJOR    1
#define ZSTD_VERSION_MINOR    3
#define ZSTD_VERSION_RELEASE  3

#define ZSTD_VERSION_NUMBER  (ZSTD_VERSION_MAJOR *100*100 + ZSTD_VERSION_MINOR *100 + ZSTD_VERSION_RELEASE)
ZSTDLIB_API unsigned ZSTD_versionNumber(void);   /**< useful to check dll version */

#define ZSTD_LIB_VERSION ZSTD_VERSION_MAJOR.ZSTD_VERSION_MINOR.ZSTD_VERSION_RELEASE
#define ZSTD_QUOTE(str) #str
#define ZSTD_EXPAND_AND_QUOTE(str) ZSTD_QUOTE(str)
#define ZSTD_VERSION_STRING ZSTD_EXPAND_AND_QUOTE(ZSTD_LIB_VERSION)
ZSTDLIB_API const char* ZSTD_versionString(void);   /* v1.3.0 */
```

I didn't notice that last line before ... if that last comment is correct, is my version too old?

Trying to install the package gets me this:

```
libzstd-dev is already the newest version (1.3.3+dfsg-2ubuntu1.2).
```

**Comment by SmallJoker** [comment]
> The ZSTD header does say version 1.3.3.

Apparently the README is outdated or the source code needs a workaround to support older versions as well.

**Comment by sfan5** [comment]
It looks like we inadvertently raised the libzstd requirement from 1.0.0 to 1.3.5 in commit b1233056b76aa803123cc304d323887ad5fdfbae

**Comment by sfan5** [comment]
FWIW you can easily work around this by adding a `#define ZSTD_CLEVEL_DEFAULT 3` to the top of l_util.cpp.

**Comment by lhofhansl** [comment]
The current version is 1.5.4. 

1.3.3 is from December 2017 (https://github.com/facebook/zstd/releases).
There have been many, many fixes and performance improvements since then. You do not want to use such an old version.

Is that an environment where a later version is not available?

IMHO, we should not only not fix this, we should purposefully fail the build with any version of zstd older than 1.4.0 (April 2019).

Yes, I realize this is radical. But I fear that even if this is fixed there might be other subtle problems from which we will get bug reports.
