### ISSUE TITLE
Out-of-bounds access in NodeDefManager::nodeboxConnects

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#13377]
##### Minetest version
`master` @ 48fc286a9500abfbd6c05f2002d73cc8ba57eebb

##### Summary
`MapblockMeshGenerator::drawNodeboxNode` calls `NodeDefManager::nodeboxConnects` with `connect_face` up to 32 (lines 1421, 1440):
https://github.com/minetest/minetest/blob/48fc286a9500abfbd6c05f2002d73cc8ba57eebb/src/client/content_mapblock.cpp#L1420-L1442
`NodeDefManager::nodeboxConnects` has an array of size 4×33=132 (line 1732) but indexes it with `(connect_face * 4) + (to.param2 & 0x1F)` (line 1747) which may thus be up to 4×32+31=159
https://github.com/minetest/minetest/blob/48fc286a9500abfbd6c05f2002d73cc8ba57eebb/src/nodedef.cpp#L1707-L1758

**Comment by Zughy** [comment]
@numberZero is this still a thing? Since the first file changed in current master

**Comment by Desour** [comment]
Still exists. Fix: #13944
