### ISSUE TITLE
libm:sincosf32x suddenly shows large CPU usage on Linux.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13386]
##### Minetest version

Latest master

##### OS / Hardware
CPU: Linux/Intel/NVidia

##### Summary
shows a CPU hog in the Minetest client that I have not seen before: sincosf32x.
That is new.

```
5.06%  libm.so.6                                [.] sincosf32x
3.49%  minetest                                 [.] ClientMap::renderMap
2.94%  minetest                                 [.] GameGlobalShaderConstantSetter:
2.59%  minetest                                 [.] MainShaderConstantSetter::onSet
2.20%  libc.so.6                                [.] __strcmp_avx2
2.15%  libnvidia-glcore.so.530.41.03            [.] 0x00000000015ec3b8
```
##### Steps to reproduce

Start the MT client. Run `sudo perf top` on Linux. And see how `sincosf32x` is the most expensive task on the CPU.

**Comment by lhofhansl** [comment]
It's independent of which occlusion culler (bfs, loops) is used... So we can rule that one out.

**Comment by sfan5** [comment]
Can't reproduce here.
<pre>
   4,46%  minetest                             [.] ClientMap::renderMap
   1,79%  radeonsi_dri.so                      [.] 0x00000000001e8316
   1,68%  radeonsi_dri.so                      [.] 0x00000000001e830c
   1,54%  libc.so.6                            [.] 0x0000000000153585
   1,46%  libc.so.6                            [.] 0x00000000001537a9
   1,42%  minetest                             [.] MainShaderConstantSetter::onSetConstants
   1,30%  libc.so.6                            [.] 0x00000000001537ae
   1,29%  libIrrlichtMt.so.1.9.0.11            [.] irr::video::CNullDriver::getBufferLink
   1,26%  libc.so.6                            [.] 0x00000000001537b3
   1,18%  minetest                             [.] Environment::getDayNightRatio
</pre>

**Comment by lhofhansl** [comment]
Hmm... Large viewing_range >= 500, client_mesh_chunk >= 4?

**Comment by lhofhansl** [comment]
Sorry. Had some left-over local patches applied. Never mind me. Sorry I wasted your time.

**Comment by lhofhansl** [comment]
If you are curious, it was the "god ray" changes from @x2048 .
