### ISSUE TITLE
use of on_use does not repeat the action

### ISSUE THREAD

**Issue by mowgli** [minetest/minetest#13381]
With the default behavior of tools with on_use set to nil, the tool is used as long as the left button is pressed. But when I use a on_use function, there is only one action executed until I release the button and press it again.

I need to use on_use to create a tool that is only digging special nodes. Unfortunately the crumbly nodes will always be digged even if not in groupcaps. So, maybe that are two bugs?

**Comment by Zughy** [comment]
Hello, unfortunately your request is not clear to us. Please open a new issue following the proper template

**Comment by mowgli** [comment]
> Hello, unfortunately your request is not clear to us. Please open a new issue following the proper template

Which template? How?

**Comment by fluxionary** [comment]
> That explains it for some degree. However. it is not helpful.

if you join the `#minetest` channel on [IRC](https://wiki.minetest.net/IRC), i or someone else can try to help you figure out a way to achieve the effect you want, or help you create a feature request.
