### ISSUE TITLE
Water behavior

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest#13388]
##### Minetest version
```
5.6.1, flatpak version
```

##### OS / Hardware
Operating system: Zorin OS Core
CPU: AMD® V140

##### Summary
Water don't flow through holed objects, plants, and ladders so players use this as cheat to stay alive underwater and even on lava.
![Schermata da 2023-01-06 17-28-01](https://user-images.githubusercontent.com/123581658/230118187-96e66f13-26d5-4af7-b417-c0a747b68c62.png)
![Schermata da 2023-01-06 17-28-09](https://user-images.githubusercontent.com/123581658/230118195-b374c525-5a39-46d6-b47a-dade0ef2ef62.png)
![Schermata da 2023-01-06 20-40-11](https://user-images.githubusercontent.com/123581658/230118203-31b685da-71e7-4559-b5c9-451db5485849.png)
Also, when something is placed on it (on my case, a big transparent red wall on Capture the Flag server), once it disappears water don't flow on that empty space unless you dig a block that's adjacent to the water so that water all around the dug node can start flowing to fill the large gap.
![Schermata da 2023-01-08 02-37-50](https://user-images.githubusercontent.com/123581658/230119209-059e5c2b-1fc0-47af-a714-98f1e8b5d440.png)
To close this, water don't extinguish furnace fire.
![Schermata da 2023-01-08 16-13-31](https://user-images.githubusercontent.com/123581658/230119495-3b845c04-7180-40b2-a3ee-04c8ac2b57b4.png)

##### Steps to reproduce
I bet it's enough clear by my summary and screenshots.

**Comment by PavanLuca** [comment]
I see I'm not the lone thinking that water is weird. At least until someone decides to fit it better to real physic laws I'll think that it's magic.

**Comment by Desour** [comment]
FYI, the other two things you described are mod, not engine, issues.

**Comment by PavanLuca** [comment]
Heh, if I was a bit of a programmer I'd have already done, but I'm not, not even 1% 😑😆.

**Comment by sfence** [comment]
@PavanLuca  Maybe, this #14103 can take your attention.
