### ISSUE TITLE
Building minetest from stable-5 branch with current irrlichtmt fails

### ISSUE THREAD

**Issue by buti1021** [minetest/minetest#13382]
##### OS / Hardware

Operating system: Ubuntu 22

##### Summary
Building minetest from the stable-5 branch with the current irrlichtmt version fails

##### Steps to reproduce
```
git clone -b stable-5 --depth 1 https://github.com/minetest/minetest.git
cd minetest
git clone -b stable-5 --depth 1 https://github.com/minetest/minetest_game.git games/minetest_game
git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt
cmake . -D{BUILD_CLIENT=0,{BUILD_SERVER,RUN_IN_PLACE,ENABLE_POSTGRESQL,ENABLE_PROMETHEUS}=1}
make -j$(nproc) package
```

> /tmp/test3/minetest/lib/irrlichtmt/include/irrMath.h:160:18: warning: inline function ‘T irr::core::roundingError() [with T = short int]’ used but never defined
>   160 |         inline T roundingError();
>       |                  ^~~~~~~~~~~~~
> In file included from /tmp/test3/minetest/lib/irrlichtmt/include/vector3d.h:8,
>                  from /tmp/test3/minetest/src/irr_v3d.h:24,
>                  from /tmp/test3/minetest/src/voxel.h:23,
>                  from /tmp/test3/minetest/src/voxelalgorithms.h:22,
>                  from /tmp/test3/minetest/src/voxelalgorithms.cpp:20:
> /tmp/test3/minetest/lib/irrlichtmt/include/irrMath.h:160:18: warning: inline function ‘T irr::core::roundingError() [with T = short int]’ used but never defined
>   160 |         inline T roundingError();
>       |                  ^~~~~~~~~~~~~
> [100%] Linking CXX executable ../bin/minetestserver
> /usr/bin/ld: CMakeFiles/minetestserver.dir/mapgen/mapgen.cpp.o: in function `Mapgen::updateLiquid(UniqueQueue<irr::core::vector3d<short> >*, irr::core::vector3d<short>, irr::core::vector3d<short>)':
> mapgen.cpp:(.text+0x5b68): undefined reference to `short irr::core::roundingError<short>()'
> /usr/bin/ld: mapgen.cpp:(.text+0x5c61): undefined reference to `short irr::core::roundingError<short>()'
> /usr/bin/ld: mapgen.cpp:(.text+0x5ca6): undefined reference to `short irr::core::roundingError<short>()'
> /usr/bin/ld: mapgen.cpp:(.text+0x5cd9): undefined reference to `short irr::core::roundingError<short>()'
> /usr/bin/ld: mapgen.cpp:(.text+0x5cfb): undefined reference to `short irr::core::roundingError<short>()'
> /usr/bin/ld: CMakeFiles/minetestserver.dir/mapgen/mapgen.cpp.o:mapgen.cpp:(.text+0x5d79): more undefined references to `short irr::core::roundingError<short>()' follow
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/CMakeFiles/minetestserver.dir/build.make:3341: bin/minetestserver] Error 1
> make[1]: *** [CMakeFiles/Makefile2:391: src/CMakeFiles/minetestserver.dir/all] Error 2
> make: *** [Makefile:156: all] Error 2

Checking out an older version of irrlichtmt before building works perfectly fine (I tried ce0d29df933fd03c5de218e159976629113257b9)

**Comment by Niklp09** [comment]
You have to build Minetest 5.6.1 with [Irrlicht 1.9.0mt8](https://github.com/minetest/irrlicht/releases/tag/1.9.0mt8)

![grafik](https://user-images.githubusercontent.com/89982526/229417365-cdab9a21-d9ea-4e2d-971c-3b8a301769cc.png)

**Comment by buti1021** [comment]
Thank you!

**Comment by sfan5** [comment]
FWIW the reason this happens is that CMake allows you to build the _server_ with just a copy of the headers. If you try to build the client it will check the cmake target and verify that you are using exactly the version that was intended.

**Comment by buti1021** [comment]
Thought about this a bit more as it makes automated building a bit problematic, as one would have to manually check the release notes to find the appropriate IrrlichtMt version to build, or could you see any good way to find this programatically? Might adding Irrlicht MT as git submodule to the repository might be a good approach?

**Comment by sfan5** [comment]
yes, see #13215

**Comment by buti1021** [comment]
Awesome! :)
