### ISSUE TITLE
after_place_node() not called when on_place() defined

### ISSUE THREAD

**Issue by webD97** [minetest/minetest#1338]
When placing a node which has defintiions for on_place and after_place_node, the latter one isn't called.

Code example:

``` lua
(...)
on_place = minetest.rotate_node,
after_place_node = function(pos, placer, itemstack, pointed_thing)
    minetest.chat_send_all("bla")
end,
(...)
```

Result: Rotated node, but no chat output.

**Comment by t4im** [comment]
@webdesigner97 try wrapping `on_place` instead
```lua
on_place = function(itemstack, placer, pointed_thing)
	minetest.chat_send_all(minetest.serialize(pointed_thing))
	return minetest.rotate_node(itemstack, placer, pointed_thing)
end,
```
^^ that should even call `after_place_node`, too.

Only when you add a custom `on_place`, you *might* end up not calling `after_place_node`. But then you'd usually don't need it either, because you do everything inside `on_place` already.

**Comment by everamzah** [comment]
return minetest.item_place(itemstack, placer, pointed_thing)

**Comment by paramat** [comment]
See related https://github.com/minetest/minetest_game/issues/656 and #5807

**Comment by SmallJoker** [comment]
This behaviour is documented.
https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/doc/lua_api.txt#L6044-L6046
