### ISSUE TITLE
[documentation] Client HUD API documentation doesn't match Server HUD API documentation

### ISSUE THREAD

**Issue by Maverick2797** [minetest/minetest#13396]
##### Minetest version

```
minetest 5.6.1 release
```

##### OS / Hardware

Operating system: Windows 10
CPU: Ryzen 5 5600G

##### Summary

Documentation should either be identical (due to there not being any/many differences between the server/client APIs) or just refer the user to the server documentation instead.
Client HUD API documentation is currently missing:
- All reference to `z_index`
- `direction` reference is missing the description of what it does, ie it only shows the description of the parameters

##### Steps to reproduce

Compare current (5.6.1) Server vs Client HUD api documentation

**Comment by v-rob** [comment]
Honestly, `client_lua_api.txt` is horribly out of date, and it's not just the HUD documentation.  This issue is too specific, so closing in favor of #11577.
