### ISSUE TITLE
Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by Festus1965** [minetest/minetest#13395]
##### Minetest version
5.7.0-dev  but also a version 2-3 weeks before

##### OS / Hardware
Operating system: Ubuntu 22.04
CPU: I7-4770

GPU model: GForce 960 GTX
OpenGL version: ?
under NVIDIA Driver metapackage 510 
but new compiled version works with 525 after restart PC

##### Summary
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  760
  Current serial number in output stream:  761

##### Steps to reproduce
compiled and used 5.7.0-dev for 2 weeks or more and no change
last run 2 days ago from self compiled /bin/minetest

just today it refuses to run,

so download new, compile new, same failure
and then update Ubuntu NVidia driver from 510 to 525 and restart new compiled 5.7.0-dev started normal

no idea from where, but main from Ubuntu or graphic there - but we should know this
I can update if new download available

**Comment by SmallJoker** [comment]
#13041

Did you yet try to reboot?

**Comment by Festus1965** [comment]
the failure happened already before I changes something,
the PC with Ubuntu is restarted several times, as I shut down when not needed - so booting 3 times a day normal

the failure even with new compiled version of 5.7.0-dev only solved after
I updated to a new Nvidia driver (from 510 to 525) and then also restarted

So from my mind, that seams to be something with the older 510-driver,
as several boots, no changes at old compiled MT, is sure

not clear sure about new compiled version, update system and after upgrade to 525 and reboot then all was solved

So for other might fall in this problem - 
* reboot check
* upgrade or change NVidia driver, reboot and check again

**Comment by sfan5** [comment]
Please check whether GLX is working at all on your system using e.g. `glxgears` or `glxinfo`.
Also the output of `minetest --version` would be helpful.

**Comment by Festus1965** [comment]
mhh, all this output ?

Working / Gaming PC - where I solved it with upgrade NVidia driver to 525:
Minetest 5.7.0-dev (Linux)
Using Irrlicht 1.9.0mt9
Using LuaJIT 2.1.0-beta3

the other way installed stable version 5.6.1 start normal with older 510 and new 525 driver !

glxgears = working (3 color gears)

glxinfo ...
name of display: :0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: NVIDIA Corporation
server glx version string: 1.4
server glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_no_error, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_framebuffer_sRGB, GLX_EXT_import_context, GLX_EXT_libglvnd, 
    GLX_EXT_stereo_tree, GLX_EXT_swap_control, GLX_EXT_swap_control_tear, 
    GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, GLX_EXT_visual_rating, 
    GLX_NV_copy_image, GLX_NV_delay_before_swap, GLX_NV_float_buffer, 
    GLX_NV_multigpu_context, GLX_NV_robustness_video_memory_purge, 
    GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, GLX_SGI_swap_control, 
    GLX_SGI_video_sync
...
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 2048 MB
    Total available memory: 2048 MB
    Currently available dedicated video memory: 1347 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 960/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 525.105.17
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
...
OpenGL version string: 4.6.0 NVIDIA 525.105.17
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
... 
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 525.105.17
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20

**Comment by rubenwardy** [comment]
If it is now working, after a driver update/restart, then I don't really see any issue here that we need to fix

**Comment by Festus1965** [comment]
BUT the same issue also happened on the server now:
Ubuntu 22.04
self compiled 5.6.1 stable / final from jsut 3 weeks ago:

even I didn't force any update on drivers, as I avoid restart,
NOW, yesterday evening I can't open 5.6.1 client anymore

minetest --version
5.6.1 Linux
Irrlicht 1.9.0mt9
Using LUAJit 2.1.0-beta3

ah, glxgears deliver same failure I got other PC by start client gui in terminal:
Error of failed Conquest ...
152 (GLX)
3 (X_GLXCreateContent)
0x0
36
37

glxinfo
fails on same issue

not solved yet, but I am sure after
* maybe just reboot now (less chagne)
* update graphic driver, and restart (high change) will work again
