### ISSUE TITLE
Minetest Android downloads din't got update

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13405]
##### Minetest version

```
5.7.0
```

##### Summary

F-Droid and GitHub Android download did not get updated, the 5.7.0 also don't have Android download but the build from Action workflow still work  (not mention Google Play download because its stuck in 5.5.1 & gone)

**Comment by licaon-kter** [comment]
F-Droid will build it next cycle: https://gitlab.com/fdroid/fdroiddata/-/commit/5a627c7cf7fa5fbf4cedc943191be8925256bfbc

**Comment by oong819** [comment]
wow, i dont know that Minetest F-Droid download are not synced with tag release

but why Minetest 5.7.0 dont have apk release? i dont see any blocker issue

**Comment by licaon-kter** [comment]
> wow, i dont know that Minetest F-Droid download are not synced with tag release

As https://github.com/minetest/minetest_android_deps/issues/3 says, maybe we can have that in the future :tada:

**Comment by oong819** [comment]
resolved!
