### ISSUE TITLE
World crashed after loaded

### ISSUE THREAD

**Issue by TheMalaysianDude** [minetest/minetest#13406]
##### Minetest version

```
5.7.0
```

##### OS / Hardware

Operating system: Windows 7
CPU: Intel(R) Pentium(R)

GPU model:
OpenGL version:

##### Summary
World crashed after loaded.
```
2023-04-09 16:41:08: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:30000.
2023-04-09 16:41:13: ERROR[Server]: An unhandled exception occurred: Failed to prepare query 'INSERT INTO `player_inventories` (`player`, `inv_id`, `inv_width`, `inv_name`, `inv_size`) VALUES (?, ?, ?, ?, ?)': no such table: player_inventories
```

##### Steps to reproduce
-Create a new world and enter it/Enter an existing world.

**Comment by Desour** [comment]
* Did this already happen in minetest 5.6?
* Are you using the sqlite player db backend (the default)?
* Have you tried with default settings (rename your minetest.conf)?
* What is your sqlite3 version?
* What files are in your world folder (`worlds/your_worldname/`)?
  * Does it include `players.sqlite`?
  * If yes, try `$ sqlite3 players.sqlite` and `> .schema`. Paste the output.

**Comment by TheMalaysianDude** [comment]
> * Did this already happen in minetest 5.6?
> * Have you tried with default settings (rename your minetest.conf)?
> * Are you using the sqlite player db backend (the default)?
> * What is your sqlite3 version?
> * What files are in your world folder (`worlds/your_worldname/`)?
>   
>   * Does it include `players.sqlite`?
>   * If yes, try `$ sqlite3 players.sqlite` and `> .schema`. Paste the output.

* No, it did not happen and minetest is running fine.
* I deleted my minetest.conf and it's still the same
* Unsure, All I know is that I have player.sqlite inside the world file.
* Format 3
* I am not familiar with sqlite command.

**Comment by rubenwardy** [comment]
Note that we no longer support Windows 7. Microsoft doesn't support it either, so you really should consider updating or switching to Linux
