### ISSUE TITLE
32-bit build with shadows runs out of memory quickly (memory leak?)

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#13411]
##### Minetest version
```
Minetest 5.7.0 (Windows)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware
GPU model: Radeon RX 6500
OpenGL version: 4.6

**I have currently only reproduced this on Wine, not on real Windows.** Issue could be hardware/driver-dependent.

##### Summary
```
<+sfan5> dynamic shadows or automatic exposure seem to be leaking memory, I can easily bring the 32-bit build to crash by flying around a bunch
<+sfan5> 2023-04-08 18:55:43: ERROR[Emerge-0]: /home/stefan/mt-build/build/32/minetest/src/emerge.cpp:2f4: run: A fatal error occurred: std::bad_alloc
<+Krock> only in 32-bit?
<+Krock> https://github.com/minetest/minetest/blob/master/src/emerge.cpp#L756  referenced line
<+sfan5> alternatively the allocation size is wrong, memory usage at time to crash is barely above 1GB
<+sfan5> could be that the process runs out of virtual address space for other reasons
<+sfan5> client_mapblock_limit = 2000 does not prevent this so this suggests there's an actual bug
```

minetest.conf used: https://paste.debian.net/1276768/

##### Steps to reproduce
1. Use 32-bit windows build
2. configure as described
3. enter a world and fly around for 1-2 minutes
4. `std::bad_alloc`

**Comment by sfan5** [comment]
ping @x2048

**Comment by x2048** [comment]
Checked on Windows 11 22621.1413, AMD Ryzen 3 5300U without issues.

Checked:
* No shadows, no mapblock limit
* Medium shadows, 1000 client mapblocks
* Referenced minetest.conf
* Bloom
* Auto-exposure

**Comment by sfan5** [comment]
Can't reproduce this on Windows 10 on the same hardware, putting this off as Wine weirdness.
