### ISSUE TITLE
More control over dungeons in MapgenV6

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#13413]
## Problem

* Desert temples can not be disabled independently from dungeons
* however it may be desirable to still allow _normal_ dungeons to generate in the desert

## Solutions

New stuff in mgv6_spflags.

## Additional context

I'm writing a game that reproduces Minetest-c55 0.3 and these get in the way.

**Comment by wsor4035** [comment]
related: https://github.com/minetest/minetest/pull/13019

**Comment by sfan5** [comment]
> Could trailgen, if merged, be an indirect solution to your issue?

In general, yes. My issue, not really.
