### ISSUE TITLE
Make the game bar easier to navigate when owning a copy of 500-or-so games.

### ISSUE THREAD

**Issue by 56independent** [minetest/minetest#13418]
## Problem
The Minetest game pool is growing at a fast pace yet the GUI has barely adapted to it. First, it removed games from the world-creation work-flow and moved them to a better place... unless you have hundreds of games and have to press that right-arrow button what feels like 600 times to reach the game you want (or that plus button that makes the problem worse, thankfully at the end to help reduce the problem).

And since every time you leave, the game-bar resets position to the beggining, it can get annoying to trail each new game going sequentially down the list.

These navigation options are intuitive but very tedious to use. Instead, some improvements to the existing system can better adapt to Minetest's high game count and the nature of humans to be greedy and get all the games they like in that plus-button menu, just like children in a sweet shop. 

## Solutions
Here is a good solution-pack for end-users:

* A bottom-aligned scrollbar in addition to the arrow buttons to make navigation easier.
* A Endless-Sky-like series of key-multipliers to the arrow (normal goes 1 game forwards, shift goes 5 games forward, and control goes 10 games forward if those keys are pressed down, and putting two together multiplies (shift+control goes 50 games))
* A green "focus square" underneath the game. Arrows "push" the focus square, characters find the games that begin with that letter (like in the mod menu), and enter selects that game and moves focus to the world selection screen.

## Alternatives
If we we could not implement the above due to technical constraints, try just:

* A green "focus square" underneath the game. Arrows "push" the focus square, characters find the games that begin with that letter (like in the mod menu), and enter selects that game and moves focus to the world selection screen.

**Comment by y5nw** [comment]
This sounds like an interesting addition to #6733.

I could imagine this being addressed by a gridview-like game selection menu.

**Comment by Zughy** [comment]
See previous comment, closing here

**Comment by 56independent** [comment]
Ah dammit, i was searching in too close of a scope using "game bar" so i didn't find that issue. I'll refine my searching to avoid making so many duplicates.

Yeah, something like the GNOME app selector screen accessed using some form of keybind (proposing a new "Minetest superkey" for the all-new propietary Minetest-flavour keyboard! (JOKE)) or button could be helpful and make Minetest feel more like an engine then a game in itself, helping improve first-impressions. Along with this, some searchbar would be helpful, complete with a little section below showing worlds and mods by that name, ready for selection.

When a world is selected, the world will be run inside the game it was made in (which will come as a detail in square brackets as a throwback to older Minetests). When a mod is selected, one can then apply it to worlds using a reverse mod selection screen (where we have the mod, a list of worlds, and the ability to select them for addition of mods). Obviously, this is quite complicated and difficult to implement, so we can leave it for later.

Alongside this, we might as well (Warning: leaving scope; terminate your reading session if you wish to remain within the scope of the reply) begin shipping Minetest with the top 10 games on the ContentDB leaderboard at the point of each release from ContentDB, installed-on-the-fly at each first-run, to allow first-time users more selection and introduce the power.
