### ISSUE TITLE
privacy respecting ip hash of some kind to detect alts on servers

### ISSUE THREAD

**Issue by JasonTable** [minetest/minetest#13436]
## Problem

someone had their server flooded with fake users. so lets think about this for a second. anyone can make a server look bad and look like they are inflating the player count to get to the top of the rank. i have one idea to mitigate that. tho i admit its not very good

## Solutions

make a unique identifier public. like how the usernames are public on the server list, make it so servers share a special identifier. it could just share the ips of all the players but that would be bad for privacy. so instead, make it hash the ip along with a random string of characters that is unique to each server and only known by the server and display the hash result publicly to the server list. so if a bunch of players with the same IP joins, people will NOT know what the IP is but they will know its the all the same IP. and the server list can treat it like its just 1 player and not 30.

## Alternatives

i dunno. its a stupid solution to a stupid problem.

## Additional context

If a server admin actually wanted to inflate their player count, they could bypass this and generate different IDs for each fake player but this will at least mitigate people who try to make other peoples servers look bad.

**Comment by rubenwardy** [comment]
Too much cost (security/privacy/implementation) for not much benefit

**Comment by NathanSalapat** [comment]
If a server own is worried about this they can already set a limit on accounts per IP.
