### ISSUE TITLE
How to rebase PRs after lua_api.txt -> MD change

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#13438]
To rebase other PRs without conflicts:

```
git remote add upstream https://github.com/minetest/minetest

git fetch upstream
git rebase --onto b1786e88ac8921d9c4f0cfe366fdf7e2c965984c $(git merge-base HEAD upstream/master)
git pull --rebase upstream master
```

If you have any issues, comment in your PR and/or post on #minetest-dev

**Comment by Desour** [comment]
I just did:
```
git rebase b1786e88ac8921d9c4f0cfe366fdf7e2c965984c
git rebase master
```
And it worked fine for me.

**Comment by rubenwardy** [comment]
> I just did:
> 
> ```
> git rebase b1786e88ac8921d9c4f0cfe366fdf7e2c965984c
> git rebase master
> ```
> 
> And it worked fine for me

This is simpler, didn't want to assume people had master up to date though
