### ISSUE TITLE
The game's default jump is like being on the moon, it looks very uncomfortable

### ISSUE THREAD

**Issue by slwyts** [minetest/minetest#13449]
The game's default jump is like being on the moon, it looks very uncomfortable, please modify it. Like minecraft's jump. Thanks

**Comment by fluxionary** [comment]
there's various settings to control player physics:

https://github.com/minetest/minetest/blob/4158b7297197dcab7bb8101281ccd90be890968a/builtin/settingtypes.txt#L764-L806

**Comment by Bituvo** [comment]
You can also use `set_physics_override`.

**Comment by ixPost** [comment]
You mean low jump force and low gravity?

**Comment by Bituvo** [comment]
I'm not sure what you mean. You can also change a players' gravity using `set_physics_override`.

**Comment by ixPost** [comment]
Not planned! He's saying it doesn't feel right and that's effectively a issue.(Thou it doesn't feel floaty to me.)

**Comment by Bituvo** [comment]
Read my previous post... this isn't an issue. This issue is invalid and needs to be closed
