### ISSUE TITLE
Falling nodes get stuck on top of the void

### ISSUE THREAD

**Issue by Niklp09** [minetest/minetest#13459]
##### Minetest version
```
5.7.0
```

##### OS / Hardware

Operating system: Ubuntu 22.04 (server)
CPU: i9-9900K

##### Summary
If you dig out blocks under sand and gravel so that the sand and/or gravel falls down onto the bottom of the world sometimes the entities don't disappear into the void (or become nodes), they stay on the bottom but you can't dig them or interact with them in any way.

![grafik](https://user-images.githubusercontent.com/89982526/234083983-baa6b373-0c64-48c1-a7a4-ceecc84ec04e.png)

##### Steps to reproduce
1. Teleport to world border/void
2. Place some blocks with `falling_node` group (e.g. (sand or gravel) over a non falling block (e.g. stone)
3. Dig the normal block
4. See what happens
![grafik](https://user-images.githubusercontent.com/89982526/234084268-e0487a4e-fc9e-4e7d-a55b-c31991828b7f.png)

**Comment by PrairieAstronomer** [comment]
I saw this in 5.6.1 too. Can confirm it exists.
