### ISSUE TITLE
Crash in C++: vector::append, seemingly inside minetest.find_path()

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#13453]
Got this crash:
```
2023-04-22 22:39:29: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'pm' in callback luaentity_Step(): vector::_M_default_append
```

The offending Lua code:
```
self._path = minetest.find_path(a1, a2, r, 1, 1, "A*_noprefetch")
```

**Comment by BluebirdGreycoat** [comment]
Ok, now I've got a std::bad_alloc, same place in the Lua:

```
2023-04-22 23:11:15: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'pm' in callback luaentity_Step(): std::bad_alloc
```

Hmmm .....

**Comment by BluebirdGreycoat** [comment]
Both times this happened right after a player teleported; best guess is that the path search region is too large (the destination pos, `a2` is -- in some cases -- derived from the position of a player).

**Comment by Desour** [comment]
IIRC, someone reported a similar issue somewhere (was it irc?), and it turned out to be a stack-overflow.
Sounds like it's similar here.

**Comment by sfan5** [comment]
> IIRC, someone reported a similar issue somewhere

#7132

**Comment by Zughy** [comment]
Closing in favour of #7132 and because OP hasn't followed the template
