### ISSUE TITLE
Sudden FPS drop inside a spherical volume

### ISSUE THREAD

**Issue by superfloh247** [minetest/minetest#13463]
##### Minetest version
```
5.8.0-dev-0fb6dba
```

##### OS / Hardware
Operating system: OSX 13.2.1
CPU: Apple M1pro

GPU model: Apple M1pro
OpenGL version: 2.1

##### Summary
Sudden FPS drop when I move a tiny bit backwards, happens with viewing range 300 and down to 20.

Please guide me in a direction where to look and what to test, which settings to change etc. so that I can provide meaningful input to track this down.

![screenshot_20230427_115246](https://user-images.githubusercontent.com/26180993/234829620-36fb86f0-5acb-4023-a0e3-9ab0435a3d90.png)

![screenshot_20230427_115309](https://user-images.githubusercontent.com/26180993/234829709-5fe256fa-d972-49cd-a568-27e4cd616c74.png)

**Comment by rubenwardy** [comment]
Hi, please try Settings > All Settings > Search for occlusion culler > Set it to "loops". If it doesn't help, set it back to bfs

**Comment by superfloh247** [comment]
loops culler reaches higher FPS values (>90 vs 60 with bfs) in the "no FPS drop" position, but also drops to 30 in the problematic position

![screenshot_20230427_123759](https://user-images.githubusercontent.com/26180993/234838637-7e797d76-6691-4e3c-a9c7-246e93a5e84b.png)


![screenshot_20230427_123813](https://user-images.githubusercontent.com/26180993/234838661-a6e733c8-11c8-4388-992a-0b6a3235dc90.png)

**Comment by superfloh247** [comment]
Another observation: FPS drop to approx 25 in that position when I turn around 180° or when I look to the ground.

position difference: 1 node

![screenshot_20230427_124421](https://user-images.githubusercontent.com/26180993/234839808-6882ddc4-3812-4914-be10-2c04a8347d6e.png)


![screenshot_20230427_124429](https://user-images.githubusercontent.com/26180993/234839859-d53ca43b-4b43-4939-bfa6-c8bc5e6120af.png)

**Comment by superfloh247** [comment]
minetest client conf (some lines removed)

maintab_LAST = settings
world_config_selected_mod = 34
screen_h = 916
screen_w = 1512
mute_sound = true
free_move = true
fast_move = true
pitch_move = false
sound_volume = 0
enable_fog = true
viewing_range = 300
main_menu_technical_settings = true
fps_max_unfocused = 15
mgv7_spflags = caverns,floatlands,ridges,mountains
wieldview_update_time = 2
wieldview_node_tiles = false
minimap_shape_round = true
connected_glass = true
noclip = false
fsaa = 2
trilinear_filter = false
node_highlighting = box
leaves_style = fancy
mip_map = false
enable_waving_leaves = false
bilinear_filter = false
enable_waving_plants = false
anisotropic_filter = false
tone_mapping = true
enable_clouds = false
enable_3d_clouds = true
performance_tradeoffs = true
mgflat_spflags = lakes,hills,caverns
server_announce = false
opaque_water = false
enable_waving_water = false
shadow_levels = 3
enable_dynamic_shadows = true
enable_server = false
port = 30001
shadow_map_color = false
shadow_map_texture_size = 2048
shadow_map_max_distance = 140
shadow_map_texture_32bit = true
shadow_filters = 1
update_last_checked = 1682591818
autojump = false
doubletap_jump = false
keymap_cmd_local = KEY_PERIOD
keymap_increase_viewing_range_min = KEY_PLUS
keymap_rangeselect = KEY_KEY_R
aux1_descends = false
keymap_decrease_viewing_range_min = KEY_MINUS
enable_bloom = true
enable_bloom_debug = false
inventory_items_animations = true
saturation = 1
enable_mesh_cache = true
mesh_generation_threads = 0
fps_max = 120
vsync = true
client_mapblock_limit = 75000
occlusion_culler = loops
client_mesh_chunk = 4
meshgen_block_cache_size = 64

**Comment by Desour** [comment]
Is there maybe a cellar or cave nearby?

Getting different fps at different positions is not a bug per se. You're probably just near a tipping point where fewer blocks are occluded.

**Comment by superfloh247** [comment]
I'll start digging right away.

**Comment by debagos** [comment]
I checked that exact location (I'm the admin of the server where it happend), tried moving around, looking up and down and around but I always kept having 90 to 144 FPS, no matter what I do...
I checked for caves, there are a few little tunnel, but nothing out of the ordinary.
My first guess was an insane amount of entities, but the server was pretty much idling at that time, so I don't think that was the case, so I think it was/is a client side quirk.
Wondering if you still can reproduce that issue @superfloh247 ?

**Comment by debagos** [comment]
I tested it with the posted settings now, still not happening.
But I realized that even with `fps_max = 120` set, I still have around 123 to 126 FPS :thinking:

**Comment by superfloh247** [comment]
another observation, looking directly down.
at y=7.5 I get 29FPS up to y=13.3, then at 13.4 it jumps to 118FPS. when I fly down to y < 13.4, eg 12.5, FPS fall to 28 again

![screenshot_20230502_154247](https://user-images.githubusercontent.com/26180993/235685948-ea768c12-4db3-463f-a174-48bd2573aa43.png)

![screenshot_20230502_154357](https://user-images.githubusercontent.com/26180993/235685964-5d42ed42-6163-4a06-918a-be2836a9d791.png)

**Comment by superfloh247** [comment]
next observation: the problematic volume is not a map block. looks more like a sphere.

I started to mark the border of the FPS drop with steel blocks, the grey almost complete circle on the map

<img width="358" alt="Bildschirm­foto 2023-05-03 um 18 05 08" src="https://user-images.githubusercontent.com/26180993/235974590-e7fd3498-3a8c-41e5-adc0-b91c631b42b9.png">


<img width="358" alt="Bildschirm­foto 2023-05-03 um 18 05 08" src="https://user-images.githubusercontent.com/26180993/235974338-f0105c18-6b72-481d-bd43-f784966bd74f.png">

**Comment by superfloh247** [comment]
yes, it's definitely a sphere, with the center in the center of a map block 

![screenshot_20230503_192828](https://user-images.githubusercontent.com/26180993/235995892-6596e8a5-82c4-4d82-817a-27718a071744.png)

**Comment by rubenwardy** [comment]
What does it look like with wire frames mode? (F5, you'll need the debug priv)

**Comment by Desour** [comment]
There's a hole in the ground. Is this hole new or did you just dig it? And is there more empty space below that block?

(FYI, the sphere probably is the bounding sphere used for occlusion culling.)

**Comment by sfan5** [comment]
FWIW you can use `enable_local_map_saving` to get a dump of the relevant area even without any debug priv.

**Comment by superfloh247** [comment]
> There's a hole in the ground. Is this hole new or did you just dig it? And is there more empty space below that block?

The hole is new, I rigged out the center of the sphere and placed blocks there and removed them again to overwrite any weird meta information that might have been there, but no success, FPS still drop

**Comment by superfloh247** [comment]
> FWIW you can use `enable_local_map_saving` to get a dump of the relevant area even without any debug priv.

OK, I did that. Interesting feature, I was not aware of it :)

My local game does not suffer from the FPS drop, but the area now consists of mostly unknown nodes.

Screenshot in wireframe mode (obviously) directly into the center of the sphere

![screenshot_20230504_020009](https://user-images.githubusercontent.com/26180993/236076263-617963c4-a91b-47f1-a336-78e6537d21f8.png)

**Comment by superfloh247** [comment]
looks like it's no a client thing, other players on windows and linux also have this effect.
It's public, everybody can have a look. wunderwelt.one:30000
it's a bit remote and hard to get there, try to get me or the admin on discord to teleport you https://discord.com/invite/AW27td4ZAV

**Comment by Zughy** [comment]
Can't reproduce. Also, the area pointed by OP is different now, so the minimal test is probably gone. Labelling as Possible close

**Comment by Zughy** [comment]
Maybe different MT versions? Unless you ask them specifics, it's impossibile for us to investigate further

**Comment by superfloh247** [comment]
I'll ask everybody on the server to visit that region with me and check for FPS drop and then I'll collect system info

for me this affects:
Minetest 5.8.0-dev-12e9867 (OSX)
Using Irrlicht 1.9.0mt12
and
Minetest 5.7.0 (OSX)
Using Irrlicht 1.9.0mt10

**Comment by Zughy** [comment]
@superfloh247 any updates?

**Comment by superfloh247** [comment]
sorry, no updates yet

**Comment by sfan5** [comment]
What would help here is either 
1) a way to reproduce the issue
2) or hard data, namely profiling data for the Minetest client (e.g. `perf` on Linux, @lhofhansl might know how to do this on windows)

if we collect the system information of people who have this issue it just leads to more guessing.

**Comment by superfloh247** [comment]
this fixes it for me!

https://github.com/minetest/minetest/issues/12900#issuecomment-1384524625

`transparency_sorting_distance = 0
`

**Comment by nininik0** [comment]
when i build a worldedit sphere and went inside it it went from 50 fps to 11 fps, same can be said about a cylyder
