### ISSUE TITLE
Everytime you go to "Most Used" settings, shadow setting are set back to the chosen preset.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13478]
##### Minetest version

Master branch

##### OS / Hardware

Does not matter.

##### Summary and Steps to reproduce

Open settings, search for "shadows" make some changes.
Then go to "most used", scroll down, to shadow presets, **but make no changes**.
Notice how your shadow settings are reset to the whatever the preset was.

@rubenwardy

**Comment by rubenwardy** [comment]
It's the exact same code that was on the previous settings tab. Looks like it always runs, regardless of whether the dropdown is changed
