### ISSUE TITLE
Make footsteps sound faster when sprinting

### ISSUE THREAD

**Issue by Bituvo** [minetest/minetest#13474]
## Problem

I think it would be fitting if footstep sounds played faster when you were sprinting (using Aux1).

## Solutions

Make footstep sounds play faster when sprinting.

## Alternatives

Don't do anything.

**Comment by fluxionary** [comment]
sprinting is not an engine behavior, it is 100% mod behavior.

**Comment by MathPlusEnglish** [comment]
Doesn't that already happen?
