### ISSUE TITLE
Default Sneak keybind does nothing on OS X Mavericks.

### ISSUE THREAD

**Issue by TheRabbitologist** [minetest/minetest#1347]
In the 2014-05-23 zipped build of Minetest for OS X, pressing Left Shift (the Sneak default keybind) does not trigger sneaking. The fix is fairly trivial: rebind Sneak from its default to Shift. Perhaps the default Sneak keybind for OS X specifically could be changed to Shift?

EDIT: Metadata from the pause menu:
```
VER=0.4.9-234-g94dba66-dirty
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
```

**Comment by nerzhul** [comment]
It's a very old build and we don't have a user feedback since this issue. I close it.
