### ISSUE TITLE
Using IBus breaks non-Latin input in Minetest

### ISSUE THREAD

**Issue by slashdevslashurandom** [minetest/minetest#13473]
##### Minetest version
```
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

##### OS / Hardware
Operating system: Alpine Linux v3.17
CPU: AMD Ryzen 3 4300U with Radeon Graphics

##### Summary
Whenever I play Minetest while also running IBus, attempts to enter non-Latin text seem to fail.

When typing cyrillic characters, the end result is a mixture of random CJK characters, close to what is seen in the console output of bug #1638 (although unlike that bug, these same CJK characters also actually appear in game). When I try to use the "compose key" to type characters with diacritics, such as the ĉ used in Esperanto (`Compose`+`^`+`c`), the compose key is ignored and the characters are typed as is (`^c`).

When IBus is not being used, everything works okay. However, IBus is a necessary part of the system for those who need to type in languages with complex writing systems, like Chinese and Japanese.

##### Steps to reproduce
On my GNOME-based system, IBus is enabled whenever I have a layout that uses it in the keyboard layouts list (for example, Japanese using Anthy).

**Comment by y5nw** [comment]
Have you tried compiling MT (and IrrlichtMt) with SDL? I had some problems with Minetest and ibus since around 5.6.1 until I compiled MT/IrrlichtMt with SDL. (Specifically, the client would randomly "lock up"/stop responding in chat. I was reluctant to open a bug report because IrrlichtMt is apparently moving to SDL anyway where this is not an issue.)

**Comment by sfan5** [comment]
FWIW I use fcitx5 (with mozc for IME) and it works perfectly fine no problems.

**Comment by y5nw** [comment]
Weirdly, I do not think I had issues with fcitx (both versions) and MT.

That said, I recall ibus working with MT properly in a Debian VM. That was over a year ago though.

**Comment by slashdevslashurandom** [comment]
> Have you tried compiling MT (and IrrlichtMt) with SDL? I had some problems with Minetest and ibus since around 5.6.1 until I compiled MT/IrrlichtMt with SDL. Specifically, the client would randomly "lock up"/stop responding in chat, and I had to kill MT using xkill; I also had to restart ibus after killing MT (not when closing MT regularly) to make IME usable in MT again. (I was reluctant to open a bug report because IrrlichtMt is apparently moving to SDL anyway where this is not an issue.)

I didn't have issues like that, but i can confirm that rebuilding Irrlicht with SDL being used *partially* resolves the problem: Cyrillic works, but CJK input and the Compose key still doesn't. I'll try to ask my distro's maintainers to use SDL for Minetest in the meantime, but I believe the issue still remains.

**Comment by y5nw** [comment]
> Cyrillic works, but CJK input and the Compose key still doesn't.

Interesting. I can use "Intelligent Pinyin" (Chinese input) on ibus in Minetest, although on a 5.8.0-dev version.

> I'll try to ask my distro's maintainers to use SDL for Minetest in the meantime, but I believe the issue still remains.

I am not sure about the current development progress on using MT with SDL, but

* The 5.7.0 release with IrrlichtMt 1.9.0mt10 does not seem to accept the `USE_SDL2` flag.
* The transition to SDL seems quite recent, so I assume the developers have a justifiable reason to not have IrrlichtMt built with SDL yet.

**Comment by sfan5** [comment]
> I'll try to ask my distro's maintainers to use SDL for Minetest in the meantime

Don't, it's still experimental.

**Comment by Zughy** [comment]
About CJK characters: related #13813. Might actually be same problem?

**Comment by wsor4035** [comment]
@slashdevslashurandom could you confirm/deny the above?

**Comment by slashdevslashurandom** [comment]
I don't think so, for me the Chinese/Korean characters I get when I try to type in Cyrillic do get outputted properly and not filtered. I can also type in Japanese using a different app, paste it into Minetest and have that show up correctly in chat.
