### ISSUE TITLE
Horrendous flickering (z-fighting)

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#13499]
v5.8-dev

With translucid nodes under the water.

See the image, the spots flicker when the player moves.

![Captura de pantalla de 2023-05-12 23-06-42](https://github.com/minetest/minetest/assets/13217027/f91f9e99-5f21-48f2-8807-7b20c4499f4b)

**Comment by runsy** [comment]
You can try it with The Samz game.

Just to add a ice block underwater.

**Comment by runsy** [comment]
This not happened with 5.7

**Comment by Desour** [comment]
Please fill out the issue template. You haven't even provided the nodedefs.

**Comment by runsy** [comment]
> Please fill out the issue template. You haven't even provided the nodedefs.

What is that? The names of the nodes?

**Comment by Desour** [comment]
> > Please fill out the issue template. You haven't even provided the nodedefs.
> 
> What is that? The names of the nodes?

nodedef = node definition.

**Comment by runsy** [comment]
> > > Please fill out the issue template. You haven't even provided the nodedefs.
> > 
> > 
> > What is that? The names of the nodes?
> 
> nodedef = node definition.

```
minetest.register_node("nodez:water_source", {
	description = S("Water Source").."\n"..
		"Drowning damage: 1",
	drawtype = "liquid",
	waving = 3,
	tiles = {{
		    name = "nodez_water_animated.png"..WATER_COLORIZE..WATER_ALPHA,
		    animation = {type = "vertical_frames", aspect_w = 16, aspect_h = 16, length = 4.0},
		    backface_culling = true,
	}},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drowning = 1,
	liquidtype = "source",
	liquid_alternative_flowing = "nodez:water_flowing",
	liquid_alternative_source = "nodez:water_source",
	liquid_viscosity = WATER_VISC,
	post_effect_color = {a = 64, r = 100, g = 100, b = 200},
	groups = {water = 3, liquid = 3},
	sounds = sound.water(),
})
```

```
minetest.register_node("nodez:ice", {
	description = S("Ice"),
	tiles = {"nodez_ice.png"},
	is_ground_content = false,
	drawtype = "glasslike",
	use_texture_alpha = "blend",
	paramtype = "light",
	paramtype2 = "glasslikeliquidlevel",
	groups = {cracky = 3, cools_lava = 1, slippery = 3, build = 1},
	sounds = sound.ice(),
})
```

**Comment by runsy** [comment]
Reopen inmediately this, it is a issue introduced in 5.8.

**Comment by runsy** [comment]
Please reopen. Z-fighting with transparent nodes. Big issue.

**Comment by runsy** [comment]
![Captura de pantalla de 2023-06-04 15-27-34](https://github.com/minetest/minetest/assets/13217027/8e49e73d-53f9-4d25-b89f-8f3202efff75)
![Captura de pantalla de 2023-06-04 15-27-25](https://github.com/minetest/minetest/assets/13217027/d7351f3d-985a-41bd-a149-61d1e2d3eb5e)

**Comment by runsy** [comment]
Vines disappear under another angle.

**Comment by NathanSalapat** [comment]
A picture does no good without node definitions and textures. Furthermore what graphics settings are you using? We can't help if we don't have all the information.

**Comment by fluxionary** [comment]
the first example looks like backface culling should is not enabled for water nodes, perhaps related to what's documented in #3704. i'm not sure what's up w/ the vines, but it seems other mods (ethereal, plantlife_modpack) specify `drawtype="signlike"` for their vines, perhaps that's necessary.

it's not an identical setup to runs's, but here's some code to produce z-fighting:

```lua
minetest.register_node("zfighting:node", {
	description = "zfighting node",
	tiles = { "[combine:16x16^[noalpha^[colorize:#FFF:255" }
})

minetest.register_node("zfighting:nodebox", {
	description = "zfighting nodebox",
	drawtype = "nodebox",
	paramtype2 = "facedir",
	tiles = { "[combine:16x16^[noalpha^[colorize:#000:255" },
	node_box = {
		type = "fixed",
		fixed = {
			{
				-1 / 2,
				-1 / 2,
				-1 / 2,
				1 / 2,
				3 / 2,
				1 / 2,
			}
		},
	},
})
```

place the "node", then place the "nodebox" below it. this seems to produce z-fighting independent of most graphics settings. i tried w/ and w/out shaders, texture filters, anti-aliasing, smooth lighting. i've tested in 5.6.1., 5.7.0, and dev commit 7221de6edeb80b0512934118bb972288b6825e91.

![image](https://github.com/minetest/minetest/assets/25628292/5364cf42-d60f-4e82-9cd2-783a1424a260)

**Comment by Desour** [comment]
See this as duplicate of #9324.

@fluxionary Your example is not an engine bug, as you caused the z-fighting deliberately.

**Comment by runsy** [comment]
> See this as duplicate of #9324.
> 
> @fluxionary Your example is not an engine bug, as you caused the z-fighting deliberately.

Not duplicate. In stable 5.7 an prior not error.

**Comment by NathanSalapat** [comment]
If you don't show us your code we can only assume you are doing something wrong. Just because something worked in the past and doesn't work the same way now doesn't necessarily mean it's a regression, the previous behavior could have been wrong.

**Comment by Desour** [comment]
Tried now also in 5.7.0, and can't reproduce. It's indeed a regression. Sorry, I didn't see your message earlier that it doesn't happen in last stable.

Will open an issue with the useful info.

**Comment by Desour** [comment]
See  #13569.

**Comment by runsy** [comment]
> If you don't show us your code we can only assume you are doing something wrong. Just because something worked in the past and doesn't work the same way now doesn't necessarily mean it's a regression, the previous behavior could have been wrong.

For example the vine is very simply a nodebox:

minetest.register_node(creeper_name, {
		description = S(def.desc),
		drawtype = "nodebox",
		walkable = false,
		paramtype = "light",
		paramtype2 = "facedir",
		tiles = {tile},
		inventory_image = inventory_image,
		wield_image = def.wield_image or def.inventory_image or def.tile,
		use_texture_alpha = "clip",
		node_box = node_box,
		groups = {
			snappy = 2, flammable = 3, oddly_breakable_by_hand = 3, choppy = 2, carpet = 1, leafdecay = 3, leaves = 1,
		},
		sounds = sound.leaves()
	})

**Comment by fluxionary** [comment]
> Your example is not an engine bug, as you caused the z-fighting deliberately.

the example stemmed from an issue w/ FaceDeer's [castle tapestries](https://content.minetest.net/packages/FaceDeer/castle_tapestries/), it's not something i pulled out of nowhere, i just wanted to simplify it. is z-fighting not considered an issue that can be fixed reasonably? i'm not familiar enough w/ 3d graphics bugs.

**Comment by Desour** [comment]
> > Your example is not an engine bug, as you caused the z-fighting deliberately.
> 
> the example stemmed from an issue w/ FaceDeer's [castle tapestries](https://content.minetest.net/packages/FaceDeer/castle_tapestries/), it's not something i pulled out of nowhere, i just wanted to simplify it. is z-fighting not considered an issue that can be fixed reasonably? i'm not familiar enough w/ 3d graphics bugs.

If 2 or more faces that lie in a plane collide, they z-fight, as it's unclear which face is in front of the other.

If it's a regression you can see it as a bug I guess. Nonetheless, mods should probably try not to put faces exactly between nodes.
