### ISSUE TITLE
Rendering pipeline and post-processing problems on some platforms

### ISSUE THREAD

**Issue by S1LI** [minetest/minetest#13492]
Hello everyone) I don't know if this is the right place to ask my question, but I don't know where else to write. I decided to try compiling Minetest 5.7.0 for the IOS platform. So far, I've had little success. I was able to run Minetest on IOS 15 (Iphone 7 Plus), but I encountered a problem with the game displaying with OpenGL ES 2 shaders enabled. I know that Minetest doesn't officially support IOS, but I want to try to solve this problem. Please help me and tell me in which direction to go. 
System on which the tests are being run: iPhone 7 Plus (IOS 15.6.1)
Problem description:  The problem occurs during the launch of the created world. It consists in the fact that when the OpenGL ES 2 video driver is activated in the settings and shaders are enabled (just activated, without additional types of tone mapping), the display turns blue (I'm attaching a screenshot). 
![screen_1](https://github.com/minetest/minetest/assets/69674483/f230533f-15dc-4667-95b6-100727ea50d6)
The controls work, the sounds work too. Everything is fine in the menu and when loading the world. No errors were found in the debug file. I tried to find the problem myself and came to the conclusion that it is related to the rendering pipeline and post-processing. Node and object shaders work fine. The problem occurs when post-processing is added in the plain.cpp script in the create3DStage method 112 line: 
```
std::unique_ptr<RenderStep> create3DStage(Client *client, v2f scale)
{
	RenderStep *step = new Draw3D();
	if (g_settings->getBool("enable_shaders")) {
		RenderPipeline *pipeline = new RenderPipeline();
		pipeline->addStep(pipeline->own(std::unique_ptr<RenderStep>(step)));
//CHECK
		auto effect = addPostProcessing(pipeline, step, scale, client);
		effect->setRenderTarget(pipeline->getOutput());
		step = pipeline;
	}
	return std::unique_ptr<RenderStep>(step);
}
```
If you exclude this step, the image is returned and, as I said, the node and object shaders work correctly. I think that maybe the second_stage shader is to blame, but my knowledge in this area is very limited. From what I could do, I could simplify the second_stage shader to the simplest possible one that returns the same value as it received. This did not work. I tried to analyze the code of the "addPostProcessing" function a little bit and came to the conclusion that the problem occurs when adding a PostProcessingStep to the RenderPipeline (secondstage.cpp, addPostProcessing, pipeline->addStep(effect), 201 lines): 
```
// final post-processing
shader_id = client->getShaderSource()->getShader("second_stage", TILE_MATERIAL_PLAIN, NDT_MESH);
PostProcessingStep *effect = pipeline->createOwned<PostProcessingStep>(shader_id, std::vector<u8> { TEXTURE_COLOR, TEXTURE_BLOOM_UP, TEXTURE_EXPOSURE_2 });
pipeline->addStep(effect);
effect->setBilinearFilter(1, true); // apply filter to the bloom
effect->setRenderSource(buffer);

if (enable_auto_exposure) {
     pipeline->addStep<SwapTexturesStep>(buffer, TEXTURE_EXPOSURE_1, TEXTURE_EXPOSURE_2);
}

return effect;
```
That's where I stopped. Please tell me in which direction I should move on. Perhaps there is a description of the rendering pipeline and post-processing. If you need any information, I will be happy to provide it. I apologize for any grammatical errors and mistakes in my report. Thank you all for your help. 
Attached is the debug file.
[debug.pdf](https://github.com/minetest/minetest/files/11442772/debug.pdf)

**Comment by sfan5** [comment]
That's hard to say since you're working on an entirely new platform with us knowing very few details on how your setup looks.

As far as I know our OpenGL ES 2 shaders generally, while postprocessing is *not* supported.
Did you check whether it happens with the built-in Irrlicht shaders (`enable_shaders = false`)? Did you try investigating with a graphics debugger? Are you sure all asset files are present in the correct paths? How did you work out the support code given iOS support was removed from IrrlichtMt (https://github.com/minetest/irrlicht/commit/df8881898d08234920696e32f777ee31b7431386)?
