### ISSUE TITLE
Mouse sensitivity is directly linked to window width

### ISSUE THREAD

**Issue by Montandalar** [minetest/minetest#13491]
##### Minetest version

```
Minetest 5.8.0-dev-5cd6a22dd (Linux)
Using Irrlicht 1.9.0mt11
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale
```

##### OS / Hardware

Operating system: Debian Bookworm (11 testing)
CPU: AMD Ryzen 3 2200G

GPU model: Sapphire Radeon RX 570 4GB
OpenGL version: 4.5

##### Summary
Horizontal mouse sensitivity is directly linked to window width, which was previously not the case. If I set my mouse sensitivity for a good setting when the window is maximised, then it's wrong when I open another window and Minetest becomes half width (I use i3 window manager, but window manager/desktop environment should not matter).

##### Steps to reproduce
1. Open a Minetest client and move the mouse around
2. Halve the window width and move the mouse around again. Notice that the camera pans way faster.

**Comment by Desour** [comment]
Can't reproduce. The yaw and pitch change per mouse movement always feel about the same for me.

>which was previously not the case

Since when? Can you git bisect?

**Comment by Montandalar** [comment]
> Since when? Can you git bisect?

I can git bisect a single repo but if this is related to a change in irrlichtMt, what do I even do?

**Comment by Montandalar** [comment]
Closing as I think this is a problem readjusting from another game I have played recently with different mouse sensitivity, and confusing actual camera movement with what happens at the edge of the field of view when the window is wide (wide FOV) and narrow (narrow FOV). I tried 5.6.1 and my -dev version side by side for a bit and they seemed the same.
