### ISSUE TITLE
Incorrect get_natural_light(pos) results above surface

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#13507]
##### Minetest version

```
5.8.0-dev
```

##### Summary
I was under the impression that using minetest.get_natural_light(pos) would only return a value of natural sunlight or moonlight, which seems to work fine out in the open landscape or underground, but...  Building a huge dirt cube above ground and place a meselamp inside, and it still returns a natural light value even though it is clearly not a natural light source.

**Comment by Desour** [comment]
Tried with a small dirt cube, and could not reproduce.
`//lua core.log(dump(core.get_natural_light(core.get_player_by_name("singleplayer"):get_pos())))`

How did you build the dirt cube? If you used worldedit, did you invoke `//fixlight` for the area?
And was the node where you placed placed the light node completely dark?
