### ISSUE TITLE
Shutdown takes a long time on Windows

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13518]
##### Minetest version
Latest (main) from here: https://gitlab.com/minetest/minetest/-/pipelines?page=1&scope=all&ref=master

##### OS / Hardware
Operating system: Windows 11
CPU: Intel

##### Summary
With viewing_range set to 1000 shutting down a game in Windows takes a long time (~~30s~~ 50s or more).
I have **not** observed this in Linux.

(I'm not setup to profile/debug on Windows, just seeing this on my son's - very, very fast - PC.)

##### Steps to reproduce
On Windows. Load any world, set a large viewing_range (and all the server side XXX_distance settings), wait for the surroundings to load, then exit the game. Observe that "Shutting Down" takes a very long time.

**Comment by lhofhansl** [comment]
Happens with official 5.7 as well.

Tried to change sqlite sync levels, no difference.
Look at some performance counters, it's not doing much IO in that time. So really not sure what is going on.

**Comment by sfan5** [comment]
Depends on various factors freeing memory can actually take a bit.
A perf-like tool would help bring light into the dark but no idea how to do that on windows.

**Comment by lhofhansl** [comment]
Actually, stopwatch shows in 50+s. Clearly not acceptable. On Linux I'd track down at least where it is spending time in 5 minutes. On Windows I am mostly blind (and inept).

**Comment by wsor4035** [comment]
@lhofhansl which game/mods was this test done with? on windows i have noticed certain using certain mods/games may trigger this long shutdown rather than just in general

**Comment by lhofhansl** [comment]
Fixed by https://github.com/minetest/minetest/commit/47e557b96ad4b9f053cf35150b2f46fe623b4dc7
