### ISSUE TITLE
A different name for Minetest

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13510]
After a [long talk on IRC](https://irc.minetest.net/minetest-dev/2023-05-14#i_6083383) about whether rename Minetest or not, I thought to open an issue where you can suggest a name.   

:point_right:  names outside the "voxel" and "free/open" nature are encouraged (e.g. Krita, Godot) :point_left: 

**RULES**  
1. A comment shall only contain the suggestion and, optionally, a brief description. Nothing else
2. You're allowed to suggest three names top, **one comment per suggestion** (so choose wisely and don't use your three chances all together)
3. Anyone can take part in it: outsiders, please do!
4. It won't be chosen by likes. If we ever decide to proceed with the renaming, it'll be up to @celeron55 alongside a small group of MT staff to choose the name. This issue only helps us gathering suggestions
5. No insults/trolling/yougotit

Comments not sticking to the rules will be removed  

UPDATE: suggesting "Minetest" is not an option, please stop and read the IRC log

----

EDIT by SmallJoker: If you are looking for a place to discuss naming suggestions, have a look at the following related topics:

 * [The best name instead of Minetest is...](https://forum.minetest.net/viewtopic.php?f=3&t=29497)
 * [3 reasons to *not* rename Minetest](https://forum.minetest.net/viewtopic.php?f=3&t=29513)
 * [Should we rename Minetest? (poll)](https://forum.minetest.net/viewtopic.php?f=3&t=17133) <- oldest topic for the sake of completeness. Please let it rest in peace.

**Comment by Zughy** [comment]
([posting for pgimeno](https://irc.minetest.net/minetest-dev/2023-05-14#i_6083726))
Terraforma

**Comment by savilli** [comment]
kutiko - from Finnish "kuutio" ("cube") and the Finnish suffix "-ikko", suggesting a small cube or a place of cubes.

**Comment by savilli** [comment]
luontia - from Finnish "luonti" ("creation").

**Comment by marco-acorte** [comment]
MineBlockx

**Comment by oong819** [comment]
CreativeFramework - because Minetest let players modifying almost everything

**Comment by valerio-bozzolan** [comment]
HackBlock

**Comment by RecentRunner** [comment]
Fernweh - A German word for the yearning of far away places. I feel a German name is fitting as Minetest is based on the Irrlicht engine. Also the yearning of far away places seems perfect for a procedural game which aims to be whatever game the player wants it to be

**Comment by oong819** [comment]
DeepFog - Minetest's world are usually very large and covered in fog

**Comment by marco-acorte** [comment]
LoFiGame :) ironic about the huge weight of the textures

**Comment by Montandalar** [comment]
Minet - pronounced Minety or min-ette, not sure which I like more yet.

A nod to the old name, catchy, short, and still refers to the "mine" part.

**Comment by MisterE123** [comment]
Remine'd

**Comment by Bituvo** [comment]
"Voxey" - A fork for children

**Comment by Bituvo** [comment]
"Fosscraft" - A reference to the open-source nature of Minetest

**Comment by lhofhansl** [comment]
Here are 10 from CharGPT :)
    CraftVerse
    ModiMine
    BlockForge
    OpenCraft
    ModCraft
    SourceBlocks
    Craftable
    ModuWorld
    Constructia
    OpenMine

**Comment by lhofhansl** [comment]
TerraForge

**Comment by lhofhansl** [comment]
BlockSmith

**Comment by tenplus1** [comment]
I'm all for leaving it as MineTest and only naming the games that people play, like MineClone etc.

**Comment by amreo** [comment]
voxellismo

A mix of english and italian. voxel + ismo. It means a cultural movement of voxel (like modellism)

**Comment by oong819** [comment]
MeseTest - people will less likely see Minetest as an Minecraft's cheap copy, also this name will not terminate it's history and origin

**Comment by hlqkj** [comment]
> UPDATE: suggesting "Minetest" is not an option, please stop and read the IRC log

Sorry if I’m being pedantic, sadly I didn’t have a chance to participate in that IRC conversation.

I just read it all but this isn’t still clear to me, so I ask: a decision to change the name (no matter which one will be chosen) has already been taken, and is that definitive?

**Comment by runsy** [comment]
**_KreiBloko (KB)_**

Means craft block in Esperanto.

**Comment by runsy** [comment]
**Cubexia**

Short and cool.
**CUTINESSES!!!**

**Comment by runsy** [comment]
BLOCKTRIX

"A matrix of blocks"

![blocktrix](https://github.com/minetest/minetest/assets/13217027/6fdcb180-17ed-47be-808b-22e29a9f3dfe)

**Comment by LizzyFleckenstein03** [comment]
Mesetint. See https://github.com/minetest/minetest_game/issues/2077

**Comment by lhofhansl** [comment]
Hey, not cool deleting posts.

**Comment by BluebirdGreycoat** [comment]
I agree - my nomination was one of those deleted (although it followed the rules) and the rules got updated to exclude it.

**Comment by hlqkj** [comment]
Off-topic mark has been used for much more severe “rules violations” in the past - seeing deleted comments in this instance seems rather outrageous.

**Comment by tenplus1** [comment]
My suggestion would be to keep the name: MineTest

It is a well established title that people recognise already, and please, you asked for suggestions but anyone suggesting it's original name seem to be removed by you.

**Comment by Zughy** [comment]
@hlqkj  deleting was too harsh, you're right, I'm sorry, I'll just mark them as off topic.

@lhofhansl see ^. If I let even one single person break the rules, this issue will become a nightmare pretty quick. In your case there were 10 ChatGPT suggestions + the one you picked

@tenplus1 @BluebirdGreycoat the issue is called "A different name for Minetest" and rule n°4 says "**if** we ever decide to proceed with the renaming". We're already aware that many members in the community don't want to see the name changed, I don't think there is the need to remind that to us.

**Comment by rollerozxa** [comment]
Voxeltech - The -tech suffix would sound appropriate for an engine.

**Comment by thedidek** [comment]
Voxelverse or Voxiverse - same concept with two merged words, but sounds not bad.

**Comment by ezamlinux** [comment]
Outsider here ! 

I don't really have a clue for the name but ironically I like "**NodeCore**" which is pretty perfect for the purpose of a " launcher/engine" to dissociate it from minetest the game. Like Veloren with Airshipper. It's true that "Minetest" gives the impression of a clone, or a simple game that wants to take advantage of the notoriety of minecraft with a similar name and it's misleading when i try to explain the concept to some friends.

A new name could really give it an identity of its own.

**Comment by kuba-orlik** [comment]
MineVerse

**Comment by iacore** [comment]
"Minetest is a voxel engine"

**Comment by sbutcher** [comment]
Blockcraft

**Comment by dotoscat** [comment]
cubicuniverse

**Comment by commel** [comment]
MineFramework - because it is a framework base setup for minecraft related games

**Comment by Natureshadow** [comment]
OurCraft

Because the suffix "craft" is important to attract existing Minecraft players, and "our" because it is **our** game and what we make of it, and respects **our** rights, instead of only those of the proprietors.

**Comment by mro** [comment]
the name should sound good, be easy to spell and pronounce in a variety of languages, yield significant hits when searching the internet and have **no further meaning or be cheesy**. Still thinking about it…

**Comment by Ferk** [comment]
MeseCore

**Comment by nurettin** [comment]
Blockistan

**Comment by mitscherdinger** [comment]
Klotz
A german translation of the "commercial" for a log - a brick of wood -  in the early episodes of the cartoon Ren  & Stimpy.
The visual style of such videogames as minecraft, but also of the 8- and 16bit age and their clones, are often described as "Klötzchengrafik" (I would translate as "graphics of small bricks").

**Comment by bcopy** [comment]
Avatacube

**Comment by bcopy** [comment]
Avatacube

**Comment by freshreplicant** [comment]
I'm a big mythology buff, so I was doing some brainstorming based on Finnish mythology and I was drawn to the Finnish goddess of the air and mother of the first man [Ilmatar](https://en.wikipedia.org/wiki/Ilmatar), one of the [Kalevala](https://en.wikipedia.org/wiki/Kalevala)'s key players.

One another name for Ilmatar is Luonnotar. Reading over the suggestions here, it struck me that this may share a derivation with @savilli's suggestion [here](https://github.com/minetest/minetest/issues/13510#issuecomment-1547033844). It's also the name of [a piece of music by Jean Sibelius](https://www.youtube.com/watch?v=LkHuOXhaMdQ).

Then it struck me that the first three letters are L-U-O and if we swap out the O for an A, we have [Lua](https://en.wikipedia.org/wiki/Lua_(programming_language)), which of course is Minetest's scripting language. 

That brought me to:

**Luannotar**. 

It fuses the concept of creation with lua, it has Finnish roots and it's a neologism (i.e. a new word) so it's probably fairly available as far as domains and such go.

@rubenwardy pointed out to me it sounds like a notary program written in lua, but even this association isn't too bad. In the project soon to be formerly known as Minetest, lua is the language of the law, with which you can shape your world. Notar is also the German for notary.

To me, the name sounds pretty epic, with its mythological connotations, like a kaiju's name: "Mecha Tyrannosaur vs Luannotar!"

The logic behind this name could also be used to get variations of @savilli's suggestion:

**Luanti**. If 'luonti' is creation in Finnish, then Luanti is creation through lua.

It could also be:

**Luanikko**, same logic as above but with the Finnish diminutive to achieve the 'cuteness' some posters here are seeking.

**Comment by freshreplicant** [comment]
The logic behind this name could also be used to get variations of @savilli's suggestion:

**Luanti**. If 'luonti' is creation in Finnish, then Luanti is for creating worlds/universes through lua.

**Comment by freshreplicant** [comment]
It could also be:

**Luantikko**, same logic as above but with the Finnish diminutive to achieve the 'cuteness' some posters here are seeking.

**Comment by fentras** [comment]
From @MisterE123:
> In that vein, MeseBox Engine

I actually like the name but I would remove the word "Engine" and capitalization in the middle.

<p>
<details>
<summary>Example Logo</summary>

![Mesebox Logo](https://github.com/minetest/minetest/assets/26721650/c3f8443f-bf7f-4f5f-9887-15be4c4cea03)

</details>
</p>

We get **Mesebox**.

"_Mese_" is a rarest ore in the default game, seems to be well-known and it's also often mentioned in other projects (Mesecons, MeseCraft, Meseport, etc.). "_box_" implies that the game contains many possibilities in a portable package. Also _boxes_ are in the game after all!

<p>
<details>
<summary>Slightly offtopic</summary>

The whole name reminded me of a game engine called _GameBox_ which is used by _Nadeo_ for all _Trackmania_ games so it clicked with me that **Mesebox** could actually fit nicely as it is, in fact, a game engine too.

</details>
</p>

**Comment by ThibaultLemaire** [comment]
[> **NodeCore**](https://github.com/minetest/minetest/issues/13510#issuecomment-1552684840)

I think NodeCore is a pretty epic name, but it's already the name of a(n awesome) [Minetest game](https://content.minetest.net/packages/Warr1024/nodecore/) by @Warr1024

**Comment by Bituvo** [comment]
Libreworld?

**Comment by kromka-chleba** [comment]
**Advanced Voxel Engine**

The name is simple and explains what the thing is.

**Comment by Destroyinator69420** [comment]
cyberblox is a good name.

**Comment by Jasperko1** [comment]
Realm + Mine = Realmine? How about this?

**Comment by sofar** [comment]
Off-Topic but I feel it should be added here for those people suggesting `mese` as part of a new name: originally the word comes from something related to MSN *mese*nger. IMHO it should not be part of a new name, since it wouldn't solve any problem that renaming would aim to achieve.

**Comment by mro** [comment]
Mymine, maybe.

**Comment by runsy** [comment]
I delete my 3 before names, for the poor reception.
Now I want it to be called:
**KreiBloko**
comes from Esperanto Craft Block

**Comment by Zughy** [comment]
@runsy I'm sorry but that's not how it works: you had your chances like anyone else, and I explicitly suggested in the first post to not spitball a name after the other (a thing you did). Rules are equal for everyone

**Comment by omartekTest** [comment]
**M.e.s.e.**
I like mese-trend find in the comments. It's the Minetest Environment System Evolution

**Comment by lhofhansl** [comment]
Please just close and end this thread. Instead of collecting ideas for names, we're marred by weird rules! It as become useless.

This comment is probably going to be deleted or marked off-topic anyway... Fine, find a name without me.

**Comment by TheShadowOfHassen** [comment]
Balimole

**Comment by loffren174** [comment]
Dyncubus - dynamic, because the engine allows to dynamically shape and reshape voxel-made objects in the world, as well as to alter the rules of the world itself; and cubus for the atoms making up said world.

**Comment by runsy** [comment]
> Concubator

Very similar to Concubine word. LOL.

Discarted.

**Comment by jostgrant** [comment]
Testonic 

A play on tectonic while still keeping the lineage of the `test` name in a way that doesn't rely on Minecraft's -- which should keep it distinct.

Here are the definitions (sourced from Oxford), that come up when you Google "define tectonic":

> 1. relating to the structure of the earth's and the large-scale processes which take place within it.

>> (of a change or development) very significant or considerable.

> 2. relating to building or construction.

I also happen to have the GH Org, for a Minetest-adjacent project I was intending to do but would gladly hand it over for an upstream rebrand of MT. :^)

**Comment by Treer** [comment]
MineTek

switching "Test" for a word that sounds similar gives an upgrade path for wordplays
* MoonTest →  MoonTek
* Lord of the Test →  Lord of the Tek

needn't be Tek, that word's just on-theme for an engine.

**Comment by sirrobzeroone** [comment]
If it is an engine then it can be short, bit like Unity - Doubt c55 would appreciate this but his surname is a nice word if I understand correctly means forest medow in finnish keeps some link to the history of where the engine started: 

**Ahola**

**Comment by ancientmarinerdev** [comment]
Voxelopia - It's a voxel engine, and it gives many possibilities. It isn't about crafting, or mining neccessarily. It's realising dreams. (Voxel Dreams kinda looks taken vaguely too which is unfortunate.

**Comment by ThibaultLemaire** [comment]
**Voxel Populi** -- a play on "Vox Populi". (Might be shortened to VoxelPop, or VoxPop)

**Comment by Shad-MOrdre** [comment]
A pixel represents a 2D point.  A voxel a 3D point.  MT is a new paradigm.

A new word is needed to describe the potential of programming a "voxel".  Whether it be a node or an entity, block or mesh, it is programmable, and moves through a voxelized space.

Minetest should not be thought of as a game engine.  You can mod Minecraft, it's still a game.  You can mod Minetest the engine into any type of tool you wish, whether it be GIS, 3D modelling, AI / cellular automata, or as an interface to a system, like the one in Jurrasic Park.

I propose **Aixel**, pronounced like axle.  Artificial Intelligence + -xel. 

A new word to describe the real power of Minetest, beyond the mere limits of a game engine.


Shad

**Comment by NA0341** [comment]
> @ezamlinux: I like "**NodeCore**" which is pretty perfect for the purpose of a " launcher/engine" to dissociate it from minetest the game.

**MineCore**
The current name is not bad, but "test" sounds generic & draft - like. I wouldn't think of it like a finished product but rather an experiment of some sort with no specific goals.
As for the name: `Mine` is much more true than for MC with the possibilities in MT - and `Core` gives more an idea of an engine rather than a game that's in one piece.

**Comment by IniKiwi** [comment]
I like "minetest"

**Comment by Mooncarguy** [comment]
Meshload or Meshload Engine

**Comment by dstar4138** [comment]
MicroTerrae (roughly Small Worlds)

And.. could "Minetest" still be used for "Minetest Game" so public references still "work", But "Minetest" runs on whatever we end up naming the core framework?

**Comment by Pantyhose-X** [comment]
**Calsle** , **CALSLE**
**Calsle** is mainly inspired by the [lojban](https://en.wikipedia.org/wiki/Lojban) word [Calsle, meaning is a voxel of model/object](https://la-lojban.github.io/sutysisku/lojban/index.html#seskari=cnano&sisku=calsle&bangu=en&versio=masno)

**Comment by cx384** [comment]
### **Meset**

Description:
- Could be interpreted as "Me set"ing something, in the sense of building a world for/by myself.
- Or as "meet" if the "s" gets omitted, in the sense of meet for sure.
- It is basically Minetest truncated such that it contains MESE (therefore less changes that people need to get used to)
- Does sounds less like the name of a game, but more of an engine. 
- A short name has its benefits, also in doubt it can be called "Meset Engine" like it is often done with [Godot](https://godotengine.org/). 
- Месец means moon in Serbian, therefore it could be a connection to the naming of lua
- Has very little room for interpretation, as it should be the case for an engine. No allusions to any game related things, e.g. mine, cube (in the sense of sharp, pixelated cubes), voxel (in the sense of a strict grid, manipulating nodes), craft, survival ...

**Comment by efa** [comment]
OpenCraft

**Comment by DragonSWDev** [comment]
TerraCore. Word "core" should suggest that this is engine that can be extended in many possible ways.

**Comment by DragonSWDev** [comment]
CraftCore

**Comment by nininik0** [comment]
MeseCore

**Comment by fluorescently** [comment]
The first cube
Do you remember your first time interacting, placing or breaking a cube? What was the first cube? How did this world came to be.

**Comment by PeppeFailla** [comment]
VoxelCore or something like that

**Comment by jasons393** [comment]
Maybe Terranode?

**Comment by BasToTheMax** [comment]
Meegy

**Comment by FreeLikeGNU** [comment]
**moxelu**  - *portmanteau of modding voxels (with) Lua*.   

I avoid ending the name with "lua" to avoid trademark nonsense. 

The "mox" of moxelu can also represent the moxie (determination and playful spirit) our community has.

**Comment by FreeLikeGNU** [comment]
**lunodemod** (doot doo dah doo doo) -  *portmanteau of Lua node modding*.

**Comment by FreeLikeGNU** [comment]
**masochraft** - masochism (coding, releasing and modding) can be constructive!

**Comment by mahdihasan2006** [comment]
**Craftscape** - An expansive virtual landscape where crafting and creation know no bounds, encouraging players to unleash their imagination.

**Comment by mahdihasan2006** [comment]
**Createopia** - Discover a utopia of creativity, where players can freely create, modify, and share their own unique creations with others.

**Comment by mahdihasan2006** [comment]
**CreativeCore** - Unleash your creativity with CreativeCore, a game engine that offers a core set of powerful tools and features for game development, empowering you to build worlds that captivate and inspire.

**Comment by csevier** [comment]
It's a voxel engine for game making. It's voxelbased, ie blocks. It's FOSS software, which imo is one of the important things to market. It's why I'm here.  But it's also freedom of creativity with  said blocks. 

LibreBlocks

**Comment by groggone** [comment]
Minecraft

**Comment by nininik0** [comment]
> Minecraft

Bro what the actual "" are you some kind of hater or something

**Comment by BasToTheMax** [comment]
> Minecraft

Copyright issues 💀

**Comment by grat72** [comment]
CraftedWorlds or just CraftWorlds

**Comment by tigercoding56** [comment]
call it openminecraft  , as in openArena , opensurge ,etc

**Comment by Megamichi123** [comment]
Voox=Vox=Voxel +Box

**Comment by Megamichi123** [comment]
ChatGPT names

1. NodeCraft
2. VoxelVerse
3. EngineWorld
4. BlockNode
5. PixelEngine
6. VoxelCraft
7. NodeRealm
8. BlockBuilder
9. EngineCraft
10. VoxelNode
11. NodeGrid
12. BlockEngineer
13. VoxelWorld
14. EngineBlocks
15. NodeVortex
16. BlockCrafters
17. VoxelEngine
18. EngineVerse
19. NodeBlaster
20. Blocktopia
21. VoxelGrid
22. EngineNode
23. NodeCrafters
24. BlockVortex
25. VoxelVerse
26. EngineGrid
27. NodeExplorer
28. BlockEngine
29. VoxelCrafters
30. EngineScapes
31. NodeSaga
32. Blocktopolis
33. VoxelRealm
34. EngineBlaster
35. NodeCraftia
36. BlockVerse
37. VoxelWorld
38. EngineCrafters
39. NodeBlocks
40. BlockEngineer
41. VoxelNode
42. EngineGrid
43. NodeCrafters
44. BlockVortex
45. VoxelVerse
46. EngineRealm
47. NodeBlaster
48. Blocktopia
49. VoxelGrid
50. EngineNode
51. NodeCraftia
52. BlockVerse
53. VoxelWorld
54. EngineCrafters
55. NodeBlocks
56. BlockEngineer
57. VoxelNode
58. EngineGrid
59. NodeCrafters
60. BlockVortex
61. VoxelVerse
62. EngineRealm
63. NodeBlaster
64. Blocktopia
65. VoxelGrid
66. EngineNode
67. NodeCraftia
68. BlockVerse
69. VoxelWorld
70. EngineCrafters
71. NodeBlocks
72. BlockEngineer
73. VoxelNode
74. EngineGrid
75. NodeCrafters
76. BlockVortex
77. VoxelVerse
78. EngineRealm
79. NodeBlaster
80. Blocktopia
81. VoxelGrid
82. EngineNode
83. NodeCraftia
84. BlockVerse
85. VoxelWorld
86. EngineCrafters
87. NodeBlocks
88. BlockEngineer
89. VoxelNode
90. EngineGrid
91. NodeCrafters
92. BlockVortex
93. VoxelVerse
94. EngineRealm
95. NodeBlaster
96. Blocktopia
97. VoxelGrid
98. EngineNode
99. NodeCraftia
100. BlockVerse

**Comment by SwissalpS** [comment]
> ChatGPT names 

please at least trim out the duplicates

**Comment by amreo** [comment]
Bloxelo

**Comment by danmcne** [comment]
CuboLibre

**Comment by danmcne** [comment]
Voxmina

**Comment by dillfrescott** [comment]
OpenCraft

**Comment by dillfrescott** [comment]
My second vote is to leave the name as it is. `Minetest`

**Comment by nininik0** [comment]
What about voxel playground or lua playground??

**Comment by TheShadowOfHassen** [comment]
Brockin

Not a play on block. Seriously, even though it's a block game, I'm trying to find cool different names. This one is inspired by Brock which means badger.

Honestly, having a badger as the mascot for a new minetest would be cool. I have some ideas for a logo...

**Comment by fluxionary** [comment]
i prefer kutiko, but i also like creating names. 

number 1: volexia

**Comment by fluxionary** [comment]
i prefer kutiko, but i also like creating names. 

number 2: rhombix

**Comment by fluxionary** [comment]
i prefer kutiko, but i also like creating names. 

number 3: madjestic

**Comment by nininik0** [comment]
I'm pretty sure mesecore is the best name cuz it implies that it is a core for games and has mese.

**Comment by nininik0** [comment]
Why are my names getting marked off topic? What's wrong with them?

**Comment by TheShadowOfHassen** [comment]
> I'm pretty sure mesecore is the best name cuz it implies that it is a core for games and has mese.

Sounds like musescore

**Comment by Niterux** [comment]
Nodegine
node + engine

**Comment by mckaygerhard** [comment]
Opennode

**Comment by mckaygerhard** [comment]
vertexplay

**Comment by mckaygerhard** [comment]
vectorplay

this based on that minetrol is now an engine, so vectorplay seems fit, but well i guess the name never will change as must be

**Comment by tigercoding56** [comment]
i have a idea   , rename it to testMine , (jk do not rename it at all)

**Comment by BRNSystems** [comment]
Voxelite

**Comment by bitokulo** [comment]
Did you ask the creators if they want to change the name?

**Comment by CandyFiend** [comment]
MultiNode

**Comment by asrelo** [comment]
A memorable unique name instead of an attempt to meld a couple of generic words together (like most of the suggestions) can be good. It also can make the project better stand out from countless "yet another Minecraft-like technical demos".

For suggestions, just a bit of rocks: Malachite, Tourmaline, Kaolin. They all don't make much sense, and that's why I chose.

Also, impossibility to find a name that satisfies all major contributors does not imply that the current name is good enough.

**Comment by bitokulo** [comment]
> A memorable unique name instead of an attempt to meld a couple of generic words together (like most of the suggestions) can be good. It also can make the project better stand out from countless "yet another Minecraft-like technical demos".
> 
> For suggestions, just a bit of rocks: Malachite, Tourmaline, Kaolin. They all don't make much sense, and that's why I chose.
> 
> Also, impossibility to find a name that satisfies all major contributors does not imply that the current name is good enough.

Those aren't memorable. And no, the current name is good enough.

**Comment by bitokulo** [comment]
If however one ought to charge the base game's name, better charge it to best pronounceability between languages. I would recommend a syllabary of CV(n), which mean a Consonant is obligatory, a Vocal is obligatory, and there may be an "n" at the end of the syllable, CH and SH could be treated as a consonant. And, hm, Latin/Japanese vowels sounds.

**Comment by SaiPanneerselvam** [comment]
Don’t waste time like this, MineTest is THE BEST name and option and it has been reigning for 10+ years now. Its perfectly fine as is

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Montandalar** [comment]
"Cubelite". Rhymes with Bakelite. After the lightweight nature of the unmodded C++ game. Probably doesn't hold up as well for modpacks and featureful games like Mineclone2. But I thought I would add it to the list.

Off-topic:
The current name sucks, so often when I introduce Minetest to people IRL I say "Minetest" then soon after say something like "yeah the name doesn't sell it very well". Minetest as an organisation is usually pretty bad at making marketable names. We don't need to wait for the perfect name, but there are plenty that can be weeded out, too.

**Comment by bitokulo** [comment]
It shouldn't be trying to sell anything. Just clarify what it is (an engine), and then tell the name makes sense out of the engine concept. And by the way, if you want to play an specific game like Mesecraft, Mineclone2, Nodecraft or Survivetest, invite to play _those_ games, not Minetest.

**Comment by CallMeDax** [comment]
Voxism

short, has voxel in it because thats what it is

**Comment by CallMeDax** [comment]
Node Box Platform/Engine

Minetest has 'nodeboxes' as a way to display nodes, maybe it can be used to display Minetest too.

**Comment by AvnyrTokirawa** [comment]
Personally, I think the choice of a name is very complicated. First of all, what horizon do we want for Minetest?
If it's to take a free path, far from the vision of another world-famous game.

Let me give you an example,
When Java was in its golden age, ECMAScript was looking to change its name. No need to go into detail... 

 ECMAScript -> JavaScript (These are however, two completely different languages)

Should we take inspiration from the name of another game, or can we go in the opposite direction?

Here are the names I'm proposing:

- OpenCube
- Lapsus `[lapsys]`
- Leaf

Off-topic:

> What I find lacking is a document detailing the project's vision and what the community expects from Minetest.
(If I haven't just missed it).

**Comment by Montandalar** [comment]
I'm going to piggyback one off CallMeDax and suggest instead of just plain NodeBox, which kind of overlaps, something with a "cute" suffix:

NodeBoxen

The inspiration goes back to the entry for [http://www.catb.org/~esr/jargon/html/B/boxen.html](Boxen) from the Jargon File, where it's a fanciful plural of box, similar to the plural ox -> oxen.

**Comment by getoffghub** [comment]
Universe - you can make everything you want out of it, the name hasn't been used for a game/engine and it sounds ambitious/high-quality. The minetest_game should just be renamed to "default_game".

**Comment by cosin15** [comment]
Mycraft

**Comment by Danyy435** [comment]
Final Minetest

**Comment by TheCorruptCat** [comment]
community game

**Comment by mckaygerhard** [comment]
> Final Minetest

@Danyy435  liked this! .. its being so familiar.. XD

**Comment by Poikilos** [comment]
> TerraForge

Consider doing a web search before suggesting a name.

- "TerraForged is a world generation mod for Minecraft"
- "TerraForged on Steam" 'You are a skilled smith who seeks to craft the legendary sword "Excalibur"'
- "Terraforge is a fully managed DevOps platform"
- "TerraForge Communities, Inc., one of Virginia's premier developers"
- "The Terraforge is a special crafting station found only in Ancient Vaults" -starbounder.org
- "Blades of the Terraforge" -Dota 2 wiki

**Comment by mckaygerhard** [comment]
Why this proposal was market as off topic?  seems minetes deserves what multicraft is doing?

MEN, guys.. stop envy.. !  what if a non ramdom person propose it? people and player dont care the issues but minetest started to being a complete mess and a changed name maybe will be the best!

@Danyy435 do you are joking? why you proposed that name?

**for all of you guys of minetest! what if people started to like it? (well minetst per se is not a great name neither final one but men.. seriously.. stop being like mycrosoft or apple!!)**

![image](https://github.com/minetest/minetest/assets/1571724/b11df448-19fd-4b65-a207-52d4a99c781a)

**Comment by rodovia** [comment]
I have an idea: Paichnindie. "paichnindi" in greek means "game" (not exclusively videogames) and a play with "indie".

**Comment by nonfreegithub** [comment]
LibreCraft

**Comment by cosin15** [comment]
(super)tuxcraft

**Comment by ancientmarinerdev** [comment]
ProcrastiNation - 4 months after a decision to rename, and no further decision, or guidance.

**Comment by Zughy** [comment]
Thanks for all your suggestions! It's been a couple weeks since we started an internal discussion about the hypothetical new name (so no, we're not procrastinating). We'll let you know as soon as a decision is taken! Locking

**Comment by Zughy** [comment]
Update: discussion is still going on and it has developed since; we're possibly going somewhere

**Comment by sfan5** [comment]
There will be an announcement on this very soon, closing.
