### ISSUE TITLE
Android: Black screen with post-processing

### ISSUE THREAD

**Issue by Yonle** [minetest/minetest#13519]
##### Minetest version
```
5.7.0
```

##### OS / Hardware
Operating system: ARM64 Android
CPU: Cortex-A53

GPU model: PowerVR GE8320, 650 MHz
OpenGL version: -

##### Summary
First time playing resulting in black screen. No Mods or any plugins installed yet. World created with default configuration.

![Screenshot_20230522_183301](https://github.com/minetest/minetest/assets/63401712/9b4aa8f5-d7c5-49f2-a80c-86edffe144f6)

Changing camera also does not helps.

##### Steps to reproduce
1. Start Minetest for the first time
2. Create world without changing anything
3. Get in

**Comment by Yonle** [comment]
Downgrading to 5.6.1 works.

![Screenshot_20230522_184730](https://github.com/minetest/minetest/assets/63401712/e529eb71-069e-46fe-8cef-fe4b7db942c7)

**Comment by Yonle** [comment]
But upgrading from 5.6.1 to 5.7.0 also leads to black screen.

**Comment by srifqi** [comment]
I can not reproduce it (on Samsung Galaxy A72, GPU: Adreno 618). Both versions mentioned in this thread can run normally.

Have you tried to set the video driver (`video_driver`) to `ogles1` in the 5.7.0 version? It is in the All Settings -> Advanced -> Advanced -> Graphics -> Video driver.

**Comment by Yonle** [comment]
> Have you tried to set the video driver (video_driver) to ogles1 in the 5.7.0 version? It is in the All Settings -> Advanced -> Advanced -> Graphics -> Video driver.

I did not modify anything on the settings yet, So i am doing it now.

It works, But some UI is buggy.

![Screenshot_20230524_190731](https://github.com/minetest/minetest/assets/63401712/35ca9f7b-fb48-457e-85a5-8d3281e3f2b2)

**Comment by sfan5** [comment]
ogles1 will not be supported in the future, so if it doesn't work we have to fix that anyway.
Do you have the debug.txt / log file?

**Comment by Yonle** [comment]
[debug.txt](https://github.com/minetest/minetest/files/11563357/debug.txt)

**Comment by nininik0** [comment]
Maybe you should delete the app and then install it again or switch to OGLES2 #13580

**Comment by joshuaruxpin** [comment]
had same issue trying to run on chromebook

**Comment by nininik0** [comment]
Yes but disabling shader causes stuff to render in fulbright #13511 #13580

**Comment by Yonle** [comment]
> Yes but disabling shader causes stuff to render in fulbright #13511 #13580

Could confirm.

**Comment by Unacceptium** [comment]
i got the same issue on my gigaset, android 9! i changed the video driver and shaders and that solved

**Comment by grorp** [comment]
Unfortunately, I can't reproduce this either, and the log posted by Yonle doesn't seem to contain anything useful...

**Comment by erlehmann** [comment]
Here is a list of mobile devices that have the PowerVR GE8320 GPU (same as the submitter):
https://mobile.phonebunch.com/phone-filter/gpu/powervr-ge8320/page/1/

I also found this PR for GLideN64 that may be related: https://github.com/gonetz/GLideN64/pull/2633

> Newer PowerVR devices need depth to be cleared every frame, otherwise most geometry is rendered behind the background.
> 
> It also needs fragment based depth to be disabled, otherwise geometry has various depth glitches.

**Comment by Unacceptium** [comment]
@erlehmann i'm not a programmer, but i can't logic out how that polygon issue related.

**Comment by erlehmann** [comment]
> @erlehmann i'm not a programmer, but i can't logic out how that polygon issue related.

I am not a graphics programmer either, but in both cases, stuff that should be rendered is not, on exactly the same hardware. So that's why I posted it. Who knows, maybe it is a red herring?

**Comment by erlehmann** [comment]
@Unacceptium can you come to #minetest-dev IRC? This issue is being discussed right now and it seems you can reproduce.

**Comment by Unacceptium** [comment]
i cant on my actual phone it is on my before phone!

**Comment by erlehmann** [comment]
> i cant on my actual phone it is on my before phone!

Do you still have the hardware for testing purposes?

**Comment by Unacceptium** [comment]
umm, i gave that phone to my mum, she is facebooking right now....

**Comment by SmallJoker** [comment]
For those affected by this bug: Please post your GPU model and and the relevant excerpt from debug.txt (and/or logcat) to narrow down whether it's a shader compiling error.

Unfortunately there does not seem to be a Minetest developer who could reproduce this issue to work on a fix, hence community inputs are highly welcomed. Removing from the 5.8.0 milestone to not hold back its release due to a specific hardware problem of certain models.

**Comment by Unacceptium** [comment]
the phone i reproduced the issue is a higaset gs190 wich is
SoC/CPU: MediaTek Helio A22 MT6761
GPU: Mali-G72 MP3
4 core
is this helpful?

**Comment by sfan5** [comment]
the good news: I can reproduce this issue on Linux with a Mali-450 GPU and the Mesa driver (so not some proprietary stuff that's impossible to debug). That also means there's a good chance there's an actual bug.

the bad news: this board is very slow at compiling and I don't have the expertise or time to continue debugging this.

**Comment by sfan5** [comment]
should be re-tested after #14338 and #14405

**Comment by sfan5** [comment]
Good news: time and motivation to re-test this came back.
More good news: disabling post-processing fixes this issue. Since it's disabled by default on Android we don't have to worry about this for now.

**Comment by grorp** [comment]
Looking at this code:

https://github.com/minetest/minetest/blob/60cd1e452957e2e924eedf9de6b46f6eb7833ccc/irr/src/OpenGLES2/Driver.cpp#L99-L105

There can be cases with OpenGL ES 2 where no depth texture format is supported at all. This would obviously result in texture creation failing, the framebuffer would be invalid and we'd have the issue described here.

**Comment by sfan5** [comment]
A second problem is the usage of `GL_BGRA`, which is an unsized format, for creating a render target. This doesn't work and never will.
The required combination for this problem to appear is:
* GLES 2.x
* `EXT_texture_format_BGRA8888` supported
* `OES_texture_half_float` not supported
