### ISSUE TITLE
Objects rendering in fullbright on unified driver without shaders

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [minetest/minetest#13511]
##### Minetest version

```
5.7.0
```

##### OS / Hardware

Operating system: Android 10
CPU: HiSilicon Kirin 710 (4x ARM Cortex-A73; 4x ARM Cortex-A53)

GPU model: Mali-G51
OpenGL version: 3.2

##### Summary

For some reason, all entities (mobs et cetera) across all Minetest-based games are rendered in fullbright, be it player or AI-controlled ones. Lighting for the world, be it static or dynamic is working correctly. For the record, the specifications are supplied by CPU-Z, the device's exact model is Huawei P30 lite, MAR-LX1A.
![Screenshot_20230516_183944_net minetest minetest](https://github.com/minetest/minetest/assets/39307800/f66cb29b-54e9-48f6-ade1-57a137f14099)

##### Steps to reproduce

Simply try to launch any Minetest-based game on this device.

**Comment by Zughy** [comment]
Maybe the same as in #9877 ? Have you changed your `display_gamma` value to increase the brightness? And if yes, how much?

**Comment by TheHopelessThrumbo** [comment]
display_gamma is currently at 1.0, and I don't recall even altering its value.

**Comment by srifqi** [comment]
I can reproduce it (Samsung Galaxy A72) if OpenGL ES 2 is used, but the shaders are disabled.

I can not do `git bisect`, but the problem already exists at c1e430ef68271b8769ae8852b2b4a2fa0fb7ccac (or probably because of a problem in IrrlichtMT, I can not check).

**Comment by nininik0** [comment]
That's what happens to me, also if you enable shaders that glitch is gone but animated sprites don't move. I made another bug #13578 
![Screenshot_20230610-173650_Minetest](https://github.com/minetest/minetest/assets/132112852/a6161980-b8bb-4311-90c1-a41c0b17f5bc)

**Comment by oong819** [comment]
> That's what happens to me, also if you enable shaders that glitch is gone but animated sprites don't move. I made another bug #13578 ![Screenshot_20230610-173650_Minetest](https://user-images.githubusercontent.com/132112852/244906214-a6161980-b8bb-4311-90c1-a41c0b17f5bc.png)

the animated sprite work fine to me even if i enabled shaders and using OpenGL ES 2
![Screenshot_20230611-101059](https://github.com/minetest/minetest/assets/76146430/f9bea9da-5b37-4367-910a-2635755189b3)

**Comment by nininik0** [comment]
Yes, it yaws depending  on how you look at it it changes looks also the hands and legs of the thing Move
