### ISSUE TITLE
Important parts of the community are not heard

### ISSUE THREAD

**Issue by Natureshadow** [minetest/minetest#13517]
In #13510, a new name can be proposed. This is a very good issue to get new contributors into Minetest, and a good starting point for learning that free software is made by the community.

However, parts of the community are not heard. I am representing a group of young Minetest players and free software enthusiasts, organised under the umbrella of [Teckids](https://teckids.org).

Due to the nature of GitHub's terms of use, these community members are currently excluded from contributing. I kindly ask the Minetest maintainers to improve the situation, and treat all community members equally, independent of their age (or origin).

A good starting point would be to migrate the development community to [Codeberg](https://codeberg.org) or another platform with less discriminatory terms of use.

**Comment by kuba-orlik** [comment]
Great idea! Even though I myself am not excluded, the above posts state some of the reasons why I try to steer away from Microsoft Github as much as possible.

**Comment by Zughy** [comment]
I guess we're talking about an age limit? By the way, there already is an issue about a possible migration, with pros and cons: #12324 
I'm closing here, but please do raise your concerns in the other one

**Comment by rubenwardy** [comment]
Should probably also make a forum topic where people can contribute suggestions there too

Related: #7901
