### ISSUE TITLE
Mouse wheel rotation

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest#13516]
## Problem

As mouse wheel rotation is inverted I was terrible when playing the first times on Capture The Flag server and now I'm not much better anyway, I keep on confusing the directions of scrolling my equipped stuff making my performance scary.

## Solutions

Add mouse wheel inversion option.

## Alternatives

Add another mouse wheel inversion option.

**Comment by Desour** [comment]
There's already `keymap_hotbar_previous`/next, but one can't bind it to mouse wheel up/down.
I therefore consider this a duplicate of #10927.

**Comment by rubenwardy** [comment]
#10927 is purely a GUI task, the settings to allow rebinding mouse keys already exist in minetest.conf

**Comment by PavanLuca** [comment]
You mean that can be edited only on minetest.conf while it's not possible directly from settings?

**Comment by srifqi** [comment]
The feature has been added to the `master` branch. You can compile it yourself or use the daily build to use it (or wait for the next release). The settings are in Controls -> Keyboard and Mouse.

**Comment by PavanLuca** [comment]
Yeah, I checked settings again and I see that for now I can only invert vertical visual movement and mouse sensitivity. I prefer to invert mouse wheel from a setting rather than editing files, I don't want to get problems even there. So I'll wait for the new release.
