### ISSUE TITLE
sneak allows walking through very thin nodebox walls

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#13527]
##### Minetest version
```
5.6.1, 5.7.0
```

##### OS / Hardware
Operating system: linux

##### Summary
apologies if this is a dupe of one of the other sneak-related issues, though none of the reports i read through seemed the same to me. 

sneak permits a player to walk through walls which are 1/16th the thickness of a regular node.

##### Steps to reproduce
1. MTG + [moreblocks](https://content.minetest.net/packages/Calinou/moreblocks/). 
2. create a wall of 1/16th slabs, e.g.
   ![image](https://github.com/minetest/minetest/assets/25628292/3008f6bd-405d-4484-8b0a-742ee85fd682)
3. walk up to the wall so that you are touching it from the side where you are "inside" the node.
4. press sneak. you will be "sucked" into the wall slightly, allowing you to walk through the wall.

**Comment by Zughy** [comment]
I confirm. Video to better understand the "inside" of the node aspect:

https://github.com/minetest/minetest/assets/63455151/5266802c-67f6-4c08-af5d-b926a8c0c2da
