### ISSUE TITLE
Make a video explaining how Minetest Engine work

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13529]
currently its not easy to understand how the Minetest Engine work in detail

so can the core devs make a video explaining how Minetest Engine work (like how item mesh are generated, how entity collision work, how mapgens work, etc.) and upload it on the minetest.net (also YouTube too if the devs want)

**Comment by rubenwardy** [comment]
It would be better and much easier to write documentation for the engine. Video making takes a lot of time and if done poorly is a lot worse than just text

**Comment by oong819** [comment]
oooh the wiki are more detailed and easy to understand than i think, closing

**Comment by Bituvo** [comment]
I'll keep this in the back of my `noggin`
