### ISSUE TITLE
Toki Pona as official language

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#13520]
Minetest should have a universal and opensource language.

Why?

English:
- It is not universal. It is not timeless.
- English speaking countries (USA) are hostile towards others: Iran, Russia, China...

So I use the Toki pona language for prestige things, like slogans, posters, and so on. For small things but with a distinguished touch.

Obviously English would be the language of communication, otherwise nobody would understand each other, but for the rest Toki Pona.

https://en.wikipedia.org/wiki/Toki_Pona

**Comment by rubenwardy** [comment]
I think it's fairly obvious why we won't be doing this

Do you even speak Toki Pona?

**Comment by runsy** [comment]
> I think it's fairly obvious why we won't be doing this
> 
> Do you even speak Toki Pona?

No, I just discovered it today, but I find it interesting. I will of course use it for Minetest stuff.
