### ISSUE TITLE
Documentation: meta:set_int() does not specify range.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#13531]
## Problem

So I was coding, and typed out `meta:set_int("time", os.time())`. And suddenly I realized that A) `os.time()` is a huge number, and B) `meta:set_int()` doesn't document its min/max contiguous integer range.

## Solutions

Need documentation, please. Mainly so that there's a promise that the range won't be smallered at some future date.

## Alternatives

Could store `os.time()` in a string. I've done that, too.

## Additional context

Bleh, leaving this empty.

**Comment by sfan5** [comment]
> And suddenly I realized that A) `os.time()` is a huge number

I don't think 32-bit numbers pass as huge in the computing world. Either way, this should be documented.

**Comment by rvenson** [comment]
According to the [code](https://github.com/minetest/minetest/blob/8fa2ea71ef1191d8eda2412f733051646c8d3800/src/script/lua_api/l_metadata.cpp), the `set_int` function already converts the integer to a string (and the string to an integer in the `get_int` equivalent). So we can assume that the range is system-dependent (usually 32 bits).

The same for the `set_float` function.
