### ISSUE TITLE
5.7.0 is sometimes extremely slow on Windows (11) and crashes

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13545]
##### Minetest version
5.7.0 official version

##### OS / Hardware
Operating system: Windows 11
CPU: Intel

GPU model: NVidia
OpenGL version:

##### Summary
At large viewing_range (800+) the game (just minetest_game, no mods) runs well initially (100+ FPS).
When panning and flying around some the game will eventually crawl to halt (1 FPS, and even 0 FPS).
Sometime this recovers. Sometime the games crashes.

Together with #13518 I have start assuming that Minetest does not work and is not supported on Windows. (at least not in highend settings)

Sorry for the unspecific nature. I have no profiler or debugger on Windows.

##### Steps to reproduce
Plain 5.7.0 with minetest_game. Set viewing_range = 1000, client_mapblock_limit = 100000, max_block_send_distance = 64
max_block_generate_distance = 63, max_simultaneous_block_sends_per_client = 160
Start a singleplayer world, fly around, close to the ground, fly up, look around.

**Comment by sfan5** [comment]
> I have start assuming that Minetest does not work and is not supported on Windows. (at least not in highend settings)

No need to be so dramatic :) These high-end settings have never before been possible in MT and we shipped a fairly new culler in 5.7.0 so that's bound to surface new issues.

FWIW I can't reproduce the "zero fps or crashes" situation on Linux with your settings (how long am I supposed to fly around?) though I do get the FPS down to about 15.

> Sorry for the unspecific nature. I have no profiler or debugger on Windows.

At least for the crash it would be easy with a debug build to use the new `--debugger` and receive a backtrace.

**Comment by wsor4035** [comment]
> Together with https://github.com/minetest/minetest/issues/13518 I have start assuming that Minetest does not work and is not supported on Windows.

been the case for a while. see https://github.com/minetest/minetest/issues/11832 and https://github.com/minetest/minetest/issues/11544 for the case

**Comment by lhofhansl** [comment]
> FWIW I can't reproduce the "zero fps or crashes" situation on Linux with your settings (how long am I supposed to fly around?) though I do get the FPS down to about 15.

Did you mean to say Linux or Windows? On Linux I do not see this problem, only on Windows.

**Comment by Zughy** [comment]
Without a profiler this report is basically useless. I'm not saying the problem it doesn't exist, just that it's impossible to fix without any further info

**Comment by ExeVirus** [comment]
Hey @lhofhansl, try recompiling on windows yourself, using a debug version of the executable - that will let you profile. Also my build instructions will build with Mingw, which might be different than the possibly MSVC version we might distribute (unsure).

Anyways, instructions for getting that set up (Windows, Mingw, debugging) are 10 minutes long: 
https://www.youtube.com/watch?v=y8eWDzLNa3E
You can just read the notes for how to get setup below (esp. for links)

Should take you less than an hour (depending on internet speed), and at the end you can just ask here for how to give the profiling command-line argument (unsure if it's on by default, but there's a ton of profiling code in there)

**Comment by srifqi** [comment]
Here are my profiling results.

-------

## Conditions

- The profiling used **Visual Studio 2022** (17.7.4) on **Windows 10** (10.0.19045) with 8 GB RAM and SSD (ASUS VivoBook 14, M413IA). The profiler looked for **CPU usage**.
- The test used recent `master` branch and it was compiled in Release mode.
- The contents of `minetest.conf` were only those settings described in the first post (other settings are default).
- The test was run by creating a new Minetest Game (`minetest_game`) world, hence there would be a big chunk of map generation's time in the first run.
- The first run was done by flying in fast mode to explore nearby areas from spawn point.
- The second run was done by rotating view one full rotation slowly until no more mapchunks are loaded.

## Result of the first run

- Minetest run as usual, except with low FPS (5–15 FPS) inside the world after some time (when more chunks are loaded).
- When the loaded world was already large, there were stutters when a mapchunk was being loaded.
- The shutdown was quick. I can not reproduce #13518.

**Flame graph**
![flame graph of first run](https://github.com/minetest/minetest/assets/4017302/b4501aad-de19-4de4-9d7a-f1d94d17bfb5)

**Main functions**

| Function Name | Total CPU [unit, %] | Self CPU [unit, %] |
|:------------- | -------------------:| ------------------:|
| `minetest` | 343117 (100,00%) | 0 (0,00%) |
| + `main` | 133060 (38,78%) | 0 (0,00%) |
| + `Thread::threadProc` | 209647 (61,10%) | 0 (0,00%) |

<details>
<summary>The main thread</summary>

| Function Name | Total CPU [unit, %] | Self CPU [unit, %] |
|:------------- | -------------------:| ------------------:|
| `minetest` | 343117 (100,00%) | 0 (0,00%) |
| + `main` | 133060 (38,78%) | 0 (0,00%) |
| ++ `ClientLauncher::run` | 133046 (38,78%) | 0 (0,00%) |
| ++ `the_game` | 126299 (36,81%) | 0 (0,00%) |
| +++ `Game::run` | 121850 (35,51%) | 1 (0,00%) |
| +++ `Game::~Game` | 3688 (1,07%) | 0 (0,00%) |
| +++ `Game::startup` | 756 (0,22%) | 0 (0,00%) |
| +++ `Game::shutdown` | 5 (0,00%) | 0 (0,00%) |
| ++ `?removeAll@CSceneManager@scene@irr@@UEAAXXZ` | 5481 (1,60%) | 0 (0,00%) |
| ++ `ClientLauncher::launch_game` | 1030 (0,30%) | 0 (0,00%) |
| ++ `ClientLauncher::init_engine` | 225 (0,07%) | 0 (0,00%) |
| ++ `FontEngine::FontEngine` | 6 (0,00%) | 0 (0,00%) |
| ++ `sound::SoundManagerSingleton::init` | 3 (0,00%) |
| ++ `?setResizable@CIrrDeviceWin32@irr@@UEAAX_N@Z` | 1 (0,00%) | 0 (0,00%) |
| ++ `RenderingEngine::setWindowIcon` | 1 (0,00%) | 0 (0,00%) |

</details>

<details>
<summary>Other threads</summary>

| Function Name | Total CPU [unit, %] | Self CPU [unit, %] |
|:------------- | -------------------:| ------------------:|
| `minetest` | 343117 (100,00%) | 0 (0,00%) |
| + `Thread::threadProc` | 209647 (61,10%) | 0 (0,00%) |
| ++ `UpdateThread::run` | 118879 (34,65%) | 2 (0,00%) |
| +++ `MeshUpdateWorkerThread::doUpdate` | 118646 (34,58%) | 23 (0,01%) |
| +++ `MinimapUpdateThread::doUpdate` | 131 (0,04%) | 11 (0,00%) |
| ++ `EmergeThread::run` | 68988 (20,11%) | 4 (0,00%) |
| +++ `MapgenV7::makeChunk` | 51872 (15,12%) | 3 (0,00%) |
| +++ `EmergeThread::getBlockOrStartGen` | 15034 (4,38%) | 6 (0,00%) |
| +++ `EmergeThread::finishGen` | 1586 (0,46%) | 0 (0,00%) |
| +++ `MMVManip::'scalar deleting destructor'` | 370 (0,11%) | 0 (0,00%) |
| +++ `EmergeThread::popBlockEmerge` | 24 (0,01%) | 2 (0,00%) |
| +++ `Map::dispatchEvent` | 18 (0,01%) | 3 (0,00%) |
| +++ `MapEditEvent::setModifiedBlocks` | 17 (0,00%) | 2 (0,00%) |
| +++ `EmergeThread::runCompletionCallbacks` | 8 (0,00%) | 6 (0,00%) |
| +++ (others) | |
| ++ `ServerThread::run` | 18956 (5,52%) | 2 (0,00%) |
| ++ `con::ConnectionSendThread::run` | 1425 (0,42%) | 20 (0,01%) |
| ++ `con::ConnectionReceiveThread::run` | 1307 (0,38%) | 1 (0,00%) |
| ++ `sound::OpenALSoundManager::run` | 92 (0,03%) | 4 (0,00%) |

</details>

## Result of the second run

- Minetest run as usual, except with low FPS (9 FPS) inside the world after some time (when more chunks are loaded).
- The shutdown was quick.

**Flame graph**
![flame graph of second run](https://github.com/minetest/minetest/assets/4017302/6ada27cc-029d-4904-9842-2d847dbf78b1)

-------

PS The Debug mode is much, much slower than the Release mode in this case.

**Comment by Desour** [comment]
A flame graph over the whole session isn't very useful if you want to know why some frames are slow.

You could try using a tracing profiler.

For example, here's a branch for using [tracy](https://github.com/wolfpld/tracy): https://github.com/Desour/minetest/tree/tracy_profiling
Build with `-DTRACY_ENABLE=1 -DTRACY_ONLY_LOCALHOST=1` (and optionally for better sampling results also with `-DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="$CXXFLAGS -fno-omit-frame-pointer" -DCMAKE_C_FLAGS="$CFLAGS -fno-omit-frame-pointer"`). You'll also need to install and launch the tracy app, and you have to annotate code to see more details.

**Comment by lhofhansl** [comment]
Fixed by https://github.com/minetest/minetest/commit/47e557b96ad4b9f053cf35150b2f46fe623b4dc7
