### ISSUE TITLE
Building Minetest 5.7.0 on MacOS: error: use of undeclared identifier 'luaopen_bit'

### ISSUE THREAD

**Issue by giangduong** [minetest/minetest#13548]
##### Minetest version

```
5.7.0
```

##### OS / Hardware

Operating system: MacOS
CPU: Intel

GPU model:
OpenGL version: 2.1

##### Summary

I used to build this version successfully in my MacBook. But today, i got a strange error.

<img width="1134" alt="image" src="https://github.com/minetest/minetest/assets/8393739/568afc3d-1544-4a81-be4d-ffeaedc45c52">

I also take a look at minetest/lib/lua/src/lualib.h. There is no definition of luaopen_bit or LUA_BITLIBNAME and LUA_JITLIBNAME

##### Steps to reproduce

git clone --depth 1 https://github.com/minetest/minetest.git
cd minetest

git clone --depth 1 https://github.com/minetest/irrlicht.git lib/irrlichtmt

mkdir build
cd build

cmake .. \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=11.7 \
    -DBUILD_SERVER=FALSE \
    -DBUILD_CLIENT=TRUE \
    -DENABLE_GETTEXT=TRUE \
    -DENABLE_FREETYPE=FALSE \
    -DENABLE_GETTEXT=TRUE \
    -DCMAKE_FIND_FRAMEWORK=LAST \
    -DCMAKE_INSTALL_PREFIX=../build/macos/ \
    -DRUN_IN_PLACE=FALSE

make package -j$(sysctl -n hw.logicalcpu)

**Comment by sfan5** [comment]
It's also failing to find `luaopen_jit` so it's not actually LuaJIT. The extra `LUA_INCLUDE_DIR` probably confuses our build script.

As an aside if you are building 5.7.0 then IrrlichtMt 1.9.0.10 should be required, yet your output shows 1.9.0.8. Weird.

**Comment by giangduong** [comment]
> It's also failing to find `luaopen_jit` so it's not actually LuaJIT. The extra `LUA_INCLUDE_DIR` probably confuses our build script (try removing that).
> 
> As an aside sibce you are building 5.7.0 then IrrlichtMt 1.9.0.10 should be required, yet your output shows 1.9.0.8. Weird.

I did try a few different ways. 

I tried to install the latest luajit 2.1. I can see that the lualib.h has definitions of luaopen_jit, LUA_JITLIBNAME, and LUA_BITLIBNAME. In order to use luajit 2.1, i'll need to add extra 'LUA_INCLUDE_DIR'.

$ cmake .. \
>     -DCMAKE_OSX_DEPLOYMENT_TARGET=11.7 \
>     -DBUILD_SERVER=FALSE \
>     -DBUILD_CLIENT=TRUE \
>     -DENABLE_GETTEXT=TRUE \
>     -DENABLE_FREETYPE=FALSE \
>     -DENABLE_GETTEXT=TRUE \
>     -DENABLE_LUAJIT=TRUE \
>    -DLUA_INCLUDE_DIR=/usr/local/include/luajit-2.1 \
>     -DCMAKE_FIND_FRAMEWORK=LAST \
>     -DCMAKE_INSTALL_PREFIX=../build/macos/ \
>     -DRUN_IN_PLACE=FALSE

I think the issue is fixed. But i got another issue.

<img width="1263" alt="image" src="https://github.com/minetest/minetest/assets/8393739/eaae0bdf-5dd3-4fc7-94b6-c00a4b2d5834">

**Comment by giangduong** [comment]
> Your Minetest build uses LuaJIT 5.1 (any version from 2017-now), however it seems to be new enough to have `luaopen_string_buffer`:
> 
> https://github.com/minetest/minetest/blob/7221de6edeb80b0512934118bb972288b6825e91/src/CMakeLists.txt#L701-L716
> 
> But it appears that your LuaJIT installation was not compiled with the BitOp library (expected to be included with `luajit.h`:
> 
> https://github.com/minetest/minetest/blob/7221de6edeb80b0512934118bb972288b6825e91/src/script/cpp_api/s_base.cpp#L37-L42
> 
> As a workaround you could either (recommended) try to figure out which LuaJIT build comes with BitOp or (less recommended) try to make use of the bundled library: (also requires you to include the file like the part shown in the code above)
> 
> https://github.com/minetest/minetest/blob/8cd129604934077f900ec587d8230fd640822934/CMakeLists.txt#L306-L308

I replaced the minetest/src/CMakeLists.txt with the one you mentioned above.

When running cmake, i got this error.

<img width="649" alt="image" src="https://github.com/minetest/minetest/assets/8393739/51cf27bd-341a-400c-98d1-9cd7ac7c6deb">

**Comment by sfan5** [comment]
It looks like your source code checkout is just broken/corrupted. Try deleting it and start over.
Note that you can check out the stable version using `-b stable-0.5`
