### ISSUE TITLE
Voxel Manipulator conflict in mapgen.

### ISSUE THREAD

**Issue by Splizard** [minetest/minetest#1354]
When using a voxel manipulator object in register_on_generated, other conventional ways of mapgen have no effect, eg. add_node functions.
This breaks compatibility between mods using different mapgeneration techniques.
Snow Mod uses voxelmanip and as soon as it calls the vm:write_to_map function other mods cannot add_node to the chunk.

**Comment by paramat** [comment]
Now fixed, closing.
