### ISSUE TITLE
Android: Remove migration code and external storage permission

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13540]
##### Minetest version

```
since 5.5.0 to latest workflow build (master)
```

##### OS / Hardware

Operating system: Android 6.0.1 (API lv 23)
CPU: MediaTek

GPU model: Mali
OpenGL ES version: 3.1

##### Summary

since 5.5.0 Minetest Android use data folder for files instead of Minetest directory but Minetest still request storage permission
##### Steps to reproduce

simply run Minetest Android

**Comment by Emojigit** [comment]
It should be super easy to fix by just removing this line from `AndroidManifest.xml`:

https://github.com/minetest/minetest/blob/fc3d6c1dd9ae754e863e1d9386984a314acf1386/android/app/src/main/AndroidManifest.xml#L8

**Comment by rubenwardy** [comment]
The permission remains to allow android versions below a certain point continue to migrate saved data to the new location. This migration code can be removed now

**Comment by oong819** [comment]
> It should be super easy to fix by just removing this line from `AndroidManifest.xml`:
> 
> https://github.com/minetest/minetest/blob/fc3d6c1dd9ae754e863e1d9386984a314acf1386/android/app/src/main/AndroidManifest.xml#L8

if i refuse to give Minetest storage permisson its will toast me that Minetest "can't" run without it and close app

**Comment by Emojigit** [comment]
> if i refuse to give Minetest storage permisson its will toast me that Minetest "can't" run without it and close app

The reason is, the app quits itself if any of the permissions are not granted:

https://github.com/minetest/minetest/blob/fc3d6c1dd9ae754e863e1d9386984a314acf1386/android/app/src/main/java/net/minetest/minetest/MainActivity.java#L136-L145
