### ISSUE TITLE
Add utility script to generate/update *.tr files

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#13546]
## Problem

Minetest lacks a tool to update and generate the `*.tr` files for mods and games. Modders are forced to rely on external software, which isn't great.

Updating the `*.tr` files by hand is not an option, this is extremely inefficient and error-prone and I strongly advice every modder to not do this.

## Suggestion

I therefore request to add an utility script into the `util/` directory of the Minetest repository to update these files automatically.

## Rationale

The reason why I want to add this into the repo is so we finally have an *official* solution. It just seems extremely wrong that external tools are required to do something with a data format that is *only* relevant for Minetest. Another benefit of this script being official is that it will be easier to react to changes to the `*.tr` file format.

## PR

This feature request is being implemented in #13464. I have postes this issue and hope to get concept approval.

**Comment by grorp** [comment]
#13739 merged.
