### ISSUE TITLE
std::istringstream always makes a copy of the passed std::string

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#13559]
##### Minetest version
N/A

##### OS / Hardware
N/A

##### Summary
We are using std::istringstream all over the place. From reading from the network, to deserializing blocks, decompression, etc.

It turns out that istringstream always makes a copy of the passed string. In most (all?) cases this is not necessary for our usage.

We can work around this as follows:
```
std::string s ...;
std::istringstream is(s, std::ios::binary);
```

can be replaced with:
```
struct ZeroCopytBuf : public std::streambuf
{
 	ZeroCopyBuf(const std::string &s) : ZeroCopyBuf(const_cast<char*>(s.c_str()), s.length()) {}
	ZeroCopyBuf(char *c, std::size_t l) { setg(c, c, c + l); }
};

std::string s ...;
ZeroCopyBuf buf(s);
std::istream is(&buf);
```

Avoiding that extra copy. 

Is it worth it?
In a microbenchmark I can confirm that no copy is made and it speeds up the creation of the stream proportionally to the length of the passed string.

End-to-end in MT, I cannot measure the difference in performance when I replace some key istringstreams this way.
Avoiding string copies (especially from pkt->readLongString()) has to be better, though.

Edit: Maybe I should make a PR to people can try...?

**Comment by Desour** [comment]
In C++20 stringstreams support easily moving from and to strings.

-----

Idk if doing this is worth it. You're certainly not the first one who wants to do this, so it might be good to look up some blog posts, stackoverflow answers, or whatever of other people.

**Comment by lhofhansl** [comment]
Are you referring to the move constructor of istringstream in c++20? (https://en.cppreference.com/w/cpp/io/basic_istringstream/basic_istringstream)?

Yeah that would be best, but...  at least in gcc 13 c++20 support is still experimental.

**Comment by lhofhansl** [comment]
Looking at `Client::handleCommand_BlockData` we actually make two copies of each block's (compressed) data: First we create a std::string from the char* in the packet (one copy), then we feed that std::string to the istringstream, which makes another copy.

Looks like this is all drowned by all the other work we're doing when receiving a block. It does seem pretty wasteful.

**Comment by lhofhansl** [comment]
I did search around a bit. In lieu of C++20 folks either gave up :) or did something close to what I suggest above.

**Comment by lhofhansl** [comment]
Just this if you wanted to try... I'll stop now.

```
diff --git a/src/map.cpp b/src/map.cpp
index 1ecd2c126..cfb1774f2 100644
--- a/src/map.cpp
+++ b/src/map.cpp
@@ -1786,7 +1786,8 @@ bool ServerMap::saveBlock(MapBlock *block, MapDatabase *db, int compression_leve
 void ServerMap::loadBlock(std::string *blob, v3s16 p3d, MapSector *sector, bool save_after_load)
 {
 	try {
-		std::istringstream is(*blob, std::ios_base::binary);
+		ZeroCopyBuf buf(*blob);
+		std::istream is(&buf);
 
 		u8 version = SER_FMT_VER_INVALID;
 		is.read((char*)&version, 1);
diff --git a/src/network/clientpackethandler.cpp b/src/network/clientpackethandler.cpp
index 48524553e..9421d3e65 100644
--- a/src/network/clientpackethandler.cpp
+++ b/src/network/clientpackethandler.cpp
@@ -301,8 +301,8 @@ void Client::handleCommand_BlockData(NetworkPacket* pkt)
 	v3s16 p;
 	*pkt >> p;
 
-	std::string datastring(pkt->getString(6), pkt->getSize() - 6);
-	std::istringstream istr(datastring, std::ios_base::binary);
+	ZeroCopyBuf buf(pkt->getString(6), pkt->getSize() - 6);
+	std::istream istr(&buf);
 
 	MapSector *sector;
 	MapBlock *block;
diff --git a/src/util/serialize.h b/src/util/serialize.h
index 4dc1a54c6..c7500667d 100644
--- a/src/util/serialize.h
+++ b/src/util/serialize.h
@@ -473,3 +473,10 @@ std::string serializeJsonStringIfNeeded(const std::string &s);
 
 // Parses a string serialized by serializeJsonStringIfNeeded.
 std::string deSerializeJsonStringIfNeeded(std::istream &is);
+
+struct ZeroCopyBuf : public std::streambuf
+{
+	ZeroCopyBuf(const std::string &s) : ZeroCopyBuf(s.c_str(), s.length()) {}
+	ZeroCopyBuf(const char *c, std::size_t l) : ZeroCopyBuf(const_cast<char*>(c), l) {}
+	ZeroCopyBuf(char *c, std::size_t l) { setg(c, c, c + l); }
+};
```

**Comment by Desour** [comment]
> Are you referring to the move constructor of istringstream in c++20? (https://en.cppreference.com/w/cpp/io/basic_istringstream/basic_istringstream)?

Yes. (And the moving version for `.str()` for the other direction.)

**Comment by sfan5** [comment]
Probably. But do we actually want to **move** strings into stringstreams (which resets the original variable) and not just have the streams operate read-only on them?
The `ZeroCopyBuf` approach doesn't seem so bad.

**Comment by lhofhansl** [comment]
@sfan5 True. In the ClientPacketHandler case it actually saves two copies: (1) make the string object, (2) copy it into the istringstream.
The nice thing about move is that it is safe. With the ZeroCopyBuf you have to make sure the istream does not outlive the buffer or the behavior is "undefined".
We could definitely use move to move the string out from the ostream part.

**Comment by Desour** [comment]
>But do we actually want to move strings into stringstreams

C++23 has spanstreams, FYI: <https://en.cppreference.com/w/cpp/header/spanstream>

----

It looks like the std lib makes adding our own streambuf not too hard, so we can do that, instead of waiting for our C++ std upgrade.

But to keep the code simple, it would be nice to also have a corresponding stream class, which holds the streambuf. This is also what the stdlib streams seem to do. E.g. look into the sstream header (`/usr/include/c++/13.1.1/sstream` for me), `basic_istringstream` is just a child of `basic_istream` with a stringbuf member.

I.e.:
```diff
-		std::istringstream is(*blob, std::ios_base::binary);
+		OurStream is(*blob);
```


-----



> Ok... So broader question: Can we change building of MT to use c++20? (-std=c++20 on G++, and /std:c++20 in MSVSC++)

Or even broader question: Based on what do we decide to raise our minimum version requirements (for compilers and also libraries) on build?

**Comment by lhofhansl** [comment]
Just this it seems:
```
class zcistream : public std::istream
{
public:
	zcistream(const std::string &s) : buf(s) { this->init(&buf); }
	zcistream(const char *c, std::size_t l) : buf(c, l) { this->init(&buf); }
	zcistream(char *c, std::size_t l) : buf(c, l) { this->init(&buf); }

private:
	ZeroCopyBuf buf;
};
```

**Comment by lhofhansl** [comment]
I'll make a PR so folks can try. Perf gain might just be in the noise, maybe not worse it.
I do wonder if it improves on Windows as it would lead to less heap pressure/fragmentation.

**Comment by lhofhansl** [comment]
Meh. Probably not worth it.

**Comment by sfan5** [comment]
I think we should do this but it's not particularly high priority.

**Comment by nerzhul** [comment]
it's a memory performance gain, which is cool for low profile devices, but not prior. I think i'tll optimize a bit the memory allocations yes

**Comment by lhofhansl** [comment]
I tried it again and looked at the block load rate/time, this reduces block load time by 5-8% on my machine.
At large viewing_ranges the block load time is the bottleneck and I find that the map load time is in indeed 5% faster. Not an earth-shattering change, but at least it's measurable. :)
