### ISSUE TITLE
Minetest Force System Reboot When Opened Through Application Menu

### ISSUE THREAD

**Issue by Moonspire** [minetest/minetest#13554]
##### Minetest version

```
5.7.0
```

##### OS / Hardware

Operating system: Linux Mint 20.3 Cinnamon
CPU: Intel© Core™ i7-8550U CPU

GPU model:
OpenGL version:

##### Summary

I'm attempting to create my own game using Minetest and have discovered a rather interesting issue present of both the flatpak and Ubuntu release versions of the game.

I've made a copy of the base Minetest game just for playing around to get my bearings on the file structure and play around a bit. Since making the copy when launched from the main applications menu or shortcuts the game force reboots my computer instantly. When launched through the terminal though the game launches fine.

##### Steps to reproduce

1: Copy a Minetest game into the [User Data]/games
2: Start game through shortcut or system main applications menu
3: Observe computer rebirth

**Comment by NathanSalapat** [comment]
Any errors thrown in debug? Or printed out when launching via the terminal.
I have the same CPU and OS so I can try to replicate this.

**Comment by Moonspire** [comment]
None that I've seen either in debug or terminal but I could be missing something.

**Comment by rubenwardy** [comment]
This will be an OS/driver/hardware issue and not Minetest. Programs shouldn't be able to crash the system

**Comment by fluxionary** [comment]
i don't have the exact same setup, but i tried and can't replicate this.

using 
* "system" minetest 5.6.1 from arch
* linux 5.15.108-1-MANJARO
* nvidia drivers 530.41.03.
* cinnamon

i created a clone of MTG using `cp ~/.minetest/games/minetest_game ~/.minetest/games/minetest_game.2`, launched minetest through the system shortcut, created a new world using the copied game, and launched it. it worked fine.

**Comment by NathanSalapat** [comment]
I am also unable to replicate this issue. Copied a game, had no issues running latest stable, or dev. Saw nothing in the terminal when I launched minetest that way either.

**Comment by savilli** [comment]
It's possible that only the window manager is crashing, rather than the entire system, as this would make more sense. You can check its logs. I don't think that minetest does something wrong here.

**Comment by Moonspire** [comment]
I think Savilli is correct

**Comment by numberZero** [comment]
Sounds like a Flatpak bug I ran into recently. Under some circumstances (don’t remember exactly), it was issuing `kill(0, 9)`. (I assume Ubuntu version is Snap which is a flavor of Flatpak essentially AFAIK)
