### ISSUE TITLE
Health bar not shown up - HUD texts turn black

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1355]
There's not much to say. Once when I lost all hearths in free fall, the health bar simply disappeared (normal when dead) but the server did not notice my death.

Result: No health bar and still alive. After a while, the white HUD text from the landrush mod turned black. 
Only closing client helped to fix this "bug".

Some players in-game noticed this bug too and needed to restart the client too.

EDIT: Still happens in some cases in the newest minetest git.

**Comment by nerzhul** [comment]
@SmallJoker can you confirm or close this issue ? We have fixed some problems with health recently
