### ISSUE TITLE
items are lost when dragging over-sized stacks onto full stacks

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#13552]
##### Minetest version
```
5.7.0
```

##### OS / Hardware
Operating system: linux

##### Summary
within any same inventory list that's displayed via a formspec, if you drag an over-sized (stack size greater than stack_max) stack A onto another stack B, of the same item which size is >= stack_max, but which is smaller than the size of A, the size of A will shrink to the size of B, and items will be lost.

##### Steps to reproduce
using devtest,

* `/giveme basenodes:cobble 200`
* `/giveme basenodes:cobble 100`

  ![image](https://github.com/minetest/minetest/assets/25628292/c3713082-0de4-46f2-ad3e-c3c28e019cc9)

* drag the stack of 200 onto the stack of 100
* the first stack's size will now also be 100, and 100 nodes will have been lost. 

  ![image](https://github.com/minetest/minetest/assets/25628292/152eaf0b-e0fb-4b2f-9af8-685f90208d99)

**Comment by fluxionary** [comment]
note that no problem occurs if the 2nd stack is dragged onto the first, if a stack is dragged onto another in a different inventory list, or if the size of the 2nd stack is less than its stack_max.

**Comment by Zughy** [comment]
I think the problem here is that `/giveme` is not splitting the stack in two

**Comment by fluxionary** [comment]
> I think the problem here is that `/giveme` is not splitting the stack in two

`/giveme` isn't the only possible source of such over-sized stacks. e.g. w/ the mesecons mod, you can smelt 1 mese block into 162 mesecons. items are lost when dragging one oversized stack onto another oversized stack. i suppose one solution would be to remove the ability to set the size of a stack to a value greater than stack_max, but i'm certain people would complain about that. there's other use cases, e.g. giving a non-creative player a large quantity of nodes for some building project.

**Comment by SmallJoker** [comment]
![ah shit here we go again](https://i.kym-cdn.com/entries/icons/original/000/029/223/cover2.jpg)

We already had this issue in 2017, reported in #6038 and fixed in #6039. It looks like the bug was unfixed again in the meantime.

**Comment by rubenwardy** [comment]
The inventory code (storage, gui, and input) needs to be completely unit tested with all of these different bugs covered
