### ISSUE TITLE
Hypertext font size doesn't scale with window size

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13568]
##### Minetest version
```
5.7.0, 5.6.0 and so on
```

##### OS / Hardware
Happens on different hardware and different OS

##### Summary
Title. Every text in the following screens is a hypertext

about 1920x1080
![image](https://github.com/minetest/minetest/assets/63455151/61a6a03d-f8e4-48e3-a59a-516ee4f0de18)

about 1280
![image](https://github.com/minetest/minetest/assets/63455151/dd68452c-880c-4b1c-9dca-8227416a9616)

about 1000
![image](https://github.com/minetest/minetest/assets/63455151/06012936-f91c-4f48-aea7-af8c48ca55b8)

about 600
![image](https://github.com/minetest/minetest/assets/63455151/70344be3-2ae8-4b95-9c22-83f1fd04c72f)

##### Steps to reproduce
Join A.E.S. server and open your Block League profile (the one in the screen) by doing `/bleague profile`

**Comment by vintprox** [comment]
Remotely related: if you use a wider text font, like [OpenDyslexic](https://gist.github.com/vintprox/553981e6b7233b8bd0d222ce8993bb1a), it's going to eventually push some boundaries in this pixel-fixed layout.

**Comment by sfan5** [comment]
How does this relate to #13858?

**Comment by Zughy** [comment]
@sfan5 tested on latest dev, bot with and without fixed size in size[] fs element. Still the same

**Comment by grorp** [comment]
- Scaling font size with window size wouldn't make sense. This isn't done anywhere else in Minetest and I haven't seen any standard GUI frameworks doing this either.
    
    Why would the user want a smaller, less readable font size just because they're using a smaller window? How would you determine the "standard window size" that corresponds to the "standard font size" for scaling?

- The real problem in your example is that formspec coordinates scale with window size. This doesn't make much sense, no standard GUI frameworks scale their coordinates with window size. This is something the formspec replacement will hopefully do better.
    
    This behavior can be disabled via fixed-size formspecs, i.e. `size[x,y,true]`. This should fix the problem in your example. I just joined A.E.S. and did `/bleague profile`. The problem is actually already fixed there, the formspec has already been changed to be fixed-size.

- #14840 would have fixed your example too, without needing to make the formspec fixed-size. It basically stops formspecs from scaling down with window size too far until it's actually necessary.

**Comment by Zughy** [comment]
Thank you @grorp for looking into this, closing then :)
