### ISSUE TITLE
Add a new type of game-mode, (singleplayer world to server/downloadable games)

### ISSUE THREAD

**Issue by FatalError42O** [minetest/minetest#13565]
## Problem

As modders, we have a lack of control over nearly every aspect of the client. This stems from the issue of not having clientside code in the first place, and while there's talks of SSCSM implementation, I believe a shortcut exists. 

In nearly every modern game engine, we see that the user has to download the game to play it, this is because it contains all the necessary clientside code. Minetest can do this too with a lot less effort then might be expected. 

The follow proposes two potential solutions, the first likely being the easiest to implement.

## Solution 1: Hacky, hopefully temporary solution.

(note that I use the term singleplayer, however the terminology should be changed)
- allow a singleplayer world to connect and receive from participating servers, leaving most of the data being sent to modder discretion, aka create an API for opening and reading world to world communication. On the "server" side, players would still be treated as  traditional clients. 
- Data like world info, would likely be best used directly, however. Perhaps a callback oriented approach would be desirable, allowing functions to intercept data and modify or reject it before application.
- create a API allowing the transfer efficient of raw data between singleplayer worlds and servers
- allow singleplayer games to read incoming server data (such as the info of entities that should be drawn)
- players would be sent to the client as entities.

This would sort of be a hack, but it'd work better then what we're doing now, and it'd probably take a whole lot less.

## Solution 2 : Permanent solution, dedicated environment.

Instead of shoehorning it in, create a new dedicated game environment. This would entail the same things as solution 1, but instead of just making it a singleplayer game, it'd be a dedicated system. There wouldn't be a separation between client and (singleplayer) server like there currently is, and APIs, netcode, and all of the other bloat made for serverside multiplayer support wouldn't be loaded at all. I'm not entirely sure what this entails (as I have not yet started to learn C++ or the Minetest Engine). 

## An important addition(?):

for these features to really shine, games should be able to modify limited aspects of the client. I haven't worked much with games, so I am unaware if this is already possible with current APIs, so if anybody knows, let me know.
 
## Additional context

Both of these ultimately would let users create games with clientside code, their own systems for handling player interactions. It would allow for basically infinite smoothness, and make lag compensation actually possible. 

Examples of what this would fix:

Ultimately, either of these would supersede SSCSMs in every capacity

- Take combat for example, if you shoot a bow and arrow, or a gun, currently the server won't know where you shot from no matter what you do, we cannot get when the input occurred, and thus the arrow or bullet may not represent what was intended by the player. 
- Driving, as another example. Currently driving is extremely laggy, sometimes bordering unplayable, input compensation alone would help, sure, but it wouldn't be responsive on the clientside still. If we can have code moving the in game object on the client's 
- Update speeds, the client has a hard time compensating for updates: take my spriteguns or my 3dguns mod, for example: the implementation of either would look smooth on clientside server with a high update speed, but looks choppy and horrible with the combination of lag and low update speeds that a server handling complex interactions needs to maintain.
- movement on objects: client could smooth walking on objects (for example, in a airship mod similar to Minecraft's Archimede's Ships)
- Clientside settings
 
The list goes on.

There's no doubt in my mind that games being downloaded is the best way to boost the Minetest modding community, and it's creativity.

**Comment by FatalError42O** [comment]
I accidentally hit enter.

**Comment by rubenwardy** [comment]
This issue is very unclear, you're mixing a lot of different things.

Solution 1 sounds like client-provided client-side mods with extra steps. It sounds like you want to run a full server locally and synchronise that with an upstream server.

Solution 2 sounds like removing the client/server split for some games, forcing them to only run in singleplayer. This is not something that I would support, being multiplayer-first is a huge advantage to Minetest.

Neither of these would be shortcuts, SSCSM would be easier to implement. The main obstacle to SSCSM is sandboxing and security. As an alternative to SSCSM, we have discussed letting servers ask for client-side mods to be loaded. The client could automatically obtain these mods from ContentDB. This would solve the security concerns

**Comment by FatalError42O** [comment]
> This issue is very unclear, you're mixing a lot of different things.
> 
> Solution 1 sounds like client-provided client-side mods with extra steps. It sounds like you want to run a full server locally and synchronise that with an upstream server. This would be very complicated and janky and not solve the issue.
> 
> Solution 2 sounds like removing the client/server split for some games, forcing them to only run in singleplayer or game developers to implement their own networking. This is not something that I would support, being multiplayer-first is a huge advantage to Minetest.
> 
> Neither of these would be shortcuts, SSCSM would be easier to implement. The main obstacle to SSCSM is sandboxing and security. As an alternative to SSCSM, we have discussed letting servers ask for client-side mods to be loaded. The client could automatically obtain these mods from ContentDB. This would solve the security concerns
> 
> It feels like what you want is more client-side control but what you're asking for is (solution 1) a networking API and (solution 2) something else

I agree partially agree with you, except that you'd be forced to implement a full client side API that'd allow you to implement the behavior I mentioned solving. The idea behind either is that you still use the built in net code for clients, however you have the option to override it's direct influence on entities. I.e. ideally you'd be allowed to know the location that the client would normally draw the entity to- the location that the server and client prediction tells you it should be, but you can simply change it. This would have to be coupled with high update speeds for it to really make any sense.
