### ISSUE TITLE
Add a darker background to the chat

### ISSUE THREAD

**Issue by zShxck720** [minetest/minetest#13570]
## Problem

I find really hard to read chat while playing and i need to constantly look towards a dark surface to be able to read it.

## Solutions

It would be nice to have a darker background for the chat while one plays (when i press T to chat the darkness is good there), this should fix the problem. Also would be nice to have a setting to decrease or increase the darkness of the background.

**Comment by SwissalpS** [comment]
something like ``console_color`` and ``console_alpha`` but for chat?  
so ``chat_color``, ``chat_background_color`` and ``chat_background_alpha``

I see how that could be useful but also annoying too.

**Comment by zShxck720** [comment]
yes i think could be annoying for some people, that's why could be useful
to add like a slider in the settings to increase or decrease the darkness

**Comment by Zughy** [comment]
The background was mentioned in #10372 alongside other problems, closing in favour of that issue
