### ISSUE TITLE
Use VoxelManip:calc_lighting from outside minetest.get_mapgen_object

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#13576]
## Problem

I want to update lighting after doing voxel manipulation outside of a map generation. The documentation for `calc_lighting` says the following:

> * `calc_lighting([p1, p2], [propagate_shadow])`:  Calculate lighting within the
>   `VoxelManip`.
>  * __To be used only by a `VoxelManip` object from `minetest.get_mapgen_object`.__

I assume `minetest.get_mapgen_object` is forbidden outside of a map generation context. I do not know what to do in this case other than implementing light propagation in Lua myself (which is too complicated for me to bother with).

## Solutions

Support `calc_lighting` for all VoxelManip objects. 

I would also love to know why this limitation exists.

**Comment by SmallJoker** [comment]
`vm:write_to_map()` updates the light propagation for any VManip object.

`calc_lighting` was added in https://github.com/minetest/minetest/commit/d6ac3d8d9a6484f2d348d1caea203de0069b6bd6 without an explanation. I believe this based on an optimization where the code relies on the fact that newly initialized (=generated) MapNodes inside the mapgen VManip are initialized with param1=0 (light values, dark) to then spread the light on them. Existing nodes would not be touched, hence slight speed-up in the calculation. Relevant code:

https://github.com/minetest/minetest/blob/c91182e1b3c38cb0a983c3330db534a84aa01af2/src/mapgen/mapgen.cpp#L468-L559

The code also relies on a few references to the emerge object which should only be used by mapgen threads. This could be fixed but said optimized functions might be trickier to get right.

**Comment by SmallJoker** [comment]
If you are not writing to the map (via VManip), consider using `minetest.fix_light(pos1, pos2)` instead. This will also recalculate the light in the specified volume.
