### ISSUE TITLE
yawsprite doesn't work on OpenGL ES 2 (with shaders enabled)

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13580]
##### Minetest version

```
5.8.0-dev (commit hash update soon)
```

##### OS / Hardware

Operating system: Android 6.0.1r10  (API lv23)
CPU: MediaTek

GPU model: Mali
OpenGL ES version: 3.1

##### Summary

yaw sprite object dont work if shader enabled
![Screenshot_20230611-101059](https://github.com/minetest/minetest/assets/76146430/41d9b87f-d897-4ba5-badb-9407d2f3c012)

https://youtu.be/VfjZ8FXiink
##### Steps to reproduce

0. set graphic driver to OpenGL ES 2 and enable shader
1. Open devtest
2. spawn yaw sprite
3. see the bug
4. its dont happen whem shader are off

**Comment by SmallJoker** [comment]
Closely related #11206

**Comment by nininik0** [comment]
That also happens to me, if you disable shaders then some animated sprites or yawsprites do their thing,  but some Meshes render in fulbright  kinda like my issue but FOR SOME REASON THEY SAID THAT WHAT I SAID I
![Screenshot_20230610-173732_Minetest](https://github.com/minetest/minetest/assets/132112852/a12ee489-17e0-4b78-b9d1-0447c2300242)
![Screenshot_20230610-173711_Minetest](https://github.com/minetest/minetest/assets/132112852/dbe399e1-2f56-48f7-bbc8-6f8302004cf7)
![Screenshot_20230610-173650_Minetest](https://github.com/minetest/minetest/assets/132112852/eb1dda91-82da-4e18-84ec-55310fb5580d)
![Screenshot_20230610-173324_Minetest](https://github.com/minetest/minetest/assets/132112852/18c08950-8223-47b1-b0fa-6f0a828a8bfe)
![Screenshot_20230610-173518_Minetest](https://github.com/minetest/minetest/assets/132112852/995d7143-e424-4e88-ae3c-f0dde30616c4)
S not understandable

**Comment by nininik0** [comment]
Android bug, happens to me too i think this has to be the unity .shader file or something

**Comment by oong819** [comment]
action workflow android build (apk unsigned)

**Comment by oong819** [comment]
> That also happens to me, if you disable shaders then some animated sprites or yawsprites do their thing, but some Meshes render in fulbright kinda like my issue but FOR SOME REASON THEY SAID THAT WHAT I SAID Is incorrect (:/) ![Screenshot_20230610-173732_Minetest](https://user-images.githubusercontent.com/132112852/245192790-a12ee489-17e0-4b78-b9d1-0447c2300242.png) ![Screenshot_20230610-173711_Minetest](https://user-images.githubusercontent.com/132112852/245192804-dbe399e1-2f56-48f7-bbc8-6f8302004cf7.png) ![Screenshot_20230610-173650_Minetest](https://user-images.githubusercontent.com/132112852/245192810-eb1dda91-82da-4e18-84ec-55310fb5580d.png) ![Screenshot_20230610-173324_Minetest](https://user-images.githubusercontent.com/132112852/245192820-18c08950-8223-47b1-b0fa-6f0a828a8bfe.png) ![Screenshot_20230610-173518_Minetest](https://user-images.githubusercontent.com/132112852/245192831-995d7143-e424-4e88-ae3c-f0dde30616c4.png) not understandable

its because your issue not following the issue template

**Comment by nininik0** [comment]
@rubenwardy  do you think this would be fixed?

**Comment by nininik0** [comment]
I guess our issue will never be fixed 
 😞 😪
