### ISSUE TITLE
WHY is minetest so strict in the recent updates?

### ISSUE THREAD

**Issue by nininik0** [minetest/minetest#13585]
Before minetest 5.6.1 and 5.7.0 you could enable a mod with a missing dependency it would let you join it would give you an in game message, also before 5.6.1 you could have a mod with no mod.conf file, now you must have all dependencies and all files or else BOOM your game crashes because of one inconvenience, this needs to be less strict.

**Comment by nininik0** [comment]
Close this if you want to, I'm just saying.

**Comment by rollerozxa** [comment]
If you have mods with unresolved dependencies you should disable those mods or resolve the dependencies.

**Comment by rubenwardy** [comment]
> Before minetest 5.6.1 and 5.7.0 you could enable a mod with a missing dependency it would let you join it would give you an in game message,

Minetest used to disable the mod when dependencies were missing. This was very confusing and error prone, so now users need to disable the mod themselves or install the missing dep

>  before 5.6.1 you could have a mod with no mod.conf file, now you must have all dependencies and all files or else BOOM your game crashes because of one inconvenience, this needs to be less strict.

There's a warning for having mod.conf, but this doesn't crash the game or prevent loading

**Comment by nininik0** [comment]
Hmm, but I played minetest 5.6.1 if there was no mod.conf my game crashed. Also in 5.6.1 you could have a mod in the game you downloaded that Is missing a non-existent mod and your game didn't crash it just disabled the mod and gave an error in game.

**Comment by nininik0** [comment]
In minetest 5.5.0 I could have no mod.conf and I'd be fine.

**Comment by nininik0** [comment]
Thanks for telling me that Rubenwardy

**Comment by nininik0** [comment]
And why is minetest crashing when i have a depends.txt file instead of mod.conf? Or when I have both of them. This is weird. I'll close this issue with another comment.
