### ISSUE TITLE
cannot add mods from internet

### ISSUE THREAD

**Issue by efa** [minetest/minetest#13584]
##### Minetest version
```
5.7.0 AppImage from https://gitlab.com/minetest/minetest/-/tags/5.7.0
```

##### OS / Hardware

Operating system: LMDE5 (based on Debian 11)
CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

GPU model: GeForce GTX850M
OpenGL version: 3.0 Mesa 20.3.5

##### Summary
cannot add mods from internet

##### Steps to reproduce
from the main Window, press "Select Mods", then press "Find More Mods" button
always show "No packages could be retrieved"

Minetest 5.3.0 from Debian11 repo work as expected and find 321 mods

**Comment by nininik0** [comment]
Do you have internet enabled?

**Comment by nininik0** [comment]
Try to install minetest again

**Comment by efa** [comment]
this is the 5.7.0 AppImage from https://gitlab.com/minetest/minetest/-/tags/5.7.0
it is a portable app, no installation needed.

Minetest 5.3.0 from Debian11 repo work as expected and find 321 mods

**Comment by efa** [comment]
```
$ date
Mon Jun 12 19:14:13 CEST 2023

$ sudo apt update && sudo apt upgrade
Hit:1 http://deb.debian.org/debian bullseye-backports InRelease
Hit:2 http://security.debian.org bullseye-security InRelease                                                                                                                                                                                 
Hit:3 http://dl.google.com/linux/earth/deb stable InRelease                                                                                                                                                                                  
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease                                                                                                                                                                 
Hit:5 https://dl.winehq.org/wine-builds/debian bullseye InRelease                                                                                                                                                                            
Hit:6 https://deb.debian.org/debian bullseye InRelease                                                                                                                                                                                       
Hit:7 https://linux.teamviewer.com/deb stable InRelease                                                                                                                                                                                      
Hit:8 https://deb.debian.org/debian bullseye-updates InRelease                                                                                                                                                                               
Hit:9 https://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                                 
Hit:10 https://download.virtualbox.org/virtualbox/debian bullseye InRelease                                     
Hit:11 https://packages.element.io/debian default InRelease                               
Ign:12 http://packages.linuxmint.com elsie InRelease                
Hit:13 http://packages.linuxmint.com elsie Release
Hit:14 https://repo.steampowered.com/steam stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

if I open the link:

https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=42&engine_version=5.7.0&hide=nonfree&hide=desktop_default

in a browser (Firefox) it show a list of 1922 numbers, that appear to be the mods.

It is Minetest 5.7 that cannot load the page.

**Comment by efa** [comment]
if can help, I repeated the test with Chrome, and fail to load the page, it show a page full of code like this:

`[{"author":"Warr1024","name":"nodecore","release":19169,"short_description":"Featured. Minetest's top original voxel game about emergent mechanics and exploration","thumbnail":"https://content.minetest.net/thumbnails/1/6b28be927c.jpg","title":"NodeCore","type":"game"},{"author":"yaman","name":"alter","release":16458,"short_description":"Featured. A challenging puzzle game in a dystopian future.","thumbnail":"https://content.minetest.net/thumbnails/1/7550c290b5.png","title":"Alter","type":"game"},{"author":"Minetest","name":"minetest_game","release":18024,"short_description":"Featured. A lightweight and well-maintained base for modding","thumbnail":"https://content.minetest.net/thumbnails/1/8ffd1409ff.jpg","title":"Minetest Game","type":"game"},{"author":"Mantar","name":"exile","release":18933,"short_description":"Featured. Challenging, at times brutal, wilderness survival with simple technology. ","thumbnail":"https://content.minetest.net/thumbnails/1/0195f6298c.jpg","title":"Exile","type":"game"},{"author":"Wuzz
...
`

**Comment by sfan5** [comment]
This is probably some edge case or packaging mistake with the AppImage.
I suggest you use a different way to install Minetest. Nobody really uses/tests the AppImage and we can't support it properly.

**Comment by efa** [comment]
for old CA certificate this is strange, as my Debian is updated, and I can regularly upload code via SSH certificate to my github repos, and apparetly all other app in this distro work and remotely connect as expected.

Anyway I will re-try the flatpak if you say with that I can download mods, I saw the flatpak Minetest distribution download about 1 GB

**Comment by efa** [comment]
just tested the flatpack:
```
efa@08i7-2500:~$ flatpak install flathub net.minetest.Minetest
        ID                                                        Branch                  Op             Remote             Download
 1. [v] net.minetest.Minetest.Locale                               stable                  i              flathub              66,6 kB / 1,5 MB
 2. [v] org.freedesktop.Platform.GL.default                        22.08                   i              flathub             143,6 MB / 143,1 MB
 3. [v] org.freedesktop.Platform.GL.default                        22.08-extra             i              flathub              16,2 MB / 143,1 MB
 4. [v] org.freedesktop.Platform.GL.nvidia-470-182-03              1.4                     i              flathub             272,9 MB / 272,6 MB
 5. [v] org.freedesktop.Platform.Locale                            22.08                   i              flathub               3,3 MB / 333,4 MB
 6. [v] org.freedesktop.Platform.VAAPI.Intel                       22.08                   i              flathub              13,6 MB / 13,4 MB
 7. [v] org.freedesktop.Platform.openh264                          2.2.0                   i              flathub               1,2 MB / 944,3 kB
 8. [v] org.freedesktop.Platform                                   22.08                   i              flathub             244,8 MB / 214,4 MB
 9. [v] net.minetest.Minetest                                      stable                  i              flathub              16,8 MB / 12,8 MB

efa@08i7-2500:~$ flatpak run net.minetest.Minetes
error: app/net.minetest.Minetes/x86_64/master not installed
```

what I miss here?

**Comment by efa** [comment]
just tested the flatpak. It start but once in the main Windows, the button "Select Mods" do not do anything.
BTW, it do not see my worlds created by 5.3.0 Debian11

**Comment by efa** [comment]
Just saw that going to "Content" tab and clicking button "Browse online content" show "No packages could be retrieved".
In the console I still see the error:
`2023-06-12 22:36:59: ERROR[Main]: HTTPFetch for https://content.minetest.net/api/packages/?type=mod&type=game&type=txp&protocol_version=42&engine_version=5.7.0&hide=nonfree&hide=desktop_default failed (SSL peer certificate or SSH remote key was not OK)`

Just tested the un-official 5.7.0 AppImage from here:
`https://github.com/An0n3m0us/Minetest-AppImages/releases`
this can find online mods and worlds with no error in the console.

**Comment by efa** [comment]
in the mean time I upgraded my distro from Mint/LMDE5/Debian11 to Debian12

5.7.0 AppImage from https://gitlab.com/minetest/minetest/-/tags/5.7.0

Operating system: Debian 12
CPU: Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz

GPU model: GeForce GTX850M
OpenGL version: 4.6 Mesa 22.3.6-1

Here pressing "Select Mods", then press "Find More Mods", find 435 mods, all works
