### ISSUE TITLE
Stuck on media

### ISSUE THREAD

**Issue by TheFreePenguin** [minetest/minetest#13595]
##### Minetest version

```
5.4
```

##### OS / Hardware

Operating system: Pop 22.04
CPU: Intel core i7

GPU model:
OpenGL version:

##### Summary

I connect to a server, it's stuck on media. The close button isn't doing anything, so I shut down my system using sudo poweroff. The computer is still on, and this is the 2nd time something like that has happened.

##### Steps to reproduce

Connect to a remote server, progressbar was stuck on media..., do a system shutdown, system hangs itself up because program refuses to close

**Comment by NathanSalapat** [comment]
Anything in the debug?
Also 5.4 is rather old, have you tried with a newer version? Same server both times? have you been able to connect to the server at any point?

**Comment by TheFreePenguin** [comment]
> Also 5.4 is rather old
Tell that to the Pop!_OS devs, not me

> Same server both times?
No, and these issues happened with some time between. Another thing I noticed was that the UI of the OS pauses for a while while Minetest loads, it also did that for a short while when I had this issue. By the way, the computer has shut down now, it just took longer than usual.

**Comment by NathanSalapat** [comment]
I'm not entirely sure what packaging system Pop uses, but you should probably be able to get a newer version of minetest from the downloads page.
How much ram do you have? I wonder if maybe you are maxing out and that's causing the system to hang.

**Comment by Desour** [comment]
> > Also 5.4 is rather old
>
> Tell that to the Pop!_OS devs, not me

Please don't be disrespectful.

----


The only reason your system "hang up" is because you shut it down while something was still running, right?

How long did you wait in the loading screen?

Have you tried a simple game?

If you launch minetest in a terminal with `--debug` (`minetest --debug`), and kill minetest while it seems to be stuck (i.e. press ctrl+c in terminal), does it shut down? And what is the terminal output?

**Comment by rubenwardy** [comment]
Please try this on 5.7. We cannot provide support for older versions. You can use Flatpak or the PPA to get an up-to-date version

**Comment by debagos** [comment]
@TheFreePenguin Does it happen when you play local too, like when you host a server on your own computer?

Note for the devs:
I can confirm that (even on latest master) if the client gets only one SIGTERM while downloading the server media, Minetest will continue the whole join process, but will close immediately after the initialization.

**Comment by falsechicken** [comment]
I am having this issue too on 5.7. It loads media forever. The background clouds keep moving and if I try to exit Minetest the progress bar immediately continues the join process until its done then closes. On my primary PC it works fine but on my old Thinkpad T400 this happens. I know this machine is like 15 years old but I would expect an error or something. I ran 5.6 on this machine before and it worked. 

OS: Garuda Sway Edition
Hardware: Thinkpad T400
Ram: 8GB

**Comment by SmallJoker** [comment]
It would be helpful if someone who is affected by this issue could build a Minetest version with debug symbols.

1. Start Minetest: `gdb ./minetest`
2. `r` in gdb to start the process
3. Get stuck while loading media
4. Press Ctrl+C in the terminal
5. Post the output of `thread apply all bt`. This way we should be able to figure out where it gets stuck.
6. Continue with `c` and and repeat step 4 & 5 to narrow down the thread that is stuck
