### ISSUE TITLE
Add volumetric lighting support

### ISSUE THREAD

**Issue by Jackdeth17** [minetest/minetest#13603]
![image](https://github.com/minetest/minetest/assets/2122943/3cd2703e-adfc-4a67-9bf4-833ad4e50877)

Previous issue: #6309

**Comment by Zughy** [comment]
Isn't there one already @rubenwardy ? Can't compile right now

**Comment by Jackdeth17** [comment]
No I check I just see bloom in the graphics option. I have adhd learning disability and don't know how to compile it

**Comment by tigercoding56** [comment]
> No I check I just see bloom in the graphics option. I have adhd learning disability and don't know how to compile it

`sudo apt remove adhd `   , https://github.com/minetest/minetest/pull/12465 , volumetric lighting can be done using the new rendering pipeline , but    the godrays / volumetric lighting is  not implemented / merged yet   https://github.com/x2048/minetest/tree/volumetric_light

**Comment by grorp** [comment]
#13881 merged.
