### ISSUE TITLE
Dynamic shadow strength varies randomly

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#13601]
##### Minetest version
```
Minetest 5.8.0-dev-debug-edcbfa31c (Linux)
Using Irrlicht 1.9.0mt11
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware
Operating system: Void Linux
CPU: Ryzen
GPU model: Radeon RX560
OpenGL version: 4.6

##### Summary
From launch to launch, dynamic shadow strength varies from very subtle to very strong.
| ![screenshot_20230617_123919](https://github.com/minetest/minetest/assets/7352626/0348bc1b-de73-4d29-8b19-7ac3099d3900) | ![screenshot_20230617_123924](https://github.com/minetest/minetest/assets/7352626/178a08f6-b8ba-4684-a1f0-002308523e35) |
|--|--|

##### Steps to reproduce
1. Enable dynamic shadows
2. Start the game
3. Observe shadows
4. Return to the main menu
5. Repeat from (2)

**Comment by rollerozxa** [comment]
This is intentional behaviour in Minetest Game's weather mod, I believe.

**Comment by Niklp09** [comment]
https://github.com/minetest/minetest_game/issues/3024

**Comment by numberZero** [comment]
Indeed. Very distracting when testing dynamic shadows specifically (for #13321).
