### ISSUE TITLE
Use bilinear filter when downscaling GUI images

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#13621]
## Problem

> Minetest does a horrible job at downscaling the larger version of the image.
> ![scrot](https://user-images.githubusercontent.com/7613443/246891733-6e64fb62-38cf-4bac-94be-ef4a70218799.png)
> I've tried other sizes, many were even worse. It looks like gui images are not even drawn with bilinear filter (tested with a different texture).

*Originally posted by @Desour in https://github.com/minetest/minetest/issues/13606#issuecomment-1597509092*

Minetest cannot upscale GUI images with bilinear filtering because that would blur pixel art, but we can *downscale* images with bilinear filtering. This would make downscaled images look much better. Compare these screenshots:

The Minetest logo on the about tab. The original resolution of the logo is 256x256 pixels. Downscaled without bilinear filtering.
![screenshot before](https://github.com/minetest/irrlicht/assets/82708541/9ae2bf5b-bef2-4930-a50d-3d231cc4d1a0)

The Minetest logo on the about tab. The original resolution of the logo is 256x256 pixels. Downscaled with bilinear filtering.
![screenshot after](https://github.com/minetest/irrlicht/assets/82708541/27f69dd3-431f-4bf8-9c98-9c2fa9f7523e)

## Solutions

Use bilinear filtering when rendering 2D graphics, but just for downscaling textures, not for upscaling. This will require changes to IrrlichtMt, as it currently doesn't allow setting the minification and the magnification filter separately.

## Alternatives

None.

**Comment by Desour** [comment]
A bit related: #13108

---

I support this.
