### ISSUE TITLE
Windows: Unicode text is garbled when copied to clipboard

### ISSUE THREAD

**Issue by Monniasza** [minetest/minetest#13646]
##### Minetest version
```
5.7.0
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel(R) Core(TM) i5-7300HQ @ 2.50GHz

##### Summary

Copying the Cyrillic text from the sign:
![image](https://github.com/minetest/minetest/assets/37037712/1e28285c-b33e-43c4-9489-b6caba1c1fb7)
results in mojibake when pasted:
![image](https://github.com/minetest/minetest/assets/37037712/75541fce-5ffa-41e7-a029-2a20a165f0ba)

##### Steps to reproduce
1. Place a sign
2. Type some Cyryllic text into a sign
3. Close the sign formspec
4. Open the sign
5. Copy the sign text
6. Paste the sign text somewhere else

**Comment by doug65536** [comment]
The only place I see it copying is where it gets the UTF8 and copies it. I would only expect the "A" (ANSI) API to fail with UTF8, but UTF-16 W (UTF-16 "wide") API would.

**Comment by sfan5** [comment]
it does: https://github.com/minetest/irrlicht/blob/d98dc90b3808335a54b3ab7fe10f177148423942/source/Irrlicht/COSOperator.cpp#L82

but the conversion functions appear to be faulty: https://github.com/minetest/irrlicht/pull/221

**Comment by grorp** [comment]
I can reproduce this with a non-SDL Windows build, system language set to English and Minetest language set to German. With an SDL Windows build, copy-paste works fine, but there are other issues with Unicode (text input, window title).
