### ISSUE TITLE
Vector metatable doesn't carry over to async environment

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#13644]
##### Minetest version
```
Minetest 5.8.0-dev-26453df (Linux)
Using Irrlicht 1.9.0mt11
Using Lua 5.1.5
```

##### Summary
When you pass vectors into or out of the async environment they lose their metatable.
Ideas on how to fix this welcome.

##### Steps to reproduce
```lua
	local v = vector.zero()
	print(type(getmetatable(v)))
	core.handle_async(function(v_)
		print(type(getmetatable(v_)))
	end, function() end, v)
```
Result:
```
table
nil
```

**Comment by Desour** [comment]
It would also be nice if metatables of mod-provided types were also transferred.

One could take inspiration of <https://repo.or.cz/luajit-2.0.git/blob_plain/HEAD:/doc/ext_buffer.html#serialize_options>: Have a global table in each side's lua state, which contains commonly known metatables. And in the serialized table, only store an index into this table.

**Comment by fluxionary** [comment]
also noting that the metatables of item defintions don't survive transfer to the insecure environment

**Comment by sfan5** [comment]
> also noting that the metatables of item defintions don't survive transfer to the async environment

There's a fix for that here: https://github.com/minetest/minetest/pull/13092/commits/05c58a5063f3e6b8e726562d88f302c9f7b295ac
