### ISSUE TITLE
update nod/block

### ISSUE THREAD

**Issue by hayimgo** [minetest/minetest#13645]
##### Minetest version
5.7.0

##### mods
https://github.com/v-rob/computer_deco

##### OS / Hardware

Operating system: fedora 38 workstion
CPU: ryzen 5 4600g

##### Summary

AsyncErr: Lua: Runtime error from mod '*builtin*' in callback item_OnPlace(): .../worlds/town 1_1/worldmods/computer_deco-master/init.lua:176: attempt to call global 'nodeupdate' (a nil value)
stack traceback:
	.../worlds/town 1_1/worldmods/computer_deco-master/init.lua:176: in function 'on_rightclick'
	/tmp/.mount_MinetefooNiA/usr/bin/../builtin/game/item.lua:313: in function </tmp/.mount_MinetefooNiA/usr/bin/../builtin/game/item.lua:306>
##### Steps to reproduce

right-clicking block/node

[AsyncErr Lua Runtime error.txt](https://github.com/minetest/minetest/files/11941757/AsyncErr.Lua.Runtime.error.txt)

**Comment by NathanSalapat** [comment]
File this bug report on the mods repository, as it's a mod issue. Nodeupdate doesn't exist, maybe six years ago it was a thing, but no mention of it anymore in the API.

**Comment by wsor4035** [comment]
please file an issue on the mods repo
