### ISSUE TITLE
A Wii port

### ISSUE THREAD

**Issue by zeeboi9** [minetest/minetest#13651]
Hi if your reading thhis you probably think im crazy and yes even with the extreme shortage of memory on the wii i was woundering if it is possible to run this on the wii i would love for someone to help me figure out what optimizations and tweaks i should know so this can be ported to the wii

**Comment by rubenwardy** [comment]
Hi, this isn't something we're going to support officially, but could be done by a third-party member of the community

See [the FAQ for more info](https://wiki.minetest.net/FAQ#Can_you_add_support_for_X_platform_or_console.3F):

> Minetest is a volunteer project with limited time and resources. Supporting a new platform takes a lot of effort, and we're only able to officially support platforms with a core developer using it.
> 
> In terms of consoles, if someone is willing to make a homebrew port for a game console then it can be done, and this port can be submitted to upstream given that the changes aren't intrusive and some kind of maintenance is kept. Putting Minetest onto a games console in any official capacity is not possible due to NDAs preventing an open source release, which is incompatible with the LGPLv2.1 license.
> 
> Minetest is open source. We welcome contributors to port Minetest to other platforms (providing they follow the licenses of course).

**Comment by rollerozxa** [comment]
The Wii has way too little RAM to be able to handle Minetest, 88MB is very much not enough to bring over Minetest in any usable capacity.
