### ISSUE TITLE
Proposal: Completely separate scripts from the minetest engine

### ISSUE THREAD

**Issue by snowyu** [minetest/minetest#13654]
Currently, there are three script hosts in the minetest engine:

1. The mainmenu script host, used in the main menu, located in the "builtin/" directory
2. The game script host, used in the game client, located in the "clientmods/" directory
3. The server script host, used in the game server, located in the "mods/" directory

The script code in these hosts cannot be shared each other, which means that in order to implement a feature, code might need to be written in all three places.

<details><summary>For example</summary>
If a nickname module is created to allow children to input their own nicknames, and an input box is added to the main menu to simplify the process, the main menu cannot call the nickname module's API to set the nickname. The code for the nickname module and its dependencies would need to be copied into the "builtin/" directory, and a configuration format that is not easy to use would need to be added. Additionally, the nickname setting in the main menu can only be used in single-player mode, and a CSM must be written to send the nickname to the server in multiplayer mode.
</details>

Therefore, I propose that there should be only one script host in the minetest engine, and the following should be done:

1. All script code should be placed in the "`mods/`" directory.
2. Modpacks should support multi-level folders, meaning that modpacks can contain not only multiple modules, but also other modpacks.
3. The main menu (`mainmenu`) script should be allowed to be included in a modpack as a special "`menu`" mod.
4. The subgame directory should be removed, and subgames should be treated as modpacks.
5. Add the `type` field to `modpack` configuration, eg, "game", "menu", "mods"
6. Add the `type` field to `mod` configuration. eg, "server", "client", "menu", "client/server"
7. A new script API should be added to check whether the execution environment is a client or server: eg, "`minetest.isClient`".
8. The "`mod.conf`" file should include a [semantic version field](https://docs.npmjs.com/about-semantic-versioning) for version management.
9. Permissions should be controlled as follows:
    * The mod folder containing the function("`mods/`") and the mod configuration data("`mod_data/`") should have read-write access.
    * Other mods and configuration data folders should have read access.
    * Private folders should have a "`.`" prefix and be completely inaccessible to other modules.
    * Public folders should be named "`public`" and have completely read-write access to other modules' files.

Other potential permissions include:

1. Privileges in the game.
2. Full network access.
3. Access to recording devices.
4. Access to camera devices.

When a module is first accessed or a call to the authorization API is made, an authorization dialog should appear to allow the user to decide whether to grant access.

Because functions may have dependencies on other modules' functions, the initial caller of the function must be determined in order to determine the IO access permissions. The only solution I can think of is to analyze the call stack to determine the initial caller of the function (See My PR #12954). However, due to a bug or optimization in Lua/LuaJIT, tailcall functions cannot be seen in the call stack, which is a serious security vulnerability. My current solution for this is to disable tailcall function optimization directly in the Lua engine.

Of course, I believe that there are better solutions for the many Lua experts here, and I welcome any suggestions.

The proposed changes offer several benefits for the minetest engine and its users. By separating scripts from the engine, the modding experience becomes more streamlined and flexible. Modpacks can be organized more effectively and the `mainmenu` script can be included as a part of a modpack, simplifying the process of changing the main ui menus. The subgame directory is removed, and subgames are treated as modpacks, making it easier to manage and organize different game modes. The new script API to check the execution environment allows for more efficient and targeted scripting. The permission system allows for more granular control over module access and can improve the security of the engine. Overall, these changes can make the minetest engine more user-friendly, secure, and flexible.

**Comment by SmallJoker** [comment]
Many Minetest features also require a change in builtin/ which is basically the same discussion as in #13034. It might be possible to split the code a bit but at this point I think it would be easier to add your custom files and add a single `dofile()` call into the builtin init.lua script which would then overwrite the functionality you would like to change or replace.

**Comment by rubenwardy** [comment]
What exactly is the problem you're trying to solve here? Main menu modding? Please don't just the issue template, the 'problem' section exists for a reason

**Comment by Zughy** [comment]
Closing as invalid (see previous comment)

**Comment by snowyu** [comment]
@Zughy  modified

**Comment by snowyu** [comment]
@SmallJoker  I wish all Lua code in Minetest to have equal privileges, without any particular type of script having elevated permissions. 

Hereby, the mainmenu interface code (builtin) of Minetest is treated equally as regular mods, and the Lua helper functions that used to be internal to Minetest are also incorporated as mods.

By unifying the script host in this way, the security of Minetest is greatly enhanced.

Furthermore, by centralizing all lua code within mods, the maintenance of Lua code becomes much easier. With mods located within subgames, it is now possible for other mods or even subgames to utilize these mods.

The three different types of mods, `csm`, `ssm`, and `ssmcsm`, can now also be maintained within the same mod and share codes each other.
