### ISSUE TITLE
[suggestion] Make Minetest Support for Apple Silicon (Natively).

### ISSUE THREAD

**Issue by KaungZinLin** [minetest/minetest#13655]
Minetest currently only supports Intel, so if anyone has a Mac with an Apple Silicon Chip, then, macOS will auto-use Rosetta, which is a translation layer. It works, but it doesn't perform well.

As Apple Silicon has been out and popular since its release, the great guys at Minetest should make it support for Apple Silicon Natively.  

I'm looking forward to that new version and improvements

**Comment by sfan5** [comment]
Minetest can be compiled to work on ARM on macOS ("Apple Silicon"). Please clarify where you are expecting support for this.

**Comment by oong819** [comment]
you mean CPU architect? Minetest did not support Intel, Minetest support x86 & ARM

**Comment by rubenwardy** [comment]
> you mean CPU architect? Minetest did not support Intel, Minetest support x86 & ARM

x86 is Intel

**Comment by ranguli** [comment]
Perhaps the question being asked here is whether official Minetest builds exist for Apple Silicon?

**Comment by 7ombie** [comment]
Minetest is utterly unplayable on the M1.

My son wanted to make a game to learn programming, and we thought Minetest would be ideal, but he's on a Mac.
