### ISSUE TITLE
Feature Request: Being able to add textbox limitations (formspec)

### ISSUE THREAD

**Issue by chmodsayshello** [minetest/minetest#13658]
## Problem
Currently, it is not possible to add certain limitation to textboxes in formspecs,like:

- limit amount of characters per line
- limit amount of total lines

Instead, you have to add a label that everything asking the user to do so, which is not very convenient, as you can't expect someone to count the amount of characters they type

## Solutions

Add a way to the lua api to make a formspec, containing a textbox with the limitations mentioned above

## Alternatives

- None (yet)

## Additional context

MineClone 2 signs

**Comment by v-rob** [comment]
Duplicate of #8412
