### ISSUE TITLE
how about we create a mega-issue about UI/UX?

### ISSUE THREAD

**Issue by Heus-Sueh** [minetest/minetest#13659]
## Problem

the problem is that the minetest UI/UX is bad but we have no idea where to start to fix these problems

## Solutions

create issues relating to each element of the game: splash screen, singleplayer, multiplayer, settings and etc... and how contributors can help improve it

## Alternatives

we can also use github projects to organize things

**Comment by Niklp09** [comment]
Already done for settings https://github.com/minetest/minetest/issues/13476

**Comment by Heus-Sueh** [comment]
> Already done for settings https://github.com/minetest/minetest/issues/13476

we need to do more stuff like this

**Comment by rubenwardy** [comment]
Just creating more vague issues won't help, issues need to have actionable steps to have any chance of ever being closed. So I'd suggest doing a UX review, contributing to main menu redesigns, and tracking UX issues using a project. For discussion, can use this issue or the forums

**Comment by Heus-Sueh** [comment]
> Just creating more vague issues won't help, issues need to have actionable steps to have any chance of ever being closed. So I'd suggest doing a UX review, contributing to main menu redesigns, and tracking UX issues using a project. For discussion, can use this issue or the forums

So, in order not to create unnecessary issues, how about opening the discussion tab?

**Comment by rubenwardy** [comment]
> So, in order not to create unnecessary issues, how about opening the discussion tab?

I forget why but there was a decision not to use discussions. We use our forums instead: https://forum.minetest.net/
