### ISSUE TITLE
is android.support.v4 really needed?

### ISSUE THREAD

**Issue by oong819** [minetest/minetest#13657]
the built apk of Minetest's classes.dex decoded contain android/support/v4

for what i know android.support are deprecated, Minetest don't support v4 (min api lv 21)

so can we remove it?

**Comment by rubenwardy** [comment]
I believe that v4 is the version of the support library, not the Android version. But yes, androidx should generally be used instead

**Comment by sfan5** [comment]
We don't have any references to this. If it's included then it's part of AndroidX.
