### ISSUE TITLE
add a scroll to the creative's inventory

### ISSUE THREAD

**Issue by Heus-Sueh** [minetest/minetest#13653]
## Problem

It's very annoying to have to keep changing pages from 1 to 2 and so on...

## Solutions

add a scroll in the right corner
![image](https://github.com/minetest/minetest/assets/98482469/681d5a51-dfb4-4aa7-bf1d-b8c5726cced4)

like this:
![image](https://github.com/minetest/minetest/assets/98482469/4026bb87-0f86-4796-a601-92fee41968b3)

**Comment by wsor4035** [comment]
please file an issue on the game/mod that you are using

**Comment by Heus-Sueh** [comment]
> please file an issue on the game/mod that you are using

Sorry, I thought it was already clear, the game is standard minetest and the mode is creative

**Comment by wsor4035** [comment]
> > please file an issue on the game/mod that you are using
> 
> Sorry, I thought it was already clear, the game is standard minetest and the mode is creative

which would be at found at https://github.com/minetest/minetest_game
