### ISSUE TITLE
Allow specific file paths to ignore when loading a mod

### ISSUE THREAD

**Issue by yogwoggf** [minetest/minetest#13663]
## Problem

I use NPM in my workflow, so a `node_modules` is generated in my modpack directory. Minetest thinks it's a mod and tries to find a `init.lua` in it, and it fails.

## Solutions

A new entry in `modpack.conf` and `mod.conf` that allows you to specify what file paths to ignore. I would recommend the glob pattern.

## Alternatives

It's not a new issue, so workarounds have been made, like making NPM output to a different node_modules folder, but this requires extra setup and is overall still a workaround.

**Comment by yogwoggf** [comment]
Further testing shows that some node applications break when the node_modules is moved, so the workarounds are not sufficient.

**Comment by wsor4035** [comment]
while not exactly named the best, issue https://github.com/minetest/minetest/issues/11240 already exists

**Comment by yogwoggf** [comment]
> while not exactly named the best, issue #11240 already exists

@wsor4035 While the issue is related, the issue linked only talks about directories that start with . and _
My issue is relating to a specific feature that doesn't exist in Minetest, which is ignoring **specific** directories.

**Comment by wsor4035** [comment]
> > while not exactly named the best, issue #11240 already exists
> 
> @wsor4035 While the issue is related, the issue linked only talks about directories that start with . and _ My issue is relating to a specific feature that doesn't exist in Minetest, which is ignoring **specific** directories.

you ignored the part where i stated "not exactly named the best" see https://github.com/minetest/minetest/issues/11240#issuecomment-841719723 and https://github.com/minetest/minetest/issues/11240#issuecomment-850005220.

its the same issue
