### ISSUE TITLE
set_player_privs does not work

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1366]
minetest.set_player_privs appears to be broken and does not work. When the command is ran, the privilege list is ignored and nothing is changed. Example I tried locally, in which neither "fly" nor "interact" were modified, although typing "/grant singleplayer fly" in the console always work:

minetest.set_player_privs("singleplayer", {interact=false, fly=false})

I believe this is the model that should be used, as documented here:

http://dev.minetest.net/minetest.set_player_privs

**Comment by MT-Modder** [comment]
I know it's been a year or so but...
The page says to use false and the lua_api.txt states nothing about using nil or false but only nil works. I think the page should be changed and a note should be added to the lua_api.txt entry so new modders don't get confused.

**Comment by neoascetic** [comment]
Yeah, just faced with wrong info from the wiki again. Someone, please change the page.
