### ISSUE TITLE
Main menu music suddenly stops

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#13660]
##### Minetest version
Latest master

##### OS / Hardware
Operating system: Linux

##### Summary
When selecting a game on the main menu that has main menu music (e.g. Labyrinth), the music suddenly stops after some seconds. Assumedly caused by the sound refactor, but I haven't bisected the issue.

##### Steps to reproduce
1. Install labyrinth (or another game with main menu music) and select it on the main menu
2. Music plays for a couple seconds and then stops

**Comment by Desour** [comment]
Oops, I completely forgot to test menu music, sorry.

I guess the issue is that the step function is not called. Will fix.
