### ISSUE TITLE
Parts of structures generated using `VoxelManip` in `minetest.register_globalstep` are missing

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#13676]
##### Minetest version
```
Minetest 5.8.0-dev-128d22e6 (Linux)
Using Irrlicht 1.9.0mt11
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

##### OS / Hardware
Operating system: Fedora Linux 37 (Workstation Edition)  
CPU: Intel® Core™ i7-4790K × 8

##### Summary

When I use the `VoxelManip` API to generate structures in a `minetest.register_globalstep` callback, parts of the generated structures are missing. This doesn't always happen. The longer the callback takes to execute, the higher the chance that parts of the structures are missing.

##### Steps to reproduce

Sorry for the long "minimal reproducible example".

This is a mod for Devtest. It completely replaces the map generator. **To meaningfully test it multiple times, you either have to create a new world each time or set `backend` to `dummy` in the `world.mt` file of your testing world.**

###### mod.conf

```
name = special_potato
depends = basenodes
```

###### init.lua

```lua
local BUSYWAIT_DURATION = 0 -- try changing this value

minetest.set_mapgen_setting("mg_name", "singlenode", true)

minetest.register_on_joinplayer(function(player)
    print("player joined!")
    player:set_pos(vector.new(0, 16, 0))
end)

local stone = minetest.get_content_id("basenodes:stone")
local dirt = minetest.get_content_id("basenodes:dirt")

local function busywait()
    print("starting to wait...")
    local start = minetest.get_us_time()
    local endd = start + (BUSYWAIT_DURATION * 1000000 / 2)
    while minetest.get_us_time() < endd do
        -- nothing
    end
    print("finished waiting.")
end

local function generate(pos)
    print("generating!")
    local pos_min = pos
    local pos_max = pos + vector.new(32, 12, 32)

    local vm = VoxelManip(pos_min, pos_max)
    local vm_pos_min, vm_pos_max = vm:get_emerged_area()
    local vm_data = vm:get_data()
    local vm_area = VoxelArea:new({MinEdge = vm_pos_min, MaxEdge = vm_pos_max})

    busywait() -- imagine some expensive mapgen code here

    for x = pos_min.x, pos_max.x do
    for y = pos_min.y, pos_max.y do
    for z = pos_min.z, pos_max.z do
        if x == pos_min.x or z == pos_min.z or
                x == pos_max.x or z == pos_max.z then
            vm_data[vm_area:index(x, y, z)] = stone
        elseif y == pos_min.y then
            vm_data[vm_area:index(x, y, z)] = dirt
        end
    end
    end
    end

    busywait() -- imagine some expensive mapgen code here

    vm:set_data(vm_data)
    vm:write_to_map()
    print("generated!")

    local next_pos = vector.new(pos_max.x, pos_min.y - 16, pos_max.z)
    return next_pos
end

local count_generated = 0
local next_generated = vector.zero()

minetest.register_globalstep(function()
    if #minetest.get_connected_players() ~= 0 and count_generated < 6 then
        next_generated = generate(next_generated)
        count_generated = count_generated + 1
    end
end)
```

###### The results

All screenshots were taken after waiting for the generator to finish and then flying up to be able to see everything.

The expected result. When `BUSYWAIT_DURATION` is 0, this is the most common result.
<img src="https://github.com/minetest/minetest/assets/82708541/1b654f18-c0db-4a5f-9196-d86be5eb3c17" alt="screenshot" width="512" />

An unexpected result, parts of the generated structure are missing. When `BUSYWAIT_DURATION` is 1, this is the most common result.
<img src="https://github.com/minetest/minetest/assets/82708541/44fa9cc5-1aa4-4b20-a898-6f0ff9b4fc79" alt="screenshot" width="512" />

Another unexpected result, very uncommon.
<img src="https://github.com/minetest/minetest/assets/82708541/1d01f898-eb77-4121-aaa6-445fb43f3f3b" alt="screenshot" width="512" />

Another unexpected result, also very uncommon.
<img src="https://github.com/minetest/minetest/assets/82708541/8c6760ec-3bed-4c4d-8b09-46c5680c58d3" alt="screenshot" width="512" />

So there's always a chance that parts of the generated structure are missing, but a higher `BUSYWAIT_DURATION` value increases that chance.

**Comment by nininik0** [comment]
Maybe the file glitches? Or maybe because the game thinks they overlap and just says: "Nope I already spawned that structure aint doing that again"

**Comment by grorp** [comment]
There are no schematics / schematic files involved.

I think the problem might be that I am writing to an ungenerated area and the mapgen simply overwrites it later. Looking at the Minetest code, it doesn't look to me like the VoxelManip API takes any precautions against reading / writing ungenerated areas.

I'll try to find out whether this is actually the problem.

**Comment by grorp** [comment]
> I'll try to find out whether this is actually the problem.

I'm now sure that my code is simply wrong. The problem is that it writes to an area with a VoxelManip without first checking if that area is loaded. VoxelManip loads blocks from disk if they have already been generated, but it doesn't generate new blocks. So I'm writing to ungenerated blocks, and I guess the mapgen simply overwrites them later.

Calling `minetest.emerge_area` on the area beforehand fixes the issue. So this isn't a Minetest bug. If anything, the documentation could be made a bit clearer.

I'm not sure why the time taken by the globalstep callback makes a difference.
