### ISSUE TITLE
Objects rotation is in radians but bones rotation is in degrees

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13688]
##### Minetest version
```
pick your fighter
```

##### Summary
It took me 20 minutes to understand what in my code was wrong because I expected bones to use radians as objects do. Not even the docs are mentioning this.  

The soft approach is to mention it in the docs. But I honestly don't understand why we're using two different unit systems for entities. It's very confusing, it's been two days I've been working with entities and it's a pile of problems one after the other, c'mon...

##### Steps to reproduce
With Minetest Game
```lua
minetest.register_on_joinplayer(function(player)
  minetest.after(1, function()
    player:set_bone_position("Head", nil, vector.new(0, 180, 0))
    local _, b_rot = player:get_bone_position("Head")
    minetest.chat_send_all(dump(player:get_look_dir())) -- this is in radians
    minetest.chat_send_all(dump(b_rot))                 -- this is in degrees (if you put `math.pi` instead of 180 the head barely rotates, as it's only 3.14 degrees)
  end)
end
```

**Comment by rubenwardy** [comment]
I opposed this when this inconsistency was added, but was outvoted unfortunately. This is now intentional and documented behaviour

Our options are:

* Add new methods suffixed with unit (`set_rotation_deg`, `set_attach_rad` for example)
* Add new types for angles that say the unit (not sure how this would work, given there's both 2d and 3d angles here)
* Add a new transform API, deprecate all rotation methods
* Break it in 6.0.0 (this might not be the best idea as the breakage might be hard to debug)

**Comment by Zughy** [comment]
This is not a suggestion, this is clearly a bug - whether in the docs or in the code

> this is now intentional and documented behaviour

There is no mention in `set_bone_position` about the rotation being in degree

**Comment by v-rob** [comment]
I like Option 3 as well.  Failing that, though, I'd advocate for deprecation of `set_attach()` in favor of a more grammatical name like `set_attachment()`, where we could also use radians.

**Comment by Zughy** [comment]
@v-rob I think `set_parent()` would be more universal

**Comment by appgurueu** [comment]
I could switch the new methods `set_bone_override` and `get_bone_override` in https://github.com/minetest/minetest/pull/12388/ to radians. The then deprecated `set_bone_position` and `get_bone_position` would continue to operate on degrees.

**Comment by rubenwardy** [comment]
> @v-rob I think `set_parent()` would be more universal and straightforward

The problem there is being able to set and get the other attachment properties - such as boon, position, rotation, etc. It doesn't make sense for get_parent to return multiple things

**Comment by Zughy** [comment]
@appgurueu that'd be lovely!

@rubenwardy I think it's better to have people instantly understand what a function does using a universal term and then learn by themselves that they can actually do more, than to be clueless about how to get/set parents because it uses "attach"
