### ISSUE TITLE
Lua function to customize wielded hand

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1368]
Please consider adding a Lua function to allow customizing hand appearance per player. This would custom player models / skins to set an appropriate hand for the player to see in 1st person view when no item is selected. Currently it doesn't seem like wieldhand.png can be changed from Lua, which is very limiting with some mods.

**Comment by HybridDog** [comment]
```
minetest.after(0, function()
	minetest.override_item("", {
		wield_image = "wield_dummy.png^[combine:16x16:2,2=wield_dummy.png:-52,-23=character.png^[transformfy",
		wield_scale = {x=1.8,y=1,z=2.8},
	})
end)
```
wield_dummy.png is a 16x16 transparent png file

**Comment by paramat** [comment]
:+1: Essential for space mods.

**Comment by rubenwardy** [comment]
I'd like to see this.

**Comment by paramat** [comment]
#2827 merged.
