### ISSUE TITLE
Unable to uninstall a game (like mineclone5) that was removed in contentdb through "online content explorer"

### ISSUE THREAD

**Issue by amreo** [minetest/minetest#13680]
##### Minetest version
```
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"
```

##### OS / Hardware

Operating system: GNU/Linux (manjaro)
CPU: Intel i7-7700HQ (8) @ 3.800GHz

##### Summary
I cannot uninstall a game (like mineclone5) that was removed from contentdb through "online content explorer" because I cannot find it

##### Steps to reproduce
1) Install a game using "online content explorer"
2) Wait that the game's developer remove its from contentdb
3) Open "online content explorer" in minetest
4) Type the name of the installed game
5) You will not find it
I expect to be able to find the game as it is locally installed

#### Workaround
It is still possible to uninstall the game from "installed contents" .

**Comment by rubenwardy** [comment]
This is expected behaviour. If a package is removed from ContentDB, installed copies behave as if they were installed manually. You can still uninstall from the content menu

This makes this more of a UX issue. With a unified content tab / contentdb GUI, this wouldn't be an issue. See #10228
