### ISSUE TITLE
How to control nodes quantity

### ISSUE THREAD

**Issue by Ygarr** [minetest/minetest#13690]
The most common error is exceeding the number of nodes 32768
Even after removing installed mods - got this error.(may be because of dependencies)

How to know what mod (and in-game mods)adds what number of nodes
 and see total quantity of nodes before game  crashes after launch?

**Comment by Zughy** [comment]
For this kind of questions, please use the [forum](forum.minetest.net) or one of our social spaces like Matrix, IRC or Discord. Closing
