### ISSUE TITLE
Only hotbar slots 1-9 are selectable on Android.

### ISSUE THREAD

**Issue by OgelGames** [minetest/minetest#13691]
##### Minetest version

```
5.7.0 (Android)
```
##### Summary
On Android, when using a mod that allows increasing the hotbar size, only slots 1-9 can be selected, despite other slots being visible.

Originally reported in https://github.com/mt-mods/dreambuilder_hotbar/issues/3, confirmed using current version.

##### Steps to reproduce
1. Install a mod that changes the hotbar size (e.g. [`dreambuilder_hotbar`](https://github.com/mt-mods/dreambuilder_hotbar))
2. Start a world, and set the hotbar size to greater than 9 slots.
3. Try to select any hotbar slot above slot 9.

**Comment by nininik0** [comment]
Yep, that happens to me. Also if you use devtest and use the /hotbar command that would happen too
