### ISSUE TITLE
Minetest CRASHES on android if NO MOD.CONF FILE is present

### ISSUE THREAD

**Issue by nininik0** [minetest/minetest#13694]
Minetest 5.6.1 - 5.7.0 this bug started happening in 5.6.1
##### Summary -->
Whenever a mod is missing a mod.conf file minetest just crashes, minetest crashes even if it uses a depends.txt file, in debug it would say "mods not having a mod.conf file with the name is deprecated " and then it crashes, people say that that dosent happen on computers.

##### Steps to reproduce
Create any mod or download any mod and DONT ADD THE MOD.CONF FILE or remove it.
Or if it has a mod.conf file you can also add a depends.txt so that there's both of them, and if you run the mod it will crash because either: 1. No mod.conf file, 2. There's a depends.txt file, 3. There's a mod.conf file but there's also a depends.txt file.

**Comment by rubenwardy** [comment]
What's the error message / stack trace?

**Comment by nininik0** [comment]
The error message is "mods without the mod.conf file is deprecated" or "depends.txt is deprecated please use mod.conf instead"

**Comment by rubenwardy** [comment]
Please reproduce the crash and provide the last 20 lines of debug.txt. If you have adb, logcat would be helpful too in case there's an ungraceful error

Those are not errors, those are just warnings (unless you've set `deprecated_lua_api_handling = error`)

**Comment by nininik0** [comment]
Bruh ITS EASY TO REPRODUCE JUST MAKE A MOD WITH NO MOD.CONF FILE AND RUN IT WOULD THEN CRASH AND SAY NO MOD.CONF FILE IS DEPRECATED SHUTTING DOWN.
