### ISSUE TITLE
Jittery mouse movement when DPI is excessively high

### ISSUE THREAD

**Issue by meetric1** [minetest/minetest#13701]
##### Minetest version
```
5.7.0
```

Active renderer: OpenGL 4.6.0
Irrlicht device: Not shown?

##### OS / Hardware
Operating system: Windows 10
CPU: i7 4790k
GPU: GTX 970

##### Summary
- Title explains it all. Different FPS and DPIs were tested. The issue worsens over ~500 DPI. 
- Altering FPS doesn't seem to worsen/fix the problem but fyi my FPS was capped at 165 (The monitors refresh rate) and VSync was disabled.
- This issue also existed in older versions of Minecraft and was fixed in 1.13.
- Ant Venom made a (pretty long imo) video of the same issue originally found in Minecraft 1.8: [Video w/ timestamp](https://youtu.be/5v4zMOQ-sSU?t=552)

##### Steps to reproduce
- Use a software to change your mouse DPI, I used Logitech G HUB since I have a Logitech mouse. 
- Set the DPI setting to 1000 (if allowed) and play until you notice the "mouse acceleration" problem.

**Comment by HybridDog** [comment]
> Ant Venom made a (pretty long imo) video of the same issue originally found in Minecraft 1.8: Video w/ timestamp

According to that video, the problem is related to the polling rate and not DPI, and it sounds like it is caused by some mouse driver.

**Comment by Desour** [comment]
Tested on X11+Linux with SDL, with 10800 DPI. No issues.

**Comment by MisterE123** [comment]
5.9.0,
tested with a high DPI using a mouse that has a DPI adjuster button ... it *is* slightly jittery but that is because the DPI is *too* high ... I can't control the mouse accurately outside of minetest either.

So unfortunately, I can't confirm.
