### ISSUE TITLE
Files with a space in their name are not read

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13708]
##### Minetest version
```
5.7.0, latest dev
```

##### OS / Hardware

Operating system: Pop!_OS
CPU: i7

##### Summary
Title. I couldn't find anything in the documentation

##### Steps to reproduce
1. Download the zip file (CC0)
2. put the audio in the sounds folder and the image in the textures folder
3. 
```lua
minetest.register_on_joinplayer(function(player)
	minetest.after(1, function()
		minetest.sound_play("boing", { to_player = player:get_player_name()}) -- works. Now rename it in "bo ing.ogg" and use the other line
		--minetest.sound_play("bo ing", { to_player = player:get_player_name()})
	end)
end)

minetest.register_tool("test:item", {
  description = "Test item",
  inventory_image = "te st.png", -- can't find the texture
  groups = {oddly_breakable_by_hand = "2"}
})
```

[boing.zip](https://github.com/minetest/minetest/files/12223014/boing.zip)

**Comment by sfan5** [comment]
working as designed: https://github.com/minetest/minetest/blob/28fce8aad58a10b45248c5dbc4ce8b0a534740a2/src/network/networkprotocol.h#L245

**Comment by Zughy** [comment]
And how are people supposed to know?

**Comment by sfan5** [comment]
Obviously this should be documented if it isn't.
The server also logs a message but it isn't even visible without `--verbose`:
https://github.com/minetest/minetest/blob/28fce8aad58a10b45248c5dbc4ce8b0a534740a2/src/server.cpp#L2516-L2518
We should change this to warningstream.
