### ISSUE TITLE
Broken wielded item loaded behind the character

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest#13710]
##### Minetest version
```
5.7.0
```

Active renderer: none, I disabled any filter to improve smoothness
Irrlicht device: I don't see it

##### OS / Hardware
Operating system: Zorin OS Core
CPU: AMD® V140

GPU model: AMD® Rs880
OpenGL version: 3.0

##### Summary
After dying and wearing the same armor I was wearing before dying I saw a broken stone sword loaded behind my armor.
![Schermata da 2023-05-31 17-57-03](https://github.com/minetest/minetest/assets/123581658/4d3d91cf-04f6-449b-957c-108aeb832cf1)

##### Steps to reproduce
Enable 3D Armor and Wielded Items > craft and wear an armor > craft and hold something > die > catch and wear the same armor again > hope to see it. In my case happened only once, not sure if happens really often. Also, I'm not sure if it depends completely on one of those 2 mods, can depend on Minetest texture loading code or whatever it is, this is mainly why I reported it here.

**Comment by sfan5** [comment]
This needs further investigation and ideally a minimal reproducer to make sure it's not just a plain mod bug.

**Comment by PavanLuca** [comment]
Well, alright, I think that someday I may be able to reproduce it and report back, as I said I'm uncertain either if it's really common 🤷.

**Comment by PavanLuca** [comment]
Yeah, probably it's a mod bug, I tested again and it doesn't happen necessarily when dying, on my offline world in that session I never died, I just returned the day after and once the world loaded I saw the broken sword on his back so the issue happens even with a simple world loading.

**Comment by PavanLuca** [comment]
Yeah, probably it's a mod bug, I tested again and it doesn't happen necessarily when dying, on my offline world in that session I never died, I just returned the day after and once the world loaded I saw the broken sword on his back so the issue happens even with a simple world loading.
![Schermata da 2023-12-24 14-30-23](https://github.com/minetest/minetest/assets/123581658/8fc60259-153f-4b95-985e-c555c302be48)
![Schermata da 2023-12-24 15-56-32](https://github.com/minetest/minetest/assets/123581658/8b4fcb78-6e81-4bb0-9f2c-9d0cdd0b5500)
