### ISSUE TITLE
add a github wiki for adhoc documentation of features.

### ISSUE THREAD

**Issue by FatalError42O** [minetest/minetest#13738]
## Problem

I'm frustrated every time I have to go looking in lua_api.txt. There's no structure, organization, or _sanity_ to any of it. It's infuriating for new users- and it's terrible practice to keep all documentation in one place. The Minetest wiki has always been poorly documented, and it's really not the style of documentation we need.

## Solutions

We can layout the Github wiki like a tree, and Github wiki allows us to do this very easily. But more importantly it allows us to link relevant information instead of just having users ctrl+f through 100s of results, and hope they actually find something.

it can be set up something like this for example. Where <> triangle brackets are links, and square brackets are pages.
```
[entities]

    for player only methods see: <player only>
 
    methods:
    get_pos() 
        *gets the position of an object, see: <vectors> (link here)
    set_pos(<vectors>)
        *sets the position of the player, see: <vectors> (link here)

[player only]
    set_hud(<hud definition>)
          *adds a HUD element

[hud definition]
       blah blah blah, see <hud element types>
[hud element types]
       talk about element types here
[particles]
       add_particle(<particle definition>)
            *blah blah blah important info
       add_particlespawner(<particle spawner definition>)
           *more important information and stuff
```
in lua_api.txt, there are three separate locations that the information needed to make a HUD element is located, all thousands of lines away from each other. It is GENUINELY the worst documentation I have ever seen an Engine or otherwise game use. It's time to stop continuing this- I would be more then happy personally to contribute to a github wiki, and I'm sure there's dozens of others who would like to. It may take a while, but I'm confident this will work far better then the current system 

Obviously the massive advantage of all of this is that we can LINK things, instead of giving a vague, likely unofficial or phrase to describe the parameters (see add_particlespawner in lua_api.txt, for example, or really any other function). As mentioned prior, this is very frustrating to modders who want actual answers and don't want to cycle through 100s of results for ctrl+f. 

Better documentation is important to the growth and hopefully the continued existence of this community. We're going to have to make changes if we want MT to survive.

**Comment by sfan5** [comment]
I agree that the documentation has to be immensely improved and restructured but adding yet another place where partial documentation is presented in an incomplete, different fashion.
We already had Lua API documentation on dev.minetest.net but that didn't work out well.
