### ISSUE TITLE
Input not working properly on Android

### ISSUE THREAD

**Issue by Nomagno** [minetest/minetest#13743]
##### Minetest version

```
Commit 7b3ed32 (master branch)
```

Active renderer:
Irrlicht device: ANDROID

##### OS / Hardware

Operating system: Android 12, AOSP on Xiaomi Redmi 9

GPU model:
OpenGL version:

##### Summary

The joystick and camera works, the hotbar too, the UI too, but the three dots, jump, shift, cog wheel, and Aux1 buttons do not work. Changing touch threshold settings and setting fixed virtual joystick doesn't help.
##### Steps to reproduce

Start world, try to play

**Comment by Desour** [comment]
Did it work in 5.7?
If yes, can you bisect?
These buttons were recently changed a little recently. <https://github.com/minetest/minetest/commit/14441a289e871824f05d29e4eff2af78a923239a> was before these changes.

**Comment by Nomagno** [comment]
It works with a CI build from 6-7 days ago, yes

**Comment by grorp** [comment]
Tested, confirmed. First bad commit is f7f3aaf43c88179bafd255f3c67275f316cff91a.
