### ISSUE TITLE
Checking the user condition when dropping an item from a node.

### ISSUE THREAD

**Issue by CandyFiend** [minetest/minetest#13740]
## Problem

The question concerns the minetest drop tables. I have a node that should store information about whether it is installed by a player or not. And depending on this, you need to choose a drop from this block. I know two ways to track the installation of the node by the player, param2 as in the original minetest game and meta is_placed bool.

An obvious way to make two nodes and generate a "technical variant" in the world with a special drop.
Is there a way to do a meta or param2 check to select a drop or reset the chance?

## Solutions

```
drop.items[x].condition = function(node, pos, player) [check condition, return true/false] end

drop = {
     max_items = 1,
     items = {
         {
             rarity = 1000,
             items = {"default:diamond"},
             condition = function (pos, node, player)
                 -- checking the condition
                 return true/false
             end
         },
     }
 }
```

I.e. when dropping an item, the drop condition of the item is calculated first and if it is met, the chance (rarity) is calculated. Will this calculation of the condition for each item in the drop be too slow?

## Alternatives

I have no idea how it can be done in another way. Perhaps you have better suggestions.

## Additional context

I do not know what arguments would be useful to this function, but I have several use cases:

1. Inventory check, equipped items, for example, an amulet for good luck.
2. Checking the node metadata.
3. Checking the entity, who exactly broke the node. For example, a drilling minecart or a player.  It is possible to check the presence of an entity in a radius, not far from the node.

I don't know the api and engine performance issues very well. If it's not difficult for you, explain to me the things related to this request that I don't understand.

Is it possible to add the ability to calculate the maximum number of items (max_items) in the same way? A function that performs the necessary checks and returns a positive integer.

**Comment by tenplus1** [comment]
Usually an external drop table is used and a check for a specific mod or node use there before adding the item e.g.
```
local droptable = {wheat}
if minetest.get_modpath("nether"} then
table.insert(droptable, {netherrack})
end
minetest.register_node("mynode", { drops = droptable })

**Comment by CandyFiend** [comment]
Read again and carefully.  I'm asking about something else.  Specifically, in my case, I need to check the metatable or param2 to decide if the first item in the drop table will be dropped.  If the condition function returns false, then the second item from the drop table will be checked.  This is not related to checking if the item is in the game.  This has to do with how the player has manipulated the node and what metadata the game has added to the node.  I wrote examples of use cases above.  If it's not clear, here's another one: The player came up with a magic book and enchanted the stone, the game recorded in the metadata of the node that it was enchanted.  In the drop table, the first item is a diamond, but in order for it to drop, the condition function checks the node's metadata to see if it has been enchanted.  Another option: The game checks if the player has a special helmet that adds an extra drop to the grass blocks.  And if it doesn't exist, the function returns false and the next item in the table starts to be checked.  if the condition is met and the function returns true, then the game will calculate the chance (rarity) whether the item fell out or not.  Like in terraria, seeds only drop if the player has a blowpipe.

I am asking for this feature to be added.  Or tell me how can I achieve this behavior if there are other ways.  If it is not possible to add this functionality, write a reason.

**Comment by CandyFiend** [comment]
I clarify, there is already a check of the tool with which the object was dug up.  The item drops only if it was dug with the right tool.  I suggest instead of adding a bunch of such conditions for all "occasions", add the ability for modders to write their own check function, which will check inventory items, metadata, entities, etc.

**Comment by tenplus1** [comment]
How about this:
```
minetest.register_node("test:block", {
	description = "Test Block",
	tiles = {"default_wood.png"},
	groups = {crumbly = 3},
	drops = {},
	preserve_metadata = function(pos, oldnode, oldmeta, drops)

		if oldmeta.enchanted then
			minetest.add_item(pos, {name = "default:diamond"})
		else
			minetest.add_item(pos, {name = "default:coal_lump"})
		end
	end
})
```

**Comment by CandyFiend** [comment]
Very similar to what I asked. I will definitely try this solution later. I'm very busy in the next few days.
This function, when checking a broken node, will spawn an object in the world in place of the block. But if I understand correctly, this is not exactly a drop, because the drop table is not used. In the minetest game, this would look strange if you consider that all dropped items are picked up in the inventory without dropping into the world.
And there is also no way to check the entity that broke the block.

Can you still think about adding a separate custom function for checking the drop condition of each item in the drop table?

**Comment by Desour** [comment]
There's `minetest.get_node_drops(node, toolname)` which you could override. The digger could maybe be stored in a static variable in another callback. But that's super hacky of course.

Is there actually a reason why we wouldn't want to allow `drop = function(...)` or the api suggested here? (I don't know any.)

**Comment by CandyFiend** [comment]
I tried to find a drop handler function that should return a list of items based on the drop table. I could redefine it and write different ways to handle my custom drop table parameters that I could define for each node. I could add both additional attributes to each item, such as an existing tool check, and handle additional calls to my functions designed for anything, including condition checks. So far I haven't found anything similar, maybe you can tell me.

There is also an option to intercept the table of dropped items before dropping them and adjust it manually, but it looks like hacking. If this is possible, please tell me the name of the function.

I may have seen something similar in the definition of the tool, but then this logic will be tied directly to the tool itself, not the node.

**Comment by CandyFiend** [comment]
> There's `minetest.get_node_drops(node, toolname)` which you could override. The digger could maybe be stored in a static variable in another callback. But that's super hacky of course.
> 
> Is there actually a reason why we wouldn't want to allow `drop = function(...)` or the api suggested here? (I don't know any.)

I was thinking about using this feature. Do I understand correctly that this is the same function with which I can get into the drop table through the "node" argument, rewrite the compilation of the list of items that will drop from the node, and add calls to my custom check functions from the drop table? If yes, then it remains only to add the digger argument (the block or entity that broke the node).
There is no example of a standard implementation in the documentation, but I'll look for it later. It would be much easier to see right away than to write my assumptions, but there is no time yet.

**Comment by Desour** [comment]
There is no drop callback function (yet), if that's what you asked.

----

Thinking of it, we probably can't add this feature as long as `core.get_node_drops` is used, as item drop mods would break.
It's weird that `get_node_drops` only takes node and toolname. Maybe we should deprecate that function, or add new params to it and deprecate the current signature, and replace it with a function that takes a digger, nodepos, and tool itemstack. Then we can later add a drop callback (which then only works if the server has no mods that use the deprecated function).

**Comment by CandyFiend** [comment]
Maybe I don't have enough api knowledge, but if through nodepos I can somehow get the definition of a broken node (oldnode -> get_definition() and oldmeta), then that would be great.
In my understanding, drop callback is a function that takes droptable as an argument, calculates the probabilities of dropping items (dropped or not), compiles a table of items and their number and returns somewhere, most likely in minetest.handle_node_drops(pos, drops, digger). 

Next, I will describe my vision of this function:
In this function, it should be possible to redefine the mechanism for compiling a list of dropable items, add custom processing of additional attributes (fields) to the droptable, including function calls. The function must accept such arguments so that it is possible to access the digger, regardless of whether it is a node or an entity. Get access to the coordinates of the node, its metadata and possibly its definition. Well, it is possible to check the environment around the node, for example, the presence of other nodes and entities, but it seems to me that there are enough coordinates for this. I think such a mechanism would solve all possible issues related to the customization of the drop. Well, the standard implementation of this function should just match the current mechanics.
