### ISSUE TITLE
GUI : Blank space when resizing the window

### ISSUE THREAD

**Issue by YoYomec** [minetest/minetest#13749]
##### Minetest version

```
5.7.0
```
(look at the right)
![image](https://github.com/minetest/minetest/assets/98414804/318abca0-f05c-4bb3-b9cf-d0bccaafc288)

**Comment by Zughy** [comment]
Please follow the provided template when opening the issue. We can't help you without knowing specs like your GPU, CPU and OS. Closing as invalid, please reopen another with the required information
