### ISSUE TITLE
Client restart required to disable inventory item animations

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#13754]
Minetest 5.7.0, confirmed on Ubuntu and Windows

After disabling inventory item animations, animations are still enabled until the client is closed and restarted.

**Comment by srifqi** [comment]
**Both** enabling and disabling inventory items animations require restart if the change/toggle happened _after_ the first play/run.

I am not sure about thread-safety for this, but this might be a fix:
```diff
diff --git a/src/client/hud.cpp b/src/client/hud.cpp
index d23b96e5b..9fba547ef 100644
--- a/src/client/hud.cpp
+++ b/src/client/hud.cpp
@@ -1027,8 +1027,7 @@ void drawItemStack(
 		return;
 	}
 
-	const static thread_local bool enable_animations =
-		g_settings->getBool("inventory_items_animations");
+	const bool enable_animations = g_settings->getBool("inventory_items_animations");
 
 	auto *idef = client->idef();
 	const ItemDefinition &def = item.getDefinition(idef);
```

**Comment by Montandalar** [comment]
This bug affects [Colorlandia](https://content.minetest.net/packages/dibesfer/colorlandia/) noticeably since the game overrides the setting with its game-specific `minetest.conf`. The effect can carry over into other games like MTG after playing Colorlandia first.
