### ISSUE TITLE
Graphical Glitches on Nodes

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#13765]
### Minetest version

```true
5.7 and 5.8 dev
```

### Active renderer

OpenGL 4.6

### Irrlicht device

X11

### Operating system and version

Ubuntu 22.04

### CPU model

AMD Ryzen 5 4600G

### GPU model

AMD Renoir (built-in)

### OpenGL version

4.6

### Summary

It seems that in Minetest 5.7 and 5.8 dev that certain nodes do not rotate or overlay textures properly resulting in graphical glitches.

### Steps to reproduce

In this example 4x trapdoors were placed in each of the 4 directions and opened, notice the black line on top where the texture is not rotated to match the door.  Also in the background grass blocks using dirt and grass overlay do not appear properly (only the grass issue was fixed in 5.8 dev).
![a](https://github.com/minetest/minetest/assets/8145060/80f489f2-abc9-45d1-8358-b89cff917237)

**Comment by tenplus1** [comment]
The glitches appear with all default settings, with and without shaders enabled.  Closed trapdoors look fine.
Devtest has no nodes that require specific side textures to work so I had to add a node to show this using the following code:
```
minetest.register_node("dtest:trapdoor", {

	groups = {choppy = 2, oddly_breakable_by_hand = 2},

	drawtype = "nodebox",
	paramtype = "light",
	paramtype2 = "facedir",
	use_texture_alpha = "clip",
	is_ground_content = false,

	node_box = {
		type = "fixed",
		fixed = {-0.5, -0.5, 6/16, 0.5, 0.5, 0.5}
	},

	selection_box = {
		type = "fixed",
		fixed = {-0.5, -0.5, 6/16, 0.5, 0.5, 0.5}
	},

	tiles = {
		"doors_trapdoor_side.png",
		"doors_trapdoor_side.png" .. "^[transform2",
		"doors_trapdoor_side.png" .. "^[transform3",
		"doors_trapdoor_side.png" .. "^[transform1",
		"doors_trapdoor.png" .. "^[transform46",
		"doors_trapdoor.png" .. "^[transform6"
	}
})
```
... and this was the result:
![a](https://github.com/minetest/minetest/assets/8145060/fe30ad6a-f8f1-4e29-abd9-7636a71948fe)

**Comment by tenplus1** [comment]
@Desour, I tried running Minetest with both those command options and the black stripe still appears.

I do not compile Minetest but download from minetest.net 5.7 stable for debian, or launchpad for the daily 5.8dev builds.

**Comment by Zughy** [comment]
@Desour thoughts on this? I can't reproduce it either (Pop!_OS, 5.7 and 5.8 dev, i7, NVIDIA GeForce GTX 1060)

@tenplus1 can you bisect as requested by Desour if the problem wasn't there before 5.7?

**Comment by Desour** [comment]
>@Desour thoughts on this?

Still can't reproduce. And nobody else reported this either. `¯\_(ツ)_/¯`

**Comment by NathanSalapat** [comment]
I just tried in 5.7.0 and a recent dev build, as of this morning, I don't see this happening either.

**Comment by Zughy** [comment]
Labeling it as a possible close, since it looks like it's an issue with OP settings (OS, libraries etc) rather than a MT one

**Comment by tenplus1** [comment]
I know this issue is closed, but I found out WHY I was having graphical glitches like the above in my game on 5.7, 5.8 and 5.8dev clients.

The Settings -> Advanced -> Advanced -> World-aligned textures mode was defaulted to 'force_solid' which gave black glitches and wouldnt allow me to rotate one-textured nodes properly, by setting this to 'enable' it fixed the issues.
