### ISSUE TITLE
Entity punching issues

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1376]
Playing around with the the SimpleMobs mod helped me notice some serious problems with the current damage system. When the player punches a mob, that mob will only flash and take damage once. Even if you keep aiming at it and punching, or let go of the left mouse button then press it again, no more damage is dealt from that point on. The only way to deal another blow appears to be looking away from the mob (turning around some 90*) then looking back so the selection box re-appears.

I've read somewhere that Minetest wanted to go for a more original damage system, such as the player having to release the left mouse button and press it again. That doesn't sound like a bad idea, but I really hope that having to look away from the mob and back at it again is a bug, since the current system makes fighting virtually broken. With SimpleMobs, I get killed instantly and fighting is outright impossible, unless I have a sword that kills from the first strike.

If it's a bug, it's hopefully nothing complex and can be fixed. If this is intended, please at least add a setting to disable having to look away from mobs to reset damage! In my game, I'd like to enable constant damage too, so that looking at a mob and holding the attack button down deals damage every 1 second. I'd be grateful if Minetest could allow this and not force the current damage system onto all games and servers even if it stays default.

**Comment by raymoo** [comment]
Is this related to how punches are prorated based on time since last punch? E.g. If you punch someone 0.5 seconds since the last time you did, you will only do half damage (which would round to 0, at default armor values).

**Comment by paramat** [comment]
> When the player punches a mob, that mob will only flash and take damage once. Even if you keep aiming at it and punching, or let go of the left mouse button then press it again, no more damage is dealt from that point on. The only way to deal another blow appears to be looking away from the mob (turning around some 90*) then looking back so the selection box re-appears.

I doubt this is still occuring, if it is a new issue will be opened. Author not responding.
