### ISSUE TITLE
Keypad input doubles as digit input

### ISSUE THREAD

**Issue by masoudd** [minetest/minetest#13770]
### Minetest version

```true
Minetest 5.7.0 (Windows)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Windows 10

### OpenGL version

4.6.0

### Summary

I am left handed, when changing binds for WASD to Keypad: 5123, trying to move changes the active item to the corresponding number too

### Steps to reproduce

change the binding for W to Keypad5, try to move forward in a game, active item changes to 5 as well.

**Comment by grorp** [comment]
You'll have to rebind the hotbar keys to avoid that.

Although you can't rebind the hotbar keys in the "Change Keys" dialog, you can rebind them in `minetest.conf` using these settings:

https://github.com/minetest/minetest/blob/0cbf96cc839e1b8202ad782420c9b50fa14ad052/minetest.conf.example#L3403-L3451

Issue for making the hotbar keys re-bindable using the "Change Keys" dialog: #11209

**Comment by rubenwardy** [comment]
@grorp I suspect you misread, the user doesn't want to change their hotbar bindings. The user is trying to bind WASD to the keypad but pressing the numpad keys moves the hotbar too. So the input code isn't distinguishing between numbers row and the numpad

**Comment by rubenwardy** [comment]
@masoudd please may you provide the minetest.conf so we can check what the keys have been bound to

**Comment by masoudd** [comment]
@rubenwardy Of course:
[minetest.conf](https://github.com/minetest/minetest/files/12480711/minetest.conf.txt)

**Comment by savilli** [comment]
When Irrlicht produces an `EET_KEY_INPUT_EVENT` for numpad keys, it sets `KeyInput.Char` to the according digit. For example, for numpad key 1 `KeyInput.Key` would be 97 (KEY_NUMPAD1), and `KeyInput.Char` would be 49 ('1').
Unfortunately, when minetest checks if a key is pressed, equal `Char` is enough to trigger the event.
https://github.com/minetest/minetest/blob/f080aa29b57db124643c0cab5a3fac129f2c5f7c/src/client/inputhandler.h#L134
https://github.com/minetest/minetest/blob/f080aa29b57db124643c0cab5a3fac129f2c5f7c/src/client/keycode.h#L39-L42

**Comment by SmallJoker** [comment]
@masoudd When using Minetest 5.7.0 (before the fix), might it also be an option for you to have NumLock turned off? This way, you could assign the arrow keys on the numblock to control your character.

I am asking this because text fields (also such of other applications) treat the numblock keys according to the NumLock state to double the normal keys in functionality.

**Comment by masoudd** [comment]
> @masoudd When using Minetest 5.7.0 (before the fix), might it also be an option for you to have NumLock turned off? This way, you could assign the arrow keys on the numblock to control your character.
> 
> I am asking this because text fields (also such of other applications) treat the numblock keys according to the NumLock state to double the normal keys in functionality.

The arrow keys on numlock are not in wasd position. It is possible to use it but It'll be hard to get used to. I'm used to numlock 5123 as wasd replacement. It is possible to turn numlock off and use the numlock off equivalent of 5123 keys. The only downside to doing that would be 1 is "End" and 3 is "Page Down" and I prefer to use these two keys as other utility keys since their dedicated keys are close to numpad and I can't use the regular 1 to 9 number row keys that is above the qwerty keys. I hope that made sense.
