### ISSUE TITLE
cmake incompatablity error

### ISSUE THREAD

**Issue by espero-dev** [minetest/minetest#13776]
### Minetest version

```true
https://github.com/minetest/minetest/commit/72ed8514c5d68392eea45768ff2366010c1ca32e
```

### Active renderer

idk

### Irrlicht device

idk

### Operating system and version

windows 10 dev

### CPU model

amd ryzen 5

### GPU model

amd radeon

### OpenGL version

idk

### Summary

cmake .
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19045.
-- *** Will build version 5.7.0 ***
-- Using user-provided IrrlichtMt at subdirectory 'lib/irrlichtmt'
-- *** Building IrrlichtMt 1.9.0.12 ***
-- Performing Test REVISION_SANITY_CHECK
-- Performing Test REVISION_SANITY_CHECK - Success
-- Device: WINDOWS
-- OpenGL: ON
-- OpenGL 3: OFF
-- OpenGL ES: OFF
-- OpenGL ES 2: OFF
-- EGL: OFF
-- WebGL: OFF
CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindZLIB.cmake:199 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  lib/irrlichtmt/source/Irrlicht/CMakeLists.txt:260 (find_package)

-- Configuring incomplete, errors occurred!

### Steps to reproduce

cmake .

**Comment by rubenwardy** [comment]
You need to install zlib. See https://github.com/minetest/minetest/blob/master/doc/compiling/linux.md#dependencies

**Comment by SmallJoker** [comment]
I would recommend you to use `vcpkg` to manage your dependencies. You can find a list of packages and instructions here: https://github.com/minetest/minetest/blob/master/doc/compiling/windows.md

FWIW: If you want to go the manual, hard route: This what I used before vcpkg was introduced to compile 32-bit Minetest on Windows XP using MSVC 2023: https://krock-works.uk.to/minetest/Compile_Minetest_MSVC.txt . The instructions should still be somewhat up-to-date except that you would need to specify the x64 compiling target for 64-bit applications.
