### ISSUE TITLE
Contuniation of DirectX 9 support in favor of RTX Remix

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [minetest/minetest#13786]
### Problem

Minetest used to have a DirectX 9 renderer which didn't have shader support. Later builds removed it entirely since it had no benefits over OGL.

As you might have heard of, NVIDIA launched the now open sourced RTX Remix Runtime, which swaps the renderer with path tracing and allows modders to swap old assets with high quality PBR materials and complex meshes without the limitations of old game engines.

With the launch of Portal RTX, a community quickly emerged and began testing games form the dx8-dx9 era.
RTX Remix requires fixed function pipeline to work, although early vertex shaders are supported, they are often problematic.
Minetest's dx9 renderer had no shaders as far as I know, which I thought a perfect opportunity to see if it works.

And it does work indeed! Although it has some issues, Minetest is open source and under active development which I hope will make fixing those much easier.

We have a [Discord](https://discord.gg/erUFKwkQ) and some of the RTX Remix developers are here too. For more detailed and accurate information please ask them :)

### Solutions

Restore the DirectX 9 renderer with fixed function pipeline, no shaders.

### Additional context

Here are the some screenshots I took. I am on [0.4.11-dev20150212](https://discord.com/channels/1028444667789967381/1147888305833246782/1147888305833246782) which is the last build with the dx9 renderer I am aware of.
![resim](https://github.com/minetest/minetest/assets/84380947/b086078a-f248-4b50-af5a-024405681bf3)
Here I replaced some of the original textures with ones from the [Vanilla RTX](https://github.com/CubeIR/Vanilla-RTX) resource pack for Minecraft RTX. The [license](https://github.com/CubeIR/Vanilla-RTX/blob/master/LICENSE.txt)
![resim](https://github.com/minetest/minetest/assets/84380947/e6dda9cd-508f-432c-9fc7-ea60fd5200fc)

Realistic translucent water with physically accurate reflection & refractions:
![resim](https://github.com/minetest/minetest/assets/84380947/ac7a187d-54db-437e-a53a-01090a19614f)

Without any modifications:
![resim](https://github.com/minetest/minetest/assets/84380947/621170d2-a118-45a8-a70b-a5760092f6bb)

**Comment by Kamilkampfwagen-II** [comment]
Can you please issue what aspect you didn't like about this?

**Comment by SmallJoker** [comment]
This is a decent result considering Minetest was not changed at all. However, DirectX depends on Windows and would need its own shader implementation for the other features Minetest got in the meantime (e.g. bloom and auto-exposure). It is more beneficial to maintain OpenGL that works on all major platforms (Android with the ES subset). After years most clients are (to my knowledge) still only using OpenGL 2.x features, with OpenGL 3.x support being rather new (see minetest/irrlicht repo).

**Comment by anchorlightforge** [comment]
Hey there, I'm not too familiar with Minetest but I'm checking in from the Remix community to hopefully clarify what exactly is necessary for such a port.  I have to say the initial Minetest screenshots we saw were pretty cool, and it shows a lot of promise.

> DirectX depends on Windows and would need its own shader implementation for the other features Minetest got in the meantime (e.g. bloom and auto-exposure).

With Remix features like bloom are not only unnecessary, but actually interfere with Remix.  It takes the rendering data and uses this info to essentially rebuild the scene in Nvidia's in-house renderer, and this renderer has its own post-processing stack already on the Vulkan end of things (the Remix project is primarily based on DXVK).

I'm currently investigating the possibility of a similar port for ioQuake3-bgfx, and it's in a similar place.  It sounds like the best course of action for restoring DX9 (exclusively for the purpose of Remix as it doesn't serve much purposes outside of that use case) would be a fork that merges the DX9 renderer from this version into the modern source code with all its technical improvements.  Additional graphical features probably won't be necessary, but I'm not familiar with Minetest and if shaders were used to solve any specific rendering issues.

**Comment by Kamilkampfwagen-II** [comment]
> This is a decent result considering Minetest was not changed at all. However, DirectX depends on Windows and would need its own shader implementation for the other features Minetest got in the meantime (e.g. bloom and auto-exposure). It is more beneficial to maintain OpenGL that works on all major platforms (Android with the ES subset). After years most clients are (to my knowledge) still only using OpenGL 2.x features, with OpenGL 3.x support being rather new (see minetest/irrlicht repo).

As [anchorlightforge](https://github.com/anchorlightforge) stated, such shader effects aren't necessary, in fact they will prevent remix from functioning anyway. As I stated in the first comment, remix requires a fixed function pipeline. Remix already has its own implementation of bloom, auto exposure and other postfx.

**Comment by sfan5** [comment]
While the results sure look nice, bringing back D3D9 would impose severe technical debt.

It's not a matter of adding back the old code (even though that would still mostly work at this stage). There have been bugs in the past that were specific to D3D and we would then need resources to address them.

In addition to that it has already been decided that new features can require shaders in the future, including removal of the fixed pipeline. We're not in a great spot graphics-wise, the renderer is old and needs to be rewritten to accommodate modern hardware (partially done as noted by @SmallJoker). And we don't have anyone actively working on this currently.
If any prospective graphics dev looks at Minetest and we tell them that everything they do has to work on D3D9 without shaders they will laugh in our face and leave.

Really, this is entirely out of question.

**Comment by anchorlightforge** [comment]
I'm honestly inclined to agree with this.  This seems like something to maintain outside of the official repository as a fork, as opposed to encouraging the maintainers to support an inhibiting legacy feature.
