### ISSUE TITLE
Ability to use item preview images as textures

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1378]
Minetest generates preview images for all items depending on their drawtype, such as an image of the furnace as a cube with its faces textured accordingly. Currently this is only used to show the item on the hotbar and in inventories. The ability to also use generated image previews as textures would be very useful for modding.

One thing this would make possible are 2D representations of the wielded item in player's hands, for mods such as stu's 3D-Armor. Currently, using a Lua entity with the real drawtype and texture of the item doesn't work, since apparently there are issues with attaching things to bones due to Irrlicht. Being able to use the inventory preview as an image in this case would be extremely helpful.

Another thing this would allow are picture frames that you can put items on, similar to those Minecraft recently added. A photo frame can be placed on a wall, then right-clicking it with any item in your hand causes the photo to turn into the inventory preview of that item. Disclaimer: This isn't intended as an instigation at copying Minecraft!

**Comment by paramat** [comment]
Item visuals are no longer generated.
