### ISSUE TITLE
Ability to pass LuaVoxelManip into `minetest.spawn_tree()` as 3rd arg.

### ISSUE THREAD

**Issue by alek13** [minetest/minetest#13788]
### Problem

As for now its not possible to use `minetest.spawn_tree()` inside the `minetest.register_on_generated()`.
Also see #2151 .

### Solutions

Lets just add 3rd param into `minetest.spawn_tree()` and pass the LuaVoxelManip.
In this case `spawn_tree()` will not instantiate new VM and will use passed one.

### Alternatives

Not sure in performance of this.
Maybe its better to declare this function on lua-side.
Or similar function.

**Comment by sfan5** [comment]
I support this and it should be easy to implement IIRC, but what prevents you from using spawn_tree inside register_on_generated? It should work just fine.

**Comment by alek13** [comment]
@sfan5 
> what prevents you from using spawn_tree inside register_on_generated?
performance.
Sorry, I'm not tested this yet, but I'm almost sure, that it will be slow.
Because `minetest.spawn_tree()` instantiate new `MMVManip`, dispatch evrnts, ..., save (Maybe I'm wrong).
And I'm not sure how it will be resolved/merged changes from LuaVoxelManip (created in `register_on_generated()`) and changes from MMVManip (created in cpp `spawn_tree()`)
Also it's switch context from Lua to C++.

> it should be easy to implement IIRC
if you don't pay attention to the cost of context switching, yes.
I think it's the ~ same cost: "context switching" and "L-Tree in Lua"

**Comment by sfan5** [comment]
> Because `minetest.spawn_tree()` instantiate new `MMVManip`, dispatch evrnts, ..., save

You are overestimating the overhead. Events are also not dispatched during `register_on_generated`.

> how it will be resolved/merged changes from LuaVoxelManip

The changes won't show up in there unless you call `read_from_map` again.

> Also it's switch context from Lua to C++.

That has to happen anyway.
