### ISSUE TITLE
Migration path once MTG is no longer preinstalled

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#13800]
What happens when the user upgrades Minetest? minetest_game will disappear and they suddenly won't see any of their worlds anymore. (\*)
We need an obvious UI flow with as few steps as possible to allow the user to download MTG so they can get back to their worlds.

(\*): Dropping the user into CDB is not sufficient, some people might not even know that they need to download something called Minetest Game to continue playing "the game that was always there".

_Originally posted by @sfan5 in https://github.com/minetest/minetest/issues/13550#issuecomment-1606999343_

**Comment by rollerozxa** [comment]
My suggestion, from the same comment thread:

> For migrating from a system-wide MTG to the CDB version, would it be fine to do something like this:
> - Check some temporary setting `has_notified_about_mtg`, when it's false check if there's any worlds that use MTG
> - If haven't been notified and there's MTG worlds, display a dialog "Minetest Game is no longer bundled with Minetest. If you would like to continue playing Minetest Game, it can be downloaded in the content browser [Go to content browser] [Dismiss]"
> - Either button on the dialog sets `has_notified_about_mtg` to true
>
> New installations won't come with any worlds, and as such won't show the dialog, so it will only come up for players upgrading.

**Comment by Lazerbeak12345** [comment]
Why drop them to the browser? Shouldn't it be in the content tab under games? Navigating there shouldn't be hard (though it might be - haven't seen the code).

**Comment by sfan5** [comment]
By "drop the user into CDB" I meant the in-game menu, not the browser.
