### ISSUE TITLE
Buildbot script download binary libraries for unclear reasons

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13810]
### Minetest version

```true
HEAD
```

### Operating system and version

Windows (32-bit)

### Summary

I noticed that a build shell script downloads library binaries from this host: minetest.kitsunemimi.pw

It is not clear to me why those libraries are apparently built (?) and/or hosted by a private server.

If they are important, why are those binaries not hosted on GitHub or on minetest.net?

How exactly would one be able build those exact binaries from source code?

If this is already documented, please point to where that is the case.

### Steps to reproduce

Look at this: https://github.com/minetest/minetest/blob/2479d51cc665f8b29b919ad3158444d032840b82/util/buildbot/buildwin32.sh#L41

**Comment by sfan5** [comment]
These "unclear reasons" are:
* re-building these every time would be a waste
* github pages is not intended for bulk file hosting
* a bit of historical reasons

> How exactly would one be able build those exact binaries from source code?

My build scripts for these can be found [here](https://github.com/sfan5/mingw-pkgs), I think the link has been mentioned in some commit.
