### ISSUE TITLE
Adding minetest.spawn_falling_node(pos) in on_construct spawns an entity that never finishes falling

### ISSUE THREAD

**Issue by kromka-chleba** [minetest/minetest#13821]
### Minetest version

```true
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
```

### Operating system and version

Guix System commit: 0c1aa354048f82023e6d2043bfecc4fd58bc9b58

### Summary

Doing this:

```
on_construct = function (pos)
    minetest.spawn_falling_node(pos)
end,
```

for a node causes Minetest to spawn a falling node entity (as expected), but the entity then hits the ground and never places a node.
Looks like it runs on_step even after running self.object:remove() and the entity can't be removed.
It also causes ugly lags when the world gets restarted.
This happens for all nodes, they don't have to be in the `falling` group.

### Steps to reproduce

As above:

Make a node with this in the node definition:

```
on_construct = function (pos)
    minetest.spawn_falling_node(pos)
end,
```

place the node somewhere high and enjoy!

**Comment by kromka-chleba** [comment]
After restarting the game it prints:

`
createPlayingSoundAt: out of memory
`

In a loop.

**Comment by rubenwardy** [comment]
What are you expecting to happen? Every time the node finishes falling, the callback causes it to fall again

**Comment by rubenwardy** [comment]
Perhaps you only meant to run this callback when a _player_ (or npc) places a node. In which, you want `after_place_node`:

```lua
after_place_node = function(pos)
    minetest.spawn_falling_node(pos)
end,
```

**Comment by kromka-chleba** [comment]
>What are you expecting to happen? Every time the node finishes falling, the callback causes it to fall again

Right, I discovered this bug late at night yesterday and overlooked this.

Looks like this works just fine:

```
after_place_node = function (pos)
     minetest.spawn_falling_node(pos)
end,
```
