### ISSUE TITLE
forceload_block ... doesn't

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest#13823]
### Minetest version

```true
Minetest 5.7.0
```

### Operating system and version

Windows 11

This:
```lua
minetest.forceload_block(pos, true,-1)
```

Doesn't actually load the block in a reasonable time ... until a player looks up at the block that is to be forceloaded.

For context, the block to be forceloaded is a single position about 100 nodes above the player's head, filled with air. A very large entity needs to spawn there, and cannot until forceloaded.

### Steps to reproduce

Using the minimal_test mod included here,

join the game... 

Wait

look up...

this should spawn, but only after waiting quite a while and/or looking up: (its a very large transparent cylinder ring entity with its position 100 nodes above the player's head)
![image](https://github.com/minetest/minetest/assets/61124264/416b5ae3-31e5-4598-9414-378971bbc216)

Here's the minimal_test mod for this bug:
[minimal_test.zip](https://github.com/minetest/minetest/files/12653793/minimal_test.zip)

### IMPORTANT EDIT:

To experience the bug, you must be in Host Server mode

**Comment by MisterE123** [comment]
I'm not really sure what the extent of this bug is. Is it just bad documentation (in which case, the minetest.forceload_block is not supposed to act quickly at all - taking more than a minute or two) 

If so, why does looking at the block to load always trigger it to load, even 100 nodes away? It seems odd to be dependent on whether a player is looking at it or not

**Comment by NathanSalapat** [comment]
Unable to reproduce on Linux with Mientest 5.7.0 or 5.8.0-dev-e36b2226b
Entity seems to load instantly.

**Comment by jeremyshannon** [comment]
Yeah, it's nearly instantaneous for me on 5.7.0 on Linux, I get like one frame of blue sky when the world loads before it pops in.
 Windows problem?

**Comment by hlqkj** [comment]
> Can any Windows guys test this?

I did: I can see it instantly, as soon as I join.

Tried both in singleplayer and dedicated server, minetest version is 5.7.0 (official, not compiled by me).

**Comment by MisterE123** [comment]
Could you guys re-test with "host server" enabled?

I also just tried in singleplayer, and yes, in singleplayer it loads immediately. But in Host Server mode, as the Host Client, the bug exists. That *might* have been an important detail, sorry :P

**Comment by hlqkj** [comment]
I'm afraid I still can't reproduce it when launching the game with 'Host Server' checked from the GUI. Neither in the hosting instance, nor in a second instance I used as a second client.

**Comment by NathanSalapat** [comment]
The entity shows for me instantly when hosting a server as well. On stable and dev, tried lowering my view_range to 110 but it still worked.

**Comment by MisterE123** [comment]
Strange. I confirmed that the latest windows zip download from minetest.net has this behavior...

**Comment by debagos** [comment]
Not sure if this is related, but when I use `minetest.load_area` and then `player:send_mapblock` to force-load a big area, there are blank areas for some reason:
![screenshot_20230923_054323](https://github.com/minetest/minetest/assets/24960652/7c77b107-d26c-4875-bb24-4df56d07fa5e)
![screenshot_20230923_054336](https://github.com/minetest/minetest/assets/24960652/ab477ce9-929b-4b83-bb36-fc4e64b419bc)
It's always the same spots that are left out, so my question to you @MisterE123 is, does it happen everywhere or only in specific spots?

**Comment by Zughy** [comment]
@MisterE123

**Comment by MisterE123** [comment]
I did not notice a difference based on location. Like I said, this is repeatable for me, on a new world, in "host server" mode

**Comment by MisterE123** [comment]
Since others cannot reproduce, and since I have found a workaround, I can see closing this issue.
