### ISSUE TITLE
Server Listing Considerate Lag Spiking?

### ISSUE THREAD

**Issue by FriendlyGamer** [minetest/minetest#13831]
I was trying to pinpoint why my Default Minetest 5.7.0 game keeps on spiking lag for no apparent reasons so I done the following to believe it might has to do with the server listing failing to poll at times... 

I kept on testing until I reached these server settings (I am on a 7900 host with 4 SSDs equipped so I could speed up the server stability)

Server is based off of Texas Dallas

```
max_packets_per_iteration = 512
map_compression_level_net = 3
map_compression_level_disk = 3
max_objects_per_block = 128
sqlite_synchronous = 1
dedicated_server_step = 0.04
curl_timeout = 200 
```

Results right after a failed server listing query....
```
<ERROR> 2023-09-22 14:40:59: [CurlFetch] HTTPFetch for
servers.minetest.net/announce failed (Timeout was reached)
Issued command: /status
# Server: version: 5.7.0 | game: Minetest Game | uptime: 5min 9s | max lag:
0.277s | clients:
```
Is there anything I can do to mitigate this incredible lag spikes??

**Comment by sfan5** [comment]
HTTP requests run in a separate thread and do not influence normal server operation. You should be able to confirm that the lag spike is still present with `server_announce = false`.

> believe it might has to do with the server listing failing to poll at times...

This is happening because you have set the curl timeout to 200 milliseconds, that's way too low.
