### ISSUE TITLE
better converter support.

### ISSUE THREAD

**Issue by mrGoodWolf** [minetest/minetest#13839]
### Problem

I'm writing a  minecraft to minetest mod converter (a extremely tiring process).

### Solutions

 i was wondering if someone  implement a
function to deal with @sideonly to help I know it will be hard but I completely understand if you can't do it.coding is hard.

### Alternatives

i can of any way to do it without embedding it into lua API.

**Comment by rubenwardy** [comment]
What is sideonly? Please provide more context that doesn't require Minecraft domain knowledge

**Comment by mrGoodWolf** [comment]
The files are stripped of unnecessary code based on the @SideOnly annotation. Modders can use @SideOnly annotation to mark those things (classes, methods and/or fields) which should only be loaded on a specific side.

**Comment by rubenwardy** [comment]
That didn't really answer the question. I googled this API, and side here means "Server" or "Client". Mods in Minetest are server-side only, therefore such a feature is not needed

For the ability for mods to run client-side code, see SSCSM #10594
