### ISSUE TITLE
Add option to hide server address from pause menu

### ISSUE THREAD

**Issue by copygirl** [minetest/minetest#13853]
### Problem

When streaming Minetest, I wish to not expose the server address to the public. However, the pause menu simply shows the connection info in the "Game Info" section, and this appears to be [hardcoded in the source code](https://github.com/minetest/minetest/blob/8fa2ea71ef1191d8eda2412f733051646c8d3800/src/client/game.cpp#L4452-L4453).

Now, I'm nowhere near big enough to be worried about getting griefed, or my server owner DDoS'd, but it's just bad form to expose this information. Besides, there could always be a bigger fish who wants to play this game, but may be discouraged knowing that opening the pause / escape menu could leak sensitive information.

I'm frustrated whenever I see a game that exposes connection info, and this is a pretty bad case of that. I do have to say, as a FOSS-advocate I'm a little embarrassed. Minetest has been around for such a long time and this issue hasn't been addressed or even talked about, at least as far as I could see. Minecraft too had this issue in its infancy, but it was fixed relatively early in its development.

Additionally, the next step would be to overhaul the "Join Game" tab in the main menu, but that looks like a lot more work compared to what I'm trying to ask for here, so that should definitely get its own dedicated issue.

### Solutions

- Add an option to the settings to hide connection info in pause menu.
- (optional) Hide the connection info by default.
- (optional) Add a button to un-hide the connection info temporarily until the pause-menu is closed again.

### Alternatives

- Never click escape?
- Set up a proxy. (Not user-friendly.)
- Remove the information entirely. (suggested by [@rubenwardy](https://github.com/minetest/minetest/issues/13853#issuecomment-1739661702))

**Comment by rubenwardy** [comment]
Probably worth just removing this information from the pause menu

**Comment by NathanSalapat** [comment]
Isn't this information already public just by looking at the server list? You don't even need minetest to view the server list.

**Comment by rubenwardy** [comment]
Private servers aren't on the server list, but will have the address shown in the pause menu

**Comment by copygirl** [comment]
@NathanSalapat Non-public servers don't show up on the server list.

If a streamers plays multiplayer, they might not want to accidentally reveal the connection information of the server they're playing on to the public. Avoiding showing the connection screen on stream can be done relatively easily by switching to a different scene while connecting, or using a shortcut to start Minetest already connecting to the server. But while playing it is difficult to avoid switching to the pause menu, say if you want to focus another window. I would like to avoid this leaking the server address.

**Comment by NathanSalapat** [comment]
You're right, I hadn't thought of that specific instance.

**Comment by fluxionary** [comment]
@copygirl in the meantime, if you want to hide the address, you can create a custom entry in your hosts file (search "how to edit host file") that's only meaningful on your computer and not anywhere else.
