### ISSUE TITLE
Pressing arrow keys on death formspec causes early respawn

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#13863]
### Minetest version

```true
Minetest 5.8.0-dev-debug-de0036f4c (Linux)
Using Irrlicht 1.9.0mt12
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Debug
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### Summary

This is a minor bug, basically cosmetic.

Pressing the arrow keys causes an early respawn without closing the formspec. This is very odd behavior, although it doesn't cause any serious problems. It's been listed on our bug tracker for quite a while and was brought to my attention again today, so I figured I'd post an issue here.

### Steps to reproduce

Open up devtest or whatever, /grantme fly, fast, zip up in the air and fall to your death.
Press an arrow key, and see how it respawns you without closing the formspec.

**Comment by srifqi** [comment]
I can confirm this issue. These are my tests on Windows 10 (10.0.19045):

**Does pressing these buttons trigger respawn?**

| Version | <kbd>Enter</kbd>/<kbd>Space</kbd><br>(clicking Respawn) | <kbd>Esc</kbd><br>(closing dialog) | <kbd>I</kbd><br>(inventory button) | <kbd>↑</kbd>/<kbd>↓</kbd><br>(up/down button) |
|:-------- |:---:|:---:|:---:|:---:|
| 0.4.8    |  ✅  |  ✅  |  ❌  |  ❌  |
| 0.4.9    |  ✅  |  ✅  |  ❌  |  ❌  |
| 0.4.10   |  ✅  |  ✅  |  ✅  |  ❌  |
| ⁞        |  ⁞  |  ⁞  |  ⁞  |  ⁞  |
| 0.4.15   |  ✅  |  ✅  |  ✅  |  ❌  |
| 0.4.16   |  ✅  |  ✅  |  ✅  |  ✅  |
| ⁞        |  ⁞  |  ⁞  |  ⁞  |  ⁞  |
| 5.0.1    |  ✅  |  ✅  |  ✅  |  ✅  |
| ⁞        |  ⁞  |  ⁞  |  ⁞  |  ⁞  |
| 5.7.0    |  ✅  |  ✅  |  ✅  |  ✅  |
| `master` |  ✅  |  ✅  |  ✅  |  ✅  |

Note: Pressing up/down button does not close the "You died" dialog. Pressing <kbd>Enter</kbd>/<kbd>Space</kbd>/<kbd>Esc</kbd>/<kbd>I</kbd> closes it.
