### ISSUE TITLE
Why do you guys refuse to add a launcher?

### ISSUE THREAD

**Issue by OguzY4** [minetest/minetest#13860]
### Problem

Just let people play any version of Minetest they want easily and they can get updates easier.

### Solutions

Please stop refusing to add it.

### Alternatives

Or the engine can update itself automatically

**Comment by rubenwardy** [comment]
You can comment on an issue that is closed, like #13817.  Creating a new issue like this will get you banned from this Github organisation

**Comment by SmallJoker** [comment]
Re-creating the same issue does not result in better chances for your request. Minetest's LGPL 2.1+ license allows you (among many other things) to distribute archives. Hence, if you would like to write a launcher you might do so. Nobody will stop you from doing that.
