### ISSUE TITLE
Too many open issues

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#13874]
1090 is a lot. A **lot**. Well enough to drown in. Even if one issue per day would be resolved it would still take 3 years to handle all of them—totally ignoring new ones. A better plan is needed.

**Comment by rubenwardy** [comment]
*1091

**Comment by rubenwardy** [comment]
There's probably a lot that can just be closed - duplicates and more. Just needs someone to go through it

**Comment by Zughy** [comment]
Closing #13510 was counterproductive, now people will start asking about whether we chose a new name or not. I suggest to reply under the internal discussion instead

**Comment by rubenwardy** [comment]
Just want to point out that anyone can look for duplicates or issues that should be merged

**Comment by Zughy** [comment]
@numberZero there were 1097 issues until three days ago. I've been closing something here and there (and trust me, it's not a fun task) but we can't make miracles. We need more contributors, core devs, possibly bounties as incentive. The blog could suggest to focus on the 300+ bugs we have left open, but the blog is kind of dead at the moment (which brings us back to more contributors). Also, let's not forget that Minetest is a software with a lot of code debt, it takes time to navigate through that and fix it. Do you have any suggestions by the way? I'd be glad to hear it

**Comment by Zughy** [comment]
Also, we had already reached this number in the past, before I started cleaning the whole repo. Unfortunately, I don't know how much there is now left to clean

**Comment by numberZero** [comment]
> @numberZero there were 1097 issues until three days ago.

> closing something here and there (and trust me, it's not a fun task)

I see. I’ve skimmed through some random issues years old, and each one looks legitimate.

> but we can't make miracles.

Noone can.

> We need more contributors, core devs,

That won’t help. At the current pace (+48−27 issues last month) 4.5 years of constant effort are necessary to handle everything. Even with 10x contributors and core devs that’d be still half a year.

**Comment by Zughy** [comment]
I'm interested to hear some solution/alternative approach

**Comment by Zughy** [comment]
Also https://irc.minetest.net/minetest-dev/2023-10-08#i_6120792

**Comment by jeremyshannon** [comment]
From what I've seen, the number of issues listed is less a problem for a project than the number of queued pull requests. Waiting for months while your PR sits around discourages contributors.

**Comment by Zughy** [comment]
Since OP agreeing on the latest comment, I'll close. If the topic wants to be discussed further, I suggest to use the forum
