### ISSUE TITLE
Redirect from minetest.gitlab.io to api.minetest.net

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#13886]
The former is still linked to and appearing in search results. There should be a redirect in place

**Comment by rubenwardy** [comment]
You need to use HTTPS not HTTP

**Comment by gd2shoe** [comment]
Now that's really weird.  Chrome is supposed to default to HTTPS... unless something has changed in the last few years:
https://blog.chromium.org/2021/03/a-safer-default-for-navigation-https.html

This might still be a server setting... but it could also be Chrome behaving badly.
Good catch.

**Comment by rollerozxa** [comment]
What would be the best course of action for this? The only option would probably be to replace the current GitLab action to instead deploy a site with just this on it:

```
<meta http-equiv="Refresh" content="0; url='https://api.minetest.net">
```

**Comment by rubenwardy** [comment]
Here's what the jekyll template generates

```
<!DOCTYPE html>
<html lang="en-US">
  <meta charset="utf-8">
  <title>Redirecting&hellip;</title>
  <link rel="canonical" href="https://api.minetest.net/">
  <script>location="https://api.minetest.net/"</script>
  <meta http-equiv="refresh" content="0; url=https://api.minetest.net/">
  <meta name="robots" content="noindex">
  <h1>Redirecting&hellip;</h1>
  <a href="https://api.minetest.net/">Click here if you are not redirected.</a>
</html>
```
