### ISSUE TITLE
pause_fps_max does not affect shaders

### ISSUE THREAD

**Issue by webD97** [minetest/minetest#1388]
The setting pause_fps_max is useful to calm down your PC when your gone, but it doesn't seem ot affect the GLSL shaders, they just continue their work. IMO this should be fixed.

**Comment by paramat** [comment]
Reducing FPS never affects shader waving in-game, so why in pause menu? I can't see any need for this.

**Comment by paramat** [comment]
There are many things that could be disabled to reduce load in pause menu, but i'm not sure it's worth doing so.

**Comment by paramat** [comment]
Any interest? Is it worth working on?

**Comment by paramat** [comment]
Closng in 1 month if not.

**Comment by paramat** [comment]
Dead issue and:

> aren't shaders calculated on gpu only?
