### ISSUE TITLE
`minetest.get_player_names` in CSM API duplicates current player

### ISSUE THREAD

**Issue by rollerozxa** [minetest/minetest#13898]
### Minetest version

```true
Some 5.8.0-dev version
```

### Summary

`minetest.get_player_names` in the CSM API duplicates the current player's name in the list of player names.

Seen from Player2's perspective:
![image](https://github.com/minetest/minetest/assets/60856959/92bff13f-15dd-4582-800d-52975350e870)

### Steps to reproduce

Print out what get_player_names returns, or install [my playerlist CSM](https://github.com/rollerozxa/playerlist_csm/blob/master/init.lua), and comment out the check in the code that works around this bug:

```lua
if i ~= 1 then -- for some reason the first name in the list is a duplicate of the current player
```

**Comment by SmallJoker** [comment]
Possible cause: `std::list` does not guarantee unique entries. `std::set` would be more appropriate.

https://github.com/minetest/minetest/blob/b1dec37adb16f7ccd21209cbdd8381865cdfb5ca/src/network/clientpackethandler.cpp#L1538-L1542
