### ISSUE TITLE
Node property determining if a node is 'swimmable' or not, and how swimmable it is.

### ISSUE THREAD

**Issue by mecha-moonboy** [minetest/minetest#13892]
### Problem

I find climbable water streams from buckets to be extremely overpowered and to be a "Minecraftism". There is no physical explanation for climbing through falling water and I think it should be 'off' by default. Climbable waterfalls removes any need for climbing gear, rope, rappeling, etc.

### Solutions

Options:
- add a 'swimmable' property to nodes which sets whether it is swimmable and how much so
- add a 'on_pass_through' property that executes on a given entity as it passes through a node
- add an 'on_swim' property to entities which can be used to check the block they're swimming through
- add a 'no_gravity' property to nodes which allow or disallow gravity on entities within the node
- apply gravity to players while in flowing water

### Alternatives

If I cannot find a solution to this design flaw, I will need to work around it mechanically and remove the capability to place water source blocks, enact gravity while in flowing water, or some other indirect solution.

### Additional context

Climbing is difficult in real life. The only other context for swimming up waterfalls is Minecraft, which is fine for MC but _not_ hard-coded into MT.

**Comment by wsor4035** [comment]
going to mention @Wuzzy2 due to there work with physics modifiers/thoughts they might have on the topic

**Comment by mecha-moonboy** [comment]
After I searched for 2 hours I found the "disable_jump" node-only group which solved my problem. River swimming is weird but manageable. I suppose this issue can be closed. I don't know why it took me so long to find. Apologies for any time wasted.
