### ISSUE TITLE
Text issues in the Minetest's English texts/strings

### ISSUE THREAD

**Issue by srifqi** [minetest/minetest#13907]
Hello. While translating the Minetest engine (after the recent strings update), I found some issues with the English texts/messages.

Please note that I am not a native English speaker. I just copied the strings into a word processor and listed problems from the spell checker here.

| Original Text | Fix | Reason |
|:------------- |:--- |:------ |
| for FSAA and SSAA **antializasing** methods. | antialiasing | Mistype |
| odd/even line based **polarisation** screen support. | polarization | US spelling |
| Defines **size** of the sampling grid | the size | Missing article |
| shadow map over given **amount of frames**. | number of frames | Countable noun |
| **Amount of messages** a player may send per 10 seconds. | Number of messages | Countable noun |
| The client will **not longer** receive most invisible | no longer | - not longer = not for a long time<br>- no longer = not any more |
| **so see** a full list at | so, see | Comma |
| When enabling water **placement the floatlands** must be | placement, the floatlands | Comma |
| enabled. **Also the** vertical distance over which | Also, the | Comma |
| Clouds are a **client side** effect. | client-side | Hyphen |
| using a **high resolution** texture pack. | high-resolution | Hyphen |
| **Client side** node lookup range restriction | Client-side | Hyphen |
| The depth of dirt or **other biome** filler node. | other-biome | Hyphen |
| Maximum size of the **out chat** queue | out-chat | Hyphen |
| Maximum **forceloaded** blocks | force-loaded | Hyphen |
| Default maximum number of **forceloaded** mapblocks. | force-loaded | Hyphen |
| **Server side** occlusion culling | Server-side | Hyphen |
| **WARNING!:** There is no benefit | WARNING: There | Multiple punctuation |
| **Misc** | Misc. | Missing punctuation |
| The file path relative to your **worldpath** in which profiles | world path | Not in a dictionary |
| Static **spawnpoint** | spawn point | Alternative form |

I want more input from native English speakers (or someone proficient in English) about the fix before it is implemented.

**Comment by grorp** [comment]
It would be nice if you could create a PR with these changes, then we could use review comments to discuss them more easily.

**Comment by rollerozxa** [comment]
Since this is probably relevant for the issue, there is a duplicate "Change keys" translation in the main menu settings dialog, while the pause menu uses "Change Keys" with capital K.

![image](https://github.com/minetest/minetest/assets/60856959/cfddb25c-dcc5-4f12-a98f-adf965e2628a)

**Comment by srifqi** [comment]
I created a PR about this.

**Comment by qwerty123a2** [comment]
@srifqi Why do you think that US  English is correct. Where does it it say that?

**Comment by srifqi** [comment]
It is a decision from 2017 (if I recall correctly). Read ["Code style guidelines"](https://dev.minetest.net/Code_style_guidelines) page on the Minetest Developer Wiki.

> ### Spelling
> Use American English, but avoid idioms that may be difficult to understand by non-native speakers.
