### ISSUE TITLE
Scroll bar up and down triangles are rendered in black on very dark buttons

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13909]
### Minetest version

```true
5.7.0-350-g8a9855241
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11 / SDL (both)

### Operating system and version

Debian GNU/Linux 11.7

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

### GPU model

Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

1.4

### Summary

The triangles on the buttons next to the scroll bars are black on a dark background.

I have a contrast vision problem and this makes it very hard to recognize the icons.

I believe that this is a bug – given that other symbols on buttons are rendered white.

Minetest's scroll bars have probably been like this for a long time, but I only noticed this after I started using Minetest with SDL and commented out the SDL scroll wheel code (because that requires a version of `libsdl2-dev` that is newer than what Debian 11.7 provides) and looked for the scroll bar buttons.

See for yourself:

![minetest-580-dev-settings-fail-1](https://github.com/minetest/minetest/assets/60905/c1c35dc8-8f6f-4a93-bef6-c53fba1de4da)

### Steps to reproduce

1. Start Minetest.
2. Navigate to any part of the interface that has a scroll bar.

**Comment by rollerozxa** [comment]
The arrows on the scrollbars, along with the arrows on dropdowns and the checkbox (unless the density is high enough that it will replace it with a texture) are symbols taken from Irrlicht's built-in font. The colour of them can be customised by changing a GUI skin colour, so to make it white you can put this in `src/client/clientlauncher.cpp`:

```c++
skin->setColor(gui::EGDC_WINDOW_SYMBOL, video::SColor(200, 255, 255, 255));
```

![image](https://github.com/minetest/minetest/assets/60856959/2d40c649-da6a-4204-8f12-787c2b23e551)

**Comment by erlehmann** [comment]
@rollerozxa that seems *very* useful, please make a PR for this.
