### ISSUE TITLE
`register_on_chat_message` gets a whitespace-trimmed chat message

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#13916]
### Minetest version

```true
Minetest 5.8.0-dev-6fdc7e0da-dirty (Linux)
```

### Operating system and version

arch linux

### Summary

See `Server::handleChat`:
https://github.com/minetest/minetest/blob/b0107144261f6513bbde95323c9663a71ed8f3c9/src/server.cpp#L3035

`core.format_chat_message` receives a message with whitespace, `core.format_chat_message` with trimmed whitespace.

Apparently #8420 added the trimming. cc @rubenwardy 
Is there some rationale behind this (not sure if it's a bug)?

### Steps to reproduce

```lua
core.register_on_chat_message(function(name, message)
	core.log("on chat msg: "..dump(message))
end)
```

In `builtin/game/chat.lua`:
```diff
function core.format_chat_message(name, message)
+	core.log("msg to format: "..dump(message))
```

Write e.g. ` foo `.
=> `"foo"` vs. " foo "

### Additional context

I found this because if you enable csm, you get the "Issued chat command: ..." messages, but not if you put whitespace before the `/`.

#### Offtopic

I had to create this Additional context section inside the Steps to reproduce field. I hate the issue form, especially the current one.

**Comment by rubenwardy** [comment]
> Apparently https://github.com/minetest/minetest/pull/8420 added the trimming. cc @rubenwardy Is there some rationale behind this (not sure if it's a bug).

It's 5 years ago so I have no idea

**Comment by appgurueu** [comment]
The solution is probably just to add trimming in the appropriate places. Leading/trailing whitespace preservation is really a "spacebar heating" kind of feature.

---

> I had to create this Additional context section inside the Steps to reproduce field. I hate the issue form, especially the current one.

I agree, that's why I often choose the "open a blank issue" option instead :)

**Comment by Zughy** [comment]
![image](https://github.com/user-attachments/assets/73094b9b-e220-41d4-addd-e3debf3adb61)

Can't seem to reproduce it

**Comment by Desour** [comment]
>Can't seem to reproduce it

It looks like you didn't add whitespace.

(Will make issue description more clear.)
