### ISSUE TITLE
Wireframe debug view shows only backfaces if undersampling on or 3d mode active

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13921]
### Minetest version

```true
5.7.0-279-gb1dec37ad
```

### Active renderer

OpenGL 1.4

### Irrlicht device

X11

### Operating system and version

Debian GNU/Linux 11.7

### CPU model

Intel(R) Core(TM) Duo CPU      T2400  @ 1.83GHz

### GPU model

Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)

### OpenGL version

1.4

### Summary

With the wireframe debug view and `undersampling` active, I can see only back faces of nodes.

Are the front faces maybe accidentally getting culled here?

Screenshots from the `void` game:

![minetest-580-dev-wireframe-fail-1](https://github.com/minetest/minetest/assets/60905/5332cabc-b7e7-48da-98b1-4aa59786162b)
![minetest-580-dev-wireframe-fail-2](https://github.com/minetest/minetest/assets/60905/6dd57239-b720-43bb-9c15-0eb939169823)

### Steps to reproduce

**If you can not reproduce this and are not convinced by the comments that this bug is real, ask me for the *apitrace* file.**

1. Compile Minetest 5.7.0-279-gb1dec37ad on a Thinkpad T60 (x86).
2. In `minetest.conf` set `undersampling` to `2` or a higher integer.
3. Start the `void` game.
4. Activate wireframe mode.
5. Notice that the only triangles visible are the ones that are normally invisible.

**Comment by erlehmann** [comment]
I found the place in the frame where the back faces are rendered with *qapitrace*:

![minetest-580-dev-wireframe-fail-3](https://github.com/minetest/minetest/assets/60905/800e3d5b-0239-461b-845b-3e39737c226c)

**Comment by erlehmann** [comment]
According to the trace, `GL_CULL_FACE_MODE` is `GL_BACK` is set but it seems as if this is not explicitly set in the rendered frame. It is set in the previous frame though.

Is this the default or is this undefined? This might be hard to reproduce if the default culling is undefined.

Another question: Is the wireframe rendering even culled on the GPU at all or is this a CPU thing?

**Comment by erlehmann** [comment]
Here is what I did:

1. Capture an OpenGL trace of Minetest.
2. Trim that trace down so that it contains fewer frames.
3. `apitrace sed -e 's/GL_CULL_FACE/GL_BLEND/' minetest-580-dev-wireframe-fail.trace`

The modified trace renders correctly, as far as I can see (this is the same frame as you can see in a comment above).

![minetest-580-dev-wireframe-fail-4](https://github.com/minetest/minetest/assets/60905/38e1ea7a-02dc-4290-9dbe-d5ef90b787a7)

**Comment by erlehmann** [comment]
With `LIBGL_ALWAYS_SOFTWARE=1` backfaces are culled, which seems a bit weird for a wireframe mode. **Is that intended?**

[An Intel integrated GPU (i965) had a driver issue where backface culling culled front faces. It was fixed in 2008 though.](https://bugs.freedesktop.org/show_bug.cgi?id=19099)

I will research if this is a driver bug. It would not be the first Minetest rendering issue where Mesa is at fault: https://github.com/minetest/minetest/issues/11987

**Comment by erlehmann** [comment]
Regardless of what the reason is, this bug also happened in Minetest 5.4.1. Why only in undersampled wireframe mode though?

![minetest-580-dev-wireframe-fail-5](https://github.com/minetest/minetest/assets/60905/3a73bc18-95aa-4373-a220-626fe6b50450)

**Comment by erlehmann** [comment]
So it seems that this bug happens with wireframe mode in 3D view modes too, entirely without undersampling!

I assume this because they also render to an offscreen target first. Does culling work differently in such a case?

![minetest-580-dev-wireframe-fail-6](https://github.com/minetest/minetest/assets/60905/de75ecee-30cd-401f-9810-32e1772d69e6)

**Comment by erlehmann** [comment]
If someone could provide a simple OpenGL program that renders some cube with culled backfaces while rendering to an fbo that is then shown on screen without using Irrlicht I could exclude or confirm that this is a GPU driver bug. I can not exclude this being an engine bug at this point, as there are too many things that affect culling and some people have such problems (inverted culling) with other GPUs and/or other 3D engines (e.g. Unity, i.e. not Minetest).

I am planning to replay the *apitrace* file on another GPU to figure out more. If it renders correctly there, I will complain to Mesa.

**Comment by rubenwardy** [comment]
Can't reproduce this issue. Set undersampling to 3 and enabled wireframe:

![image](https://github.com/minetest/minetest/assets/2122943/ab5b256a-ac37-4858-a42a-1ecb32d46fbf)

**Comment by erlehmann** [comment]
I can pretty much exclude this being a similar driver bug as the i965 one from 2008 I mentioned previously: https://github.com/minetest/minetest/issues/13921#issuecomment-1779942095

Here is what I did:

```
git clone https://gitlab.freedesktop.org/mesa/demos
cd demos
git checkout 'mesa-demos-8.5.0'
cmake .
make demos_fbotexture
./src/demos/fbotexture
```
I then pressed `c` to enable culling. If a faulty GPU driver would indeed invert the culling order here for fbo rendering somehow, instead of the properly lit outside of a teapot I would see the unlit inside of a teapot (this can be verified by changing in line 154 of `src/demos/fbotexture.c` the word `GL_BACK` to `GL_FRONT`). However, I see the properly lit outside of the teapot.

I have not replayed the apitrace on another GPU.

**Comment by erlehmann** [comment]
So @corarona tested an apitrace from my machine on `Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)`. We found the following rendering differences between my and her GPU:

Mine:
![945_call_39533](https://github.com/minetest/minetest/assets/60905/e7d2aa1d-53d1-4d1d-a626-71a1a5d4bfc9)
![945_call_40262](https://github.com/minetest/minetest/assets/60905/5828a8ee-a8b4-40f4-9a01-08e372a29208)

Hers:
![gt2_call_39533](https://github.com/minetest/minetest/assets/60905/37a887d0-be20-4440-87db-ca9f82fe4f35)
![gt2_call_40262](https://github.com/minetest/minetest/assets/60905/c40c3421-5832-4a85-8217-2361f1f23011)

The only way I can see this not be a driver bug is if the default culling order at this point is somehow not well-defined.

I  will file a bug with Mesa regarding the driver for my `Intel Corporation Mobile 945GM/GMS, 943/940GML Express Integrated Graphics Controller (rev 03)`.

**Comment by erlehmann** [comment]
Corresponding Mesa issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10058

Again: Please do not close this issue until Mesa has verified that it is a driver bug.

**Comment by Zughy** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/10058#note_2146818
