### ISSUE TITLE
Discuss: Behavioural subtyping guarantee for Minetest API functions and texture modifiers / other rendering topics (which ones?)

### ISSUE THREAD

**Issue by erlehmann** [minetest/minetest#13936]
### Problem

Changes (mostly upgrades) to the existing Minetest Lua API are necessary from time to time.

However, I have not found any part of the documentation that states self-imposed constraints for API changes.

API changes that I found were mostly backwards-compatible, so I mostly just want to codify existing practice into a guarantee.

This suggestion is intended to reduce work spent on discussing Minetest Lua API extensions, as any change that violates such a guarantee can be discarded, In API change discussions, developers would not have to deal with two possibilities that achieve the same result if one of them would violate this guarantee, because there would be a logical default.

### Solutions

As I understand it, [behavioural subtyping mostly means that implementations can change but without breaking existing usage.](https://en.wikipedia.org/wiki/Behavioral_subtyping)

I suggest to guarantee in the documentation that Minetest Lua API  functionchanges are only ever done in a way that the type of the old function can be considered a subtype of the new function. I also suggest that texture modifiers are only extended in backwards-compatible ways.

**Why would I want this?**

A behavioural subtyping guarantee would reduce the amount of breakage in Minetest mods that results from API changes.

Thinking about how to achieve a behavioral subtyping guarantee probably also results in better design for new Minetest APIs.

**So how does this work?**

Adding a new argument `can` to a function with two arguments `func(ham, spam)`:

* `func(can, ham, spam)` would be an incorrect API upgrade, as it would break existing callers.
* `func(ham, spam, can)` would be a correct API upgrade, if it does not break existing callers.

When a Lua function takes a table of arguments as a first parameter, extending it is often easy.

**What would be forbidden?**

These are only some examples:

* Changing function argument order of two arguments of the same type.
* Breaking existing texture modifier behaviour in backwards-incompatible ways.
* Changing the meaning of a function argument in a backwards-incompatible way.

Note that changing the type of a single function argument is not necessarily forbidden, as a shared supertype that includes the types of both the old and new functions can easily be constructed in such a scenario. So anything where you need to change a boolean to a string is fine, as long as the boolean is still accepted (possibly with a warning).

**What's the worst that could happen?**

At the very worst – i.e. if no new implementation can possibly satisfy the proposed behavioural subtyping guarantee – the result would be that a new function would be added to the API instead (and the old one possibly deprecated). However, in most cases I have seen so far modifying an existing function in a way that would satisfy such a guarantee is indeed possible.

**Do you have an example of something that would have been done differently with such a guarantee?**

Yes. In Minetest 5.5.0, `minetest.dynamic_add_media` was changed in a way that it does not satisfy this relation in respect to earlier implementations. However, the new function type makes it easy to preserve the relation from now on though, as the first argument was changed to an options table. Following such a guarantee here could have resulted in a new function being added and the old one either being retained or deprecated and eventually removed.

### Alternatives

* Do nothing.

### Additional context

There is a reason why I have not titled this issue ”support everything ever supported in Minetest for literally forever”.

(That reason is because that is not what I am suggesting here.)

**Comment by Wuzzy2** [comment]
I like this. The less breakage, the better.

**Comment by Wuzzy2** [comment]
Maybe it also makes sense to document what type of breakage *is* allowed. The suggestion to deprecate BMPs is a perfect example.

**Comment by rubenwardy** [comment]
We already follow this, except for experimental and undocumented APIs. This is key to compatibility

Changing existing arguments is fine as long as you continue to support the old arguments. For example, the particle function previously took a list of parameters but now takes a single table. You can still pass a list of parameters

**Comment by erlehmann** [comment]
> Maybe it also makes sense to document what type of breakage _is_ allowed. The suggestion to deprecate BMPs is a perfect example.

@Wuzzy2  yes, Minetest is missing a proper deprecation policy, but that has nothing to do with this issue. This is partially why I did the work on that issue, even if some of it was rejected, to show that something can easily be deprecated without affecting anyone if someone (in that case, me)  puts the work into it to find out if this can be done without breaking user worlds.

> We already follow this, except for experimental and undocumented APIs.

@rubenwardy the dev team *mostly* does this, but the assertion “I doubt this will break anything” by a core dev or two seems to be enough to change something in an incompatible manner or even deprecate stuff without a replacement (e.g. schur product). The following regressions all changed something in an incompatible manner and were all fixed later because of it, creating work out of thin air:

* https://github.com/minetest/minetest/issues/12581
* https://github.com/minetest/minetest/issues/12537
* https://github.com/minetest/minetest/issues/11775

I suspect that these three and many more bugs would simply not have occured with a behavioural subtyping guarantee.

(Please do not start discussing these bugs – I just provided them as reference for what kind of things I want to prevent.)

**Comment by sfan5** [comment]
Are you suggesting to apply this to _documnted_ or _observable_ behaviour? From your responses it seems to be the latter.
(Needless to say that would be an extreme inhibitor for any future API changes.)

By the way "behavioural subtyping" seems like the wrong terminology for this since there are no class hierarchies involved at all.

The three examples you gave are also poor. These were accidents. A policy would have had zero effect on them since nobody was intentionally making an incompatible change.

In addition this violates the existing practice of changing something with a deprecation period.
I do not support this :-1:

**Comment by erlehmann** [comment]
> Are you suggesting to apply this to _documented_ or _observable_ behaviour? From your responses it seems to be the latter. 

I would lean towards observable as in “mods are known to use this and rely on it in ways that makes the result incorrect when it is changed”, but I suspect you lean towards documented as in “even if it has been known for years that this function works like that and it is used in mods and is on the wiki, core devs should be free to change whatever they did not commit to”.

I consider any kind of stronger guarantee than nothing a good first step though. I just want to prevent rug pulls.

> (Needless to say that would be an extreme inhibitor for any future API changes.)

**Not at all. Software libraries extend their APIs all the time and it works fine.**

This guarantee would mostly be about the *shape* of the changes, not about *which* changes to make.

 If you have a new version of `libc` (or whatever), it is rare that you need to change the source code of software that uses it.

For a Lua example, you can examine how I extended the API for `tga_encoder` in a (hopefully) 100% backwards compatible way.

> By the way "behavioural subtyping" seems like the wrong terminology for this since there are no class hierarchies involved at all.

I started thinking about [a specific kind of type relation that Barbara Liskov introduced in 1987, the Liskov substitution principle](https://en.wikipedia.org/wiki/Liskov_substitution_principle).

My inspiration was that a coworker said that arguments to functions need to be ”liskov-substitutable” when upgraded.

Do you know a better name for that specific relation if we are not talking about object-oriented design?

> The three examples you gave are also poor. These were accidents. A policy would have had zero effect on them since nobody was intentionally making an incompatible change.

Mistakes were made, yes. But having a strict requirement would *probably* make people examine if the requirement is fulfilled.

> In addition this violates the existing practice of changing something with a deprecation period. I do not support this 👎

I think that practice simply does not werk as well for game/mod authors as it does for core devs, unless both they and their players get spammed with warnings and there is compatiblity code (like with the `use_texture_alpha` thing – I think that kinda worked out okay-ish).

**What I have learned is that game/mod authors are not known to actually recognize subtle breaking API changes early.**

And the coredevs keep making their changes (reverting many of them), which to me just looks like usefless busywork.

Again, I am not saying that everything should be supported forever. I am saying upgrades should done in a more predictable way to have less breakage – and especially less less-obvious breakage. I would, for example, have preferred a hard crash to the race conditions for dynamic media – because then it would have been *much* less debugging work to figure out what went wrong.

**Comment by Desour** [comment]
>Software libraries extend their APIs all the time and it works fine.

And they don't keep every observable behaviour compatible. :P

Keeping the documented API backwards compatible (or mostly compatible, in case there's a some weird detail that we know nobody relies on) is what we already do, AFAIK.
If modders rely on implementation details, or undocumented behaviour, they know that the hack they're producing can break over time.

**Comment by erlehmann** [comment]
>  If modders rely on implementation details, or undocumented behaviour, they know that the hack they're producing can break over time.

Again: Some of the worst breakage that I witnessed (and fixed) in mods occured because something that was *clearly* documented and not experimental was changed in a way that violated the constraint, presumably because it was assumed that such a change was irrelevant or ”permissible” breakage.

Also, to quote the Wikipedia article:

> It is important to stress that whether a type S is a behavioral subtype of a type T depends only on the specification (i.e. the documentation) of type T; **the implementation of type T, if it has any, is completely irrelevant to this question.**

I have little more to say here. If a team does not want to commit to this, no amount of “this will save you workl” can change that.

**Comment by sfan5** [comment]
> I would lean towards observable as in “mods are known to use this and rely on it in ways that makes the result incorrect when it is changed”,

Well that would introduce a bunch of new problems:
How do you find out which mods use the affected behaviour? Seach CDB (if feasible)?
If there's one result, does that mean the change can't be done? What about 3? 10?
Are some mods/games more important than others?
What about people who don't publish (or not on CDB)? Are they out of luck?

I don't think it's feasible or possible to define a good ruleset for these question so in the end we would be having the same discussions for changes/deprecations that are being had now. 

Aside of this I think most of the core devs are on the "guaranteed is only what was documented" side.

> Not at all. Software libraries extend their APIs all the time and it works fine.

Nobody was saying it is impossible. Rather, it imposes extra implementation work.

There are a bunch of libraries that do not break backwards-compatibility -- even in presence of bugs -- at any cost (like Linux, glibc and probably other low-level stuff). I don't think MT should be one.

> Do you know a better name for that specific relation if we are not talking about object-oriented design?

No, but it also doesn't matter.

> I think that practice simply does not werk as well for game/mod authors as it does for core devs, unless both they and their players get spammed with warnings and there is compatiblity code

Then maybe we can fix that?
For example we could keep a separate document for each release that contains a list of all things that were deprecated.

**Comment by erlehmann** [comment]
> > I would lean towards observable as in “mods are known to use this and rely on it in ways that makes the result incorrect when it is changed”,
> 
> Well that would introduce a bunch of new problems: How do you find out which mods use the affected behaviour? search CDB (if feasible)? If there's one result, does that mean the change can't be done? what about 3? 10? Are some mods/games more important than others? What about people who don't publish (or not on CDB)? are they out of luck?

I do not want to go into this further right now, as not only I have done a lot of the work for deprecating BMP, I know that other people are not doing that, because it is additional work.

> I don't think it's feasible or possible to define good rules for these questions so in the end we would be having the same discussions for changes/deprecations that are being had now.

Again, deprecation is a separate topic from changes/upgrades. Why do people repeatedly bring up deprecation here?

**I mainly want that *adding* functionality does not break existing call sites that rely on documented behavior.**

Btw: This is why I bring up the dynamic media thing. It was documented and not experimental, yet changed incompatibly.
I actually think that those improvements were good – the problem was that it broke in very subtle ways, i.e. not obviously.
(Less problematic ways to upgrade that API did exist, so the “inhibitor for API changes” argument does not convince me.)

> Aside of this I think most of the core devs are on the "guaranteed is only what was documented" side.

Yeah, so why not explicitly guarantee compatibility to older documentation then?
You could still deprecate things, but nothing would break in hard-to-debug ways;
i.e. either a thing keeps working or it throws warnings or does not work entirely.

> > Not at all. Software libraries extend their APIs all the time and it works fine.
> 
> Nobody was saying it is impossible. Rather, it imposes extra implementation work.

As I see, my proposal imposes extra design constraints – before an actual implementation is created.

Btw, not doing it also creates extra work (either fixing regressions in Minetest or game/mod dev work).

> There are a bunch of libraries that do not break backwards-compatibility -- even in presence of bugs -- at any cost (like Linux, glibc and probably other low-level stuff). I don't think MT should be one.
> 
> > Do you know a better name for that specific relation if we are not talking about object-oriented design?
> 
> No, but it also doesn't matter.

I agree.

> > I think that practice simply does not werk as well for game/mod authors as it does for core devs, unless both they and their players get spammed with warnings and there is compatiblity code
> 
> Then maybe we can fix that? For example we could keep a separate document for each release that contains a list of all things that were deprecated.

That might help, but I have no good idea how to reach the people who are not reading the documentation now that way.

I do indeed think deprecation can be better and I will think about it. But first I have to research what worked and what did not.

**Comment by appgurueu** [comment]
> Breaking existing texture modifier behaviour in backwards-incompatible ways.

I disagree with continuing to support anything beyond what is documented, given how hacky our current implementation is. If people rely on undocumented hacks, that's on them; the implementation can hardly be improved if it was to be kept 100% backwards-compatible with observable behavior.

As for "behavioral subtyping": That's more narrow.

If our signature is `function(Foo, Bar)`, where `Foo` and `Bar` are types (which should be (implicitly) documented), "overloading" this with a signature of `function(Baz, Foo, Bar)` is completely fine: Any valid usage should not have passed a third parameter. "Overloading" this with `function(FuncParamsTable)` (as has been done in the past e.g. in the case of particle spawners, as was mentioned) is fine as well.

(That said, adding new/optional arguments at the end of the parameter list is usually the most convenient.)
