### ISSUE TITLE
Tooltip of language setting is somewhat wrong

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#13932]
### Minetest version

```true
5.8.0-dev-2ce14ce4e
```

### Active renderer

OpenGL 4.5

### Irrlicht device

X11

### Operating system and version

Parabola

### OpenGL version

4.5

### Summary

In the settings menu, the tooltip for the language setting is slightly wrong. It says you must leave this field "empty" in order to use the system language. However, this is wrong. None of the entries in the drop-down list is empty. The first one is "(use system language)", which is not empty.

I guess the "empty" refers to the internal representation of the setting when editing minetest.conf by hand? Because in minetest.conf this is true. I think this tooltip needs to be written in a way so that it is always telling the truth.

### Steps to reproduce

1. Go to the settings page
2. Go to Accessibility
3. Hover the "info i" image next to the language setting

**Comment by srifqi** [comment]
> Set the language. Leave empty to use the system language. A restart is required after changing this.

**Comment by srifqi** [comment]
The text in question:

> Set the language. Leave empty to use the system language. A restart is required after changing this.

This might need a differentiation between descriptions in `settingtypes.txt` and `minetest.conf.example`.
