### ISSUE TITLE
Translation updater: propagates template.txt comments through other files

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#13947]
### Summary
I expect comments in template.txt to be propagated through other files, as they're quite likely to be instructions for translators (actually I can't think of any other use). Practical example: https://gitlab.com/zughy-friends-minetest/a.e.s.-server-custom-mods/a.e.s.-terms-of-service/-/issues/2#note_1502143795

@Wuzzy2

**Comment by srifqi** [comment]
> ... I'd say keep both

In what order? Is checking its substring fine for checking the existence of a template comment?

**Comment by Zughy** [comment]
Template first, .tr second. But we're talking about an edge-case anyway
