### ISSUE TITLE
`register_item`/`register_node` conflicts with modder's metatable usage

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#13953]
### Summary

See [this forum post by @hecktest](https://forum.minetest.net/viewtopic.php?p=430110#p430110):

> I don't feel like digging up my github info so I'll write it down here for now, maybe someone else can file the issue:
> 
> In builtin/game/register.lua at lines 154 to 163 (this code is hella weird but that's another story), the engine applies a metatable to the item/node definition submitted by the modder.
> 
> This sadly prevents the usage of metatables to subclass items and nodes and reduce the amount of code, as any __index tricks to implement inheritance will not work - the original metatable is detached and MT effectively makes the definition inherit from engine defaults, creating a conflicting ad-hoc class system where you can't insert your own types in the hierarchy between nodedef_default and the submitted def.
> 
> For now I can work around this by using debug.getlocal to get at register_item_raw and using my own registration logic, but this is ugly and obviously unsupported. (though unlikely to break in the future.) A quick fix would be to make register_item_raw reachable and supported; it's actually a cleaner API for original games and better reflects how the engine actually works. If I had known about it I'd have used it from the start.
> 
> Also, line 194 - this doesn't sink assignments but makes them leak to a table (newly created for each def), preventing garbage collection. This __newindex should be a no-op function instead. But ideally, the registration API should not touch metatables at all or even mutate any object passed to it. (that, or document this fact properly - this is what got me to check the code in the first place!)

### Steps to reproduce

:eye: :lips: :eye:

**Comment by Zughy** [comment]
Closing as invalid: heck is referencing to lines which could have changed in the meanwhile (no, I'm not gonna check file history just because they didn't want to look for their credentials). Feel free to open a new issue if you want to keep track of it
