### ISSUE TITLE
Bumpmapping makes nearly everything black

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#1396]
0.4.9-286-g3a9cf21-dirty

Screenshot made during daytime:
![2014-06-20-13 27 47-minetest opengl 3 0](https://cloud.githubusercontent.com/assets/1377943/3339557/3db696d8-f86e-11e3-868f-85dd2f5ba917.png)

As you can see there is a spot one the upper left.

**Comment by lightonflux** [comment]
I merged the current dev files with the worlds, mods, textures, and games from the archive i linked in the issue.

So it isn't caused by binaries of any version. 

If i disable all mods in the world, i made the screenshot with (above), then it is still there.

Same with another texture pack. Also when i use another game or world.

And i also deleted the minetest.conf and re-enabled all the options. But still.

I also deleted the folders mentioned above. No idea what causes this. 

Here some additional screenshot that might give one of you a clue. But if nobody has any ideas i would close this issue in the next week.

![minetest hauptmenu _051](https://cloud.githubusercontent.com/assets/1377943/5950034/fa7f7a24-a754-11e4-8ecf-656445546430.png)
![minetest opengl 3 0 _050](https://cloud.githubusercontent.com/assets/1377943/5950033/fa7f8122-a754-11e4-8b81-0b00b12e1a35.png)
![minetest opengl 3 0 _049](https://cloud.githubusercontent.com/assets/1377943/5950035/fa80eb0c-a754-11e4-8a2e-1436456eaa52.png)

**Comment by TriBlade9** [comment]
Huh, are you using mapgen v5/7 btw? I had this issue for awhile, but it was caused by some mods that deal with v5 and v7 mapgens. Additionally, I didn't think it was related to shaders at all.

**Comment by SmallJoker** [comment]
I'm getting the same result on Windows XP
![screenshot_1625207](https://cloud.githubusercontent.com/assets/1497498/5962697/e7fdab3c-a7e5-11e4-8e24-b10b7e96cedc.png)

**Comment by PilzAdam** [comment]
@lightonflux The "disable_img.png" is needed for shaders to work correctly and there is an error message that it is missing (among other textures). This suggests that your setup is broken (the textures should be in textures/base/pack/).

**Comment by lightonflux** [comment]
Closing as i
