### ISSUE TITLE
System freeze clicking `Quit to OS`

### ISSUE THREAD

**Issue by PavanLuca** [minetest/minetest#13972]
### Minetest version

```true
Minetest 5.7.0 flat
OpenGL 3.0
No renderers, MIP map, antialiasing or heavy settings or my laptop would just catch fire 😒.
```

### Irrlicht device

X11

### Operating system and version

Zorin OS Core 16.3

### CPU model

AMD® V140

### GPU model

AMD® Rs880

### OpenGL version

3.0

### Summary

Clicking `Quit to OS` makes the game freeze the whole computer. In my case happened only 2 so far, and I don't understand the reason at all. When happens of course I can only force shutdown. The first time probably happened when leaving Capture the Flag, this second time happened when leaving Coalition Warfare.

### Steps to reproduce

Open a multiplayer server > click `Quit to OS`

Sorry, there's not much to say about this issue 🤷.

**Comment by PavanLuca** [comment]
Alright, I'll try to make it happen again and check all logs related to this issue then 🙂👍.

**Comment by PavanLuca** [comment]
Alright, I'll try to make it happen again and check all logs related to this issue then 🙂👍. But are you sure that `dmesg` will show me messages from the previous boot? Because if I'm able to make the issue happen again I'll have to do a force shutdown as the system doesn't respond with this issue and I must be sure that I can effectively see the messages on `dmesg` even after a shutdown.

**Comment by Desour** [comment]
>But are you sure that dmesg will show me messages from the previous boot?

If you're on a system with systemd, it's `journalctl --boot=-1`.
Also, prefer SysRq keys over powering off your pc, see: https://wiki.archlinux.org/index.php?title=Keyboard_shortcuts&useskin=vector#Kernel_(SysRq)
It's still very possible that you see nothing in the logs though.

**Comment by Zughy** [comment]
@PavanLuca any updates?

**Comment by PavanLuca** [comment]
None, never happened again. It's possible that new versions or a system update fixed it, I'll report back if one day happens again.
