### ISSUE TITLE
Mapgen double-generating mapblocks, destroying user-built structures

### ISSUE THREAD

**Issue by fireglow** [minetest/minetest#1397]
Hi,

Did a clearobjects run, afterwards chunks that had buildings, etc in were regenerated.
I've noticed that problem before, but in a smaller scale. This time, a huge part of our spawn-area park got demolished.
So this is a serious issue where user-build structures get damaged, and /rollback can't do anything about.
According to PilzAdam, this is a known issue.

A fix would be most welcome.

**Comment by paramat** [comment]
From reports this seems to be happening in the 'just test' mgv7 server recently. Possibly more noticeable there because that is a very old server and mgv7 terrain has changed dramatically over the last 2 years. I am clueless on this.

**Comment by paramat** [comment]
Old issue, can anyone reproduce or is this now fixed?

**Comment by paramat** [comment]
I think this can be closed then.
