### ISSUE TITLE
Allow deferred map generation

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#13983]
### Problem

Currently, the VoxelManip object returned by `minetest.get_mapgen_object` is only valid for the duration of the on_generated call. The manipulator is freed after returning from said call, along with its data buffer.

This introduces a hard constraint on custom mapgens: you **must** be done with the chunk before returning from on_generated.
Even if you use FFI hacks to get at the data pointer and outsource the work to other threads or a GPU, the main thread is hopelessly blocked. Even if users do not want to use FFI, they could benefit from time-slicing the generation over several frames; the current on_generated design prevents this.

My current workaround is to create a separate VoxelManip that's safe to hold onto but I understand that it has the following drawbacks:
- A new scratch buffer must be allocated for the new manip
- The map database is written to twice
- The mapblocks are sent to clients twice
- The in-progress chunks aren't filled with `ignore` but with whatever `singlenode` has been instructed to emit (which is for some reason hardcoded to never be `ignore`)

### Solutions

Allow holding on to the mapgen VoxelManip past the end of on_generated, by returning a `true` value to signal that we're not done yet.
Use the `dispose()` call proposed in #13982 to signal that map generation has actually been finished. Finalize the mapgen if the object is garbage-collected without being disposed, but warn the user that they have a bug.
Until the mapgen VM has been disposed of, its buffer is not freed, the map DB is not written to, and the affected mapblocks stay unloaded and filled with `ignore`.

### Alternatives

None; this would for instance not be solved with a C mapgen API as the issue is tangential and affects Lua mapgens as well. A null mapgen that doesn't fill the mapblocks with anything would be less wasteful than `singlenode` but that's also tangential.

### Additional context

I'm trying to design a custom mapgen that minimizes the time spent blocking the main thread. Creation of duplicate VoxelManip objects and writing the map twice is currently the biggest bottleneck. Being able to asynchronously commit a VoxelManip would also help, but that's another issue - perhaps instead of a `dispose()` API, a dispose flag in write_to_map would also permit a non-blocking write?

**Comment by rubenwardy** [comment]
Would this be fixed by an async Lua mapgen API like in #13092 ?

**Comment by hecktest** [comment]
> Would an async Lua mapgen API like in #13092 be a viable alternative?

Partially; it will help by moving the manip creation and blitback away from the main thread, but it might also complicate things a lot by requiring the management of separate Lua universes. (which i can hopefully reduce to just scheduling and blitting)
If I want to use the mapgen voxelmanip, the Lua emerge threads will still have to sleep inside their callback waiting for a result from my system, effectively making their count a maximum queue size, tied to the `num_emerge_threads` setting.

What if I want to throw server-grade hardware at the mapgen, or even outsource the work to some compute farm, trading latency for a huge increase in bandwidth? Requiring an immediate result nullifies the benefits of moving the mapgen off-machine, and setting `num_emerge_threads` to 128 might have unforeseen consequences when each of these gains a whole Lua universe with its own garbage collector and a copy of the main thread's registration data.

Being able to defer the write would be helpful even after merging that PR; it's just a very inconvenient constraint that you have to finish the work in the same call stack. Removing this constraint would make the mapgen actually async, after the PR it will be threaded but still not fully async. Is there any reason this can't easily be done?

**Comment by sfan5** [comment]
The goal of my PR was to enable threaded map generation from Lua _at all_. Even if there was an async design and you'd do time slicing or whatever you are still doing the work on the main thread, which is bad. I imagine this meaningfully improves what most people do.

Exposing the async generation to Lua is possible and would need a few changes but nothing major (the engine already uses a queue internally).
Though it's probably better designed as a whole alternative to the Lua Mapgen Env.
Just adding a bool to on_generated runs into some issues with other mods. Do they see an incompletely filled vmanip? Do you delay the other callbacks too? How does that work? etc.

Thinking about the bigger picture it sounds like your use case would be best addressed if the engine had thread and IPC primitives and everything else was up to Lua. Unfortunately that's not the scope Minetest is at (yet?).

**Comment by hecktest** [comment]
You're overcomplicating this, bringing threading primitives and a separate mapgen API into the mix is a great way to make the fix never happen.

The only feature that's being asked for here is the ability to pause an emerged chunk so that its voxelmanip isn't disposed of in the same frame. Think of the whole chunk generation process as a coroutine; I'd like the ability to yield control back to other code and then request that it is resumed. Using the built-in coroutine library might work here - dispatch on_generated inside a coroutine, and whenever it yields, stash the in-progress chunk somewhere until other code requests that it's woken up. Use the minmax bounds of the chunk as an identifier for a wake request, or pass a unique ID to on_generated for this purpose. A pause would be initiated by `coroutine.yield`. The user would be responsible for stashing the identifier of the chunk they're about to pause.

Other mods' on_generated calls for the same chunk would not happen until the chunk is unpaused.

This is no replacement for threaded lua mapgen or an attempt to create a separate mapgen API; those are completely tangential and every approach will benefit from removing the arbitrary sync point described in this issue. These features are not competing; they're augmenting one another. I'll already have insanely good bandwidth if I can have multiple lua emerge threads dispatching the work to my DLL, but it's still shy of the theoretical maximum and doesn't let me control the system's topology entirely. Removing this one tiny constraint would give users absolute freedom. (that, and exposing the data pointer as a userdata object)

**Comment by jordan4ibanez** [comment]
Well that's interesting. I always thought that when the object's lifetime goes out of scope it was RCed. I think this would be quite an improvement.

**Comment by SmallJoker** [comment]
Whereas I do not fully understand the actual goal of this issue, the following part:

> Even if users do not want to use FFI, they could benefit from time-slicing the generation over several frames; the current on_generated design prevents this.

Is now addressed by #13092, thus I assume this issue is resolved?
