### ISSUE TITLE
undefined behavior in client/camera.cpp

### ISSUE THREAD

**Issue by superfloh247** [minetest/minetest#13980]
### Minetest version

```true
Minetest 5.8.0-dev-253eeb81b (OSX)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1699180677
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

### Operating system and version

MacOS 14

### CPU model

Apple M1

### Summary

minetest/src/client/camera.cpp:688:19: runtime error: nan is outside the range of representable values of type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/lindner/VSCode/minetest/src/client/camera.cpp:688:19

### Steps to reproduce

compile with -DCMAKE_CXX_FLAGS="-fsanitize=undefined -fno-sanitize=vptr" -DCMAKE_C_FLAGS="-fsanitize=undefined -fno-sanitize=vptr"

**Comment by Desour** [comment]
I was not yet able to reproduce this. In what situations does it happen?
And would the following commit fix it for you?
https://github.com/Desour/minetest/commit/bf5efe7093f5ca6e0ce749ababf8c575f0199fd1

**Comment by superfloh247** [comment]
unable to reproduce with bc33648
