### ISSUE TITLE
Superflat mapgen

### ISSUE THREAD

**Issue by atirut-w** [minetest/minetest#13988]
### Problem

There *is* currently a flat mapgen implemented, but it is only flat in terms of the generated heightmap. Caves, biomes, etc. are still generated.

A superflat mapgen can be desirable for developing mods or custom games, since there would be no structures or caves generated and thus be ideal for building out schematics or testing out mechanics in an isolated manner.

### Solutions

The simplest two (I can think of) would be adding a "superflat" flag to the existing flat mapgen or to implement a new mapgen. In my opinion, a new flag is probably the easier one to implement.

### Alternatives

None AFAIK

**Comment by tenplus1** [comment]
If you select "Flat" for the mapgen you can untick things like caves and decorations at the side to make it superflat already and only generate a single plane.

**Comment by atirut-w** [comment]
> If you select "Flat" for the mapgen you can untick things like caves and decorations at the side to make it superflat already and only generate a single plane.

This solution doesn't get rid of biomes, but it's plenty enough. In retrospect, I've only really ever noticed the part that says "Mapgen-specific flags", which was stupid of me.
