### ISSUE TITLE
FPS drops when debug information is shown (Windows MSVC build)

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest#13990]
### Minetest version

```true
minetest 5.8.0-dev-8vf6e00
```

### Active renderer

OpenGL 4.6.0

### Operating system and version

Windows 10 Home 22H2

### CPU model

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz

### OpenGL version

4.6.0

### Summary

When I press f5 to open the debug menu, the fps first says about 60fps but immediately decreases to about 40 to 32 fps. This was not the case in previous development builds. I have confirmed that it happens in both single player and multiplayer when running the default minetest game with no mods enabled.

### Steps to reproduce

You should be able to replicate it by opening the debug menu.

**Comment by Zughy** [comment]
Hello, could you bisect to find the commit?

**Comment by DustyBagel** [comment]
I don't know what that means or how to do that.

**Comment by DustyBagel** [comment]
I looked up how to do the git bisect thing that Zughy asked me in this issue, and I got to the part where you type in the git bisect good/bad commands and I tried to set the good commit with this command "git bisect good 26bb397" and it isn't working. I am getting this error message "fatal: Bad rev input (not a commit): 26bb397" Can someone help me fix this so that I can find out which commit is causing this issue?

**Comment by Desour** [comment]
Make sure you've cloned the whole git history, i.e. without `--depth=1`.

Also, note that you have to rebuild (`make -j...`) after each bisect step.
You'll also have to checkout the correct irrlichtmt version (see `misc/irrlichtmt_tag.txt`).

**Comment by DustyBagel** [comment]
> Make sure you've cloned the whole git history, i.e. without `--depth=1`.
> 
> Also, note that you have to rebuild (`make -j...`) after each bisect step. You'll also have to checkout the correct irrlichtmt version (see `misc/irrlichtmt_tag.txt`).

I tried again, this time cloning it without the --depth=1 argument and I tried adding the good and bad commits and it worked this time. Do I have to clone irrlichtmt this way too? I also don't know how to "rebuild (make -j ...). I also don't know how to check out the correct version of  irrlichtmt or how to make sure I am getting the right version.

**Comment by Desour** [comment]
>Do I have to clone irrlichtmt this way too? I also don't know how to check out the correct version of irrlichtmt or how to make sure I am getting the right version.

Yes.
After that you can use `git checkout 1.9.0mt<num>` (in the irrlichtmt path) to checkout the correct tag, if it doesn't compile.

> I also don't know how to "rebuild (make -j ...).

(Sorry, I shouldn't have assumed you use `make`.)
See here for compiling: https://github.com/minetest/minetest/tree/master/doc/compiling
To rebuild you have to do `cmake --build`.

**Comment by DustyBagel** [comment]
I am actually familiar with compiling minetest with cmake however I usually use the cmake gui instead of the command line. I went through the whole git bisect process. but didn't find the commit causing the issue. This has led me to believe that I didn't do it correctly. I have confirmed that both the good commit that I stated it with does in fact not have the issue and that the bad commit that I stated with does. I can go into more details about what I did if necessary. I did notice that the fps drops got slightly better the further back I went in minetest commits.

**Comment by DustyBagel** [comment]
I just downloaded the 5.8.0 release from minetest.net and I didn't notice the fps drop. I have noticed it on my release build of minetest 5.8.0 though. Also, can you guys fill me in on what is going on here? Are you still waiting for me to find the commit that is causing the problem or are you trying to fix it yourselves? I will try rebuilding minetest and see if the issue persists.

**Comment by rollerozxa** [comment]
When you're building from source on Windows are you using MSYS2 (or some other environment providing MinGW) or MSVC? If latter, https://github.com/minetest/minetest/issues/13399#issuecomment-1852421286 is probably related. The official builds use MinGW and don't seem to have this FPS drop issue.

**Comment by DustyBagel** [comment]
I don't know. I use cmake visual studio and vcpkg as a package manage.

**Comment by rollerozxa** [comment]
Yes, that's MSVC.

**Comment by DustyBagel** [comment]
Arleigh so do you need anything on my end?

**Comment by grorp** [comment]
> Arleigh so do you need anything on my end?

No, I think not. I suppose this is now confirmed by @srifqi through https://github.com/minetest/minetest/issues/13399#issuecomment-1852421286.

**Comment by sfan5** [comment]
Worth checking if this is perhaps caused by 3a4bf14c20161c0ffe07460665375e3b451ef3a6.

**Comment by srifqi** [comment]
> Worth checking if this is perhaps caused by 3a4bf14c20161c0ffe07460665375e3b451ef3a6.

Reverting 3a4bf14c20161c0ffe07460665375e3b451ef3a6 and minetest/irrlicht@f725b68c5738764ae9e4a7c7df05ab99de073e29 does fix the issue.

**Comment by sfan5** [comment]
Can you check if it's `convertWCharToU32String` taking the extra time?

**Comment by srifqi** [comment]
In a one minute run with debug info shown, the `irr::gui::CGUITTFont::convertWCharToU32String` function takes around 89% of the CPU time.

![Flame graph of the test](https://github.com/minetest/minetest/assets/4017302/d198334d-173b-439e-942c-a332a38c86e2)
