### ISSUE TITLE
Rename "Client" and "Server" tabs to "Connect" and "Host" respectively

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1400]
Its a bit less confusing, as new players often open the server one first because they want to connect to a "server"

**Comment by paramat** [comment]
:-1:

**Comment by rubenwardy** [comment]
My brother is 14 and had no idea what it meant by "client" and "server". They're very techy terms.

**Comment by celeron55** [comment]
I switched away from "client" and "server" in my main menu experiments (#3818). I think it would be better exactly because regular users have absolutely no idea what "client" means. Not sure about exact new names for them though.

**Comment by C1ffisme** [comment]
@rubenwardy Um... I'm 14 and I know what they mean. (I probably have known for a while... They aren't too hard to learn.)

Anyway, :+1: for this. It's a pretty good idea for people who aren't really geekish.

**Comment by paramat** [comment]
I misjudged this one, removed label.

**Comment by SmallJoker** [comment]
Most likely solved by #5627.

**Comment by iqualfragile** [comment]
can confirm, this is resolved
