### ISSUE TITLE
Why is there `set_nametag_attributes`?

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#14008]
I've just noticed that there's a `set_nametag_attributes` and `get_nametag_attributes` for ObjRefs.
Looking at the implementation, it just sets the respective object properties. So, is there a reason why we need it, when modders can use `set_properties` instead? Should we deprecate?

**Comment by SmallJoker** [comment]
This feature was originally implemented separate to the object properties and later merged in 9eee3c3f4.
There surely are mods that make use of this API but marking it as deprecated is something I would agree to.

**Comment by appgurueu** [comment]
Such "more specific" setters can technically have a small performance advantage: `set_properties` has to check for all object properties, `set_nametag_attributes` only has to deal with the nametag related ones. Back-of-the-napkin math suggests this doesn't make much of a difference however. Optimizing `set_properties` to iterate the table might also be an option.

I don't see a significant benefit to a deprecation either, though. This API is unlikely to need to be extended or to be a source of bugs in the future.
