### ISSUE TITLE
Avoid including client headers on server builds

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14005]
If you try to compile 5.7.0 server-only right now you would get this:
```
[  0%] Building CXX object src/CMakeFiles/minetestserver.dir/script/cpp_api/s_security.cpp.o
In file included from /tmp/minetest/src/client/particles.h:24,
                 from /tmp/minetest/src/client/client.h:34,
                 from /tmp/minetest/src/script/cpp_api/s_security.cpp:25:
/tmp/minetest/src/client/tile.h: In member function 'void TileLayer::applyMaterialOptions(irr::video::SMaterial&) const':
/tmp/minetest/src/client/tile.h:237:34: error: 'class irr::video::SMaterial' has no member named 'TextureLayer'; did you mean 'TextureLayers'?
  237 |                         material.TextureLayer[0].TextureWrapU = video::ETC_CLAMP_TO_EDGE;
      |                                  ^~~~~~~~~~~~
      |                                  TextureLayers
```

Now this is an unfortunate case where we changed the names in Irrlicht but more importantly what is `src/client/tile.h` doing in a server build?

### What I would do

Go through some client headers and add the following:
```c
#ifdef SERVER
#error Wrong include
#endif
```
then see what needs to be done to avoid the errors.

**Comment by sfan5** [comment]
(context: #14003)

**Comment by erlehmann** [comment]
Maybe a weird question, but would the way this separation is planned to go ultimately mean that the minimap color of a node could never be exposed on the server-side because all of that code is supposed to be purely client-side? (Minimap color is not exposed right now, I just want to know if there is some path dependency here.)

**Comment by hecktest** [comment]
> Maybe a weird question, but would the way this separation is planned to go ultimately mean that the minimap color of a node could never be exposed on the server-side because all that code is supposed to be purely client-side? (Minimap color is not exposed right now, I just want to know if there is some path dependency here.)

Probably not, because Irrlicht does the texture management and the minimap color (likely) comes from textures. Server builds don't even link image decoders last time I checked.
