### ISSUE TITLE
Small entity collision boxes are not always pointed at

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1401]
![Rat](https://cdn.mediacru.sh/4bvEnVKiYyR9.jpg)

The node behind will instead be pointed; this is maybe due to some commit that fixed entities being pointed when nodes should be, through walls.

This is the collision box used by the rat:
```Lua
collisionbox = {-0.25, -0.01, -0.25, 0.25, 0.35, 0.25},
```

**Comment by RobertZenz** [comment]
I can't reproduce this with the latest HEAD, at least not with nodes. I can point at them just fine with this collision box.

**Comment by paramat** [comment]
@Calinou still an issue?

**Comment by Calinou** [comment]
It appears to no longer occur in latest Minetest revisions (tested on https://github.com/minetest/minetest/commit/0fde86dd93d77ad3ff2662a049eeb90ad432575e).
