### ISSUE TITLE
Remove the lua_api.txt

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#14012]
### Problem

When you look up "minetest lua api" on google it goes to 
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt
Could we remove this? It's still getting traffic even though the link is duct taped in there

### Solutions

Remove that .txt file

### Alternatives

Cry as google locks it in as the minetest lua api forever

### Additional context

![image](https://github.com/minetest/minetest/assets/1088750/91aca012-10a5-4afb-95ae-8f0d972c96c0)
![image](https://github.com/minetest/minetest/assets/1088750/5d1b48c9-302c-466c-8a20-1f357380fabf)

**Comment by Zughy** [comment]
Pretty sure we can't, or the old links would result all broken. I don't know if GH allows redirects but I doubt it

**Comment by SmallJoker** [comment]
GitHub does redirect renamed/moved projects but files that were moved within git. It is better to end up at a file to redirect the users rather than an even less helpful Error 404 page. DuckDuckGo for example already links to the markdown version. It is only a matter of time until Google (or rather its users) learn to pick the correct match.

**Comment by jordan4ibanez** [comment]
> GitHub does redirect renamed/moved projects but not individual files that were moved within git. It is better to end up at a file to redirect the users rather than an even less helpful Error 404 page. DuckDuckGo for example already links to the markdown version. It is only a matter of time until Google (or rather its users) learn to pick the correct match. 👎

I certainly would, if it showed up at all

**Comment by Bituvo** [comment]
I would recommend reporting that the Google search result is outdated.

1. Click the three dots next to the URL
2. Click "Remove result"
3. Click "It's outdated"
