### ISSUE TITLE
player:add_pos(vector) relative teleport

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#14023]
### Problem

Right now, to teleport a player, this is achieved using player:set_pos(), and it works okay for low latency conditions.  However, there are cases where a player may have moved since the position to teleport them was determined, and I would like that relative movement to be added to the destination, e.g. the player walks into a "portal" and into a "fake" scene duplicating the teleport destination, and when they finally receive the teleport packet and move to the destination area, I want the transition to be seamless.

Since we have player:add_velocity() that allows layering the change on top of client-side physics, it only seems consistent to do this for add_pos() as well.

### Solutions

I would like there to be (at least) a `player:add_pos(vector)` API.  Like add_velocity, when the client receives this packet it should add the vector to the player's current position, regardless of how that position may have changed since the packet was sent (it's the modder's responsibility to ensure this makes sense under lag conditions).

Ideally, this would be a generic `object:add_pos(vector)` function that would work on players and lua entities alike, allowing other non-player objects to make relative jumps as well, layered on top of client-side kinematic prediction.  If it's too much work to implement it for objects in general, however, then it's fine to skip that, as it's really players (who can move arbitrarily and will REALLY notice if the teleport is not smooth) that matter.

### Alternatives

Haven't thought of any.  The fact that we already have the set_velocity/add_velocity duality makes the above approach seem pretty obvious.

### Additional context

Example use-cases:

- The IKEA game, while it was still under active development, wanted to make their world _truly_ infinite by having repeatable mapgen and having players teleport to loop around at the edges (and some dummy terrain and "hologram" entities could be used to display other players and entities past the edges).  This feature would have been really useful to make that seamless, otherwise players would notice  jarring transition.
- The Piranesi game goes to considerable lengths and has a ton of hacks to replace terrain *because* it can't just teleport the player; if teleporting the player seamlessly like this were possible, it would enable a massive simplification of the game's inner workings, and even enable basically full multiplayer support, which is impossible right now.
- I'm working on a new mod for NodeCore around a space bending theme, and it involves the use of similar portals.  The teleport transition could be made smoother, and a lot of the code simplified a lot, if I had player:add_pos().

**Comment by Warr1024** [comment]
Looking into the network protocol a little, I see there's a TOCLIENT_MOVE_PLAYER packet, which contains a new pos, pitch, and yaw; apparently these are always sent together in this same packet.

We could create a new packet type for relative teleports, but the problem with this is that for legacy clients that don't support the new packet, nothing would happen and the movement would simply fail.

A simpler approach might be to take advantage of the fact that IIRC MT allows additional info at the end of the packet and ignores anything it doesn't support.  When doing a plain set_pos(), send the packet the way it is now (pos, pitch, yaw), but when doing add_pos(), send (pos, pitch, yaw, oldpos), with oldpos containing the position that the server thinks the player is being moved _from_.  Then, if the cilent sees this extra oldpos parameter, instead of setting the position to the new pos, it sets it to new pos - oldpos + current_client_side_pos.

By reusing the TOCLIENT_MOVE_PLAYER packet, we get the desired behavior for new clients, but legacy clients fall back on a sane behavior (as if the server had used set_pos() and ignored client position) instead.

**Comment by sfan5** [comment]
> but the problem with this is that for legacy clients that don't support the new packet, nothing would happen and the movement would simply fail.

You could also check the protocol version and fall back to sending a MOVE_PLAYER to old clients.

**Comment by sfence** [comment]
@Warr1024 Are you able to check if pull request #14126 does, what you expected?

To work well, both the client and server have to be compiled from #14126 source.

**Comment by sfence** [comment]
This issue has been fixed by PR#14126 and can be closed.
