### ISSUE TITLE
Minetestserver.exe will not open when multiple worlds are in the worlds directory

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest#14025]
### Minetest version

```true
Minetest 5.8.0-dev-aa912e90a
```

### Active renderer

OpenGL 4.6.0

### Irrlicht device

win32

### Operating system and version

Windows 10 Home 22H2

### CPU model

11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz

### GPU model

Integrated CPU graphics

### OpenGL version

4.6.0

### Summary

When multiple worlds are in the worlds folder in minetest, the minetestserver.exe will open then close really quickly.  I unfortunately noticed this problem a while back but didn't have a GitHub account at the time to report it, so this isn't a new problem. Sorry about that.

### Steps to reproduce

You should be able to reproduce this by creating two worlds and trying to open the minetestserver.exe file.

**Comment by rollerozxa** [comment]
You need to specify one of them as an argument (with `--worldname` or similar)

**Comment by sfan5** [comment]
Working as designed. That you can launch `minetestserver` just by double-clicking when there's only one world is a lucky coincidence.

**Comment by DustyBagel** [comment]
Isn't the minetestserver.exe supposed to open and then you type in the arguments that you want it to use like the world name and then it starts the server?
