### ISSUE TITLE
Music should stop when changing window

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14026]
### Problem

If you're playing, for instance, a game with background music and you change window, the music keeps playing. If I'm changing window, I'm probably doing something not related to the game, possibly that requires me to focus and detach from the game, thus I expect it to stop

### Solutions

Make it stop

### Alternatives

Ask people to press M every time (?)

### Additional context

I'd consider this a bug but the bug form is off-putting  

EDIT: I'll let core devs decide

**Comment by Desour** [comment]
Other games have a setting for this (ddnet for example).
We should also have such a setting.
Unconditionally muting sounds when unfocused would be bad for players that still want to enjoy the game's music while unfocused.

**Comment by Zughy** [comment]
@Desour agreed. I think that muting should be the default though

**Comment by NathanSalapat** [comment]
Should probably be another feature request, but shouldn't the game also pause when the window looses focus?

**Comment by Desour** [comment]
> Should probably be another feature request, but shouldn't the game also pause when the window looses focus?

Indeed a different feature request.
(And imho not too useful, because I at least usually open pause menu first to get my mouse cursor free. If I want to not pause the game, I specifically open inv or chat first, this doesn't happen by accident for me.)

**Comment by jordan4ibanez** [comment]
I'm pretty sure that the program api can infer if the window is focused. Perhaps in the soft openal implementation at the root when it tries to play sounds it can simply do something like ```c++
if (!this->focused) {
  return;
}
// Rest of procedure
```

**Comment by rubenwardy** [comment]
@NathanSalapat @Desour this is already supported. Set `pause_on_lost_focus` to true

**Comment by Athozus** [comment]
It must be a setting. Example of use case: I'm often waiting for train and I go on another window until I hear a train is coming. I would not like to stay on my screen doing anything for several minutes, at least most than just muting the sound of my window. I understand that's annoying, but the balance is in favor of, by default, enable the sound.

**Comment by srifqi** [comment]
I like the approach of [osu!lazer](https://lazer.ppy.sh) (a rhythm game) which has two master volume settings: one for the main master volume and another for the master volume when the window is inactive. This gives players more flexibility in setting sound volume (which can be zero/no-sound).

Except the audio offset setting, other settings shown below are in their default value:

![osu!lazer audio settings](https://github.com/minetest/minetest/assets/4017302/d700d8f4-3fe1-4d03-9bbb-7fca19e98cb5)
