### ISSUE TITLE
`Settings::getV3F()` and `minetest.setting_get_pos()` have inconsistant parsing

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#14033]
### Minetest version

```true
Minetest 5.8.0-dev-debug-79cc71851-dirty (Linux)
Using Irrlicht 1.9.0mt12
Using LuaJIT 2.1.1692716794
BUILD_TYPE=Debug
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Operating system and version

Fedora 39

### Summary

`Settings::getV3F()`:

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/src/settings.cpp#L563-L566

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/src/util/string.cpp#L902-L911

`minetest.setting_get_pos()`:

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/builtin/game/misc_s.lua#L42-L48

https://github.com/minetest/minetest/blob/6783734612832bd6a25adc3ddcd32f6a12c89249/builtin/common/misc_helpers.lua#L430-L446

---

Basically the C++ function only handle values like this: `(1, 2, 3)` while the Lua function handle also values like `1, 2, 3`.

C++ function should support both notations IMO.

### Steps to reproduce

Run some C++ code like this in the server context with `static_spawnpoint = (1, 2, 3)`:

```cpp
auto v = Settings::getV3F("static_spawnpoint");
warningstream << v.X << ", " << v.Y, ", " << v.Z << std::endl;
```

See that the values are printed to warning stream correctly. Check with `/kill` in devtest that the static spawn point works.

Set `static_spawnpoint = 1, 2, 3`. Try running the C++ code again and see `0, 0, 0` as output. Check again that static spawn point works in devtest. 

---

By the way, why is the spawnpoint handeled by C++ AND Lua? The Lua callback will always handle it I think.

https://github.com/minetest/minetest/blob/03ba9370b951f1c0904b53dfac3f5daf0bb354d6/src/server.cpp#L2846-L2865

https://github.com/minetest/minetest/blob/03ba9370b951f1c0904b53dfac3f5daf0bb354d6/src/server.cpp#L3791-L3796

https://github.com/minetest/minetest/blob/ade7a1cbcf7156ebddb12bd2ec2ea60818d72b19/builtin/game/static_spawn.lua#L3-L23

**Comment by AFCMS** [comment]
I managed to get the two values formating are handled by C++:

```cpp
v3f str_to_v3f(const std::string &str)
{
	v3f value;
	Strfnd f(str);
	//f.next("(");
	f.skip_over("(");
	value.X = stof(f.next(","));
	value.Y = stof(f.next(","));
	value.Z = stof(f.next(")"));
	return value;
}
```

**Comment by AFCMS** [comment]
Fixing this bug is more or less required for https://github.com/minetest/minetest/issues/6062 (that I was trying implementing)

**Comment by appgurueu** [comment]
You are right, they are inconsistent. I'd agree that settings should probably also support the "parenthesis-less" notation for convenience and consistency.

It might be cleanest to rewrite this using C++ regex.

**Comment by AFCMS** [comment]
I can probably take care of this.
