### ISSUE TITLE
model format: (.m3d)

### ISSUE THREAD

**Issue by Pantyhose-X** [minetest/minetest#14032]
### Problem

 .b3d .obj format flaw, My suggested modern format [.m3d](https://gitlab.com/bztsrc/model3d)

### Solutions

> ### .m3d Features
> 
> * the format is freely usable, MIT licensed (unlike .PBX, .MAX or .C4D)
> * also has an [ASCII](https://gitlab.com/bztsrc/model3d/blob/master/docs/a3d_format.md) representation for exchange and easy debugging (unlike .BLEND or .B3D, similar to .OBJ but with skeletal animation support)
> * stores exactly one model with all its aspects, but nothing else (unlike .FBX, .X3D, .BLEND; just like .PLY)
> * has the biggest information density of all the formats (a cube can be stored in as little as 119 bytes)
> * can store huge number of vertices in magnitude of billions (unlike .3DS)
> * can store color maps as well as texture maps and materials
> * can store inlined textures (ideal for model distribution)
> * can store precise normal vectors, not just smoothing groups (unlike .3DS)
> * can store [voxel](https://gitlab.com/bztsrc/model3d/blob/master/docs/voxel_format.md) images, polygon mesh, procedural surfaces and procedural textures\*
> * can store parameterized mathematical surfaces, like [NURBS](https://gitlab.com/bztsrc/model3d/blob/master/docs/shape.md) (and other [CAD](https://gitlab.com/bztsrc/model3d/blob/master/docs/CAD.md) information)
> * can store skeleton based animations (unlike .MD3, which uses vertex morph only, or .MD5 which has separate files for anims)
> * can store actions, several named animation frames within the same file
> * can store model with absolute scaling factor and face thickness for 3D printing (is there any format that can do these?)
> * utilizes engine agnostic data structure, focuses on storing what's relevant for the model representation, not for the engines
> * supports material libraries in separate files if needed (using the same format)
> * expandable in nature, additional information can be easily added if needed without breaking compatibility with other applications
> * flexible data types (similar to .PLY, but much simpler, coordinate precision from 8 bits to 64 bits (*int8_t* to *double*))
> * compact file size, damn easy to interpret without third-party libraries\*\* (\~80 SLoC see below, unlike .FBX, .X3D, .glTF or .X)
> * the SDK follows the K.I.S.S. principle, MIT licensed just as the format itself, easy to integrate into any project
> 
> (\* - you provide a script interpreter callback for the SDK, so you can [use any scripting language](https://gitlab.com/bztsrc/model3d/blob/master/docs/procedural.md) you like, eg. Lua, Python, whatever)
> 
> (\*\* - the model's data may be stream compressed, however a) this is optional, and b) the SDK has a built-in decompressor. You won't need any third-party libraries to use the SDK, like JSON or XML libraries, libpng, zlib etc. it is dependency-free.)Features
>               https://gitlab.com/bztsrc/model3d

### Alternatives

glTF

**Comment by wsor4035** [comment]
please comment under https://github.com/minetest/minetest/issues/9673
