### ISSUE TITLE
`player:hud_get(id)` returns a table with `type` instead of `hud_elem_type`

### ISSUE THREAD

**Issue by cx384** [minetest/minetest#14043]
The problem is here:
https://github.com/minetest/minetest/blob/771da80bbb85c9fa4f0dcf0f3d04f46a0a20239f/doc/lua_api.md?plain=1#L10026-L10030
https://github.com/minetest/minetest/blob/771da80bbb85c9fa4f0dcf0f3d04f46a0a20239f/src/script/common/c_content.cpp#L2018

Either `hud_elem_type` should be made deprecated  for `hud_add(id)` and replaced by `type`, or the documentation should be changed, since it is wrong.

I can fix this, if I get confirmation that it is fine to make `hud_elem_type` deprecated.

### Minetest Version
```
Minetest 5.8.0-dev-debug-61db32b-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1700008891
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Steps to reproduce
Execute this:
```
local add_def = {
   hud_elem_type = "text",
   name = "test",
   position = {x = 0.5, y = 0.5},
   text = "test"
}
local id = player:hud_add(add_def)
local get_def = player:hud_get(id)
print(dump(get_def))
```
And notice the `type` field.

**Comment by appgurueu** [comment]
I am in favor of making `hud_elem_type` deprecated in favor of `type`. Of course we'll have to support `hud_elem_type` for a while...
