### ISSUE TITLE
Error on password but passwords right

### ISSUE THREAD

**Issue by DadofB** [minetest/minetest#14046]
Issue is, on another device. Joining a game, having the right password but errors saying invalid password. Over and over till it’s locked out
![IMG_8295](https://github.com/minetest/minetest/assets/152097791/1a4405e0-ef1f-4298-8ac5-74c4da611b27)
![IMG_8296](https://github.com/minetest/minetest/assets/152097791/de934d15-1b7d-4404-ab4d-8f75073e3c5b)

**Comment by rubenwardy** [comment]
Hi, this is Minetest not Multicraft. Please contact Multicraft for support or switch to an official Minetest build
