### ISSUE TITLE
ParticleSpawner (and maybe sound) IDs Reused

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#14044]
### Minetest version

```true
Minetest 5.8.0-dev-70261b8e9 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL 4.2

### Irrlicht device

X11

### Operating system and version

Debian 12

### CPU model

Intel i5-3320M (4) @ 3.300GHz

### Summary

Particle spawner IDs are aggressively reused, which can lead to deleting the wrong particle spawner.

It looks like the "ID" that MT returns for a particle spawner is not actually a unique identifier for that spawner, but an address (i.e. index of an array).  So if I create particle spawner X and it gets assigned ID 3, then when I later call delete_particlespawner(3) I am not actually saying "delete particle spawner X", I'm unwittingly saying "delete whatever particle spawner currently occupies index 3".  If X had already been deleted for some other reason (expiry, deletion by some other mod) then some other arbitrary particle spawner may now occupy that slot and be deleted instead.

The correct thing to do would be to use a unique value for each resource.  A mapping of resource unique ID to address could be maintained in the engine.

Ideally the resource identifiers would be opaque to Lua (e.g. userdata) to prevent users from attempting to rely on the content/structure of the values, or to try to serialize and store them, or try to fabricate them.

### Steps to reproduce

**WARNING**: Do **NOT** attempt to test this against NodeCore version `02673309-161dcfb0` or later, as there is already a workaround present that makes the bug unreproducible.

Install this mod code into a worldmod:

```lua
do
	local theta = 0
	local function fx()
		minetest.after(0.25, fx)

		-- singleplayer only
		local players = minetest.get_connected_players()
		local player = players[next(players)]
		if not player then return end

		local pos = player:get_pos()
		pos.y = pos.y + player:get_properties().eye_height
		local look = player:get_look_dir()
		local vert = vector.new(0, 1, 0)
		local horz = vector.cross(look, vert)
		vert = vector.cross(look, horz)
		theta = theta + math.pi / 8
		local targ = vector.add(pos, vector.multiply(look, 5))
		targ = vector.add(targ, vector.multiply(horz, math.sin(theta) * 3))
		targ = vector.add(targ, vector.multiply(vert, math.cos(theta) * 3))

		minetest.add_particlespawner({
				time = 1,
				amount = 50,
				minexptime = 0.5,
				maxexptime = 0.5,
				minpos = vector.offset(targ, -0.5, -0.5, -0.5),
				maxpos = vector.offset(targ, 0.5, 0.5, 0.5),
				minsize = 1,
				maxsize = 1,
				texture = "[combine:1x1^[noalpha",
			})
	end
	minetest.after(0, fx)
end
```

Stand still while looking out into open air, and observe that now a cloud of black particles will revolve around the center of the player's view.  This cloud is "smooth" and has no obvious gaps.

Now, add this code to a worldmod (it doesn't matter if it's in the same or different mod):

```lua
do
	local oldid
	local function fx()
		minetest.after(math.random() * 2, fx)

		-- singleplayer only
		local players = minetest.get_connected_players()
		local player = players[next(players)]
		if not player then return end

		local pos = player:get_pos()
		pos.y = pos.y + player:get_properties().eye_height
		pos = vector.offset(pos, math.random() * 10 - 5, math.random() * 10 - 5,
			math.random() * 10 - 5)
		if oldid then minetest.delete_particlespawner(oldid) end
		oldid = minetest.add_particlespawner({
				time = 1,
				amount = 50,
				minexptime = 0.5,
				maxexptime = 0.5,
				minpos = vector.offset(pos, -0.5, -0.5, -0.5),
				maxpos = vector.offset(pos, 0.5, 0.5, 0.5),
				minsize = 1,
				maxsize = 1,
				texture = "[combine:1x1^[noalpha^[invert:rgb",
			})
	end
	minetest.after(0, fx)
end
```

This will add a cloud of white particles that randomly teleports around the player.

Note that the black particle cloud "clock" will now have visible gaps in it, even though:
- The black particle effect was never modified, nothing it created was publicly accessible, and it never used delete_particlespawner
- The white particle effect code never deleted any particlespawner ID that it wasn't given by the API.

Note that the gaps may be subtle and difficult to differentiate against just the randomness of particle distribution in the cloud, but you an definitely see the difference in smoothness if you watch for a while and compare against the case without the teleporting white clouds.  Some of the black cloud particlespawners are getting deleted *too early*.

**Comment by Desour** [comment]
For sound ids, there was this: #12780 (Not merged.)

**Comment by sfan5** [comment]
Note that not reusing IDs doesn't get rid of the race condition, it just makes the window so big that it practically doesn't matter.
The actual issue is that these IDs "expire" without the Lua side having any way to tell.

**Comment by Warr1024** [comment]
Also if the IDs are expired, even if some part of the Lua side is told, there's no way to effectively guarantee that everywhere the ID ended up in the Lua side is clear about the reuse.

It's also somewhat unnecessary to require that the Lua side be responsible for dealing with this when it's easily dealt with centrally by either engine or builtin. If I attempt to delete a handle that's expired, even if I reasonably should have known that it did, there's no reason I need to be punished by having some other arbitrary resource deleted instead; it would be perfectly reasonable to just do nothing.

**Comment by Wuzzy2** [comment]
> [...] that would make it a lot simpler for me to detect the fixed version and bypass the workaround cache.

The easiest method to "detect" the fixed version is when the bugfix also adds a field to the `minetest.features` table.
