### ISSUE TITLE
water opacity bug with irrlicht 1.8.x

### ISSUE THREAD

**Issue by stormchaser3000** [minetest/minetest#1404]
http://imgur.com/HlmYh0T.png

so far i have noticed that this only happens on irrlicht 1.8.x but when i used irrlicht 1.7.x the water opacity worked perfectly

**Comment by BlockMen** [comment]
Another report: https://forum.minetest.net/viewtopic.php?f=6&t=13397

**Comment by Fixer-007** [comment]
fefa148 also has this problem, i've catched when shaders are enabled, I also feel like it depends on time of day. Please consider looking at that annoying bug.

![x4rb74b](https://cloud.githubusercontent.com/assets/16494741/13029821/5b9e831a-d29f-11e5-8953-fb81bcf8f6ce.png)

**Comment by HybridDog** [comment]
l'm not sure, the opaque water uses node_shader and the other one the water_shader.

**Comment by Fixer-007** [comment]
Update on this: http://irc.minetest.ru/minetest-dev/2016-02-14#i_4533553

**Comment by paramat** [comment]
@Fixer-007 

> Edit: problems with random water opacity on my screenshots below are fixed by c3b2797.
Note: another water rendering bugs mentioned in that issue are not fixed yet

So the water opacity bug is fixed? If so this can be closed, the tiles appearing in water columns are a different issue and should have a seperate issue made @HybridDog

**Comment by Fixer-007** [comment]
@paramat do not close, not all opactity bugs were resolved.

**Comment by paramat** [comment]
Ok, it wasn't clear.

**Comment by nerzhul** [comment]
@Fixer-007 i think it's fixed, can we close it ?

**Comment by nerzhul** [comment]
discussed with paramat i think it's related to the double shading on water. Should be fixed now

**Comment by paramat** [comment]
> l'm not sure, the opaque (because of bug) water uses nodes_shader and the other one the water_surface_shader.

Might be fixed now that the duplicate 'water surface shader' has been removed, default:water_source top tiles only were being sent to that.
