### ISSUE TITLE
Fast-move Rubber-banding Regression

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#14061]
### Minetest version

```true
Minetest 5.8.0-dev-6106e4e72-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL 4.2

### Irrlicht device

X11

### Operating system and version

Debian GNU/Linux 12 (bookworm) x86_64

### CPU model

Intel i5-3320M (4) @ 3.300GHz

### Summary

This appears to be a regression of a previously fixed miscalculation in the anti-cheat system.  It was supposed to allow the player to move as fast as allowed by in-game rules, including physics overrides, with a sufficient margin of error to account for lag, but it no longer works correctly.

Bisect identified the culprit as https://github.com/minetest/minetest/commit/8ebaf753d3c6b50028d097db924a887d98602c18 (New physics overrides).

This effect has been observed on both SP and MP servers, including servers in the wild running 5.8.0-dev.  It doesn't seem to matter whether the terrain is being generated fresh, loaded from disk, or already in memory (not affected by emerge workload).  I'm observing it on very lightly-loaded systems.

### Affected Games

This appears to affect any game that sets a higher player physics_override speed.

**NodeCore** is affected out of the box.

**MTG** and **DevTest** are not affected, but can be by adding a mod:

```lua
minetest.register_on_joinplayer(function(player)
  player:set_physics_override({speed = 2.5})
end)
```

### Steps to reproduce

1. Create a new NodeCore world, or world for another game that sets player speed physics_override.
2. /grantme fast,fly,noclip
3. Start flying around in wide circles (maybe like 80 diameter).

### Expected

- Nothing unusual, you just fly around in circles.

### Observed

- After a while (a few seconds to a minute) you will start getting position resets and "stuttering" movement, and your actual speed of progress will slow down significantly.

**Comment by sfan5** [comment]
> This effect has been observed on both SP and MP servers

Anti-cheat calculations are disabled in singleplayer so this doesn't match up.
