### ISSUE TITLE
F-Droid - mark app as `NonFreeNet` 

### ISSUE THREAD

**Issue by licaon-kter** [minetest/minetest#14078]
Since https://github.com/minetest/minetest/pull/13818 the installed app will not do anything since there's no actual game content included to be able play, forcing the users to connect to `content.minetest.net`

ref: https://github.com/minetest/minetest/releases/tag/5.8.0

> Note to package maintainers: Please remove Minetest Game from your packages, as it should no longer be installed by default.

**Comment by rollerozxa** [comment]
Is this still considered an antifeature if the content browser only contains freely licensed packages? We do have an exception for nonfree -NC licensed content, but this is filtered out from the client so only free content is available.

**Comment by rubenwardy** [comment]
The source code for ContentDB is available here: https://github.com/minetest/contentdb/

Minetest only shows FOSS packages by default, you need to change a setting to show non-free content

**Comment by licaon-kter** [comment]
> ContentDB is not a non-free network service. The source code for ContentDB is available here: https://github.com/minetest/contentdb/

It's not about that

> You can change the instance you use with the contentdb_url setting

Settings -> User Interfaces -> ContentDB URL indeed, I missed this

Thanks

**Comment by licaon-kter** [comment]
Would the team be ok if F-Droid compiles without `nonfree` here https://github.com/minetest/minetest/blob/5.8.0/src/defaultsettings.cpp#L341 ?

**Comment by rubenwardy** [comment]
> Would the team be ok if F-Droid compiles without `nonfree` here [`5.8.0`/src/defaultsettings.cpp#L341](https://github.com/minetest/minetest/blob/5.8.0/src/defaultsettings.cpp?rgh-link-date=2023-12-06T13%3A19%3A43Z#L341) ?

This would show nonfree content by default. That's fine by me.

I suspect you want to hardcode not showing nonfree stuff. In which case, you could add `&hide=nonfree` to here: https://github.com/minetest/minetest/blob/master/builtin/mainmenu/content/dlg_contentstore.lua#L635
