### ISSUE TITLE
Select locale based on locale(language) in android 

### ISSUE THREAD

**Issue by RedMatrix1** [minetest/minetest#14081]
### Problem

It’s a little inconvenient to constantly change the language after reinstalling the game, for example to Spanish or Russian 

### Solutions

Make the game automatically detect the system locale

### Alternatives

The only option is above

**Comment by rollerozxa** [comment]
This is already done in 5.8.0.

**Comment by grorp** [comment]
> This is already done in 5.8.0.

Yes, this was fixed by #13561. The fix is included in the 5.8.0 release. If you have installed Minetest from Google Play, you should get the update soon.

**Comment by RedMatrix1** [comment]
> Yes, this was fixed by #13561. The fix is included in the 5.8.0 release. If you have installed Minetest from Google Play, you should get the update soon

I've updated I have russian because I update engine.
