### ISSUE TITLE
Translation script: running it with -p flag changes slashes orientation between Windows and Linux

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14089]
### Minetest version

```true
latest script version
```

### Summary

See https://gitlab.com/zughy-friends-minetest/arena_lib/-/merge_requests/63/diffs?commit_id=943aae56fa975480534206133538726d8d315bc7 as an example. I've used Git Bash on Windows

### Steps to reproduce

1. Run the translation script on Linux with -p flag: `##[ foo/bar.lua ]##`
2. Run the same script for the same mod on Windows, always with -p
3. All the file strings have been changed into `##[ foo\bar.lua ]##`

**Comment by srifqi** [comment]
Since URLs also use forward-slash (`/`), we can use that instead (same as Unix/Linux path).

Possible fix:
```diff
diff --git a/util/mod_translation_updater.py b/util/mod_translation_updater.py
index 1d5ca9239..c941331a8 100755
--- a/util/mod_translation_updater.py
+++ b/util/mod_translation_updater.py
@@ -425,6 +425,7 @@ def generate_template(folder, mod_name):
 		sources = sorted(list(sources), key=str.lower)
 		newSources = []
 		for i in sources:
+			i = "/".join(os.path.split(i)).lstrip("/")
 			newSources.append(f"{symbol_source_prefix} {i} {symbol_source_suffix}")
 		dOut[d] = newSources
 
```

**Comment by Zughy** [comment]
I confirm that this does fix the issue (tested on Windows)
