### ISSUE TITLE
Stable build crashes before title in Win7 x32, Irrlicht or dll issue

### ISSUE THREAD

**Issue by vichoca9** [minetest/minetest#14102]
### Minetest version

```true
Minetest 5.8.0 (Windows)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Windows 7 x32 SP1

### CPU model

Intel Atom N2600 @1.60Ghz

### GPU model

 Intel(R) Graphics Media Accelerator 3600 Series

### OpenGL version

3.0

### Summary

Running the stable 5.8 branch results in a APPCRASH event with errors on IrrlichtMt.dll, with exception code c0000005. It seems a dll issue (manually compiling with mingw results in a stdc++6 symbol error, so maybe current dlls dont support Win7?)

### Steps to reproduce

Download 5.8.0 win32 zip and run minetest.exe in a Windows 7 x32 machine.

Note: 5.7.0 runs with no issue.

**Comment by wsor4035** [comment]
> Works on Windows 8, 8.1 and 10. May work on older versions, but not officially supported.

https://www.minetest.net/downloads/ windows 7 is not supported

**Comment by sfan5** [comment]
Aside from Windows 7 not being supported this is probably the bug fixed here: https://github.com/minetest/irrlicht/commit/94cb0cc19dba4090be0d290209f7149eabfd6e0d

**Comment by vichoca9** [comment]
Indeed that fixes it, so thx!
