### ISSUE TITLE
Call order of handle_node_drops

### ISSUE THREAD

**Issue by hi563145** [minetest/minetest#14108]
### Minetest version

```true
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Arch Linux x86_64

### Summary

The call order of `handle_node_drops` function in the default implementation of `node_dig` should be called before wearing out the tool.

By changing the call order of the function, `handle_node_drops` callers can have access the tool before it takes damage. This is particularity important when the tool is at it's last use as the tool would break and the function is no longer able to access the tool that is used to break the block.

See this [issue](https://git.minetest.land/MineClone2/MineClone2/issues/3931) for more information.

### Steps to reproduce

Break a block with any tool

**Comment by Zughy** [comment]
Offending lines

https://github.com/minetest/minetest/blob/48845de46ef400e532f2108dfb9ff9a3107bd66a/builtin/game/item.lua#L521-L557

**Comment by appgurueu** [comment]
This is a feature request for something that runs *before* `handle_node_drops`.

It makes little sense to me that `handle_node_drops` would also handle tool wear; that's simply not what it's designed to do, it's solely supposed to handle node drops.

Instead you are supposed to use `after_wear` to control tool wear, as you can see in the above code snippet. Why is that not an option? What would you want a more flexible feature to look like?

Note that we can't change when `handle_node_drops` runs without breaking compatibility.
