### ISSUE TITLE
lua api: PseudoRandom: peek at current rng state to allow save/restore

### ISSUE THREAD

**Issue by lolbinarycat** [minetest/minetest#14107]
### Problem

currently, aside from implementing your own LCG, there is no good way to persist the state of a PRNG across server restarts.

### Solutions

add a `state()` method to PseudoRandom metatable, which exposes the current 16-bit internal state.

because of the nature of LCGs, this can later be used as a seed, and the new PRNG will be identical to the old one at the time of calling `state()`.

### Alternatives

1. add this method to PcgRandom instead.  this may be favorable since it is more robust, however i am not sure if the PCG algorithm has a more complicated internal state that would make this difficult.
2. add serialization capabilites to PseudoRandom directly
3. allow mods to allocate persitant rng streams that are automatically saved along with worldgen rng

**Comment by SmallJoker** [comment]
@lolbinarycat What are the use-cases? Couldn't you use time-based random bias for seeding a new Pseudo-random generator?

**Comment by lolbinarycat** [comment]
usecase is anything you want to be deterministic based on a given worldseed.

**Comment by SmallJoker** [comment]
Forgive my ignorance but you already wrote that in the first comment. Based on the grep results in my installed mods, it seems that some `PseudoRandom` instances are used similar to `math.random()` or - when used for mapgen - like perlin noise, using a mixture of x/y/z coordinates for seeding the randomness once per generated chunk.

Given the nature of PRNG's it does make sense to preserve the state, although I cannot see a clear advantage over using Perlin noise (x/y/z coordinates for state tracking) at the moment.

**Comment by lolbinarycat** [comment]
> Forgive my ignorance but you already wrote that in the first comment. Based on the grep results in my installed mods, it seems that some `PseudoRandom` instances are used similar to `math.random()` or - when used for mapgen - like perlin noise, using a mixture of x/y/z coordinates for seeding the randomness once per generated chunk.
>  
> Given the nature of PRNG's it does make sense to preserve the state, ~although I cannot see a clear advantage over using Perlin noise (x/y/z coordinates for state tracking, spread = 1 to allow non-smoothed increments of 1) at the moment~. EDIT: Lossless state preservation and easier to use (seeding once, simpler API)

well of course none of the existing mods use any sort of save/restore functionality, as it doesn't exist yet, and it seems you've already identified a valid usecase for it.
