### ISSUE TITLE
ERROR[Server]: Got packet command: 23 for peer id #### but client isn't active yet. Dropping packet 

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#14113]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using LuaJIT 2.1.1702296283
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
STATIC_SHAREDIR="."
```

### Active renderer

N/A

### Irrlicht device

N/A

### Operating system and version

Alpine 3.17.3

### GPU model

Intel i5-3320M (4) @ 3.300GHz

### OpenGL version

N/A

### Summary

Ocassionally when certain players (known to have bad network latency) connect, I get this message:

```
ERROR[Server]: Got packet command: 23 for peer id #### but client isn't active yet. Dropping packet
```

Warning and error messages indicate something that a server operator needs to do: either fix a problem (mod issues) or report it upstream.

If this is NOT meant to indicate a condition that requires action and is expected behavior of a correctly system, then the severity should be lowered below "warning".

### Steps to reproduce

- Run a public server
- Conscientiously follow server logs for any messages with severity >= warning

**Comment by Zughy** [comment]
OP has not been seeing this warning for a couple of months, labelling as possible close
