### ISSUE TITLE
[regression] touchscreen stopped working with 5.8.0 on Linux

### ISSUE THREAD

**Issue by okias** [minetest/minetest#14111]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Active renderer

irrelevant

### Irrlicht device

X11

### Operating system and version

Alpine Linux (postmarketOS)

### CPU model

aarch64

### GPU model

Adreno 630

### OpenGL version

irrelevant

### Summary

While with 5.7.0 touchscreen worked well, with 5.8.0 isn't possible to enter the game from the menu.

### Steps to reproduce

Run the game. Cannot be controlled by touch-screen.

**Comment by okias** [comment]
Working version:
```
Minetest 5.7.0 (Linux)
Using Irrlicht 1.9.0mt10
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

**Comment by rubenwardy** [comment]
Are you building with the touchscreen controls? Or are you referring to the use of the touchscreen in GUIs

**Comment by okias** [comment]
These builds are done with `-DENABLE_TOUCH=1`, I originally thought it's my mistake doing the runtime detection, but just now I compiled clean 5.8.0 with option and the result is same.

**Comment by okias** [comment]
I tried the most likely guess. Reverting 53886dcdb52de80d862539e22950c84fbf88df88 helped.

**Comment by grorp** [comment]
Can confirm. Most likely `CIrrDeviceLinux` doesn't implement `event.TouchInput.ID` properly.

**Comment by okias** [comment]
Thank you for quick feedback, if you can tell me what the plan most likely be, if  fixup or revert. As I'm building https://github.com/minetest/minetest/pull/14075 a top of 5.8.0 and so far I just reverted and resolved conflicts.

**Comment by grorp** [comment]
> Thank you for quick feedback, if you can tell me what the plan most likely be, if fixup or revert. As I'm building #14075 a top of 5.8.0 and so far I just reverted and resolved conflicts.

A revert doesn't really make sense, so it needs to be fixed.

Since you apparently have a Linux phone, could you maybe test https://github.com/minetest/irrlicht/pull/262? (Compile with the linked PR, `USE_SDL2=TRUE` and `ENABLE_TOUCH=TRUE`.)

That PR shouldn't be affected by this issue. However, I have some other issues with it and I'd like to know whether they are specific to my setup or not.

**Comment by rubenwardy** [comment]
I support fixing SDL and then relying on that, I'd like to see moving to SDL as a goal for 5.9

**Comment by okias** [comment]
First, thank you for SDL2. One day I also hope run natively on Wayland (not waste power & ugliness on XWayland).

I'll test it soon.

The 5.8.x MR not-yet-SDL2 is ready. We need to get rid of hardcoded `ENABLE_TOUCH` anyway (best it would be if it only set default settings until there will be autodetection).

**Comment by srifqi** [comment]
> /cc @srifqi

Sorry, I might not be able to help in this case currently.

By the way, `CIrrDeviceWin32` also does not handle touch input.

**Comment by grorp** [comment]
#14117

> By the way, `CIrrDeviceWin32` also does not handle touch input. (EDIT: [my failed? attempt](https://github.com/srifqi/irrlicht/tree/win-touch))

You probably don't need to bother if we're planning to migrate all platforms to `CIrrDeviceSDL` anyway.
