### ISSUE TITLE
Minetest arbitrarily disallows playing the same animation twice for some models

### ISSUE THREAD

**Issue by FatalError42O** [minetest/minetest#14122]
Version 5.8

### Problem

So, I'm making a gun mod. And I found, very quickly, that you can't play the same animation on an entity twice for no apparent reason.

I was surprised to learn that GreenXenith was able to replay animations for a model he made, and it was later discovered that specifically the model (and past models) I have used, refuse to be replayed for no apparent reason.

This originally was a feature request, as I thought that it was just made like that. Testing showed otherwise. So my apologies if the format is off. This problem has been seen on several devices and is probably not hardware specific (especially given the nature of the issue)

See green's code in the comments.

**Comment by FatalError42O** [comment]
not a bug @wsor4035 it checks the x value of the animation, maybe also the y value (I'm not sure)

**Comment by GreenXenith** [comment]
I looked into this further; For some reason, on his model at least, trying to replay any frames within the range 0-6 fails. Any range exceeding frame 6 works fine, however.

Code:
```lua
minetest.register_entity("test:repeat", {
    visual = "mesh",
    mesh = "m4.b3d",
    textures = {"default_dirt.png"},
    visual_size = vector.new(10, 10, 10),
    on_activate = function(self)
        self.timer = 0
    end,
    on_step = function(self, dtime)
        self.timer = self.timer + dtime
        if self.timer >= 0.2 then
            self.timer = self.timer - 0.2
            self.object:set_animation({x = 0, y = 6}, 60, 0, false) -- change 6 to 7 for successful replay
        end
    end,
})
```
Model: https://github.com/FatalError42O/guns4d_pack_1/raw/master/models/m4.b3d

**Comment by wsor4035** [comment]
in response to tagging, this certain isnt a feature request. looking at what greenxenith found, seems to hint at it potentially being either a bug in minetest, or a `question` relating to your model being broken. going to leave it as `unconfirmed bug` for now.

**Comment by FatalError42O** [comment]
> in response to tagging, this certain isnt a feature request. looking at what greenxenith found, seems to hint at it potentially being either a bug in minetest, or a `question` relating to your model being broken. going to leave it as `unconfirmed bug` for now till its _confirmed_ one way or the other

I now agree lol.

**Comment by FatalError42O** [comment]
> I looked into this further; For some reason, on his model at least, trying to replay any frames within the range 0-6 fails. Any range exceeding frame 6 works fine, however.
> 
> Code:
> 
> ```lua
> minetest.register_entity("test:repeat", {
>     visual = "mesh",
>     mesh = "m4.b3d",
>     textures = {"default_dirt.png"},
>     visual_size = vector.new(10, 10, 10),
>     on_activate = function(self)
>         self.timer = 0
>     end,
>     on_step = function(self, dtime)
>         self.timer = self.timer + dtime
>         if self.timer >= 0.2 then
>             self.timer = self.timer - 0.2
>             self.object:set_animation({x = 0, y = 6}, 60, 0, false) -- change 6 to 7 for successful replay
>         end
>     end,
> })
> ```
> 
> Model: https://github.com/FatalError42O/guns4d_pack_1/raw/e8da9ade6d0d3145fa1560d4e5b632aa8f8b6e41/models/m4.b3d

I believe frame 6 is actually when there are no more animations (as the model is incomplete), that's surely related.

**Comment by FatalError42O** [comment]
I also noticed that when I used frame blend it COMPLETELY broke single frame animations- i.e. I have a "loaded" and "unloaded" state for the gun's magazine. It did some weird interpolation where it was for some reason at a 90 degree angle clipping into the gun and over the course of several minutes returned to its normal state

**Comment by Zughy** [comment]
How can we know is Minetest and not the model itself being corrupted somehow?

**Comment by FatalError42O** [comment]
> Member

because thats not how the b3d format works. The issue is with setting what frames to use. it seems you didn't read the full context. The animation _exists_ it just wont play unless a different animation is set previously. Strangely enough it only happens with some models according to Green.

the b3d model only defines what each keyframe is, the viewport interpolates between those frames based on the frame range provided and time elapsed. 

The proof is that it plays the first time, therefore the expected animation exists and plays as expected. The model should not change (unless minetest fucks it up). 

There is no possibility in which it is an issue caused by the model being improperly exported, especially because I _use_ this model still and simply alternate between frames when firing to work around the problem.

**Comment by FatalError42O** [comment]
if you break down the b3d format you can figure out pretty quickly that there's no way that it's because of any model

**Comment by appgurueu** [comment]
Churned this through modlib and truncated it ([m4.lua.txt](https://github.com/user-attachments/files/16660108/m4.lua.txt)), indeed this is a bug.
