### ISSUE TITLE
transparent texture issues

### ISSUE THREAD

**Issue by superfloh247** [minetest/minetest#14133]
### Minetest version

```true
Minetest 5.9.0-dev-61d0f61 (OSX)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1700008891
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
STATIC_LOCALEDIR="minetest.app/Contents/Resources/locale"
```

### Active renderer

OpenGL 2.1

### Irrlicht device

OSX

### Operating system and version

MacOS 14.2

### CPU model

AppleSilicon M1pro

### GPU model

AppleSilicon M1pro

### OpenGL version

2.1

### Summary

transparent textures are not transparent anymore, they are white or black where the transparency should be

5.9.0-dev-61d0f61 (OSX)

![screenshot_20231220_075042](https://github.com/minetest/minetest/assets/26180993/5cbd839c-925e-448e-9ddb-4d4e4379787b)

![screenshot_20231220_075610](https://github.com/minetest/minetest/assets/26180993/d9e7b718-2cba-4015-99a6-590a8b8069fe)

not affected: 5.8.0 (OSX)
Minetest 5.8.0 (OSX)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1700008891
BUILD_TYPE=Release

![screenshot_20231220_075120](https://github.com/minetest/minetest/assets/26180993/cc53b6c3-e416-4e2e-8511-6fbeda4ebb8f)

![screenshot_20231220_075658](https://github.com/minetest/minetest/assets/26180993/a04c65e6-bbf4-45c1-b8d2-396ecc95bcb3)

### Steps to reproduce

walk around and look for transparent things

**Comment by sfan5** [comment]
> ### Active renderer
> 
> _No response_
> ### Irrlicht device
> 
> _No response_

Missing important info.

**Comment by superfloh247** [comment]
<img width="275" alt="Bildschirmfoto 2023-12-20 um 11 27 04" src="https://github.com/minetest/minetest/assets/26180993/6b9463c6-265d-412c-82b2-e52f10b89b6f">

**Comment by Niklp09** [comment]
Caused by: https://github.com/minetest/minetest/pull/13929
Related: https://github.com/Archtec-io/bugtracker/issues/137

**Comment by sfan5** [comment]
Without any more info what kind of nodes that are I assume this is indeed a mod issue.

**Comment by superfloh247** [comment]
I agree

5.8 emits this warning
`2023-12-20 14:46:27: WARNING[Main]: Texture "bushes_leaves_1.png" of bushes:bushbranches1 has transparency, assuming use_texture_alpha = "clip".
`
5.9 does not and that's one of the problematic nodes
