### ISSUE TITLE
Particles are very slow

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#1414]
Minetest uses a custom particle(spawner) implementation using entities, this is very slow.
Irrlicht's built-in particles are much faster, as you can see [here](https://www.youtube.com/watch?v=5WnmQYLJzlE).

Irrlicht's particles don't support collision by default, but this can be done with particle affectors (see [here](https://www.youtube.com/watch?v=-brLc8uUeQk)).

EDIT: Done (but with issues) by #2587.

**Comment by neoascetic** [comment]
+1

**Comment by neoascetic** [comment]
If collision detection implementation is hard, it would be cool to have Irrilicht's implementation at least for particles with turned off collision detection, and fallback to current implementation otherwise.

**Comment by Wuzzy2** [comment]
The first thing I noticed is that the rendering distance for particles is infinite. It seems that once a client has "found" a particlespawner, it will handle and render it even if the player is very far away. So my first suggestion to boost performance is to limit the rendering distance of particles. Particles and particles that appear more than X nodes away from the player are ignored. You don't need to simulate particles of a block of fire over 1000 nodes away. ;-)

https://satoshiupload.com/images/UMZYItK8y5.png

Maybe the modder can be permitted to set a flag in the particle definition to overwrite the distance limit regardless (useful for large particles).

**Comment by kay27** [comment]
Particles spawners have such options as speed, acceleration and distance (position), so maybe the logic is that the particles can fly very far and finally reach you after 1000 nodes... So the easiest way of fixing it for myself is to add just one option: maximum rendering distance from spawner position. For anarchy-type servers it should be not so big value, I think not more than 100 nodes.

**Comment by ExeVirus** [comment]
So this was discussed in now closed duplicates of this issue, but the best idea(s) put forward are:

Simple version: max distance clipping
Complex version: FOV clipping. In this case, we render only particles/particle spawners that are directly in front of the player's vision up to a max distance (basically a rectangular prism). This could use an octree to subdivide the particles and spawners by block, and just specify if a given block is visible in the cone or not. 

If this complex version works for particles, it was suggested that something similar be done for all entity rendering, especially animated entities.

**Comment by kay27** [comment]
@ExeVirus I'm not sure that Complex version as you described here is correct at whole. The simple example: water drops aren't in front of the player but they MUST reach them. So spawned-specific distance setup seems would be still preferred, for myself

**Comment by AFCMS** [comment]
> Minetest uses a custom particle(spawner) implementation using entities, this is very slow.
> Irrlicht's built-in particles are much faster, as you can see [here](https://www.youtube.com/watch?v=5WnmQYLJzlE).

Link is dead.

**Comment by ronoaldo** [comment]
Hi, after some pointers on IRC about this, I'm starting to study the code and proposed approaches. I am new to 3D development, but the task at hand looks like quite interesting as a first contribution from my end. If someone else is already working, kindly let me know so I don't duplicate effort and can focus on something else.

**Comment by wsor4035** [comment]
fixed by https://github.com/minetest/minetest/pull/14489 (adoption of the linked pr above)
