### ISSUE TITLE
Pasting non-text input crashes Minetest

### ISSUE THREAD

**Issue by xenonca** [minetest/minetest#14150]
### Minetest version

```true
Minetest 5.8.0
```

### Active renderer

OpenGL 4.6

### Operating system and version

Windows 11

### OpenGL version

4.6

### Summary

When trying to paste something that is not text (e.g. a file) into a formspec using Crtl + C and Ctrl + V Minetest will crash with no errors in the logs.

### Steps to reproduce

Copy any file with Ctrl + C. Try to paste it into a formspec, e.g. a sign input field, with Ctrl + V.

**Comment by Desour** [comment]
Can't reproduce on linux with SDL2 irrlicht device.

**Comment by rewired-X** [comment]
I achieved a similar result, although I am not certain if I can reproduce it the exact same way I did it.
I tried to copy-paste coords from Discord to in-game, and crashed 3 times.
The fourth time I tried, I copied the coords again and pasted, this time it worked.

**Comment by fluxionary** [comment]
@rewired-X can you post the details of your OS and build? (`minetest --version`)

**Comment by srifqi** [comment]
This issue is caused by minetest/irrlicht#249 (specifically minetest/irrlicht@c766c3a023e52a31a0a0aeee1780e0000aabaec4).

Stack trace:
```cpp
/* 7 */ irr::core::wStringToUTF8(class irr::core::string<char> &,wchar_t const *)
/* 6 */ irr::COSOperator::getTextFromClipboard(void)
/* 5 */ irr::gui::CGUIEditBox::processKey(struct irr::SEvent const &)
/* 4 */ irr::gui::CGUIEditBox::OnEvent(struct irr::SEvent const &)
/* 3 */ irr::gui::CGUIEnvironment::postEventFromUser(struct irr::SEvent const &)
/* 2 */ irr::CIrrDeviceStub::postEventFromUser(struct irr::SEvent const &)
/* 1 */ WndProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)
```

Possible fix:
```diff
diff --git a/source/Irrlicht/COSOperator.cpp b/source/Irrlicht/COSOperator.cpp
index d2b3b8d..33b07ec 100644
--- a/source/Irrlicht/COSOperator.cpp
+++ b/source/Irrlicht/COSOperator.cpp
@@ -162,6 +162,9 @@ const c8* COSOperator::getTextFromClipboard() const
 	wchar_t * buffer = 0;
 
 	HANDLE hData = GetClipboardData( CF_UNICODETEXT );
+	if (hData == NULL) // Probably not in Unicode text format
+		return 0;
+
 	buffer = (wchar_t*) GlobalLock( hData );
 
 	core::wStringToUTF8(ClipboardBuf, buffer);
```
[Documentation for `GetClipboardData()`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclipboarddata)

**Comment by grorp** [comment]
So this doesn't happen with `USE_SDL2=TRUE` / `CIrrDeviceSDL`, right? (will become the default on Windows with 5.9.0)

(Also, I'm wondering why the missing null check didn't cause problems before minetest/irrlicht@c766c3a023e52a31a0a0aeee1780e0000aabaec4.)

**Comment by srifqi** [comment]
> So this doesn't happen with `USE_SDL2=TRUE` / `CIrrDeviceSDL`, right?

Yes, this issue does not occur using SDL2.

> (Also, I'm wondering why the missing null check didn't cause problems before minetest/irrlicht@c766c3a023e52a31a0a0aeee1780e0000aabaec4.)

My guess is that [the old code](https://github.com/minetest/irrlicht/blob/9954667c45cc6c184ead60b516e532111556e56a/include/irrString.h#L984-L995) checks for null-ness of `source` parameter.

```cpp
static inline size_t wStringToMultibyte(string<c8>& destination, const wchar_t* source)
{
	const u32 s = source ? (u32)wcslen(source) : 0;
	return wStringToMultibyte(destination, source, s);
}
```

```cpp
static size_t wStringToMultibyte(string<c8>& destination, const wchar_t* source, u32 sourceSize)
{
	if ( sourceSize )
	{
		// ...
	}
	else
	{
		destination.clear();
		return 0;
	}
}
```

**Comment by rewired-X** [comment]
@fluxionary live from the windows command prompt :P
![Screenshot (1309)](https://github.com/minetest/minetest/assets/150751430/c8139978-8f53-4770-86f2-7d876d4682f5)

**Comment by grorp** [comment]
> Possible fix: [...]

Alright, do you want to open a PR?

**Comment by srifqi** [comment]
> do you want to open a PR?

I am planning to do it.
