### ISSUE TITLE
lua_api is wrong about hud element type: image_waypoint

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#14158]
### Minetest version

```true
5.8.0, current
```

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### Summary

lua_api states:
```
* `scale`: The scale of the image, with 1 being the original texture size.
  Only the X coordinate scale is used (positive values).
  Negative values represent that percentage of the screen it
  should take; e.g. `x=-100` means 100% (width).

```
with the trouble being specifically:`
  Only the X coordinate scale is used (positive values).
`
This is false. Devtest uses both x and y values in the scale element of its test hud function. Furthermore, if the y element is NOT present, image_waypoint doesn't work; no hud elements are visible. This threw me for like 10 minutes when I did it earlier.

### Steps to reproduce

Open up devtest, edit mods/testhud/init.lua and remove the "unused" Y scale value, then fire it up and run /hudwaypoints, and the purple "WP" image_waypoint it places at your feet will be gone.

**Comment by appgurueu** [comment]
Probably a copy-paste error on my side. IIRC, both X and Y apply; omitted fields unfortunately default to 0?
