### ISSUE TITLE
Docker CI pipeline has been broken for over a year

### ISSUE THREAD

**Issue by devonhk** [minetest/minetest#14164]
### Minetest version

```true
N/A
```

### Operating system and version

N/A

### Summary

We can see [here](https://gitlab.com/minetest/minetest/container_registry/314118?orderBy=NAME&sort=desc&search[]=) that the latest docker image tags were published over a year ago.

The latest tag is pretty old:
> Published to the minetest/minetest/server image repository at 03:28:11 GMT on 2022-05-19

The docker package job seems to always be skipped since the preceding job (AppImage builder) usually fails.
https://gitlab.com/minetest/minetest/-/pipelines/872751077

### Steps to reproduce

Any merge to `master` should trigger the failing CI jobs.

**Comment by sfan5** [comment]
Our gitlab mirror has been effectively unmaintained (and largely broken) since 1 year or more¹, we should stop recommending anything produced by it asap and ideally also migrate the Docker image to a more stable workflow.

¹: IIRC it was around the time Gitlab announced more restrictions for free pipelines

**Comment by devonhk** [comment]
In the short term, you may want to remove the `Docker` section from the readme since it's currently unsupported.
https://github.com/minetest/minetest#docker

My 2cents for a longer term solution is to update the github CI workflow (which appears to be relatively [stable](https://github.com/minetest/minetest/actions/runs/7332089789/job/19965702081)) to handle container image publishing, either to ghcr.io (Github's container registry) or Docker hub.

Also, the Linux [AppImage](https://github.com/minetest/minetest/blob/335af393f09b3629587f14d41a90ded4a3cbddcd/.gitlab-ci.yml#L110) build job has also been failing for a while. Not sure if y'all want to migrate it to Github or stop supporting it.

I can help with the Docker image publishing pipeline if you don't have the bandwidth to do it yourselves.  I was originally looking to install `minetest` in my Kubernetes cluster, which led me to find these issues.
