### ISSUE TITLE
Fog can be disabled (API-sent as well)

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14163]
### Minetest version

```true
Since always
```

### Summary

Having a custom API to customise fog is useless if people can still press F3 to disable it and cheat/ruin the atmosphere. I really appreciate the work done by @lhofhansl but right now is pointless. Here's a video I made about it: https://matrix.to/#/!jGawCGhycfrYboDVtV:tchncs.de/$giwsOnMAc3SZwHVF7269r9DVkiPXRF2yRHsIyRYYHUg

If the API enforces fog, players shouldn't be allowed disabling such fog. We could also argue about removing the F3 key in general, as it seems more of a debugging tool than a gaming one (why players should decide between a smooth transition with the void and a hard one?)

### Steps to reproduce

Press F3 with whatever type of fog

**Comment by Montandalar** [comment]
F3 key should stay in my opinion, even if it should become disable-able by a mod like the minimap and radar. I think it improves the sharpness of the image and don't see a reason to completely remove it.

**Comment by lhofhansl** [comment]
My work is mostly about how far you can see. Fog just hides the edge of the world, but does not reduce your viewing_range.
Not opposed to disable the client option when the server sets the fog distance, but it does not change how much a player can see.

**Comment by lhofhansl** [comment]
I do not agree with a "High priority" here. You still cannot cheat by turning off fog - your viewing_range is still limited to what the server decides.

**Comment by Zughy** [comment]
@lhofhansl if you watch the video in the first message, you can see how much further I can see without fog

**Comment by grorp** [comment]
Disabling fog can indeed give a big advantage. Compare these screenshots from Shadow Forest by Wuzzy:

with fog enabled
![screenshot with fog enabled](https://github.com/minetest/minetest/assets/82708541/463b41aa-1d9a-450c-916d-e9d710ed5954)

with fog disabled by pressing F3
![screenshot with fog disabled](https://github.com/minetest/minetest/assets/82708541/72a36053-43e6-4576-a8f3-887fffa1e6c1)

Disabling fog allows you too see a lot more platforms. Also, collectibles that were previously hidden by the fog become visible. I think this should be considered cheating, and thus it should be high priority.
