### ISSUE TITLE
Unlimited view range + server-sent fog still shows the silhouette of far away buildings

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14166]
### Minetest version

```true
5.8+
```

### Operating system and version

Pop!_OS

### GPU model

NVIDIA GeForce something

### Summary

In the video down below, the player has `fog_distance = 50` and I enable the unlimited view range in the first seconds. I expect everything further than 50 nodes to be completely hidden

https://github.com/minetest/minetest/assets/63455151/104f6b84-5f48-4905-8c3b-722f6bd805dc

### Steps to reproduce

```lua
minetest.register_on_joinplayer(function(player)
  player:set_sky({fog = {fog_distance = 20}})
end)
```

enable unlimited view range and look around

**Comment by lhofhansl** [comment]
Hmm... Interesting. I'll have a look.

**Comment by Zughy** [comment]
That's been fixed, nice!
