### ISSUE TITLE
image[] is not clipped by scroll_container[]

### ISSUE THREAD

**Issue by aerkiaga** [minetest/minetest#14167]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Active renderer

OpenGL 4.6.0

### Irrlicht device

X11

### Operating system and version

Linux Mint 21.2

### CPU model

AMD Ryzen 5 4500

### GPU model

NVIDIA GeForce GT 730

### OpenGL version

4.6

### Summary

Related to https://github.com/minetest/minetest/issues/10925?
I'm using an image[] within a scroll_container, using a scrollbar[] and scrollbaroptions[]. While the scrollbar works and the offsets are right, image[] elements appear outside the container and the formspec altogether.
A workaround that I used is to use an animated_image[], since that one seems to work.

### Steps to reproduce

Here's the code that triggered the issue in my case: https://github.com/aerkiaga/nodeverse/blob/2b5bfc159a8680899a07ba57f7d220e0263c9666/mods/nv_encyclopedia/init.lua

And this was the workaround I used:

```diff
index 40cbd09..2a53674 100644
--- a/mods/nv_encyclopedia/init.lua
+++ b/mods/nv_encyclopedia/init.lua
@@ -35,7 +35,7 @@ local function get_base_formspec(player)
         for m, pseed in ipairs(nv_universe.get_ordered_planets_in_system(systems[n].seed)) do
             pl = pl .. string.format(
                 [[
-                    image[%d,%d;1.8,1.8;%s]
+                    animated_image[%d,%d;1.8,1.8;image;%s;1;0]
                 ]],
                 x,
                 y + 1,
```

**Comment by Desour** [comment]
Do you have a formspec to reproduce this bug in devtest?
I have a strong suspicion, that some of your code, or formspec prepend, sets `noclip` for images via formspec styling. Noclip elements are not clipped by the scroll container.

**Comment by aerkiaga** [comment]
Unfortunately I'm not using formspec styling, or any external mods that produce the formspecs and therefore could be using it. I'm looking into the linked issue, since it seems like there could be something with these lines:

````C++
GUIAnimatedImage *image = new GUIAnimatedImage(Environment, /*here:*/ data->current_parent,
			spec.fid, rect);
```
And this:

````C++
GUIBackgroundImage *e = new GUIBackgroundImage(Environment, /*here:*/ data->background_parent.get(),
			spec.fid, rect, name, middle, m_tsrc, clip, autoclip_offset);
```

I'm not familiar with the code, what is the difference between those and could it impact clipping?

**Comment by Desour** [comment]
The latter is a background images (`background[]` element), not `image[]`. `background[]` isn't made to work in scroll containers.

**Comment by aerkiaga** [comment]
Nope, nothing to do with this. Okay, I'll have a deeper look tomorrow. Thank you.

**Comment by aerkiaga** [comment]
`GUIFormSpecMenu::parseAnimatedImage` has this instead:

```C++
e->setNotClipped(style.getBool(StyleSpec::NOCLIP, false));
```

And I happened to be using `formspec_version[2]` (which I probably shouldn't?).

**Comment by aerkiaga** [comment]
Yeah, setting `formspec_version[3]` works like a charm. I feel so stupid right now, the documentation even stated that in version 3, "box[] and image[] elements enable clipping by default".

**Comment by Desour** [comment]
No need to feel stupid! I didn't remember `image[]` not being clipped in old versions either, even though I was probably involved in that change.

Printing a warning if scroll containers are used in old formspec versions might be nice, I guess.
