### ISSUE TITLE
Random crashes when trying to join a server on Windows

### ISSUE THREAD

**Issue by immagiov4** [minetest/minetest#14183]
### Minetest version

```true
Minetest 5.8
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL 4.6

### Irrlicht device

WIN32

### Operating system and version

Windows 11

### OpenGL version

4.6

### Summary

When I try to access/host a server on Windows, about 1/10 of the times the engine closes without any error message in the debug.txt. As far as I remember this did not happen before the PR separating the registration button from the login button.
It doesn't seem to happen on Linux.

Since the debug file doesn't help I've tried launching it from terminal with the verbose flag, but it doesn't seem to be very useful either: https://pastebin.com/raw/bR9Mhw9A. If there's a better way of debugging it please tell me.

### Steps to reproduce

I haven't figured out the crash trigger, but I know I'm not the only one experiencing this on Windows. Just try to join a server until it happens.

**Comment by sfan5** [comment]
What *is* your Minetest version? You accidentally cut it off in the info at the top.

> https://nekobin.com/rejecopawo.

This is empty

> As far as I remember this did not happen before the PR separating the registration button from the login button.

That was ages ago so I don't think it helps narrowing it down.

**Comment by immagiov4** [comment]
> What _is_ your Minetest version? You accidentally cut it off in the info at the top.
> 
> > https://nekobin.com/rejecopawo.
> 
> This is empty
> 

Oh, sorry I didn't notice, I fixed it.

**Comment by hlqkj** [comment]
I can reproduce this, same specs, same client version. It actually has been happening since at least a few releases (for sure 5.8, 5.7 and very possibly 5.6 are affected; I can't remember when I started experiencing this, though).

I tried to work out something from debug.txt as well, even setting `debug_log_level` to its maximum, but had no luck. Sadly I didn't succeed in attaching a debugger.

The only things I could add are:
- I keep my minetest.conf file read only, to avoid the client messing it up, and 
- I sometimes run multiple client instances outputting to the same debug.txt file.

However, guessing these unconventional conditions could be at fault, I tried to play without them for a while and the crash still happens.

I never posted an issue due to the difficulty in reproducing it: even if I could attach a debugger, it happens so _very_ randomly that it'd be very difficult to catch it (at times it could fail in five or more attempts in a row, then work fine dozens logins).

**Comment by sfan5** [comment]
> Minetest 5.8

okay good, so it's not #14140

Having a debug log is good but almost as expected it doesn't contain anything useful.

The best way to debug this would be by installing `gdb` so Minetest can find it (usually means globally) and then make sure to start each of your Minetest runs with `--debugger`.
If you do that right now you're unfortunately much more likely to run into the aforementiond crash issue.

**Comment by hlqkj** [comment]
I think I'm on the right tracks, but I don't know `gdb` at all at the moment (maybe this is the time to finally learn...)

So I ran this on a MINGW64\MSYS2 shell:
```
$ gdb -- ./bin/minetest.exe --debug
```

And got this (lucky me, it happened on 1st attempt):

```
Thread 21 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1000.0x29bc]
0x00007ff6dd55114e in std::set<unsigned long long, std::less<unsigned long long>, std::allocator<unsigned long long> >::~set() ()
```

I figure there must be some way of getting more detailed info?

**Comment by immagiov4** [comment]
Same, mine also says:
```
Thread 16 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 24844.0x6514]
0x00007ff62342114e in std::set<unsigned long long, std::less<unsigned long long>, std::allocator<unsigned long long> >::~set() ()
#0  0x00007ff62342114e in std::set<unsigned long long, std::less<unsigned long long>, std::allocator<unsigned long long> >::~set() ()
#1  0x00007ff9238f853c in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by sfan5** [comment]
FYI with `--debugger` Minetest will attempt to find, and use gdb to produce a meaningful stacktrace all on its own. So no need for any manual commands :)

Anyway your crash info suspiciously sounds like it's essentially the same issue as in #14140.
We can't tell which `std::set` it is but MT does have a thread_local [one with the same type](https://github.com/minetest/minetest/blob/c9ab61aa8cd0ca50bc8c4d90f257bb5ed3b0bb00/src/script/common/c_converter.cpp#L442).
This has been discussed in dev IRC on two occasions but the short explanation is that MinGW **for years** has had a bug where our threads would crash when exiting under random circumstances.

**Comment by hlqkj** [comment]
Ok, reading #14140 it sounds indeed like it. I'll follow that one as well then and hope for a solution. As always, thank you very much for looking into this!

(Also, thanks for the info about `gdb` - I realized I did something stupid after reconnecting my brain, lol! Besides, the switch I initially passed was even wrong... I definitely need to learn.)
