### ISSUE TITLE
Deprecate PseudoRandom

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14180]
### Problem

PseudoRandom is, according to [my benchmarks](https://github.com/minetest/minetest_docs/blob/master/doc/random.adoc) and the API docs, strictly inferior to PcgRandom.

### Solutions

Deprecate it, remove it in 6.0.

### Alternatives

Keep having two seedable random implementations, one of which is strictly worse. (I would suggest at least adding a note that usage of PseudoRandom is not recommended.)

### Additional context

I was reminded of this when reviewing #14123.

**Comment by Desour** [comment]
Suggesting in the docs to prefer PcgRandom sounds fine by me. But I wouldn't outright remove it. Some mods might not be able to replace the noise function without breaking maps. And we can't remove the PseudoRandom class from C++ anyway, because mgv6 uses it, can we?

**Comment by rollerozxa** [comment]
List of occurrences of PseudoRandom in CDB packages: https://web.archive.org/web/20231229153454if_/https://content.minetest.net/zipgrep/2432efd3-6df4-4ff4-bdf1-624a4c241344/

**Comment by BluebirdGreycoat** [comment]
I definitely cannot replace PseudoRandom in some places where I've used it. Please keep. I'm fine with it being a worse PRNG.

**Comment by appgurueu** [comment]
> But I wouldn't outright remove it. Some mods might not be able to replace the noise function without breaking maps.

Good point, I hadn't really considered this. Still, I believe removal of PseudoRandom could go on the list of breakages?

> And we can't remove the PseudoRandom class from C++ anyway, because mgv6 uses it, can we?

What if we put removal of mgv6 on the list of breakages too?

**Comment by Desour** [comment]
I'm against breaking old worlds, and hence also against removing mgv6, or PseudoRandom.

**Comment by appgurueu** [comment]
Fair. A note in the docs note to use these for new stuff it is then.

**Comment by sfence** [comment]
So, if this ends as a documentation issue only, I can fix it in #14123 PR.

So what about adding text:
"PsedoRandom generator should not be used in new mods etc. Use PcgRandom generator instead."

**Comment by BluebirdGreycoat** [comment]
I don't like. This implies that PseudoRandom is being depreciated and to be removed in the future. I prefer this instead:

`PseudoRandom is slower and has worse random distribution compared with PcgRandom. Use PseudoRandom only if you need output to match the well-known LCG algorithm introduced by K&R. Otherwise, use PcgRandom.`

(Note: I'm assuming that the output of PseudoRandom *actually does* match the K&R generator. I've never checked.)

**Comment by appgurueu** [comment]
Thanks for the suggestion, that's what I went with in the end. Fixed in https://github.com/minetest/minetest/commit/a8cf10b0b523bf4c3234be29b0dd51e719cb00c1.
