### ISSUE TITLE
TouchScreenGUI: Shootline isn't updated when the finger doesn't move

### ISSUE THREAD

**Issue by sotha1** [minetest/minetest#14188]
https://github.com/minetest/minetest_game/assets/149703967/a4396ca1-fd96-41e0-9c57-da082283c4ee

when i hold my finger to broke the stones, after more than 5 blocks of the same type, minetest stops and i have to hold again

**Comment by SmallJoker** [comment]
Assumption: the shooting line is not updated as long the mouse button (or here: finger) is held down.

**Comment by grorp** [comment]
Yes, that's indeed the problem. The shootline is only updated when you move your finger, not when the player moves.

A fix for this bug is included in #14087 because I had to rewrite the relevant code anyway.

**Comment by sotha1** [comment]
> > Assumption: the shooting line (or rather its start position) is not updated as long the mouse button (or here: finger) is held down.
> 
> Yes, that's indeed the problem. The shootline is only updated when you move your finger, not when the player moves.
> 
> A fix for this bug is included in #14087 because I had to rewrite the relevant code anyway. I can make a separate PR just for the bugfix if you want.

it would be useful

**Comment by SmallJoker** [comment]
> A fix for this bug is included in https://github.com/minetest/minetest/pull/14087 because I had to rewrite the relevant code anyway. I can make a separate PR just for the bugfix if you want.

@grorp If you don't mind - I would prefer to have a fix in a separate PR so that it doesn't get lost (e.g. due to revert) and can be merged independently.

**Comment by grorp** [comment]
@SmallJoker I tested creating a separate bugfix commit/PR. It resulted in many conflicts with #14087, which is ready to merge, and the code will be removed by #14087 anyway. I think it's not worth it. Would you be okay with merging #14087 as is, including the bugfix?
