### ISSUE TITLE
`fs::PathStartsWith` works dubiously when `prefix == ""` on Windows because of drive letters

### ISSUE THREAD

**Issue by asrelo** [minetest/minetest#14194]
**Minetest versions affected**
5.8.0 (5.8.0-dev up to 431444ba9f6a57b8105adcaeed9451fd77605fc5)
supposedly back to year 2013 (967121a34bbc60e6b46c7ec470b151f668ef1fef)

**OS**
Windows 10

This describes calls to function `fs::PathStartsWith(const std::string &path, const std::string &prefix)` when `prefix == ""` (empty string).
When `path` is an absolute UNIX path (i.e. "/" or "/some/path"), the function returns true.
When `path` is an absolute Windows path (i.e. "C:\\"` or "C:\\some\\path\\"), the function returns false.

`fs::PathStartsWith` currently treats empty `prefix` the same as if it was just a dir delimiter (not just DIR_DELIM though). It may be justified to treat empty `prefix` as a path to single root. Right now it's unclear if it's intended.

Also, because of this, unit test `TestFileSys.testPathStartsWith` fails on Windows. It wrongly asserts that `fs::PathStartsWith("C:\\", "")`, `fs::PathStartsWith("C:\\home\\user\\minetest", "")` and so on return true:

```
======== Testing module TestFilePath
[PASS] testIsDirDelimiter - 0ms
Test assertion failed: starts == true
    at test_filepath.cpp:142
[FAIL] testPathStartsWith - 4ms
[PASS] testRemoveLastPathComponent - 0ms
[PASS] testRemoveLastPathComponentWithTrailingDelimiter - 0ms
[PASS] testRemoveRelativePathComponent - 1ms
```

Suggested ways to fix:
1. Change behavior of `fs::PathStartsWith` to always return true when `prefix == ""`.
2. Leave behavior of `fs::PathStartsWith` as is, add a comment explaining how it treats empty `prefix`. Change the unit test to account this (it already has code to work differently on Windows and elsewhere).

Currently, `fs::PathStartsWith(const std::string&, const std::string&)` is rarely used in codebase, and I can't easily tell whether it could realistically affect something in existing code.

P.s. Strangely, I found 0 information about the failing unit test. The issue may be useful if someone stumbles on it later.

edit: less inline code...
edit: minor silliness

**Comment by sfan5** [comment]
`""` does not refer to a proper path so I think the function should just return `false`.

Looking at the unit test it doesn't reveal a special reason why it should be returning true or when that is useful.
