### ISSUE TITLE
Alpha-blending entities disappear completely when enable_shaders=false and alpha <= 127

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#14204]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Active renderer

OpenGL 4.2

### Irrlicht device

X11

### Operating system and version

Debian GNU/Linux 12 (bookworm) x86_64

### CPU model

Intel i5-3320M (4) @ 3.300GHz

### GPU model

Intel 3rd Gen Core processor Graphics Controller

### OpenGL version

4.2 (Compatibility Profile) Mesa 22.3.6

### Summary

Entities with alpha blending (semi-transparent texture and use_texture_alpha = true) are completely transparent when enable_shaders = false in MT config

### Steps to reproduce

- Set enable_shaders = false in MT
- Install the **Citadel** game, version https://github.com/Irevol/minetest-citadel/commit/a926d4cf3d5f482656bc8edceb2995f949ca014b or earlier (before a workaround was added for this issue)
- Teleport/travel to (5, 2, 12)
- Look south and upwards, and see (or don't) the ghost

**With shaders disabled** the ghost is invisible.

![screenshot_20240101_155727](https://github.com/minetest/minetest/assets/324806/b6a0e6c6-70a0-4d24-8a62-48a150db0693)

**With shaders enabled** the ghost appears correctly.

![screenshot_20240101_155832](https://github.com/minetest/minetest/assets/324806/faded2b6-124c-449b-b1b8-03b924b90b1b)

**Comment by regulus79** [comment]
I can confirm that am experiencing this bug as well, particularly with the entities in Citadel.
