### ISSUE TITLE
Dehardcode death menu

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14218]
### Problem

I can't make a custom death menu without annoying hacks probably resulting in bugs

### Solutions

Give modders the ability to override the death menu

### Alternatives

I don't know

### Additional context

I could open an identical issue for the pause menu but I'm lazy

**Comment by cx384** [comment]
Currently the death menu is  fully client managed, and can already be overwritten with CSM.
https://github.com/minetest/minetest/blob/2766c70ad3b32f61b6f8f5bbcb2af9cfd38c6cef/src/client/game.cpp#L2899-L2904
(You have the override the `minetest.registered_on_death` table to get rid of the builtin one, but it's not too problematic.)

So when SSCSM gets added the server could also change it.

However, imo the death screen should be fully server managed and not just triggered by a ClientEvent.
Maybe this will also fix #7879.

**Comment by p-ouellette** [comment]
I made the death formspec server-sent in #8014. I don't think this can work without breaking compatibility -- a new client connecting to an old server would not get a death screen.

**Comment by appgurueu** [comment]
> I don't think this can work without breaking compatibility -- a new client connecting to an old server would not get a death screen.

Could you elaborate on why compatibility would need to be broken? A new client could still listen to those packets and display a "default" death formspec accordingly, then send the appropriate packet when that is submitted.

**Comment by p-ouellette** [comment]
> Could you elaborate on why compatibility would need to be broken? A new client could still listen to those packets and display a "default" death formspec accordingly, then send the appropriate packet when that is submitted.

You're right, I didn't think of that.

**Comment by garymm** [comment]
@cx384 could you show an example of overriding minetest.registered_on_death? I have been unable to do it. Every time I access it, it is nil. But maybe I'm just not even enabling client-side modding properly? I have this in minetest.conf:
`enable_client_modding = true`

Though I never see anything logged from `Client::loadMods()`.

**Comment by appgurueu** [comment]
Client-side modding is client-side. Are you using this in a client-side mod? I'm pretty sure it works there.

Note that trying to use client-side API functions in a server-side mod will *not* work.

**Comment by cx384** [comment]
As appgurueu wrote, you need to do this in a Client Side Mod (CSM). `minetest.register_on_death()` does only exist for server mods.
Look here to learn more about client side modding.
https://github.com/minetest/minetest/blob/master/doc/client_lua_api.md

However, I suspect you actually don't want to use CSM, since every client has to install them independent.
Maybe you could implement a workaround using `player:on_death(self, killer)`, until the death menu is fully customizable by the server.
