### ISSUE TITLE
macOS Full Screen setting doesn't work

### ISSUE THREAD

**Issue by ShadowRoi** [minetest/minetest#14216]
### Minetest version

```true
Minetest 5.8.0
```

### Active renderer

OpenGL 2.1

### Irrlicht device

OSX

### Operating system and version

macOS Sonoma 14.1

### CPU model

Apple M1 Pro

### GPU model

Apple M1 Pro

### OpenGL version

2.1

### Summary

The settings: Window maximized and Full Screen on graphic settings are broken. The Full Screen button doesn't do anything and Window maximized also doesn't do anything. However it's worth noting that the Window maximized even if it's turned on if you close the game and enable it again it's always unchecked.
<img width="438" alt="image" src="https://github.com/minetest/minetest/assets/105967373/78e6cf91-3b96-4268-80fe-54cb735aee5d">

### Steps to reproduce

Open minetest -> turn on full screen and window maximized settings -> Restart Minetest, Minetest doesn't open in full screen

**Comment by rubenwardy** [comment]
`[x] Remember screen size` will be setting window maximized. Window maximized should be hidden if "remember screen size" is checked

The fullscreen thing is probably a bug on MacOS specifically

**Comment by ShadowRoi** [comment]
Your right, when `Remember screen size` is off the window maximized does stay enabled even after restart, so it's just the Full screen problem.

**Comment by sfan5** [comment]
It's simply not implemented for macOS:
https://github.com/minetest/irrlicht/blob/a2b6244f543da5c80d2c4c0fbb8e9e7c631bb03b/source/Irrlicht/CIrrDeviceOSX.mm#L658
This will start working again when we have SDL2.

**Comment by rollerozxa** [comment]
> This will start working again when we have SDL2.

Fullscreen does indeed work now with the SDL2 device enabled on macOS.
