### ISSUE TITLE
unexpected behavior related to stack size in register_on_player_inventory_action callback

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#14210]
### Minetest version

```true
Minetest 5.9.0-dev-55f40a7f8 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1699392533
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Linux nail 6.6.1-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Nov  9 04:27:49 UTC 2023 x86_64 GNU/Linux

### Summary

@Niklp09 noticed that blocks went missing when shift-clicking shaped blocks using the invsaw of my [moreblocks/stairsplus fork](https://github.com/fluxionary/minetest-moreblocks). i've finally been able to reproduce exactly why that happens, which is because either the "count" value passed with the info to `minetest.register_on_player_inventory_action` is wrong, or i'm not understanding how to interpret the that value correctly. https://github.com/minetest/minetest/blob/995c19287468a5733956fdba028f940901d4d1d5/doc/lua_api.md?plain=1#L5713

### Steps to reproduce

download and use the following mod: https://github.com/fluxionary/minetest-invbug. it has no requirements.

in game, run the `/invbug` command. shift-click the stack of 33 items. then shift-click the stack of 99 items. you will see the following output in chat:

```
took 33 (from_stack="" to_stack="invbug:item 33")
took 99 (from_stack="invbug:item 33" to_stack="invbug:item 99")
took 33 (from_stack="invbug:item 66" to_stack="invbug:item 33")
```

both bottom entries are generated by the second shift-click. the first indicates that the stack of 33 in the first slot now has 99 items in it, and the second indicates that a new stack of 33 was created. the last line in particular makes little sense to me.

if these numbers are correct, can someone explain how to properly calculate the number of items that were moved (should be 132 in total).

**Comment by SmallJoker** [comment]
After #12595 this mod + test sequence gives the following output:
```
took 33 (from_stack="" to_stack="invbug:item 33")
took 66 (from_stack="invbug:item 33" to_stack="invbug:item 99")
took 33 (from_stack="invbug:item 66" to_stack="invbug:item 33")
```
The `took` counter will sum up and `to_stack` is the final stack.

**Comment by appgurueu** [comment]
I think this output is reasonable: First you take 33. Then shift clicking creates an action equivalent to two inventory actions, moving 66 items to one slot and 33 items to another. This can not and should not be captured by a single inventory action due to the `index` parameters being passed to this callback.
