### ISSUE TITLE
Opening inventory should be an inventory action

### ISSUE THREAD

**Issue by kromka-chleba** [minetest/minetest#14228]
### Problem

Currently there's no way to tell when a player opened their inventory so to refresh/change its state, hacks like using `minetest.register_on_dignode` or `minetest.register_on_punchnode` are needed.
`minetest.register_on_player_receive_fields` isn't helping either, because opening the inventory doesn't trigger this either.

Edit: using `on_dig` and `on_punch` callbacks is problematic because it overwrites functions registered with `minetest.register_on_dignode` or `minetest.register_on_punchnode`.

### Solutions

Making opening the inventory an action recognized by `minetest.register_on_player_inventory_action` would solve the problem.

### Alternatives

Allowing to register multiple callbacks for one node I guess.

**Comment by Izzyb1234** [comment]
This forum post is related and provides a possible workaround in the short term for other actions that should be covered also.

https://forum.minetest.net/viewtopic.php?t=29455&sid=73635b11a567efded990f5f3cce94c41

**Comment by wsor4035** [comment]
this appears to be a combination of two or more separate issues.

see https://github.com/minetest/minetest/issues/11776 regarding opening of inventory

> Edit: using on_dig and on_punch callbacks is problematic because it overwrites functions registered with

a modder can choose to honor/run these if they wish
