### ISSUE TITLE
minetest.request_http_api() doesn`t work and secure.http_mods doesn`t help, as even disabling mod security

### ISSUE THREAD

**Issue by Sovenok-Hacker** [minetest/minetest#14221]
### Minetest version

```true
Minetest 5.9.0-dev-55f40a7f8-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1700008891
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Active renderer

OpenGL 4.6

### Irrlicht device

X11

### Operating system and version

Arch Linux

### CPU model

Intel Core i3-10100

### GPU model

Intel Integrated graphics

### OpenGL version

4.6

### Summary

I am going to create my own Minetest server, so I created a simple Python API and trying to connect to it from patched mod atm. But minetest.request_http_api() always returns nil.

### Steps to reproduce

I used this code: `
local http = minetest.request_http_api()

if http == nil then
    error("HTTP API connection was disallowed")
end

function refreshBalanceCallback(r)
if not r.succeeded then
    error("Error sending HTTP request to API backend")
end
local data = decode(r.data)
if not r.ok then
    minetest.log("debug", r.err)
return
end
atm.balance[name] = r.balance
end

function updateBalance(name)
http.fetch({url=atm.api .. "/balance", data=encode({username=name})}, refreshBalanceCallback)
end
`

**Comment by rubenwardy** [comment]
What's the value of your secure.http_mods? Is this code in init.lua?

**Comment by Sovenok-Hacker** [comment]
> What's the value of your secure.http_mods? Is this code in init.lua?

Here is my minetest.conf:
```
screen_h = 1008
screen_w = 1920
maintab_LAST = about
update_last_known = 5008000
update_last_checked = 1704569522
menu_last_game = minetest
doubletap_jump = false
connected_glass = true
aux1_descends = false
keymap_increase_viewing_range_min = KEY_PLUS
keymap_decrease_viewing_range_min = KEY_MINUS
autojump = false
enable_waving_water = true
keymap_cmd_local = KEY_PERIOD
remote_port = 30000
no_mtg_notification = true
name = barnowl_linux_kde
keymap_inventory = KEY_KEY_1
address = minetestserver.ru
enable_waving_plants = true
enable_waving_leaves = true
sound_volume = 0.0500000007
mute_sound = true
enable_damage = true
creative_mode = true
server_announce = false
selected_world_path = /home/owl/.minetest/worlds/asuna
mainmenu_last_selected_world = 2
enable_server = false
wieldview_update_time = 2
enable_fog = true
wieldview_node_tiles = false
noclip = false
block_send_optimize_distance = 4
max_block_send_distance = 12
free_move = false
fast_move = true
creative = false
spawn_mobs = true
stamina.exhaust_lvl = 160
stamina.starve_lvl = 0
world_config_selected_mod = 20
texture_path = /home/owl/.minetest/textures/soothing32/
secure.http_mods = atm
show_technical_names = false
show_advanced = true
```

**Comment by Sovenok-Hacker** [comment]
> What's the value of your secure.http_mods? Is this code in init.lua?

Is this code in init.lua? No, it`s in netbalanceupdate.lua, and `dofile(modpath .. "/netbalanceupdate.lua")`

**Comment by Sovenok-Hacker** [comment]
Thanks, it works now.
