### ISSUE TITLE
PseudoRandom() broken for negative seeds in Android build

### ISSUE THREAD

**Issue by j-r** [minetest/minetest#14237]
### Minetest version

```true
Minetest-5.8.0 Android build from github release page (both 32 and 64 bit)
```

### Operating system and version

Android X

### Summary

All (at least it seems that way, but I haven't checked every value) negative seeds produce the same PseudoRandom sequence.

With the reproducer below you'll notice a neat grid of identical looking villages all named ``House Ndean``. When doing the same on a X86 system you'll get the expected random looking distribution of different village flavours.

With the 64 bit build there are only these degenerated villages visible, because the seed used in the reproducer forces all PseudoRandom seeds chosen by mg_villages to be negative (because the world seed as seen by mg_villages when looking into mapgen parameters gets mangled into a large negative number). The 32 bit build is slightly different, because the world seed is mangled like on x86 into a positive number not large enough to affect mg_villages seed generation so that negative seeds are chosen only for some map positions. This might be a different bug, but it is also possible to result from the same root cause, possibly an unintended typedef for some of the integer types used in these code paths.

When looking at the sequence generated by various seeds to PseudoRandom (using the same range parameters as mg_villages uses, see below for code) I get on x86:

```
1099511627776: 1, 29, 69
1048576: 322, 60, 68
2: 110, 17, 0
1: 39, 79, 33
0: 1, 29, 69
-1: 331, 9, 22
-2: 260, 38, 57
-3: 222, 21, 10
-4: 152, 50, 46
-5: 114, 31, 79
-6: 43, 60, 34
-7: 5, 42, 67
-8: 335, 72, 23
-9: 297, 21, 56
-1024: 312, 2, 66
-1048576: 49, 76, 37
-1073741824: 386, 45, 52
```

On Android (both the 32 and 64 bit builds) all negative seed values generate the same sequence as seed 0 instead:

```
1099511627776: 1, 29, 69
1048576: 322, 60, 68
2: 110, 17, 0
1: 39, 79, 33
0: 1, 29, 69
-1: 1, 29, 69
-2: 1, 29, 69
-3: 1, 29, 69
-4: 1, 29, 69
-5: 1, 29, 69
-6: 1, 29, 69
-7: 1, 29, 69
-8: 1, 29, 69
-9: 1, 29, 69
-1024: 1, 29, 69
-1048576: 1, 29, 69
-1073741824: 1, 29, 69
```
The excerpt from mg_villages code to generate these first three numbers for a seed is:

```
local function checkSeed(seed, x, z)
        local pr = PseudoRandom(seed)
        local chance = pr:next(1, 400)
        local xx = pr:next(x, x + 79) - x
        local zz = pr:next(z, z + 79) - z
        minetest.log("warning", ""..seed..": "..chance..", "..xx..", "..zz)
end
 ```

### Steps to reproduce

Reproducer that uses mg_villages to trigger the problem: (Obviously one could just create a small program to check on PseudoRandom instead, but this is much easier to do on an Android device without any development tools:-)
1. Download and install Android build from github release page (either 32 or 64 bit) on a suitable device (I only tested on Android X), at least 5.7.0 and 5.8.0 exhibit the problem (the F-Droid version is affected, too)
2. Download minetest_game and mg_villages (+handle_schematics) from content db
3. Create new minetest_game world with seed 14660361307355168731 (nicely triggers the problem)
4. Enable mg_villages mod
5. Start the World
6. When the spawn point has generated (might take some time, because it places quite a lot of villages due to the bug) issue ``/vmap`` command

**Comment by sfan5** [comment]
I didn't try the reproduction steps but I wrote the following unittest code (with the results I got on x86), ran it on Android and couldn't find a test failure:
![grafik](https://github.com/minetest/minetest/assets/1042418/e5bc8ec5-0b2e-4120-95ec-17c0212ff1da)

So could be the numbers go wrong on the way from Lua to C++.

**Comment by j-r** [comment]
> So could be the numbers go wrong on the way from Lua to C++.

Possibly, I just noticed that mg_villages uses ``register_on_mapgen_init`` to get the world seed and it looks like the mangling of the world seed value happens in the wrapped ``get_mapgen_params`` when converting the world seed into a Lua integer. At least ``get_magen_setting("seed")`` gives the actual seed correctly even on Android.

So the problem could be the conversion of ``lua_number`` to ``u64`` in ``src/script/lua_api/l_noise.cpp:436``?? (I have close to zero C++ knowledge and no infrastructure to do an android build:-)

**Comment by sfan5** [comment]
Found the issue and included a fix in a PR I have open.

**Comment by j-r** [comment]
> Found the issue and included a fix in a PR I have open.

Thank you!

**Comment by j-r** [comment]
It looks like this fix might change the behavior of PseudoRandom for seed values that exceed s32 range on all systems. E.g. +/- 2^40 was equivalent to 0 before, now it produces a slightly different sequence (using the code above) in my local x86 32 bit build (I may have done something stupid, though:-):
```
1099511627776: 2, 28, 68
```
 Could this be a problem for existing worlds or are these seed values considered undefined behavior?

**Comment by j-r** [comment]
Also it looks like PcgRandom has the same problem with negative seeds all generating the same sequence as seed 0 on Android. Something seems wrong with number conversion from Lua on Android.

**Comment by sfan5** [comment]
> Could this be a problem for existing worlds or are these seed values considered undefined behavior?

This was of course never documented but the function never support more than 32-bits so as far as I'm concerned that's user error.

> Also it looks like PcgRandom has the same problem with negative seeds all generating the same sequence as seed 0 on Android.

The integer conversion is a peculiar issue but not relevant in this case. PcgRandom only accepts unsigned numbers as seed.

**Comment by j-r** [comment]
> > Could this be a problem for existing worlds or are these seed values considered undefined behavior?
> 
> This was of course never documented but the function never supported more than 32-bits so as far as I'm concerned that's user error.
> 
> > Also it looks like PcgRandom has the same problem with negative seeds all generating the same sequence as seed 0 on Android.
> 
> The integer conversion is a peculiar issue but not relevant in this case. PcgRandom only accepts unsigned numbers as seed.

I'm fine with that and I see that you added some documentation. Thank you!

How about adding something like the following on top (sorry, I'm too stupid to rebase this onto your MR)?

```
  diff --git a/doc/lua_api.md b/doc/lua_api.md
  index a85bb8152..2ca814292 100644
  --- a/doc/lua_api.md
  +++ b/doc/lua_api.md
  @@ -8059,6 +8059,10 @@ offering very strong randomness.

   It can be created via `PcgRandom(seed)` or `PcgRandom(seed, sequence)`.

  +Seed must be a non negative integer number. For other seed values PcgRandom
  +may exhibit platform dependent undefined behavior, including generating non
  +random sequences.
  +
   ### Methods

   * `next()`: return next integer random number [`-2147483648`...`2147483647`]
  @@ -8154,6 +8158,10 @@ Uses a well-known LCG algorithm introduced by K&R.

   It can be created via `PseudoRandom(seed)`.

  +Seed must be in the range -2^31...2^31-1. For other seed values PseudoRandom
  +may exhibit platform dependent undefined behavior, including generating non
  +random sequences.
  +
   ### Methods

   * `next()`: return next integer random number [`0`...`32767`]
```
