### ISSUE TITLE
"Sound queue ran empty" with pitch shift

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#14248]
### Minetest version

```true
Minetest 5.9.0-dev-55f40a7f8 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1699392533
BUILD_TYPE=SemiDebug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Linux nail 6.6.8-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Dec 21 16:21:45 UTC 2023 x86_64 GNU/Linux

### Summary

#13633 seems to have fixed most instances of a related error, but it still happens sometimes, apparently for looped sounds with pitch change. 

```
WARNING[OpenALSoundManager]: PlayingSound::stepStream: Sound queue ran empty for "queue_wind.ogg"
```

### Steps to reproduce

1. get this mod https://github.com/fluxionary/minetest-soundqueueempty
2. run `/test_sound_queue`
3. check client logs

**Comment by Desour** [comment]
Known issue, see this buried comment:
https://github.com/minetest/minetest/pull/12764#issuecomment-1507499250
I didn't think it would be an issue in practice, and hence didn't care. Thanks for reporting.
I guess this needs to be fixed then.

**Comment by fluxionary** [comment]
> You could also increase the sample rate of your sound file

oh, that's a great suggestion. thanks! increasing the pitch of this file with audacity or soundstretch resulted in something that sounded absolutely horrible, but this works just fine.
