### ISSUE TITLE
Entity lost selection box when set_rotation

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#14257]
### Minetest version

```true
Minetest 5.8
```

### Active renderer

OpenGL

### Irrlicht device

X11

### Operating system and version

Debian 12

### Summary

Entities with selection_box with rotate = true lost its selection_box after a set_rotation.

### Steps to reproduce

1. Put an attached entity with a selection box with rotate = true
2. Wait the entity to move (rotate)
3. Make a set_rotation
4. Try to hit the entity. No selection box!

**Comment by appgurueu** [comment]
Thanks for the report, I'll look into this. I suspect this might be related to attachments. Are you sure that your reproduction steps are complete? Could it be that the entity in question (the "wagon") is attached?

The test entities in devtest that were used to test rotating selectionboxes have `rotate = true` and have their rotation set, yet they do have selection boxes.

**Comment by runsy** [comment]
> Thanks for the report, I'll look into this. I suspect this might be related to attachments. Are you sure that your reproduction steps are complete? Could it be that the entity in question (the "wagon") is attached?
> 
> The test entities in devtest that were used to test rotating selectionboxes have `rotate = true` and have their rotation set, yet they do have selection boxes.

Yes it is attached.

**Comment by appgurueu** [comment]
Please provide a proper minimal test mod for reproducing this issue. Currently, I can't reproduce it. I first tried attaching entities to rotating entities, but that worked fine. I then tried the same with bones + animation, but that worked fine too:

![Screenshot from 2024-01-23 14-07-15](https://github.com/minetest/minetest/assets/34514239/e1dc5d07-4261-455a-b1f9-4ea4633a342d)

**Comment by runsy** [comment]
> Please provide a proper minimal test mod for reproducing this issue. Currently, I can't reproduce it. I first tried attaching entities to rotating entities, but that worked fine. I then tried the same with bones + animation, but that worked fine too:
> 
> ![Screenshot from 2024-01-23 14-07-15](https://private-user-images.githubusercontent.com/34514239/298950690-e1dc5d07-4261-455a-b1f9-4ea4633a342d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDc5OTUsIm5iZiI6MTcwNjEwNzY5NSwicGF0aCI6Ii8zNDUxNDIzOS8yOTg5NTA2OTAtZTFkYzVkMDctNDI2MS00NTVhLWIxZjktNGVhNDYzM2EzNDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDE0NDgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkZmQ0YWI3ZmY0M2M0M2ZiMGJkOWY3MjdlMTgxNDc3YzQ2ZTBhYzY5N2Q0OWQ4NGUwMmJiN2Y4MzMxYWM4YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ym-jUUzPMiDGfY1DEf4WmkbL1B9mMFZG2mLwi_wnbIU)

Could you download and install this version of Petz?
https://github.com/runsy/petz/tree/54a77ca06eedf5c34a2b9d60ec773dfba82010eb

1) Put a pony
2) Put  wagon on pony (right click)
3) Mount on the wagon (right click)
4) Drive the wagon to a diferent angle.
5) Unmount the wagon  (right click on pony)
6) Try the selection box

The behaviour depends of the angle of attack:
![Sin nombre](https://github.com/minetest/minetest/assets/13217027/47998dbd-41eb-42ef-9bb9-4b72547d7884)
![Sin nombre](https://github.com/minetest/minetest/assets/13217027/401c4f22-3709-4862-b0c7-8f75169fef2e)

**Comment by appgurueu** [comment]
Please try to provide a *minimal* example mod. Petz is far from minimal; it has many other features that make debugging harder. I cloned petz and checked out [54a77ca06eedf5c34a2b9d60ec773dfba82010eb](https://github.com/runsy/petz/tree/54a77ca06eedf5c34a2b9d60ec773dfba82010eb), created a fresh MTG (472997b4aa7e3f480fef0f4a401b8857761e681b) world, and joined, and after a few seconds I get crashes like:

```
2024-01-24 20:07:13: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'petz' in callback luaentity_Step(): /home/lars/minetest/bin/../mods/petz/kitz/engine.lua:856: attempt to index field 'lastvelocity' (a nil value)
2024-01-24 20:07:13: ERROR[Main]: stack traceback:
2024-01-24 20:07:13: ERROR[Main]: 	/home/lars/minetest/bin/../mods/petz/kitz/engine.lua:856: in function 'stepfunc'
2024-01-24 20:07:13: ERROR[Main]: 	...lars/minetest/bin/../mods/petz/petz/api/api_register.lua:199: in function <...lars/minetest/bin/../mods/petz/petz/api/api_register.lua:198>
```

**Comment by DragonWrangler1** [comment]
I have been able to find the collision box sometimes when this happens, but it’s way off and much much smaller.

**Comment by appgurueu** [comment]
> I have been able to find the collision box sometimes when this happens, but it’s way off and much much smaller.

Interesting. I have no idea how that could happen. Scales aren't propagated, only rotations. This might hint towards a mod bug.
