### ISSUE TITLE
`test_mapgen_edges` test runtime regression

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14261]
this is causing the random CI failures right now

* "Code style: Use non-static member initialisation instead of member in…" **1308ms**
* "Slight optimizations in ClientMap" **1869ms**
* "Allow active blocks to be generated" **9485ms**
* "Don't enable relative mouse mode if in touchscreen mode" **timeout failure**
* "Write down some developer documentation" **8900ms**

so looks like #14185 is the culprit

**Comment by sfan5** [comment]
The test is here:
https://github.com/minetest/minetest/blob/92c55c27cf520bd7b0e59639cc7cce7bcaf5d747/games/devtest/mods/unittests/misc.lua#L119

**Comment by lhofhansl** [comment]
So I took a quick look.
All that #14185 is allow active block to be put on the emerge queue with an option to generate if they do not exist, yet.
There is a check in `EmergeThread::run()` to avoid going over the map limits, the same check that's in `RemoteClient::GetNextBlocks`.

I admit I do not quite understand what this test is trying to do.
Obviously not active block can cause more blocks to be generated. Somehow we'd want to disable active blocks for this test.

**Comment by lhofhansl** [comment]
I looked through some of the recently failed runs and `test_mapgen_edges` did not seem to be problem. Could you point me to a run?

**Comment by lhofhansl** [comment]
I also ran that test a few 100 times locally, and it always passed.

**Comment by sfan5** [comment]
I should have provided more context:

The tests run with a timeout of 15s. GH actions seems to be slower in general but the suspect commit has increased the runtime ~5x which causes the CI to fail randomly.
We can of course increase the timeout but if there's some other problem here it'd be good to fix it.

I don't see how the commit might be directly causing this either. Some guesses:
* There's a bug somewhere that causes the emerge queue to be full, which causes increased runtime
* The emerge queue is just fuller than usual because more blocks are emerged now (duh)

Thinking about it a bit more it's probably just the latter. We could additionally set `active_block_range=1` in the test script.

**Comment by sfan5** [comment]
Okay yes, it was just that: https://github.com/sfan5/minetest/actions/runs/7527774608/job/20488586665#step:6:216

**Comment by sfan5** [comment]
1b0d2a37b

**Comment by lhofhansl** [comment]
Than you @sfan5 . Today makes sense.
