### ISSUE TITLE
Server accepts any string(version/language) the client sends

### ISSUE THREAD

**Issue by blaboing** [minetest/minetest#14262]
### Minetest version

```true
Minetest 5.9.0
```
### Summary

Server just accepts any string the client sends as `lang_code` or `client_version`(debug build only) and hands it over to lua side `get_player_information` unfiltered.
Might be better to limit them to the same allowed chars like playernames or atleast add a warning to get_player_information documentation.

example color escaped strings
![fancy](https://github.com/minetest/minetest/assets/56389853/6e3f66af-33be-4fe9-bbcc-1edc882c8611)

### Steps to reproduce

repro mod code
```lua
minetest.register_on_joinplayer(function(player)
	local info = minetest.get_player_information(player:get_player_name())
	minetest.chat_send_all("version_string: "..info["version_string"].."\nlang_code: "..info["lang_code"])
	end
)
```
- run a **debug** build world with the repro mod above
- join with a client that has a modified `client_version` and/or `lang_code` set

**Comment by SmallJoker** [comment]
The `lang_code` could roughly be sanity-checked against the pattern `[A-z_-]{,20}` if necessary.

What about the client version? Anything other than `[0-9\.]+(\-dev)?(\-[0-9a-f]+)?(-dirty)?` ? This is a huge mess. From a technical standpoint, the client version is not reliable and should not be used for anything other than debugging (which the build type already implies).

**Comment by appgurueu** [comment]
> What about the client version?

What about just checking that it's ASCII printable characters only?

**Comment by sfan5** [comment]
Added a fix to my PR.

**Comment by oong819** [comment]
This can be potentinal security hole
