### ISSUE TITLE
Deleting a single mapblock mesh can take up to 50ms without shader and a large viewing_range

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#14278]
### Minetest version

```true
Minetest built from master
```

### Irrlicht device

X11

### Operating system and version

Linux, Fedora 38

### CPU model

Intel

### GPU model

NVidia

### Summary

I was trying MT without shader and large viewing_ranges and notices the dtime jitter goes quickly to over 1000% and every few frames the rate drops dramatically.

I traced it to this one line: https://github.com/minetest/minetest/blob/master/src/client/client.cpp#L601
This single delete can take up 50ms.
Note that when shaders are enabled this same delete take 0.5ms max (so it's 100x slower without shaders).

That makes no sense to me...  I assume it's another inefficiency in Irrlicht. I had no time to check it out, yet. Just parking it here.

Maybe @appgurueu has an idea...?

### Steps to reproduce

Load any world. Set viewing_range to a large value (1000) along with the relavant _distance settings. Shaders off.
Observe very jittery FPS and drawtime in the debug view. Some frames take over 100 ms to render (that is a for single frame).
This most pronounced when client_mesh_chunk is set to 8 or larger. (When that setting is smaller each individual mesh deletes faster, but you have more.)
With client_mesh_chunk = 16 this can go up to 120ms... And remember, this for deleting a *single* mesh!!

**Comment by sfan5** [comment]
IMO we should be considering closely whether to invest any significant time into fixing problems for the (shader-less) legacy rendering pipeline.

**Comment by Desour** [comment]
Still, a little easy investigation doesn't hurt: I found out that destructing `MapBlockMesh::m_daynight_diffs` takes most of the time.
It's apparently a std::map that stores daylight color stuff per vertex. One rbtree allocation/free per vertex is ofcourse not good.
(Idk if worth fixing. *shrug*)

**Comment by appgurueu** [comment]
> It's apparently a std::map that stores daylight color stuff per vertex. One rbtree allocation/free per vertex is ofcourse not good. (Idk if worth fixing. _shrug_)

What if we replaced that with an unordered map? Then we'd have a single free. Seems low effort. We'd have to implement hashing for vertices, though.

**Comment by lhofhansl** [comment]
> IMO we should be considering closely whether to invest any significant time into fixing problems for the (shader-less) legacy rendering pipeline.

I agree in general and I always use shaders on. One time I had some off by accident and noticed this severe slow-down and stuttering. If the non-shader pipeline does not work, we might want to consider disabling this.

**Comment by lhofhansl** [comment]
BTW. I am also looking into why the "draw scene" time are sometimes so much larger than what "drawing the vertices" reports. I assume there is likewise some overhead somewhere.

**Comment by sfan5** [comment]
closing due to #15421
