### ISSUE TITLE
Command make package omits game directory

### ISSUE THREAD

**Issue by nolt** [minetest/minetest#14272]
### Minetest version

```true
Minetest 5.8.0
```

### Operating system and version

Ubuntu 22.04

### Summary

In mine docker build process I git mintest_game, after compiling and 
_make package_ command i get server package for minetest but without game folder.

```
root@d5694acc0884:/opt/minetest# ls
CMakeCache.txt  COPYING.LESSER           LICENSE.txt      android  clientmods           fonts                 minetest-5.8.0-linux         mods      util
CMakeFiles      CPackConfig.cmake        Makefile         bin      cmake                games                 minetest-5.8.0-linux.tar.gz  po        worlds
CMakeLists.txt  CPackSourceConfig.cmake  README.md        builtin  cmake_install.cmake  install_manifest.txt  minetest.conf.example        src
CNAME           Dockerfile               _CPack_Packages  client   doc                  lib                   misc                         textures
root@d5694acc0884:/opt/minetest# tar vft minetest-5.8.0-linux.tar.gz | grep games
root@d5694acc0884:/opt/minetest# echo $?
1
root@d5694acc0884:/opt/minetest#
```

↓↓↓ why this works?

If I add -INSTALL_DEVTEST=TRUE
_make package_ command packs whole game directory

```
root@220c0d6fe2f4:/opt/minetest# tar vft minetest-5.8.0-linux.tar.gz | grep games | tail -n1
-rw-r--r-- root/root       125 2024-01-18 09:05 minetest-5.8.0-linux/games/devtest/LICENSE.txt
```

### Steps to reproduce

- install all dependencies
- compile
- make package
```
git clone https://github.com/minetest/minetest.git -b stable-5
cd minetest/
git clone --depth 1 https://github.com/minetest/minetest_game.git minetest-5.8.0-linux/games/minetest_game
git clone --depth 1 --branch "$(cat misc/irrlichtmt_tag.txt)" https://github.com/minetest/irrlicht.git lib/irrlichtmt

cmake . -DRUN_IN_PLACE=TRUE -DBUILD_SERVER=TRUE -DBUILD_CLIENT=FALSE -DENABLE_POSTGRESQL=OFF -DENABLE_REDIS=OFF -DENABLE_SOUND=OFF
make -j$(nproc)
make package
```

**Comment by nolt** [comment]
If I add -INSTALL_DEVTEST=TRUE
_make package_ command packs whole game directory

```
root@220c0d6fe2f4:/opt/minetest# tar vft minetest-5.8.0-linux.tar.gz | grep games | tail -n1
-rw-r--r-- root/root       125 2024-01-18 09:05 minetest-5.8.0-linux/games/devtest/LICENSE.txt
```

**Comment by rollerozxa** [comment]
Minetest Game is no longer bundled with the engine, so it won't be installed by CMake. You will need to clone Minetest Game or another game of your choice on the server.

`INSTALL_DEVTEST` is an option that allows you to install devtest since it's still available in the source tree but doesn't get installed with the engine anymore by default. It was a compromise in order to make devtest not ship with engine releases anymore, see https://github.com/minetest/minetest/pull/13081. For obvious reasons you shouldn't run a public server with devtest either since it has a bunch of testing utilities available to all players.

**Comment by nolt** [comment]
Yes I know about minetest game is not included. 
But how to force to _make package_ command pack game folder (even if it's empty). I usually prepare ready to go packages with desired games and in 5.7 I was able to create it no matter if I clone minetest_game or anything else using _make package_ command. Now simply I cant do it, cuz I need to pack it again.

**Comment by Zughy** [comment]
I've run `make package` with devtest and mtg installed and the `/games` folder wasn't created anyway

**Comment by sfan5** [comment]
Everything mentioned here is working as intended.
Minetest is not supposed to package the games and mods you may have installed when creating a package.
If you want to do that modify the package file or CMake scripts to suit your needs.
