### ISSUE TITLE
Passing irrlicht via IRRLICHTMT_BUILD_DIR client build cannot find -lSDL2::SDL2

### ISSUE THREAD

**Issue by Bastrabun** [minetest/minetest#14310]
### Minetest version

```true
2b99dabdac823fee3ea843a9ded8bbe7718c3b44
```

### Active renderer

OpenGL 4.6

### Irrlicht device

Wayland

### Operating system and version

debian testing

### CPU model

5800X

### GPU model

Radeon 6600

### OpenGL version

4.6

### Summary

I am trying to build MT with irrlicht not in the lib folder. I do not want to duplicate irrlicht for the many MT clients, but share it via IRRLICHTMT_BUILD_DIR

myuser@mymachine:~$ dpkg -l | grep libsdl2-dev
ii  libsdl2-dev:amd64                       2.28.5+dfsg-3                     amd64        Simple DirectMedia Layer development files

The client does not build, the server does. If I place irrlicht in the lib directory, the client builds fine.

mientest commit 2b99dabdac823fee3ea843a9ded8bbe7718c3b44
irrlicht commit 4299ee21d8c0e4fb361e1042bda1a0a9ddbeb60e

What happens?

During client build I get this:

[ 86%] Building CXX object src/CMakeFiles/minetestserver.dir/unittest/test_socket.cpp.o
/usr/bin/ld: cannot find -lSDL2::SDL2: Datei oder Verzeichnis nicht gefunden
[ 87%] Building CXX object src/CMakeFiles/minetestserver.dir/unittest/test_threading.cpp.o
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:5062: /home/myuser/projects/minetest/5.8.0/minetest-master/bin/minetest] Fehler 1
make[2]: Verzeichnis „/home/myuser/projects/minetest/5.8.0/minetest-master/build“ wird verlassen
make[1]: *** [CMakeFiles/Makefile2:413: src/CMakeFiles/minetest.dir/all] Fehler 2

There's no minetest executable in the bin folder (there IS a minetestserver executable)

What's expected to happen?

minetest client compiles

### Steps to reproduce

#!/bin/bash

VERSION=5.8.0
BASEDIR=~/projects/minetest/${VERSION}
MASTER=minetest-master
VERSIONEXTRA=

mkdir -p ${BASEDIR}

#luajit
cd ${BASEDIR}
git clone -b v2.1 https://github.com/LuaJIT/LuaJIT.git
cd LuaJIT
luajit_folder=$(pwd)
make -j$(nproc)

#irrlicht
cd ${BASEDIR}
git clone https://github.com/minetest/irrlicht.git
cd irrlicht
irrlicht_folder=$(pwd)
cmake . -DBUILD_SHARED_LIBS=OFF -B build
make -C build -j$(nproc)

#mt
cd ${BASEDIR}
git clone https://github.com/minetest/minetest.git ${MASTER}
git clone https://github.com/minetest/minetest_game.git ${MASTER}/games/mintest_game
cd ${MASTER}
cmake -S . -B build -DENABLE_GETTEXT=1 -DENABLE_SPATIAL=ON -DENABLE_FREETYPE=1 -DBUILD_CLIENT=1 -DBUILD_SERVER=1 -DENABLE_SYSTEM_GMP=ON -DENABLE_CURL=ON -DENABLE_CURSES=ON -DENABLE_LUAJIT=ON -DCMAKE_BUILD_TYPE=Release -DRUN_IN_PLACE=TRUE -DIRRLICHTMT_BUILD_DIR="${irrlicht_folder}/build/" -DLUA_INCLUDE_DIR="${luajit_folder}/src" -DLUA_LIBRARY="${luajit_folder}/src/libluajit.a" -DVERSION_EXTRA=${VERSIONEXTRA} -DENABLE_POSTGRESQL=ON -DENABLE_SPATIAL=ON -DENABLE_SYSTEM_JSONCPP=ON 
make -C build -j$(nproc)

**Comment by sfan5** [comment]
Instead of a linking error I get this:
```
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
CMake Error at /home/user/irrlicht/build/cmake/IrrlichtMtTargets.cmake:52 (set_target_properties):
  The link interface of target "IrrlichtMt::IrrlichtMt" contains:

    SDL2::SDL2

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /home/user/irrlicht/build/cmake/IrrlichtMtConfig.cmake:11 (include)
  CMakeLists.txt:86 (find_package)
```

**Comment by Bastrabun** [comment]
Works :)
