### ISSUE TITLE
Scale sound gain according to player distance

### ISSUE THREAD

**Issue by hlqkj** [minetest/minetest#14328]
### Problem

The `max_hear_distance` field of a sound parameter table is currently used only to decide if a player receives the sound or not, according to their distance from the source. However, when the sound gets played to a specific player, its volume is the same no matter if they are right at the source position or much further away.

### Solutions

Apply some scaling based on the player distance, something that would make sense without adding complex calculations.

### Alternatives

https://github.com/BluebirdGreycoat/musttest_game/blob/main/mods/ambiance/utility.lua#L60-L98

But I really think this should be an engine feature, after all.

**Comment by rubenwardy** [comment]
This is already done by positional mono sounds. If you're trying to play a position sound, make sure you're using mono and not stereo

**Comment by rubenwardy** [comment]
> However, when the sound gets played to a specific player, its volume is the same no matter if they are right at the source position or much further away.

If you mean that a positional sound played to a specific player has no attenuation, then this would be a bug

**Comment by hlqkj** [comment]
At this point, I will double check. I am running on a 5.9-dev and didn't notice any attenuation, and I think sounds are mostly mono. Apologies in case, I wasn't aware this feature was added - it is not referenced in the current docs either.

**Comment by hlqkj** [comment]
My bad, testing it now had this working, will double-check sound files if stereo is the real problem. Closing. Thank you @rubenwardy!
