### ISSUE TITLE
MSVC build access violation crash since "Clean up client and server command sending / tables"

### ISSUE THREAD

**Issue by blaboing** [minetest/minetest#14324]
### Minetest version

```true
Minetest 5.9.0-dev-397682a
```

### Operating system and version

Win10

### Summary

MSVC builds crash with access violation since https://github.com/minetest/minetest/commit/397682a5b08ae683431618ba52b6dec1829bcce3 on starting a singleplayer game or joining a public server.

running inside VS debugger it points to
- singleplayer https://github.com/minetest/minetest/blob/397682a5b08ae683431618ba52b6dec1829bcce3/src/server.cpp#L1152
- public server https://github.com/minetest/minetest/blob/397682a5b08ae683431618ba52b6dec1829bcce3/src/client/client.cpp#L1035

### Steps to reproduce

run Minetest 5.9.0-dev-397682a MSVC build

**Comment by savilli** [comment]
Replacing `class Client;` with `class __multiple_inheritance Client;` here https://github.com/minetest/minetest/blob/397682a5b08ae683431618ba52b6dec1829bcce3/src/network/clientopcodes.h#L26 should fix the issue.
See https://learn.microsoft.com/en-us/cpp/cpp/inheritance-keywords?view=msvc-170
