### ISSUE TITLE
Needs A Better Error Reporting Sytem

### ISSUE THREAD

**Issue by LWFlouisa** [minetest/minetest#14327]
### Minetest version

```true
5.8.0
```

### Operating system and version

Linux Mint 21

### Summary

It keeps giving me this deceptive error code, no matter what my error is. There is nothing wrong with the init file itself.

~~~
ModError: Failed to load and run script from /home/sarah/.minetest/mods/yumemoire_asteroids/init.lua:
/home/sarah/.minetest/mods/yumemoire_asteroids/init.lua:1: attempt to concatenate a nil value
stack traceback:
	/home/sarah/.minetest/mods/yumemoire_asteroids/init.lua:1: in main chunk
Check debug.txt for details.
~~~

### Steps to reproduce

Trying to extend Other_Worlds.

**Comment by v-rob** [comment]
This is not a bug with the engine; these are the standard Lua error messages.  They work perfectly fine.

(In this case, it probably means that you have a variable doesn't exist yet, and you're concatenating it to a string.  Have a look at line 1 of your `init.lua` file: you probably have a variable next to the `..` symbol that hasn't been declared with `local` yet.)
