### ISSUE TITLE
short raycasts don't see objects when passing through the tops of tall ones

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#14337]
### Minetest version

```true
55f40a7
Minetest 5.9.0-dev-55f40a7f8-dirty (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1699392533
BUILD_TYPE=SemiDebug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Linux nail 6.6.8-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Dec 21 16:21:45 UTC 2023 x86_64 GNU/Linux

### Summary

it seems that very short raycasts do not properly discover relevant entities that they might collide with. 

i'm working on a projectiles mod, and one of the things it needs to do is an interpolated sequence of raycasts along the arc of motion to check for collisions with objects and solid nodes. test users discovered that for some reason, projectiles passed unimpeded through the tops of objects with large collision boxes. i discovered that the problem went away (or at least got better) if i used larger interpolation steps. another test user pointed me at the following code:

https://github.com/minetest/minetest/blob/e10d8080ba6e53e0f3c4b20b32304f8bb36e5958/src/serverenvironment.cpp#L1837C2-L1838

changing the constant from 10 to 100 also seems to fix the problem, though i don't know if that's a good solution. 

### Steps to reproduce

i've made a mod to make demonstrating this easier:

https://github.com/fluxionary/minetest-short_raycast

first, create a target entity, using the `/short_raycast_entity` command. it will spawn at the location of the player who issued the command. then, give yourself the a test tool which will do a sequence of raycasts, and add a waypoint HUD at the site of the first collision: `/giveme short_raycast:caster`. next, you can adjust the step size between successive casts by hold the tool and "place"-ing. trigger the cast by "use"-ing the tool. if the step size is 0.01 or 0.1, the casts will not intersect with the top of the entity, whereas they will if the step size is 1 or 10. 

![image](https://github.com/minetest/minetest/assets/25628292/5d1136a3-d8f4-4f55-b1b1-92bd5d0e176c)

**Comment by appgurueu** [comment]
Likely culprit:

```c++
getObjectsInsideRadius(objs, shootline_on_map.start,
		shootline_on_map.getLength() + 10.0f, nullptr);
```

I believe the `10.0f` is in blocksize, so merely one node (!) of "margin" around the start, but the entity is larger than that (selectionbox of height ~3). Bumping those numbers should work, but frankly this "get inside radius" is dubious to begin with; the client imposes no such limitation.

**Comment by nauta-turbidus** [comment]
The following may be related:
https://git.minetest.land/MineClone2/MineClone2/pulls/4156

**Comment by appgurueu** [comment]
> The following may be related: https://git.minetest.land/MineClone2/MineClone2/pulls/4156

At first it might seem related, but isn't that issue about "hitting" the ghast about client-side raycasts (e.g. hitting the ghast with a sword)? I'm not sure if Mineclone does any short range raycasts (but those should benefit from this fix too).

**Comment by nauta-turbidus** [comment]
> > The following may be related: https://git.minetest.land/MineClone2/MineClone2/pulls/4156
> 
> At first it might seem related, but isn't that issue about "hitting" the ghast about client-side raycasts (e.g. hitting the ghast with a sword)? I'm not sure if Mineclone does any short range raycasts (but if it does, those should benefit from my fix too).

That's about arrows first of all.
