### ISSUE TITLE
Allow mods to detect damage greater than the player's health

### ISSUE THREAD

**Issue by ThePython10110** [minetest/minetest#14344]
### Problem

At the moment, there is no way for mods to detect whether damage is greater than the player's health.

```
2024-02-03 15:12:28: ACTION[Server]: singleplayer damaged by 43 hp at (-3,7.165,-22)
2024-02-03 15:12:28: [Server]: HP change: -20
```
The first line is logged by the engine and the second line is logged in a `minetest.register_on_player_hpchange` function. I've looked through the engine code and found that before running those functions, the new HP is limited to a minimum of 0 (thus limiting the `hp_change` to the player's current HP). This means that there is no way to tell the difference between fall damage from 27 meters and 60,000 meters.

The reason I noticed this is because of a mod I'm making that adds very powerful armor. With the armor, players don't take damage unless it's above a certain threshold. Unfortunately, this means that when a player's HP is below that threshold, the player literally can't take damage while wearing the armor.

### Solutions

The HP change passed to `minetest.register_on_player_hpchange` functions should not be limited to the player's current health. It should be the same as the damage reported by the server.

### Alternatives

Maybe adding a boolean argument to `minetest.register_on_player_hpchange` to decide whether the full or adjusted HP change should be used.

**Comment by ThePython10110** [comment]
Yes, that's right. The problem is that my mod has *really good* armor, and not being able to access the raw value means that if a player is at 1HP, they will literally not be able to take damage (since over 1HP will be blocked).

**Comment by SmallJoker** [comment]
Relevant code:
https://github.com/minetest/minetest/blob/d733e1abea1ff18c0e6375e6f05b0c29b679a3fc/src/server/player_sao.cpp#L516-L524

However, keep in mind that `on_dieplayer` should only be called once, but respawning may call this function where `target_hp > m_hp && m_hp == 0`.

**Comment by ThePython10110** [comment]
> > Yes, that's right. The problem is that my mod has _really good_ armor, and not being able to access the raw value means that if a player is at 1HP, they will literally not be able to take damage (since over 1HP will be blocked).
> 
> Actually I'm curious about how good that is, do it have fancy icon or something? Such a value should mostly of course be accompanied by a corresponding icon IMHO, and I'm quite interested about its feature, to be honest.

It doesn't use the normal armor groups and instead uses an `on_player_hp_change` function... Unfortunately, this means that to the player, it doesn't show that it's armor correctly at all... But I'm trying to copy a Minecraft mod, and armor groups aren't specific enough.

**Comment by Xeno333** [comment]
There seem to be no attempts to implement the alternent solution? This seems to be the most practical and safest way to do it... I think I will try that

**Comment by grorp** [comment]
Two simple solutions have been suggested:

1. pass an additional `raw_hp_change` parameter to the callback
2. add a `raw` bool parameter to `register_on_player_hpchange` (false by default)

Here's the problem:

1. There's a hpchange modifier that gets a "clamped" hp_change value and returns a new hp_change value:
    
    ```lua
    core.register_on_player_hpchange(function(player, hp_change, reason)
        return hp_change * 0.85 + 3
    end, true)
     ```

2. There's a hpchange callback using "raw" hp_change values:
    ```lua
    -- alternative 1
    core.register_on_player_hpchange(function(player, hp_change, reason, raw_hp_change)
        print("raw hp change = " .. raw_hp_change)
    end)
    
    -- alternative 2
    core.register_on_player_hpchange(function(player, hp_change, reason)
        print("raw hp change = " .. hp_change)
    end, nil, true)
    ```

3. How could the callback possibly print a correct value? Where would it come from / how would it be calculated? We've already clamped the value, we can't undo that and keep modifications by modifier callbacks.

**Comment by Xeno333** [comment]
The raw would override the non raw, seems to make the most sense

**Comment by ThePython10110** [comment]
Maybe just a separate function to register callbacks that use the raw value... that would run before the regular `register_on_player_hpchange`...

**Comment by appgurueu** [comment]
> Here's the problem: [...]

Something which operates on limited legacy information and then supplies the information for the next handler (a modifier) of course will lose information.

Mod and game authors will have to deal with this, I see no way around that. We can only somewhat influence *how* they deal with it, and provide an API such that modsets / games written with this API in mind *can* work well.

Running "raw" callbacks first could make sense, though ultimately it doesn't solve the problem: If I *want* the modified HP change, there is no way to get that when preceding modifiers only operated based on a limited value.

**Comment by Xeno333** [comment]
> > Here's the problem: [...]
> 
> Something which operates on limited legacy information and then supplies the information for the next handler (a modifier) of course will lose information.
> 
> Mod and game authors will have to deal with this, I see no way around that. We can only somewhat influence _how_ they deal with it, and provide an API such that modsets / games written with this API in mind _can_ work well.
> 
> Running "raw" callbacks first could make sense, though ultimately it doesn't solve the problem: If I _want_ the modified HP change, there is no way to get that when preceding modifiers only operated based on a limited value.
> 
> In the example you give, the author of the modifier mod _should_ update their mod if it is to play well with other mods.

I think running a new callbakc first is the only feasible option, but yeah it breaks some compatibility (all the other options break more). 

Could be optional with an experimental flag for breaking changes?

**Comment by appgurueu** [comment]
> I think running a new callbakc first is the only feasible option, but yeah it breaks some compatibility (all the other options break more).
> 
> Could be optional with an experimental flag for breaking changes?

No, there is no compatibility breakage here. The problem is just that mods using the legacy API could break mods that want to use the new API, because they operate on clamped values and their results are then propagated. But note:

* In a "game" context, where the expectation is that you control the modset (and mods that want to be compatible need to be written with your game's requirements in mind), this is not a problem at all;
* There are also hacks you can do to run "first", such as inserting yourself into the registered callbacks table;
* Otherwise, I simply hope enough modders upgrade to the new API - it should be noted that many different HP change modifiers don't tend to work well together anyways

There is no alternative than to slowly propagate this through the mod landscape. If a mod is *not* registering a modifier, but only registering a "listener", it *wants* to run after the modifiers. But the modifiers are operating on limited values, hence the result will be limited. The author of the modifier *must* take unclamped values into account if these mods are to work together, there is no way around that.

**Comment by SmallJoker** [comment]
The value range of `hp_change` is not documented. Hence passing the raw HP change to this parameter would be okay. It might cause side-effects on a few mods that relied on such clamping.

https://github.com/minetest/minetest/blob/efd7792add70ccfafb14e4b2e3ddd6d52457dd8e/doc/lua_api.md?plain=1#L5788-L5792

**Comment by ThePython10110** [comment]
I am actually a bit curious whether there *are* any mods that for some reason rely on the clamped value...

**Comment by grorp** [comment]
This is actually a regression: #10377

**Comment by sfence** [comment]
However, HP change cannot be more than `hp_max` if HP is not negative.


`target_hp = rangelim(target_hp, 0, U16_MAX);` -> this line `PlayerSAO::setHP` do the limitation and cause this issue.

Do we want to return `hp_change` bigger than `hp_max`, or some field in the reason table for Lua callback?`minetest.register_on_player_hpchange(function(player, hp_change, reason), modifier)`
