### ISSUE TITLE
The Minetest trademark is registered in China

### ISSUE THREAD

**Issue by Davidliang11292** [minetest/minetest#14350]
Hello everyone, I come from China. After I learned about OldCoder's malicious registration of Minetest trademark, I decided to check whether Minetest's trademark has been registered in China. Unfortunately, it has been registered, will it have any impact on Minetest? What can be done?
![Screenshot_2024-02-05-16-43-14-87.jpg](https://github.com/minetest/minetest/assets/152856832/8a573e98-c914-455d-bd9f-e4f4ced41efb)

https://aiqicha.baidu.com/m/tradmark/list?t=9&q=Minetest&VNK=1707122194959&d=Mon%20Feb%2005%202024%2016%3A36%3A34%20GMT%2B0800%20%28%E4%B8%AD%E5%9B%BD%E6%A0%87%E5%87%86%E6%97%B6%E9%97%B4%29

(This website is in Chinese, please use a translator)

**Comment by rubenwardy** [comment]
We don't have any plans to trade or be active inside China, so I doubt this will be an issue. (But I'm not a lawyer)

**Comment by Davidliang11292** [comment]
> We don't have any plans to trade or be active inside China, so I doubt this will be an issue. (But I'm not a lawyer)

Is it possible that this trademark is registered by OldCoder?

**Comment by Zughy** [comment]
Considering that MT will probably change nane and what ruben said, closing. Also, I don't think it makes any difference knowing who registered it

**Comment by Davidliang11292** [comment]
> Considering that MT will probably change name and what ruben said, closing. Also, I don't think it makes any difference knowing who registered it

I have an idea for a new name for Minetest (sorry, this might be a bit off topic, but this issue is locked on Github and I don't know where to go, is it on the Minetest forum?)

**Comment by Davidliang11292** [comment]
> Considering that MT will probably change name and what ruben said, closing. Also, I don't think it makes any difference knowing who registered it

The new name I propose is: Create and create (CaC) The first "create" refers to in the game sandbox, the second "create" refers to in the source code, I also think of a slogan "you can create, also can create" at the same time, CaC can also be split into "Copyleft and share" Do you have any comments or suggestions on this name?

**Comment by appgurueu** [comment]
Thanks for the proposal, but I'm afraid this probably can't compete with some of the better suggestions that were made. First of all, it's repetitive (as is the slogan), not a single word and rather vague. Three-letter acronyms are unfortunately pretty much always taken (in this case by the "Corporate Affairs Commission").
