### ISSUE TITLE
Android: Automatically clear/update deps.zip

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#14352]
### Problem

It's very easy to accidentally build Minetest with outdated dependencies. For example, the current 5.8 release on the play store isn't using the correct version of Irrlicht

### Solutions

The Android build scripts should check whether the deps.zip is for the correct version of Minetest, and either:

* Fail to build
* or download the latest version

If the dependencies are outdated.

This could just be done using the misc/irrlicht_tag.txt

**Comment by sfan5** [comment]
> This could just be done using the misc/irrlicht_tag.txt

... which will go away however.

**Comment by appgurueu** [comment]
Yep, won't this become obsolete when we import Irrlicht into the Minetest repo, which we'll probably do pre-5.9?
