### ISSUE TITLE
game running highest overlay in fullscreen unable to bring system windows to the front

### ISSUE THREAD

**Issue by MPagliari** [minetest/minetest#14354]
### Minetest version

```true
Minetest 5.8.0 (Windows) 
Using Irrlicht 1.9.0mt13
using LuaJIT 2.1.0-beta3
Build_Type=release
RunInPlace=1
Use_curl=1
Static_shuredir="."
static_localdir="Locale"
```

### Active renderer

OpenGL 4.6.0

### Irrlicht device

Win32

### Operating system and version

Windows11 23H2

### CPU model

Ryzen Z1 Extreme

### GPU model

780M

### OpenGL version

 OpenGL     4.6 

### Summary

Windows 11 (speculating this could be a windows 10 issue aswell) uses sertain graphic overlays that run on top of gaming enviroments that are not able to be displayed this includes The windows xbox overlay side panal notification area and in my case the Asus Rog Ally - Armery Crate SE that is used to define keys on this gaming handheld. The overlays work when running in windowed mode but in full screen Minetest takes exclustivity of the highest layer making it imposible to render other system overlays.

### Steps to reproduce

Run game in full screen mode and press [WIN]+[G] to bring up MS XBOX gaming overlay window (Most Windows users)
on ROG Ally press the Armory create button on the left hand side to bring up the input panel to configure the device (Limited to ROG Ally users)

**Comment by Zughy** [comment]
Tested both on Windows 10 and Windows 11: can't reproduce
