### ISSUE TITLE
Tools with long range cause insane FPS drop.

### ISSUE THREAD

**Issue by nininik0** [minetest/minetest#14363]
### Minetest version

```true
5.8.0
(Any os)
```

### Active renderer

Any device

### Irrlicht device

Any 

### Operating system and version

Windows or android

### CPU model

Dosent matter

### GPU model

Any

### OpenGL version

Any

### Summary

Whenever you create a tool with a reach range higher than 50-90, your game lags very badly. Doesn't matter if the texture is blank.png or just any, the game will lag a lot. I've tried three different devices, seems like all of them had a massive fps drop. I've given the tool to some other players either, and they had very low fps too. The tool_capabilities or wield_scale doesn't matter either. 

### Steps to reproduce

Just use this code in any mod. 
```lua
minetest.register_tool("mymod:testtool", {
	description = "long range tool.",
	inventory_image = "blank.png",
	tool_capabilities = {
        full_punch_interval = 0.0,
        max_drop_level = 9,
        groupcaps = {
            unbreakable = {times = {[1] = 0, [2] = 0, [3] = 0}, uses = 0, maxlevel = 55},
            cracky = {times = {[1] = 0, [2] = 0, [3] = 0}, uses = 0, maxlevel = 55},
            crumbly = {times = {[1] = 0, [2] = 0, [3] = 0}, uses = 0, maxlevel = 55},
            choppy = {times = {[1] = 0, [2] = 0, [3] = 0}, uses = 0, maxlevel = 55},
        },
        damage_groups = {fleshy = 24, icy = 64, fiery = 4},
    },
    wield_scale = {x = 1, y = 1, z = 1},
    range = 900,
})
```

**Comment by Desour** [comment]
Surprisingly, I can't reproduce this in master. I am pretty sure this used to be an issue.

**Comment by appgurueu** [comment]
Tested on 5.8, can't reproduce, the tool works just fine for me. Possibly someone else is causing the performance issues, which happens to correlate with your use of the tool?

Estimating the work our current code is doing, I don't see why this would be a performance issue, given that only a single raycast has to be performed per client step.

(Besides, even if it were a performance issue, ridiculously long tool ranges aren't that important to support well.)

**Comment by nininik0** [comment]
Bruh

**Comment by appgurueu** [comment]
(I think "can't repro" is the more appropriate close reason for this issue)
