### ISSUE TITLE
CMake failure on macOS?

### ISSUE THREAD

**Issue by ShadowRoi** [minetest/minetest#14386]
### Minetest version

```true
5.9.0-dev
```

### Irrlicht device

OSX

### Operating system and version

macOS Sonoma 14.2.1

### CPU model

M1 Pro

### Summary

<img width="857" alt="image" src="https://github.com/minetest/minetest/assets/105967373/a5166b5f-d50b-4c7d-a995-f81440c5237f">
I am not sure but this is a cmake problem?  Sorry if I am being dumb. I am using the latest home-brew version.

### Steps to reproduce

Attempt to compile on macOS using the official instructions
Attempting to run the build commands there is a failure using the cmake

**Comment by sfan5** [comment]
Did you `brew install jpeg`?

**Comment by ShadowRoi** [comment]
<img width="572" alt="image" src="https://github.com/minetest/minetest/assets/105967373/185134a7-7740-4b10-8ca8-730769f815ca">

Yeap it was already included in fact when I had first installed brew. however even after reinstalling it, attempting to build it the same issue happens again sadly.

**Comment by SmallJoker** [comment]
One way for CMake is to find packages with `pkg-config`. Your jpeg installation should provide the file `jpeglib.h`. Might there be a separate package for development purposes? On the most common Linux distributions the libraries and header/development files are separate.

**Comment by ShadowRoi** [comment]
@SmallJoker  I have no idea to do any off that sorry. I need the exact commands cause I suck

**Comment by sfan5** [comment]
Please try `brew ls --verbose jpeg`.

You can also try `brew uninstall && brew install jpeg-turbo` and then try to run cmake again.

**Comment by sfan5** [comment]
Thanks for testing.
Not sure what exactly is wrong with `jpeg` but we should change our documentation to refer to `jpeg-turbo` and be done with it.

> [...] and after it loaded it crashed instantly. After that point attempting to try Mineclonia,Mineclone 2, Minetest Game, the entire app was crashing completely instantly [...]

Please open separate issue(s) for that.
