### ISSUE TITLE
HTTP requests turn GET into PUT

### ISSUE THREAD

**Issue by BramvdnHeuvel** [minetest/minetest#14394]
### Minetest version

```true
Minetest: 5.8.0

Docker container on WSL2
Docker container on Ubuntu
```

### Irrlicht device

WIN32

### Operating system and version

Various (Windows, WSL, Alpine)

### Active renderer

OpenGL 4.6.14761

### Summary

After having used at least one HTTP call of `method = "PUT"`, all other HTTP requests of type `method = "GET"` become `method = "PUT"` - even if explicitly mentioned.

See [this repository](https://git.noordstar.me/Bram/mt-matrix) for an example in the field:

- The file [lua/sync.lua](https://git.noordstar.me/Bram/mt-matrix/src/branch/main/lua/sync.lua) make `GET /sync` HTTP requests. These work just fine.
- The file [lua/send.lua](https://git.noordstar.me/Bram/mt-matrix/src/branch/main/lua/send.lua) makes a `PUT /send` HTTP request whenever a Minetest user sends a message in the chat.

The bug is that **as soon as** one message gets sent using a `PUT` request, ALL future `GET /sync` requests end up server-side as `PUT /sync` requests.

### Steps to reproduce

1. Set up a server that can catch `GET` and `PUT` requests.
2. Run [this repository](https://git.noordstar.me/Bram/mt-matrix) as a Minetest mod or run code that sends one `GET` request after one `PUT` request.
3. Analyze how both HTTP requests will be `PUT` requests.

If you would like to test the bug using the linked repository, I have (limited) infrastructure to provide you with the tools needed to debug.

**Comment by rubenwardy** [comment]
Minimal reproducible example: [putget.zip](https://github.com/minetest/minetest/files/14343937/putget.zip)

**Comment by sfan5** [comment]
possible bug here:
https://github.com/minetest/minetest/blob/e3cc26cb7c4fd8265adbce040c0d0577f32667f7/src/httpfetch.cpp#L302-L315

`CURLOPT_CUSTOMREQUEST` is never reset.
although the [docs](https://curl.se/libcurl/c/CURLOPT_HTTPGET.html) for `CURLOPT_HTTPGET` say:
> If useget is 1, this forces the HTTP request to get back to using GET. Usable if a POST, HEAD, PUT, etc has been used previously using the same curl handle.

**Comment by savilli** [comment]
I think "Usable if a POST, HEAD, PUT, etc has been used previously using the same curl handle." means when you set PUT method using `CURLOPT_PUT` option and not when you use `CURLOPT_CUSTOMREQUEST`.
At least according to the code, `STRING_CUSTOMREQUEST` has a bigger priority than `method` - https://github.com/curl/curl/blob/d5b0fee39a7898dac42cb4fc64e35f5bc085e766/lib/http.c#L2095 and `CURLOPT_HTTPGET` sets only `method`.
