### ISSUE TITLE
path_share/mods isn't added to get_modpaths

### ISSUE THREAD

**Issue by j-r** [minetest/minetest#14392]
### Minetest version

```true
6ca214fefc9e1eb707f006631d39c1e4dbafe1b5
```

### Operating system and version

Debian Oldstable (no upgrade path available)

### Summary

The documentation indicates that the mods directory in the shared path will be searched for mods like it is  for the games directory, but it isn't.

It's not a big problem, since one can just use MINETEST_MOD_PATH.

### Steps to reproduce

Move path_user/mods to path_share/mods and have them disappear.

**Comment by sfan5** [comment]
I see no references for `path_user.*mods` except in the documentation. So this sounds like a documentation bug.

I agree it would make sense if this was possible however.

**Comment by j-r** [comment]
Well, manually adding ``load_mod_xxx = share/xxx`` to ``world.mt`` is working perfectly fine, it seems. It's just the main menu that cannot see mods there currently, because the shared path is missing from ``get_modpaths``. When it is added it also has no problem creating ``load_mod_xxx = share/xxx`` using the normal UI.

**Comment by Mahoyomu** [comment]
I looked into the src code related to this, and I think if `getEnvModPaths()` returns name of single mod folder, maybe I can use path_share to do work similar with this loop below, considering perfomance, if one folder has mod(etc path_user/mods) then skip detect the other one(path_share/mods in this case), no comparing mod folder names or something, also avoiding possible conflicts due to this change
`for (const std::string &component : getEnvModPaths()) {
		lua_pushstring(L, component.c_str());
		lua_setfield(L, -2, fs::AbsolutePath(component).c_str());
	}`

**Comment by j-r** [comment]
The following is working fine for me. When first reading sfan5's answer I interpreted it as only wanting a documentation change, but after reading it again now, I should probably send a PR:-)

```
diff --git a/src/script/lua_api/l_mainmenu.cpp b/src/script/lua_api/l_mainmenu.cpp
index a5913e807..97101955a 100644
--- a/src/script/lua_api/l_mainmenu.cpp
+++ b/src/script/lua_api/l_mainmenu.cpp
@@ -675,6 +675,11 @@ int ModApiMainMenu::l_get_modpaths(lua_State *L)
        ModApiMainMenu::l_get_modpath(L);
        lua_setfield(L, -2, "mods");

+       std::string modpath = fs::RemoveRelativePathComponents(
+               porting::path_share + DIR_DELIM + "mods" + DIR_DELIM);
+       lua_pushstring(L, modpath.c_str());
+       lua_setfield(L, -2, "share");
+
        for (const std::string &component : getEnvModPaths()) {
                lua_pushstring(L, component.c_str());
                lua_setfield(L, -2, fs::AbsolutePath(component).c_str());
```

**Comment by j-r** [comment]
I don't really know exactly how it works either, I just copied/adapted the code from ModApiMainMenu::l_get_modpath:-)

I'll do the PR now.
