### ISSUE TITLE
Minetest fails to launch on dedicated NVIDIA GPU.

### ISSUE THREAD

**Issue by Atemo-C** [minetest/minetest#14415]
### Minetest version

```true
Minetest 5.8.0-NixOS (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1693350652
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/nix/store/3lf6l24n8lcxbkf9z19hl70wnivpni7k-minetest-5.8.0/share/minetest"
STATIC_LOCALEDIR="/nix/store/3lf6l24n8lcxbkf9z19hl70wnivpni7k-minetest-5.8.0/share/locale"
```

### Irrlicht device

X11 (Xwayland)

### Operating system and version

NixOS 23.11, using unstable.minetest from the upcoming NixOS release (24.05). Have not tried the Flatpak yet.

### CPU model

Ryzen 5 3400G with integrated VEGA 11 graphics.

### GPU model

NVIDIA GTX 1660 SUPER

### Active renderer

OpenGL 4.5

## Disclaimer
I really do not know much at all about the inner workings of Minetest. I am not sure if this is a Minetest issue, a NixOS package issue, an NVIDIA issue, an Xwayland issue, an Irrlicht issue, something else, or a combination of *any* of the above.
If you feel as though I have missed something obvious and could guide me to report the problem in a more appropriate place and with relevant details, I would greatly appreciate it.

## Problem
I am trying to run Minetest on my dedicated GPU, but get the following error:
```log
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  0
  Current serial number in output stream:  90
```

---

## GPU setup
I have two GPUs on my system:
- Integrated AMD VEGA 11 graphics *(default)*
- NVIDIA GTX 1660 SUPER *(dedicated)*

My NVIDIA GPU is only used in games and other graphics-intensive programs to save power and to avoid known bugs with Wayland under Linux with the current NVIDIA drivers (let us hope 550 series will fix those...)

---

## How other programs behave
Other programs launch properly and use my NVIDIA GPU when I tell them to use it. This is usually done via the application's settings, or variables that tell the program to use my NVIDIA GPU, usually done in my program launcher.

---

## Command used to run Minetest
- Simply running `minetest` does not use the dedicated GPU.
- Exporting `__NV_PRIME_RENDER_OFFLOAD=1` does not make Minetest use the dedicated GPU.
- Exporting the entire line I use for stubborn programs, being the following `__NV_PRIME_RENDER_OFFLOAD=1 __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __GLX_VENDOR_LIBRARY_NAME=nvidia __VK_LAYER_NV_optimus=NVIDIA_only` makes the program not launch with the above-mentioned error.
- With the above long export, other programs on my system launch without any issues.

---

### Flatpak?
I am trying to use as much as possible native packages, but I may try the Flatpak version out if you recommend it over the native "unstable" NixOS version.
I could also try downgrading to the "stable" *(23.11)* package on NixOS, but I want to run the latest and greatest that Minetest has to offer.

### Why use the dGPU when the iGPU is powerful enough?
Whilst it is true that my integrated GPU is more than performant enough to run Minetest at respectable graphical settings and frame rate, I am missing out on some nice features and on higher refresh rates compared to using my dedicated GPU. Besides, I want the integrated GPU to manage my desktop and lightweight programs, not my games.

### Did the issue happen before?
It is the first time I open Minetest in a few months, but I used to be able to run it just fine on my dedicated GPU with the previously mentioned "long export". I have no idea what could have caused it to stop working.

### Steps to reproduce

- Launch Minetest
- Expect dGPU to be used
- See the iGPU be used instead
- Try a few exports *(mentioned in the Summary)* to no avail, until the game stops launching and throws out this error:
```log
X Error of failed request:  BadAlloc (insufficient resources for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  0
  Current serial number in output stream:  90
```

**Comment by lhofhansl** [comment]
Works for me. Dedicated NVidia on Linux.

Does anything else work with your render offload? Like glxgears.
If glxgears works please attach the output of `glxgears -info` (with render offload)

**Comment by lhofhansl** [comment]
This is what I do:
```
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only
```

In the end this is not an MT problem. Might be best asked on Irc.

**Comment by Atemo-C** [comment]
```
__NV_PRIME_RENDER_OFFLOAD=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
__VK_LAYER_NV_optimus=NVIDIA_only
```
Same result on Minetest with this, as in, it launches, but it does not use the NVIDIA GPU for some reason. Maybe there is a setting inside Minetest that I could configure to force its use? I have dug into Minetest's settings and advanced settings, but could not find anything relevant. (I may just be blind, I actually hope that is the case.)

---

> If glxgears works please attach the output of glxgears -info (with render offload)

Glxgears and any other program works just fine, here is the output of `glxgears -info` with render offload.

```log
[1] 7613
GL_RENDERER   = llvmpipe (LLVM 16.0.6, 256 bits)
GL_VERSION    = 4.5 (Compatibility Profile) Mesa 23.1.9
GL_VENDOR     = Mesa
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_3DFX_texture_compression_FXT1 GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_copy_depth_to_color GL_NV_depth_clamp GL_NV_fog_distance GL_NV_half_float GL_APPLE_packed_pixels GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_MESA_ycbcr_texture GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_EXT_texture_buffer_object GL_AMD_texture_texture4 GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_buffer_object GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_compatibility GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_tessellation_shader GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_ATI_meminfo GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_copy_image GL_NV_texture_barrier GL_ARB_draw_indirect GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_shader_subroutine GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_vertex_attrib_64bit GL_ARB_viewport_array GL_EXT_direct_state_access GL_EXT_vertex_attrib_64bit GL_AMD_multi_draw_indirect GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_query_buffer_object GL_AMD_shader_trinary_minmax GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_fragment_layer_viewport GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_multi_draw_indirect GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_buffer_range GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_NV_shader_atomic_float GL_AMD_pinned_memory GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_enhanced_layouts GL_ARB_indirect_parameters GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_seamless_cubemap_per_texture GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shading_language_include GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_debug_label GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_NVX_gpu_memory_info GL_ARB_ES3_1_compatibility GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_ARB_transform_feedback_overflow_query GL_ARM_shader_framebuffer_fetch_depth_stencil GL_EXT_polygon_offset_clamp GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_ES3_2_compatibility GL_ARB_gpu_shader_int64 GL_ARB_parallel_shader_compile GL_ARB_post_depth_coverage GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_shader_clock GL_ARB_shader_viewport_layer_array GL_ARB_texture_filter_minmax GL_EXT_texture_filter_minmax GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_RG8 GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_ARB_gl_spirv GL_ARB_spirv_extensions GL_MESA_shader_integer_functions GL_ARB_polygon_offset_clamp GL_ARB_texture_filter_anisotropic GL_EXT_memory_object GL_EXT_memory_object_fd GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_texture_shadow_lod GL_INTEL_shader_atomic_float_minmax GL_MESA_framebuffer_flip_y GL_EXT_EGL_sync GL_NV_ES1_1_compatibility
VisualID 1007, 0x3ef
15852 frames in 5.0 seconds = 3170.365 FPS
```

I can confirm that it is using my NVIDIA GPU.

---

> Can you check with a self-compiled build from git?
We have switched to SDL2 which will use different code paths / APIs to create the window.

I will try that if I cannot get Minetest to run properly otherwise, thank you.

**Comment by Atemo-C** [comment]
UPDATE: It seems as though something is wrong with my setup, as this works fine on my laptop with a dedicated NVIDIA GPU and integrated Intel graphics. Will close as this is probably not caused by Minetest, but by a wrong set-up on my part. Sorry for the inconvenience!

**Comment by sfan5** [comment]
> GL_RENDERER   = llvmpipe (LLVM 16.0.6, 256 bits)

this means your graphics driver is not working and it's falling back to CPU rendering

>  but nvidia-smi does,

nvidia-smi can be used to confirm that the nvidia driver is loaded and finding your gpu but does not say anything about OpenGL or Vulkan working as expected.

**Comment by Atemo-C** [comment]
> this means your graphics driver is not working and it's falling back to CPU rendering
Yes, I can unfortunately see that. What is weird to me is that most other programs (Minecraft, PCSX2, RPCS3, Steam...) all are able to use my NVIDIA GPU, but a lot of other programs (Minetest, glxgears, vkcube...) are not. This is definitely an issue related to drivers on my system or a bug in my distribution or set-up. I will keep digging further until I find a solution, thank you for the help!
