### ISSUE TITLE
Objects with `static_save = false` are persisted

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14420]
### Minetest version

fbec37886

```
Minetest 5.9.0-dev-fbec37886 (Linux)
Using Irrlicht 1.9.0mt15
Using LuaJIT 2.1.1702233742
Built by GCC 13.2
Running on Linux/6.7.6-arch1-1 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Arch Linux x86_64

### Summary

`static_save` seems to have stopped working.

### Steps to reproduce

Put test code into mod:
```lua
local modname = core.get_current_modname()

core.register_entity(modname .. ":ent", {
	initial_properties = {
		static_save = false,
		textures = {"object_marker_red.png"},
	}
})

core.register_on_joinplayer(function(player)
	local pos = player:get_pos():offset(0, 2, 0)
	core.add_entity(pos, modname .. ":ent")
end)
```

Join and leave a few times.

Find multiple red dots in your world.

**Comment by sfan5** [comment]
introduced by #14311 in `ServerEnvironment::addActiveObjectRaw`
Before `object->addedToEnvironment` `object->isStaticAllowed()` is always true because the values have not been read from Lua.

**Comment by j-r** [comment]
I'm wondering if it should be supported to change the value of static_save after entity creation. Then the block guarded by isStaticAllowed must be moved to the read_object_properties  or something.

**Comment by sfan5** [comment]
It's supported but a bit buggy, I am in fact fixing that right now.
