### ISSUE TITLE
Colliding with unloaded blocks at high velocities is problematic

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#1442]
See here: https://forum.minetest.net/viewtopic.php?f=6&t=9547

In brief: When falling at a high speed, it it very likely to hit a block border of a block which is unloaded. The game then behaves weirdly: Your speed resets to 0 and you take no damage. You can even walk on the top of the unloaded block. When the block loads, you fall again, starting from speed 0. There are similar problems when hitting an unloaded block in a different direction. If you collide with an unloaded block from below, it it like you have hit a wall, which makes powerful trampolines (bouncy nodes) unreliable.
This is the first problem.
The second problem is that is likely to collide with unloaded blocks at all, especially at very high velocities (which happens when you fall deep). Maybe a smarter block loading strategy could help fix this.

See the thread for a deeper discussion and some ideas for possible fixes.

**Comment by paramat** [comment]
This can't be fixed, what if there is solid terrain in the ungenerated block? To pass through would result in burial. No damage can be caused in case the block is air when it generates.

**Comment by Wuzzy2** [comment]
After reading this again after a long time: Sorry, but I can't accept you just closed this.

We still have a serious problem:
You can drop from ~1000 nodes and hit the ground unharmed if you hit an unloaded chunk *just* before the ground. A 1000 node drop is a totally realistic use case by the way, just think about someone digging a mineshaft down to mese block level.

What about the speed limit many people have proposed?
This would make falling a lot more predictable, and this is important. IMO falling is the number 1 reason why players hit chunk borders, adding a speed limit would help a lot and this does not sound something to me which is impossible to implement. I don't really buy into your atmosphere argument, Minetest does not support something like this and I don't feel there's really a need for this.
The speed limit is more meant as a technical restriction, not a realistic one. This will help slow servers a lot if they can load chunks always faster than players can move. So basically the idea for speed limit is a hard fixed number of nodes per second and must be completely unrelated to gravity or even “atmosphere”. The speed limit would have to apply in all directions as the speed limit is only there to help servers keep up with loading map chunks.

Also, what is wrong about freezing players until the chunk is loaded? Especially for falling this makes a lot of sense. Resetting the speed when falling on an unloaded chunk is VERY awkward, you can basically WALK in mid-air. Resetting the speed to 0 also breaks other use cases. I have made a flying carpet mod (the flying carpet basically behaves like an air plane). The carpet requires a minimum speed to be operated. So far, so good, but when it hits an unloaded chunk, its speed is reset to 0 (like crashing) and the flying carpet crash-lands because the minimal speed was not held. There is no way for me, as the modder, is to defend against this kind of speed reset, or to even notice that it occoured. The mod only sees the speed became 0 for some reason. This is ambigious, it could either mean the carpet actually hit a wall or it just hit an unloaded chunk.

The idea of freezing is, that Minetest could *pretend* the speed of the object is still the same (speed getter functions return old values), but it does not actually move until the chunk is loaded; as long as frozen, speed setter functions would also be without effect.
I think this would both fix weird falling from 1000 nodes and flying carpet (and similar mods).

Yes, it would be annoying when you hit an unloaded chunk and freeze but IMO this is because you never should hit an unloaded chunk in the first place. The idea of freezing is mostly because to ensure consistent behaviour. If you constantly freeze this is because of heavy lag. Yet IMO it is worse to break key gameplay aspects (fall damage, objects where keeping the speed is important) rather than to slow gameplay down. In my flying carpet mod, it is very frustrating you constantly crashland because you hit an unloaded chunk. :(

Please re-open this. Maybe this can be fixed … at least partially and just not in the ways which have been proposed before.

I agree just passing through unloaded chunks will not help at all, but that's probably not the only solution.

**Comment by duckbrain** [comment]
My vote would be for displaying a message that says "Loading Chunks" and freezing gameplay until loaded. It can be confusing when you hit an unloaded chunk, and nothing else really makes sense. Also, if terminal velocity is implemented, it should be configurable to mods similar to gravity. This could allow for something like a parachute mod.

**Comment by paramat** [comment]
Ok it's reasonable for more discussion.

**Comment by paramat** [comment]
> I don't really buy into your atmosphere argument, Minetest does not support something like this

It does, there are space servers and several space mods that use vacuum nodes.
Celeron55's roadmap states:
"Keep the common base (the Minetest Engine) as universal as possible. I like to compare everything that goes into the engine for how well it suits a gravitation-less space game without ground surface. If everything is either disableable or suitable for such, then it gives much more freedom for people to experiment and create interesting things, even in ground-based worlds."

A speed limit could perhaps be an option and configurable. Problem is if the player is not looking downwards it will not help. In some cases a realistic terminal velocity would not be slow enough to avoid collision.
So i prefer the idea of not resetting player vertical speed on collision with ignore. A problem with freezing a player is that ignore is at world base and players need to move around on it.

**Comment by Wuzzy2** [comment]
> "Keep the common base (the Minetest Engine) as universal as possible. I like to compare everything that goes into the engine for how well it suits a gravitation-less space game without ground surface. If everything is either disableable or suitable for such, then it gives much more freedom for people to experiment and create interesting things, even in ground-based worlds."

I agree, but this has nothing to do with a maximum speed.

> Problem is if the player is not looking downwards it will not help, as world is only generated in the view direction.

Then maybe take the player speed into account as well? I.e. if player moves backwards fast, it makes more sense to prefer chunks behind the player over the chunks which are “looked at”.

Yeah, the bottom of the world already has its own problems, see here: https://github.com/minetest/minetest/issues/2702
You are right, the world edges are special here.

What about we add a new node which is just used for the edges (and beyond)? Not `air`, not `ignore` but `edge`.
This can be used as some kind of pseudo-node to mark an area outside of the actual world. `edge` could also be returned if a mod used `get_node` on coordinates out of range.

`edge` would be pretty much like `ignore` with the exception that they don't freeze objects.
The question is how to provide legacy support. :-/

**Comment by Fixer-007** [comment]
Don't close this, this is real gameplay issue.

**Comment by paramat** [comment]
> I agree, but this has nothing to do with a maximum speed.

It does, i wrote:
"Terminal velocity would have to depend on chosen gravity and whether the atmosphere nodes are air, alien atmosphere or vacuum. In vacuum speed could be so high that movement prediction could not generate mapchunks fast enough."

>  It seems the chunk loading algorithm must be changed to make servers more or less reliably make sure they load chunks fast enough.

Yeah celero55 has stated this needs improvement. A simpler solution is preferable, instead of detecting player speeds, just generate all blocks within the defined radius around the player.

The ideas put forward here are often too complex.

**Comment by Ferk** [comment]
> Also, what is wrong about freezing players until the chunk is loaded?

I'd prefer if the player wasn't frozen, to avoid problems with users stuck. But if #4158 was added and nodes could affect walking speed, making players walk very slow when on top of ignore nodes would be simple and a common ground.

**Comment by paramat** [comment]
PR #6447 might help.

**Comment by paramat** [comment]
It turns out the engine does predict player position due to speed and start loading mapblocks from that point, however the prediction distance was limited to 16 nodes, #6447 makes the prediction distance respond to and increase with player speed.

**Comment by paramat** [comment]
New PR #6483 helps a lot.

**Comment by Fixer-007** [comment]
Fixes in what way? Does speed still resets after contact with ignore?

**Comment by lhofhansl** [comment]
With #6483 this can be closed now.
