### ISSUE TITLE
Assertion `g_menuclouds->getReferenceCount() == 1' failed since VBO optimizations commit

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#14432]
## Minetest version

Latest master

Linux with SDL2 (EndeavourOS)

## Summary

In recent master, pressing esc in the main menu results in the following assertion failed:

> src/client/clientlauncher.cpp:270: bool ClientLauncher::run(GameStartData&, const Settings&): Assertion `g_menuclouds->getReferenceCount() == 1' failed.

I ran a git bisect, and VBO-related optimizations and improvements (https://github.com/minetest/minetest/pull/14395) - bb7f57b095cb6c95c5071d80ebc1c5173049c742 is the first bad commit

## Steps to reproduce

* Build in debug mode
* Press esc in the main menu

**Comment by sfan5** [comment]
fixed by #14423
