### ISSUE TITLE
“level” parameter for sounds

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1443]
Adding a “level” parameter for sounds would allow clients to filter which sounds they want to play.

The default maximal level should be something like 10, customizable by a minetest.conf setting.

Sounds would have a level property (default would be 0 probably, thus setting the maximal level to -1 would let a client disable all server sounds if they feel the need), in addition to the current pos, object, loop, gain and max_hear_distance ones.

Example case: let's say a server wants to implement ambient sounds. Some clients may be annoyed by it; they can change their maximal sound level in order to hear other server sounds, but not these ambient sounds.

**Comment by paramat** [comment]
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by paramat** [comment]
I don't see much need, the server is rightly in control of most things the player experiences in a world, so sound is included.
