### ISSUE TITLE
`VoxelManip:was_modified()` doesn't do what it says

### ISSUE THREAD

**Issue by cx384** [minetest/minetest#14435]
## Problem

`VoxelManip:was_modified()` doesn't work as expected.
See https://forum.minetest.net/viewtopic.php?t=30327

#### What the documentation says

https://github.com/minetest/minetest/blob/e734b3f0d8055ff3ae710f3632726a711603bf84/doc/lua_api.md?plain=1#L4853-L4855

#### What it actually does

It can only return true if it is called on a mapgen VoxelManip.
`minetest.set_data()` does not exist.
Instead, one of those functions can make it true
``` lua
minetest.set_node(pos, node)
minetest.add_node(pos, node)
minetest.remove_node(pos, node)
minetest.swap_node(pos, node)
```
And probably more.
It only happens when `ServerMap::updateVManip(v3s16 pos)` gets called, such that `m_is_dirty` becomes true.

## Solutions

Either 
- update the documentation to describe its current behavior
- completely remove the function (deprecate it)
- or change it such that it does what the documentation claims. Maybe this was the case at some point in the past, but I can't recall that `minetest.set_data()` ever existed.

**Comment by sfan5** [comment]
This was "broken" on day one: 9e4e7072da8f565eef37da7558053a436b9cbba3
`set_data` looks like just a typo for `set_node`.

I think the intention for this method is the following situation:
```lua
minetest.register_on_generated(function(...)
    -- ...
    vm:get_data(data)
    -- (work on data)
    something.else() -- code outside of your control, might use set_node
    -- You now have a need to know whether you need to refresh the `data` array
    if vm:was_modified() then
        vm:get_data(data)
    end
    -- (work on data some more)
    vm:set_data(data)
end)
```

I agree it is misleading and at the very least the documentation needs to be fixed. Maybe we even want to deprecate it.

But is there any usecase for what the forum user *thought* it does?

**Comment by cx384** [comment]
I think the forum usecase isn't too useful, since mods typically know what they do with their LVMs, and they can implement a "changed flag" it by themselves.

If `was_modified` stays consistent over multiple `on_generated` callbacks in case the mapgen-LVM is outdated, it may be necessary. However, I'm not too familiar with mapgen and the documentation is very incomplete. Also see #13006.

So for now I don't know what should be done with the function, but the documentation needs to be changed in any case.

**Comment by appgurueu** [comment]
I asked for a [zipgrep](https://content.minetest.net/zipgrep/d995cffc-7c10-4381-bd07-363064e08042/), and it seems modders do not presently use this (at least considering packages on ContentDB).

**Comment by cx384** [comment]
> Normal LVMs do not have the property that their contents are updated if set_node and similar are called.

I meant to check on every set_node and similar call if there exists an active VoxelManip which contains the position, and if yes, set `m_is_dirty` to true.

It's probably the best to deprecate `was_modified`, considering that nobody uses it, it's quite useless, and the documentation was never correct. Using it is basically undefined behavior.

**Comment by sfan5** [comment]
That would introduce quite some complexity as well as edge cases where this doesn't work. Better not to.

> It's probably the best to deprecate was_modified, considering that nobody uses it, it's quite useless, and the documentation was never correct.

I don't disagree with deprecating it. But it definitely isn't useless and I think there's no pressing need to deprecate something that works.
