### ISSUE TITLE
Crash when combining an empty texture

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#14449]
### Minetest version

```true
Minetest 5.9.0-dev-debug-f596c36f4
```

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### Summary

Just tracked down a crash in Exile that my team discovered when running MT 590dev, a crash which gave this fairly unhelpful output:
` /usr/include/c++/12/string_view:239: constexpr const std::basic_string_view<_CharT, _Traits>::value_type& std::basic_string_view<_CharT, _Traits>::operator[](size_type) const [with _CharT = char; _Traits = std::char_traits<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__pos < this->_M_len' failed.`

A bit of gdb work and it turns out we had some code doing the very dumb thing you see here:
`[combine:128x64:0,0=:32,32=cloth_upper_underwear_default.png:0,32=cloth_lower_underwear_default.png`
 where `0,0=:` is an empty texture. I've fixed that now, but there may be other mods out there that will trip this in the future , and it'd probably be polite if the crash output was clearer about what went wrong.

### Steps to reproduce

Attempt to run Exile v0.3.16 with current git, or just add a borked "[combine" modifier to whatever object or node you feel like.

**Comment by SmallJoker** [comment]
02a893d61
