### ISSUE TITLE
My account no longer can sign in to server

### ISSUE THREAD

**Issue by AdityaMH** [minetest/minetest#14455]
### Minetest version

```true
5.9.0-dev
```

### Operating system and version

Android 11

### Summary

In 5.8.0, i can register and sign in to some server.
But, i 5.9.0-dev i no longer can't sign in because "player name contains disallowed character".

But, my player name just using normal alphabets.

### Steps to reproduce

sign in to server and get rejected

**Comment by appgurueu** [comment]
Potentially related: https://github.com/minetest/minetest/pull/13987#issuecomment-1927803725 (also an issue with valid names being considered invalid).

First wild guess: Memory corruption of the allowed characters (but how? shouldn't they be stored in a readonly memory area?). Perhaps the player name is also corrupted.

Second wild guess: The player name somehow does contain invalid characters (like invisible unicode characters).

**Comment by Zughy** [comment]
@AdityaMH out of curiosity, what's your nick?
