### ISSUE TITLE
Some sounds no longer work in 5.9.0-dev

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#14453]
### Minetest version

Where it does not work

```true
Minetest 5.9.0-dev-fbec37886 (Linux)
Using Irrlicht 1.9.0mt15
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0-10-amd64 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Debian 6.1.38-2

### Summary

In Mineclonia I noticed that the sound `mcl_sounds_place_node_water.ogg` no longer works on my Minetest version. It works in 5.6.0.

### Steps to reproduce

1. Install Mineclonia (if not having it already)
2. Create a world and go into creative mode.
3. Give yourself a water bucket and place nodes
4. Notice that no sound is placed when placing water nodes

Optional: Try the same on earlier Minetest version – works on 5.6.0.

**Comment by SmallJoker** [comment]
```
2024-03-11 19:18:05: WARNING[OpenALSoundManager]: Audio: Error decoding mcl_sounds_place_node_water.ogg
2024-03-11 19:18:05: WARNING[OpenALSoundManager]: SoundDataOpenBuffer: Failed to load sound "mcl_sounds_place_node_water.ogg"
```

```sh
games/mineclonia$ find . -type f -name "mcl_sounds_place_node_water.*"
./mods/CORE/mcl_sounds/sounds/mcl_sounds_place_node_water.ogg
```

`mcl_sounds` is loaded according to `/mods`. With rough bisecting I can tell that this issue was introduced before 2024-01-21 (latest RUN_IN_PLACE=1 where I have a matching IrrlichtMt .so).

**Comment by metmj** [comment]
@SmallJoker I have same warning at Minetest 5.8.0 from ubuntu (5.8.0-ppa0~ubuntu22.04.1), but works good when I use 5.6.1 from debian (5.6.1+dfsg+~1.9.0mt8+dfsg-2).

**Comment by Desour** [comment]
Link to the file, so you can add it to your `devtest/mods/soundstuff/sounds/gitignored_sounds`:
https://codeberg.org/mineclonia/mineclonia/src/branch/main/mods/CORE/mcl_sounds/sounds/mcl_sounds_place_node_water.ogg

Can reproduce.

**Comment by Desour** [comment]
I've done a little debugging (<https://github.com/minetest/minetest/commit/43dbebd2993c419b027859ade36f78b0993326a3>).
Apparently `ov_pcm_total` says the sound is 101504 samples long (203008 bytes, because we use s16), but it ends already after 202112 bytes. Idk why this can happen.

**Comment by metmj** [comment]
@Desour something wrong with size? File size should be 23117 bytes.

**Comment by metmj** [comment]
@Desour 202112 is probably the correct value (the buffer_length from the Ogg library returned this value)

**Comment by Desour** [comment]
@ryvnf Would you like to test #14529 with more sounds? :)
