### ISSUE TITLE
Why engine change liquid source if flowing have same type

### ISSUE THREAD

**Issue by metmj** [minetest/minetest#14452]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Ubuntu 22.04 LTS

### Summary

I create some new node as modified water_source (but change some option like pointable). This problem probably occurs in the engine, because despite changing the game (also to developer). I prepared better kelp for mineclonia, but because engine swap node, I wasn't able to achieve the intended goal. I tried use groups instead node.name but this provided another bug: **Not allowing to place CONTENT_IGNORE while trying to replace**
In my opinion flowing liquid in same groups (e.g. water) or if using same liquid options shouldn't modify source, eventually how to protect my node from swap by engine ;)

### Steps to reproduce

add this new node (based on development game, in other games use analogous water and change e.g. **pointable**)
```lua 
minetest.register_node("basenodes:water_pointable", {
	description = "Water Source" .. "\n" ..
		"Swimmable, spreading, renewable liquid" .. "\n" ..
		"Drowning damage: 1",
	drawtype = "liquid",
	waving = 3,
	tiles = { "default_water.png" .. WATER_ALPHA },
	special_tiles = {
		{ name = "default_water.png" .. WATER_ALPHA, backface_culling = false },
		{ name = "default_water.png" .. WATER_ALPHA, backface_culling = true },
	},
	use_texture_alpha = "blend",
	paramtype = "light",
	walkable = false,
	pointable = true,
	diggable = false,
	buildable_to = true,
	is_ground_content = false,
	drowning = 1,
	liquidtype = "source",
	liquid_alternative_flowing = "basenodes:water_flowing",
	liquid_alternative_source = "basenodes:water_source",
	liquid_viscosity = WATER_VISC,
	post_effect_color = { a = 64, r = 0, g = 0, b = 0 },
	post_effect_color_shaded = true,
	groups = { water = 3, liquid = 3 },
})
```
 place on game and ... it's disappear, because it's change to default water source, probably based on 	liquid_alternative_source from flowing_water,

**Comment by appgurueu** [comment]
You're violating the API contract here. `lua_api.md` states:

> You *must* set `liquid_alternative_source` to the node's own name.

We could make a better effort to throw an error if this is not the case.

"Connecting" to another liquid's flowing nodes won't work either: The flowing node definition will have the source alternative set to a different liquid's source node, so the flowing nodes won't connect to the source node.

In general, `liquid_alternative_source` and `liquid_alternative_flowing` are intended for a 1:1-relationship. I'm not aware of any other usage we would currently be supporting.

**Comment by metmj** [comment]
> You're violating the API contract here. `lua_api.md` states:
> 
> > You _must_ set `liquid_alternative_source` to the node's own name.
> 
> We could make a better effort to throw an error if this is not the case.
> 
> "Connecting" to another liquid's flowing nodes won't work either: The flowing node definition will have the source alternative set to a different liquid's source node, so the flowing nodes won't connect to the source node.
> 

Ok, my fault, but I probably found some stinky code by the way. If I have A and B as a source and outflow pair, and C is a source using B (operation outside the API provided). If liquid B is created as flowing from C, then in my opinion it probably shouldn't automatically change the source node C to A, right? I haven't looked into the C++ code, so I don't know if such a thing doesn't also happen in the case of API-compliant use, i.e. whether the flowing B from A modifies A - if so, whether such an action was intentional, because it is certainly burdened with some additional cost and it is beyond the control of standard triggers declared in the API (such as on_destruct etc.)

> **In general, `liquid_alternative_source` and `liquid_alternative_flowing` are intended for a 1:1-relationship. I'm not aware of any other usage we would currently be supporting.**

Oh my God, so probably it's near impossible to create water plant like minecraft-style, you can only use crazy modifications to the appearance of the ground node (like mineclonia's kelp).

**Comment by appgurueu** [comment]
> Ok, my fault, but I probably found some stinky code by the way.

So far, the only minor issue I see is that no error is thrown. It would be better to throw one.

> If I have A and B as a source and outflow pair, and C is a source using B (operation outside the API provided). If liquid B is created as flowing from C, then in my opinion it probably shouldn't automatically change the source node C to A, right?

In my opinion, it should just crash with a helpful error message if you do that. Otherwise, we're reaching into "behavior that is not defined by Minetest" territory, so all bets about what "should" automatically happen are off.

> I haven't looked into the C++ code, so I don't know if such a thing doesn't also happen in the case of API-compliant use, i.e. whether the flowing B from A modifies A - if so, whether such an action was intentional, because it is certainly burdened with some additional cost and it is beyond the control of standard triggers declared in the API (such as on_destruct etc.)

If you're looking for bugs, you don't have to look into the source code, you can (and should) just test. If the behavior doesn't match what we're documenting, file a bug report.

I see no necessity to touch or analyze the flowing liquid code based on the fact that it behaves weirdly when its invariants are broken. Even if it does a "no-op" update of the source liquid, that is not an issue, and need not call any callbacks. It might be a minor performance concern, but that would first have to be demonstrated.

> Oh my God, so probably it's near impossible to create water plant like minecraft-style, you can only use crazy modifications to the appearance of the ground node (like mineclonia's kelp).

I'm not sure how you were hoping to use a different kind of liquid to achieve a different kind of plant. What is wrong with the hack currently used for underwater plants? This sounds like a feature request to me.

**Comment by metmj** [comment]
> I'm not sure how you were hoping to use a different kind of liquid to achieve a different kind of plant. What is wrong with the hack currently used for underwater plants? This sounds like a feature request to me.

instead of referring to the essence of the world (1 pos = 1 node), you must have create a set of nodes and an virtual node (ground), which causes complicated logic and the use of inconvenient metadata (you can't use the same proven code as for regular plants or bamboo despite very similar behavior), problems with the correct response to the pointer (currently in Mineclonia it is only caught at the ground, I was planning to implement it as nodes, but it looks like I'm doomed to continue doing it in this twisted way), you cannot do it with graphics alone also a real copy of the bubble column (especially the one working upwards).
