### ISSUE TITLE
i cant compile

### ISSUE THREAD

**Issue by SusgUY446** [minetest/minetest#14460]
### Minetest version

```true
newest version of source code
```

### Operating system and version

Windows 11

### CPU model

Processor	12th Gen Intel(R) Core(TM) i5-1235U, 1300 Mhz, 10 Core(s), 12 Logical Processor(s)

### GPU model

Built Into Cpu

### Summary

when i try compiling i get this error (see file)
[build_log.txt](https://github.com/minetest/minetest/files/14615406/build_log.txt)

### Steps to reproduce

clone the repo
install everything 
configure cmake
try compiling

**Comment by rollerozxa** [comment]
It looks like you are trying to compile with MSYS2 using instructions for compiling with MSVC. If you want to compile Minetest with MSYS2 you can follow this guide instead: https://wiki.voxelmanip.se/Compiling_on_Windows_using_MSYS2

**Comment by SusgUY446** [comment]
i compiled it on wsl now.
