### ISSUE TITLE
Sky goes black underground

### ISSUE THREAD

**Issue by theraven262** [minetest/minetest#14468]
### Minetest version

```true
Commit hash: 61a57336920e0f64361a4c48215b12969c3a1eff
```

### Operating system and version

Arch Linux

### Summary

As noticed in https://github.com/minetest/minetest/pull/14296#issuecomment-1906770135 the underground sky is almost always completely black.
The actual sky color is getting scaled close to zero when multiplied by m_brightness: https://github.com/minetest/minetest/blob/61a57336920e0f64361a4c48215b12969c3a1eff/src/client/sky.cpp#L424-L429 This is due to a loop which makes m_brightness move ever towards zero: https://github.com/minetest/minetest/blob/61a57336920e0f64361a4c48215b12969c3a1eff/src/client/sky.cpp#L380-L385

Resetting m_brightness to the default value of 0.5 just above the loop seems to alleviate the issue, assuming that the desired result is to make the sky just a bit darker when underground.

### Steps to reproduce

To reproduce the issue: go underground and notice that whatever you set as sky colors doesn't matter, the sky is black.

To reproduce the workaround/fix: add "m_brightness = 0.5f;" just above this line: https://github.com/minetest/minetest/blob/61a57336920e0f64361a4c48215b12969c3a1eff/src/client/sky.cpp#L373

**Comment by sfan5** [comment]
> This is due to a loop which makes m_brightness move ever towards zero:

The purpose of this loop is to gradually move the actual sky brightness to the actual brightness it should have.

I think the general idea of this behavior was that the sky is not supposed to be seen underground but if it is (due to holes in world rendering) then it should be much darker.
There is some complex logic for determining how bright the background should be and/or if the sunlight can be seen, in which case the sky color is not darkened:
https://github.com/minetest/minetest/blob/4f84b0135608676edc9969a653eaae07dce37e98/src/client/game.cpp#L3995-L4001

I suppose all this should be configurable via the API but for that it'd be good to hear what your use case/intent is.

**Comment by theraven262** [comment]
It is quite confusing that there is an indoors sky color parameter when the engine effectively ignores the indoors sky color. 
This probably wouldn't be an issue though if the sky wasn't always fading to black, and not for example just getting somewhat darkened, or interpolated with another darker color of choice.

I can't say that I don't see the logic behind darkening the sky like this. In the default underground setting this approach achieves exactly what I'm trying to achieve with a colored sky: making the terrain fade to a single color. But if the fog color can be set to a different value, then to preserve this fading behavior the sky color should be set to that same value.

My use case has been coloring the sky of underground biomes.
Terrain with colored fog, but black sky:
![screenshot_20240316_164152](https://github.com/minetest/minetest/assets/17565899/684c0c14-d1de-4ea3-a799-0aede9919720)
Sky with the above workaround applied (still dark, but could work):
![screenshot_20240317_153754](https://github.com/minetest/minetest/assets/17565899/1ebcf24f-1776-4ed7-b6cd-018f83294462)
Sky colored almost the same color as fog (removed the sunlight check for this):
![screenshot_20240317_112205](https://github.com/minetest/minetest/assets/17565899/b1bcc640-4569-416e-b01f-9b771b7e5e9a)

I figured that I can completely ignore this issue by switching to a "plain" type skybox for these underground biomes which are completely underground.

But to color a sky which can be shown both above and below ground, I'd have to make two versions of a skybox and implement the check for if the player is underground in order to switch between them. The ability to control (the behavior of?) the brightness parameter instead (and just use a single skybox) would make this way less messy.

**Comment by sfan5** [comment]
I think I get what you are getting at.

To be honest I just added `fog_color` to replicate the behavior of Minetest 0.3 for my [game](https://github.com/sfan5/minetest_classic). Whether the behavior made sense for other API users was not my concern.
Given that normally the sky color must equal the fog color to make the fog effect look correct the uses for it are indeed limited.

For your use case however it sounds like the "plain" skybox is the correct choice.

> The ability to control (the behavior of?) the brightness parameter instead (and just use a single skybox) would make this way less messy.

I agree in general that the brightness mechanism should be somehow controllable by mods, but I can't immediately think of how a sensible API for this would look.

**Comment by Zughy** [comment]
It seems like 5.9 (and 5.10-dev) don't trigger the black sky anymore. The worst I've seen is seeing the sky desaturating
