### ISSUE TITLE
camera wont rotate

### ISSUE THREAD

**Issue by SusgUY446** [minetest/minetest#14461]
### Minetest version

```true
Version 5.8.0 (shown in video) but its also the latest version
```

### Operating system and version

Ubuntu 22.04.3 LTS (WSL)

### CPU model

Processor	12th Gen Intel(R) Core(TM) i5-1235U, 1300 Mhz, 10 Core(s), 12 Logical Processor(s)

### GPU model

Intel Iris Graphics

### Active renderer

OpenGL 4.1

### Summary

i cant rotate my camera
https://streamable.com/q0ch3e

### Steps to reproduce

i downloaded the games code from github then compiled it myself

**Comment by SusgUY446** [comment]
sometimes it works
https://streamable.com/g58g1i
but its laggy

**Comment by rollerozxa** [comment]
Apps don't seem to be able to capture the cursor in WSL (https://github.com/microsoft/wslg/issues/376). You'll have to make due with it for engine development and then use a native Windows version when you want to actually play Minetest.

**Comment by SusgUY446** [comment]
i tried building on windows but compiling on windows is just shit. gives a error longer then the bible
