### ISSUE TITLE
android: transparent textures are black

### ISSUE THREAD

**Issue by Unacceptium** [minetest/minetest#14462]
### Minetest version

```true
latest master https://github.com/minetest/minetest/actions/runs/8294735048
```

### Irrlicht device

ANDROID

### Operating system and version

Android 12 Magic UI 6

### CPU model

idk

### GPU model

idk

### Active renderer

default setting

### Summary

transparent textures are black as background
-
please mark that i dont know if this is wanted for example debugging
(images-how should be)
![Screenshot_20240315_185535](https://github.com/minetest/minetest/assets/145642963/60747e86-9df5-4fcd-a6c8-e69320953215)
![Screenshot_20240315_185553](https://github.com/minetest/minetest/assets/145642963/02835f36-7e20-4486-93b0-f8275ebfbc5a)
(images-and how it is)
![Screenshot_20240315_185347](https://github.com/minetest/minetest/assets/145642963/f90c1c03-eb2d-4ef2-b969-31d8ef2dbab3)
![Screenshot_20240315_185754](https://github.com/minetest/minetest/assets/145642963/34dff3c8-25c7-46db-af60-2ef8869f3cae)

### Steps to reproduce

download and sign apk
https://github.com/minetest/minetest/actions/runs/8294735048
then get a block wich is transparent
there you can see they arent

E D I T
every setting is full default
E D I T 2
no matter which video driver is set

**Comment by Unacceptium** [comment]
/

**Comment by y5nw** [comment]
> Are you sure you've set `use_texture_alpha` correctly?

I cannot talk about other mods, but I can confirm that the train tracks in the screenshot show that this is related to the missing/incorrectly set `use_texture_alpha` fields, which is already [known in December 2023](https://lists.sr.ht/~gpcf/advtrains-devel/patches/48159) and [fixed last month](https://git.bananach.space/advtrains.git/commit/?id=64776ba60e8e16cbfd4cbc51447284ba074abeec).

**Comment by wsor4035** [comment]
mods need to set `use_texture_alpha` with strings rather than boolean now. the depreciation period is over and compatibility code has been removed
