### ISSUE TITLE
L-system tree nodes aren't always correctly rotated since #14355

### ISSUE THREAD

**Issue by Niklp09** [minetest/minetest#14471]
### Minetest version

```true
Minetest 5.9.0-dev-60810c2d3-dirty (Linux)
Using LuaJIT 2.1.1710088188
Built by GCC 13.2
Running on Linux/6.6.19-1-MANJARO x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
STATIC_SHAREDIR="."
```

### Operating system and version

Manjaro

### Summary

L-System tree generation is partially broken since https://github.com/minetest/minetest/pull/14355. On every ~2nd tree are the trunk nodes (`param1`) not correctly rotated.
![screenshot_20240317_165056](https://github.com/minetest/minetest/assets/89982526/5ce30038-95ee-4a47-8e63-68eefe51fa45)

### Steps to reproduce

1. Make sure you're on `60810c2` or later
2. Install a mod which uses the L-system for tree generation e.g. moretrees
3. Notice that some trunk nodes are not correctly rotated

**Comment by sfan5** [comment]
Possible cause: param1 and param2 of `treegen::TreeDef.trunknode` and other are left uninitialized.

**Comment by SmallJoker** [comment]
@Niklp09 Does this fix your issue? Asking because on my end, all trunks happened to be placed with `param2 = 0`.
```
diff --git a/src/mapgen/treegen.h b/src/mapgen/treegen.h
index 5ba1cc10c..bae541030 100644
--- a/src/mapgen/treegen.h
+++ b/src/mapgen/treegen.h
@@ -36,6 +36,13 @@ namespace treegen {
        };
 
        struct TreeDef : public NodeResolver {
+               TreeDef() :
+                       // Initialize param1 and param2
+                       trunknode(CONTENT_IGNORE),
+                       leavesnode(CONTENT_IGNORE),
+                       leaves2node(CONTENT_IGNORE),
+                       fruitnode(CONTENT_IGNORE)
+               {}
                virtual void resolveNodeNames();
 
                std::string initial_axiom;
```

**Comment by Niklp09** [comment]
Yes, your patch works for me

**Comment by SmallJoker** [comment]
a862e429
