### ISSUE TITLE
This Happend when building with cmake

### ISSUE THREAD

**Issue by TheClaytonDab21** [minetest/minetest#14488]
### Minetest version

```true
Minetest 5.9.0-dev
```

### Operating system and version

Linux Bookworm

### Summary

![image](https://github.com/minetest/minetest/assets/162779116/60478bfe-8f06-4379-8ef0-504ab2c832f3)
This happen when i type in the build commands
ps this was a fresh install

### Steps to reproduce

build it

**Comment by wsor4035** [comment]
do you have the `libsdl2-dev` package installed? https://github.com/minetest/minetest/blob/master/doc/compiling/linux.md

**Comment by theclaytondab** [comment]
It says unable to locate package libsd12-dev

**Comment by wsor4035** [comment]
`libsdl2-dev` != `libsdl2-dev`

you have a misspelling there

**Comment by oong819** [comment]
(Reply if work)

**Comment by theclaytondab** [comment]
minetest works but I just redownload it, I don't see the typo?

**Comment by theclaytondab** [comment]
Oh nevermind I got it
