### ISSUE TITLE
0 online player servers should go to the bottom of the list

### ISSUE THREAD

**Issue by dibesfer** [minetest/minetest#14504]
Theres a huge gap between 1-4 players servers under headless servers with 0 players.

I mean current players online, like down to the middle end of the list, theres lots of aged stable pingless headless servers without players

![image](https://github.com/minetest/serverlist/assets/57419948/f5f78d07-58df-4703-87ea-ca818575963a)

I think those values: server age, stability, ping... should be used to sort servers with same players online
but **all 0 players online servers should go to the bottom of the list**, and them be sorted with those parameters.

Else, empty servers should have a score cap at the very least.

Thats default in most game servers list i think

That way will also improve the first impression scrolling down the server list.

Next pro solution would include sorting parameters options in the GUI.

**Comment by sfan5** [comment]
Moved to engine repo because this is caused by the main menu re-sorting the list according to (rough) physical distance.
The sorting performed by the list itself (seen [here](https://servers.minetest.net/)) pretty consistently keeps empty servers at the bottom.

**Comment by SwissalpS** [comment]
I hope a server that usually has players doesn't drop to the bottom just because it has zero players for a few hours.

**Comment by dibesfer** [comment]
I hope humble networking servers have a chance, and the whole list overall doesn't feel like liminal spaces.

**Comment by sfan5** [comment]
Servers are intentionally not sorted by straight number of players (like you seem to be suggesting). There are more factors at play.

**Comment by dibesfer** [comment]
Yes, I guess. That's just my ability sorting json server list api to show some of the gap down jewels.
