### ISSUE TITLE
Scrolling with mouse wheel in main menu settings is broken

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#14517]
### Minetest version

```true
Minetest 5.9.0-dev-6ca214fef (Linux)
Using Irrlicht 1.9.0mt15
Using LuaJIT 2.1.1702233742
Built by GCC 13.2
Running on Linux/6.8.2-arch2-1 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

Happens in master.

Bisected to 6ca214fefc9e1eb707f006631d39c1e4dbafe1b5 + https://github.com/minetest/irrlicht/commit/3992129735ca56b13b7014d9862924bc2480fbaa.

Might depend on build type. I.e. last time I tried, building with sanitizers in Debug build in master, the bug didn't appear.
Reproducible with Release builds.

### Irrlicht device

SDL

### Operating system and version

arch linux

### CPU model

AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx

### GPU model

amd vega 8

### Active renderer

OpenGL 4.6

### Summary

Scrolling with mouse wheel in the main menu settings scroll containers seems to only work if you move your mouse while spinning the mouse wheel.

### Steps to reproduce

* Open the settings menu.
* Place your mouse cursor in the middle of the screen.
* Spin your mouse wheel.
* => This should scroll the scroll container up and down. But it doesn't work if you hold your mouse still.

**Comment by grorp** [comment]
I haven't observed this with `-DUSE_SDL2=FALSE`, so it could be related to the SDL Irrlicht device.

**Comment by appgurueu** [comment]
Couldn't reproduce with SDL enabled, `RelWithDebInfo` build type compiled with clang on Ubuntu 22.04.
