### ISSUE TITLE
Random ContentDB install failures because of same temporary folder being used for two packages

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#14518]
### Minetest version

```true
Minetest 5.9.0-dev-0ea1ec31f (Linux)
Using LuaJIT 2.1.1707061634
Built by Clang 17.0
Running on Linux/6.7.11-200.fc39.x86_64 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Fedora Linux 39 (Workstation Edition)

### Summary

The ContentDB dialog sometimes fails to install packages with the following error message:

```
Error installing "<insert package name here>": Unable to find a valid mod, modpack, or game
```

This only happens with mods that have dependencies. Some packages exhibit this more often than others (I found the problem with my "GGraffiti" mod). It happens more often if the "mods" folder doesn't exist yet. It also happens more often if installing the package is the very first thing you do after opening Minetest.

By adding some logging code and inspecting my `/tmp` folder, I found out that the reason of the error is that the ContentDB dialog accidentally uses the same temporary folder to extract two packages, which breaks the "only one package exists in the temporary folder" assumption made here:

https://github.com/minetest/minetest/blob/0ea1ec31fc19ea5026db9b068bb3a606a8505d0b/builtin/mainmenu/content/pkgmgr.lua#L255-L277

The name of the temporary folder is determined here, using `math.random`, so getting the same folder name twice shouldn't actually be possible:

https://github.com/minetest/minetest/blob/0ea1ec31fc19ea5026db9b068bb3a606a8505d0b/builtin/mainmenu/content/dlg_contentstore.lua#L99-L107

But I found out that `math.random` often returns duplicate values if you call it from different asynchronous tasks started via `core.handle_async`. I guess this happens because we call `os.randomseed()` like this:

https://github.com/minetest/minetest/blob/0ea1ec31fc19ea5026db9b068bb3a606a8505d0b/builtin/init.lua#L29

`os.time()` obviously returns the same value on many of the worker threads.

### Steps to reproduce

Repeat the following steps until you see the error message:

1. Delete the "mods" folder.
2. Open Minetest.
3. Try to install my GGraffiti mod (yay, more downloads for me ;)

**OR**

Add this code to "builtin/mainmenu/init.lua":

```lua
local randos = {}
for i = 1, 12 do
	core.handle_async(function()
		return math.random(1, 1024000)
	end, nil, function(v)
		table.insert(randos, v)
		if #randos == 12 then
			print(dump(randos))
		end
	end)
end
```

Example result I got:

```lua
{
	878129,
	878129,
	878129,
	370665,
	370665,
	642779,
	878129,
	642779,
	915659,
	370665,
	915659,
	370665
}
```

There are many duplicate values.

**Comment by sfan5** [comment]
fix is in #14519 for both problems:
* fixing the random seed
* instead using better OS functions to create temporary folders
