### ISSUE TITLE
Emojis crash Minetest

### ISSUE THREAD

**Issue by ThePython10110** [minetest/minetest#14527]
### Minetest version

```true
Minetest 5.8.0 (from minetest.net)
```

### Irrlicht device

WIN32

### Operating system and version

Windows 10

### CPU model

Intel Core i7-6700

### Active renderer

OpenGL 4.6.0

### Summary

When pasting certain emojis into any text box, Minetest either crashes or shows `Some exception: "wstring_convert::to_bytes"`, depending on where it's entered. After that, I can't copy or paste anything anywhere until I close Minetest, after which my clipboard still contains that character (even if I tried to copy other text). Attempting to paste into Minetest causes the same error. According to [this site](https://evercoder.github.io/clipboard-inspector), my clipboard contains an empty string until I close Minetest.

Here are some characters that crash it (although it's probably just all emojis): 😀🍔💔🍞🤪

### Steps to reproduce

Paste any of these characters (maybe any emoji) into any text box: 😀🍔💔🍞🤪

Apparently there's a PR in which the same error came up: #14121 
No idea whether it's actually related.

It seems like this didn't happen a few years ago, and the invalid characters were just replaced with question marks: #11300

**Comment by SwissalpS** [comment]
I tried to reproduce on a Fedora (linux) build: 5.9.0-dev-e7dbd32 and can't confirm.
Pasting the emojis just results in what looks like spaces and I was able to use the clipboard normally; minetest did not crash.

**Comment by appgurueu** [comment]
Can't confirm using the official 5.8.0 build on Ubuntu 22.04.

1. Could you check whether this still appears in 5.9-dev?
2. If so, could you try to get a stacktrace using `--debugger` (see [here](https://dev.minetest.net/Development_troubleshooting) for details)?

**Comment by grorp** [comment]
I can confirm the `Some exception: "wstring_convert::to_bytes"` part, I don't know about the crash part. #14523 probably fixes this.

**Comment by ThePython10110** [comment]
It crashed when I pasted it into the chat and into a node's formspec, but not into the server search list (just showed the error). So maybe it only crashes in-game?

**Comment by SwissalpS** [comment]
I pasted in-game.

**Comment by ThePython10110** [comment]
According to grorp, this doesn't happen on Linux.

**Comment by grorp** [comment]
Tested again. When pasting in-game, what I get is not a crash, but an (unrecoverable?) gray screen.
