### ISSUE TITLE
Crosshair not visible in latest master 2d8e4df

### ISSUE THREAD

**Issue by superfloh247** [minetest/minetest#14520]
### Minetest version

```true
Minetest 5.9.0-dev-2d8e4df (OSX)
Using LuaJIT 2.1.1710088188
Built by Clang 15.0
Running on Darwin/23.3.0 arm64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
```

### Irrlicht device

OSX

### Operating system and version

MacOS 14.3.1

### CPU model

apple silicon m1pro arm64

### GPU model

apple silicon m1pro arm64

### Active renderer

OpenGL 2.1

### Summary

Crosshair is no longer visible since a few commits - HUD is visible

affected Minetest 5.9.0-dev-2d8e4df (OSX)

![screenshot_20240405_164850](https://github.com/minetest/minetest/assets/26180993/b6eb4292-2ba6-49e3-9daf-65c73023bb56)

not affected:
Minetest 5.8.0 (OSX)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.1700008891
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1

![screenshot_20240405_164907](https://github.com/minetest/minetest/assets/26180993/274d35de-c547-45bd-8cfb-3c674a54595c)

### Steps to reproduce

start minetest

**Comment by superfloh247** [comment]
maybe related to #14501

**Comment by grorp** [comment]
Oh no, the crosshair size is probably being std::floor'ed to zero. Should be an easy fix.

**Comment by superfloh247** [comment]
hud_scaling = 2
makes the HUD quite ugly, and the crosshair is visible again

hud_scaling = 1
this is the usual HUD look, crosshair invisible

**Comment by superfloh247** [comment]
hud_scaling = 1.51

this is a workaround which makes the HUD acceptable and the crosshair visible

**Comment by superfloh247** [comment]
yes, looks good with hud_scaling = 1 and not hud_scaling set at all
