### ISSUE TITLE
Irrlicht sometimes reports unexpected multibyte character

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#1454]
Holding Volume Down + Power on Android (to take a screenshot) sometimes produces the following error:
`16:44:01: ERROR [main]: KeyPress: Unexpcted multibyte character 00000000`

![http://imgur.com/eDLbCcd.png](http://imgur.com/eDLbCcd.png)

**Comment by MoNTE48** [comment]
In my project, I simply disable error output Irrlicht chat.

**Comment by est31** [comment]
Somebody should talk to irrlicht about this.

**Comment by ShadowNinja** [comment]
@est31: The error message is generated in keycode.cpp.  What makes you think this is an Irrlicht bug?

**Comment by MoNTE48** [comment]
I found a solution. I will share with you later, if anyone is interested.

**Comment by MoNTE48** [comment]
https://github.com/minetest/minetest/blob/master/build/android/patches/irrlicht-back_button.patch#L7
@sapier, you're an idiot!

**Comment by paramat** [comment]
Can you make a PR to fix?

**Comment by paramat** [comment]
Solution according to MoNTE is:
Remove this https://github.com/minetest/minetest/blob/master/b​uild/android/patches/irrlicht-back_button.patch#L7 and add https://gist.github.com/MoNTE48/​0906326741c8b4bc39938c37869d5c3c on nativeactivity.java

**Comment by MoNTE48** [comment]
Correct link
