### ISSUE TITLE
Async mapgen environment: get_gen_notify is nil

### ISSUE THREAD

**Issue by MisterE123** [minetest/minetest#14540]
### Minetest version

```true
Minetest 5.9.0-dev-7e7a14a-dirty
```

### Operating system and version

n/a (windows)

### Summary

When calling `minetest.get_gen_notify()` in the async mapgen environment, you get ``` attempt to call field 'get_gen_notify' (a nil value)```

### Steps to reproduce

[biomegen-mglua-refactor.zip](https://github.com/minetest/minetest/files/14961392/biomegen-mglua-refactor.zip)
[luamap.zip](https://github.com/minetest/minetest/files/14961393/luamap.zip)
[mandeland.zip](https://github.com/minetest/minetest/files/14961394/mandeland.zip)

The above mod is an attempt to port biomegen to the async environment. To reproduce, run the trio of mods uploaded here. luamap and mandeland are modified to use the async environment.

In biomegen, see mapgen.lua. At line 42, in function initialize_biome_data(), at line 47, minetest.get_gen_notify() is called and causes a nil value error (minetest.get_gen_notify() does not exist)

To make biomegen run anyways without erroring, comment out lines 47 - 62.

**Comment by sfan5** [comment]
No `get_gen_notify` is indeed just an omission.
But I can tell you that the approach the code you linked takes has to be reworked quite a bit to work with mapgen threading: It overrides engine functions like `get_mapgen_object` to instead provide its own data. But this has to happen in the main environment instead, so getting the data thread is not that trivial anymore.

**Comment by MisterE123** [comment]
I think gael's solution, rather than porting biomegen, was to make the PR for minetest.generate_biomes
