### ISSUE TITLE
Pointing problems when you stand exactly at (-10.5, ?, ?)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#14554]
### Minetest version

```true
5.8.0
```

### Irrlicht device

X11

### Operating system and version

Parabola

### Active renderer

OpenGL 4.5

### Summary

If you stand at a position where the fractional part of the X or Z coordinate is EXACTLY .5 AND the same coordinate is negative, you can't point nearby nodes. Example numbers: -10.5, -4.5, -0.5.

**Significance**:

Normally, this bug is unlikely to occur since the player has to match that bad coordinate EXACTLY. But a player can get at such a coordinate via `set_pos`. If the player is then unable to move, this bug is suddenly much more visible.

I've discovered this by reworking the bed in Repixture, which puts the player at a .5 coordinate (in the middle of the bed). The workaround was to put the player at a slightly different coordinate.

### Steps to reproduce

1. Generate a flat world
2. Do this command: `/teleport -10.5 ~ ~`
3. Try to point the nodes near you (don't walk!)

Expected result: You can point every node.
Actual result: You can't point the nodes close to you, but the ones further away can be pointed.

Note: It doesn't have to be -10.5. It can be any number `X-0.5`, where X is a negative whole number. This also happens with the Z axis. You can also try to set both X and Z. I haven't tested Y.

The pointing failure stops as soon you move the tiniest bit.

**Comment by Desour** [comment]
Can reproduce.
