### ISSUE TITLE
Possible dangling reference in ModifySafeMap::get

### ISSUE THREAD

**Issue by JosiahWI** [minetest/minetest#14569]
### Minetest version

```true
Minetest 5.9.0-dev-d2a089ffd-dirty (Windows)
Using LuaJIT 2.1.0-beta3
Built by MSVC 19.39
Running on Windows/10.0.22621 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
STATIC_SHAREDIR="."
```

### Operating system and version

Microsoft Windows 11 Home 10.0.22631 Build 22631

### Summary

The following snippet is from util/container.h L365-372:
```cpp
        const V &get(const K &key) const {
                if (m_iterating) {
                        auto it = m_new.find(key);
                        if (it != m_new.end())
                                return it->second;
                }
                auto it = m_values.find(key);
                return it == m_values.end() ? null_value : it->second;
        }
```
A ternary operator may create a temporary object if it has to convert one of the operands to a prvalue [according to these rules](https://en.cppreference.com/w/cpp/language/operator_other). If that happens, this function may return a dangling reference to that temporary object. MSVC thinks that's exactly what happens in this method.

> C:\Users\yoshe\code\open_contrib\minetest\src\util\container.h(372): warning C4172: returning address of local variable
 or temporary [C:\Users\yoshe\code\open_contrib\minetest\build-msvc\src\minetest.vcxproj]
 
 I was unable to reproduce the warning on GCC nor do GCC Asan or Valgrind report any errors running the following unit test:
```cpp
void testTemporary() {
        ModifySafeMap<int, int> map;
        map.put(0, 0x12);
        UASSERT(map.get(0) == 0x12);
}
```
I don't have the C++ knowledge to know whether this is a false positive or not. In any case it seems quite risky compared to a simple if/else that definitely won't dangle anything.

### Steps to reproduce

Compile on MSVC and observe the warning.

**Comment by sfan5** [comment]
> I was unable to reproduce the warning on GCC nor do GCC Asan or Valgrind report any errors running the following unit test:

Have you treid a non-trivial type?
Or perhaps even one that prints in its con-/destructor?

**Comment by JosiahWI** [comment]
```cpp
void TestDataStructures::testMap2()
{
        ModifySafeMap<int, Tracker> map;
        TrackerState t0, t1;

        // overwrite
        map.put(1, Tracker(t0));
        map.put(1, Tracker(t1));
        std::cerr << "EVERYTHING PUT!\n";
        UASSERT(map.get(1));
        std::cerr << "GOT!\n";
        UASSERT(t0.deleted);
        UASSERT(!t1.copied);
        UASSERT(!t1.deleted);

        map.clear();
}
```

```
CONSTRUCTOR2
CONSTRUCTOR1
MOVE ASSIGNMENT
DESTRUCTOR
CONSTRUCTOR2
MOVE ASSIGNMENT
DESTRUCTOR
EVERYTHING PUT!
GOT!
DESTRUCTOR
[PASS] testMap2 - 2ms
```

I think it's a false positive.

**Comment by sfan5** [comment]
Sorry, I didn't read closely and thought you meant the `null_value`.
`it->second` can never be a dangling reference since it's inside the map. You should test the other thing instead.

**Comment by JosiahWI** [comment]
Whoops, it may be necessary to test both.

```cpp
void TestDataStructures::testMap2()
{
        ModifySafeMap<int, Tracker> map;
        TrackerState t0, t1;

        // overwrite
        map.put(1, Tracker(t0));
        map.put(1, Tracker(t1));
        std::cerr << "EVERYTHING PUT!\n";
        UASSERT(!map.get(-1));
        std::cerr << "GOT!\n";
        UASSERT(t0.deleted);
        UASSERT(!t1.copied);
        UASSERT(!t1.deleted);

        map.clear();
}
```
CONSTRUCTOR2
CONSTRUCTOR1
MOVE ASSIGNMENT
DESTRUCTOR
CONSTRUCTOR2
MOVE ASSIGNMENT
DESTRUCTOR
EVERYTHING PUT!
GOT!
DESTRUCTOR
[PASS] testMap2 - 0ms
```

It looks like the null value doesn't get converted to a temporary either.

**Comment by Desour** [comment]
>[according to these rules](https://en.cppreference.com/w/cpp/language/operator_other)

Are referring to this point?

>6.1) If both E2 and E3 now have the same type, the result is a prvalue of that type designating a temporary object(until C++17)whose result object is(since C++17) copy-initialized from whatever operand was selected after evaluating E1.

Since C++17, there's no temporary object. (Read it as: Result object of the prvalue will be copy-initialized later. Not: The result of the expression is copy-initialized. (Easy to misread imo.))
(I didn't know there was a temporary object in pre 17. :eyes:)

**Comment by JosiahWI** [comment]
Ah, phew, it seems safe in all cases since we're on C++17, then. I wonder if a bug report should be filed with MSVC?

**Comment by Desour** [comment]
Actually, thinking about it again, the result is a prvalue (because of the lvalue-to-rvalue conversions), but we return an lvalue reference. So maybe there *is* a temporary object, that binds to the lvalue reference, resulting in a dangling reference.

On the other hand, 4) says, it's a glvalue:
>4) If E2 and E3 are glvalues of the same type and the same value category, then the result has the same type and value category

[This C++17 standard draft I found](https://www.open-std.org/JTC1/SC22/WG21/docs/papers/2017/n4659.pdf) doesn't say at this point that it's a prvalue:
>—(7.1) The second and third operands have the same type; the result is of that type and the result object is
initialized using the selected operand.

So, maybe we should read this as "the conversions are applied if necessary":
>6) The lvalue-to-rvalue, array-to-pointer, and function-to-pointer conversions are applied to the second and third operands.

Anyway, we can just replace the ternary with an if.
