### ISSUE TITLE
Add something that moves to the shutdown screen

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#14571]
### Problem

If a game takes a long time to shut down, users might think that the game has hung up, as there is no indication that something is still happening on the "Shutting down..." screen.

![the shutdown screen](https://github.com/minetest/minetest/assets/82708541/2757a5c4-303e-4fe7-b4cc-c18e1c3cff6f)

### Solutions

Add something that moves to the "Shutting down..." screen. For example, we could enable clouds there too.

### Alternatives

Add a progress indicator. This would be much better, but I think it's impossible.

**Comment by nininik0** [comment]
Yep. Can confirm.

**Comment by nininik0** [comment]
Something we can do is add a custom anim bg

**Comment by rubenwardy** [comment]
I suggest making the progress bar an indeterminate progress bar, so you can see panning stripes
