### ISSUE TITLE
interpolation does nothing on set_bone_override

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#14570]
### Minetest version

```true
Literally I just keep pulling from the latest github and it's still happening
```

### Irrlicht device

x11

### Operating system and version

opensuse tumbleweed

### CPU model

ryzen 5800x

### GPU model

AMD Radeon RX 6800 XT

### Active renderer

OpenGL 4.6

### Summary

``thing:set_bone_override()`` interpolation for rotation literally does nothing at all, no numbers change anything, they just keep snapping to the next rotation.

I have created a video specifically for this bug report with the sample code below: https://youtu.be/7g5OJeiDMWc

### Steps to reproduce

``thing:set_bone_override()`` on anything, literally anything, I'm using it with character.b3d

I was asked to provide a sample code to reproduce so here it is:
```ts
// This works with the default character.b3d
const start = vector.create3d(math.pi / 4, 0, 0);
const end = vector.create3d(-math.pi / 4, 0, 0);
let timer = 0;
let state = false;

minetest.register_globalstep((delta: number) => {

  timer += delta;
  if (timer > 1) {
    // Get the players.
    let playerIterator: ObjectRef[] = minetest.get_connected_players();
    // Restart the timer.
    timer = 0;
    // Flip the state.
    state = !state;
    // Change the head bone override.
    if (state) {
      print("tick");
      for (let player of playerIterator) {
        player.set_bone_override("Head", {
          rotation: {
            vec: start,
            // Literally does nothing.
            interpolation: 1.0,
            absolute: false,
          }
        });
      }
    } else {
      print("tock");
      for (let player of playerIterator) {
        player.set_bone_override("Head", {
          rotation: {
            vec: end,
            // Literally does nothing.
            interpolation: 1.0,
            absolute: false,
          }
        });
      }
    }
  }
});
```

**Comment by appgurueu** [comment]
Can confirm with

```lua
local timer = 0
local rot = math.pi/4
minetest.register_globalstep(function(dtime)
	timer = timer + dtime
	if timer > 1 then
		timer = 0
		rot = -rot
	end
	for _, player in pairs(minetest.get_connected_players()) do
		player:set_bone_override("Head", {rotation = {
			vec = vector.new(0, rot, 0),
			interpolation = 1.0,
			absolute = false,
		}})
	end
end)
```

in Minetest Game. This should smoothly turn the head to the left, then to the right, but instead it happens instantaneously.

**Comment by appgurueu** [comment]
Heh, it's a silly naming issue. The docs say `interpolation`, but the code implements `interpolate`. Fixed in https://github.com/minetest/minetest/commit/70bddcf318b5ffbe45916c09178d59edc4f08f2d.
