### ISSUE TITLE
Unknown texture when shiftclicking item into full crafting grid

### ISSUE THREAD

**Issue by Bastrabun** [minetest/minetest#14572]
### Minetest version

```true
Minetest 5.9.0-dev-eb432d3da (Linux)
Using LuaJIT 2.1.1713517273
Built by GCC 13.2
Running on Linux/6.6.15-amd64 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

edit: SDL (previous: Wayland. I thought that's the DM you want here)

### Operating system and version

Debian GNU/Linux trixie

### CPU model

Intel i7-6700 CPU @ 3.40GHz

### GPU model

Intel Corporation HD Graphics 530 (rev 06)

### Active renderer

Open GL 4.6.0

### Summary

When I have a full inventory grid and then try to shiftclick items into the full grid, I expect nothing happens, since I can't add the items to the grid anymore. Instead, the clicked items now show an unknown texture and the mouseover a "[]". When I drag such a wrong item or any non-wrong item to another inventory slot, the inv refreshes and shows the wrong items right again.

This works on Unified inventory and the MTG stock inventory, on my server and on MTG default with no mods. The CPU and GPU I mentioned are only one example, I can reproduce with all my machines here.

For my reference 6699

### Steps to reproduce

> client version 5.9.0-dev e12db0c18 or d767ab089 or eb432d3da
1. Place items in all 9 slots of the crafting grid
2. Place one or more items in the normal inv
3. shift-click the normal item in the inv
-> WRONG: item turns to unknown texture, cursor turns to []
-> EXPECTED: Nothing happens
4. switch an item to a different slot in that same inv
-> items return to their normal textures

**Comment by Bastrabun** [comment]
https://github.com/minetest/minetest/assets/59294479/5ed79491-1101-4608-950e-dec8439d11a4

**Comment by NathanSalapat** [comment]
Can reproduce with de1d8ec07

**Comment by blaboing** [comment]
Did some quick tests and happens since https://github.com/minetest/minetest/commit/61a57336920e0f64361a4c48215b12969c3a1eff
