### ISSUE TITLE
Texture won't load and everything is black

### ISSUE THREAD

**Issue by sonisaltiner** [minetest/minetest#14588]
Greetings. When I create a world, the textures don't load, I can break and get an item but everything remains black. I follow the steps to create a world but the same problem persists no matter what I do. When I want to access a server, I have a "Timeout" problem. 

Huawei MRD-LX1, Android 9, Armeabi-v7a

![Screenshot_20240425_012157_net minetest minetest](https://github.com/minetest/minetest_game/assets/132471102/89aad31e-4852-4728-9eb3-20f7634ba56a)
![Screenshot_20240425_012230_net minetest minetest](https://github.com/minetest/minetest_game/assets/132471102/28842e86-cae6-4ef1-9944-82aec14b542a)
![Screenshot_20240425_011939_net minetest minetest](https://github.com/minetest/minetest_game/assets/132471102/9665c89f-f360-4fcf-8b31-094184c139b6)
![Screenshot_20240425_012100_net minetest minetest](https://github.com/minetest/minetest_game/assets/132471102/83cdef47-1fc6-44c1-89e8-d0756427c2d0)

**Comment by grorp** [comment]
There's a good chance your problem is already fixed on 5.8.1 / 5.9.0-dev, see #13519. Could you please try with an APK from https://github.com/minetest/minetest/actions/runs/8822564917? (you first have to sign the APK and uninstall the old version)
