### ISSUE TITLE
[BUG] Pressing both "/" and "t" keys causes Minetest to be unresponsive

### ISSUE THREAD

**Issue by Monniasza** [minetest/minetest#14585]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Linux Mint

### CPU model

Intel© Core™ i5-7300HQ CPU @ 2.50GHz × 4

### GPU model

Nvidia GeForce 1050

### Active renderer

OpenGL 4.6.0

### Summary

When I press both T and a letter, the game becomes unresponsive and can only be quit by the close button or by Alt+F4, however the game does not crash.

### Steps to reproduce

Press both a T key and the / key at the same time

**Comment by TheEt1234** [comment]
i've managed to reproduce it

**Comment by HybridDog** [comment]
I can also reproduce this. I have changed the `fps_max` setting to 5 since I think this makes it is easier to reproduce it.
The mouse is no longer captured but the rendering still works, which can be tested by looking at a rotating dropped item or by resizing the window.

**Comment by Monniasza** [comment]
I've got this issue when I've stroked "TPHR", which outputs "/tphr". It can also be reproduced by using a macro which presses / and T at the same time.

**Comment by Montandalar** [comment]
Can confirm, pressing them at the exact same time will cause the Minetest window to accept no further user input; the game has to be killed through the operating system.

```
Minetest 5.9.0-dev-be540043e (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0-20-amd64 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

Operating system: Debian 12
Irrlicht Device: X11
Active renderer: OpenGL 4.6

**Comment by SmallJoker** [comment]
@Montandalar  Would you please be so nice to run Minetest (preferably with debug symbols) in gdb, reproduce the issue and press Ctrl+C in the terminal to generate an interrupt? Then get the backtrace of all threads: `thread apply all bt`. One of them should concern inputs.
