### ISSUE TITLE
Missing CURLPART_ZONEID on  building with an old version of CURL

### ISSUE THREAD

**Issue by olafmustafar** [minetest/minetest#14598]
### Minetest version

```true
master, on commit c63c05b
RUN_IN_PLACE=1
USE_CURL=1
```

### Irrlicht device

SDL

### Operating system and version

Debian Buster aarch64 (on qemu)

### Summary

If ENABLE_CURL is enabled, it looks for 7.28.0 version of  curl, as stated in CMakeLists.txt:50
but in src/util/colorize.cpp:59 it looks for CURLUPART_ZONEID that is only present in version 7.65.0 (can be verified on https://curl.se/libcurl/c/curl_url_get.html)

This make compiling with the libcurl version 7.28.0 not work. We may update the required version of libcurl, or make so colorize.cpp doensn't use the CURLUPART_ZONEID.

### Steps to reproduce

Compile minetest using a curl version older than 7.65.0 with ENABLE_CURL enabled

**Comment by SmallJoker** [comment]
Since 24cc33e704, #13825

**Comment by Zughy** [comment]
@rubenwardy (unsubscribing)
