### ISSUE TITLE
Minetest built with SDL conflicts with kwin_x11 compositing

### ISSUE THREAD

**Issue by zmv7** [minetest/minetest#14596]
### Minetest version

```true
Minetest 5.9.0-dev-c63c05b (Linux)
Using LuaJIT 2.1.1713773202
Built by GCC 13.2
Running on Linux/6.8.7-arch1-2 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Irrlicht device

SDL

### Operating system and version

Arch, Fedora 40, FreeBSD 14

### CPU model

AMD Ryzen 5 5600

### GPU model

RTX 4070 Super

### Active renderer

OpenGL 4.6

### Summary

Kwin's compositing turns off whenever minetest built with `USE_SDL2=1` is running. It doesnt happen on `USE_SDL2=0` builds. I reproduced it on Archlinux, Fedora 40(they're both with plasma6), FreeBSD 14 (*latest* repo branch, plasma5). Tried nouveau and proprietary nvidia drivers. Also reproduced in LXQt + kwin_x11.
Cannot reproduce in XFCE.

### Steps to reproduce

1. Get OS with Plasma desktop
2. Compile minetest with `USE_SDL2=1` flag
3. Launch minetest
4. Look for graphical issues in the desktop shell:
   * Wobbly windows, transparency, animations will not work
   * Windows above minetest will leave a trail when moving quickly
   * You can also try to launch `picom`, it should start successfully and will get killed by kwin once you close minetest window.

**Comment by rollerozxa** [comment]
Plasma/KWin automatically disables compositing if programs request it to reduce latency. You need to disable "Allow applications to block compositing" in the KWin compositor settings if you don't want it to do that.

**Comment by zmv7** [comment]
> Plasma/KWin automatically disables compositing on Xorg if programs request it to reduce latency, which SDL does. You need to disable "Allow applications to block compositing" in the KWin compositor settings if you don't want it to do that.

It works, however, shouldn't apps properly control it using SDL_SetHint? For example disable compositing in fullscreen mode only, etc?

**Comment by sfan5** [comment]
It appears SDL disables compositing by default: https://discourse.libsdl.org/t/why-is-compositing-disabled-on-normal-x11-windows/37712
We could add code to set the mentioned hint to tell SDL to keep it enabled, but the default behavior is not our fault.
