### ISSUE TITLE
Input text field blocks keyboard button from being pressed again

### ISSUE THREAD

**Issue by KometFox** [minetest/minetest#14593]
### Minetest version

```true
Minetest 5.8.0
```

### Irrlicht device

X11

### Operating system and version

Xubuntu 22.04

### CPU model

AMD Ryzen 7 5700x 8 Core

### GPU model

Nvidia RTX 3060 Ti

### Active renderer

OpenGL 4.6.0

### Summary

When a GUI menu has a field for inputting text it blocks other keys from being pressed, I am left handed and it is for me very inconvenient having to press the ESC button all the time because pressing other key binds which opens for example the inventory menu doesn't work anymore unless I use the mouse and click on somewhere else so that the input text field focus gets removed. 

### Steps to reproduce

1) Open any menu which whose first tab (if any) has a field for inputting text)
2) Try to close the menu with the same keyboard button press

**Comment by srifqi** [comment]
If a formspec has a text field, the text field will be focused automatically when being shown. Did you mean to make it not focused automatically?

**Comment by grorp** [comment]
KometFox: If you mean that the text field eats keypresses so that you can't close the formspec via <kbd>i</kbd> again, that's intended. How would you enter an "i" (or whatever inventory keybind you have) into a text field otherwise?

On the other hand, this could perhaps be considered a bug if it affected non-printable keys like the F-keys as well. Does it?

> If a formspec has a text field, the text field will be focused automatically when being shown. Did you mean to make it not focused automatically?

srifqi: That would be quite inconvenient compared to the current behavior.

**Comment by KometFox** [comment]
> KometFox: If you mean that the text field eats keypresses so that you can't close the formspec via i again, that's intended. How would you enter an "i" (or whatever inventory keybind you have) into a text field otherwise?

By mouse clicking on the text field manually so that it gets the focus, otherwise it shouldn't automatically have a focus so that I can press the "i" key to close the menu again. Having to constantly press ESC or mouse clicking somewhere else in order to get rid of the text focus all the time is for me not convenient at all.
