### ISSUE TITLE
What 3D modeller is recommended when making Minetest Mods models.

### ISSUE THREAD

**Issue by DrEpicGTM** [minetest/minetest#14595]
I've heard about Blender, but I want to know if there is something less complicated available and compatible with Minetest.
I am quite new to modding, but played Minetest since 2017

**Comment by SmallJoker** [comment]
Such questions (advice, recommendation or modding help in general) are best placed in the [forums](https://forum.minetest.net/) or [one of the chat platforms](https://www.minetest.net/get-involved/). GitHub is meant for reporting bugs, requesting features and proposing changes.

To answer your question: any editor that can export one of the following model formats is suited: (.obj is the Wavefront format)

https://github.com/minetest/minetest/blob/c63c05b141d994e801c82344499d86f5b67a2e3f/doc/lua_api.md?plain=1#L274

Examples: Blender, Bforartists (fork of Blender), Wings3D, Maya (proprietary), Houdini (proprietary) and possibly many more. Consult your favourite search engine for inspiration.
