### ISSUE TITLE
The move to SDL2 broke some keybinds under Linux/X11

### ISSUE THREAD

**Issue by Montandalar** [minetest/minetest#14590]
### Minetest version

```true
Minetest 5.9.0-dev-be540043e (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/6.1.0-20-amd64 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Debian 12

### CPU model

AMD Ryzen 5 7600

### Active renderer

OpenGL 4.6

### Summary

Moving to SDL2 seems to have introduced a regression where some keys can't be used as keybindings. The normal lettered keys and - work, but not ` (my usual bind for autoforward) or numpad +- (for range select - nor does + on the number row (uses Shift)) work).

I determined it was SDL2 by running git bisect on the main Minetest project, then the irrlichtmt project:
```
9a439a3646b26b1fceda3e5d70630b0bb4b48aca is the first bad commit (irrlichtMt)
699d1bf27c5cc28033fc8c17bf43d189f54e7b5e is the first bad commit (minetest)
```
The default CMake options broke this for me after these commits. However building the latest master with
```
cmake . -DUSE_SDL2=False
```
still works. Sorry if the issue with controls is already known about but I couldn't find it in the issues posted since 2021-01-17 when the switch was made the default.

### Steps to reproduce

I will assume a US keyboard layout.

  0. Bind ` to autoforward on a pre-breaking version such as 5.8.0.
  1. On a US keyboard layout Attempt to bind ` to autoforward or any other bind. The bind will not be applied properly. The existing autoforward bind will show "OEM 3" as the key.
  2. Try to use ` and note that it has stopped working since the upgrade.
  3. Try to use Numpad + and Numpad - to change the range. Not that neither works when they used to.
  4. Try to use the number row - + and =. Note that only - works as it used to, while + and = (Shift+) do nothing.

**Comment by sfan5** [comment]
probable duplicate #14545

**Comment by MirceaKitsune** [comment]
Partly related but I understand sdl3 is on its way: Maybe that fixes a few things once it's released and we can switch to it.

**Comment by Montandalar** [comment]
This does look like a duplicate of #1454. I will report findings to there.

**Comment by appgurueu** [comment]
Shouldn't we reopen #1454 (or this, assuming this is more narrow) then? Currently both issues are closed. Is the issue gone?

**Comment by Desour** [comment]
I'm pretty sure, #1454 was just a typo for #14545.
