### ISSUE TITLE
Footstep sound repeats on ladders (and rapidy in other situations)

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1460]
When you hold shift on a ladder - you reached the bottom - then it plays the "footstep" sound again and again.

Low priority

**Comment by paramat** [comment]
Footstep-farts happen in many situations.

**Comment by DS-Minetest** [comment]
i cant reproduce the original issue but the footstep sound of the node on which the ladder is placed is played very often if above this node is air and you climb down the ladder

**Comment by tobyplowy** [comment]
@SmallJoker This bug shuld really be fixed

**Comment by Fixer-007** [comment]
Now it repeats while pressing shift on the sea floor after https://github.com/minetest/minetest/commit/14aa990cdd682b00904c4a84968a6c0e3c31716d

**Comment by paramat** [comment]
Add #6356 
"If you have free_move enabled and keep pressing Shift (without moving), you can hear the footstep sound in loop. The sound should be heard only when you reach the floor."

**Comment by lupoDharkael** [comment]
I've discovered a new one:
![capture-19 06 56](https://user-images.githubusercontent.com/14951430/29997407-8fcf1df2-9012-11e7-88aa-33bac9dd3c03.png)
You can experience the sound loop with free_move activated if you move forward at at floor level as you can see in the image.

**Comment by paramat** [comment]
Don't you mean 'fast move'? 'free move' would allow you to pass through the nodes in front.

**Comment by jastevenson303** [comment]
I suspect a duplicate?  Nonetheless, rapidly repeating footstep sounds
happen easily in my experience, regardless of fast/fly mode.

One easy way to reproduce, I think is with liquid nodes.

**Comment by paramat** [comment]
Low priority but also, footstep sound is played twice as fast on fences. Folding #4310 into this.

**Comment by HybridDog** [comment]
I've noticed that no footsteps are played when walking on the ledge, especially noticeable when jumping onto the nodes. It may be intentional because when the foot touches the ledge it should make no sound or a completely different one than when it touches a planar floor.

**Comment by SmallJoker** [comment]
I did some research and found an explanation for this bug.
1) The sound is played here when there's a new Y collision:
https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/src/localplayer.cpp#L420-L421
2) The player controls are applied once before the client environment step:
https://github.com/minetest/minetest/blob/a43a4e2d97d52f0e5e6e62e472a577e434d892eb/src/client.cpp#L409-L412
3) `LocalPlayer::move` (which does the collisions) is called multiple times per environment step to prevent aliasing problems on thin collision boxes.
https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/src/clientenvironment.cpp#L200-L205
4) So it happens that the first `LocalPlayer::move` call detects ground (Y collision) when moving down, but all other in the same env step don't. In the next loop this repeats and the oscillating `touching_ground` value causes this sound fart.

Possible solution: Only set `touching_ground = false` (`localplayer.cpp`) after the steps when none of the `LocalPlayer::move` collision results returned a Y collision.

**Comment by random-geek** [comment]
@SmallJoker Just curiously, why are the results of `LocalPlayer::move()` inconsistent to begin with?

**Comment by LoneWolfHT** [comment]
Was about to make an issue but then I saw this :+1:

**Comment by GreenXenith** [comment]
I can no longer reproduce this (ladder/fence/corner repeated step sound) in latest master.

**Comment by SmallJoker** [comment]
Bug still persists in current master (4445889). Press sneak/shift here:
![grafik](https://user-images.githubusercontent.com/1497498/71634966-8d55af80-2c20-11ea-8874-d1f739fa5cf1.png)

**Comment by GreenXenith** [comment]
That is what I did, and cannot reproduce it.

**Comment by DS-Minetest** [comment]
I can still reproduce, too. @GreenXenith have you made sure that your sound volume is loud enough and that the node below has footstep sounds?

**Comment by GreenXenith** [comment]
Yes, in fact I used the exact node setup as SmallJoker just to be sure.

**Comment by paramat** [comment]
A very simple and zero-risk improvement is here https://github.com/minetest/minetest/pull/9891#issuecomment-630746018

See #9891 for further discussion and some alternative proposals.
