### ISSUE TITLE
Randomize mod load order

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14618]
### Problem

~~I'm evil and want to step on some toes.~~

Mods can not depend on stuff they need but get lucky and have it load first anyways. For example I recently saw a mod depending just on `default` but also needing `player_api`. This is, of course, brittle.

### Solutions

We can randomize mod load order while satisfying the dependencies to bring such issues to light earlier.

This should be very easy to implement. Our current algorithm is basically an iterative topological sort in disguise. Randomization can be done simply by picking a random mod among among the "satisfied" mods each step, rather than always picking the "first" one (where first is determined by sorting).

Note that hacks like giving mods special names (`_mcl_autogroup`) to have them load first or last should become obsolete with https://github.com/minetest/minetest/pull/14177.

### Alternatives

Do nothing ~~and let them get away with it~~

### Additional context

What is our broader policy on this kind of "strictness" (by deliberately randomizing things modders shouldn't be relying on as deterministic)?

**Comment by sfan5** [comment]
I support this as an option, maybe even on by default for debug builds.
