### ISSUE TITLE
Failed to copy symlinks when building for Android using Android Studio on Windows

### ISSUE THREAD

**Issue by srifqi** [minetest/minetest#14622]
### Minetest version

```true
Minetest 5.9.0-dev-1aba7f1fd
```

### Irrlicht device

(any)

### Operating system and version

Windows 10.0.19041

### CPU model

(any)

### GPU model

(any)

### Active renderer

(any)

### Summary

I was building Minetest for Android using Android Studio on Windows.

Here is the build output:
```
Build file 'C:\git\minetest\android\app\build.gradle' line: 77

Execution failed for task ':app:prepareAssets'.
> Could not copy file 'C:\git\minetest\irr\media\Shaders\OneTextureBlend.fsh' to 'C:\git\minetest\android\app\build\assets\client\shaders\Irrlicht\OneTextureBlend.fsh'.
   > Cannot create directory 'C:\git\minetest\android\app\build\assets\client\shaders\Irrlicht' as it already exists, but is not a directory
```

Deleting `client/shaders/Irrlicht` symlink fixes the issue.

### Steps to reproduce

Using Android Studio on Windows,

1. Make sure to run Clean Project before reproducing this issue.
2. Build Minetest by running Make Project.

**Comment by rollerozxa** [comment]
This shouldn't be an issue if you have developer mode enabled in Windows and `core.symlinks` enabled in Git, see: https://stackoverflow.com/a/59761201

**Comment by srifqi** [comment]
Running `git config core.symlinks true` (inside the repo folder) fixes the problem for me. I have already enabled Developer Mode since before this issue happened.

Thank you.
