### ISSUE TITLE
Confusing loading state in Battery Saver

### ISSUE THREAD

**Issue by graciouselectric** [minetest/minetest#14620]
Dear developers,

I noticed that when I enable Battery Saver on Android 8.1, the indeterminate `ProgressBar`s in the app are not properly shown. This is a known problem in Android API level <28, see e.g. [this StackOverflow question](https://stackoverflow.com/questions/35221706/progressbar-disappears-in-battery-saver-mode-android-5-x). Battery Saver disables animations, also on progress bars on these versions. This is quite confusing because the loading state is not properly represented. It is fixed in later Android versions, where progress bars do appear and animate.

Looking at the code, indeterminate progress bars are created here:

```
className='net.minetest.minetest.MainActivity', lineNumber=95
className='net.minetest.minetest.MainActivity', lineNumber=102
className='net.minetest.minetest.MainActivity$1', lineNumber=67
```

To fix this issue, one can check [ValueAnimator.areAnimatorsEnabled()](https://developer.android.com/reference/android/animation/ValueAnimator) and provide a different UI element, such as a text label, when animations are disabled.

**Comment by Zughy** [comment]
@SmallJoker since you can test with an Android 6, would please be so kind to confirm this bug?

**Comment by rubenwardy** [comment]
Also worth testing with "remove animations"

**Comment by SmallJoker** [comment]
I can test this issue but I'd like to know which progress bars I should have a look at. Should the startup one be affected? AFAIK that's the only progress bar in the game that is not drawn with Irrlicht functions.

**Comment by SmallJoker** [comment]
@Zughy I would like to fully understand the issue, thus requesting clarification by OP because the issue text does use the plural form:

> the indeterminate `ProgressBar`**s** in the app

**Comment by Zughy** [comment]
Last time OP had been active was in May, I feel like we'll never know

**Comment by rubenwardy** [comment]
* Power saving mode is usually from the notifications shade. Pull down from the top twice and tap "battery saver"
* Remove animations is Accessibility > Colour and motion > Remove animations

I can't reproduce this with either on Android 14. Also, the loading ProgressBar has awful contrast, hard to see at all
