### ISSUE TITLE
 Experiencing lag or performance issues when transitioning from the first screen to the main screen in the mobile version of Minetest can be frustrating. 

### ISSUE THREAD

**Issue by MadhavSapkota** [minetest/minetest#14629]
### Problem

[hvq12_Final_Report.pdf](https://github.com/minetest/minetest/files/15258793/hvq12_Final_Report.pdf)

### Solutions

.

### Alternatives

. 

### Additional context

.

**Comment by jordan4ibanez** [comment]
what in absolute tarnation

**Comment by rubenwardy** [comment]
Issue template exists for a reason

**Comment by appgurueu** [comment]
I'm afraid that your "report" is egregiously wrong. To name just a few issues:

* Full of (most likely LLM-generated) fluff, much of which is plain wrong.
* Minetest consists primarily of C++ and Lua, not Java and Lua. Java is merely used for a little glue code to talk to Android. Hence the Android Studio builtin profiler isn't of much use.
* The Java code you're optimizing is almost completely irrelevant to overall performance.
* You need to actually profile the running game. Of course most time will initially be spent registering nodes etc., but this only happens during load time.
* The graphical settings you give are largely already the defaults.
