### ISSUE TITLE
Android: Crash in fs::extractZipFile

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#14632]
### Minetest version

```true
5.8.0 and 5.8.1
```

### Operating system

Android

### Summary

According to the Play Console, this is the most common crash on Android at the moment:

SIGSEGV

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 4905 >>> net.minetest.minetest <<<

backtrace:
  #00  pc 0x00000000007d3e5c  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (fs::extractZipFile(irr::io::IFileSystem*, char const*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+332) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #01  pc 0x0000000000744a68  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (ModApiMainMenu::l_extract_zip(lua_State*)+420) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #02  pc 0x0000000000702bf0  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (script_exception_wrapper(lua_State*, int (*)(lua_State*))+28) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #03  pc 0x0000000000b98a50  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (lj_BC_FUNCCW+1032192) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #04  pc 0x0000000000b3fac8  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (lua_pcall+144) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #05  pc 0x000000000070926c  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (AsyncWorkerThread::run()+668) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #06  pc 0x000000000078ac98  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (Thread::threadProc(Thread*)+96) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #07  pc 0x000000000078af08  /data/app/~~I4BGia3rCIAs5LLt-G24cA==/net.minetest.minetest-eUKWrYqsu_8rsXkvdLXyHQ==/split_config.arm64_v8a.apk!libminetest.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct>>, void (*)(Thread*), Thread*>>(void*)+1032192) (BuildId: 2fef352b0b5dff2a59a454645e9b4f412b2397fd)
  #08  pc 0x0000000000102ea0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #09  pc 0x0000000000096c30  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
```

### Steps to reproduce

I don't know. The only usage of `l_extract_zip` is here:

https://github.com/minetest/minetest/blob/e0e1d0855d38701cfb8c4ff130e65db40b9a2d86/builtin/mainmenu/content/contentdb.lua#L56-L81

I've tested with insufficient free space, but that didn't crash. Instead, it failed gracefully with the "unsupported file type or broken archive" message.

**Comment by sfan5** [comment]
Can we get line numbers from the the backtrace?

**Comment by savilli** [comment]
Anyways, after a little reverse engineering, I can confidently say that it crashed here https://github.com/minetest/minetest/blob/e0e1d0855d38701cfb8c4ff130e65db40b9a2d86/src/filesys.cpp#L935 with an empty opened_zip.

**Comment by savilli** [comment]
On Android, we store archives from cdb in the app cache, and apparently, the system can remove files from it while the app is running. See https://developer.android.com/training/data-storage/app-specific:
`Caution: When the device is low on internal storage space, Android may delete these cache files to recover space. So check for the existence of your cache files before reading them.`

If it happens while we're downloading or right after that, we will try to unpack a non-existent file and crash.

**Comment by grorp** [comment]
> Anyways, after a little reverse engineering, I can confidently say that it crashed here

How did you find out? Anyway, this sounds plausible, thank you. I'll open a PR with a fix.

**Comment by sfan5** [comment]
> We can't because we don't save that kind of debug info. If we use FULL here https://github.com/minetest/minetest/blob/master/android/native/build.gradle#L39, it will be saved. But maybe the apk size will significantly increase.

The intended way is to upload debug symbols in a ZIP file separately into Google Play, which won't affect APK size.
Surely there's some supported way of doing this easily with the gradle cmake build workflow.

**Comment by grorp** [comment]
https://support.google.com/googleplay/android-developer/answer/9848633?hl=en

Reading this FAQ (section "Native: Generate a debug symbols file"), it looks like selecting "FULL" would be fine since the debug symbols aren't included in the APK.

**Comment by savilli** [comment]
> > Anyways, after a little reverse engineering, I can confidently say that it crashed here
> 
> How did you find out?

I disassembled `libminetest.so`, found the assembly instruction that caused the segfault and matched it with the specific source line.

> Reading this FAQ (section "Native: Generate a debug symbols file"), it looks like selecting "FULL" would be fine since the debug symbols aren't included in the APK.

That's nice. Let's enable it then.

**Comment by savilli** [comment]
Btw it's possible to avoid creating a temporally zip file entirely. We can unpack the content on the fly while downloading it from cdb. It would require significant rewriting tho.
