### ISSUE TITLE
Add shift-click and middle click interactions to [item image] buttons

### ISSUE THREAD

**Issue by bramaudi** [minetest/minetest#14640]
### Problem

Can't craft a stack of stairs in Stonecutter with shift click like in the Crafting table.

https://github.com/minetest/minetest/assets/14371119/789037ea-53e4-4d58-af52-4f3d5725e2ca

### Solutions

Allow shift-clicking like in crafting table to craft a stack of item in Stonecutter

### Alternatives

Alternatively add manual button to able bulk craft item

**Comment by SwissalpS** [comment]
Isn't this an issue with the mod? Maybe open an issue there.

**Comment by bramaudi** [comment]
> Isn't this an issue with the mod? Maybe open an issue there.

Already submit an issue in mod repo, the author said they have no control in this.

> The crafting/inventory mouse interactions is implemented in the engine and there is no way for Mineclonia to change it.

https://codeberg.org/mineclonia/mineclonia/issues/1392

**Comment by SmallJoker** [comment]
I assume you'd like to detect shift-clicked [item image] buttons. As of now, only simple clicks can be registered though formspec callbacks. `ObjectRef:get_player_control` is likely not updated in formspecs, thus that cannot be used as a workaround.

Please confirm whether that is the situation/problem that you're facing.

**Comment by SwissalpS** [comment]
4. Use standard inventory list

**Comment by v-rob** [comment]
Adding the functionality to item image buttons would be an abuse of the functionality of buttons: inventory lists exist for this exact purpose.  I believe @SmallJoker's solution is the correct thing for the mod author to do.
