### ISSUE TITLE
The water glitches out visually.

### ISSUE THREAD

**Issue by Wbjitscool** [minetest/minetest#14651]
### Minetest version

```true
Minetest 5.9.0-dev-e0e1d0855
```

### Operating system and version

Windows 11

### CPU model

11th gen Intel Core i9 11900KF

### GPU model

NVIDIA GeForce RTX 3080

### Active renderer

OpenGl 4.6.0

### Summary

the water the water glitches out visually for some reason but it doesn't happen with it off but I want it to be on because I find that having the liquid water being a full block high is too high

### Steps to reproduce

once you turn on the water waving nodes then you place a block above the water node the issue appears

**Comment by Zughy** [comment]
Probably, but we need a screenshot to determine it

**Comment by Wbjitscool** [comment]
![Uploading screenshot_20240514_114627.png…]()

**Comment by Wbjitscool** [comment]
the screenshot isn't working for some reason

**Comment by Wbjitscool** [comment]
okay
![screenshot_20240514_114627](https://github.com/minetest/minetest/assets/108570042/679bacac-1f0d-403d-8c45-4c0b2c5c9d2b)

**Comment by Zughy** [comment]
Duplicate of #3075, closing
