### ISSUE TITLE
Implementation of Compound Operators

### ISSUE THREAD

**Issue by TubberPupper** [minetest/minetest#14658]
### Problem

I'm surprised there's nothing like
```lua
+=
-=
*=
```
In Minetest like there is in Roblox

This would make something like
```lua
local num = 2
num = num + 2
```
into
```lua
local num = 2
num += 2
```
removing the need to jot down the name twice, so that if you had a long variable like
```lua
local long_variable_name_for_a_number = 1
long_variable_name_for_a_number += 1
```
would be as easy as that instead of the below
```lua
local long_variable_name_for_a_number = 1
long_variable_name_for_a_number = long_variable_name_for_a_number + 1
```

### Solutions

To implement the said system, a friend of mine sent me this github link that has it set up for luajit https://github.com/SnapperTT/lua-luajit-compound-operators

This'd involve setting it up on the C++ side, and I'm not sure how Roblox does it. This isn't (obviously ;p) normally provided in Lua and is an auxiliary feature.

### Alternatives

Currently the alternative is just to keep going with the regular
```lua
local num = 2
num = num + 2
```
The feature request would only really be like a "quality of life" improvement and isn't necessary by any means.

### Additional context

You can see it in action in Roblox Studio I guess. Roblox is like discount Microsoft but worse so I don't think any of y'all would wanna download it, and it also doesn't work on Linux last I heard so oof (they broke the Wine implementation that allowed you to).

**Comment by appgurueu** [comment]
I don't think we're currently interested in forking Lua / LuaJIT for such small quality of life improvements.

Also bear in mind that Lua is already a very niche language. If you now add more exotic patches like these compound operators, you will break what little Lua tooling there is (think for example luacheck or luals), unless it happens to have extensions for these patches.

Overall, I'd say this is definitely low priority, if not a "won't implement"; it seems likely to me that the downsides of straying from "stock" Lua far outweight the advantage of such a small QoL improvement.

**Comment by TubberPupper** [comment]
Fairrr
Would it actually harm potential Lua updates? I don't program in C++ and my idea of it is as good as a caveman understanding electricity - but is having a separate C++ file for interpretation not possible? ;o

Otherwise, judging by tags, I guess I should close this?

**Comment by sfan5** [comment]
I drafted a reply to this but deleted the text again. But since you're explicitly asking:
The only way to achieve this is by editing the LuaJIT source, which is what the repo you linked does. In many cases we don't even control which version of LuaJIT Minetest is built with, so that doesn't work.
The alternative is to import the LuaJIT source code into Minetest but then we have to regularly update it, take responsibility for potential problems (and Linux distributions will be angry at us).

**Comment by TubberPupper** [comment]
Ooooh :o 
Yeah that does sound awful to work with, nevermind

Thanks for the explanation ;o
