### ISSUE TITLE
Some kind of issue with symlinks (I think)

### ISSUE THREAD

**Issue by ThePython10110** [minetest/minetest#14674]
### Minetest version

```true
Tested with 5.7.0 and 5.9.0-dev-b230428
```

### Irrlicht device

WIN32

### Operating system and version

Windows 10

### CPU model

Intel Core i7-6700

### GPU model

Intel HD Graphics 530

### Active renderer

OpenGL 4.6.0

### Summary

I have Minetest 5.8.0 set up normally. I also have 5.7.0 and 5.9.0-dev-b230428 set up with symlinks to `minetest.conf`, `worlds`, `games`, and `mods` from the 5.8.0 instance. For some reason, my mod [Better Commands](https://github.com/thepython10110/better_commands) works perfectly in 5.8.0, but in the instances with symlinks, most of the commands don't get registered, as if the files that register them aren't being run. I tried this multiple times, with different (but still wrong) results every time.

### Steps to reproduce

1. Set up Minetest 5.8.0 normally.
2. Set up Minetest 5.7.0 or 5.9.0-dev-b230428 (probably applies to other versions as well), but delete `minetest.conf`, `worlds`, `games`, and `mods`.
3. Replaced the deleted files with symlinks to the 5.8.0 instance.
4. Start Minetest with Better Commands (doesn't matter what game).
5. Go to the `/help` menu. There are probably not very many commands listed under `better_commands`. There should be [quite a few](https://thepython10110.gitbook.io/better-commands/commands).

I haven't noticed issues with other mods, but I haven't really looked for them.

**Comment by Zughy** [comment]
I've tried and in general your mod doesn't load all the commands, not even in the stable version. It just loads a couple, randomly. Other mods don't feature such behaviour, so I'd say it's something in your mod rather than Minetest itself
