### ISSUE TITLE
Can't run 64-bit Minetest 5.9 on 64-bit Windows 10

### ISSUE THREAD

**Issue by ThePython10110** [minetest/minetest#14670]
### Minetest version

```true
Minetest 5.9.0-70bddcf (Windows)
Using LuaJIT 2.1.1706185428
Built by Clang 17.0
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"

Also Minetest-5.9.0-c63c05b
```

### Irrlicht device

WIN32

### Operating system and version

Windows 10

### CPU model

Intel Core i7-6700

### GPU model

Intel HD Graphics 530

### Active renderer

OpenGL 4.6.0

### Summary

Trying to run [sfan5's builds](https://minetest.kitsunemimi.pw/builds) of Minetest 5.9.0, I noticed that the 64-bit builds crashed immediately when trying to run them, but the 32-bit builds seemed to work fine (although loading blocks seems to take a *lot* longer than I'm used to). It gives error code -1073741819, if that helps.

I would build it myself if I could, but I can't seem to make that work either.

If it's just a problem with my computer... that's annoying, but not entirely unexpected.

### Steps to reproduce

1. Download and extract one of the two most recent 64-bit builds from [here](https://minetest.kitsunemimi.pw/builds). I haven't tested with any others, so they might also work.
2. Run it.
3. Instant crash.
4. Download the 32-bit build.
5. No crash, but laggy.

**Comment by ThePython10110** [comment]
I managed to build it myself, and that worked fine. I guess I'll close this now.

**Comment by sfan5** [comment]
My builds are very close to the official builds, so it's likely that this problem affects both.
Please try the "mingw64" one from [here](https://github.com/minetest/minetest/actions/runs/9100456587#artifacts).

**Comment by ThePython10110** [comment]
It doesn't work and give the same error code. When running in MINGW, it says "segmentation fault." I managed to build it with MSYS/Clang, and that worked fine for me.

**Comment by SmallJoker** [comment]
Would you please be so nice to provide a backtrace of the failing build by running it inside `gdb` or `lldb`? If those binaries are found in `%PATH%`, you could start Minetest as follows: `minetest.exe --debugger`. Otherwise `C:\path\to\gdb.exe --args minetest.exe`, `r`, `bt`.

**Comment by ThePython10110** [comment]
Weird. It actually runs fine when running it via GDB, but not when I just launch it.

**Comment by ThePython10110** [comment]
This may be a duplicate of #14665

**Comment by sfan5** [comment]
> It gives error code -1073741819, if that helps.

That's just `0xc0000005`, so a segfault.

> This may be a duplicate of https://github.com/minetest/minetest/issues/14665

Unlikely IMO, the other looks like a macOS-specific issue.

**Comment by ThePython10110** [comment]
> > This may be a duplicate of #14665
> 
> Unlikely IMO, the other looks like a macOS-specific issue.

Yeah, I only said that because it matched what I was seeing exactly.

**Comment by SmallJoker** [comment]
@ThePython10110 Would you please be so nice to use an older 5.9.0-dev build to see which is the first one to crash? At least that would help us to narrow down the range of commits since 5.8.0.

**Comment by waxtatect** [comment]
I can't reproduce the instant crash, tested current latest, minetest-5.9.0-36d236c-win64.7z, also 70bddcf and c63c05b in 64-bit with Windows 10. Only obvious thing i noted, minetest starts with touch screen enabled, yet my laptop has no touch screen... but that works normally anyway once manually disabled

**Comment by ThePython10110** [comment]
431444b works, but not 8cbd629.

**Comment by SmallJoker** [comment]
@ThePython10110 Thank you for narrowing it down. Unfortunately 94 commits area way too many to look through (including one to support OpenGL 3). This might be a prejudice - but seeing the combination of Intel HD + Windows makes me wonder whether your game would start properly when using the Mesa3D software render? https://fdossena.com/?p=mesa/index.frag <-- put the 64-bit DLL next to the Minetest executable to make use of it.

**Comment by ThePython10110** [comment]
I tried with and without `video_driver = opengl` in `minetest.conf`, but it didn't help.

**Comment by appgurueu** [comment]
You state

> Irrlicht device: WIN32

Have you tried using the SDL device instead?

**Comment by sfan5** [comment]
Considering my builds are identical to the CI builds (built with SDL) that's probably just incorrect.

**Comment by ThePython10110** [comment]
You're probably right; I guess I didn't bother to check whether it was different.

**Comment by ExeVirus** [comment]
Unable to replicate with AMD builtin GPU with win10 for any backend. Either your system-specifica or some combination with your Intel HD issue. 

Hate to ask: have you updated your drivers and OS?

**Comment by ThePython10110** [comment]
When this happened, I was definitely using the latest graphics drivers (unless they decided to downgrade themselves; there hasn't been a new version since 2022), and the latest version of Windows 10. But now I'm using Linux.

**Comment by ExeVirus** [comment]
Interesting, you are not having issues on the exact same hardware with
Linux and 64 bit Minetest builds?

**Comment by ThePython10110** [comment]
Nope, works fine... if it's just me, I guess it doesn't really matter.
