### ISSUE TITLE
Ability to customize, disable, modify, etc the ascii art that pops up in the terminal at server start

### ISSUE THREAD

**Issue by jordan4ibanez** [minetest/minetest#14706]
### Problem

I was looking for a way to customize the minetest logo ascii art as I literally see it every time I restart the server.

I found that there was no way to do this.

### Solutions

Maybe an ascii.txt file or something that when present in the game folder, overrides the hard coded art.

Or some kind of conf file option where you can disable it.

Possibly even both for either or situations.

### Alternatives

Another alternative could be, run a initialized.lua file that can REALLY customize the things that happen when the server first launches.

This could also in fact document more advanced things based on the current instance environment.

It could also randomly generate pixel art in random styles and then the date and colorize everything because that's fun and cool.

**Comment by rubenwardy** [comment]
I don't support this and feel like it would be a bad use of time and binary bytes. Let's not add more bloat to the engine. If the ASCII art is really a problem, it should just be removed
