### ISSUE TITLE
Hiding last segments of IP addresses in logs

### ISSUE THREAD

**Issue by Emojigit** [minetest/minetest#14713]
### Problem

Under some circumstances, IP addresses may be considered personal data under data protection laws such as the GDPR. Under those laws, server owners may be required to hide the last segments of IPs in their logs for proper data protection. However, with the current available options, this is not an easy task., this is not an easy task with the current available options

### Solutions

A boolean option can be added to the `minetest.conf` to control whether the last segments (for IPv4 that's 2, I am unfamiliar with IPv6) should be hidden in the logs. If set to hidden, IP addresses will be printed as `127.0.x.x` instead of `127.0.0.1`. Lua API call returns should be kept intact -the mod's responsible for properly handling IP addresses.

### Alternatives

One could set up a script to clean up existing logs... but that would be time-consuming. Why not do the stuff from its source?

**Comment by sfan5** [comment]
> Why? This is a one-liner with `sed`:

Now do IPv6 :)

**Comment by Emojigit** [comment]
Seems like that's not MT's job then... I will look for proper log rotation.
