### ISSUE TITLE
[Feature Request] API: Use a table as a value in metadata.

### ISSUE THREAD

**Issue by rautyrauty** [minetest/minetest#14712]
### Problem

I want to store a array of positions in metadata. I don't want to convert it to strings and then return it back.

### Solutions

 Please add the get_table and set_table functions.

### Alternatives

-

**Comment by sfan5** [comment]
Metadata storage is based on strings and this won't change soon. Even if table functions were implemented they would just internally perform some kind of serialization.
I think it's better to leave it up to modders in that situation with `minetest.serialize` or `minetest.write_json`.

**Comment by rautyrauty** [comment]
>Metadata storage is based on strings and this won't change soon. Even if table functions were implemented they would just internally perform some kind of serialization.

OK, at least I don't have to reinvent the wheel.

>I think it's better to leave it up to modders in that situation with minetest.serialize or minetest.write_json.

Oh, I didn't know about that. This is probably exactly what I need!
You can close this issue.

It would be nice to just do something like this:
```lua
function set_table(self, name, table)
    self:set_string(name,minetest.serialize(table))
end

function get_table(self, name)
    return minetest.deserialize(self:get_string(name))
end
```

**Comment by wsor4035** [comment]
(closing issue as the author has stated)
