### ISSUE TITLE
`fog_moon_tint` does not work

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#14719]
### Minetest version

```true
5.9.0-dev (abf353c178935df7b7149c1020a4ef67264e53cb)
```

### Irrlicht device

X11

### Operating system and version

GNU/Linux

### Active renderer

OpenGL 4.5

### Summary

The `fog_moon_tint` sky color setting does not work properly. For most colors, the sky fog is not tinted correctly. It seems that only when a color channel is at the max. value (0xFF), that color is activated. Any value lower than that deactivates the color entirely. For example, `"#0000FF"` gives the expected result but `"#0000FE` and any lower value won't tint the sky at all.

In contrast, `fog_sun_tint` works perfectly fine.

**I believe this bug is a regression**. Because if I remember correctly, the moon tint used to work correctly in previous version (but I don't remember which one).

### Steps to reproduce

Use DevTest, activate the `luacmd` mod and enter the following commands:

* `/time 19200` (so that sun/moon tint activates)
* `/lua me:set_sky({sky_color={fog_tint_type="custom", fog_moon_tint="#0000FF"}})`
* (look at the moon and sky)
* `/lua me:set_sky({sky_color={fog_tint_type="custom", fog_moon_tint="#0000FE"}})`
* (look at the moon and sky again)

The sky should turn blue when you look at the moon in both cases. But the sky only turns blue in the first case. In the second case, the sky is not tinted. Feel free to test other values as well.

Bonus:
I wrote a little (somewhat clunky) test mod called `skyedit` to make editing sky parameters faster with a `/skyedit` command: https://codeberg.org/Wuzzy/minetest_skyedit

**Comment by appgurueu** [comment]
Looks like a trivial issue: Integer division by `255` turns `255` into `1`, everything else into `0`. I've made a trivial PR to fix this.
