### ISSUE TITLE
Calling add_particlespawner from a entity's on_activate silently fails

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#1472]
`minetest.add_particlespawner` silently fails when called from a entity's `on_activate`, and presumably from all entity callbacks.  If the call is delayed until the next server step with `minetest.after(0)` it works as expected.

**Comment by rubenwardy** [comment]
is this still an issue?

**Comment by paramat** [comment]
Closing in 1 month if no confirmation.

**Comment by paramat** [comment]
Old issue, no response.
@ShadowNinja
