### ISSUE TITLE
Warning in DevTest: "Writing to mod directories is deprecated"

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#14721]
Apparently, writing to mod directories is now deprecated, but DevTest still does this. I know this because the following warning is triggered on startup:

```
Writing to mod directories is deprecated, as any changes will be overwritten when updating content. For data storage consider minetest.get_mod_data_path() or minetest.get_worldpath() instead. (./games/devtest/mods/testnodes/textures.lua:188)
Writing to mod directories is deprecated, as any changes will be overwritten when updating content. For data storage consider minetest.get_mod_data_path() or minetest.get_worldpath() instead. (./games/devtest/mods/testnodes/textures.lua:189)
```

DevTest needs to be updated to fix this deprecation warning.

Minetest version: 5.9.0-dev (abf353c178935df7b7149c1020a4ef67264e53cb).

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/abf353c178935df7b7149c1020a4ef67264e53cb/games/devtest/mods/testnodes/textures.lua#L184-L190
this "compatibility" code can just be deleted
