### ISSUE TITLE
`get_connected_players` wrongly returns empty list in `register_on_shutdown`

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14736]
### Minetest version

Reported by BluebirdGrey51 on IRC on version 5.9.0-dev-87232358d. I can also reproduce this.

### Summary

`get_connected_players` wrongly returns an empty list in `register_on_shutdown` - 5.8.0 returned a list containing the connected players, as it should. There isn't even a good way for modders to work around this since `register_on_leaveplayer` doesn't get run on shutdown. Hence, if modders want to do something with players on shutdown (in BluebirdGrey51's example, setting some metadata values), they need this to work.

### Steps to reproduce

```lua
minetest.register_on_shutdown(function()
	print("# connected players", #minetest.get_connected_players())
end)
```

On 5.8.0: Start singleplayer game. Exit to OS. Output on terminal: `# connected players	1`.

Now do the same on 5.9-dev. Output: `# connected players	0`.

**Comment by appgurueu** [comment]
Possible culprits (not tested yet): https://github.com/minetest/minetest/commit/e7dbd325d2e50e7bc3a509ec6a7eaeee1ec2ae8a and https://github.com/minetest/minetest/commit/32f68f35cf5eabd4223ef4901486d43bb806867e. @SmallJoker

**Comment by wsor4035** [comment]
related https://github.com/minetest/minetest/issues/14711

**Comment by sfan5** [comment]
Needless to say we should add some test code to devtest for these cases.

**Comment by SmallJoker** [comment]
Since ef0009ae, the disconnected players are now unloaded properly explicitly before `ServerEnvironment` destruction. Hence these objects no longer appeared in `get_connected_players` because they're - in fact - already disconnected at this point.

**Comment by Emojigit** [comment]
Perhaps we can reverse the execution order - `on_shutdown` first, then the destruction of players. Running any actions on an already-destructed `ObjectRef` seemed nonsense.

Or we can properly handle `on_leaveplayer` on server shutdown, and call the old behavior unexpected and undocumented. This *should* not break anything - mods still know players are leaving, and handle the event via the usual approach.

**Comment by appgurueu** [comment]
> This behaviour is not documented.

Indeed we should document it.

> Intuitively it would however indeed make sense to me to still have the player list available there - even if they're already gone.

It's not just intuition. It's pretty much a necessity if you want to do any player-related things on shutdown, such as persisting data to player meta, since `register_on_leaveplayer` doesn't run on shutdown.
