### ISSUE TITLE
No Instance of Constructor "ResolveError::ResolveError" Matches the Argument List

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest#14747]
### Minetest version

```true
Minetest-5.9.0-dev-08485f6-dirty
```

### Operating system and version

Windows 11 home version 23H2

### Summary

So, I was looking through minetest's source code, and I noticed this warning in vscode "no instance of constructor "ResolveError::ResolveError" matches the argument list" on line 147 in address.cpp. I have confirmed that this still appeares in the latest dev version of the minetest. This doesn't cause an issue with the game thought.

### Steps to reproduce

Should be pretty simple, just download minetest's latest dev version and open it in vscode and look in the place mentioned above.

**Comment by rollerozxa** [comment]
Your vscode is likely misconfigured, if the error were to exist then the engine would probably fail to even compile.

I'd recommend using the clangd extension for vscode if you aren't already and generate a compile_commands.json with `-DCMAKE_EXPORT_COMPILE_COMMANDS=1` that you point the extension to so it properly knows how to analyse each source file without throwing false positives.

**Comment by DustyBagel** [comment]
It seems that we are trying to pass a value with the type wchar when ResolveError is expecting a type of std::string. Is there a reason why this isn't an issue?

**Comment by appgurueu** [comment]
Definition of `ResolveError` in `networkexceptions.h`:

```c++
class ResolveError : public BaseException
{
public:
	ResolveError(const std::string &s) : BaseException(s) {}
};
```

Usage in line 147: `throw ResolveError(gai_strerror(e));`

This performs implicit conversions. `gai_strerror(e)` is of type `const  char*` (perhaps `const wchar_t*` depending on the platform?), which can be converted to a `std::string`. This is perfectly valid. This is not of type `wchar_t`; the function is called *str*error for a reason.

With clangd properly configured in Visual Studio Code, I do not get a warning or error here. Everything compiles fine (look at CI). No bug here. This is a configuration issue.
