### ISSUE TITLE
[doc/compiling/linux.md] Instructions for Void are lacking & incorrect

### ISSUE THREAD

**Issue by rudzik8** [minetest/minetest#14746]
### Minetest version

```true
Minetest 5.8.0
(although the docs come from `master` as I'm browsing them through the web interface)
```

### Operating system and version

Void Linux

### Summary

1. The `zstd` package is also required to build Minetest, but is omitted from the dependency install command. The only one included there is `zstd-devel`.
2. Apparently, the [`make`](https://github.com/void-linux/void-packages/tree/master/srcpkgs/make) package for Void doesn't make a link from `/usr/bin/gmake` to `/usr/bin/make` (with the latter being the actual gmake), which leads to CMake erroring out at the "simple test program" step. However, I'm not sure about this. Entering `sudo ln -s /usr/bin/make /usr/bin/gmake` did help though.

Both lead to the compiling process failing at CMake, in reverse order.

### Steps to reproduce

Try compiling Minetest from Void Linux using the instructions from the documentation.

**Comment by SmallJoker** [comment]
Would you please be so nice to propose your changes in a PR? At least point "1." does make sense. "2." is an issue for the CMake or Void bug tracker. Build tools searching is CMake's task.

**Comment by rudzik8** [comment]
> "2." is an issue for the CMake or Void bug tracker. Build tools searching is CMake's task.

I'm not sure which one it is for?

Void would fix it faster though, that goes without saying.

**Comment by SmallJoker** [comment]
> I'm not sure which one it is for?

Going by your description of the symlink situation, I'd try Void first. 
Now that the other problem is fixed, I assume this issue no longer has relevance for Minetest.
