### ISSUE TITLE
math.round returns 1 for 0.49999999999999994

### ISSUE THREAD

**Issue by kromka-chleba** [minetest/minetest#14755]
## Problem

As pointed out below the most popular answer on stackoverflow, Minetest's implementation of math.round suffers from a bug: https://stackoverflow.com/questions/18313171/lua-rounding-numbers-and-then-truncate

```
> math.round(0.49999999999999994)
1
```

## Solution

I rewrote math random this way:

```
function math.round(x)
    local int, frac = math.modf(x)
    if x >= 0 then
        if frac >= 0.5 then
            return int + 1
        else
            return int
        end
    else
        if frac <= -0.5 then
            return int - 1
        else
            return int
        end
    end
end
```

### Old:

```
> math.round(0.49999999999999994)
1
> math.round(-0.49999999999999994)
-1
> math.round(0)
0
> math.round(10.3)
10
> math.round(10.5)
11
> math.round(-10.3)
-10
> math.round(-10.5)
-11
```

### New:

```
> math.round(0.49999999999999994)
0
> math.round(-0.49999999999999994)
0
> math.round(0)
0
> math.round(10.3)
10
> math.round(10.5)
11
> math.round(-10.3)
-10
> math.round(-10.5)
-11
```

### Steps to reproduce

Do this:

```
> math.round(0.49999999999999994)
1
```

**Comment by kromka-chleba** [comment]
I guess I can make the function shorter a little:

```
function math.round(x)
    local int, frac = math.modf(x)
    if x >= 0 and frac >= 0.5 then
        return int + 1
    elseif frac <= -0.5 then
        return int - 1
    end
    return int
end
```

**Comment by kromka-chleba** [comment]
@SmallJoker, that's not an upstream issue.
Lua doesn't provide math.round, Minetest does.
See `builtin/common/misc_helpers.lua`

**Comment by SmallJoker** [comment]
It appears this is in fact a Minetest issue: https://github.com/minetest/minetest/blob/master/builtin/common/misc_helpers.lua#L244-L249

**Comment by appgurueu** [comment]
> I guess I can make the function shorter a little [...]

`x >= 0` should be unnecessary, just `frac >= 0.5` should suffice, no? I'd also probably use just early returns, no need for the `elseif` there.

This could even be written as a single line with `and` and `or`, but I don't think that is worthwhile.

It might be interesting to see how the performance compares (and whether there is anyone relying on rounding being particularly fast to begin with).

**Comment by kromka-chleba** [comment]
Made a PR that fixes it.

**Comment by The4codeblocks** [comment]
this..... is painful
the number written in scientific notation for base 2 is practically 1.1111111111111111111111111111111111111111111111111111*10^-2
or in straight base 2
0.011111111111111111111111111111111111111111111111111111
IT'S PAINFUL
ROUND CAN BE IMPLEMENTED WITHIN PROCESSOR ARCHITECTURE (or its emulate) VERY EASILY, BUT THEY CHOSE NOT TO.
just a floor and a shift and an add.
# E
