### ISSUE TITLE
--gameid not set on docker

### ISSUE THREAD

**Issue by anliben** [minetest/minetest#14768]
### Minetest version

```true
Minetest 5.9.0-dev-fe6da3a16-dirty (Linux)
Using LuaJIT 2.1.1716656478
Built by GCC 14.1
Running on Linux/6.9.5-arch1-1 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Arch Linux x86_64 

### CPU model

Intel i7-10510U (8) @ 4.900GHz 

### GPU model

Intel CometLake-U GT2 [UHD Graphics]

### Summary

![image](https://github.com/minetest/minetest/assets/45929971/b3fac1ee-98e3-4994-84cb-339a7aac4ae6)

### Steps to reproduce

1 - Fork in other repository
2 - Upload git repository forked in Back3App or run docker build . minetest
3 - Wait for Back4App run docker image or run manually typing in terminal docker run -it minetest

**Comment by appgurueu** [comment]
From what I can see so far: Whatever you're using to invoke Minetest ("back3app"? "back4app"?) is just passing a wrong command line: Looking at your screenshot, apparently running something like `minetestserver --config /etc/minetest/minetest.conf`. Minetest is just appropriately complaining about you not telling it which game to run.

**Comment by sfan5** [comment]
That's a misunderstanding, the command line comes from our Dockerfile:
https://github.com/minetest/minetest/blob/9ab447843be1580e2296db5d27daaf01ab0c0512/Dockerfile#L81-L82

Our documentation on this is lacking but I think to successfully use the docker image it should suffice if you bind mount a game to the right location in `/var/lib/minetest/.minetest/games/`, for example:
`-v /real/path/to/minetest_game:/var/lib/minetest/.minetest/games/minetest_game`

**Comment by anliben** [comment]
I solved the problem by assigning a path to the volume, as it is apparently mandatory. Appreciate it
