### ISSUE TITLE
Camera angle messed up

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#14766]
### Minetest version

```true
Minetest 5.8.0
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

X11

### Operating system and version

Debian Bookworm

### CPU model

Cortex-A76

### GPU model

VideoCore VII

### Active renderer

OpenGL 3.1.0

### Summary

I can't really describe it, but the camera just doesn't rotate the way it should, it's super weird.
Video: https://github.com/minetest/minetest/assets/20720267/80dac1ee-9bc1-4196-86ec-cd116212ab54

### Steps to reproduce

1. Download a fresh build from minetest.net
2. Start the minetest bin
3. Download minetest game
4. Create a new world
5. Teleport to 0 0 0
6. Try to look around

**Comment by niansa** [comment]
Third person view is even worse: 

https://github.com/minetest/minetest/assets/20720267/d4eff15e-74a3-45e1-9dfb-3000d95d0e81

**Comment by SmallJoker** [comment]
Does it work correctly if you use software rendering? e.g. with `LIBGL_ALWAYS_SOFTWARE=1 minetest` (CPU usage must increase noticeably).

**Comment by niansa** [comment]
Software rendering doeen't make a difference here.

It's really hard to tell what direction the camera moves, really because as soon as I start walking the whole camera starts wanking around like crazy.

Also, I've noticed the items in the inventory are upside-down:
![2024-06-21-13-52-34-547](https://github.com/minetest/minetest/assets/20720267/318e3439-e368-4464-8a2b-4292d651227c)

Additionally, the sound effects all sound really distorted.

**Comment by niansa** [comment]
Here's a picture of the same system running Portal just fine: 
![2024-06-21-13-55-34-595](https://github.com/minetest/minetest/assets/20720267/6588532a-8361-4b69-9de6-5fcc1d4a4e96)

**Comment by Desour** [comment]
Looks like some numbers are swapped for some reason.

What is the output if you run `minetest --run-unittests`?

**Comment by sfan5** [comment]
Please try Minetest 5.9.0-dev and also the `ogles2` or `opengl3` video drivers, which are more modern and the former more appropriate for your hardware.

**Comment by niansa** [comment]
> What is the output if you run `minetest --run-unittests`?

[message.txt](https://github.com/user-attachments/files/15932645/message.txt)

At the end, it just seems to hang until I interrupt it.

**Comment by niansa** [comment]
> Please try Minetest 5.9.0-dev and also the `ogles2` or `opengl3` video drivers, which are more modern and the former more appropriate for your hardware.

Weirdly enough I am not able to replicate this issue *at all* when compiling Minetest myself, even when compiling 5.8.0

**Comment by sfan5** [comment]
Let's put this down to your distributions having a messed up build of Minetest.

**Comment by niansa** [comment]
> Let's put this down to your distributions having a messed up build of Minetest.

Thing is, this is an official build from minetest.net.. not from Debian itself

**Comment by sfan5** [comment]
The only official build minetest.net has is for win32.

**Comment by niansa** [comment]
> The only official build minetest.net has is for win32.

Is the PPA not official?

**Comment by sfan5** [comment]
Well I forgot about that. But PPAs are only for Ubuntu and I don't think we even have an aarch64 package in it.

**Comment by niansa** [comment]
I think I know what might be going on: I admit I manually downloaded and install the .deb from the PPA. But I *do not* think that's the problem here. I didn't make sure to actually install an aarch64 package, and I had previously tinkered with the system to get Steam to install which iIrc involved installing an *amd64 emulation layer.* That's probably why apt installed the package without a complaint and why I didn't notice it was the wrong architecture.<br>I suspect that emulation layer has some kind of bug leading to that behavior.

I would say user error? It would certainly explain it. Sorry for bothering you then.

**Comment by sfan5** [comment]
Yeah I'd consider that user error.
