### ISSUE TITLE
Backface culling of entities is inverted with .x models

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#1478]
![http://i.imgur.com/pUes2yN.png](http://i.imgur.com/pUes2yN.png)

**Comment by RobertZenz** [comment]
Is this really still happening?

**Comment by ShadowNinja** [comment]
@RobertZenz: Yep, as of 106d4b7d05cfbba901abd540113991042d77bc97 this is still an issue.

**Comment by RobertZenz** [comment]
Is the model available for testing?

**Comment by paramat** [comment]
@sofar ?

**Comment by sofar** [comment]
o_O

Seems unrelated to the recent issue introduced by me, however, it's quite similar so I'll take a look into this.

**Comment by sofar** [comment]
what mod is the model from?

**Comment by ShadowNinja** [comment]
@sofar: This one: https://github.com/ShadowNinja/nuke
Get a missile launcher (`nuke:missile_launcher`) and a missile (`nuke:missile`), and place the missile in the launcher.

**Comment by sofar** [comment]
Any idea when this last worked?

The model looks OK in blender, but that doesn't mean much from my experience.

**Comment by sofar** [comment]
```
diff --git a/missiles.lua b/missiles.lua
index 243cd20..cae0f36 100644
--- a/missiles.lua
+++ b/missiles.lua
@@ -55,6 +55,7 @@ minetest.register_entity("nuke:missile", {
        visual_size = {x=3, y=3, z=3},
        phisical = true,
        collisionbox = {-0.5, -0.5, -0.5, 0.5, 4, 0.5},
+       backface_culling = false,
        state = 0,
        --origin = vector.new(),
        on_activate = function(self, static_data)
```

this makes the model appear normally.

The only reason that I can think of right now is that there's an issue with reading the format of the model, or the model itself has mis-ordered vertices (we don't sort them in the game).

**Comment by kaeza** [comment]
I've had that problem before using `.x` models after upgrading Blender. Exporting to other formats solved this for me. Not sure if issue with Irrlicht, Blender DirectX exporter, or PEBKAC, but no set of options seem to work for me.

**Comment by sofar** [comment]
@ShadowNinja I ended up converting this to .obj and flipping the UV map, after which it's displayed properly in the game. I'm not sure where the bug is. The model looks OK in blender, but it's not in the right position, and UV maps are definitely disturbed. Sent you a pull request for the mod change.

If there are more problems with .x meshes, maybe we can dig a bit deeper, but converting to obj is trivial enough.

**Comment by ShadowNinja** [comment]
This is probably an upstream issue with either Blender (writing .x coordinates out backwards?) or Irrlicht (failing to sort vertecies properly?).

**Comment by sofar** [comment]
When I was working on the precursor to ```NDT_CONNECTED``` I noticed that irrlicht or minetest indeed do not sort vertices, and the same visuals occur. So yes, it looks like the .x file needs sorting, unfortunately. Given that the .x export function isn't a permanent part of blender, I don't trust it much.
