### ISSUE TITLE
How can I get player facing dir?

### ISSUE THREAD

**Issue by Mahoyomu** [minetest/minetest#14803]
### Problem

Same as the title said, but not `l_get_look_dir`, I need to modify .cpp and there's no LuaState, I need C++ method

### Solutions

Give me a C++ method in the src, which can give me player facing dir in vector3d

### Alternatives

Tell me there's no such a method and I need to figure it out by myself

### Additional context

I've read the src and searching for a very long time, but I can't make sure I didn't miss anything. If someone knows the method to get player facing dir, please tell me

**Comment by cx384** [comment]
Just do what `l_get_look_dir` does?
Like this:
``` cpp
RemotePlayer *player = env->getPlayer(name);
PlayerSAO *sao = player->getPlayerSAO();
float pitch = sao->getRadLookPitchDep();
float yaw = sao->getRadYawDep();
v3f v(std::cos(pitch) * std::cos(yaw), std::sin(pitch), std::cos(pitch) * std::sin(yaw));
```

**Comment by Zughy** [comment]
Please ask these questions in our community spaces like IRC, Matrix or Discord. Closing
