### ISSUE TITLE
Under some Android systems, the interface will turn black after entering the game.

### ISSUE THREAD

**Issue by jintianyehenkaixinna** [minetest/minetest#14805]
Under some Android systems, the interface will turn black after entering the game.
![Screenshot_20240702_042447](https://github.com/minetest/minetest_game/assets/149940987/1b3100e5-9d49-4929-a66b-55aeb5151990)

**Comment by wsor4035** [comment]
pretty sure this is just the spawning underground without noclip issue. grant yourself noclip/fly and fly out or teleport to something like 0,15,0

**Comment by grorp** [comment]
duplicate: #13519

**Comment by rubenwardy** [comment]
This will be fixed in 5.9.0
