### ISSUE TITLE
Is CMake reconfiguration needed when testing minetest src change?

### ISSUE THREAD

**Issue by Mahoyomu** [minetest/minetest#14816]
### Problem

Same as the title said.
CMake binaries folder is over 3GB and if every time I change src a new folder is needed, it's gonna crush my disk space. So I wanna know if it's necessary to create new folder each time I modified different src file. If not, when should I create a new folder?

### Solutions

Let me know about this.

### Alternatives

No, this is crucial to my testing and very important for me. So please help if you know.

**Comment by Desour** [comment]
You make me feel sad.
If you change something in src, you just have to rebuild using `cmake --build . -j <n>` (`make -j <n>` also works if you're using `make`). A new build directory is not needed.
(In case you're worried about long build times when you switch branches, try using ccache.)
I hope this answers your question.

Btw. regarding <https://github.com/minetest/minetest/issues/14803#issuecomment-2209062646>:
* Discord is evil and not to be recommended to anyone.
* Another place where you can ask engine development questions is the forums, e.g. at <https://forum.minetest.net/viewforum.php?f=6> or <https://forum.minetest.net/viewforum.php?f=7>.
