### ISSUE TITLE
Full screen setting doesn't work

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#14826]
### Minetest version

```true
Minetest 5.8.0 (Linux)
Using Irrlicht 1.9.0mt13
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/app/share/minetest"
STATIC_LOCALEDIR="/app/share/locale"
```

### Irrlicht device

X11

### Operating system and version

Fedora 40

### CPU model

AMD Ryzen™ 3 1200 × 4

### GPU model

NVIDIA GeForce GT 1030

### Active renderer

OpenGL 4.6.0

### Summary

"Full screen" option does nothing on my system.

### Steps to reproduce

In the screen settings, check "Full screen", restart Minetest.

**Comment by SwissalpS** [comment]
Fullscreen has been working fine for me after https://github.com/minetest/minetest/commit/bc23a610d350dfe81594959f5b238eed4bde0f95

**Comment by wsor4035** [comment]
please try with latest dev, as stated above this has been fixed
