### ISSUE TITLE
Allow main menu gamebar scroll to loop

### ISSUE THREAD

**Issue by Kazooo100** [minetest/minetest#14835]
### Problem

If you click the left arrow on the first page or click the right arrow on the last page of the gamebar it does nothing. 

### Solutions

Clicking the left button should loop around to last page of installed games and clicking the right button on the last page should loop to first page. This would also improve speed of reaching game you wish to run.

### Alternatives

Removing the left scroll button on first page and right scroll button on the last page of the gamebar would prevent people clicking it.

**Comment by SwissalpS** [comment]
I like the alternative suggestion of removing arrows.
Though I do ponder if you got left and right mixed up. Shouldn't it be "remove right button on last page and left button on first page"?

**Comment by Kazooo100** [comment]
> Though I do ponder if you got left and right mixed up. Shouldn't it be "remove right button on last page and left button on first page"?

Yes sorry, I will correct that!


> I think it's functionally better to have the direct solution of loop around to last page of installed games rather than the alternative option, also more user friendly. IMHO, that's gonna cost a lot more clicks in the long run if someone is testing with one of those games, or just wanna delete or check if one specified game exists.

Me and my dad always rage at non looping menus, so definitely agree.

**Comment by rubenwardy** [comment]
I think a looping menu matches user expectations better, so doing support that

**Comment by SwissalpS** [comment]
Looping is fine by me too. My preference for removing the arrows is only marginal.

**Comment by Kazooo100** [comment]
I managed to make it work by changing builtin/fstk/buttonbar.lua. Should I make a PR or does it need more approvals? 

`	if fields[self.btn_prev_name] and self.cur_page > 1 then
		self.cur_page = self.cur_page - 1
		return true
	elseif fields[self.btn_prev_name] and self.cur_page == 1 then
		self.cur_page = self.num_pages
		return true
	end

	if fields[self.btn_next_name] and self.cur_page < self.num_pages then
		self.cur_page = self.cur_page + 1
		return true
	elseif fields[self.btn_next_name] and self.cur_page == self.num_pages then
		self.cur_page = 1
		return true
	end`

**Comment by SwissalpS** [comment]
Other arrows sounds like overenginering this simple change.

**Comment by Kazooo100** [comment]
Closed with https://github.com/minetest/minetest/pull/14841
