### ISSUE TITLE
Add option to disable "smooth scrolling"

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#14848]
### Problem

Apparently scrollable areas scroll smoothly now (as of Minetest 5.9.0-dev). The problem is that I **HATE** this feature with a deep passion. It is irritating me so much the scrolling doesn't occur instantly anymore.

Whenever I see any software doing this, the first thing I do is look for ways to disable it. Yes, it's that bad. Sadly, Minetest doesn't seem to have a setting (search yields nothing).

### Solutions

Add a setting to disable smooth scrolling.

### Alternatives

Remove smooth scrolling entirely.

**Comment by grorp** [comment]
I'm fine with a setting as long as it's enabled by default
