### ISSUE TITLE
Make Android strings translatable on Weblate

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#14844]
We should improve our Weblate setup to make these strings translatable: https://github.com/minetest/minetest/blob/master/android/app/src/main/res/values/strings.xml

Weblate supports Android string resources: https://docs.weblate.org/en/latest/formats/android.html

I think doing this requires creating a new Weblate component, which I can't do ("You do not have permission to create components in any projects.")

Anyone who would like to do this?

### Alternatives

We could write some scripts to convert our Android strings to PO and back, so that they could be included in the main Minetest component.

**Comment by srifqi** [comment]
Who has the privileges to create new components?

List of project maintainers [(from the info page)](https://hosted.weblate.org/projects/minetest/#information): @​celeron55, @​sfan5, shadowninja (@​ShadowNinja), @​nerzhul, @​rubenwardy, Krock (@​SmallJoker), @​Warr1024, and @​grorp

**Comment by grorp** [comment]
The error message "You do not have permission to create components in any projects." I was seeing previously is gone. I set up a new translation component for Android strings now: https://hosted.weblate.org/projects/minetest/minetest-android/

It shares the Weblate Git repo with https://hosted.weblate.org/projects/minetest/minetest/, so the [translation update process](https://dev.minetest.net/Translation#How_to_merge_translations_from_Hosted_Weblate) shouldn't need changes.

**Comment by grorp** [comment]
Breaking news:

An Android string translated via Weblate
![screenshot](https://github.com/user-attachments/assets/7809cc3e-3553-455a-b13c-939f9b53d430)
