### ISSUE TITLE
Android: Update to SDK 34 by August 31

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#14855]
Google Play will require a target SDK of 34 to release new updates.

Minetest currently has a target SDK of 33

https://developer.android.com/google/play/requirements/target-sdk

**Comment by sfan5** [comment]
Here's the list: https://developer.android.com/about/versions/14/behavior-changes-14

pending intent and service stuff might affect `UnzipService` but I don't see anything else

**Comment by rubenwardy** [comment]
As long as we release 5.9.0 before 31st August this isn't required (although, Google will send us nagging emails until we do it). It may be required to release 5.9.1
