### ISSUE TITLE
`PLAYER_HP_MAX_DEFAULT` and `PLAYER_MAX_BREATH_DEFAULT` values are not specified anywhere

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#14880]
I was looking for the default value of `PLAYER_HP_MAX_DEFAULT` but this is the only mention in the API  

![image](https://github.com/user-attachments/assets/18b70556-172c-4af6-9921-dcfe957c73bc)  

Same for the other value

**Comment by sfan5** [comment]
<pre>
builtin/game/constants.lua
25:core.PLAYER_MAX_HP_DEFAULT = 20
27:core.PLAYER_MAX_BREATH_DEFAULT = 10
</pre>

they're defined in the api, would you like that copied into the docs?

**Comment by Zughy** [comment]
@sfan5 exactly

**Comment by BoySanic** [comment]
I'm intending to make a quick PR to add the current definitions to the documentation, but I have a larger concern that should we get in the habit of defining the constants in both places, it could be problematic if we change the constants but don't also change the APIs.

Minor concern, really, but longer term it'd be nice if we had documentation that updated based on the current state of the API. Maybe something like a website for api documentation, and it pulls from the variables we specify in the API to get the current values from the master branch?

**Comment by Zughy** [comment]
@BoySanic once it's documented, I'm pretty sure we won't let people get away with PRs that only change one of the two things - docs and code :P please do open a PR!

**Comment by grorp** [comment]
> it could be problematic if we change the constants but don't also change the APIs

We'll never be able to change these values anyway because backwards compatibility :P
