### ISSUE TITLE
Attached sounds don't resume playing when objects come back into range

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14886]
Opening an issue as requested in https://github.com/minetest/minetest/pull/14342#issuecomment-2243496803.

#14341 stopped attached sounds as soon as the entities disappeared from the client, either by being removed or by going out of range.

The former introduced a backwards compat breakage related to death sounds, which was addressed in #14436.

The latter trades one bug for another: Now, if an entity goes out of range, the sound will disappear, but if it comes back into range, the sound won't reappear.

Think a police car or ambulance with a siren (looped sound). When it goes out of range, the sound completely disappears, as it should, *but* the sound also stays off when it comes back into range (no matter how close).

The plan was to address the new bug in #14342 by introducing more elaborate server-side attached sound tracking, but that unfortunately turned out to be trickier than anticipated and thus won't make it into 5.9.0.

Thus my suggestion for 5.9.0 so far would be to revert #14436 and #14341, trying again in 5.10.0. Thoughts?

---

(ps. the current attached sound API should technically allow modders to work around both bugs and implement correct behavior by managing sounds entirely themselves, but that is rather cumbersome and should not be expected of them)

**Comment by sfan5** [comment]
> Thus my suggestion for 5.9.0 so far would be to revert #14436 and #14341, trying again in 5.10.0. Thoughts?

:+1:

**Comment by SmallJoker** [comment]
FYI: I am currently writing a PR. With the cleanup commits in between, this turned out to be less trivial.
