### ISSUE TITLE
Computer freezes when starting world 

### ISSUE THREAD

**Issue by LWFlouisa** [minetest/minetest#14898]
### Minetest version

```true
Minetest 5.8.0 Linux Versuion
```

### Operating system and version

Linux Mint 21.2

### CPU model

Not sure

### GPU model

Not sure

### Summary

I'm not sure what the CPU or Renderer is, but every time I boot up a world with a specific mod I use, the entire operating system freezes, and I can't even exit. I often have to do a hard restart of my machine.

### Steps to reproduce

(1. Boot up 5.8.0
(2. Load up a mod of your choosing
(3. Once you start, after about 15 seconds, rendering lag should freeze OS.

**Comment by qwerty123a2** [comment]
cat /proc/cpuinfo  | grep 'name'| uniq to get the cpu name
not sure about the gpu. What mod is it?

**Comment by SmallJoker** [comment]
Please provide more details about your hardware and drivers that you're using. Generally, applications in userspace cannot crash your system. Hence this might be a driver or hardware issue - unless there's a memory allocation bug in Minetest (unreasonably high RAM usage).

Check your syslog/dmesg for driver logs or errors in general.

**Comment by kromka-chleba** [comment]
This can happen when your GPU or CPU starts dying.
Especially if your GPU is old and you see artifacts on your screen (odd colors, strange triangles).
Had something like that last year on my 7 yo GPU.
