### ISSUE TITLE
Settings: enabling flags does not work

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14893]
### Minetest version

```true
Minetest 5.9.0-dev-7625f88a0 (Linux)
Using LuaJIT 2.1.1720049189
Built by GCC 14.1
Running on Linux/6.10.1 x86_64
BUILD_TYPE=RelWithDebInfo
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Summary

Enabling flags defined by the game's settingtypes.txt doesn't work at all.
Disabling them does (?!).

### Steps to reproduce

1. install [Minetest Classic](https://github.com/sfan5/minetest_classic)
2. go to Settings > "Minetest Classic"
3. check any of the checkboxes that aren't already checked
![grafik](https://github.com/user-attachments/assets/39a5a415-22a4-419b-b6ec-23f5c1ab41b9)
4. switch away from tab, go back, notice how nothing is saved

**Comment by nininik0** [comment]
I've had this issue a long time, somehow it worked fine for me in 5.8.0 once but then it just started going back, so I can confirm it can happen in 5.8.0 too.
