### ISSUE TITLE
Segfault when opening console

### ISSUE THREAD

**Issue by cosarara97** [minetest/minetest#149]
Opening the console sometimes causes a segmentation fault. It doesn't happen always, but I think it happens only if it's the first time you open it since you connected to the server.
I'm on linux 64 bit, always running latest version from git (compiled myself) and I have a bad intel (integrated) graphics card.

**Comment by gregorycu** [comment]
It's undefined behaviour to call isspace with a character value above 255. As we are calling isspace on a wchar, we are leaving ourselves open to a crash, but I'm not sure if that is the issue here.

**Comment by Zeno-** [comment]
Calling isspace with a character value > 255 is most certainly not undefined behaviour. However, calling isspace with a wchar value does seem to be incorrect as @gregorycu states.

**Comment by gregorycu** [comment]
@Zeno- I'm quite certain it's undefined, I'll check the specs when I get home tonight.

**Comment by Zeno-** [comment]
Yeah you're right it's undefined. Given int `isspace(int ch)`, `ch` must be representable as an `unsigned char` **or** equal to `EOF` (all other values are undefined behaviour).

**Comment by gregorycu** [comment]
I need someone on linux to try and say something in chat with a wide character. I want to see if the chat record on the server is causing a crash in clients due to wide characters.

**Comment by gregorycu** [comment]
I couldn't cause a crash by sending unicode characters over chat

**Comment by nerzhul** [comment]
Very old issue, too many things has changed. Please re-open if the issue is already there
