### ISSUE TITLE
Completely black screenshots on wayland

### ISSUE THREAD

**Issue by fgaz** [minetest/minetest#14901]
### Minetest version

```true
Minetest 5.9.0-dev-90fccc1 (Linux)
Using LuaJIT 2.1.1693350652
Built by GCC 13.2
Running on Linux/6.6.34 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/nix/store/gixslm1ibmc75ix53kyd5asys3rvngn2-minetest-unstable/share/minetest"
STATIC_LOCALEDIR="/nix/store/gixslm1ibmc75ix53kyd5asys3rvngn2-minetest-unstable/share/locale"
```

### Irrlicht device

SDL (with SDL_VIDEODRIVER=wayland)

### Operating system and version

NixOS Linux 24.05

Window manager: sway

### CPU model

AMD Ryzen 7 7840U

### GPU model

Radeon  780M

### Active renderer

OpenGL 4.6

### Summary

All screenshots I take are the right size but completely black. Using SDL_VIDEODRIVER=x11 works, but then I get all the problems related to xwayland.

### Steps to reproduce

1. Start minetest with `SDL_VIDEODRIVER=wayland minetest`
2. Load a world
3. Take a screenshot

**Comment by appgurueu** [comment]
Can reproduce on Fedora 40, also using Wayland.
