### ISSUE TITLE
Fix node swap lag (empty space instead of swapped node)

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [minetest/minetest#1492]
In my mod I need to replace node upon breaking with another (damaged-type) node. I tried to use after_destruct and then on_dig with no luck. Every time player breaks the node, minetest-client lefts empty space instead of digged out block and then put it back after some lag. Lag is noticeable even on my local machine, and when client thinks there is an empty space (which is wrong), player have an ability to dig unreachable blocks behind the solid block wall. I'd wish to have an ability to prevent this minetest-client behavior by setting some node flag like "prevent_client_dig_behavior" or something like that.

**Comment by sfan5** [comment]
`node_dig_prediction` exists now, closing.
