### ISSUE TITLE
Bugs with client-side collision detection.

### ISSUE THREAD

**Issue by kaeza** [minetest/minetest#1493]
It seems there is a bug with the way the client detects collisions and "pushes" the player in the other direction.

A new addition to [homedecor](https://github.com/VanessaE/homedecor_modpack/commit/5b705cf4edce5d748a1b9df74b57c68bb5cfcc56), 3D nodebox-based bookshelves, makes this bug easy to reproduce.

It can be seen in the following setup:
![screenshot_331846328](https://cloud.githubusercontent.com/assets/2388420/3600479/a637a9ec-0cf8-11e4-9d0c-6f38152c1a74.png)

Steps to reproduce:
- Walk up to the corner between the two bookshelves.
- Try to walk away.
- You are "pushed" into the corner _past_ the bookshelves (as if you phased through them).

The issue is in the client, and is hard to fix this in the mod itself (and if it were "fixed", would still be a workaround and not really a fix).

**Comment by paramat** [comment]
Is the collisionbox of the bookshelves incorrectly set? I see in the code that selectionbox and nodeboxes are set but not a collisionbox, maybe this is why? Try adding a collisionbox.

**Comment by paramat** [comment]
Uncomfirmed and no response.
