### ISSUE TITLE
5.9.0-beta version release for testing

### ISSUE THREAD

**Issue by okias** [minetest/minetest#14935]
### Problem

Hello,

I see 5.9.0 version is getting closer, is there chance to have beta release, so Linux distros can prepare for a new version and get a bit of testing from the power users?

### Solutions

Release alpha/beta/rc.

### Alternatives

Release without previous extensive testing within Linux ecosystem.

**Comment by rubenwardy** [comment]
See https://forum.minetest.net/viewtopic.php?t=30853

**Comment by okias** [comment]
Thank you, could you please tag it in git?
