### ISSUE TITLE
Minetest builds for Mac don't have signature

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#14939]
### Problem

The Minetest Mac applications available on the website are not signed.
In the default configuration of the actual Mac system users have to do a few unintuitive steps to open the downloaded Minetest application for the first time.

1. Open system settings, Privacy & Security
1. Start the Minetest application
1. Add an exception for the unsigned application
1. Start the Minetest application again and confirm the exception for running the unsigned application

Mac system at least two times warned the user that the application can a malware or a similar unwanted kind of application.

### Solutions

Register an Apple developer team on the Apple developer website, create an entitlements file, and use it for sign released application.

See also https://docs.github.com/en/actions/use-cases-and-examples/deploying/installing-an-apple-certificate-on-macos-runners-for-xcode-development

### Alternatives

Keep released Mac applications unsigned.

### Additional context

We can publish the build for Mac with Arm CPU with info, that commands `xattr -cr Minetest.app` and `codesign --force --deep -s - Minetest.app` have to be used to enable it.

**Comment by sfence** [comment]
See also https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#limitations-for-arm64-macos-runners

As a result -> The application will have to be signed locally probably.

**Comment by Montandalar** [comment]
If we want to get it first-party signed, then it looks like someone had better start the process now, because even after starting an actual process with an existing non-profit (GNOME foundation), it took GNOME almost 2 months to get a key/cert/thing and start to sign GIMP builds: https://gitlab.gnome.org/GNOME/gimp/-/issues/946 (from Alex Samorukov's first post onwards).

That's starting with a macOS developer and a non-profit. Minetest doesn't have a core developer who works on macOS nor a registered non-profit (to my knowledge at least).

**Comment by sfence** [comment]
> If we want to get it first-party signed, then it looks like someone had better start the process now, because even after starting an actual process with an existing non-profit (GNOME foundation), it took GNOME almost 2 months to get a key/cert/thing and start to sign GIMP builds: https://gitlab.gnome.org/GNOME/gimp/-/issues/946 (from Alex Samorukov's first post onwards).
> 
> That's starting with a macOS developer and a non-profit. Minetest doesn't have a core developer who works on macOS nor a registered non-profit (to my knowledge at least).

Yes, it can take time. However, MultiCraft has a signed app in the Apple store. It is a Minetest clone, so hopefully, it will only take a little time.

At the time I am probably the only core developer with MacBook.
