### ISSUE TITLE
[QUESTION] How do I grant privs via a luacontroller without having the sufficient grant priv on my game user?

### ISSUE THREAD

**Issue by SaiPanneerselvam** [minetest/minetest#14952]
I want to use a mesecons luacontroller, to grant a privilege like noclip on a user like LisaTI or something. How would i do this if i didnt have the grant priv

**Comment by rubenwardy** [comment]
This is the Minetest engine repository, we do not provide support for mesecons here

**Comment by SaiPanneerselvam** [comment]
sorry
