### ISSUE TITLE
Add more getter functions/methods for the Lua API

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#1496]
The Lua API has a lot of setter functions/methods (for setting a value) but it lacks many corresponding getter functions (for receiving a value). I suggest to add these getter functions.

I personally think there is in most cases no reason *not* to have such functions. It is just inconsistent and incomplete.

The suggested function/method names are like the setter functions, but with “get” instead of “set”. There is a single exception. After the arrow, I write the suggested return value. It is just the same as the input parameters. Remember that Lua functions can return multiple values at once, for example: `return 1,2,3,4`. I wrote the functions which I consider the most important in bold type.

So, here I list the functions I think are lacking in the Lua API:

For `ObjectRef`s:

* **`get_properties` → `object_property_table`**
* **`get_armor_groups` → `table_of_group_ratings`** (I tested it with the `luacmd` mod this function does *not* exist for players; since players are basically `ObjectRef`s, I conclude that this is true for other `ObjectRef`s as well)
* `get_animation` → `group_rating_table, frame_speed, frame_blend`
* `get_attach` → `parent, bone, position, rotation`
* `get_bone_position` → `bone, position, rotation`

For player objects:

* **`get_physics_override` → the same table used as input for `set_physics_override`**
* `hud_get_hotbar_itemcount` → number
* `hud_get_hotbar_image` → texture path
* `hud_get_hotbar_selected_image` → texture path
* `get_sky` → `bgcolor, type, {texture names}`
* `get_day_night_ratio` (getter function for to `override_day_night_ratio`) → ratio or `nil`
* `get_local_animation` → see input parameters of `set_local_animation`
* `get_eye_offset` → `first_person_offset, third_person_offset`

Global functions:
* `minetest.get_gen_notify` → flags (a `string`)
* `minetest.get_player_password` (OK, let’s just forget this suggestion, shall we?)
* `minetest.get_mapgen_params` → `MapgenParams`
* `minetest.get_noiseparam_defaults` → see `minetest.set_noiseparam_defaults`

For all suggested function names, I checked `lua_api.txt` if it already exists. It did not.

If you think I missed a function, please write a comment.

**Comment by nerzhul** [comment]
@ShadowNinja because you are working on mod_security can you provide us some advices on this issue ?

**Comment by ShadowNinja** [comment]
@nerzhul: This doesn't interact with mod security.

**Comment by TeTpaAka** [comment]
This can get closed now. c0335f7d13ee46c6a46d0ceebea96960439ec9fd

**Comment by Wuzzy2** [comment]
Thank you very much! Finally it is in. :-)
