### ISSUE TITLE
Flowing liquid propagation does not call `on_construct`

### ISSUE THREAD

**Issue by Sneglium** [minetest/minetest#14961]
### Minetest version

```true
5.9.0-dev
```

### Operating system and version

Kubuntu 24.04

### Summary

The engine-supplied functionality of liquid nodes to propagate their flowing alternative does not call the flowing version's `on_construct` callback when placing flowing liquid nodes.

### Steps to reproduce

1. Create a pair of source and flowing liquid nodes
2. Set the `on_construct` callback of the flowing version
3. Observe that the callback doesn't run when the liquid flows

**Comment by Sneglium** [comment]
(found out this is not needed)

**Comment by sfan5** [comment]
Changes to liquid nodes do not call callbacks and afaik this is intentional.
