### ISSUE TITLE
Windows release archive contains broken client/shaders/Irrlicht symlink

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#14972]
### Minetest version

```true
Minetest 5.9.0
```

### Operating system and version

Windows 32bit/64bit

### Summary

Some Windows users reported having problems unzipping the archive. It probably depends on the application being used to unzip and user account privileges.

### Steps to reproduce

Download the .zip archive, and check if the file/link `client/shaders/Irrlicht` is in it.

**Comment by rubenwardy** [comment]
I can't see it when opening the archive using thunar, but I can see it on the command line:

```
unzip -l minetest-5.9.0-win64.zip | grep Irrlicht
23  2024-08-11 17:19   minetest-5.9.0-win64/client/shaders/Irrlicht
```

what user visible effect does this have?

**Comment by sfan5** [comment]
these shaders are needed for the OpenGL 3 driver
when creating packages we should be copying the files pointed by the symlink, and not the link itself

**Comment by rubenwardy** [comment]
Which is only enabled with SDL2 right?

**Comment by sfence** [comment]
> what user visible effect does this have?

Some users say, he has to skip files and have no other issue.
One user says, that he was not able to unarchive and install the new Minetest version. Unarchive failed after he tried to skip a bad symlink.

**Comment by Kiisu-Master** [comment]
This is what i got with 7zip, i just ignored the message and minetest worked with no problems.
No interaction was needed. It's different with the windows explorer archive manager.
![image](https://github.com/user-attachments/assets/9bf04778-e306-4092-9046-dc18abc3ad63)

**Comment by Kiisu-Master** [comment]
I also tried unzipping with windows explorer but had no error message. Maybe some specific windows user permissions trigger it.

**Comment by tajemniktv** [comment]
Yeah, just tried to extract latest via NanaZip - same issue on my end

**Comment by SmallJoker** [comment]
Non-elevated users cannot create symlinks on Windows, even less so on filesystems that do not support them.

I think the solution is to

1. remove the symlink (does not work when building on Windows)
2. `install(DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/irr/media/Shaders" DESTINATION "${SHAREDIR}/client/Shaders/Irrlicht")`

**Comment by sfan5** [comment]
> remove the symlink (does not work when building on Windows)

this will break running opengl3/ogles2 with a source checkout.
OTOH we could also just move the shaders to the correct place. There's no reason they have to be in `irr/`
