### ISSUE TITLE
compatibility layer with minecraft mods

### ISSUE THREAD

**Issue by RustoMCSpit** [minetest/minetest#14978]
### Problem

there should be a way to translate forge / neoforge / fabric /  quilt mods into minetest readable

### Solutions

a compatibility layer between

### Alternatives

nope

**Comment by appgurueu** [comment]
I'm afraid this is not feasible for a variety of reasons, and not in scope for this project. Minetest is trying to be its own voxel game platform; it is not a Minecraft clone.
