### ISSUE TITLE
Delete OpenGL ES 1 driver

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#14976]
if we don't hear about new issues with the ogles2 driver with 5.9.0, we should drop the ogles1 driver entirely.
this is in line with the idea to require shader support some day.

to remove from irrlicht:
* everything under `_IRR_COMPILE_WITH_OGLES1_` or `IRR_COMPILE_GLES_COMMON`
* classes named `COGLES1`
* `EDT_OGLES1`

**Comment by Andrey2470T** [comment]
Is there a goal to remove `opengl` driver also? I think the limited fixed-function pipeline could be entirely removed from MT as its availability just doesn't do possible to solve some issues in PRs by the correct way, e.g. ambient light or sunlight API.

**Comment by sfan5** [comment]
There's no concrete plan but the idea of moving to OpenGL 3.x has been floated around which would mean deleting the `opengl` driver.
It wouldn't make sense to strip the fixed pipeline from it, because we already have the new cleaner driver.

it was briefly discussed here: https://irc.minetest.net/minetest-dev/2024-08-21#i_6194362

**Comment by sfan5** [comment]
Only @numzero knows the details, but I assume the plan was to use OpenGL in it's core profile (first appeared in 3.2) to definitely get rid of anything legacy and support OpenGL ES2 in addition to that.
How many desktop users that would exclude I have no idea.

**Comment by appgurueu** [comment]
Closed by #15067
