### ISSUE TITLE
OpenGL 3 driver: Colorized nodes are wrong if shaders are enabled

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14985]
### Minetest version

```true
Minetest 5.10.0-dev-98e51a015 (Linux)
Using LuaJIT 2.1.1713773202
Built by GCC 14.1
Running on Linux/6.9.10 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
```

### Irrlicht device

SDL

### Operating system and version

Fedora 40

### CPU model

AMD Ryzen 5 3500U

### GPU model

AMD Radeon Vega 11 (integrated graphics)

### Active renderer

OpenGL 4.6.0 (Compatibility Profile), Mesa 24.1.4

### Summary

There's a param2-colorized node in devtest which should look like this:

![Screenshot from 2024-08-16 13-39-23](https://github.com/user-attachments/assets/3e84823e-1259-43a7-a9e4-6a408a223ca5)

but looks like this:

![Screenshot from 2024-08-16 13-39-08](https://github.com/user-attachments/assets/012cd22e-326a-4040-b658-7988a403d432)

the param2-based base color is applied incorrectly. So far I've only been able to reproduce this with the OpenGL 3 driver and shaders enabled.

### Steps to reproduce

Set driver to OpenGL 3, enable shaders, place the "colorized base" node in devtest.

**Comment by zmv7** [comment]
> looks like an rgb <-> bgr confusion, potentially also affects ogles2.

Oh yes I clearly remember colorable curtains(and some other decorations) had the blue/red inversion on android, it was a while ago(in likely 5.4-5.5) though. Didn't pay attention on this in newer versions…

**Comment by zmv7** [comment]
> > looks like an rgb <-> bgr confusion, potentially also affects ogles2.
> 
> Oh yes I clearly remember colorable curtains(and some other decorations) had the blue/red inversion on android, it was a while ago(in likely 5.4-5.5) though. Didn't pay attention on this in newer versions…

It seems to be fine on 5.9.0 android

**Comment by appgurueu** [comment]
might've been an ogles1 issue then?

**Comment by zmv7** [comment]
> might've been an ogles1 issue then?

Perhaps. Don't remember exactly (but the main thing is that it is no longer observed in modern version tho)

**Comment by waxtatect** [comment]
I suppose this might be related to this issue ? (mt5.10 56123b2, Windows 10, SDL2+Opengl3)
with VoxeLibre (on 2b2t server)
shader on: water looks brownish
<img src="https://github.com/user-attachments/assets/c6cae88a-ac6f-4499-a585-7d1bc277bd97" width="100" height="100" /><img src="https://github.com/user-attachments/assets/14dd8c4c-7247-49e0-a13c-b6507188b303" width="100" height="100" />

shader off: black sign
<img src="https://github.com/user-attachments/assets/b571b032-06fb-4543-9cd4-4ccad812f030" width="100" height="100" /><img src="https://github.com/user-attachments/assets/29623ce5-5494-4fba-a3d7-7a0071479c16" width="100" height="100" />

**Comment by appgurueu** [comment]
I see two issues there: Water color, which is probably the same as this, and the black sign.

The latter looks like VoxeLibre is not setting `use_texture_alpha` properly, and a bug with enabled shaders is causing this to be ignored?

**Comment by Desour** [comment]
Probably same underlying issue:
With opengl3 driver, block boarders have the wrong colors (blue + cyan instead of red + yellow).

**Comment by zmv7** [comment]
> Probably same underlying issue: With opengl3 driver, block boarders have the wrong colors (blue + cyan instead of red + yellow).

Yes, I noted this in #15030
