### ISSUE TITLE
math.atan(y,[x]) does what?

### ISSUE THREAD

**Issue by karriforesthermit** [minetest/minetest#14982]
### Minetest version

```true
Minetest 5.9.0 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 11.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Ubuntu 22.04 LTS

### Summary

The arctan function in Lua doc says _"math.atan(y,[x]) Returns the arc tangent of y/x (in radians), using the signs of both arguments to find the quadrant of the result. "_ But it does not, or I am insane.

### Steps to reproduce

Lua code:
```
for x = 1,31,5 do
  print(x, math.atan(1.1,x), math.atan(1.1/x), math.atan(1.1/x,1))
end
```
Result:
```
1	0.83298126667443	0.83298126667443	0.83298126667443
6	0.83298126667443	0.18131977440149	0.18131977440149
11	0.83298126667443	0.099668652491162	0.099668652491162
16	0.83298126667443	0.068641989089834	0.068641989089834
21	0.83298126667443	0.052333124100525	0.052333124100525
26	0.83298126667443	0.04228247662763	0.04228247662763
31	0.83298126667443	0.035468989567519	0.035468989567519

```

**Comment by sfence** [comment]
Minetest is using Lua 5.1. In Lua 5.4 the `math.atan2` function has been removed, and a second optional parameter has been added to the `math.atan` function.
