### ISSUE TITLE
minetest 5.9 mapblock flickering depending on camera view

### ISSUE THREAD

**Issue by wsor4035** [minetest/minetest#14999]
### Minetest version

```true
Minetest 5.9.0 (Windows)
Using LuaJIT 2.1.1706185428
Built by Clang 17.0
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

win32

### Operating system and version

win10

### GPU model

nvidia geforce gtx 970

### Active renderer

OpenGL 4.6.0

### Summary

https://github.com/user-attachments/assets/73dfd5bc-e4ac-4176-8b80-e3dfa5785100

https://github.com/user-attachments/assets/2048482e-a9f7-4e2c-b695-d0f31e3a35e7

### Steps to reproduce

methods:  

1. join creativeworks server with a 5.9 client (maybe on windows only? havent checked other platforms yet) and fly along the rail system

2. [creativeworks_snippet_world.zip](https://github.com/user-attachments/files/16645941/creativeworks_snippet_world.zip) use this world snippet (made via local map saving), make sure you have farlands reloaded game and advtrains on the world, then teleport to `373, 8, -31` to replicate the first video

**Comment by wsor4035** [comment]
note: appears to only happen when connected to the server. not currently able to replicate locally

**Comment by wsor4035** [comment]
appears to work fine when shaders are disabled

**Comment by SmallJoker** [comment]
Cannot reproduce on:

 * Ubuntu 22.04, amdgpu driver, OpenGL 2.x (but 4.6 would be supported)
 * ^ + Wine 9.13 (using the 5.9.0 Win64 build)

The world looks normal.

![grafik](https://github.com/user-attachments/assets/781b8c26-fb14-4270-8ae3-cc1be884d17d)

**Comment by Zughy** [comment]
Same here, can't reproduce, Pop!_OS 22.04, shaders enabled

**Comment by rubenwardy** [comment]
@wsor4035  for graphics issues, you really should provide the model of your GPU. I believe you have an nvidia discrete GPU?

**Comment by rubenwardy** [comment]
> appears to work fine when shaders are disabled

What about when shaders are enabled but post-processing is disabled (if it's not already)?

**Comment by wsor4035** [comment]
> @wsor4035 for graphics issues, it would be helpful to provide the model of your GPU. I believe you have an nvidia discrete GPU?

nvidia geforce gtx 970

**Comment by wsor4035** [comment]
> > appears to work fine when shaders are disabled
> 
> What about when shaders are enabled but post-processing is disabled (if it's not already)? (`enable_post_processing`)

as per irc, issue still occurred when post processing was disabled

**Comment by wsor4035** [comment]
ci builds
grabbed a build from https://github.com/minetest/minetest/actions/runs/9696806743 (picked at random) broken
then tried a build from https://github.com/minetest/minetest/actions/runs/9175682650 (oldest non expired build) broken

sfan5 builds
tried build `minetest-5.9.0-fbec378-win64` from https://minetest.kitsunemimi.pw/builds/ works - date `2024-02-26` on the site
build `minetest-5.9.0-c63c05b-win64` broken - `2024-04-24`
build `minetest-5.9.0-5727d74-win64` broken - `2024-03-20`

**Comment by wsor4035** [comment]
commits between broken to non broken https://github.com/minetest/minetest/compare/fbec378...5727d74

**Comment by wsor4035** [comment]
making builds by checking out the respective commits on a branch, and then adding a newline to the github action to produce builds

baseline: https://github.com/wsor4035/minetest/actions/runs/10516154719 replication of sfan5 build works
using the build from the next commit (according to github - https://github.com/minetest/minetest/issues/14999#issuecomment-2295607727) https://github.com/wsor4035/minetest/actions/runs/10515935163 has the bug

cc @sfan5 as the author of the commit

**Comment by sfan5** [comment]
what is "the" commit? There's half a month between your two builds.

**Comment by wsor4035** [comment]
ah sorry, was going off what github is saying is the next commit 🤔 - will redo testing

**Comment by wsor4035** [comment]
ok, so i was dumb, and reading the list (https://github.com/minetest/minetest/compare/fbec378...5727d74) backwards previously

build https://github.com/wsor4035/minetest/actions/runs/10543403691 based off commit bb7f57b095cb6c95c5071d80ebc1c5173049c742 has the bug

so then i started going through the commits of https://github.com/minetest/minetest/pull/14395

build https://github.com/wsor4035/minetest/actions/runs/10543583057 based on commit 5280863300e88c6e42c320115a53f0957e113589 the first commit from that pr has the bug in it. so unless ive done something wrong again (sorry), it looks like that pr, first commit is at fault

**Comment by sfan5** [comment]
to confirm that please test fbec378869691444e354425073a7210555a9b31d. it should not have the bug.

**Comment by wsor4035** [comment]
i have already tested that commit, both with your build and https://github.com/wsor4035/minetest/actions/runs/10516154719 which work fine

**Comment by wsor4035** [comment]
retest again with my ci build from above, works fine

**Comment by sfan5** [comment]
okay. that would indeed point to 5280863300e88c6e42c320115a53f0957e113589.
however there's barely anything in this commit...

your title says "mapblock flickering". have confirmed using the block bounds function that it's always an entire mapblock that goes missing?

**Comment by wsor4035** [comment]
> actually at the mapblock lines

![image](https://github.com/user-attachments/assets/52d7b694-1a3e-440b-8218-5d25825f228e)
![image](https://github.com/user-attachments/assets/d1aa975e-a6d6-4afb-b0a6-b17f0149dd49)
![image](https://github.com/user-attachments/assets/5df4b500-3716-48b7-ac94-dd2314051def)

while different parts of the mapblock "flicker" differently, it does seem the flickering is limited per mapblock

> or better: post your minetest.conf
all tests where done with fresh builds, so its the stock minetest.conf. i can post neccessary?
(above test used a fresh build+mapblock key bound)

> opengl_debug

not sure if this is supposed to put stuff in chat or debug.txt, but not seeing anything

only thing im seeing in debug.txt is
> iCCP: known incorrect sRGB profile
> iCCP: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG

**Comment by sfan5** [comment]
> not sure if this is supposed to put stuff in chat or debug.txt, but not seeing anything

oh yeah it has limited effect unless you're on SDL + OpenGL 3 or OpenGL ES 2.
maybe you could see if it reproduces on opengl3 by chance?

**Comment by wsor4035** [comment]
grabbed the latest mingw64 build as of writing https://github.com/minetest/minetest/actions/runs/10529366914 - turned on opengl3, restart, still had the bug.

turned on opengl debug, restarted. while i hesitate to say the bug was gone with it on, at this time i am not able to reproduce it with the opengl debug on. 

these warnings look relevant from debug.txt, other ones are just irrlicht png warnings
```
2024-08-25 19:51:16: WARNING[#0x10592]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 16 is being recompiled based on GL state.
2024-08-25 19:51:16: WARNING[#0x10592]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 19 is being recompiled based on GL state.
2024-08-25 19:51:16: WARNING[#0x10592]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 91 is being recompiled based on GL state.
2024-08-25 19:51:16: WARNING[#0x10592]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 46 is being recompiled based on GL state.
2024-08-25 19:51:27: WARNING[Main]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 34 is being recompiled based on GL state.
2024-08-25 19:51:27: WARNING[Main]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 97 is being recompiled based on GL state.
2024-08-25 19:52:07: WARNING[Main]: Irrlicht: GL: 8246 8250 Program/shader state performance warning: Vertex shader in program 49 is being recompiled based on GL state.
2024-08-25 19:52:12: WARNING[Main]: Irrlicht: SDL_PollEvent took too long: 77ms
2024-08-25 19:52:21: WARNING[Main]: Irrlicht: SDL_PollEvent took too long: 79ms
```

**Comment by sfan5** [comment]
I looked at your log and unfortunately nothing useful to be found out there.

**Comment by SmallJoker** [comment]
1. Does the same issue occur with software rendering (otherwise same settings)? https://fdossena.com/?p=mesa/index.frag
2. To narrow down the issue: who else is affected by this bug, and do they have anything in common with your setup?

**Comment by nininik0** [comment]
The same is happening to me: https://youtu.be/srmkXHprw0s?si=yqsRn6YANRcdYWL-
This seems to only happen with alpha based nodes and liquids, as well as normal flowing liquids, somehow bandicam makes it not happen when its recording, i did manage to get a bit of it in the video,shadows seem to do the bug.

**Comment by wsor4035** [comment]
@nininik0 what gpu/hardware do you have?

**Comment by wsor4035** [comment]
third verification on discord (requires you to be in the minetest discord) https://discord.com/channels/369122544273588224/369123175583186964/1273306629000925205

**Comment by sfan5** [comment]
By the way in my debugging session yesterday I found out that you get the shown broken rendering if you skip the last few drawcalls of map drawing.
It seems likely that the root cause is not the identified commit but it rather just uncovers some broken/buggy behavior that manifests in yet unknown conditions.

possible future tests:
* does reverting 5280863300e88c6e42c320115a53f0957e113589 now fix it? (probably has conflicts)
* comment individual parts of 5280863300e88c6e42c320115a53f0957e113589 to determine which one causes it

**Comment by wsor4035** [comment]
per a request, did first possible test(one conflict to resolve), build: https://github.com/wsor4035/minetest/actions/runs/10755795327 and it the issue does not appear to occur here

**Comment by wsor4035** [comment]
thought it was worth noting, when fixing https://github.com/mt-mods/new_campfire/issues/7 pre adding `use_texture_alpha="blend"` that the node worked perfectly(abet with transparent parts black), and then once i set the property on the node it sticker flickering. just figured id mention it as texture alpha was changed in 5.9 (dropping the old code)

**Comment by wsor4035** [comment]
so i reverted the above for fun, and tested it: https://github.com/wsor4035/minetest/actions/runs/10782980440 - the issue does not appear to occur here

thoughts @sfan5 ?

**Comment by TechnoWolfTV** [comment]
I don't know if this helps find the root cause or not, but I've just discovered this:

https://github.com/user-attachments/assets/fb1b8764-4d48-4932-a3ff-e690efb03d4a

**Comment by nininik0** [comment]
Yes, somehow it also  causes not only liquids and alpha based blocks, but also mesh BLOCKS, note that i am also using alpha_workaround mod so maybe it relates.
