### ISSUE TITLE
Behavioral change in `get_bone_position`

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#14992]
#12388 introduced a behavioral change in `get_bone_position`:

Before, it would give you back the euler angles you passed to `set_bone_position`.
Now, it gives you an equivalent rotation (assuming Irrlicht's quaternion to euler angle and vice versa conversions are correct), which can break code which relied on it giving you the very euler angles you put in (such as code which interpolates a rotation manually).

The possibly affected mods and games are the following: https://content.minetest.net/zipgrep/5296f687-4e1c-4ae1-8520-0119d7940824/. Notably ElCeejo's mods are affected, as well as possibly the Mineclone family.

A simple workaround would be to keep the original euler angles around (which mods could also do themselves). Should I implement that?

**Comment by Zughy** [comment]
Is this gonna revert #13688?

**Comment by appgurueu** [comment]
> Is this gonna revert #13688?

No, the old (deprecated) API still uses degrees, the new API uses radians, and I won't change that. I will just store the euler angles (for both APIs?) and give those ("back") to modders rather than giving them an equivalent rotation.
