### ISSUE TITLE
Make `SecureRandom` non-failable.

### ISSUE THREAD

**Issue by num0005** [minetest/minetest#14991]
`SecureRandom` can in principle return nil, but I really don't see how that could happen if Minetest is able to run on that platform at all. It uses the same system random number generator as SRP login. It stands to reason since SRP is the only login method supported by Minetest that if the system entropy source didn't function then no user could log into the server in the first place.

And in any case, I don't think the entropy source can not be online, I doubt any modern Linux distro or Windows system would get much past boot in that case.

## Suggestion:

Throw an error instead of returning `nil` if the read fails, the server is likely doomed anyways if it has no system entropy source.

**Comment by DanTGL** [comment]
I'd like to try to fix this.

**Comment by appgurueu** [comment]
> I'd like to try to implement this.

Sure, go ahead. BTW, you don't need to ask for permission, though it might be nice to give a heads up so we don't have multiple people fixing the same issue (though this practically happens basically never).
