### ISSUE TITLE
Touchscreen can be enabled when Irrlicht device doesn't support touchscreen (CIrrDeviceWin32, CIrrDeviceMacOSX)

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#15005]
The touchscreen settings are still shown when the device doesn't support touchscreen, such as Windows

Split from #14973

**Comment by rubenwardy** [comment]
You shouldn't be able to enable touchscreen controls when touchscreen support isn't available. There's no backwards compatibility concern here

**Comment by SmallJoker** [comment]
https://irc.minetest.net/minetest-dev/2024-09-01#i_6197554

Suggestion:
1. New function for each `CIrrDevice*.cpp` that indicates touch support by the device.
2. Additional filter for `settingtypes.txt`

The default value will be solved properly by #14542, but not in 5.9.1.

**Comment by SmallJoker** [comment]
#14542 was merged. @grorp @rubenwardy Do we need additional code to fix the default, or is it good enough to auto-toggle as needed?

**Comment by grorp** [comment]
You can still break things and get confused by manually setting `enable_touch = true`, so I guess hiding the setting wouldn't be too bad.
