### ISSUE TITLE
Shaded block sides should not be blue tinted.

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#1501]
I noticed this while creating a new texture:

https://cdn.mediacru.sh/c0-AqmEdyhuQ.png

Colour should not be modified while brightness / contrast level should be.

Shaders were enabled in this view.

Shaders disabled:

https://cdn.mediacru.sh/AQrTaM6nLC1V.png

**Comment by paramat** [comment]
This is intentional blue tinting by nodes shader.
