### ISSUE TITLE
Android minimap is oversized

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#15021]
### Minetest version

```true
Minetest 5.9.0
```

### Irrlicht device

Android

### Operating system and version

Android

### Summary

![image](https://github.com/user-attachments/assets/d1d7e38c-6a14-465f-a3a6-0bb2720fd206)

### Steps to reproduce

Unsure

**Comment by appgurueu** [comment]
> Steps to reproduce

Have a small screen, enable minimap
