### ISSUE TITLE
Minetest Client: integrates mini IRC

### ISSUE THREAD

**Issue by atlantis451** [minetest/minetest#15028]
### Problem

All people who install Minetest Client can Chat together
- mini IRC mini IRC only supports text chat
Markdown is not support
Video images are not support

### Solutions

- Minetest Client GUI
- You can change the irc server address Minetest Client>settings 
irc Channel
`irc://irc.minetest.net/#es`
`irc://irc.minetest.net/#en`

### Alternatives

I didn't know there was any other way.

**Comment by cx384** [comment]
Alternative: Use an IRC mod https://github.com/minetest-mods/irc

Widelands has integrated IRC, but for Minetest an IRC mod should be sufficient. Adding it to the main menu also makes not much sense.
