### ISSUE TITLE
Super key doesn't work with SDL

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#15036]
### Minetest version

```true
5.10-dev, latest
```

### Irrlicht device

SDL

### Operating system and version

Pop!_OS 22.04 LTS

### Summary

Same as #15010 but for Super. It doesn't open up the interface to launch an app, that being..
![image](https://github.com/user-attachments/assets/d20a6154-2ff2-4549-8ee6-dfa921c9b4e9)

No issues with 5.9

### Steps to reproduce

Same as #15010

**Comment by rubenwardy** [comment]
I think this is a duplicate of the other ticket - the engine is capturing keys and the OS isn't receiving them

**Comment by Zughy** [comment]
Closing and merging the two
