### ISSUE TITLE
Clouds are not rendered when raising the head above a certain pitch, depending on their height

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#15031]
### Minetest version

```true
5.9.0
```

### Irrlicht device

X11

### Operating system and version

prr

### Summary

Same server, same clouds applied to both players.
Server is 5.8, players are 5.8 (the one without issues) and 5.9 (the broken one)

Dump of the clouds
![image](https://github.com/user-attachments/assets/97c2f249-8a92-44d1-a5e1-85ea1c972321)

Last sane pitch: -17.3

https://github.com/user-attachments/assets/cb87b6b4-87ab-4982-9a5c-3b3d94d5842c

### Steps to reproduce

1. Join A.E.S. server with a 5.9 client
2. look up

**Comment by Zughy** [comment]
In this other case height is 1080, pitch threshold is 9.5


https://github.com/user-attachments/assets/5a0338f8-77c9-4e31-b923-9867a290bfcc

**Comment by Zughy** [comment]
Height 300, this is fun

https://github.com/user-attachments/assets/06cdfa5b-e040-4863-b701-6d76fbb3411f

**Comment by appgurueu** [comment]
#14395 comes to mind as a large code change touching clouds.

**Comment by sfan5** [comment]
minimal reproducer (MTG):
```lua
core.after(0, function()
	function weather.get(player)
		return {
			clouds = {
				height = 1080
			}
		}
	end
end)
```
teleport (0,1036,0)
