### ISSUE TITLE
loading mesh but textures never load

### ISSUE THREAD

**Issue by CitroenGames** [minetest/minetest#15038]
```
	auto* device = m_rendering_engine->get_raw_device();
	auto* smgr = device->getSceneManager();
	io::IReadFile* file = device->getFileSystem()->createAndOpenFile("ninja/ninja.b3d");

	mesh = smgr->getMesh(file);
	if (!mesh) {
		LOG_ERROR("Failed to load ninja mesh");
		return;
	}

	irr::scene::IAnimatedMeshSceneNode* node = smgr->addAnimatedMeshSceneNode(mesh);

	auto* driver = device->getVideoDriver();
	io::IReadFile* file1 = device->getFileSystem()->createAndOpenFile("ninja/nskinbl.jpg");
	node->setPosition(irr::core::vector3df(0, 0, 0));
	node->getMaterial(0).setTexture(0, driver->getTexture(file1));
```

i wanted to load a mesh and a texture (the mesh and texture is from irrlicht examples) but it never seems to load in properly.

**Comment by Zughy** [comment]
Please open a new issue following the bug report or helping you would be quite difficult without all the required info

**Comment by appgurueu** [comment]
FWIW this isn't really a Minetest bug, it's more of a "how do I modify Minetest" question, and that needs many more details (what do you want to do, to begin with; why do you need to modify the C++ for this? where are you doing these modifications? note that minetest is not irrlicht and minetest's irrlicht fork, which is included in this repo, has diverged significantly).

It might be better suited to the forums or IRC (though in principle asking such questions here is also fine).
