### ISSUE TITLE
New outline[] formspec element

### ISSUE THREAD

**Issue by EpidermalDestruction** [minetest/minetest#15053]
### Summary

**Proposal** : Add a new formspec element outline[] which draws an outline by the gives positions. This could allow for more creative expressions in GUIs made by modders without having to use boxes to draw outlines.

I have made a version of this it works perfectly fine for me (https://github.com/Astra0081/minetest/tree/outline-formspec-element)

It looks something like this:
![Screenshot_2024-08-25-15-04-40-629_com garudclient](https://github.com/user-attachments/assets/5ef64037-1048-4bd4-b699-de5e00ca892d)

**Comment by rubenwardy** [comment]
The code here would be useful for drawing keyboard focus as well

**Comment by EpidermalDestruction** [comment]
Yep.

**Comment by grorp** [comment]
> Outlines would be useful for drawing keyboard focus as well

For that, we don't need outlines as a formspec element, but outlines as a formspec style[] option though.

**Comment by EpidermalDestruction** [comment]
> > Outlines would be useful for drawing keyboard focus as well
> 
> For that, we don't need outlines as an outline[] element, but outlines as a style[] property though.
> 
> If we need outlines as a style[] property anyway, adding a separate outline[] element would be redundant.

Personally a seperate element in good, but lets wait for other people’s opinion on this and move ahead by keeping other’s opinion in mind.

**Comment by Zughy** [comment]
`style[]` makes more sense :+1: (it makes even more sense to focus on the formspec/HUD replacement #12926 )

**Comment by appgurueu** [comment]
Isn't this use case already solved in a more flexible manner by 9 slice images? I don't see the need for another formspec feature, except possibly for convenience (and if so, worth discussing whether this should be mod responsibility), where I would agree that a `style[]` property makes more sense.

I'm skeptical about bloating formspec with redundant convenience features while a formspec replacement is in progress, so personally I would consider this low priority.

**Comment by Astra0081** [comment]
I'm working on making it a style[] property so that formspec elements don't get too saturated. Also as of 9 slice images it's true, but this feature is a bit handy than that of creating an image just for an outline.

**Comment by v-rob** [comment]
An `outline[]` element is completely unnecessary given `box[]`'s styling options--if it's too much typing to use `style_type[]` directly, make a helper function to do it for you.

As for focus rectangles on buttons, I'd argue that 9-slice images are a much better way of doing this.  Most games that want their GUIs to look good will already be using 9-slice images, so it's just a matter of creating a custom image for buttons that are focused.

(Perhaps a notable exception is if you want a dotted line as a focus outline, but I'd argue that's a deficiency of 9-slice images: you should be able to choose whether the slices are stretched or tiled, something that I will add support for in the new UI API.)

**Comment by rubenwardy** [comment]
My plan was to add focus highlighting by default, so I suppose we could switch to 9 slices (with a flattened button) or maybe the border button could hardcode it

**Comment by v-rob** [comment]
Hardcoding it for formspec buttons is reasonable--the gradiented look is already hardcoded.  The new UI API expects games to make their own theme (unless they use the optional bundled one), so focusing will be handled via the theme.
