### ISSUE TITLE
ParticleSpawner doc: `size` field is a float range, not a vec3 range

### ISSUE THREAD

**Issue by rudzik8** [minetest/minetest#15060]
### Minetest version

```true
Minetest 5.10.0-dev-56123b2fb (Linux)
Using LuaJIT 2.1.1703358377
Built by GCC 13.2
Running on Linux/6.8.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

### Operating system and version

Linux Mint 22

### Summary

https://github.com/minetest/minetest/blob/56123b2fbe1ad4e7878556f8d51c551d84fb92e7/doc/lua_api.md?plain=1#L11002

This line is plain wrong. The `size` property of ParticleSpawner definition is a float range, not a vec3 range. If you set it to a vec3 range, it will be ignored altogether.

### Steps to reproduce

1. Load this code: https://gist.github.com/rudzik8/bc408af503ace7d4a7621f8e9ed221c2
2. Do `/meow { min = 1, max = 50 }` and switch to 3rd person view
3. Do `/meow { min = {x=1, y=1, z=1}, max = {x=50, y=50, z=50} }`

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/pull/14804/files#diff-c60ce2a4d38acfedec97ac1b19e9e207aa60f223f1b7fdd1048c00bdf1f8d5d9R10927-R10929

@grorp

**Comment by grorp** [comment]
Indeed. Before it was undocumented, now it's documented incorrectly :)
