### ISSUE TITLE
Minetest Is Really Quiet Or Silent

### ISSUE THREAD

**Issue by LWFlouisa** [minetest/minetest#15070]
### Minetest version

```true
Minetest 5.9.0 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 11.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Operating system and version

Linux Mint 21

### Summary

Minetest sound was working yesterday when I used Music Player Daemon, and now it's almost completely silent. I checked my speakers and everything works outside of minetest.

### Steps to reproduce

Load up minetest. Check the volume on sounds.

**Comment by Zughy** [comment]
You sure you haven't muted MT by accident? Press M
