### ISSUE TITLE
implement stronger password protections and proper hashing

### ISSUE THREAD

**Issue by Darin755** [minetest/minetest#15081]
## The feature request

Right now Minetest doesn't have a good way of supporting modern secure hashing operations. It has the ability to do a hash for the user password but it has a weak algorithm. Ideally the hash should be changed to at least sha256 if not sha512 and it should be salted. This should be secure for a while at least and will make it harder to brute force a stolen hash. For user passwords the salt should only be known by the server. It might be wise to totally hide user passwords from lua altogether by creating an API to set and check a user password. The checking of a user password should enforce a delay to make brute forcing attempts harder. 

### Solutions

Here is a example of what the API might look like:

```minetest.sha256sum(data)```: Does a sha256sum hash of the data. Doesn't use a salt but the salt could be handled by the mod.

```minetest.check_user_creds(username, password)```: checks credentials and returns true or false. Delay handled by server. I am concerned about mods asking for passwords but I don't have a solution to that problem.

```minetest.set_password(username, password)```: sets the password for a user

### Alternatives

The Minetest server also could just switch to a stronger hash without modifying the API. However, I think this is likely a breaking change anyway so it might make sense to "rip the band aid off" so to speak.

### Additional context

It also would be nice if Minetest had some sort of secrets API that would allow mods to securely store and handle sensitive data. Ideally it be nice if a mod could simply call a helper function to store sensitive data in a hash. I could see this being used for something like a password protected door or something similar. This would prevent sensitive data from being stored in Lua where sealing it might be easier. The database would be a key value store that would allow a mod to check a secret.

Example:

```minetest.set_secret(keyname, value)``` sets a secret

```minetest.check_secret(keyname, value)``` returns true or false based on if the value is the same as the set value

```minetest.clear secrets()``` destroys all stored secrets

**Comment by sfence** [comment]
I think you misunderstand the code. SHA of the password is not stored in the database or sent to the server.
SHA is used over the username and password combination string to get some unique byte array. That array is processed via SRP. See https://github.com/minetest/minetest/blob/master/src/util/srp.cpp for details.

See also #14196, but it does not look like it has support to be merged.

**Comment by appgurueu** [comment]
Many issues in one. Let's dissect this.

> Right now Minetest doesn't have a good way of supporting modern secure hashing operations

Duplicate of #14980, which is much more fleshed out. We already support SHA256.

> For user passwords the salt should only be known by the server. 

Is it not? I haven't heard of any major issues with Minetest's SRP implementation in this regard.

> `minetest.sha256sum`

We already have this. It's called `minetest.sha256`.

> `minetest.check_user_creds`

Again we already have this. It's called `minetest.check_password_entry`. It doesn't do rate limiting to my knowledge, but I would argue that it shouldn't. Deciding on a sensible rate limit is the business of user-facing mod code, not of the engine.

> `minetest.set_password`

`minetest.set_player_password`. Please check whether features exist before requesting them.

> The Minetest server also could just switch to a stronger hash without modifying the API.

Yes, it absolutely could.

> However, I think this is likely a breaking change anyway so it might make sense to "rip the band aid off" so to speak.

No, this will not be a breaking change. We will not break authentication backwards compatibility anytime soon. It is very much possible to have newer clients use a newer auth with newer servers, while still supporting older auth mechanisms for older clients and older servers.

> [secrets API]

This should be in a different feature request.

So far I'm not convinced however. You seem to be suggesting a "global" API which is a bad idea, mods could easily conflict, especially with APIs like `clear_secrets`. So far I also don't see how this would differ from just storing hashes in mod storage. Where do you plan to store these "secrets"; how do you plan to protect them?

**Comment by red-001** [comment]
I mean for the secrets API, it doesn't seem to really be secrets for a start, more just passwords. 

Admittedly Minetest doesn't really expose any good password hashing APIs to Lua, only got a few standard hash functions. If bcrypt or argon2 were added for general password hashing then mods could use that too. 
If  #15078 was merged then at least mods could store passwords in a salted form, per the discussion in #14980 SRP verifier exponentiation is a actually fairly slow, so even with just SRP+SHA256 it's a somewhat acceptable password storage setup.

I don't know if mods use their own password systems enough for it to be worth building out a special API for protecting the hashed password data, especially since mods can already retrieve the user password verifier for the standard auth system.

**Comment by Darin755** [comment]
Never mind, I seem to have totally misunderstood
