### ISSUE TITLE
ERROR[main]: WARNING: updateListener: invalid value

### ISSUE THREAD

**Issue by yamanq** [minetest/minetest#1508]
![screenshot_1260963606](https://cloud.githubusercontent.com/assets/8166212/3640659/cfda3db2-10a6-11e4-9b20-8f33edaef2ea.png)

**Comment by paramat** [comment]
Perhaps caused by being teleported to infinity? So the teleport bug is the real bug.

**Comment by SmallJoker** [comment]
Positions are checked against being valid or not. If this was caused by a mod, it should throw the error `Invalid float vector dimension range`.

**Comment by paramat** [comment]
`void updateListener(v3f pos, v3f vel, v3f at, v3f up)`
That function works with pos, so the 'inf' co-ordinate is probably the issue here and probably is another issue (or should be).
