### ISSUE TITLE
item_drop mod broken due to engine changes

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#1509]
Apparently some changes in the builtin item code seem to break my item_drop mod: https://github.com/PilzAdam/item_drop/issues/3
Please fix this, since the engine is supposed to be backwards compatible for mods.

**Comment by nerzhul** [comment]
@PilzAdam is this actual ?

**Comment by RobertZenz** [comment]
With the addition of a `dropped_by` field in #3343, this can be more elegantly solved, [see my version of an auto-pickup mode](https://github.com/minetest-australopithecus/minetest-australopithecus-auto-pickup/blob/ef4c9a90ebc40d44073ef33f53d4b1b7e89c22a1/mods/auto_pickup/autopickup.lua#L110).

**Comment by HybridDog** [comment]
Can you close this, it's a bug of the item_drop mod, it redefines too much and makes it older.
