### ISSUE TITLE
touch_punch_gesture not only applied for actual punching

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15097]
### Minetest version

5.9.0 on Android

### Summary

The "touch_punch_gesture" setting is not only applied when punching objects, but for any left-click when pointing an object.

### Steps to reproduce

1. Create a MTG world with Simple Shooter and Mobs Monster.
2. Use the SMG to shoot monsters (by doing a long tap and holding, which translates to holding LMB)
3. When the monsters get closer and you can point them, the SMG stops working: Since you're pointing an object, you would have to do a short tap instead of a long tap to press LMB

Another example:
1. Eat an apple without pointing an entity (long tap)
2. Eat an apple while pointing an entity (short tap)

This is an unintended side-effect of #14087 I've been thinking about for a while.

The solution I came up with is only applying "touch_punch_gesture" when the item is actually able to punch, i.e. has no on_use callback defined. I'm not sure whether this will make the controls more inconsistent in other cases, though.

**Comment by appgurueu** [comment]
I do wonder why the apple or SMG allow pointing at things at all. It doesn't make much sense for either item.

**Comment by grorp** [comment]
You can place an apple as a node, so that needs pointing. For the SMG you're right that it isn't really necessary, but it's convenient since it allows you to e.g. open a chest with RMB while holding the SMG.

**Comment by grorp** [comment]
Imagine an SMG item with LMB to shoot and an NPC entity with RMB to trade. With my proposed fix, the behavior becomes more consistent from the following perspective:

before:
- nothing pointed: long tap to shoot
- NPC pointed: short tap to shoot, long tap to trade

after:
- nothing pointed: **long tap to shoot**
- NPC pointed: short tap to trade, **long tap to shoot**

But from a different perspective, things become less consistent:

before:
- bare hands: short tap to punch, **long tap to trade**
- SMG: short tap to shoot, **long tap to trade**

after:
- bare hands: short tap to punch, long tap to trade
- SMG: short tap to trade, long tap to shoot

**Comment by appgurueu** [comment]
> You can place an apple as a node, so that needs pointing. For the SMG you're right that it isn't really necessary, but it's convenient since it allows you to e.g. open a chest with RMB while holding the SMG.

Out of scope for this issue, but primary / secondary action pointabilities should probably be able to differ (that would be a separate feature request).

**Comment by appgurueu** [comment]
> The "SMG stops working if enemy is too close" thing definitely needs fixing though, so maybe we have to trade that inconsistency for the other.

For the SMG specifically, I feel the new pointability API provides a fine solution for modders: They can set `pointabilities = {objects = {["group:fleshy"] = "blocking"}}` (assuming the SMG's damage group is `fleshy`).

This means that all entities the SMG can damage wouldn't be pointable, and couldn't be pointed through, so you could shoot them just fine.

This issue ultimately is a symptom of current limitations of the pointability API.
