### ISSUE TITLE
Add priority field to ABM definition

### ISSUE THREAD

**Issue by ancientmarinerdev** [minetest/minetest#15093]
### Problem

Currently ABM's are timeboxed to run for 0.2s, and if they overextend that they are abandoned. Due to the fact the ABMs are shuffled before they run, game devs have no say over which ABMs are ran and which are abandoned. Games such as VoxeLibre (previously MineClone2) had a history of frequently hitting the time constraint and abandoning the use of them. Exile has moved away from ABMs because of the limitations: (https://github.com/minetest/minetest/issues/14011#issuecomment-1817666073).

In order to improve this, the general advice on VL was to move to timers (messy, complex, and often worse profiling wise), or to abuse global steps. Basically, if the timer hits this number, execute this code to guarantee this crucial logic has run. The amount of profiling issues I found from getting nodes around a point from a global step was quite significant.

ABM design is pretty neat and it solves an effective job in a simple way. While the timeboxing was done as issues were worse if it was not present, the current knock on effects of this often make them unfavoured and ABMs tend to be used for less relevent stuff.

### Solutions

Add a priority field to ABM definitions so that mod authors (and specifically game authors can control what ABMs are important and need to run and which they're happy with abandoning). The priority field would have 5 values. The default if unset is 3 (which would support backwards compatibility), and that way, modders and developers can use this to give an indication to what priority this abm should have. For example, if you have some crucial automation logic that must run, or machines break, or something that has a very real effect on the game that say interacts with the players, you could assign this a 2 (important), or even a 1 (critical), and this logic is executed first. If it's 4 (low priority) or 5 (cosmetics), it will only execute these if there is the time available to do this and for example if a player misses out on a particle effect, it may not be the end of the world compared to a key gameplay feature that could break some machine.

Long term, this can complement the proposal to spread scheduling over multiple globalsteps (https://github.com/minetest/minetest/issues/14011). If you are deferring uncompleted runs to a future tick, having control over which need to run first and which is fine for deferral would make that change less risky and more desirable from an effects perspective.

Current logic

The current logic randomly shuffles the applicable ABM's and runs them until the time budget is reached and then they are abandoned never to be run.

New approach

Order ABM's by priority and (optionally) randomly shuffle the order (in each priority group) and execute in order until time budget is hit.

### Alternatives

Not neccessarily alternatives but relevent context and complimentary solution:

#14011
#14114
#10068

### Additional context

Although my C++ is primative, I would be happy to attempt this if the concept is approved. If someone who is more comfortable around the codebase and this area would prefer to attempt this, I am happy to defer to them on this. Please could you give this proposal consideration. Thanks.

**Comment by wsor4035** [comment]
initial thoughts this kinda seems like a bad hack to plaster over the larger issue, also what happens once you have mods all saying they are the top priority, modify other ones, etc.

**Comment by appgurueu** [comment]
Yes, ideally ABMs would "just be fast enough" but I don't think this is realistic.

This is ultimately a scheduling problem. It might be worth looking at how various other schedulers that have priorities handle this.

One thought: Why not a probabilistic approach? If the budget is constantly exhausted and only higher priority ABMs run, that seems suboptimal vs. just running higher priority ABMs (much) more likely, but also sometimes running lower priority ones. (Another advantage of a probabilistic approach is that it can be nicely continuous when it comes to priorities.)

**Comment by ancientmarinerdev** [comment]
> initial thoughts this kinda seems like a bad hack to plaster over the larger issue

I don't think this is a hack. The time budget was needed. Processing time is finite. Deciding how it is used is either left to random chance, or it is the decision of the game dev or modder. I think only a game dev, or a "soup" creator can really decide how important each element in their game is. Even if you roll over unrun ABMs, if it's running over, it's delaying execution of something that could be important and break a mechanic. A game dev or modder should have a say on this.

If you feel this is a hack, please can you indicate what you think would be a correct solution to this?

> also what happens once you have mods all saying they are the top priority, modify other ones, etc.

I did think about this, but right now, people just abandon ABMs to prioritise their code and ensure it runs. Abusing configuration and working around is happening, so not making a change will not change that fact. This change is more for game devs, who will be weighing up decisions on multiple mods. If some mod is abusing it, the game developer would either opt not to use it, or copy it and drop the priority of it.

**Comment by ancientmarinerdev** [comment]
> Yes, ideally ABMs would "just be fast enough" but I don't think this is realistic.
> 
> This is ultimately a scheduling problem. It might be worth looking at how various other schedulers that have priorities handle this.
> 
> One thought: Why not a probabilistic approach? If the budget is constantly exhausted and only higher priority ABMs run, that seems suboptimal vs. just running higher priority ABMs (much) more likely, but also sometimes running lower priority ones. (Another advantage of a probabilistic approach is that it can be nicely continuous when it comes to priorities.)

I'm open to suggestions on how other schedulers solve this problem.

I think the probabilistic approach is already done when choosing which ones run. The chance has already been decided when the execution has happened. So combining probabilistic choice makes it less predictable to understand what exactly is going on. Priority is very simple, it's a way to say I want x before y. I cannot see a case where someone would think something is a higher priority 90% time but not the other 10%. They would be using to say "this task is more important so I need this to run first".

Secondly, a game dev is still responsible for making sure they don't have death by ABM and aren't blasting through the budget, and the cases where it is over the time budget is probably not all the time, only for certain ticks. In those few cases, what case would anyone want to abandon high priority abms?

>  (Another advantage of a probabilistic approach is that it can be nicely continuous when it comes to priorities.)

I'm not sure I understand this point, could you elaborate, please?

**Comment by appgurueu** [comment]
By a probabilistic approach I am referring to the following: The higher the priority, the larger the chance that this ABM runs first. This can be achieved e.g. by doing subsequent weighted selection.

Your approach is discrete: There are a couple fixed priorities. Within a priority, everything has equal chance of running first (assuming we go with the shuffling).

My approach would be roughly continuous: An ABM with priority 1.5 would be more likely to take priority over an ABM with priority 1, but less likely to take priority over one with priority 2.

**Comment by ancientmarinerdev** [comment]
> By a probabilistic approach I am referring to the following: The higher the priority, the larger the chance that this ABM runs first. This can be achieved e.g. by doing subsequent weighted selection: The engine would take the sum of all priorities, and the chance of an ABM running first would be determined as `priority / sum`, rinse and repeat until you have a "run order". This "run order" would be recomputed every time ABMs run.
> 
> Your approach is discrete: There are a couple fixed priorities. Within a priority, everything has equal chance of running first (assuming we go with the shuffling).
> 
> My approach would be roughly continuous: An ABM with priority 1.5 would be more likely to take priority over an ABM with priority 1, but less likely to take priority over one with priority 2.

I appreciate the clarification. This solution would likely be better than the current setup, and I'm not opposed to it, but I still think it adds a complexity in terms of a probability on top of a probability which makes things less predictable and harder to investigate.

The solution I'm proposing would probably require a shuffle and a sort, and maybe the sort would probably be slightly more expensive than the probabilistic approach. The only concern I have with the proposed solution is that it would a have a slightly increase overhead on a very frequently executed set of logic that needs to be optimised. Functionality wise, I think the decision should be with a modder rather than luck.

**Comment by sfence** [comment]
The implementation of #14011 will be better than the priority for ABMS.
Prioritization does not fix the problems with ABMs we have.

**Comment by appgurueu** [comment]
> The implementation of #14011 will be better than the priority for ABMS.

Only under the assumption that then the time budget will suffice, for all users, on all machines.

> Prioritization does not fix the problems with ABMs we have.

I disagree, I can definitely see the use case of a game wanting to registering more ABMs than compute power allows, with the expectation that low priority ABMs will be skipped if the time budget is reached.

I would agree however that #14011 is definitely higher priority than this issue.

**Comment by sfence** [comment]
> > The implementation of #14011 will be better than the priority for ABMS.
> 
> Only under the assumption that then the time budget will suffice, for all users, on all machines.
> 
> > Prioritization does not fix the problems with ABMs we have.
> 
> I disagree, I can definitely see the use case of a game wanting to registering more ABMs than compute power allows, with the expectation that low priority ABMs will be skipped if the time budget is reached.
> 
> I would agree however that #14011 is definitely higher priority than this issue.

Implementation of #14011 should allow the use of 100% of available server performance. Now it is present that most of the time servers do "nothing" and one per time they skip some ABMs to keep the server step within some reasonable limit.
If we allow some ABMs to be spreadable and some not, it should fix the most of problems. If it would not be enough, we can apply something like this. But I do not expect a big shift from it.

**Comment by ancientmarinerdev** [comment]
> > > The implementation of #14011 will be better than the priority for ABMS.
> > 
> > 
> > Only under the assumption that then the time budget will suffice, for all users, on all machines.
> > > Prioritization does not fix the problems with ABMs we have.
> > 
> > 
> > I disagree, I can definitely see the use case of a game wanting to registering more ABMs than compute power allows, with the expectation that low priority ABMs will be skipped if the time budget is reached.
> > I would agree however that #14011 is definitely higher priority than this issue.
> 
> Implementation of #14011 should allow the use of 100% of available server performance. Now it is present that most of the time servers do "nothing" and one per time they skip some ABMs to keep the server step within some reasonable limit. If we allow some ABMs to be spreadable and some not, it should fix the most of problems. If it would not be enough, we can apply something like this. But I do not expect a big shift from it.

I'm happy with better resource usage and spreading that across server steps. I think a queue that is pulled from until exhausted is sensible. One thing I am concerned about is that without a game creator specifying priority, it will result in delays to time critical ABMs which still creates the same problem that ABMs cannot be relied upon. If my schedule has decided to run something every 1s, and it is delayed by 0.5s because it is queued behind superficial non-critical ABM's such as particle effects, or entity eye candy, then I cannot rely on it. I may be happy for eye candy to be delayed, but not core game functionality. The problem changes from being about reliability to latency. That could still force a game developer to just use global steps as they have been doing. The processing will be still happening, and the game dev will still be choosing priority, they're just using hacks because the game engine isn't open to game devs indicating what is actually important (and just as importantly, what isn't).

The engine should trust that the game dev knows what they are trying to achieve. The engine is a set of tools for game devs to make games.

In a nut shell, the only difference would be a random queue, versus a (partially) sorted queue (based on priority). I personally do not think that the complexity level is that high and is worth heavy consideration when developing the solution (unless there are performance implications that are too significant).
