### ISSUE TITLE
Upright sprite animation is broken on MT5.9.0

### ISSUE THREAD

**Issue by jeremyshannon** [minetest/minetest#15105]
### Minetest version

```true
Minetest-5.9.0
```

### Operating system and version

Devuan Daedalus (eq to Debian Bookworm)

### Summary

While visual="sprite" works fine, visual="upright_sprite" does not animate properly on current Minetest stable. The sprite sits, frozen.

### Steps to reproduce

Load the attached snippet in devtest. Left click places an upright sprite entity, right click a regular sprite one that is otherwise identical. The upright doesn't animate, the player-facing one does.
```
minetest.register_entity("animtest:sprite",{
	initial_properties = {
	   visual = "upright_sprite",
	   collides_with_objects = false,
	   textures = { "testnodes_anim.png",},
	   spritediv = { x = 1, y = 4 },
	},
	on_activate = function(self, dtime, moveresult)
	   self.init = true
	   self.timelimit = 20
	   self.object:set_sprite(nil, 4, .5)
	end,
	on_step = function(self, dtime, moveresult)
	   self.timer = ( self.timer or 0 ) + dtime
	   if self.timer < self.timelimit then return end
	   self.object:remove()
	end,
})

local function set_up_entity(pointed_thing)
	local ppos = pointed_thing.under
	if not vector.check(ppos) then return end

	local pos = vector.new(ppos.x, ppos.y + 1, ppos.z)
	return minetest.add_entity(pos, "animtest:sprite")
end

minetest.register_craftitem("animtest:sprite_item",
  {
     description = "Animated sprite entity test",
     inventory_image = "testnodes_anim.png^[verticalframe:4,1",
     on_use = function(itemstack, user, pointed_thing)
	set_up_entity(pointed_thing)
     end,
     on_place = function(itemstack, user, pointed_thing)
	local ent = set_up_entity(pointed_thing)
	ent:set_properties({ visual = "sprite" })
     end
})

```

**Comment by Zughy** [comment]
Can confirm. I've tested with devtest Entity Spawner and `testentities:upright_animated` doesn't work on 5.9 nor 5.10-dev (I'm behind 7-8 commits). Works flawlessly on 5.8

**Comment by SmallJoker** [comment]
It seems to work just fine on my end, or am I missing something. Context:
![grafik](https://github.com/user-attachments/assets/2d66df39-4b4a-4312-a371-78f8a6385db4)

Linux, X11, CIrrDeviceLinux. OpenGL 2.1+.

**Comment by sfence** [comment]
I just tested minetest 5.9.0 from Arch Linux packages,

And `testentities:upright_animated` do not animate.

Some results on downloaded MacOS app 5.9.0 and self-built. No animation.

**Comment by Desour** [comment]
`testentities:upright_animated` isn't animated for me either. (Arch Linux, X11, SDL irrdevice, amd gpu, tested with opengl and opengl3 drivers, and tested with empty settings)

**Comment by appgurueu** [comment]
I have a fix.
