### ISSUE TITLE
upstreaming of lua_atccall

### ISSUE THREAD

**Issue by okias** [minetest/minetest#15102]
### Problem

The https://github.com/minetest/minetest/pull/12445/ introduced lua_atccall.

While bundling own lua is no big deal within Windows/MacOS environment, it makes in general Linux packages life harder, as distributions are very reluctant to ship local libraries copies (mainly due to risk of being missed out when security issue arises).

### Solutions

Sending the patch to the official ML: https://www.lua.org/lua-l.html .

I believe this patch could get accepted by upstream as it brings value to the developers using Lua within C++ environments.

When the patch gets accepted upstream, even before release, it's easier to convince packagers to ship it, as the patch doesn't alter existing functions of lua. 

### Alternatives

Doing nothing, which slightly slowdown the release process on Linux + makes maintainers less happy :wink:

**Comment by appgurueu** [comment]
> I believe this patch could get accepted by upstream as it brings value to the developers using Lua within C++ environments.

I'm afraid not. We're stuck on Lua 5.1, which has been EOL for more than a decade:

> The last release was [Lua 5.1.5](https://www.lua.org/ftp/lua-5.1.5.tar.gz), released on 17 Feb 2012. There will be no further releases of Lua 5.1.

(from https://www.lua.org/versions.html)

**Comment by okias** [comment]
I think it's not expected that Lua 5.1 will get new release, but acknowledging the change as useful world-wide (outside of Minetest project). Then I can try to work with distros and make it useful for everyone (and make Minetest distribution more efficient).

**Comment by wsor4035** [comment]
minetest already requires its fork of lua anyways for one or more patches.

**Comment by okias** [comment]
which one?

**Comment by red-001** [comment]
anyone can try to upstream it tbh, you don't need support from the project (whatever that would mean).
