### ISSUE TITLE
collisionMoveSimple: maximum step interval exceeded, lost movement details!

### ISSUE THREAD

**Issue by DustyBagel** [minetest/minetest#15120]
### Minetest version

```true
Minetest-5.9.0-win64-stable
```

### Irrlicht device

win32

### Operating system and version

Windows 11 home

### Summary

I keep getting this error on my personal minetest server. It is modded, and I seem to only get it when moving on something like a plane from pa28 or while riding a horse from animalia. Not completely sure this is an engine issue but I need someone to take a look:

"2024-09-04 22:20:11: WARNING[Server]: collisionMoveSimple: maximum step interval exceeded, lost movement details!
2024-09-04 22:21:17: ERROR[Server]: An unhandled exception occurred: C++ out of memory
2024-09-04 22:21:17: ERROR[Server]: In thread 30144:
2024-09-04 22:21:17: ERROR[Server]: /home/runner/work/minetest/minetest/src/server.cpp:96: virtual void *ServerThread::run(): A fatal error occurred: C++ out of memory"

Before this error, there is usaully alot of these messages printed out:
"2024-09-04 22:15:36: WARNING[Server]: First & third person eye offsets don't match, assuming first person"

I wonder if this is just a brakeage of mods with the changes from going to 5.9.0 from 5.8.0 as hinted at by:
"2024-09-04 22:17:16: WARNING[Server]: Reading initial object properties directly from an entity definition is deprecated, move it to the 'initial_properties' table instead. (Property 'pointable' in entity 'animalia:lasso_entity')"
and other such messages from a few other mods.

Any help or suggestions on how to figure out what is causing this are appreciated.

### Steps to reproduce

This is going to be a bit tricky to reproduce because the root cause of the problem isn't understood. Honestly, I haven't been able to reproduce it myself yet but maybe someone else can by doing what I did or has experienced the same problem.

**Comment by sfence** [comment]
Probably related to #15029 and #15027

**Comment by sfan5** [comment]
This log message just means you server had a lag spike above 2.5s. There's no bug for us to fix here.

**Comment by appgurueu** [comment]
This is a performance problem. Without further details it isn't clear what is responsible for this.

If you want to profile the Lua side of things, use [jitprofiler](https://content.minetest.net/packages/jwmhjwmh/jitprofiler/). To profile the engine side, something like [this guide](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/profiling/beginners-guide-to-performance-profiling.md) should work (I don't use Windows though, so I haven't tried this).

The warning messages are unrelated:

> First & third person eye offsets don't match, assuming first person

This warning message is emitted by a hack I wrote a while ago which uses raycasts to determine what the player is pointing at. The hack can't know whether the player is in first or third person view however, so when the two differ, it warns.

> Reading initial object properties directly from an entity definition is deprecated, move it to the 'initial_properties' table instead. (Property 'pointable' in entity 'animalia:lasso_entity')"

This is just a deprecation warning, there has been no change in behavior here.

**Comment by DustyBagel** [comment]
Do you mean that this is a performance problem with the engine or with the Lua mods I have @appgurueu? If it is with the engine, then I should still try to investigate the problem, right?

**Comment by DustyBagel** [comment]
Not sure if this is important but this was fixed in 5.9.1.
