### ISSUE TITLE
GamePad Bluetooth controller 

### ISSUE THREAD

**Issue by Pierochr** [minetest/minetest#15127]
### Problem

I can't find a way on rocknix ex jelos to configure minetest with external Bluetooth gamepad

### Solutions

Can't play , can't associate gamepad external Bluetooth 

### Alternatives

Only way is to play with console x55

**Comment by rubenwardy** [comment]
Duplicate of #4153 

See this link for a work around for now: https://wiki.minetest.net/Gamepads
