### ISSUE TITLE
Resize ingame names, depending on distance

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1513]

**Comment by nerzhul** [comment]
Because it's a duplicate of #1627 and this request is older i close it.
Thanks for your report;

**Comment by rubenwardy** [comment]
It makes sense to close the newer request.

**Comment by nerzhul** [comment]
oops, i inverted, you are right.

**Comment by C1ffisme** [comment]
Maybe an API for names would be nice. I would like to see some methods of disguising or hiding your name.

**Comment by indriApollo** [comment]
And a way to easily display text or even an image above the players head

**Comment by ProgrammingChicken** [comment]
@C1ffisme and @indriApollo
This is what you might be looking for
https://github.com/minetest/minetest/issues/1345

**Comment by paramat** [comment]
#1627 contains this, so folding this into that.
