### ISSUE TITLE
API for mods to dynamically load medias as binary blobs

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#15139]
### Problem

Minetest has some APIs to use media in game. Such as `minetest.sound_play` which plays a sound from a given file. Or the formspec showing images or 3D models. But these have to be a file. We can't like, play a sound from a given binary data which the mod somehow loads it.

### Solutions

 - Make a slight change to `minetest.sound_play` API and other APIs accepting `SimpleSoundSpec`. `SimpleSoundSpec` could have an additional `blob` param accepting a `string` or `userdata` where the actual sound binary is.
 - Regarding formspec it seems more complex. Maybe add an API in `minetest` namespace to write the binary data to some temporary in memory location then use a temporary name to use in formspec?

### Alternatives

I haven't got much of an idea on how to handle binary data in Lua. Alternatively, one could think of an API `minetest.store_blob(filename, blob)` and then use the filename in any API which requires a filename. The API then could choose to save data on disk or in memory.

### Additional context

The actual usecase for this feature request is showing images and playing audio files from HTTP APIs. We could consider loading blobs from HTTP endpoints instead. But I dislike this approach as it should be up to the mods to load their blobs. And with only a blob loading API, we could have more flexiblity.

**Comment by cx384** [comment]
Why wouldn't the already existing `minetest.dynamic_add_media(options, callback)` be sufficient for your use case?
Everything else would have to wait for SSCSM.

**Comment by farooqkz** [comment]
Sorry I had to do my research or at least ask in some community chatroom before opening an issue...
