### ISSUE TITLE
Star color is incorrect when shaders disabled

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#15143]
## what?

shaders enabled:
![screenshot_20240910_193653](https://github.com/user-attachments/assets/38394d12-e33e-4f4b-9f30-479480e4c57a)

shaders disabled (but with OpenGL only):
![screenshot_20240910_193639](https://github.com/user-attachments/assets/798eb4e6-3b19-47ff-ae49-d0b4db418160)

## why?

the sky code uses hardware lighting for the stars (and several other textures, which causes some more problematic differences):
https://github.com/minetest/minetest/blob/733a019bf5aefddb824e5643b791ca25fc620b03/src/client/sky.cpp#L82
this is only implemented on the GL driver, and only for the shader-less materials.

effectively this means with shaders enabled the stars get some dull color (blended against sky?)
while *without* shaders you get the color set by the API with alpha ignored

the default is `video::SColor(105, 235, 235, 255)`

## since when?

AFAICT this was actually introduced in 3077afc0a2039cd4c8d64d9df62ed9b2ba6463dc (5.4.0)
I quickly tested 5.0.1 and the stars are always the duller color.

**Comment by grorp** [comment]
Patch that seems to work:

```diff
diff --git a/src/client/sky.cpp b/src/client/sky.cpp
index f309d444c..bcf5aa69e 100644
--- a/src/client/sky.cpp
+++ b/src/client/sky.cpp
@@ -25,6 +25,7 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 #include <ISceneManager.h>
 #include <ICameraSceneNode.h>
 #include <S3DVertex.h>
+#include "client/mesh.h"
 #include "client/tile.h"
 #include "noise.h" // easeCurve
 #include "profiler.h"
@@ -77,9 +78,9 @@ Sky::Sky(s32 id, RenderingEngine *rendering_engine, ITextureSource *tsrc, IShade
 	// Create materials
 
 	m_materials[0] = baseMaterial();
-	// FIXME: shouldn't this check m_enable_shaders?
-	m_materials[0].MaterialType = ssrc->getShaderInfo(ssrc->getShader("stars_shader", TILE_MATERIAL_ALPHA)).material;
-	m_materials[0].Lighting = true;
+	m_materials[0].MaterialType = m_enable_shaders ?
+			ssrc->getShaderInfo(ssrc->getShader("stars_shader", TILE_MATERIAL_ALPHA)).material :
+			video::EMT_TRANSPARENT_ALPHA_CHANNEL;
 	m_materials[0].ColorMaterial = video::ECM_NONE;
 
 	m_materials[1] = baseMaterial();
@@ -688,7 +689,10 @@ void Sky::draw_stars(video::IVideoDriver * driver, float wicked_time_of_day)
 	color.a *= alpha;
 	if (color.a <= 0.0f) // Stars are only drawn when not fully transparent
 		return;
-	m_materials[0].EmissiveColor = color.toSColor();
+	if (m_enable_shaders)
+		m_materials[0].EmissiveColor = color.toSColor();
+	else
+		setMeshBufferColor(m_stars.get(), color.toSColor());
 
 	auto sky_rotation = core::matrix4().setRotationAxisRadians(2.0f * M_PI * (wicked_time_of_day - 0.25f), v3f(0.0f, 0.0f, 1.0f));
 	auto world_matrix = driver->getTransform(video::ETS_WORLD);
@@ -835,7 +839,6 @@ void Sky::updateStars()
 	vertices.reserve(4 * m_star_params.count);
 	indices.reserve(6 * m_star_params.count);
 
-	video::SColor fallback_color = m_star_params.starcolor; // used on GLES 2 “without shaders”
 	PcgRandom rgen(m_seed);
 	float d = (0.006 / 2) * m_star_params.scale;
 	for (u16 i = 0; i < m_star_params.count; i++) {
@@ -854,10 +857,10 @@ void Sky::updateStars()
 		a.rotateVect(p1);
 		a.rotateVect(p2);
 		a.rotateVect(p3);
-		vertices.push_back(video::S3DVertex(p, {}, fallback_color, {}));
-		vertices.push_back(video::S3DVertex(p1, {}, fallback_color, {}));
-		vertices.push_back(video::S3DVertex(p2, {}, fallback_color, {}));
-		vertices.push_back(video::S3DVertex(p3, {}, fallback_color, {}));
+		vertices.push_back(video::S3DVertex(p, {}, {}, {}));
+		vertices.push_back(video::S3DVertex(p1, {}, {}, {}));
+		vertices.push_back(video::S3DVertex(p2, {}, {}, {}));
+		vertices.push_back(video::S3DVertex(p3, {}, {}, {}));
 	}
 	for (u16 i = 0; i < m_star_params.count; i++) {
 		indices.push_back(i * 4 + 0);
```

**Comment by grorp** [comment]
Umm... actually I think this is a recent regression caused by this: https://github.com/minetest/minetest/commit/bb7f57b095cb6c95c5071d80ebc1c5173049c742#diff-841c1b824e0ac7bf7749b4e4d239685d529ef79054b6a91dd1730c4b38c625e4

```diff
-	m_materials[0].DiffuseColor = m_materials[0].EmissiveColor = m_star_color.toSColor();
+	m_materials[0].EmissiveColor = color.toSColor();
```

If I set both again, it works again. Thoughts?

**Comment by sfan5** [comment]
Hmm I don't remember changing that.

>   Real fixed pipeline: Dynamic color set via vertex color -> correct, but performance might suffer
>  Fake fixed pipeline: Dynamic color set via vertex color -> correct, but performance might suffer

This doesn't matter. Time spent ensuring the shader-less code paths are fast is wasted time.
Getting rid of `Lighting = true` is still the correct way forward.
