### ISSUE TITLE
iPad Version

### ISSUE THREAD

**Issue by ArielEco2014** [minetest/minetest#15158]
### Problem

I am always frustrated when I want to play MineTest with my friends. They only have iPads and they don’t have Mac.

### Solutions

I would want an iPad version of MineTest, as I think this is a very good game. Please try to make it a downloadable app in the App Store.

### Alternatives

Nil

### Additional context

Nil

**Comment by DragonWrangler1** [comment]
There was some reason that minetest wasn't on ios (was it due to the modding ?). I just can't remember.

**Comment by sfence** [comment]
MultiCraft je na iOS i iPad. Jdou tam aj mody instalovat.
Ale z nejakeho duvodu je maji v predkompilovanem Lua.

**Comment by kromka-chleba** [comment]
Apple Store policy is in some way incompatible with GNU GPL v3, because the policy restricts the users:

https://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store

https://opensource.stackexchange.com/questions/9500/is-apple-allowed-to-distribute-gplv3-licensed-software-through-its-ios-app-store

https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement

But Minetest is under LGPL v2.1, so I'm not sure if the issues persist:

https://forums.developer.apple.com/forums/thread/27709

And Multicraft is there with the very same LGPL v2.1 code they took from Minetest.

**Comment by chmodsayshello** [comment]
This *MIGHT* be an option: https://support.apple.com/en-gb/117767

**Comment by nininik0** [comment]
yes, but multicraft has visual glitches too, such as oversized mesh nodes etc, unstable client, somehow they crashed my server by rightclicking a helicopter, yet minetest client no

**Comment by red-001** [comment]
Unfortunately
> 2.5.2ASR & NR Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the app completely viewable and editable by the user.

**Comment by red-001** [comment]
Some apps like Roblox I think use client sided Lua but they might have special permission for that which CDB might not get. Would in that case have to limit the app to only a client without the ability to play singleplayer games.

**Comment by sfence** [comment]
@ red-001 The biggest problem is to make the luajit work well in arm64 builds on macOS. A self-contained app means only that the path to data should be changed.

**Comment by red-001** [comment]
@sfence I was pointing out the ["no downloadable code" requirement](https://developer.apple.com/app-store/review/guidelines/#safety) for app notarization, I think that's a separate process from MacOS notarization.

**Comment by red-001** [comment]
I see the core technology fee got mentioned on the forum, but that wouldn't apply to Minetest. Not sure if this was the case from the start but:

> Developers that earn no revenue whatsoever. This includes offering a free app without monetization of any kind (physical, digital, advertising, or otherwise). This is intended to give students, hobbyists, and other non-commercial developers an opportunity to create a popular app without paying the CTF.

https://developer.apple.com/support/core-technology-fee/

Would still need to pay the fee for the account.

**Comment by red-001** [comment]
Probably worth keeping open actually @Zughy unless all stakeholders are already aware that Apple is no longer requiring additional per-install payments for free apps. 

It's a pretty significant change from the old situation around this issue - it would actually possible for ordinary players to install Minetest without jailbreaking their devices provided they live in the European Union. Rest of the world would have to stick to side-loading but at least some players could use an official build.

**Comment by sfence** [comment]
> @sfence I was pointing out the ["no downloadable code" requirement](https://developer.apple.com/app-store/review/guidelines/#safety) for app notarization, I think that's a separate process from MacOS notarization.

So there is a question if MultiCraft solution is ok. They does not distribute Lua code but Lua bytecode.

Btw: they use luajit with disabled compiler.

But in future, we will have to finish macOS support, or to go through this at least for macOS.

Actually, luajit is etc 1000 times slower for arm64 minetest in comparation with luajit from standalone binary or from x86_64 minetest. It is probably something with entitlements. But I try entiteiments for jit and it does not help.

**Comment by sfence** [comment]
@rubenwardy I don't think so. We are not oriented to generate profit.

**Comment by red-001** [comment]
even if you consider the 22 Euro a week on librepay to be revenue, I don't see how that would be tied to a potential app. There isn't in-app prompts to donate and barely any links to that section of the website. 

Alternative, I think setting up a non-commercial legal entity is fairly straightforward in some countries. I think France might be one of them if anyone is based there.

**Comment by sfence** [comment]
@red-001 https://developer.apple.com/app-store/review/guidelines/#software-requirements
> (iii) They may not auto-launch or have other code run automatically at startup or login without consent nor spawn processes that continue to run without consent after a user has quit the app. They should not automatically add their icons to the Dock or leave shortcuts on the user desktop.

I think this can fix one windows which ask user if he really wants to run singleplayer server and execute downloaded Lua code from user mods.

**Comment by red-001** [comment]
> @red-001 https://developer.apple.com/app-store/review/guidelines/#software-requirements
> 
> > (iii) They may not auto-launch or have other code run automatically at startup or login without consent nor spawn processes that continue to run without consent after a user has quit the app. They should not automatically add their icons to the Dock or leave shortcuts on the user desktop.
> 
> I think this can fix one windows which ask user if he really wants to run singleplayer server and execute downloaded Lua code from user mods.

That's only for releasing on the App Store itself, which I think still could have ToS issues. Not for notarization, there should be an toggle on the side of that page to only highlight notarization requirements not the full app store requirements.

![image](https://github.com/user-attachments/assets/190a6fae-caaa-4d02-945f-a47635282a61)
