### ISSUE TITLE
Minetest 5.9.0+: Results of unitest module TestServerModManager results depends on devtest game version

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#15156]
### Minetest version

```true
Minetest 5.9.0
```

### Operating system and version

Probably OS independent

### Summary

The released version is built with unit tests and this unit test uses the Devtest game which can be downloaded https://content.minetest.net/packages/Minetest/devtest/ by the users.

### Steps to reproduce

Install the released version of Minetest or build Minetest and replace the Devtest game.
Install Devtest from Contentdb. Run unittests by `--run-unittests` command line argument.

Something like: 
```
Test assertion failed: mods.size() == 31 + 1
    actual  : 30
    expected: 32
    at test_servermodmanager.cpp:125
[FAIL] testGetMods - 21ms


Unit Test Results: FAILED
    1 / 47 failed modules (1 / 299 failed individual tests).
    Testing took 4949ms total.
```
Will be reported.

**Comment by SmallJoker** [comment]
Why does devtest even exist as a ContentDB package? I thought it was only meant to be available in tree for people who develop the Minetest engine.

**Comment by sfence** [comment]
It is there probably for modders. They can easily check/see/test what is possible.

**Comment by sfan5** [comment]
Not a bug. It's fine if unittests only work with the exact devtest version at that revision.

**Comment by sfence** [comment]
I mentioned it because it can result in false bug reports from users.
