### ISSUE TITLE
Wieldhand looks different with shaders enabled/disabled

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15166]
### Minetest version

6f23de41fb9566b00757c5f6fee6d3904a40a0d9

### Operating system and version

Fedora 40

### GPU model

NVIDIA GeForce GTX 1080 Ti

### Active renderer

OpenGL 4.6.0

### Summary

with shaders:
![screenshot 1](https://github.com/user-attachments/assets/e6f77a67-2a1b-4844-9d2a-348431ad9488)

without shaders:
![screenshot 2](https://github.com/user-attachments/assets/4a318892-ed81-4098-acf3-38f8740ff0ea)

related: #15143

This doesn't look like a (recent) regression, I can reproduce on it 5.7.0.

### Steps to reproduce

1. MTG world
2. `/time 23:00`
3. `enable_shaders = true`, take screenshot
4. `enable_shaders = false`, take screenshot
5. compare

**Comment by appgurueu** [comment]
Possibly related (if not a duplicate): #12578. That issue is a bit too specific though so preferably this one should be kept.
