### ISSUE TITLE
minetest.get_player_window_information's "touch_controls" option should be moved to an integer/string

### ISSUE THREAD

**Issue by swagtoy** [minetest/minetest#15167]
### Minetest version

```true
Minetest 5.9.0
```
### Operating system and version

Windows 11 The latest

### Summary

I am opening this thread because I want to question this.

Specifically, I want to just axe the `touch_controls` key and just move to a new variable, simply because:

- You can only really use one control method at a time. There would be:
  - Touch controls
  - Keyboard controls
  - Controller controls
  - VR controls
  - Neurolink
  - Xbox 360 Logitech Steering Wheel
- Writing your own fallback would be easier anyway `local is_touchy = (win.control_method == 2 or win.touch_controls)`
- It's so astonishingly new that I doubt anyone is using it yet
- ..and anyone that IS using something from 5.9.0 probably wouldn't mind updating their code if we axed it.

I suggest removal because deprecation for something that was just added and is already quite niche is just going to look gross.

If this is approved, I will keep this issue up, but will very likely fix this myself since I'm already using said code to change a formspec I'm writing.

### Steps to reproduce

1. Use Xbox 360 Logitech Steering Wheel.
2. Question your life decisions.

**Comment by rubenwardy** [comment]
Touch controls specifically refers to the onscreen controls, if those are visible then you can't use other input methods to control the game

See #12264 for the remaining stuff

**Comment by swagtoy** [comment]
@rubenwardy Apologize, I never saw that issue. I'd say it's not 100% a duplicate, especially seeing your issue suggesting something different, however I'll actually contribute to your issue instead so it's fine. Appreciate it.
