### ISSUE TITLE
Graphic bug -> missing hearts HUD

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#15170]
### Minetest version

```true
Minetest 5.9.0 official release and 5.9.1 prerelease version.
```

### Operating system and version

MacOS 14

### CPU model

M2

### GPU model

M2

### Active renderer

OpenGL 2.1

### Summary

Lives bar disappears after some time of playing.

Observation from 5.9.1 prerelease:
<img width="1440" alt="Screenshot 2024-09-15 at 16 55 43" src="https://github.com/user-attachments/assets/8353aec0-130a-4e17-9504-016368d79aff">
<img width="1440" alt="Screenshot 2024-09-15 at 17 01 35" src="https://github.com/user-attachments/assets/52f87aec-ba70-4044-9d96-a802c12cbc0c">

Observation from 5.9.0:
<img width="1440" alt="Screenshot 2024-09-15 at 18 52 43" src="https://github.com/user-attachments/assets/53036e86-b2ad-4ef0-b749-f6852a1ebcca">
<img width="1440" alt="Screenshot 2024-09-15 at 18 52 48" src="https://github.com/user-attachments/assets/9011928b-d75b-46a3-a95e-956f6662d7bd">
<img width="1440" alt="Screenshot 2024-09-15 at 18 56 13" src="https://github.com/user-attachments/assets/3a2e0cea-fba6-4f3c-a1a4-42c9c7a80d19">

### Steps to reproduce

I reproduced it several times after playing for a few hours. I estimate from 1 to 3 hours.

**Comment by Zughy** [comment]
Can you also reproduce it on devtest?

**Comment by SmallJoker** [comment]
It's interesting how only the health HUD is affected. If it's got the internal ID 0, then it might be deleted by accident by another mod. This certainly needs to be reproduced with as few mods as possible.

**Comment by appgurueu** [comment]
Suggestion: Hijack `player:hud_remove` / `player:hud_change` and dump a stack trace every time these are called with the same ID as the health HUD. This can be done from builtin.

Side note: HUD IDs suck for enabling this kind of bug and essentially returning us to the dark ages of manual ~~memory~~ ID management. This issue wouldn't exist if HUD elements were userdatums.

**Comment by cx384** [comment]
I can't reproduce it, so when the healthbar is not visible, please show use the result of this:
``` lua
print(dump(player:hud_get_all())
print(player:hud_get_flags().healthbar)
print(player:get_armor_groups().immortal)
print(player:get_hp())
```
(Maybe the bar just got disabled by the HUD flag/armor group, or it is still there, but not visible when the hp 0, could be caused by #7879, or the bug is related to #14346, but I also suspect that another mod just messed something up.)

It is very likely that the hotbar will have ID 0, but it could also get another one if it gets disabled for a short time and another element takes ID 0 in the meantime.

> Side note: HUD IDs suck for enabling this kind of bug and essentially returning us to the dark ages of manual memory ID management. This issue wouldn't exist if HUD elements were managed as userdatums.

Maybe #14104 would actually make sense.

**Comment by sfence** [comment]
So some new information. 
I reproduced this on the 5.10.0 dev version.
And also on 5.9.0 Linux version.

![shot](https://github.com/user-attachments/assets/04957c6e-4b00-498c-966d-9268fba85606)

I hijacked hud_add, hud_remove, and hud_change calls.

It looks like the problem comes from the offhand mod. But makes no sense why.

**Comment by sfence** [comment]
Confirmed it is an offhand mod bug.

**Comment by sfence** [comment]
More info here https://github.com/t-affeldt/minetest_offhand/issues/2 if you are interested.
