### ISSUE TITLE
I can't hide the game interface for android

### ISSUE THREAD

**Issue by daniiltur4in** [minetest/minetest#15188]
### Проблема

Не знаю, как скрыть игровой интерфейс на maintest, I think we need to add a function 

### Решения

Создайте новую кнопку, чтобы скрыть интерфейс maintest на Android

### Альтернативы

Я смотрел новую команду /hub 0

### Дополнительный контекст

_Нет ответа_

**Comment by nauta-turbidus** [comment]
The reason why there's no such thing is probably that it's unclear how to show it again. Possibilities:
1. Show again on any touch input.
2. Show again after a certain time.
3. Show again after "back" button input (could be confusing).
Could do more than one and add settings for it.

**Comment by nininik0** [comment]
I agree. This should be a feature.  I used to have a texture pack hiding the main buttons.

**Comment by daniiltur4in** [comment]
It is better to show the interface on the touch only not once but twice on the click, just how to click on the screen button, you need to add a warning window and give a hint how to return the interface

**Comment by grorp** [comment]
There's two different possible feature requests here:

- The ability to hide the touch controls while still being able to interact with them

- The ability to hide the touch controls while disabling them as well (already available via a setting as of 5.10.0-dev)

Which one are you requesting?

And what exactly is your use case? The first post is quite unclear about that.

**Comment by daniiltur4in** [comment]
how the new button will look like it will look very simple you need to create an image in the form of a frame and balls with these and then you need to make another cross there put it in this image before you click on this veteran with a cross then you need to add a warning and before you click again then the cross disappears and if you if you start then a cross will be shown, but if the cross appears in the picture then it means that the interface is shown and if you click on it then the interface will hide, well, the sensor fest but you can only walk

**Comment by daniiltur4in** [comment]
Okay, so I can’t hide the interface for android, you can block the topic 😞

**Comment by rubenwardy** [comment]
It's quite hard to understand you, you can post in your native language and someone else can help translate if that's easier

It's would be good to know why you want to hide the interface, what you are trying to do, as that informs the design. My guess would be for screenshots or recording

**Comment by daniiltur4in** [comment]
Да я хотел скрить интерфейс для записи и скримшота, а управление на андроїд, в minetest мне только мешает снимать видео и не красивою видео получается.

**Comment by daniiltur4in** [comment]
@grorp What do you suggest ?

**Comment by vintprox** [comment]
@daniiltur4in, for the benefit of readers, I want to clarify: what you seek is a touch control that you can hold to temporarily hide the game user interface?

If so, that indeed would be a welcome addition, as it makes for a quality-of-life screenshotting and recording. The execution requires some unpacking, because it's also not convenient to hold the button when you try to do other things - perhaps, solved by double-tapping or navigating "Back".

**Comment by daniiltur4in** [comment]
@vintprox Thanks for the offer

**Comment by daniiltur4in** [comment]
@vintprox I think it's a good solution to double tap on the touch screen

**Comment by nininik0** [comment]
> Request still not clear, closing

ill probably make  my own issue to make it more clear
