### ISSUE TITLE
register_on_mods_loaded calls while some functions still think the game is loading

### ISSUE THREAD

**Issue by swagtoy** [minetest/minetest#15200]
### Minetest version

```true
5.9.1
```

### Irrlicht device

WIN32

### Operating system and version

Windows 12

### Summary

When calling register_on_mods_loaded, and using a function such as minetest.get_connected_players(), function still complains about get_connected_players() being ran at runtime

`Warning [ServerStart]: Calling get_connected_players() at mod load time is deprecated`

# Workaround

1. Don't call get_connected_players() in mod loadtime, as technically (?) the player has not joined, but not sure how this affects server.
2. Use `minetest.after(0.1, ...)`. Doesn't complain when using get_connected_players(), but also has a 50/50 chance of working unless you use a longer time like 0.5 given that the player hasn't connected yet.
3. Use player on join method (at least in my scenario)

### Steps to reproduce

```lua
minetest.register_on_mods_loaded(function()
	for i,player in ipairs(minetest.get_connected_players()) do
		errorform(errorqueue, player)
	end
end)
```

**Comment by sfan5** [comment]
This is working as intended. "mod load time" is any point in time before the first server step happens and `register_on_mods_loaded` is after all mods were loaded but *before* the first server step.

So the first legal opportunity to call `get_connected_players` is with `minetest.after(0, ...)`. However no player can possibly join that fast, so it's not an useful thing to do.
If you want to show something to the first player you will need to use the join callback.

**Comment by swagtoy** [comment]
@sfan5 Should we improve the error message, at least? Or keep it as is?

I agree, it's really a user issue

**Comment by sfan5** [comment]
How would you improve it?

**Comment by appgurueu** [comment]
We should probably make clearer that `register_on_mods_loaded` is still considered "load time", which enables it to do stuff that is only possible at load time. Currently the docs say this:

> Called after mods have finished loading and before the media is cached or the aliases handled.

The wording here slightly contradicts the wording of the error message, which considers it mod load time.

**Comment by swagtoy** [comment]
What @appgurueu says, really. I wouldn't in a million years have distinguished mod load time to the time that the first onstep calls. How to word it? No clue at the moment, but anything better than what it says for sure
