### ISSUE TITLE
mindboggling variable naming conventions in CMatrix4:setRotationRadians() 

### ISSUE THREAD

**Issue by FatalistError** [minetest/minetest#15202]
### Minetest version

```
5.9.1
```

### Summary

Matrix code is nonsensical and unreadable. "cr, sr, cp, sp, cy, sy" are terms meaning "cosine roll, sine roll, cosine pitch ... " and so on. The rotation matrix code that is used for entities throws this out the window and seemingly uses them completely at random, where roll is set to X, pitch is set to Y and yaw is set to Z. This is obviously confusing as all hell.

(edit) to clarify:

the issue is that the variable names aren't correctly corresponding to their vector counterpart.
for example. 
`cp = cos(rotation.x)` is correct
`cr = cos(rotation.x)` is incorrect because roll is the _Z_ axis not the x axis.
The same issue is found with the other variables. This is an issue when trying to understand the code because the matrix reads completely differently due to these variables being improperly named, it's incredibly confusing and isn't something I _noticed_ until hours after trying to understand it.

https://github.com/minetest/minetest/blob/700fbc803d7fb393863074beb9e6c86e6883f003/irr/include/matrix4.h#L858
### Steps to reproduce

1) view https://github.com/minetest/minetest/blob/700fbc803d7fb393863074beb9e6c86e6883f003/irr/include/matrix4.h#L858
2) lose mind when trying to find out what the rotation order is.

**Comment by FatalistError** [comment]
I wasted _fucking hours_ trying to decode this before I realized that it was just incredibly shit code and didn't use conventions.

**Comment by FatalistError** [comment]
ill possibly fix this one day myself

**Comment by swagtoy** [comment]
I don't mean to be rude, but I think it's pretty obvious, especially considering the context of what these are set too.

It's in 3 dimensions, and we use roll, pitch, and yaw to represent these. We never really use X, Y, or Z to represent the rotation of say, a camera. Even the function name gives a hint of what these could possibly mean.

It's very likely, especially in the context of mathematical functions, that this code is just a codified version of an algebraic statement. Make these names more clear would make lines 866-884 stretch way past 80 characters.

But hey, I think an underscore could help, compared to just 2 little characters at least.

**Comment by FatalistError** [comment]
> I don't mean to be rude, but I think it's pretty obvious, especially considering the context of what these are set too.
> 
> It's in 3 dimensions, and we use roll, pitch, and yaw to represent these. We never really use X, Y, or Z to represent the rotation of say, a camera. Even the function name gives a hint of what these could possibly mean.
> 
> It's very likely, especially in the context of mathematical functions, that this code is just a codified version of an algebraic statement. Make these names more clear would make lines 866-884 stretch way past 80 characters.
> 
> But hey, I think an underscore could help, compared to just 2 little characters at least.

You missed the entire point hun. 
Z is Roll
X is Pitch
Y is Yaw
this code doesn't use those conventions because it's likely adapted and or thrown together.

**Comment by FatalistError** [comment]
but when you're trying to break down the meaning (i.e. rotation order) due to the complete lack of comments, you run into an issue when the variables randomly switch over to the wrong axis

**Comment by swagtoy** [comment]
YEs i see it now :) Thank you. I thought you meant the variable names being confusing.

**Comment by PichiBeta** [comment]
Hey! I want to work on this issue. I do want to clarify so I make sure I understand this properly though: the name of the variables are wrong and have to be fixed. So currently we have roll as X, pitch as Y and yaw as Z, but they should be roll as Z, X as pitch and Y as yaw. So the second letter of these variables just have to be changed to the appropriate ones?

**Comment by PichiBeta** [comment]
Also, I noticed that the same naming conventions are being applied in lines 964-989. Should those be fixed as well?

**Comment by PichiBeta** [comment]
the way i did the renaming was simply by renaming the variables within the scope of the functions. For example, cr (which should have been cosine pitch) I first renamed it into c_pitch so that there were no naming collisions with other variables within the function; I then repeated this process for all variables and finally, once all variables were correctly accounted for, I changed all names from c_pitch to cp, s_pitch to sp and so on. The renaming was done individually for each function so that no other variables outside of this known issue were changed. 
This can also be seen easily in the file changes if you use split diff view :)

Also, I just resolved the changes mentioned in the PR, I think all name changes would be accounted for now

**Comment by FatalistError** [comment]
> Hey! I want to work on this issue. I do want to clarify so I make sure I understand this properly though: the name of the variables are wrong and have to be fixed. So currently we have roll as X, pitch as Y and yaw as Z, but they should be roll as Z, X as pitch and Y as yaw. So the second letter of these variables just have to be changed to the appropriate ones?

yes. But i'd recommend something like cRoll or sRoll etc, may make things more obvious.

**Comment by FatalistError** [comment]
actually i'd also recommend this function:
https://github.com/minetest/minetest/blob/bca44574d511ed49d50c4eaf8f5927063f7d40ed/src/util/numeric.cpp#L190
be renamed using those conventions, as it has similar problems, though not as counterintuitive
