### ISSUE TITLE
Erratic lighting regression

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#15212]
See https://forum.minetest.net/viewtopic.php?p=439532:
~~(wsor4035 edit) regression pr: https://github.com/minetest/minetest/pull/14610~~

> Under both OpenGL drivers, Mineclonia's chests and mobs have been displayed with very erratic lighting, which alternates between complete darkness and full (14/14) brightness, ever since the visual effects branch was merged. Chest visuals are implemented as objects.
> 
> In the spirit of a picture being worth a thousand words, I've attached screenshots of both extremes.
> 
![screenshot_20240930_180027](https://github.com/user-attachments/assets/433426f0-b9e9-4b4d-a23b-90109127b9db)
![screenshot_20240930_180023](https://github.com/user-attachments/assets/e98f4317-2a12-4b0b-b750-2e8206a3b6dc)

**Comment by sfan5** [comment]
I can reproduce this with the mobs from Farlands Reloaded.
All models of the same type are always lighted identically it appears.

@GefullteTaubenbrust2 ping

**Comment by GefullteTaubenbrust2** [comment]
I'll look into it. In general some of the features need polishing, so I will probably do a PR just for that soon...

**Comment by GefullteTaubenbrust2** [comment]
Hm... So I was able to reproduce the bug, but it persisted even after reverting the changes from the PR in GitHub... So most likely the issue is not related to #14610.

**Comment by sfan5** [comment]
did a bisect:
```
70e169f1652ecd68d5f32d627d253ec531225183 is the first bad commit
commit 70e169f1652ecd68d5f32d627d253ec531225183 (HEAD)
Author: grorp <gregor.parzefall@posteo.de>
Date:   Wed Sep 18 12:18:28 2024 +0200

    Drop fixed pipeline lighting stuff (#15165)

```

**Comment by SmallJoker** [comment]
Can confirm the issue with shaders enabled. Shaders disabled does render the chests correctly.

**Comment by appgurueu** [comment]
> EDIT: Might this be a material number issue?

If it only appears with shaders enabled, yes. The "material type enum can be a material type or a shader material ID" hack has tripped me over in the past like this. However according to @GefullteTaubenbrust2 this is also reproducible with shaders disabled:

>  I suppose that makes sense as the issue persists even without shaders and I changed very little that isn't shader-related...

**Comment by GefullteTaubenbrust2** [comment]
> However according to @GefullteTaubenbrust2 this is also reproducible with shaders disabled:

Yes it is. Although the bug is very weird and sometimes refuses to happen. I thought at several times I had found the cause only for it to happen again... It definitely happened even with shaders disabled though, numerous times.
