### ISSUE TITLE
Progress bar periodically jumps backwards with Intel HD 4000 IGP

### ISSUE THREAD

**Issue by nyuszika7h** [minetest/minetest#1522]
OS: Windows 8.1
Minetest: 0.4.10-eec456b (sfan5's build)

When Minetest is connecting to a server, the progress bar jumps backwards a lot when using the Intel HD 4000 IGP. The issue doesn't appear with  NVIDIA GeForce GT 740M.

**Comment by paramat** [comment]
Now fixed? @nyuszika7h

**Comment by est31** [comment]
Yes the progress bar had multiple changes since, see 0db73bd83effa7dbc0f28862c8157e0283d24e44 for most of the changes and e4f7c92cff0badd6c40b47bd90b1fc1b35456a1a as small improvement on that for example.

Reopen if you still can experience the behaviour.
