### ISSUE TITLE
Make bloom parameters game-controlled

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15229]
### Problem

Unlike other visual effects (volumetric lighting, dynamic shadows, saturation), bloom is completely client-controlled at the moment. Allowing the server to adjust bloom parameters (strength etc.) would...

1. make bloom consistent with other visual effects
2. allow for nice effects triggered by status effects - e.g. extreme bloom after drug use or sleep deprivation

### Solutions

Make bloom parameters server-controlled via `player:set_lighting`.

### Additional context

I haven't heard anyone complaining about this, so maybe it's not actually needed/desired? What do others think?

**Comment by sfan5** [comment]
Obvious :+1: 
When adding new features we should pay attention to having features be server-controlled.
