### ISSUE TITLE
[Feature request]: `damage_groups` for nodes.

### ISSUE THREAD

**Issue by alek13** [minetest/minetest#15223]
### Problem

In game we can have:
- different nodes: fire/lava, toxic water.
- different damages: by fire, by toxic.
- different armor: from fire, from toxic.  (`armor_groups`)

So, for tools we have `tool_capabilities.damage_groups`, and this damage + armor handled by engine.
But for nodes we have only `damage_per_second` and no way to specify the damage type (by fire, by toxic -- `damage_groups`).

### Solutions

I think, the simplest way: move `tool_capabilities.damage_groups` from  "handling by tool" in some parent class or similar.
so that nodes have the same ability to customize damage.

### Alternatives

Or just `damage_groups` in `NodeDefinition` (without `tool_capabilities. ...`)

**Comment by appgurueu** [comment]
Another alternative: If you really need the customizability, just implement your own node damage. Use an ABM, or node timers, or a global step and track the nodes yourself, and deal damage by punching players.

**Comment by alek13** [comment]
@appgurueu 
We already implement our own handling of this. (We use `on_hpchange`)
Using global step is not an option at all, any additional global step function will load the server.
As for now, MT has no so much features, that there are a lot of different global step functions for a lot of different features in any game.
Its ok for now, because the project is growing and developing.
Thanks for you all very much!!!
MT Team pleases (makes happy) us with new features with each new release.
Its cool. Thanks you all again.

But it's not just about how we can to implement this.
It will be awesome, if same [`Entity damage mechanism`](https://api.minetest.net/entity-damage-mechanism/#entity-damage-mechanism) will works for nodes.
And most of all / most importantly this:
> Client predicts damage based on damage groups.

**Comment by appgurueu** [comment]
> Thanks you all again.

Glad you appreciate it :)

---

> Using global step is not an option at all, any additional global step function will load the server.

Globalsteps per se are not a problem so long as the code running inside them is efficient. Which it can be if you have e.g. a table of node positions and your nodes are sufficiently sparse. But as said node timers or ABMs are also options. Though forgive me for missing the obvious: You'll just want to iterate over players rather than nodes and check whether they are standing in a damaging node.

I would really recommend writing your own implementation of this; it allows for it to be much more game specific and frankly, the engine implementation is (IMO) a bit crappy.

> And most of all / most importantly this:
> 
> > Client predicts damage based on damage groups.

I don't think this is currently client predicted (just checked, doesn't seem to be). It also doesn't matter very much for something that is roughly once per second.

**Comment by alek13** [comment]
> I would really recommend writing your own implementation of this;

as I already [said](https://github.com/minetest/minetest/issues/15223#issuecomment-2389974110):

> We already implement our own handling of this. (We use `on_hpchange`)

----

> I don't think this is currently client predicted (just checked, doesn't seem to be).

hmm... [Documentation](https://github.com/minetest/minetest/blob/3eef1ca28f05b13adf71b2486d2650ef125239df/doc/lua_api.md?plain=1#L2471) says:

> Client predicts damage based on damage groups.

is it just mistake ?

**Comment by sfence** [comment]
Duplication of #8265 ?

**Comment by appgurueu** [comment]
> as I already [said](https://github.com/minetest/minetest/issues/15223#issuecomment-2389974110):
> 
> > We already implement our own handling of this. (We use `on_hpchange`)

I think you're misunderstanding my suggestion. I really mean using a globalstep looping over players so you don't get bogged down by engine limitations. I've done this in the past e.g. for spikes.

Hooking `on_hpchange` and replacing the node damage with a punch definitely also works if this is all you need though.

> hmm... [Documentation](https://github.com/minetest/minetest/blob/3eef1ca28f05b13adf71b2486d2650ef125239df/doc/lua_api.md?plain=1#L2471) says:
> 
> > Client predicts damage based on damage groups.
> 
> is it just mistake ?

This refers to punches. It could be more clear.

**Comment by alek13** [comment]
> Duplication of #8265 ?

Exactly! Thnx!
