### ISSUE TITLE
Mainmenu should offer to visit the server website (`server_url`)

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#15237]
Right now any server_url you set is largely pointless because only people visiting the server list [in the browser](https://servers.minetest.net/) will ever see it.

two quick mockups:
![grafik](https://github.com/user-attachments/assets/21bcbd23-e08c-4579-a0bb-6eef2dc53f39)
![grafik](https://github.com/user-attachments/assets/d3738d1e-aef5-4aad-9105-0d7b0779155d)

**Comment by Zughy** [comment]
Maybe the planet is a better fit than the chain links. The blue link is hardly readable

**Comment by Desour** [comment]
I'd also prefer a globe over the chain.

The blue text link looks like it would take too much space.

Please also make sure the user can see the link they're opening before clicking, e.g. via a tooltip.

**Comment by rubenwardy** [comment]
> Please also make sure the user can see the link they're opening before clicking, e.g. via a tooltip.

Should reuse the open URL dialog

**Comment by siliconsniffer** [comment]
Might it be an option to have the server url in the dialog from #15425 too?

**Comment by appgurueu** [comment]
> Might it be an option to have the server url in the dialog from #15425 too?

I remember suggesting the URL be part of a "more info" dialog, but it seems some people might prefer it being directly accessible via a single click rather than taking two clicks.

**Comment by siliconsniffer** [comment]
> people might prefer it being directly accessible via a single click rather than taking two clicks.

Maybe even three if we would reuse the open URL dialog in the info dialog, that would be quite annoying.
I personally like the idea of a button (with a globe symbol) but I don't know if it might get too busy if we add another button.

**Comment by siliconsniffer** [comment]
Hey there,
Thought I'd give a quick update:
I am working on it, so far I am only missing an icon for the button.
There is also still a bug in the url dialog which I am trying to figure out.

![image](https://github.com/user-attachments/assets/d956f8ce-4436-4c3d-8b2b-c464b3b5a360)
![image](https://github.com/user-attachments/assets/7458de62-4051-45f6-9fa0-8127a3a8f41d)

**Comment by siliconsniffer** [comment]
Thought I'd give a quick update:
So far I am only missing an icon for the button so if anyone here feels artistic enough, feel free to suggestion something.
There is also still a but in the url dialog which I am trying to figure out but I am confident that this will get resolved.
