### ISSUE TITLE
Improve client-side localization system, possibly using ini-files

### ISSUE THREAD

**Issue by fnetX** [minetest/minetest#15245]
### Problem

The translation format used for Minetest is a custom format that is only used in Minetest. The issues described in https://github.com/minetest/minetest/issues/7290 apply.

Additionally, my proposal focuses on being minimum-effort, both in terms of the implementation (although this is mostly a guess, because I didn't take a look at the Minetest code) and the effort for mod creators (aiming for backwards compatibility and a minimum-effort migration).

I got affected by this problem by setting up Weblate translations for several Minetest mods at https://translate.codeberg.org/projects/zughy-friends-minetest/ and running into several compatibility issues with the Minetest format and the expectations of software. [Some notes exist about the setup](https://codeberg.org/Codeberg/translathon-2024/src/branch/main/HOWTO_Weblate_for_Minetest_mods.md), but many problems and workarounds remain.

I am aware of https://github.com/minetest/minetest/pull/14726, but this change seems to be WIP for a rather long time. Without dismissing the effort invested into it, I am making this proposal for your consideration. It it meant to **offer a simpler alternative**, not to void the efforts. Depending on the state of the linked PR, it might be worth considering my proposal as a low-hanging fruit, but I'm fine closing this issue to focus on the other implementation.

### Solutions

The primary issue that prevents the current system from being translatable is that it uses a custom format for mapping English versions to localized counterparts. Certain issues arise, such as special characters (e.g. `'` or trailing spaces in source strings). However, the syntax is rather simple with it effectively being a `source=translation` mapping.

The format is close to the [ini config file format](https://en.wikipedia.org/wiki/INI_file) which is at least supported by [Weblate](https://docs.weblate.org/en/weblate-5.7.2/formats/ini.html) and from my experience commonly available (I can confirm it is used by Forgejo, some other projects of mine, and all translation libraries and frameworks I have checked out so far).

Currently, the workflow for getting a translation from a mod[^1] seems to be somewhat like this:

~~~lua
local S = minetest.get_translator("mymod")
[...]
    S('Some string that needs to be translated')
~~~

It maps the string to be translated to the translated version, or prints it literally in the case of English.

I suppose to modify this workflow slightly:

Instead of only looking up translated versions, the given string is considered a "key" and looked up in an English file (e.g. mymod.en.tr), too.

This can provide backwards compatibility with any existing mod, because

- if the modname.en.tr file does not exist, the string is printed literally (current behaviour)
- if the key does not exist in the file, the string is printed literally (current behaviour)
- the only remaining challenge is trailing and leading whitespace (see below for details)

But it will allow for a more common translation workflow based on key-value mapping:

~~~lua
local S = minetest.get_translator("mymod")
[...]
    S('some_string')
~~~

and the file `modname.en.tr` resolves it:

~~~ini
some_string=Some string that needs to be translated
~~~

From here, software like Weblate can conveniently take over. It will treat the base language as the source know to map the strings based on the same key. Language files would then contain

~~~ini
some_string=The translation of some string into some language
~~~

<details><summary>An additional example for backwards compatibility</summary>

~~~lua
local S = minetest.get_translator("mymod")
[...]
    S('Some existing string in the software')
    S('Another existing string in the software')
    S('new_string')
~~~

and mymod.en.tr:

~~~ini
new_string=The actual text of the new string
Another existing string in the software=The text of the existing string can be modified easily now, as a side-effect!
~~~

</details>

The only challenge regarding backwards-compatibility I can currently think of is leading and trailing whitespace. For convenient ini support, keys should be allowed to have trailing space, e.g. both lines in

~~~ini
key = value
key=value
~~~

should map "key" to "value", while it currently maps "key " to " value". It should be considered for the sake of compatibility. There are two options:

- provide a new interface for mods to opt-in to the new format. It will be backwards-compatible for most and an easy migration (modify `get_translator` to `get_ini_translator` for example), but it would allow for guaranteed backwards-compatibility for mods that use trailing whitespace
- look up the string literally first, then look it up again, ignoring potential whitespace (note that this will need to be kept forever and the additional lookup might add an undesired performance penalty long-term)

<details><summary>an example for potential compatibility issue</summary>

Consider the following code:

~~~lua
local S = minetest.get_translator("mymod")
[...]
    S('Players:') # used in a menu heading, for example
    S('Players: ') .. list # would result in "Players: a, b, c, d" for example
~~~

the mod might not have opted in for the new format, but there is a translation file that could look like this (note that translations differ for some reason - could be on purpose:

~~~ini
Players: =Joueurs: 
Players:=Les jouers:
~~~

The new lookup (assuming it is a first-match system) might always return the first (potentially wrong) string.

</details>

[^1]: I am basing this assumption on https://dev.minetest.net/Translation and [reading source code](https://gitlab.com/zughy-friends-minetest/arena_lib/-/blob/master/src/nodes.lua?ref_type=heads)

### Alternatives

Finishing https://github.com/minetest/minetest/pull/14726 addresses many issues, except for backwards compatibility for existing mods.

Ini files can commonly contain section headers. Currently, I'm speaking of keeping it a ".tr" format but adhering to the ini format to increase compatibility with tooling that can work with ini files.
Adding full ini-file support could have the additional benefit of having an easy way to group strings into categories. The following additional changes would need to be made:

- the format does not expect a root category (some parsers / libraries do not work with ini files that do not start with `[xyz]` where `xyz` can be an arbitrary name for a category
- the system allows for subheadings in the format of `[something]` or `[some.thing]` with potentially even more levels
- looking up the string `some.thing.example` would look up the string literally, find it in `[some]` as `thing.example` or in `[some.thing]` as `example`.

**Comment by sfan5** [comment]
I think an ini-based system is worse and with the gettext PR now merged, we don't need an alternative.

**Comment by fnetX** [comment]
Yeah, since the better system is now available, there is no need for this. Thank you all for working on it and for finishing the gettext PR.
