### ISSUE TITLE
Clicking on "Mapgen Fractal" in the settings menu causes an error

### ISSUE THREAD

**Issue by birdlover32767** [minetest/minetest#15242]
### Minetest version

```true
Minetest 5.9.1 (Windows)
Using LuaJIT 2.1.1706185428
Built by Clang 17.0
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

WIN32

### Operating system and version

Microsoft Windows 10 Pro Build 19045

### CPU model

Not needed

### Summary

The title. Minetest doesn't crash completely, but the error causes an error message to show up.
![Capture](https://github.com/user-attachments/assets/469335e8-d455-4e55-bfb6-a3478c5d9f8b)

### Steps to reproduce

1. Go to the settings.
2. Scroll down until you find "Mapgen Fractals".
3. Click on "Mapgen Fractals".

**Comment by sfan5** [comment]
Can't reproduce on 5.10.0-dev. Was probably fixed in the meantime.

**Comment by birdlover32767** [comment]
well, i can't even see a mapgen part in 5.10.0-dev, closing

remindme: check the dev version
