### ISSUE TITLE
When is node inventory nil?

### ISSUE THREAD

**Issue by hlqkj** [minetest/minetest#15243]
According to the [API docs](https://github.com/minetest/minetest/blob/master/doc/lua_api.md?plain=1#L6541) the `minetest.get_inventory()` function always returns an `InvRef`.

However, I saw that function being used in the following flavour, to check whether a position is occupied by any node with an inventory:

```lua
if minetest.get_inventory({type = "node", pos = pos}) then
	minetest.chat_send_player(name, "Cannot place protector.")
	return
end
```

That method sort-of works most of the times, and indeed, in the code below I see that this API function can actually return `nil` - although this is undocumented behaviour:

https://github.com/minetest/minetest/blob/1037ee2a55a4f94926c48aebba6dade7d8dcdb3b/src/script/lua_api/l_inventory.cpp#L466-L477

The question is: when will a position be considered to have an inventory, or not have it? (As I assume the returning of `nil` represent a "not have" whereas returning an `InvRef` represents a "have one, that *may* be empty".)

I am seeing actual cases of nodes which don't have inventories anymore (but *had* them before, being occupied by e.g. boneboxes that have since been replaced) that still retain an empty inventory and have that function returning an `InvRef`, whereas other nodes just return `nil` instead.

This leads to me wondering if *not having* an inventory shall be considered the same as having a completely empty one or not, and if not, why replacing a node at a position don't erase that position's previous inventory existence.

**Comment by SmallJoker** [comment]
Unloaded mapblocks, hence contained nodes do not have an inventory.
I suppose the documentation is flawed then.

**Comment by hlqkj** [comment]
Thanks for your reply, but I have to add that I also got `nil` in (loaded) air nodes.

**Comment by appgurueu** [comment]
Code in question:

https://github.com/minetest/minetest/blob/1037ee2a55a4f94926c48aebba6dade7d8dcdb3b/src/server/serverinventorymgr.cpp#L51-L57

Note that if `meta` is non-null, then the inventory is always non-null too (see `nodemetadata.cpp`). So if you get `nil`, either you're calling it at load time (should probably throw an error instead tbh, but it's too late to change that), or the meta is `nil`. That can happen if a node has no meta at all.

https://github.com/minetest/minetest/blob/1037ee2a55a4f94926c48aebba6dade7d8dcdb3b/src/map.cpp#L497-L514

> This leads to me wondering if not having an inventory shall be considered the same as having a completely empty one or not

This sounds like the sanest choice to me.

> and if not, why replacing a node at a position don't erase that position's previous inventory existence.

How are you replacing the node? I believe that using `set_node` should clear the inventory, whereas `swap_node` won't touch the meta, as is documented.

**Comment by hlqkj** [comment]
> So if you get nil, either you're calling it at load time (should probably throw an error instead tbh, but it's too late to change that), or the meta is nil. That can happen if a node has no meta at all.

They were nodes with no meta at all.

> This sounds like the sanest choice to me.

For what is worth, I agree, and suggest that an `InvRef` be always be returned, perhaps adding an inventory-wise (that is, not asking for a listname) `is_empty()` utility function to it. I realize it would break some existing mods which relied on the (undocumented) `nil` behaviour, though...

> How are you replacing the node? I believe that using set_node should clear the inventory, whereas swap_node won't touch the meta, as is documented.

Here I am not sure: the node was into a liquid which has is `liquid_renewable` property set to true. So I assume the node was set by the engine internals, which I don't know very well. I would assume this is the same as using `set_node` from the Lua side?

https://github.com/minetest/minetest/blob/1037ee2a55a4f94926c48aebba6dade7d8dcdb3b/src/servermap.cpp#L1125

**Comment by rubenwardy** [comment]
How are you supposed to make an inventory if the InvRef is nil? I assumed that it would only return nil for unloaded nodes, and it would always return an InvRef for loaded nodes. "creating" an inventory would then just be setting a non-zero length list

**Comment by hlqkj** [comment]
I did some more tests today: to add more inconsistency, a position returning `nil` to a first call to `minetest.get_inventory()` will subsequently return a valid `InvRef` if and after `minetest.get_meta()` gets called.
