### ISSUE TITLE
Formspec: cursor becomes as small as text when hovering over field and stays small until the dialog is closed

### ISSUE THREAD

**Issue by mruncreative** [minetest/minetest#15252]
### Minetest version

```true
5.9.1
```

### Operating system and version

Linux/X11

### Summary

Formspec: cursor becomes as small as text when hovering over field and stays small until the dialog is closed.
It's annoying to be stuck with a tiny cursor.

### Steps to reproduce

Hover search field in MTG creative mode.

or

Hover any fields in the main menu settings screen.

**Comment by Desour** [comment]
You mean your cursor changes size? Screenshot would be nice.

If you hover text, e.g. a field formspec element, the cursor becomes an i beam.
Do you use some unusual cursor configuration?

**Comment by mruncreative** [comment]
Yes and the text cursor is smaller than in other applications and afterwards the normal pointer is small too.
No, I don't have any unusual configuration but now that you mention it: Cursors can provide multiple resolutions and the size it changes to (only while hovering the minetest window) matches the smallest cursor size provided by the cursor theme. The game could be making wrong assumptions about how cursors work.

**Comment by mruncreative** [comment]
Reading up on this it seems like a general X11 issue. Feel free to close it. Can't take on the entire world at once. Eventually my DE will transition to Wayland too.

**Comment by appgurueu** [comment]
> It's still in 5.10

(SDL was reverted again for 5.10, hopefully we'll have it for 5.11 - that requires us to prioritize the corresponding PR(s?)...)

If you can compile current master (or grab CI builds, or PPA daily builds, or something like that), I would encourage you to try it.
