### ISSUE TITLE
Integers overflow when parsing JSON on 32-bit

### ISSUE THREAD

**Issue by zmv7** [minetest/minetest#15277]
### Minetest version

```true
Minetest 5.9.1 (Linux)
Using LuaJIT 2.1.0-beta3
Built by GCC 12.2
Running on Linux/5.15.150 armv7l
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

### Operating system and version

OpenWRT 23.05.3 + debian bookworm chroot

### CPU model

MT7623 4 cores 1.3GHz ARMv7

### Summary

I noticed strange behaviour of parsing json in the telegram mod - there are big integers. They are changing during the parsing process. The screenshot with quick test represents it.

![parse_json_issue](https://github.com/user-attachments/assets/d74460fa-5b8a-40e0-8532-9dfff23c5b10)

I can't reproduce it on my PC with x86_64 CPU, same minetest version (5.9.1)

### Steps to reproduce

* Get 32-bit (especially armv7) hardware
* Execute `dump(core.parse_json("{\"id\":-1234567891011}"))` using worldedit's `//lua` / snippets / whatever and look at the output.

**Comment by zmv7** [comment]
I installed lua-cjson on this server and it is working fine
```
> print(cjson.decode("{\"id\":-1234567891011}").id)
-1234567891011
```

**Comment by appgurueu** [comment]
Observations: (1) `-2^53 <  -1234567891011`: This number can be represented by a double; (2) `(int) -1234567891011 == -1912277059`, so something is probably casting this to `int` when it should stay a 64-bit int.

**Comment by sfan5** [comment]
> I could imagine that `lua_Integer` is 32-bit on a 32-bit platform,

indeed, it is `ptrdiff_t` which is basically the pointer width but signed.

> `//l error(dump(core.parse_json("{\"id\":-1234567891011}")))`

btw: this is clever, but you can just use `//l =core.parse_json("{\"id\":-1234567891011}"`

**Comment by zmv7** [comment]
> Observations: (1) `-2^53 < -1234567891011`: This number can be represented by a double; (2) `(int) -1234567891011 == -1912277059`, so something is probably casting this to `int` when it should stay a 64-bit int.
> 
> See also: [8ae8c16](https://github.com/minetest/minetest/commit/8ae8c1600a66c724565ce7a70e0e5f542f12e38e). I could imagine that `lua_Integer` is 32-bit on a 32-bit platform, so the call to `lua_pushinteger` casts and loses bits. We should always push numbers as doubles:
> 
> ```diff
> diff --git a/src/script/common/c_content.cpp b/src/script/common/c_content.cpp
> index 2e5873bbf..2a18ccd11 100644
> --- a/src/script/common/c_content.cpp
> +++ b/src/script/common/c_content.cpp
> @@ -2087,11 +2087,7 @@ static bool push_json_value_helper(lua_State *L, const Json::Value &value,
>  			lua_pushvalue(L, nullindex);
>  			break;
>  		case Json::intValue:
> -			lua_pushinteger(L, value.asLargestInt());
> -			break;
>  		case Json::uintValue:
> -			lua_pushinteger(L, value.asLargestUInt());
> -			break;
>  		case Json::realValue:
>  			lua_pushnumber(L, value.asDouble());
>  			break;
> ```

Seems like this patch works
```
Issued command: //l =core.parse_json("{\"id\":-1234567891011}")
WorldEdit -!- code successfully executed, returned {
        id = -1234567891011
}
```
