### ISSUE TITLE
Bad UX when upgrading to 5.10 with shaders disabled

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15270]
### Minetest version

5.10.0-dev

### Summary

Since #15210, the `enable_shaders` setting is inside advanced settings (hidden by default) and enabling shaders results in a warning. +1 for that.

However, now imagine someone who has `enable_shaders = false` in their minetest.conf upgrades from 5.9.1 to 5.10.0. If they're a normal non-tech-savvy person, ...

1. ... they will be confused because the option to enable shaders again is suddenly gone from the settings, and with it the option to enable all the fancy effects.
2. ... they may not be able find out how to enable shaders again.
3. ... they may not even notice they're missing something.
4. ... they'll likely never see the warning (#15209)

### Solutions

Fixing #15209 wouldn't fully solve the bad UX problem. The user would still need to know about the advanced settings section and manually enable shaders again.

#### Idea 1

Move the `enable_shaders` setting back to the normal settings ("Effects" section) when it's false, only hide it in the advanced settings when it's true

#### Idea 2

Here's a mockup:
![shaders disabled mockup](https://github.com/user-attachments/assets/eaad88bd-cc8b-49ab-9440-7b1199a075cc)

### Steps to reproduce

1. Install Minetest 5.9.1
2. Disable shaders
3. Upgrade to Minetest 5.10.0-dev

**Comment by sfan5** [comment]
I like idea 2.

**Comment by Zughy** [comment]
+1 for n°2
