### ISSUE TITLE
Adding "Problem Solver" Role on github issues.

### ISSUE THREAD

**Issue by SaiPanneerselvam** [minetest/minetest#15285]
### Problem

its hard to get answers if people post offtopic answers. 

### Solutions

If a person answers a question correctly, that person could possibly get a role here called "Problem Solver", showing that they have the expertise to answer a basic question

**Comment by rubenwardy** [comment]
Hi, our github issues aren't intended as a place to ask questions. You should ask questions on the forums or another community place https://www.minetest.net/get-involved/
