### ISSUE TITLE
Player getting stuck inside block

### ISSUE THREAD

**Issue by Maikile** [minetest/minetest#15291]
##### MultiCraft version
```
V2.0.8
```

##### OS / Hardware
Operating system: Android
CPU: Snapdragon 8 gen 2 Mobile Platform

GPU model:
OpenGL version:

##### Summary
Jumping and building two blocks underneath the player quickly after the jump results in the player being inside the second built block
##### Steps to reproduce
Have at least two buildable block in your inventory, jump and quickly place the two blocks underneath the player, which will result in the player being inside the second built block

**Comment by SmallJoker** [comment]
Repost of #15282, which is also a duplicate. Please only report Minetest issues in the Minetest repo.
