### ISSUE TITLE
minetest get (intentionally?) SIGKILLed after three SIGTERMs

### ISSUE THREAD

**Issue by RonnyBarthmann** [minetest/minetest#15298]
### Minetest version

```true
minetest 5.9
compiled from source
```

### Operating system and version

debian 12 & 13

### CPU model

AMD Ryzen 2200U

### GPU model

AMD Ryzen 2200U

### Active renderer

server only

### Summary

it seams that minetest is intentionally killed after three SIGTERMs which is ... wtf

since all files (sqlite) can be become corrupted

what i wrote about it in the forum:
```
my approach would be different:
don't just set g_killed to true, but count it up
and then perform different actions depending on the value.
for:
1: normal shutdown (with the message that minetest is shutting down because of SIGTERM)
2: do nothing but warn that another SIGTERM will cause a "harder shutdown"
3: simply shut down the LUA VM and then unmount all SQLite files. (no damage should occur)
4: again, do nothing. but this time: warn that another SIGTERM will cause a "even harder shutdown"
5: kill all hanging LUA VMs and other threads and then unmount the SQLite files forcefully
6: display a message that minetest is hanging and that you should kill it with SIGKILL
7: set g_killed to 5 so that the next SIGTERM shows the message again (see 6)
```
source: https://forum.minetest.net/viewtopic.php?p=439972#p439972

### Steps to reproduce

issue a comman din minetest where minetest needs a huge amount of time ... e.g. "/emergeblocks"

send minetest a SIGTERM three times in a row

**Comment by RonnyBarthmann** [comment]
file of Interest: https://github.com/minetest/minetest/blob/master/src/porting.cpp

**Comment by RonnyBarthmann** [comment]
but wouldn't it be better to just do nothing?
I mean, SIGKILL is responsible for killing processes
I just don't think it's good that you should risk data loss with a "friendly" SIGTERM because it also starts "killing processes"

**Comment by Desour** [comment]
>Yes, this is intentional.

Is it also intentional that it's 3 and not 2?

>since all files (sqlite) can be become corrupted

FYI, sqlite files shouldn't be corrupted by this. Database systems provide robustness against crashes.

**Comment by Jookia** [comment]
The signal handler code is not signal or thread safe so maybe that's having a bit of an effect?

**Comment by RonnyBarthmann** [comment]
> > Yes, this is intentional.
> 
> Is it also intentional that it's 3 and not 2?

right ?

such an odd number ...

**Comment by sfan5** [comment]
> Is it also intentional that it's 3 and not 2?

dunno
