### ISSUE TITLE
GitLab container minetest/server has not been updated since 5.7.0

### ISSUE THREAD

**Issue by MarSik** [minetest/minetest#15297]
### Minetest version

```true
5.7.0 - 5.9.1

This is a release process related issue.
```

### Operating system and version

Docker

### Summary

The container builds seem to be disabled or misconfigured. The last update to the container was the 5.7.0 release a year ago.

### Steps to reproduce

Please see the latest tags here https://gitlab.com/minetest/minetest/container_registry/314118

**Comment by wsor4035** [comment]
gitlab isnt used anymore, docker images are made here since https://github.com/minetest/minetest/pull/14230

reference: https://github.com/mt-mods/dreambuilder_game/blob/master/.github/workflows/test.yml#L13-L16

**Comment by MarSik** [comment]
Thanks! It might be a good idea to add this somewhere to the documentation. Because I could not find it (even the old gitlab was hard to find.. but at least there was the Deploy / Container registry link directly in the repo)
