### ISSUE TITLE
A better-fitting ascii banner

### ISSUE THREAD

**Issue by Gamer-Kold** [minetest/minetest#15307]
### Problem

This is the current ascii banner visible in the terminal when you start up the game:
```
         __.               __.                 __.  
  _____ |__| ____   _____ /  |_  _____  _____ /  |_ 
 /     \|  |/    \ /  __ \    _\/  __ \/   __>    _\
|  Y Y  \  |   |  \   ___/|  | |   ___/\___  \|  |  
|__|_|  /  |___|  /\______>  |  \______>_____/|  |  
      \/ \/     \/         \/                  \/ 
```

This will be replaced by a luanti version in #15294

```
.__                       __  .__ 
|  |  __ _______    _____/  |_|__|
|  | |  |  \__  \  /    \   __\  |
|  |_|  |  // __ \|   |  \  | |  |
|____/____/(____  /___|  /__| |__|
                \/     \/         
```
My problem with this is that it doesn't fit with Luanti's image at all. The font is very cool and edgy, more fit for something with personality of DOOM rather than Luanti. 

### Solutions

I believe that Luanti should use a more neutral "font" for its ascii banner. It doesn't have to be completely devoid of personality but something more fitting than the current one. 

Here's my proposal:
```
  _           _      _    _______     _______     _______     _______  
 / |         / |    | |  /   _/  \   /   _/  \   /   _/  \   /   \_  \
|  |        |  |    | | |    _  _ | |         | |__     __| |__     __|
| /|        |  |    | | |/  / \  \| |/  ____  |    |   |       |   |
|  |        |  |    | | |   \_/   | |  |    | |    |\_ |       | _ |
|  |        |_/|    | | |_/ ____  | |  |    | |    |  _|       |  \|
|_/|_______ |  |____| | |  |    | | |_/|    | |    | / |     __|   |__
|     /   / |    _/   | |  |    | | |  |    | |    |   |    |       \ |
 \_______/   \_______/   \_|    |_|  \_|    |_|     \_/      \_______/

```

With an alternate T and I
```
  _           _      _    _______     _______     _______    ___
 / |         / |    | |  /   _/  \   /   _/  \   /   _/  \  |   | 
|  |        |  |    | | |    _  _ | |         | |__    ___| |_  |
| /|        |  |    | | |/  / \  \| |/  ____  |    |  |     |   |
|  |        |  |    | | |   \_/   | |  |    | |    |  |     | _ |
|  |        |_/|    | | |_/ ____  | |  |    | |    |  |     |  \|
|_/|_______ |  |____| | |  |    | | |_/|    | |    |  |     | _ |
|     /   / |    _/   | |  |    | | |  |    | |    |  |     |/  |
 \_______/   \_______/   \_|    |_|  \_|    |_|     \_|     '___'

```

These are hand-made.

### Alternatives

A more minimal figlet font could be chosen. This was one of the alternatives proposed in the PR and I think it fits much better than the current font.

```
 _                   _   _ 
| |_   _  __ _ _ __ | |_(_)
| | | | |/ _` | '_ \| __| |
| | |_| | (_| | | | | |_| |
|_|\__,_|\__,_|_| |_|\__|_|
```

It's very minimal and neutral. I also like the 3D-ness of:
```

██╗     ██╗   ██╗ █████╗ ███╗   ██╗████████╗██╗
██║     ██║   ██║██╔══██╗████╗  ██║╚══██╔══╝██║
██║     ██║   ██║███████║██╔██╗ ██║   ██║   ██║
██║     ██║   ██║██╔══██║██║╚██╗██║   ██║   ██║
███████╗╚██████╔╝██║  ██║██║ ╚████║   ██║   ██║
╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═╝
```
I want to add a similar effect to my logo but I haven't had the time to, yet. Despite this, I still prefer mine (with obvious bias).

There's also the option of removing the banner entirely, but I wouldn't advocate for that.

**Comment by HybridDog** [comment]
Instead of the program name, it could also show ASCII art of the logo.

**Comment by SwissalpS** [comment]
I'm fine with the DOOM-like one. I also prefer the minimal one over the other proposals.

**Comment by DustyBagel** [comment]
> It's worth pointing out that the box/line drawing characters of the "3D-ness" one are liable to cause issues on some terminals. Our safest bet is to stick to actual printable ASCII only.

How so? I don't know a lot about this kind of stuff so I am really interested on why that could be.

**Comment by appgurueu** [comment]
I think the minimal one is emerging as a pretty clear winner. We can probably move forward with that.

ASCII art of the logo is also popular, albeit less so, and I'm doubtful of whether that will look good in practice as there is no concrete proposal yet.

> How so? I don't know a lot about this kind of stuff so I am really interested on why that could be.

Many things can go wrong. ASCII is about as basic as it gets. Essentially every system we support supports ASCII. When unicode box drawing characters are used, you require more things to work. First of all the Unicode encoding (UTF-8? UTF-16? WTF-16?). Second you need a font supporting these characters, etc.

**Comment by Gamer-Kold** [comment]
```
  _                       _   _ 
 | |                     | | (_)
 | |    _   _  __ _ _ __ | |_ _ 
 | |   | | | |/ _` | '_ \| __| |
 | |___| |_| | (_| | | | | |_| |
 |______\__,_|\__,_|_| |_|\__|_|                          
```

I apologize for not bringing it up sooner but I realize now that I did not capitalize the L in this.
So here's an alternative keeping that in mind. 

(here also an all-caps version; mostly for my own curiosity)
```
  _     _    _         _   _ _______ _____ 
 | |   | |  | |  /\   | \ | |__   __|_   _|
 | |   | |  | | /  \  |  \| |  | |    | |  
 | |   | |  | |/ /\ \ | . ` |  | |    | |  
 | |___| |__| / ____ \| |\  |  | |   _| |_ 
 |______\____/_/    \_\_| \_|  |_|  |_____|
```

**Comment by SwissalpS** [comment]
> ```
>   _                       _   _ 
>  | |                     | | (_)
>  | |    _   _  __ _ _ __ | |_ _ 
>  | |   | | | |/ _` | '_ \| __| |
>  | |___| |_| | (_| | | | | |_| |
>  |______\__,_|\__,_|_| |_|\__|_|                          
> ```

I like this a lot more than the all lowercase version in the PR

**Comment by appgurueu** [comment]
I would say I still prefer the all lowercase version, since it gets out of the way more, is more subtle. But we can wait a bit to see what others think.

**Comment by rubenwardy** [comment]
very few users will even see this, it's not worth spending so much time debating it. Just choose something and roll with it

**Comment by SmallJoker** [comment]
Interjecting in the last minute that I like the stylish (although edgy) variant over the Arial-style version. The suggested art is plain boring and could be removed altogether.

As a counter-proposal, game-specific banners could be added by settings (we have multiline settings already). Nobody asked for this, but why not :man_shrugging: .
