### ISSUE TITLE
Be Able to Load Mods Without Restart

### ISSUE THREAD

**Issue by nuclearsubstation** [minetest/minetest#1531]
I'm not exactly sure how this would be done, but it would be a great feature. I've seen many a server owner have to restart a few times just because a mod didn't load correctly.
What I'm suggesting is a command for loading Lua mods from ingame. Such as "/loadmod <name>"
Thoughts?

**Comment by neoascetic** [comment]
Must-have, especially for development purposes

**Comment by paramat** [comment]
Closing with agreement of est31.

**Comment by neoascetic** [comment]
@paramat what does it mean?

**Comment by 0-afflatus** [comment]
Hmm, I think it's bad procedure to close a FR on the basis of (I assume) a private conversation somewhere else. I'd like to see this flagged for possible close and for @est31 to thumb it down on here. @paramat I know you're both phenomenally busy right now, but I don't think it would hurt to allow a little more discussion. Servers are expected to run 24/7 and most Linux users are used to doing live updates, so this isn't a ridiculous idea. I know for practical purposes most MT servers have regular downtime and I'm not sure the gains are worth such a non-trivial change, however I'm more concerned about adopting a clear procedure that allows non-devs to have a full discussion without cluttering things up too much.

**Comment by est31** [comment]
Its a giant project which adds lots of complexity, and the effort to implement it bug-free is not worth the gain.

Also, this issue relies on getting #2513 done (or at least the low level support for it), but that was closed as well, this issue hasn't much more chances either.

**Comment by est31** [comment]
And no, there was no private conversation about this issue, I even explained the reasons to gregorycu in public IRC, you can [read up the logs](http://irc.minetest.ru/minetest-dev/2016-03-31) if you want, but I already summarized the reasons above.

**Comment by paramat** [comment]
Sorry i should have linked to IRC http://irc.minetest.ru/minetest-dev/2016-03-31#i_4570352 and http://irc.minetest.ru/minetest-dev/2016-03-31#i_4570363

**Comment by TheLambdaFunction** [comment]
> And no, there was no private conversation about this issue, I even explained the reasons to gregorycu in public IRC, you can [read up the logs](http://irc.minetest.ru/minetest-dev/2016-03-31) if you want, but I already summarized the reasons above.

It became private as soon as the links stopped working. Anything worth knowing about the discussion should be duped here, otherwise something that was meant to be public is in some way "hidden". At least, that's how it feels IMO

**Comment by rollerozxa** [comment]
irc.minetest.ru has been down for a very long time now. you can change the domain to irc.luanti.org to find anything you'd be looking for, it has all the old IRC logs from that time as far as I'm aware

**Comment by SmallJoker** [comment]
Log links as of 2026, to whom it may concern:

* https://irc.luanti.org/minetest-dev/2016-03-31#i_4570352
* https://irc.luanti.org/minetest-dev/2016-03-31#i_4570363
