### ISSUE TITLE
File Browser messed up with screen scaling.

### ISSUE THREAD

**Issue by GoodClover** [minetest/minetest#15312]
### Summary

The settings menu uses Irrlicht's file browser.

When on 1× screen scaling, it's fine.
![image](https://github.com/user-attachments/assets/c74337e5-410c-452d-b46d-7ad3a27f7413)

With 2× screen scaling, fonts are scaled up and the menu dimensions are doubled, but the buttons and boxes and icons are the same size as 1×, causing this:
![image](https://github.com/user-attachments/assets/9ce92513-b4e0-4bca-add3-fe6afed030d8)

(Interestingly, toggling between screen scaling doesn't change the menu's dimensions, but does change everything else.)

I've never noticed issues with formspecs, they seem to handle scaling fine.
If there are other non-formspec Irrlicht menus, they likely suffer the same issue.

### Steps to reproduce

Have 2× scaling set.
Settings → Graphics → Screen shot folder → Browse

### Minetest version
**Irrlicht device**: SDL/Wayland
**Operating system and version**: Void Linux
**Active renderer**: OpenGL 4.6
```
Minetest 5.10.0-dev (Linux)
Using LuaJIT 2.1.1725453128
Built by GCC 13.2
Running on Linux/6.6.54 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/local/share/minetest"
STATIC_LOCALEDIR="/usr/local/share/locale"
```

**Comment by GoodClover** [comment]
This menu likely needs scrapping and replacing with a formspec at some point :P

**Comment by BoySanic** [comment]
This seems to be the case for a lot of menus. 
For instance, the settings menu (not even just the file selector) has similar behavior.
1.0:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/6f81872c-5fa9-4913-8897-055ae5ce6c81">


2.0:
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/b55cf354-7c9c-4158-bcc2-32e7e917933c">

**Comment by BoySanic** [comment]
This might be a separate issue, and it may be display aspect ratio dependent, but once I raise to gui scale 1.2, anything above that only scales font. There appears to be a maximum size for the gui that the font size doesn't obey.

But, that may be unrelated to your issue and I can split that off if needed

**Comment by sfan5** [comment]
> This menu likely needs scrapping and replacing with a formspec at some point :P

#13512

**Comment by GoodClover** [comment]
> This seems to be the case for a lot of menus.
> For instance, the settings menu (not even just the file selector) has similar behavior.

Actually, you're right.  I just got lucky.
Menu's scaling is derived from window dimensions + screen scale.
Font size from the setting + screen scale.

File Browser is unique in that it's menu scaling ignores screen scale.

**Comment by grorp** [comment]
For the Irrlicht file browser, it's supposed to be deleted and we shouldn't spend any time on it, so this issue should be closed.

For formspec scaling, this is how it works:

- Font size is fixed: font_size setting * gui_scaling setting * OS scaling factor (display density)

- Formspec coordinate size depends on window size: It's proportional to window size with a padding (padding[] formspec element) and gui_scaling setting applied (OS scaling factor or font size are not involved here)

     - since 5.10.0-dev, there's a minimum size calculated as: some constant * gui_scaling setting * OS scaling factor (display density)
     - but the effective coordinate size is still limited by the available space and the padding

see `GUIFormSpecMenu::calculateImgsize` and `FontEngine::initFont` for actual code
