### ISSUE TITLE
Windows: nil modpath for "*builtin*"/"builtin" with get_modpath()

### ISSUE THREAD

**Issue by TubberPupper** [minetest/minetest#15338]
### Minetest version

```true
Minetest 5.9.1
```

### Irrlicht device

WIN32

### Operating system and version

Windows 8.1

### Active renderer

OpenGL 4.4.0

### Summary

Basically we Windows folk can't get the modpath for builtin, it seems. Caused a crash with a friends' mod of mine (that he has since fixed)

I hear that this isn't expected behaviour? That's what my friend told me (that it's a difference between Windows and Linux)

(Yes I know Win8.1 is terrible, only reason why I haven't tried updating is because I don't want to brick my only harddrive lol and Win8.1 works well enough)

### Steps to reproduce

Have Windows and download the latest from https://www.minetest.net/
Run `minetest.get_modpath("builtin")` or `minetest.get_modpath("*builtin*")` and see how it's nil

**Comment by wsor4035** [comment]
builtin isnt a mod

**Comment by sfan5** [comment]
As stated, builtin isn't a mod so this isn't expected to work.
Instead an undocumented function called `core.get_builtin_path` fulfills this purpose.

Why do you need the builtin path in a mod?

**Comment by wsor4035** [comment]
also `minetest.get_modpath("*builtin*")` isnt valid

**Comment by TubberPupper** [comment]
> Why do you need the builtin path in a mod?

It's a mod that gets information on a node, and then checks the modpath to pinpoint functions in respective lua files.

Huh, interesting on the builtin_path thing.

Weird, then why does it work on Linux? Or does it not?

**Comment by TubberPupper** [comment]
> also `minetest.get_modpath("*modname*")` isnt valid

It got `"*builtin*"` from the mod origin of air IIRC. It checks mod_origin to get the modpath

**Comment by sfan5** [comment]
> Weird, then why does it work on Linux? Or does it not?

it does not.
