### ISSUE TITLE
Policy question: Engine name of old versions

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#15334]
I have a policy question about the rename (Minetest → Luanti) because this will come up quite a lot during the renaming process:

Does the name "Luanti" apply retroactively?

I.e. when we refer to an old version (pre-5.10.0 probably) in the documentation or official documents/websites/etc., should it be called "Minetest" or is it OK to call it "Luanti"?

There is no obvious answer either way as both answers can be justified:

* Yes: It's more convenient to not have to flip-flop around between "Minetest" and "Luanti" in the documentation and it makes writing it easier
* No: It's more "historically accurate" and old version literally include the name "Minetest" in them

Arguments can be made that one way or another is more/less confusing, and it's not clear which arguments we should trust more.

Please discuss.

**Comment by Zughy** [comment]
Just stick with "version" so to bypass the problem

**Comment by SmallJoker** [comment]
The name change happened in 5.10.0-dev, thus <= 5.9.1is Minetest. Attempting to change anything retroactively is impossible.

**Comment by appgurueu** [comment]
Old versions should be referred to as Minetest versions. If appropriate, the rename should be mentioned; a list of major versions could look e.g. like this to avoid confusion:

> * Luanti 5.10.0
> Before version 5.10.0, Luanti was called Minetest:
> * Minetest 5.9.0, 5.9.1
> * Minetest 5.8.0

**Comment by Wuzzy2** [comment]
OK. Is there anyone from the core devs who thinks the "Luanti" name *is* appropirate to use for old versions? So far the consensus seems to be "no".

I'm neutral on this btw.

I'm going to wait a few days more (in case more responses appear) and plan to add a short section to the wiki guidelines. Once this is done, the issue can be closed.

**Comment by Desour** [comment]
What we changed is just the name. So imo, "Luanti" and "Minetest" refer to the same thing, the same way that `minetest` and `core` refer to the same table. Luanti is not a fork, it is not a new project, not a copy, not move constructed, it's just a new reference.
So my vote goes to "yes, retroactively call old versions luanti". And the same way, "Minetest 5.10" will refer to the same as "Luanti 5.10".

**Comment by rubenwardy** [comment]
Yeah I think it's fine to say Luanti version 5.3.0 even if it wasn't called Luanti at the time. The most important thing is to avoid confusion rather than be technically historically accurate

**Comment by appgurueu** [comment]
> Yeah I think it's fine to say Luanti version 5.3.0 even if it wasn't called Luanti at the time. The most important thing is to avoid confusion rather than be technically historically accurate

I agree, and like Desour I think this goes both ways, so "Luanti" and "Minetest" are effectively the same thing to me.

I do think that it is probably less confusing to call older Luanti versions Minetest versions rather than to attempt a (partial) rewrite of history. Hence I think it is preferable to call older Luanti versions Minetest versions, *and* mention / imply the name change. Depending on the context, the opposite may also work well, e.g. "Luanti (at the time Minetest) version 5.4.0". But just "Minetest 5.4.0" -> "Luanti 5.4.0" might lead to nasty inconsistencies and confusion.

**Comment by rubenwardy** [comment]
When someone comes across the word "Minetest" in five years, they might have heard of it but not know exactly what it is referring to. So I'd prefer either referring to old versions as Luanti or wording it such that the name is avoided

**Comment by Wuzzy2** [comment]
Looks like the opinions are split. So I have decided to *not* update the wiki page. Closing because I made this issue specifically for a wiki question.
