### ISSUE TITLE
Distance based graphics and shaders

### ISSUE THREAD

**Issue by Ghurir** [minetest/minetest#15343]
### Problem

Minetest provides several default graphics and shader features that improve the game's look. However, these features reduce the performance and thus reduce the playable render distance. These features are applied at far distances where they cannot be noticed.

stable 30+ FPS at:
Features turned on: 150 render distance
Features turned off: 300 render distance

### Solutions

Allow for enabling features based on distance.
some of the features include:
#### Graphics
- Translucent liquids (angle-based might be a more physically accurate way for this setting)
- leaves style
- smooth lighting
- Undersampling? (I am not sure if this is possible)
#### Shaders
- Waving leaves (related #10929)
- Waving plants
- Waving liquids

-  ̶D̶y̶n̶a̶m̶i̶c̶ ̶s̶h̶a̶d̶o̶w̶s̶ Edit: already implemented and configurable

### Alternatives

Only if practical, easy to implement and doesn't complicate the shader code.

**Comment by appgurueu** [comment]
This sounds like a good idea. It shouldn't be terribly hard to implement: These features are controlled by preprocessor variables which we can set. We'd need two sets of compiled shaders, one for short distance, another for long distance. The shader code does not need to be changed at all.

Undersampling is possible and an interesting proposal for a GPU-side "Level of Detail" implementation. That would be a bit more work to implement, you'd probably render to two different textures of different resolutions and combine them in the second stage.

**Comment by lhofhansl** [comment]
- Already done for dynamic shadows.
- I had tried (locally) to change the leave style at a distance. It looked weird and the performance improvement was within the noise, so I did not pursue it.
- Waving plants and liquids is a good idea
- I'd like to figure out how to reduce geometry at a distance. Not only does not cost unnecessary performance, it also leads to very visible aliasing effects (past 400 or 500 nodes) that FXAA (or any other pixel space AA cannot fix)

**Comment by sfan5** [comment]
> Waving leaves
> Waving plants
> Waving liquids

These are just a few calculations inside the shader, which means these effects are essentially *free* performance-wise. No point disabling them.

> smooth lighting

I don't know enough about its implementation. Does it really improve performance that much?
What's your hardware?
