### ISSUE TITLE
Air blocks or blue blocks appearing underwater which blocks the view, resulting from using a lighted helmet

### ISSUE THREAD

**Issue by revevil** [minetest/minetest#15361]
### Minetest version

```true
Minetest 5.9.1 (Windows)
Using LuaJIT 2.1.1706185428
Built by Clang 17.0
Running on Windows/6.1.7601 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Irrlicht device

Direct X9

### Operating system and version

Windows 7

### CPU model

Xeon X5472

### GPU model

MSI Radeon R7 370

### Active renderer

OpenGL 2 (I think, whatever the default renderer is)

### Summary

This is my version output, but this bug existed in MineTest v5.8.0. The bug is these air nodes or blue boxes which are created underwater by the interaction of Wielded Light mod and the MineTest engine. The bug did NOT exist in v5.7.0. The bug is not with the Wielded Light mod but with the MineTest engine itself. It was previously reported by bell07, the maintainer of the Wielded Light mod. I will provide the link:

https://github.com/minetest-mods/wielded_light/issues/31

I am reporting this bug, because it was declared that MineTest is going through a "feature freeze" so that bugs can be caught up on and corrected. PLEASE address this issue if possible. This bug has been reported a few times over the past year. Unfortunately it kills the fun of creating underwater bases. It has been speculated that this bug is a rendering-related issue having to do with backface-culling, or the mod could be causing the engine to replace the block with a normal water source.

I have also tested this in Linux Mint v22 MATE, and the bug still happens. I prefer to run MineTest in Windows, because I get constant lockups in Linux if I attempt to run it at all.

![screenshot_20241030_221725](https://github.com/user-attachments/assets/efaf4e84-cf86-491e-90d3-fb4042b6c1f5)
![screenshot_20241030_221737](https://github.com/user-attachments/assets/61782851-110d-4c92-8358-eb88ed52c144)
![screenshot_20241030_221938](https://github.com/user-attachments/assets/30ee18e2-5037-46fd-80d8-64c62116a51d)

### Steps to reproduce

The steps to reproduce would be to install MineTest v5.8 or newer. Install these mods:

Wielded Light
3D Armor
3D Armor Light
Lighted Helmets

Make sure you have a lighted helmet equipped. If you are unable to find the crafting recipe for lighted helmets, copy this line into the mod.conf file for lighted helmets:

optional_depends = armor_admin, armor_bronze, armor_cactus, armor_crystal, armor_diamond, armor_gold, armor_mithril, armor_nether, armor_steel, armor_wood

With the lighted helmet equipped, go jump into some water that is deep enough to at least cover your head. You WILL see these blue blocks.

**Comment by cx384** [comment]
The title is a bit misleading.
IIRC, the wielded light replaces water sources with another type of water source which emits light. And when those are next to each other, you can see the border.
I guess this is more of a missing feature than a bug, or maybe a regression bug, but I don't know if this is actually the case.

**Comment by appgurueu** [comment]
Not a bug but more of a feature request / suggestion.

The linked mod uses a very ugly hack which was never guaranteed to work; it was probably pure luck that it worked to begin with. I would argue that Luanti is doing a less wrong thing now: As far as Luanti is concerned, these are two different liquid sources next to each other, so there *should* be faces rendered to separate them. If you invert the textures of the light node, you can see that that's what's happening: When you're inside the light source water source, you see the blue textures of the surrounding water nodes; if you're outside of it, you see the orange textures of the light source water source.

![Screenshot from 2024-10-31 16-15-54](https://github.com/user-attachments/assets/fcd79d8d-2c87-4703-b601-18de597f7340)
![Screenshot from 2024-10-31 16-15-44](https://github.com/user-attachments/assets/63b86f52-4067-4ae6-9534-7c77b69c7555)


Ideally we need some feature to control the lighting system instead.

**Comment by revevil** [comment]
I just want to say thank you for your replies! I think I am understanding the problem a bit better now. It makes me wish I had much greater knowledge of coding and could actually help. I've been obsessed about building underwater since I started doing it more. It is fun to watch the fish swim by when you are inside a glass building.
