### ISSUE TITLE
2D rendering: Artifacts at texture borders when downscaling

### ISSUE THREAD

**Issue by grorp** [minetest/minetest#15384]
### Luanti version

5.10.0-dev

### Irrlicht device

SDL

### Operating system and version

Fedora Linux 40 (Workstation Edition)

### CPU model

Intel® Core™ i7-4790K × 8

### GPU model

NVIDIA GeForce GTX 1080 Ti

### Active renderer

OpenGL 4.6.0

### Summary

minetest/irrlicht@fb7a0e4298356a2d339c5ebf23152b441dc06a8f changed Irrlicht's 2D code to use bilinear instead of nearest-neighbor filtering when scaling textures down. This introduced a regression: There are artifacts at the borders of some textures when they are scaled down.

This seems to be caused by the combination of bilinear filtering and "repeat" texture wrapping. It probably happens because the pixel at the other side of the texture is considered for interpolation.

### Steps to reproduce

High-level steps:

1. Make a texture with some content at the borders, some transparency at the borders
2. Show it in a formspec or HUD in Minetest
3. Make sure it's rendered below its original resolution (downscaling)
4. (Be lucky)

-----

In PRANG!'s in-game menu:
<img alt="screenshot 1" width="512" src="https://github.com/user-attachments/assets/60d5caef-aa17-4517-9bbd-c0531dc17235" />
(Artifacts around the light blue text textures, e.g. "START")

With minetest/irrlicht@fb7a0e4298356a2d339c5ebf23152b441dc06a8f reverted, I see this:
<img alt="screenshot 2" width="512" src="https://github.com/user-attachments/assets/d0c24c8d-48bd-4187-ba00-0c86382caf86" />
(No artifacts.)

-------------

Mod for reproducing: https://github.com/grorp/graphicsbug. After installing the mod and executing `/gb red`, I see this:
![screenshot 1](https://github.com/user-attachments/assets/c00f5b04-2cdd-4ac4-802b-49fddfbd8bc5)
(Artifacts at the left border and the right half of the upper border.)

With minetest/irrlicht@fb7a0e4298356a2d339c5ebf23152b441dc06a8f reverted, I see this:
![screenshot 2](https://github.com/user-attachments/assets/a74b84ec-d9b0-459f-bdb8-efd844f1e158)
(No artifacts.)
(Very small window size only for easier visibility, not needed for reproducing.)

----

This can also be reproduced by removing the transparent vertical padding at the bottom of `menu_header.png`, producing this texture: [menu_header.png](https://github.com/user-attachments/assets/0a195e13-b03c-4af0-8951-0857684c89d2). This results in artifacts at some window sizes, like here:
<img alt="screenshot 1" width="512" src="https://github.com/user-attachments/assets/98a19268-dcfd-4fdb-8e67-2bfc0da462c1" />

With minetest/irrlicht@fb7a0e4298356a2d339c5ebf23152b441dc06a8f reverted:
<img alt="screenshot 2" src="https://github.com/user-attachments/assets/82fe4d06-1249-45a4-acf9-9a051e5ad343" width="512" />

------

Potential occurrence "in the wild": https://discord.com/channels/369122544273588224/369123175583186964/1302416079250784316

**Comment by Desour** [comment]
Issue for #15362 I assume.

---

Another thing this caused is that colors of fully transparent now matter, see e.g. the boarders of the luanti header in your example, they are dark.

**Comment by sfan5** [comment]
> https://github.com/minetest/irrlicht/commit/fb7a0e4298356a2d339c5ebf23152b441dc06a8f changed Irrlicht's 2D code to use [...]

For the record: this puts the regression at MT 5.8.0

**Comment by nininik0** [comment]
Somehow I have a similar issue with a 32x32 texture pack that that does some HUD changes, they look weird and have a similar look, but the smooth edges became jagged when viewed, or uneven
