### ISSUE TITLE
Falling nodes do not turn back to solid blocks when connected to a server

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#15381]
#### Client
```
Luanti 5.10.0-dev-9982c5637 (Linux)
Using LuaJIT 2.1.1727870382
Built by GCC 11.4
Running on Linux/5.15.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

#### Server
```
Luanti 5.10.0-dev-9982c5637 (Linux)
Using LuaJIT 2.1.1727870382
Built by GCC 10.2
Running on Linux/5.10.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Irrlicht device

X11

#### Client
Ubuntu 22.04 LTS
#### Server
Debian 11

#### Client
Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz
#### Server
Intel Xeon Processor (Skylake, IBRS)

### GPU model

NVIDIA GeForce GT 710

### Active renderer

OpenGL 4.6.0

### Summary

When connecting to as server and finding a hanging sand-like nodes and punching them they fall but do not return to solid block state. They're showing GenericCAO when pointing over them and do not despawn nor can be interacted. Mining a single block under them some times fixes a problem. Server has no mods except for Minetest Game, also I'm not sure if it's game or engine bug, does not happen on local games.

#### Screenshots
![screenshot_20241103_163742](https://github.com/user-attachments/assets/359a03fa-f120-48b9-bee8-d06f0705650b)
![screenshot_20241103_173554](https://github.com/user-attachments/assets/e962b5ac-bed5-4e07-a5a4-c2d0af37ea91)
![screenshot_20241103_185524](https://github.com/user-attachments/assets/4369f947-33a9-45f7-89cf-114416bb14e3)

**Edit:** Could also reproduce in devtest. Making nodes fall using falling node tool world trigger the bug, can confirm it's not related to particular game. Screenshot added to show that.

### Steps to reproduce

1. Connect to remote server
2. Find hanging sand-like nodes
3. Punch them
4. Observe them not returning back into solid notes after falling (does not happen frequently), may not happen all the times.
5. Mine a block under them, usually they return to normal state by doing that

**Comment by sfan5** [comment]
possibly collision related and thus to #15375 (same root cause?)

**Comment by Desour** [comment]
Can reproduce.

**Comment by juozaspo** [comment]
Could also reproduce in devtest. Making nodes fall using falling node tool world triggers the bug, can confirm it's not related to particular game.
![screenshot_20241103_185524](https://github.com/user-attachments/assets/4369f947-33a9-45f7-89cf-114416bb14e3)

**Comment by sfan5** [comment]
ping @kno10

**Comment by kno10** [comment]
Probably related to #15196 #15375.

Might be related to this condition (predating cb6c8eb2):
https://github.com/minetest/minetest/blob/e952a0807b85e089eaa320cfeb09e33816d141ed/src/collision.cpp#L548-L549

The improved collision code may more frequently trigger this issue: it recognizes the collision with the floor is instant, and hence the velocity is unchanged. This may also apply to falling blocks when they are stacked - because of the instant collision, their velocity is still unchanged after applying acceleration, and that condition un-sets the collision flag then.

**Comment by sfan5** [comment]
> This may also apply to falling blocks when they are stacked - because of the instant collision, their velocity is still unchanged after applying acceleration, and that condition un-sets the collision flag then.

Yeah this condition sounds like nonsense. In the presence of acceleration, if speed stays unchanged you definitely did have a collision on at least one axis or the speed would have changed.
Do we know why this condition exists?

**Comment by kno10** [comment]
It seems to trace back to when bouncy nodes were introduced:
https://github.com/minetest/minetest/commit/3b43c69df4ce7d68aebb4bd02aaa4aca18b9afad
probably meant to eventually stop bouncing when the velocity gets small enough.
I'd remove it and check if bouncy nodes work as expected.

**Comment by kno10** [comment]
Does removing this else condition
https://github.com/minetest/minetest/blob/cb6c8eb2f013edfe127ce18f760c432aee5aba01/src/collision.cpp#L547-L550
repair the falling nodes?
(there are similar conditions also for x and z, but for testing this case y is enough).
This else is meant to prevent reporting repeated collision within one time step.
