### ISSUE TITLE
Option to disable minetest_game's default ore generation

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#1539]
At present, one cannot "un-register" an ore generation pattern once it has been registered, making it impossible to supply new ores and new generation of the existing ores without also getting the existing behavior/patterns.

Currently the preferred way to do something like this is by making a custom game, with a custom version of, say, the default mod that is already modified to produce ores in the desired pattern, but this makes it impossible for a simple mod to change the ore generation settings without supplying an entire map generator to go with it.  

A second option he came up with was to write a skeleton of a default mod, include it in a modpack so that the engine's load order resolver loads it first, and have it load the *real* default mod after it sets its overrides.  This of course is hacky but it may work in lieu of a better way.

A third, and probably the best option is to just add a couple of lines to minetest_game to wrap its ore generation code in an if/end clause, with a flag that other mods can then change.  This would require all other subgames that intend to retain minetest_game cross-compatibility to follow suit in order for said mods to be able to reliably turn it off.

This would depend on the existence of Mod preloading support as described in #1532 and would need to be a global flag (as one would need to be able to turn it off before 'default' reads it).

**Comment by kwolekr** [comment]
Great news, VanessaE!  You can do this as of 0.4.11:
https://github.com/minetest/minetest/commit/cf8213ea827f38ae5d4b8ef16c396545e3e59657
