### ISSUE TITLE
Unexpected results when adding inverted velocity

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#15426]
### Luanti version

```true
Luanti 5.10.0
```

### Operating system and version

Windows 10

### Summary

When adding the players velocity flipped, the players movement becomes erratic and unpredictable.

### Expected Behavior:
Player movement on the x axis is canceled

### Potential Causes:
Maybe the velocity is getting applied multiple times? Not quite sure what the issue could be here.

### Video of the bug: (Epilepsy Warning)

https://github.com/user-attachments/assets/b55d43a8-5dfe-44d2-a883-097f6e165d4a

### Steps to reproduce

Run this code:
```lua
minetest.register_globalstep(function(dtime)
    for _, player in ipairs(minetest.get_connected_players()) do
        local vel = player:get_velocity()
        if vector.length(vel) > 0 then
            player:add_velocity({x=-vel.x, y=0, z=0})
        end
    end
end)
```

**Comment by appgurueu** [comment]
> Expected Behavior:
> Player movement on the x axis is canceled

Note that this will never work out exactly, it will always be janky because player movement is clientside and add velocity is a command issued by the server. It could be tolerable in singleplayer though.

That said what I'm seeing in your videos is well above any margin of error I'd expect...
