### ISSUE TITLE
Floating small pieces of land on V7/Valley mapgen

### ISSUE THREAD

**Issue by Firestar-Reimu** [minetest/minetest#15420]
### Luanti version

```true
(base) [firestar@Archlinux ~]$ minetest --version
Minetest 5.9.0 (Linux)
Using LuaJIT 2.1.1725453128
Built by GCC 14.2
Running on Linux/6.11.6 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/minetest"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Irrlicht device

wayland

### Operating system and version

Archlinux (it did not update luanti for a month)

### Summary

Floating small pieces of land on V7/Valley mapgen

I do not open "Floatlands (experimental)" but small rocks still float in the sky

<details>

![Screenshot_20241111_151055](https://github.com/user-attachments/assets/8908b653-9a0e-4c71-9957-cc6c5b870f82)
![Screenshot_20241111_151237](https://github.com/user-attachments/assets/f7e35e0f-129f-42e0-9863-d08a7fa58879)
![Screenshot_20241111_152018](https://github.com/user-attachments/assets/68069994-caaf-47b7-9809-ad5d48244399)
![Screenshot_20241111_152204](https://github.com/user-attachments/assets/fafe6d80-5a17-4a84-a296-d4856f86d158)

</details>

### Steps to reproduce

The seed is 114514, and the coordinates are on the screenshots

first 2 pictures are valley mapgen

last 2 pictures are v7 mapgen

**Comment by sfan5** [comment]
That's a feature.

**Comment by appgurueu** [comment]
> That's a feature.

It needs to be enabled though, and the report says "I do not open [did not enable?] 'Floatlands (experimental)' but small rocks still float in the sky"

**Comment by nininik0** [comment]
Can confirm 
![screenshot_20241111_113743](https://github.com/user-attachments/assets/3f9aa591-0c2c-42ce-bbd9-a34dd15493c2)
On my server.

**Comment by Firestar-Reimu** [comment]
I think you should add a "detect if there are small chunks of floating land and eliminate them" feature
