### ISSUE TITLE
Mainmenu UX

### ISSUE THREAD

**Issue by worldmind** [minetest/minetest#15439]
### Problem

It was really difficult to understand how to start the game with exact game/mods/textures (Minetest 5.6.1 from Ubuntu's repos).
Now (next day), looking to the start screen I am starting to understand that probably all options are independent, but it makes it really difficult to start and likely many users were not able to get what they wanted and just deleted the application.
I guess it's a known issue - https://github.com/minetest/minetest/issues/6733

### Solutions

Looks like there are 5 blocks:
1. Creative mode/Enable damage/Host server checkboxes in top left corner
2. Games selector in bottom left corner
3. World selector in top right corner
4. Mods selector under it (took long time to get that you need to create world and later select modes for it)
5. Textures pack selector in Content tab

Perhaps some abstraction on top of them is needed, like "Play" (no idea how to name it better) and wizard to create "plays" via 5 steps.
"Play" will keep settings from all steps mentioned above.
I tried to draw it a bit, see attached file.
[Luanti_mainscren.pdf](https://github.com/user-attachments/files/17779022/Luanti_mainscren.pdf)

### Alternatives

Don't allow to start app until exam passed

**Comment by worldmind** [comment]
Ups, looks like I forgot to draw "Start" buttons near store "plays", but hope it's clear.

**Comment by worldmind** [comment]
Just checked in 5.10 - only change - it's ask to install a game, so, I think everything I wrote here still valid.

**Comment by wsor4035** [comment]
> **this is a duplicate**

you even link the proper issue.....

**Comment by worldmind** [comment]
> you even link the proper issue.....

yep, somehow I didn't paid attention that proposals are in comments. not in separate issues
