### ISSUE TITLE
~30% lower framerate with shaders on old hardware

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#15433]
Report forwarded from IRC.

<blockquote>

### Luanti version
 
```true
Luanti 5.10.0-dev-debug (Linux)
Using LuaJIT 2.1.ROLLING
Built by GCC 14.2
Running on Linux/6.10.6 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```
 
### Irrlicht device
 
X11
 
### Operating system and version
 
GNU Guix System
 
### GPU model
 
Intel GMA 4500 MHD
 
### Active renderer
 
OpenGL 2.1
 
### Summary
 
Luanti is significantly slower with shaders enabled compared to no
shaders when displaying exactly the same thing.  This isn't a new
issue: I get similar results with the same GPU on a different computer
with Minetest 5.6.1 and Debian 12.

Without shaders (22 FPS): https://x0.at/bqPG.png
With shaders (14 FPS): https://x0.at/4KUX.png

Effects that depend on shaders (post-processing, waving nodes, dynamic
shadows) are all disabled.
 
### Steps to reproduce
 
1. Join a world with shaders enabled (make sure it's already generated
   since the mapgen can also slow things down)
2. Disable shaders and join exactly the same world

</blockquote>

**Comment by appgurueu** [comment]
My thoughts: This is comparatively old hardware (2008), without shaders it's barely playable. (It would likely benefit from general necessary rendering performance improvements though, which are much higher priority.)

**Comment by sfan5** [comment]
my reply from IRC:
> looking at https://www.notebookcheck.com/Intel-Graphics-Media-Accelerator-4500MHD-GMA-X4500MHD.9877.0.html your gpu was barely suitable for basic gaming back in the day. with it being old enough to buy beer (in germany)¹ now I think that's just the answer.
>
> looks like you should be able to enjoy quake 3 however

While we don't have a clear range of supported hardware I think this one falls out of it and this issue is ripe for closing.

¹ that is 16 years

**Comment by lhofhansl** [comment]
My $0.02. Do not maintain mountains of code around just to support some very old H/W.
