### ISSUE TITLE
glTF and mod PO support missing in core.features

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#15437]
### Luanti version

```true
Luanti 5.10.0
```

### Operating system and version

GNU/Linux

### Summary

Neither the new glTF support nor the support for the PO file format for mod translations is listed in `core.features`, making it impossible to provide proper fallback code in games at the moment.

Please add them (preferably for an upcoming 5.10.1 patch release).

It's possible other relevant features were overlooked for this release as well (please post them).

### Steps to reproduce

1. Read `lua_api.md`

**Comment by sfan5** [comment]
You wouldn't be able to provide proper fallback even if you could check for them, because these are client-side features.

**Comment by Wuzzy2** [comment]
OH! I didn't know it was intentional. Yeah, makes sense. Closing …
