### ISSUE TITLE
Inverted Mouse [Android]

### ISSUE THREAD

**Issue by minefaco** [minetest/minetest#15443]
### Luanti version

```true
Luanti 5.10
```

### Operating system and version

Android 13

### Summary

If I move the cursor up, it goes to the left; if I move it down, it goes to the right; if I move it to the left, it goes up; and if I move it to the right, it goes down. It is completely inverted.

### Steps to reproduce

Install Luanti on Android.
Conect a Mouse.
Try to move.

**Comment by SmallJoker** [comment]
If you could rotate the screen to be in portrait mode, then the mouse would probably function correctly.

**Comment by minefaco** [comment]
After doing some research, I found out that it's a bug in Android that affects various devices running Android 13, including mine.
