### ISSUE TITLE
Just deleted itself on windows 10 and exe file gone

### ISSUE THREAD

**Issue by SpyRiley1065** [minetest/minetest#15458]
### Luanti version

```true
5.10.0
```

### Operating system and version

Windows 10

### CPU model

Intel Core i5-4310U

### GPU model

Intel HD Graphics 4460

### Active renderer

 OpenGl 4.3.0 

### Summary

Just deleted luanti.exe from my pc

### Steps to reproduce

try finding it in the trash and fixing the dll files

**Comment by wsor4035** [comment]
cant replicate, in coordination with a core dev, closing this. if you deleted it yourself, then thats not something we can resolve.

**Comment by SpyRiley1065** [comment]
![SharedScreenshot](https://github.com/user-attachments/assets/975e54df-9880-42db-a79e-d56f35b16c19)
bruh now not loading luanti

**Comment by wsor4035** [comment]
i would suggest redownloading and installing

**Comment by SpyRiley1065** [comment]
I got off and it just moved luanti.exe to the trash bin

**Comment by appgurueu** [comment]
This is not something Luanti will do by itself.

Since I choose to believe that you are acting in good faith, please check whether some other software, like an overzealous antivirus software, might be moving Luanti to the trash.
