### ISSUE TITLE
Building and running with SDL and OpenGLES2

### ISSUE THREAD

**Issue by sfence** [minetest/minetest#15457]
### Luanti version

```true
Luanti master branch -> macos
```

### Operating system and version

macOS 15

### Active renderer

OpenGLES 2.0

### Summary

OpenGLES header not included here -> https://github.com/minetest/minetest/blob/b63e988bd60089b5f0595442b974886c17d5e1c9/irr/src/OpenGL/Common.h#L10-L13

When starting Luanti with OpenGLES2 frontend, glError GL_INVALID_ENUM is dropped from this code -> https://github.com/minetest/minetest/blob/b63e988bd60089b5f0595442b974886c17d5e1c9/irr/src/mt_opengl_loader.cpp#L761-L772

SIG_BAD_ACCESS  glDebugMessageCallback is not defined in OpenGLES 2 without GL_KHR_debug extension -> https://github.com/minetest/minetest/blob/b63e988bd60089b5f0595442b974886c17d5e1c9/irr/src/OpenGL/Driver.cpp#L173-L175

### Steps to reproduce

Try to build Luanti for iOS on macOS with iPhoneSImulator SDK and run.

**Comment by sfan5** [comment]
> OpenGLES header not included here -> 

We don't need the GLES header here.
Arguably `SDL_opengl.h` not defining anything is a bug but we can work around it.

> glError GL_INVALID_ENUM is dropped from this code -> 

We can either clear the error here or add a version check.

> SIG_BAD_ACCESS glDebugMessageCallback is not defined in OpenGLES 2 without GL_KHR_debug extension 

We should check the extension.
