### ISSUE TITLE
Clicking on tooltip closes formspec

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest#15467]
### Luanti version

```true
Luanti 5.11.0-dev-946b3a422-dirty
OpenGL 4.6.0
```

### Irrlicht device

X11

### Operating system and version

Linux Mint 20.3 Cinnamon

### CPU model

Intel i7-8700K

### GPU model

Nvidia GeForce RTX 3060

### Active renderer

OpenGL 4.6.0

### Summary

If you have a small formspec and a large tooltip, or a formspec anchored to a corner of a window so the tooltip can't move out of the cursors way when you click on the tooltip the formspec will close.

### Steps to reproduce

In Devtest open the inventory and make the game screen tiny. Take an item will a long description, such as the mese pickaxe and put it in the lowest right inventory slot. As you mouse-over the slot the description/tooltip will display. Click on the tooltip and watch the formspec close.
![screenshot_20241121_180605](https://github.com/user-attachments/assets/0cf46cb3-6257-4927-b20a-add5fa9132b0)
I realize that having a screen that tiny is silly, but I first experienced the problem when working on my game for the game jam. I have a formspec that shows in the lower right corner of the screen, and the button has a tooltip. If you accidentally click on the tooltip it closes the formspec, but doesn't call the button's action.
![screenshot_20241121_180656](https://github.com/user-attachments/assets/6bd37357-801d-4b9a-b04c-451192762e8c)

**Comment by SmallJoker** [comment]
I think the correct solution here is to move the tooltip above the cursor so that you can interact with the button as usual.
