### ISSUE TITLE
"ERROR[main]: Some exception: "bad allocation"" on official builds

### ISSUE THREAD

**Issue by qwrwed** [minetest/minetest#1547]
On the official build, Minetest keeps crashing with the error "ERROR[main]: Some exception: "bad allocation"" on multiplayer (VanessaE's Survival Server). 
Fess' latest 64-bit build as of 8/8/14 works fine, but the official MSVC 0.4.10 build does not.
Forum topic here: https://forum.minetest.net/viewtopic.php?f=6&t=7914&p=150471#p150471

**Comment by nerzhul** [comment]
No response from user since 8 months. I close the issue.
