### ISSUE TITLE
Grass generates 1 node below water

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#15485]
### Luanti version

```true
5.10.0
```

### Operating system and version

GNU/Linux

### Summary

Since Luanti 5.10.0, newly generated maps start with grass below water at the default water level. This happens in Minetest Game and Repixture.

**This is a regression compared to 5.9.0.**

### Steps to reproduce

1. Start Minetest Game and generate a new map (v7)
2. Fly to a beach with grass
3. Look below the water at water level

There should by any node *but* dirt-with-grass, but there is dirt-with-grass.

**Comment by SmallJoker** [comment]
Rudimentary bisecting using old (and dirty) RUN_IN_PLACE=1 builds:

Good: 2024-09-02 (with VBO PR 15076 applied)
Bad: 2024-09-11 (with network PR 15087 applied)
