### ISSUE TITLE
the end...?

### ISSUE THREAD

**Issue by JayAndrewBoy** [minetest/minetest#15504]
Hey everyone.

I reached out because I have been struggling with heavy feelings of depression and defeat recently. I have long wanted to create a Minecraft-like server where I could hang out with friends, play some mods, and have a good time. But in Luanti, formerly Minetest, is turning out to be much harder than I imagined.

I've tried everything to get it to work. Every day I tried to set up my server with **Hamachi**, **playit.gg**, **FreeDNS Update**, but nothing worked. Every time I started the server, I got an error message saying "**Connection timeout expired**".

Looks like it's time for me to give up. I am feeling like a dumb loser for not being able to solve such a simple problem. I mean, creating a server in Minecraft is so easy and straightforward, but with Luanti, it's like hitting a brick wall. No matter what I try, it just won't let me start it.

I guess it's time to say goodbye. I'll forget all about it and start looking for something else. 😢😔

I'm not sure if I'll ever come back, but I really regret that I feel this way about myself. I'm deeply sorry if I let anyone down.

So thanks for everything, stay safe, and peace out. ❤️

**Comment by appgurueu** [comment]
1. Your problems don't sound like Luanti problems, but rather like basic problems with administrating any kind of public server.
2. If you struggle with setting up a server, you can always let someone else do it for you (at a price). I've heard of at least two providers: [Buckaroo Banzai's Hosting](https://hosting.minetest.ch) or [Pine Hosting](https://pinehosting.com/minetest).
3. This issue tracker is the wrong place for this kind of post either way.
