### ISSUE TITLE
[BUG] Mods can place and move blocks into void

### ISSUE THREAD

**Issue by Monniasza** [minetest/minetest#15501]
### Luanti version

```true
Luanti 5.10.10 Flatpak
```

### Irrlicht device

X11

### Operating system and version

Linux Mint 22

### CPU model

Intel© Core™ i5-7300HQ CPU @ 2.50GHz × 4

### GPU model

Nvidia GeForce 1050

### Active renderer

OpenGL 4.6.0

### Summary

Mods like Jumpdrive can move and/or place the blocks into the void. It breaks assumptions about finity of the world. Related to https://github.com/mt-mods/jumpdrive/issues/114

### Steps to reproduce

Go to Luanti main menu > Multiplayer > Pandorabox > /spawn > lga's Tiny Town > Museum of oddities > O-162 > mission > press the button

**Comment by Zughy** [comment]
Hi, please provide a minimal example. Current instructions aren't straightforward and I quit after trying reaching the point for 5 minutes

**Comment by appgurueu** [comment]
Agreed that there should be a minimal example ideally in the form of a small standalone mod / `init.lua`.

This report is overall very unclear:

* What is "the void"? Areas outside of map bounds? How far outside?
* Which API functions does "place" and "move" refer to here? `core.set_node`? `core.bulk_set_node`? VoxelManip? All of them? Some of them?
* What do these API functions currently do; what do you expect them to do instead?
* Bonus, follow-up of the last question: How do you expect backwards compatibility to be maintained?

I briefly read through the mod-side bug report by the way and while it can be discussed whether the engine should handle this, this is definitely something a mod can handle today already just fine (and probably needs to handle: It won't be very useful to the mod authors if functions like `core.set_node` start erroring out; they will want to catch OOB teleportations before they happen).

**Comment by appgurueu** [comment]
Alright, closing this for now.
