### ISSUE TITLE
Incorrect normals on mesh nodes

### ISSUE THREAD

**Issue by paulevsGitch** [minetest/minetest#15503]
### Luanti version

```true
Luanti 5.10.0 (Windows)
Using LuaJIT 2.1.1725453128
Built by Clang 18.1
Running on Windows/10.0.19041 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Windows 10, 64 bit

### CPU model

Intel Core i9-10900F

### GPU model

NVIDIA GeForce RTX 3060

### Summary

Normals on nodes that uses mesh draw type are not the same as in .obj file and are highly influenced by face direction. On the entities all imported normals works fine (right is node, left is entity):

![screenshot_20241201_163725](https://github.com/user-attachments/assets/4a69a267-156f-4e88-9355-13cfde2df9b2)

### Steps to reproduce

Simple mod (for any game) that can reproduce this issue (adds node `debug_normals:sphere` and entity `debug_normals:sphere`)
[debug_normals.zip](https://github.com/user-attachments/files/17969081/debug_normals.zip)

**Comment by sfan5** [comment]
we recalculate normals on entities if they seem wrong:
https://github.com/minetest/minetest/blob/e9080f91f28af50a649c146ea34c371ef19affc3/src/client/content_cao.cpp#L733-L738
but we always do it for nodes:
https://github.com/minetest/minetest/blob/e9080f91f28af50a649c146ea34c371ef19affc3/src/nodedef.cpp#L945-L954

**Comment by sfan5** [comment]
Doing this makes them look identical:
```diff
diff --git a/src/client/content_mapblock.cpp b/src/client/content_mapblock.cpp
--- a/src/client/content_mapblock.cpp
+++ b/src/client/content_mapblock.cpp
@@ -1671,7 +1671,7 @@ void MapblockMeshGenerator::drawMeshNode()
                else if (degrotate)
                        rotateMeshXZby(mesh, 1.5f * degrotate);
                recalculateBoundingBox(mesh);
-               meshmanip->recalculateNormals(mesh, true, false);
+               //meshmanip->recalculateNormals(mesh, true, false);
        } else {
                warningstream << "drawMeshNode(): missing mesh" << std::endl;
                return;
diff --git a/src/nodedef.cpp b/src/nodedef.cpp
--- a/src/nodedef.cpp
+++ b/src/nodedef.cpp
@@ -950,7 +950,7 @@ void ContentFeatures::updateTextures(ITextureSource *tsrc, IShaderSource *shdsrc
                        v3f scale = v3f(BS) * visual_scale;
                        scaleMesh(mesh_ptr, scale);
                        recalculateBoundingBox(mesh_ptr);
-                       meshmanip->recalculateNormals(mesh_ptr, true, false);
+                       //meshmanip->recalculateNormals(mesh_ptr, true, false);
                }
        }
 }
```

The problem is in `content_mapblock.cpp` we might rotate the mesh, but we don't rotate the normals.
So whoever wrote this code opted to just recalculate them instead, which leads to the difference you're seeing.
