### ISSUE TITLE
L-system trees: `R-Key` does not work

### ISSUE THREAD

**Issue by a-tour-ist** [minetest/minetest#15506]
### Luanti version

```true
Luanti 5.11.0-dev-e9080f91f (Linux)
Using LuaJIT 2.1.1725453128
Built by GCC 14.2
Running on Linux/6.10.13 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Manjaro Linux

### Summary

When using `core.spawn_tree(pos, tree_def)`, the `R`-Key in axioms does no longer work. Instead of the fruit-node, air is placed.

Looks like it first broke with https://github.com/minetest/minetest/commit/60810c2d375a8c63e096669dd6c6cd791f2c5075

![image](https://github.com/user-attachments/assets/dce1dd7f-7730-4f0f-ac35-4f3266a8bcb3)

### Steps to reproduce

```lua
core.spawn_tree(vector.new(0,0,0), {
    axiom = "TRT",
    trunk = "mapgen_tree",
    fruit = "mapgen_apple",
    leaves = "mapgen_stone"
})
```

**Comment by appgurueu** [comment]
Thanks for the detailed report. The issue seems pretty obvious (in hindsight): There are `if (fruit_chance)` guards for resolving the fruit node. But `fruit_chance` isn't the only way fruits can be placed; `R` is another, which I assume was forgotten. @cx384
