### ISSUE TITLE
how do I fix this error on mods

### ISSUE THREAD

**Issue by LinuxDevloper3D** [minetest/minetest#15526]
### Luanti version

```true
flatpak
```

### Irrlicht device

X11 

### Operating system and version

Debian 12

### CPU model

 Intel Celeron N4020 (2) @ 1.094GHz

### GPU model

Intel UHD 600

### Active renderer

4.3

### Summary

some of the mods I download required the the mod default

### Steps to reproduce

download nether mod  and it will say missing dependics

**Comment by LinuxDevloper3D** [comment]
![Screenshot 2024-12-07 1 37 36 PM](https://github.com/user-attachments/assets/df076178-4d40-4b70-b284-ea10414be62a)

**Comment by wsor4035** [comment]
because your trying to install the mod on some other game than minetest game (or derivative mod soup).
