### ISSUE TITLE
Parameters tooltips extend longer than screen's lenght

### ISSUE THREAD

**Issue by Cwpute** [minetest/minetest#15539]
### Luanti version

```true
Luanti 5.10.0
OpenGL 4.6
```

### Irrlicht device

X11

### Operating system and version

Linux Mint 22

### Summary

Long tooltips in the settings menu don't wrap around and can be longer than the mai nwindow. We should settle on a maximal line lenght before it wraps around.
![2024-12-12_13-34](https://github.com/user-attachments/assets/3f440aa4-1b48-4384-b4b4-1068f8e392aa)
Related to #13476

### Steps to reproduce

Above screenshot is from the Researcher mod's settings from ContentDB.

**Comment by appgurueu** [comment]
Same as #15201 essentially

**Comment by Cwpute** [comment]
indeed, should i close this issue ?

**Comment by appgurueu** [comment]
> indeed, should i close this issue ?

I've retagged the other issue as a bug, closing this now as a duplicate.
