### ISSUE TITLE
Replace Github during the Minetest to Luanti repo migration

### ISSUE THREAD

**Issue by Githubismalware** [minetest/minetest#15546]
### Problem

Hello!
Minetest/Luanti has always been, unfortunetly, hosted on Github, which is a git platform made of nonfree malware. It mostly requires propietary JS to work, spies on your activities, feeds all code in repos to not so co-operating Copilot and probably many more shenanigans we may be vulnerable to by a huge tech company made up of manipulation and unjust power.

The community has also been campaigning (e.g. in forums or here) for a git repository change, which should be very easy to do now, as the game is being renamed to Luanti. The repo hasn't been migrated yet, so its destination can be still changed, so instead of Github it can be hosted on a platform like the ones below.

### Solutions

Please switch the game repo during the migration to Codeberg. It is a free/libre git service, an instance of Forgejo, with care for freedom and privacy.

However, the JS is incorrectly licensed, but everything still works without it and that's probably the only problem with it.

### Alternatives

A good alternative to Codeberg is Nongnu Savannah (nongnu.org). It has the most care for freedom, as it can be expected from a service hosted by GNU themselves.

The only cons are that a free software review is required (which should only take a few days) and the interface may look a bit bare bones in some aspects.

1 more alternative could be hosting a git repo yourself, which could possibly be the best way, but it would take more server resources and everg contributor would need to make a specific account.

### Additional context

Doing the switch to a free/libre git platform can make contributors and the Minetest/Luanti organization invulnerable to propietary malware anti-features, and would make the community thankful.

Thank you very much in advance!

**Comment by wsor4035** [comment]
dupe of https://github.com/minetest/minetest/issues/12324
