### ISSUE TITLE
`.x` model rendering regression

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#15544]
### Luanti version

```true
5.11.0-dev (202412121819)
```

### Irrlicht device

Wayland

### Operating system and version

Kubuntu 25.04

### CPU model

AMD 7840HS

### GPU model

AMD Radeon 780M

### Active renderer

OpenGL 4.6

### Summary

Latest build seems to have some weird model issues, most mobs appear fine but lava flan specifically does not show properly but inside out and tiny. Worked fine before this.

### Steps to reproduce

Create world, add mobs redo and mobs monsters and spawn in a lava flan, instead of the tall proud lava blob he usually is with eyes and mouth, he appears like an inside out floating tiny lava worm.

Same happens with mobs_horse...

**Comment by appgurueu** [comment]
Likely regression from https://github.com/minetest/minetest/commit/1e59b9a75651130aa7061c2c67dd588d74bb6cb5. Notably the lava flan is a `.x` model, while the other models are `.b3d`. I will look into this. Thanks for the report.

**Comment by BluebirdGreycoat** [comment]
Thanks for reporting this issue, I have the same problem. I've noticed the .X models are on their side, reduced in size, and normals are inverted. The models don't animate either. Saw this with nssm mobs: white_werewolf, warthog (aka pumba). I didn't test any others.
