### ISSUE TITLE
Cannot mine/place/interact with almost all nodes/blocks [on the latest daily build]

### ISSUE THREAD

**Issue by SlavaArduino12345** [minetest/minetest#15557]
### Luanti version

```true
Luanti 5.11.0-dev (Linux) 202412141820+5.10.0+52a6673da-ppa~ubuntu24.04.1
Using LuaJIT 2.1.1703358377
Built by GCC 13.3
Running on Linux/6.8.0 x86_64
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="/usr/share/luanti"
STATIC_LOCALEDIR="/usr/share/locale"
```

### Irrlicht device

SDL

### Operating system and version

Linux Mint 22 Cinnamon

### CPU model

AMD A4-6300 APU with Radeon(tm) HD Graphics × 1

### GPU model

NVIDIA Corporation GK208B [GeForce GT 710]

### Active renderer

OpenGL 4.6.0

### Summary

You cant mine, place, or interact with 99% of nodes at all. The selection outline is also not present.
![image](https://github.com/user-attachments/assets/920e49f8-eb53-48b9-8658-0913b9d77ef5)
You can sometimes interact or mine with some nodes like signs from mod signs_lib, trainblocks or farebox faregates...
![image](https://github.com/user-attachments/assets/0ae4172a-ff4b-4b1b-a274-f6665d5d875d)
...sometimes only from an extremely close distance...
![screenshot_20241214_222501](https://github.com/user-attachments/assets/ea2f70f0-de09-4aaa-bd36-94b8239979a8)
![screenshot_20241214_222506](https://github.com/user-attachments/assets/24a24461-3794-497c-9f8b-1103df2f0dac)
![screenshot_20241214_222513](https://github.com/user-attachments/assets/7420aa78-9079-4eb8-b739-ac6c7081d7cd)
![screenshot_20241214_222553](https://github.com/user-attachments/assets/6bae6992-6166-4b43-abe0-43c0ad583285)
...but cant place them back:
![screenshot_20241214_222606](https://github.com/user-attachments/assets/b6739f15-b9aa-40f7-b4fe-d5e414f39ceb)

_The version is 202412141820+5.10.0+52a6673da-ppa~ubuntu24.04.1 and was downloaded via apt from the unstable PPA_

### Steps to reproduce
Make sure you are using the latest version from the unstable PPA
Join any singleplayer or multiplayer world(s) and try mining/placing/interacting with any block/node. Monitor the presence of the block/node selection outline/highlight.

**Comment by SmallJoker** [comment]
Already fixed. #15553
