### ISSUE TITLE
Send different textures per player

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#15551]
### Problem

In a specular map (e.g. CTF) I'd like to have a node shown as blue if it's in my team part of the map and red if it's in the other. Vice versa, enemies will see blue what I see red and red what I see blue.

Example from S4 League game
![-5974078984096433442_121 (6)](https://github.com/user-attachments/assets/80aa9a84-d3d0-4ac0-a3fc-9aa936a67e8b)

### Solutions

Title. Maybe it should be a function/attribute for players?

### Alternatives

---

**Comment by sfan5** [comment]
This sounds good except what would you do when the player changes teams?

**Comment by Zughy** [comment]
@sfan5 override the player function. Like, I could have two nodes that are white by default, where half of them are on one side and the other half on the other.

When players join, if they're in team 1, they'll see blue and red respectively, otherwise they'll see red and blue. Basically I'd run the function when they join check their team ID

**Comment by appgurueu** [comment]
Ultimately implementing this properly requires adding another level of indirection for textures I believe.

Related: #3528 (of which this issue is a special case with an additional requirement that it may be different per-player), #13417 (tangentially).

**Comment by sfan5** [comment]
yeah it sounds like this is best covered by https://github.com/minetest/minetest/issues/3528

**Comment by Zughy** [comment]
It lacks the per-player feature, as appguru said

**Comment by sfan5** [comment]
I know. But if you implement dynamic texture updates the ability to do this per-player will basically exist as a free byproduct.

**Comment by Zughy** [comment]
Oh well, I trust your judgement
