### ISSUE TITLE
Meshnode size regression

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#15576]
### Luanti version

Since 21437090b80275f7967b7f5927ae0ead7f49d2e1. Still happens in master.

cc @sfan5

### Irrlicht device

SDL

### Operating system and version

Arch

### Active renderer

Tried both opengl and opengl3.

### Summary

Nodes with drawtypes mesh are rendered too big, it seems.

### Steps to reproduce

* Start Wuzzy's eyeballs game.
* `/level 1`
* Wuzzy's eye balls are huge!
* In particular: `eb_eyeballs:static_good_closed`, def: https://codeberg.org/Wuzzy/Eyeballs/src/commit/5e07e4fa778bc0751f306cc74a37e8fbbf937cab/mods/eb_eyeballs/classes.lua#L9-L31

**Comment by nininik0** [comment]
Can confirm on my server with player statue blocks, THEY ARE ABSOLUTELY HUGE when viewed by multicraft users

**Comment by appgurueu** [comment]
> THEY ARE ABSOLUTELY HUGE when viewed by multicraft users

That sounds like a different bug. Possibly a Multicraft bug. The changes in the commit responsible for this bug should not affect the server. (Also, are you even running a recent dev version on your server to begin with?)

What makes this bug odd is that, glancing at the diff, it doesn't (and didn't) seem like scaling was being touched at all. I would vaguely guess that it might be some "shared mutable meshes" kind of problem again. (Though really the diff looks inconspicuous even in that regard.)

**Comment by sfan5** [comment]
recalcuating normals resets the mesh animation as a side effect...

fix:
```diff
@@ -953,6 +954,9 @@ void ContentFeatures::updateTextures(ITextureSource *tsrc, IShaderSource *shdsrc
                                infostream << "ContentFeatures: recalculating normals for mesh "
                                        << mesh << std::endl;
                                meshmanip->recalculateNormals(mesh_ptr, true, false);
+                       } else {
+                               if (mesh_ptr->getMeshType() == scene::EAMT_SKINNED)
+                                       ((scene::SkinnedMesh*) mesh_ptr)->resetAnimation();
                        }
                }
        }
```

**Comment by nininik0** [comment]
> > THEY ARE ABSOLUTELY HUGE when viewed by multicraft users
> 
> That sounds like a different bug. Possibly a Multicraft bug. The changes in the commit responsible for this bug should not affect the server. (Also, are you even running a recent dev version on your server to begin with?)
> 
> What makes this bug odd is that, glancing at the diff, it doesn't (and didn't) seem like scaling was being touched at all. I would vaguely guess that it might be some "shared mutable meshes" kind of problem again. (Though really the diff looks inconspicuous even in that regard.)

I'm using normal 5.10.0 and also here is some screenshots I took of other multicraft player's videos and images of my server (kinda old but still happens)
![Uploading Screenshot_20241220-080314_YouTube.png…]()

**Comment by nininik0** [comment]
![Screenshot_20241220-075940_Chrome](https://github.com/user-attachments/assets/4f49bf2a-f25b-4561-921a-4beab9a34f84)

**Comment by nininik0** [comment]
![Screenshot_20241220-080314_YouTube](https://github.com/user-attachments/assets/b8215585-4f4e-49de-bf4a-b097c2281220)
![Screenshot_20241220-080258_YouTube](https://github.com/user-attachments/assets/ccd7027b-2bbc-42a4-a825-bb3af2df198c)
![Screenshot_20241220-075940_Chrome](https://github.com/user-attachments/assets/9391e1c8-579a-4972-a243-5bb6d17e3365)

**Comment by appgurueu** [comment]
@nininik0 Please report issues that are likely clientside and have only been reproduced with the Multicraft client to Multicraft, not to us.
