### ISSUE TITLE
core.raycast() does not work with liquids with `liquidtype = "none"`

### ISSUE THREAD

**Issue by cosin15** [minetest/minetest#15575]
### Luanti version

```true
Luanti 5.11.0-dev-debug-f99a1a7c7 (Linux)
Using LuaJIT 2.1.1719379426 (OpenResty)
Built by GCC 14.2
Running on Linux/6.11.0 x86_64
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_CURL=1
USE_GETTEXT=1
USE_SOUND=1
STATIC_SHAREDIR="."
STATIC_LOCALEDIR="locale"
```

### Operating system and version

Ubuntu

### Summary

I'm working on a pure lua implementation for the Liquid transformation.

It turns out that the function `core.raycast()` ignores liquids that do not set the `liquidtype`.

It breaks buckets.

`core.raycast()` should determine if something is a liquid by the `drawtype` instead. 

https://github.com/minetest/minetest/blob/a37bdbf8b7778336c6740f994164097ebb4129e6/src/environment.cpp#L103

`isLiquidRender()` could be used instead.

The cleanest solution might be to add an attribute to the node_definition: `liquid_builtin_transformation = 'none'`. This way `liquidtype` would be ignored by Luanti. And it would also not break mods that read the `liquidtype`

### Steps to reproduce

1. Comment out the `liquidtype` in the node_definition of a liquid source.
2. Run Luanit
3. Place the liquid with a bucket.
4. Try to grab this liquid with an empty bucket.

**Comment by grorp** [comment]
This could be fixed by using pointabilities and a custom liquid group instead

**Comment by appgurueu** [comment]
I am somewhat inclined to consider this "not a bug" or a feature request (and as grorp pointed out there is another, more flexible way to do this).

What is a liquid (for pointability purposes) anyways? I think `drawtype` isn't correct to go on either.

You would just get the opposite issue of "core.raycast() considers my non-liquid with liquid / flowingliquid drawtype a liquid". (And yes, non-liquid nodes which are drawn like liquids exist. For example I abused them to get a sloped moon surface for a moon lander game I haven't yet released a while ago.)

Saying "liquid is if liquidtype != none (if engine liquid flow logic is enabled)" seems sensible (note that the entire "liquids pointable" is a relict of the times when Luanti was more of a game than an engine). This need not extend to the new addition of liquidtype = none liquid drawtypes, these may be liquids conceptually or not.

Ultimately either is an okay choice and I don't see a justification for a breaking change here.

**Comment by cosin15** [comment]
> This could be fixed by using pointabilities and a custom liquid group instead

Thanks for pointing that out. I was not aware of that.
