### ISSUE TITLE
this sucks ass

### ISSUE THREAD

**Issue by meadowlovescaysen** [minetest/minetest#15589]
### Problem

problem- this is the crappiest code ive ever seen plz delete now 

### Solutions

DELETE IT

### Alternatives

nothing its that bad

### Additional context

if u wanna speak more plz contact me thru snap-thiscodeisass

**Comment by SmallJoker** [comment]
![oh no! anyway](https://i.kym-cdn.com/photos/images/newsfeed/001/881/867/6f6.jpg)
