### ISSUE TITLE
Water pools up at chunk borders

### ISSUE THREAD

**Issue by HeroOfTheWinds** [minetest/minetest#1558]
Exactly as the title says, when water flows downward, say, from a waterfall on a floating island, it will stop when it reaches a chunk border and then proceed to "pool" up on top of the unloaded chunk.  Furthermore, if said chunk is loaded afterward, the flowing water above is treated like a source block, continuing the flow in greater volume.

Would it be difficult to simply make water stop flowing if the chunk below is unloaded?

**Comment by HeroOfTheWinds** [comment]
I know I'm kinda dragging this back out of the grave, but nothing has still been done about it.  I was trying to look through the source code one night for the water flowing code (since I finally understand the C++ well enough), but couldn't find it. Anyone know where the liquid system's code is?

**Comment by Zeno-** [comment]
https://github.com/minetest/minetest/blob/master/src/map.cpp#L1623

I wish thee luck :3

**Comment by paramat** [comment]
I recently fixed this.
