### ISSUE TITLE
Tooltips don't work for dropdown, scrollbar, and more

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#1577]
e.g. if you point to content of a dropdown no tooltip is shown, the only way to get the tooltip is pointing exactly to the black frame around content.
For scrollbar pointing to the arrows doesn't show up tooltips. 
Maybe there are other gui elements not handled correct too.

**Comment by Wuzzy2** [comment]
Bug confirmed. Proposed issue title (for people with "issue renaming rights"): "Tooltips don't work for dropdown, scrollbar, and more"
