### ISSUE TITLE
Depend the selection box of players on their model

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1586]
Not sure if this has been posted already - well, it would be cool if the selection box around the player would +/- be around it.
Currently, it's just a single box, which does not even rotate.

**Comment by paramat** [comment]
@SmallJoker i guess you are referring to the selectionbox and not the collisionbox?
I don't think it's justified having a complex rotating selectionbox, rotation makes it so much more complex, and if it doesn't roatate then there's no point having it shaped like a player.
:-1:

**Comment by SmallJoker** [comment]
A shaped, rotatable selection box is what I had in mind. Surely, it would be a large improvement to have rotatable collision boxes as well but then we would need a much more complex collision detection code.
This is a long term goal for Minetest, so closing this issue doesn't seem to be appropriate.

**Comment by paramat** [comment]
Yes if we had shaped rotating collisionboxes, which is useful, then the selectionbox could be easily set to that, but it would not be worth doing this for selectionboxes only, that's what my -1 is for.
Related #2721

**Comment by paramat** [comment]
Rotating selection boxes or making them a complex shape will be complex and a lot of work, for no benefit, a simple non-rotating box works just as well :-1:

**Comment by SmallJoker** [comment]
Maybe it'll become again a discussion with a more complex physics and collision calculation. Closing for being too complex to add in the current state of development.
