### ISSUE TITLE
Colour codes in chat and console

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1587]
[Freeminer](https://github.com/freeminer/freeminer) has color codes for coloring chat and console messages, which is very useful. The patch was added before the license change, so it could be merged.

**Comment by rubenwardy** [comment]
Why do we still not have this?

**Comment by C1ffisme** [comment]
@rubenwardy A good question.

**Comment by beyondlimits** [comment]
related: #4077

**Comment by t4im** [comment]
@Ekdohibs Please reopen.

There is no support for:
* Console colors
* Background colors for chat
* Stripping of color codes for terminals without color support

**Comment by Ekdohibs** [comment]
@t4im #4077 was mainly for foreground colors in chat; formspec support came as a side-effect. The problem with background colors right now is that they affect the entire GUI element, which means the complete chat element will have a background.

**Comment by LunaSquee** [comment]
There's player interest.

**Comment by Calinou** [comment]
Colored chat and in-game console is now implemented. ANSI colors in the server's command-line interface aren't supported, but this is low-priority and deserves its own issue. Thus, this issue can be closed.
