### ISSUE TITLE
Allow limiting mapgen per world

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1608]
constants.h

> # define MAP_GENERATION_LIMIT (31000)

It would be very helpful if this setting would be configurable by world.

Reason: Testing servers which are public -> Walking players can create masses of terrain which results in a big database.
Also, an effective 100% limitation with mods is impossible.

Feature request.

**Comment by paramat** [comment]
2908 is merged.

**Comment by paramat** [comment]
2908 is merged but is not per-world.

**Comment by rubenwardy** [comment]
A much better solution would be to make worlds/world/minetest.conf and allow any setting to be world only.

**Comment by paramat** [comment]
See #5388

**Comment by paramat** [comment]
Related #4338 8

**Comment by paramat** [comment]
#5440 merged.
