### ISSUE TITLE
the possibillity to use "inf" as time parameter for /rollback should be documented

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1612]
maybe by setting the time to 0 or -1 or something

**Comment by paramat** [comment]
Old issue with no support. Anyone interested in coding this? If not closing in 1 month.

**Comment by DS-Minetest** [comment]
I think, there's no need for a change. The chatcommand params are given as a string and so the time is gotten with `tonumber`. Ergo you can write `inf` as time.

**Comment by iqualfragile** [comment]
never thought of that, that solves it.

**Comment by iqualfragile** [comment]
which pr contains the documentation change?

**Comment by paramat** [comment]
Reopening as this is a request for documentation.
