### ISSUE TITLE
minetest server hangs when connecting from outside local network

### ISSUE THREAD

**Issue by tofuhead** [minetest/minetest#1615]
I'm running minetest server, and connecting to it from another machine in the network with local ip addresses seem to work fine.. but using external ip doesn't. 
server seems to respond and notices user coming in, but then nothing happens on the client side, it gets stuck in middle of loading "media" .. couple of times i got a bit further and it loaded empty looking world.. 
port forwading is done.. (forwarding port 30000 udp/tcp) i'm running minecraft and pocket craft servers on this machine too.. they work. maybe there is something that i have to set up differently for minetest?

some server logs:
```
10:57:40: ACTION[main]: Server for gameid="minetest" listening on 0.0.0.0:30000.
10:57:43: INFO[ServerThread]: ServerMap: SQLite3 database opened
10:57:52: INFO[ServerThread]: Server: Maximum lag peaked to 1.5 s
10:58:09: INFO[ServerThread]: Server: New connection: "tofuhead" from 88.115.37.152 (peer_id=2)
10:58:09: INFO[ServerThread]: Server: Sending content to [id=2]
10:58:39: INFO[ConnectionSend]: con(5/1)RunTimeouts(): Peer 2 has timed out. (source=peertimeout_counter)
11:02:45: INFO[ServerThread]: Server: Maximum lag peaked to 2 s
```

I'm running this on ubuntu machines. I've tested stable version, nightly build version and now lastly compiled server and client both from git.. problem is same with each version.

bug, or did i miss something?

**Comment by nerzhul** [comment]
It's not a minetest issue and you didn't answer to @sapier since 5 month. Socket listening is done properly on minetest, it's a problem in your home configuration.

Thanks.

**Comment by ufa** [comment]
I am suffering this same bug. 
On LAN everything is fine. On Internet, nothing works :(

**Comment by ufa** [comment]
used values:

max_packets_per_iteration = 128
max_block_send_distance = 6
ax_packets_per_iteration = 128
