### ISSUE TITLE
[Request] ETA/Information/Status for /clearobjects

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#1620]
Hi.

I'd like minetestserver to give some information about the current status of a running /clearobjects command.
I believe this command takes long on most of the servers if not all. So it would be really useful if we could know some information about what's going on.

My suggestion is of info shown is:
Total Objects to be cleared:
Number of Objects already cleared:
Number of Objects to be cleared:
And if possible, elapsed time and remaining time.

That info could be shown on the console "window" (F10).

**Comment by est31** [comment]
IMO we should remove /clearobjects entirely and replace it with a mechanism that is much faster. It actually is doable, look here: https://github.com/est31/minetest/tree/fix_too_many_entities_bug

**Comment by kahrl** [comment]
Maybe "/clearobjects quick" should be made the default mode. It's much much faster and should be sufficient in almost all cases, and if not the admin can still choose the full mode by typing "/clearobjects full". If it turns out that most admins actually want full mode most of the time, the change can easily be reverted before the next release.

FWIW, /clearobjects already reports progress updates, albeit to infostream.

**Comment by Megaf** [comment]
@est31 https://github.com/minetest/minetest/issues/1620#issuecomment-246134513
Can you please elaborate on that? What is the alternative?

@kahrl https://github.com/minetest/minetest/issues/1620#issuecomment-246156831

**Comment by Wayward1** [comment]
@Megaf, "Do we already have the quick and full options?" Yes, added with #3673

**Comment by Megaf** [comment]
Ok, /clearobjects quick is indeed pretty quick. Well done @kahrl 
Still, some progress information or ETA would be nice.

**Comment by paramat** [comment]
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by Megaf** [comment]
@paramat Eh, don't close this.

**Comment by paramat** [comment]
Sorry for that temporary label, don't worry it's not a primary contender for a close, only being a year old.
Let's bump this and see if there is more support. A readout of blocks cleared is a good idea as in /emergeblocks. Objects to be cleared can't be known and remaining time can only be a rough estimate.
Is there currently no feedback at all? There should at least be 'blocks processed'.

**Comment by Megaf** [comment]
All that happens when you do a /clearobjects is a complete lock down, the game/servers becomes 100% frozen and eats all CPU it can find.

**Comment by Megaf** [comment]
Up

**Comment by Megaf** [comment]
@paramat I don't think this can ever be implemented with our current design. Closing the issue.

**Comment by paramat** [comment]
Why? Do you know the code cannot do what you want?

**Comment by Megaf** [comment]
Well,  the whole server hangs up in /clearobjects and there doesn't seem to be enough interest on this. That's why I closed it.

**Comment by paramat** [comment]
> BTW, /clearobjects already reports progress updates, albeit to infostream.

Ah, maybe if we just change this to warningstream it will appear in terminal.

**Comment by paramat** [comment]
PR #6657

**Comment by paramat** [comment]
#6657 merged.
