### ISSUE TITLE
v7 Mapgen decotation height limits and spawn by for schems

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#1621]
Would it be possible to add 'min_height' and 'max_height' to v7 mapgen decorations so they appear at specific limits (like some plants and trees do), also it would be handy to have 'spawn_by' working for schematics as well (palm trees spawn by water kinda thing)... thx

**Comment by kwolekr** [comment]
I have half of what you wanted here: https://github.com/minetest/minetest/commit/863379a4c68b9862ea6913c1b1e475d022aba100
DecoSchematic spawn-by isn't as simple because the concept of what's "by" a decoration is not quite clear.
