### ISSUE TITLE
new map functions for floating and underground mapgen

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#1626]
Please look into adding settings for v7 mapgen that allows for floating maps and underground maps carved into the rock, e.g.
```
node_top = "mymod:skydirt"
node_filler = "mymod:skysand" -- you get the idea
height_min = 200
height_max = 300
floating = true -- tells mapgen that perlin can be used to create floating islands with decoration
```
also...
```
node_top = "mymod:netherdirt"
node_filler = "mymod:nethersand"
height_min = -1000
height_max = -1300
ceiling_min = 10 -- sets a ceiling above carved out biome underground
ceiling_max = 20 -- only when ceiling set will it carve anything and place decoration

**Comment by paramat** [comment]
I'm working on alternative noiseparams for mgv7 that will create floatlands.
Mgv5 has code that makes it theoretically possible to add floatlands and an underworld, i might add these as an option.
If i create a new core mapgen it will certainly have floatlands throughout the atmosphere, to make full use of our world height.

**Comment by paramat** [comment]
Also, hmmmm aparently still wants to add an optional underworld for use in all mapgens, i will encourage him to do this.
So since these features are being worked upon i am closing.
