### ISSUE TITLE
Change Request: Playernames In-Game Are Too Small To Read

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#1627]
Change Request: Playernames in-game are too small to read.

Must:
- be increased

May:
- be increased depending on player to player distance

Maybe the Chat/Console lines could be increased too.
Also there should be about 2-3 more chat lines if console is closed.

Conditions:
- O/S resolution 1920x1200

**Comment by nerzhul** [comment]
Duplicate #1513 , i close it

**Comment by Megaf** [comment]
I'm not sure if duplicated, one is my the font size at any time, other is about font size according to distance.

**Comment by paramat** [comment]
Re-opening and folding #1513 into this as this contains that.

**Comment by paramat** [comment]
Do we have control over font size yet?

**Comment by Calinou** [comment]
> Are player tags the same font size as chat? What are they set to?

I'm quite sure they are set to the default font size (which is, at the time of writing, [16 pixels](https://github.com/minetest/minetest/blob/master/minetest.conf.example#L855)), and their size can't be changed separately from the chat font size.

**Comment by SmallJoker** [comment]
Please also note that this issue was opened when player name tags used the builtin font from Irrlicht, which is nothing more than minimalist pixelart. Since the default font size is used, this became less of a problem.

**Comment by paramat** [comment]
If they're the same size as the chosen chat font then there's no issue because they're just as readable.
Any larger and they begin to obscure too much , especially for multiple distant players.
A little larger for close players may be ok though.

**Comment by paramat** [comment]
> Please also note that this issue was opened when player name tags used the builtin font from Irrlicht,which is nothing more than minimalist pixelart. Since the default font size is used, this became less of a problem.

Issue is no longer relevant.
