### ISSUE TITLE
Single player worlds should be visible regardless of selected game

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1643]
Today, a player sent me [this image](https://cdn.mediacru.sh/bq8fqU845WS9.png). They were confused about not having any text in the world selection field.

What about showing the worlds regardless of the selected game, and instead differentiate the worlds by a prefix or suffix?

**Comment by rubenwardy** [comment]
the main menu is confusing generally, and needs to be  redesigned

**Comment by paramat** [comment]
Old issue, please can people restate their support for this?
It confused me too once but players will soon learn.
Subgmaes are essentially different games within the MT engine, so why would they contain worlds from other subgames?
:-1:

**Comment by Megaf** [comment]
@paramat That's your point of view, it may differ alot from the average joe point of view.

**Comment by paramat** [comment]
Yes, it's a point of view obviously :) many may agree with it too.
Thanks for restating your support.

**Comment by Megaf** [comment]
Maybe we should just add a checkbox "Show all worlds". Like on multi desktop DEs, we have the option to "Show windows from all desktops."

**Comment by LazyJ** [comment]
A checkbox to "Show All Worlds" would be nice.

**Comment by Megaf** [comment]
Or a button, "Show More"

**Comment by Megaf** [comment]
So, anyone making a PR for this?

**Comment by paramat** [comment]
No. It's low priority and dev is slow currently.

**Comment by paramat** [comment]
Any dev support?

**Comment by SmallJoker** [comment]
@paramat Yes. The players want this feature (a checkbox, possibly) for a long time, which seems reason enough to keep this open if it's what you had in mind.

**Comment by paramat** [comment]
This seems obviously wrong. MT is a game engine, you would not want worlds of other games showing up in a game. Players soon learn to click the icon to see worlds of other games.

**Comment by jastevenson303** [comment]
Show all worlds, automatically select the right game.

**Comment by SmallJoker** [comment]
> 'The players'? :) There are only 4 supporting in this thread

I see. Once again the discussion about a possible implementation makes it appear more demanded than it actually is. In exchange for less clicking to select the right game, more scrolling and checking for the right world is required. The idea is good when there are only a few worlds available or when new players don't know about different games - but the more worlds (and games) there are, the less usable this feature gets.
A PR to add that checkbox (plus .conf check-state setting) is however welcome.

Closing due lack of developer interest.
