### ISSUE TITLE
Player is not informed if keepalive ping to server fails

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#1654]
The Player should be noticed that the connection to the Player is interrupted.

There should be a big notice in the mid of the screen so it cant be overseen.
Client should automatically redo a reconnect after 10 seconds for the first time, 30 for the second retry and 60 for the third retry.
if the user pushes a reconnect button, the client will immediantly reconnect.
after 3 retries the client must be totally disconnected and forced to the menu.

**Comment by nerzhul** [comment]
@codeandfix i think protocol must handle, at first, a packet broadcasted to clients when shutdown. Second, a ping packet must be sent, else client will disconnect from server. It's commonly used in MMORPGs like World of Warcraft or Guild Wars

**Comment by sofar** [comment]
While auto-retry may not be necessary, it should at minimum be an option in the `escape` menu so that a player doesn't have to jump back to the menu. Ideally there's a prompt window as codeandfix suggests. Asking for a password sounds reasonable to me.

**Comment by red-001** [comment]
Hasn't this been fixed already?

**Comment by Fixer-007** [comment]
no, sometimes I receive RTT=-1 silently.

**Comment by iownall555** [comment]
As @sapier mentioned, the client doesn't store the pass. Would it be possible for the server to hand the client a token that the client can use one time to reconnect from the same ip? From there the client could attempt a reconnect, give the server the token and be allowed back on. Or perhaps just store the password for the session?

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by nerzhul** [comment]
If I remember this is fixed since 0.4.15

**Comment by paramat** [comment]
@Fixer-007 could you check?

**Comment by paramat** [comment]
Moving discussion to similar #4564
