### ISSUE TITLE
Configurable chat message display timeout

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#1655]
The Player should be able to change the chat message display timeout to a longer value.
Also, the size of the font should be configurable.
Maybe the numbers of shown messages could be changed too.

**Comment by paramat** [comment]
>  there should be a quicker non geeky/developer/nerd way of changing font size, in a configuration tab maybe

Done in advanced settings menu.

Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by SmallJoker** [comment]
The amount and duration of shown chat messages might still be a feature that some people would like to have. In these three years, it hasn't got much interest, so it's fine to close until players request this feature. Recent chat messages can be viewed easily in the chat window.

**Comment by paramat** [comment]
Can the full-screen chat window be scrolled back to messages that have gone off-screen?

**Comment by SmallJoker** [comment]
@paramat Yes sure. Even the page up/page down work there for faster scrolling.

**Comment by paramat** [comment]
Great, all issues addressed then.
