### ISSUE TITLE
Fake chatter problem

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#1659]
Turns out someone is able to post fake chatter on servers making it look like a player has said something they have not inc. swears and the like...  It's possible they were using a hacked client but would it be possible to add a failsafe to the chat where it checks if it's coming from the current player before displaying anything on screen for all to see?

**Comment by nerzhul** [comment]
i will push an option to limit characters allowed by server on chat someday permitting to limit this "hacky" problem, but please note that a real chat protocole could be better and would permit to have more features natively like whispers, channels etc
