### ISSUE TITLE
Example text for text fields (aka placeholder)

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1668]
The idea: http://i.imgur.com/3rRtY7a.png

This would solve the Admin and GuestXXXX problem - an example text which disappears if the field is activated/filled.

**Comment by SmallJoker** [comment]
The issue is not about missing space or bad described login fields. It's one of these features that would make the GUI more various and well designed. Not only the password input but also search fields or empty title fields would look better with a placeholder text.

**Comment by paramat** [comment]
Ok, removed my -1 for a general feature.

**Comment by numberZero** [comment]
These fashionable placeholders are ugly, annoying, and often make it unclear whether something is entered in the field. Also they can't be used if the field have a tiny chance to have default/remembered value as that would hide the label. So no, please do it the right way. That's possible, although maybe not with the current UI system.

**Comment by rubenwardy** [comment]
Placeholders are generally considered to be bad UX, as the placeholder disappears when you enter text

See https://www.nngroup.com/articles/form-design-placeholders/

**Comment by paramat** [comment]
I dislike placeholder text, messy and ugly.
The labels for the text fields should be present next to the text fields anyway so it is duplication.
:-1:

**Comment by rubenwardy** [comment]
Note that a comprehensive GUI framework should make this possible, but that doesn't mean we should use it
