### ISSUE TITLE
Texture glow-mapping

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1670]
It's quite simple: you overlay a texture (coloured or not) that always glows, regardless of the light level, on another texture. It should work with and without shaders. This is useful for some kinds of ores.

**Comment by paramat** [comment]
:-1: complex, just use the node defs instead.

**Comment by paramat** [comment]
Any support?

**Comment by raymoo** [comment]
I think it would be cool to have.

**Comment by juhdanad** [comment]
With hardware overlays I think it is implementable. I will try to code this.

**Comment by C1ffisme** [comment]
This could also be useful for Bloom... Because now you wouldn't have to make the computer figure out which parts of a node should glow, you just have to add the Blur effect.

**Comment by ThomasMonroe314** [comment]
@juhdanad any updates?

**Comment by juhdanad** [comment]
Not yet, sorry.

**Comment by ThomasMonroe314** [comment]
ok
