### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#1682]

**Comment by neoascetic** [comment]
The problem still appears (can use multi-byte character as world name, but it is not displayed correctly in the world list). Also unable to use multi-byte characters in the chat (however, it seems like others are able).

![screen shot 2015-03-29 at 12 55 08](https://cloud.githubusercontent.com/assets/725836/6885160/3a3177fc-d613-11e4-8d93-6a1eea969132.png)

![screen shot 2015-03-29 at 12 56 56](https://cloud.githubusercontent.com/assets/725836/6885164/5ed790f0-d613-11e4-82c9-31f0b9086387.png)

This is **not** related to translation. @ShadowNinja could you please reopen the issue? Or I should create new one?
