### ISSUE TITLE
set_physics_override: sneak_glitch=false does not work if sneak is true

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#1692]
Issue #1484 may have been fixed for mysterious reasons, but I may have found a similar bug.

Again, I am talking about a bug in `set_physics_override`.

It is now possible to disable sneaking by setting `sneak` to `false`.
But it appears that `sneak_glitch=false` only works if also `sneak` is set to `false`.

If `sneak_glitch` is `false` but `sneak` is `true`, then the sneak glitch is still working!

My test case:
I used the mod “luacmd” and typed in this in chat:

```
/lua me:set_physics_override({sneak_glitch=false, sneak=true})
```

I am using v0.4.10.

**Comment by wilkgr76** [comment]
Is this happening?

**Comment by Fixer-007** [comment]
Tried to reproduce this on today's build:
```
minetest.register_on_joinplayer(function(player)
	player:set_physics_override({sneak_glitch=false, sneak=true})
end) 
```

Sneak is working, but sneak ladders are not. Bug is fixed for me.

**Comment by Wuzzy2** [comment]
OK, if another user is failing to reproduce this bug, I think it is safe to close this issue as dubious.

**Comment by paramat** [comment]
> What I mean with “sneak glitch” here is that you can jump over a wall which is 2 nodes high

The 'sneak glitch' physics override is specifically the ability to sneak onto a ledge that is a single node of air in a flat wall, nothing other than this.
```
			// The node to be sneaked on has to be walkable
			node = map->getNodeNoEx(p, &is_valid_position);
			if (!is_valid_position || nodemgr->get(node).walkable == false)
				continue;
			// And the node above it has to be nonwalkable
			node = map->getNodeNoEx(p + v3s16(0,1,0), &is_valid_position);
			if (!is_valid_position || nodemgr->get(node).walkable) {
				continue;
			}
			if (!physics_override_sneak_glitch) {
				node =map->getNodeNoEx(p + v3s16(0,2,0), &is_valid_position);
				if (!is_valid_position || nodemgr->get(node).walkable)
					continue;
			}
```
The override controls whether 2 non-walkable nodes exist above the sneak node.
