### ISSUE TITLE
Optionally persist detached inventories across server restarts

### ISSUE THREAD

**Issue by jkoelndorfer** [minetest/minetest#1696]
When creating an inventory with the "detached" type, its contents should persist if you quit and re-enter the game.

**Comment by paramat** [comment]
@rubenwardy what is your opinion?

**Comment by rubenwardy** [comment]
it's worth allowing mods to at least serialize inventories nicely, even if it's not done automatically.

You could do `minetest.json_serialize(inv:to_table())` every time the inv changes, but that's a bit messy and inefficient.

**Comment by paramat** [comment]
I agree it could be made easier for mods to do if they want, but i disagree with making detached inventories persist by default, for reasons given by ShadowNinja.
