### ISSUE TITLE
Android: Certain views do not scale properly

### ISSUE THREAD

**Issue by easyaspi314** [minetest/minetest#1698]
Certain views in Android official builds do not scale to fit the screen, making parts useless on high-resolution and low-res devices. The main menu scales properly, the inventory - kinda, but submenus do not scale, becoming huge and unusable on a 3.8" 320x480 phone, and too tiny to touch on the Kindle Fire HD, (also, the KF's unusual behaviour of blocking font size and typeface makes this annoying. ) See screenshots below.

Also, the sneak button overlaps the hotbar. 
![screenshot_2014-09-28-15-58-31](https://cloud.githubusercontent.com/assets/6258309/4435543/f6cac692-4749-11e4-98b2-1cf6350a93e0.png)

The Config Mods on the Kindle.

![screenshot_2014-09-28-16-00-44](https://cloud.githubusercontent.com/assets/6258309/4435546/25d7c408-474a-11e4-94b5-2638dd70d6b0.png)

Kindle Settings

Also, can someone label this? Swype sent a submit, so I did not get to finish.

**Comment by sapier** [comment]
should be fixed in master as of 083d19b3fc8f60468e124c801296c13b66c41abc please test and give feedback

**Comment by sapier** [comment]
tested it's fixed on all of my devices
