### ISSUE TITLE
minetest.find_path constantly fails to generate path

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#1701]
I recently implemented an experimental pathfinding system for mobs in my Creatures mod. This allowed me to preform various tests for minetest.find_path, as I attempted to find the most optimal Lua method to use it. Here is the commit diff which shows my initial Lua function:

https://github.com/MirceaKitsune/minetest_mods_creatures/commit/baa748d4c892980455b1769cab9b802732062466

In latest GIT master of Minetest, minetest.find_path is broken to the point of being unusable. It almost always fails or errors out, due to being unable to find the path between the two positions. It only succeeds on occasion, and even then there's a chance that it returns an incomplete path.

The start and end positions are always above ground level, although I tested with buried nodes as well. I also tested with all 3 algorithms, and the result remains unchanged.

Please look into what's causing the engine function to fail so frequently, and if anything can be done to guarantee success when a path between the two points is possible.

**Comment by tenplus1** [comment]
Is there some way to disable the copious amount of error messages for pathfinding when it doesn't find a path available ?  They do get rather annoying and vastly increase the debug.txt file.

**Comment by JurajVajda** [comment]
:+1

**Comment by sofar** [comment]
I've spent some time looking into this. It appears that ```find_path``` does not consider plants to be "equal to air - can be walked through", and this causes find_path to consider itself stuck and stops immediately.

A solution would be to look at the ```walkable``` member in ContentFeatures instead of just looking at CONTENT_AIR, and treat plants with ```walkable = false``` identical to air, which would solve getting stuck in plants.

**Comment by sofar** [comment]
#4029

**Comment by sofar** [comment]
Note that #4029 doesn't fix the "stuck on edge - without grass" problem. I still see that occurring.

**Comment by Wuzzy2** [comment]
Is this bug still valid? This would explain some of the error spam I get with mobs.

**Comment by Wuzzy2** [comment]
> It seems to be a problem when the start position is on the edge of a node (when there is air under the starting node)

This ancient comment is 100% spot on, and still true in 5.2.0-dev. In my testing, I have noticed that when the start point is not directly above a `walkable` node, the function immediately fails and returns `nil`.

For example, if the start point is inside air, but only 2 nodes (or more) above a walkable node, the function fails, no matter how high you set `max_drop`.

The function seems to expect you always start directly above a walkable node. It's enough if only one block of air is below you to fail. So it's enought if you jump or stand at the edge of a node to trigger this bug. These are 2 very common situations.

Interestingly, the same is true for the end point. If the end point is not exactly above a walkable node, the algorithm fails as well.

My proposed solution:

For the start point: Before starting the search, simulate a fall until you hit a walkable node. If the simulated fall was within the allowed `max_drop`, start the search from this point. If the simulated fall was too deep, fail (which is expected).

For the end point, a fix isn't that trivial. Maybe check if the node could be reached by jumps or falling when the algorithm is very close to the end (low X/Z distance)

----

For testing, you can use my testing mod “testpathfinder” here: https://forum.minetest.net/viewtopic.php?f=9&t=23802

**Comment by Wuzzy2** [comment]
Fixed by #9339.
