### ISSUE TITLE
Error with map_meta.txt

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#1708]
From the latest -dev release (today), each time that you enter in a new world, it shows : 
```
ERROR[main]: ServerMap::loadMapMeta(): could not open /home/jp/.minetest/worlds/testworld/map_meta.txt
```
This file is created though.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/eeea454bff0cfcda495c20029a0246f63f14393e

**Comment by ShadowNinja** [comment]
eeea454bff0cfcda495c20029a0246f63f14393e is not a fix, it just ignores a real error.

**Comment by liuzhongjun** [comment]
But what should we do then ? I saw this error as I wanted to start server with a world.

**Comment by C1ffisme** [comment]
Why don't we just try checking for possible typos and such?

**Comment by ShadowNinja** [comment]
Sort-of fixed now, but not really.  #2211 is a proper fix.
