### ISSUE TITLE
Subsystem maintainers

### ISSUE THREAD

**Issue by kahrl** [minetest/minetest#1710]
This is mainly addressed to core devs.

Since RBA does not want to do it, I will write this issue:

1. Since @celeron55 doesn't do minetest development these days and client/audiovisuals has by far the most open issues, I think someone else should be the client/audiovisuals subsystem maintainer. Do you agree? Who do you think it should be?

2. What about the "maintainer conflicts" meta-subsystem?

3. Since proller is not developing minetest anymore someone else should be the masterserver maintainer.

4. Any takers for Build or Translation?

**Comment by kilbith** [comment]
I'm not a dev, but I'd support RBA too.

**Comment by nerzhul** [comment]
@kahrl @ShadowNinja does this issue needs to be opened ?

**Comment by paramat** [comment]
Subsystem maintainer system is not used anymore.
