### ISSUE TITLE
Water placed at y = 47 by lua mapgen is dark

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#1727]
![screenshot_3990385976](https://cloud.githubusercontent.com/assets/3686677/4553777/6290e4d0-4ea0-11e4-8859-4ed8bfa529a1.png)

This is voxelmanip lua mapgen, bug occurs only when generatiing chunks downwards (see comment below).
If anyone can advise me how to fix this in the lighting code i will test and make a pull request.

**Comment by kwolekr** [comment]
Hopefully fixed by this https://github.com/minetest/minetest/commit/7233a1228eb161cbcbb46c6e801cabd89ef3d2ab

**Comment by paramat** [comment]
![screenshot_3024273460](https://cloud.githubusercontent.com/assets/3686677/5605478/86065b80-93f5-11e4-9106-ebeee9860930.png)


Fixed when using a singlenode lua mapgen with flags="nolight", however when using vm:set_lighting({day=0, night=0}) dark patches appear and disappear:


![screenshot_3023303254](https://cloud.githubusercontent.com/assets/3686677/5605482/edcdb312-93f5-11e4-9d17-be840c1b32c6.png)
