### ISSUE TITLE
Advanced settings

### ISSUE THREAD

**Issue by Gael-de-Sailly** [minetest/minetest#1736]
I suggest to implement a dialog in the main menu to set any setting of the minetest.conf file (if you want more informations about my idea, see [this page of the forum](https://forum.minetest.net/viewtopic.php?f=5&t=10353&p=158258#p158258)). I'd like to try to do it myself.
The problem is : is it possible to get ALL of the fields of minetest.conf in the builtin LUA files ? I'm not able to write in C++.

**Comment by PilzAdam** [comment]
006ef5b4a5e362eed848ca26b411a8059d74b965
