### ISSUE TITLE
tools used in recipies get repaired (unintentionally)

### ISSUE THREAD

**Issue by lathan** [minetest/minetest#1741]
For example, [this recipe](https://github.com/VanessaE/moretrees/blob/master/crafts.lua#L102) uses coconut, drinking_glass, and a tool. You can put in a worn tool and it will return a new tool. Maybe there could be a way to expose wear in the api so that tools can be properly used in crafting?

Relevant discussion: https://github.com/VanessaE/moretrees/issues/9

**Comment by paramat** [comment]
Continue discussion iin #5323
