### ISSUE TITLE
Add mumble positional Audio

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#1753]
http://wiki.mumble.info/wiki/Link

**Comment by mwild1** [comment]
Any update on this, @iqualfragile ?

**Comment by falsechicken** [comment]
I would like to know as well. It would be a killer feature for me as it is something I have always wished Minecraft had for survival servers. I would like to have full positional audio (Similar to games like DayZ) where you cannot hear players until you get close.

**Comment by iqualfragile** [comment]
@mwild1 @falsechicken 
Well, i did test that patch i wrote, and it worked on linux x64 but i never tested it on other platforms.
There also seem to be a horrendous ammount of issuse with the code, which are mostly styling issuses, that i am in fact willing to fix, but the "moving it to the games recyable state" thing i am not so sure how to do, as i am not too familiar with minetests inner workings. if someone could mentor me on that i could fix it up (would base it on kaezas work so it might work on crappy platforms, but i can't really test that).
@hmmmm the dependency on shm is necessary as thats the way to talk to mumble. if there is some way to detect if its available on compile time, we should use that.

**Comment by rubenwardy** [comment]
Look at how LibSpatial is optionally used. At a guess when -DENABLE_LIBSPATIAL, a config is set in the config.h.i which you can then do #ifdef ENABLE_LIBSPATIAL

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/blob/master/src/CMakeLists.txt#L198-L211
https://github.com/minetest/minetest/blob/master/src/CMakeLists.txt#L567-L569
https://github.com/minetest/minetest/blob/master/src/cmake_config.h.in#L24

**Comment by iqualfragile** [comment]
@rubenwardy not quite sure what the relation between mumble positional audio and libspatial is.
there is no need to serialize anything for mumble.

**Comment by rubenwardy** [comment]
I meant that it is possible to optionally include a library.

> @hmmmm the dependency on shm is necessary as thats the way to talk to mumble. if there is some way to detect if its available on compile time, we should use that.

**Comment by Hiradur** [comment]
Anybody working on this? If not I'll give it a try.

**Comment by iqualfragile** [comment]
@Hiradur not that i know of, there is working code, but its considered ugly for the linked reasons (irc)

**Comment by Hiradur** [comment]
I'm almost finished now. Here is my implementation:
https://gist.github.com/Hiradur/94bb7414a40043b2a628

Please note that it is untested. I'm going to test it over Christmas. Any feedback and testing is welcome (particularly on Windows which I can't test on).

details:
- optional at build time (ENABLE_MUMBLE)
- optional setting at runtime (enable_mumble in mintest.conf)

Known issues:
- requires restart if enable_mumble is changed ingame.
- Option "Mumble positional audio" is visible ingame even if the game was built without ENABLE_MUMBLE (any idea how to fix this?)
- calculation of avatar direction and up vector depends on camera and thus is wrong in "third person front camera" mode

**Comment by iqualfragile** [comment]
There is no need to have the settings for run and compile time, especially not the setting for run time.
It costs like one function call and 7 variable sets each frame, which is ignorable so a run time setting is not necessary. The compile time switch is not needed in my opinion because it does not introduce any external dependencies or change any function. Maybe use the server/client flag instead, because having that on a server is really useless.

**Comment by Hiradur** [comment]
I made it optional at runtime because it could influence PvP games which some may not like.
I made it optional at build time because I'm not sure if and how shared memory works on Android and other platforms.

I have no problem with making it non-optional if the community demands though.

**Comment by JurajVajda** [comment]
hi guys, would be possible to test this already without re-building the minetest game, maybe even in some sort of lua mod ?

**Comment by iqualfragile** [comment]
as you need to set up shared memory, i think not.

**Comment by 0-afflatus** [comment]
I'll be ready to test this soon. It would be a great addition.

**Comment by tchncs** [comment]
Any news here? :)

**Comment by paramat** [comment]
:-1:

**Comment by paramat** [comment]
#3739 was closed, we consider it not worth doing.

**Comment by Erudition** [comment]
Minetest is still listed as supporting positional audio [on the wiki](https://wiki.mumble.info/wiki/Games).
looks like that's not the case?

**Comment by benrob0329** [comment]
There is a client-side mod for it [here](https://forum.minetest.net/viewtopic.php?f=53&t=21586).

**Comment by rubenwardy** [comment]
> Minetest is still listed as supporting positional audio on the wiki.

Minetest supports positional audio, it doesn't support mumble - an open source 3d voice chat system

**Comment by Erudition** [comment]
> Minetest supports positional audio, it doesn't support mumble - an open source 3d voice chat system

I know what Mumble is, that's why I linked to the Mumble wiki - which says it supports positional audio for Minetest. According to this bug, it does not. So given the context of this bug and the context of my link - Mumble - no, Minetest does not support positional audio. Only the in-game sounds are positional (which is unfortunate, especially considering Mumble and Minetest would make a great libre pair).

**Comment by benrob0329** [comment]
[Again, there is a clientside mod for it](https://forum.minetest.net/viewtopic.php?f=53&t=21586). So Minetest (the engine) supports it via a mod (the same as Minecraft's support according to the Mumble Wiki).

**Comment by Erudition** [comment]
If that works, that's great but it looks like it's actually more than a client-side mod - it needs to be run with a separate launching binary, which are of course all platform-dependent and fragile - even though all it does is redirect the positional data out of Minetest... something that Minetest could easily do natively without such a bulky hack.

Even if it doesn't get put in the core, it would still be better if it _was_ "just a mod", that worked out-of-the-box without some external binary, because then you could at least have an easier time getting your friends to use it. (It would still be impractical however to run a server based on it; you'd have to get everyone to install the client-side mod.)

Minecraft supports via mod, a mod that requires nothing but installation of the mod - no wrapper hack.

**Comment by benrob0329** [comment]
Minecraft mods also modify the source code. Minetest has refused both this and Discord rich presence, and I can't blame them. Adding in bits of code just for a single VoIP platform is silly for a game with such a small development team.

Really, someone should probably look at the Mumble Positional Audio interface and figure out what CSMs need to be able to interface with it natively (I'm assuming it's probably a local server type thing).

**Comment by Erudition** [comment]
> Minecraft mods also modify the source code. Minetest has refused both this and Discord rich presence, and I can't blame them.

Yup, exactly. Modifying the source code shouldn't be necessary and neither should wrapping the binary with another running alongside it. Nor should it be necessary to add voip-platform-specific code, especially for a proprietary platform like Discord. I think you hit the nail on the head with this:

> Really, someone should probably look at the Mumble Positional Audio interface and figure out what CSMs need to be able to interface with it natively

A client-side mod approach that "just works" would certainly make the most sense.

> Adding in bits of code just for a single VoIP platform is silly for a game with such a small development team.

Now that makes a lot less sense. Dev team size shouldn't have anything to do with whether a feature gets added, unless it's deemed to much work - but we've already established that there's not much to it. Very little code is required, the data is there but simply not exposed.

>  just for a single VoIP platform

...that being the only major gaming voip platform that is libre software like Minetest... If there were lots of competition, that'd be one thing, but Mumble is really the only viable player in this space that respects user freedom (unlike Discord) and thus can't be dismissed for not sharing Minetest's values. But again, universal generic support via CSM would certainly be better than anything platform-specific.

**Comment by davidebeatrici** [comment]
I updated our [wiki page](https://wiki.mumble.info/wiki/Games) mentioning the mod.

We also have a page explaining how to communicate with our Link plugin: https://wiki.mumble.info/wiki/Link
