### ISSUE TITLE
Mapgen V6 don't like altitude 47

### ISSUE THREAD

**Issue by Gael-de-Sailly** [minetest/minetest#1755]
I thought the hills were too small. So I changed the noise parameters and I realize that when the ground is high, there is a cleavage at y = 47.

Look at this, it's flagrant :
![Cleavage at y=47](http://i.imgur.com/xMhv61r.png)

47-48 is a chunk boundary. So it's probably a problem in the map generator. Could it be fixed ?

**Comment by paramat** [comment]
> I've already noticed lighting discontinuities. Jungle grass, leaves or water, for example, placed at y = > 47 are often dark
This was fixed recently.

> Is it because of these bugs that the mountains are so small by default ?
Yes sort of, restricting terrain to the surface mapchunk makes everything easier, simpler and faster.
