### ISSUE TITLE
Freezes when starting a game because of pulseaudio

### ISSUE THREAD

**Issue by random85** [minetest/minetest#1760]
My game freezed all the time after I clicked the "play" button. To solve the problem I had to kill pulseaudio (pulseaudio --kill).

I found this out running the game with gdb and I could see some stacktrace going throught libopenal. Unfortunately I couldn't reproduce the issue to have an exact stack trace, it might come later ...

As improvement, it was suggested on the IRC channell to add some timeout.

System: Up to date archlinux ...
Source: 7e34621b1de754449a5849f3ddfe8f77f32e64f5

**Comment by nerzhul** [comment]
I use archlinux with pulseaudio and this bug isn't present anymore.
