### ISSUE TITLE
Increase step height on Android

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1773]
To compensate for tricky controls on Android, increase step height in order to step on full nodes without jumping.

*This is just a suggestion, no working code here. This is probably doable with ifdef stuff.*

**localplayer.cpp** line **194**:
```C++
float player_stepheight = touching_ground ? (BS*0.6) : (BS*0.2);
```

On Android, it should be:

```C++
float player_stepheight = touching_ground ? (BS*1.1) : (BS*0.2);
```

**Comment by sapier** [comment]
fixed by 25235a432425e60b1b917adcc669449933403cb1
