### ISSUE TITLE
Split player's head and Crosshair

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#1774]
It is very difficult to play in third person  view because the player's head is covering blocks and dropped items. Try to pick up a dropped item in third person view, the Crosshair is always inside the head and you never see the item. 
![screenshot_6684571](https://cloud.githubusercontent.com/assets/6941454/4782687/23b4ef94-5d01-11e4-85b0-d7597fbd7f48.png)

**Comment by RHRhino** [comment]
@paramat I think this old issue can be closed. 
For people who also got annoyed by it, one solution is to use a mod that picks up dropped items like Calinou's modified version of Pilzadam's item_drop mod
https://github.com/Calinou/carbone-ng/tree/master/mods/item_drop

**Comment by paramat** [comment]
Ok, it seems there is an API for camera position also, i hope that does the job.
Closed on request.
