### ISSUE TITLE
Velocity ignored in function minetest.add_particle

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1789]
This some code spawns smoke - it does not have any velocity.

```Lua
minetest.add_particle({
	pos = pos,
	velocity = {x=0, y=2, z=0},
	size = 2,
	texture = "smoke_puff.png",
})
```

The velocity works fine with minetest.add_particlespawner()

![Example of a not moving smike particle]
(http://i.imgur.com/E517b5z.png)

**Comment by VanessaE** [comment]
It's an API "misprint" of a sort (see #1280), use vel={foo}.

**Comment by est31** [comment]
dupe of #1280
