### ISSUE TITLE
Allow usage of Android controls on desktop Minetest

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#1798]
Hi. i buy win 8 tablet and i can't play (no keyboard).
Please, add touch control in android port and go to Windows Market.
Thank you!

**Comment by paramat** [comment]
Any support?
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by paramat** [comment]
No support, and sapier is not keen, we have very little time for Android stuff, it's low priority. This request is for a rare situation and is possibly a lot of work. Also of course, touch controls are horrible and i can't see any justification for dev time to be spent on this..
So, sorry but an obvious close.

**Comment by HybridDog** [comment]
You could use qt5 for minetest formspec, couldn't you?
http://doc.qt.io/qt-5/qt5-intro.html

**Comment by basicer** [comment]
I made a brief attempt at this.  Qt5 didn't play so well with minetests event loop.

**Comment by HybridDog** [comment]
Thank you.
l think minetest doesn't work well on touch screens as long as there's the concept of a pointed node because with multi-touch you can point multiple nodes and objects at once.
