### ISSUE TITLE
Player and entity pitch visual appearance (moving player heads)

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1800]
Since Irrlicht can't manage bones correctly (find an hack to fix?), the proposal would be to show the player pitch at a 0.25 factor. This means the pitch value is divided by 4 then displayed.

So, the rendered pitch would be ±22.5 degrees, to not look too silly. This is what a few games like AssaultCube or Paintball 2 do.

**Comment by Calinou** [comment]
It is possible to do this with a server-side mod (which turns only the head), but it is an hack.

**Comment by sofar** [comment]
Ideally, this is done client side. The client should have all the data to adjust the head bone according to each player look direction. This does require that the player model has a consistently named bone for the head.

**Comment by paramat** [comment]
Movable heads #2716 has been rolled into this, which would be an excellent feature.

**Comment by LoneWolfHT** [comment]
If this is about making it possible for player heads follow their look dir I think this can be closed

**Comment by Calinou** [comment]
@LoneWolfHT I'd still like to have some kind of display for players' pitch angles , which would be especially nice in PvP :slightly_smiling_face:

**Comment by rubenwardy** [comment]
I believe object API changes has made this much easier to implement from a mod. Given that the player model is in MTG, this should be implemented in there with the engine only changing if extra support is needed

**Comment by sfan5** [comment]
> for example, to add client-side prediction to bone animations

There was #8335 for that but it was a big vague and is now closed.

**Comment by Zughy** [comment]
Please use the headanim mod: https://content.minetest.net/packages/Lone_Wolf/headanim/. Stale for more than a year with "possible close", closing
