### ISSUE TITLE
Update Android XML for (hopefully) better forward-compat

### ISSUE THREAD

**Issue by easyaspi314** [minetest/minetest#1801]
I have not tested this using Make, but I believe that setting the `android:targetSdkVersion="21"` in the Manifest and making a styles.xml for each Android version would add a bit of enhancement, allowing Android to stop running in backward-compat mode:

/res/values/styles.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.Transparent" parent="android:Theme.Transparent"/>
    <style name="MTTheme" parent="android:Theme.NoTitleBar.Fullscreen"/>
</resources>
```

/res/values-v11/styles.xml:

```
<?xml version="1.0" encoding="utf-8"?>
    <resources>
       <style name="Theme.Transparent" parent="android:Theme.Holo">
          <item name="android:windowNoTitle">true</item>
          <item name="android:background">@android:color/transparent</item>
          <item name="android:windowBackground">@android:color/transparent</item>
          <item name="android:colorBackgroundCacheHint">@null</item>
         <item name="android:windowIsTranslucent">true</item>
         <item name="android:windowAnimationStyle">@android:style/Animation</item>
  </style>
  <style name="MTTheme" parent="android:Theme.Holo.NoActionBar.Fullscreen"/>
</resources>
```

/res/values-v20/styles.xml:

```
<?xml version="1.0" encoding="utf-8"?>
    <resources>
       <style name="Theme.Transparent" parent="android:Theme.Material">
          <item name="android:windowNoTitle">true</item>
          <item name="android:background">@android:color/transparent</item>
          <item name="android:windowBackground">@android:color/transparent</item>
          <item name="android:colorBackgroundCacheHint">@null</item>
         <item name="android:windowIsTranslucent">true</item>
         <item name="android:windowAnimationStyle">@android:style/Animation</item>
  </style>

<style name="MTTheme" parent="android:Theme.Material.NoActionBar.Fullscreen"/>
</resources>
```

Finally, set the theme in the AndroidManifest.xml:

```
<application ... android:theme="@style/MTTheme">
   ...
<activity android:name=".MinetestTextEntry"
    ...
    android:theme="@style/Theme.Transparent"/>
```

**Comment by MoNTE48** [comment]
This works very well.

**Comment by sapier** [comment]
Ok here's missing something how to switch between the various styles for different android versions? Manually?

**Comment by easyaspi314** [comment]
No, you don't have to do it manually. For the default theme, put the theme
in /res/values/styles.xml.Holo theme, put it in /res/values-11/styles.xml
and for Material, do the same for values-v21. Make sure the styles have the
same name. The OS will automatically switch.

**Comment by sapier** [comment]
mentioning this change requires latest sdk would've been nice

**Comment by easyaspi314** [comment]
Sorry. :(

**Comment by sapier** [comment]
Nothing to be sorry for it's a good idea I just wanna know if those issues I saw happen for others too!
Maybe I'm doing something wrong.

**Comment by MoNTE48** [comment]
@sapier, on my project I use this code.
1) last SDK - 21.
Fix targetsdk on 21 on project.
2) this is very good.
I compile this and send you apk.

**Comment by easyaspi314** [comment]
An APK would help me too, as I can't compile it on Windows and my old
laptop is refusing to cooperate.

@sapier <https://github.com/sapier>, on my project I use this code.
1) last SDK - 21.
Fix targetsdk on 21 on project.
2) this is very good.
I compile this and send you apk.

--
Reply to this email directly or view it on GitHub
<https://github.com/minetest/minetest/issues/1801#issuecomment-69534858>.

**Comment by rubenwardy** [comment]
heh, I don't think this is really necessary. Apart from immersive mode, it seems to work perfectly fine for me. Maybe explain the problem more?
