### ISSUE TITLE
Incorrect inventory images displayed

### ISSUE THREAD

**Issue by JohnnyComeL8ly** [minetest/minetest#1838]
The display of textures in the game is fine except for in the inventory bar/panel_where_you_can_craft_items. The items, for reference, are Dirt, Coal Block, Cobblestone, and Bookshelf (they are ordered that way in the inventory too).  The time of day is 12000, just in case you can't tell from the images. :-D
Without preload_item_visuals:
![without_preload_item_visuals](https://cloud.githubusercontent.com/assets/9731801/5040313/3bec240e-6b72-11e4-8110-db27de394750.png)
With preload_item_visuals:
![with_preload_item_visuals](https://cloud.githubusercontent.com/assets/9731801/5040319/51000f7c-6b72-11e4-9456-dcf265795e11.png)
Without preload_item_visuals (inventory):
![without_preload_item_visuals-inventory](https://cloud.githubusercontent.com/assets/9731801/5040347/cea5748a-6b72-11e4-890e-34faa414ab56.PNG)
With preload_item_visuals (inventory):
![with_preload_item_visuals-inventory](https://cloud.githubusercontent.com/assets/9731801/5040338/9cdca22a-6b72-11e4-8275-4a4374db679e.PNG)
This is from the last time I opened the game.
```
Irrlicht log: Irrlicht Engine version 1.8.1
Irrlicht log: Microsoft Windows XP Personal Service Pack 3 (Build 2600)
Irrlicht log: Using renderer: OpenGL 1.4.0
Irrlicht log: Intel 945GM: Intel
Irrlicht log: OpenGL driver version is 1.2 or better.
Irrlicht log: GLSL not available.
Irrlicht log: Resizing window (800 580)
18:31:18: ACTION[main]:         .__               __                   __   
18:31:18: ACTION[main]:   _____ |__| ____   _____/  |_  ____   _______/  |_ 
18:31:18: ACTION[main]:  /     \|  |/    \_/ __ \   __\/ __ \ /  ___/\   __\
18:31:18: ACTION[main]: |  Y Y  \  |   |  \  ___/|  | \  ___/ \___ \  |  |  
18:31:18: ACTION[main]: |__|_|  /__|___|  /\___  >__|  \___  >____  > |__|  
18:31:18: ACTION[main]:       \/        \/     \/          \/     \/        
18:31:18: ACTION[main]: World at [C:\Documents and Settings\lisa\Application Data\Minetest-0.4.10-win32mingw\bin\..\worlds\Test]
18:31:18: ACTION[main]: Server for gameid="minetest" listening on 0.0.0.0:61066.
Irrlicht log: PNG warning: Interlace handling should be turned on when using png_read_image
Irrlicht log: Could not open file of texture: 
Irrlicht log: Could not open file of texture: 
Irrlicht log: Could not open file of texture: 
18:31:24: ACTION[ServerThread]: singleplayer [127.0.0.1] joins game. 
18:31:24: ACTION[ServerThread]: singleplayer joins game. List of players: singleplayer
Irrlicht log: Could not open file of texture: 
Font size: 8 17
Irrlicht log: Could not open file of texture: character.png
```

**Comment by est31** [comment]
Commit 6cd2b3b445bf558fda1e5a7908adef8e3a45449a has hugely changed how we draw item images, so most likely any underlying bug should be now not reproducible anymore. Please report if you still can reproduce the bug with the new code.

**Comment by JohnnyComeL8ly** [comment]
It works, but shaders are still broken... probably due to the driver.  I'm using default settings except for these:
Shaders, ScreenW, and Fullscreen

**Comment by Trixarian** [comment]
Shaders will probably never work properly. This is due to the Series 3
Intel GMA chipsets not having Vertex Shaders at all.

**Comment by JohnnyComeL8ly** [comment]
Ok, that's nice to know. :-D

**Comment by est31** [comment]
Hrmm, wontfix then?

**Comment by Trixarian** [comment]
Yeah - on Linux MESA uses emulation to get around it and give true OpenGL
2.1 support. On Windows modded drivers use Intel Intel's built in emulation
(meant for just the GMA 965 - but modders like making things equal) to work
around it on Vista or better. Might be possible for XP using the GMA 3150's
driver since it's structure is similar to Vista and Windows 7, but still
works with XP. Most of the Series 3 chipsets are interchangeably compatible
with each other's drivers, so there might be some hope left. Haven't tested
it yet, but would be nice to being Software Vertex Shaders to XP if I'm
right. You'd be at least be able to play Portal on it then. Sorry, that was
a bit off topic...

**Comment by Trixarian** [comment]
Wontfix is probably good. Even with software emulation of Vertex Shaders it
doesn't work well for Minetest. Like most, I just disable them.

**Comment by JohnnyComeL8ly** [comment]
So, I shouldn't bother using https://userscloud.com/i7fx37xfg9j4
?

**Comment by Trixarian** [comment]
As the person that made it, yes for a performance point of view, but it
won't help with Vertex Shaders. I need to setup a XP partition again to do
proper testing to see if my hypothesis of the GMA 3150 driver pans out.

**Comment by JohnnyComeL8ly** [comment]
Ok, gotcha.
