### ISSUE TITLE
Map-related FPS performance regression

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#184]
I can't pin down when this started, but there is a serious performance issue that's been cropping up.

Rather than trying to explain it, just try this not-quite-so-simple test procedure:

Build 0.4.1, 0.4.2-rc1, or really anything somewhat recent (maybe several weeks old at most).
Do not install any mods or create a config file - that is, leave everything in its 'factory fresh' state.
Start the game and create a new world using minetest_game.
Find a part of the world that's mostly flat and fairly low-elevation (less than 5m above sea level if possible).
Exit the game to the OS, then immediately restart it and go back into the world.
Set your view distance to 145.
Give yourself fly privilege.
Walk or fly around until you've got perhaps 10x10 or so MapBlocks loaded.
Navigate back to the middle of the loaded area.
Set time of day to 7000.
Set your view distance to 150.
Make sure the full viewing range is *disabled* (the default)
Look straight down at the ground.

Now fly up, down, and around - but keep your view pointing straight down at the ground.  Fly around only *just* enough to make sure all parts of the visible map are actually loaded, but try to stay close to your X/Z starting point.

Observe the change in your FPS as you rise up and as more of the map is loaded.

Keep flying up and stop at 50m, but keep looking down.

Observe your FPS at that height.

Now, drop back down and fly around a fair bit more, but in a larger radius so that more of the map gets loaded/generated.  When you've got about two or three times as much of the map loaded as before, return to your starting point at 50m up.  Keep your view pointing down at the ground at all times.

Observe your FPS again.

Finally, just start flying around the map, getting a whole bunch of it to load up - give it a good 5 minutes just flying around, leaving the map generator to load up normally as you go.

Return to your 50m-high starting point

Observe your FPS again.

Note that this whole time, you've been flying around with the "full viewing range" option disabled, as most people probably use the game.

Without looking up, hit escape and move the game into the background.  Go off and do some other task, e.g. chat or browse the web or whatever.

After 5 or so minutes, bring the game back to the foreground and hit escape again to cancel the exit menu.

Wait a few seconds, and observe your FPS.

Now, turn your gaze back to horizontal - you'll notice that, as is normal, the game has unloaded/discarded much of the area that wasn't visible when you were looking at the ground.

For my setup, the conclusion here is pretty obvious - the more of the map I have loaded, whether I can see the the extra stuff or not, the worse the performance gets, until the game starts throwing away old map blocks.

On my 2.8 GHz Phenom II 6-core machine with a Radeon HD6870 video card, I might see 55 to 60 FPS at first, but after enough of the map is loaded, this frame rate becomes only a memory.  In the above test, it gets as low as 19 FPS once a lot of the map has been loaded - which is WAY slower than this card is capable of, and one of the six CPU cores is pegged a 100%.

This machine runs Xubuntu Linux 12.04, AMD64 version, with fully up-to-date system software, up-to-date binary blob ATI video driver, and a copy of 0.4.2-rc1 I compiled from github sources today.

A number of other users with a variety of video cards and base hardware have reported similar performance loss.

**Comment by nerzhul** [comment]
@VanessaE can you confirm this issue or close it ?

**Comment by C1ffisme** [comment]
Wow. I think when you go through a procedure like that, then you really want to fix bugs.

**Comment by nerzhul** [comment]
yes @C1ffisme but some bugs are always there, and some core-dev must go to the mt issue cave and find the issues from the depths :p

**Comment by C1ffisme** [comment]
Hmmm... Someone needs to rewrite minetest at some point, maybe. Perhaps we should make it a little easier to see what you are doing in C++. I had trouble just geting torches to appear in dungeons. LOL.

Minetest has an excess amount of preformance issues. Maybe we should see if the same problems appear if we were to write a game in another 3d language rather than Irrlicht.

**Comment by VanessaE** [comment]
I can't be sure if this is still a problem, but ShadowNinja is surely still correct about the structure of Minetet's meshes.  That being the case, my totally unqualified opinion is that this is still a problem, if less noticeable than it used to be.

**Comment by Cyberpangolin** [comment]
I want to report a similar issue: Even if I did not exactly VanessaE's protocol, my core i7 is on its knees after a small amount of time. I have 1 thread at 100%, and everything else is waiting on it. My gtx750 is used only at 30% of its capacity. and I have tons of RAM still available. I would be happy to make further investigation ingame, if they can be useful. But, my apologizes, I cannot code.

**Comment by paramat** [comment]
Thus seems to old, obscure and unconfirmed to be kept open, can we close? @VanessaE
