### ISSUE TITLE
Singlenode:  Failed to resolve 'mapgen_water_source'

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#1840]
If you load a game with singlenode mapgen which does not contain 
`minetest.register_alias("mapgen_water_source", "default:water_source")`
you will get the error: 
`'ERROR[main]: NodeResolver::resolveNodes():  Failed to resolve 'mapgen_water_source'`
This error is a bit weird when you want to create a mapgen/subgame which does not contain water.

**Comment by est31** [comment]
@neoascetic this was the bug we spoke about earlier on irc.

**Comment by neoascetic** [comment]
It is pretty old

**Comment by paramat** [comment]
Because i added river water to the biome API as a base terrain node it will be expecting that mapgen alias in subgames.

**Comment by paramat** [comment]
RHRhino hope you don't mind me closing this.

**Comment by paramat** [comment]
Reopen as a reminder, i suggest downgrade to warning.

**Comment by paramat** [comment]
What i can do is add a bool argument to
https://github.com/minetest/minetest/blob/3face01a202040e4feff3b0936b4aa89c051c98d/src/nodedef.cpp#L1623
that decides whether that error is logged, and disable the error here:
https://github.com/minetest/minetest/blob/746ca41f58e356b0fbeeca1b43b7061ad1e1c02d/src/mapgen/mg_biome.cpp#L318

**Comment by paramat** [comment]
PR #7256

**Comment by paramat** [comment]
#7256 merged.
