### ISSUE TITLE
minetest sometimes fast sometimes slow

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#1841]
Hello
On My ZBox (Atom 1,8GHz dualcore 4GB NVidia) Computer
Minetest at start sometimes works fine (24FPS) sometimes it hacks (between  1 and 12FPS)
I´ve set the wished and maximum FPS to 24 in my minetest.conf, if I stop the Programm reapetadly it works after restart 1 to 20 times until restart sometimes.
I am using Kubuntu 14.04 LTS OpenGL 3.3.
This happens since one of the last Updates. There are no errors on the Console or in the Log.
Sorry that I can´t say better.
Thanks,
JPR

**Comment by paramat** [comment]
@JPRuehmann Old issue and we've had lots of changes, still a problem? Will close in 1 month if no response.

**Comment by paramat** [comment]
Closing.
