### ISSUE TITLE
rollback memory leak

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#1846]
There appears to be a severe memory leak in rollback of actions.  This is a screenshot of the last few hours' worth of stats on my servers taken right after I noticed that an incident had occurred (I was away at the time):

![image](https://cloud.githubusercontent.com/assets/1733537/5312418/49378c32-7c27-11e4-982a-53d211c041e5.png)

Those two sudden spikes in memory at ~14:40 and 16:20 are from a couple of rollback checks followed by rollback/undo actions done by one of my admins did while I was out. The screenshot shows the typical behavior of this server (save for the CPU activity from 08:00 to 10:15, which was caused by a different Minetest instance and is probably unrelated to this issue).

In the server's log, there was nothing printed associated with the event except a "Killed" message; `dmesg` reports that the OOM killer nailed it.

This is a system with 8 GB of physical RAM and another 512MB of swap.

It is the rollback/undo action itself is where the memory leak lies, apparently; my admin reports that the rollback checks merely "took forever", but the actual undo actions were what precipitated the crashes.

**Comment by nerzhul** [comment]
@VanessaE can you confirm your issue ?

**Comment by VanessaE** [comment]
I've since had to disable rollback on the servers affected.  It's just taking way too many resources to be of any use anymore.

**Comment by ShadowNinja** [comment]
Maybe valgrind's massif or memcheck tools would find the issue.

**Comment by Megaf** [comment]
@VanessaE https://github.com/minetest/minetest/issues/1846#issuecomment-86105309
Yep, I did the same in my server, the benefit of having rollback now is too little compared to the headache of having it enabled.
Unfortunetaly.
