### ISSUE TITLE
Wield item is always fully bright

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1860]
**This is only with shaders enabled.** With shaders disabled, it works fine.

1. Walk or fly into a dark area.
2. Look at your wield item (happens with any, even an empty hand)
3. The wield item is fully bright, even though it should be dark.

**Comment by Calinou** [comment]
This appears to be fixed, maybe this should be closed.

**Comment by Megaf** [comment]
It is fixed indeed. Can be closed.
