### ISSUE TITLE
[Proposal] Organize minetest.conf settings in namespaces

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1865]
Currently, settings are quite disorganized. A way to solve this would be to add namespaces to the settings. This would likely break compatibility with older clients and servers (they would have to rename the old variables to the new ones, which could be sped up with a script).

Thus, I suggest using the following namespaces for settings, which would be prepended to the current settings:
- `core` for the settings in the C++ code, or builtin Lua.
  - `common` for settings that impact both the client and server.
  - `client` for settings that impact only the client.
  - `server` for settings that impact only the server.
- `mods` as a general namespace for settings that impact several or all mods.
- `*mod_name*` for settings that impact only a single mod or mod pack. Mods are then free to add their own sub-namespaces if they wish.

Example setting name/functionality changes:
- `enable_clouds` ⇒ `core.client.clouds` or `core.client.clouds.enable`
- `enable_3d_clouds` ⇒ `core.client.clouds.3d` 
- `disable_fire` ⇒ `fire.enable`
-  `log_mods` ⇒ `mods.log`

Most setting names will be longer, but I think it is worth it.

**Comment by PilzAdam** [comment]
Kinda done in 006ef5b4a5e362eed848ca26b411a8059d74b965, though only in GUI and `minetest.conf.example`.

**Comment by paramat** [comment]
@Calinou thoughts on this now we have the new settings menu?

**Comment by t4im** [comment]
Ordering by most significance would certainly be nice. And it seems with mod-security `secure.*`  (and probably soon mod-profiling) that will already start spreading for additions.

**Comment by rubenwardy** [comment]
This is done in a way using setting types. Frankly I'm not sure the cost of changing everything and keeping backwards compat is worth it

**Comment by paramat** [comment]
:-1: We now have advanced settings menu so using .conf for settings is not necessary. The advanced settings menu already groups settings into a tree to organise them. Also, not worth the work.

**Comment by Megaf** [comment]
@paramat in a server environment we don't use the menu at all, as we have is the minetest.conf file to set our settings.

But anyway, I agree this is not necessary.
