### ISSUE TITLE
Error on server shutdown: master-server/announce not found (HTTP response code said error) (response code 500)

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#1881]
Hi, there is a little issue here.
When we shutdown the minetest server, either using /shutdown or ctrl +c it throws the following:
```
07:12:19: ACTION[ServerThread]: MegafAdmin shuts down server
07:12:19: ERROR[CurlFetchThread]: servers.minetest.net/announce not found (HTTP response code said error) (response code 500)
```

That is not really a bug since it works during regular operation.

**Comment by paramat** [comment]
@Megaf still an issue?

**Comment by Megaf** [comment]
fixed, not sure when. @paramat
