### ISSUE TITLE
Lava/drowing damage is calculated on client-side only

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#1894]
Is this OK? I mean, I can simply recompile client without corresponding code and have no damage on any server.

[![](https://www.bountysource.com/badge/issue?issue_id=6664294)](https://www.bountysource.com/issues/6664294-lava-drowing-damage-is-calculated-on-client-side-only)

**Comment by nerzhul** [comment]
@ShadowNinja is not the problem, this handling permit to client to bypass every damage wit ha special crafted client on PVP servers and damage_enabled servers.
This will be fixed by the 0.5. Having a client side breath/damage is unacceptable.

**Comment by neoascetic** [comment]
However, about `fleshy` armor group, there may be octopuses or fishes which, obviously, must not drown.

**Comment by bdjnk** [comment]
While I agree that client side breathing and damage are no good, I don't accept that this should result in any user noticeable lag. What is needed is proper client-side prediction (here is [an excellent technical overview](http://www.gabrielgambetta.com/fast_paced_multiplayer.html)). This is actually generally applicable, as requested here #1072

**Comment by nerzhul** [comment]
This is fixed in the 0.4.16 i did it.

**Comment by nerzhul** [comment]
Fixed by #4981

**Comment by neoascetic** [comment]
Finally, thanks!
