### ISSUE TITLE
font_size setting broken

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#1896]
The `font_size` setting in minetest.conf seems to be ignored. It's only applied to the version string in the top-left corner and the progress bar when connecting to a server, or loading a world.

**Comment by sapier** [comment]
font size setting doesn't do what it did do by now. It's now only usefull to do finetuning for custom fonts. If you want to have bigger ui elements use gui scaling setting.

**Comment by PilzAdam** [comment]
@sapier that is not good. This and also #1897 show that one setting for GUI size is just not enough.
I would like to change the font size or hotbar size without changing the size of the inventory. The previous behavior was better.

**Comment by sfan5** [comment]
This was fixed in some commit.
