### ISSUE TITLE
Numblock does not work in text entry fields, left/right instead of 4/5

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#1898]
The numblock does not work correctly in entry fields. For example the "New World" window, when entering the name, then 0, 3 and 9 are working correctly on the number block, but the other keys are trying to execute their designated function, like left, right, up and down.

This happens under Ubuntu 14.04 with a US keyboard/layout.

**Comment by ngosang** [comment]
It's an Irrlicht problem. I compiled minetest with Irrlicht 1.9 (development) and the problem is fixed.
http://sourceforge.net/p/irrlicht/code/HEAD/tree/trunk/

**Comment by paramat** [comment]
Closing as is upstream issue and fixed in Irrlicht 1.9.

**Comment by debagos** [comment]
Soooo here we are now, with a forked Irrlicht :sweat_smile:
Is there an possibility that we will be able to use _copy&paste_ as expected in the future?

**Comment by sfan5** [comment]
The bug for that is still open, it'll probably get fixed before 5.5.0 -> #7830

**Comment by debagos** [comment]
Oh sorry, I confused two tabs in my browser :neutral_face:
Of course my question was meant for the #7830 issue...
