### ISSUE TITLE
save the attachments of all players

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#1915]
Engine doesn't save the attachments of all players and re-attach them on join. This would be useful for some mods such as the boat mod. Here is an issue related to this problem: https://github.com/minetest/minetest_game/issues/265

**Comment by MT-Modder** [comment]
Closing in 2 weeks if no response.

**Comment by rubenwardy** [comment]
What if someone else wants to use the boat whilst the player is offline?

**Comment by MT-Modder** [comment]
True and a mod could simply save the attachments on_leave, then reattach on_join.
