### ISSUE TITLE
lua_api.txt ⇒ lua_api.md

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#1919]
Basically, rewrite `doc/lua_api.txt` to use Markdown.

Discuss, if you think another format is better. I think this is a big improvement over using raw text.

I volunteer to do it, but would rather ensure it gets merged.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/800d912b6f93b4e9e6efdc89b9e7a720807f2b1a
