### ISSUE TITLE
TAB auto complete will no longer work on console.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#1934]
Hi all, TAB is no longer auto completing nicks on the game console.
I noticed this on https://github.com/minetest/minetest/commit/dcc48976ce92dc0385037e8bf16075396bcb6943

I dont know when it started.

**Comment by Megaf** [comment]
:bug: 
Bug still present, OS X Yosemite and on Debian 8 GNOME at least.

**Comment by Megaf** [comment]
Can someone please try to compile Minetest with this?
cmake -DRUN_IN_PLACE=1 -DENABLE_FREETYPE=1 -DEUSE_FREETYPE=1 -DENABLE_LEVELDB=0 -DENABLE_REDIS=0 -DBUILD_SERVER=0

And then login to a server and see if TAB works to complete names in the games console?

**Comment by Megaf** [comment]
Still present. I can still reproduce on my Debian computers, version 7 and 8, 64 bit with XFCE and GNOME and on my Macbook Pro with OS X Yosemite.

**Comment by paramat** [comment]
@Megaf still an issue?

**Comment by Fixer-007** [comment]
Does not autocomplete, Win7 sp1 latest git.

**Comment by Megaf** [comment]
Still not working on Linux either

**Comment by Megaf** [comment]
Seems to have been fixed.

**Comment by Megaf** [comment]
Nick auto complete no longer works again, not working either in F10 console nor on server console.
And, did we have an auto complete for commands? If we did, it's now working again.
Sorry, can't track the commit that caused that.

**Comment by Fixer-007** [comment]
I've noticed that too, sometimes it works, sometimes it is not. I can confirm the bug again!

**Comment by est31** [comment]
It was said on IRC that the bug is spurious.

**Comment by SmallJoker** [comment]
Can confirm too. Very annoying sometimes.

**Comment by wilkgr76** [comment]
It seems that when the nametag is not in range (ie not being displayed), then the tab autocomplete doesn't work.

**Comment by ExeterDad** [comment]
Bingo! @wilkgr76 nailed it. I can reproduce every time now. This has been killing my trying to understand why it would only work sometimes.

**Comment by sfan5** [comment]
This is pretty simple, if the server doesn't tell MT about the clients positions (because they are e.g. too far away) then the client doesn't know about them and can't tabcomplete their name.

**Comment by rubenwardy** [comment]
this doesn't seem like a bug to me, then

**Comment by Megaf** [comment]
I'm quite sure in the past we had autocomplete for commands too. Since before I opened this bug, everything is broken.

**Comment by wilkgr76** [comment]
We did indeed, but not in a stable version I believe.

**Comment by HybridDog** [comment]
There's autocomplete for commands using client side modding: #5532

**Comment by Megaf** [comment]
@wilkgr76 has it ever been a stable version? We are in aplha state.

**Comment by wilkgr76** [comment]
@Megaf I was using *stable* loosely here. I meant a proper release, such as 0.4.16.

**Comment by paramat** [comment]
> This is pretty simple, if the server doesn't tell MT about the clients positions (because they are e.g. too far away) then the client doesn't know about them and can't tabcomplete their name.

So not a bug, expected behaviour, and doesn't seem worth trying to make auto complete work in this situation.

**Comment by wilkgr76** [comment]
It's not expected behaviour for people who don't know why it is happening. Expected behaviour, for normal players, is to have autocomplete work for _all_ names.

**Comment by paramat** [comment]
If the client has no information about a distant player, then auto-complete cannot happen, it's as if the player does not exist so impossible to do anyhting about it.
Rationally it's expected behaviour, players just don't understand that distant players are not sent to the client.
