### ISSUE TITLE
deactivatefarObjects error/warning / engine creating "ghost" entities

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#194]
A user on the forums experienced the following while using PilzAdam's carts mod, and I've received a somewhat unclear comment from another suggesting what is probably the same error, while using my flowers mod.   I doubt the mods themselves have anything to do with it though:

error[serverthread] serverenvironement deactivatefarObjects(): id=74 m_static_exists=true but static data doesn't actually exist in (3,0,-2)

I have seen this in my logs as well, in 0.4.1 stable and 0.4.2-rc1, but I haven't noticed any ill effects from it.

EDIT, 2015-03-10:  This still occurs with 0.4.12 and git HEAD from later than that, and the aforementioned lack of "ill effects" no longer applies.  See later comments.

**Comment by nerzhul** [comment]
Is this issue already present ?

**Comment by dgm3333** [comment]
Do you mean *still* present (in which case the answer is yes).
More recently I would have thought it occured if a particle object is sent into the distance and not destroyed (but again just a theory)

**Comment by VanessaE** [comment]
Still present.  Here's something a bit more useful:
```
01:22:43: ERROR[ServerThread]: ServerEnv: Trying to store id=39452 statically but block (-43,1,-28) already contains 686 objects. Forcing delete.
01:22:45: ERROR[ServerThread]: ServerEnv: Trying to store id=39453 statically but block (-43,1,-28) already contains 686 objects. Forcing delete.
01:22:45: ERROR[ServerThread]: ServerEnv: Trying to store id=39454 statically but block (-43,1,-28) already contains 686 objects. Forcing delete.
01:22:47: ERROR[ServerThread]: ServerEnv: Trying to store id=39455 statically but block (-43,1,-28) already contains 686 objects. Forcing delete.
01:22:49: ERROR[ServerThread]: ServerEnvironment::deactivateFarObjects(): id=39457 m_static_exists=true but static data doesn't actually exist in (-43,1,-28)
WARNING: StaticObjectList::remove(): id=39457 not found
01:22:49: ERROR[ServerThread]: ServerEnv: Trying to store id=39457 statically but block (-43,1,-28) already contains 687 objects. Forcing delete.
01:22:51: ERROR[ServerThread]: ServerEnv: Trying to store id=39459 statically but block (-43,1,-28) already contains 687 objects. Forcing delete.
01:22:53: ERROR[ServerThread]: ServerEnv: Trying to store id=39460 statically but block (-43,1,-28) already contains 687 objects. Forcing delete.
```

**Comment by MT-Modder** [comment]
glooptest's treasure chests give me the same errors. Is that relative to this?

**Comment by VanessaE** [comment]
I wouldn't know about that, those treasure chests are disabled on the server in question.

**Comment by MT-Modder** [comment]
Okay. :-) Nvm then.

**Comment by Fixer-007** [comment]
This bug still happens on Vanessa's servers, please consider fixing multiplying ghost entities.

**Comment by SmallJoker** [comment]
One way to reproduce this bug can be found in #6249. I hope we can find an easier method for triggering this bug soon.

**Comment by davisonio** [comment]
Still experiencing this bug on 0.4.17.

**Comment by nerzhul** [comment]
is this issue already present in 5.2 series ? if i remember @sfan5 did some work on entities since 5.0

**Comment by paramat** [comment]
Any recent occurrences?
