### ISSUE TITLE
Mechanism to update current formspec after certain interval

### ISSUE THREAD

**Issue by gregorycu** [minetest/minetest#1955]
I believe there should be some facility to have the currently shown form updated after a certain intervals.

For instance, I believe mod-writers would like to have the forms update on a timer. Nodes currently do have a single timer, however, I believe the complexity in essentially multiplexing this timer would make this complicated to do. If the timer is already used for meaningful purposes, it because problematic trying manage a cosmetic form update hinge off the same timer.

A concrete example is you have a node that represents some sort of machine. The machine performs some process every minute. So you have a timer that will expire after a minute to perform the process. The machine has a form that you want to have a process bar. So, instead of a one minute timer, it gets replaced with a one second timer, so you can generate a new formspec every second to update the process bar. This introduces a counter, that counts the number of seconds. To simplify the code, a mod writer may apply this to every machine, so every second, every machine has a timer that updates the formspec.

Now, in this example, the mod writer can get clever, and have code that handles which nodes formspec is shown, and not update the formspec. It can even have code that will do different timers depending on if the form is shown or not. But I believe this is rather intrusive. In many scenarios, if a form is brought up, the mod writer probably doesn't want any change in behaviour, unless inventories are changed, or buttons are clicked, etc.

I therefore think there should be an unobtrusive means of updating the current form on some unspecified interval. For instance, I would have it so the engine gives no guarantees on how often the form will be updated, so people should not use the means to do anything meaningful, only update a formspec.

**Comment by sapier** [comment]
right now server doesn't even know if a formspec is shown or not. at least not for sure

**Comment by gregorycu** [comment]
That's a good point. I think the question is "should the server care". What I mean to say, should the server only care about any inventory changes?

**Comment by MT-Modder** [comment]
I think it should because right now the formspec is very glitchy. hmmm has plans for client side support of the hud and formspec. IDK how soon but that's his plan anyway. Formspecs should be faster too :-).

**Comment by gregorycu** [comment]
And then it follows, what do we do about formspecs that have buttons etc that are meant to make meaningful changes. For instance, what if you have some block that represents a machine that can be turned on or off. You kinda need a view-model approach...

**Comment by 4aiman** [comment]
How about minetest.after for the main menu? (I.e. prior to launching the game with ```core.start()``` and having access to ```register_onglobalstep```)

That may be used to create per-game dynamic themes for main menu.

**Comment by paramat** [comment]
Who is still requesting this? Author has left MT.

**Comment by rubenwardy** [comment]
This was requested in #minetest yesterday

**Comment by paramat** [comment]
Any dev interest, leave open?

**Comment by rubenwardy** [comment]
I don't see the need, this is easily done with minetest.after
