### ISSUE TITLE
Public serverlist causes Minetest to freeze on client tab

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#1959]
I don't get an error but it freezes and I have to force close it.

Edit: I'm using the build supplied here - https://forum.minetest.net/viewtopic.php?f=18&t=10742

Edit: This only happens without playing a singleplayer game. If you play a game then exit the game it works fine.

**Comment by kilbith** [comment]
I can't reproduce that "bug" too. Last 0.4.10-dev for Linux.

**Comment by MT-Modder** [comment]
I still have this problem with current head (https://github.com/minetest/minetest/commit/1702c34b6406025802a4fbecd893c27827b3ce96) I doubt this will ever be fixed just like my issue with preload_item_visuals being disabled. The latter issue is probably caused by my GPU though.

**Comment by kaeza** [comment]
Any news? Still happens as of d75009a75853bd188f132e93165622c5e1315f70 (current HEAD at time of writing).

**Comment by MT-Modder** [comment]
Well after upgrading to Windows 10 64bit and not being able to install my old custom driver I'm stuck with direct3d9, but I believe this issue was either because I was using a 32bit OS on a 64bit processor or it's because I was using a custom driver for my graphics card. Either way I'm not having the issue any longer. Thank you all. Oh and the issue with preload_item_visuals is gone too.

**Comment by kaeza** [comment]
Still happening as of current HEAD (87291ea at time of writing). Please reopen.

**Comment by Jordach** [comment]
@kaeza Can you send me the build you were using, I'll try it on my laptop
to if there is an actual issue, I'll be able to report back in about ~6
hours.

**Comment by HybridDog** [comment]
minetest freezes and then crashes

**Comment by HybridDog** [comment]
Please read that: http://paste.ubuntu.com/14868236/

**Comment by rubenwardy** [comment]
Happens to me on 0.4.13-stable, the console shows lots of lines of output which looks like the serverlist. Freezes for about 10+ seconds whilst loads of it is printed out.

**Comment by MT-Modder** [comment]
Okay IDK if this helps any but using opengl caused the issue for me and while using direct3d9 it works as it should.

**Comment by HybridDog** [comment]
l use linux and minetest doesn't freeze, but it crashes, see #2040.

**Comment by MT-Modder** [comment]
Seems related but I wouldn't be able to tell. I'm surprised by the lack of attention that issue has.

**Comment by HybridDog** [comment]
It obviously gets more attention than a change which makes enabling mods automatically enable also their dependencies. #3473

**Comment by JoelMon** [comment]
I get a similar problem on MintLinux (Jessie/sid). I installed Minetest via apt-get. When I check off the checkbox for Public servers Minetest crashes. Happens each time.

Minetest 0.4.9
Using Irrlicht 1.8.1
Build info: VER=0.4.9 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR=/usr/share/games/minetest

**Comment by Zeno-** [comment]
There was a race condition related to the server list (which has now been fixed). I wonder if it was/is related

**Comment by MT-Modder** [comment]
Still happens for me. (@ 0f6e4a0)

**Comment by gregorycu** [comment]
I'll take a look in a few days

**Comment by Fixer-007** [comment]
Never had this issue.

**Comment by kaeza** [comment]
Still happening as of 21ac38c.

Now thanks to 307def0, Client tab is unusable. It fetches the list every time triggering the bug.

**Comment by red-001** [comment]
Does this still happen?

**Comment by paramat** [comment]
Any recent occurence?

**Comment by paramat** [comment]
@MT-Modder

**Comment by MT-Modder** [comment]
Sry I haven't been on here in forever... One sec let me do some testing with the current dev build.

**Comment by MT-Modder** [comment]
@paramat  Well I tried all the different driver settings with this build: [HERE](https://forum.minetest.net/viewtopic.php?p=307217#p307217) and it looks like the issue is gone but mind you I'm on a whole new laptop from before so you might want to ask the other people having this issue. @kaeza @rubenwardy I think the issue is solved now that the checkbox is gone.

**Comment by paramat** [comment]
Thanks, will close for now but can reopen if anyone still experiences it.
