### ISSUE TITLE
Make max breath configurable

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#1972]
You can only hold your breath for 20 seconds and this should be customizable, especially for servers and subgames.

**Comment by MT-Modder** [comment]
Bump

**Comment by HybridDog** [comment]
>Closing in 2 weeks if no response.

you did a response

**Comment by MT-Modder** [comment]
You're too funny :laughing:

**Comment by paramat** [comment]
+1. Also i do consider 20 seconds too short.

**Comment by PilzAdam** [comment]
Not as a conf setting. It should be done in the nodedef, as #3094 tried to do.

**Comment by MT-Modder** [comment]
@PilzAdam that's nice and all but it doesn't change max breath. The only thing that does is allows you to drown faster. I want to be able to slow down drowning, maybe 40 seconds instead of 20.

**Comment by PilzAdam** [comment]
@MT-Modder I said what it "tried to do", not what it actually did ;-)

My point was only that it should be done in nodedef, not in minetest.conf.

**Comment by MT-Modder** [comment]
lol oh. Good point.

**Comment by PilzAdam** [comment]
I'd rather keep this issue open until a PR that does this actually merged.

**Comment by MT-Modder** [comment]
Okay.

**Comment by nerzhul** [comment]
it's now possible to change max HP using object properties

**Comment by Wuzzy2** [comment]
Also for players?

**Comment by SmallJoker** [comment]
@Wuzzy2 For all objects - including players. See #6287.

**Comment by paramat** [comment]
@SmallJoker do i remember correctly you are intending to work on this? Maybe it was someone else?

**Comment by SmallJoker** [comment]
@paramat Customizable breath has quite a low priority. Will make a PR to implement this soon.

**Comment by paramat** [comment]
PR #6411

**Comment by paramat** [comment]
PR merged.
