### ISSUE TITLE
Android port has no method for splitting stacks or placing blocks

### ISSUE THREAD

**Issue by MarkTraceur** [minetest/minetest#1994]
Without a mouse or keyboard or something, there's no method for placing blocks (vital component of the game) or splitting stacks (very important for management of inventories), it would be nice to add multi-touch controls for this or something.

(reported by a user on IRC)

**Comment by MoNTE48** [comment]
It is not very convenient!
You must long press - to dig the block. A quick press - to put the block.
Separation in the inventory must be made in Minecraft PE. Now is not very convenient. Especially if you want to split stack into 9 parts!

**Comment by ShadowNinja** [comment]
@MoNTE48
  1. I agree that a single tap should place.
  2. This isn't MCPE, tell that to Mojang.

**Comment by sapier** [comment]
1. I don't agree as you're gonna have nodes over nodes beeing placed accidently
2. same as ShadowNinja we're not MCPE we don't have to do everything same way.

**Comment by Phosphan** [comment]
Splitting is really tricky on a small screen - what about double tapping to split? I'd like that better.

**Comment by ShadowNinja** [comment]
False issue report.
