### ISSUE TITLE
Localization workaround active - Error

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#1996]
Happened after testing the language setting in the mainmenu.
`10:37:33: ERROR[main]: MSVC localization workaround active restating minetest in new environment!`

Also, the console window disappears. I would like to have that one back.

**Comment by paramat** [comment]
@SmallJoker @srifqi still a problem?

**Comment by srifqi** [comment]
I'm using 80cec4702dde598ded6a5b31e291d2973b26cc7b version (using `mingw32-make`) and things just fine. I've set the `language` in `minetest.conf` (from Main menu) into `id`.
