### ISSUE TITLE
Manipulating/setting the position of the sun/moon from the Lua API.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#1997]
It would be very nice if we would have the possibility to set the position of the sun/moon (anywhere on the celestial sphere) from the Lua API.

This would allow mods/games to change to the length of the day/night cycle, for example it would also allow to implement a seasonal change of the length of days or having the moon rise while the sun is setting.

The most "extreme" use-case I can think of is to implement a day/night system known from Larry Nivens Ringworld, with the sun being fixed at the top of the sky and the moon sliding in front of it for the night.

**Comment by twoelk** [comment]
Things I wish were  configurable (my wishlist ;-P , from the [Textureable sun and moon] (https://forum.minetest.net/viewtopic.php?p=152129#p152129) Thread)

  *  Size of object in the sky
  *  Keeping the descriptive original file name
  *  setting of a rising time
  *  More than one object (satellites and natural satellites)
  *  setting offset from default path for each satelite (parallel paths)
  *  making the orbit time of each satellite independant from the star background (making eclipses possible)
  *  making individual orbit paths independant from the default star background direction (east to west)
and
  *  day and night ratio

as far as I know there is no way to change the day / night ratio as of yet as time_speed just sets the complete cycle but keeps the one to one ratio. What RobertZenz requests though is not only changing the cycle length but also the ratio of day and night to each other. So maybe something like the following could generate a night twice as long as the day:  
  daynightratio = 1, 2

**Comment by RobertZenz** [comment]
Am I seeing this correct that a mod/subgame can't set time_speed in their configuration (game.conf)?

**Comment by C1ffisme** [comment]
@twoelk YES!!!

**Comment by 0-afflatus** [comment]
@twoelk :+1:
Also make sun / moon textures configurable per game / server, not just on the client.

**Comment by rubenwardy** [comment]
> I feel this is realism going too far, i was not impressed seeing a seasonal sun in a Minecraft video, it's a good example of how Minecraft in it's decline is adding stupid features. The cosmology of Minetest is highly unrealistic and one of no axial tilt, there is no good reason to change this even as an option.

Don't force minetest_game ideology on all subgames - some subgames will want this.

**Comment by paramat** [comment]
My comment was too harsh. I'm not particularly opposed now, it's just perhaps not needed enough. Moving the path of the sun N or S will only enable shorter days, for days longer than nights we would need to also tilt the rotation of the skybox.

**Comment by RobertZenz** [comment]
You could simply add a callback that either returns a path or the position of the sun directly. By default the engine would provide the current path, a mod could add a callback that returns the position on the sky (like latitude/longitude or whatever you use for skies) which would be called on every "timechange". That would allow easy and versatile control.

Of course, lighting is a completely different matter.

**Comment by 0-afflatus** [comment]
As a game designer, I'd like to be able to:
1. Include custom textures for sun, moon and additional satellites.
2. Add more satellites.
3. Specify different rotation times for each satellite.
4. Tilt the ecliptic (skybox) so the sun appears in the south at midday.
4b. Have the option to make the skybox ecliptic rotate west to east.
5. Have some method of representing phases of satellites when they are not opposite the sun, with appropriate lighting changes.
This list is prioritised.
And yes, we are asking for the moon here.

**Comment by 0-afflatus** [comment]
Being able to poll the objects for their current position would be pretty useful too. The most useful value would probably be degrees relative to the ecliptic - 0 = invisible / new, 180 = full.

**Comment by paramat** [comment]
Old issue but is certainly wanted in some form.
I'm not sure about the level of customisation requested by some, especially axial tilt, but the ability to add or remove celestial objects and control their positions is very useful.

**Comment by paramat** [comment]
Related #6732 #6128

**Comment by v-rob** [comment]
Implemented in #8964.

**Comment by twoelk** [comment]
I wonder if there still is interest for adding more satellites, such as several moons or having phases on celestial objects or any of the other things mentioned besides the issues listed in the tittle.

**Comment by 0-afflatus** [comment]
I'd 

> I wonder if there still is interest for adding more satellites, such as several moons or having phases on celestial objects or any of the other things mentioned besides the issues listed in the tittle.

Absolutely. #8964 doesn't actually implement any of the features I was looking for. Being able to customise sky boxes and change the size of sun, moon and stars is nice, but it doesn't allow multiple moons. Pretty much every fantasy world has multiple moons. Probably best to open a new issue.

**Comment by 0-afflatus** [comment]
Paramat's arguments for not allowing seasonal changes and variable day / night ratio are based on the idea that the world is a cube. Considering that the playing area is 32km³, it's a < 0.1° section of most planet's surfaces and it forces gameplay onto a generic flat earth minetest world. That's fine if all you want to do is run a mineclone, but it limits the possibilities for new games.
