### ISSUE TITLE
clouds appear in front of water

### ISSUE THREAD

**Issue by sudoman** [minetest/minetest#200]
when viewing these columns of water, the clouds appear to be drawn in front of the water.

that could be because these columns of water come from very high in the sky, above the level of the clouds.

![ka468](https://cloud.githubusercontent.com/assets/3686677/15031649/366f2eee-1252-11e6-9cbe-e4f9b9dfe88b.png)

**Comment by RobertZenz** [comment]
Works for me with the latest build:

![screenshot_20160117_140337](https://cloud.githubusercontent.com/assets/611377/12377613/c1f6b1e6-bd23-11e5-8e10-ab705903ca5f.png)
![screenshot_20160117_140702](https://cloud.githubusercontent.com/assets/611377/12377614/c1f79dcc-bd23-11e5-8a7e-b65777f4cf7f.png)
![screenshot_20160117_140736](https://cloud.githubusercontent.com/assets/611377/12377616/c1fab430-bd23-11e5-8012-ce7ea033f8ec.png)
![screenshot_20160117_140750](https://cloud.githubusercontent.com/assets/611377/12377615/c1f813d8-bd23-11e5-8b77-1ae4c9003ee8.png)


Though, you cant seem to see water when looking through the clouds, but I believe that that is a different issue.

**Comment by paramat** [comment]
The order of drawing can change, explaining why sometimes it works correctly. Closing.

**Comment by PilzAdam** [comment]
@paramat why did you close this? Is this bug fixed?

**Comment by paramat** [comment]
Sorry, i shouldn't have closed this.

**Comment by Wayward1** [comment]
This doesn't appear to be an issue any more:

Windows:
![screenshot_20160504_154611](https://cloud.githubusercontent.com/assets/8821916/15027719/216e9da2-1213-11e6-8285-cf69f1518813.png)

Linux:
![screenshot from 2016-05-04 08_55_26](https://cloud.githubusercontent.com/assets/8821916/15027747/3efa5b22-1213-11e6-9865-a5d7c7640cd3.png)

Android:
![screenshot_2016-05-04-08-38-22](https://cloud.githubusercontent.com/assets/8821916/15028049/d5b4d910-1214-11e6-8f78-74122ca0dc92.png)

**Comment by Wayward1** [comment]
This doesn't appear to be an issue any more:

Windows:
![screenshot_20160504_154611](https://cloud.githubusercontent.com/assets/8821916/15027719/216e9da2-1213-11e6-8285-cf69f1518813.png)

Linux:
![screenshot from 2016-05-04 08_55_26](https://cloud.githubusercontent.com/assets/8821916/15027747/3efa5b22-1213-11e6-9865-a5d7c7640cd3.png)

Android:
![screenshot_2016-05-04-08-38-22](https://cloud.githubusercontent.com/assets/8821916/15028049/d5b4d910-1214-11e6-8f78-74122ca0dc92.png)

**Comment by paramat** [comment]
This might still occur in certain circumstances, the translucency sorting issue is a bit unpredictable.
However i will now make #95 the original issue to refer back to for translucency sorting, as it has information from c55 and is more on-topic.

**Comment by paramat** [comment]
See #95 as is related to the translucency sorting issue.
