### ISSUE TITLE
Update OpenSSL

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2002]
Your application uses a version of the library OpenSSL, which has a vulnerability. Update the OpenSSL as soon as possible.
Vulnerabilities have been fixed in OpenSSL versions starting with 1.0.1h, 1.0.0m and 0.9.8za. To check your version of the library, use the command grep ("$ unzip -p nazvanie_prilozheniya.apk | strings | grep" OpenSSL ""). For more information about the vulnerabilities listed in the file http://www.openssl.org/news/secadv_20140605.txt.

**Comment by sapier** [comment]
no it's not as we're using https for server list as well as modstore we need to update

**Comment by MoNTE48** [comment]
Last commit fix this.
Close Issue.

**Comment by sfan5** [comment]
>we're using https for server list

wat.
There isn't even something listening on port 443 of servers.minetest.net.

**Comment by ShadowNinja** [comment]
@sfan5 I think he means the mod DB.
