### ISSUE TITLE
Attached player gets teleported to 0,0,0 when attempting to teleport furtherer than 200

### ISSUE THREAD

**Issue by obneq** [minetest/minetest#2004]
https://forum.minetest.net/viewtopic.php?f=11&t=6183&start=75#p165513

this post describes a problem where an attached player gets teleported back to pos 0, 0, 0 when any coordinate exceeds 200 in any direction.

**Comment by paramat** [comment]
@obneq still occuring? surely boats and cars would experience this if it was?

**Comment by obneq** [comment]
@paramat it has to do with how the mod is coded, specifically helicopter mod. The real issue is that the attachment system sucks so this mod has to do some stuff to code around that. It relies on the attached player and the thing its attached to have similar positions, which is not the case on camera offset limits.

**Comment by paramat** [comment]
Mod issue, no other vehicle has this bug.
