### ISSUE TITLE
minetest.dig_node(test_position) does not fail when expected -- always returning true

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2015]
```
minetest.dig_node(pos)
^ Dig node with the same effects that a player would cause
  Returns true if successful, false on failure (e.g. protected location)
```

contrary to documentation `minetest.dig_node(pos)` will always return `true`, even when digging a node that has `can_dig` return `false` or is protected by `minetest.is_protected(pos, name)`

[shakedown](https://github.com/t4im/shakedown)-unittest: [environment](https://github.com/t4im/coretest/blob/master/environment.lua)

**Comment by HybridDog** [comment]
lf you add
print(minetest.get_node(test_position).name)
do you get "api_test:undiggable" or "ignore"?

**Comment by t4im** [comment]
It recognizes it correctly as api_test:undiggable
Updated test: https://gist.github.com/t4im/f0d34baeb54855fcd63a

**Comment by t4im** [comment]
I just rerun the unit-test, and are reconfirming the bug to be still present.

----
#### minetest.dig_node(pos)
###### … it returns false on failure (e.g. protected location) (minetest/minetest#2015)
 1. **Given** an undiggable node
 2. **When** digging it
 3. ~~**Then** return false~~  
    Fail with:
    > /home/t4im/.minetest/mods/coretest/environment.lua:20: Expected objects to be the same.
    > Passed in:
    > (boolean) true
    > Expected:
    > (boolean) false
