### ISSUE TITLE
facedir > 23 causes segfault in client

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#2017]
https://github.com/minetest/minetest/blob/3ea5ed4ffe600fa11a3deb3de58d5bd5bbb65ee1/src/content_mapblock.cpp#L1732 lacks a check for facedir > 23 (see https://github.com/minetest/minetest/blob/3ea5ed4ffe600fa11a3deb3de58d5bd5bbb65ee1/src/mapblock_mesh.cpp#L695-697).

acerspyro found this: https://gist.github.com/kahrl/d0a106bd79ddd0b8f2e2
This should fix it, and the check in mapblock_mesh.cpp can be removed.

**Comment by RealBadAngel** [comment]
kahrl's fix should be enough to solve the issue.

**Comment by Zeno-** [comment]
commit d576235409c1c21c25167ccd611fc847e9d23cb8

**Comment by PilzAdam** [comment]
@Zeno- you forgot to remove the check at https://github.com/minetest/minetest/blob/3ea5ed4ffe600fa11a3deb3de58d5bd5bbb65ee1/src/mapblock_mesh.cpp#L695-697

**Comment by Zeno-** [comment]
@PilzAdam commit 3c8e3721199ff5b9f7f454e5a6ecf76a87d3a3f9

**Comment by HybridDog** [comment]
As far as l know you can also crash anyone's client if you write/paste special letters onto a sign and make that he/she looks at this sign.
