### ISSUE TITLE
Separate "rollback" and "log" privileges

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#202]
Basically: "rollback" privilege allows rollbacking stuff, "log" (or "rollbacklog" maybe) only allows seeing the logs. Very useful against griefing, so that players can know who griefed them, but cannot rollback to prevent infinite resources.

**Comment by paramat** [comment]
@Calinou still want this open?

**Comment by paramat** [comment]
http://irc.minetest.ru/minetest-dev/2016-03-27#i_4566776 closing.
