### ISSUE TITLE
window is borderless

### ISSUE THREAD

**Issue by fz72** [minetest/minetest#2022]
Hi, sometimes when I start minetest the window has no border.

![window_borderless](https://cloud.githubusercontent.com/assets/7348083/5565265/d2fe7fd2-8eee-11e4-9edb-5160f1443392.png)

**Comment by HybridDog** [comment]
l use lubuntu 14.04 and don't get a borderless window bug.
But when l wanted to use the awesome window manager minetest didn't work right on lubuntu.

**Comment by indriApollo** [comment]
I have the same issue with ubuntu 14.10 running unity/compiz. This doesn't happen with cinnamon on my linux mint 17 laptop. However Cairo dock doesn't hide when in front of the minetest window (http://i.imgur.com/0RMmY6H.png)

**Comment by alex1702** [comment]
hey i can move the window with alt + drag on ubuntu 15.04 with unity and minetest 0.4.13.

**Comment by HybridDog** [comment]
Unity puts the window border into the top panel

**Comment by rubenwardy** [comment]
Check that it's not fullscreen. (Look in minetest.conf)

**Comment by 0-afflatus** [comment]
This looks like an issue with Unity / Irrlicht.
I don't see any suggestion of a fix within minetest.
I have never seen this on XFCE

**Comment by H-H-H** [comment]
I just pulled latest git of both Minetest and the game and built it and have exactly the same issue running on manjaro 64bit with xfce and compiz

**Comment by paramat** [comment]
@fz72 still a problem? Might be solved in Irrlicht.

**Comment by Fixer-007** [comment]
Hmm, think I have something like that in Windows rarely, somehow I click in background or alt-tab differently and minetest remains in foreground, but without window border. Happens very rarely and I'm not sure how to reproduce.

**Comment by H-H-H** [comment]
I just pulled latest git of both Minetest and the game and built it and still have this issue running on manjaro 64bit with xfce and compiz

However Clicking on maximise in the taskbar tab for Minetest maximises it and the border pops back
I have also noticed that any kind of window manipulation (ie resizing) will make the window border pop back

**Comment by rubenwardy** [comment]
looks like a WM issue
