### ISSUE TITLE
Schematic Crash

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#2023]
When placing a schematic file using minetest.place_schematic or as a biome decoration, Minetest crashes with a "Segmentation fault" error...  0.4.11 stable is fine, the newer builds have this problem though...

**Comment by nerzhul** [comment]
@tenplus1 can you give us a backtrace. I close the issue in 1 week if there isn't any answer

**Comment by paramat** [comment]
I've had problems trying to place a schematic that was created and saved using Worldedit, but need to test this again.

**Comment by paramat** [comment]
Perhaps the same issue as https://github.com/minetest/minetest/issues/2481
