### ISSUE TITLE
"Local map saving" overwrites the saved world of the last connected remote server when starting a local server

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2024]
When starting a local server (non-dedicated) with `enable_local_map_saving = true`, it will start saving to the locally saved world of the last connected multiplayerserver.

**Comment by Zeno-** [comment]
Can more information on how to reproduce this be provided, please?

**Comment by t4im** [comment]
With a recent version e.g. 4d15d63
1. enable local map saving `enable_local_map_saving = true`
2. start minetest, connect to a multiplayer server <host>. Expected output:
`ACTION[main]: Local map saving started, map will be saved at <path>/server_<host>_<port>'`
3. Disconnect and directly start a local server in the server tab of a random world, except the one we just created as copy of <host>. E.g a new one "Test"

The server will now save to the local save of the previously connected multiplayer world
`ACTION[main]: Local map saving started, map will be saved at <path>/server_<host>_<port>'`

**Comment by Zeno-** [comment]
Well, the problem is obviously (at least partially) here: https://github.com/minetest/minetest/blob/master/src/client.cpp#L288

@sfan5 why is the local directory name based on something in g_settings?

**Comment by Zeno-** [comment]
commit 38561023b468b923aa2b7957b807fa2700ea59ce
