### ISSUE TITLE
The health bar overlaps the inventory slots

### ISSUE THREAD

**Issue by CraigyDavi** [minetest/minetest#2029]
A recent change seems to have made the health bar overlap the inventory slots:
![Image](https://cdn.mediacru.sh/-/-CbI4o3OC2_Z.png)

**Comment by crazyR14** [comment]
this is only on certain builds. on most o the windows builds it was fine. but when building from source on unix i had this issue. i think its related to the various hud issues

**Comment by ShadowNinja** [comment]
Should be fixed by 15c037614f6f7193cef4bfd1da45d83ef2fef393.

**Comment by BlockMen** [comment]
Is fixed by https://github.com/minetest/minetest/commit/15c037614f6f7193cef4bfd1da45d83ef2fef393
