### ISSUE TITLE
Able to see through walls in glitchy behavior

### ISSUE THREAD

**Issue by joshlemer** [minetest/minetest#2032]
Here's a video of the issue
https://www.dropbox.com/s/i7zfklip3g85gwq/out.ogv?dl=0

Here is my .minetest folder:
https://www.dropbox.com/s/41db6c04m3tzatf/.minetest.zip?dl=0

The F5 debug info at the spot:

```
Minetest 0.4.10 FPS = 60 (R: range_all=0) drawtime = 16, dtime_jitter = 12.9 %, v_range=240.0, RTT = 0.001
(-95.8, -50.5, 16.2) (yaw = 69.2) (seed = 2115579629429870690)
```

Running on Arch Linux. If there's any other information I missed, just let me know!

**Comment by paramat** [comment]
@joshlemer still occuring?

**Comment by paramat** [comment]
No response and not enough detail.
