### ISSUE TITLE
Can walk through blocks if placed where player is standing

### ISSUE THREAD

**Issue by joshlemer** [minetest/minetest#2034]
The player is able to place a block in the same space they are standing in, and then they end up being able to walk through the block until they leave that area.

Video of the phenomenon:
https://www.dropbox.com/s/tcov9cc3rq7ppsh/out-2.ogv?dl=0

.minetest folder:
~~https://www.dropbox.com/s/41db6c04m3tzatf/.minetest.zip?dl=0~~
https://www.dropbox.com/s/ktscta7m1m435dc/.minetest.zip?dl=0

**Comment by paramat** [comment]
@joshlemer 
> you shouldn't be able to place the node unless you've set enable_build_where_you_stand
