### ISSUE TITLE
Slabs are drawn through wall (graphic bug)

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#2035]
Slabs are drawn through the walls of the windmill (in the background). This also happens at other towers, with and without shaders:
![screenshot_184404911](https://cloud.githubusercontent.com/assets/6941454/5589365/2f6aea14-911d-11e4-8350-573cd3e5bc38.png)
More Screenshots:
https://mediacru.sh/d71a3dd6ffbd

**Comment by HybridDog** [comment]
your wielded items look a bit strange

**Comment by MT-Modder** [comment]
@HybridDog This is the problem: https://forum.minetest.net/viewtopic.php?f=6&t=10862
Recently RealBadAngel changed some of the shader code and this is the result for some people without shaders. :smile: For the longest time I thought it was a horrible "feature", but turns out it's a bug.

**Comment by RHRhino** [comment]
Maybe related with https://github.com/minetest/minetest/issues/2179 and https://mediacru.sh/8soQTJmg57qR and https://forum.minetest.net/viewtopic.php?f=6&t=10862??

**Comment by HybridDog** [comment]
l also noticed that dropped items with wield image or inventory image have lots of polygons which aren't necessary.
l can see them if l fly into the dropped items:

![screenshot_3997221490](https://cloud.githubusercontent.com/assets/3192173/5891111/3dff246e-a482-11e4-84aa-65647aa21776.png)

![screenshot_3997202998](https://cloud.githubusercontent.com/assets/3192173/5891112/41f64ac0-a482-11e4-837c-8a5440314840.png)

**Comment by Zeno-** [comment]
@RHRhino RBA didn't write that code

**Comment by RHRhino** [comment]
This bug does not only occur with slabs. The wall in the background is made out of full blocks. This stripes change with the viewing direction. It looks very weird.
![screenshot_7444346](https://cloud.githubusercontent.com/assets/6941454/6275372/dc798dae-b87e-11e4-8b46-770b9218966c.png)
![screenshot_7448033](https://cloud.githubusercontent.com/assets/6941454/6275373/dc7a1e7c-b87e-11e4-95be-7776c275b92e.png)
![screenshot_7453828](https://cloud.githubusercontent.com/assets/6941454/6275374/dc7d994e-b87e-11e4-8510-ad05e7115cba.png)
![screenshot_7460461](https://cloud.githubusercontent.com/assets/6941454/6275376/dc802f7e-b87e-11e4-8dcb-5b452337f042.png)
![screenshot_7465581](https://cloud.githubusercontent.com/assets/6941454/6275375/dc7e8782-b87e-11e4-8ff0-602a9b64d856.png)

**Comment by BlockMen** [comment]
I can confirm those stripes with nodesboxes.

**Comment by RHRhino** [comment]
Snow has this stripes too 
![screenshot_20150513_210119](https://cloud.githubusercontent.com/assets/6941454/7618595/6cbeffbe-f9b3-11e4-81b2-068e1479539d.png)

**Comment by RHRhino** [comment]
Can be closed because fixed with https://github.com/minetest/minetest/pull/3586
