### ISSUE TITLE
World mod configuring is broken

### ISSUE THREAD

**Issue by ChaosWormz** [minetest/minetest#2037]
```
-------------
  Separator  
-------------

Irrlicht log: Irrlicht Engine version 1.8.1
Irrlicht log: Linux 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64
Irrlicht log: Using renderer: OpenGL 2.1
Irrlicht log: Gallium 0.4 on ATI R520: X.Org R300 Project
Irrlicht log: OpenGL driver version is 1.2 or better.
Irrlicht log: GLSL version: 1.2
13:01:10: ERROR[main]: Invalid character ' ' found in setting name
13:01:10: ERROR[main]: MAINMENU ERROR: Invalid sequence found in setting parameters
13:01:10: ERROR[main]: stack traceback:
13:01:10: ERROR[main]: 	[C]: in function 'set'
13:01:10: ERROR[main]: 	...ts/minetest/bin/../builtin/mainmenu/dlg_config_world.lua:201: in function 'handle_buttons'
13:01:10: ERROR[main]: 	...chaoswormz/Documents/minetest/bin/../builtin/fstk/ui.lua:118: in function 'handle_buttons'
13:01:10: ERROR[main]: 	...chaoswormz/Documents/minetest/bin/../builtin/fstk/ui.lua:155: in function <...chaoswormz/Documents/minetest/bin/../builtin/fstk/ui.lua:148>
```

**Comment by kwolekr** [comment]
Haha, great stuff, my recent work on Settings caught something bad.
We're trying to decide if mod names should disallow spaces or escape them, leaning toward disallow.  If this becomes the official policy, then it would be your mod that's broken rather than Minetest.

**Comment by ShadowNinja** [comment]
Spaces aren't currently allowed.  Only lowercase letters, numbers, and underscores are allowed (source: https://github.com/minetest/minetest/blob/master/src/mods.h#L33).

It seems like the main menu is failing to validate mod names.

**Comment by est31** [comment]
So, as I see, the actual problem is that simply having a directory with a space in the name inside your `mods` directory can make the dialog fail every time. PR 2345 fixes this behaviour, by only giving an error if the player actually selected the mod.
