### ISSUE TITLE
Memory corruption in httpfetch? (server list)

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#2040]
```
Irrlicht log: GLSL version: 4.4
*** Error in `18:27:12: ERROR[AsyncWorkerThread_1]: servers.minetest.net/list not found (Timeout was reached) (resposervers.minetest.net/list not found (Timeout was reached) (response code 0)
~/minetest': double free or corruption (!prev): 0x0a7d3228 ***
Abgebrochen
```
l don't know how to reproduce it, it sometimes appears when l'm in the menu at the server tab.

And the public serverlist often, almost every time, disappears and reappears after about a second. l thought it was fixed recently but l didn't saw a difference.

**Comment by HybridDog** [comment]
What does this error mean?

>17:05:05: ERROR[AsyncWorkerThread_0]: URL: servers.minetest.net/list
17:05:05: ERROR[AsyncWorkerThread_0]: Failed to parse json data * Line 1, Column 49197
17:05:05: ERROR[AsyncWorkerThread_0]:   Missing ',' or ']' in array declaration
17:05:05: ERROR[AsyncWorkerThread_0]: data: "{"total": {"clients": 286, "servers": 50}, "total_max": {"clients": 464, "servers": 76}, "list": [{"dedicated": true, "url": "http://minetest.net", "privs": "interact, shout", "uptime": 429

… some spam …

>ted": true, "url": "", "privs": "interact, shout", "uptime": 4500, "updates": 16, "creative": false, "mods": ["money2", "craft_guide", "cars", "sethome", "screwdriver", "fire", "dye", "default", "vendor", "signs_lib""
17:05:11: ERROR[AsyncWorkerThread_2]: servers.minetest.net/list not found (Timeout was reached) (response code 0)

**Comment by HybridDog** [comment]
2015-04-21 19:28:58: ERROR[AsyncWorkerThread_0]: servers.minetest.net/o_t?proto_versioversio_versiroto_version_max=24 not found (Timeout was reached) (response code 0)

**Comment by HybridDog** [comment]
l used gdb:
>(gdb) run
Starting program: /bin/minetest 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/i386-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
2015-09-16 17:39:39: ERROR[Main]: Subgame specified in default_game [minetest] is invalid.
[New Thread 0xb3b05b40 (LWP 3154)]
[Thread 0xb3b05b40 (LWP 3154) exited]
[New Thread 0xb3b05b40 (LWP 3155)]
[New Thread 0xaf1ffb40 (LWP 3156)]
[New Thread 0xae9beb40 (LWP 3157)]
[New Thread 0xaddffb40 (LWP 3158)]
[New Thread 0xad5feb40 (LWP 3159)]
[New Thread 0xacdfdb40 (LWP 3160)]
[New Thread 0xac5fcb40 (LWP 3161)]
[New Thread 0xabdfbb40 (LWP 3162)]
[Thread 0xabdfbb40 (LWP 3162) exited]
[Thread 0xac5fcb40 (LWP 3161) exited]
*** Error in `2015-09-16 17:39:45: ERROR[AsyncWorker-1]: seerves.minetest..t/list?net/_version_min=13&plist?proto_version_min=13&proto_version_max=26 not found (Timeout was reached) (response code 0)
Program received signal SIGABRT, Aborted.
[Switching to Thread 0xae9beb40 (LWP 3157)]
0xb7fdd428 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7fdd428 in __kernel_vsyscall ()
#1  0xb769f607 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xb76a2a33 in __GI_abort () at abort.c:89
#3  0xb76d9e53 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0xb77d6edc "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:175
#4  0xb76e433a in malloc_printerr (action=<optimized out>, 
    str=0xb77d6fd0 "double free or corruption (!prev)", ptr=0x8a21780)
    at malloc.c:4996
#5  0xb76e4fad in _int_free (av=0xb781b420 <main_arena>, p=<optimized out>, 
    have_lock=0) at malloc.c:3840
#6  0xb78ca82f in operator delete(void*) ()
   from /usr/lib/i386-linux-gnu/libstdc++.so.6
#7  0xb792f18b in std::string::_Rep::_M_destroy(std::allocator<char> const&) ()
   from /usr/lib/i386-linux-gnu/libstdc++.so.6
#8  0xb78c876a in ?? () from /usr/lib/i386-linux-gnu/libstdc++.so.6
#9  0xb79301d0 in std::string::reserve(unsigned int) ()
   from /usr/lib/i386-linux-gnu/libstdc++.so.6
#10 0x0841fc09 in Logbuf::xsputn(char const*, int) ()
#11 0xb79060d3 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, int) () from /usr/lib/i386-linux-gnu/libstdc++.so.6
---Type <return> to continue, or q <return> to quit---
#12 0x083ed787 in HTTPFetchOngoing::complete(CURLcode) ()
#13 0x083ed9c0 in httpfetch_sync(HTTPFetchRequest const&, HTTPFetchResult&) ()
#14 0x083301ee in fetchJsonValue(std::string const&, std::vector<std::string, std::allocator<std::string> >*) ()
#15 0x084f9b9c in ServerList::getOnline() ()
#16 0x0823a74c in ModApiMainMenu::l_get_favorites(lua_State*) ()
#17 0x0821132f in script_exception_wrapper(lua_State*, int (*)(lua_State*)) ()
#18 0xb7b30643 in ?? () from /usr/lib/i386-linux-gnu/libluajit-5.1.so.2
#19 0xb7b73cf4 in lua_pcall () from /usr/lib/i386-linux-gnu/libluajit-5.1.so.2
#20 0x082141e5 in AsyncWorkerThread::run() ()
#21 0x08265e09 in Thread::theThread(void*) ()
#22 0xb7a85f70 in start_thread (arg=0xae9beb40) at pthread_create.c:312
#23 0xb775cbee in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:129

**Comment by paramat** [comment]
Why re-opened?

**Comment by HybridDog** [comment]
l noticed l still get the error.
