### ISSUE TITLE
Minetestserver segfaults on player join.

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#2042]
With BFD, the server has every time, segfaulted when I join it via LAN.

Valgrind:

http://paste.debian.net/plain/139072

Non-Valgrind:

http://paste.debian.net/139071

**Comment by ShadowNinja** [comment]
Appears that `Schematic::blitToVManip` (called from `ModApiMapgen::l_place_schematic`) is reading from a `NULL` pointer.

**Comment by Jordach** [comment]
Another thing to note that several hundred entities consisting of 12 faces were used around the world.

**Comment by kwolekr** [comment]
Could you try giving a 'bt full' from gdb instead of Valgrind output?

**Comment by Jordach** [comment]
Bam. http://paste.debian.net/139134/

**Comment by kwolekr** [comment]
Great, that's a lot more clear.
Could you post the schematic that's crashing, now?

**Comment by Jordach** [comment]
All of the schematics used can be found in here:

https://github.com/Jordach/big_freaking_dig/tree/master/mods/mapgen/schematics

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/cd4d213ae07724b698d8a37f4dfe83f82f0fc6e8
