### ISSUE TITLE
TARGET_ARCH bug

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2048]
On last commit bug!
TARGET_ARCH = armv7 "on toolchain config for arm old processors"
TARGET_ARCH = arm "on toolchain config for arm old processors"

**Comment by MoNTE48** [comment]
ShadowNinja, this is small bug on Makefile.
Please, check this!

**Comment by ShadowNinja** [comment]
I defer to sapier on this.  I don't know which one is correct.

**Comment by sapier** [comment]
fixed 04d4a00393a6eaa6b2c7681b2cd799dc2d2de3fb
