### ISSUE TITLE
Min light on night

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2050]
Hi. Pls, add settings on minetest.conf, regulated min light on night.
Now i can't see night nothing!

**Comment by MT-Modder** [comment]
:+1: I like this idea.

**Comment by Jordach** [comment]
Turn up the "Gamma" setting on your monitor, or via the .conf, which has
just been added recently by Zeno.

(You can always try this with the AMD Radeon Control Panel or with the
nVidia Control Panel.)

**Comment by MT-Modder** [comment]
@Jordach Good point didn't think about that. But what if day is too bright after changing gamma? You will have to keep changing this setting every time the day/night cycle changes. I think this should be a separate setting.

**Comment by Jordach** [comment]
Consider changing the value to one that suits you at *both* times of day,
as this will allow you to configure it for yourself.

**Comment by MT-Modder** [comment]
Okay.

**Comment by Calinou** [comment]
Have you tried this minetest.conf setting?

`display_gamma = 1.1`

**Comment by MT-Modder** [comment]
I didn't know that. Thank you Calinou.

**Comment by MoNTE48** [comment]
Calinou, don'tnwork on my Win-tablet :(

**Comment by Calinou** [comment]
> Calinou, don'tnwork on my Win-tablet :(

You need to use a recent Git client, 0.4.11 does not have this feature.

**Comment by Zeno-** [comment]
MoNTE48, since you have your own minetest-based app in the Android Play Store, why don't YOU fix it to behave like you want it to do and give us the updated code?

**Comment by MoNTE48** [comment]
I'm sorry, i don't write on C++.
I hire people and I write code for money.
