### ISSUE TITLE
German Ingame-Translation is broken in 0.4.11

### ISSUE THREAD

**Issue by davidak** [minetest/minetest#2053]
![bildschirmfoto 2015-01-05 um 13 30 25](https://cloud.githubusercontent.com/assets/91113/5613095/4a73d350-94df-11e4-9694-ea0d609e46c2.png)
![bildschirmfoto 2015-01-05 um 13 31 26](https://cloud.githubusercontent.com/assets/91113/5613096/51a58d94-94df-11e4-9f31-2231577c2aaa.png)

in the launcher is german text.

![bildschirmfoto 2015-01-05 um 13 25 59](https://cloud.githubusercontent.com/assets/91113/5613068/d8819fe8-94de-11e4-8294-8409bb351c10.png)

**Comment by PilzAdam** [comment]
This seems due to a broken/outdated `util/updatepo.sh`, it's missing the `wstrgettext` function.
Adding `-kwstrgettext` in line 52 should fix it.

**Comment by ShadowNinja** [comment]
efeb372e95e3bd056c0821c203fabc4e5d685c1f
