### ISSUE TITLE
Shaders don't work on Android (remove from menu or fix)

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#2060]
Shaders should be removed from the menu or fixed on Android (ogles2 supports them).

**Comment by sfan5** [comment]
Didn't Android use `ogles1`?

**Comment by sapier** [comment]
right now we use ogles1 but ogles2 is selectable and working on some devices too

**Comment by paramat** [comment]
Still the case?

**Comment by stujones11** [comment]
I have been investigating this issue and have found that no shaders are ever loaded for android since the driver types `EDT_OGLES1` & `EDT_OGLES2` are not recognised by the loader function. The effect you see when enabling shaders is only that Irrlicht's inbuilt shaders are no longer used.
https://github.com/minetest/minetest/blob/de2c40c8fc189eeeeba010a0aaa1d28aed588c68/src/shader.cpp#L836-L848
However, if I add the ogles types to the GLSL section things get a little further but now the shaders are failing to compile [logcat.txt](https://gist.github.com/stujones11/6b5a75a36bcd38efba0035de9908410f)
Unfortunately this beyond my capabilities to debug, I just thought I should share my findings.

@numberZero Does this mean anything to you?

**Comment by numberZero** [comment]
> Does this mean anything to you?

@stujones11 Yes it does.
1. `src/shader.cpp:597:	std::string shaders_header = "#version 120\n";`
but GLES2 uses different GLSL version numbering, it seems to have no version 120 at all, only 100.
2. GLES2 doesn’t support predefined vertex attributes (like position, color, etc.), only user-defined ones. IrrLicht supplies some, but uses different names (see `EVertexAttributes.h` for list).

**Comment by stujones11** [comment]
Thanks for the prompt reply, this doesn't look like something I'd be able to fix but at a guess that would probably involve supplying a separate set of shaders to work with GLES2

**Comment by stujones11** [comment]
I might add that currently it is possible to abuse this bug to gain 'fullbright' and although you have to put up with other visual glitches, it does provide a considerable advantage when mining,

IMO this should be marked as a blocker.

**Comment by paramat** [comment]
> Unless this can be fixed I would suggest disabling the shaders menu completely for the 0.5.0 release.

Agreed.

**Comment by paramat** [comment]
Further discussion https://github.com/minetest/minetest/issues/5600#issuecomment-390780993

**Comment by paramat** [comment]
Just to check, #5600 seems to be resolved, do we still need to disable shaders on Android? 5.0.0 is nto far off and i doubt shaders wil be fixed by then, so disable?

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/5600#issuecomment-390786094

For 5.0.0 these should be removed from menu and settings for Android.

**Comment by numberZero** [comment]
Hmm, I forgot [my own comment](https://github.com/minetest/minetest/issues/2060#issuecomment-361088989)... These errors should be fixable. And as I found a GLES emulation library, I may be able to debug that...

**Comment by codexp** [comment]
On S9+ with Android 8 shaders are still not available.

**Comment by paramat** [comment]
I'm just unsure this can be done in time for 5.0.0.

**Comment by numberZero** [comment]
> shaders are still not available.

@codexp Shaders aren’t even loaded for GLES in the current `master`. I’m working on that now, see #7514.

**Comment by paramat** [comment]
It seems this should stay open until #7514 is resolved.

**Comment by rubenwardy** [comment]
The PR that closed this disables the GUI on Android, which is what this issue calls for

**Comment by paramat** [comment]
Ok, thought it might be useful as a reminder to try and fix shaders on Android, but not essential :)

**Comment by z0rti** [comment]
Shaders don't work on Android 10 (Samsung Tablet) with 5.4.0, is there a chance for 5.5.0 with the IrrlichtMt?

**Comment by sfan5** [comment]
Open a new issue for that.
