### ISSUE TITLE
Text pop-up should open automatically when opening up the chat form

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#2062]

**Comment by sapier** [comment]
I'm not sure if this would be a good idea. Chat window is just a regular formspec, so what textedit should be autoselected if there's more then one?

**Comment by MoNTE48** [comment]
Yes! Please, add this.

**Comment by stujones11** [comment]
I do not understand what this issue is about or why it was ever classified as a bug. AFAIK the text input box and soft-keyboard do automatically show when you press the chat icon. There is absolutely no sense in showing the formspec as well.

**Comment by stujones11** [comment]
@MoNTE48 you wanted this, please explain what you are expecting to happen, if this _is_ still an issue.

**Comment by MoNTE48** [comment]
@stujones11 Just install MultiCraft, and see how Minetest should look on Android, if someone listened to my opinion.
https://play.google.com/store/apps/details?id=mobi.MultiCraft
50 million downloads

**Comment by stujones11** [comment]
Yes, we know that but please explain what exactly is wrong here or just make PR to fix it :)

I will take a look at your fork and see what might be worth back-porting, though I have to admit I am not very clued up on the java side of things, to say I dislike it would be an understatement :p

**Comment by MoNTE48** [comment]
> and see what might be worth back-porting
MultiCraft use LGPLv3+. Only i can create PR for Minetest :)
But yes, please, look my fork. Maybe you find something interesting

**Comment by stujones11** [comment]
Well in that case I wont bother, I'd hate to be wrongly accused of something.
