### ISSUE TITLE
 Back doesn't close chat on android

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#2065]
Map back to ESC?

**Comment by MoNTE48** [comment]
Confirm. Please, fix

**Comment by sapier** [comment]
well this ain't a really "fixable" issue. chat window is a formspec and by definition a formspec could contain multiple text input fields.
Especially as this window is already about to be replaced by console I'm not really eager to write code for trash ;-)

**Comment by ShadowNinja** [comment]
@sapier, other formspecs close when you hit back.

I'm no longer able to reproduce this though.

@MoNTE48, are you using a recent dev build?

**Comment by MoNTE48** [comment]
Sorry, on last dev build BACK closed chat formspecs.
And bug, BACK button don't cansel loading world (ESC on PC cansel this).

**Comment by kaeza** [comment]
The back button does cancel loading on 0.4.10 (official build for Android), FWIW.

**Comment by MoNTE48** [comment]
and on 0.4.11 release and curent dev version!

**Comment by sapier** [comment]
"BACK" closes chat menu on android to as long as you're not within the text edit field. At least for me. Are you sure you're not in text field edit mode?

**Comment by sapier** [comment]
Kaeza please open a separate issue for loading cancel as it's completely different and not related to the (possible) formspec issue mentioned here

**Comment by paramat** [comment]
Bug is fixed it seems.

@MoNTE48 please open a separate issue for loading cancel, if still present.
