### ISSUE TITLE
Inventory button is too small

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#2067]
You can use gui scaling setting to increase it!

**Comment by MoNTE48** [comment]
Confirm. This is bad!

**Comment by sapier** [comment]
any suggestions not including filling whole screen with huge buttons?

**Comment by MoNTE48** [comment]
The debug button, noclip, speed and full view to hide and add ... button which will show them.
The size of the button gear should be the same as the other buttons.

**Comment by rubenwardy** [comment]
The sizes are ok on my device. Although the UX needs a better design

**Comment by MoNTE48** [comment]
![screenshot_20160922-020448](https://cloud.githubusercontent.com/assets/6764600/21084716/7ed33920-c010-11e6-84a5-3e303dce4c2c.png)

**Comment by rubenwardy** [comment]
That's actually very similar to how I was going to design the controls - two analog sticks: left for movement, right for camera. Just seems like a more natural way, IMO

**Comment by MoNTE48** [comment]
joystick to control the camera is not very convenient (IMO). Now I experiment with the return of crosshair on Android (thank's @ sfan5)

**Comment by rubenwardy** [comment]
Guess I would have found that out through testing :)

**Comment by MoNTE48** [comment]
@rubenwardy I'll be glad to see your control option (and if it is a comfortable - I did fork) :D

**Comment by paramat** [comment]
@srifqi is this old issue fixed yet?

**Comment by srifqi** [comment]
@paramat I agree with @rubenwardy, the sizes are okay on my device. But, with this UI design, it will be hard for small-screen user.

**Comment by paramat** [comment]
Inventory is the 3 small squares on the left side?
Perhaps the button is too close to screen edge to use with a case?

**Comment by paramat** [comment]
@srifqi @stujones11 what's the actual issue here? What does 'too small' mean? Visually? Or is the detection area of the button too small?

**Comment by srifqi** [comment]
I agree, the actual issue is not clear. As I stated above, the sizes are okay.

**Comment by paramat** [comment]
No response.
