### ISSUE TITLE
Entity detach crash while chat/command line is open

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#2072]
Set up a Minetest server instance (not a singleplayer session), minetest_game should be sufficient, and add PilzAdam's carts mod.  If possible, compile and add kaeza's irc mod (and its luasocket5.1 dependency) and add the related irc_commands mod, and get the server into an IRC channel.

Connect to the server and build a long run of railroad track going down a steep hill.  You'll need a fairly long run, perhaps 100+ nodes, to ensure that there's enough run time on the track for the bug to assert itself.

Place a cart at the top of the hill, stand behind it and punch it.   The cart will start down the hill -- quickly right-click on it to get in and ride the cart down.

While the cart is on its way down the hill, open the chat/command line with 't' and start to type something i.e. a regular chat message (it doesn't matter what) but don't hit enter.

If the cart falls off the tracks or gets stuck part way down the hill, the client will lock up completely (requiring a SIGKILL) and the server will peg at 100% CPU.  It will stop talking to clients, but it'll still respond to IRC commands such as `Botname: players` and others.  At this point, you can issue the command `Botname: cmd shutdown` in the server's IRC channel, and the server will shutdown gracefully.  Ctrl-C or SIGINT will probably also suffice.

It may take several tries to get the cart to fall off the tracks and for this lockup/crash to occur.

My client was at commit 3c3887bb198c07b50ad3451f228aadfe6fd25168 and server is at 900fa26965a2fbdf2b9de74e2d680c083de91482.

If you can't reproduce using minetest_game + carts, try again with Dreambuilder (older code, and carts is included therein).

**Comment by rubenwardy** [comment]
closing, as no recent reports
