### ISSUE TITLE
Disharmonious GUI/Font scaling

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2077]
This is addressed to @sapier. Here's the screenshots & detailled explanations you've requested yesterday on IRC...

From the up-to-date Git HEAD (compiled one hour ago with Freetype) with a clean minetest.conf (nothing set inside) and no tricking/external font : 
- Initial display (scaling factor at 1.0) : https://mediacru.sh/inmOiURnWiM6
> The tabs goes beyond the header, everything is oversized and extravagant.
> Translated in french, the text (which is commonly longer than in english) exceeds easily its limits (scaling at 1.0, latest -dev build from yesterday), ex.: https://mediacru.sh/I3vpen2sqVvn

- Scaling factor at 0.85 : https://mediacru.sh/7B5lAClcqMMz
> The GUI elements become decents but the fonts are skinny compared to their size.

- Scaling factor at 0.75 : https://mediacru.sh/9gZUXU_MfGlo
> The font scaling is nice but the GUI elements become undersized both in the menu and in game (ex.: https://mediacru.sh/XxgzQJDnrf9d).

My conclusion is that the adequation GUI / font ain't good and seems mainly adapted to the Android user-convenience.

Now for comparison with 0.4.11 stable : 

- Initial display (scaling factor at 1.0), slightly too little but that remains acceptable : https://mediacru.sh/aXg6f_BeehRV

- You get a globally pleasant GUI/fonts scaling at 1.10-1.18 : https://mediacru.sh/SKinmOK06G2h

**Comment by sapier** [comment]
nope fonte size ain't adjusted to android for what I remember zefram fysh did try to get it as close to old for 1.0 scaling and 800x600 screen size

**Comment by cheapie** [comment]
Text in text boxes doesn't seem to scale at all for me, no matter what I set it to.
Formspec buttons seem to scale more slowly everything else, while the formspecs themselves seem to scale faster than most of their elements.
On top of all this, I had to set the GUI scaling value to 0.82 just to make everything that does scale properly a reasonable size (similarly to 0.4.11 stable).

My screen resolution is 1280x1024, if it helps at all.

**Comment by Zeno-** [comment]
Although you can get "almost right" results by changing gui_scaling (in my case I have to change gui_scaling to 0.65) this introduces the same issue as last time.

For example. In a message/chat box start typing. You get to the end of the input box (control), keep typing, and the text does not scroll to the left so you can see what you're actually typing.

**Comment by ChaosWormz** [comment]
The font is definitely far to big

**Comment by Wayward1** [comment]
Yes, it's too big for my liking as well. Also, it doesn't seem to fit in the text input boxes well.

**Comment by kilbith** [comment]
Fixed.
