### ISSUE TITLE
text input: ctrl + arrow doesn't move one word

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2079]
On a desktop using ctrl with your movement keys in text will move the cursor one word. This isn't the case in MT, but it would be nice and make the text fields more comfortable.

**Comment by rubenwardy** [comment]
this sounds like an upstream issue to me

**Comment by nerzhul** [comment]
yes it's irrlicht related

**Comment by paramat** [comment]
Any point keeping this open?

**Comment by rubenwardy** [comment]
It's fairly minor and also platform dependent, so I say no
