### ISSUE TITLE
Object highlight

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2080]
Most of us really like the new node highlight, which makes it easier to see which and if a node is selected.

Objects and items on the other hand are still "highlighted" by the wireframe box. Which doesn't look that great and sometimes makes it hard to see, if there are many object that are far away.

I don't think the current node highlight would work to great because it changes the colours of the item/object. (i know the default highlight image can be changed).

Here is my suggestion how an object highlight could look, without altering the appearance of the object.

I just applied a drop shadow. I know it doesn't fit that well, because it isn't as blocky. But i just wanted to have some pics that illustrate what i mean by highlighting without changing the appearance of the object. I think you could make a shadow like this look more blocky. Maybe by giving it a blocky texture.

![bugreport-item-highlight](https://cloud.githubusercontent.com/assets/1377943/5650719/35d39f70-96a1-11e4-8fe8-1b49034193d1.png)

![bugreport-item-highlight_chicken](https://cloud.githubusercontent.com/assets/1377943/5650718/35d2f700-96a1-11e4-8087-68fe8a219ffc.png)

**Comment by MT-Modder** [comment]
:+1: This would be a great addition to the node highlighting feature.

**Comment by MoNTE48** [comment]
:+1: Best idea!

**Comment by rubenwardy** [comment]
I'd like to see this. Customisable colors may be an idea in the entity data, but not required. minetest.conf is enough.

**Comment by TriBlade9** [comment]
I like this, but drop shadows may be deceptively hard. Perhaps get @RealBadAngel to take a look at it?
Also I don't think it fits with the node highlighting very well. There needs to be something that blends them together somehow.

**Comment by rubenwardy** [comment]
These aren't drop shadows, they're just blurs around the object. You could do it with just a shader, probably.

Dynamic shadows is on RBA's todo list, iirc.

**Comment by Jordach** [comment]
My suggestion is to have rotating hitboxes / collision boxes as well as a
collision box based from the shape of the mesh. This would solve lots of
time when making entity based mods.

**Comment by paramat** [comment]
Objects and items are now highlighted by the halo.
