### ISSUE TITLE
Mapgened Water and Lava Sources Do Not Flow

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#2082]
**Minetest Engine Commit:**  ef140eb

Since the later updates to 0.4.10 I've been noticing that mapgen placed water and lava sources took longer and longer to begin flowing. Now, after 0.4.11, they've become completely static.

When I place a node next to a water or lava sources *then* that source node will begin to flow and, in squence, begin to cause the other sources to flow.

When I place a water or lava source, it begins to flow almost instantly.

So the static, non-flowing water and lava sources seem to be limited to the ones placed as the map chunks are first created.

Screenshots (coords and map seed included):

**Water not Flowing**
map seed:  123456789
coords:  225,16,382
![Water sources not flowing to fill in area](https://dl.dropboxusercontent.com/u/30991334/mt0411_water_not_flowing_.png)

**Lava not Flowing**
map seed:  123456789
coords:  336,-89,217
![Lava sources not flowing to fill in area](https://dl.dropboxusercontent.com/u/30991334/mt0411_lava_not_flowing.png)

**Comment by RHRhino** [comment]
@LazyJ: I don't think that this is not a new behavior. This happens as long as I can remember (0.4.10 also had non flowing lava/water).

**Comment by MT-Modder** [comment]
Same as #2003.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/4a57ef12a163f9792a8822b6e1a2bd9dca4f86fb

**Comment by LazyJ** [comment]
Thanks for the fix, kwolekr. ;)
