### ISSUE TITLE
Dynamic throwing distance from inventory

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2086]
If you have a game or mod with auto pickup you probably got annoyed by the following:

You are in the inventory and throw something away. But it is to close, so when you move you pick it up. For some reason i always try to throw it as far away as possible by clicking at the upper edge of the screen. And it has no effect!

So image MT had a variable like max_throwing which has a value of 10. Then the vertical resolution of MT is 100%. So when you click in the top quarter of the screen you throw with 75% of the throwing distance so you drop your item 7 blocks away.

Here a image that illustrates it with a imaginary value of 100% = 10 blocks:

![feature-throwing-distance](https://cloud.githubusercontent.com/assets/1377943/5666576/d15bef3c-9760-11e4-96b2-1d8124d59122.png)

If someone has a better title for this issue i am happy to change it.

**Comment by Calinou** [comment]
In Terasology, the throwing distance depends on how much you have held the Drop key for.

**Comment by lightonflux** [comment]
Distance by key press duration would be much easier to implement.

**Comment by paramat** [comment]
:-1: 
But how about we solve this simply by just reconsidering and increasing the hardcoded velocity a little?
Note this is only an issue with auto-pickup mods, which should have a radius parameter already.

**Comment by C1ffisme** [comment]
I'm not sure why this would be easier to implement based on key-press duration. In that case, we have to write-up a system to detect how long a player holds down a key if it doesn't already exist.

In this case, all you have to do is multiply the current throwing distance by the height of the window minus the y-value of the cursor on the window. (`distance = current_distance * (window_height - mouse_y)` At least in a system where a mouse cursor at the top of the window has a y of 0 and a cursor at the bottom has a y of window_height.)

Anyway... Even if it is kinda pointless, I do think it would be a nice easter-egg for people to enjoy.

**Comment by paramat** [comment]
I'm just thinking of tuning a hardcoded value as a very quick fix, can't be bothered to do anything more complex.

**Comment by ExeterDad** [comment]
This would be great. Even better with "key press duration", far better still with basic left-right aiming. This would give the ability to "spread" prizes and such around rather then multiple items in one spinning bundle.

**Comment by C1ffisme** [comment]
@paramat How long does it take to write code that imports whatever header file has the window resolution and preforms the simplest arithmetic?

**Comment by paramat** [comment]
More time than i can justify.
I think 3 nodes away is enough, auto pickup of 1-2 node radius is plenty (and 2 often too much).

**Comment by paramat** [comment]
PR #6410

**Comment by paramat** [comment]
We're considering a throwing API, possibly using the drop code, if done then variable throw distance from inventory could be coded then. So this may still happen.
I'm not sure this issue is worth keeping open though, seems very low priority and has been open for 2 years.
An issue for a throwing API (including this feature) would be more justified.

**Comment by paramat** [comment]
No dev interest.
