### ISSUE TITLE
Android Hardware scaler

### ISSUE THREAD

**Issue by ezraanderson** [minetest/minetest#2087]
Suggestions for better Android experience.

Scaling, Font, Gui, Fps :
1. Set a static low resolution size for the android hardware scaler in irrlicht.
2.  Set minetest gui scaling to a static number in the java-host-return and it should work well on all devices.
3. Then remove the scaler form the gui menu.
4. It will also give a few more fps to minetest when down scaling from higher res-devices.

``` C
\deps\irrlicht\source\irrlicht\CEGLManager.cpp

Code: Select all
    #if defined(_IRR_COMPILE_WITH_ANDROID_DEVICE_)
        EGLint Format = 0;
        eglGetConfigAttrib(EglDisplay, EglConfig, EGL_NATIVE_VISUAL_ID, &Format);

    // YOU DON"T WANT IT RUNNING AT THE MAX RESOLUTION OF THE DEVICES, 720p and 1080p makes minetest run poorly on low end devices
    //MAYBE 320x480

        ANativeWindow_setBuffersGeometry(EglWindow, 720, 480, Format);
    #endif
```

**Comment by sapier** [comment]
Ineresting idea I'm gonna have a look how this can be integrated

**Comment by ezraanderson** [comment]
~
Well unity for example allows down scaling to 720p because most android that support 1080p still can not play game well enough at 1080p.  Most xbox and ps3 games all so use 720 vs 1080. Minetest is not very demanding game and probably plays well on newer android devices, but on tegra 3 and lower devices, I have pretty spotty performance even when down scaled. Down scaling is a minor tweak but does help a little.  

1. Its also just a suggestion maybe people can investigate further
2. Using it as an option would also work well.

Interesting article 
http://www.cinemablend.com/games/Xbox-One-Unlikely-Hit-1080p-With-DX12-Says-Witcher-3-Dev-66567.html

**Comment by sapier** [comment]
I tried to implement this but for some unknown reason irrlicht does the scaling correct but fails to get ui positions correct. Did you experience same issue?

**Comment by ezraanderson** [comment]
~
You are correct there is a problem with touch_x,touch_y on the irrlicht side when setting the android hardware scaler.  I never tried MT on the phone before so I was unaware of the issue.

An ugly patch to fix this would be this:
\deps\irrlicht\source\irrlicht\CIrrDeviceAndroid.cpp
```C
s32 pointerCount = AMotionEvent_getPointerCount(androidEvent);
s32 pointerIndex = (eventAction & AMOTION_EVENT_ACTION_POINTER_INDEX_MASK) >> AMOTION_EVENT_ACTION_POINTER_INDEX_SHIFT;     


float wWidth  = 720.0f / ANativeWindow_getWidth(app->window);
float wHeight = 480.0f / ANativeWindow_getHeight(app->window);
float tX      = AMotionEvent_getX(androidEvent, pointerIndex)*wWidth;
float tY      = AMotionEvent_getY(androidEvent, pointerIndex)*wHeight;
LOGD("IRRLITCH --> width %f height %f x %f, y %f", wWidth,wHeight,tX,tY); 
```
Lower down in the CIrrDeviceAndroid there is some code for CreationParams, the proper fix might be there.
line :323
```C
case APP_CMD_INIT_WINDOW:
```
Gist
https://gist.github.com/ezraanderson/12a61324d1d36f525db4

**Comment by sapier** [comment]
https://github.com/sapier/minetest/tree/android_hw_scaler_addon is what I have sofar, I think I did implement it the way you suggested. It does improve the situation but doesn't actually fix it. Any suggestions?

**Comment by ezraanderson** [comment]
Try stetting the "device->CreationParams.WindowSize.Width" the same size as the buffer, I tried it on a couple of devices it appears to work.

```C++
if (device->CreationParams.WindowSize.Width == 0 || device->CreationParams.WindowSize.Height == 0)
{
//device->CreationParams.WindowSize.Width = ANativeWindow_getWidth(app->window);
//device->CreationParams.WindowSize.Height = ANativeWindow_getHeight(app->window);
device->CreationParams.WindowSize.Width = 720;
device->CreationParams.WindowSize.Height = 480;
}
```

**Comment by rubenwardy** [comment]
sounds like undersampling, which we already have
