### ISSUE TITLE
Android  Fps dips:

### ISSUE THREAD

**Issue by ezraanderson** [minetest/minetest#2088]
4.10 stable android, Fps dips:

This code seemed to cause me problems on my android version of minetest, it gives 5fps dip every time it gets executed which makes for an unpleasant experience. Not sure if you have the same problem or a patch.
```C
/minetest/blob/master/src/server.cpp

Code: Select all
    994: while(m_unsent_map_edit_queue.size() != 0)
```

**Comment by sapier** [comment]
well this is the code doing communication between server and client. It's quite natural your fps drop while game has to do different things.
