### ISSUE TITLE
Android crashes on main menu

### ISSUE THREAD

**Issue by ezraanderson** [minetest/minetest#2089]
4.10 stable android, Crashes on main menu when idling

Crashes if you let it idle for a long time on the main menus, it appears to be caused from displaying images on the main menu gui, I resolved this from removing all images from the menu but I am sure there is a code fix somewhere.

**Comment by MoNTE48** [comment]
Pls, test my UNOFFICIAL 0.4.11-dev build:
http://195.154.230.137/1/Minetest03.01.15_MoNTE48.apk

**Comment by MoNTE48** [comment]
Please close it! This is not bug

**Comment by paramat** [comment]
@ezraanderson still a problem?

**Comment by ezraanderson** [comment]
unsure
