### ISSUE TITLE
rollback.sqlite grows in size but enable_rollback_recording is false

### ISSUE THREAD

**Issue by apoleon** [minetest/minetest#2090]
Since I upgraded my dedicated server to 0.4.11 the file rollback.sqlite grows in size although I have set enable_rollback_recording to false. This did not happen with 0.4.10. I would like to disable this feature because currently I don't make use of rollbacks. How can it be disabled now?

**Comment by CasimirKaPazi** [comment]
Can confirm. It also gets recreated after deleting.

**Comment by nerzhul** [comment]
I looked at the option. It seems the option is correctly set but never used.

**Comment by apoleon** [comment]
Hello,

it seems this bug is gone in 0.4.12 and disabling enable_rollback_recording works again.

**Comment by nerzhul** [comment]
hi @apoleon right, i fixed the issue but forget to close the issue :) thanks
