### ISSUE TITLE
server flag icons don't show

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2099]
I'm using:
OS: windows 7 32-bit
Build: https://forum.minetest.net/viewtopic.php?f=42&t=9515&start=50#p167343
At commit: https://github.com/minetest/minetest/commit/56a89fd

Picture:
![capture](https://cloud.githubusercontent.com/assets/7414772/5690480/0ecc2964-985a-11e4-9cfd-265b2a55008f.PNG)

Here is the error:
```
Irrlicht log: Could not open file of texture: C:UsersThomasDownloadsminetest_releasetexturesbasepackblank.png
Irrlicht log: Could not open file of texture: C:UsersThomasDownloadsminetest_releasetexturesbasepackserver_flags_creative.png
Irrlicht log: Could not open file of texture: C:UsersThomasDownloadsminetest_releasetexturesbasepackserver_flags_damage.png
Irrlicht log: Could not open file of texture: C:UsersThomasDownloadsminetest_releasetexturesbasepackserver_flags_pvp.png
```

**Comment by ShadowNinja** [comment]
Seems like someone forgot a `minetest.formspec_escape` call...

**Comment by MT-Modder** [comment]
wow something so simple :smiley:

**Comment by ShadowNinja** [comment]
Related to #2095.

**Comment by ShadowNinja** [comment]
Oops, looks like it's my fault.  77e20a0c2188ab260e571a0406959113faa3e850 should fix it.
