### ISSUE TITLE
online mod repo won't load

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2101]
I'm using:
OS: windows 7 32-bit
Build: https://forum.minetest.net/viewtopic.php?f=42&t=9515&start=50#p167343
At commit: 56a89fd

Here is the error after opening:
```
23:56:54: ERROR[AsyncWorkerThread_2]: https://forum.minetest.net/mmdb/mods/ not found (Unsupported protocol) (response code 0)
```

Here is the error after closing:
```
WARNING: not a single toplevel ui element active switching to default
```

**Comment by MT-Modder** [comment]
Here is the forum topic about this issue.
https://forum.minetest.net/viewtopic.php?f=6&t=10768

**Comment by sapier** [comment]
You can ignore the warning, it's a relic I've fixed in some code never beeing merged. It's not related to the problem you have.

**Comment by MT-Modder** [comment]
Okay.

**Comment by MT-Modder** [comment]
@sapier rubenwardy told me to ask you about this problem to see if it's a client side issue. The forum topic has more information about this issue.

**Comment by C1ffisme** [comment]
@sapier Why are we leaving an error here? Can we please fix it rather than leaving a message in the terminal? If we do not fix this, then please close the issue.

**Comment by MT-Modder** [comment]
Well it looks like there's no more online mod repo so....closing this.
