### ISSUE TITLE
Jungles sometimes generate in mid-air

### ISSUE THREAD

**Issue by CraigyDavi** [minetest/minetest#2104]
Image taken on a new v6 world using default minetest_game with no extra mods.
![Image](https://cdn.mediacru.sh/3/3Lci_bkmHt_7.png)
^ Screenshot shows jungle tree and jungle grass in mid air

**Comment by tenplus1** [comment]
The same problem exists in v7 maps also.  For some reason the landscape is drawn and decorated then caves/cliffs/ridges are carved out afterwards leaving things floating in mid air...

**Comment by paramat** [comment]
Normally trees are added after caves are cut, occassionally there is a glitch where this is reversed. Your screenshot seems to show part of a glitchy large cave that is protruding from an adjacent mapchunk, it looks to have a flat wall along one edge of the pool, this is a sign of a large cave glitch. As far as i know very difficult to fix and is a well known bug.

**Comment by kwolekr** [comment]
The only way to fix this is to remove mapchunk borders :/
It's an issue with 'discretely placed structures' in general.  I was mindstorming some ways to fix this overarching, large problem, and one way we could do it is to plot all these types of features on the map in advance upon world creation and only place the nodes for the portion intersecting with the mapchunk currently being generated.  Hrmm...
