### ISSUE TITLE
Can't disable mudflow

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#2110]
I've put this into "minetest.conf" BOTH within my game folder and minetest folder:
````
mg_flags = trees, caves, nodungeons, light, v6_jungles, v6_nomudflow, nomudflow
mgv6_spflags = biomeblend, jungles, nomudflow, v6_nomudflow, v6_jungles, nodungeons
````

but dirt, sand, desert sand and desert stone (!!!) still flow down O_o

As one can see, I had to disable dungeons, cause those made the whole thing even worse.

Why do stone flows anyway?

**Comment by paramat** [comment]
Only dirt flows during mapgen to make the terrain look more eroded. Dungeons do not make it worse.
All you need is 'nomudflow' in mgv6_spflags..

**Comment by 4aiman** [comment]
As you can see I've that one there...
So, I guess, mudflow has nothing to do with following:

https://dl.dropboxusercontent.com/u/39772195/mtmods/111/screenshot_138599250.png
https://dl.dropboxusercontent.com/u/39772195/mtmods/111/screenshot_138613900.png
https://dl.dropboxusercontent.com/u/39772195/mtmods/111/screenshot_138669782.png
https://dl.dropboxusercontent.com/u/39772195/mtmods/111/screenshot_138707629.png
https://dl.dropboxusercontent.com/u/39772195/mtmods/111/screenshot_3656149011.png

**Comment by MT-Modder** [comment]
I believe paramat is saying that this is all you need:
```
mg_flags = trees, caves, nodungeons, light
mgv6_spflags = biomeblend, jungles, nomudflow
```

**Comment by 4aiman** [comment]
Well, I knew that was an overkill, but it *is* confusing to have multiple mg flags, e.g. **nomudflow** is referred as **mgv6_nomudflow** in the code.
Regardless of whether the issues I have are connected with the mudflow feature (but then again, which one?) or not, that confusion goes nowhere.

So, if I may suggest so, it would be much easier to have just one *mg_flags* param and a list of described options for that, e.g. something like this:
````
#mg_flags - trees, caves, light, dungeons
#^ Used to enable/disable inbuilt mapgen features. Default ones are shown above.
#^ Note, that some flags are only available for a certain mapgen version.
#^ Those flags should be prepended by a *mgvX_*. For example, there's a *biomeblend* flag that is specific for mapgen v6. To enable it you should supply a *mgv6_biomeblend* option alongside the "universal" ones, e.g.
# mg_flags = mgv6_biomeblend, trees,  caves, light
#^ To effectively disable any feature just prepend any option's name with a *no*, e.g. 
# mg_flags = *nodungeons*, *mgv6_biomeblend*, trees
# The lists of features, supported ATM can be found below:
# universal (can be activated for any mapgen version)
# *mapgen v5:*
#    ... - does this and that
#    ... - enables generation of this and that
#    ... - make it so, that X is like Y and Z
# etc
#* mapgen v6:*
#    ... - does this and that
#    ... - enables generation of this and that
#    ... - make it so, that X is like Y and Z
# etc
#* mapgen v7:*
#    ... - does this and that
#    ... - enables generation of this and that
#    ... - make it so, that X is like Y and Z
# etc
````
^ That would be much more sane than additional mgvX_spflags. 
As for the backwards-compatibility - the engine may as well read mgvX_spflags into mg_flags. Somewhere @ ver. 0.5 that compatibility may be broken.
But to tell the truth, strict.lua breaks much more than this, so I see no harm in getting rid of mgvX_spflags right away.


^ That was only a speculation. Can anyone tell me what flags are available for every mapgen (including "universal" options)? Current lua_api.txt doesn't have much sense in that term as well as the code (see above) uses different names for option. (I *do* hope I'm not expected to prove that nomudflow is referred as mgv6_nomudflow in the sources.)

P.S.: I just "made up" the default features list

**Comment by kwolekr** [comment]
Can anybody confirm if this is still an issue?

@4aiman: I was under the presumption that these settings were documented... my apologies if they aren't.  They were originally all in the same flags field and I split them up afterwards since having multiple map generators each adding their own settings could fill up the available bit space quickly, and it's very messy as well..  Boolean settings specific to a single map generator are therefore separated into the "mg<name>_spflags" settings.  For what it's worth, I have plans later to break out all these different flag fields into discrete boolean setting fields... maybe that will help make them more understandable.

**Comment by paramat** [comment]
> So, I guess, mudflow has nothing to do with following:

Correct.
All you need is 'mgv6_spflags = nomudflow' in minetest.conf.
The documentation for flags is in minetest.conf.example near the end.
Nomudflow does indeed stop mudflow, i was the one who requested the option and tested it.
