### ISSUE TITLE
Problems with building

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2111]
Hey, I downloaded the minetest source, and thought I might play around with the code, etc. But when I changed dungeongen.cpp, saved, and tried to build the file. However, through a long line of "includes", it was importing a file called "irrTypes.h". This file didn't exist.

I do have the irrlicht-dev package, I am playing around with minetest 0.4.10, on Lubuntu. I have a Dell Latitude D620 laptop. (Not that I know what the computer type will help with.)

I don't think this is a bug since several people have been able to fork and pull request minetest. Actually, I think it's more of the question: "What did I do wrong?" but go ahead and awnser it, and I'll stop talking.

**Comment by sapier** [comment]
C1ffisme a bug tracker is for reporting issues. 
forum.minetest.net is for questions, please write there or join #minetest at irc.freenode.net.
