### ISSUE TITLE
Android GUI VERY big

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2114]
I look last commit.
Main menu smallest, game GUI VERY big. Pls, compile and check!

**Comment by sapier** [comment]
can you post screenshots as well as device information.
menu does autoadjust to your device so even if it works for me it may still be broken on other configurations.
Another option is deleting the Minetest folder on your sdcard or at least the included minetest.conf file

**Comment by MoNTE48** [comment]
I tested on Galaxy S, Galaxy S4 and Galaxy Note 4.
Look game control - very big!

**Comment by sapier** [comment]
Screenshots!

**Comment by MoNTE48** [comment]
Main Menu: http://hostingkartinok.com/show-image.php?id=18d80a1693f26c320803108dd73a65fd
Game control: http://hostingkartinok.com/show-image.php?id=6c46f75ca40eca0da4bcf09d628d2898
On Galaxy S4

**Comment by kilbith** [comment]
By the way, @MoNTE48, you should give the right credit / link source to Minetest when you propose your renamed builds on the Google Store ;) And not hidden at the very bottom of the description by preference...

**Comment by MoNTE48** [comment]
@kilbith , please, write me on email MoNTE48@mail.ua and help me sourse code and credits organization.
Thank you!
(OFFTOP)

**Comment by proller** [comment]
https://pbs.twimg.com/media/B7GlyuSIcAArkbW.jpg:large

**Comment by MoNTE48** [comment]
@proller freeminer? Best!
Hmm, this is LAST commit?

**Comment by sapier** [comment]
sorry but this is a modified build please verify it's wrong in original build too!

**Comment by MoNTE48** [comment]
OK, I check this

**Comment by MoNTE48** [comment]
I check this.
Game gui good.
MainMenu small, +15% size is good.
Press New/Configure build - VERY big menu.
http://sendimage.me/8Z2IXirc
