### ISSUE TITLE
Hotbar is far too big

### ISSUE THREAD

**Issue by davisonio** [minetest/minetest#2118]
![Image](https://cdn.mediacru.sh/Y/YoSXNMC1BoLi.png)
^ Left window is using commit https://github.com/minetest/minetest/commit/7ad17a25f4dfc81427df54d5c855b40b4472d517 and right window is using commit https://github.com/minetest/minetest/commit/c367f7301a4bd2f69a84b53392439482abd6dc5a

Might be related to #2114

**Comment by CraigyDavi** [comment]
Also I've noticed that the scrollbar on the main menu server list is bigger than it used to be.

**Comment by kilbith** [comment]
Same here.

**Comment by MoNTE48** [comment]
The scroll bar is now very good!
Previously on Android was difficult to scroll. Now it was good!

**Comment by ShadowNinja** [comment]
I can confirm, it's HUGE now.

**Comment by sapier** [comment]
can you please post what os and screen resolutions you use?
proprietary hud scaling was removed and replaced by a dpi based hud adjustment.
Yet dpi detection ain't implemented on windows.
Of course the default size could be wrong too, try hud_scaling parameter to find out if it'd be fine for a different value then 1.0

**Comment by ShadowNinja** [comment]
Arch Linux, KDE, X11, 1366 x 768, 15".
About 0.6 looks good.  I use 0.9 for `gui_scaling`.

**Comment by MoNTE48** [comment]
Android. 0.6-0.7 is good.
(S4)

**Comment by paramat** [comment]
@davisonio still a problem?

**Comment by davisonio** [comment]
I'm not noticing the problem anymore, perhaps it was fixed.

@kilbith, @ShadowNinja is the problem still occurring for you?

**Comment by kilbith** [comment]
> I'm not noticing the problem anymore

Ditto.

**Comment by davisonio** [comment]
:tada:
