### ISSUE TITLE
Volume key Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2122]
On Android port Volume key don't work.
Tested on more device.
Don't change volume and don't show volume panel,
Pls, fix.
And Volume (+ -) and power (screenshot on more ROM) = error on chat!

**Comment by MoNTE48** [comment]
This is quite a critical bug. Any options?

**Comment by ShadowNinja** [comment]
Related to #1454.

**Comment by paramat** [comment]
This bug is in your fork Multicraft? If so is this bug reproducable in Minetest?

**Comment by MoNTE48** [comment]
@paramat, This is a bug in Minetest and I could not fix it until now. However, I am working on a temporary fix right now.

**Comment by DonBatman** [comment]
I can confirm that the volume buttons do nothing in official minetest for Android

**Comment by Zeno-** [comment]
I know this is certainly the case with official minetest Android build because I was trying to work on a fix for it before my break. I'll see if I have any related notes on my laptop regarding it (but I doubt it unfortunately).
