### ISSUE TITLE
Multiserver proxy - BungeeCord alternative in Minetest

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2124]
Will be possible create some kind of multi-server proxy like BungeeCord in Minecraft?

http://www.spigotmc.org/wiki/about-bungeecord/

**Comment by TriBlade9** [comment]
I'd love this idea, but I have no clue how it would be implemented safely in Minetest.
Minetest doesn't even have multiple worlds per-server yet.

**Comment by ShadowNinja** [comment]
Bungeecord seems to be implemented as a separate daemon that simply proxies requests to servers.
You could probably implement something similar for Minetest without too much trouble.

**Comment by rubenwardy** [comment]
I'm not sure how why this is an engine issue, when it should be a suggestion for an external project
