### ISSUE TITLE
Don't show console window by default on windows

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2128]
You can disable console window in game and add a checkbox to settings.

**Comment by ShadowNinja** [comment]
I don't understand what you're saying.  Could you restate it differently?

**Comment by MoNTE48** [comment]
When I open Minetest opens two windows: the game window and Debug window.
I suggest to disable Debug window by default and add its inclusion in the settings.

**Comment by ShadowNinja** [comment]
This is intentional: https://github.com/minetest/minetest/blob/0fd1ee03808ee8121e7b65e5c7c9ba19599d185e/src/main.cpp#L37

**Comment by MT-Modder** [comment]
I like the ability to disable the debug window but I don't like the idea of it being disabled by default.

**Comment by SmallJoker** [comment]
I love the debug window. There's no need to hide it because it's easier to read something from there than opening the debug.txt file

**Comment by ngosang** [comment]
Hide the console by default seems like a good idea. Keep in mind that most people who use windows  never have seen a console and can be scary. For me, the ideal would be that the console was hidden by default and you can show it somehow. If someone needs to report a bug you can request the debug.txt file.

**Comment by MoNTE48** [comment]
@SmallJoker for developers? Yes.
More users don't use debug.

**Comment by est31** [comment]
What about disabling it for release builds, but keeping it for debug builds?

**Comment by Fixer-007** [comment]
It is good for devs but not for actual players, so it can be hidden by default and controlled via config.

**Comment by adrido** [comment]
https://github.com/minetest/minetest/pull/5416
