### ISSUE TITLE
index out of bounds at src/mapblock_mesh.cpp in finalColorBlend()

### ISSUE THREAD

**Issue by hasufell** [minetest/minetest#2134]
https://github.com/minetest/minetest/blob/master/src/mapblock_mesh.cpp#L349
https://github.com/minetest/minetest/commit/807a0d31#commitcomment-9304193

Could be due to a mod maybe, but this shouldn't happen.

**Comment by Zeno-** [comment]
Thanks.

commit 5e58a954910d9a9a3368bee71ab3aa0b3baf7c3a
