### ISSUE TITLE
Hotbar position should be changeable from Lua

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#2139]
If any subgame wants to have their hotbar elsewhere they need to mess with custom HUD stuff and e.g. update the selected item manually.

(The hotbar position is hard-coded in _hud.cpp_)

**Comment by RobertZenz** [comment]
It might be interesting to not only expose the location of the hotbar but allowing to override it at all. Though this will most likely be easier if #1399 is done.

Exposing only a thin interface and a default implementation would allow mods to override the appearance and location of the hotbar completely. For example a new hotbar would have to simply provide the following entry points:

    item_selected(index) -- When the selection in the hotbar changes
    item_changed(item, index) -- When an item in the given index changes

Mouse events would need to be handled by the implementation, obviously.

The upside of that approach would be that the implementation would not only control the location, but also the appearance. Allowing it to appear as a circle, or folding or vanishing if the selection hasn't changed in some time.

**Comment by 4aiman** [comment]
Hotbar is customizable with images already. All you need is to have a server-side setting hotbar_pos = X Y. Server owners are happy, game maintainers know how to set stuff from Lua.

**Comment by 0-afflatus** [comment]
As a game maintainer I would love to have more control over the hotbar (or at least understand what 4aiman is talking about). I confess I have only looked at it briefly and couldn't figure out to change anything, so decided to put up with the default position. It would be a good way to show players that they are in a different game.

**Comment by rubenwardy** [comment]
You can move the hotbar on the screen, although #2094 is a problem

**Comment by paramat** [comment]
Still relevant and wanted?

**Comment by cx384** [comment]
I suggest to close this issue and refer to #9270 instead.
