### ISSUE TITLE
Minetest.conf ignored on new world creation

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2143]
In my minetest.conf, I put "mg_flags = trees, dungeons", but after I start a new world, the map_meta.txt reads "mg_flags = trees, caves, dungeons, noflat, light". I make sure Minetest is closed before editing the .conf, so my changes don't get overwritten. I've noticed this for a while now, but as I don't really play singleplayer much anymore, it never really bothered me. It does seem to be a significant problem though, as it takes away part of your control over the creation of a new world.

**Comment by ShadowNinja** [comment]
The flags have defaults now.  You have to explicitly specify `trees, dungeons, nocaves, nolight` if you want only those two flags applied.

**Comment by Wayward1** [comment]
Hmm, ok. I guess I was unaware that "noflat" is added automatically if not specified.
