### ISSUE TITLE
Meshnode ligthing issues create unwanted patterns

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2150]
Meshnodes create unwanted patterns, probably due to lighting issues.

Before/After pics of the greatly welcome technic-cnc updates by @VanessaE 
https://mediacru.sh/a194b82e4bec

The issue presents itself textureset independent and is not limited to cnc forms but e.g. also appears with moreblocks slopes.
Tested with recent build a39c136
Mts for reproduction of the bug can be created if it should be necessary.

**Comment by Calinou** [comment]
I believe the engine should always try to render meshes as solid?

**Comment by acerspyro** [comment]
Credit? :D (jk)

**Comment by VanessaE** [comment]
Although it highlights the engine's inadequate lighting process, I think this bug can be closed, since it was determined to be a problem in my models in Technic, rather than an engine bug.  I believe those models are now fixed.
