### ISSUE TITLE
Texture filtering smoothes textures

### ISSUE THREAD

**Issue by neko259** [minetest/minetest#2154]
...and makes them loose the details. Filtering must smooth only distant textures, not all of them.
This happens with bilinear, trilinear and anizothropic filtering.

**Comment by KenneyNL** [comment]
Agreed, not sure who would use any of the filtering options right now. They'll totally break any texture and creates a blurry mess.

![Filtering sample](http://i.imgur.com/NdKwLE9.png)

**Comment by kahrl** [comment]
Bi/trilinear filtering isn't meant to be used with low-res texture packs.

Anisotropic filtering should be fine, but some buggy video cards or drivers implement it incorrectly and make it cause similar effects to bi/trilinear filtering.

**Comment by neko259** [comment]
Is this an incomplete feature or low-res (and default) textures are
intended to be unsupported? I know that minecraft has filtering (not sure
what exactly) and it works fine with its low-res textures, so it definitely
can be done with the same video driver.
19 янв. 2015 г. 19:42 пользователь "kahrl" <notifications@github.com>
написал:

**Comment by PilzAdam** [comment]
> I know that minecraft has filtering (not sure what exactly) and it works fine with its low-res textures

There are many filtering methods, you need to be more specific about this.

**Comment by neko259** [comment]
As I said I don't know what exactly they use. Just know they use some filtering to decrease texture noise when viewing distant blocks.

**Comment by RobertZenz** [comment]
That would be Anisotropic filtering.

**Comment by Calinou** [comment]
This is not a bug.

You should use mip-mapping, and nothing else, if you want to smoothen far away textures only.

**Comment by kwolekr** [comment]
This issue has been fixed as of 1e4fb80d46da634f04d84e3f1065aaabc6909468.  Update to the latest version and set texture_min_size=64!
