### ISSUE TITLE
Command to regen area

### ISSUE THREAD

**Issue by neko259** [minetest/minetest#2155]
I  have a very old map that has areas generated in old mapgen versions but uninhabited. I want an admin command to regen these areas with the current mapgen.
Or a Lua API function for this to run in from WorldEdit on a number of nodes.

**Comment by PilzAdam** [comment]
There was a command added to delete mapblocks recently.

**Comment by neko259** [comment]
Could you point me to a link?

**Comment by PilzAdam** [comment]
9736548720a96c9c7f739edb0435d9ba4ad80652

**Comment by neko259** [comment]
Thanks!
