### ISSUE TITLE
minetest.register_on_chat_message not working properly

### ISSUE THREAD

**Issue by rater193** [minetest/minetest#2157]
minetest.register_on_chat_message only runs when people type a command, not when they actually talk, also can you make it so if you return a string when they type, it sets the message to the returned string. I am working on making a ranked based chat system, and cant do much to it, untill you do that. thanks in advance!

here is the code
![image](https://cloud.githubusercontent.com/assets/6468037/5799991/10ca1c04-9fa7-11e4-9456-7f2716a78fcd.png)

and here is the result, i typed a message first, and nothing happend, but when i typed a command, it triggered.
![image](https://cloud.githubusercontent.com/assets/6468037/5799993/1a43d5ea-9fa7-11e4-8891-bee182f7961d.png)

**Comment by kahrl** [comment]
Works fine for me (executes both for chat messages and chat commands). Make sure none of your other mods aborts processing by returning true.

**Comment by TriBlade9** [comment]
Is client-side chat prediction still a thing? (That needs to die a swift and terrible death)

**Comment by paramat** [comment]
@rater193 still occuring?

**Comment by rubenwardy** [comment]
That will be due to chatplus, probably.

**Comment by ExeterDad** [comment]
I may be experiencing this as well unless I'm misunderstanding usage.
I've been trying to filter and replace words in chat without success. If I type "Hi", I would see in chat <ExeterDad> Hi
Then the next line would show modified chat message. Here's a simple example without any filtering.

```
minetest.register_on_chat_message(function(name, message)
     minetest.chat_send_all("Only this message should appear")
     return true
end)

```
I'm expecting the "return true" to suppress the original chat message, instead both messages show. 
This occurs in Minetest_Game and Minimal without any other mods running

**Comment by rubenwardy** [comment]
That's due to chat prediction. All other users just see the modified chat

When you press enter, it posts it to your screen, it sends, the server runs lua then sends a chat message

**Comment by ExeterDad** [comment]
@rubenwardy as it turns out, you are correct. Connecting with a additional client shows exactly what you described. Using github for support wasn't my intentions, but thank you for your help :)
