### ISSUE TITLE
"Exit to OS" button has the focus in the pause menu. Should be on "continue"

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2158]
When opening the ingame/pause menu via `esc`, the "Exist to OS" button has automaticly focus, leading the game to more often than not being left accidental when the space key is pressed.
Expected behavior is a resumption of gameplay (focus on continue) by default.

Happening since a while, but still with 9b89f7a

To reproduce press `esc` followed by `space` ingame.

**Comment by ngosang** [comment]
One fix could be draw the buttons from bottom to the top, but should be another way...

**Comment by ngosang** [comment]
Fixed by #2217.

**Comment by Zeno-** [comment]
commit dd2bb950be36c3ae34caacfe62df391612364f8a
