### ISSUE TITLE
minetest executes locally installed mods when connecting to a server under certain circumstances

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2159]
When saving to a local world from a remote server with 9b89f7a (though probably since introduction of the feature)
and activating a mod for the just saved world, given mod will be executed when connecting to the associated remote server again. (Including preventing a connection on lua error)

Possivly related to #2024?

**Comment by sfan5** [comment]
This is a byproduct of being able to save MapBlocks. Theoretically the code could use the raw Database interface and not run a server instance.

**Comment by ShadowNinja** [comment]
Fixed by #1845, which removes the ServerMap parameter to the databases (none of them use it anyway).
