### ISSUE TITLE
Glass is always connected despite connected_glass = false in both server side and client side.

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2160]
Same as https://github.com/minetest/minetest_game/issues/394.

**Comment by kahrl** [comment]
Can't confirm. Most likely this is caused by some mod redefining glass (one offender I know of is moreblocks).

**Comment by MT-Modder** [comment]
Okay I'll check.

**Comment by kilbith** [comment]
@MT-Modder MoreBlocks is indeed using the `glasslike_framed_optional` drawtype, which is seems to works correctly only on the full nodes (stairplus in MoreBlocks uses nodeboxes). In practice this messes up these nodes.

The commit problem is : https://github.com/Calinou/moreblocks/commit/f0a455f878c8d72865c91799a793d21bb82e9860

Some players have already reported the bug to @Calinou - he knows pertinently the cause and does not have reacted at all yet ...

![screenshot_607423245](https://cloud.githubusercontent.com/assets/7883281/7002644/7a2c4e22-dc4e-11e4-8d8b-29580b95e50f.png)

**Comment by MT-Modder** [comment]
Hmm...those do look ugly. I wonder when he is going to fix this. He'll have to change his api I believe. I don't know if the engine will ever support connected nodeboxes XD.
