### ISSUE TITLE
Using the distribution's system Irrlicht library

### ISSUE THREAD

**Issue by apoleon** [minetest/minetest#2163]
In Debian the attached patch was applied to achieve the following:

https://gist.github.com/apoleon/197065708305dd696376

Distributions like Debian, Ubuntu, Fedora or Gentoo build against a shared version of the Irrlicht engine. But FindIrrlicht.cmake only looks for a static build. I'm not 100% sure how to properly fix this issue for all use cases but it would be great if we could find a way to drop this patch somehow. In the meantime the FIND_LIBRARY function looks for libIrrlicht.so.

**Comment by nerzhul** [comment]
Right URL:
https://gist.github.com/apoleon/197065708305dd696376

**Comment by sofar** [comment]
`make sharedlib` creates the shared irrlicht .so files. These should be easy to pick up and use instead of a static library...

**Comment by apoleon** [comment]
On Fri, 30. Jan 18:54 Auke Kok <notifications@github.com> wrote:
>    make sharedlib creates the shared irrlicht .so files. These should be easy
>    to pick up and use instead of a static library...

You probably misunderstood this bug report. Linux distributions build
minetest with a separate (not the embedded one), shared version of
Irrlicht. The cmake module to find those system libraries simply needs
an update and should look for the .so files in the right path. A similar
issue exists for the FindJson.cmake module. In general there should
always be a way to use system libraries instead of embedded code copies.
