### ISSUE TITLE
Seemingly infinite firespread / client lockup

### ISSUE THREAD

**Issue by ikeydoherty** [minetest/minetest#2178]
Picture says a thousand words and I decided to test a couple dozen TNT set off with a lava source block. As ya do. Anyway the fire doesn't stop spreading and the inventory UI becomes almost unresponsive :)

![screenshot from 2015-01-21 21 00 23](https://cloud.githubusercontent.com/assets/164489/5845087/14289ff4-a1b1-11e4-9a07-0c4139262ad0.png)

Current build is from a clone yesterday, a6dd6199385fccd0659232b3a4425e9d125c297c

Maybe an option to limit fire-spread would be the way here?

**Comment by MT-Modder** [comment]
I think it would be better to report this issue here: https://github.com/minetest/minetest_game
It handles things like this.

**Comment by ikeydoherty** [comment]
I considered that but it occurred to me this was more an engine issue ?

**Comment by ikeydoherty** [comment]
Re-reported, thanks. Closing ^^

**Comment by MT-Modder** [comment]
I could be wrong but the engine doesn't handle fire specifically. It handles the abm's that are used to spread it which are registered in the "fire" mod in the "minetest_game".

No problem.
