### ISSUE TITLE
Clouds are moving with the player movement

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#2179]
Today a bug occured where clouds followed the player movement. Not sure what was causing that, maybe the massive amount of water falling from the sky. As far as I remember this only happend on server and not in singleplayer so far. Could this be caused because of lag?
https://mediacru.sh/zi1OIyNkpuuW

**Comment by RHRhino** [comment]
Maybe related with https://github.com/minetest/minetest/issues/2035 and https://mediacru.sh/8soQTJmg57qR and https://forum.minetest.net/viewtopic.php?f=6&t=10862??

**Comment by paramat** [comment]
@RHRhino 
> Not sure what was causing that, maybe the massive amount of water falling from the sky

Were you using an intensive rainfall mod? Has it happened again?

**Comment by RHRhino** [comment]
No, just many floating water nodes. I never observed it again, most likely because I turned clouds off roughly since that time anyway. So because nobody else had troubles with this obscure bug, you can close it.
