### ISSUE TITLE
Error loading a new world

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2180]
Always I create a new world, the first time I play it I get this error:
```
13:28:53: ERROR[main]: ServerMap::loadMapMeta(): could not open/home/xxxxxxxxx/.minetest/worlds/xxxxxxxxx/map_meta.txt
```
Everything is working well and the next time I play this world there is no error but this error should not appear because cause alarm for no reason.

**Comment by C1ffisme** [comment]
That happens to me, too. It's really annoying.

**Comment by SmallJoker** [comment]
Duplicate #1708
