### ISSUE TITLE
Possible to sneak+jump through a slab ceiling.

### ISSUE THREAD

**Issue by Phvli** [minetest/minetest#2188]
While holding sneak and forward keys after jumping from a slab, player is able to jump through another slab above him. Player ends up standing on the upper slab.

Vertical layout to reproduce:
layer of air
layer of air
layer of slabs in the upper half of their nodes
layer of air (player's initial position)
layer of slabs in the lower half of their nodes

Possible since 0.4.10 with sneak_glitch override disabled.

**Comment by Wayward1** [comment]
I've noticed this with stairs too

**Comment by paramat** [comment]
#5327 merged, is this fixed?

**Comment by sofar** [comment]
You just bounce in between the 2 slabs now.
