### ISSUE TITLE
Mod Store Mockup Design

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2196]
The Mod Store has wasted potential. Here is a mock up I did on what it could look like (layout is the most important, not colors):

Of course this should wait until MMDB is fixed, if that ever happens...

(Edit: I'm thinking of working on this, I'd like your feedback).

![modstore](https://cloud.githubusercontent.com/assets/2122943/5888604/b009c2ba-a3fd-11e4-95e6-42771b8c6d1f.png)

[PDF version](https://www.dropbox.com/s/1uudn0hoh5m4hap/modstore_design.pdf?dl=0)

**Comment by Calinou** [comment]
Looks good, although I would use gray-ish colours with some green parts to fit Minetest.

**Comment by kilbith** [comment]
:+1:

**Comment by ShadowNinja** [comment]
:+1:

**Comment by Calinou** [comment]
How about this (background colours)?

![Image](https://lut.im/96RUxs6V/Uxs6VG1o)

**Comment by rubenwardy** [comment]
That looks good. The blue was to indicate that there is sky behind the formspec.

**Comment by wilkgr76** [comment]
YES! +20

**Comment by FaraoneLele** [comment]
Any news?

**Comment by sfan5** [comment]
No
