### ISSUE TITLE
Entity is dark in airlike, sunlight_propagates node

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#2199]
How to reproduce: create an airlike, sunlight_propagates node, and put an entity inside it. The entity will be darkened even when it shouldn't.

**Comment by ShadowNinja** [comment]
You might need to set `paramtype="light"` too.

**Comment by paramat** [comment]
@Ekdohibs does that fix it?

**Comment by Ekdohibs** [comment]
This fixed the problem indeed.
