### ISSUE TITLE
A method that allows mods to interupt the account creation proccess

### ISSUE THREAD

**Issue by crazyR14** [minetest/minetest#2202]
I think one thing we are missing is a **minetest.register_on_prenewplayer()** method.

The idea behind it is that it is identical to the **minetest.register_on_prejoinplayer()** method, except if the method returns then the account is not created and the message in the return is posted to screen same way as **minetest.register_on_prejoinplayer()** does.

Mods like *xban* and *No More Guests* would benefit from using this amongst others

**Comment by t4im** [comment]
less unnecessary player files and running of `give_initial_items` or other registered functions when not really needed :+1:

**Comment by crazyR14** [comment]
Turns out this functionality is already available in the minetest.register_on_prejoinplayer() method afterall. :)
