### ISSUE TITLE
Android swipe menu

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2204]
It would be nice if sliding a finger from the edge of the screen opens a menu such as that accessed by pressing the back button. It should also include toggles for fly, sneak (see #2194) and fast.

**Comment by wilkgr76** [comment]
Maybe have sneak & fast permernantly there; show only settings, fly, etc. when doing what you said. I was just thinking that sneak & fast are used lots of times during the game, would be a pain to open that menu each time, esp. on a PvP server (refers more to the latter one)

**Comment by nanepiwo** [comment]
Maybe players can change what buttons are on the screen and which on the swipe menu?

**Comment by wilkgr76** [comment]
I like that! +1

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.
No one is working on Android so i can't see a luxury feature lie this being coded.
