### ISSUE TITLE
Chat covers formspecs on Android

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2208]
At the moment (0.4.10 stable build of Android) chat covers formspecs meaning that chest interaction and many other similar actions are impossible on multiplayer servers. I request chat be hidden in all formspecs on Android builds.

**Comment by ShadowNinja** [comment]
The chat shouldn't be hidden, it should just be drown below other elements.  This was "fixed" one or two times already.  I can't reproduce this on Linux though.

**Comment by MoNTE48** [comment]
Pls, check my build 0.4.11 on forum.

**Comment by MoNTE48** [comment]
https://forum.minetest.net/viewtopic.php?f=42&t=9389&start=125

**Comment by nanepiwo** [comment]
Oh, thanks.

**Comment by numberZero** [comment]
Currently, similar thing happens on (Linux) desktop: https://github.com/sapier/mobf_core/issues/21
It is only noticeable with such tall windows as in mobf, for obvious reason.
