### ISSUE TITLE
getCraftRecipes implementation is very slow

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2210]
The function [getCraftRecipes](https://github.com/minetest/minetest/blob/70074800a20/src/craftdef.cpp#L974) is very slow, and could do better than O(n) by eg. using hashtables. I've created a [minimal test](https://gist.github.com/est31/f4ad8d4403f29ca230e3) using conditions encountered by the dreambuilder game and the unified inventory. This issue causes unified inventory to load ~18 secs at the start of a game. During this time, no client can connect.

**Comment by gregorycu** [comment]
https://github.com/gregorycu/minetest/commit/7ad3f9c4ae9e4ec2679e3a657a7eccbb1ea7dcff
This speeds the function by by several orders of magnitude, something like 50000%. Problem is that is increases the time to register a recipe by 50%.

**Comment by Zeno-** [comment]
50000 percent! Whoa! That's huge! It's 10 times huger than 5000 percent!

**Comment by est31** [comment]
That figure came from me. Calculation bases on numbers [provided by](http://irc.minetest.ru/minetest-dev/2015-01-26#i_4131935) him: 28 000 ms == 500 * 59 ms. and, as we all know, 500 = 50000%.

**Comment by est31** [comment]
Here are real benchmark numbers:
running without patch:
20000 iterations of adding crafts: 365,043 us
2325 iterations of lookup: 20,285,332 us
running with patch:
20000 iterations of adding crafts: 540,101 us
2325 iterations of lookup: 577,979 us

**Comment by gregorycu** [comment]
Awesome. I was somewhat sceptical.

**Comment by gregorycu** [comment]
Anyway, I've been thinking about this some more. While existing API functions should be fast enough to not cause issues, it's possible that the method existing in the first place is a mistake.

In my mind, there should be two additional methods created. get_registered and register_on_register.

Both these functions accept a parameter of "type"  and allow you to inspect any type of thing that can be registered. The first method returns an iterator that will iterate over the entire collection. The second allows you to register a function that will be called when the corresponding register function has been called. This means mood authors can hook into the registration of things (such as recipes, items etc) This means mod authors can be less concerned about mod startup order.

There would have to be benchmarking to ensure such a system doesn't allow everything drastically.

**Comment by est31** [comment]
@gregorycu IDK, there are already [some tables](http://rubenwardy.com/minetest_doc/lua_api.html#global-tables) you can read from. Crafts seems to be missing out of some reason... :( and how would the register_on_register solve the issues with the load order? would the function passed to that function be called for things before that call? --> I guess not.

**Comment by gregorycu** [comment]
Ahh awesome. I thought there were tables somewhere, but couldn't find them in the API. register_on_register in conjunction with the iterator means you do your initial iteration, and then you register a watch. Because the tables exist, I would instead have the watch and the tables. That way mod authors don't feel inclined to periodically loop through the table to ensure they have everything.

**Comment by est31** [comment]
Additional note: T4im has reported the autocrafter stores the crafts inside a hashmap it serializes itself in order not to call `minetest.get_craft_result` repeatedly.... best is to remove the for loop there too.

**Comment by est31** [comment]
New run by SN here: #2460

**Comment by est31** [comment]
Fixed by commit 03e0dd33a847a83d975282c6caf6b926306e7b57 .
