### ISSUE TITLE
Glitch when you grab the first block.

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2215]
Start a new world and when you grab the first block in the hand there is a glitch in the image. The same thing happens if you have nothing in your hand and you grab a block type you don't have previously (you get this new block in hand).

**Comment by nanepiwo** [comment]
Are you referring to the block appearing briefly in the middle of the screen? What build?

**Comment by ngosang** [comment]
Linux, last developer version. It was my fault. I compiled against the last Irrlicht dev version 1.9.0. With the last stable release 1.8.1 it works well.
