### ISSUE TITLE
Android - Unwanted Momentum

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2216]
On android (tested on 0.4.10 build and MoNTE48's 0.4.11 builds) opening a formspec while moving causes problems. The character continues to move, even after all move keys are released. Sometimes, this stops, and sometimes it doesn't. Hitting up against a corner and pressing some keys will make this stop, but sometimes causes a crash.

EDIT: This also occurs on the 0.4.12 official version on Google Play.

**Comment by MoNTE48** [comment]
Confirm. Very bad bug!
~300 my users report this bug.

**Comment by est31** [comment]
I can reproduce this too.

**Comment by Wayward1** [comment]
I just reproduced it as well.

**Comment by Wayward1** [comment]
Why is this still labeled unconfirmed?

**Comment by nanepiwo** [comment]
This also happens if you're holding, say, the noclip toggle key when a formspec pops up. After you close the formspec, the noclip toggle messages will appear on the screen as if the key is held down.

**Comment by sapier** [comment]
fixed by 6a7e1667f6e696f152191d9fdd74947ceefcfd3a
