### ISSUE TITLE
add wait_clicked and texture_waiting to formspec button or image_button

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2220]
My idea is to add two fields/params to formspec, one boolean to button called `wait_clicked` and one image to image_button called `texture_waiting`.

`wait_clicked` should let the button, if it was successfully clicked, remain in a clicked state until the server sends updated formspec information. `texture_waiting` should let the image_button display the specified texture while that time.

Reason for the request: When the user clicks a button that results in a change of the formspec, the button appears as unclicked, and through greater lags it seems to the user that the button hasn't been clicked at all, or the click was forgotten by lag. This is particularly bad for on/off switches, and when the user closes the formspec and reopens it in order to "reload" it.

**Comment by t4im** [comment]
:+1: for allowing useability
