### ISSUE TITLE
minetest.get_craft_recipe returns different table than lua_api claims

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2221]
Just a small error in the api/documentation (but still cost some time debugging the problem down to this)
```
* `minetest.get_craft_recipe(output)`: returns input
    * `input.method` = `"normal"` or `"cooking"` or `"fuel"`
```
is actually returning `input.type`
https://github.com/minetest/minetest/blob/70074800a207974a0c1383275186cefe6955f297/src/script/lua_api/l_craft.cpp#L373

**Comment by gregorycu** [comment]
Best to bring the documentation into line with behaviour?

**Comment by t4im** [comment]
Just saw, that `minetest.get_craft_result` on the other hand operates on "method". So now it's also inconsistent. ;-)

**Comment by paramat** [comment]
#4387 merged.
