### ISSUE TITLE
Minetest main menu uses a lot of CPU

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2226]
Just start Minetest, doing nothing, consumes 14% of my CPU. I guess that's generating clouds background but it's too much.

**Comment by C1ffisme** [comment]
Yeah, I can get temparatures of about 60 celsius on my Latitude D620 laptop.

**Comment by ngosang** [comment]
I'm just saying that the game is doing nothing. I guess it can be improved in some way.

**Comment by Calinou** [comment]
Try: `menu_clouds = false` in your minetest.conf.

**Comment by ngosang** [comment]
5%. It is acceptable.

**Comment by SmallJoker** [comment]
`menu_clouds = false` results in a CPU usage of 6 - 9%. I think there's a loop which repeats too frequently.

**Comment by gregorycu** [comment]
I'll take a look at this sometime this week.

**Comment by ShadowNinja** [comment]
A static menu should consume negligible CPU.

**Comment by gregorycu** [comment]
Except it is not that static. I'll check it out in any case. First
impressions matter. A menu that causes a laptops fan to speed up looks bad.

**Comment by gregorycu** [comment]
I've taken a look at the code. It looks very simple.

The main menu FPS cap is set by the fps_limit minetest.conf setting.

In a perfect world, minetest should probably use the pause menu fps to render (setting should be renamed menu fps).

To test this, with the main menu open:

Settings > Advanced
Client > Graphics > In Game > Advanced
Drop the max FPS down to 20 or even 60.
CPU usage should drop dramatically.

Please let us know. Depending on the performance of your rig, setting the maximum fps to 80 or so may be a good temp fix.

**Comment by Zeno-** [comment]
46da0e8
