### ISSUE TITLE
Game doesn't always disregard image filename extensions in the context of a mod's code

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#223]
In a mod, when you specify an image to be used as a texture, according to the API you should be able to supply simply the base filename, or a filename with any image extension regardless of the actual file's contents.  For example, consider the following code:

``` lua
minetest.register_node("tv:screen_7", {
   description = "TV",
   tile_images = {"tv_screen_7.png"},
   is_ground_content = true,
   groups = {snappy=1,bendy=2,cracky=1,melty=2,level=2},
   drop = 'tv:screen_1',
   light_source = 8,
})
```

Deprecated use of tile_images aside, the referenced file, "tv_screen_7.png" is actually stored on disk as a JPEG image, with the wrong file extension.  

https://raw.github.com/Jordach/Minetest-Mods./master/tv/textures/tv_screen_7.png

According to the API, this should still work, but it doesn't.  If the mod references the image with the wrong extension, or with no extension at all, the game does not load the image and warns the user of this.

If given the exact on-disk name of the image, and the image is properly named according to its content, the above code will load it just fine.  That is, if I rename the image on disk to "tv_screen_7.jpg" and change the above code to match, it works fine.

While talking about this in IRC:

[08-23 12:36] [celeron55] i found the problem, and it is kind of odd
[08-23 12:36] [celeron55] the checking of different file extensions is done at the filesystem level, not at cache level (in which the stuff from the server ends up)

**Comment by nerzhul** [comment]
@VanessaE please confirm

**Comment by VanessaE** [comment]
This is still an issue (at commit cd684497c28a93e1bca4fbe889eef2d6d5c59289).  Tested by modifying a mod to call for its textures just by their base filenames (no extensions).

**Comment by Megaf** [comment]
Still present.

**Comment by rubenwardy** [comment]
Not sure how needed this is. With no file extension specified, then determining the file extension is good. However, not working with the wrong file extension is correct imo. Documentation change?

**Comment by rubenwardy** [comment]
can't reproduce

    2017-08-26 02:35:03: ERROR[Main]: generateImage(): Could not load image "default_dirt.jpg" while building texture; Creating a dummy image
