### ISSUE TITLE
Add Custom Field (eg: notes) to Main Menu's Client Tab - Feature Request

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#2230]
I keep a backup copy of my favoriteserver.txt because it contains better descriptions of the servers I frequent than the servers themselves provide. However, when I login to those servers my custom description is overwritten. In most cases my description is deleted leaving no description at all.

While server-ops should do a better job of filling in this info for their servers, having the ability to write your own description, that is saved client-side, would be helpful.

The descriptions I use are either a name for those servers that only appear as IP addresses or URLs, or short comments about the server that sets it apart from the others.

**Comment by rubenwardy** [comment]
this is quite an overkill feature that most players won't use IMO.

**Comment by paramat** [comment]
:-1: Yes, and no support or interest.
