### ISSUE TITLE
Map Seed Default is Now Zero

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#2233]
Mintest commit used: 4d15d63134

I started a few new worlds and each time the map seed was 0.

I checked my minetest.conf and the "fixed_seed" was commented out.

Then I tried again, this time making sure the map seed field was blank when creating another new world. Still the seed was 0.

I tried again, this time entering a random number into the map seed field. When I started that new world, the seed was still 0 - the number I had entered was ignored.

Then I tried entering a random number in minetest.conf, i.e. "fixed_seed = 122333444455555". That worked. However, when I cleared the map seed field in the menu to start another test world, the random seed Minetest came up with was back to 0.

**Comment by ngosang** [comment]
Bug introduced in this commit ad690c46b10423b23d515bda0e89228b51f5b5e9.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/48fa893abdaa7d7f29f7e909b326146b2f0606b9
