### ISSUE TITLE
add an option to check for global declaration/variable nilness without triggering a warning

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2236]
The warning added for getting or setting global variables is a great addition.
Yet it often triggers false positives as we've seen in the case of intllib or technic.

In case of intllib people even started seeing this wrongly as a mod-bug. (minetest-technic/unified_inventory#19)
Mods generally started to migrate to a version that tests for mod existance instead of functionality existance just to avoid a warning on the console. This yields higher coupling and less functional guarantees by depending on the mod instead of the function.
(kaeza/minetest-intllib@c4335aa3)
This isn't the only case, but probably the most common one.

Testing a undeclared variable for nilness is a valid and so far i know the only way in lua to test the declaration state of that variable.

Since it might be too hard differentiating the different cases in the metatable, (and i can't think of a clean way to suppress the warning in certain cases) i suggest a bypassing `minetest.` function to test for declaration. This allows intentional checking and still avoids accidental global variable access.
e.g.
```lua
minetest.is_declared("variablename")
```
This would also allow sufficently to test if a mod adds a certain functionality (e.g. due to missing it in later versions) giving as mentioned better functional guarantees than testing for a mod to be present.

**Comment by SmallJoker** [comment]
A pull already exists: #1862

**Comment by t4im** [comment]
Thanks! Closing this as duplicate of #1862 then.
