### ISSUE TITLE
InvRefs set_width is not being used by set_list to add lists of different width

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2238]
Originally thought as an issue of #2222 as well, it turns out that `InvRef`s `set_width` seems to not be respected by its `set_stack` nor `set_list`

**Comment by kahrl** [comment]
Can you clarify? In what way should the width be respected?

**Comment by t4im** [comment]
Documentation implied that the width was used for crafting.
Having a 9 sized Inventory changed in width will not change the way the e.g. Steel door recipe (a list of 9 in which the first 6 stacks are steel ingots) is sorted into it.

But i admit that this is probably making too many assumptions, as both widths would be required to properly act on it, and fixing one onto a crafting grid width is certainly not a clean solution.

Maybe this rather requires an additional set_list parameter that has the input width passed as well?
