### ISSUE TITLE
Opus file format for sounds

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2239]
I have seen many comparisons and seems to have better performance than Vorbis, especially for short and low bitrate sounds, used in games.
It is fully opensource, stable and is developed by international organizations. There are several projects like Mozilla Firefox that include full support.
I've seen games like openage who use it.

https://en.wikipedia.org/wiki/Opus_%28audio_format%29
http://www.opus-codec.org/comparison/

**Comment by Calinou** [comment]
We could also support FLAC and WAV.

**Comment by rubenwardy** [comment]
this is an upstream issue, we don't tend to add media format support ourselves

**Comment by BobOmbuzal** [comment]
Is opus supported now in the upstream?

**Comment by Desour** [comment]
Idk why this would be an upstream issue. We're using libvorbisfile directly to load ogg vorbis. Implementing support for other file formats would be possible.

**Comment by farooqkz** [comment]
I have doubts if adding opus support brings enough benefits to justify adding it. I can't think of any use case in which is impossible without opus, or opus brings significant advantage. One advantage opus has got is support of very low bitrates, and thus much smaller media size. But we already have got ogg, and opus codec can be used in it.

**Comment by Calinou** [comment]
> But we already have got ogg, and opus codec can be used in it.

Luanti only supports the Ogg container with Vorbis audio, not Opus audio. `.opus` is just a renamed `.ogg` file AFAIK.

**Comment by farooqkz** [comment]
> > But we already have got ogg, and opus codec can be used in it.
> 
> Luanti only supports the Ogg container with Vorbis audio, not Opus audio. `.opus` is just a renamed `.ogg` file AFAIK.

In that case, not I only agree that opus should be added, I also think it might be better to not have a low priority.
