### ISSUE TITLE
Why does flying fairly fast with noclip and then suddenly disabling fly cause a freezed minetest for a few seconds?

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#2247]
If I fly with noclip very fast and then suddenly disable fly, I need to wait a few seconds until l can move again. Maybe this waiting isn't necessary.

**Comment by HeroOfTheWinds** [comment]
It may have to do with needing to load the chunk you just entered.  I've encountered this problem while testing voxel manipulator mods.

**Comment by Zeno-** [comment]
Mid-air refuelling is another possibility

**Comment by ShadowNinja** [comment]
@HybridDog Ignore is a solid node.  Noclip lets you pass through it, but disabling noclip or fly will make it solid again.

**Comment by HybridDog** [comment]
>Ignore is a solid node. Noclip lets you pass through it, but disabling noclip or fly will make it solid again.

l know, it's solid. Unloaded chunks consist of it, don't they?

**Comment by ShadowNinja** [comment]
@HybridDog Correct.  Are you flying into unloaded blocks before disabling fly?  That seems to be your issue.  You can confirm it by flying with noclip disabled and seeing if you bump into blocks.  If so, this isn't a bug, it's intended behavior.  Minetest can't know if the block is full of solid nodes or non-solid nodes until it's loaded, so it makes a safe guess.

**Comment by HybridDog** [comment]
>Are you flying into unloaded blocks before disabling fly?

of course, yes, l greatly increased the default fast speed

Ok, l just tested it again and the problem seems to be solved already.
https://github.com/minetest/minetest/commits/master/src/localplayer.cpp
Maybe l used an outdated version, sorry.
