### ISSUE TITLE
Use negative values in damage_per_second for healing

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2248]
A node definition can contain the field “damage_per_second”. If specified, the node will damage any player in this node by this number. However, this number can only be non-negative.
If I specify a negative value, I just instantly die. I guess this is because of a “wrap-around” and I get the maximum possible damage.

This is rather useless, since already a value of 20 is a quick kill, so the highest values will probably not be used.

Therefore, I suggest to actually allow negative numbers and use them for healing. So a value of -5 means you get healed by 5 HP per second. It also makes more sense, a damage of -5 equals a healing of +5. In practice, I don’t think this change would break any existing mods, because using a value larger than 20 is already overkill.

This feature request has been taken from:
https://forum.minetest.net/viewtopic.php?f=5&t=10285

**Comment by MT-Modder** [comment]
:+1:  I love this idea!

**Comment by C1ffisme** [comment]
:+1: Yes!!!!

**Comment by HeroOfTheWinds** [comment]
:+1:  This would be so much more optimum than the ABMs I've had to use before...

**Comment by JakubVanek** [comment]
I can try to implement that. What about body parts? I mean should we prefer healing, damage or the one with highest maximum absolute value? What if maximum absolute values are equal?

**Comment by ShadowNinja** [comment]
@JakubVanek I think that HP changes from all nodes that you're touching should be applied.  The order won't matter since death/overflow will only be handled after all effects have been considered.

**Comment by nerzhul** [comment]
I think we must continue the topic in PR #2261
If you agree please close.

Thanks !

**Comment by Wuzzy2** [comment]
Sorry, but this feature is not actually implemented as of 0.4.14. Reopening.

**Comment by JakubVanek** [comment]
That's because the dev-0.5 branch is gone. I don't know why.

**Comment by Wuzzy2** [comment]
Then can you (or someone else) just try to do another PR?
The relevant commit is still visible on GitHub:

https://github.com/minetest/minetest/pull/2261/commits/252bd7e95ced99912c9470128ab840cacdcaa873

**Comment by paramat** [comment]
Closing until confirmation that it doesn't work.
