### ISSUE TITLE
Formspec element for read-only multiline text

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2249]
I make a feature request for a new formspec element for read-only text which has multiple lines. It similar to a label, only with multiple lines.

The properties I wish are:
- Read only
- Looks like a label, only with multiple lines
- Lua scripter specifies position, size and text of the textbox. Line breaks happen automatically at the end of the textbox, like for textareas.
- Optional: A scrollbar for the whole textarea if the text is too long (like for textlists).
- I don’t care about background. That could be added with the box element anyways, so I don’t see a need for it.

Source: https://forum.minetest.net/viewtopic.php?f=5&t=10198

**Comment by MT-Modder** [comment]
:+1:

**Comment by rubenwardy** [comment]
:+1:

**Comment by C1ffisme** [comment]
:+1:

**Comment by paramat** [comment]
See https://forum.minetest.net/viewtopic.php?p=171738&sid=53883d02b5a60d600ffeca4f2897fada#p171738
Is partially possible but missing a scroll bar.
The idea has a lot of support.

**Comment by adrido** [comment]
A readonly textarea is possible now. 
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1921-L1924
Just create the textarea as normal, but do not specify a name and a label.

**Comment by SmallJoker** [comment]
Solved. The implementation isn't the best but has already been used for the server description in the online tab.
