### ISSUE TITLE
Add model pitch and roll and add API

### ISSUE THREAD

**Issue by Kalabasa** [minetest/minetest#2251]
##### Issue type
 - Feature request

##### Add `setpitch(radians)` and `setroll(radians)` and the corresponding getters.

We already have `get/setyaw(radians)` to rotate the model visually. Why not `get/setpitch(radians)` and `get/setroll(radians)` too? This gives us complete control on model rotation.

One use case is for spiders that crawl walls and ceilings. The can rotate upside-down or sideways so that they look like they're actually crawling on walls and ceilings.

Another simpler use case is flying entities (arrows rotating in line with their trajectory, bats flying around).

(Wow. It's been 3 years. Updated description to be more accurate.)

**Comment by SmallJoker** [comment]
We already have a function to set the pitch:
```c++
int ObjectRef::l_set_look_pitch(lua_State *L)
```
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_object.cpp#L759

But that doesn't work with Lua entities, there's no pitch.
https://github.com/minetest/minetest/blob/master/src/content_sao.cpp#L374
https://github.com/minetest/minetest/blob/master/src/player.cpp#L51

**Comment by Kalabasa** [comment]
That's look pitch

**Comment by SmallJoker** [comment]
Because model rotation pitch has not been added yet.

**Comment by Kalabasa** [comment]
Oh, that's what I meant. I'm changing the title...

**Comment by raymoo** [comment]
Automatic pitch movement like we have with yaw would also be nice to have as an option.

**Comment by Kalabasa** [comment]
That would be excellent for flying units, although the trigonometry involved might get complicated.

**Comment by Nyarg** [comment]
Half issue is using set_bone_position() - model need have bone of course.
'half' because attached childs isn't inherit root rotation.

**Comment by paramat** [comment]
Related to #1800

**Comment by Wuzzy2** [comment]
:+1: I also want this. It's an obvious missing feature of entities.

Yaw, pitch and roll should be all settable for entities. It's annoying that you can only rotate entities around one axis, this is too limiting.

Some use cases:

* Arrows which can pitch up and down while flying (current arrows look hilarious when you shoot up as their pitch never changes)
* Other ballistic projectiles
* Rotatable items in item frames
* Entity-based item frames on floor and ceiling
* Probably many more

**Comment by paramat** [comment]
See experiments in #7323

**Comment by DS-Minetest** [comment]
To be closed?

**Comment by paramat** [comment]
#7395 merged.
