### ISSUE TITLE
Framerate cut in half, HUD problem ?

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#2252]
For some reason the latest 0.4.11 daily builds have cut my frames per second in half...  Where 0.4.11 was running at a smooth 30fps and over, Build 3404 for linux/ubuntu is running 15fps and is jittery...

By pressing F1 to turn off the HUD, framerate jumps back up to 40fps so something is up with that it seems...

**Comment by Zeno-** [comment]
Do you experience this on all servers (and also single player games)?

**Comment by Zeno-** [comment]
Do you know which commit caused the problem (in other words, where the problem began)?

I cannot reproduce. There is a difference of about 5% for the render loop with HUD enabled/disabled but as far as I can tell that was probably always there (you'd have to expect **some** difference with HUD enabled/disabled; 5% is perhaps too much but it's not 50%). I'm not saying it doesn't happen for you but if you can nail it down to a single commit that causes the issue it would go a long way towards fixing it.

**Comment by tenplus1** [comment]
Unfortunately I can only guess at 5 builds ago previous to the current...  I try to download the latest as they appear and test new changes and the last few were very slow and glitchy until HUD disabled...

**Comment by Zeno-** [comment]
Ok, running under valgrind there appears there may be up to ~4x increase in dtime with HUD enabled

**Comment by Zeno-** [comment]
Thanks @tenplus1 

commit 9a0dd47057cad18522e43d159a06c856dfdeeef4
