### ISSUE TITLE
Unattended project

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2253]
I wonder if there is any reason why the project is unattended. There are 391 issues and 110 PR open. Many people is working on fixing problems and these changes are not included in the game (without reasons for not including them).
If it is a temporary thing I understand, but given the number of PR think should be added new collaboratos to not stop the advance of development.
@nerzhul, @gregorycu and @paramat looks like active collaborators and their PRs are really good.

**Comment by nerzhul** [comment]
There are few active developper which test the changes and some changes are very big. At this time it's feature freeze it's why PR are not merged. But FF is very slow.

**Comment by gregorycu** [comment]
It's difficult with lots of PRs, especially during a change freeze. We probably need a few more collaborators (not putting my hand up).

The good news is that PRs are not lost, unless they are closed, so the work can sit there for a while. The concern is that if it sits there long enough, rebasing may be required.

**Comment by ngosang** [comment]
@nerzhul Most PR are to fix bugs present in the current version.
I've played this game for a long time. A few days ago I decided to fix a problem that was bothering me and I share with the community. But without receiving feedback from developers, I do not know if my work will count for something and discourages me to continue working.

**Comment by nerzhul** [comment]
@ngosang i talked with celeron55.
Please look at https://forum.minetest.net/viewtopic.php?f=3&t=11172 and comment it if you have other ideas.

**Comment by ngosang** [comment]
Thanks for all @nerzhul. I do not want to get too involved in the project but I would like to see progress.

**Comment by nerzhul** [comment]
@ngosang i'm nos a core developper and i will work with community to reduce problems ans improve the API/stability. 
A branch has been created to continue devel whereas feature freeze is here. 

If you are satisfied please close your issue

**Comment by ngosang** [comment]
Satisfied.
