### ISSUE TITLE
Dying in water (not drowning!) does not reset player's breath value

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2254]
If you die inside water or anything where you can drown in, and the death is *not* caused by drowning and you still had some breath left, Minetest behaves weirdly:
You will respawn with the same amount of breath you had after you died.

How to reproduce:
* Install the mod “luacmd”
* Start a minetest_game world with damage and luacmd enabled
* Give yourself the “lua” privilege
* Make sure you are not diving right now and have full breath
* Confirm this by typing “/lua print(me:get_breath())” into console. It should return 11.
* Dive into water
* Before you drown, type “/lua me:set_hp(0)” into the console. This should kill you.
* Respawn
* If you spawn over water, quickly hold the space bar and make sure you do not dive. Go to land.
* Look closely on the breath bar
* Also examine your breath value again with “/lua print(me:get_breath())”. It should be the same number of bubbles as the breath bar shows

You will notice the breath will be the same after you have died in water. It will stay at this number until you dive again. So the breath value is wrong after respawn and it also will not gradually grow.

Suggested fix: As soon as the player respawns, reset the breath to 11.

This bug has been tested under: Minetest 0.4.11, subgame minetest_game 0.4.11, operating system GNU/Linux.

**Comment by falsechicken** [comment]
Just tested it. I can confirm this does happen.

**Comment by Wuzzy2** [comment]
I have made a little bit more research into this. It looks like the error also occours when you die by drowning. When you respawn, breath is set to 0 (instead of 11).

**Comment by Zeno-** [comment]
commit 929e0b0
