### ISSUE TITLE
Subgame banner is hidden for 16:9 resolutions

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2262]
The subgame banner (big text logo) is scaled depending on the window/screen width. However, if the window or screen is very wide but not very high (a 16:9 screen is totally sufficient), the logo could take up too much space and so it is just hidden.

This is not good that the subgame logo simply disappears, there should be a better way to fix the scaling of the logo.

This bug report is valid for 0.4.11.
To test this, just select any subgame with a large banner in the main menu and scale the window until the banner disappears.

Screenshot example:
Here the subgame “Weird” is selected:
https://i.imgur.com/ougda1F.png

Now if I just reduce the window height a little bit, the logo does not fit in anymore and disappears:
https://i.imgur.com/aYzFaje.png

**Comment by SmallJoker** [comment]
This bug also exists in newest 0.4.11-dev.

**Comment by paramat** [comment]
@Wuzzy2 still occuring? There have been changes.

**Comment by Wuzzy2** [comment]
Yes. f9a90383e14a02ab0e66e5d5c36940a4ffb54502

**Comment by paramat** [comment]
The header image scaling is weird and really needs work. Sometimes it becomes huge and sometimes it overlaps the tabs or formspec.

**Comment by appgurueu** [comment]
Not appearing on 5.2 anymore

**Comment by Wuzzy2** [comment]
Wrong. There has been no effort at all to fix this, and this bug didn't just magically fix itself.

I have >20 games installed, and clicking through the games, the majority of headers still very visibly overlaps with the main menu.

But there have been plans for a complete main menu redesign anyway, it's best to fix the bug as part of the redesign.

**Comment by sfan5** [comment]
> the majority of headers still very visibly overlaps with the main menu.

But this is not what the bug reports. The bug report is about headers <b>not</b> appearing.

**Comment by Wuzzy2** [comment]
Oh, lol, that other thing ... Yeah, the disappearing happens, too, if you scale the window in a weird fashion …

As a guess, I'd say both problems are related. Anyway, this is just another reason for the main menu rework.

**Comment by rubenwardy** [comment]
This isn't orthogonal to the main menu rework, both would need to happen and the rework doesn't make this any easier to fix

**Comment by paramat** [comment]
> the disappearing happens, too, if you scale the window in a weird fashion

Can you be more specific? If the header image only disappeared for completely insane game window aspect ratios then this is not much of an issue.

**Comment by Wuzzy2** [comment]
Well, it very much depends on the header size as well, I can't make an overly generic statement here …

Just try it out yourselves. Sometimes it happens for 16:9, sometimes not. It's more likely to happen if the header image is tall and has a low width.

**Comment by sfan5** [comment]
The header only disappears at about 31:9 aspect ratio here so I consider this solved.
