### ISSUE TITLE
add warning log level

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#2263]
Currently the `warning` log level is absent from `minetest.log()`.
This lead among other things to [`strict.lua` using `print(...)` as a fallback](https://github.com/minetest/minetest/blob/b56f1175a2d3661459143e7c4104c43bf5a9caa5/builtin/common/strict.lua#L8).

There is a certain irony in especially `strict.lua` using it, given that lua itself mentions in its manual:
> print is not intended for formatted output, but only as a quick way to show a value, typically for debugging.

Minetest respects this by redirecting `print(…)` onto `minetest.debug()`.
`strict.lua` does not.

Adding a warning log level would be a cleaner solution, as well as allow the rest of us to avoid printing out errors, when we just wanted to warn about something.

**Comment by nerzhul** [comment]
At this time there isn't a warning log level into core, there is debug, info and error.

**Comment by t4im** [comment]
fixed by #2628
