### ISSUE TITLE
Settings(path):remove(key) always returns true

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#2264]
IRC comments : http://irc.minetest.net/minetest-dev/2015-02-06#i_4144929

**Comment by t4im** [comment]
Added a unit test: https://github.com/t4im/mtt/blob/master/api_test/data_handling.lua
It fails to persist the key, not to remove it. It's actually `write()` that returns `true` when it should not.

**Comment by SmallJoker** [comment]
Fixed since b67eab3

**Comment by t4im** [comment]
The unit test continues to fail, although not at the return value, but the persistence of it.
Is is possible the change just hid the symptom?

#### Settings:remove(key)
###### … it really persists written changes (minetest/minetest#2264)
 1. **Given** a settings file with an example entry
 2. **When** successfully written
 3. **Then** really persist the change
 4. **Given** a removal of the key
 5. **When** successfully written
 6. ~~**Then** really delete the entry from the file~~  
    Fail with:
    > /home/t4im/.minetest/mods/coretest/data_handling.lua:76: Expected objects to be the same.
    > Passed in:
    > (string) 'testvalue'
    > Expected:
    > type nil
