### ISSUE TITLE
string.cpp error on android build make

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2269]
```
minetest <= database-leveldb.cpp                          
jni/../jni/src/util/string.cpp: In function 'int mbtowc(wchar_t*, const char*, size_t
)':                                                                                  
jni/../jni/src/util/string.cpp:65:42: error: cannot convert 'std::wstring {aka std::b
asic_string<wchar_t>}' to 'wchar_t*' in initialization                               
  wchar_t *intermediate = narrow_to_wide(s);                                         
                                          ^                                          
jni/../jni/src/util/string.cpp:67:19: error: request for member 'length' in 'intermed
iate', which is of non-class type 'wchar_t*'                                         
  if (intermediate.length() > 0) {                                                   
                   ^                                                                 
jni/../jni/src/util/string.cpp: In function 'const wchar_t* narrow_to_wide_c(const ch
ar*)':                                                                               
jni/../jni/src/util/string.cpp:78:35: error: invalid conversion from 'wchar_t*' to 'w
char_t' [-fpermissive]                                                               
  wchar_t wcs = new wchar_t[mbl + 1];                                                
                                   ^                                                 
jni/../jni/src/util/string.cpp:83:9: error: invalid types 'wchar_t[size_t {aka unsign
ed int}]' for array subscript                                                        
    wcs[i] = wide_chars[(unsigned char) mbs[i] - 32];                                
         ^                                                                           
jni/../jni/src/util/string.cpp:87:9: error: invalid types 'wchar_t[size_t {aka unsign
ed int}]' for array subscript                                                        
    wcs[i] = L'\n';                                                                  
         ^                                                                           
jni/../jni/src/util/string.cpp:91:9: error: invalid conversion from 'wchar_t' to 'con
st wchar_t*' [-fpermissive]                                                          
  return wcs;                                                                        
         ^                                                                           
make[2]: *** [obj/local/armeabi/objs/minetest/jni/src/util/string.o] Error 1         
make[2]: *** Waiting for unfinished jobs....                                         
make[2]: Leaving directory `/root/minetest/build/android'                            
make[1]: *** [apk] Error 2                                                           
make[1]: Leaving directory `/root/minetest/build/android'                            
make: *** [release] Error 2                                
```

**Comment by ShadowNinja** [comment]
Does [this patch](http://sprunge.us/MGej) fix it?

**Comment by MoNTE48** [comment]
@ShadowNinja, I will be able to check it in a few days, sorry.
Could you check it?

**Comment by ShadowNinja** [comment]
@MoNTE48 Not without seting up an Androoid build environment, and tgat's not trivial.  :-|

**Comment by MoNTE48** [comment]
I didn't understand your last message :-(

**Comment by Zeno-** [comment]
@MoNTE48 it kind of means that unless someone tests it, perhaps you, it won't be fixed quickly

**Comment by MoNTE48** [comment]
Patch worked, but have the following problem:

[armeabi-v7a-hard] SharedLibrary  : libminetest.so
/root/ndk/sources/cxx-stl/gnu-libstdc++/4.8/include/bits/basic_ios.h:152: error: undefined reference to 'toClientCommandTable'
jni/../jni/src/client.cpp:1177: error: undefined reference to 'NetworkPacket::getString(unsigned int)'
jni/../jni/src/client.cpp:1199: error: undefined reference to 'NetworkPacket::operator>>(unsigned short&)'
jni/../jni/src/client.cpp:1205: error: undefined reference to 'NetworkPacket::operator>>(float&)'
jni/../jni/src/client.cpp:1249: error: undefined reference to 'NetworkPacket::operator>>(unsigned short&)'
jni/../jni/src/client.cpp:1253: error: undefined reference to 'NetworkPacket::operator>>(unsigned short&)'
jni/../jni/src/client.cpp:1281: error: undefined reference to 'NetworkPacket::operator>>(unsigned short&)'
jni/../jni/src/client.cpp:1292: error: undefined reference to 'NetworkPacket::operator>>(unsigned char&)'
jni/../jni/src/client.cpp:1293: error: undefined reference to 'NetworkPacket::readLongString()'
jni/../jni/src/client.cpp:1310: error: undefined reference to 'NetworkPacket::getString(unsigned int)'
jni/../jni/src/client.cpp:1340: error: undefined reference to 'NetworkPacket::operator>>(float&)'
jni/../jni/src/client.cpp:1340: error: undefined reference to 'NetworkPacket::operator>>(float&)'
jni/../jni/src/client.cpp:1340: error: undefined reference to 'NetworkPacket::operator>>(float&)'
jni/../jni/src/client.cpp:1366: error: undefined reference to 'NetworkPacket::operator>>(unsigned char&)'
jni/../jni/src/client.cpp:1399: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<float>&)'
jni/../jni/src/client.cpp:1436: error: undefined reference to 'NetworkPacket::operator>>(bool&)'
jni/../jni/src/client.cpp:1437: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<float>&)'
jni/../jni/src/client.cpp:1520: error: undefined reference to 'NetworkPacket::operator>>(unsigned int&)'
jni/../jni/src/client.cpp:1549: error: undefined reference to 'NetworkPacket::operator>>(std::string&)'
jni/../jni/src/client.cpp:1551: error: undefined reference to 'NetworkPacket::readLongString()'
jni/../jni/src/client.cpp:1573: error: undefined reference to 'NetworkPacket::getString(unsigned int)'
jni/../jni/src/client.cpp:1600: error: undefined reference to 'NetworkPacket::getString(unsigned int)'
jni/../jni/src/client.cpp:1658: error: undefined reference to 'NetworkPacket::operator>>(int&)'
jni/../jni/src/client.cpp:1694: error: undefined reference to 'NetworkPacket::readLongString()'
jni/../jni/src/client.cpp:1719: error: undefined reference to 'NetworkPacket::readLongString()'
jni/../jni/src/client.cpp:1722: error: undefined reference to 'NetworkPacket::operator>>(std::string&)'
jni/../jni/src/client.cpp:1781: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<float>&)'
jni/../jni/src/client.cpp:1781: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<float>&)'
jni/../jni/src/client.cpp:1783: error: undefined reference to 'NetworkPacket::operator>>(bool&)'
jni/../jni/src/client.cpp:1787: error: undefined reference to 'NetworkPacket::operator>>(unsigned int&)'
jni/../jni/src/client.cpp:1791: error: undefined reference to 'NetworkPacket::operator>>(bool&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(unsigned int&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(unsigned char&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<float>&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(std::string&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<float>&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(std::string&)'
jni/../jni/src/client.cpp:1848: error: undefined reference to 'NetworkPacket::operator>>(unsigned int&)'
jni/../jni/src/client.cpp:1849: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<float>&)'
jni/../jni/src/client.cpp:1849: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<float>&)'
jni/../jni/src/client.cpp:1856: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<int>&)'
jni/../jni/src/client.cpp:1899: error: undefined reference to 'NetworkPacket::operator>>(unsigned char&)'
jni/../jni/src/client.cpp:1909: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<int>&)'
jni/../jni/src/client.cpp:1986: error: undefined reference to 'NetworkPacket::operator>>(bool&)'
jni/../jni/src/client.cpp:2002: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<int>&)'
jni/../jni/src/client.cpp:2003: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector2d<int>&)'
jni/../jni/src/client.cpp:1045: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<short>&)'
jni/../jni/src/client.cpp:1057: error: undefined reference to 'NetworkPacket::operator>>(unsigned long long&)'
jni/../jni/src/client.cpp:2036: error: undefined reference to 'ToClientPacket::ToClientPacket(unsigned char*, unsigned int, unsigned short)'
jni/../jni/src/network/toclientpacket.h:28: error: undefined reference to 'NetworkPacket::~NetworkPacket()'
jni/../jni/src/network/toclientpacket.h:28: error: undefined reference to 'NetworkPacket::~NetworkPacket()'
jni/../jni/src/client.cpp:2036: error: undefined reference to 'toClientCommandTable'
jni/../jni/src/client.cpp:1622: error: undefined reference to 'NetworkPacket::operator>>(int&)'
jni/../jni/src/client.cpp:1129: error: undefined reference to 'NetworkPacket::operator>>(short&)'
jni/../jni/src/client.cpp:1130: error: undefined reference to 'NetworkPacket::operator>>(short&)'
jni/../jni/src/client.cpp:1131: error: undefined reference to 'NetworkPacket::operator>>(short&)'
jni/../jni/src/client.cpp:1095: error: undefined reference to 'NetworkPacket::operator>>(short&)'
jni/../jni/src/client.cpp:1112: error: undefined reference to 'NetworkPacket::getU8Ptr(unsigned int)'
jni/../jni/src/client.cpp:1116: error: undefined reference to 'NetworkPacket::getU8(unsigned int)'
jni/../jni/src/client.cpp:1085: error: undefined reference to 'NetworkPacket::operator>>(std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&)'
/root/ndk/sources/cxx-stl/gnu-libstdc++/4.8/include/ostream:113: error: undefined reference to 'toServerCommandTable'
jni/../jni/src/server.cpp:1774: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<int>&)'
jni/../jni/src/server.cpp:1775: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<int>&)'
jni/../jni/src/server.cpp:1776: error: undefined reference to 'NetworkPacket::operator>>(int&)'
jni/../jni/src/server.cpp:1777: error: undefined reference to 'NetworkPacket::operator>>(int&)'
jni/../jni/src/server.cpp:1760: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<short>&)'
jni/../jni/src/server.cpp:1854: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<short>&)'
jni/../jni/src/server.cpp:2190: error: undefined reference to 'NetworkPacket::getChar(unsigned int)'
jni/../jni/src/server.cpp:2197: error: undefined reference to 'NetworkPacket::getChar(unsigned int)'
jni/../jni/src/server.cpp:1440: error: undefined reference to 'NetworkPacket::getChar(unsigned int)'
jni/../jni/src/server.cpp:1441: error: undefined reference to 'NetworkPacket::getChar(unsigned int)'
jni/../jni/src/server.cpp:1367: error: undefined reference to 'NetworkPacket::getU16(unsigned int)'
jni/../jni/src/server.cpp:1373: error: undefined reference to 'NetworkPacket::getU16(unsigned int)'
jni/../jni/src/server.cpp:1730: error: undefined reference to 'NetworkPacket::getU8(unsigned int)'
jni/../jni/src/server.cpp:2825: error: undefined reference to 'ToServerPacket::ToServerPacket(unsigned char*, unsigned int, unsigned short)'
jni/../jni/src/network/toserverpacket.h:28: error: undefined reference to 'NetworkPacket::~NetworkPacket()'
jni/../jni/src/server.cpp:2874: error: undefined reference to 'toServerCommandTable'
jni/../jni/src/server.cpp:2700: error: undefined reference to 'NetworkPacket::operator>>(irr::core::vector3d<short>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [obj/local/armeabi-v7a-hard/libminetest.so] Error 1
make[2]: Leaving directory `/root/minetest/build/android'
make[1]: *** [apk] Error 2
make[1]: Leaving directory `/root/minetest/build/android'
make: *** [release] Error 2
root@dedi-fr-30594:~/minetest/build/android#

Note. Never assemble a dedicated server on the i3 in 16 streams (-j16). We had to ask for hand reboot.

**Comment by ShadowNinja** [comment]
@nerzhul Looks like you didn't add the new sources to the Android Makefile.

**Comment by ShadowNinja** [comment]
98b37e3e0d4d0bcea4d0a202f8519a39163b7493

I guess I'll leave this open until tge networking issue is fixed.

**Comment by nerzhul** [comment]
You are right. I fix this soon (~1 hour).

**Comment by nerzhul** [comment]
Commit https://github.com/minetest/minetest/commit/10b208f5c16d3d608fd029372422dd801aaa56ae fix it
