### ISSUE TITLE
Internationalization for mods

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2270]
This is a feature request for a huge (???) but I guess important feature:
Internationalization for mods

The request: Mods should be able to be translated, and this should also work reliable over the networks.

This topic has been discussed before in
https://forum.minetest.net/viewtopic.php?f=5&t=10031
, read this thread for more rationale.

The summary:
- Mods are not translatable, and this sucks
- Since mods are not translatable, a huge part of Minetest is not translatable, including the entire default game, so any claims that Minetest “has been translated” are pretty much bullshit. ;-)
- The existing “translation mods” such as intllib do not solve the problem regarding the network; they simply “force” one language for all clients
- The core idea of how to solve this problem by translating the mods on the server side _and_ serving the translated strings to the clients, but with respect to _each_ client's language, so sending German strings to German clients, etc.
- Translating things like formspecs, server messages, etc. could be tricky

More details in the thread. It has not yet been fully discussed on how to solve this problem exactly, so feel free to discuss it here.

**Comment by rubenwardy** [comment]
This would be good.

@4aiman keeps saying stuff about Russian and tenses which I don't understand - I think it is because males and females should receive different translate strings.

**Comment by nerzhul** [comment]
@Wuzzy2 i look at this for next release, because i'll rewrite on protocol and i think we must tell the server which lang we are using and send sending the proper strings (if nobody else do it before me)

**Comment by nerzhul** [comment]
Before intl we need to fix the character input problem

**Comment by Wuzzy2** [comment]
Right. Is there an issue for that, too?

AFAIK xyz implemented proper UTF-8 support eons ago, and it got recently merged into Freeminer. But not Minetest ago.

**Comment by 4aiman** [comment]
@Wuzzy2 
He did.
However, it turned out that there are issues on android. Those were fixed, but under the GPLv3.

@rubenwardy 
I'm taking not only about Russian. Any Synthetic/Inflective language may become a milestone in terms of translation.
I don't want to give yet another excursion into linguistics, so look at the problem with the following little thing in mind: 

To make an adequate translation, the function that translates any string should be under control of the translator. Even with %playername%, %itemname% and %reason% being available, it's impossible to make an understandable (let alone adequate) translation w/o tackling with the case of the %itemname%, the gender of the %playername% and changing the %reason% so that it would fit.

So far variables with names and properties are invariable...

**Comment by rubenwardy** [comment]
How do other things get around this? Is there like ru_fe and ru_ma ?

**Comment by 4aiman** [comment]
@rubenwardy, well-translated software uses resource files.
However, multiplayer+a_lot_of_items=can't use resources.

I'd suggest to use smth like 
```
    minetest.register_on_translate(args)
```
Then every message may be translated to any language accurately.
Say, **args** is a table with a %playername%, %event_id%, %reason_of_event_id%, %name_of_the_other_player% (or %entity_reference%) and a %language_id%.
Then, with the args filled like this
```
args = {
    ['playername']='4aiman',
    ['event_id']=1,
    ['reason_of_event_id']=2,
    ['name_of_the_other_player']='griever',
    ['language_id']='ru',
}
```
and the knowledge that if event_id==1 then we're dealing with a death of a %playername% 
and that if reason_of_event_id==2then we're dealing with a murder
then...
we would be able to make a good translation to any language with as much freedom as one would want!
This would enable to override trnslations as well! (In case some mod would want to hide some messages or to alter those.)
```
   Just now griever has killed 4aiman!
   4aiman был убит! K этому явно причастен griever!
```
It would be easy to add different details by expanding args table (with a tool-names) within newer versions while maintaining full backward-compatibility.

**Comment by Ferk** [comment]
Why is the translation itself not done client-side?

The server could send to the user the table of strings for its language if he doesn't have them already  and then only send translatable keys. Wouldn't this reduce both processing time in the server and potentially bandwidth as well (provided the user keeps a cache, also gzipping the full stream of text will make its size smaller).

Though I guess the difference in speed wouldn't be very significant.

**Comment by rubenwardy** [comment]
Translation wasn't considered when Minetest was created, therefore it
hasn't been added yet.

Either the client should tell the server what language it wants, or server
should send a whole table like you say. It should also be possible to have
translation packs client side, if a mod isn't translated.

**Comment by xoyteam** [comment]
We on [russian branch](https://forum.minetest.net/viewtopic.php?f=23&t=14423) forum talk about localization.
compilation of all discussions
* translation of items through the tooltip. There are translations c intllib.
* In order to implement a multilingual server, the client must transfer its locale to the server.
* The server must return the rows to the client's locale (store the rows in all locales at once or switch)
* you need bilingualism for terms and subjects (mother tongue and English) and / or chat localization (the name of the subjects when communicating amongst the players, through !Dirt=Грязь or !231 = Грязь)

**Comment by Wuzzy2** [comment]
@xoyteam: Most of what you say has been discussed before.

Please read: https://forum.minetest.net/viewtopic.php?f=5&t=10031

About your suggestions:
* (1): Translation of the item names is just a fraction of what we need. To translate a subgame/mod, you need much more than that, like chat command help, HUD strings, formspec texts, chat messages from the server, and so on. Giving special treatment to item names is the wrong approach
*  (2) and (3): Already discussed to death. See thread and the issue text. Spoiler alert: We came to the same conclusion as you did. xD
*  (4): What are you talking about? Please give a concrete example

**Comment by xoyteam** [comment]
We have a complete translation. International server. I need a pickaxe. I want to ask in the chat: Give me a "кирку", please. (pickaxe). But on the server, past me (Russian locale), a player with a German locale and a Chinese locale...
The rest of the players will not understand my request.
If I have a fully localized client, I can not learn the international name of the subject. If translating back into English may not be unambiguous. (For this, I still need to switch to Google Translate.)
Solution options:
1) Bilingualism in the tooltip.
2) Unique identifiers for items for chat. Example: #Кирка will be displayed in the chat for everyone in his language.

**Comment by Wuzzy2** [comment]
The problem with your logic is that it while this will translate the word “pickaxe”, it will not translate “Give me a <whatever>, please.”, so there is still a language barrier. The receiver will only know that you say *something* about a pickaxe. This is not enough.
Putting two languages into item tooltips sounds interesting, but it should be an option and off by default, especially in singleplayer.

Either feature is off-topic here. Getting mod translation itself finished is a huge task on its own. I think your two suggestions should go in a different issue instead.

**Comment by rubenwardy** [comment]
:tada:

**Comment by Fixer-007** [comment]
Why close? Can you eleborate on how to actually translate mods/games now?

**Comment by rubenwardy** [comment]
Because this feature has been added.

https://forum.minetest.net/viewtopic.php?f=18&t=18349
