### ISSUE TITLE
Android log.cpp warning

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2274]
```
[armeabi-v7a-hard] Compile++ thumb: minetest <= log.cpp
jni/../jni/src/log.cpp:33:40: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
 unsigned int android_log_level_mapping[] {
                                        ^
```

**Comment by Zeno-** [comment]
At the top of log.cpp change lines 32-39 to look like below
(add an '=' after android_log_level_mapping[]) and please let us know if it fixes the issue. Thanks.

```
#ifdef __ANDROID__
unsigned int android_log_level_mapping[] = {
		/* LMT_ERROR */   ANDROID_LOG_ERROR,
		/* LMT_ACTION */  ANDROID_LOG_WARN,
		/* LMT_INFO */    ANDROID_LOG_INFO,
		/* LMT_VERBOSE */ ANDROID_LOG_VERBOSE
	};
#endif
```

**Comment by MoNTE48** [comment]
OK, I test this and send result. Pls, wait.

**Comment by MoNTE48** [comment]
Yes, this work. Wait on next commit :)

**Comment by Zeno-** [comment]
commit 66efaaa983cde27e0ad2f9cc142950a62c868765

**Comment by MoNTE48** [comment]
On 0.4.12 I found this warning now!

**Comment by Zeno-** [comment]
Looks like it was missed when adding patches to the freeze branch. The warning should not cause any issues for you though (just ignore it).

**Comment by MoNTE48** [comment]
I understand, just to inform

**Comment by Zeno-** [comment]
Thank you :)

**Comment by Zeno-** [comment]
Wait... do you mean it happens with the current master (HEAD)?

**Comment by MoNTE48** [comment]
@Zeno- ,yes. Master branch, last commit

**Comment by Zeno-** [comment]
Are you sure it's the same warning?

The change is included in master (at least):
https://github.com/minetest/minetest/blob/master/src/log.cpp#L33

**Comment by MoNTE48** [comment]
Pls, wait 5m. I test this...

**Comment by MoNTE48** [comment]
Yes. I see this bug on 0.4.12 stable

**Comment by Zeno-** [comment]
It must have got missed in the merge to stable-0.4 branch (oops). But it's fixed in master

**Comment by MoNTE48** [comment]
:) no problem. My work - report bug :)
