### ISSUE TITLE
lua_api.txt should have a since field for every function

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2275]
The `lua_api.txt` doesn't contain information on which version (release, etc) introduced a function. This is important however for mod writers, as they need to know which minetest versions their mod supports.
Other APIs docs feature this too ([example](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html#replaceAll%28java.lang.String,%20java.lang.String%29, [another one]%28http://php.net/manual/en/function.is-a.php%29). I'd prefer doing something like the php docs, `(=>0.4.12)` style.
I am volunteering to create some initial documentation for the functions, however somebody would need to review it. Also, I dont think I will go back to the first version, or just start with some earliest version. Please write which version you think is ok in your eyes.
Proposed behaviour for adding a new function is then to set its `since` value to `$LASTSTABLERELEASE-dev`, and before a release, somebody changes the versions to the release version.

**Comment by nerzhul** [comment]
I think we must add this documentation on dev.minetest.net, with a starting version and a depreciated version.
Also, it could be good to have version steps for the call

**Comment by est31** [comment]
If there are no supporting comments for me to do this by 2 core devs by 2015-02-13, I will close this issue due to lacking interest in the change.

**Comment by rubenwardy** [comment]
This would be very useful, but would be a pain in the ass to do. I'm not volunteering. :D

**Comment by rubenwardy** [comment]
0.4.1 was the first version with a mod API. Or 0.4. I forget.

You could just add => 0.4.12 and be lazy.

**Comment by est31** [comment]
I've started sth starting with 0.4.7, up to somewhere between 0.4.10 and 0.4.11.

**Comment by rubenwardy** [comment]
0.4.7 is sufficiently long ago. That's good.

**Comment by paramat** [comment]
Close?

**Comment by paramat** [comment]
Author is no longer contributing to MT.
Others are not keen to do this and i think it's not important.
