### ISSUE TITLE
3rd person camera shake in confined spaces

### ISSUE THREAD

**Issue by obneq** [minetest/minetest#2276]
1. dig a trench, 1 node wide, 2 nodes deep, 3 nodes long and get inside
2. toggle 3rd person view
3. walk forwards to the wall then backwards again, repeat.

this results in camera flickering when it hits the wall.

**Comment by VanessaE** [comment]
I can't reproduce this problem in recent Minetest.  The camera position just adjusts according to the wall you hit - no flickering.

**Comment by paramat** [comment]
Confirmed camera 'shakes' forward and backward when you walk lengthways in the trench.

**Comment by SmallJoker** [comment]
See #10841 for further issues.
