### ISSUE TITLE
Bad render performance based on shader data

### ISSUE THREAD

**Issue by gregorycu** [minetest/minetest#2283]
It appears when shaders are turned on, the game spend about 50% of the map rendering time updating the shaders constants.

It appears to update these shader constants once per material switch, and for every setting.

This can be improved drastically so the constants are only set when changed, for each of the shaders.

Also, the number of shaders could be reduced.

**Comment by kahrl** [comment]
Some ideas for improving performance:

Low-hanging fruit:

1. Don't set constants that are not used by the shaders. I noticed `mTransWorld`, `mInvWorld` and `DRAW_TYPE`; there may be others.
2. Since `DRAW_TYPE` is not used, don't make different shaders for different draw types. Making different shaders for different `MATERIAL_TYPE`s should be sufficient.

Higher-hanging fruit:
* Reimplement texture atlases to reduce the number of material switches.

**Comment by celeron55** [comment]
It also appears that the thing can generate up to 84 unique shaders for no good reason, which then have to be switched around when rendering - they all use the same constants, but Irrlicht probably assumes they don't, and this causes the constant setting performance problem.

**Comment by gregorycu** [comment]
I can probably do the two low hanging fruit mentioned, but not within the week.

**Comment by gregorycu** [comment]
I tried to make the shaders not be generated on DRAW_TYPE, however, I didn't notice a performance change.

**Comment by Zeno-** [comment]
I think this needs more investigation. E.g. a) is it a Windows only issue?; b) is it a driver issue?; c) is it a GPU issue?. etc.

**Comment by PilzAdam** [comment]
@Zeno- definitely not windows only.
I get very poor performance with shaders enabled with my GTX 460 and proprietary nvdia drivers.

**Comment by gregorycu** [comment]
@PilzAdam If you don't mind I'll ask you to apply a patch locally which will reduce how often your shaders are fed data. If it's the same problem you should notice a significant performance improvement.

I am on Windows with an ATI card.

**Comment by Fixer-007** [comment]
This issue can be closed I think since "Fix superflous shader setting updates" was finally merged.

**Comment by paramat** [comment]
#4800 merged.
