### ISSUE TITLE
No damage in creative mode

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#2285]
When creative_mode and enable_damage are true, and I join my singleplayer world with non-full health then I don't take any damage from falling or lava.

**Comment by kilbith** [comment]
I wonder if these modes ought be mutually exclusive... A game focused on pure creation should not be constrained by physical consequences.

**Comment by nerzhul** [comment]
I agree with kilbith

**Comment by PilzAdam** [comment]
@kilbith They are intended and always used to be independent.

**Comment by LazyJ** [comment]
jp/kilbith has a valid point; the purpose of using creative mode is to create without limitations.

However, I have found it useful, when testing and developing mods to be able to swtich between creative mode, survival, mode and neither (creative_mode and enable_damage are both *not* selected).

Creative mode so I can have quick access to all items in a mod to see what they do and don't do.

Survival mode to check that recipes work and to evaluate whether the recipes are too cheap or too expensive, in time, effort and materials, for what the resulting item is worth.

Neither mode where neither the creative_mode nor enable_damage box are checked is what I use most for mod work. I test that things are working with the inventory and crafting as intended while not being bothered with taking damage.

**Comment by nerzhul** [comment]
This make sense. We must discuss on IRC to see if we choose to solve the issue or not

**Comment by PilzAdam** [comment]
This is totally unrelated to this bug report. If you want to combine damage and creative mode then open a new issue and discuss it there.
Note that you do get damage in creative mode if you join with full HP.

**Comment by LazyJ** [comment]
Perhaps creative_mode was intentionally coded to override enable_damage if damage has been incurred?

I can see where it would be useful if you are testing mods or mobs that inflict damage *(how quickly, how much, how far away)*.  Exit the survival_mode game to switch to creative_mode, restart the game, grab more items from the creative inventory to stock up, then exiting the game again to turn off creative_mode, and then starting the game again to resume the damage test.

I didn't say that I wanted to combine damage and creative mode, although for the testing scenario I just described it would be useful and time-saving.

The comments do relate to the bug report if the bug fix affects the testing methods described in the comments. Whoever performs the bug fix may not be aware of how the bug and the different combinations of creative_mode and enable_damage are, indeed, used for purposes beyond game play.

**Comment by PilzAdam** [comment]
@LazyJ again, this is a bug. It is not intended this way.

**Comment by Zeno-** [comment]
Yes, this is unintended behaviour

**Comment by nerzhul** [comment]
I look at the code with grep and i haven't found where the creative mode is called yet. enable_damage seems to be handled properly. Maybe it's lua game related

**Comment by SmallJoker** [comment]
I can not reproduce this bug with the current HEAD.
Is there someone who still has this problem?

**Comment by paramat** [comment]
Is this solved by hmmmm's recent fix for the damage bug?

**Comment by paramat** [comment]
Bug is not present in latest dev 9c76f379acb12246fb1e282661e67b9da4cdcb62
