### ISSUE TITLE
Processing speed touch (Android)

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2288]
Ellementy addition control KodexKy are too quick response. They respond to the pressing duration of 100 ms. Therefore very difficult to switch them. One touch of a button I can enable, disable, and re-enable again to turn off the flight (pushing 0.5 seconds!). It is not very convenient. To ignore the pressing of less than 500 ms, and does not handle a few clicks in a row.

**Comment by Zeno-** [comment]
commit 9fbc3a8ca364922bc1129a35c1a37addab5f023c
