### ISSUE TITLE
Players start with a breath of 65535

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2289]
I noticed that on a player's first spawn, the initial breath value equals 65535.

How to reproduce:
* Install the mod “luacmd”
* Start a completely new minetest_game world with damage and luacmd enabled
* Give yourself the “lua” privilege
* Make sure you are not diving right now and have full breath
* Enter “/lua print(me:get_breath())” into console.

I would expect it to output `11` (for “breath bar not shown”), but instead it shows `65535`, a value with undefined meaning in `lua_api.txt`.

Note that the values seem to become normal as soon as you start to dive.

This bug has been tested under: Minetest 0.4.11, subgame minetest_game 0.4.11, operating system GNU/Linux.

**Comment by PilzAdam** [comment]
Fixed by 929e0b0ad8a1e2a7b373f5661e52e2384a24916d
