### ISSUE TITLE
 Eating from stack removes the whole stack using replace_with_item

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2292]

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L370

**Comment by MT-Modder** [comment]
Should be a simple fix then, no?

**Comment by rubenwardy** [comment]
Yes. I will do this in a few minutes time.

**Comment by rubenwardy** [comment]
According to PilzAdam in #2299, this isn't a bug.

**Comment by MT-Modder** [comment]
Well having a stack of food suddenly disappear is a bug to me.

**Comment by C1ffisme** [comment]
I agree with MT-Modder.
