### ISSUE TITLE
table.copy fails if one of input table's keys has a value of “false”

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2293]
Try this ultra-short mod and see how Minetest 0.4.11 fails:

```
table.copy({key=false})
```

Instead of copying the table, Minetest shows me this error message:
```
ERROR: /usr/share/minetest/builtin/common/misc_helpers.lua:510: bad argument #1 to 'pairs' (table expected, got boolean)
```

It also happens recursively to subtables. This code causes the same error:
```
table.copy({key={key=false}})
```

In contrast, this mod works:
```
table.copy({key=true})
```

If you have luacmd installed, it may be faster to test it with this mod.

**Comment by est31** [comment]
Confirmed. For `master`, the error is at line 548 btw.
And `table.copy({key=nil})` outputs `{}`...
Gonna do this with properly with if-then-else, as the selfmade ternary operator obviously fails here.
