### ISSUE TITLE
Very small icons on Full HD (Android)

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2294]
On Full HD andi 2K/3K screen icons on HUD bar @BlockMen very small.
On mainmenu client tab icon on server list very small.
Tested in Galaxy S4, S5, Note 4 and more other devices.

**Comment by MoNTE48** [comment]
Bug on main menu (official build!)
![screenshot_2015-02-14-17-32-05](https://cloud.githubusercontent.com/assets/6764600/6200061/794cc3ee-b46f-11e4-80f5-50138d86f9d7.png)
HUD bug. Unofficial build.
![screenshot_2015-02-14-17-32-18](https://cloud.githubusercontent.com/assets/6764600/6200063/8887c3d6-b46f-11e4-8d49-7d56ef855b26.png)

**Comment by MoNTE48** [comment]
This is still true. Especially, I can not put a tick in the check box

**Comment by RHRhino** [comment]
yeah vector graphics would be nice ...

**Comment by MoNTE48** [comment]
Pls, remove Unconfirmed labels

**Comment by paramat** [comment]
Is this bug in your fork Multicraft or in Minetest? If in Minetest is the bug stll occuring?

**Comment by MoNTE48** [comment]
This is Minetest bug. The MainMenu we use some incorrect scaling, it is not designed for small Full HD (Android devices) or small 4K monitors. The Client tab icons are shown "as is" if I make more of them (64*64), they will be more in the MainMenu, it does not apply to the scaling.

**Comment by paramat** [comment]
Are you sure? Or do you mean the bug is occuring in your fork of the engine and you're assuming it also affects Minetest? If so please try to reproduce the bug in Minetest. This is why the label is 'unconfirmed'.

**Comment by MoNTE48** [comment]
@paramat, I just can not restrain harsh words. I tested it on Minetest play store version. I have no reason to lie, and I'm not stupid to give out the error of the code (my code is error-free) for the mistake Minetest.

**Comment by paramat** [comment]
Thanks for the clarification.

**Comment by MoNTE48** [comment]
No problem. It seems to me that I am ready to engage in a Android port and no one else do not care. It is a pity that I was not the developer :(

**Comment by MoNTE48** [comment]
![screenshot_2016-04-11-01-59-38 1](https://cloud.githubusercontent.com/assets/6764600/14413653/3f47fa68-ff89-11e5-851e-31775ce55795.png)
LG G4

**Comment by stujones11** [comment]
This should now be fixed by 3b112889892f6652d4e80d97e45131f179b1fbe4

@MoNTE48 Could you confirm this? An apk is still available in the PR topic, if it helps.
