### ISSUE TITLE
SharedBuffer<unsigned char>::drop() [T = unsigned char]: Assertion '(*refcount) > 0' failed.

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#2300]
Server version: 0.4.11 (stable)
OS: FreeBSD 10.1

This is the second time this assert occurs on my server since 1 day:
```
In thread 805406800:
/wrkdirs/usr/ports/games/minetest/work/minetest-minetest-be358c0/src/util/pointer.h:279: void SharedBuffer<unsigned char>::drop() [T = unsigned char]: Assertion '(*refcount) > 0' failed.
Debug stacks:
DEBUG STACK FOR THREAD 805406400:
#0  int main(int, char **)
#1  Dedicated server branch
#2  void dedicated_server_loop(Server &, bool &)
(Leftover data: #3  void Server::step(float))
DEBUG STACK FOR THREAD 805408400:
#0  virtual void *ServerThread::Thread()
#1  void Server::Receive()
(Leftover data: #2  void Server::SendBlocks(float))
(Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment *, EmergeManager *, float, std::vector<PrioritySortedBlockTransfer> &))
(Leftover data: #4  MapBlock *ServerMap::loadBlock(v3s16))
(Leftover data: #5  void ServerMap::loadBlock(std::string *, v3s16, MapSector *, bool))
DEBUG STACK FOR THREAD 807433400:
#0  virtual void *CurlFetchThread::Thread()
DEBUG STACK FOR THREAD 807433800:
#0  virtual void *EmergeThread::Thread()
(Leftover data: #1  MapBlock *ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string *, v3s16, MapSector *, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream &, IItemDefManager *))
```

**Comment by nerzhul** [comment]
I read the file and the only issue i can see is the SharedBuffer is used by two threads at the same time and there is no mutex, but this is a supposition, i could not confirm where is the code for this.

**Comment by nerzhul** [comment]
It happened 4 times in 2 days

**Comment by Zeno-** [comment]
Backtrace?

**Comment by nerzhul** [comment]
i don't have a backtrace at this time. I'll try to get it

**Comment by nerzhul** [comment]
Ok, server is now launched with GDB.

**Comment by nerzhul** [comment]
Unfortunately... But this is always on loadBlocks.

#0  0x00000008028db6ca in thr_kill () from /lib/libc.so.7
#1  0x00000008029b0149 in abort () from /lib/libc.so.7
#2  0x00000000004aee91 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<< ()
#3  0x0000000000485205 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<< ()
#4  0x0000000000473c60 in std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<< ()
#5  0x0000000000472f5a in std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<< ()
#6  0x000000000040a2d1 in ?? ()
#7  0x00000008026524f5 in pthread_create () from /lib/libthr.so.3
#8  0x0000000000000000 in ?? ()

**Comment by nerzhul** [comment]
this issue doesn't occur since 1 year
