### ISSUE TITLE
BACK button crash on Android Lollipop.

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2302]
Test on more devices 5.0.1-5.0.2
Press BACK button on MainMenu and app crash.
On <4.4.4 all good

**Comment by MoNTE48** [comment]
unconfirmed bug ?

Download genymotion.com , sarting Andorid 5.0 and test this.

**Comment by MoNTE48** [comment]
Crash unofficial build.
On official build bug too.

![screenshot_2015-02-14-17-35-19](https://cloud.githubusercontent.com/assets/6764600/6200071/e9bdcb1e-b46f-11e4-8f2b-0c1fcabbea11.png)

**Comment by est31** [comment]
related to PR #2677. Still there? I can't reproduce.

**Comment by MoNTE48** [comment]
Bug on ALL Samsung (official firmware) 5.0-5.0.2. On 5.1 all good.

**Comment by MoNTE48** [comment]
On other devices I not see this problem. Only on Samsung.

**Comment by sapier** [comment]
can you provide adb logcat output of this crash?

**Comment by MoNTE48** [comment]
It was all Samsung 5.0-5.0.1 firmware. I've been thrown out of my s5 and note 4. On 5.1 this error is not

**Comment by est31** [comment]
@sapier this crash is most likely about android forcing its "you can't end an app's process yourself as app" system upon apps. The moment minetest asks to terminate, its seen as reason to crash, even though nothing really bad happened.

**Comment by est31** [comment]
But I don't add upstream labels here, because the reasoning is unconfirmed.

**Comment by est31** [comment]
?

**Comment by MoNTE48** [comment]
I could not reproduce it on the master. I think there are no more errors.

**Comment by est31** [comment]
Well, okay then...
