### ISSUE TITLE
Username Tag API for Engine

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2305]
In minecraft, you can hide your username by holding down shift. It would be great if we could do this in minetest games, if you want to hide in a maze, etc. Then I thought about it, why not make a whole API? We could use name = minetest.get_username_tag("username") and then do things like hide it, disguise it as another name, etc. I would like the functions:
- minetest.get_username_tag("username") - Returns a username object
- minetest.username_hide(username_object) - Hides the username from view.
- minetest.username_show(username_object) - Opposite of minetest.username_hide().
- minetest.username_change(username_object) - Changes the text in the name.
- minetest.username_return(username_object) - Returns the username to it's origional value.

I can see this being used on PVP servers, or servers that use a Polyjuice Potion, or some kind of disguise method.

**Comment by ShadowNinja** [comment]
I think it would be better if this worked for all objects.

The flexibility to add things like health bars would be good too.

**Comment by indriApollo** [comment]
:+1: ^

**Comment by MathieuMorrissette** [comment]
it would be really nice

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by Amaz1** [comment]
Aren't all of these functions now possible using player:set/get_nametag_attributes()?
You can hide nametags by using `player:set_nametage_attributes({text = " "})` and show/restore them to their default text by `player:set_nametage_attributes({text = ""})`

**Comment by C1ffisme** [comment]
I'd be interested in seeing support for client-side nametag hiding, because then you can do things like hiding the player's nametag when they are more than 25 blocks away from you. But that's low priority.
