### ISSUE TITLE
minetest.place_node ignores node parameters

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2306]
Currently I've only tested param2. This just doesn't seem correct IMO.

**Comment by ShadowNinja** [comment]
I'm not sure if this should be counted as a bug.  The docs says it places like a player would, and players can't set param1 or param2 -- it's set for them by place_node for things like facedir.

**Comment by MT-Modder** [comment]
I see your point. The main issue here is with mesecons and doors.
For more about this issue see: https://github.com/Jeija/minetest-mod-mesecons/issues/220
I just realized that the doors mod should be rewritten so it doesn't use a craftitem. That would fix this issue. I'm gonna close this issue for the reasons you stated above.
