### ISSUE TITLE
Oclusion is calculated with the charecter's position, not the camera's

### ISSUE THREAD

**Issue by mamoit** [minetest/minetest#2307]
The following behaviour is observed when in third person view.
Without moving the mouse:
First you are hidden...
![screenshot_2239699140](https://cloud.githubusercontent.com/assets/4675358/6197648/1ae3d402-b3e1-11e4-9466-7a1426cf34fb.png)
Then you jump...
![screenshot_2239702607](https://cloud.githubusercontent.com/assets/4675358/6197649/20353388-b3e1-11e4-916f-01f9a6b34e48.png)
Therefore the calculation of occlusion is being done relative to the character, not the camera.

**Comment by mamoit** [comment]
This behaviour was first observed by @PilzAdam on #2070.

**Comment by Fixer-007** [comment]
Confirm it.

**Comment by mamoit** [comment]
Seems to be happening, just tested it with master.

Empty area back there:
![screenshot_20160331_132135](https://cloud.githubusercontent.com/assets/4675358/14175563/9e93c838-f743-11e5-964a-98755251ff25.png)
Then I move out of the blocks way:
![screenshot_20160331_132126](https://cloud.githubusercontent.com/assets/4675358/14175565/a321fbe0-f743-11e5-8c5a-d7b7212ce172.png)

**Comment by Fixer-007** [comment]
But maybe it is intentional, to study behaviour of rendering/occlusion.

**Comment by mamoit** [comment]
That does not make a lot of sense to me.
If you can play in third person, it should look good in third person.

**Comment by rubenwardy** [comment]
is this still the case?

@juhdanad may know

**Comment by mamoit** [comment]
I don't really know, haven't built minetest in a while.
I'd say #2240, #2070 and #4922 have something to do with this.

**Comment by juhdanad** [comment]
It is @lhofhansl and @numberZero who changed occlusion recently, not me.

**Comment by lhofhansl** [comment]
The code does not adjust for 3rd person view. #4959 is related.

**Comment by numberZero** [comment]
I have never touched occlusion, only renderer itself.
