### ISSUE TITLE
Server should send other player's inventories when its needed

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2308]
@thefamilygrog66 has pointed out on irc that the formspec `"list[player:"..param..";main;0,0;8,4;]"` isn't working (returning an empty inventory) when the value of `param` is something else than the player themself. I've inspected the code and found [this lookup](https://github.com/minetest/minetest/blob/master/src/client.cpp#L2503-2509) ,which should take care of the formspec, but unfortunately m_env doesn't contain inventory informations for other players than the current one. The server should send, when needed, other player's inventory to the client. It would need a network protocol change, so I'm @nerzhul on this.

**Comment by est31** [comment]
My idea would be to add a new message type `TOCLIENT_OTHER_INVENTORY` which contains the other player's name and the serialized inventory. We could also think of unifying `TOCLIENT_INVENTORY`, `TOCLIENT_DETACHED_INVENTORY` and that `TOCLIENT_OTHER_INVENTORY` functionality into one message, but it would create unneccessary overhead. Or we could remove the useless lookup from client.cpp and document that "player:<name>" inventory locations aren't working for formspecs.

**Comment by nerzhul** [comment]
Don't use a new packet, just add player name field into original packet and handle it properly on client side.

**Comment by est31** [comment]
This requires a break in protocol. I'll wait until the debate about whether to break stuff in master has been resolved.

**Comment by Zeno-** [comment]
Under what circumstances would this be useful?

**Comment by est31** [comment]
@Zeno- to make code like this work: http://pastie.org/9945419

**Comment by PilzAdam** [comment]
@Zeno- also useful for backpacks from nodetopia.

**Comment by est31** [comment]
[src for nodetopia](https://github.com/PilzAdam/nodetopia/blob/master/mods/backpack/init.lua#L125)

**Comment by nerzhul** [comment]
Have you created a PR for this, as we discussed ?

**Comment by est31** [comment]
I'll do it as PR to 0.5-dev branch.
