### ISSUE TITLE
Update translations for all languages

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2313]
Update translations for all languages. In the past month we have changed over 30 strings and no further changes are anticipated. It is necessary to revise all translations for the next release.
First run ***./util/updatepo.sh*** for update all strings and then put a notice in the forum for someone to review. @ShadowNinja 
***Note:*** I already did that in #2312 and updated the Spanish language. You only need to write a message in the forum or notify translators.

**Comment by JakubVanek** [comment]
PRs containing .po updates can be merged, even if they already have updatepo.sh applied. If updatepo.sh is executed to up-to-date .po, nothing happens. For example: 2630f45

**Comment by ngosang** [comment]
@JakubVanek I didn't know. I updated the PR and the first message. Check if everything is ok with cs translation.

**Comment by ngosang** [comment]
@JakubVanek I checked the cs translation and there are several changes. Looks like you have to translate some strings again. You can also remove the commented lines at the end of file, they are old translations.

**Comment by ShadowNinja** [comment]
This breaks all translation update PRs, they all have to be merged first.

**Comment by ngosang** [comment]
Ok.
