### ISSUE TITLE
Feature Request : Make minetest.add_entity() return a Luaentity, rather than an object.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2318]
Lets say I make an NPC mod that looks like this:

> names = {"Jeff","Bob"}
> 
> npcs.make_npc(name)
>     minetest.register_entity(name,{
>           name = names[math.random(1,2)],
> })
> 
> npcs.make_npc("NPC1")

Now I want to make an NPC and change it's name.

> obj = minetest.add_entity("NPC1",{0,0,0})
> obj.name = "Joe"

This code will not work, first because I didn't do a lot of required stuff for registering, but also even after making the code that makes this work, the NPC's name will not be changed to Joe. Why? `minetest.add_entity` does not return a luaentity. It returns an object, which could barely give HALF the information we might use. I think a fix is in order? Either make `minetest.add_entity` return a luaentity or an entity ID to find it in the table of luaentities.

**Comment by C1ffisme** [comment]
BUMP!!!

**Comment by C1ffisme** [comment]
Bump.

**Comment by rubenwardy** [comment]
You can't do OBJ.entity.name, or something?

**Comment by PilzAdam** [comment]
@rubenwardy yes, you can, with obj:get_luaentity().name

@C1ffisme This is not possible since it would break the API.

**Comment by C1ffisme** [comment]
Hm... I'll attempt this...

**Comment by C1ffisme** [comment]
It works! Thanks guys. I'm a little slow when it comes to proggramming, and new-ish (I started proggramming mods somewhere around 0.4.3 I think.). This will help me in my personal animals mod. But, as a feature request, could you make a function to retrieve an Object ID from an object? Thank you if the awnser is yes, no problem if the awnser is no. Closing.
