### ISSUE TITLE
No proper way to remove recipes

### ISSUE THREAD

**Issue by gregorycu** [minetest/minetest#2319]
At the moment if a mod author wants to remove a recipe, they have to overwrite the recipe with one that outputs 0 items.

We should have a proper API to remove a recipe.

**Comment by C1ffisme** [comment]
I can see this coming to use, if say, you have to overwrite the craft recipe for bronze or something, but I can also see there are very FEW uses for it. If you did need to overwrite a recipe, I would think that it would be better to just use code.

**Comment by gregorycu** [comment]
But how do you disable a recipe? Let's say you wanted to make it harder to make sticks. So you make a different recipe. But what of the existing one? It still exists. There is no requirement that there exist only a single recipe per output item.

**Comment by C1ffisme** [comment]
The technic mod actually made a way to disable a recipe. Just find the code that stops the bronze ingots from being crafted with iron.

**Comment by gregorycu** [comment]
They did exactly what I said above (though I probably explained it poorly): Define an additional recipe with an output of 0.

**Comment by C1ffisme** [comment]
True... True...

**Comment by rubenwardy** [comment]
I have put this on my to do list. The main problem is how do you identify a craft recipe? You could do output, but it is possible that other mods define recipes for that output, or you only want to delete one of the recipes (eg: recipe for making tool, not for deleting tool.)

I suggest this:

    minetest.delete_tool({
        output = "blah",
        type = "normal" --(or whatever the default type is)
    })

**Comment by rubenwardy** [comment]
* craft.

That function checks that each of the properties you give match the property in the recipe definition.

**Comment by rubenwardy** [comment]
Nevermind, it's been done. I can do something else now! :D

**Comment by gregorycu** [comment]
I can't tell, are you happy with this or not? :)

**Comment by rubenwardy** [comment]
I am happy, it means I don't have to do it. I can do other things. Don't worry, any patches I would have made won't have been to the same quality.

**Comment by hunter688** [comment]
Will be fine recipes per player, this can be way for technology tree, researching etc like in the ThaumCraft mod in the Minecraft.

**Comment by rubenwardy** [comment]
hunter688, it would be better to override the inventory to make a different craft method.

**Comment by jhcole** [comment]
> Edit: Nevermind, it's been done. I can do something else now! :D

Where has this been done? I would really like to use something like this.

**Comment by est31** [comment]
Implemented by 281e9f39fdffd106e79122ae23e2b5443a5daea3
