### ISSUE TITLE
Minetest ignores numlock on Xubuntu 14.04

### ISSUE THREAD

**Issue by JakubVanek** [minetest/minetest#2322]
When I want to type numbers on numeric keyboard, I simply can't. This happens when **numlock is turned on, even when it's turned off**. Instead of numbers numeric keys behave as functional keys (arrows etc.). I must type numbers by using keys above QWERTY line of keys. It's very odd bug. I don't know if this happens also on Windows, but I'll bet the answer is **no**.
Minetest version: latest from Ubuntu daily ppa on 15 Feb 2014 *(I'm unable to determine commit)*, but it started to happen some time before.

**Comment by Zeno-** [comment]
This is a known bug in irrlicht

**Comment by JakubVanek** [comment]
I hope they can fix it. Related bugs: #373 
https://forum.minetest.net/viewtopic.php?f=6&t=9782
https://forum.minetest.net/viewtopic.php?id=3792

**Comment by PilzAdam** [comment]
Duplicate of #1898
