### ISSUE TITLE
Video-making Options

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2323]
These would be very useful for making trailers and films in Minetest.
- Smooth movement
  - Smooth increases and decreases in movement speed.
- Freecam (move independently of player)
- Spline / path following.
  - Some way of placing paths on client side and then following them.
- Lock cam (player, not camera)
- Recording resolutions higher than your screen size (eg: 1080p when using a screen of 1024x768)

**Comment by C1ffisme** [comment]
Yes. Please. I made some videos for school in minetest, believe it or not. (Another one of my homeschooly moments.) :+1:

**Comment by rubenwardy** [comment]
I'm going to work on smooth mouse & movement, but I can't even think of how to do the rest.

Another problem is recording 1080p HD when the screen is only 720p.

**Comment by C1ffisme** [comment]
@rubenwardy I think the freecam could be attempted by using similar code to the 3rd person view. I dunno though, I don't really know any C++ and barely any C.

**Comment by rubenwardy** [comment]
This is @BlockMen's area, I think he wrote 3rd person view.

**Comment by C1ffisme** [comment]
We'll see what he says when he reads his messages.

**Comment by BlockMen** [comment]
@rubenwardy Freecam like "you can rotate and zoom in/out" or like "cinematic camera that jumps around and take awesome scenes". The first shouldnt need too much changes.

But in general its done in MT with camera modes that could be extended, but that also raises the question: how many camera modes are fine to be toogled through?

**Comment by rubenwardy** [comment]
@BlockMen The first would be good. I did mean the second, but that could just be done by another player filming (although if using a single computer you wouldn't be able to move the filmed camera whilst filming.)

Some of these things will need privileges to be used because they may give an advantage in multiplayer. Such as freecam or splines.

A note on splines, you'd need to consider whether to move the player as well. Different modes.

Moving the player separately to the camera is an interesting idea (Calinou suggested freecam) you could use WASD for the player and arrows for the camera.

**Comment by est31** [comment]
do we really want free camera? I mean some servers dont give fly to every player, what is free camera different from fly except that you can interact? And when you have fly, you can just move the player. And when you want to record from 3rd person view, and the supplied 3rd person view is not enough, then you can simply join as another player, and record that window.
but yes engine support for binocular mod would be really cool.

**Comment by sfan5** [comment]
> Another problem is recording 1080p HD when the screen is only 720p.

Not really. All you need to do is create a render target at the desired resolution and render Minetest into that, the problem is that this requires either:
* Rendering everything twice

_or_
* Downscaling the rendered scene


See my `8k_screenshot` branch for working code: https://github.com/sfan5/minetest/blob/8k_screenshot/src/client.cpp#L2804-2822

**Comment by rubenwardy** [comment]
Ah. Can you do this easily in upstream Minetest? If not it should be added in some form, in my opinion.
