### ISSUE TITLE
Dialogs whilst game loading

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2324]
Dialogs can be sent to the player from the server whilst the are connecting. Players only emerge into the game when all dialogs have been dealt with (no more are being sent and the server says so).

**Uses:**
- Automagically fixing mod installation.
  - Missing init.lua files are usually caused by the mod folder being inside another folder.
    The player could be asked if they'd like it to be automagically fixed
    (ie: if there is only one subfolder and no files in the root of the mod,
    move the subfolder out and delete the mod folder.)
  - Players could ask if they'd like to automagically fix dependency problems instead of just deactivating the mod. (requires MMDB to actually work)
- Mods can send connecting players dialogs which halt their connection progress.
  - Setup mod (may need to be setup before game finishes loading to change which blocks are defined.)
  - Rules

The aim of this is to improve the user interface by 1) making it clearer what went wrong, rather than weird mod errors or disabling the mod. 2) Make fixing common problems automatic.

Servers are usually started from the console, so that needs to be taken into account with the autofixing (then again, they'd be more seasoned developers)

**Comment by C1ffisme** [comment]
@rubenwardy I can see this being used with some kind of skins mod to show what skin you'd like, what gender you are, etc.

**Comment by rubenwardy** [comment]
**Why not as formspecs ingame?**

* Customizing and setting up mods that needs to be done before the game loads.
* No distractions, players can't even enter game before clicking agree to rules.

**Comment by C1ffisme** [comment]
Exactly! I knew a server where people wouldn't bother reading the rules before stepping outside. It's like nobody cares about rules. I know the LinuxGaming.us Server has a solution, it will make a formspec apear on join, but you can close it. With a dialog before joining, you can read the rules right away.

**Comment by rubenwardy** [comment]
You could make a formspec appear persistently.
