### ISSUE TITLE
Add a responsive favicon to minetest.net

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#2329]
Using http://realfavicongenerator.net/, you can generate a responsive favicon for the site. The recommended source image size is 260² pixels.

**Comment by ShadowNinja** [comment]
* This probably belongs here: https://github.com/celeron55/minetest.net_dokutemplate3
  * `image/vnd.microsoft.icon` files store a bunch of sizes of bitmaps on one badly compressed file.  Adding these could substantially increase the file size of the icon.  Using gzip compression (yes, it actually works on these images) will mitigate it a bit, but it might be better to use a larger PNG and let browsers scale the image.
  * 260<sup>2</sup> pixels?  That sounds way too big.

**Comment by cheapie** [comment]
I'm of the opinion that it should be a 64x64 PNG (after all, PNG is the standard icon format).

**Comment by Calinou** [comment]
> 2602 pixels? That sounds way too big.

This is the source image size. The actual images are 192² or so *at most*; not all of them are downloaded.
