### ISSUE TITLE
large air bubbles created under water

### ISSUE THREAD

**Issue by sudoman** [minetest/minetest#233]
it looks like that sometimes large systems or tubes of air bubbles are created under water. [pic](http://imgur.com/ZZCVS)

these bubbles are near a tunnel that comes out of the water.

I can upload the map in question (or a particular backup), if needed. It was created on 8-12-12 with the latest git, and has been used with 9696ed31a41b5e3ca85bad4a29c190a0d25c7752.

**Comment by paramat** [comment]
Dungeons too sometimes create large air bubbles underwater, we now have increased capacity in the waterflow code, so these bubbles tend to fill with water after a few seconds.

**Comment by nerzhul** [comment]
@paramat issue fixed ?

**Comment by paramat** [comment]
Yes, closing.
