### ISSUE TITLE
craft replacement only replaces when stack is 1

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2331]
I wouldn't know the best way to fix this since you would either replace the whole stack or add the replacement to another crafting slot and the latter wouldn't work if the crafting grid is full so....??? I know this isn't a bug but it just doesn't feel right since it only replaces once instead of once per craft.

**Comment by C1ffisme** [comment]
Maybe the replacements should go to the inventory, like the milk buckets in cake in minecraft.

**Comment by MT-Modder** [comment]
Yeah that would probably be better. Then if the inventory is full drop it on the ground. I ran across this issue and issue #2292 about six months ago when I made seeds replace watermelon slices when crafted or eaten.

**Comment by TeTpaAka** [comment]
Fixed by 17ba584

**Comment by est31** [comment]
sorry, forgot to close this, @TeTpaAka is right, 17ba584fe254eeaee3489cc20e03810a59f3ef9b closed this.
