### ISSUE TITLE
Start work on 0.5.0. Now.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2333]
I'm pretty sure a lot of us have been waiting, and been excited after 0.4.9, until we found out about 0.4.10.

See, minetest isn't doing much. The changelog on the dev wiki needs to be updated, and a lot of other things. If you do look at that change log, you will see there is only a few big changes between versions. I suggest we look at the TODO, [here](http://dev.minetest.net/TODO). I want to do at least ONE of these big long term projects. I would like to see voxel area entities, but what we do is probably up to the community.

We have delayed 0.5.0 for too long. Ubuntu releases new versions every 6 months, so why haven't we gone up to the next big version in like, 2 or 3 years?

**Comment by ShadowNinja** [comment]
1. We **ARE** working on 0.5 *now* (and at the same time finishing up 0.4.12).
  2. This isn't really an issue, it's more of a discussion.  Use the forum or IRC instead.

**Comment by PilzAdam** [comment]
Version numbers do not matter.
