### ISSUE TITLE
Some way of specifying not to do rollback recording in set_node()

### ISSUE THREAD

**Issue by cheapie** [minetest/minetest#2335]
On VanessaE's survival server (as well as, no doubt, others), there are lots of quarries, deployers, node breakers, etc. running constantly, and everything they do is recorded in the rollback logs, making the rollback DB grow to several GB, and a simple rollback_check takes in excess of ten minutes. If griefing is caused by one of these machines, it is generally fairly obvious where the machine is or was, and a rollback check can be done on that location. I therefore propose that the dig_node() and place_node() functions should have some way of specifying that the action is not to be recorded in the rollback database, so that these machines do not record rollback entries as they run. The default should be to record an entry, so that things where it is not obvious who used them will still record entries, even if not updated for this.

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.
Seems too low priority to add a new field to node placing functions :-1:
