### ISSUE TITLE
Unhandled exception in vector.lua

### ISSUE THREAD

**Issue by vitaminx** [minetest/minetest#2336]
Hi, my server crashed 5 times in just a couple of minutes today:

    07:35:53: ERROR[main]: ERROR: An unhandled exception occurred: /usr/share/games/minetest/builtin/common/vector.lua:104: attempt to perform arithmetic on local 'b' (a nil value)
    07:35:53: ERROR[main]: stack traceback:
    07:35:53: ERROR[main]:  /usr/share/games/minetest/builtin/common/vector.lua:104: in function 'subtract'
    07:35:53: ERROR[main]:  ...erver/.minetest/mods/mesecons/mesecons_detector/init.lua:139: in function 'node_detector_scan'
    07:35:53: ERROR[main]:  ...erver/.minetest/mods/mesecons/mesecons_detector/init.lua:263: in function <...erver/.minetest/mods/mesecons/mesecons_detector/init.lua:262>

I'm using minetest-server 0.4.11+repack and minetest-game on Debian.
I dont know how to reproduce it though.

A also opened a bug already for the mesecons developer: https://github.com/Jeija/minetest-mod-mesecons/issues/224
But it seems to be an issue with minetest itself.

Thanks!

**Comment by PilzAdam** [comment]
This is a bug in the mesecons mod, it calls subtract() with an invalid second parameter.
