### ISSUE TITLE
Server console and remote control of server

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2338]
Will be possible add server console? It will be very useful for server owners. Also remote control, telnet or any kind of secured connection will be very useful.

I know https://github.com/ShadowNinja/minetest-irc_commands
but builtin server console will be better.

**Comment by nerzhul** [comment]
Personnaly i disagree to this.

**Comment by hunter688** [comment]
I think about server console like in bukkit or minecraft.

http://i.imgur.com/a0Y0Q.png

**Comment by falsechicken** [comment]
:thumbsup: I would love this. I cannot count how many times I have needed to SSH into my box and do some admin commands from my phone or something only to remember I have to run the full freaking client to do a simple kick/ban/whatever. I did it with Bukkit all the time and it was awesome.

**Comment by ShadowNinja** [comment]
I used a mod for this that perioducally checked for a file in the world dir and ran commands from it before I started using the IRC mod.  It's hacky, but there isn't really a good way to implement this without something like a control socket or a ncurses-style interface so you can accept input and send output at the same time without messing up input lines.

**Comment by hunter688** [comment]
For Remote Console (RCON) and server console can be inspired by code from MCServer project (Apache 2.0 license): https://github.com/mc-server/MCServer

**Comment by est31** [comment]
I think there should be a C API. The "console" consists of a dynamically loaded so or dll file whose path is specified inside a minetest.conf setting. The default implementation consists of the current state, and there should be some alternatives, like one that depends on ncurses, and one for systemd (I won't code that, have no systemd). Then people can add ssh support, a smal http server, lua bindings, or other things, as they want, and chose their solution at runtime. As its dynamically loaded, nobody has to recompile. I think a lua API is the wrong approach here, as lua might be easily editable, but it hasn't been designed for interfacing with various stuff like advanced control of the console, systemd, or network for ssh and http.

**Comment by est31** [comment]
@rubenwardy from IRC I assume this issue might interest you.

**Comment by rubenwardy** [comment]
I tried getting ncurses to work on a clean c++ project, it was painful. I
have never used it before, and I don't know how to create the effect I want
from looking at the docs. It would probably be best if someone else
attempted this.

    Minetest ASCII Art
    Some log msgs




    Login (username):

The vision i had was a fixed input box at the bottom of the prompt, with
output messages being added above it.

**Comment by Megaf** [comment]
Folks, I had the oportunity to administrate several servers of several types of games, such as, America's Army 2.5 and 2.8, Return to Castle of Wolfenstein, Unreal Tournament 2004 and Minecraft.

All of them have at least a simple console from where I can send commands to the server. In my humble opinion, one of the most useful features of a server console is to be able to remotely login and and messages to all players. 

So for example, I could login remotely from my workplace, using ssh/telnet and tell players about a reboot or mod update. I could see check how things were going and stop players from doing stuff they weren't supposed to be doing.

@rubenwardy suggestion is the most elegant, all we need is a window with the output of player actions and stuff that's going on the server, and a box to enter commands.

**Comment by Zeno-** [comment]
Once you're used to it, ncurses is quite straightforward. 

Regarding a C api, this is something  I've always supported

**Comment by nerzhul** [comment]
is ncurses supported by Windows ?
Also, i don't think we need ncurses, a simple prompt with some commands is sufficient, and don't add more deps

**Comment by rubenwardy** [comment]
You need to be able to input and output at the same time. So ncurses would be best. It could be an optional dependency, anyway.

**Comment by nerzhul** [comment]
It's possible with two threads... stdin is on main thread with only do a join on other threads. And other threads (like serverthread) are do output to stdout.

**Comment by rubenwardy** [comment]
Will it work as I want it to?

**Comment by nerzhul** [comment]
Yes

**Comment by Zeno-** [comment]
Yes, don't add more deps. Just add the C API. Then people can use whatever dep that pleases them.

ncurses is available on Windows btw.

**Comment by hunter688** [comment]
Please do not add ncurses, simple console like minecraft (bukkit/spigot) will be better.

**Comment by est31** [comment]
Check out my [ncursesw console](https://github.com/est31/minetest/tree/ncurses-console) I wrote. If you set it up with screen, you can control the server remotely. Also, if we abstract auth and further things out of the client class, we can perhaps make the console even natively remote.

**Comment by hunter688** [comment]
Hey, it works very well! Thanks!

**Comment by FreeLikeGNU** [comment]
:+1:  @est31 that would be very handy!  I hope it gets merged upstream!

**Comment by est31** [comment]
It got merged, as #3292 .

**Comment by ShadowNinja** [comment]
@est31: Close then?

**Comment by est31** [comment]
Well one could argue about a remote server console, so that part of the feature request is not implemented. Dunno whether it should.

**Comment by falsechicken** [comment]
I'd just use ssh/tmux for remote support and call it a day xD.

**Comment by est31** [comment]
Yeah that would be the reasoning for not implementing native remote support. Do one thing and do it well style.

**Comment by hunter688** [comment]
I think can be closed, server console works very well. Remote control can be achieved via ssh/rdesktop etc... Thanks.
