### ISSUE TITLE
privileges groups

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2339]
Will be possible add support for privilege groups?

For example default group for players, group builders for players who can change gamemode, admins, etc...

This can simplify server management.

**Comment by nerzhul** [comment]
Good idea !

**Comment by C1ffisme** [comment]
:+1:

**Comment by ShadowNinja** [comment]
I implement something like this with a custom mod on my server that just grants privileges in batches based on config settings.  Groups would be a much cleaner way to do this though.

**Comment by Calinou** [comment]
Perhaps groups would be privilege names prefixed with `@`. In a mod, groups could be created, then you could do stuff like `/grant player @build`.

**Comment by falsechicken** [comment]
:+1:

**Comment by Zeno-** [comment]
I've been thinking about this for a while, so of course I agree with the idea :+1:

**Comment by rubenwardy** [comment]
this should probably be done by a mod first, before the core
