### ISSUE TITLE
map seed is still broken

### ISSUE THREAD

**Issue by fz72** [minetest/minetest#2341]
to reproduce create a new world with seed 44, 
   the world gets a random seed
next create a world with seed 34, 
   now the world gets seed 44

**Comment by kilbith** [comment]
I can reproduce that (@kwolekr). The seed is buggy since a while, and the last patch 48fa893a is apparently incomplete. Likely related with the map_meta.txt.

**Comment by nerzhul** [comment]
Thanks for your PR.

0a299fd4e5dff20bb09f54f2329aedcc8d22ef9d
