### ISSUE TITLE
Android toclientpacket.cpp

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2347]
abling jobserver mode.                                                                                                                    
make[2]: *** No rule to make target `jni/../jni/src/network/toclientpacket.cpp', needed by `obj/local/armeabi/objs/minetest/jni/src/network/toclientpacket.o'.  Stop.                 
make[2]: *** Waiting for unfinished jobs....                      

Pls, see all change and add on android build! Thank you, @nerzhul

**Comment by nerzhul** [comment]
Fixed;... i added two other files which are missing and remove toclientpacket and toserverpacket which are removed.
