### ISSUE TITLE
Bad Alloc Error

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2351]
I'm playing around with my coding, and I'm trying to make a mod with soldiers that fight each other and players. However, I'm having problems getting soldiers to attack each other, because usually one will attack, and the soldiers on one player's side cannot attack with the player being near. So I tried a few things, and I'm at a point where I keep getting this error and minetest crashes:
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc

This is my init.lua : https://gist.github.com/C1ffisme/5a8ff341ae1668afff98
This is my animal_definition.lua : https://gist.github.com/C1ffisme/7ea19591e6027fbd3a03

**Comment by PilzAdam** [comment]
Do you run out of RAM?

**Comment by C1ffisme** [comment]
Not sure... I'm on a Dell Latitude, which might not be the best computer for minetest. Do you know of a way to check RAM on Linux?

**Comment by PilzAdam** [comment]
`top`

**Comment by C1ffisme** [comment]
So, I removed the if loop around the for loop which detected for nearby entities to attack, and my mod works now on my computer, but if we decide, we should probably consider finding a way to stop this crash.

**Comment by nerzhul** [comment]
Solves, memory problem on user's computer
