### ISSUE TITLE
Add some useful global variables to Lua API

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2360]
It would be useful for modders to add some variables into global space, available for all mods and subgames automatically:
- `MIN_X`, `MAX_X`, `MIN_Y`, `MAX_Y`, `MIN_Z`, `MAX_Z`: The minimum and maximum legal coordinate for each corresponding axis. Should contain number, i.e. `MIN_X = -30912`
- `LIGHT_MAX`: Maximum possible light level (sunlight level). I _strongly_ suggest to remove this variable from the default mod of minetest_game, this is engine stuff, not subgame stuff.

Do you have suggestions for other global variables? Maybe it is helps to search the engine code for important constants and judge which of them could be important to modders as well.

**Comment by ShadowNinja** [comment]
Using globals is a Bad Idea.  Storing these under the engine's namespace would be O.K. though.

`LIGHT_MAX`currently means max non-sunlight IIRC.  Also, it's clearly defined as `14` in the API docs if I'm not mistaken.

**Comment by Wuzzy2** [comment]
Something like `minetest.WHATEVER`, i.e. `minetest.MIN_X`?

The thing with `LIGHT_MAX` is, even if it is defined as such in the docs, minetest_game writes into this variable. This variable is *not* defined outside of minetest_game, unless you define it explicitly in any mod. Pretty redundant, I think.

Also, `LIGHT_MAX` is not explicitly defined in lua_api.txt.

**Comment by MT-Modder** [comment]
> The docs clearly should not use a variable which is never formally defined and is minetest_game-specific.

I agree.

I agree with ShadowNinja on this. It's pretty redundant to add these globals since mods could easily do it themselves, i.e. ```mod.min_x = -30912```

**Comment by Zeno-** [comment]
Actually, `LIGHT_MAX` is a good example and so is `mod.min_x`. IF these could somehow be global constants of some sort then mods would be more robust and "future proof". A mod that assumes a value for `min_x` is making an assumption on what that value is for the engine (or server) that it's running on. min_x can be changed now by someone running a server. It might also change in the engine tomorrow, in a year, or never.

**Comment by MT-Modder** [comment]
Good point Zeno, I didn't think of it like that. :+1:

**Comment by PilzAdam** [comment]
:+1: these constants are useful for mods that don't want magic numbers.

**Comment by rubenwardy** [comment]
I believe these have already been added

**Comment by paramat** [comment]
The min and max generated co-ordinate for each axis now depends on the 'map generation limit' setting (but i know how to calculate it).

**Comment by paramat** [comment]
LIGHT_MAX is added.
