### ISSUE TITLE
Option to remap mouse buttons, not just keyboard keys

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#2361]
I would like to have the ability to remap my mouse buttons freely. Like middleclick = placing nodes or rightlick = jump for example.

Would be a useful feature for lefthanded players, too.

See MT forum thread:
https://forum.minetest.net/viewtopic.php?f=5&t=11255

**Comment by SmallJoker** [comment]
It would require some changes in game.cpp to make this possible.

Example: https://github.com/minetest/minetest/blob/master/src/game.cpp#L3383

**Comment by paramat** [comment]
Any more comments or support?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by paramat** [comment]
See #2382 was being coded but author disappeared, anyone else intersted in coding this or adopting the PR?

**Comment by paramat** [comment]
Any core dev interest?

**Comment by rubenwardy** [comment]
Implemented in 5.4
