### ISSUE TITLE
Player Names are Too Small to Read Above Avatars

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#2363]
Minetest Engine commit:  e357577
Minetest_Game commit:  03c00a8

This has been a problem for a long time. I finally thought to increase the font size in minetest.conf to a large setting and then log into a server *(MTZ-Basic/mtzeno.com)* to take a screenshot of a player to illustrate the problem as just chatting about it seems to not convey well.

Here is the screenshot that shows the player name's so tiny that it is almost illegible:

![Screenshot showing how tiny the player name's are](http://i.imgur.com/wFt1b39.png)

**Comment by rubenwardy** [comment]
This is specified in ClientCAO or something like that. It is an ITextSceneNode supplied by Irrlicht, I don't think you can choose the font.

**Comment by BlockMen** [comment]
@rubenwardy sure you can change that ;)
![screenshot_406767882](https://cloud.githubusercontent.com/assets/3742497/6310317/e86b299c-b955-11e4-9566-5757b69194d8.png)

**Comment by rubenwardy** [comment]
okay, I remember someone saying you couldn't in IRC ages ago.

**Comment by indriApollo** [comment]
Well that myth has been busted tadadaaaaa :D
