### ISSUE TITLE
Error Building Latest stable-0.4

### ISSUE THREAD

**Issue by falsechicken** [minetest/minetest#2364]
I cannot seem to build Minetest anymore. I recently switched from ElementaryOS (Based on Ubuntu 12.04) to Mint Xfce 17.1 (Based on Ubuntu 14.04) and I think that has something to do with it. I have not been able to build since. Even tried building the last version I know I could build before I switched (Stable 0.4.11) with the same problem. All dependencies installed correctly as far as I can tell. Any suggestions? 

```
[ 92%] Building CXX object src/CMakeFiles/minetest.dir/treegen.cpp.o
[ 93%] Building CXX object src/CMakeFiles/minetest.dir/version.cpp.o
[ 93%] Building CXX object src/CMakeFiles/minetest.dir/voxel.cpp.o
[ 93%] Building CXX object src/CMakeFiles/minetest.dir/voxelalgorithms.cpp.o
make[2]: *** No rule to make target `/usr/lib/libIrrlicht.a', needed by `bin/minetest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 94%] Building CXX object src/CMakeFiles/minetest.dir/wieldmesh.cpp.o
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
make: *** [all] Error 2
```

Running Linux Mint Xfce 17.1 64bit using GCC 4.8.2. Thanks!

**Comment by nerzhul** [comment]
Have you install irrlicht-dev libs ?

**Comment by falsechicken** [comment]
The libirrlicht-dev package? Yes. I installed all the packages from the README without issue.

**Comment by falsechicken** [comment]
Hmmm... It seems to be an issue that is common with this version of Mint. I have a fresh install on my netbook that I just tried and it fails with the same problem.

**Comment by ShadowNinja** [comment]
Seems that Irrlicht isn't installed properly.  I'll close this soon if I don't hear otherwise.

**Comment by falsechicken** [comment]
Do you have any suggestions? I installed the packages just as the readme said.

**Comment by Zeno-** [comment]
Clear cmake cache and all related files and run cmake again?

**Comment by falsechicken** [comment]
Oh wow that worked! Thanks! Now that you mention it I see why this would happen my two seperate machines. The repo folder is synced via OwnCloud to the two machines. So the cache was the same xD. Thank you!

**Comment by Zeno-** [comment]
;)
