### ISSUE TITLE
minetest.serialize doesn't serialize floating-point numbers properly

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#2365]
minetest.serialize and / or minetest.deserialize no longer persist stacked tables correctly. For example: If you set mytable.foo.bar = 1 and run it through minetest.serialize then fetch it through minetest.deserialize, mytable.foo.bar is now an invalid value. I don't know the exact commit at fault, but believe the issue was introduced approximately a week ago.

I noticed this in my Creatures mod: Several properties are persisted in mob's get_staticdata and set_staticdata functions. All of them work well except for one, which stores settings in stacked tables. This causes all mobs to have invalid settings after the server is restarted, making them sit there and do nothing. I made a commit to temporarily disable the persistence of this setting, and it shows where exactly the issue happens in my mod: https://github.com/MirceaKitsune/minetest_mods_creatures/commit/918652bea4e9eedb6b266bc42b8e4f36eb09f199

**Comment by t4im** [comment]
i can not reproduce this issue, the unit test seems to pass
please take a look at t4im/mtt@54be41a where it differs from your case and if you can, adapt it to fail

could this be a problem in a different spot?

**Comment by MirceaKitsune** [comment]
@t4im That's very weird. In this case someone who understands the issue better might have to take a look at my Creatures mod explicitly. If anyone wishes to test, please clone it from the link below. Make sure to first undo the commit I linked above however, which temporarily disables trait persistence to work around this issue!

https://github.com/MirceaKitsune/minetest_mods_creatures/

How to test: Create a new world with this mod enabled. Wander around until people begin to spawn. Once you see a human mob, walk up to them and right-click them. A menu will pop up which lists the personality traits of that individual... such as visual sight, attack skill, etc. Each of those traits is typically a number between 0 and 1. A screenshot of the menu in cause:

http://i.imgur.com/ND7zY2V.png

Now shut down Minetest and the server. Start it up again and log back into the world. Once the mob reappears, right click them again. You will notice that all values are now either 0 or INF, because the table was corrupted. In consequence, mobs will just sit there and no longer do anything.

The traits are stored as floats in a table called self.traits. For example, self.traits.fear = 0.75. The self.traits table is persisted in get_staticdata / set_staticdata, where it's of course ran through minetest.serialize and minetest.deserialize first.

**Comment by ShadowNinja** [comment]
I broke floating-point serialization with 47aca6f6d164347de950a46b11e1774445cdb9e3.  We'll need to use a hybrid so that both cases work.

**Comment by ShadowNinja** [comment]
Should be fixed by cd4324e5a800f12d4bbfea07a47d78e04eace920.  Can you confirm?

**Comment by MirceaKitsune** [comment]
Updated and tested. That fixes the bug, mob traits are persisted correctly again. Thanks!

**Comment by t4im** [comment]
It just migrates the problem.
Why not use %f instead of %d?

**Comment by t4im** [comment]
updated/added unittest and it passes now for floating points with a precision of 14 or lower
anything over 14 will however fail, but seems unfeasible to me anyway

**Comment by ShadowNinja** [comment]
@t4im Because `%f` adds extra trailing zeros, eg `0` becomes `0.000000`.  That's a waste of space and I don't know how to disable that behavior.
