### ISSUE TITLE
Bug when looking downwards

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2369]
When looking downwards, the sky goes black. This started to happen a long time ago for me, and it may affect new players.

Hey look! I figured out how to get a screenshot up with githubusercontent.com!
![screenshot_2893063681](https://cloud.githubusercontent.com/assets/9893266/6314331/6849ee4c-b9a0-11e4-8ef6-957ebf3782c1.png)

**Comment by SmallJoker** [comment]
IIRC, that's a feature of Irrlicht, not Minetest.

**Comment by C1ffisme** [comment]
@SmallJoker Do you mean "feature" by:
* **Sarcastic**: You meant it as a joke. It's really a bug.
* **No really**: This is meant to be so.

If it's a real feature, I wonder what the developers for Irrlict were **thinking**.

Why am I suddenly using **bold text** a lot?

**Comment by SmallJoker** [comment]
I think that's a bug where Irrlicht tries to render many, many nodes and each node down there gets darker and darker.

**Comment by ShadowNinja** [comment]
I remember looking at the code that did this when making my inside-node-blacks-screen patch.  I thought it was weird, but assumed it was there for a reason.

**Comment by C1ffisme** [comment]
@SmallJoker It could be, but I'm not rendering more than 10 unwhole nodes in that picture.

**Comment by PilzAdam** [comment]
This is intended behavior when e.g. looking down a cave you don't want to see blue sky at the end.

**Comment by C1ffisme** [comment]
@PilzAdam True, but you can't exactly see clouds at the bottom, just blue. Maybe the sky should have a horizon?

**Comment by paramat** [comment]
PilzAdam is correct, below sea level the default light level of a mapchunk is set to dark, the game makes the skybox dark when the majority of mapchunks the player is looking at are dark. To avoid this in your singlenode or custom worlds set water_level to -31000.

**Comment by C1ffisme** [comment]
@paramat Seems annoying to do this for every world, why not have a fix for this? Make the game look good.
