### ISSUE TITLE
crafting is slow

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2379]
this [minimal](https://gist.github.com/est31/e477d9a624dced5cb274) speed test (simulating dreambuilder conditions) outputs for me:
```
filling up the craft table...
time spent registering: 394685
starting the crafting loop... 
us time spent looking up: 7185114
ms spent per craft lookup: 143.70228
```
140 ms per lookup is too slow. People crafting whole stacks can cause lags. One way to optimize crafting would be to store the craft definitions in different containers: all recipes without groups (a majority) should get a "hash" which identifies the input grid, the hash for shapeless recipes should base on an normalized input grid, where all inputs are sorted by name and stacksize. They should be stored inside two maps, one which resolves shaped recipes based on that hash, and one for shapeless recipes. On crafting, the shaped map gets looked up. If there is a fail, the shapeless map gets looked up with an normalized input grid. If that still fails, a list with all group recipes is iterated.

Another way would be to cache the last craft inside a player-global variable. Most times there is only one player crafting whole stacks.

**Comment by nerzhul** [comment]
In fact inventory is very slow and need to be rewritten

**Comment by CasimirKaPazi** [comment]
I also find it strange that when crafting ten of something it is crafted ten times, instead of ten units on time.

**Comment by est31** [comment]
@CasimirKaPazi This is a balance question. There are mods that off-load crafting to machines like autocrafters or workshops, but no mod makes the crafting happen instantly.

**Comment by CasimirKaPazi** [comment]
I was referring to the middle click feature. Where you can craft ten of a kind, instead of only one.

**Comment by est31** [comment]
ah ok, didnt knew of that feature :)

**Comment by hunter688** [comment]
This issue will be fine add to Roadmap #2370 

Smoother game will attract more players/testers...

**Comment by est31** [comment]
The output of [this stats script](https://gist.github.com/est31/406f939396c4d110f330) on dreambuilder:
```
grouped: 6 non-grouped: 17478 type stats: {
        cooking = 148,
        shapeless = 9400,
        toolrepair = 2,
        fuel = 398,
        default = 7536
}
```
In this context, default means shaped. This is quite notable, as, given the vast number of dreambuilder craft recipes, only 6 are grouped.

**Comment by est31** [comment]
334e70455b7f8a4607fe99dc12710d48169113a6
