### ISSUE TITLE
Calling minetest.chat_send_all in minetest.register_on_newplayer causes hanging

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2383]
Noticed while developing my capture the flag subgame.

![hanging](https://cloud.githubusercontent.com/assets/2122943/6336349/e39ac85a-bb99-11e4-947c-06ed8bfb25d1.png)

Pressing ctrl+c on server prints

     ^C20:24:09: INFO: sigint_handler(): Ctrl-C pressed, shutting down.

But nothing else. Server doesn't close. No error messages.

Minimal example, install as init.lua in a mod:

```Lua
minetest.register_on_newplayer(function(player)
	minetest.chat_send_all(" has joined")
end)
```

No hanging when using minetest.register_on_joinplayer.

**Comment by rubenwardy** [comment]
Back trace of client: https://gist.github.com/rubenwardy/b9bbb98d89f345a7d083
Server is in "usleep" whenever I backtrace it.

**Comment by rubenwardy** [comment]
No longer a problem on latest master.

**Comment by nerzhul** [comment]
I fixed a deadlock similar as you show yesterday

**Comment by rubenwardy** [comment]
Awesome. Thank you very much.
