### ISSUE TITLE
Saner raillike group handling

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2385]
Problem:
The current way how raillike nodes are connected is pretty unflexible.
We currently only have these two options:

* Creating one node which is only able to connect to the same node type
* Putting the node into the group `connect_to_raillike`, but then *all* nodes in this group will connect to this

It is not possible to have multiple “connection” groups which will only connect to nodes in the same group
i.e. 5 rail nodes and 2 gunpowder nodes (gunpowder trails).

My idea on how to tackle this:

Extend the current group `connect_to_raillike`. Nodes are considered to be in the same “connection” group not just if they are member of this group but also if they use the same group value. Different group values denote a different “connection” group, these nodes will not be connected.

The modder should not be bothered to assign a number manually, actually, modders should never use it manually. Instead it is handled by using a function:
`minetest.raillike_connect_group(name)`
(stupid name, I know)

`name` is a string and an unique name for the connection group. This name must be communicated between modders. 

Internally, this function should work like this: There is a counter variable `x` which starts at 0.
If the function is called with an unknown name, `x` is incremented and the name is is stored in a name/value dictionary as the tuple (`name`, `x`). Then the function returns `x`.
If the function is called with a known name (the name is found in the dictionary), it will simply return the value of the key.

Here is an example on how it could be used in practice. Suppose we have 5 rail nodes and 2 gundpowder nodes. We want the rails to connect to other rails and the gunpowder connect to other gunpoweder, but we do not want rails to connect to gunpowder.

In the node definitions of the rails we write:
`groups = { connect_to_raillike = minetest.raillike_connect_group("rail") },`

Similar for the gunpowder:
`groups = { connect_to_raillike = minetest.raillike_connect_group("gunpowder") },`

That's all from the modder side to do.

In practice, the rail nodes could be resolved to `connect_to-raillike =1` and the gunpowder to `connect_to_raillike=2`, but the numbers could also differ each time the server is run because of different loading order etc. But since the modder does not have to bother with these numbers and it only matters if the numbers are equal or not, it should not be a problem.

Note that connection groups are different from Minetest's group system.

This issue has been created as feature request so that this minetest_game PR can be reworked in a sane way:
https://github.com/minetest/minetest_game/pull/435

**Comment by BlockMen** [comment]
https://github.com/BlockMen/minetest/commit/24f3dc018db94cea62fb387b67112035b14aa8ed

**Comment by BlockMen** [comment]
https://github.com/minetest/minetest/commit/b65c7ab4a43b082fd798eded3ca3c67fb66fad3f
