### ISSUE TITLE
Change in Particle Code is Causing Visual Glitches

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#2388]
**Minetest Engine Commit:**   b4acac706dae66be3ddc3f0a291097ca175417f7
**Minetest_game Commit:**  minetest/minetest_game@3b526a72769cff4ef9296725d4148d8291ab0bb3

**Problem Commit:**  c09d026f0561ee3c6db821a7e193716f724a0e4a

**Setup**
* Linux Compile *(Ubuntu 14.10)*
* OpenGL 4.4.0
* Default Texture Pack
* Settings Tab:
     - 2nd column - "no filter", "mipmap + aniso filter", "rendering opengl"
     - 3rd column - yes shaders, no bumpmapping, no generate normalmaps, no parallax occlusion, yes waving water, yes waving leaves, yes waving plants

I took "after" particle change screenshots with engine commit b4acac7 and then made a new compiled version where I had commented out the two lines added to engine commit c09d026 and took "before" particle change screenshots of the same locations/items.

Two things happen:
1. Particles with transparencies show through clouds to the blue sky.
2. Enabled node highlighing causes some nodes to disappear. Note in the screenshots where the node disappears, that the node highlight *is* present around the node and the debug displays the "modname:nodename texture.png" of the glicthed-invisible node.

**BEFORE Particle Change - Smoke Particles**
 ![Smoke Before Particle Change](http://i.imgur.com/hXgFULB.png)

**AFTER Particle Change - Smoke Particles**
 ![Smoke AFTER Particle Change](http://i.imgur.com/YdlfEKn.png)

**BEFORE Particle Change - Node Highlight HomeDecor Door**
![HomeDecor Door BEFORE Particle Change](http://i.imgur.com/wpE8QSS.png)

**AFTER Particle Change - Node Highlight HomeDecor Door**
![HomeDecor Door AFTER Particle Change](http://i.imgur.com/8kxSFen.png)

**BEFORE Particle Change - Node Highlight HomeDecor Curtain**
![HomeDecor Curtain BEFORE Particle Change](http://i.imgur.com/ALPhpAV.png)

**AFTER Particle Change - Node Highlight HomeDecor Door**
![HomeDecor Door AFTER Particle Change](http://i.imgur.com/Sb9iBN4.png)

**Comment by C1ffisme** [comment]
Odd. I don't know what node highlighting has to do with node visuals and particles.

**Comment by nerzhul** [comment]
Reverted. thanks for your report. I tested and you are right.

**Comment by BlockMen** [comment]
It was nox fixed by reverting the commit, it just hides other problems with draworder in minetest!

@LazyJ please test  #2406 and report possible problems

**Comment by MT-Modder** [comment]
Visuals seem to be getting worse and worse ever since that wield glitch popped up.

**Comment by BlockMen** [comment]
@MT-Modder this is not realated to the wielded glitch

**Comment by MT-Modder** [comment]
Oh, but don't you agree?

**Comment by LazyJ** [comment]
@BlockMen 

**Minetest Engine Pull Request:**   #2406 
**Minetest_Game Commit:**   e604d8d

It works!

The smoke particles aren't displaying as blue holes in the clouds and the HomeDecor doors and curtains don't become invisible when enable_node_highlighting is used.

Thank you ;)

**Comment by BlockMen** [comment]
36e8ba9ce2d9eafb1f36e76e86113ed47afe8f7f
