### ISSUE TITLE
How do I get 0.4.12

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#2392]
How can I get 0.4.12 from git
everytime I Pull I still get 0.4.11 even if I delete the minetest sourcefolde.
pulling stable-0.4 does not help either.
Even git pull --tags 0.4.12 only says insufficient rights or no such repository.
Thanks,
JPR

**Comment by SmallJoker** [comment]
You can use the command `git checkout 1.1.4`

Source: http://stackoverflow.com/questions/4330610/switch-to-another-git-tag

**Comment by JPRuehmann** [comment]
Thanks that helped.
JPR

**Comment by rubenwardy** [comment]
The checking of Minetest versions is broken due to the new way of releasing.

**Comment by nerzhul** [comment]
Solved
