### ISSUE TITLE
Liquids aren't updating fast enough for my liking.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2397]
I don't need to say much. Water and lava never seem to update properly. If you try to put some lava around the edges of a river that seperates your bases in PVP, the lava takes a very long time to flow. I'm really tired of seeing this bug, because in Minecraft, water and lava flow almost instantly when updated. You don't have to wait a whole minute for your river to be filled with lava. Can we please try to improve water speed?

**Comment by ShadowNinja** [comment]
`liquid_update = 0.1`

**Comment by C1ffisme** [comment]
That seems to heat up my laptop. Maybe the code for liquids needs some CPU friendly updates. Maybe VoxelManip should preform water flow? There is no reason to heat a computer to 80 Celcius for water. Even then it seems rather slow, which may be a node update problem.

**Comment by ShadowNinja** [comment]
The liquid updates are known to be heavy, but that's a separate issue.  It's probably the main reason the updates are slow by default.

**Comment by C1ffisme** [comment]
Someone needs to rewrite minetest. A lot.

**Comment by proller** [comment]
fixed in freeminer ;)
