### ISSUE TITLE
Lava doesnt flow correct

### ISSUE THREAD

**Issue by BlockMen** [minetest/minetest#2399]
Lava doesnt flow correct (x+, z+) when between water and lava is one block air:
![screenshot_40070664](https://cloud.githubusercontent.com/assets/3742497/6420700/c6a7958e-bec8-11e4-9a00-64d92c7f5f28.png)
https://github.com/minetest/minetest_game/issues/425

**Comment by C1ffisme** [comment]
Did you know, I also tried to make an automatic rebuilding wall which was stopped by this bug.

Someone should try and bisect this.

**Comment by paramat** [comment]
Gregorycu has worked on liquid flow and may be able to help.

**Comment by est31** [comment]
@gregorycu

**Comment by alexeysvrv** [comment]
Who can fix it? I want create stone generator...

**Comment by Fixer-007** [comment]
This bug is not fixed yet. You can make different stone generators.

**Comment by DS-Minetest** [comment]
this bug happens with all combinations of different liquid types
![screenshot_20161217_205100](https://cloud.githubusercontent.com/assets/7613443/21289374/64e05616-c49c-11e6-8247-233245b0c945.png)

i also found out that there the liquid flowing to west(-x) is not normal
![screenshot_20161217_202207](https://cloud.githubusercontent.com/assets/7613443/21289373/64dd4372-c49c-11e6-8b85-b32b6752d36c.png)
![screenshot_20161217_204842](https://cloud.githubusercontent.com/assets/7613443/21289375/64e25060-c49c-11e6-8455-764ab88e16c1.png)

it also doesnt flow down in the south(-z)
![screenshot_20161217_210717](https://cloud.githubusercontent.com/assets/7613443/21289405/29be4ede-c49d-11e6-8f21-ade1d8c960dd.png)

**Comment by alexeysvrv** [comment]
I hope to get to release 0.4.15 fix this bug.

**Comment by Fixer-007** [comment]
This bug still appears as of f840839

**Comment by Wuzzy2** [comment]
More info on liquids refusing to flow into a particular direction, copied from #5802:

> If you have a liquid, and in the +X direction of that block is air, the liquid refuses to flow towards +X if below that air block there is a liquid block of a different type.
>
> Illustration with compass:
> 
> ![Example showing missing liquid flow to -X](https://i.imgur.com/3WVG5vb.png)
>
> This example uses water and river water from Minetest Game. It is the same if I swap their positions. The top liquid never flows.
> 
> Proof that this the liquid flow on top of another liquid works in all directions but one:
> ![Screenshot showing the bug that the liquid refuses to flow into +X](https://i.imgur.com/pTiUuU2.png)

> How to reproduce:
> * Replicate the glass structure in the 1st screenshot, keep the compass in mind and use debug mode to learn the correct orientation
> * First place the bottom liquid, then the top one

> According to my tests, this seems independent of subgames. Rotating above build into any other direction makes the top liquid flow.
> 
> It doesn't make a difference if either of the liquid is flowing or source:
> 
> ![Second example of the bug](https://i.imgur.com/ESb6FTw.png)
> 
> Tested in: 0.4.15

**Comment by paramat** [comment]
Also see #3263 for more examples of unusual flow near 2 liquids.

**Comment by azekillDIABLO** [comment]
It also does this on flat ground too:
![screenshot_20180309_104635](https://user-images.githubusercontent.com/17685062/37201181-39da3266-2387-11e8-8cb8-b79ae4f28708.jpeg)
![screenshot_20180309_104639](https://user-images.githubusercontent.com/17685062/37201182-39f9e016-2387-11e8-9c68-64606dcb3830.jpeg)
![screenshot_20180309_104351](https://user-images.githubusercontent.com/17685062/37201183-3a1709e8-2387-11e8-910b-73582f8a03ae.jpeg)

**Comment by oilboi** [comment]
Oi

**Comment by leorockway** [comment]
Just wanted to confirm this is still happening. Here's a cobblestone generator from vanilla minetest game. On one side, I get cobble, on the other the flow stops and nothing is generated. Same setup, just rotated 180 degrees.
![cobblegenerator](https://i.imgur.com/U9YWZPz.png)

**Comment by leorockway** [comment]
#9874 fixed this for me. I don't know what other testing to try for any other regressions, but at least it's evident that the same setup (same world) is now producing cobblestones on both sides:
![fixed](https://i.imgur.com/aAtUjhW.png)
