### ISSUE TITLE
name of a new world

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#2407]
So apparently there is no character filtering when you give a name to your new world.
I was able to enter "../test é(-è_" resulting in a crappy folder located outside "minetest/worlds"

Even if this can't be used for directory traversal attacks (you can only harm yourself), it allows bad habits like spaces and special characters in directory names.

Thing is, I wanted to get the current worldname by keeping the last string after the latest "/" (or "\" f* u MSDOS) to create a centralized table with world_specific configs.
But I realised how poor this approach is if players have chaotic world names.

My ideas : 
- add a minetest.get_worldname() ; returns a string with current world name
- add a name field in world.mt with the user-inputted wordname (with every possible crap) but save the actual world with a filtered name containing only a-zA-Z0-9

What do you think ?

**Comment by indriApollo** [comment]
I'm also confused : will the new security policy allow mods to read/write world.mt and write own files in the worldpath ? If so, I could save my world specific configs to the world directory.

**Comment by ShadowNinja** [comment]
@indriApollo Yes, you will be able to access files in the world path, including world.mt (although you probably shouldn't touch that file).

**Comment by indriApollo** [comment]
The point about bad world names is still valid.
