### ISSUE TITLE
Draw and react to signals while loading

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2409]
Neither closing or sending `SIGINT` to a loading minetest client can stop it. Also, when I put another window over the client window, and put it back, the client window doesn't draw over. The client should do both.

**Comment by est31** [comment]
related to #1665.

**Comment by JakubVanek** [comment]
Graphical glitch: Loading screen "viewport" isn't updated when window was resized, it's stuck in bottom-left corner.
