### ISSUE TITLE
Configurable chat position in client

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2417]
Will be possible allow user change position of chat? For example I prefer Minecraft style, lower left corner instead upper left.

**Comment by indriApollo** [comment]
Also make it's font bigger and add some opacity to improve readability

**Comment by crazyR14** [comment]
yeah this sounds good. id like to have the ability to create a chat that can slide out from the side. but we're probably a long long way from being able to customize it this much

**Comment by hunter688** [comment]
#3933

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by hunter688** [comment]
When nobody interested in coding, any feature request will be closed? LOL. Great idea.

**Comment by paramat** [comment]
If no-one is interested in coding it after 2.5 years, and it is completely unnecessary, yes.
Chat is fine where it is, highup means it obscures less important stuff (sky) and is away from the hotbar which it would have to be above, therefore obscuring much more important stuff.
In fact, thinking about it this way, this is an obvious close.

**Comment by paramat** [comment]
:-1: Seems unnecessary, lower down it will obscure more important stuff, and will need to be above the hotbar, making it more obtrusive.
