### ISSUE TITLE
Cannot press key "4" in Minetest

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2422]
When pressing key "4" in Minetest, its like pressed Enter, no character written.

Also Numeric keyboard does not work.

Using Fedora 21 Linux, Gnome3, issue is in the Minetest only.

Console log show only this, no errors:
```
[hunterz@dusan bin]$ ./minetest
Automatically selecting world at [/home/hunterz/minetest/bin/../worlds/worldik]
Irrlicht log: Irrlicht Engine version 1.8.1
Irrlicht log: Linux 3.18.7-200.fc21.x86_64 #1 SMP Wed Feb 11 21:53:17 UTC 2015 x86_64
Irrlicht log: Creating X window...
Irrlicht log: Using renderer: OpenGL 3.3.0
Irrlicht log: GeForce GT 330M/PCIe/SSE2: NVIDIA Corporation
Irrlicht log: OpenGL driver version is 1.2 or better.
Irrlicht log: Dedicated video memory (kB): 1048576
Irrlicht log: Total video memory (kB): 1048576
Irrlicht log: Available video memory (kB): 912080
Irrlicht log: GLSL version: 3.3
```

**Comment by indriApollo** [comment]
Lucky you, mine is the '7'

**Comment by LeMagnesium** [comment]
It happens sometimes that some numbers' keys don't work... apparently it's because of Irrlicht... (mine is 7 too, forced to use localhost instead of 127.0.0.1). It's a problem, but we can't do anything if I remember correctly...

**Comment by RobertZenz** [comment]
Possible duplicate of #1898.

**Comment by hunter688** [comment]
Yes irrlicht bug....

http://irrlicht.sourceforge.net/forum/viewtopic.php?f=7&t=50491
