### ISSUE TITLE
Support for SVG icons for subgames

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2423]
Hi!
I suggest to use SVG icons for subgame icons as an alternative to PNGs.
Since the GUI is scalable, this seems not too far-fetched.

This would also solve all scaling issues with subgame icons.

I know that SVG is a complex format, but SVG has the concept of profiles, where some profiles are minimalistic and provide less functionality.
So maybe only the tiny profile could be supported to minimize code overhead?

To reduce load times, renders of complex SVGs could be cached for later use.

**Comment by RHRhino** [comment]
I don't know how difficult SVG support is, but it would be also a nice feature if you want to create smooth texures without using 256x256px graphics or even higher.

**Comment by rubenwardy** [comment]
Sort of a duplicate for #2419

**Comment by kilbith** [comment]
Irrlicht does not support loading and rendering of SVG's (atm) : http://irrlicht.sourceforge.net/features/

**Comment by nerzhul** [comment]
Duplicate #2419 .
