### ISSUE TITLE
Minetest closes when double-clicking on the background of the main menu

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2425]
When you are in the main menu and double-click on the background, Minetest closes.

This comes probably unexpected for many users which accidentally/unknowingly double-click the background and think that Minetest just crashed for no reason.
Also, it is a very unusual and annoying behavior for a program to close in such a way, the vast majority of video games for PC does not behave this way. There is no reason for Minetest to deviate from the de-facto norm.

I request to remove the weird behavior.

**Comment by ExeterDad** [comment]
This behavior was added as a feature when the Android version was being developed. It is a way to exit Minetest in Android. It is also a useful way to exit a formspec in game.

**Comment by Zeno-** [comment]
I think that we have so many reports regarding this feature that we should remove it for non-android builds

**Comment by nerzhul** [comment]
:+1: @Zeno-

**Comment by PilzAdam** [comment]
:+1: @Zeno-

**Comment by C1ffisme** [comment]
:+1: @Zeno-

**Comment by MoNTE48** [comment]
:+1: @Zeno-

**Comment by Heybye44** [comment]
:+1: I think it might be crashing Minetest on my PC.



—

**Comment by Zeno-** [comment]
commit 76177c80d0859f3ed4b954a3cedd43789ca99283

(still enabled for Android for now)
