### ISSUE TITLE
Tooltips display escaped formspec strings incorrectly

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2428]
In 038d3a31 (after 0.4.12), tooltips (formspec element) are incapable of accepting escaped strings.

They display the string with complete disregard for escape sequences.

To test, create a minimal mod with only the file `init.lua` with this content:

```
minetest.register_on_joinplayer(function(player)
	local test = [=[\;\,\[\]]=]	-- Properly escaped formspec string, should result in “;,[]”
	local formspec = "size[6,6]label[1,1;Reference: "..test.."]button[1,2;2,1;button;Hover me!]tooltip[button;Test string: "..test.."]"
	minetest.show_formspec(player:get_player_name(), "test_formspec", formspec)
end)
```

Then start a world with this mod enabled. A formspec will appear. First read the label, then hover the button and read the tooltip. Did both contain the substring “`;,[]`”? Then everything works as it should, you were unable to reproduce the bug.
But if one of them did *not*, you have reproduced the bug.

Explanation of the code:
This will show a formspec immediately after joining and shows a label and a button. The button has a tooltip, the label is only there for comparision. Both the label and the tooltip should display the same characters after the colon.
The variable `test` contains a few characters which have been properly escaped for formspecs: `\;\,\[\]`

Thus the characters in test must be displayed in the formspec as:
`;,[]`

In my test, the label displays the characters “`;,[]`”, which is correct.
But the tooltip displays the characters as “`\;\,\[\]`”, which is incorrect.

**Comment by nerzhul** [comment]
#2472 fixed the problem. thanks
