### ISSUE TITLE
Breaking animation for multi-node objects

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2432]
If you punch a multi node object like the piano from homedecor the braking animation is only applied to the node on the left, the one that you place. Same thing for beds.

The braking animation should indicate that you remove the object and not one node of it. 

![auswahl_074](https://cloud.githubusercontent.com/assets/1377943/6497553/a4ed3a26-c2e1-11e4-9443-ab03a2ed1afb.png)

**Comment by C1ffisme** [comment]
It's more of a problem with how the node is registered. It's really 2 nodes. I suppose you could ask Vannessa to use one node with a multi-node nodebox.

**Comment by lightonflux** [comment]
Just want to add that many mods do that. 

 * travelnet
 * beds
 * connected_chests
 * homedecor
 * computer (block: server rack)
 * gemalde
 * default (block: doors) but the animation is where you point at

**Comment by PilzAdam** [comment]
There is no way for the engine to know if two nodes next to each other are supposed to represent one "object", so detecting this is currently not possible.

**Comment by ShadowNinja** [comment]
You can fix this by using a node box / mesh that's sized to two nodes.

**Comment by VanessaE** [comment]
For the objects that are comprised of two nodes in Home Decor and my other mods, indeed meshes will be used in the future.  However it IS possible to detect which nodes are connect:  look at the selection box when applying the breaking animation, and apply it to all nodes that the box encompasses.

**Comment by paramat** [comment]
^ Possible but overcomplex for something done per punch.
:-1:
