### ISSUE TITLE
Allow multiple alternate textures per node

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2433]
I've been thinking about this for bookshelves. This would mean every block, there would be a randomness involved in the textures. There is (I suppose) a way to do this without an engine feature, such as placing a random block on_place. But, that would use several blocks.

What I'm suggesting is, add another way to register tiles. It would look like this.
```tiles = {{"texture_front_1.png","texture_front_2.png","texture_front_3.png"},{"texture_side_1.png","texture_side_2.png"}}```
Now, the C++ code would check for sub tables, and if found, it would take the sub-table and apply a random one of these textures is applies to the node. Now, if this happened every view update, this would be extremely slow, and all the nodes would switch textures very quickly. So I suggest the texture chosen is stored in a node's meta and used for the texture.

**Comment by PilzAdam** [comment]
A better way would be to do this like sound files: each texture can have multiple versions (texturename.png, texturename.1.png, ...). This way it's possible that texture packs supply more textures than the mod defines.

**Comment by C1ffisme** [comment]
That's a good idea.

I'm just thinking that if you look at bookshelves, you see the same books again and again. A bit of randomness might fix this.

**Comment by paramat** [comment]
See #2746

**Comment by tobyplowy** [comment]
@C1ffisme will this ever happen?

**Comment by tobyplowy** [comment]
@C1ffisme @paramat  will this ever happen?

**Comment by paramat** [comment]
I think #2746 is a better method for this.
It happens if someone codes it.

**Comment by paramat** [comment]
I re-opened #2746 for reasons given, closing this as the duplicate. Please move discussion there.
