### ISSUE TITLE
Freeze while leaving server

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2437]
Last commit : cd684497
```
In thread 7f11af92d880:
/home/jp/git/minetest/src/script/cpp_api/s_base.cpp:75: ScriptApiBase::ScriptApiBase(): Assertion 'm_luastack' failed.
Debug stacks:
DEBUG STACK FOR THREAD 7f11af92d880:
#0  int main(int, char**)
(Leftover data: #1  void ClientMap::renderMap(irr::video::IVideoDriver*, irr::s32))
(Leftover data: #2  virtual void ClientEnvironment::step(float))
(Leftover data: #3  void Client::Receive())
(Leftover data: #4  void Client::ProcessData(irr::u8*, irr::u32, irr::u16))
(Leftover data: #5  void MeshUpdateQueue::addBlock(v3s16, MeshMakeData*, bool, bool))
Abandon (core dumped)
```

**Comment by Zeno-** [comment]
I cannot reproduce...

**Comment by kilbith** [comment]
It happens not systematically, but sometimes.

**Comment by Zeno-** [comment]
> It happens not systematically, but sometimes.

Oh, you mean the really nice kind of bug :)

**Comment by nerzhul** [comment]
Code triggering assert:

m_luastack = luaL_newstate();
assert(m_luastack);

This will be difficult

**Comment by nerzhul** [comment]
NULL because of oom ?

http://www.fxcodebase.com/documents/IndicoreSDK/lua/luaL_newstate.html

**Comment by ShadowNinja** [comment]
This is known to happen under LuaJIT when running in valgrind when LuaJIT wasn't compiled with valgrind support.  Are you using LuaJIT?

**Comment by kilbith** [comment]
@ShadowNinja Yes, I use LuaJIT.

**Comment by Zeno-** [comment]
@kilbith you don't use valgrind though do you?

**Comment by kilbith** [comment]
@Zeno- Nope.
