### ISSUE TITLE
Freeze and crash while respawning

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2441]
Last commit : 0d1eedc

Whenever you die, then you click on "Respawn" the client is freezing and crash on that error : 

> Segmentation fault (core dumped)

**Comment by nerzhul** [comment]
Please test by launching gdb and give us the backtrace

**Comment by nerzhul** [comment]
0x0000000000845a20 in ClientEnvironment::step (this=0x2d6eef0, dtime=0.0160000008) at /home/nerzhul/Devel/minetest/src/environment.cpp:2389
2389			simple->step(dtime);

**Comment by Zeno-** [comment]
commit b214cde5b4a833e1826ec6850b95bf1938c8b0a0 is the issue

**Comment by nerzhul** [comment]
I will push a fix for it. You are right this is the conversion from list to vector which is the problem there.
I push it now
