### ISSUE TITLE
minetest.set_node() Problem

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2444]
This is really, really odd. I was making a pull to minetest_game, and I made this:

```
minetest.register_node("farming:pie", {
	description = "Apple Pie",
	tiles = {"farming_pie_top.png","farming_pie_bottom.png","farming_pie_side.png"},
	is_ground_content = false,
	drawtype = "nodebox",
	paramtype = "light",
	groups = {crumbly=3},
	sounds = default.node_sound_leaves_defaults(),
	node_box = {
		type = "fixed",
		fixed = {-0.5, -0.5, -0.5, 0.5, 0, 0.5},
	},
	on_rightclick = function(pos,node,player)
		local health = player:get_hp()
		player:set_hp(health + 5)
		minetest.set_node(pos,{node="farming:pie_half"})
	end,
})
```

And when I rightclick, I get the strangest error ever:
```
14:35:00: ERROR[main]: ServerError: ....minetest/games/minetest_game-pie/mods/farming/nodes.lua:106: bad argument #4 to 'set_node' (string expected, got nil)
14:35:00: ERROR[main]: stack traceback:
14:35:00: ERROR[main]: 	[C]: in function 'set_node'
14:35:00: ERROR[main]: 	....minetest/games/minetest_game-pie/mods/farming/nodes.lua:106: in function 'on_rightclick'
14:35:00: ERROR[main]: 	/usr/share/minetest/builtin/game/item.lua:326: in function </usr/share/minetest/builtin/game/item.lua:319>
```
Notice the first line? I'm pretty sure that minetest.set_node does not have 4 arguments. And when I tried to change minetest.set_node to this:

```
minetest.set_node(pos,{node="farming:pie_half",nil,blah})
```

I got a similar error that said argument 6 was missing. Which can only mean something very fishy is going on.

**Comment by LeMagnesium** [comment]
The only wrong thing I see here is : `minetest.set_node(pos, {node = "farming:pie_half"})`
However, the good name is "**name** =". The builtin functions are trying to place a node, with no name, and it can't handle it. Try with **name** = , but it's still odd the game can't warn you.

**Comment by kilbith** [comment]
Rubbish. RTFM next time : http://dev.minetest.net/minetest.set_node

**Comment by C1ffisme** [comment]
Okay. Another case of my bad eyes. :tongue:  Sorry about that.
