### ISSUE TITLE
Ugly cliffs that look like chunk borders.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2446]
![screenshot_3968080802](https://cloud.githubusercontent.com/assets/9893266/6518021/dbc6c8d4-c366-11e4-8d90-3509a2e39f3f.png)
![screenshot_3968089994](https://cloud.githubusercontent.com/assets/9893266/6518027/e5055b4a-c366-11e4-9ff4-4b7b59038f18.png)

Don't these look a little ugly? At least a little noise or detail would be appreaciated if this is intended.

**Comment by nerzhul** [comment]
Please tell us what is your mapgen

**Comment by LeMagnesium** [comment]
The default mapgen (v6) is known to have issues like these, random generation is sometimes buggy. However, I don't know if it's from the minetest_game's settings for v6, or the engine itself (of both).

**Comment by C1ffisme** [comment]
This is v6's mapgen. I just think these cliffs look BORING. It's too flat.

**Comment by LeMagnesium** [comment]
This  is a mapgen issue... Try to /deleteblock them and see if the land regenerates correctly. It's indeed chunck borders, I've seen a lot of things like this on many servers using mgV6 since 0.4.7, and even today.

**Comment by paramat** [comment]
Certainly a bug, mgv6 is not meant to do this but apparently occasionally does. Does it happen often for you? I can't remember the last time it happened to me.

**Comment by kwolekr** [comment]
We should compare current mapgen v6 output to a known good state.  Somebody could have inadvertently changed v6's generation, or maybe this is related to the seed problem I had created for about a week or so.
C1ffisme, could you create a new map with that same seed and re-visit the areas affected by those cliffs?

**Comment by C1ffisme** [comment]
![screenshot_1205502928](https://cloud.githubusercontent.com/assets/9893266/6787211/5138c12a-d15f-11e4-9dec-9c633042e165.png)

Huh, the cliff seems to have fixed itself.

**Comment by MT-Modder** [comment]
> Huh, the cliff seems to have fixed itself.

That seems like an even worse bug.

**Comment by C1ffisme** [comment]
No No no, this is a different world. You don't have to stay awake all night thinking that your chunks will delete themselves. XD

**Comment by MT-Modder** [comment]
Oh okay so it was just one of those fluke happenings.
