### ISSUE TITLE
Eating not updating hud

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#2449]
Since the previous daily (linux) when eating food it does not update the stack unless you try to move it to another grid or sign out and back into the game... e.g.  4 apples, eat 2, still says 4 apples... move to another grid, 2 apples...

**Comment by rubenwardy** [comment]
What happens if you try to eat 5?

**Comment by est31** [comment]
is it only a hud problem, or also a problem when you open the inventory?

**Comment by tenplus1** [comment]
Yep, also problem when opening inventory, items are still there until you move them to another grid...

**Comment by PilzAdam** [comment]
This might be because the server fails to send the event to the client. Are you using the master or dev-0.5 branch?

**Comment by tenplus1** [comment]
I'm using whatever this is: https://code.launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds/+packages

**Comment by poet-nohit** [comment]
I'm pretty sure I've narrowed this down to something exposed by this commit:

https://github.com/minetest/minetest/commit/1b2f64473ed4f222d3b7f02df853730d4382105e

How to reproduce:

Create a minimal world
giveme bucket
pick up and place water using the bucket

**Comment by MT-Modder** [comment]
I too have this problem with food and buckets.

**Comment by NathanSalapat** [comment]
I have this problem as well, using the daily PPA. I thought I was doing something wrong writing my mod, glad to see that others are having this problem as well.

**Comment by poet-nohit** [comment]
Turns out this was serverpackethandler.cpp. You have to do SendInventory() in both action == 3 and action == 4 setWieldedItem() call blocks or it won't work right.

**Comment by est31** [comment]
@poet-nohit, do you want to submit a pull request?

**Comment by poet-nohit** [comment]
I guess I could. Let me just look up how to do that...

**Comment by est31** [comment]
I can confirm that the issue isn't reproducable anymore for me. @poet-nohit good work!. You should perhaps make a nicer commit message, and do the pull request against `minetest/master`.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/7679396ebbb38115eedbfb8e9636dff50cdf2075
