### ISSUE TITLE
Android "touch free target" is finicky about targets above eye-level

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#2457]
Reproduced using a Samsung GT-P5113 running Android 4.2.2, minetest android debug build, version 5698e2b.  "Free touch target" enabled in settings.

When my view is centered below the horizon (I'm looking downward), I can't dig nodes above my eye level (top part of the screen).  When my view is centered above the horizon (facing upward), I can dig any node I can touch, as normal.

**Comment by Wayward1** [comment]
I haven't been able to reproduce this on Amazon Fire HD, latest Android release

**Comment by Warr1024** [comment]
It seems that my instructions to reproduce are not necessarily correct.  I haven't really been able to pin down a consistent pattern on what works and what doesn't work.  If I face a bunch of nodes and start digging them, and drag my finger across them to dig others, often a bunch of nodes (usually, it seems, near the top of my screen) are undiggable; I still get the swinging tool animation, but no digging action.  Changing the direction I'm facing seems to make those nodes diggable again, but it's definitely quite the annoyance.

**Comment by sapier** [comment]
There's still a max digging range even in touch free target mode. Could this be related to it?

**Comment by Warr1024** [comment]
It _could_ be a calculation error in max digging range checks, I suppose.  Pretty sure it's not correct behavior, since I can dig nodes that are farther away when it happens.
