### ISSUE TITLE
Fix break effect on player

### ISSUE THREAD

**Issue by netbun** [minetest/minetest#2461]
I've noticed when press and holding your cursor on a player, a break effect occurs as it would on any other normal block

**Comment by ShadowNinja** [comment]
I can't reproduce this with latest git (d75a0a73941259ea3ebac297803838094c7d458f).

I noticed that holding down the left mouse button causes continuous damage now though.

**Comment by netbun** [comment]
![screenshot from 2015-03-07 21 29 08](https://cloud.githubusercontent.com/assets/11084749/6544176/1e1b710c-c511-11e4-8ae7-1b4d19b10f30.png)

This is what appears to be happening, @ShadowNinja

**Comment by ShadowNinja** [comment]
@netbun: That's the smoke puff sprite.  It's generated on an object's death.  It should probably be removed though, since most entities shouldn't generate a smoke puff when they die.

**Comment by netbun** [comment]
@ShadowNinja  thanks for explaination, should this issue be closed?
