### ISSUE TITLE
minetest.generate_ores makes too many ores

### ISSUE THREAD

**Issue by Gael-de-Sailly** [minetest/minetest#2464]
I use the function `minetest.generate_ores(vm)` to add ores in my WIP Lua mapgen.
I've calculated (with `minetest.find_nodes_in_area`) that there are about 3 times more ores than in v6.
I can explain it by the emerged positions : the VoxelManip "overflows" a lot on the 6 faces of the chunk. So, at the border of a chunk, ores can be generated twice, or even 8 times on chunk corners !
What do you think about adding two parameters, like `minetest.generate_ores(vm, minp, maxp)` ? I understand partially the code, I think it's not a big rewrite but I can't code it myself.
[Code here](https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_mapgen.cpp#L810)

**Comment by paramat** [comment]
Certainly the ores should only be generated within the mapchunk, not throughout the mapchunk plus mapblock shell.

**Comment by paramat** [comment]
Okay i'm on it, seems a simple fix.

**Comment by paramat** [comment]
Merged and closing.
