### ISSUE TITLE
Android Working with inventory

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2465]
I propose to do the work with inventory in Minecraft PE. This will facilitate the stacks section and craft.
I will finance the one who will do it.
I will translate it to $ 500 on PayPal.

**Comment by indriApollo** [comment]
I think this is the place were you could post such requests :)
https://www.bountysource.com/teams/minetest

**Comment by MoNTE48** [comment]
@indriApollo, I disagree. I want to know to whom the money is going to work. All you are working on enthusiasm without getting anything. It's your hobby. I suggest you to capitalize on this. So you can devote more time to the project.

**Comment by neoascetic** [comment]
This is Minetest project repo, not Minecraft

**Comment by MoNTE48** [comment]
@neoascetic, and?

**Comment by nerzhul** [comment]
And i close.
