### ISSUE TITLE
Add possibility to disable particles for certain nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2466]
I suggest to add the possibility to disable particles appearing when you hit a node.

This could be done by extending the node definition by a field `particles`. It is a boolean. If it is `true`, particles are used, if it is `false`, no particles are shown. `true` is default.

There are some nodes where showing particles on mining them does not make much sense, for example fire, torches, other nodes with `dig_immediate=3`, etc.

**Comment by paramat** [comment]
Particles on some nodes don't make sense, but they're there for visual feedback, i doubt this feature is worth the complexity :-1:

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by paramat** [comment]
Old and no support, i don't think a new nodedef field is justified :-1:
