### ISSUE TITLE
Particles and entities become fully black when they are partially in a solid node

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2467]
If a particle somehow moves partially into a solid node, it becomes black!

IMO this is unexpected behavior and should not happen. Most of the time, modders probably don't want this.

Seen in Minetest 0.4.12.

![t19xaf8](https://user-images.githubusercontent.com/3686677/30358007-b1e8f460-9839-11e7-9599-7f61fc1d1342.png)

(Flare particle from a flare from the Simple Shooter [shooter] mod.)

**Comment by Dartmouth44** [comment]
Same thing for players in 3rd person view, as long as the upper half is also partially inside the ground the character is completely black.

[https://imgur.com/a/K13WV](https://imgur.com/a/K13WV)

**Comment by MT-Modder** [comment]
Objects are the same way.

**Comment by paramat** [comment]
Seems expected behaviour though, particles take on the lighting of the node they are in, otherwise they would be fullbright in dark air.

**Comment by MT-Modder** [comment]
I agree with paramat doesn't seem to be a bug.

**Comment by C1ffisme** [comment]
It is a logical error. The code works just fine, and it dosen't crash, but it's wrong. I think maybe particles/entities should have a variable like ```enable_lighting = true (or false)```.

**Comment by Wuzzy2** [comment]
I understand what paramat is saying. My problem is simply that it looks very ugly for many particles:
* Flare particles
* Snowflakes
* Raindrops
* etc.

Also, I am only talking about particles inside solid nodes and nothing about dark air. I suppose we can still darken particles in the shadow while retaning a sane brightness level when a particle is partially in a solid node. Correct me if I'm wrong.

**Comment by est31** [comment]
Can't we do something like
```
if node_we_are_in is conducting light then
    give us the light of the node we are in
else
    for loop over all 6 adjacent nodes
        if our selection box reaches into that node, give us the light of that node
    end
end
```
Of course that is still a hack. this should be done properly by giving every single part the lightning of the node we are in. So one part is inside some solid node, make that dark, another part is outside in air, give it as much light as the air has.
If we want to support VAEs we need this too I guess, if that doesn't need lightning overhaul already.

**Comment by paramat** [comment]
I guess what's happening is that particle collision detection can only be triggered when a particle's centre passes into a node, so even with collision detection on, the particles will inevitably go black for a moment before they bounce. A minor visual glitch (which we will get used to and might even add some lovable character to the game) is much more preferable than a complex processing heavy fix. SO i think best to keep it simple and live with a minor glitch.

**Comment by ShadowNinja** [comment]
@paramat: No, this isn't "lovable", it's ugly.

**Comment by C1ffisme** [comment]
@paramat Sorry, but we can't use lame "This is why I didn't do my homework" excuses to not make minetest pretty. I know it's hard to change minetest's C++ code, but if we want to have a fun game, you gotta code it.

**Comment by Fixer-007** [comment]
Same problem with entities.

**Comment by C1ffisme** [comment]
This is actually a problem with Minecraft's entities too, but Minecraft seems to have better hitbox code for entities and particles.

**Comment by Wuzzy2** [comment]
I can confirm what Fixer-007 said. I updated the issue name accordingly.

**Comment by C1ffisme** [comment]
I have at least a basic idea of how the rendering engine works, and I know that this might be difficult to make such that it isn't resource intensive, but I feel like we should have at least thought through this issue more 2 years ago...

**Comment by paramat** [comment]
I worked on this recently, each object has an internal point which determines the lighting for the whole particle/object, this point is at or near the centre as you would expect, if this point passes into a node the whole object goes dark. This is expected and due to this simple implementation.

Particles are slow enough and we can't make them slower by searching around for light. If we start using native Irrlicht particles we want hem to be very fast so a complex lighting implementation doesn't seem justified, and may not even be provided in Irrlicht.

I also don't think it's justified searching for nearby light for objects, as objects have collisionboxes that prevent them passing into solid nodes.
I would expect an object to go dark when it's centre is inside a dark node, because then it is mostly in darkness.

**Comment by paramat** [comment]
For particles, we now have 'glow', can this now be used to keep particles fullbright?
If not maybe we can have a particle bool that keeps it at a fixed light level even when underground? That would be a simple approach.

**Comment by paramat** [comment]
So this is undoable for particles which are slow enough already.

For entities, the only way to avoid this would be to sample light at at least 6 points at the centre of the collisionbox faces, this means 6 instead of 1 nodes have to be fetched for their light levels. Since entities have collisionboxes which stops them entering nodes there seems no point.

**Comment by paramat** [comment]
#6363 makes lighting customisable for objects.

**Comment by HybridDog** [comment]
> that requires multiple point light sampling.

You could do it only when the light is 0 and the player can see it.

**Comment by paramat** [comment]
PR #7626 will add a settable entity light sampling position, so is partial fix.

**Comment by paramat** [comment]
Idea mentioned in duplicate issue https://github.com/minetest/minetest/issues/9752#issuecomment-619440860
> taking the maximum light at four collisionbox points would be a noticeable improvement in many cases where an entity would otherwise be incorrectly shaded.
