### ISSUE TITLE
Death Loop bug

### ISSUE THREAD

**Issue by deezl** [minetest/minetest#2469]
On VanessaE's Creative server, somehow players were "killed" in a certain location, so they appeared "dead" (as in player model in laying down position). On subsequent logins of the player, they were greeted with the death screen upon emerging into the world, and after selecting "respawn" they remained "dead" and could still move around, but not interact with anything. The same issue remained even after the server was rolled back to stable-0.4 branch. The only way to fix it turned out to be to enabling damage for the server so that the players could actually finish dying and respawn with full hp. Another player reported in chat having experienced the same bug in singleplayer, also on near latest git. The bug occured while VE's server was running at: 9e675793155d7cd56bbd2222df7b45245008c647.
Some relevant messages from debug associated with this event:
>23:44:56: ERROR[ServerThread]: ServerEnv: Trying to store id=7560 statically but block (-43,1,-28) already contains 2653 objects. Forcing delete.
<VanessaE> 23:44:58: ERROR[ServerThread]: ServerEnv: Trying to store id=7561 statically but block (-43,1,-28) already contains 2653 objects. Forcing delete.
<VanessaE> 23:44:58: ERROR[ServerThread]: ServerEnv: Trying to store id=7562 statically but block >(-43,1,-28) already contains 2653 objects. Forcing delete.

And....:
>23:58:14: ERROR[ServerThread]: ServerEnv: Trying to store id=12639 statically but block (-19,1,-27) already contains 500 objects. Forcing delete.
<VanessaE> 23:58:16: ERROR[ServerThread]: ServerEnv: Trying to store id=12641 statically but block >(-43,1,-28) already contains 2677 objects. Forcing delete.

**Comment by deezl** [comment]
Also, the above "Forcing delete" mentions have been flooding debug on the server lately, and running clearobjects does not help. Not sure if this is related to the death loop issue, but the ERROR messages were occuring at the time of the bug.

**Comment by ShadowNinja** [comment]
Error messages are irrelevant.  The server simply shouldn't allow death if damage is disabled.

**Comment by nerzhul** [comment]
Partially fixed by b2801d8127f4b25fd96f981974763f33bc7ff42b which properly sent the HP or deathscreen on those servers when client connects.

**Comment by nerzhul** [comment]
Fixed: aaf26b3a4410c4a1dc2f4a8bb9c61122648fedf3
