### ISSUE TITLE
What does the crack:1:0 error message mean?

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#2473]
![Do you remember globis?](https://cloud.githubusercontent.com/assets/3192173/6582373/36c243c2-c75d-11e4-9d19-9277566ff902.png)
sometimes l get an error message that waiting for a texture with crack modifier timed out

**Comment by Wuzzy2** [comment]
I am not sure, but it probably means the crack texture is missing.
Your subgame needs to have `crack_anylength.png` in one of its mods.

**Comment by HybridDog** [comment]
the default's crack_anylength.png is available

**Comment by C1ffisme** [comment]
It's probably that too much lag happened, and the crack took too long to load up.
