### ISSUE TITLE
New texture gamecontrol Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#2474]
Since I'm sick of textures game control, which are used now, I asked my designer to offer something new.
Here are some of its variants.
Current version:

![left_arrow](https://cloud.githubusercontent.com/assets/6764600/6590936/41711528-c7c1-11e4-8c4d-c1e287e4b87b.png)

New ver: ![123_3](https://cloud.githubusercontent.com/assets/6764600/6590946/79757fa4-c7c1-11e4-9521-b717c5eb8485.png)

All graphics will be in png and svn.

License: I do not care. It's a small gift from MultiCraft, I do not claim these graphics.

**Comment by Zeno-** [comment]
Number 2 is best imo ... simple yet looks good

**Comment by MoNTE48** [comment]
I will ask my designer just draw other icons.
