### ISSUE TITLE
No texture load + timeout when lauch a map

### ISSUE THREAD

**Issue by racam** [minetest/minetest#2477]
Hi,
it's my first issue so I hope I do it the right way.

I'm on windows 8.1 and sometimes when I tried to play a map, I have got a gray screen with a black hand : no texture load I guess.
In consequence, I decided to run minetest with --info, and I found 2 differents trace : one with bug and one without.

Bug on right ; normal trace on left.
![capture](https://cloud.githubusercontent.com/assets/6368338/6602184/608fc9e6-c81a-11e4-9753-7b7271217eae.PNG)

When I run the game with --verbose I got this 2 lines that are spamming until the timeout
- 17:34:50: VERBOSE[ConnectionSend]: con(1484/1)RE-SENDING timed-out RELIABLE to 1 27.0.0.1(t/o=0.5): from_peer_id=1, channel=0, seqnum=65504
- 17:34:50: VERBOSE[ConnectionReceive]: con(1484/1)WARNING: ACKed packet not in ou tgoing queue

I tested it with differents builds (mine and other on the forum) and i got the same result + Minetest_game & minimal developpement kit.

The most weird with this bug is that sometimes it works, sometimes not.

**Comment by racam** [comment]
Hello,

I'm now on Windows 10 with the lastest version of minetest, and the bug seems to be gone. Impossible to reproduce the bug (same hardware except for a new ssd).

I don't know if you have made some changes in your hand-made udp-reliable protocol, but it seems to work better. I don't close this issue because I can't test it on Windows 8.1, moreover I don't know if you found & fix the bug and forget to mentioned it here. 

btw, I don't know if it's the right place to speak about networking, but is there any major changes schedule for the network part ? (in few words)

**Comment by nerzhul** [comment]
in fact the bug was fixed on this release cycle. Thanks for your return, closing
