### ISSUE TITLE
having trouble registering schematic decorations

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2481]
I used worldedit to make the .mts file. Normally I would just get the invalid schematic file error with no crash but ever since I updated a few days ago I get this longer error with a crash.

Here is the error:
```
19:18:03: ERROR[main]: loadSchematicFile: invalid schematic file
19:18:03: ERROR[main]: ========== ERROR FROM LUA ===========
19:18:03: ERROR[main]: Failed to load and run script from 
19:18:03: ERROR[main]: C:\Users\Thomas\Desktop\minetest_release\bin\..\mods\custom\biomes\init.lua:
19:18:03: ERROR[main]: caught (...)
19:18:03: ERROR[main]: stack traceback:
19:18:03: ERROR[main]: 	[C]: in function 'orig_reg_fn'
19:18:03: ERROR[main]: 	...esktop\minetest_release\bin\..\builtin\game\register.lua:388: in function 'register_decoration'
19:18:03: ERROR[main]: 	...ktop\minetest_release\bin\..\mods\custom\biomes\init.lua:3: in main chunk
19:18:03: ERROR[main]: ======= END OF ERROR FROM LUA ========
19:18:03: ERROR[main]: Server: Failed to load and run C:\Users\Thomas\Desktop\minetest_release\bin\..\mods\custom\biomes\init.lua
19:18:03: ERROR[main]: ModError: ModError: Failed to load and run C:\Users\Thomas\Desktop\minetest_release\bin\..\mods\custom\biomes\init.lua
```
Here is the file content: (It's small)
```
-- Biomes

minetest.register_decoration({
	deco_type = "schematic",
	place_on = {"default:dirt_with_grass"},
	sidelen = 16,
	noise_params = {
		offset = 0.04,
		scale = 0.02,
		spread = {x=250, y=250, z=250},
		seed = 436,
		octaves = 4,
		persist = 0.5
	},
	biomes = {"grassland"},
	y_min = -31000,
	y_max = 31000,
	schematic = "tree.mts",
})
```

**Comment by paramat** [comment]
Related to this, a year ago i could use .mts files created in Worldedit, more recently i have experienced this 'invalid schematic file' error.
So currently i am creating schematic decorations by lua tables, for trees in my biomes dev work.
Can anyone help? this is beyond my knowledge.

**Comment by MT-Modder** [comment]
I will submit an issue and reference this in the worldedit repository. The weird thing is I can place .mts files just fine, created using worldedit, using minetest.place_schematic() but not minetest.register_decoration().

**Comment by paramat** [comment]
Related to this ..
The .mts saving feature of Worldedit cannot set y-slice probabilities.
Also, it cannot place ignore nodes, and air cannot be punched to set it's probability, these are essential when creating force-placed schematics.
For the short term i would like to see some way to create .mts files from the type of lua table currently used to define schematic decorations. For small to medium structures lua tables are the fastest and easiest method to create schematics.

**Comment by MT-Modder** [comment]
When I wrote a small mod adding chat commands to create schematics I didn't have a enough knowledge of chat command parameters in order to use the totality of the ```minetest.create_schematic()``` function. Otherwise I would write the mod myself. In other words I'm young and have no life so I have loads of time to write something like this, but only with help from others. Even this, I think, wouldn't fix the schematic decoration problem. It would definitely be useful though :-). Good luck to you paramat.

**Comment by paramat** [comment]
Also there is code here in the lua API that could be used to help write a 'create and save schematic from lua table' API:
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_mapgen.cpp#L499

**Comment by MT-Modder** [comment]
I understand pretty much nothing in c++ but I understood some of that. If I would take the time to understand the lua table method, or the L-System, from your examples I wouldn't have to worry about this issue. A little off topic but I wouldn't have started messing around with the mapgen if it wasn't for your examples with paragen and paragenv7. Especially your biomedev mod so thank you.

**Comment by MT-Modder** [comment]
I hope this is fixed soon. :frowning:

**Comment by paramat** [comment]
Yes a few months ago this bug led me to that signature code. On IRC hmmmm posted that the files and/or signatures might be being corrupted.
Currently schematic decorations defined by a lua table do still work.

**Comment by MT-Modder** [comment]
Good luck paramat and kwolekr. I hope you guys figure it out and it's easy to fix.

**Comment by Zeno-** [comment]
This is happening because it's looking for the .mts file in the current directory; i.e. the directory you are in when you run minetest

**Comment by paramat** [comment]
Just to note, the issue raised in Worldedit https://github.com/Uberi/Minetest-WorldEdit/issues/77 seems to suggest this is not a Worldedit bug.

**Comment by Zeno-** [comment]
This is certainly (100%) an engine bug

**Comment by paramat** [comment]
Discussion on IRC http://irc.minetest.ru/minetest-dev/2015-03-19#i_4192020
This *might* work, although i probably misunderstand:
schematic = minetest.getmodpath("mycoolmod").."tree.mts",

**Comment by Zeno-** [comment]
Yes that's  a workaround  @paramat  ... I personally don't like it much but will have to see what happens.

**Comment by MT-Modder** [comment]
That's a simple fix :-).

**Comment by C1ffisme** [comment]
Hey! There you go, that's what I used when I made some simple trees for V7! Huh, it's surprising how we can make such big, frustrating errors by just doing something the way someone didn't expect. Does this completely solve the problem?

**Comment by MT-Modder** [comment]
@Zeno-  I like the ability to define where the schems are but it's not too important me.

**Comment by paramat** [comment]
I asked TenPlus1 if Ethereal mod is having problems, it isn't, now look at the code (facepalm):

local path = minetest.get_modpath("ethereal").."/schematics/"

schematic = path.."acaciatree.mts"

**Comment by MT-Modder** [comment]
> (facepalm)

Same here.

**Comment by Zeno-** [comment]
Leaving this open for now because either the behaviour needs to be documented or the behaviour needs to change, and the solution is not clear at the moment

**Comment by MT-Modder** [comment]
Good point.

**Comment by kwolekr** [comment]
I thought about this a bit more and I think the correct behavior is to prepend the mod directory in the case of a relative filename, and use the exact filenamed passed if it's determined to be an absolute filename.
The issue here is that we'd have to assume minetest.get_modpath() returns an absolute path all the time, which is patently false on OSes other than the "big four".  I think we need to fix initializePaths() in order to make any progress here.

**Comment by paramat** [comment]
kwolekr has made commits for this issue, perhaps this can be closed now?

**Comment by MT-Modder** [comment]
Yes it can thanks.

**Comment by DerpyPony25** [comment]
I Got Problem in Ethereal Mod 

2015-12-08 19:28:56: ERROR[main]: Server: Failed to load and run C:\Users\user\Desktop\minetest Real\bin\..\mods\ethereal\init.lua
2015-12-08 19:28:56: ERROR[main]: ModError: ModError: Failed to load and run C:\Users\user\Desktop\minetest Real\bin\..\mods\ethereal\init.lua
2015-12-08 19:28:56: ERROR[main]: Error from Lua:
2015-12-08 19:28:56: ERROR[main]: cannot open C:\Users\user\Desktop\minetest Real\bin\..\mods\ethereal/mapgen_v7n.lua: No such file or directory
2015-12-08 19:28:56: ERROR[main]: stack traceback:
2015-12-08 19:28:56: ERROR[main]: 	[C]: in function 'dofile'
2015-12-08 19:28:56: ERROR[main]: 	...user\Desktop\minetest Real\bin\..\mods\ethereal\init.lua:58: in main chunk
