### ISSUE TITLE
Feature Request : Per-world difficulty settings.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2486]
It's easy to get into your minecraft world and play, because you don't have to remember if it's a survival or creative world. You just plop right in. If you need to change your gamemode, you can do so with commands.

I want to have this feature, almost. I think every world should have a ```creative_mode``` and ```enable_damage``` setting. And when you select a world, the checkmarks would automatically set themselves to that worlds settings. You can still change them, but you don't have to remember to set them when you select a world.

##### Simpler Explanation : 

* Player starts up menu.
* The settings to the left of the world selection have damage disabled and creative mode enabled.
* A player selects a survival world.
* **What I want:** The checkboxes change, damage is enabled and creative mode is disabled.

This way people don't accidentally start their singleplayer world and mine tons of diamonds before realizing they were in creative mode. It also means you can start up a world really quickly without clicking too much.

**Comment by LeMagnesium** [comment]
Usually, when you want to start a server using static settings like these, you use the command lines interface. Servers using settings like these are generally stable servers, not servers kept alive by the admin's client (started by GUI). So maybe it is a good idea, but there are easy ways to do that.

**Comment by C1ffisme** [comment]
I don't think you understand what I mean. I'm not suggesting a huge overhaul to gameplay or administration. I just want the checkboxes for creative mode and enable damage to, when you click on a world, check or uncheck themselves to be what they were last time. Just so that you can select a world and play, you can still uncheck or check the boxes, but this means you don't have to keep a paper of what worlds were in survival or creative.

**Comment by LeMagnesium** [comment]
If you want to keep the values of enable_damages and creative_mod then you would need to save them in a file, somewhere. Minetest.conf cannot save that, it's not its role, and it is already full enough if settings. Saving this in world.mt or map_meta.txt could be a good idea. I perfectly understood what you meant, I was just telling you that there are other ways to keep these values, like dedicated configuration files (which the path to are specified when you launch a server with command lines). Keeping these values for GUI is a good idea, but then, we have to think of where we will keep them stored.

**Comment by C1ffisme** [comment]
Yeah, that's what I was thinking, just 2 lines in map_meta.txt.

**Comment by C1ffisme** [comment]
This has been merged now. Closing.

**Comment by Zeno-** [comment]
commit 8ca08a850ff2494652aa0ac2daa3d00f03aa4e7a
