### ISSUE TITLE
damage problems

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#2492]
I've got problems with damage in minetest.
The disable_damage setting doesn't seem to work correctly:
If I disable it, I still become damaged from my shooting object.
And then when I die, I click on respawn but no respawn happens, I run around and digging doesn't work, but I can use the chat.

And I've got another damage problem:
When I ran a local server, after some time the hud wasn't shown after joining.
This was annoying and I had to restart the server the whole time.

**Comment by LeMagnesium** [comment]
The same issue have been reported by w_laenger on IRC who got stuck in the laying state. Not being able to respawn if server shut down and restart without damage while you're dead is a known bug, but damages disabled that keep working is knew and I didn't see this until I compiled my version today.

**Comment by SmallJoker** [comment]
One (or more) of the following commits are the source of this problem:
4e63c977
afb19f3a1
3067d782

**Comment by nerzhul** [comment]
@SmallJoker the bug is older than the commits you said, @VanessaE reports the issue on IRC before these commits. Theses commits fix one bug linked with respawn problem.

**Comment by HybridDog** [comment]
@LeMagnesium today only the first one

@Krock the second one appeared approximately when the hud got an image in minetest_game

**Comment by nerzhul** [comment]
@HybridDog for the death loop bug, i partially fix the problem with last commit: b2801d8127f4b25fd96f981974763f33bc7ff42b.
Players which are stucked can now disconnect and reconnect to fix the problem. Now i need to find where is the loop bug

**Comment by nerzhul** [comment]
Fixed: aaf26b3a4410c4a1dc2f4a8bb9c61122648fedf3
