### ISSUE TITLE
Ability to mark server as a favorite

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#2496]
Favorite servers should be shown on the top of server list with some icon (:star: or :heart:). Currently :heart: means that damage is enabled on server, but I think better icon if damage is enabled is :skull: or something similar.

**Comment by kilbith** [comment]
@kahrl

**Comment by est31** [comment]
And what do you propose for the "favourite" list that is currently implemented?

**Comment by neoascetic** [comment]
Oh, we already have favorite servers list? I didn't know, and still unable to see it anyway.

![screen shot 2015-03-16 at 17 10 09](https://cloud.githubusercontent.com/assets/725836/6669083/bedab748-cbff-11e4-9937-fd49f7a2486f.png)

**Comment by MT-Modder** [comment]
@neoascetic If you uncheck the public serverlist you get a list of favorites. I think these should be tabs so it's easy for new people to know there is a favorites list. The tab idea was first suggested here: https://github.com/minetest/minetest/pull/2054

**Comment by neoascetic** [comment]
IMO be able to see favorite servers among the others is better because it is under same tab.

**Comment by MT-Modder** [comment]
True.

**Comment by neoascetic** [comment]
Okay, initially I thought favorites do not exist in any state, but currently I see that they are exist, though it was not very intuitive. So I close the issue. I hope when main menu being redesigned, designer better than me will make favorites list better. Thanks to everyone.
