### ISSUE TITLE
Crash upon selecting the inventory on Android

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2498]
While testing the official app from the Play store, I noticed another big problem: upon selecting the inventory, the game crashes. I tested it multiple times, even reinstalled it, and got the same result.

**Comment by Wayward1** [comment]
Sorry, false alarm- after deleting the Minetest folder from my tablet and reinstalling, the problem was solved.

**Comment by nerzhul** [comment]
@Wayward1 a conflicting mod ? :)
Thanks

**Comment by Wayward1** [comment]
No, I think it may have been something in the minimal game, because for some reason that was the game that was automatically selected instead of minetest_game
