### ISSUE TITLE
on_enter_node() and register_on_enter_node() methods

### ISSUE THREAD

**Issue by MT-Modder** [minetest/minetest#2500]
This is just a feature request.

The idea is that this function would be called when a player, or maybe any entity, enters a non-walkable node. Here is one simple example for this:
```
minetest.register_node("foo:bar", {
    on_enter_node = function(pos, player)
        player:setpos({x=pos.x, y=pos.y+4, z=pos.z})
    end,
})
```

The uses for this are practically infinite.

**Comment by C1ffisme** [comment]
I can think of just that node being a useful elevator.

**Comment by MT-Modder** [comment]
Yeah that was the idea for that example. I was making a quicksand mod and wanted the player to get stuck but couldn't do it without something like this.

**Comment by rubenwardy** [comment]
If you look at the TNT code, they ABMs to see if players are stepping on them. A similar method could be used here.

An on_step callback would be nice, though, for cleanness of code.

**Comment by MT-Modder** [comment]
@rubenwardy 
> If you look at the TNT code, they ABMs to see if players are stepping on them. A similar method could be used here.

Yeah but I don't think this fits exactly. Being on a node and in a node are different things. I get your point though it's possible.

This is probably how I would have done what I wanted to through an abm:
```
local objs = minetest.get_objects_in_area(pos, 1)
for _, obj in pairs(objs) do
    local obj_pos = obj:getpos()
    if obj_pos = pos and obj:is_player() then
        obj:set_physics_override({speed = 0})
    end
end
```
But this seems like it would only work sometimes, not to mention being unnecessary and possibly slow.

> An on_step callback would be nice, though, for cleanness of code.

That would be a nice addition too. :+1:

**Comment by MT-Modder** [comment]
The method used within the TNT code is good enough.
