### ISSUE TITLE
creative & damage disabled: tnt deals damage and kils player

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2501]
When in creative and with damage disabled the player still gets damage by tnt explosions and dies. 

You also get damage by drowning (there is the animation) but you don't die.

**Comment by paramat** [comment]
Confirmed. Drowning red screen and damage tilt underwater even in creative and with damage disabled.

**Comment by nerzhul** [comment]
The main problem is the set_hp call which doesn't care about enable_damage parameter and it is normal. We need to have a do_damage call which solve this issue and need to be used by mods.

**Comment by C1ffisme** [comment]
Or you could just rewrite set_hp.

**Comment by nerzhul** [comment]
No. Set_HP works properly it sets HP.
If you need to do damage we need a call which does damages/heals

**Comment by nerzhul** [comment]
Created a new apply_damage call for preventing this.
a PR is now in minetest_game to fix this:

https://github.com/minetest/minetest_game/pull/468

**Comment by paramat** [comment]
If it's any help, this is still occuring in d03c2999daafaff5b48948bb97a5854f5fb56484

**Comment by nerzhul** [comment]
@paramat did you apply https://github.com/minetest/minetest/commit/2676d289d9ac46a3145f3740c75e5078480ff858, that solve the problem for me

**Comment by paramat** [comment]
I think so, as i compiled at the commit afer that, but i will check again in case i made a mistake.

**Comment by paramat** [comment]
Just compiled latest master, bug is still present in mgv7, red screen and damage tilt when underwater, in creative mode and with damage disabled.

**Comment by nerzhul** [comment]
You talk about underwater, it's the only case or also TNT ? I tested TNT it works perfect

**Comment by paramat** [comment]
Okay good, i didn't test TNT i trust you on that.
Strangely i get red screen and damage tilt when drowning but not when falling from a high place.

**Comment by nerzhul** [comment]
It's because a race is missing somewhere, but you point a special thing, i should reproduce it

**Comment by paramat** [comment]
Also i noticed this bug is not always reproducable, on one occasion the bug was not present when underwater.

**Comment by paramat** [comment]
> The main problem is the set_hp call which doesn't care about enable_damage parameter and it is normal. We need to have a do_damage call which solve this issue and need to be used by mods.

See comments in https://github.com/minetest/minetest/pull/2511. Please could you offer to remove that commit?

**Comment by paramat** [comment]
Tested again in 6cf7c89236d6b222f53ca9c8d681d6cde656bea1. With damage disabled i get red screen and camera-tilt when falling a long way or when drowning underwater. But these bugs are inconsistent, coming and going with no pattern even within one gaming session, most mysterious.

**Comment by nerzhul** [comment]
you mean it's not every time ? Only in some cases ?

**Comment by paramat** [comment]
Yes. For example testing this bug by drowning my player a few times, or jumping off a high place a few times, the bug sometimes happens, sometimes doesn't.
Sometimes when first entering a world the bug will happen once, then not again, but then leaving and re-entering the world can make the bug happen again.
It seems fairly random the way the bug comes and goes during a gaming session.

**Comment by PilzAdam** [comment]
@paramat It consistently appears for me until I die; I have to rejoin with damage enabled to respawn properly.

**Comment by paramat** [comment]
I just realised i might be wrong about the inconsistency of this bug. Perhaps instead during multiple tests i am taking enough damage to 'die' and so the damage effects then stop after 20 HP has been subtracted. This occured to me while testing the bug in lava: the damage effect only happened once or twice then stopped, as if i had lost 20 HP quickly after just a few seconds in lava.
Perhaps we have invisible HP which when used up does not result in death, then at this point the bug stops occuring.

**Comment by paramat** [comment]
Has anyone bisected this yet? I would like to if i can find time, i bisect manually so it takes hours.

**Comment by Zeno-** [comment]
Tested with the following script and /sethp 10 to observe the damage flash/tilt while standing in lava
```
local function setphp(name, param)
	player = minetest.get_player_by_name(name)
	if player then
		player:set_hp(param)
	end
end

minetest.register_chatcommand("sethp", {
	description = "set your HP",
	privs = {interact=true},
	func = setphp
})
```

The quick version:

```
[eatenbyagrue@localhost minetest]$ git bisect start
[eatenbyagrue@localhost minetest]$ git bisect bad 7f8f9785d7e9e120a6708d2f51e32dfef3e50c19  
[eatenbyagrue@localhost minetest]$ git bisect good 056e8f7839d72dfc2e8aa0a68c5d19d7cc30a282
Bisecting: 2 revisions left to test after this (roughly 1 step)
[7e56637ed07d9f32b4bd9049009cf7e1e4cff884] Send Breath packet on event, don't check it at each AsyncRunStep
[eatenbyagrue@localhost minetest]$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[64ff966bae99813229dff6629fd9131a91ba7484] Send Player HP when setHP (or a setHP caller) is called instead of looping and testing the state change.
[eatenbyagrue@localhost minetest]$ git bisect bad
64ff966bae99813229dff6629fd9131a91ba7484 is the first bad commit
commit 64ff966bae99813229dff6629fd9131a91ba7484
Author: Loic Blot <loic.blot@unix-experience.fr>
Date:   Mon Mar 2 17:31:31 2015 +0100

    Send Player HP when setHP (or a setHP caller) is called instead of looping and testing the state change.

:040000 040000 b997c19737d7fcb32ccec690ae0bf96dfdda1ded 5bc3f6fa61103a809f883bbaeaa8d0c89c45b402 M  src
```

**Comment by paramat** [comment]
Awesome, thanks so much.

**Comment by nerzhul** [comment]
It seems that an event was hidden by previous code. We need to find which évent and where to disable it. Thanks for the reproduction

**Comment by paramat** [comment]
Hi nerzhul, are you able tix this? I hope this gets fixed soon as i often need to fly underwater when workng on mapgen, camera tilt is actually painful for me.

**Comment by HybridDog** [comment]
@paramat, does https://github.com/minetest/minetest/pull/2592 fix it?

**Comment by nerzhul** [comment]
It's not the solution :(

**Comment by paramat** [comment]
Hi nerzhul, if you're unable to fix this please let us know so others can prioritise working on it.

**Comment by nerzhul** [comment]
at this moment i have some IRL problems and i cannot do devel for minetest theses days...

**Comment by paramat** [comment]
Needs fixing.

**Comment by HybridDog** [comment]
>It's not the solution :(

l think it's the solution for the drowning problem.

**Comment by kilbith** [comment]
Can be closed since https://github.com/minetest/minetest/commit/1a1774a1051790ef85b1bd8b047ac45a3676b5d6

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/1a1774a1051790ef85b1bd8b047ac45a3676b5d6

**Comment by paramat** [comment]
Confirmed fixed.
