### ISSUE TITLE
Shaders on android produce wrong colors

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2502]
When you enable shaders on android, you get wrong colors:
![screenshot_error](https://cloud.githubusercontent.com/assets/8872119/6680051/69293de4-cc52-11e4-861a-c620b64a5616.png)
[See here for some further screenshots](https://imgur.com/6m4teRi,EKqJze3,qeTkDVO,WR2qYk8,bYjamcq#0)

**Comment by C1ffisme** [comment]
It's a well known bug that shaders can cause things to look red. It may be because of your graphics card.

**Comment by est31** [comment]
Three people can reproduce this. Can you?

**Comment by C1ffisme** [comment]
Me? I'll try...

**Comment by C1ffisme** [comment]
Nope, no wrong colors. Although I did only check the shaders button. Bumpmapping makes minetest unplayable.

**Comment by ShadowNinja** [comment]
Are you using OGLES 2?  OGLES 1 doesn't support shaders.  They aren't really expected to work yet though, I don't think anyone's gotten them working yet.

**Comment by nerzhul** [comment]
Maybe we must ignore shader setting if OGLES1 is set @ShadowNinja , no ?

**Comment by Zeno-** [comment]
This is also present using  ogles 2 driver and shaders enabled. In fact, with es2 there are additional visual glitches for me (cuboids not rendered properly)

Galaxy tab 4

**Comment by Wayward1** [comment]
Confirmed with all four graphics drivers on Amazon Fire HD 6". Also, plantlike nodes don't seem to render properly either.

**Comment by ExeterDad** [comment]
Same report as Wayward1
LG Volt

**Comment by MoNTE48** [comment]
Confirm.
Samsung Galaxy: S4, S5, Note 4, Note Edge, Note Pro

**Comment by Warr1024** [comment]
Confirm on Samsung Galaxy Tab 2 10.1 (GT-P5113), Android 4.2.2, using OpenGL ES1.
Most textures appear red.  Light sources appear yellow.  Transparency is lost entirely from textures (transparent areas appear opaque black instead).

**Comment by est31** [comment]
dupe of #2060
