### ISSUE TITLE
Registering Nodes while minetest is playing.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2513]
I thought about something new. What if later on we made mods that required thousands of node types? It be great if we could register new ones in minetest.

I don't have much time to talk about it, I need to join a friends LAN server, but think about the possibilities.

**Comment by LeMagnesium** [comment]
It would need a protocol and massive engine change, and it has already been proposed. I can't find the issue anymore but if someone does please send its number (and maybe close this one).

**Comment by C1ffisme** [comment]
Why not close the older, probably forgotten one and start the conversation over again here?

It's a good idea, and might allow mods that require TONS of nodes to just register the few items people craft. (Think about something like, an inventing mod) But, it would need tons of coding done.

Maybe a collaborative pull request is needed. I'm sure this is something to work on for 0.5.0 or 1.0.0 or something.

**Comment by tenplus1** [comment]
-1  nodes should be defined at start to save errors and problems within game...

**Comment by neoascetic** [comment]
+1 from me, this will lead to more creative gameplay when it is possible to create new nodes/tools/etc right in the game

**Comment by LeMagnesium** [comment]
A change like this could allow quite strange things : image you're playing, and suddenly a bunch of new nodes is registered which are unbreakable, and someone use them against a construction of yours (okay, it's maybe not the more creative example I have but it one). Or, when you had to mine during an hour to get what you needed to craft a specific item a new one appears, easier to get, which does the same thing : giving you in a few seconds what tooks maybe half an our to do. Changing rules when game is started leads to serious problems, and as @tenplus1 said, every node registering should be checked at server start, like entity's, and generally item's ones.

**Comment by C1ffisme** [comment]
True, but remember that there are server owners who decide what mods get entered in.

I'm not suggesting player node making, but maybe on_craft you could make an item like a certain chemical or firework or something. The item would be registered and then maybe de-registered when there are no instances of it.

Here's an example:
- There are millions of possibilities for a firework.
- You craft one. That type of firework gets registered.
- The firework gets added to a list of instances of this item.
- The firework is shot.
- The firework is removed from the inventory, which removes it from the list.
- The node gets un-registered. This saves space.

About registering things at the start, what would happen if I did this?:
```
for i = 1,10000 do
    minetest.register_node("chemistry:chemical_"..i,{
         -- This is where the node stuff goes. It isn't relevant.
    })
end
```
I'm sure this would give the RAM the worst time yet. It would be easier on computers to do this:
```
minetest.register_on_craft({
    recipe = {{"default:coal","default:paper","dye:red"}},
    action = function()
        minetest.register_node("fireworks:red_firework",{
            -- Again, not relevant
        })
        return "fireworks:red_firework 4"
    end
})
```

**Comment by kwolekr** [comment]
This is sort of difficult to do without changing a lot of stuff after making the switch from a statically allocated array to a vector.  It must be atomic, but adding a new element to a vector is not an atomic operation. Adding locks around nodedef operations is simply not happening, so a solution must be lock-free and wait-free.

**Comment by paramat** [comment]
Essentially, not worth the headache.
