### ISSUE TITLE
Segmentation fault when attempting to call minetest.clear_registered_ores

### ISSUE THREAD

**Issue by Echoes91** [minetest/minetest#2514]
The minetest.clear_registered_ores() call issued from a mod's init.lua within default minetest_game cause immediate segfault:

However calling them from inside with luacmd or with any delay results in them working as expected. This is a workaround:
minetest.after(1, function()
	minetest.clear_registered_ores()
end)

**Comment by nerzhul** [comment]
can you give us the backtrace please

**Comment by Echoes91** [comment]
Sorry, took some time to learn to debug on Arch Linux...
Actually the issue regards only minetest.clear_registered_ores(). Compiling from master branch and creating a new world with mapgen v7, default minetest_game and only one mod with just that call enabled:
Program received signal SIGSEGV, Segmentation fault.
https://bpaste.net/raw/492a2560d678

**Comment by Echoes91** [comment]
Corrected confusing informations, now it should be clearer

**Comment by paramat** [comment]
Looks to be a problem with blob ore, probably triggered by me recently moving blob ores into the 'register ores' function in MTGame. I may need help wit this one.

**Comment by paramat** [comment]
Did your test mod have 'default' as a dependancy? If the mod is running before default it would be trying to clear ore registrations that don't exist. Singlenode mapgen does not have ores registered so might also have the same result.

**Comment by Echoes91** [comment]
Yes, it had default dependency since it defined biomes and anything else
using default's nodes. Now i quitted it since your biomesdev is exactly
what i was aiming at and it's already far better, anyway that may still
prevent any custom ores redefinition if not "delayed" with the workaround.

2015-03-20 11:23 GMT+01:00 Paramat <notifications@github.com>:

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/26153bab7dbe57a0200949c9a121058150e67f6c

**Comment by paramat** [comment]
Thanks, will test.
