### ISSUE TITLE
Default action on doubleclick doesn't work on OSX

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#2515]
It would be more user-friendly to be able to execute default action on double-click on some element in menu. For example, when I am double-clicking on singleplayer world name, I, obviously, want to start it and play. Another example: double-click on mod name in mod configuration for a world should enable/disable corresponding mod.

**Comment by MT-Modder** [comment]
This is implemented and it works for me. Running Windows 7.

**Comment by Zeno-** [comment]
Works for me as well (Linux)

**Comment by neoascetic** [comment]
OK, seems like OSX issue, will try to fix it.

**Comment by paramat** [comment]
@neoascetic any news on this?

**Comment by neoascetic** [comment]
It seems like it is Irrlicht's issue. I don't know why, but doubleclick event does not propagate, singleclick is propagated instead.

**Comment by ShadowNinja** [comment]
Might be worth checking if it's fixed in Irrlicht 1.9, I hear the input system's been revamped.

**Comment by echosa** [comment]
I downloaded the game this week and am experiencing this issue as well. OS X 10.11.6.
