### ISSUE TITLE
Ability to change hover text for objects and mobs

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#2516]
Changing hover text on nodes can be done but for a moving object it always displays "GenericCAO" and armor/health status...  Handy information but could you change it so that the "GenericCAO" part can be changed in a mod... e.g...   "Cow (recovering)", "Cow (pregnant)" etc...

**Comment by ExeterDad** [comment]
+1 on this. Some meta if possible would be cool also for infotext

**Comment by MT-Modder** [comment]
:+1: @tenplus1

**Comment by Echoes91** [comment]
+1 That would be useful

**Comment by C1ffisme** [comment]
:+1: Yes! You could use it to show NPC names or show who owns a soldier or a whole bunch of things!

**Comment by hunter688** [comment]
Look like TagAPI in the bukkit.
:+1:

**Comment by Warr1024** [comment]
I would also like to be able to control the display of player names, for instance, hiding from each player the names of all other players other than himself/herself, e.g. for a stealth PvP game type.

**Comment by est31** [comment]
@Warr1024 there is already `player_transfer_distance` for that.

**Comment by Warr1024** [comment]
@est31 as I understand it, that affects transfer of the players themselves, not their names.  I still want players to be transferred, but I want control, from the server-side, of the names that are displayed over their heads, especially when the players themselves are occluded by terrain.

**Comment by neoascetic** [comment]
+1

**Comment by hunter688** [comment]
Also hiding nicknames will be will be useful on the PvP server for example. Or configurable (on the server side) show only when another player can be seen or is in the some distance etc...

**Comment by neoascetic** [comment]
@hunter688 yeah, for some something like this: #3240

**Comment by est31** [comment]
Hover text can be now changed (its called "infotext"). Fixed by commit: 87291ea44a61614d5bd9efc0657926da3f867b5f
