### ISSUE TITLE
Android: noclip, fly, etc. buttons are way too sensitive

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2520]
When trying to toggle any of the non-control related buttons, it usually takes several tries to get the desired result. I noticed that when you touch and hold any of them, they quickly cycle between on and off. It seems it would make more sense to have it change only once each time the button is touched and held, for easier selection.

**Comment by MoNTE48** [comment]
Duplicate!
https://github.com/minetest/minetest/issues/2288

**Comment by Zeno-** [comment]
Closed as duplicate (see above comment)

**Comment by Wayward1** [comment]
Oh, oops
