### ISSUE TITLE
Android: fast_move only works with free_move enabled

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2522]
On the latest Android build, enabling fast_move has no effect on walking speed, only on flying speed.

**Comment by MoNTE48** [comment]
so. it is right. No bug

**Comment by Wayward1** [comment]
? But that seems counterintuitive... What about servers with fast but no fly?

**Comment by PilzAdam** [comment]
In the desktop version you also have to hold down the E key to move fast when fast_move is enabled.
@MoNTE48 it is intended that players can move fast when not flying.

**Comment by Zeno-** [comment]
Oops. Thanks :)

99cf53c9087671d0a2130d2272b9a4f61d680517

**Comment by Zeno-** [comment]
Note: The player must still have the fast priv for this to work (as before)

**Comment by Wayward1** [comment]
Np :)
