### ISSUE TITLE
Error when using minetest.get_craft_recipe('item') in a lua file

### ISSUE THREAD

**Issue by Miner59** [minetest/minetest#2530]
I got an error when I used minetest.get_craft_recipe() in a mod.
The following error is from a test mod, just with this line in init.lua:

minetest.get_craft_recipe('default:torch')

20:20:53: ERROR[main]: ========== ERROR FROM LUA ===========
20:20:53: ERROR[main]: Failed to load and run script from 
20:20:53: ERROR[main]: .../minetest-413/bin/../mods/test/init.lua:
20:20:53: ERROR[main]: attempt to index a string value
20:20:53: ERROR[main]: stack traceback:
20:20:53: ERROR[main]: 	[C]: in function 'get_craft_recipe'
20:20:53: ERROR[main]: 	.../minetest-413/bin/../mods/test/init.lua:1: in main chunk
20:20:53: ERROR[main]: ======= END OF ERROR FROM LUA ========

Minetest version is from github, a few hours ago.

**Comment by est31** [comment]
confirmed.

**Comment by est31** [comment]
@ShadowNinja missed one line as he changed @gregorycu's patch. PR #2537 adds it.

**Comment by Zeno-** [comment]
commit 5b5c4980112843e38d11cbc5c59d7c5de48da980
