### ISSUE TITLE
Server console/log timestamp format

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2539]
Will be possible change or add configuration for timestamp format of server console/logs?

Now is: 

07:04:33: ACTION[ServerThread] .....

Will be better add date, day, month, maybe year for example:

2015-03-23 07:04:33: ACTION[ServerThread] .....

**Comment by nerzhul** [comment]
I agree with this.

**Comment by Zeno-** [comment]
+1

**Comment by donat-b** [comment]
+1

**Comment by yo-we** [comment]
+1

**Comment by yo-we** [comment]
Actually, I came to request that :)   Thanks

**Comment by Megaf** [comment]
:+1: 

Maybe:
DD/MM/YY - HH:MM:SS: [Server/Action] - PlayerName: digs defaut:stone at (000,000,000)

**Comment by proller** [comment]
MM/SS/DD - MM:YY:HH: [Server/Action] - PlayerName: digs defaut:stone at (000,000,000)

**Comment by donat-b** [comment]
ISO 8601

**Comment by Megaf** [comment]
@donat-b 
Then it would be:
YYYY-MM-DD - hh:mm:ss: [Server/Action] - PlayerName: digs defaut:stone at (000,000,000)
Or with time before date:
hh:mm:ss - YYYY-MM-DD: [Server/Action] - PlayerName: digs defaut:stone at (000,000,000)

I like the last one.

**Comment by Zeno-** [comment]
The ISO-like one is the only correct way

**Comment by Megaf** [comment]
@Zeno- 
So the correct way is:
YYYY-MM-DDThh:mm:ss: [Server/Action] - PlayerName: digs defaut:stone at (000,000,000)

2015-04-24T14:21:50: [Server/Action] - PlayerName: digs defaut:stone at (000,000,000)

**Comment by donat-b** [comment]
@Megaf
I think it's better with a space instead of the T.

**Comment by Megaf** [comment]
It's all a matter of following the ISO or not.
In my humble opinion the best looking and perhaps clearest way is the following:
```
YYYY-MM-DD - hh:mm:ss [Server/Action] PlayerName digs defaut:stone at (000,000,000)
2015-04-24 - 14:21:50 [Server/Action] PlayerName digs defaut:stone at (000,000,000)
```

**Comment by Zeno-** [comment]
@Megaf your latest example is "iso-like" which is why I put "iso-like" in quotation marks in my previous comment :)

**Comment by Megaf** [comment]
@Zeno- Right, iso-like it is.

**Comment by yo-we** [comment]
Hello, The proposals are alright for me, wether there is the "T" or the " - ". Remark: If you really want to have something without ambiguity, you will have to replace the 2 numbers of the month by three letters. Like
2015mar25
or
2015-mar-25
because otherwise it can be misread by Americans.

**Comment by PilzAdam** [comment]
@yo-we The date format follows [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601), which is an international standard.

**Comment by Megaf** [comment]
@PilzAdam @yo-we 
@Zeno- indeed forgot to put a "-" to separate date and time, or perhaps it was intentional?

**Comment by Zeno-** [comment]
I intentionally left it out, but perhaps some other character can be used as a delimiter between the date and the time?

**Comment by Megaf** [comment]
Why not " - "?
``` 2015-04-24 - 14:21:50 [Server/Action] PlayerName digs defaut:stone at (000,000,000) ```

**Comment by Zeno-** [comment]
Because, personally, I'd like a different deliminator between date and time ('-' is already used in the date) for pattern matching and stuff. Obviously you can still do it if the deliminator is the same it's just more cumbersome (IMO)

**Comment by yo-we** [comment]
@Zeno: use of "@" could be a possibility and remain readable
@all: I agree to the ISO-approach. Just telling you that it remains ambiguous as you have to know that it is "ISO" not to take it for "american".
