### ISSUE TITLE
*object:remove() registered at shutdown causes segmentation fault

### ISSUE THREAD

**Issue by Echoes91** [minetest/minetest#2546]
I needed to register at shutdown the removal of some LUA entities (my arrows):
minetest.register_on_shutdown(function(obj)
    obj:remove()
end)
Minetest crashes on shutdown with https://bpaste.net/raw/76290904ca1c
After restart the arrow is effectively removed. The same happens with obj:get_luaentity():remove() or obj:get_luaentity().object:remove().

**Comment by Echoes91** [comment]
Looks like that any other LuaEntity method called gives the same result, maybe those objects are unreachable at shutdown.

**Comment by RobertZenz** [comment]
With the latest HEAD of Minetest, it does not crash for me if an entity is removed on shutdown, instead the entity turns into a "ghost" entity. It suddenly has completely different properties as it was registered with, isn't reachable via `get_objects_inside_radius` and can't be removed except with `/clearobjects` (or whatever that command is called).

**Comment by sfan5** [comment]
Doesn't seem to apply anymore, closing.
