### ISSUE TITLE
Mainmenu Lua errors

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2548]
Last commit : 732d7b9a7c2a89bc21abb40b333f974a4b2474c4
If I check "*Creative Mode*" and/or "*Enable Damage*" with an empty world list : 

```
12:17:39: ERROR[main]: MAINMENU ERROR: ...inetest/bin/../builtin/mainmenu/tab_singleplayer.lua:153: attempt to index field '?' (a nil value)
12:17:39: ERROR[main]: stack traceback:
12:17:39: ERROR[main]: 	...inetest/bin/../builtin/mainmenu/tab_singleplayer.lua:153: in function <...inetest/bin/../builtin/mainmenu/tab_singleplayer.lua:100>
12:17:39: ERROR[main]: 	(tail call): ?
12:17:39: ERROR[main]: 	/home/jp/minetest/bin/../builtin/fstk/ui.lua:118: in function 'handle_buttons'
12:17:39: ERROR[main]: 	/home/jp/minetest/bin/../builtin/fstk/ui.lua:155: in function </home/jp/minetest/bin/../builtin/fstk/ui.lua:148>
12:17:43: ERROR[main]: MAINMENU ERROR: ...inetest/bin/../builtin/mainmenu/tab_singleplayer.lua:167: attempt to index field '?' (a nil value)
12:17:43: ERROR[main]: stack traceback:
12:17:43: ERROR[main]: 	...inetest/bin/../builtin/mainmenu/tab_singleplayer.lua:167: in function <...inetest/bin/../builtin/mainmenu/tab_singleplayer.lua:100>
12:17:43: ERROR[main]: 	(tail call): ?
12:17:43: ERROR[main]: 	/home/jp/minetest/bin/../builtin/fstk/ui.lua:118: in function 'handle_buttons'
12:17:43: ERROR[main]: 	/home/jp/minetest/bin/../builtin/fstk/ui.lua:155: in function </home/jp/minetest/bin/../builtin/fstk/ui.lua:148>
```

**Comment by kilbith** [comment]
It happens when no world is created yet... So it's normal.

**Comment by Zeno-** [comment]
Define "normal" :)

**Comment by kilbith** [comment]
Those settings can't be saved if there's no world. They are specifical to a world.

**Comment by nerzhul** [comment]
They need to be handled properly, then, not trigger a nil error

**Comment by kilbith** [comment]
Re-open because it can be fixed by https://github.com/minetest/minetest/pull/2581

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/pull/2586

**Comment by 4aiman** [comment]
Nearly 2 months of discussion instead of adding a single check...
Don't get me wrong, I'm not going to search for a responsible person ;)
It's just I'm frustrated how things like this are being discussed over instead of fixing.

Do you know that ANY lua error crashes the Android client with absolutely NO info shown to a player?
Since MT is on GP, there's nothing to discuss - you need to fix this like all other clients have done.

**Comment by kilbith** [comment]
Fix here : https://github.com/minetest/minetest/pull/2855

**Comment by est31** [comment]
85f3d575ec3d99ef2ce680d4a2546e4d31327d83
