### ISSUE TITLE
Option to remove timestamp from stdout log

### ISSUE THREAD

**Issue by neko259** [minetest/minetest#2554]
I'm using journald to capture minetest's output to log. journald saves its own timestamp to the log so there's no need to duplicate it in the log line itself.

**Comment by Calinou** [comment]
Suggested minetest.conf setting: `console_timestamps = true|false`

**Comment by est31** [comment]
I think settings are a bad idea, as then we lose the flexibility to make time-stamped (or stampless) log messages before we load the  settings file (or we buffer but thats bad because of crashes).

**Comment by neko259** [comment]
Do we really require timestamps for messages before the setting a were
loaded? I think timestamps are needed only for server game events to find
something that happened in hours of gameplay.
26 марта 2015 г. 2:34 пользователь "est31" <notifications@github.com>
написал:

**Comment by ShadowNinja** [comment]
A command line option would be much more convenient for my use case (manager starting the server that redirects it output and adds it's own text to it).

There is probably logging done even before options are parsed though.

**Comment by PilzAdam** [comment]
Add this as a mintest.conf option and add a way to override minetest.conf settings in the command line?

**Comment by paramat** [comment]
Very low priority with no support or interest from coders.
