### ISSUE TITLE
Missing fast move (USE) Button on android?

### ISSUE THREAD

**Issue by netinetwalker** [minetest/minetest#2556]
I try everything ... 
How i can use fast move in the android version?

the fast move dis/enable button is working and i can see the differnce if i activate fly mode too.

But the function like Pressing E too fast move on the PC Version is missing in android or in the docs of the android version .?

**Comment by Wayward1** [comment]
Duplicate, see #2522

**Comment by Zeno-** [comment]
ff924ef h
#2567
