### ISSUE TITLE
Wielding items that use minetest.inventorycube causes an error

### ISSUE THREAD

**Issue by Pilcrow182** [minetest/minetest#2557]
There doesn't seem to be anything wrong visually, but the minetest server spits out an odd error if a player wields an item that uses minetest.inventorycube.

For example, here's the error I get when wielding default:water_source...

ERROR[main]: generateImagePart(): Failed to load image "[inventorycube{default_water.png{default_water.png{default_water.png" for [combine

**Comment by Pilcrow182** [comment]
it would appear this happens only with older games. I was using a custom subgame built around an older version minetest_game (the one that came with minetest 0.4.8, to be exact)... as it *is* an incompatibility with older games (even if only slightly), I'm not sure I should close this issue. However, it does not affect the current minetest_game, so it should not cause problems for most people.

**Comment by Megaf** [comment]
I don't know if related, but I noticed a couple of days ago that the water_souce node wield item was invisible from my view when I was holding it on my hand.a

**Comment by paramat** [comment]
Closing, much has changed.

**Comment by est31** [comment]
@paramat please be a bit more verbose. I understand what you mean, but I doubt that the issue creator does, and that they can reopen the issue if they still can reproduce it.
