### ISSUE TITLE
Option to add exif data to screenshots.

### ISSUE THREAD

**Issue by ExeterDad** [minetest/minetest#2564]
I couldn't even hope to code this, but maybe a interested guru will.

I think it would be useful to have exif data added to our screenshots with the xyz coordinates and seed embedded in them for reference. I know F5 shows this information directly on the screenshot, but not everyone chooses to play the game this way.
It also may be useful to embed other data such as Minetest build, subgame name, server name if any or even active mods. So interested troubleshooters, or even curiosity seekers can more easily replicate a specific terrain.

**Comment by sfan5** [comment]
PNG files do not support EXIF data, also some players might want to keep the location they're at or the server they're playing on secret.
Also most online image hosts strip EXIF data so it's not useful for troubleshooting.

**Comment by Megaf** [comment]
I think EXIF is an interesting idea yes, but not practical.
I agree with sfan5.

**Comment by ExeterDad** [comment]
Disappointing. But it never occurred to me all points sfan5 brought up. They are indeed valid.
Thanks anyway :)

**Comment by Megaf** [comment]
@ExeterDad Yep, but your idea is nice, I like it tho. Just not possible/practical. Let's close the issue?

**Comment by ExeterDad** [comment]
Absolutely 
Didn't realize I could close, or I would of on last comment.
