### ISSUE TITLE
Inventory manipulation on multiplayer server is very slow/laggy

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#2566]
When moving items between player inventory and chest on the multiplayer server i see some ugly lags.

When move items inside chest see lags too.

When move items in the player inventory, all going smoothly.

Attached video: http://www.mirc.cz/mt-inventory-lag.ogv

**Comment by nerzhul** [comment]
Are you using latest master ?

https://github.com/minetest/minetest/commit/7851c4f7a2673477cf80a38842d77efbe5a0a915 commit fixed this problem, tested on my server with high load and lag disappeared.

**Comment by hunter688** [comment]
yes, using... client/server latest master

**Comment by Megaf** [comment]
Internet lag maybe?
Press F5 and see the RTT and type /status to see max_lag
Most likely your connection to the server is bad.
Or, the server is just overloaded/missconfigured.

**Comment by hunter688** [comment]
no lag no... on same server running some minecraft servers and no lags... Server isnt overloaded...

**Comment by hunter688** [comment]
Tested with iperf bidirectional udp without packetloss, jitter 0.425ms.

**Comment by Megaf** [comment]
Ok, and what about the RTT and max_lag values?

**Comment by hunter688** [comment]
RTT 0.005 max_lag 0.726329

**Comment by hunter688** [comment]
Im doing some another test with running game and wireshark network analyzer... Im expecting client send packet to server immediatelly when item is dropped to chest, but conversation with client-server works in cycles or something, this cause lag imho.

**Comment by Megaf** [comment]
in game.
grant youself all privs, /grant PlayerName all
then do a /set dedicated_server_step 0.05 or even lower like 0.01 and see if the lag persists

**Comment by nerzhul** [comment]
@hunter688 the server side now used a Sending-on-event mode for inventory.

**Comment by hunter688** [comment]
@Megaf setting have no effect :(

**Comment by Megaf** [comment]
@hunter688 Ok, so it looks like a bug indeed.
If the server is not too busy doing something else and even reducing the time it takes for it to do stuff had no affect, then I believe it might be a bug.

One last thing to try, fresh minetestserver build and fresh minetest build from fresh git and new configuration, can you do that?

**Comment by hunter688** [comment]
Ok, I will prepare it and then report.

**Comment by hunter688** [comment]
Tested on fresh server/client - server running on localhost have same issue. No mods, only default game. Singleplayer works smoothly.

**Comment by Megaf** [comment]
@hunter688 could you do one last test for us? Trying to play in a different machine, I mean, the server on one machine in your network and the client in another.
The server could be even on a Virtual Machine.

**Comment by hunter688** [comment]
Maybe found source of problem. When try fresh minetest without mods on fresh server without mods, looks like works fine. When install mods like technic+depedencies, unified inventory etc, problem appear. When uninstalled mods from server and reconnect, client still have background images in chest gui from previous modded version. When open crafting backround disapear and moving items works fine again. In the client log are these messages:
2015-03-27 18:43:12: ERROR[main]: generateImage(): Could not load image "technic_form_bg.png" while building texture
2015-03-27 18:43:12: ERROR[main]: generateImage(): Creating a dummy image for "technic_form_bg.png"
2015-03-27 18:43:12: ERROR[main]: generateImage(): Could not load image "technic_wooden_chest_inventory.png" while building texture
2015-03-27 18:43:12: ERROR[main]: generateImage(): Creating a dummy image for "technic_wooden_chest_inventory.png"
2015-03-27 18:43:12: ERROR[main]: generateImage(): Could not load image "technic_main_inventory.png" while building texture
2015-03-27 18:43:12: ERROR[main]: generateImage(): Creating a dummy image for "technic_main_inventory.png"

Maybe is slow generateImage() not communication between client and server. If this true Im sorry.

**Comment by hunter688** [comment]
Looks like https://github.com/minetest/minetest/commit/24e8b0ac1ea45719937948607259f13866c8bc64 solved this issue for me
