### ISSUE TITLE
Entity attached to player visible to other, but not to player itself

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#2570]
Probably there also should be a option if attached entity should be visible in 1st person mode or not.

**Comment by Calinou** [comment]
This is a good thing for mods like gauges (that add health bars above players), I think the current behaviour should stay.

Perhaps attached entities could have a flag to force their display anyway.

**Comment by 4aiman** [comment]
Yey! Someone misses this feature!
It's been over 2 years now...
Back then I've tried to make 3d armour out of entities :)

Anyway, with this optionally available it would be so much easier to add non-glitching weather effects by attaching a simple mesh to a player and making it animated!

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by paramat** [comment]
Any core dev support?

**Comment by paramat** [comment]
No core dev support for 3+ years so closing. Core devs feel free to reopen if you support it.
