### ISSUE TITLE
Android: Taking a screenshot floods the chat with an error

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2571]
Taking a screenshot (pressing the power button and one volume button simultaneously for most devices) floods the chat with an error message, seen here:
![screenshot_2015-03-28-19-41-13](https://cloud.githubusercontent.com/assets/8821916/6883449/d538f9d6-d583-11e4-93d1-6b2650c4f0d7.png)

**Comment by est31** [comment]
confirm, I have this too.

**Comment by Zeno-** [comment]
Strange... the keycode being sent is 0 which is invalid but I'm not sure from where. It seems to be irrlicht which is not handling SYM events, but I'm not sure

**Comment by kilbith** [comment]
Should be closed now.

**Comment by Zeno-** [comment]
@kilbith closed? Why?

**Comment by kilbith** [comment]
Thought it was fixed by 43aab618e52dd26b7d26f05db7df941489917a35

**Comment by Zeno-** [comment]
Nah, that's something different

**Comment by Wayward1** [comment]
Oops, just discovered this is a duplicate of #1454
