### ISSUE TITLE
ABMs are not happening fast enough.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2572]
I'm trying to make my own electricity mod. However, the ABMs used are not going very fast even with ```interval=0```. Even though manipulating nodes at that kind of speed would cause a LOT of lag, I think ABMs should be run more rapidly. With interval=0, I'm almost getting speeds of the ABM happening every 2 seconds. I know this isn't lag, because I make the ABM print every time it runs and I know its not printing fast and then very slow (which would be the case of lag.)

Can we make ABMs a little faster?

**Comment by PilzAdam** [comment]
0 is not a valid value for interval. Only integers >= 1 are allowed.

**Comment by C1ffisme** [comment]
@PilzAdam True. Still, I'd like to be able to not have problems with slow electronics.

At least an interval of 0 should make it go faster. Not instantly, but maybe every half-a-second if possible.

**Comment by paramat** [comment]
See #3805
