### ISSUE TITLE
Singleplayer world crashes on leave

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#2576]
Console output:
```
 >> === FATAL ERROR ===
 >> Access violation (Exception 0xC0000005) at 0x7C9213C0
 >> Saved dump to E:\Programme\minetest\bin\..\Minetest.dmp
R6025
- pure virtual function call
```

Minetest.dmp (crash) file: https://www.dropbox.com/s/i6ydhjixj5fvg3l/Minetest.dmp
First known bad: 93fcab95 (Build commit; not a bisect output)
Last know good: 538036d (Build commit; not a bisect output)

**Comment by kwolekr** [comment]
Does the problem still exist as of current HEAD?

**Comment by SmallJoker** [comment]
@kwolekr The problem extended. Current HEAD gives me following error `on startup`:
```
 >> === FATAL ERROR ===
 >> Access violation (Exception 0xC0000005) at 0x0067DB03
 >> Saved dump to E:\Programme\minetest\bin\..\Minetest.dmp
AL lib: (EE) alc_cleanup: 1 device not closed
```
https://www.dropbox.com/s/5eiq5loa19pmj2o/Minetest_150401.dmp

No, this isn't a 1st April joke.

**Comment by Zeno-** [comment]
@SmallJoker what flags are you using when building?

**Comment by SmallJoker** [comment]
Fixed after compiling current HEAD.
I guess 92f2069 solved the problem.
