### ISSUE TITLE
Feature Request : Building a world from a drawn map

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2577]
I'm sure one of the many reasons few of us make good maps for the forums is because of minetest's mapgen. See, you can add ```flat``` to ```mg_flags```, but what if you want to keep some realistic mapgen? What if you need to make an ocean? What if you need to build into mountains?

See, currently players don't have much control over mapgen, other than seed. Which is impossible to use to make maps.

What I suggest is a mapgen called "picture-gen" which takes a few arguments in the world creation window...
* Import Location : Biome map (This shows where biomes are, and is colored. Every pixel is a block. Per pixel, green shows grassy biomes, dark green pixels show where a tree is grown, orange makes a desert, white makes a snowy biome and blue makes an ocean. Other colors become grassland.)
* Import Location : Elevation map (Optional, but without it, the elevation should be based off of how far blocks are from water. This would be a grayscale picture the same size as the Biome map where lighter is higher.)
* Dropdown list : Picture edge filler (This is what to show outside of the picture's range. You can choose from a mapgen that will generate outside of the edges, or you can make it copy the picture in a gridlike fashion around the world.)

As soon as the world is created, the maps are sent into the world folder, so that mapgen can commence.

I hope this can be added to minetest. I hope to see many new maps created with interesting maps.

**Comment by PilzAdam** [comment]
This can be done is a mod, especially since the usecase you mentioned doesn't require much speed.

**Comment by C1ffisme** [comment]
True, but have you seen any mods that do this?

And what if I have a map of some country that's over 1000 pixels big?

Also, the pictures can't really be moved to the world folder. (At least, not in a way that I know of.)

**Comment by C1ffisme** [comment]
I also had this idea to switch from block based map-building to chunk based map building, where every pixel is a chunk. Of course, the elevation map remains the same, because otherwise you would have some very mountainous maps.

**Comment by ShadowNinja** [comment]
@kaeza made a mod that does something very similar -- although it imports images into existing maps.

I think this belongs in a separate map editing tool though.

**Comment by hunter688** [comment]
Will be fine have something similar to Terraincontrol - http://www.spigotmc.org/resources/terraincontrol.2214/ and for realistic world tool similar to WorldPainter - http://www.worldpainter.net/

**Comment by bugreport0** [comment]
Technically this would be possible to do and not super complicated for someone that understands mapgens.

The process might go something like this:
1. Import the image and use it as a baseline heightmap for the entire planet.
2. Mix the heightmap with terrain noise from a lua mapgens to give it the extra detail.

I have seriously considered this very process of mixing images with a mapgen to create super realistic planets with areas pre-planned out.

Now, having said that, I only mention this to say that it is possible... but I would not expect anyone to actually implement it.  The number of mapgen developers is not that big.


However, your request to import an image as a simple heightmap would be much easier to implement.  I bet many people could do that for you if you find the right person.  Many games have done this... take a greyscale image and convert it to a 2d heightmap.

**Comment by Zeno-** [comment]
It would be a pretty big image. For 256 height levels (maybe not enough) that's 32000x32000 = 1024000000 .... which is 100000KB => 976MB => 0.95GB

**Comment by paramat** [comment]
I'm not inspired to work on this, and hmmmm is super-busy. This method will have some problems that might not result in satisfying terrain, so the best thing to do is develop a good method in a lua mod to see if it can be made to work well, it could then *possibly* be transferred to core mapgen if it turns out impressive and useful enough.
Several players seem interested in this including fishywet and leetelate (who has some code, see https://forum.minetest.net/viewtopic.php?p=118665#p118665 and his SHUPA mods) the LOTT players might be interested also. You could get some talent together to work on the lua version.

**Comment by bugreport0** [comment]
> It would be a pretty big image. For 256 height levels (maybe not enough) that's 32000x32000 = 1024000000 .... which is 100000KB => 976MB => 0.95GB

Yeah, bad news for using them for an entire map.  My personal thoughts on using heightmaps was merely as a way to improve an already good mapgen, by using them to define generalities for the whole map and then having the mapgen generate the details based on that.  With this technique you could create some really unique stuff in a mapgen that you can't do with noise... because noise is often so predictable and repeats the same thing everywhere.
Note: Sorry for slightly offtopic post. :)

**Comment by C1ffisme** [comment]
I'm not suggesting that huge a map. Just maybe 1000x1000 that would loop over.

I mean, I doubt many players go past about 5000 blocks.

I did say many, there are a few who would go past that (I went to z=-10000 on a server one time).

**Comment by C1ffisme** [comment]
I just think of all the adventure maps possible. You could easily sculpt landmarks with this feature.

**Comment by paramat** [comment]
> by using them to define generalities for the whole map and then having the mapgen generate the details based on that

Yes, this. Small scale detail would be difficult and time-consuming to create on a huge image. Just a way to locate biomes and base terrain level.

**Comment by bobombolo** [comment]
check out realterrain mod: https://forum.minetest.net/viewtopic.php?f=11&t=12666

**Comment by C1ffisme** [comment]
Yeah, I saw that. I downloaded it even.
