### ISSUE TITLE
Static analysis using Coverity Scan

### ISSUE THREAD

**Issue by ngosang** [minetest/minetest#2584]
Maybe it's time to introduce another tool to help identify bugs: Coverity Scan
https://scan.coverity.com
It's free for open source projects and can hook up via Travis CI, I think its worth a try...

I tried it in my fork and he reports 153 defects in the code.

**Comment by Calinou** [comment]
Coverity is proprietary.

**Comment by ngosang** [comment]
> Coverity is proprietary.

It's but it's free to use in open source projects. LibreOffice and many other important projects use it to improve the code.

**Comment by ngosang** [comment]
@Calinou I don't understand why so much opposition. It's just a tool that tells you if there are parts of  code with problems. No need to heed the recommendations.

**Comment by Zeno-** [comment]
It's just a static analysis tool... I can't see how it would conflict with our code style guidelines
