### ISSUE TITLE
Formspec image_button crashes for empty filename (regression)

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2591]
Since 6d61375cc72bad5c569d25c253adca4e3701dd27 this code, which tries to display an `image_button` with an empty image filename, produces a crash:
```
minetest.register_on_joinplayer(function(player)
    local formspec = "size[3,3]image_button[1,1;2,1;;name;fallback_label;true;name]"
    minetest.show_formspec(player:get_player_name(), "test_formspec", formspec)
end)
```
Behaviour before the commit was analogous to nonexistent, non-empty filename strings: Tthe fallback label gets displayed instead. Those still work.
This issue also makes the client crash when the singleplayer tab is selected, with a game, that doesn't have a `menu/icon.png` file, as Sokomine originally reported.
@Warr1024 bug was since your commit.

**Comment by Zeno-** [comment]
92f20696eb57701d4d59adb5e9278315c2558180

**Comment by est31** [comment]
great, thanks!
