### ISSUE TITLE
Error in server log when players changing (successful) passwords

### ISSUE THREAD

**Issue by Miner59** [minetest/minetest#2595]
It seems I always get this error when somebody changes his password on my server:

11:14:49: ERROR[ServerThread]: PAssword packet size: 56 size required: 56
11:14:49: ACTION[ServerThread]: Guest1590 changes password

I connected myself as client and tested to change password and got the same message in server log.
But logging in with new password works, so it seems there's no problem, except this strange error message.
My minetest version is ~ 1 week old git version.

**Comment by est31** [comment]
1cb404522f1fd2f856383e10e409048468df0849
