### ISSUE TITLE
Android: Random spinning with cinematic_mode enabled

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2599]
While testing the latest Android build, 0.4.12.12, I noticed that when cinematic_camera_smoothing is enabled, the player will frequently spin while looking around. When I disabled cinematic_camera_smoothing, gameplay was normal.

**Comment by rubenwardy** [comment]
I can't reproduce this

**Comment by Wayward1** [comment]
I'm still able to reproduce this with a different device and newer Android.

**Comment by rubenwardy** [comment]
What's your Android version and vendor? Anything special about it?

**Comment by rubenwardy** [comment]
If I pan too far to the right, it every so often it jolts left - is this the bug you're describing?

**Comment by Wayward1** [comment]
Yes, that's it. Sorry, I should've been more specific in the description. Fire OS 5.3.1, based on Android 5.1.1

**Comment by rubenwardy** [comment]
The jolt is when going from 359 to 0 or vice versa - for some reason it goes 359 degrees the wrong way rather than 1 degree the right way (across the 360/0 border)

This happens for me with cinematic mode off, too
