### ISSUE TITLE
Android: No way to choose singleplayer worlds/subgames

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2600]
It seems two of the biggest features of Minetest are absent from the Android build: the ability to choose different subgames and worlds. From the viewpoint of a player, I prefer the Freeminer app to Minetest, as it offers both of those capabilities. With the Minetest app, you must switch worlds and games manually with the folder.

Minetest vs. Freeminer: 
![screenshot_2015-04-04-01-31-42](https://cloud.githubusercontent.com/assets/8821916/6991896/c4126770-da7c-11e4-9569-d0744408ed79.png)
![screenshot_2015-04-04-01-29-45](https://cloud.githubusercontent.com/assets/8821916/6991897/c70329ec-da7c-11e4-8603-dcb1f50a5945.png)

**Comment by C1ffisme** [comment]
Yikes, those are two features we've had since 0.4.0, and we didn't include them in android?

True, I suppose we saved many people's tablets and phones because they might have overfilled with worlds.

**Comment by nerzhul** [comment]
As i see Android has a dedicated interfact, Freeminer use the original interface.

**Comment by MoNTE48** [comment]
I prefer to use the standard menu. You can view the repository MultiCraft
https://github.com/MoNTE48/MultiCraft/tree/master/builtin/mainmenu

**Comment by ensonic** [comment]
+1 for using a menu more closer to the desktop version. I just copied a world over, but I can't select it.

**Comment by ShadowNinja** [comment]
I support using the full menu for Android too.  I don't see any advantage that the simplified menu provides.

**Comment by MoNTE48** [comment]
If you allow me, I will commit to which Android will be the menu is the same as on a PC. Should I do it?

**Comment by Wayward1** [comment]
Yes, definitely! I believe that would greatly improve the Minetest experience on Android.

**Comment by sapier** [comment]
Original menu doesn't fit a lot of android devices you just can't use it if you only see parts of it. 
As menu is configurable via minetest.conf those of you who want the big menu can still switch to it, just see minetest.conf.example for the parameter.

**Comment by MoNTE48** [comment]
@sapier You do not say. None of my players never complained that the menu does not fit on the screen. All of it works just fine, just do not need much to set up. You can see my code.

**Comment by Wayward1** [comment]
@sapier, there is no parameter in the minetest.conf.example that allows Android users to choose the full menu; perhaps you meant gui scaling?

**Comment by sapier** [comment]
well there is but obviously someone not having knowledge about how to use it did break main menu so it doesn't work any longer

the parameter I'm talking about is:
main_menu_script =
initially there have been two init.lua files one for android one for pc but obviously someone did merge them making the merged version autodetect what to do

**Comment by Wayward1** [comment]
Ah, ok.

**Comment by spyjoshx** [comment]
@sapier I've tried your solution twice (once on android, once on desktop) and found the following:
- android DOES have both menu scripts
- when I change the main_menu_script parameter in minetest.conf the game crashes immediately on both platforms.
Do you have any reccomendations?

**Comment by MuhdNurHidayat** [comment]
I hope the Android port will eventually have the ability to choose different world and different subgame, I'll be waiting for this.

**Comment by paramat** [comment]
Can anyone fix the setting which allows normal menu on Android?

**Comment by Wayward1** [comment]
Fixed by https://github.com/minetest/minetest/commit/0e4c467a8248d1bd2cf658096f8476ce07c86c63

**Comment by rubenwardy** [comment]
I don't think this has been resolved, as it requires users to modify their settings. It should be possible to make multiple worlds without doing that

**Comment by paramat** [comment]
Should this be a blocker for 5.0.0?

**Comment by paramat** [comment]
The so-called 'simple menu' is more crowded than the normal menu, why not just remove the simple menu code completely?

**Comment by paramat** [comment]
Keep in mind that it seems that MultiCraft will no longer be developed, so we may then have over a million players looking for a new app to use, since MultiCraft was probably tjhe best forked app the choice will be moving to a worse app (making those players more annoying on servers) or moving to the official app.
So we need to be better than MultiCraft in every way.

**Comment by rubenwardy** [comment]
I'm in favour of removing the simple menu, and using the full one

**Comment by juozaspo** [comment]
A full menu looks neat (with a patch from #7934, fixes a few build errors) . The only useless/not working button is reset singleplayer world button in options page when using full menu. Screenshots when `main_menu_style = full`:

<details>

![screenshot_20181203-183652](https://user-images.githubusercontent.com/6626242/49387815-70a02d00-f72b-11e8-8df3-58bfa059bd38.png)
![screenshot_20181203-183702](https://user-images.githubusercontent.com/6626242/49387825-739b1d80-f72b-11e8-9663-3fcba5e37fa6.png)
![screenshot_20181203-183708](https://user-images.githubusercontent.com/6626242/49387832-75fd7780-f72b-11e8-855e-6bcf3d1fa42b.png)
![screenshot_20181203-183713](https://user-images.githubusercontent.com/6626242/49387833-785fd180-f72b-11e8-8e66-f2b594829f26.png)
![screenshot_20181203-183719](https://user-images.githubusercontent.com/6626242/49387838-7ac22b80-f72b-11e8-8cb1-db00944852ea.png)

</details>

**Comment by paramat** [comment]
Good, we could vertically shrink the menu by moving 'play game' to the left of the other buttons?

**Comment by MoNTE48** [comment]
...and disabling minetest logo for phones (based on code in your last PR)

**Comment by paramat** [comment]
I expect the main box of the 'start game' menu will be fine as it's automatically the same size as the other main pages, it's just the added game box below that might be close to screen edge.

**Comment by paramat** [comment]
#7940 and #7936 merged. Full menu now set as default and hopefully usable on all Android devices, if not please comment here.
