### ISSUE TITLE
builtin crash issue

### ISSUE THREAD

**Issue by neko259** [minetest/minetest#2601]
/builtin/game/misc.lua:28: Invalid core.after invocation

Not sure how to reproduce it

**Comment by est31** [comment]
No backtrace available?

**Comment by neko259** [comment]
@est31 Nope. This line is the only one, that's why I said I don't know what caused it and how to reproduce. I was not on the server at the time and only saw the line in the log.

**Comment by est31** [comment]
ok closing now. It can be reopened if it turns out to be an engine bug.

**Comment by neko259** [comment]
> It very much seems like a mod having done things wrong.

At least it should show a stack trace, otherwise I don't know which mod was that and what was wrong. Can the trace be fixed?

**Comment by est31** [comment]
Can you publish an excerpt of the log somewhere?
