### ISSUE TITLE
Crash caused by taking a screenshot

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#2603]
Available errors: None; crashes without any log mesage or .dmp file.

Possible source of this bug:
862d4ea : `screenshot_YYYY-MM-DDTHH::MM::SS[-serial].png`
`:` is not allowed in filenames.

**Comment by nerzhul** [comment]
":" is not allowed on windows if i remember. We must be compliant with both Linux/UNIX, Windows and Mac OSX

**Comment by nerzhul** [comment]
@Zeno- because you are the owner of the screenshot patch, could you fix the path to be compliant with all OS ?

**Comment by Zeno-** [comment]
High priority? Ok, onto it!

**Comment by Zeno-** [comment]
43aab618e52dd26b7d26f05db7df941489917a35

**Comment by Zeno-** [comment]
oops ... didn't mean to re-open
