### ISSUE TITLE
 player:override_day_night_ratio() now results in a dark landscape

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#2607]
Discovered while checking my moonrealm mod, present 1 April 2015 at 74eb14cc804c2f51c97d94bebeb38661177f3806, not present on 14 July 2014.
Interestingly player:set_sky() and set_physics_override() still work fine.
My usage in moonrealm mod, the ratio of 1 is to set a constant maximum brightness:
https://github.com/paramat/moonrealm/blob/master/init.lua#L133

**Comment by C1ffisme** [comment]
Screenshots?

**Comment by SmallJoker** [comment]
I can not reproduce this bug with the current yesterday's git version.

**Comment by paramat** [comment]
Thanks, good to see it works 'on joinplayer'. My usage is different, i use it occasionally in 'globalstep' so that skybox, physics and light level all change when entering or leaving a chosen section of the world, so that the moonrealm can be added to a core mapgen. Because the moon is in the sky i want to have it as another realm stacked above the normal realm.
https://github.com/paramat/moonrealm/blob/master/init.lua#L133

**Comment by paramat** [comment]
Experimenting, i find the bug happens when trying to override day/night ratio on joinplayer in singlenode mapgen. I now have a workaround to avoid this bug, overriding on globalstep. Something has changed in Minetest to cause this bug but i have laballed it as low priority. I'm not even sure it is worth keeping open as an issue.
