### ISSUE TITLE
Remove “Activate all” button in mod manager (Discuss)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2617]
The button “Activate all” in the mod manager activates all mods you have installed.

I think this button is really pointless. I never needed to click it. In fact, clicking this button is pointless especially for me, because I have a ton of mods installed and a few mods have incompabilities between them.
The more mods you have installed, the more likely it is you end up with an unstable or broken mod configuration if you blindly activate all mods and start.

I suggest to remove this button altogether, because it only leads to confusion for newbies and has probably no use anyways.

Please discuss.
Do you have an opposing opinion? In that case, I would like to hear it.

**Comment by SmallJoker** [comment]
Yes, that button is never used by anyone.
Some of my mods are just for testing features and would throw errors on startup.

**Comment by PilzAdam** [comment]
The button was added because people complained when mods where made opt-in instead of opt-out.

**Comment by kilbith** [comment]
IMO, the inverted functionality (i.e. "Disable all") can be useful, though.

**Comment by yo-we** [comment]
Hello, I use this button. The use-case is as follows:
 * I have a script to duplicated the mods in use on the server and bring them to another PC/server.
 * I "activate all" to have the same configuration as the server and carry out my tests
Having loads of mods, activating them one by one is too time-consuming. Activating 150 at a time and then deactivating 2 or 3 is quite fast.

**Comment by Calinou** [comment]
I use this button too, please don't remove it. In fact, I would like a "Disable All" button to go along with it.

**Comment by Holyphoenix** [comment]
I use the button all the time, please don't remove it.   

Also I +1 Calinou's idea of adding a disable all button.

**Comment by donat-b** [comment]
Tip: make a toggle button.

**Comment by yo-we** [comment]
donat-b: The Toggle does not fit in any of my use cases, except that it could be used to replace "activate all" if you are *sure* that nothing is activated, yet. That requires to check if any of the mods is already activated....no problem if you run 3 or 4 mods, but quite some work if there are plenty of them.

**Comment by donat-b** [comment]
@yo-we This is what I meant - make one toggle button instead of activate/deactivate all.

**Comment by yo-we** [comment]
@donat-b It does not do the same, which is what I tried to explain. Logically, "toggle" can only replace "(de)activate all" under the supplementary condition that the activation state of all mods is known and identical when pressing the toggle button.

**Comment by Wuzzy2** [comment]
Okay, since enough people do not want this button to be removed, I am closing this issue.

**Comment by C1ffisme** [comment]
As a side note, maybe the disable all button should be available at all times. Also, add a search for people who have lots of mods.
