### ISSUE TITLE
wiki.minetest.net (discussion)

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#2622]
We have a wiki at wiki.minetest.net. It hasn't been updated as much as I would like. Recent additions like mese lamps, beds and vessels shelves are not documented, many textures are missing or not updated, and most (heck, all of them really) of the pages are very tiny. Just compare the pages to the minecraft wiki at minecraft.gamepedia.com. In fact, I'll go ahead and give you some links.

- [Minecraft Cobble](http://minecraft.gamepedia.com/Cobble)
- [Minetest Cobble](http://wiki.minetest.net/Cobble)

Note that the page for minetest cobble is one of the bigger pages because of all the crafting recipes. You can find a smaller page for straw.

Okay, so Minecraft has more features to document. So what? Even then they describe more. They even give a history of cobble.

Here is what I suggest we change : 
- Add history
- Add a block at the bottom that links to other things in that category. (Other blocks, etc.)
- Add in all missing textures and update old ones
- Add a gallery (Make sure all screenshots are in VANILLA minetest unless a picture description tells what mods were used)
- Finish all the mod sub-wikis and delete the mod wikis that nobody cares about. Also, add sub-wikis for the more famous mods (All the ones that are in the mods menu on the website.)
- Add a section called "Inspiration" which contains information of where this block might be used.
- Add more pictures!!!
- Add a more descriptive description. For example, rather than saying cobble is a decorative block, say something like:

> Cobblestone is a very common block used for building. It is very grey and looks boring without 
> being combined with other blocks. Cobblestone is useful for roads and walls. You can find it when > mining stone, which makes it very common. Cobblestone is very useful for making your first house.

Sorry if this was offtopic, but we don't really have a github page for the minetest wiki, so I thought this was the best place to share my concerns. Thank you for reading (if you have).

**Comment by Calinou** [comment]
There are discussion pages on the wiki, please use that instead of GitHub issues. As a last resort, you can use the forum.

**Comment by C1ffisme** [comment]
I don't have an account on the wiki (or the forum, please don't comment me on that), but also the discussion pages might just NEVER get read. Because no one seems to moderate it anymore.

It's not like a Github issue is going to pump venom into poor creatures' hearts or anything. One issue is not too much for discussion.

**Comment by PilzAdam** [comment]
This is not the right place to discuss the wiki.

**Comment by kilbith** [comment]
Problem with you, factually, is that you open lot of "issues" that are pointless, wacky or offtopic : https://github.com/minetest/minetest/issues/created_by/C1ffisme

Your place is definitely on the forum.

**Comment by rubenwardy** [comment]
GitHub is not the forums. This is for development, not chatter.

**Comment by est31** [comment]
@C1ffisme you can ask @ShadowNinja or other wiki admins to give you an account. The wiki is open for contributors.
This issue tracker is about the core minetest engine. Closing.

**Comment by C1ffisme** [comment]
Goodness. We seem to think organization is more important than getting it done now.

I'm starting to wonder if anyone reads these issues or just looks at the title and screenshots.

**Comment by est31** [comment]
I have read the issue description, and agree with it. As I already said, the wiki is open for contributors, so join and add the content :) It would be really good if you had time to contribute. This however isn't the right place to discuss that.
