### ISSUE TITLE
The mysterious patchy forests of the biome API

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#2639]
In mgv5/v7 for months now, forests which are meant to be thick and solid become increasingly patchy in hilly areas. Only schematic decorations are affected, simple decorations such as junglegrass act as they should and are uniformly thick on the ground. The bug is best seen in the rainforests of my biomesdev mod https://github.com/paramat/biomesdev because they are the only forests that are defined to be thick and solid with no density variation.

In low completely flat landscape the rainforest acts as it should:

![screenshot_20150421_041240](https://cloud.githubusercontent.com/assets/3686677/7245107/a64a8fc4-e7dd-11e4-8ab4-77a589570e9f.png)

Now if i increase the vertical scale of the landscape the forest becomes increasingly patchy. The patchy areas are the hilly areas, the low flat areas act as they should. The patchiness is at all altitudes and has no obvious pattern when seen from above. Jungletrees are not cutoff at any altitude (they are 16 nodes high so fit into the mapblock shell around a mapchunk) :

![screenshot_20150421_034931](https://cloud.githubusercontent.com/assets/3686677/7245119/d2f3b2f8-e7dd-11e4-8c66-551e2d6829b2.png)

Another weird thing, adding default:dirt to the 'place on' nodes increases the density, even though all surface nodes are grass. Here are 2 screenshots of the same terrain to show the effect of that change:

![screenshot_20150421_040211](https://cloud.githubusercontent.com/assets/3686677/7245144/40c73c3c-e7de-11e4-9fa6-3904bfbf9325.png)

![screenshot_20150421_040337](https://cloud.githubusercontent.com/assets/3686677/7245145/498623b0-e7de-11e4-8cab-5783aac2b18e.png)

Now adding "air" to 'place on':

![screenshot_20150421_043421](https://cloud.githubusercontent.com/assets/3686677/7245285/5029ea74-e7e0-11e4-969a-9c0af1cc4412.png)

Now adding "default:stone" to 'place on' the trees finally become almost solid everywhere and many are sunken into the ground:

![screenshot_20150421_043738](https://cloud.githubusercontent.com/assets/3686677/7245291/75bac222-e7e0-11e4-80dd-71ad6e095579.png)

It's almost as if the heightmap is becoming detached from the terrain in hillier areas, however schematic decorations are placed as simple decorations are, and they are unaffected by the bug.

**Comment by paramat** [comment]
I found the cause: flags = "place_centre_x, place_centre_z",
These are somehow displacing the place_on node check sideways, on flat ground this is not a problem, as the groound gets more hilly there is more chance the place_on check will be under- or over-ground, which is why adding dirt, air or stone to place_on increased the density.
Will attempt to fix.

**Comment by paramat** [comment]
Now fixed.

**Comment by Zeno-** [comment]
With a title like this issue has I was expecting a more exciting narrative... possibly including dragons, orcs, elves and mysterious adventures.

**Comment by C1ffisme** [comment]
@Zeno- LOL.
