### ISSUE TITLE
Set viewing_range both equal for min and max

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2644]
Somehow it seems the game runs better and stabler on lower hardware in setting (example) : 
```
viewing_range_nodes_min = 50
viewing_range_nodes_max = 50
```
Instead of just :  `viewing_range_nodes_min = 50`

^ The latter case looks odd and unstable (viewing range randomly goings and comings -- FPS drops accordingly).

Therefore, pressing **[+]** or **[-]** ought set equals values for min and max.

**Comment by PilzAdam** [comment]
What do you mean by "it runs better"? Maybe you just want to increase wanted_fps?

**Comment by kilbith** [comment]
> Maybe you just want to increase wanted_fps?

No-no... by "runs better" I meant that you have higher performances and smoother playing because there's no longer those weird viewing range randomly goings and comings from afar (_max ain't set by default).

@Sokomine can confirms it as well : [here](https://forum.minetest.net/viewtopic.php?f=5&t=11560&p=173671#p173671).

**Comment by lightonflux** [comment]
I can confirm as well. 

First i only had 
> viewing_range_nodes_min = 55
in the conf. 

When i look at a jungle (many waving leaves) the framerate dropped to 28 - 35 fps.

When i added the following line it was in the 40 range sometimes dropping to 30-something but never below and mostly between 40-45.

> viewing_range_nodes_max = 55

**Comment by Megaf** [comment]
I can confirm that. Using the same value for max and min increase the gameplay a lot, makes it fluid.

Minetest will slowdown and hickup when switching from min to max back to min.

**Comment by Pilcrow182** [comment]
I can confirm this as well. It's always seemed like minetest takes quite a bit of power when calculating a new view range, especially on low-powered hardware. Every time it happens, the framerate spikes downward and back up. I've been playing with 50min/50max since 0.4.8, actually; it's been happening for a long time...

**Comment by kilbith** [comment]
I still militate for those settings by default, as many people report a significant performance improvement with the same value on _min and _max.

**Comment by paramat** [comment]
I set them equal myself, seems better.

**Comment by PilzAdam** [comment]
Maybe the view range adjustment algorithm needs tweaking? @celeron55 usually does this.

**Comment by celeron55** [comment]
Well it's probably impossible to make a markedly better algorithm. If you improve it for someone, it will be worse for someone else.

Just add these options to the GUI with an option to disable the adjusting algorithm (the GUI can disable it by setting identical min and max values).
