### ISSUE TITLE
Add CONTRIBUTING(.md)?

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#2645]
We have a [few] (http://dev.minetest.net/Code_style_guidelines) [pages] (http://dev.minetest.net/Lua_code_style_guidelines) on devs wiki regarding code style guidelines/contribution rules. And GitHub has a nice [contribution guidelines] (https://github.com/blog/1184-contributing-guidelines) integration. I think it is better to have these rules in the repo than on separate resource, so everyone who makes a Pull Request may fix some small style mistakes and don't waste reviewers time.

I guess, project's contributors also may be listed in this file.

**Comment by Calinou** [comment]
It should be `CONTRIBUTING.md`. Credits can be contained in a file named `AUTHORS.md`.

**Comment by Calinou** [comment]
It should be `CONTRIBUTING.md`. Credits can be contained in a file named `AUTHORS.md`.

**Comment by paramat** [comment]
#3142 is merged.
