### ISSUE TITLE
Snowbiomes (#2598) possibly fail to display

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#2646]
When adding the new snowbiome flag to mv6, I get this weird result : 
![img](http://i.imgur.com/ugkduep.png)

mapgen params are : 
```
mg_name = v6
mg_flags = trees, caves, light, nodungeons, snowbiomes
mgv6_spflags = jungles, biomeblend, mudflow
enable_floating_dungeons = false
```

Minetest version : 
```
Minetest ac6efa2
Using Irrlicht 1.8.1
Build info: VER=ac6efa2 BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=0 STATIC_SHAREDIR="."
```

Extra info : 

```
Irrlicht log: Using renderer: OpenGL 3.0
Irrlicht log: Mesa DRI Intel(R) Ivybridge Mobile : Intel Open Source Technology Center
Irrlicht log: OpenGL driver version is 1.2 or better.
Irrlicht log: GLSL version: 1.3

OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.6.0-devel (git-125574d 2015-04-23 utopic-oibaf-ppa)
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.6.0-devel (git-125574d 2015-04-23 utopic-oibaf-ppa)
```

*I have not encountered any texture error while playing my large steam library, so I doubt my mesa version is the problem.

**Comment by est31** [comment]
Which game version do you run?

**Comment by indriApollo** [comment]
4.12-dev

**Comment by est31** [comment]
Is it up to date?

**Comment by paramat** [comment]
Weird. yes you will need the latest version of Minetest Game. Also, the 'snowbiomes' flag must be in 'mgv6_spflags' not 'mg_flags'.

**Comment by indriApollo** [comment]
Now running latest master and minetest_game, everything works fine. Thank you @est31 and @paramat (your snowbiome is amazingly beautiful btw <3)

**Comment by kilbith** [comment]
Next time before reporting an issue, be sure to be up-to-date both with the engine and game. Also don't use an unstable, devel version of Mesa that contains bugs (verified on that PPA).

This isn't serious...
