### ISSUE TITLE
mapgen mv6 generates caves underwater

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#2647]
Shouldn't water_source and water_flowing be "no_ground_content" ?
![img](http://i.imgur.com/97WlJ9g.png)

**Comment by Wayward1** [comment]
I noticed this too

**Comment by paramat** [comment]
Water nodes are 'is_ground_content = false' in latest version of MTGame, try updating. Mgv6 cavegen checks for water were therefore at the same time removed, which causes this bug. Let me know if updating MTGame fixes this for you.

**Comment by indriApollo** [comment]
Yes, Updating minetest_game fixed my issue. Thank you @paramat  :)
