### ISSUE TITLE
set_look_pitch and set_look_yaw do not work.

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#2649]
unrelated maybe: log out, log back in, yaw/pitch are not preserved (unrelated maybe? but this should be preserved imho)

the real bug is:

player:set_look_yaw|pitch(rad) don't work. Player camera angle does not change after these methods are called from lua.

e.g.

  player:set_look_yaw(yaw)
  player:set_look_pitch(pitch)

fails to achieve any camera angle change no matter value of yaw/pitch.

**Comment by Etzos** [comment]
I did a quick git bisect and it appears as though the first bad commit is d65a90a. The set_look_yaw() and set_look_pitch() will work if cinematic mode is on, but not if it's off (and it defaults to off).

**Comment by sofar** [comment]
That correctly fixes the yaw/pitch after player:set_look_yaw/pitch() on my system, both in cinema "smooth" view and without (F8).

Please merge.

**Comment by Zeno-** [comment]
@Etzos Thanks for the bisect. I'll merge the fix when I get back to my main computer (unless someone does it before me)

**Comment by est31** [comment]
400c6087b6da0d4563573189535ba58f589bd7ae
