### ISSUE TITLE
Dungeon generation takes over much of the map

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2652]
Latest build, when creating a new world dungeon generation runs rampant, covering much of the map. I tested it three times, once with Carbone (when I first noticed it), and twice with the latest minetest_game. 

![screenshot_2015-04-25-18-23-14](https://cloud.githubusercontent.com/assets/8821916/7335151/2d4903c2-eb79-11e4-9dc7-f7773c5509fd.png)
![screenshot_2015-04-25-18-19-20](https://cloud.githubusercontent.com/assets/8821916/7335152/450c6116-eb79-11e4-9373-e2138a7aa740.png)
![screenshot_2015-04-25-18-21-33](https://cloud.githubusercontent.com/assets/8821916/7335154/71f3b512-eb79-11e4-94b3-91d6cdd65b67.png)
![screenshot_2015-04-25-18-22-33](https://cloud.githubusercontent.com/assets/8821916/7335155/7baa774e-eb79-11e4-958c-7b52bdedb152.png)

**Comment by paramat** [comment]
Wow, that's certainly too much dungeon. Android only?

**Comment by Zeno-** [comment]
@paramat There is no way that can be Android only...

**Comment by Wayward1** [comment]
Nope, not just Android:
![screenshot from 2015-04-26 10 37 47](https://cloud.githubusercontent.com/assets/8821916/7337804/0051f040-ec05-11e4-95a2-76404725df67.png)
![screenshot from 2015-04-26 10 38 05](https://cloud.githubusercontent.com/assets/8821916/7337807/232cb53c-ec05-11e4-83e0-8d62b3c09d59.png)
It seems the mapgen is fine before dungeongen, but as soon as one forms, they keep going.

**Comment by paramat** [comment]
I haven't touched dungeon stuff for a while. Your worlds seem overly eaten by large caves too, as if they are generatng too much also.

**Comment by C1ffisme** [comment]
> It seems the mapgen is fine before dungeongen, but as soon as one forms, they keep going.

Hmm... Maybe rooms just keep growing?

If it's not that, than maybe we just need to make dungeons rarer.

**Comment by paramat** [comment]
> Hmm... Maybe rooms just keep growing?
No, each dungeon is the normal size there's just way too many of them.
> If it's not that, than maybe we just need to make dungeons rarer.
Nope, this is a bug for sure, when the bug does not occur the dungeon rarity is normal and is fine.

**Comment by C1ffisme** [comment]
When was the last time anybody touched dungeon code?

Does it happen before that commit?

**Comment by Wayward1** [comment]
Really sorry guys, this may have been a false alarm >.<  I rechecked my .conf file, and found I had chunksize = 1 in there. I must have missed that when I first checked the .conf prior to reporting this.

**Comment by paramat** [comment]
That's a relief, and explains the number of dungeons and large caves, since they are a fixed number per chunk they were 125 times more common.
