### ISSUE TITLE
Make cloud radius adjustable

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#2662]
https://github.com/minetest/minetest/blob/master/src/clouds.cpp#L102
Cloud radius is the distance to the furthest displayed cloud measured in 64 node cloud squares. Currently only 12 = 768 nodes:

![screenshot_20150501_204611](https://cloud.githubusercontent.com/assets/3686677/7436626/48b2e0ba-f047-11e4-831d-ecee085442bd.png)

It can be increased to almost 32 = 2048 nodes before the 2 kilonode cloud cutoff chops the displayed clouds:

![screenshot_20150501_204435](https://cloud.githubusercontent.com/assets/3686677/7436632/574a1daa-f047-11e4-915e-edd0abcc7b3a.png)

This creates a vast spacious feel to the game. A large radus may affect game performance if clouds are 3D, the default should of course stay as it is for slower computers using 3D clouds.

At a 'realistic' cloud height of 1024 the cloud area is no longer a small square in the sky:

![screenshot_20150501_205809](https://cloud.githubusercontent.com/assets/3686677/7436645/7437f112-f047-11e4-9576-6d9ed6fc7b38.png)

However here you can see the 2kn cutoff is clipping the clouds, a smaller cloud radius would be preferable, but this depends on cloud height.
Calculating, a maximum radius of 22 will avoid any clipping of the cloud area corners, with standard cloud height.

**Comment by C1ffisme** [comment]
Oh wow, that looks much better.

**Comment by kilbith** [comment]
Question : why the clouds are cut-off diagonally there ? (we don't see that with the current clouds).

![7437f112-f047-11e4-9576-6d9ed6fc7b38](https://cloud.githubusercontent.com/assets/7883281/7440877/f6dbf8b2-f0cd-11e4-8d9b-a3b1de0c4e7b.png)

**Comment by paramat** [comment]
Clouds are always clipped at 2kn from the player along a line perpendicular to the players view, and it depends on view pitch also, That screnshot has radius 32 which hits the clipping distance, a radius of 22 would avoid most clipping.

**Comment by Megaf** [comment]
I think we should figure out a new way to draw clouds, clouds should always be "infinite" (They should disapear with the horizon). There are lots of games that are able to draw very realisitc clouds with almost no perfomance hit. In minetest they are just a decoration anyway...

**Comment by paramat** [comment]
![screenshot_20150502_205949](https://cloud.githubusercontent.com/assets/3686677/7442579/f02db9c4-f10e-11e4-96c9-9d7f7aa51d28.png)

Radius = 22 (1408 nodes) merges nicely with the horizon haze, and has no clipping of the cloud area corners with a standard cloud height.

![screenshot_20150502_205830](https://cloud.githubusercontent.com/assets/3686677/7442602/99b6cf8a-f10f-11e4-9e74-9d37cffef206.png)

At 1024 nodes above the clouds, the clipping is there but is very soft and hazy with no noticeable cutoff line, so 22 seems optimum.

**Comment by paramat** [comment]
So the issue is, is this needed/wanted enough to justify another setting in .conf? I think yes, just, but there is some resistence to yet another setting. State your support here to help this be added =)

**Comment by falsechicken** [comment]
I personally am all about options. :+1:

**Comment by kilbith** [comment]
I support the setting in .conf, as everything that impact appearance and/or performance in game.

**Comment by RHRhino** [comment]
More settings are always interesting for us players and .conf settings also ensure that only advanced players find a way to play with the values of the settings, while new players are not bothered and confused with them. I'm for it. :+1: 

What about the 3D clouds: Is there a huge performance drop if you increase the Cloud radius setting from 12 to 32??

**Comment by Amaz1** [comment]
I would like this to be added! :+1:

**Comment by LollenJumplan** [comment]
+1 for that! Why should it be a problem to have many options? I always found the opposite to be true.

**Comment by paramat** [comment]
![screenshot_20150504_164246](https://cloud.githubusercontent.com/assets/3686677/7456739/aea26a24-f27e-11e4-9e6c-21f67f3b3fb2.png)

Testing 3D clouds with radius 32 i get a barely noticeable drop of 1 FPS compared to the default radius of 12. So with the optimum radius of 22 the FPS drop will be even smaller.
So this has turned out successful i will try to get this merged as a .conf setting.

**Comment by paramat** [comment]
Merged. I find the optimum maximum to be roughly 26, there is a slight clipping of the cloud area corners but it is very hazy and soft with no noticeable cutoff line.
