### ISSUE TITLE
Wielding certain items causes HUGE FPS sag

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#2667]
Minetest commit 0c792db05c9e53a2e5dd7f6462f8aaa561fde858
Using default textures.

Appears to be related to the texture scaling feature controlled by texture_min_size, as setting it to 128 (instead of 256 as in the config below) reduces the severity of the hang/sag, and commenting that line out entirely is enough to reduce the hang/sag to imperceptibility.
 
Steps to reproduce:

* Get homedecor modpack, make sure it's up-to-date (at least to commit https://github.com/VanessaE/homedecor_modpack/commit/2f9efc2807a4f5aaf5a08a3fa99f19754e66cc04 anyway).
* Add any random *default* item to your inventory, such as cobble.
* Wield the above item (cobble).
* Give yourself fake_fire:fake_fire.  Move it into your hotbar if necessary.
* Roll your mouse wheel or press a number key to wield the fire in your hotbar.

When switching wielded items, the client normally animates the swap between items, sliding one off the screen and sliding the other on.  In this case, just as the "default" item finishes sliding off the screen *but before it is completely gone*, the client's FPS will drop to 0 for a second or two, and then the fire will appear.  This is repeatable - if you wield the pick again, and then switch back to the fire, the pick will slide off the screen and the FPS will sag out just before it disappears, before the fire replaces it.

Using an AMD R9 280x with binary ATI fglrx driver, Xubuntu 14.04.

Client config:
```
address = digitalaudioconcepts.com
main_menu_tab = singleplayer
name = VanessaEzekowitz
port = 30010
server_dedicated = false
free_move = true
mainmenu_last_selected_world = 13
selected_world_path = /home/vanessa/.minetest/worlds/Dreambuilder-testing

main_menu_last_game_idx = 1
anisotropic_filter = false
mainmenu_last_selected_TP = 3
mip_map = false
texture_path = /home/vanessa/.minetest/textures/halo
trilinear_filter = false
preload_item_visuals = false
public_serverlist = false
enable_shaders = false
noclip = true
aux1_descends = true
doubletap_jump = false
fast_move = true
keymap_backward = KEY_KEY_S
keymap_chat = KEY_KEY_T
keymap_cmd = /
keymap_console = KEY_F10
keymap_drop = KEY_KEY_Q
keymap_fastmove = KEY_KEY_J
keymap_forward = KEY_KEY_W
keymap_freemove = KEY_KEY_K
keymap_inventory = KEY_KEY_I
keymap_jump = KEY_SPACE
keymap_left = KEY_KEY_A
keymap_noclip = KEY_KEY_H
keymap_print_debug_stacks = KEY_KEY_P
keymap_rangeselect = KEY_KEY_R
keymap_right = KEY_KEY_D
keymap_sneak = KEY_LSHIFT
keymap_special1 = KEY_KEY_E

enable_bumpmapping = false
disable_fire = true
fixed_map_seed = 
mg_name = v6
sound_volume = 0.52
enable_waving_leaves = false
enable_waving_plants = false
enable_waving_water = false
creative_mode = true
remote_port = 30006
enable_parallax_occlusion = false

enable_vbo = true
time_speed = 0

font_size = 17
mono_font_size = 17
font_shadow = 2
font_shadow_alpha = 255
font_path = /home/vanessa/.minetest/fonts/DejaVuSans.ttf
mono_font_path = /home/vanessa/.minetest/fonts/DejaVuSansMono.ttf

curl_parallel_limit = 32

bilinear_filter = false
generate_normalmaps = false
normalmaps_smooth = 0
enable_damage = false
enable_clouds = 0
maintab_LAST = singleplayer
menu_last_game = dreambuilder

enable_item_drops = false
enable_item_pickup = true
remove_items = 10

ignore_world_load_errors = true
enable_particles = true
enable_water_surface_shader = true
video_driver = opengl

world_config_selected_mod = 1
viewing_range_nodes_min = 35
active_block_range = 1
connected_glass = false

enable_mesh_cache = false
enable_node_highlighting = false

cinematic = false

gui_scaling_filter = true
texture_min_size = 256
texture_clean_transparent = true

wieldview_node_tiles = false
wieldview_update_time = 2
```

**Comment by Etzos** [comment]
Just as a note I am unable to reproduce this bug using minetest master and homedecor master.

I'm using the Radeon driver (r600) with an older graphics card, so perhaps this is a driver bug (or something driver-related)? Can anyone else attempt to reproduce this?

**Comment by VanessaE** [comment]
Commenting-out these lines in my config stops the sagging:

gui_scaling_filter = true
texture_min_size = 256
texture_clean_transparent = true

**Comment by VanessaE** [comment]
Commenting-out the "texture_min_size = 256" line is enough to stop the hangs/FPS sags.

**Comment by Etzos** [comment]
I am able to reproduce this now. For some reason it didn't work the first time I tried it, but now after adding `texture_min_size = 256` to my config file it causes the FPS drop.

**Comment by kwolekr** [comment]
Is that commit you mentioned when you first started noticing the problem, or did you find through revision history bisection that it was the commit causing the problem?

**Comment by VanessaE** [comment]
The commit mentioned is just where my copy happens to be at.  Never noticed the problem before because I basically never have nodes like the fake fire in my inventory, normally.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/5fa4fed09731fa869cfcee5c15e53d9fbdedc28b
