### ISSUE TITLE
Missing faces for liquids

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#2674]
There still are missing faces for liquids (probably related to #439):
![screenshot_20150505_141135](https://cloud.githubusercontent.com/assets/2923554/7472344/cd53858a-f331-11e4-8a7c-7e9f33b75398.png)

To reproduce, build the following structure:
![screenshot_20150505_141901](https://cloud.githubusercontent.com/assets/2923554/7472342/c5149418-f331-11e4-8fd1-87a57e5a7054.png)
then look from the side:
![screenshot_20150505_141909](https://cloud.githubusercontent.com/assets/2923554/7472348/d464cabe-f331-11e4-84f6-7c3e7de82574.png)

**Comment by PilzAdam** [comment]
It seems like it's the bottom tile for the flowing nodes that is missing.

**Comment by paramat** [comment]
Looks like liquid base and side tiles are not visible when seen through 2 glass blocks.

**Comment by Novatux** [comment]
@PilzAdam: yes; bottom tile is missing when the liquid is over something else (I didn't test with liquid over another liquid, though)

**Comment by paramat** [comment]
The 3rd lava node up in that column is missing a side tile, but side tiles are visible through one glass node.

**Comment by DS-Minetest** [comment]
this is a bigger problem than you think . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . :skull: 
just think if someone digs up and there is lava,when  the player sees it hes already doomed to die :fire:

**Comment by Wuzzy2** [comment]
It's definitely the bottom face which is missing, and it *only* affects flowing liquids. I can not confirm any claims relating this bug to glass. Liquid sources appear to be OK.
Here's a recent screenshot from Minetest 0.4.15 (using MineClone 2, but it's same for all other subgames) which should make this bug very obvious to see:

![Missing bottom face of water](https://i.imgur.com/B1tC5Ma.png)

As you see, left and right side faces are rendered, but not the bottom face. Note the liquid is 

I fully agree with DS-Minetest. If you look from lava “falling” downhill, it is very hard to see the node contours, making any flowing liquid dangerously deceptive when viewed from below.

**Comment by paramat** [comment]
Yes i have noticed this too, a large volume of lava can appear non-existant.

![screenshot_20170313_164110](https://cloud.githubusercontent.com/assets/3686677/26275212/9f146bee-3d53-11e7-90fc-08193bbd099d.png)

**Comment by Wuzzy2** [comment]
Good for 0.5.0 milestone?

**Comment by paramat** [comment]
I'll alert our expert @numberZero

**Comment by numberZero** [comment]
See #6989

**Comment by paramat** [comment]
Thanks.
