### ISSUE TITLE
Client crash when wielding a meshnode with >6 tiles

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2681]
Title says it all...

```
minetest: /build/buildd/minetest-201505080416/src/wieldmesh.cpp :361 : void WieldMeshSceneNode::setItem(const ItemStack&, IGameDef*):  assertion « i < 6 » has failed.
Abandon (core dumped)
```

Sure, using >6 tiles is not allowed but it ought returns an indicated error instead of a brutal crash.

**Comment by rubenwardy** [comment]
Did you define this in the lua code? It should validate that.

**Comment by kilbith** [comment]
Yes, defined in the Lua code. However, 6 tiles is the hard limit in the engine.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/f1ccfd3c3d7d626087f70b8c5798110cd28b248a
