### ISSUE TITLE
minetest.find_nodes_with_meta reports nodes outside its area

### ISSUE THREAD

**Issue by Sokomine** [minetest/minetest#2682]
When minetest.find_nodes_with_meta( pos1, pos2 ) is called, it does report nodes with metadata which do not lie in the area defined by (and including) pos1 and pos2. Its area streches at least one more in each direction.

**Comment by paramat** [comment]
Looks like it searches all 16^3 mapblocks that the specified volume enters into, this probably makes it fast, solution is to specify a volume aligned with mapblock edges.

**Comment by rubenwardy** [comment]
It is a bug, as it does not do what you expect. You should at least put a note that says that it does it in terms of mapblocks.

**Comment by paramat** [comment]
Yes, docs need updating.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/ff740a417946abb003426734645f823458eee9f3
