### ISSUE TITLE
No OpenGL/DirectX rendering on Windows network game

### ISSUE THREAD

**Issue by technomancy** [minetest/minetest#2684]
I'm running the latest release (0.4.12) on Windows 7, and it works fine when playing singleplayer (any rendering engine) or when playing a network game with software rendering.

However, when playing a network game with OpenGL or DirectX connecting to a Linux server using the latest from git (2b44e7544267e26e) I get no rendering of nodes. It's just a grey screen, though it does render the hand. I have to switch to software rendering to play.

Let me know if there's any more relevant details I could include.

**Comment by PilzAdam** [comment]
Are you sure that this is caused by the rendering and not the just network lag (i.e. it takes a long time for mapblocks to be send to you)?

**Comment by technomancy** [comment]
The network game was on a LAN, and the screen stayed grey as long as I stayed in the game; at least 15 seconds. I suppose it's theoretically possible, but when I started playing with software rendering the latency was imperceptible. If you can suggest a way to measure network lag I could confirm this, but it seems really unlikely.

**Comment by est31** [comment]
Can you repeat it some times, to ensure behaviour is reproducable? Also, a screenshot would be great. Just drag&drop it into the comment edit field.

**Comment by SmallJoker** [comment]
leave the serer then join again, I know this problem from my server.

**Comment by technomancy** [comment]
Here's a screenshot.

Interestingly enough, you can see clouds, but the server is hosting a subgame that has clouds turned off. It is definitely 100% reproducible so far; I have tried it 12 or so times. Leaving and rejoining makes no difference.

![blank-minetest](https://cloud.githubusercontent.com/assets/141/7559905/8df4fd28-f7e7-11e4-842d-91daff2be424.png)

**Comment by est31** [comment]
Can you try the following combinations with OpenGL or DirectX:
1. Linux 0.4.12 server over network, 0.4.12 client
2. Linux git server over network, git client

**Comment by sfan5** [comment]
> Interestingly enough, you can see clouds, but the server is hosting a subgame that has clouds turned off. 

Clouds are controlled by the client, setting enable_clouds in the server settings has no effect.

**Comment by rubenwardy** [comment]
This happened to me, it turned out that the server was locked up and not responding to the client.

#2383

**Comment by LlelanD** [comment]
On a fresh install, the first login to a singleplayer or online game works fine. Any login after that gives me an empty gray world with no nodes spawned at (0, -0.5, 0). There are no error messages in the console.

I'm on an Asus K55A laptop running Windows x64 8.1 and minetest 0.4.12 x64.

![minetest_empty_world](https://cloud.githubusercontent.com/assets/766883/7646078/112ebba6-fa73-11e4-8d62-8456ed82d263.png)

**Comment by 4aiman** [comment]
I can't reproduce this with *any* server.
And I always connect to a Linux server. Win7/8 + Debian Sid/Testing/Unstable server = just fine.
That is inside LAN.
Inside the WAN I've connected to Xanadu, Carbone, Land Rush and several others servers - all those are just fine too.

What server do you use, @technomancy ?

**Comment by technomancy** [comment]
@est31 Linux to Linux doesn't exhibit this problem on any of my machines, whether it's a git build or the 0.4.12 release.

@4aiman The servers I've tried are 0.4.12 and d59e6ad004 from git, both on Debian. Perhaps the difference could be related to running the Windows client on a Vista machine?

**Comment by 4aiman** [comment]
@technomancy 
So... the server you've mentioned is not public but was created by you?
I haven't got a Vista machine ATM. 
But I don't use Intel IGA either.Mine's ATI HD 5xxx (IGA) and ATI 85XX HD (Discrete).
WIn8, x64 (single language), 6Gb of RAM and 2.4GHz*4 AMD CPU.

I still think that either IGA or its drivers are to blame (chipset drivers may affect Intel IGA too).

Lets run a test:
Say, what about x86 build? Does that fail to render OpenGL/DIrectX too?

**Comment by technomancy** [comment]
I've upgraded the server to git master, and now I only get this on OpenGL; software rendering and DirectX work fine. I can try a 32-bit build later.

**Comment by Fixer-007** [comment]
Any news on this bug?

**Comment by sofar** [comment]
0.4.12 is ancient. If this can be reproduced with 0.4.15, great, we'll leave this bug open.

**Comment by sofar** [comment]
No feedback for over 2 years.
