### ISSUE TITLE
Writing outside the VoxelManip boundaries modifies weird locations on the map.

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#2685]
Summary:
on_generated provides a 112x112x112 region that can be written to.
If you call voxel manip on this 112x112x112 region and then attempt to assign data to a location outside that region, it will modified parts of the map in weird locations.

Details:
Sorry, for no testcase or details.  It's quite possible this is already a known issue.  Here is an example of where I've noticed it:
1. Use a mapgen like paramat's watershed
2. Explore a location with very tall trees (the jungle biome on watershed has tall trees).
3. In some areas the tops of the trees get cut off because they go beyond the edge of the 112x112x112 chunck boundary, but what happens next is even weirder...
4. The part of the tree that was cutoff shows up in weird locations on the map... usually underground below the chunck... in a totally different chunck.

I realize an easy solution is to do checks inside LUA to make sure you never assign data to a location outside the chunck boundaries... and I'm fine with that.
But, I figured it good to just report this bug anyways, in case it's something that would want to be fixed one day.

**Comment by paramat** [comment]
Might be a bug with watershed, as far as i can remember i wasn't careful about limiting the height of jungletrees, if they extend more than 16 nodes above a mapchunk it's possible that due to how voxelmanip indexes work that the chopped part appears 112 nodes below. I'll check.

**Comment by paramat** [comment]
I think the relevant index code is here https://github.com/minetest/minetest/blob/master/src/voxel.h#L275
This needs to be simple and fast so it's probably best to not add checks for co-ordinates outside the voxelarea.

**Comment by est31** [comment]
I disagree, we shouldn't trust modders' code, which is the sole reason of #1606.

**Comment by bugreport0** [comment]
This might help, if it were possible to do fast and easy:
* Make index return an index that does not write any data to a chunck if it's out of bounds ... instead of returning an index to a wrong location.

I don't know what else would be required to fix this bug, but that *might* help some.

**Comment by paramat** [comment]
It's easy to add a check, but the function is used 6400 times per mapchunk during core and lua mapgen, so slowing it down may not be justified. There are endless ways modders' careless code can cause unexpected results, we can't add safety checks for all of them, this is fairly harmless anyway.

**Comment by bugreport0** [comment]
index has to do various calculations to turn a coordinate into an index, would this be possible to do without any extraneous checks that would slow it down?

Consider something like this:
> Assume that voxel manip creates a table with 38416 entries (indexes: 1-38417)
> Add an addititional entry to that table (index 38418)
> Anytime you use the index function in lua to turn a coordinate into a table index, if the coordinate is out of bounds, it returns the index to the extra entry: index 38418
> When you write the data to the map at the end (when you are all done), voxel manip knows to just ignore index 38418 and not write that data anywhere.

So basically index would return a useless location in the table... you can then write data to that index in lua... but the data never actually gets used/saved.

**Comment by Zeno-** [comment]
I kind of have to agree that it's, really, up to the calling function to ensure that the data passes to the function it calls is correct (especially in this case). Let's call it a precondition. The danger I see, though, is that there is no out-of-bounds checking *when calculating the index*, however just calculating an index doesn't (and shouldn't) included bounds checking. The calling function should check either that the coordinates it sends are within bounds, OR that the returned index is within bounds. Perhaps the best solution is to create a new Lua function called isIndexInBounds(index) (or whatever) and properly written mods can either satisfy the preconditions at the start of the loop (loop invariant) so it knows that the returned index will always be in bounds, or it can call the bounds checking function every iteration.

**Comment by paramat** [comment]
> it's, really, up to the calling function to ensure that the data passes to the function it calls is correct

Yes. I couldn't find an API for area:index() so am assuming this is the one piece of code that is used by lua and c++. Because core code is more carefully programmed than mods, it would be wrong to slow down this code, and core mapgen, with safety checks it doesn't need. Therefore this pushes responsibility back to mods.

**Comment by paramat** [comment]
> a new Lua function called isIndexInBounds(index)

There is a c++ function that checks if a position is within a given voxelarea, 'area:contains(p)' or something, we could possibly add an API to access that from mods, then mods that need to use that can, at the cost of lower performance. Something to discuss with hmmmm when he returns.

**Comment by 4aiman** [comment]
Thank you, people!
Now I know what to do with my villages :)
:+100:

**Comment by paramat** [comment]
There are so many ways to cause errors through bad mod code, this is just another and not an issue.

**Comment by est31** [comment]
This bug is especially bad as this means rogue memory access, and could possibly be a security hole in our sandbox.

**Comment by est31** [comment]
Note: I am not proposing to do boundary checks on each access per default here. This is bad for speed, especially as this is performance related code. But it stays an issue that needs to be fixed somehow.

**Comment by est31** [comment]
I'm not really sure, which code can be used to do out of boundary writes to the map?

I've looked at `set_node_at`, it makes boundary checks, and `set_data` doesn't do anything outside of bounds as well.

All the other API functions seem to implement boundary checking as well.

So I'd say unless somebody can tell me where exactly one can write outside of bounds I'd say that this bug is either invalid or fixed (without this issue being closed). Closing therefore.

**Comment by paramat** [comment]
> This bug is especially bad as this means rogue memory access, and could possibly be a security hole in our sandbox.

@est31 The lua voxelmanip creates a lua flat array table accessed by an index, could an index < 0 or > array size cause such serious problems?

The issue is about area:index not doing a boundary check for the voxelmanip, and returning an index that is a weird location inside the voxelmanip. It still happens if getting the index for a point outside the lua voxelmanip.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3139
I should have checked earlier, we already have voxelarea methods 'contains()' that takes, xyz, vector or index. Such seperate check functions are the ideal solution to this issue.
