### ISSUE TITLE
Android: Jumping negates fast_move

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2686]
With fast_move enabled, you can run and swim normally, but when you jump, your speed is reduced to that of walking.

**Comment by Zeno-** [comment]
At the time I wrote the "auto fast" patch that was intended behaviour:

```
	/* For Android, invert the meaning of holding down the fast button (i.e.
	 * holding down the fast button -- if there is one -- means walk), unless
	 * performing an action, sneaking or jumping.
	 */
	const u32 autofast_exludebits =
			  (1U << 4) | (1U << 6)     // jump, sneak
			| (1U << 7) | (1U << 8);    // left state, right state
```

If jump should not disable the "autofast" then I am of course willing to change this based upon user feedback.

**Comment by Wayward1** [comment]
Ah, ok. I wasn't aware this was intended. It does make certain actions difficult though, like jumping across a valley, or trying to "skip" (fast_move + jump) across water.

**Comment by Wayward1** [comment]
I've been testing a patch from Zeno- over the past few days which removes those exclusions, and it works fine :)

**Comment by Zeno-** [comment]
Ok, I'll merge shortly. Thanks Wayward1

**Comment by Wayward1** [comment]
No problem

**Comment by Zeno-** [comment]
99cf53c
