### ISSUE TITLE
Node highlighting makes particles inside mesh nodes (plants) hidden

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#2687]
I've been adding particles to plant nodes (mesh visuals) and whenever I add particles inside the nodebox for a plant, I can only see the particles if either

- node highlighting is turned off
- I'm not highlighting the node with the particles

There's other weird visual artifacts as well with node highlighting, such as water surfaces visible through a highlighted mesh node disappearing, and other things as well.

**Comment by sofar** [comment]
example visual: http://i.imgur.com/kNgzIlE.png

Note the node highlight box chops off almost the entire top of the 2-high corn mesh

**Comment by paramat** [comment]
@sofar Should be fixed now, can anyone test?

**Comment by sofar** [comment]
Particles are visible inside the holo node highlight with 7ea40e45b1bf893aa693c179cbe8612ede86faee

I also don't see the mesh node issues with corn I saw before.

I do find the new halo really dark, though.
