### ISSUE TITLE
Strange behavior of inventory function "remove_item" with stack sizes over 99

### ISSUE THREAD

**Issue by Miner59** [minetest/minetest#2689]
Hi,
I noticed a problem with using inv:remove_item() in a mod.
When you want to remove a stack size bigger than 99 then it only works sometimes correctly.
It depends on the amount of items in inventory, but sometimes more items as specified are removed.
Although if you check the returned stack size with :get_count(), it doesn't match the really removed items.

As it is hard to describe, I added a lua code for a mod which can show the strange behaviour.
It adds 200 cobblestones to your inventory and removes 150 cobble again.
But amount of cobble isn't growing all the time, it stays at almost same amount everytime.

``` lua
local lasttime=0
local countold=0

minetest.register_globalstep(function(dtime)
    local now = math.floor(minetest.env:get_timeofday() * 500)
    if now~=lasttime then
        lasttime=now
        local players  = minetest.get_connected_players()
        for _,player in ipairs(players) do
            local inv=player:get_inventory()
                if inv~=nil then
                    local added=200-(inv:add_item("main",ItemStack("default:cobble 200"))):get_count()
                    local removed=(inv:remove_item("main",ItemStack("default:cobble 150"))):get_count()
                    minetest.chat_send_all("added:get_count"..tostring(added).."/removed:get_count"..tostring(removed))
                end
                local count=0
                for i=0,inv:get_size("main"),1 do
                    local stk=inv:get_stack("main", i)
                    if stk:get_name()=="default:cobble" then
                        count=count+stk:get_count()
                    end
                end
                local diff=count-countold
                minetest.chat_send_all("count before:"..tostring(countold).."/count after"..tostring(count).." +-(should be 50):"..tostring(diff))
                countold=count
                break
            end
        end
    end)
```

**Comment by paramat** [comment]
Maybe because we only support stacks up to 99?

**Comment by raymoo** [comment]
A quick grep didn't find anything using 99 specially, other than as  a default.

**Comment by t4im** [comment]
Have you overridden the `stack_max` property in the cobble definition first?
A lot of code uses `get_stack_max` to check before operating on stacks and might limit to it.

**Comment by paramat** [comment]
@Miner59 see previous comment.

**Comment by paramat** [comment]
No response from @Miner59 
Can reopen if needed.
