### ISSUE TITLE
positions of particle_spawner output not entirely accurate

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#2690]
Picture says it all:

![image](https://cloud.githubusercontent.com/assets/1733537/7557278/572fd99c-f75c-11e4-987f-c48baa021fac.png)

There's only one particle spawner in this picture.  If I turn off that one, all three of these streams will disappear.  And, those extraneous particles respond to/collide with stuff that's placed in their way.

Engine is at commit 5a1975a4e38caa1385cfefac299ce17018172714

**Comment by est31** [comment]
Works for me:
![screenshot_20150511_164840](https://cloud.githubusercontent.com/assets/8872119/7567511/af30aee0-f7fd-11e4-8170-9500e8a6e415.png)

**Comment by kilbith** [comment]
@est31 Try with a sink instead...
![screenshot_20150511_170952](https://cloud.githubusercontent.com/assets/7883281/7568021/bb851d86-f800-11e4-9dab-79dcb2f6b841.png)

Or a faucet...
![screenshot_20150511_171215](https://cloud.githubusercontent.com/assets/7883281/7568073/f2802ce0-f800-11e4-838c-659fba4ca6ae.png)

**Comment by est31** [comment]
My guess this is a glitch in collision detection.

**Comment by est31** [comment]
Clearly there is a physics issue:
![screenshot_20150511_173633](https://cloud.githubusercontent.com/assets/8872119/7568678/4f457f5e-f804-11e4-8335-dc0e6b10985f.png)
I wonder however whether the original Image @VanessaE shared can be explained by that too.

**Comment by obneq** [comment]
Problem seems to go away if you disable handling of negative nearest_dtime in collision.cpp, line 446.
so something is off with the checks done for bool step_up in the same file, line 431
