### ISSUE TITLE
Show default text-based header in main menu when header.png is not present

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2698]
This is a simlple suggestion for subgames. Currently, if the `header.png` is not present, the subgame has no header at all in the main menu.
You could still read the subgame's name on the top left part of the window, but this is a bit small.

I suggest that Minetest automatically uses the default font to “write” the subgame's name (as defined in `game.conf`) as header. The font size should dynamically change based on the window size and the position of other main menu elements, similar to what happens to the header image.

I.e. if the subgame is called “Whatever Game XYZ”, Minetest simply writes “Whatever Game XYZ” as header when `header.png` is not present.

**Comment by C1ffisme** [comment]
I agree.

**Comment by 4aiman** [comment]
And what if the game don't want use a header where the engine puts it? 
Don't force ppl to add a transparent ```header.png``` just because it's place suits you well.

Personally I don't use the ```header.png``` because I've my game's name written in the background.
If this will be added my design will be ruined with extra-layer of text.

![Magichet game](https://lh4.ggpht.com/w8XXowuPRJJJYtUIXpzN7TnfknT6WxgCxTjJiZFVdY0GwghFPr7Ul0-Rm5PUG950NIA=h310)

**Comment by Wuzzy2** [comment]
Then add a `game.conf` setting. Something like `auto_header = false`. If this is false, no automatic header is shown, if it is true, the automatic header is shown. Default should be `true` IMO for those lazy people. :-)

But: A transparent `header.png` won't be a huge problem anyways, you could just use 1 pixel, so minimal overhead. But it still would be a kinda ugly workaround, I know.

**Comment by 4aiman** [comment]
I'm more than "Okay" with the game.conf setting.
I'd rather move there all other settings from the minetest.conf too :)

**Comment by paramat** [comment]
If a header is missing this is a subgame error, and there seems to be a use for having nothing showing if desired. Not worth another setting.
