### ISSUE TITLE
[Feature Request] Add command to display the current time.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#2700]
Hi, I'd like to suggest that we had a command ti display the current server time.

/time alone could display time and /time 00000 could be used to set the time.

Or
We could have /gettime and /settime.

**Comment by tenplus1** [comment]
+1 for /time simply showing time  when no value present

**Comment by est31** [comment]
:+1: Also, the current number format of /time is ugly. Best to convert it into hh:mm:ss format.

**Comment by Dartmouth44** [comment]
Maybe just hh:mm for easier usage?

**Comment by C1ffisme** [comment]
Yes. Please. Make time work better.

**Comment by LeMagnesium** [comment]
> Maybe just hh:mm for easier usage?

One day has 1440 minutes, so 86400 seconds.
hh:mm sounds reasonable, you don't need something specific about a second. 1 minute is about 16 minetest time units, while 1 second is 0.2 unit. I will work on it and maybe do a PR about this. (I won't change the inner working of time, just the way we receive and transmit the information to the command)

**Comment by est31** [comment]
d647eaa67adcde40f4ad9cbd819d08645420f99d
