### ISSUE TITLE
Node Drop Errors

### ISSUE THREAD

**Issue by DevynCJohnson** [minetest/minetest#2710]
Minetest crashes sometimes when nodes are mined. Originally, I thought it was a bug in PilzAdam's Item-Drop mod (https://github.com/PilzAdam/item_drop). However, with or without his mod, I get an ipairs error in item.lua. Typically, the error can be triggered by digging into a default:dirt_with_grass node that has a plant on top of it (such as the typical grass that may drop wheat seed). The error can also be triggered when walking through a snow biome. The error rarely occurs in the Nether or underground. Often times (with or without an item-drop mod), mobs do not drop items when killed (including PilzAdam's sand monster or sheep). The error is not triggered as easily when I use the Item drop made by Nerzhul (https://github.com/nerzhul/minetest_item_drop) or Crabman77 (https://github.com/crabman77/item_drop).

End of log during crash - 
11:34:59: ACTION[ServerThread]: singleplayer digs default:dirt_with_grass at (-254,7,59)
11:34:59: ERROR[main]: ServerError: /usr/share/minetest/builtin/game/item.lua:180: bad argument #1 to 'ipairs' (table expected, got string)
11:34:59: ERROR[main]: stack traceback:
11:34:59: ERROR[main]: 	[C]: in function 'ipairs'
11:34:59: ERROR[main]: 	/usr/share/minetest/builtin/game/item.lua:180: in function 'get_node_drops'
11:34:59: ERROR[main]: 	/usr/share/minetest/builtin/game/item.lua:445: in function </usr/share/minetest/builtin/game/item.lua:423>
compassgps writing settings
11:34:59: ACTION[ServerThread]: singleplayer leaves game. List of players: 
11:34:59: ACTION[main]: [playereffects] Server shuts down. Rescuing data into playereffects.mt
11:34:59: ACTION[main]: [playereffects] Wrote playereffects data into /home/collier/.minetest/worlds/Beta/playereffects.mt.

Mods -

3d_armor
adv_spawning
animalmaterials
areas
beds
boats
bones
boost_cart
bridges
bucket
carpet3d
carts
charcoal
coloredwood
colormachine
compass
compassblock
compassgps
cottages
crafter
craft_guide
creative
default
digilines
doors
dye
farming
farming_plus
fire
fireworks
flowers
food
food_sweet
growing_cactus
hbhunger
heal_potions
homedecor
hudbars
ilights
initial_stuff
intllib
item_drop
locked_sign
mesecons
mobf
mobs
money
moreblocks
more_fire
moreores
moretechnictools
moretrees
myroofs
nether
not_so_simple_mobs
npcf
nuke
pipeworks
pizza
plantlife
playereffects
pmobs
pyramids
screwdriver
sea
sethome
smelter
snow
stairs
streets
technic
throwing
tnt
travelnet
unifiedbricks
unifieddyes
unified_inventory
u_skins
vessels
villages
walking_light
windmill
wool
WorldEdit
xpanes

**Comment by est31** [comment]
We don't fix bugs with minetest mods, thats the mod creator's responsibility. This issue seems very much like that.
To help you track down the issue, can you add the green code inside  builtin/game/item.lua near line 180:

```diff
+			if type(item.items) == "string" then 
+					core.log("error", nodename .. " has string items drop type for item" .. dump(item))
+			end
			for _, add_item in ipairs(item.items) do
				got_items[#got_items+1] = add_item
			end
```

If you get that error next time, it should print which node has caused the issue. Then contact the author of the mod that caused this error.

**Comment by nerzhul** [comment]
This issue is not related to minetest core, closing it. Contact PilzAdam and use issue on the mods' github instead of us :).
