### ISSUE TITLE
[Feature request] Too much player movement control while jumping

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#2711]
In realistic physics, if you jump up in the air, while airborn you can't do anything to change your velocity. The same applies if you jump off a cliff - your horizontal speed vector remains largely the same (sans air resistance) until you hit the ground.

In minetest, you can however jump straight up, *then* push the forward key, and land significantly forward from where you jumped straight up.

I'd argue that, while airborn, the player should not be able to change it's velocity.

Yes, this will make gameplay a bit more difficult. I don't think Minetest movement behavior should be like super mario ;^)

**Comment by PilzAdam** [comment]
Movement shouldn't be a challenge. Keeping the controls as simple as they currently are is the least annoying way of implement moving.

**Comment by C1ffisme** [comment]
Yeah, I agree with @PilzAdam . Can you imagine jumping up non-stair stairways? Oh, the pain... You'd either never get up or spend hours getting up what right now would take minutes or even seconds. No. This cannot be added. It's as bad as removing map compatability. We might as well remove bronze and leave people with hundreds of unknown items.

**Comment by est31** [comment]
I agree with @PilzAdam, too. Its basically a replacement for human's ability to direct their jump. Additionally, your skin may have two legs, but in minetest physics you are one-legged.

**Comment by paramat** [comment]
I remember that Celeron55 will not accept this realistic change, and i agree with him.

**Comment by kilbith** [comment]
@paramat Where's the quote ? I often see you invoking the so-called opinions of c55 to strengthen your statements...

**Comment by Zeno-** [comment]
8 hours for a discussion is not long enough. Re-opened.

**Comment by sofar** [comment]
ahaha! Thanks Zeno-

TBH I'm not asking to take away all in-air player control, but I did notice that I had exactly the *same* control horizontally in-air as walking around. (can someone confirm?)

An improvement, and a middle-of-the-road solution would be to reduce, but not eliminate, the airborn movement control.

Control and speed while swimming is already less than normal walking speed. Just reducing the maximum horizontal speed one can obtain *after* jumping may be a good way to implement this.

if (airborn) then
    if velocity + velocity_adjustment_from_keyboard < max_airborn_velocity then
         veolocity = velocity + velocity_adjustment_from_keyboard
    end
else if swimming then
    if velocity + velocity_adjustment_from_keyboard < max_swimming_velocity then
...

you get the idea.

**Comment by paramat** [comment]
kilbith, it was a few months ago on IRC, it would take a long time to find the quote, this issue gets raised occasionally, celeron55 considered no airborn control to be very undesirable (from reading 3 years of dev logs we do seem to have similar opinions on most issues).
It would be a frustrating change for players. I feel the extra complexity of a change or compromise is not justified, as all we gain is frustration, and some realism (which is in no way a purpose of Minetest according to celeron55).

**Comment by sofar** [comment]
paramat, it seems that having this thread documented is a better way than keeping personal IRC logs, so instead of making the discussion less productive, perhaps you can produce the IRC logs you kepts so others can read the discussion that was held, and we can either close the discussion or consider any missed angles.

Also, people change their minds. It's never bad to revisit old decisions to see if they still were valid. That's a strength, not a weakness, and will get you very far in any form of engineering.

**Comment by est31** [comment]
There are public irc logs at http://irc.minetest.ru

**Comment by kilbith** [comment]
@paramat No offense but mentioning celeron55 so frequently is not insignificant and as sofar said, you have to provide a source since it's leading us to definitive settling.

**Comment by 4aiman** [comment]
Please, NO realistic jumping!

(BTW, Super Mario physics might work rather well since those are in-between, but nah... don't want those too ;)

**Comment by Megaf** [comment]
Please, keep the physics as they are, Minetest is not a reality simulation, is a free game where you are free. All we don't want are limitations.

**Comment by sofar** [comment]
@4aiman: I think we're in agreement that we don't want to take away all movement control. But have you thought about limited control? Please add to the discussion instead of re-stating something that is already agreed on.

**Comment by sofar** [comment]
Since others haven't attempted to find the relevant thread, I dug around and found this section:

    http://irc.minetest.ru/minetest-dev/2013-02-15#i_2874201

The way I read it, celeron55 says "this no air acceleration sucks" (which it does) and Pilzadam states that a (30%) reduced air accel is playable. At the end celeron55 says he'd support other values if enough support ("i'm changing all three accelerations back to 4 until somebody is able to show me something that is actually better (or make a vote for such with a majority agreeing)")

Also, since people don't believe that people would actually like more realistic physics, here's some proof that I'm not the only one: The Carbone subgame explicitly reduces air accelleration:

    https://forum.minetest.net/viewtopic.php?t=9033

FYI, I didn't realize that the values could be changed per server, and trivially, so this may just be closed with documentation showing people what settings are relevant.

**Comment by 4aiman** [comment]
@sofar 
Please, stop telling me what to do. 
I *am* adding. 
Only several ppl are "in agreement". 
Should a dozen of those who would be *for* the change appear - my "voice" will obtain it's meaning.
Especially since you've found some info @ irc.minetest.ru.

**Comment by Calinou** [comment]
> The Carbone subgame explicitly reduces air accelleration:

Yeah, but the values are still reasonable.

```Conf
# Decreased acceleration compared to minetest_game.
movement_acceleration_default = 2.4
movement_acceleration_air = 1.2
```

**Comment by sofar** [comment]
@4aiman I'm sure there's a misunderstanding here.

"Realistic physics" mean "0 air acceleration". A non-zero air acceleration is not "realistic physics" by any means, unless you grow wings on your minetest character.

You said "Please, NO realistic jumping" which I interpreted as "Please, no realistic (physics for) jumping"

I previously said, quote: "I'm not asking to take away all in-air player control" which, obviously can be read as "I'm not asking for realistic physics".

So, we are in agreement. We both don't want realistic physics. Just like everyone else in this thread I think agrees that zero air acceleration is unacceptable, and this discussion is no longer about that.

The IRC thread is undecided at best. Even paramat tried reduced air acceleration and posts that it feels OK (paraphrasing). I'll have to try myself as well and gladly will post my findings, but it would help if more people could try playing with various settings for "movement_acceleration_air" in minetest.conf.

@Megaf minetest is full of limitations already, I see plenty of people writing mods to work around some of those limitations, and that's a good thing? 

@calinou again, yes, I'm not asking movement_acceleration_air to be set to 0.

**Comment by paramat** [comment]
> I didn't realize that the values could be changed per server, and trivially

Ah excellent i had forgotten they are settable in .conf. The IRC log discussion (thanks for searching) resulted in the current value of 2 suggested by PilzAdam as a compromise between celeron55's 4 and Taoki's 0, i feel it would be best then to leave it at 2 because most players are used to it being that way for the last 2 years, parkour maps would be tuned for this, and it is easily changeable in .conf.

**Comment by HybridDog** [comment]
l assume if you set ```movement_acceleration_air``` to e.g. ```0.01``` you can climb nodes and you aren't able to do noticeable acceleration in air without flying.

**Comment by 0-afflatus** [comment]
In theory I would support reducing in-air movement but 

> parkour maps would be tuned for this

Breaking parkour areas would be very bad indeed.
Anyway I'm glad to see it's a non-issue as it's easily changeable in .conf
