### ISSUE TITLE
Invulnerability for players (aka “god mode”)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2719]
It would be nice if players could be made invulnerable and immortal via the Lua API.

Something like what `enable_damage = false` does for all players globally, but on a per-player basis. If a player is in invulnerability mode, this means:
- No fall damage
- No damage from punches
- No damage from `damage_per_second` nodes
- No `<insert other event which may hurt/kill the player here>`
- `set_hp` is a no-op

Note: This does not do what you would expect:

```
player:set_armor_group({immortal=1})
```

It seems the `immortal` group has no effect on players.

EDIT: `immortal` now partially works (see below).

**Comment by est31** [comment]
Punches can be oppressed on a per-player basis since c5b4e541749c50805519ce040d98a0a8e5e0ec03

**Comment by Wuzzy2** [comment]
Good to know, but AFAIK this does not prevent any other damage sources.

**Comment by est31** [comment]
No

**Comment by C1ffisme** [comment]
What we NEED is per-player gamemode. Currently only one global gamemode exists, and if someone has to fix an accidental TNT blast, everyone has to get off the server, wait until the explosion is fixed in creative mode, and then come back on. REALLY bad for things like PVP.

**Comment by SmallJoker** [comment]
Why not a new builtin privilege: `immortal`?

**Comment by Calinou** [comment]
> Why not a new builtin privilege: immortal?

This makes sense but has two downsides:

* Other players can know when you are immortal,
* If only this (and not `immortal` group support) is implemented, then it is not possible to make them immortal without a message appearing in their chat.

**Comment by TeTpaAka** [comment]
This could be implemented if someone coded #2631 in a way register_on_punchplayer was made. This way, every hp change could be disabled for a specific player.
I would do this, but I don't think, the engine has enough support for this feature, yet. My main concern is, that there is practically no distinction between the different types of hp changes. The only differentiation possible is in client side hp changes (fall damage, drowning, node damage...), server side damage (punching) and lua hp changes (Well, these can be differentiated easily by adding an argument to set_hp).
It would be better if you would know, what caused the HP change, so you could disable e. g. only fall damage. But as long as so much of the damage is calculated client side, it is not doable the way I want it.
However, if this feature is really wanted, I can code it.

**Comment by TeTpaAka** [comment]
Now this can be done by registering an on_player_hpchange callback that returns 0, true for certain players.

**Comment by wilkgr76** [comment]
:+1:

**Comment by Wuzzy2** [comment]
After a recent test in 0.4.14, I noticed that you can now set the armor groups of players, including `immortal = 1`.

If you set `immortal = 1`, this disables damage from attacks but not damage from falling.
So I guess setting `immortal = 1` almost is like a god mode as I requested.

If `immortal =1` would reliably disable *all* forms of damage, I would consider this to be a “god mode” and I am willing to close this issue.

**Comment by sfan5** [comment]
@Wuzzy2 to me that sounds like the client is not getting that damage should be disabled, probably easy to fix.

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by Wuzzy2** [comment]
How is player immortability a “possible close”? Entities can be immortal but players can't. Seems pretty inconsistent to me.

Obvious use case for this would be an immortability potion. ;-)

**Comment by sfan5** [comment]
possible close = there is not enough (apparent) user interest/developer interest to get this fixed anytime soon

**Comment by paramat** [comment]
@SmallJoker maybe you would be interested in coding this sometime?
