### ISSUE TITLE
Water Bug

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2723]
I think this has something to do with transparency...
![screenshot_20150526_173418](https://cloud.githubusercontent.com/assets/10261530/7824076/31766864-03ce-11e5-8611-70279cfdd772.png)
![screenshot_20150526_173422](https://cloud.githubusercontent.com/assets/10261530/7824077/3184a29e-03ce-11e5-9702-c6c347209cdf.png)

**Comment by Wayward1** [comment]
Duplicate of #1404

**Comment by nanepiwo** [comment]
OK, closing.
