### ISSUE TITLE
Android - Black Screen

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2724]
While a world is loading, switching off the display until the lockscreen shows and then unlocking the phone will lead to a black screen instead of the loading bar. When the next stage of loading is reached, the regular animation is shown. Tested on official version on Google Play and one of Wayward_One's recent builds.

**Comment by MoNTE48** [comment]
Confirm

**Comment by Wayward1** [comment]
I can confirm as well

**Comment by est31** [comment]
dupe of #2409, minetest isn't rendered while loading, inside certain "loading steps"

**Comment by MoNTE48** [comment]
Fix https://github.com/minetest/minetest/pull/2999
