### ISSUE TITLE
OSX - Formspec buttons offset

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2725]
When pressing any button (or selecting a field/text box) on a formspec, I always have to move my mouse slightly upwards. This does not happen in game for punching, digging, etc.

Minetest 0.4.12, OSX 0.9

**Comment by nanepiwo** [comment]
This seems to only happen if I do shift + maximize window to increase the window size

**Comment by mdoege** [comment]
Yes, if you resize the MT window while it is running apparently mouse coordinates for formspecs still refer to the old window size somehow. Resizing MT works on Linux, so I'm not sure what the problem on OS X is.

**Comment by neoascetic** [comment]
Duplicate of #1614
