### ISSUE TITLE
Automagick fixing of problems

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2726]
![auto](https://cloud.githubusercontent.com/assets/2122943/7832768/745cd5b0-0459-11e5-8edf-5ed74fdd6afe.png)
- Incorrectly named mods.
- Missing / disabled dependencies (would require MMDB to actually work).
- end of envargs missing.

**Comment by rubenwardy** [comment]
Sort of related to #2324

**Comment by est31** [comment]
Please no "This mod requires security privileges, do you want to give them?" like messages. This just leads to people clicking yes yes accept and not knowing what they actually do.

**Comment by rubenwardy** [comment]
I thought that might be a problem. The point of this is to make it easier for kids / computer noobs, and mod security shouldn't just be a click through.

**Comment by est31** [comment]
Fixing names is ok I guess, as long as some criteria are met, e.g. the new name wouldn't conflict and the new name isnt suprise suprise a trusted mod.

**Comment by asl97** [comment]
Most people never read even if you force them to one way or another.
Making the important text bigger and bright red might help.
Putting a timer too to force people to wait could help but it would annoy most people and most people would switch to doing other stuff till the timeout is finish.
____
This mod requires security privileges
----
do you want to give them?
`No` ---- `Yes (10)`
____
where the - is spaces and the `10` is the time in second that people got to wait before `yes` become clickable

**Comment by est31** [comment]
Thats just horrible UX design.

**Comment by asl97** [comment]
@est31 i know it's horrible, it is the only design that get the highest amount of people to read (the last time i check)

**Comment by est31** [comment]
Escaping the sandbox should be the exception, not the rule. I understand when you need it for servers to interface with IRC or some forum, but I can't think of usecases for singleplayer.

**Comment by iqualfragile** [comment]
thats not only horrible ui/x design, its also ineffective as fuck. people will just look at the countdown and then click yes, and be annoyed about the lost time.
In my opinion the right way to go about this is not not provide any way to install privileged mods from the gui at all, forcing the user to read the documentation and write the config file themselves.

**Comment by rubenwardy** [comment]
I agree, a count down for this is not good.

**Comment by C1ffisme** [comment]
What about making it similar to the github deletion screen, where you have to type in the name of the repository before you delete it. This not only makes people read the message, but reminds people which mod it is, so you remember what people gave you this mod, etc.

Also, the screen should include adequate warning, something along the lines of:

<h2>Mod requires security privileges

Clicking yes will give the mod access over certain functions like using files.

<h3>WARNING!

Giving this permission could be very dangerous for your system! This mod could easily have malware on it! Do not give security to mods from people you do not trust!

**Comment by est31** [comment]
Still, no. There is really no reason for the common mod to legitimately need the security privs, and the few which need it can be added by normal editing of minetest.conf, or even via the new settings tab.

**Comment by C1ffisme** [comment]
Alright then, add it to the settings tab! A warning should be **required** when giving privs.

**Comment by rubenwardy** [comment]
What about a schematics mod which wants to add a building store to the game? That's not just a server thing for specialised use.

**Comment by est31** [comment]
That problem can be solved by adding lua http networking, and adding a per-mod whitelist of websites to access. That whitelist is either confirmed/set by the user, or reviewed by contributors. There are some problems ofc, what if the dns entry points to 127.0.0.1 or to the router ip, but they can be solved by requiring https. With let's encrypt I hope https is easy to get :). The user should be aware though that the mod connects to the internet.

**Comment by paramat** [comment]
:-1:
