### ISSUE TITLE
Change volume of sound on the fly

### ISSUE THREAD

**Issue by KenneyNL** [minetest/minetest#2728]
It would be great if multiple sounds that are playing (looping) could have their volume changed dynamically. Think of fading ambiance sounds against each other or battle music that fades in and out.

``` lua
minetest.sound_change("testmod_foobar", {
    gain = 1.0,
})
```

**Comment by celeron55** [comment]
Similarly to `minetest.sound_stop(handle)`, this should take a `handle` that is returned by `minetest.sound_play`.

(Review for bounty: OK)

**Comment by Bremaweb** [comment]
https://github.com/minetest/minetest/pull/4304

**Comment by paramat** [comment]
#5340 merged.
