### ISSUE TITLE
Key to toggle fullscreen

### ISSUE THREAD

**Issue by KenneyNL** [minetest/minetest#2732]
Add a key (F11?) to toggle between fullscreen mode.

Previous discussion:
https://forum.minetest.net/viewtopic.php?f=5&t=11033

**Comment by C1ffisme** [comment]
There is one for Ubuntu I believe.

**Comment by Calinou** [comment]
Alt+F11 is a common key binding for fullscreen, we might provide it.

> There is one for Ubuntu I believe.

Windows doesn't provide an easy and convenient way to fullscreen all applications.

**Comment by C1ffisme** [comment]
Ah Windows. Beautiful, breakable Windows.

**Comment by RobertZenz** [comment]
@Calinou Alt+Enter is the keystroke used to bring CMD windows on Windows into fullscreen mode. Today most applications are using F11 for changing between fullscreen and windowed mode.

**Comment by celeron55** [comment]
This is not very easy in Irrlicht; that's why it doesn't exist in the first place. But if someone is up to the task, go ahead.

(Review for bounty: OK)

**Comment by neoascetic** [comment]
#2510 is related a little bit

**Comment by 4aiman** [comment]
First, F11 and alt+ctrl are both commonly used in different software.

Second, I guess, no one really wants true full screen.
A simple border-less window on top of all others would be enough.
Monitor resolution change can be done regardless of the graphics engine.
So...
1. change the resolution
2. disable window borders
3. maximize the application.
Just don't forget to restore the resolution upon exit.

That IS a hack of sorts, but who cares? (@celeron55 ?)

**Comment by Calinou** [comment]
A borderless window will slightly decrease performance, but it's perfectly acceptable today. Even Source games propose using a borderless window.

**Comment by kilbith** [comment]
If you disable the WM, you slightly increase performance at the contrary - but it's barely noticeable.

**Comment by RobertZenz** [comment]
@kilbith If disabling your WM increases performance even "barely noticeable" your machine is either *way too weak* or your WM is insanely broken. What you mean is most likely broken compositors, which manage to absolutely kill performance of any OpenGL application (I think Gnome managed to deliver such a broken compositor).

@4aiman The borderless window is preferable in nearly all instances, yes.

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by paramat** [comment]
Anyone still requesting this? Author and supporter are no longer with us.
Close in 1 month if no support.

**Comment by cweiske** [comment]
> Very little gain (no border)
I have two toolbars, one at the top and one at the bottom of the screen. Getting rid of those would be more than a little gain to me.

Also related: #3982.
