### ISSUE TITLE
[Android] Stimulating holding down use key.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2734]
I can't find the commit which did this, but there was recently an update which made the fast toggle button actually work. However, this makes it as if the use key is continually pressed, *all the time, not only if fast mode is on*. This makes it impossible to properly use a node which executes a different function if interacted with while holding the use key (such as the shops in one of the economy mods). It would be nice if the stimulated holding down the use key was only initiated when fast_move is enabled.

EDIT: This mod, https://github.com/SmallJoker/bitchange , specifically https://github.com/SmallJoker/bitchange/blob/master/shop.lua#L292-L296

EDIT2: I think it's https://github.com/minetest/minetest/pull/2567

**Comment by nanepiwo** [comment]
I would code this if I knew C++, it seems fairly easy to me...

In src/game.cpp:

Currently the code is to always stimulate pressing the use key.

This should be changed to if fast_move is enable, then stimulate pressing the use key....

**Comment by Zeno-** [comment]
addf3ee

**Comment by Wayward1** [comment]
@nanepiwo, try this: https://docs.google.com/uc?export=download&id=0B4ncVDvTlVbISm9CaDFsYVREV28

It's the latest git, with Zeno-'s fix
