### ISSUE TITLE
Add gamma to GUI and Add brightness option

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#2739]
Add an option to increase brightness/gamma.

**Comment by TeTpaAka** [comment]
#    Adjust the gamma encoding for the light tables. Valid values are in the range
 #    1.0 to 3.0 (inclusive); lower numbers are brighter.  This setting is for the
 #    client only and is ignored by the server
 #display_gamma = 1.8

In minetest.conf

**Comment by codeandfix** [comment]
This should be added to the GUI, also 1.0 is not enough. Its still very dark on low-black-point graphic monitors.
Also a brightness option should be added.

**Comment by 4aiman** [comment]
+1
Can be easily done in lua if this is to go to the settings menu.

The trick would be to make minetest to change gamma immediately (e/g w/o restarting the client).

**Comment by Calinou** [comment]
You can edit the shaders to make everything brighter, however this requires to have shaders enabled.

**Comment by 4aiman** [comment]
@Calinou, that's the main reason to not let shader to do that :)
Anything that doesn't use OpenGL would be depraved of the ability to change anything.
That includes: directx, ogles1 & 2 (thus, android RPi and BPi), old VGA adapters, some integrated VGA (usually Intel) adapters.

**Comment by PilzAdam** [comment]
006ef5b4a5e362eed848ca26b411a8059d74b965
