### ISSUE TITLE
No way to press enter in formspec without closing it

### ISSUE THREAD

**Issue by technomancy** [minetest/minetest#2743]
In [this form](https://github.com/technomancy/calandria/blob/master/mods/digipad/init.lua), I'd like to be able to press enter to trigger the `on_receive_fields` callback, but every time I press enter, it closes the form.

According to Zeno on the freenode channel, it should only close when `button_exit` is set, but this appears not to be checked here: https://github.com/minetest/minetest/blob/master/src/guiFormSpecMenu.cpp#L3038

**Comment by Zeno-** [comment]
I've labeled this as a bug (as well as feature request) because I think that, in essence and in my opinion, not having a way to bypass the enter key closing a formspec is undesirable behaviour

**Comment by technomancy** [comment]
For what it's worth, my long-term goal is to be able to implement a terminal in Minetest (a la [computercraft](http://computercraft.info)'s) but since that appears to be currently impossible the current engine, so I'm shooting for the next-best thing, line-oriented teletype interaction.

**Comment by 4aiman** [comment]
I just show another formspec to a player in magichet.
I have to update some fields in the current formspec most of the time anyway.

But image_button work well for me - I sort inventory with it and it doesn't close anything.

**Comment by technomancy** [comment]
@4aiman Could you give me a link to the code where you just show another formspec to make it appear as if enter doesn't close the form? I've tried this in my own code and haven't been able to get it to work.

**Comment by 4aiman** [comment]
@technomancy 
There's no link to a code sample at the moment, but I can assure you that the following works:
1. Create a handler for on_recieve_fields()
2. minetest.show_formspec()
3. inside your handler (from the point 1) you should have something like:
```
if formname == 'bla-bla-bla' then
   if fields.button1 then
      minetest.shof_formspec()
   end
end
```

In case you'll need more info: please, tell me what are you trying to do and if possible show your code that needs "fixing". I'll be able to help you. I won't demand anything from you in turn, so feel at ease about licensing or whatever distribution concerns you may have.

**Comment by technomancy** [comment]
@4aiman Thanks. What I've got is here: https://github.com/technomancy/calandria/commit/84f3651d716dfe910be15a4b6baf4fbfd4f3a6b7

I call `minetest.show_formspec(...)` in `on_receive_fields` regardless of the value of `formname` or `fields`, but it does nothing. If I call the function with no arguments, it crashes the game with a `ServerError`.

**Comment by 4aiman** [comment]
@technomancy 
I've answered in a comment below your code ;)

**Comment by technomancy** [comment]
Just to follow-up back here re: conversations held elsewhere, there are some workarounds for this, but none of them work for keyboard-initiated form callbacks, which is what I need.

Is there anything I could do to help get this fixed inside Minetest itself?

**Comment by tenplus1** [comment]
I wouldn't say this is a bug, more down to how the formspec/mod is written...  Check out how nametags are done in mobs redo, you can hit enter and it works fine; https://github.com/tenplus1/mobs/blob/master/api.lua#L2662

**Comment by ShadowNinja** [comment]
#516

**Comment by paramat** [comment]
#516 was refused btw.

**Comment by Ferk** [comment]
I think the idea was to make a new formspec element for this, instead of changing the behavior of the current one. That's why it was refused.
