### ISSUE TITLE
Playername distance/far on per Player Basis / Priv or API

### ISSUE THREAD

**Issue by codeandfix** [minetest/minetest#2745]
There should be a far priv, so SuperUsers can see far but others cant.

**Comment by C1ffisme** [comment]
To see far, all you need to do is press R or turn up the viewing range with Shift+"+".

About Usernames, I think those should be tweaked so that you can see far away ones with a priv, and close ones without.

**Comment by NathanSalapat** [comment]
I agree, it can be annoying to see names, and walk toward them but never find the player because they are so far away.

**Comment by neoascetic** [comment]
+1

**Comment by neoascetic** [comment]
#75 is pretty old but still related

**Comment by hunter688** [comment]
will be fine add feature if player want hide own nick, controlled by command, privileges, also privilege for show hidden nicks will be useful

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by paramat** [comment]
Actually, don't we now have player tag API? There was an issue closed recently similar to this.

**Comment by Amaz1** [comment]
> Actually, don't we now have player tag API? There was an issue closed recently similar to this.

If you change a nametag, all players (within range) see the changed nametag. There's no way of hiding it/changing it for just one player/players with a certain priv, which is what I think this issue is about. So it is similar, but not quite the same.

**Comment by paramat** [comment]
Any core dev interest?
I'm not keen on a priv and don't see it as important enough to add to player object properties.
:-1:

**Comment by SmallJoker** [comment]
If anyone is interested in implementing it:

https://github.com/minetest/minetest/blob/326eeca306f7bfb53ae3685eef18978dd81e587e/src/server.cpp#L609-L614

`player_radius` can be adjusted locally to extend the sending distance of other players (value 0 means unlimited). Doing it per-player-properties will require a change in the server environment where objects are added and removed from the player's view.
