### ISSUE TITLE
Random rotation of textures

### ISSUE THREAD

**Issue by KenneyNL** [minetest/minetest#2747]
Add an option to node registration that textures (top, side, bottom or all) to be randomly rotated upon placement. This would create a varied terrain, see sample;

![Texture rotation sample](http://i.imgur.com/NTmTTx2.jpg)

**Comment by celeron55** [comment]
I'm going to say it's probably better if #2746 is added, and not this, because the functionality is so similar and this is much more limited, adding unnecessary maintenance burden. Later when #2746 exists we can review if this is still needed.

(Review for bounty: Not now.)

**Comment by paramat** [comment]
:-1: I agree with celeron55.

**Comment by paramat** [comment]
After discussion on IRC http://irc.minetest.ru/minetest-dev/2016-04-10#i_4580709 we decided to close this.
