### ISSUE TITLE
Advanced connected textures

### ISSUE THREAD

**Issue by KenneyNL** [minetest/minetest#2748]
Currently connected textures only use a 1 pixel strip and are bugged. A system like the picture below illustrates would allow for more flexibility:

![Sample](http://puu.sh/e9bHL/f36fdfb006.png)

**Comment by PilzAdam** [comment]
Doesn't it look weird when you place a node and the node next to it changes it's texture?

**Comment by KenneyNL** [comment]
It works in Minecraft, shouldn't look too weird.

**Comment by RHRhino** [comment]
Yes please! :+1:

**Comment by celeron55** [comment]
As long as performance is taken care of, this sounds like a good idea. That being said, this might not be very easy.

(Review for bounty: OK)

**Comment by C1ffisme** [comment]
:+1:

**Comment by 4aiman** [comment]
It works for Minecraft, Terraria and me :)
:+1:

**Comment by RealBadAngel** [comment]
We dont have any "connected textures" feature atm, so how can it be bugged? :)
What we do have is drawtype called glasslike framed which is quite a different thing.

**Comment by PilzAdam** [comment]
@RealBadAngel there is no need for extra vertices and it would work for the current normal drawtype. Just the number of materials needs to be increased.

**Comment by RealBadAngel** [comment]
@PilzAdam, who said anything about extra vertices?

**Comment by PilzAdam** [comment]
@RealBadAngel you:

> much higher number of vertices

**Comment by RHRhino** [comment]
>this drawtype will be definitely slower
Will this drawtype be much slower than the current drawtypes or just as slow as some of the slower ones?

**Comment by 4aiman** [comment]
How about a minecraft-like blending?
- additional colorizing depending on the surrounding nodes
- slow devices can disable that for good
- no new drawtypes
Is that possible?

**Comment by RealBadAngel** [comment]
Taken.

**Comment by KenneyNL** [comment]
Since it isn't mentioned here: There's a $100 bounty on adding this feature.

https://forum.minetest.net/viewtopic.php?f=7&t=12370

**Comment by C1ffisme** [comment]
With all these bounties going around, minetest is going to start going proprietary.

**Comment by indriApollo** [comment]
@C1ffisme what are you talking about ? A lot of open source projects use bounties to motivate developers. They still commit their changes and those are available under the terms of the project licence. So no, bounties won't change that.

**Comment by kilbith** [comment]
Just ignore C1ffisme guys, his comments are incessantly pure noise all around.

**Comment by RealBadAngel** [comment]
@PilzAdam ouch. Number of vertices will remain the same. I will just split each face into 4 triangles not 2 as we have by now.

**Comment by PilzAdam** [comment]
@RealBadAngel there is no need to do that. The full texture for all possible cases is provided by the texture atlas, see the example images in the first post.

**Comment by HybridDog** [comment]
lf you add connected textures l think some nodes, e.g. bookshelves and ores, need less visible sides than nodes having textures with transparency, e.g. glass. So maybe in nodedef.cpp more sides could be forced to be added if use_texture_alpha is true.

**Comment by 4aiman** [comment]
@PilzAdam but enabling the texture atlas proved to lead to swapped textures for some HW configurations...

@everyone Is it possible to "motivate" devs to pull in a code which requires protocol bump right *now* (i.e. w/o waiting till 0.5 or any other event)?

**Comment by PilzAdam** [comment]
@4aiman I wasn't referring to a texture atlas that contains all textures that Minetest used to have. I was referring to the texture of a single node, that contains multiple different versions, as you can see in the first post.

**Comment by RealBadAngel** [comment]
@PilzAdam i wont agree on makin atlases for that feature. Look closer at the image. It will result in making 5 textures for each face. Instead of just 2. We are already suffering because of such gimmicks.
Problem is rather not noticeable with 16px textures, but when it comes to HDX for example, mt starts to eat gigabytes as free chips ;)

**Comment by RealBadAngel** [comment]
![screenshot_20150615_173333](https://cloud.githubusercontent.com/assets/2177790/8163843/cebc3308-1385-11e5-8626-3023a865c388.png)

**Comment by KenneyNL** [comment]
Big thumbs up! Could you have a go with these two textures, interested in how the method works.

http://i.imgur.com/uRFzL7a.png
http://i.imgur.com/NJI4mNZ.png

**Comment by est31** [comment]
I think the method @RealBadAngel does is patching diagonals together, observable by this edge:
![scrensh9](https://cloud.githubusercontent.com/assets/8872119/8164299/62beba74-1388-11e5-8acc-03de9c522379.png)

**Comment by C1ffisme** [comment]
@kilbith Please refrain from trying to disinclude me in what I believe you have called "open source" software. Github is a tool, and tools do not have only one use. Axes can be used for fighting war as  well as chopping wood, and the right size coin can work as a screwdriver. My use of github is not decided by your words alone, and neither can you ban me from Minetest either.

@indriApollo I tend to just spit out strings like a logfile sometimes. Maybe I'll find the time to learn to do otherwise.

**Comment by PilzAdam** [comment]
@RealBadAngel defining the texture in an atlas-like style as seen in the first post has a speed advantage at compile-time and also gives the creator of the texture pack more artistic freedom to define the textures.

Also as @est31 pointed out, your method produces unwanted artifacts.

**Comment by paramat** [comment]
Any more comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by HybridDog** [comment]
l think this is just an approximation for visual behaviour of nodes next to each other. A bookshelf which connects to the sides looks strange if it's very big because there're no wooden walls for stability. Ores connecting to each other may look better than ores which look the same for every position, but then 2x2 connected ore nodes look like they contain more ore than 4 single ore nodes.

**Comment by ensonic** [comment]
Just for reference in minecraft optifine/mcpatcher has different modes:
https://github.com/sp614x/optifine/blob/master/OptiFineDoc/doc/ctm.properties
Here are templates for illustration how many textures are needed:
https://github.com/sp614x/optifine/tree/master/OptiFineDoc/doc/images/

**Comment by paramat** [comment]
No core dev interest stated for years, is there still interest?
