### ISSUE TITLE
Sound will only come through speakers, not headset (Debian)

### ISSUE THREAD

**Issue by Schlesiger** [minetest/minetest#2758]
I am unable to set the sound output to headphones in the pulse audio volume controller.

I am using:
Debian Stretch
pavucontrol 3.0-3

All my other applications are able to output to headphones. Only Minetest isn't working.

**Comment by 4aiman** [comment]
Mine works. Debian Sid/Testing/Unstable (all 3 repos enabled to get SW from) x86.
Do you have more than one sound card?
I've 3 - integrated, USB and integrated in the video card (sound via HDMI) - and can output the sound to any.

**Comment by Schlesiger** [comment]
It's very odd. I am on a laptop and have a similar configuration to you. Every other application will work on any output. Only minetest has an issue. I can select the headphones, but the sound still comes through the speakers.

**Comment by 4aiman** [comment]
@Schlesiger is that true for *any* device?
I'm using the HDMI for 99% of time. 
I'll try to make my earphones to not work with minetest and let you know should I succeed.

Anyway, the openAL calls used by minetest/irrlicht are deprecated:
```
AL lib: (EE) alcOpenDevice: Option 'format' is deprecated, please use 'channels' and 'sample-type'
```
Maybe updating to the next version will fix your sound issue?

**Comment by Elinvention** [comment]
I have another issue where minetest only output to the right channel.

**Comment by paramat** [comment]
@Schlesiger Still happening?

**Comment by Schlesiger** [comment]
Yes. I'm not sure how to debug this, but if you have any instructions I can try them out. Since I opened this ticket I've done two fresh Debian installs for other reasons and the issue persists. I can go into the mixer, see both outputs, but can't select my bluetooth headphones. The same process works for all my other applications. That is why I assume it's Minetest, but I could be wrong.

**Comment by 4aiman** [comment]
@Schlesiger  Set your headphones as a default sink and then run Minetest.
The issue with BT headphones can sometimes be repeated in Terraria, Audacious and other programs.
You also may want to try disabling extra output devices temporarily (i.e. before running Minetest) and re-enabling those later.

**Comment by 0-afflatus** [comment]
Oh bluetooth headphones. I have had no problems with PAVC using wired headphones. I suspect this is more to do with your audio config, or just the general awfulness of pulseaudio than Minetest.

**Comment by nerzhul** [comment]
This problem is not due to minetest but the sound server you use (jack, pulse, alsa...)

**Comment by vilhelmgray** [comment]
Solarus had a similar issue (https://github.com/solarus-games/solarus/issues/912). The reason is that OpenAL Soft doesn't enable PulseAudio device moves by default.

You can override the default behavior and enable moves by creating the following OpenAL Soft configuration file (at `~/.alsoftrc` for local configuration):

```
##
## PulseAudio backend stuff
##
[pulse]

## allow-moves: (global)
#  Allows PulseAudio to move active streams to different devices. Note that the
#  device specifier (seen by applications) will not be updated when this
#  occurs, and neither will the AL device configuration (sample rate, format,
#  etc).
allow-moves = true
```

**Comment by schlesiger** [comment]
Thanks for taking the time to post @vilhelmgray! That worked!

**Comment by wallzero** [comment]
Thanks for taking the time to post @vilhelmgray! That worked!

**Comment by farooqkz** [comment]
> I have the same problem as @wallzero as playing minetest on Kubuntu 21.10. Where should i put the configuration file .alsoftrc as recommended by @vilhelmgray ?

In your home directory. E.g. if your username is `foo` then the home directory will be `/home/foo/`
