### ISSUE TITLE
Shadow bug at y = 63 in mgv5/mgv7/mgflat/mgfractal/mgvalleys(/mgwatershed)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#2759]
![screenshot_20151129_222541](https://cloud.githubusercontent.com/assets/3686677/11490103/580d3a82-97cd-11e5-9d35-d0a7c89aee5c.png)

Note there is light around the decorations. Affects mgv5, mgv7, mgflat, mgfractal, mgvalleys and mapgens in development which are based on mgv7 and have the same lighting code. Sometimes as mapchunks generate parts of the shadows appear and disappear.

These may have started around the time of this lighting change https://github.com/minetest/minetest/commit/7233a1228eb161cbcbb46c6e801cabd89ef3d2ab before which we had lighting bugs at y = 47.

See more details below.

**Comment by nanepiwo** [comment]
I've seen similar lighting glitches (shadows that can't be removed) but not at any specific elevation, with the default mapgen.

**Comment by paramat** [comment]
Yes in 0.4.12 stable mgv6 has shadow glitches but those have been fixed now.

**Comment by paramat** [comment]
This is still a mystery. From testing i have found this occurs when the mapchunk above y = 47 is generated before the mapchunk below. When the lower mapchunk generates the shadows appear at y = 63 which is the top layer of nodes in the full voxelmanip volume of the mapchunk below.

**Comment by paramat** [comment]
I tried editing mgv7 to not overgenerate, and used the lighting call from mgv6:
calcLighting(node_min, node_max);
These shadows remain. There must be something about mgv5/v7/flat/fractal that causes these shadows but it's a mystery.

**Comment by duane-r** [comment]
This affects [Valleys C++] (https://github.com/duane-r/minetest/tree/valleys_c), also a derivative of mgv7, at the same altitude.

![example](http://duanerobertson.com/img/c-demo-32.jpg)

**Comment by paramat** [comment]
Marked as blocker just to keep it in mind as a possible blocker.

**Comment by paramat** [comment]
I plan to llook at this once feature freeze starts.

**Comment by paramat** [comment]
Hmmmm and i have discovered the cause, fix coming.

**Comment by paramat** [comment]
#4013

**Comment by paramat** [comment]
#4013 is merged.
