### ISSUE TITLE
[Feature request] Node definition of alpha for non liquid node

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#2760]
Example: ice
![screenshot_81520285](https://cloud.githubusercontent.com/assets/8843475/8019876/7e9f4352-0c9f-11e5-9e8e-bfd49a302736.png)

**Comment by LeMagnesium** [comment]
I asked this a few days ago on [IRC](http://irc.minetest.ru/minetest/2015-05-30#i_4270620) (I think that's what meant @Rui914) : 

> ElectronLibre | Is it possible to use 'alpha = xxx' in a node's definition with any drawtype or must the node's drawtype be "liquid"/"flowingliquid"?

At the moment, only liquid and flowingliquids can use an alpha value specified in their registration. For example, I was trying to create an amber node, which was not completly opaque. I gave up after about 1 hour of texture tweaking, mask manipulation and tests, sadly realizing there was a very bad solution : making the amber liquid.
Being able to specify an alpha value for not liquid nodes would be a very useful feature.

**Comment by PilzAdam** [comment]
This is already possible, see https://github.com/PilzAdam/minetest_game/commit/cff31f68283486dea4d7fa4554098b91c0d97a3e

**Comment by Rui914** [comment]
Or,
```
"default_ice.png^[alpha:0~255"
```

**Comment by LeMagnesium** [comment]
> Or,
>
>    "default_ice.png^[alpha:0~255"

^[alpha is what I tried, and it didn't work.
It has no effect unless it's a liquid. (here is an example with ^[alpha:10
![Alpha 10](https://lut.im/W0jPnhUQ/qzKxLXeP)

Yet, `use_texture_alpha` works, but I have to set `drawtype` to `glasslike`, and edit the texture.

**Comment by Rui914** [comment]
@LeMagnesium 
Sorry for the confusion.
I said with the intention of the request.

**Comment by LeMagnesium** [comment]
Oh, ok. To me, both should work :

    "default_stone.png^[alpha:130"

and

    -- ...
    tiles = {"default_stone.png"},
    alpha = 130,
    -- ...

should both take the texture called `default_stone.png` and render it with an alpha channel value of 130, for all liquids. Otherwise, specify in the [doc](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3065) that `alpha` can only be used with liquids.

**Comment by PilzAdam** [comment]
> Yet, use_texture_alpha works, but I have to set drawtype to glasslike, and edit the texture.

Thats what the glasslike drawtype is for.

I don't think that hardcoding an alpha in the nodedefinition is good. It should be up to the texture pack to choose a reasonable value, so I think the use_texture_alpha approach is enough.
