### ISSUE TITLE
“camera update” toggles when pressing N on release builds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2762]
It turns out you can still toggle “camera update” in version 0.4.12 with default settings. But not with one of the function keys this time, you have to press the N key for that. I have made sure my `minetest.conf` does not alter this keymapping.
This only works in release builds, not in development/debug builds. It looks like this is unintentional.

Now for my guess on the cause of this bug/weirdness:
In `defaultsettings.cpp` the default for `keymap_toggle_update_camera` is either `"KEY_F4"` (debug build) or `"none"` (release build). My guess is that Minetest thinks of the letter “N” because “none” starts with “n”. ;-)

**Comment by nanepiwo** [comment]
I have this too on a recent build, but interestingly my apostrophe key toggles the debug screen (as does the f5 key) with default settings.

**Comment by kahrl** [comment]
Fixed by 63b12f1f048d83632069a4d0b3d2649cf9be7904.

@Wuzzy2 your guess was spot on :)
