### ISSUE TITLE
Weird Lighting Glitch

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2765]
First, I placed a torch, the black wall as seen in the first two screenshots lit up but briefly darkened.

![screenshot_20150608_183340](https://cloud.githubusercontent.com/assets/10261530/8046915/281c1ba8-0e0d-11e5-9a26-8319be2fb041.png)
![screenshot_20150608_183345](https://cloud.githubusercontent.com/assets/10261530/8046913/2818c25a-0e0d-11e5-8884-767066bff44e.png)

Afterwards, I placed a torch on the wall and the problem was fixed.

![screenshot_20150608_183357](https://cloud.githubusercontent.com/assets/10261530/8046914/28190ada-0e0d-11e5-9f4a-098b32e86262.png)

This is on a multiplayer server.

Similar glitches have happened before to me, but not on such a large surface.

**Comment by paramat** [comment]
@nanepiwo Is this still happening regularly? If not i think this can be closed.

**Comment by paramat** [comment]
nanepiwo hasn't been active on Github for 6 months, and no response.
Lighting code has changed and improved since.
Closing.
