### ISSUE TITLE
Ability for mods to edit damage.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2766]
It would be nice if mods could edit the damage taken when falling.

**Comment by est31** [comment]
#2751 will fix this I think.

**Comment by nanepiwo** [comment]
What I mean is for mods to be able to set the rate of damage when the player falls, for example. I think the issue you linked to only adds a callback to check when the player's hp has changed...

**Comment by TeTpaAka** [comment]
This fixes it only partly. With the callback, you can change the damage taken, but you don't know if it is fall damage. 
This is mainly an engine problem. The fall damage is calculated client-side and sent to the server. So there is no knowledge of what causes the damage.

**Comment by nanepiwo** [comment]
I know some servers have a mod which disables PvP in certain areas. But, it is done with the hacky way of constantly replenishing a player's HP. As at least damage is calculated client side, there should be a way to set the damage per hit to 0 or something like that.

**Comment by TeTpaAka** [comment]
PVP can be disabled in certain areas very easily.
https://github.com/TeTpaAka/save_spawn
It is not a finished mod but can be used as a starting point for further improvements.

**Comment by nanepiwo** [comment]
Nice, so damage can be disabled with minetest.register_on_punchplayer

**Comment by TeTpaAka** [comment]
Well, only punch damage. To disable all damage you can use minetest.register_on_player_hpchange() since aa13baa

**Comment by nanepiwo** [comment]
So it is called before the actual damage is done. Thanks for clarifying!
