### ISSUE TITLE
Add entity callbacks for attaching and detaching

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2769]
If I understand, any entity can be attached to another entity.

So I think callbacks (along with `on_stop`, etc.) for those entities whenever an entity attaches to an entity would be useful.

When an entity attaches, these callbacks are called both to the active and passive entities:
- `on_attaching(a,b)`: Entity `a` attaches itself to entity `b`. The attaching entity `a` gets this callback.
- `on_attached(a,b)`: Entity `b` attaches itself to entity `a`. The passive entity `a` gets this callback.

When an entity detaches, these callbacks are called both to the active and passive entities:
- `on_detaching(a,b)`: Entity `a` detaches itself from entity `b`. The detaching entity `a` gets this callback.
- `on_detached(a,b)`: Entity `b` detaches itself from entity `a`. The passive entity `a` gets this callback.

**Comment by paramat** [comment]
Any comments?
Is anyone interested in coding this sometime? if not closing in 1 month.

**Comment by Wuzzy2** [comment]
Is there anything wrong with the request in particular?
I think callbacks for attaching and detaching are quite essential. It's pretty basic stuff lacking in the Lua API IMO.
Closing this in 1 month only because we have no coder *yet* seems quite aggressive.

**Comment by rubenwardy** [comment]
this is a valid request that improves the API

**Comment by paramat** [comment]
Yes of course, i hope someone states their intention to code it sometime @rubenwardy are you?
If no-one does then we can't keep control of issue number and issues hang around for years with nothing being done.

**Comment by rubenwardy** [comment]
Added by @SmallJoker
