### ISSUE TITLE
Digging upon join.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2770]
Recently, this started happening to me on a recent Minetest build for OSX. I would join a server and my player would start punching. This stops after a while, but opening a formspec and closing it has no effect.

**Comment by Megaf** [comment]
Doesn't this happens when you resize the window while the game is loading?

**Comment by nanepiwo** [comment]
It might, but why does resizing affect digging?

**Comment by C1ffisme** [comment]
Usually, when you resize a window, you hold down the left mouse button. Which I'm guessing starts you out punching before your client has fully loaded.

Try holding down the left mouse button before entering a server.

**Comment by Megaf** [comment]
@nanepiwo I'm not sure, is a know bug on OS X, already reported somewhere, I will see if find it.

**Comment by paramat** [comment]
The player punches if i click the screen before the fame starts.
@nanepiwo is this still happening?

**Comment by paramat** [comment]
No response from @nanepiwo can reopen if needed.
I suspect the screen was clicked before the game started.
