### ISSUE TITLE
Allow semi-transparent pixels in detail texture of connected glass

### ISSUE THREAD

**Issue by An-dz** [minetest/minetest#2773]
Allowing semi-transparent pixels would allow HD textures to create realistic looking glasses rather than having to use weird looking non-transparent pixels. It would also look like glass as it would have some colour change from air.

**Comment by C1ffisme** [comment]
Unfourtunately, there are... Problems... with this. Semi-transperancy is glitchy.

**Comment by An-dz** [comment]
:cry: Maybe a way we can set an alpha for the texture? So to make the details texture work like the water texture. Maybe with some .conf file.

**Comment by C1ffisme** [comment]
Oh... It's a glitch that can probably be fixed, unless it's because of Irrlicht, then they have to fix it.

If it's possible, I'm sure a lot of nodes will become semi-transparent. Ice, Glass...

**Comment by RobertZenz** [comment]
Maybe it would be better to remove `use_texture_alpha` and support by default for all kinds of nodes.

**Comment by LeMagnesium** [comment]
#2760 is a bit related. It has already been requested that all kind of nodes could use the alpha given in their registration or the one from their texture.

**Comment by 4aiman** [comment]
```use_texture_alpha``` + glass = 
![screenshot_20150624_163036](https://cloud.githubusercontent.com/assets/2913210/8331030/65d3fd48-1a8e-11e5-8bc3-ce947a42f3ad.png)

**Comment by An-dz** [comment]
Not that good, there are glitches and the detail texture (glass) is over the default texture (frame)
![Glass glitches](!http://i.imgur.com/4CpsncS.jpg)

**Comment by 4aiman** [comment]
And... your image has a perfect semi-transparency.  :)

Please, attach the textures themselves.
W/o those it's hard to say what it should look like and whether that's truly a glitch.

**Note:** I'm not trying to say the textures look "just fine". My only concern is to make it clear what is *should* look like. Right now I can't tell for sure.

Can't see why a HD texturepack would like to use those not-so-glass-like textures for a glass, though.

**Comment by An-dz** [comment]
Yes, it has semi-transparency and that's great.

That's not the glass texture, it's only a 50% transparent grey rectangle to show how it's being rendered. I did not lose my time creating a texture that I would not be able to use.

Compare the frame in the two following images.

Here's how it should look:
![How it should look](http://i.imgur.com/qUTqFw8.jpg)

Here's how it looks:
![How it looks](http://i.imgur.com/kLtJdAO.jpg)

**Comment by 4aiman** [comment]
@An-dz, as I can see above you want the frame of a glass to look like it's "wooden"?
Then why not use a little smaller details pick?
Here's mine:
![default_glass](https://cloud.githubusercontent.com/assets/2913210/8363976/6427caf8-1b8b-11e5-9dad-166a2a16db40.png)
![default_glass_details](https://cloud.githubusercontent.com/assets/2913210/8363977/644550be-1b8b-11e5-87cd-aecd3708e4b9.png)

Note that details image has no coloured pixels (either opaque or transparent) at its "borders".


I still don't understand what's wrong with the way the glass details image is being drawn.
Maybe @est31 would be able to enlighten me? 
(Or maybe I should just wait for this feature to be implemented and stop asking questions :)

**Comment by An-dz** [comment]
Let me try to explain in a more Minetest way.

Right now it's being drawn as default_glass^default_glass_detail, but it should be default_glass_detail^default_glass, so the details stay below the frame.

Your suggestion won't output a connected texture.

**Comment by asl97** [comment]
from the look of https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/src/content_mapblock.cpp#L758

it seem @An-dz might be right about that, note that i don't know much about c++ let alone the code in the link but my gut tell me the the frame (12 parts) is rendering first then the faces (6 parts)

maybe swapping the for loop position would fix it?

**Comment by 4aiman** [comment]
@An-dz , @asl97 
Ok, now it's finally clear to me :)

And it's also clear that this is a bug, not a feature request :smile: 

@est31, do you agree?

**Comment by paramat** [comment]
Transparency and z-sorting doesn't work in Minetest due to our current use of scene nodes.

**Comment by 0-afflatus** [comment]
I get really confused by these discussions. `use_texture_alpha` kind of works. Sure it's imperfect, but I don't understand how you can say "transparency doesn't work" when clearly it does. What am I missing here ... some new imperial costume?

**Comment by ObaniGemini** [comment]
@0-afflatus : *transparency doesn't work * ***properly***

**Comment by asl97** [comment]
this issue is about the frame and it look fine to me.

![screenshot_20160405_153400](https://cloud.githubusercontent.com/assets/4752645/14274662/3d74c920-fb45-11e5-9093-74c5acb1f695.png)

ps: i was wrong in my [last comment](https://github.com/minetest/minetest/issues/2773#issuecomment-115464392)

**Comment by paramat** [comment]
Oops again i didn't mean to reopen this.
I also meant 'translucency', which does work sometimes but also often does not.

**Comment by paramat** [comment]
The bug with translucency often swaps the visual order of textures, maybe this is why sometimes the 'detail' is below the 'glass'.
