### ISSUE TITLE
disable_jump does not work correctly when sneaking is disabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2774]
I have found a bug in Minetest 0.4.12.

It appears that `disable_jump` does not work correctly when the player attempting to jump has no sneaking capability (`player:set_physics_override({sneak=false})`).

It is very weird:
- If the player stands on `disable_jump` node, and a non-`disable_jump` node is below it, the player _can_ jump
- If the player stands on a normal node, but a `disable_jump` node is below it, the player _can not_ jump.
- Two stacked `disable_jump` nodes work as expected
- If there is no `disable_jump` at all, things also work as expected.

Note: I have only used full solid nodes for testing.

It appears to me that Minetest actually checks the node _below_ the node on which the player is standing, and not the node on which the player is standing.

**Comment by est31** [comment]
does #2241 fix this, can you test?

**Comment by Wuzzy2** [comment]
Nope, it does not fix it. I have tested the fix on b6387b4e0f43503ae139cb31a04f42c401378fdc.

**Comment by paramat** [comment]
#5327 merged, bug still present?

**Comment by Wuzzy2** [comment]
Yes.
Tested version: 46276414ed51d61dc29879ac85e861dc770d90da

**Comment by sofar** [comment]
Confirmed broken in `0.4.16` with sneak disabled on the server, player can still jump.

**Comment by paramat** [comment]
@SmallJoker

**Comment by paramat** [comment]
#6458 merged.
