### ISSUE TITLE
dofile() silently fails on syntax errors

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#2775]
```Lua
-- init.lua
print("this runs")
dofile(minetest.get_modpath("dofilefail") .. "/two.lua")
print("this runs")


-- two.lua
print("This never runs")
local a = 0
a += 1  -- syntax error
```

Issue first added by 3a8c7888807e4483bbdb3edd81c9893f3e2f427d (Add mod security by @ShadowNinja)

**Comment by est31** [comment]
See the referencing commit for a quick fix. I'm however not sure whether the solution is the proper one, as I don't know what to return (returning the return value of the error function is not neccessarily the right thing), also I don't know whether I have to clean up the stack (e.g. remove the nil thats below the error message).

**Comment by rubenwardy** [comment]
It should crash Minetest (ie: error in mod) - is that what your patch does?

**Comment by est31** [comment]
Try it
