### ISSUE TITLE
Missing register_on_setnode

### ISSUE THREAD

**Issue by bdjnk** [minetest/minetest#2776]
Or perhaps there's some other mechanism for determining a mod based change of node?

[place_node](http://dev.minetest.net/minetest.place_node) -> [register_on_placenode](http://dev.minetest.net/minetest.register_on_placenode)
[set_node](http://dev.minetest.net/minetest.set_node) -> nil

**Comment by rubenwardy** [comment]
It would increase the time of set_node. Although when it matters you'd use LVM.

**Comment by RobertZenz** [comment]
I don't think that callback support is desired there. Let's compare their Lua API description.

> set_node: Sets a specific `MapNode` in the `VoxelManip` at
that position
>
> place_node: Place node with the same effects that a player would cause

So what we can extract from that is that `set_node` is some sort of 'internal' function and that if you want to have similar effects as when a player places a node you should use `place_node`. `set_node` is really "set the node here without any side effects".

Though, it might very well be that a mod uses `set_node` even though it should use `place_node` in that moment, I'd report that as a bug against that mod.

**Comment by bdjnk** [comment]
@RobertZenz I actually sort of agree. However, mods do use set_node, far more than place_node. Take a look at, for example, the default game.

But this actually brings up an important further consideration. What about LVMs?

Perhaps there should be some general mechanism by means of which mods can track changes to the environment.

**Comment by paramat** [comment]
The 'register on' callbacks are mostly linked to a player. set node is more of a mod thing, there is 'on construct' which can be added to a node definition.

**Comment by ShadowNinja** [comment]
`set_node` is missing callbacks because it needs to be as fast as possible.  Some mods (eg, WorldEdit) call `set_node` thousands or even millions of times, and the overhead of running callbacks would be unacceptable.

**Comment by paramat** [comment]
Good point.

**Comment by bdjnk** [comment]
I understand the performance concerns, and I actually agree. However, short of a mod polling the environment, which is its own performance drag, there is no way to know when `set_node` (or an LVM) has altered to world. This seems to me a fairly glaring deficiency.

The solution that occurs to me is to have the engine track changes, and alert listeners after the mod function returns or (less optimally) after an interval. This way environment change notifications could be sent with minimal additional overhead.

**Comment by paramat** [comment]
LVM and schematics intentionally have no callbacks for speed, that won't change. So far i haven't seen much need for 'set node' callbacks.

**Comment by paramat** [comment]
LVM and schematics intentionally have no callbacks for speed, that won't change. So far i haven't seen much need for 'set node' callbacks.

**Comment by paramat** [comment]
Disapproved.
