### ISSUE TITLE
Textures sometimes corrupted

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2778]
Sometimes, not always,  textures of items in my inventory are broken as in being a weird set of grayish purplish pixels. Every time this happens, the broken textures look different, but they always occur on the same nodes (mostly full-block items and stuff from stairsplus, not craftitems).

**Comment by est31** [comment]
Can you provide a screenshot, and find out how to reproduce?

**Comment by nanepiwo** [comment]
I think this is reproduced when the screen is turned off and back on to get to the lockscreen at some time during loading

**Comment by nanepiwo** [comment]
Like so... Sometimes more textures get corrupted like this, sometimes not. 
![screenshot_2015-06-21-18-25-05](https://cloud.githubusercontent.com/assets/10261530/8273593/058354a4-1843-11e5-945f-03f59eedaafc.png)

**Comment by 4aiman** [comment]
@nanepiwo, try to use OGLES1, disable mip-map and enable preload_item_visuals.

Then tell if that helps, please.

**Comment by nanepiwo** [comment]
BTW, an official android build forum topic (https://forum.minetest.net/viewtopic.php?f=3&t=9389) mentions that trying inventory_image_hack = true might help. I will also try @4aiman 's suggestions.

**Comment by MoNTE48** [comment]
After some tests, I realized that it is necessary to include inventory_image_hack default for Android. Why is not included so far?

**Comment by est31** [comment]
@nanepiwo with an up to date apk from master, can you reproduce the bug?

**Comment by paramat** [comment]
Indeed we now have a new mesh-based inventory so this may be fixed now.

**Comment by est31** [comment]
That's why I asked. Its no guarantee, but there is a strong chance that the bug is fixed.

**Comment by paramat** [comment]
@nanepiwo this should be fixed now?

**Comment by paramat** [comment]
No response, should be fixed now.
