### ISSUE TITLE
Render bug with shaders enabled

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2780]
When I enable shaders, water surface makes interesting patterns:
![animated](https://cloud.githubusercontent.com/assets/8872119/8145529/ebc33c56-120b-11e5-92c6-c02c6a2a4180.gif)
These patterns have two manifestations: 1. random spontaneous blinking when viewing range is limited. There the blinking mostly appears inside a limited distance. Seen above.
2. constantly "badly" rendered water surface, not changing over time, only depending from pitch and yaw, both there with max viewing range enabled and disabled:
![animated](https://cloud.githubusercontent.com/assets/8872119/8145588/dcc87e9e-120d-11e5-8499-1536abfafb58.gif)

**Comment by RHRhino** [comment]
maybe related? https://github.com/minetest/minetest/issues/1404

**Comment by est31** [comment]
Dupe, closing
