### ISSUE TITLE
Entry in formspecs broken

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2781]
With the latest Git, trying to join a server gives the following error: "ERROR: Couldn't resolve address: No address associated with hostname" despite having entered an address. Also, both the username and password boxes have characters already in them when opened.

Username box:
![screenshot_2015-06-13-21-15-49](https://cloud.githubusercontent.com/assets/8821916/8146914/178599c2-1222-11e5-890d-0fc337244e73.png)

Password box:
![screenshot_2015-06-13-21-15-54](https://cloud.githubusercontent.com/assets/8821916/8146916/27617ab4-1222-11e5-8ce2-80d2bec1089a.png)

**Comment by est31** [comment]
caused by b6387b4e0f43503ae139cb31a04f42c401378fdc or 572990dcd3f43386860b5b14015ad722fb96ea83, which is very weird, because android uses irrlicht 1.9 and therefore doesn't even use `intlGUIEditBox`, which was the main change of those two commits.

**Comment by est31** [comment]
60f31ad52348c53209701d0112f9f809018f7188
