### ISSUE TITLE
wide_to_utf8 doesn't work on android

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2782]
When you do `hex_encode(wide_to_narrow(utf8_to_wide("hello")))` (which works), you'll get `68656c6c6f`.
When you do `hex_encode(wide_to_utf8(utf8_to_wide("hello")))` (which doesn't work), you'll get `010101010101`.
60f31ad52348c53209701d0112f9f809018f7188 only hacks around this issue, by falling back to the old method. This is the root cause of #2781.

**Comment by est31** [comment]
fixed by eb3aac20c879b9532cd3b678efb2126adcd07af7

**Comment by est31** [comment]
We had to bypass it again due to issues in #2973, in 457d42c5997cc430231ed221f06d8f4bba2100e7, as eb3aac20c879b9532cd3b678efb2126adcd07af7 only fixed the problem for some devices.

**Comment by MoNTE48** [comment]
I have not seen this error today in any of the devices. It seems it was agreed earlier. I do not remember where.

**Comment by est31** [comment]
@MoNTE48 see commit 457d42c5997cc430231ed221f06d8f4bba2100e7 it disables normal wide_to_utf8 for android.
