### ISSUE TITLE
ID for every player

### ISSUE THREAD

**Issue by Snipie** [minetest/minetest#2791]
I think it would be easier to refer to players on a server with their IDs.
IDs would be volatile that everytime you connect the server might give you a different ID.
This would be useful when you for example want to send a PM to someone, you wont have to remember his username only his ID which would be 3 digits maximum. ( /msg 123 hello. )

A seperate window that let you see all the connected players and their IDs and usernames would be nice.

These two features exist on SAMP (GTA San Andreas MultiPlayer) and they are handful.

**Comment by est31** [comment]
Right now, the f10 chat offers two features that make `/msg` chatting easier:
1. nick completion via tab
2. a history of entered commands, accessible via up and down arrow keys

**Comment by C1ffisme** [comment]
I can see this being helpful, but I mean, it's really a question of whether or not you want to type a lot or not.

**Comment by rubenwardy** [comment]
this could be done using a mod, although you'd have to override chat commands like `/bring` and `/privs` - I'm not sure if that's possible.

**Comment by nerzhul** [comment]
I also think this could be done by a mod. But i agree that playerID should be useful to suppress many player comparison by std::string.

**Comment by 4aiman** [comment]
It *is* possible to override any chat command: just register a new one with the same name ;)
Overall, I'd prefer to have IDs for every SAO accessible through Lua.

**Comment by paramat** [comment]
> you wont have to remember his username only his ID which would be 3 digits maximum

A username is more friendly and memorable than a 3 digit number :-1:

**Comment by 4aiman** [comment]
If anyone cares I'm still *for* the feature. Will make it a lot easier to refer to players and entities for things like portals/teleports. I also agree with nerzhul.

**Comment by nerzhul** [comment]
3 digits is not good. I have a database for my users on my server and there are 31k accounts (not all active, but all connected one time). a U32 is the minimum

**Comment by rubenwardy** [comment]
> A username is more memorable than a 3 digit number, this seems pointless :-1:

Not when the username is fsjfeisheiedndkamei which has happened a few times. 

> 3 digits is not good. I have a database for my users on my server and there are 31k accounts (not all active, but all connected one time). a U32 is the minimum

> IDs would be volatile that everytime you connect the server might give you a different ID.

----------------------

I'm neutral on this issue

**Comment by 0-afflatus** [comment]
I would find this useful for the reason given by rubenwardy above, but not if they had to be volatile.

**Comment by ShadowNinja** [comment]
This would also notable be necessary if, eg, Unicode support was added to names, as admins would have a really tough time banning someone with a name with characters that they don't have on their keyboard.
I think this is a good idea to implement for this simple reason.

**Comment by est31** [comment]
Most services don't use unicode for the technical names for this precise reason. They are all in latin english ASCII letters. I'm against unicode for player names, the restricted set we have now is enough.

**Comment by paramat** [comment]
> Unicode support was added to names

Bad idea,

**Comment by 4aiman** [comment]
> the restricted set we have now is enough.

What is "good" for a dev can be "not so good" for a player.

**Comment by rubenwardy** [comment]
As a server owner, I oppose support for any usernames which contain letters not on a qwerty keyboard.

**Comment by 0-afflatus** [comment]
I think there is a huge amount of cultural bias in this conversation. Unicode support is a big issue, and IMO we should do it properly, so this isn't something we should do piecemeal or immediately. The limited set of characters without diacritics basically limits us to English - most other languages are represented incorrectly. So this isn't really about what is good for a dev or server owner, the current state is good for people who are comfortable using English as the primary language for communication. That currently satisfies the majority of Minetesters, but I think there is a long-term usecase for a Russian server owner (as an example) who finds reading latin script a pain.

I have experienced other online games where every single object can be referenced via a unique numerical ID - one of the things this allows is object-specific triggers. I know this goes well beyond the scope of this issue, but I think it's a useful perspective.

**Comment by 4aiman** [comment]
@0-afflatus t 
> a Russian server owner (as an example) who finds reading latin script a pain.
A server owner probably *should* be comfortable to read latin, since editing mods is required for a good server. :)

But players - those are different.
To oppose non-latin characters means to misservice them. 

But then again, every other dev there is may or may not want Minetest to be played. 
Some of them just having fun contributing to Minetest. 
That does not correlate with a dev being or not being a server owner in any way.

**Meanwhile**
Enabling IDs won't enable non-latin characters in nicks.
And even enabling *support* for non-latin characters in nicks will *not* force server owners to let non-latin characters in nicks be allowed on their servers.
Thus, no reason to oppose IDs for players.

**Comment by est31** [comment]
Its not just about server owners, sometimes players want to speak to other players in the server too. If their name consists of non-ascii characters, there is a problem, especially for players from countries with ASCII language based character sets.

But players with non ASCII character sets will always need the ability to switch to ASCII keyboards because they need those for movement, at least until #3190 gets fixed.

What we could do however is to give people a non-technical name that doesn't impose any restrictions on the character set. They will get shown per default ingame and in chat, but you can always switch between the technical name and the non-technical one in the display. Banning etc will be done only with the technical name.

**Comment by paramat** [comment]
> 3 digits is not good. I have a database for my users on my server and there are 31k accounts

A 5 or 6 digit number is no more memorable than the username, and usually much less so.
We're not going to add unicode support.

So is there any reaosn to keep this open?
Anyone interested in coding any potentially useful ideas here?
If not closing in 1 month.

**Comment by nerzhul** [comment]
if player have a DB id, we don't care about digit, it should be a uint64_t that's all :)

**Comment by Snipie** [comment]
My aim of creating this issue was that I found referring to players in-game was hard but this is now gone by nickname completion. I just type the first character and then hit TAB it will complete it for me. I don't know how is it on Android.
but this feature is still not well known and IMO is needed to brought to the player as a tip or something.
Also TAB completion is not in the latest stable release.
I would like also to add that I would be delighted and also would help translate if the game supported non-latin languages like Arabic for example.

**Comment by paramat** [comment]
Ok closing then.
