### ISSUE TITLE
When have to hand an item of high resolution image, drawing time will increase.

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#2800]
![screenshot_20150618_230924](https://cloud.githubusercontent.com/assets/8843475/8233067/1b8417d8-160f-11e5-819d-a80fb83ba248.png)
![screenshot_20150618_230931](https://cloud.githubusercontent.com/assets/8843475/8233068/1ba04e9e-160f-11e5-8143-6cde7078713f.png)

**Comment by PilzAdam** [comment]
This is because the 2D texture is transformed into a 3D mesh. The more pixels the texture has, the more complex the mesh gets, and thus the drawtime increases.

As I see it this is a non-issue.

**Comment by Rui914** [comment]
Is there a way to be displayed as 2D texture?

**Comment by hunter688** [comment]
There is no cache? Will be fine add feature to use cache. When player join server, downloaded all content, will also generate cached versions of all textures/meshes.

**Comment by est31** [comment]
@hunter688 there is a cache, what @PilzAdam sais is that we convert a 2d image into a 3d mesh before displaying -- clientside.

**Comment by C1ffisme** [comment]
Wait... Hold on... What if we used the pre-load visuals setting? When it's on, pre-make 3d meshes for each object. When it's off, make them whilst the game is running.

**Comment by PilzAdam** [comment]
@C1ffisme the problem is not the generation of the meshes, but the rendering.
