### ISSUE TITLE
wield_box definition for node

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#2802]

**Comment by est31** [comment]
whats your usecase (which node do you want to make nicer)? what should the wield box item do? how should it look like? like nodeboxes?

**Comment by Rui914** [comment]
Like node box.
I want wield_box can make a inventory icon.
![screenshot_20150621_115756-min](https://cloud.githubusercontent.com/assets/8843475/8270178/e6e1e64a-180c-11e5-8f71-5c5b6c1ca2cf.png)

**Comment by asl97** [comment]
from http://dev.minetest.net/minetest.register_node :
```inventory_image — This texture will be used for every state except when placed in the world (i.e. it will be used in inventory and when dropped). If undefined (nil) an image will be automatically constructed from tiles.```
