### ISSUE TITLE
Texture corruption

### ISSUE THREAD

**Issue by cheapie** [minetest/minetest#2815]
I am experiencing texture corruption, starting with commit 53efe2e (I did bisect and determined it's that one).

GPU: AMD Radeon HD 7770
Driver: "radeon" (the open-source one)
Settings: This only occurs if "generate normalmaps" AND "parallax occlusion" are on.

Good:
![screenshot_20150621_233245](https://cloud.githubusercontent.com/assets/415827/8275585/3687cc44-186e-11e5-9c53-9910b53dd95e.png)

Bad (note the extra line on the near edge and the fuzziness on the far edge):
![screenshot_20150621_233318](https://cloud.githubusercontent.com/assets/415827/8275588/3bc239ce-186e-11e5-9ed5-419c2f09dcf1.png)

**Comment by 4aiman** [comment]
I remember VanessE was complaining about extra line of pixels on IRC and the fact it was fixed by RBA (not sure it was him).

Try to rebuild the latest dev and see if the problem persist.

**Comment by cheapie** [comment]
RBA was insisting on IRC that this somehow isn't a bug, and parallax occlusion is somehow supposed to do that.

**Comment by kilbith** [comment]
Texture displacement is inherent to the relief mapping, and he will try to find out a solution for the non-tiled textures.

**Comment by RealBadAngel** [comment]
https://github.com/minetest/minetest/commit/655fc6010ffd4be7de315be261df2a61d5d4538a
This fixes the issue engine side (will require also network protocol raising and minetest_game changes)

**Comment by est31** [comment]
and fix activated in 2eb329cc6362958537737c2a82ae593c7ba5d30a
