### ISSUE TITLE
Windows client doesn't render nodes at screen edge

### ISSUE THREAD

**Issue by technomancy** [minetest/minetest#2820]
This only happens with the software renderer (with OpenGL or DirectX I get nothing at all, see #2684) connected to a Linux server.

![image](https://cloud.githubusercontent.com/assets/141/8321432/ff82681e-1a50-11e5-8b57-35e60bd93f41.png)

 If I turn shaders on I get the same thing, but the whole screen turns red.

![image](https://cloud.githubusercontent.com/assets/141/8321474/79788612-1a51-11e5-87ae-6f5bc590b7d2.png)

**Comment by technomancy** [comment]
This is on the 64-bit MSVC build of 0.4.12.

**Comment by kilbith** [comment]
This is known from a long time ([hint](https://forum.minetest.net/viewtopic.php?f=6&t=11468&p=173049#p172567)). Don't use this broken driver.

**Comment by 4aiman** [comment]
1. Shaders doesn't work with anything but OpenGL
2. Software renderer has been like this at least since the early 2013
3. It's better to use OGLES drivers on old IGAs

As for #2684 - I can't reproduce it. That being said I'm still using the latest official build for Win.

**Comment by technomancy** [comment]
Strange; I wonder why the problems don't exhibit for singleplayer games. If the software renderer is known to be useless in network games, let's get it documented and we can close this issue out.

**Comment by kilbith** [comment]
You play on a server as well in singleplayer.

IIRC, @sfan5 has already suggested to take off the possibility to choose that driver.

**Comment by 4aiman** [comment]
@kilbith I hope he hasn't succeed. I.e. remove from the GUI all you want, but leave that settable via config. It's very useful to test MT inside a VBox w/o proper HW video acceleration.

**Comment by sfan5** [comment]
> IIRC, @sfan5 has already suggested to take off the possibility to choose that driver.

Yes, — if at all — the menu should allow people to use the burningsvideo driver which works better than any of the other software drivers.

**Comment by technomancy** [comment]
As an update, this definitely seems to depend on the version of the server; I upgraded the linux server to git master and it's running smoothly, whereas earlier it was happening with an 0.4.12 server and a server running git master from May. I'm happy to close this out unless we want to explore it further.

**Comment by 4aiman** [comment]
I'd rather vote *for* exploring a bit more. 
Linux server + windows client is not such a rare case, after all ;)

On a side note, burningsvideo works awfully slow in VBox w/o video acceleration.
I'd rather cope with not rendered blocks in order to be able to test MT within VBox.

I'm all for removing option but adding some cmake build flag, like ```-DENADLE_SOFTWARE_RENDERER=1```

**Comment by paramat** [comment]
Related to FOV and frustrum culling?

**Comment by sfan5** [comment]
@paramat No, this is related to the Irrlicht software driver being a broken piece of software.

**Comment by SmallJoker** [comment]
The `software` render is broken. Not our issue.
