### ISSUE TITLE
Ability to create inventories like the craft output field from Lua.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#2826]
Currently it is not possible to create an inventory that behaves similar to the craft output field. It would be very nice if we would be able to create inventories that behave the same way.

The behavior I'm talking about is the ability to take the content and without having to drop it somewhere it is removed from the inventory.

**Comment by est31** [comment]
What would be your usecase?

**Comment by RobertZenz** [comment]
My exact usecase is [Artisanry](https://github.com/RobertZenz/minetest-australopithecus-artisanry), a mod that aims to allow to have multiple outputs per receipt (so you send one stone in and decide if you want to have the stairs, different slabs or other stuff). Being able to create an inventory that behaves exactly like the output slot would make the GUI actually usable, currently it behaves just like another inventory, which makes it quite hard to use.

Also I can think of workbenches, furnaces, etc. which would benefit from that.

**Comment by est31** [comment]
Ah, I see. Too bad you can't enjoy my crafting speedup #2596 then. Also, the crafting system has the concept of *replacements*, which is something like multiple outputs.

**Comment by est31** [comment]
Also, if I remember right, you can register 5x5 craft recipes, and also add 5x5 crafting grid workbench formspecs.

**Comment by RobertZenz** [comment]
Yes, you can. My main reason for writing that mod was to have identical receipts with different outputs (or to have the same receipt with multiple outputs, however you look at it). Also I realized along the way that one can easily realize f.e. crafting tables with such a system or use it in any other way (though, support for it is not added yet).

**Comment by est31** [comment]
either way, its good to have multiple implementations of something around.

**Comment by rubenwardy** [comment]
surely this can be done with detached inventories?

**Comment by paramat** [comment]
Since you're an inventory expert it probably is.
