### ISSUE TITLE
Ability to specify coordinates for /spawnentity

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#2829]
Currently, `/spawnentity` works like this:

```
/spawnentity mod:entity
```

What about giving it an optional argument at the end, like this?

```
/spawnentity mod:entity 0,10,0
```

That would specify the spawn coordinates of the entity.

**Comment by Ombridride** [comment]
+10 000, we NEED this feature for mesecons systems ! (mostly with command block)

**Comment by est31** [comment]
c5c609ce3d0ff7b959adc72c26486c14b2219046

**Comment by Ombridride** [comment]
Commited so fast, thank you very much ! :)
