### ISSUE TITLE
Client desync

### ISSUE THREAD

**Issue by asl97** [minetest/minetest#2832]
the client slowly get desync from the server, action performed by client apply immediately on the server but action performed by other player get delayed by the desync.

unknown cause.

---

old report:

---

start a client-server world and use another computer to join,
lets call the client-server as client1 and other computer-client as client 2

using client2, randomly shot the laser mk3 from technic in a desert and try to cause lots of falling sand, client2 slowly become desync and it worsen slowly although the client1 doesn't get desync.

so the client1 could show day time while the client2 could show night time.

every action make by the client1 doesn't show Immediately on client2 but every action by client2 is show immediately on client1

client2 can only get resync by reconnecting to the server, client2 doesn't seem to try to get resync even when both client are idling, the time flow the same,
ie: when client2 is desync by X amount, it stay desync by X amount while idling
eg: client1 could be watching the sun rise while client2 watch the sun set and when client1 watch the sun set, client2 would be watching the sun rise.

the server is on a wlan ad-hoc network so i don't think it's cause of the network.

**Comment by 4aiman** [comment]
Same here. But only windows MINGW build is affected (I can't build with VS).
It is also irrelevant who launches a server.
But as for getting re-synced, all I have to do was to teleport linux player to a windows one. Gradually the desynchronization disappears (5-20 seconds) and as  long as linux player is there, the windows one has no delays

**Comment by rubenwardy** [comment]
Has anyone been able to reproduce this recently? Does this happen regularly?
