### ISSUE TITLE
Add “cancel” button for in-game volume and password menus

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2834]
From the in-game menu, you can access a password menu (only in multiplayer) and a menu to change the volume.

I suggest to add a “cancel” button to both these menus.

**Comment by jogag** [comment]
You can always press escape to close but a cancel menu would be great.

**Comment by Dragonop** [comment]
+1
Mostly useful for android users

**Comment by red-001** [comment]
The sound change menu already has an `exit` button so it doesn't really need a `cancel` one.

**Comment by Wuzzy2** [comment]
I need to clarify:

The “Cancel” button is supposed to abord/discard the input. E.g. if you start with 100% volume, enter sound menu, change it to 50%, then click “Cancel”, the volume should be go back unchanged to 100%.
If you hit Esc this counts as confirmation (the volume you set is saved, not discarded).


Also, current, there is a “Back” button, but this closes the menu entirely, returning you to the game, NOT to the pause menu. This is a bit inconvenient.

**Comment by nerzhul** [comment]
@Wuzzy2 discard is more than a windows feature, in MacOS you don't have really save/exit, for the sound it make sense it's consistent like every other menu to not have this discard method (main menu doesn't permit to discard options you change, for example)

**Comment by red-001** [comment]
partially fixed a button has been added to the password change menu.

**Comment by paramat** [comment]
:-1: Disapproved.
