### ISSUE TITLE
[Esc] does not close the in-game keybinding menu

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2836]
In Minetest 0.4.12, there is this in-game menu where you can change the keybindings.
If you hit [Esc], the menu does not close.

IMO it should close when you hit [Esc], because this is the case for every other menu in the pause menu.
Anything else would be inconsistent.

**Comment by est31** [comment]
You mean keybindings?

**Comment by est31** [comment]
This seems to be an easy bug

**Comment by est31** [comment]
842579eb8c31e6a5d4fb3a56413380b11b7252b7
