### ISSUE TITLE
Add sound volume controls into main menu

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2837]
You can change the volume in-game, but not in the main menu.
This is a bit strange. ;-)
I suggest to add a sound volume control into the main menu as well.

**Comment by est31** [comment]
Yea, the settings menu needs to be expanded.

**Comment by jogag** [comment]
That settings menu is **really weird**, I think it must be divided into categories (video, graphics, gameplay, sound...). And adding a new "music" sound category, its volume can be controlled separately.

**Comment by paramat** [comment]
Not really strange, in-game is when you know if volume needs changing.

Anyone interested in coding this? If not closing in 1 month.

**Comment by DS-Minetest** [comment]
You can change the sound volume in main menu. Go to advanced settings and change `sound_volume`.

**Comment by paramat** [comment]
That's good enough.
