### ISSUE TITLE
[Request] minetest.get_inventory_image

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#2839]
I want to get nodebox image.
![screenshot_20150621_115756-min](https://cloud.githubusercontent.com/assets/8843475/8270178/e6e1e64a-180c-11e5-8f71-5c5b6c1ca2cf.png)
(This like.)

**Comment by LeMagnesium** [comment]
There are many ways to get an inventory image, the most simple being `minetest.registered_item[itemname].inventory_image`. You can also use [Inventorycube](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L307).

**Comment by est31** [comment]
And what do you want to do with it?

**Comment by Rui914** [comment]
minetest.register_node("box", {
	drawtype = "nodebox",
	tiles = {"default_stone.png"},
	node_box = {
		type = "fixed",
		fixed = {
			{-0.5, -0.5, -0.25, 0.5, 0.5, -0.25},
			{-0.5, -0.5, 0.25, 0.5, 0.5, 0.25},
			{0.25, -0.5, -0.5, 0.25, 0.5, 0.5},
			{-0.25, -0.5, -0.5, -0.25, 0.5, 0.5}
		}
	},
})

minetest.register_node("test:test", {
	drawtype = "normal",
	tiles = {"default_stone.png"},
	inventory_image = minetest.get_inventory_image("test:box")
})

**Comment by est31** [comment]
erm, I think this exists already. Read [this page](http://dev.minetest.net/texture) for more clarification

**Comment by Rui914** [comment]
![screenshot_20150621_115756-min](https://cloud.githubusercontent.com/assets/8843475/8270178/e6e1e64a-180c-11e5-8f71-5c5b6c1ca2cf.png)
I want to get the node box preview image.
Or, is it already possible?

**Comment by est31** [comment]
ah I see

**Comment by Rui914** [comment]
Sorry for my bad English.

**Comment by Rui914** [comment]
https://github.com/BlockMen/hud/issues/22

**Comment by paramat** [comment]
We have meshes for inventory items now.
