### ISSUE TITLE
RE-SENDING timed-out RELIABLE to 127.0.0.1

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#2842]
The problem starts when ItemDefManager start registering the items and nodes.
All packets sent to 127.0.0.1 time-out
Verbose debug log, shortened: http://pastebin.com/xTYEFPZx

This bug didn't exist in 622918d and in c6766b2 yet, but exists in 36163d9 . (Win32, MSVC build)

Is this report helpful enough or is a bisect required to find the bad commit?

**Comment by est31** [comment]
bisect would be good.

**Comment by SmallJoker** [comment]
Solved with newwest minimap fixes.
