### ISSUE TITLE
Apply working anti-aliasing to rendered world

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2846]
Many 3D games have anti-aliasing, so I guess this is a pretty obvious feature request.

Should also be added as a setting.

**Comment by Calinou** [comment]
We already have:

```
fsaa = 0|2|4 # Defaults to 0
```

(Do not use higher values, everything will be blurry.)

Note how items are glitchy when this is enabled.

**Comment by Wuzzy2** [comment]
Oh, cool. Why is this not exposed in the options menu? :-(

**Comment by asl97** [comment]
@Wuzzy2 i think it cause it's:
```
#    Experimental option, might cause visible spaces between blocks
#    when set to higher number than 0.
```

**Comment by Wuzzy2** [comment]
Okay, I have changed the title accordingly. ;-)

I have spotted one issue with anti-aliasing so far:

https://i.imgur.com/jiKFIjx.png
https://i.imgur.com/E8UpI3b.png

It looks like some superficial pixels are drawn from the wieldhand and the jungle grass. The wieldhand pixels change when you walk, but they don't change when you stand still. Looking around does not change them either.

**Comment by kwolekr** [comment]
This is a duplicate issue, and also has already been fixed.  Closing.
