### ISSUE TITLE
Font characters broken

### ISSUE THREAD

**Issue by mahmutelmas06** [minetest/minetest#2847]
Turkish characters  (probably other non ascii characters too )  is not shown as it should be since last week. There are just blanks instead of these characters. English characters are fine.

**Comment by est31** [comment]
@SmallJoker has reported this too I think.

**Comment by kilbith** [comment]
What's your OS ?

**Comment by mahmutelmas06** [comment]
Windows 7 64bit.
 I have these issue only the builds from last week till now. There was no issue before.

**Comment by SmallJoker** [comment]
Yes, I reported this bug in IRC after @mahmutelmas06 wrote a forum post about this issue.
Quoting myself:
> Builds until June 6 are fine and those after June 21 are broken (+/- some days).
He pointed out that the build 502e40a worked, the fail must be between that ommit and the one from June 21: 622918d

It's a character issue -> a commit between 572990d and d105bf2 @est31

**Comment by est31** [comment]
Does it work with irrlicht 1.9?

**Comment by est31** [comment]
So, how does the bug manifest? can you enter turkish characters in chat? can you show a screenshot, before after?

**Comment by mahmutelmas06** [comment]
Here is the screenshot. All was nice with stefan's latest build.
![Uploading screen.jpg…]()

**Comment by mahmutelmas06** [comment]
Here is the screenshot. All was nice with stefan's latest build.

![screen](https://cloud.githubusercontent.com/assets/11191763/8394568/88e66e0a-1d46-11e5-9909-c5e3e78a7a68.jpg)

**Comment by SmallJoker** [comment]
I alias'ed `utf8_to_wide` with `narrow_to_wide` and `wide_to_utf8` with `wide_to_narrow` in string.cpp, it solved the problem on here.
But now it's no longer UTF8...

**Comment by est31** [comment]
Great, that's the emergency fix for 0.4.13 then, if nobody takes care of this until 0.4.13.

**Comment by Rui914** [comment]
I have this problem too.

before:
![minetest _001](https://cloud.githubusercontent.com/assets/8843475/8502534/482af336-21ec-11e5-86f4-2ba68a797477.png)
after:
![minetest _002](https://cloud.githubusercontent.com/assets/8843475/8502549/6f10401e-21ec-11e5-90c4-34159dec0fd5.png)

**Comment by est31** [comment]
It will be disabled with a non-proper solution for 0.4.13, if nobody with enough knowledge can fix the issue. I have no windows box to test this.

**Comment by est31** [comment]
about how to disable it for you personally: do it like 60f31ad52348c53209701d0112f9f809018f7188

**Comment by Rui914** [comment]
I dont know C language (C ++) .
Is it possible to disable it by changing the current code?

**Comment by est31** [comment]
Can you try now, 2891 got merged.

**Comment by est31** [comment]
Fixed, as @SmallJoker confirms
