### ISSUE TITLE
Incosistent minetest.conf.example

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#2850]
Some settings in minetest.conf.example have their description under and not above them.

**Comment by est31** [comment]
Yes, I'd like it to be description-above-setting too.

**Comment by RealBadAngel** [comment]
For me more sense makes description below the setting.

**Comment by kilbith** [comment]
The description is never before the words in the dictionaries. It's just common sense : you don't describe something that you don't have yet named or introduced (else it's confusing).

**Comment by bdjnk** [comment]
In every config file I know of, the description is above the setting. This is also true in programming, where the documentation comments always come before the code

**Comment by SmallJoker** [comment]
We should do it like in the lua_api.txt fle, description below the setting.

**Comment by Calinou** [comment]
Description above the setting, because it is a standard in eg. `php.ini`.

**Comment by PilzAdam** [comment]
@RealBadAngel this is not a discussion how it should be. Also in the future just stay with the conventions we already use instead of silently doing your own stuff.

**Comment by paramat** [comment]
Yes, additions should follow the majority of entries: description above. Shaders settings are currently reversed.

**Comment by ShadowNinja** [comment]
6c5bc14290e8895a61ca2bf9b71fa3c69857675a
