### ISSUE TITLE
Selection boxes for attached entities

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#2851]
I recently noticed that, if an entity is attached to another entity or a player, it no longer has a collision box, even if self.collisionbox is present. Would it be possible to make collision boxes work for attachments please, so that they can be punched or right-clicked?

Example from my mod, Creatures: I recently added 3D items, which allow the wielded item to show in the right hand as well as other inventory items to be worn on the body (such as on the belt). Obviously it relies on an attached Lua entity for each item. I was going to add support for pickpocketing, which would let players steal items from the mob's hand or belt by right-clicking them. After I noticed this limitation I had to drop the idea, because there's no way to select an attached entity by looking at it.

**Comment by est31** [comment]
hehe cool idea.

**Comment by DS-Minetest** [comment]
:+1: 
attached collision boxes would be great, you could for example make a vehicle thats more long than wide and attach 2 invisible entities, each at one end:
not turned:
![collision_before](https://cloud.githubusercontent.com/assets/7613443/20101960/8127f4d8-a5c4-11e6-8bb1-7ff911375cb2.png)
turned:
![collision_after](https://cloud.githubusercontent.com/assets/7613443/20101967/898d3a02-a5c4-11e6-9c5d-36a81b93fd4d.png)

**Comment by DS-Minetest** [comment]
i suggest to edit `set_attach(...)` like this:
`set_attach(parent, bone, position, rotation, disable_collisionbox)`
where `disable_collisionbox` is normally `true` (so that nothing is changed automatically)

**Comment by DS-Minetest** [comment]
did nobody subscribe this issue?
the 4 participants are @MirceaKitsune , @est31 , me and @paramat

**Comment by DS-Minetest** [comment]
its sad, nobody is interested in this issue :disappointed:

**Comment by paramat** [comment]
Anyone interested in coding this? If not closing in 1 month.

**Comment by paramat** [comment]
Any core dev interest?

**Comment by rubenwardy** [comment]
Krocks open entity pr will fix this

**Comment by SmallJoker** [comment]
@rubenwardy No, my PR only addresses the issue where attached objects could not be damaged or pointed. The collision calculation is left untouched, which would be this code area:
https://github.com/minetest/minetest/blob/326eeca306f7bfb53ae3685eef18978dd81e587e/src/content_sao.cpp#L347-L368

**Comment by rubenwardy** [comment]
Ah, my bad. Read selection box

**Comment by paramat** [comment]
Actually, the request is for selection boxes:
> Would it be possible to make collision boxes work for attachments please, so that they can be punched or right-clicked?

>  I was going to add support for pickpocketing, which would let players steal items from the mob's hand or belt by right-clicking them. After I noticed this limitation I had to drop the idea, because there's no way to select an attached entity by looking at it.

@SmallJoker is your PR merged?

**Comment by SmallJoker** [comment]
@paramat Yes it's merged but as I already said (three posts above): the attached entities can be punched and right-clicked now but the collision handling was not affected by this PR. What can be clicked is the selection box, not the collision box.

**Comment by paramat** [comment]
Thanks but as i wrote, this request is not for collision boxes. So closing as implemented.
@MirceaKitsune do comment here if i'm wrong.
