### ISSUE TITLE
Calling hud_change directly after hud_add on same HUD element does not change it

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2862]
I probably have found a problem in the Lua API of Minetest 0.4.12.

If you call `hud_add`, then shortly after call `hud_change` on the same HUD element, it will not be changed. `hud_change` only seems to work if some time has elapsed between `hud_add` and `hud_change`.

Example input for `luacmd` mod:

```
/lua id = me:hud_add({hud_elem_type="text", text="Original text", number=0xFFFFFF, position={x=0.5, y=0.6}}); me:hud_change(id, "text", "I have changed!")
```

Alternatively, you can use this code in a mod (works only in singleplayer mode):

```
local player = minetest.get_player_by_name("singleplayer")
local id = player:hud_add({hud_elem_type="text", text="Original text", number=0xFFFFFF, position={x=0.5, y=0.6}})
player:hud_change(id, "text", "I have changed!")
```

This code will first add a text HUD element saying “Original text”, then immediately changing (at least it attempts to!) the text to “I have changed!”.

If you run the code, the expected result would be that your screen displays the text “I have changed!”. In my test, however, the text will reliably be “Original text”.

For comparison, here is another test for `luacmd`, this time, I have added a 2 second delay for `hud_change`:

```
/lua id = me:hud_add({hud_elem_type="text", text="Original text", number=0xFFFFFF, position={x=0.5, y=0.6}}); minetest.after(2, function() me:hud_change(id, "text", "I have changed!"))
```

This reliably first shows “Original text”, then it changes to “I have changed!” after 2 seconds.

**Comment by SmallJoker** [comment]
Packets are sometimes received out-of-order, as seen in https://github.com/minetest/minetest/issues/7052#issuecomment-390488861. Network issue.
