### ISSUE TITLE
No way to see server descriptions on Android

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2865]
Perhaps it is trivial, but I think it would be nice if one could see the description, when available, of any new server one joins.

**Comment by nanepiwo** [comment]
I think this should be accessible from the server list, maybe with a "more info" button.

**Comment by paramat** [comment]
Anyone interested in coding this? If not closing in 1 month.

**Comment by Wayward1** [comment]
Closed by https://github.com/minetest/minetest/commit/0e4c467a8248d1bd2cf658096f8476ce07c86c63
