### ISSUE TITLE
Use the function in minetest.register_decoration

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#2867]
Example:
```
minetest.register_decoration({
	deco_type = "function",
	sidelen = 16,
	fill_ratio = 0.03,
	biomes = {"grassland"},
	height = 1,
	deco_func = function(pos)
		default.grow_pine_tree(pos)
	end
})
```
deco_func is tentative.

**Comment by paramat** [comment]
Decoration code is meant to be fast and simple, the problem with using it to run functions is that this would slow down mapgen. It's better to use decoration code to place a mod-defined node and run an ABM on those, to then run your function.
Any other uses for this i haven'y thought of? I can't see good reason to add this.
