### ISSUE TITLE
Text alignment of text HUD element is always left-justified for multi-line text

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2871]
Hi! I think the way how the text HUD element is aligned is pretty weird as soon as you use multiple lines of text (with `\n`).

Here is an example for you to try:

```
player:hud_add({
    hud_elem_type = "text",
    text = "This is an example\ntext with\na\ncouple of\nlines.\n\nThis is the last line.",
    number = 0xFFFFFF,
    position = {x=0.5, y=0.5},
    offset = {x=-0,y=-256},
    direction = 3,
    alignment = {x=0,y=1},
    scale = {x=800,y=600},
})
```

Here I set `alignment.x` to `0`. This means center. _However_, my text is entirely left-justified; it seems that Minetest only moves the entire _text box_ to the center, but does not change the actual text alignment (if you use multiple lines).
Also, `alignment.x` with `1` seems to only move the text box to the right, but the text is not right-justified, but left-justified.

In other words, it is impossible to create a centered or right-justified text HUD element with multiple lines.

I think this needs to change. Changing the `alignment.x` parameter should _also_ affect the text alignment for texts of multiple lines. `alignment.x=0` means “centered text” and `alignment.x=1` should mean right-justified, `alignment.x=-1` should mean left-justified. 
`lua_api.txt` descibed the `alignment` parameter for text simply as “alignment of the text”, so I'd understand it as such.

You might think of this workaround: Simply calling `hud_add` multiple for each line. But this is a bad workaround, because it will break as soon as there is a client who does not use a standard font, a different font size or a different GUI scaling. In this case, the HUD elements would either overlap (if too big) or be too far apart (if too small).

(Version used: 0.4.12)

**Comment by paramat** [comment]
Possible bug?

**Comment by paramat** [comment]
Any core dev interest?

**Comment by SmallJoker** [comment]
This sounds more like bug report than a feature request. Broken alignment for multi line text.

**Comment by SmallJoker** [comment]
`text-align: center` in CSS aligns each line to the center. Text processing programs offer the same "Alignment" configuration options, such as "Left", "Right", "Center", "Justified" and possibly more. It makes sense to have the same behaviour in Minetest if that's possible with the API we've got.

**Comment by Wuzzy2** [comment]
Yes, that's what I meant.
https://en.wikipedia.org/wiki/Typographic_alignment
