### ISSUE TITLE
Minetest attempts to start world named “world” from main menu when no world is selected.

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2872]
Try this in the main menu, singleplayer tab:
If there are no worlds in the world list, but click on “Play” anyways, Minetest seems to attempt to start a world called “world”. It shows a weird error message saying that Minetest has not found the world called “world”. This also happens if you double-click on the world list. (This list never seems to be actually empty, you can select an empty line at the top → maybe another issue with lists in general?).

Fun fact: If you actually have a world named “world” in a different subgame, Minetest actually starts it (along with the other, correct subgame)! :D

**Important:** If you want to reproduce this bug by clicking on “Play”, make sure you have selected the “invisible” entry on the list first.

Minetest should not do this, instead, Minetest should show a message saying something like “No world selected.” or simply doing nothing at all.

Seen in 0.4.12.

**Comment by est31** [comment]
Does it still occur with latest git? @kilbith can you check?

**Comment by kilbith** [comment]
Yep, I can reproduce it.

**Comment by est31** [comment]
c53520aa314960855fc57bf09045c3f977557bb5
