### ISSUE TITLE
Android users can't sprint (missing “Use” key)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2873]
Simply spoken: **Android users are pretty much unable to sprint!**

Multiple users have reported to me that there is no way to use the “Use” button (also known as “Aux1”) on Android.
So I request to add support for the “use” button on Android.

Note that some mods need the use button to work, for example, the Sprint mod by GunshipPenguin, so being able to use this button is needed.

**Comment by nanepiwo** [comment]
It is true that there is no use button, though the hack to enable fast mode kind of fixed this. (If fast is enabled, holding the use button is simulated)

**Comment by Wuzzy2** [comment]
You are entirely missing the point. The use button needs to be directly available on Android.
If the use button is not directly available on Android, this breaks some mods which depend on this button.

**Comment by nanepiwo** [comment]
It does not break mods IIRC since they check if the use button is pressed (enabling fast on android tells the engine that the button is pressed), though it might be confusing if the use button is the fast button (that's how it looks like). Are there enough mods which use this functionality that adding a use button is worth it?

**Comment by Wuzzy2** [comment]
I don't know if there are “enough” mods, my point is that is a bad idea to have Android mashing [Use] and [Fast] together, while on PC, both things are seperate. This can be very confusing/frustrating for mod makers!
And I think adding this functionanity is worth it.

**Comment by nanepiwo** [comment]
I think a separate sneak key would also be nice.

**Comment by sapier** [comment]
well guys there's limited space on android screens we can't show a full keyboard on top of it ;-)
Don't ever expect on android being exactly same keys available as on PC. 

What about adding a "use" key to hiding rare controls bar to be added soon can someone provide a image?

**Comment by paramat** [comment]
Anyone interested in coding this? If not closing in 1 month.
@sapier

**Comment by Wuzzy2** [comment]
Sorry, but having the use button available is **very essential**, it should not be dismissed.

There are mods which *heavily* depend on this key/control being available, for example, it is used for sprinting. This means that Android users are unable to sprint and thus are at a serious disadvantage on some servers.

Either the use key is added or someone suggests a better solution to this.

**Comment by paramat** [comment]
I agree it's a good idea.

**Comment by paramat** [comment]
In fact it seems essential.
Since it is sometimes used for sprint perhaps a new button just above the joystick?
@srifqi

**Comment by paramat** [comment]
Good for sprint, but what if the key is for another action? You would have to walk forward to activate.

**Comment by rubenwardy** [comment]
Dragging the stick past a point needs to enable E, to give a good UX. There can also be a button too.

I personally think that fast should be bound to a new key, say fast, and then the sprint mods updated to use this. Feels better

**Comment by paramat** [comment]
> Dragging the stick past a point needs to enable fast, to give a good UX. There can also be a button too.

Seems good, that also makes fast work with the non-fixed joystick. The extra button could then possibly be on the right or at least in the menu.

**Comment by paramat** [comment]
> I personally think that fast should be bound to a new key, say fast,

Yes, it does bother me that E is shared between fast and an aux key.

**Comment by srifqi** [comment]
Give it options again? I mean, we can just put the "use" button as @paramat suggests and add option to activate using joystick as @rubenwardy suggests.

Also, if an item doesn't have "use" key callback, it doesn't have any effect when pressing "use" key, right? For example, I have an item which can be activated by pressing "use" key. If I don't want to use it, simply select another item which doesn't have "use" key callback, e.g. torch, in the hotbar. Simple.

Still, I agree with @rubenwardy that "sprint" should be bound to a new key.

**Comment by srifqi** [comment]
I just tried to add "use" button (as @paramat suggests) and joystick activation past main circle (as @rubenwardy suggests). (See srifqi/minetest@68b15a1c68dc96173972386cc6c15364af582cb9.)

[Video (1): paramat's suggestion](https://youtu.be/VZw4e2oD0_Q)
[Video (2): rubenwardy's suggestion](https://youtu.be/KM-RAOfryB4)

APK (armeabi-v7a, srifqi/minetest@68b15a1c68dc96173972386cc6c15364af582cb9, minetest_game):
https://drive.google.com/open?id=17ALHooN4tPSpKDk2hYEWjbSkP7rDoKwh

**Comment by paramat** [comment]
Thanks for that. Dragging the joystick further forward is good and works with the non-fixed joystick, but we will also need a separate 'use' button as discussed above https://github.com/minetest/minetest/issues/2873#issuecomment-380568673
Something to consider: How will sprint control work in fixed joystick mode? Will it be a tappable area above the joystick or require pressing forward and then dragging upwards? Either seems ok to me.

**Comment by srifqi** [comment]
> Dragging the joystick further forward is good and works with the non-fixed joystick, but we will also need a separate 'use' button as discussed above.

I haven't be able to use "use" button while using joystick to control "use". Any suggestion?

> How will sprint control work in fixed joystick mode?

For now, it needs to be dragged after pressing joystick.

**Comment by paramat** [comment]
> I haven't be able to use "use" button while using joystick to control "use".

Weird, i would have thought you could map both controls to the same result.

> For now, it needs to be dragged after pressing joystick.

Fine.

**Comment by orwell96** [comment]
Indeed, I use the 'aux1' aka 'use' key inside advtrains, for sounding the horn.
However, making this a separate key is certainly useful.
What do you think about reserving even more than 1 auxiliary key, such as 2 or 3? Mods (or rather subgames) could use them for special functions such as laying down(useful in pvp with guns) or toggling some sort of custom GUI. This would have the advantage of not having many different actions bound to the same key, if multiple mods require the auxiliary key at the same time.

**Comment by paramat** [comment]
Could this be worked on soon? It would be good for 5.0.0.

**Comment by paramat** [comment]
> Dragging the stick past a point needs to enable fast, to give a good UX. There can also be a button too.

An issue is that it would be very easy to activate 'use' by accident using the joystick, when 'use' is controlling something other than 'fast'. This needs a solution.

**Comment by srifqi** [comment]
So, which way will we fix this issue?

**Comment by paramat** [comment]
@rubenwardy what do you suggest? We could get around this issue by adding to MT a dedicated key for 'fast' (which i support doing), activating that when dragging the joystick far forward, and then also adding a 'use' key to Android. But, i'm not volunteering to do any of this.

**Comment by Wuzzy2** [comment]
What do you mean, “a dedicated key for ‘fast’“? What will it do?

**Comment by rubenwardy** [comment]
I agree with adding a dedicated fast key

**Comment by paramat** [comment]
Anyone inspired to work on adding a new key binding to separate 'fast' from 'use'? And any more opinions on that?

This issue needs sorting out before 5.0.0 so perhaps simply add a 'use' key on the right side of the screen for now.

**Comment by srifqi** [comment]
@paramat Will https://github.com/srifqi/minetest/commit/68b15a1c68dc96173972386cc6c15364af582cb9 (just button, without moving past joystick) do?

**Comment by paramat** [comment]
If that's this video https://www.youtube.com/watch?v=VZw4e2oD0_Q yes that's fine for me. However it needs a better button texture for 'use', and perhaps the 'use' and 'zoom' buttons should both be placed on the right edge of the screen? With 'zoom' above 'use' since it is used less?

But let's get some more core dev opinions on this before you work on it.

**Comment by paramat** [comment]
https://github.com/srifqi/minetest/commit/68b15a1c68dc96173972386cc6c15364af582cb9 adds a 'use' button and adds a setting (default 'false') for the joystick to activate 'use'. Seems ideal to me.

**Comment by srifqi** [comment]
I'll create PR ASAP.
