### ISSUE TITLE
Please document recommended screenshot.png size in lua_api.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2874]
`lua_api.txt` mentions the purpose of `screenshot.png` only very briefly. I think, at the very least, it should document the recommended image size and/or its aspect ratio.
Many mods with `screenshot.png` have it distorted in the main menu. :-(

Besides: Can you developers please also ensure / promise the aspect ratio of the screenshot won't change in future releases? Having distorted screenshots is ugly. ;-)

**Comment by ExcaliburZero** [comment]
Yeah this has something that has confused me a bit. From measuring a screenshot of the mod tab, the screenshots appear to be displayed with an aspect ratio of 3:2 (ex: 300x200px), however I have seen it noted elsewhere, such as in Rubenwardy's [Minetest Modding Book](http://rubenwardy.com/minetest_modding_book/chapters/releasing.html), as being 4:3 (ex: 200x150px).

**Comment by ExcaliburZero** [comment]
I took a quick look at the code that displays the screenshot in the Mods tab of the Minetest main menu, and from my understanding it looks like the correct aspect ration is 3:2.

Here is the code that is used to display the image in the Mods tab: (https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/builtin/mainmenu/tab_mods.lua#L64)

~~~
"image[5.5,0;3,2;" .. core.formspec_escape(modscreenshot) .. "]"
~~~

**Comment by ExcaliburZero** [comment]
I took a look through the other uses of screenshot images and I think I found one inconsistency in their use.

I looked through the use of the screenshot image that is supposed to be displayed by the Store, and that does seem to be consistent with the 3:2 aspect ratio. (https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/builtin/mainmenu/store.lua#L393)

~~~
return "image[0,".. ypos .. ";3,2;" ..
~~~

However, when I checked the use of the screenshot images in the Texture Packs tab, it oddly used a ratio of 4:3.7 rather than the 3:2 ratio used in other places of Minetest. (https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/builtin/mainmenu/tab_texturepacks.lua#L85)

~~~
"image[0.25,0.25;4.0,3.7;"..core.formspec_escape(screenfile or no_screenshot).."]"..
~~~

**Comment by ExcaliburZero** [comment]
Here is a screenshot of a mod entry, as you can see the aspect ratio of the displayed image of the screenshot of the mod is 3:2

![screenshot from 2015-07-14 13 32 00](https://cloud.githubusercontent.com/assets/4276196/8680162/7437f99e-2a2d-11e5-90b4-fee217cbd7e7.png)

Here is a screenshot of a texture pack entry, as you can see the aspect ratio of the displayed image of the screenshot of the texture pack is 4:3.7

![screenshot from 2015-07-14 13 33 00](https://cloud.githubusercontent.com/assets/4276196/8680192/ab23b45c-2a2d-11e5-83e8-fee2243414a2.png)

**Comment by srifqi** [comment]
So, for the `screenshot.png`:
- In Mods tab is `3:2`, and
- In Texture Packs tab is `4:3.7` (?)

**Comment by 0-afflatus** [comment]
Could we not just standardise it to 3:2 all round?
That would be much less confusing.

**Comment by ExcaliburZero** [comment]
Having it standardised to 3:2 would make a good bit more sense.

**Comment by paramat** [comment]
Yes 3:2 everywhere seems good.

**Comment by Wuzzy2** [comment]
I don't care so much about the aspect ratio. But we should agree on one and also decide to stick with it as long as possible for future versions and only change it if there is really no other way. Mod makers should be able to rely on the numbers.

**Comment by srifqi** [comment]
So, in `tab_texturepacks.lua`, line 97, should be changed from:
```lua
"image[0.25,0.25;4.0,3.7;"..core.formspec_escape(screenfile or no_screenshot).."]"..
```
into:
```lua
"image[0.25,0.25;4.0,2.67;"..core.formspec_escape(screenfile or no_screenshot).."]"..
```
to make it `3:2` aspect ratio?

**Comment by paramat** [comment]
Mod screenshot has limited vertical space so 3:2 is useful to give it some extra area.

**Comment by rubenwardy** [comment]
Updated Minetest Modding Book: http://rubenwardy.com/minetest_modding_book/chapters/releasing.html#screenshotpng

I originally thought it was 200x150 as that's the size of  textures/base/pack/no_screenshot.png

**Comment by Wuzzy2** [comment]
Oops, so that means `no_screenshot.png` should be fixed as well.

**Comment by Wuzzy2** [comment]
Okay, the aspect ratio of 3:2 with a minimum size of 300×200 seems to be semi-official now:

> Screenshot should be 3:2 with a minimum size of 300x200px.

**Comment by paramat** [comment]
Please can you makea PR then?

**Comment by Wuzzy2** [comment]
Okay, look here: https://github.com/minetest/minetest/pull/4355

**Comment by paramat** [comment]
#4355 merged.
