### ISSUE TITLE
player:setpos and player:moveto do not really teleport player when player is sneaking

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#2876]
If you use `player:setpos(some_position)` or `player:moveto(some_position)` on the player object `player`, the player is not really set to `some_position` under these conditions:

* The player is standing on any solid node AND
* The player is currently sneaking (holding down the sneak key)

The player won't be teleported to the destination, instead the player is just moved to the edge of the node on which the player is currently standing, but interestingly, this is always towards the direction of the destination.

One way to quickly test this is by using the Mirror of Returning (https://forum.minetest.net/viewtopic.php?f=11&t=11224) or Point Teleporter (https://forum.minetest.net/viewtopic.php?f=11&t=9629).
Both mods directly call `setpos` when you use the item.

I think this is very unexpected for modders, it also seems to me the modder has zero chance to somehow “overwrite” this behaviour or to ignore the sneaking.

Tested in: 0.4.12

**Comment by HybridDog** [comment]
Does the problem exist for player:moveto(pos), too?

**Comment by PilzAdam** [comment]
This probably because we keep a reference to the node the player is standing on in the player object. It may be fixable by setting `m_sneak_node_exists` to false when teleporting.

**Comment by Wuzzy2** [comment]
> Does the problem happen to player:moveto(pos), too?

Yes.

**Comment by paramat** [comment]
3535 is merged, hopefully this is fixed.

**Comment by Ombridride** [comment]
Thank you for this merge.
