### ISSUE TITLE
player:get_look_yaw and player:set_look_yaw not consistent.

### ISSUE THREAD

**Issue by beyondlimits** [minetest/minetest#2879]
`player:get_look_yaw()` produces different value than was used to `player:set_look_yaw()`.

Proof: doing `player:set_look_yaw(player:get_look_yaw())` causes player to rotate left 90 degrees instead of looking at the same point.

**Comment by TeTpaAka** [comment]
Duplicate of #2658

**Comment by est31** [comment]
@TeTpaAka is right, dupe of #2658.
