### ISSUE TITLE
Prioritize shaped recipes over shapeless ones.

### ISSUE THREAD

**Issue by beyondlimits** [minetest/minetest#2881]
Currently shapeless recipes may get in conflict with shaped, overriding them. Since shaped recipes have narrower scope, prioritizing them over shapeless could bring more flexibility to the API and allow modders to write less code to avoid conflicts.

Example: https://github.com/Calinou/moreblocks/blob/master/stairsplus/slabs.lua#L69 cannot be declared shapeless, because it may conflict with https://github.com/Calinou/moreblocks/blob/master/stairsplus/stairs.lua#L206.

**Comment by nanepiwo** [comment]
+1

**Comment by beyondlimits** [comment]
Bump! Anyone here?

**Comment by beyondlimits** [comment]
Nah, closing just to get rid of dangling issue.
