### ISSUE TITLE
Support Unicode in tooltip names

### ISSUE THREAD

**Issue by bluebear94** [minetest/minetest#2883]
Currently, tooltip names and chat messages specified by mods appear in ANSI. This can be resolved by reading the `description` field in UTF-8. As backward compatibility is important, a new field, `use_unicode` will be specified.

**Comment by est31** [comment]
apart from the fact they dont support localisation at all.

**Comment by est31** [comment]
can you check whether #2891 fixes this? This does a direct switch, we haven't defined before whether we want ANSI or some other method.

**Comment by bluebear94** [comment]
I'm [having trouble building](http://pastebin.com/0LXcAqcT) on Windows 7 / MinGW 4.7.2.

**Comment by bluebear94** [comment]
While I ponder on how to get Irrlicht to build on my machine, try inspecting the tooltips of the items added by [this mod](https://github.com/bluebear94/kawerin-mod).

**Comment by est31** [comment]
Closing this, until its confirmed to still exist in recent versions of minetest.
