### ISSUE TITLE
Mislead with spawn_by in decoration registering

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2888]
I'm not sure if it's the intented behavior but the positioning of the decoration with `spawn_by` is contradictory with the [documentation] (https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3333-3334).

The node specified with `spawn_by` is considered as the neighbor of the node specified in `place_on`. 
The node specified in `spawn_by` should be the neighbor next to the decoration itself, respectively to the documentation.

This makes a correct placing harder or even impossible, really.

##### Example in practice #####

```
minetest.register_decoration({
	deco_type = "simple",
	place_on = "default:dirt_with_grass",
	spawn_by = "default:tree",
	num_spawn_by = 1,
	sidelen = 16,
	fill_ratio = 0.03,
	y_min = -31000,
	y_max = 31000,
	decoration = "default:mushroom_red"
})
```

*Currently results as...*

![screenshot_20150706_121451](https://cloud.githubusercontent.com/assets/7883281/8520561/91bba55e-23db-11e5-8f19-a9ca72472cb7.png)

The decoration is spawned if : 
- is on the `dirt_with_grass`
- the `dirt_with_grass` is next to the `tree` (-> the subject of this issue).

*What it should be...*

![screenshot_20150706_121516](https://cloud.githubusercontent.com/assets/7883281/8520587/ddfd3a86-23db-11e5-9c96-26634ed1bd55.png)

The decoration is spawned if : 
- is on the `dirt_with_grass`
- the **decoration** is next to the `tree` (-> faithful behavior).

**Comment by paramat** [comment]
Will consider.

**Comment by paramat** [comment]
This seems intentional, as 'spawn by' seems to be have been initially added for checking water is nearby and is saturating the dirt below the decoration, for papyrus for example. More generally you are correct though. Problem is if it is changed then plants checking for water will not work.
The documentation seems to be correct in a 2D 'seen from above' sense.
So for the moment i think no change is best.

**Comment by kilbith** [comment]
The documentation is explicit enough I think...

```
spawn_by = "default:water",
    --  ^ Node that the decoration only spawns next to, in a 1-node square radius.
```

As demonstrated factually in my example, it doesn't happens.

Another example : 

```
minetest.register_decoration({
    deco_type = "simple",
    place_on = "default:dirt_with_grass",
    spawn_by = "default:grass_5",
    num_spawn_by = 1,
    sidelen = 16,
    fill_ratio = 0.03,
    y_min = -31000,
    y_max = 31000,
    decoration = "vessels:glass_bottle"
})
```

![screenshot_1792187906](https://cloud.githubusercontent.com/assets/7883281/8559677/f460abb6-250f-11e5-8130-a2d85ef90dbc.png)

**Comment by paramat** [comment]
I agree, changed my mind, i think i will make the search volume 1 node higher, so that all nodes next to both the decoration and the node the decoration is placed on, are checked. This won't hit performance much.

**Comment by kwolekr** [comment]
Why not just add a flag to specify which behavior is wanted?

**Comment by RobertZenz** [comment]
Or add another parameter, like `spawn_next_to`.

**Comment by paramat** [comment]
I feel 'spawn by' should be a 3D search, not just restricted to the same level. Having a 2 node high search volume combines both use cases.
