### ISSUE TITLE
Useless arithmetic operations on player position in a save file

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#2896]
I think it's safe ti assume that everyone knows about player save files located at ```$minetest_dir/worlds/$name_of_your_world/players```.

Currently the ```position``` parameter stored in a multiplied by 10 form.
I.e. instead of ```position = (95.77,16.5,-357.73)``` it reads ```position = (957.68,165,-3577.25)```.

The engine works just fine in dividing those numbers by 10 before spawning a player on_join, but it is still a weird kind of behaviour.

**Comment by HybridDog** [comment]
idk, vec3 is a part of irrlichttypes.h, isn't it?

**Comment by 4aiman** [comment]
idk either ))

But when I'd like to go to 65000... What will be saved/loaded?
If that would be safe - I don't have anything against current behaviour.
Just wanna it be documented, I guess.

**Comment by rubenwardy** [comment]
At a guess I'd say it's due to `BS`. BS is a multiplier that turns node coordinates into Irrlicht coordinates.

It does however make more sense to store the player positions as node positions than Irrlicht positions. (Irrlicht positions should only be used internally, and not be exposed at all)

**Comment by 4aiman** [comment]
I've thought is may be due to a recent ``` BS==1``` change, but I thought that thing has smth to do with ```basic speed``` XD

**Comment by paramat** [comment]
:-1: It uses the x10 version for good reason as this is the co-ord system often used in the engine. No point changing it.
