### ISSUE TITLE
Allow doing something before the core mapgen and minetest.registered_on_generates are executed

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#2899]
For the fractures game, l would like to be able to switch to singlenode mapgen mode if the chunk is on the specific side of the gap. As far as l know it isn't possible yet before the core mapgen starts.

**Comment by paramat** [comment]
Not possible. Mapgen type is for an entire world, there is little need to mix mapgens within a single world.

**Comment by PilzAdam** [comment]
@paramat it is very useful for different layers (think of realms like the nether). In this case mods may want to use the default mapgen for the surface area and everything should be empty so they can fill it themselves.

**Comment by paramat** [comment]
I closed this too hastily, an option to disable core mapgen within a particular chunk could be useful, any more support for this?
