### ISSUE TITLE
minetest.conf.example: comments not clear enough

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2900]
Some comments in the example file for minetest.conf could be better explained. 

See [this post](https://forum.minetest.net/viewtopic.php?p=184080#p184080):
```
#    This is a trade-off between sqlite transaction overhead and
#    memory consumption (4096=100MB, as a rule of thumb)
#max_clearobjects_extra_loaded_blocks = 4096
```
 so if i have 4gb ram i must set 163 840 (4096*40)??? or
```
#    Maximum number of forceloaded blocks
#max_forceloaded_blocks = 16
```
what is forceloaded blocks?

I think it would help if the command would have an example what forcibly loads blocks. E.g. does a  forceload anchor block by ruben uses this? And how does it affect this mod if there are more anchors than max blocks allowed?

**Comment by est31** [comment]
I think the wiki is a better place to have extensive documentation -- feel free to edit it.

**Comment by C1ffisme** [comment]
The comments should probably follow these rules: http://dev.minetest.net/Lua_code_style_guidelines#Comments

**Comment by rubenwardy** [comment]
No, @c1ffisme: The comments discussed in the code style guidelines are **code** comments and are aimed at developers. The comments in the minetest.conf are **configuration** comments and are aimed at end users.

**Comment by asl97** [comment]
@rubenwardy some of it should apply, like the `Don't write comments that describe things that are obvious from the code.` (replace code with setting name)

people should be able to tell this set the `Maximum number of forceloaded blocks` without the comment, what some people can't tell is what is `forceloaded block`
```
#Maximum number of forceloaded blocks
#max_forceloaded_blocks = 16
```

something like `Maximum number of area allow to keep active/running` would explain much more.

**Comment by C1ffisme** [comment]
Mainly what I was pointing at.

**Comment by rubenwardy** [comment]
My point is that configuration files don't follow the code style rules, but they follow common sense.

**Comment by lightonflux** [comment]
I am closing this as most things are said. And the issue is not specific enough to be closed by a single commit. So if nobody has to add something to the general discussion…

**Comment by PilzAdam** [comment]
@lightonflux #3271 introduces a convention of longer comments for each setting. When it is merged then future pull requests are free to expand and improve the descriptions.
