### ISSUE TITLE
Graphical glitch (hand) - fsaa 

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#2902]
Look at the stone above the hand. It happens when the fsaa option is set to 2 or 4. 

![bildschirmfoto von 2015-07-11 12 21 47](https://cloud.githubusercontent.com/assets/1377943/8633413/89509272-27c7-11e5-976d-1b143e205282.png)

It looks a bit like the front of the hand was rendered, but then messed up with mode lines. 

My system has a Intel HD4000 and uses the xserver-xorg-video-intel driver (version: 2:2.21.15-2+b2 from Debian Jessie).

**Comment by Calinou** [comment]
It is an engine bug, it will happen with all graphics drivers.

**Comment by kwolekr** [comment]
Hrmm, I'm not sure how we can solve this.  At its root, this is an internal Irrlicht problem.  I suppose we could experiment with different hand models and see precisely what it is about this texture or whatever is exposing this behavior.

**Comment by kahrl** [comment]
Try this: 
```
diff --git a/src/wieldmesh.cpp b/src/wieldmesh.cpp
index 036b25a..b54f278 100644
--- a/src/wieldmesh.cpp
+++ b/src/wieldmesh.cpp
@@ -282,6 +282,8 @@ void WieldMeshSceneNode::setExtruded(const std::string &imagename,
 	// Customize material
 	video::SMaterial &material = m_meshnode->getMaterial(0);
 	material.setTexture(0, tsrc->getTextureForMesh(imagename));
+	material.TextureLayer[0].TextureWrapU = video::ETC_CLAMP_TO_EDGE;
+	material.TextureLayer[0].TextureWrapV = video::ETC_CLAMP_TO_EDGE;
 	material.MaterialType = m_material_type;
 	material.setFlag(video::EMF_BACK_FACE_CULLING, true);
 	// Enable bi/trilinear filtering only for high resolution textures
```

**Comment by RealBadAngel** [comment]
above will be merged into upcoming wielded fixes

**Comment by est31** [comment]
Added to milestone because we merged in-menu ability to turn on fsaa.

**Comment by RealBadAngel** [comment]
fixed in above PR
