### ISSUE TITLE
Players occasionally are not moved to spawn after respawning

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#2903]
1. Player dies.
2. Player respawns.
3. Player is expected to move back to spawn, but they occasionally don't.

Very annoying on Hunger Games servers. Note that this isn't related to anti-cheat -- it happens even on servers where it is disabled. No particular message appears in the log.

**Comment by C1ffisme** [comment]
I've had this on 0GB's server before. A very long time ago. Quite annoying. Do you still have hearts when you respawn or do they not appear?

**Comment by ExcaliburZero** [comment]
I've had this issue happen occasionally on the Linux Gaming server. I find it usually happens when I am moving fast and die from fall damage.

@C1ffisme 
If I remember correctly, the player's hearts are refilled when they "respawn". Same as if they had actually died and been returned to the spawn point.

**Comment by cheapie** [comment]
This seems to only happen if I'm moving when I die.

**Comment by neoascetic** [comment]
Yeah, it looks like "cheating protection" resets player's position because, well, he moves too fast

**Comment by paramat** [comment]
But:

> Note that this isn't related to anti-cheat -- it happens even on servers where it is disabled.

However, anyone still experiencing this?

**Comment by rubenwardy** [comment]
I haven't seen this happen in a while. Will close in a month if no more reports

**Comment by paramat** [comment]
Can be closed in 10 days, 1 month after my question.

**Comment by Calinou** [comment]
I'll close this for now (until we get reports that the bug still occurs, if any).
