### ISSUE TITLE
Player slept on the bed goes every direction, and missing sleep animation poses

### ISSUE THREAD

**Issue by GrandChaos9000** [minetest/minetest#2906]
This is the first time I posted my issue in this repository, but...

...there are two problems of single player in the latest unstable version (0.4.12-dev-515e702-dirty).
- During at night, the player went to sleep on the bed while jumping/walking goes away from every direction.
- In third-person view, the sleeping player animation pose was missing.

Edit: Updated but the glitch was present.

**Comment by C1ffisme** [comment]
Explain "while jumping/walking goes away from every direction." more clearly. I can't understand it when verbs go away from every direction.

**Comment by GrandChaos9000** [comment]
@C1ffisme You know that is a glitch from the first paragraph, but I have proof screenshots right here.
![](https://cloud.githubusercontent.com/assets/13311548/8657847/b9802434-29a8-11e5-8e82-99543eacbb8a.png)
![](https://cloud.githubusercontent.com/assets/13311548/8657862/cc0ef486-29a8-11e5-9617-fcca6ddd6a62.png)

**Comment by C1ffisme** [comment]
Okay, I heard nothing about the hand in the original description. I understand now that I have some screenshots to clarify.

**Comment by DS-Minetest** [comment]
is this really a bug of the minetest engine?

**Comment by paramat** [comment]
Can't understand any of this, if there's a bug it will be reopened by someone else.
