### ISSUE TITLE
Shift-Click in Minetest Game replicates items

### ISSUE THREAD

**Issue by yamanq** [minetest/minetest#2915]
To reproduce this behavior:
1. Log in to a new game (Minetest Game) in creative.
2. Put some items into your inventory.
3. Shift-Click on a random item in the creative menu.
4. Your entire inventory is now filled with clones of your original inventory (this includes stacked items).

Example:

Before Shift-Click:
![screenshot_20150716_024543](https://cloud.githubusercontent.com/assets/8166212/8717000/d401b332-2b64-11e5-975a-f5caffc4ca1a.png)

After Shift-Click:
![screenshot_20150716_024548](https://cloud.githubusercontent.com/assets/8166212/8717002/d7305130-2b64-11e5-9dc2-4d3969350f36.png)

**Comment by est31** [comment]
Confirmed.

**Comment by est31** [comment]
7bbb9b066a8cc079512ddd3e6b32475309f49fca
