### ISSUE TITLE
Use Z-order curves? Or split up the coordinates?

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2916]
While reading through the [docs](https://bitbucket.org/s_l_teichmann/mtsatellite/src/default/SETUP.md) for MTSatellite by @s-l-teichmann, I have seen it uses its own "interleaved" format. It seems Z-ordered trees might be very useful if you don't have an SSD, because mapblocks close to each other have highly different ids, this is the current [getBlockAsInteger](https://github.com/minetest/minetest/blob/990a96578f20244626b6b9f67f8e79a7e2e614ea/src/database.cpp#L51) implementation. There is however another PR by @ShadowNinja that wants to split up the coordinate data and let the actual database do the work. What should be used in the future?
Also, @s-l-teichmann does your "interleaved" format have additional changes?

**Comment by Novatux** [comment]
Also, there is another thing that needs to be done if mapblock ids are changed: make sure there isn't some kind of hard limit with map size like with the current format, so that map size can be extended without changing database format again (ShadowNinja's format seems to allow this, unlike the current one).

**Comment by s-l-teichmann** [comment]
@est31 The "interleaved" format of MTSatellite only changes the block keys to be bitwise interleaved x, y and z. So bits zzzzzzzzzzzzyyyyyyyyyyyyxxxxxxxxxxxxx become zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx (if i've counted to 12 correctly).

Currently MT  uses only 12 bits per component. To use a 64bit integer more effectively using 21 bits would be a valid option. This would increase the world size to 16x2^21m ~ 33554km edge length.

**Comment by est31** [comment]
Thanks for explaining. Interleaving sounds indeed like something we should do.
About extending the world, thats another issue. The map backend makes no problems I think, just like normal active objects comaratively easy to increase bit numbers, the problem is more with what we use at other parts. For example, minetest.hash_node_position returns (as our doc guarantees) an 48 bit integer, and on IEEE 754 platforms we must not go beyond 2^53. It will have to be made to return a string instead,

**Comment by est31** [comment]
@s-l-teichmann can you point us to some information which describes how databases align their data on disk? Have you noted any speed benefit from using those z-order curves?
