### ISSUE TITLE
Invisible caves floating in the air

### ISSUE THREAD

**Issue by RealBadAngel** [minetest/minetest#2925]
As in title, mapgen is carving caves in the air, causing lighting glitches and wasting mapgen time.
Since hmmm is not able to fix that for years, maybe some other dev will fix this.

**Comment by paramat** [comment]
Which mapgens? A while ago i fixed the shadow bugs in mgv6 by adding a heightmap and stopping large caves from generating above it:
https://github.com/minetest/minetest/issues/1190
https://github.com/minetest/minetest/pull/2410
https://github.com/minetest/minetest/commit/773aa8c57b70dd85273cb61286f8be577b4ca3aa
Mgv5 and mgv7 also have heightmaps and large caves are not generated above these.

**Comment by est31** [comment]
While caves cutting into trees is ugly, I don't think this is a blocker.

**Comment by paramat** [comment]
The generation of mgv5/mgv7 3D noise tunnels is very lightweight, as the perlinmap has been generated beforehand, the code needed to keep these below the heightmap may well eliminate any gain. There is also a check for air so air is not replaced by tunnel air.

However now mgv6 has a heightmap, it may be a good idea to also keep small caves below it, anyone know why only large caves are kept below the heightmap? I can't think of a reason yet, so i'll probably do this to save processing.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/pull/2932

**Comment by paramat** [comment]
4046f3e302a3394bf376caf543cb643e1562bc5e

**Comment by paramat** [comment]
To explain, i didn't think this was high priority because the small caves were not actually creating lighting glitches, and the extra processing was not much.

**Comment by paramat** [comment]
> Perhaps this be closed now?

By that i meant this can be closed now but thought it more polite to let RBA close it if satisfied. It's been a while so now closing this.
