### ISSUE TITLE
Clean up SAO attachment interface

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#2927]
As a developer, I would like a clean and efficient interface for managing SAO attachments so that I can more easily write code which uses attachments and better understand existing code that uses attachments.
# Acceptance Criteria:

At the very least,
1). update of parent/child attachment status when deleting an object should be automated.
2). The special attachment object ID of 0 should use a constant instead for semantic information
3). Proper width datatypes should be used for object IDs

**Comment by rubenwardy** [comment]
I think this has been partially fixed by @SmallJoker
