### ISSUE TITLE
Add documentation on how to create texture packs

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#2928]
As a modder, I want an official resource on how to create texture packs, so that I can have easy and reliable access to accurate information on the topic.
# Acceptance Criteria:

There is a new file in doc/ which explains the process of creating a texture pack, as well as information about all file paths, formats, and conventions involved

**Comment by C1ffisme** [comment]
That sounds like a wonderful idea!

Do you want to write it or do you want somebody else to?

**Comment by ExcaliburZero** [comment]
This sounds like a good idea. There really isn't enough documentation on texture packs right now.

Also, whoever writes this should make sure to take into account the recent change of "info.txt" to "description.txt" in 5b9c8dfbd26851268ae2cdaecafb255cc57d05cd .

**Comment by RealBadAngel** [comment]
i can write part on creating normal maps and heightmaps - on bumpmapping and relief mapping

**Comment by est31** [comment]
@RealBadAngel it needs to be documented yes, but I think it should be documented where general textures are described.

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/blob/master/doc/texture_packs.txt
