### ISSUE TITLE
Clean up particle spawner Lua interface

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#2929]
As a developer, I want the C++ binding for the Particle Spawner's Lua interface (src/script/lua_api/l_particles.cpp) to get cleaned up so it is easier to read and modify the code, and to verify all behavior is correct.

#Acceptance Criteria:
get<type>field() and/or get<type>field_default() are used instead of iterating through the parameter table and handling the field when a key name matches.

**Comment by est31** [comment]
e47f390e0d37d7906bbbe6a082cc69e10235a3ba
