### ISSUE TITLE
Allow to define shaders, just like textures, for nodes and maybe even globally.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#2937]
Currently we can "only" change the appearance of a node by setting a mesh, nodebox, texture and if it should be waving or not. A very interesting idea to explore would be to allow to register shaders on nodes just like textures.

Obviously, the main benefit would be to allow modders to create, define and use their own shaders. Which grants a lot more freedom when it comes to using the engine. A bonus would be if we would also be able to register shaders for the whole scene.

A main usecase would be to change the appearance of water or lava, or allow other different looking liquids. Or a shader for the skybox would also be interesting.

I'm unaware of the current implementation within the engine in how shaders are used, so I do not know how much work this would require or if this would be at all possible with the current implementation.

**Comment by kilbith** [comment]
That'd be fantastic. @RealBadAngel Your thoughts ?

**Comment by est31** [comment]
If we do things like this, we should put validations in place IMO, like the WebGL standard [requires](https://www.khronos.org/registry/webgl/specs/1.0/#4). An implementation can be found [here](https://dxr.mozilla.org/mozilla-central/source/dom/canvas/WebGLShader.cpp).

**Comment by C1ffisme** [comment]
Sounds wonderful! Especially if you could create a mod with colored grass...

**Comment by RealBadAngel** [comment]
Its not possible to use more than one shader per each material.
So if you would like to assingn your new shader for grass for example, you wont have all the other effects already coded for that kind of node: bumpmapping, normal map generation, relief mapping, fog, lighting.
To get new effect for a node you simply have to modify existing shader.
From that theres no exception - its how the engine (irrlicht) works.

Lava and water shaders are already done, you can find some vids on that on yt, i will merge them one day.

Multiple shaders on the other hand will be aviable for already rendered world - postprocessing ones.
Like lens flares, cartoon shader, etc.

**Comment by PilzAdam** [comment]
@RealBadAngel how about defining only parts of the shaders? Maybe a function that is called before (or after) the other effects are applied? Mods would supply only this function then, and not the whole shader.

**Comment by RealBadAngel** [comment]
@PilzAdam thats possible. shaders are compiled runtime (on startup). i can insert there a piece supplied by modder the same way im doing it already with headers and whole shaders body
some set of rules should be made ofc, but technically, yes i can do that

**Comment by paramat** [comment]
See #3616

**Comment by paramat** [comment]
The original request is not possible, and author has left MT. However:

>  how about defining only parts of the shaders? Maybe a function that is called before (or after) the other effects are applied? Mods would supply only this function then, and not the whole shader.

> thats possible. shaders are compiled runtime (on startup). i can insert there a piece supplied by modder the same way im doing it already with headers and whole shaders body
some set of rules should be made ofc, but technically, yes i can do that

Anyone interested in working on this suggestion? If not closing in 1 month.

**Comment by paramat** [comment]
Any core dev interest?

**Comment by paramat** [comment]
Closing due to age of request, lack of support and difficulty. We also have no shader expert.
