### ISSUE TITLE
Animated textures are not globally synced.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#2938]
Animated textures are not globally synced, which means that if you have a large area of animated nodes, the textures will be in different states of the animation.

Attached is the screenshot of a large body of water, you can clearly see that the animated textures are at different frames.

![screenshot_20150720_203904](https://cloud.githubusercontent.com/assets/611377/8783992/b2ee8cba-2f1f-11e5-8d33-f2a37e1c25c5.png)

**Comment by PilzAdam** [comment]
`desynchronize_mapblock_texture_animation` in minetest.conf

**Comment by RobertZenz** [comment]
There's a setting for that?! I really need to read the `minetest.conf.example` some day. Thanks, that works.

With that option set to `false`, I'm still seeing out of sync behavior if I'm further away from the blocks or if the blocks are at the edge of the screen. Is that expected (for example update of each block or so)?

**Comment by est31** [comment]
@RobertZenz perhaps ypu are experiencing #1404? The dupe #2780 has some more screenshots.

**Comment by RobertZenz** [comment]
No, I re-tested in more shallow waters and the water does not become opaque. It looks like that blocks that are far away get out of sync slightly.

![screenshot_20150721_183554](https://cloud.githubusercontent.com/assets/611377/8806538/69b03a7c-2fd7-11e5-8360-b38cd2fad761.png)
![screenshot_20150721_183555](https://cloud.githubusercontent.com/assets/611377/8806539/69b11532-2fd7-11e5-9e0d-fe54739b5610.png)

**Comment by rubenwardy** [comment]
Doesn't seem like a bug to me
