### ISSUE TITLE
Disable profiler code by default, enable it with a compile-time option

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#2939]
For increasing game performance, profiler should not be built by default. Perhaps `-DENABLE_PROFILER=1` would help.

**Comment by nerzhul** [comment]
:+1: agreed.
Here is an example commit to remove it (warn it remove a little bit more):

https://github.com/nerzhul/minetest/commit/0de7dbf9b4d2d9d07e9bf5ba9a81ad9d88cbdcf9

**Comment by est31** [comment]
The default for that option should be on for debug builds, and off for release builds.

**Comment by nerzhul** [comment]
:+1: est31

**Comment by Zeno-** [comment]
Is this really going to make a performance difference?

**Comment by nerzhul** [comment]
@Zeno- it's a minimal gain, and profiler shouldn't be enabled in production releases, debugging code shouldn't have to be present in production

**Comment by paramat** [comment]
@nerzhul Done in #2940 ?

**Comment by paramat** [comment]
Anyone interested in coding this sometime? If not closing in 1 month.

**Comment by nerzhul** [comment]
let this open

**Comment by erlehmann** [comment]
> profiler shouldn't be enabled in production releases, debugging code shouldn't have to be present in production

@nerzhul can you guarantee that this has no negative effects for mod developers?
