### ISSUE TITLE
Serialization error

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#2941]
With `minetest_game`, and entities around... Happens since recently.

```
ERROR[main]: Client::handleCommand_ActiveObjectMessages: caught SerializationError: deSerializeString: couldn't read all chars
```

Potential cause in : https://github.com/minetest/minetest/commit/6f07f79c2f36b007b4c0385b7df2fc4612af7aba

I'm not the only one to experience that error : https://github.com/Ombridride/minetest-minetestforfun-server/issues/144

**Comment by est31** [comment]
@kilbith which commit do you run?
@kwolekr ping

**Comment by kilbith** [comment]
@est31 Always the latest in-time.

**Comment by kwolekr** [comment]
This is a good thing.  It's catching the error that would have otherwise gotten ignored.

**Comment by kilbith** [comment]
Previously it was throwing something like : `\00\0A ...` filing the entire screen.

Should I close that issue ?

**Comment by kwolekr** [comment]
Yes, and link that issue here too.  This one should take over for the corrupted AOM bug that has been around for quite a while now.

**Comment by paramat** [comment]
Should this have been closed @kilbith ? Sounds like kwolekr meant close the other issue not this one?

**Comment by kilbith** [comment]
Yes the current behavior is sane apparently. I can't find the other issue in that mess, sorry.

**Comment by kilbith** [comment]
Okay, I think it's that : https://github.com/minetest/minetest/issues/1218

**Comment by kilbith** [comment]
In all frankness, those errors are kinda spammy when mobs are around (seen on various servers)... There's no way to hide them ?

![capture d ecran_2015-09-26_12-53-05](https://cloud.githubusercontent.com/assets/7883281/10117150/9b3ce338-644d-11e5-8087-616d2a3e4fe3.png)

**Comment by 0-afflatus** [comment]
These errors should appear in the log, not in chat.

**Comment by est31** [comment]
@0-afflatus this issue report is closed.

**Comment by paramat** [comment]
> This one should take over for the corrupted AOM bug that has been around for quite a while now.

This was wrongly closed.

**Comment by Fixer-007** [comment]
Yes please, those errors are for modders/developers only :)

**Comment by appgurueu** [comment]
Is this still reproducable?
