### ISSUE TITLE
Allow to suppress/veto chat messages.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#2943]
Currently we can register listeners for chat messages with `minetest.register_on_chat_message`. It would be very useful if we would be able to veto chat messages, so that they are not send.

The proposed change is simple, if the function registered at `register_on_chat_message` returns `false`, the chat message should be discarded. In this case the check should be explicit for `false`, to keep compatibility with already existing clients that use this function (which are not returning anything).

    minetest.register_on_chat_message(function(player, message)
        if message is not what I like then
            -- Suppress message.
            return false
        end
    end)

The main use case in this case is that I'd like to write a chat system that is distance based with absolute no global messages except admin announcements or some such. For that there needs to be a way to suppress messages.

**Comment by C1ffisme** [comment]
This would be useful, especially if your server had a strict policy against cursing, etc.

**Comment by PilzAdam** [comment]
It already has this functionality; you need to return `true`, though, to indicate that the message was handled.
This seems to be missing in lua_api.txt.

**Comment by bluebear94** [comment]
Also useful would be the ability to return a modified version of the message and have that instead be shown.

**Comment by PilzAdam** [comment]
@bluebear94 That could be achieved via a combination of blocking the message and using `chat_send_all()`.

**Comment by RobertZenz** [comment]
@PilzAdam Yes, it is missing from lua_api.txt and I've seen that when browsing `chatcommands.lua`, though even if I would return `true` in my tests, the message was still send. I've tried it in singleplayer mode.

**Comment by PilzAdam** [comment]
@RobertZenz the client who sends the message always displays it directly in it's own chat. If the message is blocked it is not send to any other clients. You can't test this in singleplayer.

**Comment by RobertZenz** [comment]
@PilzAdam Ohhh. Thank you.
