### ISSUE TITLE
Immortal/Zombie Glitch

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#2945]
Sometimes (I think this happens when the player dies but the server somehow doesnt register it), the player becomes like a zombie in the world.

The player has no HP, and can't be killed (PvP or fall damage)
The player can't build, or interact with the world (though can still use the client-side copy of the map)
The player can still chat, use commands, etc.
The player appears to be lying on the ground to others, similarly to when a player dies but doesn't click the respawn button.

Rejoining doesn't always help.

I don't know how this fixes itself, but it is fixed after some time.

**Comment by nerzhul** [comment]
Can you revert commit https://github.com/minetest/minetest/commit/1a1774a1051790ef85b1bd8b047ac45a3676b5d6 and tell us if that fix your problem ?

**Comment by nanepiwo** [comment]
I will try this, but since I am not exactly sure how to reproduce this bug, there may be no way to check if this fixes the problem.

**Comment by est31** [comment]
@VanessaE has seen the bug since 0.4.10, its no recent regression.

**Comment by red-001** [comment]
This has happened to me before. It seems to be linked to the player profile because making a new one removes it even if rejoining doesn't.

**Comment by paramat** [comment]
Any recent occurence?

**Comment by LoneWolfHT** [comment]
Try disabling the death formspec. IIRC: /Minetest/builtin/client/init.lua

**Comment by LoneWolfHT** [comment]
I've done it before without disabling the death formspec. If you hit an exit button on a formspec just as you die I think it will also close the death formspec without respawning the player

**Comment by WulftheNordicRanger** [comment]
I've observed this on my server, it can be reproduced in this fashion:
1, do /killme
2, close the window by hitting the x without hitting respawn
3, rejoin
I can fix it The player becomes as nanepiwo said, a zombie, rebooting does not fix it and the only way I have been able to fix is by using /heal (I have icydiamond's server essentials installed) on the player. It also seems to happen in multiplayer only as I cannot reproduce it in singleplayer. Both my client and the server are on 5.3 dev but I had a player who managed to reproduce this on 5.2

**Comment by SmallJoker** [comment]
So if you join with 0 HP, the death message is not re-sent?

**Comment by WulftheNordicRanger** [comment]
Nope, you just join as basically a corpse that can move around, chat and run commands but they can't interact. Rebooting the server also does not fix the glitch

**Comment by LoneWolfHT** [comment]
Might be nice to have a `.respawn` command for when you need to manually respawn because the death formspec wasn't shown

**Comment by fluxionary** [comment]
I've seen this issue occasionally on Blocky Survival, but have never been able to reproduce it. I have no idea what's different between my client(s) and those of other players. 

I fixed the issue on BlS w/ this snippet:

```
local spawn_pos = minetest.string_to_pos(minetest.settings:get("static_spawnpoint") or "(0, 0, 0)")

minetest.register_on_joinplayer(function(player)
    if player:get_hp() == 0 then
        player:set_hp(20, "respawn")
        player:set_pos(spawn_pos)
    end
end)
```

**Comment by nerzhul** [comment]
a such command is required in games yes, and this workaround is nice, but in fact we just need to send the death formspec on joining if player hp are zero and we are a mode compatible with, instead of respawning directly (which is not the original player state).
Can someone provide a such behaviour using builtin or c++ side ?

**Comment by fluxionary** [comment]
@nerzhul code is alredy in place to send a "death" formspec to the player on relog in the appropriate context, the issue is that *some* players don't seem to get it. the problem seems to be client-side. i (and probably any dev that's looked at this) can't replicate it, but i've had trusted players replicate it to my satisfaction in front of me. something weird is going on.

**Comment by nerzhul** [comment]
i think it's because it's too early maybe ? we may add an extra time step before sending. I think if we send it when player is login and not in world map the formspec is just missed.

**Comment by jherforth** [comment]
I fixed this for my two users who were in this state by having them log off the server, then running /remove_player PlayerName command. They logged back in and respawned fresh and had everything fixed again.
