### ISSUE TITLE
Android graphics broken

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2962]
See screenshot. Shaders are disabled. You can see that plants are broken, as well as inventory icons.
![screenshot](https://cloud.githubusercontent.com/assets/8872119/8909522/0a639d70-3482-11e5-907a-529a708d1f98.png)

**Comment by Wayward1** [comment]
It must've been a recent commit (assuming there's nothing wrong with your build :P), because my build from the 24th works fine:
![screenshot_2015-07-27-12-00-41](https://cloud.githubusercontent.com/assets/8821916/8910962/bc4777bc-3457-11e5-8676-033871c12ab5.png)

**Comment by est31** [comment]
okay, my build seems to be broken, still having it with 9af7f38e3f077ec42fcc3086c82d2676c53c84a6

**Comment by est31** [comment]
Can't reproduce anymore
