### ISSUE TITLE
Android: No creation of a new world on first run

### ISSUE THREAD

**Issue by est31** [minetest/minetest#2971]
If you delete or rename the `/storage/sdcard0/{M,m}inetest` directory, and let a recent build e.g. eb3aac20c879b9532cd3b678efb2126adcd07af7 re-create it, fails to create a world directory for the singleplayer, when you press the "Start Singleplayer" button. The relevant logcat is:
```
I/minetest(17718): GUIEngine: Deinitializing scripting
I/minetest(17718): Searching worlds...
I/minetest(17718):   In /storage/sdcard0/minetest/worlds: 
I/minetest(17718): 0 found.
I/minetest(17718): Selected world: [--world parameter] [new] [/storage/sdcard0/minetest/worlds/world]
V/minetest(17718): 2015-07-29 18:51:48: ERROR[main]: Provided world path doesn't exist: /storage/sdcard0/minetest/worlds/world
E/minetest(17718): Provided world path doesn't exist: /storage/sdcard0/minetest/worlds/world
```

**Comment by est31** [comment]
Note: Clicking "Reset Singleplayer world" in the settings menu is no workaround.
Confirmed to exist on 1cb404522f1fd2f856383e10e409048468df0849 .

**Comment by kilbith** [comment]
This error triggers when you are joining the menu or after a specific action ? Also is there any worlds list in the Android menu ?

**Comment by est31** [comment]
@kilbith updated issue description, the bug is seen when you click the "start singleplayer" button.

**Comment by kilbith** [comment]
OK, last comment is useful then.

**Comment by Wayward1** [comment]
I am unable to reproduce this after building from both my normal directory and a fresh directory.

**Comment by est31** [comment]
Ok, this is an invalid bug, it happens if you don't copy minetest_game.
