### ISSUE TITLE
Very fast repeating step sounds on entity collision

### ISSUE THREAD

**Issue by wischi-chr** [minetest/minetest#2974]
Standing on an entity forces it to "jiggle" and producing step sounds.
This can be reproduced by this three simple steps:

1.) place a boat on water (does also work with other entities)
2.) replace the water source with another node (for example: dirt)
3.) now step on the boat and listen :smile: 

Because I'm very bad at explaining things I made a short video:
https://youtu.be/EAwQ4Mwr4tc

**Comment by est31** [comment]
We should perhaps scan for the velocity on collisions, and if its too small, don't play the sound.

**Comment by 4aiman** [comment]
If collisions are to be looked upon, could it be that someone would add collision box rotations?

On the topic:
Find *any* mob or any entity and step on it.
Moreover, if an entity will step on some other entity... the result will be the same.

**Comment by PilzAdam** [comment]
@est31 maybe there is a bug in collisionMoveSimple(). Sound is only played if `!touching_ground_was && touching_ground`. So it seems that touching_ground changes when you are standing on top of an entity, although it shouldn't.

**Comment by VanessaE** [comment]
You can also reproduce the rapid-sounds effect by trying to climb down a ladder while standing on the ground.

**Comment by est31** [comment]
That can be even seen as feature, the sound giving feedback that you press a button.

**Comment by PilzAdam** [comment]
@est31 thats ridiculous.

**Comment by 4aiman** [comment]
> That can be even seen as feature, the sound giving feedback that you press a button.

Tee-hee ^______^
Hilarious!
