### ISSUE TITLE
player model not showing double-sided polygons/normals

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#2984]
Take this skin for example:

![skin_20150704042449192820](https://cloud.githubusercontent.com/assets/1733537/9022819/ea006256-3851-11e5-9a52-18ae4b8517a6.png)

( Image file taken from http://www.minecraftskins.com/skin/5888666/ombre-rainbow-cat/ )

In Minecraft, apparently it renders like this:

![image](https://cloud.githubusercontent.com/assets/1733537/9022831/5a4d1b08-3852-11e5-9139-693f00c74412.png)

(Screenshots of the same minecraftskins.com page as above)

But in Minetest, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1733537/9022808/9a032144-3851-11e5-8cff-49585f040563.png)

Notice that the cat's face and tail, really the outside surfaces of the body front and body back, are rendered only from one side -- you can't see the skin's front surfaces when looking at the back of the model, nor the back surfaces when looking at the front view.

Also notice the similar glitch at the bottoms of the "legs".

This affects all player skins with transparent body/arm/leg sections.

**Comment by stujones11** [comment]
I'd say that was just backface culling in action, not really a bug imo.

**Comment by est31** [comment]
Well, we claim to be compatible with minecraft skins. So our behaviour has to be exactly the same as theirs, therefore this is a bug. We'll either have to disable backface culling for player textures, or find another way to do it.

**Comment by stujones11** [comment]
>Well, we claim to be compatible with minecraft skins. So our behaviour has to be exactly the same as theirs
Sorry, but I think you would need to do a lot more than disable bfc to be fully compatible to current mc skins.
This has been the default behavior since forever so I still do not think this deserves the bug label :p
