### ISSUE TITLE
Can't serialize data of type userdata

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#2989]
tenplus1 reports the following error:

> Crash logs from Xanadu server, multiple crashing within minutes of each other:

```
2015-07-26 01:37:05: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
2015-07-26 01:37:05: ERROR[main]: /usr/share/minetest/builtin/common/serialize.lua:152: Can't serialize data of type userdata

2015-07-26 01:37:05: ERROR[main]: stack traceback:
2015-07-26 01:37:05: ERROR[main]:   [C]: in function 'error'
2015-07-26 01:37:05: ERROR[main]:   /usr/share/minetest/builtin/common/serialize.lua:152: in function 'dump_or_ref_val'

2015-07-26 01:37:05: ERROR[main]:   /usr/share/minetest/builtin/common/serialize.lua:147: in function 'dump_or_ref_val'
2015-07-26 01:37:05: ERROR[main]:   /usr/share/minetest/builtin/common/serialize.lua:147: in function 'dump_or_ref_val'

2015-07-26 01:37:05: ERROR[main]:   /usr/share/minetest/builtin/common/serialize.lua:167: in function </usr/share/minetest/builtin/common/serialize.lua:20>

In thread 7f256d75c7c0:
/build/minetest-Uqow_W/minetest-201507251831/src/server.cpp:522: void Server::step(float): A fatal error occurred: /usr/share/minetest/builtin/common/serialize.lua:152: Can't serialize data of type userdata

stack traceback:
    [C]: in function 'error'
    /usr/share/minetest/builtin/common/serialize.lua:152: in function 'dump_or_ref_val'
    /usr/share/minetest/builtin/common/serialize.lua:147: in function 'dump_or_ref_val'
    /usr/share/minetest/builtin/common/serialize.lua:147: in function 'dump_or_ref_val'
    /usr/share/minetest/builtin/common/serialize.lua:167: in function </usr/share/minetest/builtin/common/serialize.lua:20>

Debug stacks:
DEBUG STACK FOR THREAD 7f25537fe700:
#0  virtual void* EmergeThread::Thread()
(Leftover data: #1  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #2  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
(Leftover data: #3  void ItemStack::deSerialize(std::istream&, IItemDefManager*))

```

> ...am adding the following lines after line 121 in serialize.lua incase it helps error:

```
elseif tp == "userdata" then
    return "user: "..x:get_player_name().." at "..minetest.pos_to_string(x:getpos())
```

**Comment by est31** [comment]
#2972 is related. I don't think this is a bug.

**Comment by PilzAdam** [comment]
Probably a mod passing invalid data to minetest.serialize().

**Comment by kwolekr** [comment]
We can't tell if it's a bug or not because there isn't a complete stack trace.  Is this a limitation of Lua or our own code?

**Comment by HybridDog** [comment]
as far as l know <userdata> doesn't mean it's a player
it's a object, e.g. meta, vmanip, player

**Comment by est31** [comment]
players are entities as well, no?

**Comment by HybridDog** [comment]
>players are entities as well

http://dev.minetest.net/player
they are entities, e.g. ```minetest.get_player_by_name("admin"):set_properties({visual_size={x=100, y=100}})```, but if you try to e.g. set the acceleration of a player it doesn't work

**Comment by nerzhul** [comment]
Discussed on IRC. no fix to do there it's just a bad implementation done by user

**Comment by TamaMcGlinn** [comment]
Since I end up looking for this issue in the hope of finding more debugging info, I'll dump this utility function here for others as well:

```lua
-- Find first path to value inside input
-- with type 'userdata' by calling itself for each element
-- of lists and dictionaries
function path_to_userdata(input)
  if type(input) == 'userdata' then
    return ""
  end
  if type(input) == 'table' then
    for key, value in pairs(input) do
      local path_to_userdata = path_to_userdata(value)
      if path_to_userdata ~= nil then
        return "." .. key .. path_to_userdata
      end
    end
  end
  return nil
end
```

To use this, just call it on the variable you want to serialize beforehand. I recommend still crashing, as in the below code, so that the error message is the last item in debug.txt:

```lua
function MyNewEntity:get_staticdata()
  local data = { ... }
  local userdata_path = path_to_userdata(data)
  if userdata_path ~= nil then
    minetest.log("error", "attempted to serialize userdata at " .. userdata_path)
  end
  return minetest.serialize(data)
end
```

That way after crashing, `tail debug.txt` is going to show something like:

```
2025-01-02 16:42:32: ERROR[Main]: attempted to serialize userdata at .workspace.bot.object
```

And then you know that data.workspace.bot.object is of type userdata.

**Comment by appgurueu** [comment]
That's a solid option. You can also use `dump` (or `dump2`, or any decent Lua pretty-printing / inspecting / dumping util) to dump Lua tables so you can see their structure (including opaque `<userdata>`) at a glance, see https://github.com/minetest/minetest/blob/master/doc/lua_api.md#helper-functions.

<sub>Nerdy side note, your paths are found using a DFS which depends on `pairs` (which does not guarantee an order of iteration), meaning really it just finds any path to userdata, not necessarily the "first" or even "a shortest" one (the latter would require a BFS).</sub>
