### ISSUE TITLE
Looking around is jittery

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#2998]
While looking around, the view jitters noticeably, even while moving one's finger in a straight line. Enabling cinematic_camera_smoothing seems to help, but leads to #2599, and camera_smoothing does the same thing, but more pronounced.

**Comment by est31** [comment]
I can confirm this, although I haven't tested master. Have you?

**Comment by est31** [comment]
Easy way to reproduce: keep your finger pressed on some part of the screen, without dragging it. The screen will then jump around.

**Comment by est31** [comment]
Hrmm, now I can't really reproduce this anymore... Have you tried with and without connected to an usb charger? Internet says it can affect jitterishness.

**Comment by Wayward1** [comment]
I've noticed it for a while now, but never thought to open an issue until recently. It happens on both the official and my builds, with and without a charger connected.

**Comment by sapier** [comment]
This might be device dependent, could those having this issue please provide information about their devices?

**Comment by rubenwardy** [comment]
I can see some discrete movement (as in, not continuous - in small steps), but it doesn't jitter as such. Is that what you meant?

**Comment by Wayward1** [comment]
Yes, that's it. "Jittery" was the best term I could come up with at the time.

**Comment by stujones11** [comment]
@Wayward1 Are you still getting this with recent builds? It seems okay for me, given the framerate, etc.

**Comment by paramat** [comment]
Seems ok or fixed.
