### ISSUE TITLE
Allow overriding damage calculation outside of entity definition

### ISSUE THREAD

**Issue by infmagic2047** [minetest/minetest#3001]
Currently we have `register_on_player_hpchange` for overriding player damage, but for entity damage (eg. mobs) we can only use `on_punch` in entity definition which can't be used in mods that didn't define the entity. For example, I can't define a tool that does damage differently. It would be nice if we have something like `register_on_punchentity` to do that.

**Comment by pandaro** [comment]
+1

**Comment by paramat** [comment]
Any comments? Anyone interested in coding this? If not closing in 1 month.

**Comment by paramat** [comment]
Any core dev interest?

**Comment by paramat** [comment]
No core dev support for 2 years. Core devs feel free to reopen if you support.
