### ISSUE TITLE
ABM scanning is very slow

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3002]
I haven't done a benchmark, but from reading the code, our current strategy looks like:

```
For all nodes n in loaded areas do
    For all abms a registered do
        If n matches a's nodename then
            If we have neighbours then
                  For all 8 possible neighbour positions do
                     If its a neighbour then
                         //neighbour found, abm matches!
                     end
                  end
            else
                  //abm matches!
            end
        end
```

The worst part of this is, that it happens at each abm step. There is no caching happening.
It even becomes worse, every node in an "inner" mapblock (one where all neighbouring mapblocks are loaded) is additionally scanned 8 times (again, for every possible abm out there), because of the `active_object_count` and `active_object_count_wider` params.

This has to be improved greatly. We should cache the `active_object_count`, and invalidate the cache at modifications of the world. Also, we should also cache the list of matching nodes for the abm.

**Comment by paramat** [comment]
Surely the 'active block range' of 32 nodes will reduce the scan to a 32 node radius around the player?

**Comment by nerzhul** [comment]
@paramat if we look in range we will look to all nodes to have a list, some tests are needed.

**Comment by est31** [comment]
@paramat You can adjust this range parameter (right now the default for `active_block_range` is 2 (mapblocks), which is equal to your mentioned 32 nodes), but it won't help you with e.g. servers with the technic mod, where we keep all blocks with machines loaded. 

Also, its better to have an efficient algorithm than having to make compromises in gameplay.

**Comment by juhdanad** [comment]
I think such nodes that are not frequent should use node timers. They can reset their timer to a random value to mimic ABMs.
ABMs should be used when massive amounts of nodes need to be modified and it is inefficient to store them in memory (leaves, grass, dirt etc.) The chance of the ABM is almost always a big number then.

My idea to make ABMs with small probabilities more efficient:
let the probability of a node to trigger be p=1/ABM.chance.
The ABM's (inefficient) algorithm could be:
```
For all abms a registered do
    For all nodes n in loaded areas do
        If random()<p
            If node and its neighbors match
                //trigger node
```
Now the chance that the first node will be inspected is p.
The second node: (1-p)p (first fails, then succeeds).
The k-th node: p(1-p)^(k-1).

The sum of the first l probabilities is 1-(1-p)^l.
So the l-th node will be updated if 1-(1-p)^(l-1)<=random()<1-(1-p)^l.
floor(1+log_(1-p)(1-random()))=l

So the faster version:
```
For all abms a registered do
    if p>0.5 // computing logarithms is slower probably
        For all nodes n in loaded areas do
            If random()<p
                If node and its neighbors match
                    // trigger node
    else // if p<=0.5
        start from the 0-th node
        while true
            skip floor(1+log_(1-p)(1-random())) nodes
            if there are no nodes left, break
            If node and its neighbors match
                    // trigger node
        end while
```

**Comment by paramat** [comment]
Reopening because important and useful information.
Also see #7280

**Comment by paramat** [comment]
#7555 merged.
