### ISSUE TITLE
Do leafdecay scanning in the engine

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3003]
Currently, leafdecay scanning is very slow, as its usually done in an abm, and by lua. We should add additional support for a "missing_neighbours" param for the `register_abm` call, with additional `missing_neighbours_range` and `neighbours_range` scan range params (maximum 16, for now).

About implementing it engine side:
If the range is larger than 1, I propose that we add help data structures `ABMNeighbourCache` per each abm neighbour and mapblock, invalidated if a node inside the mapblock gets changed.

Every `ABMNeighbourCache` contains a list of 4 boolean arrays, each representing a tighter grid on the mapblock, from sizes of 2^3 to 16^3, the complete mapblock. The boolean value for a grid cell is true, if there is a matching neighbour inside the cell, false otherwise. Now, when we search for the presence (or non-presence) of possibly distant neighbours, we do a lookup of this array structure. During scanning, we progress down throgh the cache, from the whole mapblock, to finer grids.

**Comment by nerzhul** [comment]
:+1:

**Comment by C1ffisme** [comment]
But if we did leafdecay in the engine, then that would remove a lot of customization. Then you couldn't say how fast you wanted the leaves to decay or if you wanted them to not decay on certain events.

**Comment by est31** [comment]
@C1ffisme my proposal is only about leafdecay scanning, not about leafdecay itself. You would still be abled to set interval and chance of the decay, as well as have a fully customizeable function called when the decay criteria are met.

**Comment by C1ffisme** [comment]
Ah...

I know, though, that there is an issue on making ABMs faster.

**Comment by ProgrammingChicken** [comment]
'Do ABM scanning in the engine' may or may not be an existing issue.

**Comment by est31** [comment]
We already do ABM scanning engine side. This issue is about implementing the algorithm described above.

**Comment by paramat** [comment]
Leafdecay no longer uses ABMs fortunately.
