### ISSUE TITLE
Lighting bug with water

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3004]
Water source nodes that have been placed with a bucket have different lighting than water nodes that have been autogenerated. see attached screenshot, there are 4 actual source blocks here, the two darker ones are placed with the bucket.
![screenshot](https://cloud.githubusercontent.com/assets/8872119/9055717/9a816df4-3a8d-11e5-8319-06dec89499be.png)

**Comment by ProgrammingChicken** [comment]
I've actually never seen this, but I'll try to reproduce it with my minetest.

**Comment by Wayward1** [comment]
I can't reproduce either, at least not on Android. I'll try again on my laptop once I get home.

**Comment by nanepiwo** [comment]
Might be related to #1404

**Comment by est31** [comment]
Nope, its not 1404.

**Comment by Megaf** [comment]
Well, water_source do have a different shadow than water_flowing, if that is intentional or not I don't know.

**Comment by est31** [comment]
Its water_source both times.

**Comment by ProgrammingChicken** [comment]
Maybe a bug in lighting engine?
This is confusing.

**Comment by gregorycu** [comment]
I cannot repro either.

**Comment by Zeno-** [comment]
I don't know if it's been fixed, but there was a bug introduced with a reflow liquid optimisation. It might be related. Dunno.

**Comment by Megaf** [comment]
@Zeno- Do you know the commit?

**Comment by Zeno-** [comment]
@Megaf not off hand. I guess I could find it. It was one of gregorycu's changes if that narrows things down

**Comment by Fixer-007** [comment]
Confirmed that bug on 0.4.13

**Comment by RealBadAngel** [comment]
one could mention that this is only visible with smooth_lighting = false ...

**Comment by RHRhino** [comment]
@RealBadAngel For me it is only visible the other way round with smooth_lighting = true. It diaappears as soon as you disable smooth_lighting.

**Comment by Megaf** [comment]
For me the bug shows up with smooth_lighting = false.

**Comment by paramat** [comment]
Possibly fixed by #4655 ?

**Comment by Fixer-007** [comment]
Ok, I'm looking at it just now, will post updates here, pasting my notes here:
build cd2c8ad: can see it when placing water source near beach with shaders on and off
will check build with light improving PR now

**Comment by Thomas--S** [comment]
I can also not reproduce the bug with the latest version.

**Comment by est31** [comment]
Okay, then I'd say its fixed, most likely by c071efaa43ad3dcba7d60a7a67e942aae2a7dc83
