### ISSUE TITLE
 Change animation speed of Entity, without starting it from the beginning

### ISSUE THREAD

**Issue by andrey-kun** [minetest/minetest#3007]
There is a problem: need change the speed of Entity wheel during its rotation. I made an animated wheel in Blender and sketched a similar code:

``` lua
function vehicleWheel.on_step(self)
    self.object:set_animation({x = 1, y = 100}, rotateSpeed, 0, true)
end
```

However, I only got convulsive trembling wheel, because the function set_animation animation starts from the beginning. If I put game on pause, I see that the wheel starts to spin normally. But to set the animation speed Entity, bypassing set_animation function is not possible. Can implement animation using the functions set_bone_position, but the result is predictable. Tell me, can I have missed something, or Lua Mod API is now really does not give to do it. If not, in the future it will be added to the API? I could add a function like set_animation_speed, but not Know how it will be compatible with future changes.

**Comment by sofar** [comment]
At a minimum this needs a documentation change, that explains that "if setting the same animation sequence but with different speed, that the animation isn't restarted from the start of the sequence"

Or something like that, at least, that is how I understood this PR.

**Comment by NaruTrey** [comment]
I agree. In addition, in **lua_api.txt** `set_animation` method does not have any description.

**Comment by paramat** [comment]
Added 'bug' for the lack of documentation.

**Comment by DS-Minetest** [comment]
Afaik, it's even documented: https://github.com/minetest/minetest/blob/7640749d68b87a62868840d34a665101861ca9c0/doc/lua_api.txt#L3333

**Comment by paramat** [comment]
> At a minimum this needs a documentation change, that explains that "if setting the same animation sequence but with different speed, that the animation isn't restarted from the start of the sequence"

**Comment by paramat** [comment]
Apart from the docs issue, any interest for the feature?

**Comment by Wuzzy2** [comment]
This is now fixed since a while. You can use `entity:set_animation_frame_speed` to change the animation speed without resetting the animation.
