### ISSUE TITLE
mingw cross-compiled binary needs  libgcc_s_sjlj-1.dll and other libs

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#3009]
While it's "ok" to ship Minetest with some dlls, there are some of those which shouldn't be required (i.e. should be statically built):

```
chaiman@konsodeb:~/minetest/util/buildbot$ wine32 /home/chaiman/minetest/util/buildbot/win32/minetest/bin/minetest.exe
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:process:SetProcessDEPPolicy (1): stub
fixme:heap:HeapSetInformation (nil) 1 (nil) 0
fixme:win:RegisterDeviceNotificationA (hwnd=0x125878, filter=0x75e944,flags=0x00000001) returns a fake device notification handle!
fixme:win:RegisterDeviceNotificationA (hwnd=0x125878, filter=0x75e944,flags=0x00000001) returns a fake device notification handle!
err:module:import_dll Library libintl3.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library Irrlicht.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library libleveldb.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library libcurl-4.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library libvorbisfile-3.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library libsqlite3-0.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library zlibwapi.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library libgcc_s_sjlj-1.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"Z:\\home\\chaiman\\minetest\\util\\buildbot\\win32\\minetest\\bin\\minetest.exe" failed, status c0000135
```

^ Look at the last 2 dlls needed to get what's wrong.
I can see the same "picture" when running in Windows 7/8.

PS: latest minetest-dev here.

**Comment by paramat** [comment]
@4aiman Stil a problem?

**Comment by 4aiman** [comment]
@paramat yes.

I wonder how hard could it be to try to cross-compile on any recent Debian [derivative]?..
It seems like no one have tried to reproduce this issue.
And it's all about the fact that libgcc and libstdc++ don't want to be linked statically.
But the toolchain file is broken anyway.

Please, keep issue this open till someone who *do* cross-compile will show up.

**Comment by Fixer-007** [comment]
I do cross-compile it on debian, and it is needed to include two dlls shipped with mingw64 in /bin directory: libgcc_s_seh-1.dll and libstdc++-6.dll
Why is this a problem for you?

**Comment by 4aiman** [comment]
@Fixer-007 It's not a problem to ship 2 more dlls. But those 2 libs don't add any 3rd-party functional like openal or vorbis. I think those should be linked statically.

Even if static linkage is not an option, then CPack should include those libs in a package.

Either way, package build system is broken, as one can't ship the win32/64 package "as is" but forced to re-pack manually instead.

Now back to static linkage: 
Additional dlls' paths may differ for various OSes. That means the CPack should either search for the correct dll files or the one who builds should manually adjust the building script for every new setup (PC).

Static linkage would've solved the problem above once and for all w/o too much trouble.

**Comment by paramat** [comment]
Still an issue?

**Comment by sfan5** [comment]
Yes, this won't go away unless solved.
