### ISSUE TITLE
Client side way to turn off player names

### ISSUE THREAD

**Issue by cornernote** [minetest/minetest#3012]
you can toggle chat and gui with F1 F2, but there is no way to toggle player names (unless I am mistaken)

giving this ability would allow for cleaner screenshots in multi-player servers

**Comment by ProgrammingChicken** [comment]
+1, and I also think this might be a tiny bit related to what you are talking about:
https://github.com/minetest/minetest/issues/1345
and there are global (all players affected) lua API functions.

**Comment by paramat** [comment]
See #3712 and RBA's latest work.

**Comment by paramat** [comment]
#3712 is merged, F1 now toggles names.

**Comment by cornernote** [comment]
Thanks!
