### ISSUE TITLE
Reliable node update callback

### ISSUE THREAD

**Issue by wischi-chr** [minetest/minetest#3015]
atm every mods which needs such an update mechanism registers on_dignode and on_placenode use them for node change detection. But this fails in many cases:

1.) minetest.set_node and minetest.swap_node can not be detected at all. It is not even possible to hook this function reliable because there is no way to make sure a mod is loaded first (before other mods can use the original function)

2.) Many mod-devs do not care (or forget) calling the callback functions
http://dev.minetest.net/minetest.register_node#on_place
(there is no way to prevent this besides fixing all used mods yourself)

3.) There is no way to detect "landing" falling_nodes. They are triggered by on_dignode and on_placenode - so nr. 2 mods also break falling_nodes. And falling_nodes break every update mechanism because the landing is not detectable at all!

imo a minetest.node_changed(pos,old_node,new_node) is needed which can not be accidentally overwritten.

**Comment by est31** [comment]
Related to #2776
About 2.: there is `on_construct`.

**Comment by ShadowNinja** [comment]
`on_construct` and `on_destruct` should be called for everything but changes via an LVM (and a callback won't be added for that because it's low-level).

**Comment by paramat** [comment]
Any comments? Anyone interested in coding this sometime? If not closing in 1 month.

**Comment by JurajVajda** [comment]
i need a callback on swap_node please :+1:

**Comment by paramat** [comment]
Isn't swap node meant to have no callbacks to be fast? Just like it not changing metadata.

**Comment by JurajVajda** [comment]
Yes that is true.. but how can i trigger the callbacks on the node or detect that the node was swapped ?

**Comment by JurajVajda** [comment]
Nevermind..i found different solution.

**Comment by paramat** [comment]
Any core dev support?

'swap node' is not an issue here, it's without callbacks for good reason.

**Comment by paramat** [comment]
Actually i support this, as it may allow ABMs to be used less.

**Comment by Minetest-One** [comment]
this is getting actual now, I guess
[swap_not crash 5.1.0-dev](https://forum.minetest.net/viewtopic.php?f=6&t=22397)
goes back to 
`/usr/local/share/minetest/builtin/game/item.lua:423: in function </usr/local/share/minetest/builtin/game/item.lua:416>
`

**Comment by Zughy** [comment]
Paramat's gone, ShadowNinja said they were against this idea, and OP said they've opted for another solution anyway. Closing

**Comment by wischi-chr** [comment]
I haven't really found a good solution (Juraj did) and I still think it would be a good idea to provide a more solid way of detecting changes. But I'm currently not working with minetest and this issue is seven years old, so it's probably for the best to close it.
