### ISSUE TITLE
The character can not walk down the stairs.

### ISSUE THREAD

**Issue by narrnika** [minetest/minetest#3021]
minetest-0.4.13_RC
windows-8.1, 32-bit

The problem is when I go down from node with climbable = true ("default:ladder", for example)
to node with node_box = {type = "fixed", fixed = {{-0.5, -0.5, -0.5,  0.5, H, 0.5}}}, (0.5 < H < 0, for example "default:snow" or "door:trapdoor").
It looks like this: http://www.youtube.com/watch?v=cGaCrqgjwWE

If H >= 0 then this is no problem.
In minetest-0.4.12 this is no problem.

PS: I understand that it's not a big problem, but it can create difficulties in some situations, or when using some mods.

**Comment by PilzAdam** [comment]
Just another manifestation of #665. When you reach the bottom of the ladder you fall onto the nodebox and sneaking pushes you up again.

**Comment by narrnika** [comment]
Agreed.
Menu -> Change_Keys -> ["Use" = climb down] = true.
Closed.
