### ISSUE TITLE
Input Method Editor (IME) Support

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3022]
https://en.wikipedia.org/wiki/Input_Method_Editor

Minetest isn't support IME.
(Ctrl+V only can enter)

**Comment by Rui914** [comment]
This is irrlicht problem.
Also, I created Japanese IME for Minetest.

**Comment by sfan5** [comment]
Eh, actually not. Using a mod to add IME support to Minetest is probably the worst way to solve this. 

What we need is Irrlicht to support IMEs.

**Comment by paramat** [comment]
Any point keeping this open? Any news if Irrlicht will support IMEs?

**Comment by sfan5** [comment]
I doubt it.
It's useful to keep this open as a reminder, also workarounds might be possible.

**Comment by paramat** [comment]
I can't see a point in keping it open.

**Comment by paramat** [comment]
Just wondering, how is this useful as a reminder?

**Comment by zaoqi** [comment]
Popping a text box on input like Android build is a possible workaround

**Comment by zaoqi** [comment]
Using Irrlicht with SDL is a possible workaround
Popping a text box on input like Android build is another possible workaround

**Comment by Zughy** [comment]
Since Irrlicht development is now handled by Minetest core devs, please reopen this issue (if it still persists) in the specific repo: https://github.com/minetest/irrlicht
