### ISSUE TITLE
error in src/util/serialize.h:265

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3023]
When l played with technic devices, minetest suddenly crashed:
```
2015-08-09 19:57:24: ACTION[main]: Deprecated formspec element "invsize" is used
2015-08-09 19:58:01: ERROR[main]: WARNING: updateListener: invalid value
minetest: /build/minetest-cirfxp/minetest-201508080046/src/util/serialize.h:265: void writeF1000(irr::u8*, irr::f32): Zusicherung »i >= ((float)(s32)((-0x7FFFFFFF - 1) / 1000.0f)) && i <= ((float)(s32)((0x7FFFFFFF) / 1000.0f))« nicht erfüllt.
Abgebrochen
```
https://github.com/minetest/minetest/blob/master/src/util/serialize.h#L265

**Comment by kwolekr** [comment]
Could you get a stack backtrace of this crash?

**Comment by est31** [comment]
removing blocker tag, as it only affects debug builds.

**Comment by est31** [comment]
The assert has been added by 42cf5e972d1e27a92048712bc79806e1a088b96c, but only to help finding the core problem.

**Comment by HybridDog** [comment]
>Could you get a stack backtrace of this crash?

l think l can't

**Comment by tenplus1** [comment]
I get this error as well in Xanadu and we are not using Technic, it crashes server at random times...
```
minetest: /build/minetest-IUBSkD/minetest-201508120830/src/util/serialize.h:265: void writeF1000(irr::u8*, irr::f32): Assertion `i >= ((float)(s32)((-0x7FFFFFFF - 1) / 1000.0f)) && i <= ((float)(s32)((0x7FFFFFFF) / 1000.0f))' failed.

**Comment by est31** [comment]
@tenplus1 compile in release mode, then the error shouldn't occur. Otherwise, get a debugger and give us a stacktrace :)

**Comment by ShadowNinja** [comment]
This is due to the fact that floats are serialized by just multiplying them by 1000 and truncating it to an `s32`, therefore only values inside the range `S32_{MIN,_MAX} / 1000` can be serialized.  A better way would be to serialize the floats as IEEE-754 binary32.  We could probably just use something like `i = htobe32(i); memcpy(buf, &i, sizeof(i));` (yes, technically IEEE-754 isn't guaranteed by the standard, but AFAIK it's used by all semi-modern computers).

@est31: It may not crash in release mode, but the truncation will result in a garbage value being serialized.

**Comment by HybridDog** [comment]
l get the same problem on another pc, 64 bit

**Comment by HybridDog** [comment]
that was for another issue

**Comment by est31** [comment]
I would agree with ditching F1000 for IEEE standardized format if:

1. We assert at program start or compilation that the program in fact uses IEEE fmt

2. @kwolekr agrees on it. He had I think the greatest concerns.

**Comment by kwolekr** [comment]
Pretty sure IEEE 754 is mandated for ANSI C/C++.
We could do this but it would totally break reverse compatibility.  For that reason it cannot be done.

**Comment by kwolekr** [comment]
I think this issue can be closed out now, seeing as how many of the Lua APIs dealing with object positions have now sanitize their inputs.

Feel free to re-open if this is not the case.

**Comment by est31** [comment]
@kwolekr you won't need to pass "version" parameters around: we already have a global version number: the network protocol verison. But yes, internally that number would need to be known to code that decides whether to serialize as f1000 or IEEE 754. It wouldn't "break" anything though, its perfectly implementable with backwards compatibility included. I don't know however about map serialisation, whether we store floats there.

**Comment by est31** [comment]
@kwolekr ANSI C++ doesn't mandate this. From the section "3.9.1 Fundamental types" of the [latest working draft of C++14](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) (page 75):

> The value representation of floating-point types is implementation-defined.

**Comment by kwolekr** [comment]
est, I'm confused by what you say.  If a server wants to support older clients it would need to take the client's version as a parameter to decide which float serialization format to use and vice versa for clients connecting to older servers.

As for the implementation-dependent format for C++... I looked into it a bit more and it seems like it's only C99 onward that mandates IEEE 754.  Oh well
