### ISSUE TITLE
Buildbot fails with gcc/g++ 5.2

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#3026]
<b>low priority</b> because I use an older gcc/g++ version for building

solutions:
- Rebuild LevelDB with g++ 5.2 (will break compat with older g++ though)
- <i>or:</i>
- Figure out how to tell g++ not to use cxxabi11

<pre>
[100%] Linking CXX executable ../../bin/minetest.exe
CMakeFiles/minetest.dir/objects.a(database-leveldb.cpp.obj):database-leveldb.cpp:(.text+0x4cf): undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
CMakeFiles/minetest.dir/objects.a(database-leveldb.cpp.obj):database-leveldb.cpp:(.text+0x12ff): undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
CMakeFiles/minetest.dir/objects.a(database-leveldb.cpp.obj):database-leveldb.cpp:(.text+0x17a6): undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
CMakeFiles/minetest.dir/objects.a(database-leveldb.cpp.obj):database-leveldb.cpp:(.text+0x17f0): undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
CMakeFiles/minetest.dir/objects.a(database-leveldb.cpp.obj):database-leveldb.cpp:(.text+0x1ee1): undefined reference to `leveldb::Status::ToString[abi:cxx11]() const'
collect2: Fehler: ld gab 1 als Ende-Status zurück
</pre>

**Comment by nerzhul** [comment]
add this option to CXX_FLAGS: -std=cxx89

**Comment by paramat** [comment]
@sfan5 still an issue?

**Comment by sfan5** [comment]
Yes

**Comment by MoNTE48** [comment]
I can confirm this
