### ISSUE TITLE
Bitwise operators don't work in lua.

### ISSUE THREAD

**Issue by 1Nick1Name** [minetest/minetest#3028]
See: https://forum.minetest.net/viewtopic.php?f=6&t=13002&p=186664#p186664

**Comment by est31** [comment]
Do you use luaJIT? bitop depends on luajit. Currently, we support both luajit and non-luajit (old) lua, so you shouldn't rely on bitops.

**Comment by 1Nick1Name** [comment]
Yes I use LuaJIT. As said in my post "Using BitOp lib works."
The problem is, that binary operaters like the shift operators << and >> dont compile, they produce an synty error. And using BitOp does not work because using "require("bit")" is not allowed with security on.

**Comment by est31** [comment]
You can turn off security then, or mark your mod as trusted.
I don't think we should do extra efforts to pass on lua runtime dependent features like bitop to our secure sandbox.

**Comment by 1Nick1Name** [comment]
Setting the mod as trusted does still not allow for require.

**Comment by est31** [comment]
You'll have to get the insecure environment, see https://forum.minetest.net/viewtopic.php?f=18&t=12471

**Comment by 1Nick1Name** [comment]
What do you mean by "runtime dependent features".  Shift and xor operators are just normal opreators like + and -.

**Comment by 1Nick1Name** [comment]
What do you mean with getting the insecure environment? 
I am jusing a version that supports security.

**Comment by est31** [comment]
bitwise operators shift and xor got added to lua only in 5.2, not in 5.1. We support 5.1 as native lua, and I guess the operators are turned off for luajit to not cause confusion.

**Comment by 1Nick1Name** [comment]
found the minetest.request_insecure_environment().
will try this.

**Comment by 1Nick1Name** [comment]
Works.
Thank you.

Why not simply add the following to builtin/init.lua an make it trusted by default.
```
function minetest.request_bit()
	local env = minetest.request_insecure_environment()
	return env.require("bit")
end
```

Then modders can write the following code using bitwise operation without going through the hassle of having to care about security.
```
local bit = minetest.request_bit()
local xor = bit.bxor
local x = 4
x = xor(x, 15)
print ("...."..tostring(x))
```

**Comment by PilzAdam** [comment]
It should be obvious when mods use an insecure environment. Also this extra line on top of a mod isn't really bad.

**Comment by 1Nick1Name** [comment]
Well then maybe add a file called *trusted.lua* have that one be trusted by default and *dofile* it in builtin/init.lua.
It would be realy great to have bitwise operations everywhere, without having to ask every server owner separatly.

**Comment by 1Nick1Name** [comment]
Hum, I've tested a bit. The idea with putting the trusted stuff in an extra mod does not work right now, because mods depending on that (trusted) mod will have to be trusted too. Too bad.
Also tried adding the *minetest.request_bit()* function to *builtin/init.lua* and setting that mod tusted, but that crashes the application.

**Comment by paramat** [comment]
Upstream issue.
