### ISSUE TITLE
Minetest crashes if resources aren't enough

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3030]
User "Biggvs_Richardvs" writes on the [forum](https://forum.minetest.net/viewtopic.php?f=6&t=12890):

> I installed the android apk on my 301T tablet running stock 4.2.1 rom and it runs fine on the default world, but as soon as I try anything "fancy" like big freakin dig, or a combo of mods like moreores+creatures+farmingplus+homedecor it will run for a while, slowly, and then _pop_ it just exits back to the home screen and you're done.
> 
> It's an nvidia tegra chipset so I'm running the ARM version.
> 
> I even tried installing omnirom running kitkat 4.4.4 and re-installing the apk, and I still get basically the same result. Running the OpenGL ES2 driver on kitkat seems to help a little, but it croaks the same after a few minutes or so of play.

Seems that many mods are too much for minetest, making it crash. Instead of crashing, we should display an error message to the user if the resources of the device aren't enough. Otherwise people might think its minetest's fault.

The reporter had the bug on android, but given limited resources I guess it can be reproduced on desktop too, therefore no android label.

**Comment by kwolekr** [comment]
WTF, stop acting bitter.

Anyway this is not a blocker.  It's likely he got an out of memory error from the testimony.  It's nothing we can realistically do about.

**Comment by est31** [comment]
OOM errors should be explained with error messages, is this demanding too much?

**Comment by PilzAdam** [comment]
I agree with @kwolekr, this isn't a blocker.

**Comment by Wayward1** [comment]
I've noticed this too when playing on certain servers. Everything loads fine, but once I spawn, the game runs much slower than usual until it just stops and exits.

**Comment by Elinvention** [comment]
Minetest crashes on my android phone with 1GB of ram too. Usually on Android devices there is no swap partition, so when the ram is full it has to kill Minetest.

**Comment by 0-afflatus** [comment]
Minetest frequently crashes with no suggestion of any reason in the log. The more information the better.
