### ISSUE TITLE
Server must have the ability to disable the minimap

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3036]
The minimap needs to be customizeable by the server, and lua.

**Comment by est31** [comment]
I believe this is a blocker, because minimap affects gameplay.

**Comment by est31** [comment]
My proposal:
1. Api function player:set_minimap_options with definition:
```
{
default_mode = id,
modes = mapping integer id to objects of the form: 
{
render_mode = "none" or "radar" or "surface",
zoom = 1,
next_f9_mode = id,
next_shift_f9_mode = id,
},
}
```
1. Api function player:set_minimap_mode(id).
And similar messages in the protocol.
If the server doesn't send such a message, the current mode-set is used.

**Comment by RealBadAngel** [comment]
wont code it here.

**Comment by PilzAdam** [comment]
Maybe use the hud api for that?

**Comment by kwolekr** [comment]
Server owners not having control over the minimap is really the only blocking issue here IMO.
You mentioned they can already do this by changing the minimap texture on the server-side.  If that's the case, the rest can wait.  This issue is asking to add functionality during a feature freeze.

**Comment by est31** [comment]
I'll have to research whether the texture can be overridden by a texture pack. If it can, we do have to add this functionality before release, if it cannot, there is no problem :)

**Comment by paramat** [comment]
Should the minimap be hard-disabled for 0.4.13? RBA is planning to rewrite it. also RBA and hmmmm are unhappy with it's current implementation, apparently being inefficient and heavy. It seems it was merged too early and is not up to release standard.

**Comment by ExeterDad** [comment]
@est31 I can verify at least the round overlay can be overridden client side by a texture pack but @kwolekr I am unable to figure out how to change the texture server side. https://forum.minetest.net/viewtopic.php?f=4&t=13035

**Comment by est31** [comment]
@ExeterDad I think this is impossible, therefore we need a custom way.

**Comment by est31** [comment]
@paramat Yes, it should have no performance impact if it is disabled in .conf.
I don't think we should hard-disable or default-disable it for 0.4.13, its mostly in an ok state.  Its not inefficient from how I see it, I haven't heard any real big issues from them, see #2844 for more discussion on this.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/be9024a397506dff1151b16e5f7a91e393b00d7e
