### ISSUE TITLE
Cannot load mod list

### ISSUE THREAD

**Issue by TheLastProject** [minetest/minetest#3042]
`2015-08-13 01:51:29: ERROR[AsyncWorkerThread_1]: https://forum.minetest.net/mmdb/mods/ not found (HTTP response code said error) (response code 404)`

Commit: 738fbc6

**Comment by kwolekr** [comment]
This isn't a problem with the engine, but rather the Minetest website.

**Comment by est31** [comment]
We have to decide whether to abandon mmdb, or whether to fix the website. We shouldn't release a version of minetest though that supports mmdb when the website doesn't work, so adding the blocker tag.

**Comment by kwolekr** [comment]
Why does it need to be abandoned?  Maybe the tab can be hidden if the server isn't available.
FWIW the moddb existed for several versions now and it's broken for everybody, not just 0.4.12-dev users.  This is purely an operational issue.  I don't see why it's a blocker.

**Comment by kwolekr** [comment]
Okay, we'll just add an error message on the UI if the MMDB is down.  This should suffice.

**Comment by est31** [comment]
Agreed

**Comment by est31** [comment]
Disabled mmdb in d565ce95395ec514d48b86910ae333bd5bfaa951
