### ISSUE TITLE
Segmentation fault while joining server, little to no output in console/debug.txt

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#3047]
After both git pulling in my normal directory and then deleting it and re-cloning, Minetest seg faults while on the loading screen. Nothing relevant shows up in the console or debug.txt.

Console output:

`mint@mint ~/minetest/bin $ ./minetest
Automatically selecting world at [/home/mint/minetest/bin/../worlds/test]
Segmentation fault
mint@mint ~/minetest/bin $ `

Also, VanessaE reports nothing in the console as well, while her debug.txt reads as follows:

http://pastebin.com/GJwkJTvB

**Comment by kilbith** [comment]
Yep, I confirm this. I'm up-to-date with HEAD and I experienced lastly some random freeze on joining servers.

Here's a GDB backtrace that I caught : 

```
[New Thread 0x7fffe2cef700 (LWP 3245)]
[New Thread 0x7fffe3cf1700 (LWP 3244)]
[New Thread 0x7fffe8f86700 (LWP 3243)]
[New Thread 0x7fffe3df2700 (LWP 3242)]

Program received signal SIGSEGV, Segmentation fault.
0x000000000078a2e6 in Map::timerUpdate(float, float, unsigned int, std::vector<irr::core::vector3d<short>, std::allocator<irr::core::vector3d<short> > >*) ()
```

Commit's troublemaker is https://github.com/minetest/minetest/commit/a8e238ed06ee8285ed4459e9deda3117419837f6

**Comment by VanessaE** [comment]
Both Wayward and I were connecting to the same server (stormchaser3000's "skyblock server" as the public list calls it).

While the client segfaulted for Wayward, it worked for me.  Client is at commit a8e238ed06ee8285ed4459e9deda3117419837f6 in my case.

**Comment by celeron55** [comment]
When connecting to said server, using valgrind/memcheck:

	==27383== Invalid read of size 8
	==27383==    at 0x998B61: Map::timerUpdate(float, float, unsigned int, std::vector<irr::core::vector3d<short>, std::allocator<irr::core::vector3d<short> > >*) (map.cpp:1503)
	==27383==    by 0x8295F8: Client::step(float) (client.cpp:426)
	==27383==    by 0x8F2491: Game::getServerContent(bool*) (game.cpp:2290)
	==27383==    by 0x8F0BE5: Game::createClient(std::string const&, std::string const&, std::string*, unsigned short) (game.cpp:2008)
	==27383==    by 0x8EF30E: Game::startup(bool*, bool, InputHandler*, irr::IrrlichtDevice*, std::string const&, std::string const&, std::string const&, std::string*, unsigned short, std::string&, bool*, ChatBackend*, SubgameSpec const&, bool) (game.cpp:1743)
	==27383==    by 0x8FD011: the_game(bool*, bool, InputHandler*, irr::IrrlichtDevice*, std::string const&, std::string const&, std::string const&, std::string const&, unsigned short, std::string&, ChatBackend&, bool*, SubgameSpec const&, bool) (game.cpp:4352)
	==27383==    by 0x6DFF1E: ClientLauncher::run(GameParams&, Settings const&) (clientlauncher.cpp:254)
	==27383==    by 0x98C6C8: main (main.cpp:236)
	==27383==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
	==27383== 
	==27383== 
	==27383== Process terminating with default action of signal 11 (SIGSEGV)
	==27383==  Access not within mapped region at address 0x8
	==27383==    at 0x998B61: Map::timerUpdate(float, float, unsigned int, std::vector<irr::core::vector3d<short>, std::allocator<irr::core::vector3d<short> > >*) (map.cpp:1503)
	==27383==    by 0x8295F8: Client::step(float) (client.cpp:426)
	==27383==    by 0x8F2491: Game::getServerContent(bool*) (game.cpp:2290)
	==27383==    by 0x8F0BE5: Game::createClient(std::string const&, std::string const&, std::string*, unsigned short) (game.cpp:2008)
	==27383==    by 0x8EF30E: Game::startup(bool*, bool, InputHandler*, irr::IrrlichtDevice*, std::string const&, std::string const&, std::string const&, std::string*, unsigned short, std::string&, bool*, ChatBackend*, SubgameSpec const&, bool) (game.cpp:1743)
	==27383==    by 0x8FD011: the_game(bool*, bool, InputHandler*, irr::IrrlichtDevice*, std::string const&, std::string const&, std::string const&, std::string const&, unsigned short, std::string&, ChatBackend&, bool*, SubgameSpec const&, bool) (game.cpp:4352)
	==27383==    by 0x6DFF1E: ClientLauncher::run(GameParams&, Settings const&) (clientlauncher.cpp:254)
	==27383==    by 0x98C6C8: main (main.cpp:236)
	==27383==  If you believe this happened as a result of a stack
	==27383==  overflow in your program's main thread (unlikely but
	==27383==  possible), you can try to increase the size of the
	==27383==  main thread stack using the --main-stacksize= flag.
	==27383==  The main thread stack size used in this run was 8388608.

**Comment by est31** [comment]
I had connected to that same server, with my change, back then when it still was a pr, it did work.

**Comment by est31** [comment]
Clearly a blocker, as multiple people report it, and they even point to a location.

**Comment by celeron55** [comment]
Also, this is obviously caused by the mapblock unloading change, in case someone didn't realize yet.

**Comment by celeron55** [comment]
This probably fixes it:

	diff --git a/src/map.cpp b/src/map.cpp
	index 38a700e..76a558d 100644
	--- a/src/map.cpp
	+++ b/src/map.cpp
	@@ -1499,8 +1499,8 @@ void Map::timerUpdate(float dtime, float unload_timeout, u32 max_loaded_blocks,
		            }
		            block_count_all = mapblock_queue.size();
		            // Delete old blocks, and blocks over the limit from the memory
	-               while (mapblock_queue.size() > max_loaded_blocks
	-                               || mapblock_queue.top().block->getUsageTimer() > unload_timeout) {
	+               while (!mapblock_queue.empty() && (mapblock_queue.size() > max_loaded_blocks
	+                               || mapblock_queue.top().block->getUsageTimer() > unload_timeout)) {
		                    TimeOrderedMapBlock b = mapblock_queue.top();
		                    mapblock_queue.pop();

**Comment by est31** [comment]
@celeron55 :+1:

**Comment by celeron55** [comment]
Pushed as def274a583909a695580509028bd2f393b9c5cf9.
