### ISSUE TITLE
Inventory Replace Bug

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#3048]
http://youtu.be/EN_G2xtkj9Q

~~0:03 ... Disappeared first item in player inventory.~~ my misunderstand.
0:10 ... Creative inventory and player inventory items are swapped.

**Comment by BlockMen** [comment]
Might be a bug in minetest_game, or can someone confirm that this happens with other detached inventories aswell?

**Comment by Rui914** [comment]
@BlockMen 
Perhaps, secound bug is allow_put bug.

**Comment by est31** [comment]
It might be a regression from one of my inventory changes.

**Comment by Rui914** [comment]
Shall I check old version?

**Comment by est31** [comment]
Can you test commit 3ae8b92be6e527054a3f291dee995230528141ca
and then test commit 7bbb9b066a8cc079512ddd3e6b32475309f49fca

**Comment by Rui914** [comment]
@est31 
I will check them.
I'm compiling now.

**Comment by Rui914** [comment]
Old version(3ae8b92):
Disappeared bug: none
Swapped bug: none

**Comment by Rui914** [comment]
I completed check.

**Comment by est31** [comment]
Can you again write a list of steps what to do in the description?

**Comment by est31** [comment]
We shouldn't release a version with this obvious bug.

**Comment by Rui914** [comment]
1. While holding item and click creative inventory.
2. Put item from creative inventory to player inventory.
3. Then, Selected item by 1 in creative inventory contains.

**Comment by Rui914** [comment]
1. Hold item in creative inventory.
2. Put item for creative inventory.
3. Then, creative inventory contains is replaced.

Also, both seems similar in case of creative inventory.

**Comment by est31** [comment]
Fixed by commit 1fadf7f21eb5fd7a09037d92f87cd0154e9306c1
