### ISSUE TITLE
Shutdown progress bar not rendered if inventory is open

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3050]
1. open inventory
2. shut down minetest by pressing the close button
3. the "shutting down" text will be drawn onto the inventory, without an actual progress bar

![shutdownbug](https://cloud.githubusercontent.com/assets/8872119/9256720/6787764e-41f1-11e5-97d8-82521af46b1f.png)

**Comment by Rui914** [comment]
Also, on_receive_fields doesn't receive fields.quit.

**Comment by paramat** [comment]
What is 'the close button'? I thought exiting menu was only possible in pause menu?

**Comment by red-001** [comment]
@paramat the window manager close button
