### ISSUE TITLE
Mainmenu lua errors include "Runtime error from mod '??'"

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3059]
create an error in mainmenu lua, you'll get error messages like:

```
ERROR[main]: MAINMENU ERROR: Runtime error from mod '??' in callback step():
```

Regression since 2b04ab874d75711bc021a0cd8dc7fca68f4e6929

**Comment by kwolekr** [comment]
Huh?  Does it not show the backtrace or something?
Otherwise it seems fine to me.

**Comment by est31** [comment]
It does show a backtrace, but mainmenu isn't moddable. Error messages shouldn't include the "from mod" part.

**Comment by kwolekr** [comment]
That is so nitpicky.  If you'd like to fix it, go ahead, but I'm not spending the time :p

**Comment by est31** [comment]
Therefore, low priority label.
