### ISSUE TITLE
Option for --mods <modlist.txt> at commandline

### ISSUE THREAD

**Issue by FreeLikeGNU** [minetest/minetest#3065]
I would really appreciate a way to specify additional mods for a subgame on the command line to run minetest like we already can for --world and --gameid.  For instance

./bin/minetestserver --gameid carbone-ng --world carbone-ng --mods extramods.txt --port 30020

contents of extramods.txt would be mod ids or paths?  I dont know what would make more sense.

Thank you for you consideration!

**Comment by PilzAdam** [comment]
Using a world with a different sets of mods may lead to a lot of unkown items / nodes / entities. Is providing an easy way to do so really good?

**Comment by FreeLikeGNU** [comment]
It is good in my use case starting a minetest server on a headless vps.  Having a world startup without mods (such as a mapgen mod) invoked is the problem and is precisely why I want this feature to include mods before the world folder is created.   Currently I'm having to put additional mods in my subgame mod folder, but this makes it messy for keep mods and subgames updated.    Subgame authors, such as Calinou also recommend putting mods in ./minetest/mods and not using the ./minetest/games/subgame/mods folder.

**Comment by est31** [comment]
This should perhaps better be done by some default mods setting.

**Comment by FreeLikeGNU** [comment]
@est31 I'm not sure I understand?  If I am running multiple servers using different subgame and additional mods settings how would I use a default mods setting?

**Comment by est31** [comment]
@FreeLikeGNU you want to include mods before the world folder is created, so you only need it for world creation? Surely you don't want to create worlds "in parallel"? Als, you can use different minetest.conf files, I suggest you should do this either way.

**Comment by FreeLikeGNU** [comment]
If this request is unreasonable, I'll just symlink mods from my mod folder into the subgames mod folder as needed. I don't know what worlds in parallel involves.   
I would just like to 

`$ screen minetestserver --gameid carbone-ng --world carbone-ng --port 30000`
and
`$ screen minetestserver --gameid carbone-ng --world carbone-ng-with-cheese --modlist cheesey_addon_mods.conf --port 30010`

I do not see where I can set what mods to enable in a config such as in in https://github.com/minetest/minetest/blob/master/minetest.conf.example

**Comment by est31** [comment]
There is the world.mt file, with a list of enabled mods.

**Comment by FreeLikeGNU** [comment]
@est31 understood, however, my problem with world.mt is that it is generated only after I start the world for the first time.  I do like that the world.mt keeps a list of enable mods for each world.

**Comment by est31** [comment]
Well, yes, that's a missing feature. I've just said that we should solve the issue with the .conf method before modifying cmd line params.

**Comment by FreeLikeGNU** [comment]
@est31 the issue with .conf not having a mods parameter?  Please clarify.  I'm not sure I want to mess with a subgames minetest.conf as this is something that will be updated on a git pull/push.   Putting on the command line to reference a config file outside of the subgame would keep the subgame folder clean and make testing/contribution much easier, IMHO.

**Comment by FreeLikeGNU** [comment]
@PilzAdam if you are worried about adding and removing mods from a world being too easy, why are we able to do this from the GUI?!  I only ask for the kind of functionality that is present in the GUI to be accessible from the command line.

**Comment by PilzAdam** [comment]
@FreeLikeGNU good point.

**Comment by paramat** [comment]
Any comments? Seems to be some confusion here.
Anyone interested in coding any practical idea here? If not closing in 1 month.

**Comment by paramat** [comment]
> Well, yes, that's a missing feature. I've just said that we should solve the issue with the .conf method before modifying cmd line params.

Implementation may need to differ from the request.

**Comment by red-001** [comment]
while this would be pretty trivial to implement not sure if it's worth adding yet another command line switch.

**Comment by paramat** [comment]
Any core dev interest?

**Comment by paramat** [comment]
No core dev support for 2 years and seems controversial. Core devs feel free to reopen if you support.
