### ISSUE TITLE
tileable_{horizontal,vertical} flags cause fps decrease

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3073]
Assume the following tile definition:

    tiles = {
        name = "somenode.png",
        tileable_horizontal = true,
        tileable_vertical = true
    }

This leads to the following effect:

![screenshot_20150817_204453](https://cloud.githubusercontent.com/assets/611377/9313034/da562b0c-4520-11e5-8319-de9cfb8f3857.png)
![screenshot_20150817_204503](https://cloud.githubusercontent.com/assets/611377/9313035/da5658b6-4520-11e5-85c2-35c7cd29c4cd.png)

Note that the textures are slightly moved, like they wrap around (at the top and bottom).

Now it seems that I can fix that by using:

    tiles = {
        name = "somenode.png",
        tileable_horizontal = false,
        tileable_vertical = false
    }

But that kills performance, from easily 60fps down to ~10fps if I'm lucky.

I can remember seeing a ticket related to this, but I'm not finding it right now.

**Comment by PilzAdam** [comment]
AFAIK these attributes were added to fix this bug.

**Comment by est31** [comment]
Agree with @PilzAdam, see #2815.
dirt side textures should be horizontally tileable, but not vertically.

The fact that FPS goes down might be a new bug.

**Comment by kilbith** [comment]
The patch is here for some existing nodes : https://github.com/minetest/minetest_game/pull/626

... but surprisingly not merged yet.

**Comment by RobertZenz** [comment]
@est31 If I set 

    tiles = {
        name = "somenode.png",
        tileable_horizontal = true,
        tileable_vertical = false
    }

The FPS is also down to 10fps...so, yeah, then that is the bug here.

**Comment by paramat** [comment]
@RealBadAngel

**Comment by RealBadAngel** [comment]
https://github.com/minetest/minetest/pull/3079

**Comment by RobertZenz** [comment]
@RealBadAngel Doesn't fix the FPS drop for me, it's still there after applying these changes.

**Comment by RealBadAngel** [comment]
@RobertZenz can you join irc? i would like to talk and find a solution

**Comment by est31** [comment]
Fixed with commit 8b8d17b22b5853c7d32bdb8b369f4523f6c57b95
