### ISSUE TITLE
client side gui_scaling setting needed for servers

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#3078]
The gui_scaling setting in minetest.conf works as planned on a singleplayer game and of course on formspec on both client and server side games, but...  if I wish to scale up HUD items to suit then I am only able to read server-side gui_scaling instead of the induvidual players setting...

Could you make it possible to read clientside gui_scaling or even add a new variable for mods to use this information...

**Comment by PilzAdam** [comment]
What is your use case for this? The setting is supposed to be set and used by the client; the server shouldn't care about it.

**Comment by est31** [comment]
@tenplus1 Do you know there is also a hud scaling setting?

**Comment by tenplus1** [comment]
Not so much for the server itself but players connected to servers where the gui_scaling only reads the server setting saved in minetest.conf instead of the players client-side setting...

**Comment by PilzAdam** [comment]
gui_scaling (like gamma or font size) depends on the screen size and the resolution on the client; there is no best value for these and players should be able to configure this on their own independently from what server they are playing on.

**Comment by est31** [comment]
@tenplus1 what do you actually want to resize/scale?

**Comment by rubenwardy** [comment]
@PilzAdam @tenplus1 is saying that currently gui_scaling is controlled by the server, but it should be controlled by the client.

**Comment by tenplus1** [comment]
exactly rubenwardy, I want a player to connect to a server which can detect their own gui_scaling value (and not the server's own) and use that to scale up health.hunger.air.armor bars on screen...

**Comment by ShadowNinja** [comment]
@tenplus1: Settings like `gui_scaling` are supposed to do that for you, but it's currently disabled for the HUD.  It's positioning system means that things can overlap if scaled.

**Comment by rubenwardy** [comment]
Doesn't hud_scaling do this for you?

**Comment by tenplus1** [comment]
hud_scaling is built into the mod itself and yes, works fine but I've tweaked the hudbars mod to read gui_scaling and scale accordingly for each player's gui_scaling without overlap...

**Comment by rubenwardy** [comment]
server mods shouldn't care about client scales, the hud system should be able to handle this IMO

**Comment by paramat** [comment]
:-1:
