### ISSUE TITLE
Black menu screen

### ISSUE THREAD

**Issue by wilkgr76** [minetest/minetest#3080]
Using the 0.4.12.11 build, I cannot open the menu. If I launch minetest, once the progress bar is full, the screen turns black. I am using Android Kitkat (4.4.2) on P716 (LG Optimus L7 II Dual). Here's what debug.txt says:

```lua
-------------
  Separator  
-------------

Automatically selecting world at [/storage/emulated/0/Minetest/worlds/singleplayerworld]
Irrlicht log: Irrlicht Engine version 1.9.0
Irrlicht log: EGL version: 1.400000
Irrlicht log: Using renderer: OpenGL ES-CM 1.1 V@6.0 AU@04.01.01.42.002 (CL@)
Irrlicht log: Qualcomm
Irrlicht log: GL_EXT_debug_marker GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_APPLE_texture_2D_limited_npot GL_ARB_vertex_buffer_object GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_OES_blend_equation_separate GL_OES_blend_func_separate GL_OES_blend_subtract GL_OES_compressed_ETC1_RGB8_texture GL_OES_compressed_paletted_texture GL_OES_depth_texture GL_OES_depth24 GL_OES_draw_texture GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_framebuffer_object GL_OES_matrix_palette GL_OES_packed_depth_stencil GL_OES_point_size_array GL_OES_point_sprite GL_OES_read_format GL_OES_rgb8_rgba8 GL_OES_stencil_wrap GL_OES_texture_cube_map GL_OES_texture_env_crossbar GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_texture_mirrored_repeat GL_QCOM_binning_control GL_QCOM_extended_get GL_QCOM_tiled_rendering GL_AMD_compressed_3DC_texture 
Irrlicht log: GL_INVALID_ENUM
Irrlicht log: Could not bind Texture
19:48:10: ERROR[main]: Shutting down minetest.
```

**Comment by Wayward1** [comment]
I can't reproduce this.

**Comment by wilkgr76** [comment]
@Wayward1 I dunno, this might have to do with the phone, it is a budget phone, and running Android KitKat. I'm not sure about the minimum requirements of minetest, because I have a 1.00 Ghz processor.

**Comment by Wayward1** [comment]
It should be. I've played on a tablet with a 1GHz processor and 1GB RAM without any problems. Maybe try <a href="https://jenkins.unix-experience.fr/job/minetest-android-OfficialRepository-RollingRelease/lastBuild/artifact/build/android/bin/Minetest-debug.apk ">this</a> apk, which is the latest build, and see if the problem still exists.

**Comment by wilkgr76** [comment]
Thanks Wayward1 - I'll try that, then report back :)

**Comment by wilkgr76** [comment]
@Wayward1 Doesn't work

**Comment by 4aiman** [comment]
I found this issue to appear when the assets unpacking went wrong or after updating the apk.
Clearing the game's data folder usually helps (one can safely leave the worlds folder in order to not to loose the world there are and the game progress).

Sometimes it takes up to 3 times of "deletion"  to launch the game normally.

ARCHOS GamePad 2 (4*1.6GHz RC CPU + 2Gb DDR3 RAM + Mali-400 MP4) here.
The same can be reproduced on a "china-phone" (1*1.2GHz MTK CPU + 512Mb RAM + Mali-400).

So, I doubt that have smth to do with a particular phone but rather is a consequence of some init error.

PS: There *are* some phones like Zenphone which have issues related to the device itself, but this issue is not one of those ;)

**Comment by MoNTE48** [comment]
@4aiman , Asus Zenfone 2 and Samsung Galaxy S4, to be more precise.

**Comment by wilkgr76** [comment]
Ok, thanks everyone for your help! :+1:

**Comment by 4aiman** [comment]
Actually, not only Zen(f?ph)one, but Galaxy Edge 4/5, HTC One too...

**Comment by Wayward1** [comment]
No pronlem :)
