### ISSUE TITLE
Spawning at 0,0,0 even with static spawnpoint set.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#3083]
Occasionally (more often on server join or on a laggy server) the player (re)spawns at 0,0,0 rather than the static spawnpoint. This is often underground and sometimes confuses new players.

**Comment by Wayward1** [comment]
This should have been fixed by <a href="https://github.com/minetest/minetest/commit/470de10de3a4d864ce2808bb3778cf9abfbc560e">this</a> commit

**Comment by nanepiwo** [comment]
OK, closing.

**Comment by Fixer-007** [comment]
not fixed
