### ISSUE TITLE
safeWriteToFile() probably broken on Linux

### ISSUE THREAD

**Issue by celeron55** [minetest/minetest#3084]
On #minetest-dev today it became obvious that on Linux the files being written by safeWriteToFile() are being seen ending up truncated in case of hard shutdown.

Commit 5f1f1151d3a9c113902630adc16cc3f4845da7ba probably breaks the safe file writing on Linux. It enables the remove() call for the file being overwritten by the rename(), which was only intended to be done on Windows and is not needed on Linux.

Does someone have any comments about this or should I just go ahead and add back the _WIN32 conditional for the remove()?

**Comment by est31** [comment]
Related to #2663

**Comment by celeron55** [comment]
I will be merging this soon. It is the fix I described: https://gist.github.com/celeron55/27245358fb5cdcc90c3e

**Comment by celeron55** [comment]
64c060e1f2d94d8277246d8cdd8a886010564770

**Comment by 0-afflatus** [comment]
Thank you. I'm running a server on some dodgy old hardware and this will save me considerable grief.
