### ISSUE TITLE
Formspecs not shown after closing die screen with spacebar

### ISSUE THREAD

**Issue by jogag** [minetest/minetest#3086]
Link to the issue on the forum: [click here](https://forum.minetest.net/viewtopic.php?f=6&t=10573)

Shortly, if you press spacebar to close the die screen, formspecs shown in functions registered with minetest.register_on_dieplayer() **won't show**.

**Comment by paramat** [comment]
We had some changes to the death formspec recently, still occuring?

**Comment by pauloue** [comment]
Formspecs shown `on_dieplayer` are never shown and doing so makes no sense becuase the formspec will be overridden by the death formspec (or it will override the death formspec and you won't be able to respawn).
