### ISSUE TITLE
Add the originally pointed at node to node_definition.after_place()

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3091]
We can register a callback for after a node is placed in the node definition. One of the parameters of this callback is `pointed_thing` which is returning the position of the node that is to be placed and that node below it.

It would be extremely interesting if we also would get the originally pointed at node. An illustration.

    P       n
    P     o n
    n n n n n
    n n n n n

`P` is the player, `n` is a node and `o` is the currently highlighted node. If the player now places a node, we will get the following `x` nodes in `pointed_thing`.

    P       n
    P   x n n
    n n x n n
    n n n n n

What I'm proposing is to also get the `o` node.

    P       n
    P   x x n
    n n x n n
    n n n n n

This would allow us to know better what the player did, what node was originally pointed at which might yield different behavior.

**Comment by ShadowNinja** [comment]
This is how pointed_thing works now.  `pointed_thing.under` is whatever you were pointing at when you placed the node.

**Comment by paramat** [comment]
@RobertZenz ^

**Comment by paramat** [comment]
@RobertZenz i guess you would like information for all 3 nodes?

**Comment by RobertZenz** [comment]
Based on my illustration, I guess so.

**Comment by ShadowNinja** [comment]
If you want the nice that's below the placed node on the y axis you can just subtract 1 from the y coordinate of the above node, so you can get all three.
