### ISSUE TITLE
Allow to register a callback in the node_definition for before the node is placed.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3092]
Currently we can register a callback in the node definition for after a node has been placed (`after_place_node`). What would be extremely interesting is to have the possibility to register a callback for before the node is placed. That would allow us to swap the node before it is actually put into the world, which is much better than swapping it afterwards (depending on the connection the node might be quite long visible before it is replaced in the `after_place_node` callback).

The function I'm proposing is looking the same as `after_place_node`:

```
before_place_node = function(pos, placer, itemstack, pointed_thing)
```

The function would return two values, first a boolean if the node should be placed at all, and second the (replacement) node to be placed. Example.

```
before_place_node = function(pos, placer, itemstack, pointed_thing)
    return true, {
        name = "replacement:node",
        param1 = something,
        param2 = something
    }
end
```

This would allow us to replace a node when it is placed without the original node showing up.

**Comment by nanepiwo** [comment]
But the client would have already placed the node on its side, so not much will be gained.

**Comment by ShadowNinja** [comment]
You can use `on_place` for this (although it isn't quite as clean).
@nanepiwo: You can set `node_placement_prediction` to fix that.

**Comment by paramat** [comment]
Possible with `on_place` and author has left MT.
