### ISSUE TITLE
Allow to define different meshes for wallmounted nodes.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3095]
Currently nodes that are wallmounted do support different nodeboxes depending on the wallmounted value. It would be very interesting if we would be able to also define different meshes depending on the wallmounted value.

```
mesh = {
    type = "wallmounted",
    wall_top = "mesh_normal.obj",
    wall_bottom = "mesh_upsidedown.obj",
    wall_side = "mesh_side.obj"
}
```

For example this would be useful if we want to use a mesh for torches.

**Comment by paramat** [comment]
Any support or comments? Anyone interested in coding this sometime? If not closing in 1 month.
Author has left MT.

**Comment by paramat** [comment]
Old issue with no support.
