### ISSUE TITLE
Allow to define some sort of status/overlay that allows to overlay the node with a texture.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3096]
It would be very nice if we'd be able to attach a status or overlay to a node and overlay it with a texture, nodebox or mesh.

The following concept, nodes can have a status in addition to the params it already has. A status/overlay might be defined the same or very similar to a node, at least it should have most properties (like `light_source`). Maybe we can even use another node as overlay, would need testing. This would allow us to define fire as a node and attach it to a burning node, like the following:

```
minetest.register_node("mod:fire", {
    description = "Fire",
    drawtype = "firelike",
    drop = "",
    light_source = 10,
    name = "fire",
    tiles = { Some animated stuff }
})

minetest.set_node_overlay(pos, c_fire)
```

The node at the given position will be drawn with the fire node overlayed. To avoid drawing issues this would require some "magic", obviously.

This would allow us to get "real" burning nodes. Additionally this would also allow me and other modders to fix #3074 ourselves, because we could then decide what nodes let water pass and which do not, we could then simply overlay it with a source node.

**Comment by est31** [comment]
This is inside the general "give nodes a state" department.

**Comment by RobertZenz** [comment]
Going slightly overboard with this idea, it might be the absolute uber-feature if we could have an unlimited amount of nodes occupying the same slot.

**Comment by est31** [comment]
Its against the Voxel principle, IMO.

**Comment by RobertZenz** [comment]
I could not care less if it is against any abstract principle or philosophy, I only care about it because I've need for it and so the only question that matters for me is "Are you gonna support that in your engine?". If it is not the goal of your engine, then that is something I can live with...though, I'll obviously neck you about it from time to time because I still want it (and this is definitely outside of the scope that I could change in Minetest).

To be a little bit less snarky about it, yeah, sure, quite deep fundamental changes. But I'd consider it worth it. There are a lot of interesting applications for this: Water sources on/through other nodes, fruits mixed into leaves, fire, easily doable roots of trees, other decorations, basically everything that would require you to know about some node would suddenly become super easy.

**Comment by paramat** [comment]
Such a node could still be considered a single node (and probably should be), just one with overlayed textures.

**Comment by est31** [comment]
@RobertZenz you can still freely define a tree_with_fire or dirt_with_root node, or, if you want, chair_with_rooftop_shingles_left, so its possible already now.

**Comment by RobertZenz** [comment]
@est31 Yeah, I'm aware that I could combine these "manually", but for that I need to know about the node, instead of say simply grabbing any node with a certain group and attaching/overlaying it with it.

**Comment by paramat** [comment]
Any comments? Anyone interested in coding this sometime? If not closing in 1 month.
Author has left MT.

**Comment by paramat** [comment]
Old issue with no support and fairly redundant.
