### ISSUE TITLE
Animated textures should be separately synced depending on a flag.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3097]
Currently *all* animated textures are either globally synchronized by using the `desynchronize_mapblock_texture_animation` setting or they are not.

However, it is necessary to have such a flag on a node level, as there are textures that need to stay in sync, like fluids, and there are textures which should *not* stay in sync, like the textures of torches. It would be really good if we would get an additional flag in the `tiles` definition to set the synchronized mode for that texture.

	tiles = {
		{
			name = texture_animated,
			animation = {
				aspect_h = 32,
				aspect_w = 32,
				length = 3.0,
				type = "vertical_frames"
			},
			synchronization = "globally|none|random|"
		}
	}

The flags for it as I propose it:

 * globally: The animated texture is globally kept in sync, same as `desynchronize_mapblock_texture_animation` set to false.
 * none: The animated textures are not kept in sync, same as `desynchronize_mapblock_texture_animation` set to true.
 * random: Upon load of the block, a random frame is picked as start, otherwise same as none.

**Comment by PilzAdam** [comment]
Whats your usecase of `random`?

Currently all nodes in a mapblock are in sync; do you want to have that changed with `none`?

**Comment by RobertZenz** [comment]
'random' was just an idea to make sure that animations are not in sync after the block has been loaded (torches again). I guessed at least that animations will always start at frame 1, so if a block is loaded all animations will start at frame 1, `random` should choose a random frame so that they freshly loaded nodes can not be in sync.

Exactly, I do not want them to be synchronized if `none` is specified. If they sync up at some time, fine, but they should not on purpose.

**Comment by PilzAdam** [comment]
That is currently not possible; all torches are the same Irrlicht material and animation updates can only be done on a complete mapblock mesh. What you ask is to make each torch it's on material, which might kill performance.

**Comment by RobertZenz** [comment]
I could swear that I saw something different during my testing...well, if it is not possible than it is not possible.

**Comment by paramat** [comment]
Closing as the random flag feature is impossible.
