### ISSUE TITLE
Temporary grant or revoke privileges

### ISSUE THREAD

**Issue by Ombridride** [minetest/minetest#3099]
Im thinking of this feature since a little time...

I grant privileges to players for screenshots/moderators tasks/events/etc... and i must write the names, and the older privileges on a pad. 
But, after the screenshots/moderators tasks/events/etc... i need to revokes all privileges granted...

#### That's an horrible concepts
Because :
- this takes a long time,
- we can forget privileges to grant/revoke (administrators and moderators are humans after all...)
- if we miss a privileges to revoke, the following errors can be dramatic
- if we forget to re-add a privilege to a player, depend on the privilege, but maybe he can't play anymore...
- many other reasons i certainly don't think at this moment...

So, my issue is about add a ...

#### New revoke and grant system
This is a simple solution to implement a great way to dothe boring tasks i said earlier.

Add a /grant_temp and /revoke_temp command !
Like this : 
/grant_temp "name" "privilege" "time"
/revoke_temp "name" "privilege" "time"

Or simply, re-used the actual grant/revoke command line, and add a third argument, by default, this argument should be "infinite"
/grant "name" "privilege" "time"
/revoke "name" "privilege" "time"

Thank you for reading :)

**Comment by PilzAdam** [comment]
This can be done via a mod.

**Comment by est31** [comment]
Agreed, this isn't something the engine should do, as its perfectly doable with a mod.

**Comment by rubenwardy** [comment]
yeah, this is a mod kind of thing.

**Comment by ShadowNinja** [comment]
I actually did this a while ago.  Here's a link to an updated (but untested) version: http://sprunge.us/NjSa
