### ISSUE TITLE
Movement bug: You get into a narrow space where you don't get out.

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3100]
![movement-bug](https://cloud.githubusercontent.com/assets/8872119/9430363/8bebd440-49f2-11e5-82e5-d41502a29e2d.png)
Build such a structure, then walk in. You will get inside, but will be trapped onto one of the border nodes, not being abled to leave it. The snow nodes have a height of .25 BS, the player has a height of 1.8 BS, so it is true that its too much. Therefore, the bug is here that you actually get in.

Sneaking gets you out again.

Discovered this with pines.

**Comment by nanepiwo** [comment]
Duplicate of #1229.

**Comment by paramat** [comment]
Luckily there is usually no snow under pines, although there is around the edge (in mgv5/v7), so i may still have to raise them as i intended for them to always be passable underneath, will test.

**Comment by est31** [comment]
Seems it indeed is a dupe of #1299.
