### ISSUE TITLE
Android - Glitches when joining a server.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#3102]
There are frequent messages that Minetest doesn't respond. Also, locking the screen will cause the Minetest loading screen to be black until it reaches the next stage of loading.

**Comment by nanepiwo** [comment]
Second part: #2409

**Comment by ShadowNinja** [comment]
Issue two is fixed by #2999.

**Comment by MoNTE48** [comment]
Some news? My commit corrects this fully. Perhaps it should merge?

**Comment by est31** [comment]
@ShadowNinja have you tested it? Then you can squash and merge the xml changing commits. Idk about the setting commit, probably its useful too.

**Comment by sapier** [comment]
imho the default settings changes shouldn't be merged unless there's way more then one person where this is necessary.
Those changes are extremely hardware dependent and everyone feels different about "are 20 fps enough, is it 50 or is only 100 enough"

**Comment by paramat** [comment]
The fix for issue 2 is in #5759 and is not applied yet. That issue can replace issue 2 here.
Issue 1 is too vague to be useful, might be connecting to a heavy server.
