### ISSUE TITLE
[Request] LuaSocket or cURL for Mods

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#3103]
```
minetest.curl("http://aaa.bbb")
minetest.socket("http://aaa.bbb")
```
These are useful for mods.
Also, we don't have to think compatibility of os if available this feature by engine.

**Comment by rubenwardy** [comment]
IId llike this, it makes some features a lot easier. Now we have mod security, the pr for this can be rebased and made more secure.

**Comment by crazyR14** [comment]
This does make sense. especially as there is a already few good mods that already make use of curl and sockets.... not to mension some of the server owners that have there own mods for there various individual needs etc  +1

**Comment by indriApollo** [comment]
:+1:

**Comment by ShadowNinja** [comment]
#1869

**Comment by arpruss** [comment]
Instead of minetest.socket(), I would prefer to keep the standard luasocket interface, as this would allow mod makers to use other lua code that uses luasocket, without changing it.

**Comment by arpruss** [comment]
Why did this get closed? I know that HTTPFetchRequest() was added, but that isn't the same as socket support. Socket support has other use cases, for instance supporting the Minecraft PI API as in my Raspberry Jam Mod.
