### ISSUE TITLE
fgettext issues

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#3105]
These are fairly minor, but they're easy to fix:
1. Only 9 insertions are supported. <sup>[1]</sup>
2. Escapes aren't  supported. <sup>[1]</sup>
3. The `fgettext`/`fgettext_ne` thing is (subjectively) ugly<sup>[2]</sup>.  `fgettext`/`efgettext` or so would be better.

[1]: Intllib has an implementation of replacements that avoids these issues: https://github.com/kaeza/minetest-intllib/blob/master/init.lua#L38
[2]: Because usually a postfix on a function means that it adds something, not removes it.

**Comment by Wuzzy2** [comment]
Is this even a bug? This is more like a very-low priority missing feature (for devs-only, too). Also, after all these years, 9 insertions or more weren't needed in Minetest. Or pretty much any other game. In all my years as a translator for FOSS, I can't recall if any string needed 9 insertions or even more. So it's definitely extremely rare. And even if one day your hypothetical string needs that many inserts, your string is probably too large anyway and should probably be split.

The 3rd one is completely subjective. Who cares?

I'm not sure what kind of escapes you mean. Which characters need escaping and why?

This "bug" is not really a bug and it sounds like a possible close.
