### ISSUE TITLE
Allow `register_on_dignode` to veto the receiving of the dropped items.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3107]
`register_on_dignode` should be able to veto the receiving of the dropped items and should also be informed about them, like this:

```
minetest.register_on_dignode(function(pos, oldnode, digger, dropped_items)
    -- Do something on the dropped_items.

    -- Don't add the dropped items to the inventory of the player.
    return true
end)
```

`dropped_items` can be a simple table, like

```
{
    [1] = ItemStack or string,
    [2] = ItemStack or string
}
```

or some such.

That would greatly improve the possibilities to implement something like the [item_drop](https://github.com/PilzAdam/item_drop) mod  or a some sort of feedback with the dropped items when the block is mined.

**Comment by PilzAdam** [comment]
Either override `minetest.handle_node_drops` (like the itemdrop mod does) or override the node's `on_dig`.

**Comment by RobertZenz** [comment]
`node_definition.on_dig` doesn't seen to offer to suppress that the drops are added to the inventory.

And overriding `minetest.handle_node_drops` seems like a solution (why are you checking if the inventory contains a stack with these items?), but overriding this function doesn't seem to be compatible in any way if multiple mods would like to be notified about drops.

**Comment by PilzAdam** [comment]
The default `on_dig` handles drops, so if you override it nothing is dropped if you don't add it to your function.

```Lua
old_handle_node_drops = minetest.handle_node_drops
minetest.handle_node_drops = function()
    --...
    old_handle_node_drops()
end

**Comment by RobertZenz** [comment]
Okay, that's a possibility.

But what took me as odd is that this functionality can only be achieved by overriding a method. I would have expected that I can register myself to an event, just like everything else works in Minetest. Also I'd still argue that this should go into `on_dig`, as it makes sense to have it there (it is also analogue with `on_place`/`after_place_node` where you can veto that the itemstack is reduced).

**Comment by paramat** [comment]
Any comments? Anyone interested in coding this sometime? If not closing in 1 month.

**Comment by paramat** [comment]
Old issue with no support and can be done already.
