### ISSUE TITLE
Use desktop mouse behavior when connecting a USB/BT mouse to an Android device

### ISSUE THREAD

**Issue by ensonic** [minetest/minetest#3110]
connecting a usb/bt mouse and keyboard lets me play minetest almost like on a desktop. Except that the mouse behaves differently (double click to place and click-drag to lock around).

**Comment by sapier** [comment]
difficult to fix as touch control is mixed up to regular controls, guess controls would require a major refactoring for getting both work independently

**Comment by paramat** [comment]
And no-one is working on Android. Very low priority to work on a feature for a rare case of using a mouse for Android.
:-1:
