### ISSUE TITLE
Is mapgen silly ?

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#3122]
Look at this picture. Does the mapgen has drunk ? How can this be possible ?

mapgen: v6
fixed_map_seed: 2232334619595520844220622""

![capture d ecran de 2015-08-30 17-39-26](https://cloud.githubusercontent.com/assets/119752/9567998/2d07abb0-4f3e-11e5-90fa-e4430691cef3.png)

**Comment by kilbith** [comment]
I confirm those straight delimitations of biomes.

**Comment by paramat** [comment]
LOL.

**Comment by est31** [comment]
I guess if @paramat wants to reproduce, he'll need the coordinates of your screenshot as well.

**Comment by kwolekr** [comment]
I kinda doubt this is consistently happening.  Paramat changed the default biome parameters IIRC which would cause this exact scenario.  Re-open this issue if you believe it's a true bug.
