### ISSUE TITLE
Minimap isn't removed from HUD when disabled by server

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3126]
If the server disabled the minimap for a player but the player had already enabled it, the minimap is not hidden automatically.

How to reproduce:

* Start a server
* Connect as a player to this server
* Activate the minimap with this player
* Now call `player:minetest.hud_set_flags({minimap=false})` in Lua (replace `player` with the player object) (write a quick and dirty mod or use the `luacmd` mod)

What I expect: The minimap of the player is automatically hidden as soon it is disabled.
What actually happens: Nothing. The player is allowed to keep the minimap until F9 is pressed another time, after which it cannot be enabled again.

Seen in Minetest 0.4.13.

**Comment by est31** [comment]
Yeah, I see this happening from the code.

**Comment by est31** [comment]
0903190ba2ed2134c464f2efe694d7281ead1c09
