### ISSUE TITLE
can_place(pos, itemstack, placer, pointed_thing, param2) for nodedef

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3133]
I think we need a way to block node places which knows both the position of the placement, and the node's name.

Right now, you can achieve this _sort of_ by overriding on_place. But with that, you'll either have to do the placement yourself, which breaks things like logging, or, if you call minetest.item_place after your checks, you'll have to guess the actual position minetest.item_place put the item to (its not always [pointed_thing.above](https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L224-228)), and I don't want that we have to guarantee this placing behaviour doesn't change in future versions.

There are multiple ways of adding this functionality. A new callback for the nodedef, `can_place(pos, itemstack, placer, pointed_thing, param2)` is best I think, because if we add a position to on_place, we'll have to handle things like logging outside of it, and there would be no way of customizing the actually placed place.

This `can_place` callback would be called by minetest.item_place once it knows the position to place to, with according params.

See also https://github.com/tenplus1/protector/issues/3
my personal use case is similar, I want to forbid placing nodes with an "no-go-area" too close as well. Me and @tenplus1 would only need the pos and placer params, but perhaps the other ones might be useful for some people.

**Comment by HybridDog** [comment]
l already did a function to allow disabling nodes to be placed:
http://dev.minetest.net/User:Hybrid_Dog#minetest.on_place

**Comment by est31** [comment]
It still doesn't give you the position.

**Comment by HybridDog** [comment]
the position is pointed_thing.under if there's buildable_to, else pointed_thing.above, l think

**Comment by est31** [comment]
@HybridDog yes, I know, just read the description. The problem is that this might change in the future, and therefore its cleaner to have such an additional function.

**Comment by HybridDog** [comment]
>The problem is that this might change in the future, and therefore its cleaner to have such an additional function.

yes, l did a mod which disallows placing torches in water, l think it somehow also disallows opening doors with a torch in your hand
