### ISSUE TITLE
optional dependencies don't work correctly

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3136]
lt tells me that the mods can't be loaded because of missing dependencies but some of them are optional dependencies. (and the optional dependency which does not work is the last one in depends.txt)

> 2015-09-02 13:45:27: ERROR[Main]: mod "extinguisher" has unsatisfied dependencies:  "poisonivy"
> 2015-09-02 13:45:27: ERROR[Main]: mod "treecapitator" has unsatisfied dependencies:  "moretrees"
> 2015-09-02 13:45:27: ERROR[Main]: mod "bushes_classic" has unsatisfied dependencies:  "biome_lib"
> 2015-09-02 13:45:27: ERROR[Main]: mod "flowers_plus" has unsatisfied dependencies:  "biome_lib"
> 2015-09-02 13:45:27: ERROR[Main]: mod "poisonivy" has unsatisfied dependencies:  "biome_lib"
> 2015-09-02 13:45:27: ERROR[Main]: mod "seacoral" has unsatisfied dependencies:  "unifieddyes"
> 2015-09-02 13:45:27: ERROR[Main]: mod "sumpf" has unsatisfied dependencies:  "treecapitator"
> 2015-09-02 13:45:27: ERROR[Main]: mod "moretrees" has unsatisfied dependencies:  "plants_lib"
> 2015-09-02 13:45:27: ERROR[Main]: mod "special" has unsatisfied dependencies:  "moretrees"
> 2015-09-02 13:45:27: ERROR[Main]: The following mods could not be found: "plants_lib"

l updated plants_lib and didn't notice that biome_lib is in a separate repository, so l didn't install it.
Then, of course, moretrees, poisonivy, flowers_plus, … have missing dependencies (which aren't optional).
But it also didn't load treecapitator and sumpf. They have moretrees and treecapitator as optional dependency in depends.txt at the end:
https://github.com/HybridDog/treecapitator/blob/master/depends.txt
https://github.com/HybridDog/sumpf/blob/master/sumpf/depends.txt

So l guess you could reproduce it by installing sumpf and treecapitator with their dependencies and moretrees but without biome_lib.

**Comment by est31** [comment]
Can you give a configuration one can use to reproduce?

**Comment by HybridDog** [comment]
l updated plants_lib and didn't notice that biome_lib is in a separate repository, so l didn't install it.
Then, of course, moretrees, poisonivy, flowers_plus, … have missing dependencies (which aren't optional).
But it also didn't load treecapitator and sumpf. They have moretrees and treecapitator as optional dependency in depends.txt at the end:
https://github.com/HybridDog/treecapitator/blob/master/depends.txt
https://github.com/HybridDog/sumpf/blob/master/sumpf/depends.txt

So l guess you could reproduce it by installing sumpf and treecapitator with their dependencies and moretrees but without biome_lib.

**Comment by rubenwardy** [comment]
My guess is that they do work correctly, but Minetest prints misleading error messages.

**Comment by HybridDog** [comment]
>My guess is that they do work correctly, but Minetest prints misleading error messages.

No, the sumpf mod was disabled (l typed /mods and looked for its nodes in the creative inventory) although treecapitator is an optional dependency.

**Comment by HybridDog** [comment]
>My guess is that they do work correctly, but Minetest prints misleading error messages.

No, l just tested it, they weren't loaded.

**Comment by est31** [comment]
@HybridDog what makes you believe the issue got fixed?

**Comment by HybridDog** [comment]
as far as l know l'm the only one having this problem

**Comment by paramat** [comment]
@HybridDog ^

**Comment by paramat** [comment]
No response, can be re-opened if there is a bug.
