### ISSUE TITLE
pointing at nodes with thin selection boxes doesn't always work

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3137]
![l hope your browser supports apng](https://cloud.githubusercontent.com/assets/3192173/9633725/a6e30248-518e-11e5-8cb8-f9fc4a10721e.png)

**Comment by PilzAdam** [comment]
This happens with too small selection boxes. The step-width in the getPointedThing() should be modified.

**Comment by ShadowNinja** [comment]
@PilzAdam: That would just push the problem to smaller nodeboxes though, and it would degrade performance.  It would be better to do a proper ray trace so that you don't miss anything.

**Comment by BlockMen** [comment]
Seems to be still valid, reopening.

**Comment by beyondlimits** [comment]
http://www.academictutorials.com/graphics/graphics-raycasting.asp
