### ISSUE TITLE
Lighting Glitches with Pine Needles.

### ISSUE THREAD

**Issue by nanepiwo** [minetest/minetest#3145]
There seems to be light coming out of the corner, but there isn't any light producing node and it is night.
![screenshot_2511103808](https://cloud.githubusercontent.com/assets/10261530/9673899/c5a165b4-5277-11e5-93cc-650da4d16917.png)
![screenshot_2511112295](https://cloud.githubusercontent.com/assets/10261530/9673900/c5a20e9c-5277-11e5-9ee5-271b4ffcd190.png)

**Comment by Wayward1** [comment]
I can't reproduce this. Does it happen with naturally generated pine needles, manually placed, or both? Also, how often?

**Comment by paramat** [comment]
Minetest has occasional lighting bugs, so how often this happens is the issue.

**Comment by paramat** [comment]
@nanepiwo Does this happen regularly? Also, mapgen lighting has been improved recently.

**Comment by est31** [comment]
Yeah lets close this it cant be reproduced
