### ISSUE TITLE
`get_node_light` does always return zero.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3149]
`minetest.get_node_light(pos)` returns zero for all nodes.

I attached a global `on punch` listener and punched a few nodes, for all nodes the function returned zero.

    minetest.register_on_punchnode(function(pos, node, puncher, pointed_thing)
        print(minetest.get_node_light(pos))
    end)

**Comment by asl97** [comment]
quote: `This function returns the light value "inside" of the node at given position. So if you need to get the light value ontop of target node you need to get the light value of position above the target.`

**Comment by RobertZenz** [comment]
Ohhhh...this information is missing from lua_api.txt, which I used.

Yeah, that is it...I'll make a pull request for adding this information to the lua_api.txt.
