### ISSUE TITLE
Feature request : commands aliases

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3154]
I want an equivalent of the bash aliases on Unix-based systems. Syntactically it could have this format : 

``` Bash
alias /cschem='//mtschemcreate'
alias /t='/time'
```

**Comment by rubenwardy** [comment]
It would be quite easy to make a mod like this, but this sort of thing should be done by the engine.

**Comment by rubenwardy** [comment]
https://github.com/rubenwardy/aliases

**Comment by rubenwardy** [comment]
It should definitely be a client side engine feature, however.

**Comment by kilbith** [comment]
Ideally I want these aliases located in a text file (Unix way), so that it's portable and I don't have the pain to re-register them whenever I change of config.

Thanks for the interest anyhow :+1:

**Comment by est31** [comment]
Related to #2445

**Comment by kilbith** [comment]
Any news on this ?

**Comment by rubenwardy** [comment]
This looks like the place where you'd add such a feature: https://github.com/minetest/minetest/blob/master/src/client.cpp#L1562
