### ISSUE TITLE
Moon, Sun and Stars on Android

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3155]
Nobody noticed, but they really do not have to Android. This is bug.

**Comment by ProgrammingChicken** [comment]
Please explain.

**Comment by MoNTE48** [comment]
On Android i cant see sun, moon or stars. Only clouda.

**Comment by Wayward1** [comment]
I've noticed this too. It's rather odd, actually

**Comment by ProgrammingChicken** [comment]
Probably something with textures, otherwise I dunno. Not the expert on anything around here.

**Comment by MoNTE48** [comment]
@est31, pls, add bug label!

**Comment by est31** [comment]
great we have screenshots now.

**Comment by MoNTE48** [comment]
This is not a problem with textures, I can not understand what went wrong, but it is very ugly.
@sapier ^

**Comment by MoNTE48** [comment]
Pls, add bounty labels, I paid... $200 :)

**Comment by srifqi** [comment]
Still same, using newest version from Google Play.
Video: https://youtu.be/35FQYJQTCHg

**Comment by stujones11** [comment]
I hereby claim my bounty :1st_place_medal: :)

**Comment by MoNTE48** [comment]
@stujones11 yes! please, write me your paypal donation link.

**Comment by MoNTE48** [comment]
@stujones11 
![stu](https://user-images.githubusercontent.com/6764600/43497228-5d871c84-9541-11e8-81a8-95305828cd45.PNG)

**Comment by stujones11** [comment]
I think the bounty label should now be removed since it has now been claimed and promptly paid even though my PR has yet to receive a review :P
