### ISSUE TITLE
camera_smoothing default value too high

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3156]
Many people complained that their mouse is laggy when they unknowingly hit F8 and activated cinematic mode. Even if cinematic is enabled the mouse shouldn't feel laggy. The default value is to high.

I think a lower value like 0.3 or better 0.2 (IMHO) would be much better. 

You can change the value ingame to test it on different levels:

      /set camera_smoothing 0.4

**Comment by rubenwardy** [comment]
The setting is cinematic_camera_smoothing. It's supposed to be smooth panning / movement, so it will lag behind the cursor.

**Comment by est31** [comment]
Perhaps we should make camera smoothing settable with a setting in the conf.

**Comment by rubenwardy** [comment]
I don't know what you mean, est31.

Currently you can use two minetest.conf settings:

`camera_smoothing` is used when cinematic mode is off.
`cinematic_camera_smoothing` is used when cinematic mode is on.

F8 is used to toggle cinematic on and off.

**Comment by est31** [comment]
@rubenwardy it is possible that you hit f8 by accident. It is very well possible that you mistake the smoothing feature with a laggy mouse. Therefore we should perhaps add a setting that enables cinematic on f8 only if a setting is set, like for the minimap.

**Comment by rubenwardy** [comment]
You didn't phrase that very well, so I didn't understand first time. It would probably be better to just nullify the key for cinematic mode rather than adding another setting

**Comment by est31** [comment]
That's okay as well, but I don't know whether its possible to have a key not set.

**Comment by rubenwardy** [comment]
It is. See disable camera updates - it used to be on F1.

**Comment by paramat** [comment]
I find the default value already subtle enough, it needs to be effective for making videos.
I don't feel that a few players occasionally hitting a key by accident is justification enough to make a change.

**Comment by everamzah** [comment]
Why not add cameras and paths?  Cinematic mode would make sense then, otherwise I feel it's quite misnamed.  How is a mouse filter/delay related to cinema?  It took me forever to figure out how to turn this off because all the while I was looking for a _mouse_ setting, not a video production setting.

**Comment by rubenwardy** [comment]
It's related as it enables smooth panning for making films.

#2323

**Comment by kilbith** [comment]
+1 with @paramat

**Comment by PilzAdam** [comment]
Maybe consider not binding "cinematic mode" to any key by default.

**Comment by lightonflux** [comment]
In c328478 the cinematic mode is disabled by default.

**Comment by rubenwardy** [comment]
Cinematic mode was always disabled by default.

**Comment by paramat** [comment]
> Even if cinematic is enabled the mouse shouldn't feel laggy

Impossible.
The current setting is subtle, and it is adjustable.
Opinions on the default setting?

**Comment by rubenwardy** [comment]
It is possible that the camera smoothing code isn't entirely FPS independent, but from my attempts it seemed ok. It would be okay to unbind the key to stop it being hit accidentally.

What would be nice as well is a section in the pause menu or a new F1 menu which tells you which modes are enabled. For example, full range or no camera updates.

**Comment by 0-afflatus** [comment]
I think it's fine. If you don't like the feature turn it off or adjust the setting. Perhaps I'm not really understanding the issue.

> What would be nice as well is a section in the pause menu or a new F1 menu which tells you which modes are enabled. 

Something like that would be a good idea.

**Comment by paramat** [comment]
> when they unknowingly hit F8 and activated cinematic mode

There's a screen message when it is activated. It is already subtle by default and most here find the default acceptable.

**Comment by everamzah** [comment]
I don't.  It took me forever to figure out why my mouse was being filtered (delayed).  This has nothing to do with cameras!  Call it mouse_smoothing = false, or take it off F8 by default, is my thought.

It's a misnomer at best.

**Comment by paramat** [comment]
@everamzah Nope, 'camera' is accurate, it has nothing to do with mouses, a player may be using a touchpad, trackball or gamepad.
Perhaps you could open a new issue requesting removal from F8? seems reasonable as this is not something that needs to be switched in-game regularly, more of a per-session thing.

**Comment by everamzah** [comment]
It's a pet-peeve.  It is input smoothing.  It's a filter, a delay, on the input.  Call it hid_smoothing, but I'm certainly not using a camera to play Minetest.  Anyone using a trackpad or trackball, who sees mouse_smoothing will recognize that.

**Comment by everamzah** [comment]
https://github.com/minetest/minetest/issues/4275

**Comment by paramat** [comment]
> Anyone using a trackpad or trackball, who sees mouse_smoothing will recognize that.

Yeah i guess so.

'Camera' is referring to the player viewpoint, it's the right technical term, maybe more precise is 'camera pan smoothing'.
