### ISSUE TITLE
Node destructors not being called from `place_schematic`

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#3160]
```lua
        on_destruct = func(pos), --[[
        ^ Node destructor; always called before removing node
        ^ default: nil ]]
        after_destruct = func(pos, oldnode), --[[
        ^ Node destructor; always called after removing node
        ^ default: nil ]]
```

When nodes are being replaced with `place_schematic`

This prevents nodes from proper cleanup tasks.
E.g. `homedecor:desk_fan` or `itemframes:frame`/`itemframes:pedestal`

([shakedown](https://github.com/t4im/shakedown)-run test was since reverted, as it became clear, that this issue will rather be fixed by change of specification than behavior)

**Comment by paramat** [comment]
This is probably intentional as schematics are primarily for use in mapgen and therefore must be as simple and fast as possible, during mapgen there are usually no nodes with destruct functions. Seems to me the occasional minor advantage does not remotely justify the significant slowdown of mapgen.

**Comment by t4im** [comment]
Destruction would not be needed at all, when the replace flag isn't set, or when no destructor is available (which is the default). Are you sure this would even have any speed penalty attached that warrants a breach of api?

**Comment by paramat** [comment]
Checking a node definition for destruct functions would be needed, and this done thousands of times per schematic, so some slowdown yes.
These on-construct/destruct functions are only promised behaviour for individual 'add node' 'remove node' 'place node' 'did node' actions.

**Comment by kwolekr** [comment]
This is never guaranteed anywhere in the documentation.  This isn't a bug, this is a feature request.

**Comment by t4im** [comment]
*sigh*
It is promised in the api, as quoted above. Always means always, not sometimes.
It is quite easy fixable as well, if not by changing behavior, then by mentioning the exceptional behavior in the api as well. It would also be less work to fix it there, than to try to define the issue away.

**Comment by est31** [comment]
It can either be seen as documentation bug, or as a functionality feature request.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/1f9c5a4a7b15ab49e717d81162fe58e4202c0814
