### ISSUE TITLE
Make it possible to change fov ingame

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3165]
Is it possible to change `fov` temporally ingame? After playing with some higher settings (360°) i realised it would work great as a visual effect that indicate intoxication. Some mods have beer, mushrooms an similar things so it would add special "value" to those food items.

**Comment by everamzah** [comment]
/set fov n doesn't work in-game.  I'd be really excited if it did, because I like the idea of a +zoom.

**Comment by rubenwardy** [comment]
fov is a client side value anyway, so the server wouldn't be able to set it. You'd still need to add an API for it.

**Comment by ShadowNinja** [comment]
Relevant: #1075

**Comment by paramat** [comment]
Is being added to CSM #5797

**Comment by paramat** [comment]
:-1: 
Any support?

**Comment by rubenwardy** [comment]
I can certainly see this as useful for mods - sprint mods being a good example

**Comment by paramat** [comment]
Actually i'm neutral. We are now able to set zoom FOV per-player using object properties. This request is for the normal FOV version of that.

**Comment by rubenwardy** [comment]
Implemented
