### ISSUE TITLE
Mods should be able to add shaders

### ISSUE THREAD

**Issue by jogag** [minetest/minetest#3169]
Self-explanatory. Mods should also change shaders' parameters, or even make them from code instead of loading them from file.

**Comment by PilzAdam** [comment]
This could be tricky, since it would mean that client execute code which is send by the server.

**Comment by Calinou** [comment]
This poses security issues, as said by PilzAdam. Shaders can crash clients or make poorly cooled graphics cards overheat.

**Comment by rubenwardy** [comment]
> Shaders can crash clients 

With the number of bugs Minetest has you can crash the client from the server, anyway. Also, I'm pretty sure that if a shader crashes it just renders the world red, rather than stopping the client.

> make poorly cooled graphics cards overheat

I don't know how to respond to this.

> it would mean that clients execute code which is send by the server.

If any progress is to be made by mods, this needs to happen - without client side scripting you can't have custom client side prediction or graphical effects.

**Comment by rubenwardy** [comment]
also, this is a duplicate of #2937.

**Comment by PilzAdam** [comment]
@rubenwardy client side Lua scripting is relatively easy compared to this, since you can sandbox Lua execution.

**Comment by rubenwardy** [comment]
What would be possible to do from shaders?

**Comment by PilzAdam** [comment]
@rubenwardy thats the problem, every graphics card is different and compiles the shaders in a different way. There definitely is potential for security risks since it's quite close to the hardware.

**Comment by HybridDog** [comment]
>make poorly cooled graphics cards overheat

ls it really so easy?
>I don't consider a server crashing a client a security vulnerability. (However a client crashing a server is.)

l'm not sure, l think it's possible to change source code to do a receive_fields but with completely different contents.
And maybe you can crash a server by simply sending 0 as player pitch, by default it goes to 0 but never reaches it.

**Comment by rubenwardy** [comment]
> l'm not sure, l think it's possible to change source code to do a receive_fields but with completely different contents.

I'm not sure what you're saying.

> And maybe you can crash a server by simply sending 0 as player pitch, by default it goes to 0 but never reaches it, many mods use player look directions.

Yes, I imagine that there are quite a lot of ways to crash a server. However, it shouldn't be possible for a client to crash a server, ideally.

**Comment by HybridDog** [comment]
>I'm not sure what you're saying.

lf you click on a button in ui, it's sent which button you pressed, e.g. the home button. You could have pressed the sethome or tohome button, but not both at once, what you pressed is send in the fields to minetest.on_receive_fields() l think. So l guess you can edit the source code to manually let both buttons become pressed at once. l guess pressing both home buttons wouldn't cause problems, but what if you make it send that you used the worldedit gui which has a formspec show prediction that it isn't shown to players without worldedit priv, so modder thinks testing that on receive_fields isn't necessary?

**Comment by rubenwardy** [comment]
In an ideal world, the mod should validate this otherwise it is a security issue.

**Comment by nerzhul** [comment]
@rubenwardy as an example a server sending shaders could so some things like mining bitcoins :D

**Comment by rubenwardy** [comment]
Anyway, this issue is still a duplicate of #2937 and should be closed.

**Comment by est31** [comment]
dupe of #2937 , closing
Thanks @rubenwardy

**Comment by est31** [comment]
The security issues can probably be mitigated by using web technologies (see https://github.com/minetest/minetest/issues/2937#issuecomment-122861647). Those are already exposed to the internet, so there would be no additional security issue with them.
