### ISSUE TITLE
Feature request: adjustable offset for ore columns in register_ore, type=sheet

### ISSUE THREAD

**Issue by blert2112** [minetest/minetest#3172]
IMO, register_ore type=sheet is upside-down, see this thread for pics...
https://forum.minetest.net/viewtopic.php?f=47&t=13206
Was told by hmmm that those random ore colmuns are supposed to be relative to center and it was suggested that I ask for an adjustable offset so that the sheets could be, in essence, flipped over so the smooth contour is on the top and the rough jaggies on the bottom. Might not be my place to suggest but maybe something like: column_offset =
1 ... smooth contour on bottom, rough on top (as is now)
0 ... relative to center (as was originally intended)
-1 ... rough on bottom, smooth contours on top (what I am looking for)
and if it makes you grin... decimals based on percentage of sheet thickness?

**Comment by paramat** [comment]
I was studying this ore recently so will probably fix this, to be relative to centre. I wondered why sheet ore was so ugly.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/beba96941365a750f8b681df7a73566bdf797f0c
