### ISSUE TITLE
Data truncated on compress >> file:write >> file:read >> decompress  (Windows)

### ISSUE THREAD

**Issue by Ferk** [minetest/minetest#3173]
I've set up this example code in a mod:

````
-- read the file
local filename = minetest.get_modpath("default") .. "/test.we"
local f, err = io.open(filename, "r")
local data= f:read("*a")
f:flush()
f:close()

-- compress it and write it
f, err = io.open(filename.."z", "wb")
f:write(minetest.compress(data, "deflate" ))
f:flush()
f:close()

-- decompress it and read it
f, err = io.open(filename.."z", "r")
local data_compressed = f:read("*a")
f:close()
local dedata = minetest.decompress(data_compressed, "deflate");

-- why should this fail?
if (dedata ~= data) then
	error("problem reproduced...")
else
	minetest.log("action","it works!")
end
````

The resulting decompressed data, provided it's long enough seems to be always truncated (original was 78981 characters, result was 4139). [Here's the content](https://gist.github.com/Ferk/0a73950123594f193415) of the file I used for the example (it's a ````.we```` file). But I think it happens with any data long enough.

I have the feeling that this is also the cause for ````.mts```` files not working properly when saving/restoring big areas or nodes (I get always an error saying "the uncompressed data has wrong size").

The problem doesn't happen if the data is not compressed, or if the compressed data is not saved to disk. So it might be that the file doesn't get properly written/read if there are strange characters in the string caused by the compression.

I'm on a Windows machine right now btw. I'll try again on Linux and see if this is OS - specific.

EDIT: ok, it worked on Linux, so it seems to be Windows-only after all. Maybe there's something with the locale of the system messing things up, since I had problems in the past when I wasn't using US_EN as the english language of the Windows system (I had malaysian english and I couldn't even properly control the character).

**Comment by Sokomine** [comment]
Try reading with "rb" instead of only "r". Might make a difference; one of the chars could be EOF.

**Comment by Ferk** [comment]
@Sokomine thank you! that actually worked. Sorry, you can close this issue as invalid.

**Comment by HybridDog** [comment]
>Might make a difference; one of the chars could be EOF.

May you give me the EOF char which stops reading the file, please?
l need it there for my mod: https://github.com/HybridDog/outgame_intervention/blob/master/init.lua#L42

**Comment by Ferk** [comment]
I don't think there's such a thing as an "EOF" character. EOF is a constant (I think it's value is -1) that the "read" syscall from C returns when the stream ends. The closest thing is the '/0' character used to delimit strings in a char array.

I guess what was happening is that the zlib decompress stopped reading the input from the stream as soon as it found problems when reading from a stream of chars since it expected binary. It's most likely something decompress-specific.

**Comment by HybridDog** [comment]
>I guess what was happening is that the zlib decompress stopped reading the input from the stream as soon as it found problems when reading from a stream of chars since it expected binary. It's most likely something decompress-specific.

ok, thanks
>You might have to keep a lua table to remember the files that have been already run in your mod. Or move the files to a subdirectory, rename them or something. 

l think l'll make the file loose its content also if executing that didn't work. lf you did a typo, you fix it in the editor and hit ctrl+s again.

**Comment by HybridDog** [comment]
l've got another question:
What happens if l do local file = io.open(filename, "r") but don't close the file (io.close(file))?
