### ISSUE TITLE
ERROR[Main]: Couldn't find a locale directory! ... when starting game.

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3174]
Perhaps related to recent commit https://github.com/minetest/minetest/commit/2a9da62b21b5c509496b8fd427f29dd650035fe6
Occurs after:

cd bin
./minetest

.. when working on Minetest code and 'unclean' recompiling. Doesn't seem to cause other issues but thought i'd mention it.
I recompile like this:

cmake . -DRUN_IN_PLACE=1
make -j2

**Comment by est31** [comment]
commit 2a9da62b21b5c509496b8fd427f29dd650035fe6 only made it complain, didn't likely cause the root issue.

Looking at it, it should probably not be errorstream, perhaps warnstream(which gets added by the logging pr) or infostream.

**Comment by ShadowNinja** [comment]
I'd say `warningstream` or `errorstream`, but only after that code is set to not compile for non-gettext builds.

**Comment by nerzhul** [comment]
same problem without RUN_IN_PLACE in my build on Linux & FreeBSD

**Comment by ShadowNinja** [comment]
a44393e43a39d2b78ff6673fc646be44698c9d37
