### ISSUE TITLE
Don't have Schematic sources assign schematics to globals

### ISSUE THREAD

**Issue by t4im** [minetest/minetest#3176]
A schematic source is atm exported and expected to look like:

``` lua
schematic = {
    -- stuff
}
```

Which is, when loaded as lua chunk not unlike:

``` lua
function()
    schematic = {
        -- stuff
    }
    return nil
end
```

A cleaner way, that avoids this global definition, is to simply return it:

``` lua
return {
    -- stuff
}
```

As it is already done with serialization in minetest.

A nice consequence would be, that you can do things like:

``` lua
local export = minetest.serialize_schematic(dofile(path .. "/mts_source.lua"), "mts", {})
```

``` lua
for key, var in pairs(dofile(path .. "/mts_source.lua").data) do
    -- iterate through all the data
    -- either to manipulate it, or use it as a base for a VoxelManip
end
```

(dofile excutes the chunk, so it would currently assign the global, but with return simply return the table)

**Comment by paramat** [comment]
We don't understand, can you explain?

**Comment by t4im** [comment]
I was suggesting a cleaner export-format of schematics, that avoid assigning them to globals and then returning `nil`, but instead just passes them as return value directly. This is cleaner, easier to use during import and in cases of frequent imports even a little bit easier on resource usage.

**Comment by sofar** [comment]
This is nice, but there is no action for minetest. I suggest closing this.

**Comment by t4im** [comment]
I'm not sure i understand what you mean by "no action" here.
But i'm not talking about a mod or something minetest-unrelated, but about the format as created by `minetest.create_schematic` and parsed by `minetest.serialize_schematic` (perhaps also others).

**Comment by sofar** [comment]
I feel that there's no action needed to `minetest` because:

- it's trivial for mod makers to choose to save the file and change `schematic =` into `return` and use the  `dofile()` loading method you propose
- the `dofile` loading method reduces memory but increases time needed to place schematic, after all, a schematic that's loaded in memory should generally be loaded faster than from disk.
- changing the default behavior would break API, which is not desirable, and not needed I feel
- schematic saving and loading isn't really designed for frequent user use, but for developers during pre-production (development), and they will pick the right methods to optimize it
- nothing in core actually loads schematics (even mapgen tree schematics are handled in `minetest_game`

Now, if there's a good way to redesign this that takes the incompatibility in mind and doesn't break the current API, then patches are always welcome...

**Comment by t4im** [comment]
* There is no api and hardly a behavioral change, just a format change.
* Backward compatibility should be trivial: simply use the return value if it is non-`nil`, otherwise use the schematic global.
* Placement should be equally fast or faster, since you have the same read from the file in both cases, before the lua-chunk is executed in memory; but the current case involves additional global table lookups and an assignment and then returns a value (`nil`) anyway. The benefit is probably unnoticeable though.

But yea, the issue isn't of high importance. It's just some awkwardness i spotted during [api testing](https://github.com/t4im/coretest) last year, when i was more active.

**Comment by kwolekr** [comment]
Maybe it's just me, but I don't understand what would need to change in minetest in order to do what t4im is saying...

**Comment by t4im** [comment]
Hm, the import isn't even an issue (must have mixed it up after all that time with the unrelated discarded return value in [loadscript](https://github.com/minetest/minetest/blob/095f623fa7278375a6fa4fe01ed39d2b68cce7af/src/script/cpp_api/s_base.cpp#L131))

So this is even more trivial, as it essentially just involves a literal-change in
[serializeToLua](https://github.com/minetest/minetest/blob/c8ff11b417ae2c3a156bcaca819eaeec334c76b5/src/mg_schematic.cpp#L374) from `schematic =` to `return `. But then sadly has some minor behavioral change attached after all, since any mods using it apparently took care of the parsing themselves (unnecessarily).

**Comment by kwolekr** [comment]
I see what you mean now.  In retrospect, it wasn't the greatest idea to add the `schematic = `, but now it's the expected default behavior...  but at the same time I disagree with changing it to `return `.  It should be only the code for the table expression, and the mod should be the thing to assign action to the expression.

You could work around this by inserting the schematic string in between
`"local " .. minetest.serialize_schematic(...) .. "\nreturn schematic"`, no?

In any case, this might be changeable depending on how the documentation for this function was worded and how the majority of mods use this function.  Don't hold your breath, though.

**Comment by paramat** [comment]
Any comments? Anyone interested in coding this sometime? If not closing in 1 month.

**Comment by paramat** [comment]
:-1: 
Kwolekr is the expert.
