### ISSUE TITLE
Export/Import MTS not portable.

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#3177]
Exported MTS from Linux are not portable to FreeBSD.

How to reproduce: generate a huge MTS with ~1M blocks to be sure, export the MTS with a command like worldedit provised,. Reimport it on the same system it works.

Now send the file a FreeBSD server, import it. Serialization error.
It's related to zlib. Non compressed MTS are not affected by this problem

**Comment by ShadowNinja** [comment]
It sounds very odd that zlib would have a cross-platform compatibility issue, considering how much it's used for serialization...

**Comment by kahrl** [comment]
Jus a shot in the dark, but: I noitced that decompressZlib calls unget() on the input stream repeatedly, to unget all characters that were extraneously read. Could it be that FreeBSD's C++ library only supports ungetting a single character at a time?

**Comment by nerzhul** [comment]
@kahrl i admit i don't have any idea

**Comment by SmallJoker** [comment]
Why did you close this issue? Isn't this bug still present?

**Comment by nerzhul** [comment]
It seems no
