### ISSUE TITLE
wielditem visual regression when filters enabled

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#3178]
Before (5b0c719171eb9ccb8f2829eb1cc8b3fe9f24cd05):
![tool-before](https://cloud.githubusercontent.com/assets/324806/9839891/74abf644-5a54-11e5-988b-105eb7c68818.png)

After (60350699c792b816b20704d59cfbda0894cdba39):
![tool-after](https://cloud.githubusercontent.com/assets/324806/9839892/7e4ad026-5a54-11e5-8e3e-7a502d5a2523.png)

Notice how the jungle grass behind the tools are not affected, and still look reasonably good, because the `texture_min_size` and `texture_clean_transparent` filters are applied.  Wielded nodes are also not affected; only extruded tool images.

Applying the `^[applyfiltersformesh` transform to the texture that's applied to the extruded mesh should resolve this.

**Comment by Warr1024** [comment]
It looks like `getTextureForMesh` got replaced with `getTexture` in `wieldmesh.cpp`.  Reverting that one line appears to fix it for me.

https://github.com/minetest/minetest/commit/60350699c792b816b20704d59cfbda0894cdba39#diff-60aa608aac2fefb1a86d4c2861a08eb7L284

**Comment by RHRhino** [comment]
If this is really as trivial as the label says: Could someone please fix that bug?

**Comment by 0-afflatus** [comment]
I don't understand what you mean by "visual regression". Could you post a screenshot of the fixed version? If this makes sense to the devs and it really is a trivial fix, then no need to respond. I'm just asking out of interest.

**Comment by Warr1024** [comment]
A regression is when something that was working correctly before is broken due to changes elsewhere in the software.  Thus, the "fixed" screenshot will simply match the "before" in the original post.

**Comment by 0-afflatus** [comment]
I know what a regression is. I just don't understand what you think is broken.

**Comment by est31** [comment]
fixed by 900db310638531a8b9fb1a587f75a02a15ae0c24
