### ISSUE TITLE
Provide the possibility to pre-generate a map.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3183]
Currently the server is generating the map as needed based on the player positions, this can lead to noticeable and pretty bad lag. It would therefor be good if we would have the possibility to pre-generate a complete area on server start or as some sort of stand-alone operation, something along the lines of this:

    ./minetestserver --gameid SomeGame --world SomeWorld --generate -1000,-1000,-1000/1000,1000,1000

The server could than generate that area and either continue normal operation or exit.

This would also allow to pre-generate a pretty vast map on a faster machine and then copy it onto a server.

An additional bonus is that for people that are writing mapgens could quickly and easily generate large portions of the terrain and map it with minetestmapper, instead if spending time flying around the world.

**Comment by paramat** [comment]
Good for lua mapgens.
There is a hacky mod https://forum.minetest.net/viewtopic.php?id=2950

**Comment by PilzAdam** [comment]
This could be handy when testing mapgens by running minetestmapper.

**Comment by est31** [comment]
This could be handy as well when testing map compression.

**Comment by RobertZenz** [comment]
As I just noticed, part of this seems to have landed in f062bbd7. Exciting.

**Comment by est31** [comment]
I think it can be seen as fixed now, can't it? Just copy a trivial mod that pregenerates the world into the worldmods directory.

**Comment by RobertZenz** [comment]
Doesn't even need to be a mod, can be invoked by a player (chat command) and then waiting. Means you have to idle around, but I guess that is okay and better then having to fly around.

From my side that's basically it, yes, unless you'd like to have command line function for that, too.

**Comment by RobertZenz** [comment]
I just tried it, the command does not generate  non-generated blocks. I commented on the diff where the problems seems to be for me.

**Comment by C1ffisme** [comment]
This is a wonderful idea!

Mapgen in minetest is excruciatingly slow on most servers, and with this you won't have to worry about new areas being generated for quite a while.

**Comment by kwolekr** [comment]
I fixed that and improved the /emergeblocks command to give progress updates every 2 seconds here: https://github.com/minetest/minetest/commit/c2b5da735ea0c961d4f6521df9d96142c7143eee

Feel free to re-open this issue if you find the solution to be insufficient.
