### ISSUE TITLE
Server does not create new worlds.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3184]
Currently the server does not create a new world if provided with a non existing one. If a non existing world is specified it does fallback to an already existing one (I did not test what happens if there is none at all). It would be very useful if the server would actually create new worlds.

**Comment by PilzAdam** [comment]
Do you start the server with the `--world` or `--worldname` parameter?

**Comment by RobertZenz** [comment]
Yes. [I asked about it on IRC back then](http://irc.minetest.ru/minetest/2015-09-10#i_4390743), at least est31 seemed to be aware of it.

**Comment by PilzAdam** [comment]
IIRC only the `--world` parameter with a complete worldpath creates new world; `--worldname` doesn't. This needs to be checked, though.

**Comment by sfan5** [comment]
`--world` is able to create new worlds, closing.
