### ISSUE TITLE
[Request] Camera API

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#3188]
```
player:get_camera_mode()
player:set_camera_mode(3) -- third person
player:lock_camera_mode(true) -- true, false or nil
```

It will be used in beds, boats, and more.

**Comment by PilzAdam** [comment]
What about `set_eye_offset()`?

**Comment by Rui914** [comment]
This will be switched to first-person view and third-person view from the Mod.

**Comment by PilzAdam** [comment]
Ah, in this case I'd suggest calling it `player:lock_camera_mode()`; passing `nil` leaves the player the option to change it.

**Comment by RobertZenz** [comment]
Related: #3070

**Comment by RobertZenz** [comment]
I'd like to suggest to be more explicit, handing a magic number to a function isn't the most readable option. Either there should be a constant for it:

    player:set_camera_mode(Player.CAMERA_THIRD_PERSON)

Or have a separate function:

    player:use_third_person_camera()

Or directly allow the function to accept a table, something like:

    player:set_camera_mode({
        self_visible = false,
        relative_eye_position = {
            0,
            0,
            0
        }
    })

In combination with static values for the camera.
