### ISSUE TITLE
Nordic letters can't be keybound

### ISSUE THREAD

**Issue by etu** [minetest/minetest#3190]
Might be slightly related to #2951, but in this case it doesn't crash.

I'm typing on a Swedish Dvorak layout called Svorak, which puts the letters ÅÄÖ in the place where the letters QWE usualy live. Which makes me want to keybind those to movement.

Only tested in Minetest 0.4.13 on Arch Linux, got no other system available. It doesn't crash, the key just doesn't get binded, it get's a - sign on it.

Cheers for making good and open software. C/C++ families just isn't my cup of tea, otherwise I would have tried to make a patch for it :)

**Comment by est31** [comment]
Seems to be a problem as well on german äöüß keys.

**Comment by est31** [comment]
I don't give it yet the "upstream bug" label, until I (or some other) dev had a close look at the code and what irrlicht provides. What is sure is that the name resolves to "-", and that it doesn't work when used.

**Comment by paramat** [comment]
@etu still an issue?

**Comment by SmallJoker** [comment]
Other Irrlicht key handling problems: #6573, #3170, #845, #302
We can't fix this upstream issue unless we decide to fork Irrlicht.

**Comment by etu** [comment]
I must say that I haven't used the software eve since I've reported this since I was a bit put off by not being able to play it using my regular keyboard layout. So I reported this issue just to be nice and tell someone about it.

But I've just installed latest stable from NixOS repositories which happens to be 0.4.15 and tested and it seems to work there at least.
