### ISSUE TITLE
Items being dragged disappear if their list's formspec is updated

### ISSUE THREAD

**Issue by LeMagnesium** [minetest/minetest#3195]
Observed in @stujones11 's 3d_armor mod : 
A mod adds a new inventory list, which formspec is frequently updated. A player puts an item in a slot, another one in another slot, then select the second one, click with it on the first item, swapping the items, and observe : when the list's formspec is updated, the item currently dragged will disappear.
As I observed, it never happens with direct transfer of an item (from a slot to an empty one). There should be a prediction by the client, putting the dragged item in the first empty slot for example, or leaving it in its "dragged" state.

([The original issue](https://github.com/MinetestForFun/server-minetestforfun/issues/253#issuecomment-137983703) (mostly in french))

**Comment by C1ffisme** [comment]
What we need is for the dragged item to actually be a detached inventory. When you drag something it goes into that inventory, but it still looks like you are dragging it. And if you are still dragging and your inventory closes (You press I) then what is in that inventory is dropped as an item.

**Comment by tenplus1** [comment]
+1 good idea

**Comment by LeMagnesium** [comment]
This is a very good idea, very graceful way to fix it in my opinion. I don't know how hard it will be to implement that, but this behavior will fix perfectly the problem and will probably allow more control from the API over the dragged itemstack (assuming the detached "dragged" inventory will be available in Lua).

**Comment by LeMagnesium** [comment]
I will close this since we've been able to somehow fix the problem in the incriminated mod. I don't know if my interpretation of its origin (the dragged item being reset when updating a list's formspec) was correct so if it happens again to anybody feel free to comment here/reopen the issue. Sorry for the bother.
(note that if anybody still wants to implement @C1ffisme's idea you can reopen this issue too)
