### ISSUE TITLE
Use a manifest, deprecate depends.txt

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#3200]
Instead of having a depends.txt that controls which mods _need_ to be loaded before you load your mod, there should be a manifest.txt (or preferably manifest.json/manifest.lua (If you're using Lua already, might aswell use it for the config files!)), with tags such as:
- "modname" (Human readable name.)
- "version" (Mod version. Can be useful.)
- "lua_version" (A string. e.g. "5.1", "5.2", "5.3", etc.)
- "load_order" (List of mods including this one. e.g. `["libthing", "libother", "thisthing", "otherthing"]` to load after libthing and libother and before otherthing.)
- "dependencies" (List of mods depended on. This does not imply order! Use order to control loading order.)
- etc

**Comment by ShadowNinja** [comment]
Related: c5defe7a11f58048acfa4568ea784f31d9ffa276
Mod.conf should store the description from `description.txt` and the things you've mentioned.
A Lua format is not optimal because you'd have to set up the whole secure environment and such.

**Comment by SoniEx2** [comment]
For the Lua format you just setfenv(nil). (or empty table)

**Comment by SoniEx2** [comment]
Actually, from the C side, all you do is load the code without setting up the Lua environment at all! (e.g. a call to luaL_newstate followed by a call to luaL_dostring)

**Comment by est31** [comment]
Agree with @ShadowNinja , if we deprecate depends.txt we should use `mod.conf`, together with the settings file format we already use.

**Comment by cheapie** [comment]
I like the list of fields that @SoniEx2 gave, except that instead of "require", it should have "depends" (requires another mod to be installed, such as if it uses the other mod's items in a crafting recipe), "pre-depends" (requires that the other mod be loaded first, such as if it uses an API provided by the other mod), "conflicts" (breaks the other mod and cannot be loaded at the same time), and "provides" (can stand in for the other mod, for example if it's a superset of it).

**Comment by SoniEx2** [comment]
But that doesn't let you control before/after or optional vs non-optional

**Comment by RobertZenz** [comment]
Just as a note: Having something like "load_after" sounds like a very bad idea. The dependencies can already quickly escalate and get out of hand, being able to specify not only dependencies but also dependants sounds a like an administration nightmare to me.

**Comment by SoniEx2** [comment]
Toposort.

It's pretty common to have both. See, for example, Minecraft Forge.

**Comment by PilzAdam** [comment]
@RobertZenz `load_after` could come in handy when you want to overload a hook that a specific mod uses. `load_after = *` might even be added that tells the engine to the mod before any other mod; e.g. if the mod wants to override the default stack_size.

**Comment by est31** [comment]
`conflicts` sounds good.

I don't think we need `provides`. Just make a modpack in that case.

**Comment by rubenwardy** [comment]
We definitely needs provides.

See farming/farming redo, they shouldn't have to have the same name, that's hacky and means you can't depend on farming redo.

**Comment by SoniEx2** [comment]
Surely you don't!

Just use a dummy empty mod that depends on the main mod.

(If only we could have submods instead of modpacks...)

**Comment by est31** [comment]
What's the difference between submods and modpacks? Its the same, just with modpacks you have more options.

**Comment by SoniEx2** [comment]
With submods you put mods inside a mod's folder. Useful for "provides" and/or modules. (Please don't put dependencies in there tho)

**Comment by ShadowNinja** [comment]
I find the `load_before`/`load_after` naming confusing, the opposite meanings make just about as much sense ("load these before this" or "load this before these"?), so I think they should be named something less confusing like `depends` and `depended-by`.

**Comment by est31** [comment]
"the following mod depends on this mod" "this mod depends on the following mod".

**Comment by est31** [comment]
But confused me as well.

**Comment by SoniEx2** [comment]
"loaded" and "to_load" (shorter)?

**Comment by rubenwardy** [comment]
#6243

**Comment by SoniEx2** [comment]
"order": ["name1", "name2", "thisname", "name3"]

**Comment by rubenwardy** [comment]
PR merged
