### ISSUE TITLE
Load mod from .zip

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#3204]
You should be able to package a mod's dir **contents** into a .zip and use the .zip instead of a mod folder.

Visually, this is how it is with folders:

```
modid
| - init.lua
| - other files
```

This is how it'd be with zips:

```
modid.zip
| - init.lua
| - other files
```

Easier distribution (no unpacking required) and stuff. Keep unpacked mods for easy development.

**Comment by PilzAdam** [comment]
This would definitely make installation of mods easier for some users.

**Comment by est31** [comment]
This would be useful, agreed.

**Comment by Calinou** [comment]
:+1:

**Comment by crazyR14** [comment]
+1

**Comment by LNJplus** [comment]
But if download a repo on github in a .zip then you'll get this:
`modid-branch.zip
| - modid-branch
  | - init.lua
  | - other files`

**Comment by cheapie** [comment]
Why .zip and not .tar.gz or something?

**Comment by est31** [comment]
Well, perhaps those formats can be supported as well. zip should be supported at least though, as github offers their branch downloads in this format.

**Comment by 4Evergreen4** [comment]
If we do decide to support this, make sure that it also works for zip files that contain a directory which contains the mod.  _(as mentioned by @LNJplus)_

**Comment by Fixer-007** [comment]
+1

**Comment by gregorycu** [comment]
This is how I'm thinking of implementing it. It sounds a little complicated but I think it's the simplest solution.

The minetest engine will have a virtual filesystem for use with such mods. This is a very basic in-memory cache of filename to uncompressed file.

When it loads mods, it also searches inside all zips for mods inside of it. For each mod, it will decompress and add all the files for these mods to the virtual filesystem.

With lua, certain functions such as "dofile" will be hooked, and if an actual file matching the path cannot be found, it will attempt to find the file in the virtual filesystem.

Example, a modpack with two mods inside of it:
somefilename-master\somepath\mod1\depends.txt
somefilename-master\somepath\mod2\depends.txt

The virtual filesystem will act as-if there are two folders in the mods/ folder called mod1 and mod2 which both represent mods.

Problems with this approach is what happens if mods data to the mod directory, how should the virtual filesystem handle that? I don't think it's a problem worth solving.

I am also not sure how modpacks fit into all of is. The example is basically a modpack, but it's an implicit one.

I've written some code that can see files inside a zip, and I've hooked dofile, so the solution looks possible.

**Comment by red-001** [comment]
@gregorycu 
>Problems with this approach is what happens if mods data to the mod directory, how should the virtual filesystem handle that? I don't think it's a problem worth solving.

Many mods do this. The best solution in my option would be to have minetest extract the files and save them on to the filesystem.

**Comment by est31** [comment]
Mods putting stuff to the mod dir? That's no issue IMO, security prevents mods from doing this any way. Settings should be stored with minetest's setting system and world specific data in the world dir.

**Comment by SoniEx2** [comment]
@est31 What about extracting/loading native libs? In case of a packed zip, you need to extract the natives to a temp or permanent location before using them. (Altho I guess you can use os.tempfile() or w/e for this.)

**Comment by est31** [comment]
native libs can't be used if security is enabled.

**Comment by rubenwardy** [comment]
> Mods putting stuff to the mod dir? That's no issue IMO, security prevents mods from doing this any way. Settings should be stored with minetest's setting system and world specific data in the world dir.

Not true. Mods can read and write to their own directory at load time.

**Comment by gregorycu** [comment]
I think the security around mods probably needs to be decided/clarified at some point. How this feature is implemented would be dependent on those clarifications.

**Comment by est31** [comment]
I just want to write why I think that a virtual filesystem is better than copying the whole mod:

1. It requires even more space, we copy the whole thing again to disk, for no reason except our own convenience.

2. How should we treat updates? Either we extract the whole zip file at every start of the server, which is of course extra slow, or we live with the problem that people have to delete their temp dir if they want to update their mod. Or we check every file at startup, which is probably equal to the "extract everything" solution.

There are two advantages of a "copy everything" approach over a "virtual filesystem" one though. If some files of the mod are stored compressed (usually they are), then loading the files from a cache is usually faster then uncompressing them. But even this comes with a big question mark, as there is the problem with the updates, so probably one would have to extract them every time either way.

And the second advantage would be that the "copy everything" approach can be implemented faster than the virtual filesystem one.

Perhaps one idea would be that upon start, minetest automatically extracts the zip to the place it exists, removing the zip in the process. This would solve problems 2. and 1.

**Comment by cheapie** [comment]
Well, for the "copy everything" approach, you could calculate a checksum
(even an "insecure" but rather fast algorithm should work) and store that
somewhere, and only bother extracting if it doesn't match what it was last
time. The last game I saw using zips did that, and you could tell it loaded
a lot faster after the first time.

**Comment by stujones11** [comment]
I have some concerns about this whole idea, there are many mods which utilize the mods directory for configuration files etc that are expected to be readable/writable with a text editor, so to my mind the "copy everything" approach is in only way to go, if any. 
While I would be willing to make changes to my own mods, there are a good deal of unmaintained mods that will no longer work and for what benefit, make life easier for people who cannot be arsed to follow some very simple instructions?

Also, wouldn't the "virtual file system" approach make developing mods a major pita by having to re-archive every single change you make and want to test?

**Comment by SoniEx2** [comment]
@stujones11 dirs override zips.

**Comment by DI3HARD139** [comment]
+1

**Comment by stujones11** [comment]
>@stujones11 dirs override zips.

Sorry, I must have missed that part. Besides, if this is to be entirely optional then I fail to what there is to gain from it.

**Comment by SoniEx2** [comment]
@stujones11 It's end-user friendly. Yes, they're zips, yes, end-users can unpack them, but end-users can also see them as an opaque blob, a packed single-file mod, which is easier to send around and install.

**Comment by stujones11** [comment]
I really did not have a problem with this idea personally, especially if it was to be optional. I am sorry I misinterpreted the original suggestion, I just didn't really see it as a high priority and had a few concerns about backwards compatibility.

**Comment by gregorycu** [comment]
You still have valid points.

For example, what if a mod does have a config file.

In my mind, mods should have a first class storage facility provided by the
api framework for this kind of thing. The reason I think this, is this
would allow people to easily update mods without worrying about preserving
config etc. Also it's probably better from a security standpoint.

My intention is that you could have both the mod folder and the mod zip.
The mod folder would have first preference at finding a file, and then it
would hit the VFS.

This means people/mods could persist stuff. You could "factory reset" a mod
just by deleting that folder. And you could theoretically patch a mod
locally.

**Comment by rubenwardy** [comment]
This is difficult and without much gain when the mod etc store is added for 0.5.0

**Comment by paramat** [comment]
:-1: Seems wrong and 'vulgar', zips are meant be unpacked and people are able to do this, or should learn.

**Comment by rubenwardy** [comment]
This could actually help with the mod store actually, by forcing mods to be read only and having a vfs for backwards compat. With the mod store, updating will cause data loss if the mod writes to itself

**Comment by paramat** [comment]
Ok, but surely it's better to get around that issue another way? Installing mods as zip files is just so wrong :)

**Comment by rubenwardy** [comment]
Yeah, that's a separate issue

**Comment by paramat** [comment]
Closing, not much needed.

**Comment by Calinou** [comment]
> Installing mods as zip files is just so wrong :)

For the record, it's very common in other games. Minecraft mod loaders have been doing this for years now, and most id Tech 3-derived games use PK3 files which are just renamed ZIP archives.

I have no problem with this not being implemented in Minetest, but it's not "just so wrong".

**Comment by rubenwardy** [comment]
I agree, there's something very nice about having a single file for mods as an archive. It just has less value when a mod store is added

**Comment by paramat** [comment]
Ok, some other games do it, but that doesn't make it right, or seem right, or a good idea.
It's like adding robotic arms inside a microwave to remove the wrapping from food, convenient yes but ridiculous and over engineered, exaclty what MT needs to avoid with our limited dev time.
:)
