### ISSUE TITLE
Submods

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#3205]
Submods (or child mods) would allow for modular mods. Instead of having a modpack (multiple mod files you unpack into the mods dir), you'd have a single mod with all the submods. Combined with #3204 this would be useful for modular mods.

Combined with #3200, each submod would *need* a manifest to be considered a submod, and it would *need* to come directly under a mod. Attempting to depend on a submod would be an error. (this is to discourage packing dependencies into the mod and causing conflicts with other mods >.>)

E.g. this is legal:

```
modid
| - init.lua
| - mod.conf
| - submodid
    | - mod.conf
    | - init.lua
```

(loads 2 mods, `modid` and `submodid`)

But this isn't:

```
modid
| - init.lua
| - mod.conf
| - subdir
    | - submodid
        | - mod.conf
        | - init.lua
```

(loads only `modid`)

Having a dependency on a sibling mod would be allowed. Having a dependency on the parent mod would be implicit. Due to this last restriction, having a dependency on a child mod would be an error.

**Comment by est31** [comment]
I dont think it allows anything more that currently possible.

**Comment by SoniEx2** [comment]
No-unpacking-single-download.

**Comment by est31** [comment]
modpacks do allow that

**Comment by SoniEx2** [comment]
But Minecraft (MinecraftForge at least) has submods and I want them here too!

**Comment by est31** [comment]
Thats no argument, we are no fork/clone of MinecraftForge.

**Comment by SoniEx2** [comment]
You /are/ a clone of Minecraft.

**Comment by est31** [comment]
No.

**Comment by SoniEx2** [comment]
\> GUIs
\> chests
\> torches
\> blocks
\> world
\> tools
\> iron
\> diamond
\> stone
\> wood
\> coal
\> ...

I could go on.

**Comment by est31** [comment]
We share many gameplay (and technical) concepts with minecraft, but we are no fork that tries to mimick Minecraft in every aspect.

**Comment by SoniEx2** [comment]
Maybe not a fork but definitely a clone.

**Comment by PilzAdam** [comment]
Please stop the offtopic discussion whether Minetest is a clone / fork / whatever of Minecraft.

You can make your mods modular with `dofile()`, or use modpacks. Adding "submods" just for the sake of having it without any benefits is not good.

**Comment by est31** [comment]
Let's close this then?

**Comment by SoniEx2** [comment]
> You can make your mods modular with `dofile()`

Doesn't let you add metadata.

> or use modpacks.

What are modpacks anyway?

**Comment by rubenwardy** [comment]
http://rubenwardy.com/minetest_modding_book/chapters/folders.html#mod-packs

**Comment by SoniEx2** [comment]
Submods have a more interesting structure.

**Comment by C1ffisme** [comment]
Interest is not important in a file system.

Style is important in code, and so is readability, but interest is not important. Would you build a house out of triangular bricks in tornado valley?

**Comment by rubenwardy** [comment]
Triangles are strong.

**Comment by C1ffisme** [comment]
Fine then, make it out of glass, and use octogons with diamonds to fill in the gaps.

**Comment by gjgfuj** [comment]
Is it possible to have a modpack and a mod in the same directory? if not, then there's a problem here. If so, it's submods. that's literally all that's needed to have submods, allow for a modpack and a mod in the same directory.

**Comment by rubenwardy** [comment]
I still don't see why it's needed. You could just use a mod pack.

```
mods/
|---- mod1/
|---- mod2/
|---- mod3/
|---- modpack/
|--------mod4/
|--------mod5/
|--------modpack.txt
```

Please can you give an actual reason for why you want this?

**Comment by rubenwardy** [comment]
Please note that you can do this:

```
mod1/
|-- init.lua
|-- somefile.lua
|-- someotherfile.lua
```

**Comment by rubenwardy** [comment]
Please note that you can do this:

```
mod1/
|-- init.lua
|-- somefile.lua
|-- someotherfile.lua
```

or even this:

```
mod1/
|-- init.lua
|-- somefile.lua
|-- somedir/
|---- somefile.lua

**Comment by SoniEx2** [comment]
Can you do this?

```
ModCore/
|-- init.lua
|-- modpack.txt
|-- ModMachines/
    |-- init.lua
    |-- modpack.txt
    |-- ModAdvancedMachines/
        |-- init.lua
```

Pay close attention to the hierarchy.

**Comment by rubenwardy** [comment]
...

That's still not a reason.

That's like saying can a screwdriver cut wood, without giving a reason why it should do that.

```
ModCore/
|-- init.lua
|-- modpack.txt
ModMachines/
|-- depends.txt (modcore)
|-- init.lua
|-- modpack.txt
ModAdvancedMachines/
|-- depends.txt (modcore, modmachines)
|-- init.lua
```

**Comment by SoniEx2** [comment]
Organization. For the same reason I want github/bitbucket to add projects/subprojects. For the same reason I want sublabels. More importantly, **for the same reason I don't put all my files on the partition root, but rather in a DIRECTORY TREE.**

**Comment by rubenwardy** [comment]
Would sub mods be hidden from the user?

**Comment by rubenwardy** [comment]
If the reason is storing in a directory tree, then really all you need is this:

```
Mod1/
|-- modpack
|-- Core/
     |-- init.lua
|-- ModMachines/
     |-- modpack.txt
     |-- BasicMachines/
          |-- depends.txt (modcore)
          |-- init.lua
     |-- ModAdvancedMachines/
          |-- depends.txt (modcore, modmachines)
          |-- init.lua
```


Although the mod configurer doesn't like doubly nested modpacks, ie: you can't enable mods using a GUI, which I think should change.

**Comment by SoniEx2** [comment]
Can you have a mod and a modpack in the same place? E.g. can mod1/ have init.lua and modpack.txt?

**Comment by gjgfuj** [comment]
yes, exactly. that's simple enough.
