### ISSUE TITLE
Adding an FPS limit

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#3207]
When I play Minecraft, my movement feels slightly drunken, but my laptop heat doesn't rise to insane temperatures.

When I play Minetest, my movement feels more sober, but my laptop heat stays in the 60s and 70s (Celsius, of course) and sometimes hits the 80s.

This may not be the problem, maybe it's because the game just asumes it can get as much FPS as it requires. This means it isn't limited by computer safety regulations or anything. You may get really good minetest performance, but your computer's life is shortened.

This may not be the problem, it could possibly be rendering issues, etc. But it's worth a try, and for those who want to add an FPS limit to lower power usage, I think this would be a good addition.

**Comment by asl97** [comment]
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L80

**Comment by C1ffisme** [comment]
I'll give it a try, if it doesn't improve my heat problems, we can close the issue. If it does, we can close the issue, but make a note to others that this will help you on laptops.

**Comment by asl97** [comment]
@C1ffisme iirc, you need to set the viewing_range_nodes_max too or it would just render as far as it can, making the fps reduction useless for reducing heat and power use.
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L87

**Comment by C1ffisme** [comment]
Glad you posted that, I made the fps limit 30, and I wondered why it was still going over 30 in the debug info.

**Comment by est31** [comment]
There is already a setting for FPS limits, as @asl97  has pointed out. Closing.

**Comment by PilzAdam** [comment]
@C1ffisme this is not a support forum.

**Comment by rubenwardy** [comment]
@C1ffisme https://forum.minetest.net/viewforum.php?f=6

**Comment by C1ffisme** [comment]
@PilxAdam I didn't know there was an FPS limit, it was a feature request. Not an ask for support

**Comment by rubenwardy** [comment]
Literally all you needed to do was search fps in minetest.conf.example -
that's where such an option would be.

**Comment by C1ffisme** [comment]
I'll do that next time...
