### ISSUE TITLE
Allow changing chunksize from lua API, with set_mapgen_params()

### ISSUE THREAD

**Issue by eduardomezencio** [minetest/minetest#3222]
Being able to change chunksize from a mod would be very useful if the mod implements a mapgen that could be optimized with a particular chunksize. I'm working on one of these right now, so it would definitely help me.

**Comment by paramat** [comment]
+1. It's in 'getmapgenparams' but not in 'setmapgenparams', this should be made consistent.

**Comment by eduardomezencio** [comment]
I have just implemented that myself by just adding some 3 lines to the code and it's working perfectly for myself. I think, however, that if the devs left out this thing that is so simple, they probably had a reason. Let's wait to see if someone points out any issue.

I'll fork this repository and add my tiny patch to my version. If no one opposes it, I'll make a pull request to merge it.

**Comment by paramat** [comment]
> if the devs left out this thing that is so simple, they probably had a reason

Like laziness perhaps.

**Comment by kwolekr** [comment]
Unlike other mapgen params, futszing with this one is dangerous.  It shouldn't be made modifiable at all, I don't know why I made this into a param

**Comment by paramat** [comment]
eduardomezencio why do you need to set chunksize? this should only be done in a singlenode mapgen as chunksize affects how mgv5/6/7 generates.

**Comment by eduardomezencio** [comment]
Setting it in .conf is not good, because I need it to be changed only when the mod that needs this change is in use. The reason why I need it is that I'm creating a mod that is a mapgen. It uses singlenode as the 'base' mapgen, so it really does not matter if the param messes with v5, v6 and v7 mapgen.

My mod generates an infinite dungeon. My algorithm can be optimized to perform faster and, more important, to require fewer lines of code (making it easier to maintain and to enhance) if I can set the chunk size to an optimal size.

Just like the builtin mapgens are optimized to use the chunksize 5, other mapgens could be optimized to use any other chunk size, meaning that if you don't expose this param to the lua API, you are simply saying that people should not try to create innovative mapgens in lua. Changing this value only in a mod that can only be used with singlenode is not dangerous in any manner that I am able to imagine.

**Comment by kwolekr** [comment]
Very well, I'll add it.

**Comment by est31** [comment]
implemented by commit 5130dbce7b294c392733e93c05e2099786523342
