### ISSUE TITLE
Oregen crash / regression

### ISSUE THREAD

**Issue by ChaosWormz** [minetest/minetest#3228]
```
In thread 7f5c99fab700:
/home/chaoswormz/Documents/minetest/src/emerge.cpp:573: virtual void* EmergeThread::run(): A fatal error occurred: Range too large
Debug stacks:
DEBUG STACK FOR THREAD 7f5c99fab700:
#0  virtual void* EmergeThread::run()
(Leftover data: #1  virtual MapBlock* ServerMap::emergeBlock(v3s16, bool): p=(23,-72,-2), create_blank=0)
(Leftover data: #2  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #3  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
DEBUG STACK FOR THREAD 7f5c9a7ac700:
#0  virtual void* UpdateThread::run()
DEBUG STACK FOR THREAD 7f5c9bfff700:
#0  virtual void* UpdateThread::run()
DEBUG STACK FOR THREAD 7f5cb3fff700:
#0  virtual void* ServerThread::run()
#1  void Server::Receive()
(Leftover data: #2  virtual void ServerEnvironment::step(float))
(Leftover data: #3  void RemoteClient::GetNextBlocks(ServerEnvironment*, EmergeManager*, float, std::vector<PrioritySortedBlockTransfer>&))
(Leftover data: #4  MapBlock* ServerMap::loadBlock(v3s16))
(Leftover data: #5  void ServerMap::loadBlock(std::string*, v3s16, MapSector*, bool))
DEBUG STACK FOR THREAD 7f5cccf6c7c0:
#0  int main(int, char**)
#1  void ClientMap::renderMap(irr::video::IVideoDriver*, irr::s32)
(Leftover data: #2  virtual void ClientEnvironment::step(float))
(Leftover data: #3  void Client::Receive())
(Leftover data: #4  void Client::ProcessData(NetworkPacket*))
(Leftover data: #5  void MeshUpdateQueue::addBlock(v3s16, MeshMakeData*, bool, bool))
```
this crash doesn't occur in the stable branch

**Comment by est31** [comment]
@ChaosWormz can you tell about your configuration:

2. Which mapgen do you run?
2. Singleplayer? server?
3. Is it reproducible? If yes, how?

**Comment by ChaosWormz** [comment]
I use mapgen v6 in singleplayer. 

I can trigger this crash every time i try to go to  a certain spot on the map. which is new area

**Comment by est31** [comment]
Can you share the seed? This seems to be a noise exception.

**Comment by ChaosWormz** [comment]
4911283841526065781

**Comment by kwolekr** [comment]
Are you using any mods by any chance?

**Comment by ChaosWormz** [comment]
the only mods that i have installed that effect mapgen are ruins, sedimentology and caverealms

**Comment by kwolekr** [comment]
Could you post a link to the ruins mod?

**Comment by ChaosWormz** [comment]
https://forum.minetest.net/viewtopic.php?id=7200

**Comment by kwolekr** [comment]
Thanks, I couldn't find that one on the forum for some odd reason.

**Comment by kwolekr** [comment]
I tried flying around the area you crashed at with the same seed, same mapgen, and same mods for about 30 minutes and I couldn't get it to crash.  How often do you see this crash happen?

**Comment by ChaosWormz** [comment]
the area is 166 -1152 31 and it seems to crash a every time i go there

**Comment by kwolekr** [comment]
Hmmm, I tried a couple more times and I can't get a crash.  @est31, can you try??

**Comment by ChaosWormz** [comment]
well it seems it was  a mod that cause it after all might related to --flags = "absheight" in my morestones mod

**Comment by ChaosWormz** [comment]
The issue appeared to be related to my morestones mod even though it works fine in stable https://github.com/ChaosWormz/morestones/blob/master/init.lua

**Comment by est31** [comment]
I can reproduce with above seed, coordinates, and mtgame + morestones mod, nothing else.
[backtrace](https://gist.github.com/anonymous/1a0640ac45a9d8126100).
Bisected to breaking commit 18973f9af196ca48abfca25e05d4b1a396fdd871 "Ores: change ore chance in clusters to better respect clust_num_ores for dense clusters".

**Comment by paramat** [comment]
Odd i can't see an error.

**Comment by est31** [comment]
@paramat are your params:

* mgv6
* seed 4911283841526065781
* mtgame + morestones mod
* coords at 166 -1152 31?

**Comment by paramat** [comment]
Sorry, what i meant is, i can't see how that commit would cause a problem. My only guess is that one of the ores has a clust_size of 15 which causes:
pr.range(1, 3375)
Perhaps 3375 is too big a number for pr.range? I doubt it though.

**Comment by VanessaE** [comment]
3375 is indeed too big.  Max is 3276:

https://github.com/minetest/minetest/blob/master/src/noise.h#L39
https://github.com/minetest/minetest/blob/master/src/noise.h#L57

**Comment by est31** [comment]
So, what to do now? Forbid clust_size larger than 14 or 14.8? Find a way around it, removing the limit?

Either way, if there is an internal limit, it should be compared against already when the ore is registered. Then the mod author gets a big red arrow indicating "fix this please", instead of the engine crashing during mapgen.

**Comment by VanessaE** [comment]
If it's between 14.8 and 15.0, print a warning and cap it at 14.8.  If it is higher than 15.0, throw an error.

**Comment by paramat** [comment]
15 is huge for a cluster anyway, i think auto-cap at 14 and add info to docs.

**Comment by est31** [comment]
I like breaking more than auto-cap, it gives better feedback when developing a mod. Crash when registering the ore + info in docs?

**Comment by paramat** [comment]
> hmmmm 	paramat:  we can fix the oregen crash by switching to PcgRandom

Seems best.

**Comment by est31** [comment]
I guess so.
