### ISSUE TITLE
GUI setting for mouse_sensitivity 

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3229]
A GUI setting for mouse_sensitivity would be nice. And was requested in the forum few times.

**Comment by MoNTE48** [comment]
:+1:

**Comment by Heybye44** [comment]
:+1:

**Comment by lightonflux** [comment]
in c328478 the feature is exposed via GUI. But as everything is exposed it is not surprising. The current UI has to be refined. 
![bildschirmfoto von 2015-10-24 01 50 13](https://cloud.githubusercontent.com/assets/1377943/10707354/9b5a3a14-79f1-11e5-8d0e-39a2ac5c6c59.png)

**Comment by lightonflux** [comment]
Is the UI change permanent? If it is, then i would close this issue. Any comments?
