### ISSUE TITLE
Improve documentation of texture upscaling

### ISSUE THREAD

**Issue by garryo** [minetest/minetest#3251]
I use VanessaE's hdx64 texture set, but the server I visit has custom blocks not supported by hdx64.
However the minetest version I downloaded from github on 8th March 2015 upscales and blurs the server's custom blocks so that all blocks    appear to have the same 64 pixel resolution. 
The latest version from github (and versions going at least as far back as July) does NOT do this.

I have texture_min_size=64 in my config file, I have tried various values for this parameter and various filter settings to no avail.

[this screenshot](http://imgur.com/bCmQfg8) shows a plank block (supported by hdx) and stone tile and blue marble blocks (not supported). Unfortunately I can't show a "before" image because the strict protocol version policy in force on the server means I can no longer use the earlier client.

**Comment by PilzAdam** [comment]
Only textures with a resolution greater or equal to `texture_min_size` have the filters applied. The low resolution textures (probably 16x16 px) are smaller than your `texture_min_size` setting, so they aren't affected by the bi- or trilinear filter.

**Comment by garryo** [comment]
PilzAdam, thank you for your response. I see you have edited your post, but in fact your initial response was correct: if I set texture_min_size=16 then all textures 16px and larger have the filters applied, which was the result I wanted.
The comments in the code and minetest.conf.example are ambiguous, and despite looking at them repeatedly,  I would not have interpreted then this way without your comment.
Thanks again for your help.

**Comment by PilzAdam** [comment]
@garryo if my original comment was correct, then the doc here https://github.com/minetest/minetest/blob/master/minetest.conf.example#L292-L299 would be wrong. This needs to be reviewed.

**Comment by garryo** [comment]
@PilzAdam, I confirm that your original comment is indeed correct.
the comments in the .example file (and in the source: /src/client/tile.cpp ) should read something like:

#    When using bilinear/trilinear/anisotropic filters, low-resolution textures
#    can be blurred to remove pixellation and automatically upscaled using nearest-neighbor
#    interpolation.  This parameter sets the minimum texture size that will be filtered, that is to say
#    textures this size and larger will be filtered, smaller textures will not.
#    Powers of 2 are recommended.  Setting this will not have a visible effect 
#    unless bilinear/trilinear/anisotropic filtering is enabled.
#texture_min_size = 64
 
I would also suggest that the default value should be 16, not 64

**Comment by Warr1024** [comment]
Your suggested comment is still not really correct.  *All* textures, of *any* size, *are* filtered, when filtering is enabled.  This option just performs a nearest-neighbor filter on the texture *before* the hardware linear filters are applied.  That means that if your 16x16 texture is upscaled to 64x64, it will only be 1/4 as "blurry" as its 16x16 original would have been, when filtered by the hardware.

This option was added to allow people to enable linear/aniso filtering for some of its other benefits (such as reduced moire effects at long distance on some hardware, and aliasing "jaggies" within textures) without sacrificing the "pixellated" aesthetic that is MT's default.  How textures in MT "should" look is highly bikesheddable, hence, customizable.

**Comment by paramat** [comment]
Related recent change #6580 #6586

**Comment by paramat** [comment]
@lhofhansl ^

**Comment by siliconsniffer** [comment]
@Zughy 
Can this be marked as solved? The documentation was changed: https://github.com/minetest/minetest/issues/3251#issuecomment-355198883
