### ISSUE TITLE
Some Irrlicht messages bypass the Minetest log system

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#3255]
(This was NOT introduced by my logging changes BTW)

Sometimes Irrlicht bypasses the Minetest log system, apparently going directly to `stdout` (Minetest uses only `stderr` for log messages).
This results in:
- The timestamp/level/thread prefix not being printed,
- The message not being logged in debug.log,
- The message not being filtered out at low log levels,
- And, of course, the message being in `stdout` instead of `stderr`.

I tried to fix this when working on logging, with no success.

It seems that Irrlicht switches back and forth between the two modes freely.  It starts with `stdout`, switches to the Minetest system, and after that may switch back and forth some more.

This may be an upstream issue.

Example:

```
################ [Direct]
Loaded texture: /home/owen/minetest/minetest-dev/textures/base/pack/menu_header.png
################ [Through Minetest log system]
2015-10-15 13:42:11: WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
################ [~~~ Snip ~~~]
2015-10-15 13:45:57: WARNING[Main]: Irrlicht: Could not open file of texture: character.png
################ [Back to direct printing]
Loaded mesh: animal_gull.b3d
Could not open file of texture: character.png
Loaded mesh: character.b3d
Could not open file of texture: defense_paniki.png
################ [~~~ Snip ~~~]
Could not open file of texture: character.png
Loaded mesh: character.b3d
[Back to Minetest log system]
2015-10-15 13:46:07: WARNING[Main]: Irrlicht: Could not open file of texture: character.png
2015-10-15 13:46:07: WARNING[Main]: Irrlicht: Could not open file of texture: defense_paniki.png
2015-10-15 13:46:07: WARNING[Main]: Irrlicht: Could not open file of texture: character.png
################ [~~~ Snip ~~~]
```

**Comment by ShadowNinja** [comment]
After testing, it looks like this only happens in the main menu, if you enter a game it will work properly, but exiting to the menu will break it again.

**Comment by paramat** [comment]
Mentioning CONTENT_IGNORE and texture loading warnings here so that my duplicate can be closed.

**Comment by ShadowNinja** [comment]
@paramat: The first chunk of messages is indeed because of this issue, but the second chunk isn't.  It's simply messages that were moved from infostream to warningstream.

**Comment by paramat** [comment]
Ok.

**Comment by Zughy** [comment]
Since Irrlicht development is now handled by Minetest core devs, please reopen this issue (if it still persists) in the specific repo: https://github.com/minetest/irrlicht
