### ISSUE TITLE
Various new messages appearing in terminal

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3257]
Possibly due to the 'refactor logging' commits by ShadowNinja and kwolekr.
Switching back and forth between menu tabs causes these messages to repeat:
```
Loaded texture: /home/matstandard/minetestf/gitmods/minetest/games/minetest_game/menu/header.png
Loaded texture: /home/matstandard/minetestf/gitmods/minetest/textures/base/pack/menu_header.png
Loaded texture: /home/matstandard/minetestf/gitmods/minetest/games/minetest_game/menu/header.png
Loaded texture: /home/matstandard/minetestf/gitmods/minetest/textures/base/pack/menu_header.png
...
```

New messages appearing:
```
WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
```

```
WARNING[Main]: Irrlicht: Could not open file of texture: character.png
```

**Comment by HybridDog** [comment]
they are infostream messages, aren't they?

**Comment by ShadowNinja** [comment]
* The first set isn't caused by my changes.  Before they were removed because the Irrlicht log level was set to the Minetest debug.txt log level, which broke having a seperate console and debug.txt log level.  I removed this, electing to pass the messages through Minetest's normal filtering mechanism, but some Irrlicht messages bypass this, going directly for `stdout` instead.  I don't know why this happens.  See #3255.  To reiterate, my logging changes don't cause this, they just make the bug more visible.
  * This used to be sent to `infostream` with a `WARNING` prefix, so I changed it wo warningstream.  The message should be removed by addressing its cause.
  * This is probably due to the same bug that causes issue 1.

**Comment by est31** [comment]
Either way, I do confirm that the verbosity increased.

**Comment by paramat** [comment]
register.lua seems to be redefining air, unknown and ignore using ':ignore' etc.
nodedef.cpp prints the message because '// Don't allow redefining ignore (but allow air and unknown)'.
Seems this have always been happening but the message is only seen now. The other 2 issues seem harmless.

**Comment by kwolekr** [comment]
I think this issue can be closed out if the actual errors that were being hidden before get fixed, such as the duplicate air definition, etc.
Is anybody working on this?

**Comment by paramat** [comment]
This issue is just to notify of new messages appearing, here's 2 more i've noticed:

WARNING[Main]: BanManager: creating /home/matstandard/minetestf/gitmods/minetest/bin/../worlds/flatnew/ipban.txt

 WARNING[Main]: Map::getNodeMetadata(): Block not found

**Comment by paramat** [comment]
Lots of these in mgv6:

2015-11-12 10:35:56: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:36:21: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:36:25: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:36:33: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:36:55: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:36:58: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:37:05: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:37:05: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:37:11: WARNING[Main]: Map::getNodeMetadata(): Block not found
2015-11-12 10:37:33: WARNING[Main]: Map::getNodeMetadata(): Block not found

**Comment by ShadowNinja** [comment]
@paramat
  * That's probably printed on new world creation.  It doesn't seems like it's really a warning though, so it should just be moved to `infostream` probably.
  * This may be an issue, or it may be something that happens frequently and doesn't really matter, in which case it should be moved to `infostream` or even `verbosestream`.

**Comment by ShadowNinja** [comment]
Further research on the "Could not open file of texture" warning:
When Irrlicht loads a mesh like `character.b3d` it automatically tries to load any textures mentioned in that file (eg, `character.b3d` mentions `character.png` so Irrlicht tries to load `character.png` from the current directory).
Removing the texture from `.x` files seems to work, but removing the `TEXS` section from a `.b3d` file causes Irrlicht to hang.
There doesn't seem to be a way to disable the auto-loading, therefore this appears to be an **upstream issue** in Irrlicht.

**Comment by Fixer-007** [comment]
Hmm, I was plain custom game (extreme_survival) and noticed this:
comes huge lag (max_lag jumps to 11)
then:
4407 "WARNING[Server]: Map::getNodeMetadata(): Block not found" errors
2016-04-01 16:11:59: ACTION[Emerge-0]: Created mine at (-1566,-74,-25)

So, I think in this case tsm_mines mine generator caused 4407 errors with lag.

**Comment by paramat** [comment]
See #3255

**Comment by est31** [comment]
Yeah its a dupe

**Comment by ShadowNinja** [comment]
@est31: Not quite.  The CONTENT_IGNORE and texture loading warnings aren't mentioned in the other issue.

**Comment by paramat** [comment]
Copied messages seen inot the other thread #3255

**Comment by DerpyPony25** [comment]
-------------
  Separator
-------------

2016-06-07 21:33:34: WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition

what can i do?
