### ISSUE TITLE
use_texture_alpha doesn't work together with the colorize texture modifier

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3259]
l tried to use the modifier to reduce the amount of laser node textures by 7 files, 770 Bytes.
But then l saw that colorize does not only break normalmaps, see the picture, the green one is a colorized derivate of the white one:
![screenshot_20151016_192724](https://cloud.githubusercontent.com/assets/3192173/10548646/8378daa0-743c-11e5-9b4d-a8cee68cbb6d.png)

**Comment by BlockMen** [comment]
Please post you colozize modifier, i can't reproduce the issue

**Comment by HybridDog** [comment]
the mod is there:
https://github.com/HybridDog/laser/blob/master/init.lua#L266

>i can't reproduce the issue

it might only work if shaders are enabled

**Comment by BlockMen** [comment]
You must specify the alpha value for you color, by default it's 255 which is opaque like in your screenshot.
You can set the alpha value as 4th part of the hexadecimal number OR as integer from 0-255, see https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L350

**Comment by HybridDog** [comment]
Which alpha value would l need to use to use the texture alpha?

**Comment by BlockMen** [comment]
Idk what value would be best for your needs, maybe look here, it could help you: https://forum.minetest.net/viewtopic.php?f=11&t=13303

**Comment by PilzAdam** [comment]
@BlockMen @HybridDog wants to use the alpha value supplied by the texture, not a fixed one.

**Comment by BlockMen** [comment]
@PilzAdam colorize modifier overlays a texture per pixel with given color and alpha ratio 0-255. So if he uses an alpha value = 255 the result will be an opaque color. A modifier you specified is currently not implemented AFAIK

**Comment by HybridDog** [comment]
It's not possible to make colorize test if the node uses texture alpha, is it?

>https://forum.minetest.net/viewtopic.php?f=11&t=13303

l think colorize also works without texture on which it is applied (paintings mod).
@tenplus1 so maybe you could remove the ```cblocks.png^```
