### ISSUE TITLE
Logfile Option Crashes Minetest on Startup

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#3262]
Minetest Commit:  6be74d1

When using the option to **not** produce a debug.txt file, Minetest will crash on start-up.

```
./minetest --logfile ''
```

Produces:

```
ERROR[Main]: An unhandled exception occurred: Failed to open log file : No such file or directory
ERROR[Main]: In thread 7f6c192d07c0:
<mypath>/minetest/src/main.cpp:e5: int main(int, char**): A fatal error occured: Failed to open log file : No such file or directory
ERROR[Main]: Debug stacks:
ERROR[Main]: DEBUG STACK FOR THREAD 7f6c192d07c0:
ERROR[Main]: #0  int main(int, char**)
(core dumped)
```

**Comment by PilzAdam** [comment]
Why not use `/dev/null`?

**Comment by est31** [comment]
@LazyJ Is it a regression, so that it worked earlier, and now it doesn't?
When did it work last?

**Comment by PilzAdam** [comment]
Maybe related: I notice that Minetest creates a `debug.txt` in the directory where I start it from. This is new, AFAIR.

**Comment by kilbith** [comment]
> Minetest creates a debug.txt in the directory where I start it from.

Confirmed. I have a newly appeared `debug.txt` in my home directory, it's generated anywhere where MT is started from.

**Comment by zhangjunsin** [comment]
It seems to be the caused by the newly introduced function `init_log_stream()` in `src/main.cpp`, replacing the old `init_debug_stream()`. This function no longer checks whether `log_filename` is empty or not, so an empty string was sent to `file_log_output.open()`.

**Comment by zhangjunsin** [comment]
Created a pull request https://github.com/minetest/minetest/pull/3272

**Comment by est31** [comment]
@PilzAdam our doc (`minetest --help`) claims this method works: `--logfile <value>     Set logfile path ('' = no logging)`
