### ISSUE TITLE
Allow to define an entity as transient.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3278]
It would be very useful if we would be able to define an entity as transient, meaning that it is not permanently saved in the map data and therefor lost on shutdown.

The exact use-case for me would be attaching a [shadow to a player](https://github.com/minetest-australopithecus/minetest-australopithecus-player-shadow/), this entity does not need to be persisted as it can/will be re-added and attached to the player upon join. Currently my solution suffers from #2546, which makes it not possible to remove entities on shutdown.

**Comment by PilzAdam** [comment]
Your use-case is a hack, but adding this functionality might be useful for other things. Maybe adding an `on_unload()` callback that is called when the object is saved to disk would be more flexible.

**Comment by RobertZenz** [comment]
As long as there is the possibility to cancel the saving of the entity.

Do you mean "hack" as in "well, attached entities weren't supposed to be used this way" or as in "there's another possibility"?

**Comment by ShadowNinja** [comment]
> Maybe adding an on_unload() callback that is called when the object is saved to disk would be more flexible.

This already exists, `get_staticdata`.

This feature would also be useful for the WorldEdit markers.

**Comment by C1ffisme** [comment]
And if you have entities attached to a node, say a turret or something. Then the node might think the entity isn't there, and suddenly your turret shoots twice as many shots.

**Comment by raymoo** [comment]
I don't think the suggested use-case is a hack, since visual effects in general are things that shouldn't be persisted. There is also the related case where entities are merely visual representations of something persistent that a mod keeps track of in its own table somewhere, and basically uses entities to draw itself.

**Comment by sofar** [comment]
@shadowninja but does the core code save the entity if `get_staticdata() == null` ?

**Comment by raymoo** [comment]
@sofar No, it just uses empty string for the staticdata.

**Comment by raymoo** [comment]
I mean yes, it does save it, just with empty staticdata.

**Comment by Ferk** [comment]
Related: #6084

There could be an ``on_deactivate`` that gets called when the entity unloads and depending the return value it removes the entity completely or just saves normally so it can get reloaded.

**Comment by SmallJoker** [comment]
> It would be very useful if we would be able to define an entity as transient, meaning that it is not permanently saved in the map data and therefor lost on shutdown.

`static_save = false`, added in https://github.com/minetest/minetest/pull/5112
Issue solved.

> There could be an on_deactivate that gets called when the entity unloads and depending the return value it removes the entity completely

That's a more detailed request for the implementation of that callback. Belongs into #6084
