### ISSUE TITLE
Don't waste bandwidth by sending a player's position to the player in cause

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#328]
Whenever the server sends a player's position to clients, it also sends it to the player in cause. The local player already knows his own position and actually informs the server of it, so this wastes bandwidth for no reason.

I attempted to fix it myself, but I couldn't understand the ActiveObjectMessage structure so I'm posting here for others to look at. Although it might be useful for debugging, I believe it's most important to reduce and optimize networking as much as possible and not waste packets... especially now that we send 10 player updates per second instead of 5.

Technical stuff: content_sao.cpp updates the position of a player to clients at line 1134 (where it checks m_position_not_sent). This is only executed after that player's client sends a new position to the server. But this code simply adds a new object message to the aom list, and it can't filter the destination. We need to know if the player that would receive the update is the player we're informing about, and abort of so.

**Comment by nerzhul** [comment]
this issue is tagged as won't fix and very old. I close it
