### ISSUE TITLE
force_place for decorations

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#3282]
Maybe I'm just stupid and don't do enough research, but as I know there is no way to make sure that a decoration being placed isn't being destroyed by mapgen. Most of my buildings walls are filled with leaves, and look more like ruins.

Is this impossible, is there a feature for this, or is it yet to be made?

**Comment by RHRhino** [comment]
Did you tried ["is_ground_content = false"](https://github.com/minetest/minetest/blob/59fa117d13ba881f6f5e77c94f5a4ce6adb9647f/doc/lua_api.txt#L3187) ?

**Comment by C1ffisme** [comment]
This is about schematics, not singular blocks.

Sorry about this. I just realized force_placement exists as a flag. (facepalm)

One of these days, I'll get a life. :angry:
