### ISSUE TITLE
Getting mmdb to work again

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#3289]
The mmdb has not been working for quite a while. As i believe that is brings quite a big benefit to users i would like to work on getting it to work again.
Sadly my current internet connection is too bad to maintain a stable irc connection :(
There are/were multiple issues, as far as i can remember (feel free to contribute)
- [ ] Thexyz stopped hosting the minetest websites, @celeron55 now does that, but did not yet set up the mmdb.

If there is any trouble with that feel free to contact me.
- [ ] The database (as in the sql database) seems to have had some inconsistency issues

Well, at least think it did, i never had access to the database to diagnose. If i am right then they were introduced by switching the forum software, which caused a renaming of tables. @celeron55 do you have a dump of the old database, or are we starting from scratch? resolving these inconsistencies is rather trivial, mainly consists of finding and removing foreign key contraints, or never even creating them.
- There are some Features missing from the mmdb, please do comment on those, and add things i forgot.
  - [ ] Halfautomatic release creation from repository. This requires cellery for asynchronous task execution, and i did not want to ask for that to be set up, as thexyz seemed hesitant hosting the stuff that was already there.
  - [ ] Automatic release creation on commit. I am not quite sure supporting that would be a great idea, as currently the mmdb has a review system, and reviewing mods on each commit would be… well a lot of work, to say at least.
  - [ ] removal of the review system. With the latest changes to mod sandboxing the reviewing might not be necessary any more.
  - [ ] be more flexible about authorship.
- Some client side things might be nice to have, too:
  - [ ] UI improvements (low prio)
  - [ ] respecting reviewed status #1053 (in case that does not get dropped, and minetest version compatibility
  - [ ] automatic resolving of dependencies (thats the reason i originally started the mmdb^^)

Yeah, so please do contribute to this discussion, so we know what the general/community expection of the mmdb is, so we can adapt it to that.
The current code for the mmdb lives at https://bitbucket.org/iqualfragile/mmdb/

**Comment by rubenwardy** [comment]
It should also be possible for other (trusted) users to add other author's mods onto mmdb, in case the authors have gone inactive. The Minetest client should maybe also include a download from git option.

**Comment by rubenwardy** [comment]
Have a look at these project which have sprung up whilst mmdb was gone:

* [http://github.com/rubenwardy/mtpm](Minetest Package Manager)
* [http://github.com/rubenwardy/mtpm_lists](Minetest Package Manager Lists - Forum Parser)
* [https://minetest-bower.herokuapp.com](Minetest Bower)

I think that forum parsing then editing is a good way to go. Most of the information can already be detected from the title and the message. Just not categories.

**Comment by iqualfragile** [comment]
Browsing the forum to import mods was not wished for when i wrote the mmdb, but it can be done.

**Comment by rubenwardy** [comment]
You'd need to go through and check all the imported information.

**Comment by est31** [comment]
1. IMO we should turn on mod sandboxing by default for the mods, and, until #3132 is resolved, we should disable the ability to execute trusted mods alongside mods from the mmdb. Then in turn the review system can be more relaxed.

1. I don't think we should go with a completely moderation-less system, where everybody just uploads their mod to WIP mods and it gets automatically added. What we could do is to scan for the mod releases category, and increase moderation in that topic (move mods that fail one of the conditions to some other category, etc).

1. Where is the server side of the mmdb? I can't find the source, it should be a repo in the minetest
project IMO.

1. The UI of the mod store is totally ugly. This isn't a low priority problem IMO, but blocks the re-addition.

1. release-per-commit sounds good, we should perhaps make it possible to change the release-per-commit-or-per-git-tag setting per mod.

**Comment by iqualfragile** [comment]
> 3.
It is thinkable to run automated scripts on the mod releases to check for things, but these must never actually load lua code or anything for security reasons.
> 6.
This is impossible to combine with reviewing mod releases.
> 4.
https://bitbucket.org/iqualfragile/mmdb/
here, added to first post.

**Comment by celeron55** [comment]
One practical thing you need to take into account is that I run OpenBSD on my server, so mmdb has to be able to run on OpenBSD in order for me to host it.

**Comment by iqualfragile** [comment]
OpenBSD should not be a problem compatiblity-wise, but the last time i looked at a bigger benchmark it was performing horrible for things like fork and bind and stuff, so it might be a performance problem if many people want to access the mmdb (or the website in general) at the same time (then again those benchmarks are quite old, sadly i did not really find newer data to cite)

Well, that might be because MySQL was/is castrated by oracle for them to have an argument to sell their "pro" version. the mmdb runs on postgres, that was actually my local setup, and i was suprised when the old server ran mysql (which did not matter thought)

You won't have to be fixing things all the time, the only things that made work for the server administrator in the past were pulling from upstream from time to time, in some cases installing new dependencies, and the forum software switch.
Shell access would have allowed me to do the first and third thing myself (which i would be happy to do) so that might be a good idea.

**Comment by tobyplowy** [comment]
@est31 Is this still being worlds on?

**Comment by rubenwardy** [comment]
Why ping him specifically?

The answer is no. And I don't think MMDB will ever be up again

#4082 is much more promising, imo

**Comment by tobyplowy** [comment]
@rubenwardy look at https://github.com/minetest/minetest.github.io/issues/76

**Comment by rubenwardy** [comment]
This project does do that, just not very well. And it needs a new maintainer - I'm not willing to work on mmdb, and nobody else seems to be

**Comment by iqualfragile** [comment]
i am generally (still) willing to work on this, just have not heard anything from @celeron55 about the hosting.
one time forum parsing is a good idea imo, for some reason we decided against that a while ago for the mmdb, i don't know why anymore, just that there was a discussion.
continious parsing of the forum to keep the modstore up to date as opposed to a migration is not the best idea in my opinion, as i believe forums are not the best way to present and work with mods.
therefore having a single source of authentification would be quite useful, so either run both the modstore and the forum on a single server, or have some kind of kerberos/oauth-like protocol up and runnnig.

**Comment by rubenwardy** [comment]
This reply talks about my future design, which will reuse mtmods4android_server but will be heavily modified.

> continuous parsing of the forum. i believe forums are not the best way to present and work with mods

The only reason you reparse the forum is to:

* Find new mods
* Find changed download links

The forum in my design is only used to find mods. It gets from the forum:

* Download URL / Github
* Author (overridden by mod.conf)
* Basename (overridden by mod.conf)
* Title (overridden by mod.conf)

It then uses the GitHub API or a raw download to get more information from mod.conf
Other VCS sites will have similar APIs.

As for mod updates, it'll poll the mod's link for updates, say twice a day.
There'll also be a form to allow users notify the system when there is an update.

> single source of authentification 

They won't need to sign in to update their mod's meta (title, basename, description, depend, license info) - they can do that from the download URL.

They'd only need to log in if they need to correct a mistake made by the forum parser - say a wrong URL or download link. And whilst it would be much better to allow signing in using the PhpBB token, [you don't need to](http://blog.rubenwardy.com/2016/05/07/2100-link-external-phpbb-forum/).

**Comment by iqualfragile** [comment]
> Please do - if all the points in the opening post are fulfilled, then I'll be happy
well, i want to know that the work would not go to waste, so the hosting would need to be out of the way

> phpbb-cookie
thats already done, and works, if people are logged into the forum they are automatically logged into the mmdb, too, smooth transistion

about your approach: how do you address the actual presentation of the mods, short description, long description, a galery, a comment/rating system, etc? without a login that might be a bit hard.

checking more then 200 mods every 12 hours seems like a lot of work

when reparsing the forum posts, what exactly is the merge strategy with existing data?

proposal: quickly get the mtmods4android to work, so it basically acts as a proxy/gateway between the minetest forum and the minetest client, so people can use something right now, then i/we work on the mmdb, and, once its done, migrate the minetest-mods subforum over to the mmdb. that seems like the most pragmatic solution.

**Comment by rubenwardy** [comment]
* short description -> first line of description.txt
* long description -> description.txt
* a gallery -> screenshot.png
* a comment -> forum topic
* rating system -> not supported, 

> checking more then 200 mods every 12 hours seems like a lot of work

500 mods every 12 hours is 42 per hour, which is one mod per 1.5 mins. It doesn't take that long to perform a zip download, let alone a RESTful API call if on GitHub

> proposal: quickly get the mtmods4android to work, so it basically acts as a proxy/gateway between the minetest forum and the minetest client, so people can use something right now, then i/we work on the mmdb, and, once its done, migrate the minetest-mods subforum over to the mmdb. that seems like the most pragmatic solution.

For a temporary solution, all I'd need to add is checking for updates. A more permanent solution would need a rewrite as it wasn't originally designed to do this

**Comment by ShadowNinja** [comment]
> 500 mods every 12 hours is 42 per hour, which is one mod per 1.5 mins. It doesn't take that long to perform a zip download, let alone a RESTful API call if on GitHub

If you use If-Modified-Since this probably won't be an issue, although it does seem a little clumsy.

**Comment by rubenwardy** [comment]
> If you use If-Modified-Since this probably won't be an issue, although it does seem a little clumsy.

mmdb would require you to manually update anyway

--------

If mmdb actually worked, then I wouldn't have needed to make mtmods4android_server anyway. The reason I choose to use the forum parser design is because it's passive and didn't require mod makers to file their own mods. It's the simplest way to add a ton of mods and keep it up to date

**Comment by nerzhul** [comment]
please note mmdb should prepare future and take care about serverside mods and client side mods, whereas there is no clientside modding atm

**Comment by BrunoMine** [comment]
I am very enthusiastic about this project. A template that will be a better way to install mods in the future. Installing mods is a better thing in minetest.

I do not want to disrupt or upgrade development, but I wish I could already think of the translations of the mods. It may be interesting that languages are identified and descriptions are translated (when possible).

**Comment by paramat** [comment]
Is it worth working on? Is #4082 better?

**Comment by iqualfragile** [comment]
#4082 was made and closed by rubenwardy, so im not sure he things its viable?

about this issue: i am waiting for the person hosting the forums right now to get in contact to re-deploy the software, but that has not happened for like 2 years

**Comment by rubenwardy** [comment]
Have you asked him?

**Comment by nerzhul** [comment]
i can propose a different concept foçr this as a early stage, creating a new app as a webservice using GH repo as a registration model to know the apps and the versions, if you are interested

**Comment by rubenwardy** [comment]
nothing's happening with this, and #4666 covers mod store stuff anyway

**Comment by paramat** [comment]
No response from author, continue discussion in #4666
