### ISSUE TITLE
Shadows look different in formspec tables

### ISSUE THREAD

**Issue by kaadmy** [minetest/minetest#3293]
I haven't confirmed this yet, but it seems that text shadows in formspec tables use a fixed alpha, instead of using your configuration's text shadow alpha.
I think this is very low priority, and that I could fix, but I can't find where in the code it is.

**Comment by BlockMen** [comment]
Actually that shouldnt happen, since it simply uses the current skin font, see https://github.com/minetest/minetest/blob/master/src/guiTable.cpp#L71

Could you provide a screenshot that shows it?

**Comment by kaadmy** [comment]
Never mind, it was just me. It's the same alpha if I check it in GIMP.
