### ISSUE TITLE
write_json doesn't write anything, it just return a JSON

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#3294]
Why it called then `write_json` instead of `convert_to_json`, `json_stringify` or something like that?

**Comment by ShadowNinja** [comment]
To be consistent with `read_json`.  The idea is that it writes the data as JSON to a string (and returns it).

**Comment by rubenwardy** [comment]
It's `parse_json - https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2317

To be consistent with `serialize()` and `deserialize()` for .lua, I think it should be called `serialize_json` and `deserialise_json`

**Comment by neoascetic** [comment]
Why use json at all if we have lua?

**Comment by ShadowNinja** [comment]
@neoascetic: Because JSON is supported out of the box by just about everything, Lua isn't.

**Comment by neoascetic** [comment]
Oh, to be compatible for third-party utilities. Got it.
