### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ChaosWormz** [minetest/minetest#3296]
[ 24%] [ 25%] [ 25%] Building CXX object src/CMakeFiles/minetest.dir/client/tile.cpp.o
    Building CXX object src/CMakeFiles/minetest.dir/client/clientlauncher.cpp.o
    Building CXX object src/CMakeFiles/minetest.dir/network/clientopcodes.cpp.o
    [ 26%] Building CXX object src/CMakeFiles/minetest.dir/network/clientpackethandler.cpp.o
    [ 26%] Building CXX object src/CMakeFiles/minetest.dir/network/connection.cpp.o
    [ 27%] Building CXX object src/CMakeFiles/minetest.dir/network/networkpacket.cpp.o
    [ 27%] Building CXX object src/CMakeFiles/minetest.dir/network/serveropcodes.cpp.o
    [ 27%] Building CXX object src/CMakeFiles/minetest.dir/network/serverpackethandler.cpp.o
    [ 28%] Building CXX object src/CMakeFiles/minetest.dir/script/common/c_content.cpp.o
    [ 28%] Building CXX object src/CMakeFiles/minetest.dir/script/common/c_converter.cpp.o
    [ 28%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_async.cpp.o
    [ 29%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_env.cpp.o
    [ 29%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_item.cpp.o
    [ 30%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_mainmenu.cpp.o
    [ 30%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_node.cpp.o
    [ 31%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_nodemeta.cpp.o
    [ 31%] Building CXX object src/CMakeFiles/minetest.dir/script/cpp_api/s_security.cpp.o
    [ 31%] [ 32%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_areastore.cpp.o
    Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_base.cpp.o
    [ 32%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_craft.cpp.o
    [ 32%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_env.cpp.o
    [ 33%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_inventory.cpp.o
    [ 33%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_item.cpp.o
    [ 34%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_mainmenu.cpp.o
    [ 34%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_mapgen.cpp.o
    [ 34%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_nodemeta.cpp.o
    [ 35%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_nodetimer.cpp.o
    [ 35%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_noise.cpp.o
    [ 36%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_object.cpp.o
    [ 36%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_particles.cpp.o
    [ 36%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_rollback.cpp.o
    [ 37%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_server.cpp.o
    [ 37%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_settings.cpp.o
    /home/chaoswormz/Documents/minetest/src/script/lua_api/l_server.cpp: In static member function ‘static int ModApiServer::l_get_modnames(lua_State*)’:
    /home/chaoswormz/Documents/minetest/src/script/lua_api/l_server.cpp:380:2: error: ‘sort’ is not a member of ‘std’
      std::sort(modlist.begin(), modlist.end());
      ^
    [ 38%] make[2]: *** [src/CMakeFiles/minetest.dir/script/lua_api/l_server.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_util.cpp.o
    make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
    make: *** [all] Error 2

**Comment by BlockMen** [comment]
see also: https://travis-ci.org/minetest/minetest/builds/87610357

**Comment by BlockMen** [comment]
fixed by https://github.com/minetest/minetest/commit/c406438b95e3df181961add56a2511b96bd9d690
