### ISSUE TITLE
Allow in-line commenting in minetest.conf

### ISSUE THREAD

**Issue by davisonio** [minetest/minetest#3304]
For example, I add a setting to minetest.conf and add a small comment explaining what it does:

```
foo = bar #This sets foo to bar
```

...but when I use `minetest.setting_get("foo")` it returns:

```
bar #This sets foo to bar
```

It would be great if anything after `#` isn't part of the value, or at the very least a warning is displayed showing that the comment is part of the setting.

**Comment by ShadowNinja** [comment]
Note that this would break current IRC mod configurations (channel name).  This wouldn't be too much of an issue as long as there was an escape sequence though.

**Comment by PilzAdam** [comment]
This is not needed; escape sequences will probably confuse some users.

**Comment by rubenwardy** [comment]
:-1:

It over complicates it, and makes you need to define ways to escape.

**Comment by BlockMen** [comment]
I would like to have a way to escape the row.

**Comment by rubenwardy** [comment]
That would be good.

**Comment by est31** [comment]
:-1: don't think that's neccessary. next we want conditionals and while loops.

**Comment by est31** [comment]
Sorry, wrong button.

**Comment by paramat** [comment]
No support and is not needed, you can put your comment above the line.
