### ISSUE TITLE
Mapgen bug with clang 3.7

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#3306]
I build every time with clang.
Since this week mapgen is silly with clang 3.7 on Archlinux. gcc 5.2 works fine.

Here is what the mapgen does with clang
![capture d ecran de 2015-10-28 22-47-53](https://cloud.githubusercontent.com/assets/119752/10832248/98a92878-7e8a-11e5-8ce3-5a8343b24ba4.png)

**Comment by kilbith** [comment]
Same thing happened 2 weeks ago to me : http://irc.minetest.ru/minetest-dev/2015-10-17#i_4426712

... when using Clang 3.7 (Arch Linux) for compiling. GCC does not produced such bug. I'm not yet sure whether it's a causality.

**Comment by nerzhul** [comment]
I tested on FreeBSD with Clang 3.7: same bug as on Archlinux. On FreeBSD with clang 3.6 mapgen is correct.

**Comment by nerzhul** [comment]
No problem with FreeBSD 10.2 embedded clang 3.4.1.
Problems seems related to clang 3.7.0

**Comment by nerzhul** [comment]
tested on clang-devel (3.8) same problem.

I also tried to rollback my git tree to two months ago and the problem was also there

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/commit/d198e420ec54be47fe2285b3205953282ec06742

Can be closed ?

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/d198e420ec54be47fe2285b3205953282ec06742
