### ISSUE TITLE
Feature request: Relative /teleport

### ISSUE THREAD

**Issue by fireglow** [minetest/minetest#3311]
Hi,
this is a feature request for relative /teleport along the given axis:

```
/teleport [x/y/z] [distance]
```

e.g.

```
/teleport x -100
```

**Comment by indriApollo** [comment]
Could U use multiple parameters like : 
```
/teleport x -100 z +10
```
?

**Comment by 0-afflatus** [comment]
why? just curious.

**Comment by est31** [comment]
:-1: I think this can be done by a mod instead, it shouldn't be added to the engine.

**Comment by ChaosWormz** [comment]
I already have a mod that does this

**Comment by PilzAdam** [comment]
@est31 I think this should be done in the engine. The engine adds this command, so it should be done properly. Also there is no easy way for mods to hook into an existing chat command, to enhance it's functionality, so mods need to create a new command for that, which is bad for the end-user.

**Comment by est31** [comment]
Okay then. What you say makes sense.

**Comment by paramat** [comment]
:-1: Not much need for this, teleportation is usually to a distant co-ordinate.

**Comment by C1ffisme** [comment]
I can see uses for this in command blocks, and if you just want to get out of a door-less area without having to use math or remember coordinates.

**Comment by o-jasper** [comment]
Well, `/teleport` is already defaultly in there. Perhaps it could do relative simply by detecting numbers starting with `r` as being relative.

Note: [teleport requests](https://github.com/ChaosWormz/teleport-request) already exists too. Best to keep requests in separate command. Separates admin action from userlike action, and no messing up code accidentally giving teleport.

**Comment by C1ffisme** [comment]
What about allowing a number to be changed from it's original value in a command? (For the syntax, I'll use Minecraft's "~(number)".)

This wouldn't just apply to teleportation, for example, set the time to an hour later:

/time ~1000

**Comment by paramat** [comment]
Can we close this? I see very little usefulness.

**Comment by octacian** [comment]
I'd say no. This could definitely be useful. Let's say you want to teleport 100 blocks up in the y axis. Right now you might type something like `/teleport 391 100 590`, whereas properly implementing a feature like this could allow typing something like `teleport ~ 100 ~` (syntax could probably be improved).

**Comment by paramat** [comment]
> Let's say you want to teleport 100 blocks up in the y axis.

If they want to move a certain distance in a certain drection they can look at their F5 co-ordinates and add 100 (it will improve their maths skills too). I've been teleporting frequently while developing for 4 years and not once wished for something like this. For the use in mods it is very simple lightweight maths to add a relative movement to a world position.

Features need justification, we can't just add everything that is thought up. There is only 1 request for this (by the author) in 1.5 years, and C1ffisme's use case is very easily done with a single vector addition in a mod.

PIlzAdam wrote:

> The engine adds this command, so it should be done properly

This is wrongly asserting that for teleporting to be 'proper' it has to have relative motion.

**Comment by octacian** [comment]
It can be very annoying having to look at the f5 coordinates and then back to chat, and back to the f5 coordinates again if you got part of it wrong.

> we can't just add everything that is thought up

True, true. However, it's many of the little details like this that make a game (or any program for that matter) enjoyable to use.

**Comment by paramat** [comment]
Good point, but the issue of F5 information not being easily visible when writing a command is a separate issue which should be fixed, it doesn't justify this.

We can still add little details as long as they are justified.

**Comment by C1ffisme** [comment]
> If they want to move a certain distance in a certain drection they can look at their F5 co-ordinates and add 100 (it will improve their maths skills too)

Computers are for doing math. Games should be educational when the game intends for you to learn, not when you just want to do something that should be simple and easy to do.

**Comment by paramat** [comment]
Any core dev support?

**Comment by Ezhh** [comment]
This has been done in mods (teleport_request has a command for it) and works fine in mods. I don't see why this would need to be included in the engine...

**Comment by paramat** [comment]
Very old issue with no core dev support, was closed before and PilzAdam is no longer here.
Engine chat commands have to br kept minimal, this is a fancy specialist feature a mod can do.
