### ISSUE TITLE
Compilation warning "typedef locally defined but not used"

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3316]
Regression of commit 688556a5d1910ead2cf06a87af6908110fa9d035
You'll get a warning like:
```
src/minetest/src/log.cpp:233:3 warning: typedef ‘mismatch_between_loglevel_names_and_enum’ locally defined but not used [-Wunused-local-typedefs]
   mismatch_between_loglevel_names_and_enum);
```

**Comment by kwolekr** [comment]
Pretty dumb warning if you ask me.  Google tells me this is in both gcc since 4.8 and clang since 3.7.

We could add  -Wno-unused-local-typedefs  to the cflags, or (even better) the  __attribute__ ((unused)) decorator is supposed to fix this.

**Comment by est31** [comment]
How would the `__attribute__` decorator look like?

**Comment by kwolekr** [comment]
Like this:  https://github.com/minetest/minetest/commit/6ba4f3775e9b2a5bacb2537c058728a67222b67d
