### ISSUE TITLE
Fast movement when autorun and forwarding.

### ISSUE THREAD

**Issue by Rui914** [minetest/minetest#3319]
W key + Autorun Enable = Fast move
after b6dfae0.

**Comment by zhangjunphy** [comment]
It is in fact related to https://github.com/minetest/minetest/commit/b6dfae02215d7bd61e06ff1999ee3ecb0ec80b9e. 
Autorun is implemented with `continuous_forward`. According to  [src/localplayer.cpp](https://github.com/minetest/minetest/blob/6ba4f3775e9b2a5bacb2537c058728a67222b67d/src/localplayer.cpp#L518-L524), `continuous_forward` will give player `superspeed` if the key for `control.up` is pressed.
Either the behavior of `continuous_forward` or the implementation of autorun need to be changed.

**Comment by est31** [comment]
1550ab3c5d17787bcb9885c045db2f07aa4971ac
