### ISSUE TITLE
noise_threshhold should be noise_threshold

### ISSUE THREAD

**Issue by davisonio** [minetest/minetest#3321]
https://en.wiktionary.org/wiki/threshhold

**Comment by paramat** [comment]
Indeed, where is it misspelled?

**Comment by CraigyDavi** [comment]
https://github.com/minetest/minetest/blob/ffe291cb78fc7135034fe6456b2d7dfc3761dc52/games/minimal/mods/default/mapgen.lua#L39

https://github.com/minetest/minetest/blob/d69ef6acd386ccfd5ff456002591b97b92a26956/src/script/lua_api/l_mapgen.cpp#L947

https://github.com/minetest/minetest/blob/50ba7e114d0937061f988c9452904dd2456399b5/doc/lua_api.txt#L780

**Comment by kwolekr** [comment]
Oops...
Well, those can't be changed, but you could deprecate the "threshhold" fields and add a field with the correct spelling.

**Comment by davisonio** [comment]
Fixed in https://github.com/minetest/minetest/commit/a78dd7f2b6b0e1fefdbaa1ae21b722dd4459e4f4 :smile:
