### ISSUE TITLE
item_image_button "label" has multiple uses

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3322]
label is more useful to pass a value for the "name" key (name=label is passed in fields when the image button is pressed) but the label is also plastered on top of the image. this seems redundant since the idea of item_image_button is that there are tooltips already handily generated from the itemstring, and so a label seems useless especially since they don't fit in the image unless it is huge, and even more especially since the label has a use in passing a value for name. can the display of the lable simply be turned off please?

**Comment by paramat** [comment]
Comments?

**Comment by paramat** [comment]
Any core dev support?

**Comment by paramat** [comment]
Not sure if this is a bug report or a feature request.

**Comment by paramat** [comment]
Request needs consideration.
