### ISSUE TITLE
Disabling sneak glitch doesn't work anymore

### ISSUE THREAD

**Issue by PilzAdam** [minetest/minetest#3323]
`player:set_physics_override({ sneak_glitch = false })` doesn't seem to work anymore. It is still possible to glitch yourself up.

**Comment by BlockMen** [comment]
@PilzAdam plz try #3089  IIRC it was fixed aswell by this commit.

**Comment by paramat** [comment]
#5327 merged, is this still the case?

**Comment by Fixer-007** [comment]
I tried to use sneak with this - no glitching to me (tried this in carbone_ng).

**Comment by paramat** [comment]
So fixed yes?
