### ISSUE TITLE
Proposed mapgen flag changes (attention those who use 'trees' and 'flat' flags in mgv6)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3327]
The 'trees' and 'flat' global mapgen flags have no meaning outside mgv6, so i am proposing they are moved into mgv6 'sp flags' (mapgen-specific flags). There will be a new dedicted flat mapgen soon that will use the biome API to make it very customisable.

We might ask that world maintainers edit their map-meta.txt at changeover time, or perhaps more likely we'll make everything automatically backwards-compatible.

I also propose new global mapgen flags are added: 'ores', 'biomes' and 'decorations'. Together with 'caves', 'dungeons' and 'light' this willl make all the mapgen modules easily switchable.

**Comment by PilzAdam** [comment]
:+1:, but do not break map compatibility or require active changes by the user.

**Comment by 0-afflatus** [comment]
:+1: but must be backwards compatible.

**Comment by paramat** [comment]
At the least we need a new global 'decorations' flag, to allow these to be disabled in the flat mapgen.
There's no need to move the 'trees' flag into mgv6 spflags because mgv6 trees are decorations and so can be controlled by the new global decorations flag.
