### ISSUE TITLE
Why some textures can not be loaded?

### ISSUE THREAD

**Issue by Limingbiao** [minetest/minetest#3335]
Why some textures can not be loaded? 
For example,I would register a node,

minetest.register_node("hug:workbench", {
	description = "Workbench",
	tiles = {
		"hug_workbench_t.png",
		"hug_workbench_b.png",
		"hug_workbench_s.png",
		"hug_workbench_s2.png",
		"hug_workbench_f.png",
		"hug_workbench_f.png"
	},
})
       But when I run the game，Only "hug_workbench_t.png","hug_workbench_f.png" can be loaded normally,however,"hug_workbench_b.png","hug_workbench_s.png","hug_workbench_s2.png" can't be
loaded.
       Any Requirement for textures?  by the way，if support 9patch png?

**Comment by C1ffisme** [comment]
Could you post the pictures to Github? That *might* help us find out what's wrong...

**Comment by Limingbiao** [comment]
![hug_workbench_f](https://cloud.githubusercontent.com/assets/15642373/10926557/62d170fa-82d3-11e5-8a27-ea5f8ac31f38.png)
![hug_workbench_front_b](https://cloud.githubusercontent.com/assets/15642373/10926556/62d0cbe6-82d3-11e5-8072-47c39ce59bd8.png)
![hug_workbench_front_s](https://cloud.githubusercontent.com/assets/15642373/10926555/62d0aa94-82d3-11e5-9d44-3ceb57772fd4.png)
![hug_workbench_front_s2](https://cloud.githubusercontent.com/assets/15642373/10926554/62ce358e-82d3-11e5-9733-6b819b3d97e1.png)
![hug_workbench_t](https://cloud.githubusercontent.com/assets/15642373/10926558/62d23e18-82d3-11e5-8dfa-5179cabc3a5b.png)

these image are not created by me......

**Comment by C1ffisme** [comment]
Well... since you can load them on, they aren't corrupted... Do you get an error message, or just textures in the wrong places?

**Comment by Limingbiao** [comment]
I don't think that'll be a problem... Why some textures can be loaded?

![qqw](https://cloud.githubusercontent.com/assets/15642373/10926776/58fd2338-82d5-11e5-8169-2b0ecc7e7ed3.png)
![qq](https://cloud.githubusercontent.com/assets/15642373/10926906/45d0a9c8-82d6-11e5-9afc-9db27e04b0fa.jpg)

**Comment by kahrl** [comment]
Some of the files have "_front" in their filename, which you didn't include in the node definition.

**Comment by Limingbiao** [comment]
Please forgive my IQ.  x_x

**Comment by C1ffisme** [comment]
It's okay. I've done the exact same thing a million times.
