### ISSUE TITLE
Screen flickering/flashing in git build

### ISSUE THREAD

**Issue by JohnnyComeL8ly** [minetest/minetest#3338]
Every time I load a singleplayer or WAN game I get screen flickering/flashing. Btw, MT won't capture this with F12... I had to use Shutter (5 second delay) to screenshot it.
https://forum.minetest.net/download/file.php?id=4063
I use Xubuntu 15.10 x86_64
I made a fresh Git version 0.4.13-dev-64049cf (cleaned the code too "git clean -xf"). I also have my minetest_game from git (no mods).
http://paste.ubuntu.com/13099166/

EDIT: I think it was est31's  c75ab52 that fixed it.  I don't have the problem any more.  And it seems I made an issue for the wrong build: #3337 was the last one where I had issue.  Sorry, guys.

**Comment by est31** [comment]
Yes, c75ab521153b928e6718d7d3ac4c2104f13ac1e4 fixed the issue. I've also done a manual launchpad rebuild (everything except precise) so that nobody who updates will get the buggy state.
