### ISSUE TITLE
Add "coordinates" to the crafting grid to make telling recipes easier

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#334]
Add "coordinates" to the crafting grid to make telling recipes easier, so that you can say "add wood to slot 3" instead of "add wood to bottom-right slot".

An example would be like this:

This is the current grid:
[  ] [  ] [  ]
[  ] [  ] [  ]
[  ] [  ] [  ]

Maybe make it look like this (the numbers would appear in the background, written in dark gray):
[7] [8] [9]
[4] [5] [6]
[1] [2] [3]

**Comment by nerzhul** [comment]
Should we close this ?

**Comment by C1ffisme** [comment]
Go ahead, @nerzhul. Maybe someone can resurrect this if they want this feature.

**Comment by sapier** [comment]
closing due to old age and noone objected to closing for about 9 months now
