### ISSUE TITLE
SRP util library srp_pcgrandom_seed() unused warning

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#3349]
.../src/util/srp.cpp:515:13: warning: 'void srp_pcgrandom_seed(srp_pcgrandom*, long long unsigned int, long long unsigned int)' defined but not used [-Wunused-function]

Reported on MinGW 64

**Comment by est31** [comment]
Fixed in upstream commit https://github.com/est31/csrp-gmp/commit/695822e45d9ca48b75b4ec1af1b4eea19139f8b1 . Will backport it for minetest.

**Comment by est31** [comment]
337c02c0f0186c52e2bd4307c6018295a1d2b137
