### ISSUE TITLE
print() does not end line with line feed

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#3350]
Regression from https://github.com/minetest/minetest/commit/5e507c9829942c434a6f1ae7a4f3a488c7e50bef
Lua's print() function is overridden but does not append a newline to the end of the string printed.

**Comment by est31** [comment]
If we ended with carriage return, we would do it differently from the original function. It always uses line feed:
https://github.com/minetest/minetest/blob/337c02c0f0186c52e2bd4307c6018295a1d2b137/src/lua/src/lbaselib.c#L48
