### ISSUE TITLE
Remove #include <algorithm> from util/basic_macros.h

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#3352]
Having such a heavyweight include in a basic header file undermines the whole point of it - what would be best is including <algorithm> only in the files that use the CONTAINS() macro.  This is tricky to get right because different compile options (i.e. server-only) or different platforms (Linux for example) include different headers, so what may compile on your machine may not compile for others'.

This is an enhancement since it would reduce compilation time.

**Comment by ShadowNinja** [comment]
#3256 fixes this.

**Comment by kwolekr** [comment]
Yes but that PR does something else too that we might not want.

**Comment by paramat** [comment]
Done in #3256
