### ISSUE TITLE
F10 Chat console should be available all the time

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3353]
When you open the inventory it is not possible to open the terminal. IMHO the terminal should be always accessible just like the menu. Because it is part of MT not the game.

**Comment by paramat** [comment]
Any support?

**Comment by Wuzzy2** [comment]
I agree, but it's not important.. This is pretty much standard practice in many video games.

**Comment by Fixer-007** [comment]
Our chat system needs rework, it is a mess IMO even after SN changes. I would rather go with chat in left buttom corner without any formspecs popups and F10 console for technical.

**Comment by paramat** [comment]
F10 is fullscreen chat, any formspec would cover it and make it unreadable.

**Comment by Calinou** [comment]
> F10 is fullscreen chat, any formspec would cover it and make it unreadable.
Even when configured to be partial-screen, formspecs would likely cover parts of it.

The point is that the console should go *on top* of the formspec, not below.

**Comment by paramat** [comment]
Ok that makes more sense.

**Comment by paramat** [comment]
Any core dev support?

**Comment by paramat** [comment]
No core dev support for a long time and low priority.

**Comment by HybridDog** [comment]
Please add the "Closed but PRs may be accepted" label.

**Comment by orbea** [comment]
@paramat Do you know what part of the code base is relevant to this issue?

**Comment by SmallJoker** [comment]
@orbea The relevant code can be found here:

https://github.com/minetest/minetest/blob/aa3cf400e2ca4096517e926dbae5b6337b2f1876/src/client/game.cpp#L1829-L1833

If there's a formspec (menu) open, it currently captures all inputs.
