### ISSUE TITLE
Saplings no longer grow in caves and underground structures.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#3357]
Hi, recently the behavior of growing trees has changed. Now they need a torch or something to be placed beside them so they can grow.

This completely breaks gameplay on my server and others as this breaks several machines people make.

Please change the behavior back to what it was, when saplings would grow into trees without strong light, as in caves and underground buildings and structures.

**Comment by kilbith** [comment]
It's a new Minetest Game feature, see : https://github.com/minetest/minetest_game/issues/704 and https://github.com/minetest/minetest_game/pull/705

**Comment by Megaf** [comment]
https://github.com/minetest/minetest_game/issues/724
