### ISSUE TITLE
Scrollbar in formspec: bug?

### ISSUE THREAD

**Issue by narrnika** [minetest/minetest#3360]
[**minetest/doc/lua_api.txt**](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt)
line 1574: `#### scrollbar[<X>,<Y>;<W>,<H>;<orientation>;<name>;<value>]`

[**minetest/src/guiFormSpecMenu.cpp**](https://github.com/minetest/minetest/blob/master/src/guiFormSpecMenu.cpp)
line 453: `std::string name = parts[2];`
lines 484-485: `if (parts[2] == "vertical") is_horizontal = false;`

*May be, should be as follows:*
line 453: `std::string name = parts[`**3**`];`
*or I misunderstood something?*

P.S. *I'm sorry, my english - is google-translate.*

**Comment by BlockMen** [comment]
Oh, right. I noticed that earlier but forgot to push it that time: https://github.com/BlockMen/minetest/commit/36855522a5382614c525c69dd884560a197b875d

**Comment by BlockMen** [comment]
Fixed. 36855522a5382614c525c69dd884560a197b875d
