### ISSUE TITLE
Strange green thing inside connected glass

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3361]
![screenshot_20151110_191120](https://cloud.githubusercontent.com/assets/3192173/11126868/50d839c0-8971-11e5-8d37-7d84ed42dde9.png)

**Comment by kilbith** [comment]
Not a bug : https://forum.minetest.net/viewtopic.php?p=195679#p195679

Also dupe of https://github.com/minetest/minetest/issues/1514

**Comment by HybridDog** [comment]
ok, sorry
