### ISSUE TITLE
replacements in minetest.register_craft does not include groups

### ISSUE THREAD

**Issue by MrIbby** [minetest/minetest#3368]
For example:
```lua
minetest.register_craft({
	type = "shapeless",
	output = "cake:cake",
	recipe = {"farming:flour", "group:water_bucket", "group:food_sugar", "group:food_sugar"},
	replacements = {
		{"group:water_bucket", "bucket:bucket_empty"}
	}
})
```
`group:water_bucket` works just fine for `recipe` but not `replacements`. The only workaround as of now is replacing `group:water_bucket` with `default:bucket_water`, `bucket:bucket_river_water`, and any other water buckets.

**Comment by est31** [comment]
Can anybody test #3369? If it works, it can be merged (wit approval of me and @Ekdohibs ), and this issue is fixed.

**Comment by MrIbby** [comment]
3f8eb5e0d0a7dd30bfd6b805d6c03e0f45182e9a
