### ISSUE TITLE
Add aliases for textures

### ISSUE THREAD

**Issue by 0-afflatus** [minetest/minetest#3370]
Due to having reorganised the contents of default into separate mods for my sub-game, I still need to keep some old textures in default for compatibility with 3rd party mods.

It would be so much cleaner to be able to create aliases for the texture image files. Ideally this would be by allowing minetest.register_alias() to accept filenames as well as node names.

**Comment by rubenwardy** [comment]
Also for compatibility with texture packs.

**Comment by pithydon** [comment]
I think this should not be in the lua files at all, but instead in a alias.txt that can be place in the texture folder of a mod or a texture pack.
A mod alias should only be used if a texture file with the same name is not found.
Texture pack aliases should override mod aliases and textures.

**Comment by paramat** [comment]
Any core dev support?
@rubenwardy i can't tell if you support it.

**Comment by paramat** [comment]
@rubenwardy ^ ?

**Comment by paramat** [comment]
I'm not keen on this as i generally dislike aliases, i also don't see much need.
No core dev support for 2+ years so closing, but core devs feel free to reopen if you support this.
