### ISSUE TITLE
Destroy unknown items on drop

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3389]
On clear minetest-dev server 0.4.13 (18.11.2015) you can't drop unknown items (can drop only to trash if you will add inventory mod). This bug confirm also Narrnika.

**Comment by tenplus1** [comment]
I wouldn't consider this a bug but a way to keep worlds tidy from unknown items, use the /pulverise command to get rid of these.

**Comment by amadin** [comment]
Does all your players know about this command? Many players don't read motd messase, some players don't know english.

**Comment by est31** [comment]
Did it work before?

**Comment by RobertZenz** [comment]
I can remember that dropping unknown items worked, they would simply vanish after being dropped (or become invisible).

**Comment by BlockMen** [comment]
@est31 I remember it was possible, don't know if it was in 0.4.12 though

**Comment by 0-afflatus** [comment]
Is this really a bug? Seems like acceptable behaviour to me.

**Comment by amadin** [comment]
In 0.4.12-dev it works, unknown items was drops. 0.4.13-dev i use only 1 week and all this time unknown items don't drops.

**Comment by tenplus1** [comment]
It did allow you to drop unknown items before although the current behavious is much better as it forces the player to get rid of them in a better manner like typing /pulverise or dropping them into a rubbish bin of sorts.

**Comment by paramat** [comment]
Not sure this is a bug yet, unless it exposes something else that is broken.

**Comment by amadin** [comment]
So may developers add an option in minetest.conf to droping unknown items, because after deleting bugged mod, players must just drop unknown items of this mod. I negative attitude to attempts to create problems players. The game should be intuitive and not to irritate.

**Comment by est31** [comment]
Yeah, I think this is a bug. People should be able to drop stuff.

**Comment by 0-afflatus** [comment]
1) I haven't tested this yet.
2) If it was never the intention to make unknown items undroppable, then this is a bug, regardless of the fact that some of us think it may be a beneficial side-effect.
3) I would be interested in making unknown items undroppable within my sub-game, so while I test this I will consider whether it is possible to soft-code it as a feature.

**Comment by beyondlimits** [comment]
I prefer it to be a setting, since there are obe who would like to enable dropping unknown items on their server and others who would like to prevent the mess caused by unknown items. In the end, don't forget that Minetest is meant to be a game engine.

**Comment by paramat** [comment]
I feel this doesn't justify a setting, the proper behaviour should be decided and we go with that.

**Comment by BlockMen** [comment]
Unknown items that are droped are removed, no? So i think it wouldn't mess any server. If I'm not mistaken with that then I'm all for fixing the old behavior.

**Comment by Wuzzy2** [comment]
While I'm not sure whether unknown items should be destroyed after an attempted drop (this was this way a few versions ago), there should be defintely some standard and easy way to get rid of them, they can become pretty annoying when cluttering your inventory because you can be stuck with them forever (they are cursed, hehe!).
`/pulverize` alone is clearly not the final answer.

**Comment by tacotexmex** [comment]
As a server admin I see players' inventories and chest fill up with unknown items. This is ridiculous.

**Comment by Fixer-007** [comment]
There is /pulverise. Maybe minetest_game should have trash included in inventory GUI

**Comment by amadin** [comment]
I think need add the command for clearing inventory from unknown items or at least add to unknown item name "(type /pulverise for remove item in hand)"

**Comment by tacotexmex** [comment]
> at least add to unknown item name "(type /pulverise for remove item in hand)".
That would be almost a non-solution to the problem, at least if in response to my description of it.

> Why unknown items not should be destroyed after an attempted drop?
Unknown items may also be a result of unintentional server admin actions, so immediate destroying of the items is not ideal either imo. 

I just want to be able to drop unknown items. builtin_item or item_drop handles removal of old in-world items for my servers anyway.

**Comment by Wuzzy2** [comment]
In earlier Minetest versions it was possible to “drop” unknown items, but they got immediately destroyed when doing so. This was a quick and convenient and portable way to get rid of your unknown items.

Why has this feature been removed?
