### ISSUE TITLE
hud_set_flags({}) causes disappearence of hp bar etc

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#3395]
Lua API says

> if a flag equals nil, the flag is not modified

However there's been a regression that means that the flag is set to false.

Minimal test case:

```Lua
minetest.register_chatcommand("a", {
	func = function(name)
		local player = minetest.get_player_by_name(name)
		player:hud_set_flags({})
	end
})
```

Before:

![before](https://cloud.githubusercontent.com/assets/2122943/11323835/96347e82-9116-11e5-8d29-6962cb798d4e.png)

After:

![disappear](https://cloud.githubusercontent.com/assets/2122943/11323816/4ac020d2-9116-11e5-96e6-fb81a4a21775.png)

Additionally, I think that the hotbar flag is cached somehow or something. It does disappear, but after a client restart on a persistent server, it seems. (Although haven't checked this)

**Comment by est31** [comment]
Thanks for filing the bug, the cause for the observed behaviour doesn't match your theory, but still its a bug, and not a young one.
