### ISSUE TITLE
Migration from Redis to LevelDB/SQLite segfaults

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3396]
```
[root@ra ~]# /mnt/sda3/minetest-master-13/minetest-rivergen/bin/minetestserver --migrate leveldb --world /mnt/sda3/minetest-master-13/minetest-rivergen/worlds/world/
Error segmentation
```

**Comment by sfan5** [comment]
This is not a missing feature, it's a bug.
Can you reproduce this with a debug build in gdb and give us the backtrace?

**Comment by amadin** [comment]
Yes i can.  cmake . -DRUN_IN_PLACE=TRUE -DBUILD_SERVER=TRUE -DBUILD_CLIENT=FALSE -DCMAKE_BUILD_TYPE=Debug -DENABLE_REDIS=TRUE  then make -j 2 ??

**Comment by sfan5** [comment]
Yes, then run <code>gdb --args ./bin/minetestserver --migrate leveldb --world \<worldpath\></code>
When it crashes type <code>thread apply all bt full</code>.

**Comment by amadin** [comment]
$ gdb --args /mnt/sda3/minetest-master-13/minetest-rivergen/bin/minetestserver --migrate leveldb --world /mnt/sda3/minetest-master-13/minetest-rivergen/worlds/world
GNU gdb (GDB) 7.5.0.20121002-alt3 (ALT Linux)
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i586-alt-linux".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /mnt/sda3/minetest-master-13/minetest-rivergen/bin/minetestserver...done.
(gdb) thread apply all bt full
(gdb)

**Comment by sfan5** [comment]
You'll need to do <code>run</code> first to get gdb to actually start the process.

**Comment by amadin** [comment]
Can you write all the commands that I need to enter in the terminal?

**Comment by sfan5** [comment]
Apparently <code>reply->str</code> may be <code>NULL</code> and <i>std::string::operator+</i> doesn't like this.

[relevant code](https://github.com/minetest/minetest/blob/master/src/database-redis.cpp#L177-L178)

**Comment by neoascetic** [comment]
Still have this issue!

**Comment by neoascetic** [comment]
It didn't work on latest stable (0.4.13), but I was able to migrate my world to leveldb (twice) with no issues using the latest master! It seems like the issue was fixed.
