### ISSUE TITLE
falling.lua removing solid nodes

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#3398]
I use wallmounted to place certain nodes in-game and if a falling sand zips by and lands on this node at speed it tends to remove it from the floor even if it's solid and not signlike.  This can affect servers using protection logo's to stop griefing, carpets and teleport pad's.

Also it would be nice for falling nodes to have sound when they hit the ground, so maybe a peek at HybridDog's falling_extras mod would be useful: https://github.com/HybridDog/falling_extras

**Comment by HybridDog** [comment]
Sand falls into not buildable to plantlike nodes and replaces them, e.g. those red bones on sss' server.

**Comment by rubenwardy** [comment]
I had an issue where falling nodes would destroy flag nodes (which are not walkable) and make them drop onto the ground. A player could then place that node elsewhere, creating another flag. The ctf mod would then notice there is a node missing at the original location, and would set a flag there again.

CTF's flag nodes are in the "immortal" group, I'm surprised that the falling code doesn't respect that.

**Comment by twoelk** [comment]
is this related?
https://forum.minetest.net/viewtopic.php?p=204606#p204606

**Comment by t4im** [comment]
This is most likely a `CONTENT_IGNORE` issue. I'll line a fix up soon.

You should be at increased risk of this, when entering a previously unloaded area
(e.g. by `/home` or teleporting there) on a laggy or badly connected server.

In singleplayer this shouldn't happen at all,
which is probably, why this hasn't been confirmed yet.

**Comment by raymoo** [comment]
@rubenwardy I don't think immortal is stated anywhere in the documentation to have any meaning for nodes. The first time I had heard of the convention was when Wuzzy posted about mod interoperation.

**Comment by paramat** [comment]
#4740 merged, hopefully fixed.
