### ISSUE TITLE
Feature request: reload config files when SIGHUPped.

### ISSUE THREAD

**Issue by Mikaela** [minetest/minetest#34]
It would be very nice if server reloaded all configuration files when it's sighupped. Usually many programs do that on sighup.

**Comment by nerzhul** [comment]
This is a good idea.

**Comment by paramat** [comment]
Nearly 2 years later .. still a good idea?

**Comment by bigfoot547** [comment]
@paramat +1 year, yeah, still a good idea ;-).

**Comment by paramat** [comment]
+1 year, still a good idea? :)

**Comment by HybridDog** [comment]
How could you close this two times without reopening it in between?
I think this closed issue could become forgotten if you don't add the Adoption needed label.

**Comment by SmallJoker** [comment]
@HybridDog It's black magic in effect. "Adoption needed" is for PRs which were abandoned by their authors. Issues are simply re-opened if enough interest is shown.

**Comment by paramat** [comment]
Yes i am wondering if we need a new label for issues closed due to to lack of dev interest instead of dissapproval, to make them searchable.
