### ISSUE TITLE
Images in tablecolumn are not scaled

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3403]
@kahrl I notify you since you know the issue.
@VanessaE wants scalable images as well to put icons in the settings tab.

(The bag image is 128x128px, others are 16x16px)
![screenshot_20151127_134546](https://cloud.githubusercontent.com/assets/7883281/11441551/7dfe2ec6-950d-11e5-8fbb-540f4bd16b58.png)

**Comment by paramat** [comment]
Bug or feature request? @VanessaE can you enlighten us?

**Comment by VanessaE** [comment]
I don't remember what precipitated this, and I have no idea about the mod being shown, but images on a button scale with the button size.  Seems to me the same should be true for other uses.

Then again, the last formspec I did was minislots, and everything there works more or less the way one should expect.

**Comment by paramat** [comment]
Thi sis possibly the relevant code:
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/gui/guiTable.cpp#L386
Looks like the table column width is simply set to the largest image's width, without scaling the image, so seems to be a feature request.

Any core dev support?

**Comment by VanessaE** [comment]
To put it simply, "only 16px" is a bad assumption, if that's the case.

**Comment by paramat** [comment]
Still unconfirmed? Close?

**Comment by NathanSalapat** [comment]
![screenshot_20200808_204950](https://user-images.githubusercontent.com/8930456/89723198-bd381300-d9b8-11ea-965a-da4f08457c30.png)
I believe this is still happening. Although I'm not the one that wrote the code for this.
I have an object here with a 128px texture and it just a strip of it. The mod is commoditymarket_fantasy

**Comment by paramat** [comment]
Thanks.

**Comment by v-rob** [comment]
Tables are a big mess; the code is garbage.  There are many bugs with `tablecolumns` functionality being broken.  I personally want to completely rewrite it since it's basically beyond refactor.
