### ISSUE TITLE
minetest/doc/protocol.txt  is far out of date

### ISSUE THREAD

**Issue by rarkenin** [minetest/minetest#341]
[minetest/doc/protocol.txt](https://github.com/minetest/minetest/blob/master/doc/protocol.txt) is extremely out of date. It only includes a connect and disconnect implementation, currently useless for doing anything,  Can up-to-date info be given in this file? It'll help foster alternative clients, such as bots and clients for mobile devices.

**Comment by nerzhul** [comment]
Documentation is on our wiki as @PilzAdam said. Moreover, protocol will be reworked and documentation will be updated as soon as this will be released
