### ISSUE TITLE
[Enhancement] Categorize subgames and mods based on their use

### ISSUE THREAD

**Issue by DonaldTsang** [minetest/minetest#3414]
It would be nice to have tags on mods to indicate what properties and use they have.
For mods:
- Architecture (e.g. building materials, "auto-house" blocks)
- Agriculture (e.g. harvesting and irrigation tools, fertilizers)
- Cuisine (e.g. food items, cooking appliances and utensils)
- Technology (e.g. computers, circuits, cameras, speakers)
- Engineering (RESERVED)
- Transportation (e.g. vehicles, airplanes, boats/ships)
- Industry (e.g. automatic item generation machines)
- Chemistry (e.g. nuclear research, chemical production)
- Biology (e.g. mobs, organs, Frankenstein creations)
- Astronomy (e.g. space exploration, gravity)
- Art/Music (e.g. musical instruments, sound recorders)
- Economics (e.g. stock markets, currency, trade centers)
- Education (RESERVED)
- Military (e.g. guns, knifes, shields, bombs, armor)
- Fashion (e.g. clothing, accessories, "ears, paws and tails")
- GUI (e.g. on-screen maps, special effects)
- RESERVED are blank labels for future expansion
- The categories should be updated every year to accommodate the variety of mods

**Comment by RobertZenz** [comment]
Why predefine tags? Mods might not fit any of these categories well (for example my Artisanry mod does not fit well into any of these categories).

**Comment by 0-afflatus** [comment]
Setting multiple tags dynamically would be the WTG. This approach is too top-down.

**Comment by paramat** [comment]
:-1:

**Comment by C1ffisme** [comment]
I think that I could see some use for this, if someone wanted to play a singleplayer world with only their technology mods, and not their magic mods. However, the selection of tags here is a bit too specific. I would choose a few tags that cover just about every kind of mod. Also, if we do end up adding this, you should still be able to sort your mods by alphabetical order, in case you feel indifferent to the new system.

Other than anything I have said in the above paragraph, this is a :+1: !

Here's the tags I would suggest, and a mod should be able to apply multiple tags : 

- Tools
- Decorative
- Game Overhaul
- Minor Game Changes
- Scientific
- Magic
- Commands
- Blocks
- Mobs

That would be my list, although there may be more groups of mods that I might have missed.

**Comment by rubenwardy** [comment]
jumping ahead of ourselves, this should be part of a mod manager that can actually use it
