### ISSUE TITLE
disable_anticheat doesn't disable "interacted_too_far" cheat

### ISSUE THREAD

**Issue by asl97** [minetest/minetest#3416]
since the code say '`interacted_too_far`' is a cheat, i say this is a bug.

https://github.com/minetest/minetest/blob/657a16d90c42afc212e70c594296b1e204545a4c/src/network/serverpackethandler.cpp#L1375

**Comment by est31** [comment]
Seems so.

**Comment by ShadowNinja** [comment]
106d4b7d05cfbba901abd540113991042d77bc97
