### ISSUE TITLE
System luajit not detected on openSUSE

### ISSUE THREAD

**Issue by susnux** [minetest/minetest#3419]
On openSUSE luajit is not detected correctly.
This is because openSUSE is using a lua version suffix, like other Linux distributions do it also.
So the include directory is:
include/luajit-5_1-2.0

I have created a patch which will create a proper FindLuajit, so compiling works.
If you want, you can use it freely: https://gist.github.com/susnux/6b4b5a7f9328a7d73c79

**Comment by est31** [comment]
Code looks good, can you make a PR to let the buildbots test it?

**Comment by est31** [comment]
If not, I do it :)

**Comment by susnux** [comment]
If you have time, go on :)

**Comment by est31** [comment]
Fixed by 70ece71ee4e8f8bff5cbc572710c0fa6fc3b355f
