### ISSUE TITLE
libcguittfont.so not found (patch provided)

### ISSUE THREAD

**Issue by susnux** [minetest/minetest#3420]
When compiling minetest with system freetype it  will build the internal cguittfont as a shared library.
This will result in a "libcguittfont.so not found" at start up.

To fix this I have created a very basic patch, you can use it freely:
https://gist.github.com/susnux/6bcc5791a32d25fa46c9

**Comment by est31** [comment]
Have you changed the `BUILD_SHARED_LIBS` option? I don't see it settable. Or is it enabled by default on special cmake setups?

**Comment by susnux** [comment]
Ah on openSUSE the cmake macro sets it to ON by default.

**Comment by est31** [comment]
@susnux okay with pushing above commit to master?

**Comment by susnux** [comment]
Yes of cause, do it :+1:
