### ISSUE TITLE
L-system lighting bug

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3421]
This issue is to document some progress i made tracking down shadow bugs.
Same issue as #3455 
Possibly related issues #3430 #3839 

Working on my 'fracture' lua mapgen mod i noticed lighting bugs in mgv7 not present in mgv6 or singlenode. The difference is mgv7 uses 1 up 1 down overgeneration while mgv6 and singlenode do not. I solved the lighting bug in 'fracture' by calculating lighting over the entire overgenerated volume instead of just the mapchunk:
vm:calc_lighting({x = x0, y = y0 - 1, z = z0}, {x = x1, y = y1 + 1, z = z1})

I then thought about how 'moretrees' mod has shadow bugs in mgv7 and not in mgv6 and suspected that the overgeneration of mgv7 was incompatible with 'updateLighting' used by l-system tree generation. Studying the code, l-system tree code automatically emerges a large volume that probably touches the mapchunk top, when propagating sunlight into that volume it looks at the single layer of nodes just above the volume, which in mgv7 would often be the single layer of overgenerated nodes above a mapchunk, instead of 'ignore' in mgv6.

I noticed the moretrees shadow bugs were dependent on whether the mapchunk above had been generated first. 'updateLighting' was probably lookng at the lowest mapblock in the mapchunk above. If this was generated and full of sunlight no shadow bug. If it was ungenerated and therefore mostly full of 'ignore' but with a single layer of overgenerated nodes as it's lowest layer the shadow bugs occured.

I created a branch with a version of mgv7 without overgeneration and tried the moretrees mod, the more extreme shadows were fixed. Overgeneration is essential to avoid discontinuities at mapchunk borders, so i am currently testing a '0 up 2 down' overgeneration which so far seems to fix the more extreme shadow bugs, however it needs testing to see if the advantages of overgeneration remain. The '0 up' means the top of the generated volume now aligns with mapblock edges just as in mgv6, hopefully fixing the bug when propagating sunlight down.

Because the placement of schematics also uses 'updateLighting' the shadow bugs related to schematic placement may also be fixed by this method.

**Comment by 0-afflatus** [comment]
:+1:  Good work tracking that down. Here's hoping ...

**Comment by paramat** [comment]
![screenshot_20151204_000851](https://cloud.githubusercontent.com/assets/3686677/11578529/6b00e802-9a1e-11e5-8f37-2fddd3be30fb.png)

![screenshot_20151204_000953](https://cloud.githubusercontent.com/assets/3686677/11578531/71abcd3e-9a1e-11e5-87b9-d69e1df72ecc.png)

Unfortunately testing 0 up 2 down overgen i find many bugs at y = 47, 16x16 areas of stone where biomegen has failed, and ores in sand.
I will attempt a fix by editing 'updateLighting' instead.

**Comment by paramat** [comment]
The shadow bugs caused when using moretrees in mgv7 do not happen when flying high to generate upper mapchunks first, this shows that the trees are being generated too early, it would be better to place them as saplings grown a few seconds after mapgen by ABM to make sure all surounding mapchunks have been generated. L-system tree generation includes a lighting update so is meant to be used long after mapgen.

However the 1 up overgeneration of mgv7 does obviously change the behaviour of lighting so there may still be issues related to ths.

**Comment by paramat** [comment]
Re-opening as this is useful information on the moretrees lighting bug.

**Comment by paramat** [comment]
For a while the advice has been to use the moretrees option to place all trees as saplings that grow by ABM long after mapgen, ensuring the mapchunk above has been generated. Apparently this almost solves the lighting bugs but subtle shadows remain in water.

**Comment by paramat** [comment]
Mgv6

![screenshot_20160327_174856](https://cloud.githubusercontent.com/assets/3686677/14066561/82b2c724-f444-11e5-8bf4-b37f3043ba77.png)

Subtle shadows are present in mgv6, using moretrees in the default mode of generating trees at mapgen.

**Comment by paramat** [comment]
We can split this issue into 2 now:
1) Subtle shadows in water in all mapgens, seems to be an issue with l-system code.
2) Extreme and dark shadows in mapgens with overgeneration when the surface mapchunk is generated before the mapchunk above.

**Comment by paramat** [comment]
I doubt this will be fixed for release but added to milestone anyway in th ehope it is attended to.

**Comment by paramat** [comment]
#4967 merged, this issue may now be fixed.
