### ISSUE TITLE
Request for noise parameter value checks to avoid segfault

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3423]
gdb http://pastebin.com/iFRyKcQw

This log from 0.4.13-dev (commit 57b429574ef92c62d202955535896b36845b88db), but segmentation fault i got on 0.4.13 stable too. AltLinux 7.0.5 School Master. Tested with Sqlite and Redis databases, first crush was on stable version with Redis while i flying underground. Compiled with:  -DRUN_IN_PLACE=TRUE -DBUILD_SERVER=TRUE -DBUILD_CLIENT=FALSE -DENABLE_REDIS=TRUE -DENABLE_FREETYPE=FALSE -DENABLE_GETTEXT=FALSE -DENABLE_LEVELDB=FALSE -DENABLE_LUAJIT=TRUE -DENABLE_SYSTEM_GMP=TRUE -DCMAKE_BUILD_TYPE=Debug

**Comment by est31** [comment]
So you can reproduce the crash? That's good, it means one can find out alot about it.

1. Does it occur when the first player logs in, or when any player logs in?

1. Did it work before on that server, or does it appear anew?

1. What mods/game do you have?

Your posted backtrace points to a corrupted m_blocks list... So might be something about mapgen, but possibly something completely else too.

**Comment by amadin** [comment]
1. First player, but first crash was while i flying undeground few minutes after my login
2. New. Today i compile stable version (I had not used stable version before) with mods from other server (0.4.13-dev), i changed mapgen parameters to this:
mgv7_np_cave1 = 0, 6, (50, 20, 100), 52534, 1, 0.5, 2.0
mgv7_np_cave2 = 0, 6, (60, 20, 100), 10325, 1, 0.5, 2.0
or to this:
mgv7_np_cave1 = 0, 6, (50, 20, 50), 52534, 1, 0.5, 2.0
mgv7_np_cave2 = 0, 6, (60, 20, 60), 10325, 1, 0.5, 2.0
Then i got crash i compile development version. I deleted database file and map_meta.txt but it not help me.
3. load_mod_3d_armor = true
load_mod_admin_tools = true
load_mod_advancedban = true
load_mod_beds = true
load_mod_boats = true
load_mod_carts = true
load_mod_caverealms = true
load_mod_chat2 = true
load_mod_compassgps = true
load_mod_craft_guide = true
load_mod_darkage = true
load_mod_ethereal = true
load_mod_inventory_plus = true
load_mod_lrfurn = true
load_mod_mobs = true
load_mod_no_sneak_glitch = true
load_mod_playeranim = true
load_mod_protector = true
load_mod_serveressentials = true
load_mod_shields = true
load_mod_technic_armor = true
load_mod_wieldview = true
load_mod_worldedit = true
load_mod_worldedit_commands = true
load_mod_worldedit_gui = true
load_mod_worldedit_infinity = true
load_mod_worldedit_limited = true
load_mod_worldedit_shortcommands = true
load_mod_xdecor = true

I fix this crash by deleting world dir (sorry i don't copy it before). Now i can't reproduce crash.

**Comment by est31** [comment]
If you change the mapgen params again (for a new world), does it still crash?

**Comment by amadin** [comment]
mapgen params are in minetest.conf and i don't change it.

**Comment by amadin** [comment]
I reproduce this crash after changing last parameters to 0.1
mgv7_np_cave1 = 0, 6, (50, 20, 50), 52534, 1, 0.5, 0.1
mgv7_np_cave2 = 0, 6, (60, 20, 60), 10325, 1, 0.5, 0.1

**Comment by est31** [comment]
@paramat your turn.

**Comment by paramat** [comment]
> This log from 0.4.13-dev (commit 57b4295)

The log mentions 'minetest-rivergen/src' so can't be from 0.4.13dev at that commit, perhaps you were using my branch instead?
If you get the same segfault on 0.4.13 stable then it's not due to my rivergen core mapgen, might be due to the mods you're using?

> I reproduce this crash after changing last parameters to 0.1
mgv7_np_cave1 = 0, 6, (50, 20, 50), 52534, 1, 0.5, 0.1

The last parameter 'lacunarity' should never be below 1.0 it works best between 1.5 and 3.0.

**Comment by nerzhul** [comment]
gdb ?

**Comment by amadin** [comment]
I posted link to it on first message.

**Comment by est31** [comment]
@paramat why does it not deny startup then if `lacunarity` is outside of the bounds? If its effect indeed is a crashing mapgen, it should give a clear warning to the user, or even an error, so that they can't start the world that way.

**Comment by amadin** [comment]
Or write about outside of the bounds in minetest.conf.example

**Comment by paramat** [comment]
I'll add a note here https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L640

There are other ways to crash MT through noise parameters, however i agree with hmmmm when he explained that having checks for everything everywhere would be too slow and/or complex. Essentially it is assumed those who adjust noise parameters know what they're doing. Better to add warnings in lua_api.txt i think, and i will.

**Comment by Fixer-007** [comment]
Not sure if related by sometimes when I join some multiplayer server I can catch segmentation fault at login time.

**Comment by est31** [comment]
:-1: I disagree with this attitude. The speed implications of an additional check at world loading time are minimal. Additionally, its wrong usage of our API, and this should yield in an instant error at world load other than failure only in certain cases when some noise is big enough.

**Comment by paramat** [comment]
Let's see what hmmmm thinks on this.
Perhaps best to open a new issue requesting checks on all noise parameters? if the spread of any octave falls below 1 a similar thing happens.
Indeed it would be better to trigger an error that is more obviously noise.

**Comment by 0-afflatus** [comment]
Noise params are seriously arcane, even if you do have an idea of what you're doing, the odd sanity check or error report wouldn't go amiss.

**Comment by paramat** [comment]
I'm unsure about parameter checks, sometimes parameters change so this would not necessarily be only at session start. Better to just make sure the error is more obviously noise, and to document the acceptable ranges for parameters in lua_api.txt (i would do this).

**Comment by paramat** [comment]
Noise parameter docs improve with warnings on values used.

**Comment by paramat** [comment]
Recent experimentation suggests, possibly, that lacunarity can be set below 1 with no problems.
That just leaves the broken noise caused if the spread of any octave is < 1.
PR #9394 attends to perlinmap noise in core or Lua API.
I might then attend to point-polled noise later, although that is less trivial.
