### ISSUE TITLE
Disable "Public Serverlist" or show warning on selecting it if minetest is compiled without curl

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#3425]
If you don't have curl enabled mintest wont show any information (in gui) about why serverlist is loading for infnite time.
Some sort of warning would be nice or disabling the "Public Serverlist" checkbox might help ... or something else

**Comment by Elinvention** [comment]
Make curl mandatory.

**Comment by rubenwardy** [comment]
:+1:

I suggest a warning.

**Comment by rubenwardy** [comment]
we no longer have this checkbox
