### ISSUE TITLE
Configurable damage screen intensity

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#3429]
When you are damaged (for any reason), a red flash is displayed. It can become obnoxious in fights (against players or mobs).

What about having a configurable intensity (with the ability to disable it entirely if wanted), in minetest.conf?

**Comment by paramat** [comment]
:+1: I actually find red screen and camera tilt visually painful, we need an alternative like perhaps a health bar flash.

**Comment by RobertZenz** [comment]
Maybe flashing the healthbar on *any* change would be a nice alternative, easy way to draw attention that something just happened to your health.

**Comment by est31** [comment]
This has gameplay effects too.

**Comment by C1ffisme** [comment]
Doing something like MC where the health bar flashes white would be good. Also, as a side note, MC doesn't need a red screen because knock back takes care of that effect.

P.S.
```I actually find red screen and camera tilt visually painful```
Does this count as virtual reality?

Sorry, I couldn't help myself. :laughing:

**Comment by est31** [comment]
:-1: Allowing the user to modify would mean its unfair with regards to other users who have the flash enabled.

**Comment by C1ffisme** [comment]
@est31 If they don't like the flash, then they can disable it. If they think they can play well with the flash on, then they may turn it on.

In fact, if we ever add knockback, the red flash should be completely removed. The red flash is only meant to make sure the player knows that he is being damaged, in case a player thought that the lava was actually molten cheese.

**Comment by Calinou** [comment]
>  Allowing the user to modify would mean its unfair with regards to other users who have the flash enabled.

Some potentially-unfair settings can already be changed, like view bobbing (which changes where the player actually aims).

**Comment by paramat** [comment]
Perhaps we could make the red flash much shorter?

**Comment by rubenwardy** [comment]
> Allowing the user to modify would mean its unfair with regards to other users who have the flash enabled.

Hackers/CoreModders can already disable it.
I'd like to be able to disable the flash, and instead show FPS style blood splatters around the cursor.

**Comment by 0-afflatus** [comment]
Could we make it configurable per game?

**Comment by rubenwardy** [comment]
I think it should be done using `player:set_hud_flags` or whatever from the server side.

**Comment by paramat** [comment]
See near-duplicate #3691 please can we continue discussion there? as that has more developed ideas.

**Comment by ObaniGemini** [comment]
Making everything an option for the player is not a long-term solution.

I think we shall close it because https://github.com/minetest/minetest/issues/3691 contains more interesting ideas.

**Comment by est31** [comment]
Maybe close both? I like the current behaviour.

**Comment by paramat** [comment]
Closing as author Calinou develops ideas in near-duplicate #3691 Please continue discussion there.
