### ISSUE TITLE
Android APK builder includes too many files

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#3431]
Recently, it tried to add all of `doc/`, including `doc/html/` which is over 300MiB! (I ended up just deleting the folder and regenerating it later because excluding it ended up  being harder than I thought)
However, `doc/` shouldn't really be included at all, since it's only accessible by browsing the "SD card" or unpacking the app.
I suspect there are other unnecessary files included, but I haven't done a thorough check.

**Comment by est31** [comment]
The license is in `doc/`, and we should ship with the license.
But yeah, we probably shouldn't put the doxygen docs inside.

**Comment by MoNTE48** [comment]
Anyone who needs to can open and read the license github.
Just do not need locale and media folders

**Comment by sapier** [comment]
https://github.com/minetest/minetest/pull/3454 clears any html folder that might end up in apk

**Comment by sapier** [comment]
fixed by dcb91cf0c0c9a20622feeb4e5e8104ffbc9fa8ec

**Comment by ShadowNinja** [comment]
Said patch still copies the directory and deletes it afterwards, which means that it wastes a bunch of time and temporarily uses a lot of disk space.  Also, `doc/html` isn't the only item that shouldn't be included, in fact the only thing from `doc/` that should be included is *maybe* `lgpl-2.1.txt`.  Also, `client/serverlist` probably shouldn't be included either.

**Comment by MoNTE48** [comment]
LGPL does require the inclusion of the contents of the file in the APK? Technically, there is no explanation anywhere that you can find the file in a specific folder on your system. Hence, it is necessary to create a separate tab in the game with a license, if necessary. Many users are stupid, they will not be looking for something in the file system.

**Comment by sapier** [comment]
this is picky I'm quite sure we've got worse problems then some memory on build machine used for a couple of seconds.
Feel free to fix it yourself if you believe it to be worth your time ;-)

**Comment by ShadowNinja** [comment]
#3471

**Comment by est31** [comment]
3471 would fix it.

**Comment by sapier** [comment]
fixed by b4eb614d31a6ed7935bfaa4090fa275a306a3aee
