### ISSUE TITLE
Custom Item Names - CONCEPT

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3435]
Concept: Allow items to be named using ItemStack metadata

Applies to: craftitems, stuff in your inventory

Mods will have to modify methods like on_place to transfer the metadata into nodes properly

What works: Getting the client to display some other string than the itemdef.description

What needs to be added: The books mod is the only mod I could find quickly that stores metadata in itemstacks for books. The metadata is serialzed in lua, so we need a deserialization method for Itemstack that can parse the metadata content and extract a "description" member in the deserialized data, so that that can be displayed instead.

Note that in the image I have the code displaying the metadata in raw form as concept.

http://i.imgur.com/6nYY5MB.png

```
diff --git a/src/guiFormSpecMenu.cpp b/src/guiFormSpecMenu.cpp
index 3cef507..0e6e1a0 100644
--- a/src/guiFormSpecMenu.cpp
+++ b/src/guiFormSpecMenu.cpp
@@ -2237,8 +2237,14 @@ void GUIFormSpecMenu::drawList(const ListDrawSpec &s, int phase)

                        // Draw tooltip
                        std::string tooltip_text = "";
-                       if (hovering && !m_selected_item)
-                               tooltip_text = item.getDefinition(m_gamedef->idef()).description;
+                       if (hovering && !m_selected_item) {
+                               if (item.metadata.empty()) {
+                                       tooltip_text = item.getDefinition(m_gamedef->idef()).description;
+                               } else {
+                               // FIXME - replace with deserialized metadata.description
+                                       tooltip_text = item.metadata;
+                               }
+                       }
                        if (tooltip_text != "") {
                                std::vector<std::string> tt_rows = str_split(tooltip_text, '\n');
                                m_tooltip_element->setBackgroundColor(m_default_tooltip_bgcolor);
```

**Comment by C1ffisme** [comment]
Now that I realize it, this could be used for things like watches, were the time could be told by the item's name in the inventory.

I think this may already be an issue called Meta set Nodedef, though, but it's good to know someone has found a workaround.

**Comment by sofar** [comment]
A watch would be possible, but you'd have to have a global timer updating the itemstack's metadata, which sounds horrendous.

**Comment by C1ffisme** [comment]
You could do it in a way similarly to [node timers](http://dev.minetest.net/minetest.register_node#on_timer), if this was added to craftitems/tools.

**Comment by sofar** [comment]
Itemstack timers, lovely. How about we first solve the naming issue here ;^)

**Comment by C1ffisme** [comment]
Yeah.

I just wish this code worked, but of course it won't run ```get_time``` over and over.

```
local function get_time()
	if minetest.get_timeofday() then
		return minetest.get_timeofday()*24000
	else
		return "No Time"
	end
end

minetest.register_craftitem("tests:joebob",{
	description = get_time(),
	inventory_image = "default_wood.png",
})
```

(P.S. I used this code, and I just got an item that was named "No Time", since time is nil until after registering nodes and items.)

**Comment by sofar** [comment]
please keep threads on topic...

**Comment by sofar** [comment]
I came up with this part: Adds "metadata_as_table" flag to the ItemStack. This allows (next phase) the l_item.cpp code to add 2 new methods: get_metadata_as_table() and set_metatdata_from_table() that then set the "metadata_as_table" flag to (true).

That should allow the client and server to interpret safely whether the metadata is a raw field or whether it's set with a serialized table.

After that we modify the tooltip code to check for this bit, deserialize the metadata and look for the "description" in the table.

```
diff --git a/src/content_cao.cpp b/src/content_cao.cpp
index 72f6145..d9acd48 100644
--- a/src/content_cao.cpp
+++ b/src/content_cao.cpp
@@ -953,7 +953,7 @@ void GenericCAO::addToScene(scene::ISceneManager *smgr, ITextureSource *tsrc,
 		if(m_prop.textures.size() >= 1){
 			infostream<<"textures[0]: "<<m_prop.textures[0]<<std::endl;
 			IItemDefManager *idef = m_gamedef->idef();
-			ItemStack item(m_prop.textures[0], 1, 0, "", idef);
+			ItemStack item(m_prop.textures[0], 1, 0, "", false, idef);
 
 			m_wield_meshnode = new WieldMeshSceneNode(
 					smgr->getRootSceneNode(), smgr, -1);
diff --git a/src/craftdef.cpp b/src/craftdef.cpp
index 67c3ae6..9c56a0b 100644
--- a/src/craftdef.cpp
+++ b/src/craftdef.cpp
@@ -139,7 +139,7 @@ static std::vector<ItemStack> craftGetItems(
 	for (std::vector<std::string>::size_type i = 0;
 			i < items.size(); i++) {
 		result.push_back(ItemStack(std::string(items[i]), (u16)1,
-			(u16)0, "", gamedef->getItemDefManager()));
+			(u16)0, "", false, gamedef->getItemDefManager()));
 	}
 	return result;
 }
diff --git a/src/guiFormSpecMenu.cpp b/src/guiFormSpecMenu.cpp
index 3cef507..0e6e1a0 100644
--- a/src/guiFormSpecMenu.cpp
+++ b/src/guiFormSpecMenu.cpp
@@ -2237,8 +2237,14 @@ void GUIFormSpecMenu::drawList(const ListDrawSpec &s, int phase)
 
 			// Draw tooltip
 			std::string tooltip_text = "";
-			if (hovering && !m_selected_item)
-				tooltip_text = item.getDefinition(m_gamedef->idef()).description;
+			if (hovering && !m_selected_item) {
+				if (item.metadata.empty()) {
+					tooltip_text = item.getDefinition(m_gamedef->idef()).description;
+				} else {
+				// FIXME - replace with deserialized metadata.description
+					tooltip_text = item.metadata;
+				}
+			}
 			if (tooltip_text != "") {
 				std::vector<std::string> tt_rows = str_split(tooltip_text, '\n');
 				m_tooltip_element->setBackgroundColor(m_default_tooltip_bgcolor);
diff --git a/src/inventory.cpp b/src/inventory.cpp
index e89993e..aad90ee 100644
--- a/src/inventory.cpp
+++ b/src/inventory.cpp
@@ -111,12 +111,14 @@ static std::string deSerializeJsonStringIfNeeded(std::istream &is)
 
 ItemStack::ItemStack(std::string name_, u16 count_,
 		u16 wear_, std::string metadata_,
+		bool metadata_as_table_,
 		IItemDefManager *itemdef)
 {
 	name = itemdef->getAlias(name_);
 	count = count_;
 	wear = wear_;
 	metadata = metadata_;
+	metadata_as_table = metadata_as_table_;
 
 	if(name.empty() || count == 0)
 		clear();
@@ -138,7 +140,7 @@ void ItemStack::serialize(std::ostream &os) const
 	if(wear != 0)
 		parts = 3;
 	if(metadata != "")
-		parts = 4;
+		parts = 5;
 
 	os<<serializeJsonStringIfNeeded(name);
 	if(parts >= 2)
@@ -147,6 +149,7 @@ void ItemStack::serialize(std::ostream &os) const
 		os<<" "<<wear;
 	if(parts >= 4)
 		os<<" "<<serializeJsonStringIfNeeded(metadata);
+		os<<" "<<(metadata_as_table ? 1 : 0);
 }
 
 void ItemStack::deSerialize(std::istream &is, IItemDefManager *itemdef)
@@ -291,6 +294,14 @@ void ItemStack::deSerialize(std::istream &is, IItemDefManager *itemdef)
 			// Read metadata
 			metadata = deSerializeJsonStringIfNeeded(is);
 
+			// Read metadata_as_table
+			std::string metadata_as_table_str;
+			std::getline(is, metadata_as_table_str, ' ');
+			if(metadata_as_table_str.empty())
+				break;
+			else
+				metadata_as_table = (stoi(metadata_as_table_str) == 1);
+
 			// In case fields are added after metadata, skip space here:
 			//std::getline(is, tmp, ' ');
 			//if(!tmp.empty())
@@ -580,7 +591,8 @@ bool InventoryList::operator == (const InventoryList &other) const
 		ItemStack s1 = m_items[i];
 		ItemStack s2 = other.m_items[i];
 		if(s1.name != s2.name || s1.wear!= s2.wear || s1.count != s2.count ||
-				s1.metadata != s2.metadata)
+				s1.metadata != s2.metadata ||
+				s1.metadata_as_table == s2.metadata_as_table)
 			return false;
 	}
 
diff --git a/src/inventory.h b/src/inventory.h
index a690eb5..5313cbe 100644
--- a/src/inventory.h
+++ b/src/inventory.h
@@ -32,9 +32,10 @@ struct ToolCapabilities;
 
 struct ItemStack
 {
-	ItemStack(): name(""), count(0), wear(0), metadata("") {}
+	ItemStack(): name(""), count(0), wear(0), metadata(""), metadata_as_table(false) {}
 	ItemStack(std::string name_, u16 count_,
 			u16 wear, std::string metadata_,
+			bool metadata_as_table_,
 			IItemDefManager *itemdef);
 	~ItemStack() {}
 
@@ -62,6 +63,7 @@ struct ItemStack
 		count = 0;
 		wear = 0;
 		metadata = "";
+		metadata_as_table = false;
 	}
 
 	void add(u16 n)
@@ -168,6 +170,7 @@ struct ItemStack
 	u16 count;
 	u16 wear;
 	std::string metadata;
+	bool metadata_as_table;
 };
 
 class InventoryList
diff --git a/src/script/common/c_content.cpp b/src/script/common/c_content.cpp
index fe429b5..22f45c4 100644
--- a/src/script/common/c_content.cpp
+++ b/src/script/common/c_content.cpp
@@ -723,7 +723,8 @@ ItemStack read_item(lua_State* L, int index,Server* srv)
 		int count = getintfield_default(L, index, "count", 1);
 		int wear = getintfield_default(L, index, "wear", 0);
 		std::string metadata = getstringfield_default(L, index, "metadata", "");
-		return ItemStack(name, count, wear, metadata, idef);
+		bool metadata_as_table = getintfield_default(L, index, "metadata_as_table", 0) ? true : false;
+		return ItemStack(name, count, wear, metadata, metadata_as_table, idef);
 	}
 	else
 	{
diff --git a/src/script/lua_api/l_env.cpp b/src/script/lua_api/l_env.cpp
index 084b1b4..cc1864f 100644
--- a/src/script/lua_api/l_env.cpp
+++ b/src/script/lua_api/l_env.cpp
@@ -233,7 +233,7 @@ int ModApiEnvMod::l_place_node(lua_State *L)
 		return 1;
 	}
 	// Create item to place
-	ItemStack item(ndef->get(n).name, 1, 0, "", idef);
+	ItemStack item(ndef->get(n).name, 1, 0, "", false, idef);
 	// Make pointed position
 	PointedThing pointed;
 	pointed.type = POINTEDTHING_NODE;
```

**Comment by 0-afflatus** [comment]
If this leads to dynamic descriptions for written books I'm all for it.
Being able to change textures on changes of state would save creating multiple nodes for active and passive states. Being able to store transient temperature and humidity per node would facilitate weather-related solid / liquid / gas; wet / dry transitions. If you could see to all that by the close of play today, we can move on to world domination tomorrow. Plan?

**Comment by C1ffisme** [comment]
Plan! :smiley: 

If we could get several nodes inside of one node, especially if they were different states of matter, textures, or molecular structure, then we almost have a virtual reality generator in our hands.

But for now, let's get the description thing done so we can name our swords awesome things. And if we added a little more text below the description...
![screenshot_20151208_120240](https://cloud.githubusercontent.com/assets/9893266/11663952/8b1d3b5c-9da4-11e5-927a-f7393b174da0.png)

**Comment by sofar** [comment]
Above patch actually breaks ALL in-game tools - you end up with not a single tool in your inventory.

I'm really not happy about adding in an itemdef field forcing a protocol update. I'll probably focus instead on deserializing the metadata description, since that actually could work without a protocol change.

**Comment by C1ffisme** [comment]
Really? How would it break them?

**Comment by sofar** [comment]
@C1ffisme I assume serializing or deserialzing the new format isn't going as I expected it to go, so when the itemstacks are sent to the client, it spots an error and fails to load them. But, I'm just guessing.

**Comment by C1ffisme** [comment]
It's worth a test... Although compiling something on a laptop isn't the smartest idea. I might be able to procure a desktop computer to test a pull request or fork, though.

**Comment by sofar** [comment]
I really don't like the idea of the extra flag - this works just fine without an extra itemdef flag and deserialization can be attempted rather safely. There's a working pull request posted.

**Comment by octacian** [comment]
IDK how many times I've asked this question, but, is there any chance of this feature making it into Minetest? In other words, the question I've asked so many times, is this dead?

The often repeated second paragraph:
I hope not, I see a lot of potential for mods, and later for maps. After reading through the conversation, it looks like the feature was on the right track with deserializing the meta. I wish I could do something myself to help, but as of yet, I've only ever done 40 minutes worth of anything related to C++. I really hope this get's completed, thanks for your work.

**Comment by rubenwardy** [comment]
Fixed since my itemstack pr was merged
