### ISSUE TITLE
On-screen Android soft-buttons for back, home, and recent-apps not hidden

### ISSUE THREAD

**Issue by KarlHegbloom** [minetest/minetest#3436]
I can not use the HUD controls in minetest on Android on my son's tablet, which has no hardware buttons, and instead uses the on-screen buttons that are drawn as a semi-transparent overlay along the bottom edge of the screen. Other full-screen android programs make them disappear during gameplay, bringing them back with just the right swipe from the bottom edge, just as the status bar is revealed with the right kind of swipe down from the top edge.

**Comment by asl97** [comment]
duplicate https://github.com/minetest/minetest/issues/2736

**Comment by nerzhul** [comment]
As mentioned, dup
