### ISSUE TITLE
get_lists() broken?

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3438]
I've been working on a node/object inspector tool to help mod development and debugging, and it fails to ever retrieve the itemstacks in a nodemetaref inventory, because inventory:get_lists() always returns 0, even when I inspect nodes that have itemstack lists like furnaces, chests with items, etc.

because I can't thus determine the names of the inventory lists, I can't delve deeper to list items in them.

proto code:

```
minetest.register_tool("inspector:node_inspector", {
    description = "Node Inspector",
    inventory_image = "default_tool_steelaxe.png",
    on_use = function(itemstack, user, pointed_thing)

        local pos = pointed_thing.under
        local node = minetest.get_node(pos)
        local meta = minetest.get_meta(pos)
        local inventory = meta:get_inventory()
        local lists = inventory:get_lists()
        print(#lists)
    end
})
```

I'd expect it to return 3 for furnaces (fuel, src, dest) etc. and 1 for chests and bookcases. But it never does.

**Comment by rubenwardy** [comment]
There's [a more direct way to get an inventory, btw](http://rubenwardy.com/minetest_modding_book/chapters/inventories.html#node-inventories): 

```Lua
local inv = minetest.get_inventory({type="node", pos={x=, y=, z=}})
```

#table only counts numeric indexes, not named ones.

As seen [here](http://rubenwardy.com/minetest_modding_book/chapters/inventories.html#lua-tables):

```Lua
{
	list_one = {
		ItemStack(),
		ItemStack(),
		ItemStack(),
		ItemStack(),
		-- inv:get_size("list_one") elements
	},
	list_two = {
		ItemStack(),
		ItemStack(),
		ItemStack(),
		ItemStack(),
		-- inv:get_size("list_two") elements
	}
}
```

all the keys are string based, not numbers.

So to count it, you'd do:

```Lua
local lists = inv:get_lists()
local count = 0
for key, value in pairs(lists) do
    count = count + 1
end
```

**Comment by sofar** [comment]
@rubenwardy  OK, thanks, I'll look into this later tonight to see if this was user error or not.

**Comment by sofar** [comment]
Yup, user error. Sorry for the perlin noise!
