### ISSUE TITLE
The waving parameter is not documented at all.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3450]
I just noticed that the `waving` parameter for node/liquid definitions is not documented at all. Is that on oversight or a consciousness decision?

**Comment by BlockMen** [comment]
I would guess on oversight, but we should wait until #3391 is merged or not, because it could get deprecated then.

**Comment by sofar** [comment]
#3497 would fix this, as it includes documentation for the ```waving``` parameter.

**Comment by SmallJoker** [comment]
#3497 merged
