### ISSUE TITLE
Allow all nodes to be "waving".

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3451]
Currently the `waving` parameter is limited to leaves, plantlikes and liquids. It would be extremely interesting to have the possibility to define _any_ node as waving, especially meshes and nodebox-nodes.

As I looked through the implementation this might require some change in the API, though, as currently `waving` is a simple boolean, but then would need to be...uh, something different. To explain that, currently `waving` behaves different depending on if it was set on a plantlike, liquid or leaves. This would then be required to be changed into something like an enum, allowing values of
- `LIQUID`, the liquid style is used
- `FULL`, the whole node is transformed (leaves)
- `TOP_ONLY`, only the top part is transformed (plantlikes)

Now that I think about this, this could be done without an API change by simply mapping the value `1` (as most mods are using that value, I hope) to `TYPE_DEPENDANT`, which checks the drawtype for what value to apply.

The main usecase would be to enable to have the same shader effects on mesh/nodebox-nodes, which would allow to implement custom plantlikes or liquids. Additionally this could be used for further game effects, for example to simulate some "wonky" world by setting the waving shader on the grass nodes, for example.

**Comment by paramat** [comment]
Note that waving water is something different from waving leaves/plants, and RBA intends to remove waving water (as it is very buggy) and replace it with a water surface shader.

**Comment by sofar** [comment]
![waving mesh nodes]
(https://youtu.be/3IsiROoZwZs)

```
diff --git a/src/nodedef.cpp b/src/nodedef.cpp
index 4c5d4fc..1c9e07b 100644
--- a/src/nodedef.cpp
+++ b/src/nodedef.cpp
@@ -909,6 +909,8 @@ void CNodeDefManager::updateTextures(IGameDef *gamedef,
                case NDT_MESH:
                        f->solidness = 0;
                        f->backface_culling = false;
+                       if (f->waving == 1)
+                               material_type = TILE_MATERIAL_WAVING_PLANTS;
                        break;
                case NDT_TORCHLIKE:
                case NDT_SIGNLIKE:
```

The video contains my crops:corn nodes. Only the top parts have been made waving, since the corn plant is 2 nodes high and made out of 2 nodes.

It looks awesome, I don't see why this shouldn't be enabled, it's just propagating settings from nodes to the engine.

**Comment by sofar** [comment]
I think nodeboxes likely should just wave like TILE_MATERIAL_WAVING_LEAVES, but it would be good to have a fallback and choice.

**Comment by sofar** [comment]
#3497

**Comment by SmallJoker** [comment]
#3497 merged
