### ISSUE TITLE
How can l get the version string of the server?

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3462]
l noticed that lua_api.txt only contains information of how to get the vers_string of players:
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1771
l found it after hitting ctrl+f.
How can l get the version of the server?

**Comment by est31** [comment]
This is not a forum. Please ask this on the minetest forums: https://forum.minetest.net/index.php

**Comment by HybridDog** [comment]
ok, sorry

**Comment by HybridDog** [comment]
@est31 l changed it: no question marks, does it fit now?

**Comment by rubenwardy** [comment]
You shouldn't use version strings to check for features and API differences. Instead, there should be a flag somewhere saying that `threshold` is supported.

**Comment by est31** [comment]
Agree with @rubenwardy, mods shouldn't get the version IMO but instead do feature based checks.
In fact, there even exists a mechanism for this: the minetest.features table.

**Comment by HybridDog** [comment]
there is no threshold feature l think
```
{
	nodebox_as_selectionbox = true,
	chat_send_player_param3 = true,
	use_texture_alpha = true,
	glasslike_framed = true,
	texture_names_parens = true,
	get_all_craft_recipes_works = true,
	no_legacy_abms = true
}
```
Where can l find the meaning of the available features, https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1746 doesn't inform about it?

**Comment by rubenwardy** [comment]
For now, I'd just duplicate both fields.
