### ISSUE TITLE
Client puts assets into cache even if assets are already present in the game directory

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3464]
The most prominent example is singleplayer: the client puts assets into the cache directory even though it knows that the game is singleplayer, and the client therefore has access to all the assets.
Instead of copying the assets and using up disk space, the client should rather use the game provided assets directly.

This is especially a problem on android where disk space is usually highly constrained.

One way of fixing this bug would be for the client to recognize that it is connected as singleplayer, and pretending to the server that it has all media cached, while it itself doesn't cache but loads the asset directly from the game path.

A nicer way would be for the client to somehow keep book about the game assets and their hashes and then using them if they match the server's hashes (its nicer because it would also work outside of singleplayer). E.g. the client keeps a database of hash, last changed date, and size for every asset in the game directories, and then checks upon start whether these assets are still up to date (it could even have an optimisations per game/mod, and keep also book about the last changed date of the directory).

**Comment by MoNTE48** [comment]
I totally agree with you. I had to clean this folder every update, because over time it srtanovitsya very large.
But now she is in the system, and many who use the Clean Master or other filth clean it.
Therefore, it is not a very big problem.

**Comment by sapier** [comment]
imho this ain't a bug, client and server are independent in single player this ain't any different except of some small glue code starting both at once.

**Comment by ShadowNinja** [comment]
Not a bug, but certainly a very welcome performance enhancement.

**Comment by sapier** [comment]
ShadowNinja only if someone finds a way to do it without messing up architecture ;-) Storage is cheap and everyone has plenty of, developer time to fix up the bugs caused by adding sideeffects isn't ;-)

**Comment by ShadowNinja** [comment]
@sapier: The disk space is almost irrelivant on modern computers.  I'm concerned about the time spent doing this copying over a network socket.

**Comment by C1ffisme** [comment]
> modern computers

Yes, but do remember that minetest has a known policy to try and work on old computers. I have many computers in my house, but I don't think any one of them is very modern, except maybe my laptop.

**Comment by beyondlimits** [comment]
Let's Minetest keep its local database of all the assets: path, date modified, checksum and helper flag.

**When Minetest is launched:**
```
Set the flag of all records to false.
For each asset that is outside cache directory (textures, sounds etc.)
	Find the asset in database by its path
	If it is not found or modification date doesn't match
		Compute the checksum and add/update the record along with modification date taken from file and flag set to true.
	End If
End For
Delete all records that had the flag set to false (cleanup)
For each record in database
	Remove the file of given checksum from cache directory.
End For
```
**When Minetest receives checksum of asset from server:**
```
Find the asset in database by its checksum.
If it is not found
	Find the asset in cache directory by its checksum.
	If it is not found
		Download the asset and put it in cache directory using checksum as filename.
	End If
End If
Use the asset.
```
