### ISSUE TITLE
Add chat command /m to send PM

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3472]
Because /msg is too long if you write PM often.

**Comment by kilbith** [comment]
3 letters is too long ? Huh ?
Also `/m` is meaningless. Doable with a mod (hint : https://github.com/rubenwardy/aliases).

**Comment by amadin** [comment]
Minetest chat don't memorize last message (if press "up" button, like chat in other games) so need add short commands. This is trouble of aliases mod ;)

**Comment by est31** [comment]
I don't think the engine needs this. We should add a history for the t chat instead. @amadin the f10 chat has such a feature.

**Comment by amadin** [comment]
F10 covers the floor screen and push away with left hand, please add history for the t chat.

**Comment by paramat** [comment]
> Because /msg is too long if you write PM often.

:-1: 

Please can you update the thread title for the other things you are requesting>

**Comment by est31** [comment]
In fact chat history in the t menu just got added.

**Comment by paramat** [comment]
Closing then.
