### ISSUE TITLE
log level documentation in minetest.conf.example is incorrect

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest#3480]
minetest.conf.example describes the following log levels:

```
#    Level of logging to be written to debug.txt:
#    -    <nothing> (no logging)
#    -    none (messages with no level)
#    -    error
#    -    warning
#    -    action
#    -    info
#    -    verbose
#    type: enum values: , warning, action, info, verbose
# debug_log_level = action
```

However, the code does:

```
*log_level = g_settings->getS32("debug_log_level");
```

with a net result of setting the log level to 0 if debug_log_level is set to a symbolic value

**Comment by PilzAdam** [comment]
Hm? https://github.com/minetest/minetest/blob/ea2964f5a168cb52d1b9f74a08f00c7c068c6649/src/main.cpp#L534

Is your code up to date? It was changed a while ago.

**Comment by Rogier-5** [comment]
... I was inadvertently using an older branch indeed. My apologies...
