### ISSUE TITLE
Return Old Settings Tab

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#3486]
The new "Settings" tab allows for a lot of fine tuning of Minetest but frequently changed settings, that were easy toggles in the previous version of the Settings tab, are buried in a very long list. The previous version of the Settings tab had the visual settings that are changed most often when switching to a different texture pack or upgrading/downgrading the visual settings as needed to before logging in to different servers.

Keep the current one, rename it "Advanced Settings" and bring back the old one as "Settings".

**Comment by MoNTE48** [comment]
:+1:

**Comment by kilbith** [comment]
Already requested in https://github.com/minetest/minetest/issues/3266

**Comment by Fixer-007** [comment]
+1, but maybe "advanced settings" button in "Settings" tab (too much tabs :))

**Comment by paramat** [comment]
Marked as possible blocker.

**Comment by paramat** [comment]
#3740 ecc8b70182b9ad3aaec910d7c8b32fc54cac824a is merged.
