### ISSUE TITLE
Terminal interface (ncurses --terminal) not updating dimensions.

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3492]
It seems I always have to PGDN to the bottom of the terminal when running minetestserver --terminal whenever its dimensions change.  And when its dimensions don't change, the text eventually nudges upwards until it's out of sight.

**Comment by est31** [comment]
What is your terminal application? And what precisely is the bug? When dimensions change, it should adjust automatically.

The fact that text nudges out of sight is an unfortunate problem, as the text has to be buffered, and the buffer can't be infinitely large. The only areas for improvement would be to make the buffer size user configurable.

Also note that only minetest should print to that terminal. If you have started other applications via &, they will ruin the ncurses console, and it requires a restart.

**Comment by everamzah** [comment]
I'm running minetestserver --terminal inside of tmux.  The bug is that the log slides upward on the screen, even so far as to be entirely out of sight, and I need to PGDN to "refresh" it.  The status at the top of the window, and the user input at bottom, remain at their positions regardless.

**Comment by est31** [comment]
Does it also happen if you are PGDN to the bottom.

**Comment by everamzah** [comment]
Yes, even if I PGDN to the bottom, and wait, the log text will slowly but surely move its way upward until it is out of view.  Later, if you would like, I can record a video.

**Comment by kahrl** [comment]
@everamzah I remember fixing a bug like that a long time ago, but the fix was never merged: b1fefe86dcb06eed80b1e7719553140a11daabf4

Does the above commit fix your problem?

**Comment by paramat** [comment]
Can anyone reproduce this?

**Comment by paramat** [comment]
ghost is now a deleted user on GitHub, no response, no reproduction, so closing.

**Comment by HybridDog** [comment]
@paramat, could you add a `Missing feedback` label to find such issues easier if someone gets the same problem (finding duplicates)?
