### ISSUE TITLE
Open/Close Inventory key breaks if there is a text input

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#3495]
The key for opening and closing an inventory works fine for the default survival formspec, and chests, etc., but not so well if there's any sort of text-entry.  This is clear when using unified_inventory, or the recent minetest_game creative menu.

**Comment by paramat** [comment]
I discovered this too, i'm in the habit of using the inventory key to exit the inventory instead of ESC, so found it frustrating trying to find a way to exit the creative inventory that now has a search function.

**Comment by kaeza** [comment]
I still fail to see how this is a bug. I always liked how when using UI I can always start typing right away and the text goes to the search field. You can always use Esc to close a form, which for me is not even a problem.

**Comment by paramat** [comment]
Good point.

**Comment by everamzah** [comment]
It would make more sense to tab once or even hit slash.  But I don't think tab switches between elements in formspecs.  Hitting escape seems to be the only option, here.
