### ISSUE TITLE
e2d54c9 crashes when client connects to server

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3498]
https://github.com/minetest/minetest/commit/e2d54c9f9275e4f77ec33be8054621d42945f7a4 crashes for me when it's the topmost commit - connect to a multiplayer server, and once done loading, segfault.

I wonder if ```server == NULL``` here.

@est31?

**Comment by est31** [comment]
wow, thanks for pointing out.

**Comment by est31** [comment]
preparing a fix

**Comment by sofar** [comment]
reverting it against tip still fixes it, so it must be that.
