### ISSUE TITLE
[combine: texture modifier fails to combine more than (approximately) 3600 textures

### ISSUE THREAD

**Issue by slemonide** [minetest/minetest#3510]

**Comment by HybridDog** [comment]
If you use shorter texture names, can you combine more?

**Comment by slemonide** [comment]
Using 5-letter texture names I was able to combine a texture made out of 5476 smaller textures. Before that I used textures with names composed of 14 letters in the average.

**Comment by est31** [comment]
@slemonide can you try to do it on a machine with larger specs? Most likely your RAM ran out, or graphics RAM or something.

**Comment by HybridDog** [comment]
maybe somewhere the texture string has limited size

**Comment by slemonide** [comment]
I tried combining textures again and found an interesting effect: if I try to add textures on one line and not in a square, there will be less textures I can add.

Here is the code you can notice the bug with: https://github.com/slemonide/texture_combine_test
Change w and h variables in init.lua to alter final texture size.

**Comment by paramat** [comment]
I'm sure it was never meant to combine thousands of textures.

**Comment by slemonide** [comment]
I think there should be a method that allows to combine millions of textures. Maybe by using a table instead of a string?

**Comment by HybridDog** [comment]
The textures are combined client side, aren't they?

**Comment by est31** [comment]
@HybridDog  yes

**Comment by RealBadAngel** [comment]
each texture made is stored in client's RAM until shutdown. theres no way atm to remove unused textures - so, most likely you're running out of RAM

**Comment by paramat** [comment]
> each texture made is stored in client's RAM until shutdown. theres no way atm to remove unused textures - so, most likely you're running out of RAM

> I'm sure it was never meant to combine thousands of textures.

**Comment by paramat** [comment]
Changing to a feature request.

**Comment by 0-afflatus** [comment]
Why is this even an issue?

**Comment by paramat** [comment]
Oops i didn't mean to reopen this.

**Comment by asl97** [comment]
@paramat the fact that unused texture aren't able to get unloaded (that cause this problem) is a bug.

#3806 is probably a dupe to this if you consider the underlying problem.

**Comment by obneq** [comment]
this should not be closed, its a real issue and hinders dynamic game content.
