### ISSUE TITLE
Setting an item's range high results in poor performance

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#3511]
I set an item's range to 100, and it resulted in a large increase in lag when wielded. The lag went away after I switched to something else. A range of 30 doesn't create any issues for me.

EDIT: This file defines the item in question: https://github.com/raymoo/magical_realm/blob/master/magic_spells/creative_stick.lua

**Comment by est31** [comment]
Idk, its like to say "if there are lots of mods on my server, its slow".

But if sb can propose a solution, fine with me.

**Comment by paramat** [comment]
From IRC: Calinou 	yes, don't use range > 12 for tools
12:08 		it will be very slow to trace the ray
12:08 		(the engine uses a ray casting system to point at nodes and entities, IIRC)
12:08 		also the server might revert your actions beyond 12 nodes
12:08 		(more like… will revert your actions, by experience :P)

**Comment by HybridDog** [comment]
>also the server might revert your actions beyond 12 nodes

It's not documented.
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3292

**Comment by paramat** [comment]
It might not improvable.

**Comment by HybridDog** [comment]
How about looking at Terasology for the aiming system?

**Comment by gregorycu** [comment]
The old code was horribly inefficient. For a tool of range 100, it would check interception with 1 million nodes. Referenced PR fixes this.

**Comment by raymoo** [comment]
Good to hear this was a solvable issue.

**Comment by est31** [comment]
Fixed by commit 3f8261830e0503cd59d8713d5c9aab12fc1491db

**Comment by HybridDog** [comment]
@est31 Does the commit also affect minetest.line_of_sight?

**Comment by juhdanad** [comment]
No, it is only client side.
(`line_of_sight` is improved in #4828)
