### ISSUE TITLE
I see sometimes blue sky or stars deep underground

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3520]
Please set black sky without sun and stars if player are underground (y <= -40), because if map load not fast or lag then players can see sky or sun deep underground.
0.4.13 stable (server and client).

**Comment by nanepiwo** [comment]
That would be nice, though there should be an option client-side for what depth it kicks in....However on some servers, the default client-side value would actually be above ground, so maybe the server can also have an option to give an "override" value to the client if the client has left it at default..

**Comment by paramat** [comment]
Some areas of a world may be excavated, so deciding sky darkness based on 'water level' or average terrain height doesn't work, currently the amount of dark blocks in view determine the sky darkness, it often fails but works fairly well considering the difficulties.

**Comment by amadin** [comment]
You can deciding sky darkness for y < -50 or for y < -100 because of excavated areas or allow the server owner to do it yourself in minetest.conf. Bright sky now not only for caves in mountains but in y < -100 for example (sometimes), if you move fast already excavated tunnel (fast boots or cart on power rail, or something else) you will see light because map loading longer than you move. I always see a light in the end of a tunnel on my server if i go to the cart on powerrail.

**Comment by est31** [comment]
Agree with @paramat it can't really be fixed.

**Comment by paramat** [comment]
Any fixed y value would fail and look worse. All that can be done is to try and improve the detection of dark blocks surrounding the player.

**Comment by amadin** [comment]
I always see sky or sun in long tunnels. 0.4.13.

**Comment by amadin** [comment]
I always see sky or sun in long tunnels. 0.4.13.

![screenshot_20160121_160417](https://cloud.githubusercontent.com/assets/13412191/12482771/651d90ba-c049-11e5-97a8-19c21c8fff83.png)

**Comment by 0-afflatus** [comment]
So do I, but it's hardly a showstopper.
