### ISSUE TITLE
Click-to-play feature

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#3527]
Many apps introduce their own protocols (for example, `skype://foobar` or `irc://minetest-dev`) to make it possible to switch directly from webpage to that app and do something. It would be nice to have similar for minetest too: user may start playing directly from masterserver list or server's website by clicking on special link, for example `minetest://krondor.neoascetic.me:1488`.

**Comment by MoNTE48** [comment]
I think it's unnecessary. Too much code, a lot of questions for cross-platform. In addition to Windows application is not installed in the system. Technically, it is a portable application.

**Comment by rubenwardy** [comment]
Someone did this ages ago, but I can't find the program. It was a third party windows installer which registered one of those urls. You wouldn't need to add any code to Minetest (providing it still handles `minetest --address <ad> --port <port>` correctly). As for finding Minetest, just look for *minetest* folders with bin/minetest.exe files inside at c://apps/, c://games/, My Documents, My Documents/games. It's how NBE. Or, you could have a "set the minetest path" in the windows installer to do this.

There should be an installer for Windows. I have a Windows laptop now, which would make it easier for me to make installed builds.

**Comment by neoascetic** [comment]
Agreed with installed for Windows, personally I am interested in same functionality for OSX.

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest.github.io/pull/52

**Comment by paramat** [comment]
:-1:

**Comment by rubenwardy** [comment]
Why, paramat?

**Comment by rubenwardy** [comment]
That's asking for why in particular. It is a little bit of a nightmare to maintain on all the platforms, and then some people may want to use portable builds like me. It's not really worth any core dev time, just something an outside contributor might want to do.

**Comment by paramat** [comment]
Just seems unnecessary and a little tasteless.

**Comment by rubenwardy** [comment]
That's fair enough.

**Comment by 0-afflatus** [comment]
"tasteless" lol

**Comment by paramat** [comment]
Let's close this.

**Comment by C1ffisme** [comment]
Personally I don't think I'd use this, because server urls are a lot harder to remember than much smaller IRC or Skype server names. But also, I don't really feel like Minetest is a web application...

**Comment by paramat** [comment]
This is so pointless, players are able to quickly start MT, they don't need an automatic game start from an internet hyperlink.

**Comment by HybridDog** [comment]
If it was possible to copy-paste in minetest…

**Comment by rubenwardy** [comment]
> But also, I don't really feel like Minetest is a web application...

Those aren't web links. They're internet links with a protocol name. Minetest is an internet application by definition

This probably isn't that useful though
