### ISSUE TITLE
Water flowing into water should not fan out

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3529]
related to #2767.

Waterfalls that are falling down into another pool of water should not cause fanning out of the water. This creates lots of new flowing water nodes that are completely against what water as a liquid behaves like in reality. Maybe some splashing can be seen, but water mostly absorbs all the liquid without disturbing the area as it does right now.

![before adding waterfall]
(http://i.imgur.com/CStVUGj.png)

![after adding waterfall]
(http://i.imgur.com/NZjANlk.png)

expected bahavior: water falling down onto a liquid node just stops right there. nothing more.

**Comment by tenplus1** [comment]
+1000 water should never fan out on top of water or unloaded chunks of map, it's very messy.

**Comment by sofar** [comment]
I think it fans out because it's water_flowing that reaches the top of water_source, and that's a different node name. If I read the code correctly....

**Comment by Rogier-5** [comment]
To complicate things a bit: regular water flowing into river water (or vice versa) should also not fan out...

BTW: IMO, a small fanout of 1 node, would probably look better for water flowing into other water (like when river water flows into regular water).

**Comment by C1ffisme** [comment]
Yes please, this would make many fountains or other builds require less trouble.

**Comment by red-001** [comment]
Working on fixing this.

**Comment by PilzAdam** [comment]
Is this really a bug? I think this is intended behavior.

**Comment by rubenwardy** [comment]
I'd argue that it's not a bug, but rather how the water works: however I still think the behaviour should change.

**Comment by kaeza** [comment]
I also believe calling it a bug is too much, but the .current behavior is kind of weird. So :+1:.

The "Unconfirmed bug" label is unneeded. It' neither unconfirmed, nor a bug. Call it a (mis)feature.

**Comment by NathanSalapat** [comment]
The new behavior is far better than the old, my waterfalls always looked silly, this would fix that.

**Comment by paramat** [comment]
There may be good reason for this current behaviour, see https://github.com/minetest/minetest/pull/3656#issuecomment-181152091

**Comment by red-001** [comment]
![screenshot_20160208_084209](https://cloud.githubusercontent.com/assets/12450071/12881331/034379ee-ce41-11e5-9fe0-990b0a47a510.png)

**Comment by paramat** [comment]
#3656 was closed due to tests confirming the loss of slopes on rivers.
Note that liquid will spread on liquid if the 2 are different types of water.

**Comment by 0-afflatus** [comment]
The issue here really is that water physics is just wrong.

**Comment by paramat** [comment]
Liquids are unrealistic in many ways in MT, they have to be to be simple and fast.

**Comment by red-001** [comment]
Maybe there should be an option in the node definition to make the liquid spread over other liquids? That way you could have river slopes that are longer then one node.

**Comment by paramat** [comment]
Not keen, that seems an unjustified complexity.

**Comment by paramat** [comment]
> anything that stops a source spreading when above another source will remove river slopes.
