### ISSUE TITLE
Cache map on client-side

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#353]
It would be great to cache the map on client-side, so there is no need to resend everything.

I have 2 ideas in mind for the implementation:
- add a last-changed-date to every chunk, compare, in case of differences re-request the chunk
- some rsync-like algorithm: 
  - create some kind of hash for a group of ~16 chunks
  - if its different: recheck for half the size
  - repeat down to some kind of defined minimum and resend that

That would really help people to host their server at home, where the upload is nearly nonexistent.

If its implemented as an additional standalone-version (craftproxy-like) it could be used for funny constructions:
S=server
P=players who are able to forward a port
n=players
| - = connections

```
   n  n  n
   |  |  |
n--P--S--P--n
```

**Comment by nerzhul** [comment]
We have a mesh cache now, not a map cache, and map can be downloaded but rest of your ideas is not realisable easily, closing this issue

**Comment by iqualfragile** [comment]
@nerzhul
the mesh cache is entirely unrelated to this issue.

the map being downloadable is a good first step towards using it as a chache, but it does not resolve this issue.

An issue not being easily resolvable does not mean you close it. Has there been a discussion at some other place between the maintainers that reached the conclusion that this should be closed? if so i would be happy about a link.

**Comment by paramat** [comment]
See #1732 and https://github.com/minetest/minetest/commit/9d69436052c32bc218352fc991be157a4f135b9d

sfan5 has described ths as non-trivial and nerzhul agrees. Would be good to have more dev input though, although i expect the opinions to be similar.

**Comment by iqualfragile** [comment]
small joker is opposed on the basis that it would use disk space, but right now in 2017 everybody has way too much disk space and cache size is generally a choosable thing.

this is non-trivial, i agree, but that does not mean, "no this will never happen and is opposed to the goals of this project".
so i don't see why this issue would be closed.

**Comment by SmallJoker** [comment]
Reopening. This is a reasonable feature request.

I see that my opinion on this idea has changed a bit over the time. The point of disk I/O is still there but players should be allowed to decide if and what maps they would like to cache. Surely, not enabled for Android players :P

**Comment by nerzhul** [comment]
@iqualfragile you forget android.

**Comment by rubenwardy** [comment]
unless someone opts to contribute this, I don't see this getting done. It would be much better to improve chunk sending and emerging overall.

So this may get merged if it was made as a PR, but I don't think it's worth keeping an issue open

**Comment by nerzhul** [comment]
@rubenwardy i agree, and to improve this, we need to change the compression algorithm first

**Comment by paramat** [comment]
Close in 1 month if no-one is inspired to work on it, it's been open almost 5 years.

**Comment by HybridDog** [comment]
> we need to change the compression algorithm first

You could use the filtering mechanisms of png files extended by a dimension.
https://en.wikipedia.org/wiki/Portable_Network_Graphics#Filtering
