### ISSUE TITLE
21-25% FPS drop with shaders disabled due to vertex tangents commit

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3530]
See #2755 and #2783. The commit tested is 2783 merged 14 June 2015.

The use of vertex tangents enables many shader effects and speeds up some current shaders, but unfortunately has an effect on FPS when shaders are disabled.
At the time VanessaE profiled the commit and found only an insignificant drop in FPS, which is why it was merged. Much later kwolekr found a 25% drop in FPS. Unfortunately my own test has shown a drop of 21-25%.

First 2 tests:
```
max_block_send_distance = 20
max_block_generate_distance = 20
```
In mgv7 with view range 320 and fog disabled:
First location: FPS dropped from 38 to 30, down to 79%.
Second location: FPS dropped from 36 to 27, down to 75%.

Third test.
```
max_block_send_distance = 8
max_block_generate_distance = 8
```
In mgv7 with view range 128 and fog disabled:
FPS dropped from 56 to 44, down 21% to 79%

![screenshot_20160206_024708](https://cloud.githubusercontent.com/assets/3686677/12864264/0cc5cf46-cc7d-11e5-80fc-b75098b34514.png)

![screenshot_20160206_024330](https://cloud.githubusercontent.com/assets/3686677/12864265/13bc79c6-cc7d-11e5-98a9-064413610f72.png)

To reproduce conditions i set a static spawn and did not move, panned around for a few minutes to let world generate out to the generate distance, then focussed on the exact same spot, same yaw value.

System details:
Intel Core i5-4670T CPU @2.30GHz x 4
Intel Haswell Desktop integrated graphics (no graphics card)
OS type 64 bit
Linux Ubuntu 14.04 LTS

**Comment by paramat** [comment]
@RealBadAngel is there anything you can do to improve performance?

**Comment by RealBadAngel** [comment]
i can split shaders/non shaders renderers, that would be the best way
since tangent space is crucial for any advanced effect, removing it completely is out of discussion
only way to speed up non shaders case is split

**Comment by celeron55** [comment]
I think slowing down rendering by bloating up the vertex data to create overly fancy graphics is not something that belongs in Minetest.

It's sad this was not catched earlier.

**Comment by RealBadAngel** [comment]
i will code that in next few days

**Comment by paramat** [comment]
Thought i had better do a third test to be more scientific.
This time with view range 128 looking at trees, another FPS drop of 21%.
See first post for details and screenshots.

**Comment by paramat** [comment]
See #3654 and bf884e37a06e0a8dd6c31789a69921f07ec5a9a9
