### ISSUE TITLE
objects not showing nametags

### ISSUE THREAD

**Issue by pinkysnowman** [minetest/minetest#3536]
it seems on some builds the nametags of objects will not show up but on other builds they do. 

object:set_properties({nametag = "string-here"})

the best example is to use the mobs redo and name a kitten with the nametag, it should show the name above it the same as a player does

**Comment by RealBadAngel** [comment]
Ive tested current dev, the nametags do appear over entities. Previously i had slightly outdated sources and they were absent like in your case. So, it looks like you have to get most recent windows build.
