### ISSUE TITLE
Support for multiple screens or windows

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#3539]
Specifically, personally I'd like it to be possible to move the chat and the minimap to another window, and just have the 3d view and the hot bar in the main window (and any formspecs).

How hard would this be, technically?

Seems that Irrlicht supports it, however it's not an area that I've explored: http://irrlicht.sourceforge.net/forum/viewtopic.php?f=9&t=48780

**Comment by DI3HARD139** [comment]
+1

**Comment by Fixer-007** [comment]
Reason for closing?

**Comment by rubenwardy** [comment]
This is a relatively minor issue that would require lots of refactoring - it's better to wait until hud/formspecs are redesigned before doing this
