### ISSUE TITLE
Missing docs for 'minetest.registered_biomes'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3544]
Just so we don't forget.
@sofar can you confirm this list exists? Do you know if or how it is indexed? (i'm not too good with C++).
Looking at https://github.com/minetest/minetest/blob/master/src/mg_biome.h#L66 it might be indexed by "biome" which i guess is the text name of the biome.

**Comment by sofar** [comment]
If I read this correctly...

These are derivative objects of the objdef class, which has a type (generic, biome, ore, decoration, schematic) and they seem to be indexed by a u32 index. See objdef.h.

Of course the index numbers contain all types, so lua probably has to filter these before they are returned. 

I don't think the actual registered_biomes list comes from c++, it's just kept by core.registered_biomes as part of builtin I think.

**Comment by paramat** [comment]
Thanks i guess i'll add:
```
* `minetest.registered_biomes`
    * List of registered biome definitions.
```
and not mention the index.

**Comment by paramat** [comment]
8fc8cb819b60dcaca887056e9fcb9cb7927412f1
