### ISSUE TITLE
Inventory for entities

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#3549]
e.g. trader, maid, ...

**Comment by kaeza** [comment]
Isn't this already doable with e.g. detached inventories?

**Comment by C1ffisme** [comment]
It would be nice if we didn't have to pass the return values from said inventories through the player and then into the entity. That is what the NPC Framework mod does.

**Comment by kaeza** [comment]
Correct me if I'm wrong, but adding special support for inventories in entities would require a change in the map format.

If you need to persist an entity-specific inventory, you can do it by storing the serialized list in the entity metadata.

**Comment by maikerumine** [comment]
If your interested, I figured out a way to do this with bones, so on death their drops go into the bones.  see my esmobs for the result.  https://forum.minetest.net/viewtopic.php?f=11&t=13616

it is hackish but works.
