### ISSUE TITLE
on_rotate not documented

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3553]
The ```on_rotate``` node method isn't documented, but it's used all over minetest_game. This should be in ```lua_api.txt```.

**Comment by sofar** [comment]
I mean, even if there's a reference to ```game_api.txt``` then that would be helpful.

**Comment by 4Evergreen4** [comment]
Isn't `on_rotate` a function defined in minetest_game?

**Comment by sofar** [comment]
Took me a while to figure that out, yes. I think that's sufficient, but it had me puzzled for a bit to understand why it's not in lua_api.txt.
