### ISSUE TITLE
Bright particles, no light needed.

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#3555]
Turns out you can only see particle effects when enough light is present so things like fireworks and lightning strikes at night-time will never be seen... so...

would it be possible to add a new flag to the add_particle function that shows the texture without lighting effects and at full brightness?  this could maybe even be used for entity sprites (fireballs), something like:

```
minetest.add_particle({
    pos = {x=0, y=0, z=0},
    vel = {x=0, y=0, z=0},
    acc = {x=0, y=0, z=0},
    expirationtime = 1,
    size = 1,
    collisiondetection = false,
    vertical = false,
    texture = "default_wood.png",
    playername = "singleplayer",
    always_lit = true,
})

**Comment by RobertZenz** [comment]
I'd rather allow to set some sort of lighting level, which would allow to darken and lighten the particles as needed.

That could then also be abused to have nice effect, like three spawners at the same location which are spewing differently lit particles.

**Comment by tenplus1** [comment]
maybe changing always_lit to light_level would be a better option ?
