### ISSUE TITLE
`degrotate` should also work for nodeboxes and meshes.

### ISSUE THREAD

**Issue by RobertZenz** [minetest/minetest#3560]
The paramtype2 `degrotate` should also work for meshes and nodeboxes. That would open up whole new possibilities on how to use nodeboxes and meshes.

**Comment by paramat** [comment]
:Param2 is already used or reserved for the 24 rotations, which is much more important. With plantlike param2 was unused.

**Comment by Rui-Minetest** [comment]
👍

**Comment by paramat** [comment]
:-1: :-1: :-1: 
Fine rotation is barely acceptable for flat planes and plantlike, but totally unnacceptable for cuboids. i actually want to remove degrotate completely.
