### ISSUE TITLE
Angular velocity for prediction of spinning entities

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#3562]
It would be cool if you could add spinny effects to entities that are predicted by the client, by setting angular velocity.

**Comment by raymoo** [comment]
actually, graphical effect use case is probably covered by animated meshes

**Comment by paramat** [comment]
Don't we already have clientside entity auto-spin?

**Comment by paramat** [comment]
The PR that adds pitch and roll rotations doesn't add the new types of auto-spin, we decided against it, see threads for discussion.

**Comment by paramat** [comment]
Any core dev support for spin in all 3 axes?
