### ISSUE TITLE
Memory leaks when using minetest.place_schematic_on_vmanip()

### ISSUE THREAD

**Issue by slemonide** [minetest/minetest#3566]
How to reproduce the bug:
1. Install this mod https://github.com/slemonide/roomgen
2. Create new world and wait
3. Memory will leak

**Comment by est31** [comment]
Somebody has to test the claim. If nobody did by friday next week, I will.

**Comment by paramat** [comment]
Will test.

**Comment by paramat** [comment]
Confirmed rapid rise when this mod generates world, not cleared by exiting to menu, only when exiting to OS @kwolekr

**Comment by kahrl** [comment]
init.lua:43
```table.insert(placed_corridors, corridor)```

What is the purpose of this line? This could be the source of the memory leak.

**Comment by slemonide** [comment]
I think it has something to do with this
https://github.com/freeminer/freeminer/commit/551eb8515450be4167504f12653d111e09b0ee32

**Comment by paramat** [comment]
kahrl, will test without that line.

**Comment by paramat** [comment]
@kahrl no change with that line removed, this leak is >1GB per minute.

**Comment by paramat** [comment]
> I think it has something to do with this

Tested that commit and unfortunately doesn't fix this.

**Comment by slemonide** [comment]
Some new data about the bug.
If mod is started using the minetestserver, server doesn't leak. Unlucky, some clients do.
Also, can it be that this bug depends on what video card the person is using? My client froze and I have AMD/ATI Mobility Radeon HD 5650/5750 / 6530M/6550M

**Comment by slemonide** [comment]
Even more info. If time is changed to night, the tunnels will turn dark. If mesecons lamp is placed then the lightning will update and memory might leak.

**Comment by paramat** [comment]
Possible blocker, but needs more testng.

**Comment by gregorycu** [comment]
slemonide is correct. freeminer/freeminer@551eb85 fixes a memory leak that is hit by this scenario. Maybe it's not the only one, but it's the most egregious. Recommend we pull this change over.

**Comment by gregorycu** [comment]
In terms of the lighting issue, this looks like a different thing.

**Comment by est31** [comment]
@slemonide please stop linking commits from freeminer, we can't use them and if we look at them and implement similar changes we might make ourselves vulnerable for accusations that we copied them.

@gregorycu we can't use that patch as its under GPL not LGPL, like minetest is.

**Comment by kilbith** [comment]
My ass, freeminer backports MT's commits daily for years and proller would dare to DMCA'ing upstream ?

Do you know a different way for fixing that leak ? If it's the only trivial way, there's no reason to worry about licensing shit.

**Comment by gregorycu** [comment]
That is their right. Blame the LGPL.

**Comment by kilbith** [comment]
Oh and btw, we _used_ Freeminer commits in the past without complains for fixing RBA's leaks.

**Comment by est31** [comment]
@kilbith they chose to use a more strict license, which especially means that they do not want us to take patches without their consent, and we should respect that. I am no lawyer, but I don't want to risk anything here.

That being said, I have given the code a look, and can understand why there there is leak like behaviour happening, and that the fix from freeminer makes sense. I just don't understand why it checks whether the name is empty first, its never is set I think.

Also, mean people may call it not a bug, but just wrong behaviour from lua.

**Comment by kilbith** [comment]
@est31 Then revert https://github.com/minetest/minetest/commit/c4287a0d681abd4728f978d2ac55285cf6a6ecad if you dare. It's illegally backported (https://github.com/freeminer/freeminer/commit/7ba086c25509c740c48fd3a9c4a16d90b460decb). Amongst other stuff probably...

**Comment by gregorycu** [comment]
@est31 It's pretty clearly a bug. We seem to try to cache on the filename but fail.

The discussion around historically questionable merging is a good one, probably best had in a difference place than this page.

**Comment by est31** [comment]
@kilbith thanks for spotting, please open a new issue report for cases you find. I wouldn't think that one is infringement, as its far more trivial than this fix (you only have to read one method, and the method name isn't very creative either).

@gregorycu see #3926 ; its not an infringement in my opinion.

**Comment by est31** [comment]
@slemonide can you try the patch whether you still can reproduce the behaviour? (Or anybody else who can reproduce).

**Comment by gregorycu** [comment]
@est31 Thanks. I won't submit my PR then.

The reason i think it's a bug is we attempt to cache off the file name and fail to do so properly. If we didn't attempt to cache we wouldn't run out of memory, and we wouldn't have this problem. We expose a function called place_schematic_on_vmanip, which accepts a filepath for the schematic. We can't blame users for using it in such a manner.

It's largely an academic discussion as we are fixing the bug, or whatever we want to call it.

I'm testing a similar change in my code now. Will let you know.

**Comment by gregorycu** [comment]
@est31 Looks good to me.

What do you want to do about the lighting bug?

> Even more info. If time is changed to night, the tunnels will turn dark. If mesecons lamp is placed then the lightning will update and memory might leak.

**Comment by paramat** [comment]
I wouldn't worry about the lighting issue too much.

**Comment by paramat** [comment]
The lighting bug is confirmed in my lua mapgens #3930

**Comment by paramat** [comment]
See #3926 , fix is merged, please test.
