### ISSUE TITLE
Client side filter chat, error messages or chat from a specific player ignored

### ISSUE THREAD

**Issue by joshuamars** [minetest/minetest#3569]
Clients should be able to independently filter incoming chat.  Error messages and auto-generated chat can get annoying, as well as spam from specific players.

**Comment by 0-afflatus** [comment]
I'm currently looking for ways to filter some of my more verbose players. If it were possible for clients to create filters on an 'if message contains <"string">' basis that would obviate a certain amount of server-side scripting.

**Comment by sfan5** [comment]
Possible using CSM, closing.
