### ISSUE TITLE
Add tables support for AreaStore

### ISSUE THREAD

**Issue by slemonide** [minetest/minetest#3570]
insert_area(edge1, edge2, data) method seems to require data to be a string. I propose to make it support tables as data, too.

**Comment by est31** [comment]
Can you edit the description so that we know what you mean?

**Comment by paramat** [comment]
Any core dev support?

**Comment by SmallJoker** [comment]
`minetest.serialize` can be used to convert the table into a string. If that's too slow, then consider to use "data" only for storing an unique key which then can be used to look up the cached table in Lua.
