### ISSUE TITLE
Issue on compile with CrystaX NDK

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3575]
jni/../jni/src/database-leveldb.cpp:61: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:86: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:99: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:43: error: undefined reference to 'leveldb::Options::Options()'
jni/../jni/src/database-leveldb.cpp:46: error: undefined reference to 'leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
jni/../jni/src/database-leveldb.cpp:47: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status

**Comment by est31** [comment]
I don't know your modifications, but somehow it seems that there is some mismatch between leveldb headers and the created leveldb so file.

Perhaps leveldb got compiled with the wrong compiler?
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=791086

Can you do `make clean_all` and try again?

**Comment by MoNTE48** [comment]
1) i use official minetest master repo. No changes!
2) make clean_all - Yes, the problem remains
3) Leveldb and CrystaX NDK collaborators say "This is minetest bug"

**Comment by MoNTE48** [comment]
oops, i changed minetest jni/Android.mk - i add LOCAL_CPPFLAGS += -std=c++98
It advised CrystaX dev, to ignore errors from Minetest, which I created previously Issues

**Comment by est31** [comment]
Well, that was the issue then.

**Comment by MoNTE48** [comment]
@est31 , I do not quite understand you. CrystaX Dev say me, it was a mistake to Minetest. Do not you agree?

**Comment by est31** [comment]
No, if you add `LOCAL_CPPFLAGS += -std=c++98` to your Android.mk, precisely this issue will happen. You either have to remove it, or pass `-std=c++98` to leveldb too, via CPPFLAGS.

**Comment by MoNTE48** [comment]
I'm understood, thank you!
However, I think it is possible to add on Makefile! Some want to use CrystaX. I can do Pull request.
By the way, you decide https://github.com/minetest/minetest/issues/3512

**Comment by est31** [comment]
I see, `LOCAL_CPPFLAGS += -std=c++98` is a workaround around bug #3512 . You'll have to edit the makefile then: https://github.com/minetest/minetest/blob/master/build/android/Makefile#L391

change it to
```
export CPPFLAGS="$${CPPFLAGS} ${TARGET_CFLAGS_ADDON} -std=c++98";
```

and then make a clean build.

But #3575 is no bug, with neither minetest nor leveldb nor crystax.

**Comment by MoNTE48** [comment]
Ok. However, anyone interested in correcting https://github.com/minetest/minetest/issues/3512 or I (or you) just push commit with a workaround? :)

**Comment by MoNTE48** [comment]
LevelDB use

**Comment by MoNTE48** [comment]
Well, it works for me. But problem number 2. I press Start Singleplayer, and Minetest freezes on Media ... The game does not crash, but not loaded

**Comment by est31** [comment]
Alternative workaround: just revert the commit 52e5b513ed9dc143c967c733423fe751e1b663d1
A bug that exists "for several years" can't be super horrible.

**Comment by MoNTE48** [comment]
@est31, i revert commit, make clean_all and get
``` jni/../jni/src/threading/event.cpp: In member function 'void Event::wait()':
jni/../jni/src/threading/event.cpp:54:2: error: 'MutexAutoLock' was not declared in this scope
  MutexAutoLock lock(mutex);
  ^
jni/../jni/src/threading/event.cpp:56:11: error: 'lock' was not declared in this scope
   cv.wait(lock);
           ^
jni/../jni/src/threading/event.cpp:56:11: note: suggested alternative:
In file included from /home/monte48/crystax/sources/cxx-stl/gnu-libstdc++/5/include/condition_variable:39:0,
                 from jni/src/threading/event.h:30,
                 from jni/../jni/src/threading/event.cpp:26:
/home/monte48/crystax/sources/cxx-stl/gnu-libstdc++/5/include/mutex:650:5: note:   'std::lock'
     lock(_L1& __l1, _L2& __l2, _L3&... __l3)
     ^
jni/../jni/src/threading/event.cpp: In member function 'void Event::signal()':
jni/../jni/src/threading/event.cpp:75:2: error: 'MutexAutoLock' was not declared in this scope
  MutexAutoLock lock(mutex);
  ^
make[2]: *** [obj/local/armeabi-v7a/objs/minetest/jni/src/threading/event.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by MoNTE48** [comment]
@est31 , please, open this!
We need to add or
export CPPFLAGS = "$$ {CPPFLAGS} $ {TARGET_CFLAGS_ADDON} -std = c ++ 98";
in Makefile (do it?) or create path to fix this bug. However, if you believehttps://github.com/google/leveldb/issues/330  this is a problem  minetest, not leveldb

**Comment by MoNTE48** [comment]
Hmm, i add this line on makefile, make clean_leveldb && make release -j64 and get
```
jni/../jni/src/database-leveldb.cpp:61: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:86: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:46: error: undefined reference to 'leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
jni/../jni/src/database-leveldb.cpp:47: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:99: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
```

**Comment by est31** [comment]
@MoNTE48 This is neither a problem with minetest, nor with leveldb, nor with the CrystaX NDK. Its a problem of you adding `-std=c++98"` to the cppflags. As the base bug #3512 is now fixed, there really is nothing anymore we as minetest devs can do.

**Comment by MoNTE48** [comment]
No! I remove -std=c++98 on makefile, clone latest commits, make clean_all && make release and get this error!

**Comment by everamzah** [comment]
Not trying to be naive, but did you try doing a fresh clone instead of pulling?

**Comment by MoNTE48** [comment]
@everamzah yes, on my home pc 3min ago
jni/../jni/src/database-leveldb.cpp:61: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:86: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:46: error: undefined reference to 'leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
jni/../jni/src/database-leveldb.cpp:47: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
jni/../jni/src/database-leveldb.cpp:99: error: undefined reference to 'leveldb::Status::ToString[abi:cxx11]() const'
collect2: error: ld returned 1 exit status
make[2]: *** [obj/local/armeabi-v7a/libminetest.so] Error 1

**Comment by est31** [comment]
did you remove it from jni/Android.mk too?

**Comment by MoNTE48** [comment]
@est31, I remove minetest folder and reclone
