### ISSUE TITLE
C++11 VERSION_STRING

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3584]
invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
 #define VERSION_STRING STR(VERSION_MAJOR)"."STR(VERSION_MINOR)"."STR(VERSION_PATCH)

**Comment by nerzhul** [comment]
please provide the patch if you have the solution, it's faster

**Comment by MoNTE48** [comment]
This warning, which appears about 10 times to build on Android. I do not pay attention to it.
https://github.com/minetest/minetest/blob/master/build/android/Makefile#L831
I'm not sure I understand what's wrong :)

**Comment by nerzhul** [comment]
Warnings should be fixed :)

**Comment by MoNTE48** [comment]
That's your job, not me. I'm not a C++ programmer.

**Comment by rubenwardy** [comment]
And yet you maintain a C++ game on the app store?

**Comment by MoNTE48** [comment]
@rubenwardy, Which is much better and much more popular than Minetest on Play Store.

**Comment by everamzah** [comment]
Does it have a Use key?

**Comment by rubenwardy** [comment]
Only because of the name, really.
(L)GPL apps aren't legally allowed on the app store.

**Comment by MoNTE48** [comment]
App Store is not the only way to install applications on Apple Devices;)

**Comment by MoNTE48** [comment]
@rubenwardy vlc LGPL https://itunes.apple.com/ru/app/vlc-for-mobile/id650377962?mt=8
I can not use gpl license because xcode closed source. But I have a right to use the LGPL :)

**Comment by everamzah** [comment]
Whoops!  Looks like minetest_game should be GPL then!

**Comment by MoNTE48** [comment]
@everamzah minetest_game use LGPLv2.1+ license

**Comment by everamzah** [comment]
Well that's unfortunate.

**Comment by MoNTE48** [comment]
@nerzhul,
```
	echo "#define VERSION_STRING ${VERSION_MAJOR}.${VERSION_MINOR}             \
	.${VERSION_PATCH}";                                                        \
```

**Comment by rubenwardy** [comment]
> @rubenwardy vlc LGPL https://itunes.apple.com/ru/app/vlc-for-mobile/id650377962?mt=8
It's dual licensed under Mozilla Public License and GPL 2: http://www.videolan.org/vlc/download-ios.html

> I can not use gpl license because xcode closed source. But I have a right to use the LGPL :)

http://stackoverflow.com/questions/459833/which-open-source-licenses-are-compatible-with-the-apples-iphone-and-its-offici

**Comment by MoNTE48** [comment]
Minetest could change the license, as did VLC. And I would have given Minetest port on iOS :)
I know that many developers Minetest never go for it, just a thought.

**Comment by rubenwardy** [comment]
It would be a pain, you'd have a lot of contributors to ask: https://github.com/minetest/minetest/graphs/contributors

**Comment by MoNTE48** [comment]
I know that it will take a few months, but I'm sure it's possible. In addition, many investors are translators. their resolution is not required.

**Comment by sfan5** [comment]
Minetest is not intended to be compiled as C++11, submit a pull if you want this fixed.

**Comment by MoNTE48** [comment]
;)

**Comment by est31** [comment]
I've coded this but didnt test it: https://github.com/est31/minetest/commit/ef779b0ab6d7460fe074d8b2eda05864c822d905

can you test it?

**Comment by MoNTE48** [comment]
I'll check it out. Also, add patch for Irrlicht in sourese/Irrlicht/os.cpp
#include "time.h"
#include "sys/time.h"
This fixed  C++11 stop compilation

**Comment by MoNTE48** [comment]
@est31, yes, this work. Thank you!

**Comment by est31** [comment]
ef779b0ab6d7460fe074d8b2eda05864c822d905
