### ISSUE TITLE
Plant-like nodes on some servers render parts depending on yaw

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3598]
This problem occurs on 0459eca when you play on "outdated" servers like "Just Test", "Linux Gaming 2", "Liberty Land" and possibly others, few days earlier build 22bc66d has no such problem. I suspect it is somehow connected to https://github.com/minetest/minetest/commit/882a89d65aa78b89cfaf2af054d15cc4c94ad022 @sofar 

Images that demonstrate this problem: https://imgur.com/a/ENgAx
This problem does not occur, if you play singleplayer (and probably dedicated server of 0459eca). So this looks like some compatibility problem with older servers.

PR with a fix here: https://github.com/minetest/minetest/pull/3600

**Comment by sofar** [comment]
Confirmed

**Comment by sofar** [comment]
At issue is that backface culling is being enabled based on tiledef, and v1 tiledef format is always setting it enabled irregardless.
