### ISSUE TITLE
Minetest.conf.example is too long.

### ISSUE THREAD

**Issue by red-001** [minetest/minetest#3599]
Minetest.conf.example is 1398 lines long. This means the average player can't find a setting in a reasonable amount of time. I think it would be best if minetest.conf and the example were broken into multiple files e.g graphics.conf, keys.conf, server.conf. This would make config files more readable.

**Comment by lisacvuk** [comment]
He can press Ctrl+F, right? :smile:

**Comment by Dragonop** [comment]
I agree with @lisacvuk 
Maybe adding a line that says "press Ctrl+F" to search? I think it's Ctrl+B in some Windows text editors.

**Comment by red-001** [comment]
That means I need to know what the setting is called before I search for it meaning I only find out if I guessed correctly.

**Comment by RobertZenz** [comment]
This might actually be a neat idea...but only if the settings are not limited to one file. Meaning Minetest should not limit what settings can be in what file, that would allow to still have one generic minetest.conf file instead of multiple.

**Comment by Calinou** [comment]
I propose splitting `minetest.conf` into `common.conf` (settings that impact both the client and server) `client.conf` (settings that impact only the client), `server.conf` (settings that impact only the server).

**Comment by C1ffisme** [comment]
What about putting relevant functions together and adding an index?

Or we could put a copy of it on ```dev.minetest.net``` and just leave a link, with maybe a few commonly used configurations and their descriptions.

**Comment by Dragonop** [comment]
No thanks, my connection is unstable and I *need* an offline copy of minetest.conf.example and lua_api.txt. Using external links would only make it a pain everytime I update.

**Comment by C1ffisme** [comment]
@Dragonop I do agree with you on that, my own connection to the internet is horrible itself.

I guess we still have the index idea.

Or we could remove certain settings that have little-to-no use. I'm not sure which ones, though, since I rarely change my settings in the text file.

**Comment by est31** [comment]
@red-001 The average player can use the settings menu added by PilzAdam to the mainmenu. minetest.conf.example is for people who know how to use ctrl+f. Both contain the same amount of documentation.

However, one could think about a settingsytpes.txt -> html formatter to put the config on the website.

**Comment by red-001** [comment]
@C1ffisme I would agree that there are settings in minetest that have little to no use or are only useful in a few edge cases. 

@est Afaik settingstype.txt doesn't have all the settings in it but I could be wrong.

**Comment by est31** [comment]
settingstypes.txt in fact has all settings, and minetest.conf.example is autogenerated from it.

**Comment by MoNTE48** [comment]
@est31, "However, one could think about a settingsytpes.txt -> html formatter to put the config on the website." +1

**Comment by srifqi** [comment]
> However, one could think about a settingsytpes.txt -> html formatter to put the config on the website.

So, has it already done?

**Comment by est31** [comment]
No.

**Comment by paramat** [comment]
The length of conf.example seems okay to me for now, maybe it could have more empty lines and clearer section titles to make it easier on the eyes and easier to navigate.

**Comment by ShadowNinja** [comment]
> settingtypes.txt -> HTML

Done: http://ix.io/o8a?diff
Output: http://doxy.minetest.net/settings.html

**Comment by est31** [comment]
Nice.

**Comment by yyt16384** [comment]
Well, settingtypes.txt doesn't have all settings. At least `keymap_autorun` and `keymap_console` are not there.

**Comment by est31** [comment]
@yyt16384 if you find settings that are not inside settingstypes.txt, you should make a PR that adds them. Otherwise they don't get into minetest.conf.example, and other parts.

**Comment by lightonflux** [comment]
> I propose splitting minetest.conf into common.conf (settings that impact both the client and server) client.conf (settings that impact only the client) and server.conf (settings that impact only the server). This will make each file much shorter already.

This would also remove the confusion about which settings apply to client, server or both.

Or there needs to be a easy way to determining the scope of a setting in the txt or html documentation files mentioned above.

**Comment by nerzhul** [comment]
@Calinou common.conf make no sense :)

**Comment by est31** [comment]
@lightonflux on the settings dialog in the mainmenu, the settings are very clearly ordered after client, server, and both. And in minetest.conf.example, they are ordered too, albeit you have to search for the headlines.

**Comment by Calinou** [comment]
> @Calinou common.conf make no sense :)

We can have just `client.conf` and `server.conf`, but it would mean some settings will be duplicated. There are some settings like `name` which applies to both client and server, hence my proposal.

**Comment by red-001** [comment]
Closing as the new settings menu fixed this.
