### ISSUE TITLE
Add ability to update node/craft/tool/entity properties during runtime

### ISSUE THREAD

**Issue by Maksym-L** [minetest/minetest#36]
Now only meta data of the node can be changed in real-time. But to change property such as texture you need to remove node from the world and place another node with desired property on the same place. 

Such feature required for implementation of animated furnace like objects, and objects with some kind of progress indication on their sides.

**Comment by Novatux** [comment]
Related to https://github.com/minetest/minetest/pull/1118

**Comment by nerzhul** [comment]
@Novatux can you rebase and finish this PR ? :)

**Comment by falsechicken** [comment]
:+1: I would love to see this. A big limitation for me at the moment is not being able to dynamically set the tooltip description on items. 

I have been working on a locked door and key mod and would like to be able to have the description text change from "Key" to "Key to <nameofdoor>".

**Comment by ShadowNinja** [comment]
@falsechicken That's separate from meta nodedef.  It should be easier to implement though.

**Comment by paramat** [comment]
Can we close this due to its age and because #2887 is similar?

**Comment by ShadowNinja** [comment]
@paramat: Since this is the older issue the new one should probably be closed instead.

**Comment by paramat** [comment]
Fine by me.

**Comment by raymoo** [comment]
I am thinking of implementing tool capability overrides. What do people think of having a "toolcaps" key with a value that is a JSON-serialized toolcaps table?

@sfan5 suggested an alternative in IRC:
>+sfan5 ╡ wouldn't it be nicer to be able to define several toolcaps ahead of time and have "toolcaps" just be an int
>╡ would be less flexible but nicer imo

Which I think removes too much flexibility.

**Comment by raymoo** [comment]
@rubenwardy I want to add stuff to serialized item metadata, but it looks like if I add anything after the meta key/value pairs it will append garbage to the end of the last pair, from the point of view of older clients.

**Comment by raymoo** [comment]
Though I suppose I could just put the serialized stuff in a special-use meta field.

**Comment by raymoo** [comment]
PR for tool capability overrides: #5612

**Comment by paramat** [comment]
#5612 merged.

**Comment by paramat** [comment]
> But to change property such as texture you need to remove node from the world and place another node with desired property on the same place

Yes, no problem, this is preferable to a complex and problematic alternative.

> Such feature required for implementation of animated furnace like objects, and objects with some kind of progress indication on their sides.

We have animated textures, but otherwise textures can be changed by replacing with other nodes. Its not a high priority need.

However more generally this feature may be useful.

**Comment by Bulldog83** [comment]
We can change facedir of node by changing it's param2. How about to add to node defenition 'node_states' field as some table with alternative drawtypes and tiles for node and select needed by using param2?
Something like:
```
    node_states = {
        {
              drawtype = "mesh",
              mesh = "node_mesh.obj",
              tiles = { ... }
        },
        {
              drawtype = "nodebox",
              nodebox = { ... }
              -- here will be used default tiles
        }
    }
```

**Comment by Wuzzy2** [comment]
This issue should be closed.

The use cases that were stated are:

* animation: Obsolete. We already have animated textures
* Allowing to change node textures without changing the node itself: This is reasonable, but I don't think node definitions need to be overwritten all the time for this.

In fact, I have posted a different idea to make node textures changable, namely, by adding a new `paramtype2`: https://github.com/minetest/minetest/issues/9193

I summarize:
This suggestion is ancient, OP hasn't replied for >8 years, the suggestion is partially technically obsolete, the suggestion has enormous design implications that would cause huge disruption, the only valid stated use case is for changable node textures, and for this use case there's already a more lightweight alternative suggestion on the table.

Therefore, I recommend to close this isse.

**Comment by Wuzzy2** [comment]
@paramat: "Supported by core dev" lol why? Was this label added by mistake?

**Comment by v-rob** [comment]
I'm going to go out on a limb and say that the label is a mistake.  If it isn't, it can be added again.  However, this feature is essentially infeasible at the present time with Minetest's current capabilities (metadata is bad for the job; it might be possible with SSCSM, but that's not a feature yet, so irrelevant to this issue), so closing.
