### ISSUE TITLE
slabs back to blocks

### ISSUE THREAD

**Issue by CodePhase** [minetest/minetest#3601]
Hello,

I am running Minetest 0.4.12 and am unable to change slabs back to their original block forms by crafting one on top of the other as mentioned on the wiki (http://wiki.minetest.net/Slab):
> Two slabs of the same material can be built into full blocks by building them over each 
> other. Can be used as thin wall/fence when rotated using screwdriver.

Attached is a screenshot.  I have no mods enabled and am running the default minetest_game.  
![noslabtoblock](https://cloud.githubusercontent.com/assets/14020204/12517126/38a82ce6-c0ff-11e5-9427-3c53a3ea9b73.png)
Please let me know if you need any other information.  Thanks!

**Comment by CodePhase** [comment]
I also noticed this issue on the latest git checkout for both minetest and minetest_game.

**Comment by ExcaliburZero** [comment]
It looks like this is an issue with minetest_game, rather than the minetest engine.

You should probably report this issue in the [minetest_game issue tracker](https://github.com/minetest/minetest_game/issues) instead.

**Comment by sofar** [comment]
This issue needs to be moved to minetest/minetest_game indeed.

**Comment by est31** [comment]
As already pointed out, this is the wrong tracker.

**Comment by CodePhase** [comment]
Ok will do.  Thanks!

**Comment by CodePhase** [comment]
FYI this wasn't a bug, I was doing it wrong.  It's not a craft recipe.  A player needs to place a slab in the world then place another on top of it to create a block.  Then you can mine the black as normal to get it back into your inventory.
