### ISSUE TITLE
Odd behaviour of liquids

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#3604]
I'm not sure if this a bug or a wanted behaviour, but it looks odd to me. Flowing nodes of liquids are spreading (nearly) infinitely over a hill during floating downwards even if the source node has been removed. Shouldn't there be some kind of limitation?
![screenshot_20160122_234255](https://cloud.githubusercontent.com/assets/6941454/12525296/9da5fae2-c163-11e5-9c3a-20824c920fc0.png)
![screenshot_20160122_234305](https://cloud.githubusercontent.com/assets/6941454/12525299/9da7a932-c163-11e5-899e-7e69118b9a11.png)
![screenshot_20160122_234325](https://cloud.githubusercontent.com/assets/6941454/12525298/9da72ebc-c163-11e5-8410-f7a1644d3dc5.png)
![screenshot_20160122_234442](https://cloud.githubusercontent.com/assets/6941454/12525300/9da8968a-c163-11e5-9f97-bd63ffa4039a.png)

**Comment by est31** [comment]
Yeah, there are some pseudo sources, but I don't really know the code involved. It works for me that I remove / add blocks close to the pseudo sources, sometimes there is also a chain reaction.

**Comment by paramat** [comment]
This is 'normal', flowing water does spread out on every possible surface (because this is the simplest behaviour to implement) so multiplies insanely.

**Comment by paramat** [comment]
RHRhino let me know if you're happy for me to close this, but feel free to continue to discuss.

**Comment by RHRhino** [comment]
Okay I see. The behaviour of flowing nodes is differs between a surface and a mountain. If you remove the water source on a flat surface all flowing nodes just disappear slowly. If you remove the source node on a mountain the flowing nodes continue spreading down the whole montain and don't stop until the reach a flat surface, in this example the sea. I expected that those nodes also just disappear slowly. This would make more sense for me, but if this behaviour is wanted, then you can close this issue, because it's not a bug. :smile:

**Comment by paramat** [comment]
Yes when water drops a node it receives a 'drop boost' which makes it flow further horizontally, this is wanted otherwise water would never flow all the way down a slope as is expected.

**Comment by 0-afflatus** [comment]
Thanks for the explanation.
