### ISSUE TITLE
acacia leaves not waving

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#3607]
acacia leave block not waving

**Comment by est31** [comment]
This issue tracker is about the minetest engine, not about minetest_game. Can you open a bug on this tracker: https://github.com/minetest/minetest_game/issues

**Comment by tobyplowy** [comment]
Sorry I'm new here where do I put this?

**Comment by est31** [comment]
Click the link above, it contains the issue tracker for the minetest_game repo.

**Comment by tobyplowy** [comment]
Ok thx you probably don't know this but when will the next update come out? (stable)

**Comment by est31** [comment]
No idea.

**Comment by tobyplowy** [comment]
:( I hope its soon because I see great potential in this game
