### ISSUE TITLE
Long Android build times

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3614]
Android port is being built in several times longer than Linux version.
I thought that we can keep prebuilt binary files (* .so), and update them if necessary (it is 1 every 3-6 months is sufficient). 
I say this idea with my programmer and he liked it. When he will have time for this, he added this feature (makedeps.sh), it MultiCraft. If you want, I can give this code to Minetest :)

**Comment by est31** [comment]
I rather build from source, minetest is an open source project after all. Its a bad habit IMO.

Also it bloats the repo size which is something @celeron55 doesn't like.

**Comment by neoascetic** [comment]
Absolutely bad idea

**Comment by ShadowNinja** [comment]
I agree.  Including sources is bad enough, we can't include binaries.
Plus, we'll need several copies of each lib: x86, mips, and arm variants.

**Comment by kaeza** [comment]
This could be done like MinGW cross-compilation is done via `buildbot`: have a trusted person host the binaries externally and pull them as part of build process.
