### ISSUE TITLE
Swords do not wear when fighting

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3615]
Scenario: 2 players in multiplayer, damage enabled, creative disabled.

Axes, Pickaces, Hoes, Shovels, all show tool wear after digging.

However, no matter how often one strikes a player with a sword, the sword does not wear down.

Swords _do_ wear down when used for digging, but this is not their primary use. They should wear down when punching entities and players, too.

I think this is an oversight, as the engine clearly implements all sorts of things to add wear to tools, and swords are just that.

**Comment by sofar** [comment]
I can see that there's a callback for when a player is punched, but nothing for the more generic "punches an object" case, which is required. This needs a new registration table and a callback...

If we'd just modified the damage paths to ```addWear()```, which is entirely possible, we'd still have to remove the itemstack from the wielder when it wears out, and add a different callback to tell mods/game that the item broke, which seems more convoluted

**Comment by est31** [comment]
:-1: Current behaviour is fine for me. And it can be modified by mods so we only change defaults here.

**Comment by Calinou** [comment]
> Current behaviour is fine for me. And it can be modified by mods so we only change defaults here.

I don't get it, why would swords ever have infinite durability when attacking entities? It doesn't really make any sense. Currently, they only wear when digging leaves (and slightly increase the digging speed).

**Comment by est31** [comment]
Minetest should be kept simple we cant have total realism.

**Comment by rubenwardy** [comment]
:+1: for consistency.

**Comment by RealBadAngel** [comment]
If swords doesnt wear while literally everything else does it looks like a bug not a feature.
Definitely needs fixing.

**Comment by est31** [comment]
Swords do wear, just not for fighting. Its just bad if you go in minecraft mode and you have to punch objects to pick them up after they got mined, and the pickaxe gets worn down due to that punching.

**Comment by Ekdohibs** [comment]
:+1: for consistency too, but it should be a callback when an item is used on an object, so that the problems outlined by @est31 are avoided.

**Comment by RealBadAngel** [comment]
"Swords do wear, just not for fighting." Excuse me, what is the purpose of the sword then?

**Comment by C1ffisme** [comment]
If we really have no use for swords in singleplayer (other than digging nodes which we already can dig with our hands) than we should probably go ahead and add durability for multiplayer. This could also serve a purpose if we ever add say... a mob API.

**Comment by sofar** [comment]
@est31 what?

**Comment by rubenwardy** [comment]
Punching inventory cubes doesn't change their HP: inventory cubes override on_punch or something.

**Comment by C1ffisme** [comment]
@rubenwardy @sofar I would know... My mobs have caused errors abusing on_punch and it's code not checking for existant inventories.

**Comment by ShadowNinja** [comment]
:+1: Swords should wear too IMO.

**Comment by everamzah** [comment]
If punching inventory cubes doesn't change their HP, and currently swords don't wear when hitting a player, then this would seem to be consistent.

I too would worry that picking up dropped items with a sword would damage them.  Otherwise, this all comes as a big surprise to me, I just assumed swords wore when fighting all along.

**Comment by rubenwardy** [comment]
When you punch an item, I see it as picking it up rather than destroying it.

**Comment by sofar** [comment]
@everamzah I don't think this can be fixed in a mod. As a matter of fact, I'd like to see the code of a mod that has swords adding wear when you hit a mob. It can't be pretty - each mob definition would have to specially handle adding of wear.

**Comment by sofar** [comment]
Note that item entity blocks are immortal. If we'd have an ```on_wear()``` callback it would be trivial to not add wear for those.

**Comment by ExcaliburZero** [comment]
@sofar Here is how Blockmen's creature mod handles sword wear:

* Entity definition with sword wear on punch
    * https://github.com/BlockMen/cme/blob/a3bf9627a4bd933981e2273d252e9ef748f1a99c/creatures/functions.lua#L247-L283
* Add wear function
    * https://github.com/BlockMen/cme/blob/a3bf9627a4bd933981e2273d252e9ef748f1a99c/creatures/functions.lua#L206-L219

**Comment by sofar** [comment]
@ExcaliburZero thanks - it seem somewhat ridiculous that every mod has to add a handler to every mob that *gets hit* (not even the one that *hits*) to add wear to the *hitters* wielded item.

**Comment by rubenwardy** [comment]
That's the correct behaviour IMO, it is possible that you don't want to wear the item when punching.

**Comment by sofar** [comment]
@rubenwardy it's fine if people want to override the behavior - but that should not be the default, nor is it the right way to do it.  The wear should not be overridden by the entity object that receives the damage. It should be overridden by something in the tooldef, ideally.

That way, if someone wants to add some sort of "Infinity" modification to specific tools, only those tools would have a special ```on_wear``` callback attached to it, and everything else would function as it would by default, which is to wear down the item when it's used appropriately.

Just look at the current chain of events:

1. player left clicks
2. event "on_punch" triggers
3. on_punch code looks at pointed_thing, sees it's not immortal
4. determines that it's an object with on_punch() handler, calls it
5. punchee method has to look at puncher object
6. punchee method has to fetch puncher's wielded itemtack
7. punchee method has to add wear punchers wielded itemstack

[side exercise: imagine the sword had an itemstack metadata enchantment with +knockback. Where would the code to handle the knockback effect go?]

whereas ideally:

1. player hits entity
2. event "on_punch" triggers 
3. on_punch code looks at pointed_thing, sees it's not immortal
4. on_punch code fetches wielded item
5. checks if on_use() method exists for wielded item
6. adds wear otherwise
7. calls punchee:on_punched() method...

[similar side exercise: where would you put the code to handle the weapon's special properties here?]

So, maybe from a first glance you think both these methods have the same effect, but the difference is huge from a mod perspective:

- entity mods can stop looking at swords' code: they can just focus on the post-hit handling - e.g. fleeing, attacking back, etc. They shouldn't even have to handle their own incoming damage, ideally. They don't need to modify their velocity in case of a knockback, they don't need to calculate incoming damage, that's already done for them.

- sword mods can stop looking at entities' code: they don't need to modify every entity's registration table to make sure that items are wearing down appropriately. Instead, they modify the tool (sword) to determine wear level when the tool is used. The ```on_use``` callback already exists, and would be a perfectly logical callback to override default wear, like looking at metadata, armor values, player properties, etc. Similarly, they don't need to bother even knowing what it was that they hit. And hey, they can call itemstack:add_wear() to have the core engine add wear to the tool used where appropriate. If they DO need to do something different per entity, they should instead look at the entities wear modifiers data or metadata, and entities should expose them as proper API's instead.

Similarly, this is also the correct place to calculate damage. Damage modifiers (better swords) should be coded in the sword code, not in the stuff-that-gets-hit-by-swords code.

Building code like this will prevent code salad. Like the two links that @ExcaliburZero posted. Yeah, they had no choice to add that code - but it's still a workaround, and it doesn't scale. Come to think of it, they should have just overridden the ```on_use``` for swords instead.

I'm sure we can correct this behavior in a consistent and programmatically logical way that doesn't require odd callback handlers for wear and damage, but ones that are in the right place and call back the into the correct and logical mod code. Using the tooldef's ```on_use``` to or ```after_use``` is a good step forward (I need to verify this actually gets called when punching, and not when digging alone), but there should still be a default core addition that adds wear and damage to the target if those callbacks are missing.

**Comment by 0-afflatus** [comment]
:+1:
I don't say this very often but @est31 I think you're wrong on this issue.
@rubenwardy would this not help to write a trigger for combat awards? Otherwise the only usable callback is in the victim's on_punch IIRC, which is backwards.

**Comment by sofar** [comment]
Core should add a ```minetest.register_on_punchentity()``` callback handler.

**Comment by 0-afflatus** [comment]
> Core should add a minetest.register_on_punchentity() callback handler.

Agreed.

**Comment by est31** [comment]
Entities will still need to opt-out from this, like for example the dropped items.

**Comment by paramat** [comment]
Folding #1449 into this:
"When hitting an entity with a tool the wear of the tool does not get reduced. That is especially important for mobs. Also the damage groups don't define any uses. It can be done by mods, but it would be better engine side."

**Comment by paramat** [comment]
I support this too.

**Comment by Xerus2000** [comment]
I can't understand why this is still not implemented. It seems so trivial and basic.

**Comment by paramat** [comment]
#6804 PR needs some work and testing.

**Comment by sfan5** [comment]
was fixed by #8959
