### ISSUE TITLE
Memory access error sometimes if manip:update_map() isn't executed immediately

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3617]
ldk how to reproduce the crashes.
When l spawned a vulkan, minetest sometimes crashes telling "Speicherzugriffsfehler".
https://github.com/HybridDog/vulkane/blob/master/init.lua#L330
https://github.com/HybridDog/function_delayer/blob/master/init.lua
It says that the stones are set, then
after some seconds it says map updated and then it crashes.

**Comment by paramat** [comment]
You delay 'update_map' so perhaps something going wrong is not surprising?

**Comment by HybridDog** [comment]
It's not documented if it has to be executed directly after write_to_map.

**Comment by paramat** [comment]
I guess a delayed use was not expected.

**Comment by HybridDog** [comment]
Usually it doesn't crash when it's delayed, see the automatic rocket launcher.
Delaying it should be possible without causing problems
because it's very useful, see that rocket launcher: https://github.com/HybridDog/nuke/blob/master/init.lua#L371
