### ISSUE TITLE
minetest.transforming_liquid_add(pos) is not working?

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3621]
Looks like minetest.transforming_liquid_add(pos) is not working for me, tried it with code below, paramat also mentioned problems with it iirc. Tested on git 52eea79 under win7 and very recent MTG.

```lua
--
-- Water and lava activation
--

minetest.register_abm({
    nodenames = {"default:water_flowing"},
    neighbors = {"air"},
    interval = 15,
    chance = 128,
    catch_up = false,
    action = function(pos, node)
	local above = {x = pos.x, y = pos.y + 1, z = pos.z}
	local below = {x = pos.x, y = pos.y - 1, z = pos.z}
	local name_above = minetest.get_node(above).name
	local name_below = minetest.get_node(below).name
	local nodedef_above = minetest.registered_nodes[name_above]
	local nodedef_below = minetest.registered_nodes[name_below]
	if nodedef_above and nodedef_below and (nodedef_below.liquidtype == "none" or nodedef_above.liquidtype == "none") then
	        minetest.transforming_liquid_add(pos)
		print("activ: "..pos.x..", "..pos.y..", "..pos.z)
		print("above: "..name_above..", "..above.x..", "..above.y..", "..above.z)
		print("below: "..name_below..", "..below.x..", "..below.y..", "..below.z)
		print("---")
	end
    end
})
```

**Comment by paramat** [comment]
It might be because stuck liquid has reached a steady state where it no longer updates due to it's param2 value, so adding it to the queue makes no change. We may have to actually reset param2 to get stuck liquids flowing again.

**Comment by paramat** [comment]
To early to say this is broken. It's possible your ABM just takes too long to randomly select a flowing node a the bottom of a column, you could try: interval = 16, chance = 1, obviously a large load on the game but you'll find out if this method actually works or not.

To check 'liquid add' is working you could write a mod that places a water source on the ground using 'set node' and then adds it to the liquid queue.

**Comment by everamzah** [comment]
Does 'air' have liquidtype = "none" by default, or is it actually the nil.

**Comment by paramat** [comment]
I expect air is liquidtype none.

**Comment by everamzah** [comment]
While I'm quite certain you would know better than I, the liquidtype property isn't defined in air's definition:
https://github.com/minetest/minetest/blob/master/builtin/game/register.lua#L281

I took this screenshot, which shows not this "liquidtype" property, so that's why I was asking if it were nil.
![screenshot from 2016-01-30 07 07 12](https://cloud.githubusercontent.com/assets/1761623/12695559/7d52078c-c720-11e5-8f5e-3539f38d433a.png)

**Comment by paramat** [comment]
Good point, perhaps it could be nil. but then liquidtype = none is used in the core code on many nodes that don't have a liquidtype definition.

**Comment by Fixer-007** [comment]
>It's possible your ABM just takes too long to randomly select a flowing node a the bottom of a column

I've tried waiting for a very long time

**Comment by everamzah** [comment]
Did you try `if nodedef_above and nodedef_below and not (nodedef_below.liquidtype or nodedef_above.liquidtype) then`?  I have no idea if that's right, of if it would be right even if it worked.

**Comment by paramat** [comment]
Nevermind that stuck-water ABM that's mixing issues, just test like this:
> To check 'liquid add' is working you could write a mod that places a water source on the ground using 'set node' and then adds it to the liquid queue.

**Comment by Fixer-007** [comment]
>To check 'liquid add' is working you could write a mod that places a water source on the ground using 'set node' and then adds it to the liquid queue.

minetest.set_node(pos, {name="default:water_source"})  activate the flow without any help :}

**Comment by paramat** [comment]
Aha, maybe i was thinking of placing it using a voxelmanip, that doesn't add it to the queue.

**Comment by Fixer-007** [comment]
btw, voxelmanip has update_liquids() method, I wonder if that can help? Using it is beyond my coding expertise (which is close to none).

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_env.cpp#L946
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_vmanip.cpp#L166
https://github.com/minetest/minetest/blob/master/src/mapgen.cpp#L203
https://github.com/minetest/minetest/blob/master/src/map.cpp#L1609

**Comment by paramat** [comment]
Anyway, on topic, try placing a water source using the non-mapgen-object voxelmanip (without using 'update liquids'), it should not flow, then try minetest.transforming_liquid_add(pos) on it.

**Comment by paramat** [comment]
@Fixer-007 ^

**Comment by Fixer-007** [comment]
@tenplus1 wrote interesting function to test it:
```
minetest.register_craftitem(":test:axe", {
	description = "Test Axe",
	inventory_image = "default_tool_steelaxe.png",
	liquids_pointable = true,

	on_use = function(itemstack, user, pointed_thing)
		if not pointed_thing or pointed_thing.type ~= "node" then return end
		local pos = pointed_thing.under

-- START

		pos.y = pos.y + 2

		minetest.place_schematic(
			pos, {
			-- place air schem to fix lighting and air node for update
				size = {x = 1, y = 1, z = 1},
				data = {{name = "default:water_source", param1 = 255}}
			}, "", {}, true)



		minetest.transforming_liquid_add(pos)
-- END

	end,

})
```

It created a static water source in air, after uncommenting transform function water starts to flow.
So bug can be probably closed, but I found something interesting with this function that can interest you:
Try this function with water_flowing and without comment transforming_liquid part, place near some trees, you will notice this:
![2016-04-03 17_13_58-minetest opengl 4 5 13416](https://cloud.githubusercontent.com/assets/16494741/14232856/d900687c-f9bf-11e5-907b-bb9cf6b02106.png)
![2016-04-03 17_14_26-minetest opengl 4 5 13416](https://cloud.githubusercontent.com/assets/16494741/14232862/e1fcfecc-f9bf-11e5-9874-2f9372054380.png)

**Comment by paramat** [comment]
Placing a schematic uses 'update lighting' which is a more complex lighting update than that used in mapgen.
Thanks for this test.
