### ISSUE TITLE
is this project GAME-OVER?

### ISSUE THREAD

**Issue by fujita-nozomi** [minetest/minetest#3627]
i seeing minetest website saying:"0.4.13 released (August 20th 2015)" 
oh come on It's 2016 now There is no any upgrade?
I have great hope for this game...

> _Because C++ it's faster than JAVA_

and now... just Like a stone thrown into the water... :-(

> _hey take it easy
i've gotten a [ton] of work done today
a skele-[ton]_

> _＊The drums and cymbals sound＊_

**Comment by lisacvuk** [comment]
NO. Minetest is far from dead. If you are doing daily, unstable updates, you'll see that more features are added every day.

**Comment by rubenwardy** [comment]
It's been 4 months - we usually do a stable release every 5/6 months, but it depends.

**Comment by est31** [comment]
Nobody has made any promise to release or not release something, and multiple core devs have announced a pause from minetest (I am at a pause technically as well, keeping my involvement constrained). I am closing this now, I don't see any value in keeping it open.

**Comment by C1ffisme** [comment]
If you need proof about how much stuff is happening in minetest, just 'watch' the minetest and minetest_game repositories. Not that I'd recommend it, although I personally have done that.
