### ISSUE TITLE
No error message when trying to revoke privilege from admin or singleplayer

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3632]
I know the server admin (specified in “name” config variable) is a special player in the server who has some irrevokable privileges.
However, if someone with the “privs” privilege tries to revoke such a privilege from the admin, there is no error message, it just displays the unchanged list of privileges.

So if someone tries `/revoke admin server`, an error message should be shown so the user knows at least what went wrong.

**Comment by est31** [comment]
IMO this is a bug no enhancement.

**Comment by Splizard** [comment]
Something along the lines of this would probably work!
[0001-Fix-3632.patch.txt](https://github.com/minetest/minetest/files/115120/0001-Fix-3632.patch.txt)

**Comment by est31** [comment]
There are some minor issues with the patch, can you make a pull request? Then commenting on it is easier.

**Comment by Splizard** [comment]
Alright I shall spin up a pull request! I am in a issue fixing mood :)

**Comment by Splizard** [comment]
Pull request #3642

**Comment by paramat** [comment]
#6397 delayed, maybe done later.
