### ISSUE TITLE
Add server command to get the name of the server admin

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3633]
I want to have a new server command called “admin” and I want to have it in builtin.
Everyone can enter it and the server will respond with a message saying who's the admin on this server.

I guess this can be a simple lookup of the “name” config variable, right?

Open questions:
* What to do if “name” is empty? Is this even possible?
* What to do in singleplayer?

**Comment by tenplus1** [comment]
The '/admin' command can easily scroll through connected players, check for 'server' privelage and return a list of names, this would include singleplayer if playing on your own.

**Comment by Wuzzy2** [comment]
You don't understand. The thing about being “admin” is, there is no privilege called “admin”. I don't talk about privileges here. Yes, there's the “server” privilege, but I don't mean this. It is a bit confusing in Minetest.

With “admin” I mean the player set in the “name” config variable. This variable is a bit weird, it both sets the player name when you connect to servers but also makes this player an admin if he/she/it is connected to your server. This “admin” player gets some default privileges which can not be revoked. There are the admin powers I am talking about.

And as far I know, there can only be one such admin.

**Comment by tenplus1** [comment]
-1 ... Typically players will ask who is admin and regulars are quite happy to give a name...  Your method seems to over-complicate this process.

**Comment by Wuzzy2** [comment]
Jeez, my “method” just involves typing in “/admin”, how is this over-complicated?
Also, the admin may not be always there and sometimes you may be out of luck when there is currently nobody around to help you. So this is not reliable.
The admin command, however would be reliable.

**Comment by rubenwardy** [comment]
The owner name is already stored in the `name` setting, it wouldn't need any configuration. However, there may be more than one *admin*: that name is only the owner.

[Report](https://forum.minetest.net/viewtopic.php?t=13752) shows the names of the online moderators when sending a report. I think that would be a nice command for players to expect to exist. Although it has it's disadvantages - young players tend to abuse it by complaining about silly things.

**Comment by LazyJ** [comment]
The "name" listed in minetest.conf may never be around; RedCrab for example.

> rubenwardy said:
> "Although it has its disadvantages - young players tend to abuse it by complaining about silly things."

Aye, they do, with or without the Reports mod. For that reason, announcing who the staff are can make staff no longer wish to play on the server. Staff have earned or have been granted higher privs to deal with problems, ***real*** problems; not to be personal babysitters and entertainers. Staff log in to play too, just like everyone else.

Another hazard of announcing who the staff are is that it tips off the troublemakers. Some troublemakers refrain if they don't know who, among the logged in players, is staff. Other troublemakers grief or cause problems without realizing that the nearby player has the ability to ban them.

Sure, player's usually use the "privs" command to check the other players' privs but there are modifications that disable this and were done specifically to mask who the staff are so as not to tip off troublemakers or whiny, high maintenance players craving constant personal attention.

**Comment by tenplus1** [comment]
Good point, I know that on Xanadu as soon as certain players know you have special privs they beg items and teleport and set time to day etc. etc.

**Comment by rubenwardy** [comment]
I tend to play with a different nickname.

**Comment by LeMagnesium** [comment]
In case there is nothing more to add, [here](http://zerobin.qbuissondebon.info/?4dafd9e078d234ab#tVS+1A2HPt8S9hio19dCoPgAge+l4QnOwdSoP5RbFYg=) is a basic `/admin` command I coded that just returns either the value of the `name` configuration key or a message if, for some reason, that value doesn't exist.

```lua
minetest.register_chatcommand("admin", {
	privs = {shout = true},
	description = "Show the name of the server owner",
	func = function(name)
		return true, (minetest.setting_get("name") or "Couldn't determine who") .. " is the owner of this server"
	end
})
```

**Comment by nerzhul** [comment]
PR was merged

**Comment by 0-afflatus** [comment]
> as soon as certain players know you have special privs they beg items and teleport and set time to day etc. etc.

Sure, I've been on a big learning curve with this. The answer is to consistently say 'no' to all such requests. It does help a lot to have in-game methods for earning privs (where appropriate) and teleportation.
