### ISSUE TITLE
Feature suggestion: spawn scatter

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3634]
I need to work on findSpawnPos soon to make it cope with new mapgens.
I have an idea for a 'spawn_scatter' option setting that will scatter spawns over the 2000x2000 spawn area so that players must travel to find each other and have the option to be all elusive and mysterious.
It's simple to implement in the code.
Would be good for 'Battle Royale' servers and PVP, adds interesting new possibilities to servers and player interaction.
I'm opening this issue for any feedback or objections before i start work on this.

**Comment by est31** [comment]
Can't this be somehow done by a mod? And if not, can't we add an API that allows mods to do this? That's better than saying only 2000x2000 area is okay.

**Comment by rubenwardy** [comment]
The capture the flag server does this, but on a much smaller area (20x20x20).
The code is here: https://github.com/rubenwardy/capturetheflag/blob/master/mods/ctf_team_base/init.lua#L1-L36

**Comment by paramat** [comment]
Erm, i think only core code can do this because to spawn a player at ground level before an area has generated the 'getGroundLevelAtPoint()' function in the mapgen cpp file has to be called. The only way to do that in lua is to reproduce the entire mapgen code in lua.
I guess there could possibly be another setting for spawn area size, that would also be useful for conventional spawning to specify how large an area is searched for a spawn point. For example a large scale mapgen with ooeans 1000s of nodes across would often make the current spawn search fail resulting in a burial or drowning at 0,0,0.
