### ISSUE TITLE
Make nodeupdate(pos) and nodeupdate_single(pos) part of the API

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3639]
Just a reminder for myself or whoever.
Code is here https://github.com/minetest/minetest/blob/master/builtin/game/falling.lua#L155
Some possibly related cpp_api code is here https://github.com/minetest/minetest/blob/master/src/script/cpp_api/s_node.cpp#L251

**Comment by Splizard** [comment]
[0001-Improve-nodeupdate-documentation.patch.txt](https://github.com/minetest/minetest/files/115110/0001-Improve-nodeupdate-documentation.patch.txt)

Here is a possible start :)

**Comment by est31** [comment]
Lol, the cpp_api code you linked to isn't even used. git blame says it originated from commit 3aedfac9, which is now (mostly?) reverted. So I guess its probably okay to remove the cpp code.

**Comment by est31** [comment]
@Splizard I guess @paramat  wants it documented in lua_api.txt.

**Comment by Splizard** [comment]
[0001-Lua_api-doc-for-nodeupdate.patch.txt](https://github.com/minetest/minetest/files/115125/0001-Lua_api-doc-for-nodeupdate.patch.txt)
Something like that, I'm not sure where it would go in the file but searching for falling or nodeupdate will let you find it.

**Comment by est31** [comment]
@paramat probably the function should be inside the minetest namespace, if we want to officially support it. Probably the authors just forgot adding the "local". idk, is a lot of code relying on it atm, or can we simply rename/move it?

**Comment by Splizard** [comment]
@est just my opinion as I know I have used this function in my snow mod in the past, but I do agree it should be in the minetest namespace

**Comment by paramat** [comment]
> probably the function should be inside the minetest namespace

I agree, mods will need updating but that shouldn't stop us.
It's used in falling.lua and also in the leafdecay ABM, maybe a few other places.

**Comment by PilzAdam** [comment]
The question is whether we need to actually document this. This is mostly a helper function for falling nodes; is there any benefit from telling mods about this?

**Comment by red-001** [comment]
@PilzAdam minetest game uses it so, I think it's fair to say other subgames or mods could have a use for it too.

**Comment by red-001** [comment]
@paramat  It is used in the fire and default mods in minetest game.

**Comment by paramat** [comment]
One use i like is to have an ABM that occasionally updates any hanging unstable nodes, mapgen tends to create overhanging sand and gravel.

**Comment by est31** [comment]
I like to have overhanging gravel in mines. It adds a nice component to the game, if you mine blindly, and then lots of gravel falls down and you have to dig through it to get out.

**Comment by RealBadAngel** [comment]
it also updates hanging nodes (and causing them to fall)

**Comment by 0-afflatus** [comment]
It's used in a few places. I nearly removed it when searching for undeclared globals, so it should be in minetest namespace and documented. I can guess what it does, but it would be nice to know for sure.

**Comment by paramat** [comment]
Closing as is a helper function.

**Comment by est31** [comment]
Since when is that a valid closing reason? You've pointed out a valid issue, and it is not fixed yet.

**Comment by sofar** [comment]
I just added:

http://dev.minetest.net/nodeupdate

**Comment by est31** [comment]
If we make it official it should get a better name. `nodeupdate` is far too generic.

**Comment by paramat** [comment]
Well, it is just a helper function, and doesn't update fully, just in terms of falling nodes.
If others want to document it and make it an API then that's ok.

**Comment by paramat** [comment]
Sorry for the close.

**Comment by paramat** [comment]
#4589 is merged, but keeping this open to address making these functions official API and moving to minetest namespace.

**Comment by paramat** [comment]
MTGame devs agree on this, it should be done after https://github.com/minetest/minetest_game/pull/1308 is merged.

**Comment by Wuzzy2** [comment]
Info: https://github.com/minetest/minetest_game/pull/1308 is merged. Does this mean that the functions can go to `minetest` now?

**Comment by paramat** [comment]
Yeah i intend to do this now.

**Comment by paramat** [comment]
Est31 has done this now.

**Comment by est31** [comment]
commit link for reference: 649448a2a91fbf3e944b2f2e739f4e2292af1df0
