### ISSUE TITLE
Don't cut of the desert-stone at hight 0

### ISSUE THREAD

**Issue by CasimirKaPazi** [minetest/minetest#364]
Above 0 it's desert-stone, below it's normal stone.
This should be smoother, probably with perlin-noise. Just like the edges between desert and grass.

**Comment by paramat** [comment]
In mgv5 and mgv7 biome stone will generate down to y = -32, i could make mgv6 do this too for consistency. I'm not sure a varying level is worth the extra processing, you would only notice the transition when passing through caves so the flat cutoff is not so noticeable at y = -32.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/pull/2504
