### ISSUE TITLE
Deco schematic doesn't check for non-walkable node above placement pos

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3640]
![vsrqawq](https://cloud.githubusercontent.com/assets/3686677/12767557/c3438a70-ca01-11e5-8e51-7967c8377579.png)

Reminder for myself probably.
Now noticeable due to having 2 tree types in this biome.
Decoration placement uses the mapgen heightmap, if the heightmap wasn't present it uses 'findGroundLevel' or 'findLiquidSurface', these scan down a column to find the first walkable node, or the first liquid node not under a walkable node. So if we fix this we must simulate these functions by checking for a non-walkable node above the placement pos.

**Comment by C1ffisme** [comment]
Yes.

Please.

This would really help with people who make things like pre-generated ruins, etc.

**Comment by paramat** [comment]
Input is appreciated as i'm undecided. Keep in mind this only checks the node above the placement position, so is only of use for symmetric tree schematics with central trunks, or schematics that are single columns of nodes, like small cacti.

**Comment by Fixer-007** [comment]
This bug occured more then once for me.

**Comment by paramat** [comment]
Now fixed by re-adding root nodes.
