### ISSUE TITLE
Fix for disappearing-world problem

### ISSUE THREAD

**Issue by OldCoder** [minetest/minetest#3660]
A few weeks ago, I reported an interesting problem in the IRC dev channel. The issue has now been identified, with est31's assistance, and a simple fix has been submitted as a pull request.

The problem was that traveling more than 23212.4 node units away from the origin along any axis would cause the screen to go blank except for mobs. If different compilers and worlds were tested, the cutoff point varied slightly, but it was consistent down to the 0.1 step for any given configuration.

The reason for the problem turned out to be that signed 16-bit values were going negative due to 16-bit overflows. The overflows occurred because viewing_range_nodes_min was set higher than Minetest's camera code was designed to support.

I've discussed the issue with est31 and paramat and have submitted a pull request that corrects the problem. The pull request is located at the following link:

[https://github.com/minetest/minetest/pull/3659](https://github.com/minetest/minetest/pull/3659)

**Comment by paramat** [comment]
Fixing PR #3724

**Comment by paramat** [comment]
Merged 997be666e37e9494bb92a50521b4b749156a609c
