### ISSUE TITLE
Android: Translate Russian letters into English

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3663]
A couple of days ago, I added in the Russian transliteration MultiCraft messages. I write "Привет"and get "Privet".
It is very easy to add support for other Cyrillic letters, while I added all the letters of the Russian alphabet.
It works very well, I can write in chat and create worlds in Russian, and the Java script will convert my Russian letters into English. (This is java part, build/android/src).
It is very convenient to the servers. But it's proprietary code. If you want, I'll give it Minetest, while support for Russian letters completely broken :(

**Comment by MuhdNurHidayat** [comment]
^ that's not minetest forum, minetest uses `minetest.net` and not `minetest.org`

**Comment by codexp** [comment]
@MuhdNurHidayat thank you!

**Comment by paramat** [comment]
If it's proprietary code we can't use it.
Is this issue requesting this is done in MT or just to offer code?

**Comment by MoNTE48** [comment]
@paramat "If you want, I'll give it Minetest" -> i can create PR with LGPLv2.1+
