### ISSUE TITLE
Instant resurrection at same location bug

### ISSUE THREAD

**Issue by Darcidride** [minetest/minetest#3664]
Linked to : https://github.com/MinetestForFun/server-minetestforfun/issues/161

Many players use bug with the resurrection formspec and click very fast on the **resurrect** button to resurrect instantly where they was dead before, it's maybe a core use bug BUT, maybe we can reduce its impact :
- Add a timer to the resurrect formspec to be appear ?
- Remove the formspec and force the player to wait 5/10sec before an automatic resurrection ?
- Any other ideas ?

Thank you in advance,

**Comment by rubenwardy** [comment]
Would be nice to make the respawn time customisable by mods / subgames.

**Comment by Fixer-007** [comment]
Sometimes I can take my bones while respawning, needs some luck.

**Comment by C1ffisme** [comment]
The player shouldn't have to wait too long, but it would be a nice feature to have players wait a while before appearing again, except that on "anarchy" servers, or other servers where you die 5 times a minute, this would get pretty annoying.

So, basically, :+1: if this is customizable.

**Comment by 4aiman** [comment]
Why not try to revoke interact while player is dead?

**Comment by paramat** [comment]
We had some changes to the death formspec recently, still occuring?

**Comment by erlehmann** [comment]
This sounds like an interesting glitch. How to test this?

**Comment by erlehmann** [comment]
@sfan5 I have reports from players who managed to resurrect at the spot where they died this year, so I would assume the bug still exists in some form.

**Comment by sfan5** [comment]
This bug sounds highly game specific so this should be closed anyway unless someone can reproduce it in devtest.

**Comment by erlehmann** [comment]
@sfan5 so this bug is more about a game using the API wrong, I guess?
