### ISSUE TITLE
Player is not drowning when damage is on

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3665]
To reproduce easily: go on "Just Test" (0.4.12) server, go underwater, you will not drown here. 
I've managed to reproduce it on 0.4.13 after many tries, but I'm still not sure if it appears on 0.4.13-dev.
You can start drowning after eating an apple or taking damage.

MT git and MTG from git (8 jan 16 or later)
Confirmed by Obani, everamzah

Another report here: https://github.com/minetest/minetest/issues/3901

**Comment by paramat** [comment]
A while back we had a long-term problem with damage happening when it was disabled, could be related.

**Comment by Fixer-007** [comment]
Any reports about this in 0.4.14 or -dev?

**Comment by Fixer-007** [comment]
Will reopen if I see this again.
