### ISSUE TITLE
util/buildbot bug or bad doc?

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3666]
After building, I lack the 4 libraries. 2 I found in /usr, but still do not have 2 in my Linux PC.
Perhaps searching libraries can be added to .sh, as well as complement the documentation?

**Comment by paramat** [comment]
Is this problem in your fork Multicraft? If so is this problem reproducable in Minetest?

**Comment by MoNTE48** [comment]
It's starting to annoy me :)
When you have the car stop working lamp, definitely go to the people who sewed seat.
No, it Minetest error. You do not even have checked the assembly and does not read the text!

**Comment by sfan5** [comment]
You need to be more specific.

Which libraries are missing? Did you build 32-bit or 64-bit? Which ones did you find in <code>/usr</code>?

**Comment by MoNTE48** [comment]
Please, add in doc this depend for mingw build:
udo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install g++-4.9 mingw-w64

**Comment by paramat** [comment]
You mean it's a Minetest error occuring in your fork.

**Comment by MoNTE48** [comment]
@paramat it is an error contained in Minetest and all Minetest forks.

**Comment by MoNTE48** [comment]
@sfan5 and pls add in doc location libgcc_s_seh-1.dll and libstdc++-6.dll. Thank's
When I was building for the first time, find those files were hell for me

**Comment by paramat** [comment]
Currently your Citroen has broken down and you're going to the Renault garage and saying 'my Renault has broken down'.

> it is an error contained in Minetest and all Minetest forks.

Have you reproduced the bug in Minetest? Or is it occuring in your fork of the engine Multicraft and you are assuming it also affects Minetest? You may be correct, but you have to be clear from the start.

**Comment by MoNTE48** [comment]
@paramat, tell me, how could I offend you?
Or you do not understand in the assembly MinGW (then what are you doing in this issue?), Or you have decided to mock me.

**Comment by MoNTE48** [comment]
I will explain if you have not got it. In order to get a working build MinGW I have found in my Linux OS and copy 2 lib.so
However Minetest dev wiki
http://dev.minetest.net/Compiling_Minetest
nothing is said about it and about what packages I had installed on my OS. I had to look in Google answer these questions for some time. This makes the problem of Windows version build.

**Comment by paramat** [comment]
Ok thanks and sorry i misunderstood the issue.

**Comment by Fixer-007** [comment]
Yes, there should be info about dependencies (unzip,7zip-full,mingw*,git, etc) and I need to copy to /bin libgcc_s_seh-1.dll and libstdc++-6.dll, will be nice if CMAKE does this instead of me.
