### ISSUE TITLE
Wield images are set as inventory images since 6cd2b3b

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3668]
Cc: @est31 

A regression since https://github.com/minetest/minetest/commit/6cd2b3b445bf558fda1e5a7908adef8e3a45449a : `wield_image` is used as `inventory_image`.

![capture d ecran de 2016-02-07 21-52-38](https://cloud.githubusercontent.com/assets/7883281/12875243/13444f40-cde6-11e5-82ff-93131c245f35.png)

**Comment by est31** [comment]
Thanks for noticing. @RealBadAngel you want to fix?

**Comment by RealBadAngel** [comment]
@est31, sure

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/commit/38e712260046f159aa201259569054bdf9793b7f
