### ISSUE TITLE
Timeout reached on fetching serverlist

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3669]
Cc: @est31 

The following error occurs quite frequently and since recently when : 
- Trying to load the serverlist on the menu.
- Loading a singleplayer world — with a 1-2s lock up before throwing the error.

```
ERROR[AsyncWorker-0]: servers.minetest.net/list?proto_version_min=13&proto_version_max=27 not found (Timeout was reached) (response code 200)
```

**Comment by crabman77** [comment]
The server send very slow but curl timeout before.
Add in minestest.conf
> curl_timeout = 20000

You can check with "curl_timeout = 20", the error occurs immediately.
