### ISSUE TITLE
Inventory items are covering item_image_button labels since 6cd2b3b

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3672]
Cc: @RealBadAngel 
Cci: @est31 

Another regression caused by https://github.com/minetest/minetest/commit/6cd2b3b445bf558fda1e5a7908adef8e3a45449a : labels in [item_image_button](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1510) are covered by the inventory items.

Before 6cd2b3b : 
![screenshot_20160208_213324](https://cloud.githubusercontent.com/assets/7883281/12898347/848913ea-ceac-11e5-9b76-1ffe66de3228.png)

After 6cd2b3b : 
![screenshot_20160208_212954](https://cloud.githubusercontent.com/assets/7883281/12898323/6db369a4-ceac-11e5-9b8d-96057174934d.png)

**Comment by MoNTE48** [comment]
Confirm!

**Comment by RealBadAngel** [comment]
i see, will try to code the labels today

**Comment by RealBadAngel** [comment]
havent fixed the labels yet, but to display item stack count on buttons label is no longer needed.
Ive updated Unified Inventory to show properly item stacks
https://github.com/minetest-technic/unified_inventory/commit/b3c6c922861f9936cc03fae5cd6cabb9cacd9e27

**Comment by RealBadAngel** [comment]
ok, issue fixed
