### ISSUE TITLE
After set_attach attached model may disappear

### ISSUE THREAD

**Issue by amadin** [minetest/minetest#3681]
If first player was attached to the object by set_attach and second player connected (after attachment) then second player can't see first player but can see object, also second player can't see first player if first player was disappears from sight and then returns. So attached player model will displaying at 0,0,0 or at old object points only, and in both cases will not move with object.

In Lua it may be fix with this:

 ```
minetest.register_globalstep(function(dtime)
  for _, player in pairs(minetest.get_connected_players()) do
    local parent,bone,position,rotation = player:get_attach()
    if parent then
      player:set_attach(parent,bone,position,rotation)
    end
  end
end
```

0.4.13 stable

**Comment by 0-afflatus** [comment]
I have experienced this with kpg_horses mod. Boats don't seem to do it, but I will check.

**Comment by amadin** [comment]
You can test this on 93.170.76.99 with boats. Aso i recorded video - https://yadi.sk/i/WYCTuzIRp4Kv5

**Comment by Foghrye4** [comment]
I encounter same bug when i design my mod. Also happened when players is attached to freshly created object.
