### ISSUE TITLE
Get biome information by position

### ISSUE THREAD

**Issue by xeranas** [minetest/minetest#3685]
It would be useful to have ability get biome information by position from lua api. Currently this information is available only in the map generation callback. However what I like to known is what biome is at map position during game (e.g. from globalstep).

It would be much easier to apply appropriate weather, sound, mobs (and so on) which meets biome theme.

**Comment by paramat** [comment]
There is some C++ code for getBiomeAtPoint() which is currently unused, i might see if i can get this working with a new lua API.

**Comment by C1ffisme** [comment]
This would be wonderful...

**Comment by Gael-de-Sailly** [comment]
+1

Useful for compatibility between mods.
That's the end of moretrees' palm trees on the glacier!

**Comment by Ombridride** [comment]
+1 for compatibility between mods purpose

**Comment by 0-afflatus** [comment]
:+1:

**Comment by Gael-de-Sailly** [comment]
Would help a lot for minetest/minetest_game#999

**Comment by pyrollo** [comment]
IMO, it would more logical (but much much things to be broken I guess) to have "Climate" map from which Biomes and Weather are determined.

**Comment by paramat** [comment]
hmmmm/kwolekr is reworking mapgen and biome stuff architecture now, so this may come with it, or if not i'll add it later.

**Comment by MarkuBu** [comment]
I sign this. And there should be more informations for mods outside the mapgen like the hightmap, temperature, humidity and more. Mods must try to get all the informations by parsing nodes

**Comment by Fixer-007** [comment]
:+1:

**Comment by zorman2000** [comment]
Sorry for the bump, but what became of this?

**Comment by paramat** [comment]
hmmmm (on IRC) / kwolekr is intending to code this, best if you join IRC #minetest-dev channel and bug him about it.

**Comment by Griiimon** [comment]
This would be great help for coding realistic survival subgames/mods. My mods are currently on ice until this feature is added..

**Comment by paramat** [comment]
Kwolekr (hmmmm) isn't around recently so i might attempt this myself.

**Comment by Wuzzy2** [comment]
:+1:
This will be very important for getting weather right in MineClone 2. Otherwise, I see no way I can make sure snow doesn't fall in deserts etc.

**Comment by paramat** [comment]
It's coming, as always a matter of lack of dev time.

**Comment by Fixer-007** [comment]
Not just for weather, for spawning lots of different stuff, for temperature/thirst/spawning trees in proper places (acacia in snow biome in dreambuilder)

**Comment by tacotexmex** [comment]
Ambient sounds and music mods need this too.

**Comment by paramat** [comment]
#6455 merged.
