### ISSUE TITLE
Possible increase of camera offset distance?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3694]
@Ekdohibs 
For the sake of less processing.
See issues #228 #1093 and PR #1119
In this comment https://github.com/minetest/minetest/issues/1093#issuecomment-32012342 kahrl mentions it can happen subtly at 1000 nodes from world centre.
Perhaps 500 would be a good balance? 200 seems a little too small.

**Comment by est31** [comment]
Wow, an actual proposal by paramat that doesn't remove a feature.

**Comment by Ekdohibs** [comment]
@paramat I remember I tested it, and with some thin nodeboxes (1/16th node), when being far enough (20? 50?) nodes from the node, it was enough to see the nodebox flicker and disappear even a 400 nodes distance IIRC

**Comment by Ekdohibs** [comment]
However, it could be possible to make it a configurable (so it would go in advanced settings or something like that).

**Comment by RealBadAngel** [comment]
@Ekdohibs please do tests again, because that what you are talkin about was very similar to "texture tear issue" which i fixed already.
Problem was with not set depth buffer bits (it should be set to 24 by default, but wasnt on some configs).

**Comment by paramat** [comment]
Okay thanks, maybe i'll test as RBA suggests.

est31, chill out :P

**Comment by paramat** [comment]
I've just tested with camera offset step of 31000 and made snow nodeboxes 1/16th node thick, i only noticed them blinking at roughly 1000 nodes altitude.
With 1/32th node nodeboxes they start to get bad at 200 nodes distance, so the current setting may be necessary.
