### ISSUE TITLE
Build with irrlicht 1.7 broken

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3701]
@ShadowNinja noticed that the build with irrlicht 1.7 is broken. This is a regression of commit 5ca48a35a610aefd5c34d615cb49900f423b7aa6

A failing build log can be found at the [launchpad precise build](https://launchpadlibrarian.net/238352477/buildlog_ubuntu-precise-i386.minetest_201602130801-0~4563~ubuntu12.04.1_BUILDING.txt.gz).

**Comment by est31** [comment]
cc @RealBadAngel

**Comment by MoNTE48** [comment]
(I have never understood why maintain support for older versions. Hey, let's build Minetest for Windows 3.5. offtopic,i'm sorry)

**Comment by kaeza** [comment]
@MoNTE48 If supporting old versions is trivial, why not?
