### ISSUE TITLE
Liquids Rendering issue

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3702]
Liquids close to a player have a display problem. Liquids far away work:
![screenshot_20160213_211557](https://cloud.githubusercontent.com/assets/8872119/13029850/e076e562-d297-11e5-960b-2a110d6374dd.png)
![screenshot_20160213_211622](https://cloud.githubusercontent.com/assets/8872119/13029851/e2bfc1e0-d297-11e5-8e4c-9130ef672772.png)

**Comment by est31** [comment]
Seems to be a regression of one of the recent commits by @RealBadAngel .

**Comment by Gael-de-Sailly** [comment]
I've noticed that on water yesterday. It seems it only occurs with enabled shaders.

**Comment by paramat** [comment]
Hopefully fixed by 7ea40e45b1bf893aa693c179cbe8612ede86faee ?
