### ISSUE TITLE
get_us_time() causes all the afters to run at once when the pause ends (Singleplayer)

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#3706]

**Comment by est31** [comment]
Yeah the async worker threads aren't bound to the pause-stop yet.

**Comment by Fixer-007** [comment]
noticed that too

**Comment by rubenwardy** [comment]
minetest.after is powered by minetest.register_globalstep

**Comment by Rui914** [comment]
Is get_us_time() cause?

**Comment by est31** [comment]
Ahh, yeah. idk then, sb has to give it a closer look...

**Comment by sofar** [comment]
How do you pause singleplayer?

**Comment by rubenwardy** [comment]
Surely get_us_time() would cause all the afters to run at once when the pause ends, if the pause is sufficiently long?

**Comment by rubenwardy** [comment]
oops, sorry.

**Comment by Rui914** [comment]
```
minetest.register_globalstep(function()
	print(core.get_us_time())
end)
```
↓
```
...
2240005484
2240035813
2240066174 // paused here
2244087499
2244117957
2244148290
...
```

**Comment by sofar** [comment]
Look at src/game.cpp line 3199:

```
if (can_be_and_is_paused) {    // This is for a singleplayer server
    *dtime = 0;             // No time passes
}
```

async ticks are probably still just happening, trace this down in C++, not Lua. The code still needs to handle key presses, for instance. And leaves still wave as well.

**Comment by Rui914** [comment]
https://youtu.be/HPJuNyQ6wKg

**Comment by ShadowNinja** [comment]
@sofar: Server::step mainly just increments `m_step_dtime` by `dtime` and `Server::AsyncRunStep` decrements it.  If it goes below `0.001` `AsyncRunStep` returns early and the server step doesn't run.  This causes the server to completely freeze.
