### ISSUE TITLE
Meshgen slowdown regression with fancy leaves

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3714]
Commit 7ea40e45b1bf893aa693c179cbe8612ede86faee has caused large meshgen lags connected to fancy leaves.

**Comment by Fixer-007** [comment]
On AMD/ATI Radeon HD6870 on Windows 7 (sp1) can't reproduce this bug.

**Comment by RealBadAngel** [comment]
@est31 fancy leaves were just a way to see the issue in action, it was reserve() in meshbufffers

**Comment by est31** [comment]
Seems to be fixed by 08517244f7d19556f0449ff5d90f66e9ef079977
