### ISSUE TITLE
Minetest console (F10) should have DATE/TIME:

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3716]
Proposing to add date+time to the F10 in-game terminal, something like this:

```
2015-11-10 17:22:06 # *** Guest007 joined the game
2015-11-10 17:22:20 # Guest0242342: test
2015-11-10 17:22:30 # /grant singleplayer fly
2015-11-10 17:22:31 # singleplayer was grunted fly
2015-11-10 17:22:31 # /emergeblocks x y z
2015-11-11 20:34:59 # ... done emerging blocks
```

If it looks too big, date can be dropped.

Posted on forum about this earlier: https://forum.minetest.net/viewtopic.php?f=5&t=13559

**Comment by MoNTE48** [comment]
:+1:

**Comment by sofar** [comment]
Server console, absolutely. But that's already there.

I think you can omit the date for client side chat, time is plenty for chat logs (my IRC client is set to show time only, and that's perfectly reasonable IMHO).

**Comment by Fixer-007** [comment]
>Server console, absolutely. But that's already there.

I'm taking about in-game one (opened by F10), that one with a chat, yes. Dates in can be probably omitted, yes.

**Comment by VanessaE** [comment]
In my opinion, it needs to be configurable - whether they're shown and what they look like, because the time/date stamps shown in the example are simply too big.  In Hexchat, I have simply "[DD-MM HH:MM]" (i.e. "[02-27 17:24]") for brevity.

**Comment by Fixer-007** [comment]
This is already done via CSM mods (for example with this https://github.com/cheapie/chat6)
