### ISSUE TITLE
halo/selection box selects item behind open door mesh

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3719]
reproduce:
- Place a new-style 2-node high mesh door (minetest_game HEAD as of today) and open it.
- stand at same elevation as door placement
- point at door top half
- halo shows node behind door is selected

Interestingly, once you lower your viewpoint, the problem seems to go away.

Note crosshair location in screenshot:

![]
(http://i.imgur.com/Tk7vquI.png)

**Comment by paramat** [comment]
Does it highlight the door if the crosshair is on the door window crossbars?

**Comment by sofar** [comment]
No, it does highlight if you select either vertical edge, but nowhere in the middle. Transparency is irrelevant there.

**Comment by sofar** [comment]
@RealBadAngel is aware, and states that this is a very old bug that can also happen with the classic box selection.

**Comment by sofar** [comment]
BTW, this only happens if there's a block *right behind* the door mesh.

**Comment by sofar** [comment]
Also, it seems that the problem goes away if you target from further away.

**Comment by RealBadAngel** [comment]
the code responsible for this glitch:
https://github.com/minetest/minetest/blob/master/src/game.cpp#L334

**Comment by sofar** [comment]
Confirmed fixed properly, thanks.
