### ISSUE TITLE
Don't add infotext by default to builtin items

### ISSUE THREAD

**Issue by BlockMen** [minetest/minetest#3721]
Since 87291ea44a61614d5bd9efc0657926da3f867b5f builtin items have by default their description shown as infotext when pointed.

IMO this should be disabled by default, this is a game to explore things, not to describe and label everything that is existent in the world. Its like writing on every node their name...

**Comment by MoNTE48** [comment]
+0.5 Yes, it would be nice if it could be turned off. Although I like this feature.

**Comment by kilbith** [comment]
Perhaps it should be moved to the F5 debug infos as for nodes. But this detail is quite insignificant.

**Comment by est31** [comment]
I agree, the description should only been shown if it has been enabled by the server. And it should be default hidden.

**Comment by C1ffisme** [comment]
> Its like writing on every node their name...

So like, this node?

![mese_big](https://cloud.githubusercontent.com/assets/9893266/13083150/6595bbb2-d499-11e5-88e2-8d2b60fdd3af.png)

But yes, you have a valid point. We wouldn't want someone to instantly discover a new unknown ore and learn it's name just by looking at it.

I agree with @kilbith on this one. The F5 menu is probably the better spot. Although how to do this while still showing infotext for other entities, I don't know.

**Comment by sofar** [comment]
Opposed. 

You may as well remove texts like "Door owned by Player" texts and "Furnace 0% fuel" while you're at it, as they also provide spoilers about the content of nodes.

**Comment by C1ffisme** [comment]
@sofar I think this is just so that you don't see the name of every dropped node as soon as you point your crosshair at it. It can get slightly annoying after a while, if a drops mod is used.

**Comment by MoNTE48** [comment]
@C1ffisme , i use item_drop and i like this infotext. 
It is very convenient and does not bother me. When you you direct the mouse on the object in the inventory, you also see the prompt. This helps to servers with new modes that are unfamiliar to you.

**Comment by sofar** [comment]
This infotext is incredibly useful if many items drop in the same location.

I find the idea to force players to pick up items absolutely nonsense, if you want to force them to pick up items, then make the items disappear after a shorter period.

**Comment by BlockMen** [comment]
> You may as well remove texts like "Door owned by Player" texts and "Furnace 0% fuel" while you're at it, as they also provide spoilers about the content of nodes.

Excactly this. For what do you know its locked by xyz? Steel doors are locked, no matter by whom. Same goes for locked chests. And even more ridiculous: Chests. For what the hell are chests labeled?

In my personal Opinion the infotext "feature" should go at all, but since this is an engine and it might be usefull in some cases I'm fine with have this in general, but plz not everywhere...

**Comment by sofar** [comment]
@blockmen removing it would force every mod writer put up formspec messages with the wanted text, not a good alternative. Now mod writers have a choice.

**Comment by C1ffisme** [comment]
What about improving the infotext?

I would like it to be right above the hotbar, and not in the middle of space.

**Comment by BlockMen** [comment]
@sofar I said that i would prefer in general, not that i want/going to remove it...

**Comment by est31** [comment]
@sofar this discussion is only about the `builtin/game/item.lua` code, not about the general modding possibilities the commit by RBA added. I first too wondered about this.

**Comment by paramat** [comment]
More opinions?

**Comment by SmallJoker** [comment]
@paramat You removed this feature about 4 months after it was added: 643ac9d.
