### ISSUE TITLE
The speed of Minetest port

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3725]
Hello. I finished work on Android port optimization.
Now Minetest runs on the powerful Android device (Nexus 9, LG G4, Galaxy S6, Note 5) is almost as fast as on my PC (Microsoft Surface Pro 3).
Unfortunately, all of my changes LGPLv3. But I am ready to relicense them and give you guys!
It's not a lot of code, but it's a lot of hours of reading, googling and testing on a large number of devices. Yes, my desk is piled high with different tablets and phones (15+ pcs). I bought it just for testing and I did it.
Check it out https://play.google.com/store/apps/details?id=mobi.MultiCraft

**Comment by RealBadAngel** [comment]
Can we see that code?

**Comment by MoNTE48** [comment]
https://github.com/multicraftproject
And 1 commit not yet been published, I'm testing.

**Comment by MoNTE48** [comment]
@RealBadAngel I did some PR, but nobody is interested. Some interests was expressed, but no merge them.

**Comment by ShadowNinja** [comment]
Performance improvements would certainly be welcome, but they'll probably take a while to merge considering how much your fork has diverged from Minetest's code.

**Comment by nerzhul** [comment]
This is not an issue. If you want to share code instead of promoting your fork, please do a pull request. There is nothing for us to fix there. As you said your licence is not compatible.
Closed.
