### ISSUE TITLE
Auto-Update Minetest in Fedora 23

### ISSUE THREAD

**Issue by TJProgrammer** [minetest/minetest#3726]
Hello!
A question: why minetest doesn't update automaticaly to 0.4.13 version in fedora 23?
Thanks.

**Comment by asl97** [comment]
@TJProgrammer wrong place.

you should ask the people downstream (who maintain the repo) at https://bugzilla.redhat.com/

there is an bug report but no reply yet: https://bugzilla.redhat.com/show_bug.cgi?id=1295398

**Comment by TJProgrammer** [comment]
Thank you!
