### ISSUE TITLE
Biosphere mapgen

### ISSUE THREAD

**Issue by lugarius** [minetest/minetest#3727]
http://www.minecraftmods.com/biosphere-mod/
http://minecraft.gamepedia.com/Mods/Biosphere

A worldgen like the MC mod

**Comment by C1ffisme** [comment]
This can be done via mods.

**Comment by paramat** [comment]
Depends on whether a core mapgen dev is keen to do this, i'm not. I don't find biospheres particularly interesting. Also i'm not sure they have enough potential to be a core mapgen.

**Comment by Gael-de-Sailly** [comment]
We have much better to do than to copy Minecraft.

**Comment by RHRhino** [comment]
@Gael-de-Sailly Minecraft Mods not Minecraft itself :smile: 
@lugarius I already saw a mapgen mod for minetest in the forum which creates spheres - maybe you want to try this: https://forum.minetest.net/viewtopic.php?f=11&t=13618&hilit=sphere
The next time please ask in the forum first.
@paramat I think we already have many good core mapgens, we should try to focus on improving them instead of creating many fun mapgens - this should be done with mods. I think this issue is ready to be closed.

**Comment by Gael-de-Sailly** [comment]
I think making a biosphere mod would not be that difficult, and it could be fast for a Lua mapgen, because it will generate on a small part of the volume of the world.

**Comment by est31** [comment]
Removed an arrogant and childish link in the issue description.

**Comment by paramat** [comment]
Ew yes that link ..
A mod could possibly do this by modifying a core mapgen by replacing certain volumes of world with air, so it would be fairly fast.

**Comment by est31** [comment]
Well a proper biosphere mapgen is more than just removing some nodes, as every "unit" only contains one biome, and in the mapgens there are also transitions between biomes, so one unit can also contain only the transition zone for a biome.

**Comment by C1ffisme** [comment]
@paramat @est31 It's a fun idea for Minetest, and might be interesting, but I've known that the community sways towards a non-bloated engine and game. Whilst the other mapgens are meant to look good for modded worlds, this mapgen only has one usecase.

Plus, it's not that hard to create something like this by creating a singlenode world/flying into the air, and then using worldedit.

**Comment by est31** [comment]
Well, I quite like the idea. E.g. I would prefer biosphere maps over the stuff 3456 added.

**Comment by lugarius** [comment]
Thanks

**Comment by 0-afflatus** [comment]
I'm with @C1ffisme on this. I don't really see the need to have this in the engine.

**Comment by paramat** [comment]
It would be me who does this, and i'm not interested, although the concept is potentially good, so closing.

**Comment by est31** [comment]
What about contributors?

**Comment by kilbith** [comment]
You don't understand, he secretly believe that MT is his game...

**Comment by ObaniGemini** [comment]
I think this mapgen should not be implemented in-game. It's a mapgen for a very specific use, and would be done easily, as @Gael-de-Sailly said it, by a lua mapgen.
If we accept such a mapgen, then we would have to accept every other mapgens similar to planetoids, mg or others.

As @paramat said, the concept is good. But I don't think the engine is the place for such specific mapgens. I'm for closing this as it would make a better mod request than feature request.

Please @kilbith stop being mad with everyone. I understand @paramat 's acting, Minetest organization can be very slow on many occasions and it's not a bad innitiative when you want to be the first to act.
Cheers

**Comment by kilbith** [comment]
Obani, stop highlighting me please. You're not even a developer and thus insignificant for me.

**Comment by ObaniGemini** [comment]
If I'm not a developper, I'm some other thing(s). Stop talking like you're superman. Nobody is. Stop sarcasm. You're even more insignificant to me.
Flowers

**Comment by paramat** [comment]
Well we could ask @duane-r

**Comment by est31** [comment]
@paramat I don't think it is a goal of this project to have as many closed feature requests as possible.

**Comment by rubenwardy** [comment]
Feature requests could be put on the wiki, it just clutters up the issue tracker here.
Unless they're higher priority, such as client-side modding or colored text.

**Comment by C1ffisme** [comment]
@rubenwardy To be fair, I think I was the one who started these feature request issues. :fearful: 

Which wiki?

It might be worth putting a section in the minetest forums for suggestions, while some suggestions could be put here by minetest developers for major features. The only problem with that is the people who will post this suggestion:
```
i thnik we n33d som new blox to mk ths into fr33 Minecrfat!
- 3l3ctricity (red color)
- enchating
- (The list goes on and on, only talking about unoriginal features stolen from Minecraft, for the purpose of making Minetest into free Minecraft.)
```

**Comment by RHRhino** [comment]
@C1ffisme There are already sections for that:
[Feature Discussions](https://forum.minetest.net/viewforum.php?f=5) for new features for the engine 
and [mod ideas ](https://forum.minetest.net/viewtopic.php?f=47&t=2434)for new mods. Should be more than enough. :wink:

**Comment by C1ffisme** [comment]
@RHRhino Yes, we could use Feature Discussions, however this is more of a place to discuss features currently in the game, or features that are coming up into the game. If we had a forum to put suggestions, it might clear up some confusion.

(Of course, there is the fact that Minetest Game is trying not to be as bloated as most suggesters would make it, but I bet that some people could come up with a good suggestion sometimes.)

**Comment by est31** [comment]
@rubenwardy who decides what "higher priority" is? Either we track no feature requests via the issue tracker, or we track all of them (except those that clearly don't fit minetest).

**Comment by rubenwardy** [comment]
> @rubenwardy who decides what "higher priority" is? 

The core team does, and should be the ones to create them

**Comment by rubenwardy** [comment]
> If we had a forum to put suggestions, it might clear up some confusion.

We do have a forum to discuss features: https://forum.minetest.net/viewforum.php?f=5

**Comment by C1ffisme** [comment]
@rubenwardy I'm not sure you read... anything I just said.

`
Yes, we could use Feature Discussions, however this is more of a place to discuss features currently in the game, or features that are coming up into the game. If we had a forum to put suggestions, it might clear up some confusion.
`

**Comment by est31** [comment]
I think its important to discuss new features before they get implemented, not after. Its always demoting if your PR gets turned down because it implements an unwanted feature. Therefore I think that there should be more discussion about new features inside issues, because that's most close to the developers. The wiki and forums are I think bad places for discussing this.

**Comment by est31** [comment]
damn I should learn to press the right buttons :/

**Comment by paramat** [comment]
I think feature requests should stay here in issues, despite the problems.

**Comment by paramat** [comment]
See #3941

**Comment by paramat** [comment]
Duane is experimenting with a mod on the forum, so this can stay open for a while.

**Comment by duane-r** [comment]
I've got a [working mod](https://forum.minetest.net/viewtopic.php?f=9&t=14348) that does this sort of world, but it would be extremely impractical for a real mapgen. I can't see any advantage to porting it.

The alternative would be a switch in one of the regular mapgens that masks everything outside the bubbles, but you'd get schematic bleed-over, and it wouldn't be very pretty or practical. It would also have the disadvantage of being two-dimensional.

**Comment by paramat** [comment]
Okay closing then.
