### ISSUE TITLE
32bit builds tend to crash with "bad allocation error" in crowded areas (out of memory)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3731]
if walk around with big view range in a forests or other crowded places long enough with 32bit build, usually 30-60 min, game memory usage will grow up to 1.6 GB and crash giving bad allocation errors
This looks like out of memory error (32 bit memory limit).

You can avoid this problem in a different ways:
1) use 64bit OS and 64bit build of minetest (default download anyway) -- best option
2) lower client_mapblock_limit in minetest.conf;

This problem is for low-end users (possibly android ones too?), maybe there should be a way to autotune client_mapblock_limit if 32 bit system is low in memory (or mt.exe eats to much).

Originally posted here: https://forum.minetest.net/viewtopic.php?f=6&t=13585
There was a discussion on IRC about that with celeron55 in 2015, but I can't find it right now.

**Comment by paramat** [comment]
From the forum thread seems reproduced quite recently (well, 0.4.15).
