### ISSUE TITLE
Entered data in formspecs resets after update/resize

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3732]
As example: entering password in multiplayer login screen and resizing/maximizing window after that will reset your login password (so you will need to retype it again). It affects any entry fields, not just password one.

**Comment by RealBadAngel** [comment]
Not fixeable rather. Formspecs are regenerated all the time.

**Comment by paramat** [comment]
Is it indeed unfixable?

**Comment by Wuzzy2** [comment]
Well, this looks like another entry for the list of *100 Reasons Why Formspecs Suck (Reason 42 Will Make You Cry!)*.

I suggest to fix this problem with all other formspec problems when they are being redesigned.

**Comment by paramat** [comment]
This can be discussed in the formspec replacement thread.

**Comment by aerozoic** [comment]
link to formspec replacement thread plz?
:large_orange_diamond:

**Comment by SmallJoker** [comment]
@aerozoic It's already linked above the [Can't fix] tag. #6527
