### ISSUE TITLE
Lighting of slabs and full blocks is different

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3735]
I've noticed that whole block and slab block have different lightning on them, look at the screenshot (this problem is evident on default and custom slabs), whole blocks are closer, slabs are farther. Also, probably the same problem with stairs.

Screenshot of the issue: http://i.imgur.com/iy4myvR.png

**Comment by PilzAdam** [comment]
This looks similar to an old bug where lighting was applied before the nodes where rotated. @RealBadAngel can you look into this?

**Comment by RealBadAngel** [comment]
This is not a bug but our lighting system. slabs, stairs, all nodeboxes, plants, rails, meshnodes are using internal light of the node. solids blocks calculate that for all 6 faces. So, the effect is different for them.

**Comment by Fixer-007** [comment]
this is probably dupe of https://github.com/minetest/minetest/issues/104

**Comment by Fixer-007** [comment]
This issue was fixed \o/
