### ISSUE TITLE
Can't change screenshot path via GUI

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3750]
In the new settings GUI you can select your path for screenshots with a GUI. But every time i press Ok the UI elements disappear i i see only clouds and logo. If i press esc i see a bit of the settings UI, but it is unusable. (dev compiled from newest commit.)

![bildschirmfoto von 2016-02-20 06-43-48](https://cloud.githubusercontent.com/assets/1377943/13194740/513d2644-d79d-11e5-8920-a3d971794f13.png)

**Comment by PilzAdam** [comment]
I think it's a problem with the file dialog, see https://github.com/minetest/minetest/issues/1020#issuecomment-29562408
