### ISSUE TITLE
Better Mouse Lock

### ISSUE THREAD

**Issue by Lolums** [minetest/minetest#3756]
Instead of constantly changing the mouse's position to be in the center of the screen, Minetest should trap the mouse properly.

This is really important to me, since movement feels glitchy and keeps stopping due to the mouse.

**Comment by C1ffisme** [comment]
:+1:

Although, we would have to calculate the center of the screen every time you resized the window.

**Comment by Gael-de-Sailly** [comment]
I don't see what do you want to have. If the mouse is not constantly replaced at the center of the screen, it will reach the edges.

**Comment by C1ffisme** [comment]
@Gael-de-Sailly Not the center of the screen, but the minetest window. You can reproduce this if you select another window while playing minetest.

**Comment by rubenwardy** [comment]
He's saying that we should use the correct APIs to lock the mouse in the middle of the screen

**Comment by PilzAdam** [comment]
AFAIK this is done by Irrlicht.

> This is really important to me, since movement feels glitchy and keeps stopping due to the mouse.

This doesn't make any sense. No movement info of the mouse is lost.

**Comment by est31** [comment]
I had looked into this issue some time ago, and indeed, @PilzAdam is right, its done by irrlicht, not by us.

And as far as I know, there is no way, neither on windows nor on X or anywhere else, to properly trap the mouse as requested, and only receive relative events. Even Wayland only offers partial support for this, but at least they plan it. If we wanted to use this feature

To my knowledge all other games do the same, but please tell if you know something what I don't.

See also issue #1763 , its hugely related.

**Comment by est31** [comment]
Also we cant really fix this, as all the window management stuff is done by irrlicht, and irrlicht doesn't expose the X context, therefore upstream label. And, as I said above, even if we had the X context, we couldn't do anything with it to fix the bug.

**Comment by Lolums** [comment]
> This doesn't make any sense. No movement info of the mouse is lost.
The mouse moves away from the center a bit and is then constantly placed back into the center, which feels glitchy.

> Also we cant really fix this, as all the window management stuff is done by irrlicht, and irrlicht doesn't expose the X context, therefore upstream label. And, as I said above, even if we had the X context, we couldn't do anything with it to fix the bug.
I see. Thanks for looking into it anyway though.

**Comment by PilzAdam** [comment]
> >This doesn't make any sense. No movement info of the mouse is lost.
>
> The mouse moves away from the center a bit and is then constantly placed back into the center, which feels glitchy.

But the mouse cursor is hidden when it's "locked" to the window, isn't it?

**Comment by Gael-de-Sailly** [comment]
Ok I think I understand. The mouse cursor shouldn't be visible when you play, only when you have a menu (inventory or game menu). If it is, it's a bug, that probably depend on the OS. @Lolums, what system do you use?

**Comment by asl97** [comment]
@est31 @PilzAdam https://github.com/minetest/minetest/blob/master/src/game.cpp#L3098
if you meant that by 'its done by irrlicht' then ignore this comment.

**Comment by est31** [comment]
Yes, thats the most proper way to do mouse trapping, that irrlicht and Xorg allow. so the demand of the issue creator "Minetest should trap the mouse properly" can't really be met.

**Comment by Lolums** [comment]
@Gael-de-Sailly apologies for not replying earlier. This isn't the issue, as the mouse is always hidden but the movement feels jittery to me. I realise that you can't change it though, or not very easily anyway.

**Comment by Gael-de-Sailly** [comment]
Press `F8` for the cinematic mode (smoother movements). Is that what you want?
Or maybe your FPS rate is too low. Press `F5` to see detailed information. You can increase FPS by decreasing the viewing range (minus key).

**Comment by paramat** [comment]
@Lolums is this a low FPS issue?

**Comment by lightonflux** [comment]
@PilzAdam Well not if you hit #3507

**Comment by PilzAdam** [comment]
@lightonflux that is a different bug; if that bug is fixed, then there is really no problem with the current behavior.

**Comment by Lolums** [comment]
Yeah, bug #3507 is what I'm experiencing. The mouse is jiggly. My FPS is fine, it's 60.

**Comment by PilzAdam** [comment]
Ah, ok, closing as duplicate then.

**Comment by Lolums** [comment]
Just asking, how often do you update the mouse's position?
Do you do it right after the event is called or do you check for the position?
If it's the latter, that might be the issue.

**Comment by est31** [comment]
Its updated once per frame, see `Game::updateCameraOrientation` and `Game::updateCameraDirection` in src/game.cpp.
