### ISSUE TITLE
Remove 'new style water' and waving water.

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3759]
See discussion #3734
As both have problems, are embarassing and are unusable now we have water surface decorations.
RealBadAngel has plans for better water shaders.
PR for removing new style water #3760 
Removing waving water is more complex and involves #3616

**Comment by est31** [comment]
Removing waving water doesnt involve 3616 at all, from what I've seen.

**Comment by est31** [comment]
But I agree to have new style and waving water removed, and that that's a blocker, I don't think however that having better water shaders is a blocker though.

**Comment by paramat** [comment]
> Removing waving water doesnt involve 3616 at all

Yes that's what i said to RBA, i asked that the removal of waving water be seperate from 3616, so that we can continue to discuss 3616 and possible future water shaders later.

**Comment by PilzAdam** [comment]
I think that the shader effect is easily fixable.

IIRC there was already a patch (maybe it was even merged) that rendered the top-side of liquids if solid nodes are above it when new_style_water is enabled. This could be expanded to work with shaders, too (this is quite trivial).

The initial problem of #3734 only happens if new_style_water and the shader effect are enabled both at once, which of course wouldn't happen anymore if new_style_water is removed.

**Comment by cheapie** [comment]
So the proper action when a feature isn't just right is just to remove it now?

(besides, I'd think just implementing some way to wave the decorations too would be easier)

**Comment by 0-afflatus** [comment]
> So the proper action when a feature isn't just right is just to remove it now?

On some level, yes. You make this sound like it's a trivial decision - I liked new_style water and the waving effect, but there are so many problems associated with it that needed fixing. On the run-up to a release, it's much cleaner to remove broken features as that leaves a clean, stable base on which the feature could be properly re-implemented and / or the gaps left by its removal can be clearly seen.

Were it just the case that water-lilies and seaweed didn't move with the water then maybe.

**Comment by RealBadAngel** [comment]
about #3616, it cleans the  mess a bit, by removing hardcoded water shaders for default water, and letting mods define it.
so with it i can simply delete "water_surface_shader", fix the nodes one (remove waving there) and in the future when needed add specialized one for water of any kind

**Comment by paramat** [comment]
The issue with waving water is that it is perhaps not usable now we have water surface decorations. RBAs new approach, which i agree with, is to keep water surface fixed and use shaders to animate the surface texture.

**Comment by est31** [comment]
Note that I oppose waving water out of other reasons, decorations aren't really the reason for it (they can just as simply be disabled from mapgen with the same argumentation -- now as we have waving water we cant have decorations). After all water decorations are a game thing.

**Comment by paramat** [comment]
Removing milestone as new style water has been removed. Removing or fixing waving water doesn't seem particularly essential for release and may take some time.

**Comment by MirceaKitsune** [comment]
Please don't remove the waving water or leaves as a feature! Some of us really like them and are using them, we don't want them to go away. If there's a problem with them, that problem should be fixed. :-1: !

**Comment by paramat** [comment]
Closing.
