### ISSUE TITLE
Require minetest.request_http_api to be called from main scope

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3764]
Commit 31e0667a4a53a238d0321194b57b083bd74c0a5b has added HTTP support, but it is vulnerable to an attack similar to #3132 .

So we'd need a fix for HTTP, just like 4827ee1258ac9d68808ca4e2a9cb88bf49473e6b did for 3132.

**cc** @ShadowNinja @Jeija

**Comment by est31** [comment]
I'd also say its a blocker: its fairly easy to do and the underlying issue is quite bad.

**Comment by kaeza** [comment]
request_http_api should respect security setting, IMHO. I'm on mobile currently and reviewing is a PITA, so please correct me if it already does.

**Comment by Jeija** [comment]
@kaeza: No, it doesn't respect the `secure.enable_security` setting, the idea was that this way "mod authors won't need to change anything in their documentation when we default to security on" (https://github.com/minetest/minetest/pull/3729#discussion_r53354175).

I'm currently trying to work on a fix for this issue, but for some reason https://github.com/minetest/minetest/commit/4827ee1258ac9d68808ca4e2a9cb88bf49473e6b doesn't even work for me, it breaks `minetest.request_insecure_environment` completely. Currently investigating...

**Comment by est31** [comment]
@kaeza that's intentional.

**Comment by kaeza** [comment]
Fair enough.
