### ISSUE TITLE
Android:object_marker_red.png causes tile.cpp crash

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3768]
It was quite difficult to understand what the problem is. It turns out that because there is object_marker_red.png crash android port immediately after the launch of the world.
(For idiots who say that I only report bugs that you have fixed them for me for free: I am not using minimap and I do not care about this error. I just say this to let you know!)
```
ERROR[Main]: jni/../jni/src/client/tile.cpp:2d6: virtual void TextureSource::rebuildImagesAndTextures(): An engine assumption 'img->getDimension().Height == npot2(img->getDimension().Height)' failed.
```
for @est31 | @ShadowNinja

**Comment by ShadowNinja** [comment]
This means that `object_marker_red.png`'s height is Not a Power Of Two, which is necessary on Android to avoid glitches, and indeed it's 15x15.  The image simply has to be resized to 16x16.

**Comment by est31** [comment]
**cc** @RealBadAngel

**Comment by ShadowNinja** [comment]
b114fd87a95dbba147b5a659f12323fd47975ad6
