### ISSUE TITLE
Unable to turn off security from main menu.

### ISSUE THREAD

**Issue by kaeza** [minetest/minetest#3769]
Turning off mod security from the main menu crashes Minetest with the following error:

```
terminate called after throwing an instance of 'LuaError'
  what():  Runtime error from mod '' in callback handleMainMenuButtons(): Attempt to set secure setting.

stack traceback:
        [C]: in function 'setting_setbool'
        ...minetest\bin\..\builtin\mainmenu\dlg_settings_advanced.lua:605: in function 'handle_buttons'
        ...minetest\bin\..\builtin\fstk\ui.lua:148: in function 'handle_buttons'
        ...minetest\bin\..\builtin\fstk\ui.lua:192: in function <...minetest\bin\..\builtin\fstk\ui.lua:178>
```

So what is happening is `setting_set*` disallows editing of settings prefixed by `secure.` in any case. Main menu needs to use `setting_setbool` to toggle `secure.enable_security`, and this raises an error.

CC: @ShadowNinja

**Comment by ShadowNinja** [comment]
The issue is that only one version of the minetest API table is created -- there's no insecure version so setting these variables has to be banned even for builtin.

We'll have to somehow register the minetest API table twice -- once with security enabled and once with it disabled.

**Comment by rubenwardy** [comment]
The main menu minetest.* is different to the ingame minetest.*, as far as I know. And it's a different lua environment.

**Comment by ShadowNinja** [comment]
Actually nevermind, rubenwardy's right.  This should fix it: http://ix.io/oLE/diff
