### ISSUE TITLE
Can no longer jump upwardly on nodes.  Shaky movement on small collision boxes.

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#3773]
Since 60dc01dc258db842e229351b871d0989e3e7d62c I can't jump upward from node to node (hills, mineshafts).  Instead each node now takes two jumps to climb.

Also, walking on small collision boxes (such as stone paths or odd shaped nodeboxes really) makes for a bouncy view (bobbing?) or actual player movement that is shaken about.

**Comment by MoNTE48** [comment]
Same https://github.com/minetest/minetest/issues/3767 ?

**Comment by paramat** [comment]
Smooth comtinuous running up hills must be preserved.

**Comment by paramat** [comment]
Jumping up 45deg slopes is differernt now, there's a visual 'jump' and the player seems to 'teleport' to the node edges.
It's jerky and slower movement, the smooth and fast running up 45deg slopes is gone.
It's possible to jump 3 node gaps now, not sure if it was before.

**Comment by gregorycu** [comment]
I don't really have time at the moment to look at this. Maybe the offending
change should be rolled back as this is probably more of an issue than the
jumping bug?

**Comment by kilbith** [comment]
Blocker label please, this bug is really annoying. Try moving out from mesecons pressure plates for example.

Cc: @ShadowNinja

**Comment by paramat** [comment]
> Maybe the offending change should be rolled back

Yes.

**Comment by zhangjunphy** [comment]
Has anyone tried approaching a grassblock:slope from its left or right side? This will blank my game screen. Seems also related to https://github.com/minetest/minetest/commit/60dc01dc258db842e229351b871d0989e3e7d62c.

**Comment by kilbith** [comment]
Yes this commit is really awkward and should be reverted.

**Comment by zhangjunphy** [comment]
I believe the problem with node edge jumping is caused by the discrepancy of `COLL_ZERO` in `axisAlignedCollision()` and `d` in `collisionMoveSimple()`, both used as a margin when deciding whether two box overlap. 
https://github.com/minetest/minetest/pull/3796 should solve the above problem.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/commit/60dc01dc258db842e229351b871d0989e3e7d62c will be reverted soon.

**Comment by nerzhul** [comment]
Reverted
