### ISSUE TITLE
Green model/texture bug

### ISSUE THREAD

**Issue by Ombridride** [minetest/minetest#3780]
A player, noticed this Green model/texture bug on the chicken white model/texture, but nobody else can see this glitched green texture...

![capture du 2016-01-04 16 05 06](https://cloud.githubusercontent.com/assets/12512762/12092414/432e5fe2-b2fd-11e5-9ae8-4cce007553a3.png)

Linked to this issue https://github.com/MinetestForFun/server-minetestforfun/issues/360

**Comment by RealBadAngel** [comment]
Its not glitched. Its bumpmapped by autogen. You should provide rather own normal texture (can be flat one to effectively disable normal mapping for that model)

**Comment by 0-afflatus** [comment]
This is really an issue for whatever mobs mod this comes from. IIRC the chicken texture requires some ridiculous workaround to get the textures to wrap properly. I'm sure offers of better textures would be well received.

**Comment by NathanSalapat** [comment]
Looks like a UV layout problem to me, not an engine problem.
