### ISSUE TITLE
Feature request: Remove unknown block

### ISSUE THREAD

**Issue by greencopper** [minetest/minetest#3783]
It would be really nice if we could get some easy way to clean up unknown objects from removed mods.

Without having looked through the code there must be some conditioning which inserts the "unknown" part, this conditioning could be changed into simply removing the block rather than inserting an the "unknown" part.

Anyway, this would really be nice.

**Comment by indriApollo** [comment]
Mods can already do this, see mine for example : https://github.com/indriApollo/remove_unknown

**Comment by greencopper** [comment]
Yeah, but not quite. We need a simple command that just cleans all the world out in one go without radius or other specifications.

**Comment by C1ffisme** [comment]
I would like it if unknown nodes retained their old names, and you could select what they are replaced with. That way ores become stone, and building blocks become cobblestone, and glass-like blocks become glass.

**Comment by nerzhul** [comment]
@greencopper cleanup the whole world mean load all mapblocks in memory to cleanup them. The better way could be to use @est31 LBM and have a native LBM to manage this case if a feature is enabled;

**Comment by C1ffisme** [comment]
LBM sounds better.

**Comment by ObaniGemini** [comment]
@LeMagnesium has started working on this : https://github.com/LeMagnesium/python-minetest
It permits to do what you say but also can take very long.

**Comment by JurajVajda** [comment]
Im going to definately replace my abm with lbm today...this would be a life saver (and a lag saver)

**Comment by nerzhul** [comment]
Close issue as LBM could solve this issue
