### ISSUE TITLE
Settings need removing from simple settings menu

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3787]
New style water.
Node highlighting.

**Comment by est31** [comment]
Why does node highlighting need a complete removal? It can switch between box and halo highlighting.

**Comment by kilbith** [comment]
New style water ain't in the simple settings menu.

**Comment by 0-afflatus** [comment]
> Why does node highlighting need a complete removal?

Because 'simple' users don't need to turn it off?

> New style water ain't in the simple settings menu.

That should be 'Waving Water'

**Comment by Wayward1** [comment]
Actually, waving water is different. New style water just lowers the water surface

**Comment by paramat** [comment]
Oops new style water isn't in there.
RBA told me it was a mess and needed updating, but it seems ok looking at it.
Sorry i must have been half asleep.
