### ISSUE TITLE
Client tries to open mesh files from any path without check [edited]

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#379]
Minetest loads meshes by using full unchecked  path to mesh file:

``` C++
scene::IAnimatedMesh *mesh = smgr->getMesh(m_prop.mesh.c_str());
```

This path is transfered to client when synchronizing CAO so client attempts to load mesh from servers path! Or any other path specified by mod!

**Comment by paramat** [comment]
Very old issue, can anyone confirm?

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/f3997025fd4785606fe4f8b05037e9463c5be7da/src/content_cao.cpp#L603
Code has changed.
