### ISSUE TITLE
Smooth lighting no longer works on liquids

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3790]
Cc: @RealBadAngel 
Cci: @est31 @paramat 

Regression caused by https://github.com/minetest/minetest/commit/8eb7ddb0a2f03ae514a96191f6edba9333ba2423

**Before https://github.com/minetest/minetest/commit/8eb7ddb0a2f03ae514a96191f6edba9333ba2423 :**
![screenshot_20160226_150043](https://cloud.githubusercontent.com/assets/7883281/13354221/eb7641ea-dc99-11e5-89e6-bcd9d28caab6.png)

**After https://github.com/minetest/minetest/commit/8eb7ddb0a2f03ae514a96191f6edba9333ba2423 :**
![screenshot_20160226_145618](https://cloud.githubusercontent.com/assets/7883281/13354267/2dac53b0-dc9a-11e5-9145-2ddc4d6d57cc.png)

**Comment by PilzAdam** [comment]
`f->solidness = new_style_water ? 0 : 1;` should have been changed to `f->solidness = 1;`, not `0`.

**Comment by kilbith** [comment]
@PilzAdam Your fix works, you can merge ?

**Comment by paramat** [comment]
Cool, i can do this.

**Comment by PilzAdam** [comment]
@paramat go ahead.

**Comment by paramat** [comment]
Should be fixed now.
