### ISSUE TITLE
Insecure environment table doesn't give minetest table, but it gives core table

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3791]
If you do `print(dump(minetest.request_insecure_environment()))` in a trusted mod you get lots of things, but you quickly see there is no minetest table -- the table instead is named "core".

Is that a good thing? Do we want to abandon the minetest prefix on new APIs?

I don't think its too late to switch to `minetest` yet, its not such a big stability break considering the number of mods using the insecure environment.

**Comment by est31** [comment]
**cc** @ShadowNinja

**Comment by MoNTE48** [comment]
@est31, what is the difference between core.* and minetest.* ?

**Comment by rubenwardy** [comment]
core is the builtin/engine name for minetest.
At the last line of builtin/init.lua ? there is this line:

```lua
minetest = core
```

Mods should use minetest.*
Builtin things should use core.*

**Comment by MoNTE48** [comment]
@rubenwardy, some modifications used core.* without problems
 If there is no difference, why not use the core.*? This will be more aesthetically pleasing (although there is no difference) for the forks.
