### ISSUE TITLE
Only stone with minetest_game on v5/v7/valleys

### ISSUE THREAD

**Issue by MoNTE48** [minetest/minetest#3794]
sometimes (1 to 10), I get the only stone biomes on Android. There are a lot of stone (a kind of biome is the same as it should be, simply just a stone), sand, water and gravel. This is quite strange, but it happens. v6 and other mapgens work satisfactorily.

**Comment by paramat** [comment]
Weird, Android is weird. Screenshot please. Is there sand, dirt, gravel as blobs in the stone? if so those are blob ores.

**Comment by MoNTE48** [comment]
@paramat, yes, all blobs it too.

**Comment by MoNTE48** [comment]
![screenshot_20160228-005543](https://cloud.githubusercontent.com/assets/6764600/13375950/1774dd16-ddb6-11e5-9ae4-4cbb8b499709.png)

**Comment by paramat** [comment]
Looks like biome definitions are failing for some weird reason.

**Comment by MoNTE48** [comment]
@paramat, Yes, if I will go into some side about 500 block, will begin medleneo appears different decorations (for example, a little earth and a tree). After about a thousand blocks generated correct biomes will be restored

**Comment by rubenwardy** [comment]
Is this with minetest game?

**Comment by MoNTE48** [comment]
@rubenwardy, Technically, yes.

**Comment by rubenwardy** [comment]
Does it still persist if you use the latest vanilla minetest game?

**Comment by MoNTE48** [comment]
I will check it in the morning and I will write to you. But I'm 99% sure that there is no difference because in MultiCraft I use almost vanilla mapgen (it will not overcraft)

**Comment by paramat** [comment]
This report is not valid unless you are using latest dev of vanilla @MoNTE48 will close soon.

**Comment by paramat** [comment]
No response so closing, please do let us know if this happens with latest official MTGame.

**Comment by paramat** [comment]
@MoNTE48 ^

**Comment by MoNTE48** [comment]
@paramat, As I said, this is not a problem my subgame (I use a completely vanilla mapgen, only changes in the ore) and in multicraft there is no change in mapgen, mostly changes to the interface. Where can I download the latest minetest build?

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/archive/master.zip

**Comment by MoNTE48** [comment]
@paramat, no, apk. But I can check minetest_game in MultiCraft,  if you agree.

**Comment by paramat** [comment]
Sorry, you want a build instead, i'm not sure i always compile, but i expect there are links on the forum.
It's best to not use a subgame as there may be something different we haven't thought of.

**Comment by DonBatman** [comment]
MoNTE48 I think you would be better off if you helped the dev team with the andriod miinetest instead of your own version of it. Maybe you could help with the controls. The need a little tweaking.

**Comment by MoNTE48** [comment]
@DonBatman, I wanted to help, but my changes are ignored. MultiCraft is much faster and more stable than Minetest. sapier did not know many details, when doing port. I would be happy if my changes were in Minetest (Now MultiCraft code stolen more often than Minetest. This is the irony). But some idiots think that if I earn money on the LGPL code (which is completely allowed by the license, chosen by a respected celeron55), I shit you want to humiliate and ignore.

**Comment by rubenwardy** [comment]
You need to submit any changes as pull requests, it's rather hard for someone to go through your repo and pick changes.

**Comment by paramat** [comment]
I've just discovered Multicraft is a forked engine not just a subgame, that could change many things so this issue is obviously useless, please only submit issues for official Minetest and Minetest Game.

**Comment by MoNTE48** [comment]
@paramat, As I mentioned, if you believe that the generation of maps affected by changes mainmenu, defaultsettings.cpp, touchscreengui.cpp and some other files that have no relation to the mapgen - I'm surprised to hear it. You checked it extremely carefully.

**Comment by paramat** [comment]
It's possible that something in your fork is causing this bug, something subtle you haven't thought of, that's why it's obviously pointless opening as issue here for a bug in a fork of Minetest.
This issue is a waste of our time, you didn't make it clear this is a bug in your fork of Minetest, i was thinking you were using a subgame called Multicraft.

I see you are Martin_Devil on the forum, you have a thread that was originally titled "Re: MultiCraft – Me hate Minetest and Mojang" and which reads "Me do not like many Minetest developers", so why would we have any respect or time for you, why are you even here? The thread also points out some possibly bad behaviour in your fork.

In future i will close any issues you open unless you clearly state that the issue is in, or can be reproduced in, Minetest and/or Minetest Game.

**Comment by MoNTE48** [comment]
@paramat, true, Martin_Devil is my old nickname.
I can not blame you. You're a respected developer and you're probably right. When I have time and I decide to try v7 again, I will make a full test on the official minetest. Just now it is useless, Google Play, a very old assembly code in Minetest master repo is not going for me. And as the game runs very slowly.
If in the future a minimum of 2 Developer (I think @ est31 not mind) would be willing to accept my changes Minetest code, I spend my time and make Android version of the game is the same chic as MultiCraft. However, I want the developers to understand that what I've changed - I've done it correctly (for example, I was criticized for changing max_fps to 30. But no one bothered to test as I). I am very much I test my game and now I can say that @sapier just made the code work on Android. But he did not do anything to the people was a pleasure to play. My respect @rubenwardy very useful for the creation of "mtmods4android". He thought of the Android players, but have not decided what they will do everything yourself.
An example of what I do not like:
what the fuck on Android is retarded mainmenu? Why do it? Android players are not idiots, they want to be able to create many worlds. Why am I back the original menu and it does not cause anybody problems, Minetest and did not do it? You can see here
https://github.com/minetest/minetest/issues?page=2&q=is%3Aopen+is%3Aissue+label%3AAndroid
I've fixed most of these errors. But I know that if I make a pull request will take several months before his notice and criticize. Perhaps I should say that in the IRC.
(Sorry if I have offended anyone, I talked to some guys who left Minetest and they agree with me. Minetest has no clear ToDo and goals he wants to achieve.)

**Comment by sofar** [comment]
There are currently no active core devs that are really focused on android. The only solution is to keep submitting the changes to minetest, test them thoroughly, and be patient. If you don't submit them, they're never going to get merged - no matter how upset you get.

**Comment by MoNTE48** [comment]
@sofar, i just want to hear whether or not to consider my commit or it will be forgotten, and I will spend the time that I could spend with my family. I just want to improve the gaming experience for Minetest players.
