### ISSUE TITLE
Clipping bug 

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3798]
We discovered a clipping bug on Liberty Lands. I attached a we file (with txt extension because github). 
[bug.we.txt](https://github.com/minetest/minetest/files/149681/bug.we.txt)

You need the following mods for this particular we file. But the bug can be triggered with blocks the same shape from other mods.

 * windmill
 * homedecor
 * columnia

In the image you see the area on the server. Just walk in the direction of the arrow. The green lines show where the bug can appear. You will fall through the blocks. 

![bildschirmfoto von 2016-02-28 02-13-51](https://cloud.githubusercontent.com/assets/1377943/13376649/ab717eb0-ddc1-11e5-92f4-56cc802d0bf7.png)

**Comment by lightonflux** [comment]
Simple layout:

     plank slope |    air
         air     | full block

Or 

     plank slope |    air
     full block  | full block

**Comment by est31** [comment]
Can you check whether it still exists in current master?

**Comment by lightonflux** [comment]
If the server and moreblock run the current master then it appears that the bug is not triggered.

**Comment by est31** [comment]
Okay, it seems to be fixed by ee50341297435d05fd276d28ff469505fbdb303b then.
