### ISSUE TITLE
A way to register callbacks that run after all the callbacks from register_on_player_hpchange

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#3799]
Since any on_player_hpchange callback can change the result damage to the player, no callback can assume that the damage it receives is the final damage. This makes it impossible to make for example a mod that displays damage values above the player, and have it be accurate. (You could do it in a punchplayer callback, but it would have the same issue).

If there is another list of callbacks that is run after on_player_hpchange, and do not have the ability to change the result damage, it would be safe to make callbacks that assume the input damage is the final value. Maybe register_after_player_hpchange?

**Comment by TeTpaAka** [comment]
This is already the case. When you register a function with minetest.register_on_hpchange() you can omit the second parameter and the function is called after the callbacks, which change the hp value, but can't change anything.
See https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1870

**Comment by raymoo** [comment]
Thank you. I was aware of the parameter, but I did not know it changed the ordering of callbacks.
