### ISSUE TITLE
Cmake generates a wrong (bundled)lua project file

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#3802]
cmake generates a project file where lua is a static libary. But then it want to compile it as a multi-threaded-dll (compile with **/MD**) but this will end up with several linker errors. The correct way would be to compile it as multi-threaded ( **/MT**)

I does not know if this is a bug of CMake itself or just a wrong cmake configuration file.
If its the last case this should be fixed, because you have always change the compiler parameter manually after generating the project files.

Screenshots: (sorry for localization)
Generated file: (does not work)
![lua-configuration_generated](https://cloud.githubusercontent.com/assets/3142688/13421259/9971a50a-df8d-11e5-825f-d4bf4056a4e7.PNG)
corrected file: (works)
![lua-configuration_correct](https://cloud.githubusercontent.com/assets/3142688/13421260/9c11ea90-df8d-11e5-8aaf-da786faad264.PNG)

**Comment by SmallJoker** [comment]
#6153 merged
