### ISSUE TITLE
Questions about #ifdef cases for Windows (maybe obsolete?)

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#3803]
in [main.cpp lines 20-28](https://github.com/minetest/minetest/blob/master/src/main.cpp#L20-L28) There gets several libs linked which gets already linked by the Cmake generated project file. Compiling and linking works fine if you uncomment all this lines. Is there a special reason that they are there or could they get tidied up?

in the file [sound_openal.cpp](https://github.com/minetest/minetest/blob/master/src/sound_openal.cpp#L26-L29) lines 26-29 there is a `#ifdef _WIN32` case for special header files.
But as you can see in the [official download of OpenAl-soft](http://kcat.strangesoft.net/openal.html#download) everything is in the directory [/include/AL/](https://github.com/kcat/openal-soft/tree/master/include/AL)
as is used in `#else`. Is there also a special use for this or could this also removed?

**Comment by rubenwardy** [comment]
seems to be fixed
