### ISSUE TITLE
Make base64 encoding/decoding available for lua mods

### ISSUE THREAD

**Issue by indriApollo** [minetest/minetest#3804]
It would be cool to have this builtin instead of having to supply our own.
(I currently use http://lua-users.org/wiki/BaseSixtyFour)

**Comment by red-001** [comment]
What would a mod use base64 for?

**Comment by indriApollo** [comment]
To decode/encode url's, json params from restful api's since we have the http lua api.

**Comment by red-001** [comment]
See #3919.

**Comment by paramat** [comment]
@indriApollo any specific usecases or any needs for this at the moment?

**Comment by sofar** [comment]
A Github "stalk" of him reveals that he has a mod that talks base64 encoded strings over http (e.g. base64 encoded HTTP post requests).

This is also the most likely use case: a Minetest mod that pushes e.g. player statistics to an internal http service, or provides some interaction with a website.

**Comment by adrido** [comment]
Such Implementation could be pretty useful even to download skin files. Doing base64 conversation with lua only is horrible slowly, and does not make much fun.
https://forum.minetest.net/viewtopic.php?f=47&t=14149

**Comment by red-001** [comment]
could this get closed?
