### ISSUE TITLE
Add multi-line label (formspec element)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3807]
It would be **very** useful if Minetest supports a formspec element to show a text box.

The properties I wish are:
- Read only
- Looks like a label, only with multiple lines
- Lua scripter specifies position, size and text of the textbox
- Line breaks happen automatically at the end of the textbox, like for textareas
- Optional: A scrollbar for the whole textarea if the text is too long (like for textlists)
- I don’t care about background. That could be added with the box element anyways, so I don’t see a need for it

All current solutions I can imagine for multi-line text are ugly work arounds:
- Create text from textlist. Downside: You must manually place line breaks as “,”. This in turn forces you to escape manually, because you can’t throw the text into minetest.formspec_escape, because those commas would be escaped, too!
- Textarea. Downside: This is an input field which can be edited.
- Manually placing labels line per line. Way too much work.

I think this formspec element would be _badly_ needed; I have written several mod which need such labels but ended up using ugly hacks and manual line-breaks which is not pretty at all. :(

Also, it would be possible to get rid of the ugly manual line breaks in the settings descriptions in the extended settings menu and probably some other menus as well.

I have even seen mods where a textarea was used which should clearly not be editable. But it was done because a multi-line label was not available.

This suggestion originates from: https://forum.minetest.net/viewtopic.php?f=5&t=10198

**Comment by C1ffisme** [comment]
:+1: times several million.

We need this for books, computers with text, etc.

**Comment by 4aiman** [comment]
Like this?
[https://gist.github.com/4aiman/deaa22b5f2833e3584ed](url)

**Comment by Wuzzy2** [comment]
Personal remark: I think this is the most important feature currently lacking in the formspec API. Just to proof it to you: I have already 3 (!) mods where I would have really needed such a widget, but instead I was forced into hacking my own crappy workaround solutions:

* `tutorial` from my Tutorial subgame, for the text on the info signs
* `ltool`, for the internal help texts explaining how to use the mod
* `doc`, for the help entries

Either I hacked something with word wrap together with textlist, or I used textlist and applied ALL line wraps manually. Unsurprisingly, all solutions I used are ugly. Manual line wrap is ugly for obvious reasons. For `doc`, I hacked together my own automatic line wrapping. It works, but it is fixed to ca. 80 characters, instead of the actual width of the textlist widget I used for this. This is because in Lua I have no knowledge of the actual space used by the textlist widget. So I just settled for a very small window width. Which means for large windows there will be lots of open space left. :-(
With the proposed widget, the UI of these 3 mods can be greatly simplified and improved.

Fixing this issue will also help to clean up many main menu widgets which are currently more or less abusing textlist: Credits, error messages, mod description. For small window sizes, the text may not fit into the widget anymore, and because textlist does not apply automatic line breaks, text may get lost in these widgets. Replacing textlist with the proposed widget will also fix this.

**Comment by HybridDog** [comment]
You can't manually set line breaks because the client can use custom font and font size and it's likely not a monospace font. **C** for example is much longer than **l**
![img](https://my.mixtape.moe/uvkqll.png)

**Comment by HybridDog** [comment]
https://forum.minetest.net/viewtopic.php?f=47&t=18492

**Comment by paramat** [comment]
Any core dev support?

**Comment by SmallJoker** [comment]
> Textarea. Downside: This is an input field which can be edited.

They can be set to read-only:
https://github.com/minetest/minetest/blob/21c720755bfc9fa54fbb2722e0dd5cfbd96f8814/doc/lua_api.txt#L2205

In the master branch they will however have additional scrollbars (as seen in the new player registration confirmation dialog) as soon they run out of vertical space.

**Comment by HybridDog** [comment]
read-only textarea still shows the background, doesn't it?

please add the "Closed but PRs may be accepted" label

**Comment by SmallJoker** [comment]
@HybridDog No, look at the screenshots here #7047 and the code example in #6787 to test the different textarea types.

**Comment by Ezhh** [comment]
I'd say that label makes a lot of sense. It clearly indicates the team doesn't plan on adding/changing something themselves and don't see not doing so as an actual "issue" in anyway , but that it's not a definite no and that people can still make a PR if they feel strongly enough. It's not about encouraging PRs, just about informing contributors that one wouldn't be automatically rejected.

**Comment by paramat** [comment]
I was just about to delete my last comment :)

**Comment by paramat** [comment]
If an issue is closed it is either 'won't add' or no core dev support or interest for 2+ years, in both cases we shouldn't encourage PRs because no core dev support or interest is essentially disapproval, any new PR is likely to get the same reaction.
The label encourages PRs which are likely to result in no support or interest.
If PRs may be accepted there is interest in the feature so the issue can be kept open.

**Comment by paramat** [comment]
Ok sorry for my silly arguing.
