### ISSUE TITLE
Advanced settings: Comments do not line-wrap

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3808]
For settings with flags, the description in the extended settings menu sometimes doesn't fit.
I am talking about the list of available flags.

Just look at the description of mg_flags. The final line. There should be a list of all flags but it is all put into a single line and the text is too long for the line and is incomplete, thus losing a part of the information.

Related: https://github.com/minetest/minetest/issues/3807

**Comment by paramat** [comment]
@PilzAdam

**Comment by paramat** [comment]
Related #3266

**Comment by paramat** [comment]
Duplicate of #5832 closing this as that contains other issues.

**Comment by paramat** [comment]
Fixed by #7802
