### ISSUE TITLE
Node highlighting no longer relies on `enable_node_highlighting` and break settings tab

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3812]
Cc: @est31 

Since https://github.com/minetest/minetest/commit/b44da4916aa09b27155ce6675cccbcc128b5a66c, the setting `enable_node_highlighting` is inoperative to enable/disable that feature. RBA added the setting `node_highlighting` which expects a string value (i.e. `box` or `halo`).

I suggest to rename `node_highlighting` to `enable_node_highlighting` and make it expect a boolean value instead of a string because the current settings tab is broken because of that (checking / unchecking the checkbox has no effect).

Looking for string values force using a dropdown just for 2 values instead of a simple checkbox.

**Comment by paramat** [comment]
This seems to be caused by re-adding the simple settings menu, which uses a bool. RBA did say the simple settings menu was broken since re-adding it. I agree to returning to asimple bool for this, this way the simple settings menu can stay unchanged and remain a simple checkbox, and we alter the advanced one instead.
:+1:

**Comment by est31** [comment]
:-1: The new setting is more user friendly being an enum. I've seen it during code review, but it was okay for me, and it still is.

Main menu needs fixing though, that's a bug I agree. And it can still stay a checkbox in the simple settings menu :)

**Comment by kilbith** [comment]
> And it can still stay a checkbox in the simple settings 

Make it an enum suggest that RBA might add other types of node highlighting. So I'm very dubitative about a checkbox.

**Comment by est31** [comment]
Well once we get more types of node highlighting we can change the main menu checkbox to be a drop down list. But it requires only modification of the main menu code, the setting stays an enum.

**Comment by kilbith** [comment]
IMO, it may be pain for the next people to deal with the dropdown code once they add a new highlighting type. It's done once and for all in my referenced PR.

**Comment by est31** [comment]
I'm fine with both.

**Comment by paramat** [comment]
Yeah i'm fine with either method of fixing this.

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/commit/335ad705e6cb3cad4ba1a1e27d36d77d163777e8
