### ISSUE TITLE
Won't compile, Build System Paths screwed up when compiling on Visual Studio.

### ISSUE THREAD

**Issue by hcorion** [minetest/minetest#3814]
Hi all, 
So I've been trying to get Minetest (from source) running all day. I was always gettings these wierd errors about files missing, like it couldn't find zlib.h or sqlite3.h for some reason. So, after some snooping around, Visual Studio gave me an error when it tried to find sqlite3.h, which said that it couldn't find it in the Build System Paths. So I went to go check out the Build System Paths. Turns out, I had the following build system path:
```
C:\minetest-git\DIR\minetest-build\src;C:\minetest-git\DIR\minetest\src;C:\minetest-git\DIR\irrlicht-1.8.3\include;C:\minetest-git\DIR\zlib123;C:\minetest-git\DIR\minetest\src\Release;C:\minetest-git\DIR\minetest\src\;"C:\minetest-git\DIR\sqlite3\include";C:\minetest-git\DIR\minetest\src\lua\src;C:\minetest-git\DIR\minetest\src\gmp;C:\minetest-git\DIR\minetest\src\json;C:\minetest-git\DIR\minetest\src\script
```
And there was a ; missing between `C:\minetest-git\DIR\minetest\src\` and `"C:\minetest-git\DIR\sqlite3\include"`
please fix this!
System details:
Intel i7
64 GB RAM
Windows 10 Pro 64-bit (10.0, Build 10586)
Microsoft Visual Studio 2015 Community Edition
CMake version 3.4.3

**Comment by est31** [comment]
@SmallJoker builds using MSVC, perhaps they can provide assistance.

**Comment by SmallJoker** [comment]
How and where can this error be reproduced?
Which compiling tutorial are you using?

1) Get the required libraries
2) Compile the libraries if not done yet
3) Start CMake using the command `cmake-gui` (or using any other link)
4) Hit configure and fill in all fields (see checkbox "Advanced" if you can't find some)

I would like to help you but the information you gave us is incomplete.

**Comment by hcorion** [comment]
Ok, turns out It was having troubles because I was using quotes, like "C:/User/Jim/minetest" rather than just C:/User/Jim/minetest, in my path names. We can probably close the issue.
