### ISSUE TITLE
dungeongen y_limits

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#3819]
It would be useful if you could set generation y_limits for dungeons. 
e.g. only allow dungeons below the water surface `dungeon_y_max = 0` 
or between two y values like `dungeon_y_max = -500` and` dungeon_y_min = -1000.`

**Comment by C1ffisme** [comment]
:+1:

**Comment by paramat** [comment]
Dungeon parameters are going to be reworked soon, this might be added.

**Comment by paramat** [comment]
See #4216

**Comment by RHRhino** [comment]
@paramat Is it possible to define the y_limit for dungeons in a mod or are the parameters only added to the core code?

**Comment by paramat** [comment]
Dungeon parameters will be easily settable soon.
