### ISSUE TITLE
Revised Server List 

### ISSUE THREAD

**Issue by Eater4** [minetest/minetest#3828]
Limit the number of servers displayed at one time to 10. If more then 10 servers are connected to the server list, have the client rotate though different  every time the client connects to the server.

**Comment by Eater4** [comment]
have the client rotate though different servers*

**Comment by Calinou** [comment]
What's the point in making part of the servers impossible to join through normal means? Or did I not understand what you want right?

**Comment by rubenwardy** [comment]
:-1:

Maybe have a special slot for a random server, but don't hide servers.

**Comment by 0-afflatus** [comment]
-1000 Unless I have misunderstood something this is a really stupid idea.

**Comment by Eater4** [comment]
Ah, No. The issue here is that we have too many servers to be in one list. If we can separate servers by creating different tabs for different playing modes, I think that all servers will have a better shot at gaining players.

**Comment by 0-afflatus** [comment]
It would be better to make the one list filterable and sortable by the player instead of trying to pre-guess what the player might want or limit the options.

**Comment by rubenwardy** [comment]
one such filter mode could be subgame based, and have a category for each subgame like:

```
- minetest game (97 servers)
     - one
     - two
- capturetheflag (2 servers)
     - three
     - four
```

however a problem with this is that servers often have their own subgame (and that does make sense IMO).
For example, redcrab_game

**Comment by stujones11** [comment]
I might be useful to allow filtering by the existing tags, such as dmg, ded, pvp etc but servers should **not** be hidden regardless of their popularity. If server admins really want more players then they should look at what makes the popular ones so successful. This has very little to do with how the server-list is sorted as the many previous attempts to 'control' it have proven. IMO it comes down to three major factors: speed (ping/lag) content (mods/subgames) and above all, good administration.

**Comment by JurajVajda** [comment]
Just making a filter input field and possibility of adding a server to
favorites would me more than enough imho

**Comment by JurajVajda** [comment]
Having a simple filter and adding a server to favorites would be really nice to have imho

**Comment by 0-afflatus** [comment]
@stujones11 agreed.

**Comment by rubenwardy** [comment]
this seems unpopular
