### ISSUE TITLE
Layered/Cascaded Texture Packs

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#3832]
Texture packs that can be combined by simply putting them all zipped into the texture packs folder and then enabling them within the client giving them an order and the game automatically “cascades” them from top to integrated default textures making it possible to use textures from a various amount of different texture packs at the same time each styling only individual nodes

I.e. texture pack A has textures for the nodes 1, 2 and 3 and texture pack B has textures of node 2 only and is “on top of” texture pack A, so the result would be nodes 1 and 3 are styled like A defines, and node 2 has the texture B provides).

Please refer to the image I created showing the suggested feature.

![cascaded_texture_packs](https://cloud.githubusercontent.com/assets/1668792/13655731/f4dfdee0-e661-11e5-88f1-31371536f954.png)

**Comment by C1ffisme** [comment]
Why ZIP files? Why not just use folders?

(Sorry if I don't quite understand, I'm tired at this time and can't read this right.)

**Comment by lightonflux** [comment]
This is a great idea. Although I would recommend layering by name without zip as this would be easier to integrate in currently distributed texture packs.

Default we now have: texture.png
First additional layer texture.1.png
Second layer texture.2.png etc pp

**Comment by dsohler** [comment]
#### Zip files or folders

Actually it doesn’t really matters (wasn’t it that Minetest already supports both) for the result. Using folders is absolutely fine even if it may take a little longer to load because extracting in RAM is faster than reading single files form a storage. When using an SSD this isn’t that much of an issue anymore. (Actually even on a HDD this might be in the microseconds field but still …)

But again: It’s not important. Maybe the best way would be supporting both so you can simply download texture packs and use them without having to extract them. And when you’re a texture artist simply use a folder for your texture pack development so you don’t need to re-archive your texture pack all the time when testing things out.

#### Altering the texture pack’s file/folder name for ordering

Linux does/did this very similar for the priority or loading modules some time ago. Even there one of the issues was the ordering or the adding of more modules between other modules.

You either need a large gap between the numbers (10, 100, 200, etc) to have enough space to add more between, let’s say, 10 and 100. or when you want to keep your numbers small you need to rename all of the following files (having 1, 2, 3, 4 and you want to add something between 1 and 2 you have to rename 2, 3, and 4).

Another downside of this is that you need to alter all of your texture packs making it harder or impossible to automatically update them. When having a simple menu where you can change the order of the texture packs (on the back-end represented as values in `minetest.conf`) by drag’n’drop or via buttons and you don’t have to mess with the files manually it’s just easier to handle and update texture packs.

When using file/folder names for ordering: How do you want to respect the textures added by mods? Since there is no file/folder representing the texture (except within the mod’s folder) you need to find another solution for that or ignore mods completely when it comes to the order of the layers.

If you use a menu you could add “Textures provided by mods” as a “virtual” texture pack you can move like the “real” texture packs. Maybe you could add an option “Show individual mod’s textures” so you can order the textures for all mods

**Comment by 0-afflatus** [comment]
I think the general idea is good, but it does needs to be kept simple.

I'm not quite understanding some of this. The folder organisation is irrelevant to the game as textures are all prefixed by `modname_` so the game sees a flat list of files. Currently the textures used depend on the order of loading - I use this in my game, which uses 32px textures to override the default 16px textures of 3rd party mods. So to a certain extent you can already do this - but I can see this would obviate the need to create a single custom texture pack.

**Comment by dsohler** [comment]
For having the textures provided by mods the game has to “pseudo-load” all mods to be able to “extract” the textures from them, yes. The “mods textures layer” is only relevant if the mod is used and otherwise will have no effect because the nodes and items are not rendered anywhere.

Instead of relying to a possible race condition or unintended texture loading behavior resulting from how mods are being loaded a way to define the loading order (or display priority) would inherently make this all more reliable and consistent … Plus: You get a way to prioritize textures without messing with the actual texture pack files/folders or manually altering textures provided by mods.

This makes in more stable when it comes to updates.

**Comment by yyt16384** [comment]
I think textures provided by mods are only known when client connects to the server, so it probably won't work in the settings menu. Having one layer for each mod also seems too complex.

If it is only about client side textures, it should be easy to change the texture pack option to allow multiple values, and having the client load all of them in a certain order.

**Comment by tenplus1** [comment]
Why not just take the time to copy & paste the textures you DO want into a custom pack ?  It would save having to add features to the engine.

**Comment by C1ffisme** [comment]
@tenplus Probably better organization. Sometimes you would want only certain parts of that pack, like on a custom server or something.

**Comment by rubenwardy** [comment]
This seems like a lot of added complexity for something that not many people would use

**Comment by dsohler** [comment]
We all can’t say if people would use it or not.

It would add a lot of flexibility in using texture packs making it possible to have partial texture packs without having to manually copy and paste files around making it impossible to properly maintain the texture packs when it comes to changes or updates.

Maybe leave out textures provided by mods completely and add them right after the default textures when creating the texture layers. This would remove a lot of complexity from the suggestion.

This could boost the participation of texture artists on Minetest because they don’t need to create ALL the textures at once (or copying from the default texture pack) when releasing texture packs but can release texture packs bit-by-bit without needing to care about newly added nodes or not yest finished textures because they can simply leave them out.

I see that the manual approach tenplus1 has is the simplest one coding-wise but it’s the most complicated one regarding the actual management (and development) of different texture packs and updates because it all has to be done repeatedly with every update of the texture pack.

We can only assume if people would accept a properly implemented, fully optional (it’s still possible to use tenplus1’s way of texture pack management) texture pack management that adds a lot of flexibility to the game’s configuration in userspace or if they’ll stick with manually cobbling together files from different texture packs.

**Comment by 0-afflatus** [comment]
> We all can’t say if people would use it or not.

So there is no need for this feature then.
Plus I have to mention your sentences are far too long and really difficult to understand.

**Comment by paramat** [comment]
:-1:

**Comment by dsohler** [comment]
Too bad that obviously no-one cares.

Fuck it.

**Comment by numberZero** [comment]
I ask similar but simpler thing: to be able to load several texture packs at once. This way you could play with your favorite TP but use some not-as-pleasant but larger TP as a fallback, e.g. if you don’t want to see a 16px texture having a 64–256px TP.

Separate handling of builtin nodes is not required as there are only 2 builtin nodes: `air` and `ignore` (`unknown` is not really a node); game nodes are added by game mods. Ordering of these may be altered by (soft) dependencies, AFAIK it’s even possible to let game mod load after a third-party mod, in its presence.

**Comment by tacotexmex** [comment]
Too bad this closed. As texture pack maintainer and subgame maker this would be really useful to rely on a git based overhauling texture pack then add texture customizations on top of it. How else would I maintain a customized version of, say, Summerfields?

**Comment by tacotexmex** [comment]
Actually, this could solve the whole thing? #4468

**Comment by tenplus** [comment]
Hi all,

I don’t know why I’m in the mail list. In fact, I know nothing about the project. Can anybody tell me why?

Best,

Jia Shi

**Comment by nerzhul** [comment]
@tenplus1 ^

**Comment by tenplus** [comment]
Oh, it’s not me!

**Comment by C1ffisme** [comment]
Oops.

**Comment by red-001** [comment]
@tenplus looks like someone confused you with @tenplus1

**Comment by paramat** [comment]
#6412 is merged and may enable similar usage?

**Comment by Warr1024** [comment]
With the advent of ContentDB in 5.0+, it seems like this issue is relevant again.  Now that users can install texture packs directly from the in-game menus, the level of technical expertise required to combine them is significantly higher than the level necessary to install them.  Expecting each player to create a custom texturepack by hand with the combination they want is probably unreasonable for players who just want to pick packs from the content store, but not letting them combine packs means they may have to choose which content they want textured and which they want untextured for a particular set of mods.

We also can't expect the community to fill in the gaps here, i.e. by publishing compilation texture packs, because (1) some texture pack content on the CDB may be incompatibly licensed, and (2) the number of potential combination texturepacks grows factorially with the number of original ones, and we don't necessarily want to CDB cluttered with trivial recombinations of the same content over and over.

**Comment by tacotexmex** [comment]
>Expecting each player to create a custom texturepack by hand

I don't think no one expects the player to be able to do this, not even the player itself.

_If_ someone wants to delve into it and customize by layering/cascading the TPs, which is what this issue is about (not customization tools per se), the feature introduced by #6412 enables this.
