### ISSUE TITLE
Protection API improvements

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3833]
@sofar has originally brought up this issue, and its best discussed first before implementing it.

The current way we handle the `minetest.is_protected` API is a bit bad: we require mods to override the function, and there is no way for the engine to influence the outcome of `minetest.is_protected`, e.g. in order to add a special priv to bypass protection like #3800 does. The way 3800 implements it is to accompany every `minetest.is_protected` call with a check inside the privs, which surely shouldn't be the way to do it.

sofar's idea would be that instead of overriding `minetest.is_protected` mods register a function that decides about protection, and then the engine providing the code that calls the mod provided functions, and returning a result depending on what the mods returned.

What the new implementation should provide:
- Of course the main reason: tracking indifference by a mod
- An easy way to realize the #3800 feature
- Support for #2250
- Handling for legacy mods that override `is_protected`

Some open issues:
- As we have to handle mods that override `is_protected` as "normal" part of their life, should we provide the new functionality under a new name like `cant_access`?
- @ShadowNinja has expressed concerns about speed in #2250 but his suggested changes require lua 5.2 which we won't likely introduce, as luajit will very likely never ever get more lua 5.2 features.

**Comment by sofar** [comment]
I'd replace the negative with a positive: ```can_access```. However, ```access``` is suggestive, so I feel it's a bad word choice.

A more neutral word shouldn't be too hard to come up with: ```is_allowed(player, pos, action)``` or ```is_permitted``` may work well (plus corresponding ```minetest.register_is_allowed``` or ```minetest.register_is_permitted()``` registrations).

Mechanically, I think an API as follows can work:
- by default, the action is allowed
- each registered callback is called
- if the callback is returns ```nil```, the default action value is used
- if any callback returns ```false```, the action is denied
- if any callback returns ```true```, the action is allowed immediately and no more callbacks are considered
- if no callback returns ```false```, or all return ```nil```, or there are none, the action is allowed

I like the idea to have fine grained access bits. I can think of the following, and this is meant to be exhaustive, so if I'm missing any let me know:

- place: player can place a node at pos
- dig: player can dig pos
- interact: player can right-click the node at pos
- punch: player can punch the node at pos
- move: player is allowed to move to pos (this one is likely unwanted)
- formspec: player is allowed to view node formspec at pos
- inventory-get: player is allowed to get items from the node inventory
- inventory-put: player is allowed to put items in the node inventory

**Comment by C1ffisme** [comment]
We should implement a protection system inside of minetest that can be overwritten by mods. (Meaning that servers don't have to install a protection mod unless they want custom features.)

Maybe it would work like:
"/protect" -Protect a 16x16x16 cube around you (Not an actual chunk, just an area of that size.)
"/unprotect" - Take away protection from the cube you are standing in (Only works if you own it, or you have sofar's privilege.)
"/givearea (player)" - Give the area to another player.

This really doesn't have to do with the API, but if we have protection at all, we might as well use it.

**Comment by est31** [comment]
@C1ffisme no I think its cool to have diversity on this issue.

**Comment by est31** [comment]
@sofar what's the difference between interact and formspec?

I can think of player and entity punch access bits as well.

Also, I don't think we should check player and entity punch access bits or move bits per default, mods will have to enable it manually, so that we spare the additional processing.

**Comment by sofar** [comment]
@C1ffisme I'm with est31 on this. I think we should redesign the API but leave it at that.

**Comment by sofar** [comment]
@est31 they're mutually exclusive, so, they can use the same priv. (or they are the same from a player perspective, yes)

**Comment by sofar** [comment]
We could easily provide backwards compatibility by maintaining and honoring ```is_protected()``` and allowing older protection mods to overwrite a ```core.is_protected()``` function. Instead of the default ```core.is_protected()``` effectively being ```return false``` we could put all the new logic in there. If an old protection mod is installed then that would work as previous, and if that protection mod gets upgraded to use a new ```minetest.register_is_protected()``` API function it would also work and use the new functionality. This would be extremely simple.

We could even, after mod init time, warn if an old protection API mod is installed to notify the admin that it needs upgrading, since we can compare the value of minetest.is_protected with the known core.is_protected function. (I tested this with lua5.1 and it works)

**Comment by 0-afflatus** [comment]
Can this please allow shared protection?

**Comment by sofar** [comment]
@0-afflatus can you elaborate what you exactly mean by that question?

If you mean, "can this facilitate having two protection mods live side-by-side", then the answer is yes (that's the design goal).

If you mean, "can this allow two players access to the same protected area", then the answer is yes (that's already possible though the current implementation, and would be something mods already do).

**Comment by 0-afflatus** [comment]
What I'm angling for is shared ownership of chests and doors, because many of my players want it. That is really outside the scope of this particular discussion as I understand it. I know it is possible using mods - I am working on integrating locks mod atm, but it seems daft to have several different types of door and chest, some locked, some shared locked and others not lockable at all. Most of that is doable in Lua, I just need some clear time not chasing bugs down for that. 

I'm happy with the answer you just gave regarding this issue.

**Comment by sofar** [comment]
@0-afflatus The API proposed in my comment near the top establishes all the required functionality in core/minetest_game to do exactly that. It would do it even so that the default doors, chests and furnaces could use it if applied properly, which is what I intend to do.

**Comment by Rogier-5** [comment]
@sofar: I was thinking of some additional types of actions:
- hit / attack without cause (between 2 entities, one of which may be a player)
  This can be enforced by one or more of:
  - not applying damage to the attacked entity
  - applying damage to the attacker instead
  - teleporting the attacker
  - or in general: invoking a callback to handle the situation
- fight back if attacked or provoked (between 2 entities, one of which may be a player)
- right-click a MOB / use a tool on a MOB
- pick up an item
- modify protection rules.

As a protection mechanism can be complex, maybe a two-tiered approach might be a good idea: one mod which implements the actual protection api, and one or more protection policy mods that implement the protection policies.

The protection api mod would make the final protection decisions after having invoked all necessary callbacks registerd with it by any protection policy mods. Protection policy mods in turn use the api provided by the api mod to register themselves.

The default protection api mod itself would implement a new api, and the arbitration algorithm you describe. And it would of course implement the legacy api as well. It should probably be enforced that only a single mod can register itself as protection api provider. It could replace the registration function with its own version that returns an error and logs a message, or so.

The advantages of the two-tiered approach are:
- The builtin protection api remains simple and minimal
- Only minimal changes are needed to the current protection api.
- All the additional complexity of handling and arbitrating between multiple protection policy mods is delegated to a mod.
- Mod writers can easily modify it to suit their needs. For example, they may want to assign priorities to different protection policy mods.

**Comment by ShadowNinja** [comment]
I think this is still relevant.

**Comment by sofar** [comment]
Very much so, I intend to tackle this after `0.4.16`

**Comment by nerzhul** [comment]
we need coreside protection API, a real protection with areas etc. I have the code in my fork permitting to generate protected areas easily (and store them into db for a player) and check currently protected areas. It will permit also to enable pvp or disable pvp locally :)

**Comment by SmallJoker** [comment]
A few new things appeared since this issue was created
 * `AreaStore` API
 * Clarified docs regarding the `protection_bypass` privilege (#8675)
 * `minetest.is_area_protected` API function (#6952, renamed in #7073)

I think this is already enough to provide ..
1) protection mod inter-compatibility (more than one per server)
2) sane area "contains position" checks
3) a way to store freely settable areas reliably
