### ISSUE TITLE
Serverside full chat scrollback

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#3838]
It would be nice if the server admin could specify:
- how much chat scrollback is saved to disk (preferably by days)
- how much chat scroll back is send to the clients

At the moment it is very annoying for players that reconnect to a server that all the chat history is gone. There is no context for ongoing discussions or even own messages (if you left a previous discussion).

At the moment only chat log from within a session (minetest client) are displayed after relogin.

**Comment by ShadowNinja** [comment]
Note to implementer: Any chat log would have to have a timestamp attached to each message for my console timestamp PR.

**Comment by rubenwardy** [comment]
I'd prefer this to be done as a mod (or at least in builtin)

**Comment by paramat** [comment]
@rubenwardy do you support the feature?

**Comment by paramat** [comment]
No core dev support for 2+ years so closing, but core devs feel free to reopen if you support this.
