### ISSUE TITLE
Console and Pause menu disabled after respawning

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#3842]
Cc: @ShadowNinja @est31 

Regression caused by https://github.com/minetest/minetest/commit/effa24737d6997dc40508533635accca3ed099e9

Clear steps to reproduce systematically : 

1. Die with the chat console opened (e.g. by falling).
2. After respawning, try re-opening your chat console.

There will be a screen-locking, just click to go back to the game. Then it will be impossible to open the chat console or the pause menu (forcing to quit Minetest by killing its process).

**Comment by est31** [comment]
Blocker label because before the thing worked fine, and the bug is very easy to reproduce.

**Comment by ShadowNinja** [comment]
Duplicate of #3831.

**Comment by est31** [comment]
Fixed by 8c951cae5bcfa715e227d47d122cc2de45d70a63
