### ISSUE TITLE
singlenode mapgen not selectable in main menu anymore

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3844]
I can not select the singlenode mapgen in the main menu (world creation dialog) anymore.
Is there a reason for this? I use this mapgen a lot for testing and stuff and it is annoying to have it removed.

0d2df732e5c5075cd8848b9a9530865430630bfe

**Comment by kilbith** [comment]
Yes it's hidden on purpose.

**Comment by Wuzzy2** [comment]
Okay, is there a simple setting to make it appear again? I don't want to go through the extended settings just to change the mapgen to singlenode.

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/blob/master/src/emerge.cpp#L113

But @paramat wondered about unhiding it.

**Comment by PilzAdam** [comment]
What other reason than mod mapgen is there to use singlenode? Mods can easily set the mapgen to singlenode, and there is no reason for users to select it manually.

**Comment by kilbith** [comment]
> What other reason than mod mapgen is there to use singlenode?

Importing big maps from MC : https://forum.minetest.net/viewtopic.php?f=12&t=9440

Although the flat mapgen may be more appropriate for that now.

**Comment by PilzAdam** [comment]
@kilbith I'm not sure that I get your point. `map_meta.txt` in the world contains the mapgen (`singlenode` in this case).

**Comment by rubenwardy** [comment]
I use it so that I can then use WorldEdit to make a flat platform for the base of a circuit board.

**Comment by PilzAdam** [comment]
@rubenwardy there are `flat` flags for other mapgens.

**Comment by rubenwardy** [comment]
It's not flat as in the mapgen definition, but it a cuboid 10x1x10
I reverted the commit in my local version, so doesn't effect me anyway.

**Comment by paramat** [comment]
Yes hmmmm hided it to avoid confusing newbies, but i have seen so many players with wanting to select it, and asking how to, that i will unhide it.

**Comment by paramat** [comment]
See #3851

**Comment by paramat** [comment]
I changed my mind. Although it's mildly annoying, those who know what they're doing can use a simple mod to select it. I feel it's more important to avoid giving a bad impresion when someone new to the game, or a reviewer, tries the various mapgens.

Here's the mod code you need https://gist.github.com/paramat/feb2361da106371652ad
I keep this simple mod in the game and enable it if i need to use singlenode.

**Comment by paramat** [comment]
Closing due to dev opinion.

**Comment by ObaniGemini** [comment]
I think there should be a way to enable it again for non-GNU/Linux users that can't compile the game, or if it already exists, a documentation to show how to do that.
Would a minetest.conf setting be possible ?
