### ISSUE TITLE
Suggestion: In-game [Esc] menu overhaul

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3845]
The in-game [Esc] menu is really outdated and contains a lot of legacy stuff and information probably uninteresting for the average user.

Proposed changes:
- Remove all the build information except maybe the name “Minetest” and version number. Move all the gory details to the main menu (credits or about section)
- Remove default controls except those which can not be configured yet (i.e. attack, select hotbar item, etc.). They are mostly pointless since controls can now be configured directly from this menu anyway
- In singleplayer it should say “Game paused.” (or something like that) at the top
- On the left, it should show some important Minetest settings currently active on the server:
  - Subgame name (read from game.conf, _not_ the folder name since it can vary wildly)
  - Damage on/off
  - PvP on/off
  - Creative Mode on/off
  - Maybe other settings if they are important, but we should not overdo it
- In multiplayer, it _could_ use the left area for a few server information like hostname / IP adress / port, server name, etc. But I am not sure about that

**Comment by 4aiman** [comment]
:+1: for everything with a remark that I'd rather have currently configured controls to be shown instead the default ones

**Comment by C1ffisme** [comment]
I have given my :+1: . I think that menu is really, really old. It's been the same since forever, the only change being the sound volume and controls buttons that were added.

**Comment by red-001** [comment]
working on adding this
TODO list
- [ ] Remove build information.
- [ ] Replace default controls with current controls
- [ ] Add game paused to the top of the menu in singleplayer
- [ ] Add game/server info

**Comment by nerzhul** [comment]
i agree, the build information should be in main menu in an about tab i think

**Comment by red-001** [comment]
@Wuzzy2 maybe you could close this and open a new issue for anything that's still missing?

**Comment by Wuzzy2** [comment]
Bravo! But I think the controls section to the right is a little bit buggy. Will post new issue soon.

**Comment by Wuzzy2** [comment]
Follow-up issue posted: #5750

@red-001
