### ISSUE TITLE
Make more keys configurable in-game or in main menu

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3846]
The controls menu in the main menu and in-game is a bit incomplete by now. A few more controls should be configurable with it.

Must-haves:
- [X] Camera [F7]
- [X] Minimap [F9]

Should-haves:
- [X] Screenshot [F12]
- [X] Toggle HUD [F1]
- [X] Toggle chat [F2]

Maybe-haves:
- [X] Select next/previous hotbar item
- [X] Select hotbar item no. X (maybe something for minetest.conf)

**Comment by red-001** [comment]
working on this.

**Comment by red-001** [comment]
See #3896.

**Comment by C1ffisme** [comment]
The Debug menu might also be nice, as well as camera toggle.

**Comment by Wuzzy2** [comment]
Everything of the feature request is now included in Minetest!
https://github.com/minetest/minetest/pull/6170 has been merged!
This issue can be closed!
I am happy!
