### ISSUE TITLE
Drop support for < 25 protocol servers by default

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3854]
Protocol 25, which was shipped first in 0.4.13, added SRP based authentication. SRP (among many other things) prevents the server from getting information about the client's password which it can use to log in to other servers where the user uses the same password. Right now however SRP is not of that much use as the client still sends the legacy password over the line in order to support pre-v25 servers. In order to unleash SRP's full potential, clients must not send the legacy init packet.

I propose the following: Add an option `send_pre_v25_init` defaulting to false. If the option is true, the client will send the legacy init packet to the server, otherwise it won't. If the option is false, clients won't be able to connect to pre v25 servers.

A "light" version can be that with `send_pre_v25_init` being set to false we still never send the pre v25 init packet, but if we encounter a legacy server where the `proto_max` field is below 25 or non existent (it was introduced with 0.4.12), we show a box before connecting asking the player to confirm that they join a legacy server, with an user friendly message.

A small survey run by me about server version distribution shows that 120 out of 129 servers from the masterlist (93%) would still be able to operate with newest clients. For the remaining 9 servers, users of clients after the change would have to flip the `send_pre_v25_init` switch.

I have always argued against protocol support breaks because there is no reason to do so, and no real benefit from doing the break, but in this case I think its justified, as the benefits outweigh the cost. Also, I only propose default protocol breakage, not total one, support for the old protocol will still be there so that people can still join a legacy server if they really want.

What are the opinions of the dev team on this?

**Comment by est31** [comment]
Link to the detailed survey results: https://gist.github.com/est31/66602d589b225b27afd5

**Comment by celeron55** [comment]
The generally working lazy way to handle these is to have one stable version that supports both, and then just disable by default in the next one, but if somebody bothers to add a UI dialog to warn and ask the user, I think there could be a setting already that defaults to having legacy logins disabled.

**Comment by est31** [comment]
In fact, there is already a stable client version that supports both pre v25 and v25 servers, its 0.4.13, and this issue is not about servers supporting pre v25 clients, that's a different situation, most of the clients use pre v25 protocols. So that would mean you :+1: the non-"light" approach? I would prefer it too as it would be the most simple to implement.

**Comment by nerzhul** [comment]
i agree with this but as we talk some month ago i think dropping this should wait at least 1 year. Then shipit with ~0.4.15 not 0.4.14.

**Comment by est31** [comment]
Okay as both @nerzhul and sfan5 want to wait, I've changed the PR to default to "still send old init packet".

**Comment by paramat** [comment]
Did we recently drop support for < 25 protocol? @nerzhul

**Comment by nerzhul** [comment]
no, we are in v24. v25 will be at least the minimum after 0.4.16 for 0.5

**Comment by nerzhul** [comment]
also, we have send_pre_v25_init inited to false, it seems it's a solved issue, else next release will increase protocol version and solve this issue too

**Comment by est31** [comment]
Yeah this is fixed since commit d767f025cb0d5cca29c1f2147d2a0931a088b717 , forgot to close it.
