### ISSUE TITLE
Mgv7 large pseudorandom caves bright at chunk borders when above water level

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3857]
... and when generating chunks upwards.

![screenshot_20160313_090230](https://cloud.githubusercontent.com/assets/3686677/13748217/c721f692-e9f3-11e5-900f-18fc16889197.png)

This is because, when the chunk above has not generated yet there is no way to know if there is light or shadow above, so mapgen assumes light when above water level and darkness when below water level.

I feel these large caves are not really needed above y = 47, they seem more of a 'at or below water level' thing. So i am considering disabling their generation above y = 47 in mgv7. They are already kept below y = -33 in mgv5, mgflat, mgvalleys and mgfractal. They can't be changed in mgv6 because this would break old worlds and mgv6 is 'stable'. We would still have the 3D noise tunnels above y = 47.
Thoughts? Does this seem reasonable?

**Comment by paramat** [comment]
I'll make a PR.

**Comment by 4aiman** [comment]
What about multi-layered worlds?

**Comment by paramat** [comment]
3862 merged.
Mountains and floatlands will only have 3D noise tunnels.

**Comment by 4aiman** [comment]
Ok, thanks. I have to remember to revert this commit locally.
