### ISSUE TITLE
API Tool Example Incorrect

### ISSUE THREAD

**Issue by Miner48er** [minetest/minetest#3864]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1226

Show formulas used to calculate these tables and correct examples.

**Comment by C1ffisme** [comment]
Probably a good idea, otherwise one modder may have way too underpowered tools, the other have way too powerful tools, and suddenly you put the two mods together, and un-balancedness happens.

**Comment by est31** [comment]
I think @sofar  has complained about something like this already... Do you want to take on this one?

**Comment by apachano** [comment]
@Miner48er The link is out dated, there is no tool information on that line. I can take care of this issue if you update what line it is coming from. Else is this still an issue?

**Comment by Ezhh** [comment]
@apachano This now appears to be at https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#1772
Line starting: "#### Example definition of the capabilities of a tool" - in case it moves again.
(I checked history for lua_api at the time the issue was opened to locate this)

**Comment by Ferk** [comment]
> https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#1772

The hash reference is missing the "L", should be /doc/lua_api.txt#L1772

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1772-L1803

**Comment by Ezhh** [comment]
@Ferk Typos happen :)

**Comment by paramat** [comment]
If you click the line number, then click the [...] box that appears you can copy a permalink to that line at that point in history https://github.com/minetest/minetest/blob/cd6bcef6d9f387d43fa8fa34b93722ab0b8ba895/doc/lua_api.txt#L1772

**Comment by apachano** [comment]
I will be putting documentation together pending this discussion https://github.com/minetest/minetest/issues/4815
