### ISSUE TITLE
server console commands default

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3866]
As server admin prefer server console for managing server instead of chatting. Please set default behavior when type to command, instead of chat message. Also slash at begin is not needed imho. When would like admin chat using console will use for example command "say" "chat" or something similar. See how works bukkit, native minecraft server etc... I think server console is for control, not for chatting.

**Comment by everamzah** [comment]
You typed into your minetestserver --terminal window and hit enter before realizing you forgot a slash, huh?

**Comment by hunter688** [comment]
everamzach not understand. I want change server console behavior. Example: Instead write _/kick nickname_ I want write only _kick nickname_. Now when write _kick nickname_, is this parsed as chat message. I want command as default in the server console instead of chat.

**Comment by rubenwardy** [comment]
:+1:

**Comment by 0-afflatus** [comment]
So long as there is an option to use chat `/say` or even `/"` might be acceptable

**Comment by hunter688** [comment]
Any progress after one year?

**Comment by paramat** [comment]
@Ezhh any opinion?

**Comment by Ezhh** [comment]
If by console f10 is meant, big big no.

Otherwise I'm indifferent.

**Comment by hunter688** [comment]
Its about server console, when logged to server, its not anything about client console.

**Comment by Ezhh** [comment]
Thanks for confirming. Many people call the f10 console "console" without clarification.

I'm really indifferent to how it works from the server console because I find IRC commands the most convenient thing for myself. What would be interesting is opinions from people who do/would use the server console.
