### ISSUE TITLE
Make compilation instructions in README.txt more fool-proof

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3868]
Apparantly someone (https://forum.minetest.net/viewtopic.php?f=6&t=14216&p=210739) got confused by these compilation instructions from README.txt:

> Build a version that runs directly from the source directory:
> $ cmake . -DRUN_IN_PLACE=TRUE
> $ make -j <number of processors>

Philani got confused by the “<number of processors>” placeholder. My suggestion to fix this:

> Build a version that runs directly from the source directory:
> $ cmake . -DRUN_IN_PLACE=TRUE
> $ make -j $(nproc)

`nproc` gets the number of processors. It is safe to assume this is available at least for GNU/Linux systems since it is part of the `coreutils` package.

**Comment by MoNTE48** [comment]
make -j $(nproc)+1

**Comment by Wuzzy2** [comment]
No, this would evaluate to something like `make -j4+1` which is a syntax error.

**Comment by MoNTE48** [comment]
@Wuzzy2, yes. I've never done so, usually I use -j32 :) love my amd 8*5.5GHz and the RAM 32.

**Comment by PilzAdam** [comment]
You should not just use all processors that are available. In my case, I have so many cores that I simply run out of RAM when compiling with all of them, which is way slower than compiling with fewer cores.

I'd suggest simply writing `make -j2` and adding a comment that explains that you can change the `2` to whatever you like.

**Comment by sfan5** [comment]
Was fixed
