### ISSUE TITLE
Documentation of formspec coordinates

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#3872]
Practically everyone agrees that formspec coordinates are a mess, but could we at least to try to document them?
Since they are inconsistent between element types, the coordinate system should be ideally written down for every single element.
Like:
- “Uses inventory slot coordinates”
- “Uses blabla coordinates with offset of X”
- Etc.

Related forum thread: https://forum.minetest.net/viewtopic.php?f=47&t=14178

**Comment by kaeza** [comment]
Ideally, ALL formspec elements should use an unified coordinate system, and the client code should go to any lengths necessary to at least approximate the desired coordinates.

This would probably break compat with older clients somewhat, but we could add some kind of version to the formspec. Something like `show_formspec(name, fsname, fs, 2)`, or `version[2]` or something, if there is no such thing already. If this would be added (the version field), it could be done before 0.4.14 to set the ground for future compat.

**Comment by raymoo** [comment]
This would be nice, since I came into issues with the discrepancy between button and image coordinates when drawing trees to a formspec.

**Comment by raymoo** [comment]
If coordinates are unified then there needs to be helper functions so that it is easy to get the button and inventory spacing that we currently get.

**Comment by Wuzzy2** [comment]
Thinking about it, I would go as far and consider the inconsistent formspec coordinate systems a major bug.
Some elements (like `field`) use the inventory grid, like the docs promise. It's documented and straight-forward.

BUT! Other elements (like `dropdown`) use their completely own independent, incompatible and coordinate system, inconsistent with what the docs claim. It is an absolute nightmare to properly align these formspec elements together. Also, this just doesn't make any sense whatsoever.

Does anyone *at least know* how the weird coordinate works?

**Comment by DS-Minetest** [comment]
Related: #8524

**Comment by sorcerykid** [comment]
Here is a quick summary of how positions and dimensions of visual elements are computed by the engine. 

![image](https://user-images.githubusercontent.com/24327224/58972251-bbeed300-8782-11e9-8650-c9ac8d65caf6.png)

The vast majority of elements (including dropdown[], despite what Wuzzy claims above) actually adhere to the same coordinate system, albeit one that is very unintuitive. That is, cells for X and Y values, yet slots for W and H values. The primary outliers are textarea[], field[], pwdfield[], image[], and item_image[].

This screenshot depicts the various inconsistencies, most of which are related to element dimensions.

![image](https://user-images.githubusercontent.com/24327224/58973160-ea6dad80-8784-11e9-88b1-50de3a084a17.png)

![image](https://user-images.githubusercontent.com/24327224/58973188-f8233300-8784-11e9-921f-fd0e19e6a814.png)

**Comment by Wuzzy2** [comment]
@rubenwardy: Since you seem to have been working on formspecs lately: Is this issue still relevant?

**Comment by rubenwardy** [comment]
I don't think it is, as real co-ordinates has been merged

**Comment by Wuzzy2** [comment]
@sorcerykid: How did you create the table? Did you have some code or something?
If yes, it would be nice if you could do the test again in latest dev, to verify the new “real coordinates” actually work. :-)
