### ISSUE TITLE
Incorrectly selected node after node change with node highlighting

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#3873]
![screenshot_20160318_000806](https://cloud.githubusercontent.com/assets/2923554/13864020/9686e2ec-ec9e-11e5-99e5-a6e423405618.png)

To reproduce: place a door, and try to open it and close it multiple times until the bug is triggered. I can only reproduce it with node highlighting. Also, moving the mouse after triggering the bug can fix it, so you should only click the buttons to open and close the door after you selected it (a touchpad is useful for that).

**Comment by yyt16384** [comment]
I have also seen this when using screwdrivers.
