### ISSUE TITLE
Minetest on Mac use openGL 2.1

### ISSUE THREAD

**Issue by FaraoneLele** [minetest/minetest#3876]
On mac minetest besides being a little slow, it works through openGL 2.1, you could fix this and run with opengl4.0 as in other platforms?

**Comment by kilbith** [comment]
It depends entirely on your drivers. Irrlicht already supports up to OpenGL 4.x.

**Comment by nerzhul** [comment]
As said by @kilbith it depends on which opengl version which was exposed by your drivers

**Comment by Calinou** [comment]
More recent OpenGL versions are not necessarily faster. Minetest wouldn't benefit much from using OpenGL 4.x, so we don't use it.
