### ISSUE TITLE
implement a minetest updater

### ISSUE THREAD

**Issue by FaraoneLele** [minetest/minetest#3879]
Please add an automatic updater for minetest, so that when a new version comes we can update it directly from 'app, without having to re-download the whole package every time

**Comment by C1ffisme** [comment]
It's not really that hard... And minetest updates every few months. I'm pretty sure you can download something and install it using a terminal or the Ubuntu Software Center every few months. To get the latest builds, I usually do it every few days if a cool feature comes out. (Such as connecting nodeboxes).

Anyway... I'm sure this is a duplicate issue.

**Comment by Ferk** [comment]
The problem is also that this would basically have to be windows-only.
"Ain't nobody got time for that"... and it's not worth it, imho.

**Comment by PilzAdam** [comment]
Duplicated of #2442

**Comment by rubenwardy** [comment]
That issue is about a notifier, not an updater.
