### ISSUE TITLE
"Warp" effect inside liquids

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#388]
Can be done using a shader, or a FOV change.

**Comment by paramat** [comment]
:-1: Visual distortions are hard on the eyes, FOV change in Minecraft videos is visually unpleasant for me and disorientating. I like the way we can see clearly underwater.

**Comment by rubenwardy** [comment]
I would like to see refraction underwater, but it should be mostly clear water

**Comment by C1ffisme** [comment]
I would like to see the screen get darker when I'm underwater. Currently, going underwater is still as bright as being on the surface, it's just not as blue. 
(in Minetest Game:)
I might also want some 'pollution' particles if I'm in normal water. (Maybe river water is more clean?)

**Comment by paramat** [comment]
Underwater brightness was reduced a lot recently, too much, then increased slightly again.

**Comment by C1ffisme** [comment]
@paramat Yes, but I mean that it gets darker the further you go under-water (to a certain extent).

Example from Minecraft: (I am slowly going down an under-water staircase, 1 block at a time.)
![2016-03-27_15 00 56](https://cloud.githubusercontent.com/assets/9893266/14067587/f7a7aa9e-f42c-11e5-9095-c3442413e905.png)
![2016-03-27_15 01 00](https://cloud.githubusercontent.com/assets/9893266/14067588/f96acc80-f42c-11e5-9e95-472c2d36b63e.png)
![2016-03-27_15 01 03](https://cloud.githubusercontent.com/assets/9893266/14067589/fb3decae-f42c-11e5-9698-26fe739c97f5.png)
![2016-03-27_15 01 06](https://cloud.githubusercontent.com/assets/9893266/14067590/fcde1de0-f42c-11e5-80f7-5a1a7d4f3286.png)
![2016-03-27_15 01 24](https://cloud.githubusercontent.com/assets/9893266/14067591/02993602-f42d-11e5-9e7f-acc9a34435ce.png)

**Comment by ObaniGemini** [comment]
Well it would be needed to check every upper blocks... Is that really needed ?

**Comment by paramat** [comment]
Light level does get darker per node in Minetest, it becomes fully dark blue at y = -15, the post effect colour causes the bluish tint.

**Comment by C1ffisme** [comment]
@ObaniGemini I think it depends on light level, and water only lets some light through.

**Comment by Dragonop** [comment]
:-1:

**Comment by paramat** [comment]
Indeed that's due to post effect colour being more noticeable when terrain goes dark.

**Comment by raymoo** [comment]
Minecraft also has light levels go down 2 levels per water node, if I remember correctly.

**Comment by sofar** [comment]
I'd like to see darker underwater. Shader effects can be (and already are largely) optional, and if someone wants to try making them, I think we should be open to considering them.

**Comment by paramat** [comment]
@Calinou a visual distortion underwater is unrealistic, so why do it? Sight is unchanged underwater. There is only a refraction when viewing underwater structures from above water, but this issue is for altered sight when underwater, which makes no sense.

**Comment by Calinou** [comment]
> @Calinou a visual distortion underwater is unrealistic, so why do it? Sight is unchanged underwater.

While a dynamic distortion (e.g. a continuous FOV change) isn't realistic, Minetest isn't realistic and never was about realism.

> There is only a refraction when viewing underwater structures from above water.

In Minecraft, your FOV is lowered by a constant value while underwater. I'm not really fond of this effect, but it's probably better than nothing.

**Comment by paramat** [comment]
Ok but why have any visual distortion at all? MT is loosely based on the real world. There's simply no reason to do it.

Since this has no dev interest or support in 4 years i think it shold be closed.

**Comment by paramat** [comment]
> In Minecraft, your FOV is lowered by a constant value while underwater. I'm not really fond of this effect, but it's probably better than nothing.

This is a very silly argument for doing something: just because MC does it, for no other reason, even though you don't like it much, and because it's 'better than nothing'.

**Comment by paramat** [comment]
Rubenwardy agrees to a close.

**Comment by rubenwardy** [comment]
Minetest is lacking in the shader department, there's no need keeping an issue open for each one.
Also, this is an old thread yet only has 3 people supporting it.

I suggest keeping track of these sorts of things on the dev wiki like so: http://dev.minetest.net/Discussions/Shaders

**Comment by paramat** [comment]
2 supporting including the author, no dev support, and dannydark has been in active in MT snce 2013.
