### ISSUE TITLE
commands do not work on mac

### ISSUE THREAD

**Issue by FaraoneLele** [minetest/minetest#3880]
the commands on Mac do not work by pressing T, after writing it, nothing happens
![screenshot_20160318_184957](https://cloud.githubusercontent.com/assets/17162630/13887255/05fbdcbc-ed3b-11e5-880c-5e205de46b10.png)

**Comment by Rui914** [comment]
Didn't you press K after writing it?

**Comment by FaraoneLele** [comment]
yes , but it don't work

**Comment by C1ffisme** [comment]
@Rui914 How do you know he is trying to fly???

[Here](http://dev.minetest.net/Server_commands) is the link to a list of commands. You can also try '/help'.

It's best to run commands from the console. Type a '/' or F10 to open it.

**Comment by lisacvuk** [comment]
There may be a space before it (eg. " /home" instead of "/home"). Can you check?

**Comment by FaraoneLele** [comment]
ok I solved the problem, and that if you delete the space between the 'start and then slash him when you write you rebuild. for sistemaro I had to write the command and send it and then take it back and delete the space

**Comment by paramat** [comment]
Can i close the issue then?

**Comment by FaraoneLele** [comment]
yes
