### ISSUE TITLE
Forum link in the mod section of the menu

### ISSUE THREAD

**Issue by DonBatman** [minetest/minetest#3892]
I would like to see a forum section in the mods menu.
Either make it so if the forum like is in the description.txt file then allow to click on it to open in browser or have a button that connects to the forum page if available. Modders could have to put a "forum = http://blahblahblah" in the mod.conf to be able to do it. 

I am not sure of the best way to make it happen but I do think that it would be better then people having to Google it in order to find info.

**Comment by C1ffisme** [comment]
That would be nice. It's bad to have people searching 'Minetest'. I know of an iPhone game named 'Minetest' and it has nothing to do with our game (It's not an illegal fork of our game, it looks pretty different).

**Comment by red-001** [comment]
It might be quite hard to add a cross platform "open in browser" button.

**Comment by 14NGiestas** [comment]
@red-001  maybe the source code of the module webbrowser of python built-in can help or even inspire someone:
```bash
cat /usr/lib/python2.7/webbrowser.py | more
```
[https://svn.python.org/projects/python/trunk/Lib/webbrowser.py](url)

**Comment by rubenwardy** [comment]
> It might be quite hard to add a cross platform "open in browser" button.

Nope: https://github.com/rubenwardy/NodeBoxEditor/blob/master/src/MenuState.cpp#L12-L16

**Comment by paramat** [comment]
:-1: I'm uncomfortable with links to internet in the game. Anyone playing is very likely to already know the forum, so i also feel it's unnecessary.

**Comment by C1ffisme** [comment]
@paramat Technically this isn't "in the game", this is just in the main menu.

Also, maybe your Dad or your friend downloaded this on your computer for you, or you just plain forgot the URL. (.com or .net? Or was it .org?)

**Comment by paramat** [comment]
So? Just do a websearch, it's easy enough. Players are very likely to already know the forum before playing MT, a forum is one of the first things you look at when considering playing a game.

Any core dev support?

**Comment by paramat** [comment]
No core dev support for 2 years, low priority and unnecessary work. Core devs feel free to reopen if you support.
