### ISSUE TITLE
Too big gui - fullscreen mode

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#3903]
Will be possible make configurable size of gui elements?
When play with fullscreen, gui is too big for me. Look at buttons vertical size at first two pictures.

window is 800x600
fullscreen is 1920x1200

Window:
![main-menu-windowed](https://cloud.githubusercontent.com/assets/1410134/13984156/c5134f9c-f0f4-11e5-9450-f63c204ec35f.png)

Fullscreen:
![main-menu-fullscreen](https://cloud.githubusercontent.com/assets/1410134/13984175/dd3f537c-f0f4-11e5-8743-d0d12ac57fa4.png)

In-game window:
![ingame-windowed](https://cloud.githubusercontent.com/assets/1410134/13984190/ee801946-f0f4-11e5-8b06-119e39e540a2.png)

In-game fullscreen:
![ingame-fullscreen](https://cloud.githubusercontent.com/assets/1410134/13984198/fe2d29ce-f0f4-11e5-988e-20aef44e3317.png)

**Comment by DonBatman** [comment]
Go into settings and click advanced. Then graphics - menu - gui scaling.
You can set it there. 1.0 is default

**Comment by hunter688** [comment]
When playing with gui scaling, and set for example to 0.5 - text is unreadable, but boxes are still big. When set to 0.8, text is readable but boxes, gui is stil big.

**Comment by hunter688** [comment]
Looks like gui scaling affect only font, not gui elements...

**Comment by DonBatman** [comment]
I just compiled the latest github on linux and the gui scales with the text. At 0.5 the text is hard to read and the box is small. 
This might be specific to windows build.

**Comment by hunter688** [comment]
Im not using windows. Using linux and compile MT from git. Take look at "Trash:" text and size of slot below. Slot is big, text is small in full screen mode.

**Comment by tchncs** [comment]
Hi, 1980x1200 for me. 
This is (real) fullscreen using minetest-git:

![2016-03-24-214441_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/14030767/a2bfd9b8-f209-11e5-9faf-1a4a7f717b8f.png)
^maybe a bit padding more...

![2016-03-24-214255_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/14030752/8fb9d77e-f209-11e5-81ac-54eae7e00824.png)

**Comment by hunter688** [comment]
Present MT GUI:

![mt-gui-now](https://cloud.githubusercontent.com/assets/1410134/24405804/789b85a8-13c6-11e7-803f-b8caf3d5db2d.png)

Expected GUI (size):

![mt-gui-expect](https://cloud.githubusercontent.com/assets/1410134/24405832/8dd9d8de-13c6-11e7-8ab6-fcb3e290d8d3.png)

**Comment by mnn** [comment]
Trying the game on a 4k monitor and it is awful. :disappointed: Inventory seems to not be scalable by any item in settings (tried hud and menu scaling). Is there any other way to solve this, like some special hidden option?

This is whole window screenshot:
![minetest_broken_gui](https://user-images.githubusercontent.com/1975567/27450205-31fd60cc-578b-11e7-9291-e74aa6b9eb5d.png)

**Comment by hunter688** [comment]
any progress after one year?

**Comment by QwertyCoolMT** [comment]
plan on taking this on if anyone is working on this please get in touch!

**Comment by paramat** [comment]
Seems that the font needs to be scaled up too, not that the GUI is too big.

**Comment by hunter688** [comment]
Hmm 2 years :(

**Comment by rubenwardy** [comment]
gui_scaling effects the GUI, not just fonts
