### ISSUE TITLE
texture packs' screenshot.png is painted over description.txt text.

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3910]
Related, but not the same: #2874

see image:

![](http://i.imgur.com/3QtrsQl.png)

Note the image is over the top line of text.

**Comment by kilbith** [comment]
Text can be moved down here : https://github.com/minetest/minetest/blob/master/builtin/mainmenu/tab_texturepacks.lua#L98

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/c8ff11b417ae2c3a156bcaca819eaeec334c76b5
