### ISSUE TITLE
Idea: Allow cheats, while creating new world.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#3912]
I don't like cheating on singleplayer survival world, in minetest version 0.4.13, player started privileges with: server, teleport, rollback, home, shout, privs, password, basic_privs, interact, give, kick, bring, settime and ban.

Developers, add new feature "Allow cheats" checkbox, while creating new world. Add toggle button, to select 2 gamemodes "Survival Mode" and "Creative Mode", instead of "Enable Damage" and "Creative Mode" checkboxes. If creating new world, without enable cheats, you will starting with privileges: interact and shout. If creating new world with enable cheats on, you will starting with privileges: interact, basic_privs, privs and shout.

**Comment by C1ffisme** [comment]
It sounds nice, although we probably are keeping the creative mode and enable damage as is, unless somebody wants to change that.

(It would be nice to change gamemode in-game).

I support the idea of an allow cheats button, I guess, but couldn't you just... not use them?

**Comment by yyt16384** [comment]
The enable cheats button should control whether singleplayer get most privs unconditionally or only privs listed in `default_privs`, instead of hard-coded lists.

As for the survival mode button, this is not a good idea because people can't play with creative mode off and damage disabled anymore.

**Comment by Ferk** [comment]
Imho, the best would be to allow each game to provide a lua file that contains a custom "new game" menu window defining any custom parameters the game may want.

It doesn't make sense to provide for example a setting for the mapgen when the game is gonna override the mapgen, or settings like creative or enable damage for things like tha tutorial game.

This would also allow for more interesting settings the game could provide.

Celeron55 was experimenting with the menu and mentioned something like this here: https://github.com/minetest/minetest/pull/3818

**Comment by WSDguy2014** [comment]
@yyt16384 Survival mode button should be have same as "Enable Damage" on, but, creative mode is off.

**Comment by yyt16384** [comment]
@WSDguy2014 Maybe I didn't understand it correctly, but with the old setup there are 4 possible combinations, while a survival/creative switch will only give 2.

**Comment by WSDguy2014** [comment]
@yyt16384, should be add `default_privs_survival` with "interact" and "shout"
and also add `default_privs_creative` with "interact", "shout", "creative", "fly" and "fast".
add more `default_privs_extra` with "basic_privs" and "privs", to add extra privs (if you enabled cheats ON), while creating new world.

**Comment by yyt16384** [comment]
@WSDguy2014 Currently singleplayer gets all privs that don't have `give_to_singleplayer = false`, and I think this is OK if enable cheats is on. I don't think we should add separate `default_privs` settings for survival and creative, the `creative` mod in minetest_game is probably a better place if this is wanted.

Also, I believe that `creative` priv is added by mods, so it shouldn't be in default settings.

**Comment by paramat** [comment]
>  If creating new world, without enable cheats, you will starting with privileges: interact and shout. If creating new world with enable cheats on, you will starting with privileges: interact, basic_privs, privs and shout.

This is a very specific choice of privs that suit you, the privs wanted in each mode will differ for other people, we can do this easily in a mod and this is very low priority.
