### ISSUE TITLE
Shaders PRs not possible due to CRLF LF line ending issues

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3913]
See #3887 
When i attempt a merge of a shaders PR the merge fails at the first line, this is apparently due to line ending issues
Reading up on this, there seems to be ways to configure git to correct line endings, but i am not comfortable with implementing this (yet).

**Comment by est31** [comment]
Fixed by 205e38f5b8bd480bbe880db5d30300faea13a465

**Comment by paramat** [comment]
Thanks.
