### ISSUE TITLE
Colored item descriptions

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#3924]
Ability to set item description colors.
[See here](https://forum.minetest.net/viewtopic.php?f=5&t=13796)

**Comment by C1ffisme** [comment]
Sounds reasonable...

While were at it, what about the ability to add extra lines to the description?

(These lines could include descriptions, explanations, enchantments, variables, etc.)

**Comment by lisacvuk** [comment]
Hmm, I thought you can add extra lines already, with "/n"?

**Comment by C1ffisme** [comment]
@lisacvuk Really? I'll have to check...

**Comment by lisacvuk** [comment]
@C1ffisme Of course I'm right :D

**Comment by C1ffisme** [comment]
@lisacvuk I made a discussion about doing something with that for Minetest Game. It could be interesting.

**Comment by lisacvuk** [comment]
First thing that needs to be done is to treat them as characters, rather than lines... Then we should be able to color each character with a specific color.

**Comment by Ekdohibs** [comment]
This could be done at the same time as colored chat I think.

**Comment by Dragonop** [comment]
While you are at it, what about adding a way to change the font size? (if not already there hehe)

**Comment by lisacvuk** [comment]
This actually isn't hard: But it does require rewriting the chat system, a lot of it.

**Comment by beyondlimits** [comment]
related: #1587, #4077
