### ISSUE TITLE
Conductive blocks/nodes

### ISSUE THREAD

**Issue by trukoil** [minetest/minetest#393]
Inspired by the wool group (on minetest_game issue), it would be a good idea to make blocks (node should be the right term?) conductive to mesecon/lv-mv-hv electricity.

The value for the property could be:
0: not conductive
1: mesecon conductive (act like a mesecon wire)
2: Low voltage conductive (act like a Technic mod wire)
...and so on.

Higher voltage conductivity could be usable by lower voltage wires.

**Comment by nerzhul** [comment]
It's not needed in core, and works very well since two year
