### ISSUE TITLE
No light spread at night in lua mapgens

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#3930]
In a dark cave in my 'noisegrid' lua mapgen https://github.com/paramat/noisegrid

![screenshot_20160329_154207](https://cloud.githubusercontent.com/assets/3686677/14112470/aea7075e-f5c6-11e5-9b6a-229fdc5ed8e9.png)

^ In daytime

![screenshot_20160329_154223](https://cloud.githubusercontent.com/assets/3686677/14112475/b37ef476-f5c6-11e5-96f6-226439473c8b.png)

^ Now change time to night

Light sources spread their light in daytime, but change time to night and only the light source itself is lit, there is no light spread.
I guess it wouldn't affect core mapgen lava because that is always flowing and therefore updating lighting. However if core mapgen ever had glow ore these would have this problem, so i would consider this essential.
My mod has paramtype = "light" for these light sources, essential for spreading light in daytime.

**Comment by C1ffisme** [comment]
This is pretty interesting. So mapgen is affected by the time it is generated? Very peculiar.

Is it possible to just simulate daytime underground to fix this? (Forgive me if I'm just being stupid.)

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/0338c2eb91ca2ba19551aaa23bbfb46552cee9ac

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/0338c2eb91ca2ba19551aaa23bbfb46552cee9ac

**Comment by paramat** [comment]
Confirmed fixed by #3932
