### ISSUE TITLE
Block loading feels much more sluggish as of current dev version

### ISSUE THREAD

**Issue by kwolekr** [minetest/minetest#3931]
It might be a matter of perception, but the current development HEAD feels like block loading is much slower than previous versions.  Should perform regression testing to verify if this is an issue or not, before release.

**Comment by Fixer-007** [comment]
It looks good to me, I can see only big stuttering as usual. Nothing unusual.

**Comment by MoNTE48** [comment]
@kwolekr, I think you're right. Just download the game became a little longer (25%?).
You can do the test with the same seed and subgame.

**Comment by gregorycu** [comment]
I will do a spot of profiling to try and see what the diff is.

**Comment by celeron55** [comment]
You need to describe the issue better.

One thing that I have noticed is that the client_mapblock_limit of 5000 by default limits the effective loading range to something like 140 nodes, after which the server continues to send stuff but the client immediately deletes the blocks that were just sent, causing 100% processing with no useful result.

(My farmap branch attempts to fix it among other things)

**Comment by gregorycu** [comment]
It's hard to tell what the slowness is, if any. However, profiling did reveal a performance regression that I've fixed: #3937

**Comment by Fixer-007** [comment]
BTW, It was observed on debug build

**Comment by kwolekr** [comment]
Fixed with https://github.com/minetest/minetest/commit/f9a90383e14a02ab0e66e5d5c36940a4ffb54502
