### ISSUE TITLE
Regression after merging of PR #3932

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3935]
After PR #3932 was merged I've noticed lighting in caves near -50, on this level, but not everywhere. This should appear at least on valleys mapgen and mapgen 7 (and probably everywhere).

Screenshots:
https://i.imgur.com/djdXcA3.png (valleys)
https://i.imgur.com/S2ucbo6.png
https://i.imgur.com/3DTCXOf.png
https://i.imgur.com/Rlu1o5L.png (mgv7)

@kwolekr @paramat

**Comment by paramat** [comment]
Now fixed? Please test.
