### ISSUE TITLE
Hiding nametags stopped working

### ISSUE THREAD

**Issue by est31** [minetest/minetest#3939]
It was reported on IRC that hiding nametags from server side (via the alpha = 0 method) has stopped working after commit c3b279750ece0b5144bf8e973d55108347462223 .

**Comment by kilbith** [comment]
I can confirm (as one of my mod [uses it](https://github.com/minetest-mods/spectator_mode/blob/master/init.lua#L63)) that hiding nametags with this method has never worked before and after https://github.com/minetest/minetest/commit/c3b279750ece0b5144bf8e973d55108347462223.

**Comment by est31** [comment]
What about directly on b600bc30a9fbd92800dabad14a38f28f0ccdd28e ?

**Comment by kilbith** [comment]
Hard resetting to https://github.com/minetest/minetest/commit/b600bc30a9fbd92800dabad14a38f28f0ccdd28e does seem to fix the issue (nametag is no longer translucent black).

But https://github.com/minetest/minetest/commit/c3b279750ece0b5144bf8e973d55108347462223 is not the troublemaker for sure.

**Comment by est31** [comment]
Well then at least there was a time when it worked... sigh, seems it gets broken so often.

**Comment by est31** [comment]
Okay merged the fix: b8ac7b80e6031f1322b76d638256f8e4a52e89d1

It was a regression of c3b279750ece0b5144bf8e973d55108347462223 after all

**Comment by kilbith** [comment]
I'm dead sure than not, I've seen that before.
