### ISSUE TITLE
Stackable node number definable by minetest.conf file

### ISSUE THREAD

**Issue by trukoil** [minetest/minetest#394]
I don't know if open this issue here or in the minetest_game, but i found this property in "/builtin/item.lua" file, so it's possible to have the limit of stackable node/item in inventory/chests definable in the minetest.conf file?

**Comment by paramat** [comment]
:-1: I agree with PilzAdam.

**Comment by rubenwardy** [comment]
I think the power should be with subgame creators, and not necessarily users. Users can become subgame creators, ofc.

**Comment by 0-afflatus** [comment]
> The stack_max value should be defined by the game creators and not by the users.

Absolutely.

**Comment by est31** [comment]
Agree here, this is something the game should decide. The subgame still can allow the user to configure it.
