### ISSUE TITLE
Config file on XDG dir on Linux

### ISSUE THREAD

**Issue by trukoil** [minetest/minetest#395]
The config file on Linux could use the XDG specification:

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by nerzhul** [comment]
I approve the change to XDG_USER_DIR and .cache dir.

**Comment by nerzhul** [comment]
Duplicate with https://github.com/minetest/minetest/issues/864

**Comment by eli-schwartz** [comment]
Repeating my comment from https://github.com/minetest/minetest/issues/8151#issuecomment-460102567 (which is closed as a duplicate):

Failure to follow the XDG Base Directory specification **or its OS-specific adaptations** results in software which is just as broken on macOS **and** Windows as it is on Linux.

On macOS, `XDG_CONFIG_HOME` maps to `~/Library/Preferences/`, `XDG_DATA_HOME` maps to `~/Library/Application Support/`, and `XDG_CACHE_HOME` maps to `~/Library/Caches/`.

On Windows, `XDG_CONFIG_HOME` and `XDG_DATA_HOME` are not separated, as both are in `%APPDATA%`, but `XDG_CACHE_HOME` must be in `%LOCALAPPDATA%` to prevent roaming across network shares (it does not specify when you can clean it up though).

Linux of course provides separate directories for all three (just like macOS), and goes even further by allowing them to be relocated via environment variables. But I hardly see why the lack of cross-platform support for overriding `XDG_*` should cast doubt on the usefulness of a program intelligently deciding where to put files according to the well-documented, preferred OS-specific locations.
