### ISSUE TITLE
Allow all orientations for wallmounted nodeboxes/meshnodes

### ISSUE THREAD

**Issue by qwrwed** [minetest/minetest#3951]
When using a screwdriver on a node with the "wallmounted" paramtype2, only 6 orientations are available instead of the 24 available for other nodes. Normally this isn't an issue, but when trying to use a screwdriver to rearrange a sign/ladder/Homedecor shutter etc it becomes noticeable.

**Comment by VanessaE** [comment]
In particular with the shutters in homedecor, this "noticeable" can result in the model and its selection box being inexplicably separated to opposite ends of the node space, at some rotations.

**Comment by sofar** [comment]
This needs a modification in the screwdriver. It's basically a new rotation handler.

**Comment by est31** [comment]
Why not use the full 24-rotation param2type then?

**Comment by sofar** [comment]
Possible. I just know that the screwdriver mod explicitly currently checks for ```paramtype2 == facedir``` right now, as I added that myself a while back to prevent crashes.

**Comment by sofar** [comment]
Should this be moved to minetest_game?

**Comment by VanessaE** [comment]
No, because unless the screwdriver is creating an alternate, broken node from the original, it's gotta be the engine screwing up the positioning of the selection box (assuming my code for homedecor's shutters is good).

**Comment by paramat** [comment]
> When using a screwdriver on a node with the "wallmounted" paramtype2, only 6 orientations are available instead of the 24 available for other nodes.

Then use 'facedir' for that node. 'wallmounted' nodes only have 6 orientations, that's because they're wallmounted, duh :)
