### ISSUE TITLE
Suspend breaks audio and issues OpenAL error flood

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#3954]
Suspending the computer while the game is open will stop audio from working and issue a flood of identical errors from OpenAL until the game is closed (100+/second).

```
AL lib: (EE) ALCplaybackAlsa_mixerProc: start failed: File descriptor in bad state
```

IIRC Xonotic also has this issue, so possibly an upstream issue.

**Comment by 0-afflatus** [comment]
I can't precisely confirm because I routinely turn off xscreensaver and power management, but for this sort of reason. I think this could be part of a wider sound issue - I've been killing off pulseaudio a lot to stop lag. I'll try to come up with a less vague comment.

**Comment by nerzhul** [comment]
i will test it to verify if it's always valid
