### ISSUE TITLE
Death on login [commit with regression identified]

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#3955]
I've experienced death on login on two heavily modded server that uses recent minetest and minetest_game (Extreme Survival Minetest and Xanadu). Many players already confirmed this on both servers.
You login, instant death - spawn, you loose your bones.
Bug appeared in this commit: https://github.com/minetest/minetest/commit/8787d2e7e9671f3b5930ca9c41c6e0867b8a5a54

P.S. Confirmed by @Dragonop and me (via nore's method) on clear minetest.

**Comment by paramat** [comment]
Please can you bisect this to find the exact commit that causes it?

**Comment by paramat** [comment]
Possibly related #3483

**Comment by paramat** [comment]
@tenplus1 any chance you could update to absolute latest engine and game and try to reproduce?

**Comment by paramat** [comment]
IRC discussion http://irc.minetest.ru/minetest-dev/2016-04-03#i_4574119

**Comment by Ekdohibs** [comment]
Could reproduce it by adding ```minetest.register_on_generated(function() os.execute("sleep 2") end)``` in a mod, simulating a slow mapgen. I die each time on login after this is added.

**Comment by Fixer-007** [comment]
After some fast testing with Dragonop I think bug was introduced between 20.09.2015 and 15.10.2015 (including them)

**Comment by Fixer-007** [comment]
My suspects:
https://github.com/minetest/minetest/commit/8787d2e7e9671f3b5930ca9c41c6e0867b8a5a54
or
https://github.com/minetest/minetest/commit/596484da4fcd301e597a851a9a54b6dc276a286a

**Comment by Dragonop** [comment]
You can reproduce the bug in any mapgen that takes at least two seconds to generate the map for you. Apparently the cause of death is fall damage.

**Comment by paramat** [comment]
Probably these #2784 #3076

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/3483#issuecomment-205075816

**Comment by paramat** [comment]
This might be due to how players are spawned, if i increase spawn point by 1 node, to be just above ground, it might help.

**Comment by Fixer-007** [comment]
By using nore's method I've identified the exact commit with this "die on login" regression, and it is this: https://github.com/minetest/minetest/commit/8787d2e7e9671f3b5930ca9c41c6e0867b8a5a54

:)

**Comment by sofar** [comment]
I'm not entirely convinced it's due to slow mapgen. The new farmap can kill you at already generated chunks when you just start the server as well.

**Comment by Ekdohibs** [comment]
@sofar: the problem could just be that the server is being too slow...

**Comment by tenplus1** [comment]
I'm sure there was a setting inside minetest.conf that would force load an area before placing player on server and that way this glitch wouldn't happen.  It may be related to the falling on connect glitch where flying players have been noted to fall while connecting.

**Comment by paramat** [comment]
Yes it's not slow mapgen because it happens to players in already generated worlds.
Zero gravity fixes this, so player's velocity is being icreased by gravity before they're properly interacting with the world.
```
2016-01-12 20:39:39: VERBOSE[Server]: ServerEnvironment::addActiveObjectRaw(): Added id=1; there are now 1 active objects.
2016-01-12 20:39:39: VERBOSE[Server]: Server: Sending TOCLIENT_MOVE_PLAYER pos=(270,150,1480) pitch=0 yaw=0
2016-01-12 20:39:39: ACTION[Server]: singleplayer [127.0.0.1] joins game. 
2016-01-12 20:39:39: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2016-01-12 20:39:42: WARNING[Server]: active block modifiers took 369ms (longer than 200ms)

2016-01-12 20:39:43: WARNING[Server]: active block modifiers took 433ms (longer than 200ms)
2016-01-12 20:39:44: VERBOSE[Main]: OpenALSoundManager::maintain(): 0 playing sounds, 34 sound names loaded
2016-01-12 20:39:44: ACTION[Server]: singleplayer damaged by 84 hp at (27,15,148)

2016-01-12 20:39:47: WARNING[Server]: active block modifiers took 521ms (longer than 200ms)
2016-01-12 20:39:51: WARNING[Server]: active block modifiers took 545ms (longer than 200ms)
2016-01-12 20:39:54: WARNING[Server]: active block modifiers took 319ms (longer than 200ms)
2016-01-12 20:39:58: WARNING[Server]: active block modifiers took 466ms (longer than 200ms)
```

**Comment by paramat** [comment]
From IRC:
12:33 nore       I found how to fix the die on login bug
12:33 nore       I'm on my phone right now, so I can't test it
12:34 nore       but it should be enough to set speed_f to zero when we return early from collisionMoveSimple
12:35 nore       in the test that was added in the commit that broke it
12:36 nore       if someone wants to test that, feel free, else I will do that tonight

**Comment by est31** [comment]
While #3965 (hopefully) will fix the dying bug, is there an explanation for why there are no bones?

**Comment by Ekdohibs** [comment]
@est31 a possible one would be that the player is in a protected area, I don't know what happens if it is theirs though.
