### ISSUE TITLE
F10 console covers the entire viewport/screen

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#3956]
Using git commit 01ae43c, compiled in Release mode.

When using 't' or '/' to open the chat console, only 10 or so lines' worth of space is taken at the top of the window.  Using F10 brings up a console that takes the entire window, when it used to be something like half the window height.  All three methods of opening the console should result in the same space taken, and a whole window's worth is too much in any case.

Secondary to that, the console is drawn underneath/behind the F5 debug graphs, if they're currently displayed, which looks...ugly.  (example: https://cloud.githubusercontent.com/assets/1733537/14235451/bcb55f4e-f9cc-11e5-8143-e630e5d47b6e.png )

**Comment by ShadowNinja** [comment]
This is intentional.  The chat isn't supposed to come very far down for `t`/`/` so it's not distracting.  It's supposed to open all the way for F10 so that you have plenty of room for looking back in the chat log (because if you don't intend to scan far back in the log it's easier to just use `t`).

**Comment by est31** [comment]
Nah, its good to have differently sized consoles.

**Comment by VanessaE** [comment]
Perhaps but the whole screen?  That's just too much.

**Comment by 0-afflatus** [comment]
I really like the fact that F10 covers the whole screen. But perhaps this is an argument for configurability?

**Comment by wilkgr76** [comment]
@0-afflatus Agreed. This should be configurable.

**Comment by Zeno-** [comment]
I am re-opening this for discussion

**Comment by Zeno-** [comment]
If I am running the game in fullscreen mode then the console is 2560x1440... that's a bit overboard IMO

**Comment by tenplus1** [comment]
Does this look any better: http://i64.tinypic.com/1zzmhjt.jpg

**Comment by 0-afflatus** [comment]
@VanessaE is there any practical reason why it's too much?

In all seriousness, I find it really useful to have F10 full screen, not only for displaying the full output of verbose commands, but also to be able to track conversations when it's busy. On a busy server like TARDS, for example, this is almost essential for wading through a sea of CapsLock noise.

This feature has made my life as an admin considerably easier and I would find it frustrating to have it limited due to aesthetic considerations. That said I'd be in favour of configurability.

The one thing that really needs fixing is that it needs to consistently open at the tail of the conversation.

**Comment by tenplus1** [comment]
@0-afflatus - Agreed, having to scroll down to the end of the conversation is annoying as hell...  Also a configurable console screen would be very handy (top and bottom limits)

**Comment by VanessaE** [comment]
Well like Zeno, I have a large monitor (1600x1200, 20 inches).  Gaming on big screens is fun, but seeing a ginormous console open up and cover everything ... isn't.  It's overkill. :smile:  Now imagine doing that when MT is spread across multiple screens or displayed on a large-screen TV or projection system (I don't do either of these, but I'm sure some people do).

tenplus1, your screenshot is better, but honestly, having no upper/lower borders on your version makes it look hacked-in, unfinished.

Consider OpenArena, and for that matter its predecessors going all the way back to Doom 1993.  Approximately a half-window-sized console by default, with a dividing line at the bottom of it.  Modern games seem to tend towards either that or a pop-up window not unlike a regular shell/terminal program.

If there's a reason to be different from this, I don't see it.

**Comment by kilbith** [comment]
When you open the console, it is certainly to do something not related with playing. Thus the screen-filled console makes completely sense.

**Comment by Fixer-007** [comment]
I like it this way, but I dislike one when pressing "T", it hides game coordinates :/

**Comment by Calinou** [comment]
I like how the chat console takes only a small portion of the screen, but this should be configurable (`console_chat_height` probably).
But the F10 console height should also be configurable (`console_height` probably), most games with a console can do it already.

**Comment by est31** [comment]
There should be two settings, with configurable percentage of the screen size.

**Comment by lightonflux** [comment]
**If** we add a configurable height because of large monitors, then we need a width as well. Usually the height is not the problem to read, but the width, because all text is aligned to the left which can be far away. For the same reasons many websites have max-width.

**Comment by paramat** [comment]
'F10' is intended to be full screen and this is useful and i feel should be kept, however perhaps the text width could be settable to avoid overly-long lines on big monitors (long lines can become harder to read).
'T' or '/' is the partial view and perhaps could have a settable vertical size.

**Comment by paramat** [comment]
I support a setting for how many lines to display with F10, as a huge screen of text would be too much for me too. This is causing headaches for people.

**Comment by Zeno-** [comment]
Apparently Ezhh is working on this. I'd support a PR that adds a setting for sure (I don't like the full screen/window f10)

**Comment by Zeno-** [comment]
https://github.com/minetest/minetest/pull/5136

**Comment by ShadowNinja** [comment]
0c9189d10989f85cd5148107b643dc17a49c06ff
