### ISSUE TITLE
/kill [player] command

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#396]
Would allow suicides and killing other players, would require "ban" privilege.

**Comment by nerzhul** [comment]
we already have /sethp and /kick command is this issue useful ?

**Comment by Calinou** [comment]
No, since you can just `/sethp <player> 0`.

**Comment by 4aiman** [comment]
Aha, and miss the key and set HP to 9.

Anyway... I don't mind this being closed.
This isn't something one can fail do on his own in Lua.
