### ISSUE TITLE
damage_per_second spatial calculation highly inaccurate

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#3960]
environment.cpp line 2512+ reads that damage_per_second from blocks is calculated by taking 3 points in the body and seeing if these three positions are inside any nodes.

Effectively this means you can stand at 4/16 of the center of the node away until you start to take damage, because even through almost half your body is inside the lava, the positions that are checked are not in the lava block.

We should probably check in a few more points on the player position than just these 3.

**Comment by tenplus1** [comment]
Will this slow down game any by checking additional points ?

**Comment by sofar** [comment]
Fixed by #3961

**Comment by sofar** [comment]
@tenplus1 highly unlikely. All the node info should already be in the cache at that point, since the rest of the collision code pretty much hits all of it as well.

**Comment by Longor1996** [comment]
I'm not a contributer to this project (just watching the development), but:
Wouldn't it be easier to check if a player's bounding box is intersecting with a node?
Do players and nodes even have bounding boxes?
