### ISSUE TITLE
do not show box when looking to another player

### ISSUE THREAD

**Issue by hunter688** [minetest/minetest#3963]
![Players](http://minetestbb.suret.net/playertexture.png)

I think will be better without box.

**Comment by tenplus1** [comment]
If it helps, pressing F1 to turn off HUD removes collision boxes also.

**Comment by kilbith** [comment]
Already addressed here : https://github.com/minetest/minetest/pull/1645

**Comment by est31** [comment]
Still no reason to close it, for the case somebody intends to.

**Comment by C1ffisme** [comment]
Generally, if you want a good screenshot, you should:

* Turn debug info off (Toggle Debug info with F5)
* Turn HUD off as tenplus1 said. (F1)
* Turn off chat. (F2)
* If you are in singleplayer, you could also quickly turn on a few settings (Fancy Leaves, 3D Clouds, etc.), though I don't recommend this for anyone with an older computer.

Just a bit of help if you want good screenshots. :wink:

**Comment by hunter688** [comment]
screenshot is only informative...

I do not want disable hud, I only want disable ugly box around the player

**Comment by est31** [comment]
Nodes have such a box too and nobody is complaining.

**Comment by ObaniGemini** [comment]
That's false, many people were complaining about those.
https://github.com/minetest/minetest/pull/1645 Just needs rebase and reviews and this issue could get closed.

**Comment by rubenwardy** [comment]
> Why is this screenshot from 0.4.4??

It's an old screenshot of redcrab's server.

**Comment by C1ffisme** [comment]
@rubenwardy Ah, I see.

Wait... Didn't redcrab have about a million servers? (I remember browsing through the forum a long time ago, although not getting an account.)

**Comment by tobyplowy** [comment]
Yes please remove These Black boxes they ar annoying and Look bad!

**Comment by C1ffisme** [comment]
> Yes please remove **t**hese **b**lack boxes they ar**e** annoying and **l**ook bad!

@tobyplowy If you can't spell, just use a :+1: or a :-1: to show your reaction.

**Comment by Fixer-007** [comment]
Yes, please make this box disabled by default.

**Comment by ObaniGemini** [comment]
|||((({{{[[[===>>>>>> #1645 <<<<<<]]]}}})))|||

**Comment by hunter688** [comment]
@ObaniGemini 2014... hmmm

**Comment by sofar** [comment]
#3992 is a rebased version of #1645

**Comment by paramat** [comment]
#3992 is merged.
