### ISSUE TITLE
Lua Sound API: Add a time range option

### ISSUE THREAD

**Issue by 14NGiestas** [minetest/minetest#3966]
Just a feature request for the Lua API: add an option to just a region of an audio file.
Reason:
Sometimes seems necessary... like music mods and such...

``` lua
minetest.sound_play("testmod_foobar", {
   to_player = "foo",
   gain = 2.0,
   region = {1*60, 2*60},
})
```

region would be measured in seconds.

**Comment by everamzah** [comment]
minetest.sound_play() returns a handle id, and you may use minetest.sound_stop() to cancel it after some time.

**Comment by rubenwardy** [comment]
> minetest.sound_play() returns a handle id, and you may use minetest.sound_stop() to cancel it after some time.

That won't work accurately due to server latency/lag.

**Comment by 14NGiestas** [comment]
The point it's: The current API does not provide a method for play specific interval of a sound file.
For a "real life" example... In my time_travel mod I can't start the stream of audio at the point where the player had stopped previously in a video stream...

**Comment by C1ffisme** [comment]
The problem is that sounds have to be done server side.

This isn't too much of a problem in singleplayer, but in multiplayer, this makes all the difference. Playing a different sound to all the players on a server can be... unspeakably laggy.

**Comment by 14NGiestas** [comment]
[note: I'm actually reading the source and trying learn some C++ (not very successful as expected)]
Why don't make this client side?
And isn't a different sound: it's the same sound but starting from a specific point...  
the data (as far I can see, pls correct me if not) is already on client side... the client just receive a packet with the command TOCLIENT_PLAY_SOUND and then start to read and play the sound (client-side) so, 
why the packet don't carry the "region" information and then make the client do all the work?

**Comment by rubenwardy** [comment]
That's how it shound work if done currently, using `sound_stop()` is not good.

**Comment by C1ffisme** [comment]
@14NGiestas The problem is that there is no client side lua modding.

If we could have the client detect nearby nodes and entities, and play sounds based on those, the sound wouldn't lag as much. But we can only mod on the server side, which means that the server has to play every single sound, as well as send it to all clients, rather than just the ones that can hear the sound.

**Comment by rubenwardy** [comment]
> @14NGiestas The problem is that there is no client side lua modding.

Not a problem for this usecase.

>  as well as send it to all clients, rather than just the ones that can hear the sound.

You can send a sound to individual players.

**Comment by C1ffisme** [comment]
@rubenwardy You can send a sound to individual players, but as far as I know, the data still has to be sent to other clients [citation needed].

Even then, it still has to be managed by the same server that is managing the sounds for every other client. (Ambience, TNT, etc.)

**Comment by 14NGiestas** [comment]
> rubenwardy You can send a sound to individual players, but as far as I know, the data still has to be sent to other clients [citation needed].
This isn't done on loading time @C1ffisme ? The sound bytes aren't passed every time. Just what file must be played. [citation: error 404]
>Even then, it still has to be managed by the same server that is managing the sounds for every other client. (Ambience, TNT, etc.)
And...?

**Comment by rubenwardy** [comment]
You can pretty much ignore everything that c1ffisme says

**Comment by C1ffisme** [comment]
I'm sorry if I'm spitting nonsense. Some of it is just my vague assumptions.

**Comment by 14NGiestas** [comment]
LOL @rubenwardy. 
@C1ffisme you're forgiven. Some of mine is a kind vague. Whatever.

**Comment by HybridDog** [comment]
How about adding a impulse tracker api, music can be send as .mo3 file and it can contain some sounds and play them from specific positions with specific pitch, can't it?

**Comment by everamzah** [comment]
Yeah! https://github.com/minetest/minetest/issues/3878

**Comment by paramat** [comment]
:-1: Seems low priority, use separate audio files for each section you want tto play?

**Comment by HybridDog** [comment]
paramat, using separate sections doesn't help, all sounds are sent at once to the player who connects and doesn't have them in their disk cache yet.

**Comment by paramat** [comment]
Ok good point.

**Comment by paramat** [comment]
Folding #6714 into this as this can provide that.

**Comment by BluebirdGreycoat** [comment]
#6719.

This only implements offset. I couldn't find an easy way to stop sound after OpenAL gets to a certain point in the buffer. If someone knows the right function please mention it.

**Comment by paramat** [comment]
Any core dev support?

**Comment by paramat** [comment]
No core dev support for 2 years. Core devs feel free to reopen if you support.

**Comment by HybridDog** [comment]
Please add the "Closed but PRs may be accepted"  label.
