### ISSUE TITLE
Add sprinting

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#397]
I suggest adding sprinting ability to the minetest engine.
Here's the concept: Custom Hud + hunger mod + sprinting ability + some mobs.
Now for the "What's the purpose?" question:

The first one (a custom HUD) needed to graphically show that the player has food-o-meter, 'cause for now all that the hunger mod can do is send the player a message using Scripting API. That's not very nice, 'cause the player do not know how much time he has.

Hunger mod should be in the dependencies of the "stamina" mod or should be edited to include the sprinting ability: if the player is hungry he shouldn't be able to sprint. That's natural.

And here's the fun part:
In the minecraft sprinting is useless. There are NO mobs with velocity greater than that of the player. In Minetest all could be different. I suggest making it possible to create a rare powerful mob who can walk faster then the player. So, If it sees the player, it would chase him. And the sprinting would be one and only possibility to avoid him catch the player. But if the player is hungry he couldn't run and MUST engage with that mob. It's the matter of a few variables/constants to make that mob strong enough for any player want to avoid him.

To make all that possible I suggest adding a sprinting mode. To double press the forward key to sprint would be handy too. To stop sprinting and continue to walking when the player have bumped into the wall or entity would be natural. To stop sprinting in/under the water and on the sand/leaves would be natural too.

**Comment by paramat** [comment]
:-1: Can be done in mods now with per-player physics.
@4aiman still want this open?

**Comment by rubenwardy** [comment]
Due to having to check for keyboard input every tick (if E is pressed), Sprinting is rather more inefficient than it should be. But it should be solved by making it better for mods to do this, rather than adding it to core.

**Comment by ObaniGemini** [comment]
I say :+1: too. This should be better handled but not by adding it as default in the engine.

**Comment by rubenwardy** [comment]
:-1: to having sprinting builtin, but it a less laggy way to do it would be good.

**Comment by C1ffisme** [comment]
> In the minecraft sprinting is useless.

Not to be offtopic... But sprinting is what makes sure I don't go insane because of impatience.

Anyway, I'm going to agree that this should go in Minetest Game, not in Minetest, since other games that use racecars/make you into a snail/something else wouldn't want you to sprint.

**Comment by 0-afflatus** [comment]
:-1:

**Comment by 4aiman** [comment]
@paramat I'm closing this one. 
I'm sure sprinting will be requested by someone else later.

**Comment by everamzah** [comment]
Personally I just double: movement_acceleration_default, movement_acceleration_air,  movement_speed_walk, movement_speed_crouch, movement_speed_climb, and movement_speed_descend.

Then I override physics on player join to half (speed=0.5), and while sprinting override physics to 1.  This solves it for me, and one can sprint with no stuttering/resetting even without the fast priv.

**Comment by rubenwardy** [comment]
Clever. How much of a problem is having to check for E or double W?

**Comment by everamzah** [comment]
No problem, tho I never used the double-tap method.  Only AUX1, and I hear mobile users don't have AUX1.  Anyway, it's fine, just subject to lag (start/stop of sprint action).
