### ISSUE TITLE
Select crafting recipes without groups first

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#3972]
There could be following situation:
default adds this recipe:

```
minetest.register_craft({
    output = 'default:stick 4',
    recipe = {
        {'group:wood'},
    }
})
```

A mod called smd adds its own wood node and its own stick; the craft recipe to get the stick from the wood doesn't work:

```
minetest.register_craft({
    output = 'smd:stick 4',
    recipe = {
        {'smd:wood'},
    }
})
```

smd:wood should still be in the wood group (for crafting default chests etc.) but smd:stick should be the output when crafting sticks from it, not default:stick.

l think crafting should be changed, it should get a table of all possible recipes and then it should select the recipe which fits best (which has the lowest amount of "group"s).

Edit: group recipes are already prioritised due to the craft hash type selection. The problem happens for shapeless recipes.

**Comment by C1ffisme** [comment]
@HybridDog 
> not defaul**t**:stick.

Sorry, thought I might as well correct an error.

**Comment by DonBatman** [comment]
I like the idea!

**Comment by HybridDog** [comment]
@C1ffisme thanks, l didn't notice this typo

**Comment by est31** [comment]
Have you actually tried that example? I don't think it should have the behaviour you told.

Crafting indeed first tests for node name only matches, and only then looks for craft recipes with groups in them.

Take this as an example:

```lua

minetest.register_node("test:wood", {
	description = "Wood",
	tiles ={"default_wood.png"},
	groups = {snappy=2,wood=1,choppy=2,oddly_breakable_by_hand=2},
})
minetest.register_node("test:fancy_wood", {
	description = "Wood(fancy)",
	tiles ={"default_wood.png"},
	groups = {snappy=2,wood=1,choppy=2,oddly_breakable_by_hand=2},
})
minetest.register_craftitem("test:fancy_stick", {
	description = "Stick",
	inventory_image = "default_stick.png",
})

minetest.register_craft({
	output = 'default:stick 4',
	recipe = {
		{'group:wood'},
	}
})

minetest.register_craft({
	output = 'test:fancy_stick 4',
	recipe = {
		{'test:fancy_wood'},
	}
})
local function d(name)
	local v = minetest.get_craft_result({
		method = "normal",
		width = 1,
		items = { name },
	})
	print(dump(v.item:to_string()))
end
d("test:wood")
d("test:fancy_wood")

```

It prints

```
Crafting "test:wood" gives "default:stick 4"
Crafting "test:fancy_wood" gives "test:fancy_stick 4"
```

So, everything is fine, no?

**Comment by HybridDog** [comment]
sorry, you're right, est31

l'm wondering why l thought that l had such a problem with some wood of the nether mod…

**Comment by sofar** [comment]
No, that's incorrect. The order in which crafting recipes is inserted into the list makes it seem like it works, but if you reverse the order of the two craft recipes, you get:

```
"default:stick 4"
"default:stick 4"
```

because of this, mods can't make more generic recipes for ones that already exist, since the group-based recipes need to be inserted first for this to work.

Please re-open.

**Comment by est31** [comment]
Ah right, sorry.

**Comment by est31** [comment]
??

**Comment by beyondlimits** [comment]
related: #2881

**Comment by sofar** [comment]
This is entirely fixable btw. All that needs to be done is to add a `bool` flag to the recipe lookup function so that it can be called twice. Once looking for exact recipes (ignoring groups) and once looking for recipes while attempting to match groups.

Since the first call is a subset of the functionality of the second call, it shouldn't even be that much code.

**Comment by HybridDog** [comment]
I think that it can be fixed by adding priorities to the recipes:
cooking = fuel = shaped > shaped and groups > shapeless > shapeless and groups > toolrepair > no recipe
When traversing the recipes, the recipe with highest priority is preserved.
https://github.com/minetest/minetest/blob/ad75dba87bb39de2c3d12b228bf113abe740c942/src/craftdef.cpp#L911
