### ISSUE TITLE
Add brightness option into minetest.conf

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#398]
So anyone could change the overall brightness level inside the game without having to change the brightness of their displays.

**Comment by codeandfix** [comment]
Most important change! Or add a "Gamma" selector like in ego-shooters.

**Comment by 4aiman** [comment]
How come this was labeled with ```won't add``` w/o anyone responsible? (i.e. I can see who added ```Feature Request``` but can't see who has added the ```won't add```) O_o

Anyway, I'd like to know the reason for this.
Why not?
Is it too difficult to implement that everything would be a little bit brighter *visually*?
(I.e. I'm *not* asking to add brightness levels but merely add a multiplier to a "basic" light level)

**Comment by PilzAdam** [comment]
This: https://github.com/minetest/minetest/blob/master/minetest.conf.example#L121L124 ?

**Comment by 4aiman** [comment]
> This: https://github.com/minetest/minetest/blob/master/minetest.conf.example#L121L124 ?

Yes, but with more "spread". 

It would be nice to be able to use 1.0 for the "default" value, 0->1.0 for fractions and 1.0+ to add gamma. 

Even with the current possible values, 1.8 is not even a middle. 2.0 is.
But sometimes even 3.0 is not enough. The screenie below shows a midnight with gamma set to 3.0
 
![screenshot_20150731_194811](https://cloud.githubusercontent.com/assets/2913210/9012397/19743c14-37bd-11e5-8c22-e9e26a5639e0.png)

Overriding day-night ratio with 0.2 (instead of 0) will give me the amount of light I'd like to see as 0 (I can see at least something).
![screenshot_20150731_195042](https://cloud.githubusercontent.com/assets/2913210/9012429/6ea2c8e0-37bd-11e5-8a2c-65d4ac9282c8.png)

0.4 is even more preferable. For a dim monitor (~30/100 brightness and contrast).

The point is *not* to shrink the range of min<->max light, but to be able to **considerably** multiply the levels of both.

**Comment by PilzAdam** [comment]
>But sometimes even 3.0 is not enough.

"lower numbers are brighter"

**Comment by 4aiman** [comment]
Well, 1.0 is better, but not *that* better good either:
![screenshot_20150731_201818](https://cloud.githubusercontent.com/assets/2913210/9012922/48d3eb68-37c1-11e5-9e71-03d43b406407.png)

A night is still a night.
A day is no brighter that it was...

**Comment by paramat** [comment]
@4aiman closing, you could always open a new issue for a wider range for gamma.
