### ISSUE TITLE
Standardizing API naming and calling conventions.

### ISSUE THREAD

**Issue by kaeza** [minetest/minetest#3980]
I just brought this up on the [development channel](http://irc.minetest.ru/minetest-dev/2016-04-10#i_4580816), and kwolekr/hmmmm suggested I make this issue.

Basically, there are several inconsistencies in the API, from naming conventions, to function arguments, to function return values, that make modding a pain, as you can't remember which form is used and need to constantly refer to the `lua_api.txt` file instead of it feeling mostly "natural".
#### Some examples:
- Most functions are `fully_spelled_words_separated_with_underscores` (`register_node`, `register_on_generated`, `register_on_player_receive_fields`). Others have arbitrary use of underscores (`setting_getbool`, `get_timeofday`). Some others use no underscores at all (`getpos`, `getyaw`, `getvelocity`).
- To create an item stack, there's the `ItemStack` _function_. In order to create a "vector" object, you call `vector.new(x, y, z)` (note the `.` notation; it means that `vector` is intended as a namespace). For `VoxelArea`, you need to call `VoxelArea:new(sometable)` (note the `:` notation; in Lua, it is mainly used for _method calls on an instance of some object_, not regular function calls. Worse, `sometable` is a table which contains two fields, `MinEdge` and `MaxEdge` (tables themselves), instead of `VoxelArea` being a _function_.

So I propose we gradually change everything to a common style, adding backward compatibility aliases to `builtin` as we go along.

For this, though, we first need to have consensus on which style should be adopted.

My proposal, personally, and from a practical standpoint, is to use `PascalCase` for anything that should be construed as "class constructor" (e.g. `ItemStack`, `VoxelArea`; `Vector` is debatable), `lowercase` (single word) for anything that should be construed as "namespace" (probably `vector`, obviously `minetest`), and `words_with_underscores` for functions, methods, and field names.

This is the style that most parts of the Lua API uses, and should minimize the compatibility code needed.

**Comment by PilzAdam** [comment]
This is definitely something that should be dealt this.

> So I propose we gradually change everything to a common style

Why gradually? Why not everything at once? Doing everything at once has the benefit that mod maintainers only have to update their mods once, instead of every single release a little bit.

**Comment by kwolekr** [comment]
@PilzAdam kaeza has indicated that he has a reverse compatible way to change method names, so nobody should be required to update their mods.

**Comment by PilzAdam** [comment]
@kwolekr Some modders may still want to update their mods to the new naming scheme. It would make the life easier for them if it was one clear "cut", maybe with a wiki page that contains a conversion table.

**Comment by ObaniGemini** [comment]
@rubenwardy : modding manual ?

**Comment by paramat** [comment]
However, MT is full of inconsistencies, modders are used to the current inconsistencies, and compatibility code causes extra complexity. This is why for example inconsistencies in MTG remain.
It's debateable whether correcting everything is actually worth it.

**Comment by SmallJoker** [comment]
`setting_getbool` and `getpos` (and alike) are already deprecated. Only a few functions plus `vector` are left over which do not fit into the naming scheme.
Documenting the scheme for new features/functions would surely be helpful - https://dev.minetest.net/Lua_code_style_guidelines might be the right place for this.
