### ISSUE TITLE
Full screen mode?

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#3982]
Why do we still don't have full screen mode?

**Comment by asl97** [comment]
minetest.conf
`fullscreen = true`

**Comment by tobyplowy** [comment]
Where do I find the advanced settings?

**Comment by ObaniGemini** [comment]
@tobyplowy : you need a recent build to have them.
Search in your minetest folder the text file called `minetest.conf`
Open it with a notepad for example and add the line 
`fullscreen = true`

Just as said @asl97 .
It might work perfectly :)

The advanced settings menu will come in the upcoming new release.
For now, you can download : https://minetest.kitsunemimi.pw/builds/ **on Windows**

Or

Compile the game yourself on Linux using the Documentation :)

**Comment by tobyplowy** [comment]
Thanks for Being so helpful and nice
