### ISSUE TITLE
Retexturbl gui (ui textures)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#3983]
The gui should have a texture so you can Re texture it using texture packs. Example of what it could do https://www.google.be/search?q=minetest+ui&client=tablet-android-google&prmd=ivn&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiL4orW_IPMAhUCQBQKHSIuAWwQ_AUIBygB&biw=960&bih=600#tbm=isch&q=minecraft+ui+retexture
(also i downt like the Gray gui we Have riht now)

**Comment by tobyplowy** [comment]
The examples ar from Minecraft but Just pretend teir from minetest ;P

**Comment by PilzAdam** [comment]
Mods can already do this.

**Comment by tobyplowy** [comment]
Seriously mods can also add the other stuff det gets added the menus are grey and boring they should get a texture

**Comment by PilzAdam** [comment]
I'm not sure you understand how this works. Minetest is an engine and it already provides the functionality you are requesting. If the games and mods that run on the Minetest engine don't use this functionality, then it's not the engines fault.

Also you should work on your spelling.

**Comment by C1ffisme** [comment]
Please use the [forum](https://forum.minetest.net/) and not Github for your feature requests or support questions.

Thank you.
