### ISSUE TITLE
Upscale texture overlay to the underlying size

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#3987]
This is a problem since texture overlay is possible. Smaller textures are copied 1:1 to the bigger one, which causes this situation: (right side, the copper ores)

![16x texture in a 32px pack](http://i.imgur.com/wuwbSGl.png)

Imagine this would be a 256px texture pack - the copper texture wouldn't be visible anymore.
My idea at this point would be to upscale the overlay texture, so the copper ores can be identified as copper.

**Comment by Fixer-007** [comment]
Yes, very needed, since MC textures are available now (thanks to sofar's tool)

**Comment by stujones11** [comment]
Be careful though, some mods make use of the fact that textures are copied 1:1. While I am not aware of any nodes that do this, I would guess that it's the same code that is used for entities.

**Comment by paramat** [comment]
#4016 is merged.
