### ISSUE TITLE
Add "options" button into pause menu

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#399]
So client wouldn't have to disconnect and then again connect and use additional network traffic when he or she wants to change some settings.

**Comment by paramat** [comment]
:-1:

**Comment by rubenwardy** [comment]
This has limited use while a lot of settings are cached. But it could still be useful for testing, but would be a lot simple to make /cset which is intercepted by client.

**Comment by 4aiman** [comment]
@paramat So what if it's old? :confused: 
Do what you want. Minetest is *not* my project, so it's not up to me to decide anything. 
I guess this can be closed if @sapier won't agree to look into kahrl's work.

It's just the way devs add "Rebase needed" and then forget about the issues that can't bring any joy.
Kahrl's work was ignored from the very beginning despite +1s. And now it's too old to merge. :disappointed:

**Comment by Calinou** [comment]
> This has limited use while a lot of settings are cached. But it could still be useful for testing, but would be a lot simple to make /cset which is intercepted by client.

Settings which require a reconnect or a client restart to be effective could be marked with * and ** respectively, while in the in-game menu.

**Comment by rubenwardy** [comment]
They could. But currently settings are cached using:

```cpp
static int my_setting = m_settings->getInt("my_setting");
```

There is no way for the ingame menu to know whether they're cached, you'd have to look at each one individually and work it out.

Ideally engine settings should use an enum based look up, rather than an std::map based look up. This would remove the need for caching in most places.

**Comment by paramat** [comment]
It's fine to keep this open, we are just checking old issues.

**Comment by paramat** [comment]
Not doable, most settings are cached or require an exit to menu or even a program restart to change, so would be of very little use. Settings are in settings menus for a reason, that's where you go to change them, we're not going to put them everywhere fro no good reason.
