### ISSUE TITLE
Mgv7: Stone in tunnels in mountain terrain at y = 48 when generating downwards

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4000]
![screenshot_20160415_113745](https://cloud.githubusercontent.com/assets/3686677/14559142/c3c666b2-02fe-11e6-8038-fd709039e21b.png)

I know the cause, mountain terrain is allowed to generate in air by necessity, so it generates stone in tunnels at node_max.Y + 1 when the lower mapchunk generates after the upper.
It can be fixed by re-allowing tunnel generation to overgenerate 1 up and 1 down, but then we lose the 'roof' trick bb2ee54d3b841ebdb6c6a0b6573b64216ae0baae that stops light in tunnels at mapchunk borders.
I will see what i can do.

**Comment by paramat** [comment]
One fix could be for mountain terrain generation to detect if the mapchunk above has been generated, and if so disable mountain terrain overgeneration at node_max.Y + 1.

**Comment by paramat** [comment]
See #4002

**Comment by est31** [comment]
Issue 4k celebrate! :tada:

**Comment by paramat** [comment]
#4002 is merged.
