### ISSUE TITLE
Can't compile minetest, linking fails

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#4001]
When building MT on Debian Stretch (testing atm) the build fails when linking the minetest bianry.

Log

	LANG=C cmake . -DRUN_IN_PLACE=1 -DENABLE_GETTEXT=1 && time make -j2                                                [6:54:28]
	-- *** Will build version 0.4.13-dev ***
	-- cURL support enabled.
	-- GetText enabled; locales found: da;be;lt;zh_TW;pt;ky;et;ca;ko;he;ro;de;fr;id;uk;tr;zh_CN;it;ru;eo;es;pt_BR;cs;jbo;hu;nb;pl;ja;nl
	-- Sound enabled.
	-- Using GMP provided by system.
	-- ncurses console enabled.
	-- Redis backend enabled.
	-- Using bundled JSONCPP library.
	-- SpatialIndex not found!
	-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
	-- Configuring done
	-- Generating done
	-- Build files have been written to: /home/moritz/.minetest-dev
	[  0%] Built target jsoncpp
	-- *** Detected Git version 0.4.13-dev-d82c5da ***
	[  0%] mo update
	[  0%] Built target GenerateVersion
	[ 15%] Built target translations
	[ 16%] Linking CXX executable ../bin/minetest
	[ 53%] Built target minetestserver
	/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libIrrlicht.a(CImageLoaderPNG.o): In function `irr::video::png_cpexcept_error(png_struct_def*, char const*)':
	(.text+0xf5): undefined reference to `png_set_longjmp_fn'
	/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libIrrlicht.a(CImageLoaderPNG.o): In function `irr::video::CImageLoaderPng::loadImage(irr::io::IReadFile*) const':
	(.text+0x209): undefined reference to `png_set_longjmp_fn'
	/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libIrrlicht.a(CImageLoaderPNG.o): In function `irr::video::CImageLoaderPng::loadImage(irr::io::IReadFile*) const':
	(.text+0x492): undefined reference to `png_set_longjmp_fn'
	/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libIrrlicht.a(CImageWriterPNG.o): In function `irr::video::CImageWriterPNG::writeImage(irr::io::IWriteFile*, irr::video::IImage*, unsigned int) const':
	(.text+0xc9): undefined reference to `png_set_longjmp_fn'
	/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libIrrlicht.a(CImageWriterPNG.o): In function `irr::video::CImageWriterPNG::writeImage(irr::io::IWriteFile*, irr::video::IImage*, unsigned int) const':
	(.text+0x26e): undefined reference to `png_set_longjmp_fn'
	/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libIrrlicht.a(CImageWriterPNG.o):(.text+0x515): more undefined references to `png_set_longjmp_fn' follow
	collect2: error: ld returned 1 exit status
	src/CMakeFiles/minetest.dir/build.make:5185: recipe for target 'bin/minetest' failed
	make[2]: *** [bin/minetest] Error 1
	CMakeFiles/Makefile2:149: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
	make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
	Makefile:149: recipe for target 'all' failed
	make: *** [all] Error 2
	make -j2  2.23s user 0.32s system 121% cpu 2.091 total

The right dev version of libpng is also installed:

    libpng12-0:amd64                      1.2.54-4+b1
    libpng12-dev:amd64                    1.2.54-4+b1 ←
    libpng16-16:amd64                     1.6.21-2   
    libpng16-16:i386                      1.6.21-2   

The version [migrated on 2016-03-07 to testing](https://tracker.debian.org/pkg/libpng). And i compiled the dev version of MT several times before i hit this error. So it might not be connected to the package directly. 

Any ideas who i can fix the problem?

**Comment by Zeno-** [comment]
libpng12 does not include those functions (they were introduced in version 1.4 (14)) so you somehow need to use the -dev files for the newer version of libpng (maybe it's called libpng16-dev?????)

**Comment by everamzah** [comment]
Shot in the dark, but do you need to delete CMakeCache.txt and try again?

**Comment by lightonflux** [comment]
@everamzah's solution worked. (Haven't changed any packages, just removed that file.)
