### ISSUE TITLE
Viscosity affecting player speed in liquid (was also 'Water flow pushing players')

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#401]
I'm not sure where to put this...
Water flow should affect players. As well as any other liquid flow should push player alongside the... um... the flow.
Also it would be nice to change player's speed according to liquid viscosity when he/she is in that liquid.

**Comment by raymoo** [comment]
With CSM in we may be able to have some kind of forces API that allows Lua to add pushy forces to players.

**Comment by C1ffisme** [comment]
@raymoo I don't think allowing client side mods to affect player motion is a good idea at all, since that means you could effectively make an infinite flying mod.

But I do think water pushing players, and entities in general, would be a good idea, and would make sitting in water feel more like being pushed in a current, rather then sinking in an oddly shaped pit of quicksand.

**Comment by raymoo** [comment]
@C1ffisme It wouldn't be a problem if client mods could only affect player motion if they were sent from the server. Or more precisely, it would be just as much as a problem as it is now: players would have to use a modified engine to abuse the feature.

**Comment by C1ffisme** [comment]
@raymoo 
> It wouldn't be a problem if client mods could only affect player motion if the client mod was sent from the server.

Um... Maybe I just haven't studied our current implementation of client side modding to know enough, but doesn't that defeat some of the benefits of CSM? (Such as using CSM for WAILA-like mods, or minimaps, or playing ambient noises to the player.) And does it actually work like that?

**Comment by raymoo** [comment]
I meant that only specific features would be barred from player-provided client mods, not all features, and you said yourself that players shouldn't be able to provide client mods that affect movement. There is currently no system in place to place such restrictions, but it could be done similarly to how mod security works on the server.

**Comment by paramat** [comment]
Is anyone capable and interested in coding this? Closing in 1 month if not.

**Comment by paramat** [comment]
Not CSM, as some servers may not want to use CSM, water flow moving entities is a fairly basic thing so should be in the engine.
Please continue that discussion to #6755 
This issue can be for 'Viscosity affecting player speed in liquid'.

**Comment by TekhnaeRaav** [comment]
Is viscosity to player speed still not working? Cause I was just messing with liquids and the player speed in the liquid is slowing with the viscosity. I don't know why I thought it wasn't working before, but it is now. :confused:

**Comment by Fixer-007** [comment]
He asked about flow pushing the player, we still don't have that, only viscosity.

**Comment by TekhnaeRaav** [comment]
Then what's the issue open for?

**Comment by raymoo** [comment]
@TekhnaeRaav 
>He asked about flow pushing the player, we still don't have that, only viscosity.

**Comment by raymoo** [comment]
Oh, @paramat moved that part to another issue.

**Comment by paramat** [comment]
Ok thanks, closing.
