### ISSUE TITLE
Frequent lag spikes on the server side

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#4022]
I run the [Minetest Capture the Flag server](https://forum.minetest.net/viewtopic.php?f=10&t=13157) on a VPS. Here's the specs:
### Hardware
- **CPU:** 8 cores @ 2.4GHz
- **RAM:** 16GB
- **Storage:** 500 GB SSD
- **Bandwidth:** 100 Mb/s (Speedtest: 95 Mb/s download, 80 Mb/s upload)
### Software
- **OS**: Ubuntu Server 14.04 64-bit
- **Minetest engine**: 0.4.13-dev, commit fefa148, self-compiled, LuaJIT enabled
- **Subgame**: [capturetheflag](https://github.com/rubenwardy/capturetheflag), world uses the `dummy` database back-end
### Extract of server configuration

```
sqlite_synchronous = 0
map_generation_limit = 160
dedicated_server_step = 0.1
server_map_save_interval = 60
```
## The issue

There are between 12 and 19 players on the server, at all times of the day. The CTF experience is quite enjoyable until frequent lag spikes ruin everything. Every 5 to 10 seconds, players will notice that other players stop moving for a second or two, then teleport about 4-8 nodes away. This makes for a very unpleasant (and unfair) PvP experience, not to mention inventory changes are also delayed by those lag spikes.

The VPS is very powerful, and runs tons of other game servers successfully (it can compile the Minetest engine in less than 5 minutes). It is far from having its CPU 100% used, being out of RAM, or having is bandwidth congested. I also believe the subgame isn't that heavy in resources.

Changing the `dedicated_server_step` to `0.05`, effectively doubling the tick rate, did not solve the issue or aggravate it.

**Comment by sofar** [comment]
latencytop may prove helpful to eliminate OS-related lag sources.

**Comment by paramat** [comment]
Might be caused by the VPS somehow. Not necessarily a MT bug and no way to know for sure. Many people have server issues.
@rubenwardy since you are CTF any comments?

**Comment by rubenwardy** [comment]
I found that I was able to eliminate lag spikes by reducing IO on my server. The server saves every 10 seconds, which would sound right

**Comment by Calinou** [comment]
I cannot reproduce this anymore, closing for now.
