### ISSUE TITLE
Cardboard VR support?

### ISSUE THREAD

**Issue by poVoq** [minetest/minetest#4026]
Given that there is already an Android port and stereoscopic rendering it would be awesome if it would be possible to integrate with Google's Cardboard system, see:
https://developers.google.com/cardboard/android/get-started

**Comment by C1ffisme** [comment]
Please use the [forum](https://forum.minetest.net/) and not Github for your this kind of request.

Thank you.

**Comment by paramat** [comment]
Nothing wrong with making this request here.

**Comment by poVoq** [comment]
Your forum does not allow registration from many parts of the world (in my case currently the Philippines).

**Comment by rubenwardy** [comment]
Why doesn't it?

**Comment by poVoq** [comment]
So called spammer protection that blocks the entire ISP IP range that serves several tens of million of people.

**Comment by rubenwardy** [comment]
It works though, we don't get spam.

Ask @celeron55 for an account.

**Comment by sfan5** [comment]
> It works though, we don't get spam. I guess at the disadvantage of losing users XD

That's complete bullshit. Blocking whole ISP IP ranges is not a good solution to prevent spam.

**Comment by rubenwardy** [comment]
I agree, but over zealous spam blocking with too many false positives is still spam blocking, not "so called"

**Comment by rubenwardy** [comment]
So it's not complete bullshit. Everything there was true, and I never said I agreed with blocking IP ranges.

**Comment by C1ffisme** [comment]
@paramat I dunno...

I would like this kind of thing to be talked about on the forum before we consider it to be added to Minetest.

**Comment by sofar** [comment]
Cardboard seems to be a purely android thing. How are the current stereoscopic render modes supported by minetest insufficient to cover this?

**Comment by est31** [comment]
Idk, perhaps the interface needs to be improved (no idea how that works), or we need to implement head tracking (do we?)....

Either way most of the code is already done, and I don't think the cardboard VR API would be helpful with meeting that goal, as most of the work is already done, isn't it.

**Comment by poVoq** [comment]
As far as I understood it would be good to have a cardboard specific implementation as it deals with all of the specific configuration issues if headset specific lenses distortion. It also has various build in head tracking improvements to statistically correct gyro drift and so on.
Last but not least it offers easy to use VR specific 3D sound and I think it also has a implementation of timestamp to increase the apparent frame rate of the head movement to decrease motion sickness cause by below 60fps frame rates.

**Comment by sfan5** [comment]
Yes, Irrlicht on Android supports OGLES 2.0. There were some difficulties with it in the past IIRC

**Comment by est31** [comment]
I doubt this will be ever possible with the graphics engine we have.

**Comment by poVoq** [comment]
It seems to be possible to wrap it around an existing 3D engine if OpenGL ES 2.0 is supported, see for example the Darkplaces (enhanced Quake1) port: www.quakevr.com
I mirrored the source code here: https://github.com/poVoq/Quake-1-Cardboard-Port-QVR

**Comment by rubenwardy** [comment]
> I doubt this will be ever possible with the graphics engine we have.

Why? We already have side-by-side 3d views, we just need to add support for the tilt to turn camera.
Also, Irrlicht makes things harder but you can still make good looking games with it, see buildaworld...

**Comment by Megaf** [comment]
Up!
I'm curious to see how this goes.

**Comment by edoardoo** [comment]
Yup me too.

**Comment by dgm3333** [comment]
This has already been requested on a number of occasions in the forum posts. I managed to get a klutzy version without controls by mirroring pc screen to headset a couple of years ago, and thought it had potential. Also with VR headsets building momentum over the past 5 years (1M Cardboards were shipped within 1 year of release), so this seems like an area worth working on and (still) has my vote...

**Comment by ensonic** [comment]
Just to give a sample link from the forum: https://forum.minetest.net/viewtopic.php?f=5&t=10710 and like @rubenwardy said, the side by side mode can be enabled from the advanced settings already. What I see as missing pieces is to:

- [ ] auto-select vr-mode (see below) when the cardboard mode is detected
- [ ] map the gyro to the mouse (look around)
- [ ] map a game controller to the keyboard
- enable side-by-side

**Comment by Ferk** [comment]
> map the gyro to the mouse (look around)

I don't think it's that simple. The rotation of the head is centered in the neck, not in the eyes themselves so the translation is not direct and might even involve displacement of the camera itself, not just the angle.
This might seem like a small detail but every small detail is noticeable and cause of bad aligments. 
Even for the occulus rift it took them several iterations to minimize the dizziness people felt when using it for a while.

I think its better to integrate with a dedicated library for that. And even them better to wait until the technology is more mature and more compatible with each other.

Ideally, this should be done in irrlicht.

**Comment by timoteo7** [comment]
something like mod 'Vivecraft' with 'Riftcat' and 'SteamVR'

**Comment by paramat** [comment]
Nope.

**Comment by paramat** [comment]
Closed due to 2 years with no core dev support, but will be reopened if supported by a core dev.
