### ISSUE TITLE
Server list displays incorrectly on Android

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#4030]
I was finally able to build the apk, only to discover that the server list appears jumbled, as seen here with the latest git:

![screenshot_2016-04-24-22-26-34](https://cloud.githubusercontent.com/assets/8821916/14772966/21b9fdae-0a72-11e6-94b0-d55e5c05e6c8.png)
![screenshot_2016-04-24-22-26-49](https://cloud.githubusercontent.com/assets/8821916/14772996/5372c420-0a72-11e6-87ab-88b1fe355da8.png)

**Comment by paramat** [comment]
@MoNTE48 any ideas?

**Comment by MoNTE48** [comment]
This is a mistake in simple mainmenu, I have everything works fine in the client tab

**Comment by kilbith** [comment]
I know why, the android file relies on `common.lua` and the former needs to be updated. I'm preparing a PR.

**Comment by kilbith** [comment]
^ Referenced PR as fix, please test.

**Comment by est31** [comment]
No way we can release minetest for android in such a state. Added blocker label.

**Comment by paramat** [comment]
#4031 is merged.
