### ISSUE TITLE
Opaque leaves and waving leaves

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#4036]
![screenshot_20160425_120222](https://cloud.githubusercontent.com/assets/9893266/14792000/ef54e48e-0add-11e6-8b61-902c2b8b9c95.png)

This.

**Comment by sofar** [comment]
This is a non-standard leaf texture? can you enable F5 and take the screenshot again so we can see what texture this is looking at?

**Comment by C1ffisme** [comment]
This is using my own subgame, but I imagine it's the same for every subgame... I'll test it now.

**Comment by sofar** [comment]
Yes, but point at the leaves when taking the screenshot, not the acacia planks block, lol =D

**Comment by sofar** [comment]
Ohh I see why this is happening - waving leaves shader causes this behavior, no matter the texture.

**Comment by sofar** [comment]
Yeah this is entirely unfixable in the shader. If you use opaque leaves and the leaf waving shader, the mesh needs to draw both ALL sides of the leaf block AND any adjacent surface.

And that would probably kill the performance gain of using opaque leaves to begin with, since it potentially would double the amount of faces, making opaque leaves hurt performance, instead of gain.

I never liked waving leaves to begin with myself :)

**Comment by C1ffisme** [comment]
@sofar Yeah, I thought so myself, but decided to post here in case anyone could find a working fix.

**Comment by est31** [comment]
It would not double the amount of faces, only where leaves blocks touch non leaves blocks. I guess its fixable by a condition in meshgen (with an accompanying comment).

**Comment by est31** [comment]
So yeah, there would be a performance loss by fixing the bug, but how many leaves are touching non leaves blocks, not many. Very certainly the performance advantage would not be *killed*. If people want it to render faster, they should disable waving leaves :)

**Comment by C1ffisme** [comment]
I think that waving leaves should enable the feature @est31 talked about (faces are drawn where leaves blocks touch non-leaves) but without waving leaves the behaviour would remain the same.

**Comment by paramat** [comment]
:-1: To any change for performance reasons stated by sofar.
Opaque leaves are there for maximum performance at the cost of looking a bit crude. if you don't like the minor glitch then don't use opaque leaves.

**Comment by C1ffisme** [comment]
@paramat Yeah, I kinda predicted in my head that this would either be incredibly innefficient or impossible to fix.

I think a better fix for this, if a fix is needed at all, would be to just prevent the player from choosing opaque leaves and waving leaves at the same time.
