### ISSUE TITLE
Squishy textures using john smith TP

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4041]
The texture pack from this forum thread https://forum.minetest.net/viewtopic.php?id=5383 results in squishy textures

![screenshot_20160427_003550](https://cloud.githubusercontent.com/assets/1761623/14841973/14763eb4-0c11-11e6-9ba7-e07f7ee5d2b4.png)

This issue was originally reported by @DonBatman in #minetest-project

**Comment by everamzah** [comment]
Same texture pack with 31c1fca6 reverted:

![screenshot_20160427_005810](https://cloud.githubusercontent.com/assets/1761623/14842224/3083999c-0c13-11e6-9e3c-50f7c5dad3d5.png)

**Comment by yyt16384** [comment]
It has a 320x32 default_grass_side.png, and aspect ratio is not preserved when scaling overlay textures.

**Comment by sofar** [comment]
I think that's an animated grass side texture in MC, so the conversion is broken.

**Comment by Fixer-007** [comment]
Yes, mcresconvert needs to handle such cases, textures are scaled now.

**Comment by est31** [comment]
It seems its a texture problem? Closing then.
