### ISSUE TITLE
In-Game Font switching mess up the GUI

### ISSUE THREAD

**Issue by 14NGiestas** [minetest/minetest#4044]
As the title says...
Some screenshots...
After choose the font and press ok:
![captura de tela de 2016-04-27 10 52 16](https://cloud.githubusercontent.com/assets/14851487/14854555/8c5f0f28-0c66-11e6-97cc-e47b66561cc5.png)
After press "save":
![captura de tela de 2016-04-27 10 52 25](https://cloud.githubusercontent.com/assets/14851487/14854556/8c6a9a6e-0c66-11e6-9533-374e82574806.png)
After repeat the same thing more one time with other font:
![captura de tela de 2016-04-27 10 52 40](https://cloud.githubusercontent.com/assets/14851487/14854557/8c7403a6-0c66-11e6-9d4b-cfbf73566bbd.png)

How to reproduce:
just change the font in-game using the advanced settings...

**Comment by kilbith** [comment]
Yes, known issue. @PilzAdam or @kahrl may have an idea.

**Comment by 14NGiestas** [comment]
Just reporting, because I haven't seen any issue about that... and others devs should know and such...

> @PilzAdam or @kahrl may have an idea.

I hope that XD. Clear all gui and rebuild with the other font perhaps helps...

**Comment by paramat** [comment]
Blocker for release?

**Comment by kilbith** [comment]
Not really. A blocker is a major bug preventing to play the game in confortable condition.

**Comment by kahrl** [comment]
This is caused by the Irrlicht file chooser switching back the locale, in particular for LC_NUMERIC, which breaks formspec coordinate parsing (and other things). See the discussion at https://github.com/minetest/minetest/pull/3258#issuecomment-148756395.

**Comment by kilbith** [comment]
@kahrl I confirm your patch works perfectly. I could open a PR for you.

**Comment by kilbith** [comment]
@kahrl I confirm your patch works perfectly.

**Comment by kwolekr** [comment]
Don't remember all the details, but IIRC sapier left it like that for a reason.  I feel like the actual solution to this bug could be much more difficult to implement than what's in this patch...

**Comment by paramat** [comment]
Added to milestones just so it is considered as a blocker.

**Comment by Zeno-** [comment]
8fe753c3
