### ISSUE TITLE
Mainmenu: initially selected server doesn't influence the gui mainmenu

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4045]
If you start minetest and open the Client tab, or if you return from a server you have joined, an entry will be selected in the gui list on the left, but the port and server info on the right won't match that selected entry. Also, if that server is a favourite, it won't show the "del.fav." button.

The bug is not related with @kilbith 's recent changes to the main menu.

There are two options to solve it:
- a) not select an entry at the start
- b) make the port and server info (and del.fav. button) at the right match the selected server

**Comment by paramat** [comment]
Blocker?

**Comment by est31** [comment]
Nah, its a minor bug i think

**Comment by neoascetic** [comment]
If a favorite server was deleted and a newly selected server is favorite too, it won't have "Del. favorite" button as well.

**Comment by est31** [comment]
@neoascetic can you file a bug on this?

**Comment by neoascetic** [comment]
Doesn't it fit in this issue pretty well?
