### ISSUE TITLE
Chat does not scroll properly

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4051]
Often I see the ever increasing gap in chat (opened with t), so I need to scroll it down regularly: https://i.imgur.com/7ckuaJH.png
kahrl mentioned his code that can help fix this: kahrl@b1fefe8

**Comment by kahrl** [comment]
Yes, I have to finally get over my laziness and submit a PR. Will do that once I can build again (i.e. once #4054 is fixed).

**Comment by Fixer-007** [comment]
4054 is fixed, can you proceed? Will be nice to have this fix in release.

**Comment by paramat** [comment]
@kahrl

**Comment by paramat** [comment]
#4092 is merged.
