### ISSUE TITLE
Unable to use some symbols in console, Shift behaviour is weird

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#4057]
OS: OSX 10.11.4
1. I am unable to input curly braces in console
2. Shift behaviour is weird: it adds extra space when it is pressed

**Comment by neoascetic** [comment]
@paramat not sure if this affects only OSX. Do you have similar problems on your machine?

**Comment by est31** [comment]
**cc** @ShadowNinja

**Comment by PilzAdam** [comment]
@neoascetic can't reproduce on Linux with QWERTZ keyboard layout.

**Comment by neoascetic** [comment]
It seems like `event.KeyInput.Char` equals to `event.KeyInput.Key` on OSX even if Control or Shift button is pressed, see also `CIrrDeviceOSX.mm`. Any advice how to fix this in a proper way? Is this completely Irrlicht issue or maybe we may fix it somehow?

**Comment by ShadowNinja** [comment]
I think Irrlicht 1.9 reworks the input system, you could see if it's fixed there.

**Comment by est31** [comment]
The 1.9 rework only fixes the most tough bugs one has with input, there are still general issues with it remaining, @ least AFAIK.

**Comment by neoascetic** [comment]
I've created #4074 to fix at least shift behavior

**Comment by nerzhul** [comment]
Fixed

**Comment by neoascetic** [comment]
Great, the first part of the issue should be fixed by [this](https://sourceforge.net/p/irrlicht/patches/313/).
