### ISSUE TITLE
Connecting walls, walls and connecting iron bars and glass panes. stairs blocking angle 90 degrees.

### ISSUE THREAD

**Issue by StepDevelop** [minetest/minetest#4058]
Are you working on these bugs? I can be of help? I need information to work ... the connection of the blocks is controlled by the right xpanes? I almost finished the new wood textures (jungle and trees, the current textures can be improved :) texture trees, I changed by deleting the edges! so it's much better! when building structures, the tree creates texture effect made of continuity, currently the texture creates lines that break off individual blocks. I await answers, I hope to work with you to improve Minetest. Thank you guys.

**Comment by PilzAdam** [comment]
I don't understand what you try to say here.

**Comment by paramat** [comment]
Please can you post screenshots of the bugs, or explain them more clearly?

**Comment by StepDevelop** [comment]
Work to fix the bugs of the block connections? walls, iron bars, etc ... ???
I have changed the standards, to make them better textures. My English is very bad :) sorry :)

**Comment by sofar** [comment]
This seems like it should be 2, maybe 3, separate bugs in minetest_game, not minetest.

**Comment by StepDevelop** [comment]
Ok! Sofar thanks :) sorry, the public all of minetest game. Thanks for the reply. I move on minetest_game;)

**Comment by sofar** [comment]
Please close this when you've moved the issues and split them out! thanks.
