### ISSUE TITLE
(Gamma) Brightness slider option 

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4060]
There really needs to Be a Brightness slider option in the gui (because when it's dark or I go into a cave the only thing I see is black) and torches don't really help because the radius of the light isn't big enough

**Comment by rubenwardy** [comment]
Gamma?

**Comment by tobyplowy** [comment]
@rubenwardy yes. Gamma sorry :smile:

**Comment by rubenwardy** [comment]
There's already a gamma setting, just not on the gui.

**Comment by tobyplowy** [comment]
@rubenwardy it Should Be added to the gui (also where do I find it is it in advanced options)

**Comment by est31** [comment]
@tobyplowy its in the advanced menu, `Client → Graphics → In-Game → Advanced → Gamma`.

**Comment by Calinou** [comment]
> @tobyplowy its in the advanced menu, `Client → Graphics → In-Game → Advanced → Gamma`.

You probably want to set it to the lowest value possible, which is 1.0. Lower gamma means the display will be brighter in dark areas (bright areas, like sunlight, are not affected by this setting).

**Comment by tobyplowy** [comment]
@paramat thanks i hope it gets added :smile:

**Comment by paramat** [comment]
> (because when it's dark or I go into a cave the only thing I see is black)

Seems expected behaviour. If it's dark too bad use some lights.
Gamma is good enough in advanced settings i don't think it needs to be quickly accessible.
:-1:

**Comment by Zeno-** [comment]
The thing with darkness/brightness is that people's monitors are vastly different. That's why a gamma option was added in the first place. A brightness option might be good as well. 

I think having a slider is a reasonable idea.

**Comment by paramat** [comment]
Might as well just increase the power and range of the gamma setting instead of adding something new. This is something thst doesn't need setting often so doesn't need in-game access.

**Comment by paramat** [comment]
@tobyplowy we have a new light curve now, torches are effectively much brighter.

**Comment by tobyplowy** [comment]
@paramat Shadows seem to be a lot darker

**Comment by tobyplowy** [comment]
@paramat the darknes is pure black
![gggg](https://cloud.githubusercontent.com/assets/16853304/24171076/52ef2fd2-0e83-11e7-8f4f-53fb0089ba83.png)

**Comment by tobyplowy** [comment]
@paramat also one blue pixel for some reason

**Comment by HybridDog** [comment]
That's not pure black:
![52ef2fd2-0e83-11e7-8f4f-53fb0089ba83](https://cloud.githubusercontent.com/assets/3192173/24193469/a7a9b9ba-0ef2-11e7-816d-140e9c94fd25.png)

**Comment by tobyplowy** [comment]
@HybridDog ok almost pure

**Comment by HybridDog** [comment]
Your problem can be fixed by implementing exposure: http://web.archive.org/web/20160305200308/http://freespace.virgin.net/hugo.elias/graphics/x_posure.htm

**Comment by paramat** [comment]
Any core dev support?
