### ISSUE TITLE
Add an option to change night brightness, if possible.

### ISSUE THREAD

**Issue by adamryczkowski** [minetest/minetest#4062]
I'd like to add a little more atmosphere to the survival part of the game and make nights a little more scarier. I'd like to make nights at least so much dark, that the only thing I would be able to discern is the silhouette of the blocks on the horizon (and perhaps eyes of the mobs who want to attack me ;-) ). 

Does it require editing node brightness table?

**Comment by SmallJoker** [comment]
> Does it require editing node brightness table?
Yes it does. But it also depends on the individual screen settings, thus, the brightness (or better darknes) will not be the same for every player.

**Comment by paramat** [comment]
See use of gamma #4060

**Comment by adamryczkowski** [comment]
I know about gamma. But that would change the way caves and daylight world looks like. I just want the nights to be darker. Is it doable?

**Comment by Zeno-** [comment]
It's doable, but will make caves darker as well.

**Comment by adamryczkowski** [comment]
@Zeno-  thank you.

**Comment by hunter688** [comment]
It looks like hardcore darkness mod in the Minecraft. http://mods.curse.com/mc-mods/minecraft/225957-hardcore-darkness

**Comment by adamryczkowski** [comment]
@hunter688  yes. Together with ambient music and sounds, and hostile mobs it would let me better appreciate cosiness of my electrically-illuminated home. :-)

**Comment by paramat** [comment]
Moonlight is brighter than cave darkness, so i guess gamma won't help.

**Comment by Fixer-007** [comment]
@adamryczkowski Try toggling on "tone mapping" setting, it darkens the night and caves (at least for me).

**Comment by paramat** [comment]
We now have a user-settable light curve, try experimenting with that.
