### ISSUE TITLE
Mingw cross-compiler error for minetest ver 8fe753c

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4068]
I have compiling error while cross-compiling win build on my debian with mingw64 of minetest ver 8fe753c : error in event.cpp

Pic: https://i.imgur.com/U6A90oH.png
Probably caused by commit: "Zeno- Fix use of uninitialised variable in class Event" ?

**Comment by Zeno-** [comment]
yes, that is my fault

**Comment by hcorion** [comment]
I would also like to add that this error shows up on MSVC as well.

**Comment by Zeno-** [comment]
9dee4be
