### ISSUE TITLE
Stuck chat window

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4069]
If you in-game, hold "F10" button for 5 seconds. Now, if you trying to enter chat or pause the game, but you can't. You will get stuck for not get enter a chat or pause the game.

**Comment by sfan5** [comment]
Works fine here.

**Comment by neoascetic** [comment]
Works well for me

**Comment by Wayward1** [comment]
I can confirm, the only way I could leave the window was alt+tab

**Comment by kahrl** [comment]
Confirmed, except it took about 10 seconds for me, on Gentoo amd64 with XFCE4.

**Comment by Zeno-** [comment]
Introduced by 8c951cae5bcfa715e227d47d122cc2de45d70a63

**Comment by Zeno-** [comment]
Fix: 4072

**Comment by Zeno-** [comment]
Fixed by d864c13
