### ISSUE TITLE
Add and use #minetestdev tag on StackOverflow for dev questions on forum

### ISSUE THREAD

**Issue by adamryczkowski** [minetest/minetest#4073]
I am considering writing something more serious for Minetest than patching already existing mods. 

If I go through with it, I'd require a good channel of communication with the community for my numerous questions like "*How do I add custom stamina meter*" or "*How to store custom data in nodes and LuaEntities, to make effect of gradual rotting of food items?*". I realize there is already forum for that, but I would personally prefer using StackOverflow for this specific type of questions. 

How do you feel about adoption of some SO tag for this sort of traffic?

**Comment by neoascetic** [comment]
There is a forum, there is an IRC... Maybe gaming.stackexchange.com is more appropriate?

**Comment by rubenwardy** [comment]
gaming.stackexchange.com is not appropriate for engine dev discussion.

**Comment by ShadowNinja** [comment]
If you want to use such a thing, we won't stop you.  There probably won't be many people that can help you monitoring that site though.
Someone with 1500 reputation on SO would have to do this.  You may have to ask one of the mods of that site to create it for you.

As for your example questions (if you actually wanted to know): 1. Use the HUD API.  There are a number of mods which already add stat bars, so look at how they do it.  2. Node meta for nodes; just use the item's table fields with items, with `get_staticdata`/`on_activate` for serialization. See `__builtin:item` code.

**Comment by neoascetic** [comment]
@rubenwardy sorry, I meant gamedev.stackexchange.com

**Comment by est31** [comment]
I don't think it is useful to have this issue opened anymore.
