### ISSUE TITLE
Overlaying a texture with a smaller texture as base no longer works correctly

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#4081]
Regression caused by https://github.com/minetest/minetest/commit/31c1fca6fd5e200c4f4b24d7ba62b36a16494ed2
Cc: @SmallJoker 

Before it was possible to overlay 2 textures like so : `16px_texture.png^32px_texture.png` to force adapting a 32px texture to 16px.

Now it no longer works and only the greater resolution is considered.

My mod `xdecor` is broken because of that, I had a mailbox enforcing a [texture cutting](https://github.com/kilbith/xdecor/blob/master/mailbox.lua#L31)  to 16px in formspec's tablecolumn thanks to an overlay, and now its table is completely screwed when stuff inside have higher resolution textures than 16px.
- Before https://github.com/minetest/minetest/commit/31c1fca6fd5e200c4f4b24d7ba62b36a16494ed2 : 
  ![screenshot_20160503_021553](https://cloud.githubusercontent.com/assets/7883281/14971907/2236f08c-10d7-11e6-8460-96bda3208678.png)
- After https://github.com/minetest/minetest/commit/31c1fca6fd5e200c4f4b24d7ba62b36a16494ed2 : 
  ![screenshot_20160503_021538](https://cloud.githubusercontent.com/assets/7883281/14971912/342ffb9e-10d7-11e6-8fb4-4b360cd85d3a.png)

**Comment by kilbith** [comment]
^ Sorry for the mess, some clarification needed.

**Comment by Thomas--S** [comment]
Maybe `[combine:WxH:x1,y1=filename1:x2,y2=filename2:... ` can help you. You can find more details about [combine here: http://dev.minetest.net/texture#Texture_grouping

**Comment by SmallJoker** [comment]
To not tap into kahrl's TODO list, I got those two things:
`img = img..i.."="..minetest.formspec_escape("[combine:16x16:0,0=mailbox_blank16.png:0,0="..img_col(stack_name))..","`
This will just copy pixel by pixel, as @Thomas--S suggested above. It must be escaped to not destroy the table modifier.

The sond thing is the plan for adding the modifier `[resize:WxH:file` to eliminate such hacky workarounds.

**Comment by stujones11** [comment]
This not a bug since the mod relies on previously undocumented behaviour :p
