### ISSUE TITLE
use_texture_alpha =true should Be on by default

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4083]
It's a lot more convenient if use_texture_alpha =true is on by default (For Beginners like me)

**Comment by Thomas--S** [comment]
Have you tried the option `use_texture_alpha = true` in nodedef? However, use_texture_alpha seems to be a bit buggy.

**Comment by tobyplowy** [comment]
@Thomas--S it works thank you for the help 
![glass](https://cloud.githubusercontent.com/assets/16853304/14988695/564ce2b8-1155-11e6-82dc-85846ba3632f.png)

**Comment by Calinou** [comment]
No, it should not be set to `true` by default, because this would ruin performance. Setting a material to be able to use transparency (other than 1-bit transparency) is very resource-intensive.

**Comment by PilzAdam** [comment]
There are rendering issues with semi-transparent nodes.

**Comment by tobyplowy** [comment]
@Calinou Sorry I diddent know

**Comment by tobyplowy** [comment]
@PilzAdam it seems to be working just fine what do you mean by issues. also if there ar issues culd they be fixed?

**Comment by paramat** [comment]
:-1: 
Translucency seems to work at first, but try setting up several scattered nodes and look at the others through each, weird stuff happens (no z-sorting).

**Comment by tobyplowy** [comment]
@paramat it looks good to me 
![lll](https://cloud.githubusercontent.com/assets/16853304/14993480/3a3644d2-116b-11e6-9ba0-91edf850fd2d.png)

**Comment by Thomas--S** [comment]
@tobyplowy  Place a semi-transparent node on air and look at it from under-water. You will see the bug.

**Comment by tobyplowy** [comment]
@Thomas--S oh I see The Water Becomes Invisible. could this be fixed?

**Comment by sofar** [comment]
It's mostly a problem for nodeboxes and mesh nodes. This is an ordinary cube node.
