### ISSUE TITLE
[Discussion] Support for engine changes with modding API

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4085]
Why is it not possible to change engine properties with mods. for example shaders or Changing the main menu to look More like Minecraft this would make a lot More possibilities (i have no idea how all of this works so it may be a limitation with the game engine but still wanted to talk about it) I've only just started to program :smile:

**Comment by rubenwardy** [comment]
There is a pr to allow server mods to define shaders, but the maintainer left the project.
The main menu code is Lua, so you could write mods for it. (They wouldn't be modular mods, ofc).

Minetest is the game engine. Minetest is written in C++ which makes it hard to inject code as an outside mod. You could add more Lua callbacks, but that's at the cost of efficiency. Also, there is the server/client split. Lua mods are run on the server.

**Comment by tobyplowy** [comment]
@rubenwardy why is minetest not so advanced it's already a couple years old. And Why doesn't minetest_game have gameplay (I think the people of minetest need to Step It Up a bit at this Point You Never Gonna Get anywhere) just add more gameplay and More user Friendly ui

**Comment by PilzAdam** [comment]
This basically requests client-side mods. Marking as duplicate.

Btw, changing the menu is already easily possible via Lua and the `menu_script` setting.

**Comment by est31** [comment]
Yeah let's close it.
