### ISSUE TITLE
Node metadata is lost on falling nodes

### ISSUE THREAD

**Issue by jhcole** [minetest/minetest#4087]
Node metadata set on a `falling_node` is lost if the node falls. For example, a falling chest will lose its inventory if it falls.

**Comment by sofar** [comment]
This is due to falling.lua only serializing and deserializing node data, not metadata. Should be fixable in falling.lua.

**Comment by sofar** [comment]
It should also serialize and deserialize any active node timers.

**Comment by PilzAdam** [comment]
@sofar maybe we should just call a callback in nodedef if a node starts falling? This way we don't have to consider every corner case and chests could just serialize the stuff they actually need.

**Comment by sofar** [comment]
@pilzadam yeah, that's a very good idea. I'll probably look into this after 0.4.14...
