### ISSUE TITLE
Texture transforms not working for certain sides of a node

### ISSUE THREAD

**Issue by webdesigner97** [minetest/minetest#4088]
```lua
minetest.register_node("streets:test", {
  tiles = {"streets_line_mixed_double.png^[transformFX", "streets_line_mixed_double.png^[transformFX", "streets_line_mixed_double.png", "streets_line_mixed_double.png", "streets_line_mixed_double.png", "streets_line_mixed_double.png"}
})
```

The first texture gets flipped correctly, the second does not change at all. I also tested `[brighten` resulting in the same problem. Only the top texture changes.

![screenshot_20160504_104937](https://cloud.githubusercontent.com/assets/2469742/15009313/fdb85b00-11e5-11e6-806f-a8fc3c1acf9d.png)
No transforms specified.
![screenshot_20160504_104956](https://cloud.githubusercontent.com/assets/2469742/15009312/fdb5c19c-11e5-11e6-89da-025a519aeeb1.png)
Transforms specified as given in the code above.

**Comment by Thomas--S** [comment]
Is it possible, that `^[transformFY` is needed?

**Comment by webdesigner97** [comment]
I tried multiple ones, like [brighten, but I''ll retry later...

Von meinem Sony Xperia™-Smartphone gesendet

---- Thomas--S schrieb ----

Is it possible, that `^[transformFY` is needed?

---

**Comment by webdesigner97** [comment]
Nope, no transformation at all wants to work...

**Comment by webdesigner97** [comment]
I just found out that this weird behaviour was caused by confused textures and texture orders, combined with facedir nodes. So there's no bug at all. The bug was in front of the screen ;)
