### ISSUE TITLE
[can I ask this kind of question here?] [forum issue] near-infinity captchas

### ISSUE THREAD

**Issue by 14NGiestas** [minetest/minetest#4089]
I always forget my passwd for minetest forum so sometimes this msg appear:
"You exceeded the maximum allowed number of login attempts. In addition to your username and password you now also have to solve the CAPTCHA below."
Q: What version of Minetest came after 0.4.10?: A: 0.4.11
Q: What's the number in the nickname of the original creator of Minetest?: A: 55
Q: Watch out, roses have _ _ _ _ _s!: A: spike
and so on...
I don't think this is a good way to avoid automated form submissions by spambots. Cause theres a limited number of questions... I already seen all of it...

**Comment by C1ffisme** [comment]
What about one of the CAPTCHAs where you only need to click a button?

**Comment by 14NGiestas** [comment]
reCAPTCHA from google?
https://www.google.com/recaptcha/intro/index.html
It's nice, seems a good API, but don't know if it's a FOSS alternative...

**Comment by est31** [comment]
**cc** @celeron55 

@14NGiestas reCAPTCHA was disregarded because of the usual reasons to reject external cloud services. And you have to enable javascript etc etc.

And about the questions being limited: yes that's true but as long as it keeps 99% of the spammers out, everything is fine. I haven't heard about any problems with that.

**Comment by PilzAdam** [comment]
This doesn't really belong here. Maybe post it here: https://github.com/minetest/forum.minetest.net_template1/issues ?

**Comment by rubenwardy** [comment]
Doesn't really belong there either. Really this could just be an email to celeron55@gmail.com, or on IRC

**Comment by est31** [comment]
Agree with @rubenwardy.
