### ISSUE TITLE
mesh tiling bug and possible fix

### ISSUE THREAD

**Issue by obneq** [minetest/minetest#4091]
the following screenshots were made with a one line change in clientmap.cpp, in renderMap after line 523 added 'buf->getMaterial().setFlag(video::EMF_WIREFRAME, true);'.
![screenshot_20160505_231754](https://cloud.githubusercontent.com/assets/168487/15057825/1eed3e1a-1319-11e6-95a2-74f5813127c3.png)
you can see the maximum length of tiled nodes is two, when it should tile rows. Here is what it looks like with patch below applied: 
![screenshot_20160505_231610](https://cloud.githubusercontent.com/assets/168487/15058139/f443029c-131a-11e6-90f3-8c186b83071a.png)

https://gist.github.com/obneq/6cb623b85df59742ead79e4a9a5c96f9

**Comment by Fixer-007** [comment]
Can you provide more details?

**Comment by sofar** [comment]
How does this actually look in the game before/after the patch without the wireframe?

**Comment by obneq** [comment]
@Fixer-007 what details do you mean? ie can you provide more details? :)
@sofar no visual change afaict

**Comment by Fixer-007** [comment]
In other words, are you sure that was the bug, what benefits of the patch here?

**Comment by est31** [comment]
Ohhh that looks nice. @Fixer-007 I haven't looked at the code yet, so I don't know whether its a bug in performance improving code or "only" a performance improvement but if the screenshots are true, then the fix should greatly improve the FPS. Less polygons == Faster rendering.

**Comment by ExeterDad** [comment]
More FPS is a exciting possibility for sure! What happens to selection boxes of these tiled nodes?

**Comment by Fixer-007** [comment]
I will try that patch for sure then.

**Comment by SmallJoker** [comment]
About the 2nd image: Couldn't the polygons be larger in the flat areas? They are just calculated along one axis.

**Comment by Fixer-007** [comment]
I have same fps with patch and without, what problem it actually solves?

**Comment by sofar** [comment]
The effect will likely be not noticeable unless you run with a really crappy graphics card (or software rendering). However, it still helps, so this is great.

**Comment by rubenwardy** [comment]
> Less polygons == Faster rendering.

Not necessarily. That's only if your rendering is GPU bound. I suspect that Minetest is mostly CPU bound, so less polygons won't make much of a difference, it would be much better to send things to the GPU better by eg: reducing draw calls and batching.

If you have a shit graphics card, then it will be GPU bound. That's the case when reducing polygons would matter.

Afaik. This is from reading a few articles.

https://www.opengl.org/wiki/Performance
http://answers.unity3d.com/questions/716942/how-many-trianglespolygons-is-a-draw-call-worth.html#
http://stackoverflow.com/questions/4853856/why-are-draw-calls-expensive
http://stackoverflow.com/questions/22264356/more-vertices-or-more-draw-calls

**Comment by asl97** [comment]
@Fixer-007 This fix the tile grouping bug, the bug which make it able to group two tiles together at most.

It's because the variable ain't updated to the "next node" at the end of the loop, causing it fail to set `next_is_different` to false when checking it with the new "next node".

No idea why the removal though: https://gist.github.com/obneq/6cb623b85df59742ead79e4a9a5c96f9#file-mapblock_mesh-patch-L35
____
@SmallJoker That probably would be hard to implement, it can be change again at a later date if someone figure out how to do it.

**Comment by Fixer-007** [comment]
Oh I see, while fps is the same, the number of vertices is much less in noncomplex scenes, I guess this can help for really slow videocards I guess (if cpu is good enough).

**Comment by obneq** [comment]
as others have noted, the difference in FPS is not huge on this one, and as it is invisible it is indeed debatable if this is a worthwhile fix. However, looking at the code it seems clear that there is the intention to tile identical adjacent nodes. But it does not work and this is an attempt to fix that. The resulting code is simpler, shorter and easier to follow, so i think it should be done

**Comment by Zeno-** [comment]
I think it's worthwhile

**Comment by kwolekr** [comment]
Looks good to me, could you make a PR for it?

**Comment by rubenwardy** [comment]
Does this add n-gons?

**Comment by Zeno-** [comment]
Tested and looked good

**Comment by obneq** [comment]
@kwolekr i doubt i should make a PR, as i am unable to maintain a local repo with git. this has made my last PR result in a lot of extra work just for rebasing, which is why i just give a gist this time.

Also some more work needs to be done on this, mainly checking and adjusting the debug info gathering about tiles drawn by tiling.

@rubenwardy this does not add n-gons, it just makes it possible for tiled quads to be longer than 2, up to the maximum of MAP_BLOCKSIZE. I have ported the js algorithm for greedy meshing for use in minetest if you are interested, it's here:  

https://gist.github.com/obneq/737aec01624160efea8814a3442f9476
note that this was intended for testing another approach to collision detection and thus only cares if nodes are solid or not. in practice not too much can be greedily tiled once you take into account different node types (textures) and light levels, but i have not done any testing.

**Comment by paramat** [comment]
#4442 is merged but what about this?:

> Also some more work needs to be done on this, mainly checking and adjusting the debug info gathering about tiles drawn by tiling.
