### ISSUE TITLE
Add 'sound packs' that work like texture packs. Add 'media packs' that can contain 'texture packs' and 'sound packs' 

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4093]

**Comment by MoNTE48** [comment]
You can add your sounds on /sound in minetest folder.

**Comment by tobyplowy** [comment]
@MoNTE48 with texture packs?

**Comment by MoNTE48** [comment]
No, you can copy texturepack on /textures and sound pack on /sound

**Comment by tobyplowy** [comment]
@MoNTE48 why do you have to make 2 pack files wouldn't it be easier if it's all in one pack like Minecraft resource packs?

**Comment by MoNTE48** [comment]
@tobyplowy, Certainly easier. I just gave you a clue what to do, until your proposal has not been put into practice.

**Comment by tobyplowy** [comment]
@MoNTE48 thanks for helping bdw :smile:

**Comment by rubenwardy** [comment]
Two separate folders is better than one, textures aren't that similar to sounds.

**Comment by est31** [comment]
two separate folders yes, but if people want it in one pack file

**Comment by sofar** [comment]
@rubenwardy doesn't that make it difficult to switch between different sets of sounds?

What if mcresconvert also would convert sounds from resource packs, how would it switch between the various "sound packs"?

**Comment by paramat** [comment]
:-1: Best seperate files.

**Comment by everamzah** [comment]
If minetest were to support an archive format, say .pk3 or .pk7, or both, then the problem would be easily solved.  Inside would be a directory hierarchy with whatever resources the pack provides/overrides.

**Comment by desttinghim** [comment]
Maybe an import function for "resource packs" could be made. Resource packs being sound, textures, models, etc.

**Comment by ensonic** [comment]
+1 for unified resource packs. That is renaming the "texture pack" tab into "resource pack" and being able to swap both. As a transition, minetest could scan both 'asset' and 'texture' folders, but prefer entries from the new 'asset' folder.

**Comment by Holyphoenix** [comment]
Isn't this basically what a game pack is supposed to be minus the mods?

**Comment by SmallJoker** [comment]
I see many people would like to have a combined sounds and textures directory. But then it still should be possible to combine various "resource packs" because not all packs will have sound, and those who have sounds might not have any textures. Or you got a complete pack but prefer the sounds from another?
Either this will result in moving the files manually around or it will be done in the GUI to pick a pack for each category.

**Comment by tobyplowy** [comment]
Yes being able to combine packs wuld be awesome ( for example if I make an edit of a texture pack I have to copy all textures from the original pack with this I could just make what I need and put it on top of the original :D

**Comment by tobyplowy** [comment]
@SmallJoker Yes being able to combine packs wuld be awesome ( for example if I make an edit of a texture pack I have to copy all textures from the original pack with this I could just make what I need and put it on top of the original :D

**Comment by tobyplowy** [comment]
@everamzah yeah but it would be harder for noobs to make a texture pack, I think we should keep using .zip it's much more Noob friendly :D

**Comment by paramat** [comment]
:-1: Independent packs are simpler and less problematic, they can always be bundled together inside another file.

**Comment by ensonic** [comment]
@Holyphoenix what are game_packs? subgames?

I don't mind if there would be a tab for selecting sound packs either, as long as there is a way to select them from the UI. Tools like mcresconver would then create two packs if the original pack contains sounds ...

**Comment by Holyphoenix** [comment]
@ensonic  Yep, my bad, I used the wrong term.  Subgames is what I was talking about.

**Comment by paramat** [comment]
@tobyplowy there is disapproval for texture packs containing sounds, this obviously cannot be done, so please change the thread title to a request for resource packs that contain texture packs and sound packs, if you are happy with this idea.

**Comment by rubenwardy** [comment]
I've changed my opinion about this, and think that it would be good to have resource packs which can change sounds as well. Sounds are just as important as textures in giving a feel in game.
Although they should be separate folders, and I consider this low priority compared to other things.

**Comment by tacotexmex** [comment]
_Below started as its own issue (#6920) but was redirected to this one._

As with the problem described in #5860 (a feature which is now merged: #6032), subgame makers face the same issue when it comes to sound packs.

My proposal is to implement this the same way as with subgame textures pack support:

>If the subgame contains a folder called **`sounds`** the server will load it
    as a sound pack, overriding mod sounds.

Perhaps @red-001 are interested in doing this, as done with #6032 ?

**Comment by paramat** [comment]
If we add sound packs, they will very probably be implemented with the same features as texture packs, so game sound packs will naturally be a part of this.

**Comment by tacotexmex** [comment]
But sound packs [_are_ implemented](https://wiki.minetest.net/Sound_Packs)?

**Comment by tobyplowy** [comment]
Hallo it's been a while since I have posted something here so...

I'm tied of waiting
Why doesent this just get added like really do you guys want to limit creativity?
It's not like it's hard to program ether :/

I'm just tempted to close this issue becouse I know that it will be done for me very soon anyways

Please just say yes or no.

**Comment by paramat** [comment]
We have a crude 'sounds folder' ability, but see https://github.com/minetest/minetest/issues/5363#issuecomment-285666082
"You can replace sounds by placing sounds into the sounds folder (you may need to create it)
But there's no concept of sound packs yet"
For example there is no menu tab for sound packs. So this issue can address if we want more user-friendly sound packs that work just like texture packs.

tobyplowy that is childish whining, we are discussing and many have explained their opinions about the implementation, it's not as simplistic as yes or no. It also depends on when someone codes it, we have a severe lack of dev time.
Yes obviously we want to limit creativity.
If you close the issue we will reopen it because there is interest from many in this.

**Comment by tacotexmex** [comment]
> tacotexmex, we have a crude 'sounds folder' ability, but see #5363 (comment)
"You can replace sounds by placing sounds into the sounds folder (you may need to create it)
But there's no concept of sound packs yet"
For example there is no menu tab for sound packs. So this issue can address if we want more user-friendly sound packs that work just like texture packs.

Imo, the implementation may be made in at least two stages, where the first one puts the structure in place for a `sounds` folder in `~/.minetest` and subgame folder respectively to be loaded and overriding sounds. The second stage of implementation would add the UI features for handling such packs. The first stage would still be quite useful on its own.

**Comment by tacotexmex** [comment]
I suggest renaming of this issue to simply "Add 'sound packs' that work like texture packs". 

Media packs as a concept is just a collection of textures and sounds anyway, so that part is irrelevant. The issue won't move anywhere with the current framing.

**Comment by rubenwardy** [comment]
I support adding media packs

**Comment by mk-pmb** [comment]
I'd love these. What's the next missing step?

**Comment by rubenwardy** [comment]
#11936
