### ISSUE TITLE
In-game font switching reverts language to English

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4094]
If you use the advanced settings to set the font, if you click “edit” to open up the file selection menu, then select a file and hit the “Save” button, you are suddenly presented with an English Minetest.

Test this by starting Minetest in a language other than English.

Tested in ae02d1eb8f4222d5cd3f885352011e4e699e6a3f on GNU/Linux.

Related issue: #4044

**Comment by PilzAdam** [comment]
The Irrlicht file dialog probably changes all language environment variables.

@kahrl maybe it would be possible to save all the lang variables before opening the Irrlicht file chooser and then resetting them once it closes?

**Comment by kahrl** [comment]
Cannot confirm. I set the language to German, opened the font path file browser (difficult since many of the translated strings show up as "<invalid UTF-8 string>" for me) and saved. The language remained German.

**Comment by sfan5** [comment]
Now seems to segfault instead :laughing:

**Comment by Wuzzy2** [comment]
No longer the case in Minetest 5.1.1, but the font selection is broken in a different way now.

See #8978.
