### ISSUE TITLE
Compilation warnings in Lua

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#4096]
I recently tried the latest git on Ubuntu 16.04 amd64, and this warning came up:

`/home/mtango/minetest/src/lua/src/loadlib.c: In function ‘ll_sym’:
/home/mtango/minetest/src/lua/src/loadlib.c:76:21: warning: ISO C forbids conversion of object pointer to function pointer type [-Wpedantic]
   lua_CFunction f = (lua_CFunction)dlsym(lib, sym);
                     ^`

Note that this is using gcc 5.3.1, cmake 3.5.1.

**Comment by est31** [comment]
Well its a lua issue, we can't do much about it, as we prefer not to edit around in different librarie's code... The only thing we should modify here is the cmake script.

Have you turned on some specific warnings? Or is that the default config now?

**Comment by mtango688** [comment]
I don't know, but I guess pendantic is the new default.

**Comment by mtango688** [comment]
There was some discussion upstream, now that I'm looking around for it.

http://lua-users.org/lists/lua-l/2015-01/msg00019.html

**Comment by Zeno-** [comment]
That particular warning has actually been occurring for a long time (and always without specifically providing -Wpedantic). *shrug*

**Comment by paramat** [comment]
Yes i'm used to seeing that during build.

**Comment by mtango688** [comment]
Some other references:

https://github.com/freeminer/freeminer/issues/258
https://github.com/minetest/minetest/issues/457
https://forum.minetest.net/viewtopic.php?f=6&t=8024
http://irc.minetest.ru/minetest-dev/2014-04-09/text

This has been around for awhile.

**Comment by Zeno-** [comment]
Closed because it's a known "issue" and something upstream should address, not us
