### ISSUE TITLE
Dieplayer playersao failed error

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4098]
The following error appears with server crash, happens randomly:

"minetest: /build/minetest-zv2Xpr/minetest-201605071646/src/server.cpp:2520: void Server::DiePlayer(irr::u16): Assertion `playersao' failed." errors

**Comment by Zeno-** [comment]
How often does this occur?

Can you provide log files for around time time the crash occurs (edit for privacy if necessary).

**Comment by gregorycu** [comment]
I'll take a look
