### ISSUE TITLE
Minetest apk build failure (again)

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#4099]
After following the new apk build instructions, the build seems to be searching a bunch of directories, then often hangs at this: http://paste.ubuntu.com/16285724/

And when it _does_ get past that, it fails with http://paste.ubuntu.com/16285694/

**Comment by paramat** [comment]
@MoNTE48 any ideas.
Can anyone reproduce?

**Comment by MoNTE48** [comment]
@Wayward1, as I previously say. If you want me to make it easier to understand what the problem is,
make clean_all && make release
And do not use -j *, please.

**Comment by Wayward1** [comment]
@MoNTE48, sorry about that, will retry with your suggestions. Also, I never used -j except the one time I was directed to.

**Comment by asl97** [comment]
@Wayward1 seem like you are missing `realpath`, iirc, it is provide by coreutils.

**Comment by Wayward1** [comment]
Hmm, apparently it's not. Installing now. Perhaps it needs to be added to the dependencies?

**Comment by Wayward1** [comment]
@MoNTE48, new results for Minetest: http://paste.ubuntu.com/16288564/

And Multicraft: http://paste.ubuntu.com/16288582/

**Comment by MoNTE48** [comment]
@Wayward1 minetest - contains an error in build script. MultiCraft - oops, bug in java code. I'll kill your programmer :) But errors in the build script does not have.

**Comment by MoNTE48** [comment]
@Wayward1 replace the files in the vorbis-ogg files on this commit. https://github.com/MoNTE48/libvorbis-android/tree/4b26897e1362772f11c9bec8d37345b89c0781f6

**Comment by est31** [comment]
-j * worked fine before the update, I've spent really lots of time making that sure.

**Comment by Wayward1** [comment]
@MoNTE48, with those files added it now gives this: http://paste.ubuntu.com/16301617/.
Retrying make clean_all && make release once more for good measure.

**Comment by MoNTE48** [comment]
Good. Now I see bug in androidmanifest. 
@ShadowNinja ?

**Comment by Wayward1** [comment]
I added the AndroidManifest.xml file from an earlier build to build/src/main, and now it fails with this: http://paste.ubuntu.com/16313232/

**Comment by MoNTE48** [comment]
@Wayward1 I'll be honest - I did not build Minetest almost a year :)
I just merge commits on MultiCraft, I correct bugs and build it. If ShadowNinja not help you before, I will be able to resolve this issue tomorrow.
(I suggest to use my Java part, but no, you want to use your code).

**Comment by est31** [comment]
@Wayward1 the new error is because you have a wrong manifest xml file. Don't do that, that won't fix the bug.

**Comment by Wayward1** [comment]
@est31, ah, ok. I figured as much. Thought it was worth a shot though :P 
@MoNTE48 I understand, and by the way, thank you for your help so far :) Also, I'd be willing to give your Java part a try, just let me know how

**Comment by ShadowNinja** [comment]
@Wayward1: If you properly checked it Minetest the manifest will exist.  See https://github.com/minetest/minetest/blob/master/build/android/src/main/AndroidManifest.xml .  Please make sure that you've done a proper clone and checked out the latest commit and haven't deleted anything.

**Comment by Wayward1** [comment]
@ShadowNinja, I always make a fresh clone with the latest Git. I'll try again though

**Comment by Wayward1** [comment]
...Ok, it was successfull this time. I apologize for all the time spent on this. The only thing I can think of is that my previous clone was somehow corrupted, perhaps by my spotty Wi-Fi connection (which I have since fixed). Thank you all for your help with this, I really appreciate it, even if this did turn out to be an error on my part.
