### ISSUE TITLE
New engine header

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4104]
![screenshot from 2016-05-10 00 24 24](https://cloud.githubusercontent.com/assets/3686677/15131209/f67b555e-1645-11e6-9eae-a2b9ad120704.png)

This is an early attempt at what i feel is a more suitable subgame-universal header for the engine, as discussed in #3890 I feel the current stone texture is not universal enough, it is MTGame-specific.
This uses the colours used in the obsidian texture, apart from the bright highlighting on the edges which has the hue of our sky.
I'm not submitting this for 0.4.14 but if people like it enough it could be.

![screenshot from 2016-05-10 00 42 30](https://cloud.githubusercontent.com/assets/3686677/15131472/1dc0465e-1648-11e6-8f8e-e2d20def10c8.png)

^ Current header

**Comment by est31** [comment]
The contrast between the dark color and the bright shadow makes it hard to read and look at.

**Comment by benrob0329** [comment]
Its nice, I'm just not sure if its really "Minetest".

It seems very dark compared to the old one, and compared to the rest of the UI.

**Comment by est31** [comment]
@benrob0329 its the engine logo and the engine tries to be game agnostic, the only constant is that it's a first person voxel game with crafting, etc. So it makes sense to say that the logo should follow that. However, if we show this logo to people new to minetest they might wonder what it is about.

I'm not really sure when and where its shown to users.

**Comment by rubenwardy** [comment]
I much prefer the stone, even for an engine logo

**Comment by yyt16384** [comment]
Can subgames override the header image? We can make a game-agnostic one for engine, and stone for mtgame.

The current image is too dark, though.

**Comment by PilzAdam** [comment]
> Can subgames override the header image? We can make a game-agnostic one for engine, and stone for mtgame.

Yes, this is how it currently works.

**Comment by SmallJoker** [comment]
I would like to see a new header image, it could be changed whenever a new version is released.
Just an idea. The submitted texture has a too high contrast but otherwise it looks good.

**Comment by benrob0329** [comment]
@paramat could you please post the header image itself? I would like to try and tone the contrast down a bit.

**Comment by Ferk** [comment]
The pixel in the corners should have a transitioning color, it's very strange that the bottom left pixel is deep black and suddenly it's bright right above. The stone textured letters did this right.
Also, imho there should be a 1 pixel space in between each letter.

**Comment by Ferk** [comment]
Some experimenting:
![image](http://i.imgur.com/CfTDaRU.png)

**Comment by paramat** [comment]
Good points, my harsh contrast and lack of corner bevels was intentional, but i'll probably update this based on your feedback.

**Comment by paramat** [comment]
I'll re-open an issue or PR if or when i have something good enough.
