### ISSUE TITLE
Add an API for in game text?

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#4105]
Something similar to signs_lib, but using actual fonts, and allowing any node / entity / texture to have text would help with things like:

    Readable Signs
    LCDs / Screens
    Text on HUD (or does this already exist?)
    Custom nametags for mobs/areas
    Ect

It could be done internally with entities, or with dynamic textures.

Advantage over using a mod: You don't add 256 extra images (or more, if you have UTF-8 characters for other languages) and it allows for a unified API.

**Comment by C1ffisme** [comment]
I think this is a duplicate, I seem to remember an older issue about this...

**Comment by rubenwardy** [comment]
Duplicate: #1367

**Comment by benrob0329** [comment]
Darn it, I'll close this one.
