### ISSUE TITLE
Requesting override of on_cheat via mods

### ISSUE THREAD

**Issue by thePalindrome** [minetest/minetest#4108]
Given that the minetest server will revert any "cheating changes" by a player, I would like the ability to simply return false from an on_cheat handler to drop the cheat.

Possible Implementation:
change ScriptApiPlayer::on_cheat to use RUN_CALLBACKS_MODE_AND_SC

Possible Uses:
Vehicles (why would you ever drive a car if you can't go faster than walking pace?)
Bionic Arms ( interacted too far would prevent this )
Generally any mod that could bend physics in certain circumstances

Known Use: `sprint` causes slight rubberbanding due to overzealous anti-cheat.

**Comment by thePalindrome** [comment]
One policy oriented question:
Would we want the register_on_cheat callbacks to short circuit?
Is it realistic to assume side effects from callbacks?

**Comment by rubenwardy** [comment]
* **vehicles** - could be fixed by disabling move too fast when attached to an entity.
* **bionic arms** - interact too far should take tool distance into account.
* **sprint** - move too fast should take physics overrides into account.

**Comment by everamzah** [comment]
None of those things are currently available, however?  I admit I have recently looked for the ability to do what this issue is suggesting.

**Comment by PilzAdam** [comment]
@rubenwardy these are things that the engine should do anyway, regardless of mods.

**Comment by rubenwardy** [comment]
> @rubenwardy these are things that the engine should do anyway, regardless of mods.

...that's what I'm saying, the use cases mentioned should be solved by the engine.

**Comment by thePalindrome** [comment]
Really the only reason I'm suggesting allowing mod overrides in this case is because I get the feeling that there will be circumstances where a mod would want to prevent the server from reverting a "cheat" otherwise it becomes a matter of figuring out any instance where a "cheat" wouldn't be cheating, which has to follow the cycle of engine releases.

**Comment by PilzAdam** [comment]
@thePalindrome I see your point here, but I'm not fully convinced that there is an actual use-case for this. We would need at least one valid example where mods add functionality that triggers the engine's anti-cheat, even if the anti-cheat is implemented properly (i.e. it properly handles stuff like your initial 3 examples)

**Comment by everamzah** [comment]
I made a simple sprinting mod that doubles the player's speed using set_physics_override when holding AUX1 ('Use', [E] by default).  The mod works as expected as long as the player has the fast priv.  If the player doesn't have the fast priv, then they're position is constantly reset and movement is very glitchy.  https://forum.minetest.net/viewtopic.php?f=9&t=14768

Is there a way to comfortably set (increase) a player's speed using set_physics_override without disabling anticheat?  In the past I have set joining players speed to 0.5 and used set_physics_override to speed=1 to simulate an increase, without having to disable anticheat, but I think that is a not as nice as just setting speed=2.

**Comment by rubenwardy** [comment]
Are there any valid usecases for this pr that can't be solved in better ways?

**Comment by thePalindrome** [comment]
I'm not seeing any good reason to allow mods to bypass anti-cheat, so I guess I'll get started on it.

**Comment by rubenwardy** [comment]
Apparently the speed check has been fixed a while ago: https://github.com/minetest/minetest/issues/2356
I guess the fix didn't work

**Comment by kwolekr** [comment]
Anticheat should be bypassable simply because the role of the Minetest core is just that, a core - not a game.  Games decide what cheating is.

**Comment by est31** [comment]
I'm with @rubenwardy on this. Minetest might be an engine but why should it offer functionality without an usecase. There is a setting for turning anticheat on/off. Everything else should be done by the engine code.

**Comment by everamzah** [comment]
So if I want to use physics override to increase a player's speed (sprint), I also must disable anticheat and allow (cheating) players to hit others from any distance?

I'd open an appropriate issue, but there's probably already five of them (!) and I'm afraid this is old news by now.

**Comment by thePalindrome** [comment]
Could we get somebody assigned, or at least designated to work on this?

We seem to be in agreement that the anti-cheat needs to take certain factors in account.

I would be willing to work on this if requested, but setting a milestone and assigning somebody would at least bring us one step closer to settling this.

**Comment by est31** [comment]
I don't see any issues right now. Anticheat is successfully bypassed for all examples you brought.

**Comment by thePalindrome** [comment]
Which commit fixed these?

**Comment by est31** [comment]
@thePalindrome it never was a bug, at least it wasn't one when you opened it:

1. if a mod sets the position for a player, like with a teleporter, or a mod attaches a player to an entitiy, like with a vessel, then there are no "moved too fast" checks run.

1. if a mod interacts on behalf of a player, like with bionic arms, then the interact isn't registered as player event and therefore (shouldn't) be checked by the engine.

1. same goes for sprint mods, those should be working as well. But if you still experience problems, can you open a new bug report with example code?

**Comment by everamzah** [comment]
I opened a fresh issue with a video showing issue 3.  Anticheat has always been, and still is, broken on sprint mods.
https://github.com/minetest/minetest/issues/4291
https://www.youtube.com/watch?v=_FjERImCPxk
