### ISSUE TITLE
Ubuntu devs should be installing git, not git-core

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#4109]
Readme.txt should be changed to reflect this, and I'm pretty sure Ubuntu inherited this change from Debian. If you look at Ubuntu's gir-core, the description going back to 12.04 all say "obsolete" and the package description says:

> This is a transitional dummy package.  The 'git-core' package has been renamed to 'git', which has been installed automatically.  This git-core package is now obsolete, and can safely be removed from the system if no other package depends on it.

http://packages.ubuntu.com/search?keywords=git-core&searchon=names&suite=all&section=all
https://tracker.debian.org/pkg/git

**Comment by sofar** [comment]
Send a patch? the patch would be shorter than this issue?

**Comment by mtango688** [comment]
I don't know... Search and replace "sudo apt-get install git-core" with "sudo apt-get install git" I guess.

Anyway, I always prefer issues on trivial things like this... And going through the Debian changelog is interesting. Did you know that they switched the naming over back in 2010?

1:1.7.0.4-2~exp0 is the exact point where they did that.

**Comment by sofar** [comment]
1. Go to this URL:

https://github.com/minetest/minetest/edit/master/README.txt

2. Edit the file in the webpage

3. Fill in a description and summary, and click the button

4. then click the green button that says "create pull request"

**Comment by est31** [comment]
I agree to the change being done for ubuntu, but I wonder what the fedora guide should read.

**Comment by benrob0329** [comment]
Should be something like this:

"sudo dnf install git"

**Comment by benrob0329** [comment]
https://apps.fedoraproject.org/packages/

**Comment by Zeno-** [comment]
Yes, Fedora is dnf install git (or, prior to fedora 22, yum install git). 

Standard users in Fedora are not sudoers and I don't know if it's really necessary as people know that you have to be root somehow (either because they've added themselves to sudoers, or they use su -, or they use su - c "dnf ...", or whatever other method they prefer... if it's there though it's not a big deal

**Comment by benrob0329** [comment]
When you install you have the option of making your user an admin/sudoer.

**Comment by mtango688** [comment]
Well, git-core is still git-core in Fedora. On a side note, for openSUSE the command is

`sudo zypper install git-core`

Or just click on "Direct install" here https://software.opensuse.org/package/git-core?search_term=git-core
