### ISSUE TITLE
Android: "Provided world path doesn't exist" if chosing singleplayer on first run

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4111]
Steps to reproduce:

If you remove/rename the Minetest folder from your sd card, start minetest as a "first run", and immediately tap on the singleplayer button, you will get an "Provided world path doesn't exist" error.

If you change tabs (and change them back), or restart minetest, you can play singleplayer. Still, the bug is bad for everyone first trying minetest, they will think singleplayer is completely broken.

I've tested the 0.4.13 build from f-droid and couldn't reproduce. This also means that this bug is no dupe of #2971. @ShadowNinja can reproduce it as well.

**Comment by est31** [comment]
Logcat excerpt from when you press the singleplayer button (timestamps are all almost the same, there is no user interaction between):
```
INFO[Main]: Searching worlds...
INFO[Main]:   In /storage/sdcard0/Minetest/worlds: 
INFO[Main]: singleplayerworld 
INFO[Main]: 1 found.
INFO[Main]: Selected world: [--world parameter] [new] [/storage/sdcard0/Minetest/worlds/world]
ERROR[Main]: Provided world path doesn't exist: /storage/sdcard0/Minetest/worlds/world
[...]
INFO[Main]: Searching worlds...
INFO[Main]:   In /storage/sdcard0/Minetest/worlds: 
INFO[Main]: singleplayerworld 
INFO[Main]: 1 found.
INFO[Main]: Initializing world at /storage/sdcard0/Minetest/worlds/singleplayerworld
INFO[Main]: Searching worlds...
INFO[Main]:   In /storage/sdcard0/Minetest/worlds: 
INFO[Main]: singleplayerworld 
INFO[Main]: 1 found.
```

**Comment by est31** [comment]
I'm adding the blocker tag as its really not something nice for new users, and as its very easily reproducible.

**Comment by Wayward1** [comment]
I can confirm

**Comment by Rui914** [comment]
I'm sorry about my mistake.
Cause: 95446f4

**Comment by Rui914** [comment]
#4113
