### ISSUE TITLE
Android mainmenu: can't leave change keys dialog

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4115]
In the current android mainmenu you can open the change keys dialog by navigating to the settings tab from the mainmenu. Once you have opened it you can't close it anymore, the save/cancel buttons dont work.

I suggest that the button should be removed on android, as it is a touch device. It has already been done for the esc menu, where you can reach the change keys dialog on the desktop version, but not on the android version.

**Comment by est31** [comment]
I think its a blocker as its easy to reproduce + fix and it is bad enough for the players.

**Comment by est31** [comment]
Thanks to @Fixer-007 for discovering this

**Comment by ShadowNinja** [comment]
Android is NOT touch-exclusive.  The menu should be fixed for users with keyboards on Android.

**Comment by est31** [comment]
@ShadowNinja they still can edit minetest.conf.

**Comment by ShadowNinja** [comment]
@est31: Yes, but that's difficult, especially on Android.
