### ISSUE TITLE
Client: assertion failure of `f->liquid_type == LIQUID_SOURCE'

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4118]
In builds with assertions enabled, clients can fail with the following error message when connecting to certain servers:

```
minetest: /build/minetest-kUVrrd/minetest-201605121646/src/nodedef.cpp:938: virtual void CNodeDefManager::updateTextures(IGameDef*, void (*)(void*, irr::u32, irr::u32), void*): Assertion `f->liquid_type == LIQUID_SOURCE' failed.
```

Probably its because of a node trying to specify a liquid without also setting the liquid draw type.

Its a mod problem it seems which generates this kind of buggy nodedef, and which causes the client to crash.

There are two problems here I think:
1. (not such a big problem, as its "only" the client which crashes): The server can make clients crash
2. (the main problem): The server should detect itself that there is something wrong, and give a meaningful error message when parsing the lua based nodedef at server start. Or if there is no reason for the assertion to be there, it should be removed.

Originally reported by @ChaosWormz over irc.

**Comment by est31** [comment]
Not adding blocker label as I think it is a bug but "only" a minor one, and probably an older one as well.

Also, it should only affect debug client builds, release builds seem to work.

**Comment by paramat** [comment]
Yeah after release.

**Comment by taikedz** [comment]
I just started getting this today; I was connected to that server yesterday with no problems (Extreme Survival Minetest City - for info if you want to try to repro)

minetest: /build/minetest-bJwx9_/minetest-0.4.13/src/nodedef.cpp:839: virtual void CNodeDefManager::updateTextures(IGameDef*, void (*)(void*, irr::u32, irr::u32), void*): Assertion `f->liquid_type == LIQUID_SOURCE' failed.
Aborted (core dumped)
tai@gbx:~$ minetest --version
Minetest 0.4.13
Using Irrlicht 1.8.1
Build info: VER=0.4.13 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
tai@gbx:~$ uname -a
Linux gbx 4.2.0-36-generic #41-Ubuntu SMP Mon Apr 18 15:49:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
tai@gbx:~$ cat /etc/apt/
apt.conf.d/        sources.list       sources.list.save  trusted.gpg~       
preferences.d/     sources.list.d/    trusted.gpg        trusted.gpg.d/     
tai@gbx:~$ cat /etc/apt/sources.list.d/minetestppa.list 
deb http://ppa.launchpad.net/minetestdevs/stable/ubuntu wily main 
deb-src http://ppa.launchpad.net/minetestdevs/stable/ubuntu wily main

**Comment by est31** [comment]
Its a mod and server problem. You can contact the admin on the forum page of the server or via forum PM.
