### ISSUE TITLE
Android: missing "delete world" button

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4120]
I think this button was present in 0.4.13 build but now it is gone.
Android build needs "delete world" button, right now it is impossible to delete in in game, only via file manager.

Ver: mt 0.4.13-fb762c0a-Android (from Zeno), Kitkat 4.4.2

Edit: it is not "Feature Request", if button was lost via merging/bug then it is regression that needs bugfix.

**Comment by rubenwardy** [comment]
It's in the settings tab, "reset world" or something.
At least in the 0.4.13 version.
But this isn't a good intuitive place for it.

**Comment by Fixer-007** [comment]
I don't see it in settings tab anymore.

**Comment by paramat** [comment]
We can consider this after release.

**Comment by nerzhul** [comment]
@paramat i don't think we could defer it. It's important for user to remove worlds if they want. Many worlds can be created on a single device in 6-10 months

**Comment by rubenwardy** [comment]
> I propose delaying the android release or giving android maintainers the right to release patches before 0.4.15
> Preferably both if there is a regression, and the later if there is no regression

**Comment by est31** [comment]
I too think it should be done before the release.
