### ISSUE TITLE
Add option to block nametags by walls/blocks

### ISSUE THREAD

**Issue by xunto** [minetest/minetest#4122]
I don't know if it is a feature-request or complaining but I don't know what was the purpose of moving nametags to camera.h

It's uneasy now to normally implement nametags that isn't visible through walls. 

It's actually a very important feature for shooter mods, roleplay servers(this one even more important for me) and etc

I don't know what is the best way to code it for minetest, so I can't do it myself. 

Waiting for your proposes and advices.

**Comment by asl97** [comment]
https://github.com/minetest/minetest/pull/3712

**Comment by Fixer-007** [comment]
I remember pretty long discussion of where to move it, it helped to fix very nasty water and window opacity bugs.

**Comment by Fixer-007** [comment]
Could you rename your PR to something more explanatory? Not just "Nametags" but "Add option to block nametags by walls/blocks" or similar...

**Comment by paramat** [comment]
Would be good.
Currently there is serverside control of each player's nametag as seen by all clients. Also we have clientside toggling of nametag visibility with F1.
This feature would need the ability to hide a particular player's nametag from a particular player, based on line of sight.

**Comment by paramat** [comment]
Related to #5996  as it is for the visibility of certain tags to certain players.

**Comment by paramat** [comment]
Here's a mod solution https://forum.minetest.net/viewtopic.php?f=9&t=19401

**Comment by paramat** [comment]
This would be very intensive, having to look for nodes along a line from observer to player, over often very long distances. The only practical way is to have an actual entity above the player head, as in the mod, but then the name gets smaller with distance, plus other issues.

Any core dev support or thoughts?

**Comment by SmallJoker** [comment]
Assuming this is for short distances (~4 mapblocks) only, then it could be implemented with the Raycast functions. But as soon the line of sight crosses an unloaded/not sent mapblock it's not clear what to do: Hide or show?

**Comment by rubenwardy** [comment]
> Assuming this is for short distances (~4 mapblocks) only, then it could be implemented with the Raycast functions

The better way for this would be using a depth buffer, and this would be fast and fairly easy. The issue then would again be unloaded blocks client side

**Comment by paramat** [comment]
Closed due to 2 years with no core dev support, but will be reopened if supported by a core dev.
