### ISSUE TITLE
Remove showing description as infotext

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4131]
![screenshot_20160516_230649](https://cloud.githubusercontent.com/assets/3686677/15305433/003e9766-1bbb-11e6-87df-3ccc61465c40.png)

![screenshot_20160516_204715](https://cloud.githubusercontent.com/assets/3686677/15301792/7e6f4bc6-1ba7-11e6-9256-aeff1f0e6605.png)

See #3547
Irritating and unnecessary for most things.

**Comment by PilzAdam** [comment]
Chests explicitly set the infotext: https://github.com/minetest/minetest_game/blob/master/mods/default/nodes.lua#L1450

**Comment by sofar** [comment]
Doesn't seem to be any good reason for that (The fact that the locked chest does it is fine, of course). So we could just remove that line.

**Comment by paramat** [comment]
Updated, i see it's default for item entities, and yes i would like to remove it from chests too.

**Comment by C1ffisme** [comment]
We really shouldn't need it on furnaces, either, the only problem is that furnace formspecs update too slowly for any major detail.

**Comment by paramat** [comment]
It only appears when furnace is active, which is ok.

**Comment by paramat** [comment]
PR #4134

**Comment by MoNTE48** [comment]
I liked the description. This should be the setting.

**Comment by Calinou** [comment]
I would rather keep infotexts, since they should you can actually interact with the items, much like RTCW/Wolfenstein: Enemy Territory's "interact" icons when near an object that you can interact with.

**Comment by C1ffisme** [comment]
@Calinou That might be interesting, maybe a small image near the crosshair if metadata is present?

**Comment by paramat** [comment]
Calinou, maybe for chests, but certainly not for every node item.

**Comment by paramat** [comment]
#4134 is merged.
