### ISSUE TITLE
Somewhat random crashes because of errors in mutex.cpp

### ISSUE THREAD

**Issue by orwell96** [minetest/minetest#4141]
Since the 0.4.14 release, Minetest (installed from Ubuntu PPA minetestdevs) sometimes crashes because of the following error:

intel_do_flush_locked failed: I/O Error
AL lib: (EE) alc_cleanup: 1 device not closed
minetest: /build/minetest-4egrtW/minetest-0.4.14/src/threading/mutex.cpp:87: void Mutex::lock(): Assertion »!ret« failed.
Cancelled (written memory dump)

(some error descriptions translated to English)
System:
Kubuntu 15.10 (but running LXDE desktop)
Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz

If you tell me where it is on my system, I can provide the memory dump.

**Comment by Fixer-007** [comment]
Related to https://github.com/minetest/minetest/issues/4129 ?

**Comment by orwell96** [comment]
yup

**Comment by sfan5** [comment]
duplicate
