### ISSUE TITLE
Item description bug

### ISSUE THREAD

**Issue by cdqwertz** [minetest/minetest#4142]
I think the most of you know that I am working on a subgame called RPGtest. RPGtest displays the level, damage... of a tool in the item description. Since 0.4.14 is out it looks like this:

![bug](https://cloud.githubusercontent.com/assets/12814327/15386508/8614e1bc-1da8-11e6-97d5-4c8c2087df7f.png)

**Comment by Amaz1** [comment]
I think that this was caused by 21079cc8ebae0bf694c1903c07bf3e1517feab99

**Comment by Zeno-** [comment]
Can you please give an itemstring for an item that shows the bug? This is what I see:

![snapshot19](https://cloud.githubusercontent.com/assets/5899883/15416607/9cb6c212-1e90-11e6-875d-938e11a1f3f6.jpg)

**Comment by cdqwertz** [comment]
`minetest --version
Minetest 0.4.14-dev (Linux)
Using Irrlicht 1.8.1
Build info: VER=0.4.14-dev BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."
`

**Comment by Zeno-** [comment]
#4145

**Comment by Zeno-** [comment]
88acda0

**Comment by Zeno-** [comment]
This is related to irrlicht versions... perhaps there is an issue with the macro?

**Comment by Zeno-** [comment]
Yes, the macro that checks the irrlicht version is incorrect. Whoops

**Comment by paramat** [comment]
See #4299 for bug re-occurence.

**Comment by nerzhul** [comment]
@cdqwertz is this always the case ?

**Comment by Zeno-** [comment]
It's the macro for irrlicht version that needs fixing

**Comment by paramat** [comment]
@cdqwertz @theraven262 more details needed, and link to code that reproduces the bug, to help us fix this.

**Comment by paramat** [comment]
![screenshot_20171206_062740](https://user-images.githubusercontent.com/3686677/33647819-d281925c-da4e-11e7-952e-02cb48e873b8.png)

No bug in latest MT.

**Comment by paramat** [comment]
Silly question but i'm having trouble running 'minetest --version', in what directory and game state do i enter this command?

**Comment by paramat** [comment]
Thanks.

**Comment by paramat** [comment]
Anyone still experiencing this?

**Comment by paramat** [comment]
Is anyone experiencing this? Apparently it depends on Irrlicht version.

**Comment by paramat** [comment]
Apparently this bug occurs with Irrlicht versions before 1.8.2.

**Comment by paramat** [comment]
This bug has not been reproduced since MT 0.4.14, and we have merged the bugfix https://github.com/minetest/minetest/commit/8a1a9fdc24d29419422f0fb41095fd0388c4be9e since then, see PR thread #4766 
So #4302 should have been closed but wasn't.
I made #6822 to adopt it but that wasn't necessary, will close this and that.
