### ISSUE TITLE
Mapgen API

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4144]
As far as I understand mapgens, lua mods are executed after the decoration from the default c++ mapgen, so lua mods have to deal with stuff that is already generated

In minetest caves are neglected. The default caves (v7) are not very pleasant and modders don't have a chance to change this without causing other issues like flying or destroyed nodes.

I would suggest that generators are executed by priority, ordered by terrain, caves, dungeons, structures like buildings and plants last, independently if lua or c++

I suggest something like register_terrain, register_biomes, register_caves, register_structures, register_plants and whatever I have forgot like ores or mods like 3D stone biomes, which should be executed after terrain to give cavegens the ability to use this information (e.g. don't dig)

Currently it would be necessary to write everything in lua and ignore the built in mapgens at all

I know that this would be a lot of work and would cause incompatibility with existing mods, but it would provide more flexibility for the future

**Comment by C1ffisme** [comment]
> As far as I understand mapgens, lua mods are executed after the decoration from the default c++ mapgen, so lua mods have to deal with stuff that is already generated

Actually, they change the mapgen type to "singlenode" which contains only air. So this isn't a problem.

**Comment by MarkuBu** [comment]
I know that I can use singlenode and do my own stuff. But that's not what I mean.

**Comment by paramat** [comment]
Dev Hmmmm is currently re-organising mapgen architecture, it will be more flexible and modular in future.

> so lua mods have to deal with stuff that is already generated

Mgv6 biomes and flora are hard-coded, but in all other mapgens you can use a mod to first 'clear' the existing registered ores, biomes and decorations:
```
minetest.clear_registered_biomes()
minetest.clear_registered_ores()
minetest.clear_registered_decorations()
``` 
and then register your own.
There is also a mapgen flag to disable decorations (flora).

> The default caves (v7) are not very pleasant and modders don't have a chance to change this without causing other issues like flying or destroyed nodes.

You can change the tunnel noise parameters and tunnel width. You can also disable caves entirely with a mapgen flag.

> I would suggest that generators are executed by priority

They are ordered for good reasons https://github.com/minetest/minetest/blob/master/src/mapgen_v7.cpp#L270 line 270 onwards.

> I suggest something like register_terrain, register_biomes, register_caves, register_structures, register_plants and whatever I have forgot like ores or mods like 3D stone biomes, which should be executed after terrain

We have register ores, biomes, decorations, these are generated after basic terrain.

**Comment by MarkuBu** [comment]
I know that I can clear things and I know that I can disable things with flags. But it is ineficient to write and execute the same code twice, especially if I have to replace C++ code with lua.

What I mean is exactly this part of code you linked to. The order is hard coded. You can disable single calls like caves and dungeons, but you can't replace them at the same position. 

Replace this hard coded part with a list of function calls, which can be replaced by a mod. Then you can use all C++ parts from the mapgen and replace single parts with a lua mod without changing the execution order.


for example:
c++ terrain, c++ biome, lua cave, c++ decoration

currently it would look like this
c++ terrain, c++ biome, c++ decoration, lua cave

> Dev Hmmmm is currently re-organising mapgen architecture, it will be more flexible and modular in future.

With the current concept it is easyer to write the whole mapgen in lua. Maybe the new architecture will look like my suggestion?

**Comment by MarkuBu** [comment]
> There is also a mapgen flag to disable decorations (flora).

I try to explain what I do. I'm working on a mod that generates v6 caves for other mapgens. The problem is, that this mapgen can replace nodes with air a little bit over the ground. Because the decoration is generated before the cavegen is executed the cavegen can remove trees or plants floating in the air.

I try to disable decorations 

`minetest.set_mapgen_params({flags="nodecorations"})`

and add the decoration after the cave generation

```
generateCaves(max_stone_height)
vm:set_data(data)
minetest.generate_decorations(vm, minp, maxp)
vm:set_lighting({day=0,night=0},{x=minp.x,y=emin.y,z=minp.z},maxp)
vm:calc_lighting({x=minp.x,y=emin.y,z=minp.z},maxp)
vm:update_liquids()
vm:write_to_map()
```

Now the biomes are totally messed up. The lumin tree from Valleys Helper mod spawn in the desert, jungletrees spawn eveywhere, even in snow biomes, trees in snow biomes are not covered with snow and the forests look strange at all. There is no more jungle biome or anything else. The trees are just mixed together.

So the only solution I currently see is the ability to execute a lua cavegen instead of the original from the mapgen after the terrain, but before everything else.

**Comment by paramat** [comment]
Currently trees and leaves are 'is_ground_content = true' which means they are removed by cavegen, you could override default nodes to make them 'false' then make your lua cavegen check for 'is_ground_content''.

**Comment by paramat** [comment]
:-1: Re-reading this i don't see justification for such a big task and added complexity.
