### ISSUE TITLE
The Night sky's colors look ugly.

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#4146]
![better colors](https://cloud.githubusercontent.com/assets/9893266/15432965/e81e492a-1e75-11e6-8753-b184a3b0af62.png)

(On the left, we have the current night sky, and on the right, we have the night sky with some colours picked from a Minecraft screenshot. The Hotbar on the right has also been given less brightness and more contrast for effect.)

Currently, the night sky in Minetest looks a bit too bright, and doesn't have a lot of contrast or colour. It might fit well if you take a screenshot in a city, but in the wilderness it looks far too bright.

![screenshot_20160520_103435](https://cloud.githubusercontent.com/assets/9893266/15433290/5d80480c-1e77-11e6-8a97-c5c3e77618ce.png)

(Another edited screenshot, just to see if people like it.)

**Comment by benrob0329** [comment]
I would have to say that a darker sky looks better.

But also keep in mind that there is always a full moon in Minetest, so the sky is bound to look a little brighter than normal.

**Comment by C1ffisme** [comment]
@benrob0329 I also don't like how grey the sky looks. It looks too foggy, almost like a second layer of clouds.

**Comment by benrob0329** [comment]
Isn't that the point of grey sky?

**Comment by paramat** [comment]
+1 darker and bluer looks better. Full moon tends to produce a dark blue.

**Comment by C1ffisme** [comment]
@paramat Yeah, the blue in the first screenshot (right part) isn't the best, though. It also has to be done so that it doesn't look like you are in space.

@benrob0329 I'm not sure if that really works, since the cloud layer doesn't appear in the day. And you can see stars through it. I'd rather the colour looked a bit less like city smog.

**Comment by 0-afflatus** [comment]
I agree darker and bluer would be better. I think it looks like constant astronomical twilight rather than smog, but that may be due to my monitor settings.

**Comment by paramat** [comment]
I'm experimenting in this branch https://github.com/paramat/minetest/tree/nightsky
So far the only way i can deepen night sky is to make day sky a deeper blue as well, the effect on night sky is minimal when i do this. I'll ask celeron55 for advice.

![deeperblue](https://cloud.githubusercontent.com/assets/3686677/15524498/fc1ffcfe-221a-11e6-818e-d94f3584f975.png)

![screenshot_20160525_013625](https://cloud.githubusercontent.com/assets/3686677/15524499/ffa7de00-221a-11e6-8750-2adacdd0f855.png)

**Comment by yyt16384** [comment]
Should sky color be a client setting?

**Comment by yyt16384** [comment]
Should sky color be a client setting?

**Comment by paramat** [comment]
![screenshot_20160526_010739](https://cloud.githubusercontent.com/assets/3686677/15559954/900c1efc-22de-11e6-9a5b-c98fe119da12.png)

Some progress, showing that black is possible.

**Comment by C1ffisme** [comment]
@paramat I might make the clouds just a tad less grey, or more transparent, to look a bit less smoggy, and contrast less. (Maybe white-er clouds?)

**Comment by paramat** [comment]
![screenshot_20160526_011946](https://cloud.githubusercontent.com/assets/3686677/15560101/1e05d4fe-22e0-11e6-9995-f787bd1647c7.png)

Example of a dark blue, same hue as daytime sky, but darker and more saturation. Looks suitable for a sky lit by a full moon.

**Comment by C1ffisme** [comment]
@paramat Still a bit grey, but looking better... I might copy your image and have a go...

**Comment by paramat** [comment]
You can see the black sky RGB 0, 0, 0 ends up slightly grey too for some reason.

**Comment by C1ffisme** [comment]
@paramat Hmmm... That's strange...

**Comment by paramat** [comment]
Haven't updated my branch yet.

**Comment by C1ffisme** [comment]
Here are two tries at texturing those clouds. I actually like the clouds in picture 2 being a slight green color.

1: 
![clouds1](https://cloud.githubusercontent.com/assets/9893266/15560266/8f42899a-22af-11e6-9fc3-59b45f9035b8.png)

2:
![clouds2](https://cloud.githubusercontent.com/assets/9893266/15560267/8f48c8d2-22af-11e6-8ff3-396597c461e2.png)

(This is done with GIMP photoshopping, I couldn't find where the night time sky colors were specified in the code.)

**Comment by paramat** [comment]
Updated my branch.

**Comment by paramat** [comment]
#4163 is merged.
