### ISSUE TITLE
Add multiple nodeboxes for "wallmounted" drawtype

### ISSUE THREAD

**Issue by 4aiman** [minetest/minetest#415]
ATM if someone defines some complex nodebox for a node (2 is sufficient) he gets an "empty" node with only selection box. Screenshot: http://dl.dropbox.com/u/39772195/mt%20screens/bugs/screenshot_375265124.png (That is a 3d torch divided into 2 nodeboxes).

**Comment by est31** [comment]
This can be done using meshnodes. Therefore, closing.
