### ISSUE TITLE
Valleys Mapgen Heightmap Errors

### ISSUE THREAD

**Issue by duane-r** [minetest/minetest#4150]
When a mod requests a heightmap from valleys and the terrain height is outside of the current chunk, the heightmap table should contain numbers outside the altitude range of the current chunk, since valleys can't calculate exact values unless they're actually in the current chunk. The values I get back while generating chunks underground actually indicate maxp.y - 1 (it should be maxp.y + 1).

The relevant code in mapgen_valleys.cpp returns surface_y_int when it's higher than node_max.Y or lower than node_min.Y, which seems right. I also took a look at lua_api/l_mapgen.cpp, but it's so simple, I can't see it failing. I'm at a loss here.

```
		if (heightmap[index_2d] == -MAX_MAP_GENERATION_LIMIT) {
			s16 surface_y_int = myround(surface_y);
			if (surface_y_int > node_max.Y + 1 || surface_y_int < node_min.Y - 1) {
				// If surface_y is outside the chunk, it's good enough.
				heightmap[index_2d] = surface_y_int;
			} else {
				// If the ground is outside of this chunk, but surface_y
				// is within the chunk, give a value outside.
				heightmap[index_2d] = node_min.Y - 2;
			}
		}
```

This isn't a major issue, but it's annoying when you actually use heightmap in a mod.

**Comment by est31** [comment]
@kwolekr might help

**Comment by paramat** [comment]
```findGroundLevel()``` is called from ```updateHeightmap``` and should return the y of top of chunk when underground, which is correct. It only returns ```-MAX_MAP_GENERATION_LIMIT``` if no ground is found, so your code is only triggered in that situation.

> When a mod requests a heightmap from valleys and the terrain height is outside of the current chunk, the heightmap table should contain numbers outside the altitude range of the current chunk

Not possible, when underground, ground is found at chunk top, there's no way of knowing if that's actually true surface level or deep underground, so y of chunk top is returned correctly.

> The values I get back while generating chunks underground actually indicate maxp.y - 1

Odd, it should be maxp.y.

**Comment by duane-r** [comment]
It's very easy to get around anyway by scanning the table before you use it. It might not even be worth pursuing, if I'm the only one who's noticed it.

**Comment by paramat** [comment]
Reading my comment do you agree it's not a bug? Can i close?

**Comment by duane-r** [comment]
There's a bug somewhere, because I'm still getting maxp.y - 1, but it's probably not worth taking time on unless somebody else complains.

Here's the code I used to detect the problem:
```
local function detect_bull(heightmap, csize)
	local j = -31000
	local k = 0
	local cutoff = (csize.x * csize.z) * 0.3
	for i = 1, #heightmap do
		if j == heightmap[i] then
			k = k + 1
			if k > cutoff then
				print("maxp.y: "..maxp.y..", minp.y: "..minp.y..", heightmap stuck at: "..heightmap[i])
				return true
			end
		else
			k = 0
		end
		j = heightmap[i]
	end

	return false
end
```

This is the result at one chunk below sea level:

`maxp.y: -33, minp.y: -112, heightmap stuck at: -34`

**Comment by paramat** [comment]
Invalid now as code rewritten. While doing so i noticed very odd messing about with the heightmap so i'm unsurprised there was a problem.
