### ISSUE TITLE
Use spatial index for postgres rollback

### ISSUE THREAD

**Issue by iqualfragile** [minetest/minetest#4157]
This is just in advance:
If the rollback functionality will be implemented for the postres backend it will be a really good idea to use a spatial indexing method (GiST for postgres) otherwise queries involving distances (like all modifications around a block in range x) will be horribly slow (see https://github.com/minetest/minetest/issues/1613)

@nerzhul

**Comment by paramat** [comment]
Comments?

**Comment by iqualfragile** [comment]
given that shadowninjas contribution in #1613 lead to much win this is probably still important. i am not aware of the status of the postrges backend though.

**Comment by paramat** [comment]
Closed due to 2 years with no core dev support, but will be reopened if supported by a core dev.
