### ISSUE TITLE
Add multiple levels of slippery-ness

### ISSUE THREAD

**Issue by o-jasper** [minetest/minetest#4158]
Add a surface `friction` value to nodes, with some sensible(high or "infinite") default. I.e. ice is slippery. (slide, to add a search term that should find this)

Might also be nice to allow sounds to be associated with sliding, like with sand.

**Comment by paramat** [comment]
Related #817

**Comment by o-jasper** [comment]
Forgot to try that search term, i guess. Implementing it seems to be a matter of knowing the normal force. Seems to me that you basically need to have "all forces in" already. In which case you could try avoid "overstep", i.e. if speed relative goes over due to the timestep, you set it equal.

**Comment by o-jasper** [comment]
Got some code for a [jetpack/hoverboard](https://github.com/o-jasper/minetest-jetpack). It has some bouncing/sliding physics. Still probably needs a tweak so things that bounce down really hard don't get movement parallel to surface overly reduced.

**Comment by o-jasper** [comment]
#4182 , #817 related. Doesn't say much about how it is implemented? Probably fine.

**Comment by rubenwardy** [comment]
basically done by slippery, only binary currently

**Comment by paramat** [comment]
https://github.com/minetest/minetest/commit/fc13c00ef3e9b6f280146f3d77b6659fcc55a13c enables levels of slipperyness, but the API needs updating to use the levels.
