### ISSUE TITLE
Allow multible serverthreads

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4160]
Hi there, i just noticed, that i have an option to increase the emerge threads.
But why? The server one is the one with constantly the highes load!
We can have a powerful machine as we want when Minetest doesnt use the ressources!
Please allow Minetest better multithreading(!).

kind Regards

**Comment by nerzhul** [comment]
It's not possible to have multiple servers threads because Lua run into one thread mainly and many things depends of the same thread.
