### ISSUE TITLE
Skybox textures 

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4161]
I'm requesting custom Skybox textures to be added to the base game. (There should be an option to turn it on and off for the people that don't like it) they allow you to do stuff like [this](http://cdn.resourcepack.net/images/2015/02/Minecraft-Custom-Sky-Resource-Pack-for-minecraft-1.jpg) or [this](http://files.gamebanana.com/img/ss/textures/5339e646198dd.jpg) it also adds more customizability in texture packs (I think it would be a great feature for minetest) also this is inspired by #4146

**Comment by paramat** [comment]
We already have custom skybox.

**Comment by 0-afflatus** [comment]
Right, I thought we had custom skyboxes, but if they are fixed and break sun/moon/clouds operation that would make their usefulness pretty limited. I take it that the standard sky doesn't use textures apart from sun/moon and tonemaps? I did have a brief skim of sky.cpp, but I can't say I made much sense of it.

**Comment by tobyplowy** [comment]
@paramat how do I get it in my texture pack what is the PNG  calld? Could you make a template?

**Comment by tobyplowy** [comment]
@0-afflatus no the normal Skybox doesn't use any textures apart from the Sun Moon clouds now that I said that I'm not even sure if the clouds are a texture because ther texture is nowhere to be found. (And if there is I can't find it in the bace textures)

**Comment by sofar** [comment]
@tobyplowy texture packs can't change the skyboxes, you have to write a mod for that.

**Comment by paramat** [comment]
You can override sun and moon with your own textures and apply your own tonemaps to them to change colour through the day, clouds do not have a texture they are directly drawn by the engine.
Example of skybox code https://github.com/paramat/moonrealm/blob/master/init.lua#L207

**Comment by 0-afflatus** [comment]
> You can override sun and moon with your own textures and apply your own tonemaps to them to change colour through the day

And only client-side. 

I know we've been here before, but if anyone does have a go at customisable skyboxes it would be great if they could be modded per game or per world. I'm not going to hold my breath on that one as I know it would take a combination of genius and inspiration, which might currently be better employed fixing more urgent issues.

**Comment by sofar** [comment]
Sun and moon textures should be moddable, for exactly the same reason that skybox textures should be moddable.

**Comment by tobyplowy** [comment]
@true

**Comment by tobyplowy** [comment]
@paramat could custom Sky boxes be added to the base game (also why are clouds not a texture) also I found another cool thing that's possible with custom Sky box texture [this](http://www.retailsims.com/mcwp/wp-content/uploads/2014/05/FiberWIP_daySky_800x500.png)

**Comment by tobyplowy** [comment]
@0-afflatus one can only hope (all Jokes Aside this would be amazing)

**Comment by tobyplowy** [comment]
@paramat the Mod isn't working it says you can only use [a-z0-9_]

**Comment by paramat** [comment]
After download rename the mod to 'moonrealm'.

**Comment by tobyplowy** [comment]
@paramat thank you for the help (I tried the mod and it looks really awesome this is exactly what I wanted thx do you mind if I edit the textures for personal use of course)

**Comment by paramat** [comment]
Go ahead.

**Comment by tobyplowy** [comment]
![skybox](https://cloud.githubusercontent.com/assets/16853304/15602054/42411856-23f3-11e6-8e03-fc00cf734c69.png)

**Comment by tobyplowy** [comment]
@paramat It looks so nice ![skybox](https://cloud.githubusercontent.com/assets/16853304/15602054/42411856-23f3-11e6-8e03-fc00cf734c69.png)
But just one question how do I get rid of the anti-gravity and the other stuff

**Comment by tobyplowy** [comment]
@paramat could this be added to the base game?

**Comment by paramat** [comment]
Nope it's not remotely a suitable style, no drifting clouds eother.

**Comment by tobyplowy** [comment]
@paramat I was not talking about the texture I was talking about Sky box textures (by the way the texture is from Google Images :sweat_smile:

**Comment by 0-afflatus** [comment]
@tobyplowy we're talking about changes to the engine here, so the feature would be available in any game. Or did I misunderstand?

**Comment by tobyplowy** [comment]
@0-afflatus yes shuld be available in every game but it should be a setting. for the people that don't like it for some reason :smile:

**Comment by paramat** [comment]
:-1: Skybox is a specialist thing so i think it's fine to enable them in a mod.

tobyplowy please could you edit the first post to be more specific about the feature you are requesting?

**Comment by tobyplowy** [comment]
@paramat I've changed my first post I can't be more specific with it. So I hope it helps :smile:

**Comment by paramat** [comment]
Sorry this request makes no sense, we already have an API for custom skybox.
