### ISSUE TITLE
teleporting players seems to use a queue

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#4165]
If you use moveto (or setpos) to teleport a player multiple times, the player gets teleported to all the passed locations, l tested it.
So if you run this code:
```
for i = 1,10000 do
	player:moveto(pos1)
	player:moveto(pos2)
end
```
the server doesn't abort but delays a few ms, whereas the client needs to quit minetest because he/she just gets teleported constantly, he seems to do teleporting to positions from a position queue

l think code should be changed that there's a position_changed bool and a new_position vector.
If player:moveto(pos) is executed, position_changed is set to true and new_position is set to pos.
After returning from lua if position_changed is true then it's set to false and the player gets teleport information to new_position.

**Comment by paramat** [comment]
This is correct behaviour, the player is teleported to every location as defined by the code, if a mod is badly written and teleports rapidly that's the mod's fault.

**Comment by kwolekr** [comment]
Agreed, this is the expected behavior...

**Comment by sofar** [comment]
Mods abusing the API like this don't exist. If this patch would be merged, it would actually likely break mods that legitimately depend on this behavior. I know of a mod written by someone that does several teleports on purpose shortly after another... and that would be broken.

:-1:
