### ISSUE TITLE
Sapier's fix for the RESEND RELIABLE problem

### ISSUE THREAD

**Issue by OldCoder** [minetest/minetest#4171]
The Pull Request linked below is Sapier's fix for the RESEND RELIABLE problem, a network issue that has affected MT worlds for at least 1.5 years. The fix is relatively simple and is believed to be correct.

I've used the fix myself for over a year to keep a dozen worlds up and running; for me, MT wouldn't be possible without it. The fix has been tested, recently, in other worlds and seems to improve performance even in problematic cases such as residential hosting.

https://github.com/minetest/minetest/pull/4170

**Comment by est31** [comment]
The PR got merged as 7ea4a03c835d68a6fb58aa55aa6a6315ec80b79f
