### ISSUE TITLE
`minetest.get_register_*` corresponding to `minetest.register_`

### ISSUE THREAD

**Issue by o-jasper** [minetest/minetest#4176]
In one case, i want to access `sounds` in `minetest.register_node`, to use for the [jetpack thingy](https://github.com/o-jasper/minetest-jetpack) bumping into things. (i'd also like to suggest `sounds` like. I.e. `.footstep`, `.hit`(harder), `.scrape` as options. or a `.passthrough` sound going through foiliage, i'd just search in some order)

Not sure it is good to have the potential use to "derive" from `minetest.get_register_` to create new versions. Possibly better do via lua directly.

**Comment by rubenwardy** [comment]
use minetest.registered_item["default:dirt"] etc.

**Comment by o-jasper** [comment]
Can work with that. Still, don't see that [in the docs](http://dev.minetest.net/Global_Minetest_object#Register_something_to_core). Also for the node it is  `minetest.registered_node`, grepping for it. Also not entirely consistent; `minetest.registered_entities` is suddenly plural?(I myself am also split between whether such a thing should be plural)

**Comment by rubenwardy** [comment]
The developer wiki is not that docs - that's a community project.
This is the docs: [lua_api.txt](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L433) [lua_api.html](http://rubenwardy.com/minetest_modding_book/lua_api.html#registered-definitions-of-stuff).

And it's registered_items and nodes not item and node.

**Comment by rubenwardy** [comment]
That page you linked lists functions, and doesn't list members.
registered_* are documented in the pages of register_*, like here: [devwiki/minetest.register_node#Node_definition](http://dev.minetest.net/minetest.register_node#Node_definition).

**Comment by o-jasper** [comment]
Sorry to kindah waste your time..

**Comment by rubenwardy** [comment]
Don't worry about it :P
