### ISSUE TITLE
Possible GNU License Infrigement

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#4181]
I'm not so sure about how licenses work, but I believe that all forks of a GNU LGPL object must be licensed as GNU LGPL. (I could be wrong, sorry if this is nothing, and I'm being a noob.)

[Planet Build of Craft Google Play Store page](https://play.google.com/store/apps/details?id=com.roso2kosi.plblcraft&hl=en)

(My brother found this in a video, if you wonder where I found this.)

I believe the edited version has ads and such put in there, though I'm not sure yet. (I only glimpsed at my brother's video...)

**Comment by sofar** [comment]
> I believe that all forks of a GNU LGPL object must be licensed as GNU LGPL

Incorrect. The LGPL allows relicensing as long as the new license is not in conflict with the original license.

In general, relicensing of LGPL->GPL is allowed.

**Comment by benrob0329** [comment]
It says in the description:

Source licensed under LGPL v3: drive{dot}google{dot}com/open?id=0BzBGq_TeKVXkS1ZaZmFoNWdiX1E

**Comment by C1ffisme** [comment]
Oops! Minetest is Licensed under the LGPL, not GPL.

LGPL to LGPL.

Stupid me...

Sorry about this, I wasn't looking too far into this...

**Comment by C1ffisme** [comment]
Is using it for commercial purposes allowed by the GPL/LGPL license? (Advertisements or otherwise)

I tried searching for this on the [LGPL license page](http://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html) but couldn't get anything from Ctrl+F.

**Comment by sofar** [comment]
Monetization (ad revenue) isn't covered by the LGPL, so I believe (IANAL) that it is allowed. If people object, they have all the sources needed to make an ad-free version.

**Comment by C1ffisme** [comment]
Eh, that's true...

Sorry for just being plain stupid, but I suppose we all have to learn from our mistakes...

**Comment by sofar** [comment]
I don't mind, it's actually a completely sensible question.
