### ISSUE TITLE
Rework H/J/K keys (noclip, fast, fly) to avoid fog problems and player confusion

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4187]
Right now it works like this, for example `fly`:
Press K, you get either
`free_move enabled`
`free_move enabled (note: no 'fly' privilege')`
`free_move disabled`

This behaviour is not only confusing, but also has unexpected side effects, like this: https://i.imgur.com/GLQcc0l.png (daylight fog at -20000? wth? oh, it is `free_move enabled (note: no 'fly' privelege')` insanity.

How I imagine it.
If you have fly privilege:
`free_move enabled` or `free_move disabled`
If you have no fly privilege and press K you got only this:
`free_move is disabled on this server`, fly stays in disabled mode to avoid that fog problem I described above.

Same with other privs hotkeys.

Some useful code locations: https://github.com/minetest/minetest/blob/master/src/game.cpp#L4076

**Comment by SmallJoker** [comment]
`free_move is disabled on this server` is wrong information to the player. It rather should be called `Can not enable free_move (Privilege missing: fly)`

**Comment by Fixer-007** [comment]
Or this, yes

**Comment by paramat** [comment]
This happened to me and sofar too in the nether mod, we wondered if a dark skybox was needed.
https://github.com/minetest/minetest/blob/master/src/game.cpp#L4076 is in updateFrame() so i assume the bool is used for simplicity and speed. I'm not convinced this is a big enough problem to make the code more complex by checking player privs.

**Comment by sfan5** [comment]
You dont have to check player privs everytime, just don't set <code>free_move</code> to true if the player is missing privs.

**Comment by yyt16384** [comment]
What will happen if player has `free_move = true` and joins a world without `fly`?

Also, `free_move` and similar settings should really be per-world. Maybe we can add a system for per-world settings?

**Comment by Fixer-007** [comment]
>What will happen if player has free_move = true and joins a world without fly?

"free_move disabled on this server"

**Comment by rubenwardy** [comment]
You'd need to check for the privilege and update the setting when joining a world or being granted/revoked a priv

**Comment by yyt16384** [comment]
It is bad to update the global setting when joining a world. It should be made into a per-world setting first.

**Comment by paramat** [comment]
@Fixer-007 #4646 is merged, does that address your issue?

**Comment by sfan5** [comment]
@paramat the status texts shown by the game might still be a little confusing to players, but the daylight/fog problem is fixed now.

**Comment by Fixer-007** [comment]
Right now If I had free_move and noclip in singleplayer and joined multiplayer I will suddenly see white fog/sky even if I have no privs, thats still the problem, problem of enabled privileges on server where you don't have them and confusing set of options.

**Comment by paramat** [comment]
The issues were discussed further in #4646 
The first 2 features:
* Doesn't allow enabling free_move unless the fly privilege is given
* Doesn't allow enabling noclip unless the noclip privilege is given
Were not implemented and could still perhaps be done in some way.

**Comment by paramat** [comment]
@lhofhansl

**Comment by SmallJoker** [comment]
> but also has unexpected side effects, like this:

Sky color addressed in #4646
Fog color split to #9608

This issue contains roughly three bug reports, so please open a new one if the permission status text still needs fixing.
