### ISSUE TITLE
Ubuntu/Mint ppa should also have -dbgsym packages

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4188]
By installing `pkg-create-dbgsym` on debian/ubuntu when you build your deb package (with debuild -us -uc or similar), you will also get separate .ddeb with debug symbols included that are useful for debugging. Increases used space by ~100%.

I think this can be tried on https://launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds

More info about it here http://kylenubuntu.blogspot.com/2013/02/dbg-versus-dbgsym.html

**Comment by est31** [comment]
I'll give it a look.

**Comment by cjwatson** [comment]
@est31 contacted me on IRC about this, but is no longer online so I'm responding here.  It used to be that this required the assistance of Launchpad staff to change, but that is no longer the case and any owner of the PPA can set this themselves.  Go to "Change details" on the PPA and check "Build debug symbols" and "Publish debug symbols".

**Comment by est31** [comment]
Okay, I've checked the checkboxes, and the stable and daily ppas both have dbgsym packages. Many thanks @cjwatson for the answer!
