### ISSUE TITLE
Requests for a extensible Mapgen and BiomeManager

### ISSUE THREAD

**Issue by MillersMan** [minetest/minetest#4189]
As some might already have seen in the forum I'm working on the <a href="https://forum.minetest.net/viewtopic.php?f=14&t=14380">Canyon Mapgen</a> that creates physically plausible river networks and is written. The map-generation and biome-management are currently changing quite a lot and this could make it easier for me to implement newer features or on the other side make it even harder than it is already. Therefore here a list of planned features and their requirements on the engine. Note that the Mapgen itself doesn't use noise-maps but is a fractal that refines the noise together with the resulting environment:
1. Dry and wet areas: The Mapgen currently generates rivers that match to a homogeneous rain-fall over the whole world. While it's possible to make an area an desert by just assigning the right biome to it having plenty of wells will look strange. A better approach would be to adjust river density to match the biomes. For this to work right the Mapgen has to be in control of humidity- and heat-maps. Either by generating it itself or by overwriting it with the internally created one.
2. Special areas like glacier valleys: The Mapgen is capable to locally change the rules to create broader valleys and fill them which might create alpine glaciers that cut off at some point and act as a spring for a small river. But this doesn't work well alongside biomes as the the Mapgen must be able to tell for sure that this is a glacier biome and the valley is filled with ice that should be handled like water in other biomes. Best would be if the Mapgen could mark certain locations with a fixed biome or if it isn't supported by the game to disable the glacier feature.
3. Other ideas that don't have any further requirements compared to the previous ones: Weather related large-scale structures (e.g. Great Canyon like landscape etc), underground rivers, maybe settlement biomes (villages/cities) that could be connected by intelligently placed streets.

I'll extend this list once I have more ideas.

**Comment by 0-afflatus** [comment]
Currently the only way to store biome info is to have a different topsoil node for each biome. I would prefer to have each node store heat and humidity values - an idea that got thrown out with the bathwater of proller's weather system. There is also the little issue of how to store these data.

**Comment by rubenwardy** [comment]
@paramat  ?

**Comment by paramat** [comment]
Currently biomes and heat / humidity noises come after basic terrain generation (which is stone, air, water, river water only).

1. It might be fairly simple to allow a certain mapgen to define or create the heat and humidity distributions before it even creates the terrain, and pass these on to the biome generation.

2. Could be done by allowing a mapgen to create a heat / humidity distribution that is not a noise, or is forced to certain values in certain places. It may be a complex thing to do but that's up to the mapgen creator to work out. Allowing this may be fairly simple to do.

I'll consider it certainly, and it could be useful and provide interesting possibilities, it's just not a priority for 0.5, maybe after.

**Comment by rubenwardy** [comment]
Any support?
