### ISSUE TITLE
player visual_scale changes on attach, uses the entity's visual_scale

### ISSUE THREAD

**Issue by mauvebic** [minetest/minetest#419]
I have different entities with different visual_scales and when the player attaches to them it's own visual_scale changes to match the entity, giving something like this:

![ndmbo](https://cloud.githubusercontent.com/assets/3686677/20616552/e496fe6a-b2da-11e6-82c6-bc8d1af8f4c1.png)

![tanmp](https://cloud.githubusercontent.com/assets/3686677/20616554/e87b63fe-b2da-11e6-9ebe-12436fc8a0a3.png)

Dont know if bug or intended behaviour. Looks funny either way

**Comment by DS-Minetest** [comment]
since it would make big problems to mods, which already scale the player model down, here shouldnt be changed anything, i think
so, is the only reason to leave this issue open to prevent anyone complaining about the same?

**Comment by paramat** [comment]
I want to do something about this now. Often it is required to use 'visual_scale' for a vehicle that has 'visual = cube/wielditem' to scale it up, any attached player then becomes scaled in bizarre ways. However the behaviour may be useful and may be relied on.

I suggest that 'set attach()' API takes an additional 'child_scale' parameter to control this.

**Comment by paramat** [comment]
Searched for a long time and can't find it, maybe the attachment visual scale cannot be independent of parent visual scale?

**Comment by paramat** [comment]
Looked at code for a while, still cannot see what code is responsible for altering a player's visual scale when attached. Does anyone know?
I suggest that, for players only, visual scale is not altered when attached to another object.

I have written a few vehicle mods (that do not use models) and the current behaviour is a problem.
If i create a vehicle using `visual = "cube"`, it needs scaling up to be larger than a node, my 'mesecar' mod does this, but the player is also scaled up by the same amount, so has to be hidden inside the vehicle.
I now create vehicles using `visual = "wielditem"` or `"item"` as this allows the vehicle to be defined as a nodebox. Now the player size is tiny, the only workaround is to define the vehicle nodebox small and use `visual_size = {x = 2.0, y = 2.0},`. Seemingly related to that, objects with  `visual = "wielditem"` or `"item"`, unlike other visual types, have their visual scale hardcoded to half of the object property:
https://github.com/minetest/minetest/blob/4b6bff46e14c6215828da5ca9ad2cb79aa517a6e/src/client/content_cao.cpp#L740

**Comment by ClobberXD** [comment]
> Maybe it is simply inherent that a child object is scaled by the parent object [visual_size]?

If that behaviour is hard-coded in Irrlicht, then maybe MT should manually rescale the object by the inverse of the parent object's visual_size upon attachment, and the opposite upon detachment. Hacky though...

**Comment by paramat** [comment]
Yes i would like to avoid doing that, it may be too complex to be worth fixing.
I think this issue is not a big problem. Vehicles are usually models ("mesh"), and therefore have scale 1, are very rarely "cube", and there is a workaround for "wielditem" / "item".

**Comment by rubenwardy** [comment]
visual_scale should only apply to that entity, and a future scale feature (`player:set_scale()`) would propagate down the attachment tree and be interpolated

**Comment by appgurueu** [comment]
Not a bug. Visual scale is multiplied, which can be avoided by doing:
```lua
player:set_properties{visual_size = vector.divide(object:get_properties().visual_size, player:get_properties().visual_size)}
```
