### ISSUE TITLE
Sunrise glow texture is still visible after sunset

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4194]
To confirm go up a little to see horizon clearly, look in +X (East) direction, set /time 0:00
You will observe this: https://i.imgur.com/9Owwyfo.png

@paramat says it is probably "sunrise glow texture".

P.S. It is not a cloud and not a moon, I checked.

```
Minetest 0.4.14-xxx-d4457ef-dirty (Windows)
Using Irrlicht 1.8.1
Build info: VER=0.4.14-2060fd9-d4457ef-dirty BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."
```

**Comment by paramat** [comment]
Yeah as in https://github.com/minetest/minetest/blob/master/textures/base/pack/sunrisebg.png

**Comment by paramat** [comment]
Confirmed, it also gets stuck on the Western horizon too. It's not always visible though, sometimes if shifting back and forth in time it disappears.

**Comment by paramat** [comment]
It's material [2] and code is here https://github.com/minetest/minetest/blob/master/src/sky.cpp#L233

**Comment by Zeno-** [comment]
The bug is on this line: https://github.com/minetest/minetest/blob/master/src/sky.cpp#L239

**Comment by paramat** [comment]
That's the cause but i think the solution is to just alter some numbers, such as perhaps
```float y = -(1.0 - a) * 0.2;```
Change that 0.2 to 0.21 or something.

**Comment by paramat** [comment]
I think y is the downward displacement that puts the texture below the horizon, so using your white test texture just increase 0.2 slightly until your texture disappears behind the horizon.

**Comment by Zeno-** [comment]
<Zeno`> changing to float y = -(1.0 - a) * 0.255;  will fix the reported bug
<Zeno`> or even float y = -(1.0 - a) * 0.26; to make sure
<Zeno`> but it doesn't fix the sunrise not working in the first place (not like a real sunrise anyway)
<Zeno`> the glow doesn't appear until after the sun is fully risen (in minetest currently)
<Zeno`> the glow should appear before the sun rises

**Comment by paramat** [comment]
![screenshot_20160607_171744](https://cloud.githubusercontent.com/assets/3686677/15865977/cfd2d530-2cd4-11e6-90f6-4b4d12a68f87.png)

Changing the texture to solid white shows it is not completly below the horizon in day and nght, i'll tune that number until it is.

**Comment by paramat** [comment]
```float y = -(1.0 - a) * 0.22;``` is perfect.

**Comment by Zeno-** [comment]
3ef71ed
