### ISSUE TITLE
Texture packs should be able to override wield_image and inventory_image

### ISSUE THREAD

**Issue by infmagic2047** [minetest/minetest#4197]
They can already override `tiles`, and it would be nice to have the same for `wield_image` and `inventory_image`.

**Comment by sofar** [comment]
Texture packs work on a file name base. If a node has an inventory image defined then the texture pack can override it already.

Suggest closing. Proposing an on demand adding of custom wield images doesn't make things simpler.

**Comment by rubenwardy** [comment]
I think he's talking about texture overrides. See the file in docs.

**Comment by yyt16384** [comment]
Yes I'm talking about `override.txt`.

**Comment by 0-afflatus** [comment]
Interesting, this is a feature I wasn't aware of. Saying "it would be nice to have" isn't a strong reason, can you provide a more concrete use case / example?

**Comment by rubenwardy** [comment]
I created the texture override feature, it shouldn't be too hard to add this to it.

**Comment by yyt16384** [comment]
Use case: some mods decide to use the same image for `tiles` and `inventory_image`, and texture packs may want to override this.

Example: fences from minetest_game use a modified texture based on its `tiles` for `inventory_image`.

In some cases (like the fences) it is possible to override `tiles` instead, but if the image is also used elsewhere or it is a complex expression, it can be hard or impossible to get it right.

**Comment by yyt16384** [comment]
And here is an example where this is really needed: in pipeworks the inventory image of priority tube is generated with normal tube and `colorize`, so it is impossible to use a color other than the hardcoded one now.

**Comment by rubenwardy** [comment]
I started implementing this: https://github.com/rubenwardy/minetest/tree/text_over_inv
But I realised that it's harder than I thought it would be. Currently the updates are done in the NodeDef class, to add this the function would need to be moved somewhere better.

**Comment by tacotexmex** [comment]
To be able to automate texture building from an override.txt file would be really helpful in texture pack construction.

**Comment by Df458** [comment]
This feature, if it includes regular craftitems and tools as well, is vital for texture pack making. Assuming there is coredev support (seems that way since ruben started implementing it), I'll see if I can implement this in the next release cycle.
