### ISSUE TITLE
Call on_leaveplayer before shutdown in singleplayer

### ISSUE THREAD

**Issue by sapier** [minetest/minetest#420]

**Comment by nerzhul** [comment]
This issue is not a really issue

**Comment by RobertZenz** [comment]
This is really an issue, as `leaveplayer` is the perfect function for a mod to clean up its state, that might or might not involve the world directly.

Direct example: An entity is attached to the player which needs to be removed after the player is gone, the perfect function for that is `leaveplayer`, but it is not invoked in singleplayer which means that the entity happily lives on.

A workaround would be to *also* remove it in the `shutdown` function, that would mean to spread it over two points in the code.

**Comment by PilzAdam** [comment]
How does on_leaveplayer currently behave on a non singleplayer server, when clients are connected and the server shuts down?

**Comment by RobertZenz** [comment]
`leaveplayer` is not invoked on server shutdown...mh. I thought the players would be kicked first? Shouldn't that invoke `leaveplayer`?

**Comment by Wuzzy2** [comment]
I agree, this is needed.

**Comment by rubenwardy** [comment]
Surely this is solved by the server kicking players on shutdown?

**Comment by paramat** [comment]
:+1: I needed this a while ago.

**Comment by paramat** [comment]
^ Yeah sounds good.
This behaviour has caused me issues too.

**Comment by rubenwardy** [comment]
solved by #6689 or before

**Comment by SmallJoker** [comment]
Re-opening because the callback is not run in singleplayer (5.0-dev):
```Lua
print("Registering leaveplayer...")
core.register_on_leaveplayer(function(player)
	print("bazz!")
end)
```

**Comment by jastevenson303** [comment]
I just ran into this too.  It means a player _must_ exit the running world before shutting down the server, which is impossible in singleplayer mode, or when hosting a game from the Start Game menu!
