### ISSUE TITLE
passwordbox reset if serverlist loaded

### ISSUE THREAD

**Issue by verymilan** [minetest/minetest#4200]
Hi there, since i have a really bad network connection, my client needs a while to load the serverlist.
It happens often, that i start typing my password to join my server but before i am finish, the password box resets because the serverlist was surprisly loaded. So, i join often with an uncomplete password.^^

**Comment by Wayward1** [comment]
As I frequently play on a laptop, I notice this often while roaming around the house, and it does get rather annoying. I usually remember to wait for the server list to load now, but I imagine it must be quite confusing for new and younger players.

**Comment by cessna151** [comment]
FWIW the username box also gets reset. How about when the list loads, the boxes simply don't get reset? 
:large_orange_diamond:

**Comment by ClobberXD** [comment]
Happens to me all the time, slower the internet connection, the more the possibility of encountering this bug. As @aerozoic mentions, the username also resets to the value of `name` in minetest.conf

**Comment by SmallJoker** [comment]
Same issue with formspec inputs when the window is resized. Any formspec redraws reset the user input to the default value.

Formspecs suck. See #3732
