### ISSUE TITLE
Can't loop a sound connected to player

### ISSUE THREAD

**Issue by aa6** [minetest/minetest#4203]
I'm trying to play a looped sound connected to player but it doesn't loop. It plays once then stop.
https://github.com/aa6/minetest_wadsprint_dyspnea/blob/master/init.lua
Wiki says that 

> Only sounds connected to objects can be looped.
> http://dev.minetest.net/minetest.sound_play

Does this limitation made on purpose? If yes, what's the point then?

**Comment by sofar** [comment]
Is `obj` here the LuaEntitySAO or the PlayerSAO object?

**Comment by paramat** [comment]
Perhaps sounds can only be attached to non-player objects?

**Comment by aa6** [comment]
@sofar How do I know it? It's the player object from `register_on_joinplayer`.

**Comment by raymoo** [comment]
Can someone confirm that it even works for LuaEntitySAOs? It looks like attached sounds may be entirely unimplemented:  https://github.com/minetest/minetest/blob/master/src/network/clientpackethandler.cpp#L794

**Comment by rubenwardy** [comment]
Is this a bug then?

**Comment by aa6** [comment]
Yes, it is a bug. A sound attached to the player object that is meant to be looped forever until `minetest.sound_stop()` actually is not looped and stops right after first loop cycle. How can this not be a bug?

**Comment by rubenwardy** [comment]
the labelling said question, so I was wondering if this was actually discovered to be a bug

**Comment by jastevenson303** [comment]
Looping a sound on a player object works for me:
```
local h
minetest.register_on_joinplayer(function(player)
        h = minetest.sound_play("Front_Center", {
                object = player,
                loop = true,
        })
end)    

minetest.register_chatcommand("stop", {
        func = function(name, param)
                minetest.sound_stop(h)
        end,
})
```
Here's a video: https://www.youtube.com/watch?v=T4OXo1Pq2AE

**Comment by sofar** [comment]
How about a luaentity?

**Comment by jastevenson303** [comment]
Yes, that works too from my experience.  My `s' sub-game uses it a lot.

**Comment by jastevenson303** [comment]
But, I don't know about multiplayer now that I'm testing that.  I may be doing it wrong, and will continue to test, but I'm only certain about locally for the one client.

**Comment by jastevenson303** [comment]
I'm using a mod `snd' to test, and so far you are correct, and I was mistaken.

The sound is playing once only, and then stopping and not looping with this: https://gist.github.com/jastevenson303/13b742e650892c4418bbd04463ecaf25

**Comment by jastevenson303** [comment]
Alright, this is where I've lost it:
```lua
snd = {}
snd.players = {}
minetest.register_chatcommand("snd", {
        func = function(name, param)
                local player = minetest.get_player_by_name(name)
                if param == "play1" then
                        snd.players[name] = minetest.sound_play("Front_Center", {object = player, loop = true})
                elseif param == "play2" then
                        local s = minetest.sound_play
                        {
                                name = "Front_Center",
                                pitch = 0.69,
                                --gain = 0.9,
                                --fade = 0.1,
                        },
                        {
                                --pos = pos,
                                --fade = 0.1,
                                object = player,
                                loop = true,
                                max_hear_distance = 32,
                                --gain = 0.5,
                        }
                        snd.players[name] = s
                else
                        minetest.sound_stop(snd.players[name] or -1)
                end
        end,
})
```

Issuing `/snd play1` will loop, but only for the client (player 2 doesn't hear it!!)

Issuing `/snd play2` will NOT loop!  however, player 2 DOES hear it.  (I'm blown away right now, and will continue to test.)

(Front_Center.wav comes with ALSA.)

**Comment by jastevenson303** [comment]
So I'm off to test out various sound mechanisms because this is so interesting, but in conclusion here per this issue, I think you put loop=true in the simplesoundspec (arg#1), but I think it needs to go in arg#2, SoundParameterTable
```
local sound_handle = minetest.sound_play({name="sound"},{object=player,loop=true})
```
versus
```
local sound_handle = minetest.sound_play({name="sound",loop=true},{object=player})
```
Next I'm testing entities, which is outside the scope of this issue but, I'll still test for player objectrefs too.

**Comment by aa6** [comment]
I have changed arguments order and it worked. Probably would be good to rewrite API leaving only one arguments (and second as a legacy) or/and throw errors/warnings on unknown arguments' parameters.

**Comment by jastevenson303** [comment]
>How about a luaentity?
@sofar it looks like it works, but still strange.  I'm going to do more tests.  https://github.com/jastevenson303/snd/blob/master/init.lua#L96

Yes, the sound system and documentation do indeed need work.
