### ISSUE TITLE
Adding diagonal rails in raillike drawtype

### ISSUE THREAD

**Issue by NaruTrey** [minetest/minetest#4204]
On the server, the players have built a lot of diagonal railways. Add to mod the new position of the rail rotated in 45°. Not for this image of the railway tracks

```
   ┃
  ┏┛
 ┏┛
━┛
```

And like this

```
   ┃
  /
 /
━
```

But I have not found a way to succinctly combine raillike drawtype and diagonal rails. I suggest that it is possible in the core Minetest add code to find new combinations of adjacent rails and painted texture diagonal rails provided modder. However, it may be necessary to add four new textures such rail tracks for each mod using the rails:

```
 │  │    /  \
/    \  /    \
```

What to do?
1. Nothing. Modder himself must provide for the modification of its diagonal rails.
2. Add code to the kernel of the diagonal rails, but will not work by default, modders will need to **register_node** to add an additional flag.
3. Add code to the kernel of the diagonal rails, but the code will turn on only when announced by the required number of tiles in the **register_node**.

**Comment by NaruTrey** [comment]
I've already written the code, but I do not know how best to include it in the Lua API.

**Comment by paramat** [comment]
I think @SmallJoker is attempting this?

**Comment by SmallJoker** [comment]
Code and local branch exists, but I have no plans how the default rail texture could be rotated automatically to obsolete two custom textures:
![Diagonal rails](https://i.imgur.com/PNTOQnv.png)

**Comment by paramat** [comment]
I get the feeling this will be difficult and cause issues, and probably isn't worth it. Just don't build zigzag tracks, most of MT is aligned to a grid afterall.
:-1:

**Comment by paramat** [comment]
Actually seems impossible, imagine a crossing junction, when this feature is added the 4 rails aorund the crossing would then connect diagonally and break existing rail networks.
