### ISSUE TITLE
mapgen: weight heat and humidity along positive y axis

### ISSUE THREAD

**Issue by 0-afflatus** [minetest/minetest#4205]
This would be the correct way to change biome with altitude, and would cause a natural variation in the horizontal biome borders.
An option for settable fall for each of heat and humidity with altitude could be good, measured from water_level and with a default of 0. They would need to be new biome parameters and stored per-world in map-meta.txt.
I would personally like to be able to do the same along both ends of the x and z axes, but I understand hmmmm and paramat have reservations about that.
I haven't looked at the existing code yet, but my experience of doing this in Lua says it's relatively trivial to achieve with no noticeable side-effects.

**Comment by 0-afflatus** [comment]
The overall effect of this will weight the map towards colder biomes, so this would need to be normalised around the average height of flatlands to compensate.
In real-life temperature drops about 10 degC every 1000 metres altitude, I think that works out to about 30 voronoi points per 100 nodes if you want Alpine tundra to appear around y = 256 (my maths is rubbish, please correct if necessary). We compress height ranges severely but if you consider cloud range is 2 - 18k and Alpine biomes start around 3k, it will look right if Alpine biomes begin just above the clouds. Cloud height itself should give rise to Montane cloud forests (effectively taiga).
The setting needs to be flexible enough to deal with a wide range of mapgens and also turn off-able to allow for floatlands and skyblock realms. A settable upper limit might be interesting.

**Comment by paramat** [comment]
> The overall effect of this will weight the map towards colder biomes, so this would need to be normalised around the average height of flatlands to compensate.

The heat and humidity noise offsets can be used to compensate for the bias towards colder, drier biomes.

**Comment by paramat** [comment]
![screenshot_20160612_004701](https://cloud.githubusercontent.com/assets/3686677/15987998/cd15e2b8-3037-11e6-9c30-abfe90db969a.png)

Initial experiment.

**Comment by paramat** [comment]
See #5278

**Comment by paramat** [comment]
I made a PR but was very uncomfortable with it and delayed it.
Now that i have worked on many vertical aspects of mapgen i am actually relieved that i didn't add this feature as it would have made everything even more complex.
So currently i feel it's best to avoid this, even though the idea is nice.

**Comment by paramat** [comment]
Reconsidering. PR that will need redoing is #5344
