### ISSUE TITLE
Hide watermark in the top left corner

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4209]
Hide watermark in the top left corner (the white text that says the build number you're playing on)

**Comment by NathanSalapat** [comment]
It's rather useful to know the build number when it comes to error reporting, it also reports the version numbers, which is good to know when talking about problems as well.

**Comment by rubenwardy** [comment]
I'd also like to see this gone, it's untidy. Error reporting is not a good enough reason IMO to force this on all users

**Comment by tobyplowy** [comment]
@rubenwardy couldn't this be an option Like in the settings or something

**Comment by Fixer-007** [comment]
Yes, please make it open if you specify some option at start, like minetest --debug-window or smth...

**Comment by paramat** [comment]
Perhaps move it into F5 information? then we don't need any options or settings.

**Comment by tobyplowy** [comment]
@paramat yes good idea

**Comment by Fixer-007** [comment]
Yes, please move it into F5 info.
Also, what about showing coordinates instead of it?
