### ISSUE TITLE
Instant block breaking in creative mode

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4213]
It's quite annoying you have to wait a second Until It Breaks it really slows down the building process (it would be better if it instantly breaks, you click and it breaks no brake animation.)

**Comment by Fixer-007** [comment]
It is probably made that way because you occidentally remove some blocks you don't want, happens often to me in MC.

**Comment by FLHerne** [comment]
I would much prefer instant removal - often I just want to see if a block looks right somewhere, or *which* block looks right there. The enforced pause for removal is distracting, especially when trying several alternative block types when it really adds up.

**Comment by wilkgr76** [comment]
Perhaps a button to toggle it... Perhaps in the inventory?

**Comment by DonBatman** [comment]
If blocks are removed too fast you end up removing more than one block. Also accidental clicks would remove blocks. A slight delay is better imo.

**Comment by Ferk** [comment]
I don't think this belongs to the engine.
Also, see https://github.com/minetest/minetest_game/pull/1268

**Comment by paramat** [comment]
Yes my PR slightly reduces dig time and makes it near-identical for all nodes.

**Comment by paramat** [comment]
https://github.com/minetest/minetest_game/pull/1268 is merged.
Note 2 creative server admins requested very little change in creative dig time.
This is a MTGame issue for the creative mod so closing.
