### ISSUE TITLE
Update RTT in F5 debug info

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4214]
Strangely enough I've noticed that RTT (round trip time) is updated only on connect in F5 info text, it is useful to check network with it, can you make it update once a second or so as before?

**Comment by Fixer-007** [comment]
I don't think it is "Feature Request" but a bug, because I've noticed in mt 0.4.4 it works properly (changing every 0.5 or 1 sec), but not in newer minetest.

**Comment by sfan5** [comment]
RTT is updated continously according to the code

**Comment by Fixer-007** [comment]
It does not, it is updated during login once, and then frozen to some value.

**Comment by sfan5** [comment]
Reproduced, could not find a reason for this in the code though.

**Comment by paramat** [comment]
getRTT() was altered here https://github.com/minetest/minetest/commit/c7160cb629086df2a32c7dcf4faed4761ec4393e

**Comment by Fixer-007** [comment]
>getRTT() was altered here c7160cb

This bug is much older than that commit and my issue was filed before that change.

**Comment by HybridDog** [comment]
> could not find a reason for this in the code though.

https://github.com/minetest/minetest/blob/90acb9b3a769fb949b7202b16e29418c945591a7/src/network/connection.cpp#L839-L843
At first, avg_rtt is set to rtt, which is the RTT during login.
The next time, avg_rtt is updated to `m_rtt.avg_rtt * (num_samples/(num_samples-1)) + 
rtt * (1/num_samples)`. Obviously somebody accidentally used an integer division, therefore it's the same as `m_rtt.avg_rtt * (1) + 
rtt * (0)`, which is `m_rtt.avg_rtt`, i.e. the average value does not change.
