### ISSUE TITLE
Lit Particle Effects.

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4215]
An issue I have with current particle effects is that they are shaded and cannot be seen unless there is light around them... but, what if there was a flag in the minetest.add_particlespawner() that told the minetest engine NOT to look at surrounding light levels and DRAW the particle without shading so we can see them during low light or night time conditions?

e.g.

```
minetest.add_particlespawner({
   amount = 20,
   time = 0.25,
   minpos = pos, maxpos = pos,
   minsize = 0.5, maxsize = 2.0,
   texture = "glowing_particle.png",
   light_level = 15, -- (nil for surrounding, 0-15 for forced light level)})
```

![example particles](http://i43.tinypic.com/9kwj90.png)

We need this kind of feature for effects like fireworks, lightning, magic etc.

https://github.com/minetest/minetest/blob/d499ec483837fa7210176ef39beba2d5a3a5a61d/src/particles.cpp#L157

**Comment by est31** [comment]
I'd favor a `light_level` field, which if it is nil, takes the surrounding light level.

**Comment by paramat** [comment]
I like est31's suggestion.

**Comment by tobyplowy** [comment]
I could be wrong here but you could use this to make fireflies right. full support anyways.

**Comment by tenplus1** [comment]
@est31 light_level sounds a way better option.

@tobyplowy definitely, one of the things I wanted to add was fireflies.

**Comment by tobyplowy** [comment]
@tenplus1 nice :) will it be for a mod or for the base game?

**Comment by tenplus1** [comment]
If lit particles are added which shouldn't be too difficult since it's only a single setting in particles and lighting information given to code link above... then I will make a fireflies mod :)

**Comment by tobyplowy** [comment]
@tenplus1 I'm definitely going to download it.

**Comment by sofar** [comment]
I'd argue that we do *not* want particles to *emit* light (since this will cause map light updates, and those are heavy.

What we want instead is a particle that is *lit* with a certain level.

I disagree with @est31 that a `light_level` should take surrounding light.  The light level should be arbitrary, and, since it is trivial to determine light level on the map, one can easily make particles that way that have the light level of the surrounding light.

That way we have a way more generic implementation where light_level doesn't cause map light updates, nor would it have to determine the map light level in the first place, which is much more simple.

**Comment by est31** [comment]
@sofar I've meant precisely what you said: if `light_level` is not nil, it should be used to determine the light, if it is nil, the surrounding light should be used. This way we can ensure backwards compat with current behaviour, and add the feature.

Either way I can't recall how my suggestion was different from @tenplus1 's one, so I don't claim authorship of the idea :)

**Comment by sofar** [comment]
Ah, that makes sense, yes.

**Comment by tenplus1** [comment]
@est31 - that sounds a better idea actually, nil for surrounding light levels and 0-15 for custom/forced.

**Comment by raymoo** [comment]
I want to work on this once attached spawners are merged. I'm not sure if I should start now, since some of the edited code will be near the changes from attached spawners. Should I be worried?

**Comment by paramat** [comment]
By the way, if particle light is set, take the maximum of set light and ambient light, otherwise dimly glowing particles will be slightly dark in daytime.

**Comment by sofar** [comment]
@raymoo I wouldn't be too worried about that... if the code does the right thing it'll sort itself out anyway.

**Comment by sofar** [comment]
@paramat that can be done entirely in lua, so I don't see why that has to be done in C (that would make it less generic).

**Comment by raymoo** [comment]
@sofar It can't be done in lua, in the case that the lighting of an area changes after the particle spawner is created. Also particles could move into an area with different lighting, a problem that would be made worse if attached spawners are implemented.

**Comment by sofar** [comment]
I'd focus on making lit particles consistently look like they're in the same light level - my suspicion is that most uses for this particle is for people who want to create light effects (sparks, flames, smoke, etc) that are likely to be consistently lit.

Particles that have to "adjust" light levels can be re-spawned with a new light level anyway, for now.

**Comment by paramat** [comment]
Hm good points.

**Comment by raymoo** [comment]
You can't respawn a particle because particles don't have a handle. But I agree that the more complicated functionality might not be necessary.

**Comment by tenplus1** [comment]
Simply having particles with specific (0-15) or surrounding (nil) light levels would be more than perfect :P

**Comment by tchncs** [comment]
Anything new here? :)

**Comment by raymoo** [comment]
@tchncs Take a look at #4774, it adds particle glow parameters.

**Comment by tchncs** [comment]
Oh, i iguess i misinterpreted something with my smartphone, sorry.

**Comment by tenplus1** [comment]
Closing now that 'glow' flag has been added to add_particles :)
