### ISSUE TITLE
Water reflections?

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4219]
Can water reflect stuff

**Comment by rubenwardy** [comment]
No

**Comment by tobyplowy** [comment]
@rubenwardy I can't program it's a request, but if I could I would definitely do it :/

**Comment by paramat** [comment]
Your first comment looked like a question missing a question mark, we could have answered 'no' and closed this as a waste of time. Please be clear when you are making a feature request.
RBA may have worked on this but now he's gone we don't have a shader coder, so it's highly unlikely to happen soon. I would -1 it anyway as being too excessive even for shaders.

**Comment by tobyplowy** [comment]
@paramat it was a request but I was already doubting it would happen I will close this issue

**Comment by paramat** [comment]
It would be very intensive code, especially for a realtime rendered game like Minetest, even if the water was flat with no ripples creating a perfect reflection. It would be effectively creating a second camera.

**Comment by tobyplowy** [comment]
@paramat I understand (but will corals be added I know it's off topic but it's very important to know so I can verify the texture packs and working on.

**Comment by ezileicorreia** [comment]
We want #14427 #14610 #14828 in version 6.0.0!
