### ISSUE TITLE
Lighting and shadowing needs improving/bugfixing

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4223]
Will add few screenshots why... in a sec (tone mapping is _on_):
Seems reasonable (don't like the edges though):
![seo8zhp](https://cloud.githubusercontent.com/assets/16494741/16126446/e8d51d8a-3400-11e6-95bb-e3d2a3443077.png)
Now worse part:
![hdnvvln](https://cloud.githubusercontent.com/assets/16494741/16126482/0a40ce92-3401-11e6-96c3-530290f6d7ad.png)
After increasing distance between, seems reasonable, but edges are ---p:
![5fvcxod](https://cloud.githubusercontent.com/assets/16494741/16126507/24f95a06-3401-11e6-8072-327a4501a11a.png)
Complicating, non symmetrical lighting shapes:
![vyh44qc](https://cloud.githubusercontent.com/assets/16494741/16126563/5d82d2ee-3401-11e6-8ba1-45c6abe17027.png)
Suspicious case of corner lighting:
![mw6skub](https://cloud.githubusercontent.com/assets/16494741/16126589/78b037fa-3401-11e6-860d-0f780f94c885.png)
Or this one made by RHR (notice how MT ones has cubic shape in center, I observed it myself:
![ifzoata](https://cloud.githubusercontent.com/assets/16494741/16128115/fb2bc572-3407-11e6-912b-ba0a128c727d.png)
Or this one by Kaeza:
![screenshot_20160616_142225-urow1qxw](https://cloud.githubusercontent.com/assets/16494741/16128167/3305f6f2-3408-11e6-8a99-a8507217dafb.jpg)

Lighting needs improving for sure, in some cases I need to use lifehacks to avoid this ugly light shapes by using lights on ceilings, spacing them more on walls immersing, them deeper etc...

Light edges drawing is worst part.

**Comment by Calinou** [comment]
Does this happen with `display_gamma = 1.0` in minetest.conf?

**Comment by paramat** [comment]
That sharp-edged bright area is a problem.

**Comment by RHRhino** [comment]
Is Minetst lighting based on the whole block or based on the face of the block that is illuminated?

**Comment by ExeterDad** [comment]
I agree light oozing through edges of nodes is irritating as it messes up how things look inside buildings (for example). But it certainly is useful when mining. When edges of default stone are illuminated... watch out, lava is near.

**Comment by beyondlimits** [comment]
Each square face is composed out of two triangles, and orientation of those triangles affect the shape of light. Minecraft does it properly, however sacrificing the correctness of ambient occlusion. When you look under Minecraft's big mushroom, you may notice that the shape of "shadow" isn't always perfect.

In Minetest, this is exact opposite case - ambient occlusion seems to always work properly while lighting is buggy.

**Comment by Fixer-007** [comment]
It is not just this... problems are everywhere, when you work with lava it often leaves spots with wrong lighting, light spots after lightning strikes (mod), writing letters with water source in ocean (gives different lighting), ...

**Comment by paramat** [comment]
> Lighting is not good

The title is funny.

The other lighting problems have their own issues, 'updateLighting' has problems.
Best keep this issue specific to the light edges problem.

**Comment by Fixer-007** [comment]
Issues in pics #1,2,3,4 and 5 were fixed by recent change in light curve, looks MUCH BETTER now! Will close it down, issue in Pic 7 was mentioned recently in new issue.
