### ISSUE TITLE
Hiding collision boxes

### ISSUE THREAD

**Issue by xunto** [minetest/minetest#4224]
Collision boxes don't look good with entities. I think that they should be hidden by default with option to enable them(in lua api or minetest.conf).

**Comment by asl97** [comment]
It has already been decided that the default would be to show them
https://github.com/minetest/minetest/pull/3992

You can disable them by setting the conf:
`show_entity_selectionbox = false`

**Comment by hunterdelyx1** [comment]
Oh, didn't know that. Thx.

**Comment by paramat** [comment]
Still a valid request to hide by default.

**Comment by everamzah** [comment]
I can't seem to find it in the settings tab.

**Comment by paramat** [comment]
client -> network

**Comment by everamzah** [comment]
Definitely the last place I'd think to look.  Thanks!

**Comment by tobyplowy** [comment]
I also think they should be disabled by default.

**Comment by tobyplowy** [comment]
@paramat why is it in (client -> network) And Not in (client -> graphics)

**Comment by paramat** [comment]
No idea, sofar made the PR.

**Comment by sofar** [comment]
The setting can be changed server-side afaicr.

**Comment by paramat** [comment]
See #1645 there are good reasons for on by default, also it is the previous behaviour.
I prefer on by default.

**Comment by paramat** [comment]
You can keep this open if you want but it was decided to show these by default.

**Comment by everamzah** [comment]
However, this doesn't belong under Client -> Network -> Show entity selection boxes.  It's a client graphics setting.

**Comment by paramat** [comment]
Since shown by default was decided on, and since @xunto didn't know of the option, i think this can be closed now, xunto i hope this is ok feel free to object.
