### ISSUE TITLE
Document set_texture_mod

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4226]
I saw settexturemod in lua_api.txt without any description. Based on its use in minimal, it looks like it basically allows you to append stuff after an entity's texture to add mods. Is that right? (Also looks like you could change the texture of an entity by giving it a blank texture and overlaying it with the texture you want)

**Comment by stujones11** [comment]
+1 I never did understand what that was for.

**Comment by sofar** [comment]
entity textures can be changed as needed already - the texture is set when the entity spawns, not when it's registered (I think)

**Comment by raymoo** [comment]
Can they be changed without unspawning/spawning?

**Comment by kaeza** [comment]
>Can they be changed without unspawning/spawning?

Yes, via `ObjectRef:set_properties(...)`.

`settexturemod` is probably a deprecated-but-never-shown-as-such method.

**Comment by paramat** [comment]
It allows setting the argument here https://github.com/minetest/minetest/blob/ee0bfbede1f5eb17e76cd00444ea9749869d9adb/src/content_cao.cpp#L624
just after a generic CAO is added to a scene.

**Comment by nerzhul** [comment]
It's a valid issue, no documentation

**Comment by sorcerykid** [comment]
I just discovered today that there is a HUGE difference between `set_texture_mod()` and the more generic `set_properties( { texture ... } )`. The later resets the animation cycle of the mesh with every call, which causes visual glitching effects.

So there is definitely a huge advantage to using `set_texture_mod()` if all you want to do is overlay or recolor a texture on the fly. I suspect it may also be slightly more efficient too, although I haven't looked at the implementation.

**Comment by Zughy** [comment]
@paramat this one should have been closed by the PR above but it wasn't included in the original PR description

**Comment by paramat** [comment]
Thanks.
