### ISSUE TITLE
Allow customising messages when a player joins/leaves a server.

### ISSUE THREAD

**Issue by Amaz1** [minetest/minetest#4227]
At the moment, there is no way to change the message when a player joins/leaves the server, it is always **\* name joined/left the game. I'd like to be able to change this message, preferably via on_join/leaveplayer, maybe with a similar system to register_on_chat_message.

**Comment by DonBatman** [comment]
What if you add a counter to the players file? Then mods could make messages based on how many times someone logged in.

**Comment by red-001** [comment]
What could mods use a system like this for?

**Comment by DonBatman** [comment]
I take back my comment. It has uses but in more non-minetest things. Also it can be easily done in a mod. I would like more info collected on players activity but it is used so little that it would be a bunch of code that has little use and needs to be maintained.
