### ISSUE TITLE
Being able to change the cloud texture

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4228]
For now clouds are generated and don't actually use a texture, I think they should use a texture.

**Comment by paramat** [comment]
They're faster and simpler as they are now, just using a uniform RGB colour, and cloud rendering needs to be fast and lighteight. It would be fairly easy to make this RGB colour user-settable.
There are actually 2 cloud colours, there's another one for dawn/dusk.

**Comment by tobyplowy** [comment]
@paramat so it's a no? (because I think customization is quite important)

**Comment by paramat** [comment]
No for a texture.

**Comment by tenplus1** [comment]
I usually turn the clouds off anyhow but I would keep it simple RGB with no textures.

**Comment by o-jasper** [comment]
> They're faster and simpler as they are now, just using a uniform RGB colour, and cloud rendering needs to be fast and light[w]eight. It would be fairly easy to make this RGB colour user-settable.

It does? it is just one set of blocks?

**Comment by paramat** [comment]
They're not nodes and no mesh is created, but like sun, moon, stars are direct rendering of a simple colour, so lightweight.

**Comment by paramat** [comment]
If you change this request to asking for settable RGBA values for clouds that has a good chance of happening.

**Comment by DonBatman** [comment]
@paramat why not have it so it uses a texture if cloud.png exists else use rgb color? This allows more customization of games.

**Comment by paramat** [comment]
Enabling clouds to use textures means a complete change in how they're rendered, it would be much slower, made more complex by the fact they drift. TIled textures would not look good on clouds.

**Comment by tobyplowy** [comment]
@paramat it look's good in Minecraft (the tiled textures for clouds)

**Comment by tobyplowy** [comment]
@paramat after all this is an engine right so it should be possible

**Comment by paramat** [comment]
MC doesn't use tiled textures for clouds in vanilla.
Clouds are already intensive enough just being plain rendered colour.
Someone is working on a clouds API where you can change the plain colour.
