### ISSUE TITLE
init.lua not found for mods

### ISSUE THREAD

**Issue by nwodb** [minetest/minetest#4237]
Was some new code requirement added to enforce all mods/sub-games to have init.lua in the folder? There are several popular mods do not have this this file - and are broken because of it.

```
ERROR[Main]: Subgame specified in default_game [minetest] is invalid.
WARNING[Main]: BanManager: creating /home/daddy/Code/bitbucket/worlds/minetest/bin/../worlds/daddy/ipban.txt
WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
ERROR[Main]: ModError: Failed to load and run script from /home/daddy/Code/bitbucket/worlds/minetest/bin/../mods/carbone_ng/init.lua:
ERROR[Main]: cannot open /home/daddy/Code/bitbucket/worlds/minetest/bin/../mods/carbone_ng/init.lua: No such file or directory
ERROR[Main]: Check debug.txt for details.
WARNING[Main]: BanManager: creating /home/daddy/Code/bitbucket/worlds/minetest/bin/../worlds/daddy/ipban.txt
WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
ERROR[Main]: ModError: Failed to load and run script from /home/daddy/Code/bitbucket/worlds/minetest/bin/../mods/lord_of_the_test/init.lua:
ERROR[Main]: cannot open /home/daddy/Code/bitbucket/worlds/minetest/bin/../mods/lord_of_the_test/init.lua: No such file or directory
ERROR[Main]: Check debug.txt for details.
WARNING[Main]: BanManager: creating /home/daddy/Code/bitbucket/worlds/minetest/bin/../worlds/daddy/ipban.txt
WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
ERROR[Main]: ModError: Failed to load and run script from /home/daddy/Code/bitbucket/worlds/minetest/bin/../mods/lord_of_the_test/init.lua:
ERROR[Main]: cannot open /home/daddy/Code/bitbucket/worlds/minetest/bin/../mods/lord_of_the_test/init.lua: No such file or directory
ERROR[Main]: Check debug.txt for details.```

**Comment by nwodb** [comment]
adding an empty init.lua in the folder seems to fix the of it not loading the mod. Should probably not be a requirement to have the main mod folder have that file in it if:
a) it is not required to load the mod in the first place
b) of the several mods i have tried to use, none of them have this, causing a large part of minetest's user generated content to be un-loadable.

this seems to be the change that broke it:
`https://github.com/minetest/minetest/commit/9269a0ecc7267822bc5ac5af95ad4977bdc94fec#diff-2d01836e6c0329cf2b516efb9b407661`

**Comment by rubenwardy** [comment]
Mods have always required an init.lua file, unless they're a mod pack. Subgames only require a mods/ folder. You install mods to mods/ or world/<name>/worldmods/ and subgames to games/

Carbone-NG and Lord of the test are **subgames** not mods, so should be in games/

**Comment by nwodb** [comment]
thanks, that helps
