### ISSUE TITLE
When player runs away from falling water he made water stuck in air.

### ISSUE THREAD

**Issue by ProzacR** [minetest/minetest#424]
When player runs away from falling water he made water stuck in air.
Throw some buckets of water on top of large hill and run (better with fast move) to reproduce.
Similar issue with furnace it will stop working too without player nearby.

**Comment by paramat** [comment]
The capacity of water flowing code was multiplied by 10 recently, so water tends to flow properly now. Closing.

**Comment by ShadowNinja** [comment]
@paramat This isn't about the capacity of the update queue, it's about water not being updated when it's reloaded sometimes (possibly particularly if it hit a unloaded block before unloading).  Are you sure it's fixed?

**Comment by Zeno-** [comment]
Water won't be in the update queue at all if the server has shutdown before it's all been "flowed"
