### ISSUE TITLE
A simple way for a better multithreading?

### ISSUE THREAD

**Issue by Cyberpangolin** [minetest/minetest#4241]
Hello!

I have an idea that may double (or even better) performances for all multi-core computers.
As you know probably, the limiting factor on any recent computer is clearly the CPU. Mine (a core-i7) is used at 110 % on 400 available (800 if we count the multithreading).

If I understand well, there are multiple threads, and one of them cares about blocks: where are they / what to show or not, and then it sends the infos to the GPU.

What if this thread was splitted in 3: 1 and 2 for the left / right half of the screen, and 3 to compile gathered infos to send to the gpu? Or more: 3 / 4 / 5 vertical bands of screen processed by 1 thread each?
This would give a massive improvement in performance: any multi-threaded computer, even the slowest, could gain a lot of fps / render distance.

Probably it's not that easy, but I really hope this can be done. Thanks for reading.

**Comment by MarkuBu** [comment]
Multithreading is never simple. Currently I play with OpenMP, but the Minetest code is not designed with multithreading in mind

**Comment by rubenwardy** [comment]
it's not quite that simple, sorry
