### ISSUE TITLE
pcf fonts work bad, freetype = true

### ISSUE THREAD

**Issue by xunto** [minetest/minetest#4244]
https://github.com/minetest/minetest/blob/master/src/fontengine.cpp#L340-L342

gui::CGUITTFont::createTTFont() can load pcf([link](https://en.wikipedia.org/wiki/Portable_Compiled_Format)) but when I set pcf font for mono_font_path...

![image](http://storage8.static.itmages.ru/i/16/0621/h_1466547256_8181094_dd3f8a9e32.png)
If I set font_size to a higher value, it works... But it's a bug anyway. 

Loading different files for different sizes(pcf is bitmap format) doesn't work as well.

**Comment by rubenwardy** [comment]
Is this still a problem?

**Comment by xunto** [comment]
I'll check it today.

**Comment by paramat** [comment]
@xunto

**Comment by xunto** [comment]
@rubenwardy @paramat Sorry, worked a lot and forgot about this issue. Font doesn't look like a mess now but setting wrong font size for pcf font do some strange thing.

![](https://i.imgur.com/cpYnHH8.png)

It's font 12 with font_size set to 20 (which is default). I'm not sure that this should be part of this issue but...

**Comment by sfan5** [comment]
pcf fonts are bitmaps, so setting `font_size` just doesn't work for them.
I consider this solved, then.

**Comment by xunto** [comment]
@sfan5 but ```font_size``` works for them. As you see on screenshot. When ```font_size``` doesn't match font size, lines are positioned like 0.5 line down and even intersect with input line.
