### ISSUE TITLE
on_dieplayer gets re-called after server restart if player did not respawn

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest#4246]
The on_dieplayer callback is being called again following a server restart if a player did not respawn after dying. This is causing a lot of problems for my armor mod since this happens before on_joinplayer is called and the mod has had a chance to initialize https://github.com/stujones11/minetest-3d_armor/issues/61

You can prove this is an engine bug by adding this simple mod 

``` Lua
minetest.register_on_joinplayer(function(player)
    local name = player:get_player_name()
    if name then
        print(name.." joined the server")
    end
end)

minetest.register_on_dieplayer(function(player)
    local name = player:get_player_name()
    if name then
        print(name.." died")
    end
end)
```

**Output:**
`<playername>` died
`<playername>` joined the server

Note that I have tried applying #4127 and it does not fix this particular issue.

**Comment by pauloue** [comment]
This is fixed since https://github.com/minetest/minetest/commit/351cc2e79a7d78f7ec97ff9b33e4f0bad4042b19.

**Comment by ClobberXD** [comment]
I think I still encounter this phenomenon - if the server shuts down while I'm still dead, I get the death formspec the next time I join the server. (I hope that's related)

**Comment by pauloue** [comment]
Well if you didn't get the death formspec on join then you wouldn't be able to respawn. If you try the posted code `on_dieplayer` is no longer triggered in that situation.

**Comment by ClobberXD** [comment]
Hmm... but I guess the `on_dieplayer` callbacks aren't called on the next join. Just wanted to make sure this wasn't an edge-case bug. :)
