### ISSUE TITLE
Magic window to the underground

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4248]
It is possible to open a "magic window" to look to the underground.

If you stand in front of a wall and place a node in front of you, the player stands IN the node and can look through the wall. So it is possible to see if there is a cave near

![screenshot_20160623_172259](https://cloud.githubusercontent.com/assets/16163058/16308946/3fe63b70-3967-11e6-8dc9-ab9c0247b10e.png)

**Comment by paramat** [comment]
The player is behind the mesh, this is expected. We do have code that prevents building where the player is.

**Comment by MarkuBu** [comment]
This does obviously not work because I can place a node where I stand

**Comment by MarkuBu** [comment]
@paramat it is obvious that I can place a node where I stand

https://www.youtube.com/watch?v=OS_K5Ox7PlY

Or did I understand something wrong?

**Comment by t4im** [comment]
You need to set `enable_build_where_you_stand = false` for that code to be active.

But if the camera is within the mesh, the behavior is as expected from pretty much any 3D Application, where you clip through faces.

**Comment by MarkuBu** [comment]
No, I have noclip enabled, sorry. Didn't know that
