### ISSUE TITLE
Undocumented Lua function

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4250]
I found the function _find_nodes_in_area_under_air_ in l_env.cpp.

https://github.com/minetest/minetest/blob/dfbdb5bcd7bc48efb21d585d5c22454a9d5f0f1e/src/script/lua_api/l_env.cpp#L673

It is not documented in the wiki. Is it not documented by intention to wait for the generic version? If this function already works I would suggest to leave it as it is if it is faster

**Comment by paramat** [comment]
It is documented https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2070
the wiki is very incomplete and out of date, any omission is not an issue for here.
