### ISSUE TITLE
minetestserver should handle SIGTERM signals and properly shutdown the server

### ISSUE THREAD

**Issue by apoleon** [minetest/minetest#4251]
It appears that minetestserver can only handle SIGINT signals (src/porting.cpp). This makes sense if the server is a foreground process. However if minetestserver is configured as a systemd unit, the default signal to terminate the process (systemctl stop) is SIGTERM which seems reasonable.  This behavior can be overridden by using the KillSignal=SIGINT option in the service file. Though I think it would be better if Minetest supported SIGTERM signals as well and ensured that the server is cleanly shutdown.

**Comment by dr4Ke** [comment]
Related debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828018
