### ISSUE TITLE
Allow toggling F7 and F8 from lua.

### ISSUE THREAD

**Issue by Splizard** [minetest/minetest#4252]
It would be great to be able to enable and disable 3rd person mode and cinematic mode from Lua. I want to create a cinematic mod which would make use of such functions :+1:

**Comment by DonBatman** [comment]
This would be cool for my battle arena mod. When a battle starts it could go into 3d person view. This would be a totally different fighting experience.

**Comment by lightonflux** [comment]
@DonBatman For that feature we also need an inhibitor, so people don't have an advantage or disadvantage. But that stuff for another issue.

**Comment by sofar** [comment]
@donbatman somewhat offtopic, but 3d person view for battles in minetest isn't as good as e.g. 3d person view in WoW is, due to the fact that the pointed vector is attached to the camera angle - i.e. you can't view the battle from above because you'll always be hitting the ground.

**Comment by paramat** [comment]
You can select third person from Lua.

**Comment by paramat** [comment]
Any core dev support?

**Comment by ClobberXD** [comment]
Also needed is the ability for a mod to disable 3rd-person, 1st-person, or frontal views, probably by means of boolean flags

**Comment by Ezhh** [comment]
For any use in cinematics, we'd need a lot more than being able to toggle the view from lua. We'd need zoom in/out and the ability to move the camera so the player isn't central. And MT isn't really a game /game engine that feels focused on those kinds of visual effects in general, so for cinematic use, I'd call this very low priority.

The only possible really good use I can think of would be positioning the view while previewing skins for a skins mod.

**Comment by paramat** [comment]
+1 for being able to switch between 1st and 3rd person camera views from Lua.

**Comment by paramat** [comment]
Folding control over switching 1st/3rd person view into #3070 since it is very closely related and is being discussed there.
