### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#4254]
Maybe, I mean, really maybe, we should make the third/second version from now, maybe even next, 1.0. As the game is already pretty playable, and giving it version 1.0 will add credibility. Right? It will become something finished, only to be improved upon.

**Comment by Calinou** [comment]
There are currently too many long-standing issues with Minetest core to call it 1.0, like [this one about performance](https://github.com/minetest/minetest/issues/4022) (and many other ones).

**Comment by paramat** [comment]
:-1: 
We've already planned to go 0.5.0 or 5.0.0 which is more of a natural progression from .0.4.x.
The problem with 1.0.0 is that it gives the impression of 'just now completed', which then produces disappointment when all the bugs and unfinished stuff is discovered. Better to always be < 1.0.0 or go way beyond it.

**Comment by C1ffisme** [comment]
@lisacvuk I'm sorry, who are you to control an entire group of people's design decisions about a thing as large as a version number, something that shows how complete a piece of software is?

Minetest is pretty incomplete as an engine now, considering that large parts of the API are missing, or badly implemented.

Minetest Game is also incomplete as a game, see [this](https://github.com/minetest/minetest_game/issues/515).

**Comment by obneq** [comment]
who gives a shit about version numbers?

**Comment by Calinou** [comment]
> who gives a shit about version numbers?

They actually mean something to most users, even if they're not really justified in themselves.

**Comment by lisacvuk** [comment]
@C1ffisme Well, sorry, It is just a recommendation. None needs to listen to me, or do anything about it. I'm only discussing it. I apologize if anyone found it insulting.

**Comment by paramat** [comment]
No problem, it's a valid suggestion and devs have discussed the issue at length so it is significant.

**Comment by nerzhul** [comment]
We already discussed this and this version is not the version we will choose as paramat said, i close the issue
