### ISSUE TITLE
Disable stdout spam

### ISSUE THREAD

**Issue by Aftermoth** [minetest/minetest#4255]
There should at least be an option, via the game interface, to disable dumping everything to stdout.
I don't like to tamper with the default installation to add symlinks and wrappers, and opening a separate shell every time is annoying.
I wouldn't object if only errors were dumped, but even then, debug.txt is often a better outlet.
(I'm using 0.4.10)

An awkward startup routine impacts both player experience and willingness to do spontaneous in-game experiments when the game is not already running.

**Comment by rubenwardy** [comment]
Duplicate: #4210

Also,

    debug_log_level = 

to disable all MT logging including to, but the window will still be open

**Comment by Aftermoth** [comment]
Logging is useful to me; burying the output of other programs is not.

You seem to be describing an open console on a Windows desktop, where it's generally unwanted. But I'm using Linux where CLI fits in nicely, provided it's well-behaved.

**Comment by rubenwardy** [comment]
I'm not sure what you mean then. I use Linux too

**Comment by Calinou** [comment]
This is a legitimate issue, I don't think one can change the logging level in debug.txt separately from the console (stdout) logging.

**Comment by est31** [comment]
@Aftermoth you might want to use pipes to redirect everything to /dev/null: http://www.cyberciti.biz/faq/how-to-redirect-output-and-errors-to-devnull/

**Comment by Aftermoth** [comment]
Okay, I think Calinou understands, but I'll try to be clear enough for any future readers. No insults intended if I overdo it.

Usually, one can run several programs from the same console and important information from any or all of them can be printed to the same place and easily seen. It's like an email inbox.

MT prints a lot of output to its console and constantly throughout game play
> 10:06:09: ACTION[ServerThread]: singleplayer places node default:desert_sand at (-184,-64,1119) 
This makes the console unsuitable for shared use, so it is necessary to open a separate one just to keep others useable. Like a spam folder.

@est31 I'm aware that there are workarounds, but it would be better if MT could be executed from the WM directly however the user prefers, without altering the installation directory or requiring script/alias/CLI commands and not have this problem.
Reminder: X and window managers output to tty as well, even if some users don't see it.

In my case, the easiest solution is to open a separate vt in its own workspace and type "minetest". I use `tail -f debug.txt` for debugging.

**Comment by est31** [comment]
Yeah, nearly every tool outputs to the console. I know this because I too often start graphical tools from the terminal. To be honest though, I don't consider the stdout output of those to be really usable information.
