### ISSUE TITLE
Fade and sound playback with gain <= 0 delete the handle (for mute)

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4256]
I would suggest the function sound_mute() to mute currently played sounds without stopping them. Parameters are the sound handle and a boolean to turn mute on and off.

Additionally or alternatively the function sound_volume(handle, gain) would be helpful

**Comment by paramat** [comment]
Author left MT, anyone else requesting this?

**Comment by SmallJoker** [comment]
Can be done with the sound fading functions, as implemented by #5340.

**Comment by paramat** [comment]
@jastevenson303 please could you open a new issue for these fade problems?

**Comment by paramat** [comment]
Any core dev support for this feature?

**Comment by SmallJoker** [comment]
Fade is supposed to fade and muting is possible too with this feature. This issue is about the sound volume, not about pausing and resuming the playback. Please open an issue with the appropriate request.

**Comment by jastevenson303** [comment]
Yeah you can mute but you cannot unmute.  Pausing/resuming and muting/unmuting are what this issue requests.  This cannot be done with minetest.sound_fade.

And you want me to create a duplicate issue?

**Comment by jastevenson303** [comment]
One cannot achieve what this issue requests with minetest.sound_fade.  @smalljoker

**Comment by SmallJoker** [comment]
@jastevenson303 Muting/unmuting and pausing/resuming are two different things, whereas the former is requested in this issue. Feel free to open a new issue for latter.

The sound handle is deleted on purpose when the gain is `<= 0.0f`, code reference: (also for `Server::playSound`)
https://github.com/minetest/minetest/blob/0e306c084284aeafb3d5cde0cfec11a85a11cb9c/src/server.cpp#L2054-L2077
The reason for this is that sound handles must be deleted in mods (using `sound_stop`), so deleting them in this case automatically seemed to be a good idea. Modders would then no longer have to set a timer to delete the sounds.
I agree, this is not a great solution.

**Comment by paramat** [comment]
First comment:
> I would suggest the function sound_mute() to mute currently played sounds without stopping them.

Nothing to do with pause/resume.

**Comment by jastevenson303** [comment]
Thank you smalljoker, I can contjnue testing now.  As usual, sorry for any
confusion.  :)

**Comment by jastevenson303** [comment]
@smalljoker muting cannot be done with `minetest.sound_fade`.

In the Sound Parameter Table, `fade` is by default 0.0, which is "fade out."  Setting it to 1.0 allows to fade the sound in.  You need to different sound specs: one to fade in, and one to fade out, thus muting is possible, however as I stated _unmuting_ is not.

Here is the doc reference: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L813

Here is some code to test:
```
local fadetest = function(player)
	local pos = player:get_pos()
	local name = player:get_player_name()
	local sss = "fadetest_tone-a"
	local spt = {
		loop = true,
		gain = 1.0,
		fade = 0.0,
		object = player,
		to_player = name,
		pos = pos,
		max_hear_distance = 32,
		pitch = 1.0,
	}
	return minetest.sound_play(sss, spt)
end

local handles = {}

minetest.register_chatcommand("fadetest", {
	description = "Test minetest.sound_fade()",
	params = "start, fadeout, fadein, stop",
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		if not player then
			return
		end
		if param == "start" then
			handles[name] = fadetest(player)
		elseif param == "fadeout" then
			if handles[name] then
				minetest.sound_fade(handles[name],
						-1.0, 0.00001)
			end
		elseif param == "fadein" then
			if handles[name] then
				minetest.sound_fade(handles[name],
						1.0, 1.0)
			end
		elseif param == "stop" then
			if handles[name] then
				minetest.sound_stop(handles[name])
			end
		else
			return false, "Invalid usage.  Type /help fadetest " ..
					"for more information."
		end
	end
})
```

So, again, muting is not possible with minetest.sound_fade.  Sure, _silencing_ is possible, but muting _implies_ unmuting, when it comes to a feature like this.  Please correct me if I'm wrong.

**Comment by Desour** [comment]
It's unclear to me what this issue exactly requests. Did the ghost person want to mute and unmute sounds, or did it want to pause and unpause them?
(The issue title and description are clearly outdated.)

Anyway, I think this issue can be resolved with the `time_offset` parameter added in #12764, by stopping the sound and afterwards starting a new sound. 
(An unmute function wouldn't work too well for positional sounds, btw., as new players would still not hear the sound when coming nearby. `time_offset` enables mods to solve these issues.)
