### ISSUE TITLE
Cannot compile on Fedora 23

### ISSUE THREAD

**Issue by luvitto** [minetest/minetest#4257]
**Installed libs:**
ncurses-devel
irrlicht-devel
gettext-devel
freetype-devel
bzip2-devel
libpng-devel
libjpeg-turbo-devel
libXxf86vm-devel
mesa-libGL-devel
libsqlite3x-devel
libogg-devel
libvorbis-devel
openal-soft-devel
libcurl-devel
luajit-devel
leveldb-devel

This analog for Fedora from http://forum.minetest.net/viewtopic.php?f=3&t=3837

Compiling without errors, except end:

[ 99%] Building CXX object src/CMakeFiles/minetest.dir/voxelalgorithms.cpp.o
make[2]: *** No rule to make target '/usr/lib64/libGL.so', needed by '/home/luvitto/packages/minetest/bin/minetest'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object src/CMakeFiles/minetest.dir/wieldmesh.cpp.o
CMakeFiles/Makefile2:152: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

ls -l /usr/lib64/libGL.so
lrwxrwxrwx 1 root root 14 Jun 14 16:08 /usr/lib64/libGL.so -> libGL.so.1.2.0

**Comment by duckbrain** [comment]
Do you need to install the `mesa-libGL` package?

http://forums.fedoraforum.org/showthread.php?t=258399

Suggests using `yum whatprovides */lib64/libGL.so` to find a package that will satisfy that requirement.

**Comment by luvitto** [comment]
I already have it installed
dnf list installed | grep libGL
libGLEW.x86_64                     1.10.0-6.fc23                        @fedora 
mesa-libGL.i686                    11.1.0-4.20151218.fc23               @updates
**mesa-libGL.x86_64                  11.1.0-4.20151218.fc23               @updates**
**mesa-libGL-devel.x86_64            11.1.0-4.20151218.fc23               @updates**
mesa-libGLES.x86_64                11.1.0-4.20151218.fc23               @updates
mesa-libGLU.i686                   9.0.0-9.fc23                         @fedora 
mesa-libGLU.x86_64                 9.0.0-9.fc23                         @fedora 
mesa-libGLU-devel.x86_64           9.0.0-9.fc23                         @fedora

**Comment by luvitto** [comment]
Sorry, my mistake.

/usr/lib64/libGL.so was dead link. I'm point it to /usr/lib64/libGL.so.1 and compile minetest successfully.
Please, close this issue.
