### ISSUE TITLE
Play a sound when another player mentions your name

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#4259]
Another one of my, fairly unpopular, 'feature requests'. Why not play a beep sound when another player mentions you in chat?

**Comment by sofar** [comment]
Can be done entirely in mods I think, so technically, the engine supports this.

**Comment by lisacvuk** [comment]
Yes, but it would probably lag in mods.

**Comment by raymoo** [comment]
I don't think it would lag much if done server-side, since the client should receive the sound turn-on message around the same time they receive the text message, maybe even a little bit before (If the call sends it immediately rather than being put in a queue or something).

**Comment by sofar** [comment]
>Yes, but it would probably lag in mods. 

It would lag exactly the same in the client.

Chat messages are processed on the server, and having mods process them and send a sound packet together with the chat packet wouldn't give any significant lag.

On top of that, lag in chat messages is entirely irrelevant to gameplay.

**Comment by tobyplowy** [comment]
I don't think this is a good idea (this could be used for trolling)

**Comment by lisacvuk** [comment]
You could add ignore, too.

**Comment by tenplus1** [comment]
This would quickly get annoying, how about using the same effect that IRC chat uses instead, when a player types your name their username appears coloured and in bold to stand out from the rest of the chat?

**Comment by C1ffisme** [comment]
@tenplus1 Now that we have colored chat, that's possible to do.

**Comment by paramat** [comment]
A fraction of a second of lag is not a problem, can be done in mods, also see new CSM functions.

**Comment by lisacvuk** [comment]
Wow I completely forgot about this PR. There was no CSM when the issue was created.

**Comment by C1ffisme** [comment]
I still like the idea of coloring the player's own name. (The only problem is that this suggestion and @tenplus1 's are both pretty much useless when someone has a name like gvramtuslir and you type things like gvramtsulir or gvramtuslr. I have never met a player with that name, but I've seen names that are pretty hard to spell.)

**Comment by DS-Minetest** [comment]
@C1ffisme You can use tab auto completion.

(Btw, for anyone who is searching for a csm that implements this: https://forum.minetest.net/viewtopic.php?f=53&t=17837)
