### ISSUE TITLE
minetest.clear_item(itemstring)

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#4264]
I suggest to add a function `minetest.clear_item(itemstring)` that works similiar to `minetest.override_item`. The new function should completely unregister the given node/item/tool.

**Comment by mtango688** [comment]
There is a clear_craft, now.

See https://github.com/minetest/minetest/commit/281e9f39fdffd106e79122ae23e2b5443a5daea3

**Comment by Thomas--S** [comment]
Someone made a PR: #4307

**Comment by Thomas--S** [comment]
aa33166
