### ISSUE TITLE
Building for Android on MacOS fails

### ISSUE THREAD

**Issue by vuongkien** [minetest/minetest#4265]
I just want to build minetest for android on MacOS but I can't. 
Everything is OK when i make build for MacOS.
But when i run make on "build/android". This error always happen:

<pre>
libtool: link: arm-linux-androideabi-gcc -shared  -fPIC -DPIC  objects/.libs/iconv.o objects/.libs/localcharset.o objects/.libs/relocatable.o    -O2   -Wl,-soname -Wl,libiconv.so.0 -o .libs/libiconv.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libiconv.so.0" && ln -s "libiconv.so.0.0.0" "libiconv.so.0")
libtool: link: (cd ".libs" && rm -f "libiconv.so" && ln -s "libiconv.so.0.0.0" "libiconv.so")
libtool: link: ( cd ".libs" && rm -f "libiconv.la" && ln -s "../libiconv.la" "libiconv.la" )
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: warning for library: libicrt.a the table of contents is empty (no object file members in the library define global symbols)
libtool: link: arm-linux-androideabi-gcc -g -O2 iconv_no_i18n.o -o .libs/iconv_no_i18n  ../srclib/libicrt.a ../lib/.libs/libiconv.so -Wl,-rpath -Wl,/usr/local/lib
/private/tmp/ndk-arm-linux-iconv/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: ../srclib/libicrt.a: no archive symbol table (run ranlib)
./iconv.c:185: error: undefined reference to 'program_name'
./iconv.c:60: error: undefined reference to 'rpl_strerror'
./iconv.c:67: error: undefined reference to 'program_name'
./iconv.c:691: error: undefined reference to 'safe_read'
./iconv.c:234: error: undefined reference to 'uc_width'
./iconv.c:850: error: undefined reference to 'set_program_name'
../srclib/streq.h:71: error: undefined reference to 'program_name'
collect2: error: ld returned 1 exit status
make[3]: *** [iconv_no_i18n] Error 1
make[2]: *** [all] Error 2
make[1]: *** [/Users/kienvuong/Documents/Works/Projects/Eclipse/minetest-master/build/android/deps/libiconv//lib/.libs/libiconv.so] Error 1
make: *** [debug] Error 2
</pre>

Please help me!

**Comment by est31** [comment]
The android port was made for gnu/linux. Its not cross platform. Until that is fixed, the only workaround is to install a VM and execute the android build on that.

Note: if you find out how to build it, please make a PR so that the build can be made cross-platform.

**Comment by est31** [comment]
Hmm, running into this issue on linux now, too. So it shouldn't be mac specific only...

**Comment by vuongkien** [comment]
how about this bug?

**Comment by nerzhul** [comment]
no problem for me on Android it's due to your environment. Also MacOSX build works, our CI test it

**Comment by nerzhul** [comment]
Note, building with NDK on MacOSX is not recommended, use Linux or Windows instead
