### ISSUE TITLE
Advanced settings: Minimum and maximum float values are ignored

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4268]
In Minetest 0.4.14, the minimum and maximum boundaries for values of type “float” are ignored when entering values in the advanced settings menu.
This can be tested easily:

Go to the advanced settings, then go through Client → Controls → `camera_smoothing`. Enter out-of-bounds values like “-443”, “8001” or “1.0”.
According to `builtin/settingtypes.txt`, the values must be between 0 and 0.99.

**Comment by SmallJoker** [comment]
Specially with `camera_smoothing` it's interesting to look at the source code because it shows up that valuse from `0.01` to (and with) `1.0` are accepted.
https://github.com/minetest/minetest/blob/master/src/game.cpp#L1957

**Comment by srifqi** [comment]
The `int` type has a check for range. IMO, `float` should have too.

**Comment by paramat** [comment]
#6836 merged.
