### ISSUE TITLE
Shift+click to build on node with right click action does not cause build sound to play

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4270]
In Minetest 0.4.14, if you build by pressing Shift+left click (Shift is the sneak key), the build sound for the node you want to build is not played (but should) if you place the node on a node which can be used. The building happens silently.

Concrete example in Minetest Game: You want to place a chest on a chest. If you use Shift+left click to place it, the chest is placed, but no build sound can be heard.

**Comment by Snipie** [comment]
I tested this by placing a default:chest on top of an other using SHIFT+right click. Build sound plays normally.
SHIFT+left click does nothing. What I'm missing here ?

**Comment by Wuzzy2** [comment]
Oops, you are right. The chests Minetest Game seems to work, actually. Sorry, my fault.
This is strange.
But when I do this with the dice from the dice2 mod (http://repo.or.cz/w/minetest_dice2.git), it doesn't work. Note the dice2 nodes have “on_rightclick” set and also the “place” sound spec, so I don't know why it works for chests but not for those dice. Strange.

Is this a bug in the mod? Or is this a bug in Minetest and I don't fully understand under which conditions this bug actually appears? I have no idea.

**Comment by rubenwardy** [comment]
Was this a mod bug? Does the dice have a formspec in the meta?

**Comment by Wuzzy2** [comment]
No idea.
Check <http://repo.or.cz/minetest_dice2.git/blob/refs/heads/master:/init.lua>. I don't see anything weird here.

**Comment by paramat** [comment]
Too vague to keep open, probably a mod bug. Can reopen if an engine issue is suspected.

**Comment by Wuzzy2** [comment]
OMG. I think you need to reopen. :D 

The issue is happening now **exactly as I described**.

I just pulled today, and retested. Please test again.

MTG: 1e9c61f241f6495d944d7e8e21fa5e150e7f8315
MT: 861cfd848473db6c36b0debb7152d98ca8017062

In MTG this happens now when you build a chest at a chest by sneak-rightclick. Or basically, you just build anything at a chest.
Other affected nodes include furnaces, all trapooors, all fence gates, firefly in a bottle, all beds. Place anything at them with sneak-rightclick and the placement is silent.

I also has this in MineClone 2 for my trapped chests.

The dice have no metadata or inventories, they only have `on_rightclick`.

All these nodes I just mentioned have something in common: They either have `on_rightclick` or metadata inventories (so they are rightclickable). Maybe this is the reason. Maybe Minetest suppresses the rightclick sound when you try to build something at a rightclickable node?

**Comment by jastevenson303** [comment]
Maybe if one has not tried to reproduce, they shouldn't close.

**Comment by paramat** [comment]
It was tested and couldn't be reproduced in MTG, seemed to be a mod bug.
However now is different.

**Comment by DS-Minetest** [comment]
PR: #8639 
(Just that the participants here are notified.)
