### ISSUE TITLE
Adding new functions to vector.lua

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4271]
I'm working on some functions for vector.lua, inspired by Processing

https://processing.org/reference/PVector.html

Until now I added the functions

```
vector.random2d()
vector.random3d()
vector.setLength(v, l)  -- in Processing this is setMag()
vector.limit(v, l)
vector.dot(a, b)
```

I want to add

```
fromAngle()
heading()
angleBetween()
```

But I don't know how to make a pull request for a single file yet

**Comment by t4im** [comment]
Github is providing help pages, that are explaining how that works in detail :-)
https://help.github.com/articles/using-pull-requests/

**Comment by MarkuBu** [comment]
I don't know why I can't make a pull request, but here are the changes

https://github.com/minetest/minetest/commit/f19dde3cc9f559f3d96830398fd6d46f1e8f3f9d

Github is still a myth for me

**Comment by t4im** [comment]
You should create a fresh branch for every new pull request and have it point to the newest commit on minetest/master at that time.

You appended that commit to #4238

**Comment by MarkuBu** [comment]
Ok, I try this. Thx

**Comment by t4im** [comment]
#4277

**Comment by paramat** [comment]
PR #5564
