### ISSUE TITLE
Remove default F8 keybinding

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4275]
Please remove this default keybinding.  It is too easy to toggle third person view, hit the wrong key, and then suddenly wonder why the mouse, or whatever input device you're using, is suddenly smoothed.

Looking in the configuration options for any input device, re: mouse, settings yields no results, as this is called, oddly, `cinematic mode`.

If you had a smartphone strapped to your face and wanted the POV to move smoothly, almost, maybe then I could understand the name.  I propose, additionally, to call it simply `input_smoothing` or something similar.

**Comment by paramat** [comment]
This seems reasonable as is more of a per-session thing than something that needs switching often in-game.
I agree 'cinematic mode' is unclear naming.

**Comment by paramat** [comment]
> perhaps add a setting that enables cinematic on f8 only if its set,

Please not another setting, it's not important enough.

> Maybe consider not binding "cinematic mode" to any key by default.

ANother possibility.

**Comment by rubenwardy** [comment]
:+1:

**Comment by Fixer-007** [comment]
I had no problem with cinematic mode :/
