### ISSUE TITLE
Keyboard is not working.

### ISSUE THREAD

**Issue by tirth-patel** [minetest/minetest#4285]
I have just installed the game and keyboard is not working. [ OS - windows 8.1 ].

**Comment by est31** [comment]
@tirth-patel which keys did you try? Does the mouse work? Which keyboard model do you have?

**Comment by est31** [comment]
And where did you download minetest from, which version?

**Comment by tirth-patel** [comment]
I downloaded it from: www.minetest.net. Mouse is working, alphabets and number keys aren't working.

**Comment by est31** [comment]
@tirth-patel which keyboard layout have you set up? If you have foreign alphabet keyboard layouts, it might not work. Can you try with an english keyboard layout?

**Comment by tirth-patel** [comment]
"English (India) US Keyboard" is my default keyboard. After adding "English (United States) US Keyboard" it's working now. Thank you. :)

**Comment by est31** [comment]
Yeah, its a known bug that different keyboard layouts don't work, see #3190
