### ISSUE TITLE
Cannot use remove_item() to remove item selected in hotbar / being held

### ISSUE THREAD

**Issue by whitephoenix0** [minetest/minetest#4286]
Background info: 
OS: up-to-date debian stretch
Minetest version: 0.4.14

While working on a mod, I spent forever trying to figure out why I couldn't remove the item I was holding after rightclicking a node, after some goofing off I tried to take a different item from my inventory. This worked, so I can remove items from my inventory, but not the itemstack that is selected on the hotbar and being held. 

Screenshots / steps:
 1) http://i.imgur.com/Mv979ZN.png
Notice that on line 32 and 33, shown on the left, if the player rightclicks holding "default:dirt", then it should run the fire_sigil_craft function, which spawns some particles, removes the item you rightclicked using, and then gives you an item defined in the function call. Also notice, it should take one default:tree from the inventory.

2) http://i.imgur.com/4eoIxV6.png
After rightclicking with dirt, you can see the default:tree count in the hotbar has changed from 33 to 32.

Now lets try removing the dirt item we rightclicked using:

3) http://i.imgur.com/AixJ47b.png
Notice I've changed line 48 to take dirt away

4) http://i.imgur.com/tAWgiwe.png
This is after rightclicking, you'll notice that before my inventory had 10 dirt, and after it also had 10 dirt despite the lua file on the left saying to remove it.

I'm not sure whether this was intended or not, but its very weird and will trip a lot of modders up, therefore I think it should be fixed. I'm happy to provide any additional info, just ask.

**Comment by paramat** [comment]
This may be a code error, 'on rightclick' needs to return the resulting 'itemstack', see https://github.com/minetest/minetest_game/pull/1173 for how.

**Comment by paramat** [comment]
Something like:
```
			if not minetest.setting_getbool("creative_mode") then
				itemstack:take_item()
			end
return itemstack
```
