### ISSUE TITLE
warning: ignoring return value of fread() in test_map_settings_manager.cpp

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#4290]
I'm just now getting this warning from the compiler for read_file_to_string(), and I noticed all kinds of screwy things (like using long instead of size_t).

This is with the latest Ubuntu LTS (gcc 5.3.1).

**Comment by est31** [comment]
**cc** @kwolekr

**Comment by nerzhul** [comment]
It's not present in recent versions
