### ISSUE TITLE
Anticheat false positives

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4291]
If anticheat is on, and physics override is greater than 1 (or whatever movement_speed_walk is), then anticheat resets position constantly.  This only occurs when you lack the fast priv!

https://www.youtube.com/watch?v=_FjERImCPxk

**Comment by est31** [comment]
Okay, this is a valid bug. Thanks for recording the video.

**Comment by tenplus1** [comment]
With many new mods being able to change player speed and jump height and potions that let you fly, anticheat itself is kinda useless now.

**Comment by thePalindrome** [comment]
The whole reason anticheat is here is not to prevent mods from doing things, but to prevent rogue clients from faking numbers.

Why have a mod teleport when you can just tell the server "I'm over here now?"

That's really why the anticheat is still a thing.

**Comment by 0-afflatus** [comment]
Anticheat is so broken and useless I disable it.
It would be good if it worked.

**Comment by everamzah** [comment]
I was told it adds a lot to the latency.  I never considered that, but if turning it off provides a smoother game play, then that's very tempting indeed.
