### ISSUE TITLE
cmake fails to find postgres on Debian.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4292]
Hi, cmake fails to find postgresql on debian.

```
-DPOSTGRESQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so.5.7
```

```
-- Could NOT find PostgreSQL (missing:  PostgreSQL_TYPE_INCLUDE_DIR) (found version "9.4.8")
-- PostgreSQL not found!
```

**Comment by Megaf** [comment]
[https://github.com/minetest/minetest/blob/master/README.txt#L207](url)

**Comment by est31** [comment]
Seems to be two bugs here :)

**Comment by Megaf** [comment]
@est31 Agreed
https://github.com/minetest/minetest/issues/4293

**Comment by est31** [comment]
Okay the one where autodetection fails is an usptream bug: https://cmake.org/pipermail/cmake/2012-December/053027.html

The other one where specifying the path manually fails is connected to that bug as well.

@Megaf you can work around by specifying the `PostgreSQL_TYPE_INCLUDE_DIR` variable instead:

```
-DPOSTGRESQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so.5.7 -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/
```

**Comment by Megaf** [comment]
Ok, it seems like cmake ignores totally the -DPOSTGRESQL_LIBRARY because when using
```
-DPOSTGRESQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so.5.7 -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/
```
It says...
```
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "9.4.8")
```
And it finds it anyway without using -DPOSTGRESQL_LIBRARY

**Comment by Megaf** [comment]
I believe this has been fixed. Haven't encountered this bug anymore, therefore I'm closing this issue.

**Comment by Megaf** [comment]
Fixed.
