### ISSUE TITLE
POSTGRE_SQL_INCLUDE_DIR option doesn't work.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4293]
```
-DPOSTGRESQL_INCLUDE_DIR=/usr/include/postgresql/
```

```
  Manually-specified variables were not used by the project:

    POSTGRESQL_INCLUDE_DIR
```

**Comment by est31** [comment]
Its either a doc issue (our README.txt being wrong), or an issue with the cmake.

**Comment by SmallJoker** [comment]
Weird enough there are multiple PostgreSQL variables shown in `cmake-gui`:
```
POSTGRESQL_CONFIG_EXECUTABLE (FILEPATH)
POSTGRESQL_LIBRARY (FILEPATH)
PostgreSQL_INCLUDE_DIR (PATH)
PostgreSQL_LIBRARY (FILEPATH)
PostgreSQL_TYPE_INCLUDE_DIR (PATH)
```
Could you try to use `-DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql/`?

**Comment by Megaf** [comment]
@SmallJoker https://github.com/minetest/minetest/issues/4292#issuecomment-230922546

**Comment by nerzhul** [comment]
warning it's PostgreSQL_INCLUDE_DIR not POSTGRESQL_INCLUDE_DIR, it's not the same variable

**Comment by fgrosswig** [comment]
still no joy compiling with posgtreSQL support -

```
 Could NOT find PostgreSQL (missing:  PostgreSQL_TYPE_INCLUDE_DIR) (found version "9.5.6")
-- PostgreSQL not found!
```

compiling options:

```
cmake . -DRUN_IN_PLACE=1 -DBUILD_CLIENT=0  -DENABLE_REDIS=1 \
-DPostgreSQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so.5.8 -DENABLE_POSTGRESQL=1 \
-DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql/ -DBUILD_SERVER=true \
-DENABLE_GETTEXT=1 -DENABLE_FREETYPE=1 -DENABLE_LEVELDB=0 \
-DCMAKE_BUILD_TYPE=Debug
```
when this will be fixed? last comment on this was july last year ✌️

**Comment by ExeterDad** [comment]
With a bunch of trial and error I can get it to build with this:

	-DENABLE_POSTGRESQL=1 \
	-DPOSTGRESQL_INCLUDE_DIR=/usr/include/postgresql/ \
	-DPOSTGRESQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so.5.7 \
	-DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/ \

my servers on Debian so your mileage may vary.

**Comment by nerzhul** [comment]
Doc typo fixed in master
