### ISSUE TITLE
Item description bug, again

### ISSUE THREAD

**Issue by theraven262** [minetest/minetest#4299]
I got the same problem as: https://github.com/minetest/minetest/issues/4142 .I had compiled the latest minetest version and the bug is still here.Version output : 

Minetest 0.4.14-dev-795f1c7 (Linux)
Using Irrlicht 1.8.3
Build info: VER=0.4.14-dev-795f1c7 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=0 STATIC_SHAREDIR="/usr/local/share/minetest"

**Comment by C1ffisme** [comment]
I think you should have bumped the old thread, rather than creating a new one...

**Comment by paramat** [comment]
I re-opened #4142 please can you transfer this to there?

**Comment by est31** [comment]
I agree, the discussion should be moved to the new bug.

**Comment by Zeno-** [comment]
@theraven262 in the other thread please provide more details. E.g. when does this bug occur? What mods? etc. etc

**Comment by paramat** [comment]
@theraven262 i don't experience this with Irrlicht version 1.8.3 can you retest?
