### ISSUE TITLE
Merge fail in weblate

### ISSUE THREAD

**Issue by Jibec** [minetest/minetest#4301]
Hi there, since june 5th I get an everyday mail alert about failed mail in weblate. Can you please fix this ? As I have a filter, I only notice when I go have a look in my dedicated folter for weblate alerts.

Btw, are we sure Weblate includes everything coming from minetest_game and the defaults mods ?

 Bonjour,

Un échec de fusion s'est produit sur Minetest/Minetest à Hosted Weblate.

Message d'erreur

Auto-merging src/mapgen.h
Auto-merging src/mapgen.cpp
CONFLICT (content): Merge conflict in src/mapgen.cpp
Removing doc/old/changelog.txt
Removing doc/old/ancient_main_comment.txt
Automatic merge failed; fix conflicts and then commit the result. (1)

État du référentiel

On branch master
Your branch and 'origin/master' have diverged,
and have 17 and 33 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

	modified:   build/android/jni/Android.mk
	modified:   builtin/common/strict.lua
	modified:   builtin/game/item.lua
	modified:   builtin/settingtypes.txt
	modified:   doc/lua_api.txt
	deleted:    doc/old/ancient_main_comment.txt
	deleted:    doc/old/changelog.txt
	modified:   minetest.conf.example
	new file:   misc/minetest-xorg-icon-128.png
	modified:   src/CMakeLists.txt
	modified:   src/client/clientlauncher.cpp
	modified:   src/content_nodemeta.cpp
	modified:   src/craftdef.cpp
	modified:   src/craftdef.h
	modified:   src/defaultsettings.cpp
	modified:   src/dungeongen.cpp
	modified:   src/dungeongen.h
	modified:   src/emerge.cpp
	modified:   src/emerge.h
	modified:   src/environment.cpp
	modified:   src/game.cpp
	modified:   src/guiChatConsole.cpp
	modified:   src/guiEngine.cpp
	modified:   src/guiEngine.h
	modified:   src/guiKeyChangeMenu.cpp
	modified:   src/intlGUIEditBox.cpp
	modified:   src/map.cpp
	modified:   src/map.h
	new file:   src/map_settings_manager.cpp
	new file:   src/map_settings_manager.h
	modified:   src/mapblock.h
	modified:   src/mapgen.h
	modified:   src/mapgen_flat.cpp
	modified:   src/mapgen_flat.h
	modified:   src/mapgen_fractal.cpp
	modified:   src/mapgen_fractal.h
	modified:   src/mapgen_singlenode.h
	modified:   src/mapgen_v5.cpp
	modified:   src/mapgen_v5.h
	modified:   src/mapgen_v6.cpp
	modified:   src/mapgen_v6.h
	modified:   src/mapgen_v7.cpp
	modified:   src/mapgen_v7.h
	modified:   src/mapgen_valleys.cpp
	modified:   src/mapgen_valleys.h
	modified:   src/mg_biome.cpp
	modified:   src/mg_biome.h
	modified:   src/nodedef.cpp
	modified:   src/nodetimer.cpp
	modified:   src/nodetimer.h
	modified:   src/player.h
	modified:   src/porting.cpp
	modified:   src/porting.h
	modified:   src/script/cpp_api/s_player.cpp
	modified:   src/script/cpp_api/s_player.h
	modified:   src/script/lua_api/l_craft.cpp
	modified:   src/script/lua_api/l_craft.h
	modified:   src/script/lua_api/l_mainmenu.cpp
	modified:   src/script/lua_api/l_mapgen.cpp
	modified:   src/script/lua_api/l_mapgen.h
	modified:   src/script/lua_api/l_nodetimer.cpp
	modified:   src/script/lua_api/l_object.cpp
	modified:   src/script/lua_api/l_object.h
	modified:   src/script/lua_api/l_vmanip.cpp
	modified:   src/server.cpp
	modified:   src/settings.cpp
	modified:   src/settings.h
	modified:   src/sky.cpp
	modified:   src/subgame.cpp
	modified:   src/threading/thread.cpp
	modified:   src/unittest/CMakeLists.txt
	new file:   src/unittest/test_map_settings_manager.cpp
	modified:   src/unittest/test_threading.cpp
	modified:   src/util/string.cpp
	modified:   src/util/string.h

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both modified:   src/mapgen.cpp

**Comment by est31** [comment]
I've mailed nijel about this and he meant that we have a github hook set up to auto-sync weblate via git. I have asked @celeron55 to turn off the hook. Weird that this issue still exists...

**Comment by est31** [comment]
> Btw, are we sure Weblate includes everything coming from minetest_game and the defaults mods ?

Weblate currently only manages the main engine translations.

**Comment by est31** [comment]
To give background: these merge fails happen due to how minetest is developed: we have a rule that allows changing commits by force pushing on master within the first 10 minutes after the commit was pushed. These force-pushes create the merge failures in weblate, as weblate updates the moment the commit was pushed, not 10 minutes after it, and gets confused by the new force pushed commit (technically, these are two separate commits, with same parent).

So the best approach to prevent these merge failures is to prevent weblate auto-merging in changes. We don't need this auto-merging anyway, as the other merge direction is done manually anyway, and the source strings get updated manually as well (the source strings being updated is the only time source repo changes are relevant to weblate). All other times, we don't need auto-merging.

**Comment by Jibec** [comment]
I don't understand everything you said, I assume things are going to be fixed, but just to let you know the translator point of view : weblate is a great tool for single project management because it is really close to git content. So dev don't have to worry about it and translators can work without fear to work on out of date content.

Please continue taking good care of us because in my situation it's my only way to thank you by contributing in translations !

If not too difficult, can you include minetest-game so we have a more locale version of the game ?

Ideally, make it possible to translate other parts of minetest, maybe can we have a common subproject containing all plugins strings (the idea is to reduce redundancy) ?

It would be nice to also use this reporting to give credits to contributors : https://docs.weblate.org/en/latest/devel/reporting.html#translator-credits

It's a nice project, continue doing well !

**Comment by est31** [comment]
Hrmm, so I've fixed it again and it seems the weblate repo has stopped auto updating. That's a good sign, meaning the bug is fixed long term!
