### ISSUE TITLE
Ability to define a list of nodes/node groups which cause or not cause a particle collision

### ISSUE THREAD

**Issue by neoascetic** [minetest/minetest#4305]

**Comment by paramat** [comment]
So currently they only collide with walkable = true?

**Comment by paramat** [comment]
:-1: They would then collide with walkable mostly empty nodes like plants, also with airlike nodes like fog or vacuum.

**Comment by neoascetic** [comment]
Okay, I just don't want my raindrops to fall through water. What should I do?

**Comment by paramat** [comment]
Well we can consider adding collision with water nodes.

**Comment by neoascetic** [comment]
I don't think adding exception only for water nodes is a great idea. How about the more general approach: ability to define a list of nodes/node groups which cause or not cause a collision?

**Comment by paramat** [comment]
Perhaps, and yes that would be better.

**Comment by paramat** [comment]
I support doing something, either definable node types, or collision with liquids as requested in #9834

**Comment by appgurueu** [comment]
Why close this as completed when it isn't? Have you lost interest in the feature?
