### ISSUE TITLE
Minetest fails to link JSONCPP on Debian 9.x if -DENABLE_SYSTEM_JSONCPP=1

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4306]
Might be some problem on Debian itself, I tried with Minetest Stable 0.4 branch too and got the same result.
`cmake /home/user/Documents/games/minetest -DWARN_ALL=0 -DRUN_IN_PLACE=0 -DENABLE_GETTEXT=0 -DENABLE_CURL=0 -DCMAKE_BUILD_TYPE=MinSizeRel -DENABLE_LEVELDB=0 -DENABLE_POSTGRESQL=0 -DENABLE_REDIS=0 -DENABLE_SPATIAL=0 -DENABLE_SYSTEM_GMP=1 -DENABLE_SYSTEM_JSONCPP=1 -DENABLE_CURSES=0 -DENABLE_GLES=1 -DRUN_IN_PLACE=1`

```
[100%] Linking CXX executable /home/user/Documents/games/minetest/bin/minetest
CMakeFiles/minetest.dir/client/clientlauncher.cpp.o: In function `ClientLauncher::launch_game(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, bool, GameParams&, Settings const&)':
clientlauncher.cpp:(.text+0x1c6a): undefined reference to `Json::Value::operator=(Json::Value const&)'
clientlauncher.cpp:(.text+0x1ca9): undefined reference to `Json::Value::operator=(Json::Value const&)'
clientlauncher.cpp:(.text+0x1ce8): undefined reference to `Json::Value::operator=(Json::Value const&)'
clientlauncher.cpp:(.text+0x1d27): undefined reference to `Json::Value::operator=(Json::Value const&)'
CMakeFiles/minetest.dir/script/common/c_content.cpp.o: In function `read_json_value(lua_State*, Json::Value&, int, unsigned char)':
c_content.cpp:(.text+0x1c74): undefined reference to `Json::Value::operator=(Json::Value const&)'
CMakeFiles/minetest.dir/script/common/c_content.cpp.o:c_content.cpp:(.text+0x1ca6): more undefined references to `Json::Value::operator=(Json::Value const&)' follow
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetest.dir/build.make:5330: recipe for target '/home/user/Documents/games/minetest/bin/minetest' failed
make[2]: *** [/home/user/Documents/games/minetest/bin/minetest] Error 1
CMakeFiles/Makefile2:142: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

Debian Stretch x86_64.

**Comment by Megaf** [comment]
Testing with CC=gcc-4.8 CXX=cpp-4.8 cmake gives me a 
```
-- Check for working CXX compiler: /usr/bin/cpp-4.8 -- broken
CMake Error at /usr/share/cmake-3.5/Modules/CMakeTestCXXCompiler.cmake:54 (message):
  The C++ compiler "/usr/bin/cpp-4.8" is not able to compile a simple test
  program.

  It fails with the following output:

   Change Dir: /dev/shm/build/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/make" "cmTC_07c33/fast"

  /usr/bin/make -f CMakeFiles/cmTC_07c33.dir/build.make
  CMakeFiles/cmTC_07c33.dir/build

  make[1]: Entering directory '/dev/shm/build/CMakeFiles/CMakeTmp'

  Building CXX object CMakeFiles/cmTC_07c33.dir/testCXXCompiler.cxx.o

  /usr/bin/cpp-4.8 -o CMakeFiles/cmTC_07c33.dir/testCXXCompiler.cxx.o -c
  /dev/shm/build/CMakeFiles/CMakeTmp/testCXXCompiler.cxx

  cpp-4.8: fatal error: ‘-c’ is not a valid option to the preprocessor

  compilation terminated.

  CMakeFiles/cmTC_07c33.dir/build.make:65: recipe for target
  'CMakeFiles/cmTC_07c33.dir/testCXXCompiler.cxx.o' failed

  make[1]: *** [CMakeFiles/cmTC_07c33.dir/testCXXCompiler.cxx.o] Error 4

  make[1]: Leaving directory '/dev/shm/build/CMakeFiles/CMakeTmp'

  Makefile:126: recipe for target 'cmTC_07c33/fast' failed

  make: *** [cmTC_07c33/fast] Error 2

  

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:9 (project)


-- Configuring incomplete, errors occurred!
```
Not sure if it's a bug in my system or minetest.

**Comment by Zeno-** [comment]
Well, it's certainly not caused by 4c530de because that commit only changes comments.

**Comment by Fixer-007** [comment]
GCC 4.9.2 cross-compilation was successful on that build.

**Comment by Megaf** [comment]
@Zeno- Stable 0.4 doesnt link either, maybe a problem with Debian itself?

**Comment by Rogier-5** [comment]
From superficial examination, I guess that minetest may be using the wrong header files, or linking against the incorrect jsoncpp library. See also [this information](http://stackoverflow.com/questions/28445744/undefined-reference-in-jsoncpp-operator) and [this issue](https://github.com/open-source-parsers/jsoncpp/issues/484). Most people probably don't use `-DENABLE_SYSTEM_JSONCPP=1`, so that might be the reason that the problem has remained undetected.

If that *is* the problem, maybe that removing `src/json` might make a difference (workaround-type).

**Comment by Megaf** [comment]
@Rogier-5 Indeed it links with -DENABLE_SYSTEM_JSONCPP=0

**Comment by Rogier-5** [comment]
> Indeed it links with -DENABLE_SYSTEM_JSONCPP=0

Then, from the information, it seems that minetest either still uses the included version of the json include file (instead of the system version) when compiling with `-DENABLE_SYSTEM_JSONCPP=1`, or it uses the correct include file, but links with the included version of the json library anyway, instead of using the system version.

**Comment by Rogier-5** [comment]
The primary problem turns out to be that minetest uses `#include "json/json.h"`, where it should use `#include <json/json.h>`. I fixed that - see PR #4429

**Comment by Megaf** [comment]
@sfan5 Why you closed this if it wasnt fixed?

**Comment by sfan5** [comment]
The PR that was supposed to fix this was merged.

**Comment by paramat** [comment]
Similar problem reported.

**Comment by rdococ** [comment]
For me, using Debian 8.6, neither -DENABLE_JSON_CPP=1 nor -DENABLE_JSON_CPP=0 seems to work.

**Comment by stujones11** [comment]
Solution for me here: https://forum.minetest.net/viewtopic.php?f=6&t=18147

Not sure if this is debian or MT related so did not open an issue.

**Comment by Megaf** [comment]
Fixed.

**Comment by ne-vlezay80** [comment]
[ 35%] Building CXX object src/CMakeFiles/minetest.dir/script/scripting_client.cpp.o
/usr/src/minetest/src/script/lua_api/l_util.cpp: In static member function ‘static int ModApiUtil::l_parse_json(lua_State*)’:
/usr/src/minetest/src/script/lua_api/l_util.cpp:101:3: error: ‘CharReaderBuilder’ is not a member of ‘Json’
   Json::CharReaderBuilder builder;
   ^
/usr/src/minetest/src/script/lua_api/l_util.cpp:102:3: error: ‘builder’ was not declared in this scope
   builder.settings_["collectComments"] = false;
   ^
/usr/src/minetest/src/script/lua_api/l_util.cpp:105:8: error: ‘parseFromStream’ is not a member of ‘Json’
   if (!Json::parseFromStream(builder, stream, &root, &errs)) {
        ^
[ 35%] Building CXX object src/CMakeFiles/minetest.dir/script/scripting_mainmenu.cpp.o
src/CMakeFiles/minetest.dir/build.make:1434: ошибка выполнения рецепта для цели «src/CMakeFiles/minetest.dir/script/lua_api/l_util.cpp.o»
make[2]: *** [src/CMakeFiles/minetest.dir/script/lua_api/l_util.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…
CMakeFiles/Makefile2:193: ошибка выполнения рецепта для цели «src/CMakeFiles/minetest.dir/all»
make[1]: *** [src/CMakeFiles/minetest.dir/all] Ошибка 2
Makefile:137: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by Megaf** [comment]
Not sure if that is related to this issue.

**Comment by Megaf** [comment]
I just built Minetest Server 0.4 stable on Debian Buster/Testing/10. With systemjson, no problem at all. @ne-vlezay80 @SmallJoker
