### ISSUE TITLE
Footstep sound is played twice as fast on fences

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4310]
If you walk on a fence the footstep sound is played twice as fast as normal. Sounds more like running

**Comment by est31** [comment]
Its probably because you collide with the collision boxes more often, which results in this.

**Comment by SmallJoker** [comment]
#1460

**Comment by paramat** [comment]
Probably unfixable, and not a big problem.

**Comment by paramat** [comment]
Seems ok to me, little steps as you carefully tread. This can be folded into #1460
