### ISSUE TITLE
Local variable ignored in ores definition

### ISSUE THREAD

**Issue by Gael-de-Sailly** [minetest/minetest#4314]
That may occur in many other situations, I've not tested all.

Create a test mod and write this into init.lua:
```lua
local noise = {
    offset         = 0,
    scale          = 1,
    spread         = {x=256,y=512,z=256},
    persist        = 0.5,
    octaves        = 5,
    seed           = 20099,
    flags          = "absvalue"
},

minetest.register_ore({
    ore_type       = "scatter",
    ore            = "default:wood",
    wherein        = "air",
    clust_scarcity = 8 * 8 * 8,
    clust_num_ores = 10,
    clust_size     = 3,
    y_min          = -31000,
    y_max          = 31000,
    noise_params   = noise,
    noise_threshold= 1,
})
```
I get this: `WARNING[Main]: Undeclared global variable "noise" accessed at /home/gael/.minetest/mods/test/init.lua:20` and the `noise params` are not applied.

**Comment by paramat** [comment]
It's not often that we need to duplicate one noise param in many registrations, so labelling as low priority.

**Comment by bendeutsch** [comment]
I just tried to reproduce this – could it be that the issue is actually the comma "," after the noise definition? The warning disappears if you change it to a semicolon. Can't confirm the noise parameters being applied, though :-P

**Comment by paramat** [comment]
Good point, that table should not have a comma after it.

**Comment by Gael-de-Sailly** [comment]
That's actually the comma! I've removed it and it works!
