### ISSUE TITLE
Documentation for checkbox[] incorrect

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4317]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1599 Reads checkbox[x;y;name;label;selected;tooltip] but tooltip is an invalid element.

**Comment by SmallJoker** [comment]
Code reference: https://github.com/minetest/minetest/blob/master/src/guiFormSpecMenu.cpp#L378
There's no sign of parts[4]

**Comment by paramat** [comment]
#4318 merged.
