### ISSUE TITLE
X11 Icon not shown when minetest is installed via make install

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4323]
As @everamzah has [pointed out](https://github.com/minetest/minetest/commit/5d4d3f8366b74d9c3da892d94188defc49407ebf#commitcomment-18271629), minetest does not show the X11 icon when its installed via make install.

There are several things we have to do / figure out to fix this bug:

1. find a suitable location for the icon. Maybe `$ICONDIR`? Read the xdg spec and similar to find more about this.
1. tell the cmake script to install the icon on that location
1. tell the code to look for the icon on that location

There is a different way to solve this, which would involve adding the minetest png image in the build process to the binary, using `objcopy` ([link here](http://stackoverflow.com/a/4865249)). This requires binutils, which should be available on every unix platform minetest is built. Then we spare all this "where to put the image" business.

**Comment by est31** [comment]
@everamzah can you try whether this patch (made thaks to the suggestions of @ShadowNinja) fixes the issue for you: https://github.com/est31/minetest/tree/icon_install

**Comment by everamzah** [comment]
It appears that minetest is still looking in /usr/local/share/minetest/misc, but has installed to /usr/local/share/icons.

**Comment by est31** [comment]
Ah stupid me, I should have used || and not &&.

**Comment by est31** [comment]
@everamzah can you update the branch and try the new commit?
