### ISSUE TITLE
Better sounds

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#4328]
Minetest sounds are usable but needs to be enhanced

**Comment by SmallJoker** [comment]
You're free to collect good (and free/libre) sounds and create a pull request to make the game better.

**Comment by MarkuBu** [comment]
other sounds for ice and snow would be nice.

**Comment by est31** [comment]
I certainly agree, the sounds for ice and snow are bad, and could be improved, but this is no engine bug. Please open a bug on the minetest_game repository (if there's none yet): https://github.com/minetest/minetest_game/issues
