### ISSUE TITLE
2D Player texture on front view looks like mirrored. Instead of normal.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4329]
![2d skin bug](https://cloud.githubusercontent.com/assets/13905392/16899801/70a7f720-4c19-11e6-8160-5cfe7823cdc6.png)
I'm on Minimal Development Test subgame, for testing 2D textures. It's a bug on 2D player front texture, because, 2D player front texture looks like a mirrored in-game. Must be normal look...

**Comment by paramat** [comment]
#4360 is merged.
