### ISSUE TITLE
Huge item glitch (at least I think it's a glitch)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4341]
It's very simple to duplicate first you need to be in Windowd mode, then open up the inventory (press e). hold a Block/item on your cursor and take it outside the window (DONE! a giant version of the item you're holding should be displayed)
![dzzf](https://cloud.githubusercontent.com/assets/16853304/17020976/eb308380-4f44-11e6-9901-82e9a851b1f5.png)

**Comment by t4im** [comment]
Can't reproduce it. When trying to move it outside the window, it just squeezes on the edge.
Clicking will obviously lose window focus. Clicking outside the formspec correctly drops the item.

**Comment by Fixer-007** [comment]
Reproduced. Will post gif.

**Comment by tobyplowy** [comment]
@t4im yeah first it squeezes it and then it's a huge item you have to go further outside the window ( also my operating system is Windows this may not work on other systems.)

**Comment by SmallJoker** [comment]
Can not reproduce this on my Win XP machine (MSVC binary), the item gets dropped.
When was this bug first seen? (Minetest version)
Does it happenin other subgames too?

**Comment by tobyplowy** [comment]
@SmallJoker i use win 10
i cant test the latest dev build it keeps giving me this
@paramat what is this?
-------------
  Separator
-------------

2016-07-21 13:08:57: [Main]: Automatically selecting world at [C:\Games\Minetest\bin\..\worlds\zzzdeafefefqd]
2016-07-21 13:08:59: WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition
2016-07-21 13:08:59: ERROR[Main]: ModError: Failed to load and run script from C:\Games\Minetest\bin\..\games\minetest_game-master\mods\default\init.lua:
2016-07-21 13:08:59: ERROR[Main]: ...in\..\games\minetest_game-master\mods\default/mapgen.lua:1471: attempt to call field 'get_mapgen_setting' (a nil value)
2016-07-21 13:08:59: ERROR[Main]: stack traceback:
2016-07-21 13:08:59: ERROR[Main]: 	...in\..\games\minetest_game-master\mods\default/mapgen.lua:1471: in main chunk
2016-07-21 13:08:59: ERROR[Main]: 	[C]: in function 'dofile'
2016-07-21 13:08:59: ERROR[Main]: 	...\bin\..\games\minetest_game-master\mods\default\init.lua:45: in main chunk
2016-07-21 13:08:59: ERROR[Main]: Kijk in debug.txt voor details.

![dzzf](https://cloud.githubusercontent.com/assets/16853304/17020993/152b2302-4f45-11e6-928d-23fe6ffc02ee.png)

**Comment by SmallJoker** [comment]
@tobyplowy, your "latest" dev build does not contain the commit 3c63c30 yet. Your MTG (minetest_game) is newer than the core, that's why you get this error.

The bug looks exactly the same way to me.

**Comment by t4im** [comment]
> yeah first it squeezes it and then it's a huge item you have to go further outside the window ( also my operating system is Windows this may not work on other systems.)

Even going 1600px+ outside won't break it for me. So it's probably indeed a windows-only issue.

**Comment by tobyplowy** [comment]
@smalljoker so is this a bug? Also Does it happen on the unstable?

**Comment by SmallJoker** [comment]
Tested on today's fresh build:
![20160721_1509_28 00_00_00-00_00_10](https://cloud.githubusercontent.com/assets/1497498/17023844/a898060e-4f55-11e6-861e-19e1141568e9.gif)

**Comment by MarkuBu** [comment]
Looks like a windows only bug. Can't confirm this with Ubuntu

**Comment by tobyplowy** [comment]
Can anyone test this on Mac?

**Comment by tobyplowy** [comment]
@SmallJoker yeah that's exactly what happens thank you for the gif

**Comment by pithydon** [comment]
This bug works on mac to, but does not rotate.
OS X 10.11.6, Minetest 4.14 stable

**Comment by paramat** [comment]
This is funny.

**Comment by tobyplowy** [comment]
@pithydon are rotating items enabled in the settings?

**Comment by tobyplowy** [comment]
@paramat true XD

**Comment by pithydon** [comment]
The rotating part does work an mac I just had it disabled.

**Comment by DonBatman** [comment]
Tested on Ubuntu 16.04.
The item does go large and then falls to ground as a dropped item. It is too fast to matter.

**Comment by GReaperEx** [comment]
Tested 0.4.14-dev-2ba8ad1 on Ubuntu 14.04, 
I can't reproduce it at all.

**Comment by Wuzzy2** [comment]
The *particular* reported bug does not seem to exist on my GNU/Linux machine on a dev build.
The item image just becomes smaller.

But I have news for you: It appears there's a related bug which causes the item image to become huge if you have any item images in a formspec. If you then shrink the window to a size that one of the item images becomes very small (maybe one of the dimensions is zero), the item image suddenly becomes very huge.

You can easily test this with `doc_items` and opening one of the item help pages with an item image inside. Just squeeze the window horizontally and see what heppens.
