### ISSUE TITLE
Make client server list searchable

### ISSUE THREAD

**Issue by Miner48er** [minetest/minetest#4342]
Add search bar to client server list.

**Comment by DonBatman** [comment]
I would like to see this too.

**Comment by Ezhh** [comment]
Would like to see this.

As a suggestion to improve further: ability to filter based on type of server could also be useful.

**Comment by Miner48er** [comment]
Suggestion: filtering and sorting for all columns.

**Comment by LazyJ** [comment]
Another idea to toss on the table - what about a connection strength icon like the signal strength bars of a cell phone with the "connection strength" being a scale based on the ping between the client and individual servers on the list? That would probably take several moments to go through the full list. Another idea would be server IP's country and region/state/province/parish/whatever is the next sub-division smaller than "country" in whois.

**Comment by 0-afflatus** [comment]
Search bar and column sorting are great ideas; but KISS, so none of whatever LazyJ is trying to suggest.

**Comment by red-001** [comment]
see #4472

**Comment by SmallJoker** [comment]
Added in #5000
