### ISSUE TITLE
Outdated profiler settings in minetest.conf.example

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4348]
After profiler overhaul https://github.com/minetest/minetest/commit/d7060c212f3d9fb9a69719e9041fdef1f5792fef you forgot to update minetest.conf.example file, right now it has:
```
#    Useful for mod developers.
#    type: bool
# mod_profiling = false

#    Detailed mod profile data. Useful for mod developers.
#    type: bool
# detailed_profiling = false

#    Profiler data print interval. 0 = disable. Useful for developers.
#    type: int
# profiler_print_interval = 0 
```
but this ones are outdated entries.
@t4im @est31

**Comment by est31** [comment]
Nobody guarantees minetest.conf.example to be up to date. thats only provided for releases. Otherwise, there will be commits to update the file every now and then.

**Comment by paramat** [comment]
Nah .. minetest.conf is indeed kept up to date, it has to be as many players use latest dev versions of Minetest. Remember to update builtin/settingtypes.txt too if necessary.

**Comment by est31** [comment]
`builtin/settingtypes.txt` should **always** be up to date, because minetest.conf.example is autogenerated from it. If minetest.conf.example contains a setting that settingtypes.txt doesn't, then the next update will remove it from minetest.conf.example.

**Comment by paramat** [comment]
Oops just saw t4im's commit did update settingtypes.txt, sorry.

**Comment by est31** [comment]
Either way, I've updated minetest.conf.example as well: f833159a68f2ff605224ed7a5ac956e5a0ca42d8

**Comment by paramat** [comment]
Nice, i am concerned that although we can auto-generate .conf that this doesn't get done often enough, creating an imprecise document for those using latest dev.
I'm in the habit of always updating .conf manually in my PRs.
