### ISSUE TITLE
Make PointedThing more informative

### ISSUE THREAD

**Issue by juhdanad** [minetest/minetest#4349]
A feature request: in the Lua API pointed_thing could contain the point of collision, the normal vector of the colliding face and maybe the real undersurface node.

The point of collision is where the player's shootline meets the pointed thing's nearest nodebox.
The normal vector points outwards of the nodebox and is perpendicular to the colliding face.
If the node's nodebox exceeds the node's bounds (for example the refrigeator in the home decor mod), the above and under nodes are not always neighbors. The real undersurface node is the neighbor of the above node which contains the nodebox. (this can be calculated as above-normal)

Mods could use this feature to get right-click input without formspecs (for example a keyboard node could determine which button was clicked) and to place small nodes on the the place of the click (like microblocks). Entities could also react differently based on where they were punched.

Note that #4346 already computes these values and places them in the PointedObject, they just need to be exposed to the Lua API.

But it would be a nice feature even if that request gets not merged.

**Comment by paramat** [comment]
We now have a way to get exact pointed position on the face of a node.

**Comment by juhdanad** [comment]
#6304 partially implements this.
The function that returns the exact pointing location is not always accurate, because the client rounds the looking direction before sending it to the server.

What I wanted is to make the client send this information over the network. This now can be done as there is a compatibility break.

**Comment by paramat** [comment]
Any core dev support?

**Comment by ClobberXD** [comment]
@paramat - This was implemented in a PR which was merged a few days ago - #6304
