### ISSUE TITLE
It wont let me start the game

### ISSUE THREAD

**Issue by HuuvyTheBest** [minetest/minetest#4351]
Dear Minetest Creator/Developer,

I have an issue where i start the game and when i started it it open the black thing and the Main Menu and the Main Menu was just full of white.
 Within like 5 second, the Minetest Engine stop working, it says something but i dont remember the word.

Please fix this me and my friend have a lot of great times in that game and i love it and Minetest just seems to broke it.

 Your Sincerely,
Awerey Nick McRichmen

**Comment by rubenwardy** [comment]
Please post the last 20 lines of your debug.txt here.

If you used the windows installer, this will be found at C://games/minetest/bin/debug.txt

Copy the last 20 lines, write:

    ```

then paste the file content then write:

    ```

again

**Comment by SmallJoker** [comment]
Please reopen if you're able to reproduce this bug and provise us some debugging information.
