### ISSUE TITLE
"require" in lua

### ISSUE THREAD

**Issue by ferchaure** [minetest/minetest#4354]
Hi, I have problems (instant crash without error message) using "require()" in a lua mod.  does the lua interpreter support that function?

Is there a way to Call C or Python functions from the mods?

**Comment by t4im** [comment]
I'm successfully using `require()` for requiring lua modules. But it won't work well with mod_security enabled.

You could also use `os.execute()`, needing mod_security to be disabled or an insecure environment being requested via minetest api.

**Comment by ferchaure** [comment]
In my case, it works only for Lua modules.

I could use os.execute(), but I have to be quite precise in timing, and run another application isn't the best option.

**Comment by t4im** [comment]
What do you need it for?
It might be better to execute the time sensitive code in lua and then just pass the results. It's how most profiling or benchmarking is done in minetest.

**Comment by ferchaure** [comment]
I have a recording system for EEG signals ( and a few more) and my idea is synchronise  that recording with the position of the player in the map. Usually we send pulses from the PC to the system to mark events (in this case position logging times). 
I wanted to load the C functions we use to communicate with the recording system and use them when I log the position (2 or 3 times per second). But minetest crash when I load the dll.  I tested the dll using luaforwindows, maybe I have to use MinGW to compile the dll?

**Comment by t4im** [comment]
That's pretty cool!

Generally you cannot just use *any* c library with `require`, Lua expects a special format for it: 
http://www.lua.org/pil/26.2.html

LuaJit has an extension though, that might help you anyway: http://luajit.org/ext_ffi.html
If that dosn't work, maybe write time + position to a named pipe (fifo)?

Minetest provides µs precision with `minetest.get_us_time()` btw, if that would be enough.

**Comment by ferchaure** [comment]
I made a wrapper for the C functions and I tested them in luaforwindows, and they worked in that environment.

I tried to use the socket module to make a tcp communication between Lua and a python script outside but minetest crash when I do require("socket"). (In any case I didn't know how to make all the code even in luaforwindows)

I was using os.clock for get the time.
