### ISSUE TITLE
strange behavior in minetest.register_node

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest#4356]
Not entirely sure if this is a bug in Minetest or a bug in https://github.com/pithydon/comboblock/releases
Somehow registering a node prevents registering a node. I had "comboblock:stairs_slab_stonebrick_onc_stairs_slab_brick" in my inventory then added a minetest.register_node to my code and the node became unknown. I added a comment in my mod saying "bug is here" to mark it. Mods that are ran after my mod can still register nodes.

**Comment by NathanSalapat** [comment]
that URL doesn't link to anything, comes up with a 404 error.

**Comment by paramat** [comment]
Seeing the complexity of your code i suspect a mod error.

**Comment by pithydon** [comment]
:P fixed the link

**Comment by pithydon** [comment]
I was able to get around this by redesigning my mod.
I suspect the bug stems from registering nodes while reading "minetest.registered_nodes".
My mod no longer reads registered nodes.

**Comment by paramat** [comment]
Do you still consider it a bug or can we close this?

**Comment by pithydon** [comment]
If it is the case that you can't register nodes wile reading registered nodes, then it depends on if the devs want that to be a feature of minetest.

**Comment by t4im** [comment]
This isn't really a minetest issue.

Adding to a hashtable has no guarantee of order nor does pairs for iteration. I would generally not recommend adding to tables you iterate, unless you know what you are doing.

**Comment by paramat** [comment]
I agree, it's an inherent behaviour of any code.
