### ISSUE TITLE
Document special textures in lua_api.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4358]
Minetest gradually has built a number of “special” textures, that is, textures which are in some way needed or used by the engine directly rather than provided by a mod. Examples are `bubble.png`, `crack_anylength.png` or `crosshair.png`. A non-example is `default_apple.png`.

However, there is zero documentation on these quite important files, this should be changed. This is important for mods and texture packs.

For myself, I know a few names of special textures, but probably not all. Can someone who knows more about this please list them in this issue?

Requirements:

* Document the names of *all* special textures (at least those which can be set by mods and texture packs)
* Document for each texture at least:
   * File name
   * Purpose
   * Expected size (if applicable)
   * Other technical requirements (if applicable)
* Maybe mention reserved/forbidden names

**Comment by paramat** [comment]
#4381 merged.
