### ISSUE TITLE
Minetest no longer compiles with LevelDB

### ISSUE THREAD

**Issue by nolsen42** [minetest/minetest#4365]
I get this error while compiling:

<pre>
/usr/local/lib/libleveldb.a(table_builder.o): In function `leveldb::TableBuilder::WriteBlock(leveldb::BlockBuilder*, leveldb::BlockHandle*)':
table_builder.cc:(.text+0x7c9): undefined reference to `snappy::MaxCompressedLength(unsigned long)'
table_builder.cc:(.text+0x7f6): undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/usr/local/lib/libleveldb.a(format.o): In function `leveldb::ReadBlock(leveldb::RandomAccessFile*, leveldb::ReadOptions const&, leveldb::BlockHandle const&, leveldb::BlockContents*)':
format.cc:(.text+0x43a): undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
format.cc:(.text+0x5c0): undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetestserver.dir/build.make:4161: recipe for target 'bin/minetestserver' failed
make[2]: *** [bin/minetestserver] Error 1
CMakeFiles/Makefile2:147: recipe for target 'src/CMakeFiles/minetestserver.dir/all' failed
make[1]: *** [src/CMakeFiles/minetestserver.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by sfan5** [comment]
Known Bug on Ubuntu 12.04.

Either disable LevelDB or somehow install better leveldb packages.

**Comment by Rogier-5** [comment]
@nolsen42 It looks like a linking problem.

You're probably suffering from the c++11 ABI problem (e.g. [1](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html), [2](http://stackoverflow.com/questions/36159238/linking-problems-due-to-symbols-with-abicxx11)). It looks like the snappy library was not compiled in the same way as minetest and leveldb. Recompile snappy, and/or leveldb, and more if needed. Don't use clang for one library, and gcc for another.

**Comment by MoNTE48** [comment]
Have same issue :)
Recompiled leveldb and snappy from source

**Comment by daytonnvpaul** [comment]
My advance appologies for the reopening.

I'm getting the exact errors on compile.

Could you post the proper cmake settings for snappy, leveldb, and minetest (stable-5 branch), as well as the preferred source for both snappy and leveldb, in order to get leveldb support.

OS is Ubuntu 20.04

Thank you.

**Comment by sfan5** [comment]
Works for me, here's what I did in a fresh `Ubuntu 20.04.1 LTS` container:
<pre>
apt install libirrlicht-dev zlib1g-dev cmake make g++ libsqlite3-dev libleveldb-dev libcurl4-gnutls-dev libfreetype-dev libxxf86vm-dev libjpeg-dev libpng-dev libbz2-dev libgl-dev
git clone https://github.com/minetest/minetest --depth=10
cd minetest/
cmake . -DENABLE_SOUND=OFF
nice make -j12
</pre>

The resulting build is a bit minimal but it does include leveldb *and* links correctly.

**Comment by daytonnvpaul** [comment]
@sfan5, I found that 1 other package is required -- libleveldb1d

Thanks for your reply.  Everything is working fine now.
