### ISSUE TITLE
#minetest.object_refs doesnt work

### ISSUE THREAD

**Issue by cdqwertz** [minetest/minetest#4369]
I tried to get the number of object refs using `#minetest.object_refs`, but it always returned 0.
`dump(minetest.object_refs)` works well.

```lua
minetest.chat_send_all(#minetest.object_refs)
```

Minetest : 0.4.14-dev

**Comment by t4im** [comment]
It's a map of object-id to object-reference, so this is indeed correct lua behavior.
```lua
local counter = 0
for _ in pairs(minetest.object_refs) do counter = counter + 1 end
```
Will give you, what you want.

**Comment by SmallJoker** [comment]
The expression `#table_var` returns the *number* of the numberic indices of the table. Make sure you call `minetest.chat_send_all` with a *string* argument to make sure it's sent properly.

**Comment by cdqwertz** [comment]
@SmallJoker that doesnt change anything. I already tried that.
@t4im Thank you! I will try that now.

**Comment by est31** [comment]
So it seems to be fixed then.
