### ISSUE TITLE
Automatic server list fetching delays password input

### ISSUE THREAD

**Issue by everamzah** [minetest/minetest#4371]
I've gotten used to waiting for the server list to (attempt to) load before entering my password.  Sometimes I still forget, and end up connecting with an incorrect password.  The problem is that the delay can be long enough that, by the time you make a selection and attempt to connect, the list has been updated and all text boxes emptied.

I recommend displaying a cached list if it exists, and adding a refresh button.  Fetching the server list automatically if said cache doesn't exist would still be alright, I think.

Apologies if this issue is in duplicate.

**Comment by Wayward1** [comment]
It is indeed a duplicate, of #4200
