### ISSUE TITLE
unusable code in lua_api.txt

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#4373]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2693
The set_animation of objects using mesh is documented in a strange way, `set_animation({x=1,y=1}, frame_speed=15, frame_blend=0, frame_loop=true)` should be `set_animation(pos, frame_speed, frame_blend, frame_loop)` and the params should be described below (their types, their default values, whether they can be omitted).
If you copy-paste the code, minetest crashes because of the "="s inside the round brackets.

**Comment by everamzah** [comment]
That is not example code.

**Comment by paramat** [comment]
Yes this is wrong, please can you submit a PR?

**Comment by everamzah** [comment]
I mean, I don't think it's supposed to be copy/pasted.

Nevertheless, how about:
```
* `set_animation({x=1,y=1}, 15, 0, true)`
  ^ pos, frame_speed, frame_blend, frame_loop
```

**Comment by t4im** [comment]
Aren't those the default values to those fields?

If not, you should keep the field names, not the values.
```lua
set_animation(range, frame_speed, frame_blend, frame_loop)
```
Like the rest of the api does.

But if those are the defaults, i would keep them, they are useful information.

**Comment by HybridDog** [comment]
>Nevertheless, how about: […]

everamzah, it looks fitting, but, as t4im already wrote, information about the default values needs to be given

>But if those are the defaults, i would keep them, they are useful information.

l don't know whether they are default or magic values.

**Comment by paramat** [comment]
There's another at https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2731
Everamzah's suggestion seems good to me.

**Comment by HybridDog** [comment]
ghost's suggestion doesn't work if there are no default values, e.g. the nodename which is passed in minetest.set_node

**Comment by paramat** [comment]
> should be set_animation(pos, frame_speed, frame_blend, frame_loop) and the params should be described below (their types, their default values, whether they can be omitted).

I agree with this and T4im's opinion, keep it consistent with the rest of lua_api.txt.

**Comment by HybridDog** [comment]
#6339

**Comment by paramat** [comment]
#6339 merged.
