### ISSUE TITLE
Any way to know if the server is shutting down?

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#4375]
Is there any way to know if the server is shutting down? 
I want some things to happen before the server shut off.
(minetest.on_shutting_down?)

**Comment by asl97** [comment]
next time, try checking the lua_api.txt or the wiki before asking.
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1907
http://dev.minetest.net/minetest.register_on_shutdown
