### ISSUE TITLE
More fine-tuning regarding minimap permissions

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4378]
Currently, you can disable usage of minimap and radar with `hud_set_flags({minimap=false})`.

However, it is only possible to disable _both_ minimap (surface mode) and radar at once. It's all-or-nothing.

I have a feature request to allow for more fine-tuning regarding this feature. Add the following flags:
- `minimap_surface`: Allows to use surface mode
- `minimap_radar`: Allows to use the radar mode
- `minimap_rotate`: Enables the rotating mode of the minimap (Shift+F7)
- `minimap_static`: Enables the static mode of the minimap

The `minimap` flag should be deprecated and `minimap=bool` should be seen as alias for `minimap_surface=bool, minimap_radar=bool, minimap_rotate=bool, minimap_static=bool`.
By default, all 4 flags are `true`.

To effectively enable the minimap feature at all, the following condition has to be met:

```
(minimap_surface or minimap_radar) and (minimap_rotate or minimap_static)
```

Examples:
1. All 4 flags are true: Same behaviour as `minimap=true`.
2. All 4 flags are false: Same behaviour as `minimap=false`.
3. `minimap_surface=true, minimap_rotate=true, minimap_static=true, minimap_radar=false`: Surface mode is enabled, but not radar.
4. `minimap_surface=false, minimap_rotate=true, minimap_static=true, minimap_radar=true`: Radar is enabled, but not minimap.
5. `minimap_surface=true, minimap_rotate=true, minimap_static=false, minimap_radar=false`: Only surface mode in rotating mode is available.
6. `minimap_surface=true, minimap_rotate=false, minimap_static=false, minimap_radar=false`: Minimap feature is not available at all because the aforementioned condition is not met.

Use cases for mods (not part of the feature request):
- Addding a set of tools which enable various map/radar features when they are in player inventory; by default nothing is enabled (specifically: https://forum.minetest.net/viewtopic.php?f=9&t=15247)
  - For example, carrying an “automapper” might enable the surface mode
  - Carrying a “radar” item might enable the radar
  - By default, only “rotating” mode can be enabled; when carrying a compass item, static mode becomes available as well
- Adding a potion which allows to use the radar temporarily, minimap is disabled otherwise

**Comment by paramat** [comment]
Minimap usage certainly needs development, some here are keen to do that.

**Comment by xunto** [comment]
I'm more interested in adding minimap as texture modifier, not just hardcoded in hud. 

That way we can add it to the hud(with ordinary hud api), wield items, formspecs and etc

**Comment by tacotexmex** [comment]
I'd like a fallback texture on the minimap map area when these conditions are met:
`minimap=true, minimap_surface=false`:
Surface map is gets fallback texture render on it.

The same would go for 
`minimap=true, minimap_radar=false`:
Radar map is gets fallback texture render on it.

Then we could make compass-only mods, mods that condition the use of the minimap while still showing that it exists, and so on. Two ugly examples for surface map texture fallback:
![image](https://cloud.githubusercontent.com/assets/25328789/26406511/c5d03554-4098-11e7-8dbc-85a0c809ecc0.png) ![image](https://cloud.githubusercontent.com/assets/25328789/26406520/c9343c90-4098-11e7-92eb-0b41811a377a.png)

**Comment by paramat** [comment]
I support this.
In a survival game where you have to craft special items to be able to use the minimap the items required are likely to be very different: a drone for surface overview, and a radar for underground.

I'm not so sure about rotating versus static, i can see the reason of needing a compass to be able to know North, but F5 already allows this.

**Comment by Wuzzy2** [comment]
> but F5 already allows this

This is not a valid argument.
I consider using F5 to be cheating (or kinda cheating). The fact that you can see coordinates and yaw **for free** at any time breaks any mod or subgame where the very *point* is that you do *not* automatically know where you are. Mods are unable to disable this. This is not fantasy talk, this is an actual problem for the `orienteering` mod.
And this has been discussed before: https://github.com/minetest/minetest/issues/4556

**Comment by paramat** [comment]
Yeah, we have a priv for wireframe view, maybe there could be one for F5.
You can also tell directions from watching clouds or motion of sun, moon and stars.

**Comment by octacian** [comment]
Wireframe view already requires the `debug` privilege. I for one wouldn't be too against requiring the debug privilege for f5 entirely, but only assuming that more information was added to the f5 menu to make it worthwhile.

Yes, you can tell the direction from your surroundings, but usually, it's far more convenient to just look at f5. Maybe a HUD flag? HUD flags are really underused considering the potential IMO.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/commit/7657fe7a505425e82d9cab7ae5638f7927138fb0 merged, adds HUD flag for radar mode.
I disagree with controls for static / rotating, i can see no reason for needing to control that.

**Comment by Wuzzy2** [comment]
> 7657fe7 merged, adds HUD flag for radar mode. Is this good enough and can we close this?

I am not too happy about this because to enable radar mode, you MUST also enable surface mode. It is not possible to only enable radar mode, but not the surface mode.

> I disagree with controls for static / rotating, i can see no good reason for needing to control that.

With the “square” mode you automatically know the cardinal direction as well and you don't really need a compass anymore.
It's not as much imporant as radar on/off, but would still be nice to have.

**Comment by paramat** [comment]
> to enable radar mode, you MUST also enable surface mode. It is not possible to only enable radar mode, but not the surface mode.

There's a reason, the existing code uses the minmap HUD flag as the master control, it was much simpler to make radar a supoption.
Using radar without surface is not much needed as radar is the special ability that therefore contains the surface ability.

> With the “square” mode you automatically know the cardinal direction

Of course, i see.

**Comment by paramat** [comment]
Cardinal directions can also be known from cloud drift, sun / moon / star motion and texture orientation, so is a non-issue.
The radar HUD flag is added and a MTGame PR is coming for enabling minimap functons.
