### ISSUE TITLE
Add arrow for rotating mode of minimap

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4379]
I find it slightly irritating that there is an arrow for the “static” mode of the minimap but not the rotating mode.

I suggest to add an up-pointing arrow for the rotating mode, for making it a bit less confusing and more consistent.

Because this is probably a controversial change, adding some `minetest.conf` setting for enabling/disabling the arrow can't hurt.

For bonus points, a key mapping for toggling the minimap arrow would be nice (not mapped to any key by default).

**Comment by rubenwardy** [comment]
I'd be satisfied with a hollow cross hair at the very least - I find it difficult to find the center

**Comment by paramat** [comment]
I find the arrow a bit obstructive, needs to be more 'transparent' as in, yes, a hollow/outlined design.

**Comment by SmallJoker** [comment]
Added in #7350
