### ISSUE TITLE
Possible to register crafting recipe with output = "air"

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4383]
In Minetest 0.4.14, it is possible to register a crafting recipe with `air` as output. This seems wrong to me.

Example code:

```
minetest.register_craftitem("craft_bad:dummy", {
	description = "Craft Testing Dummy Item",
	inventory_image = "unknown_item",
	wield_image = "unknown_item",
})
minetest.register_craft({
	recipe = {{"craft_bad:dummy", "craft_bad:dummy", "craft_bad:dummy" }},
	output = "air",
})
```

**Comment by t4im** [comment]
Do you actually get a node out of it?

**Comment by Fixer-007** [comment]
This can be used in space subgames I guess.

**Comment by paramat** [comment]
Certainly it's weird and rather useless to craft and obtain "air", but it's not harmful in any way so checking for this is not needed.
