### ISSUE TITLE
Riverwater source sometimes don't flow

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4384]
In the valleys_c mod riverwater sources are placed in caves, but some of them don't start to flow. 

vm:update_liquids() is executed

On this screenshot are several water sources, some of them are flowing, others don't flow

![bildschirmfoto vom 2016-07-29 21-30-17](https://cloud.githubusercontent.com/assets/16163058/17261133/8dcec918-55d4-11e6-8ff0-99e98c71140f.png)

**Comment by paramat** [comment]
#4065 improved things, and there's #4061 to come.

**Comment by paramat** [comment]
@MarkuBu #4061 has been merged, does it help?

**Comment by paramat** [comment]
@MarkuBu will close soon if bug is not confirmed still present.

**Comment by MarkuBu** [comment]
@paramat I'm sorry. Missed that last post. It seems that it's working now. Issue can be closed
