### ISSUE TITLE
Possible to register crafting recipe with invalid/nonexistant input items

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4385]
Consider this Lua code:

```
minetest.register_craftitem("craft_bad:dummy", {
	description = "Craft Testing Dummy Item",
	inventory_image = "unknown_item",
	wield_image = "unknown_item",
})
minetest.register_craft({
	recipe = {{"craft_bad:nonexistant", "craft_bad:nonexistant"}},
	output = "craft_bad:dummy1",
})
```

The item `craft_bad:nonexistant` does not exist. Yet in Minetest 0.4.14, it is possible to execute this code without getting an error, warning or debug log message slapped in the face.

My own experience shows this is a pretty common mistake by modders which manifests itself in “unknown item” or other weird images in crafting guides, it's quite annoying when this happens.
My guess is the main cause for this kind of bug is that modders are not aware since this kind of mistake; it is rather hard to spot. You basically have to directly search for something like this or you find it by chance.

What Minetest should do:

- When `minetest.register_craft` is called with an item which Minetest does not know yet, it should at least give an error-level debug message.

Of course, this also applies to fuel, shapeless and cooking recipes, what matters is that one of the input items does not exist.

**Comment by rubenwardy** [comment]
There are already nonexistent items in MTG

https://forum.minetest.net/viewtopic.php?id=5831

**Comment by SmallJoker** [comment]
I disagree with that "throw error" behaviour. Yes, unknown items in the crafting recipes are mod bugs. But Minetest should not throw an error there. When the recipe items are checked right when the function was called it would throw an error even if the required items are defined in the code below. This would force mods to register their craft recipes always after defining the nodes which could break so many existing mods.

**Comment by t4im** [comment]
> When minetest.register_craft is called with an item which Minetest does not know yet, it should at least give an error-level debug message.

No, You would error sometimes, when mods register recipes without (soft)dependency on another mod, because of loading order.
If you have two mods recipe with each other, then even a dependencies couldn't prevent one of them logging an error anymore.
@SmallJoker  also ninja'd the other scenario already with the self-registering order.

**Comment by Wuzzy2** [comment]
> There are already nonexistent items in MTG

I see. If it is broken in Minetest Game, then it is acceptable. xD

> This would force mods to register their craft recipes always after defining the nodes which could break many existing mods.

I think forcing mods to register recipes after the items actually makes sense. Why did we ever get mods away with registering crafts *before* the actual items were registered? IMO this is wrong logically and bad design and probably a key reason why this issue arose in the first place.
Maybe we could handle the bugfix in some sort of deprecation period.

> You would error sometimes, when mods register recipes without (soft)dependency on another mod, because of loading order.

Well, then the error is obviously made by the modder who used broken dependencies. We should never encourage broken dependencies.

> If you have two mods recipe with each other, then even a dependencies couldn't prevent one of them logging an error anymore.

Then the recipe has to be registered without making a circular dependency. One possible way would be by registering it in a 3rd mod. Maybe there are other ways.


Whatever, I don't understand your complete rejection of this bug.
The issue is, it is easy to accidentally include an invalid item in the input recipe, but it is hard to spot the bug afterwards. Any better ideas on how to fix this?


Maybe we could just include rubenwardy's script by default, after some optimization, cleanup and stuff.
I really hate the `minetest.after(0)` part of this script, a callback for “after all items/nodes/recipes/whatever have been registered” would be very useful.

**Comment by paramat** [comment]
The objections to this request are valid.
Also, spelling mistakes in recipes are soon found when a modder tests their recipes by crafting. This level of code checking is over-complex and unnecessary.

**Comment by Wuzzy2** [comment]
> Also, spelling mistakes in recipes are soon found when a modder tests their recipes by crafting. This level of code checking is over-complex and unnecessary.

Unless there's a huge number of recipes; are you seriously suggesting to test them all by hand?

**Comment by t4im** [comment]
> are you seriously suggesting to test them all by hand?

If you want to test for these things automatically, adding a test for it to the [smoketests of shakedown](https://github.com/t4im/shakedown#smoketest) could be an option. It's what it is build for after all. It already finds some issues way more serious than this.

**Comment by SmallJoker** [comment]
@Wuzzy2 You don't need to check them by hand. There's already a mod that does that for you - the one rubenwardy menioned above. It works well to find broken recipes.
