### ISSUE TITLE
Make descriptions scrollable (if long enough)

### ISSUE THREAD

**Issue by nolsen42** [minetest/minetest#4389]
I noticed if a description is long enough, it will get cut off in the main menu, because there is no way to scroll and read all of it, this might be something that should be added into the main menu.

**Comment by paramat** [comment]
Long horizontally or vertically?

**Comment by nolsen42** [comment]
@paramat Vertically

**Comment by nolsen42** [comment]
For example, my server description is longer than it appears, so the rest is cut off: https://nolsen.xyz/paste/?374e98845964160d#RlePzfF+jw04pPE+tF8+86Rkqy0Z/wqdvHY8Oz/Keg8=

**Comment by paramat** [comment]
Descriptions should be short. However, a scrollable box might be present in the formspec API.
It's Lua in builtin so easy to modify https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1377

**Comment by raymoo** [comment]
There are no scrollable box elements other than the editable textarea and the textlist, but the second would require breaking up the text into lines when it would wrap around (would either require a fixed column number or somehow determining how to expand based on GUI settings).

I think tables can have scroll bars too, but you would have a similar issue as with textlists.

**Comment by paramat** [comment]
So i think we can't do anything about this, apart from making the text box larger, but i think an effort should be made to make descriptions shorter to fit.

**Comment by SmallJoker** [comment]
I think it's the server owner's problem to keep the description short. It's possible to specify a website - a place where further information can be found if required.

**Comment by paramat** [comment]
Agreed. There's not enough need to expand description boxes, so closing.

**Comment by raymoo** [comment]
Actually mod info is in a scrollable textlist for me, am I looking at the wrong thing?

**Comment by tobyplowy** [comment]
@paramat I think a scroll function for descriptions would be really awesome

**Comment by SmallJoker** [comment]
@raymoo It is actually only a list like it's used to display the installed mods and texture packs.
But the description uses the undocumented function `core.splittext` to make a line wrap after X characters. This means it does not look for the box width or font size. However, it works but not well in all cases (big font size or a small GUI scaling factor).

**Comment by raymoo** [comment]
@SmallJoker I did say it was a textlist. When I read this issue I thought it meant that there was no scrolling description at all.

**Comment by Wuzzy2** [comment]
This issue is definitely solvable IMO. It's just not reasonably solvable with the current formspec API.

The solution would be to first fix https://github.com/minetest/minetest/issues/3807, then fixing this issue should be a piece of cake.

**Comment by DS-Minetest** [comment]
A bit related: #5355

**Comment by ExeterDad** [comment]
That box handles much more than server description. When a player is kicked, banned or when the sever shuts down, the message is displayed. Most often unreadable.
I do hope we find a way to have a scroll box there and not attempt to resolve by mere shorter server descriptions.

**Comment by ThomasMonroe314** [comment]
@paramat @nolsen42 @SmallJoker This has been implemented.
![screenshot](https://user-images.githubusercontent.com/26969467/35278221-3c0e0f12-0041-11e8-92e5-fe6e7160352b.png)

**Comment by paramat** [comment]
Seems so.
