### ISSUE TITLE
Settings / .conf: Mgv5 ground noise unsettable / missing

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4390]
Mgv5 ground noise cannot yet be set in the settings menu due to unsupported noise flags, and is therefore missing from conf.example when it is auto-generated, despite it being settable in conf using a table form:

```
mgv5_np_ground = {
    offset      = 0,
    scale       = 40,
    spread      = (80, 80, 80),
    seed        = 983240,
    octaves     = 4,
    persistence = 0.55,
    lacunarity  = 2.0,
    flags       = "eased"
}
```

Noise flags need support in the settings menu.

**Comment by paramat** [comment]
Two more issues ..

A problem with .conf auto-generation is that here is now the temptation to not update .conf in PRs, but this would result in .conf being out of date almost all of the time, when it is essential for it to always be up to date. Auto-generation is done rarely and would be excessive work if done for each PR.

I suggest making sure that .conf is always updated in PRs despite the auto-generation feature.

Another problem with .conf auto-generation is that it's content is now completely defined by the advanced settings menu. .conf used to have useful information about the table format for noise parameters:
```
#    Perlin noise attributes for different map generation parameters.
#    Noise parameters can be specified as a set of positional values:
#    Offset, scale, (spread factors), seed offset, number of octaves, persistence, lacunarity.
#mgv6_np_terrain_base = -4, 20, (250, 250, 250), 82341, 5, 0.6, 2.0
#    Or the new group format can be used instead, for example:
#mgv6_np_terrain_base = {
#    offset      = -4
#    scale       = 20
#    spread      = (250, 250, 250)
#    seed        = 82341
#    octaves     = 5
#    persistence = 0.6
#    lacunarity  = 2.0
#    flags       = "defaults"
#}
#    Only the group format supports noise flags which are needed for eased noise.
#    Mgv5 uses eased noise for np_ground so this is shown in group format,
# other noise parameters are shown in positional format to save space.
```
Now this has been erased due to auto-generation.
This information is unlikely to be present even if the advanced settings menu supports all noise parameters. But this information is essential to show how to use the table format in .conf, so that  users can use noise flags for any noise parmater in any mapgen.

I suggest that for now we no longer auto-generate .conf and re-add this information. The first issue above means that auto-generation is almost redundant anyway.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/4518#issuecomment-247214458 the noise format that has been lost is needed in minetest.conf.

**Comment by paramat** [comment]
I suggest this PR:
Add a note at the end of builtin/mainmenu/dlg_settings_advanced.lua to warn against updating conf.example with an auto-generated version.
In conf.example re-add the format example for noise group format, re-add mgv5 ground noise in group format.

**Comment by paramat** [comment]
#4545 merged.

**Comment by paramat** [comment]
@PilzAdam before you disappear please could you make the advanced settings menu support noise parameters in group format?

**Comment by paramat** [comment]
A new file minetest.conf.example.extr has been added to contain the text that is not autogenerated from settingtypes.txt https://github.com/minetest/minetest/blob/master/minetest.conf.example.extra

**Comment by srifqi** [comment]
So, this basically noise setting with flags?

**Comment by srifqi** [comment]
So, this is basically noise settings with flags?

**Comment by paramat** [comment]
Yes, docs are here https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L997
It needs to accept no flags set, an empty string.
Extra information from hmmmm:

<hmmmm> leave flags blank for noise just like you're used to, eased/non-eased is determined by the type of noise it's being used for
<hmmmm> 2d noise uses eased by default
<hmmmm> 3d noise uses non-eased by default
<hmmmm> this is needed for backwards compatibility
<hmmmm> if you want to do something a little different though... you need to specify the flags field
<hmmmm> 2d noise with the "eased" flag does nothing really because it's already eased by default
<paramat> 2d noise has always been eased then?
<hmmmm> yup
<hmmmm> if you specify "noeased" though, or just have the flags field present without "eased" present, it'll disable easing on 2d noise
<hmmmm> if you specify "eased" on 3d noise, it'll ease your 3d noise
<hmmmm> if you specify "noeased" on 3d noise or leave nothing at all, it'll be regular 3d noise
<hmmmm> let's say you want absolute noise but you don't want to specify eased or not eased
<hmmmm> you'd specify defaults instead
<hmmmm> flags = "defaults, absvalue" would make the noise eased or not eased based on if it's being used for 2d or 3d noise
<hmmmm> by the way, you understand the flags specifier format, right?
<hmmmm> there's the comma-delimited string format, and then there's the table format
<hmmmm> "flag1, flag2" sets flag 1 and flag 2
<hmmmm> "noflag1, flag2" specifically unsets flag1 in case it's set by default, and sets flag2
<hmmmm> flags = { flag1 = true, flag2 = true } in table format
<hmmmm> or...
<hmmmm> flags = { flag1 = false, flag2 = true }  which is equivalent to flags = { noflag1 = true, flag2 = true }

**Comment by srifqi** [comment]
Seems like Minetest Lua API cannot get a group-type setting.
```lua
local varr = core.settings:get("mgv5_np_ground")
print(" --- type: ", type(varr))
print(dump(varr))
```
debug.txt:
```
2017-09-09 19:51:13: ERROR[Main]: Setting [mgv5_np_ground] is a group.
```

**Comment by paramat** [comment]
Isn't there a special settings:get for noise params?

**Comment by srifqi** [comment]
It was unimplemented in Minetest Lua Modding API.

**Comment by paramat** [comment]
minetest.get_mapgen_setting_noiseparams(name)
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2647
minetest.get_noiseparams(name) (might be deprecated)
?

**Comment by paramat** [comment]
More information, from https://github.com/minetest/minetest/blob/master/minetest.conf.example.extra
```
#    Noise parameters can be specified as a set of positional values, for example:
#
#    Offset, scale, (x, y, z spread factors), seed offset, octaves, persistence, lacunarity
# mgv6_np_terrain_base = -4, 20, (250, 250, 250), 82341, 5, 0.6, 2.0
#
#    Or the group format can be used instead, for example:
#
# mgv6_np_terrain_base = {
#    offset      = -4,
#    scale       = 20,
#    spread      = (250, 250, 250),
#    seed        = 82341,
#    octaves     = 5,
#    persistence = 0.6,
#    lacunarity  = 2.0,
#    flags       = "defaults"
# }
#
#    The advanced settings menu does not yet support the group format.
#    Only the group format supports noise flags which are needed for eased noise.
```

**Comment by paramat** [comment]
PR #6399

**Comment by paramat** [comment]
#6399 merged.

Next i will regenerate minetest.conf and delete minetest.conf.example.extra.

**Comment by paramat** [comment]
#6554 merged.
