### ISSUE TITLE
Toggling Camera Update is no longer works?

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4392]
In-game, i tried to toggle camera update off, its useful for stopping loading chunks (F4), because its easy find perfect chunk. Now it's not working in Minetest version 0.4.14. Did removed for some reason?

**Comment by rubenwardy** [comment]
It was removed from the key binding as it's confusing to players if they accidentally tap it.
You can readd it using:

    keymap_toggle_update_camera = KEY_F4

**Comment by WSDguy2014** [comment]
@rubenwardy, thanks for the information.
