### ISSUE TITLE
Players helplessly stuck at 0,0,0 for minutes (spawn bug)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4403]
Some players reported to "Red Cat Creative" admin that they spawn at 0,0,0 for 10 minutes without any way to get out.

I have similar problem on "VanessaE's creative-building server", where you spawn in 0,0,0 and no commands are accepted from player (including /status), I do get network packets received, I can walk and chunks load. After waiting some long minutes I get spawned in proper place.

Servers use mt 0.4.14. This very annoying bug encountered on real servers, please react.
sfan5 did some testing of this bug on several servers, results are here: http://irc.minetest.net/minetest-dev/2016-11-25

**Comment by VanessaE** [comment]
I can confirm this on servers other than the aforementioned "creative building" one, hence all of my servers have a "secondary" building housing the 0,0,0 point, with instructions to help get players out who get stuck.

The length of time to get moved to the proper spawnpoint varies; some players have indicated being stuck for minutes at a time.

**Comment by Ezhh** [comment]
Just to add details - issue has only been present on Red Cat since switching to 0.4.14. No issues were ever reported prior to this, though I have experienced the issues myself on other servers, both 0.4.14 and 0.4.13.

**Comment by paramat** [comment]
Related #2524 #3083
Please can you make clear the use of static spawnpoint in this?

**Comment by VanessaE** [comment]
static_spawnpoint is in use on my servers, as well as a mod that moves the player to another location depending on "interact" privilege.  I assume most server owners are using a similar mod by now.

**Comment by Fixer-007** [comment]
To start actually playing you need to wait:
1) 14 minutes on Red Cat creative (I've also noticed big wait time for N minutes to confirm my password changes)
2) 2 minutes (or longer if first time) on Vanessas creative-building server

This is insane bug :(

**Comment by Fixer-007** [comment]
More my observations of this annoying bug on Red Cat:
+ after my login blocks load normally in all places (receiving net packets)
+ starting at 0,0,0
+ can't see any chat, but other people can read me
+ no commands working
+ can't fly or fast even when I have those privs on server
+ no formspecs
+ no text on kaeza/vanessas signs
+ very big wait before successful password change
+ server restart "solves" this problem, but it becomes progressively worse with time in matter of hours

**Comment by tenplus1** [comment]
Confirmed on standalone server tests also, run server, sign it with 2 players, sign out, sign in again and at times you respawn at 0,0,0 instead of where you last left off.

**Comment by red-001** [comment]
Could this be caused by `TOSERVER_CLIENT_READY` not being received by the server?

**Comment by Fixer-007** [comment]
This bug is different from those mentioned just above ^^

**Comment by garywhite207** [comment]
I have seen this on VE-Building & VE-Creative, Xanadu, and Red Cat Creative in the year I've been in the Minetest community. Could it be possibly lag from a combination of slow internet connection and/or high ping times? I have 100 Mbps internet and I get it too, but not as much, so I wonder if it's ping with server lag personally.

Paramat: Please make this of some priority cause there are several players that have also complained about the issue, and it seems to be getting worse.

**Comment by Zeno-** [comment]
On Red Cat Creative this bug affects me for 100% of logins

**Comment by Wayward1** [comment]
I too experience it each time on Red Cat Creative, as well as VE-Building and TPS-Lego. Interestingly, as Fixer noted, it's always longest by far on Red Cat.

**Comment by Ezhh** [comment]
I get it longest on Xanadu, then TPS-Lego... Many other servers give me it for just a couple of seconds, but these are the two where I have really felt it. Can't get it on Red Cat Creative no matter what I do. 

(Just as a note to those of you testing at the moment, Red Cat has been very busy (#1 in public list currently) which always seems to make it worse, and server has been running for quite a while without a restart, which also definitely makes it worse.)

**Comment by tenplus1** [comment]
Xanadu experiences this glitch as well, players have a 0,0,0 holding area with a sign asking them to be patient until game moves them to start location.

**Comment by Wuzzy2** [comment]
@sfan5: Are you sure this issue is fixed by #4812? That PR doesn't look like it has anything to do with spawning. Can you please check again? I think you may have confused some numbers here.

**Comment by sfan5** [comment]
@Wuzzy2 you're the second person to ask whether i've confused any numbers, the answer is: **no**, the referenced PR definitely does fix this issue

**Comment by paramat** [comment]
See IRC logs for the discussion.
