### ISSUE TITLE
Owned Punches

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4405]
Right now, the only sense of "attacking" in Minetest is the punch. This is adequate for melee attacks, but not projectile attacks, since projectiles will have themselves as a puncher. Mobs won't know who to be aggressive against if attacked with a projectile that uses itself as the puncher, and the server won't know who attacked who when projectiles are used, in case it wants to bestow rewards or penalties upon the attacker.

Here are some non-solutions:
- Have the projectile punch using the owner's ObjectRef: If it's a player, they might have logged off in the meantime. Also, you may want to distinguish the projectile from the owner since there might be effects specific to meleeing, such as contact damage.
- Have mob mods themselves implement an attack method: Mob mods can't be expected to all have the same interface, so modders would have to know about every interface and implement them all, making any they missed not work.

I think the punch method of ObjectRefs should have an optional owner argument, which can be an ObjectRef or a string (for player names). These should get passed in entities' on_punch callbacks and in register_on_punchplayer callbacks.

**Comment by t4im** [comment]
The technic mod solved this by spawning the projectile as a particle and dig/punch its target directly.
It's less affected by lag as well, but only works for very fast projectiles.

> If it's a player, they might have logged off in the meantime.
> ... distinguish the projectile from the owner

From the API:
> `puncher`: an `ObjectRef` (can be `nil`)
> `is_player()`: returns true for players, false otherwise

I think some projectiles might already do that. #3280

Of course it would be cleaner if you could walk along an object-chain, but besides item's setting a `dropped_by` when dropped, there does not seem to be a standard yet.

Adding a generic `spawned_by` might be useful for other situations as well.

**Comment by rubenwardy** [comment]
This can and should be done by having a property in the Lua entities' Lua table being he player name
