### ISSUE TITLE
Minetest gravity 

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#4406]
Minetest gravity is ~= 9.8 , after testing i think MT gravity should be 10 by default , i think 10 is the sweet spot.
thanks

**Comment by SmallJoker** [comment]
> Effective gravity on the Earth's surface varies by around 0.7%, from 9.7639 m/s² on the Nevado Huascarán mountain in Peru to 9.8337 m/s²
Source: [Wikipedia](https://en.wikipedia.org/wiki/Gravity_of_Earth#Variation_in_gravity_and_apparent_gravity)

Earth's gravity is defined as 9.81 m/s², same in Minetest.

**Comment by est31** [comment]
As @SmallJoker says, earth's gravity varies, and the usual value you use in calculations is 9.81. The default is fine, and the actual value in the game can be [modified by mods](http://rubenwardy.com/minetest_modding_book/lua_api.html#gravity) if they want to customize it.
