### ISSUE TITLE
Error in callback item_onUse(): C++ exception

### ISSUE THREAD

**Issue by Nosrick** [minetest/minetest#4411]
I'm not sure if this should go in minetest, or minetest_game, but here it is;
I've created an item that summons up a creature, but when the item is pointed at a living creature, the game crashes with the above error.

Here's a link to my repo:
https://github.com/Nosrick/MoMTest

It requires the Simple Mobs mod by PilzAdam (https://forum.minetest.net/viewtopic.php?t=3063), and it requires it to simply be called "mobs".

If you pull my repo, look for the "GUARDIAN_SPIRIT_CRASH" tag.

**Comment by Rogier-5** [comment]
Could you provide more details ? As many and as specific as possible ?

Is the text in the title the only message ? or does minetest print some more info ? A lua stack traceback for instance ? (check the file debug.txt _and_ the terminal / console from where minetest was started).

Could you also be more specific about exactly where in the code the error happens ? You are linking to an entire repositiory, and leave it up to the reader to find the 'GUARDIAN_SPIRIT_CRASH' needle in the haystack...

Maybe you could also incude the relevant sections of code ? If you haven't already done so (I had a quick look, but didn't find the tag), try experimenting to narrow it down to some specific code. For instance, using print() or minetest.log() in the lua code to determine where exactly the crash happens, and what the values are of different variables at that point.

**Comment by Nosrick** [comment]
Sorry, I am kind of dumb and bad at error reporting.

Okay, so let's address your points one at a time:
The text is as follows: "Lua: Runtime error from mod 'momtest' in callback item_OnUse(): C++ exception".
That's literally it. Nothing else in the console or debug log.

The error happens in src/items/books/life/guardianSpiritBook.lua, in the on_use function, I think.

I can't get the code to format properly, sorry. However, I did push the GUARDIAN_SPIRIT_CRASH tag, because I'm a doofus and forgot to last time. :)

**Comment by tenplus1** [comment]
Your code is flawed, use this command to get position:

http://dev.minetest.net/minetest.get_pointed_thing_position

**Comment by Rogier-5** [comment]
> Your code is flawed

@tenplus1: That doen't explain the 'C++ exception', does it ?

I get the following error when hitting an object (item):
```
ServerError: Lua: Runtime error from mod 'momtest' in callback item_OnUse(): Invalid position (expected table got nil).
```

**Comment by sapier** [comment]
fix merged
