### ISSUE TITLE
Fast privilege can inhibit antcheater?

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#4414]
I want to allow players to run on my server, but I believe that this can open a security hole. Maybe I'm wrong and anticheater works normally.

**Comment by paramat** [comment]
Remember 'fast' mode is not 'running' because it's 20m/s (45mph), it's an admin / creative -type superpower like fly or teleport.

**Comment by SmallJoker** [comment]
#4303 will fix this.

**Comment by paramat** [comment]
Sorry i closed this. For a 'sprint' mode physics override should be used for something fairly realistic (and #4303 will fix the issue for that).
'fast' priviledge triggering anticheat is expected and desired behaviour.

**Comment by BrunoMine** [comment]
This seems to solve my problem. I hope soon to be added to the game play. Thank you.

**Comment by everamzah** [comment]
>'fast' priviledge triggering anticheat is expected and desired behaviour.

It's the *lack* of fast privilege that results in anticheat being triggered with physics override greater than movement_speed_fast.

**Comment by paramat** [comment]
I misunderstood this,

**Comment by C1ffisme** [comment]
> Remember 'fast' mode is not 'running' because it's 20m/s (45mph), it's an admin / creative -type superpower like fly or teleport.

Which makes sense, except that a day in Minetest is 72 times faster than a real life day (according to the [Minetest Wiki](http://wiki.minetest.net/Minetest.conf).) Which means that we're walking about 72 times slower than we should be in Minetest.

**Comment by paramat** [comment]
> 'fast' priviledge triggering anticheat is expected and desired behaviour.

I was wrong here too.

**Comment by HybridDog** [comment]
paramat, it's called privilege, the d is a typo from the unified inventory mod
