### ISSUE TITLE
check several items simultaneously

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#4415]
It is possible to check whether it is possible to add a list of items simultaneously in the inventory of a player?

**Comment by stujones11** [comment]
Questions should be posted on IRC or the minetest forums but you can use `InvRef:room_for_item`

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2816

**Comment by BrunoMine** [comment]
Nobody can answer that question in the forum.
`InvRef:room_for_item`
This method does not work for more than one type of item. I can check 99 irt or 99 stones, but can not check 99 dirt and 99 stones simultaneously.

**Comment by paramat** [comment]
Please ask questions on the forum or on IRC.

**Comment by asl97** [comment]
@BrunoMine I don't think it's currently possible.
____
@paramat 
Even though this is a question, it could even be interpreted as an feature request, something like new method for inv:
```lua
room_for_inv("listname", inv)
add_inv("listname", inv) or merge_inv("listname", inv)
```
Use cases:
* inv dumping (eg:  bone mod maybe)
* times where you want something to be able to add all the items without dumping object into the world or not used at all. eg: gift box item

Although, I don't think it be worth it since I doubt people require merging Inv that often for it to be a performance problem.

**Comment by rubenwardy** [comment]
untested:

```lua
local function room_for_items(inv, list, stacks)
	local items = {}
	for i = 1, #stacks do
		local stack = ItemStack(stacks[i])
		local iname = stack:get_name()
		local count = stack:get_count()
		items[iname] = items[iname] and (items[iname] + count) or count
	end

	local taken = {}
	for itemname, count in pairs(items) do
		local itemdef = minetest.registered_items[itemname]
		local stack_max = itemdef and itemdef.stack_max or 99
		local pointer = 1
		while pointer <= inv:get_size(list) and count > 0 do
			local stack = inv:get_stack(list, pointer)
			if stack:get_name() == itemname then
				-- Stacks max, fill up spare place
				local take = stack_max - stack:get_count()
				-- stack:get_count could be bigger than stack_max
				if take > 0 then
					count -= 
				end
				
			elseif stack:is_empty() and not taken[pointer] then
				-- Allocate empty slot to this item
				taken[pointer] = true
				count -= stack_max
			end
			pointer = pointer + 1
		end
		if count > 0 then
			return false
		end
	end
	return true
end
```

`stacks` can be a list or ItemStacks or item strings.

```lua
room_for_items(inv, "main", {"default:dirt 99", "default:stone 99"})
```

or

```lua
inv.room_for_items = room_for_items
inv:room_for_items("main", {"default:dirt 99", "default:stone 99"})
```

**Comment by paramat** [comment]
Good point, is this a feature request?

**Comment by paramat** [comment]
'room_for_item' is usually used for a single item and items added seperately, and it's easy to just use that multiple times, so i can't see much need for this.

**Comment by paramat** [comment]
Sorry for the close.

**Comment by BrunoMine** [comment]
I want to use this to add several items to the inventory simultaneously. If the inventory Player support only one item and I want to add more, some items will be lost. That's too bad for some adventures which I am working on my server.

**Comment by rubenwardy** [comment]
You could drop the item next to the player if there's no room

**Comment by BrunoMine** [comment]
This is a good solution. But if the player does not pay attention, you can have a valuable item behind.

**Comment by asl97** [comment]
I was thinking about a `C` implementation and speed when I said "I don't think it be worth it".
A `lua` implementation for usability wouldn't be bad idea.

**Comment by paramat** [comment]
I agree with a close, seems low priority and a lua workaround is possible.
