### ISSUE TITLE
Inventory callbacks that also run on non-player additions and deletions

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4419]
It would be nice to let inventories have `on_add` and `on_remove` callbacks that run for the inventory methods `add_item` and `remove_item`. It would be hard to get these callbacks to work with `set_list`, so they could just be not run in that case.

EDIT: Maybe also an `on_set_list` that receives the old and new inventory lists? The information may be difficult to work with, but sometimes all that's needed is notification that the inventory changed.

**Comment by raymoo** [comment]
Related discussion in minetest/minetest_game#1229

**Comment by rubenwardy** [comment]
This is also needed for player inventories now that we have callbacks for those

**Comment by SmallJoker** [comment]
Closing in favour of newer #8390
