### ISSUE TITLE
Allow vilocity for players

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4422]
Hi there, in my case i wanted to add a drunken effect to the game but it seems impossible since players dont have a vilocity as i heard from @Calinou in the irc.

Maybe there is some hope to make this possible somewhen?

Regards :)

**Comment by raymoo** [comment]
Duplicate of #2960 I think

**Comment by paramat** [comment]
I think best the discussion continues in #2960 as this is a near-duplicate.
