### ISSUE TITLE
Null pointer exception (I think)

### ISSUE THREAD

**Issue by Nosrick** [minetest/minetest#4423]
I'm not entirely sure where the problem lies, but it's somewhere in api.lua, under momtest.on_punch(), between lines 12 and 16.

Have the gist:
https://gist.github.com/Nosrick/5ba6bc81445f80eaaf3665bb354e4b2b

If you need more code, just say so.

EDIT for more information: I took out all the callback registrations, and it still crashes in exactly the same place.

EDIT 2: I've isolated it to line 16, I think. It's happening somewhere in the set_hp() function.

**Comment by raymoo** [comment]
What triggers the crash?

**Comment by Nosrick** [comment]
Punching an entity which uses my on_punch.

**Comment by Rogier-5** [comment]
What messages are printed when minetest crashes ?

**Comment by Nosrick** [comment]
Nothing. It's a hard crash, a "Not responding" kind of crash.

**Comment by Rogier-5** [comment]
> Nothing. It's a hard crash, a "Not responding" kind of crash.

Then how do you conclude it is a null pointer exception ?

Do you mean that minetest keeps running, but does nothing ?
Does it consume a lot of CPU in the process ? Then it may be some kind of endless loop...

**Comment by SmallJoker** [comment]
Could you please try if
```lua
target.object:set_hp(math.floor(math.max(0.0, target.object:get_hp() - damage) + 0.5))
```
causes the same crash?

**Comment by Nosrick** [comment]
> Then how do you conclude it is a null pointer exception ?
Ah, sorry. Should have included this info when I opened the issue:
I debugged it in Visual Studio, and all the information I got was that it had an error reading location 0xlotsOfZeroes.

> target.object:set_hp(math.floor(math.max(0.0, target.object:get_hp() - damage) + 0.5))
Still the same crash.

**Comment by Rogier-5** [comment]
BTW: note that the parameters of your `on_punch` are not in the same order as the [documented](http://dev.minetest.net/LuaEntitySAO#Lua_Entity_Properties) parameters of the on_punch callback. I don't know if this is intentional, and if they are supposed to be ?

Also note that in the `on_punch` callback, `tool_capabilities` _can_ be `nil`. I don't know if the circumstances that it is `nil` can happen in your code ?

**Comment by Nosrick** [comment]
Yeah, it's intentional.
And I'm not sure; I will add a nil check, and see if that sorts it.

**Comment by Rogier-5** [comment]
>> Then how do you conclude it is a null pointer exception ?

>Ah, sorry. Should have included this info when I opened the issue:
I debugged it in Visual Studio, and all the information I got was that it had an error reading location 0xlotsOfZeroes.

I have no experience using VS, but that sounds like a null pointer exception indeed.

If you haven't done so already, you could add some temporary `minetest.log()` statements in the lua code, to see the exact value of the argument to `set_hp()`.

Can you get VS to produce a stack trace ?

**Comment by Nosrick** [comment]
I managed to get VS to produce a stack trace, as well as a disassembly. Here's the gist:
https://gist.github.com/Nosrick/732c30a4e180bc3381d9febb5aeee2c5

**Comment by Nosrick** [comment]
Sorry for the double post, but I've narrowed it down to the target.object:get_hp() call. I took that out and it works just fine.

**Comment by raymoo** [comment]
Unrelated, but you shouldn't be calling momtest.on_punch if onPunch is defined.

**Comment by Nosrick** [comment]
Why not? I should point out that momtest.on_punch only deals with bonus damage/effect callbacks.

**Comment by raymoo** [comment]
Normally when you override entity on_punch, it disables normal punch handling.

**Comment by Nosrick** [comment]
Ah, I see. Well, it uses the mobs mod on_punch function by default, so it already overrides normal punch handling.

**Comment by raymoo** [comment]
momtest.on_punch does?

**Comment by Nosrick** [comment]
(Continued in IRC)

**Comment by Nosrick** [comment]
I might have narrowed it down. Trying to retrieve toolCapabilities.full_punch_interval in the momtest.on_punch function when the player is being attacked causes the crash.

**Comment by Rogier-5** [comment]
And `toolCapabilities` is not `nil` ? Or maybe `toolCapabilities.full_punch_interval` is `nil` or zero ?

**Comment by Nosrick** [comment]
It turned out that the _self_ reference being passed in wasn't a LuaEntitySAO for players, it was a Player (obviously) and I was trying to access a player's .object, which was causing a crash. (Or something very similar to this, can't remember the exact situation)

However, it'd be nice to have been told that, rather than just getting a hard crash.

**Comment by nerzhul** [comment]
Closing this issue as it's related to player implementation
