### ISSUE TITLE
APNG support

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#4426]
Please add support for APNG. It stores per-frame timings in the .png file and can also do delta compression. It also has a fallback for APNG-unaware code where it just uses the first frame (read the [APNG spec](https://wiki.mozilla.org/APNG_Specification)). That is, if for some reason you want to remove APNG support later on, you can safely do it.

Note that the server doesn't have to be aware of this change.

**Comment by asl97** [comment]
Wait wat....  If you are talking about this animation [format](https://github.com/minetest/minetest_game/blob/f86ac2fdffba76621935e2ea62038107f5269daf/mods/default/textures/default_furnace_front_active.png), I believe it is widely known as Spritesheet Animation (and when was it even proprietary?).

Anyone can easily create it in pretty much any image editor,  removing it and replacing it with APNG would be (IMO) a pretty stupid move.

How would one even create an APNG anyway?

**Comment by rubenwardy** [comment]
1. it's not proprietary
2. it's not unique to minetest

**Comment by SoniEx2** [comment]
> How would one even create an APNG anyway?

With an image editor.

> 1. it's not proprietary
> 2. it's not unique to minetest

1. it's not standard
2. it requires Lua and the minetest module to specify timings

**Comment by asl97** [comment]
@SoniEx2 I sure would like to see someone try to create one using an basic image editor like mspaint
____
1. it's basically just a set of image with a set width and height stack together.
2. it's Spritesheet Animation
3. APNG would made reviewing animation troublesome.

**Comment by SoniEx2** [comment]
3\. tell github to add support for it.

**Comment by asl97** [comment]
3. I wasn't talking about github, I was talking about the PNG Group,  all available implementation are unofficial.

> The PNG group officially rejected APNG as an official extension on April 20, 2007.     https://sourceforge.net/p/png-mng/mailman/message/131482/

**Comment by SoniEx2** [comment]
Yes, don't care, that just means it's not standard. It has a fully functional spec which is better than what we have.

**Comment by SoniEx2** [comment]
Also about that basic image editor thing: Basic image editors can't edit lua files. (or text files, for that matter.)

**Comment by asl97** [comment]
afaik, nether can advance image editors,  your argument is invalid.

**Comment by Calinou** [comment]
I suggest that instead, animation timings are customizable by texture packs, eg. using text definition files. For example, it would be possible to have `default_furnace_front_active.txt` in texture packs, containing the animation duration in seconds that would override the server-defined one (that is defined in Lua).

**Comment by SoniEx2** [comment]
@asl97 At least advanced image editors can do APNG.

**Comment by paramat** [comment]
:-1:

**Comment by asl97** [comment]
@SoniEx2 the point is not requiring advanced image editors.

**Comment by est31** [comment]
:-1: While I think using a more standard image format is a good idea, FLIF (once its standardized) seems a better candidate for this than APNG, which is non-standard.

**Comment by SoniEx2** [comment]
Well how am I gonna promote APNG then? >.>

**Comment by sfan5** [comment]
@est31 
>FLIF (once its standardized) seems a better candidate for this

Have fun waiting 20 years for FLIF to be standardized and to gain adoption.

**Comment by paramat** [comment]
Tmings should not be specified in the image format, those are specified in mods.
The whole point is easy image editing in Gimp or some basic image editor.

**Comment by SoniEx2** [comment]
@paramat Current issues:

- Texture packs can't add animation frames
- Texture packs can't change animation speed
- The compression is shit
- Etc

Also Gimp supports APNG just fine.

**Comment by Calinou** [comment]
> Texture packs can't add animation frames

You can choose the number of animation frames however you want (more or less than the original, it's not an issue).

> Texture packs can't change animation speed

This is an actual issue, see what I proposed.

> The compression is shit

It's lossless, but you should use [OptiPNG](http://optipng.sourceforge.net/) for smaller file sizes. If this is not enough, you can use JPEG.

**Comment by SoniEx2** [comment]
The compression doesn't have any inter-frame compression. Not even minimal inter-frame compression like APNG. (With APNG, the next frame only needs to be as big as the area changed, which can save a lot of space)

**Comment by SoniEx2** [comment]
Also wait, minetest doesn't support per-frame animation speeds?

**Comment by paramat** [comment]
Discussion http://irc.minetest.ru/minetest-dev/2016-08-12#i_4677596

> Please remove minetest's yet-another-proprietary-animation-format

It'll help you to remove this part of the request, obviously we cannot remove the current format.

**Comment by paramat** [comment]
-1 from nerzhul http://irc.minetest.net/minetest-dev/2017-03-21#i_4836610
Author was annoying on IRC and is a known troublemaker.
