### ISSUE TITLE
Sometimes, autokick doesn't work for the servers, if it gets error.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4433]
I was playing Minetest version 0.4.14 at "1248's regnum server", i was mining stones, but then, i see RTT changed 0.141 to -1.000 and it's not kicked me automaticaly out from this server. It's hard to reproduce this bug.

https://www.youtube.com/watch?v=9Q4bDGHXQDw      Note: i hate annoying logo for the url. that blocks view. Because, i'm not registered in Bandicam.

**Comment by SmallJoker** [comment]
># The dollar sign is reserved as placeholder to insert non-translated text

https://github.com/SmallJoker/simple_protection/blob/master/locale/template.txt#L1

**Comment by SmallJoker** [comment]
Why should a bug in the RTT calculation kick you from the server?

**Comment by WSDguy2014** [comment]
@SmallJoker, yeah. Because, if it reach -1.000, will kicked me to the main menu.

**Comment by paramat** [comment]
@WSDguy2014 Still happening in 0.4.15?

**Comment by Fixer-007** [comment]
I seen this on Just Test 2 too.

**Comment by paramat** [comment]
The above is unclear. Does the 'autokick' mod monitor RTT using 'get player information' and kick at -1? Is -1 a valid value?

Is this issue perhaps affected by the recent RTT fix, related to 'get player information' returning 'nil'? If so, perhaps this should be closed?
