### ISSUE TITLE
SE4 swh pulseaudio plugin crashes occasionally when joining a minetest world

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#4434]
I noticed that the stereo expander with variable envelope follower for RMS / peak behaviour. Based on the code for SC1. pulseaudio plugin does not always work with minetest.
http://plugin.org.uk/ladspa-swh/docs/ladspa-swh.html#tth_sEc2.93
how to reproduce: Install pulseaudio and swh-plugins and then run this command to enable the filter with the configuration l use:
```
$ pacmd load-module module-ladspa-sink sink_name=myplug plugin=se4_1883 label=se4 control=0,15,401,-30,20,3.25,0; pacmd set-default-sink myplug
```
In my experience the plugin only disappears/crashes if l join a world in minetest, I didn't get problems with other applications.

**Comment by Fixer-007** [comment]
Why you closed this? Reason?
