### ISSUE TITLE
Longer texture pack descriptions (scrollable)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4435]
The texture pack description box is cut off And a bit too short (it does not go to the bottom of the gui) it should be extended, that's really it.

**Comment by SmallJoker** [comment]
There is almost no space left. We could either make the whole tab bigger or move the screenshot a bit up to free space for two more lines.
But it also depends on your font and font size how many lines of text there can be.

**Comment by tobyplowy** [comment]
@SmallJoker i use the standard font bundled with Minetest (and two more lines would be amazing I would like more but two lines are already the small improvement I guess) now my credits can fit in my description :D

**Comment by ShadowNinja** [comment]
A scroll box should be used so that the description length doesn't matter.

**Comment by tobyplowy** [comment]
@ShadowNinja yeah actually it should. thank you for pointing that out :D

**Comment by Wuzzy2** [comment]
Using automatic line breaks would fix this issue.
If we had a widget for adding scrollable read-only text, this issue could be fixed easily (I guess). But sadly, no such widget exists apart from hackig together a textlist or table (both require manual line breaks).
See also:
https://github.com/minetest/minetest/issues/2249

**Comment by WSDguy2014** [comment]
Also same thing on server with long description?

**Comment by rubenwardy** [comment]
Fixed with new content tab

**Comment by SmallJoker** [comment]
Double fixed by content tab and automatic scrollable text areas.
