### ISSUE TITLE
Make water nodes a bit smaller

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4439]
I will suggest to make water nodes a little bit smaller because I thing it looks better than full size nodes 

This is water if it is waving. Looks better for me
![screenshot_20160811_191255](https://cloud.githubusercontent.com/assets/16163058/17597856/08ab7276-5ff8-11e6-8e01-ca867253fdf3.png)

This is water without waving. Looks... I don't know the english word
![screenshot_20160811_191406](https://cloud.githubusercontent.com/assets/16163058/17597866/0f096f92-5ff8-11e6-8b9c-341115b13e85.png)

**Comment by SmallJoker** [comment]
> I don't know the english word

Flat; awful; too normal
I agree. If this can be changed in C++, then it should. Having the water level slightly lower makes it look better.

**Comment by asl97** [comment]
related: https://github.com/minetest/minetest/issues/3734
tldl: It would make stuff meant to be floating on top of water "look like flying in the air"

**Comment by MarkuBu** [comment]
Didn't know that there was a new water node. But to be honest: water decoration also "look like flying in the air" if the waving shader is on. It is often recommended that the shader should be turned off, what is now the default and the shaded water also looks crappy sometimes. It just look strange if river water is used in caves, and it flickers

I would prefer the new style water without shader and get rid of water lilies

**Comment by paramat** [comment]
We can't remove all water decorations.
Water shaders are buggy currently, RBA was going to rewrite them, his intention was to not use lower water (for the decoration reason) but use surface texture shaders instead.
We may already have a 'lower water' feature in shaders, waving water with custom parameters might do it.
:-1: For lower water outside of shaders, there will be no smooth lighting as well as flying decorations.
Water is an extremely basic, fundamental and numerous node, these should reman cubic full nodes for simplicity and rendering speed.

**Comment by tobyplowy** [comment]
+1 normal Walter looks too flat ( it should be lowered a little bit 2 pixels or so) but it doesn't really matter to me because I use the waving water anyways (shaders)

**Comment by HybridDog** [comment]
> […] but use surface texture shaders instead.

z fudging?
Make z sorting think the water surface is lower, so the waterlily does not float and the water doesn't look full sized, does it?

**Comment by beyondlimits** [comment]
related: #3759

**Comment by MarkuBu** [comment]
Still looks ugly. I would remove water decorations instead of lowered water nodes

**Comment by paramat** [comment]
We can't remove water decorations :]
Lower water is a specialised or shader thing, even the mighty RBA disagreed with lowered water due to it's problems. He and others actually removed 'new style water' a while ago.
This can be done with waving water with custom parameters AFAIK.

**Comment by paramat** [comment]
You can do this with the waving water shader with wave height set to zero, see https://github.com/minetest/minetest/issues/5427#issuecomment-288127235
