### ISSUE TITLE
debug.txt slowly becomes huge

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4449]
If you use Minetest over a long time, the `debug.txt` gradually becomes huge, going into sizes of hundreds of MiB or even a few GiB. So Minetest slowly clutters your disk. :-/

As an user, there's nothing you can really do about it, except maybe disabling debug logging completely or regularily delete `debug.txt`. I'm not happy with either solutions.

There should be some automatic mechanism which limits the file size of `debug.txt`. Minetest should prevent the `debug.txt` from getting larger than that.
Maybe as a setting, but enabled at a reasonable size by default (I'd suggest 3 MiB because this is already extreme for a text file).

I am not exactly sure how exactly this could work. Anyone knows how other applications prevent writing huge log/debug files?

PS: I don't know if this issue was posted before, but I checked and found nothing.

**Comment by rubenwardy** [comment]
On start up, minetest could do something like this:

```bash
head -n 30000 debug.txt > debug.txt.2 &&
  rm debug.txt
  mv debug.txt.2 debug.txt
```

**Comment by paramat** [comment]
Use debug log level too limit it, maybe the default level is set too high?
I'm not keen on a defined limit because sometimes users want a huge amount of verbose output even if they only look at the last second of it. This limit also depends on device memory size.

**Comment by kahrl** [comment]
> Anyone knows how other applications prevent writing huge log/debug files?

Most daemons (in the linux world at least) don't rotate logs themselves, they either log to syslog or allow to reopen the log file via SIGHUP, and rely on the admin to configure a logrotate job for the log file.

There are only a few I know of that rotate logs themselves. One that comes to mind is ClamAV which has the `LogRotate BOOL` and `LogFileMaxSize SIZE` settings, and even then it's common practice to use logrotate instead of those options (since logrotate is more flexible). Another example is python applications that use the standard logging library and allow the user to choose a [RotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#rotatingfilehandler) or [TimedRotatingFileHandler](https://docs.python.org/3/library/logging.handlers.html#timedrotatingfilehandler).

**Comment by paramat** [comment]
Any core dev support?

**Comment by Fixer-007** [comment]
I wonder if android version has this debug.txt with bloating as well, probably has...

**Comment by rubenwardy** [comment]
Yes, this is an obvious issue. The simplest way to do this may be to limit the file size by bytes, not sure how efficient that would be however. ~Most end users won't need a rotating logger, but just a limited size~ A rotating logger could be used to limit the amount stored efficiently, by only having at most X files of max Y KB

**Comment by Wuzzy2** [comment]
@paramat: Yeah, right, no core dev support, therefore it's OK that debug.txt becomes 20 GiB large. Totally not important ... XD

**Comment by paramat** [comment]
Yes actually, i support this too.

**Comment by miketallroth** [comment]
I had left minetest server running with a couple mods installed and spawning all sorts of stuff. My debug_log_level was set to 2, which over the course of 60 days created a 56G debug.txt file.

My first point of attack on this was to reduce the log level, so I set it to 1, deleted the log files and restarted the server. This definitely slowed down the growth of the debug file, however it did not stop it entirely, even with a world that no one was playing in. Each second, a new set of about 12 lines was being logged.

I finally noticed that the set of lines in the log file always ended with a particular ERROR line. I looked up that error, found a solution to it, and once that error was no longer occurring, then nothing was being logged. Now, it simply logs about 10 lines on server startup and then just sits. It doesn't keep growing!

My particular error was "loadMeta():EnvArgsEnd not found", and I found a nice fix for it at;
https://forum.minetest.net/viewtopic.php?id=1824. However, don't get sidetracked on this particular error, that might not be the same one you are having.

Point is, when the ERROR lines are dealt with, it looks like minetest does the right thing with the log file.

**Comment by paramat** [comment]
LOL 56GB,

**Comment by ClobberXD** [comment]
While I did initially support #8382, a (potentially) better approach would be to fix the random messages that spam the hell out of the logfile, like the following in my case:

```
WARNING[Main]: Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
```

```
WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
```

50-60% of my logfile is just tens and thousands of these messages. While these messages can be potentially useful, it'd be nice if

- they are only be printed once (I don't know how viable this is)
- they are printed at a lower log-level (e.g. `info`)
- they are only printed if MT was built in debug mode (not sure if that's relevant, just putting it out here)

**Comment by Wuzzy2** [comment]
I would love it if these messages would actually specify WHICH PNG file is broken, so that it can be fixed.

**Comment by DS-Minetest** [comment]
Related: #7953

**Comment by SmallJoker** [comment]
@Wuzzy2 It's contained in the verbose output, but should really be moved to warningstream.

**Comment by ClobberXD** [comment]
@SmallJoker What's contained in verbose output? If you're referring to the spammy messages I mentioned in my previous post, they're already logged at the warning level, which is the annoying part.

**Comment by SmallJoker** [comment]
@ClobberXD 
```
debug_log_level = verbose
grep -r "Irrlicht: PNG warning" -A 1 debug.txt >filtered.txt
Tidy lines.

Client: Loaded cached media: 0d90f5b3ffda36a46aa150afde6352f641066dd4 "bbq_veggie_packet.png"
Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
Client: Loaded cached media: 8b3aa5bd9021e955c05a4ee5b4019eb1a4aa18fc "bbq_veggie_packet_raw.png"
Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
Client: Loaded cached media: 4aecd0c630df2868db4766dbccda29e50ac93157 "character_1017.png"
Irrlicht: PNG warning: iCCP: known incorrect sRGB profile
Client: Loaded cached media: 5e8a03c1620e578f108eef660c9840cf83db3868 "character_1267.png"
Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
Client: Loaded cached media: bd5ec9da2e981edb0f306103d4beb301d3e913e3 "character_1270.png"
Irrlicht: PNG warning: Interlace handling should be turned on when using png_read_image
Client: Loaded cached media: 2016fbb0863f58897d30b4e7bcd6aaedbfeab060 "character_128.png
```
Took me a few minutes.

**Comment by ClobberXD** [comment]
@SmallJoker Oh, so the filenames are indeed output to the logs, just at the verbose level. Weird...

**Comment by Wuzzy2** [comment]
PNG warnings split off into new feature request: https://github.com/minetest/minetest/issues/8910
