### ISSUE TITLE
Node drop behaviour inconsistent with lua_api.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4450]
Here's what `lua_api.txt` has to say about node drops:
>        drop = "",  -- Name of dropped node when dug. Default is the node itself.
>        -- Alternatively:
>        drop = {
>            max_items = 1,  -- Maximum number of items to drop.
>            items = { -- Choose max_items randomly from this list.
>                {
>                    items = {"foo:bar", "baz:frob"},  -- Choose one item randomly from this list.
>                    rarity = 1,  -- Probability of getting is 1 / rarity.
>                },
>            },
>        },

What I am interested here is the inner `items` table. I suspect what is meant here is that the probability of 1 item in this table is equal for each item within the item table, so in the example above the probability to get `foo:bar` is 50%.

Consider this Lua code, which is basically the same example as above, just in usable form:

```
minetest.register_node("example:dirtstone", {
	description = "Dirtstone",
	drop = {
	       max_items = 1,
	       items = {
	           {
	               items = {"default:stone", "default:dirt"}, 
	               rarity = 1, 
	           },
	       },
   	},
	groups = {oddly_breakable_by_hand=3},
})
```

Expected: Drop is either dirt (50%) or stone (50%).

Actual result (from testing): Drop is always 1 dirt **plus** 1 stone at once.

Therefore, either the Lua documentation is wrong or Minetest behaves incorrectly. Please clarify for me what is the actual intended behaviour, because I have already contributed to 2 mods which tried to calculate drop probabilities under the assumption that the Lua documentation is correct.

Tested in Minetest 0.4.14.

**Comment by paramat** [comment]
Already fixed, see latest docs.
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3627
