### ISSUE TITLE
Server keep sending data on unavailable client

### ISSUE THREAD

**Issue by volkj** [minetest/minetest#4453]
On a client crash i noticed that the server, in a multiplayer game, kept sending data to the client in an unusual quantity (about 3-5 MB in a time of ~10 seconds).

Currently tried on 2 servers, on client crash (original cause of client crash was a library mismatch on the from-repo minetest client from my distro, gone away once recompiled) or killed with `kill -9` the server keeps sending data with a speed of 2~3 Mbit/s for ~ 10 seconds, an unusual speed as the normal speed on client using (player moving or interacting) seems to be under 1 Mbit/s.

Minetest 0.4.14

**Comment by Fixer-007** [comment]
Can you try this on latest minetest 0.4.14-dev build? There was some fixes for "Resend reliable" network problem, maybe it helps.

**Comment by volkj** [comment]
Minetest 0.4.14-dev-986d70c-dirty (Linux)
Client to remote public server (version 0.4.14): after the `kill -9` it downloaded 10 MB of data.
Client to local server, vanilla: after the kill it seems to not transmit anything, then it started transmitting at least 1 MB.

I noticed the activity stopped once the server acknowledged the player timeout, reported in the terminal as `2016-08-18 17:19:13: ACTION[Server]: Volkj times out. List of players:`

**Comment by est31** [comment]
They weren't really fixes, they were mere workarounds and only treating the symptoms.

Probably what you see is the server trying to reach the client and to get it respond. I don't think there is much we can do here.

**Comment by Fixer-007** [comment]
>(about 3-5 MB in a time of ~10 seconds)
>of 2~3 Mbit/s for ~ 10 seconds

this figures are suspicious to me, I think you added this label too fast. This needs more investigation?

**Comment by est31** [comment]
maybe but I won't do it :)

**Comment by lightonflux** [comment]
Volkj i think you need to test it with a -dev server. Because MT stable isn't patched in any way (afaik). If you need a public server with -dev ask me, i will create one if needed.
