### ISSUE TITLE
Multiplayer joins/quits should be yellow in chat

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4454]
I would text color is yellow. For example:

Player joined the game.
Player left the game.

![000 -](https://cloud.githubusercontent.com/assets/13905392/17803835/858fb504-6601-11e6-86d6-251ce3388b57.jpg)

Must be Minecraft-like. Without yellow text color, will be sad. :(    It used to almost trolling players with "/me" command.

I don't like without yellow text color. For example like this:

**\* Player joined the game.
**\* Player left the game.

![image](https://cloud.githubusercontent.com/assets/13905392/17803910/e0c89260-6601-11e6-988b-83d4d8603fd0.png)
This is default, from 0.4.14  ^ (Note: It's glitched wield item from 0.4.11 - 0.4.13).

Please. Add this.

**Comment by xunto** [comment]
I don't even know why should on_die, on_join, on_left messages are defined in builtin. It should be part of games. :/

**Comment by WSDguy2014** [comment]
@xunto, there's no death messages mod in minetest_game.

**Comment by xunto** [comment]
@WSDguy2014 Ops, I was looking at freeminer code. Omg, it's even worse. Is it defined in cpp? Why? We don't even need to define it. It should be written using register_on_joinplayer and etc.

**Comment by Calinou** [comment]
:+1:, should be relatively easy to do. Helps with reading chat, so why not.

**Comment by SmallJoker** [comment]
:-1: It's easier to ignore some white/grayish lines than a rainbow in the top left corner.

**Comment by paramat** [comment]
:-1: Yellow is much more visually intrusive.

**Comment by LazyJ** [comment]
:+1:

Having colored nicks would help resolve one form of trouble-making on multi-player servers where the trouble-maker impersonates a known player, in in-game chat, with rude or offensive chat messages. They do this by holding the space bar until there is a tremendous amount of blank spaces before entering the false chat. The result looks like the victim had sent the message instead of the impostor because all the excessive spaces push the original sender's nick out of the text area.

Here's an example:

>\<BillGates\>. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .\<RichardStallman\> Microsoft Windows and proprietary software is infinitely superior to GNU/Linux and FOSS!

With colored nicks, the "\<RichardStallman\>" part of the fake message would appear white along with the rest of the message and that would be the visual clue that the message and its sender is a fake *(if the text written wasn't so obvious to that fact)*.

Colored nicks could be a useful tool to help Minetest server staff and players to sort out the situation quickly.

**Comment by HybridDog** [comment]
@LazyJ faking other persons is a lot easier, on the one hand
in comparison to \n, \r allows a line break without having the <playername> thing added automatically, i.e. if you have it in your clipboard (ingame) you can use \r to fake any message, on the other hand
the default fonts in minetest make big i look like small L, i.e. everyone with an I or l in their name can get a copycat.

**Comment by WSDguy2014** [comment]
@LazyJ, maybe add chat limit for typing, due for flood/text is soo long and gets a lag.

**Comment by WSDguy2014** [comment]
@SmallJoker, but i like a Minecraft-like game. If you publish new stable version with non minecraft-like from default/vessels. will get many of hates people disliked for non minecraft-like features. For example: bookshelf texture changed, now only front and back. Not left, nor right side. Because, developers changes    game feature every update.

**Comment by paramat** [comment]
Heh.

**Comment by est31** [comment]
@LazyJ in fact its possible right now for clients to send colored chat. So faking still will be possible, even with colored nicks.

**Comment by xunto** [comment]
@est31 you can escape user mesages.

**Comment by xunto** [comment]
@WSDguy2014 #4460 meged. Now you can customize join and left messages. They are in builtin/game/misc.lua

**Comment by ExeterDad** [comment]
I happen to like the colored chat in MC. I also like the larger text. It's easy to see, and it seems my kids have no trouble looking through it to do their building. It's unfortunate that the opinion is we have to be completely original to avoid being a copycat. If something makes since and works, why resist simply to be unique? I don't and have never played MC, but my kids do daily and convincing them to choose MT is impossible. That said... my kids started off playing MT. Long before I lost them to the "Dark Side".

**Comment by xunto** [comment]
@ExeterDad You can customize font for yourself. And you have modding api where you can colorize. So what's the problem?

**Comment by ExeterDad** [comment]
I'm aware chat may be modded. It was more of a response to @SmallJoker's a bove comment than a problem :)

**Comment by beyondlimits** [comment]
I can hold  (that's U+001B) in clipboard and type coloured mesages like ```(c@#FFFF00)yellow```.

An idea:
```
minetest.register_on_chat(function(player, message)
	-- colorize, strip escape sequences, do whatever... and display!
	minetest.chat_send_all("<" .. player .. "> " .. message)
end)
```

**Comment by paramat** [comment]
White as default makes sense as it's less intrusive and colour neutral. An option for non-modded coloured chat is more acceptable.

**Comment by nerzhul** [comment]
in fact, i think chat should be reworked server side to be flexible and have some norms, to send more typed messages defined in core (system messages, chat messages, errors ...)

**Comment by est31** [comment]
@nerzhul that can be done via mods already (they have access to the color environment), no need to overengineer this.

**Comment by rubenwardy** [comment]
If the server sends what type a message is along with the actual text, eg join/quit/chat/mod, then it would be possible for the client to be modded/patched to use different colors

**Comment by nerzhul** [comment]
Nice point for Rubenwardy, having a proper protocol permit to have better client side modding possibilities.
I think this chat improvement should be done for 0.4.16, but if some other coredev agreed that we should have proper chat, i can provide some patches to make chat better for client + mods

10 octobre 2016 16:10 "rubenwardy"  a écrit:
	If the server sends what type a message is along with the actual text, eg join/quit/chat/mod, then it would be possible for the client to be modded/patched to use different colors

**Comment by WSDguy2014** [comment]
> _xunto said:_ 
@WSDguy2014 #4460 is meged. Now you can customize join and left messages. They are in builtin/game/misc.lua


@xunto, 0.4.15 released, but how i do to customize join and left messages color? I'm bad for coding.

**Comment by paramat** [comment]
I think this should be closed now.
