### ISSUE TITLE
Idea: This text should be always displays in main menu and in-game "Your version is outdated! Please, click HERE to download latest version." and other.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4455]
This text should be work in online, if developers made a new stable version: "Your version is outdated! Please, click HERE to download latest version.". You can rid of in-game by hiding HUD, chat and debug info and profiler graph is hidden. It's used to still screenshoting.
If you click button "HERE", it will go to website "www.minetest.net/downloads/". For example:
![000 -](https://cloud.githubusercontent.com/assets/13905392/17805017/1c732560-6606-11e6-818b-0d1ed3326473.jpg)

If server color text is gray, which means, your version is outdated (Server has 0.4.14-dev). If you join this server, you can't. It will get a disconnected and has a message for this:

Outdated client (Please, use {For exampele: 0.4.14-dev}) – The server is running a more recent version of Minetest then the client is.
Outdated server (I'm still on {For example: 0.4.3}) – The client is running a more recent version of Minetest than the server is.

I would like a Minetest snapshot versions (might be a bug, glitches or unstable), not always 0.4.14-dev versions.

**Comment by rubenwardy** [comment]
#2442
