### ISSUE TITLE
Modpack in modpack does not work

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#4458]
The mods of a modpack put into another one in mods/ can't be enabled.

**Comment by paramat** [comment]
Remove the 'modpack.txt' file from the inner modpack?

**Comment by HybridDog** [comment]
>Remove the 'modpack.txt' file from the inner modpack?

doesn't work, it searches an init.lua

**Comment by DonBatman** [comment]
This would be nice. You could organize modpacks much easier. There has been a couple times I wished I could do this.

**Comment by HybridDog** [comment]
llrc, l fixed it at #3473, but that needs upgrade and rebase or the other way round or sth between.
