### ISSUE TITLE
Digging stone with picaxe in creative mode is slower than with bare hand

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4462]
I noticed that in creative mode digging stone with the picaxe is slower than digging stone with any other item or bar hand

Digging wood with an axe is also slower with other items. Same with shovel and dirt. But you need a stone shovel to see a difference. 

A diamond shovel is much faster than normal creative speed, but a diamond picaxe is not fast

Edit: damn, I guess this should be in minetest game

**Comment by est31** [comment]
I'm not sure, is this an engine bug? Its more an mtgame issue, no?

**Comment by MarkuBu** [comment]
I'm not sure, to be honest. The right tool for the nodes works with their normal speed. Creative has no effect.

**Comment by MarkuBu** [comment]
Reopen cause it seems that it is an engine issue

**Comment by est31** [comment]
Either way I'm completely fine with current behaviour. Creative shouldn't completely turn off different digging speeds.

**Comment by MarkuBu** [comment]
As parameters said, everything should have the same dig speed.

**Comment by paramat** [comment]
I noticed that some nodes are fairly slow to dig in creative, as if digging speeds were still being used but just modified. It seems better to just use one optimum dig time for everything in creative to speed up building.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/d767f025cb0d5cca29c1f2147d2a0931a088b717/src/tool.cpp#L129
I think dig time is modified by the level difference between tool and node, so increasing the modified hand level in creative should stop obsidian being slower to dig.

**Comment by paramat** [comment]
In the creative mod the hand is redefined to have digtime 0.5, maxlevel 3.
So for most nodes, which have the default level 1 the leveldiff is 2 so digtime is 0.5 / 2 = 0.25.
For nodes of level 2, 3 etc leveldiff is limited to a minimum of 1 so digtime is 0.5.
For consistency we would therefore set a constant dig time of 0.25 in creative mode.

**Comment by est31** [comment]
:-1: digging speed should depend on which tool you have / select only, and not be globally "switched" by creative/non creative mode. If your tool is slower than the hand, don't use the tool.

I do agree though with setting a constant dig time for the creative hand (no tool selected), because this would help with consistency.

**Comment by paramat** [comment]
Equalising the hand dig times may be possible in the creative mod, i'll see. I'm not too bothered about tool behaviour.

**Comment by paramat** [comment]
Seems possible but a little hacky. I suggest setting hand maxlevel to a high value so that leveldiff doesn't change much between nodes of levels 1, 2 and 3. Dig time would therefore need to be set to a high value because it will be divided by a large number. There would still be a slight difference in dig times for nodes of different levels.

**Comment by MarkuBu** [comment]
I agree that using a tool in creative mode shouldn't be necessary because you wouldn't fill your inventory with tools. So I picked a stop watch. 

First time is bare hand, steel tool and diamond tool. Times are only approximate values

Wood: 3s, 9s, 6s
Dirt: 3s, 4s, 2s
Stone: 3s, 5s, <3s

I need to dig 10 nodes with bare hand slightly more than 3 seconds. So digging speed of some diamond tools is faster than the bare hand in creative

**Comment by paramat** [comment]
Yes that's expected, we can always adjust hand speed to be as fast as diamond tools, i'll make a PR for creative mode.

**Comment by MarkuBu** [comment]
add parameter to minetest.conf

creative_dig_speed = x

or something like that. So can everybody set his favorite value.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest_game/pull/1268

**Comment by paramat** [comment]
Creative mode is meant to use the hand only and i don't feel there is much need to change tool behaviour in the engine, so :-1: for engine changes.

**Comment by MarkuBu** [comment]
Ok, will close this here
