### ISSUE TITLE
Schematic Decorations to use spawn_by

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4463]
Would it be possible to have it so that schematic decorations are able to use the spawn_by feature for placement ?

**Comment by paramat** [comment]
This was added on my request, easy to implement and useful.

**Comment by tobyplowy** [comment]
👍  +1

**Comment by sofar** [comment]
What would the content of `spawn_by` actually contain? Nodenames?

Perhaps this is best explained by writing the `lua_api.txt` documentation first so people can get an idea of the implementation and what it does (that's unclear to me from this report)

**Comment by paramat** [comment]
'spawn by' is already used for simple decorations (see decoration definition bottom of lua_api.txt), the idea is to simply allow decoschematics to use it too.

**Comment by paramat** [comment]
hmmmm is ok with this so i'll attempt it sometime.

**Comment by paramat** [comment]
#4520

**Comment by paramat** [comment]
#4520 merged.
