### ISSUE TITLE
Pressing number four (4) tries to connect to the server

### ISSUE THREAD

**Issue by baptistepouget** [minetest/minetest#4465]
when i press on the 4 key on top of the keyboard not the numpad and shift to write the number 4 the game tries to connect to the server

here is a video of the issue
https://youtu.be/o8uesny8Jm0

i'm running fedora 24, minetest 0.4.14

It's the first time I experience this...

**Comment by rubenwardy** [comment]
what keyboard layout do you use? As in, QWERTY/AZERTY etc

**Comment by baptistepouget** [comment]
I use bépo

**Comment by baptistepouget** [comment]
Ok so I changed my main layout to azerty and it seems to be working now, weird though

**Comment by red-001** [comment]
Wouldn't this be an Irrlicht bug?

**Comment by red-001** [comment]
Isn't this a duplicate of #302?
