### ISSUE TITLE
All node/block breaking speads should be the same in creative

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4466]
For example if you break a wood block it just takes a second but if you break an iron block it takes you 3 seconds I think all these speeds should be the same (all blocks should break at the speed of wood)
This is based on https://github.com/minetest/minetest_game/issues/1267

**Comment by Wayward1** [comment]
Duplicate of #4462

**Comment by rubenwardy** [comment]
duplicate of game#1267
