### ISSUE TITLE
Being able to change the color of grass water and the sky in biomes

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4467]
I think biomes should work the way they work in Minecraft where there's different zones and in those zones grass, trees, and water, (also a little thing that's not in Minecraft is being able to change the color of the sky that would also be nice) being able to change the colors in biomes should be a thing in Minetest here's the perfect [picture](http://i.imgur.com/TJtO8Br.jpg) to show what you can do with this

Also stuff like [this](http://i.stack.imgur.com/hcejG.jpg) would be possible without having to make new nodes/blocks

**Comment by paramat** [comment]
This has been discussed quite a bit here and there, probably in the forum somewhere. I'm strongly opposed for reasons given in these discussions.

**Comment by MarkuBu** [comment]
I wanted to create a similar issue, but not for texture and water color.

I want to suggest, that mods can change sky color, cloud density and color, light level and fog distance. If fog is disabled a mod should be able to turn fog on.

This would help e.g. weather mods to create more realistic weather situations.

**Comment by paramat** [comment]
>  change sky color, cloud density and color [...]  fog distance

These are certainly possible and i would support these.
Light level seems more difficult and complex.

**Comment by tobyplowy** [comment]
@paramat maybe Grass color gradient can be added for the upcoming biome update?

**Comment by paramat** [comment]
Erm no, that's a huge job and i'm strongly opposed.
More biomes, each with differing surface nodes is the way to go.

**Comment by tobyplowy** [comment]
@paramat ok :( also I Wanted to ask Something When Will and grass variant for the Jungle biome be added and The Desert Biome? 

also another thing I wanted to ask is the fog, is that a good idea Maybe in biomes like the deserts The fog could be really dense And sand coloured also oceans could have a far fog with dark Blue sky and white fog, and Jungle could have a greenish Blue sky and dense fog, what do you think about this?

**Comment by bendeutsch** [comment]
I've actually started working on a cloud API a while ago: https://github.com/bendeutsch/minetest/tree/clouds-api . Supports cloud density, color, and "glow" (minimal brightness).

I'm still new at the Lua API and minetest's network system, though, so progress is a bit slow at the moment.

**Comment by Fixer-007** [comment]
@paramat if you are opposed to this then how about JUNGLE dirt with grass block? That will be a nice addition.

**Comment by paramat** [comment]
You mean dirt with a grass of a different colour?
I'm not sure jungle should have thick grass as a floor, it's more likely to be a dirt surface.

**Comment by Wuzzy2** [comment]
Hmm, now with the improved coloring options available in Minetest 0.4.16, I think colored grass is now a possibility.
This issue can probably be closed as fixed. Right?

**Comment by paramat** [comment]
Smooth changes in grass, leaves, water colours across a landscape is now more possible due to hardware colouring, but requires a new second biome API to be added, which i will not do and will not maintain.

it is certainly possible to now write a Lua mapgen that uses hardware colouring to get this effect if you want it.

So ther's no point keeping this open, if or when MT has a second mapgen dev who is interested in this then you can ask again, however i will always be opposed to such a waste of effort on over-fanciness.
