### ISSUE TITLE
Very strange distorted leaves (allfaces_optional drawtype)

### ISSUE THREAD

**Issue by LNJ2** [minetest/minetest#4469]
![screenshot_20160826_203905](https://cloud.githubusercontent.com/assets/13557034/18016912/13741c2a-6bcf-11e6-9323-6a1a87a6b047.png)
![screenshot_20160826_204726](https://cloud.githubusercontent.com/assets/13557034/18016924/231d3d64-6bcf-11e6-9b89-d546b07c85fe.png)
![screenshot_20160826_204753](https://cloud.githubusercontent.com/assets/13557034/18016938/3064a296-6bcf-11e6-99f3-3ad4796600a6.png)

After a restart or in a new world (same seed) I got the same bug, but not at the same place.

The screenshots are made with Minetest TNG (subgame), but I also got these bugs with MTG.

Minetest 0.4.14
Debian Sid 64-Bit
OpenGL 3.0, Intel HD 4000, i5-3210U, 12GB RAM

**Comment by Fixer-007** [comment]
Check your main system memory for errors. 10 years ago my ATI Radeon 9600 was giving me the same problem in other game because of the faulty RAM in my videocard, since Intel HD 4000 uses main system memory, it could be faulty. Try updating your drivers, or changing shader settings.

**Comment by sofar** [comment]
This is a typical side-effect of memory errors/faulty memory. A memtest86 run would be instrumental to see if it is indeed faulty system memory.

**Comment by LNJ2** [comment]
It's not Minetest, I also get this 'bug' in other games...
