### ISSUE TITLE
Make forceloads act per-mod: introduce named forceloads

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4473]
Typically mods need something forceloaded because they are doing something, and it doesn't matter too much to the mod if a block they don't need forceloaded remains loaded. So a block should remain loaded as long as any one mod needs it to be. To solve this issue, named forceloads should be introduced. forceload_block should come with a parameter for naming the forceload, and as long as any one forceload on a block is active, the block should remain loaded. The forceload removal function should come with a corresponding parameter. Doing it this way would allow mods to forceload the same blocks without interfering with each other, and a block would remain loaded as long as any mod needs it. To avoid name collisions there should probably be a convention where forceload names are prefixed by the mod name.

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3262
Mods can manually save forceloaded positions, when quitting the server they can save the positions there and when starting it, they can load them from there.
So you could alternatively make consistent forceloading deprecated.
Or you could make consistent forceloads be stored automatically in builitn's mod storage (if it has one).

**Comment by raymoo** [comment]
@HybridDog I agree that this isn't as useful after API support for non-persistent forceloads was added (by me). I'm assuming that by "consistent" you mean "persistent".

The main benefit of this feature at this point would be that mods cannot accidentally remove too many forceloads and un-forceload a block that should have been kept forceloaded by another mod.

Deprecating persistent forceloading might be a good solution. The only use case I can imagine for automatically persistent forceloading is if you have forceload nodes, because then the "forceloading state" is part of the map and the mod doesn't have to keep separate information about forceloads. Any other usage would probably have the mod keeping track of the forceloads already, in which case they can just use transient forceloads.

Saving persistent forceloads in builtin's mod storage looks like to me the completely orthogonal issue of replacing forceloads.txt (which probably should be done). I don't think it has anything to do with named forceloads.

**Comment by HybridDog** [comment]
> I'm assuming that by "consistent" you mean "persistent".

You're right.

> The only use case I can imagine for automatically persistent forceloading is if you have forceload nodes, […]

Also, if a server admin decides to remove such a mod, the positions are still forceloaded, aren't they? 

> I don't think it has anything to do with named forceloads.

If you switch to using mod storage, you can simply add the mod name as additional information, whereas with forceloads.txt you'd need to care for compatibility I think.

**Comment by raymoo** [comment]
@HybridDog Why couldn't you just add more information to the table that's written to forceloads.txt?

**Comment by HybridDog** [comment]
Sorry, I don't know how forceloads.txt looks like. If it's a table, you could do it of course.

**Comment by raymoo** [comment]
It's in minetest.serialize format (aka just a Lua chunk)

**Comment by paramat** [comment]
Any core dev support?
