### ISSUE TITLE
Strange mapchunk regeneration due to 'deleteblocks'

### ISSUE THREAD

**Issue by paly2** [minetest/minetest#4476]
Hello,

The /deleteblocks here command (so, I guess, the minetest.delete_area API function) regenerates blocks a lot further than written.

I just did a /deteblocks here 1. I could read in the chat: Successfully cleared area ranging from (-266.0,-0.5,47.8) to (-264.0,1.5,49.8). But there were regenerated nodes in -225,35,120 for example.

Note: out of the area indicated by the chat message, not all blocks are generated. It looks random: some are, and some are not.

2nd note: I use the [MTSatellite](https://bitbucket.org/s_l_teichmann/mtsatellite/) redis server (mtredisalize).

**Comment by paramat** [comment]
The regeneration works in mapchunks (80^3 nodes). All mapchunks that contain reqested area are regenerated.

**Comment by paly2** [comment]
But the mapchunk regeneration is very strange (really, it looks random out of the mapblock): nodes that were generated as air but then builded as other nodes look untouched, while the other nodes (that were generated nodes dig and replaced) are randomly regenerated (some stay untouched and some are regenerated)... Is that normal ?

If you don't understand I may do a screenshot

**Comment by paramat** [comment]
Yes screenshot please, you can drag and drop it into a comment.

**Comment by paly2** [comment]
The mapgen is v6

**Comment by paly2** [comment]
I found a non-reconstructed house destroyed by an old deleteblocks, which may show the bug.
![screenshot_20160911_122158](https://cloud.githubusercontent.com/assets/12398822/18416662/c6ad8658-781a-11e6-9614-22a584efa8b2.png)
As you can see, the door is gone, and the floor has been replaced. However, every nodes have not be regenerated, for example:
![screenshot_20160911_123059](https://cloud.githubusercontent.com/assets/12398822/18416709/f0a68260-781b-11e6-915a-4cd0649cf089.png)
The stonebrick here (such as the node in the "1" entity) here has not been regenerated (I broke three desert sand nodes to make the stonebrick visible)
![screenshot_20160911_123312](https://cloud.githubusercontent.com/assets/12398822/18416710/f3af5c66-781b-11e6-8d3a-ba9a0a0fb51c.png)
And here the stonebrick and even air have not been generated too (I did not break the desert sand and desert stone, they were air before /deleteblocks and stayed air after it)

The three screenshot should be in the same mapblock (the debug info are shown on the screenshot, if you want to check, I do not know very well where the mapblocks begin and end) and they are definitely not in the mapchunk were the /deleteblocks has been done.

**Comment by paramat** [comment]
Thanks, i am bemused.

**Comment by paly2** [comment]
May the protected areas have any influence on the deleteblocks behaviour ?

**Comment by HybridDog** [comment]
The problem looks similar to the one which happened when you join on the same world at the same time in two minetests (which is fixed by locking the map afacw).

**Comment by paramat** [comment]
When a mapchunk regenerates, the large caves often extend up to 16 nodes beyond the mapchunk border, removing any nodes that are 'ground content = true'.
Not sure if this is what you're seeing, one way to test is to do a 'deleteblocks' for one mapblock and make a note of which mapchunk it is in (mapchunks always extend from -32 + n * 80 in each co-ord to that plus 79. So minp co-ords are always -32 48 128 208 288 etc.).

**Comment by paramat** [comment]
No response, unconfirmed, unreproduced.
