### ISSUE TITLE
More glitches and idea

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4478]
I found some glitches in Minetest version 0.4.14

How to reproduce: https://www.youtube.com/watch?v=jB3V1v8RBPc
1. Footstep spamming sound.
2. Sometimes, if you hold shift to sneak, while falling on the gravel block and it's not making a sound.
3. White particles, while breaking a wooden trapdoor.
4. Player nickname tag locates incorrect way, while riding on boat.
5. Impossible to kill a player, if player riding on boat.
6. If you opened the game, joining a server first time, sometimes does not joining and it will show a grey screen (Does not show in video).
7. Blinking lines problem in new chat.

Idea:

If you right-clicking on bed, if it's daytime, will show a chat message, i don't like it. Improve message like this:
![screenshot_20160828_230727](https://cloud.githubusercontent.com/assets/13905392/18047749/1970fac0-6de7-11e6-9111-2f68930e5002.png)

If you standing on 4 blocks away from the bed and right-clicking, if it's night time, will show a message:
![screenshot_20160828_231044](https://cloud.githubusercontent.com/assets/13905392/18047764/26862190-6de7-11e6-882f-4ba04a610407.png)

Because, player will set a spawnpoint 4 blocks away from bed. Too far away.

Must be very closer to the bed, and then right-click to sleep. Showing marking with torches, closer to bed, to detect a player, to sleep:
![screenshot_20160828_231159](https://cloud.githubusercontent.com/assets/13905392/18047777/32ae55c8-6de7-11e6-8f6b-4d323dd04d07.png)

This feature based on Minecraft: https://www.youtube.com/watch?v=3GrPWuLmjn4&t=1m10s (Stop watching video at 1:20)
https://www.youtube.com/watch?v=9qRRQBCWDvw&t=3m28s (Stop watching video at 3:34).

Also, add the code for bed:

`if_player_sleeping:true` - Player detects if sleeping on bed. Because, it's used to fix for another player sleeping on occopied bed (If player is sleeping). It's a glitch.
`if_player_sleeping:false` - Player detects if it's not sleeping on bed.

**Comment by SmallJoker** [comment]
One bug per issue only, please.
Everything about beds belongs to minetest_game. This is the core repository and is not the correct destination for this suggestion. -> https://github.com/minetest/minetest_game/issues

**Comment by paramat** [comment]
1. Already has an issue open.
3. Is a game issue probably.
All the bed ideas can be combined into a feature request issue in game.

**Comment by paramat** [comment]
5 now has an issue.

**Comment by paramat** [comment]
@WSDguy2014 
2 is possibly fixed.
Your additional unnumbered issues about beds are MTGame issues.
Please split these into individual issues and move some to MTGame.
No response so closing.

**Comment by WSDguy2014** [comment]
Posted issue on minetest_game: https://github.com/minetest/minetest_game/issues/1659
