### ISSUE TITLE
Gray screen on Lua error (completely freezes Minetest)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4482]
Hi, here's an issue I encountered quite often in Minetest 0.4.14 and earlier versions while modding:

When one of the mods has a Lua error, sometimes instead of just halting the server and showing the Lua error, the entire Minetest screen becomes gray, nothing else is visible and Minetest doesn't react to almost anything, not matter what keys I try to press. I have to manually close the Minetest window. At least Minetest reacts to normal closing; it is not neccessary to kill (`SIGKILL`) the application.
That's pretty much like the infamous blue screen in Windows, only that it's gray and without text. ;-)

I know this “gray screen” occours on Lua errors because on every occurance `debug.txt` shows a Lua error. When I fix this Lua error, the gray screen is gone. It has never happened to me that I got a gray screen _without_ a Lua error being reported into `debug.txt` before.

The expected behaviour is of course that Minetest still works, but it displays the Lua error and maybe halts the server if needed, so that the user doesn't have to restart Minetest entirely.

I am not sure what causes this bug. But from my experience so far it seems to be more likely to happen when a critical (=causes server to halt) Lua error happens while a formspec or the console is opened.
More research on this needs to be done, obviously.

Note: I am using Minetest 0.4.14 on GNU/Linux.

**Comment by rubenwardy** [comment]
I get this too. I run Minetest using the console, and so see an error in the console

**Comment by Wuzzy2** [comment]
I have currently no buggy mod at hand which can be used to reproduce a gray screen, but as soon as I have one again, I will post the source code here. I hope this will be helpful for fixing this bug.

**Comment by MarkuBu** [comment]
Interesting. I never saw a grey screen. Is it a special kind of error?

**Comment by rubenwardy** [comment]
Replicated it. Open the inventory and cause a formspec submit, for example by clicking a creative inventory button.

```lua
minetest.register_on_player_receive_fields(function(p, n, f)
        abc.def()
end)
```

**Comment by t4im** [comment]
If i remember correctly, then this only happens on LuaJIT. Vanilla Lua will actually return to the main menu with a proper dialog.

**Comment by Wuzzy2** [comment]
Note: My Minetest program does not have LuaJIT (`USE_LUAJIT=0`), but I still experience the bug.

**Comment by DonBatman** [comment]
I get this too. I do not use luajit.

**Comment by paramat** [comment]
Happens to me without LuaJIT.

**Comment by LunaSquee** [comment]
This still happens on 0.4.16.

**Comment by MahalRaj** [comment]
Regarding: gray screen. Mainly seen on my Samsung note 7 while playing local lan on 0.4.16.17 windows server. Note 10 not so much of a problem.  It was a gray screen that occured when entering inventory.  I remedied this by reducing complex mods (adv-trains) and eliminating UNIFIED INVENTORY mod which seemed to create more problems as I got up in mod count (I miss that mod too).  The grey screen would commonly appear while switching pages within inventory.  I can't remember a time it wasnt inventory related.  It wasn't strictly Unified Inventory, I still get grey when opening default inventory, but not very often.  If I keep my inventory pages below 248 I'm good.  Above 250 pages, I'll have problems.

**Comment by paramat** [comment]
MahalRaj that might be due to a different cause, it sounds like it's caused by too many inventory items, instead of on a Lua error.

**Comment by rubenwardy** [comment]
I can't reproduce this with the above script anymore

**Comment by LoneWolfHT** [comment]
**Steps to reproduce**

Create a mod with the code minetest.after(3, function() meintest.log("This shouldn't work") end)
Join a world with the mod enabled
Press T and wait for game to crash

**Comment by Wuzzy2** [comment]
I was able to reproduce LoneWolfHT's steps in 5.2.0-dev @ 44458896d9097c15c722c5bffb3d72e14962b7ce.

**Comment by ClobberXD** [comment]
I'm able to reproduce the gray screen every time there's a mod error while a formspec is open. I *think* I've also encountered this when there's an error while processing formspec events, but that's again probably because the formspec is still open.

**Comment by LoneWolfHT** [comment]
Yeah, formspecs and the chat cause it. 
It would be nice if this could be fixed. It causes the command history to be wiped (since I have to start a new client), and when you're using a bunch of complex WE commands to test your game for bugs a command history wipe is a bit annoying
