### ISSUE TITLE
Player immortal while attached

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4484]
It turns out that while the player is attached to an entity (boat, cart) they are immune to attack by other players and mobs.  The minetest.register_on_punchplayer() function is never called.  This is quite a bad problem.

**Comment by stujones11** [comment]
I think this is due to the fact that attached entities do not have a collision-box

Related #2851

**Comment by Megaf** [comment]
We've just confirmed the bug here. Can't be harmed by sword attacks if you are on boats for example.

**Comment by Fixer-007** [comment]
Confirm.

**Comment by SmallJoker** [comment]
No idea why this was added: https://github.com/minetest/minetest/blob/master/src/content_sao.cpp#L445

**Comment by Megaf** [comment]
Maybe if a player dies while attached something bad happens?

**Comment by stujones11** [comment]
@SmallJoker no idea but it looks like it's been that way ever since the attachment system was added. https://github.com/minetest/minetest/commit/948b5a8be7b13a346c873c157567a72b4e7e320a#diff-da1e28445fc732755d2b64683bd94ee4R1081

**Comment by Wuzzy2** [comment]
Can this be added to the 0.5.0 milestone? This bug is quite serious.

**Comment by Wuzzy2** [comment]
Fixed via #6786.
This can now be closed.

:tada:
