### ISSUE TITLE
 Settings tab: settingtypes.txt for modpack

### ISSUE THREAD

**Issue by Rui-Minetest** [minetest/minetest#4491]
```
Modpack
|-- modpack.txt
|-- settingtypes.txt <-- this
`-- some mods...
```

It's useful when write the settings for multiple mod.

**Comment by SmallJoker** [comment]
The idea is good because the current settings tab does not look out for the installed mods (or their contents) yet. But this must be fail-safe (maybe dump the error to console). A regular player would have problems fixing a broken file himself.

**Comment by Rui-Minetest** [comment]
Sorry some spams.

I think the mods already can have settingtypes.txt.
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L134

**Comment by SmallJoker** [comment]
Whoops. Seems like I missed something. The use in modpacks seems not much needed now because each mod can decide what it wants to add to the settings tab.
In which specific case is this helpful?
