### ISSUE TITLE
More user-friendly group names

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4492]
This is a feature request.

Currently, groups are kinda an internal-sort of thing. You can only use their internal name like `stone` or `disable_jump` which works fine for modding but not if you actually want to expose group names to the interface.

Groups are very important for gameplay so it makes sense to expose them in some way.

The actual feature request here is to create a function to assign a “readable” group name to a certain group:

`minetest.register_real_group_name(internal_name, real_name)`

Registers the name “real_name” to the group “internal_name”. Using the function is completely optional, but highly recommended to use.
Examples:

`minetest.register_real_group_name("stone", "Stones")
minetest.register_real_group_name("leaves", "Leaves and Needles")
minetest.register_real_group_name("tree", "Tree Trunks")
minetest.register_real_group_name("leafdecay", "Decaying Leaves and Needles")
minetest.register_real_group_name("cracky", "Cracky")
minetest.register_real_group_name("oddly_breakable_by_hand", "Hand-Breakable")
minetest.register_real_group_name("not_in_creative_inventory", "Not in Creative Inventory")`

Style guide for “exposable” group names: Treat them as proper names, so this means in English the first letter of nouns must be capitalized. Examples: “Leaves and Needles”, “Sand”, “Tree Trunks”, etc. Try to write them in such a way that they can be (hopefully) easily pasted into text. Prefer plural form over singular form (this is a soft requirement), especially for grouping nodes together, to make them more distinguishable from node descriptions. Example sentence: “Stone and Desert Stone belong to the Stones group.”

Second function:

```
minetest.get_real_group_name(internal_name)
```

Returns the registered name of the group or `nil` if it does not exist.

Finally, Minetest should automatically register group names for all special groups such as `disable_jump`.
Minetest Game should register group names for all groups it introduces, such as `cracky`.

**Use cases**
- Unified Inventory has a crafting guide which supports group inputs for the crafting recipes. Currently, when you hover them, you get a tooltip with the raw group name in the form of “group:stone”
- `doc_minetest_game` makes use of group names as well. It currently tries to work around the problem of “raw” group names by manually assigning such “readable” names but this is of course doomed to be inconsistent; so this mod could benefit from the change as well

**Comment by paramat** [comment]
Not sure about this, the use is somewhat limited and the readable group names are not much different from the raw ones. Players are often modders and are often more familiar with the raw names.

**Comment by Wuzzy2** [comment]
How can this be controversial at all? Minetest should be useable by non-developers by default. How is this not a no-brainer? I really don't like when players are exposed to Minetest's internals in mid-game. No support for readable group names is probably also a reason why modders rarely expose group names in formspecs.

> the readable group names are not much different from the raw ones

This argument will crumble to dust as soon Minetest finally allows mods to be translated. Besides, underscore-heavy names like `not_in_creative_inventory` really look ugly even in English texts, since they don't belong there.

> Players are often modders

This train of thought is exactly why Minetest is such an usability wreck right now. I thought that Minetest is still supposed to be an engine for actual (!) games, not just developer toys. Even if modders are the majority now (which I doubt), the main audience should be players who are not developers.

**Comment by paramat** [comment]
>  Players are often modders

Sorry for that comment, we should of course not assume a player is a modder.

I can see this would be necessary if or when MTGame becomes translated, but that may never happen or be far off.

Before then i think the internal names are clear enough for non-modders, and modders and those familiar with groups will prefer to see the exact technical names. Even for non-modders the internal name helps them to get familiar with the technical names which they will need to use if they start modding.
So i think, for now anyway, it's probably slightly better to use the technical names even if they look less tidy.

For your doc mod it seems the job of the mod itself to provide more friendly descriptions of groups, you might want to provide more information than the 'readable' form provides.

**Comment by Wuzzy2** [comment]
> For your doc mod it seems the job of the mod itself to provide more friendly descriptions of groups, you might want to provide more information than the 'readable' form provides.

The problem with this is that all names given to the groups like this are unofficial, other mods will probably just ignore them or use the internal names because of lack of a better choise. That's why I suggested an engine change, simply for standardization.

**Comment by kaeza** [comment]
I feel this really falls into the domain of mods that want to make use of that feature and has otherwise no use in the engine/default game (contrary to e.g. `description`).

:-1:

**Comment by Wuzzy2** [comment]
Yes, of course this **could** be implemented by mods. This is besides the point. I just think it is not the best idea to implement it by mods.

The problem is, how to make sure the group names are standardized, then?
Every mod will just use their own ad-hoc group names which is pretty suboptimal.
This approach is doomed to inconsistency.

And my experience shows that standardization attempts done within mods rarely work out well or are just very hard to accomplish. If you feel so strongly about avoiding an engine change, then could you at least present me a rough idea on how to do it with mods only? Especially answer me how modders could prevent conflicts with mods? There is the danger that multiple mods pop up which attempt to register group names. This will just lead to chaos, confusion and inconsistencies.

Of course someone could try to write a “de facto” standard mod but from my experience this simply doesn't happen or does not work out well; there are always some mods which try to do the same thing in a different way. Therefore, engine change. Please.

I think the argument “has no use in the engine” is misguided. This is actually just a failure of Minetest since Minetest is **extremely** lacking in any form of built-in documentation, and is also **extremely** lacking in usability. If you don't know already what's going on, you're screwed. Minetest could easily make use of the groups to show e.g. what nodes a tool can dig by e.g. extending the item tooltip. But this is just an example. The fact that Minetest doesn't expose any group names by itself atm does not mean it will or should stay that way forever.

Also, the default game is not everything in Minetest, what's the point in having a generic engine if it only really works well together with the default/example game?

Different idea: What about putting this functionality into `builtin`?

**Comment by rubenwardy** [comment]
If this is to be implemented, it should be a builtin feature. I suggest something like:

```lua
minetest.register_group("cracky", {
    description = "Cracky dig type",
    explaination = "diggable by pickaxes",
    values = "bigger number is easier to dig"
})
```

It should of course be optional.

This doesn't solve the issue of group conflicts. I attempted to solve this by writing this list:

http://more-rubenwardy.github.io/mtostd/mtostd/groups/list.html

**Comment by Wuzzy2** [comment]
Interesting, rubenwardy. Although I would just use the name “Cracky” for the group to keep it short.

By the way, you may be interested in this: http://dev.minetest.net/Groups/Custom_groups
But group conflicts are off-topic here; this issue is only about making the groups more usable.

**Comment by rubenwardy** [comment]
There doesn't seem to be much interest here. Mods can have their own table of groups to readable names, and do `name:replace("_"," "):title()`. I don't think this needs to be a builtin feature

**Comment by paramat** [comment]
:-1:

**Comment by Wuzzy2** [comment]
The problem is, mod implementations will never be standardized. :-(
You always have to hack something together and hope everyone is using your implementation.

**Comment by paramat** [comment]
Yes, but seems minor, it's not a big problem if the readable group descriptions vary between mods as long as they are clear and descriptive.
