### ISSUE TITLE
ICON_DIR not declared in porting.cpp

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#4493]
Latest Android build fails with

``[armeabi-v7a] Compile++ thumb: minetest <= quicktune.cpp
jni/../jni/src/porting.cpp: In function 'bool porting::setXorgWindowIcon(irr::IrrlichtDevice*)':
jni/../jni/src/porting.cpp:625:4: error: 'ICON_DIR' was not declared in this scope
    ICON_DIR "/hicolor/128x128/apps/" PROJECT_NAME ".png") ||
    ^
make[2]: *** [obj/local/armeabi-v7a/objs/minetest/jni/src/porting.o] Error 1``.

Seems to be due to #4407.

**Comment by est31** [comment]
Eh, sorry for that.

**Comment by Wayward1** [comment]
Here's Freeminer's fix:
https://github.com/freeminer/freeminer/commit/417bde0fbaf4b3c9c86125e546b76c57eaddce16

If this is one of those "only one way to do it" situations, meaning it won't be a license violation, I'll gladly open a PR.
