### ISSUE TITLE
disable swimming for liquid type nodes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4494]
Liquid type nodes are not only used for water. They are also used for lava, quicksand, mud or cobwebs. And normally you can't swim in this kind of material

I purpose to add the optional feature to disable swimming (move up with space) to make material like quicksand more realistic and dangerous. Currently it is only slow water

**Comment by sofar** [comment]
This sounds interesting, but effectively creates nodes that trap the player. If you use nodes like these that are 1 deep, the player is just *stuck*, and if the player can't break any nodes around themselves, or somehow die (player head isn't in the liquid, so no drowning happens), then this is a recipe for disaster.

I can only ever see this work for lava, which damages the player, and avoids the "trapped forever" problem that way. But lava is so dense and heavy, a player could actually likely walk on it, and a human wouldn't sink that far in lava anyway due to buoyancy.

So, I'm not so sure this is something that generally will work well.

**Comment by MarkuBu** [comment]
You can still dig nodes like trapsand or mud. But it takes time and you can't fight while digging

**Comment by tenplus1** [comment]
We already have the 'disable_jump = 1' group that can be used for normal nodes to stop player jumping on them, so why not have liquids behave the same way and stop player swimming UP when this flag is active ?

**Comment by MarkuBu** [comment]
seems legit

**Comment by tobyplowy** [comment]
@sofar lol I think you're just overthinking this a bit (it's just a game)

**Comment by paramat** [comment]
Not keen on this. I'd rather a mod altered player physics in such nodes.

**Comment by MarkuBu** [comment]
> I'd rather a mod altered player physics in such nodes.
Why? It would be easier and more performant if this is done in the engine. And if the system is lagging it might be possible to run over these nodes without any effect

**Comment by Wuzzy2** [comment]
I agree with MarkuBu here. I am not very keen of the idea of trying to implement client controls on the server side.

**Comment by MarkuBu** [comment]
I'm still interested in this. And I still think this is not a job for lua. It would be a simple thing for the engine to disable jumping, maybe just one or two lines of code, but a lot of work for lua. And we have enough problems with lag caused by lua mods

I would make a PR myself, but I don't know enough about the engine code

**Comment by paramat** [comment]
Author left MT, anyone else requesting this?

**Comment by Wuzzy2** [comment]
Yes, me. For quicksand this sounds useful; quicksand is used in Ethereal. Cobwebs are used in MineClone 2.

And I pretty much agree with all the other use cases.

**Comment by numberZero** [comment]
I’m not a core dev, but remembering MT is an *engine* and not a game, I consider such feature nice. It’s up to a game to use or not to use it.

> creates nodes that trap the player. If you use nodes like these that are 1 deep

There are so many ways to trap the player already, so that doesn’t matter. And, well, on some servers that may be seen as an advantage.

**Comment by paramat** [comment]
Yes trapping is possible already and we have a suicide command in MTG because of this.

**Comment by paramat** [comment]
No longer opposed, more neutral.

Currently movement in a liquid is slowed down according to the defined viscosity of the liquid. Perhaps we can implement this feature simply by preventing movement (apart from sinking) in a liquid once the viscosity passes a certain high value, as this is somewhat realistic. Then for these special nodes like quicksand you would set a suitably high viscosity value. This way we don't need a new parameter while also making movement in liquid more realistic.
This would mean that zero-player-movement liquids would inevitably spread very slowly (if range is > 0), which seems suitable.

**Comment by paramat** [comment]
PR #7688

**Comment by SmallJoker** [comment]
#7688 merged
