### ISSUE TITLE
More general particle spawners

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4501]
Currently particle spawners are pretty limited as far as trying to make shapes. For example, you can't make a spawner that points all its particles inwards or all outwards, and you can't make particles spawn in circles or anything other than a union of boxes (by using multiple spawners). I don't know a good general solution for this, other than maybe client-side scripts, but I think I should at least say that I wish there was more flexibility in spawning patterns.

**Comment by Fixer-007** [comment]
I think particles also somewhat hard on fps, look at weather mod for example.

**Comment by raymoo** [comment]
@Fixer-007 I suspect it has something to do with how every particle has its own ISceneNode.

**Comment by paramat** [comment]
The problem with supporting complex behaviours is that there are so many, just the very basic essential ones need to be chosen. Complex behaviours can be left to be done by multiple spawners, no point bloating the code for rarely used specialist behaviours.

**Comment by raymoo** [comment]
@paramat I think there are a couple solutions that might address your concerns for having too many specialized behaviors:
  - Allow specifying a matrix from random numbers to position, velocity, acceleration, exp time, and size vectors: This is strictly more general than the current specification, and would allow you to make particles spawn along diagonals, or have positions correlated with velocities if they transform the same random numbers. The downside is that it would require knowledge of vector maths and you would want to add some linear math library to the API to make it easy to specify the matrices. The upside is that vector operations can be done cheaply and that matrices would have a low memory footprint.
  - Allow specifying an expression using a special type: You would have a new userdata representing a mathematical expression, and make a clean Lua API using metamethods for +, *, index, etc. The upsides of this is that it is more general than the matrix one, and that it could be used without knowledge of vector math. It would still be useful to have linear math helpers, for things like rotation, but they would not need to generalize to an arbitrary number of inputs like the matrix solution would. The downside is a larger memory footprint for spawners of the same complexity. If constant matrices and matrix multiplications are made as specific nodes of the expression tree though, the memory overhead compared to specifying matrices would not be that high, and might even be smaller if the matrix is sparse.

Another useful input for both potential solutions would be the elapsed time.

The memory usage / network fatness of both solutions scales with the complexity of the particle spawner, so it shouldn't affect simple spawners as much, especially if the old API is kept alongside the new one. If the old API is deprecated and replaced with the expression tree solution, you could have expression nodes analogous to the old API, for example something like a `particle_math.rand_vec3(low, high)` node, which would avoid needing to create nodes and bloat memory for each individual operation.

Example of a position matrix for spawning particles around a diagonal line (takes as input a 5-vector with four uniform random numbers between -1 and 1, and a constant 1 fifth element):
```
5 0.2 0 0 0
5 0   0.2 0 10
0 0   0   0.2 0
```

The same example for a general math API:
```
-- Creates an expression nodes representing constant vectors
local origin = particle_math.vector(0, 10, 0)
local direction = particle_math.vector (1, 1, 0)

-- Creates expression nodes representing binary operations
local random_along_line = origin + particle_math.rand(0, 5) * direction
-- Use random_along_line in a particle spawner definition
```

@paramat, I think these solutions would address your concerns of being too specialized, as they are pretty general, especially the second suggestion. I would guess that you might think one or both is too complex for Minetest, but would you at least agree that they aren't too specialized?

**Comment by paramat** [comment]
Yes i agree they're not too specialised.
I think using vector maths and matricies is too much to ask of modders. For example i have a physics degree and while with some review i could cope with it, it doesn't come naturally to me.

**Comment by raymoo** [comment]
@paramat I agree that the first suggestion is too much, but the second is similar to what modders already need to do to manipulate player view direction, set entity velocity, etc.

**Comment by raymoo** [comment]
Advanced future tech: spawning particles along diagonal lines: https://a.safe.moe/3TAoR.webm
At the end of the video you can see the mod code required to produce the effect.

**Comment by paramat** [comment]
I disagree with both suggested methods.
However it may be useful to enable particle spawners to do a little more, but the request needs to be more specific as to what to add.

Any core dev support for the suggested methods?

**Comment by raymoo** [comment]
IMO closing should be based on the original problem description, not the suggested solutions. A solution that hasn't been mentioned is server-sent CSM (and some batch add particle function for performance), which would fulfill any use case my other suggestions would have.

**Comment by paramat** [comment]
Yes agreed, sorry.

**Comment by paramat** [comment]
Issue is too vague and i am :-1: for the suggestions.
Specific suggestions for new definable spawner behaviour are more useful.
Note server-sent CSM may not actually happen.

**Comment by raymoo** [comment]
@paramat Should it be one issue per class of particle spawner features?

**Comment by paramat** [comment]
I think any complex spawner behaviour should be done by SSCSM (and only by SSCSM) as then no complexity is added and you gain complete programmable control over behaviour, which is what modders need.

**Comment by raymoo** [comment]
I think the examples in the VM PR compiled to something pretty small (less than 50 bytes as a conservative estimate since I don't remember the exact values), so not sure code size would be a huge problem. However I do prefer SSCSM for its generality.

I think @rubenwardy was interested in the feature itself since he outlined a process for attempting to get it merged. Of course that is just speculation since he hasn't explicitly said that he wants the feature, it could be that he was just trying to help with procedure.
