### ISSUE TITLE
get_stack_max() returns 0 if stack_max > 32767

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4504]
Consider the following Lua code:
```
minetest.override_item("default:gold_ingot", {stack_max = 65535})
```

Then I tested this in Minetest 0.4.14 with the `luacmd` mod:

```
/lua print(ItemStack("default:gold_ingot"):get_stack_max())
```

Expected output: 65535
Actual output: 0

More tests resulted in this observation:
With `stack_max` of 32767 the function returns the correct number. With a `stack_max` of 32768 the function returns 0.

As far I know, item stacks officially support up to 65535 items, so `get_stack_max` appears to be broken.

**Comment by paramat** [comment]
I'm thinking just the change from s16 to u16 is needed here.

**Comment by kwolekr** [comment]
https://github.com/minetest/minetest/commit/2de8c22a9971153d594b2bb4736eb293753f1212
