### ISSUE TITLE
AreaStore:get_area(areaID) crashes for non-existent ID

### ISSUE THREAD

**Issue by taikedz** [minetest/minetest#4507]
Trying to loop over an area store with an index to list the areas, I got this behaviour.

## Issue

When calling `areastore:get_area(id)` with an ID not matching any ID in the store, the game crashes silently (no log, process terminates)

## Expected

Should return nil, no crash

## Reproduce

Lua script:

        local astore = AreaStore()
        astore:get_area(5)

## Env

Installed from Ubuntu PPA

    minetest --version
    Minetest 0.4.14 (Linux)
    Using Irrlicht 1.8.3
    Build info: VER=0.4.14 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"

**Comment by everamzah** [comment]
Can confirm.  Thanks for posting this issue!

**Comment by everamzah** [comment]
@est31 Is there another way to get the total number of entries from the store without having to track it separately?

**Comment by everamzah** [comment]
OMG OMG OMG!

```
diff --git a/src/script/lua_api/l_areastore.cpp b/src/script/lua_api/l_areastore.cpp
index 20e7875..a9bf74c 100644
--- a/src/script/lua_api/l_areastore.cpp
+++ b/src/script/lua_api/l_areastore.cpp
@@ -110,6 +110,9 @@ int LuaAreaStore::l_get_area(lua_State *L)
 
        const Area *res;
 
+       if (!ast->getArea(id))
+               return 0;
+
        res = ast->getArea(id);
        push_area(L, res, include_borders, include_data);

```

Did I do it?!

**Comment by Zeno-** [comment]
403dada
