### ISSUE TITLE
Insane amount of empty stuff in MapBlock metadata

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#4516]
It seems that metadata is being saved for lots of nodes even though there is nothing to save. (Note the absence of any variables or inventory contents!).
The bug is most likely hard to reproduce reliably.

**Possible workaround**: Do not serialize empty metadata objects (`nodemetadata.cpp`)

[decoding script used here](https://gist.github.com/sfan5/52917a0e1338bcda2176edbc416dae60)

![bildschirmfoto_2016-09-10_18-37-38](https://cloud.githubusercontent.com/assets/1042418/18412083/89750f48-7786-11e6-89c4-fe5a6828d1b1.png)
![bildschirmfoto_2016-09-10_18-40-24](https://cloud.githubusercontent.com/assets/1042418/18412084/8d02b4e4-7786-11e6-9274-b474a0184d00.png)

**Comment by IhrFussel** [comment]
Can confirm, my DB (created in 0.4.13-dev from May) also contains a lot of these mapblocks with nothing but air and >50k of meta data.

**Comment by Rogier-5** [comment]
If there are some empty inventories in a block already, does their number grow over time ?

**Comment by Fixer-007** [comment]
I wonder how it affects performance.
