### ISSUE TITLE
Disable basic nodes shader by default

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4521]
See #4336 for further discussion, that was closed because i deleted the PR due to conflicts, the first post has been copied here.
I feel that shaders should be disabled by default, or, the proper fix is made, before next release.

/////////////////////

See #4335 for comparison screenshots and FPS gains.
#3530
#3654
Discussion http://irc.minetest.ru/minetest-dev/2016-07-18#i_4653391

20:25 hmmmmmm it's really hard to decouple now
20:26 hmmmmmm the old code used to calculate tangents from a big set of if statements
20:26 hmmmmmm now i think it actually calculates it using the mathy calculating way
20:27 hmmmmmm you need to basically revert part of his normal mapping commit
20:28 paramat mtgame no longer uses normalmaps but custom texture packs and subgames do
20:28 hmmmmmm i'm sure we can fix it, it just takes some effort
20:28 hmmmmmm everybody's busy though :/

Ideally tangent space should only be used when a shader effect that requires it is enabled, such as normalmaps. However currently tangent space is used even with the basic node shader which doesn't require it.
The result is a huge unnecessary reduction in FPS in the default setup of basic nodes shader enabled. In some cases, for example in built-up areas of servers, FPS has halved, no wonder players complain of low FPS.
The basic nodes shader only makes very subtle changes to colouring and contrast (see screenshots in issue) and may affect the smoothness of day/night transition.
Eventually, once we only enable tangent space when it's needed, we can re-enable the basic nodes shader.

**Comment by everamzah** [comment]
The first impression on a slower machine with shaders on by default is that it's not as smooth as it could, or should be.

I think they ought to be disabled by default, and that one with a powerful PC can enable them.

**Comment by paramat** [comment]
I created a duplicate by opening this, sorry, first post has been copied into #4335
