### ISSUE TITLE
Let players freely bind keys to any action

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4536]
The issue here is that you cannot rebind certain actions to other keys. The actions in question are:
- [ ] Attack/mine (Left mouse button)
- [ ] Build/use (Right mouse button)
- [x] Select next item in hotbar (Rotate mouse wheel down)
- [x] Select previous item in hotbar (Rotate mouse wheel up)
- [X] Select item X in hotbar (0-9)
- [ ] Open pause menu (Escape)

I request that Minetest allows to rebind keys freely for these actions.
For “Select item X in hotbar”, Minetest could make available 23 key bindings (e.g. `keymap_hotbar_1`, `keymap_hotbar_2`, etc.) because the hotbar can have 23 slots at maximum. Slots 1-9 are bound to the keys 1-9, and slot 10 is bound to key 0 by default, like now. The slots 11-23 are unbound by default. This allows interested players for more customization if the default 10 bindings aren't enough for them. :-)
I consider rebinding of Escape to be of minor importance. If it is too difficult to make this key freely re-bindable, it is okay to skip this.

See also: #2361 (binding mouse buttons to actions)

**Comment by est31** [comment]
Dupe of #2361

**Comment by Wuzzy2** [comment]
Not exactly. Part 1 of this issue does not care about the mouse, but about the fact that you can't bind *any* new key to the listed actions.

Only part 2 of this issue may be kinda a duplicate.

**Comment by Wuzzy2** [comment]
I have now edited the issue to remove any mouse-related stuff. This issue is now only about the actions themselves, and not about the mouse.

Please re-open.

**Comment by everamzah** [comment]
It may seem odd, but I would surely rebind 1-8 to tcv5rgwa.  I always use the same keys in different games, except Minetest because of this.

**Comment by est31** [comment]
In fact you can already use joystick buttons for mouse actions, so that code only has to be generalized...

**Comment by tobyplowy** [comment]
With this can you use button 3 (scrollwheel button) for sneaking

**Comment by wilkgr76** [comment]
This could be a bit further 'generalised' for #4398

**Comment by Wuzzy2** [comment]
Good idea! But I think first the basics need to work (free key binding) before #4398 will be even possible.
But #4398 is definitely legit.

**Comment by paramat** [comment]
#4929 merged.

**Comment by rubenwardy** [comment]
Correct

**Comment by GreenXenith** [comment]
I believe the next/prev item selection has been added
![image](https://user-images.githubusercontent.com/24834740/48442758-f3912180-e743-11e8-9de7-935011c8f318.png)
The scroll wheel is not disabled, but it is a keybind nonetheless.

**Comment by LoneWolfHT** [comment]
3 and 4 in your todo are technically done now I think

**Comment by Wuzzy2** [comment]
Digging and building can now be rebound, so the biggest part of this issue is now done. Now the only thing missing is the Escape key.

It is arguable if making the Esc key (pause menu) configurable is *really* neccessary. Feel free to decide for yourself if you want to close this or keep open.

**Comment by v-rob** [comment]
On the other hand, there is no ability to bind the mouse to e.g. the arrow keys for mouseless use (although I think there's already an issue for that).  Ideally, everything could be bound to any type of input device, like to a keyboard button, joystick button/axis, etc, but Minetest doesn't have that sort of support yet.

On the other hand, I think it's important to keep Esc non-configurable.  There should always be a consistent way to exit the game.

**Comment by Wuzzy2** [comment]
Well, it works in `minetest.conf`. `keymap_whatever = KEY_LBUTTON`. (L/M/R)

Anyway, I don't care about Esc anyway. I think this issue can be technically closed then.
