### ISSUE TITLE
core.colorize does not work with multiline strings

### ISSUE THREAD

**Issue by cdqwertz** [minetest/minetest#4543]
This is the code I used:

``` lua
minetest.chat_send_all(core.colorize("#0000ff","Line 1\nLine 2"))
```

The problem is that the first line will be blue but the second line will be white.

Minetest : 0.4.14-dev

**Comment by HybridDog** [comment]
cdqwertz, does it work if you use \r instead of \n for line break?

**Comment by red-001** [comment]
Yes it works if you use `/r` instead of `/n`

**Comment by red-001** [comment]
@cdqwertz could test does #4546 fix this issue?

**Comment by nerzhul** [comment]
Fixed
