### ISSUE TITLE
The privs chatcommand lacks ignoring whitespaces

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#4550]
If you add a space after the playername when invoking /privs, it is put to the playername:
![screenshot_20160926_183834](https://cloud.githubusercontent.com/assets/3192173/18843506/9897c4da-8419-11e6-8184-82ae281886e1.png)
Since playernames consist of selected letters (correct me if l'm wrong), l think it should be trimmed to make /privs work with whitespace(s) e.g. added by some autocompletion mechanism.
l noticed it when editing chat autocompletion.

**Comment by Wuzzy2** [comment]
> Since playernames consist of selected letters

What is a “selected letter”?
Space is not an allowed character in player names. Allowed are A-Z, a-z, 0-9, dash and underscore.

**Comment by paramat** [comment]
#4636 merged.
