### ISSUE TITLE
Some items will not stick to xdecor:itemframe

### ISSUE THREAD

**Issue by kingtard** [minetest/minetest#4562]
I accidentally knocked the default:junglesapling of it's xdecor:itemframe and couldn't get it to stick back on. I tried with newest version itemframe and newest sapling and still didn't work as it did before. Also, seeds never worked.

**Comment by everamzah** [comment]
Just a first question: Did you dig and replace the itemframe itself?

**Comment by t4im** [comment]
> you may want to post this issue there instead.

He already did: https://github.com/minetest-mods/xdecor/issues/60
I asked him to raise an issue in minetest_game (not minetest), as seeds and saplings don't pass the rightclick through to the pointed thing, and neither homedecor's nor xdecor's itemframes can do anything reasonable about that.

**Comment by tenplus1** [comment]
The new sapling placement checking kinda interferes with certain mods now but CAN be overriden by using Megaf's gameplay changes: https://github.com/Megaf/minetest_gameplay_changes

**Comment by est31** [comment]
Closing this issue as its not an engine bug. @kaeza please open an issue report on https://github.com/minetest/minetest_game/issues

**Comment by kaeza** [comment]
@est31 ?

**Comment by est31** [comment]
sorry :) meant @kingtard ...
