### ISSUE TITLE
[Request] Make client timeout if RTT <  0.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4564]
Hi, I was playing now and there was a lag spike on the server side, that made the server time out all the clients. But nobody noticed, clients never got the timeout message and the server was still up as it was just a spike.

But one of the players and then me noticed the RTT = -1. That's a good indication that the client should time out.

**Comment by rubenwardy** [comment]
This is always irritating. It should at least display some notification that the server hasn't replied in X (5<X<20) seconds

**Comment by Fixer-007** [comment]
+1

**Comment by Megaf** [comment]
And this is not very hard to implement, is it?

**Comment by Megaf** [comment]
We need more comments on this issue please.

**Comment by Megaf** [comment]
Ok, tell me what file I have to change and how to do it and I will do it myself...

**Comment by paramat** [comment]
Folding #1654 into this.

**Comment by twoelk** [comment]
could https://github.com/crazyginger72/minetest_time or https://github.com/BrunoMine/latent be usefull for this? 
or is this a good example for (gulp) a 
client-side-mod usecase?

**Comment by Megaf** [comment]
https://github.com/crazyginger72/minetest_time/blob/master/init.lua
That could be added to builtin perhaps, with some changes.
All I want is a simple if/then check.

**Comment by Megaf** [comment]
@paramat Shouldn't I just close this? Not a lot of interest from people in this as it seems.

**Comment by ThomasMonroe314** [comment]
I suppose if the RTT drops below zero everytime there is a lag spike then +1 from me

**Comment by Megaf** [comment]
RTT is Round Trip Time. Is the time it takes for "signal" to travel from client to server and back to client. It's the actual network based ping.
So it's kinda obvious, IMHO, way of telling if the network has stopped working or not.

**Comment by Megaf** [comment]
Hi everyone, is anything been done on this issue?

**Comment by ExeVirus** [comment]
So to clarify: we want the Client to auto-kick itself whenever RTT < 0?
Or do we want a simple warning to the client?

**Comment by Megaf** [comment]
> So to clarify: we want the Client to auto-kick itself whenever RTT < 0?
Yep, client kicking itself out with a message saying something along the lines "Server is too busy now and can't continue. Please come back in a few minutes." could be ideal.

> Or do we want a simple warning to the client?
A warning would be nice, if it's possible to detect that the server still running and the things is recoverable then a warning would suffice. The issue is that the server doesn't seem to be able to continue to keep clients connected after the spike.
I think RTT -1 already indicated that is non-recoverable.

**Comment by sfan5** [comment]
Is this even still present? I'm pretty sure the client does timeout these days.

**Comment by ExeVirus** [comment]
I tracked it down on network/connection.h, like 934 or something like that.
We currently just return nothing when rtt < 0, which based on my reading,
does timeout. So yeah, we fixed it somewhere between 2017-2019.

**Comment by Megaf** [comment]
It indeed seems to have been fixed. I will close the issue for now and reopen if required. Thanks.
```cpp
void UDPPeer::reportRTT(float rtt)
{
    if (rtt < 0.0) {     /////Notice the "Do nothing when rtt < 0"
        return;
    }
    RTTStatistics(rtt,"rudp",MAX_RELIABLE_WINDOW_SIZE*10);

    float timeout = getStat(AVG_RTT) * RESEND_TIMEOUT_FACTOR;
    if (timeout < RESEND_TIMEOUT_MIN)
        timeout = RESEND_TIMEOUT_MIN;
    if (timeout > RESEND_TIMEOUT_MAX)
        timeout = RESEND_TIMEOUT_MAX;

    MutexAutoLock usage_lock(m_exclusive_access_mutex);
    resend_timeout = timeout;
}
```
