### ISSUE TITLE
Minetest fails to compile on Windows

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#4568]
`5>...minetest\minetest-master\src\porting.cpp(632): error C4716: "porting::setXorgWindowIcon": Muss einen Wert zurückgeben`

Free translated:
`5>...minetest\minetest-master\src\porting.cpp(632): error C4716: "porting::setXorgWindowIcon": Have to return a value`

Compiler: MSVC 2015 Enterprise
Build mode: Release x64
OS: Win 7 Professional
latest git master branch

**Comment by est31** [comment]
oops, sorry that was me

**Comment by adrido** [comment]
Never mind ;-) please fix it.

**Comment by est31** [comment]
fcfa418c4cb5c3490413dd345e5e4b998cb7a4c3

**Comment by adrido** [comment]
Thanks
