### ISSUE TITLE
Higher resolution X11 icon

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#4569]
Looks pretty bad in Docky here:
![bildschirmfoto_2016-10-03_19-50-18](https://cloud.githubusercontent.com/assets/1042418/19047574/c08dce24-89a2-11e6-86c0-56bcd736d648.png)

**Comment by est31** [comment]
In fact minetest is supposed to have actually bigger icons than most other applications.

If you do `xprop` in your shell, and then click on the minetest window, you will see that its icon has a resolution of 128x128. This is bigger than most other applications have. Also, it only has one resolution, not multiple smaller ones, so the window manager *has* to use the high res one.

Like for example firefox has according to xprop only resolutions of 16x16, 32x32 and 48x48. Hexchat has only resolution of 48x48.

So its a bit obscure what's happening here.

Plus, I can't reproduce it in KDE when I make my taskbar super large (the minetest icon in fact looks better than the firefox one):

![screenshot](https://cloud.githubusercontent.com/assets/8872119/19051158/1faecf16-89b2-11e6-88af-9b17a1666a32.png)

**Comment by est31** [comment]
Useful link with discussion: #4273
Alternate implementation: https://github.com/est31/minetest/tree/window_icon_old

**Comment by sfan5** [comment]
Docky is not actually using the window icon but something else, probably their bug.

**Comment by est31** [comment]
Do you have a link? I'm interested.

**Comment by sfan5** [comment]
Nah, I just noticed that Docky didn't show an icon despite the window having an icon.

Selecting the icon again in the .desktop file fixed it which leads me to believe that Docky uses the low-res rendered image if it encounters SVG icons.

**Comment by est31** [comment]
OK, thanks anyway.
