### ISSUE TITLE
Server not Listed on Server List when Domain Name is used in server_address Setting

### ISSUE THREAD

**Issue by LazyJ** [minetest/minetest#4570]
**Minetest 0.4.14-dev**, 2016_09_14, 297546a

When using minetest.conf setting "server_address = linuxgaming2.com", the server will not appear on the Minetest Server List nor the Public Server List in the client.

When the IP is used instead "server_address = 45.33.54.11", then the server will appear on both lists.

sniper, of ESP Team's Minetest server, mentioned that he is experiencing the same problem *(but I don't know which specific dev release he is running)*.

**Comment by Megaf** [comment]
This was second of September I think on #Minetest-Project
So it turn out that maybe he had done everything correctly and it was just a bug on minetest?
I know that on commit 45a9145 everything was fine, my server is on that version and it works.
> [11:36:41] <sniper570> in minetest.conf; server_address = IP but if I put domain, it doesn't work, I mean it won't get listed on servers.minetest.net :'(
[11:37:28] <_Megaf> sniper570: should work with domain
[11:37:47] <_Megaf> What's the domain you are using?
[11:40:30] <sniper570> _Megaf: well I haven't configured my domain names yet but according 2 wat I was told domain names refused 2 work b4 but only IP addresses did :(
[11:41:31] <_Megaf> sniper570: if you put a domain name that points to your server it should work
[11:42:19] <_Megaf> If the domain is not set up then it will not work

**Comment by est31** [comment]
**cc** @sfan5

**Comment by Megaf** [comment]
Second time I see you doing that @est31 :)

**Comment by tailot** [comment]
I can also confirm on debian 7.11

**Comment by sfan5** [comment]
First: minetest/master-server would be the 100% correct place for this issue.

Using a domain will only work if your domain points to the IP your server is announcing.
If it does and still doesn't work ping me on IRC and I can debug the issue.

@Megaf `server_website` doesn't exist as a setting or anywhere else.
