### ISSUE TITLE
Add string.regex_search(string, pattern)

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#4576]
This would be very useful for mods that could e.g. perform chat filtering/kick certain classes of usernames. There would be doubtless many other uses as well. To keep things simple, the function can just return a boolean result if the pattern matches any part of the string. More complex regexs like group capturing could be implemented with other APIs if there is demand.

I have never used regexs in C++98, so I don't know how easy implementing this will be.

**Comment by BluebirdGreycoat** [comment]
Adding that I have looked at Lua Patterns. They are missing important features of POSIX regexs.

>Especially if you're used to other languages with regular expressions, you might expect to be able to do stuff like this:
>
>  '(foo)+' -- match the string "foo" repeated one or more times
>   '(foo|bar)' -- match either the string "foo" or the string "bar"
>
> Unfortunately Lua patterns do not support this [...]

**Comment by rubenwardy** [comment]
If added, it would be better as a method or so in the string namespace, not the minetest one

**Comment by BluebirdGreycoat** [comment]
Title changed. Thanks.

**Comment by pgimeno** [comment]
For security reasons, I'd suggest using something like https://github.com/google/re2 - not as feature-rich as other RE engines (most notably it lacks lookahead) but it has a nice worst-case performance, and allows configuring a memory usage limit.

**Comment by nerzhul** [comment]
it needs another depency, C++11 has regexp one embedded in the norm

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by sfan5** [comment]
Sounds useful to me __if__ we can go with C++11's builtin regex instead of adding a third-party library.

**Comment by pgimeno** [comment]
Please check https://cxsecurity.com/issue/WLB-2014070187 for issues with C++11 regex implementations.

**Comment by pgimeno** [comment]
Arguably, Lua patterns have the same issue, though (e.g. [mesecons LuaController blocks all form of Lua patterns](https://github.com/minetest-mods/mesecons/issues/255)). If Lua patterns are safe to use for mods, so are regular expressions.
