### ISSUE TITLE
SEG FAULT on entering anything on the curses terminal.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4579]
Hi, I just updated to 7fab86a and now server happily segfaults when I hit enter to execute anything that I wrote on the curses terminal.

`]Segmentation fault`

**Comment by est31** [comment]
@Megaf what commit did you have before? You can use git reflog to inspect the backlog.

**Comment by est31** [comment]
Mhh, it seems to be caused by d4c76258e37337ea585cf24d8e05b50a30fa307d

**Comment by Megaf** [comment]
Thanks @est31 @nerzhul
