### ISSUE TITLE
Segmentation fault on minetestserver. When punching entities.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#4586]
Hi, my server is on commit 667975f

Well, @SmallJoker and me were testing boost cart https://github.com/minetest/minetest_game/issues/1311#issuecomment-252000328 and I noticed that when trying to shift click to collect the cart or punching it, when it was moving, caused the server to set fault, that happened for 3 or 4 times in a row, however, I couldn't reproduce the bug intentionally, so we need more help in narrowing and tracking this down.

**Comment by Fixer-007** [comment]
Build debug build and use GDB.

**Comment by Megaf** [comment]
This weekend I will try to run a local copy of my server with GDB.

**Comment by Megaf** [comment]
@SmallJoker @Fixer-007 Was this ever fixed? Or at least could anyone reproduce this bug?

**Comment by Fixer-007** [comment]
Had no problems with carts...
