### ISSUE TITLE
Puff ore bug

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#4590]
Unable to modify in anyway(form) the puff ore, even with nd_puff_bottom, always looks like a flat 1/4 circle, thin of 2 blocks, with no conection with the environement around. Is it intended.

**Comment by paramat** [comment]
Could you make the ore default:meselamp (so it can be seen underground) and show a screenshot?

**Comment by paramat** [comment]
I'll test too, this is a new ore type by hmmmm with no helpful docs on how noise should be set.

**Comment by paramat** [comment]
![screenshot_20161007_192325](https://cloud.githubusercontent.com/assets/3686677/19201019/ca547b1e-8cc3-11e6-9e19-ab02e5ea6305.png)

Works as intended.
```
	minetest.register_ore({
		ore_type        = "puff",
		ore             = "default:meselamp",
		wherein         = {"default:stone"},
		y_min           = -31000,
		y_max           = 31000,
		noise_threshold = 0.0,
		noise_params    = {
			offset = 0,
			scale = 2,
			spread = {x = 32, y = 32, z = 32},
			seed = 316,
			octaves = 3,
			persist = 0.5
		},
		np_puff_top    = {
			offset = 8,
			scale = 4,
			spread = {x = 8, y = 8, z = 8},
			seed = 692234,
			octaves = 1,
			persist = 0.0
		},
		np_puff_bottom    = {
			offset = 8,
			scale = 4,
			spread = {x =8, y = 8, z = 8},
			seed = 90001,
			octaves = 1,
			persist = 0.0
		},
	})
```

**Comment by azekillDIABLO** [comment]
ah, we use np_puff_top like that.... sorry. But at least would need a far better documentation than 2 lines

**Comment by paramat** [comment]
Yes i might improve ore docs, they're not clear. I had to read the code to work out how to set noise params.
