### ISSUE TITLE
Empty tooltip displayed on top left corner

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#4592]
![image](https://cloud.githubusercontent.com/assets/17685062/19204197/a5075328-8cdb-11e6-8b67-8a34ab29fb17.png)
ckeck the top of the screen. where minetest 4.14 is supposed to be written. It has agreen thing with border that hide it. does with all games the same issue,and goes off after loading the overlay and header of the menu.

**Comment by whitephoenix0** [comment]
Do you still see it when you disable your games and mods?

**Comment by azekillDIABLO** [comment]
it works nappens even if no mod, even without worlds generated.

**Comment by Wuzzy2** [comment]
I am pretty sure the green thing is a tooltip gone wild.
I have seen such a tooltip in different situations, so I can partially confirm this weirdness.
I may report back when I know more about this.

**Comment by raymoo** [comment]
I have figured out one way to reproduce this. It happens if a tooltip is displayed (because the pointer is on top of something), and the formspec is updated. I found this with the Mineclone 2 furnace formspec, by hovering over the "craft guide" button while something was cooking.

**Comment by Wuzzy2** [comment]
Yes, I can confirm this, too. Nice observation.

Another way to reproduce this is by using the Help modpack (https://forum.minetest.net/viewtopic.php?f=9&t=15912&p=240152). If you go to any help entry, click on a next/previous button, keep your mouse cursor on top of that button, and then press *space bar* to press the button repeatedly, then the lop left tooltip will appear again.
