### ISSUE TITLE
Interesting bug with nodeupdate(pos)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4594]
![screenshot_20161007_222002](https://cloud.githubusercontent.com/assets/3686677/19206074/6954391a-8cde-11e6-87ef-11e2542ba86a.png)

^ During sand collapse.

![screenshot_20161018_040348](https://cloud.githubusercontent.com/assets/3686677/19462971/1aa7548e-94e8-11e6-9d47-c2024fd43d56.png)

While experimenting with an ABM to make unsupported sand nodes collapse using `nodeupdate(pos)` i occasionally experienced huge areas of supported sand collapsing in on itself, often leaving hundreds of black spinning sand entites just below surface level.
The new flat area created is the top of y = -1, so is the top surface of mapblocks.
Terminal is spammed with hundreds of error messages like those seen at top of screen.

```
minetest.register_abm({
    nodenames = {"default:sand"},
    neighbors = {"air"},
    interval = 2,
    chance = 128,
    catch_up = false,
    action = function(pos, node)
        nodeupdate(pos)
    end
})
```

The same ABM with `nodeupdate_single(pos)` does not trigger this, so it seems to be something to do with recursion.

**Comment by t4im** [comment]
Ah, Sandslides. I actually have a started fix for this somewhere in my git stash. Needs likely some rebasing though.

**Comment by sofar** [comment]
The algorithm is not recursive anymore since my changes to it a few months back.

**Comment by Ekdohibs** [comment]
@paramat The problem is caused by the falling code creating hundreds of entities, one for each falling node, and therefore going over the static object limit. To fix that, we would need to handle falling nodes in a better way, probably putting it in the engine.

**Comment by paramat** [comment]
#4630 seems to fix the sand collapses.
#4648 is merged.

**Comment by paramat** [comment]
Don't know why i closed this, fix not merged yet.

**Comment by paramat** [comment]
#4740 merged.
