### ISSUE TITLE
Minetest GUI isn't flexible for long translations

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#4607]
Can be seen here https://postimg.org/image/wiqniu9hn/
Toggle unfortunately takes two words to write in Serbian, as there is no word for it (or at least I can't think of it). To save you a click, the text overlaps between the lines. It would be nice if we could have a bit more space there. Thanks.

**Comment by Wuzzy2** [comment]
This needs to be taken into account when the main menu and controls menu will be completely redesigned (which will happen sooner or later, I hope).

**Comment by Fixer-007** [comment]
>It would be nice if we could have a bit more space there.

It is half-measure. It is hiding the problem of long text, it can be solved in various ways: 
1) truncate long words with three ... added and show tooltips for long words when holding cursor over it.
2) start a new line
3) ???

**Comment by Wuzzy2** [comment]
More space is still very crucial. The space in many menus, especially in controls, it *very* tight. Give translators more space to breathe. :-)

“…” is still a loss of information, it only prevents the GUI from breaking.
Line breaks obviously make sense, but they are not always possible.

Anyway, I'm sure we'll find a way.

**Comment by raymoo** [comment]
Another solution: have a GUI system that will resize components so that they are big enough to fit their contents.

**Comment by tacotexmex** [comment]
Is the silent agreement to wait on #6527 for most formspec related issues?

**Comment by v-rob** [comment]
Merging this into #13748, since that one is more general.
