### ISSUE TITLE
F11 and ALT+ENTER should both toggle windowed/fullscreen

### ISSUE THREAD

**Issue by JonasT** [minetest/minetest#4609]
Please make both F11 (the modern choice) and if possible also ALT+ENTER toggle windowed/fullscreen. I spend 5 minutes looking around how to simply change to fullscreen and couldn't figure it out, which is somewhat silly. It would be great if this could be improved to be easier to find with supporting those common shortcuts to do it.

**Comment by everamzah** [comment]
There's fullscreen via the window manager, and then separately, fullscreen via Irrlicht.  They're not the same, but I've been using Alt+F11 on Xfce for a while.  I agree it's frustrating, but found personally that fullscreen via the window manager worked better anyway.  Perhaps it's the same, or the reverse, but I'm not sure.

**Comment by Calinou** [comment]
> There's fullscreen via the window manager, and then separately, fullscreen via Irrlicht. They're not the same, but I've been using Alt+F11 on Xfce for a while. I agree it's frustrating, but found personally that fullscreen via the window manager worked better anyway. Perhaps it's the same, or the reverse, but I'm not sure.

I don't think that exists on Windows or macOS, so an universal fullscreen toggle should be added. Moreover, not all desktop environments enable a shortcut for fullscreen by default (KDE doesn't, for example).

**Comment by JonasT** [comment]
FWIW: I'm reporting this from Linux, and GNOME 3 seems convinced that the window isn't resizable at all, so there's no way to toggle anything via the window manager there. So even for Linux, I think relying purely on some window manager shortcut that might or might not be there is a bad idea. (and many Linux games have their own built-in toggling via F11)

**Comment by t4im** [comment]
> GNOME 3 seems convinced that the window isn't resizable at all, so there's no way to toggle anything via the window manager there

Resizing/Maximizing Minetest in window mode works perfectly by default here on GNOME 3.
Fullscreen by window manager is possible, too, although there is no shortcut by default for that, unless an application defines one.

I've hacked myself something in javascript together for a global shortcut, even without application support.

```javascript
 global.display.focus_window.make_fullscreen()
```

But it works even better than most engine provided fullscreens, which usually handle multi-monitor setups very badly and enforce monitor resolutions, sometimes unnecessarily.

**Comment by kahrl** [comment]
Last time I checked (it's been a few years), the only way to toggle fullscreen in Irrlicht was to recreate the Irrlicht device. This invalidates all objects that are managed by the device, such as textures, models, the scene graph, GUI elements, etc... The engine code isn't prepared at all to recreate all of those objects on demand at any random point, so implementing fullscreen toggle might be quite non-trivial.

**Comment by JonasT** [comment]
@kahri what about if it uses the modern borderless on-top window fullscreen? Since the window is already resizable right now, I don't see why that should be much harder to do. Many modern games don't bother to enter the proper oldschool fullscreen anymore, e.g. not even SDL2 as THE widespread, somewhat conservative base lib for many game engines does it anymore as a default - so that is what I would suggest doing here as well.

**Comment by paramat** [comment]
For simplicity i think we should just have the one control, F11, for fullscreen, perhaps it should be added to controls docs?

**Comment by everamzah** [comment]
It's gonna conflict with some people's F11, I fear.  By the way, didnd't fullscreen = 1 require a restart?

**Comment by paramat** [comment]
Good point, i don't think i know what i'm talking about.

**Comment by kahrl** [comment]
@JonasT I think that should work. While Irrlicht doesn't have a method to resize/move the window, it provides access to the raw X11 window handle or HWND, so the window could be resized/moved using platform specific code.

**Comment by JonasT** [comment]
@everamzah I don't think any game or application on Linux cares about that. Generally the application is expected to handle fullscreen change itself, and if the window manager wants to do something else with F11 it's the window manager's business to somehow interject the key and make it work. So I don't think there should be much of a problem

**Comment by everamzah** [comment]
Yes, and it occurred to me later that many programs use F11 just fine, and
that there exists "fullscreen direct overlay" or some such, and that that
is usually well supported, and overrides compositing, etc.  That's my
general understanding, anyway.

**Comment by rubenwardy** [comment]
#2732
