### ISSUE TITLE
Attaching entities cause assertion fail

### ISSUE THREAD

**Issue by Foghrye4** [minetest/minetest#4610]
Attaching player entities cause assertion fail on checking `m_cao == __null' at localplayer.h:96
Commit causing problem: 
> commit ad163ee5c3f7d6ca31e0add052fb76466a9bfcc8
> Author: Foghrye4 <foghrye4@gmail.com>
> Date:   Sat Oct 8 16:51:25 2016 +0400
> Prevent attached models from disappearing during parent reload (#4128)

Possible line causing error:
https://github.com/minetest/minetest/blob/1b450861f01eef98c7d4f7810724d6bec7423a7c/src/content_cao.cpp#L1764
Error log: http://pastebin.com/saphcxDm

PS: Sorry ( -._.-)

**Comment by sfan5** [comment]
was fixed by #4611
