### ISSUE TITLE
Main menu tab icons

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#4613]
The titles of the tabs Singleplayer, Client, Settings, etc. are currently shown as plain text,
icons could be used and the titles can be changed to tooltips (shown when the mouse cursor is moved onto it and kept quiet).

Singleplayer: Sam looking at you
Client: more Sams on the icon
Server: idk yet
Settings: a simple gear icon
Texturepacks: idk yet
Mods: piece of a puzzle (See the Add-ons icon of firefox)
Credits: the minetest logo

**Comment by paramat** [comment]
The icon suggestions are less clear than words are.

**Comment by SmallJoker** [comment]
Additionally, we have enough space in the GUI to use text. We could put the icon in front of the text but that's not required IMO.

**Comment by rubenwardy** [comment]
Icons are less clear. It would be much better to use better names for the tabs like "join" and "host",  or combine the tabs into one called "multiplayer" with a host button to show the host tab

**Comment by Wuzzy2** [comment]
Why not icon + text?

**Comment by HybridDog** [comment]
How about making it configurable to text only, icon+text and icon with tooltip?

**Comment by rubenwardy** [comment]
both those suggestions would be okay - with icon+text as default

**Comment by paramat** [comment]
Icon plus text is overcomplex and unnecessary, adding options even more so. Tooltips are unnecessary, if the tabs are unclear to a newbie the player will soon find out after a few clicks.
:-1: To all suggestions.

**Comment by rubenwardy** [comment]
icons are the least of the main menus problems, we need a more game like menu
