### ISSUE TITLE
Header guards use identifiers reserved for the compiler/library implementation

### ISSUE THREAD

**Issue by elfring** [minetest/minetest#4616]
I would like to point out that identifiers like "[`_CLIENTIFACE_H_`](https://github.com/minetest/minetest/blob/edba6e50d9c9c0a7120c251bed36a87b51f4c826/src/clientiface.h#L19)" and "[`__CONVERT_JSON_H__`](https://github.com/minetest/minetest/blob/b88595050f3af5ccac06aac331ead4ebdcb9deb9/src/convert_json.h#L20)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by nerzhul** [comment]
No, thanks

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by ShadowNinja** [comment]
This should be fixed, and it's pretty trivial to do so; you just have to go through a bunch of files.

**Comment by Ekdohibs** [comment]
Closing since we now use `#pragma once`.
