### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [minetest/minetest#4617]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null) like the following.
- [ClientLauncher](https://github.com/minetest/minetest/blob/b88595050f3af5ccac06aac331ead4ebdcb9deb9/src/client/clientlauncher.cpp#L70)
- [QueuedMeshUpdate](https://github.com/minetest/minetest/blob/70f104be076321330a0827010704761a040d8ec7/src/client.cpp#L69)
- [SharedPtr::drop](https://github.com/minetest/minetest/blob/b88595050f3af5ccac06aac331ead4ebdcb9deb9/src/util/pointer.h#L86)

**Comment by nerzhul** [comment]
@elfring thanks for the modifications you pointed. Please make a PR

**Comment by elfring** [comment]
I imagine that it would be nice if desired software improvements could also be achieved by the usage of classes like "[std::unique_ptr](https://github.com/minetest/minetest/issues/4618 "Improve exception safety with smart pointers")" and "[std::shared_ptr](https://isocpp.org/wiki/faq/cpp11-library#shared-ptr "FAQ: shared_ptr")", wouldn't it?

**Comment by QrchackOfficial** [comment]
Added PR https://github.com/minetest/minetest/pull/5914

**Comment by nerzhul** [comment]
@elfring yes we can use those C++11 class now we are C++11 compatible

**Comment by elfring** [comment]
I am curious how this software will be improved further with the reuse of current C++ functionality.

**Comment by rubenwardy** [comment]
bump

**Comment by paramat** [comment]
PR was merged, can thsi be closed?

**Comment by SmallJoker** [comment]
`delete` fixed.
