### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [minetest/minetest#4618]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr)"?

Update candidates:
- [MapgenV5](https://github.com/minetest/minetest/blob/b88595050f3af5ccac06aac331ead4ebdcb9deb9/src/mapgen_v5.cpp#L48)
- [MapgenValleys](https://github.com/minetest/minetest/blob/b88595050f3af5ccac06aac331ead4ebdcb9deb9/src/mapgen_valleys.cpp#L67)

**Comment by sfan5** [comment]
Are you a bot? o.O

**Comment by est31** [comment]
Needs C++11 so it won't be added to soon.

**Comment by elfring** [comment]
How do you think about [interfaces from a class library like "boost"](http://www.boost.org/doc/libs/1_62_0/libs/smart_ptr/smart_ptr.htm "Smart Pointers")?

**Comment by est31** [comment]
No, boost is no option.

**Comment by nerzhul** [comment]
boost is not an option and we are not C++11 minimum compatible atm. Also if we know the lifetime of our values it's useless. only case i see is packets + exception handling

**Comment by nerzhul** [comment]
I close it as it's not time to move to Full C++11 support or we won't use boost

**Comment by elfring** [comment]
* Would you like to use utilities from other class libraries any more?
* How do you think about to reopen this issue when you would dare to reuse more functionality from the current C++ standard?

**Comment by elfring** [comment]
How do you think about to [reconsider remaining update candidates](https://github.com/minetest/minetest/blob/cde2a7f6f24f638421238ead4e61b155322fefc8/src/mapgen/mapgen_carpathian.cpp#L53 "Update candidate: MapgenCarpathian class")?
