### ISSUE TITLE
Falling nodes stop falling.

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest#4619]
I you place a falling node in a place where it will have a long fall, it will stop falling before it hits the ground.
You can also drop more and more and they will all stop in the same spot.
If you fly down it will fall a little more.

**Comment by RHRhino** [comment]
This is already known. It happens every time when the falling node reaches an area or chunk which is not loaded/generated.

**Comment by paramat** [comment]
It has to stop because the unloaded / ungenerated block may contain solid nodes.
