### ISSUE TITLE
Player falls through slab/stair stairs occasionally when going up

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4621]
When you go upstairs or upslabs you can fall through them or get stuck on block below them. It happens randomly.

It is old and very annoying bug that happens occasionally, not all people know about it because they don't use stairs or slabs often or walk rarely on them.

Examples:
Stone slabs just before player, you go on them, and instead of bumping you up, you go down again and stuck before higher stone block.
![u7kzziz](https://cloud.githubusercontent.com/assets/16494741/19251055/22879058-8f46-11e6-8e7d-97dff74ecc12.png)
Even better example, by simply walking on this few times you are going to fall through such slabstairs.
![to_fix_in_this_century2016](https://cloud.githubusercontent.com/assets/16494741/19251056/22c2ea54-8f46-11e6-9728-8ebaf5c2537e.png)

Sometimes this happens on stairs I believe. So don't ever use slab-stairs or stairs as... stairs above lava or other dangerous places. Combining slabs, stairs, full blocks may induce even more headache.

**Comment by JurajVajda** [comment]
Yes this happens to me too, sometimes too often.

**Comment by everamzah** [comment]
Same here.  It's been going on for a bit now, around the time of the "jumping at node edges" phenomenon.

**Comment by Fixer-007** [comment]
You can reproduce it much easier by making stairs down to underground and then going up and get stuck often, like this:
![stuck](https://cloud.githubusercontent.com/assets/16494741/20246856/858cade0-a9c8-11e6-8599-ba0756dd31ad.png)

**Comment by Fixer-007** [comment]
I've actually tested this on singleplayer with very long stairs, but I'm planning to test more. Is this code purely client-side?

**Comment by JRottm** [comment]
@Fixer-007: Yes, singleplayer should be fine.

If this PR really fixed it you should still be able to reproduce the bug when checking out the commit immediately before the change (e63df5ce80eb1a0955e04f75ce8f72f119dc5f3c), but the bug should be gone with commit 248a1a8d65c483edcab328d898cc570071d6a182. I'm keeping my fingers crossed. :-)

**Comment by Fixer-007** [comment]
This problem of going into slab still happens:
![default](https://user-images.githubusercontent.com/16494741/29191037-f94f108e-7e24-11e7-98c3-c8e407bd37d1.png)

**Comment by JRottm** [comment]
> problem of going into slab still happens

:-(

> this yaw is most problematic

Ah, ok. Because I just built the mother of all endless stairs, but couldn't reproduce anything, either with or without the PR. But my stair is straight, so I did it wrong.

Ah, well. Many thanks for checking!

**Comment by Fixer-007** [comment]
Stairs itself work ok (at least in singleplayer, in multiplayer 0.4.14 i had problems), but certain slab-stairs is still a problem even on singleplayer it seems.

**Comment by IhrFussel** [comment]
Wiull you ever fix this?!

It makes certain build styles problematic.

What if I want to build a PvP arena with stairs?

And what if I want to build something large with slabs as stairs?

Falling through happens a lot of times there and is unacceptable.

**Comment by SmallJoker** [comment]
This bug is related to the collision detection, probably the code lines here:
https://github.com/minetest/minetest/blob/922e6ff57ec9f07d2ff04cf010821c1ddd00831e/src/collision.cpp#L582-L583
It eases players to jump onto nodes and smoother movement (bounce?).

**Comment by rubenwardy** [comment]
I've had this happen to me once

**Comment by LoneWolfHT** [comment]
Sometimes when jumping on the corners of full sized nodes I fall into them. Might be the same bug?

**Comment by ClobberXD** [comment]
#metoo. I always fall into a full-sized node at least once every time I play.

**Comment by style-nine** [comment]
> This bug is related to the collision detection, probably the code lines here:
> 
> https://github.com/minetest/minetest/blob/922e6ff57ec9f07d2ff04cf010821c1ddd00831e/src/collision.cpp#L582-L583
> 
> It eases players to jump onto nodes and smoother movement (bounce?).

How to go about fixing it, though? You can't just comment out the code.

**Comment by sfan5** [comment]
Please check recent versions, there has been a collision rework some time ago.
