### ISSUE TITLE
Collision detection code is extremely inefficient for larger speeds

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest#4623]
The collision detection code is extremely inefficient for larger entity velocities. The memory consumption and processing time of the code easily and unneccessarily increase quadratically with velocity (or actually: with the magnitude of `velocity * dtime`), while the worst case is a cubic increase.

A while ago (commit 6b8435cf, in april 2013), the max speed was limited to 500 to solve a perceived hang. While it is probably impossible to determine what was the cause at the time, currently, a very high speed object, especially one moving at an angle, will cause excessive processing time, which can be mistaken for a hang; using a debugger, it can be determined that the collision detection loop _is_ making progress...

Personally, I have observed consistent huge processing delays and predictable `std::bad_alloc` crashes (in a 32 bit environment) with only a single entity, traveling at a speed of 2000. At larger speeds, processing time will be cubically worse.

So the collision detection code ought to be revised / improved.

---

_Edit: reworded the issue. Some of the comments below may no longer be relevant as a result..._

**Comment by paramat** [comment]
Are you requesting a max velocity of 500? This is unclear.

**Comment by Rogier-5** [comment]
@paramat: clarified (hopefully)

**Comment by paramat** [comment]
So you're asking for performance improvement of collision code, that will have to be improved before max velocity is increased.

**Comment by Rogier-5** [comment]
Primarily, I wanted to document the fact that there is a severe performance issue in the collision detection code, and that as a consquence, the max velocity is limited, which seems undesirable.

If I get around to it, I may even fix the collision detection code myself. I get the impression it has other issues as well...

In practise, I think few objects will need speeds in excess of 500, however, if the there is serious (I tested 1s) lag, a single entity with a speed of 500 already causes a 4-second computational delay on my computer. This in turn would cause other high-speed entities to experience lag, etc.

**Comment by C1ffisme** [comment]
How fast can you go at 500? The world is only about 64000 blocks long, so do you need to travel that fast anyway?

**Comment by paramat** [comment]
Issue title is a little unclear, could you include the request for more performance in collision detection?

**Comment by rubenwardy** [comment]
Entity collision performance has been improved, not sure if it solves the issue however

**Comment by paramat** [comment]
It's partly non-trivial as the collisionboxes within range of the next player step movement must be checked, which inevitably increases with speed.

**Comment by paramat** [comment]
No point having an issue asking for collision performance improvement, that's obvious and will be done if possible. It's also very difficult and to a degree impossible due to what i write above.
