### ISSUE TITLE
Mouse vertical sensitivity

### ISSUE THREAD

**Issue by adrienhenry** [minetest/minetest#4629]
I just installed Minetest on Archlinux .

The default setting give me a highly sensitive mouse.  Reducing the **mouse_sensitivity** helps on the horizontal axis but not the vertival axis.
When I lift a little bit my mouse, I find myself facing the sky and any other move (left or right) make me spin on myself. Same thing happend when facing the floor.
I found similar issues for the global sensitivity but none concerning the vertical sensitivity, is this a known issue ?

**Comment by sfan5** [comment]
Doesn't happen here, Arch too. This definitely seems to be a bug and not just a case of sensitivity being set too high.

**Comment by est31** [comment]
@adrienhenry if you are using wayland or mir its a dupe of #1763 . Otherwise I haven't heard of the behaviour happening on X11.

**Comment by adrienhenry** [comment]
Hello,
Thanks for your answers!
@est31 I am using X11.
I changed the mouse and with a very low sensitivity(0.005) it works fine. I still have some trouble to leave the position facing top or facing down(the two poles views). Moving the mouse tends to make me spin but with some percistance I can make my view leave the pole.

**Comment by hoosierEE** [comment]
Same here, Ubuntu 16.04, using X11 on a Chromebook via the [crouton extension](https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom).

For me, the issue appears to be related to the mouse's relative position within the viewport.

For example if I have the game *not* full-screened, then if the mouse pointer is near the edge of the window, the crazy spinning around the z-axis gets worse.  As I bring the mouse pointer nearer the center of the game window, it gradually gets better until it's "normal" within a few pixels of absolute center.

Does it in full-screen mode too.

**Comment by Fixer-007** [comment]
Another player has similar issue, minetest 0.4.16+repack-4 on Debian Sid, reported here http://irc.minetest.net/minetest/2018-01-31#i_5217921

**Comment by xavierog** [comment]
Hi,

> Another player has similar issue

and I am that other player -- after further investigations, I was able to pinpoint the exact culprit: when my Desktop Environment starts, it runs various scripts of mine, including one that configures the mouse through the "xinput" utility. Specifically, it adjusts the coordinate transformation matrix for that input device.

Therefore, here is how I can perfectly reproduce the "spinning around Z-axis" issue:

- launch Minetest, select a world and click "Play game";
- assuming you are not affected by the issue, everything should be alright;
- check <code>xinput --list</code> to determine the input device name for your mouse (typically right under "Virtual core XTEST pointer")
- run the following command: <code>xinput --set-prop "${YOUR_POINTER_DEVICE}"  'Coordinate Transformation Matrix' 1.6 0 0 0 1.6 0 0 0 1</code>
- the slightest mouse movement in the game should make you spin around the Z-axis;
- the spinning can be stopped by restoring the transformation matrix: <code>xinput --set-prop 'Logitech USB-PS/2 Optical Mouse'  'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 1</code>

**Comment by avoidr** [comment]
I confirm that @xavierog's method works.

**Comment by paramat** [comment]
So a hardware problem.

**Comment by avoidr** [comment]
That's not what I would conclude so easily. The "problematic hardware" works in all other cases, except with Minetest with changed transformation matrix. To me that looks like a problem in Minetest or one of its dependencies. Unless I am really lucky to have the same bug in all other software I use.
