### ISSUE TITLE
Texture pack in /usr/share/minetest/textures does't load

### ISSUE THREAD

**Issue by guoyunhe** [minetest/minetest#4634]
If I copy texture pack to ~/.minetest/textures folder, it loads.

If I copy texture pack to /usr/share/minetest/textures folder, it doesn't load.

I am trying to build RPM packages for mods and textures, so texture pack must be installed in /usr/share/minetest/testures folder.

**Comment by sfan5** [comment]
Most likely only the `path_user` is considered for texture packs.

**Comment by est31** [comment]
This is a good thing to consider for the next release.

**Comment by yyt16384** [comment]
Related: #3953

**Comment by paramat** [comment]
Bump, needed for release?

**Comment by sfan5** [comment]
@paramat 
would be nice but not required
