### ISSUE TITLE
Don't ship with broken languages

### ISSUE THREAD

**Issue by est31** [minetest/minetest#4638]
There are a few languages which are broken in minetest, like hebrew, as minetest doesn't support RTL and doesn't ship a font that supports hebrew. The issue can be seen as a packaging problem, and left to people creating minetest executables, but in the best case it'd be managed in the master branch, as packaging should be as trivial as possible.

An English fallback is in this case much better than a broken language support because Minetest at least is usable.

Languages confirmed to work/not work: (complete list)
- [x] : English, obviously
- [ ] : Belarusian, translations seem empty
- [x] : Catalan, looks fine to me (@sfan5)
- [x] : Czech, already in minetest for a long time
- [x] : Danish, already in minetest for a long time
- [x] : German, already in minetest for a long time
- [x] : Esperanto, looks fine to me (@sfan5)
- [x] : Spanish, already in minetest for a long time
- [x] : Estonian, already in minetest for a long time
- [x] : French, already in minetest for a long time
- [ ] : Hebrew, confirmed broken on IRC (fonts, RTL)
- [x] : Hungarian, already in minetest for a long time
- [x] : Indonesian, looks fine to me (@sfan5)
- [x] : Italian, already in minetest for a long time
- [x] : Japanese, confirmed by @sfan5
- [x] : Lojban, looks fine to me (@sfan5)
- [ ] : Korean, confirmed broken by @sfan5 (fonts)
- [ ] : Kyrgyz, confirmed broken by @sfan5 (fonts)
- [x] : Lithuanian, looks fine to me (@sfan5)
- [x] : Norwegian, already in minetest for a long time
- [x] : Dutch, already in minetest for a long time
- [x] : Polish, already in minetest for a long time
- [x] : Portuguese, already in minetest for a long time
- [x] : Portuguese (Brazil), already in minetest for a long time
- [x] : Romanian, already in minetest for a long time
- [x] : Russian, already in minetest for a long time
- [x] : Serbian (Cyrillic), looks fine to me (@sfan5)
- [x] : Swahili, looks fine to me (@sfan5)
- [x] : Turkish, looks fine to me (@sfan5)
- [x] : Ukrainian, confirmed by @Fixer-007
- [ ] : Chinese (simplified), ???
- [ ] : Chinese (traditional), ???

**Comment by est31** [comment]
Making this a blocker, as minetest is not usable with those locales.

**Comment by est31** [comment]
One way to "fix" this issue would be to remove the locale files for the affected languages, but it would be cool if they could be kept for when minetest adds support for those locales.

A much better fix would be to make a whitelist of confirmed working languages which then is used as part of the build process.

**Comment by paramat** [comment]
Still a blocker?

**Comment by est31** [comment]
@paramat yes.

**Comment by paramat** [comment]
See #4637

**Comment by paramat** [comment]
Could someone make a simple workaround? Just make it as if these languages are not supported, then we fix properly later.

**Comment by paramat** [comment]
I'm referring to this:

> est31 	We still need to 1. find out which languages are broken and 2. find a way how to disable broken languages
06:37 		because https://github.com/minetest/minetest/issues/4637
06:38 		https://github.com/minetest/minetest/issues/4638
06:38 	sfan5 	just move the translation files somewhere else is easiest probably

**Comment by est31** [comment]
See this issue: #4940
