### ISSUE TITLE
[discuss] free-move sky color in caves

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4640]
I know it's by design, and I think this came up before, but with the current logic that always has the default sky color when free-move is enabled it looks dorky in caves (invisible portions of the cave are bright).

As a test I disabled that logic to see what would happen with free-move enabled and it looks fine in all cases I tested (above ground day/night, in large caves day/night) - much better than what Minecraft does in fact.

As there was specific code to do that, I'm sure there's a good reason and I'm missing something.
Perhaps performance?

Anyway, if anybody wanted to try as well here is a super trivial patch to do that:
```
diff --git a/src/game.cpp b/src/game.cpp
index ed2673c..ad8536f 100644
--- a/src/game.cpp
+++ b/src/game.cpp
@@ -4097,17 +4097,12 @@ void Game::updateFrame(ProfilerGraph *graph, RunStats *stats,
        float direct_brightness;
        bool sunlight_seen;
 
-       if (g_settings->getBool("free_move")) {
-               direct_brightness = time_brightness;
-               sunlight_seen = true;
-       } else {
-               ScopeProfiler sp(g_profiler, "Detecting background light", SPT_AVG);
-               float old_brightness = sky->getBrightness();
-               direct_brightness = client->getEnv().getClientMap()
-                               .getBackgroundBrightness(MYMIN(runData->fog_range * 1.2, 60 * BS),
-                                       daynight_ratio, (int)(old_brightness * 255.5), &sunlight_seen)
-                                   / 255.0;
-       }
+       ScopeProfiler sp(g_profiler, "Detecting background light", SPT_AVG);
+       float old_brightness = sky->getBrightness();
+       direct_brightness = client->getEnv().getClientMap()
+                       .getBackgroundBrightness(MYMIN(runData->fog_range * 1.2, 60 * BS),
+                               daynight_ratio, (int)(old_brightness * 255.5), &sunlight_seen)
+                           / 255.0;
 
        float time_of_day = runData->time_of_day;
        float time_of_day_smooth = runData->time_of_day_smooth;
```
I'll run with this change going forward (my son and I like to fly around in Nether :) ).
Feel free to close if this is 100's time this came up.

**Comment by Wayward1** [comment]
Actually, if I'm understanding you correctly, the issue you're reffering to has had several people asking for its removal, including here: https://github.com/minetest/minetest/issues/4187

**Comment by Fixer-007** [comment]
I don't know the reason but it is annoying thing for sure. Can you make a PR for this?

**Comment by lhofhansl** [comment]
Perhaps the background should default to sky only when no-clip is enabled; because that does look a but strange (when you look down everything is black, if you look up it suddenly is bright).

I'll do a PR and we can discuss there.

**Comment by lhofhansl** [comment]
Yeah testing like this is best:
```
	if (client->checkPrivilege("fly") &&
	    g_settings->getBool("free_move") &&
	    client->checkPrivilege("noclip") &&
	    g_settings->getBool("noclip")) {
```

Only when both noclip and fly privileges are given _and_ both free_move and noclip are enabled would we should the time-default sky. PR coming.
