### ISSUE TITLE
Don't print 'forcing delete' messages to screen

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4648]
![screenshot_20161018_043327](https://cloud.githubusercontent.com/assets/3686677/19504073/8c60563a-95af-11e6-9a1e-9b67dc374508.png)

Large collapses of sand or gravel can cause force-deletes as the limit of 49 per mapblock is fairly low.
Printing to screen in red letters seems overkill for something that is not a big deal and not a bug.
I might attempt a PR for this.
Relevant code https://github.com/minetest/minetest/blob/master/src/environment.cpp#L2179

**Comment by sfan5** [comment]
Downgrade it to a warning maybe?

**Comment by est31** [comment]
What about just raising the level to something larger?

The solution is not to make minetest ignore it, the solution is to fix it.

**Comment by sfan5** [comment]
Not sure whether increasing the limit is the correct solution. 49 objects in a 16x16x16 square is already a lot, that limit seems appropriate to me.

**Comment by stujones11** [comment]
Why 49 anyway? I have often thought that limit should be increased, what problems would that be likely to cause? I reckon 256 makes more sense as this is one complete slice of a 16x16x16 area.

**Comment by paramat** [comment]
Will downgrade to a warning.

**Comment by paramat** [comment]
I guess 0 is counted so this means 50 objects.
Raising the default limit can be considered too, but even if raised the excess will still happen so this is still needed.

**Comment by stujones11** [comment]
I agree with the downgrade to warning regardless of the limit. I guess increasing the limit is another issue.

**Comment by MoNTE48** [comment]
It seems to me that the increase in the limit of a stupid idea. On the weak device is greatly lowers FPS.

**Comment by paramat** [comment]
The limit is the number of objects stored in the world database, it doesn't affect FPS.

**Comment by MoNTE48** [comment]
@paramat Is not the number of objects that can be simultaneously stored in the chunk? For example mobs?

**Comment by paramat** [comment]
Correct, you can have much more than 49 objects active in a mapblock if players are nearby, the warning is printed as part of `void ServerEnvironment::deactivateFarObjects(bool force_delete)` https://github.com/minetest/minetest/blob/master/src/environment.cpp#L2034

**Comment by est31** [comment]
63a3bb229a9ff288ab01e3e80c8477da5e84ee1e
