### ISSUE TITLE
Chatbox opacity ?

### ISSUE THREAD

**Issue by fwhcat** [minetest/minetest#4650]
To read the in-game chat is sometimes hard because of what we are currently seeing, the contrast is sometimes not important enough to read easily the text. We do have F10 which is great, as it both show a lot of text lines, and have a background with a nice opacity.

My suggestion is to set such an opacity on the in-game chat, on the top-left corner so that we wouldn't have to use F10 a lot.

What do you think? Don't hesitate to post your opinion.

**Comment by paramat** [comment]
A more subtle tint might be acceptable.

**Comment by Ferk** [comment]
Instead of having a semi-transparent background box (which is what I think you are suggesting), I'd prefer if the font style itself had some background (or outline.. but not sure if irrlicht supports any of those).

Otherwise when you are playing singleplayer it would be annoying to have an empty square in the corner all the time, as you won't get many text messages.

Perhaps the F2 button could cycle between "chat hidden", "chat shown" and "chat boxed" or something.
Or perhaps this could be a mod thing if the chat box was a HUD element mods could manipulate.

**Comment by Wuzzy2** [comment]
Why don't you just edit the `console_alpha` setting?

**Comment by rubenwardy** [comment]
we have console_alpha

**Comment by paramat** [comment]
> My suggestion is to set such an opacity on the in-game chat, on the top-left corner

I suspect this means the in-game chat that appears top left, not 'T' or 'F10'.
However if so i'm :-1: because we already have 2 other ways to see chat with a dark background.

**Comment by fwhcat** [comment]
@paramat totally what I meant.

**Comment by Fixer-007** [comment]
Chat needs to be redesigned in general I think, current drop down to type is UI-wise silly. Having chatbox opacity configurable is good thing.

**Comment by paramat** [comment]
However, the in-game chat at top left is meant to not obscure the view of the world, so i think low priority.

**Comment by benrob0329** [comment]
I believe adding a small drop shadow would help improve readability by quite a bit.

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by paramat** [comment]
Any background added would have to be per-line, to not show an empty box when there are no messages.
Otherwise we could have a drop shadow (iff possible).

**Comment by Ezhh** [comment]
If going the drop shadow route, please make it optional. I don't have any trouble reading the text as it is and would find it really annoying.

**Comment by paramat** [comment]
^ I agree with that, i wouldn't like the appearence drop shadow personally.

**Comment by Calinou** [comment]
The default font used by chat already has a drop shadow (`font_shadow_alpha`, defaults to 127 and can be set up to 255).
