### ISSUE TITLE
Mapblock deserialization code is probably inefficient

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest#4654]
While playing around with compression algorithms (see issue 4495), I discovered that the mapblock deserialization code is probably too inefficient. See the following graphs:

Speed of compression / decompression code:
![plot-decompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19619024/1c722736-985c-11e6-806d-47ba06a132d7.png)
![plot-recompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19619025/1c77bab6-985c-11e6-9ebb-fc716464b9cd.png)

Speed of deserialzation code. Note that while decompression is much faster than compression, deserialization is mostly (much) slower than serialization. The only reason for this I can think of, is the code being unnecessarily inefficient.

![plot-decompress-ser_blocktime](https://cloud.githubusercontent.com/assets/6202053/19619027/286361a4-985c-11e6-9ec4-705a29560a7e.png)
![plot-recompress-ser_blocktime](https://cloud.githubusercontent.com/assets/6202053/19619028/286890ca-985c-11e6-8f59-8cc5e979822e.png)

The issue seems to be in the following functions/methods:
- `correctBlockNodeIds()`, consuming 17% of CPU time (not counting called functions)
  
  (including called functions, `correctBlockNodeIds()` required 71.6% of CPU time of the decompression test).
- `CNodeDefManager::getId()`, consuming 29.5% of CPU time (not counting called functions)
- `__memcmp_ssse3()`, consuming 23% of CPU time, in calls originating from `correctBlockNodeIds()`

**Comment by Megaf** [comment]
Well, from my 5 years of experience in running Minetest servers I can confirm that things related to mapblocks/data being written to disk and read are indeed very CPU intensive. We can easily observe that on low power CPUs, I had a server running on a Raspberry Pi Model B, the first one and it would use 100% of CPU when loading and writing map data. That was not caused by IO wait, it was just something related to the way Minetest deal with mapblocks.
@Rogier-5 Thank you for all the work you have been doing, me as a Minetest admin and player really appreciate that and I'm thrilled in having persons like you in our little community.
@Rogier-5 Now, do you have any idea how to make the mapblock deserialization more efficient? Can you send a PR so I can test it?

**Comment by Rogier-5** [comment]
> Thank you for all the work you have been doing, me as a Minetest admin and player really appreciate that and I'm thrilled in having persons like you in our little community.

@megaf: thanks !

> Now, do you have any idea how to make the mapblock deserialization more efficient?

In terms of concrete improvements: no. I only know in which functions the inefficiency must be, but so far that's all. I had a very quick glance, but saw nothing that was immediately obvious to me.

> Can you send a PR so I can test it?

When I have one, I'll send it of course. I do have a number of existing PRs that are in need of my attention as well...

**Comment by kahrl** [comment]
Would be interesting to see what effect compiling with C++11 has vs. without. (It should be faster with C++11, because `CNodeDefManager::getId()` uses an `unordered_map` when compiled with C++11, since commit 9393e4a0a8e32905d32a9dc58131218aee318686).

**Comment by sofar** [comment]
That are the axes of the graphs? The title suggests that one of the axes is time, but neither axis has a label.

**Comment by Rogier-5** [comment]
@sofar: That is unclear indeed. The graphs are from my tests with compression algorithms. The y-axis is time per mapblock (µs), the x-axis is the compression level of the algorithm.

@kahrl: I have merged the latest master. See the graphs below. There is a 50% improvement, but IMO the deserialization speed should be (much) lower still: block deserialization time is still about a factor 8 slower than block serialization time. See the serialization speed graph for comparison. Looking at the algorithm `none` (no compression), block serialization time is about 60-70 µs, while deserialization time is about 500 µs...

BTW: the graphs were generated using my [compression branch](https://github.com/Rogier-5/minetest/tree/compression). The necessary scripts for re-generating are included.

Deserialization teim per block with C++98:

![plot-decompress-ser_blocktime](https://cloud.githubusercontent.com/assets/6202053/19625875/ebc72e78-9924-11e6-83d5-d41805f918e4.png)

C++11:

![plot-decompress-ser_blocktime](https://cloud.githubusercontent.com/assets/6202053/19625879/f7317a48-9924-11e6-929d-27d45570e300.png)

Serialization (C++11):

![plot-recompress-ser_blocktime](https://cloud.githubusercontent.com/assets/6202053/19625924/21fa80ac-9926-11e6-87f4-332362c05656.png)

Compression (C++11):

![plot-recompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19625902/71d36b4e-9925-11e6-9114-b9b868ffef36.png)

Decompression (C++11)

![plot-decompress-comp_blocktime](https://cloud.githubusercontent.com/assets/6202053/19625904/825e51d6-9925-11e6-98a7-01cc5992bdce.png)
