### ISSUE TITLE
Add mod store again

### ISSUE THREAD

**Issue by 22i** [minetest/minetest#4666]
Do you think subgames, mods and texture packs are easy to install now? Wait till you get to install them via addon tab from minetest itself.

It would work like this: when you switch the tab to addons there would be three tabs: subgames, mods and texture packs. there would also be notification if any of these got updates and if so there would be an option to update everything.

on the subgame tab there would all the old, wip and released subgames. By clicking on some subgame you will get to see subgame details with pictures, list of mods,description and option to install the subgame. There would categories to change between wip, old and released subgames.

on the mods tab there would be categories to sort mods like these http://wiki.minetest.net/List_of_Mods By clicking on some mod you will get to see mod details with pictures, description and option to install the mod including its dependencies.

on the texture pack tab there would be categories to sort texture packs by pixels 8x 16x 32x 64x By clicking on some texture pack you will get to see texture pack details with pictures, description and option to install the texture pack.

There would also be a way to upvote addons and then sort by most upvoted to least, newest  - oldest.

**Comment by rubenwardy** [comment]
Already exists, but disabled due to missing backend

**Comment by hy8wGWme** [comment]
What backend is missing is there a way to enable it again?

**Comment by rubenwardy** [comment]
Related: #3289

**Comment by rubenwardy** [comment]
You can re-enable it by following this: https://github.com/minetest/minetest/pull/4082
That hasn't been merged yet though due to security

**Comment by tobyplowy** [comment]
@hy8wGWme +1 from me :)

**Comment by rubenwardy** [comment]
Another user suggests allowing bulk download of popular mods.

**Comment by MrRar** [comment]
@rubenwardy
The backend alread exists!
It is https://github.com/minetest-mods/
You can get mods via downloading https://github.com/minetest-mods/[mod id]/archive/master.zip
All you need:
http client (exists)
An unziper (unknown)
Some special FS operations (?)

**Comment by Ferk** [comment]
@MrRar that could actually work using the github api.
List of repos: https://api.github.com/users/minetest-mods/repos
Details on the status of master branch: https://api.github.com/repos/minetest-mods/airtanks/branches/master

You could fetch the dependencies directly from the depends.txt: https://raw.githubusercontent.com/minetest-mods/airtanks/master/depends.txt (or better mod.conf, where it should have been moved to).

The only problem is the zip downloads don't include git submodules.
And that it would be depending on a third party proprietary service...

Another alternative would be the bower: https://minetest-bower.herokuapp.com/ (but that would require git for downloading)

**Comment by MrRar** [comment]
@Ferk Yep. Minetest provides JSON trascoding. Ie minetest.encode_base64(string)
minetest.decode_base64(string). But you may not be able to use the github api because of minetest's http client may not have SSL support.

**Comment by rubenwardy** [comment]
87ad4d8e7f25210cd28d9f2b372aa00aa3dab929
