### ISSUE TITLE
add an option to create new worlds without the need to name them.

### ISSUE THREAD

**Issue by 22i** [minetest/minetest#4671]
When i create a new world i usually name it something random like this: sadsdasd but then often this message comes up - a world named sadsdasd already exists.

Lets add an option that lets you create worlds without the need of naming them. World names could be generated with random words or giberish.

**Comment by est31** [comment]
I think @nerzhul has implemented some algorithm to random-generate world names?

**Comment by nerzhul** [comment]
@est31 i have a working algo for that yes, it's in spacel:
https://github.com/spacel/game/blob/master/src/common/engine/generators.cpp#L70

it's C++11 in some parts but can be easily ported to C++03

**Comment by stujones11** [comment]
Does it need to be random words or gibberish? Why not simply world_1,2,3 ... etc or use a time-stamp of some kind.

**Comment by hy8wGWme** [comment]
Not realy but it could be one of the options that you get to choose from when creating worlds. Time stamp or world 1 would be just fine every other option like random words or gibberish could be for extra customization.

**Comment by paramat** [comment]
:-1: I feel this is not needed enough to bother with.

**Comment by paramat** [comment]
Useful.

**Comment by tobyplowy** [comment]
@paramat true xD

**Comment by tobyplowy** [comment]
This is incredibly useful because I always get the same problem Sometimes I just wanna make a World Without giving It a name it's just a World to throw away in a couple minutes (test World) why do I have to waste my time on making a name for it

**Comment by tobyplowy** [comment]
@hy8wGWme This is incredibly useful because I always get the same problem Sometimes I just wanna make a World Without giving It a name it's just a World to throw away in a couple minutes (test World) why do I have to waste my time on making a name for it

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/commit/d1a39f01402c06ad3b5f904a2b3467b5ee2eb6e1
