### ISSUE TITLE
Unintended opaque water surface using shaders and texture pack

### ISSUE THREAD

**Issue by Xanthin** [minetest/minetest#4676]
After 198ed60cabd3066977df5360b7b32a6b895ea744 the water surface is opaque for me if I have shaders enabled, water opaqueness disabled and using the mt version of [misa's texture pack](https://forum.minetest.net/viewtopic.php?f=4&t=274), on Xubuntu 14.04.

Disabling shaders fixes that.
Also this doesn't happen with the default textures and two other texture packs I tested ([HDX Textures (64px)](https://forum.minetest.net/viewtopic.php?f=4&t=1583) and [John Smith Texture Pack](https://forum.minetest.net/viewtopic.php?f=4&t=5383)).

So is it just a problem with this one texture pack? Everything worked fine the last years. Is there any hint how to fix this?

![waternulltpshader](https://cloud.githubusercontent.com/assets/6878547/19748099/08a01eca-9be0-11e6-9446-30a3020a241e.png)
with default textures and shaders enabled

![watertpshader](https://cloud.githubusercontent.com/assets/6878547/19748116/21739bf2-9be0-11e6-874b-50b234a57169.png)
with Misa TP and shaders enabled

![watertpnullshader](https://cloud.githubusercontent.com/assets/6878547/19748143/3e7a3fc6-9be0-11e6-8f01-ff785df4cd9a.png)
with Misa TP and shaders disabled

**Comment by Xanthin** [comment]
I can't say that I really understand what the commit changed, but reading something about "alpha" made me looking at the water textures of the TP and compare it with the default one. It seems that it has no transparency which it probably needs now. 

Adjusting the alpha channel for the animated water textures with gimp fixed the problem for me.

I guess I can close this, because it's more a texture (pack) maintenance thing?

**Comment by paramat** [comment]
Good news.
