### ISSUE TITLE
Underwater Floor not always rendered or emerged correctly.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4678]
Here's a screenshot, notice the sharp edges, and the light blue under the water. When one gets closer that part gets shown. Also notice that there're other parts further away already drawn/emerged.

![screenshot_20161026_220143](https://cloud.githubusercontent.com/assets/446130/19755049/8c38eba4-9bc7-11e6-9dc8-5096c6338fb4.png)

I'm happy to look if somebody can point me towards the code that might affect when a block is drawn or emerged, specifically when underwater.

**Comment by Fixer-007** [comment]
This problem is known for ages, @celeron55 knows the reasons why (he was talking about that long ago). I will be very happy if someone fixes this.

**Comment by Wuzzy2** [comment]
Yes, this is (sadly) a very old bug, but as far I know it was never officially entered into the bug tracker. It was long overdue.

**Comment by sofar** [comment]
This happens with underwater chasms. Even though further terrain is generated, the problem is the "far side of the cliff" which is beyond the draw range.

The same thing happens in caves.

The only solution I can see right now is to make a better fog color blend that masks the problem. Loading more terrain isn't the right solution.

**Comment by lhofhansl** [comment]
It seems to only happen under water, though. I does not happen in dips above ground.
The fog distance is now the same everywhere, but the blocks not rendered are much closer than the fog limit... At least that's what it seems like.

**Comment by lhofhansl** [comment]
Here's another image, I'm underwater practically right in front of the unrendered part.

![screenshot_20161027_132318](https://cloud.githubusercontent.com/assets/446130/19783817/39870fae-9c48-11e6-92ba-796e5b47de1b.png)

**Comment by lhofhansl** [comment]
Or this one is even better. The ground is mostly flat, yet, the blocks above the water are rendered.

![screenshot_20161027_132523](https://cloud.githubusercontent.com/assets/446130/19783885/84ef8f20-9c48-11e6-97e9-b666dfd1c2e9.png)

Not trying to harp the issue. Just figuring out if this is something I can look at it and fix :)

**Comment by Fixer-007** [comment]
Ask celeron about this :trollface:

**Comment by lhofhansl** [comment]
@Fixer-007 on the forum?

**Comment by paramat** [comment]
The missing meshes are where light reaches zero, 17 nodes below water surface. The current code delays the appearence of meshes if the mesh is completely dark, it's intended to be an optimisation but even c55 considers it possibly not a good idea.

**Comment by lhofhansl** [comment]
Thanks @paramat that makes sense. Do you know where this code is? (looked around a bit, but wasn't immediately obvious)

**Comment by paramat** [comment]
No idea.

**Comment by lhofhansl** [comment]
Found it. This fixes it. Since we still enforce the max send distance and block count, this is safe to remove (IMHO).

The experience of the rendered ground under water and particularly caves is _much_ better.
If people are not getting heart-attack over this, I'll send a PR.

```
diff --git a/src/clientiface.cpp b/src/clientiface.cpp
index d78cf1c..16f2383 100644
--- a/src/clientiface.cpp
+++ b/src/clientiface.cpp
@@ -288,19 +288,6 @@ void RemoteClient::GetNextBlocks (
 
 				if(block->isGenerated() == false)
 					block_is_invalid = true;
-
-				/*
-					If block is not close, don't send it unless it is near
-					ground level.
-
-					Block is near ground level if night-time mesh
-					differs from day-time mesh.
-				*/
-				if(d >= 4)
-				{
-					if(block->getDayNightDiff() == false)
-						continue;
-				}
 			}
 
 			/*
```

**Comment by paramat** [comment]
Yes please for a PR.
This issue may also be why dark places such as cave entrances and deep hollows under overhangs sometimes stay unrendered.

**Comment by paramat** [comment]
Looking at the code that seems safe to remove.

**Comment by paramat** [comment]
Somewhat related #4684

**Comment by lhofhansl** [comment]
I saw the code mentioned in #4684 as well, but that at least makes some sense - and when I removed it as a test things seems slower.
