### ISSUE TITLE
Build error: "undefined reference to '...'"

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#4683]
The Android build fails with

``jni/../jni/src/environment.cpp:613: error: undefined reference to 'RemotePlayer::save(std::string, IGameDef*)'
jni/../jni/src/environment.cpp:623: error: undefined reference to 'RemotePlayer::save(std::string, IGameDef*)'
jni/../jni/src/environment.cpp:635: error: undefined reference to 'RemotePlayer::RemotePlayer(char const*, IItemDefManager*)'
jni/../jni/src/environment.cpp:644: error: undefined reference to 'RemotePlayer::deSerialize(std::istream&, std::string const&)'
jni/../jni/src/server.cpp:2751: error: undefined reference to 'RemotePlayer::canSendChatMessage()'
jni/../jni/src/server.cpp:3437: error: undefined reference to 'RemotePlayer::RemotePlayer(char const*, IItemDefManager*)'
jni/../jni/src/touchscreengui.cpp:102: error: undefined reference to 'keyname_to_keycode(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [obj/local/armeabi-v7a/libminetest.so] Error 1
make[2]: Leaving directory `/home/wayward_one/minetest/build/android'
make[1]: *** [apk] Error 1
make[1]: Leaving directory `/home/wayward_one/minetest/build/android'
make: *** [debug] Error 2``

**Comment by paramat** [comment]
@MoNTE48 any idea?

**Comment by Wayward1** [comment]
Perhaps @sfan5 or @nerzhul could help as well? It looks like it could be related to some of nerzhul's cleanups and improvements involving RemotePlayer

**Comment by nerzhul** [comment]
@Wayward1 i think i forget to add one new source file to android build.

**Comment by Wayward1** [comment]
Cool, thank you both :) It now builds successfully.
