### ISSUE TITLE
Reconsideration of vertical generation / sending limits for mapblocks 

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4684]
Relevant code https://github.com/minetest/minetest/blob/master/src/clientiface.cpp#L233

```
                /*// Limit the generating area vertically to 2/3
                if(abs(p.Y - center.Y) > d_max_gen - d_max_gen / 3)
                    generate = false;*/

                // Limit the send area vertically to 1/2
                if (abs(p.Y - center.Y) > full_d_max / 2)
                    continue;
```

Currently vertical is treated specially, the limits are smaller, however in our increasingly vertical mapgens with floatlands and extreme mountains this could be reconsidered. Personally i find it a little irritating. This is something c55 has mentioned as being questionable.

Would there be much of a performance hit if invisible mapblock meshes of air are not above and culled mapblock meshes are not below?
There would be more map generation though, although empty air and underground takes less time to generate, and underground would often be explored anyway later.
Perhaps a setting could control the vertical limits, with a setting for treating vertical identically to horizontal?

**Comment by Fixer-007** [comment]
This problem also bugged me, if you asking why - join server with NYC map or download it on forum. You will have a big problem rendering apper parts of buildings, heck even on usual minetest servers it has problems, like big baloon on Just Test II.

I have a feeling, maybe block loading for positive Y should be treated differently? Like: check pointed direction -> load mapblocks beginning from player level and all blocks UP to players v_range? Hard to say for sure.

**Comment by paramat** [comment]
I'm thinking of a setting "isotropic block generate send distances" or something.
Keep old behaviour as default as it seems to help performance.

**Comment by paramat** [comment]
#4746 merged.
