### ISSUE TITLE
Allow a different "hand" item per player

### ISSUE THREAD

**Issue by PureTryOut** [minetest/minetest#4688]
Currently the `default` mod registers an item for ever player which acts as the hand

```
minetest.register_item(":", {
    type = "none",
    wield_image = "wieldhand.png",
    wield_scale = {x=1,y=1,z=2.5},
    tool_capabilities = {
        full_punch_interval = 0.9,
        max_drop_level = 0,
        groupcaps = {
            crumbly = {times={[2]=3.00, [3]=0.70}, uses=0, maxlevel=1},
            snappy = {times={[3]=0.40}, uses=0, maxlevel=1},
            oddly_breakable_by_hand = {times={[1]=3.50,[2]=2.00,[3]=0.70}, uses=0}
        },
        damage_groups = {fleshy=1},
    }
})
```

However, this hand either applies for _every_ player, or none. This is for example the reason why creative mode is set for _every_ player in a server, as the default hand is replaced for _every_ person.
I would like to have the option to replace that hand per player, so mods can set creative mode on/off per player instead of for the whole world.

Maybe it's better to make creative mode an option per player entirely, and just have the existing `creative_mode` option be the default for a world.

**Comment by est31** [comment]
I think PR #2827 wants to implement this.

**Comment by PureTryOut** [comment]
Ooh interesting, that's basically what I want. With that implemented, and some kind of way to track gamemode status per player (can you set custom variables/metadata per player?), it does exactly what I need it too.

It seems that the PR was approved, but since the 2nd of June nobody has done anything with it?

**Comment by paramat** [comment]
I very much want a customisable hand texture, it will be an excellent feature. Let's consider #2827 again. PureTryOut perhaps you have input for that PR? If you have an alternative implementation to submit that would be welcome too.

**Comment by PureTryOut** [comment]
Sorry, I can't really code in C++ (yet), and I know literally nothing about's Minetest core code based. I just need a fairly good documentated (or an example) of how to use such a function ;)

I would just like to be able to set a custom hand, and be able to say how much damage a player does with it, how quick he can punch, etc. Like the original implementation, but per player instead of per world.

**Comment by Ferk** [comment]
> can you set custom variables/metadata per player?

#4155 was the most promising attempt.

**Comment by PureTryOut** [comment]
Asking players to re-log is not at all acceptable to me. I want my mod to become as user-friendly as possible, and that is *not* user-friendly ;)

Anyways I think #2827 and #4155 together do what I want, I'll just wait for those to get merged.

**Comment by Wuzzy2** [comment]
This is a good idea. This is much more useful that way. I don't know how much I was forced to restart a world only to turn off Creative Mode. :(
I think we might even remove the traditional Creative Mode entirely. The way it was implemented is already very awkward, with most of the features already done on mod-side (instead of engine-side), so this will be no big loss.
And a privilege could be added to players to toggle their own creative mode.

One question remains: How do players turn on creative mode? And don't say “chat command”! :P

**Comment by PureTryOut** [comment]
Well I would set a default gamemode for a world when creating the world. Maybe beneath choosing a game for the world, add a selection for gamemode. Whatever is set there will be the gamemode a player gets if he/she enters the world for the first time (basically the current "creative_mode" boolean).
If people want to change it in-game, they can with the "chat command!" :p, of course with a privilege attached to it. Also, `singleplayer` should probably get this privilege by default.

**Comment by tobyplowy** [comment]
@Wuzzy2 +1 for redo of creative mode

**Comment by paramat** [comment]
#2827 merged.
