### ISSUE TITLE
Commit 779d2c5f makes the entire world too dark

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest#4691]
Commit 779d2c5f makes the world too dark (or at least, that's what I think it does - in any case it looks really bad).

Before:

![screenshot-good](https://cloud.githubusercontent.com/assets/6202053/19821431/8cf658c2-9d5e-11e6-81c9-be04a7c1473e.png)

After:

![screenshot-bad](https://cloud.githubusercontent.com/assets/6202053/19821430/8cf56e08-9d5e-11e6-93ff-b7c57bb98a0b.png)

**Comment by sfan5** [comment]
Graphics Card / Driver / OS ?

**Comment by Rogier-5** [comment]
Card: GeForce 8400M GS
OS: Linux debian with kernel 3.16.0-4-amd64 and 32-bit userland
Nouveau: 2.4.60

**Comment by paramat** [comment]
Weird. @lhofhansl ?

**Comment by lhofhansl** [comment]
Huh? Do see how it could. It's not doing anything with the brightness.
@Rogier-5 you have shaders on? Absolutely nothing else that changed? gamma? Time :) ?

I can't test with Nouveau, only with the proprietary NVidia drivers or Intel HD.

**Comment by lhofhansl** [comment]
Tried again. With change and without, with shaders and without, Intel HD and NVidia. The brightness is same when all settings are the same.
Did you enable/disable tone-mapping perhaps? That changes the brightness too.

**Comment by sofar** [comment]
Looks fine to me (nvidia drivers on a GTX960) after that patch.

**Comment by Fixer-007** [comment]
Maybe something with your gamma settings? It works to me.

**Comment by Rogier-5** [comment]
Nothing else is different. Same minetest tree, same world. Patch not applied: 1st image, patch applied & restart: 2nd image.

No filter, no mipmap, no AA, shaders enabled, but no *-mapping (although I tested it, and it doesn't make a difference). I also tried starting with an empty `minetest.conf`, and the effect is the same.

Gamma settings are all 1 (as reported by xgamma).

With fog enabled, and a viewing range 30 it looks OK. When the viewing range increases, it gets worse, and with a viewing range above about 60, the colors are dark. With fog disabled, they are dark across all viewing ranges. See images below.

With shaders disabled, the world looks normal again (but as the patch affects the shaders, that is probably to be expected).

Screenshot without patch:

![screenshot-good2](https://cloud.githubusercontent.com/assets/6202053/19830555/a23615c8-9dfa-11e6-9445-cd2267816def.png)

With patch, viewing range 200:

![screenshot-bad2](https://cloud.githubusercontent.com/assets/6202053/19830554/a22c36fc-9dfa-11e6-87b2-385c697912cb.png)

With patch, viewing range 30:

![screenshot-range30](https://cloud.githubusercontent.com/assets/6202053/19830556/a23a90bc-9dfa-11e6-857f-9437f5265839.png)

**Comment by lhofhansl** [comment]
I can't explain it. Patch doesn't do anything with brightness, the fog calculation is correct. Might be badly supported shaders by the driver. I tested with short view range and up to 200.

Not sure how to proceed. Obviously we coul revert the change. I guess I'd be happier to see this behavior from someone else.

**Comment by paramat** [comment]
It's almost as if 'clamp' isn't working and 'd' is passing it's limits making colours over-saturate. I wonder if using min, max instead of clamp would help?

**Comment by Rogier-5** [comment]
I have been playing around a bit with the code; unfortunately, glsl does not have printf statements, so that I can't see what happens exactly, but I suspect it may be a glsl compiler bug...

The following code (latest minetest tree) makes everything too dark:
```glsl
float d = clamp((fogDistance - length(eyeVec)) / (fogDistance * 0.6), 0.0, 1.0);
```
while the following code produces the correct results...
```glsl
float d = clamp(1.0 / 0.6 - length(eyeVec) / (fogDistance * 0.6), 0.0, 1.0);
```

Also, the observed colors seem to be consistent with a value of `d` somewhere in the range 1.5 .. 2, which should be impossible due to `clamp()`.

**Comment by paramat** [comment]
Ah, there's a problem with brackets in the commit?

**Comment by Rogier-5** [comment]
@paramat: I did try `min()`/`max()` instead, and that didn't change anything. I suspect the compiler is incorrectly optimizing stuff away:

@paramat (2): The brackets seem fine. Both statements shoud be 100% equivalent AFAICS. But apparently, one of them isn't equivalent (:-) on my system...

An example which (almost?) proves this:

The following is not OK
```glsl
float d = (fogDistance - length(eyeVec)) / (fogDistance * 0.6);
d = max(d, 0.0);
d = min(d, 1.0);
```
while the following is:
```glsl
float d = (fogDistance - length(eyeVec)) / (fogDistance * 0.6);
if (d < 0) d = 0;
if (d > 1) d = 1;
```

**Comment by paramat** [comment]
Yeah i just saw the brackets are ok, my mistake.

**Comment by paramat** [comment]
How about calculating d, then using clamp() in a second line?

**Comment by Rogier-5** [comment]
@paramat: Tried, but it didn't work either.

**Comment by paramat** [comment]
It's likely there will be others with your problem, so alternative equivalent code should be used.

**Comment by paramat** [comment]
Perhaps try a new build, or recompile?

**Comment by paramat** [comment]
Anyway i agree we need one other person confirming this before acting.

**Comment by lhofhansl** [comment]
We can always replace the clamp with if condition, that will work everywhere.

**Comment by juhdanad** [comment]
@lhofhansl, `if`, `for` and `while` make shaders really slow, I don't suggest that.

**Comment by lhofhansl** [comment]
So what should we do with this?

Perhaps we can have a "compat" mode where we compile the shaders differently (similar to how we do it with normal mapping, etc). When in compat mode we'd do things with if-for-while or whatever needed. Maybe that would help with Android as well (on Phone/Tablet everything is red'ish for example).

**Comment by paramat** [comment]
@Rogier-5 what build do you use? have you tried compiling a clean build?
If it's equivalent we perhaps could use:
```glsl
float d = clamp(1.0 / 0.6 - length(eyeVec) / (fogDistance * 0.6), 0.0, 1.0);
```

**Comment by Fixer-007** [comment]
I've noticed a spider in your screenshot. Can you disable ll mods and test again?

**Comment by Rogier-5** [comment]
> So what should we do with this?

As my software versions are a little over a year old, and as nobody else confirms the problem so far, this issue may be caused by my older version of the glsl compiler (which I suspect is miscompiling the code - but I am not a graphics stack expert). Unfortunately, I can't upgrade at this moment. Other people with systems that are not frequently upgradewd might experience the same problem. Or they might have a different glsl compiler version that doesn't have the problem.

So, we could wait for another bug-report, and then use the code paramat quotes. Or we could just use that code now(*).However, ATM there doesn't seem to be a need for special cases. Just rewriting the formula a little seems to be sufficient

From a personal point of view, I'd naturally prefer not to have to re-apply / rebase my fix every time I pull some new commits. However from a project point of view, I agree with @paramat that it's better to have at least a confirmation that more than one person is affected.

(*) But see my remark below. Maybe another similar fix is needed elsewhere as well...

> what build do you use? have you tried compiling a clean build?

I regularly fetch the latest minetest development tree, and use that. I have at least once compiled minetest from scratch, with the same result. As an aside, if I exit the game to the main menu, apply or revert the patches I mention, and start the game again (without even exiting minetest altogether), the rendering changes. That indicates it is primarily, or even purely, a run-time issue.

-----------------------

While I'm at it: in the mean time, I discovered another rendering change caused by the recent changes (commits 198ed60ca, 98176481, 779d2c5f): the water in darker parts of caves looks black, while it used to be nice and blue

Screenshot without the commits I mentioned:

![screenshot_20161108_233431](https://cloud.githubusercontent.com/assets/6202053/20120398/f212db0c-a60c-11e6-87f9-6f800bf1d261.png)

Screenshot with those commits, but with the shader fix that I mentioned earlier applied:

![screenshot_20161108_233606](https://cloud.githubusercontent.com/assets/6202053/20120399/f21378aa-a60c-11e6-8c76-d33601689998.png)

Is anyone else seeing this effect as well ? Please let me know. Or is it specific to my environment too. If this change is not universal either, I'll try to find a (similar?) fix for it...

---------------------

@Fixer-007: this is not a mod problem: here's the same screenshot which includes the commits, and doesn't include my fix to te original problem. The game is minetest_game, apart from that the world is as good as modless.

![screenshot_20161108_234729](https://cloud.githubusercontent.com/assets/6202053/20120654/f68a3706-a60d-11e6-9642-e03dcbe04bb3.png)

**Comment by paramat** [comment]
Thanks.
Wow, looks like the bug sometimes occurs in water but not elsewhere.

**Comment by lhofhansl** [comment]
Hmm... If clamp is not working right it would have ill effects everywhere.

**Comment by lhofhansl** [comment]
@Rogier-5 this all is with shaders enabled, right?

**Comment by lhofhansl** [comment]
Oh wait... You did apply your shader changes already.

**Comment by Zeno-** [comment]
The order of floating point operations, especially in shaders for some reason, /can/ cause different results on different cards, drivers etc

**Comment by Rogier-5** [comment]
@lhofhansl: it's not that `clamp()` is _not_ working. It rather seems that, depending on the order of computations, it is erroneously optimized away by the compiler... The following patch works for me:

```diff
diff --git a/client/shaders/nodes_shader/opengl_fragment.glsl b/client/shaders/nodes_shader/opengl_fragment.glsl
index 4d9ce1c..8baf1e8 100644
--- a/client/shaders/nodes_shader/opengl_fragment.glsl
+++ b/client/shaders/nodes_shader/opengl_fragment.glsl
@@ -199,7 +199,7 @@ void main(void)
 #endif
 
        if (fogDistance != 0.0) {
-               float d = clamp((fogDistance - length(eyeVec)) / (fogDistance * 0.6), 0.0, 1.0);
+               float d = clamp(1.0 / 0.6 - length(eyeVec) / (fogDistance * 0.6), 0.0, 1.0);
                col = mix(skyBgColor, col, d);
        }
        col = vec4(col.rgb, base.a);
```
and replacing `clamp()` with `min()` and `max()` has no effect, so they are also affected.

> Oh wait... You did apply your shader changes already.

Indeed. I modified my comment to clarify

> The order of floating point operations, especially in shaders for some reason, /can/ cause different results on different cards, drivers etc

@Zeno-: I assume those would be rounding errors ? Not an apparent failure to perform a `clamp()` which is in the code and which is unconditional ?

**Comment by Rogier-5** [comment]
The water-in-cave rendering problem had a similar same cause. And the hand shading code had the same issue. I changed all of them, and created a PR (if only for the record).

**Comment by Zeno-** [comment]
@Rogier-5 normally it's just rounding errors but I do remember reading somewhere that it can introduce more than that (i.e. not just rounding errors like normal code) depending on OpenGL version, driver etc etc. Maybe even optimise stuff away that's not meant to be optimised away ;)
