### ISSUE TITLE
player_falling_damage.ogg is played when damage is disabled

### ISSUE THREAD

**Issue by infmagic2047** [minetest/minetest#4696]
IMO it should not be played because player is not actually taking falling damage.

**Comment by paramat** [comment]
I agree.

**Comment by paramat** [comment]
Easily fixed by just removing 'player falling damage' from MTGame. Will fix.

**Comment by paramat** [comment]
Fix is here https://github.com/minetest/minetest_game/issues/1352

**Comment by paramat** [comment]
https://github.com/minetest/minet​est/blob/master/src/game.cpp#L840
I could reword the sound name here, or better only play it when damage is enabled, depends on whether we want it as an always-on 'long fall' sound effect.

**Comment by paramat** [comment]
Forgot to close this, all fixed.
