### ISSUE TITLE
MSVC x64 fails to link in "Release" build mode. "MinSizeRel" and "RelWithDeb" works fine

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#4697]
I recently got a new computer and set up a new build environment for Minetest.

But it seems minetest is not able to link if I use the "Release" build mode. If I select MinSizeRel and RelWithDebInfo it compiles and links fine. The output:

```
1>------ Build started: Project: GenerateVersion, Configuration: Release x64 ------
1>  -- *** Detected Git version 0.4.14-361e687 ***
2>------ Build started: Project: minetest, Configuration: Release x64 ------
2>LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification
2>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
2>sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol __imp__endthreadex
2>sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol __imp__beginthreadex
2>sqlite3.lib(sqlite3.obj) : error LNK2001: unresolved external symbol __imp_rand_s
2>freetype27.lib(ftbase.obj) : error LNK2001: unresolved external symbol __imp_strncpy
2>freetype27.lib(truetype.obj) : error LNK2001: unresolved external symbol __imp_strstr
2>...\Minetest\bin\Release\minetest.exe : fatal error LNK1120: 5 unresolved externals
========== Build: 1 succeeded, 1 failed, 4 up-to-date, 0 skipped ==========
```

Since there are other people seems to be able to build, is there something I have to change inside Cmake script? Or can someone confirm It does not build within a fresh build environment?
BTW: If I use builtin lua there are a lots of more linker errors which disapeared switching to LuaJit
Thanks for any help

**Comment by sfan5** [comment]
There seems to be a problem with your libraries.

**Comment by adrido** [comment]
And why does it work with MinSizeRel and RelWithDebInfo? Also MinetesetMapper links fine with the sqlite. 
Im currently trying to change all compiler/ linker options "MinSizeRel" that are different to the "Release" options, but currently without success

**Comment by SmallJoker** [comment]
**Bundled Lua**
According to my old notes from 2014 it is possible to fix the bundled Lua build by replacing all occurrences of `MultiThreadedDLL` with `MultiThreaded` in `cmake_build_dir\src\lua\build\lua.vcxproj`

**Sqlite3**
I'm using this CMakeLists.txt file for the amalgamation version of sqlite3 with yet no problems:
```cmake
cmake_minimum_required(VERSION 2.6)

if(MSVC)
	set(CMAKE_C_FLAGS_RELEASE "/MT /O2 /Ob2 /D NDEBUG")
endif()

add_library(sqlite3 "sqlite3.c")
target_link_libraries(sqlite3)

add_executable(sqlite3_gui "sqlite3.c" "shell.c")
target_link_libraries(sqlite3_gui)
```
Sometimes it also helps to delete the affected .obj files in `cmake_build_dir\src\minetest.dir\Release\` to make MSVC re-build them. It's not a proper way to fix things but it (usually) works.

**Comment by adrido** [comment]
Im recently got a bit closer to a solution :-D
I remembered there where something wrong with the bundled Lua
Do you have a link to your note? It could be usefull for someone else.

Like you I fount out that some bundles get compiled with /MD and some others with /MT. If I completely remove all customs compiler flags like 
```CMAKE
if(MSVC)
    #set(CMAKE_C_FLAGS_RELEASE "/MT /O2 /Ob2 /D NDEBUG")
endif()
```
and run Cmake with the default values (probably `/MD /EHsc /O2 /Ob2` ) it compiles and links fine without warnings and errors. Ill search now which parameter is causing the errors. (I think its /MD vs /MT but just want to get sure)
But wouldn't it be better to keep everything as default and let CMake decide what params are the best to compile and link?

**Comment by SmallJoker** [comment]
I've added a notice for the bundled Lua thing in [the wiki-linked external help page from my site](http://krock-works.16mb.com/MTstuff/Compile_Minetest_MSVC.txt).
The two libraries like to throw errors when they're being mixed up. Make sure everything's compiled either with `/MT` or `/MD`.

**Comment by adrido** [comment]
Sadly its not so simple. Now I tried to compile where everything is build with /MT and get the same problems as first.  It only works if the Minetest project is compiled with /MD - which is default in CMake or new Visual Studio projects. If I compile Minetest with /MD it does not seem to make a difference if I compile sqlite and freetype with /MT or /MD it just works fine then.
Was there a reason, that someone changed from /MD to /MT?

**Comment by rubenwardy** [comment]
Please bump if the problem is still present, looks like a question thread to me
