### ISSUE TITLE
Add a FXAA shader

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#4698]
FXAA (Fast approXimate Anti-Aliasing) is a fast anti-aliasing method that also smoothes out transparent textures (unlike MSAA). It is quite faster than MSAA, and thus suitable on almost all hardware (it could even be enabled by default, depending on how well it performs).

It's usually implemented as a post-processing shader, as far as I know.

**Comment by HybridDog** [comment]
>It is quite faster than MSAA […]

There's also MLAA and its successor SMAA:
http://www.iryoku.com/mlaa/

**Comment by paramat** [comment]
1+ year bump, any core dev support?
