### ISSUE TITLE
Water Physics

### ISSUE THREAD

**Issue by that4chanwolf** [minetest/minetest#47]
Things like signs and torches block out water for some odd reason.

**Comment by nerzhul** [comment]
Very old issue.

**Comment by PilzAdam** [comment]
@nerzhul but still valid. Non-walkable nodes should be flushed away by water.

**Comment by C1ffisme** [comment]
Shouldn't this issue be a part of Minetest Game? After all, water is basically registered there. If we want to fix water physics, we should fix it in Minetest Game. Minimal? That can remain simple.

Or, to help other games easily do this, why not go ahead and do this in the engine, but add a group like: ```manipulates_space_and_time_to_mess_with_water_physics = 1```. Okay, so maybe not that long, but something like that.

**Comment by paramat** [comment]
This needs attention now as i am enabling core mapgens to place airlike nodes as atmosphere or vacuum, liquids need to be able to flow into these and destroy them. If i can i'll fix this myself.

**Comment by paramat** [comment]
Related https://github.com/minetest/minetest_game/pull/829 see discussion there.

**Comment by paramat** [comment]
Signs and torches would have to be dropped when water floods these nodes, using an 'on_flood' callback, see the discussion linked above. I feel water should continue to be non-destructive to avoid being a griefer's wet dream, torches may be the only node i would be happy to see flooded away, certainly not signs, so they will have to continue to block out water.

**Comment by sofar** [comment]
This should be decided by the subgame:

- For single-player subgames, griefing is part of the game mechanics and may be highly desirable.
- For multiplayer subgames, griefing is a major problem and undesirable.

The only logical conclusion is that the engine should support both.

**Comment by paramat** [comment]
Good point. We could have an 'on flood' callback and leave it to subgames to use it is wanted.

**Comment by MT-Modder** [comment]
Bump

**Comment by paramat** [comment]
#5619 merged.
Now that we have the engine code to allow drop on flood this issue is now MTG in terms of whether to drop certain nodes 'on flood'.

**Comment by C1ffisme** [comment]
Maybe next issue won't take 5 years to fix/implement?
