### ISSUE TITLE
Replace zoom privilege with function calls (discuss)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4700]
I am personally not happy with the way zooming is allowed/forbidden to players.
It requires the player to have the `zoom` privilege. But this is the wrong approach IMO. 

I suggest to either turn it into a HUD flag (Lua API: `hud_set_flags({zoom=true})`) or add 2 additional functions to the `player` object: `set_zoom(true/false)` and `get_zoom() = true/false`. I don't care which one you chose, the point is that it is integrated into functions rather than by privileges.

For example, to enable zoom, the modder just writes `player:hud_set_flags({zoom=true})`, and to disable it, it's `player:hud_set_flags({zoom=false})`.

By default, zooming should be enabled.

Rationale: Zooming is closely related to gameplay, it would make more sense to use different mechanisms. The minimap also does not require a privilege, but is instead implemented via HUD flags (`hud_set_flags`). Also, it seems awkward for zooming to be something to be controllable by the server admin.

Example use case (to illustrate the problem): Binoculars. If player wields this item, he/she can zoom, otherwise not. If just `hud_set_flags` is used (as I suggested), it is pretty straight-forward to implement. However, if zooming is implemented as privilege, things become ugly: You could theoretically still implement binoculars by modifying the privilege, BUT this is asking for trouble since server moderators can happily overwrite the privilege by granting/revoking, which will lead to unexpected/awkward results. Basically moderators and mods “compete” for the `zoom` privilege, which is very awkward. xD

Do you agree with my opinion on the `zoom` privilege? Are you OK with my proposal?

**Comment by paramat** [comment]
Certainly worth considering. I feel that zoom should be disabled by default though, enabled somehow on creative servers and by mods when special items have been crafted. Perhaps it was done through privilege to make it simple to enable on creative servers?
This reminds me we should have a telescope item craftable in MTGame which enables zoom.

**Comment by Wuzzy2** [comment]
Oh, well. Whether `zoom` is on by default or not, I don't really care.

About “telescope”: Today I pushed an experimental binoculars branch to my Orienteering mod: https://forum.minetest.net/viewtopic.php?f=9&t=15247
(it “abuses” the privilege, that's why it is experimental)

**Comment by PureTryOut** [comment]
While you're at it, I think the same should be done with flying (and possibly `fast` as well?). Flying and going fast is just as well part of gameplay: maybe I would make some kind of "magic" mod which allows you to fly while wielding a staff of some sorts, or I could make flying only possible if in creative mode. Same point applies: you can modify the privilege, but that would give problems.

**Comment by Wuzzy2** [comment]
Let's keep this discussion on `zoom`, shall we?

**Comment by PureTryOut** [comment]
Eeuhm sure... Reading your post I thought it was about general privilege versus function calls, I guess not. I'll make a separate issue for it someday then ;)

**Comment by est31** [comment]
I prefer the current state with a priv, and in future client side modding can take this over.

**Comment by Wuzzy2** [comment]
What's your rationale for that? Also, why waiting for a feature which is probably in the far future?
Client-side scripting is not the answer to everything IMO.

**Comment by est31** [comment]
@Wuzzy2 it will add more technical debt, and its subject to lag from the server. Zoom is a client only feature, and therefore the logic best runs directly on the client.

**Comment by paramat** [comment]
I'm thinking about this now for a telescope item. Curently it seems the only way is too, every few seconds, scan the players' hotbars for the telescope item and if found grant the privilege, if not remove the privilege.

**Comment by Wuzzy2** [comment]
@paramat: Would an implementation like that be OK for Minetest Game? I just need a better texture (I hate the current one by myselves)?

**Comment by paramat** [comment]
I'm planning on making the PR myself, i opened an issue for input.

**Comment by tobyplowy** [comment]
@PureTryOut You should make a separate issue on that (you already have a +1 from me for creatieve Not The staff)

**Comment by rubenwardy** [comment]
I'd much rather make zoom a hud flag like minimap, then give or take it when a privilege is granted or revoked #4713

**Comment by Fixer-007** [comment]
My thinking:
1) zoom priv - for admins or other special needs
2) binoculars with zoom - for gameplay
3) minimap priv - for admins or other special needs
4) compass(?) that enables minimap - for gameplay

**Comment by Wuzzy2** [comment]
No. Having BOTH a zoom/minimap priv and a HUD flag (or whatever other mechanism may be used) is adding too much complexity IMO, for no good reason. We should decide for one or another, but not both. My main concern about having a priv is that it interferes with mods and gameplay. And vice-versa: That mods interfere with priv assignments made by moderators. If we add a HUD flag to the existing flags, things will only get worse.

I am also against adding too much privileges into the game. Each additional privilege just adds cognitive workload to the server operators, so privileges should only be added sparingly and only if needed. Remember we are talking about *builtin* privileges, not about privileges from other mods.

The minimap suggestion is off-topic and also pointless. We already have a minimap HUD flag, what more do you need? Suggestion no. 4 is already implemented in my mod `orienteering`. It is called the “Automapper”. :-) And as said earlier, suggestion no. 2 is implemented in an experimental branch of the same mod.

**Comment by kaeza** [comment]
#1075

**Comment by C1ffisme** [comment]
I'd be interested in using this for things such as potion effects, bows or telescope items.

**Comment by paramat** [comment]
I support making this a HUD flag, so let's do it'

> Zoom is a client only feature, and therefore the logic best runs directly on the client.

It needs to be restricted by the server somehow.

**Comment by paramat** [comment]
PR #6262

**Comment by paramat** [comment]
HUD flag turned out to be an unpopular idea, with discussion we agreed on making it a 'player object property'.

**Comment by Ferk** [comment]
> Rationale: Zooming is closely related to gameplay, it would make more sense to use different mechanisms

Honestly, most privilege flags affect gameplay. By this rationale I'm not sure what the purpose of privileges is.

You could make an item that allows you to fly as well, or noclip, does that mean fly and noclip should not be priviledges?
Imho, it seems to me this distinction is just conceptual and based on particular gameplay mechanics of particular modes of play, not really a technical distinction that makes sense for the engine to implement this capability differently, imho.

**Comment by paramat** [comment]
In other discussions we have found that using privs for certain things is problematic, and it is for zoom.

**Comment by rubenwardy** [comment]
It makes it possible to add a binoculars slot to the inventory, to unlock the zoom ability. Plus now that privilege callbacks have been merged, you can easily implement a zoom privilege in a clean way.

**Comment by paramat** [comment]
#6340 merged.

**Comment by Ferk** [comment]
> It makes it possible to add a binoculars slot to the inventory, to unlock the zoom ability

That's not possible without a player property?
Maybe then it would be worth it to rather add callbacks to make it possible than to simply go the easy way and add this as a player property.

This now sets a precedent. As soon as there's any other feature that can be enabled per player and that someone thinks it's good to have associated with an item in an inventory slot a new player property might have to be added for that.

Not to mention that this done in C++, so privileges that are defined in Lua by mods will not benefit from the ability of being able to have an item that enables them.

**Comment by Wuzzy2** [comment]
Ferk, you sound like it's the doomsday apocalypse.

> As soon as there's any other privilege that can be enabled per player and that someone thinks it's good to have associated with an item in an inventory slot a new player property might have to be added for that.

Nobody suggests that we have to act the same way for every privilege, that's just nonsense. I think you fell victim to the slippery slope fallacy.

Fly, fast and noclip are special because they are useful in Creative Mode or just for “cheating”, so privileges make total sense. It is questionable whether these will ever become a player property (I hope not). If you want an item which lets you fly, using fly mode for that is not really good anyway, you probably want a different gameplay mechanic for that.

Zooming is very different here because it is directly related to legit (!) gameplay and a privilege really didn't make sense here.

**Comment by Ferk** [comment]
Sorry if I appeared bothered by this, it was just an opinion, but honestly it's not really a big deal.

@Wuzzy2 yes, that's exactly what I meant, it being based on arbitrary gameplay expectations of a particular game mode. Imho, an engine should be an engine and not introduce judgements based on anything that is not technical functionality and behavior. Introducing different implementations for things that functionally behave the same just makes the API more inconsistent, the main reason for the distinction seems to be just based on the concept that zoom is different for your particular gameplay use case, making the engine a bit more gameplay-dependant where it doesn't need to be, imho.
