### ISSUE TITLE
Custom field names naming convention

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4704]
This is more a discussion issue and less a bug report or feature request.
I propose a naming convention for field names (e.g. of item definition fields).
See also: https://forum.minetest.net/viewtopic.php?f=47&t=15801&p=238138

All names starting with `x_` are reserved to be assigned by modders freely. Everything else is “engine land”, meaning that developers of the engine can assign names.

The actual request here is that, when discussion is done, is to write down the conventions into `lua_api.txt`. Also, the fact that modders can add custom fields to their item definition is not something which is obvious, so it could be mentioned as well.

(Use the reaction icon to show your support/opposition.)

**Comment by est31** [comment]
:+1: I like the idea.

**Comment by dsohler** [comment]
Wouldn't it be better to add namespace support? So modders can use whatever names they want in their mod's namespace?

**Comment by Wuzzy2** [comment]
I don't exactly know what you mean by “namespace support”. Usually mods just add a global variable in which they put everything, if the mod wants to “export” stuff like functions. E.g. `default` in the `default` mod.

**Comment by dsohler** [comment]
> I don't exactly know what you mean by “namespace support”.

It would be like in [PHP](http://php.net/manual/en/language.namespaces.php), or [JavaScript](https://javascriptweblog.wordpress.com/2010/12/07/namespacing-in-javascript/) (obsolete with ES6 though), or [Python](https://bytebaker.com/2008/07/30/python-namespaces/), or even [Lua](http://lua-users.org/wiki/NamespacesAndModules).

With namespace support we don't need to rely on naming conventions but make it impossible to break stuff by ignoring such a convention.

**Comment by Zeno-** [comment]
namespaces probably *would* be a good idea as well. At the same time I don't mind the idea of reserved names either.

**Comment by dsohler** [comment]
Is there anything that would speak against a leading underscore for "custom" variables? It's a bit easier to read and write than `x_`. Plus: Less work on the engine. There only has to be a list of reserve variable names.

When using reserved variable names in a mod it should throw an exception.

**Comment by Wuzzy2** [comment]
Note: My suggestion does not include *any* engine involvement whatsoever. It is just a naming convention, and a request to developers to never add any fields starting with “x_”, and finallly documenting this in `lua_api.txt`.
Modders can (in theory) still use any name they like, but this practice would not be considered “best practice” then.

If we can't agree on a prefix right now, let's vote to get it over with.

My vote is for “`x_`”.

**Comment by dsohler** [comment]
I like having rules and that the rules are enforced. So it really don't matter to me if it's `x_` or `_` or a namespace as long as it is guaranteed that the system has to be used in order to not having the mod only throw an exception.

A convention is nice to have and would be awesome but to me it's only a nice-to-have when there isn't a rule to enforce it.

**Comment by paramat** [comment]
:-1: 

> Like, custom fields should always have the form “x_modname_fieldname” to avoid naming collisions.

All we need to do is document the advice that modders use the 'modname' prefix for custom nodedefs, that is obvious and intuitive and avoids mod conflicts as well as mod-engine conflicts.

**Comment by Wuzzy2** [comment]
Sorry, this does not guarantee collision freeness. Using the modname as the prefix is waaay to unpredictable since a modname can be any word.

Example:
- Mod `water` adds (supposedly) custom field `water_fluidity` (just a silly example).
- Engine devs don't know this mod and (by chance) add a field called `water_fluidity` into the node definition

If you don't like the form `x_modname_fieldname`, then just `x_whatever` with the promise that engine devs never add any field starting with `x_` (or whatever prefix you might want to use).

**Comment by kaeza** [comment]
#1075

**Comment by paramat** [comment]
I see.
I agree we should add documentation stating that custom fields are possible, but i don't think we should dictate a prefix, just warn to use a field name that is highly unlikely to be used later by developers, and maybe mention examples such as prefix 'cf_' for 'custom field'. or just '_'.
This is a minor issue so i don't agree with dictating to develpers what field name to not use.

**Comment by Wuzzy2** [comment]
I am fine with the `_` prefix as well.

**Comment by paramat** [comment]
#4770 merged.
