### ISSUE TITLE
Allow wire-frame rendering for debugging

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4708]
@Fixer-007 had a great idea on #4686 to debug what is actually retrieved from the server.

We can add that to minetest as a debug option. I have a simple patch that adds it to the F5 key. A client needs the "debug" privilege to use this. (this is better than a compile time option, since it allows the server owner to control this, rather than allowing folks to easily build a cheating client).

We can then add other things guarded by the debug priv.

(If you guys think a compile time is better after all, let me know.

**Comment by SmallJoker** [comment]
It rather should be in the F6 profiler, as a further "tab" or similar.

**Comment by lhofhansl** [comment]
It would show the entire scene as write-frame, not just a small portion. You'd likely want the wire rendering on and still cycle through the profiler options.

**Comment by paramat** [comment]
Cheating is an issue. We added minimap with undrground scanning and are now trying to avoid the cheating this allows.

**Comment by yyt16384** [comment]
> A client needs the "debug" privilege to use this. (this is better than a compile time option, since it allows the server owner to control this, rather than allowing folks to easily build a cheating client).

Making client ignore the privilege is almost as easy as changing a compile time option...

**Comment by lhofhansl** [comment]
Sure. But at least you'd have to read the code, and not just rebuild. If you can ignore privs can do many other cheats.

In any case, I'm fine either way.

**Comment by lhofhansl** [comment]
Closed with #4709
