### ISSUE TITLE
Marking favorite server problem in Minetest version 0.4.14

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#4710]
I just found a glitch and how is that possible to reproduce a glitch?

1. Join any server (for example 2b2t Minetest) and will mark server as favorite;
2. Play around something else or leave server;
3. Now wait, until server changes and description (i think);
4. Now you done. Because server IP and port is same (?);

![image](https://cloud.githubusercontent.com/assets/13905392/19859564/66abafa0-9f8e-11e6-9a3b-fba121e9eb39.png)
This is not used photoshop, trust me.

Server changed, but still has a favorite marked picture (star), it does not have a button "Del. Favorite".

**Comment by SmallJoker** [comment]
Also seen this bug - looks rather trivial to me.

**Comment by Wuzzy2** [comment]
I can confirm this. Long story short, if you start Minetest or go back from a game into the multiplayer tab, if the selected server is a favourite, the “delete” button is missing.
My guess is that a simple check (is favourite y/n) at Minetest start and/or returning from the game is missing here.

**Comment by Fixer-007** [comment]
This was from the beginning after jp commit, I think I've asked about that already but not on github.

**Comment by garywhite207** [comment]
I can also verify that this bug is true, especially on Just Test 2 server

**Comment by paramat** [comment]
Still occuring?

**Comment by rubenwardy** [comment]
Fixed by my JSON serverlist PR
