### ISSUE TITLE
Check user path for sounds

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#4711]
See https://github.com/minetest/minetest/pull/1984#issuecomment-68335660

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by paramat** [comment]
@ShadowNinja are you going to code this?
1+ year bump, any core dev support?

**Comment by paramat** [comment]
Is this a necessary change or just a feature request?

**Comment by rubenwardy** [comment]
Closed in favour of #11936
