### ISSUE TITLE
Visual weapon swing time doesn't correspond with full punch interval

### ISSUE THREAD

**Issue by anonymousAwesome** [minetest/minetest#4714]
It's hard to tell when attack strength will be at full without some sort of visual indicator.  The simplest and most intuitive is matching the physical location of the weapon to the strength of the attack.  When the weapon or item is at normal height the attack would be at full strength, and attacking again while the weapon is still low on the screen would do less damage.

At least part of the relevant code can be found in [sfan's recent pull request](https://github.com/minetest/minetest/pull/4625/commits/4f57a43f6a6ce96de843641b008cc8f7a03416e2), but I don't have the c++ skills to get the code to do what I want.

**Comment by sfan5** [comment]
What you are asking for in the issue title is fixed by my PR, however your description also asks for some unrelated feature.

Please create a second (or third?) issue or edit the title to reflect what your description says.

**Comment by anonymousAwesome** [comment]
Well, no.  Your PR solves the problem "spam-clicking doesn't deal damage."  My problem is "it's not obvious when full_punch_interval has elapsed".  Solving my problem doesn't require solving your problem, and not everybody agrees with your view of the problem.

**Comment by anonymousAwesome** [comment]
Your PR changes the length of time it takes before you can punch again, but it doesn't scale the animation so that "full extension" occurs at exactly full_punch_interval.  The whole point of my request is to make it visually obvious when you can attack at full strength.

In fact, once the animation speed is scaled to full_punch_interval, I *want* the player to be able to attack before full_punch_interval has elapsed, but with a correspondingly lower strength.

**Comment by Ferk** [comment]
#4297 allows setting a duration, in addition to allowing for custom movement.

**Comment by anonymousAwesome** [comment]
It sounds like that would solve the problem.  Can we get a rough estimate on when the branch will be ready for merging?  It's currently listed as WIP.

**Comment by Zughy** [comment]
Is this still a thing?
