### ISSUE TITLE
Formspec API: Set colors of buttons

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4717]
I propose to add a new formspec element for setting the color of all buttons (not the text color, this is already done). This element will belong to the familiy of “coloring”, like `bgcolor` and `listcolors`.

It's syntax could look like this:

`buttoncolors[color_start;color_end;color_border;gradient_direction]`

The idea of this is that buttons are to be style more or less how they already look like. It is meant as a lightwight styling feature.
Each button is styled as a rectangle with a simple gradient in it. And they have a 1px border. This is how the buttons in Minetest look like right now: Vertical gray-gray gradient with black 1px border.

Usage of this formspec element:
The gradient has a color with `color_start` at the top and `color_end` at the bottom. The color of the button border is set in `color_border`.
`gradient_horizontal` is optional and is for setting the gradient direction. It can be set to be either `horizontal` (left to right) or `vertical` (up to down; default value).
If the user wants buttons with an uniform color, the user just needs to set `color_start` and `color_end` to equal values.
The formspec element only needs to be added once per formspec. If multiple `buttoncolors` appear, the final one “wins”.

**Comment by paramat** [comment]
1+ year bump, any core dev support?
