### ISSUE TITLE
Allow to set the object's model's bone sizes

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#4719]
Why cant you change the bone size with `set_bone_postion`?
You can only change rotation and position. In blender you can also change the bone size, so why not in minetest code?
Example usecase: A beam coming out from a with bone rotation turnable thing that shall have a length that reaches its target.

**Comment by est31** [comment]
What do you mean with "size"?

**Comment by sofar** [comment]
Length of the bone, basically. In blender, bones have many more parameters, including bone rotation (around the bone end) and bone rotation (around the axis between bone ends), length, and position of the bone end.

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by paramat** [comment]
Seems like altering bone length would have strange results? And usually we only want to adjust the angle of a players arm for example, not it's length. So perhaps it was seen as not useful.
