### ISSUE TITLE
Mod dependency list has bad line breaks if file has Windows line-breaks on unixoid system

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4720]
Minetest may screw up the list of mod dependencies in the main menu if the line endings of `depends.txt` are in “Windows” mode and Minetest runs on Linux (my system):

![Dependencies Windows mode](https://i.imgur.com/4Bygsqu.png)

The text seems to be a “half line” too high. The file was stored with “Windows” line endings. If I convert `depends.txt` to “UNIX” mode, Minetest shows it correctly:

![Dependencies in UNIX mode](https://i.imgur.com/1Os5DFX.png)

The source `depends.txt` file used for this example:
```
default
farming
stairs
flowers
doors
bakedclay?
moreblocks?
intllib?
```

(No line-break at the final line, but it makes no difference.)

Tested in 70e2df4f86cf4101a10c7e1f7a6ac5cc03992793.

---
My guess:
So the bug here seems to be that Minetest expects `depends.txt` to have “UNIX”-style line endings because I am on Linux. Ideally, Minetest should be able to deal with all 3 possible line ending types (Windows, UNIX, Mac) correctly on any system.

**Comment by est31** [comment]
Mhh, maybe we should decline to accept non linux mode line endings?

**Comment by paramat** [comment]
#4896 merged.
