### ISSUE TITLE
Be able to load Minecraft maps into minetest

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#4726]
Being able to put a Minecraft map (world safe) into Minetest and Being able to play on it in minetest 

I know This Is incredibly Hard (probably inpossible) but if it works It Would Be amazing
Also I know this is 99% sure not gonna happen but I can just ask for it maybe its a good idea

So I know There's gonna be a lot of problems with this Because of missing blocks
Also this is not a mod thing because you can't do this with Mods Just pointing that out :)

**Comment by est31** [comment]
I think this is out of scope for the minetest engine itself. You can use converter tools for this, like this one : https://github.com/minetest-tools/mcimport

**Comment by tobyplowy** [comment]
@est31 I Know but It Would Be cool To Do It in game

Also as far as I know there's no converter tool for Windows

**Comment by hy8wGWme** [comment]
we could also import maps from other voxel games like terasology, creativerse and others there are also these two tools:
https://forum.minetest.net/viewtopic.php?f=12&t=6007
https://forum.minetest.net/viewtopic.php?f=12&t=13709

**Comment by tobyplowy** [comment]
@hy8wGWme good idea :D

**Comment by paramat** [comment]
:-1: This is for external mods or programs, this would be a huge amount of work too.
