### ISSUE TITLE
Main menu clouds sometimes dark after exiting game (when using 'set sky')

### ISSUE THREAD

**Issue by kahrl** [minetest/minetest#4727]
This is a small visual glitch and perhaps not even worth fixing, but I thought I'd mention it.

Whenever you start minetest, the menu clouds are very bright, because the default fog color is white.

Start any game; a new singleplayer minetest_game mgv6 world will do. Dig some dirt and place it around you until you're standing in complete darkness (no sunlight). Exit to menu. Now the menu clouds will be darker, because the fog color is now black-ish.

I believe this happens because the fog color is continuously set to the sky background color while the game is running, however the fog color is never modified while the menu is running. So the menu inherits the fog color from the game that was last running.

**Comment by DS-Minetest** [comment]
i recognized something like that, too
but dont see it as bug, see it as feature, there are rainy clouds :cloud_with_rain: :smile:

**Comment by bigfoot547** [comment]
I saw some of that now that you mention it... :thinking:.

**Comment by ThomasMonroe314** [comment]
Any more updates on this?

**Comment by paramat** [comment]
Can't reproduce it, even with a mod that creates a custom dark sky

**Comment by Fixer-007** [comment]
I have impression that I seen this not long ago too, but not as much dark.

**Comment by bigfoot547** [comment]
@ThomasMonroe314 I got a new computer with windows on, so I still have yet to get minetest :p
I will test it and post results here when I can.

**Comment by ThomasMonroe314** [comment]
@bigfoot547 Ok...wait...O_O Windows!?!?!

**Comment by bigfoot547** [comment]
Yes, I'm very sorry :(. I used to use Debian, but they just don't have the graphics drivers windows has :p
And my EVGA GeForce 1080 FTW2 (*flex flex*) wants drivers...
If it helps, I have a Linux VM ;)

**Comment by ThomasMonroe314** [comment]
> my EVGA GeForce 1080 FTW2 (flex flex)

lol

**Comment by bigfoot547** [comment]
And to be fair, the computer was a build so it didn't have anything on it when we were done making it. We added win10 (ouch) out of our own accord. (That was an adventure...) Thankfully it installs in about 5 minutes on this computer since we needed to reinstall far too many times xD

**Comment by paramat** [comment]
Is now being reproduced.

**Comment by paramat** [comment]
I reproduced it with my moonrealm mod which has custom skybox textures, but it's distant and subtle.

![screenshot from 2018-08-20 17-52-00](https://user-images.githubusercontent.com/3686677/44354544-0d52fd80-a4a2-11e8-990d-263df8b8ee1a.png)

**Comment by IhrFussel** [comment]
The Blood Night event simply sets this sky for each player when it happens:
player:set_sky({r=138, g=7, b=7}, "plain", {})

**Comment by rubenwardy** [comment]
This is due to a static value. @Jordach is working on a patch which may fix this as a result (hopefully)
