### ISSUE TITLE
Can't use minetest.colorize with HUD element text [Feature Request]

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#4731]
So, I tried to use `minetest.colorize()` on a HUD element and it did not change the color.
The only way to get color is to change the `number` element but then the HUD element color is only one color!

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by tacotexmex** [comment]
Bumped into this issue myself. Have to register multiple HUD text items just to display text of differing colors. 

With this solved I can just append `\n`..minetest.colorize(color, nextline) to one single HUD text item.
