### ISSUE TITLE
Remove “Enable all” / “Disable all” button from mod list (Discuss)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4736]
I think the button “Enable all” or “Disable all” in the mod list is probably the most pointless button.
What's the point of enabling all mods at once?
This will very likely result in a very broken world. If you are able to start it at all.

I have never ever needed it, and I am sure I will not need it in the future. The button is more an annoyance since if I accidentally click on it, I can only abort and have to start over with setting up the mod selection. >_>

What's your opinion on this?

**Comment by SmallJoker** [comment]
Never used the "Enable all" button, but the one to disable all mods is quite good for testing worlds with the dummy backend.

**Comment by Wuzzy2** [comment]
Too bad the disable button only is visible after you enabled all mods. xD

**Comment by est31** [comment]
:-1: I like those buttons.

**Comment by stujones11** [comment]
I think the average person using singleplayer mode (where mods are applicable) would probably want to enable all the mods they downloaded. As a modder it can be annoying, I agree but it's not about us.

> Too bad the disable button only is visible after you enabled all mods. xD

That actually sounds like a bug to me.

**Comment by DS-Minetest** [comment]
i think the button was implanted because before it was normal that all mods in the mods folder were activated automatically. with the button it was easier to live with the switch
for non modders the button could be still useful but for modders and server owners it would be more useful to have a search bar. thats because the average players want all the features, they can get. modders pick only the ones they need to prevent extra lag and server owners want to know exactly what mods are installed

> Too bad the disable button only is visible after you enabled all mods. xD

you can double click the button

**Comment by Wuzzy2** [comment]
> I think the average person using singleplayer mode (where mods are applicable) would probably want to enable all the mods they downloaded.

This is not convincing. All a player needs to do is to download tons and tons of mods. You do not need to be a modder for this use case.
OK, I bet 20 or so mods are already enough for trouble. Sooner or later, the chance of a conflict is inevitable. The button can only be useful if you have a VERY small number of mods AND they do not conflict.

But if there are enough people who actually need this button (which I doubt), I retract my suggestion.

My main concern is actually the “Enable all” button, the disable button is of no concern.

@est31: Do you *actually* need/use the “enable all” button? How many mods do you have?

**Comment by rubenwardy** [comment]
I've used it many times. I tend to only play a single world at a time, and so download a load of mods for it all at once

**Comment by NathanSalapat** [comment]
I've never used the enable all button, I don't see the point, as @Wuzzy2 pointed out, it would result in mod conflicts.

**Comment by cheapie** [comment]
I use it a lot since I tend to only keep the mods installed that are relevant to what I'm doing at the time. Besides, it doesn't make a whole lot of sense to me to remove a feature that works fine just because some people don't find it useful.

**Comment by Wuzzy2** [comment]
Okay, apparently these buttons are actively used by some people. I give up my suggestion.
