### ISSUE TITLE
Changing one player bone garbles the entire player model

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest#4739]
The bones in the player model are not positioned correctly. When changing one bone, the whole player becomes garbled. After some experimentation, it seems that the code below will (approximately) put the player parts in the correct positions. Note that the values themselves are not even reasonable: e.g. to place the arm in the default position, it needs to be rotated about 8.5 degrees around one axis, and 180 degrees about another. Similarly, the default body position (angle 0°) makes its back side face forward!

```lua
player:set_bone_position("Body", {x=0, y=-3.3, z=0}, {x=0, y=180, z=0})
player:set_bone_position("Head", {x=0, y=6.75, z=0}, {x=0, y=180, z=0})
player:set_bone_position("Arm_Right", {x=-2, y=6.75, z=0}, {x=180, y=0, z=-8.5})
player:set_bone_position("Arm_Left", {x=2, y=6.75, z=0}, {x=180, y=0, z=8.5})
player:set_bone_position("Leg_Right", {x=-1, y=0, z=0}, {x=180, y=0, z=0})
player:set_bone_position("Leg_Left", {x=1, y=0, z=0}, {x=180, y=0, z=0})
```

The player before and after changing one single bone:
![bones_0](https://cloud.githubusercontent.com/assets/6202053/20090748/4fce3f4e-a58f-11e6-8a7e-fd9b156f67b0.png) ![bones_2](https://cloud.githubusercontent.com/assets/6202053/20090749/4fd142ca-a58f-11e6-8e13-6327d8d22b40.png)

**Comment by paramat** [comment]
LOL.

**Comment by Wuzzy2** [comment]
This issue should go to `minetest_game`.

**Comment by stujones11** [comment]
> This issue should go to minetest_game.

If it turns out to be a problem with the model then yes but my guess is that it's an engine or irrlicht issue.

**Comment by Rogier-5** [comment]
I have done some more investigation, and both the engine and the model have a problem.

I submitted a new issue for minetest_game: minetest/minetest_game#1376

The problem of the engine is, that when one bone is changed the position and angles for all other bones are set to 0. In addition, if a bone position has not been set by a mod, `get_bone_position()` returns 0 for all values, so that a mod can't know what the actual, or default positions are supposed to be. IMO `get_bone_position()` should return the actual values; those should presumably be obtained from irrlicht ?

**Comment by Rogier-5** [comment]
It also appears that there is an aspect of randomness to this issue. It does not actually happen every time, and not always to all bones. Sometimes, the 'other' player (the one who's watching) even needs to logout and login again to see the effect...

**Comment by stujones11** [comment]
I would be interested to see how other models and other model formats like directx behave. I know that bone attachements are screwed up with the b3d model. See #2813 not sure if it is related though.

**Comment by Rogier-5** [comment]
With my changes (minetest/minetest_game#1392), and a freshly-exported b3d file, part of the problem has disappeared (some of it magically...).

Problems remaining:
- When changing from the animated model to a manually positioned model (say for player A), either the client (player B's client) garbles the model immediately, but then a disconnect and reconnect of player B will garble the model, or the client gets it right, but then the model is garbled after disconnect and reconnect of player B.
- The manually positioned model is still rendered about 3.3 nodes higher than the animated model (this might be a problem with the model, or with the export script
- I didn't manage to restart the animation after manually changing some bones
- The server does not return the actual position and orientation of bones when queried, unless they have been set manually first. It will return all zeroes instead. That means it is not possible to obtain the default positions of the bones (except by opening blender, and checking the model).
