### ISSUE TITLE
Mod security: io.lines() does not work/was removed

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#4741]
Please make it work even with secure. There is imo no reason to disable it. Or disable secure by default.
Thanks.

Lua api : https://www.lua.org/manual/5.1/manual.html#pdf-io.lines
Minetest forum: https://forum.minetest.net/viewtopic.php?f=47&t=15842

**Comment by paramat** [comment]
More details on mod security https://forum.minetest.net/viewtopic.php?p=180948#p180948

**Comment by TechnologyClassroom** [comment]
I also ran into this bug.  "Enable mod security Disabled" works.  "Enable mod security Enabled. Trusted mods modname" does not work.

**Comment by ShadowNinja** [comment]
I suppose this was just an oversight.  You can do `io.open():lines()` instead until it's fixed.

**Comment by ShadowNinja** [comment]
This was implemented, it just had a bug which caused it to drop all return values from the insecure `io.lines` backing the secure version.  Fixed in 3af5eef96463510a27cf06b9c3ecc9f1d04cdac6.
