### ISSUE TITLE
default_privs = fly in ~/.minetest/minetest.conf not applied

### ISSUE THREAD

**Issue by ensonic** [minetest/minetest#4748]
from minetest/minetest_game#1369

On the server side:
```
$ grep default_privs ~/.minetest/minetest.conf
default_privs = interact, shout, fly
```
There is no ~/.minetest/auth.txt file (neither on client or server side). Modifying default_privs on the client side has no effect either (as expected). 

Still when a client joins the game (local non public server) he has no fly privilege and one has to

    /grant <username> fly

first. According to
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L854-L857
this should work though.

**Comment by est31** [comment]
Does your minetest build actually read minetest.conf from that location? Can you verify that by changing some other setting?

**Comment by ensonic** [comment]
Yes, the config is used. I just toggled

    fullscreen = true / false

and it shows effect.

**Comment by rubenwardy** [comment]
Default_privs is a server side setting, try typing `/set default_privs` it'll tell you what it thinks the setting is.

Also, iirc when the server starts it prints something like

> reading config from path/to/config

**Comment by kahrl** [comment]
Did you log in as a new user, or one that existed before the setting was changed?

**Comment by ensonic** [comment]
most likely an existing user. Is there some local setting on the client?

**Comment by est31** [comment]
@ensonic `default_privs` only affects new players. If you want to change your privs, edit auth.txt.

I hope the issue is resolved now.

**Comment by ensonic** [comment]
I edited the <world>/auth.txt files, for some reasons the granted privileges where not stored. I'll send a PR shortly to update the minetest.conf.example to mention world/auth.txt.
