### ISSUE TITLE
Diablo-like item size in inventory

### ISSUE THREAD

**Issue by xunto** [minetest/minetest#4755]
It would be good to have an ability to make a diablo-like inventory where items have size in cells.

In this picture helmet is 4 cells while potion is only 1.
![example](https://joshmosey.files.wordpress.com/2013/05/diablo_2_erica_level_76.jpg)

**Comment by est31** [comment]
I think this is out of minetest's scope

**Comment by xunto** [comment]
@est31 why? Isn't it game engine?

**Comment by paramat** [comment]
No thanks, one slot is one item in Minetest.
The 'game engine' argument can be used to justify anything, this game engine can't so everything.

**Comment by dsohler** [comment]
"The 'game engine' argument can be used to justify anything," - It IS used for anything.

**Comment by paramat** [comment]
No, obviously this game engine can't be used for anything.

There's no justification for the huge amount of work needed to implement this.
