### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#4756]
I was playing and I got a random error:
`2016-11-08 21:35:16: ERROR[Main]: ServerError: Lua: Invalid float vector dimension range 'x' (expected -2.14748e+06 < x < 2.14748e+06 got -nan).`

EDIT: I got the same error 2 more times now.

**Comment by NathanSalapat** [comment]
Unfortunately this doesn't give us much to work with.

We need to know what mods you are using, what you were doing when you got this error, if you know.

Take a look at debug.txt and see if any of the lines above or below this error say anything about which mod might be causing it.

**Comment by bigfoot547** [comment]
The mod that I was using was PilzAdam's simple mobs mod. I was spamming the spawnenity command and invariably, I spawned 3 or 4 mobs then the game crashed. The only other notable mod I used was my morecommands mod and I was testing the /butcher command.

**Comment by NathanSalapat** [comment]
Not positive but sounds like a problem with the simple mobs mod, I'd report the error on the forum topic for that mod, and it's github, if it has one.

**Comment by Rogier-5** [comment]
You'll probably get more meaningful information by patching `src/script/common/c_converter.cpp` as follows:

In the following code:
```lua
#define CHECK_FLOAT_RANGE(value, name) \
if (value < F1000_MIN || value > F1000_MAX) { \
	std::ostringstream error_text; \
	error_text << "Invalid float vector dimension range '" name "' " << \
	"(expected " << F1000_MIN << " < " name " < " << F1000_MAX << \
	" got " << value << ")." << std::endl; \
	throw LuaError(error_text.str()); \
}
```
change: `throw LuaError(error_text.str()); \` to `luaL_error(L, error_text.str().c_str()); \`
**don't** forget the trailing `\`, and make sure it's the last character on that line.

And keep an eye on my PR #4425. It can't be merged atm, but I plan to push an updated version sometime in the coming week (if I don't get distracted by other important PRs). It won't make the problem go away, but it _will_ give more meaningful feedback.

**Comment by Rogier-5** [comment]
@bigfoot547: I pushed a new version of #4425. If you use that, it should print the lua file and line number when there is a range error.

**Comment by bigfoot547** [comment]
I also get the problem every time a creeper blows up. That mod is no longer supported, thus the problem will never be fixed.

**Comment by paramat** [comment]
Since it's a probably a mod issue use the code posted here and try to get help in the forum, then later you may find out it's partly an engine issue, then you can open an issue here.
