### ISSUE TITLE
minetest.add_item and minetest.add_entity are unreliable

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4759]
While trying to debug my [Tutorial subgame](https://forum.minetest.net/viewtopic.php?t=10192), I have had trouble with using `minetest.add_item`. I use this function to spawn the items around the tutorial world.

This function seems to be pretty unreliable. After several test runs I figured out that `minetest.add_item` may or may not actually spawn an item at the specified position. The really sad part is, I always get an `ObjectRef` returned, and apparently I only get `nil` when I plugged in blatantly incorrect information. So this function is useless in determining whether the spawning was successful.
The problem is, currently `minetest.add_item` can not be used to reliably spawn items.

In a simple flat test world, I have used the `luacmd` mod to debug this function a bit more. And I noticed some patterns:
If I spawn an item close to me, it always spawns. If I spawn an item far away from me, but still in a generated chunk, it does seem to spawn. It is not instantly visible but when I move to the coords, the item quickly appears. When I spawn the item very far from me, in a non-generated chunk, and then immediately teleport to this place, the item is NOT there. Which is odd since I still get an `ObjectRef` returned, and not `nil`.

Also, the documentation of this function is rather poor IMO. Corner cases are not explained at all.

I think the function should be fixed to guarantee an item spawn for correct input, or at least return `nil` if spawning failed for some reason.

An improvement of the docs would also be appreciated, in case this behaviour is somehow intentional or there is another way I am supposed to go.

Tested in c05aac3766e88530fcf5d38a8c25c994b792b324

**Comment by sfan5** [comment]
> When I spawn the item very far from me, in a non-generated chunk, and then immediately teleport to this place, the item is NOT there.

This is expected but undocumented behaviour. `add_item()` always returning a valid ObjectRef seems like a bug though.

**Comment by Wuzzy2** [comment]
@sfan5: What other conditions must be met for `minetest.add_item` to guarantee an item spawn?
Is it safe to assume it will succeed when called inside a bounding box of an `on_generated`? Or do I have to check/wait for other conditions as well?

**Comment by tenplus1** [comment]
When spawning an entity that doesn't exist I always have to check for get_luaentity() to make sure it's actually there.

**Comment by Wuzzy2** [comment]
Something seems to be seriously broken about `minetest.add_item`. I have written a small test mod. My goal was to reliably find a way to spawn items inside `minetest.register_on_generated`. This seems to be impossible. My assumption is that it is OK to attempt to spawn items inside generated MapChunks, so as long I respect their bounding boxes, the items should spawn reliably, right?
Sadly, no. This is not the case.

The test mod spawns one item per generated MapChunk and a “pedestal block” below it to mark the position on which the item is supposed to spawn. The first thing I note here is that `minetest.set_node` reliably sets the node in loaded MapChunks. But not every pedestal has an item on it.

The test mod is a bit chaotic, but the most important thing this mod shows is that items often fail to spawn even long after the mapchunk has been loaded. The test is simple:
If the pedestal block is not cobblestone (anymore), then an item MUST be on the pedestal.

But I noticed some pattern, I guess: If you run close to the cobblestone pedestal before the item spawn attempt happens, it is much more likely that the item spawns.
But if the pedestal block is in visible range (which implies it is generated), the item may NOT spawn! Quite interesting …
I guess my first post is not 100% correct.

For figuring out more stuff, I added some testing stuff. The item itself is attempted to spawn 7 seconds after the mapchunk was loaded. I already know the item almost never spawns if I do not add this delay, so this is probably another issue.
After 1 second of an (apparently) successful item spawn attempt I do a “recheck” which means the item object is checked if it is still there. Often this recheck fails, which is very interesting. Because this means the item object which you previously got from `add_item` is not valid anymore after 1 seconds. Did Minetest spawn the item, but then deleted it immediately afterwards? Is the return value just plain wrong? Hmmm......

The block type has meaning:
* Cobblestone: Item was not spawned yet
* Gold Block: Attempt to spawn item has happened the spawned item seems to exist
* Desert Cobblestone: Attempt to spawn item has happened, but item object seems to be non-existant (never happened)
* Diamond block: Recheck was successful (but sometimes even this is a false-positive)
* Cactus: Recheck failed

Items are generated on a flat plane only. Test this in the flat mapgen in Minetest Game and fast mode.
Here's the mod code:
```
minetest.register_on_generated(function(minp, maxp, seed)
	if not (minp.y <= 8 and maxp.y >= 8) then
		return
	end
	local pos = {}
	pos.x = minp.x + 2
	pos.y = 8
	pos.z = minp.z + 2

	local pos2 = {}
	pos2.x = pos.x
	pos2.y = 6
	pos2.z = pos.z

	minetest.set_node(pos2, {name="default:cobble"})

	local ipos = pos
	minetest.after(7, function(ipos)
		--minetest.log("error", "ATTEMPTED ITEM SPAWN: "..minetest.pos_to_string(ipos))
		local o = minetest.add_item(ipos, "default:goldblock")
		ipos.y = 6
		minetest.log("error", dump(o:get_luaentity()))
		if o:get_luaentity() ~= nil then
			minetest.log("error", "SUCCESSFUL ITEM SPAWN: "..minetest.pos_to_string(ipos))
			minetest.set_node(ipos, {name="default:goldblock"})
			minetest.after(1, function(p)
				minetest.log("error", "RECHECK RESULT:")
				minetest.log("error", dump(p.o:get_luaentity()))
				if p.o:get_luaentity() == nil then
					minetest.set_node(p.pos, {name="default:cactus"})
				else
					minetest.set_node(p.pos, {name="default:diamondblock"})
				end
			end, {o=o, pos=ipos})
		else
			minetest.log("error", "FAILED ITEM SPAWN: "..minetest.pos_to_string(ipos))
			minetest.set_node(ipos, {name="default:desertcobble"})
		end
	end, pos)

end)
```

**Comment by Wuzzy2** [comment]
It gets worse: I think I just observed the very same behaviour with normal entities as well (`minetest.add_entity`).

So it's not just about spawning items, but spawning entities in general.
To clarify:
* **You can't rely on minetest.add_entity or minetest.add_item to spawn an entity, even if it is inside an `on_generated` area**.
* **You can't trust the return value** either: They never seem to return `nil`, no matter if the item actually spawned or not. So even workarounds will be hard.

This is pretty bad IMO.


Allow me to make some guesses:

* Guess 1: Minetest *does* indeed spawn the entity but immediately destroys it afterwards
* Guess 2: To trigger the fail, the entity must spawn far enough from any player

**Comment by Wuzzy2** [comment]
Here's another test mod for your convenience.
It adds the “spawntest” command, when you enter it, it tries to generate 1000 entities along the X axis with `minetest.add_entity`. You can then walk along the line to count if the number matches the expectation. It also counts how many times minetest.add_entity returned `nil`.

You can use a different number by setting the parameter, e.g. `/spawntest 100`.

```
local t = "default_silver_sand.png^[colorize:#FF000080"

minetest.register_entity("test_add_entity:entity", {
	visual = "cube",
	visual_size = { x=0.9, y=0.9 },
	collisionbox = { -0.45, -0.45, -0.45, 0.45, 0.45, 0.45 },
	textures = { t,t,t,t,t,t },
})

minetest.register_chatcommand("spawntest", {
	params = "[<entities_to_spawn>]",
	description = "Spawn many test entites along the X axis.",
	privs = {},
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		local startpos = player:getpos()
		startpos.y = startpos.y + 1
		local max = 1000
		if param~=nil then
			max = tonumber(param)
		end
		if type(max) ~= "number" then
			max = 1000
		end
		local p = table.copy(startpos)
		local passed = 0
		local failed = 0
		for i=1, max do
			p.x = p.x + 1
			local ret = minetest.add_entity(p, "test_add_entity:entity")
			if ret == nil then
				failed = failed + 1
			else
				passed = passed + 1
			end
		end
		minetest.log("error", "minetest.add_entity reported "..passed.." succeeded spawns.")
		minetest.log("error", "minetest.add_entity reported "..failed.." failed spawns.")
	end,
})
```

Testing with 1000 spawns, the function pretends for me that all spawns succeeded. But when I actually walk along the line, I only find around 100 enties, but this number varies greatly.

Hint: For easier counting, just use your coordinates.

**Comment by celeron55** [comment]
It might be that minetest.add_entity only works when the position is inside an active block, and otherwise doesn't.

It would seem the code attempts to handle that situation but maybe there's an issue with id overlap or maybe the entity gets destroyed when the block is activated or something.

Active blocks are those that aren't further away from a player than active_block_range. They are the blocks in which objects (that can be lua entities) are deserialized from their static state and are instead handled as active objects that can move and be modified. Last time I checked, it was not possible to make a block active in any other way than going near it as a player.

Could be related to #194 or #4759 for sure. Each of these involve the active/static object system.

**Comment by rubenwardy** [comment]
>  Last time I checked, it was not possible to make a block active in any other way than going near it as a player.

Force load anchors?

**Comment by celeron55** [comment]
Hmm, I guess those do that, yes.

**Comment by azekillDIABLO** [comment]
Does 'minetest.add_item' works at all? It seems like it doesn't... My mods (MILA) that used it to make mobs drops doesn't work anymore though it perfectly worked in 4.15...

Please check this: https://github.com/azekillDIABLO/mila/issues/4

**Comment by Wuzzy2** [comment]
> It might be that minetest.add_entity only works when the position is inside an active block, and otherwise doesn't.

How can this hypothesis be tested?

**Comment by LoneWolfHT** [comment]
Haven't read everything here but you might be able to use nodes and LBMs to spawn items
(The node would basically allow you to put an item inside of it (via meta/an inventory). When you load the node it would replace itself with its item)

**Comment by orwell96** [comment]
The add_entity function and in general the whole Minetest entity handling is somewhat broken from my experience. It's the reason why, whenever I mod something with entities (e.g. advtrains), I do not use Minetest's static object handling at all. advtrains only spawns wagon entities when it is sure that the position is loaded, and entities are never saved using staticdata.

It appears to be a reliable way to check if an ObjectRef in Lua is still valid by calling `object:get_yaw()`. If this returns nil, the object is unloaded or destroyed.

gpcf and me stumbled upon another oddity today: if you're spawning (add_entity()) an entity that has ˋstatic_save = falseˋ, it appears to be statically saved anyway, triggering warnings like "ServerEnv: Trying to store id = 0 statically but block (-173,0,42) already contains 13772 objects." The expected behavior would be to either not even create it or destroy it immediately.

**Comment by sfan5** [comment]
> if you're spawning (add_entity()) an entity that has ˋstatic_save = falseˋ, it appears to be statically saved anyway, triggering warnings like "ServerEnv: Trying to store id = 0 statically but block (-173,0,42) already contains 13772 objects."

Please open a separate issue.

**Comment by gpcf** [comment]
I have problems with add_entity since I upgraded minetest to 5.3.0. This is the code that fails:


```
                local obj = core.add_entity(pos2, "drawers:visual")
                if bdir.x < 0 then obj:set_yaw(0.5 * math.pi) end
                if bdir.z < 0 then obj:set_yaw(math.pi) end
                if bdir.x > 0 then obj:set_yaw(1.5 * math.pi) end
```

It didn't fail before the upgrade

**Comment by gpcf** [comment]
```
2020-09-03 00:23:57: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'drawers' in callback LuaLBM::trigger(): ...s/minetest-server/.minetest/mods/drawers/lua/helpers.lua:106: attempt to index local 'obj' (a nil value)
2020-09-03 00:23:57: ERROR[Main]: stack traceback:
2020-09-03 00:23:57: ERROR[Main]:       ...s/minetest-server/.minetest/mods/drawers/lua/helpers.lua:106: in function 'spawn_visuals'
2020-09-03 00:23:57: ERROR[Main]:       ...es/minetest-server/.minetest/mods/drawers/lua/visual.lua:461: in function <...es/minetest-server/.minetest/mods/drawers/lua/visual.lua:435>

```

our drawers mod being found on `https://github.com/minetest-mods/drawers`.

**Comment by gpcf** [comment]
a similar bug has also happened in mesecons
```
2020-09-02 18:11:59: ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'mesecons' in callback environment_Step(): ...st-server/.minetest/mods/mesecons/mesecons_mvps/init.lua:221: attempt to index a nil value
2020-09-02 18:11:59: ERROR[Main]: stack traceback:
2020-09-02 18:11:59: ERROR[Main]:       ...st-server/.minetest/mods/mesecons/mesecons_mvps/init.lua:221: in function 'mvps_move_objects'
2020-09-02 18:11:59: ERROR[Main]:       ...server/.minetest/mods/mesecons/mesecons_pistons/init.lua:94: in function 'old_action_on'
2020-09-02 18:11:59: ERROR[Main]:       ...etest-server/.minetest/mods/mesecons_ratelimiter/api.lua:36: in function 'action_on'
2020-09-02 18:11:59: ERROR[Main]:       ...est-server/.minetest/mods/mesecons/mesecons/internal.lua:190: in function <...est-server/.minetest/mods/mesecons/mesecons/internal.lua:183>
2020-09-02 18:11:59: ERROR[Main]:       ...-server/.minetest/mods/mesecons/mesecons/actionqueue.lua:93: in function 'execute'
2020-09-02 18:11:59: ERROR[Main]:       ...-server/.minetest/mods/mesecons/mesecons/actionqueue.lua:84: in function <...-server/.minetest/mods/mesecons/mesecons/actionqueue.lua:61>
2020-09-02 18:11:59: ERROR[Main]:       /usr/share/games/minetest/builtin/game/register.lua:429: in function </usr/share/games/minetest/builtin/game/register.lua:413>
2020-09-02 18:11:59: ERROR[Main]: stack traceback:

```

**Comment by sfan5** [comment]
It's possible that `drawers:visual` deletes itself right when being spawned: https://github.com/minetest-mods/drawers/blob/d3850ca205b24a501203c20f4a6a5f2a25abed32/lua/visual.lua#L81-L84
Check if that's the case, if it is then this _isn't_ a bug.

The mesecons thing is likely another bug, the line numbers also don't match up with whats in master.

**Comment by gpcf** [comment]
it really was that bug, I just submitted a PR upstream. It also fixed a mysterious bug with maple drawers not working.

**Comment by grorp** [comment]
Here is another test case:

Create a devtest world with this mod and the singlenode mapgen.

``` Lua
minetest.register_entity("test:test", {
	initial_properties = {
		visual = "sprite",
		visual_size = vector.new(10, 10, 10),
		textures = {
			"default_apple.png",
			"default_apple.png",
			"default_apple.png",
			"default_apple.png",
			"default_apple.png",
			"default_apple.png",
		},
		pointable = false,
		physical = false,
	},
})

minetest.after(0, function()
	minetest.add_entity(
		vector.new(0, 10, 0),
		"test:test"
	)
end)
```

When you open the world for the first time, the entity isn't spawned. Probably because the map isn't generated yet. Open the world a second time, and there is it.

What I need this for is a (yes, another) maze game:

``` Lua
local storage = minetest.get_mod_storage()

minetest.after(0, function()
    if storage:get_int("generated") == 0 then
        storage:set_int("generated", 1)

        -- Generate a maze and write it to the map with a VoxelManip
        -- Spawn monsters with `minetest.add_entity`
    end
end)
```

But I'd be very open to ways to do the whole thing so that it doesn't even touch this bug.

**Comment by Wuzzy2** [comment]
I think I found a workaround. If you call `minetest.load_area` around the entity position right before calling `minetest.add_entity`, entity spawning seems to be reliable. I'm not 100% sure about this tho.

I believe the reason this works is because Minetest aggressively removes entities in `ignore`, and Minetest does not like it when you try to spawn an entity in `ignore`. (This is just a guess.)

**Comment by Wuzzy2** [comment]
I suggest to assign this issue a high priority.

Rationale: *spawning an entity* is one of the most fundamental features of the Lua API. Without this, you can't do much with entities. Yet this function is broken; entity spawning can fail unpredictably with no error reporting available (checking the return value for nil doesn't work either, see above). This makes dealing with entities in Lua a nightmare. I don't know how often I had to fight against this bug in my mods and games.

**Comment by appgurueu** [comment]
We're currently discussing what should happen when an entity is spawned in a not yet generated area (in sfence's fix PR). The current behavior is clearly broken: You get an ObjectRef (rather than `nil`), but once the area is generated, that entity will be removed. Now there are two ways to fix it:

* Make `add_entity` return `nil` (failure) if `pos` is in a not yet generated area.
* Don't remove all entities when generating a mapblock. This would let you spawn entities in areas before these areas are generated.

Unfortunately it's not clear what the proper fix is; the docs don't mention this case. So I'm asking the modders subscribed to this issue: What would you expect to happen?

**Comment by Wuzzy2** [comment]
I prefer the first option: Return `nil`.
Because then you can actually write functional fallback code, such as trying again in 10 seconds or loading/emerging the area first and then trying again. And because this solution seems the most disruptive. The documentation just needs to mention the new `nil` case. Backwards-compability is no concern here because the current behavior is just broken anyway.

And to keep the code clean, I would not just return `nil` but actually not spawn the entity to begin with (since it would be useless anyway).

The second option seems a little far-fetched. If I remember correctly, it was a deliberate design decision earlier to not allow active entities to exist in unloaded areas. And I think this decision should be kept.
