### ISSUE TITLE
Mapblock not rendered by client while within viewing range

### ISSUE THREAD

**Issue by Rogier-5** [minetest/minetest#4763]
The client will not render some mapblocks that are within the viewing range. See the image:

In the case below, after just a small movement forward, the mapblock in question is shown. A small movement backwards makes it disappear again.

![screenshot_20161110_105704](https://cloud.githubusercontent.com/assets/6202053/20172283/be1656e8-a734-11e6-866e-c3cf229c7dee.png)
![screenshot_20161110_110236](https://cloud.githubusercontent.com/assets/6202053/20172409/38d32f1e-a735-11e6-888a-3b6256a5c948.png)

**Comment by Fixer-007** [comment]
Does it happen if you increase view range?

**Comment by Rogier-5** [comment]
If I increase the viewing range, the problem moves farther away, but as far as I manage to see, there's always one (or more) mapblocks missing before the fog gets too thick to see anything.

**Comment by Fixer-007** [comment]
In the screen corners?

**Comment by Rogier-5** [comment]
More or less straight ahead of me. Notice that I am standing near, but not too close to a mapblock border to my right. When I move towards that border, i.e. to the right, the other mapblock that *is* visible (on the left side) disappears as well. When I move further, the corresponding mapblock to the right appears in turn. Following screenshots with a viewing range of 30. The strange fog coloring is due to another bug, which comes in handy at this moment. Note the z-coordinate.

![screenshot_20161110_151451](https://cloud.githubusercontent.com/assets/6202053/20179941/9edadf96-a758-11e6-8bb3-72d823af9f12.png)
![screenshot_20161110_151457](https://cloud.githubusercontent.com/assets/6202053/20179942/9ede377c-a758-11e6-8530-d3ce4fd08951.png)
![screenshot_20161110_151502](https://cloud.githubusercontent.com/assets/6202053/20179943/9ee3967c-a758-11e6-91d9-2b548bef2bfe.png)

**Comment by est31** [comment]
cc @lhofhansl

**Comment by lhofhansl** [comment]
That looks like an issue with occlusion culling.
@Rogier-5 any chance to try without 2b21cac1?

**Comment by lhofhansl** [comment]
I have not seen this in any playing or testing I did.

It's possible it's another shader issue too with the fog, but an entire mapblock missing would be weird.

**Comment by lhofhansl** [comment]
I see this too when I set my view range to a very small value.
This has nothing to do with the fog then, since the whole block is not rendered, it also nothing to do with occlusion culling, since that does not take the view range into account.

I suspect this is an old bug. My guess is that we getting into the ballpack of the mapblock size (the diagonal of a mapblock is 27.7), and that such short view range are just not useful.

**Comment by Rogier-5** [comment]
I fixed the issue. The problem was that the client would not compute the distance from the camera to a mapblock correctly. See PR #4765
