### ISSUE TITLE
Credit where credit is due

### ISSUE THREAD

**Issue by Zeno-** [minetest/minetest#4769]
I would like to see the next release dedicated to those who really keep minetest alive: the people who operate public servers. It is, in my opinion, that they are long overdue for recognition. Put them in the credits for at least the next release. They deserve to be there.

**Comment by est31** [comment]
Maybe for the modder community as well?

**Comment by Zeno-** [comment]
@est31 of course

I want the release to acknowledge all the hard work put into the game other than the "core devs"

**Comment by lisacvuk** [comment]
Maybe add currently installed mods' authors to the list, too?

**Comment by sfan5** [comment]
Release dedications will become meaningless if we organize a who-wants-a-dedication-next-release contest everytime :-1: :-1:

**Comment by sofar** [comment]
I'm with @sfan5. If you have to debate it, you probably shouldn't.

**Comment by paramat** [comment]
If this is done, just simply state "all server admin / modders / devs / whatever". Any list of everyone will be huge, lots of work to compile, and will always leave some out. Being left out of a list of everyone would be an insult.
However i see no need to do a dedication except in exceptional circumstances (RBA), and we should not dedicate to RBA again.
Am neutral.

**Comment by Zeno-** [comment]
I don't think I necessarily meant that every individual be named personally. A general thanks to the modding "community" and those running servers would probably suffice

**Comment by garywhite207** [comment]
I agree with @Zeno- . It would be ridiculous to have a separate personal dedication for each version. A general thanks, or maybe just saying "This version of Minetest is dedicated to everyone, devs, modders, server owners, & players alike", and then everyone will be happy.

**Comment by C1ffisme** [comment]
What defines someone who 'runs a public server'? Anybody that runs any server that isn't hosted on their own LAN? Anyone who's server appears in the 'Client' menu of the Minetest main menu?

**Comment by garywhite207** [comment]
Basically, yes. Any server that appears in the Client menu of the Minetest
client is considered a public server

**Comment by C1ffisme** [comment]
@garywhite207 That is... Not a small number to put in the credits.

I wanted to count how many I saw in the list, but there were just too many. I think it has to be more than 20.

**Comment by rubenwardy** [comment]
> I think it has to be more than 20.

163 is certainly more than 20

**Comment by garywhite207** [comment]
You just put "This version is dedicated to all the server owners of
Minetest". Plain and simple.

**Comment by rubenwardy** [comment]
I don't agree with it being "dedicated" as that implies not all versions are thankful - much better just to add a thank you

**Comment by paramat** [comment]
^ I agree.

**Comment by est31** [comment]
Me too.

**Comment by garywhite207** [comment]
Makes sense.

**Comment by ShadowNinja** [comment]
I'd be happy to see something along the lines of "...and the community of modders, artists, server owners and more that help make Minetest great!".

We should also probably remove the " active contributors" and "previous contributors" lists because these lists seem to be pretty subjective and out of date, and of course they only recognize contributors that make code contributions to the engine.  If we keep the lists I think they should be automatically generated from the git history on each release.  They could be updated by the release making script.

**Comment by paramat** [comment]
> We should also probably remove the " active contributors" and "previous contributors" lists because these lists seem to be pretty subjective

I agree, either include all contributors or none. The amount of contributions to be included is arbitrary, and the line between active and previous is arbitrary too, people take breaks and come and go.
Better to list current core devs, plus maybe a long list of github usernames of all contributors in engine and game, maybe ordered by commit number.

**Comment by Zeno-** [comment]
> I'd be happy to see something along the lines of "...and the community of modders, artists, server owners and more that help make Minetest great!".

yes, and this is really want I originally meant. I described myself poorly

**Comment by paramat** [comment]
Meh, the intention is sweet, but i'm just not comfortable with a vague thank you to absolutely everybody :-1: Sorry.

**Comment by Zeno-** [comment]
@paramat, how is thanking the people who make mods and run servers vague?

**Comment by paramat** [comment]
Yeah, it's not vague, i mean vague in another sense, as in saying thank you to a huge number of people, to me personally it feels unfocussed, and like Minetest thanking itself.
They do deserve credit, just i feel not in MT credits.
