### ISSUE TITLE
'fixed map seed' is numeric only which should be documented

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4776]
Hi there, i tried to find a cool seed for my upcoming servers world.
I used `fixed_map_seed = ` with letters and special characters seems to be effectless - in single player like on server, the seed i see in the client with `F5` is always different.

**Comment by tchncs** [comment]
Okey, it must be numeric, this should be mentioned in the api. :)

**Comment by paramat** [comment]
Ah so alphanumeric seed is a menu only-thing.

**Comment by tchncs** [comment]
no, as far as i expected, minetest just generates its own seed if you use a non-numeric seed / a too long seed.. .

**Comment by paramat** [comment]
I'm fairly sure alphanumeric is converted consistently, otherwise alphanumeric seeds would not be usable.

**Comment by Wayward1** [comment]
They are. I've used the same word many times and received the same mapgen/numeric seed each time.

**Comment by paramat** [comment]
@tchncs please can you edit the title to something like 'document that 'fixed map seed' is numeric only'?

**Comment by kwolekr** [comment]
I don't understand the problem here. fixed_map_seed accepts either decimal number format, hex number format, or an arbitrary string.  It saves the seed in the decimal form to the world's map_meta.txt.

**Comment by paramat** [comment]
Confirmed no issue.

**Comment by Routhinator** [comment]
What is the max length? Why does the UI not prevent us from adding more characters than possible? Why is fixed_map_seed not found in the documentation with any of this information recorded? So many questions from such an old issue...

For those still finding this in 2025 when looking for _any_ sort of cohesive documentation on this setting:

`fixed_map_seed` appears to have the following requirements to work:
* Must be a positive integer (numbers only)
* Must be no more than 20 digits long
* There appears to be other rules for the seed that I cannot nail down - taking an existing seed from `map_meta.txt` and pasting it into `fixed_map_seed` will work, but trying to randomly come up with a number doesn't seem to work. The number `08068141353848008651` comes out into `map_meta.txt` as `18446744073709551615` for some reason. `08068141353848008651` is less than `18446744073709551615` so it's not a max value or something. I'm at a loss. This needs proper documentation as the issue originally asked for.

In mapgen v7, in addition to the unknown rules; when using a seed that does consistently pass from `fixed_map_seed` to `map_meta.txt` - I've gotten the same map from it 2 times in a row, then something completely different on the 3rd try - without changing any mod or code. Simply wiping everything but the world.mt file and letting it regen from scratch. Every time after the third try was different though the seed stayed the same.

I'm thinking this may have to do with the various cave,mountain etc blocks in `map_gen.txt` having their own seed values.. perhaps the answer here is to completely skip using `fixed_map_seed` and instead keep the entire `map_gen.txt` when wanting to regenerate the same map.. pending testing once I find a map that works for my testing purposes again.

[EDIT]: Nope, keeping the full `map_meta.txt` I get different results.

**Comment by sfan5** [comment]
quoting from above:

> I don't understand the problem here. fixed_map_seed accepts either decimal number format, hex number format, or an arbitrary string. It saves the seed in the decimal form to the world's map_meta.txt.

you can see the code here:
https://github.com/luanti-org/luanti/blob/f390137d6eae6cc94208b3d9cc3556d4d5cc9754/src/util/string.cpp#L295-L309

If it can't be [parsed](https://en.cppreference.com/w/cpp/string/byte/strtoul.html) as an unsigned 64-bit number, the string will instead be hashed into a number.

> I'm thinking this may have to do with the various cave,mountain etc blocks in map_gen.txt having their own seed values.. 

No, those are relative to the map seed.

> What is the max length? Why does the UI not prevent us from adding more characters than possible?

Since - as explained - it can be any string, there's no maximum length or validation.

**Comment by Routhinator** [comment]
Oh - so because the `08068141353848008651` number I used has a leading zero, the game had to hash it to have a leading digit. That explains that part.

Strange - wonder why I cannot get the same result twice when I use `18446744073709551615`. Not just decorations, but the actual terrain does not stay the same either.
