### ISSUE TITLE
Modding Around Death Screen

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#4777]
I think that you should be able to mod around the death screen and override it using something like:
`player:set_die_formspec(string or nil)`. If The argument is nil, don't show a formspec, but instantly respawn.

**Comment by red-001** [comment]
The death screen is already a formspec so it shouldn't be too hard to add.

**Comment by olivattaque** [comment]
I second that !
I run into limitations with the death screen (impossible to override or prevent) and the bones mod (lack of api which force me to take the bones mod code into mine) when trying to implement a "second chance" mod (like in borderland or cod).
See this post for more information and ideas for more modding features https://forum.minetest.net/viewtopic.php?f=47&t=15630, I'm gonna write a reply with the current state when I can.
For example with what bigfoot said, i would like to be able to prevent the death screen but don't respawn instantly (manage it myself), control the flow of the bones mod (don't put the bones until I say so).
Thanks for your work ^^ Don't hesitate to ask more info or whatever :)

**Comment by red-001** [comment]
see #4798. 
@olivattaque 
You can stop a player from being moved on respawn by returning true in `register_on_respawnplayer` and you can save the player inventory, remove it and restore it using minetest.after to stop the bones mod from placing bones. You can see my duel mod for an example of how to do it.

**Comment by bigfoot547** [comment]
Well, since #4737 has been merged, I will close the issue!
:smiley:

**Comment by red-001** [comment]
Didn't @orwell96 say that #4737 covered metadata and `show_formspec()` ?

**Comment by bigfoot547** [comment]
Well, just now I got the newest commit and tested it out.
The results are that it actually does close the death screen when run like
this:
`minetest.close_formspec(name, "")`.
Unless I didn't understand what you said.

**Comment by orwell96** [comment]
I meant, showing a death formspec string that is '' will result in an empty formspec opened. close_formspec() works independent of this.

**Comment by bigfoot547** [comment]
That is what I thought when I saw the PR, but if you run in a minetest.after(0) this code:
minetest.close_formspec(name, "") then it will close the death formspec.
