### ISSUE TITLE
Crash on latest git due to recent commit.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#4778]
> ServerError: Lua: Runtime error from mod '' in callback item_OnPlace(): /usr/local/share/minetest/builtin/game/item.lua:278: attempt to call global 'check_attached_node' (a nil value)

A recent commit made this function and a few others local to their own file, thus hiding them from the rest of the engine and games.

Edit: commit is this one: 649448a2a91fbf3e944b2f2e739f4e2292af1df0

**Comment by sofar** [comment]
I think this needs to be moved to `minetest_game` then

**Comment by est31** [comment]
No, sorry, my fault.

**Comment by sofar** [comment]
Ahh I see, yes, this is in `builtin`

**Comment by est31** [comment]
@BluebirdGreycoat can you test the PR I opened whether it fixes your issue?

**Comment by NathanSalapat** [comment]
Also having this error with the latest daily build. Placing a torch will crash the game.

**Comment by JurajVajda** [comment]
please fix!

**Comment by BluebirdGreycoat** [comment]
This appears to fix it. Thanks!

**Comment by NathanSalapat** [comment]
Fixed for me as well.
