### ISSUE TITLE
Sound fade-in/fade-out

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4786]
Currently sounds don't support fade-in/fade-out. This can be worked around for starting sounds by duplicating your sound files with a fade-in version, assuming you need both versions, but cannot be worked around for stopping sounds, because in general you do not know in advance when you might call `sound_stop` on a sound.

I propose that parameters are added for `sound_play` for specifying fade-in/fade-out, and to `sound_stop` for fade-out. If a sound finishes without being stopped prematurely, it should use the fade-out setting set in `sound_play`. A sound stopped by `sound_stop` should use the fade-out given there.

**Comment by SmallJoker** [comment]
PR #4304

**Comment by paramat** [comment]
#5340 merged.
