### ISSUE TITLE
Mod store like rubenwardy's Mod Manager for Android

### ISSUE THREAD

**Issue by garywhite207** [minetest/minetest#4787]
Suggesting a mod store similar to rubenwardy's mod manager for Android. If not in the minetest engine, then maybe as a separate Windows/Linux application.

**Comment by paramat** [comment]
https://github.com/rubenwardy/mtmods4android

**Comment by paramat** [comment]
There are other issues open for mod store, you might want to see those, however this issue may be unique enough to not be a duplicate.

**Comment by rubenwardy** [comment]
#4666
