### ISSUE TITLE
Android 0.4.14 crashes on pre-join errors

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#4789]
The 0.4.14 stable version of Android crashes on:

- Server not reachable
- Incorrect password
- Empty password
- Custom pre-join error messages

It makes the app partially unusable because players don't know what happened since they don't see ANY errors.

I'm not sure if this has been fixed in the dev version yet but most players on Android play the stable build from the Play Store or other stores, so it would be nice if you could fix this in the current stable release too.

**Comment by Wayward1** [comment]
Could you try my recent dev build here [https://forum.minetest.net/viewtopic.php?f=42&t=12169&start=25#p237996](url) and see if it works?

**Comment by est31** [comment]
I think this should be resolved before a release.

**Comment by paramat** [comment]
@MoNTE48 are you able to help?

**Comment by MoNTE48** [comment]
I have never experienced such problems.
I do not follow Minetest after 0.4.14 release, sorry

**Comment by paramat** [comment]
Ok no problem, thanks anyway.

**Comment by rubenwardy** [comment]
540071002e949dfa7be3999a58be46d75d7631e9
