### ISSUE TITLE
Let mods suppress or modify the initial message sent by server on player join.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#4790]
Whenever a player joins a server, the first message they see is the server status information, followed by the MoTD, if one is set. It would be great if it were possible to modify this message, or even suppress it completely. I searched a little bit through the code for likely keywords to see if there was any function in core that I could override to do this, but didn't find any. I don't know if this can be easily implemented, or if it would require changes in C++, but I think that server owners especially would find this useful.

An example use would be the ability of a mod to override the message in such a way that players with an invisibility priv (such as a hidden admin) are not shown in the client list that is sent to players connecting.

**Comment by nerzhul** [comment]
I looked at the current code, i think there is only one way to do it properly using the current callbacks.

I think we should add a setting to disable this line and you will use on_player_join event to generate your custom line

@sfan5 @sofar @Zeno- did you agree with this mode ?
