### ISSUE TITLE
chat_message_limit* seems to be broken

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4795]
Hi there, i just tried the new spamcontrol feature.
The 500 chars limit is working but the rest seems to be broken.

```
chat_message_limit_per_10sec = 6.0
chat_message_limit_trigger_kick = 6
```

I flooded the chat with more than 20 messages with success.

**Comment by Fixer-007** [comment]
as admin?

**Comment by tchncs** [comment]
No, "in case" i joined with a test account. :)

**Comment by kaeza** [comment]
I just tested with:

```
chat_message_limit_per_10sec = 1
chat_message_limit_trigger_kick = 2
```

And works as expected. Only one chat log is shown, and I was kicked after 2 messages.

**Comment by est31** [comment]
Maybe @tchncs 's issue is not the described one but what he described in https://github.com/minetest-mods/irc/issues/33 which is bug #4799? Then this issue should be closed.

I'll assume this and @tchncs if you don't agree with this observation please object.

**Comment by tchncs** [comment]
Hmm sorry... i posted this in a sleepy state and forgot that i have a huge delay problem on two of three servers where i tested this. Something causes too much traffic ingame and i don't know what.
Today i am not throtteled and was able to test this again and with success.
I am so sorry for wasting your time here.
