### ISSUE TITLE
Join message is shown in singleplayer

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#4804]
We've had two PRs for this already but it remains an issue. It's a **regression** from the last release and IMO will only confuse players.
It doesn't matter if this is done for "the sake of consistency" or because "technically SP is a server too"; does anyone even care about the experience players have?

see #4526 or #4474 for implementations

**Comment by DS-Minetest** [comment]
i think normal players ignore such texts
_other games have much more confusing texts_

**Comment by paramat** [comment]
This join message already appears in the terminal, singleplayers are used to it, having it appear in chat is no problem and won't confuse.

**Comment by Wuzzy2** [comment]
Please remove it, I think it doesn't belong in singleplayer. It is unneccessary noise.

**Comment by paramat** [comment]
It's difficult to have an opinion on this, however i have noticed this now popping up and cluttering the chat so i really don't mind it being removed. If no-one else +1s i will.

**Comment by rubenwardy** [comment]
:+1: I've changed my mind and now agree with this - singleplayer is not really a server as no one else can join

**Comment by paramat** [comment]
sfan5 rubenwardy perhaps you could review / approve #4474

**Comment by DS-Minetest** [comment]
why dont write another message on singleplayer server to avoid confusing?
something like: `You joined one of your singleplayer worlds!` and dont use the word `server`

or make a setting to show the message which is normally disabled?

**Comment by Zeno-** [comment]
:+1:
