### ISSUE TITLE
Plantlike meshes have dark textures

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#4809]
It seems that the plantlike drawtype is much brighter than a normal block or a mesh. This already caused some confusion here. https://github.com/pithydon/flowerpots/issues/1

![screenshot_20161125_100726](https://cloud.githubusercontent.com/assets/6941454/20619882/10c3d780-b2f7-11e6-89a5-4ac0e55adcfc.png)

**Comment by paramat** [comment]
The sides of cubic nodes are darker on purpose, so compare brightness with top textures, it does look brighter than even nodeboxes. How's the comparison when smooth lighting is off?

**Comment by RHRhino** [comment]
Oh I see now what you mean, the brightness of plantlike matches with the block top textures. 
I'm afraid that most people also use smooth lighning, which creates even more difference between block front and plantlike.

![screenshot_20161126_104108](https://cloud.githubusercontent.com/assets/6941454/20639488/e2fad5c8-b3c4-11e6-98e1-555ee048abd0.png)

![screenshot_20161126_104809](https://cloud.githubusercontent.com/assets/6941454/20639514/d9c862da-b3c5-11e6-8f4b-e690a85ee1f7.png)

**Comment by paramat** [comment]
Yeah, because the plant pot is a model it has darker shading similar to cubic nodes.
The darkening effect of smooth lighting cannot be considered a bug.
So is there no issue here then?
I think plantlike should continue to be at the 'node top brightness' otherwise they will become dark too.

**Comment by pithydon** [comment]
Is there any way I could make the plant part of the mesh match plantlike?

**Comment by RHRhino** [comment]
@paramat 
I just added the smooth lighting to make the plants a little bit better visible in the screenshots. No I don't see any issue here, because it makes sense that plants are as bright as the top side of nodes, although it looks weird from the side. TBH both would work IMO. 😄 

During playing around with meshes and plants I recognized that meshes (the plant part of the model) change the brightness in an unexpected pattern. If you rotate them clockwise from 0 to 360 degrees they have of one brightness from 300 to 60° and 120 to 240° and another brightness from 60 to 120° and 240 to 300°. 
Do you know why this is asymmetric (2 times 60° and 2 time 120°, instead of 4 times 90°)?

> Is there any way I could make the plant part of the mesh match plantlike?

@pithydon No it is currently impossible to change the model like that. The plant planes in the mesh model can only get the brightness values of the walls (z and x in minetest) if you rotate it around the y-axis (in minetest). 

The only solution is that you overwrite all plants from minetest_game to mesh models which have the same brightness as the flowers in your pot (flower mesh model is on the left side)

![screenshot_20161126_220852](https://cloud.githubusercontent.com/assets/6941454/20643892/f97ad3f6-b424-11e6-8fa9-8d91972a4faf.png)

**Comment by paramat** [comment]
> Do you know why this is asymmetric (2 times 60° and 2 time 120°, instead of 4 times 90°)?

Maybe so that a plantlike mesh with 2 diagonal sections has equal brightness for both sections, while the aligned cuboids have differing face shading?

**Comment by RHRhino** [comment]
> Maybe so that a plantlike mesh with 2 diagonal sections has equal brightness for both sections, while the aligned cuboids have differing face shading?

If you rotate a cube mesh the same way its side faces change the brightness the same way as single diagonal mesh faces do. e.g. rotating them around 45° changes all 4 sides to the darker brightness.

![screenshot_20161126_115205](https://cloud.githubusercontent.com/assets/6941454/20651222/691e9730-b4e1-11e6-96c5-5b7f21a6329b.png)

> Perhaps then we could rotate these 4 regions by 90 degrees to make diagonal mesh faces slightly brighter and equal to the brighter cuboid sides? Seems a better choice than matching the darkest cuboid sides, since plantlike meshes will usually be intended to be similar brightness to plantlike drawtype (as here).

Yes that sounds like a good idea, although I still wonder where this asymmety comes from, because if you had the borders around 45° (with equal 90° segments) you could flip between both brightness values just by rotating them by one degree. (and you wouldn't be able to see a difference between 45° and 46°)

**Comment by paramat** [comment]
No, with 4 90deg segments, 2 faces would be dark and 2 faces light, with almost any rotation.

**Comment by RHRhino** [comment]
> No, with 4 90deg segments, 2 faces would be dark and 2 faces light, with almost any rotation.

of a cube?

**Comment by paramat** [comment]
No i mean the 4 faces, or rather, normals, of a plantlike mesh.

**Comment by RHRhino** [comment]
Oh okay I see what you mean. Yes you need a little bit of a offset to avoid that.

**Comment by paramat** [comment]
Now i have to find the code for this.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/src/mesh.cpp#L175
```
			if (vertex->Normal.Y < -0.5) {
				applyFacesShading (vc, 0.447213);
			} else if (vertex->Normal.Z > 0.5) {
				applyFacesShading (vc, 0.670820);
			} else if (vertex->Normal.Z < -0.5) {
				applyFacesShading (vc, 0.670820);
			} else if (vertex->Normal.X > 0.5) {
				applyFacesShading (vc, 0.836660);
			} else if (vertex->Normal.X < -0.5) {
				applyFacesShading (vc, 0.836660);
			}
```
Swapping the order of Z and X lines may work, you can see the Z lines are darker and have priority.

**Comment by paramat** [comment]
Remind me after release and we can try this.

**Comment by pithydon** [comment]
Now it is after release.

**Comment by paramat** [comment]
![screenshot_20161224_051945](https://cloud.githubusercontent.com/assets/3686677/21465370/c76e46d4-c998-11e6-8cfe-dfd6fd499c35.png)

Just noticed this, possbly related, falling node entities have face shading darker on NS faces, instead of darker on EW faces as nodes have. The code above may be the one shading this, which explains why that code seems to make NS faces darker.
Avoidinf that discolouration wuld be good too.

**Comment by paramat** [comment]
Please test your mesh with #4953

**Comment by paramat** [comment]
#4953 fixes falling node shading but does not make your flowerpot meshes brighter, i must be workiing on different code.

**Comment by paramat** [comment]
Found this in mapblock mesh https://github.com/minetest/minetest/blob/master/src/mapblock_mesh.cpp#L1169
This may be what shades meshnodes and your models.

**Comment by paramat** [comment]
#4961 may fix your issue.

**Comment by paramat** [comment]
#4961 fixes this, see screenshots.

**Comment by RHRhino** [comment]
@paramat It looks good from the screenshots! 😄

**Comment by paramat** [comment]
@RHRhino 
#5172 is merged and we also have smooth lighting for plantlike, can you recheck this issue? Will close in 1 month.

**Comment by paramat** [comment]
Mesh shading has been completely reworked so i can't now alter face brightness, closing.
