### ISSUE TITLE
find_node_near issue

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4819]
When using minetest.find_node_near(pos, 5, {"default:mese"}) it will of course search a radius around pos for a mese block, but... why doesn't it search the actual 'pos' position as well ???

If I use a tool to find mese and click on an actual mese block then it will return nothing, whereas if I click the node beside it then it returns the mese block position without a problem ?!?! this is strange behaviour for that command.

I ask that POS be checked as well as it's radius.

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_env.cpp#L612
should be 
```C++
for (int d=0; d<=radius; d++) {
```
Will make a PR tomorrow if it hasn't already been fixed then.

**Comment by tenplus1** [comment]
Sweet, thanks dude :)

**Comment by sofar** [comment]
This just makes using the function more complex:

Before situation:

Scenario I: search with pos included

1. check `pos` for node.name
2. scan around `pos` with find_node_near

Scenario II: search without pos:

1. scan around `pos` with find_node_near

After situation:

Scenario I: search with pos included

1. scan around `pos` with find_node_near
 
Scenario II: search without pos:

1. scan around `pos` with find_node_near
2. parse entire array to find result for `pos` to remove it
3. recount array to find total results or handle results.

**Comment by sofar** [comment]
@SmallJoker I wouldn't patch this. Testing `minetest.get_node(pos)` manually once seems trivial enough.

It also would be an API breakage.

**Comment by paramat** [comment]
:-1: 'find node near' means not including the centre node. The API searches outwards in increasing radius shells and returns the first requested node found. With the centre node included it will just return the centre node if that is a requested nde. Modders will be using this to find the nearest node X to centre node X so it will then be broken.

**Comment by DS-Minetest** [comment]
well, the centre node is near, too. it only excludes the point which is exactly on the pos, here point A:
![bildschirmfoto vom 2016-12-01 18-50-30](https://cloud.githubusercontent.com/assets/7613443/20805542/604a005e-b7f7-11e6-8a6c-4a8ab1f35438.png)
_(if minetest would be 2D)_
but the most part of the centre node is inside the circle
the node with the middlepoint F is detected by `find node near`, but much less of the node is in the circle, the centre node is inside with its dull volume - an infinite small point (=> which got no volume)
the node isnt only made of the middlepoint
=> you could think, `find node near` includes the centre node
maybe you should just add in lua api (if it isnt already there, i didnt look), that `find node near` does not include the node on the position

**Comment by paramat** [comment]
Those are irrelevant arguments, it is being used to not include the centre, and is used to find the nearest identical node.
Any alternative desired use needs a new API.

**Comment by NathanSalapat** [comment]
@tenplus1 
To find the center node can't you just use minetest.get_node(pos) in addition to the find_node_near code?

**Comment by sorcerykid** [comment]
> Those are irrelevant arguments, it is being used to not include the centre, and is used to find the nearest identical node.

That doesn't make any sense paramat. If the entire purpose of minetest.find_node_near( ) is to find the nearest **identical** node then why even have a second parameter to specify the node to find?

**Comment by paramat** [comment]
I see, we would need a new API then 'find_node_near_full' or something.

Sorry i mean 'it is often being used to find the nearest identical node' in which case the suggested change would break many mods.

**Comment by sorcerykid** [comment]
Good point. Perhaps if no second parameter is specified then it wouldn't search the position itself, but instead would use the node at that position to search for surrounding identical nodes? That might still break existing code. Your thoughts?

**Comment by paramat** [comment]
That makes assumptions that would still break stuff.
Perhaps someone could open a new issue requesting a new API function?
