### ISSUE TITLE
Android Studio and Minetest

### ISSUE THREAD

**Issue by Azzeccagarbugli** [minetest/minetest#4820]
When I compile the app in Android Studio, it crashes when I run it in the emulator.
Where's the error? I'm using this repository and I'm under Windows . 
Thanks in advance.

**Comment by est31** [comment]
@Azzeccagarbugli can you paste the logcat output somewhere and link it here?

**Comment by nerzhul** [comment]
Minetest app is not designed for android studio

**Comment by rubenwardy** [comment]
> Minetest app is not designed for android studio

Citation neeeded

**Comment by est31** [comment]
IDK, its no general android issue, it works for me when building with make...

Probably android studio doesn't use make but attempts to use gradle, and then the app crashes at startup when it can't find the native stuff. If this is true, @nerzhul is right.

Either way, its not really useful to be able to compile minetest with android studio, as minetest is mostly native code...

**Comment by nerzhul** [comment]
@rubenwardy no citation needed. Android studio handle gradle builds using Java. Minetest is not a pure java app and doesn't use gradle except for packaging native binaries with JNI classes to call app from android.

**Comment by Azzeccagarbugli** [comment]
So, how could I compile and run Minetest without using Android Studio?
I mean, how have you done it? Thanks.

**Comment by nerzhul** [comment]
Android compilation is only available on UNIX

**Comment by est31** [comment]
@Azzeccagarbugli  http://dev.minetest.net/Android

Yes, Android compilation is only available on UNIX, and I think it even requires GNU coreutils, so mac/bsd might not be supported either.

**Comment by rubenwardy** [comment]
Thanks for the info

**Comment by Azzeccagarbugli** [comment]
@est31 Thanks a lot.

**Comment by est31** [comment]
I think this is resolved now.
