### ISSUE TITLE
player:hud_replace_builtin does not exist

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4832]
`lua_api.txt` mentions a player method `hud_replace_builtin` but it does not seem to exist. When I try to call it, I get an error: “attempt to call method 'hud_replace_builtin' (a nil value)”.

Tested in: 105676b952484affdb97164eceaf4cb903955373

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/builtin/game/statbars.lua#L126
