### ISSUE TITLE
No way for mods to determine formspec support

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4834]
For modders, there is currently no way to figure out the level of formspec support. Or at least it is not documented.

For instance, I can not figure out whether a particular formspec element is available at runtime which makes it impossible to do compability checks.

If Minetest would provide some way to learn about the level of formspec support (e.g. `colorize` works), I could introduce compability code.

**Comment by kaeza** [comment]
Ditto for other things that are client-side (drawtypes, and texture transforms/expressions/whatever come to mind).

**Comment by SmallJoker** [comment]
`formspec_version` added.
