### ISSUE TITLE
Fog considerations

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4836]
I think as of now, some far parts of scenes are totally covered by fog (invisible to player) yet rendered (at least with shaders enabled).  Another use case was when I played on MP server, there was quite a big mountain with shore, with fog disabled I had impression that it was hidden waaay too much.
I'm thinking maybe we need to move it farther from player a bit (right now it is a bit aggressive)?

Here is my examples:
https://imgur.com/a/8eH9N
https://imgur.com/a/AKbkr

Notice how some parts of trees are completely hidden by fog, yet rendered, naturally my guess is to weaken the fog to unhide slightly those guys,

@lhofhansl - what do you think?

**Comment by Wayward1** [comment]
I was just about to open a similar issue. I feel like the fog starts too soon, taking up too much of the view range, especially at lower ones. For example, with the default view range of 25, about half is taken up by fog.

**Comment by lhofhansl** [comment]
The fog distance has not changed, though. I just checked and it is just so the edge of what is rendered is not seen, as it should be.

**Comment by lhofhansl** [comment]
I.e. enable full range 'R', fly forward a bit until you see the edges loaded with new blocks. Stop and disable full range, you'll see that it exactly hides the corners, but not more... Unless there are platform dependent differences this is correct.

**Comment by lhofhansl** [comment]
@Fixer-007 How did you disable fog? With F3 or with R?

**Comment by lhofhansl** [comment]
Does exactly the same with shaders and without for me (in terms of fog range).

Now there is (and has been, not changed recently) this `runData->fog_range = 0.9 * draw_control->wanted_range * BS;` is game.cpp. So we reduce the range by 10%, presumably to be save here. I think we could remove that, but I'd need to try.

I also want to be clear: Is there a range difference between 0.4.14 and current git HEAD?

**Comment by lhofhansl** [comment]
Nope when I do that, it is possible to see the edges sometimes.
Let's also be clear, that minetest load in map blocks (16 blocks). When the view range is 25 or less, then obviously depending on where you look exactly a large percentage of the loaded map might be hidden, but that's not wrong.

So I really don't think there's anything to change here.

**Comment by Fixer-007** [comment]
disabled fog with F3

**Comment by Wayward1** [comment]
@lhofhansl, sorry, I should have clarified. This is something I've been noticing even before your changes. I feel like the depth is too much, like you mentioned in commit 2 of #4652.

**Comment by lhofhansl** [comment]
@Wayward1 Oh I see. Yeah, I have a slight preference as well to have fog only affect the areas further away.
@paramat and others thought it better to leave it as is. It's a matter of taste.

It's not hard to make this configurable. Could be a simple value between 0 and 1. It would be range that the fog would cover. 0.6 would be the default (that's what it is now), smaller values have the fog start further away. That you could set this to 0.8 or 0.9.

**Comment by Wayward1** [comment]
I would love to have it configurable

**Comment by lhofhansl** [comment]
I can send a PR, but I'd like to have some consensus first :)

**Comment by Fixer-007** [comment]
I would like it configurable!

**Comment by paramat** [comment]
I'm not keen on having that configurable, as it just looks so wrong at most alternative values.

**Comment by paramat** [comment]
> Nope when I do that (remove the 0.9 factor), it is possible to see the edges sometimes.

This could be tuned upwards a little though, it's not a problem if mapblocks disappear when still very slightly visible, it also optimises performance.

**Comment by lhofhansl** [comment]
Personally I like at 80%.

As for the 0.9 factor, can try 0.95, too. It actually bothers me visually a lot of I can see the "edge of the world" beyond the fog. Lag while moving is fine - and unavoidable, but when standing still no edges should be visible.

It's already pretty optimal (IMHO), hiding things just before the edge.

**Comment by lhofhansl** [comment]
Can also autotune if the view range is really small.

**Comment by lhofhansl** [comment]
With 0.95, I was not able to produce any visible artifacts, so could tune up to that.

**Comment by lhofhansl** [comment]
So we're talking about two things (just to be clear):
1. Increasing the "fix factor" in game.cpp from 0.9 to 0.95.
2. Perhaps making the fog range configurable or autotuned. At small view ranges (like Android) that might be important.

**Comment by paramat** [comment]
Yeah 0.95 is good then.

**Comment by lhofhansl** [comment]
I'll do a PR (or you just wanna change it)

**Comment by paramat** [comment]
Go ahead, i'm super-busy.

**Comment by paramat** [comment]
Maybe fog start point could be configurable then, i'm not strongly opposed.

**Comment by lhofhansl** [comment]
Will do a PR for both later in the evening.

**Comment by lhofhansl** [comment]
After testing some more I think I like 0.9 as the "fix factor" better. 0.95, is very close and the view range is hardly any better.
I also have a PR with different fog start, but for small view-ranges it does not improve things either.

I think we just have to accept that for small view-range size of a map block (16 blocks) becomes significant, and hence it seems like we're wasting resources.

I'll post the PR and folks can play with it maybe.

**Comment by lhofhansl** [comment]
Default (40%):
![screenshot_20161203_213615](https://cloud.githubusercontent.com/assets/446130/20864323/14223dee-b9a1-11e6-803e-ff52735eb54b.png)

60%
![screenshot_20161203_213648](https://cloud.githubusercontent.com/assets/446130/20864326/1425e1ba-b9a1-11e6-9230-387a7ad4869d.png)

80%:
![screenshot_20161203_213718](https://cloud.githubusercontent.com/assets/446130/20864324/1425394a-b9a1-11e6-86fd-b05e1aede1b2.png)

90:
![screenshot_20161203_213907](https://cloud.githubusercontent.com/assets/446130/20864325/14259d72-b9a1-11e6-9414-811d0b350faf.png)

You see that while close things get sharper the visible range does *not* increase.
This is also with the fixer set to 0.95 (which I don't think is good)

**Comment by lhofhansl** [comment]
And for good measure fog start = 0%:
![screenshot_20161203_214956](https://cloud.githubusercontent.com/assets/446130/20864345/77fbdcc0-b9a2-11e6-99f6-f2e9143b49e7.png)

**Comment by lhofhansl** [comment]
Another reason why setting the fixer to 0.95 might not be a good idea is in part due to #4811, since this will optimize the blocks sent for the view-range, so it is no longer possible to have the server oversend blocks. 0.9 nicely handles that, with 0.95 the lagging becomes more important.

**Comment by paramat** [comment]
Ok no problem, 0.9 can remain.
Your screenshots: 60% looks good to me, 80% loses sense of depth and 40% is too hazy.

**Comment by lhofhansl** [comment]
40% is the current default. Should we change it to 60%?

**Comment by paramat** [comment]
Eh? i thought 0.6 was the default?

**Comment by lhofhansl** [comment]
It was fog start everywhere (both in game.cpp for the irrlicht fog, and in the shaders), so I took that, so fog start in % is where the fog starts. 40% means the range in 60%.
Fog start is also easier to explain... That's where the fog starts.
With fog range you'd have explain it's the range covered by the fog from the furthest distance (or something like that).

As you see the visual it's pretty subjective. :)

**Comment by paramat** [comment]
Ok i got confused, fog start is at 40%.

**Comment by paramat** [comment]
#4842 merged.
