### ISSUE TITLE
Errors with minetest.get_dir_list and with io.popen

### ISSUE THREAD

**Issue by ErrorNull0** [minetest/minetest#4837]
Hello! I've been using sfan5's excellent 64-bit builds from here https://forum.minetest.net/viewtopic.php?f=42&t=1523 . However since the latest build release minetest-0.4.14-e403115 on 11/12/2016 and  minetest-0.4.14-785a9a6 on 11/26/2016 I am getting a C++ exception error when calling minetest.get_dir_list() function and getting NIL value error when calling io.popen. 

This seems regardless of the path parameters and I've tried on Windows 7, 8.1 and 10. I've also tried the 32bit versions of the two latest builds above - and get the same problem. i've also turned off windows firewall. 

I use the below test mod w/out any other additions or changes to the downloaded builds:

```
minetest.register_chatcommand("test", {
   params = "<name>",
   description = "test",
   privs = {},   
   func = function(name)
      local path = "c:/games/minetest"
      print("**** path: "..path)
      local returnVal = minetest.get_dir_list(path)
      print("**** Success!")
   end,
})
```

Minetest completes the first 'print' statement to display contents of 'path'. But, the game errors before ever hitting the 2nd print 'success' statement. It doesn't matter what I assign to 'path'. Any ideas on this? Thank you for an awesome game. All my freetime is spent on modding MT!

**Comment by SmallJoker** [comment]
Due to the recently enabled mod security it is no longer possible for regular mods to damage the system outside their own mod or the world directory. In order to disable this for a specific mod, add the following line to your minetest.conf:
`secure.trusted_mods = mymodname,mysecondmod,anothermod`

If you want to use the `io` functions for these insecure locations, you may want to do it like the irc mod: https://github.com/minetest-mods/irc/blob/master/init.lua#L7-L14

**Comment by ErrorNull0** [comment]
ah ok. I remember reading about the mod security. i will use the 'secure.trusted_mods' line in my mod for now.. thank you! When I fine-tune my mod in the future, i do not intend to rely on functions like get_dir_list to interact with the host file system. Also, i only attempted the io.popen statement as an alternative for my get_dir_list predicament and will not be using it. thanks again.

**Comment by ErrorNull0** [comment]
Hmm.. I added the 'secure.trusted_mods' line in my minetest.conf and still seeing the same error when i run my 'test' command in-game. I'm using the latest build from sfan **minetest-0.4.14-785a9a6**

```
2016-12-03 17:08:13: ACTION[Server]: ErrorNull [127.0.0.1] joins game.
2016-12-03 17:08:13: ACTION[Server]: ErrorNull joins game. List of players: ErrorNull
**** path: c:/games/minetest
2016-12-03 17:08:20: ERROR[Main]: ServerError: Lua: Runtime error from mod 'test' in callback on_chat_message(): C++ exception
2016-12-03 17:08:20: ACTION[Server]: ErrorNull leaves game. List of players:
Loaded texture: C:/games/minetest/textures/base/pack/menu_header.png
```

Just to be sure, I added   **secure.trusted_mods = test**    inside the minetest.conf file from both locations..
C:\games\minetest
C:\games\minetest\games\minetest_game

My mod is simply called 'test' with a single init.lua file with the chat command code I mentioned on the prior post. Is there anything else I am missing? Thanks!

**Comment by ErrorNull0** [comment]
I got it figured out, so it's all okay now. as i mentioned before i will intend to redo my mod to not require the use of these 'unsafe' functions. Thanks again.
