### ISSUE TITLE
Allow access to client settings on server and server settings on client

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4840]
There have been various discussions around this.

I think if we want it completely general, we'd keep clientSettings on the server (alongside gSettings) and serverSettings on the client (again, alongside gSettings). I wouldn't optimize much here and just keep them as global settings, where optimizations are needed it can be cached.

Can we just send all settings? Do we need to whitelist them, or blacklist some?
How often do we sync (maybe send initial values and and on the client followup with changes via callbacks)

@est31 FYI, since you had an opinion :)

**Comment by est31** [comment]
There should be a whitelist. Maybe it makes sense to sync some settings, like the fov info, but most settings don't need to be on the server or on the client.

**Comment by rubenwardy** [comment]
It would be better to have this as a unified flags/settings API where the server can send things like zoom FOV and the client can send things like their FOV. It shouldn't necessarily read directly from settings
