### ISSUE TITLE
Singlenode mapgen type is not on the main menu

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#4841]
To fix this, go into `minetest/builtin/mainmenu/dlg_create_world.lua` and add this:
```
mglist = mglist .. "singlenode,"
```
before this:
```
mglist = mglist:sub(1, -2)
```
so your code looks like this:
```
...
for k,v in pairs(mapgens) do
	if current_mg == v then
		selindex = i
	end
	i = i + 1
	mglist = mglist .. v .. ","
end
mglist = mglist .. "singlenode,"
mglist = mglist:sub(1, -2)
...
```

**Comment by SmallJoker** [comment]
1) This is not a proper solution to fix this issue
2) #3851 and #3844

**Comment by bigfoot547** [comment]
Thanks for the quick response @SmallJoker.
I have yet to find an issue thread that has a snippet of code showing how to temporarily "*fix*" the problem without recompiling the game.

**Comment by paramat** [comment]
That gist is actually the official correct way to select singlenode.

**Comment by paramat** [comment]
We've been through this twice before and both times decided it's best hidden, so closing.
