### ISSUE TITLE
Undefined and inconsistent chat command parameter description syntax

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4843]
The parameter description of most chat commands (`param` field) seems to follow a rough rule, but when you look closely it is a bit inconsistent and the syntax very much looks like an ad-hoc syntax.

After going through the builtin commands, it seems that both “/” and “|” are used for alternations, and that “[text]” is both used for signifying a parameter `text`, which is optional, or the literal text “text”. This is bad as this makes the syntax ambigious. What may be worse is that other modders could come up with an even worse ad-hoc syntax, leading to inconsistency across mods.

IMO this inconsistency is unacceptable. IMO the following things need to happen:

* Formally define the syntax of the command parameter description (and try to keep it as simple and lightweight as possible)
* Make all builtin commands obey this syntax

Here is my proposed addition to `lua_api.txt`, mostly based on the existing builtin commands:

---

#### Parameter syntax guidelines

Please follow the following syntax rules for the parameter description:

* `<param>`: Placeholder for parameter `param`
* `[text]`: “text” can be omitted
* `text1 | text2 | text3`: Alternation: One of “text1”, “text2” or “text3” (scope is one word)
* `(word1 word2) | (word3 word4)` Use round brackets to group multiple words
  together for the alternation
* All other text is literal

Other guidelines and hints:

* Use `[<param>]` to signify an optional parameter `param`
* A “word” is defined as any string without whitespaces
* Program your command in a way so that its parameter syntax is simple
* Use the simplest possible command description which is still complete
* Avoid special characters in your parameter syntax

Special characters:

    <>[]()

---

If you give green light for this, I am going to write a PR with updated `lua_api.txt` and chat commands.
Please give your comments about my proposed semi-formal syntax. If you have suggestions to simplify it even further without loss of information, that would be greatly appreciated! :-)

**Comment by dsohler** [comment]
It's a pity that there seems to be no proper API to register chat commands with that automatically provides the documentation.

Until there is one, this idea here seems a good approach to standardize chat commands a little bit.

+1 from me.

**Comment by rubenwardy** [comment]
>  no proper API to register chat commands with that automatically provides the documentation

https://forum.minetest.net/viewtopic.php?t=14899

**Comment by dsohler** [comment]
> https://forum.minetest.net/viewtopic.php?t=14899 does iirc

Yes. It's another workaround provided by a 3rd party mod creator compensating for the lack of a feature in the official API.

If I think of a proper API to register chat commands I think of something like this:

~~~~
local foo = minetest.register_chatcommand({
    name = 'foo',
    description = 'A command doing foo'
})

foo.add_parameter({
    name = 'doit',
    description = 'Doing it',
    parameters = {
        { name = 'first', expected = 'string', description = 'the first parameter' optional = false },
        { name = 'second', expected = 'integer', optional = true }
    },
    function = function ()
        -- doing it. It the function has access to the parameters
    end
})

foo.add_parameter({
    name = 'reset',
    description = 'Resetting it',
    permissions = { 'permission_one', 'permission_two' },
    function = function ()
        -- running the reset function if the caller has the permissions listed
    end
})

local parameterless = minetest.register_chatcommand({
    name = 'noparameters',
    description = 'A command having no parameters',
    permissions = { 'permission_one' },
    function = function ()
        -- simply run this.
    end
})

foo.enable_chatcommand()
parameterless.enable_chatcommand()

~~~~

... resulting in ...

~~~~
/help
    ...
    /foo - A command doing foo
    /noparameters - A command having no parameters
    ...

/help foo
    /foo doit first [second] - Doing it
    /foo reset - Resetting it

/help foo doit
    Parameters:
        string "first": the first parameter, obligatory
        integer "second": undescribed, optional
    Permissions needed:
        None

/help foo reset
    Parameters:
        none
    Permissions needed:
        permission_one
        permission_two

/help 
    /foo doit first [second] - Doing it
    /foo reset - Resetting it

/help noparameters
    Permissions needed:
        permission_one

/foo doit "my string" "a second string"
    Parameter "second" has to be an integer, see "/help foo doit"

/foo reset
    Insufficient permissions
    See "/help foo reset"
~~~~

... but maybe I'm just a little spoiled Python kid :)

**Comment by rubenwardy** [comment]
That is what my mod does. And it's hardly a workaround (that implies there's a bug here), it's a library to make higher level command registration

**Comment by dsohler** [comment]
> And it's hardly a workaround (that implies there's a bug here), it's a library to make higher level command registration

It's a good mod that is necessary to properly define chat commands. Yes. But to me a workaround does not only circumvents bugs but also missing features.

> it's a library to make higher level command registration

... and this should be part of Minetest itself so modders (Minetest is intended as base for modding - it should at least provide an unified interface to the API to register chat commands without modders need to manually extract the given parameters) can easily register chat commands.

**Comment by Wuzzy2** [comment]
Please continue your mod discussion in another issue, thank you very much. :P

**Comment by dsohler** [comment]
It isn't much about a mod. It's about Minetest in general. The chat commands thing lacks more than just the "Undefined and inconsistent chat command parameter description syntax". Adding a description on how it should look like to the unmaintainable and nearly unusable complex `lua_api.txt` is only a workaround for the API not actually being able to properly define chat commands.

And because I silently follow MT development for some time now I assume changing the file would successfully prevent adding a proper chat command syntax to the api because "it is documentet how to set up chat commands".

So yes, the idea of documenting that is good. :+1: from me for that. But a better solution would be adding proper functions to the API to create chat commands. How hard can that be if a third party mod makes it possible?

**Comment by Wuzzy2** [comment]
Umm, wait, what? I never had any problems with setting up chat commands. I agree that some high-level parsing functions would be nice but I think such a feature can wait.
But I also agree that this is probably not the best solution. As writing down the param syntax manually is of course error-prone and redundant.
On the other hand, there are even modders who don't even bother to write a chat command description. Sloppy mods should not be a reason to change the chat command syntax.


If you really need a full-blown fancy parser library for your chat commands, then your chat commands might have a overcomplex syntax anyway.

> I assume changing the file would successfully prevent adding a proper chat command syntax to the api because "it is documentet how to set up chat commands".

This doesn't make sense. Just because the guidelines have been written down doesn't mean they are set in stone. But even if, this is not a reason which would prevent anything. The chat command parser could probably just pick up the existing syntax rules.
The slightly bigger issue here would be maintaining legacy support.

**Comment by dsohler** [comment]
> If you really need a full-blown fancy parser library for your chat commands, then your chat commands might have a overcomplex syntax anyway.

I'd say "maximum flexibility".

With my syntax idea (I hacked together within a few minutes of free time at work) you can add `/foo` as well as `/bar baz bleh 1 2 "yo man!" blubb` without needing to care about proper help display and proper parsing of the parameters. You also don't need to do any escaping, value type checking or permission checking in your chat command's function.

Maybe check my heavily WIP xTend modpack. It's extremely over-engineered but with that I gain maximum flexibility and extensibility (gray-box) for changing all of it's mods or adding new mods. It even propagates all of it's variables and functions to a prefixed global table so other mods could depend on it and re-use or alter it.

>> I assume changing the file would successfully prevent adding a proper chat command syntax to the api because "it is documentet how to set up chat commands".
>
> This doesn't make sense. 

Unfortunately it makes sense. Nothing works better as a long-term solution then implementing a temporary workaround ... :grin: (Source: ~20 years of working in the IT sector.)

> The slightly bigger issue here would be maintaining legacy support.

Raise the major version number and accept incompatibilities with older versions. That is absolutely fine regarding [SemVer](http://semver.org/) (weren't there discussions that SemVer should be used in MT development?). Mods that need older versions of the API either need to implement a compatibility layer (such a thing could be provided by a third party like with the chat commands mod) or upgrade to the newer API.

**Comment by Wuzzy2** [comment]
> I'd say "maximum flexibility".

Fine. But we have to be careful that modders don't interpret this as an invite to write absurdly overcomplex commands, only because they can. On the other hand, if *you* can present a working solution and post a PR, I would appreciate that. :P


>>> I assume changing the file would successfully prevent adding a proper chat command syntax to the api because "it is documentet how to set up chat commands".

>> This doesn't make sense.

> Unfortunately it makes sense. Nothing works better as a long-term solution then implementing a temporary workaround ... :grin: (Source: ~20 years of working in the IT sector.)

No, it doesn't make sense, and your reply to my reply is unrelated. I attacked your claim that just by the mere act of writing down some guidelines, they suddenly becomes impossible to change. “it is documentet how to set up chat commands” sounds like a straw man to me, who would argue like that to oppose the feature you presented? You haven't criticised the concrete syntax guidelines I wrote, and you haven't posted the syntax of your proposed feature.

We have to add proper documentation of the syntax either way. At least for the user side. I am not opposed to adding “real” syntax support, but I don't see a pressing need for it either. I agree, forcing modders to manually write down the param syntax (like we do now) is bad because it is redundant and error-prone, so we have to get away from this at some point.
But as I said, if you have it worked all out already, you probably have code to share. :P

Oh, about SemVer:
First, Minetest does not use SemVer. Maybe this changes in future (and I hope so). Second, using SemVer is no excuse for breaking compability. There must be a more tangible reason to break compability. But in this particular case, I think it's actually no big deal to break it as the impact seems to be low. I just said there might be a need for some legacy support to not break mods, and I see no reason for not providing it, other than being lazy. Third, raising the major version would mean version 1.0.0 which is way too early at this point.

**Comment by dsohler** [comment]
> You haven't criticised the concrete syntax guidelines I wrote

Because there is nothing wrong with that. It’s a good approach to define the standard syntax.

> and you haven't posted the syntax of your proposed feature.

[I did from coder point of view and from user point of view](https://github.com/minetest/minetest/issues/4843#issuecomment-265367370).

> First, Minetest does not use SemVer

I know. I just had in mind that there was a discussion about switching to it.

> SemVer is no excuse for breaking compability.

You don’t. All you do with SemVer is starting a new major branch of the API if it is incompatible to the previous version.

> Third, raising the major version would mean version 1.0.0 which is way too early at this point.

I see the issue here from a user point of view. As long as the version number is an arbitrary string to me it is simply not relevant from a technical point of view. A solution would be separating the modding API version number from the engine version number.

**Comment by paramat** [comment]
@Ezhh did you fix this recently?

**Comment by Ezhh** [comment]
#5985 adjusted chat command params, but I didn't add anything to lua_api.txt.

**Comment by paramat** [comment]
Ok, the suggested addition to lua_api.txt will need basing on the approach of your PR.

**Comment by paramat** [comment]
#6910 merged.
