### ISSUE TITLE
Add DirectX support

### ISSUE THREAD

**Issue by DreepSTear** [minetest/minetest#4846]
Hello. OpenGL performance seems very bad. Please, add DirectX support because It's fastest on Windows. Thank you!

**Comment by rubenwardy** [comment]
Minetest already has directx support. You can use it by adding the following line to minetest.conf:

    video_driver = direct3d9

It was hidden from the user interface as shaders do not work on DirectX

**Comment by DreepSTear** [comment]
I tried thes already. It says: 

> 2016-12-05 20:26:12: ERROR[Main]: Invalid video_driver specified; defaulting to opengl

**Comment by rubenwardy** [comment]
Please paste your minetest.conf

**Comment by DreepSTear** [comment]
anisotropic_filter = false
bilinear_filter = false
creative_mode = true
enable_bumpmapping = true
enable_damage = false
enable_parallax_occlusion = false
enable_waving_leaves = true
enable_waving_plants = true
enable_waving_water = true
fixed_map_seed =
fsaa = 0
generate_normalmaps = false
leaves_style = opaque
mainmenu_last_selected_world = 2
maintab_LAST = settings
menu_last_game = minetest
mg_name = valleys
mip_map = false
name = Eugene
node_highlighting = box
selected_world_path = E:\Games\Minetest\bin\..\worlds\cpu
server_dedicated = false
tone_mapping = true
trilinear_filter = false
server_announce = false
address = x.x.x.x
remote_port = 30000
fast_move = true
free_move = true
video_driver = direct3d9
cinematic = false
enable_shaders = false
enable_3d_clouds = false
enable_particles = true
smooth_lighting = true

**Comment by Fixer-007** [comment]
Use this:
```
#    The rendering back-end for Irrlicht.
#    type: enum values: null, software, burningsvideo, direct3d8, direct3d9, opengl
# video_driver = opengl
```

**Comment by SmallJoker** [comment]
Some builds might not support DirectX. Could you try if you get the same results with [my Win32 build](https://forum.minetest.net/viewtopic.php?p=241470#p241470)? I tested direct3d8 and 9 successfully there.

**Comment by sfan5** [comment]
only the 64-bit version of the official build supports directx btw
