### ISSUE TITLE
Improve wireframe mode performance

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4850]
If you go into wireframe mode, there will be a somewhat noticable FPS drop.
How to reproduce this:

* Make sure Minetest loads a large area of the world
* Go into far view mode and try to get your FPS at 30 or so
* Turn on wireframe mode with F5 and `debug` priv

For me, the FPS drops to 20 after doing the third step.
But when my FPS was at 60, I see no noticable drop when turning on wireframe mode, so this issue probably is not very pressing.

Tested in: 8a7dc838a8c1f8f2a5e9b710a8ee27d4d00715f9

**Comment by Fixer-007** [comment]
Can't reproduce at least in few scenes. This mode is not meant for play and disabled by default in singleplayer/multiplayer.

**Comment by paramat** [comment]
Seems possibly expected because you can see further and see more stuff.
Wireframe mode is probably somewhat hacky and is obviously not optimised for gameplay.
Obviously not an issue as it's a debug mode.

**Comment by paramat** [comment]
We can consider this a request for any possible performance improvement in wireframe mode.
