### ISSUE TITLE
Broken lighting of soil after intricate TNT explosion (squares-like)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4853]
Description: Old lighting bug associated with TNT that happens to this day. 
How it happens: after specially crafted explosion bunch of TNTs fly in different directions wildly, after landing on distant spots, player flies around observing results, on approach TNTs explode and some leave square-like shadowed areas next to explosion. Explosion nearby can reset or mutate this area.
How to reproduce: read bottom part of the issue.

Examples of this bug on newest build (8a7dc83). Before examining screenshot notice place of explosion adjacent to glitched area.:
![2016-12-06 20_28_06-minetest 0 4 14-8a7dc83-8a7dc83-dirty opengl 4 5 13416](https://cloud.githubusercontent.com/assets/16494741/20938542/288e6be0-bbf4-11e6-813b-015c1dc1e934.jpg)
One darkened square after nearby explosion was converted from vertical gradient to diagonal one.
![2016-12-06 20_19_43-minetest 0 4 14-8a7dc83-8a7dc83-dirty opengl 4 5 13416](https://cloud.githubusercontent.com/assets/16494741/20938544/288ef024-bbf4-11e6-90f3-d236af9510d1.jpg)
More examples of this bug on older builds:
![2016-04-30 23_48_13-minetest shadow bug](https://cloud.githubusercontent.com/assets/16494741/20938538/2870a4ac-bbf4-11e6-84ce-c4336e7bfdf2.jpg)
![2016-04-30 23_51_11-minetest](https://cloud.githubusercontent.com/assets/16494741/20938535/286e4482-bbf4-11e6-8489-467843b49d92.jpg)
![2016-05-01 minetest tnt induced bug 3](https://cloud.githubusercontent.com/assets/16494741/20938539/287308d2-bbf4-11e6-9f6d-ad19bc656bbd.jpg)
![2016-04-30 minetest tnt induced bug](https://cloud.githubusercontent.com/assets/16494741/20938541/288aca9e-bbf4-11e6-985c-db0292eaed70.jpg)

How to reproduce:
Make something like this on picture on flat mapgen, fly below upper part and start chaotically lighting that upper part so they drop in batches with some slight delays, also light top of column, resulting explosions below may boost some TNTs away from explosions so they land within 50-100 blocks range.
The trick is to make as much of flying TNTs as possible scattering them over some areas in some way.
![2016-12-06 20_33_31-minetest 0 4 14-8a7dc83-8a7dc83-dirty opengl 4 5 13416](https://cloud.githubusercontent.com/assets/16494741/20938543/288f1f2c-bbf4-11e6-8ef9-a6b0b05f74c2.jpg)

**Comment by paramat** [comment]
Possibly related to L-system trees lighting bug #3421 the distant TNT may be exploding before the blocks or mapchunks above them are loaded / generated. The L-system tree bugs happen when trees are placed beofore the mapchunk above has been generated (and therefore is darkness above).

**Comment by paramat** [comment]
Where the shadow has a gradient, you may find that the darkest edge is aligned with a mapchunk border.

**Comment by Fixer-007** [comment]
Thats what I suspect too.

**Comment by paramat** [comment]
#4967 merged.
