### ISSUE TITLE
Function to broadcast player inventories to make "player:<name>" work

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#4859]
EDIT by SmallJoker (no previous description was given):
The inventory location `player:<name>` only works for the current player. There should be a function to send the inventory when needed.

**Comment by sfan5** [comment]
Sounds like a feature to me

**Comment by bigfoot547** [comment]
How do you mean, @sfan5?

**Comment by SmallJoker** [comment]
@bigfoot547 because inventories of other players aren't sent.
1) No data to distribute when the inventory changes
2) CSM and client modifications can not be used to read the other player's inventories (safety)

Also looks like a feature to me. However, do you wish API functions like `player:send_inventory(dst_player)` and the pendant to undo that?

**Comment by paramat** [comment]
No reply, invalid.

**Comment by bigfoot547** [comment]
@SmallJoker : that'd be cool. The reason I wanted this in the first place is because I wanted to make a mod where you could open someone else's inventory and take or give items to it. (This was inspired by some Minecraft mod thing)

looks like I missed my window of response tho :C

**Comment by paramat** [comment]
You could open a new request issue.

**Comment by sfan5** [comment]
Likely non-trivial as the client is not laid to handle anything other than its own inventory (for player-bound invs)

**Comment by bigfoot547** [comment]
If player:<name> can only be used on the current player, I think it should be removed as there is already a way to do this without knowing the name of the player.

**Comment by paramat** [comment]
> The reason I wanted this in the first place is because I wanted to make a mod where you could open someone else's inventory and take or give items to it

Doesn't seem a justification for the work, the server mod can do this another way.
:-1:

**Comment by zeuner** [comment]
If the current behaviour is to be regarded as non-buggy, it should be properly documented: https://github.com/minetest/minetest/pull/7720
