### ISSUE TITLE
Why Minetest have no any reflections?

### ISSUE THREAD

**Issue by acterhd** [minetest/minetest#4866]
Hello. I looked sources of: Blockscape, Terasology... They have planar or screen space reflections. Why Minetest have no any reflections: No Planar? No Screen Space? No Cubemaps? <del>And... No Ray Tracing?</del> (pardon, spoilers). 

So.... how I can embed my experimental ray tracing?

**Comment by rubenwardy** [comment]
It simply hasn't been worked on yet. RBA managed to get a prototype working (you can see it on his youtube channel) but wanted to work on prerequisites before doing it properly. Unfortunately he's no long with us

Read up on OpenGL and Irrlicht, those are the technologies we use

**Comment by acterhd** [comment]
I only begun work with Minecraft, and instantly confused "why SQL need for Minetest i.e. why need enterprice DB for game?" I tried to load sqlite, but not found SDK.

**Comment by paramat** [comment]
Minetest has always been relatively simple graphically, the creator celeron55 dislikes shaders, although he is not much involved in development anymore. The shaders and effects we do have are the more simple ones.
Personally i find advanced effects like reflections look out of place in a simplified abstract voxel game, the more advanced and photo-realistic the effect the worse it looks in this type of game.
Minetest is made to be lightweight and many users do not have powerful hardware, so the more intensive effects may not be much used.

**Comment by rubenwardy** [comment]
For more information about shaders and visuals, see #3623 #4336 #4335
