### ISSUE TITLE
Teleport back command

### ISSUE THREAD

**Issue by lightonflux** [minetest/minetest#4868]
Add a teleport back command. E.g. `/tp_back` or `/tp last`, `/tp -`.

When admins `/tp` around it is sometimes a bit annoying to get back. 

My feature request/suggestion:

 1. Store position when user runs /tp (before it is executed)
 2. `/tp_back`is just the regular `/tp` with the variable "$last_tp_position

Equivalent to this in `bash`:

 1. `cd /tmp`
 2. `cd -`

**Comment by ExeterDad** [comment]
Interesting. But that seems easy enough to do in a mod.

**Comment by nerzhul** [comment]
Not a minetest issue, please refer into mod or minetest_game
