### ISSUE TITLE
allow water to cross specific node groups

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4869]
Hi, i would love to be able to place reed to the borders of oceans and so on.
Just like in this minecraft (sorry) screenshot:

![](http://img.mod-minecraft.net/Mods/Plant-Mega-Pack-Mod-2.jpg)

But sadly i know no way to let water cross a node. :/ 

![screenshot_20161209_115859](https://cloud.githubusercontent.com/assets/10698140/21046905/31440528-be07-11e6-8fbc-3629ba262f60.png)

**Comment by C1ffisme** [comment]
If you don't want to wait for an update, I've seen entities used to create plants that don't make air bubbles, but entities load up slower, and they'll put strain on the server with too many of them. (Since entities take up more memory than nodes.)

**Comment by paramat** [comment]
tchncs you mean plantlike nodes in water without air bubbles surrounding them?
We very much want this too.

**Comment by tobyplowy** [comment]
@tchncs +1

**Comment by tchncs** [comment]
@C1ffisme yes, i thinked about this but i would definitly prefer a proper way... .
@paramat yes, i mean this. There are mods? Will search in the forum a bit.

Just in case, i'll add another screenshot.

**Comment by tobyplowy** [comment]
@tchncs this is a mod https://forum.minetest.net/viewtopic.php?id=4627

**Comment by tchncs** [comment]
@tobyplowy yes, i have it on my servers - it does not modify the water itself, also it just fakes to be water.
If such a plant is on Y -1, it will make a hole in the water just like the freshly added screenshot above.
Same thing as someone makes a underwater glasstunnel and such a plant touches it.
Not beautiful... .

**Comment by juhdanad** [comment]
There is a possible solution, but it requires a great change in the engine:
there are currently 3 bits used in flowing liquids' `param2`. We could use the rest to indicate which liquid is flowing in plants.
So to make a plant let liquids trough one had to set its `paramtype2` to `flowingliquid`.

Limitations:
- Plants that let water trough can't store further information (mesh options, rotation, being wallmounted) in their `paramtype2`.
- This maximizes the number of liquid kinds:

`maximum number of liquid kinds=256/maximal length the liquids can flow=32`.

Let me know what you think!

**Comment by Ferk** [comment]
@juhdanad there would be no need to use the 3 extra bits of "flowingliquid" for that, though. You already know the node is not a liquid node, because it wouldn't have the "liquid" drawtype, but plantlike (or other) instead.

But yes, you would need to use param2 to be able to store in the map the fact that the node has some liquid level on it.

There's the additional problem of having to know which liquid is the one filling the node. How to know it's water and not river_water the liquid flowing through when the node is a plant node.

**Comment by bigfoot547** [comment]
@tchncs I like the idea

**Comment by raymoo** [comment]
Why not just arbitrarily choose a neighboring liquid node?

**Comment by paramat** [comment]
The plant may be in a single node of water and have no liquid neighbours.

Then there's mod liquids to support, there are an unlimited number of these.
Perhaps these nodes are best done as separate nodes, a node that contains a combination of nodedefs for the liquid and the plantlike inside.
So a plant that grows in and out of water has 2 nodes.

**Comment by orwell96** [comment]
@tchncs: that's not the default minecraft reed, right? or did they change it in a new version?
It would be interesting how MC handles this.

**Comment by tchncs** [comment]
@orwell96, this is a screenshot i found somewhere about the "Plant Mega Pack" plugin as i remember.
(I cannot check if i remember right because very slow network connection.)

**Comment by numberZero** [comment]
MT needs something I would call “Node Entity:” immobile (belonging to some node), reliable (unlike SAO), as lightweight as possible, but fully customizable otherwise (little more than the mesh actually remains). It also should receive all the callbacks its node receives, thus probably facilitating or preventing replacing. This way, it could be used for plants, chests, furnaces, etc. thus making node metadata unnecessary. Well, ideally that should be used for all non-cubic nodes, but I’m not sure if it is possible to make that lightweight enough.

**Comment by orwell96** [comment]
Don't confuse it with 'Tile Entities' which are (or have been) MC's way to store node metadata.
Are SAO's not reliable enough? signs_lib is working with SAO's and i haven't recognized any unreliabilities. By pointing at the entity's selection box you can trigger the right callbacks (punch, rightclick)

**Comment by numberZero** [comment]
Well, probably I just have outdated information, SAOs were unreliable AFAIK. Also they are known to be heavy; I’m speaking about something as lightweight as possible. And the callbacks I mentioned are node’s, hooked by the entity bound to it.

**Comment by orwell96** [comment]
OK, they can be unreliable when they are moving. I think the existing ways to draw and handle nodes are more lightweight than storing node entities. The only minor limitation (and advantage of node entities as you suggest) would be rotating nodes in steps finer than 90°, but this is needed in very few cases.
And if a node entity is bound at a node, do you mean a custom node(like signs) or any existing node such as water?

**Comment by C1ffisme** [comment]
@numberZero Wouldn't it be much simpler to develop a new drawtype that acts like a plantlike node, but gaps filled in with water rather than air?

**Comment by numberZero** [comment]
@C1ffisme and then a new drawtype for river water, for dirty water, etc.? No, that’s not suitable.

What I’m talking about isn’t simple, but it has several advantages. I think I should write a longer description.

**Comment by C1ffisme** [comment]
@numberZero In that case, what about a drawtype with a plantlike node in any liquid specified by the textures applied to the node?

**Comment by numberZero** [comment]
@C1ffisme  Sounds better. But remember, that should be “flowing” liquid; how to determine whether a node can be flooded this way, what to do when the liquid dries out, what’s about adjacent lava and plant-in-water? And, well, most of such problems should be solved directly in the liquid flow code and not in Lua. This is possible but definitely not as simple as just another drawtype.

**Comment by numberZero** [comment]
@orwell96 @C1ffisme something like that:
https://wiki.minetest.net/User:Numzero/NodeEntity
Surely that’s not a short-term goal; that’s just my dreaming of how wonderful it could be...

**Comment by C1ffisme** [comment]
> how to determine whether a node can be flooded this way?

You don't. The plant within a water is an entirely new node, which acts like a liquid, but looks like the liquid has a plantlike node suspended within it. (Before you reply "But C1ff, then we have to define a new node for every liquid the plant is inside of!", the answer to that is: "Yes, but we already have this problem with other nodes, such as ores, so it's not quite so far fetched, and chances are you don't want a river water plant in ocean water or lava.")

As for flooding, this can be done by an ABM using the origional plantlike node, turning it into either a flowing or source block depending on it's surroundings. (Might require a new function, such as `minetest.spawn_source_here()` or otherwise.)

> what to do when the liquid dries out

That would be defined by whatever ABM affects the block. 

> what’s about adjacent lava and plant-in-water?

Again, ABMs.

Of course, another solution would to have a minetest.on_liquid_flow could also work.

**Comment by numberZero** [comment]
@C1ffisme sounds good! Sadly flowing can’t be combined with facedir, so this solution is inappropriate for other nodes, like tubes, fences, etc. But for plants that should be OK.

**Comment by paramat** [comment]
![screenshot_20170117_143855](https://cloud.githubusercontent.com/assets/3686677/22024950/b5b546b6-dcc3-11e6-927c-1dbc82c24dd0.png)

![screenshot_20170117_144334](https://cloud.githubusercontent.com/assets/3686677/22024954/b9d9ef26-dcc3-11e6-84b2-fc79861d7a3a.png)

I'm cheating here, it's a bit hacky, but by using a large 'visual_scale' for the texture it can pass through nearby water nodes. The second screenshot has the junglegrass placed in a hole underground.

So, it would be possible to have a reed node above water level which has a texture that extends down into the water below, not affecting water nodes below. Plantlike texture always starts at the node base and extends upwards so a new plantlike drawtype would be needed where the texture extends in all directions.

I might try coding this for fun.

**Comment by paramat** [comment]
![screenshot_20170117_164752](https://cloud.githubusercontent.com/assets/3686677/22030319/2d8c0c40-dcd5-11e6-80dc-04a7ac7d17a1.png)

A plant with a node above water is possible, this is a new mesh option in plantlike https://github.com/paramat/minetest/commit/032d08aeb2f36dfa9096662d60c9d0c8703e7fc2

**Comment by C1ffisme** [comment]
@numberZero 
> @C1ffisme sounds good! Sadly flowing can’t be combined with facedir, so this solution is inappropriate for other nodes, like tubes, fences, etc. But for plants that can solve the problem.

Yeah, that's the only problem. It does fix plants, though. So that's a plus. (Although, do connected nodeboxes use facedir? If not, then underwater fences and tubes can be done too...)

**Comment by numberZero** [comment]
@C1ffisme 
> do connected nodeboxes use facedir

They do, to reduce amount of used node types. And liquid has more than 10 variants of `param2` so it can’t be combined with 6d facedir.

@paramat Your solution looks nice, although it’s just a hack (of which MC is full AFAIK). But is new drawtype really necessary for that? We have mesh nodes already, these should be suitable.

**Comment by C1ffisme** [comment]
@numberZero Aw, that's a shame.

**Comment by paramat** [comment]
Clever implementation can be seen as a hack, i think this is as excellent way to do reedlike plants.
It needs a new variation of plantlike mesoptions because as explained existing textures only extend upwards when using visual_scale.

**Comment by numberZero** [comment]
@paramat Do you mean that plantlike is faster that mesh node using the same mesh?

**Comment by paramat** [comment]
I suspect so, because it's dedicated code for just 2 textures.

**Comment by paramat** [comment]
Hm this is a bit hacky.

I was thinking about making underwater plants in a hacky way by creating a new node that is a cube (sea bed) plus plantlike textures extending upwards out of it. It would accept two textures, one tile would be the seabed and the other the plantllike textures. When dug Lua code would replce the seabed node with a normal node.

**Comment by numberZero** [comment]
@paramat sounds great! I hope you mean using a mesh node for that to do that before engine change? I’ve looked through the code: the mesh drawtype seems to be the *fastest* (certainly the simplest) on mapblock mesh generation, and should be equal to other nodes with the same mesh on rendering (only solid nodes and leaves seem to be optimized on mesh generation)

**Comment by C1ffisme** [comment]
@paramat That's my original idea, a node that has the properties of water, but appears to have a plant stuck in it, and can be dug by hand.

**Comment by numberZero** [comment]
@C1ffisme as I understood, paramat’s idea is to replace a node *under* water, not the water node itself. That’s easier and requires no engine change, usual mesh node may be used.

**Comment by C1ffisme** [comment]
@numberZero Ah, thanks for the clarification.

**Comment by pithydon** [comment]
The sea modpack uses special water nodes with transparent textures to remove the air bubbles.
The faces of water nodes are not drawn between liquid and normal drawtypes.
If you made it so water faces are shown between liquid drawtype and nodes with "show_water_faces = false" then you could do the same thing without special water nodes, still a bit hacky.

**Comment by tchncs** [comment]
Is there anything new? :)
I would like to release a server soon with swamp/waterplants and it is hard to decide if i should pre-add those plants or not (because i will emerge a big part of the world) :cat2: 
(When i am going to add those plants it looks quite odd near the beaches until this feature is available - i don't want anyone to hurry, it's just a question)

**Comment by paramat** [comment]
I could submit my new plantlike type, which will pass through water if part of the plant is above water, this will also allow placing plantlike on slabs of any thickness. This is waiting on the content_mapblock.cpp refactor though.

**Comment by tobyplowy** [comment]
@paramat that doesn't really fix The Problem (not correct that is)

**Comment by numberZero** [comment]
@tchncs Just use mesh nodes.

**Comment by paramat** [comment]
#3047 related.

**Comment by paramat** [comment]
My future implementation #5381

**Comment by paramat** [comment]
#5748 merged.

**Comment by ixPost** [comment]
Unless it is kelp.
