### ISSUE TITLE
Block loading bug at small view range

### ISSUE THREAD

**Issue by juhdanad** [minetest/minetest#4878]
How to reproduce:

1. go to an undergeround cave
2. log out
3. set view range to 20
4. log in

Underground blocks may not load on login.

**Comment by est31** [comment]
cc @lhofhansl

**Comment by lhofhansl** [comment]
will have a look later

**Comment by lhofhansl** [comment]
@juhdanad 

- Only in caves? Above ground blocks are rendered?
- Does this only happen with latest git, or also with 0.4.14?

**Comment by lhofhansl** [comment]
Looks like there's a problem with the max_block_send_distance is 1. We should force it to a minimum of 2.
Perhaps related to #4765 @Rogier-5 ?

Easiest seems to force minimum of 2 map blocks on top of the change in #4811

**Comment by juhdanad** [comment]
Sometimes I bump into invisible inexistent blocks near to the place I logged in on the surface too. But it is much easier to reproduce underground. I tried with an older version (about 3-4 months old) and the bug appeared then, too.

**Comment by lhofhansl** [comment]
OK... Nothing recent then. At least I know where not to look. :)

What your server's `max_block_send_distance` and `max_block_generate_distance`?

**Comment by juhdanad** [comment]
max_block_send_distance=9
max_block_generate_distance=7

**Comment by Rogier-5** [comment]
Bisected to commit 5dc61988788e44bc87e8c57c0beded97d4efdf05:
Optimize/adjust blocks/ActiveObjects sent at the server based on client settings. (#4811)

Can't reproduce it on earlier versions.

Pushed a possible fix. @juhdanad: Could you verify whether it fixes the problem, or whether your problem is a different one or maybe a dual one ?

**Comment by paramat** [comment]
With view range it's normal for nearby blocks to not load in, however i did quickly find a block that refused to load in despite walkiing against it.

![screenshot_20161211_003431](https://cloud.githubusercontent.com/assets/3686677/21077165/e61230c8-bf39-11e6-8980-8333f0b503c9.png)

**Comment by est31** [comment]
I think this is important enough to warrant the blocker label, and if its not fixed before release we still can revert the commits that caused the regression.

**Comment by paramat** [comment]
I find that often after 20-30s the missing blocks load in.
