### ISSUE TITLE
Rewrite bad/confusing strings (for translators)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4879]
Since we have a feature freeze now, I think it is a good time to clean up a few strings before starting translations:

~“Mapgen v7 terrain persistation noise parameters”
    * Neither the dictionary nor Wikipedia know the word “persistation”. You probably mean “persistance”~
~“Maximum number of players that can connect simultaneously.”
     → “Maximum number of players that can be connected simultaneously.”~
* “Number of emerge threads to use. Make this field blank, or increase this number
to use multiple threads. On multiprocessor systems, this will improve mapgen speed greatly
at the cost of slightly buggy caves.”
   * Rogier says:
       * >  This comment is not entirely correct. Unless there are more than 3 processors, the number of emerge threads will be 1 (# CPUs - 2). Also, LUA map generation speed is not increased when increasing the number of emerge threads, and as much of the emerge thread is serialized, I suspect that increasing the number of emerge threads could actually be a cause of lag.
* “Number of extra blocks that can be loaded by /clearobjects at once.
This is a trade-off between sqlite transaction overhead and
memory consumption (4096=100MB, as a rule of thumb).”
    * Usage of “MB” is ambigious, as there are a few (but powerful) folks who insist on using factor 1000 (rather than factor 1024). I recommend using “MiB” for meaning 2^20 bytes. See also: https://en.wikipedia.org/wiki/Binary_prefix

~“Scale gui by a user specified value.
Use a nearest-neighbor-anti-alias filter to scale the GUI.
This will smooth over some of the rough edges, and blend
pixels when scaling down, at the cost of blurring some
edge pixels when images are scaled by non-integer sizes.”
    Replace “gui” with “GUI”. Replace “Use” with “Uses”.~
~Width of the selectionbox's lines around nodes.
    → “selectionbox's” → “selectionbox'” or (if UTF-8 supported) “selectionbox’” (put apostrophe at end)~

If you find bad strings or typos or whatever, post them all here so we can collect them.

**Comment by paramat** [comment]
The 'MB' thing is a non-issue.

I agree that the emerge threads thing should be clarified to remove the dubious performance claims. 'On generated' calls are not threaded which complicates things.
I'll probably do this myself soon.

**Comment by paramat** [comment]
PR #8066
