### ISSUE TITLE
zoom should be stronger

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#4887]
with `zoom_fov >= 15` you cant zoom a very long distance and zoom doesnt give a big advantage
i suggest making the minimum zoom_fov lower

**Comment by C1ffisme** [comment]
Although I doubt it's possible, I would like to see the game load the chunks where the player is zooming, so that it has an actual purpose rather than just making a small part of the screen a bit larger.

**Comment by lhofhansl** [comment]
With #4811 that's actually doable with fairly little extra server load, since the client's FOV is now sent to the server - which means only that small view cone would have to be retrieved.

**Comment by DS-Minetest** [comment]
Is it so difficult to decide if this will be changed or not? I thought it would be trivial.

**Comment by paramat** [comment]
> i suggest making the minimum zoom_fov lower

Do you mean make the default value lower? Is there a minimum value?

**Comment by paramat** [comment]
Wow i just saw the zoom FOV is limited to a minimum of 15, which is not at all powerful, x10 (7 degrees) should at least be possible.
:+1: 
Now what's the smallest practical zoom FOV?

**Comment by lhofhansl** [comment]
I think what's being suggested is that zoom also retrieves a further blocks from the server.

**Comment by paramat** [comment]
That's possibly a good idea, perhaps we can consider that in a separate PR? It might need to override the 'max send distance', because that is only 160 nodes by default, it should certainly at least force the 'max send distance'.

**Comment by lhofhansl** [comment]
I'm traveling right now... Might take this on when I'm back.

**Comment by paramat** [comment]
#5095 merged.
