### ISSUE TITLE
active_block_range (and other setting) should auto-tune based on server performance

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#4892]
An idea I just had on IRC. We could measure the active block modifier time and adjust the range based on that; right now we're skipping a few rounds in that case, which can be laggy.

I might do a conceptional PR for this as basis for discussion.

**Comment by lhofhansl** [comment]
Is 200ms is good target, or is it already too long?

**Comment by est31** [comment]
This will probably make players sad who stay AFK close to their farms so that they grow. Or it'll make them happy, idk...

**Comment by lhofhansl** [comment]
Old issue, based on old code... Closing.
