### ISSUE TITLE
HUD Text Scale

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#4898]
Adding text to a HUD element is great, even having it's own colour, but we really need the ability to scale the text size and override the default GUI_Scale setting in .conf e.g.
```
local idx = player:hud_add({
	hud_elem_type = "text",
	position = {x = 1, y = 0},
	offset = {x=-100, y = 20},
	scale = {x = 100, y = 100},
	text = "My Text",
	text_size = 2.4,
	number = 0xFF0000 -- Red
})

**Comment by alexdevteam** [comment]
Why can't we just use the `scale` var?

**Comment by tenplus1** [comment]
'scale' is used for images which may be a different size from the text.

**Comment by hunter688** [comment]
yes please: https://github.com/minetest/minetest/issues/3903

**Comment by IvanTurgenev** [comment]
i cant see anything!!!! :(
![screenshot from 2017-04-13 23-11-38](https://cloud.githubusercontent.com/assets/3318444/25032972/90743104-209e-11e7-88c1-b4311b77e485.png)

**Comment by SmallJoker** [comment]
@IvanTurgenev that's not related to this issue. Add (or change, if already existent) the following setting in your minetest.conf file:
`font_size = 50`

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by ClobberXD** [comment]
Related: #6560 and #7620

**Comment by LoneWolfHT** [comment]
I'll take a stab at this later. Here's to hoping Irrlitcht's text api is similar to other API's I've used
