### ISSUE TITLE
Number of tool uses is off by 1..32767

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4900]
I noticed the number of tool uses before they break (specified via `groupcaps` in the tool definition) is off by 1.
You can use the tool one more time than the Lua documentation claims to.

Proof:
* Take wooden shovel (`uses=10`, `maxlevel=1`) from Minetest Game
* Dig dirt (`level=0`) with it until shovel breaks, count how much dirt u got

Expected number: 30
Actual number: 31

According to documentation, use count is calculated like this:

> Determines how many uses the tool has when it is used for digging a node,
> of this group, of the maximum level. For lower leveled nodes, the use count
> is multiplied by `3^leveldiff`.

Shovel digs `crumbly` and has `uses=10` and `maxlevel=1`.
Dirt has `crumbly` and `level=0`

`leveldiff` is thus 1, and the expected use count is `uses * 3^leveldiff` = `10 * 3^1` = `30`.

Minetest Game source code for reference:
Shovel groupcaps:
```
                 groupcaps={
                         crumbly = {times={[1]=3.00, [2]=1.60, [3]=0.60}, uses=10, maxlevel=1},
                 },
```

Dirt definition:
```
 minetest.register_node("default:dirt", {
         description = "Dirt",
         tiles = {"default_dirt.png"},
         groups = {crumbly = 3, soil = 1},
         sounds = default.node_sound_dirt_defaults(),
 })
```

**Comment by nerzhul** [comment]
This is a bug to fix for this release

**Comment by bigfoot547** [comment]
Maybe it has something to do with the fact that wear is stored as 0-65535 and in minecraft (why does that game keep coming up?), wear is stored as uses left until the tool breaks.

**Comment by garywhite207** [comment]
I did similar testing with shovels after @Wuzzy2 posted this issue, and I found:

Diamond shovel digs 820 dirt (which is correct, so I understand), 
Stone axe cuts 61 pine tree nodes (which is bugged)
Wood axe cuts 31 pine tree nodes (which is bugged)
Mese shovel digs 542 dirt (which is even more bugged)

**Comment by paramat** [comment]
Uses being off by 1 or 2 is a minor bug, not worth dev time at the moment, removed from milestone.

**Comment by yyt16384** [comment]
Currently the number of nodes dug is `floor(65535 / floor(65535 / uses)) + 1`, which is `uses + 1` for small values of `uses`.

I think replacing `uses` with `uses - 1` should be good enough.

**Comment by bigfoot547** [comment]
I have had this problem, but, @yyt16384 , that may not be the answer. Only sometimes does this happen, other times it it correct. I do think that you are on the right track though. :+1:

**Comment by Wuzzy2** [comment]
Actually, it turns out the bug is much more serious than previously thought. The number of tool uses is not always off by only 1 or 2. This only happens for small numbers. As the number of uses grows larger, the error grows substantially.

With `minetest.get_dig_params` you can test larger numbers:

```
/lua print(dump(minetest.get_dig_params({cracky=3}, {groupcaps={cracky={times={[3]=0.5}, uses=40000, maxlevel=0}}})))
```

(replace the 40000 with the number of uses you wish to test)

This example returns a wear of 1. Actually, all `uses` numbers between 32768 and 65535 return the same wear, which implies 65536 total uses. So for 40000 uses, the effective number of uses is off by over 20000!
For smaller numbers (in fact, all of them), there's still an error, it's just smaller.
The only number of uses that is *not* broken is 0, which is a special number that stands for unlimited uses.

For other wear numbers, you can calculate the effective number of uses with `65336 / <returned wear>`.

## Analysis
I have analyzed the formula (`src/tool.cpp`), and I noticed the following problems:

First, the off-by-one error comes from the fact that `U16_MAX=65535` is used as the reference value, but the maximum theoretical number of uses is 65536 (adding 1 wear 65536 times; because you can use the tool one more time when you've reached 65535).

But that's not everything. Even if you fix that, the core assumption of the formula is wrong: It basically is just (I paraphrase) `65535 / uses` (or `65536 / uses` if off-by-1 error is fixed). The problem is rounding. We have to round, since `wear` is not a float. But due to rounding, this will create lots of equal wear values for different `uses`, especially higher numbers. And equal wear values result in equal effective number of uses. And the error increases with larger values of `uses`.

I am currently working on a PR for a solution, I already have the maths worked out.

**Comment by Wuzzy2** [comment]
Oh, another thing: `leveldiff` is not the problem here. I my analysis I always assumed `leveldiff` to be 0, so that part disappears in the formula.
