### ISSUE TITLE
Missing and useless descriptions for advanced settings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4903]
This is a list of advanced settings which currently only have an useless description (just repeat the setting name, no explanation) or no description at all (in the main menu):

Useless descriptions:
`enable_vbo`
~tone_mapping~ (EDIT by paramat: Done)
`enable_ipv6`

Missing descriptions:

* `water_wave_height`
* `water_wave_length`
* `water_wave_speed`
~* **All* settings under “Server / singleplayer → Game → Physics”~

This list has been created before the 0.4.15 release process. It should be investigated which sensible descriptions could be added.

**Comment by sofar** [comment]
Since we are in freeze, does it make sense to fix these if this is not accepted for 0.4.15? I assume there will be translations that need updating after this is fixed?

**Comment by paramat** [comment]
mgv6_freq_beach and all noise parameters have an alternative "readable" version set, they're not missing https://github.com/minetest/minetest/blob/master/builtin/settingtypes.txt#L951
Although they are just a repetition of the parameter name and no clearer.

**Comment by dsohler** [comment]
Most of the values lack a proper description.

**Comment by Wuzzy2** [comment]
So basically none of the strings will get updated for 0.4.15?

Translations need updating anyway, especially it seems Weblate strings do not fully represent the current Minetest strings.

**Comment by dsohler** [comment]
> Also, the feature freeze was never loudly declared (no thread in News forum), nor have translators been formally informed yet.

... but du translations count as features? Updating translations should not be affected by a feature freeze.

**Comment by paramat** [comment]
The descriptions in advanced settings could be improved before release, but it's not high priority, out time is best spent elsewhere.

**Comment by paramat** [comment]
Sorry i misunderstood, the notes for noise parameters are indeed missing, and i am obviously the person to do this, will do after release.

**Comment by paramat** [comment]
Completed descriptions for mapgen stuff.

**Comment by pauloue** [comment]
The `modstore_*` settings (and the `main_menu_*` settings after #7929 is merged) no longer exist, so they can be removed from the top post.

**Comment by paramat** [comment]
Thanks, done.

**Comment by paramat** [comment]
Physics settings documented in #8867 
I also improved the 'readable' names for waving water settings, they're somewhat self-explanatory so i don't see much need for descriptions.
Tone mapping is described as 'filmic tone mapping' which seems good enough.

**Comment by Wuzzy2** [comment]
All settings have a description since a while now. Closing.
