### ISSUE TITLE
Feature: Create new world from commandline

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#4908]
For testing purposes, I'd like to be able to run minetestserver out of the box and host a new world. Currently, `minetest --server --worldname "new"` does not create the new world if it does not exist.

**Comment by Fixer-007** [comment]
I'm surprised minetestserver does not have this, that will be very useful for headless servers.

**Comment by stujones11** [comment]
:+1 I've wanted this feature for a long time, mapgen might be useful here but mods can be added easily enough afterwards.

**Comment by serra** [comment]
> Just create a folder with the world name.
> Minetest server creates worlds/worlds you run it when no other world's exist.
> -- rubenwardy

From: https://forum.minetest.net/viewtopic.php?f=3&t=14273

**Comment by LoneWolfHT** [comment]
This isn't already possible?

**Comment by SmallJoker** [comment]
Already possible using `--config` and `--worldname` or `--worldpath`. A new world will be generated automatically.
