### ISSUE TITLE
Pixels flicker on nodes when using Minetest without shaders

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4912]
I often see single pixels on the nodes (or maybe the node borders?). It looks like this:

![Blue pixels bug](https://i.imgur.com/qQVbz20.png)
https://i.imgur.com/qQVbz20.png
**Important**: Watch the image in full size, otherwise the problem may be hard to see.

These pixels appear to have the same color as the sky.

When I look around (i.e. move the mouse) the pixels start to flicker, i.e. there will be pixels on other positions. When I stand still, the pixels stay. The pixels may be easier to see in darkness, shadows or at dark walls. Interesting observation: If you manage to get the camera back to the EXACT position, you will see the exact same pixels again. So it appears your viewing angle matters a lot.

This screenshot has been taken in c67f2b29651eb98aaaf14649560d91ce5963223d. I first have completely reset `minetest.conf` and then disabled shaders in the main menu. I run Minetest on GNU/Linux with the OpenGL backend. (**EDIT**: No idea if shaders are responsible.)

I've seen this bug in 0.4.14 and c67f2b29651eb98aaaf14649560d91ce5963223d, but if I can remember correctly I have observed this bug since the dawn of time (probably). ;-)

**Comment by sfan5** [comment]
This has been here since the beginning of time and you can fix it by enabling some graphics setting I don't remember right now.

**Comment by Wuzzy2** [comment]
Why providing a setting if it causes graphical glitches / is broken?
Or are these pixels technically inevitable in this mode (I hope not)?

Maybe the setting you mean is just broken. Then it's still a bug.

**Comment by Fixer-007** [comment]
Try enabling "mipmap" or "mipmap + aniso". There is also possibility of videocard snow due to GPU problem, but I doubt it.

**Comment by Wuzzy2** [comment]
No, sorry. This doesn't change anything.
Also, this happens with a **100% default `minetest.conf`**.

**Comment by MoNTE48** [comment]
+1 It is very annoying when fast mode!

**Comment by paramat** [comment]
I have always had this, but seems dependent on hardware, as my new computer has much less of this. I'm pretty sure it's tiny gaps on node edges. I think it may be a GPU thing, gaps in the mesh.

**Comment by rubenwardy** [comment]
Does it still appear when you enable anti-aliasing?

**Comment by tobyplowy** [comment]
@Wuzzy2 +1 this is very annoying when you're in dark caves

**Comment by Fixer-007** [comment]
Have not encounter this bug IMO.

**Comment by SmallJoker** [comment]
Can confirm with NVidia GeForce 6600GT (AGP, silent pipe), Windows XP - No shaders turned on

**Comment by Fixer-007** [comment]
Confirm this bug on AMD/ATI HD6870 on Win7sp1, to spot them easier go into cave somewhere near surface (say -15). It is 1px size dots that appear in some way.

**Comment by Wuzzy2** [comment]
@rubenwardy: Yes.

**Comment by Zeno-** [comment]
This has happened ever since I've been involved in Minetest. Perhaps we should investigate it for the next release

**Comment by tobyplowy** [comment]
@Zeno- I agree +1

**Comment by tobyplowy** [comment]
a vidioe that shows it in action NOTE i made my minetest window smaller so it's easier to see the flickering pixels but it also happens on 1920x1080 res also i use farlands in this vid but it also happens in mintestgame
https://youtu.be/zZd3b37iFsc

**Comment by HybridDog** [comment]
It's not caused by floating point inaccuracy, is it?

**Comment by paramat** [comment]
Is it possibly an Irrlicht and hardware issue and therefore nothing we can fix?

**Comment by nerzhul** [comment]
@paramat yeah

**Comment by rubenwardy** [comment]
Irrlicht issues our usually our issues, except GUI and Input.

We also don't know if this is an Irrlicht issue, anyway.

**Comment by numberZero** [comment]
@paramat This is *definitely* a confirmed bug. We can see these gaps all the time:
![screenshot_20190103_184632](https://user-images.githubusercontent.com/7352626/50646902-58b90480-0f88-11e9-980b-f695e3b7f1b4.png)
(there in the fog).
![screenshot_20190103_191535](https://user-images.githubusercontent.com/7352626/50648437-42ad4300-0f8c-11e9-8b98-02c7a0e16b23.png)

That has nothing to do with filtering, mipmapping or whatever. That’s rounding error. It becomes insane when half-precision coordinates are used (that may happen on Android, see https://github.com/minetest/minetest/pull/7514#issuecomment-435685867 and following comments).

The reason we don’t see such gaps in other games is that proper polygon meshes are used there.
Take a look at this picture:
![mesh](https://user-images.githubusercontent.com/7352626/50648159-818ec900-0f8b-11e9-8826-7a2398f2e2a1.png)
Black grid is the “ideal” mesh, green grid is what is drawn. Rounding error is there, but it is the same for both faces sharing an edge, so there is no gap.

On the other hand, MT generates optimized mesh, like on this image:
![mesh2](https://user-images.githubusercontent.com/7352626/50648162-83f12300-0f8b-11e9-9329-e3849e2ee05e.png)
There is no “real” shared edge, so rounding error affects faces differently, causing either overlap or gap. Check the screenshots: the gaps are at strip edges.

So, sharing an edge means using *exactly* the same coordinates at *both* ends. Solid node vertices’ coordinates are always exact (integer), so disabling striping is enough to fix the gaps.

**Comment by paramat** [comment]
Thanks for the explanation, so we know it is not hardware. To be clear, this is due to MT fast-faces code drawing a line of idnetical node faces as long rectangles? So i guess a fix would remove the performance gain from fast-faces.

**Comment by HybridDog** [comment]
Why are the gaps never bigger than one pixel?
Would increasing the float precision instead of disabling fast-faces have less impact on performance?

**Comment by numberZero** [comment]
> increasing the float precision

“Never use this.” — [OpenGL wiki](https://www.khronos.org/opengl/wiki/Vertex_Specification#Component_type). There are many reasons, including bad performance and poor support.

> Why are the gaps never bigger than one pixel?

Because that’s the renderer resolution. Try enabling FSAA, it should hide (almost) the gaps as it increases the rendering resolution effectively, but keeps the display resolution. I think the error is less than 1 pixel for each vertex, and the gaps are way smaller than 1 pixel mathematically; it’s the renderer what has to decide whether to fill a given pixel or not.

Note that on Android, as you could see, the gaps may be *way* wider than a pixel. I suppose it uses half-precision floats internally.

**Comment by HybridDog** [comment]
> Try enabling FSAA

I stopped using FSAA when I noticed gaps at node boxes: #6860

**Comment by numberZero** [comment]
Still open? There are ways to optimize mesh not breaking it, although they are more complicated than the current striping, and probably need more computational power. Something like:
![triangulate1](https://user-images.githubusercontent.com/7352626/82133386-3bd74700-97f4-11ea-9533-59d971edb014.png)
I had a working example somewhere, need to find it...

**Comment by ResuUman** [comment]
I humbly vote to mitigate this problem in caves.
This is daylight passing through. Perhaps tuning daylight dimming would be enough (in caves at least).

**Comment by paramat** [comment]
It is only a problem in caves if 'fly' and 'freemove' are enabled, which is rarely, the sky needs to be bright in this situation so i see no solution in terms of sky brightness.

**Comment by Jipok** [comment]
> It is only a problem in caves if 'fly' and 'freemove' are enabled, which is rarely, the sky needs to be bright in this situation so i see no solution in terms of sky brightness.


I have this problem all the time.  'fly' and 'freemove' are disabled:
![image](https://user-images.githubusercontent.com/25588359/99899778-d7fe7100-2ca3-11eb-88a9-1e57ee8c8350.png)

Sometimes lines several centimeters long appear instead of dots

**Comment by nininik0** [comment]
this happens to me all the time, its annoying when youre in fast or in caves
