### ISSUE TITLE
The night to day transition is not smooth

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#4913]
The night to day transition is not smooth

**Comment by C1ffisme** [comment]
Care to go into more detail?

**Comment by masrourmouad** [comment]
at sunrise the light transition is chunky

**Comment by rubenwardy** [comment]
It is smooth if you enable shaders

**Comment by C1ffisme** [comment]
Do you mean chunky as in the light in each chunk does not update at the same time, or the light changes from one value to another too quickly?

**Comment by paramat** [comment]
Try enabling basic shaders. I doubt there's anything we can do for the shaders-off behaviour.
