### ISSUE TITLE
Allow visual_size for nodes

### ISSUE THREAD

**Issue by tchncs** [minetest/minetest#4918]
Hi, i have another feature request:

I would like to add plants to the game which are actually two nodes tall (cacti plants for example).
The problem is, that i have only (as far as i found out on tests and the api txt) option to scale a complete node with its texture which makes small textures (on width) ugly (imagine a baseball bat cacti on this example).

I would enjoy to define x and y there too. (like it is on entities, isn't it?)

**Comment by RHRhino** [comment]
You can already do two node tall plants perfectly with one texture.
![screenshot_20161217_105256](https://cloud.githubusercontent.com/assets/6941454/21285954/201aa540-c447-11e6-938f-f316ffdf5fe6.png)

You just need a 32x32px texture with each "node" is a 16px texture on that, both positioned 8px away from each side. And visual_scale=1.5 in the node definition. The pixel size is equal to the other 16px textures then.

This texture was used: 
![grass](https://cloud.githubusercontent.com/assets/6941454/21285958/372ec25c-c447-11e6-8020-2911abfcd032.png)

**Comment by tchncs** [comment]
Wooo so my fault was mainly to use a 16x32px texture, tested with success, thank ya!
