### ISSUE TITLE
"Kapplyfihtersformesh" couldnt be loaden while building texture

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#4920]
i had a weird bug (on punching "default:cobble")
![2016-12-17-201716_1280x1024_scrot](https://cloud.githubusercontent.com/assets/7613443/21289249/34058fa6-c498-11e6-8f22-797c67a18a4c.png)
it seems like it wanted to overlay this texture at cracking (multiple(6) times, maybe for each crack(5) and one for beginning or end?)
i couldnt reproduce this bug yet and have no idea what it is

**Comment by C1ffisme** [comment]
> i couldnt reproduce this bug yet and have no idea what it is

Then, where did you get this screenshot and why are you posting an issue about it? Did you take this screenshot or did someone else?

Judging from the strange item on the very right of the hot bar, your game is modded, but since you can't reproduce this again, I don't know what you want us to do, nor what we should have you do.

**Comment by DS-Minetest** [comment]
its mine screenshot, i meant that it only happened once
i was not sure if i should open this issue but **i wanted to see if anyone knows what it is**
yes, it is modded (the tool on the very right of the hotbar is a worldedit wand) but i dont think, a mod could cause something like this
perhaps it would be better to close this again...

**Comment by kahrl** [comment]
You might want to run a memory test (e.g. [memtest86+](http://www.memtest.org/)) on the computer where this happened.

The correct texture modifier (generated by TextureSource::getTextureForMesh()) is "^[applyfiltersformesh", but on your computer it apparently got corrupted to "^Kapplyfihtersformesh". So

* '[' (ASCII 0x5b) got corrupted to 'K' (ASCII 0x4b)
* 'l' (ASCII 0x6c) got corrupted to 'h' (ASCII 0x68)

In both cases, exactly one set bit was returned as unset. This highly suggests a memory error to me.

**Comment by DS-Minetest** [comment]
ill close this issue now, that i know what the reason was
thanks, @kahrl 
im sorry that if i annoyed anybody with this issue
