### ISSUE TITLE
Borderless fullscreen mode (to fix many issues with driver fullscreen)

### ISSUE THREAD

**Issue by mahmutelmas06** [minetest/minetest#4921]
Driver mode fullscreen has many issues. Most modern games use fake fullscreen by creating a borderless window. ~ @rubenwardy

---------------------------

> **original post**
>
> I think it should be an option to chose **borderless windowed** mode as a graphic option additional to fullscreen and windowed. Would be faster to switch between apps while still using fullscreen.

**Comment by Calinou** [comment]
This would help fix the error about fullscreen on Windows, saying "The fullscreen mode is not supported." despite it working just fine.

**Comment by dsohler** [comment]
Window borders are part of the operating system’s window manager and are nothing the applications should care about.

**Comment by rubenwardy** [comment]
The driver's fullscreen mode is not the best way to fullscreen, ironically. It causes less problems to use borderless fullscreen (especially when you have multiple moniters)

**Comment by dsohler** [comment]
> It causes less problems to use borderless fullscreen (especially when you have multiple moniters)

Exactly. And it is still the window manager's job and not the job of the applications.

**Comment by rubenwardy** [comment]
Even if it is the window manager's job, it is **our job to give the user the best possible experience**. Therefore we should allow then to choose the fullscreen mode. Under your logic, we also shouldn't support full screen at all. Please note Windows doesn't support alt+f4

I also don't think it's the window manager's job as most just respect what the app requests - and we request fullscreen mode

**Comment by dsohler** [comment]
> Therefore we should allow then to choose the fullscreen mode.

The application should send the corresponding signal for either switching to fullscreen or to maximize and undecorate but it should be only that.

> Under your logic, we also shouldn't support full screen at all.

To be honest: Yes, that would the correct way. Applications should behave properly regarding the window mode the window manager applies to the application's window.

> Please note Windows doesn't support alt+f11 for fullscreen

And therefore fullscreen mechanisms are implemented over and over again by developers. That's actually Microsofts fault. Almost all WMs except the thing that is used in Windows can be properly controlled via signals.

**Comment by skewty** [comment]
I'm running Gnome 3.34 and `Alt-F11` isn't working for me.  
I verified in `Gnome Settings` - `Keyboard Shortcuts` that `Alt-F11` isn't mapped to something else.
Is Gnome the issue?  I see above some KDE people seem to have it working.

I don't see any mention of `Alt-F11` in the game settings anywhere..  Is it undocumented?

**Comment by soshimee** [comment]
toggle fullscreen mode is missing for me

**Comment by sfan5** [comment]
https://github.com/minetest/irrlicht/compare/393793f...c84d8ac
