### ISSUE TITLE
hide the contents of packages, hide the game, enabled by default

### ISSUE THREAD

**Issue by SpaghettiDeveloper** [minetest/minetest#4924]
Enable default option "hide the contents of packages", "hide the game" tab in the "single player", button "configure". I think it is very useful to make the additional mod easier to select with no errors, and makes everything neater! I think it's a good idea, I always use this option I find very useful. There is no use to see the mods included in Minetest_Game, those who want to select the option to display them, the end user will not make confusion. Thank you all guys.

<img src='https://s23.postimg.org/fk6wpiqpn/Schermata_del_2016_12_18_12_32_08.png' border='0' alt='Schermata del 2016-12-18 12-32-08'/>

**Comment by red-001** [comment]
so #5065 ?
