### ISSUE TITLE
App force close on Android x86

### ISSUE THREAD

**Issue by vichoca9** [minetest/minetest#4932]
I don't know if this is happening with other devices with x86, but in my tablet Minetest doesn't work. Someone knows?

**Comment by ShadowNinja** [comment]
Please provide more details.  What version of Minetest?  What version of Android?  Can you get the relevant logcat logs?

**Comment by vichoca9** [comment]
The latest version of minetest. (0.4.14.14)
From fdroid and google play .
Android version: Kitkat

**Comment by vichoca9** [comment]
Older versions and ports (like Mullticraft ) works very well but the original no.

**Comment by est31** [comment]
tbh, I've never tested x86 compatibility, as I don't have such a device. But if someone wants to contribute support, it would be useful.

**Comment by vichoca9** [comment]
I have a tablet now so i can test new builds if you post some now

**Comment by wilkgr76** [comment]
Also occurs on 0.4.15

**Comment by stujones11** [comment]
The x86 build was reported to be working around the time of this PR https://github.com/minetest/minetest/pull/6796#issuecomment-353805186

Right now there is no official x86 build (to my knowledge) so I'm not sure this issue is even still valid.
