### ISSUE TITLE
Make credits focussed, inclusive and non-arbitrary

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4935]
As someone has commented, these lists of 'active' and 'previous' are awkward and arbitrary.
We have been deciding an amount of contribution that gets someone a mention, i think it should be all commit authors however small the commit.
We have been deciding who is 'active', better to define it specifically as those who have committed during the last release cycle.

So, i would have 2 lists, the first is 'recent contributors', the second is everyone else, anyone who has authored a commit in engine or game. 
Perhaps both lists ordered by number of commits, or maybe to be easier to locate a username, alphabetically by username.
The second list would be large, so don't bother with email addresses, just their Github usernames, it can have multiple usernames on each line to save space.
Have one contributor per line and email addresses in the first list only.

**Comment by sfan5** [comment]
Including a huge contributor list simply generated from the git history is just a waste of space. :-1:

**Comment by paramat** [comment]
I think it would be about 300 in total. 10 per line makes 30 lines.
Perhaps just the first list then?

**Comment by ShadowNinja** [comment]
Listing everyone from the Git history would be quite long.  I think just a list of people contributing to the current release would be fine.

**Comment by dsohler** [comment]
So, basically [this](https://github.com/minetest/minetest/graphs/contributors) in text form? Why not simply link it?

**Comment by DS-Minetest** [comment]
the 2nd list also contains the committer of minetest_game

**Comment by red-001** [comment]
Just get the 30 top/most recent contributors and link to the github list?
