### ISSUE TITLE
Turn mod security off for release

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#4944]
With bugs still occurring #4943 and complex work still being done, i don't feel we can enable mod security for this release, the risk of problems is very high. As agreed a while back, in this situation security should be disabled for release then re-enabled afterwards.

**Comment by Wuzzy2** [comment]
:-(

**Comment by est31** [comment]
Its sad, but the best option for stability atm. About agreement, three coredevs agree on this: @paramat @sfan5  and me.

Once 0.4.15 is released, and a proper fix for #4943 is done, mod security can be enabled on master now, and hopefully shipped with 0.4.16.
