### ISSUE TITLE
Inconsistent data types in Itemstack

### ISSUE THREAD

**Issue by forsakenquantum** [minetest/minetest#4947]
The `awards` mod has a `register_on_craft` which receives an `itemstack` object. In general, it appears that `type(itemstack)=="userdata"`, however, in some cases it looks like `type(itemstack)=="table"`. Specifically, if I make a mese pickaxe and add a couple of cavorite handles, as long as the mese pickaxe has never been used, then `type(itemstack)=="userdata"` and when the awards mod calls `itemstack:get_name()`, everything is fine. But if the mese pickaxe has been used, then `type(itemstack)=="table"` and trying to call `itemstack:get_name()` crashes the server.

I can work around this by detecting when `type(itemstack)=="table"` and then callling `itemstack["name"]` to get the name instead of `itemstack:get_name()`, but I feel like this isn't optimal

**Comment by TeTpaAka** [comment]
This is intended (see http://dev.minetest.net/ItemStack). You could also use a string as an itemstack.
If you want to have a consistent interface, you can always call
`ItemStack(itemstack or itemstring or table or nil)`
to get a userdata object.

**Comment by paramat** [comment]
Perhaps we should avoid a crash for this situation?

**Comment by stujones11** [comment]
Perhaps we should avoid a crash for this situation?

I am not sure how that would be possible, calling a method on a string or a table will obviously cause a crash. I think the documentation is fairly clear about this and the reason why ItemStack() is provided by the api.

**Comment by rubenwardy** [comment]
If the parameter is called itemstack then it should always give an object that conforms to ItemStack. It's misleading otherwise

**Comment by stujones11** [comment]
Yeah, I may have misread the issue, `register_on_craft` should be made to always return a valid `userdata` object.

**Comment by SmallJoker** [comment]
*bump* @fermionic, I think you should check all enabled mods that use `minetest.register_on_craft`. Most likely this error is caused by one of these. They return string or tables (since it's a valid stack, by definition), but these values do not get converted to the userdata `ItemStack` anywhere, that's why calling functions such as `:get_wear()` fail.
