### ISSUE TITLE
Server join queue

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#4948]
Right now players are rejected completely with their connection ended if they try to join a full server. Could be nice to add an option to have players stay connected, but not joined into the game, until a spot is opened on the server, like how some games do it. You could display a "x people in front of you" thing too.

Example: The server can hold 1 player, and player A is playing. Players B and C try to join (in that order), and the server puts them in a waiting queue. Player A leaves, and player B is immediately joined into the game. Player C is still waiting for B to leave (or for C to leave early).

**Comment by est31** [comment]
I think we should rather work on making minetest more efficient to allow more players on the servers.

**Comment by raymoo** [comment]
Unless it gets efficient enough to host 1000 players on low-end hardware, I think this is still a relevant suggestion.

**Comment by bigfoot547** [comment]
:+1:
I like the idea.
