### ISSUE TITLE
Creating own Scripting Language

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4956]
What about creating an own scripting language instead of using Lua?

For the same reasons Godot choose to create it's own language

http://docs.godotengine.org/en/stable/reference/gdscript.html#history

**Comment by ShadowNinja** [comment]
This would be a massive amount of work for very little benefit.  Also, we won't be able to match the speed and portability of LuaJIT without even more work.
The only advantage seems to be better multi-threading support, which we can work around with things like the async API that the main menu has.

**Comment by est31** [comment]
I admire godot, its a great project. Also, gdscript is great, you can get started with it really fast. But godot has the sad tradition of rolling their own stuff for little actual benefit. Also, godot is non stable, meaning they are okay with breaking things. Having their own language makes it easier for them to break things. Minetest is the opposite about this. Its meant to have a stable API, without major breakage.

Gdscript is slow, and many people have complained about this already.

LuaJIT is so fast that some people joke it has been created by an [alien from the future](http://wren.io/performance.html), and unless you have your own alien yourself, you shouldn't try re-rolling something like it.

Maybe it would be a fun project to invent your own language and implement it, but I'm sure it will be way behind the features and speed of LuaJIT.

It would be great to have better multi threading support, and a way around that "not enough memory" issue, but coming up with our own language would be a very bad approach towards this.

So general :-1:  from me.

We could try to experiment with the ability to write mods in Rust (or some other already existing language, but Rust is my favourite xD) though, at least for computation heavy mods like mapgens. Of course, its no scripting language, but its fast like C++, and rubyists, aka people who did many things in scripting languages before, love it, preferring it much over C++.

**Comment by nigels-com** [comment]
As a casual observer, I'd probably rather learn more Lua, than pick up something game-specific.  As a dependency, Lua seems manageable and (mostly) stable.

**Comment by paramat** [comment]
:-1:

**Comment by MarkuBu** [comment]
Even with ActionScript you won't have MT specific data types or 3d functions like vectors. And the memory issue is annoying

**Comment by C1ffisme** [comment]
You're about 4 years too late to suggest this now.
