### ISSUE TITLE
Add support for building against system Lua

### ISSUE THREAD

**Issue by ignatenkobrain** [minetest/minetest#4964]
Unfortunately, luajit is not available on ppc64/ppc64le and only option is to build against Lua, but there is no option to use system lua..

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by sfan5** [comment]
This is definitely useful, distros will do this anyway even if we don't support it.

**Comment by TurkeyMcMac** [comment]
Building against the system Lua is now entirely unsupported due to the use of custom functionality added to Minetest's Lua (specifically `lua_atccall`).
