### ISSUE TITLE
minetest.chatcommands is not mentioned in lua_api.md

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4970]
There's a table named `minetest.chatcommands` but it is not mentioned in `lua_api.txt`.

Any variable which is not documented **does not exist** from the modder's point of view. Please fix this.

**Comment by rubenwardy** [comment]
#4969

**Comment by DS-Minetest** [comment]
isnt it `lua_api.txt`?

**Comment by DS-Minetest** [comment]
dont just give a thumb up, edit it, if im right
or should the thumb mean that i should be executed by the other gladiator? or should i kill the other gladiator because i am right and shouldnt show mercy?

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest/commit/e8b7179ccd5b1f70eba3f9ac570c5f10474cf7a7
