### ISSUE TITLE
Minimap's radar mode is completely green (and useless) at certain heights

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#4972]
The radar mode of the minimap sometimes turns completely green without any shading and is basically useless when you have passed certain height levels. Even if some higher terrain is around you.

This looks pretty nice:
![unbenannt2](https://cloud.githubusercontent.com/assets/1675853/21529729/da3b3f00-cd3b-11e6-957b-8f43b8d33386.png)

Now if I just jump up by 1 block height, this happens:
![unbenannt](https://cloud.githubusercontent.com/assets/1675853/21529730/da417140-cd3b-11e6-9fda-39f2a44acf3f.png)

Note the coordinates and the seeds in the screenshots. The mapgen used was v7. The zoom level is 1.
From the screenshots you can also see the player is not even at the topmost block in this area.

The effect is highly noticable at very flat areas as seen in the screenshot.

**Comment by rubenwardy** [comment]
It's for underground use

**Comment by Wuzzy2** [comment]
Clearly this behaviour shows that something seems to be wrong with the radar mode.
Why should the radar jump from showing useful data to complete green-ness?

The radar might be useful for navigating in cities as well, but not if it jumps around from useful to green.
My Tutorial subgame also fails to expain the radar properly because the radar is all-green for Tutorial World.

**Comment by ExeterDad** [comment]
I've been trying to find the conversation without luck. I recall RBA stating that the radar was never designed to show with  complete accuracy the voids or solid objects around the player at the current level. Instead it's designed to show in a range to avoid making things too easy for a player to find or avoid caves, tunnels, lava etc. You can easily prove this works as he designed by digging a long straight tunnel. You will be able to see your tunnel clearly on the radar. But if you were to dig and locate yourself straight up or straight down from that tunnel, you will not see your tunnel removed from the radar for a long time.

I agree with you that the radar may not show the results you were expecting, but I also feel the radar works as designed and it is not a bug.
