### ISSUE TITLE
Node selection is inaccurate

### ISSUE THREAD

**Issue by juhdanad** [minetest/minetest#4973]
It is possible to select nodes further than 4 nodes from you if you look diagonally.
To reproduce: build a 6\*6\*6 node large hollow cube. If you stand in one corner, you can reach most parts of the walls. (you must be in survival mode).

**Comment by DS-Minetest** [comment]
i think the reason for this is that each dimension is checked by its own, not the real length
l=((x^2+y^2)^0.5+z^2)^0.5

**Comment by juhdanad** [comment]
@DS-Minetest The reason is that the shootline is longer than it should be by one node: https://github.com/minetest/minetest/blob/master/src/game.cpp#L3828
