### ISSUE TITLE
Minetest on Ubuntu starts with window title below the panel

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4977]
Most time I run Minetest the window opens at the top edge of the desktop, below the panel. I have to move the window with Alt key pressed

This happens with Ubuntu 14.04 and later.

![bildschirmfoto vom 2017-01-01 15-40-37](https://cloud.githubusercontent.com/assets/16163058/21581615/2bd9ba3a-d039-11e6-87d1-20e840e2dc31.png)

**Comment by JurajVajda** [comment]
Not happening on 16.04

![selection_051](https://cloud.githubusercontent.com/assets/5089392/21581749/beed406c-d00c-11e6-8681-c0c09b580fd6.jpg)

**Comment by juhdanad** [comment]
The window is misplaced for me, too.

**Comment by est31** [comment]
This looks like a known bug with ubuntu: https://bugs.launchpad.net/ubuntu/+source/compiz/+bug/1303462

**Comment by MarkuBu** [comment]
@JurajVajda might not happen if you open the window maximized. It also not happen if other windows (not maximized are open

@est31 I only noticed this with Minetest, but could be an Unity issue, thx

**Comment by Zeno-** [comment]
I have a similar "problem" with Fedora (except because my panel is at the bottom the bottom of the minetest window is hidden). I figured it was a window manager issue and just forced the position where minetest should open (by using the window manager and setting explicit x, y coordinates)

**Comment by paramat** [comment]
Not a Minetest issue so closing. Remember to use Alt + drag, good tip.
