### ISSUE TITLE
Travis: Update OS X and Linux compilers (g++, clang) to latest version

### ISSUE THREAD

**Issue by AraHaan** [minetest/minetest#4980]
Please install g++-6 or newer (g++-7 and gcc-7 from source) for the projects that use C++ 14~17, besides it has some bug fixes and some performance fixes as well.

Example being like this especially clang 3.9 requirements on projects fails when someone uses ``std::experimental::filesystem`` in the ``<experimental/filesystem>`` header in C++ 14, in C++ 17 it will move to ``std::filesystem`` and the header would be renamed to ``<filesystem>``

https://travis-ci.org/AraHaan/bin2c/builds/188047806 As you can see all the OSX builds fail because clang 3.9 and g++-6 are not present. But the gcc 6 build of it on linux works just fine. Note: I try to manually hack the compilers and the clang version to 3.9 using the build matrix method.

Besides a lot of projects requires g++-6, gcc-6, and clang 3.9 only to build and any versions before that would be no dice. Mainly I want OSX and the linux VM's to at least always have the latest compilers so I don't have to hack my ``.travis.yml`` just to have it install it and waste some time before build just to make it work. An example compile that also comes with latest gcc option is at gcc.godbolt.org but it does not include osx building. So updating the compilers to the latest on those VM's by default should help make all the C++14~17 programmers happy.

**Comment by AraHaan** [comment]
I just realized this was not the travis-ci repo. dang it google.

**Comment by rubenwardy** [comment]
That makes this issue make more sense :D
