### ISSUE TITLE
Add "Pick Block button" in survival/creative

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4984]
This feature is used in MC with great success, it simplifies building a lot. Here is short description from their site:
>Switch to the block currently looked at, as long as it is in the inventory(in creative mode the item will appear on the hotbar ignoring if the item is in the inventory or not). In Creative mode, if the block is not in the quickbar, replaces the currently active quickbar slot with the block currently looked. http://minecraft.gamepedia.com/Controls#Pick_Block

Currently they use middle mouse button for that,

**Comment by tobyplowy** [comment]
@Fixer-007 totally agree this would be amazing for building in creative

I know one of the next comments will be by paramat he will probably say something like yeah but if you break a block you also get it why would you need this, and to that I Would Point him to my my issue I made  a while back if you brake blocks your inventory gets filled Up With crap You Don't Need and it makes building in creative less fun

**Comment by dsohler** [comment]
… yeah. And then some other developer steps in continuing that this would only add complexity but totally ignores that there are actual people out there playing Minetest instead of only developing it.

And after three or four replies the discussion will fade out and this issue here will be ignored for a few months before it will be closed because of no-one participates anymore.

That’s the usual thing that happens if someone requests an enhancement that the first-reacting dev does not like.

**Comment by rubenwardy** [comment]
Stop being so cynical. This is a very useful feature that I don't see even paramat opposing in concept

**Comment by tobyplowy** [comment]
@rubenwardy if this is added it can fix https://github.com/minetest/minetest_game/issues/1389#issuecomment-270006479

**Comment by tobyplowy** [comment]
@dsohler true I think everyone should think of every issue with an open mind that would make minetest development alot better! And all of the, this is a mod thing really drives me mad!

**Comment by bigfoot547** [comment]
Yes. Ctrl+middlemouse should keep the metadata of the block and restore it when the item is placed.
The meta table will be stored as a serialized string in the item metadata.
:smile:

**Comment by dsohler** [comment]
> I don't see even paramat opposing in concept

Because - quote - “it's not important enough.” - quote end. So the other issue was closed and I’m pretty sure this one will be, too.

**Comment by tobyplowy** [comment]
@dsohler true @Fixer-007 you can already close this it's already dis approved :/

**Comment by rubenwardy** [comment]
He's talking about ctrl+middle to save meta data, not the middle

**Comment by Fixer-007** [comment]
I was not talking about metadata. It just middle mouse click searching for pointed block in your inventory and selects it to work with

**Comment by DS-Minetest** [comment]
This can be done by a mod adding a tool.
eg. HybridDog's `superpick` mod ([Forum topic](https://forum.minetest.net/viewtopic.php?t=3691)) ([Github repository](https://github.com/HybridDog/superpick))

**Comment by paramat** [comment]
> This is a very useful feature that I don't see even paramat opposing in concept

LOL.
I don't oppose it, just not mouse middle button as many mouse devices (touchpads, trackballs) do not have a middle button (nothing i have ever used has had a middle button).

**Comment by rubenwardy** [comment]
> not mouse middle button as many mouse devices (touchpads, trackballs) do not have a middle button (nothing i have ever used has had a middle button)

That is an issue ofc. There could always be two bindings, middle click and say 'p'.

This should be implemented as a generic function callback such as `on_auxclick` or `on_alt_interact` or something like that

**Comment by C1ffisme** [comment]
@paramat Some mouses require you to press both mouse buttons as the same time. And as @rubenwardy has said, you can always map the key to something else.

**Comment by paramat** [comment]
> Some mouses require you to press both mouse buttons as the same time.

I know and it's very unpleasant to do that, almost unusable.

**Comment by dsohler** [comment]
People using such hardware know the limitation and already handle that because  shit-ton of applications use middle mouse button for navigation.

It should be a configurable option, of course.

**Comment by paramat** [comment]
I have found very few applications that absolutely require a middle mouse button. Pressing 2 buttons at once is often a feature but is laughably unusable and unhealthy for the hand.

**Comment by rubenwardy** [comment]
The majority of games I play use a middle mouse button. Yes, it shouldn't be required, but that doesn't mean it shouldn't be supported at all

Again,

> There could always be two bindings, middle click and say 'p'.

**Comment by paramat** [comment]
Sure i agree, it's fine as long as a key is also possible.

**Comment by dsohler** [comment]
I guess we all agree that it should be fully configurable (button, key, modifier for metadata, etc.)
