### ISSUE TITLE
Add "Instant game reload" for lua development purposes

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#4988]
While I was watching the stream with guy developing lua mod for minetest, I had an idea.
Lets say you have IDE on left part of screen, and Minetest on right part.
You are working in IDE, changed the code, saved it, now in minetest window you press special Key that instantly reloads the game (without killing the game and relaunching in terminal).

Can it save some time and be convenient for lua dev?

**Comment by juhdanad** [comment]
If you quit to the main title and reload your world, the scripts are reloaded.

**Comment by C1ffisme** [comment]
So, if I'm understanding you correctly, you want a key that automatically exits the world and loads it back up again?

I'd prefer a command, but could be useful.

EDIT: Ninja'd.

**Comment by Fixer-007** [comment]
>So, if I'm understanding you correctly, you want a key that automatically exits the world and loads it back up again?

Yes

**Comment by C1ffisme** [comment]
@Fixer-007 Could require long-term engine changes, but if this were possible to do without the server going down, that could be especially helpful. (Clients would see a loading screen as mods are re-downloaded, and then the game would resume.)

**Comment by nerzhul** [comment]
reloading Lua stack is not possible as Lua & CPP core are linked, only a server restart permits to have a cleaned up Lua environment

**Comment by beyondlimits** [comment]
> reloading Lua stack is not possible as Lua & CPP core are linked, only a server restart permits to have a cleaned up Lua environment.

You mean we can't just destroy current Lua environment and create new?

**Comment by juhdanad** [comment]
@beyondlimits: re-creating the Lua environment would re-define nodes. The server had to send the new node data to the clients, and new nodes would cause media downloads ingame. You can not restart Lua, because there are code parts that run at the server's initialization.

**Comment by est31** [comment]
You can easily get to something similar with scripting, e.g. where you restart both client and server from the command line directly to the game.

With this alternative in mind,  I think the engine doesn't need more support built in for this.

**Comment by beyondlimits** [comment]
Kinda hacky way with bunch of caveats, but if you like to experiment, whatever callback you have, you can use:

```
local modpath = minetest.get_modpath(minetest.get_current_modname())

local function external(filename)
	local path = modpath .. '/' .. filename
	return function(...)
		local status
		local code, err = loadfile(path)
		if code then
			status, err = pcall(function(...)
				loadfile(path)(...)
			end, ...)
		end
		if err then
			minetest.log('error', err)
		end
	end
end
```

Example of use:
```
minetest.register_craftitem('wand:wand', {
	description     = 'Wand',
	inventory_image = 'wand.png',
	stack_max       = 1,
	on_use          = external('script.lua'),
})
```
then in script.lua:
```
local itemstack, player, pointed_thing = ...
minetest.chat_send_player(player:get_player_name(), 'Hello')
```
Changes to script.lua are reflected without restarting the server.

You can also use your chat box as a developer console (like in web browser):
```
if minetest.is_singleplayer() then
	minetest.register_on_chat_message(function (name, s)
		if string.sub(s, 1, 1) == "=" then
			s = "return " .. string.sub(s, 2)
		end
		local result
		local status, err = pcall(function()
			result = loadstring(s)()
		end)
		if status then
			minetest.chat_send_player(name, dump(result))
		else
			minetest.chat_send_player(name, "ERROR: " .. err)
		end
	end)
end

http://pasteboard.co/i7VoD0WYA.png

**Comment by paramat** [comment]
:-1: The effort and code bloat doesn't seem worth it, it's easy enough already to exit and re-enter a world
