### ISSUE TITLE
No damage when buried by sand or gravel

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#4995]
The player doesn't get damage when buried by sand or gravel. He just stuck

**Comment by nerzhul** [comment]
@MarkuBu the problem is in minetest_game not minetest, please report a bug there. Note: damages like lava should be added

**Comment by tenplus1** [comment]
Try using PlayerPlus mod, it has suffocation and cactus hurt added: https://github.com/tenplus1/playerplus

**Comment by nerzhul** [comment]
@tenplus1 i think these optimisations should be added to mtg directly as it's just logicial (and like MC too)

**Comment by MarkuBu** [comment]
You're right. It's MTG. Close this and reopen in MTG
