### ISSUE TITLE
Search for settings

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5001]
Sometimes it would be helpful to search for settings by name, e.g. enter "mouse" and all parameters for mouse are listed.

Search should be work for technical names and the real names in the current language

I know that I can edit the minetest.conf, but there are not all settings listed

![bildschirmfoto vom 2017-01-06 16-13-47](https://cloud.githubusercontent.com/assets/16163058/21722028/27f7477a-d42b-11e6-9d9b-1e971fa54a7c.png)

**Comment by SmallJoker** [comment]
What exactly is missing in pull #4806 or did you not know of it?

**Comment by MarkuBu** [comment]
Ups, Sorry, missed that pull. Close this issue
