### ISSUE TITLE
Auto-disable sky darkening above water_level

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5006]
Related issue #3577 
We have a problem of the skybox wrongly going dark in certain situations.
The addition of floatlands creates large areas of shadow under them which now makes the skybox go dark when seeing the blue atmosphere and clouds below is needed.

My suggestion is: Since we already make assumptions about light according to y >/< water_level, and since skybox-darkening is effective underground and mostly a problem above ground, auto-disable the behaviour above water_level.

Obviously this will cause some subtle light in caves above water_level, but i feel is worth it. Caves in mountains may not always trigger sky-darkening anyway because there may not be enough volume of darkness.

Related code:
Controlled by 'sunlight seen' bool.
https://github.com/minetest/minetest/blob/master/src/clientmap.cpp#L752
in
https://github.com/minetest/minetest/blob/master/src/clientmap.cpp#L653
called from
https://github.com/minetest/minetest/blob/master/src/game.cpp#L4090

**Comment by Fixer-007** [comment]
Related issue https://github.com/minetest/minetest/issues/3577

**Comment by paramat** [comment]
PR #5014

**Comment by paramat** [comment]
Decided against this method.
New PR #5028
