### ISSUE TITLE
spectator mode support

### ISSUE THREAD

**Issue by leslie-wang** [minetest/minetest#5015]
Minecraft has spectator mode support. Does Minetest provide this feature?

**Comment by sofar** [comment]
I googled for "minetest spectator" and found this as first hit:

https://forum.minetest.net/viewtopic.php?t=13718

**Comment by leslie-wang** [comment]
Minecraft spectator mode allows spectators to fly, clip through blocks and entities, and view all entities, including other players in spectator mode. Seems like Minetest spectator can not fly to arbitrary places. Is it corrrect?

**Comment by sofar** [comment]
The engine supports all the functionality needed to make spectators fly, clip through blocks and entities, view all entities including other players in whatever mode you want to call it.

Note, it is an **engine**.

There are several mods (unrelated projects to the engine, that use the engine's API) that provide you with spectator-mode like functionality. If none of those mods provide the functionality you specifically need, you have to program it yourself, or file a bugreport against those mods instead.

But this project, the one where you filed an issue report in, fully supports any spectator mode functionality you can think of.

**Comment by leslie-wang** [comment]
that is great. I'll try and report my finding. Thanks for quick reply
