### ISSUE TITLE
Lua API: Add minetest.find_node()

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#5017]
Currently, minetest.find_node_near( ) searches for nodes (either by name or group) within a given radius _outside_ of the specified position. This results in unnecessary complexity and redundancy for certain very basic tasks, such as placing bones at or near the location of a dead player or mob:

```
local bones_pos = vector.round( player_pos )
local node_name = minetest.get_node( bones_pos ).name
if node_name ~= "air" and minetest.get_item_group( node_name, "liquid" ) == 0 then
     bones_pos = minetest.find_node_near( bones_pos, 1, { "air", "group:liquid" } )
end
```

However, with the addition of minetest.find_node(), such logic could be simplified dramatically:

`local bones_pos = minetest.find_node( bones_pos, 1, { "air", "group:liquid" )`

As per Issue  #4819, this new API should be identical to minetest.find_node_near() in every respect, except that the node at the specified position will be compared prior to radiating outward.

**Comment by paramat** [comment]
This will be easy to do, copying 'find node near' code plus a simple change, want to attempt it yourself?

**Comment by paramat** [comment]
Is it ok to close this in favour of #5213 that adds a bool to the existing function?

**Comment by sofar** [comment]
I disagree that this is needed, and I disagree that this will make the code more efficient.

Especially in the case of a player dying, the chance that the node where the player died *is* air or liquid is extremely high.

Therefore, the optimal case isn't to find a suitable spot in many locations, but **check the player death position first**.

You already have the most efficient algorithm implemented.

If you want to prove me wrong, show me raw data from your server that shows that the majority of the bones require the `find_node_near` part of your 4 lines above to be executed, by collecting total deaths and counting how many need the `find` part executed.

**Comment by sorcerykid** [comment]
Considering that players frequently die:

on minecart tracks -- that is not an air or liquid node
on grass -- that is not an air or liquid node
on flowers -- that is not an air or liquid node
on steps -- that is not an air or liquid node
on slabs -- that is not an air or liquid node
in doorways -- that is not an air or liquid node

And even if air nodes are more frequent, that doesn't change the fact that find_node_near( ) already has the exact logic necessary to check the center position first and then to search the surrounding area by changing just ONE value. I'm baffled why this should be a point of contention.

I appreciate concerns about code bloat, feature creep, etc. But sfan5 needs this functionality and so do I. So there should be no question of its utility. Add a boolean argument and be done with it.

**Comment by tenplus1** [comment]
#5213 is a needed feature which can improve node checks for quite a few mods, and for the sake of adding a bool at the end of an already existing function it's not adding any additional bloat.

**Comment by sorcerykid** [comment]
Oops I meant tenplus1 needs the functionality. Sorry, long night!

**Comment by raymoo** [comment]
Just for record purposes, this functionality was added in #5255 (as mentioned in the forum thread).
