### ISSUE TITLE
"AL lib: (WW) .." messages in terminal when exiting from world to menu or OS

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5019]
```
AL lib: (WW) FreeContext: (0x1e9de00) Deleting 1 Source(s)
AL lib: (WW) FreeDevice: (0x1e449f0) Deleting 79 Buffer(s)
```
Probably harmless but thought i'd mention it. Seems to be referrng to audio libraries?
Not sure when i started seeing these messages, fairly recently.

**Comment by nerzhul** [comment]
This output is not from MT itself but from AlsaLib. We cannot handle it
