### ISSUE TITLE
JPG screenshots have nearly the same size as PNG and quality has no effect

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5025]
Because PNG screenshots are to big to upload in the forum I want to save screenshots as JPG. But the JPG screenshots have nearly the same size as the PNG version.

for example: a PNG screenshot has a size of 1.6MB, JPG has 1.5MB

Setting the quality to 50 has no big effect. The file size is still around 1.4MB

If I save the PNG screenshot with my image viewer as JPG the file size is 240kB

**Comment by est31** [comment]
I guess we just have an inefficient encoder.

**Comment by sfan5** [comment]
you mean:

> I guess Irrlicht just has an inefficient encoder.

However IIRC Irrlicht uses `libpng` and `libjpeg`, maybe they just choose inefficient settings by default.

**Comment by kaeza** [comment]
I'm not sure what is wrong with your setup. I just tested a few combinations and works as expected:

```
# ls -lh
total 1,4M
-rw-rw-r-- 1 kaeza kaeza 408K ene 13 15:24 screenshot_20170113_152455.png  <-- default settings
-rw-rw-r-- 1 kaeza kaeza 176K ene 13 15:25 screenshot_20170113_152511.jpg  <-- q=0
-rw-rw-r-- 1 kaeza kaeza 778K ene 13 15:26 screenshot_20170113_152608.jpg  <-- q=100
-rw-rw-r-- 1 kaeza kaeza  28K ene 13 15:26 screenshot_20170113_152631.jpg  <-- q=1
```

**Comment by kaeza** [comment]
Nevermind, misunderstood the issue.

For me, `q=50` results in slightly **bigger** file size than `q=100`. WTH?

**Comment by MarkuBu** [comment]
I made a screenshot as PNG. It has 1.6MB. If I load this PNG in GIMP and export it as JPG with quality 90, the file is 440kB.

If I make the same screenshot with JPG and quality 50 the file size is 1.1MB, so lower quality, but more than twice as big.

**Comment by numberZero** [comment]
MT just uses different quality levels. I’ve just tested it.
Original (could be compressed by the hosting):
[![screenshot-lossless.png](https://s24.postimg.org/uwtzah9h1/screenshot_lossless.png)](https://postimg.org/image/oj4w784kx/)
Minetest, quality=20, 127 kiB:
[![screenshot_mt20.jpg](https://s27.postimg.org/qhj4oul0f/screenshot_mt20.jpg)](https://postimg.org/image/qhj4oul0f/)
Minetest, quality=30, 198 kiB:
[![screenshot_mt30.jpg](https://s27.postimg.org/nopx4tknz/screenshot_mt30.jpg)](https://postimg.org/image/nopx4tknz/)
Minetest, quality=40, 988 kiB:
[![screenshot_mt40.jpg](https://s27.postimg.org/alualjufz/screenshot_mt40.jpg)](https://postimg.org/image/alualjufz/)
GIMP, quality=40, 117 kiB:
[![screenshot_q40.jpg](https://s27.postimg.org/p6fyu4esf/screenshot_q40.jpg)](https://postimg.org/image/p6fyu4esf/)
As you can see, MT’s 20 is just about the same as GIMP’s 40, and the file size is the same.

**Comment by paramat** [comment]
Author left MT, anyone requesting a change to MTs jpg quality setting?

**Comment by paramat** [comment]
Sorry, misunderstood this as a setting we can adjust. Any point in keeping this open if upstream? Is there anything we can do?

**Comment by HybridDog** [comment]
You could add a note to minetest.conf.example about the quality setting behaviour.
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L892

**Comment by paramat** [comment]
Seems no point keeping this open.
