### ISSUE TITLE
$share on Ubuntu linux is incorrect

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#5029]
The minetest customizations in ubuntu are installed in share/games

The installed mods maintained by the [Ubuntu Developers](https://apps.ubuntu.com/cat/applications/minetest/) (saved in /usr/share/games/minetest) are not compatible with the minetest of the [Minetest Development Team](https://launchpad.net/~minetestdevs) (saved in /usr/share/minetest).

**Comment by sfan5** [comment]
Ubuntu chose to use a different share path for their builds, if you want to have compatibility use the build provided by Ubuntu.

**Comment by BrunoMine** [comment]
How can we adjust the minetest installation in ubuntu?
Users can not install the minetest mods available in Ubuntu Software Center.

Alternatively, is there any mods repository for ubuntu that works with the ppa from the Minetest Developer Team?

**Comment by Taose** [comment]
This isn't our problem is it? This Ubuntu's problem. In which case, we shouldn't support changing the installation around of someone else's customized version of Minecraft. For all we know, it could break it. 

I could have sworn that we recommend compiling from source and using the maintained mods on the main minetest site?

**Comment by BrunoMine** [comment]
So let's live with this problem? 
Simply because ubuntu has decided to organize itself in a slightly different dir?

We should trust in the return of mmdb.
:(
