### ISSUE TITLE
 BADLY broken: Recent checkins break Active Objects

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#5033]
Some checkin after 7ae7f1ea4cbbda7d7849a1240ce30d867e850bfb breaks all active objects in the following way:
Once an objects gets out of range it turns into a "Unknown Object" the next time they come into range. That change is permanent (persisted to sqllite) it seems.

I suspect "Optimize SAO getStaticData by using std::string pointer instead of return copy" or "Cleanup content_sao by factorizing similar code parts"

Can't track down which one right now, but it's pretty bad.

**Comment by Zeno-** [comment]
This is confirmed by using git bisect?

**Comment by est31** [comment]
cc @nerzhul

**Comment by nerzhul** [comment]
hi @lhofhansl thanks for the bug report. The mentionned code only move exactly similar parts to parent object, i will re-verify the diff to ensure something wasn't forget

**Comment by nerzhul** [comment]
@lhofhansl i suspect https://github.com/minetest/minetest/commit/ef0aa7d5b543b6561e1b7292b2d0a0ac43add55d because this code is invoked at object deactivation, but atm i don't see the problem on this code.

**Comment by nerzhul** [comment]
I found the problem i think , i need to test it:

https://github.com/minetest/minetest/commit/ef0aa7d5b543b6561e1b7292b2d0a0ac43add55d#diff-5e9cb59de8d770b571fe51af0e62a82bR122

Problem is here, unlike child functions, the main function is not const. I think compiler just use ActiveObject::getStaticData instead of LuaEntitySAO::getStaticData

**Comment by nerzhul** [comment]
I pushed the const fix directly to master, it's that. I added a cout to LuaEntitySAO it's not called if base function is not const, but call with it.

@lhofhansl thanks for report it.

**Comment by lhofhansl** [comment]
I can confirm that this is fixed now.
(Sorry I didn't have the energy to track it down myself yesterday night.)

**Comment by nerzhul** [comment]
no problem, it was my responsibility to fix it :)
