### ISSUE TITLE
higher default values for max_block_generate_distance and max_block_send_distance

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5034]
I would like to propose to increase max_block_generate_distance and max_block_send_distance to higher default values.

Their default values are good for a view range of 100, but if you increase the view range you see map blocks popping up in the distance and you can only see the parts of the map that are already generated.

On the other hand you can set max_block_generate_distance and max_block_send_distance to 50 without any negative effect for lower view ranges. At least I didn't notice any effect.

If you set the view range to e.g. 70 and press r for full range you can see that nothing is generated outside the view range

**Comment by SmallJoker** [comment]
These mapblocks would also be generated in that radius underground. That's a lot more of not used data on servers. I think the current generate distance is just right.

**Comment by MarkuBu** [comment]
Does it has any impact to the performance if the database is a little bit larger? I'm not sure if there will be much more generated. Will try that later

But it is a deal breaker for a game if you can change something, but it has no effect. 

Like in this case. A player has a high end gaming PC and wants to be able to use his power. But if he increases the view range, nothing happens.

So something has to be changed here. Higher default values, presets or automatically adjusted parameters if view range changed

**Comment by MarkuBu** [comment]
It doesn't matter if max_block_generate_distance and max_block_send_distance to higher are set to default or to 50. If the view range is set to 100 in both cases the exact same data is generated.

And I think it doesn't matter what is set at the server. If the client has higher values the server has to generate the mapblocks

**Comment by paramat** [comment]
> It doesn't matter if max_block_generate_distance and max_block_send_distance are set to default or to 50. If the view range is set to 100 in both cases the exact same data is generated.
And I think it doesn't matter what is set at the server. If the client has higher values the server has to generate the mapblocks

Incorrect AFAIK, these settings are serverside.

**Comment by paramat** [comment]
I disagree with increasing these. Players may be travelling straight ahead and not need to see far too either side, and you would be generating a far larger sphere of world around the player and sending more over network too :-1:

**Comment by paramat** [comment]
> I am not sure how it currently works but it would be optimal to adjust the block send distance to the view range of the client.

Nope, this is why we have a maximum, players often increase their view range to huge values for screenshots or viewing large structures, this would cause a huge spike of block sends.

**Comment by MarkuBu** [comment]
With the same view range nothing more is generated. And to the sides nothing is generated as well. Only in the direction you are looking

**Comment by paramat** [comment]
To be clear, the server will only generate and send up to the client's view range, but the client can't force the server to generate or send beyond the set limits.
When i write 'player travelling straight ahead' i mean the player will be looking around while doing this.

> Like in this case. A player has a high end gaming PC and wants to be able to use his power. But if he increases the view range, nothing happens.

Ok i see what you are requesting, but this is client-centred thinking, the limits are there to limit load on the server and network, if the server is powerful enough to cope you ask them to increase the limits so that your powerful PC can see more if it wants.

It's always better to err on the side of lightweightness, then some can increase the limits if they have the power.

**Comment by MarkuBu** [comment]
Well, I think more from the single player side. Then I will close this and return to #5024

**Comment by Ryan-Nolan** [comment]
I see what you mean @MarkuBu and I agree with you @paramat but to solve this problem... 

would it not be possible to have  seperate max_block_generate_distance for the Y axis?

I dont understand how the engine works to this sort of level but my theory is if we could control the max_block_generate_distance on the y axis seperatly to X/Z axis then this i would think would solve MarkBu issue?

**Comment by paramat** [comment]
We used to have generate and send distances smaller for Y but decided to make it equal in all directions, as MT is increasingly vertical now with new mapgens with high mountains and floatlands, and special Lua mapgens. no longer is it just mgv6 that stops at y = 47.
