### ISSUE TITLE
Request digging speed multiplier, accessible through API

### ISSUE THREAD

**Issue by Griiimon** [minetest/minetest#5038]
For my mods and as a great addition to player_effects, i'd like to request a global factor for the players digging speed, like the speed multiplier in the player physics API.

It would allow for potion effects to raise/reduce the node harvesting time. Also diseases, drugs and happiness mechanics in advanced survival mods would profit from this.

Of course, it has to be independent of the tool the player uses.

**Comment by C1ffisme** [comment]
@Griiimon So, you'd be able to make a [Haste](http://minecraft.gamepedia.com/Status_effect#Haste) status effect? I can agree with that. (Though this might be a MTG issue, unless it absolutely requires meta-set-node/itemdef.)

**Comment by Griiimon** [comment]
Yes, exactly. If i knew where to find the code either MTG or here, i could do a branch..

**Comment by paramat** [comment]
:-1: I think it's better to do this with special tools, it seems updating tool capabilities can be done in-game https://github.com/minetest/minetest/issues/5634#issuecomment-379872091
