### ISSUE TITLE
API function for (probably) unique IDs

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#5048]
There are cases where you might want to generate unique never-repeated IDs (unique items, keys, pets?). Currently there is no way to generate such numbers in the API or in Lua itself. math.rand is a bad choice because its seed is not very random.

Other partial solutions:
 - /dev/(u)random: Platform-dependent and requires mod trust
 - Internet-based RNG services: Requires internet and mod/http trust

Since we already have good PRNGs in the API, it would be enough to be able to generate one good seed.

**Comment by raymoo** [comment]
Another bad solution is keeping a counter which is periodically saved (with the map or in its own file), as this counter could get corrupted somehow, and would not be usable between different servers.

**Comment by est31** [comment]
[SecureRandom](http://rubenwardy.com/minetest_modding_book/lua_api.html#securerandom) is an interface for the OS's RNG (/dev/urandom, or windows API stuff that is similar). Use it to seed the RNGs from the API.

I think this is pretty much what you want, so I'm closing.

**Comment by raymoo** [comment]
@est31 Yep, looks good to me, sorry for not looking through the docs more carefully.
