### ISSUE TITLE
No alpha in entity textures

### ISSUE THREAD

**Issue by orwell96** [minetest/minetest#5049]
The opacity texture modifier does not change the texture opacity continuously, but only allows two states:
n = 0-128: fully transparent
n = 129-255: fully opaque
Tested with latest git from right now.
 See comments below, they contain most information!

**Comment by pithydon** [comment]
To my understanding this is how it is for all textures when use_texture_alpha = false or nil in the node_def.

**Comment by orwell96** [comment]
Alright, that did the trick.  Thanks.

**Comment by orwell96** [comment]
... for nodes...
Entities are still affected.
See the same example with entities.
Below the code:
```
for i,opc in ipairs({0,128,129,255}) do
minetest.register_entity("drwho:opc"..i,{
	collisionbox = {-0.5, -0.5, -0.5, 0.5, 2.0, 0.5},
    visual = "cube",
    visual_size = {x=1, y=1},
    is_visible = true,
    use_texture_alpha = true,
	textures={"default_cobble.png^[opacity:"..opc,"default_cobble.png^[opacity:"..opc,"default_cobble.png^[opacity:"..opc,"default_cobble.png^[opacity:"..opc,"default_cobble.png^[opacity:"..opc,"default_cobble.png^[opacity:"..opc,}
})
end
```
In lua_api.txt, there is nothing about use_texture_alpha or a similar property.

**Comment by Thomas--S** [comment]
The opacity filter was made for overlays.

**Comment by Wuzzy2** [comment]
The real bug / missing feature seems to be that Minetest does not support any translucency for entity textures.
It is not limited to the texture modifier, it also happens if the original texture uses translucent pixels. Only 0% or 100% opacity are possible, but nothing in-between.

I think the issue should be renamed and re-labelled as feature request.

**Comment by paramat** [comment]
Semi-translucency is not supported for most nodes anyway.

**Comment by rubenwardy** [comment]
entities (and players) now have use_texture_alpha
