### ISSUE TITLE
GUI Scaling flawed on many devices (especially phones)

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#5054]
On many phones the default GUI scale value is just too high!

Some players on my server tell me they cannot even navigate certain formspecs or menus because part of them is outside of their screen.

Is there no better way to determine the screen size + resolution and adjust the scale that way?

IMO it's absolutely unacceptable that mobile players need to edit the gui_scaling value in the config file manually just to be able to see the entire menu.

**Comment by paramat** [comment]
Perhaps that GUI scaling value can be set to a differrent value automatically for Android? We do that already for other settings.

**Comment by numberZero** [comment]
MT with default settings:
![photo5280846828453079643](https://user-images.githubusercontent.com/7352626/46099330-2a7c9980-c1cf-11e8-9b79-34e462ae3c97.jpg)
@stujones11 That’s what I meant by “unusable.” As you can see, check boxes are tiny (and unlike most GUIs, clicking on the label does nothing). Moreover, scroll bars are that narrow too, so it’s virtually impossible to drag them.

**Comment by paramat** [comment]
Possible blocker.

**Comment by paramat** [comment]
Current Android settings are:
https://github.com/minetest/minetest/blob/d6f2a1c4b8ab13cee92e2041b3410fe3548e88e6/src/defaultsettings.cpp#L423
```
#ifdef __ANDROID__
	...
	settings->setDefault("gui_scaling", "1.1");
	...

	// Check for a device with a small screen
	float x_inches = ((double) porting::getDisplaySize().X /
			(160 * porting::getDisplayDensity()));
	if (x_inches  < 3.5) {
		settings->setDefault("hud_scaling", "0.6");
	} else if (x_inches < 4.5) {
		settings->setDefault("hud_scaling", "0.7");
	}
```
As a first step, perhaps we should adjust these settings to see if they will help with issues #7504 and #6725 , could anyone do this?

**Comment by paramat** [comment]
@MoNTE48 maybe you can help? how does MulitCraft do this?

**Comment by MoNTE48** [comment]
@paramat, It is better to say "_did before_"...
https://github.com/MultiCraftProject/MultiCraft/blob/master/src/defaultsettings.cpp#L407
However, the settings tab is hidden in MC for mobile devices. You need to check it out.

**Comment by paramat** [comment]
@MoNTE48 thanks, please can we use your setting values for MT?

**Comment by paramat** [comment]
MultiCraft settings are:
```
	// check screen size
	float x_inches = ((double) porting::getDisplaySize().X /
					  (160 * porting::getDisplayDensity()));
	if (x_inches <= 3.7) {
		// small 4" phones
		settings->setDefault("hud_scaling", "0.5");
		settings->setDefault("gui_scaling", "1.0");
		settings->setDefault("mouse_sensitivity", "0.25");
	} else if (x_inches > 3.7 && x_inches < 5) {
		// all phones
		settings->setDefault("hud_scaling", "0.6");
		settings->setDefault("gui_scaling", "1.2");
		settings->setDefault("mouse_sensitivity", "0.15");
	} else if (x_inches >= 5) {
		// tablets
		settings->setDefault("hud_scaling", "0.85");
		settings->setDefault("gui_scaling", "1.2");
	}
```
@IhrFussel @numberZero @codexp @rubenwardy @srifqi @stujones11 perhaps those with the MT app can test the settings shown for their screen size?

**Comment by MoNTE48** [comment]
@paramat, Yeah, if that helps, of course.

**Comment by paramat** [comment]
Thanks, looks like oit would help with #7504 
> Display size: 6.2" Quad HD+ (2960x1440) 529 ppi
Hey, cool! Setting hud_scaling to 0.75 has helped and gear button has appeared!
GUI looks so much nicer now.

And GUI scaling slightly larger at 1.2 might help with the menu issue shown above.

**Comment by paramat** [comment]
PR #7784

**Comment by paramat** [comment]
Removed as blocker. Still high priority but any decent solution seems complex and i can't see it being done for a long time, it shouldn't delay release.

**Comment by paramat** [comment]
Only #7850 remains now.
