### ISSUE TITLE
framework

### ISSUE THREAD

**Issue by sd3ntato** [minetest/minetest#5056]
i'm searching for the best framework to debug minetest. can u guys suggest me?

**Comment by rubenwardy** [comment]
Generally you just use `print()` statements to do this

**Comment by red-001** [comment]
It would be nice to have support for a debugger.

**Comment by nerzhul** [comment]
you can use gdb for core.

**Comment by paramat** [comment]
Yes gdb.
An issue is not the right place for this question, the forum would be a better place.

**Comment by sd3ntato** [comment]
Oh thz a lot man i'll use gdb, also sorry for asking here i didn't know i had to ask in forum 
Ciao
