### ISSUE TITLE
Pick up 10 items at a time with middle click.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5058]
I would like to add a feature in (not creative menu) the inventory: giving for example bread by middle-click mouse button to get 10 per middle-click, quicker than 1 item per left-click/right-click.

**Comment by DS-Minetest** [comment]
I don't understand. Do you mean picking up dropped entities?
In inventory you already can pick up and drop 10 items at once with middle click.

**Comment by WSDguy2014** [comment]
@DS-Minetest Because i don't know somehow don't like the idea feature in "creative" mod to get any item, like bread, 10 items per middle-click mouse in creative inventory.

**Comment by GreenXenith** [comment]
This is already a feature.

**Comment by octacian** [comment]
What he means is that he'd like it so that if you middle click an itemstack in the creative inventory, rather than getting one item, you get 10. I think 99 would be better; if you want to get more than one it kinda makes sense.

**Comment by GreenXenith** [comment]
Ah, I see. I think this might be nice aswell.

**Comment by DS-Minetest** [comment]
Aah, I was confused by the
> (not creative menu)

.
It would be very useful getting more than one item out of creative once. :+1: 
So, he meant the creative _inventory_ and not creative _menu_, but what is the creative menu?

**Comment by WSDguy2014** [comment]
@DS-Minetest Its a creative interface...

**Comment by Wuzzy2** [comment]
The real issue here seems to be that sometimes, items can be consumed in Creative Mode. Like when you eat an apple in Minetest Game. This should not be the case.
I'm not sure if this should be considered a Minetest, or a Minetest Game problem.

**Comment by DS-Minetest** [comment]
There are many use cases for this, eg. food or fuel.
Eg. making infinite food would only fix one.

**Comment by purveyor-of-points** [comment]
Ahh, fixed numbers! Ahh, fixed keymaps!

Otherwise, a neat idea. A re-mappable key/mouse press that allows the player to select a determinable (via menu options, probably) amount from a stack would be handy.

**Comment by WSDguy2014** [comment]
There is a problem and need to add a feature: At inventory menu, if you point cursor at any item and pressing "Q" button, will quickly drop stack, holding "Shift" and "Q" button, will quickly drop per item. It used to be for PVP to throw all junk items quickly...

**Comment by Wuzzy2** [comment]
WSDguy2014, please don't hijack other people's issues. Thanks.

**Comment by paramat** [comment]
We have rapid item pickup using scrollwheel now, surely that's better and more flexible as it's not fixed at 10?
