### ISSUE TITLE
Windows servers can be crashed/hung by certain usernames

### ISSUE THREAD

**Issue by red-001** [minetest/minetest#5059]
See http://kizu514.com/blog/forbidden-file-names-on-windows-10/ for a list of filenames that aren't allowed on windows. This seems to stop minetest from creating the player file, causing it to crash.

**Comment by sfan5** [comment]
Instead of some random blog entry, here's the official docs: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by tenplus1** [comment]
Personally I think we should limit player names to a-z A-z 0-9 _

**Comment by ChaosWormz** [comment]
It can also crash and freeze if you chose a specific player name that windows doesn't allow files to be called.

**Comment by numberZero** [comment]
Player data should be stored in a DB. Current storage is weird.
Of course there are other solutions, like limiting player names to ASCII alphanumeric and prefixing file names with `player_` (to avoid conflicts with `NUL`, etc.), or using random names for player data files and storing a separate player list, etc. But these are just work-arounds that may have their own issues.
PS. I have a folder called `C:\*.*` in my home directory =)

**Comment by nerzhul** [comment]
@numberZero yes ofc there is a current draft to add extra attributes and migrate user datas to database, but leveldb is a problem there as it's not a relational DB (or maybe we can only accept players to relational DB & skip leveldb for players)

**Comment by red-001** [comment]
I don't think that adding a hack like that is a good idea, this sort of stuff should be in a database anyway. Storing user input as a filename is never the best idea, much less remote user input. Even if we ignore that filesystems are not designed to store this amount of files and this sort of stuff is exactly the use case databases are made for.

**Comment by Fixer-007** [comment]
Another case for introducing a one database for player files, also easier to backup, instead of copying bazillion files which is very slow in fact.

**Comment by red-001** [comment]
yeah copying the player files takes the longest even on small server despite how much larger the map is

**Comment by Fixer-007** [comment]
It is now possible to write player data into database since recently in 0.4.15-dev

**Comment by nerzhul** [comment]
recently merged sqlite3 support for players should do the trick
