### ISSUE TITLE
Double application of 'visual scale' to plantlike, suggested solutions

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5069]
![screenshot_20170119_030331](https://cloud.githubusercontent.com/assets/3686677/22092211/f9e9ae4a-ddf3-11e6-8083-d0e00556e784.png)

This is papyrus with 'visual_scale = 2.0', it is now 4 times larger, visual scale is applied twice in the code, so to create a certain visual scale a square root of the desired scale has to be taken.

The code starts  correctly with:
```
float s = BS / 2 * f.visual_scale;
```
```
video::S3DVertex(-s,-BS/2, 0, 0,0,0, c, 0,1),
video::S3DVertex( s,-BS/2, 0, 0,0,0, c, 1,1),
video::S3DVertex( s,-BS/2 + s*2,0, 0,0,0, c, 1,0),
video::S3DVertex(-s,-BS/2 + s*2,0, 0,0,0, c, 0,0),
```
.. which scales the texture the correct amount and places it so it's base remains on the ground.

But then later visual scale is applied again for no apparent reason:
https://github.com/minetest/minetest/blob/master/src/content_mapblock.cpp#L1605
```
				for (int i = 0; i < 4; i++) {
					vertices[i].Pos *= f.visual_scale;
					vertices[i].Pos.Y += BS/2 * (f.visual_scale - 1);
```
.. followed by the necessary correction to vertical position to keep it's base on the ground.

We could remove these 2 lines to make visual_scale apply correclty and make the code slightly simpler faster.
Of course, many mods using visual_scale would then be broken, so i suggest that these lines are removed for plantlike 'meshoptions' only, since these are only a month old in stable MT.
However, this would mean that visual_scale acts differently with meshoptions.
We could, perhaps, remove these lines for all plantlike and publicise the change in the forum well before next release. This would be my preference.

I am able to code any changes we may decide on.

This is related to https://github.com/minetest/minetest/issues/4869#issuecomment-273227503 where i have coded downward-extending textures for plantlike and discovered this double application that made what i did difficult, i had to add code to avoid the double application for my special meshoption.

**Comment by sofar** [comment]
I think this is an error resulting from the plant mesh stuff?

**Comment by paramat** [comment]
Nope, old commit by c55 https://github.com/minetest/minetest/commit/eed727c61b51f46f6d172c56ecd26a3b1752d449

**Comment by paramat** [comment]
Related PR #1989 and related commits https://github.com/minetest/minetest/commit/7e34621b1de754449a5849f3ddfe8f77f32e64f5 https://github.com/minetest/minetest/commit/815876e7097fcd1e317ecfd867db807681f9cb1a
However these do not explain c55's original double application

**Comment by paramat** [comment]
Ahh see the file at the time of c55's commit https://github.com/minetest/minetest/blob/eed727c61b51f46f6d172c56ecd26a3b1752d449/src/content_mapblock.cpp#L788
That applied visual scale once, since then it was accidently applied a second time in S3DVertex.

**Comment by paramat** [comment]
Broken here by Sokomine https://github.com/minetest/minetest/commit/19742d8d985dbb0a63a406c881617da7aed50151

**Comment by paramat** [comment]
Oh maybe not ..

**Comment by paramat** [comment]
https://github.com/minetest/minetest/commit/c3703ded953326823c5a0941881d23f3f136f88d
Ugh still working through this.

**Comment by paramat** [comment]
Looks like it was broken during the many changes meant to keep the texture base at ground level, and no-one noticed the double application.

**Comment by paramat** [comment]
Maybe broken here https://github.com/minetest/minetest/commit/19742d8d985dbb0a63a406c881617da7aed50151
So, the second application of visual scale was the original single application, then in the attempt to make plantlike start from the ground complex stuff was done in S3DVertex, broken and fixed several times over. If they had just removed the 'second application' and done it all in S3DVertex it would have worked.

This is a bug then, visual_scale is probably not squared in other drawtypes.

**Comment by VanessaE** [comment]
Just leave it be, @paramat.  There's zero benefit from making such a change, and it's just gonna break mods all over the place.

**Comment by paramat** [comment]
Nope, not zero obviously. Visual scale is currently squared in plantlike and not in signlike or torchlike, it was mistake that adds a small amount of redundant code in a heavily-used drawtype. Plantlike drawtype is not heavily used and it would take a few seconds to update a mod.

**Comment by paramat** [comment]
PR #5070

**Comment by paramat** [comment]
The PR also makes new plantlike meshoptions much easier to implement, for example my experiment with a plantlike that has it's texture starting at the top of a node and extending downwards, this was very difficult to code due to this bug, i ended up having to disable these 2 lines to make it work https://github.com/minetest/minetest/issues/4869#issuecomment-273227503

Such a meshoption will be useful for plantlike nodes placed on ceilings, for when i add underground decorations placable on cave and dungeon ceilings.

**Comment by paramat** [comment]
#5115 merged.
The double application to firelike was fixed in the recent refactor of content_mapblock.
