### ISSUE TITLE
Players killed while attached to entity stay attached and don't respawn normaly.

### ISSUE THREAD

**Issue by red-001** [minetest/minetest#5075]
E.g if a player is in a boat and gets killed by TNT they will respawn still in the boat in the same place.

**Comment by SmallJoker** [comment]
Needs testing after #8701. Maybe fixed.

**Comment by DS-Minetest** [comment]
I've tried to reproduce **without** #8701 and wasn't able to.

**Comment by SmallJoker** [comment]
Ask for re-opening this issue if it still happens.
