### ISSUE TITLE
Lava and water issue in caves

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5101]
Lava and water in caves are not really natural. They should fill the caves and have a closed surface. Especially this "Waterfall" is odd

![screenshot_20170123_084358](https://cloud.githubusercontent.com/assets/16163058/22195470/74736dc0-e148-11e6-9ef0-43177096b711.png)

![screenshot_20170123_084516](https://cloud.githubusercontent.com/assets/16163058/22195475/79e8b440-e148-11e6-9583-b090321c9825.png)

**Comment by nerzhul** [comment]
@paramat any idea ?

**Comment by MarkuBu** [comment]
I don't know how it is implemented now. Maybe I would try to use something like floodfill to fill the plane of the water surface  and then fill below each water source down to the bottom.

But I think this takes some time to render

**Comment by C1ffisme** [comment]
@MarkBu Agreed 100%. They changed this around 0.4.3, and it really doesn't look like an improvement. I really liked the flat lava lakes, which would make more sense if lava had been sitting there for who knows how long. (Long enough for dungeons built on the surface to sink into the ground.)

**Comment by MarkuBu** [comment]
It works much better in mg v6

![screenshot_20170123_171715](https://cloud.githubusercontent.com/assets/16163058/22212139/d1b0787e-e18f-11e6-9a96-9318f2a8c83a.png)

**Comment by paramat** [comment]
Mgv6 should have the same cave liquid generation as all other mapgens, but i can check.
It's not necessarily a bug, more just how it works, probably this way for generation speed.
I think the non-level lava looks ok, as if it is oozing out of vents and flowing down to the sides, lava is viscous, the water looks less natural this way.
I might have a look at the code.
There is another issue on this somewhere i think.

**Comment by C1ffisme** [comment]
@MarkuBu It's still not quite flat, though. :P 

@paramat It's not as much of a question of whether or not it looks like something, as it is a question of whether or not it looks good.

Example of a good looking lava cave: (Found through Google Images:)

![lava cave](https://cloud.githubusercontent.com/assets/9893266/22233150/d0ad4550-e1b3-11e6-9b23-27c1c2660864.png)

[Source](http://www.minecraftforum.net/forums/minecraft-discussion/survival-mode/249223-largest-lava-pool?comment=10)

While the dirt on the left does look a bit out of place, the rest of the scene looks very nice.

**Comment by paramat** [comment]
I like the look of the mgv6 screenshot, where each section of the cave has it's own level which extends mostly to the edges. Having those differing levels looks better to me than a flat surface throughout the whole cave.
Our caves are created in sections, and each section is given it's own liquid level. Some or our caves are created 'flat' and should result in a single liquid level throughout. I'll investigate.

**Comment by paramat** [comment]
![screenshot_20170124_083303](https://cloud.githubusercontent.com/assets/3686677/22239759/e0aece18-e20f-11e6-8926-582f101e3cb3.png)

Try adding
`liquid_range = 0,`
to water and lava source and flowing nodedefs to see how the initial source nodes are placed, they are placed in weird floating blobs.
I've looked at the code, while mgv6 and mgv7 large caves differ slightly i can't see any difference that would make liquids placed in a worse way in non-mgv6 mapgens.
Testing with range zero liquid placement seems just as bad in mgv6 as in other mapgens.

Don't yet know of how to improve but maybe i'll figure something out eventually.

**Comment by MarkuBu** [comment]
You are right. V6 and v7 are the same. I found blobs of water sources or lava fighting against gravity in both mapgens

**Comment by C1ffisme** [comment]
If possible, the lava should be sloped, rather than fall straight down. I'm not sure how difficult it would be to code this, however.

Compare:

![screenshot_20170124_122032](https://cloud.githubusercontent.com/assets/9893266/22260680/af2b1836-e22f-11e6-8dd2-19b9c44db3af.png)
![screenshot_20170124_122023](https://cloud.githubusercontent.com/assets/9893266/22260686/b7102c9e-e22f-11e6-9b20-a83d1d29e619.png)

Also note that the lava texture doesn't look that great either, it's far too bright and unpleasant on the eyes, but that's another issue.

**Comment by paramat** [comment]
Falling straight down is simply liquid mechanics, we can't start rewriting that just because of this issue.

**Comment by C1ffisme** [comment]
@paramat Liquid mechanics wouldn't change, rather, lava (and water, or other liquids generated in caves?) would detect (during world generation) whether or not the lava is above air, and add lava under it recursively (detecting where it will flow), so that the lava slopes rather than falls straight down.

**Comment by paramat** [comment]
That's unnecessary and complex. Something is wrong with placement but vertical drops are fine, as they are in character with MT liquids behaviour.

**Comment by C1ffisme** [comment]
@paramat It's either that or not allowing lava/liquids to generate at all if air will be generated under them for flatter lava. (Or possibly prevent caves from overlapping, if that's why this happens.)

**Comment by paramat** [comment]
No. I don't yet know why liquids are placed strangely, but the intended behaviour will work fine once fixed.

**Comment by MarkuBu** [comment]
@paramat did you change something? Lava and water looks different now. Only the floor is covered

**Comment by paramat** [comment]
Nope.

**Comment by MarkuBu** [comment]
Than it must have something to do with the changes I made in my mod base because now it's looking everywhere like this

https://github.com/MarkuBu/minetest_game/tree/mod_base

![screenshot_20170131_164138](https://cloud.githubusercontent.com/assets/16163058/22472137/fd27950a-e7d4-11e6-92ad-485e06351a8e.png)
![screenshot_20170131_164147](https://cloud.githubusercontent.com/assets/16163058/22472136/fd2647b8-e7d4-11e6-9e75-50ef6cbb5ebd.png)

**Comment by paramat** [comment]
Note that in non-mgv6 mapgens the liquid surface is a few nodes lower than in mgv6.

**Comment by paramat** [comment]
Also these screenshots are the 'flattened caves' whch are less tall. Liquid level is set to a certain number of nodes below cave centre level so in flat caves the liquid surface is closer to the floor.

**Comment by paramat** [comment]
Eacg large cave is created by the carving of many blob-shaped segments, each of these has it's lower part filled with liquid. If these segments are all on the same level there is no problem (half of caves are 'flat' so are like this). But when the segments step downwards you inevitably end up with https://github.com/minetest/minetest/issues/5101#issuecomment-274741308 as the liquid level changes. This can sometimes look good as in the mgv6 screenshot but sometimes not so good. I can't see a way around this that would preserve the character of our large caves.
