### ISSUE TITLE
get_look_horizontal returns values between -2*math.pi and 2*math.pi

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5104]
:cry:

`get_look_horizontal` does not return, as one would expect, only values between 0 and `2*math.pi` (a full circle), but values between `-2*math.pi` and `2*math.pi`.
It seems the negative values appear if you have rotated the player a couble of times clockwise.
There seems to be a single “absolute angle” at which the angle switches from positive to negative.
I think the negative values are completely nonsensical, as they force the user to do `math.abs` to get an actually usable angle.

Also, the documentation does not mention the correct value range.

**Comment by raymoo** [comment]
PR: #5106

**Comment by sofar** [comment]
Note: `math.abs()` would be **wrong** to convert.

**Comment by adrido** [comment]
I created a example mod in the [forum thread](https://forum.minetest.net/viewtopic.php?f=47&t=16466#p247983), to make it easier to reproduce.
sofar is right, `math.abs()` is not the correct conversation, which makes it even more worse to get correct values.

Btw: I would not say this is a Request/Suggestion, this is a real bug! It would be a request, if I would wish a function like `get_look_horizontal_degrees()` that returns the rotation as 0-360 degrees.

**Comment by nerzhul** [comment]
Fixed by #5106
