### ISSUE TITLE
Custom font for subgame (set font path from API)

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#5105]
It Would Be cool to be able to use custom fonts for subgames (without haveing to go to the settings)

I would like to use a custom font for my subgame Also thanks to @Wuzzy2 for reminding me to make this issue
Wuzzy2 wrote
> Font is a client setting (font_path), I can't set it in the subgame (sadly). You can download a Minecraft font here: http://www.dafont.com/minecraftia.font

**Comment by tobyplowy** [comment]
@rubenwardy sorry about

> Custom format for subgame

Auto correct is amazing but sometimes it can be a pain in the ass

**Comment by tacotexmex** [comment]
Yes, this could work just like textures, combined with the setting in the conf.

**Comment by paramat** [comment]
1+ year bump. Any core dev support?

**Comment by oilboi** [comment]
Oh yea, bump bump bump

**Comment by v-rob** [comment]
This issue and #10416 are essentially the same, so closing this one since the other is a little more clear.
