### ISSUE TITLE
Make nodes coloured by param2 distinct

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5107]
This is rather obvious but i get the impression some do not realise this yet.
Currently nodes coloured by param2 act as if they are identical nodes in inventory and when dug, so are not practically usable.
Perhaps we need a new nodedef bool that makes differing param2 values make the node act as different nodes, this would then be useful for other uses of param2.
The node descriptions will be identical though, unless they now display the param2 value.

**Comment by Ekdohibs** [comment]
@paramat most likely the item metadata pr (which also allows to change an item's description, and could probably be made to change its texture as well) would be the best way to fix that.

**Comment by sofar** [comment]
> are not practically usable.

I disagree with this statement. If I wanted to color my landscape and have all the nodes drop the same node, this is highly useful. I can also intercept placement of that same node, and color them after placement.

So, this feature is extremely useful, *without* further modifications.

What @Ekdohibs said most certainly is imho the right way to do *more* with this stuff, though. A new nodedef flag won't help us avoid tons of nodedefs for all the colored variants of node X.

**Comment by paramat** [comment]
Yeah, by practical i mean using it for the wool mod and having each colour wool act as expected as a standard node. Currently it's more of a specialist feature.

**Comment by paramat** [comment]
Hm looking at #1118 it seems to have performance problems.
Am i right in thinking this stores the diff of a nodedef as node metadata in the world database? Seems heavy if used for the large numbers of nodes that would be using the colouring feature. Imagine if every surface node in mapgen had to store metadata.

I wasn't aware that it would be so problematic to make these act as standard nodes, the colouring feature is quite limited and specialised, this makes me feel a little concerned that we rewrote all of node colouring for it and merged it quickly without much questioning. I feel people got a bit too excited about this and were a little careless, i had to make a fuss to get colouring identical to before, and now we can see it was a very good idea for me to insist on this.

**Comment by paramat** [comment]
Perhaps instead there can be node param like 'param2_distict' or something, such that when dug the node is treated as a distinct item according to it's param2? I don't see it needing metadata stored in the world.

**Comment by C1ffisme** [comment]
@sofar 

> If I wanted to color (different shades of dirt or grass) my landscape and have all the nodes drop the same node, this is highly useful.

That's true, but it can already be done with `drop = 'default:dirt'`. Meanwhile, being able to drop items based on params would be incredibly useful... Especially if the item's metadata can be modified. All the colors of wool (And more!) in 1 block definition!

**Comment by numberZero** [comment]
@C1ffisme There is `on_dig`. But remember that items with metadata stack poorly. And IMO that’s not the proper use of this feature. It should be good for something subtle, ephemeral (what MT mostly lacks currently), like grass color variety; or maybe colorful corals, which *should* lose the color when dug. Or e.g. chest dyeing—it may be very handy in the world, but do you need a rainbow of chests in your inventory?

**Comment by C1ffisme** [comment]
@numberZero That's true, but being able to retain the metadata in items would make this double-purpose. It would require engine changes, of course. Not only would you need to change the description, but also the texture of the item being placed. However, I think it would be well worth the trouble, considering the possibilities.

**Comment by sofar** [comment]
@C1ffisme I never said that it couldn't be done - I actually stated that it could currently be done...

@paramat meta set nodedef is not the right solution. Nodes already have a param2 which allows us to determine the color. So meta set nodedef is not a solution (it's orthogonal).

What we need is `ItemStack:get_meta()` and `:set_meta()`, and a consistent way to tell the engine "hey, these 2 wool things are different, you want to color the inventory representation of this one here red, and this one here blue, and when you place them, put these param2 values on the nodes"

**Comment by paramat** [comment]
Yes i would rather avoid using meta set nodedef for this.
I admit this issue is not very urgent, any solution needs to be carefully designed to be elegant.

**Comment by C1ffisme** [comment]
@sofar It's possible, but like you've said, we still need to be able to modify the item's appearance in the inventory so that you don't have to tell which kind of wool is which by placing it. And for visual effect, you also need to be able to set this in crafting recipes, etc. without dying white wool and seeing white wool until you actually craft it. (Not sure if this is possible with `minetest.register_craft_predict()` or not.)

**Comment by Ekdohibs** [comment]
@C1ffisme item metadata would be enough for that. As for the crafting, `register_craft_predict` is indeed enough but a complicated solution, I would prefer to have craft recipes with an output that can have non-null metadata rather than using `register_craft_predict` as a hack for this.

**Comment by VanessaE** [comment]
Unified Dyes currently treats digging param2-colored nodes as identical (aside from also getting the dye back), but if it comes to pass that in-inventory nodes reflect their former param2 status, I'll happily update UD to handle this case (maybe default to it, shift+dig to get the uncolored node + dye).

**Comment by paramat** [comment]
This issue is being worked on now.
