### ISSUE TITLE
Make minetest.get_node() be able see the node groups 

### ISSUE THREAD

**Issue by Yzelast** [minetest/minetest#5111]
Hi guys, i don't know if i'm doing something wrong but i can't get node group with **minetest.get_node()**

Here's the code i was trying to make work:

```
if node.name == "group:soil" then
return true
else		
return false
end
```
And here's the way i make it work:

```
local function exist(table,node)
	for key,value in pairs(table) do
		if value == node.name then
			return true
		end
	end
end 

local function soil(pos)
local soil  = {
		"default:dirt",
		"default:dirt_with_grass",
		"default:dirt_with_dry_grass",
		"default:dirt_with_snow",
}

local node = minetest.get_node({x = pos.x, y = pos.y - 1, z = pos.z})

	if exist(soil,node) then
		return true
	else
		return false
	end
end
```

**Comment by cheapie** [comment]
Try minetest.get_item_group("modname:nodename","soil").

**Comment by Yzelast** [comment]
Thanks, worked great. Although i think it should be easier to simply get node group with only a single function.But it's not really necessary, i think..

**Comment by cheapie** [comment]
I think you can do something like this:
minetest.registered_nodes[minetest.get_node(pos).name].groups
