### ISSUE TITLE
Lighting not working at all (everything fully bright)

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#5116]
[SS1](http://i.imgur.com/4tXRYu4.png)
Only with shaders enabled in latest git minetest. With shaders disabled, works fine.
APU: A8 7600
RAM: 8G DDR3

**Comment by juhdanad** [comment]
Do you use the latest shader files (in client/shaders)?

**Comment by Fixer-007** [comment]
This looks like the very same issue @sofar had in PR5098 that was fixed, but apparently not?

**Comment by lisacvuk** [comment]
@juhdanad I ran 'git clone https://github.com/minetest/minetest.git', 'cd minetest/build', 'cmake ..', 'make', '../bin/minetest'. So, probably.

**Comment by juhdanad** [comment]
@lisacvuk, are caves bright, too? Or is only the sunlight buggy?

**Comment by paramat** [comment]
I can't reproduce this with Intel integrated GPU.

**Comment by Fixer-007** [comment]
I can't reproduce this with AMD/ATI HD6870 (with shaders enabled as author of report).

**Comment by Fixer-007** [comment]
What is your OS and compiler (incl version) btw?

**Comment by sofar** [comment]
The issue went away for my by doing a `make clean` and then a rebuild.

**Comment by lisacvuk** [comment]
@juhdanad Caves too
@Fixer-007 Linux Mint 18.1 Cinnamon, custom compiled Kernel 4.9 with AMDGPU support for GCN1.0 GPUs, which I'm using. Compiler: "gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609" Minetest config is mostly default, with no adv. options changed.

**Comment by numberZero** [comment]
@lisacvuk do you have other MT version anywhere? it tends to use wrong configuration or data files sometimes, depending on whether it was compiled with `RUN_IN_PLACE` or not.

**Comment by lisacvuk** [comment]
@numberZero I do have another version, yes. Maybe I should try compiling with RUN_IN_PLACE.

**Comment by numberZero** [comment]
@lisacvuk Try that, or install the fresh-compiled version. When compiled without `RUN_IN_PLACE` it uses files installed system-wide, but even 1 week old shadres are not compatible with the current code.

**Comment by lisacvuk** [comment]
@numberZero Yes, that seems to be the issue. Works fine with -DRUN_IN_PLACE=1. Thanks, and sorry for false alert, everyone :(
