### ISSUE TITLE
resetting position after setpos

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#5118]
Most times a player is teleported, the anti-cheat resets their position.
This seems to be a major problem with the anti-cheat system.

**Comment by mtango688** [comment]
Do you mean the rubber-banding that sometimes happens? Because I see that fairly often with my version of the nether mod.

**Comment by BrunoMine** [comment]
After some tests I checked that this happens often because of bad connection.
With a PING of approximately 200 milliseconds.
Would it be interesting to create some latency compensation system?

**Comment by mtango688** [comment]
Okay. In the case of the nether mod, it might be double hitting the minetest.after() function because of the delays involved in loading the destination. Does your teleporter use ABM for teleporting?

**Comment by jhcole** [comment]
I'm having similar problems with the justice mod. Players are being returned to jail by anti-cheat after the mod releases them with setpos().

**Comment by BrunoMine** [comment]
I use only the setpos function.

**Comment by BrunoMine** [comment]
My hypothesis is that the client takes some time to go to new_pos and the server can identify that it is still in old_pos.

**Comment by sofar** [comment]
Reproduced this. This is quite problematic:

1 - player gets teleported by server from A to B (far away)
2 - client sees player walk from A to C (nearby A), send new player pos C to server
3 - server thinks player moved from B to C, which exceeds movement limit.

**Comment by Ekdohibs** [comment]
Can reproduce as well, by adding a connexion delay to localhost.

**Comment by Ekdohibs** [comment]
Ok, so here is what happens:
1- player doesn't move much, m_move_pool has lots of free time in it.
2- player is teleported, but client sends old position. Since the movement between both those positions can be explained by m_move_pool, server accepts client old position.
3- client receives new position and sends it; but m_move_pool is now depleted and server thinks the client moved too fast, so resets position to client old position.

**Comment by paramat** [comment]
#5143 merged.
