### ISSUE TITLE
"Minimal dev test" failed to resolve node

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5120]
Decided to report it here:

```
NodeResolver: failed to resolve node name 'mapgen_river_water_source'.
```

PR available: https://github.com/minetest/minetest/pull/4907

**Comment by paramat** [comment]
Harmless, some subgames cause this too because they don't have river water and mapgen is looking for it. I don't think it's important to fix just for minimal.

**Comment by paramat** [comment]
#4907 needs improvement before merge.

**Comment by paramat** [comment]
PR #5809

**Comment by paramat** [comment]
#5809 merged.
