### ISSUE TITLE
node_highlighting=halo bugs

### ISSUE THREAD

**Issue by RHRhino** [minetest/minetest#5126]
It seems that there are some troubles with node_highlighting=halo
1) Halo: highlight selected face does not work. (still worked in 0.4.15 release) https://github.com/minetest/minetest/pull/4653
2) textures are blurred (I think they were always blurred, see screenshots)
3) the color of the textures is wrong and changes over time (see screenshots)

I tried it with with shaders on and off.
Minetest version: 08911160aa5294883a7ebfb681fbf0c1a858dc78

used halo texture
![halo2](https://cloud.githubusercontent.com/assets/6941454/22396656/2472e6be-e55f-11e6-895a-411e7ffbe346.png)

screenshots (blurred and color change)
![screenshot_20170128_132612](https://cloud.githubusercontent.com/assets/6941454/22396650/0019024e-e55f-11e6-97e4-1446ad98903c.png)
![screenshot_20170128_132614](https://cloud.githubusercontent.com/assets/6941454/22396651/00194664-e55f-11e6-9c27-08568584224c.png)
screenshot (selected face is not working)
![screenshot_20170128_134046](https://cloud.githubusercontent.com/assets/6941454/22396667/66546878-e55f-11e6-95d2-d47edd8eadb3.png)

**Comment by juhdanad** [comment]
The changing color is a feature. It was in 0.4.15 too.
https://github.com/minetest/minetest/blob/stable-0.4/src/game.cpp#L517

**Comment by RHRhino** [comment]
> The changing color is a feature. It was in 0.4.15 too.

That's weird feature. It's only really visible with a plain white texture and usually if you use such a texture, you also want it to stay white. 😄 

@juhdanad I saw you created a pull request https://github.com/minetest/minetest/pull/5130 for the face selection. Would it also be possible to make another pull request which makes the texture blur and the changing color optional? Both seem only be useful with the original halo texture, but disturbing for custom halo textures.
