### ISSUE TITLE
Inventory item taking with mousewheel

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#5129]
It would be very convenient to use the mouse wheel to take an item from a stack (especially on touchpads with default synaptics configuration).
Just move your cursor above it,
mousewheel down n times to take n items from the stack,
move your cursor above a free slot,
mousewheel up m times to put m items to the slot.

**Comment by numberZero** [comment]
Should be very handy for filling the craft grid) (I use mouse, not touchpad)

**Comment by beyondlimits** [comment]
related: #2730 #5058

**Comment by HybridDog** [comment]
beyondlimits, this issue is about mouse wheel, whereas those ones refer to middle mouse click.
l don't think paramat has a problem with this since it's just a convenience feature.

**Comment by paramat** [comment]
Correct i don't. Luckily my trackball has a mousewheel.

**Comment by paramat** [comment]
Nice idea.

**Comment by HybridDog** [comment]
> Nice idea.

thank you
