### ISSUE TITLE
Bug in nodeboxes and collision check. And ghost slabs again, in version 0.4.15

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5132]
I found 3 bugs/glitches that i found in 0.4.15:

1. fwhcat found glitch that can go through blocks: https://www.youtube.com/watch?v=gmUfwlcBbyo
it used for secret rooms and/or fire emergency exit. Some directions are works, some directions don't work:
North-East with Simple Bed - Does not work
North-East with Fancy Bed - Does not work
West-North with Simple Bed - Does work
West-North with Fancy Bed - Does not work
South-West with Simple Bed - Does work
South-West with Fancy Bed - Does work
East-South with Simple Bed - Does not work
East-South with Fancy Bed - Does work;

2. I already created minetest_game issue "4 glitches in Minetest version 0.4.14" before https://github.com/minetest/minetest_game/issues/1193, in 4th glitch description, @paramat said: "Now fixed by new slab code", but is a lie! It was improved placing slabs on walls, but didn't fixed ghost slabs glitch. In the comments on 24 Sep 2016, @paramat said: "Yes we have merged changes to slabs so please recheck that bug. Are you saying ghost slabs are fixed?", didn't fixed in 0.4.15.
How to reproduce: https://www.youtube.com/watch?v=wbvXY6GHNP4;

3. Green bar at top-left screen (Not showed in video, only a screenshot). This is was referenced issue "Weird menu bug" at #4592 by @azekillDIABLO was found on main menu screen, i found simple way to find green bar at top-left screen in-game: Right-click mouse button on chest or furnace (even on bookshelf too), press Esc button and right-click mouse button at the same time, sometimes will get this: 
![screenshot_20170128_174610](https://cloud.githubusercontent.com/assets/13905392/22398509/945e03fe-e592-11e6-9005-1939165cfb2c.png)
I didn't used photoshop, try to reproduce this.

**Comment by Wayward1** [comment]
For the last two, you should probably comment in their respective issues ([#1193](https://github.com/minetest/minetest_game/issues/1193) and #4592) instead of using this new one, and leave this one for the bed issue.

**Comment by paramat** [comment]
I tested by copying what you did in the video and had no bugs, but i probably misunderstood, could you explain how to reproduce the ghost slab bug?

**Comment by WSDguy2014** [comment]
@paramat, to reproduce ghost slab bug, you must be have to leave 2 any slab at the same type exactly, not more, nor less, now construct a full block and it creates ghost slab, must be only working if disabled creative mode (does not matter for enable or disable damage).

**Comment by paramat** [comment]
Ah i must have had creative mode on.

**Comment by paramat** [comment]
I can't reproduce the ghost slabs, a ghost slab does very briefly appear then disappear, i think you must have a very slow server because this looks like node placement prediction that is not yet updated by the server.

**Comment by paramat** [comment]
Bug 1 may be related to #4621

**Comment by WSDguy2014** [comment]
@paramat, trying to reproduce ghost slab glitch is hard? it's almost simple, i tested on singleplayer world, i will repeat: disable creative mode (don't enable creative mode, if you enable creative mode, glitch will not work, only in survival mode), you must have 2 slabs on hotbar slot at time, for example 2 amounts of wooden slabs, create a full block wooden plank, after created a full block, will create a ghost slab, i don't need an extremely slow server. If you try to place slab if ghost slab is on chunk. Will updates chunk block, ghost slab disappear, even if you re join your world, ghost slab disappear too. Please, use release version 0.4.15 first, than try on latest 0.4.15-dev version. If you can't reproduce glitch, please, ask other developers to reproduce ghost slab glitch.

**Comment by paramat** [comment]
Yes i tested in creative mode and survival mode and did exactly what you describe.
I tested in latest 0.4.15dev because there's no point in fixing old code, the slab code is probably identical anyway.
Can anyone else test this?

**Comment by Fixer-007** [comment]
>fwhcat found glitch that can go through blocks

This is known, I've posted an issue about something similar here: https://github.com/minetest/minetest/issues/4621

>Green bar at top-left screen

That green bar may appear for short period of time when you work with "craftguide by jp" or "unified inventory" mods IIRC, I've seen it.

Also, please open separate issues for each bug, don't dump them in one big pile.

**Comment by red-001** [comment]
I think the greenbar has something to do with incorrect usage of/bug in tooltips

**Comment by SmallJoker** [comment]
Invalid. Please open an issue for each single bug, feature request or question.
