### ISSUE TITLE
How to combine textures with different sizes (16x16, 32x32, 64x64, ...)?

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#5144]
I have a question about the [combination of textures](http://dev.minetest.net/texture).
The problem is for cases where the textures resolution changes.

For example:
`
"[combine:16x32:0,0=default_stone.png:0,16=default_wood.png"
`

This code works great for reusing the default textures (16x16), but will not work if you apply an texture pack with higher resolutions (32x32, 64x64), or smaller (8x8, 4x4, 2x2)

I want to use default game textures in UV mapping to mesh. This maintains the theme of the textures packs without it being necessary to be created textures for specific texture packs.

**Comment by tenplus1** [comment]
Would be handy if we could use percentage as a value.

**Comment by BrunoMine** [comment]
This functionality is at least very useful.
If there is no solution for this. I expect it to be implemented soon.

**Comment by kaeza** [comment]
There was some work about this on #759.

**Comment by Zughy** [comment]
Closing in favour of #14134 (more info there)

**Comment by appgurueu** [comment]
> Closing in favour of #14134 (more info there)

I think that's a different issue. This issue is a feature request on how to change combine to be able to work with different resolutions (combine currently uses pixels and has no option to use e.g. percentages). That issue is a bug report that overlaying textures created via combine doesn't rescale them as expected.

**Comment by Zughy** [comment]
Uhm it sounds like the same thing to me? Like, they want to achieve the same thing
