### ISSUE TITLE
Scheduling 0.4.16

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#5145]
@minetest/team-minetest as discussed yesterday on IRC somes of us (users and/or coredevs) wanted to release 0.4.16 in a reasonable interval. Last release was done after 9 months of development.

On current master branch we have many fixes and new features, and we are actively developping Client Side Modding in a separate branch. Client side modding is a huge and long awaited feature, which can trigger a major version bump. But before releasing CSM we will need to trigger a last 0.4.16 release on this branch, without this major feature.

This issue is here to discuss about a release date. On IRC, @Zeno- and @paramat talked about 6 months after 0.4.15 release, this step is the 22/06/2017. I except a shorter release, maybe 5 months, because CSM will be ready since the end of march, but i don't want to merge it into master 2 months before release, permitting to add more and more polish during next release cycle. We also doesn't want to rebase branch every weak because CSM will use massively the client code to interact and will need some server parts for interesting features.

What are your ideas for MT 0.4.16 last 0.4.X release ?

here are some proposals:

* 7th may
* 21st may
* 4th june
* 18th june

If you prefer other dates, please tell me, i choose sundays, with two weeks interval.

**Comment by paramat** [comment]
I think this is too early too discuss, i'm still exhausted from the last release and don't want to think about the next.
>  CSM will be ready since the end of march

That's only a guess, why not see how it goes.

Proposing dates makes no sense at this point.

Concerning a shorter release cycle, ther are reasons why 3-4 months is not possible:
http://irc.minetest.net/minetest-dev/2017-01-30#i_4799743

04:29 paramat       some are suggesting more frequent releases, 6 months is ok but 3/4 months is too frequent
04:29 Zeno         I dunno... even MArch/April seems too soon to me
04:29 Zeno         yeah
04:30 paramat       some reasons:
04:31 paramat       preparing for release takes a month and is very busy, exhausting and stressful, more frequent releases means a higher proportion of dev time is busy, exhausting, stressful
04:32 thePalindrome Very much so
04:33 thePalindrome I personally enjoy the "git", or "nightly" versionining
04:33 Zeno         we're already nearly in march
04:33 thePalindrome Where if you *really* want to, there is a pseudo-version to serve as a static commit
04:34 paramat       after a release devs are exhausted and need / deserve a month of holiday / relaxing / taking it easy, maybe some take a break. then we need to feel next release is a decent enough time away to not start worrying about it
04:36 paramat       so, 1 month relax, 1 month release preparation takes 2 months out of the cycle, there needs to be a decent time between to think, discuss, code, review, bugfix big new features
04:36 paramat       i would say 4 months minimum
04:37 paramat       so i would see 6 month cycle about right as a minimum
04:37 Zeno         6 is better :(
04:37 Zeno         4 months we have no time to properly debug the more complex PRs
04:37 paramat       yeah
04:37 Zeno         i.e. give server ops a chance to field test them

**Comment by nerzhul** [comment]
with a date we all can see when on the release cycle doing the biggest changes, when no milestone is due, we don't know how and what release

**Comment by sfan5** [comment]
I'd prefer to reserve 0.5 for when we make non-backwards compatible changes (such as fixing the horrible formspec stuff)

Also I agree with @paramat that it's far too early to discuss

**Comment by DS-Minetest** [comment]
> nerzhul commented a day ago in #5088 
@paramat as @sapier is absent since a long time and @red-001 and me worked hard to securise the current API we should merge it **in 1 week** if there is no more sapier comment.

So, on 11.03.2017 CSM will be merged and
> before releasing CSM we will need to trigger a last 0.4.16 release on this branch, without this major feature.

So, 0.4.16 will be released before 11.03.2017 or on this day.
Am I right?

**Comment by sfan5** [comment]
> Am I right?

no

**Comment by Fixer-007** [comment]
shadow fixes should be merged before release

**Comment by nerzhul** [comment]
@DS-Minetest no we will not release it soon, but CSM should be merged, and disable before release if needed, but i don't think it will be

**Comment by DS-Minetest** [comment]
Ah, so if needed CSM will be disabled at 0.4.16 release and after that enabled again.
Thanks you three for the answers.

**Comment by nerzhul** [comment]
I close this issue as the main subject is now closes
