### ISSUE TITLE
Init packet error when logging on to remote server.

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#5150]
`Connection failure: init packet not recognized by server`

I have a server compiled from the master branch running on a raspberry pi, and a client running Linux Mint x64. (Both OSes up to date via official repositories.) I often have this error at random intervals, when  I try to log into the server. Sometimes retrying works, sometimes it doesn't. No other network problems manifest. I can SSH in just fine and there should be no issues. I have tried enabling `send_pre_v25_init` as the message suggests. When I do so, it just gives me a "connection timed out" error. 

No modifications to the source were made, and all was pulled straight from the master branch and compiled per instruction. Any idea what's causing this?

**Comment by numberZero** [comment]
@avrildev do your server lags? I experience the same problem with one (not my) server when it lags especially horribly (that’s SiE, 1–2 seconds is not considered a lag for it...)

**Comment by avrildev** [comment]
@numberZero Yes, we do occasionally have problems with it lagging, but never this bad. It is mostly very playable. There are only two players using it and it seems to perform quite well, except when this happens. We have quite a lot of mods installed. Could it have something to do with that?

**Comment by sfan5** [comment]
I can confirm that this happens sometimes with specific(?) servers, possibly related to high latency.

It does however solve itself if you try often enough.
