### ISSUE TITLE
Replace node names with IDs in ContentFeatures

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#5156]
`liquid_alternative_source` and `liquid_alternative_flowing` in `ContentFeatures` (`nodedef.h:301`) are declared as strings (storing node names), but the corresponding IDs seem to be used everywhere except of (de)serialization. IMO it’s better to store the node ID instead.
@paramat You’re keeping things in order in MT, what’s your opinion on that?

**Comment by paramat** [comment]
I have needed to set one of these to a different node before, to get a special liquid behaviour, keeping them as strings makes it easy for modders to experiment. I would rather keep it as it is, content IDs are never found within the mod node definitions.

**Comment by numberZero** [comment]
@paramat I don’t mean to change any APIs. Is `ContentFeatures` accessible from Lua at all? I thought it keeps its own copy of node definitions.

**Comment by paramat** [comment]
Sorry, i misunderstood.
