### ISSUE TITLE
use modpack names for dependencies

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5158]
I think it will be helpful if modpack names can be used for dependencies. If it is not important how many mods are in a modpack all mod can be loaded at once.

Additionally modpack.txt can be used if some mods need to load in a defined order

**Comment by sfan5** [comment]
:-1: This won't work, users can name modpacks however they want. You can download mesecons and name it `mesecons-mp`, `minetest-mod-mesecons`, `not_mesecons` or `modpack1234`; each one of those will function identically.

**Comment by MarkuBu** [comment]
I don't understand what you mean, but it is not what I mean

**Comment by MarkuBu** [comment]
I want to give an example. Lets assume I have a modpack named "plants". In this modpack, surprise, several mods with different plants.

Now another mod, lets call it "mapgen", wants to use these plants, but it doesn't care how many mods are in this modpack. It is just important that all mods are loaded before mapgen runs

So I would expect to put the modpack name "plants" in the "depends.txt" from "mapgen" to make sure all plant mods are loaded before mapgen is executed.

Without that I had to put each single mod in depends.txt and I have to maintain it every time I add or remove a mod

**Comment by DS-Minetest** [comment]
:-1:
There won't be any use case for this. A mapgen mod would only use specific nodes from the modpack and these specific nodes are from specific mods in the modpack. If the mapgen mod would want to plant these plants randomly then it would need to get all these mod names and node names in the modpack. This could be simply done by one plants mod. Don't make it more laborious than it has to be.
(Before I saw this I already saw the posts in `post your modding questions` topic on forum.)

**Comment by MarkuBu** [comment]
I have a usecase and it would work, even if you don't believe it.

**Comment by tenplus1** [comment]
This would not work, modpack directories as stated above can be called anything and each mod inside could contain a mod.conf file with it's proper name which SHOULD be used in depends.txt if another mod relies on it...  Add the actual mod names and dont rely on a whole new feature being implemented.

**Comment by MarkuBu** [comment]
So it's only about mod.conf, a mod COULD contain. What about an agreement that modpacks only should be used as dependency if no mod has a mod.conf?

I know that it works what I explained because I have already done this, except the modpack as dependency. I had to list all mods in depends.txt

**Comment by raymoo** [comment]
So the purpose of this is so that you don't have to list the mods in your depends.txt?

**Comment by MarkuBu** [comment]
No, the purpose is that the number of mods in the mod pack doesn't matter.

**Comment by rubenwardy** [comment]
:-1: sorry, this doesn't make sense. Just depend on all the mods in the mod pack
