### ISSUE TITLE
Values in formspec input fields are destroyed when resizing Minetest window

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5161]
If you have a formspec with input fields and you enter in stuff, then resize the Minetest window, everything you have entered so far is destroyed.

To be more precise: The contents of the fields is reset to the stage where you have opened the formspec.

Example 1: Sign in Minetest Game:

* Place sign
* Rightclick
* Enter “LALALA”
* Scale Minetest Window
* You now see an empty input field

Example 2:

* Place sign
* Rightclick
* Enter “LALALA”
* Confirm
* Rightclick the sign again
* Enter “TUTUTU”
* Scale Minetest window
* You now see “LALALA” instead of “TUTUTU”

Example 3:

Find any formspec with a drop-down list. Change the value and scale the window again. The drop-down list will revert back to its original value.

Maybe there are some other formspec elements which are affected by this bug

Tested in 0.4.15 across multiple subgames.

**Comment by Fixer-007** [comment]
Dupe... 8) https://github.com/minetest/minetest/issues/3732
