### ISSUE TITLE
Dungeons in Minimal dev test are made of stone and have holes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5163]
The dungeons in minimal development test are not generated with cobble and they have sometimes "holes" to the underworld

![screenshot_20170202_163736](https://cloud.githubusercontent.com/assets/16163058/22556045/1fd64be0-e966-11e6-8511-74b97cfbdf98.png)

**Comment by C1ffisme** [comment]
Those holes are `ignore`, and they are generated because someone forgot to alias something for the map generator.

**Comment by paramat** [comment]
Easy to fix, just a case of being bothered to do it.

**Comment by paramat** [comment]
PR #5167

**Comment by paramat** [comment]
#5167 merged.
