### ISSUE TITLE
Static build - no dynamic linked binary

### ISSUE THREAD

**Issue by alugarius** [minetest/minetest#5165]
is it possible to make a 100% static binary of minetest?

**Comment by rubenwardy** [comment]
a quick google found this: http://stackoverflow.com/questions/24648357/compiling-a-static-executable-with-cmake

**Comment by kaeza** [comment]
Why do you need a static build?

Maybe your actual problem can be solved in a better way?

**Comment by nerzhul** [comment]
@alugarius you can if you compile yourself all libraries.

**Comment by sfan5** [comment]
Obviously yes, however I don't know how good of an idea statically linking stuff like libGL would be

**Comment by j8r** [comment]
I was able to compile minetest statically by appending this cmake flags: `-DENABLE_SYSTEM_JSONCPP=1 -DENABLE_LUAJIT=1 -DCMAKE_EXE_LINKER_FLAGS=-static` on Debian. However the resulted binary segfaults, maybe due to glibc particularities:
```
/usr/lib/gcc/x86_64-linux-gnu/6/../../../x86_64-linux-gnu/libsqlite3.a(sqlite3.o): In function `unixDlOpen':
(.text+0xa829): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
CMakeFiles/minetestserver.dir/network/address.cpp.o: In function `Address::Resolve(char const*)':
address.cpp:(.text+0x38d): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```
I'll try on Alpine Linux, but some libraries don't have the `.a` archives like jsoncpp and Irrlicht. Patches need to be sent upstream before compiling.

**Comment by FreedomBen** [comment]
@j8r did you ever get this working?

**Comment by nerzhul** [comment]
if you want a pseudo static linked server, just use the gitlab docker image we generated

**Comment by nerzhul** [comment]
See here: https://gitlab.com/minetest/minetest/container_registry you have master tag, and each minetest tag. It's not suitable for client yet

**Comment by j8r** [comment]
Yes @FreedomBen I got it compiling, statically linked on Alpine Linux, after adding the missing .a archives to the upstream packages.

I made a project to compile stattically various projects on x86/ARM, see the directory: https://github.com/DFabric/apps-static/tree/master/source/minetest-static

**Comment by j8r** [comment]
Yes @FreedomBen I got it compiling, statically linked on Alpine Linux, after adding the missing .a archives to the upstream packages.

I made a project to compile statically various projects on x86/ARM, see the directory: https://github.com/DFabric/apps-static/tree/master/source/minetest-static

**Comment by FreedomBen** [comment]
Awesome, thanks @j8r !

@nerzhul thank you for the tip.  For most use cases I think that would be a perfect answer.  For my case I'm trying to harden my existing docker image by removing everything I can in case the server gets compromised.  That way the attacker is jailed into a container that ideally is just `FROM scratch` but if not, still has practically nothing installed.  So far I remove all the compilers and stuff and leave the -dev packages in place, (and that's "good enough" but the nerd in me wants the holy grail :smile: )

**Comment by nerzhul** [comment]
from scratch is a bad idea, busybox is the minimum on a cpp app because we rely on the libc :) at least

**Comment by j8r** [comment]
@nerzhul not if statically linked, if musl-libc used instead of glibc.
