### ISSUE TITLE
Add drawtype "glasslike_optional".

### ISSUE THREAD

**Issue by pithydon** [minetest/minetest#5166]
Would work like "allfaces_optional" without the allfaces part.

**Comment by numberZero** [comment]
@pithydon Explain please, what’s the difference from `glasslike_framed_optional`?

**Comment by paramat** [comment]
Yes this is unclear.

**Comment by SmallJoker** [comment]
Glasslike is used for transparent faces. It will only render the faces on the border to another type of node, excluding its own faces.
The glasslike_framed drawtype will render the faces on the border to another type of node, including its own faces and add a frame around all connected nodes

**Comment by pithydon** [comment]
Thought this would be could be useful for ice to make it optionally transparent.

"allfaces_optional" works for this, but looks bad when leaf style is set to fancy.

**Comment by paramat** [comment]
Ice would then need a second transparent texture.
I can't see a need for an option to change nodes to use an alternative texture.
:-1:

**Comment by paramat** [comment]
We can't use semi-transparency, it has bugs, see #95

**Comment by rubenwardy** [comment]
Please may someone explain what this issue is for? Is it to add a drawtype that changes between glasslike and normal with a setting?

**Comment by paramat** [comment]
The code above shows a single texture with semi-transparency, which would be buggy. The non-buggy version of the feature would be switching from glasslike to normal, but that would need 2 separate textures so can't be done.
Even if possible, there's no need for it, just override the node. Very little use for the feature too.
:-1:
