### ISSUE TITLE
Add spawn_by_distance for register_decoration

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5170]
It is possible to place nodes or schematics next to a node given by "spawn_by", but it is only possible to spawn next to a node

If it would be possible to define a distance, something like palms on a beach or bushes near a river is possible. I tried to add bushes and trees to a river but because rivers have steep shorelines they are squeezed into the riverbed

biomes_lib has something similar, but a C++ implementation would be much faster

![screenshot_20170204_152711](https://cloud.githubusercontent.com/assets/16163058/22619150/7d85f4b4-eaee-11e6-9559-f0e911a9c8c2.png)

**Comment by paramat** [comment]
Possibly, code is here https://github.com/minetest/minetest/blob/master/src/mg_decoration.cpp#L96
For settable radius a new method may be needed, and the mapgen slowness will rise exponentially for larger radius, so i wouldn't want to go beyond 2 or 3.

**Comment by MarkuBu** [comment]
3 would be minimum to make sense. I would limit it to 5 with a warning, that this will slow down the mapgen dramatically. But I would leave the decision to the modder. Maybe he wants to make a server game and he has a fast server or he renders most of the map before players comes in. What if the map generation time doesn't care?

**Comment by paramat** [comment]
Yes actually a low limit doesn't make sense because the modder may use a large radius for a rare decoration, which is fine.
I agree with this feature and will put it on my TODO list.

**Comment by paramat** [comment]
:-1: i don't see enough need.
