### ISSUE TITLE
Android: Control for zoom?

### ISSUE THREAD

**Issue by Repugnus** [minetest/minetest#5173]
hi I was wondering if it would be possible to add buttons for zoom and minimap? And if I wanted to change the location of the controls how would i go about doing that i cant find it in the files on github

**Comment by tobyplowy** [comment]
@Repugnus not Only That but the controls have to be reDone completely ( They are Not So Good And very unresponsive)

**Comment by Repugnus** [comment]
Also what about a button for the use key for the sprint mod and a feature like mcpe split touch(i think this used to be in minetest on android)

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/blob/master/src/touchscreengui.cpp

**Comment by srifqi** [comment]
How can "zoom" key is not needed instantly? In desktop, we _press_ the "zoom" key to zoom and _unpress_ to go back. Did you intend to make it togglable?

**Comment by paramat** [comment]
Yes you are correct.

**Comment by srifqi** [comment]
So, will we re-use magnifying glass (a.k.a. "search" icon) from creative inventory?

**Comment by paramat** [comment]
I think that is suitable for zoom.

**Comment by SmallJoker** [comment]
#7240 merged.
