### ISSUE TITLE
Arm / Wieldmesh Inertia

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#5174]
I started working on the arm / wieldmesh inertia to get a more natural movement feeling, such as in Minecraft and pretty much all modern FPS games. ([See what I mean](https://www.youtube.com/watch?v=5Vspx8sHaAs&t=23))

~~Here's a half-baked prototype...~~ Ideally, the inertia and the "force-back effect" would need to depend on the camera acceleration/speed (calculated with a timer ?). I'm not sure how to handle that, but let's throw ideas.

**EDIT (2017-06-25): diff removed.**

**Comment by paramat** [comment]
Please not inertia, that's unnecessary realism and needs complex code to create it. This is not a realistic / photo-realstic game it's abstract.
#5175 is fine by me though as it's simple and not excessively fancy and realistic.

**Comment by tobyplowy** [comment]
@kilbith welcome back :) 

This looks interesting

**Comment by kilbith** [comment]
WIP: https://www.youtube.com/watch?v=ls9vxBTr0hg

**Comment by paramat** [comment]
Sorry, i think arm inertia looks weird and not good :-1:

**Comment by nerzhul** [comment]
I really like this, gg @kilbith , just add an option for conservatives like paramat but default it to true (enabled)

**Comment by paramat** [comment]
> a more natural movement feeling,

It's actually unrealistic, when holding a tool or weapon you use your strength to turn your arm with your body, a lag implies weak muscles and a limp arm, that's why it looks weird.

> pretty much all modern FPS games

MT is not a photo-realistic FPS, it's simple and abstract.

By the way, in the UK 'conservative' is an insult for a politically left wing person :]

**Comment by red-001** [comment]
I don't really like how the old version looked but it seems a lot of people do like it so I see no reason why it shouldn't be merged.

**Comment by SmallJoker** [comment]
#6050 merged
