### ISSUE TITLE
Player in lava dies multiple times

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#5183]
When a player dies in lava or another node that have a damage per second, if they don't respawn immediately they will be reported as dying multiple times as long as they don't have pressed the respawn button. Moreover, the respawn screen will be shown again once *after* the player has respawned and is out of the damaging node.
Steps to reproduce: place a lava or other node that damages the player per-second, enter it, and don't press the respawn button immediately after dying.
Probable cause: the player is reported as dying again if taking damage even if already dead.

**Comment by paramat** [comment]
Only happens in creative mode for me, and i don't get a respawn screen after respawn.

**Comment by Fixer-007** [comment]
related?
https://github.com/minetest/minetest/issues/3565
https://github.com/minetest/minetest/pull/4127

**Comment by Ekdohibs** [comment]
Yes, this is indeed a duplicate.
