### ISSUE TITLE
Remove smooth lighting from firelike for performance?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5188]
EDITED
The smooth lighting on all nodes PR is one of my all-time favourite PRs, it's stunningly good.

However i am not sure we should have smooth lighting for firelike, as this has faces that are disconnected from surrounding nodes so never had a visual problem when not smooth lighted.
Because the faces are not standard cube faces the smooth lighting is calculated through 3D interpolation of vertex positions, which is more intensive. Firelike has 6 faces and fire nodes can number thousands in a forest fire.
Firelike is usually used for fire, which is a bright light source so therefore has even less need for smooth lighting because it is always near full brightness. Smooth lighting is not really needed for a fire texture.

**Comment by MarkuBu** [comment]
Maybe you should post screenshots of both options. I don't know how plantlike nodes look with and without smooth lightning

**Comment by paramat** [comment]
Good idea, i expect the difference is very subtle.

**Comment by Fixer-007** [comment]
Stutter is not because of this... it is ancient problem. This is not needed, fps and its deviation is literally the same on my system. I will do extra comparisons again if you want.

**Comment by paramat** [comment]
Ok good, i hope you're right and i have added an edit to my post.
I don't feel strongly about this either way.
In the PR review it was suggested that certain nodes don't need smooth lighting.
My concern is that the drawtypes that need it the least, plantlike and firelike, are also the drawtypes needing the most lighting interpolation, plus these can be very high in number in a mesh, so i feel this is worth considering. Partly because we didn't consideer it before the merge.

**Comment by numberZero** [comment]
@paramat It seems reasonable to disable smooth lighting for several drawtypes like `plantlike`, `firelike`, etc. I think that should be an option, though; the difference may not always be subtle, and someone might even use `firelike` for something dark, who knows? That should not look like an engine bug. And for meshes, I suggest adding something like a vertex limit option so that only lightweight (pre-converted nodeboxes, for example) meshes get smooth shading.

But the main problem is that the current code is suboptimal. I know that, I know that I hadn’t optimized my code before making the PR. I even noticed increased lagginess as my PC is rather old. (Although IMO smoothness worth that =). But the current code needs refactoring, I’m working on that right now, see #5159. Generally, optimization before refactoring is a bad idea. (Note that I know already some things that I can optimize).

**Comment by paramat** [comment]
I edited my first post to only address firelike.
I can see that having smooth lighting for plantlike will help make it look more part of the world, so i won't worry about that now.
Certainly firelike could be used for a non-bright purpose, but that's unlikely as we have many plantlike options now.

**Comment by numberZero** [comment]
@paramat There is variety of optimization possibilities. I need to think on that.

> we have many plantlike options

So its code looks overcomplicated now :P

Actually I wonder how much the compiler may optimize it. Do not want to disassemble MT again, but what else can give the truth?

**Comment by Fixer-007** [comment]
Did pretty simple test in singleplayer
```
Singleplayer 0.4.15-dev (87e9466) with and without PR5098
Mapgen v7, freshly generated each time, same spot, same path,
straight fly for 3 min over huge jungle biome + some hills and water
Core i3-2120, hd6870, default config + fps_max = 0

without SL PR
-------------
2017-02-08 00:08:18 - minetest
Frames: 17602 - Time: 180000ms - Avg: 97.789 - Min: 26 - Max: 180
Frames: 17102 - Time: 180000ms - Avg: 95.011 - Min: 25 - Max: 171
Frames: 17352 - Time: 180000ms - Avg: 96.400 - Min: 29 - Max: 180
avg: 96.4 fps

with SL PR
----------
2017-02-08 00:20:40 - minetest
Frames: 17050 - Time: 180000ms - Avg: 94.722 - Min: 32 - Max: 166
Frames: 17198 - Time: 180000ms - Avg: 95.544 - Min: 33 - Max: 175
Frames: 17083 - Time: 180000ms - Avg: 94.906 - Min: 29 - Max: 160
avg: 95.1 fps (~1% drop)

Detailed test results (combined 3 runs for each)
------------------------------------------------
Parameter NO SL, ms   SL, ms    Diff
(frame times in ms, fps = 1000/frame time)

Avg           10,374    10,520   0,147
Std error     0,0258    0,0271  0,0013
Median         9,185     9,108  -0,077
Mode           9,712     8,837  -0,875
Std dev       5,8827    6,1403  0,2576
Dispersion   34,6057   37,7028  3,0971
Exsess       51,6797   48,0511 -3,6287
Assymetry     5,6351    5,3897 -0,2454
Interval     130,595   135,662   5,067
Min            5,122     4,887  -0,235
Max          135,717   140,549   4,832
Sum         539982,4  539983,0     0,6
Count          52053     51328    -725
```

As you can see fps is pretty much the same, standard deviation as measure of jitter (frame time variability) is slightly worse for minetest with smooth lighting PR (5.88 vs 6.14, about 4% diff).

**Comment by paramat** [comment]
Yes i'm now not concerned about smooth lighting PR having a significant effect on jitter. Thanks.

**Comment by paramat** [comment]
It seems stutter is probably unaffected by the smooth lighting.
The mesh generation performance issue still remains, my current feeling is to remove smooth lighting from firelike only. Firelike shows differing numbers of faces depending on surroundings so is unlikely to be used by modders for other purposes.

**Comment by paramat** [comment]
Closing, firelike may be used for purposes where smooth lighting is needed.
