### ISSUE TITLE
Android build failure (undefined references, other)

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#5190]
Android build from latest Git fails with 
```jni/../jni/src/script/scripting_game.cpp:96:` error: undefined reference to 'ModApiStorage::Initialize(lua_State*, int)'
jni/../jni/src/script/scripting_game.cpp:113: error: undefined reference to '`StorageRef::Register(lua_State*)'
collect2: error: ld returned 1 exit status
/home/home/android-ndk-r11c/build/core/build-binary.mk:665: recipe for target 'obj/local/armeabi-v7a/libminetest.so' failed
make[2]: *** [obj/local/armeabi-v7a/libminetest.so] Error 1```

**Comment by rubenwardy** [comment]
@nerzhul you forgot to add the files to the android config.

This happens pretty much everytime a new file is added, the dev forgets to add it to android. It needs to be added to the config file in build/android/jni/
