### ISSUE TITLE
Improve `minimal`

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#5192]
`minimal` is a nice thing when you want to test does it work at all. But to be more useful, it should contain examples of all available drawtypes with different options (e.g. new kinds of plantlike, glass with content, etc.), some with several variants (to test `connect_to_raillike`, for example). Also it should probably have normal creative inventory.

**Comment by C1ffisme** [comment]
@numberZero While it's incredibly low priority, it might be nice to update those textures...

**Comment by Wuzzy2** [comment]
Usage examples of drawtypes would be incredibly useful. Sadly, the drawtypes are extremely poorly documented at the moment, so I think `lua_api.txt` needs to be updated as well.

**Comment by paramat** [comment]
Issue is no core dev can be bothered to work on it as we have far higher priorities.

**Comment by rubenwardy** [comment]
I recently went though and [documented all the draw types in my modding book](https://rubenwardy.com/minetest_modding_book/en/chapters/node_drawtypes.html). I welcome any attempt to use this to make lua_api.txt, however it would need slightly different content however, as `lua_api.txt` is a reference and so should be more factual.

**Comment by Wuzzy2** [comment]
The minimal subgame also seems pretty broken anyway. You can't even use formspecs; every button press is ignored.

I find it hard that this broken subgame is useful to anyone. Why is this subgame even kept around?

**Comment by Wuzzy2** [comment]
@rubenwardy: It would be much more helpful to everyone if you spend your developer time on improving `lua_api.txt` instead of your unofficial Lua API documentation.
IMO the unofficial docs should be based on `lua_api.txt`, not vice-versa.

**Comment by rubenwardy** [comment]
I disagree. Lua_api is a reference, and because of that is very unfriendly to beginners. I am not writing documentation, I'm writing a guide/tutorial/book. There's a difference.

**Comment by paramat** [comment]
I think this is too vague, to be realistic devs are not motivated to work on minimal unless a specific problem arises, such as me having to add river water. So let's deal with specific issues as they arise.

**Comment by numberZero** [comment]
@paramat Minimal is needed to test the core, thus it should be helpful
for that. That is, should contain nodes of each and every drawtype, with
various settings, `param2` types, etc. And some nodes with oriented
textures (remember upside-down letters? reversed `glasslike`? These
would never be in `master`, would `minimal` has appropriate nodes).

Note that I have several example nodes, so may make a few PRs next week.

**Comment by rubenwardy** [comment]
Sure, PRs will be welcomed. I suggest keeping the number textures small however, to aid loading times. It should still load faster than MTG

**Comment by paramat** [comment]
Yes PRs are welcome, i agree it would be more useful if it had an example of each drawtype and dedicated tests like letters on textures etc..
I just had the impression devs didn't use it much and didn't need it to be improved, but of course, if intelligently designed as you suggest it would become much more useful and used.
I think i may have been wrong in closing this.

**Comment by nerzhul** [comment]
i agree, minimal is useful to debug and test code, it's like integration tests, i use it everytime i add a new core engine feature

**Comment by Wuzzy2** [comment]
If you want to improve minimal, start by fixing the broken formspecs first. This single bug makes it pretty useless for testing mods.

**Comment by C1ffisme** [comment]
You could try and fix minimal by replacing it with an extremely stripped-down Minetest Game. (Meaning no TNT, no newer ores, no newer biomes, etc.)

It wouldn't be that hard to do in about a day's work, and it would solve the problem of formspec breakage and outdated code without having to search for the old code and replacing it.

**Comment by numberZero** [comment]
> useless for testing mods

It’s not for testing mods, it’s for testing the core.

> we have far higher priorities

And we have tons of bugs that could be spotted early, would the minimal be better. #6536 is yet another example.

**Comment by paramat** [comment]
Yeah, to clarify i have no objection to this, sorry for my earlier opinion and the close.
To be truly useful this will be quite a lot of work, and will need to be kept up to date with new features. I don't have time myself to maintain a rewritten minimal, hopefully someone else does.

**Comment by paramat** [comment]
Folded #6618 into this.

**Comment by Wuzzy2** [comment]
So … what exactly are the goals of the minimal subgame, anyway?
Current minimal subgame just looks like a random collection of random stuff.

Is it supposed to be an example? Is this just your personal core dev playground? Is it a testbed for mods? Or a testbed for engine features?

TBH I find the current minimal subgame to be incredibly useless since a lot of engine features are unused. It's also very messy. Does any developer even actually *use* the minimal subgame for development?

I think MDT could be useful to build simple test cases for all the core features. E.g. for node drawtypes.
And if one feature breaks, all you have to do is to fire up MDT and look up the feature that is supposedly broken.

Note sure what your priorities are.

**Comment by paramat** [comment]
Done.
