### ISSUE TITLE
per client code, anti grief method, and maybe more.

### ISSUE THREAD

**Issue by pandaro** [minetest/minetest#5194]
- engine side work
1 on compile minetest generate a unique code for your machine: **client code** ;
2 this code is available ingame ( maybe only for admin or maybe not) minetest.get_client_code(player);
server side: possibility
- 1 a player that grief -> ban -> change name  can be  **code ban**
2 player that want change name without lose items and object can set up a mod that do this base on his code;
3 skills of a player can be shared over a server's network;
- minetest community;
1 the behaviur of a player can be discussed global and without reference;
2  global ban if there are reason  ;

**Comment by red-001** [comment]
The moment you add something like this someone will just release a version of minetest in which the code can be changed by the player. If anything minetest should add a way to ban a player by username instead of just by ip.

**Comment by sofar** [comment]
Too easily defeated.
