### ISSUE TITLE
Do not set irrevocable privilieges to server owner

### ISSUE THREAD

**Issue by bell07** [minetest/minetest#5197]
This bug report is a follow up to [#4413 Reduce list of default singleplayer privileges](https://github.com/minetest/minetest/issues/4413)
The same should be valid in multiplayer for "server owner" (user who started the game / name= in minetest.conf).
In abstract there is no difference between singleplayer and the multiplayer server owner. The difference is only if the owner expecting "guests" or not. So my proposal is to use the "give_to_singleplayer" attribute  for multiplayer-server-owner instead of just grant all privileges.

**Comment by red-001** [comment]
:-1 The server owner should be able to use all privileges and chat commands, maybe add a way to revoke fly, noclip and give but it the same list as for singleplayer shouldn't be used.

**Comment by bell07** [comment]
If you start the game from Main-Menu / Server tab, the given account is automatically the server owner / admin. That results in the server owner is not able to have the full game experience, because some mods does different behaviour based on permissions (ie. unified_inventory, like in #4411). So the survival game experience is "for guests only" :(.
I do not like to start prior a dedicated server from command line, then go to UI and connect to localhost to get less permissions. Maybe an additional option "logon as admin" should be in UI to handle this behaviour, selected by default?
My proposal to unify singleplayer and server owner is based on the idea to be able to switch game-mode in feature. The "singleplayer" should be just an option in the UI and means the server will not be open in LAN. So the singleplayer can have an own logon-name and be able to "open in LAN" from inside the game.
outward from this idea the singleplayer and the server owner is the same for me.

**Comment by rubenwardy** [comment]
It would be better to make it possible to start a server from the mainmenu and not be the admin player

**Comment by bell07** [comment]
*Push*

An other idea how to solve it: Maybe a new minetest.conf setting "admin_forced_privs" instead of a hardcoded list for the forced irrevocable privileges? Of course the list is set by default to the current hardcoded list values

If my need is "not really needed" because I am not in mainstream, please let me know the place I can manipulate the hardcoded list quick-and-dirty. I am on gentoo so applying patches is not an issue.

**Comment by rubenwardy** [comment]
done
