### ISSUE TITLE
Add additional biome implementations

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5201]
~~Most maps are annoying. Sometimes you walk through a a giant snow biome followed by a giant icesheet followed by another giant snowy grassland. In survival mode with hunger you are dead before you find food.
Same map, different place... See a snowy grassland from a desert.~~
EDIT by paramat: Game issues.

I think, a cell noise would be better, or polygonal map generation

http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/

**Comment by ExeterDad** [comment]
Wow! A very interesting read.

**Comment by tobyplowy** [comment]
> Sometimes you walk through a a giant snow biome followed by a giant icesheet followed by another giant snowy grassland

I've Been There and I hate it! +1

**Comment by paramat** [comment]
Many would say that a jigsaw of equally-sized biomes (like MC) is boring and childish, i think so too. If you are playing a hard survival game then the server owner should try a few different seeds to make sure spawn isn't too distant from resources.
The danger of giant barren biomes is what makes MT more interesting and adventurous than MC.

Hmmmm was keen on a MC-like biome distribution, we have the ability to have multiple biome managers so an alternative system can be made if anyone wants to.
See https://github.com/minetest/minetest/blob/master/src/mg_biome.h#L129 the current system is 'BiomeGenOriginal'.

**Comment by MarkuBu** [comment]
Biomes shouldn't be equal in size, but limited. They should have a minimum and maximum size. 

A player can walk 4 n/s, so he needs ~1min to pass 250 nodes, ~4min for 1000 nodes and 10min for 2400 nodes, which means a half in-game day. I think, biomes shouldn't be bigger than 1000 nodes, especially cold biomes, because if you walk from one cold biome to another you are screwed.

I'm not so much a server player. I want to play single survival, but I don't want to start a map 3 or 4 times just to find a spawn point with a chance to survive

**Comment by paramat** [comment]
The heat and humidity noise 'spreads' are set to 1000 nodes so it's rare to find biomes larger than that. Of course, biome size cannot have limits due to the nature of noise.

**Comment by raymoo** [comment]
If I remember there was some issue/pr about implementing support for mapgens that operate by adding detail recursively

**Comment by MarkuBu** [comment]
Well, we can put something to survive into cold barren biomes, e.g. igloos or nomade tents with loot chests

No vegetable food, but fish, seal meat or wale oil (for lamps). Also some dead trees to get some wood, a fishing rod for fishing (without mobs), a camp fire for cooking (not for smelting)

**Comment by paramat** [comment]
Yes there is a recursive mapgen prototype, but this will likely generate terrain only, the biome system is independent and applied to the terrain each mapgen creates.

**Comment by raymoo** [comment]
Oh, I see.

**Comment by purveyor-of-points** [comment]
Sounds to me like the problem lies more in the gameplay (or lack thereof) for mods that use hunger mechanics.

That being said, it'd certainly be nice to have more types of biome generation. Maybe a replacement for heat/humidity, and instead a given "biome rules" list to make sure some biomes only spawn next to another? IE: no icecaps next to deserts.

**Comment by MarkuBu** [comment]
> Sounds to me like the problem lies more in the gameplay (or lack thereof) for mods that use hunger mechanics.

That depends. Voxel games have normally two game modes: creative and survival. And I think, survival doesn't makes sense just with fall damage, drowning and lava damage. Hunger is part of survival so it should be part of Mintest Game. But that's off topic

>  it'd certainly be nice to have more types of biome generation.

What kind of procedural algo can be used instead of perlin noise? I just know cell noise

**Comment by HybridDog** [comment]
What about that algorithm?
https://github.com/mxgmn/WaveFunctionCollapse

**Comment by MarkuBu** [comment]
Interesting algorithm. But how should that generate biome maps?

**Comment by HybridDog** [comment]
It could give every biome an unique shape
http://imgh.us/mm.svg

**Comment by Ekdohibs** [comment]
There was a discussion about this on IRC some looong time ago, if I remember correctly ([here](http://irc.minetest.ru/minetest/2013-08-29#i_3293190), the discussion started a bit before but loggingbot_ wasn't there). Also, Terasology has a map generator inspired by this, so it could be worth looking at it.

**Comment by MarkuBu** [comment]
@paramat just an idea: is it possible to get an information which noise finally generates the terrain per coordinate?

e.g.  
x = 0, z = 0 is generated by mgv7_np_terrain_base
x = 100, z = 200 is generated by mgv7_np_mountain
...

A byte would be enough
1 = mgv7_np_terrain_base
2 = mgv7_np_mountain
...

If the mapgen has a map with this information a decoration could be placed by biome AND terrain, at least somehow

**Comment by paramat** [comment]
Hmmmm / kwolekr was interested in terrain affecting biome selection.
In a mod you can use perlin noise to determine whether a point is base, higher or mountain terrain.
Interesting idea though to change biome on mountians.

**Comment by asanetargoss** [comment]
In my personal opinion, most biomes should be survivable, however there should also be a robust system to guarantee that players do not spawn in certain biomes. Being forced to spawn in a biome that is not survivable and then be forced to restart with a new seed is annoying and unacceptable.

On the other hand, if a player spawns in a nice starting biome and doesn't bother preparing enough food and supplies to explore a certain distance into a hostile biome with no known end, that's their problem. However, one may want to determine ahead of time the size and probability of biomes to, for example, make certain resources scarce, or require players to explore. It's not impossible to quantify probabilities and sizes of biomes with the current system, although the voronoi system certainly makes things harder. Meanwhile, rare but large biomes (eg. magical biomes), biome variants, and cave biomes simply aren't possible at the moment.

**Comment by MarkuBu** [comment]
Even well prepared huge snow or desert biomes are annoying. And I don't think we need "a robust system to guarantee that players do not spawn in certain biomes". It just should be possible to survive in all biomes

**Comment by HybridDog** [comment]
l have problems making a rare biome using perlin noise because the values are not distributed linearly, they are not sin, not cubic and now and then outside [-1;1]. You could use many perlins and test if (n above k) have values > 0 for each x×z, but that's way inefficient.
https://forum.minetest.net/viewtopic.php?f=11&t=3616

**Comment by MarkuBu** [comment]
> You could use many perlins and test

Well, this is really inefficient

It's true, we don't have any kind of control, but that is the smaller problem. I think, the bigger problem is, that we have not enough information about the map to generate more variations of biomes or it's laborious to get them our self in a Lua script

**Comment by paramat** [comment]
> It just should be possible to survive in all biomes

This is a subgame issue, in MTGame there is no hunger or danger so no problem.
You can write a mod that checks heat and humidity noises to choose a spawn point, but again that depends on what biomes have been defined so is a subgame issue.
The engine mapgen should not have to concern itself with survival issues.
You can reduce biome size easily by setting the heat and humidity noises in a mod.

**Comment by paramat** [comment]
So as stated this issue is invalid, and we don't need to replace perlin noise because we can have multiple biome systems. However if you want to re-word this issue to be a request for new alternative biome systems then it would be valid.

**Comment by MarkuBu** [comment]
Changed the title. You are right. Replacing perlin noise was a stupid idea, but adding a new way to generate biomes would be great

**Comment by MarkuBu** [comment]
> Interesting idea to change biome on mountians

I'm not sure how mg v7 works, but I think that there are some noises and "the strongest wins". What I mean is, that each noise generates a value and only the highest value wins.

In this case it should be easy to add something like a "terrain biome"

**Comment by paramat** [comment]
Author has left MT, we are always open to adding new biome generation mehtods, but someone has to code it or be interested. Many other points made by the thread author are subgame issues.
No point keeping this open.

**Comment by paramat** [comment]
This would be obviously welcome but an issue is somewhat pointless. It will happen if or when someone is inspired to add an alternative biome system, requests for it are somewhat irrelevant.
