### ISSUE TITLE
New dimensions

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#5203]
Basically like the Minecraft Nether and end ( I know This is possible with XYZ coordinates but I don't want it I want to have real New Dimensions (how I see this is a world save in a world save and if you do a serton Action you get teleported to theat world)

**Comment by sfan5** [comment]
duplicate of #4428

Additionally please refrain from making unproductive comments like
* +10000000
* I've Been There and I hate it! +1
* if this doesent get added I will be so disappointed
