### ISSUE TITLE
Add a slope map

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5207]
I always think about how procedural map generation could be made better and then a slope map came to my mind

A slope map could be generated by adding the highest and lowest neighbor. If one neighbor is 2 nodes higher, another one is 1 node lower and the two others are equal, the slope value for this node is 3.

An average slope value for a mapblock would be nice too

With such a map it could be possible to find places for special features or prevent placing on to steep slopes

**Comment by paramat** [comment]
The existing mapgen object maps are things actually created and used during mapgen, this would be something created but not needed by mapgen, so would have to be optional.

**Comment by MarkuBu** [comment]
It could be used when placing decorations. For example the redwood trees in ethereal have a big base and they can be placed at weird places. With a slope map the mapgen can check if there is a good place or not

**Comment by MarkuBu** [comment]
This wouldn't happen with the slope map I have in mind

![screenshot_20170213_204320](https://cloud.githubusercontent.com/assets/16163058/22900035/344ca180-f22d-11e6-8666-75ce384ac9f3.jpg)

**Comment by paramat** [comment]
That looks good, because you have tapered the roots it looks right growing off the side of a rock face.
The issue only affects very wide trees which are not often used, the redwoods in Ethereal should taper their roots as you have done here.
The request is interesting but quite specialised.

**Comment by MarkuBu** [comment]
I know that it is specialized. It is only useful for procedural content. Not only trees, but also buildings and any kind of larger structure.

And I think that I am the only one who works in this direction

**Comment by paramat** [comment]
Good point about building type structures.

**Comment by paramat** [comment]
I can't see how analysing a slope map would be any less intensive than analysing the heightmap, when deciding where to place a structure, you wuold still need to scan a large area of the map to find a suitable area.
Author has left MT, feature too specialised to add another mapgen object map to core mapgen.
