### ISSUE TITLE
Allow nodes to make light level drop by 2 or more

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5209]
Currently, nodes with `paramtype="light"` and `sunlight_propagates=false` (e.g. `default:leaves` or `default:water_source`) reduce the light level by 1 per node.

I suggest to add a new field to the node definition to increase this number, so that the light level can drop by 2 or even more.

Use cases:
- Thicker water
- Very dirty glass
- Recreating water behaviour from Minecraft ([MineClone 2 project](https://forum.minetest.net/viewtopic.php?f=50&t=16407)).

**Comment by juhdanad** [comment]
It's best to implement per face light transmission ratios. Then you can also do [that](http://imgur.com/a/cFaAn) (in MC this was reverted because of performance issues, however).

**Comment by Wuzzy2** [comment]
> It's best to implement per face light transmission ratios.

This is a completely different beast. Please stay on topic (and post a new issue if you have to). :P

**Comment by paramat** [comment]
:-1: low priority and likely disruptive for complex lighting code.

**Comment by paramat** [comment]
Duplicate of #6581 
Closing this one as the other has more discussion.
