### ISSUE TITLE
Add support for shift-click transfer of stacks

### ISSUE THREAD

**Issue by darthfodder** [minetest/minetest#521]
In Minecraft, you can shift-click any stack of items in one container and it automatically moves it to another. In a crafting box, this will craft as many of the item that the current materials placed in the 9x9 will make and place it in your inventory. This would be a nifty feature to add to Minetest. Please forgive me if there is already a way to do this in Minetest, I played around with the controls but couldn't find one

**Comment by MT-Modder** [comment]
This issue is more recent: #1311.
Maybe this one can be closed, especially with the new dev. rules?
