### ISSUE TITLE
Setting for liquid flow/update rate

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5210]
Currently, even the fastest liquid flow is still rather slow.
With `liquid_viscosity=0`, the water flows at about 1 node per second.

Minecraft water, in comparison, flows lightning-fast:

http://youtu.be/YItuPMEMMwA

I suggest to allow for a much faster liquid flowing with the Lua API. I'm not saying the water speed should be increased in Minetest Game, but allowing modders to have a faster liquid flowing speed would definitely lead to interesting gameplay mechanics in other subgames.

**Comment by Fixer-007** [comment]
I believe it is intentional to make less work for cpu..

**Comment by paramat** [comment]
I suspect 'liquid_viscosity = 1' is the maximum waterflow update rate, making waterflow update rate faster in the engine would increase the already intensive code.

**Comment by MarkuBu** [comment]
Hm, but it is a good question. Why is Minecraft water so much faster?  I would like to see faster water too

**Comment by dsohler** [comment]
> Why is Minecraft water so much faster?

Because it behaves like an actual fluid and not like some kind of sticky goo that does not interact with the world (ie. items flowing in the direction of the water).

**Comment by numberZero** [comment]
Note that water flow is directional in that video. I have never played MC so can’t say much more, though.
But the MT liquid flowing code looks awkward anyway(

**Comment by raymoo** [comment]
What if the liquid flow rate is throttled down to the fastest registered (or maybe loaded) liquid? Then it wouldn't slow down Minetest Game (except maybe some overhead at the beginning to find the max flow rate), but would allow mods to add faster liquids.

**Comment by numberZero** [comment]
@raymoo The current code is complicated, but as I understand it, it uses a sort of queue. See `map.cpp:1205  void Map::transformLiquids(std::map<v3s16, MapBlock*> &modified_blocks)` for details.

**Comment by red-001** [comment]
yeah it's a queue that creates a loop, by adding any node that is updated to itself.

**Comment by MarkuBu** [comment]
If I read this I get the idea of something like a general event if a node is removed.

All neighbours can have a on_neighbour_removed callback. Nodes like water can be triggered to run their flow functions and then there is no need for an all over loop

**Comment by paramat** [comment]
1+ year bump. Any core dev support?

**Comment by paramat** [comment]
```
#    Liquid update interval in seconds.
#    type: float
# liquid_update = 1.0
```
