### ISSUE TITLE
Sneak+click on crafting output slot for much faster crafting

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5211]
Sneak-clicking is a very useful and important GUI improvement in the past, but it doesn't work for crafting so far.
Currently, you still have to move the itemstack around, sneak-clicking does nothing. For tools, this is most annoying, there is no way to quickly craft, let's say, 30 screwdrivers, as you have to click and move the screwdriver around 30 times.

I suggest the following shortcuts when clicking on the crafting output: while holding down the sneak key:

- Sneak + left click: Craft the item as often as possible (from the input grid) and automatically put the new item stacks into the inventory (probably defined via listring or an implicit default), until either no more slots are free in the target inventory or the input items are used up.  If the crafting would result in multiple item stacks, slots in the target inventory are filled up until no space is left.
- Sneak + right click: Craft the item once and immediately move it to the target inventory
- Sneak + middle click: Craft the item ten times and immediately move it to the target inventory

If no slot is free to begin with, nothing is crafted.

Examples (Minetest Game):
* Input: 99 coal lumps + 99 sticks, empty target inventory: Shift+leftclick crafts 4 stacks of torches and puts them into the inventory
* Same input, shift + right click: Crafts 4 torches (result of a single craft, mind you!) and puts in into the player inventory
* Same input: shift + middle click: Crafts 40 torches, puts them into the player inventory
* Input: 60 steel ingots + 60 sticks, empty target inventory: Shift+leftclick crafts 32 screwdrivers and fills all slots of the target inventory (because of the inventory size limit)

Adding this feature would make crafting infinitely times faster and less annoying.

EDIT: I fixed a typo where I confused right with middle. xD

**Comment by Fixer-007** [comment]
>move the screwdriver around 30 times.

There's workaround for this, middle mouse button - transfers 10 items (main reason I broke my previous mouse...). I really like how MC did it, on videos it feels almost magic-fast and easy.

**Comment by Wuzzy2** [comment]
> There's workaround for this, middle mouse button - transfers 10 items (and main reason I broke my previous mouse wheel...).

I'm aware of this, but it doesn't work for screwdrivers because the maximum stack size is 1.

**Comment by XtremeHacker** [comment]
I would say this would help the game feel more consistent, anyone else want to comment?

**Comment by DS-Minetest** [comment]
> anyone else want to comment?

ok

> **@Wuzzy2 wrote:**
Same input: shift + **right click**: Crafts 40 torches, puts them into the player inventory

But I think, he wanted to write `middle click` instead of `right click`.
Anyway he doesn't like hard bound keys, so it's not that important. Probably he meant the standard key configuration.

**Comment by Wuzzy2** [comment]
Oops, I fixed that.

**Comment by Fixer-007** [comment]
We can also reuse some of very neat shortcut features from MC: https://www.youtube.com/watch?v=fF_KEAe988M

**Comment by rasusmilch** [comment]
Just opened a bug in the Mineclone2 tracker regarding this issue. Referred here.

I agree that it is very tedious at the moment to make things while having to shuffle around and balance input items. Some kind of shift-click to create the maximum number of output items given the inputs would be greatly appreciated.

For example, crafting smooth granite in MineClone2 requires 4 blocks of granite which gives 4 output blocks of smooth granite. If I place 3 single blocks plus a stack of 61 blocks in the last slot, shift-clicking should give me a stack of 64 smooth granite blocks. Currently, I have to click 64 times, sometimes stopping to rebalance an input slot that has run out.

**Comment by Wuzzy2** [comment]
@rasusmilch: Well, at least you can use the middle mouse button to craft 10 times at once. Of course this is still no excuse for not improving it.

**Comment by rasusmilch** [comment]
@Wuzzy2 Yes, that will help with speeding it up (my wheel already acts up...) but won't solve the constant rebalancing of input items. I'll take what I can get though and hope it gets fixed/upgraded at some point.

**Comment by jastevenson303** [comment]
Personally I split stacks with right click and then middle click the output.

**Comment by rasusmilch** [comment]
@jastevenson303  Yes, I recently discovered the middle wheel button (I hate middle wheels as I'm always accidentally rolling it so avoid it like the plague.)

However, let's say I have four (4) 64 high stacks of redstone powder I need to arrange in all 9 grid locations to make one (1) redstone block. How do I do that via right-clicks? Half-cuts only go so far unless you start single placing each input item, you will run out of one item and have to redistribute.

Watch some MineCraft videos on YouTube and see that speed they can make items, it's amazing. Draw the shape, throw the rest of the items anywhere (eg, one item in the locations with a giant stack somewhere in the crafting area) and a shift-click gives 33 whatever.

(Yeah, it's a convenience thing.)

**Comment by paramat** [comment]
1+ year bump. Any core dev support?
