### ISSUE TITLE
Tool “charging” (bow and arrows, grenades)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5212]
My suggestion is to allow to “charge” tools and weapons by holding down the attack key, increasing some kind of “power” as long as the button is pressed, then using the tool action after the attack key has been released.

Obvious use cases would be:

* Bow and arrows, the longer you hold down the button, the stronger you pull and the further the arrow goes (up to a maximum strength)
* Grenade: The longer you hold down the mouse, the further you throw it (up to a maximum strength)

Maybe the callback function could simply just tell the modder for how many seconds the button was pressed until its released, so the mod can interpret this number accordingly.

Also, a “chargable” tool must be explicitly marked by the modder as such. By default, tools should be “single-shot” use like currently, so all the existing tools and weapons work like expected.

For tools of this kind, it might also make sense to have a different wield image animation. Either with different frames (bow and arrows), of the player pulling back the item (grenade). Maybe you have more ideas on the wield animation.

**Comment by C1ffisme** [comment]
@Wuzzy2 It is possible to _kinda_ get this effect using `minetest.after()`. [Example](https://gist.github.com/C1ffisme/3a466d3191bf61ce0fe744d570351035). But that should not stop anyone willing to support holding-down mouse buttons.

**Comment by purveyor-of-points** [comment]
On a technical level, I'd imagine you only really need a way for Minetest to recognize 2 or 3 things:

1: A key being held vs a key being pressed
2: The length a key is held for

and possibly 3, when a key is released.

Everything else would kinda fall into place.

**Comment by raymoo** [comment]
This *could* be done currently (except animation) by checking the player's mouse inputs in a globalstep when they click their tool, but it would have a misleading use animation.

**Comment by MarkuBu** [comment]
Custom animations are discussed as well for eating food.

Maybe it's time to add this feature.

And doing everything in globalstep isn't also the answer.

**Comment by DS-Minetest** [comment]
(~~Animations could be done by attaching entities.~~ ←If player could see entities that are attached to himself.)

**Comment by numberZero** [comment]
> checking the player's mouse inputs in a globalstep 

Have you ever played on a laggy server?
IMO that should be done using the CSM. Not sure does it support all the necessary features, though. Actually, only 2 things are needed: 1. “key down” and “key up” events/hooks (including mouse buttons), and 2. possibility of affecting the player model somehow.

**Comment by Ferk** [comment]
Imho, this makes sense for basically every weapon, including swords. Since you do minimal damage when spamming punches, having a delay or a "charge" time encourages delivering the punches more strategically.
It would also help prevent misclicks for food items if it took some time for the food to be consumed, instead of being instantaneous. Additionally, that way you would be forced to take a break from a fight to heal your wounds, instead of becoming unbeatable as long as you have food left that insta-heals you.

Related (adding delay): #4319
Regarding wielding animation: #4297

**Comment by Wuzzy2** [comment]
The current behaviour with simple one-click punches should still be possible. My proposed tool charging should NOT automatically replace existing behaviour of tools.
The point is to give modders freedom to choose between the “simple” tools and “chargable” tools.

**Comment by Ferk** [comment]
Sure, I just meant that this makes sense for melee weapons as well, not that it should be the default behavior of every item, nor that every tool should behave like that.
Auto-trigger is good for digging, for example. Or for things like an automatic firearm.

**Comment by raymoo** [comment]
@numberZero There was a recent change (disclosure: by me) that caused a player's input map to be sent along with interact events. This means a player's input map will be up to date after the player clicks (assuming an out of order control packet from before the click doesn't arrive after, fixing this would require assigning a sequence number shared between control and interact packets).

Not sure if I agree that it should be done solely on the CSM. It would allow cheating by rapid spamming full-force bow shots, for example. The way I would do it is have the client mod send to the server a "pull start" event when the player starts holding, and a "pull finish" when it ends, as that would allow the server to verify that the player had been doing the input long enough.

**Comment by sofar** [comment]
You could use the `use` key (`aux1`) in the player control to initiate a use event, and use the release of the key to fire.

**Comment by raymoo** [comment]
If I would do it in the current system, I'd use an interact callback to initiate it, adding the player to a list of players to check mouse control inputs for. Then I would check the player's inputs until they release the mouse button and fire. If I also checked control to initiate firing, I would have to check the player's wielded item (and if I used aux it would also clash with other controls, while mouse click can only conflict with the item's use callbacks).

**Comment by numberZero** [comment]
@raymoo Reasonable. The server should be able to prevent most cheating.
> rapid spamming full-force bow shots

Mod could check for an interval between events.

> "pull start" event when the player starts holding, and a "pull finish" when it ends

But it should probably send the actual pull length, or simply send a timestamp in each event, for better precision. Network lag is a great problem, though, as it may be very unstable, and it is impossible to tell whether the player cheats or some intermediate server delays some packets more than others.

**Comment by raymoo** [comment]
@numberZero Alright, that's fair, though I would still err on the side of less tolerance and use the minimum of the reported pull length and the pull length measured from messages received on the server. Lag can be unstable, but generally jitter is not really that severe, so I don't think the quality degradation will be significant.

**Comment by paramat** [comment]
1+ year bump. Any core dev support?

**Comment by LoneWolfHT** [comment]
We need something like this
