### ISSUE TITLE
Improve find_node_near() with centre check

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#5213]
Could we please improve the **find_node_near()** command by having it check centre position by use of a flag e.g.  **find_node_near(pos, radius, nodes, check_centre_bool)** and if bool is true start from 0 position instead of 1 inside code: https://github.com/minetest/minetest/blob/f2f9a923515386d787a245fac52f78e815b3a839/src/script/lua_api/l_env.cpp#L590

**Comment by paramat** [comment]
`FacePositionCache::getFacePositions(d)` supports d = 0 so this is a trivial change.
Note the bool variable name doesn't need include 'bool', it can be 'search_centre' with default false.

**Comment by sofar** [comment]
Can you please link back to the pull request that was rejected?

**Comment by paramat** [comment]
There is an issue for this somewhere.

**Comment by sofar** [comment]
#4819

**Comment by sorcerykid** [comment]
https://github.com/minetest/minetest/issues/5017

Altho, I agree a boolean argument is a more cleaner solution, to avoid unnecessary duplication.

**Comment by paramat** [comment]
Usually 'find node near' is used when we already know what the centre node is, but i think i can see some use for this. It would certainly be much faster than using 'get node' for the centre first, as 'get node' is a single map access whereas 'find node near' accesses the map in bulk.

**Comment by tenplus1** [comment]
@sorcerykid - exactly, the bool saves adding a new command and enhances the current with a centre check...  This issue stands on it's own and shouldn't be linked with the others.

**Comment by sofar** [comment]
@tenplus1 the related discussions are relevant no matter what, since arguments for and against should be weighed in context, and not omitted. It's also useless to repeat entire discussions, so, you should always link back to relevant discussions.

**Comment by tenplus1** [comment]
@sofar - True, but the previous discussions were regarding the addition of a new command entirely, whereas this one is amending the current by adding a new flag at the end.

**Comment by paramat** [comment]
The other issue is still very closely related, same feature, different implementation.

**Comment by sorcerykid** [comment]
I fully concur with sofar and paramat. Similar issues should be linked for purposes of reference. That is why this section is called an "issue tracker" after all :P

**Comment by tenplus1** [comment]
So who is gonna code this change ?

**Comment by sorcerykid** [comment]
I'd be glad to do this change myself, but I'm afraid I have no experience with PRs, so I'll trust someone with more knowledge of GitHub.

**Comment by tenplus1** [comment]
@sorcerykid - if you paste the code change I'll make the pull.
