### ISSUE TITLE
LBM is only executed with run_at_every_load = true

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5214]
As the title says, my LBM only runs if I set run_at_every_load = true, but then the LBM runs always. If I set run_at_every_load = false the LBM doesn't run at all.

I tried it with a new map and print the node name to the console, but nothing happens

**Comment by sofar** [comment]
The LBM runs only when it encounters map nodes that are old but haven't had the LBM run on them.

When new mapblocks are generated, the LBM code sees the mapblocks are newer than the LBM introduction time, and doesn't run the LBM handler.

This is by design, and not a bug.

You can not depend on LBM code to modify the map once after mapgen. For this you must use minetest.register_on_generated()

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2044

**Comment by MarkuBu** [comment]
I don't want to modify the map, I want to start some node timer

**Comment by sofar** [comment]
When do you want that nodetimer to start?

**Comment by sofar** [comment]
FWIW a nodetimer start is a map modification. Maybe not a client side map, but certainly it modifies the server version of the map (nodetimers are stored in map blocks in map.sqlite)

**Comment by MarkuBu** [comment]
Immediately after the map is generated. But it is enough to trigger a node once because the node timer can restart himself.

That was my idea. Could be used to replace some ABMs for example

**Comment by sofar** [comment]
Then use `minetest.register_on_generated()` to scan the map and perform modifications.

**Comment by MarkuBu** [comment]
Ok, thanks. I just thought, a LBM is faster. In minetest.register_on_generated() I have to search through the chunk in Lua.

**Comment by MT-Modder** [comment]
Try adding this to the nodedef:
```
on_construct = function(pos)
    minetest.get_node_timer(pos):start(TIMEOUT)
end,
```
This should start the timer when the node is placed or generated. I could be wrong though.

**Comment by MarkuBu** [comment]
No, AFAIK on_construct is not called from the mapgen

**Comment by MT-Modder** [comment]
It does, I know because I have a treasure chest mod that generates with the map and uses on_construct.

Although it could depend on how it generated... Decorations, ores, and biome nodes probably don't throw this callback but anything generated (set_node) with minetest.register_on_generated() definitely will.

**Comment by MarkuBu** [comment]
set_node will call on_construct, that is right. But I talk about the default map generation.

**Comment by HybridDog** [comment]
MT-Modder, nowadays performant mods use vmanip, which ignores on_construct und konsorten

**Comment by MT-Modder** [comment]
What you could do is add on_construct to the nodedef then run an lmb to set the node again. Effectively calling it.

@HybridDog True but if you're like me and too lazy to learn something so complex (over exaggeration) for something really simple.

**Comment by MT-Modder** [comment]
@sofar Maybe LBM functionality should be expanded with a ```run_at_first_load``` field or something. I personally think using minetest.register_on_generate() is over complex for such a simple task.

**Comment by MarkuBu** [comment]
I remember, LBM was designed to replace nodes on an existing map, e.g. replacing 2d nodes with 3d nodes. That's the original purpose

But to be honest, it would be nice if the LBM could be used for something like the node timer

**Comment by sofar** [comment]
So to explain why the LBM doesn't run, you have to understand how it works:

the LBM code uses a timestamp marker to determine whether mapblocks need to have the LBM code run or not. When the LBM is first encountered, minetest records the timestamp and compares each block encountered against that timestamp.

If a block was last loaded before the lbm timestamp, the lbm is run

if a block is generated, the timestamp is (obviously) after the LBM timestamp, and the LBM code is not run.

**Comment by sofar** [comment]
duplicate of #4050, essentially. we can continue the discussion there.
