### ISSUE TITLE
add neighbours for LBMs

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5216]
ABMs have the option to search for neighbours, LBMs don't have the option.

I know that the original purpose was to search for e.g. 2d torches to convert them to 3d or something similar, but LBMs can be used for more. But without the neighbours this check has to be done in lua

I propose to add optional neighbours to LBMs

**Comment by sofar** [comment]
The cost of lbm's is cheap enough that this isn't needed, and I think it's a complication that doesn't make any sense.

Can you give me an *exact* use case where the current LBM code can't handle what you want with this?

**Comment by MarkuBu** [comment]
Well, I want to do with the LBM something similar I did with ABM. But the LBM should run on each block once and start a node timer.

But I expected that the LBM runs once on each mapblock if run_at_every_load is false. So I can't use it for my idea. 

But maybe neighbours and even a chance might be useful if run_at_every_load is true, if you want to run an action on common nodes like leaves or dirt or something, to reduce unnecessary Lua calls

**Comment by paramat** [comment]
Author has left MT and the use case would not be possible anyway. No other support.
