### ISSUE TITLE
Change save folder to ~/.local/share/minetest on *NIX platforms (XDG related)

### ISSUE THREAD

**Issue by Lawful-Lazy** [minetest/minetest#5217]
Instead of having many files laid about the home directory, GNOME decided to create the folder `$HOME/.local/share` to move everything to. This helps ease backups of application data, while also cleaning the HOME directory while viewing hidden folders. GNOME also decided that this could be overridden by the variable `$XDG_DATA_HOME`.

This is how it would be implemented:

1. Use `$XDG_DATA_HOME` if available, else use `~/.local/share`.
2. If `minetest` is not in the data folder, look to see if `~/.minetest` exists (for old versions of minetest)
    1. If it exists, move `~/.minetest` to `path/to/data/minetest`.
    2. If it doesn't create the directory `minetest` in `path/to/data/minetest`.
3. Use the data directory as normal.

Thanks!

**Comment by dsohler** [comment]
Or support XDG in general. (Put configuration in `$XDG_CONFIG_HOME`, install manually compiled binary to `$XDG_RUNTIME_DIR`, etc.)

**Comment by Lawful-Lazy** [comment]
While separating `minetest` into `${XDG_CONFIG_HOME}/minetest` and `${XDG_DATA_HOME}/.minetest` would be ideal, I believe it would be best kept if both configs and data are on the same directory. That way, it's easier to maintain between *nix and Windows (as Windows generally has all data for an app in one directory).

**Comment by dsohler** [comment]
> as Windows generally has all data for an app in one directory

Because of the same laziness :smile: Windows actually has a good separation of user data. It was thoroughly discussed in #4931

**Comment by Lawful-Lazy** [comment]
> Windows actually has a good separation of user data.

Agreed. `C:\Program Files` for Linux's `/usr/games` and `/usr/share/games`, and `%APPDATA%` for Linux's `${XDG_DATA_HOME}`.

Also, I made a correction.

**Comment by Zeno-** [comment]
> The log file (debug.txt) should go to /var/log, but I guess proper locations for files are another issue.

I disagree. Why should they go there?

> Instead of having many files laid about the home directory, GNOME decided to create the folder $HOME/.local/share to move everything to.

How many servers have gnome installed? I'd think about zero. Even for desktop users, what if they don't use gnome? They are left with having to set up extra environment variables so that the gnomes can be catered for?

**Comment by dsohler** [comment]
> Why should they go there?

Because that's where log files are located on a standards compliant Linux based operating system.

> Even for desktop users, what if they don't use gnome?

XDG is desktop environment independent. `${XDG_DATA_HOME}` defaults to `${HOME}/.local/share`, that's all. GNOME simply uses XDG variables.

**Comment by Zeno-** [comment]
> XDG is desktop environment independent. ${XDG_DATA_HOME} defaults to ${HOME}/.local/share, that's all. GNOME simply uses XDG variables.

Where would the fallback location be if XDG_DATA_HOME is not set though? My Fedora install doesn't have it set (and no default) and neither does my Arch install (???)

**Comment by Ferk** [comment]
It defaults to ``${HOME}/.local/share`` when the variable is not set, as dsohler was saying. Most systems (even Gnome-based ones) don't have a ``$XDG_DATA_HOME`` defined either, the only reason there's a variable is just to offer a way for people to be able to set a different folder instead of having it hardcoded.

**Comment by dsohler** [comment]
> Where would the fallback location be if XDG_DATA_HOME is not set though?

Actually it depends on what the author of the software decided. Consensus is using `${HOME}/.local/share`.

> both of these installs don't have X installed, could that be the reason?

No. It depends on whether [XDG is installed](https://wiki.archlinux.org/index.php/XDG_user_directories) or not (or by [manually setting the XDG variables](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html#variables) in your bash profile).

**Comment by Ferk** [comment]
> Actually it depends on what the author of the software decided

 According to [the specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics) the defaults should be the specific ones defined. If an app doesn't use the default paths as indicated, then it's not in conformance with the spec.

> No. It depends on whether XDG is installed or not (or by manually setting the XDG variables in your bash profile).

Note that you don't even need that. I'm using XDG_CONFIG_HOME folder for the git configuration even on cygwin, without XDG commands installed and with no XDG variables defined.

**Comment by dsohler** [comment]
> because git supports the XDG paths.

At some point the application needs to know where to save the files. So you either have to configure the variables or rely on the applications to use default parts as defined in the XDG standard if the XDG variables are not set.

Installing the XDG stuff and configuring the variables usually is the first thing I do after installing a system. But it's going to be more and more OT here :smile: 

Minetest needs to support `$XDG_DATA_HOME` (or defaulting to `~/.local/share` if unset).

**Comment by Zeno-** [comment]
> Actually it depends on what the author of the software decided. Consensus is using ${HOME}/.local/share.

So, we'd be okay leaving everything as-is except if XDG_CONFIG_HOME is set. If that's what's being suggested then I'm fine with it. What I have a /minor/ concern about is changing things that might affect existing minetestserver installations.

**Comment by dsohler** [comment]
Of course it will affect existing MT installations.

Since `~/.local/share` is valid for XDG conformity and MT devs chose not to conform to XDG using `~/.minetest` is absolutely fine (even if it's absolute home clutter but that's a general issue and not MT related). Support for XDG variables would be awesome, of course.

**Comment by Zeno-** [comment]
Well, yes. I mean it's just a few mv's or even ln if you're so inclined. But I do like to keep disruption to a minimum. But I don't have much, if any, problem with this proposal.

**Comment by NatTuck** [comment]
Creating a ~/.minetest directory by default is really bad practice - same sort of thing as using C:\Minetest as your default install directory.

Much better would be to first *check for* a ~/.minetest directory, and to default to XDG behavior if no such directory exists.

**Comment by MuhdNurHidayat** [comment]
from what I read, the original issue was about moving all minetest stuffs from `~/.minetest` to `${XDG_DATA_HOME}/.minetest` (which by default is `~/.local/share/.minetest`) or something similar?

The issue to separate the data was introduced in the discussion, not in the original issue.

The original issue writer also wrote
> While separating `minetest` into `${XDG_CONFIG_HOME}/minetest` and `${XDG_DATA_HOME}/.minetest` would be ideal, **I believe it would be best kept if both configs and data are on the same directory.**

**Comment by ClobberXD** [comment]
I agree with @pauloue here. Why was the non-user data moved to `/usr/share/minetest` anyway? If there's going to be a `~/.minetest` for user-data, the non-user data could be there too. I'm not comfortable with having to go to different places to access different parts of MT like logs, mods, core, etc. and that's precisely why I prefer to use `RUN_IN_PLACE` builds.

**Comment by paramat** [comment]
1+ year bump. Any core dev support?

**Comment by eli-schwartz** [comment]
Repeating my comment from https://github.com/minetest/minetest/issues/8151#issuecomment-460102567 (which is closed as a duplicate):

Failure to follow the XDG Base Directory specification **or its OS-specific adaptations** results in software which is just as broken on macOS **and** Windows as it is on Linux.

On macOS, `XDG_CONFIG_HOME` maps to `~/Library/Preferences/`, `XDG_DATA_HOME` maps to `~/Library/Application Support/`, and `XDG_CACHE_HOME` maps to `~/Library/Caches/`.

On Windows, `XDG_CONFIG_HOME` and `XDG_DATA_HOME` are not separated, as both are in `%APPDATA%`, but `XDG_CACHE_HOME` must be in `%LOCALAPPDATA%` to prevent roaming across network shares (it does not specify when you can clean it up though).

Linux of course provides separate directories for all three (just like macOS), and goes even further by allowing them to be relocated via environment variables. But I hardly see why the lack of cross-platform support for overriding `XDG_*` should cast doubt on the usefulness of a program intelligently deciding where to put files according to the well-documented, preferred OS-specific locations.

**Comment by Baerbeisser** [comment]
Well, it's six years later now, any reconsideration? Most tools support XDG now, if the variables are set (some only half-heartedly, put stuff in dotfile if they are not set).

Minetest isn't really a tool, more a game. And there's the issue: i have my games on a separate partition, for easy backup. Which is the intent of XDG, btw.

Alternatively, a shell parameter to move configs and save and mods somewhere else than $HOME/.minetest? I see none obvious, neither with googling. Yeah, overriding HOME works, but that's hack, not a solution.
