### ISSUE TITLE
get nodes in an euclidean metric and entities in an area

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#5220]
~~There's the `find_node_near` command ([in lua_api.txt](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2233)) which returns one pos of a node of the name or group is inside the radius.~~
It would be useful to have something like a `get_nodes_near` command which returns a list of positions of the nodes.
(Also entities can't be gotten in an area.)
I know, this could all be easily done in the mod with lua but that wouldn't be that efficient, I think.
I really hope I didn't write too much crap again.

**Comment by tenplus1** [comment]
we already have the find_nodes_in_area command for nodes with a list of positions.

**Comment by DS-Minetest** [comment]
Yes, but this doesn't use an euclidean metric.
You can easily get nodes inside an area and entities inside a radius, this is not very consistent.

**Comment by sorcerykid** [comment]
Correct me if I'm wrong, but I believe that the "radius" argument in find_nodes_near( ) is not in actuality a radius, but rather a vector offset. So the search algorithm is still a cubic area for both functions. It's just that find_nodes_near progresses outwards.

**Comment by tenplus1** [comment]
Yep, find_node_near() works it's way from centre outwards in a cubic manor.

**Comment by DS-Minetest** [comment]
Oh, I didn't know, that `find_node_near()` works it's way from centre outwards in a cubic manor.

I'm unclear about this now. Would it really be useful to get nodes in a sphere and entities in an area? Perhaps this should better be closed.

**Comment by paramat** [comment]
Since `find_node_near` searches outwards in cubic shells it could not work spherically, or if it did it would be weird and innefficient searching cubic shells within a sphere.

**Comment by DS-Minetest** [comment]
I'll close this since I'm pretty sure now that it's not needed.

**Comment by paramat** [comment]
> Would it really be useful to get nodes in a sphere

Might sometimes be useful but it's inefficient because to search a sphere you still have to iterate through the cube that contains the sphere. In most cases a cuboid search area is fine or preferred. I can't remember anyone needing a spherical volume searched.

**Comment by TamaMcGlinn** [comment]
@Desour you say "You can easily get (...) entities inside a radius" but it's not very easy to find actually. There's no `minetest.find_entities`, for example. Instead, you have to use `minetest.get_objects_inside_radius(nodeLocation, radius)`. Searching the entire codebase for "search_entities" or "find_entity_within" or "get_entities_inside_range" or "get_entities_inside_radius" or "find_entity_near" will not yield any results.

**Comment by appgurueu** [comment]
> @Desour you say "You can easily get (...) entities inside a radius" but it's not very easy to find actually.

It is a bit naive to expect that the name you would guess for this function happens to be what it is called. If you just search for `radius` in `lua_api.md` you can find it in a minute. Indeed the naming is inconsistent with that of `find_nodes_in_area` or similar; that's what happens in larger projects with many contributors unfortunately, and introducing aliases (and potentially deprecations) is usually not worth it.

(Note also that a Lua entity is a different thing from an object: Objects also include players.)

Side note, I'm usually a vocal critic of using generative AI in programming, but this kind of mind-numbing task (essentially resolving some synonyms or similar words to find the right name for an API method) is something they're definitively okay for (you should absolutely refer to the proper API reference once you've gotten the function name though). See for yourself (note that obviously ChatGPT is not very aware of the recent rename so I'm reminding it):

![Screenshot from 2024-12-31 13-43-27](https://github.com/user-attachments/assets/b413f96b-a67b-4848-a9dd-1156fedace78)

(ChatGPT's answer goes on to summarize some more helpful things (including implying the currently linear performance) and to give some slightly outdated examples but it's essentially fine.)

**Comment by Desour** [comment]
> @Desour you say "You can easily get (...) entities inside a radius" but it's not very easy to find actually. There's no `minetest.find_entities`, for example. Instead, you have to use `minetest.get_objects_inside_radius(nodeLocation, radius)`. Searching the entire codebase for "search_entities" or "find_entity_within" or "get_entities_inside_range" or "get_entities_inside_radius" or "find_entity_near" will not yield any results.

Well, it doesn't have any filtering, so finding the entity requires iterating through the objects. But this is fine, because there usually aren't as many objects as nodes in an area.

Anyway, this is kinda offtopic for this (ugly and old) issue. You can ask modding questions on the forum or irc (`#minetest`).
