### ISSUE TITLE
Allow showing percentage of image in hud when hud_elem_type is set to "image"

### ISSUE THREAD

**Issue by PureTryOut** [minetest/minetest#5221]
It's quite hard to describe in a title ;)

Currently I'm making a hud element which uses `hud_elem_type = "image"` to show a progressbar. Right now to "fill" the bar I scale the image from 0 to 100%, but this looks quite ugly with the texture I'm using because I'm not using just a solid texture (which I see other mods do).
I would like a way to tell Minetest to only show a part of the image (say 50%). This way I can make the bar fill up *while looking good* by just showing a bigger and bigger part of the image.

**Comment by rubenwardy** [comment]
Use texture modifiers, like in the furnace

```
gui_furnace_arrow_bg.png^[lowpart:DECIMAL:gui_furnace_arrow_fg.png^[transformR270
```

where DECIMAL is a "percentage" between 0 and 1
