### ISSUE TITLE
add dungen dimensions to gennotify

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5224]
Gennotify only provides the center coordinates of a dungeon room. For decorations the room size would be helpful too

Currently I need to search the walls in lua by myself, which is inefficient

**Comment by paramat** [comment]
Not keen on this, it's only rarely that modders would want to know how big the room is, so gennotify just stores very basic position data for this resaon. I feel Lua is the place for the more specialist task of searching for walls, after all you will still need to use Lua to search for a suitable place on a wall, and avoid doorways and voids.

**Comment by MarkuBu** [comment]
Well, how many mods add dungeon stuff? I only know dungeon loot. And that mod just adds chests at the center of a room

**Comment by paramat** [comment]
Roomsize would not be helpful at all, gennotify would have to store the relative position of all walls, plus data for where doors, voids and stairwells are. All this data is pointless when almost no-one uses the data and if they do they will need to use mod code to find suitable positions for decorations anyway.
:-1:
