### ISSUE TITLE
Light passes solid nodes

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5233]
I build a small shed with a single torch inside. But even if I seal all holes the shed still shines bright outside

I use the latest dev from the ubuntu launchbad PPA. Don't know which build it is. 

![screenshot_20170214_191013](https://cloud.githubusercontent.com/assets/16163058/22942375/943ef0ea-f2e9-11e6-87e8-972fca4dd941.jpg)

**Comment by tenplus1** [comment]
It looks like you are using stairs and slabs which let light shine through.

**Comment by MarkuBu** [comment]
Yes, I use stairs and slabs. Is this an unfixed bug or a wanted feature?

**Comment by Fixer-007** [comment]
Thats just how it works...

**Comment by MarkuBu** [comment]
Looks a bit odd at night
![screenshot_20170214_210116](https://cloud.githubusercontent.com/assets/16163058/22946796/ccd69110-f2f8-11e6-90f2-5983322a7f44.jpg)

**Comment by paramat** [comment]
As far as i know, nodeboxes have to be 'paramtype = "light"' (propagates and attenuates light) because they get their light value from their internal light value, which would be 0 if they were like cubic nodes.
Can anyone confirm this?

**Comment by Fixer-007** [comment]
I think it is intended and was like that from very beginning, stairs and slabs pass the light (slightly).

**Comment by MarkuBu** [comment]
yes, they are paramtype = "light". Without that it looks like this

![screenshot_20170215_083847](https://cloud.githubusercontent.com/assets/16163058/22964707/3f100fca-f35a-11e6-9831-32aaf5eac21e.jpg)

So why is paramtype = "light" needed? Just because light "may" pass through a hole? However, in this case it looks much better without paramtype = "light" than with

**Comment by tenplus1** [comment]
Depending on stair/slab orientation a gap can be seen and you would want the light to come through the gap irl, so it has been set as such here also.

**Comment by MarkuBu** [comment]
That's exactly the reason I expected. 

But what is more annoying? An unrealistic light in cases like mine or a missing light through a gap?

**Comment by Fixer-007** [comment]
maybe that "light" parameter should depend on how slab/stair is placed?

**Comment by MarkuBu** [comment]
No, you can't predict just of the orientation if there is a gap or not. I think to make this work you would need to calculate the light not only in blocks but in eighth of one block

**Comment by MarkuBu** [comment]
Well, I noticed an issue. If you turn of smooth lightning slabs and stairs are black when paramtype = "light" is not set.

But anyway, I would prefer this setting

**Comment by dsohler** [comment]
Can confirm light passing (edges) of solid blocks.

![screenshot_20170215_234138](https://cloud.githubusercontent.com/assets/1668792/22998671/103fce0a-f3d8-11e6-8f17-977d6e210e52.png)
![screenshot_20170215_234141](https://cloud.githubusercontent.com/assets/1668792/22998670/103dee8c-f3d8-11e6-9619-7ca2f7c4c685.png)
![screenshot_20170215_234156](https://cloud.githubusercontent.com/assets/1668792/22998672/10446fc8-f3d8-11e6-9b29-445d01fee896.png)

**Comment by MarkuBu** [comment]
Yes, this is also an ugly known bug. I build an igloo form snow with one torch in it and it just glows outside, even with a second layer of snow

As you can see on the screenshot the light comes even to two layers of blocks. I removed one in the center to demonstrate the difference. 

And FYI, the torch is only set to `light_source = 10`

![screenshot_20170215_234705](https://cloud.githubusercontent.com/assets/16163058/22998940/6a678962-f3d9-11e6-8a64-4a20e90feb3f.jpg)

**Comment by paramat** [comment]
> Well, I noticed an issue. If you turn of smooth lightning slabs and stairs are black when paramtype = "light" is not set.

Before smooth lighting was added to nodeboxes recently they went dark with the global smooth lighting setting enabled, if they did not have 'paramtype = "light"" (because non-smooth lighting was forced for nodeboxes) so that's the main reason.

> Can confirm light passing (edges) of solid nodes.

Yes different issue, this is because face lighting is calculated from the light at vertexes, and those vertexes are of course bright. I consider that as light bleeding through the zero-thickness gaps along the edges and at the corners, then it doesn't seem so unreasonable.

**Comment by paramat** [comment]
A possibility is to force 'paramtype = "light"' when smooth lighting is disabled, otherwise leave it up to the modder whether they want light propagation for a node.

**Comment by MarkuBu** [comment]
> Many nodeboxes do not fill a cube and need to transmit light depending on their orientation, it would be too complex to decide light propagation by detecting if the orientation should block light.

I understand how it works. It would be much more complex to calculate if light passes a gap in a nodebox

**Comment by MarkuBu** [comment]
Hm, if I remove paramtype = "light" from stairs they emit light if shaders are on

Need to test this more and open an issue eventually

**Comment by paramat** [comment]
Duplicates #3554

**Comment by dsohler** [comment]
> Duplicates #3554

No it doesn’t, because #3554 is about mesh and nodebox nodes and this here is about solid nodes.

**Comment by DS-Minetest** [comment]
>this here is about solid nodes.

Here slabs and stairs were seen as solid.

**Comment by dsohler** [comment]
But they aren’t. And light leaking through the edges of actually solid nodes is a confirmed bug.

**Comment by paramat** [comment]
This issue is about stairs and slabs (meshnodes and nodeboxes) letting light through.
Your issue shown in https://github.com/minetest/minetest/issues/5233#issuecomment-280163929 is a different unrelated issue that happens with full cube nodes, it should have a separate issue if there isn't one already.

**Comment by dsohler** [comment]
Sigh … happy now?

https://github.com/minetest/minetest/issues/6429
