### ISSUE TITLE
Login name field is erased after entering singleplayer

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5236]
To reproduce: (you should have your **login name** entered for multiplayer saved in config at this time), switch to singleplayer, start game, exit, go to multiplayer tab, **login name field** is empty.

Basically "name = blabla" is erased from minetest.conf after joining and exiting singleplayer.

Engine at minetest 1de08e1, started happening recently. Someone fumbled with formspecs 💃💃💃

**Comment by rubenwardy** [comment]
I'm not sure what you mean by this. Screenshot?

**Comment by red-001** [comment]
Maybe he means singleplayer wiping the player name from the settings?

**Comment by Fixer-007** [comment]
Will bisect now:
1de08e1 is bad one
87e9466 is good build

**Comment by Fixer-007** [comment]
Regression caused by this https://github.com/minetest/minetest/commit/e2ad76f91087215309012300eb9f1ebdd7fa40ee

@red-001 and others...
