### ISSUE TITLE
Allow offsetting placement of nodes

### ISSUE THREAD

**Issue by PureTryOut** [minetest/minetest#5240]
I'd like to have a node (draw type "plantlike") to be off-setted (is that even a word?) a pixel downwards to be able to fit on the (custom) block beneath it.

Because a picture does more than a thousand words:
![screenshot_2017-02-15_16-09-49](https://cloud.githubusercontent.com/assets/1565836/22980466/d848574e-f399-11e6-95f1-b2d95eb03a76.png)

Normally I would use draw type nodebox for something like this, and just make the nodebox start 1 pixel lower. However, since this node is a plant, it won't work like that, and I'm left with a small gap between the two nodes.

**Comment by paramat** [comment]
Unfortunately adding a new drawtype just for this rare usage is not likely.

**Comment by PureTryOut** [comment]
I don't need a separate drawtype tbh, just being able to offset the node a few pixels each direction (in my case just downwards) would be good enough. We could even make blocks fit on top of slabs that way, just offsetting it half a block down.

**Comment by numberZero** [comment]
@PureTryOut There are too many options already. Use a mesh instead. (You can even make it in `vim` for such simple `plantlike` thing).
But some existing options, like (currently `plantlike`-only) random offset, should probably be applicable to meshes too.

**Comment by paramat** [comment]
Well, placing plantlike on slabs is rarely done too, i'm not sure there is enough need to do this.

**Comment by numberZero** [comment]
@paramat 
> placing plantlike on slabs is rarely done

Imagine how does it look now ;)

Really, I’m against new drawtypes, the system is overcomplicated already. But new paramtype (e.g. vertical offset, just like degrotate), well supported by many drawtypes, might be a reasonable addition.

**Comment by sofar** [comment]
The simplest method is just to make a custom mesh node that is 1/16 lower.

**Comment by paramat** [comment]
Interestingly i have recently wished we can place plantlike on slabs so that i can create a mapgen that uses slabs to create smoother, and walkable, slopes.

**Comment by rubenwardy** [comment]
Can't you use plantlike_rooted for this?

**Comment by paramat** [comment]
The plantlike_rooted node would have to be below the nodebox, it's a bit hacky.
