### ISSUE TITLE
Improve shadows in Minetest

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5241]
There is one thing in Mintest that always bothers me. Shadows.

Under a closed plant of nodes there is nearly no visible shadow

![screenshot_20170215_160018](https://cloud.githubusercontent.com/assets/16163058/22979953/5ef9af56-f398-11e6-9726-13fb2f5cbaa0.jpg)

Under an overhang it is pitchblack

![screenshot_20170215_160114](https://cloud.githubusercontent.com/assets/16163058/22980049/931a4368-f398-11e6-9bf6-3b632e315a71.jpg)

I noticed in the "other game" that shadows look more realistic, even without shader

![bildschirmfoto vom 2017-02-15 15-35-15](https://cloud.githubusercontent.com/assets/16163058/22980134/f0db40f6-f398-11e6-8a7d-36d6450644e7.png)

This is a screenshot from the very first version of MC

![bildschirmfoto vom 2017-02-15 16-09-25](https://cloud.githubusercontent.com/assets/16163058/22980220/37a81acc-f399-11e6-8bcf-af2ac4dd67c0.png)

same scene in MT

![screenshot_20170215_161537](https://cloud.githubusercontent.com/assets/16163058/22980521/0de4b050-f39a-11e6-90d6-b928e306555b.jpg)

I would really like to see better shadows. There should be a visible shadow below nodes and it should not be pitchblack under overhangs

**Comment by C1ffisme** [comment]
@MarkuBu Yes please. As much as I'd like our general gameplay to be mildly different from Minecraft's, I'd like to see similar rendering techniques used, because the game just doesn't look... appealing... to me.

**Comment by Fixer-007** [comment]
This is expected and thats how lighting system works. You can get worldedit and inspect it to see how it works. Basicly it is around 13-14 below that blocks, you will not have a big shadow at all, to make a deep shadow you need to place lots of blocks, say 20x20..., that will give you dark spot in center.

**Comment by MarkuBu** [comment]
This is how Minetest lighting system works. MC and reality makes it different.

Seriously, the plane of dirt from my first screenshot should cause much more shadow

And to be honest, torches are to bright

**Comment by Fixer-007** [comment]
It is planned to slightly decrease torch light.

**Comment by MarkuBu** [comment]
That's good. But what can be done to get more MC like lightning?

**Comment by MarkuBu** [comment]
And maybe fix #5233

**Comment by sofar** [comment]
> But what can be done to get more MC like lightning?

redo the entire lighting model from scratch, and remove everything we have.

**Comment by juhdanad** [comment]
> redo the entire lighting model from scratch, and remove everything we have.

Or just modify `Light_LUT` for sunlight (the light value - screen brightness mapping) to a function that is bright at sunlight (light=15), then at light=14 brightness drops significantly, and then it slowly reaches zero at light=0. This makes shadows sharper, as light=15 only if there are no nodes above the block.

**Comment by Fixer-007** [comment]
well, maybe not significantly, but in a way noticeable by the player, don't wanna torchless houses be dark as hell at daylight...

**Comment by RHRhino** [comment]
@MarkuBu Vanilla MC (PC) without shaders smoothes shadows the same way as Minetest does. Idk how you created this hard drop shadow, I guess you installed some shaders for that.

![2017-02-15_21 33 45](https://cloud.githubusercontent.com/assets/6941454/22994369/05553c66-f3c7-11e6-8d71-11a13800a8c6.png)

![](https://cloud.githubusercontent.com/assets/16163058/22980134/f0db40f6-f398-11e6-8a7d-36d6450644e7.png)

Changing the light curve of torches does not affect #5233 and MC has the similar problems with light passing through stairs models.

![2017-02-15_21 51 37](https://cloud.githubusercontent.com/assets/6941454/22994917/f494a194-f3c8-11e6-815b-77ba001cc9b4.png)

**Comment by MarkuBu** [comment]
@RHRhino I don't play MC. My screenshot is from YouTube. But this video doesn't look like there is a shader installed.

On your first screenshot I can see also a shadow and shadows around the nodes on the ground. If this is vanilla it is still far better than MT

**Comment by MarkuBu** [comment]
> It is planned to slightly decrease torch light.

I'm currently testing a value of 10. It's still fine and looks more natural. It's a damn torch and not a 1000W Super Truper Stage Light.

**Comment by paramat** [comment]
There was a lot of discussion on torch brightness, i wanted to reduce it once the new light curve was added to compensate and create a difference between torch and max-brightness mese lights, but there was controversy. I still think we can reduce torches to 11, they are extremely bright and will still be visually brighter than before with the old light curve. See discussion #1476

The weak shadows are due to the new light curve which has a much gentler dropoff of visual brightness with light level, i've noticed dense forests are not as dark now unfortunately.

**Comment by paramat** [comment]
@sofar this was you original intention https://github.com/minetest/minetest/pull/4873#issuecomment-266915098 "what we want to do is, after 0.4.15, merge this and redo all the light levels in minetest_game - we should lower the torch light level, and possible the mese lamp level too."
However there was some opposition. For a compromise how about we reduce torch light level by 1 to 12. Then we can have torch 12, fire 13, mese lights (able to grow crops) 14, which makes sense, then fire can be brighter than a torch (lava is currently 13, equal to fire). This of course will not affect the growing of crops because torches were never bright enough to do that.

**Comment by MarkuBu** [comment]
About the torch: people who want's a bright torch are just lazy. It wouldn't a huge problem to create a new light source and write an LBM to replace torches with the new lightsource. And as I said: it's a damn torch

About the shadow: tuning the light curve to fit a few peoples laziness on cost of the visual game appearance is the wrong way. First of all the visual appearance should be good. Everything else has to be adjusted to that. The absence of shadows on one side, the pitchblack shadows on the other side are not really appealing.

Shadows under overhangs: In computer graphics an environment light is added. How about a minimal light level?

**Comment by paramat** [comment]
The light curve was changed for good reason and greatly improves lighting. what it improved were not things that could be done by other means, so it's not a case of laziness.

Ambient light may be very difficult, how would you decide whether there is a source of light nearby in a sealed cave with parts of the cave unloaded?

**Comment by MarkuBu** [comment]
I don't really see an improvement, but ok

I know that it is difficult, but I don't know enough about the light to have a better idea

**Comment by Fixer-007** [comment]
It was huge improvement, you needed a lot of torches or even mese lamps to make a simple room bright, everything looked like it was global minetest energy crysis :) No more. Now you have actual ability to tweak torch/lava/fire light levels, before that it was everything dark, now we can customise it.

**Comment by sofar** [comment]
I think lowering the torch by 1 or 2 is reasonable. Torches are bright enough to really light up caves right now, whereas before the new light level map they totally were not, so dropping it one or two is reasonable, it brings back a bit more atmosphere but won't drop down the usable light range to previous levels where 5-6 nodes away from a torch you're already squinting to see further.

**Comment by paramat** [comment]
I'll open a new PR for reducing torch by 1.

**Comment by paramat** [comment]
To be clear to those who may object:
Even with a reduced light source level, torches will still be effectively much 'brighter' than with the old lightcurve in 0.4.15 stable.
This will not affect the growing of plants as the current torch light level of 13 is not high enough to do that anyway.

**Comment by C1ffisme** [comment]
I decided to do some experimenting with Minecraft and Minetest lighting. Do note that Minecraft has a slider for how bright or dark it's light curve (I assume that's the right term) is. Also note these take place on (close enough to) 15 deep by 20 wide platforms:

Minetest, Smooth Lighting:
![screenshot_20170216_201340](https://cloud.githubusercontent.com/assets/9893266/23050069/b7e99c6e-f485-11e6-9860-f4f7f64c04f3.png)

Minetest, No smooth Lighting:
![screenshot_20170216_201405](https://cloud.githubusercontent.com/assets/9893266/23050082/bf8ac6c8-f485-11e6-8cca-a4258cc9cb8a.png)

Minecraft, Smooth Lighting, Darkest Brightness:

![2017-02-16_20 25 24](https://cloud.githubusercontent.com/assets/9893266/23050155/32e2721a-f486-11e6-8302-b5ca165cdfcb.png)

Minecraft, Smooth Lighting, Brightest Brightness:

![2017-02-16_20 25 37](https://cloud.githubusercontent.com/assets/9893266/23050168/41ec1e3c-f486-11e6-8c05-6275851a0bb2.png)

Minecraft, No smooth lighting, Darkest Brightness:

![2017-02-16_20 25 02](https://cloud.githubusercontent.com/assets/9893266/23050184/53fb30cc-f486-11e6-8167-e703f46850e7.png)

Minecraft, No smooth lighting, Brightest Brightness:

![2017-02-16_20 25 13](https://cloud.githubusercontent.com/assets/9893266/23050194/60832fde-f486-11e6-9944-4ae048eab9f0.png)

**Comment by MarkuBu** [comment]
Interesting. Can you do this for overhangs too? Minecraft screenshot would be enough because we know how Minetest looks.

**Comment by numberZero** [comment]
@C1ffisme That looks very similar. But please add such flat cobble wall in MT. Shape does matter.
And remember that MT has brightness control too, called `gamma`, although it is hidden somewhere in the advanced options.

**Comment by paramat** [comment]
MC uses a very similar lighting method, but it's lightcurve is apparently more exponential with more dropoff at high values, while MT's is now fairly linear near high values, so we effectively have a 'brighter' game but this means more subtle shadows.

**Comment by Fixer-007** [comment]
How it is done in MC: http://minecraft.gamepedia.com/Light

**Comment by C1ffisme** [comment]
@numberZero Arright, I'll get on it...

**Comment by numberZero** [comment]
Tested linear scale:
![screenshot_20170218_182942](https://cloud.githubusercontent.com/assets/7352626/23094450/7f34421e-f612-11e6-8ba2-2f1679fa1385.png)
(`encode_light_and_color` does some own magic)

In-game:
![screenshot_20170218_184150](https://cloud.githubusercontent.com/assets/7352626/23094400/b4efc23a-f611-11e6-9318-fe75d789933b.png)
![screenshot_20170218_184212](https://cloud.githubusercontent.com/assets/7352626/23094401/b4f97172-f611-11e6-9460-2c208e16d6d3.png)

With tone mapping:
![screenshot_20170218_183135](https://cloud.githubusercontent.com/assets/7352626/23094382/435f2e4e-f611-11e6-9d94-3544c18e6bc6.png)
![screenshot_20170218_183300](https://cloud.githubusercontent.com/assets/7352626/23094384/438dfdfa-f611-11e6-9df0-af0b225b1ee1.png)

**Comment by numberZero** [comment]
Playing with shading. What’s about this? (codename `983f80bc`)
![screenshot_20170218_192030](https://cloud.githubusercontent.com/assets/7352626/23094688/21856210-f617-11e6-9a6f-83bbcaa65436.png)
![screenshot_20170218_192105](https://cloud.githubusercontent.com/assets/7352626/23094689/21ba678a-f617-11e6-8720-9b15aaf045d2.png)

**Comment by MarkuBu** [comment]
Looks a bit better I think. Have to see it in a real game

**Comment by numberZero** [comment]
https://github.com/numberZero/minetest/commit/1f631a017eb37b4000afe162b0c04fa652420b6c
Try also https://github.com/numberZero/minetest/commit/4bb114217901ee1671dabf16b73ef9e0333ca311 and play with gamma and sharpness values a bit.

**Comment by paramat** [comment]
#5279 merged. Lightcurve is now user-settable so shadows can be adjusted to taste.
Author has also left MT.
