### ISSUE TITLE
Client spews node metadata messages for no reason.

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#5246]
I have a server mod that has a node that every 12 seconds replaces itself with the same node but a different param2. 

The *client* runs on a different machine and constantly emits the following warnings:

```
2017-02-15 22:18:31: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:18:31: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2017-02-15 22:18:44: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:18:44: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2017-02-15 22:18:57: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:18:57: WARNING[Main]: Map::removeNodeMetadata(): Block not found
2017-02-15 22:19:09: WARNING[Main]: Map::getNodeMetadata(): Block not found
2017-02-15 22:19:09: WARNING[Main]: Map::removeNodeMetadata(): Block not found
```

There is no metadata used in this node.

The node is rotated randomly somewhat like this:

```
	on_timer = function(pos, node)
		-- make it self-rotate randomly
		minetest.set_node(pos, {name = "test:rotating_node", param2 = math.random(24) - 1})
	end,
```

**Comment by paramat** [comment]
I get this too with no mods running.

**Comment by red-001** [comment]
maybe move the messages to infostream?

**Comment by Ekdohibs** [comment]
Could it be caused by the use of `minetest.swap_node`? Since it keeps metadata, maybe it complains about not being able to find it in the first place.

**Comment by Ekdohibs** [comment]
Probable cause: the client is near the node that is modified, but not facing it. As such, the mapblock is not loaded on the client side, and thus the block is not found when looking for its metadata. However, since the client is near that node, then it will receive the map events concerning it, thus creating this error message.

**Comment by sofar** [comment]
It has always amazed me that I can turn around and find myself with nothing but a blue abyss.

Can't the client always load the blocks *right* behind them? I mean, the chance that a player turns around is practically 1.

**Comment by paramat** [comment]
^ That would also help when falling and looking upwards. Seems a good idea to always load all blocks within a 1 block radius @lhofhansl ?

**Comment by ClobberXD** [comment]
My debug.txt is ridden with 1000's of these messages...

Is someone working on this issue? If not, I could try my hand at fixing this.

**Comment by paramat** [comment]
I'm fairly sure no-one's working on it.
This issue still happens to me quite often.

**Comment by SmallJoker** [comment]
@ClobberXD Whereas you're right with that it's where the messages are thrown, it is not the source of the issue.
Ekdohibs already mentioned it earlier. `sendAddNode` and `sendRemoveNode` usually do a range of 30m check around the clients to decide whether to send a single change or mark the entire mapblock as not sent:
https://github.com/minetest/minetest/blob/1aaee5b30d2c28e3256a0c8c3fc3784af91fb21b/src/server.cpp#L2129-L2134

**Comment by lhofhansl** [comment]
Just seeing this comment:
> ^ That would also help when falling and looking upwards. Seems a good idea to always load all blocks within a 1 block radius @lhofhansl ?

Yes. I think that would be a good idea. Although 1 block would still lead to a visible "blue abyss". I think this is simply a trade-off between reducing the number of a blocks and having an occasional visibly missing block.
