### ISSUE TITLE
This code should fill a mapchunk

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5254]
I'm pretty sure that this code should fill a mapchunk with meselamps, but it doesn't. Only half of the chunk is filled

Is something wrong with my code or is there a bug? I also tried to calculate the index with a:index(), but with the same result

The same loop works fine e.g. in the intersect_light mod from duane. I have no clue what's wrong

```
minetest.register_on_generated(function(minp, maxp)
	local vm, emin, emax = minetest.get_mapgen_object("voxelmanip")
	local a = VoxelArea:new({MinEdge = minp, MaxEdge = maxp})
	local data = vm:get_data()
	local c_glass = minetest.get_content_id("default:meselamp")
	local heightmap = minetest.get_mapgen_object("heightmap")

	for z = minp.z, maxp.z do
	for y = minp.y, maxp.y do
	for x = minp.x, maxp.x do
			data[count] = c_glass
			count = count + 1
	end
	end
	end

	vm:set_data(data)
	vm:write_to_map()
end)
```

**Comment by paramat** [comment]
Try `local a = VoxelArea:new({MinEdge = emin, MaxEdge = emax})`

**Comment by MarkuBu** [comment]
Boah, damn, I really didn't see this. Thanks paramat
