### ISSUE TITLE
Schematic generated chests and furnaces don't work

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5256]
I placed a chest and a furnace with a schematic to a map, but both can't be used. They behave like normal nodes. I can't open their inventory.

I use a lua table schematic. This is the code for the chest and the furnace

Edit: I place the schematic as decoration with the mapgen (like a tree)

```
local n48 = { name = "default:chest", param2 = 3, force_place = true }
local n49 = { name = "default:furnace", force_place = true }
```

**Comment by sfan5** [comment]
The schematic format is meant for rather simple node arragements (bushes, trees) and does not support metadata on purpose, not a bug.

**Comment by Fixer-007** [comment]
Maybe make it as "future request", maybe someone will implement?

**Comment by MarkuBu** [comment]
Yes, please reopen it as feature request. Could be useful sometimes

**Comment by MarkuBu** [comment]
Or I open a new issue for that. Maybe better

**Comment by sofar** [comment]
This can be fixed mod-side, just hang a `on_rightclick` function on the chest node that initializes the chest formspec`. If there is a formspec, the client displays it, and so the `on_rightclick` only gets called once, ever.

**Comment by MarkuBu** [comment]
This might work, but would mean that you have to click twice to a node

**Comment by SmallJoker** [comment]
@MarkuBu After creating the formspec and inventory items it's still possible to send the player a formspec in `on_rightclick`.

**Comment by MarkuBu** [comment]
Ah, ok. Do you have an example for that?

**Comment by SmallJoker** [comment]
```lua
minetest.override_item("default:chest", {
	on_rightclick = function(pos, node, clicker, itemstack, pointed_thing)
		minetest.registered_nodes["default:chest"].on_construct(pos)
		minetest.show_formspec(
			clicker:get_player_name(),
			"default:chest",
			get_locked_chest_formspec(pos)
			-- ^ Cheat: Same inventory names as the locked chest
			--          also uses the coordinates to define the inventory location
		)
	end,
})
```

**Comment by MarkuBu** [comment]
Thanks, I need to learn more about formspecs, metadata, itemstacks and inventory

**Comment by MarkuBu** [comment]
@SmallJoker can you tell me what this line is for?

`minetest.registered_nodes["default:chest"].on_construct(pos)`

If I add this line to the current (MTG 0.4.16) code for chests even schematic placed chests work as expected. Without this line the chest opens, but I don't get an inventory form
