### ISSUE TITLE
Dropped item shadows

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5264]
I would like to add a new setting for item drop entity graphics type "Fancy" and "Fast" for slow or old computers (except for block drop entity, because it always as Fancy look). Oldest item drop looks like a "Fast" type with spining (not shown), i don't want it back.
https://www.youtube.com/watch?v=yHqBWrZhC2E

Also i want to add to make leave shadow.
![my desktop 08 08 2016 - -](https://cloud.githubusercontent.com/assets/13905392/23092534/0ebc36c2-f5d6-11e6-8928-45291851aab8.png)

**Comment by paramat** [comment]
I'm not keen on shadows.

**Comment by rubenwardy** [comment]
Shadows makes them seem more physical and tangible. As a graphical effect, it's fine for this to be shaders only imo

**Comment by tobyplowy** [comment]
I do like the look of the shadow like @rubenwardy says 

> Shadows makes them seem more physical

**Comment by numberZero** [comment]
As nodes have shadows (some side-effect of smooth lighting?), this seems reasonable too. But shadows should be smoother, so that 1. they would match node shadows, and 2. shape mismatch would not be a problem. Also the shadows should only appear on a node, if possible.

**Comment by paramat** [comment]
The objects are thin extruded planes, round shadows look weird.

**Comment by numberZero** [comment]
@paramat smooth enough shadows wouldn’t look weird

**Comment by paramat** [comment]
Yes smooth-blended circular would be best.

**Comment by Calinou** [comment]
This should probably be closed in favor of https://github.com/minetest/minetest/issues/13164.
