### ISSUE TITLE
find_nodes_in_area doesn't work in register_on_generated

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5275]
I tried a small code

```
minetest.register_on_generated(function(minp, maxp)
    local nodes, count = minetest.find_nodes_in_area(minp, maxp, {"air"})
    print(dump(count))
end)
```

I would expect to get 512000 in clean air, but I get less than 60000, even in clean air. Adding "ignore" doesn't change it. Get ignore = 0

Is the area to large or is it not possible to use find_nodes_in_area in register_on_generated?

**Comment by paramat** [comment]
The node count is a u16 so limited to 65536 and overflows https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_env.cpp#L653

**Comment by MarkuBu** [comment]
That explains the results. I think the limit is ok. With u32 the resulting list would go crazy

Possible close?
