### ISSUE TITLE
Biome API: Heat and humidity gradient parameters

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5278]
I realised i may be able to add parameters for linear heat and humidity gradients to the Biome API in a fairly simple and lightweight way.
Each would have 3 components, for X, Y, Z, so that change with altitude and/or change with horizontal world location would be possible.
These would act from 0,0,0 so any offset needed would be applied in the 'offset' of the noise parameters.
This would not necessarily be used in MTGame for all mapgens but would be settable by users or by mods.
This could possibly replace the 'altitude chill' code in mgvalleys.

Just wanted to gauge interest.

Related #4205

**Comment by MarkuBu** [comment]
Sounds interesting. It would be possible to create maps with an equator and falling temperatures to North and south or similar. Or with a polar area in the center and rising temperatures in all directions.

Yes, please

**Comment by paramat** [comment]
I'm not sure about more complex gradients as you describe, maybe, want to keep it as simple as possible.

**Comment by MarkuBu** [comment]
If it works for altitude chill in Y axis, why not in X and Z axis?

**Comment by paramat** [comment]
The change with altitude is linear, but of course at some point hits a reasonable limit. This would also result in a rise in temperature underground which is acceptable i think.

**Comment by MarkuBu** [comment]
Well, it's realistic. The deeper you dig, the hotter it will be

**Comment by paramat** [comment]
Thinking about how the geometry of a planet affects variation of climate .. for a MT world that is a flat plane the only horizontal geometric effect that makes sense would be 'distance from edge' / 'distance from centre' with a square-type radius (due to cubic cosmology).

The advantage of linear is that you can have world centre unchanged, colder Northwards and hotter Southwards, for all 3. Whereas with centre-outwards variation if the centre is unchanged you can only either get colder outwards or hotter outwards, unless you offset the centre to be cold or hot.

So we could perhaps have linear vertically, plus a choice of linear or centre-out horizontally.

**Comment by paramat** [comment]
Closing, please discuss in #4205
