### ISSUE TITLE
ItemStack() seems to delete some metas on its own

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#5282]
`minetest.deserialize(some_item_string)` : 

```Lua
meta = {
	test = "return {\"foo:bar\"}",
	description = "Foo bar"
},
metadata = "",
count = 1,
name = "foo:bar",
wear = 0
```

`ItemStack(minetest.deserialize(some_item_string))` : 

```Lua
meta = {
	["foo:bar"] = "Foo bar"
},
metadata = "",
count = 1,
name = "foo:bar",
wear = 0
```

**Comment by rubenwardy** [comment]
What's an example of `some_item_string`?

**Comment by rubenwardy** [comment]
Can reproduce with

```lua
local stack = ItemStack("default:stone")
stack:get_meta():set_string("foo", "bar")
stack:get_meta():set_string("description", "Hello everyone!")

print(stack:to_table())
print(dump(ItemStack(stack:to_table()):to_table()))

error("")
```

**Comment by rubenwardy** [comment]
#5283

**Comment by nerzhul** [comment]
@rubenwardy is this possible to have a unittest to check the meta validity and ensure we don't break this anymore ?

**Comment by rubenwardy** [comment]
If it's possible to unit test lua methods, then yes

**Comment by nerzhul** [comment]
@rubenwardy maybe outside of this PR we should add a specific lua stack for unittests then

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/commit/2d1fca51e975a01f84fa3fd9b266435316fbe548
