### ISSUE TITLE
Switch tabs using mouse wheel

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#5285]
In minetest in the mainmenu you can't use the mousewheel to switch tabs.

In many programs, you can conveniently use mousewheel down to switch to the tab right to the current tab. If the tab is the last one, it does nothing. Mousewheel up switches to the left tab.

**Comment by paramat** [comment]
Seems pointless extra functionality, just click the tab instead, there are only a few of them.
:-1:

**Comment by HybridDog** [comment]
> extra functionality

When l took a look at the code, l noticed that it uses an irrlicht tabs library, so maybe it can be configured without adding lines to code.

**Comment by paramat** [comment]
That would be better.

**Comment by paramat** [comment]
Sorry, i feel this is not needed and has no benefit, i feel it is a waste of time to consider, implement or review this.

**Comment by C1ffisme** [comment]
@paramat
> i feel it is a waste of time to consider, implement or review this

That's a little bit harsh, considering you are the only one that's seen this suggestion. Although, I do agree, I don't see why this is something that would be useful, if anything I think giving tabs hotkeys would be more useful, if you could also browse and use menus using the keyboard.

**Comment by sofar** [comment]
I'd support this. There are other threads for better input event handling, and scrollwheel events are already something the client does something with, so I don't see why we couldn't use it for other things as well.
