### ISSUE TITLE
Pressing inventory button exits pause menu

### ISSUE THREAD

**Issue by wilkgr76** [minetest/minetest#5287]
Title is self-explanatory. Steps to reproduce:

1. Pause game
2. Press the button that is bound to opening the inventory. Game unpauses (multiplayer & singleplayer)

Other keys don't unpause the game as far as I can tell (apart from the button to pause the game ofc).

**Comment by DS-Minetest** [comment]
Is this a problem?

**Comment by Wayward1** [comment]
It seems to me that if you're accessing the inventory, you're indicating you wish to resume playing

**Comment by paramat** [comment]
Not much of a problem, but inconsistent with other key presses.

**Comment by wilkgr76** [comment]
@Wayward1 Then why don't the movement keys unpause the game?

For singleplayer - esp. hardcore survival - it can be an issue if it unpauses unexpectedly. I, for one, don't want to come back from lunch to find that I'm dead and my items have all despawned.

**Comment by DS-Minetest** [comment]
I like it as it is.
You can still go back to main menu or to os if you think, it's too risky to leave it in pause.

**Comment by wilkgr76** [comment]
@DS-Minetest In that case, why don't movement keys unpause the game?

**Comment by DS-Minetest** [comment]
On normal settings the movement keys are `w`, `a`, `s` and `d`, the inventory button is `i`. Your hand is always on `w`, `a`, `s` and `d`, you could press one of them by mistake, `i` not because you have to move your arm and press it intentionally.

**Comment by wilkgr76** [comment]
@DS-Minetest 

Honestly, you make a good point that the inventory button is somewhere completely different, but this brings up a different point. Most of the keys are in one 'bunch' (Q, W, A, S, D, E, Z), so it is unexpected that a button on _the other side of the keyboard_ would unpause the game.

Since you're so insistent about having the inventory key unpause the game, how about just making all keys unpause it?

(I personally would prefer to have a setting that can switch it on, but leave it switched off by default).

**Comment by wilkgr76** [comment]
Oops, wrong button.

**Comment by DS-Minetest** [comment]
As much as I know, `i` doesn't close only inventory and pause menu but also every else formspec.
=> This seems to be because of consistence.
Perhaps you are true, I'm undecided now.

> (I personally would prefer to have a setting that can switch it on, but leave it switched off by default).

Or a setting where you could decide which keys can close it (additional to esc?), I think perhaps also @Wuzzy2 would like this since he doesn't like hardcoded keys.

**Comment by rubenwardy** [comment]
It's not that much of an issue - if you write a PR that makes the code nicer and more consistent, then it'll probably be merged
