### ISSUE TITLE
Night Mode for mini map

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5291]
The minimap is to bright at night. I suggest to dim the colors at night

![screenshot_20170221_211845](https://cloud.githubusercontent.com/assets/16163058/23183221/99be088e-f87b-11e6-8013-863b607d256d.jpg)

**Comment by kaeza** [comment]
This should be optional somehow. It may be useful for mods to provide some kind of "night vision" for the minimap.

**Comment by DS-Minetest** [comment]
- If the minimap is dark on night you can't see anything on it.
- The main menu is always bright, this is consistent.
- The map is not always rewritten by Sam to make it look dark at night.
- You can't see clouds on the minimap.

**Comment by MarkuBu** [comment]
The minimap should just be darker at night because it hurts in the eyes and maybe you need to turn it off because you don't see much from the game. I can't find the English word for what I mean

**Comment by numberZero** [comment]
> The map is not always rewritten by Sam to make it look dark at night.

Yes, but there is little light at night. It might use the light level of the node Sam stands in)

> This should be optional

Sure.

**Comment by MarkuBu** [comment]
>  It might use the light level of the node Sam stands in

I think that it is no good idea. It would be black in a cave and the brightness would change all the time if you walk e.g. through a forest

**Comment by dsohler** [comment]
Are we really discussing something looking as good and consistent as this?

![screenshot_20170223-082007](https://cloud.githubusercontent.com/assets/1668792/23248723/2cdbf560-f9a1-11e6-885c-f81fd7e60fad.png)

**Comment by MarkuBu** [comment]
I like it

**Comment by paramat** [comment]
It's a case of being blinded by the minimap, as MT nighttime is so dark, so it doesn't necessarily need to be as dark as night, but dimmed a little. However, at nighttime the player may be indoors in a bright place, so a very dark minimap would also not be good. Maybe a slight automatic dimmig at night?
Detecting light at player position will just cause annoying brightness changes in the minimap and is over-complex for this issue.

**Comment by MarkuBu** [comment]
Hm, just dim at night would also mean that you know if it is day or night if you are underground. Maybe that's not necessarily wanted

**Comment by dsohler** [comment]
> However, at nighttime the player may be indoors in a bright place, so a very dark minimap would also not be good.

Since the minimap has no indoor navigation this should not be an issue. The dimming should only be applied to the regular mode and not the "radar mode" you can use in caves.

**Comment by paramat** [comment]
it could be a large outdoor brightly-lit area, which is common.

**Comment by dsohler** [comment]
Just look at the screenshot to see how light could be dealt with.

**Comment by paramat** [comment]
:-1: No need as the minimap can be hidden if it blinds in a dark location, and at night players are often in bright locations.
