### ISSUE TITLE
Lighting glitches on borders (temporarely)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5295]
**Important**: those glitched shadows go away: 
* after going away from place for some time and coming back
* after flying near it in some specific way
* after punching 
* after reloading map. 

So it usually fixes itself. I still think I can report this :)

How I reproduced? Flat mapgen with seed 5065288349354300950. 
Scenarios:
* placing a block at 16 x 16 - gives this view at least **since 0.4.13**:
![kek2](https://cloud.githubusercontent.com/assets/16494741/23275540/91d9918e-fa0f-11e6-9739-6956cba9c351.png)
* pillaring it up and making 3x3 mushroom top with Y=15.5 when you stand of it, now place another layer of blocks above, hover near it and start removing them one by one (look at this demo gif https://imgur.com/a/N4Qdo). Earlier it was hardly visible and slightly different effect in different configuration of blocks but **after commits from** https://github.com/minetest/minetest/pull/4655 (oct 27 2016) it got like this on picture and persists today.
![kek4](https://cloud.githubusercontent.com/assets/16494741/23275674/196f5a34-fa10-11e6-9a31-b950f1e7749d.png)
* spotted it in wild (v7):
![bug](https://cloud.githubusercontent.com/assets/16494741/23481800/7b399f8a-fed5-11e6-821f-66572a751c73.png)
* spotted it on actual server (BuildersWorld by Telesight)
![default](https://cloud.githubusercontent.com/assets/16494741/23573194/df16997e-007c-11e7-997d-c3a173536622.png)

Even applying https://github.com/minetest/minetest/pull/4967 does not affect those :) @juhdanad will probably be interested.

**Comment by Thomas--S** [comment]
I can confirm this bug. It happens especially often with the street lights of streets 2.0 mod on my server.

**Comment by paramat** [comment]
I guess these are not visible with smooth lighting off?
