### ISSUE TITLE
Force dropped items out of solid nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5297]
An annoying issue is that dropped items can somehow end up inside solid nodes.
The most obvious scenario for this is when a falling node such a sand falls on dropped items.
But players can also just easily build on them as well.

For the player it seems the items are gone but they simply stay at the place. When you remove the block, the item becomes visible again.

The problem with this is also that many dropped items can end up pointlessly inside solid nodes. The players may be unaware of their existance,. This means that these dropped items just increase the number of entities in the world for no benefit, until they get either removed by the item entity TTL (which takes long) or a player find it again (which is unlikely).

So, my simple idea is to force items out of blocks when they are inside a solid node.
“Solid node” is here defined as any `walkable` node with a full cube collision box (1×1×1 collision box or larger), and a “free” node is any node that is not solid and not `ignore`.

When the item is in a solid node, it should look at its direct node neighbors: left, right, front, back and up. It first checks if and of the left, right, front or back nodes are free. If there is, it will start moving towards the node with the closest distance to “freedom”. If all 4 sideway nodes are not free, the item will move upwards, but only if the node above is not `ignore`. In that case, the item does not move until the area above is loaded. This is to prevent items floating into unloaded areas or even out of world boundaries.
The algorithm terminates as soon as the item's selection box is completely outside of any node's collision box, then the normal item physics apply (i.e. gravity).

This algorithm implies that items are still stuck inside a node if they are stuck in solid rock and are directly below `ignore`. If they are at the top of the world, they are stuck in the node forever
This also means items can not move out of map boundaries (e.g. the top of the world).

My algorithm may not be perfect. First, I have no idea how seriously this would affect performance if there are many dropped items stuck inside somewhere.
Second, it does not handle cases where items get stuck into stairs and slabs, but maybe you have an idea on how to handle this.

**Comment by bigfoot547** [comment]
Yes. It is terribly annoying.

**Comment by sofar** [comment]
https://github.com/minetest-mods/droplift may be of help

**Comment by tenplus1** [comment]
My own fork of builtin_item already does this: https://github.com/tenplus1/builtin_item

**Comment by paramat** [comment]
Hmm this would need each object to regularly detect surrounding world and move. Maybe this expulsion of the object should be in falling code instead so that it happens only once and during the most common cause?

**Comment by Wuzzy2** [comment]
Are you sure this will catch all items possibly get stuck in a solid node?

Besides falling nodes, there are many other ways:

* `setpos`
* Player places block at item position
* `minetest.add_item` into solid node
* (probably more)

I think under your approach it is still very likely that items are stuck in solid nodes forever because they aren't updated.

**Comment by paramat** [comment]
Yes my suggestion only addresses one cause, but is more lightweight.
Perhaps your suggestion will be ok if made very simple and triggered not too often.

**Comment by tenplus1** [comment]
The builtin_item fork already checks for nodes at item position and if it is resting within a solid node it will quickly do a find_node_near search for 'air' and move item to that position.

**Comment by Wuzzy2** [comment]
@tenplus1 and is it efficient?

**Comment by tenplus1** [comment]
Yes, very much so as original builtin_item checks node below item and item position whereas this fork does one check and only does the other when needed.

**Comment by Fixer-007** [comment]
I support this.

**Comment by Wuzzy2** [comment]
This has been implemented in <https://github.com/minetest/minetest/pull/8885>.
