### ISSUE TITLE
(mgv7) Y borders of biomes should be blended

### ISSUE THREAD

**Issue by verymilan** [minetest/minetest#5308]
Hi there, i hope this is not just some stupid misconfiguration by my self.
I adjusted the map metafile and changed alot of biomes from the ethereal mod.

However, i am really sad about the ugly Y borders when defined.
Even overlapping max_y does not really help.
This effect is not everywhere but way too often.

Example:

![i1](https://cloud.githubusercontent.com/assets/10698140/23334687/4cd8f610-fba4-11e6-919d-106de0e10964.jpg)

![i2](https://cloud.githubusercontent.com/assets/10698140/23334686/4ca620c8-fba4-11e6-8869-809a82de5ef3.jpg)

kind Regards

**Comment by MarkuBu** [comment]
It's not your confirmation. This was discussed before somewhere

**Comment by tchncs** [comment]
Oh i hope i did not create a duplicate.
The only discussion i know (and created and found) was in the forum.. .

**Comment by MarkuBu** [comment]
Maybe it was in the forum. I just remembered a discussion about this topic

**Comment by paramat** [comment]
Yes this is the expected behaviour, i did at one time try vertical biome blend but had some problems. For example at sea level you would want a straight border to match water level, so how to make this optional?

**Comment by tchncs** [comment]
What if it only blends when the Y settings are overlapping?

* biome a: min: 1 max 14
* biome b: min: -4 max 6

**Comment by paramat** [comment]
Well we have biomes with overlapping y limits already, not sure if or how this could trigger vertical blend.

Anyway see #5316

**Comment by paramat** [comment]
I'm trying another implementation that adds new biome parameters to define the vertical height of the biome blend, it works.
Note that if you have a vertical biome blend of 4 nodes (not much) you get large ugly dithered areas on the flatter land:

![screenshot_20171228_234454](https://user-images.githubusercontent.com/3686677/34426065-93bbe43a-ec2a-11e7-856b-3d0da34cf68c.png)

![screenshot_20171228_234639](https://user-images.githubusercontent.com/3686677/34426069-9ae0656a-ec2a-11e7-85dc-316d715f70e3.png)

**Comment by paramat** [comment]
#6853 merged.
Will probably add some blending to MTG.
