### ISSUE TITLE
Items drop when a stack of falling nodes impacts ground at high speed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5313]
If you have a large stack of falling nodes (such as sand), and then dig a solid node below it (such as dirt) so that all the falling nodes fall down a deep hole, it is likely some of the falling nodes will drop as items instead of properly becoming nodes at the end again.
When you make 10 nodes fall at a height of 10 nodes, usually at least one item drops, so that only 9 nodes appear at the bottom. This number appears to vary often.

You can see good screenshots here:
https://forum.minetest.net/viewtopic.php?f=6&t=16702

Tested in version 0.4.15. Happens in all subgames I've played so far without exception.

**Comment by sfan5** [comment]
Sounds like a feature to me

**Comment by wilkgr76** [comment]
@sfan5 "It's a feature, not a bug" LOL

**Comment by CasimirKaPazi** [comment]
collide_with_objects = true,

This fixes it.

**Comment by DS-Minetest** [comment]
> `collide_with_objects = true,`

Wouldn't then the falling objects stay on the head of the player if he's beyond?
Also would that reduce the velocity of them if they collide in fall?

**Comment by CasimirKaPazi** [comment]
Both true, but isn't that the way it should work? Behaving like real falling objects, not some ghosts passing trough.

**Comment by paramat** [comment]
'collide with objects' might make falling more intensive, which could be significant with large numbers of falling nodes.

**Comment by CasimirKaPazi** [comment]
Actually it makes it better. Without all nodes are landing simultaneously and cause all to be placed at about the same time. With ```collide_with_objects = true``` the above node only gets placed after the one below, spreading the load.

I tried it with 20000 nodes falling at once. Without the change Minetest froze instantly, with the change I had ~1fps but it still progressed. I would also recommend adding again the delay we once had in falling update for the same reason.
