### ISSUE TITLE
ItemStack meta: from_table() doesn't work

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#5314]
I've been working on updating MTG to use some of the new features introduced by the new key-value ItemStack meta. I've noticed that the `:from_table(<table>)` function does not seem to work. Rather than importing the wanted table, the ItemStack's meta is entirely cleared. I've had to write my own function to loop through the table and add the items one-by-one, which not only adds extra code but also loses data types (i.e. `int` converts to `string`).

I'm not quite sure as to what is causing this issue, or if I'm just really doing something wrong, so I'll include both the problematic code and my solution.

**Problem:**
```lua
local meta = itemstack:get_meta() -- default/craftitems.lua line 17
local data = meta:to_table()
-- Make Changes
...

-- Update
meta:from_table(data)
```

**Solution:**
```lua
local function from_table(stack, table)
	local meta = stack:get_meta()

	for _, i in pairs(table) do
		meta:set_string(_, i)
	end

	stack:set_metadata("")
end
```

**Comment by rubenwardy** [comment]
I can't reproduce this

```lua
local stack = ItemStack("default:stone")
stack:set_metadata("hello!")
stack:get_meta():set_string("foo", "bar")
stack:get_meta():set_string("description", "Hello everyone!")

do
	local meta = stack:get_meta()
	local data = meta:to_table()
	data.fields.bleg = "sldmslmdsd"
	meta:from_table(data)
	print(dump(stack:get_meta():to_table()))
end

{
	fields = {
		[""] = "hello!",
		bleg = "sldmslmdsd",
		description = "Hello everyone!",
		foo = "bar"
	}
}
```

**Comment by octacian** [comment]
Ah, I think I found the issue. It appears as though I'm just confused as to exactly how the data is stored in meta. From your code above, it would appear as though all of the data is stored in the `fields` "sub-table.' With that in mind, I will close this issue. Thanks!
