### ISSUE TITLE
Remove celeron55's email in lua_api.txt

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5322]
I think this is outdated and should be changed to a Github PR

> If you see a deficiency in the API, feel free to attempt to add the functionality in the engine and API. You can send such improvements as source code patches to <celeron55@gmail.com>.

**Comment by sfan5** [comment]
Making a PR is as easy as creating an issue, why haven't you done it yourself?

**Comment by MarkuBu** [comment]
I have less time then it might look. A lot of posts I make are written on a smartphone, like this one

**Comment by kaeza** [comment]
Didn't @celeron55 keep that because people still contact him via e-mail?

**Comment by paramat** [comment]
There are lots of issues for improvements needed for lua_api.txt, we should link all these issues from a new issue to fix many at once.

**Comment by paramat** [comment]
Fixed in #6434
