### ISSUE TITLE
Falling nodes of “node box” type don't rotate properly

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5324]
If you have a falling node from a node with a nodebox appearance with a nodebox which can rotate (thanks to `facedir`), the falling node is sometimes incorrectly rotated when it falls.
Example: If you have an anvil node box, and it drops, for some orientations, the anvil gets rotated back to its default orientation while it falls. When it reaches the bottom and becomes a node again, the orientation is OK again.

Tested in Minetest 0.4.15.
I discovered this bug while developing MineClone 2. To test this, you can try to place an anvil from the creative inventory in MineClone 2 version 0.13.0 and make it fall. Test it with different orientations.

My guess: Minetest simply ignores the facedir when rendering the falling node.

**Comment by stujones11** [comment]
The problem is that falling nodes are `wielditem` entities which can only be rotated around the y-axis. This could only be fixed if entities were to support pitch and roll.
