### ISSUE TITLE
Allow to tweak the “friction” (braking distance) when falling into liquids and climbable nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5326]
In very old versions of Minetest, when you fell into a climbable node (e.g. ladder) or a liquid (e.g. water), your fall came instantly to a halt, making them useful as “stoppers” in deep shafts.

As of 0.4.15, all climbable nodes and liquids reduce the downwards speed instead when you drop into them.
While this behvaiour is of course 100% legit, I think it may be interesting to get the old Minetest behaviour back; it might be useful for some subgames (like MineClone 2).

I suggest to add a field to the node definition to tweak the slowing down effect:

    fall_stopping_factor = <number>

`<number>` is a floating-point factor which multiplies how much the player is slowed down when falling into a falling node, compared to the default value. The default value is `1`.
If the value is `"inf"` (or some other special value), the player stops instantly, thus recreating the old Minetest behaviour.
If this field is used on something which is neither a liquid nor climbable, it has no effect.

Examples:

* `1` means there is no change from the 0.4.15 behaviour which is why it is the default
* `2` means the player is twice as “strong” slowed down on this particular node. As a consequence you come to a halt earlier and the “braking distance” is lower
* `0.5` means the player is half as “strong” slowed down. As a consequence you come to a halt later and the “braking distance” is higher
* `0` and negative values should be discarded as invalid

If for some reason this new field is not possible for liquids like I explained, we can discuss about a different implementation for liquids which differs from climable nodes.

**Comment by DS-Minetest** [comment]
> If the value is `"inf"` (or some other special value), the player stops instantly, thus recreating the old Minetest ~~behaviour~~ behavior.

What about `0` or `-1` instead of `"inf"`?

**Comment by Wuzzy2** [comment]
I don't really care which value is considered special as long it is different from all other values.

**Comment by DS-Minetest** [comment]
Btw, liquids can have different viscosity, right? Doesn't this already affect the "friction"?

**Comment by Wuzzy2** [comment]
Sadly, viscosity is used for two things:

* How fast you can swim in it
* How fast it flows

This limits the amount of customization subgame authors can do.

Also, if I just set a very high viscosity for water, it will be almost impossible to swim in. The point of this suggestion is to allow players to come instantly to a halt when falling into a liquid in order to recreate the gameplay of very old Minetest versions while retaining the current swimming speed.

**Comment by paramat** [comment]
:-1: The deceleration is obviously dependent on viscosity so i would prefer using that value to determine it.

**Comment by Wuzzy2** [comment]
Background: This feature will be required for MineClone 2, a Minecraft clone.
Would the feature have more chances if I submit a PR?

**Comment by paramat** [comment]
It wouldn't change my opinion.
I'm surprised MC still stops a player instantly in water.
Personally i don't see one small feature in a MC clone enough justification for adding a new nodedef.

**Comment by DS-Minetest** [comment]
You could give as reason for the instant break the water surface tension but then you would also get falling damage on entering water.

**Comment by XtremeHacker** [comment]
If it is configurable, what is really wrong with adding this?

**Comment by paramat** [comment]
The deceleration in a liquid is obviously dependent on the viscosity, so we don't need another parameter, and imitating MC is no justification fo it.
