### ISSUE TITLE
get_pointed_thing()

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5328]
Get the highlighted node, item or whatever is pointed to without punch or use

**Comment by SmallJoker** [comment]
Please explain further. Would you like to have a Lua function to get the pointed thing of a player whenever a mod requests it?

**Comment by MarkuBu** [comment]
Yes, I'm sorry. A lua function to get the pointed node

**Comment by juhdanad** [comment]
See #4421.

**Comment by stujones11** [comment]
Since this information is already available in the F5 debug info, I would expect there should be a way to this entirely client-side, maybe CSM can help here?

**Comment by MarkuBu** [comment]
@juhdanad I would still have to calculate a "virtual" point because the server doesn't know in which direction I'm looking and you have to pay attention for head bopping and other modifications of the camera position.

I think this is better done client side

**Comment by sorcerykid** [comment]
From my research pointed node information is only passed to the server during user interaction (punching, digging, etc.) by the client via the Server::handleCommand_Interact(NetworkPacket* pkt) method in network/serverpackethandler.cpp. So it is built into the client-server protocol. There is no way to natively obtain the pointed node coordinates exclusively from the server-side without a lot of hacking.

**Comment by stujones11** [comment]
> I think this is better done client side

Then it will probably have to wait for CSM as mods are currently server-side, there is no way to implement `get_pointed_thing` that works purely client-side without a lot of klugdery.

It is, however, quite possible to obtain the current pointed node using `line_of_sight` which is actually quite efficient and effective, though you would need to poll it.

**Comment by MarkuBu** [comment]
Of course line_of_sight could be used, but it is difficult to get the start and end positions.

**Comment by stujones11** [comment]
It is not difficult, at least IMO. Simply obtain the player look direction as a unit vector, multiply it by a given max distance then add the player pos and eye-offset, that gives you the end position. The start position is obviously just the player current pos plus the eye-offset. Of course this method may suffer from the effects of server lag but so would any other server-side implementation.

**Comment by sorcerykid** [comment]
What is the recommended stepsize? According to the wiki, "smaller gives more accurate results but requires more computing time". That doesn't inspire much confidence in the efficiency of this function :P

http://dev.minetest.net/minetest.line_of_sight

**Comment by stujones11** [comment]
I use this method extensively in my shooter mod with the default stepsize and find the accuracy quite acceptable, in singleplayer, at least without the problem of lag.

**Comment by sorcerykid** [comment]
It might be worthwhile then to simply add a core.get_pointed_thing( ) function to builtin/misc.lua using the method you described above.

**Comment by stujones11** [comment]
There may be a problem with mobile devices using this method, I'm not sure. This technique only really tells what node you are looking at which may or may not be what is actually being pointed at.

Really, this is best done with CSM when it eventually happens, there does seems to be some progress there recently.

**Comment by sorcerykid** [comment]
Excellent point, thanks for mentioning that! I hadn't considered the potential discrepancy for users with touchscreens. I do hope that something can be done client-side at some point.

**Comment by stujones11** [comment]
> I do hope that something can be done client-side at some point.

Failing that, #4421 would solve the above mentioned problem and possibly even work with objects.

**Comment by MarkuBu** [comment]
#5394

**Comment by nerzhul** [comment]
CSM can have it easily, as we already have this information in debug string when shown :)

**Comment by sorcerykid** [comment]
Another alternative is that the client pass the pointed_thing position within a new (or existing) packet, but that would require changes to the client-server protocol which could impact compatibility.

**Comment by SmallJoker** [comment]
#4421 merged.
