### ISSUE TITLE
Digging an airlike node creates “unknown node” particles

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5331]
When you dig an `airlike` node, you will see “unknown node” particles (`unknown_node.png`). This should never happen.

Why do I want to dig `airlike` nodes? Easy: Let's suppose I want to make an invisible but walkable, pointable and diggable block (e.g. invisible barrier), then I need this.

Example:

    minetest.register_node("example:barrier", {
        description = "Barrier",
        drawtype = "airlike",
        paramtype = "light",
        inventory_image = "example_barrier_logo.png",
        wield_image = "example_barrier_logo.png",
        stack_max = 64,
        sunlight_propagates = true,
        is_ground_content = false,
        groups = { cracky=3, },
    })

It is possible to create a workaround for this: Just add “`tiles = { blank.png }`” to the node definition. Then no particles appear. But I don't like this workaround and it is ugly. Unknown node particles should normally not appear.

Tested in 0.4.15.

**Comment by paramat** [comment]
I guess airlike nodes should not create any dig particles unless tiles are specified.
