### ISSUE TITLE
Per-node climbing speed factor

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5333]
My suggestion is to add a new field to node definitions for climable nodes.
It is a factor to multiply the default climbing speed of the player when climbing this particular node. It shall be `1` by default.

Use cases:

* Faster steel ladders in Minetest Game: https://github.com/minetest/minetest_game/issues/1600
* A mod which adds “turbo ladders” with a 3× climb speed as a simple and leightweight alternative to the infamous sneak elevators

**Comment by paramat** [comment]
Similar to #1935

**Comment by paramat** [comment]
No longer needed for a sneak ladder replacement as we provide sneak ladders in new code.

**Comment by Wuzzy2** [comment]
You're right. This suggestion is almost identical to https://github.com/minetest/minetest/issues/1935.
I close this.
