### ISSUE TITLE
Shaped recipes ignore empty space

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#5336]
When creating two shaped recipes using the same formation of the same material on different locations the first recipe gets overwritten by the second even if logically it is a different recipe.

### Example/proof

Create this mod:

~~~~
-- definition A
minetest.register_craft({
	output = 'default:stone',
	recipe = {
		{'default:cobble', 'default:cobble', ''},
		{'',               '',               ''},
		{'',               '',               ''}
	}
})

-- definition B
minetest.register_craft({
	output = 'default:stick',
	recipe = {
		{'',               '',               ''},
		{'',               'default:cobble', 'default:cobble'},
		{'',               '',               ''}
	}
})
~~~~

Now craft definition B (a shaped recipe with cobblestone at position 5 and 6 to return one stick). Result:

![b](https://cloud.githubusercontent.com/assets/1668792/23567354/3325658a-0056-11e7-938d-45411c2ba3fe.png)

As expected, the result is one stick as defined for the shaped recipe with cobblestone at positions 5 and 6 and all other slots are empty.

Now try to craft definition A (a shaped recipe with cobblestone at positions 1 and 2 to return one stone). Result:

![a](https://cloud.githubusercontent.com/assets/1668792/23567433/7d6a1a6e-0056-11e7-9046-4f59cdf4ce96.png)

As you can see other than expected for the shaped recipe that was defined a stick is being returned instead of a stone.

The first shaped recipe got overwritten by the second shaped recipe that is different from the first one.

**Comment by sfan5** [comment]
They all called `shaped` because only the shape matters, not where on the crafting grid the items are placed.
