### ISSUE TITLE
Control-click as right click does not function on macOS

### ISSUE THREAD

**Issue by gituser2194** [minetest/minetest#5341]
On macOS, pressing the control key while clicking right clicks, but it doesn't in Minetest. Because of the way I like to keep my trackpad configured, I must change the settings every time I play MT and change them back when I am done.

Relevant macOS setting:

![screen shot 2017-03-04 at 12 17 38 pm](https://cloud.githubusercontent.com/assets/24639916/23580711/94b2654a-00d4-11e7-90d3-50d1d5516764.png)

Minetest version:

![screen shot 2017-03-04 at 12 19 02 pm](https://cloud.githubusercontent.com/assets/24639916/23580723/c880c524-00d4-11e7-8d8f-e9459ecb1876.png)

**Comment by davisonio** [comment]
This bug seems to be fixed.

Command + Click works as a right click on macOS Sierra and latest Minetest dev. Can you confirm @gituser2194?

**Comment by rubenwardy** [comment]
Is this still the case on 5.5.0?

**Comment by SwissalpS** [comment]
I recently had the chance to test newest version on one of the newest MBPs. I can't exactly remember if control clicking worked but I had real dificulties asigning my keys correctly.
For example the key next to the left shift was recognized as F5 and some keys on the right part of the keyboard were treated as numpad keys.
Additional quirks happened when I wanted to type chat messages and had to change keyboard layout to something that worked.

Possibly the key mappings work for standard US layout but not for dvorak or DE_CH.
Unfortunately I didn't have much time for proper debugging and can't get my hands on another MBP to do so.

**Comment by sfan5** [comment]
Thanks for testing but what is "the website"? All macOS builds of Minetest are community-made.

**Comment by SwissalpS** [comment]
https://forum.minetest.net/viewtopic.php?t=9190 >> https://github.com/krondor-game/minetest/releases

**Comment by sfan5** [comment]
Ah, that's hopelessly outdated so that's unfortunately no help.

**Comment by SwissalpS** [comment]
ouch, so sorry.
