### ISSUE TITLE
Support facedir for connected nodeboxes

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#5342]
@Ekdohibs raised this concern when connected nodeboxes were first proposed/coded (https://github.com/minetest/minetest/pull/3503#issuecomment-192865950), but it apparently needs re-addressed, as it doesn't work anymore (did it ever?).  A node that could theoretically connect to its neighbors may, in some cases, also need facedir or perhaps colorfacedir.

Someone's going to ask for a use-case, so consider signs_lib signs, particularly the ones on a fencepost (let's not get into a discussion about how they display their text :stuck_out_tongue_closed_eyes:), which consists of a couple of "fixed" nodeboxes for the sign and its fencepost.  Placing such a sign, then exiting the world, adding connected nodeboxes to the node def, and then starting that world again causes the already-in-place sign (or rather, its "fixed" nodeboxes) to rotate to a hard-coded orientation, and the textures get messed up.

The sign should be able to connect to its neighbor fenceposts from the left, right, and/or back, regardless of its rotation (ideally, one only wants to rotate one of these around the Y axis, and keep it upright, since the text won't display right otherwise, anyway).

**Comment by paramat** [comment]
@sofar ?
I get the feeling there is a good reason for this.

**Comment by paramat** [comment]
@sofar ^

**Comment by sofar** [comment]
I never considered this usage. Nodebox nodes can certainly be rotated, but I don't remember any specific code to handling facedir values in connected nodeboxes. Definitely never worked, too, as far as I remember.

**Comment by paramat** [comment]
It would get confusing too since connected nodeboxes 'connect' in particular directions. If the node is rotated, do the connection directions rotate too or not? Seems it would make the code a nightmare. Best to just create a new connecting node.
