### ISSUE TITLE
Better input: Abstracting type of binding from the rest of the game

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#5348]
I can envision a system where only the input manager cares if a binding is a key, joystick, touch screen or mouse event.

![dsc_0105](https://i.rubenwardy.com/EiFdWmUTgg.JPG)

Left is before, right is after

```cpp
// proposed InputManager API
class InputManager {
public:
    float getValue(InputType type);
    // 0 if off, 1 if on, decimal if input is analogue

    bool wasJustActivated(InputType type);
    // ^ whether the input became active since last tick,
    //    eg the key was only just pressed

    V2f getLookDelta();
    // Eg: from mouse or joystick movement

    V2f getMoveVector();
    // Helper function to interpret MOVE_LEFT etc actions
};
```

What do you think of this proposal?

**Comment by Wuzzy2** [comment]
The current input system is a huge clusterfuck and badly needs rework. Any improvement of that is a plus. While we're at it, can we also throw away the extremely outdated controls configuration menu and redo it from scratch?

It looks like the new system will allow to bind keys and mouse and joypad actions to anything relatively easy, which is very important. Minetest has way too many hardcoded keys which need to be made configurable.

I wonder what you envision about the clusterfuck that is the rightclick. It is so deeply entrenched and hardcoded into Minetest, it almost makes my heart bleed. I mean, we even have a Lua API function which is *called* `on_rightclick`!

PS: This PR feels left behind: https://github.com/minetest/minetest/pull/4929 :-(

**Comment by dsohler** [comment]
> Minetest has way too many hardcoded keys which need to be made configurable. Allowing to rebind all the actions (not just a few selected) is good for improving accessibility.

Quoted for emphasis.

**Comment by est31** [comment]
While I'd generally be in support of such an abstraction, I'm not sure whether its doable without cost. I mean, you'll still have vast differences between how touch screens are supposed to be used and mice. Like in the touch screen you double tap to open a chest, with the mouse you right click. I don't think double left clicking should open a chest when using a mouse just for the sake for that abstraction.

**Comment by rubenwardy** [comment]
The touch screen would simulate an ACTION_RIGHTCLICK when you double tap, and the mouse would do it on a right click. And other examples

**Comment by ClobberXD** [comment]
I'd really love to see this in action. Abstracting key-binds creates so many new possibilities like mods registering their own keybinds, and getting notified of the relevant key-press through a callback, etc.

**Comment by sbrl** [comment]
I assume this was closed because it was implemented, @rubenwardy?
If so great work!
