### ISSUE TITLE
Customize lava height

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5352]
Currently, the height at or below lava lakes can appear in Minetest (0.4.15), as generated by the stock map generators, is hardcoded.
In v6, it is at Y=-32 or below and in all other mapgens it is at Y=-273 or below (if I'm not mistaken).

This is clearly bad that the lava height is hardcoded like this, it makes it unneccessarily hard for modders and subgame authors to tweak the mapgen to their needs.

I suggest to allow modders and/or players to modify this with a mapgen setting.

Mapgen progress:

* [X] v5
* [ ] v6
* [X] v7
* [X] flat
* [X] carpathian
* [X] fractal
* [x] valleys (kinda done, but confusing, see below)

**Comment by Wuzzy2** [comment]
Progress has been made. Okay. Right now we have dedicated lava height settings for these mapgens: v5, v7, flat, carpathian, fractal

The mapgens v6 and valleys do not have such a setting yet.

**Comment by Wuzzy2** [comment]
Hmm. I noticed something odd. I think for v7 the lava height was previously hardcoded at Y=-273.

But `mgv7_lava_depth`'s default value is at Y=-256. Is this inconsistency an accident?
Does this mean that 0.5.0 could break 0.4.16 worlds because of this?

**Comment by paramat** [comment]
Valleys is done:
`lava_max_height = water_level + MYMAX(0, lava_features_lim - 4) * 50;` it is set by the 'lava features' parameter, although that is not a straightforward y value, maybe it should be but i'll leave that to @duane-r 

Mgv6 could be done but i'm not sure as it has always been that way, needs to be requested more.

**Comment by paramat** [comment]
Lava depth is per-mapchunk as the large caves are generated per-mapchunk, so setting it to -256 actually creates lava caves that can reach down to mapchunk base at -272, so it's essentialy the same setting but better expressed instead of a value dependent on a mapchunk size of 80.

**Comment by paramat** [comment]
Mgv6 is a preserved stabel mapgen and i can't be bothered adding a lava height setting, players have told me they like the way lava is so close to the surface.
