### ISSUE TITLE
Tie time_speed setting to world

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5353]
I frequently use `/set time_speed 0` to stop the sun for development and testing.
But I also happen to just play, where I of course want the normal day/night cycle.

Too bad that this setting appears to be global and stays the same even if I change the world. So I have to give myself the `server` priv just to start the day/night cycle again.

I think it makes a lot of sense if the `time_speed` setting is instead saved per-world, and not globally, so that users can have development/testing worlds, or worlds with a different sun speed, etc. without being forced to manually adjust the speed each time after switching worlds.

Into `minetest.conf`, another setting could be added with the name `time_speed_default`. This is a global setting which contains the default `time_speed` to be used for new worlds. It is of cours `72` by default.

**Comment by rubenwardy** [comment]
Minetest.setting_set and /set should set per world, not globally

**Comment by paramat** [comment]
Ther are many settings that perhaps should be per-world, and some higher priority than this one, such as mapgen limit.

**Comment by sofar** [comment]
For this very reason I run all my servers with something like `--config server.conf`, and I have no idea if `/set` even would write to the correct alternative location.

**Comment by dsohler** [comment]
> Ther are many settings that perhaps should be per-world, and some higher priority than this one, such as mapgen limit.

Too bad none of the devs really thinks this would worth some time and so no-one is going to ever implement this.

**Comment by sofar** [comment]
@dsohler If you're just here to spew ad hominem nonsense, then please stop. You have 2 devs already commenting in this thread that they agree.

**Comment by dsohler** [comment]
> If you're just here to spew ad hominem nonsense, then please stop.

Currently there are 866 open issues and 185 pull requests.

**Comment by paramat** [comment]
I'm not sure time speed is always wanted to be per-world, it's debateable and i'm not necessarily opposing. What i'm saying is that there are others of higher priority and it's difficult to decide the dividing line.

**Comment by paramat** [comment]
We are well aware.

**Comment by sofar** [comment]
> I'm not sure time speed is always wanted to be per-world

well it's certainly never wanted for all worlds at the same time (which 
is what it does right now).

**Comment by paramat** [comment]
Ii is sometimes, i have a favourite time speed which i alter sometimes, and want this to apply to all my singleplayer worlds. But then in other situations and for server worlds per-world makes sense, so that's why i think it's not so obviously a per-world thing, like 'map-generation-limit' is.

**Comment by Wuzzy2** [comment]
@paramat:

> Into minetest.conf, another setting could be added with the name time_speed_default. This is a global setting which contains the default time_speed to be used for new worlds. It is of cours 72 by default.

**Comment by paramat** [comment]
Anyway, do we have the ability to set a subset of settings for a world? This would be ideal instead of trying to decide for each setting whether it is best global or per-world.

**Comment by dsohler** [comment]
> do we have the ability to set a subset of settings for a world?

[According to the wiki](http://wiki.minetest.net/Maps#env_meta.txt) there is `env_meta.txt` being used for "Simple global environment variables". Or `map_meta.txt` for "Simple global map variables" or `world.mt` for "World metadata".

The only thing that has to b decided is, where to put time speed information? According to the example data given in the wiki `env_meta.txt` would be okay, because there already time-related things stored. But it would also fit into `map_meta.txt` or `world.mt` because to me time speed isn't actually an environment variable but more like a meta information about the map or the world in general.

But YOU are one of the devs. You should already know this :smile:

**Comment by rubenwardy** [comment]
I'd just put it into worldname/minetest.conf.

**Comment by dsohler** [comment]
Why introduce another file if there are already several files this could be placed into?

**Comment by rubenwardy** [comment]
because I think the correct fix is to make all settings set by /set or minetest.setting_set world specific

**Comment by dsohler** [comment]
But wouldn't it be `worldname.conf` instead of `minetest.conf` since you configure the world and not Minetest itself.

**Comment by paramat** [comment]
> another setting could be added with the name `time_speed_default`

I feel we have enough settings, let's not start duplicating every one that is made per-world.

**Comment by rubenwardy** [comment]
> But wouldn't it be worldname.conf instead of minetest.conf since you configure the world and not Minetest itself.

Nope, see gameid/minetest.conf

**Comment by paramat** [comment]
> I'd just put it into worldname/minetest.conf.

Seems ideal, then you can make any setting per-world without us having to decide whether a setting should be global or per-world.

**Comment by Wuzzy2** [comment]
`worldname/minetest.conf` sounds good.

**Comment by dsohler** [comment]
> nope, see gameid/minetest.conf

Okay, then call it `minetest.conf` but allow ALL settings that can be set in regular `minetest.conf`, too.

**Comment by Wuzzy2** [comment]
Closing in favor of the more generalized issue #6966.
