### ISSUE TITLE
Doc not consistant. sometimes == is used instead of = 

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5354]
Is there any reason that in this section a == is used?

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L609

For example `liquidtype == "flowing"`

In the example above it is correct

`paramtype = "light"`

It is confusing and leads to mistakes if you copy and paste the code

**Comment by SmallJoker** [comment]
With a single equal sign it's supposed to be an example, with the explanation of what it does below.
The double equal sign is rather if you want to check for something, which isn't the case in a node definition table, thus this would be more correct IMO.

**Comment by dsohler** [comment]
This document is edited by a lot of different people all bringing their own ideas, style, and arbitrary syntax ideas. It should be rewritten completely by one single person defining a proper syntax and all changes have to be approved by this one person.

No matter how weird confusing and unmaintainable the document is: In the code `==` is for boolean comparisons and `=` is for assignments. Always.

**Comment by paramat** [comment]
Yes here '=' should be used.
