### ISSUE TITLE
Another graphics engine

### ISSUE THREAD

**Issue by acterhd** [minetest/minetest#5365]
Hello. Why Minetest based on outdated Irrlitcht engine? I think come time for new engine. I for example cannot found newer Irrlitcht 1.9 version (and url unavailable). I for example can recommend Urho3D.

**Comment by sfan5** [comment]
Oh, sure. We'll just switch the engine of our codebase no problem, should be done in 5 minutes. It will be much better when it's on a different engine (also muh shaders).

----

Actual answer: **No.**

Irrlicht 1.9 is not released yet and can be found here: http://irrlicht.sourceforge.net/?page_id=140

Also I'm pretty sure this is a duplicate.
