### ISSUE TITLE
Visual Studio 2017 not compiling

### ISSUE THREAD

**Issue by acterhd** [minetest/minetest#5366]
I can't link LUA and sqlite, despite of I included and compiled. 
Unresolved symbols with `lua.lib` and `sqlite3.lib`

```
2>sqlite3.lib(sqlite3.obj) : error LNK2001: неразрешенный внешний символ "__imp__endthreadex"
2>sqlite3.lib(sqlite3.obj) : error LNK2001: неразрешенный внешний символ "__imp__beginthreadex"
2>sqlite3.lib(sqlite3.obj) : error LNK2001: неразрешенный внешний символ "__imp_rand_s"
2>lua.lib(lauxlib.obj) : error LNK2001: неразрешенный внешний символ "__imp_freopen"
2>lua.lib(lauxlib.obj) : error LNK2001: неразрешенный внешний символ "__imp_strstr"
2>lua.lib(lobject.obj) : error LNK2001: неразрешенный внешний символ "__imp_strncat"
2>lua.lib(lobject.obj) : error LNK2001: неразрешенный внешний символ "__imp_strncpy"
2>lua.lib(lstrlib.obj) : error LNK2001: неразрешенный внешний символ "__imp_strncpy"
2>lua.lib(lvm.obj) : error LNK2001: неразрешенный внешний символ "__imp_strcoll"
2>lua.lib(liolib.obj) : error LNK2001: неразрешенный внешний символ "__imp_clearerr"
2>lua.lib(liolib.obj) : error LNK2001: неразрешенный внешний символ "__imp_fgets"
2>lua.lib(ldblib.obj) : error LNK2001: неразрешенный внешний символ "__imp_fgets"
2>lua.lib(liolib.obj) : error LNK2001: неразрешенный внешний символ "__imp__pclose"
2>lua.lib(liolib.obj) : error LNK2001: неразрешенный внешний символ "__imp__popen"
2>lua.lib(liolib.obj) : error LNK2001: неразрешенный внешний символ "__imp_tmpfile"
2>lua.lib(loslib.obj) : error LNK2001: неразрешенный внешний символ "__imp_system"
2>lua.lib(loslib.obj) : error LNK2001: неразрешенный внешний символ "__imp_clock"
2>lua.lib(loslib.obj) : error LNK2001: неразрешенный внешний символ "__imp__difftime64"
2>lua.lib(loslib.obj) : error LNK2001: неразрешенный внешний символ "__imp__mktime64"
2>lua.lib(loslib.obj) : error LNK2001: неразрешенный внешний символ "__imp_tmpnam"
2>C:\dev\minetest\bin\Release\minetest.exe : fatal error LNK1120: неразрешенных внешних элементов: 18
2>Сборка проекта "minetest.vcxproj" завершена с ошибкой.
```

**Comment by SmallJoker** [comment]
Is this the same problem as in issue #4880 ?

**Comment by acterhd** [comment]
I tried recompile sqlite and change MT in lua, but anyways. 

3>LINK : warning LNK4075: не учитывается "/INCREMENTAL" из-за спецификации "/LTCG"
3>auth.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>base64.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>enriched_string.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>numeric.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>pointedthing.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>serialize.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>string.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>timetaker.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>ban.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>camera.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>cavegen.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>chat.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>client.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>clientenvironment.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>clientiface.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>clientmap.obj : error LNK2038: обнаружено несоответствие для "RuntimeLibrary": значение "MD_DynamicRelease" не соответствует значению "MT_StaticRelease" в clientlauncher.obj
3>   Создается библиотека C:/dev/minetest/bin/Release/minetest.lib и объект C:/dev/minetest/bin/Release/minetest.exp
3>LINK : warning LNK4098: библиотека по умолчанию "MSVCRT" противоречит использованию других библиотек; используйте параметр /NODEFAULTLIB:library
3>serialize.obj : error LNK2001: неразрешенный внешний символ "__imp_strtok_s"
3>string.obj : error LNK2001: неразрешенный внешний символ "__imp_strnicmp"
3>OLDNAMES.lib(strnicmp.obi) : error LNK2001: неразрешенный внешний символ "__imp_strnicmp"
3>camera.obj : error LNK2001: неразрешенный внешний символ "__imp__hypotf"
3>C:\dev\minetest\bin\Release\minetest.exe : fatal error LNK1120: неразрешенных внешних элементов: 3
3>Сборка проекта "minetest.vcxproj" завершена с ошибкой.
========== Сборка: успешно: 2, с ошибками: 1, без изменений: 4, пропущено: 0 ==========

**Comment by acterhd** [comment]
I ask question. How to use "minecraft_game" LUA libraries for?
