### ISSUE TITLE
New API: Swap node with no light update (swap opaque node)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5372]
I was thinking about how in my mods i often want tto swap a non-light propagating node with another non-light propagating node, for example in a footprints mod. This would not need a light update. I was hoping that the existing 'swap node' was a simple swap with no light update, so that i could use it, but it is not.

The light update is an intensive part of 'set node', 'remove node' and 'swap node', a new API without a light update (and probably no metadata modification) would be a faster way to modify nodes in the world.

Any interest in this? I am offering to code it.

Relevant code: The 'swap node' API calls `swap_node()` https://github.com/minetest/minetest/blob/master/src/serverenvironment.cpp#L956 which calls `addNodeWithEvent()` https://github.com/minetest/minetest/blob/master/src/map.cpp#L312 which calls `addNodeAndUpdate()` https://github.com/minetest/minetest/blob/master/src/map.cpp#L238 which calls `voxalgo::update_lighting_nodes()` https://github.com/minetest/minetest/blob/master/src/voxelalgorithms.cpp#L605

**Comment by SmallJoker** [comment]
Comparing the previous and the new node against their parameters `sunlight_propagates` and `light_source` could already be enough to skip the light calculation part.

**Comment by paramat** [comment]
Ok i'll investigate that.

**Comment by paramat** [comment]
Yes the light update does some optimisiing if old and new nodes are both opaque and the same light level, but not calling a light update at all might help.
Another possibility is not adding the node or surrounding liquids to the liquid update queue, as this API would be for non-liquid nodes.
I would need to profile such an API to see if it has a significant effect.

**Comment by paramat** [comment]
@juhdanad

**Comment by juhdanad** [comment]
I do not think that this would cause significant performance boost, as no additional nodes are checked when the new node is opaque.
Also the swapping code does other things too (for example sends map edit events).

**Comment by paramat** [comment]
Agreed.
