### ISSUE TITLE
Wheat seeds grow as cotton (wrong ABM seems to be executed on catch-up)

### ISSUE THREAD

**Issue by pgimeno** [minetest/minetest#5375]
This happens in current HEAD as of this writing (f83d868). To reproduce:

1. Plant a good bunch of wheat seeds on fertile ground (wet soil).
2. Quickly go away, far enough as for the ABM to cease executing,  ensuring that at least some of the seeds still remain as seeds and have not germinated yet.
3. Wait a minute or two, time enough that at least some of the seeds should have germinated while you were away.
4. Return, and observe that the seeds appear to germinate as cotton instead of wheat.

If it doesn't reproduce, repeat the process. It occasionally takes two tries, rarely more.

I'm using a very old minetest_game (minetest/minetest_game@00a0d9a) if that matters. I hope not.

Analysis reveals that the ABM function is called twice, one which correctly substitutes the wheat seed with a wheat plant, and another one which incorrectly calls the cotton ABM function for the same position instead of the wheat one, and apparently replaces the size 1 wheat plant with a size 1 cotton plant. That happens even if there's no cotton around.

Bisection points to commit ca362963 as having introduced this problem.

**Comment by sofar** [comment]
> I'm using a very old minetest_game (minetest/minetest_game@00a0d9a) if that matters. I hope not.

It does. We can't fix that git release. We can only fix `HEAD`. So, if the bug isn't present in `HEAD`, there's nothing to fix. You should always try and see if the bug is in `HEAD` first if you can.

**Comment by sofar** [comment]
I tried to reproduce this with `HEAD`. Planted over 500 seeds and zoned out, left for 10 minutes, then came back. I don't see a single cotton plant.

FYI, there is a mod that produces "radiation" that can mutate plants - technic. It may be the cause of your problem.

**Comment by pgimeno** [comment]
Thanks for your reply. I don't have technic installed. The only non-core mod I had active was worldedit.

To be clear, when I said "if that matters", I meant for reproducibility. You're right, I've tried with current head and the repro doesn't work there. But it's still reproducible with minetest/minetest_game@00a0d9a which exposes the problem. Whether that's a bug worth pursuing or not, is up to you. My concern is that the current minetest_game head hides it but it surfaces while using other mods.

**Comment by sofar** [comment]
It's a waste of time.

Most of farming now uses nodetimers, and the way that nodes grow us largely different now. If you can't reproduce it at all, why would we bother to fix something that is almost a year old?

**Comment by pgimeno** [comment]
Unless ABMs are now considered obsolete, calling the wrong ABM sounds like a serious enough bug to me, that could have consequences for other mods. But whatever. I've worked around it for now, by downgrading the database to version 25 and downgrading the core to the 0.4.15 release.

**Comment by pgimeno** [comment]
For what it's worth, I've dug further into this issue, and this patch fixes it for me:

```diff
diff --git a/src/serverenvironment.cpp b/src/serverenvironment.cpp
index f3f4890..ca2f35d 100644
--- a/src/serverenvironment.cpp
+++ b/src/serverenvironment.cpp
@@ -774,7 +774,9 @@ class ABMHandler
 		for(p0.Y=0; p0.Y<MAP_BLOCKSIZE; p0.Y++)
 		for(p0.Z=0; p0.Z<MAP_BLOCKSIZE; p0.Z++)
 		{
-			const MapNode &n = block->getNodeUnsafe(p0);
+			const MapNode &n = block->isValidPosition(0,0,0) ?
+                                           block->getNodeUnsafe(p0) :
+                                           MapNode(CONTENT_IGNORE);
 			content_t c = n.getContent();
 
 			if (c >= m_aabms.size() || !m_aabms[c])
```

ca36296 substituted the call to `getNodeNoEx`, which called `isValidPosition`, with the new `getNodeUnsafe`, which doesn't, apparently thinking that it was enough at that point to be sure that the coordinates were valid (as the name of the function suggested). However, `isValidPosition()` not only checks the coordinates, but it also checks that `block->data` is not `NULL`, and the cause of this bug seems to be that `block->data` is in fact `NULL` when the problem appears.

The fix above is a kludge, because `MapBlock::data` is private and has no getters, and no checkers other than `isValidPosition()`. Since the latter is easily inlineable, the compiler should have no problem in optimizing the call, which uses constant coordinates, with just a check for `block->data != NULL`, but of course, a better fix would be to add an explicit checker or getter for `MapBlock::data`.

I'll leave up to you the decision on whether this is worth fixing. I don't know when and why `block->data` can become `NULL` at that point, because I don't understand the code well, so I can't point to a better repro than the old `minetest_game` version I already pointed to. To me, this seems like an ABM regression that may have odd side effects and break existing mods, but others may have a different opinion.

**Comment by sofar** [comment]
@Ekdohibs rewrite a bunch of this in the engine a while back, perhaps he can take a look at it.

**Comment by pgimeno** [comment]
> I don't know when and why `block->data` can become `NULL` at that point, because I don't understand the code well

Turns out, it doesn't. I don't know if I've hit a compiler bug or what, but this patch also appeared to fix it, which was extremely puzzling:

```diff
diff --git a/src/serverenvironment.cpp b/src/serverenvironment.cpp
index f3f4890..ca2f35d 100644
--- a/src/serverenvironment.cpp
+++ b/src/serverenvironment.cpp
@@ -774,7 +774,9 @@ class ABMHandler
 		for(p0.Y=0; p0.Y<MAP_BLOCKSIZE; p0.Y++)
 		for(p0.Z=0; p0.Z<MAP_BLOCKSIZE; p0.Z++)
 		{
-			const MapNode &n = block->getNodeUnsafe(p0);
+			const MapNode &n = 1 ?
+                                           block->getNodeUnsafe(p0) :
+                                           MapNode(CONTENT_IGNORE);
 			content_t c = n.getContent();
 
 			if (c >= m_aabms.size() || !m_aabms[c])
```

A valgrind run showed no signs of hitting uninitialized memory either. Recompiling with g++-4.8 (I was using 4.9) appeared to solve the problem. But after going back to 4.9, I am now unable to reproduce it again.

I'll open a new issue if I'm able to identify a clear cause and it turns to be Minetest-related (as opposed to e.g. compiler-related). Sorry for bothering.
