### ISSUE TITLE
Optional giant caverns in mgv7

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5380]
I have noticed that the 3D noise giant caverns in mgvalleys are very popular, i can add these as an option to mgv7 (it won't break old worlds) and there will be no performance problems because the 3D noises for mountains and rivers are not calculated underground, so i can add a cavern noise.

Any interest or objections before i start work?

**Comment by MarkuBu** [comment]
:+1: from me

**Comment by bigfoot547** [comment]
Pull Request: #5382

**Comment by paramat** [comment]
Now there's a PR no point in keeping this open.
