### ISSUE TITLE
CSM: messaging channels

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#5390]
I'd like to see CSM offer a messaging protocol:

completely hypothetical API:
```
local modchannel = ModMessageChannel("channel:name", paramtable)

modchannel:send(blob)
blob = modchannel:receive()
```

interally, a msgid should be kept to prevent sending messages back to senders?

(trying not to think too deep into implementation yet)

- Messages should be any format.
- The messages are relayed between client mods that understand them (local client to local client) or (local client to server)
- no messages from client to other clients, server should route them instead.

Use cases:

- things like private chat
- alternative games
- sharing loot information
- monster alerts ("a village is under attack")
- living shared wiki documents or library books
- etc. etc.

**Comment by raymoo** [comment]
What about messages from the server to the client?

**Comment by sofar** [comment]
I meant that vice-versa.

**Comment by raymoo** [comment]
Oh, ok. So would a message channel on the server side take a player argument in its send method to choose the destination?

**Comment by raymoo** [comment]
What if you want to send a message to only one client? Do they have to use a unique channel id?

**Comment by sofar** [comment]
ok so, we would have to have channel types:

- broadcast (everyone can send & receive all messages on this channel)
- to-peer (client - to client (via server)(and vice versa))
- to-peer (client - to server (and vice versa))

?

**Comment by nerzhul** [comment]
It's a nice idea we would love having for mods, but before we need an enhanced API to do more things. Also, what about security

**Comment by raymoo** [comment]
Mods should be in charge of validating and sanitizing messages since only the mod knows how a message is intended to be used. Maybe there should be a big warning above the API saying that modified clients could send arbitrary messages.

Also there should be a cap on the message size, possibly configurable per channel. Or just big enough to allow most legitimate uses.

**Comment by nerzhul** [comment]
@raymoo i think 10ko should be the max message size, it permits to send sufficnet raw data if we want to serialize some things

**Comment by sofar** [comment]
Size is an ecosystem problem, and I think we should not restrict message sizes or content too much. Let the mods handle this, and if the mods are bad or stupid, nobody will use them.

**Comment by nerzhul** [comment]
@sofar the main problem i see is i send 25M message and server broadcast it to other mod clients and i DoS their MT

**Comment by bell07** [comment]
I think the channel should be defined oneway on server. On server something like
```
minetest.register_csm_channel("channel:name", function(clientdata)
   if clientdata == "items"
      return mintest.registered_items 
   end
end)
```
The channel could be used on client site using
```
local modchannel = minetest.get_csm_channel("channel:name")
local registered_items = modchannel:send("items")

```
So it will be possible client-initiated to send to and receive data from server. The server defines the channel.
Maybe it could be useful in the other direction for server notifications, but for this we need a framework that checks all registered clients if the client does have the client channel receiver mod.

Some additional remarks:

> i see is i send 25M message and server broadcast

Ok, the server needs a "max_csm_message_size" parameter.

To avoid session management issues the channels should be stateless or follow the REST idea: https://en.wikipedia.org/wiki/Representational_state_transfer

I see a security issue the channels could be defined by mod developers that maybe not experienced in development. Great mod+Great graphics => install to the server => overseen the crufty channel => security hole

**Comment by raymoo** [comment]
Why not just have the server send the message regardless and have the client ignore messages sent on channels that they don't have registered?

**Comment by nerzhul** [comment]
server and client should both have a max message size, also channel registration is important to prevent DoS other clients with a single mod.

**Comment by bell07** [comment]
In case of pushes server -> client the client needs to subscribe the push service before receiving the notifications. The server needs to check if the player on client is permitted to get the message before sending them.

**Comment by nerzhul** [comment]
we are in early stages for this protocol, i don't think we will write it before next release, as we should at first show the CSM pure Client side possibilities to end users, get their feedback enhance existing calls before adding more calls.

**Comment by bell07** [comment]
I'm not in a hurry, it is just some ideas for the "CSM: messaging channels #5390" topic

**Comment by nerzhul** [comment]
also, i need to finish my chatting protocol rewrite, which will support channels, this will permit mods to use a specific mode to send their data to server channel hub

**Comment by bell07** [comment]
I look from the perspective what I need to develop a client-site inventory mod in a secure way. Because the client is not allowed (advisably) change the players inventory directly I need a second backend mod on server site that checks players permissions and take the actions. And I need a push service for messages like "your helmet is destroyed (= removed from "armor" inventory) to be able to react on them client site. So the message bus channel is needed for mod2mod communication to be able to develop such mods.
It is just a vision currently ...

**Comment by agrecascino** [comment]
wamp

**Comment by rubenwardy** [comment]
done
