### ISSUE TITLE
Multi-line Strings in Settings Files

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#5392]
I'd really like to see support for multi-line strings in files loaded with the `Settings()` function. I've actually begun looking into C++ in hopes I'd be able to do it myself, but I've got a long ways to go to be able to even do this.

Essentially though, I'd like to see the format below supported:
```lua
-- Normal String
test = hello
-- Multi-line String
multi = [[
This
is
longer.
]]
```

This would allow for much easier management of some settings where you need a longer message. I would suggest that a space be automatically added after each line as well.

Anyways, thoughts?

**Comment by octacian** [comment]
Looking through the code, I begin to wonder if this is already possible. I see Settings::getMultiline which is called by Settings::parseConfigLines. However, even if it is possible, I'm still unable to figure out how multiline settings should be formatted in the settings file.

**Comment by SmallJoker** [comment]
Multiline settings can be denoted like this:
```
setting = """
Just some
multiline text here
"""
```
The only thing mentioned about this topic is that the sequence `"""` may not be used in setting values:
https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/doc/lua_api.txt#L5392
So it basically only needs a PR to document this multiline format and perhaps testing whether it actually works.

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/82deed2d7d5573f1fa463516732475563da59569/doc/lua_api.txt#L6789-L6795

Documented and works.
