### ISSUE TITLE
CSM: Minimap bug

### ISSUE THREAD

**Issue by Amaz1** [minetest/minetest#5404]
Since https://github.com/minetest/minetest/commit/40ce538aad9af8f7634c4ba7e9f12246fb23b31c the minimap has been broken for me, with CSM both enabled and disabled. With CSM enabled, I'm getting this: http://i.imgur.com/4EpJkTw.png (Notice the infotext!) And I can't seem to enable it at all with csm disabled. When I press f9, the minimap appears briefly, and then dissapears...

See from here for the IRC logs: http://irc.minetest.net/minetest-dev/2017-03-16#i_4832336

**Comment by nerzhul** [comment]
Working on the fixes

**Comment by ForbiddenJ** [comment]
I too am having this issue. And when I leave CSM enabled, I get this after switching to "Minimap hidden".

![screenshot from 2017-03-16 21-46-34](https://cloud.githubusercontent.com/assets/26123860/24026890/0dc35324-0a92-11e7-9ddf-8b949404900c.png)

**Comment by nerzhul** [comment]
Fix is now merged
