### ISSUE TITLE
Item drop entities getting stuck if increases hitbox size.

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5409]
I found annoying bug in 0.4.15, i was trying to make farm using water to harvest crops in MineClone 2 subgame, i tested and some items are getting stuck and won't move. So, i figured out how to reproduce:

1. Make a structure like this (any block, steel block for example),
![screenshot_20170317_200603](https://cloud.githubusercontent.com/assets/13905392/24056851/ea758894-0b4d-11e7-8d28-f19c2a675eca.png)
2. Drop 1 any item that it's stackable (drop 1 item, stone bricks for example), must be landing on it,
![screenshot_20170317_200635](https://cloud.githubusercontent.com/assets/13905392/24056940/33db624c-0b4e-11e7-9221-bb6da649f829.png)
3. Drop 98 stone bricks to increase item drop entity hitbox size and remove 1 block here, and it should be get stuck and cannot be fall.
![screenshot_20170317_200650](https://cloud.githubusercontent.com/assets/13905392/24056977/547b2a64-0b4e-11e7-8188-0a8a98562956.png)

There is a way to fix this problem:

:+1: - Improve item drop entity model to make look stackable if it has more than 1 (costs FPS) + never change hitbox size.

or

:-1: - Never change hitbox size if item drop entity has more than 1 + keep item drop entity model size.

**Comment by paramat** [comment]
Or we could make the hitbox slightly larger but keep it a constant size, with a larger entity the corners of the hitbox would still be visible.

**Comment by DS-Minetest** [comment]
related: #5297

**Comment by SmallJoker** [comment]
Another solution would be to check the position and nodes of all 4 corners (bottom) and teleport the item to the closest air position. Before coding the fix for this problem I would like to have the builtin_item mess cleaned up first (#4370) or at least know what's going to happen with it. (Rebasing reasons)

**Comment by paramat** [comment]
^ I feel that's too complex.

**Comment by Avamander** [comment]
Would it be possible to just make minetest do a collision check when the hitbox grows, that would allow smooth pushing out of the wall?

**Comment by paramat** [comment]
That may also be quite complex, overly complex, i feel,  for a rare and minor bug.

**Comment by Avamander** [comment]
A bug is a bug and bugs must be squashed.

**Comment by Fixer-007** [comment]
There is also one thing that needs investigation - blowing items in wall after explosion after TNT.

**Comment by dsohler** [comment]
> A bug is a bug and bugs must be squashed.

Not if the solution is "too complex" :rofl:

**Comment by DTA7** [comment]
For TNT see #5482.

**Comment by SmallJoker** [comment]
Closing in favour of #5482, as it's a more often occurring issue (TNT) and covers all cases of "Entities stuck in walls".

**Comment by paramat** [comment]
Not sure it's the same issue.
