### ISSUE TITLE
Jumping 2 Blocks High (or more?) if Running Toward Higher Trap Door

### ISSUE THREAD

**Issue by expertmm** [minetest/minetest#5410]
Try to replicate the structure in the pictures, and if you keep holding sprint (I am using sprint mod, the one that uses hudbars) while already against the wall and on a trap door, while facing a trap door 1 block higher, you can jump 2 blocks high (without fast priv). You may even be able to get higher, since you hover in the air above the block that is 2 above the trap door's y value. This is using the git version of minetest and minetest_game from March 16, 2017. I am not sure whether it is related to using the lapis pillars or not. I'm not sure if the problem happened with earlier versions or not. This is on a server, and the client is an earlier version: the client is sfan5's windows build named minetest-0.4.15-7279f0b3-win64 downloaded Jan 24, 2017.

![screenshot_20170317_145459_4](https://cloud.githubusercontent.com/assets/7557867/24059771/acfb19f6-0b26-11e7-9e7b-70823348a364.jpg)
![screenshot_20170317_145500](https://cloud.githubusercontent.com/assets/7557867/24059776/ad0887bc-0b26-11e7-8213-e44c93ec8b13.jpg)
![screenshot_20170317_145500_1](https://cloud.githubusercontent.com/assets/7557867/24059772/ad04b8b2-0b26-11e7-9c34-4978b23a4610.jpg)
![screenshot_20170317_145500_4](https://cloud.githubusercontent.com/assets/7557867/24059773/ad06965a-0b26-11e7-91f7-e17da8eedc49.jpg)
![screenshot_20170317_145501_1](https://cloud.githubusercontent.com/assets/7557867/24059775/ad08b0ac-0b26-11e7-869f-8f147b0ff141.jpg)
![screenshot_20170317_145502](https://cloud.githubusercontent.com/assets/7557867/24059774/ad0868e0-0b26-11e7-92fa-5fdba097ce79.jpg)

**Comment by bigfoot547** [comment]
The problem is that the sprint mod increases jump height from `1` to `1.1`.
AFAIK, `set_physics_override` is not linear in it's values, correct me if I'm wrong, so setting `jump` to 1.1 makes you jump _higher_ than 1.1 blocks. The trapdoors and pillars are irrelevant.

**Comment by paramat** [comment]
@expertmm can you test the bug without using the sprint mod?

**Comment by paramat** [comment]
The trapdoors are relevant because the add height to the player, i'm surprised the player can jump that high with jump speed multiplied by 1.1, but maybe it's expected.

**Comment by bigfoot547** [comment]
The trapdoots just add extra height. The jump height is not multiplied AFAIK, so `1.1 jump != 1.1 blocks`.

**Comment by paramat** [comment]
Likely the height of the trapdoor plus the extra height from sprint mod, so not an MT issue.
