### ISSUE TITLE
Fps drop triggered by unknown random event

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5412]
Fps drop is triggered by unknown random event while I'm connected to Hometown server, drop is hard to measure, but roughly up to ~20 fps in general scenes and if looking at sky does not go higher then 70-80 fps, which is very unusual. There is no mesh updates or anything suspicious. After block unload (?) fps goes back to normal.

Reproduced on "Hometown server" in my afk place on those engine builds: 
+ fbc1432 (29 Mar 2017) - reproduced
+ a7485e4 (17 Mar 2017) - reproduced
+ b52f300 (16 Mar 2017) - reproduced
+ https://github.com/minetest/minetest/commit/7a4878cd0b563296b3f2718b79dc9af177dd4fd2 (12 Mar 2017) - reproduced
+ 2baa191 (10 Mar 2017) - reproduced
+ https://github.com/minetest/minetest/commit/f1ab42fdff7a15d81c8cac0f9192b3d5ff9fb913 (05 Mar 2017) - reproduced (after some afk at the base, chunks were still loaded, 35-40 fps everywhere, minimap was used few times)
+ https://github.com/minetest/minetest/commit/707e27b5c26b6c082abbd2f385a976c5bc8964fe (29 Jan 2017) -  reproduced (40-50 fps, bug started while I was approaching the window while looking at forest)
+ 1dd361f (21 Dec 2016) - reproduced. prerelease 0.4.15
+ 9d3d43f (12 May 2016) - test failure due to low fps in general, 40-70fps

![iubj9hf](https://cloud.githubusercontent.com/assets/16494741/24476447/edffd07c-14db-11e7-82aa-418de8e196aa.png). 
In example below expected fps is around 200, yet it is only 80 at most, occured after day/night change while I was alt-tabbing between irc and minetest and also did some mining and added torch, bug was felt at some point.
![jrtautj](https://cloud.githubusercontent.com/assets/16494741/24481841/cc90141e-14f5-11e7-8d91-8bf620b44394.png)
After bug went away after 20 minutes of wait while looking at sky: faulty mapblock was unloaded (?):
![default](https://cloud.githubusercontent.com/assets/16494741/24482359/41c9a8aa-14f9-11e7-88cd-33bec32c08cb.png)

Possible triggers:
+ ~~minimap~~
+ ~~antijitter code~~
+ day/night changes
+ mapblock load/unload
+ animated block ![default](https://cloud.githubusercontent.com/assets/16494741/24510996/6e743db4-1573-11e7-8d39-43caae1650f2.png)

Config:
```
anisotropic_filter = true
bilinear_filter = false
creative_mode = true
enable_damage = true
enable_waving_leaves = false
enable_waving_plants = false
fast_move = false
free_move = true
leaves_style = fancy
mainmenu_last_selected_world = 2
maintab_LAST = multiplayer
menu_last_game = minetest
mip_map = true
node_highlighting = box
server_announce = false
server_dedicated = false
trilinear_filter = false
viewing_range = 160
fps_max = 0
tone_mapping = false
sound_volume = 0.5
enable_shaders = true
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
world_config_selected_mod = 6
fixed_map_seed = 
enable_local_map_saving = false
minimap_shape_round = false
mesh_generation_interval = 0
fsaa = 0
enable_client_modding = false
time_speed = 1
```

**Comment by Fixer-007** [comment]
I have a suspicion that this can be caused by https://github.com/minetest/minetest/commit/25a24c0cdf1467df51c41d0b24e2ab6318ba1850 @numberZero can you try reproducing the problem too?

**Comment by numberZero** [comment]
@Fixer-007 the code I changed in 25a24c0 doesn’t even get called when the minimap is off.

Am I right that the client loads more blocks when the minimap is enabled, in attempt to cover it? And IIRC it doesn’t unload them afterwards, not from the minimap cache at least.

**Comment by Fixer-007** [comment]
@numberZero I have no proofs for now, was not able to catch the bug anymore (on clean mt), I suspect it can be induced by that mesh generation PR with sleep 15ms, but I'm not sure.

**Comment by Fixer-007** [comment]
For some reason it happens best with ```mesh_generation_interval = 15```. Not sure why...

**Comment by numberZero** [comment]
@Fixer-007 you can try to:
* add proper synchronization to the minimap code (it is not fully thread safe now)
* debug minimap code (to make sure it doesn’t get stuck somewhere in the middle)
* make it purge minimap data on disabling
* use valgrind or other sanity checking tool (gcc has some nice options for that)

Debugging isn’t a simple thing, though; to catch such error you need to debug the release build (but add `-g` to the compilation flags), and you need to pause the program (all threads simultaneously) only when you see the error. Often such errors just don’t appear during debugging due to lower speed, different scheduling, etc. But only debugging may give you the whole information on the program state *(boolean variable with value of 67? er, what?)*.

**Comment by Fixer-007** [comment]
Too advanced for me

**Comment by Fixer-007** [comment]
I think I've catched the bug even without enabling the minimap, next phase is I disabled antijitter, will see how it goes with that.

**Comment by Fixer-007** [comment]
Update: bug happens even with minimap off and with antijitter off, this is bad, that means I need to start searching/bisecting for a bug, and that is crazy hard to do.

**Comment by paramat** [comment]
Perhaps try lowering 'client mapblock limit' to see if the increase kicks-in earlier?

**Comment by numberZero** [comment]
Day/night changes should not affect FPS if shaders are enabled.
Animated texture may be slower to render, and may cause some extra CPU<=>GPU data transfer, but the effect should be negligible.
What is important is where is the bottleneck: is it GPU or CPU, user-mode or kernel-mode? Such information may help a lot.

**Comment by Fixer-007** [comment]
I think it is something with CPU load, since when I reduce vrange to 20 and look at sky it shows only 40 fps or so, without bug it would be 120-300 fps... (gpu does not react to changes, thats suggests it is cpu bound). Also, bug kicks in hard, there is no symptoms, fps just suddenly goes down (and gpu was working fine I checked, good temps, low use, low fan use).

**Comment by Fixer-007** [comment]
@ExeterDad What is your Hometown exact engine version?

**Comment by ExeterDad** [comment]
4b05feaceb38a2ab2063b8ff6e92d96393ad384e
Pulled and built on the 27th
https://github.com/minetest/minetest/tree/4b05feaceb38a2ab2063b8ff6e92d96393ad384e

**Comment by Fixer-007** [comment]
Did not posted this earlier, but during those periods of very low fps, there were also reports from chat about this.

**Comment by Fixer-007** [comment]
Another observation with shaders disabled - just after sunrise, at the time of big brightness change there was very noticeable fps drop that persisted during night-day transition, when full daytime appeared fps went back to normal very-very smoothly (in few seconds with shallow drawtime graph).

**Comment by paramat** [comment]
Could that be the change of the light of mapblocks occurring at dawn and dusk, and therefore expected?

**Comment by Fixer-007** [comment]
Nope, when bug kicks in, it persist for looong time with fps going down as low as 24 with vrange 20, clearly something is wrong.

**Comment by ExeterDad** [comment]
@Fixer-007 If you can come up with some date/times (maybe UTC), I'd be happy to check the logs to see if something interesting is occurring during those times. I have have all the logs since going live.

**Comment by Fixer-007** [comment]
I will note it next time, also, bug is gone after rejoining the game, that is very odd. During normal play I noted 50-60 fps, when bug kicks in it is 25-30 fps (F5 graphs are dead silent), very weird, my videocard is also fine...

**Comment by Fixer-007** [comment]
Another suspicious thing is abnormal memory usage during the bug - about 2.4gb

@ExeterDad 08 May 2017 bug started somewhere around 13:00 - 13:10 New York Time (hope it converted right).

**Comment by ExeterDad** [comment]
@Fixer-007 The logs aren't very verbose and there isn't much out of the ordinary logged. But... there was Much TNT blown off during the morning and some TNT explosions as high as 99 during the times you noted.
I attached output of a grep for TNT related activity for the day. https://gist.github.com/ExeterDad/e043c987e0215fe984950bbea8ffc3ef
It must be noted that TNT on hometown can only be placed below -500 So there is a override in place to handle that. Also the TNT mod is a modified version of MTG TNT.  When each tnt is placed all nodes in the area are searched for tnt and they are counted. TNT can only ignite with a torch at this time. This was my solution to keep tnt in the excess of MAX (currently 99) from igniting and taking the server down.

Server timestamps are in CDT (Central Daylight Time) which I believe is UTC -5
If you need the entire log for the day I would share on request. I'm not sure players chat and PM's posted for the world to see would be appreciated much :)

**Comment by Fixer-007** [comment]
@ExeterDad can you look if there was massive animal feeding during that time?

If someone can write debug code to see current number of rendered particles on client on F5 graph, need to check if that can be related to particles-lowfps-TNT bug, but in other circumstance.

**Comment by numberZero** [comment]
https://github.com/numberZero/minetest/tree/profiler-particles
`git fetch https://github.com/numberZero/minetest.git profiler-particles`

**Comment by Fixer-007** [comment]
@numberZero thank you a lot, will utilise this in my investigation of the bug.

**Comment by Fixer-007** [comment]
Observation: connected to Hometown, number of particles raised pretty quickly and stabilised at 200-300 for very long time (sometimes going as high as 700), I do quick restart and it suddenly goes back to 20-30 particles... this huge particle count may also be linked to my poor fps at times. Possible particle spawn/despawn problems?

**Comment by Fixer-007** [comment]
Sudden particle rise to 400 lowered my fps down to bug levels for significant period of time, I have big suspicion that particle rendering is the main cause of this bug. If someone sends me code that completely disables particles I will test it to really confirm it.

**Comment by numberZero** [comment]
@Fixer-007 I just checked *how* inefficient particles are, so they certainly may be the source of the problem, even in that low quantity (400 is not that much for particles).

> that completely disables particles

That is, everything, not just rendering. Try my `z-disable-particles` branch:
https://github.com/numberZero/minetest/tree/z-disable-particles
`git fetch https://github.com/numberZero/minetest.git z-disable-particles`

**Comment by Fixer-007** [comment]
Nice! Will test this.

**Comment by Fixer-007** [comment]
I've played some time on server with particles disabled, and I don't see those fps drops for now, good fps across my base, I have some confidence that 300-400+ particles were the main reason of big fps drops on said server.

**Comment by Fixer-007** [comment]
This issue seems to be fixed after merger of particle spawn PRs, low fps was probably caused by huge amount of particles produced by homedecor faucets (based on my tests).

**Comment by paramat** [comment]
Awesome.
