### ISSUE TITLE
CSM: unable to toggle chat visibility, hud hidden instead

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#5413]
Toggling F2 to show/hide chat instead hides the HUD, and chat remains visible.

**Comment by nerzhul** [comment]
Looking for this

**Comment by nerzhul** [comment]
it's not related to csm as CSM has no API for this, but it will be added when we have access to Game class at a point

**Comment by nerzhul** [comment]
It's now fixed, a recent change introduce a variable error
