### ISSUE TITLE
Add clang-format to project & travis step

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#5415]
clang-format is a very interesting tool to reformat code.
We should include clang-format rules in our project and use a travis step to check it, permit users to fix their code style without coredev review

Example here
https://github.com/DaMan69/citra/commit/0e3f0120a8ec2996e73bb6b7b6c9d7531f7a7eb1

**Comment by sfan5** [comment]
Won't this cause lots of problems with old code that isn't properly formatted?
Also can `clang-format` cover our whole set of formatting rules including exceptions?

**Comment by bendeutsch** [comment]
Yes, please! By complete coincidence, I too started checking out `clang-format` just this weekend (yes, for minetest). I'm a vim user, and I found two plugins which allow formatting only selected parts of a file. The main `clang-format` command supports line ranges, so I'm sure other editors can do this as well.

That should solve the problem with old code: only format the parts you're actively working on.

As for exceptions: at the end of the day, you're checking in a text file, formatted or not. And it's probably better to have something that's 90% correct, and learn the exceptions, than something thats 10% correct (or less), and learn every single rule.

In fact, I'd love to help develop one – I assume http://dev.minetest.net/Code_style_guidelines is still the primary source?

**Comment by bendeutsch** [comment]
Oh right, Travis: it's probably going to be a while before that can be a blocking check, if ever. Start with `allow_failures`?

**Comment by nerzhul** [comment]
also it's very simple to configure clang-format for us as we are using a Linux kernel codestyle which is implemented in the tool :)

**Comment by nerzhul** [comment]
I added a PR which enable a builder using clang format on our codebase in lazy mode (just check, don't block, until we fix more the codestyle)

**Comment by nerzhul** [comment]
This issue is now solved
