### ISSUE TITLE
Server crash with clientmod

### ISSUE THREAD

**Issue by Sokomine** [minetest/minetest#5418]
Testing/development of the [oredetect](https://forum.minetest.net/viewtopic.php?f=9&t=17046) clientmod led to repeated server crashes on a server it was tested on.

```
Extract from server log before each crash:
2017-03-18 17:39:24: ACTION[Server]: player digs default:stone at (298,-1384,-2050) 2017-03-18 

Extract from client log (with the client-side mod running):
17:39:24: WARNING[Main]: Map::removeNodeMetadata(): Block not found
```

**Comment by sofar** [comment]
that's not a crash

**Comment by Fixer-007** [comment]
It is crash, but without any useful info :) Try increasing verbosity and maybe build debug build and run it under gdb and get a backtrace.

**Comment by nerzhul** [comment]
Please give us a backtrace (lua or gdb) and the lua call concerned, here there is no information. but i suspect it's on_dig_node

**Comment by Fixer-007** [comment]
My signature has rough explanation on how to do this:
https://forum.minetest.net/memberlist.php?mode=viewprofile&u=190 (read gdb part)

**Comment by Sokomine** [comment]
The latest news I have on this issue is that the server owner who encountered this bug runs MT under Windows. He was able to reproduce the bug there - but not under a Linux build. Any further debugging under Windows does not seem to be possible on the machine concerned.
Perhaps it is a bug related to one particular build or other circumstances. As there is no way to gather further information and since no one else encountered this problem I think the bug ought to be closed.
