### ISSUE TITLE
Flag for entities like static = true

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#5419]
Flag 'Static' must prevent render from 
> [quote="sofar"] entities need to be serviced every step to update position and calculate physics.[/quote]

Now 10000 entities ruin FPS. 
But if all it's static (no collide no physics) why do engine must recalculate something each step.

More important, attaching give no effect even entities seems after like one mesh. But

> [quote="sofar"] nodes are rendered into a "mesh" together. 

edit:  something like 
`minetest.register_entity( ... , {static = true, ...} )`

**Comment by sofar** [comment]
Because entities have speed properties, and acceleration. And thus the engine needs to look at them to see if they were changed, etc..

Maybe you can use particles instead.

**Comment by MarkuBu** [comment]
Minecraft has the same problem. A German Youtuber uses a lot of drawers from the drawer mod and each drawer uses entities to show the items.

Near the storage system he has only 10 FPS. Now he has disabled the entities and the game runs much faster

**Comment by nerzhul** [comment]
answer done

**Comment by Nyarg** [comment]
> answer done

 I'm sorry nerzhul but where is answer ?

Answer in that case must be like something:
A: No man it's absolutelly impossible because irrlicht don't recognize and control static entity so each entity will full controled each draw loop step.
A:Ohh man it make MT worse.

Now I see only constant fact 
> Minecraft has the same problem

> Because entities have speed properties, and acceleration. And thus the engine needs to look at them

'needs' isn't same the 'must' am I right ?

But MT isn't MC right ? MT must be better )

**Comment by nerzhul** [comment]
oh i agree MT must be better, it's better in termes of modding etc, not in terms of performance. Sofar proposed you a solution and only describe the engine processus, not tell we should look at the issue :)

**Comment by SirGitHub** [comment]
Sorry for bringing this back to life but what if what I wan't is non-laggy signs? Using particles is impossible because they rotate
