### ISSUE TITLE
Impossibility to register new node after loadTime seems strange.

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#5420]
If topic really impossible from irrliht side so changing tiles of registered node may cover it.

**Comment by rubenwardy** [comment]
It's just one of the assumptions that Minetest makes in its design. It makes quite a lot of things easier. Also, if you define a node you can't delete it (unless you want unknown node errors).

**Comment by rubenwardy** [comment]
Related: #1118

**Comment by rubenwardy** [comment]
47

**Comment by sfan5** [comment]
I'm pretty sure this issue is a duplicate...

**Comment by rubenwardy** [comment]
> I'm pretty sure this issue is a duplicate

Same, although a quick search couldn't find the original

**Comment by paramat** [comment]
Is there any point in considering this? A lot of work to make things slower and more complex :-1:

**Comment by Nyarg** [comment]
> Is there any point in considering this?
1. At now I found no way to create new node during game, so it means the game have no ability for evolution and hard linked with reload subgame for updating stuf.
2. Entity may half cover '1' but have more problem - glitches, frosings, texture losing etc. and don't inherit node behavior.
    Entity driving seems for new modmakers more complex than simple creating of new node after loadTime and decrease creativity.

**Comment by raymoo** [comment]
What would be a specific use-case for this?

**Comment by paramat** [comment]
There may be a PR or issue somewhere for 'meta set nodedef' which might offer similar functionality.

**Comment by raymoo** [comment]
Here's a related one: #36

**Comment by sofar** [comment]
node setmeta would be a far better way to solve this issue than to allow new nodes to be registered during runtime.

**Comment by Nyarg** [comment]
> node setmeta would be a far better way to solve this issue

How do it can help gamer get node with new textures after loadTime ?
May be I didn't found proper method in http://dev.minetest.net/Category:Methods ?

**Comment by C1ffisme** [comment]
@sfan5 I think I remember making an issue like this, although I might be wrong.

**Comment by paramat** [comment]
Also see #2887
