### ISSUE TITLE
I don't like Lua, can I use Haskell?

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#5421]

**Comment by MarkuBu** [comment]
If you write a modding API for Haskell, yes

**Comment by zaoqi** [comment]
How to write a modding API for Haskell?@MarkuBu

**Comment by rubenwardy** [comment]
You can either implement a wrapper for haskell in lua (ie: call haskell from lua) or rewrite the src/scripting/ folder to support both lua and haskell.

**Comment by nerzhul** [comment]
You can also use a python wrapper. But we will not do this ourselves.

**Comment by raymoo** [comment]
I support

**Comment by PowerOlive** [comment]
it is good
lua is too long
