### ISSUE TITLE
`minetest.request_shutdown` does not work.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#5425]
Just what the title says. I first noticed after updating my server to latest commits as of 2017-3-19. /shutdown does nothing. Sending SIGINT does nothing. My custom /reboot command (implemented with `minetest.request_shutdown`) does nothing. I really do not want to have to send SIGKILL.

**Comment by sfan5** [comment]
525d2a0d511bc9e9f3691af6ed2f5284dd205e33

**Comment by BluebirdGreycoat** [comment]
Thanks! I guess I should have waited half an hour before grabbing the latest. :)
