### ISSUE TITLE
/deleteblocks does nothing when using postgres backend

### ISSUE THREAD

**Issue by ExeterDad** [minetest/minetest#5426]
/deleteblocks with any options will return with a successful message with the expected areas of deletion. But there is no change in the terrain. 
I created a alternate instance of our public server to eliminate mods one by one to see if it was caused by them. There was no change in behavior. 
/deleteblocks worked very well in the development of the server in the past, but before going public the sqlite db was migrated to postgres. Reverting a portion of database and running server with map.sqlite solves the issue. /deleteblocks works as expected.

**Comment by nerzhul** [comment]
/deleteblocks is agnostic of map backend, very strange issue

**Comment by ExeterDad** [comment]
I've been digging and digging trying to make this work and though I can't be confident as I have nearly zero C programming knowlege... and limited postgres experience...  I really think I have found something interesting that I'm hoping you guys will check out.

src/database-postgresql.cpp:

```
bool Database_PostgreSQL::deleteBlock(const v3s16 &pos)
{
	verifyDatabase();

	s32 x, y, z;
	x = htonl(pos.X);
	y = htonl(pos.Y);
	z = htonl(pos.Z);

	const void *args[] = { &x, &y, &z };
	const int argLen[] = { sizeof(x), sizeof(y), sizeof(z) };
	const int argFmt[] = { 1, 1, 1 };

	execPrepared("read_block", ARRLEN(args), args, argLen, argFmt);

	return true;
}
```

Shouldn't the "read_block" above be the "delete_block" prepared statement?

**Comment by ExeterDad** [comment]
Can someone at least confirm or deny this change will/may fix my issue? I'm not crazy enough to test my "educated guess" on a live server that desperately needs some map fixing from careless players. 
@nerzhul since you seem to understand these things? (I'm sorry, I understand your plate is full)

**Comment by nerzhul** [comment]
in fact deleteblock = read_block is a real problem, don't move i look at the current master code

**Comment by nerzhul** [comment]
Fixed, nice shot
