### ISSUE TITLE
Add particle property 'angle'.

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#5431]
It wide MT with more decor for example sun beams in forest.
It's not more difficult than particle collision (hmm but if surface is one mesh around I'm not right may be)

Emulate sunbeam with entities more difficult for modmakers.
Common format like existing 'speed' and 'velocity' properties I mean angleStart = {...} and angleEnd={...}

As I see here 'angles' ability exist http://irrlicht.sourceforge.net/docu/classirr_1_1scene_1_1_i_particle_emitter-members.html

More interested is analyze best issues for example
]http://wiki.secondlife.com/wiki/LlParticleSystem
http://wiki.activeworlds.com/index.php?title=Particle_Emitter
and add best from the best to MT

**Comment by paramat** [comment]
Please can you explain what you request more clearly, or explain with an image?

**Comment by DS-Minetest** [comment]
I think, he wants to give particles rotation.
Maybe related: #5722

**Comment by paramat** [comment]
Any core dev support?
