### ISSUE TITLE
Shift + middle mouse clicking on >99 of items in inventory/chest erases items during transfer

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5432]
Give yourself 200 apples, put a locked chest nearby, open the chest and transfer all items to it, then from chest via **shift + middle mouse button** clicking back to inventory, this will put 10 apples in your inventory, chest will have only 150 apples (you lost 40). 

If you try transferring larger sizes (like 1000), it gets random, loosing items in the process in random way (I often end up with about 400 items). 

Bug works both ways, but seems random, sometimes it works, sometimes not. If you have problems reproducing, try transferring 1000 apples, and in creative mode.

Needs checking on custom stack sizes (bigger than 99) too.

Confirmed on everything newest and on hometown server. Found out after I've lost 900 out of 1000 silver sand on actual server during transfer to/out of chest very quickly.

Possibly related to this issue: https://github.com/minetest/minetest/issues/2689

Demo of the bug:
![demo](https://cloud.githubusercontent.com/assets/16494741/24116389/4d65fab6-0daf-11e7-945e-604bdabad59a.gif)

**Comment by Wuzzy2** [comment]
I'm not sure if this bug report is even valid. I don't think Minetest needs to be really concerned about stack sizes above the maximum allowed stack size (99 in this case), because this is, frankly, an invalid game state. You are not supposed to ever hold more than 99 apples in one stack anyway.
The real bug may be that `/giveme` allows you to obtain more than `stack_max` items in a single stack.

But if someone wants to fix this, I won't stop you. xD
But I think it's not a real bug.

**Comment by dsohler** [comment]
It's an API function to configure the maximum amount of nodes/items in the definition for said node/item. Minetest should not fail when this function is used to raise the stack limit for a node/item to >99 using said API function.

**Comment by Wuzzy2** [comment]
`/giveme` is not an API function. The only legal way to raise the maximum stack size (I suppose) is by setting it in the item definition. `/giveme` should obey `stack_max` IMO. Or is there a reason why `/giveme` is allowed to disobey? If not, then there's no legal way to ever obtain more than `stack_max` items in a single stack. If it happens anyway, *that's* the bug.

What do others think about this?

**Comment by orwell96** [comment]
The question is: does the bug appear with items that /have/ stack_max set higher?

**Comment by Fixer-007** [comment]
I tried with stack_max=1000 and transferred 1000 apples via shift+midclick without any problems.

**Comment by SmallJoker** [comment]
Cannot reproduce after #8895
