### ISSUE TITLE
Implement FFI to LuaJIT

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5442]
I propose to add the FFI library to Minetest LuaJIT because this could make a lot of things faster

http://luajit.org/ext_ffi.html

**Comment by sfan5** [comment]
Can't you just install it like a normal lua library?

**Comment by MarkuBu** [comment]
I don't think so. I'm not sure, but I expect that some C/C++ changes are necessary. 

https://github.com/facebook/luaffifb

I can install it on my PC, but it is still not available in MT and only for me

https://luarocks.org/modules/colesbury/luaffi

**Comment by red-001** [comment]
Wouldn't this undermine the whole concept of mod security?

**Comment by MarkuBu** [comment]
Maybe it is possible to disable "calling external C functions". I'm more interested in "using C data structures"

> Now let's have a look at the impact of the changes: first, memory consumption for the image is down from 22 Megabytes to 640 Kilobytes (400*400*4 bytes). That's a factor of 35x less! So, yes, tables do have a noticeable overhead. BTW: The original program would consume 40 Megabytes in plain Lua (on x64).

> Next, performance: the pure Lua version runs in 9.57 seconds (52.9 seconds with the Lua interpreter) and the FFI version runs in 0.48 seconds on my machine (YMMV). That's a factor of 20x faster (110x faster than the Lua interpreter).

I think it' worth a closer look

**Comment by MarkuBu** [comment]
I have installed the ffi lib via luarocks. I think it should be possible now to use it if mod security is disabled. If that works I will try to make a test and measure the performance

**Comment by Ekdohibs** [comment]
@red-001 Non-trusted mods shouldn't be allowed to execute C code; however, this shouldn't be a security problem if it is part of the insecure environment.

**Comment by MarkuBu** [comment]
Until now I don't see any effect. I try to replace lua tables in a lua mapgen with cdata arrays. Maybe I did something wrong, maybe LuaJIT can optimize that good enough. I don't know

**Comment by MarkuBu** [comment]
I compared the example from the page. There is a significant difference in performance and memory

5000ms and 22MB memory usage for the lua version
600ms and 1,4MB for the FFI version

Maybe it mostly effects some specific table in table situations, but not simple arrays

**Comment by MarkuBu** [comment]
Is it possible that FFI is already used by Minetest for functions like the voxelmanip and perlin noise? That would explain that there is no difference in my test.

data from voxelmanip is already a ctype

**Comment by sfan5** [comment]
No, ffi is not in use in Minetest. However we might be doing something similar to increase performance.

**Comment by paramat** [comment]
Author has left MT, anyone else requesting this?

**Comment by octacian** [comment]
What exactly does ffi allow? It seems to me as though it would allow calling C++ functions directly from Lua, is that correct?

Either way, if it would improve performance, I'd happy to see it implemented (although performance isn't a major issue at the moment AFAIK).

**Comment by paramat** [comment]
Increased performance does not necessarily mean it's a good idea.

**Comment by paramat** [comment]
Any dev interest? Close in 1 month if not.

**Comment by nerzhul** [comment]
i don't exactly the benefit, we already have lua mappings for C++ functions, it removed the abstraction level ? Not sure it has a real benefit, and it's dangerous and not compatible with non JIT Lua

**Comment by paramat** [comment]
sfan5 agrees to a close.

**Comment by pgimeno** [comment]
Slight nitpick: you can't (portably) call external C++ functions, only C, due to name mangling.

Anyway, FFI is not only about calling external C functions, but also, and more importantly, about using memory more efficiently and allowing allocation past the LuaJIT limit, which paramat told me is causing crashes. `ffi.new()` is essentially a `calloc`.

Yes, FFI is dangerous both from the security and from the stability perspectives. I don't think you can disable function calls as @MarkuBu proposes, but even if you could use it only for memory access, there's the fact that using CDATA is in fact using raw pointers, with all the caveas associated: if you go past the area you allocated, you're not protected as you are with Lua arrays, and you'll probably cause a hard crash.

On the plus side, that's precisely the reason why it's much more efficient, space and speed wise, and why I'd like to see it available, if only for trusted mods and possibly for the builtins.

Reading this more carefully can help understanding the main use of FFI for Minetest: http://luajit.org/ext_ffi.html#cdata

Then there's also callbacks, that I have seen mentioned as one of the bottlenecks in MT. I'm not sure how they would fit but perhaps it's worth investigating. Info on callbacks here: http://luajit.org/ext_ffi_semantics.html#callback

**Comment by pgimeno** [comment]
Apologies for not noticing that just using `minetest.request_insecure_environment()` suffices to be able to use `require` (and therefore FFI) in a mod. Still, there are some areas that can greatly benefit from this.

To start the ball rolling, I've used my maze mapgen  https://gist.github.com/pgimeno/3f86ca27d2ad7d2bba4633448db059fb as an example by converting it to FFI. It needs the following additions to the engine:

```diff
diff --git a/src/script/lua_api/l_vmanip.cpp b/src/script/lua_api/l_vmanip.cpp
index 254a7e5a..5fe2440f 100644
--- a/src/script/lua_api/l_vmanip.cpp
+++ b/src/script/lua_api/l_vmanip.cpp
@@ -29,6 +29,29 @@ with this program; if not, write to the Free Software Foundation, Inc.,
 #include "mapgen.h"
 #include "voxelalgorithms.h"
 
+#if USE_LUAJIT
+extern "C" void voxelmanip_get_data(LuaVoxelManip *lvm, u16 *data)
+{
+	u32 volume = lvm->vm->m_area.getVolume();
+	for (u32 i = 0; i != volume; i++) {
+		data[i] = lvm->vm->m_data[i].getContent();
+	}
+}
+
+extern "C" void voxelmanip_set_data(LuaVoxelManip *lvm, u16 *data)
+{
+	u32 volume = lvm->vm->m_area.getVolume();
+	for (u32 i = 0; i != volume; i++) {
+		lvm->vm->m_data[i].setContent(data[i]);
+	}
+}
+
+extern "C" int voxelmanip_get_volume(LuaVoxelManip *lvm)
+{
+	return lvm->vm->m_area.getVolume();
+}
+#endif
+
 // garbage collector
 int LuaVoxelManip::gc_object(lua_State *L)
 {
```

And here is the patch to convert the mapgen itself to dual Lua and FFI:

```diff
--- mazegen.lua	2017-12-27 03:45:42.488485216 +0100
+++ init.lua	2017-12-27 03:54:01.569000826 +0100
@@ -4,6 +4,32 @@
 -- Many thanks to Paramat for the numerous tips with the flat world generator
 -- and understanding the VoxelManip, and the people at IRC for their support.
 
+local ffi
+local ie = jit and minetest.request_insecure_environment() or nil
+
+if ie then
+  ffi = ie.require('ffi')
+  ffi.cdef [[
+    typedef uint16_t u16;
+    void voxelmanip_get_data(void *vm, u16 *data);
+    void voxelmanip_set_data(void *vm, u16 *data);
+    int voxelmanip_get_volume(void *vm);
+  ]]
+  if not pcall(function ()
+                 assert(ffi.C.voxelmanip_get_volume
+                    and ffi.C.voxelmanip_get_data
+                    and ffi.C.voxelmanip_set_data)
+               end) then
+    minetest.log("warning", "[mod] mazegen: Minetest version lacks support for FFI VoxelManip access; performance will suffer")
+  else
+    print("[mod] mazegen: Using accelerated VoxelManip")
+  end
+elseif jit then
+  minetest.log("warning", "[mod] mazegen not added to secure.trusted_mods; performance will suffer")
+else
+  minetest.log("warning", "[mod] mazegen: LuaJIT not available; performance will suffer")
+end
+
 -- Which height to use for the terrain
 local terrain_height = 0
 
@@ -59,7 +85,8 @@
 local sx, sy, sxy, base, xbase, zbase
 
 -- This is the VoxelManip data. Make it a top-level local as recommended.
-local data = {}
+local datasize = 0
+local data = not ffi and {}
 
 
 local function intersects(px, pz, size)
@@ -155,7 +182,6 @@
 end
 
 
-
 minetest.register_on_generated(function (minp, maxp, blockseed)
   local vm, min, max = minetest.get_mapgen_object("voxelmanip")
 
@@ -167,17 +193,32 @@
     sx, sy = max.x - min.x + 1, max.y - min.y + 1
     sxy = sx * sy
 
-    base = (maze_height - min.y) * sx + 1
+    base = (maze_height - min.y) * sx + (ffi and 0 or 1)
     xbase, zbase = min.x, min.z
     xmin, ymin, zmin = minp.x, minp.y, minp.z
     xmax, ymax, zmax = maxp.x, maxp.y, maxp.z
 
     -- Prepare to modify the voxelmanip
-    vm:get_data(data)
+    local vmp
+    if ffi then
+      vmp = ffi.cast('void **', vm)[0]
+      local olddatasize = datasize
+      datasize = ffi.C.voxelmanip_get_volume(vmp)
+      if datasize > olddatasize then
+        data = ffi.new('u16 [?]', datasize)
+      end
+      ffi.C.voxelmanip_get_data(vmp, data)
+    else
+      vm:get_data(data)
+    end
 
     mazegen_recursive(-32768, -32768, 32768)
 
-    vm:set_data(data)
+    if ffi then
+      ffi.C.voxelmanip_set_data(vmp, data)
+    else
+      vm:set_data(data)
+    end
     vm:write_to_map()
   end
 end)
```

I haven't performed any measurements, so I can't tell how much of a difference it will make. I can only tell that there's an obvious reduction in overhead when comparing e.g. `voxelmanip_get_data()` with `LuaVoxelManip::l_get_data()`, and in the LuaJIT side the performance is improved if the code gets compiled (whether it will make a noticeable difference is another matter).

**Comment by rubenwardy** [comment]
This looks like it would break mod security.

**Comment by paramat** [comment]
LuaJIT is problematic and poorly maintained. I disagree with doing anything that relies on it :-1:

**Comment by paramat** [comment]
From https://github.com/minetest/minetest/pull/6863#issuecomment-354591924

> #5442 suggested adding FFI, but FFI is part of LuaJIT, so I can only take #5442 as a request to add FFI to pure Lua. I don't think that's desirable.

**Comment by paramat** [comment]
Treating this as a suggestion to add what pgimeno has submitted.
