### ISSUE TITLE
Add settable dungeon distribution noise to mapgens

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5447]
I start a new map and followed the output of `get_mapgen_object("gennotify")`. From spawn point I had to fly a while until the first dungeon appeared. But in this area I found a lot of dungeons

Is it possible to add more dungeons and spread them more evenly?

![screenshot_20170324_150131](https://cloud.githubusercontent.com/assets/16163058/24297406/f05a8336-10a2-11e7-879b-66c11b5c8136.jpg)

**Comment by DS-Minetest** [comment]
:thinking: Well, dungeon cities make sense I think.

**Comment by MarkuBu** [comment]
But for the gameplay more spreaded dungeons would be better. I want to add chests in dungeons, but if there are no dungeons 1000 nodes around your spawn point it doesn't make fun

**Comment by paramat** [comment]
It's possible but the large variation in density is a good thing. In dense areas it's fun to link up the dungeons. Sometimes 2 dungeons will overlap. However that high density would be ridiculous everywhere. I think it's fine as it is.
`NoiseParams nparams_dungeon_density(0.9, 0.5, v3f(500.0, 500.0, 500.0), 0, 2, 0.8, 2.0);`
Spread (scale of variation) is 500 nodes.

Hmmmm was planning to make dungeon params settable but left MT before doing so, i don't know how to.

**Comment by paramat** [comment]
:-1:

**Comment by MarkuBu** [comment]
So you won't change the default. Will Hmmmm return or did he left forever?

**Comment by paramat** [comment]
No idea.
Hopefully we can make dungeonparams settable, hmmmm told me they are actually already settable in Lua using a workaround method, this is in IRC logs somewhere shortly before he left IRC.

**Comment by MarkuBu** [comment]
I really need to get into the C++ code, hm?

**Comment by Wuzzy2** [comment]
I don't think there is anything wrong with the dungeon spread. I agree with paramat.

**Comment by paramat** [comment]
I am able to add dungeon density noise to a mapgen's noise parameters, i could do this after release.

**Comment by MarkuBu** [comment]
> I don't think there is anything wrong with the dungeon spread.

There is someone who complains about it, so there is something wrong.

**Comment by paramat** [comment]
That was Wuzzy2's subjective opinion.

**Comment by paramat** [comment]
Changed this to be a request for being able to set the dungeon distribution noise in a mapgen, something i know how to do.

**Comment by paramat** [comment]
I support adding mapgen-specific parameters for dungeon y-limits and density noiseparams.

**Comment by paramat** [comment]
When i do this i also intend to move the 3D noise calculation for dungeon density out of dungeongen.cpp and into mapgensimple. Working on new core mapgens i have found that if a core mapgen wishes to make custom use of the dungeon generator it has to provide a dummy density noise even if that's not required.

**Comment by paramat** [comment]
PR #5447
