### ISSUE TITLE
make dungeon stairs higher

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5448]
If you walk stairs (the one with the normal nodes, not the stair nodes) in dungeons up and down you always bump your head on the ceiling. That slows the player down and looks strange

I propose to make these stairs one node higher

![screenshot_20170324_221658](https://cloud.githubusercontent.com/assets/16163058/24313989/9e128618-10df-11e7-96c2-ffaa8f48cfb4.jpg)

**Comment by DS-Minetest** [comment]
This is normal with old buildings, in the past the people were smaller and built smaller corridors.

**Comment by SmallJoker** [comment]
@DS-Minetest Since SAM was created by god (c55), he did not grow at all. ;)

Having 4-node high corridors would be nice to have but is not important.

**Comment by paramat** [comment]
There might be problems with the stair corridors matching the minimum room height.
I agree it's not comfortable to walk, but am hesitant to start altering the classic dungeon dimensions. Will consider though.

**Comment by DS-Minetest** [comment]
> Since SAM was created by god (c55), he did not grow at all. ;)

God didn't want Sam to know this, so he made the corridors smaller to make him think, that there were other smaller people before him.

**Comment by dsohler** [comment]
> There might be problems with the stair corridors matching the minimum room height.

Maybe don't change the height but move the steps one node back? This won't change corridor height so there is no need to take care of the room heights.

**Comment by paramat** [comment]
Yes that would work, difficult to code though because the stair code is a nigtmare. Not worth doing i feel. If i can get stair nodes reliably placed this will help this issue, i would rather work on that first.

**Comment by paramat** [comment]
There's a dungeon parameter only settable withiin a core mapgen that can alter the height of corridors and stairs, note both corridors and stairs will be changed, 2-node high corridors have a good restricted feel to them that i don't want to change. This would also prevent 2-node high rooms.
:-1: New mapgens can specifiy higher corridors if they want but i disapprove of changing existing stone dungeons, the low ceilings are part of their character.
