### ISSUE TITLE
Jittery motion when player tries to sneak out of the block more than allowed at high fps

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5449]
Not sure if this can be described as a bug: if you use custom fps_max, with high values like 100, you can observe this jittery motion, but default config is not affected though.

Now you decide if this needs to be open or not... this looks like minor nuisance for high fps configs and rarely seen, I still want to at least document it in github system. 

This bug exists in 0.4.15-dev, 0.4.14 and probably older versions.

It is not the only "bug" caused by high fps, if you have extremely high fps (about 200-300) - you can hear repeatedly looped snow sound on snow nodeboxes iirc.

Demo of the jittery motion:
![jitter](https://cloud.githubusercontent.com/assets/16494741/24317573/1fd13854-1101-11e7-8f68-fecbf973df80.gif)

**Comment by bigfoot547** [comment]
How do you get that high of fps? I have `fps_max` tat `120` and my FPS is stuck at `60`.

**Comment by SmallJoker** [comment]
@bigfoot547 Turn off `vsync` to get higher framerates.

**Comment by sfan5** [comment]
Before anyone cites this as being my fault:
<b>This bug has existed since before 14aa990cdd682b00904c4a84968a6c0e3c31716d, e.g. in 0.4.15</b>

**Comment by Fixer-007** [comment]
@sfan5 It is not your fault in any way, it exists in 0.4.14 and probably forever.

**Comment by paramat** [comment]
I've noticed this in current sneak code, it's very subtle and only happens when sneaking and pushing against the limit of sneak. I expect it is move code moving the player out while sneak code restricts movement.

**Comment by paramat** [comment]
@Fixer-007 how subtle is this motion at high FPS?

**Comment by Fixer-007** [comment]
Very slight yet visible

**Comment by paramat** [comment]
#5675 merged.
