### ISSUE TITLE
Wallmounted nodes appearing backwards/upside-down

### ISSUE THREAD

**Issue by cheapie** [minetest/minetest#5450]
Ladders are appearing on the wrong side of the node (opposite the selection box), and letters from another mod are showing up upside-down. This seems to have been introduced by d4e0c0f.

![screenshot_20170321_222916](https://cloud.githubusercontent.com/assets/415827/24320165/d77a9792-10fd-11e7-92cf-ebe68ab0d453.png)

**Comment by SmallJoker** [comment]
@numberZero

**Comment by numberZero** [comment]
doesn’t happen in my branch. compiling master now.

**Comment by numberZero** [comment]
> Ladders are appearing on the wrong side of the node (opposite the selection box),

default:ladder works fine for me

> letters from another mod are showing up upside-down. 

confirm, fixing. there is some problem with glasslike too, though.
@cheapie please explain which mods you used

**Comment by numberZero** [comment]
#5453

**Comment by cheapie** [comment]
I don't know where the letters mod in use comes from, but here's the relevant part of the nodedef:
![screenshot_20170325_144319](https://cloud.githubusercontent.com/assets/415827/24325578/886a0aea-1169-11e7-8c0b-7555ae806af4.png)

#5453 does appear to fix this.

**Comment by Fixer-007** [comment]
Letters mod was developed by @Amaz1

**Comment by paramat** [comment]
![screenshot_20170326_001208](https://cloud.githubusercontent.com/assets/3686677/24327147/ed48f49a-11b8-11e7-91cc-4d8fde3773f4.png)

Default ladders are fine for me.

**Comment by cheapie** [comment]
Default ladders started working properly again at some point, but letters are still showing up incorrectly.

**Comment by numberZero** [comment]
@cheapie make sure you test https://github.com/minetest/minetest/pull/5453/commits/c3e946c4b55ec3cd2426f8ed562f1cb03bad2345

**Comment by cheapie** [comment]
I tested that a few posts up and it did fix it (same one as with the screenshot of the nodedef).

**Comment by numberZero** [comment]
@cheapie 
> letters are still showing up incorrectly.

so what do you mean? if my patch fixes the problem, we can only ask people to review it and wait.

**Comment by cheapie** [comment]
Hopefully this clears it up:

With patch, as you requested that I test:
Ladders and letters both work

Without patch:
Ladders were broken, but were fixed at some later point
Letters are still broken

**Comment by paramat** [comment]
#5453 merged.
