### ISSUE TITLE
[CSM] Add settings API

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#5454]
l noticed that minetest.setting_get doesn't work.
l need this function to get the player name and other settings.
It's executed at load time, so according to the [documentation](https://github.com/minetest/minetest/blob/master/doc/client_lua_api.md#initlua) it should work.

**Comment by DS-Minetest** [comment]
Also `settingtypes.txt` doesn't work yet.
related: #5394

**Comment by nerzhul** [comment]
sorry, but it's a bad usecase to use settings to get player name. We will have a lcoalplayer reference instead for this when roadmap 2 will be finished

**Comment by HybridDog** [comment]
nerzhul, thanks, but l don't need the function solely to get the player name

**Comment by rubenwardy** [comment]
Are there any usecases for this apart from mod settings? Might be worth only letting CSM access settings starting with `client.`

**Comment by HybridDog** [comment]
You may want to get the smooth lighting setting and whatnot.

**Comment by nerzhul** [comment]
@HybridDog i think we can offer setting getter to mods, but not setting setter

**Comment by HybridDog** [comment]
This issue is about the getter.

**Comment by sofar** [comment]
We want to make sure mods (sent by the server) can't scrape all user settings and send them to the server. So indeed what @rubenwardy said, you probably only want to allow a few settings to be read, if any.

**Comment by paramat** [comment]
> so according to the documentation it should work.

That's not official documentation of the function, that may just be copy-paste.
Some settings may be best hidden from CSM.

**Comment by raymoo** [comment]
What if mods can only read specific settings plus all settings with names that are modname.settingname?

**Comment by paramat** [comment]
Mods may have settings that control things that need to be secret on a server. Likewise we need to be careful about accessing other settings a client should not know and could abuse.

**Comment by raymoo** [comment]
If it's a secret then don't send it to the client.

**Comment by DS-Minetest** [comment]
Related: #5941

**Comment by paramat** [comment]
1+ year bump, any core dev support?

**Comment by DS-Minetest** [comment]
The link in the first post is outdated, here's a permalink:
https://github.com/minetest/minetest/blob/b6adb7f09e4375f145c3ddb592527c1dd0b026a2/doc/client_lua_api.txt#L100-L101

**Comment by paramat** [comment]
The future of CSM is highly uncertain at the moment. I feel it's best to wait until we know SSCSM is going ahead before adding new CSM features (as it may be wasted work). So i am :-1: until SSCSM progresses.
