### ISSUE TITLE
Per-player tool specs and damage (to allow for per player gameplay)

### ISSUE THREAD

**Issue by PureTryOut** [minetest/minetest#5465]
Continuation of [here](https://github.com/minetest/minetest/issues/4688#issuecomment-257122515), as more people seem to think change is needed. I think the way creative mode is handled right now should be changed.

At the moment of writing, creative mode is a world option. This means that it's either on or off, for *everyone* in the world. However, there are several use-cases to think off why one would want a single person to either enable or disable creative mode, and leave the rest of the players be.

Example:
A popular survival server has griefer problems. To estimate the damages and try to rollback if needed, an admin would switch to creative, do his admin duty without having the risk to be killed by accidentally falling or annoying players trying to kill him, and revert back to survival once he is done.

I think a new option would have to be added when creating a world, to specify the default "gamemode". No matter the gamemode of the players already in the world, any new players would get this gamemode on first join. Once in, they can change it (if they have the appropriate permissions obviously). This would also remove the need in singleplayer to leave the world only to turn on or off creative mode.
Mods would need a way to check if a player is in creative mode or not of course.

Maybe handle more tasks for this on the mod side as well? Minetest could just tell mods if the player has the mode on or off, and mods could then decide what to do with that fact (negate damage, fly, etc).

I would like to hear your feedback.

**Comment by ExeterDad** [comment]
@rubenwardy  already has a very good mod for this feature you may want to try.
https://github.com/rubenwardy/perplayer_gamemode

**Comment by rubenwardy** [comment]
There are already api functions for this in the creative mod that make it extremely easy to add as a mod. I'd rather not have a perplayer creative mode in mtg.

This is the wrong tracker, anyway

**Comment by PureTryOut** [comment]
> @rubenwardy already has a very good mod for this feature you may want to try.

Nope, that only changes the inventory based on creative mode, it doesn't actually enable or disable damage (as far as I can see).

> There are already api functions for this in the creative mod that make it extremely easy to add as a mod.

I'm sorry, but it has literally no API functions that are not related to inventory. Creative mode does more then just changing the inventory, it also enables or disables damage, and switches the hand item out for a creative one. Those features are part of the core it seems, so I think it very much belongs here.

> I'd rather not have a perplayer creative mode in mtg.

1. Why not?
2. You don't have too. It can be setup so both options are possible, depending on the mod that implements it. You could just forbid gamemode changes, or change it for all people if one person changes it. Right now possible options are limited, by making it a user setting in the core mods get way more options.


Minetest is supposed to be an engine, but right now it controls some aspects of the game that I really think should be "off-loaded" to mods, one of which is creative mode. Having the idea of "I don't like perplayer creative mode and thus no one else should have it" is a really limited view in my opinion, and I don't get it. Making this change wouldn't actually remove the option to have it per world...

**Comment by rubenwardy** [comment]
So this is an engine issue - it's not currently possible to make tool specs per person, so in that respect per person creative isn't possible

**Comment by raymoo** [comment]
Solving #5200 would allow at least the creative case (by giving creative players a hand that can dig anything quickly), though it would conflict with other mods changing the hand.

**Comment by PureTryOut** [comment]
> though it would conflict with other mods changing the hand.

It would be acceptable for a first solution, but yeah that'd become a problem in the long run. It would still be an improvement from right now though, as currently as long as you have a tool in your hand, you won't even notice that you're in creative.

**Comment by orwell96** [comment]
You could assign callbacks to the creative hand that check if creative mode is enabled
Also, creative mode and damage are 2 different things. You may want to disable damage but play survival.

**Comment by Ferk** [comment]
Yes, there are already APIs for controlling both the hand and the inventory. Which is what creative mode does.
Creative mode does not affect damage taken, there's an independent flag for that. Though for that one there are no APIs.

You might want to change the issue title/description, or make a new one specifically about the "enable damage" flag.

**Comment by PureTryOut** [comment]
Well the title like I had it before was better in my opinion, but I'm not the one that changed it to the current one.

If damage taken is indeed a separate flag, then creative mode uses that. I don't really care how it does it really, I just want creative mode (or any other possible gamemode a mod could add really) per player instead of per user.

Inventory and hand offloaded to mods is a good start, now moving control of the damage flag away from core to mods is the next step.

I literally just want players to have a gamemode variable which mods can read, and then let the mods decide what to do with it (change inventory, change main hand and tool specs, enable or disable damage, etc). Then a mod could add a "creative" gamemode, a "survival" gamemode, and even a "peaceful" gamemode (disable damage but survival).

**Comment by rubenwardy** [comment]
> already APIs for controlling both the hand

creative mode also modifies tool specs

> Well the title like I had it before was better in my opinion, but I'm not the one that changed it to the current one.

The one before was an invalid issue - you can set creative mode per player using the API - it's just tool specs that can't be modified. If the request was for a default feature to change creative mode, then this is the wrong repo.

**Comment by paramat** [comment]
> At the moment of writing, creative mode is a world option. This means that it's either on or off, for everyone in the world. However, there are several use-cases to think off why one would want a single person to either enable or disable creative mode, and leave the rest of the players be.

Per-player creative is now possible in MTGame.
Please can you update the first post to what you are actually requesting?

**Comment by PureTryOut** [comment]
Ugh, this is becoming unnecessarily confusing. I don't understand how you guys still don't understand what I want ;)

Even if per-player creative is now implemented by MTGame (which only handles the inventory right now it seems), the setting `creative_mode` is still there. If creative is now per player, what does the value of that setting mean?

So from what I understand @rubenwardy, we can now change the main hand specs and change inventory based on creative status? The ability for mods to change tool specs would indeed be needed, but what about enabling/disabling damage/breath per player?

**Comment by orwell96** [comment]
From a mod: set player armor group immortal and hide hud. or register an on_punchplayer callback that returns true on creative players

**Comment by PureTryOut** [comment]
That just negates damage from other entities, but I like to completely disable **all** damage, so fall damage as well. It would be nice if the "enable_damage" setting became per-player, or at least have a per-player equivalent...

**Comment by rubenwardy** [comment]
Implemented, will be in 0.5
