### ISSUE TITLE
Can't climb down into certain place (regression after PR5443)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5466]
Found regression after https://github.com/minetest/minetest/pull/5443, on "just test 2" server (and in vanilla game) I can't descend via this ladder, it goes down unevenly half-way and stops. Test world with mtg only blocks were you can reproduce (rename to .zip after DL): 
[TestChamber.pdf](https://github.com/minetest/minetest/files/870876/TestChamber.pdf) (to reproduce - go down that ladder, obviously). Removing trapdoor does not help.
![default](https://cloud.githubusercontent.com/assets/16494741/24332680/af268772-1253-11e7-9445-af724ed438e0.png)
Maximum descend depth:
![default](https://cloud.githubusercontent.com/assets/16494741/24332720/6246dc6c-1254-11e7-83cc-b43e7ca8e9bb.png)
Reproducing with default mtg blocks:
![default](https://cloud.githubusercontent.com/assets/16494741/24359429/0386e500-130d-11e7-9f19-f488e1bb7d9c.png)
Also, this does not help:
```
<sfan5> Fixer: try replacing
<sfan5> else if(m_can_jump || (control.sneak && m_sneak_ladder_detected))
<sfan5> with
<sfan5> else if(m_can_jump || (control.sneak && m_sneak_ladder_detected && !is_climbing && !in_liquid))
```

**Comment by paramat** [comment]
I'll try to reproduce with full nodes.

**Comment by paramat** [comment]
Can confirm.

**Comment by Fixer-007** [comment]
He has a solution for this https://github.com/sfan5/minetest/tree/snek3

**Comment by paramat** [comment]
I'll test that.

**Comment by paramat** [comment]
Confirmed fixed by that commit.
I also have a further commit that *might* provide 2-node jump near a ledge https://github.com/paramat/minetest/commit/236cde54362ff7f076e90a72525c802e43fc21a2

**Comment by paramat** [comment]
#5470 merged.
