### ISSUE TITLE
[CSM] [Request/Suggestion] Get player name

### ISSUE THREAD

**Issue by cheapie** [minetest/minetest#5468]
There does not appear to be any way to get the local player's name. This should probably be added.

**Comment by bigfoot547** [comment]
I will work on this. Expect a PR soon! :smile:

**Comment by bigfoot547** [comment]
I was planing on being cheap and just adding a function, but instead, I will add a localplayer reference.
I have to do it tomorrow though.

**Comment by nerzhul** [comment]
@bigfoot547 for a player reference be very very careful about the lifetime of the localplayer lifetime in client class

**Comment by bigfoot547** [comment]
@nerzhul Can you please rephrase that? I don't understand :confused: ...

**Comment by nerzhul** [comment]
@bigfoot547 you mean you want to work on localplayer reference exposed to Lua, i just wanted to poke you about being careful about LocalPlayer object lifetime in minetest client object lifetime which could be different than localplayer

**Comment by bigfoot547** [comment]
Oh! So the LocalPlayer object is not deleted when the client object is disposed.

**Comment by nerzhul** [comment]
i don't said that

**Comment by nerzhul** [comment]
Will be solved by #5480

**Comment by nerzhul** [comment]
Solved
