### ISSUE TITLE
Lua Unit Tests

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#5469]
To make builtin testing easier

@t4im has done some experimenting in this area

**Comment by nerzhul** [comment]
i'm interesting about a lua unit test framework as i have a library with Lua callbacks for my own and didn't see a clear way to do this

**Comment by t4im** [comment]
I am happy there is finally an interest in lua testing showing. :-)

Let me know if you want to recycle anything. While the smoketest component was experimental, the unit/integration testing framework itself was not. I'm sure there are a few things that can be carried over to run on top of busted and still be useful.

**Comment by rubenwardy** [comment]
I have already started this, using busted's luassert

**Comment by t4im** [comment]
I am not sure i understand what you mean to say. Cubictest uses luassert for assertions, mocks and spies as well. What i mean is that some functionality might be easily transferable due to that.

**Comment by rubenwardy** [comment]
Thanks for the clarification in PM, I'll have a look in more detail at your projects to see if there's anything that could be combined. It would be great if you could come online at some point, I went AFK so wasn't able to respond to any of your questions
