### ISSUE TITLE
Add entity callback for death events.

### ISSUE THREAD

**Issue by shacknetisp** [minetest/minetest#5474]
Currently there is no way to determine when an entity has died besides calculating health during on_punch.

Adding an `on_death` entity callback would resolve this problem, providing a simple and reliable way to detect entity death.

**Comment by bigfoot547** [comment]
AFAIK, `hp` and, in turn, death are handled purely by the property table for the object and is not standard. Thus if an object's hp is `0`, it is still not removed by the game.

**Comment by Wuzzy2** [comment]
I agree. `on_death` is a **glaring omission** because entity death is a *core* feature of entities.

**Comment by nerzhul** [comment]
See #6177

**Comment by nerzhul** [comment]
Fixed
