### ISSUE TITLE
Add a callback for when a player has their inventory open

### ISSUE THREAD

**Issue by PureTryOut** [minetest/minetest#5481]
I'd like a callback for when, or at least a way to determine if, the player has their inventory opened.

I'm trying to change the inventory look based on stuff happening around the player while he/she has their inventory opened, and often before the inventory has been opened. Right now I can only change stuff when the inventory is closed by using `minetest.register_on_player_receive_fields`, but that isn't exactly what I want.

**Comment by tacotexmex** [comment]
Why not expand this feature to when a player has any formspec open? Optionally returning information on which formspec it is.

**Comment by paramat** [comment]
A callback can only be triggered on an event, such as inventory open or close, i gess you want a way to tell if inventory is currently open.

**Comment by PureTryOut** [comment]
Yes, callbacks preferably.
