### ISSUE TITLE
Fullscreen mode breaks multi-head display settings

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#5484]
Minetest at commit fbc1432fe8e821f58e97a5f35340efb2f46f93e4 (plus the "undersampling" patch), under Debian 'sid'.

Going into full screen forces all of my displays to "mirrored" mode (all show the same content), and when exiting from the game, they're all left stuck in that mode until I reset them via XFCE's display settings.

Minetest should either fullscreen just the one screen it's on and leave the others alone, or maximize itself across all of them (some users will want a way to configure which ones to use, and in what layout, if this were the case), and in any case restore the monitor layout back to normal on exit.

At the least, Chrome web browser has no problem going in/out of full screen one monitor at a time.

**Comment by sfan5** [comment]
related: #4921

**Comment by rubenwardy** [comment]
We should use a fake fullscreen rather than a real one. This is not a bug in Minetest, but simply a fact of how the fullscreen system works.

Until then, use alt+f11

**Comment by VanessaE** [comment]
Alt-F11 works perfectly; is there any reason "fullscreen" doesn't do the same thing then?

**Comment by rubenwardy** [comment]
> Alt-F11 works perfectly; is there any reason "fullscreen" doesn't do the same thing then?

It's because we are setting the fullscreen property of the render window to true (using irrlicht), rather than setting the window to borderless fullscreen. Note it's not a Irrlicht bug either, just how fullscreen mode on a window works (due to compatibility reasons)

**Comment by celeron55** [comment]
I'd like to note that the lack of support for fake fullscreen in Irrlicht can be considered to be an Irrlicht bug. We could workaround it by using the native window handles somehow probably?

**Comment by rubenwardy** [comment]
#4921
