### ISSUE TITLE
[Feature Request/Question] Changing a user's FOV in the lua API

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#5497]
I'm working on a bow and arrow mod similar to Minecraft's, but I've reached the problem of the screen zooming in whilst firing. Is this possible at the moment? (If not, just rename this to "[Feature Request] Allow changing a user's FOV in the lua API")

**Comment by C1ffisme** [comment]
Huh, I see [this](https://github.com/minetest/minetest/pull/1075), but it's been closed for a while.

**Comment by bigfoot547** [comment]
Somebody should remake it. Not me though.
Maybe me. IDK...

**Comment by paramat** [comment]
There may be a duplicate issue somewhere. No it's not possible currently.

**Comment by paramat** [comment]
Discuss in #3165
