### ISSUE TITLE
Overriding groups via minetest.override_item doesn't update ABM neighbor recognition

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#5518]
I've been attempting to modify the behaviour of the default mod's lava cooling in an another mod that depends on default and I've discovered what appears to be a bug.

Basically, I wanted to stop water_flowing from cooling lava and have it just evaporate instead. Part of how I tried accomplishing this was to remove water_flowing from the cools_lava group using override_item, but I found that ABMs were still being triggered by water_flowing as if it was still in the cools_lava group despite override_item apparently succeeding.

This is a trimmed-down version of the code I was using that illustrates the problem:

```
local water_flowing_groups = minetest.registered_nodes["default:water_flowing"].groups
water_flowing_groups.cools_lava = nil
minetest.override_item("default:water_flowing", {
    groups = water_flowing_groups,
})

default.cool_lava = function(pos, node)
	minetest.debug("overridden cool_lava")
end

local new_cool_lava = function(pos, node)
	local cooler_list = minetest.find_nodes_in_area(
		vector.add(pos,{x=-1, y=-1, z=-1}),
		vector.add(pos,{x=1, y=1, z=1}),
		{"group:cools_lava"}
	)
	for _, cooler in pairs(cooler_list) do
		minetest.debug(minetest.get_node(cooler).name)
		minetest.debug(dump(minetest.registered_nodes[minetest.get_node(cooler).name].groups))
	end

	if node.name == "default:lava_source" then
		minetest.set_node(pos, {name = "default:obsidian"})
	else -- Lava flowing
		minetest.set_node(pos, {name = "air"})
	end
end

minetest.register_abm({
	label = "New lava cooling",
	nodenames = {"default:lava_source", "default:lava_flowing"},
	neighbors = {"group:cools_lava"},
	interval = 1,
	chance = 1,
	catch_up = false,
	action = function(...)
		new_cool_lava(...)
	end,
})
```

I've disabled the default lava-cooling ABM entirely by turning default.cool_lava into a no-op, removed the "cools_lava" group from water_flowing, and created a new ABM that only looks for cools_lava nodes (not group:water). This should in theory make water_flowing no longer have any effect here.

However, I find that water_flowing still triggers this new ABM, as if it still had the cools_lava group defined. This is a snippet of my debug log showing some of the output that I get when I place a lava_source node next to some water_flowing:

```
2017-04-04 22:40:51: [Server]: overridden cool_lava
2017-04-04 22:40:51: [Server]: default:water_flowing
2017-04-04 22:40:51: [Server]: {
	not_in_creative_inventory = 1,
	liquid = 3,
	puts_out_fire = 1,
	water = 3
}
```

This suggests that both minetest.find_nodes_in_area and the ABM "neighbors" search still think that default:water_flowing belongs to group cools_lava, even though the groups listed in the registered nodes definition doesn't have it any more.

I'm on Windows 10 and using version 0.4.15-1de08e19

**Comment by tenplus1** [comment]
You can also override the active ABM itself and remove groups from neighbors.

**Comment by FaceDeer** [comment]
That won't help in this case, though. I still want to have an ABM that triggers on "cools_lava" neighbors. Whether I override the original ABM or create a new one from scratch it will still incorrectly be considering water_flowing as part of the "cools_lava" group.

**Comment by tenplus1** [comment]
Look carefully at this code: https://github.com/tenplus1/ethereal/blob/master/dirt.lua#L290

... I override 3x default Abm's within Ethereal and change nodes affectes AND neighbors.

**Comment by FaceDeer** [comment]
Interesting, I'll try that out. Usually directly editing the minetest.registered_foo tables doesn't have an effect.

Is this really a "request/suggestion" issue, Paramat? As things currently stand using minetest.override_item to change a node's group assignment puts the game into an inconsistent state - some methods recognize the change occurred whereas others do not. Seems like a straight-up bug in minetest.override_item to me.

**Comment by fozolo** [comment]
This may be related:

Normally an override does not change minetest's reported inventory size, but I've noticed that trying to override the group of a node increases the reported inventory size.  Something is going wrong when overriding groups.

**Comment by fozolo** [comment]
This happens when directly editing the `minetest.registered_nodes[nodename].groups` table as well.  So I suspect the bug is not in the override function.
