### ISSUE TITLE
bug attached entity on join server

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#5520]
if player1 is attached to a entity, when player2 join he don't look player1 at good pos, Player2 do not see player1 attached.

vidéo with player attached to cart.
https://www.youtube.com/watch?v=jTos-JLXBvU

same issue with gauges:hp_bar.
![bugattached](https://cloud.githubusercontent.com/assets/7189389/24703885/9166963c-1a05-11e7-8a1f-b4a95f24d66c.png)

**Comment by paramat** [comment]
I feel there might be a duplicate issue somewhere.

**Comment by raymoo** [comment]
@paramat #4128 ?

**Comment by rubenwardy** [comment]
I can reproduce this

**Comment by paramat** [comment]
Closing in favour of duplicate #7841 which has better discussion.
