### ISSUE TITLE
Animation in glasslike_framed is broken

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5522]
Since very recently animated blocks like homedecor's plasma_lamp is broken. Probably caused by https://github.com/minetest/minetest/commit/ea549bbae3650d246db7b70a2b07485a4b404409

Now:
![default](https://cloud.githubusercontent.com/assets/16494741/24728105/46637ebe-1a61-11e7-8263-8875ed8cfcf0.png)
Before bug:
![default](https://cloud.githubusercontent.com/assets/16494741/24510996/6e743db4-1573-11e7-8d39-43caae1650f2.png)

Node definition from homedecor:
```
homedecor.register("plasma_lamp", {
	description = S("Plasma Lamp"),
	drawtype = "glasslike_framed",
	tiles = {"default_gold_block.png","homedecor_glass_face_clean.png"},
	special_tiles = {
		{
			name="homedecor_plasma_storm.png",
			animation={type="vertical_frames", aspect_w=16, aspect_h=16, length=2.0},
		}
	},
	use_texture_alpha = true,
	light_source = default.LIGHT_MAX - 1,
	sunlight_propagates = true,
	groups = {cracky=3,oddly_breakable_by_hand=3},
	sounds = default.node_sound_glass_defaults(),
	after_place_node = function(pos, placer, itemstack, pointed_thing)
		minetest.swap_node(pos, {name = "homedecor:plasma_lamp", param2 = 255})
	end
})
```

**Comment by paramat** [comment]
As stated in the PR and forum post, this is essentially a liquid tank so needs:
`paramtype2 = "glasslikeliquidlevel",`
