### ISSUE TITLE
Persistent unique identifiers for Lua entities

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#5524]
ObjectRefs are not guaranteed to be valid between different server frames, which can cause issues when one wants to keep track of an object for whatever reason (for example, to keep track of a pathing target, or enemies). This can be worked around for players, since they have a username, but there is nothing similar for lua entities.

Lua entities should get identifiers that are unique across all entities ever created in the same world, and which are persistent across different activations of the same entity. To save memory, maybe this system should be opt-out or opt-in (by entity definition).

Possible API:
```
-- Returns an ObjectRef if there is currently an entity loaded with this ID,
-- or else returns nil
minetest.get_entity_by_id("UID")

-- Returns the unique ID of a lua entity
ObjectRef:get_entity_id()
```

**Comment by paramat** [comment]
Bump for core dev attention.

**Comment by raymoo** [comment]
numberZero thumbsed-up it, don't remember if he's a core dev

**Comment by paramat** [comment]
He isn't.
