### ISSUE TITLE
Compiler warning after commit bce0d45

### ISSUE THREAD

**Issue by t0ny2** [minetest/minetest#5536]
Commit bce0d45 introduced 2 "comparison between signed and unsigned integer expressions"
compiler warnings in client/joystick_controller.cpp

Line 173: if (id < 0 || id >= joystick_infos.size()) {

Line 178 : if (id >= 0 && id < joystick_infos.size()) {

**Comment by rubenwardy** [comment]
Already fixed

And this wasn't a bug anyway
