### ISSUE TITLE
Create API to allow safe teleporting

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#5538]
Problem:

1. player is at position p1, which is somewhere midair
2. player moves to position p2 (far from p1)
3. p1 drastically changes, but client is out of range and does not receive updated blocks around p1
4. player teleports back to p1
5. client thinks he's at p1, which previously was just all air, falls down until blocks are refreshed, and now stuck in a node, or craters

Solution: Provide an API to tell the client "You're about to teleport to X and you're going to need to update your blocks for that". The server sends the updated blocks (if needed).

```
minetest.send_block_updates(player, pos)
```

is all that would be needed. the `pos` could be converted to the smallest needed blockpos, and then the server should send the block data to the appropriate client. Immediately after, the :setpos() method can be called since the client now guaranteed has the right block data.

**Comment by sfan5** [comment]
An easier solution would be to always send the a few client mapblocks around `pos` before sending the teleport action.

**Comment by sofar** [comment]
@sfan5 agreed

**Comment by paramat** [comment]
This is an issue for a feature, it will not be remotely ready for 0.4.16.

**Comment by rubenwardy** [comment]
implemented
