### ISSUE TITLE
Death formspec not blocking other formspecs and chat screen?

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#5549]
Would it be possible also to leave the game from the death screen?

**Comment by red-001** [comment]
Since lua has access to both `core.send_respawn` and `core.disconnect` you can easily add that yourself if you don't mind messing around with formspecs.

**Comment by bigfoot547** [comment]
In mc (sorry!) you can be in the chat screen while dead. I think this is very useful, because otherwise the chat screen disappears and you need to respawn to talk.

**Comment by nerzhul** [comment]
@bigfoot547 formspec are global, changing this would require to rewrite it for all formspec on the current screen layer, it's not easy

**Comment by paramat** [comment]
:-1:
