### ISSUE TITLE
Some kinds of nodes are now colorized when they should not be.

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#5555]
Sorry I didn't catch it sooner, but the colored itemstacks change messes up nodes that have a palette specified, but which do not have a paramtype2 that supports that feature.  All such nodes used to look fine in-world, but now they're colorized in-world (but not in the inventory or wield).  The color appears to come from the first pixel in the palette file, since param2 = 0 in the affected nodes.

For example, a mod can override/redefine some generic node to include a reference to a Unified Dyes palette file and a reference to an alternate node name, which tell UD that it can swap in the alternate node and colorize it according to that palette.  Blox, Colored Wood, Unified Bricks, and Stained Glass do this with things like default stone, cobble, wood, or bricks, or some More Blocks nodes.

You don't need Unified Dyes or any other mods installed -- it is sufficient to simply add `palette = "somefile.png",` to any common minetest_game node, such as default:stone, and then provide a palette image that has some bright color in its first pixel.

**Comment by sofar** [comment]
https://github.com/minetest/minetest/commit/58d83a7bb2f992194c3df304b1dcbb81f98f78c0#diff-70868aa6d6b96c0c1623c761500d23c4L1412

The check for paramtype2 in `nodedef.cpp` was removed but never re-inserted in another codepath where relevant. It seems to confirm that the color options always apply then.

**Comment by sofar** [comment]
@juhdanad

**Comment by VanessaE** [comment]
![](http://i.imgur.com/6sI1QAH.png)

**Comment by sofar** [comment]
http://i.imgur.com/6sI1QAH.png

**Comment by juhdanad** [comment]
@VanessaE @sofar thank you for the detailed report.

The check for the node's draw type was intentionally removed: now items can also have palettes, and they don't have any draw type. The overridden items also have that palette - if you set their `palette_index`, they will be properly colored.

For all registered node definitions there is an item definition too: all nodes are also items, but their item part does not know about the node's properties.

I think the solution is that if you have a node that has a palette but not a suitable draw type, add the palette to the item (the item does not know the draw type), but not to the node (it knows that the draw type is not compatible). IMO this is the most consistent approach. (note: the item won't be colored unless it has metadata)

**Comment by VanessaE** [comment]
I think I read that right if `s/draw type/paramtype2/` ?

**Comment by juhdanad** [comment]
@VanessaE sorry, I don't understand you.

What does `s/draw type/paramtype2/g` mean?

**Comment by VanessaE** [comment]
Sorry, that's `sed(1)` shorthand (substitution, replace "draw type" with "paramtype2", global)

I was asking if you actually meant to write "paramtype2" where you wrote "draw type".

**Comment by juhdanad** [comment]
Yes, that's it. I meant  `paramtype2`.

**Comment by VanessaE** [comment]
I'm okay with however you do it -- if worse comes to worst, I can work around this "glitch" in the current implementation if I have to (though it means an API change in Unified Dyes); I just currently use the "palette" field out of convenience.
