### ISSUE TITLE
Buggy alpha behavior with hardware itemstack coloring

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#5556]
Cc: @juhdanad 

If you set e.g.

```Lua
meta:set_string("color", "#0000FF80")
```

The itemstack does not show up in the inventory or hudbar. However it you set a value greater than `80` for the alpha, the itemstack shows up.

**Comment by bigfoot547** [comment]
The reason is the same as luaentities right? Alpha 128 and above is opaque and alpha 127 and below is transparent.

**Comment by paramat** [comment]
Related #5461

**Comment by kilbith** [comment]
The inventory image could stay fully opaque, but we should be able to use the alpha channel on the coloration overlay (like `^[colorize` does).

**Comment by juhdanad** [comment]
In Minetest there are no translucent items, because alpha sorting is not implemented. An item is either opaque or transparent (invisible).

My opinion is that hardware colorization should ignore alpha.

**Comment by kilbith** [comment]
So why does `^[colorize` works with the alpha on inventory items ?

**Comment by juhdanad** [comment]
@kilbith the texture modifier affects the texture's pixels directly, and works even with separate layers. You can create a translucent layer and add it to an opaque base, the result will be opaque. When that texture is rendered, its pixels are opaque too. If you apply `colorize` to the whole texture, the item will disappear as well.

Hardware colorization is applied to the whole texture. Therefore the produced pixels are translucent, and are converted to invisible.
