### ISSUE TITLE
CSM: undocumented API calls

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#5570]
These function are present in `_G`, but not documented:

 - [ ] - find_node_near
 - [ ] - string_to_pos
 - [ ] - get_node_level
 - [ ] - override_chatcommand
 - [ ] - get_day_count
 - [ ] - get_mod_storage
 - [ ] - get_node_max_level
 - [ ] - pos_to_string
 - [ ] - splittext
 - [ ] - string_to_area
 - [ ] - get_timeofday
 - [ ] - send_respawn
 - [ ] - global_exists
 - [ ] - ~get_builtin_path~ _internal function_
 - [ ] - unregister_chatcommand
 - [ ] - ~set_last_run_mod~ _internal function_

**Comment by red-001** [comment]
https://gist.github.com/red-001/1baaf2a6e64cd75bfe97b05148c46e81

**Comment by sofar** [comment]
Updated topic, text with list so we can track.

**Comment by DS-Minetest** [comment]
Also modstorage isn't documented.

**Comment by nerzhul** [comment]
I pass this as blocker, should be done for release

**Comment by ShadowNinja** [comment]
As of right now the CSM is an unstable/unreleased feature, so I don't think this quite rises to the level of a blocker.  This should be pretty trivial to fix though.

**Comment by paramat** [comment]
#5756 merged.
