### ISSUE TITLE
Connected nodeboxes rendered incorrectly

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#5572]
Connected nodeboxes seem to be not fully rendered.
Example screenshot (technic concrete fence):

![](http://i.imgur.com/Z5Rg78j.png)

Quote from @SmallJoker:
> ah, wrong flipped nodeboxes
> with negative height/width/depth

_EDIT: Moved the screenshot to github_

**Comment by paramat** [comment]
Please can you drag and drop the image into the first post to store it at Github? An image hosting site is less reliable.

Perhaps the content_mapblock.cpp refactor? https://github.com/minetest/minetest/commit/d4e0c0f9b818120286369b33b1bdb5eb6ece7a83
@numberZero

**Comment by sofar** [comment]
Works fine for me. The image shows a non-standard node (I don't recognize the texture). Maybe the xyz pairs are input incorrectly? @Thomas--S can you paste the nodedef somewhere?

**Comment by paramat** [comment]
Could you also check the 'backface_culling' parameter for the texture?

**Comment by Thomas--S** [comment]
The source code can be found here: https://github.com/minetest-mods/technic/blob/master/concrete/init.lua#L134

@sofar I think that your (and @SmallJoker's) guess are the reason. However, I some time ago, these definitions worked fine.

**Comment by paramat** [comment]
`local box_left = {0, -0.3, -0.1, -0.5, 0.3, 0.1}`

**Comment by SmallJoker** [comment]
Should be
```Lua
local box_left = {minx, miny, minz, maxx,  maxy, maxz}
-----v
local box_left = {-0.5, -0.3, -0.1, 0, 0.3, 0.1}
```
Sorting these positions when reading the params from Lua would be helpful here.

**Comment by Thomas--S** [comment]
How about adding something like this here after https://github.com/minetest/minetest/blob/master/builtin/game/register.lua#L134

```lua
if itemdef.drawtype == "nodebox" then
	if itemdef.nodebox then
		if itemdef.nodebox.fixed then
			itemdef.nodebox.fixed = {
				math.min(itemdef.nodebox.fixed[1], itemdef.nodebox.fixed[4])
				math.min(itemdef.nodebox.fixed[2], itemdef.nodebox.fixed[5])
				math.min(itemdef.nodebox.fixed[3], itemdef.nodebox.fixed[6])
				math.max(itemdef.nodebox.fixed[1], itemdef.nodebox.fixed[4])
				math.max(itemdef.nodebox.fixed[2], itemdef.nodebox.fixed[5])
				math.max(itemdef.nodebox.fixed[3], itemdef.nodebox.fixed[6])
			}
		end
	end
end
```

**Comment by numberZero** [comment]
@Thomas--S the docs say `{minx, miny, minz, maxx, maxy, maxz}`, and `techinc` passes values in the wrong order, so that’s their bug. Nevertheless, I confirm MT had loose rules here, it had sorting in the mesh generation. Your suggestion is better, although I would prefer to raise a warning on such incorrect usage (and maybe fix the values).

**Comment by paramat** [comment]
Labelled as a request for vector sorting.

**Comment by Thomas--S** [comment]
I'll close this, as further discussion can take place in the PR: #5583
