### ISSUE TITLE
SVG Images

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#5578]
Why don't we have SVG textures in Minetest?

This would be a huge improvement the way I see it. The texture packs could potentially have a small file size, excellent for slow internet, and there could even be a setting to set the resolution of the rendered SVG images.

**Comment by sofar** [comment]
SVG textures are not efficient as every operation requires software calculations to manipulate them, and so every render step would require SVG processing from scratch.

The GPU is optimized for handling texture bitmaps. It is thousands times more efficient at doing that than SVG processing.

SVG is *nice*, but it's not *fast*.

**Comment by luk3yx** [comment]
@sofar Couldn't it render the SVGs while the game is loading?

**Comment by cheapie** [comment]
I think the idea is to render (and cache) the images during startup. The user could specify the resolution of the render, as well.

**Comment by luk3yx** [comment]
@cheapie That's what I meant by changing the resolution.

**Comment by sofar** [comment]
none of this is faster folks. Rendering SVG requires starting a full XML parser, validating the XML code, loading external entities (a HUGE security risk) and losing massive amounts of detail (since SVG can't encode or optimize noise at all).

Seriously, search for AAA 3d rendered games that use SVG for textures - there are none.

**Comment by luk3yx** [comment]
I don't see why JavaScript or external links would be necessary.

**Comment by sofar** [comment]
The SVG standard uses XML. To parse XML you need to use an XML parser. Due to the nature of XML, parsing it can invoke external XML components (not javascript, but things like DTDs) if done incorrectly, or using advanced features.

**Comment by luk3yx** [comment]
@sofar I'm assuming that Minetest will never have SVG support. Thank you for your help.

**Comment by sofar** [comment]
It would make things a lot more complicated, less portable, and not faster. SVG memory overhead is also significant, which would likely make it unusable on slow platforms.

The list against SVG goes on.

I have nothing against SVG. One of my more important work projects uses SVG and hugely benefits from its design. And for some games, like 2D games, it could be useful. Just not a 3D rendered game like minetest.

**Comment by rubenwardy** [comment]
How do we solve icons on different screen sizes? Just have massive icons?
