### ISSUE TITLE
pointed_thing has diagonal coordinates when punch the upper half of a door

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5580]
If I rightclick on the upper half of a door pointed_thing returns diagonal coordinates for above and under

for example:
```
{
	type = "node",
	above = {
		y = 3,
		x = -246,
		z = -1602
	},
	under = {
		y = 2,
		x = -246,
		z = -1603
	}
}
```

**Comment by paramat** [comment]
See discussion https://github.com/minetest/minetest_game/issues/1700
My suspicion is:
"The door top nodebox is not pointable, the door base node has a selectionbox that covers the entire door, so above / under may give diagonal positions due to this: perhaps under is the door base node but above is the position in front of the upper part of the selectionbox?"

**Comment by MarkuBu** [comment]
Ok, I placed a door at x = 0, y = 12.5 and z = 0 facing south (see screenshot). Then I placed a slab at the front of the door

```
{
	type = "node",
	above = {
		y = 14,
		x = 0,
		z = -1
	},
	under = {
		y = 13,
		x = 0,
		z = 0
	}
}
```
"under" is the position of the door, "above" is the node in front of the door

![screenshot_20170413_164758](https://cloud.githubusercontent.com/assets/16163058/25010026/061a63f0-2069-11e7-9e8f-fbd5b9d0cd69.jpg)

**Comment by MarkuBu** [comment]
If the door faces east or west the above.x is +1 or -1 to under.x

so above as always in front of the door

**Comment by paramat** [comment]
Thanks. Notice that 'above' is in front of the upper half of the door as i suspected.

**Comment by juhdanad** [comment]
The `above` field is the position where you would place a node if you right clicked.
The `under` field is the position of the node you are pointing at. It is true that the door's collision- and selection boxes exceed the source node (the lower half), but the actual information of the door - its content ID - is only stored in the lower node. And that position is the actual position of the door, this is why `under` always points to the lower half.

So `above` and `under` are not always neighbors, and this is not a bug. The engine needs both information: if someone changes the meaning of the `under` field, Minetest won't know in which node it should clear the content ID when you dig the door.

P. S.: The engine also calculates the position of the node under the `above` node, the collision point and normal [there](https://github.com/minetest/minetest/commit/3f8261830e0503cd59d8713d5c9aab12fc1491db#diff-feffcf88703db87c85c5a3f48963c01cR60), but these are not sent to the server and are not exposed to Lua.

**Comment by paramat** [comment]
Yes i agree this behaviour should not be changed.

**Comment by paramat** [comment]
#5581 merged.
