### ISSUE TITLE
Texture overlay not shown in inventory image under certain conditions

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#5582]
A texture overlay is not shown in the auto-generated inventory image under certain conditions:

- The node is a connected nodebox
- The tiles have to be defined in a certain way, I haven't found the exact point yet.

This bug can be reproduced with the [Streets 2.0 Mod's traffic barrier](https://github.com/minetest-streets/streets/blob/master/streets_roadwork/init.lua#L10)

EDIT:
I'll post the nodedef for reproducing the bug here. I will push a workaround to the streets mod master branch soon.
```lua
minetest.register_node("streets:roadwork_traffic_barrier", {
	description = "Traffic Barrier",
	paramtype = "light",
	drawtype = "nodebox",
	tiles = { streets.concrete_texture, streets.concrete_texture, streets.concrete_texture .. "^streets_roadwork_traffic_barrier.png" },
	sunlight_propagates = true,
	groups = { cracky = 1, level = 2, wall = 1 },
	node_box = {
		type = "connected",
		fixed = { { -0.35, -0.5, -0.35, 0.35, -0.4, 0.35 }, { -0.15, -0.5, -0.15, 0.15, 0.5, 0.15 } },
		connect_front = { { -0.35, -0.5, -0.5, 0.35, -0.4, 0.35 }, { -0.15, -0.5, -0.5, 0.15, 0.5, 0.15 } }, -- z-
		connect_back = { { -0.35, -0.5, -0.35, 0.35, -0.4, 0.5 }, { -0.15, -0.5, -0.15, 0.15, 0.5, 0.5 } }, -- z+
		connect_left = { { -0.5, -0.5, -0.35, 0.35, -0.4, 0.35 }, { -0.5, -0.5, -0.15, 0.15, 0.5, 0.15 } }, -- x-
		connect_right = { { -0.35, -0.5, -0.35, 0.5, -0.4, 0.35 }, { -0.15, -0.5, -0.15, 0.5, 0.5, 0.15 } }, -- x+
	},
	connects_to = { "group:wall", "group:stone", "group:wood", "group:tree", "group:concrete" },
	sound = default.node_sound_stone_defaults()
})
```

**Comment by numberZero** [comment]
Duplicate of #6536; that’s not a texture overlay but the 3rd texture (which only happens to be a combination of two) not shown.
Should have been fixed by #6596 and #6780.

**Comment by Thomas--S** [comment]
Thanks for your comment, I'll test it soon (maybe tomorrow).

**Comment by Thomas--S** [comment]
I can confirm that this problem is solved in the latest minetest version. Thanks for fixing it!
