### ISSUE TITLE
Backspace stops working in formspecs

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5587]
During the bug: typing and space work, but backspace and left/right arrows are not. If I use arrow up or down or by clicking other position with mouse - bug goes away.

Ways to reproduce:
+ Write a book with multiline text and save it. Open a book again and click to very end after the text and try to backspace or start typing and then try to backspace.
+ Alt-Tabing several times while writing the book may cause this problem, but I'm not 100% sure

Reproduced on newest minetest_game. @sofar and @octacian also seen this.

DEMO on how to reproduce, what is interesting, backspace started working again somehow near the end of the gif.
![test](https://cloud.githubusercontent.com/assets/16494741/23777600/897546f2-053e-11e7-8475-89ff553083f7.gif)

Update: moved the bug into engine section from here https://github.com/minetest/minetest_game/issues/1614

**Comment by cheapie** [comment]
I've found that sometimes (but not all the time) mashing backspace enough gets it to work, as if the insertion point is past the end of the text.

**Comment by nerzhul** [comment]
since recent fix on keys is this always the case @Fixer-007 ?

**Comment by Fixer-007** [comment]
Will check.

**Comment by nerzhul** [comment]
Re-tested fixed for me, if you are okay, please close it
