### ISSUE TITLE
Libraries for the android app

### ISSUE THREAD

**Issue by Olexandr1904** [minetest/minetest#5588]
Where I can find this libraries
System.loadLibrary("openal");
System.loadLibrary("ogg");
System.loadLibrary("vorbis");
System.loadLibrary("ssl");
System.loadLibrary("crypto");
doesn't work without them

**Comment by rubenwardy** [comment]
Did you run the make file?

What OS are you compiling on?

**Comment by nerzhul** [comment]
Those libraries are downloaded by the Makefile
