### ISSUE TITLE
Setting view bobbing = false disables walking sound

### ISSUE THREAD

**Issue by Xanthin** [minetest/minetest#5602]
When I set `view_bobbing = false` to "[disable] view bobbing when walking" I get no walking sound. Jump, build, dig, damage sounds are not affected.

Tested on todays build (without any additions) on Xubuntu 14.04 x64. I added just this line in the autogenerated minetest.conf.

**Comment by paramat** [comment]
I always have view bobbing false and footsteps play for me.

**Comment by paramat** [comment]
Will test.
Interestingly we have 2 settings for view bobbing and one is redundant.
I use `view_bobbing_amount = 0` instead and that doesn't stop footsteps.

**Comment by Xanthin** [comment]
Yes, that's what I used before and now again without any issues.

**Comment by desttinghim** [comment]
I have fixed this bug in PR #5645, so this can be marked as closed (once #5645 is merged in).

**Comment by Zeno-** [comment]
db17225a976e
