### ISSUE TITLE
Add the ability of changing the progress bar background depending of the subgame background

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#5605]
Add the ability of changing the progress bar background depending of the subgame background

**Comment by tacotexmex** [comment]
What if… ![image](https://cloud.githubusercontent.com/assets/25328789/25280189/58b02ea6-26a9-11e7-86c1-b0114a7a6867.png)

**Comment by Fixer-007** [comment]
Except nyan, since it is trademarked.

**Comment by masrourmouad** [comment]
i mean change the loading page background depending on the subgame background.

**Comment by nerzhul** [comment]
it's impossible to know which subgame we are loading in multiplayer. On singleplayer is can be possible but very hacky

**Comment by C1ffisme** [comment]
@nerzhul Would it be possible to send 1 or 2 images over the internet before node definitions and media have been sent? That might work. Before the images are sent, it will just use the generic loading bar. (Or it could cache loading bars from different servers, although that means you store old loading bars from ancient servers.)

**Comment by masrourmouad** [comment]
i think that it makes sense that when you are playing in a subgame, the background of the subgame loading page, should be the same as the menu of the subgame.

**Comment by nerzhul** [comment]
@C1ffisme definitively not, it's a pure hack

**Comment by paramat** [comment]
:-1:
