### ISSUE TITLE
If inventory is opened while digging, the crack overlay remains until looking away from the node

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#5611]
Funny bug I found while testing tool caps stuff.

To reproduce:
1) Equip some slow digging tool (your hand is fine)
2) Start digging something that will take some time to dig (but not forever)
3) Before you are finished digging, press the inventory key while still holding the dig control
4) close the inventory
5) Look at the node and see that it still has the crack texture
6) Look away from the node
7) Look at the node again and see that it is gone

**Comment by bigfoot547** [comment]
Same with anything that frees your cursor. (eg. death formspec, escape menu, any formspec)

**Comment by appgurueu** [comment]
Can confirm with 5.4
