### ISSUE TITLE
minetest.request_shutdown("whatever", true) does not cause the client to display a reconnect button.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#5617]
Also, it appears that the message specified in "whatever" is not sent to the client, either, causing a generic shutdown message to be displayed instead of the custom message.

**Comment by red-001** [comment]
Linked to 34d32ce55ae4f3f29d7b645075dc8efacb2c96d2?

**Comment by orwell96** [comment]
Issue lies in server.cpp:3480
If delay is 0, it forgets to set m_shutdown_msg and m_shutdown_reconnect...

**Comment by orwell96** [comment]
Fixed by #5621, please test it, I can't test it at the moment.

**Comment by BluebirdGreycoat** [comment]
I was working on a fix too before I saw you had one. At at glance it looks like your is better though. I will try to test it as soon as I can.

**Comment by BluebirdGreycoat** [comment]
It works for me.
