### ISSUE TITLE
Entity detatchment problem

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#5620]
When detatching the player from an entity the player model doesn't simply appear at those coordinates, instead it slides in from 0,0,0 position which is quite visible.

**Comment by SmallJoker** [comment]
Related: #4580

**Comment by tenplus1** [comment]
@SmallJoker - for example, for playerplus mod's knock-back effect I create an invisible entity, attach player to entity and on detach (away from 0,0,0) you see the player slide back to position.

**Comment by stujones11** [comment]
@tenplus1 that seems like a very complicated way to do knockback, could you not just use `player:move_to()`? Off-topic, I know, this bug does need to be fixed regardless. I have noticed this myself in other situations.
