### ISSUE TITLE
Special drawtypes appear cyan

### ISSUE THREAD

**Issue by MirceaKitsune** [minetest/minetest#5631]
After updating to latest Git master and recompiling the engine, I noticed a strange issue is now occurring: Drawtypes other than the standard block seem to be colorized in a green / cyan color. I haven't yet tested if this is caused by shaders, and which in particular if so.

As a reminder, I run Minetest on Linux and use the free video drivers (Mesa 17.0.3). My video card is a Radeon R7 370, GCN 1.0 / RadeonSI.

![screenshot_20170421_171931](https://cloud.githubusercontent.com/assets/825418/25281686/c1c3319c-26b6-11e7-89ed-ccaafcc2b0c3.png)

**Comment by Fixer-007** [comment]
>Taoki: Fixer: The problem no longer exists with that commit! So it is introduced after 2ad74a9e8b9da48aef62346de6cd55f304c6440d

So it is probably caused by "Soft node overlay" commit https://github.com/minetest/minetest/commit/1ffb180868ffcec6812cd3aac8f56ffefb91c8bc

@juhdanad

**Comment by MirceaKitsune** [comment]
Yes, I just ran the test: Upon switching to commit 2ad74a9e8b9da48aef62346de6cd55f304c6440d I don't have this problem. The only commit after it is 1ffb180868ffcec6812cd3aac8f56ffefb91c8bc labeled "Soft node overlay". The logical conclusion is that it was introduced in today's latest change.

**Comment by Fixer-007** [comment]
Also crashes on exit from the world/game.

**Comment by Fixer-007** [comment]
Fixed for me

**Comment by MirceaKitsune** [comment]
Fixed for me as well, thank you!
