### ISSUE TITLE
Tests create files in current directory

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#5643]
`test_player.cpp`  creates two files, `testplayer_load` and `testplayer_save`, in the current directory, and doesn't clean them up.  These files should be written to a temporary directory (i.e. `/tmp/` and removed after the tests.
To reproduce simply run `minetest --run-unittests`.

**Comment by nerzhul** [comment]
It's exact the only problem is /tmp doesn't exists on windows :)

**Comment by red-001** [comment]
%temp%

**Comment by nerzhul** [comment]
please note this test will be disabled by #5475

**Comment by nerzhul** [comment]
#5475 is now merged
