### ISSUE TITLE
minetest.get_node seemingly returning incorrect node

### ISSUE THREAD

**Issue by evrooije** [minetest/minetest#5648]
I am trying to determine the node type at or underneath a player using minetest.get_node. It is showing strange behavior. When I test for node name "ignore" and retry after 5 seconds using minetest.after, sometimes it keeps retrying forever, the get_node function always returning "ignore". I stripped my mod to the bare minimum, and now it correctly retries a couple times. Sometimes 1 or 2, in the screenshot quite a bit more, but on my server it looks like it takes forever.

Now the bigger problem is, at some point get_node indeed no longer returns "ignore", but I am actually getting "default:water_source" now even though I am standing on grass and in the air ... And it looks like every call returns the wrong node type when the next minetest.after is called. Could not find anything related besides issues that get_node returns "ignore", but during map loading that it is to be expected (hence my guard code to retry using minetest.after). But to eventually return the wrong node is a bit unexpected. Am I doing something wrong here?

See screenshot and init.lua attached:

![get_node_issue](https://cloud.githubusercontent.com/assets/17067614/25313757/756e7376-2835-11e7-90f7-f6dc3c4c69f7.png)
[init.lua.txt](https://github.com/minetest/minetest/files/949722/init.lua.txt)

Mods in use when this happens:
evrooije@basilisk:~/minetest/games/sandbox/mods$ ls
00_bt_music  bones   creative  dye      flowers             screwdriver  stairs   walls
beds         bucket  default   farming  give_initial_stuff  sethome      tnt      wool
boats        carts   doors     fire     killme              sfinv        vessels  xpanes

Minetest master:
evrooije@basilisk:~/minetest/bin$ git rev-parse --short HEAD
dc0e909

Compile flags:
cmake . -DENABLE_GETTEXT=1 -DENABLE_FREETYPE=1 -DENABLE_LEVELDB=1 -DENABLE_REDIS=1 -DBUILD_CLIENT=1 -DBUILD_SERVER=1 -DCMAKE_BUILD_TYPE=Release -DRUN_IN_PLACE=1 -DENABLE_SPATIAL=1 -DENABLE_SOUND=1 -DENABLE_LUAJIT=1 -DENABLE_SYSTEM_GMP=1 -DENABLE_SYSTEM_JSONCPP=1 -DVERSION_EXTRA=Beerholder-dev

I did an override of FindJsonCpp but I also did hard reset of my local copy, recompiled -DENABLE_SYSTEM_JSONCPP=0 and it shows the same behavior.

**Comment by evrooije** [comment]
P.s. I think/ am assuming this is something in the Lua API, and I can probably have a look at the code myself some time. If this is somehow not core engine and related to minetest_game or me just being stupid, let me know and I'll raise the issue on the game or in the forum!

**Comment by t0ny2** [comment]
Your table definitions are incorrect, they should be:

{x = pos.x, y = pos.y, z = pos.z}

**Comment by evrooije** [comment]
Ugh of course O_o Sigh I am such a noob -_- Thanks t0ny2 that was indeed the problem, issue can be closed and I should've first posted in the forum. Guess I've been staring to long at this last night ;)
