### ISSUE TITLE
LBM idea: add option like 'run_once_per_load_per_session'

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#5650]
This is an idea to slightly improve the usability of LBMs. Currently, we can set `run_at_every_load = true` (intended to run the associated function every single time the block is loaded), or we can set `run_at_every_load = false` (such as in the case of node or metadata replacements), which means the action will only be run once per block and never again.

The first option can imply a high performance cost however, if the associated action executes a lot of code (example: a complex algorithm for choosing locations to spawn mobs). The second option is no good at all for non-utility/maintenance purposes, since it was specifically designed for upgrading old worlds, not for gameplay related logic.

What I propose is an in-between option, perhaps called `run_once_per_load_per_session = true`. Quite simply, it means that the associated function would be run only once per mapblock load, and not again, *until* the server is restarted. You could think of it as sort of like a soft version of `run_at_every_load = false`, the main difference being that the server would *not* record the execution in the map database that is stored on disk, so that the function gets executed again the next time the server loads the block (which would be after the server restarts). A quick glance at the server list shows that a typical server restarts every day or so.

Example use-case: think of all those mob-spawning ABMs that could be replaced with something like the LBM modification that is proposed here.

**Comment by tenplus1** [comment]
We still need a neighbors flag for this to be viable in spawning mobs, otherwise it will check each and every node they spawn on instead of the one's near air/grass/etc.

**Comment by BluebirdGreycoat** [comment]
I have created a pull for this idea: #5653.

**Comment by paramat** [comment]
1 year bump for more core dev consideration.
