### ISSUE TITLE
Occasional error in chat after starting the sinleplayer world (dropping packet)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5655]
It is not really a problem since everything is working, but the fact of red error text appearing in chat may indicate something is not working as expected, or maybe it has to be hidden from usual player.
Engine af96309, to reproduce start a singleplayer world (or maybe few times).
```
ERROR[Server]: Got packet command: 65 for peer id 2 but client isn't active yet. Dropping packet 
```

**Comment by Wayward1** [comment]
I experienced this as well today, using Linux Mint 17.3

**Comment by desttinghim** [comment]
I have also experienced this bug, using elementary OS 0.4 Loki

**Comment by sfan5** [comment]
it's a `TOCLIENT_PRIVILEGES` (0x41) packet btw

**Comment by t0ny2** [comment]
I think it is actually a TOSERVER_RECEIVED_MEDIA which was removed from the server code in commit 0C34FE2, but is still being sent by Client::received_media()

**Comment by red-001** [comment]
looks like you are right 142e2d3b74ad886eed83b0fc9d6cfea100dae10a stopped using `TOSERVER_RECEIVED_MEDIA` but it's still being sent by the client.

**Comment by red-001** [comment]
see #5658
