### ISSUE TITLE
Asynchronous logging

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#5664]
Logging is synchronous, which can slowdown server or client if many logs are generated on a console.

Make logging asynchronous using a MutexQueue and a dedicated thread.

Maybe we should use a logging library which does nice logs, like log4cpp which is quite standard in professionnal CPP project and use a log4j like methods (which is a java standard in spring environments)

**Comment by HybridDog** [comment]
The info, verbose and trace log messages, which appear very frequently, are also generated when they aren't printed, am l right?
So would removing them increase performance, e.g. because unused strings aren't longer put into the processor cache?

**Comment by rubenwardy** [comment]
I really like https://github.com/emilk/loguru
