### ISSUE TITLE
Implement attached particle spawners.

### ISSUE THREAD

**Issue by Splizard** [minetest/minetest#567]
Allow a parameter to minetest.add_particlespawner which takes an entity to attach to.
The positions parameters would then work out relative to the entity.
For things like weather this would allow smooth particle spawning during player movement.

**Comment by neoascetic** [comment]
+1

**Comment by C1ffisme** [comment]
:+1:

**Comment by raymoo** [comment]
Could be used for projectiles (magical, missiles?) to leave some sort of trail

**Comment by Fixer-007** [comment]
+1

**Comment by 0-afflatus** [comment]
:+1:

**Comment by nerzhul** [comment]
Closing this issue as #4409 has been improved and will be merged
