### ISSUE TITLE
Entity rendering problems

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5671]
IIRC protector redo renders its protection zone by creating an entity, I've noticed very recently that rendering of this entity after punching the node goes away if I face opposite direction from it. It seems there was a change in an engine related to this. Is this a bug or was intended?

Demo: https://imgur.com/a/JUZZi
Protector redo repo: https://github.com/tenplus1/protector

Bisected it: 1ffb180 "Soft node overlay (#5186)" caused this problem.

**Comment by sfan5** [comment]
Can't see any difference between 1670bc73 (26apr) and 6120251 (17apr, from issue desc) with the box WorldEdit uses to display selection

**Comment by Fixer-007** [comment]
Bisect results: https://github.com/minetest/minetest/commit/1ffb180868ffcec6812cd3aac8f56ffefb91c8bc caused this.

**Comment by paramat** [comment]
The entity is not rendered when you are not facing it, seems correct behaviour even if it didn't do this before, possibly even an improvement.

**Comment by sfan5** [comment]
Even if this isn't a bug it seems to be a regression...

**Comment by Fixer-007** [comment]
This is regression, since I don't see it mentioned anywhere in said PR/commit.

**Comment by raymoo** [comment]
Maybe the code should always render the entity if the camera is "inside" it (by some heuristic).

**Comment by Fixer-007** [comment]
Observation: connected to Hometown, number of particles raised pretty quickly and stabilised at 200-300 for very long time (sometimes going as high as 700), I do quick restart and it suddenly goes back to 20-30 particles... this huge particle count may also be linked to my poor fps at times.

**Comment by raymoo** [comment]
Or allow entities to define a rendering aabb separate from the collision box and use that to determine if the camera is inside the object.
