### ISSUE TITLE
Change inventory image using Itemstack Metadata

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#5686]
A fourth key for itemstack metadata, one that allows on the fly changing of texture of any itemstack, whether it's a tool, hand, craft item and / or node using inventory_image.

Suggested usage, giving players a hand based on https://github.com/jordan4ibanez/newhand (Updating it to use any of the many existing skins mods wouldn't be generally too difficult)

Example for a hand that gets a new texture based on a skin;

    minetest.register_on_joinplayer(function(player)

        local pname = player:get_player_name()
        local stack = player:get_inventory():get_stack("hand", 1)
        stack:set_name("newhand:hand")
        local meta = stack:get_meta()
        meta:set_string("texture_string", "player_" .. pname .. ".png")
        player:get_inventory():set_stack("hand", 1, stack)

    end)

Alternatively, after a book has been written; it could have a small red ribbon on it after being wrote to;

    local meta = stack:get_meta()
    meta:set_string("texture_string", "default_book_written.png")

This saves using up a item registry.

There might be other use cases where on the fly itemstack re-texturing might be useful. (Especially in the case of custom skins, nobody likes a static hand that doesn't look like them.)

**Comment by LunaSquee** [comment]
I support this idea. It would really come in handy.

**Comment by paramat** [comment]
1 year bump for core dev opinons.

**Comment by raymoo** [comment]
Not a core dev, but I think it would be just as useful as dynamic text. They are both used to display item stacks specific information.

**Comment by paramat** [comment]
Assuming support from rubenwardy as re-opened.

**Comment by rubenwardy** [comment]
wtf

![image](https://user-images.githubusercontent.com/2122943/48905490-9a1ea600-ee59-11e8-9061-518045a7b367.png)

**Comment by SmallJoker** [comment]
Bounty: https://www.bountysource.com/issues/44703548-change-inventory-image-using-itemstack-metadata

**Comment by paramat** [comment]
Rubenwardy, to explain, at the time, 'core dev opinions needed' was a (poorly worded) label added to feature requests over a year old but with no core dev support, and therefore about to be closed. It was a way to search for such issues.
Even after bumping and adding the label, no core devs stated support in the following 2.5 months, so it was closed.

**Comment by velartrill** [comment]
this would be an enormously helpful addition and extremely useful for the mod i maintain (i could collapse ~100 generated items into a single item, among other things); however i'm concerned about the impact on the `override.txt` mechanism in texturepacks.

it'd take a bit more work but i'd suggest changing the format of the `texture_string` property to something like *`<state>`*`:`*`<texspec>`*, where `<state>` is a short label describing the change made to the inventory image, and then `<texspec>` would hold the actual texture spec itself. then override.txt could be altered to allow lines like `mymod:bow inventory:arrow_loaded my_drawn_bow.png` to override a specific state of the item (this is necessary because it might not be possible to achieve the texturepack author's desired effects simply by changing the textures used to compose the dynamic texture)

i'd be inclined to make the state field mandatory because most modders probably won't use it otherwise, but we could also just allow a `:<texspec>` format specifier if the author doesn't want texture packs overriding the image, or if the logic involved is too complex for discrete overrides to be useful

**Comment by MisterE123** [comment]
bump, maybe for 5.6?

**Comment by LandonAConway** [comment]
I'd like to also bump this topic again. This feature could be incredibly useful and would prevent us from needing to register 100+ items simply for different textures. Sure, we have the ability to change the color of a stack but not the texture alltogethor.

**Comment by S-S-X** [comment]
Some time ago I wanted to try how this would work in game and put together simple test, not going to work on this myself but here if anyone finds it useful:
```diff
diff --git a/src/client/hud.cpp b/src/client/hud.cpp
index e08d2ef02..3c0dc88ec 100644
--- a/src/client/hud.cpp
+++ b/src/client/hud.cpp
@@ -1106,7 +1106,13 @@ void drawItemStack(
 
                draw_overlay = def.type == ITEM_NODE && def.inventory_image.empty();
        } else { // Otherwise just draw as 2D
-               video::ITexture *texture = client->idef()->getInventoryTexture(def.name, client);
+               video::ITexture *texture;
+               const std::string &texturestring = item.metadata.getString("inventory_image", 0);
+               if (!texturestring.empty()) {
+                       texture = client->idef()->getInventoryTexture(texturestring, client);
+               } else {
+                       texture = client->idef()->getInventoryTexture(def.name, client);
+               }
                video::SColor color;
                if (texture) {
                        color = client->idef()->getItemstackColor(item, client);
```

**Comment by velartrill** [comment]
as i indicated on #9354 im willing in theory to take the PR over and continue it, but i would need some assurance from the core devs that the existing code is OK and the PR will likely be accepted if i complete it; i don't want to end up wasting time on something that never goes anywhere (i already have one major PR that's been languishing for half a year now)

**Comment by rubenwardy** [comment]
> as i indicated on #9354 im willing in theory to take the PR over and continue it, but i would need some assurance from the core devs that the existing code is OK and the PR will likely be accepted if i complete it; i don't want to end up wasting time on something that never goes anywhere (i already have one major PR that's been languishing for half a year now)

Yes, I'll review it if made. Would like to see this

**Comment by velartrill** [comment]
alright, i will add this to my to-do list. caveats: the particlespawner animation pr is still my priority until it's merged and i have personal projects to work on as well, but I'll try to pick this up soon. if anyone else is interested in working on this i would welcome their assistance

**Comment by JurajVajda** [comment]
Hi just popping in, see some traction on this feature. Any plan on this to be included in the future release(s)?

**Comment by rubenwardy** [comment]
Yes, I've implemented most of it - just need some time to polish it up. I'm hoping to get it in for 5.7.0

**Comment by JurajVajda** [comment]
Any updates on this one please?

**Comment by JurajVajda** [comment]
not in 5.7 but hope for the best in the future
