### ISSUE TITLE
Add "find_lightlevel_near" function

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5688]
Like the `find_node_near` function finds a given node it would be nice to have a `find_lightlevel_near` function. As parameters a max and min value can be given. For example

`find_lightlevel_near(max = 10)`

returns the nearest node with a lightlevel of 10 or below

`find_lightlevel_near(min = 5, max = 10)`

returns the nearest node with a lightlevel between (including) 5 and 10

**Comment by sfan5** [comment]
This is triviálly done in Lua, how big of an area do you want to search the C++ makes a difference?

**Comment by MarkuBu** [comment]
A radius of 20 nodes or more maybe. Not sure what I will need

Do you mean to use voxelmanip?

**Comment by DS-Minetest** [comment]
(@MarkuBu I think, you forgot the `{`s and `{`s since something like `foo(bla = 1)` makes no sense AFAIK.)

**Comment by MarkuBu** [comment]
It is just pseudo code, not actual lua code. Of course you need {}

**Comment by paramat** [comment]
A radius of 20 is a huge volume, that's where 'find nodes in area' hits a limit.
This seems quite specialised, probably too much so for the engine.

**Comment by MarkuBu** [comment]
I think this should be done in C++ because in Lua it is to slow

**Comment by paramat** [comment]
Yes it's faster in C++, but what decides inclusion in the engine is widespread usefulness and need.

**Comment by paramat** [comment]
Author left MT and no other support.
