### ISSUE TITLE
Add Carbon to Minetest

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5690]
I found the Carbon Standard Library for Lua and I think this would be a great addition to Minetest.

https://github.com/lua-carbon/carbon

The licence (zlib/libpng) should be ok.

If some modules may cause security issues I think they can be removed.

Would that be an option?

**Comment by Calinou** [comment]
What's the practical use cases in making Minetest mods?

**Comment by MarkuBu** [comment]
Carbon adds lots of mathematical functions for vectors and matrix, OOP, collection (like lists) and a lot of other stuff I didn't understand yet

**Comment by sfan5** [comment]
You didn't fully understand its features, yet you suggest including it in it's entirety.
wat

**Comment by MarkuBu** [comment]
I understand enough to decide that it is useful

**Comment by MarkuBu** [comment]
Maybe it's not such a good idea. It seems that this project is maintained by only one developer and it looks dead since 2 years.
