### ISSUE TITLE
Misleading error message when connecting to a server while bootup/shutdown

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#5691]
When a client tries to connect and the target server is in the process of booting up or shutting down, the client sees an error message about "init packet not sent, tell the admin to update their server version" which is very misleading because players now think that the admin really didn't update the server in a long time.

I receive such messages a lot where players advise me to update the server and it starts to annoy me honestly...I suggest to check the exact status of the server when a client connects and THEN show an error like "Server could not respond to your request, please try again later".

**Comment by Zughy** [comment]
I can't reproduce this on a local server using two clients, can anyone double-check?
