### ISSUE TITLE
Assign Up/Down/Left/Right Arrow keys to Up/Down/Left/Right mouse movements.

### ISSUE THREAD

**Issue by slemonide** [minetest/minetest#5696]
And assign Enter/Backspace as right/left mouse clicks..

This should make the game more playable when there is no access to the mouse.

**Comment by Thomas--S** [comment]
#5699

**Comment by dsohler** [comment]
Instead of hardcoding another key-to-action set maybe finally allow to configure all action to be triggered with all keys/buttons.

**Comment by rubenwardy** [comment]
> Instead of hardcoding another key-to-action set maybe finally allow to configure all action to be triggered with all keys/buttons.

That's not what this pr does, also that would be a massive change

**Comment by slemonide** [comment]
Also, it could be easier to use this feature if **build**/**remove** keys were in the same keyboard row. For example, if **ENTER** placed a node and **L** removed a node (though, I guess it wouldn't be as good as mouse anyway).

**Comment by Thomas--S** [comment]
I don't know if **`Enter`** and **`L`** would be a good choice ...
At least on a german keyboard (I assume its the same for US ones), you can't reach the **`L`** and the arrow keys at the same time.
However, if you personally prefer **`Enter`** and **`L`**, you can customize the settings.

**Comment by slemonide** [comment]
Well, depends on the keyboard.

**Comment by dsohler** [comment]
> At least on a german keyboard (I assume its the same for US ones), you can't reach the L and the arrow keys at the same time.

It is. And it is for all other relevant layouts, too. L is one of the least reachable keys in relation to the arrow keys and WASD.

**Comment by slemonide** [comment]
Unless it's a micro-keyboard.

**Comment by wilkgr76** [comment]
I would, as a desktop user, prefer right ctrl and numpad 0, which are near the arrow keys.

On the other hand, using IJKL for look directions and U and O for digging and placing, and moving the fly-fast-noclip keys to V, B and N respectively.

**Comment by rubenwardy** [comment]
You should use an accessibility key program to do this (moving mouse with arrow keys). In future I'd like actions such as camera rotation and such to be freely bindable, but not mouse moving
