### ISSUE TITLE
Client crash on older server after #bd921a7

### ISSUE THREAD

**Issue by t0ny2** [minetest/minetest#5698]
When connected to a pre #bd921a7 server the client will attempt to read a non existant fade value from a TOCLIENT_PLAY_SOUND packet. This results in a PacketError exception, but the code in handleCommand_PlaySound() is catching a SerializationError exception. Consequently the client crashes.

**Comment by SmallJoker** [comment]
Are you sure it's a SerializationError?
https://github.com/minetest/minetest/blob/master/src/network/clientpackethandler.cpp#L781-L783
