### ISSUE TITLE
Yellow clouds at dawn/dusk

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5701]
All screenshots with all shaders disabled (shaders master setting off).
I suspect this bug started with the clouds API commit which altered how clouds are coloured, but i have not bisected to be sure.
Yellow clouds occur from 19000 to 19250.
This 'yellow' is always R and G equal with B much lower.

The `cloudcolor_bright_dawn_f` orange cloud effect was active from 18500 to 19000 in earlier versions of MT, but does not occur in latest master (see comments below. This may or may not be related to the yellow clouds, and the lack of orange colouring may have started at a different time).
EDIT: See comments below, the new MT light curve has probably moved the time of orange clouds from 18500-19000 to 19000-19250, so orange colouring has not been broken.

@bendeutsch 

![screenshot_20170502_223951](https://cloud.githubusercontent.com/assets/3686677/25640687/7012e272-2f88-11e7-9964-12017f7346b9.png)

![screenshot_20170502_230536](https://cloud.githubusercontent.com/assets/3686677/25641432/f113078c-2f8b-11e7-924b-c77d49b803f1.png)

^ Latest master at time 19125 with directional coloured fog enabled.
The cloud colour looks ok when looking at the moonrise, but goes yellow when looking at the sunset.
My guess is that directional coloured fog is altering cloud colour to make a more intense yellow in one direction and cancels-out yellowness in the other direction.

![screenshot_20170502_230300](https://cloud.githubusercontent.com/assets/3686677/25641362/9e36a226-2f8b-11e7-9233-f055d63304c5.png)

![screenshot_20170502_230253](https://cloud.githubusercontent.com/assets/3686677/25641366/a19f3cd4-2f8b-11e7-8a8e-e8733e4d6dcf.png)

^ Latest master at time 19125 with directional coloured fog disabled.
Clouds are a constant yellow viewing in both directions.

![screenshot_20170504_061618](https://cloud.githubusercontent.com/assets/3686677/25691291/48d92ca2-3091-11e7-83e6-af4e931e774e.png)

^ 0.4.15 stable at time 19125 with directional coloured fog disabled.

**Comment by sofar** [comment]
I don't see anything wrong with it, the red intensity makes the colors all shift and create a greater contrast, just like tonemapping would.

Leave as is.

**Comment by sofar** [comment]
Oh, wow, yes, without tonemapping enabled it's terrible

- OK without shaders
- OK with shaders AND tonemapping
- BAD with shaders but without tonemapping

**Comment by paramat** [comment]
![screenshot_3519010682](https://cloud.githubusercontent.com/assets/3686677/25690751/2711983e-308c-11e7-89b6-8303fcba960e.png)

^ 0.4.8 which is before the directional coloured fog feature.
Here the orange cloud effect is active from 18500 to 19000. Not saying this should be recreated, but cloud colouring at dawn/dusk may have broken somewhere since 0.4.8.

**Comment by paramat** [comment]
![screenshot_20170504_054656](https://cloud.githubusercontent.com/assets/3686677/25690847/4340bee4-308d-11e7-8768-fd0c3dae2f4f.png)

^ 0.4.15 stable also at 18750 with directional coloured fog disabled.
Sampling clouds shows they are indeed orange coloured, just more subtly, so orange cloud colouring is still working in 0.4.15 stable.

**Comment by paramat** [comment]
Yellow clouds occur from 19000 to 19250, so happen after the orange cloud colouring stops at 19000.

**Comment by paramat** [comment]
![screenshot_20170504_060908](https://cloud.githubusercontent.com/assets/3686677/25691194/7b36fa68-3090-11e7-9cda-9a0080751bcf.png)

^ 0.4.15 dev latest master at time 18750 with directional coloured fog disabled.
The clouds have a blue hue, bluer than daytime, so orange colouring is not in effect anymore.

**Comment by bendeutsch** [comment]
Hi, sorry I'm only intermittently online – there was no purposeful color change introduced during the clouds API pull request, provided the default colors are not changed. If this bug shows different behaviour before and after the clouds API, then that's a bug of course.

One note on cloud colors at specific times: In https://github.com/minetest/minetest/blob/master/src/sky.cpp#L567 and https://github.com/minetest/minetest/blob/master/src/sky.cpp#L582, the sky color is gradually moved towards the "actual" color, so if you load a world in different versions of minetest to compare colors, you'd have to rewind time a bit and wait for the color to "settle". I'm not sure how strong this effect is, but it should be taken into account.

**Comment by MirceaKitsune** [comment]
I implemented the directional fog and cloud colors, however this was long ago so I don't remember specific code details. All I can say is that, clouds changing color together with the fog is itself intentional. I'm not sure if it should be doing it quite as much as in the first screenshot, but the last 3 screenshots above look perfectly normal to me and likely represent the intended effect.

**Comment by paramat** [comment]
> clouds changing color together with the fog is itself intentional.

Yes.
No problem, the last 3 screenshots are just to keep track of the classic dawn / dusk cloud colouring (without your feature enabled) and how it has changed, as it may be relevant to this bug.
I will do some bisecting next.

**Comment by bendeutsch** [comment]
I've just compared two builds from before and after the cloud API change (no shaders, no directional fog), using a constant output of the resulting cloud color:

```
dstream << c_top.getRed() << ", " << c_top.getGreen() << ", " << c_top.getBlue() << std::endl;
```
just after the individual colors of the cloud parts are calculated around line https://github.com/minetest/minetest/blob/master/src/clouds.cpp#L160.

There is an actual difference in colors during the dawn phase which I can't quite explain. While the "pre-API" version has more red, medium green, and low blue during the most colorful phase, the "post-API" version seems to have equal red and green, with less blue. So "pre" is more orange, and "post" is more yellow.

It could be that my refactoring of the dawn coloring did not work as expected. Specifically, I don't think I ever really checked that the R channel of the dawn cloud color in sky.cpp is actually above 1.0…

**Comment by bendeutsch** [comment]
Probably the simplest "fix" would be to set `cloudcolor_bright_dawn_f` in `sky.cpp` to a real pale orange, without the super-saturated R channel. Clouds would be a bit dimmer at dawn, but the hue would behave correctly, at least… maybe worth a try?

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/5692#issuecomment-299077826 and next comment, i tried altering `cloudcolor_bright_dawn_f` in several ways, even changed it a lot, but the yellow remained.

**Comment by paramat** [comment]
However, i suspect `cloudcolor_bright_dawn_f` is what is applied between 18500 and 19000 to produce the orange clouds in 0.4.8 and 0.4.15 stable (see screenshots above). Yellow clouds happen after this from 19000 to 19250.

**Comment by paramat** [comment]
Did you see https://github.com/minetest/minetest/commit/76ec6b83133f286581f051dcb1b3da5a52e30b5b ? Hope this was correct. Issue #5692 PR #5693

**Comment by paramat** [comment]
![screenshot_20170504_225928](https://cloud.githubusercontent.com/assets/3686677/25726748/89dea222-311d-11e7-9bca-1b8e0700b135.png)

^ Just before Clouds API at time 18750 (time of classic orange clouds) with directional coloured fog disabled.
Blue hue very similar to daytime blue hue.
So the clouds API did not break orange clouds from 18500 to 19000, that happened earlier.

![screenshot_20170504_230018](https://cloud.githubusercontent.com/assets/3686677/25726787/a9a4f052-311d-11e7-89a7-efefdd1da522.png)

^ Just before Clouds API at time 19125 (time of yellow clouds in bug) with directional coloured fog disabled.
Orange hue 255 224 197 similar to the intended cloudcolor_bright_dawn_f(255.0f/240.0f, 223.0f/240.0f, 191.0f/255.0f);

**Comment by paramat** [comment]
Just realised something, soon after 0.4.15 stable we changed the light curve of MT, it seems this shifted the time of orange clouds from 18500-1900 to 19000-19250 because, i assume, colour change is driven by brightness not absolute time.
You can see that everything is brighter at time 18750 by comparing https://github.com/minetest/minetest/issues/5701#issuecomment-299096452 with https://github.com/minetest/minetest/issues/5701#issuecomment-299098298

**Comment by bendeutsch** [comment]
I think I have it:

```
diff --git a/src/clouds.cpp b/src/clouds.cpp
index 627fac4..c450878 100644
--- a/src/clouds.cpp
+++ b/src/clouds.cpp
@@ -360,7 +360,7 @@ void Clouds::update(v2f camera_p, video::SColorf color_diffuse)
        m_camera_pos = camera_p;
        m_color.r = MYMIN(MYMAX(color_diffuse.r * m_params.color_bright.getRed(),
                        m_params.color_ambient.getRed()), 255) / 255.0f;
-       m_color.g = MYMIN(MYMAX(color_diffuse.r * m_params.color_bright.getGreen(),
+       m_color.g = MYMIN(MYMAX(color_diffuse.g * m_params.color_bright.getGreen(),
                        m_params.color_ambient.getGreen()), 255) / 255.0f;
        m_color.b = MYMIN(MYMAX(color_diffuse.b * m_params.color_bright.getBlue(),
                        m_params.color_ambient.getBlue()), 255) / 255.0f;
```

Typical mis-swizzled accessors :-(

This, and PR #5693, seems to restore the colors to the previous settings. I can make a pull request for this if you want, but if you want to hotfix it in, no problems.

**Comment by paramat** [comment]
Wow thanks! I'm so relieved. I'll make a PR don't worry..
