### ISSUE TITLE
Incorrect saving of maximised window

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5711]
Recently "autosave screen size" was introduced. Usually after start up I maximise my minetest window (in Win 7), so I did it and restarted minetest, it does not look right after start, window is shifted down-right and not maximised properly: 
![default](https://cloud.githubusercontent.com/assets/16494741/25775715/2cbf3212-32b4-11e7-839b-33543777d7e2.png)

**Comment by Zeno-** [comment]
Perhaps the position needs to be saved as well

**Comment by srifqi** [comment]
Should window state also saved? In case of use maximizing screen.

We can use [ShowWindow](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633548(v=vs.85).aspx) function.

**Comment by rubenwardy** [comment]
@Fixer-007  is this still reproducable?

Given that this happens on Windows 7, which we don't support, I'd suggest closing this until it's reproduced on another version

**Comment by rubenwardy** [comment]
Reproduced by user on Discord

**Comment by LoneWolfHT** [comment]
This is an issue on both Windows and Linux (not tested recently) for me

**Comment by Desour** [comment]
#12861 fixes this for the SDL backend.

**Comment by grorp** [comment]
#12861 merged.
