### ISSUE TITLE
Disabling autosave screen size does not work

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5712]
After posting https://github.com/minetest/minetest/issues/5711 I disabled "Autosave screen size", yet after restart I still has this weird shaped window explained in bug report above, it turns out "screenH" and "screenW" are still present in my config, so disabling it has no effect apart from remembering last screen size when that option was enabled.

What I expect when disabling that option is deleting screenH and screenW from my config, or in other words - reset the window size back to default.

**Comment by rubenwardy** [comment]
With it disabled, it shouldn't change (including remove) screenW and screenW, so this expected behaviour.

Unless I misunderstood you

**Comment by Fixer-007** [comment]
reread last part

**Comment by nerzhul** [comment]
there is no default size, there is only saved size
