### ISSUE TITLE
Collisions: can't walk past door

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5713]
To reproduce: start singleplayer game on engine c6e96c6.
Regression in: https://github.com/minetest/minetest/commit/b6f4a9c7e1a4f0bac66fd6f6ff844425ac775975 "Make the player collisionbox settable"

Description:
Impossible to walk through door in this configuration (something is wrong with the height of the player):
![default](https://cloud.githubusercontent.com/assets/16494741/25776030/95e77c84-32bb-11e7-9e86-9080bcbf456f.png)

or this
![default](https://cloud.githubusercontent.com/assets/16494741/25775977/83a49d28-32ba-11e7-8c69-9c0373f95c9d.png)
If I flip upper trapdoor above opened door - it lets me in.

or this
![default](https://cloud.githubusercontent.com/assets/16494741/25775998/db746146-32ba-11e7-8fdc-1eb83cf1261b.png)

or this
![default](https://cloud.githubusercontent.com/assets/16494741/25776013/2b734d42-32bb-11e7-9bf7-b3c57d9fa57f.png)

**Comment by t0ny2** [comment]
Changing line 1594 of content_cao.cpp to:
collisionbox.MaxEdge += v3f(0, BS * 0.7, 0);
seems to fix the problem for me

**Comment by paramat** [comment]
^ No, the offset of 1 is needed.

I can fix this in MTG, the engine PR removed a hardcoded player collisionbox so the player property needs adding to MTG.

**Comment by paramat** [comment]
Fix #5715

**Comment by paramat** [comment]
#5715 merged.

**Comment by Fixer-007** [comment]
Fixed in singleplayer but not in multiplayer (for example on Hometown server), needs reopen

**Comment by nerzhul** [comment]
Server side fix. Wait for servers to update

**Comment by stujones11** [comment]
Wasn't preventing this sort of problem the reason given for not fixing #2738 properly in the first place?

**Comment by paramat** [comment]
stujones11, yes, but this bug is not related to what you imply as it was caused by falling back to a default collisionbox that correctly had it's base at -1 but the box was 2 units tall.

**Comment by paramat** [comment]
Reopen.
If a new client connects to an older server it gets the old default collisionbox which is causing the problem. My commit only fixed for singleplayer or latest client with latest server.

**Comment by paramat** [comment]
Reverted feature in #5733 , please test.
