### ISSUE TITLE
Reserve `param1` for lighting

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#5717]
Currently `param1` is either used for lighting, or not used at all. I suggest to reserve it entirely, so that if any node has no lighting support, its `param1` would be guaranteed to be 0. This way, some checks might be removed, primarily checks in mesh generation.

**Comment by paramat** [comment]
Seems good.

**Comment by rubenwardy** [comment]
Sounds good. Will this result in a non-neglible performance improvement?

**Comment by numberZero** [comment]
Actually, this appears to be not enough for real improvement, as virtually every time paramtype is checked currently, light source level is checked as well, so ContentFeatures need to be accessed anyway. The only way to work around that is to cache some critical information in the node itself. I think it may be acceptable to double in-memory node size, at least on the client side.

**Comment by Wuzzy2** [comment]
Let me just drop in as a modder and say it will very unlikely to see mod breakage.
None of my mods will be affected by this, since I never used/abused `param1` for any custom stuff.
I also never saw `param1` abuse anywhere else, so I think this should be a safe change.

Therefore, I am neutral.

**Comment by numberZero** [comment]
Basically, the change consists of saying “param1 is reserved for lighting,” and maybe renaming it to `lighting` in the core (not in the API because it can be legitimately used in mods)

**Comment by TurkeyMcMac** [comment]
This is an old issue, but I have a mod that would be broken by this change: [area_containers](https://github.com/TurkeyMcMac/area_containers). I have to use param1 and param2 instead of the node metadata in order to work with Mesecons. I assumed this was OK, since the documentation explicitly says param1 can be used to store an arbitrary value with `paramtype = "none"`.

**Comment by Wuzzy2** [comment]
I no longer support this. Being able to use `param1` to store arbitrary values if `paramtype = "none"` is nice to have. It's basically a free byte!
Also, there isn't really a reason to drop `"none"` support other than "simplify some checks". That's not a good enough reason for me.

**Comment by numberZero** [comment]
Wow. It took only four years to find a mod that actually uses param1. Moreover the initial commit is from July, 2021 so it was actually four years *without* that mod. Congratulations.
