### ISSUE TITLE
Updating default_privs not updating exisitng users

### ISSUE THREAD

**Issue by mixrat** [minetest/minetest#5721]
Updating default_privs in minetest.conf has no effect on existing users. After adding 'home' to default_privs new users have the home privilege but existing users do not. The auth.txt file is not being updated by minetest.conf at server shutdown as the docs say it should: http://dev.minetest.net/Privileges

Is there a way to grant all current users a privilege similar to...
`/grant * home`

**Comment by tenplus1** [comment]
Server owners may have removed privs from certain players on purpose so changing default_privs will only affect NEW players instead of current.

**Comment by mixrat** [comment]
OK. Is there a way to grant all current users a privilege without manually editing auth.txt?

**Comment by DS-Minetest** [comment]
What about a priv called something like "default_privs" with that a player can get the default privs again?

There are mods that add workarounds for this problems, eg. mesecons_commandblock.

**Comment by mixrat** [comment]
I think `/grant * home` is the solution. An asterik is a disallowed charectar in a user name so it would make sense and make granting ALL users a breeze.

I would ask that this issue be changed from a Feature Request to a Bug. The reason being that the behavior of not updating all users upon making a change to the default privileges in the server config file is counter-intuitive for a reasonable minded person.

**Comment by nerzhul** [comment]
in future release auth & privs will be separated to have per player privs and not per account privs, and use database, then you will able to update privs very fast for all your players with a single SQL query, it's not for this release, auth.txt is already there and doesn't have multiple backends for this now

**Comment by rubenwardy** [comment]
This should be done as a mod using the authentication handler API, or using a bash script
