### ISSUE TITLE
Definable biome 'air' nodes

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5725]
2 Biome API features i would like to work on after release of 5.0.0:

A while back hmmmm / kwolekr and i agreed to add definable air nodes to registered biomes.
'air' is the only 'basic terrain node' left that cannot be defined in a biome registration and replaced during mapgen.
This feature would allow you to use the biome API to add vacuum nodes to the surface of a moon, or add an unbreathable alien atmosphere to an alien planet, or add a layer of fog to a biome, or add poisonous gas as a hazard, or add vacuum nodes to an area of empty deep space or an asteroid field.
Currently my 'moonrealm' mod uses Mgv7 and the Biome API to create a lunar surface, but i still have to use a slow Lua voxel manipulator afterwards to place all the vacuum nodes.

~The second idea is to give registered biomes X and Z limits, currently they only have Y limits so can only be limited vertically.
For example imagine a mapgen with several cubic planets floating at random positions in our 62kn^3 MT world. 3D limits would allow each cubic planet to have it's own set of biomes. Currently we can only have multiple sets of biomes if they are stacked vertically, this limits us to having flat realms stacked vertically.~
EDIT: Done.

Both these ideas are in the spirit of celeron55's roadmap for MT http://c55.me/blog/?p=1491 ...

"Keep the common base (the Minetest Engine) as universal as possible. I like to compare everything that goes into the engine for how well it suits a gravitation-less space game without ground surface. If everything is either disableable or suitable for such, then it gives much more freedom for people to experiment and create interesting things, even in ground-based worlds."

**Comment by tacotexmex** [comment]
This will be interesting. I imagine creating myself some misty marshlands.

**Comment by nerzhul** [comment]
sounds to be a nice idea, maybe there is two implementation points

* Change air nodes to specific nodes (green/red/purple transparence for example)
* Have local smoke for example imagine a ore-like smoke (volcano smoke for example)

**Comment by paramat** [comment]
I'll close this for now as there is no great need for either yet and definable "air" will be complex.
The problem being that throughout MT "air" is considered to be the node that remains when you remove something, this assumption is in many places and taking into account varying atmosphere nodes in biomes will be a big job.

3D biome limits is simple but i don't yet see a need.

**Comment by Wuzzy2** [comment]
I don't think this alone justifies closing this issue, it still sounds useful. The rationale in the first post is still valid.

**Comment by paramat** [comment]
Ok.

**Comment by paramat** [comment]
Ok i will try this. Placing non-air nodes will create some difficulties, but many of those can be dealt with in lua in a subgame, as my 'moonrealm' mod demonstrates. So instantly solving all issues in C++ is not necessary.
The important thing is to enable the fast placement of chosen atmosphere / vacuum / fog nodes by mapgen.

**Comment by CoderForTheBetter** [comment]
@paramat Are you still thinking about how to execute this idea? I'm more interested in the X and Z limits. I've been looking through the code and trying to figure out how to go about adding the limits myself so I can test the idea but I have not had much luck.

You said [above](https://github.com/minetest/minetest/issues/5725#issuecomment-316497923) that you don't see a need for this but, I was thinking of using it to make a mod that makes the biomes tougher the more north the player gets. Also, you referenced this issue 15 days ago when talking about using the limits to allow for 'space' which is another good idea.

I will continue to look at how I can implement this myself, but if you make a pull request (if the code is really that easy) then I will be more than happy to help test it.

**Comment by paramat** [comment]
I do see a need for it now, and do intend to add XZ biome limits, it will be fairly easy.
MT has to be able to 'do space' which means individual planets in that space need to have their own biome systems, y limits alone can't do that.

**Comment by tacotexmex** [comment]
![](https://i.imgur.com/Xijqp76.png)

Are you referring to generation like this? ☝️ Perhaps it's a hacky way, but the stratum ore type worked just fine for this since register_ore can be biome delimited.

**Comment by paramat** [comment]
PR #7070

**Comment by paramat** [comment]
This feature is not much needed, i suggested it because i was thinking about a planet-generating mapgen.
My intuition is telling me this will lead to nightmarish problems and complexities, as MT has for so long assumed that 'nothing' == 'air'.
So, for now anyway, i think it is best to not attempt this, closing.
