### ISSUE TITLE
Problem for climbing stairs

### ISSUE THREAD

**Issue by paly2** [minetest/minetest#5727]
Since https://github.com/minetest/minetest/commit/5e04f1a3357a618bed6d36b6a7439279b758fc8e, it is no longer possible to climb stairs without jumping.

**Comment by Fixer-007** [comment]
Possibly related to this https://github.com/minetest/minetest/issues/5713 ?

**Comment by paly2** [comment]
Perharps, but #5713 seems to be fixed now

**Comment by TeTpaAka** [comment]
The problem is, only the stepheight set from lua is multiplied by BS, but not the default version. So we have to replace here https://github.com/minetest/minetest/blob/master/src/content_sao.cpp#L814:
`	m_prop.stepheight = PLAYER_DEFAULT_STEPHEIGHT;`
by
`	m_prop.stepheight = PLAYER_DEFAULT_STEPHEIGHT * BS;`

**Comment by paly2** [comment]
I don't understand why it is necessary to multiply the stepheight by BS, could someone explain it ?

**Comment by TeTpaAka** [comment]
BS stands for BlockSize. The engine doesn't use 1 as unit, but BS, which is 10. Don't ask me, why it was introduced. it was probably a bad decision, but minetest is full of weird stuff like that.

**Comment by paramat** [comment]
@TeTpaAka see coments near end of #5724 as you can see i am bemused by where the multiplication of stepheight comes from, can you help?

Another possible cause is using latest client with an older server, the new client will not find a default value for player stepheight.

**Comment by paramat** [comment]
The engine uses Irrlicht units, and 1 node is 10 (BS = 10) Irrlicht units in size.

**Comment by paramat** [comment]
> `	m_prop.stepheight = PLAYER_DEFAULT_STEPHEIGHT;`
by
`	m_prop.stepheight = PLAYER_DEFAULT_STEPHEIGHT * BS;`

Works, now to address new client-old server.

**Comment by TeTpaAka** [comment]
In Lua, the stepheight is set with the object properties. We call this function: https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_object.cpp#L742, which uses read_object_properties to get all the fields. read_object_properties is defined here: https://github.com/minetest/minetest/blob/master/src/script/common/c_content.cpp#L132

In this function, the stepheight is multiplied by BS here: https://github.com/minetest/minetest/blob/master/src/script/common/c_content.cpp#L204

**Comment by paramat** [comment]
Thanks i see where the multiplication comes from.

I'm now thinking about how to set stepheight if a new client is used with an old server.

**Comment by paramat** [comment]
#5731 WIP

**Comment by paramat** [comment]
Reverted feature in #5733 , please test.

**Comment by paly2** [comment]
@TeTpaAka: ok, thanks for the explanation!

> please test

Works, thank you 😃
