### ISSUE TITLE
Block instadig after tool switch

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5728]
How to: place obsidian, start mining it with diamond shovel, while mining it switch to diamond pickaxe, obsidian will be instamined.

Bug was reported by vita from Hometown server and confirmed by me on engine de028fc

Regression in 7f4cdbc "Fix click-digging torches (#5652)"

Debug output thanks to @nerzhul (details: http://irc.minetest.net/minetest-dev/2017-05-08#i_4911760)

```
2017-05-08 18:57:53: ERROR[Main]: Hey i'm there here is the value 2 - trying diam pickaxe and stopped half-way
2017-05-08 18:57:54: ERROR[Main]: Hey i'm there here is the value 0 - trying diam shovel and switching to diam pickaxe during mine, instamine vvv
2017-05-08 18:57:57: ACTION[Server]: singleplayer digs default:obsidian at (10,45,-8)
2017-05-08 18:57:57: ERROR[Main]: Hey i'm there
```

Another try with cleaner output:
```
2017-05-08 18:59:55: ACTION[Server]: singleplayer places node default:obsidian at (10,45,-8)
2017-05-08 18:59:58: ERROR[Main]: Hey i'm there here is the value 0
2017-05-08 18:59:59: ACTION[Server]: singleplayer digs default:obsidian at (10,45,-8)
2017-05-08 18:59:59: ERROR[Main]: Hey i'm there
```

Demo of the bug:
![instadig](https://cloud.githubusercontent.com/assets/16494741/25807088/4d92cf8e-340e-11e7-833d-bd30ff722311.gif)

**Comment by lisacvuk** [comment]
Same thing happens to me, latest MT.

**Comment by octacian** [comment]
I can confirm this as well. Note that it works on any block, not just obsidian. (Assuming that the first tool used while attempting to mine the block is incapable of mining the block at all and the second tool is capable, though the time it would take to mine with the second tool normally doesn't matter.)

**Comment by nerzhul** [comment]
i cannot reproduced it in current master. The fix for me triggers the bug, look at the video in the PR

**Comment by nerzhul** [comment]
Here is my behaviour in master: https://youtu.be/XB6bEodZAJs (note i didn't update minetest_game since a long time, i'm on minetest 0.4.15 tag)

**Comment by paramat** [comment]
There is no PR for this currently, but #5743 was an attempt that might help to look at.

**Comment by paramat** [comment]
W might have to revert #5652 for release.

**Comment by lisacvuk** [comment]
@nerzhul, @paramat, what are your OSes? Mine's Arch Linux latest. Maybe the bug only occurs on some OSes?

**Comment by nerzhul** [comment]
Archlinux testing

**Comment by Fixer-007** [comment]
@lisacvuk Apply your PR. Give yourself wooden pickaxe in survival, click, instamine.

**Comment by lisacvuk** [comment]
@Fixer-007 https://youtu.be/OeAqRJc4WYk
I can't replicate that behaviour.

**Comment by lisacvuk** [comment]
Wait. I got it. It does that on other groups.

**Comment by lisacvuk** [comment]
ex. If I dig dirt with a pickaxe.

**Comment by nerzhul** [comment]
5785 is okay for me

**Comment by Fixer-007** [comment]
Fixed the issue for me.
