### ISSUE TITLE
Mob is glitching into solide node

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5729]
While working at my code I noticed that a mob can glitch into a solid node as you can see in this video

https://youtu.be/zHCUiI8S4rM

I only use set_velocity() to move the mob and set_yaw() to rotate it

**Comment by paramat** [comment]
What commit are you on?

**Comment by MarkuBu** [comment]
The issue is, that the collision box of the mob intersect with a node. How should a pathfinder or moving the mob wit set_velocity() do this? 

It would be possible if I use set_pos() or move_to(), but not with set_velocity()

**Comment by MarkuBu** [comment]
I have downloaded the latest dev version right now from Github. 

It seems that it has something to do with stepheight. In the video I had stepheight set to 1.1

If I set stepheight to 1.0 it doesn't happen. But the mob also doesn't jump.

However, the mob shouldn't glitch into the node. He should jump up or slide along the wall

**Comment by nerzhul** [comment]
it's not possible to fix this problem as it's a underlying problem with entities which are... too low level server side.

A high level NPC api is required permitting to properly calculate path & collisions partially client side (but this requires a breakage in API)

**Comment by MarkuBu** [comment]
> @sofar and me planed a better API in next release

What does that mean? Can I stop working with mobs?

**Comment by paramat** [comment]
Maybe your bug was due to recent breakage of collisionbox and stepheight? (just now reverted).

**Comment by MarkuBu** [comment]
That's more probable than a bug in my code
