### ISSUE TITLE
Snow trap bug

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#5741]
I accidentally found a bug with snow (and maybe similar nodes). If you are walking for example under a tree and you have nodes like leaves above your head and snow (slabs) on the ground you can walk on the snow node, but than you are trapped. 

I hope this video can explain it better

https://youtu.be/WR5f_UCk9ag

I know that snow naturally never appears under a tree, but maybe other similar nodes are also effected
I use the Minetest dev, downloaded and compiled yesterday. You can see the version in the video

**Comment by SmallJoker** [comment]
Duplicated of #1229, reopening that one.

**Comment by paramat** [comment]
Player is now 1.7 nodes high so this no longer happens with snow quarterslabs.
