### ISSUE TITLE
Minor [Esc] / Pause menu text issues

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5750]
This is a follow-up to #3845.

If you change movement keys to anything else but letters, it looks stupid in the [Esc] menu. For example:

```- UpLeftDownRight: Move```

Easy fix: Just use a single line for each key:

```
• %s: move forwards
• %s: move backwards
• %s: strafe left
• %s: strafe right
```

It doesn't look like we would run out of space. But if we need to squeeze all 4 keys into one line, at least respect English grammar by using commas:

```• %s, %s, %s, %s: move```

The [Esc] menu is very narrow. You force yourselves and translators to squeeze the text in a tiny box. Maybe give a little bit air to breathe. :-)

Grammar/typography issues:

- Use “Creative Mode” because it is a proper name (correct me if I'm wrong; at least this is the spelling used almost everywhere in the wiki)
- Use “Game paused” because it is not a title, just a status message
- If possible, use bullet points for the controls list (instead of “-”, use “•”), will be more eye-friendly

**Comment by red-001** [comment]
Using Unicode for the bullet points might not be a great idea, it might not work correctly with all fonts etc. See minetest/minetest_game#1665 for an example.

**Comment by red-001** [comment]
see #5751

**Comment by C1ffisme** [comment]
Could the "Change Password", "Sound Volume" and "Change Keys" GUIs be moved to an "Options" GUI? (Or better yet, the "Options" GUI would have buttons for all of the current options, and we can put in more options if we want to, such as FOV or visual effects that can be changed while the game is still running.)

**Comment by nerzhul** [comment]
Fixed

**Comment by nerzhul** [comment]
For the submenu, it's not time for this but maybe we can think about it after release. Freeze is in 8 days
