### ISSUE TITLE
Android lock screen problem

### ISSUE THREAD

**Issue by kenneth-Q** [minetest/minetest#5759]
Issue is :  android system auto lock. When the game loading media,node, screen become black
Add 'keep screen on' funsion.

**Comment by Wayward1** [comment]
Confirmed, but not every time. When turned back on the screen was black, but once loading was complete the screen went back to normal.

**Comment by MoNTE48** [comment]
https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/java/mobi/MultiCraft/GameActivity.java#L23

**Comment by nerzhul** [comment]
@MoNTE48 can we backport this change to MT ?

**Comment by MoNTE48** [comment]
@nerzhul just copy this line here https://github.com/minetest/minetest/blob/master/build/android/src/main/java/net.minetest.minetest/MtNativeActivity.java#L12

**Comment by paramat** [comment]
Fix wasn't applied, reopening.

**Comment by nerzhul** [comment]
Fixed
