### ISSUE TITLE
Set a PaX flag on the binary to disable W^X

### ISSUE THREAD

**Issue by Columbus240** [minetest/minetest#5761]
When trying to run minetest on a PaX configuration that prevents execution of writable pages (I don't know the specifics), then luajit will fail, which seems logical, because it needs to be able to execute some data it generates from lua code.
But this prevents the game from working. On such a PaX enabled system you can run minetest, then load a world, or open the "Mods" tab on the main menu and it crashes.
To solve this problem use `paxctl -m <minetest executable>;setfattr -n user.pax.flags -v m <minetest executable>`. And it will work again, because then PaX is told not to prevent luajit from doing its thing. The above line changes both the (at least on Gentoo deprecated) flags in the ELF binary, and the extended file attributes. Because the first command manipulates some headers, it might need a little work (maybe the -C or the -c flag), but the second one will surely work, if xattrs are enabled in the kernel (and the kernel has been told to listen to them).

**Comment by nerzhul** [comment]
it's not related to our source code, please ask to your distro maintainers.

**Comment by Columbus240** [comment]
ok, thx

**Comment by Columbus240** [comment]
Just a little question, couldn't this be done in the build scripts for Linux?
Then not each distro would have to do this by themselves.

**Comment by nerzhul** [comment]
No, it's specific to distro, not us, because they set the flag in their packages.
