### ISSUE TITLE
Subgame list on new world creation disappears if subgame name has square brackets

### ISSUE THREAD

**Issue by Admicos** [minetest/minetest#5763]
### Reproduction steps:
1. Make/install a subgame with a normal name as "hello world"
2. Check new world creation screen to see everything normal
3. Rename subgame name (inside game.conf) to something like "hello world [asd]"
4. Check new world creation screen to see the issue
5. (optional) try creating a world

### Some more info
running under Arch Linux x64
Minetest version: Minetest 0.4.15-dev-1bf9b25fb-dirty (Linux)

**Comment by paramat** [comment]
I suggest only a limited selection of characters are allowed for subgame names (a-z A-Z 0-9 _), brackets seem to be asking for trouble

**Comment by dsohler** [comment]
> I suggest only a limited selection of characters are allowed for subgame names (a-z A-Z 0-9 _), brackets seem to be asking for trouble, as do spaces.

... and another arbitrary limitation because there is no proper sanitizing.
