### ISSUE TITLE
Item and node colorization PRs in engine and game possibly essential for release

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5768]
See #5640 and https://github.com/minetest/minetest_game/pull/1707
What these 2 PRs do may be essential for release to complete the hardware colouring feature @juhdanad is this so?
The game PR was wrongly merged first, which means the engine PR needs to be merged or the game PR removed before release. However, both may be essential for release.

**Comment by juhdanad** [comment]
MTG is not broken. Just https://github.com/minetest/minetest_game/pull/1707 has no effect without #5640.

Hardware colouring works well without these modifications, but modders will have to write their own color transferring code between items and nodes. Automatic colorization is to make creating colored nodes easy for everyone, and avoid redundant code in mods.

**Comment by nerzhul** [comment]
removing blocker as @juhdanad told it's not broken

**Comment by paramat** [comment]
Ok.

**Comment by VanessaE** [comment]
I was told to leave this here:  What about crafting a pre-param2-colorized item?  i.e. to complement the colored itemstacks feature. What would the recipe look like?  This comes to mind as a possibility:
```lua
minetest.register_craft( {
	output = "mynode:foo",
	param2 = 123,
	recipe = {
		{ "node:foo", "node:bar" },
		{ "node:baz", "node:blah" },
	},
})
```
...where param2 could be set via a formula, table lookup, or whatever the modder wants to use, would simply be the param2 palette index as used elsewhere in MT.

**Comment by paramat** [comment]
^ @juhdanad

**Comment by juhdanad** [comment]
@VanessaE It is already possible to create craft recipes with metadata, however it is not well documented:
```lua
local dyed = ItemStack("wool:block") -- any block with a palette
dyed:get_meta():set_int("palette_index", 3) -- you can set the output color there
dyed:get_meta():set_string("color", "#FF0000") -- this way you can colorize any item, even without a palette
minetest.register_craft({
	output = dyed:to_string(), -- output is ItemString, which means it can contain metadata
	type = "shapeless",
	recipe = {
		"wool:block",
		"dye:red",
	},
})
```

The only thing that is not implemented is the ability to use color in the `recipe` field. So as long as the dyes are distinct items (note: you still can use the same texture for them and use static hardware colorization), you can create colorized output, and the client will see the item with color in the crafting output field.

Static colorization example:

```lua
minetest.register_craftitem("dye:red", {
	inventory_image = "dye_white.png",
	color = "red",
})
```

**Comment by VanessaE** [comment]
It's good that it can be done (and definitely needs to be documented, perhaps citing your example), but to be perfectly honest, that's over-complicated and just not very human-readable -- a beginning modder is not going to understand what they're doing here.  Since colorization is now more stable in how you do it, the Lua API should have a shortcut similar to my suggestion, but doing all of the work behind the scenes.  Then modders can choose the simple way if that's all they need.

Also consider that someone will eventually want to `/giveme` a colorized item (in which case, the second suggestion of `output = "mynode:foo 1 123"` would be apropos).

**Comment by juhdanad** [comment]
I do not think that a plain palette number in the item string is flexible enough for Minetest. With my (over-complicated) method you can set any metadata in the craft output.
Currently you should be able to use `/giveme` to add a colorized node to your inventory by: `/giveme default:wool 1 0 \u0001palette_index\u00023\u0003`. I know this is not a user-friendly format. What about JSON?

**Comment by VanessaE** [comment]
Well, think of it this way:  what benefit would there in the added flexibility?

Remember, I'm not proposing you get rid of the complicated method, only that some shortcut be added that does the hard work behind the scenes.

**Comment by VanessaE** [comment]
Well, think of it this way:  what benefit would there be in the added flexibility, in terms of an average user or modder?

I'm sure there are more than a few modders who would find the extra features useful, but if it's just some guy in singleplayer who wants to `/giveme` an item, or a modder who wants to write his or her first hardware-color-using mod, the complicated method definitely won't fly, neither would `\u0001` or JSON.

Remember, I'm not proposing you get rid of the complicated method, only that some shortcut be added that does the hard work behind the scenes.  It could even be as simple as:

`output = minetest.colorize_itemstack("foo:bar 1", 3, 0xff0000)`

(using your numbers, though that still wouldn't address `/giveme`)

**Comment by juhdanad** [comment]
See #5870.
