### ISSUE TITLE
ItemStack::addItem does not enforce stack size limit when ItemStack is empty

### ISSUE THREAD

**Issue by nybble41** [minetest/minetest#5773]
When a large (>99 items) ```ItemStack``` is added to an inventory, the expected result is that the stack is split across several inventory slots. However, the actual result is that any items which could not be added to an existing non-empty slot are placed together in a single slot. This is because of the ```if(empty())``` condition in ```ItemStack::addItem``` which simply copies ```newitem``` over the current ```ItemStack``` when the current ```ItemStack``` is empty, without checking whether all the items should fit.

There is a similar issue in ```ItemStack::itemFits```, which clears ```newitem``` if the current ItemStack is empty regardless of the number of items in ```newitem```.

This issue was observed with the ```global_exchange``` mod and the packaged version of Minetest 0.4.15 on Debian Sid. When receiving items or cancelling an order the mod adds the items to the player's inventory as follows:

    local stack = ItemStack(item)
    stack:set_count(amount)
    p_inv:add_item("main", stack)

This is consistent with the examples in the Minetest Modding Book—the section on ```ItemStack``` includes an example with a temporary stack larger than the normal stack limit (100 items). However, due to this issue, when a sell order for 198 items was created from two stacks of 99 items and then later cancelled, the result was a single 198-item stack in the inventory rather than two 99-item stacks.

**Comment by paramat** [comment]
#5774 merged.
