### ISSUE TITLE
Textarea regression (cursor not in last position)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5776]
I've noticed it very recently, bug probably occurred in https://github.com/minetest/minetest/commit/a4a377ecad6f1732cc54e7ac329fdef9949f9bf7

When you set your cursor to end of the word in text area, cursor is placed one position back.

Demo:
![1](https://cloud.githubusercontent.com/assets/16494741/26266812/b94e0f7e-3cef-11e7-8c28-adc12aaeed77.gif)

**Comment by nerzhul** [comment]
@HybridDog

**Comment by HybridDog** [comment]
l guess there's a bug in [getCharacterFromPos (irrlicht)](http://irrlicht.sourceforge.net/docu/classirr_1_1gui_1_1_i_g_u_i_font.html) which causes that https://github.com/minetest/minetest/pull/3474#issuecomment-302149987. So if you still experience this problem, you could disable searching the line end in the last line as a workaround.

**Comment by Fixer-007** [comment]
Was fixed by 1469424

**Comment by HybridDog** [comment]
l don't know, there's an alternative workaround in case it still happens:
https://github.com/HybridDog/minetest/commit/ea2be33442ba0995f4e5610e84c838e9ffa15213

**Comment by Fixer-007** [comment]
I've discovered that similar issue still exist if you edit the book contents in minetest_game.
Actually there are two bugs, one is impossible to set cursor position at the end of some lines and cursor not in last position.
Demo:
![1](https://cloud.githubusercontent.com/assets/16494741/26355175/5c559aba-3fd0-11e7-9bf9-4f8cda1947b6.gif)

What do you think?

**Comment by nerzhul** [comment]
i fixed cursor in last position recently, how can this happen... oO
