### ISSUE TITLE
Smaller selection box for flowing liquids

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5778]
In order to improve usability a bit, I suggest to reduce the height of selection boxes of flowing liquids based on the highest *actual* point by the flowing liquid 3D model/mesh/whatever in that node.

As of 0.4.15, all flowing liquids, no matter how small, have a full cube as a selectionbox:
![Selection box of flowing water in Minetest 0.4.15](https://i.imgur.com/kv5cKsm.png)

As you can see, it makes it quite annoying to point at the dirt with grass behind the flowing liquid node.

My suggested selection box for this node could look like this (in white):
![Suggested selection box in white](https://i.imgur.com/ewhQK4a.png)

**Comment by NathanSalapat** [comment]
I like it, unsure on how much code would be needed as the level is a param value if I recall, and all flowing water nodes share the same node.

**Comment by NathanSalapat** [comment]
(I guess I can't edit on mobile)
Water usually isn't pointable the only time this should be visible is if you are holding a bucket.

**Comment by paramat** [comment]
I don't think it's worth the processing needed, water level would need to be got and the selectionbox dynamically changed rapidly. Selectionboxes are larger than the actual object on very many nodes already, it's not a problem :-1:

**Comment by paramat** [comment]
Any support?

**Comment by Wuzzy2** [comment]
> Selectionboxes are larger than the actual object on very many nodes already

That's not true even in Minetest Game anymore. Even if, just because we have bad selection boxes now is no reason to improve them.
I think my screenshot shows pretty well that it would be an improvement, the difference in height is quite significant.


How high would be the CPU overhead, anyway? I find it hard to believe that it will be much, but I'm just guessing. If you `get` the node, don't you get the node name plus `param2` for free anyway?

**Comment by paramat** [comment]
> That's not true even in Minetest Game anymore.

Agreed, edited my post.
Also, i missed Nathan's support, edited another post.
It won't be intensive no, but i didn't write that, i mean i don't think it's worth coding a dynamically changing selectionbox, and running that code, just for a very minor issue.

**Comment by paramat** [comment]
Why does your liquid have a selectionbox? That only happens if wielding an item with `liquids_pointable = true` which is very rare and in which case you would want to point at the water instead of something behind.
Non issue.

**Comment by Wuzzy2** [comment]
Why close this?

Almost all liquids have selection boxes.
In MTG, all 3 liquids (water, lava, river water) have selection boxes. You can point to liquids with buckets.

Just because you don't like to implement this is no reason to close this IMO. :-(

**Comment by MarkuBu** [comment]
I want to point out one thing: you can't fill buckets with flowing liquids. Only sources can be used to fill buckets.

So there is no selection box needed at all

**Comment by Wuzzy2** [comment]
Please do not remove selection boxes for flowing liquids, that would be a terrible idea. Then it would be impossible to point to flowing liquids at all.

Buckets were just an example. Please don't be so MTG-centric. Another use case would be glass bottles which can be used on flowing liquids to fill it up with liquid.

The reason I suggested this is the same reason why in MTG the selection boxes of plants have been made pixel-perfect a while ago. It's more user-friendly that way.

**Comment by MarkuBu** [comment]
The problem is: the selection box is defined in the subgame, but the water level height is defined in the engine. 

I totally understand your reason for this issue, but I think the result does not justify the effort, if it is possible to implement at all.

And what I mean: you can't fill a bucket with flowing liquids, so there is no need to show a selection box. But this would be a different issue

**Comment by paramat** [comment]
> As you can see, it makes it quite annoying to point at the dirt with grass behind the flowing liquid node.

What i'm saying is that a selectionbox only appear when you are wielding a `liquids_pointable = true` item that specifically interacts with flowing liquid, in which case you want to select the liquid instead of the node behind.
Such items are not often wielded, and when they are it's actually a benefit to have a large selectionbox because you want to interact with the liquid node.
Also note that while visually the liquid doesn't fill the node, but the player bobs and post effect colour is applied as if the liquid fills the node, so in some ways it still fills the whole node.
I agree your suggestion looks nicer but it takes a lot of dynamic selectionbox adjusting and doesn't seem worth it.

I'll reopen.

**Comment by MarkuBu** [comment]
> when you are wielding a liquids_pointable = true item that specifically interacts with flowing liquid

But that's the point I mentioned. Buckets don't interact with flowing liquids. Only with liquid source

**Comment by paramat** [comment]
Maybe instead we can split 'liquids pointable' into 'source pointable' and 'flowing pointable'? Since items often interact with only one.
Another point is that flowing liquid can and does fill an entire node depending on its level and 'range' parameter, so a full box is in a way correct.

**Comment by MarkuBu** [comment]
> As you can see, it makes it quite annoying to point at the dirt with grass behind the flowing liquid node.

So here is the real question: why do you want to point at the grass behind a flowing liquid node if you hold an item in your hand, that only interact with liquids? You can't punch grass with a boat or a bucket.

If you would tell us more why you want to change this, it maybe would make more sense to us.

For me, the only issue currently is that you can point flowing liquids at all, even if you can't interact with them

**Comment by paramat** [comment]
As described above this has no benefit and some disadvantages, as well as needing a quite complex implementation that updates every time a liquid node changes it's level.
