### ISSUE TITLE
Fall damage evasion 2.0

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5788]
Short bug description:
Falling from Y=2000 height without encountering ignores will not cause death but only 4.5 heart damage. Encountering ignore during fall = death. Easily reproducible. Tested on engine: 358074b

How to reproduce:
+ Place a block at 0 2000 0 (via worldedit)
+ Teleport to it and /sethome, jump down
+ At first landing you will die, this is needed to preload all mapblocks
*Main part:*
+ Teleport back to block, wait >3 seconds
+ Jump, you should encounter no ignores and reach a huge speed of about 280 nodes/sec before landing, you will lose just 4.5 hearts in the process

Demo:
![kek1](https://cloud.githubusercontent.com/assets/16494741/26279213/3404efe6-3db6-11e7-8fc7-bcfd0a8d5f0b.gif)

**Comment by bigfoot547** [comment]
Overflow in damage variable?
I can imagine it is only a u8, so over 255 rolls back to 0.

**Comment by red-001** [comment]
Can confirm, version dada983f

**Comment by Fixer-007** [comment]
I have the same impression, you can find the spot somewhere near 1900, where you take just 1 heart of damage.

**Comment by Fixer-007** [comment]
Fixed
