### ISSUE TITLE
Console does not open correctly after window resize

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5789]
Console (T, F10) does not open correctly after minetest window resize (especially from small to maximised). Win7. engine ec490ab. It is still functional though and fixes itself after reopening.

To reproduce: start the game with window size at 800x600 (for example), open the chat or chat-console, input something to see amount of lines, do not close the chat, maximise the window, observe chat size.

**Comment by bigfoot547** [comment]
screeny?

**Comment by wilkgr76** [comment]
I find that this happens after resizing the window

**Comment by nerzhul** [comment]
I don't have this issue on Linux, seems related to Windows

**Comment by Fixer-007** [comment]
Seems like it is fixed by https://github.com/minetest/minetest/commit/318106223fc7351bd879980c17ee9c4bee65a272 Thanks
