### ISSUE TITLE
Zoom isn't working

### ISSUE THREAD

**Issue by echosa** [minetest/minetest#5794]
I have zoom set to `Z`, but when I press it, nothing happens. I tried setting zoom to a different key (`C`) and it still doesn't work. I looked in `debug.txt`, but I don't see any related errors.

Minetest 0.4.15-dev-39f4a2f-dirty
macOS 10.12.5

**Comment by rubenwardy** [comment]
Do you have the zoom privilege?

(use the /privs command ingame to check this)

**Comment by Wuzzy2** [comment]
Sigh. We still require a privilege for zooming? IMO this is a design flaw. See also: https://github.com/minetest/minetest/issues/4700

**Comment by echosa** [comment]
Ugh. Yep. I didn't have the privilege. I didn't even know you needed a privilege for zooming. I don't see the need for it. Flying? Sure. No clip? Definitely. Zoom? What harm can it do? Anyway, if you're going to keep zoom as a required privilege, maybe at least put a `(* requires zoom privilege)` on the keybinding screen or something to make it more obvious. Also, a GUI for setting/revoking privileges might be nice, for "average" players.

Closing this ticket as zoom is working as intended (for better or worse) and the bigger discussion is happening in Wuzzy's other ticket.
