### ISSUE TITLE
Client timeouts during and after sign-in, after "connecting" phase is over.

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#5799]
Normally when a client is going to time-out, it'll be during the "Connecting" phase.

However, these timeouts are occurring later in the process - sometimes during the "Media" phase, sometimes during the "Initializing Nodes" phase, and often, after the connecting has completed.

In the latter case, users usually get to see the world, and even perhaps start playing, before they're suddenly timed-out.  When they don't get to see the world, it's either just a starfield with moon and clouds, and no terrain, or it's a grey screen with a black wield hand.  Sometimes, the user can see other players' usernames floating in the void.

One user who has problems reports that he can connect reliably with an older client (0.4.14), but not with more recent ones - neither 0.4.15-release, nor sfan5's latest builds.  Note that this user was not having problems until a couple days ago, and he's definitely not the only one.

Another user reports, "I noticed that I had to enable the old server protocal [sic] to get on."

I am having problems as well, and have seen all of the timeout variations listed above, on an up-to-date client build.

This most often happens if there is more than one client connecting from the same IP (i.e. two family members logging in to play, on two separate usernames).

The server in question is my Dreambuilder Survival server (daconcepts.com 30001), and is at commit ec490abf5889e06c88887e17f1746043de3b10fe  but users were also having problems when it was at 9b5effffbb0599f85014b53c3fd025b6a8222e02.  However, since using an older client apparently does work reliably, I am not inclined to blame the server's build.

**Comment by nerzhul** [comment]
i don't think it's due to old or new protocol because this mode is managed after passing packets to server thread, the timeout management is in network receiver

**Comment by Wayward1** [comment]
I'm experiencing this too. Same server, latest git, Linux Mint 17.3. So far only two out of at least 7 attempts were successful, the rest ended with a gray screen and dark wield hand.

**Comment by qwrwed** [comment]
This bug seems to be preventing many people from being able to connect (same server, it can sometimes take upwards of 20-30 attempts to connect).

**Comment by paramat** [comment]
Since this is a very media-heavy server (Dreambuilder) perhaps it is due to amount of media?

**Comment by nerzhul** [comment]
i don't think paramat, media are sent over HTTP @VanessaE ?

**Comment by VanessaE** [comment]
It is indeed a media-heavy server, but as @paramat said, media is sent over HTTP.

I doubt it's a media issue, because mods and game data on the server haven't been updated in well over a month, and users who have long since received all of the media (myself included) are getting timeouts after getting all the way in (e.g. while actively playing).

It happens even when the server is responding in a timely manner, so it's not routine server/network lag.

**Comment by nerzhul** [comment]
maybe it's a minetest protocol attack stuckying network code... all servers are not affected by this, mine for example can have 15-20 players without lag

**Comment by VanessaE** [comment]
I thought about that, but my stats page suggests normal network activity:  https://daconcepts.com/vanessa/hobbies/minetest/stats-daily.html

(Ignore the high activity in the period between 11:00 and ~13:30 - that's normal and has been for years)

**Comment by nerzhul** [comment]
because of the current networking code i think ti's possible to DoS a mt server with a single passive of very slow client :(

**Comment by VanessaE** [comment]
I *am* however seeing lots of this (as in hundreds) in `dmesg`:
[14432975.250927] IPv6: udp checksum is 0 for [<someone's ipv6 address, redacted>]:43618->[2001:41d0:2:ba51::1]:30001

...and a similar set of perhaps dozens of errors,
[14751000.760665] UDP: bad checksum. From <someone's ipv4 address, redacted>:53602 to 188.165.239.81:30001 ulen 56

30001 is the port for the affected server.

**Comment by nerzhul** [comment]
Linux IPv6 protection and MT UDP usage can trigger this and can explain your problem, if a user has a bad IPv6 implementation or a router in the path, or your kernel does wrong checksum calculations (if i remember some linux kernel has this problem), packets are dropped and not received by server. This shows a timeout for MT

**Comment by VanessaE** [comment]
That might make sense, but often the timeout happens after less than one minute online.  Shouldn't that limit be much higher, like a few minutes?  (think IRC ping timeouts, that's around 4 minutes)

**Comment by VanessaE** [comment]
I should note that only one of my server instances is seeing these timeouts. EWven my Dreambuilder Creative server (30000), which is just as mod-heavy as the Survival server, seems to be unaffected.  I was able, for example, to fire up six (6) client instances to the Creative server without so much as a hiccup.

**Comment by nerzhul** [comment]
the only thing i can said is just change the server port to mitigate if a bot targets your port

**Comment by VanessaE** [comment]
Nope, no such luck.  Moved to a different port, taken out of the master list, and only I am connected.  Still getting timeouts when there's more than about three or four clients connected.   

Reminder:  I can sit here in one client instance, running or flying through parts of the map that I know for sure have not been loaded, while watching other clients on my machine time-out, with barely any effect on the client where I'm running/flying.  Literally the only delays I see are just normal map loading delays of a second or two here or there.

**Comment by JosephTheTank13** [comment]
Yes please fix this bug asap. I do think it is due to the media. I made a LAN server with 50+ mods and I had the same exact problem as described. You log in, the server works for about 30 seconds then times out.

**Comment by nerzhul** [comment]
@VanessaE is trying to bisect to find a reasonable commit range where we can find something interesting

**Comment by VanessaE** [comment]
#5818 definitely appears to have fixed this.

**Comment by SmallJoker** [comment]
#5818 was merged.
