### ISSUE TITLE
player:get_sky() suddenly returns arguments in incorrect order

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5803]
This is a regression of the Lua API in 0.4.15 and breaks all scripts which relied on the output of `player:get_sky()`.

According to `lua_api.txt`, this is `get_sky()` in 0.4.15:

> returns bgcolor, type and a table with the textures

In 0.4.15, documentation matches fact.

In ec490abf5889e06c88887e17f1746043de3b10fe, `lua_api.txt` says:

> returns bgcolor, type, table of textures, clouds

So, the same, but with new `clouds` argument. So far so good.

However, in dev, the actual order is different. In dev I get `type` (like `"plain"`) before I get `bgcolor` (a typical `ColorSpec` table). This means, the actual returned order is:

`bgcolor, type, table of textures, clouds`

Please fix this before release, it already broke a script of mine.

**Comment by sfan5** [comment]
The order of the arguments has not been touched since c0335f7d13ee46c6a46d0ceebea96960439ec9fd (when `get_sky` was added)
Documentation bug?

**Comment by Wuzzy2** [comment]
Well, a documentation bug wouldn't explain why the order suddenly differs between 0.4.15 and ec490ab, although the order in documentation clearly didn't.

I made some tests. How `get_sky` acts in 0.4.15:

![](https://i.imgur.com/PS40rgE.png)

And here's how it looks like in ec490ab:
![](https://i.imgur.com/7OCqEM0.png)

Transscription: After calling `me:set_sky("#FFFFFFFF", "plain"), followed by `me:get_sky`, the returned values are:

0.4.15:
`{r=255,b=255,a=255,g=255}, "plain", nil, nil`

ec490ab:
`"plain", {}, true, nil`

Something seems to be seriously wrong about the output in ec490ab (besides order). 0.4.15 looks OK to me. The 3rd argument is probably `nil` because the `plain` type does not need textures (actually, it should be an empty table, but that's not the issue here.

The output of ec490ab really doesn't make sense. `"plain"` somehow moved to the first place, the 2nd argument is an empty table for some reason, the the third argument is `true`?! This is completely wrong.


---

As you see, the order actually differs quite obviously. Maybe the order has been changed by accident (sneaky bug?). When you are about to fix this, I suggest to try to keep the order of 0.4.15 intact since the order matches documentation, otherwise, you will break all scripts depending on `get_sky`.

**Comment by sfan5** [comment]
Took another look and found the bug:
ad9fcf859ec2347325830e09504ae96968b51ea8 makes set_sky return a fourth value but keeps the result as `return 3;` which confuses Lua and breaks the ordering
@paramat plz fix

**Comment by nerzhul** [comment]
Fixed

**Comment by paramat** [comment]
Thanks, so return 4 was needed.
