### ISSUE TITLE
Impossible to set cursor position at the end of some lines in multiline text area

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5805]
If you edit the book contents in minetest_game (engine 0530922) and try to set your cursor to end of the word in some lines - it will be refused and instead set to beginning of new line.

Demos:
![1](https://cloud.githubusercontent.com/assets/16494741/26355175/5c559aba-3fd0-11e7-9bf9-4f8cda1947b6.gif)

**Comment by nerzhul** [comment]
1469424075affce7c27bb44e5a5cbd51485e44b2 should be reverted before release if nobody find a solution for this problem as it's not better
