### ISSUE TITLE
Remove interpolation on player (and entities)

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#5816]
![screenshot_20170525_083324](https://cloud.githubusercontent.com/assets/15371866/26457430/ead1135a-4124-11e7-8eb4-f7d96189f875.png)

The interpolation used on the player and other entity textures just plain looks bad. It removes the sharp and pixelated feel that a game such as Minetest should have. If this interpolation were removed, the player itself would appear much more natural in the Minetest setting and would also likely fix other issues with the player skin texture bleeding on the eges.

Thoughts?

**Comment by Fixer-007** [comment]
Hmmmm, are you using texture filtering? Because I have proper look with mipmaps + aniso + no filter
![default](https://cloud.githubusercontent.com/assets/16494741/26461338/8acfe3ee-4185-11e7-8c2d-e2eaffd636f2.png)

**Comment by Calinou** [comment]
This is likely a bug, if you have bilinear or trilinear filtering turned off, no texture should be filtered. Inversely, if you have either of these enabled, all textures should be filtered – it's intended for use with HD textures.

**Comment by octacian** [comment]
Whoops, your right @Calinou, I did have trilinear filtering enabled resulting in the initial "issue." Closing this. I apologize, I need to research a little more thoroughly as to what some settings do before I open issues like this :D

**Comment by Fixer-007** [comment]
I have follow up question myself, there is:
~~~
#    When using bilinear/trilinear/anisotropic filters, low-resolution textures
#    can be blurred, so automatically upscale them with nearest-neighbor
#    interpolation to preserve crisp pixels.  This sets the minimum texture size
#    for the upscaled textures; higher values look sharper, but require more
#    memory.  Powers of 2 are recommended.  Setting this higher than 1 may not
#    have a visible effect unless bilinear/trilinear/anisotropic filtering is
#    enabled.
#    type: int
# texture_min_size = 64
~~~

Soo... I enable trilinear filtering and nothing is crispy at all, I've even specified "texture_min_size = 64" in config.

It does not work?
