### ISSUE TITLE
Small ping (latency) shown as large , Large latency shown as small

### ISSUE THREAD

**Issue by edakiri** [minetest/minetest#5826]
In the Play Online , the indicator labelled 'Ping' shows a large amount when there is little latency (ping time) and a small amount when there is a large ping time.  They are inconsistent with one another.

I advise changing either the label or the amount indicator, so that the 2 correspond.

Suggestions for more suitable labels:  **Speed** or **Throughput** or **Connection Quality** .

**Comment by rubenwardy** [comment]
It's supposed to be like mobile phone connection - more bars of signal is better

**Comment by nerzhul** [comment]
Thanks for your report but @rubenwardy explained what is the purpose of this indicator. Closing

**Comment by edakiri** [comment]
You did not address the issue of the label. You only addressed the bar.
