### ISSUE TITLE
Debug Menu is missing options

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/minetest#5830]
Built this morning from source, the menu options are named differently than the option examples listed.

![huh](https://cloud.githubusercontent.com/assets/8930456/26523587/91f782c4-42e0-11e7-95c0-7a9b61c6d6d0.png)

**Comment by NathanSalapat** [comment]
I'm not expert, but it would seem that changing line 1471 of builtin/settingtypes.txt to read:
debug_log_level (Debug log level) enum action ,error,warning,action,info,verbose
would provide with a way to log errors only. I did some simple testing, by creating a line in a mod that read:
minetest.log('error', 'this is 100% not an error.')
when logging errors that message was printed out. If errors aren't meant to be an option we should consider removing that from the listing.

While at it maybe the none option should be added to the dropdown as well.

**Comment by paramat** [comment]
Thread title could be more descriptive, to be clear this is a bug instead of a request.

**Comment by SmallJoker** [comment]
#5836 is merged.
