### ISSUE TITLE
Use automatic line breaks in advanced settings help

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5831]
Currently, translating/writing/maintaining the long descriptions (when you click the “Edit” button) of the advanced settings dialog is very painful.
You have to add manual line breaks all the time which is of course error-prone.

It also happens from time to time that not even the English original strings obey the “add manual line break after so-and-so characters” rule. (separate issue comes soone)

Please fix this by breaking the lines automatically instead.

**Comment by sfan5** [comment]
I would even consider the lack of automatic line breaks a bug instead of just a missing "feature".

**Comment by SmallJoker** [comment]
Fixed by #7802
