### ISSUE TITLE
Path selector in advanced settings menu does not select paths

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5833]
How to reproduce this bug:

* Select in the advanced settings any setting which takes a path (e.g. `shader_path`)
* Click on “Edit”, then “Browse”
* Browse through the directories
* Select any directory
* Click “Save”

Expected: The path gets written into the text field
Actual: The text field is emptied

Fun fact: If you do the same thing, but select a file instead, it works. But it's useless if the setting requires an actual path (not a file).

Tested in: 210a339dce754a6cb03d4ef82f5bacc80b63262b

**Comment by red-001** [comment]
working on this

**Comment by red-001** [comment]
see #5852
