### ISSUE TITLE
Text in volume change menu writes over each other

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5837]
This is how the volume change menu currently looks like:

![Screenshot showing the failing sound menu](https://i.imgur.com/XBChwZh.png)

Seen in 210a339dce754a6cb03d4ef82f5bacc80b63262b, same in 0.4.15 and many, many releases before that one.

**Comment by Fixer-007** [comment]
What is your screen resolution, window size? do you use scaling? I don't have this problem on d99b6fe

**Comment by Wuzzy2** [comment]
* Screen resolution: 1920×1080
* Window size: 1920×1080, 800×600, any other window size  … basically it looks the same for any window same, the sound volume dialog does not scale
* OS: GNU/Linux
* Scaling: No
* Custom font: No
* `minetest.conf`: Deleted before start

In advanced config, Minetest claims the `font_path` is blabla/Arimo-Regular.ttf. But when I click on “default value”, it changes to fonts/liberationsans.ttf. WTF?

Anyways … custom fonts, scaling or whatever are no excuse for this bug. :P
It looks like the window uses 2 separate labels at fixed positions which are also very close to each other. If this is indeed the case this would invite all sorts of problems with scaling or verbose languages. Probably should just make it one label?

**Comment by nerzhul** [comment]
I'm working on it now

**Comment by nerzhul** [comment]
Fixed
