### ISSUE TITLE
Pressing the “print stacks” key floods chat with fake errors

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5838]
If you press the “print stacks” key (“P” by default) in the game, your chat gets flooded with red “ERROR” messages. If you read them, it turns out, those are not errors at all, it is just the information you requested.

I think those messages, if they appear in the chat at all, they should appear just as normal messages and as something other than “error” or “warning”. “Error” really doesn't make sense here. It's not an error, it's intended information.

Tested in: 
* 0.4.15
* 210a339dce754a6cb03d4ef82f5bacc80b63262b

**Comment by SmallJoker** [comment]
Removed in #6378
