### ISSUE TITLE
Ubuntu integrated problem, and others

### ISSUE THREAD

**Issue by londumas** [minetest/minetest#584]
Hello,
It is a very good game.
I have installed the latest version of Minetest fom this ppa: http://ppa.launchpad.net/minetestdevs/stable/ubuntu
and the integration to Ubuntu (Quantal for me) has some problems : 
    - Not translated (in French for me) but the translation exists in Launchpad and on Github
    - No launcher icon
    - Impossible to find it when tapping "jeu" or "game" in the Dash (problem of the category of the application in the .desktop?)
    - In the Dash when doing a right click on Minetest, no icon, a super picture, the description is not translated (to do in the package/DEBIAN/control)

The rest of the problems I have seen are not linked to Ubuntu but I prefer to put them all here.

- Why not add a "restore default" button in "Settings"
- Impossible to copy/paste the name or code of a server.
- impossible to scroll in the windows: for the server or the games

I thank you again for your work, I will be happy to give some screenshots if some of my bugs are not understandable.

Thank you for your app again

Minetest 0.4.5
Ubuntu Quantal 64bits

**Comment by nerzhul** [comment]
This issue is outdated and the improvements have been integrated or discussed at 0.4.12 release
