### ISSUE TITLE
Feature request: add get_objects_inside_ray(pos1, pos2) to lua api.

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#5846]
Like get_objects_inside_radius() this should return all objects that are on the ray between the two positions.

Use case: shooter mods like bows, guns and cannons. Or daylight sensors that checks if a object is flying above (simulating shadow).

**Comment by juhdanad** [comment]
#4421 can do that (however, it also returns nodes on the line).

**Comment by adrido** [comment]
#4421 would be perfect, thanks for your great work. I hope it will merged into Minetest soon.

**Comment by juhdanad** [comment]
#4421 is merged, this should be closed.
