### ISSUE TITLE
Untranslatable advanced settings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5849]
Hi! Either two setting names + description in the advanced settings are not translatable at all, or Weblate has not been updated accordingly.

The settings (+description) with missing translations, although Weblate shows 100%:

* Autosave Screen Size (`autosave_screen_size`)
* Maximum size of the out chat queue (`max_out_chat_queue_size`)

Please do not forget to update Weblate before release. Note I will probably soon report string errors (typos, etc.).

Tested in 1681a009bc54b19eeab0356c7ed856bc0bed6a1a.

**Comment by Wuzzy2** [comment]
Oops!
I just noticed the strings are actually in Weblate but for some reason, they still don't translate in Minetest when I use the 100% translated PO file. o_O

**Comment by Ekdohibs** [comment]
It was probably caused by the broken `updatepo.sh`, which has been fixed and run now. Closing as no longer relevant since the settings are in the PO file.
