### ISSUE TITLE
Translation string quality assurance

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5850]
Here is my review of all translatable strings currently found in 0.4.15-dev (1681a009bc54b19eeab0356c7ed856bc0bed6a1a), like I did for the previous Minetest release. This is just extracted from string comments in Weblate (https://hosted.weblate.org/projects/minetest/minetest/).

Please rewrite the following strings (typos):

* ~~“No worldname given or no game selected” → “No world name given or no subgame selected”~~
* ~“Install Mod: unable to find suitable foldername for modpack $1” → “Install Mod: unable to find suitable folder name for modpack $1”~
* ~“Android systems only: Tries to create inventory textures from meshes when no supported render was found.” → “Android systems only: Tries to create inventory textures from meshes
when no supported renderer was found.”~

Incorrect key names:

* ~“Next” → “Page Down” or “PgDn”~
* ~“Prior” → “Page Up” or “PgUp”~

Other:

~“First of 2 3D noises that together define tunnels.” → “First of two 3D noises that together define tunnels.”
“Mapblock mesh generator's MapBlock cache size MB”. First you forgot “in” before “MB”. And second, sure it's MB (megabyte), not MiB (mebibyte)?
“block send optimize distance”. Poorly worded setting name of `block_send_optimize_distance`~

~The punctuation is wrong in that one:~

~At this distance the server will aggressively optimize which blocks are sent to clients.
Small values potentially improve performance a lot, at the expense of visible rendering glitches.
(some blocks will not be rendered under water and in caves, as well as sometimes on land)
Setting this to a value greater than `max_block_send_distance` disables this optimization.
Stated in mapblocks (16 nodes)~

~I think it should be (correct me if I'm wrong):~

~At this distance, the server will aggressively optimize which blocks are sent to clients.
Small values potentially improve performance a lot, at the expense of visible rendering glitches.
(Some blocks will not be rendered under water and in caves, as well as sometimes on land.)
Setting this to a value greater than `max_block_send_distance` disables this optimization.
Stated in mapblocks (16 nodes)~

The following strings are ambigious or challenging for translators and need a translator comment (Gettext comment):

* ~“`needs_fallback_font`”: AFAIK this is a special string which you don't translate, instead you just write “yes” or “no” depending on whether this language needs the fallback font.~
* “Enter ”: See <https://github.com/minetest/minetest/blob/master/src/guiFormSpecMenu.cpp#L3067>. It seems NOT to be the enter/return key, so this is very misleading. Also, this string seems to suffer from string concatenation
* ~“Cavern taper”~
~“Terrain alt noise”~ (EDIT by paramat: Changed to 'Terrain alternative noise').
~All strings with “cliff-top” in them. WTF is “cliff-top”?~ (EDIT by paramat: Changed descriptions to clarify).
* ~All key names should mention “Keyboard key name” as context/comment, especially:~
    * ~Menu~
    * ~Select~

String concatenation (no use of format strings):
* ~“Could not find or load game "” (subgame name is appended, hardcoded quotation mark is appended to that)~
* ~“Sound Volume: ” (volume percentage and hardcoded percent sign are appended)~
* “Enter ” (see above)

**Comment by paramat** [comment]
I can edit the mapgen stuff.

**Comment by 12Me21** [comment]
cliff-top just means the top of a cliff.

**Comment by Wuzzy2** [comment]
There's a typo:
“Persistance”. Should be “Persistence”.

---

These strings are now fixed and can be striked thru:

* “Android systems only: Tries to create inventory textures from meshes when no supported render was found.”
* “Next”
* “Prior”

**Comment by paramat** [comment]
Ugh, 'persistance' is probably my fault, anyway too late for 5.0.0 now. Where is that typo?

**Comment by Wuzzy2** [comment]
builtin/mainmenu/dlg_settings_advanced.lua

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/ae1caba6aaa6f0a13e70f195f371fd4e7a378491/builtin/mainmenu/dlg_settings_advanced.lua#L620
Here too:
https://github.com/minetest/minetest/blob/9311d8a8aab7dbb8f938654f545f1929ce518996/builtin/settingtypes.txt#L45
Actually both not my fault.

**Comment by Wuzzy2** [comment]
Closing in favor of #11442.
