### ISSUE TITLE
Colored nametags are misaligned

### ISSUE THREAD

**Issue by kaadmy** [minetest/minetest#5851]
Basically the title.
If a player (and possibly entity) nametag is colored with any of the `minetest.colorize`-like functions, the nametag becomes offset too far to the left.
If I "balance" the nametags to have one color escape before and after the nametag's visible text, it's still misaligned.

**Comment by bigfoot547** [comment]
<a href=https://github.com/bigfoot547/rank/blob/master/init.lua#L60 target="_blank">Here is my hackish way around it.</a>
I "don't have this problem" with my rank mod.
