### ISSUE TITLE
Problem with daylight turning dark outside caves

### ISSUE THREAD

**Issue by Xanthin** [minetest/minetest#5853]
This is something that irritates me for a while now. IIRC it first appeared around #4646.

This effect is common to me now (worse on servers) and especially confusing when counting blocks or diving underwater.
![peek 2017-05-30 23-28](https://cloud.githubusercontent.com/assets/6878547/26606376/fe400ff6-4591-11e7-988e-081248221d7e.gif)

This effect is not very common but as well irritating.
![peek 2017-05-30 23-32](https://cloud.githubusercontent.com/assets/6878547/26606348/de3f14ea-4591-11e7-8337-e7a83e22defc.gif)

I couldn't see differences when noclip, fly and the like are on or off .

**Comment by Wuzzy2** [comment]
I can confirm this. I think this is common. You just have to be quick in changing the view.

This bug can be very easily spotted in wireframe mode.

**Comment by Wayward1** [comment]
Duplicate of #3577

**Comment by Xanthin** [comment]
Yes, true (https://github.com/minetest/minetest/issues/3577#issuecomment-264653735). Sorry.
