### ISSUE TITLE
Missing Lua API documentation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5854]
The lua_api.txt file has a ton of issues. I created this issue to keep track of them, and to encourage them to be fixed.

Note: By “undefined”, I mean, no actual definition is written down. **Examples alone do not count!** Examples can only supplement, but not replace a formal definition.

### Aliases

- [x] Scope of `minetest.register_alias` is not mentioned. What is aliased? Entitites? Items? Nodes? Players?

## Formspecs

- [x] Syntax/semantics of the `fields` table you get from `on_receive_fields` is largely undocumented. There are many gotchas like the undocumented `quit` field
- [ ] It is poorly documented which events trigger an `on_receive_fields` and which fields are sent then. One gotcha is that checkboxes are sent only when they themselves are clicked, but not when you clicked a button in the same formula

## HUD

- [x] alignment is a vector, not a number
- [ ] aligning to the left is actually aligning to the right with images

## Classes

- [ ] MetaDataRef is not explained.
    - If this is considered an abstract class, say that.
- [ ] `vector` functions are mostly undefined

## Other

- [x] `get_hit_params`
- [x] `get_dig_params`
- [x] `table.indexof` in `misc_helpers.lua`

**Comment by Wuzzy2** [comment]
FYI: I am probably not much of a help here. Most of the things missing in the documentation I do not know myself (that's why I made this issue, after all!). Sure, I will soon add some help for the more obvious things, but I will not touch the things I do not understand.

By the way: Is it really too much to ask that the programmer adding feature X is also the one adding the documentation for feature X? Makes much more sense to me than asking 3rd parties to a) first to find the code in question b) figure out what it does c) read the original developer's mind to document the developer's intentions and d) write it all down, probably with a million of factual mistakes. If the original author would write it down, a), b) and c) can be skipped.

Or is this already done, just not strictly?

**Comment by paramat** [comment]
#5879 merged.

**Comment by Thomas--S** [comment]
Nodedef: `collision_box` is also not mentioned in `lua_api.txt`

**Comment by paramat** [comment]
Also #5383

**Comment by rubenwardy** [comment]
Added some things

@Wuzzy2 if you're happy with the fix, then please remove check boxes marked as complete

**Comment by Wuzzy2** [comment]
I have clicked on all the links above, but all these issues are still open. I don't see why I should tick any of the checkboxes now. o_O

Whatever. I don't mind if you edit or even completely obliterate first post. It's a bugtracker, not a discussion forum.

**Comment by paramat** [comment]
Useful issue, with many collected here a dev could do many of these in 1 quick PR.

**Comment by HybridDog** [comment]
get_hit_params and get_dig_params aren't in lua_api.txt.

**Comment by DS-Minetest** [comment]
https://github.com/minetest/minetest/issues/6106#issuecomment-328087547

**Comment by paramat** [comment]
That's in the first post DS-Minetest.

**Comment by DS-Minetest** [comment]
I don't mean the topic but the comment:
>Actually [many registered things](https://github.com/minetest/minetest/blob/151c95bb9bb324ef27df28bbd4f2bce944e35162/builtin/game/register.lua#L555L584) aren't documented.

All those registered things could be added to first post to be added to `lua_api.txt`.

**Comment by paramat** [comment]
#6619 merged.

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest/issues/6677#issuecomment-346928953
lua_api doesn't mention that you can load a mapblock using vmanip

**Comment by rubenwardy** [comment]
indexof in misc_helpers.lua is undocumented

**Comment by paramat** [comment]
#6906 #6916 merged, some more ticked.

**Comment by benrob0329** [comment]
Entity documentation seems lacking.

**Comment by paramat** [comment]
Object 'visual = "wielditem"' needs explaining as an object that appears as a node.

**Comment by Ferk** [comment]
There's also #2838

It's not clear what "using" means in minetest.
The docs and in-game help call "place/use" to the action of the ``on_rightclick``, yet this conflicts with the ``on_use`` for the left-click. Better call the right-click action "place/interact".

"interact" is a good name since it's implicit that you are interacting with an external object (even if you code ``on_rightclick`` to do something else not related to the pointed thing, it still requires you to point to an external node/entity, unlike ``on_use`` that does not require the player to be pointing at anything).
I don't think this distinction in behavior between left click and right click is documented anywhere.

**Comment by paramat** [comment]
Ok now understand Object 'visual = "wielditem"' will document it sometime.

**Comment by HybridDog** [comment]
> "interact" is a good name […]

It's called interact there: https://github.com/minetest/minetest/blob/master/src/game.cpp#L3018

**Comment by paramat** [comment]
'visual = "wielditem"' now documented in merged #7017

**Comment by paramat** [comment]
#3423 better documentation for acceptable noise param ranges is needed (my job).

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3813
`player:get_inventory():get_width"main"` returns 0, not the inventory width (in my experience)

**Comment by HybridDog** [comment]
The return values of the on_place function are itemstack, success.
However, placing succeeded if the second return value (success) is not false (it can be nil):
https://github.com/HybridDog/replacer/issues/4#issuecomment-365402693

https://github.com/minetest/minetest/blob/540e07e3ef07de760100c2948dc3a756e48b1c72/doc/lua_api.txt#L4656
https://github.com/minetest/minetest/blob/540e07e3ef07de760100c2948dc3a756e48b1c72/doc/lua_api.txt#L3173

**Comment by HybridDog** [comment]
Swapping items in the inventory can be used to skip the allow put and/or take function.
https://github.com/minetest/minetest/blob/6cfd699b9f898be6142f5f2bbd459666aa0f0bb8/doc/lua_api.txt#L4929-L4942
This isn't documented and adds owner/protection problems, e.g. https://github.com/minetest-mods/more_chests/commit/57e32a597c3ca939305000f44f8db3204f6e523d#diff-ab8e43317940e99c95302fff936a1b6fR48

**Comment by HybridDog** [comment]
minetest.get_content_id does not work on node aliases

**Comment by paramat** [comment]
#7125 merged, ticked first box.

**Comment by Thomas--S** [comment]
**Formspecs: Tabheader**

https://github.com/minetest/minetest/blob/478b785bc8d8f82b69b23f22ea8a69007db10d9e/doc/lua_api.txt#L2185-L2186

The documentation of these two parameters could be improved.
* Default value?
* What is shown *transparent*?
* What *border* is drawn?

**Comment by paramat** [comment]
#7154 merged, better noise docs.

**Comment by paramat** [comment]
Plantlike meshoptions docs could be clearer.

The values given are a confusing mix of decimal and hex, even i didn't know you could combine them and do '4 + 0x10' in lua. Mixing number types in the param2 value is messy anyway, the value used for param2 should be stated as a decimal.
The documentation of bits should remain of course. I suggest the values to use are all expressed in decimal, as values to add up.

**Comment by paramat** [comment]
Entity 'visual = "cube"' takes 6 tiles like a node but all 6 must be listed.
/////////////

Document that order of registration of decorations and ores defines order of generation, very important to get order correct.

**Comment by paramat** [comment]
Another one for me:
Remove these incorrect and unnecessary lines from mapgen specific mapgen flags:
"Flags that are not enabled are not modified from the default.
Flags starting with 'no' are used to explicitly disable them."
The first line is actually incorrect.

**Comment by Wuzzy2** [comment]
>  aligning to the left is actually aligning to the right with images

This actually sounds like a bug to me. Because, WTF?

> alignment is a vector, not a number

Actually, this is not true. It's a table with x and y, which is not what we usually mean with “vector”. Also, the Lua API seems to mention that correctly already, so this can be ticked off.

>  It is poorly documented which events trigger an on_receive_fields and which fields are sent then. One gotcha is that checkboxes are sent only when they themselves are clicked, but not when you clicked a button in the same formula

Note that #8236 will NOT fix this entirely. It will fix only the “which events trigger an on_receive_fields” part, but not the “which fields are sent then”. This is a subtle but important difference. For this to be ticked off, it needs to be also documented which fields are sent *on a per-event basis*. This is because every event type (button press, Enter key, scrollbar scroll) seems to send a more or less different set of fields. It's pretty insane. ;-)

Finally, I like to add #3872 to the list, it's super important.

**Comment by Wuzzy2** [comment]
@HybridDog: 

> The return values of the on_place function are itemstack, success. However, placing succeeded if the second return value (success) is not false (it can be nil):

> minetest.get_content_id does not work on node aliases

> Swapping items in the inventory can be used to skip the allow take function.

All of these sound like bugs to me. Consider posting new issues for all of these.

**Comment by paramat** [comment]
More boxes ticked by https://github.com/minetest/minetest/commit/187519407be5ca51db007d638857917ba53f1b6d

**Comment by benrob0329** [comment]
### `on_rightclick` NodeDef Documentation Leaves Variables Unexplained
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6533

What is `node`, what is `clicker`? I can assume `clicker` is the player/entity doing the rightclick'ing but is node a NodeDef, a node table? Is it the node that's being rightclicked or the node that the user is holding?

**Comment by ClobberXD** [comment]
The fact that MT allows per-texture normal maps isn't documented anywhere in the API docs.

**Comment by DS-Minetest** [comment]
Not missing documentation, but wrong documentation:
https://github.com/minetest/minetest/blob/5c97eeabace3256d4f50c9d9c7776fb360c2077c/doc/lua_api.txt#L5512-L5513
That should be y, not z. (And it might be better explained with the right hand rule.)

I hope it's ok, if I add some small documentation things to this issue when I find them. :slightly_smiling_face:

**Comment by benrob0329** [comment]
`after_place_node`'s `oldmeta` argument has no description

**Comment by Wuzzy2** [comment]
Update:
* `on_receive_fields` done
* `vector` done
* MetaDataRef done

The only remaining thing from 1st post is: “HUD: aligning to the left is actually aligning to the right with images”.

**Comment by Wuzzy2** [comment]
> HUD: aligning to the left is actually aligning to the right with images

Actually, this claim is not correct. This means all checkboxes in the 1st post are now complete!

**Comment by Wuzzy2** [comment]
I think this issue shold be closed as everything in the 1st post is done. The rest are stuff posted by other people, but it's very unstructured. Maybe a new issue should be opened for those, it's getting quite chaotic in here.
