### ISSUE TITLE
lua_api.txt syntax and other errors

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5855]
Here are 9 syntax or other mistakes in `lua_api.txt`. I reviewed this file for the upcoming 0.4.16 release. I used <https://rubenwardy.com/minetest_modding_book/lua_api.html> for the review, from 23th April 2017. This made it easier to me to spot formatting errors.

Use your text editor's search function to spot the text in question.

Tick off the numbers when finished.

---

* [ ] (1)

Missing backtick at end of function name:

```
Aliases can be added by using minetest.register_alias(name, convert_to) or `minetest.register_alias_force(name, convert_to).
```

---

* [ ] (2)

At the end of the “Nodes” section explaining the possible `paramtype2` types, `collision_box` is mentioned for no apparent reason.
Search for “Nodes can also contain extra data. See "Node Metadata".”.

---

* [ ] (3)

Broken syntax; this is how it appears in formatted view:

> Noise parameters format example for 2D or 3D perlin noise or perlin noise maps: np_terrain = { offset = 0, scale = 1, spread = {x=500, y=500, z=500}, seed = 571347, octaves = 5, persist = 0.63, lacunarity = 2.0, flags = "defaults, absvalue" } ^ A single noise parameter table can be used to get 2D or 3D noise, when getting 2D noise spread.z is ignored.

After “Noise parameters format example for 2D or 3D perlin noise or perlin noise maps:”, there must be two newlines, not one.

---

* [ ] (4)

Bad asterisk:

> About probability values: A probability value of 0 or 1 means that node will never appear (0% chance). A probability value of 254 or 255 means the node will always appear (100% chance). * If the probability value p is greater than 1, then there is a (p / 256 * 100) percent chance that node will appear when the schematic is placed on the map.

---
* [ ] (5)

The entire sections “Examples of custom groups” and “Escape sequences” have broken paragraphs. Most of “minetest namespace reference” has broken newlines/paragraphs.

---
* [ ] (6)

Incorrect usage of bullet points in “Authentification” section?

---
* [ ] (7)

> e.g. 'default:pick_wood 21323'

Bad example. You can't have 21323 pickaxes in one stack. ;-) Replace it with `default:pick_wood 1 21323` if you meant the wear.

---

* [ ] (8)

In section “Ore Attributes”:

> Currently supported flags: `absheight`

Outdated. `puff_cliffs` and `puff_additive_composition` are missing.

---

* [ ] (9)

Excess backtick:

```
`minetest.delete_particlespawner(id, player)``
```

---

HINT: Use <https://daringfireball.net/projects/markdown/dingus> to test the Markdown syntax.

This issue can be considered fixed after all checkboxes have been ticked off AND when you do not spot any further formatting errors in Dingus.

**Comment by lisacvuk** [comment]
Hey, if lua_api.txt is in markdown, why isn't it named lua_api.md, so that github converts it into a more readable form?

**Comment by paramat** [comment]
lisacvuk there's a PR for doing that, it's also rather controversial. I find github MD formatting less readable.

**Comment by paramat** [comment]
#5879 merged.
