### ISSUE TITLE
Clouds API: Incorrect/misleading coordinates for speed parameter

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5857]
I think the `speed` parameter in the clouds API is a bit odd.

It is a table of the form `{x=number, y=number}`.

But shouldn't it be `{x=number, z=number}` to match the actual in-world coordinates?

Tested in 1681a009bc54b19eeab0356c7ed856bc0bed6a1a.

**Comment by SmallJoker** [comment]
Depends on the point of view. The clouds itself are just one layer that can only move along two axis. Also 2D perlin maps use `x, y`, as they're two dimensional aswell.

**Comment by Wuzzy2** [comment]
It's not really important, I just thought it makes sense to match the 2D coordinates with the 3D coordinates. It's more about consistency than anything else.

Using y like in the 3D world would mean the clouds move up or downwards. ;-)

**Comment by paramat** [comment]
:+1: X, Z would be better, but currently the code may expect X,Y  as internally noise stuff uses X,Y for 2D stuff.

**Comment by paramat** [comment]
I included this in #6163

**Comment by Wuzzy2** [comment]
Grrrrr … :angry: 
You ignored the issue when I posted this before 0.4.16 got released. Now you suddenly take it seriously, but this will be a breaking change. Had this be fixed before release, there would not be a break required.

And yes, the cloud API already has been used … by me. And yes, the speed parameter.

**Comment by paramat** [comment]
I replied on June 1st which was before release, that's not ignoring, and i agreed with you.
We don't have to break compatibility, i only asked for clarification in documentation.

**Comment by Ferk** [comment]
The change is not just in the documentation, though. I think it would break compatibility.
 https://github.com/minetest/minetest/pull/6164/files#diff-9444313da8be4290e9304a4b1faed804L1769

**Comment by paramat** [comment]
Yeah but since it is a new API we can change it without much breakage of mods.

**Comment by Wuzzy2** [comment]
OK if you just want to change docs.

**Comment by paramat** [comment]
#6164 merged.

**Comment by bendeutsch** [comment]
Wow, I really feel bad for not noticing this issue for so long :-( Sorry!

We could rewrite the code so that it can accept both `y` and `z` as the second parameter, that way mods can support 0.4.16 at release and whatever the next version is.

Additionally, if a mod sets the speed parameter with both `y` and `z` fields (to the same value), it should also work with both API versions, even if it's a bit tedious for mod authors to do so.

**Comment by paramat** [comment]
Nah no need, we're making a breaking release next and the API itself is young.
