### ISSUE TITLE
Subgame texturepacks

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#5860]
# Subgame texturepacks

## Problem
Currently, subgame makers have to manually search out textures in each mod and replace them, breaking upstream compatibility by doing so (no more git pulls). 

Also, a lot of subgames are, as we know, based on Minetest Game. Some of the subgames don't even modify that code, but may want to replace the textures it contains. This also breaks upstream compatibility with the current method. 

There are some really rich, beautiful and maintained texturepacks out there, but applying a whole texturepack that is maintained by yet another person/group is a pain to keep up with if having to resort to the the abovementioned method. 

## Solution
Subgames should be able to define their own texturepacks by providing a `/textures` directory in the subgame directory. Textures in this directory should overwrite any other textures provided by the subgame's mods.

Together with #6412, this would allow subgame makers to stay upstream on third-party texturepacks _and_ apply customizations on top of that.

A texturepack chosen in the main menu texturepack tab should still have top priority, of course.

Let's make subgames more diverse looking by simplifying the theming method!

**Comment by NathanSalapat** [comment]
No idea on how hard this would be to code, bit does sound like a good idea.

**Comment by paramat** [comment]
Seems a good idea.

**Comment by Wuzzy2** [comment]
I am not sure about this. Does this mean that all textures are contained twice in the same subgame?
First texture in the mod (which is just ignored) and the second texture is in the “subgame texture folder”?
This sounds like a waste of space, as the subgame includes textures it will never use.

**Comment by red-001** [comment]
Storage space is hardly an issue these days especially considering the size of minetest textures. If it is an issue for you just don't use the feature. A whole 32x32 texturepack with 500 textures is only around 12 mb.

**Comment by Wuzzy2** [comment]
My point is that this simple act will (more or less) **double** the total size of textures (if we assume equal size of the texture pack). Which means it scales poorly. The larger your subgame, the larger the “penalty” for using the “subgame texture directory”. I don't think this should be done lightly.
Apart from file size, it just creates pointless repository clutter. I am not happy with having files in a repository which aren't used for anything. And by duplicating the textures, you will have *tons* of useless files.

> If it is an issue for you just don't use the feature.

No, this is not an option. This is nothing which the user can simply opt out from.

I agree with the stated problem, but I think the presented solution may not be the best one. If anone here could maybe think of a solution to solve the problem *without* duplicating all the textures, I'm all in.

**Comment by red-001** [comment]
well then come up with a solution that doesn't involve a pre-processing script.

**Comment by Wuzzy2** [comment]
To be honest, I do not have *that* strong feeling about this. I just wanted to raise a possible concern. I justs thought it is not the best software design to just duplicate files.

I'm not really opposed. I am kinda OK with the idea, but it would be even better if there would be a way without duplicating textures.

And no, this feature is cleary NOT optional *for users*, I see no way how an user can opt out of this. But that's just a sidenode, not a complaint.

**Comment by red-001** [comment]
if you want to avoid duplicating textures without a lot of extra work on the part of the subgame dev you will need some sort of script for copying textures before release and thats just plain ugly. Adding this will make that easier for people that really do care about that disk space since they will be able to use something sane for development and run a script on it to copy and de-duplicate the textures on release. It is optional for users/devs as they can copy the files themselves or write a script to do it.

**Comment by paramat** [comment]
We already duplicate textures when using a texture pack that overrides the textures in mods, this just allows a subgame to do the same if they want to.

**Comment by tacotexmex** [comment]
With https://github.com/minetest/minetest/pull/6412 now merged, perhaps this feature is one step closer to being realized?

**Comment by tacotexmex** [comment]
Come to think of it, this problem can be solved if the textures are placed in the `textures` folder of a mod with a dependency written to load last of all subgame mods. But it's quite hackish.

**Comment by paramat** [comment]
#6032 merged.
