### ISSUE TITLE
Documentation issues with player:get_attribute and player:set_attribute

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5864]
`lua_api.txt` claims that you can use `get_attribute` and `set_attribute` on player objects to set attributes.

There are some things not mentioned:

* `set_attribute` does not work with *arbitrary* values (tables, userdata or functions don't work). It is undocumented which types are accepted
* `set_attribute` seems to return something after being called, but this is not documented either
* `set_attribute` apparently silently turns numbers into strings (which can be a major gotcha). Let `player` be a player object, then entering this into console (with `luacmd` mod installed):

```
/lua player:set_attribute("test", 5)
/lua x = player:get_attribute("test")
/lua print(x)
/lua print(type(x))
```

Prints out:

> 5
> string

The third problem could also be just Lua's type coercion.

Tested in: 1681a00

**Comment by paramat** [comment]
You seem the ideal person for fixing all these lua_api.txt issues before release.

**Comment by Wuzzy2** [comment]
Okay, just tell me what value type are officially allowed for `set_attribute`/`get_attribute` and I try to fix this ASAP.

**Comment by rubenwardy** [comment]
Only strings, or things that can be implicitly converted to a string such as numbers - although they will return as a string.

It's exactly the same as get_string in the metadataref

**Comment by Wuzzy2** [comment]
New PR: https://github.com/minetest/minetest/issues/5884
