### ISSUE TITLE
minetest.player_exists returns true after player was removed with minetest.remove_player

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5865]
In the Lua API, if you call `minetest.player_exists` after calling `minetest.remove_player` on the same player, `minetest.player_exists` always returns `true`.

How to reproduce:

* Start server with `luacmd` mod enabled
* Let player “abc” join
* Let player “abc” leave
* Let player “admin” join
* As the player “admin”, use these commands:

```
/lua print(dump(minetest.player_exists("abc"))
/lua print(dump(minetest.remove_player("abc"))
/lua print(dump(minetest.player_exists("abc"))
```

* Make sure the player “abc” did **not** join while entering above commands

Expected output:

> true
> 0
> false

Actual output:

> true
> 0
> true

Observations:
* If you restart the server again after entering the final command, then you try to do `/lua print(dump(minetest.player_exists("abc"))` once again, you *still* get `true` returned.
* If you let player “abc” join again, the player spawns as if a new player; all items and stuff are gone (expected behaviour)

It seems, as soon as the player “abc” joined at any point in the server's history, `minetest.player_exists` will start to return `true` for that player no matter what.

Tested in: 1681a009bc54b19eeab0356c7ed856bc0bed6a1a

**Comment by nerzhul** [comment]
remove_player doesn't remove auth, it just removed player data, not account data in fact, it's subtile a difference

**Comment by rubenwardy** [comment]
I think that it should also remove author, or player_exists should check for a player entry

**Comment by Wuzzy2** [comment]
I think this is a gotcha. Care to fix `lua_api.txt` (as I have a poor understanding of the inner workings)?

**Comment by rubenwardy** [comment]
A documentation change would be best this late in the release cycle

**Comment by ShadowNinja** [comment]
e4d3639d403f1d7cc4223bcca3816d8f19198cb6
