### ISSUE TITLE
Non-node inventory images are ca. 16% darker compared to the original (regression)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5866]
As of 1681a009bc54b19eeab0356c7ed856bc0bed6a1a, the inventory images of items which are not nodes are visibly darker (ca. 16%) compared to the original image and Minetest version 0.4.15:

MineClone 2 in 0.4.15:
![MCL2, 0.4.15](https://i.imgur.com/1mEoNB4.png)

MineClone 2 in 0.4.15-dev:
![MCL2, 0.4.15-dev](https://i.imgur.com/1g6Pbkh.png)

Minetest Game in 0.4.15:
![MTG, 0.4.15](https://i.imgur.com/iCBtiDd.png)

Minetest Game in 0.4.15-dev:
![MTG, 0.4.15-dev](https://i.imgur.com/4mejAy2.png)

The *perceived* effect seems to be stronger in MineClone 2 than in Minetet Game, probably because of the brighter background.

Observations:
* 0.4.15 perfectly represents the colors of the original image file
* 0.4.15-dev doesn't
* A white pixel (RGB = (255, 255, 255)) in the original image turns into RGB=(213, 213, 213) in 0.4.15-dev, a decrease of ca. 16%. This also means it is impossible to have any item image with a pixel brighter than 213 in any component
* Node icon don't seem to have darkened at all, but the light/bright side of the cube image seems to have been swapped. This was probably intended and I don't see this as a bug, as the overall icon brightness seems to be unchanged

**Comment by SmallJoker** [comment]
Can confirm. Basing on my quick tests I did, the bad commit is between 0891116 (Jan 25) and d176364 (Apr 16).

**Comment by nerzhul** [comment]
@SmallJoker very large range

**Comment by Fixer-007** [comment]
I have lots of compiled builds in my archive, will find much shorter range.

**Comment by paramat** [comment]
@juhdanad

**Comment by srifqi** [comment]
@Fixer-007 Can confirm, that's the commit.

**Comment by juhdanad** [comment]
@Fixer-007, thanks for finding the wrong commit. Apparently items with custom inventory images were not shaded, only nodes.
