### ISSUE TITLE
Document ItemStack set_metadata, get_metadata functions as deprecated

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5872]
What happened to the item functions `get_metadata` and `set_metadata`?
I don't see any documentation for those anymore, but the functions still seem to be silently supported.

What are the compability advices regarding items?

How do we treat items with metadata from 0.4.15 and earlier? Is there a smooth way to transition the 0.4.15 items to 0.4.16? How do the old functions relate to the new `get_meta` for itemstacks? Are those compatible?

IMO all this should be documented before release, it could be confusing otherwise. I am currently confused by this. (Told you so! xD)

**Comment by rubenwardy** [comment]
They're deprecated, so were removed from the API docs. It may be worth adding a line like

> get_metadata() - DEPRECATED - use get_meta() instead

**Comment by Wuzzy2** [comment]
One does not simply remove a function from docs without deprecating it first! :P 

(In 0.4.15, both functions had no “deprecated” status.)

I will do this today or tomorrow, when I fix some of the recent `lua_api.txt` issues.

**Comment by SmallJoker** [comment]
ItemStack `get_metadata` and `set_metadata` are documented since February this year: #5198
Why was this issue opened *after* they already were documented?
