### ISSUE TITLE
Client cloud_height setting now superficial?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5873]
Hi!
With the addition of the clouds API, do the client settings `cloud_height` and `cloud_radius` still make any sense? I stlll see those in the advanced settings.

I think the idea of the clouds API is to set clouds style per-player server side. Which is a *good* thing IMO because this allows for greater artistic control in subgames.

However, *still* making the cloud height and radius client-settable seems to be contradictory to this. I suggest to remove these settings and hardcode the default values into the engine. Because having client-defined defaults means subgames can not really rely on the defaults *at all*.

I was never really happy with the client-defined cloud setting anyway because they tend to mess up subgames unless when left at defaults, thus making them fairly useless.

IMO the client should now only be able to enable clouds entirely and toggle 3D clouds. The rest is server stuff. What do you think?

Summary:
- Remove `cloud_height` and `cloud_radius` from client settings
- Hardcode default cloud height and cloud radius into engine

EDIT: Forget about `cloud_radius`, we are now only talking about `cloud_height`.

**Comment by paramat** [comment]
The author of the Clouds API stated that the old cloud_height setting is still relevant, but confirmation would be good.
cloud_radius is certainnly still needed as is not included in the Clouds API (maybe it should?)

**Comment by Wuzzy2** [comment]
Oh sorry, I retract my suggestion of removing `cloud_radius`. It was based on a misunderstanding. You're right.

Now I only stick to `cloud_height` then.

**Comment by paramat** [comment]
From #4524 
"Even if cloud height is settable, as paramat said, I'd still duplicate this setting to the cloud API, for consistency."
But that doesn't make sense to me.

**Comment by paramat** [comment]
@bendeutsch

**Comment by bendeutsch** [comment]
Hi, sorry, my GitHub notifications are not set up that well.

So: the `cloud_height` setting is still the client-side default for the cloud height, while the server uses the "default default". Actual communication only takes place if something is set, at which point, the server "wins", and `cloud_height` is irrelevant.

The only case where this setting is useful is if we have a player who cares about the clouds playing on a server that doesn't (including single player, without cloud-changing mods or subgames). But this case can be handled easily if someone™ writes a "choose your own clouds" mod which simply gives access to the clouds API via command line. Then the above player can install this mod or ask the server admin to install it server-side. Players who don't care about clouds can ignore it.

But yes, it can be thrown out as a setting.

**Comment by bendeutsch** [comment]
Aaaand [here's the mod](https://forum.minetest.net/viewtopic.php?f=9&t=18232). Now all that's left is to remove the setting…

**Comment by bendeutsch** [comment]
There. How's that?

**Comment by paramat** [comment]
#6202 merged.
