### ISSUE TITLE
Chat command “/shutdown inf” is a thing

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5874]
You can actually write `/shutdown inf` into chat and it gets accepted, which means the server never shuts down. Well, that sounds pointless.

But this is not even the fun part.
The funny part is that in the help of this chat command, someone apparently actually explicitly wrote the “inf” case as vaild attribute. Err, what the …?!

I don't know if there is any rationale for this or if I'm missing a special meaning here, but it feels completely wrong.

Do you agree?

**Comment by red-001** [comment]
It's a valid attribute because the lua function used to convert the string to the number supports it. I don't see a point in adding extra code to detect this.

**Comment by nerzhul** [comment]
@red-001 maybe we can forbid this case because it doesn't make sense to trigger a shutdown with infinite delay ?
