### ISSUE TITLE
Item icons of items using minetest.inventorycube are displayed with delay and flicker on first load

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5875]
I have done 2 tests in “latest dev” (a7787bb9d27851b3e8ff9ff388e50793ee5120ed), using default settings only.

* Test scenario 1: Play unchanged Minetest Game on latest dev
* Test scenario 2: Play Minetest Game on latest dev, but add `inventory_image=minetest.inventorycube("wool_"..name..".png"),` to the node definition in `mods/wool/init.lua` before starting

In both tests, I just launch Minetest Game with Creative Mode on, then I click through the creative inventory until I find wool. I have restarted Minetest entirely between tests, just in case. Test results:

* Test scenario 1: Wool images are shown instantly
* Test scenario 2: On the first time you see the wool icons, they are shown with a brief delay and it even briefly flickers which looks very ugly

**Analysis**:
Apparently every item using `minetest.inventorycube` loads less efficient than other items and causes flickering when displayed the first time.

The impact of this issue varies greatly and largely depends on how many items you have with `minetest.inventorycube`. If you have pages after pages of such items, this will be very noticable, as you have flickering after each pageflip (at least on first load). In subgames not using this function at all, this has no effect, of course.

**Comment by paramat** [comment]
We don't use inventorycube anymore though, inventory items are directly rendered now. Maybe this is an inevitable delay caused by generating the inventory cube image?

**Comment by Wuzzy2** [comment]
The bug appears in 0.4.16.

Do you by “we” mean “Minetest Game developers”? Minetest Game isn't the only subgame.

Are you saying that `minetest.inventorycube` is a deprecated function? I would have no problem in deprecating it. Note that many subgames and mods still depend on it.

In my subgame I also try to avoid it everywhere, this function seems indeed pointless now and direct rendering is much better anyway.

**Comment by sfan5** [comment]
This is just a side-effect of using RTT (render-to-texture) to render these.
I'm afraid this can't be fixed, rather the fix is already in: directly rendering these by not using `minetest.inventorycube` at all.
