### ISSUE TITLE
Favorite server does not get “unstarred” when deleting favorite with active search

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5878]
How to reproduce:

* Use a7787bb9d27851b3e8ff9ff388e50793ee5120ed
* Go to tab “Play Online”
* Enter something into search, so that from your favorite servers (those with a star), one or more is still visible
* Select one of your favorite servers
* Click “Delete favorite”

Expected: Server gets unfavorited and unstarred
Actual: Server keeps its star icon. But when you empty the search bar, the server is gone from the favourites.

Compare this behavour to the behaviour when you have an empty search.

**Comment by nerzhul** [comment]
confirmed
