### ISSUE TITLE
'Host Server' check box  in 'Local Game'  tab don't have proper translation

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#5883]
'Host Server' check box  in 'Local Game'  tab don't have proper translation

**Comment by Wuzzy2** [comment]
Then just fix the translation?!

Translations are managed here:
https://hosted.weblate.org/translate/minetest/minetest/

If you manage to fix this before June 4th 0:00 UTC, it will definitely be part of next release.

**Comment by red-001** [comment]
https://hosted.weblate.org/projects/minetest/minetest/ not https://hosted.weblate.org/translate/minetest/minetest/

**Comment by nerzhul** [comment]
Closing, weblate is here for that
