### ISSUE TITLE
Window: Missing menu bar on launch if not full size

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#5887]
If Minetest is launched in a method so that the window is not full-sized vertically, the top menu bar (i.e. bar with close, shrink, etc..) is not visible on Ubuntu and several other distributions. If the window is resized to cover the full vertical height of the desktop, the bar is once again shown. The issue state can be seen in the screenshot below.

![mt bug](https://cloud.githubusercontent.com/assets/15371866/26750466/2762b242-47d8-11e7-876f-6ea0c087dc03.png)

I can confirm that the issue is present on Ubuntu 17.04 and Ubuntu MATE 16.10.

**Comment by nerzhul** [comment]
Seems mir and Ubuntu is crap these days

**Comment by Fixer-007** [comment]
Try Alt+drag the window down to move it.

**Comment by rubenwardy** [comment]
What DEs does this occur on?

**Comment by paramat** [comment]
I'm still on Ubuntu 16.04 LTS. The MT window very often opens with the lowest centimeter below screen edge, it didn't do this on a previous LTS. I'm assuming it's an Ubuntu issue not a MT one.
