### ISSUE TITLE
Window: Can "click through" when opened full-sized with dual monitors

### ISSUE THREAD

**Issue by octacian** [minetest/minetest#5888]
This issue only occurs to users with more than 1 monitor. I can confirm that it occurs on Ubuntu 17.04, but am unaware if this issue exists on other distributions.

If the Minetest window size is saved as full screen (windowed) and a Minetest instance is opened on a monitor other than the primary monitor, although Minetest is displayed on the correct monitor, it is possible to "click through" the Minetest window and access the window behind it. On the primary monitor, clicks from the Minetest window on the other monitor are responded to. This means that whenever Minetest is launched on a non-primary monitor, the window must be temporarily resized in order to make sure that clicks are responded to in the right area.

**Comment by nerzhul** [comment]
no problem for me on gnome 3.24 on Arch, related to mirshit ?

**Comment by NathanSalapat** [comment]
Couldn't reproduce on Linux Mint 18.1 with Cinnamon DE.

**Comment by azekillDIABLO** [comment]
happened to me on windows a long time ago, but i don't think it is related.

**Comment by rubenwardy** [comment]
I can't reproduce this either. I don't think it's a problem with MT

**Comment by octacian** [comment]
Yes, it seems as though it probably wasn't an issue with MT itself. On Ubuntu 17.10 with GNOME, the issue does not present itself. So, I would assume that it was either related to something in Ubuntu which was fixed with the 17.10 release (most likely) or something small in MT that was somehow fixed without knowing.
