### ISSUE TITLE
Setting movement_speed_descend appears to be completely ignored.

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5890]
No matter to which value you set `movement_speed_descend`, the downwards climbing speed at ladders is alway the same. It seems this setting has no meaning whatsoever. It also seems to have no effect on liquids either
The downwards climbing speed seems to be always the same as the upwards climbing speed defined in `movement_speed_climb` (just downwards, of course).

Could it be that `movement_speed_descend` is broken? Then again, there is no documentation on that setting yet.

Tested in 9875193d8f7082979702512a247d9472a3345c8c.

How to reproduce:
* Just frequently `movement_speed_descend` in advanced config and see if anything change in climb speed or (downwards) diving speed

**Comment by red-001** [comment]
Seems so the setting isn't even used anywhere in the code, it's just in the settings file. So it's not as much broken as not implemented.

**Comment by red-001** [comment]
Fixed by #5892
