### ISSUE TITLE
update colors.txt

### ISSUE THREAD

**Issue by anton-tsyganenko** [minetest/minetest#5896]
After running minetestmapper.py on a new map (created in 0.4.15, mgv7) I've got a lot of unknown nodes:

> Unknown node names: default:snowblock default:ice default:pine_needles default:aspen_leaves flowers:tulip default:pine_tree default:grass_1 flowers:mushroom_red flowers:viola default:aspen_tree default:bush_leaves default:bush_stem default:grass_2 default:grass_3 default:grass_4 default:grass_5 flowers:mushroom_brown default:snow default:dirt_with_snow default:silver_sand flowers:rose default:stone_with_iron stairs:stair_cobble flowers:geranium flowers:dandelion_white flowers:dandelion_yellow default:stone_with_copper flowers:waterlily default:coral_brown default:coral_orange default:coral_skeleton default:dirt_with_dry_grass default:dry_grass_3 default:dry_grass_2 default:dry_grass_4 default:dry_grass_1 default:dry_grass_5 default:acacia_bush_leaves default:acacia_bush_stem default:acacia_leaves default:acacia_tree default:jungleleaves default:torch_wall fire:basic_flame carts:rail carts:powerrail default:aspen_sapling default:meselamp nyancat:nyancat_rainbow

It's better to update colors.txt.

**Comment by sfan5** [comment]
`minetestmapper.py` and the colors file that comes with it are both outdated
use https://github.com/minetest/minetestmapper instead

**Comment by anton-tsyganenko** [comment]
If it's outdated, why don't you remove it from the repository?

**Comment by nerzhul** [comment]
@anton-tsyganenko nice shot :) see #5901
