### ISSUE TITLE
Main menu font is glitched

### ISSUE THREAD

**Issue by Profeet** [minetest/minetest#5904]
This happens exactly after pressing any button there or changing the menu category.
I tried with multiple versions but this "thing" is persistent.
![lawl](https://cloud.githubusercontent.com/assets/29172638/26763700/b1e846ec-495f-11e7-8a64-be824e2d2283.JPG)
![ljh](https://cloud.githubusercontent.com/assets/29172638/26763702/b4552aee-495f-11e7-90e5-75707dc682c8.JPG)

**Comment by paramat** [comment]
What version of MT is that? it has the old header image so is not 0.415 or 0.4.16.

**Comment by Profeet** [comment]
it's 0.4.10 but it's the same in all versions, this is the only verstion i have in my pc

**Comment by Profeet** [comment]
UPDATE:  I solved it by changing the graphincs engine from opengl to direct3d8
![lok](https://cloud.githubusercontent.com/assets/29172638/26774950/5894512c-49db-11e7-9d2c-6b387d349bfb.JPG)
![mine](https://cloud.githubusercontent.com/assets/29172638/26774956/5ac6f6b6-49db-11e7-9bc3-395e2d55d959.JPG)
![capture](https://cloud.githubusercontent.com/assets/29172638/26774960/5e86bde0-49db-11e7-83f6-a5af62169ace.JPG)

**Comment by nerzhul** [comment]
solved and please upgrade your OS/Hardware :(
