### ISSUE TITLE
progress bar looks odd

### ISSUE THREAD

**Issue by Napiophelios** [minetest/minetest#5911]
The progress bar seems the wrong size 256p X 48p
when resized to 256p X 32p it looks correct.

[![progress_bar.png](https://s4.postimg.org/dwzer038d/progress_bar.png)](https://postimg.org/image/pyusl5cgp/)

Is this just a Windows PC thing?

**Comment by srifqi** [comment]
Can't confirm. Just tested 32-bit Minetest 0.4.15-dev on 64-bit Windows 10. Works fine.

Which Windows do you use?

**Comment by Napiophelios** [comment]
I am using minetest-0.4.16-win32-msvc
on a really old desktop Windows XPSP3
I figured it was the OS, but wasn't sure

**Comment by NathanSalapat** [comment]
Can't confirm. 0.4.16 on Linux Mint 64 bit.

**Comment by nerzhul** [comment]
the problem is on OpenGL 1.X

**Comment by kilbith** [comment]
> old desktop Windows XPSP3

The issue indeed comes from OpenGL 1.x (which is 20 years old) and the support for Windows XP is going to be phased out.

Let's trash your prehistoric hardware and upgrade it.

**Comment by Napiophelios** [comment]
:-)  haha already working on upgrading, it's just a slow process for me.
thanks for the answers.

**Comment by paramat** [comment]
Can't reproduce.

> when resized to 256p X 32p it looks correct.

Squashed rectangular pixels though.
