### ISSUE TITLE
ERROR[Emerge-3]: EmergeThread::finishGen: Couldn't grab block we just generated

### ISSUE THREAD

**Issue by Golutazem** [minetest/minetest#5916]
Sometimes the following error is shown when generating map blocks.

ERROR[Emerge-3]: EmergeThread::finishGen: Couldn't grab block we just generated: (coordinates here)

It appears that missing map blocks are replaced with stone.

Reproducing it is non-deterministic. It does not happen consistently for the same mapblocks, when generating with the same parameters.

I have only seen this when using multithreaded geneneration with 1 < threads <= CPU cores. Usually I used threads=CPU cores.

It seems to happen more often at a smaller chunk size.

The following map generation causes it.
Mapgen 7, Seed 52 , ChunkSize=2, Threads=8
Seed 47 also lost many.
Issuing an emergeblocks command around the origin, such as
/emergeblocks (-256,-64,-256) (256,256,256)

Minetest and Minetest Game 0.4.16 Built with 
GCC 6.3.1
glibc 2.25-1

**Comment by paramat** [comment]
I've only seen this when running a very slow mod like the mandelbox/mandelbulb generator mod which can take 30-60s to generate a mapchunk.

**Comment by nerzhul** [comment]
yeah it's because a block is generated by a thread and grabbed by another concurrently

**Comment by paramat** [comment]
This seems to be one of many weirdnesses caused by emerge threads > 1.

**Comment by SmallJoker** [comment]
Emerge thread was cleaned up and improved recently. Please ask to reopen this issue if it still happens in 5.3.0.

**Comment by erlehmann** [comment]
i think i know how the emerge error works: the server has an unload timeout where it deletes map blocks from memory. but it seems to start counting from the beginning of the generation of the block, so if the map block takes longer to generate than the unload timeout, the server can not grab the block! you can verify that by setting the server mapblock unload timeout to 1 and getting this error all the time.
