### ISSUE TITLE
Show more infos in debug screen

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5920]
I'd like to see more infos in the debug screen:

* About the pointed node:
    * [ ] `param1` **(rejected by paramat)**
    * [X] `param2`
    * [ ] Has metadata y/n
    * [ ] Texture of pointed face instead of top texture **(rejected by paramat)**
    * [ ] “Real” name (`descripton`), if present (maybe shorten it, if too long) **(rejected by paramat)**
* About the pointed entity:
    * [ ] Entity type ID (e.g. `__builtin:falling_node`, `boats:boat`, …)
* [ ] Mapgen name
* [ ] Heat and humidity point of current position (if applicable)
* [ ] Current biome (if applicable)

Especially `param2` is very important for mod development.
If the text becomes too long, we might consider adding a 3rd line.

Feel free to suggest other information. :-)

**Comment by DS-Minetest** [comment]
I agree about the entity name but the rest of doesn't always have to be seen, there are mods that add tools for it.

**Comment by paramat** [comment]
Param1 and 2 will be useful.

**Comment by Fixer-007** [comment]
I would also creep in with this bug https://github.com/minetest/minetest/issues/5042:

>It would be nice to have the name of the pointed entity where the pointed node names are normally (in debug mode text).

**Comment by bigfoot547** [comment]
Maybe current biome could be helpful.

**Comment by Wuzzy2** [comment]
While we're at it, the debug display could be cleaned up a bit as well:

* Combine `range_all` with `v_range` into a single field
* Add units (°, s, ms, etc.)
* Remove `drawtime` and maybe `dtime_jitter`, too. IIRC celeron55 said those fields are not really important. I'm not sure about that

---
@celeron55

**Comment by Wuzzy2** [comment]
This issue has been closed too early; 1 thing of my list has actually been added: `param2`. Everything else is missing.

Note that although #6031 has been merged, *someone* has removed `param1` after that for … reasons. WTF?

**Comment by JRottm** [comment]
In case you're wondering, param1 was removed with PR #6125.

**Comment by Wuzzy2** [comment]
> Remove 'param1' (0 for all solid nodes and unreadable for light sources due to
light bank encoding).

OK, this answers the question.

**Comment by paramat** [comment]
Yes i did not realise how useless param1 would be.
Texture of the pointed tile was the original intention but the author could not make that work, it would be much more intensive too so i don't consider it worth doing. But also, tile texture name is not useful information and required fetching 'content features' for each pointed node, so it was removed.

**Comment by Wuzzy2** [comment]
Oh, other information which would be very useful:
- Heat and humidity point of current position
- Current biome

This would help a lot in debugging the biomes and to get a “feel” for the heat and humidity, and getting the biomes right is hard. I think for v6 these fields are not needed.

> But also, tile texture name is not useful information

I disagree. Even if it is only the 1st texture, it was still useful to me, it saved me time because I don't have to look into the source code again.

>  and required fetching 'content features' for each pointed node, so it was removed.

Why is “fetching content features” such a big deal? I have never witnessed any drop in FPS whatsoever in debug mode (except wireframes), even on my fairly old computer.

But yeah, the texture info is not as important as other things, but it didn't hurt either. I would agree to remove it only if it is done to save space.

**Comment by paramat** [comment]
Heat and humidity are possibly a good idea, these would be 'felt' by a player. Biome might be good too.

By 'not useful information' i mean of little usefulness, obviously occasionally someone will find it 'useful' because they are too lazy to open the code.
So i'm not talking absolutes, debug information has limited space, so we have to justify including something, taking everyhting into account, and prioritise.
Getting 'content features' is not a big deal, i mention that together with something not being of much use. if a feature is of very little use and requires fetching the nodedefs of each node pointed at (not intensive but also not insignificant), then i am judging it to be not justified.

**Comment by paramat** [comment]
Not realy suitable for hacktoberfest as is controversial and there is a PR already for F5 info.

**Comment by SmallJoker** [comment]
Closing this issue, as being replaced by the more up-to-date #6666.
We now have a 3rd line, which was mentioned in the opening comment, which is not wanted either by some people.

**Comment by paramat** [comment]
Difficult issue as everyone will have a different idea of what to include in debug. So perhaps best to not discuss too much and ask that mods are used to display what people want. For now we are keeping debug info roughly the same as it has been for years.
