### ISSUE TITLE
Map_meta.txt no longer alphabetically ordered

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5927]
Looks messy now with parameters ordered in a random way.
I'm on 599e13e95e81aadb959c9f3715aec9b425ede084
This does not happen in 0.4.16 stable.
Not a big problem but may be a sign of a bug or mistake somewhere.
Makes the map_meta.txt file messy and unpleasant to work with.
Guess: C++11 stuff.

**Comment by raymoo** [comment]
Probably UNORDERED_MAP -> unordered_map related

**Comment by nerzhul** [comment]
it's due to unordered_map, it's not important as it's a meta for server itself.

**Comment by paramat** [comment]
Ok since it is not a sign of an underlying bug.
