### ISSUE TITLE
Wielditem shadow glitch

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#5938]
Bug already existed in 0.4.15-dev from May 17

Sometimes when I move on the map a random bug seems to happen that turns my wielded item black for a sec every few secs and prevents me from moving.

As soon as the wielded item turned back to its normal texture again I can continue to move.

See .gif here http://ihrfussels-server.tk/mt.gif

Server version and client version were both compiled on Jun 4

**Comment by paramat** [comment]
Do you have a very low power machine? And what mods are you running on this server, any intensive ones like moretrees, plantlife?
This only happens to me when flying fast wth noclip and entering unloaded blocks which are full of ignore and are dark, when the block loads the wielditem becomes light again.
If you are hitting an unloaded block you cannot move and the wielditem goes dark.

**Comment by IhrFussel** [comment]
@paramat That can't be since it still happens even after you stop moving for a minute.

Steps to reproduce:

1. Set viewing range VERY LOW (20 or 30)
2. Fly fast into UNGENERATED map terrain (it will blink once when you reach the current generated area)
3. STOP moving and your tool will continue to blink dark with a pretty high chance

Here is the video that shows how it still happens even when I stand still.
http://ihrfussels-server.tk/mt.mp4

**Comment by paramat** [comment]
Ok my guess is probably wrong. I'll try to reproduce it.
Can you reproduce this in singleplayer with no added mods?

**Comment by paramat** [comment]
> notice how I am in MID AIR and there is nothing to load around me

Air nodes are still 'stuff' to generate and load.

**Comment by paramat** [comment]
Can't reproduce this.
I can get the expected darkness once for a second by flying fast with noclip enabled into an ungenerated block full of dark 'ignore' nodes, but the darkness stops as soon as the block loads/generates and doesn't happen again.

**Comment by paramat** [comment]
IRC discussion http://irc.minetest.net/minetest-hub/2017-06-08#i_4965436
See linked .conf, we suspect settings that are too extreme, such as 'clieny mapblock limit = 15'.

**Comment by IhrFussel** [comment]
I increased client mapblock limit to 100 but it still seems to happen, although less likely it seems...will test more

**Comment by paramat** [comment]
100 is still very low, 1000 is reasonable and will not use more than 100MB of RAM. You also have other settings set to extreme values, try using normal settings but with client mapblock limit = 1000.

**Comment by paramat** [comment]
Please test with more normal settings, will close in 1 month.

**Comment by kingoscargames** [comment]
>Sometimes when I move on the map a random bug seems to happen that turns my wielded item black for a sec every few secs and prevents me from moving.

This  happens to me too sometimes but i can still move when it happens.

**Comment by paramat** [comment]
> This happens to me too sometimes but i can still move when it happens.

Yes this is normal if flying into ungenerated mapblocks with noclip, you fly into ignore which is a dark node, so the wield goes dark.

**Comment by paramat** [comment]
> I increased client mapblock limit to 100 but it still seems to happen, although less likely it seems...will test more

Very likely settings used. No response.
