### ISSUE TITLE
Plantlike Meshoptions Visual Bug

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#5947]
Plantlike nodes used with meshoptions with the bits (in param2) set as following:

0 + 8 + 32

Plants set with this will be offset upwards, instead of downwards;

See http://i.imgur.com/00W8XFQ.png

You're clearly able to see that it's floating off the ground, instead of being inside the ground.

See https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L813

> Moves each face randomly a small bit down (1/8 max)

And in this case -- it's upwards. A vector has been changed since 0.4.15 and appears in the 0.4.16 stable.

**Comment by paramat** [comment]
@numberZero

**Comment by numberZero** [comment]
#5951

**Comment by paramat** [comment]
#5951 merged.
