### ISSUE TITLE
Extreme range digging/killing ability 3,000 meters+

### ISSUE THREAD

**Issue by jdc843** [minetest/minetest#5949]
For details see:
https://forum.minetest.net/viewtopic.php?f=6&t=17823

This has happened on Cash's World (0.4.15-git a few days before 0.4.16 release) and JT2.
PurpleOne (registered forum user) is the player that reported the problem, has the MT client that can do this, and is helping me test.
Maybe there is a conf option 'range_check = true' or something that I don't know about?

I will compile a 0.4.16 ( stable release version) server, use minimal minetest_game mods and enable verbose debug and do more testing.

This is a game breaker. CW is shut down until this problem is fixed.

**Comment by nerzhul** [comment]
do you enable anticheat ?

**Comment by jdc843** [comment]
No due to too many false detections in the past. Is the fix that simple? It would not surprise me :) I'll try it
Though I think JT2 has some kind of anti-cheat enabled there.

**Comment by sfan5** [comment]
There is nothing we can do if you disable anticheat.

**Comment by Fixer-007** [comment]
You have to enable anticheat, and what are those false positives?

**Comment by paramat** [comment]
> It's the mobile clients. MrHandsompig and muhdnurhidyat have both experienced the same problem with the 0.4.16 mobile client.

Are they using a non-official Android app or a hacked client? It may not be an official MT issue.

**Comment by nerzhul** [comment]
like we said in france: "No arms, no chocolate"

**Comment by jdc843** [comment]
Solved! Read first post in:
https://forum.minetest.net/viewtopic.php?f=6&t=17823

thank you for the help but sorry to bother you about this. Other problems now but time to end this issue.

**Comment by MuhdNurHidayat** [comment]
"Other problems" ... you're refering to the "extreme highlight" instead now? :P

while extreme range digging/killing could be solved server side with anticheat (you dig it and server restores that block, repeat), is there any way to actually limit the select/highlight range from client? some lines in minetest.conf??

It would be weird that you could highlight/select nodes very far but not dig it (anticheat is on) and it's also weird if you could stand in one place and destroys everything on sight (anticheat is off). Nodes very far away should not be highlightable in the first place.

I remember that 0.4.15 don't have this kind of problem so I'm wondering why it's there in 0.4.16... and it's official Minetest app for Android, not custom/community build nor forks.
