### ISSUE TITLE
Decorations higher than 1 block float in v6 at mudflow areas

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5952]
Decorations higher than 1 block can still float at mudflow areas:

![](https://i.imgur.com/F1Hy8xi.png)

Floating papyrus. :D

![](https://camo.githubusercontent.com/bf824ee98e822b28ede9fcca59ac43001dc30408/68747470733a2f2f692e696d6775722e636f6d2f67726f326342632e706e67)

Happens in 0.4.16.

This is a continuation of the discussions in https://github.com/minetest/minetest/issues/5796 and https://github.com/minetest/minetest/pull/5798.

**Comment by paramat** [comment]
Luckily papyrus is only ever at the water's edge so this is rare.

**Comment by Wuzzy2** [comment]
Minetest Game is not the only subgame. :-)

In my subgame, MineClone 2, I have plants of height 2 which can spawn anywhere in the world, not just near water. Luckily for me, they are not *that* common either. I still report this here for completenes' sake.

I kinda agree that there might be no easy fix. I'm not sure if it is a good idea to search just upwards from the node to delete more nodes. It seem like a lot of guessing is involved here.

**Comment by paramat** [comment]
Good point, will consider then.

**Comment by paramat** [comment]
Fixing this is straightforward won't be particularly intensive, will do so.

**Comment by paramat** [comment]
PR #5972 
Please test.

**Comment by paramat** [comment]
#5972 merged.
