### ISSUE TITLE
Unable to change empty password to secured one

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#5954]
I was trying to join 1248s Regnum test server, i realized my password is not secured and i accidentally logged in to server on my main account with no password required. During the game i cannot actually change my password. My old password is blank, just an empty old password, setting new password for secure and confirming password, then click button "Change". It won't actually change! Only host can change my password in player's file.

Can you reproduce glitch in 0.4.16?

**Comment by red-001** [comment]
I was able to reproduce this, it appears that password change will fail if this is your first login onto the server. It works fine after that.

**Comment by ExeterDad** [comment]
Confirmed as well. 0.4.16 release

**Comment by red-001** [comment]
From some preliminary research into whats causing this it appears to be the fault of the client. It seems to skip entering sudo mode and just sends the new authorization data.

**Comment by red-001** [comment]
It appears that the issue is that the client tries to use `AUTH_MECHANISM_FIRST_SRP` instead of `AUTH_MECHANISM_SRP`

**Comment by red-001** [comment]
I think someone that knows more about how SRP is suppose to work should take a lot at this, if I hardcode the client to use `AUTH_MECHANISM_SRP` it sends the wrong packet and it still fails. plus the server seems to be the one that tells the client what type of authorization to use for entering sudo mode

**Comment by rubenwardy** [comment]
bump

**Comment by Zughy** [comment]
Can't reproduce on 5.5, I tested in localhost both with the administrator account and another with no privileges (both with an empty password). Fixed I guess
