### ISSUE TITLE
minetest's build system does not properly clean files

### ISSUE THREAD

**Issue by apoleon** [minetest/minetest#5956]
Currently the build system does not clean all newly added and built files when the build process is started again and the compilation step is rerun. I would have expected that the clean target removed all those files from the source tree so that it becomes pristine again.

I have found the following files which are not removed in the clean target:
*.a, *.mo, *.o, *.bin and a.out files but there might be more. Please consider to support building minetest from the same source tree twice in a row.

**Comment by sfan5** [comment]
This is supported, all you need to do is an out-of-tree build.

It's however correct that CMake does not support something like `make distclean`, if you absolutely need something like that then this should remove most of the build files:
```sh
rm -rf bin CMakeFiles locale CMakeCache.txt cmake_install.cmake Makefile
```

**Comment by nerzhul** [comment]
mkdir build && cd build && cmake .. && make && cd .. && rm -Rf build.
