### ISSUE TITLE
Using clear_craft can remove more than one recipe

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#5962]
It took a while but I figured out how to repeat this problem:

1) Download and copy (into mods) the latest versions of the following mods:

pipeworks, technic, moreores - https://github.com/minetest-mods

2) Select "Minetest Game" as the subgame, and create a new world.
3) Configure and enable the above mods.
4) Play Game (Local)

/grant singleplayer all
/giveme wool:white
/giveme dye:dark_green

Now, if you try to combine the wool with the dye, it will show the output as green wool.

If you comment out the lines (in technic/machines/register/grinder_recipes.lua) where it says:

```
minetest.clear_craft({
	recipe = {
		{'default:sandstone'}
	},
})
```

Then try playing again, and you will see that the craft will produce dark green wool. At first, it seemed like maybe an issue with Technic, but I can't seem to find any reason simply removing the sandstone recipe would have any effect on wool + dye recipes.

**Comment by mtango688** [comment]
This is still a problem, as of the latest version.

**Comment by paramat** [comment]
Apparently fixed.
IRC http://irc.minetest.net/minetest-dev/2019-05-20#i_5546425

20:27 p_gimeno  #5962 is fixed, actually. It originated in https://github.com/minetest-mods/technic/issues/370 which was fixed in MTG.
