### ISSUE TITLE
Some sounds are not played

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#5967]
As of commit 683ab3a some sounds (placing blocks/torch/possibly others) are not played when connected to 0.4.16+ servers (singleplayer is fine).

On the other hand - digging, walking, opening chests, etc seems to work fine.

@Rui-Minetest @nerzhul and others who want to investigate are welcome.

**Comment by sfan5** [comment]
Guess:
pitch defaults to `0.0` which results in no sound

**Comment by Rui-Minetest** [comment]
#5968

**Comment by Rui-Minetest** [comment]
@Fixer-007
Are you checking with minimal?
It doesn't have much sounds.

**Comment by Fixer-007** [comment]
Fixed
