### ISSUE TITLE
Item tooltips wrongly sized when placing newlines

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#5977]
![ivw0ydo](https://user-images.githubusercontent.com/3686677/27108470-3c4d075a-5095-11e7-8f5b-ff5d4971d641.png)

**Comment by lisacvuk** [comment]
``[lisac@Pingus-PC src]$ minetest --version
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/local/share/minetest"
``

**Comment by SmallJoker** [comment]
Could you please provide the code that produces this tooltip? i.e. item description or the meta field.

**Comment by lisacvuk** [comment]
https://pastebin.com/FMYipePB

**Comment by paramat** [comment]
Drag-and-dropped image into first post, best to host the image with Github than an external hoster.

**Comment by lisacvuk** [comment]
this is fixed for a while. Forgot to close.
