### ISSUE TITLE
[feature request] Allow passing configuration options on the command line

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#5979]

**Comment by paramat** [comment]
?

**Comment by rubenwardy** [comment]
👍

**Comment by Calinou** [comment]
What kind of syntax should we use for this, considering users need to be able to supply several settings at once?

**Comment by nerzhul** [comment]
@Calinou --config=toto:tutu ? seems complicated for us, good idea but not simple

**Comment by numberZero** [comment]
`minetest --option name=value --option name2=value2`
One thing to notice is that these options should not be written to the configuration file (unless the user explicitly tells MT to do so). Also they should be displayed in the advanced settings menu differently from normal ones.

**Comment by paramat** [comment]
Sorry to ask, what is the usage for this feature?

**Comment by numberZero** [comment]
@paramat To test MT with different options not editing the config all the time. Most programs support that (except of win32 ones), and that’s really handy.

**Comment by paramat** [comment]
Many settings do not update until exiting and re-entering a world.

**Comment by paramat** [comment]
> One thing to notice is that these options should not be written to the configuration file (unless the user explicitly tells MT to do so). Also they should be displayed in the advanced settings menu differently from normal ones.

:-1: 
The config file is the source of settings so any change must be written there, and should be anyway.
Displaying these changes differently in advanced settings is complex and would not be necessary if we write to .conf as we need to do.

**Comment by MuhdNurHidayat** [comment]
Pretty sure it's more time-saving if MT could be tested with configuration options passed on command line, since it's not written to conf file (unless explicitly told to do so) then you don't need to undo changes in conf file if something goes wrong with some options.

**Comment by numberZero** [comment]
@MuhdNurHidayat I just wrote this script, it does the job (mostly). Place it in your `minetest/bin` directory.
For non-`RUN_IN_PLACE` versions, edit the `bindir` and `baseconf` variables correspondingly.
```bash
#!/bin/bash

bindir="$(dirname "$0")"
baseconf="$bindir/../minetest.conf"
conf="$(mktemp)"
extraconf="$(mktemp)"
cmdline=("$bindir/minetest" "--config" "$conf")
while [ $# -gt 0 ]; do
	arg="$1"
	shift
	case "$arg" in
		(--config) baseconf="$1"; shift;;
		(--option) echo "$1" >> "$extraconf"; shift;;
		(--) cmdline+=("$@"); break;;
		(*) cmdline+=("$arg");;
	esac
done
cat "$baseconf" > "$conf"
cat "$extraconf" >> "$conf"
rm "$extraconf"
"${cmdline[@]}"
rm "$conf"
```

**Comment by paramat** [comment]
>  since it's not written to conf file

As far as i know the .conf file is the only place these settings are stored and the place they are read from, so any changes must be applied there. Not doing so will probably cause many issues.
Most settings need a world restart to take effect, some a program restart.

**Comment by nerzhul** [comment]
interesting. Considering @numberZero as a workaround. Mt has too many configuration to pass settings into command line.

Closing, thanks
