### ISSUE TITLE
needed collision mesh

### ISSUE THREAD

**Issue by rogue-cupcake** [minetest/minetest#5986]
as some of the mesh items are not the best for the old coll/sell box way it would be a great idea to have the mesh be used as an option to make it simpler!

**Comment by paramat** [comment]
So you mean allow a meshnode to have simple collision and selection boxes instead of using the mesh for those?

**Comment by paramat** [comment]
Using the mesh as the collision volume would not be simpler, it would significantly slow down collision detection with no benefit.
Also no answer to my previous question.
