### ISSUE TITLE
(Security) Should JIT be disabled in server-provided client mods?

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#5987]
In case server-provided client mods are implemented, should JIT be disabled for them? Modern operating systems provide execute-write mutual exclusivity to help prevent code injection attacks, but JIT compilers offer a way around this protection if an attacker can write code that gets compiled to something that behaves maliciously when executed off of an instruction boundary.

Browser JS JIT compilers include security features since it is common to run untrusted code, but I feel as though LuaJIT doesn't have a similar level of protection. It might be wise to disable JIT compilation on server-provided client mods. This will result in reduced Lua performance, but I am not sure of what application client mods would have that is CPU intensive (ideas?).

**Comment by rubenwardy** [comment]
yes

**Comment by rubenwardy** [comment]
#7041
