### ISSUE TITLE
Missing documentation of mapgen aliases

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#5988]
Mapgen aliases (e.g. “`mapgen_dirt`”, “`mapgen_stone`”, etc.) are an important part of a subgame, all subgames are practically forced to define them, especially for v6. If you don't do this, your subgame almost certainly breaks and/or gets spammed in error messages on start.

Yet the mapgen aliases are completely undocumented at the moment. Please fix this.

**Comment by paramat** [comment]
Doesn't seem high priority, those who make subgames have qute a lot of MT knowledge so usually understand this already.
This is one of those many things that would be nice to have documented, but isn't an omission.

**Comment by paramat** [comment]
However it would be useful to know which aliases are necessary for core mapgen.
This is a job for me.

**Comment by paramat** [comment]
related #6106

**Comment by Ezhh** [comment]
Just to note - no documentation around this is a barrier for those trying to learn how to make subgames. It is not obvious that this needs to be done, nor is it obvious exactly how many of the possible things need to be defined (for example, if you are not aiming to support v6).  I'd offer to assist with this, but still don't understand it well enough.

Using "those who make subgames have qute a lot of MT knowledge" as a way to dismiss this is silly. There is no reason to learn about this until you try to make such things and people won't have this knowledge until they have somehow learned it.

**Comment by paramat** [comment]
Oops my comment there was not reasonable.
I've been thinking about this and intend to add it.

**Comment by paramat** [comment]
PR #5988

**Comment by paramat** [comment]
#6619 merged.
