### ISSUE TITLE
Red wieldhand in creative mode

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#5991]
![screenshot_20170615_231415](https://user-images.githubusercontent.com/3686677/27204029-9fad101a-5220-11e7-9d4e-2390130fe01f.png)

I'm on commit 2ab09bb48659c60e5dab19c3380a245e3eb19a17
Was not present in commit 5cc8ad946efb3612eb6ea8655780b29fe4c62e19
Wielded nodes or tools are unaffected.
Not caused by a MTG commit as i have just updated Engine without updating MTG.

**Comment by t0ny2** [comment]
My testing shows it appeared after commit bbe3dd9

**Comment by paramat** [comment]
Thanks, perhaps something to do with protocol.
That commit is actually considered potentially in need of a rework.

**Comment by Rui-Minetest** [comment]
#5995

**Comment by nerzhul** [comment]
seem @paramat you linked unrelated sentence with the bug. It's now fixed

**Comment by paramat** [comment]
My IRC link is about the commit that triggererd the bug, although it was not the cause of it, so related.
