### ISSUE TITLE
Windows compiler warnings

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#5992]
<pre>
[ 43%] Building CXX object src/CMakeFiles/minetest.dir/script/scripting_mainmenu.cpp.obj
In file included from minetest/src/socket.h:31:0,
                 from minetest/src/network/connection.h:24,
                 from minetest/src/client.h:23,
                 from minetest/src/script/lua_api/l_base.h:33,
                 from minetest/src/script/scripting_mainmenu.cpp:23:
/usr/x86_64-w64-mingw32/include/winsock2.h:15:2: Warnung: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h
  ^~~~~~~

[ 68%] Building CXX object src/CMakeFiles/minetest.dir/emerge.cpp.obj
In file included from minetest/src/socket.h:31:0,
                 from minetest/src/network/connection.h:24,
                 from minetest/src/server.h:23,
                 from minetest/src/emerge.cpp:44:
/usr/x86_64-w64-mingw32/include/winsock2.h:15:2: Warnung: #warning Please include winsock2.h before windows.h [-Wcpp]
 #warning Please include winsock2.h before windows.h
  ^~~~~~~

</pre>

**Comment by adrido** [comment]
They should be fixed by this: https://github.com/minetest/minetest/pull/5963

**Comment by SmallJoker** [comment]
@sfan5 Is it fixed now?
