### ISSUE TITLE
[Android] Using '/etc/hosts'

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#5994]
I've noticed on my Android devices that Minetest ignores the */etc/hosts* file. Which, to a degree, is understandable since the file is only editable on rooted devices. But, is there a way to get the Minetest client to recognize the entries in that file? Or is there another way to set up aliases for servers? That way I would be able to use a human-readable identifier for my local server rather than the IP address.

**--- Edit ---**

Would be nice to have a way to set up server aliases for non-rooted devices, maybe like a *hosts* file in the Minetest local directory, or *\<minetest-local\>/client/serverlist/hosts*.

**Comment by nerzhul** [comment]
It's not minetest role to handle those file but system.

**Comment by AntumDeluge** [comment]
Just as a follow-up, I was wrong about Android ignoring */etc/hosts*.

**Comment by MuhdNurHidayat** [comment]
so, no way to use it on non-rooted phone?

**Comment by AntumDeluge** [comment]
@MuhdNurHidayat Not that I know of. That's why I still think it would be a good idea to have a file in the minetest directory that could used to set aliases for IP addresses.
