### ISSUE TITLE
Compiler warning after commit 76be103

### ISSUE THREAD

**Issue by t0ny2** [minetest/minetest#5997]
Compiler warning after commit 76be103

<pre>
In file included from minetest/src/environment.cpp:21:0:
minetest/src/environment.h: In constructor ‘Environment::Environment(IGameDef*)’:
minetest/src/environment.h:121:12: warning: ‘Environment::m_gamedef’ will be initialized after [-Wreorder]
  IGameDef *m_gamedef;
            ^
minetest/src/environment.h:85:21: warning:   ‘std::atomic<float> Environment::m_time_of_day_speed’ [-Wreorder]
  std::atomic<float> m_time_of_day_speed;
                     ^
minetest/src/environment.cpp:30:1: warning:   when initialized here [-Wreorder]
 Environment::Environment(IGameDef *gamedef):
</pre>

**Comment by nerzhul** [comment]
yeah i missed it. it's fixed in #5999 PR which cover more cleanups

**Comment by SmallJoker** [comment]
Pull mentioned above is merged.
