### ISSUE TITLE
I can fly!

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#5998]
```
diff --git a/src/client.h b/src/client.h
index b4145c76..a163ff6d 100644
--- a/src/client.h
+++ b/src/client.h
@@ -414,7 +414,7 @@ class Client : public con::PeerHandler, public InventoryManager, public IGameDef
        u16 getHP();
 
        bool checkPrivilege(const std::string &priv) const
-       { return (m_privileges.count(priv) != 0); }
+       { return true; }
 
        bool getChatMessage(std::wstring &message);
        void typeChatMessage(const std::wstring& message);
```

**Comment by srifqi** [comment]
Is there a way to prevent it from server-side?

IDK much about Minetest's anticheat system.

**Comment by C1ffisme** [comment]
@srifqi Maybe if you prevented lengthened amounts of time in the air if a player does not have the fly privilege on the server side?

**Comment by sfan5** [comment]
This is not really a bug, we are aware of this and it has been known a long time.
Server-side anticheat currently does not counter this, it probably should.

**Comment by PowerOlive** [comment]
so have you fix this using sscsm?

**Comment by SmallJoker** [comment]
@PowerOlive Assuming your question is meant serious: No, nothing what's executed on client-side can be assumed to be "safe" because everything can be modified there. It's up to the server to simulate the player physics (see #6219) to improve the anticheat feature.

**Comment by ClobberXD** [comment]
> Assuming your question is meant serious

It probably isn't...

**Comment by PowerOlive** [comment]
it means what i do is not so interesting

**Comment by PowerOlive** [comment]
@SmallJoker so you are going to rewrite the whole irrlicht to let the server do all the jobs?
