### ISSUE TITLE
World data transfer and voxel mipmapping for distant geography

### ISSUE THREAD

**Issue by moemis** [minetest/minetest#60]
Here's a way to allow the player to see very distant terrain without overly taxing the server's working memory or the client's bandwidth:

Divide each chunk into power-of-2 sized volumes and choose the block type with the highest quantity in each, then store this data with the chunk as its low-res versions. When a piece of geography is to be sent to the player, send an appropriate low-res version instead if it is far enough away. This is conceptually somewhat like texture mipmapping, where a scaled-up lower-resolution texture can be a reasonable substitute for a high-resolution texture if the surface is far enough away.

Possible downside: Higher load on new servers because they'd have to generate more distant terrain right away.

I'd like to try implementing this myself as a way of getting my feet wet with the source. Any tips on how I should do this so that it's likely to get pulled back into the trunk?

**Comment by paramat** [comment]
See #3502 for farmap work, this can possibly be closed?

**Comment by paramat** [comment]
Closing as farmap is now in development.
