### ISSUE TITLE
Why zh_CN in blacklist

### ISSUE THREAD

**Issue by 71e6fd52** [minetest/minetest#6006]
In my computer, zh_CN works good.

**Comment by sfan5** [comment]
I think it's there because it didn't work on Windows, will have to check again.

**Comment by rubenwardy** [comment]
bump

**Comment by paramat** [comment]
@sfan5

**Comment by sfan5** [comment]
Well it's certainly working now.

zh_CN:
![bildschirmfoto_2018-05-16_10-08-27](https://user-images.githubusercontent.com/1042418/40104921-cfbe040c-58f1-11e8-99bf-1f3db580c81a.png)
zh_TW:
![bildschirmfoto_2018-05-16_10-10-11](https://user-images.githubusercontent.com/1042418/40104924-d3b06fc8-58f1-11e8-982b-a897cd27f6f6.png)

**Comment by SmallJoker** [comment]
#9229
