### ISSUE TITLE
Map stops loading, formspecs won't open, but all other server activity appears normal (for a while)

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#6009]
Using the regular Minetest client, at commit 63ca71e9d2c1131675a7a47a7155458af6a36e3e, server is at commit 7786521f151b6006656768fdd308f1d7e1635645.

Client build method:

```bash
#!/bin/bash

export CXXFLAGS="-O3"

cd /home/vanessa/Minetest-related/minetest_core

make clean
rm CMakeCache.txt
cmake . -DRUN_IN_PLACE=0 -DCMAKE_BUILD_TYPE=Release \
	-DENABLE_FREETYPE=true -DENABLE_LEVELDB=true \
	-DENABLE_GETTEXT=true \
	-DCMAKE_INSTALL_PREFIX=/usr

make -j8

sudo make install
```
Server build method:
```bash
#!/bin/bash

cd /home/minetest/luajit-2.1-gc64/
make clean
XCFLAGS=-DLUAJIT_ENABLE_GC64 make -j8

cd /home/minetest/minetest_core

make clean
rm -f CMakeCache.txt
export CXXFLAGS="-O3 -march=native"

cmake . -DRUN_IN_PLACE=0 -DBUILD_CLIENT=0 -DBUILD_SERVER=1 \
	-DCMAKE_BUILD_TYPE=Release -DENABLE_GETTEXT=1 \
	-DCMAKE_INSTALL_PREFIX:PATH=/usr -DENABLE_LEVELDB=1 \
	-DLUA_LIBRARY=/home/minetest/luajit-2.1-gc64/src/libluajit.so \
	-DLUA_INCLUDE_DIR=/home/minetest/luajit-2.1-gc64/src

make -j10
make install
```
* Sign onto daconcepts.com port 30001.  Be prepared to wait a long time (2-3 minutes) for media download and init.
* Walk around and get the map to load up around you in all directions out to the send/load limit.  It doesn't matter where you are on the map - you could be near the spawn, or 10km away, but it would be good if you end up near another, active player, watching him/her.
* Either just step away from the game for a while, or play as you see fit, with one exception:  don't turn around -- keep your view fixed in the same direction (e.g. north) at all times.
* After a while, turn around to look behind you. You will notice that some of the map will have unloaded, as is normal.
* You'll also notice that the map will stay not-loaded.  That is, the unloaded map will refuse to reload, and for that matter, no other part of the map (whether recently visited or not) will load, either, so if you're 10km away and you do `/spawn`, you'll be teleported into and remain in unloaded space. The odd thing is that *entities* within the un-loaded blocks *will* reload even though the terrain containing them does not show up.  Meanwhile, everything else around you continues to run normally, both at the global level (no server lag, players chatting, signing on/off, etc), and in-world, both inside the still-loaded region and outside of it (players building and digging, mesecons machines running, Pipeworks tubed entities flowing around, etc).  I've spotted only two exceptions to that "normally" part:
  * some formspecs such as the ones in a Pipeworks Deployer or Node Breaker will no longer open with a right-click - your client will erroneously try to do a *place* event instead, as if the node you right-clicked on had no formspec at all, or it may do nothing useful at all.
  * mapblocks within the area that IS still loaded will no longer update properly.  For example, a mesecons circuit that's sitting there operating (say, a clock circuit) periodically may not show its wires lighting up anymore, while another player standing next to you will see them behaving normally.
* After some amount of time (I don't know exactly how long, maybe hours), the client will act as though it has lost all communication with the server - no other-players' movements, no chat, no chat commands, etc. I did not test whether I could build in the still-loaded area when it got to that point.  It's as though the client has timed out, except that neither it nor the server actually say so.  If I then sign out from the client normally, the server reports (e.g. via logs and IRC) that the client did indeed sign out properly (i.e. NOT a timeout).
* Sign out, sign back in, and the map will reload normally, and formspecs will start working again.

Neither the server nor client debug log tells me anything useful (but I do not have them in verbose mode, as the server's log is already too active as it is), and I see nothing of particular interest at the OS level either, except huge repeats of this message in the server's `dmesg` output:

```
[17214173.848088] IPv6: udp checksum is 0 for [*** my client PC's IPv6 address here ***]:49783->[2001:41d0:2:ba51::1]:30001
```

(there is nothing of interest in my client PC's logs, `dmesg` or otherwise)

**Comment by paramat** [comment]
@lhofhansl any ideas?

**Comment by paramat** [comment]
Once you turn around, will the terrain start to load in if you move towards it?

**Comment by VanessaE** [comment]
Nope.

**Comment by VanessaE** [comment]
Here's a new bit that I didn't think to check for:  If the map stops loading, and you turn to face the unloaded part, and there's only a couple of mapblocks left in your view (i.e. you're standing at the edge of the unloaded space), and then you turn around and look behind you, you will find yourself trapped on an "island" only a few square mapblocks in size, floating in the void.  Here's what I was left standing on after leaving my client idle for a couple of hours:

![screenshot_2017-06-18_18-42-11](https://user-images.githubusercontent.com/1733537/27264831-e390ce98-5455-11e7-8e3a-e9283164c9a4.png)

Notice my wield item is black.

**Comment by VanessaE** [comment]
Here's a new bit that I didn't think to check for:  

Earlier, my client stopped loading the map, hence filing this issue.  After my last comment, I unintentionally left my client idle while staring off into unloaded territory.  There were only a couple of mapblocks in my view at the time.

When I came back, I realized I'd left the client idle for nearly 3 hours.  I un-paused, turned around, and as expected, the map behind me had unloaded as well, and also refused to re-load.  That left me standing on an "island" floating in the void, only about 2x2x2 mapblocks in size.  

So I flew up and back a bit, and snapped a screenshot:

![screenshot_2017-06-18_18-42-11](https://user-images.githubusercontent.com/1733537/27264831-e390ce98-5455-11e7-8e3a-e9283164c9a4.png)

Notice my wield item is black (it's supposed to be a yellowish mesecons wire).

**Comment by VanessaE** [comment]
(oops)

Also, it looks like if I leave the client idle long enough, all activity from the server goes dead.  No players' chat, no chat commands, no sign-ons/sign-offs, etc.  However, I don't show as actually having signed off (for any reason), until I actually tell my client to sign off (then I show a normal sign-off event).

**Comment by paramat** [comment]
The wielditem going dark means you are probably in 'ignore' nodes, if you disable noclip you probably cannot enter the unloaded volumes.

Note your server is on a commit from June 3rd, your client is 0.4.16 stable. Just in case the non-recent server commit is a factor.

**Comment by VanessaE** [comment]
The server's only three commits past 0.4.16-release, my client is one commit newer.  I doubt that's the problem, but for the sake of science :smile:  I've put them both right at 80dc961d (where the 0.4.16 tag points), and will double-check the behavior.

**Comment by VanessaE** [comment]
Yep, it does the same thing when both ends are at that commit (I only waited long enough to see if the terrain would reload or not).

**Comment by Fixer-007** [comment]
Can't reproduce on client 071736ba

**Comment by VanessaE** [comment]
I should note:  I couldn't reproduce it in singleplayer.  That said, I fail to see how a bad HUD reference can stop the map from loading.

**Comment by nerzhul** [comment]
@VanessaE there is no relation between both cases, the switch only affect HUD rendering (directly) and can trigger a crash not map loading

**Comment by VanessaE** [comment]
Oh ok.

**Comment by Wuzzy2** [comment]
Do you use the debug build and have you maybe accidentally pressed F4 without knowing it? :grin:

**Comment by VanessaE** [comment]
It is a release build and I am 100% certain I didn't press any unusual keys, because the client was paused each time this happened (maybe that's relevant?).

**Comment by Fixer-007** [comment]
Still happens?

**Comment by VanessaE** [comment]
Haven't tested anything newer, and I don't plan to until 0.4.17 is out and I can be sure it's compatible with my servers/mods/etc.

**Comment by VanessaE** [comment]
this seems to be fixed now.

**Comment by gpcf** [comment]
@VanessaE When was this issue fixed? It seems to happen on Linuxworks server frequently after we applied #9114 onto 0.4.17.1

**Comment by VanessaE** [comment]
I'm not sure -- a lot has changed since 04.x was replaced with the 5.x.x series.

**Comment by gpcf** [comment]
Do you know by any chance if it in 0.4.17.1 or 5.0?
