### ISSUE TITLE
[Request] Refresh button on server list

### ISSUE THREAD

**Issue by Arnaz87** [minetest/minetest#6028]
This is probably because where I live we have bad internet connection, but most of the time when I want to play online the server list doesn't load, and this is what is printed to the terminal:

`2017-06-22 13:54:32: ERROR[AsyncWorker-0]: servers.minetest.net/list?proto_version_min=25&proto_version_max=32 not found (Timeout was reached) (response code 200)`

And then nothing happens, it just does not ever appear. I have to restart the game a few times for the server list to show (nothing is printed when when it does appear).

If the first connection fails, I think the client should keep retrying until it works, or until a certain limit of connections have failed.

**Comment by octacian** [comment]
Maybe we should add a refresh button to the server list? It would both solve this issue and, obviously, allow you to update the server list and any point in time.

**Comment by Arnaz87** [comment]
Yes, that does sounds like a better idea. I can work on this if needed. Where should the button be? I think at the right of the Search button, or at the left of the Search field with a refresh Icon.

**Comment by octacian** [comment]
Go for it. Was going to tackle this a while back, but don't have time.

I'd suggest you use an image button with an icon and a tooltip when it comes to visual appearance. In the general area of the search bar and button would be a good place IMO.

**Comment by nerzhul** [comment]
a refresh button is better than a hacky retry

**Comment by octacian** [comment]
I believe that's what we're going for here, unless I misunderstood.

**Comment by nerzhul** [comment]
It's now merged
