### ISSUE TITLE
Fullscreen on multiple monitors is broken

### ISSUE THREAD

**Issue by mnn** [minetest/minetest#6029]
After finding hidden option to enable fullscreen mode (like what the hell? why is fullscreen hidden in "advanced" options?) I enabled it. Unfortunately the game is broken on dual monitor setup - I have one monitor with full HD and other with 4k resolution. Minetest in fullscreen mode runs on **both** monitors - on a full HD monitor is visible only center part of left half and on a 4k monitor I can see in its center right part of Minetest. The worst thing is I can't even revert the fullscreen mode, because I don't see enough on a full HD monitor so I can't navigate to that hidden option... I though maybe there is a hotkey (tried alt+enter), but after searching issues I learned there actually is not #2732 #4609 :worried:.

**Comment by rubenwardy** [comment]
Fullscreen is broken as we use "real" fullscreen as a driver mode, rather than a windowless full screen.
If possible you should use alt+F11 as a workaround (this is supported on most Linux distros)

**Comment by mnn** [comment]
Thank you for answering. Sadly, <kbd>ALT</kbd> + <kbd>F11</kbd> is not doing anything for me :'(. I am using KDE (Kubuntu) and after launching the game I can't even switch windows with <kbd>ALT</kbd> + <kbd>TAB</kbd> (to try fiddling with window settings, to free mouse).

**Comment by rubenwardy** [comment]
you need to remove `fullscreen = true` from `minetest.conf`

**Comment by mnn** [comment]
That did the trick, thanks ^_^. Now I can at least play it windowed or try the KDE's borderless thingy.

I am not sure if the fullscreen mode was actually working, because after launching it in a window mode, the game window was positioned exactly as before in the full-screen mode.

Forgot to mention version: 0.4.16 (the one from Ubuntu PPA).

**Comment by nerzhul** [comment]
solved

**Comment by rubenwardy** [comment]
#4921
