### ISSUE TITLE
Add statbar background icons

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6030]
I suggest to add background icons for the statbars by default. This includes the heart and bubble icons, but also the statbar API.

**Rationale:**
Your brain can not instantly tell how much health you have *without counting each heart one-by-one* here:

![Some hearts. Maybe 9? Or 10? Or just 8?](https://i.imgur.com/yHNsNls.png)

But with background icons, you can:

![Obviously 9 hearts](https://i.imgur.com/56Qw7UY.png)

Oh, how often have I already pointlessly wasted food because of eating at full health! :grinning: 

**Technical notes:**
First, in the HUD element definition, another field for a background icon must be added. For health and air, the default image files could be `heart_bg.png` and `bubble_bg.png`, respectively.
Also, each statbar must know its maximum count, obviously.

**Suggested rendering algorithm:**
* On a “classic” health bar (20 half hearts), it could work like this:
    * The number of total half hearts (both “active” and “inactive”) rendered equals the maximum statbar size. In this case: 20
    * An “active” (red) heart is always drawn by drawing `heart.png`.
    * An “inactive” (gray) heart is always drawn by drawing `heart_bg.png`.
    * A “half” heart is drawn by drawing the left heart of `heart.png`, directly followed by the right half of `heart_bg.png`.
    * Exception: No background image is rendered if the required variable set to `nil`.

Note this rendering algorithm intentionally does *not* involve any texture overlays. This is done to give artists more artistic freedom. (OK, pedantically, that would mean there would also be a separate icon for a “half” symbol (half active, half inactive)) Of course, the same algorithm applies to bubbles and custom statbars.

**Justification for engine feature (rather than mod feature):**
This will be an obvious and easy improvement for all subgames. Nobody will seriously miss the current hard-to-count statbars. But there is still backwards-compability in mind.

**Data files for you:**
Here you can find free background icons for free, in the HUD Bars mod: https://forum.minetest.net/viewtopic.php?f=11&t=11153

![HUD Bars icons](https://i.imgur.com/QwWox6B.png)

**Comment by red-001** [comment]
working on this.

**Comment by paramat** [comment]
Potentially a good idea.

**Comment by RICCIARDI-Adrien** [comment]
Hi,
It might be possible to implement this feature directly in engine `void Hud::drawLuaElements(const v3s16 &camera_offset)` method.
It seems that the `HudElement *e` object content when `HudElement::type == HUD_ELEM_STATBAR` does not use `HudElement::name` and `HudElement::item` fields. This way, statbar size (i.e. how many items to display when bar is full) could be assigned to `HudElement::item` and the statbar alternate texture could be assigned to `HudElement::name`. This way, method `void Hud::drawStatbar(v2s32 pos, u16 corner, u16 drawdir, const std::string &texture, s32 count, v2s32 offset, v2s32 size)` is provided with all needed settings to draw a statbar with "off state" icons.  
Furthermore, this feature could be disabled for mods that do not want it by setting `HudElement::item` to zero and checking for it in `drawStatbar()`.  
I'm new to Minetest and I don't know engine internals, so maybe I'm wrong ! If Minetest community think that this idea can work, I can try to implement it.

**Comment by rubenwardy** [comment]
@RICCIARDI-Adrien  there's already a PR open:  #9462
