### ISSUE TITLE
Mapgen: dungeons outside of ground

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6044]
Today when i tested non related thing, mapgen generated dungeon outside ground, it's not natural and ugly

![capture d ecran de 2017-06-25 14-20-53](https://user-images.githubusercontent.com/119752/27516036-a3ffaf9a-59b1-11e7-901a-e5bffb6d7007.png)

**Comment by MarkuBu** [comment]
I posted this issue before. https://github.com/minetest/minetest/issues/5204
