### ISSUE TITLE
crack overlay isn't shown on tiles that have overlay_tile above

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#6046]
Example:
![screenshot_20170625_150009](https://user-images.githubusercontent.com/7613443/27516267-2ea95240-59b7-11e7-89c4-bf609db7a7cc.png)
The wool texture is in tiles. The top has no overlay, crack is ok. On the side, where `overlay_tiles[<side>]` isn't `""`, the crack is only where the overlay_tile isn't transparent.

**Comment by SmallJoker** [comment]
Related: #5317

**Comment by juhdanad** [comment]
It is not related to #5317, I think. The problem is that the crack overlay is only drawn on top of the topmost layer.
