### ISSUE TITLE
noclip: Avoid pointing the node which contains the camera position

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6049]
Currently when you are in a cave, then walk backwards into the wall, you point the nodes in the wall you stick in and don't see (backface culling).
l'd like to have following behaviour:
If the node at the camera position is pointed and the camera position is inside the selection box of the node, the pointable selection boxes in the shooting ray are ignored until a node is found which isn't pointed. Then finding the pointed node continues as usual (stopped skipping).
So when you use noclip and walk backwards into a wall, you still point to the opposite wall of the cave and not to the nodes which are invisible from your perspective.

**Comment by paramat** [comment]
:-1: Behaviour while using noclip is irrelevant, obviously behaviour will be strange.

You may be close to a junglegrass node or a large plantlike decoration such that the camera is inside the selectionbox, but if you are pointing at the decoration that should still be selected.

Now consider that players are often spawned inside a tree node,  they can only escape by punching the node from inside. Likewise there are situations where a player may be buried inside a node and will need to remove it.

**Comment by HybridDog** [comment]
> they can only escape by punching the node from inside

They don't have noclip.

The changed behaviour happens only if you have noclip and are flying.

**Comment by paramat** [comment]
Ok, but this seems pointless.

> Currently when you are in a cave, then walk backwards into the wall, you point the nodes in the wall you stick in and don't see (backface culling).

This will only change behaviour if you are up to 1 node deep in a wall, any deeper and you have previous behaviour and will still dig a close and invisible node instead of a node on the opposite wall.
I expect to point and dig the closest node even if it is invisible because i am inside it. This also mean that the F5 information for the node you are in is incorrect, making that less useful for dev work.

**Comment by HybridDog** [comment]
It can be disabled via a setting for people who don't like it.
And it works not with only one node but with nodes until a not pointable one is found.

**Comment by paramat** [comment]
A setting doesn't make a pontless feature mergeable.

> it works not with only one node but with nodes until a not pointable one is found.

Ok, but this is even worse, now while flying underground i cannot dig a node unless it is an air neighbour.
I still can't see any need or use for this.

**Comment by HybridDog** [comment]
If you see a mese blocks you don't need to fly into the caves to dig them.

**Comment by rubenwardy** [comment]
this seems unpopular, and I personally don't think it's worth it.
