### ISSUE TITLE
Optional light level range for decorations

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6053]
I suggest to add an optional light leven range to generate decorations.

In the decoration definition, add 2 optional fields:

* `max_light`: Maximum light level in which the decoration can be generatee. If `nil`, there is no upper bound.
* `min_light`: Minimum light level in which the decoration can be generated. If `nil`, there is no lower bound.

To be precise, the light level of the bottommost/“first” node to be occupied be the decoration must be checked for this. For flowers this means the node in which the flower wants to be generate and for cacti this means the bottommost node cactus node.

Example: `max_light=10` and `min_light=1` means the decoration will only be generate if the checked node has a light level between 1 and 10 inclusive.

Use case: Make mushrooms appear in darkness only. In Minetest Game and MineClone 2, mushrooms don't like direct sunlight and the node disappears eventually, but mushrooms can still spawn in direct sunlight. Implementing this suggestion will fix this oddity.

Minetest Game issue: https://github.com/minetest/minetest_game/issues/1799

**Comment by Wuzzy2** [comment]
This is not a client or audiovisual issue. This is a mapgen issue.

**Comment by paramat** [comment]
This is actually 'can't add' because when decorations are added light does not exist in the voxelmanip, light is calculated as the last step in mapgen after decorations and all else are added.
