### ISSUE TITLE
Hand isn't visible with arm inertia enabled.

### ISSUE THREAD

**Issue by red-001** [minetest/minetest#6054]
![screenshot_20170626_191935](https://user-images.githubusercontent.com/12450071/27553891-9a19be14-5aa4-11e7-9e08-302862442d1d.png)

**Comment by Xanthin** [comment]
For me it's visible.
![peek 2017-06-26 23-24](https://user-images.githubusercontent.com/6878547/27561166-5aab646c-5ac7-11e7-8984-0b4ec35268cb.gif)

**Comment by nerzhul** [comment]
Fixed
