### ISSUE TITLE
Items with empty metadata and nil metadata are considered different

### ISSUE THREAD

**Issue by nybble41** [minetest/minetest#6057]
After updating to 0.4.16 I found that sometimes seemingly identical stacks of ordinary items (like wool) would refuse to combine. Examining the player inventory, I found that every item in the inventory with a nonzero "wear" had acquired a metadata string like "\u0001\u0002\u0003" (empty key and empty value). If this extra text was removed from the database it would reappear the next time I logged in to the server.

I tracked this down to the code which parses the metadata from an item string. If there is no wear field, the item stack stops parsing without attempting to load any metadata. However, if the wear is present then metadata is always loaded; when there is no more text to be read from the item string the legacy compatibility code still  kicks in and sets the empty key to the empty string:

    void ItemStackMetadata::deSerialize(std::istream &is)
    {
            std::string in = deSerializeJsonStringIfNeeded(is);

            m_stringvars.clear();

            if (!in.empty() && in[0] == DESERIALIZE_START) {
                    Strfnd fnd(in);
                    fnd.to(1);
                    while (!fnd.at_end()) {
                            std::string name = fnd.next(DESERIALIZE_KV_DELIM_STR);
                             std::string var  = fnd.next(DESERIALIZE_PAIR_DELIM_STR);
                            m_stringvars[name] = var;
                    }   
            } else {
                    // BACKWARDS COMPATIBILITY
                    m_stringvars[""] = in; 
            }   
    }

So an item which originally had no metadata acquires a key/value pair, which is then written out the next time the inventory table is updated.

The fix is simple; just move the "if (!in.empty())" condition so that it covers both the new deserialization code and the legacy compatibility branch.

(The fact that wool had a nonzero wear is the subject of a different issue relating to the mobf framework—it's appending the suffix ```" 1"``` to all item strings, even those which already have a count field. Ergo, wool crafted from from cotton is fine but the wool received from shearing a sheep arrives ever so slightly worn.)

**Comment by rubenwardy** [comment]
The equals function in metadata should take this into account as well, ideally

**Comment by TurkeyMcMac** [comment]
If metadata contains an empty value, I would consider that a bug. The metadata API is supposed to guard against it. If the API is coded correctly, checks added in the comparison code will be redundant. Such bugs should be solved through input validation, as this bug was. Comparing two objects is harder if they are not in canonical form.
