### ISSUE TITLE
3D modes broken

### ISSUE THREAD

**Issue by srjskam** [minetest/minetest#6059]
When I enter any 3D mode, the view is distorted and controls behave strangely. It seems that the viewpoint of the player stays fixed at 0,0,0, and only the rotation of the viewpoint is affected by moving. A block representing the player can be seen moving in the world if you manage to align the view right.

I've tested this on 0.4.16 and nightly build `201706261140-0~936d67d~ubuntu16.04.1`, xenial.

This issue has also been documented at https://forum.minetest.net/viewtopic.php?f=3&t=17782, but not reported apparently.

Image: screenshot from anaglyphic mode. The 'player' can be seen on the left side.
![screenshot_20170627_094254](https://user-images.githubusercontent.com/26146452/27574213-1f2945c4-5b1e-11e7-9eb2-8e801099d2e1.png)

**Comment by srjskam** [comment]
I managed to fix this, submitted pull request: https://github.com/minetest/minetest/pull/6158 .

**Comment by lhofhansl** [comment]
This seems to be fixed now...? Tried yesterday and it worked fine. Looks like #6158 was not merged, though.

**Comment by SmallJoker** [comment]
#6253 ("Rewrite rendering engine") was merged about a month ago. Please check whether this is still a problem in a fresh 0.5.0-dev build and reopen this issue if it's the case.

**Comment by srifqi** [comment]
Seems like already fixed. Checked using f470cb7 version.

**Comment by axredneck** [comment]
Still an issue. Minetest 0.4.17.1, Arch Linux, Nvidia GTX 1050.

**Comment by SmallJoker** [comment]
@axredneck You'll need Minetest 5.0-dev because these major render changes were not backported.
