### ISSUE TITLE
Arm inertia is broken 

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#6060]
Regression caused by https://github.com/minetest/minetest/commit/53a6b5439eac140bbbe76441a4d6a02590fadb2f
Cc: @nerzhul 

It doesn't work at all on the Y axis, and it's slightly misbehaving on the X axis too.

**Comment by nerzhul** [comment]
the limit case on Y is wrong

**Comment by kilbith** [comment]
https://github.com/minetest/minetest/commit/48cd217e3b6f53af32802c1897ddd1914d215078
