### ISSUE TITLE
Issues with arm inertia motion

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6063]
I tested the most recent arm inertia commit 48cd217e3b6f53af32802c1897ddd1914d215078
Although i'm personally not keen on arm inertia, independent of that there are some obvious issues with the behaviour, i feel the feature was merged before an acceptable motion was developed.

* The return to centre has a constant velocity then a sudden stop.
With a combination of horizontal and vertical displacement the return motion is diagonal, then abruptly hits an axis and then moves along that axis until another abrupt stop at the centre. It looks a bit robotic and the abrupt stops are visually distracting.
Perhaps this could have a smoother non-linear return motion where return velocity reduces near the centre?

* Long camera pans build up an overly-large hand displacement and afterwards a long slow return to centre.
I feel the displacement should not become so large, inertia is due to acceleration not motion, so a long constant pan should not keep buildng up more displacement.
After a large displacement the return needs to be much faster, this will create the feeling of a more agile player. Large hand displacement gives the impression of weak and limp arms, this is out of character with how agile and energetic a MT player is.
Perhaps a solution is making the return faster at larger displacements and slower nearer the centre, which is also what i suggest in the above issue.

* A more minor issue, at a certain pan velocity the hand jitters slightly, this also might be solved by making return velocity lower nearer the centre.

**Comment by kilbith** [comment]
I could add an acceleration / deceleration factor relative to the default position and camera speed to avoid this "abruptness". This is a good idea.

Your second point (i.e. _"this is out of character with how agile and energetic a MT player is"_) is subjective so I prefer not commenting it.

Last point, I do hope this is not an opportunistic issue to justify a removal of this feature, knowing your disgust for the arm inertia. Otherwise I'd not bother to address your suggestions.

**Comment by kilbith** [comment]
I'll work on improving the motion tonight.

**Comment by DS-Minetest** [comment]
I'm not sure if it's intended but #5490 doesn't work anymore.

**Comment by kilbith** [comment]
So I already have a working implementation for the smooth deceleration, this looks quite better. Tomorrow I'll try to make a proper vector of movement.

Thanks for the feedback, despite your disliking for the inertia.

**Comment by paramat** [comment]
> Your second point (i.e. "this is out of character with how agile and energetic a MT player is") is subjective

Tihs is not subjective, if you look at the motion of the arm while walking, and the motion of the player model it's quite fast and agile.

> Last point, I do hope this is not an opportunistic issue to justify a removal of this feature

No, it's popular and i'm not going to suggest removal. There's a setting so i am happy (and thanks for the setting). Here i have put aside my dislike and my approach is "now that we have it, let's work on making it as good as possible". I was actually concerned this could be interpreted as an attack but i am honestly being constructive :]

**Comment by paramat** [comment]
#6071 merged.

**Comment by Fixer-007** [comment]
Still needs improving in my opinion, i will try to record gifs of problems I still have (jitter and "reset").

**Comment by kilbith** [comment]
The motion depends on the frame time. Your frame time is abnormal, try capping your FPS at 60 and your frame time should (ideally) be at 16 ms, if your monitor has a refresh rate of 60 hz (like the big majority of monitors).

EDIT: https://github.com/minetest/minetest/pull/6094 could fix your issue though. Also it's kind of sad that people actually test once things get merged...

**Comment by paramat** [comment]
@Fixer-007 is your issue fixed now?

**Comment by paramat** [comment]
Seems so.
