### ISSUE TITLE
make it possible to color with meta only specific parts of an item's inventory and wield image

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#6064]
For nodes there's soft overlay with `overlay_tiles` for hardware coloring with `param2`. So, if you dig such a node you get an item that has the `palette_index` meta field. But this colors everything of the item's inventory and wield image.
There would be many usecases, eg. coloring only the wool part of MTG's bed item's inventory and wield image.

**Comment by juhdanad** [comment]
The reason this is not implemented yet is that I could not find a consistent and intuitive way for extending the Lua API. I do not want to add fields like `overlay_wield_image` and `overlay_inventory_image`, that would not be general at all.

Do you (all moders interested in overlays) have ideas how overlays should be generalized to those textures as well?

If not, I can still implement overlays for items, I just want to do this in the right way.

**Comment by DS-Minetest** [comment]
Well, the best would be if the texture strings could be changed with meta. Would that be easy to do?

**Comment by juhdanad** [comment]
It would be harder than to add overlays to items.

I also would like to add overlays to items, because now conversion between colored items and nodes is automatic. It is more convenient to use overlays than to create a custom conversion code between a node's param2 and an item's texture string.

**Comment by DS-Minetest** [comment]
I think, overlay images (that are not colored) would be enough.

**Comment by Fixer-007** [comment]
Can be closed?
