### ISSUE TITLE
get_inventory returns nil for Lua entities

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6079]
If you register an entity with Lua using `minetest.register_entity`, the function `get_inventory` always returns `nil`. Note: The documentation claims that `get_inventory` always returns an `InvRef`. This is clearly false.
Tested in 0.4.16.

Test code:
```
minetest.register_entity("test_entity_inventory:entity", {
	visual = "cube",
	infotext = "Inventory test entity. Rightclick to show inventory.",
	on_rightclick = function(self, clicker)
		-- Get inventory
		minetest.chat_send_player(clicker:get_player_name(), "Inventory contents: " .. dump(self.object:get_inventory()))
	end,
})
```

Put this into `init.lua` in a mod named `test_entity_inventory`. Spawn the entity with `/spawnentity test_entity_inventory:entity`. A cube appears. Rightclick the cube to see the return value of `get_inventory` (see code above). I expect to get some userdata or a table, but instead I only get `nil`.

I conclude that this bug means it is currently not possible for a Lua entity to have an inventory. :disappointed:

**Comment by SmallJoker** [comment]
In contrast to you I interpret this issue as a feature request, as there's no functionality for inventories for LuaEntities yet: No functionality = lack of features = no bugs (yet). Otherwise we'd have tons of bugs because of lacking features.
The mods I've seen used detached inventories to solve this problem, which works but isn't a proper solution. Having inventories for all entities would be a great thing, indeed.

**Comment by Wuzzy2** [comment]
It's a documentation bug, then. The docs claim this returns an inventory, while it actually returns `nil`.
At the very least, an appropriate warning in `lua_api.txt` should be written about the fact that this (currently) returns `nil` for Lua entities.
And it is not obvious that this can be `nil`.

**Comment by Wuzzy2** [comment]
I disagree this is a feature request as I did not request a feature.
The feature request (add entity inventories) has been brought up by you. I have posted this as #6081 to keep this documentation bug separate from the feature request.
