### ISSUE TITLE
Entity deactivation callback

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6084]
Right now we have `on_activate` to initialize an entity. There should also be an `on_deactivate` that is called when an entity is unloaded. This is needed in case there are things in Lua-space that need to be removed along with the entity.

Example: A mob can have at most three drones. If one of its drones gets unloaded, it should be able to spawn a new one. A drone could use `on_deactivate` to notify its parent that it is being unloaded. In this example, drones would be transient entities to avoid duplicates.

`get_staticdata` does not suffice for this because it can be called to save data to the map even if the entity is still loaded. I am guessing also that transient entities do not get serialized at all and so do not even call `get_staticdata`

`on_deactivate` should be called in the following cases:
 - The entity is being unloaded (but still exists)
 - The entity is being removed, such as by the `remove` method, due to overpopulation, or because the entity is transient

It would be useful also for `on_deactivate` to get passed an argument that tells whether this is a temporary unloading or if the entity is being removed from the map completely. An example where this would be useful is if a player can have up to five pets anywhere on the map. If a pet is unloaded because no player is nearby, it should still count towards the limit, but if a pet is deleted it should no longer count.

**Comment by azekillDIABLO** [comment]
Would be very useful in some cases **but** it should not be called when entity is being removed because this task should be reserved to a `on_death` function!

**Comment by raymoo** [comment]
I don't care too much if it's a separate callback. There isn't much functional difference between having one callback with a boolean parameters and two callbacks without the parameters. However, having two callbacks may be confusing in the case of transient objects, which are removed when they are unloaded.

**Comment by raymoo** [comment]
Actually it doesn't look like transient entities is a feature, for some reason I thought it was.

**Comment by raymoo** [comment]
Transient entities has been added since I commented that they hadn't: #5112

Also responding to @Ferk in https://github.com/minetest/minetest/issues/3278#issuecomment-361539108:
Currently that is how the engine uses `get_staticdata`, since I know that it at least calls it when the entity is first created, even if it's not being deactivated.

**Comment by paramat** [comment]
1 year bump for core dev opinions.

**Comment by DS-Minetest** [comment]
Related: #6177
