### ISSUE TITLE
Update minetest build on f-droid.org

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6085]
Currently there is Version 0.4.15.16 (16) - Added on Dec 30, 2016, it is outdated.

**Comment by bigfoot547** [comment]
Haven't we dropped android support since sapier left?

**Comment by lisacvuk** [comment]
I don't think so, latest MT is on play store.

**Comment by MuhdNurHidayat** [comment]
> Haven't we dropped android support since sapier left?

Nope, quote below from https://github.com/minetest/minetest/issues/5812#issuecomment-304477814
Paramat:
> I contacted LordFingle and he may be able to help out, so hopefully we can manage to maintain the Android app.
Perhaps this thread can be closed in a while? I don't support dropping Android anymore.

and https://github.com/minetest/minetest/issues/5812#issuecomment-305996549
Nerzhul:
> closing, it will be supported, C++11 needs a little bit support on build, but will be fixed later in the dev cycle

**Comment by nerzhul** [comment]
F-Droid was maintained by @est31 if i remember

**Comment by rubenwardy** [comment]
Minetest Mods for Android is updated automatically on F-Droid whenever I tag a commit. Is it not done the same way for Minetest?

**Comment by nerzhul** [comment]
excellent question i think it's the case, i have an app on F-Droid i don't manage but it is updated automaticly

**Comment by est31** [comment]
@rubenwardy @nerzhul some simple apps are managed that way, but it doesnt work for minetest as it has minetest and minetest_game.

Its a very simple change, look [here](https://gitlab.com/fdroid/fdroiddata/commit/ff98b40635d6a241ab40c1effa1db03392c95ce3) or [here](https://gitlab.com/fdroid/fdroiddata/commit/3ffb45fc79bb49cccacd6032c78c6f0b5d55a3be). The biggest part is setting up a local instance of f-droid to test the patch.

**Comment by mimi89999** [comment]
@nerzhul What NDK version should we use?

I added
```
+Build:0.4.16.17,17
+    commit=0.4.16
+    subdir=build/android
+    output=build/outputs/apk/Minetest-release-unsigned.apk
+    srclibs=MinetestGame@18956c7f69bd7783b657b50201ab6938f3480282
+    prebuild=sed -i -e 's/\.\/gradlew/gradle/g' Makefile && \
+        cp -R $$MinetestGame$$ ../../games/minetest_game
+    build=printf "%s\n%s" "ndk.dir = $$NDK$$" "sdk.dir = $$SDK$$" > local.properties && \
+        make release
+    ndk=r15b
```
But it failed with:
```
jni/../../COBJMeshFileLoader.cpp: In member function 'virtual irr::scene::IAnimatedMesh* irr::scene::COBJMeshFileLoader::createMesh(irr::io::IReadFile*)':
jni/../../COBJMeshFileLoader.cpp:87:6: warning: variable 'smoothingGroup' set but not used [-Wunused-but-set-variable]
  u32 smoothingGroup=0;
      ^
[armeabi-v7a] Compile++ thumb: Irrlicht <= COBJMeshWriter.cpp
[armeabi-v7a] Compile++ thumb: Irrlicht <= COCTLoader.cpp
[armeabi-v7a] Compile++ thumb: Irrlicht <= COctreeSceneNode.cpp
[armeabi-v7a] Compile++ thumb: Irrlicht <= COctreeTriangleSelector.cpp
[armeabi-v7a] Compile++ thumb: Irrlicht <= CEGLManager.cpp
jni/../../CEGLManager.cpp: In member function 'virtual bool irr::video::CEGLManager::generateSurface()':
jni/../../CEGLManager.cpp:245:61: error: 'ANativeWindow_setBuffersGeometry' was not declared in this scope
     ANativeWindow_setBuffersGeometry(EglWindow, 0, 0, Format);
                                                             ^
make[2]: *** [obj/local/armeabi-v7a/objs/Irrlicht/CEGLManager.o] Error 1
make[2]: Leaving directory `/home/michel/git/fdroiddata/build/net.minetest.minetest/build/android/deps/irrlicht/source/Irrlicht/Android'
Makefile:527: recipe for target '/home/michel/git/fdroiddata/build/net.minetest.minetest/build/android/deps/irrlicht/lib/Android/libIrrlicht.a' failed
make[1]: *** [/home/michel/git/fdroiddata/build/net.minetest.minetest/build/android/deps/irrlicht/lib/Android/libIrrlicht.a] Error 1
make[1]: Leaving directory '/home/michel/git/fdroiddata/build/net.minetest.minetest/build/android'
Makefile:164: recipe for target 'release' failed
make: *** [release] Error 2
==== detail end ====
INFO: Finished.
INFO: 1 builds failed
```

**Comment by nerzhul** [comment]
you error is not related to ndk but irrlicht

**Comment by mimi89999** [comment]
What is irrlicht? I know it is not related... I asked 2 questions, but wrote fast and messed a bit in my comment...

**Comment by lisacvuk** [comment]
~~Game~~ Rendering engine used by Minetest

**Comment by mimi89999** [comment]
How have you built *0.4.16.17* for Play Store?

**Comment by nerzhul** [comment]
yes

**Comment by mimi89999** [comment]
Yes to what? I don't quite understand you...

**Comment by MuhdNurHidayat** [comment]
You should ask "How did you build...", your question suggests you're asking "Have you build..." which make nerzhul replied "yes" as it's already built...

**Comment by Fixer-007** [comment]
"We can't build this version: The build for this version appears to have failed. Check the https://f-droid.org/wiki/page/net.minetest.minetest/lastbuild_17"

Apps with failing builds: https://f-droid.org/wiki/page/net.minetest.minetest

**Comment by nerzhul** [comment]
Bug with f-droid net

**Comment by Fixer-007** [comment]
Related https://gitlab.com/fdroid/fdroiddata/merge_requests/2436

@red-001 can you post an issue on their github about failing build (seems like network problem on their side)?

**Comment by Fixer-007** [comment]
F-droid updated their minetest to 0.4.16. Issue fixed.

**Comment by PopeRigby** [comment]
Can you reopen this? It's not updating again. It says it was last updated 3 months ago.

**Comment by ClobberXD** [comment]
As seen on https://f-droid.org/packages/net.minetest.minetest/
> Version 5.0.1.24 (24) - Added on 2019-05-01

That seems correct to me. `5.0.1` is our latest release, which was released on 2019-03-31.

**Comment by PopeRigby** [comment]
Oh. What happened to development?

**Comment by ClobberXD** [comment]
While I have no idea about when the next release is coming up, I'd say that development is actually quite brisk w/ respect to Minetest's standards, when considering factors like shortage of devs, shortage of dev time of devs, etc. :)

**Comment by SmallJoker** [comment]
Poke est31 in case there's an outdated official build.
Source: https://dev.minetest.net/Releasing_Minetest#Build_and_Publish_Android_APK
