### ISSUE TITLE
Keep the option for old sneak code after 0.5

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6090]
I know i suggested removing this at 0.5, but very respected players and server owners want the specific old behaviour and are not happy with new sneak code. There seems to be no apparent need to remove it at 0.5 so perhaps we can keep it for longer, maybe someone will work out how to make new sneak identical while also fixing the bugs (although i rather doubt this).

**Comment by tenplus1** [comment]
Once the fall damage is fixed for the old style sneak behaviour then all is well with the world.

**Comment by paramat** [comment]
Erm that's unlikely but who knows.

**Comment by tenplus1** [comment]
@paramat - Never say never :P

**Comment by Ezhh** [comment]
I've only  checked two other people's servers since 0.4.16, and they had both chosen to use the old code, as I have chosen to use it on my servers as well.  There is clearly a desire to keep this.

**Comment by tenplus1** [comment]
Xanadu will definitely use old-style sneak code once the fall damage issue has been fixed :)

**Comment by Wuzzy2** [comment]
Well, as long it is completely optional and the default (non-weird) sneak behaviour of 0.4.16 stays this way, I am not opposed. I see and understand the need for the “weird sneaking”, even if I don't prefer it personally.

The real question is whether you are able to maintain this without breaking other things, like fall damage.

**Comment by paramat** [comment]
> as long it is completely optional and the default (non-weird) sneak behaviour of 0.4.16 stays this way

This will be the case.

Maintaining this is no problem as it is just a big block of optional code kept completely separate from the new move code. It doesn't break other things, however any bugs the old move code had are preserved within it and are likely unfixable because they are probably an indivisible part of old move behaviour.

**Comment by Cat5TV** [comment]
This is a very unique case where what can be considered an "issue" or even "bug" has become so much a part of the fundamental controls within the game that its removal is akin to changing the way a player plays the game. I cast my vote in favor of this issue (6090) on behalf of [Category5](https://category5.tv) / [The Pixel Shadow](https://minetest.tv) for restoring the old-style sneak.

**Comment by paramat** [comment]
This has been open for a while and no core dev opposes, so closing. I will continue to make sure this option remains for as long as it is wanted by many.
