### ISSUE TITLE
Game crashes when up or down arrow keys are pressed while in pause menu

### ISSUE THREAD

**Issue by garywhite207** [minetest/minetest#6092]
When I open the pause menu and then hit either the up or down arrow keys while in the pause menu, the game stops responding and then crashes in Windows 7 x64, however it appears that others have confirmed that it happens to them on other platforms as well in 0.4.16 (I checked, this is something that only started with 0.4.16, as it does not occur in 0.4.15-release).

**Comment by Ezhh** [comment]
Confirmed this also happens for me on current stable.

**Comment by octacian** [comment]
I can confirm that this happens on 0.4.16-dev with Ubuntu 17.04.

**Comment by nerzhul** [comment]
okay a CSM callback, i push a fix to master

**Comment by nerzhul** [comment]
Fixed

**Comment by SmallJoker** [comment]
Still present in 0.4.17

**Comment by garywhite207** [comment]
I didn't know you could reopen issues, hence why I posted 7420 as a followup

**Comment by SmallJoker** [comment]
Fixed in 0.4.17.1
