### ISSUE TITLE
Android does not support gettext translations

### ISSUE THREAD

**Issue by mnh48** [minetest/minetest#6093]
I'm not sure if this is related to #2030 or not...

Android client would not show translated text even if the language is set in the advanced setting and Android system is running in that language, **but** the mods could all show translations correctly if intllib is enabled and the translated text showned is always based on the language set in advanced setting.

Can't the client uses the detection method in intllib mod, porting the function from mod's Lua to client app's C++ or something?

For example, the default item name is overriden with translated ones from mtg_i18n mod which depends on intllib to detect language being set (Japanese in this case), and other texts in client (eg. tabs) are still in English.
![screenshot_2017-07-03-04-07-32](https://user-images.githubusercontent.com/12217018/27773464-db08cbb0-5fac-11e7-8c08-466290d1e2f3.png)
(That cursor? Yes, I use a mouse (& keyboard, pendrive, printer) on my phone, long live 4-port USB Hub connected via OTG!!!)

**Comment by MoNTE48** [comment]
https://github.com/MultiCraftProject/MultiCraft/pull/31
@rubenwardy @paramat @sfan5 
Two years ago, sfan made localization support in MultiCraft. I would like this support to be in Minetest, too. What do you think?

**Comment by Linuxdirk** [comment]
Update on this issue: Translations do not work with 5.0.0 from releases page. Neither client nor translated mods are translated to the language set via advanced configuration.

Android Pie (build PQ2A.190305.002) on Pixel 3 XL.

**Comment by rubenwardy** [comment]
this is now implemented
