### ISSUE TITLE
Make number of maximum displayed chat messages configurable

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6096]
I propose to add a client setting to set the maximum number of chat messages shown at once.

For now, the number of chat messages displayed at once is hardcoded to 6. For crowded servers with >30 players (like JT2), it quickly becomes impossible to follow the chat because everything scrolls away way too fast.

Using the console is only a partial solution as it stops you from playing.

**Comment by DS-Minetest** [comment]
>Using the console is only a partial solution as it stops you from playing.

Well, if you can squint with one eye to chat and are very multitasking able.

**Comment by SmallJoker** [comment]
Added in #6535
