### ISSUE TITLE
Minetest no longer writes to debug.txt after the file is deleted

### ISSUE THREAD

**Issue by gdelazzari** [minetest/minetest#6098]
When I'm debugging something and I want to clear the debug log (by deleting the file), the game stops logging into that file until I restart the entire game (i.e. closing the single player world and reloading it is not enough).
I don't think this is intended, because the engine should log anyway and re-create the file as soon as it doesn't exist anymore.

**Comment by NathanSalapat** [comment]
To my knowledge this is the way the game has always been.

**Comment by nerzhul** [comment]
it's normal, minetest doesn't close/reopen the FD. Please just empty file: echo "" > debug.txt

You have same "problem" on apache, tomcat and some more services.
