### ISSUE TITLE
Dropped items show wrong normal textures

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#6100]
## Description
Apparently the error only occurs with texture packs that have `_normal` textures. This happens with any dropped items.

## Technical data
- Minetest 0.4.16 (stable)
- Texture pack [Macrotex](https://github.com/BrunoMine/macrotex) for MG
- OS Ubuntu 17-04 64-bit

![bug settings](https://user-images.githubusercontent.com/7986261/27869923-c65bb5b6-6177-11e7-8fbb-b1b2a58b8106.png)
![bug droped item](https://user-images.githubusercontent.com/7986261/27869912-bc4c1840-6177-11e7-927e-358fa7db2e06.png)
![bug apple](https://user-images.githubusercontent.com/7986261/27869917-c0b8aa92-6177-11e7-935d-ac459def3399.png)

**Comment by azekillDIABLO** [comment]
i never seen such a thing... :question:

**Comment by kingoscargames** [comment]
@azekillDIABLO  "i never seen such a thing... ❓" Its not in the latest release i think only in dev

**Comment by BrunoMine** [comment]
@azekillDIABLO Which version does this not occur ? 0.4.16?

**Comment by kingoscargames** [comment]
for me it didnt happen in 0.4.16

**Comment by kingoscargames** [comment]
Wen i stand like 2 blocks away and point at the block this happens: 
<img width="640" alt="screenshot_20170724_172249" src="https://user-images.githubusercontent.com/29333817/28530825-4cd81d92-7095-11e7-9c3d-dc7da1af885c.png">
when i stand close to it and dont point it looks normal 
![screenshot_20170724_172258](https://user-images.githubusercontent.com/29333817/28530870-6e30b6ac-7095-11e7-8f15-fda2f90ba2eb.png)
and somethimes it looks like this: 
![screenshot_20170724_172243](https://user-images.githubusercontent.com/29333817/28530890-793b35ae-7095-11e7-9994-401bcba3302e.png)

**Comment by BrunoMine** [comment]
Exactly, there is some problem with the normal mapping shaders.

**Comment by kingoscargames** [comment]
It changes with the direction i look at it
![screenshot_20170724_173042](https://user-images.githubusercontent.com/29333817/28531104-12b12e00-7096-11e7-8461-b5eafa1cc0aa.png)
![screenshot_20170724_173155](https://user-images.githubusercontent.com/29333817/28531103-12a8b270-7096-11e7-9b04-209fc71a1489.png)
![screenshot_20170724_173206](https://user-images.githubusercontent.com/29333817/28531102-12a7e494-7096-11e7-90b3-78722eebdee2.png)

**Comment by HybridDog** [comment]
![screenshot_20170902_120639](https://user-images.githubusercontent.com/3192173/29997001-60f3982c-9009-11e7-91ff-987a4d7a93cf.png)
