### ISSUE TITLE
Arm inertia Issues

### ISSUE THREAD

**Issue by lisacvuk** [minetest/minetest#6102]
https://youtu.be/U_Tn1yaxFu8

**Comment by lisacvuk** [comment]
Basically, the arm goes all over the screen.

**Comment by lisacvuk** [comment]
```
g++ (GCC) 7.1.1 20170528
Copyright © 2017 Free Software Foundation, Inc.
Ово је слободан софтвер; погледајте изворе за услове копирања. Нема БИЛО КАКВЕ
ГАРАНЦИЈЕ; чак ни за КОМЕРЦИЈАЛНУ ВРЕДНОСТ или ИСПУЊАВАЊЕ ОДРЕЂЕНЕ ПОТРЕБЕ.
```
```
                   -`                 
                  .o+`                 lisac@Pingus-PC
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 4.11.5-1-ARCH
               `+oooooo:               Uptime: 13h 48m
               -+oooooo+:              Packages: 1324
             `/:-:++oooo+:             Shell: bash
            `/++++/+++++++:            Resolution: 1280x1024
           `/++++++++++++++:           DE: GNOME 
          `/+++ooooooooooooo/`         WM: GNOME Shell
         ./ooosssso++osssssso+`        WM Theme: 
        .oossssso-````/ossssss+`       GTK Theme: Adwaita [GTK2/3]
       -osssssso.      :ssssssso.      Icon Theme: Adwaita
      :osssssss/        osssso+++.     Font: Cantarell 11
     /ossssssss/        +ssssooo/-     CPU: AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G @ 4x 3.1GHz [58.5°C]
   `/ossssso+/:-        -:/+osssso+-   GPU: Gallium 0.4 on AMD KAVERI (DRM 3.10.0 / 4.11.5-1-ARCH, LLVM 4.0.0)
  `+sso+:-`                 `.-/+oso:  RAM: 2646MiB / 5919MiB
 `++:.                           `-/+/
 .`                                 `/

```

**Comment by lisacvuk** [comment]
```
Minetest 0.4.16-dev-6bedb6de (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16-dev-6bedb6de BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/local/share/minetest"
```

**Comment by lisacvuk** [comment]
Doesn't happen every time; occurs randomly

**Comment by octacian** [comment]
I can confirm this on Ubuntu 17.04 as well. Except for me, it happens nearly all the time, and not only that but I've also had the hand disappear entirely for a time.

It is pretty sad how little these PRs have been tested before merge... lol
*/me puts it on his list to learn how to test PRs*

**Comment by kilbith** [comment]
Get back to an older commit (`git reset --hard 51104d9cd4`), recompile and tell me if it fixes your issue.

**Comment by paramat** [comment]
octacian, it was tested but didn't occur for the tester. if you want PRs tested more thoroughly then you have to test them yourself.

**Comment by kilbith** [comment]
People, can you please answer these questions: 
1. What's your monitor refresh rate?
2. What's your FPS max limit?

**Comment by lisacvuk** [comment]
1. 60
2. No limit, but doesn't cross 60

**Comment by ElementW** [comment]
a80ecbee1e838491343af760539a37fac4232048 is affected by the bug

**Comment by lisacvuk** [comment]
Seems to be triggered on teleporting

**Comment by azekillDIABLO** [comment]
> a80ecbe is affected by the bug

what do you mean?

**Comment by octacian** [comment]
I can confirm that the issue only seems to happen after teleporting, being via `/teleport` or `/home`.

**Comment by mtango688** [comment]
Seems like it's related to yaw. I can carefully pitch up and down without too much effect, but any amount of yaw will make it flicker, when the effect does come into play.

**Comment by ElementW** [comment]
@azekillDIABLO 
> what do you mean?

The only thing it could mean, you dummy: I confirm the bug happens with Minetest server+client on commit a80ecbee1e838491343af760539a37fac4232048.

**Comment by Fixer-007** [comment]
After teleportation my hand moves weirdly, fps_max = 100, fps in game was around 60, engine 0b3a8deb.
Demo:
![1](https://user-images.githubusercontent.com/16494741/28095239-f302007a-66a9-11e7-8b85-0def6f209a2c.gif)

**Comment by kilbith** [comment]
Unfortunately, I'm not able to reproduce the issue after teleporting.

But disabling the arm inertia by default should be considered.

**Comment by Fixer-007** [comment]
Try reproducing it on actual server, for example Hometown, find a spot, /sethome it, then go into completely different area and do /home.

**Comment by kilbith** [comment]
> Try reproducing it on actual server

Irrelevant, it's a client-side effect entirely. Also singleplayer mode is a server too.

**Comment by Fixer-007** [comment]
Try my config:
```
anisotropic_filter = true
bilinear_filter = false
creative_mode = true
enable_damage = true
enable_waving_leaves = false
enable_waving_plants = true
fast_move = false
free_move = false
leaves_style = fancy
maintab_LAST = online
menu_last_game = minetest
mip_map = true
node_highlighting = box
server_announce = false
server_dedicated = false
trilinear_filter = false
viewing_range = 160
fps_max = 100
mg_name = v7
tone_mapping = false
noclip = false
texture_path = 
sound_volume = 0.6
enable_shaders = false
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
enable_local_map_saving = false
mesh_generation_interval = 5
autosave_screensize = false
enable_client_modding = true
fixed_map_seed = 
minimap_shape_round = false
enable_server = false
show_debug = true
fsaa = 0
port = 30000
```

**Comment by mtango688** [comment]
It doesn't happen if you just teleport. You need to be moving the camera around during teleport.

**Comment by kilbith** [comment]
~~I still fail to reproduce, sorry.~~

EDIT: Got it now.
