### ISSUE TITLE
minetest.registered_aliases is not documented

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6106]
The existance of `minetest.registered_aliases` is not documented in `lua_api.txt`

**Comment by paramat** [comment]
Related #5988

**Comment by DS-Minetest** [comment]
Actually [many registered things](https://github.com/minetest/minetest/blob/151c95bb9bb324ef27df28bbd4f2bce944e35162/builtin/game/register.lua#L555L584) aren't documented.
