### ISSUE TITLE
Make crack an overlay

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6108]
It *is* an overlay, by nature. As @juhdanad made real overlay support, it is possible to split the crack from the main mesh so that the mesh won’t need to be regenerated that often. Also that might simplify solving of various “ugly crack” issues.

**Comment by juhdanad** [comment]
Yes, that would be great. One issue remains: the crack animation has translucent pixels.
As soon as depth sorting will be implemented, the translucent objects in the map blocks will need to be rearranged when a crack animation starts.

Otherwise it is a great idea, I have thought of it too.

**Comment by numberZero** [comment]
@juhdanad The crack will need to be inserted in a correct place in
an already sorted list. There are several ways to do this, but even
appending and bubble-sorting afterwards works in `O(n)` time, and
there are ways working in `O(log n)` (where `n` is the count of
translucent objects).

And one notice: while soft overlays require to use exactly the same
vertices as the base object, which may not be available, there are
things like selection box that don’t need that; that may be a better
way to add crack animation.

**Comment by paramat** [comment]
1+ year bump, any core dev support?
