### ISSUE TITLE
F5  'pointing at' information now runs off-screen (and remove range all, tile info, param1)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6110]
![screenshot_20170708_171342](https://user-images.githubusercontent.com/3686677/27988860-91d273b6-6424-11e7-934f-d3a4d92184e6.png)

^ 1280 720

![screenshot_20170712_030800](https://user-images.githubusercontent.com/3686677/28098653-6ada6312-66af-11e7-9da3-f079b455189d.png)

^ 800 600

Depending on nodename. I suggest everything in 'pointing at' is moved to a new line.

**Comment by DS-Minetest** [comment]
Since a new line would take more space I would suggest something else: The seed takes very much space but you don't need to see it all the time => it should be transferred to the output of the `status` chatcommand.

**Comment by azekillDIABLO** [comment]
@DS-Minetest  Debug is not meant to not take place; but to be useful :-1:

**Comment by octacian** [comment]
Yes, pointing at would be much better on a newline. However, it might look a bit weird seeing as the first and third lines would be longer than the second line, so maybe it should be placed on the second line? This could be a bit interesting to handle though seeing as the information about what you're pointing at doesn't always show (e.g. if you're looking at `air`).

I'd honestly like to see the f5 menu redesigned a little bit so that it only shows the version, position, FPS, and direction looking (but not actual yaw) on the first press of f5. Then show the rest with a second press and require the `debug` privilege. This could be useful because you might not always want the client to be able to do things like check what a block is. It would be more appropriate to inject a CSM for this. Information like range, drawtime, dtime jitter, and items like that (which should still be available) could then maybe be moved somewhere like the profiler.

**Comment by paramat** [comment]
Seed is very useful to have quickly found, so it should stay. It's one of the most important pieces of information in F5.
Another line taking space is no issue, F5 is optional and inevitably covers part of the screen, 1 more line makes little difference.
Yes since 'pointing at' often does not show it should be the 3rd line.

I now think showing param1 is pointless as light information is coded into upper and lower 4 bits, and '238' as in my screenshot shows nothing useful.

**Comment by paramat** [comment]
Actually since i would like to remove param1 i might as well do this task.

**Comment by DS-Minetest** [comment]
>showing param1 is pointless

:+1: 
>Seed is very useful to have quickly found

I don't think so. Seeds are normally very long numbers, transcribing them takes very long. Relative to that, the 7 characters of "/status" are very fast written.
>Debug is not meant to not take place; but to be useful :-1:

But seeing the seed always isn't really useful imo. And a 3rd line might also be a bit ugly.

**Comment by bigfoot547** [comment]
If you guys are worried about a debug screen that takes 3 lines, look at M*******t's debug screen. It takes the whole window! Then you turn on the pie chart.......
Just hold F3+C for 10 seconds then let go...

**Comment by Ezhh** [comment]
Seed being visible from F5 has saved me a lot of bother more than once.

I also usually have F5 active at all times because I like to see my coordinates, and do consider how many lines it uses to be important. With that said, no issues with three lines, but it would be nice if they could remain somewhat balanced in length. Is there really no way to just make the text wrap?

**Comment by paramat** [comment]
Maybe removing param1 will be enough to stop it running off-screen, i'll see.

**Comment by DS-Minetest** [comment]
I just don't understand why it's important to always see the seed, can you read something out of it?

**Comment by paramat** [comment]
People take screenshots of something interesting in a world, to locate it you need to se the co-ordinates and seed in the screenshot, it's very convenient to have this in a screenshot.
In many situations seed is very often needed to be easily and quickly viewable without having to navigate into a world's map_meta.txt.
It's one of the most important pieces of information in F5, there is other information there which is less important.

**Comment by paramat** [comment]
I've added another screenshot for 800x600 which is even worse, the 1st line doesn't fit and 'pointing at' is mostly missing.
There seems to be no need for 'range all = 0/1' as that is notified on-screen already and is obvious from fog.
'drawtime' and 'drawtime jitter' are viewable on the next F5 key press so perhaps are not needed.
And what is RTT? does anyone need it in F5?

**Comment by NathanSalapat** [comment]
The inclusion of param1 does seem mostly useless, it's just the nodes light level, not really sure how that could ever be useful to know.
I can see the texture file name being useful for texture pack creators, but with the node's name they can always look at the mods code to see what texture the node is using.

**Comment by paramat** [comment]
Just found out the tile pointed is not the tile pointed, it only displays the '0' tile for the pointed node, that is, the top tile.

**Comment by rubenwardy** [comment]
No one has 800x600

**Comment by Ezhh** [comment]
Isn't 800x600 the default?

I've often played with it left on the default. (Though I don't care if all the F5 info fits or not).

The sad thing for me has actually always been that you can't have the server turn off this info. It allows everyone to cheat in mazes. :)

**Comment by paramat** [comment]
No one has screen size 800x600 but people do not always play fullscreen for performance reasons. I can't because FPS at desired view range suffers, and it's too big a game window for my fairly large and close display.
Yes 800x600 is the default but we may change that to a more likely minimum of 1024x576 (16:9 widescreen ratio).
We now have a 'debug' priv that controls whether wireframe mode of F5 is shown, this *maybe* could be extended to hide all F5 information or maybe we can consider controlling what can be seen with GUI flags (why isn't wireframe mode controlled by GUI flags?).

**Comment by paramat** [comment]
PR #6125

**Comment by paramat** [comment]
Screen dimensions PR #6126

**Comment by Ezhh** [comment]
debug should not be needed for all F5 information as it's useful to a player in most situations. But it would be nice if there was an option to limit it. (Even though I am the one requesting that option, I would not want it to be default as its use only kicks in for servers where being able to find your way is part of the challenge). I did check previously for gui flags for this and found none. It would be a good thing to have.

**Comment by MisterXtreme** [comment]
I personally think that you should only be able to see the seed if the user has the seed priv (granted by default?), as it makes cheating easier then any CSM, grab that seed, make a world, and noclip in the desired area.

**Comment by paramat** [comment]
#6126  merged.

Debug priv discussion can continue in the relevant issue (by Wuzzy2 i think).
