### ISSUE TITLE
[CSM] Add fuzzy get_used_nodes

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#6111]
Right now, CSM mods can pinpoint the location of nodes rather easily. My suggestion is to instead have a fuzzy get_used_nodes function which returns a table of nodes within a radius/mapblock.

`used_nodes = {"air", "default:dirt", "default:tree"}` in the order of use.

The beauty of this approach is that the larger the area, the less it can be used for cheating, as clients never get the location of the node (outside of C++, which is a problem now anyways).

**Comment by raymoo** [comment]
You could still find the positions in time O(m*log r), where m = number of sought nodes and r = searched radius, by narrowing down the positions with smaller areas. This is better than the time it would take (order of r^3) examining each node individually.

**Comment by raymoo** [comment]
Though if you can only search centered around the player, or at mapblock resolution, it wouldn't be possible to do it.

**Comment by benrob0329** [comment]
While it could tell you whether a rare material is within a rather large area, it would still only see things close by, and to a more fuzzy extent the larger the radius. While it may not be as perfect as raytracing all visible blocks, it is certainly a heck of a lot better than current behavior.

**Comment by raymoo** [comment]
Yes, I guess it would still make it harder / take longer to find the nodes.

I think used_nodes though should contain the counts of nodes to be useful. For example, an ambience mod should only trigger ocean sounds if there is lots of water nearby.

**Comment by paramat** [comment]
The node getters are still needed, and will be restricted soon, so are no problem, this could be an addition.

**Comment by raymoo** [comment]
@paramat I thought @benrob0329 was implying that searches would be centered on the player, which would mean you couldn't subdivide without moving the player around. I don't see a problem of having this as a separate restrictable thing along with more precise node-getting, because the server could allow this but not the more precise one, allowing some potential for cheating but not the whole deal.

My overall position is still that the API for client-provided clientmods should not include anything (restrictable or otherwise) that could be used for cheating, though.

**Comment by benrob0329** [comment]
@paramat No, this does not allow subdividing.

The whole point of this is to not need range restriction. Detecting something rare in a larger radius is less useful than a small one. (The range is not set by the client, unless calculations are done client side, in which case it would be set in C++) However even a small range is not all that useful, as the player would have to literally be standing close to the rare node, and still has to find the exact position of it. **But** as I said, this would require an engine change to do so, and the only way to fix that is to have the server do the calculation.

I am assuming that by restricted by the server, you mean turned off entirely, which __**does not**__ solve the base issue.

**Comment by raymoo** [comment]
You could use the small-range search to detect nearby traps

**Comment by benrob0329** [comment]
You could, but only if the range was small. If the range was large, its not all that useful. (Or perhaps the range is set by the server, and could be used for a tool rich does that)

**Comment by paramat** [comment]
Ok, i did read the comments and none stated this was centred on the player, "it would still only see things close by" does not necessarily mean centred on the player.
I did not imply this had a subdividing feature, just that it could be used repeatedly in that way.

> returns a table of nodes within a radius/mapblock.

You did not state the radius is set by the server, a 'radius' implies one set by the clientmod.

> However even a small range is not all that useful, as the player would have to literally be standing close to the rare node, and still has to find the exact position of it.

Still a cheat though, you know when something is nearby, and just have to dig around to find it.

> I am assuming that by restricted by the server, you mean turned off entirely, which does not solve the base issue.

Yes it obviously does, if a node getter is disabled cheating is avoided, and it is the only certain way of avoiding cheating.

**Comment by benrob0329** [comment]
Disabling walking also prevents cheating, and disabling digging does as well.

If having a small radius allows cheating, then don't have a small radius. This is a much better alternative to node getters that still provides context awareness whilst limiting the ability to use it for cheating a heck of a lot more than other things that made it into CSM.

I guarantee you that most servers will disable node getters, and why shouldn't they? Its a given that they can be used for cheating. This would at least allow ambiance mods and the like to have something, and give server owners a chance at not completely disabling CSM.

**Comment by sfan5** [comment]
:-1:
Does not help a lot against cheating and extreme reduces usefulness of CSM.

**Comment by benrob0329** [comment]
How does this not help against cheating? The very concept of the idea is that a larger range reduces the usefulness for cheaters.

And yes, this is useful for mods which need some context about the area surrounding the player (such as ambiance mods). If you would like to use node getters, we shall see how many are still enabled on servers.

**Comment by paramat** [comment]
> If having a small radius allows cheating, then don't have a small radius.

My point is all radii allow cheating, a radius large enough to be useless for cheating would also be useless for genuine uses.

> I guarantee you that most servers will disable node getters,

Yes, which is why it seems pointless adding soft limits such as radius linits for node getters, any radius allows cheating.
Ambience mods will use 'get heat / humidity / biome at pos' which i will add before 0.5.
I'm unconvinced this is useful as an addition to CSM, and i oppose replacing node getters with this, as they are essential for other uses, for example in server-provided CSM mods.
:-1:

**Comment by benrob0329** [comment]
>Yes, which is why it seems pointless adding soft limits such as radius / line of sight limits for node getters. Any soft limit allows cheating

This is not just a soft limit, this is a whole 'nother way of looking at the problem which removes the main problem with node getters (The ability to pinpoint rare node locations)

>Ambience mods will use 'get heat / humidity / biome at pos' which i will add before 0.5.

No, no, and no. These are good for some context about the area, but a shop should certainly not have jungle music unless it was built with jungle wood, and a factory should not have Sahara music.

**Comment by paramat** [comment]
Yes, by ambience mod i mean a biome-dependent one.

**Comment by benrob0329** [comment]
By ambiance mod, I mean an every dependant one. Music needs to be done right, and having the same music throughout the whole biom with no context awareness simply isn't right.

In fact, one of the reasons I suggested using maplocks was because buildings could be built on one, to force the music to update when someone enters a shop. To rob the game of further context awareness would be wrong.

Maybe this doesn't replace node getters, but its better than not having anything at all on most servers.

**Comment by paramat** [comment]
Best to edit the title then, were not going to replace 'get node' obviously.
Any server concerned about 'get node' will very likely not allow 'fuzzy get node' because it is still a cheat as i explained.
Other than those points, maybe it is useful, but i'm unsure, and has no dev support.

**Comment by paramat** [comment]
Disapprovals and no support.
