### ISSUE TITLE
Inside-cloud effect is too pronounced

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6115]
After #6003 it seems that the cloud effect is too pronounced. I can be above a cloud, look through it and still see some of the ground, yet, when I'm inside the cloud the visibility is far more reduced.

Looking at the code I see:
```
sky->setBodiesVisible(false);
runData.fog_range = 20.0f * BS;
// do not draw clouds after all
clouds->setVisible(false);
```

I'd suggest changing the hardcoded
`runData.fog_range = 20.0f * BS;`
to
`runData.fog_range /= 2.0f;`

That gives a more realistic effect and takes the current for range into account.
If folks agree I'll send a trivial PR.

**Comment by azekillDIABLO** [comment]
***testing cloud effect***
when i am inside a cloud it disapears totally :grey_question:

**Comment by octacian** [comment]
@azekillDIABLO then you need to update your version of Minetest.

**Comment by paramat** [comment]
I don't think we should worry about comparing the fixed opacity of a cloud with the fog effect inside it, let's just choose a good constant in-cloud fog strength.

**Comment by lhofhansl** [comment]
It's just weird right now. One can be above the cloud and look down through the entire cloud and still see the ground. Then when inside the cloud the view range is suddenly limited to 20, the ground is no longer visible.

Certainly feels very unnatural :)

I think it should be related to the view range, after all the view range essentially defines a certain fog density. Then when inside a cloud the fog is more dense. Relating the two is simple and makes sense to me.

**Comment by paramat** [comment]
Yeah, it is inconsistent, but better than making the in-cloud fog disappointingly weak.

View range affecting fog distance outside a cloud is done for a reason and has nothing to do with being inside a cloud. The clouds do not look less opaque from outside as you increase your view range, their opaqueness is constant so the in-cloud fog should be too.

**Comment by lhofhansl** [comment]
Oh, and yes, as the view range is changed clouds do vary their apparent density, as the external fog effect is added to the clouds filtering.

In any case, this is not worth a long discussion. IMHO this is better, but that's just my opinion.

**Comment by lhofhansl** [comment]
Let's just close this.

**Comment by paramat** [comment]
Ok. But what i mean is that the clouds are considered to have a constant 'density' that does not change as a player changes their view distance.
it just seems that if a player has a view range 256 then in a cloud they experience view range 128 fog which is nowhere near dense enough for an in-cloud effect.

No need to close, i agree we can increase the in-cloud fog distance, to say 32, or make it configurable in the cloud API.

**Comment by lhofhansl** [comment]
Thanks @paramat , I left the PR open.

**Comment by paramat** [comment]
#6116 merged.
