### ISSUE TITLE
Allow mods to change sun and moon textures

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#6128]
Currently, the moon and sun texture can only be changed by texture packs or subgames. Also, the game must be restarted to use new textures. There could be something such as `player:set_moon_texture` and `player:set_sun_texture` to set the moon or sun texture to whatever is defined. This would allow things such as moon phases, where the mod could switch out different textures at certain times. I would attempt something myself, but I do not know C++ (yet).
Thoughts?

**Comment by dsohler** [comment]
> Thoughts?

Wasn't it that you could simply create a mod and just having the textures in a `textures` sub-folder of the mod's folder?

But yes, the options you suggested would be nice and would perfectly complement the configurable skybox and clouds.

**Comment by octacian** [comment]
> Wasn't it that you could simply create a mod and just having the textures in a textures sub-folder of the mod's folder?

Yes, you can, however, there is no way to change the texture without a game restart.

**Comment by paramat** [comment]
We have in-game per-player 'set sky' and 'set clouds' so in-game changing of sun.moon textures might be useful, for example when teleporting to another realm.
However it may be best to do this in an expanded 'set sky' so that sun, moon and stars are independently switchable and customisable, quite a big job.

**Comment by Wuzzy2** [comment]
Yes. Let the blood moon rise! xD

**Comment by paramat** [comment]
Related #6732 #1997

**Comment by paramat** [comment]
PR #7691

**Comment by LoneWolfHT** [comment]
Can't this be closed now?
