### ISSUE TITLE
Entity footstep sound distance

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#6131]
Could someone add a distance parameter for entity footstep sounds, currently they can be heard from 32 nodes away and for some of the more light-footed mobs this can be disasterous :)

**Comment by DS-Minetest** [comment]
What about using instead of the `makes_footstep_sound = <bool>` field something like `footstep_sound = <sound parameter table> or false to disable`?

**Comment by tenplus1** [comment]
That could work, yeah...  or even supplying false for off and a value for distance :)

**Comment by DS-Minetest** [comment]
But we don't only want distance, also eg. pitch, because of consistency, right?

**Comment by Wuzzy2** [comment]
If I am not mistaken, the sound also has 100% volume for the entire hear distance which is very bad. 
A mob which is 31 nodes away is as loud as a mob which is only 1 node away. And a mob which is 33 nodes away is silent.
This is one of the more annoying bugs in MineClone 2. Interesting to learn that this might be a Minetest bug. :D

But I might be hallicunating this, so correct me if I'm wrong.

**Comment by tenplus1** [comment]
@Wuzzy2 - it seems that the entity sound does fade a little with distance.

**Comment by nerzhul** [comment]
the sound distance volume is not decreased by distance yes, it should be adapted if possible

**Comment by paramat** [comment]
So this is why player footstep sounds are so irritating on servers.

**Comment by paramat** [comment]
Duplicate of #4361 please continue discussion there.
