### ISSUE TITLE
Distributed file system and computing

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#6132]
Distributed File System+Distributed Computing

**Comment by raymoo** [comment]
What specifically do you want to be possible in Minetest?

**Comment by alugarius** [comment]
I like that

**Comment by paramat** [comment]
Please use a translation program to add more information to your issues and PRs, thanks.

**Comment by paramat** [comment]
Maybe something to do with 'Distributed Server'? Forum thread https://forum.minetest.net/viewtopic.php?f=10&t=18091

**Comment by alugarius** [comment]
@paramat
Thanks, this helps

**Comment by nerzhul** [comment]
minetest is not a distributed program and cannot be that

**Comment by nerzhul** [comment]
if you want distributed filesystem use ceph, it's not mt role.
