### ISSUE TITLE
Emerging seems slower. Lots of CPU spent in getSmoothLighting.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6137]
Unfortunately I will likely not have much time to track this down.

I observed that in recent MT builds the emerging seems much slower. In the profiler a lot of time is spent now in `getSmoothLight`. I do not recall ever seeing this is earlier profiler sessions.

git history `mapblock_mesh.cpp` show quite a bunch of recent changes.

**Comment by paramat** [comment]
Do you mean the rate that terrain appears as you travel? That has slowed, maybe due to celeron55's changes that made FPS smoother?

**Comment by lhofhansl** [comment]
I don't think this is caused by the caching that c55 added.
If I get time I'll look into smooth lighting for plantlike (in fact that stuck out when I looked briefly through some recent changes)

**Comment by nerzhul** [comment]
i notice same thing, maybe i will profile to improve this performance issue

**Comment by lhofhansl** [comment]
Caused by  #5748. When I revert that, the performance is back to normal.

**Comment by lhofhansl** [comment]
@numberZero FYI.

**Comment by lhofhansl** [comment]
Specifically this hunk: https://github.com/minetest/minetest/pull/5748/files#diff-c03ca828c6b8a7695f2cd7e52c316a3cL1299

**Comment by numberZero** [comment]
oh well, sorry for that... will fix very soon

**Comment by paramat** [comment]
Thanks for finding this, i have recently thought terrain was slow to appear when flying.

**Comment by paramat** [comment]
#5748 merged.
