### ISSUE TITLE
Whole wieldhand gone after respawning

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#6140]
Happened on 0.4.16-dev server (compiled June 4) with newest daily PPA client.

Hand is completely gone and there seems to be no way to get it back (except re-connecting I guess)

Screenshot: http://i.imgur.com/BtGH6On.png

**Comment by Fixer-007** [comment]
Maybe your PPA one is 1 day old and does not contain latest hand fix yet, try next daily ppa.

**Comment by kilbith** [comment]
Don't open any issue if you're not against HEAD.

**EDIT:** Just checked, the latest PPA build has been [compiled](https://launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds/+packages) against 84aa845, i.e. one commit before the wieldmesh fix. Next time provide a commit hash or GTFO.

**Comment by paramat** [comment]
Comment here if not fixed after fixing commit.
