### ISSUE TITLE
3rd line of F5 debug overlaps with 1st line of chat

### ISSUE THREAD

**Issue by Xanthin** [minetest/minetest#6141]
Since d4cc49e9a72cb5cce7dce80ccc0196aedd106acd.

![chatf5overlap](https://user-images.githubusercontent.com/6878547/28251127-0fe55004-6a77-11e7-9b35-1e042477fa93.png)

**Comment by paramat** [comment]
Sorry, will fix today.

**Comment by paramat** [comment]
PR #6145
