### ISSUE TITLE
Review and port code from Freeminer

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6144]
Copy-paste from https://forum.minetest.net/viewtopic.php?p=283862#p283862
////////////

=== END of story.
me (proller) and xyz allow to use all our commits to freeminer in minetest.
freeminer still have lot of improvements: https://github.com/freeminer/freeminer/blob/master/CHANGELOG.md
Some changes too big and too hard to port (like threading system).
Some can be used as base for future (like enet+messagepack protocol, dev sctp via udp protocol, ...)
Some can be easily ported (like falling movement fixes, sun position, farmesh, ...)

easy way too see all changes from minetest in diff:
1. clone freeminer , cd freeminer

    git remote add minetest        https://github.com/minetest/minetest.git
    git fetch --all
    git diff abd68d346

725 files changed, 52986 insertions(+), 14400 deletions(-)

Other things that deserve attention (except weather-liquid system):
Optimized ABM (split analyze-trigger process).
Optimized block send to client/client render queues and process (fast(100+nodes per second) fly without stuck), possible to load big areas around (500+nodes).
Light update queue.
Map save process (no sector), possible to save only changed blocks => 10x less disk space.
Headless bot optimize (tested with 300 bots running on one computer (up to 600 bots on one server (yes, it still playable))).
LAN serverlist (automatically show started servers via broadcast).
Windows automatic build system (install msvs and run one script)

EDIT: Fix broken changelog link

**Comment by Wuzzy2** [comment]
Also:
* Better main menu design
* `enet`
