### ISSUE TITLE
Colour and/or Alpha Issues

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#6151]
Since switching over to current stable (0.4.16), I notice nodes from several mods no longer display as they used to. The nodes all seem to use alpha. (Please note, my screenshots are from stable, but testing confirms this holds true for current dev as well).

Coloured glass (abriglass mod) looks washed out/faded:
Pre-0.4.16:
![glass_old](https://user-images.githubusercontent.com/7035183/28333021-988d87b4-6bee-11e7-8939-7794f6217b02.png)
Post-0.4.16:
![glass_new](https://user-images.githubusercontent.com/7035183/28333034-a2ebb640-6bee-11e7-8734-26f1cf44cd63.png)

A liquid (sumpf mod) seems to have no texture left:
Pre-0.4.16:
![water_old](https://user-images.githubusercontent.com/7035183/28333089-ce383472-6bee-11e7-90e9-45965d44a449.png)
Post-0.4.16:
![water_new](https://user-images.githubusercontent.com/7035183/28333095-d408ca06-6bee-11e7-9b72-b79c984761b5.png)

And finally, one that may be a separate issue entirely, since after testing it seems to have been this way since 0.4.15, underwater plants (noairblocks mod from sea modpack) that used to be visible are now reduced to an eyesore:
Pre-0.4.15:
![sea_old](https://user-images.githubusercontent.com/7035183/28333236-35c038d8-6bef-11e7-8255-c602c2a3a402.png)
Post-0.4.15:
![sea_new](https://user-images.githubusercontent.com/7035183/28333249-3d929fb0-6bef-11e7-93a8-862b2777e14b.png)

I've had some players comment, and really don't like the differences myself, so would appreciate if anyone can work out what happened.

**Comment by bigfoot547** [comment]
I've noticed this issue too.
Do you have screenshots w/o shaders (even though it really doesn't really matter)?

**Comment by paramat** [comment]
It would be useful to know the 'use texture alpha = true/false' and 'alpha = xxx' nodedefs, if they exist, for the first 2 issues, although 'alpha = xxx' may only be used for liquid nodes.
@juhdanad @numberZero

**Comment by Ezhh** [comment]
@bigfoot547 Here's some with no shaders, there actually is a difference, mostly for the liquid.

Pre-0.4.16:
![ns_glass_old](https://user-images.githubusercontent.com/7035183/28334124-0c945536-6bf2-11e7-8f3f-bdfcc2a16f38.png)
Post-0.4.16 (looks even worse):
![ns_glass_new](https://user-images.githubusercontent.com/7035183/28334133-182c92c8-6bf2-11e7-9cac-2cc543b6fbe2.png)

Pre-0.4.16:
![ns_water_old](https://user-images.githubusercontent.com/7035183/28334146-21397d4a-6bf2-11e7-95ae-fdae65661066.png)
Post-0.4.16 (texture is now visible, though still weaker than pre-0.4.16):
![ns_water_new](https://user-images.githubusercontent.com/7035183/28334152-266d70d2-6bf2-11e7-8fe8-3f11ac30651f.png)

**Comment by paramat** [comment]
By pre-0.4.16 do you mean 0.4.15 stable or some time during 0.4.15 dev?

**Comment by Ezhh** [comment]
Tested with 0.4.15 stable client, so these issues could have appeared any time after that.

**Comment by paramat** [comment]
Here's the noairblocks mod from the sea modpack, not viewable at Github so copied here:
////////////////
```
-- NODES

minetest.register_node("noairblocks:water_flowingx", {
	description = "Flowing Waterx",
	inventory_image = minetest.inventorycube("default_water.png"),
	drawtype = "flowingliquid",
	tiles = {"default_water.png"},
	special_tiles = {
		{
			image="default_water_flowing_animated.png",
			backface_culling=false,
			animation={type="vertical_frames", aspect_w=16, aspect_h=16, length=0.8}
		},
		{
			image="default_water_flowing_animated.png",
			backface_culling=true,
			animation={type="vertical_frames", aspect_w=16, aspect_h=16, length=0.8}
		},
	},
	alpha = 0,
	paramtype = "light",
	paramtype2 = "flowingliquid",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	drop = "",
	drowning = 1,
	liquidtype = "flowing",
	liquid_alternative_flowing = "noairblocks:water_flowingx",
	liquid_alternative_source = "noairblocks:water_sourcex",
	liquid_viscosity = WATER_VISC,
	freezemelt = "default:snow",
	post_effect_color = {a=64, r=100, g=100, b=200},
	groups = {water=3, liquid=3, puts_out_fire=1, not_in_creative_inventory=1, freezes=1, melt_around=1},
})

minetest.register_node("noairblocks:water_sourcex", {
	description = "Water Sourcex",
	inventory_image = minetest.inventorycube("default_water.png"),
	drawtype = "liquid",
	tiles = {
		{name="default_water_source_animated.png", animation={type="vertical_frames", aspect_w=16, aspect_h=16, length=2.0}}
	},
	special_tiles = {
		-- New-style water source material (mostly unused)
		{
			name="default_water_source_animated.png",
			animation={type="vertical_frames", aspect_w=16, aspect_h=16, length=2.0},
			backface_culling = false,
		}
	},
	alpha = 0,
	paramtype = "light",
	walkable = false,
	pointable = false,
	diggable = false,
	buildable_to = true,
	drop = "",
	drowning = 1,
	liquidtype = "source",
	liquid_alternative_flowing = "noairblocks:water_flowingx",
	liquid_alternative_source = "noairblocks:water_sourcex",
	liquid_viscosity = WATER_VISC,
	freezemelt = "default:ice",
	post_effect_color = {a=64, r=100, g=100, b=200},
	groups = {water=3, liquid=3, puts_out_fire=1, freezes=1},
})


-- ABM'S


-- 6 x default to noairblocks


minetest.register_abm({
nodenames = {"group:sea"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
	local xn = {x = pos.x - 1, y = pos.y, z = pos.z}
	local yp= {x = pos.x, y = pos.y + 1, z = pos.z}
	local xnyp= {x = pos.x - 1, y = pos.y + 1, z = pos.z}
	if minetest.get_node(xn).name == "default:water_source" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(xnyp).name ~= "air" then 
				minetest.add_node(xn, {name = "noairblocks:water_sourcex"}) else
	if minetest.get_node(xn).name == "default:water_flowing" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(xnyp).name ~= "air" then 
				minetest.add_node(xn, {name = "noairblocks:water_flowingx"}) else
			return
		end
	end
end,
})

minetest.register_abm({
nodenames = {"group:sea"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
	local xp = {x = pos.x + 1, y = pos.y, z = pos.z}
	local yp= {x = pos.x, y = pos.y + 1, z = pos.z}
	local xpyp= {x = pos.x + 1, y = pos.y + 1, z = pos.z}
	if minetest.get_node(xp).name == "default:water_source" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(xpyp).name ~= "air" then 
				minetest.add_node(xp, {name = "noairblocks:water_sourcex"}) else
	if minetest.get_node(xp).name == "default:water_flowing" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(xpyp).name ~= "air" then  
				minetest.add_node(xp, {name = "noairblocks:water_flowingx"}) else
			return
		end
	end
end,
})

minetest.register_abm({
nodenames = {"group:sea"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
	local zn = {x = pos.x, y = pos.y, z = pos.z - 1}
	local yp= {x = pos.x, y = pos.y + 1, z = pos.z}
	local znyp= {x = pos.x, y = pos.y + 1, z = pos.z - 1}
	if minetest.get_node(zn).name == "default:water_source" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(znyp).name ~= "air" then 
				minetest.add_node(zn, {name = "noairblocks:water_sourcex"}) else
	if minetest.get_node(zn).name == "default:water_flowing" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(znyp).name ~= "air" then 
				minetest.add_node(zn, {name = "noairblocks:water_flowingx"}) else
			return
		end
	end
end,
})

minetest.register_abm({
nodenames = {"group:sea"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
	local zp = {x = pos.x, y = pos.y, z = pos.z + 1}
	local yp= {x = pos.x, y = pos.y + 1, z = pos.z}
	local zpyp= {x = pos.x, y = pos.y + 1, z = pos.z + 1}
	if minetest.get_node(zp).name == "default:water_source" and
			minetest.get_node(yp).name ~= "air" and
 			minetest.get_node(zpyp).name ~= "air" then 
				minetest.add_node(zp, {name = "noairblocks:water_sourcex"}) else
	if minetest.get_node(zp).name == "default:water_flowing" and
			minetest.get_node(yp).name ~= "air" and
			minetest.get_node(zpyp).name ~= "air" then  
				minetest.add_node(zp, {name = "noairblocks:water_flowingx"}) else
			return
		end
	end
end,
})

minetest.register_abm({
nodenames = {"group:sea"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
	local yp= {x = pos.x, y = pos.y + 1, z = pos.z}
	if minetest.get_node(yp).name == "default:water_source" then 
			minetest.add_node(yp, {name = "noairblocks:water_sourcex"}) else
	if minetest.get_node(yp).name == "default:water_flowing" then
			minetest.add_node(yp, {name = "noairblocks:water_flowingx"}) else
			return
		end
	end
end,
})

minetest.register_abm({
nodenames = {"group:sea"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
	local yn = {x = pos.x, y = pos.y - 1, z = pos.z}
	local yp= {x = pos.x, y = pos.y + 1, z = pos.z}
	if minetest.get_node(yn).name == "default:water_source" and
			minetest.get_node(yp).name ~= "air" then 
			minetest.add_node(yn, {name = "noairblocks:water_sourcex"}) else
	if minetest.get_node(yn).name == "default:water_flowing" and
			minetest.get_node(yp).name ~= "air" then 
			minetest.add_node(yn, {name = "noairblocks:water_flowingx"}) else
			return
		end
	end
end,
})


-- Undoing x


minetest.register_abm({
nodenames = {"noairblocks:water_sourcex"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
local pos0 = {x=pos.x-1,y=pos.y-1,z=pos.z-1}
local pos1 = {x=pos.x+1,y=pos.y+1,z=pos.z+1}
	if #minetest.find_nodes_in_area(pos0, pos1, "group:sea") < 1 then
	minetest.add_node(pos, {name = "default:water_source"}) else
	return
	end
end,
})

minetest.register_abm({
nodenames = {"noairblocks:water_flowingx"},
interval = 1,
chance = 1,
action = function(pos, node, active_object_count, active_object_count_wider)
local pos0 = {x=pos.x-1,y=pos.y-1,z=pos.z-1}
local pos1 = {x=pos.x+1,y=pos.y+1,z=pos.z+1}
	if #minetest.find_nodes_in_area(pos0, pos1, "group:sea") < 1 then
	minetest.add_node(pos, {name = "default:water_flowing"}) else
	return
	end
end,
})
```

**Comment by paramat** [comment]
Sumpf 'dirtywater' i assume https://github.com/HybridDog/sumpf/blob/master/sumpf/init.lua

**Comment by Ezhh** [comment]
@paramat Yes, that's the one.

**Comment by paramat** [comment]
First report of a problem with air bubbles visible https://forum.minetest.net/viewtopic.php?p=163002#p163002
Do you have 'opaque water' setting enabled? However that didn't affect the reported bug in the thread.

**Comment by paramat** [comment]
More recent bug https://forum.minetest.net/viewtopic.php?p=279692#p279692

**Comment by Ezhh** [comment]
Those issues with noairbocks are different from mine, as I cannot see the plants at all when I view from underwater. From above water it's mostly the same when I look down, and I still see solid columns of water, but some parts flicker wildly instead. Opaque water was **disabled** for the screenshots I took and the issue is present every time. No change if I enable it (though obviously nothing is then visible from above water).

As you mentioned light, I will note that my version of the sea modpack is, though largely the same, a fork which adds light to the plants. I have no idea if this could change things.

**Comment by stujones11** [comment]
I am wondering if this has anything to do with #5943, although that should only affect non-alpha nodes, it might be worth checking.

**Comment by paramat** [comment]
I doubt it, as the whole node would be opaque, not just the face next to the plant. But who knows, maybe.

I feel this issue with noairblocks is low priority due to the method's hackiness and long-term bugginess, but would of course be nice to fix if possible, and might be an indicator of another problem.
We now have a new drawtype that does underwater plants properly.

**Comment by Fixer-007** [comment]
Don't have any problems with that on 0.4.16-5117ce4c

https://user-images.githubusercontent.com/7035183/28333236-35c038d8-6bef-11e7-8255-c602c2a3a402.png

**Comment by Ezhh** [comment]
@Fixer-007 Yes, darker is favoured in this case (though they are not 'very' dark to me, especially since they are a light source). Regardless, I am mostly concerned that there is such a big change between versions and would like a way to fix it.

**Comment by Fixer-007** [comment]
I will bisect coloured glass change. Narrowed it down pretty much. Don't have sea problems though.

**Comment by Ezhh** [comment]
Update: Thanks to Fixer for some help digging into this - I can now confirm the opaque airbubbles around the plants are not due to any issue in the sea modpack, but are specifically due to the water texture used (which previously did not cause this issue). So we're now reduced to glass and two different liquid textures having issues.

**Comment by Fixer-007** [comment]
About coloured glass appearance, change is caused by: https://github.com/minetest/minetest/commit/33e0eedbfb116111fa79cbc506d9e94ffbb1543b "Add smooth lighting for all nodes"

**Comment by numberZero** [comment]
As for me, the current glass appearance seems to be proper. Nevertheless, I will investigate this, at least to make sure appearance is more or less consistent regarding various settings. But, in my opinion, @Ezhh should update textures if he wants to keep darker look, as the current texture is of full brightness.

**Comment by paramat** [comment]
Fixing noairnodes (sea modpack) mod is very low priority, as it uses a hacky method with a history of bugs, however if this issue highlights something of importance that will be useful.

For coloured glass, that uses semi-translucency which is not supported in MT for normal nodes, so we're not officially obliged to fix problems with that, although of course it would be appreciated by some if it was fixed, and the issue may be useful in highlighting something else.

**Comment by numberZero** [comment]
@paramat these glass nodes are `glasslike`, not `normal`

**Comment by paramat** [comment]
Yes, i mean 'normal' non-technically. It seems only liquids support semi-translucency because they are a different 'material'.

**Comment by Ezhh** [comment]
@numberZero Can you explain why you say the current glass appearance is proper? The previous appearance was desirable, the current is not, and the appearance has changed with no change to the mod. I am not sure in what way I can update the textures to change this. If can advise how, I will look into it.

Note that an additional node/mod has been found with the same issue as the sumpf water - homedecor plasma lamps no longer display correctly and the texture is now absent. These also worked correctly pre-0.4.15. (I haven't yet tested if the current version of the mod has found a way to correct this, as I use my own fork).

**Comment by paramat** [comment]
I think the plasma lamps use alpha and are semi-translucent.

**Comment by numberZero** [comment]
@paramat liquids are just as weird as all other translucent nodes. That may be less noticeable because liquids rarely have air gaps. But when they do...
![screenshot_20170721_214858](https://user-images.githubusercontent.com/7352626/28477910-db03c988-6e5e-11e7-804d-769eb9105600.png)
![screenshot_20170721_214905](https://user-images.githubusercontent.com/7352626/28477909-db02e1d0-6e5e-11e7-8d7e-7c4fc77ca1fd.png)
![screenshot_20170721_214911](https://user-images.githubusercontent.com/7352626/28477908-db010ffe-6e5e-11e7-8f36-3e6c75702a99.png)

@Ezhh the previous appearance was a bug IMO. Such bright texture at full light level on a light source just can’t be that dark as it was (and is, when smooth lighting is disabled). Try using gray texture instead of white one, that should help (but please keep these bright nodes as well, maybe under different names; they are nice).

**Comment by paramat** [comment]
I'm not sure it was a bug, see the textures abriglass_lightxxx.png here https://github.com/Ezhh/abriglass/tree/master/textures they seem quite dark.

**Comment by Ezhh** [comment]
I don't really want to add grey to the texture. Not all players use smooth lighting, so giving that as a solution means those players are going to be left with the glass much too dark.

Can you let me know what you mean by full light level? The light is only level 4, which is generally just a faint glow. I could even lower it a little more if needed.

**Comment by numberZero** [comment]
@paramat I checked the texture, it is (255, 255, 255, 128)
@Ezhh “Full light level” — the sunlight.

But I feel I see the problem:
![screenshot_20170721_230822](https://user-images.githubusercontent.com/7352626/28480564-ea1a899c-6e69-11e7-98d1-b29bc3d51f57.png)
That spot below glass seems to be far too bright. Perhaps light level is decoded twice somewhere...

**Comment by numberZero** [comment]
@Ezhh er, any transparent node should have `paramtype = "light"` in its definition.
![screenshot_20170721_232324](https://user-images.githubusercontent.com/7352626/28481006-cdcfcffc-6e6b-11e7-98fb-d35818130d30.png)

**Comment by Ezhh** [comment]
Hmm, interesting that that is missing; I thought I added it, but adding it does nothing to restore the desired look by itself.  I'll need to experiment more, and see if I can find a good way to get the colours darker again.

For the sumpf water, it seems the game can no longer handle textures of such low contrast. Increasing contrast makes it visible again, though that means getting a liquid with a subtle murky look to it is now a lot more difficult.

**Comment by paramat** [comment]
Sorry for my 'not obliged to fix' comment, writing nonsense again, this issue may be not particularly related to semi-translucency.

**Comment by paramat** [comment]
Since non-colourised glass in the mod is not affected the same way, perhaps try using individual textures for the different colours of plainglass?

**Comment by Ezhh** [comment]
I thought about that, but you can see the frosted (white) glass is affected, and that doesn't use colourise.

Also, this can't be only due to the smooth lighting. If you disable smooth lighting and look at where the glass meets the ground, it gets darker there (see NumberZero's screenshots), whereas if you look at my original pre-0.4.16 screenshot, you'll see that area does not darken. The behaviour change really is quite large.

**Comment by Ezhh** [comment]
(Also, you are a volunteer, as are all the devs/contributors, so not actually 'obliged' to fix anything! We are just grateful when you do!)

**Comment by paramat** [comment]
Since plainglass.png is (255, 255, 255, 128) then it appearing bright seems correct, so maybe the previous behaviour was indeed wrong.

**Comment by paramat** [comment]
@Ezhh to recolour your glass, maybe take a screenshot in an old client of the glass in front of a white background, then open the screenshot in an image editor and use a 'colour picker' tool to find the RGB values for the glass, this might get you close.

**Comment by numberZero** [comment]
@Ezhh Use `paramtype = "light"` with darker texture. Should work well with both current and older versions, both with smooth and flat lighting.
BTW, I may have unusual lighting settings (or even patches), so my screenshots may differ a bit from yours.

**Comment by paramat** [comment]
Yes `paramtype = "light"` is essential for any light source.

**Comment by numberZero** [comment]
6bedb6de4 (master)
No shaders
![screenshot_20170725_000639](https://user-images.githubusercontent.com/7352626/28544860-6db33a0a-70cd-11e7-98b3-c6cf1675f41e.png)
Shaders, waving water
![screenshot_20170725_000659](https://user-images.githubusercontent.com/7352626/28544861-6db550d8-70cd-11e7-9c31-59e3d1f9db89.png)
Shaders, waving water, tone mapping
![screenshot_20170725_000715](https://user-images.githubusercontent.com/7352626/28544859-6dacd61a-70cd-11e7-86d8-e5f65321c6ca.png)

**Comment by paramat** [comment]
So lighter coloured glass is not a bug it seems, and the noairnodes mod has been buggy for a long time, that leaves sumpf water as a possible bug, the bug may be in the sumpf water code, the nodedef should be compared to default:water for mistakes.

**Comment by paramat** [comment]
I suggest try using the exact MTG water nodedefs in sumpf mod, but just using the sumpf water textures, to see if the problem is the sumpf nodedefs. If the bug continues then you'll know it's something to do with the texture.

**Comment by paramat** [comment]
For the coloured glass, i colour-sampled the clear glass in your first screenshot at a point in front of a distant cloud, and then reduced saturation to 0, this results in RGB all 137. Because cloud sides are not pure white these values will probably need to be raised but it's a starting point.

**Comment by paramat** [comment]
![screenshot_20170728_004029](https://user-images.githubusercontent.com/3686677/28696440-7913155c-732d-11e7-9711-2ebaf911b363.png)

Experimenting ..
abriglass_plainglass.png RGBA 64 64 64 127
Similar darkness to classic but stronger colours.

**Comment by paramat** [comment]
![screenshot_20170728_004730](https://user-images.githubusercontent.com/3686677/28696590-63a34fa6-732e-11e7-9c5a-bb30598f633f.png)

Same with edited 'colourize ratio'.
`tiles = {"abriglass_plainglass.png^[colorize:#"..colour..":63"},`

**Comment by Ezhh** [comment]
Thanks paramat and numberZero. Been struggling with some other bug reports on the server, but hopefully I will be able to fix the glass over the weekend thanks to your help. 

sumpf is confusing, because I did try using the MTG default water source code with name/texture changed, but still had issues. I have adjusted the textures now to add more brightness and contrast and that makes them show (no code change, just texture change), but the source node still loses the texture when viewed from certain angles. Will look at it more over the weekend.

**Comment by paramat** [comment]
As for the coloured glass, i'm sure the old behaviour was the buggy behaviour, because your RGB = 255 textures should have been visually bright.

**Comment by paramat** [comment]
For sumpf, i notice that is missing the single frame water texture and only has the animated textures, maybe the single frame texture is needed (but i'm not sure).

**Comment by Ezhh** [comment]
Okay, updated glass to:
![abriglass](https://user-images.githubusercontent.com/7035183/29003236-d144baa8-7aaa-11e7-9774-c0bda52df458.png)
Not as dark as I would like, but it makes the glass clear and gives nice solid colours while still able to see through it properly, unlike the washed out ones I was getting, plus I think more people will favour it.

sumpf water still needs more work, but if I can't figure it out by now I never will, so will close this . :)

Huge thanks for the help.

**Comment by paramat** [comment]
I think that new abriglass looks better than the original appearence. By adjusting RGB values you can get it darker if you wish.

**Comment by paramat** [comment]
@Ezhh saw you are having problems with inventory images for abriglass, i don't think inventory supports semi-translucent nodes, so you could use 'inventory_image = "blahblah"' in nodedef and supply inventory textures.
