### ISSUE TITLE
chests stuck open if player disconnects

### ISSUE THREAD

**Issue by retsil2** [minetest/minetest#6155]
to recreate the bug in multiplayer, log in as player1, open chest, disconnect while the chest is open. log in as player2. the chest is now stuck open. it can be used normally, but it cannot be removed.

with worldedit priv, player2 can remove the chest. however, any other chest placed in the same node will get stuck open as soon as it's open.

it's been reported that player1 and only player1 can close the chest, at which point one would assume the node goes back to normal.

**Comment by tobyplowy** [comment]
Related? https://github.com/minetest/minetest_game/issues/1769

**Comment by rubenwardy** [comment]
Duplicate of https://github.com/minetest/minetest_game/issues/1769
