### ISSUE TITLE
Protocol bump due to 'settable player collisionbox'?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6160]
Since #6007  is a major breaking change.
Bump to 36 or combine into 35?

**Comment by SmallJoker** [comment]
"breaking change" - How about rising the minimal protocol version to 35? That's how players can be notified that master is going to do compat breaking changes.

**Comment by paramat** [comment]
Good point.
It seems that the CSM flavours feature was combined into the previous 35, so for this major breakage i think we need to go to 36.

**Comment by stujones11** [comment]
I agree this deserves another bump otherwise there's going to be a lot of reports of 'floating' or 'sunken' players.

**Comment by paramat** [comment]
Nerzhul thinks it doesn't need a bump or raising minimum http://irc.minetest.net/minetest-dev/2017-07-23#i_5017864
He suggests combining with previous and not raising minimum.

**Comment by paramat** [comment]
I'll make a PR to at least document it and combine into previous 35.

**Comment by paramat** [comment]
PR #6168

**Comment by paramat** [comment]
#1668 merged.
