### ISSUE TITLE
can't active a mod called 'blood'

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#6162]
[the forum post giving many details](https://forum.minetest.net/viewtopic.php?f=6&t=17547&p=268202#p268202)

Seems like something was broken since 4.15 update... a mod called blood can't be actived in any way! I can't do it from the `configure` button in the singleplayer tab... I can't either from the .conf settings in world folder... the only way to force the game loading it is by putting it inside `minetest-4.16\games\minetest_game` !!! It's very problematic because ChibiGhost said it was working all fine... :confused:

**Comment by sfan5** [comment]
can't reproduce, your mod is broken

**Comment by azekillDIABLO** [comment]
hey, the hell don't close so fats you are crazy or what? i mean, this mod is not broken, i could reduce it to
`print(demn)` and it would still won't work!!! and chibi ghost showed it was working! please read my post again, hell!! the code is okay, i can't active it, i can't have any debug about it. but

> the only way to force the game loading it is by putting it inside minetest-4.16\games\minetest_game !!!
this way works very well!

**Comment by SmallJoker** [comment]
Remove the copy of your "blood" mod from the `mods` directory and try again. Otherwise try again with a clean 0.4.16 installation.
