### ISSUE TITLE
GenericCAO models are dark when below y = 0

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6174]
Testing on a local server:

![screenshot_20170726_015326](https://user-images.githubusercontent.com/3686677/28599962-b96888f4-71a6-11e7-971f-2edf1817adfe.png)

![screenshot_20170726_015341](https://user-images.githubusercontent.com/3686677/28599967-bef99236-71a6-11e7-8449-7b6d2bffded2.png)

Jumping or hovering slightly above a node makes light return, so i suspect that the recent 'player settable collisionbox' change has shifted the point that defines player model light down by a node to feet position, and that being below y = 0 is a sign reversal that puts that point just inside the node below.
If so then when above y = 0, flying very slightly into the ground should make the player go dark too:

![screenshot_20170726_015602](https://user-images.githubusercontent.com/3686677/28600057-76784100-71a7-11e7-8585-407980509a3d.png)

![screenshot_20170726_015620](https://user-images.githubusercontent.com/3686677/28600063-88fa9224-71a7-11e7-8011-9af0beaad14b.png)

Confirmed. So it seems that a 1-node vertical offset was forgotten somewhere.
@TeTpaAka

**Comment by paramat** [comment]
I might know why. Previously player pos was centre of model, now it's foot position, so light is being sampled at foot position, we need to add in a vertical offset to raise this point back up to model centre, or, up by 1 node. If we raise by 0.9 * BS this will be rough model centre. But only for player objects.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/master/src/content_cao.cpp#L944
```
v3s16 GenericCAO::getLightPosition()
{
	return floatToInt(m_position, BS);
}
```

**Comment by kaadmy** [comment]
Just so you know, `ItemCAO` doesn't seem used outside of `content_cao.cpp`.

**Comment by kaadmy** [comment]
Doesn't the player have a seperate subclass of GenericCAO?

**Comment by nerzhul** [comment]
if i remember ItemCAO is obsolete

**Comment by paramat** [comment]
Ok.
Fot genericCAO i think it's best to go with
`return floatToInt(m_position + v3f(0, 0.5 * BS, 0), BS);`
to work with mobs / players that are 1 node high, this is also halfway up a node height so is a good general light position, i'll make a PR.

**Comment by Wuzzy2** [comment]
This is not just for player models, but for **any** models. I have seen this for item entities, boats, carts, mobs and pretty much **any** entity based on a mesh.

**Comment by paramat** [comment]
Yes but that's different and a non-issue, it usually happens when the model centre passes into a node, the model centre being the point that determines where light is sampled.
This issue is player model going dark when correctly standing on a node, because the light position is at foot level instead of higher up.

**Comment by bigfoot547** [comment]
I also noticed that the nametag is not on top of the player, but rather in the center of the player.

**Comment by TeTpaAka** [comment]
@paramat No, it is the same issues. Now, players, mobs and other entities use the same code for display and so they (should) show the same behavior. If a mob would be standing at the exact same position like the player in your screenshot, it would be black. The client doesn't even differentiate between other players and luaentities.

@bigfoot547 I'll look into it.

**Comment by paramat** [comment]
Ok, i thought people were describing the existing behaviour. Obviously mobs should have the same issue.

**Comment by SmallJoker** [comment]
#6179 merged.

**Comment by paramat** [comment]
It wasn't merged, just done it now.
