### ISSUE TITLE
It's possible to interact, break, placing and attack around obstructions in 3rd person view

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#6181]
I found a glitch only on phone/tablet version of Minetest, how to reproduce a glitch?
I build a wall with a chest that cannot be reached. Build like this, stand on this position, make sure to toggle 3rd person mode and try to interact a chest to open and store/steal items. If you did it correctly, you reproduced a glitch. If you not, its going to be sad :(
![image](https://user-images.githubusercontent.com/13905392/28670055-a17c14b0-72df-11e7-991a-c2e5b3de07fc.png)

**Comment by kingoscargames** [comment]
I dont think this is a glitch.

**Comment by WSDguy2014** [comment]
Keep in mind, this glitch only works on Android version. It need to reproduce a glitch to make players interact through walls and stuff like that.

**Comment by kingoscargames** [comment]
Do you mean being able to open chest like this?:
![screenshot_2017-07-28-00-26-00](https://user-images.githubusercontent.com/29333817/28694776-c324ea5a-732b-11e7-9bd4-dbdb3b816e5c.png)

![screenshot_2017-07-28-00-26-05](https://user-images.githubusercontent.com/29333817/28694766-b2f7ee20-732b-11e7-8dfb-844612395e2f.png)
(Screenshots were made on android version 0.4.15 (and this post was also made on mobile))

**Comment by WSDguy2014** [comment]
@kingoscargames Yes.

**Comment by kingoscargames** [comment]
Thats because mobile doesnt have a cursor and can just click everywhere.

**Comment by WSDguy2014** [comment]
Or crosshair. especially if you playing with mods trying to shoot at the animal for example.

**Comment by rubenwardy** [comment]
is this still an issue after https://github.com/minetest/minetest/commit/01c319d7784c3db614a53745e5af62c43cf45c90 ?

**Comment by paramat** [comment]
I expect it still happens because the chest is within interact distance but is behind an obstruction.

**Comment by srifqi** [comment]
How about making it always pointing at crosshair (center) when in 3rd person view?

**Comment by WSDguy2014** [comment]
@srifqi Yes, sure it's needed. I saw the the crosshair in first person view in the modified Minetest build engine for the Android, such as CubeMator, it's badly functions (like breaking the block through and badly updates node/entity highlight).
![image](https://user-images.githubusercontent.com/13905392/39927765-00300a86-553c-11e8-8923-502a196e68f3.png)
