### ISSUE TITLE
Going up stairs is faster on Android (faster swim and stepheight advantages) (autojump discussion)

### ISSUE THREAD

**Issue by WSDguy2014** [minetest/minetest#6183]
To make Android clinet players automatically jump 1 block high in tablet/phone versions, developers increased the stepsize to 1 (block) instead of 0.5 (half-block), rather making to add auto-jump feature. It's like Counter-Strike 1.6 or other games made in Gold Source Engine using console command cheat called "sv_stepsize". To make a speed test proof for PC and Android, make a staircase to go up y-100 to y0 without any stair buildings, to start a speed test, make sure start a timer and both PC and Android players go up the stairs to get out on the surface, make sure to facing straight for maximum speed in any directions, if it reaches y0 first, stop a timer to get a result. If you want to go faster, download sprint mod and do a same test but with sprinting (not using very fast sprinting without mods).

**Comment by paramat** [comment]
How much faster, and is it a problem? Doesn't seem so. Dedicated code to alter this is unlikely to be added as we have very little time for Android.

**Comment by WSDguy2014** [comment]
In mining, if player playing on PC version is trying to attack to kill another player (playing on Android version), Android player is trying to sprint to escape from fight by going upstairs 1 block high and does not have build staircase blocks yet, PC player is trying to chase Android player, but unfortunately Android player is escaping so fast, that PC player can't chase to other player. That's how cheaters playing Android version of the Minetest without using any hacked clients or cheats. This is require to nerf stepsize back to 0.5 node and then adding auto-jump feature to prevent using for cheating.

**Comment by SmallJoker** [comment]
In exchange for the fast speed, an Android player can not react with the same speed as one on a PC. I think we can give our mobile players this little advantage for the (as I heard) complicated controls.

**Comment by paramat** [comment]
WSDguy2014 good point, but i feel we would rather avoid adding anything complex to solve this. maybe something in settings, like for example a slightly slower walk speed to compensate?

**Comment by jastevenson303** [comment]
PC users can circle strafe.  Android users can hardly move at all.  Ive been playing on mt android from play store a lot.

**Comment by WSDguy2014** [comment]
I played on Hometown server, i saw another player playing on tablet/phone, swimming speed is faster than PC, that's not possible to chase Android player to kill. It also won't sink. Can you compare speed (make sure any direction facing straight and sinking speed test for Android and PC version.

**Comment by jastevenson303** [comment]
Sounds like a fun research project.  I will let you know when I test and compare.

**Comment by DS-Minetest** [comment]
>i saw another player playing on tablet/phone, swimming speed is faster than PC

I saw that, too. But I think it wasn't the official minetest client.

**Comment by paramat** [comment]
I doubt we have set swim speed to be faster on Android.
Maybe the difficulty of Android controls is an acceptable balance for the faster stair climb?

**Comment by ExeterDad** [comment]
Now that swimming was added to the conversation. Not only is swimming faster,  but it's possible for Android users to jump out of the water onto a block that is on top of the water and escape, when the PC user can not jump up onto the same block.

**Comment by paramat** [comment]
Interesting, must be the stepheight. It's possible the stepheight makes jumps onto higher obstacles possible too.
```
#ifdef __ANDROID__
	player_stepheight += (0.6f * BS);
#endif
```
Maybe we need to disable this or make it a setting?

**Comment by jastevenson303** [comment]
It has jump and crouch buttons on lower right.

**Comment by sorcerykid** [comment]
I've observed that Android players have unusual swim and jump capabilities. I am unable to emulate them on a PC no matter how hard I try.

**Comment by paramat** [comment]
I feel that hardcoded increase in stepheight should be server-configurable, since it gives several advantages.

**Comment by paramat** [comment]
Issue #6200

**Comment by paramat** [comment]
PR #6217 removes the very hacky attempt at Android 'autojump' which causes these issues.

**Comment by paramat** [comment]
Partial fix #6313

**Comment by paramat** [comment]
#6313 merged.

**Comment by paramat** [comment]
Does android actually need autojump? It applies it as a custom player stepheight, but a mod can now set player stepheight.

**Comment by Fixer-007** [comment]
I think it does need autojump, player is already crazy enough to play minetest on a dumb phone.

**Comment by paramat** [comment]
Yes we'll probably add an option usable for both Android and desktop.

**Comment by paramat** [comment]
This code could remain here and be enabed by a new server setting (not client setting) instead of by '#ifdef __ANDROID__'

**Comment by paramat** [comment]
Mods can now set custom stepheights per-player, so autojump is possible for all players already.

**Comment by red-001** [comment]
@paramat it should still be default for android, also I'm pretty sure there is no way for mods to tell what OS the client is running on, that's something we should add imho.

**Comment by paramat** [comment]
It can't be a default for one platform and not for another, as that is exactly what creates advantages for Android players on a server. It has to be all players or or none, and decided by server not client.
If desired the server can provide a mod that gives any player that wants it a higher stepheight (through per-player settable stepheight).

I don't agree with this idea of allowing significant advantages to balance supposed disadvantages of Android, we are going to improve Android controls anyway before 0.5, that is a blocker for release.
The jump button is not remotely the worst aspect of Android or Android controls and i disagree with this idea that jump is somehow unusable on Android, it has a functional jump button that will work well once it is attended to.

If someone is using Android then they have to accept the poor interface they are using and they don't deserve cheaty advantages.
We will attend to this somehow before release but this bit of code has to go and will go before release, so it can be done now.
It is also getting in the way of serverside movement, see https://github.com/minetest/minetest/pull/6219#issuecomment-361312374 which is serverside anticheat improvementa and top priority.

**Comment by bendeutsch** [comment]
Would it make sense to implement the auto-jump not as an increased step height, but as an actual jump? Triggered when running into a node with (two) free nodes above it? Then we could fiddle with the jump mechanics (use stamina, higher jumps, cooldown, artificially _reduced_ jump height) and not have to worry about how to achieve the same thing with step height, if we even remember to do so.

Please correct me if I'm wrong, but I've always seen the Android jumping thing as a compensation for it being really hard to move, turn _and jump_ at the same time. We could even implement it completely client side, by just emulating a jump key press. Also, at least one well-known voxel game added a client-side auto-jump a while ago :-P

**Comment by paramat** [comment]
However, i can see dilemmas here.

If Android doesn't have autojump ability our app becomes less attractive to players, at a time where we are desperately trying to bring them back.
If we provide autojump as an option for all players on a server, those using it will have some advantages as discussed above, which adds pressure for all to use it. However autojump is something a player loves or hates, those who don't like it won't like to feel they have a disadvantage and don't want pressure to use it.
However setting autojump on or off for all players will of course deeply irritate most players.

It seems we need to remove any side-effect advantages.

It seems it needs to be a server-controlled option, as in, the server decides whether to allow it or not, and if allowed provide it as a choice for players. The player object stepheight already makes this possible and could be used for now, it is Lua code so should be in builtin to affect all games.

**Comment by bendeutsch** [comment]
> If we provide autojump as an option for all players on a server, those using it will have some advantages as discussed above, which adds pressure for all to use it.

Here's an idea: implement autojump as a regular jump **with a slight delay**. This way it's not a complete advantage for players (since you can always do better by jumping yourself) but is a welcome support for players that need it.

**Comment by paramat** [comment]
I think autojump should be an option chosen by each player (any player, not just Android) but with the server having optional (default disabled) control to force it on or off for all players. However it will be recommended that servers allow players to choose.

This can already be done in Lua code by using 'player object properties' to set per-player stepheight, however stepheight seems to give slight advantages, perhaps we can (maybe later) create a different implementation with no advantages (might be difficult though).
