### ISSUE TITLE
Mapgen v7 breakage

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6184]
Regreesion in https://github.com/minetest/minetest/commit/bc1654feedc90caa8c26328ca6f0fc59fbe5b76c (Noise::perlinMap2D,3D: replace a loop init with a single memset call)

I've started playing on my recent world and had abrupt change of terrain/(biome? not sure) to nearly flat (ocean suddenly changed to elevated flat sand desert).
![2017-07-27 16_00_18-minetest 0 4 16-bc1654fe-bc1654fe-dirty opengl 4 5 13417](https://user-images.githubusercontent.com/16494741/28671728-64584b1a-72e6-11e7-83c8-1ef1dc4acbf6.png)
I've created new v7 map and problem persisted (nearly flat terrain with rivers and occasional mountains):
![default](https://user-images.githubusercontent.com/16494741/28671706-50bf678c-72e6-11e7-86c1-325b419c9579.png)
Other mapgens not affected it seems.

**Comment by nerzhul** [comment]
Fixed
