### ISSUE TITLE
first person view is a node too high

### ISSUE THREAD

**Issue by gpcf** [minetest/minetest#6191]
When connected to a server, I noticed that the first-person view is a node too high. This doesn't happen in third person-view, this makes that I can only go through doors in third-person view and not in first-person view. I'm running VER=0.4.16-dev-d504831e.

**Comment by SmallJoker** [comment]
Either update the server or downgrade your Minetest installation. We're going towards 0.5.0, which includes compatibility breaking changes like #6007, that's where this problem originated.

**Comment by paramat** [comment]
Yes keep both your server and client before or after coomit https://github.com/minetest/minetest/commit/49920cfe8dc7869bb8235c6fe2b8ef26e2a523ca
Also make sure you have the corresponding MTGame as the model was shifted vertically too.
