### ISSUE TITLE
Change default port number

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6192]
Minetest uses port 30000 as the default.

Problem 1: Port 30000 is not IANA registered for Minetest:

```
ndmps              30000       tcp    Secure Network Data          [Alioune_Thiam]                                       [Alioune_Thiam]                                           2013-02-05
                                      Management Protocol
                   30000       udp    Reserved
```
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt

Problem 2: Port 30000 is also used as default by Freeminer and Voxelands.

I suggest to change this. We have 2 options:
* Option 1: Change the *default* port to some port in the private area (49152 through 65535). Can be done instantly.
* Option 2: After option 1 has been done. Formally register a port number at the IANA, and use that as a default *after* it has been approved. I'm not sure if “the Minetest protocol” is eligible for this, but why not trying? https://www.iana.org/form/ports-services

Option 2 should be only done after careful consideration for obvious reasons.

**Comment by jastevenson303** [comment]
Are you suggesting a long-held default setting be changed because of two projects forked from this one also use that same default settings?

Or is it the possibility, albiet nil, of minetest getting an assigned port number?  Because it seems to me you just want to rename everything!

**Comment by mark-otaris** [comment]
Minetest is eligible. It can't use a port in the dynamic range (except in singleplayer) because the port has to be consistent between server restarts (except for servers on the server list). Otherwise clients can't know what port to connect to.

There is no need for option 1 unless Minetest 0.5.0 has to be released before the application is accepted.

**Comment by sfan5** [comment]
> Port 30000 is not IANA registered for Minetest:

Port 25565 is not registered for Minecraft.
How many people do you see giving a shit about that?

> Port 30000 is also used as default by Freeminer and Voxelands.

10/10 logic, those forks came into existence after MT
Why don't they change their port numbers?

> Change the default port to some port in the private area (49152 through 65535). Can be done instantly.

I'm sure everyone will love to have all their favorited servers, port forwards and firewall exceptions broken.


Overall :-1: :-1:

**Comment by Fixer-007** [comment]
udp 30000 is reserved, so no problems here. Voxelands and freeminer not a problem.

**Comment by Wuzzy2** [comment]
So Minetest won't have an IANA registered port, ever?

> Port 25565 is not registered for Minecraft.

“because Minecraft” is one of the worst reasons to reject or accept anything.

> I'm sure everyone will love to have all their favorited servers, port forwards and firewall exceptions broken.

0.5.0 is a breaking release, so …?

> > Port 30000 is also used as default by Freeminer and Voxelands.

> 10/10 logic, those forks came into existence after MT
Why don't they change their port numbers?

OK, this was a stupid argument. I'll admit. It seems Freeminer is almost dead anyways, and there is not much activity in Voxelands. I guess I'll talk to darkrose then.

> Minetest is eligible. It can't use a port in the dynamic range (except in singleplayer) because the port has to be consistent between server restarts. Otherwise clients can't know what port to connect to, 
except for servers on the server list.

“Dynamic range” doesn't mean that the number changes every restart. I just suggested to pick any number in this range as the default, not to change the port number after every restart. This would be insane.

**Comment by paramat** [comment]
:-1: For same reasons.

**Comment by nerzhul** [comment]
:-1: too we don't care

**Comment by paramat** [comment]
SmallJoker / Krock agrees to close http://irc.minetest.net/minetest-dev/2017-07-31#i_5029052

**Comment by Wuzzy2** [comment]
Haha, okay. It was worth a try, however. :grin:
