### ISSUE TITLE
on_rightclick callback is not called if node has a formspec

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6195]
The `on_rightclick` callback of a node does *not* get called if the node is rightclick and it has a formspec assigned to it via metadata (`"formspec"`).

Here is a test mod:

```

minetest.register_node("test_rightclick:rightclick", {
	description = "on_rightclick Test Node Without Formspec",
	tiles = {"default_stone.png^default_grass_side.png"},
	groups = {dig_immediate=3},
	is_ground_content = false,
	on_rightclick = function(pos, node, clicker)
		minetest.chat_send_player(clicker:get_player_name(), "You rightclicked an on_rightclick Test Node Without Formspec!")
	end,
})

minetest.register_node("test_rightclick:formspec", {
	description = "on_rightclick Test Node With Formspec",
	tiles = {"default_stone.png^(default_grass_side.png^[colorize:#FF0000:128)"},
	groups = {dig_immediate=3},
	is_ground_content = false,
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		meta:set_string("formspec", "field[test;;${text}]")
	end,

	on_rightclick = function(pos, node, clicker)
		minetest.chat_send_player(clicker:get_player_name(), "You rightclicked an on_rightclick Test Node With Formspec!")
	end,
})

```

**Test description**:
This adds 2 nodes. Both nodes have `on_rightclick` set which should post a simple chat message when rightclicked. One node gets a formspec after construction, the other one doesn't.

**Expected behaviour**:
When rightclicked, both nodes display a chat message. The node with the formspec shows the formspec as well.

**Real behaviour**:
If you rightclick the formspec node, you only get the formspec, but no chat. Which is incorrect.
If you rightclick the other node, you get the chat message, which is correct.

**Documentation**:
The documentation does not have any indication that `on_rightclick` may not be called when the node is rightclicked.

**Test environment**:
* Minetest 0.4.16
* Minetest Game 0.4.16
* No further mods except the test mod above

**Comment by sfan5** [comment]
This is hard to fix since the decision to show a formspec instead of sending the interaction to the server is done client-side.

IMO the best solution would be to just document this behavior and live with it.

**Comment by Wuzzy2** [comment]
This makes a very basic use case needlessly complicated:

* Simple formspec-based chest which makes a sound when rightclicked (aka opened)

Now you are forced move to nuke the metadata and open the formspec via `minetest.open_formspec` in `on_rightclick`. This reduces the power of node metadata. I don't think this sounds like the best solution. :-(

**Comment by SmallJoker** [comment]
Thinking about for how long this behaviour already exists - I'd be surprised if this issue wasn't a duplicate.
The workaround with calling \*`.show_formspec` separately works fine but this inconsistency should be fixed for easier modding in this case. Fixing itself shouldn't be a problem for existing mods as we'd only remove a limitation.

**Comment by sfan5** [comment]
The fix itself is not hard, but you have to consider that every `on_rightclick` will act "unreliably" for many years to come since it takes several until changes reach e.g. Debian stable.

**Comment by Wuzzy2** [comment]
So … the bugfix is rejected or delayed because Debian sucks? 
This is sad and crazy.

It sounds extremely frustrating if Minetest development depends on the Debian release cycle …
How about we just beat the Debian maintainers with a stick until they finally update the Minetest package? ;-)

**Comment by DS-Minetest** [comment]
But when 0.5 comes out, the clients have to update.

**Comment by paramat** [comment]
^ Exactly, so this seems ok, we are already in the pre-0.5.0 period of breaking compatibility.

**Comment by paramat** [comment]
#6232 merged.
