### ISSUE TITLE
Mirrored statbars

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6198]
I request statbars to be able to be mirroed. “Mirrored” means the symbols go from right to left instead of left to right. The symbols themselves are not mirrored.

For example, a normal statbar with value 11 looks like this:
![unbenannt](https://user-images.githubusercontent.com/1675853/28927751-a3a79048-786b-11e7-9ad7-bab1f1d3901d.png)

The mirrored version would look like this:
![unbenann2t](https://user-images.githubusercontent.com/1675853/28927752-a3ab314e-786b-11e7-9f48-7ceab6b07c3e.png)

**Comment by paramat** [comment]
I guess the reason it is useful is because the 'zero points' become the lft and right edges of the hotbar, so the amount of each stat become svisially clearer?

**Comment by Wuzzy2** [comment]
Yes, it's for MineClone 2. It's not really important.

**Comment by DS-Minetest** [comment]
Isn't there already a possibility to set the direction? https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1160,L1164 And statbar can have it. https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1209

**Comment by Wuzzy2** [comment]
Setting `direction` almost works. It also changes the origin, but this is okay.
What is wrong are the “half” symbols:

![buggy reverse statbar](https://i.imgur.com/kRQWiYZ.png)

**Comment by C1ffisme** [comment]
I don't remember Minecraft doing this, actually, but I do think this might be nice to have.

**Comment by rubenwardy** [comment]
That looks like a big to me. Flipping the direction should flip the direction of the half icon

**Comment by paramat** [comment]
It's a bug if 'direction' is a HUD bar parameter.

**Comment by paramat** [comment]
If there is a 'direction' parameter then we already have mirrored statbars (but with a bug).
