### ISSUE TITLE
Disable pointability for entities

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6199]
I request that it is possible to disable the pointability of entities.
This means, if the pointability is disabled, nobody is able to point the entity.

Use case: Item magnet. When dropped items are supposed to be attracted to the player like a magnet to collect them, instea of clicking them (which is supposed to do nothing). For this use case, being able to point item entities is annoying because the selection box just gets in the way.

**Comment by stujones11** [comment]
I support this idea, however, I think a better approach would be to give entities (including players) a separate selection and collision box, much the same as nodes have. This way you can zero the selection box without disabling collisions.

**Comment by Wuzzy2** [comment]
@stujones11: Your suggestion does not conflict with my suggestion at all.

For nodes you can also disable pointability entirely, plus you can set a custom selection box. Setting the selection box to zero to disabling pointing seems hackish. Better to have a separate field (like `pointable` for nodes).

**Comment by stujones11** [comment]
A point-ability flag is also fine by me, I am just suggesting that for consistency, the selection and collision boxes should be independent of each other. The`pointable` flag would likely just zero the selection box, under-the-hood, anyway.

**Comment by paramat** [comment]
'pointable = false' for entities seems good to me. Also having separately definable selection and collision boxes might be good too if useful.

**Comment by stujones11** [comment]
> Also having separately definable selection and collision boxes might be good too if useful.

It would be particularly useful for vehicles, etc, where the collision box often needs to be a completely different shape/size to the entity itself. However, if adding a flag is possible without having separate boxes then this could always wait for another day.

**Comment by stujones11** [comment]
I've had a play with this and it is quite easy to give entities independent selection an collision boxes, which behaves as expected when the selection box is 'zeroed', that is the entity cannot be selected but collisions do still work. The only issue I have with it right now it that there seems to be no _clean_ way to use the collision box as default when no selection box is specified, otherwise I'd make a PR :)
