### ISSUE TITLE
Do not hardcode stepheight, Android stepheight issues

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6200]
A reminder to myself to do this, it is a TODO in the code
https://github.com/minetest/minetest/blob/master/src/localplayer.cpp#L281
```
	// TODO: this shouldn't be hardcoded but transmitted from server
	float player_stepheight = (touching_ground) ? (BS * 0.6f) : (BS * 0.2f);

#ifdef __ANDROID__
	player_stepheight += (0.6f * BS);
#endif
```
This also means the advantages Android players have due to their increased stepheight #6183 can be removed by the server if desired, or, desktop players can be given the Android stepheight.
The 0.2 value would remain unchanged and a server setting added for the 0.6 value.

The issue is, this file is localplayer.cpp, so will a setting defined here actually be a clientside setting? How do i make sure it is a server setting?

**Comment by raymoo** [comment]
Wouldn't you use object properties or something, since stepheight is in that? Step height should be able to vary between players. I know other object properties like visual_size is already sent, can't check where they're stored because I'm on my phone though

**Comment by paramat** [comment]
Actually, there's a PR for per-player stepheight #2056 which was merged then reverted due to breakage, but could now be merged as part of 0.5 breakage. We could then use that. See https://github.com/minetest/minetest/pull/2056#issuecomment-300048605

**Comment by paramat** [comment]
Since i've worked on that before, tested it and reverted it, i'll make the PR.

**Comment by paramat** [comment]
#6217 merged.
Thi sissue remains:
Android stepheight should only be increased by 0.6 if 'touching ground'.

**Comment by paramat** [comment]
See PR #6313

**Comment by paramat** [comment]
#6313 merged.

**Comment by paramat** [comment]
So closing.
