### ISSUE TITLE
The "Change Keys" page does not keep the game paused.

### ISSUE THREAD

**Issue by BitOfAByte** [minetest/minetest#6201]
When you are in single player and press escape, the game is paused. However, if you click "Change Keys", the game is no longer paused despite this being part of the pause menu screen. The "Sound Volume" page keeps the game paused as expected.

**Comment by t0ny2** [comment]
It appears to be because the GUIKeyChangeMenu class doesn't override it's parent's (GUIModalMenu) pausesGame() method.
