### ISSUE TITLE
Randomly unexpected HUD behavior with statbars

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#6204]
When running a server with multiple HUDs that update frequently, there seems to be a small chance of the engine mixing up HUD IDs

Description of behavior:
- Statbar of armor mod suddenly behaves like the breathe statbar (decreasing/increasing in/out of water)
- Statbar of health behaves like the armor statbar (increasing/decreasing when (un)equipping armor)
- Statbar of stamina mod totally gray and/or disappears

___________________________________________________________________________
Those bugs do not happen at boot time, they happen during runtime in certain circumstances (I'm guessing internal server lag or something like that)

Reconnecting with an affected client does not fix it! It is definitely server side.

**Comment by jastevenson303** [comment]
I wonder if this is related to minetest.hud_replace_builtin(name, hud_definition) -- I don't use that in runfast, and haven't experienced this glitch.  I do remember experiencing it in better hud mod, though.

**Comment by Fixer-007** [comment]
I have statbars shifted down when connecting with newest client to Time Travel Server, not sure if related @Wuzzy2

**Comment by nerzhul** [comment]
the Hud id behaviour is bad client side, we should change std::vector to std::unordered_map to prevent the network ordering problem on HUD you mention, poke @SmallJoker @rubenwardy @sfan5 (just to know the problem)

**Comment by SmallJoker** [comment]
HUDs are now kept a map - server and client provided together.
Related: #7052

**Comment by SmallJoker** [comment]
Re-open this issue if it still happens after ffb17f1c (removed legacy code) and eea1fda (startup fixes).
