### ISSUE TITLE
Double clicking outside of the GUI inconsistently closes some GUIs.

### ISSUE THREAD

**Issue by bvanrosendale** [minetest/minetest#6206]
For some GUIs, when you double click on any of the area outside of the grey game paused box, the menu will close and the game will be unpaused (if paused). 

This happens on the pause menu, inventory, chest, and furnace.

This does not happen on the sound volume page or the change keys page.

I personally do not think that this should close the GUI, but if it does it should at least be consistent.

**Comment by SmallJoker** [comment]
Fixed.
