### ISSUE TITLE
Overlaying more than 3 semi-transparent textures causes transparency problems

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6210]
Consider this: You have an opaque base texture. Then you overlay several textures with semi-transparent pixels over it. If there are more than 3 semi-transparent textures in row, the resulting texture might end up with fully transparent pixels which can seriously break your in-game graphics.

This result is definitely wrong because no matter the overlays, the result must always be fully opaque if the base texture was opaque.

Here is a test mod for this:

```
local tile = "test_overlay_base.png"
for i=0,16 do
	if i > 0 then
		tile = tile .. "^test_overlay_gradient.png"
	end
	minetest.register_node("test_overlay:overlay_"..i, {
		description = "Overlay Test Node #"..i,
		tiles = { tile },
		groups = {dig_immediate=3},
		is_ground_content = false,
	})
end
```

This registers 16 gradient node and one base color node for comparison, with the number standing for the number of overlays. Each successive node adds one additional overlay layer.

If you want to test this yourelf, you have to create the textures for yourself: The base color is just plain yellow and the gradient is red to transparency.

The expected result is that every node is fully opaque.

Actual result: Here are the 17 test nodes from number 0 to 16:

![](https://i.imgur.com/SCQlFEo.png)

As you can see, the base node and the first 3 overlayed nodes look normal. But from node number 4 on, the overlaying fails. Some pixels ended up being transparent for some reason. This bug continues for the remaining test nodes.

Testing environment:
* Minetest 0.4.16
* Minetest Game 0.4.16
* The test mod above (`test_overlay`)

**Comment by HybridDog** [comment]
How does it look like if you set use_texture_alpha in the node definition to true?

**Comment by Ekdohibs** [comment]
This is caused by the use of `getInterpolated` in the `blit_with_alpha` function: https://github.com/minetest/minetest/blob/master/src/client/tile.cpp#L1966. The problem is that although this function correctly combines colors, but not alpha as it is not designed for that. It seems there are no builtin Irrlicht functions for this task (at least in the `SColor` class), and that we have to do it ourselves, unfortunately.

**Comment by Wuzzy2** [comment]
I can no longer reproduce this bug as of 44458896d9097c15c722c5bffb3d72e14962b7ce (5.2.0-dev).

The bug still exists in 5.1.0.

Was this bug fixed accidentally? XD

**Comment by SmallJoker** [comment]
Maybe. Please ask for reopening if this issue still persists somehow.

**Comment by ClobberXD** [comment]
I think this was (unintentionally?) fixed by Warr1024 in a recent PR, which made changes in this area.
