### ISSUE TITLE
Players are sometimes given large positions far off map, resulting in crashes

### ISSUE THREAD

**Issue by ShadowNinja** [minetest/minetest#6212]
The engine sometimes places players very far off map (like 100,000 or above -- not just slightly off).  This can cause crashes when mods pass these positions to other Minetest APIs that expect a reasonable position (or just one that fits within the range of an F1000, a hack used in the protocol to send floating point numbers as fixed-point numbers -- so as to not depend on IEEE 754 presumably).

I thought there was already an issue for this, but I couldn't find it.

Related issue: ShadowNinja/areas#24

**Comment by SmallJoker** [comment]
> like 100,000 or above

How about 229'367 nodes like in #5521 ?

**Comment by SmallJoker** [comment]
Crash reported in #5521 is also related to our F1000 "floating" point network code.
Merging this issue into the one mentioned above.
