### ISSUE TITLE
Add player eye height as player object property

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6216]
An API for adjusting player eye offset (camera position) was added in https://github.com/minetest/minetest/commit/c0ab09af747fc431dfb459ede30788cb9cd1c56b
However this adds a settable value to the hardcoded player eye height which is defined here
https://github.com/minetest/minetest/blob/master/src/localplayer.cpp#L689
`float eye_height = camera_barely_in_ceiling ? 1.5f : 1.625f;`

Now that we have settable player collisonbox and settable player object property stepheight it will be possible for players to be radically different sizes.
Setting eye height by using eye offset as an adjustment to a not well known hardcoded value seems messy.

Instead, maybe 'eye height' can become a new player object property that is set alongside collisionbox and stepheight when a player model is registered? Then the eye offset API can remain relative to that property.

Related, the hardcoded player eye height is too high, it should be level with the midline of the player model's head.

This is all part of recent changes that make the player model very customisable in size.

**Comment by raymoo** [comment]
I liked the idea of "eye height" conceptually being part of the player model.

**Comment by HybridDog** [comment]
> That's not technically a 'player object property' but yes i decided to not use that as eye offsets should still be usable to offset from the normal eye position, which itself should be set according to player model height. Otherwise eye offset becomes complex to use due to becoming a combination.
My intention is explained here minetest/minetest#6216

You're right, there also could be compatibility problems. A function to get the real camera position of a player (excepting the client-side bobbing offset) could be added to avoid compatibility problems.

**Comment by paramat** [comment]
#6579 merged.
