### ISSUE TITLE
Third-person camera mode renders the player one block too low

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#6222]
Pretty sure this happened recently. Basically, the player appears to be swimming in the ground.

http://i.imgur.com/qwjfQQq.jpg

**Comment by SmallJoker** [comment]
Please make sure Minetest and minetest_game are both on the newest possible version/git hash and check this bug again in singleplayer. It may also happen on servers, where you should use the latest stable build, we're currently breaking the backwards compatibility on the way to 0.5.0.

**Comment by mtango688** [comment]
Okay. Yeah. Sorry about that. I was lacking a minetest_game update there.
