### ISSUE TITLE
(partial fix available) Recent minetest travis build jobs on osx (commits/pull requests/etc) fail with errors shown in log, doesn't complete properly.

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#6224]
Just noticed that a recent commits/pull requests/etc started to fail in travis with errors in log. e.g. job **clang Xcode: xcode8** in recent builds fails with
```
Error: jpeg 8d is already installed
To upgrade to 9b, run `brew upgrade jpeg`
```
All other jobs appears to be ok. not sure if they're really ok unless I check the log. Might need investigation, or fix. Also might be problem with the osx image or even travis itself, maybe some update broke something.
**Update:** added a fix to a PR here: #6227

**Comment by JRottm** [comment]
Yes, my PR failed, too, with the same message.

**Comment by juozaspo** [comment]
Added a WIP fix to a new PR. Check out #6227

**Comment by juozaspo** [comment]
Since this is fixed in the merged PR mentioned above, I'm closing this now.
