### ISSUE TITLE
Enable/disable full viewing range message may be confusing (R key)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6226]
Recently on IRC one person had "performance" problems while looking back on i7+R390, as it turns out because of "enabled full range" (R key).
Right now pressing R gives those status messages:  "Disabled full viewing range" or "Enabled full viewing range". This may be in some way misleading/confusing. I propose to rename it to something better, that is not confusing, for example: "Rendering within view range" and "Rendering past view range".

**Comment by JRottm** [comment]
How about "Infinite viewing range". Then, as you disable it again, the normal text "Viewing range changed to 100" is repeated.

**Comment by paramat** [comment]
Good suggestion, 'full view range' implies default game usage instead of the actual extreme infinite range it actually is. It needs to be named to indicate it is extreme and not for normal use.
On disable maybe "Normal viewing range" to indicate that is the normal usage?
Also 'view' is better English than 'viewing'.

**Comment by jastevenson303** [comment]
This has gotten me more than a few times, and it probably will again.  This may be a bit much, but, what about a persistent indicator visible - like an icon - while full-range view mode is on?  Do players ever intentionally play with this mode on constantly?

**Comment by paramat** [comment]
I don't feel an indicator is much needed, the drop in FPS is a good indicator already.
I've noticed players sometimes playing with infinite view range for a while, but it's usually something only useful for quickly viewing distant areas, without having to wait for view range to adjust, or for taking a screenshot of distant or huge areas, or for various uses in dev work.

**Comment by jastevenson303** [comment]
Right on... Could that be done with a mod?

Noticing whether fullview is on depends on the number of loaded blocks I think ha.

**Comment by paramat** [comment]
Fixer maybe you could make a PR? Should be simple.
I would +1 "Infinite view range" <-> "Normal view range".

**Comment by paramat** [comment]
PR #6230

**Comment by paramat** [comment]
#6230 merged but text was improved further by f231112cc4f0c1fe7f8bb937a49e4469157a2fa7
