### ISSUE TITLE
Scattered spawn option

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6229]
Currently everyone spawns at world centre, which leads to centralised development and little travel, and a predictable player interaction.
It would be quite simple to add an option to randomise each player spawn to within a specified radius (the setting can be a single setting which is radius from world centre, default 0).
Players can then be spread out to a chosen degree.

This allows very interesting player interaction:
You start alone and travel to find other players, once you do maybe a number of you decide to start a community in a certain place. Later some of you may travel to find other communities to trade with / fight against.
Many communities may develop across the world which then interact.
Some players may prefer to hide away in the wild and remain independent, occasionally interacting.

This allows realistic types of development and social organisation instead of every server being everyone spawning together in a giant central metropolis, which allows none of these interesting possibilities.
Minetest can be seen as a technological development starting with wood tools and moving towards a steel industry (and further if mods allow). This feature adds in social development that resembles the social development, travel and colonisation of our own planet.

Having worked on player spawn a lot i can code this.
Should it be per-world or just a simple global setting?

**Comment by jastevenson303** [comment]
static_spawnpoint is a global setting, so that might work.

**Comment by tenplus1** [comment]
Having a global 'spawn_radius' could help with 0 being default as specified, although to save player respawning at another global location from spawn point you would need to save respawn position on first join.

**Comment by paramat** [comment]
Aargh i had not considered respawn behaviour.

**Comment by dsohler** [comment]
Why not store (re)spawn point in the player object and read it from there?

**Comment by srifqi** [comment]
1) Can a player spawned near center? I mean, if you want player to be scattered around the world, then it should not be spawned near center as player can easily go to center of the world.
2) Can we just save spawnpoint like we save for bed? ... or I know nothing about it?
3) IMO, we should save config per world.

**Comment by paramat** [comment]
1. By 'scattered around' i mean still on the surface, using the same code that searches for a suitable spawn point near sea level, the only change is that the centre of that search is altered.

**Comment by Fixer-007** [comment]
This feature is often used on survival servers, especially without spawn (in minecraft). I want to see this too in minetest.

**Comment by srifqi** [comment]
@paramat By "center of the world", I mean on the surface, OFC. But, if some players spawned there, it can be very easy to be visited by other players. Making scattering's aim not effective. Because in real world, we have no idea where other civilisation is because we didn't have GPS and a coordinate system.

So, how about a doughnut shape as spawn point search area?

**Comment by paramat** [comment]
Ok sorry i see.
I see no reason for the scatter to avoid world centre, being near the world centre is no problem, as due to spawn scatter that area is no different to any other area.

**Comment by Wuzzy2** [comment]
This sounds identical to what the `spawnpoint` mod (https://forum.minetest.net/viewtopic.php?t=16923) wants to achieve. :+1: for trying to put this idea into Minetest.

@octacian!

**Comment by paramat** [comment]
Hmm static spawnpoint really should be per-world.

**Comment by rubenwardy** [comment]
If you add a function to find a suitable spawn point near a position, mods could then extend any default logic to do more complicated things such as what srifqi asks at less cost.

> Hmm static spawnpoint really should be per-world.

Settings should be per world

**Comment by dsohler** [comment]
> Settings should be per world :)

Except creative mode. That should be a per-user setting

**Comment by rubenwardy** [comment]
By settings, I'm referring to `minetest.settings`, `g_settings`, and the `SettingsRef`. That doesn't mean functionality can't use player attributes.

**Comment by paramat** [comment]
> how are you going to stop them spawning in buildings?

Yeah i guess i'm thinking too much in terms of 'new world spawn for the first player' where the terrain is unchanged. I need to think through some spawn issues.

**Comment by dsohler** [comment]
Maybe check if there is 100 nodes of free space above the player so you could at least make sure they won't spawn in reasonably sized buildings.

**Comment by JRottm** [comment]
> how are you going to stop them spawning in buildings?

The 'protection' concept is only implemented by mods, right? Otherwise you could just prevent spawning in protected areas. (Which would then include castle yards, which don't have roofs.)

> need to save respawn position on first join

This might also be made optional: respawning at a completely new location would make death **much** more serious, really a new birth, as you mostly wouldn't be able to find your old home again. This would make aquiring your first bed a very high priority and you'd have to play very cautious until you have one.
(But this might also lead to serious trolling so it should be possible to hide your name tag in these kind of "survival in the wild" worlds. And it would lead to lots of abandoned makeshift huts scattered over the map.)

**Comment by JRottm** [comment]
Oh, and servers with this enabled would need a huge HDD and CPU, because you'd generate LOTS of map whenever someone comes to 'just have a look'.

**Comment by paramat** [comment]
> how are you going to stop them spawning in buildings?

This is the case currently too, which is why servers set a static spawnpoint and keep it clear.
However, with scattered communities it then becomes potentially dangerous to be respawned at a single spawnpoint as that may be in enemy territory.
Lots to think through with this.

**Comment by rubenwardy** [comment]
Isn't this now possible with the get spawn API?

**Comment by paramat** [comment]
Yes i was recently reconsidering this issue, it can be done in a mod, and isn't high priority, so closing.
