### ISSUE TITLE
Red error debug messages when sprinting or running

### ISSUE THREAD

**Issue by dynamodan** [minetest/minetest#6233]
I just upgraded to 0.4.16 on ubuntu 16.04.  (The exact version is 0.4.16-ppa5~ubuntu16.04.1)  I get a red error message filling up my scrollback whenever I sprint.  Please see screenshot.   I also ran from terminal so here's a paste of the same message which gets echoed to the terminal:

>2017-08-10 08:09:52: [Main]: -----------------------------------------
>2017-08-10 08:09:52: [Main]: Printing debug stacks:
>2017-08-10 08:09:52: [Main]: -----------------------------------------
>2017-08-10 08:09:52: ERROR[Main]: Debug stacks:
>2017-08-10 08:09:52: ERROR[Main]: DEBUG STACK FOR THREAD 140627329799936: 
>2017-08-10 08:09:52: ERROR[Main]: #0  virtual void* UpdateThread::run()
>2017-08-10 08:09:52: ERROR[Main]: DEBUG STACK FOR THREAD 140627524863744: 
>2017-08-10 08:09:52: ERROR[Main]: #0  virtual void* UpdateThread::run()
>2017-08-10 08:09:52: ERROR[Main]: DEBUG STACK FOR THREAD 140627906582400: 
>2017-08-10 08:09:52: ERROR[Main]: #0  int main(int, char**)

It's probably something simple to get rid of those.  I've turned off all the debug settings I can find, to no avail.

**Comment by SmallJoker** [comment]
Change the key `Print debug stacks` to an empty value with by editing your minetest.conf: `keymap_print_debug_stacks = ` or using the settings menu. Looks like you wanted to use the `P` key for a different action.

**Comment by dynamodan** [comment]
That's exactly what it was.  Thanks
