### ISSUE TITLE
Support other clients and servers (eg freeminer)

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#6235]
```cpp
class Client
{
    //virtual ... //callback
}
```

**Comment by rubenwardy** [comment]
please stop making such vague issues. How do virtual callbacks improve support with forks? Surely it's up to the forks to provide protocol support? Or do you mean we should separate the code out more so it's easier to rebase?

**Comment by Fixer-007** [comment]
Freeminer and voxelands are inactive those days, I don't see a need for support...

**Comment by paramat** [comment]
It seems that it is the forks that have the responsibility to be compatible if they want to be, if they are not then that was probably there decision for a reason. So this seems like a huge amount of work for no good reason :

**Comment by SmallJoker** [comment]
Closing this issue. The requested protocol documentation in issue #6236 is more important to get compatibility. Forks can decide whether they want to break the compatibility and ship "glue" for Minetest, it's not our task.
