### ISSUE TITLE
Require USA English in code and documentation

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6238]
Here i'm checking a few words to check for consistent spelling in code, comments and docs don't count as they can be easily changed without breakage.

Center (USA) https://github.com/minetest/minetest/search?utf8=%E2%9C%93&q=center&type=
36 results, 24 of which include use in code.
Centre (UK) https://github.com/minetest/minetest/search?utf8=%E2%9C%93&q=centre&type=
41 results, none of which include use in code, all are comments, docs or translation files of docs.

Color (USA) https://github.com/minetest/minetest/search?utf8=%E2%9C%93&q=color&type=
143 results, 64 out of half of the results are in code (got tired of counting).
Also, 'color' is used in Irrlicht in SColor and SColorf often nearby the use of 'color'.
Colour (UK) No results.

Meter/metre no results.

**Comment by paramat** [comment]
MTGame (including here since related):

Center (USA) https://github.com/minetest/minetest_game/search?utf8=%E2%9C%93&q=center&type=
4 results, 2 include use in code
Centre (UK) https://github.com/minetest/minetest_game/search?utf8=%E2%9C%93&q=centre&type=
2 results, none include use in code.

Color (USA) https://github.com/minetest/minetest_game/search?utf8=%E2%9C%93&q=color&type=
7 results, 6 include use in code.
Colour (UK) https://github.com/minetest/minetest_game/search?utf8=%E2%9C%93&q=colour&type=
1 result, a comment.

Meter/metre no results.

**Comment by paramat** [comment]
Based on this i suggest we make it a guideline to always use USA English in engine and game?

**Comment by Ezhh** [comment]
The linked comment from c55 makes it look more like he just doesn't want fighting over which is used...

Personally I just go with whatever already exists within the thing I'm working on, and leave it at that, regardless of which specific english it comes from.

**Comment by jastevenson303** [comment]
I agreed with you, paramat, before conversing with TenPlus1.  He illuminated me to the fact that metre and colour are exceptions, and that centre is something different.  Now, I can't help but think that if this one word were allowed to be changed, it would add a certain charm to the software.

**Comment by rubenwardy** [comment]
We should use American English in code. I couldn't care less about comments. For items, it depends on our user base, but it should be consistent (whilst avoiding idioms)

**Comment by paramat** [comment]
Yes comments are unimportant here, and docs too i guess.

So, to avoid going through this again every year, and since MT code uses USA English throughout, and since celeron55 has requested this, can someone add this requirement to the dev wiki code style guidelines?

**Comment by stujones11** [comment]
Although I am a native English speaker, I have always used the American variation for color, center etc, when writing code, they just seem a little clearer to me.

**Comment by ShadowNinja** [comment]
> [...] can someone add this requirement to the dev wiki code style guidelines?

[Done](http://dev.minetest.net/index.php?title=Code_style_guidelines&diff=3911&oldid=3901)

**Comment by paramat** [comment]
Re-open to refer to code instead of code style guidelines.

**Comment by rubenwardy** [comment]
?

**Comment by MarkuBu** [comment]
> Yes comments are unimportant here, and docs too i guess.

I think docs are very important. Because text search is the only way to find something in the "docs" spelling is important. If you search for color you may miss each occurrence of "colour"

**Comment by dsohler** [comment]
For the sake of consistency I’d say refer to “code and documentation”.

And maybe add a checklist in first post listing all the places where the wrong spelling is used.

**Comment by paramat** [comment]
rubenwardy i'll re-title to 'code and documentation' to make this worth re-opening. I'm sure docs have wrong spelling (i'm partly to blame).

**Comment by rubenwardy** [comment]
Still confused, is this about correcting code and documentation?

**Comment by paramat** [comment]
I guess closed because docs are not important enough to change and can be changed when next worked on for other reasons. Close is fine for me.
#6690 covers 'flavour'.

**Comment by rubenwardy** [comment]
yeah, this seems resolved (unfortunately, /me drinks tea whilst crying)

I'll quickly update code guidelines
