### ISSUE TITLE
Server address text box not detecting the key "7"

### ISSUE THREAD

**Issue by ogbaba** [minetest/minetest#6239]
Hello, my cousin noticed a very annoying bug when typing the server address to connect to a server : 
he tried to enter the ip 192.168.1.107 but it wouldn't write the 7, like if it was not detecting…

here is a log : 
[minetestlog.txt](https://github.com/minetest/minetest/files/1219885/minetestlog.txt)

`
$ minetest --version
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/games/minetest"
`

the pc is running Debian 9.1 stretch

**Comment by ogbaba** [comment]
by the way I found this issue is quite old https://forum.minetest.net/viewtopic.php?pid=97098

**Comment by SmallJoker** [comment]
AZERTY keyboard. See #/302 for further information.
