### ISSUE TITLE
“m_static_exists=true but static data doesn't actually exist in (x, y, z)”

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6249]
While modding and working with entities, I often get this cryptic error message:

```ERROR[Server]: ServerEnvironment::deactivateFarObjects(): id=54485 m_static_exists=true but static data doesn't actually exist in (-3,-2,-7)```

And similar error messages, it's often repeated.

I have been told that the fact this error message even appears must been an engine bug, so I post it here. Other devs claimed that this should be only a warning, not an error.

If this is an engine bug, well, it needs to be fixed. If this is just me being too stupid with entities, well, then the docs need to be fixed.

---

To help you reproduce this (sorry, I don't know a simpler way, so it's going to be complicated!):

I have a mod ready for you in which the error occours frequently. It is `tsm_railcorridors`, version 0.13.1. This version is currently unreleased because of the massive error message spam:

Download: http://repo.or.cz/RailCorridors/tsm_railcorridors.git/snapshot/78f343f4a9cc3cd0af321fba603acc8c93f027ae.zip
Repo: http://repo.or.cz/RailCorridors/tsm_railcorridors.git

Before you start, add this into `minetest.conf` to jack up the spawn chances:

```
tsm_railcorridors_probability_cart = 1.0
tsm_railcorridors_probability_railcaves_in_chunk = 1.0
tsm_railcorridors_probability_damage = 0.0
```
(remove these lines when you're done)

Then start the game and just fly into the underground and explore as many rail corridors as possible. You should encounter many carts and also this error message.

What this mod does: It tries to spawn a few carts (`carts:cart`) on rails. This often fails because `minetest.add_entity` is broken (#4759). So I have tried to do a horrible, ugly workaround for which I feel very shamed to do it. Basically I check after a few seconds if an entity has been actually spawned (and stays spawned), and if it is gone, it tries to spawn then repeats the next check, etc. until it succeeds.

If you want to analyze the mod, look for `RecheckCartHack` and `minetest.add_entity`, these are the only parts of the mod which matter. Removing `RecheckCartHack` eliminates the error message.

---

Whee! This was complicated. Anyways, this mod proof that it is possible to trigger this error message which is apparently never supposed to appear. If I would know of a more straight-forward way to trigger this error message, I would post it.
Modders: If you also have seen this mod, please say in which mod it happened (and in which commit). This might help.

**Comment by SmallJoker** [comment]
Thanks for providing a method to reproduce this bug, also known as issue #194.
