### ISSUE TITLE
Simple init packet locks a player slot, and can be easily abused for denial of service

### ISSUE THREAD

**Issue by LeMagnesium** [minetest/minetest#6254]
I should preface this by saying that I didn't use a client to get what I had, but it's simple enough that it can be coded in two minutes, and can have catastrophic consequences. I was also running 0.4.16-dev on servers but it works with 0.4.15 servers as well and probably every version from 0.4.0 onwards.

While trying to code a small headless MT client I found, in my packet sniffing, a weird packet that started with the protocol ID, and then a bunch of null bytes followed by seemingly random junk :
```
0x4f 0x45 0x74 0x03 0x00 0x00 0x00 0x03 0xff 0xdc 0x01 0x00 0x00
```

At first, I tried to replicate that single packet in my python script. Soon, I figured that if the packet was sent once, it would actually "lock" a connection slot and have the server send back multiple requests back. But then, I had the idea of a small script, essentially recreating the idea of a RUDY or Slow Loris attack, but with that packet. And it work by repeatedly locking every player slot available. It doesn't disconnect those online, or slow down connections (at least it doesn't need to), but prevents anyone from joining.
I referred to @sfan5 who advised I open an issue here if I wanted this thing fixed, and I believe it's better to, at least, start a discussion, where it is appropriate, on how to reduce the likeliness of such things working.
To be clear : I could not "freeze" any server with my code. However, **I managed to prevent anyone from joining the servers I targeted, with no way for the admin to see what happened, and barely any network traffic (so no antiDDOS possible), using a python script that I can put together in 3 minutes**. That's pretty scary. And I haven't even coded a way to redirect traffic through a thing like Onion Routers (which is entirely feasible as far as I know). I'd also share the code here but that'd probably amount to sharing the plans of a nuclear weapon.

To say things clearly : The first network packet (which I assume is probably a keepalive of some sort) locks a connection but you can just send them in loop and never log in as a player and it will still prevent real logging in from happening by real clients. I suggest that perhaps connections be "unlimited" in amount (or have a pretty high limitation) and only valid, logged in users who have completed either the legacy or SRP exchanges of passwords count as connected users when determining when to deny new users joining. It's all up to you, really. I don't know enough to determine the feasibility of that, and it's downsides if any.

**Comment by nerzhul** [comment]
i lock conversation to let only coredev discuss about this issue, you already said all we need to work on a mitigation, i will verify our slot check, and logging about max slot reached

**Comment by rubenwardy** [comment]
What's the point? There's lots of good outside contributors, and there's been no abuse of this issue yet. Plus, locking doesn't hide it
