### ISSUE TITLE
C++11 header guards: switch to #pragma once

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6259]
Pragma once is not C++11 norm but supported by all compilers we support (GCC, Clang, Visual Studio)

Switch to it permit to remove all header guard ifdef macros on all headers and prevent any collision with any file we have or in future library we will use (who knows).

Please vote (coredevs especially) to switch on it.

**Comment by nerzhul** [comment]
@minetest/team-minetest please vote :)

**Comment by paramat** [comment]
Neutral.

**Comment by nerzhul** [comment]
6 votes

**Comment by nerzhul** [comment]
i'm working on the PR

**Comment by nerzhul** [comment]
Merged
