### ISSUE TITLE
Change version model

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6266]
Our current version model for dev uses the following scheme **[last-released-version]-dev**

This has two big cons:

* Users seems to understand it's the last released version stable build or production grade
* We cannot develop or distinguish on which branch version we are working (stable-0.4 vs master which is on the 0.5 way)

I suggested times ago to switch to **[next-release-version]-dev** instead, it will permit to have 0.5.0-dev (which is clearly a dev build on the next major version) and 0.4.17-dev on stable-0.4 to release 0.4.17 bugfix patch later

please vote on the issue adding 👍 or 👎 in this message

**Comment by nerzhul** [comment]
@minetest/team-minetest please vote on this issue

**Comment by paramat** [comment]
@celeron55 seems ok with it, see http://irc.minetest.net/minetest-dev/2017-08-15#i_5044350 and discussion before that.

**Comment by nerzhul** [comment]
note: https://github.com/minetest/minetest/blob/master/util/bump_version.sh should be changed if motion is accepted

**Comment by nerzhul** [comment]
currently there is 4 coredevs approval + celeron55 approval on IRC

**Comment by paramat** [comment]
And c55's thumbs-up in first post.

**Comment by Wuzzy2** [comment]
I will only give my thumbs up if the new versioning scheme is:

a) either fully documented in prominent places (dev.minetest.net, lua_api.txt, etc.) or
b) officially switched to SemVer (http://semver.org/), and it is officially mentioned in a prominent place that you follow SemVer

**Comment by nerzhul** [comment]
PR #6292

**Comment by nerzhul** [comment]
Fixed
