### ISSUE TITLE
Objects very dark

### ISSUE THREAD

**Issue by Thomas--S** [minetest/minetest#6268]
With latest Minetest version (both client and server), objects that are directly placed under a solid node are very dark.

~~Maybe the "New lightning curve" introduced this.~~ _As SmallJoker stated, this bug is older._

Can be reproduced for example with the signs_lib mod, homedecor's itemframes, digiline's lcd screens, street's matrix screens etc.

Example screenshot:

![](https://user-images.githubusercontent.com/7414098/29449569-8c7a49f6-83fb-11e7-8ce9-01de6eafc618.png)

**Comment by SmallJoker** [comment]
This bug is definitely older. Reproduced in d65d616 (13. August)

**Comment by paramat** [comment]
> signs_lib mod, homedecor's itemframes, digiline's lcd screens, street's matrix screens

These must be using special implementations that are now causing darkness.

**Comment by jastevenson303** [comment]
I have been noticing this sporadically over the various builds as of late.  Don't recall seeing it too often in the last few, though.

**Comment by Thomas--S** [comment]
@paramat I don't think that the implementations are hacky or special. As far as I know, the place an object at the place of the respective node (sign; itemframe etc.). There is obviously light at this position, but this light isn't correctly applied to the objects there.

**Comment by paramat** [comment]
Ok.
Objects get their light from a position 0.5 nodes above their position, so this light sampling point may be inside the nodes above, therefore dark, we could move this point down to 0.49 above the object.

**Comment by Fixer-007** [comment]
Can't reproduce :/ Can someone bisect it?

**Comment by paramat** [comment]
Being above or below y = 0 may have an effect, since the light sampling point is right on the edge of the nodes above. This may also make it unreliable to reproduce.

**Comment by paramat** [comment]
A way to test is to alter that code above from 0.49 to 0.51 and see if that switches darkness.

**Comment by paramat** [comment]
It's genericCAO instead, but fix is the same.

**Comment by Thomas--S** [comment]
Thanks for your efforts. I don't have the time at the moment to open a PR with your suggested fix, so I'd really appreciate it, if you could open a PR yourself, paramat. Thanks!

**Comment by paramat** [comment]
Oops yes this was my fault https://github.com/minetest/minetest/commit/238d752fa3021fa7294a4df79bfa0b8a46f4a018 i should have checked for player to add an offset.
