### ISSUE TITLE
formspec label: Add border parameter

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6271]
![img](https://my.mixtape.moe/uvkqll.png)
People who want to show text to players, e.g. server rules, currently use `textarea` because there's no automatic line breaking in labels.
l'd like to have an optional parameter which sets the right boundary. If text exceeds this boundary, a line break is added before the last word (except if it's also the first word).
If this parameter is omitted, the boundary is set to the right end. If the label is added in a container, the right end is the right end of the container, else the right end is the right end of the formspec.

**Comment by SmallJoker** [comment]
Possible duplicate: #3807

**Comment by HybridDog** [comment]
Adding another formspec element for long text is better l guess. It's a duplicate, when l searched for formspec, l didn't find that. https://github.com/minetest/minetest/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20formspec%20
