### ISSUE TITLE
Warning about unused variable in mainmenumanager.h

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#6275]
Just starting seeing a few of these pop up, lately:

```
In file included from /home/mtango/minetest/src/client/inputhandler.cpp:23:0:
/home/mtango/minetest/src/mainmenumanager.h: In member function ‘virtual void MainMenuManager::createdMenu(irr::gui::IGUIElement*)’:
/home/mtango/minetest/src/mainmenumanager.h:51:26: warning: unused variable ‘i’ [-Wunused-variable]
   for (gui::IGUIElement *i : m_stack) {
                          ^
```
EDIT: Changed to code block

**Comment by nerzhul** [comment]
it happens only in release mode it seems, it's due to the internal assert which is stripped in release mode

**Comment by paramat** [comment]
Yes i had lots of those during build recently.

**Comment by nerzhul** [comment]
i will fix it in the next (and last) cleanup PR

**Comment by Ekdohibs** [comment]
Fixed by https://github.com/minetest/minetest/commit/1c1c97cbd1d7913ac12bf550ec02c97f843a0fd3

**Comment by nerzhul** [comment]
@Ekdohibs i think i forgot it, i should re-test a release

**Comment by nerzhul** [comment]
oh i fixed it :) ignore my previous comment
