### ISSUE TITLE
Always appearing warnings when creating new worlds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6276]
When creating a new world at default settings in 0.4.16, Minetest Game, Minimal development test or even an empty subgame (no mods), I reliably get these warnings in my `debug.txt` (in no particular order):

`"WARNING[Main]: NodeDefManager: Ignoring CONTENT_IGNORE redefinition"`

`"WARNING[Main]: BanManager: creating /home/user/.minetest/worlds/myworld/ipban.txt"`

**Comment by SmallJoker** [comment]
1) PR #4393 is pending
2) Fixed in e53d8a7

**Comment by paramat** [comment]
Since the 'Ignoring CONTENT_IGNORE redefinition' is harmless let's just move that to infostream too. Simplest solution.

**Comment by SmallJoker** [comment]
#4393 merged
