### ISSUE TITLE
Wireframe mode stays enabled when debug priv got revoked (new HUD flag?)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6288]
In MT 0.4.16, the wireframe mode stays enabled after you lose the debug privilege.

How to reproduce:

* Step 1: Player X has the debug privilege, enables wireframe mode
* Step 2: Someone revokes the debug prilege from Player X

Expected: Player X loses debug privilege and the debug screen mode is automatically disabled.
Actual result: Player X loses debug privilege, but the wireframe mode stays enabled.

**Comment by paramat** [comment]
Perhaps wireframe should be a HUD flag? Then when it gets disabled the clientpackethandler.cpp code can switch F5 mode.

**Comment by paramat** [comment]
It seems likely we will have a new HUD flag for whether sensitive information (position/direction/pointed node) is visible to a player, so a HUD flag for wireframe, which is also F5, makes sense.
I'm inspred to work on this, any objections?

**Comment by Wuzzy2** [comment]
I'm not sure about HUD flag for wireframe, because this mean in order to strip the wireframe viewing privilege from a player, you now need a mod and can't just do `/revoke Player debug` like now.

HUD flags for the other things (position, etc.) do make sense, however.

**Comment by paramat** [comment]
> this means in order to strip the “wireframe viewing privilege” from a player, you now need a mod and can't just do /revoke Player debug like now.

That's too bad, if HUD flags is the best way to do it then people will have to use a mod.
Wireframe should have been a HUD flag from the beginning, and zoom should not have been a priv.
We're moving some things out of privs due to the reported problems with using privs to control things.

**Comment by Wuzzy2** [comment]
No longer an issue in 5.5.0-dev due to some improvements to debug screen.
