### ISSUE TITLE
Slippery problems with slabs and stairs

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6291]
I did some testing of slippery on various ice blocks on 1c1c97cb engine and game and found that slippery does not work in many cases, screenshot will explain better this pattern:
![default](https://user-images.githubusercontent.com/16494741/29495106-b9b71d24-85c0-11e7-8a98-cd183d6de37d.png)

**Comment by paramat** [comment]
Does slippery fail only at slab edges or for the whole slab?

**Comment by Fixer-007** [comment]
>Does slippery fail only at slab edges or for the whole slab?

Whole slab

**Comment by paramat** [comment]
```
v3s16 LocalPlayer::getStandingNodePos()
{
	if(m_sneak_node_exists)
		return m_sneak_node;
	return floatToInt(getPosition() - v3f(0, BS, 0), BS);
}
```
Slippery uses this to get the node stood on, but BS below is actually below the slab, it should look at a point 0.4f * BS below.
If you place a ful ice node below the ice slab it might work.

**Comment by Fixer-007** [comment]
>If you place a ful ice node below the ice slab it might work.

Yes, it is. Also, stopping of slippery on ice edge kinda not good for gameplay :(

**Comment by bendeutsch** [comment]
I see that `updateSneakNode` and `getFootstepNodePos` use 0.05 * BS below the player's feet, while `getStandingNodePos` uses 1.0 * BS (as above). Does anyone know why this is?

**Comment by paramat** [comment]
No idea, a small distance below would be best to cope with thin slippery slabs.

**Comment by paramat** [comment]
`getStandingNodePos()` is only used in a very few places, and might be better replaced with something else. It may be a left over from early MT when everything was a full node.

**Comment by paramat** [comment]
> stopping of slippery on ice edge kinda not good for gameplay

Possibly unavoidable, at the edge there is no longer ice below so no slip.

**Comment by bendeutsch** [comment]
> Possibly unavoidable, at the edge there is no longer ice below so no slip.

We're talking about an ice cliff, right? Not the edge of an ice lake in a flat world. Technically the node below you is then air, even though you're still "touching_ground" according to the collision detection.

Maybe the following could work: if the slippery code detects air, *and* the player is `touching_ground`, check 4 points horizontally around the player and use the minimum "slippery" value. A bit more to code, but you'd slide off an ice cliff, at which point you'd be governed by `movement_acceleration_air`, which is ⅔ of non-slippery ground acceleration? Quite high, at least.

**Comment by Fixer-007** [comment]
Yes, I was talking about icy cliff...

**Comment by bendeutsch** [comment]
A new commit in PR #6256 deals with the not-sliding-off-a-cliff problem, following the above idea.

**Comment by Fixer-007** [comment]
I've retested with newest minetest, main problem is fixed, "not-sliding-off-a-cliff problem" seems to be fixed, but there is still movement opposition just near edge of the block. Jump on/of the slippery surface is very strange:
![whoiselvis](https://user-images.githubusercontent.com/16494741/29821546-fe2bbd9a-8cd0-11e7-9cd2-dc0b649a3ec2.gif)

**Comment by paramat** [comment]
Jumping is weird because when above the ice you are no longer 'slipping' so come to a sudden halt.

**Comment by bendeutsch** [comment]
Yeah, I stumbled over that too. Turns out that the max acceleration in air is an independently defined value, currently half the acceleration of solid ground. I guess it's that strong to support parkour-like jumping? Anyway, can't be fixed easily, I'm afraid.

**Comment by paramat** [comment]
Issue fixed.
