### ISSUE TITLE
get_objects_inside_radius also catches remove()d items

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6294]
When you get objects with get_objects_inside_radius, you currently also catch those which have their remove() executed.
When l reproduced the bug, get_objects_inside_radius got the removed object multiple times. (e.g. 4 times the error message `item_drop found removed item`)

The item double pick up bug was fixed by setting a field in the object data which indicates that it's removed, in this case the item it carries was set to an empty string.
But this fix is a workaround.

Note: The bug belongs to get_objects_inside_radius. It isn't caused by player asynchronicity. When a player clicks an object which was removed server-side, the on_punch of the removed object doesn't get executed, see below.

How to reproduce:
* Install my item_drop mod and checkout to the double_pick_up_log branch https://github.com/HybridDog/item_drop/tree/double_pick_up_log
* Insert this code in builtin/game/item_entity.lua:230
```lua
		if self.itemstring == "" then
			minetest.log("error", "player punched removed item")
		end
```
* Start minetest with the mod enabled, drop an item, wait a bit, then walk to the item and simultaneously punch it that item_drop and you pick it up at the same time (reproduction of double pick up bug)
* In chat, you should see where it finds remove()d objects

**Comment by Wuzzy2** [comment]
I can confirm this in 0.4.16.

**Comment by paramat** [comment]
Wuzzy you man 0.4.16 stable?

**Comment by Ekdohibs** [comment]
I'd just like to say that although I consider this a bug as well, it is documented: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3275
I believe that if it is possible, object removal should be instantaneous however, and not after returning from Lua.

**Comment by HybridDog** [comment]
Ekdohibs, currently minetest.get_objects_inside_radius is the only way to properly get objects in lua (don't know about getting attached objects), isn't it?

**Comment by Ekdohibs** [comment]
I think it is, yes.
