### ISSUE TITLE
Selecting empty slot on hotbar after changing hand causes client to segfault

### ISSUE THREAD

**Issue by micheal65536** [minetest/minetest#6298]
After changing the player's hand item, by changing the "hand" inventory slot as per #2827, if an empty slot on the hotbar is selected the client segfaults. The server does not seem have any problems.

Using Minetest client and server version 0.4.16.

**Comment by paramat** [comment]
0.4.16 stable?

**Comment by micheal65536** [comment]
I think so, it's the one from the stable Ubuntu PPA.

**Comment by Ekdohibs** [comment]
I think it has already been fixed by https://github.com/minetest/minetest/commit/7786521f151b6006656768fdd308f1d7e1635645, which was merged very shortly after the release of 0.4.16. Could you check it indeed fixes your problem, if possible, please?

**Comment by micheal65536** [comment]
I tested it with 7786521 and the issue does indeed no longer occur. I assume from the contents of 7786521 that the workaround is to define `tool_capabilities` for my custom hand item?

**Comment by Ekdohibs** [comment]
@micheal65536 Yes, this should work as a temporary fix.
