### ISSUE TITLE
Minetest exiting hangs when a mod executes an infinite loop

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6299]
If you make a mod execute an infinite loop and then press ESC and exit the game, it says Shutting down…, the frame isn't updated and you can't quit. To stop it you need to manually kill minetest e.g. via ctrl+c.
Please allow aborting this hang after a second by pressing ctrl+q in minetest.

**Comment by SmallJoker** [comment]
You can't stop Lua without killing the parent process. Upstream issue.
The only solution to prevent hardloops is by modifying its source code, which makes it quite much slower in executing: http://lua-users.org/lists/lua-l/2011-06/msg00513.html

**Comment by HybridDog** [comment]
l think that ctrl+q should kill the parent process.

**Comment by dsohler** [comment]
So Lua should be executed as easy killable child process instead of blocking the parent.

**Comment by nerzhul** [comment]
@dsohler it's not possible as Lua calls minetest core engine, child process  means separate memory

**Comment by dsohler** [comment]
Oh the wonders of IPC :smile:

But I guess IPC will be a "non trivial" "engine change".

**Comment by nerzhul** [comment]
non trivial non portable change

**Comment by dsohler** [comment]
The API should be callable from outside the thread and outside the process. Then multi-threading or multi-processing would be possible.

**Comment by rubenwardy** [comment]
I don't see this as an issue worth fixing.

**Comment by nerzhul** [comment]
definitively no, and this will trigger a huge core performance rearchitecture and performance due to locking penalty

**Comment by dsohler** [comment]
Too bad we'll never have multi-threading in MT :cry:

**Comment by nerzhul** [comment]
MT is multithreaded, Lua cannot be multithreaded

**Comment by dsohler** [comment]
Then have Lua run in one thread and have the API in another thread providing a proper interface for communication.
