### ISSUE TITLE
On systems with lower ram, minetest lags going large distances in flat mapgen, uses up most of the system ram and swap space

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#6321]
**(updated)** In game using flat mapgen I found that after going large distances, game starts lagging as it uses up most of sytem ram and swap space, frame rate dropping down. Mapgen that were used when testing is flat, also I was unable to reproduce the bug using default mapgen v7.
Also some times it takes a lots of time to close the world, by almost freezing the system, unable to run anything (such as task manager) until it stops doing that. Might cause out of memory crash too. 
~I suspect that after a while, the areas where the player isn't in are not unloaded properly and quickly enough, if unloaded at all, causing lag (memory leak) when that happens.~ It appears that default  config value for `client_mapblock_limit` (5000) is too large for my system, therefore causing lag
Log (debug.txt) doesn't show anything special, only casual information like server action logs, no information about lag, etc.
Tested latest commit, and latest ppa build, whitch was behind at the time of testing, both affected.

**Comment by HybridDog** [comment]
Is the lag similar to the lag when forgetting to disable full view range?

> by almost freezing the system

What's your operating system?

**Comment by juozaspo** [comment]
@HybridDog full view range not enabled, viewing distance 100 (default) , but it's still laggy, low framerate. 
OS: Linux, Memory: 2 GB
Display: NVidia Geforce 210, Driver version 340.102
Screenshot with debug:
![screenshot_20170827_094225](https://user-images.githubusercontent.com/6626242/29747937-ebf4152e-8b12-11e7-9dbb-2218dcad1cbc.png)
Notice big dtime_jitter

**Comment by HybridDog** [comment]
l run about 9000 nodes and couldn't reproduce the lag. Maybe l have too much memory.

**Comment by HybridDog** [comment]
l run about 9000 nodes and couldn't reproduce the lag. Maybe l have too much memory.
#
I've tested it a second time and had a look at memory usage. `pmap -x $(pgrep minetest)` told that minetest uses ca. 2.8 GB memory,  1.6 GB RSS and 1.6 GB dirty

**Comment by juozaspo** [comment]
It doesn't happen instantly if you walk about 1000 blocks on my system. It happens if i go large distance, turn, go another large, turn again, repeat untill I go back to original location where the lag's about to happen near the end.

**Comment by juozaspo** [comment]
Game just crashed recently (out of memory), fast run disabled. last few lines of dmesg output:
```
[ 8793.481663] Out of memory: Kill process 6564 (minetest) score 894 or sacrifice child
[ 8793.481676] Killed process 6564 (minetest) total-vm:4853816kB, anon-rss:1778292kB, file-rss:25952kB, shmem-rss:12856kB
```

**Comment by paramat** [comment]
Werd, i'll check the mapgen flat code, running any mods?

**Comment by juozaspo** [comment]
@paramat, I don't have any mods, view range all is off, 2 GB is my actual system ram. This time i'm writing from mobile since I couldn't access from desktop as game was just hung up doing shutdown and closed a moment ago :/

**Comment by Fixer-007** [comment]
Out of memory error, you can tweak some settings to reduce memory usage in minetest.conf

**Comment by juozaspo** [comment]
Total ram is 2 GB, **/proc/meminfo** contents proves it.
```
MemTotal:        2045580 kB
MemFree:          620052 kB
MemAvailable:     858108 kB
Buffers:           42992 kB
Cached:           340880 kB
SwapCached:        44056 kB
Active:           778664 kB
Inactive:         487292 kB
Active(anon):     571116 kB
Inactive(anon):   336880 kB
Active(file):     207548 kB
Inactive(file):   150412 kB
Unevictable:          32 kB
Mlocked:              32 kB
SwapTotal:       2097148 kB
SwapFree:        1886220 kB
Dirty:              4484 kB
Writeback:             0 kB
AnonPages:        842432 kB
Mapped:           239128 kB
Shmem:             25912 kB
Slab:              53444 kB
SReclaimable:      23452 kB
SUnreclaim:        29992 kB
KernelStack:        5736 kB
PageTables:        26896 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     3119936 kB
Committed_AS:    3098556 kB
VmallocTotal:   34359738367 kB
VmallocUsed:           0 kB
VmallocChunk:          0 kB
HardwareCorrupted:     0 kB
AnonHugePages:    129024 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      159232 kB
DirectMap2M:     1937408 kB
```

**Comment by juhdanad** [comment]
Map block meshes are not deleted, even if you are not near them. I suspect that they eat up memory.

**Comment by paramat** [comment]
Ok 2GB total is small, you certainly have to reduce this number `client_mapblock_limit = 5000`, try 1000 and see if you can reproduce.

**Comment by juozaspo** [comment]
tried 1000, still reproducing after going thousands of blocks starts lagging.

**Comment by juhdanad** [comment]
Do you use shaders? It affects the map block memory usage, with shaders enabled memory consumption is less. Can you confirm that if you use shaders, you can go further?

**Comment by juozaspo** [comment]
**update:** doesn't lag as it lagged when I posted the previous post. the browser was open in background. also shaders are disabled. so I can go to the 10000 in both directions (x,z) easily in one go. Only problem the default for `client_mapblock_limit` is 5000 instead of determined by current system ram (if not set manually)

**Comment by paramat** [comment]
This seems obviously an issue with setting a suitable client mapblock limit.
Auto setting the limit is not possible because how would MT know how much RAM the user wants to be used? There is also not a 'mapblock number' to 'RAM use' conversion because mapblocks can be air with no mesh or super-complex combinations of nodes and gaps with a complex mesh.

**Comment by paramat** [comment]
For the issue of auto-limiting mapblock number according to system RAM, i think there's an issue for htis already, i'll look.

**Comment by Fixer-007** [comment]
Yes, I was advocating this too, especially for 32bit builds and low RAM users. If you vrange 240 and just walk you can bypass 32 bit process limit and crash. If you have system with 2GB with OS and Firefox opened, there is little RAM for minetest.
