### ISSUE TITLE
Unknown itemgroups broken?

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#6329]
Currently it seems that unknown groups in minetest.register_item (and its subtypes e.g. minetest.register_node) won't create item ItemStack definitions for some reason. For example:
- upon right-clicking with items (including wieldhand and nodes, and even vanilla furnace copied code) with unknown groups (even existing ones like `not_in_creative_inventory = 1`) the game crashes into gray screen with [this report](http://codepad.org/OxBdzaHS).
- node timers on nodes with all groups except `cracky`, `choppy` and the like simply output
```
2017-08-28 09:20:11: ERROR[Server]: Item "research:aspect_turbine_on" not defined
```
and stop working.
I am using Minetest 0.4.16 on ArchLinux.

**Comment by paramat** [comment]
0.4.16 stable so line 352 is marked here:
```
function core.item_place(itemstack, placer, pointed_thing, param2)
	-- Call on_rightclick if the pointed node defines it
	if pointed_thing.type == "node" and placer and
			not placer:get_player_control().sneak then
		local n = core.get_node(pointed_thing.under)
		local nn = n.name
		if core.registered_nodes[nn] and core.registered_nodes[nn].on_rightclick then
			return core.registered_nodes[nn].on_rightclick(pointed_thing.under, n,
					placer, itemstack, pointed_thing) or itemstack, false
		end
	end

	if itemstack:get_definition().type == "node" then ******************************************
		return core.item_place_node(itemstack, placer, pointed_thing, param2)
	end
	return itemstack
end
```

**Comment by MineWitherMC** [comment]
It seems to be my fault: I was accidentally filtering minetest.registered_items table without copying it first. Sorry for this issue.
