### ISSUE TITLE
Drop dstack from engine

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6335]
Dstack is not very useful, it's used in minor parts of the code and don't show real stack trace, just what it can collect, near the nether.

I suggest to remove dstack support from core engine

**Comment by nerzhul** [comment]
@minetest/team-minetest please vote :)

**Comment by paramat** [comment]
Neutral.

**Comment by SmallJoker** [comment]
I'm neutral on this topic too.

**Comment by nerzhul** [comment]
Thanks for your answers, PR is #6346
