### ISSUE TITLE
Multiple classes in cpp/h files

### ISSUE THREAD

**Issue by Anth0rx** [minetest/minetest#6336]
After getting a little bit more familiar with the codebase I saw multiple cpp/h files where multiple classes were defined/implemented.
I think this is very confusing. I would use one cpp/h file per class and rather use an appropriate directory structure to arrange them logically. This would result in a way better readability.

What is your opinion on this?

**Comment by sfan5** [comment]
This is not Java, enforcing one-file-per-class without exceptions is harmful.

**Comment by rubenwardy** [comment]
> This is not Java, enforcing one-file-per-class without exceptions is harmful.

Minetest doesn't do this enough, however

**Comment by nerzhul** [comment]
Sometimes there are too many classes or big classes in MT, but yes it's not java, only java enforce a such thing. Moving code just for moving without doing any more refactor is a little bit useless and make the diff more difficult to follow, thanks anyway

**Comment by Anth0rx** [comment]
Don't you need one-class-per-file for unit tests, too? And even when the files remain the way they are I'm convinced that properly structuring them would enhance the overall readability.

What do you think?

**Comment by nerzhul** [comment]
i know it's difficult for a new member to understand minetest as minetest has age weight, but we are slowly refactoring and improving this, look at minetest 0.4.9 tree to see the differences :)

**Comment by Anth0rx** [comment]
Is there a plan for those changes? Maybe I can help with some of them. Since I am still a novice programmer, what would you recommend to begin with?

**Comment by nerzhul** [comment]
there is no plan to just move code for clarity, we move code when we refactor some classes for functional purposes generally, for exemple, recently i moved the ClientEvent objects to client/clientevent.h due to a refactor on the event handling in Client

**Comment by Anth0rx** [comment]
Ah okay,  I understand. But wouldn't it be suggestive to do this all in one go? Or at least I don't see any points disapproving that.
