### ISSUE TITLE
Drawtype "plantlike_rooted" is undocumented

### ISSUE THREAD

**Issue by Ekdohibs** [minetest/minetest#6350]
It was introduced in https://github.com/minetest/minetest/pull/5748, but has no documentation at all.

**Comment by paramat** [comment]
@numberZero

**Comment by paramat** [comment]
#6434 partially documents this, just needs a little extra text.

**Comment by paramat** [comment]
I'll do it.

**Comment by paramat** [comment]
#6437 merged.

**Comment by numberZero** [comment]
Thanks
