### ISSUE TITLE
If a formspec is shown get_player_control() doesn't work.

### ISSUE THREAD

**Issue by cx384** [minetest/minetest#6353]
get_player_control() doesn't work if a formspec is shown.
Maybe this isn't a bug, but it would be nice to have this feature.
For example if you want to execute two different things depending on holding shift on button press.

**Comment by DS-Minetest** [comment]
If this is added it will be also necessary to know if the player has a formspec opened. Else eg. there would be no way for minetest_game/mods/player_api to avoid setting the player animation while the player has a formspec opened.

**Comment by rubenwardy** [comment]
I'm not sure how this will work, due to keybinding. Sneak doesn't/shouldn't exist whilst in the formspec as it's an in game control.

Maybe controls should be sent as part of the formspec escape; but: bindings.

**Comment by sorcerykid** [comment]
What if there was a fourth parameter to the on_player_receive_fields callback that is a table of the key states (analogous to the get_player_control function). That should avoid any conflict with in-game controls, since it is formspec specific and not concerned with the state of the player object.

**Comment by rubenwardy** [comment]
duplicate of #6768
