### ISSUE TITLE
Loop in step sound while flying

### ISSUE THREAD

**Issue by lupoDharkael** [minetest/minetest#6356]
If you have free_move enabled and keep pressing Shift (without moving), you can hear the footstep sound in loop. The sound should be heard only when you reach the floor.

**Comment by DS-Minetest** [comment]
Related: #1460

**Comment by paramat** [comment]
> If you have free_move enabled and keep pressing Shift (without moving)

I see, while in contact with the ground.
Duplicate of #1460 let's make that one the issue for all cases of footstep repeats.
