### ISSUE TITLE
New "Ready for review" PR label

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6362]
There should be a label marking PRs as ready for review. It would be added when a PR has new code submitted and the author requests reviews. It would be removed when either the PR has two approvals, or there is a code review requesting changes to the code. When the author submits new code and requests more reviews, the label can be readded.

This label would make it easier to find PRs to review if a core dev is looking for one.

**Comment by sfan5** [comment]
Every PR without a `WIP` label should be ready for review, no need for a separate label.

**Comment by raymoo** [comment]
Can you filter PRs by absence of a label?

**Comment by rubenwardy** [comment]
I believe you can put a minus before the label keyword

**Comment by raymoo** [comment]
Ah, ok. Still, the WIP label differs from my idea in that it isn't usually reapplied as soon as there is a disapproving review.

**Comment by paramat** [comment]
WIP doesn't mean there is a disapproving review.
I use WIP to mean 'not ready for review', so an extra labal seems redundant.

**Comment by paramat** [comment]
This extra label seems a little redundant due to having WIP.

**Comment by raymoo** [comment]
@paramat As far as I can tell, the WIP label is not added to almost-done PRs that have some code style changes requested. The ideal situation is that a core dev looking for PRs to review can just bring up a list of PRs that will benefit from a review and then work through that list.

**Comment by paramat** [comment]
3 disapprovals and is somewhat redundant, many do use WIP to mean 'not yet ready for review'.
The devs will add a label if they feel it is useful, and we will keep this suggestion in mind.

**Comment by raymoo** [comment]
@paramat 
>we will keep this suggestion in mind

The "Won't add" label says otherwise (which is fine by me)

**Comment by paramat** [comment]
> I believe you can put a minus before the label keyword

This works:
is:open is:pr -label:WIP
