### ISSUE TITLE
Separate code reviews and feature reviews

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#6364]
Minetest's PR approval system has two primary purposes: to ensure good code quality, and to ensure that proposed features fit the vision for Minetest; currently an approval means approving both the code and the feature. Separating these concerns would make the approval process more amenable to division of labor.

There should be two levels of users with approval authority:
 - Code reviewers: These users can give code reviews and approve the code implementing the feature, but cannot approve the feature itself for inclusion into Minetest. This group can be bigger than just the core developers, since it is easier to see whether a contributor has a good grasp of coding style than to trust them to determine the direction of Minetest.
 - Core developers: These users can approve both code and the feature as described in the PR, though they are not required to review both simultaneously. They can veto code approvals from code reviewers.

The approval process for a new feature would be changed to require two passing code reviews and two feature approvals. A bug fix could just require code reviews.

Currently there is also an informal requirement that somebody test a PR before it is approved by a core dev. Maybe a tester approval should also be required?

**Comment by paramat** [comment]
Code reviewers also need an understanding of the game, so would be core devs already.
Non-core devs can already review code and point out errors.
> A bug fix could just require code reviews.

Bug fixes need core dev approval, code review by a non-core-dev is not good enough.
Testing is combined into the existing approvals.

This would make review more complex, with more labels, and i don't see justification for doing so.
:-1:

**Comment by rubenwardy** [comment]
It's rare for non-coredevs to review anyway, except for a few members that should probably become core devs anyway :D

**Comment by nerzhul** [comment]
also, just for the speed note, this dev cycle has, now, as many changes as the whole 0.4.16 cycle, i think we have more speed than before :p

**Comment by raymoo** [comment]
@paramat I argue that separating the reviews would bring benefits even if the pool of code reviewers stays limited to core devs, because a core dev might still want to do only one part of the review. On one end, a core dev might not care for or against a feature implemented by a PR at all, but they would still be able to code review it and have it count towards approval. On the other end, a reviewer might not have time to review a possibly large code change, but may approve or disapprove of the feature itself.

**Comment by paramat** [comment]
> a core dev might still want to do only one part of the review. On one end, a core dev might not care for or against a feature implemented by a PR at all, but they would still be able to code review it and have it count towards approval. On the other end, a reviewer might not have time to review a possibly large code change, but may approve or disapprove of the feature itself.

We do all this already, and state 'i approve concept' or 'code is ok but not sure about concept'.
Your suggestions in the first post are just lots of extra unnecessary complexity when dev work is already very hard work, and we're not going to create a new level of dev, it's core dev or not.
Closing due to lack of support and disapproval.

**Comment by raymoo** [comment]
I've never seen one core dev's code review and another core dev's feature review add up to one approval.
