### ISSUE TITLE
Minor optimization

### ISSUE THREAD

**Issue by lupoDharkael** [minetest/minetest#6368]
There are several constructors initializing members in the constructor's body, they should be initialized in the initialization list to prevent double call of the constructor in some situations or useless memory copy.

Some places:
https://github.com/minetest/minetest/blob/master/src/mapgen_carpathian.cpp#L111
https://github.com/minetest/minetest/blob/master/src/mapgen_flat.cpp#L86
https://github.com/minetest/minetest/blob/master/src/mapgen_fractal.cpp#L87
https://github.com/minetest/minetest/blob/master/src/mapgen_v5.cpp#L85
https://github.com/minetest/minetest/blob/master/src/mapgen_v6.cpp#L150
https://github.com/minetest/minetest/blob/master/src/mapgen_v7.cpp#L133
https://github.com/minetest/minetest/blob/master/src/mapgen_valleys.cpp#L129

**Comment by nerzhul** [comment]
@lupoDharkael you are right, can you provide a PR ?

**Comment by lupoDharkael** [comment]
@nerzhul sure!

**Comment by lupoDharkael** [comment]
solved in #6371
