### ISSUE TITLE
Change default keybindings of camera, minimap, print stacks

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6374]
I suggest to change the defaults to better reflect the frequency in which you need them:

* Camera: C (popular choice in many games, near WASD)
* Minimap: V (just near WASD)
* Print stacks: F7 (rarely used)

My rationale is that camera and minimap are **essential** game features which you need often and the function keys are just too inconveniently placed.
Print stacks is used very rarely so it should be moved to the function keys so players don't press it by accident and get annoying chat spam. F7 because it follows F6 (profiler). :-)

This suggestion is negotionable, I am open to comments. :-)

**Comment by paramat** [comment]
> Print stacks is used very rarely so it should be moved to the function keys 

I agree.

What is 'Camera', first / third person view?

**Comment by Wuzzy2** [comment]
Camera is the key called “Camera” (`keymap_camera_mode`). Duh!

**Comment by paramat** [comment]
Ok current F7, was checking you didn't mean 'toggle camera update'.

**Comment by Megaf** [comment]
So as we were talking on IRC.
IMHO,
m for mute or map, both work.
tab for minimap
print screen could be F7 yes, it's logical if the button is not used yet.

**Comment by Wuzzy2** [comment]
Tab for minimap is fine.
OK, so do we agree on this?:

- C for camera
- M for mute (no change)
- Tab for minimap
- Print stacks on F7

**Comment by paramat** [comment]
Hmm, actually i would be ok with this with one change:
V for minimap is far better than TAB.
As you suggested originally above and in https://github.com/minetest/minetest/issues/8636#issuecomment-582381201

Place your hand in the default position and notice how much easier it is to hit V with your thumb without moving the fingers from WASD. Shift-V is also easy with little finger and thumb. Shift-TAB is very awkward as they are vertically above each other.

-1 for minimap being TAB.
+1 if minimap is V.

What do other core devs think?

**Comment by Wuzzy2** [comment]
@paramat: Are you OK with:

* Camera: C (popular choice in many games, near WASD)

as well?

Note my “print stacks” suggestion is obsolete now, the default key binding for this has been removed.

**Comment by paramat** [comment]
Yes C for camera is fine for me.
Lets try to get a consensus of core dev opinions on this first to avoid PR grief.

I'm ok with:
C for camera.
V or M for minimap, but prefer M.

I prefer M because i cannot see why minimap needs to be rapidly accessed, it is something you turn on and leave on for a while, and occasionally cycled. I would prefer that keys close to WASD are prioritised for control / rapid-access uses. M for minimap is also easier to remember.

I disapprove of TAB for minimap.

**Comment by Wuzzy2** [comment]
Note: If M is for minimap, then the mute key must be re-mapped.

**Comment by Wuzzy2** [comment]
I vote for:

* Camera: C
* Minimap: V
* All other keys: No change

**Comment by LoneWolfHT** [comment]
To copy over my post in the other issue:
I do M for my minimap, V for autoforwards, and N for mute
I guess C might work for the camera, I tend to keep it just in reach of my left hand (f7) so I don't accidentally click it, which would be disastrous when in the middle of PvP

**Comment by paramat** [comment]
Aargh i forgot about mute, V is ok for me.
