### ISSUE TITLE
Item entity may become hand after merging

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6379]
It is possible for item entities to be the hand. This sometimes happens when two item entities merge.

How a dropped hand looks like:
![](https://user-images.githubusercontent.com/29333817/29997379-c08cfda2-9011-11e7-90be-3a8f1b050b70.png)

How to reproduce:
1. Create a flat world with seed 0 in Minetest Game
2. Activate the test mod below
3. Start the game
4. Go towards X=0, Z=0 to watch items dropping
5. Now go away from the center and look at the falling items
6. As soon the falling items disappear, go closer again until the items are visible again
7. Repeat the last 2 steps a couple of times
8. Go to the items and collect the wheat seeds

With a bit of luck you will now find a hand. Repeat steps 4-8 as often as you like.

```
-- Spawn a wheat seed item entity at (0,15,0) every second
local t = 0
minetest.register_globalstep(function(dtime)
        t = t + dtime
        if t > 1 then
                minetest.add_item({x=0, y=15, z=0}, "farming:seed_wheat")
                t = 0
        end
end)
```

Successfully reproduced in Minetest 0.4.16 *and* 04cf7a0d8140c5a938a57ac657f4cd282658a1d1!

## Analysis
Possible cause of the problem: In `builtin/game/item_entity.lua`, `try_merge_with` sets `itemstring` to `""` before removing it. However `remove()` doesn't really remove the item and the `on_step` function is still called a couple of times before the item is actually removed (this is another bug which I believe is reported elsewhere, I just can't find it now. Correct me if I am wrong). Now consider this: What if an item entity gets deactivated *just* before the item is *really* deleted? In that case, the itemstring is set to `""` and as soon the entitiy is `on_activate`d again, it will load the `itemstring` of `""`, which is then fed into `set_item` and boom! We have a dropped hand.
This is just a guess because I don't understand the inner workings of the item activate/deactivate/remove logic.

I'm not sure what would be the ideal bugfix for this.

**Comment by kingoscargames** [comment]
I did change the hand texture when i made that screenshot though.

**Comment by kingoscargames** [comment]
After blowing up more than 5000 tnt (i dont know why) and i restarted the game because i had less than 1 fps  there were like 50 hands on the ground.

**Comment by SmallJoker** [comment]
Can this still be reproduced with https://github.com/SmallJoker/minetest/commit/4c258d3 ?

**Comment by DS-Minetest** [comment]
I suggest adding to `__builtin:item`'s `on_ activate`
```lua
if self.itemstring == "" then
	self.object:remove()
	return
end
```
.

**Comment by sfan5** [comment]
I couldn't reproduce the issue local but I found your hypothesis to be accurate.
Could you re-test with my PR (#6414) applied?

**Comment by HybridDog** [comment]
> the on_step function is still called a couple of times before the item is actually removed

ln my experience it isn't called for remove()d items.

> I don't understand the inner workings of the item activate/deactivate/remove logic.

Documentation is missing.

**Comment by Wuzzy2** [comment]
I can confirm the bugfix.
