### ISSUE TITLE
Remember last selected slot on the hotbar

### ISSUE THREAD

**Issue by 22i** [minetest/minetest#6383]
You have 11th slot choosen on your hotbar
![11](https://user-images.githubusercontent.com/17874916/30133543-93bccffa-9354-11e7-8f49-90170baa766d.png)

Then you press `escape` - `Exit to Menu` and `Play Game`
![1](https://user-images.githubusercontent.com/17874916/30133750-49a2e5e8-9355-11e7-9aa1-f6d255ddc51c.png)
After rejoining the game your selected item always goes back to first slot.

i am requesting for an option in the settings so that the game remembers last selected slot on the hotbar.

**Comment by rubenwardy** [comment]
You could do this using a mod. I don't see this being useful for many other subgames

**Comment by 22i** [comment]
> Are there any other usecases for this?

 each login you could have different slot selected

mob changes your active hotbar slot to some other

**Comment by paramat** [comment]
I guess that the data stored for a player between sessions has to be prioritised, and hotbar selection is a low priority.
In fact it seems desirable that it resets to 1 each time you enter a world, as you would have your most useful or critical item there, like a weapon, in that case remembering hotbar slot would be undesirable.
So sorry but i am :-1:

**Comment by Wuzzy2** [comment]
I second this feature request. It's annoying when the slot resets to 1 every time.

But it's not very important to me.

**Comment by rubenwardy** [comment]
I don't think this is actually very useful, given that disconnecting-reconnecting immediately is comparably rare unless you're developing, and scrolling isn't very difficult. The majority of your time is spent in game anyway - so it's an extra packet for not that much.

**Comment by SmallJoker** [comment]
Not against the idea itself - but this can be implemented in any HUD mod easily, just like the inventory slot width as shown in OP's image.
We offer configurable keys to switch the most used/common inventory slots easily. In-game you'll switch the slots after a few seconds anyway when placing nodes for a building/structure.
:-1:
_My two cents for this bikeshredding topic._

**Comment by SmallJoker** [comment]
Three devs are opposed to this request, which can be realised easily using mods.
