### ISSUE TITLE
Add an option so that when Minetest loses focus the game automatically pauses

### ISSUE THREAD

**Issue by 22i** [minetest/minetest#6384]
There should be an option so that when pressing start to open your operating system start menu, alt-tabing to switch from Minetest to some other program like internet browser or code editor Minetest gets paused.

**Comment by paramat** [comment]
Seems low priority, why not just pause the game? But maybe you can convince me with a good reason?
Otherwise this is unnecessary code and work.

**Comment by rubenwardy** [comment]
I almost think this is a nice quality of life feature. I'd have to see how complicated the code is, however

**Comment by paramat** [comment]
Often i want to switch away from MT and leave it running, to do something else while growing plants or travel with autoforward, so i don't think it's necessarily desirable.
The quality of devs lives matters too :) in the sense of how MT should not be unnecessarily complex.
This is completely unnecessary and only saves a single key press for extremely lazy players.

**Comment by dsohler** [comment]
> Often i want to switch away from MT and leave it running, to do something else while growing plants or travel with autoforward, so i don't think it's necessarily desirable.

Hence an option and not hardcoded behavior.

**Comment by paramat** [comment]
#6401 merged.
