### ISSUE TITLE
Show itemstring of unknown items in inventory

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6389]
Currently, unknown items are just shown as “Unknown Item” in the inventory. I suggest to update this tooltip to include the itemstring, e.g. “Unknown Item (example:some_item)”. This will make debugging easier.

**Comment by dsohler** [comment]
I’d extend it to all item strings when debug mode is enabled.

**Comment by DTA7** [comment]
Would this work too?

**Comment by Ferk** [comment]
Is #6413, when enabled, just adding the itemstring to all items indiscriminately regardless of them being unknown or not?

**Comment by Wuzzy2** [comment]
@Ferk: Sadly, this seems to be the case. This is precisely what I did **NOT** want to happen. Too bad it's already merged, I must have totally missed that PR. :-(

Now players can extract potentially hidden item properties only by a setting. I only meant to have the itemstring added as a fallback. I don't know if the PR even implemented the requested fallback.

It the very least, #6413 should be only allowed to players with debug priv.

@DTA7.

**Comment by Ferk** [comment]
I didn't test it, but it's also possible that the PR doesn't really work for unknown nodes, since they might be showing ":unknown" instead. That's how the unknown item is registered as in core.

https://github.com/minetest/minetest/blob/faad6479defa30dec10cf4394c1da6fdf8f12f19/builtin/game/register.lua#L321-L330

**Comment by DTA7** [comment]
@Ferk @Wuzzy2
What do you mean by itemstring? I used Itemstack.name, as did the fallback before, which seems to be set by register_alias_raw from src/script/lua_api/l_item.cpp, which in turn is used by core.register_alias in builtin/game/register.lua. I think this does not include item metadata.

**Comment by Ferk** [comment]
@DTA7 then there's a problem of terminology.

"itemstring" is the string format in which the ItemStack objects can be serialized/deserialized and it has 4 parts, the last one being the metadata:

https://github.com/minetest/minetest/blob/bd6b90359c654f4c75964755e476a8bfd90114ba/src/inventory.cpp#L58-L70

**Comment by DTA7** [comment]
Oh, I see. Should I make a new pull request?

**Comment by rubenwardy** [comment]
> Oh, I see. Should I make a new pull request?

Yeah, the setting should be called `tooltip_append_itemname"

**Comment by Wuzzy2** [comment]
How exactly is the “name” part of the itemstring called, then? Do we even have a standard term for this yet?

I mean what is `default:apple` from `default:apple 5`?

**Comment by dsohler** [comment]
> How exactly is the “name” part of the itemstring called, then? 

ID?

**Comment by SmallJoker** [comment]
The item name is now shown with #6413, if enabled. This satisfies the conditions of the example in the main issue.
If you want to output the metadata too, it's best to use a mod to convert that into a readable form.
