### ISSUE TITLE
Efficient ways to render layered nodes like default:snow (discuss)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6409]
After a discussion with paramat I learned that the snow in Minetest Game (`default:snow`) renders slowly which was stated as a reason to not use it so much in mapgen v6.

A quick look in wireframe mode or just viewing the nodes from below with noclip mode reveals why: There are 6 faces per snow node, neighboring snow is not combined to a single face at all, like normal full-cube nodes are. The same applies to slabs, too. The bad thing is that all 6 faces appear to be rendered for each single node, even those you can't see. No wonder why paramat was opposed to add tons of snow to v6. :D

What's interesting here is that a snow node is very simple: It's just a single cuboid. It rests on the floor. It spans the full width of a node. I bet this simplicity allows for some serious optimizations.
One optimization would be to never render the bottom, it's completely unneccessary. I'm not sure

The question is what kind of optimizations we could do (discuss).

One idea might be to do some general optimizations for nodeboxes in general, but I don't know if there are any.

Another idea would be to introduce a new drawtype “slablike” or “snowlike” for very simple nodes which are defined as nodes with a cuboid of sidelength 0.5, touching a side of the node (i.e. the bottom) and having a node-defined height `h`.
Now Minetest could optimize rendering all of the slablike nodes with equal height.

These are just 2 ideas, I'm not sure if they are great. This is mainly a discussion issue. Post other ideas on how the poor rendering performance of snow and slabs can be improved.

**Comment by paramat** [comment]
@numberZero 
Nodeboxes have always been slower to render than full cubic nodes, but it became worse recently when smooth lighting was added to them, as far as i know the calculations for smooth lighting on a nodebox are more intensive than for a full cube.

**Comment by NathanSalapat** [comment]
The bottom of snow can't be seen, as removing the node from under it causes it to fall to the ground. Though I suppose a transparent item would allow you to see the bottom. However you'd just end up seeing the top of the nodebox then, which probably wouldn't look too bad. Pine trees I think are where that would be most noticeable.

**Comment by kingoscargames** [comment]
> The bottom of snow can't be seen,

![image](https://user-images.githubusercontent.com/29333817/30318778-56f195e8-97ae-11e7-9abc-d11ec638e4b1.png)

**Comment by DS-Minetest** [comment]
Would it be possible not to render those sides of nodeboxes that totally overlap with the side of the node next to it?

**Comment by C1ffisme** [comment]
I like the idea of a "snowlike" drawtype, perhaps with snow layers added back in using params.

**Comment by raymoo** [comment]
I agree with having a new drawtype for this. With nodeboxes you have to do some tricky checking to see if the faces are covered by neighboring nodes, but with a specialized drawtype you could say something like "if this other snowlike node on the left is taller than me (a param?), then don't render my left face".

**Comment by rubenwardy** [comment]
automatic removal of faces would be better

but load time vs render time

**Comment by raymoo** [comment]
By don't render I meant remove the face.

**Comment by rubenwardy** [comment]
Emphasis on the automatic, it shouldn't need a new drawtype

**Comment by raymoo** [comment]
@rubenwardy Ah, ok.

**Comment by numberZero** [comment]
In terms of meshgen time, nothing of that can help nodeboxes: they still need 8 lighting values (even if only 1 face is seen) vs. 4 for a typical solid node. What can help is lighting calculations caching.
In terms of render time, optimization is possible (theoretically). I suggest adding new `leveled` drawtype; we have glasslike-with-liquid already, this one would be similar but simpler, and would make some mesh optimization possible (like current `solid` nodes).

**Comment by raymoo** [comment]
@numberZero You could just special case nodeboxes that have bottom and side faces exactly 0.5 away from the center.

**Comment by paramat** [comment]
I agree with making 'leveled' a new drawtype, it probably should be instead of being a subtype of nodeboxes.

**Comment by DS-Minetest** [comment]
>Then we can also spell it correctly 'levelled', and deprecate 'leveled' nodebox.

"leveled" is also correct, it's American English. Minetest uses nearly everywhere AE, eg. "color". And "leveled" is shorter which is the most important thing.

**Comment by raymoo** [comment]
Another advantage to a specialized drawtype, if the level is specified as param2, is that you only need one node definition for the different levels.

**Comment by paramat** [comment]
Ahh i didn't know 'leveled' was USA English, that's ok then because generally MT uses USA English and c55 has stated he prefers the more straightforward spellings.

**Comment by DS-Minetest** [comment]
>Another advantage to a specialized drawtype, if the level is specified as param2, is that you only need one node definition for the different levels.

Currently there are leveled nodeboxes which already use `param2`.

**Comment by numberZero** [comment]
> Currently there are leveled nodeboxes which already use param2.

Er, I *certainly* saw that before...

It’s fine to keep it as a nodebox subtype, at least as long as there are connected nodeboxes. The only thing I dislike is that I can’t set the level at, say, exactly 0.5. It would be better would level be ranged {1/64, 2/64, ..., 1} or {0, 1/64, ..., 63/64}, instead of current {0, 1/63, 2/63, ..., 1}. Fortunately that’s easy to fix.

**Comment by raymoo** [comment]
Then you wouldn't be able to have it exactly 0 and 1. Why is 0.5 more important?

**Comment by numberZero** [comment]
not only 0.5, you will also have 0.25, 0.125, 0.75 and other exact pixels. and for 1.0... well, you can use a solid node instead. or don’t use 0.0 at all, it would Z-fight anyway.

**Comment by paramat** [comment]
Wut? The leveled nodebox should certainly be divisable into 64ths. it was coded by proller which explains the sloppiness. That needs changing then.

**Comment by numberZero** [comment]
By the way, liquid-in-glass has the same problem since its appearance in ea6c3835de...

**Comment by paramat** [comment]
I'll change leveled nodebox to 64ths then.
I can't see why we can't use param2 values 0-64 to enable 0 or 1.

**Comment by numberZero** [comment]
Agree. Would `param2` be split as 4:4, high-order part might be useful.
But 2 bits available currently is too little for any practical use IMO.

**Comment by paramat** [comment]
The only use for the remaining bits i can think of is hardware colouring, but as you point out 2 bits is useless.
I think param2 should take values 0-64 and use 7 bits.

**Comment by hecktest** [comment]
This can be solved by improving the mesher to drop triangles inside node, nodebox and leveled AABBs, instead of creating new, broken and redundant drawtypes. Simply drop any triangle that is fully contained (inclusively, <= and >=) by any bounding box other than the triangle's own source box. If a node uses a transparent texture, do not use its boxes for culling.
Fixing this in the mesher would not affect falling nodes at all, as those are removed from the block, rendered as temporary entities, and added again when they land.

I'll just point out that the worst of this issue is not the framerate hit but the video memory cost. Each mapblock necessarily creates a new mesh for itself, and the unseen geometry (sometimes over a half of all triangles) quickly adds up. This can even crash the client if VBOs are on, with no clue to the user regarding the cause.
