### ISSUE TITLE
minetest.get_noiseparams returns nil if noise params were left at default

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6419]
If you call `minetest.get_noiseparams` but the noise params have not been *explicitly* set in the advanced settings / `minetest.conf`, it returns `nil`.

How to reproduce this:

* Delete `mgv6_np_biome` from `minetest.conf` if it exists
* Start Minetest 0.4.16
* Activate the `luacmd` mod and start any world in any subgame
* Enter `/lua print(dump(minetest.get_noiseparams("mgv6_np_biome")))`
    * → Prints `nil` :cry: 

For comparison:
* Go back to advanced settings and change `mgv6_np_biome` in any way
* Repeat the above Lua command
    * → Now it prints out the table of noise params :smiley:

**Comment by paramat** [comment]
Try `minetest.get_mapgen_setting_noiseparams(name)` it's newer.
It may be correct behaviour, because returning 'nil' means there is no setting anywhere so the engine default is used. I guess you are requesting that the default is returned if there is no setting?
In MTG i have to 'get' or use the default:
```
-- Get setting or default
-- Make global for mods to use to register floatland biomes
default.mgv7_floatland_level =
	minetest.get_mapgen_setting("mgv7_floatland_level") or 1280
default.mgv7_shadow_limit =
	minetest.get_mapgen_setting("mgv7_shadow_limit") or 1024
```

**Comment by Wuzzy2** [comment]
Well, then the bug is that a broken function is kept around in the Lua API and not marked as deprecated.

**Comment by paramat** [comment]
I'm not sure `minetest.get_noiseparams()` is deprecated, it might vary in some way.
Hmmmm designed the new mapgen setings API carefully so there may be good reason for the way t is, so we need to be cautious.

**Comment by paramat** [comment]
Settings refer to settings, if there is no setting present then returning nil is correct.

**Comment by Wuzzy2** [comment]
But then it's impossible to get the default value (except hardcoding it). :-(

**Comment by paramat** [comment]
Default values of varables are often hardcoded and scattered around in the code, it will probably be difficult to get them and require many different methods, and very complex code. Maybe we just have to accept hardcoding them in mods is preferable to such a task.

**Comment by Wuzzy2** [comment]
This is terrifying.

Wait a minute, isn't the default value coded in `settingtypes.txt`?

**Comment by paramat** [comment]
Yes. Maybe you could request a way to get any data from settingtypes? If you change the titleand description i'll reopen.

**Comment by Wuzzy2** [comment]
New issue: https://github.com/minetest/minetest/issues/6711
