### ISSUE TITLE
"Change Password" GUI does not work on Android build.

### ISSUE THREAD

**Issue by Elkien3** [minetest/minetest#6432]
When you Press "Change Password" from the pause menu on Android, The GUI appears, but nothing works when you touch it. (except for the 3 default Android buttons.)
It is not frozen, leaves will still wave, and players will still move. The GUI just appears to be bugged.

This makes it so if a player wants a password change, s/he must either switch to a PC and do it,  or ask a server admin.
(I already know a few of my players' passwords.)

My version is 0.4.16 from the Google Play Store.

**Comment by SmallJoker** [comment]
There were a few code movements and changes in the render. Is this bug still present in 0.4.17-dev or 0.5.0-dev?

**Comment by Wayward1** [comment]
Yes, this issue is still present in 0.5.0-dev

**Comment by paramat** [comment]
Fixed by #7483
