### ISSUE TITLE
Internationalization for custom settingtypes.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6436]
If any subgame or mod adds advanced settings via `settingtypes.txt`, all the descriptive text is non-translatable at the moment, i.e. English-only.

This issue is about adding this missing part of translation.

**Comment by paramat** [comment]
1 year bump for core dev attention.

**Comment by SmallJoker** [comment]
How would those be translated? Minetest cannot bundle them with gettext, so it would have to use client-side translations.

**Comment by paramat** [comment]
Isn't there an issue for game translation issues this can be moved into?
