### ISSUE TITLE
Formspecs: Allow to add tooltips to images and labels

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6442]
Currently, you can't add a tooltip to an image or a label. I request to make this possible.
If the cursor hovers any part of the area occupied by the image (it just needs to be somewhere in the rectangle), a tooltip may appear (if assigned).

A tooltip for an image is useful for small icons and such, to add captions, short hints, etc.

**Comment by jastevenson303** [comment]
And images for tooltips!

**Comment by DS-Minetest** [comment]
What about an extra tooltip formspec element? It would allow much more custom things.
Hm, but it couldn't be used for labels because of different fonts and also not for images because of texturepacks. >_<
:+1:

**Comment by paramat** [comment]
1 year bump for core dev attention.

**Comment by rubenwardy** [comment]
This is possible using the area form. I don't think this is needed

:-1:

**Comment by Wuzzy2** [comment]
I do think this is useful. If you want to add icons which might need further explanation in a tooltip, this will come in handy.
Especially if you add something like item icons, but not in a button, but an image instead.
Currently, you'd have to add a fake button to get a tooltip.

**Comment by rubenwardy** [comment]
As I said above, you can use a tooltip with an area. Images and labels don't have names, so you'd have to add the tooltip to the definition which is a bit gross

**Comment by ClobberXD** [comment]
@Wuzzy2 How the `tooltip[]` element works is that it displays a tooltip whenever the cursor is in the rectangle. To add a tooltip for an image, one could just create a `tooltip[]` element with the image element's rectangular dimensions. See https://github.com/minetest/minetest/pull/7469#issue-196269546
