### ISSUE TITLE
Add ObjectRef:on_set_properties("property") callback?

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#6445]
I would like to see a callback for ~ObjectRef:add_player_attribute()~ ObjectRef:set_properties("property"), specifically for the new map/telescope items which use this method(?).

http://irc.minetest.net/minetest-dev/2017-09-19#i_5082076
```
18:35 | jas_ | i would like to make an issue on minetest tracker; i think on_grant/revoke callbacks were added, but i am looking for on_add_player_attr, because: https://i.imgur.com/f6C2k18.png<-- minimap is only disable IF player lacks map item.
18:35 |   | (but i dunno about making this issue...)
18:36 |   | paramat: because i don't even get feedback when trying to zoom, just not even a message it's disabled.  and it's a key setting in the menu, so this is confusing imo
```
![screenshot_20170919_143420](https://user-images.githubusercontent.com/23448162/30609146-9206ae62-9d48-11e7-9f58-fa782ba88a0a.png)

^ Shows minimap as disabled by server, but in fact it's not really, the player just needs to craft the item.

**Comment by paramat** [comment]
The map item and binocular PRs in MTGame are not merged yet, and neither use player attributes.
Zoom is now enabled by 'player object properties'.
Minimap uses player HUD flags.

However your basic request is valid.

**Comment by jastevenson303** [comment]
Oh man!  I used the wrong term ahh.

**Comment by paramat** [comment]
Ok.
Priviledges have 'on grant' / 'on revoke' because they are entered in a command line, but 'player set property' and 'player set HUD flags' are always done in a line of lua, so there's no need for a callback because you can just add the action in a following line of code.
