### ISSUE TITLE
Get world names and world paths separately on command line

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#6452]
Currently we have only `minetest --world list` to get a list of all of the currently available worlds. Which is impossible to parse when using more than only letters as world names.

~~~~
$ minetest --world list
Available worlds:
  'really long ' name' '/home/dirk/.minetest/worlds/really long ' name'
  3x3            '/home/dirk/.minetest/worlds/3x3'
  'My "cool" world' '/home/dirk/.minetest/worlds/My "cool" world'
  'test welt'    '/home/dirk/.minetest/worlds/test welt'
  logic          '/home/dirk/.minetest/worlds/logic'
  test           '/home/dirk/.minetest/worlds/test'
~~~~

My suggestion is to complement this with two functions (or with one function if `--worldname` will be extended with the `list` parameter like `--world` already is) to allow getting world names and world paths individually from each other to allow post-processing the output in other scripts. For example here: https://github.com/minetest/minetest/issues/6450

The output could be done like this …

~~~~
$ minetest --worldname list
really long ' name
3x3
My "cool" world
test welt
logic
test
~~~~

… and this …

~~~~
$ minetest --worldpath list
/home/dirk/.minetest/worlds/really long ' name
/home/dirk/.minetest/worlds/3x3
/home/dirk/.minetest/worlds/My "cool" world
/home/dirk/.minetest/worlds/test welt
/home/dirk/.minetest/worlds/logic
/home/dirk/.minetest/worlds/test
~~~~

… this would allow reading the output diretly into a bash array for example.

**Comment by rubenwardy** [comment]
aren't they tab separated?

**Comment by dsohler** [comment]
> aren't they tab separated?

Nope, spaces.

**Comment by SmallJoker** [comment]
#6555 merged.
