### ISSUE TITLE
Settings performance

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#6454]
Settings performance is not very optimal due to a too generic backend using strings.
it's nice for mods to help them store settings, but it's totally unoptimal in core engine and needs to add caching variables everywhere to solve performance issues.

In my old fork, 2 years ago, i added a new generic + specific backend to store settings which improved massively performance, using a simple std::array per setting type with enum KEY permitting to select setting value directly. I suggest to backport my backend to MT to improve setting fetch performance

Implementation is something like this

```
enum u32setting: u8 {
U32SETTING_MAX_USERS,
U32SETTING_MISC_SETTING,
...
U32SETTING_MAX
};

Settings:get(u32 k) 
{
  assert(k < U32SETTING_MAX);
  return m_u32_setting[k];
}

u32 max_users = g_settings->get(U32SETTING_MAX_USERS);
```

There is no translation, no map, just a direct access to the value

**Comment by raymoo** [comment]
For faster indexing you could also assign an ID to each entry at runtime, and make it possible to ask for the ID and use it for lookup later.

To avoid translation, you could make it possible for settings entries to specify a type.

These two form an alternative that doesn't require hardcoded IDs. However it might not be important to be that flexible, except maybe to allow mods to get settings cheaply without caching.

**Comment by nerzhul** [comment]
another possible implementation is to use constexpr hashing on strings to have uint64_t keys, i should find the algorithm

**Comment by raymoo** [comment]
by constexpr hashing do you mean hash consing? I think my suggestion would imply hash consing to obtain the unique IDs.

**Comment by nerzhul** [comment]
we need, at least, two things: 
* have settings map per type to avoid many useless conversions
* index settings using integer instead of string, constexpr hashing means you have runtime hashing (for mods) and compilation time hashing for mt settings

**Comment by HybridDog** [comment]
What about est31's efforts? https://github.com/minetest/minetest/pull/2695

**Comment by numberZero** [comment]
My [previous suggestion](https://github.com/minetest/minetest/pull/6660#issuecomment-346706593) was to use a bit cleaner syntax:
>```c++
>enum_class(Name,
>	Entry1,
>	Entry2,
>	Entry3, // the comma here is either mandatory or forbidden, depending on the enum_class macro definition
>);
>
>enum_array<Name, float> some_settings;
>```
>then some more type safety may be ensured using some supporting library like [this one](https://gist.github.com/numberZero/c3ff76f6f3009638e8b5943d5019ebff).

But now I have another suggestion: use auto-generated structure(s) like
```c++
struct SomeSettings {
    SomeSettings(const Settings &file);
    int setting1 = 0;
    float setting2 = 1.0f;
    enum class StereoMode {
        None,
        Anaglyph,
        Interlaced,
    } stereo_mode;
};
```
The constructor (auto-generated too) loads settings from the generic interface into the structure, ensuring proper types, ranges, etc.

**Comment by HybridDog** [comment]
You could use [std::bitset](http://en.cppreference.com/w/cpp/utility/bitset) for bool settings I think.

**Comment by numberZero** [comment]
@HybridDog `bitset` is size-optimized, not speed-optimized. It is less convenient as well for such usage.
