### ISSUE TITLE
Discussion: Host server without being admin

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6456]
I'm sure this has come up before. I did a quick search through the issues with "host server", but nothing related came up...

Currently it is not possible to use the UI to setup a quick game between two local players without one being necessarily an admin - and is annoying since some behaviors changes (digging does not increase the count in the inventory, etc).

In order to do that you'd have to run a separate server, with a separate config file, just to change the admin name. So what good is host server in the UI in the first place?

I think this is:
- Hard to grasp for new users
- Somewhat annoying if you just want a quick game

Not sure what easy options there are, but at least we should be able to have a separate config to declare the server admin from a player that happens to play locally on the same machine.

Maybe have a "name" and "adminname" config...?

This is just for discussion. This must have come up before somewhere.

**Comment by nerzhul** [comment]
i don't understand your point, you can run a hosted server from minetest client UI

**Comment by lhofhansl** [comment]
I cannot not run a hosted server where the client/player who hosts the server is not automatically the admin, which makes that feature somewhat useless.
(Being admin changes the various behaviors - for example how items are collected.)

I have a change that simply allows setting the admin user name in the advanced settings, and if set the server will use that when determining whether a user is an admin or not.

A bigger change could allow setting both local user and admin user (with passwords) in the Local Game dialog, but not sure that is necessary.

**Comment by lisacvuk** [comment]
I agree; starting a server from the UI shouldn't grant you anything aside from privs priv.

**Comment by nerzhul** [comment]
@lhofhansl i see your point, it's subtile :)

**Comment by paramat** [comment]
PR #6460

**Comment by rubenwardy** [comment]
>annoying since some behaviors changes (digging does not increase the count in the inventory, etc).

This is not what privs are for, which is why I didn't like that PR. It should be attributed based with a privilege to switch between modes.

**Comment by dsohler** [comment]
> and is annoying since some behaviors changes (digging does not increase the count in the inventory, etc).

Due to misconfiguration (maybe used `/grantme all`?).
