### ISSUE TITLE
Make minetestserver and minetest --server fork into the background when neither --terminal nor --no-fork is specified

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#6459]
Basically as the title said...
Maybe something like inspircd:
```
Starting minetest...
<obligatory minetest ascii art>
Forked into background, pid X
```

**Comment by raymoo** [comment]
Why?

**Comment by nerzhul** [comment]
it's better to have a -d --daemon flag like most free softwares to do this. This is not portable on Windows but it can be implemented

**Comment by dsohler** [comment]
Or --service` since the majority of relevant end user Linux distributions uses systemd.

Or have the parameter even more generic: `--background` or `--detach` (the unchanged parameter name could be used for other operating systems, too).

**Comment by paramat** [comment]
Any core dev support or more comments? (i'm neutral).

**Comment by nerzhul** [comment]
i'm for it.
Note: systemd units permits to not having it easily using a unit in simple mode
