### ISSUE TITLE
minetest --version build date update

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6461]
I've found a problem: When compiling minetest after git pulling, version.cpp is only compiled if there're changes. So the date shown by `minetest --version` isn't updated.
To fix it, version.cpp needs to be compiled every time make is executed.

See also #6331

**Comment by sfan5** [comment]
who wanted a date in there anyway, this is stupid

**Comment by SmallJoker** [comment]
His and my fault: #6331 
Moving it into version.cpp allowed a nice build date stamp in the version info. However, it wasn't tested or analysed enough to notice the problem of incremental building.
