### ISSUE TITLE
2D player sprite: Incorrect offset

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#6471]
2D player sprites are still used by a few old mods and the minimal game itself.
The new feet position of the player messed up the offset of the texture, another change shrinked the texture.

Primary issue, the zero position:
![grafik](https://user-images.githubusercontent.com/1497498/30928861-04d3d13e-a3bd-11e7-888c-efffdc1b3ae3.png)
EDIT: Custom player texture from the active texture pack, but doesn't matter in terms of the position.

**Comment by paramat** [comment]
Maybe 0.5 is the time to remove the 2D player sprite? Keep it for other objects though of course.

**Comment by paramat** [comment]
Well actually, there may be good uses of sprites. Best fix the bug.
