### ISSUE TITLE
When having to fresh install

### ISSUE THREAD

**Issue by Taose** [minetest/minetest#6475]
Mostly due to git I suspect, but... 

From time to time, an "Unrelated Histories" error pops up when trying to pull. This can be triggered by updating another mod. The only real solution I have found is to remove and the mods and minetest game and pull fresh. 

However that potentially gets rid of all player data. I highly recommend that player data is not stored in the main git directory or that player areas are protected by the gitignore by default so that worlds are not removed in error. 

It might also be useful to explain in the Readme how players could better use symlinks for example to put their data separately, yet still be seen by the game without being vulnerable i.e. to a git reset, which might be done if an error pops up and we need to get get back to the stable files.

**Comment by sfan5** [comment]
I've never seen that error when pulling.
Also `git reset --hard` won't touch files not indexed into git, your worlds will stay intact.

**Comment by Taose** [comment]
and yet, here I am, with two empty folders.

**Comment by SmallJoker** [comment]
Did you delete [.gitignore](https://github.com/minetest/minetest/blob/master/.gitignore#L34) and commit all changes by accident? That or your local repository has some kind of data corruption in its history. I never had this problem either, but that's because the git repository and the actual game directory are separated.

**Comment by sfan5** [comment]
The only way to actually nuke the user data if it's stored in the same folder as the src code is a variation of `git clean -df .`

**Comment by Taose** [comment]
Nope git ignore doesn't cover either the mod directory or the world directory and it didn't like it when I tried to modify it, a hard reset also reset the ignore file. (Seems a touch weird). 

The command I used was git reset, I don't use git clean, I avoid if I can help it, using rebase. With that said, the difference between a user inputting the reset command and the user inputting the git clean command, this still shouldn't in theory harm the players data it should be elsewhere or protected by the gitignore file (which would be the simplest way of resolving this I think).

**Comment by Taose** [comment]
@SmallJoker, its highly likely there was some corruption when trying to update a forked mod from its original source, I'm not sure how that'd effect the Minetest core, but ultimately that's what I was doing to begin with. 

For me, the game is in exactly the same place as the git repository as the read me recommends. Of course, by separating the two, the problem wouldn't happen and hence the recommendation to modify the advice.

**Comment by rubenwardy** [comment]
I suggest resetting or redownloading the .gitignore. maybe even the whole repo. Mods and worlds are very certainly protected by the ignore:

https://github.com/minetest/minetest/blob/master/.gitignore#L43

**Comment by Taose** [comment]
Yep that's what I've done (I had little other choice)

I can say, that wasn't in there before and I only downloaded the source what last week? Making sure to follow the instructions on the readme. I can only assume that either the instructions were wrong (perhaps linking to something outdated?) or that something went awry with the cloning process. 

As that appears in theory to resolve the issue for now. I'll close this issue until it rears its ugly head again.
