### ISSUE TITLE
Debian Stretch

### ISSUE THREAD

**Issue by leiptrstormr** [minetest/minetest#6476]
`libncurses5-dev doxygen libpq-dev libhiredis-dev libspatialindex-dev`

Add these to Debian install instructions, please. I did build-dep minetest as well, so there's no telling what else might be missing, but these definitely are.

`cmake ../ -DPOSTGRESQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/`

This bug was closed for some reason. It still exists in Stretch.

**Comment by Megaf** [comment]
Well, those are not required libs, they are all optional if you want to compile a build supporting those packages.

I see no bug here.

By the way, I am a Debian Stretch and Sid user myself and usually I don' t install those libs.

**Comment by bigfoot547** [comment]
I also noticed that there is no package named `libjpeg8-dev` nor is there a `libpng12-dev`.
I had to use `libjpeg-dev` and `libpng-dev`.

**Comment by Megaf** [comment]
> I also noticed that there is no package named libjpeg8-dev nor is there a libpng12-dev.

That's weird, I fixed this years ago...
https://github.com/minetest/minetest/pull/2664

**Comment by bigfoot547** [comment]
Ah, lol. I was getting the package names from here: http://dev.minetest.net/Compiling_Minetest
I don't quite know what I expected... Is the wiki ever up-to-date?

Thinking about it, maybe we should have a docs team. I'd be in it ;)

**Comment by jastevenson303** [comment]
Yes, you can have paramat, perhaps, register #minetest-docs.  I would contribute.

**Comment by bigfoot547** [comment]
Well, I have registered #minetest-docs as #minetest-doc is taken. Should I go ask an operator to have #minetest-doc dropped?
@paramat @jastevenson303

**Comment by paramat** [comment]
Best to use the existing channel, organise it on IRC dev channel.
No the wiki is never up to date, alway go by repo docs.

**Comment by bigfoot547** [comment]
The point of a wiki is to be a "manual" of sorts, so it may not be up-to-date, but it should be :P
That's just my opinion, tell me if I'm wrong...

**Comment by jastevenson303** [comment]
Is that a Dennis Miller reference?  It would be neat if the dev wiki could get updated automatically from lua_api.txt, game_api.txt, and the like.  AFAIK everything is done manually.

**Comment by Megaf** [comment]
We should just GitHubs wiki thing so we can all send PRs to update the docs. But that's a discussion for other "issue".
Shall we close this one?

**Comment by paramat** [comment]
> By the way, I am a Debian Stretch and Sid user myself and usually I don' t install those libs.

@Megaf can you confirm there is no bug here?

**Comment by Megaf** [comment]
@paramat Just some old instructions in the wiki.
The official documentation in our repo was fixed years ago by myself.
