### ISSUE TITLE
Add support for typed MetaData fields

### ISSUE THREAD

**Issue by cakenggt** [minetest/minetest#6492]
When an item or node metadata's `set_int` method is used to set a value, looking at that value by using the `to_table` method shows that it is set as a string. This is usually not a problem, as we get those values using `get_int`, but in a node's `after_dig_node` method, the oldmetadata is in table form, and it is not obvious that the value coming back from a previous `set_int` call will be a string. Perhaps these should be stored as int, or documentation can be added to the metadata methods in the lua_api.txt file stating that they are stored in the background as strings.

**Comment by sfan5** [comment]
This is a feature ... i think.
Should've been documented though.

**Comment by rubenwardy** [comment]
This is more of a feature request IMO, to have typed meta

**Comment by paramat** [comment]
Any core dev support or further comments? (i'm neutral).

**Comment by Wuzzy2** [comment]
The actual issue here is that the `to_table` form of metadata is not documented but it should be.
