### ISSUE TITLE
Separate client, server and (maybe) launcher

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6498]
That would be useful in many ways:
1. The client would not need menu GUI and all that stuff; only HUD and pause menu (which could be very basic). That would help moving from IrrLicht, too.
2. The client would load configuration on start and keep it in, say, static variables. This way, the conventional change-restart-test sequence would be less disruptive. Moreover, static constants may be slightly faster to use. (Constants could be used as configuration wouldn’t be changeable in the client, only in the launcher).
3. The client would not need to contain all the server code. Internally, they are separated already (AFAIK) and effectively share little more than the address space itself. This separation should make the system cleaner. Also, that should prevent damaging the world in the case of client failure (not sure how probable that is, actually, but that’s not the main goal anyway).

Note: this is not a duplicate of #4917, it asks for completely different things.

**Comment by sfan5** [comment]
> The client would not need menu GUI and all that stuff

yes it would, formspecs exist

> That would help moving from IrrLicht, too.

even if you exclude the GUI code literally everything else down to vector maths or simple 2d positioning relies on irrlicht

> The client would load configuration on start and keep it in, say, static variables. [...] Moreover, static constants may be slightly faster to use.

and this differs from code currently having `thread_local static const char *foo = g_settings->get(...);` exactly how?


> The client would not need to contain all the server code. 

yep, this would be an useful abstraction

**Comment by numberZero** [comment]
> > The client would not need menu GUI and all that stuff
>
> yes it would, formspecs exist

That’s why I say *menu GUI*. Formspecs don’t need to rely on IrrLicht, they are very specific (btw, IrrLicht doesn’t handle some use cases well, namely stereo modes) and may be written with something simpler and maybe more lightweight (not sure where the bottleneck is, but on my system open inventory reduces FPS significantly).

> down to vector maths or simple 2d positioning

I could give you a CC0 math library. I’ve written a few when I needed something to be fast (faster than Eigen which doesn’t handle small vectors well) and to have less dependencies.

> everything else ... relies on irrlicht

The separation is not a short-term goal. But isn’t that what IrrLicht is isolated for?

> and this differs from code currently having thread_local static const char *foo = g_settings->get(...); exactly how?

The only difference is that such code would work properly. Changing setting in the main menu and then having to restart MT for it to take effect is bad.

P.S. Why are these variables `thread_local`? Is that faster, for some reason?

**Comment by numberZero** [comment]
One note: the advantages I described are *possibilities*, not *necessities* for the separation.

**Comment by paramat** [comment]
:-1: Lots of work and not much needed, advantages are very minor.

**Comment by jastevenson303** [comment]
Nothing stopping one from making a third-party launcher.  `minetest --go --address ''` comes to mind.

**Comment by celeron55** [comment]
Separating the binaries would create lots of unnecessary portability problems. It's not like this is something I didn't think about when I was making MT originally.

Also for one, I want the full configuration menu to be available in the pause menu. Has it ever been? No. But it's something to work towards.

Also, personal opinion: Launchers are stupid.

**Comment by paramat** [comment]
Separate repos would break git history and blame (which are extremely useful to devs).
PRs often contain client and server code so would become 2 PRs that have to be reviewed and tested together.
Testing anything would require downloading and compiling 2 or 3 programs.
Essentially a nightmare for development.

Feel free to continue discussion but closing.

**Comment by numberZero** [comment]
Just one note. My suggestion *was not* to separate the repositories.

**Comment by paramat** [comment]
Ok sorry i misunderstood, reopening for more consideration.

**Comment by benrob0329** [comment]
It would be neat to modularize the server from the client. Something that a separate launcher could do is make it easy to have an android-only main menu, separate from the desktop one (potentially using a mobile orientated toolkit) and encouraging the ability to have custom launchers eg for controller only situations.

**Comment by jastevenson303** [comment]
Can the word Frontend be used for launcher?  I don't know, I think of ZDL and startx when I think "launcher".

**Comment by numberZero** [comment]
For a server, a front-end could be useful to manage bare servers. It doesn’t need to be a part of MT, though; `minetestserver` may be launched by any program.

For a client... well, we might remember that MT is an *engine*, not a game. Launcher could be used to select a game (with its own main menu each), and some settings that can’t be changed at runtime (e.g. video driver); it could also create a desktop shortcut for that particular game.

And, finally, on separating the client and the server... AFAIK, these are separate internally; they do share some code but not data. Ugh, MT binary (in singleplayer mode) communicates with itself over UDP! That’s unbelievably weird for a single process! But that should also make separation easier.

On the other hand, instead of separating them, it is possible to integrate them better instead. E.g. replace the UDP communication with data sharing.

**Comment by paramat** [comment]
Any core dev support for any of these suggestions?
