### ISSUE TITLE
A simpler flat mapgen

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#6499]
I do not necessarily want the caves, the trees, etc. on the flat mapgen, just a strict flat terrain with grass to build easily.

Can the caves, trees, etc. be turned off optionally?

**Comment by Amaz1** [comment]
Would adding ```mg_flags = nocaves,nodecorations``` to minetest.conf do this?

**Comment by kilbith** [comment]
Got my solution, thanks.
