### ISSUE TITLE
Line Break in Description

### ISSUE THREAD

**Issue by RonnyBarthmann** [minetest/minetest#6506]
There no Char to add Line Break in the Server Description

**Comment by SmallJoker** [comment]
Dupe of #5392

**Comment by sfan5** [comment]
This is not necessarily a duplicate because this might need explicit support in the mainmenu and/or serverlist.

**Comment by SmallJoker** [comment]
The server description is shown in a `textarea[` which should support the new line character, once it is supported in the configuration.
Adding a special character to force new lines while not being able to use multiple lines in the settings file sounds wrong to me.

**Comment by RonnyBarthmann** [comment]
if i write
`server_description = [[
line1
line2
line3
]]`

only `[[` is showed in the Serverlist

**Comment by DS-Minetest** [comment]
@RonnyBarthmann `server_description = line1\nline2\nline3`
