### ISSUE TITLE
minetest.clear_craft should return false instead of throwing an exception when it can't find the recipe it's given

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#6513]
In the course of working on my crafting system mod [[simplecrafting_lib]](https://github.com/minetest-mods/simplecrafting_lib) I've run into a great deal of trouble dealing with minetest.clear_craft. In a nutshell, it would be a lot easier to work with if it returned a true/false success value rather than throwing an exception when attempting to clear a craft that doesn't exist.

The problems I'm having stem from my [recipe import code](https://github.com/minetest-mods/simplecrafting_lib/blob/master/legacy.lua). It is meant to cycle through all registered items, call minetest.get_all_craft_recipes on each item, and then potentially call clear_craft if the licensee for simplecrafting_lib has registered a filter for that recipe. But if I inadvertently call clear_craft with a recipe that is "the same" as a recipe that I've previously cleared, the game throws an exception and exits to main menu.

To work around this I've resorted to keeping track of the recipes that I've already called clear_craft with and wrapping clear_craft in a "safe_clear_craft" method that will only call clear_craft if the recipe hasn't been cleared before. But it's proving complicated to figure out what recipes count as "the same", as far as clear_craft is concerned. For example:

	minetest.register_craft({
	output = "default:chest",
	recipe = {
		{"default:wood", "default:wood", "default:wood"},
		{"default:wood", "", ""},
		{"default:wood", "", ""}
	}})
	minetest.register_craft({
	output = "default:chest",
	recipe = {
		{"group:wood", "group:wood", "group:wood"},
		{"group:wood", "", ""},
		{"group:wood", "", ""}
	}})

	local crafts = minetest.get_all_craft_recipes("default:chest")
	for _, recipe in pairs(crafts) do
		minetest.debug(dump(recipe))
	end

	minetest.clear_craft({recipe = {
		{"default:wood", "default:wood", "default:wood"},
		{"default:wood", "", ""},
		{"default:wood", "", ""}
	}})
	minetest.clear_craft({recipe = {
		{"group:wood", "group:wood", "group:wood"},
		{"group:wood", "", ""},
		{"group:wood", "", ""}
	}})

This code will throw a "No crafting specified for input" exception when I try to clear the second recipe, since the crafting system code has decided that clearing the "default:wood" recipe means that the "group:wood" one should also be removed. Note that both of those registered recipes are definitely present in the crafting system before the first clear_craft call, that debug dump I stuck in the middle shows that they're both registered for default:chest.

The end result is that I've written ~140 lines of Lua code to reproduce the checking that clear_craft is doing in order to make sure that I never tell clear_craft to remove "the same" recipe twice. It would be much easier to work with this - and much more bug-resistant and future-proof - to just have clear_craft return false if it's unable to find the recipe it's been given. It looks like it'd be a simple change at the end of l_clear_craft in l_craft.cpp.

**Comment by sfan5** [comment]
> The end result is that I've written ~140 lines of Lua code to reproduce the checking that clear_craft is doing in order to make sure that I never tell clear_craft to remove "the same" recipe twice.

You can just wrap the invocation inside a `pcall` to catch thrown errors btw

**Comment by FaceDeer** [comment]
Well then. On the one hand, it's annoying to have written all that code when I could have just done that. On the other hand, it forced me to learn a lot about the crafting system's quirks. So the time wasn't entirely wasted.

And I still think this issue is a worthy one. I don't see why this particular function should throw on error instead of returning false.

**Comment by paramat** [comment]
I agree it should fail with less drama.

**Comment by paramat** [comment]
The issue suggestion seems a good idea.

**Comment by paramat** [comment]
Looks quite simple to do, might attend to this.

**Comment by paramat** [comment]
PR #7804
