### ISSUE TITLE
Strange behaviour when manipulating full stacks in chest formspecs

### ISSUE THREAD

**Issue by Hawk777** [minetest/minetest#6516]
Tested in Minetest and Minetest_game 0.4.16.

Put down a chest. Get hold of two stacks of 99 cobblestone each, plus one stack of 1 cobblestone. Put one stack of 99 cobblestone in the chest, the second in your first hotbar slot, and the stack of 1 cobblestone in your second hotbar slot. Now open the chest, click on the 1-cobble stack from hotbar slot 2 to pick it up into the mouse pointer, and then click on the 99-cobble stack in the chest.

Expected behaviour: the stacks swap places. The chest contains a 1-cobble stack, the mouse pointer holds a 99-cobble stack, and the 99-cobble stack in hotbar slot 1 is still there.

Actual behaviour: The chest contains a 1-cobble stack, the 99-cobble stack from the chest teleports directly to hotbar slot 2, and the 99-cobble stack from hotbar slot 1 teleports into the mouse pointer.

If you had a >1-cobble stack in hotbar slot 2 when you started this, and you split that stack to put only some of it into the chest, then the stack unsplits when you click in the chest’s inventory and the left-behind portion teleports into the chest at the same time as the 99-cobble stack you swapped with teleports back to hotbar slot 2.

This doesn’t require that the other 99-stack be in the player inventory; it also happens if the 99-stack that you’re not touching is in the chest. However, it *does* require that the 99-stack that you’re not touching be in an earlier slot than the 1-stack that you initially pick up; if there is only one 99-stack before the 1-stack (the one that you’re going to swap with), then the swap happens normally and 99-stacks in higher slots than the original 1-stack lived in are not touched.

**Comment by Fixer-007** [comment]
I have impression that you are describing my problem I had for ages on servers but was too confused about it to create an issue, I've tried to reproduce it, but failed. Can you create a simple demo gif with the process?

**Comment by Hawk777** [comment]
![Here you go](https://user-images.githubusercontent.com/365236/31425543-a12a85bc-ae14-11e7-908d-e70254ec077e.gif)

**Comment by Fixer-007** [comment]
Yeah, after several tries I've reproduced this bug.

**Comment by Hawk777** [comment]
It’s not network lag. This was a singleplayer game, and as you can see I was moving fairly slowly.

**Comment by SmallJoker** [comment]
#6520 should fix this problem, but could have some side-effects I haven't found yet.
@Hawk777 If you would have some free time, I'd appreciate if you could test that PR and see whether it works as expected.
