### ISSUE TITLE
Engine ignores HP change modifier when profiler is enabled it seems

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#6517]
On my server (0.4.16-dev) I use the register_on_player_hpchange() callback to be able to use a custom HP system, not the builtin one that's restricted to 20 HP per player.

But when I enable the mod profiler to check which mods cause the most lag the engine seems to give all players only 20 HP and completely ignores my custom system.

Here is an example code that will work in 0.4.16+
https://pastebin.com/4jQLtnwV

First use it with mod profiler disabled: You will have 100 HP and only die if those custom HP reach 0 ...
Now enable the profiler with profiler.load = true in minetest.conf and test again... You'll notice that you suddenly only have 20 HP instead. So when the custom HP reach 80 you are dead.

EDIT: This does not only affect custom HP systems (since those are obsolete in 0.5.0 now), it affects every mod that relies on this modifier like 3d_armor!

EDIT 2: Confirmed in 0.5.0-dev

**Comment by rubenwardy** [comment]
>I use the register_on_player_hpchange() callback to be able to use a custom HP system, not the builtin one that's restricted to 20 HP per player. 

From 0.5.0, you should look into health_max
