### ISSUE TITLE
The Menu Overlay Image Should be everywhere

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#6518]
I tried an overlay image for my own minetest game, but I noticed that it only displays in world selection.
If its possible to do I think it would be better to display in all sections. (except for maybe "Play Online")
How about you?

**Comment by paramat** [comment]
+1.

**Comment by Zughy** [comment]
This doesn't make much sense. Backgrounds are not kept between the local tab and the rest of the tabs, I don't understand why the overlay should be an exception. Either both or none (and I'd opt for the latter)

**Comment by rubenwardy** [comment]
So, whilst I don't agree with the original request in this issue, I do agree with changing the main menu to apply the game theme on all pages when a is game selected. Might be best to wait for a game selector system first soon, which would be part of a redesign
