### ISSUE TITLE
Cannot look around with trackpad while using WASD

### ISSUE THREAD

**Issue by BitOfAByte** [minetest/minetest#6522]
System:
Antergos (similar to Arch Linux)
i3wm
Lenovo Thinkpad x1 Yoga
[libinput list-devices](https://pastebin.com/mXn2Ehi9)

While pressing WASD (those specific keys, not just movement keys), the trackpad cannot be used to look around (not actually 100% true, see below). However, using the screen as a touchscreen, using a mouse, and even the little trackpoint in the keyboard all work correctly.

When rebinding the movement to other keys (I used arrow keys for testing), movement and looking with the trackpad worked fine, but pressing WASD locked the camera again (despite not being bound to anything).

Pressing WASD and then shift behaved the same, moving if movement was bound to WASD but preventing from looking around. However, if shift and then WASD is pressed, it works perfectly (movement, looking around with all different input, etc.)

**Comment by RichardTry** [comment]
@bvanrosendale Hi! Why you closed this issue and how did you fixed it?

**Comment by rubenwardy** [comment]
This is a laptop setting, not a bug in Minetest. Look for a "disable touchpad whilst typing" setting in your keyboard+mouse settings
