### ISSUE TITLE
How destroy invisible block ?

### ISSUE THREAD

**Issue by phobos56** [minetest/minetest#6524]
I use minetest 0.4.15 on windows , i use World Edit for make a big wall and i use World Edit to supress some nodes. 
When i do that , blocks are delete but it still appear invisible blocks ( like the picture below) and i would like to know how to destroy them all?
![invisible](https://user-images.githubusercontent.com/25820892/31503561-44b34a3c-af70-11e7-8945-d4219059a9af.jpg)

**Comment by SmallJoker** [comment]
Select the affected area with WorldEdit and use `//restore` to make them appear in the original node again. To replace them all with air, use `//replace worldedit:placeholder air`. Please keep in mind that the replace function will leave metadata garbage in your world, which has the (only) effect of a higher disk use per effected mapblock.

**Comment by phobos56** [comment]
Thank you !
