### ISSUE TITLE
API documentation: Object properties

### ISSUE THREAD

**Issue by zeuner** [minetest/minetest#6526]
The API documentation regarding object properties seems incomplete.

Examples:
* What do each of the 6 indices of "collisionbox" relate to?
* What do the different choices for "visual" mean?

I guess there is more, these are just those I stumbled upon right now.

**Comment by paramat** [comment]
I assume lua_api.txt, not wiki docs?

**Comment by zeuner** [comment]
This is about lua_api.txt in this git repository.

I also did not find sufficient information on the wiki, though.

original message follows:

**Comment by paramat** [comment]
#6906 merged.

**Comment by zeuner** [comment]
Great, thanks!

original message follows:

**Comment by zeuner** [comment]
Great, thanks!

original message follows:
