### ISSUE TITLE
Discuss: Make zoom a real zoom?

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6529]
Currently zoom just lowers the FOV, is does not actually zoom (as in providing any additional information).

There's a simple change where the client simply requests a larger view-distance when zooming. The server would still check its `max_block_send_distance` and if it fits would use the wider view distance.

That would work as long as the client would not normally use the maximum view distance allowed by the server.

Other options:
- allow a little extra view distance (1-3 mapblocks) at the server when the client is zooming (for example when the FOV is below some threshold). This would also be easy and pretty effective.
- more complicated and perhaps hard to understand for a user. Do not limited based on view distance but by the something that represents the work of the server better: The volume of the view-cone. Smaller FOV (for example when zooming) would allow a larger view distance).

**Comment by paramat** [comment]
Good idea.
There is the issue of different power zoom FOV values. Smaller values tend to represent a more powerful zoom, so it seems perhaps the distance should depend on how small the zoom FOV is?
This means your 3rd suggestion, however i'm not sure keeping volume of view cone constant is ideal, it might result in distances being too large.

**Comment by lhofhansl** [comment]
I think I'd prefer the 2nd way then. Smaller FOV implies a higher extra distance, can put a max limit on the extra.

**Comment by paramat** [comment]
Yes. And the distance should be able to exceed `max_block_send_distance` if the zoom is a powerful one.

**Comment by lhofhansl** [comment]
How would we define what's powerful?
The zoom fov defaults to 15. That makes the view cone volume roughly 1/12 of the default fov of 72.
(atan(72) = 0.89, atan(15) = 0.25)

atan(10) = 0.17
atan(5) = 0.09

I think the relationship between the angle (fov) and the radius of the cone is linear enough at these angles.

Perhaps we could increase the distance simply by sqrt(72/fov). That would double it for a fov of 15, or x2.6 for fov of 10, or x3.7 for a fov of 5, x8.4 for a fov of 1, etc. It would require to use a configured fov at the server.

**Comment by paramat** [comment]
How to decide distance based on zoom FOV is the difficult task.
Our default is 72 / 15 = 4.8 magnification which is low power small binoculars, suitable for the small old fashioned field glasses just added to MTGame.
Maybe we should consider what distance is reasonable for low power binoculars, calculate how many nodes across the view is at this distance, then keep this number of nodes constant to define distance from zoom FOV.
At smallest FOV 72 / 7 = roughly 10 which is like higher powered binoculars, but i think we could decrease this lower limit of zoom FOV to allow powerful telescopes.

**Comment by lhofhansl** [comment]
I agree that the lower hardcoded limit of 7 is arbitrary.

Not sure how perfect this has to be, just needs to be give a nice effect and allow zoom to actually see more detail. That would also need to increase the fog distance (which is chosen in order to hide the "edge of the world", now we're pushing that edge out, and hence the fog needs to be pushed out too), the effect here would be that in the zoom you'd see less fog, which is not what happens in real life.

**Comment by paramat** [comment]
Please could you also remove the wield when zooming?
