### ISSUE TITLE
Function to test for protection in a given cuboid

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6533]
In some situations protection needs to be tested on many nodes near each other, e.g. when using a [field replacer](https://github.com/HybridDog/replacer/blob/master/init.lua#L441), igniting tnt or https://github.com/Uberi/Minetest-WorldEdit/pull/137.
A function to test protection in an area (two position parameters defining a cuboid) could be used instead of testing every single node position with minetest.is_protected to avoid redundant lag, e.g. when testing a 100x100x100 worldedit area. Mods can implement this function, e.g. the areas mod which aligns protection to mapblocks can test only mapblocks instead of every node and the protection blocks mod doesn't need to search a 11x11x11 area for each node.
Instead of overriding minetest.is_protected, mods could use some function to register the protection function for a single node and for an area, if the area function is omitted, a simple function which tests each node is used instead.

**Comment by paramat** [comment]
I added such a function to MTGame to help check if a grown tree will intersect protection
https://github.com/minetest/minetest_game/blob/master/mods/default/functions.lua#L485
PR thread https://github.com/minetest/minetest_game/pull/1208
It has a definable check interval so that every node does not need to be checked.
Could be moved to builtin?

**Comment by SmallJoker** [comment]
@paramat good idea. Having it as a helper function in builtin is better than depending on MTG/default.

**Comment by paramat** [comment]
Ok will do.

**Comment by paramat** [comment]
PR #6952

**Comment by HybridDog** [comment]
I actually thought about a function which ensures compatibility.
When mods use minetest.intersects_protection but the e.g. protection blocks mod does not override this function (e.g. because it's made for minetest 0.4.16), there could be missed positions.
I thought instead of using an interval argument, the protection mods (e.g. protection blocks) could override the intersects_protection function additionally to is_protected. To do this while keeping compatibility, a function for registering protection functions could be used instead of directly overriding is_protected and intersects_protection, this way for the older mods which only have a function for is_protected a function for intersects_protection could be generated.

**Comment by paramat** [comment]
#6952 and https://github.com/minetest/minetest_game/pull/2030 merged.
