### ISSUE TITLE
Broken wield mesh and inventory rendering

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#6536]
On https://github.com/minetest/minetest/commit/75320e7e88ab5088a46c9e42c1e789cbdacb13b0 it appears the inventory_image (and wield_image?) are not drawing overlays.

![screenshot_20171016_014023](https://user-images.githubusercontent.com/23448162/31596868-3153699a-b213-11e7-9bb5-4a38178ad85a.png)

The protection block normally displays this.  ~I think.~

Ps. I found this older screenshot, so it used to be on there: ![sss](https://user-images.githubusercontent.com/23448162/31614107-28b017e4-b253-11e7-90cb-c6dfb27afe2d.png)

**Comment by jastevenson303** [comment]
Check out this overlay wield image now: ![screenshot_20171016_110413](https://user-images.githubusercontent.com/23448162/31619203-dbbfab48-b261-11e7-8054-09e7df21e7c9.png)

And after reverting 75320e7e88ab5088a46c9e42c1e789cbdacb13b0: ![screenshot_20171016_112003](https://user-images.githubusercontent.com/23448162/31619972-0156acce-b264-11e7-9ac3-369338cb0a9c.png) @numberZero

**Comment by Fixer-007** [comment]
Example from homedecor mod (a bit outdated but eh): 
![default](https://user-images.githubusercontent.com/16494741/31692569-ec42eac4-b3a2-11e7-96f1-b129d6906564.png)

**Comment by jastevenson303** [comment]
And I haven't been successful in reverting, cherry-picking, or working around it somehow.

**Comment by Fixer-007** [comment]
Do we need bisecting? I guess I can quick check in my archives.

**Comment by Fixer-007** [comment]
After quick check, bug appeared between 4e19791c and 75320e7e.

**Comment by numberZero** [comment]
Er...? there are no overlays in `fence_picket`

**Comment by numberZero** [comment]
Has nothing to do with overlays. Something is broken with generating wield mesh that uses several textures on one node(box).

**Comment by numberZero** [comment]
Found the problem. Digging into the source.

**Comment by numberZero** [comment]
1. This has nothing to do with texture size as well; the problem arises when first 2 tiles are the same, but next ones aren’t.
2. Bug is present in 00ceec9ff, which is well before 75320e7. @Fixer-007 ?

**Comment by numberZero** [comment]
So, *my* bisect shows d04d8aba7029a2501854a2838fd282b81358a54e causes the problem with inventory images. That’s what happens: as `return` was removed at https://github.com/minetest/minetest/commit/d04d8aba7029a2501854a2838fd282b81358a54e#diff-60aa608aac2fefb1a86d4c2861a08eb7L495, the program goes by and reaches https://github.com/minetest/minetest/commit/d04d8aba7029a2501854a2838fd282b81358a54e#diff-60aa608aac2fefb1a86d4c2861a08eb7R529, where it screws the materials up, as the order is not necessarily the same as in the tile list.

**Comment by jastevenson303** [comment]
Before 75320e7 the overlay/wield images appeared correctly.  On 75320e7, and after, it is incorrect.

Before 75320e7: https://user-images.githubusercontent.com/23448162/31619972-0156acce-b264-11e7-9ac3-369338cb0a9c.png

On 75320e7 and after: https://user-images.githubusercontent.com/23448162/31619203-dbbfab48-b261-11e7-8054-09e7df21e7c9.png

I mean, it's not a big deal, it just looks funny.

**Comment by Fixer-007** [comment]
It is a big deal

**Comment by numberZero** [comment]
@jastevenson303 can you provide *some* information? Which commits you test, which mods, etc.

There seem to be 2 bugs at least: one with the wield mesh (which was broken somewhere between [0.4.10](https://github.com/minetest/minetest/commit/e14c4cdd4c3c9b554dc9cb91f8f29078ad337ded) and f25cc0dba (inclusive), but there may be other bugs included afterwards), and another one with the inventory image (which was broken by d04d8ab, you can test that with my [test mod](https://github.com/minetest/minetest/files/1400190/test1.zip)).

**Comment by numberZero** [comment]
There is the a problem in f25cc0d that was copied into d04d8ab: RBA assumed that material ID is the same as tile ID, but that’s not always the case.

On overlays: works for me™, need more information to catch the bug.

**Comment by Fixer-007** [comment]
Have you tried reproducing with homedecor modpack?

**Comment by Fixer-007** [comment]
I have ATI X800GTO 256MB (OGL 2.1) videocard and my config is:
```
anisotropic_filter = true
bilinear_filter = false
creative_mode = false
enable_damage = false
enable_waving_leaves = false
enable_waving_plants = true
fast_move = false
free_move = false
leaves_style = fancy
mainmenu_last_selected_world = 1
maintab_LAST = local
menu_last_game = minetest
mip_map = true
node_highlighting = box
server_announce = false
server_dedicated = false
trilinear_filter = false
viewing_range = 140
fps_max = 100
address = dcbl.duckdns.org
remote_port = 30000
mg_name = carpathian
tone_mapping = false
mainmenu_last_selected_TP = 1
noclip = false
texture_path = 
sound_volume = 0.1
enable_shaders = false
fog_start = 0.7
enable_bumpmapping = false
enable_parallax_occlusion = false
enable_waving_water = false
generate_normalmaps = false
smooth_lighting = true
enable_local_map_saving = false
mesh_generation_interval = 5
autosave_screensize = false
enable_client_modding = true
fixed_map_seed = 
minimap_shape_round = false
enable_server = false
world_config_selected_mod = 42
show_debug = true
fsaa = 0
port = 30000
specular_lighting = true
directional_shading = true
wieldview_node_tiles = false
wieldview_update_time = 2
mute_sound = false 
```

**Comment by numberZero** [comment]
Tested 6bab69547 (75320e7^)
![screenshot_20171020_223435](https://user-images.githubusercontent.com/7352626/31838886-5986f418-b5e7-11e7-9bda-c20311d34104.png)

**Comment by jastevenson303** [comment]
How to reproduce:

Use current minetest 0.5.0-dev
Install "Protector Redo" mod, https://github.com/tenplus1/protector
Observe protector node differences between placed item and wielditem, and inventory and wield images.

**Comment by Fixer-007** [comment]
@jastevenson303 What is your videocard, driver, OS and minetest.conf? Maybe our GPUs are too outdated?

**Comment by numberZero** [comment]
@jastevenson303 Confirming.

So, there are plenty of bugs around... (3 found by now)

**Comment by jastevenson303** [comment]
I see that the fence uses an ^overlay, in minetest_game, but that's not a nodebox.  The protector is, and previously the inventory_image/wield_image automatically generated based on `tiles`.

I tried setting `inventory_image` and `wield_image` nodedef parameters, but that didn't work.  RBA made a commit, that made inventory(/wield?) images generate from meshes, IIRC.  I'll search for it now.

**Comment by jastevenson303** [comment]
38e7122600

Doing `git log --author="RealBadAngel"` was interesting.

Minetest reports OpenGL 3.0.  Here is my config:
```
keymap_slot1 = KEY_KEY_T
keymap_slot2 = KEY_KEY_X
keymap_slot3 = KEY_KEY_C
keymap_slot4 = KEY_KEY_V
keymap_slot5 = KEY_KEY_A
keymap_slot6 = KEY_KEY_R
keymap_slot7 = KEY_KEY_G
keymap_slot8 = KEY_KEY_B
doubletap_jump = false
keymap_zoom = KEY_CAPITAL
keymap_right = KEY_KEY_F
keymap_forward = KEY_KEY_E
address = 192.168.1.199
maintab_LAST = local
keymap_console = KEY_OEM_3
keymap_freemove = KEY_F4
keymap_cinematic = 
keymap_chat = KEY_RETURN
keymap_noclip = KEY_F11
menu_last_game = minetest
keymap_left = KEY_KEY_S
remote_port = 30005
keymap_inventory = KEY_KEY_W
server_dedicated = false
keymap_fastmove = KEY_F8
keymap_print_debug_stacks = KEY_KEY_P
name = jas
keymap_backward = KEY_KEY_D
keymap_special1 = KEY_LSHIFT
keymap_cmd = /
keymap_jump = KEY_SPACE
keymap_sneak = KEY_KEY_Z
aux1_descends = false
keymap_rangeselect = KEY_KEY_I
keymap_drop = KEY_KEY_Q
noclip = false
free_move = false
fast_move = false
mouse_sensitivity = 0.17
sound_volume = 1
viewing_range = 100
enable_waving_plants = true
tone_mapping = false
leaves_style = opaque
connected_glass = true
opaque_water = true
enable_clouds = true
enable_3d_clouds = true
minimap_shape_round = false
font_size = 18
font_shadow = 2
font_shadow_alpha = 255
font_path = /usr/share/fonts/truetype/fonts-atarismall/AtariSmall.ttf
selected_world_path = /home/james/.minetest/worlds/po
screenshot_path = /home/james/.minetest/screenshots
mainmenu_last_selected_world = 3
mg_name = v7
fixed_map_seed = 
mono_font_path = /usr/share/fonts/truetype/fonts-atarismall/AtariSmall.ttf
node_highlighting = box
fov = 90
zoom_fov = 45
show_entity_selectionbox = false
console_height = 0.5
port = 30000
world_config_selected_mod = 1
main_menu_technical_settings = false
testy = tester
runfast_display_hunger_meter = true
runfast_display_sprint_meter = true
runfast_display_debug_meter = false
runfast_sprint_jump = 1.334
screenH = 720
screenW = 1280
autosave_screensize = false
nodetimer_interval = 0.1
wieldview_update_time = 2
wieldview_node_tiles = false
runfast_hunger_step = 15.0
runfast_sprint_speed = 1.667
runfast_meter_step = 0.1
runfast_hp_regen = true
runfast_health_step = 1
runfast_sprint_to_sneak = false
server_announce = false
enable_damage = true
creative_mode = false
screen_w = 1280
screen_h = 720
mg_flags = nodungeons,nodecorations,nocaves
keymap_hotbar_next = KEY_OEM_6
keymap_decrease_viewing_range_min = KEY_MINUS
keymap_cmd_local = KEY_PERIOD
keymap_hotbar_previous = KEY_OEM_4
keymap_camera_mode = KEY_F7
keymap_minimap = KEY_F9
keymap_mute = KEY_KEY_M
keymap_increase_viewing_range_min = KEY_PLUS
keymap_decrease_volume = 
keymap_increase_volume = 
keymap_toggle_force_fog_off = KEY_F3
keymap_screenshot = KEY_F12
keymap_autoforward = 
keymap_toggle_hud = KEY_F1
keymap_toggle_chat = KEY_F2
mainmenu_last_selected_TP = 1
texture_path = 
send_pre_v25_init = false
enable_server = false
enable_tnt = true
fps_max = 30
mute_sound = false
enable_client_modding = true
enable_mod_channels = true
```

**Comment by jastevenson303** [comment]
Sorry, I mean this one: https://github.com/minetest/minetest/commit/38e712260046f159aa201259569054bdf9793b7f

I'm just looking around with `git log --author "RealBadAngel"` -- before this, it just used whatever was in `tiles`.  That's my impression.  I wish you the very best of luck here, and feel somewhat sorry that you've stumbled upon this.  : )

**Comment by numberZero** [comment]
@jastevenson303 I found that particular problem.

**Comment by numberZero** [comment]
@jastevenson303 Still, that’s not my fault; I just exposed an old bug (several bugs, in reality).

So, the problem is that when a wield mesh of some node is generated, it gets materials for all the *different* tiles used by the node, *in an unspecified order*. Later these materials are altered, but in an assumption that they have *the same order* as the original tiles; that’s true in many situations, however, that’s why the bug was not discovered earlier.

Notably exceptions to that rule are solid and mesh nodes: their materials are guaranteed to be in the same order as the tiles. But before 75320e7 nodebox nodes were converted to meshes early, way before wield meshes were generated. That’s why the bug appeared in 75320e7 only (but it actually seems to be the reason for `plantlike_rooted` inventory meshes being wrong).

Finally, the reason for the bug to appear in earlier commits in my test case is that I misspelled `node_box` as  `nodebox`, thus MT handled these nodes inconsistently, sometimes as a nodebox node and sometimes as something else. But that helped me to find the core bug, actually.

> fence uses an ^overlay

That’s not an *overlay*, that’s just a texture modifier. Overlays are specified with `overlay_tiles`.

75320e7^:
![screenshot_20171020_233442](https://user-images.githubusercontent.com/7352626/31841149-e6f7cb2a-b5f0-11e7-86e7-a7ac05583e98.png)
75320e7:
![screenshot_20171020_234227](https://user-images.githubusercontent.com/7352626/31841136-d7c1c1f6-b5f0-11e7-9cca-890a2b66f9c1.png)

**Comment by jastevenson303** [comment]
Can a more general issue be made, as I fear this one is now stale.  I do not understand the greater impacts of all this, anyway.

**Comment by numberZero** [comment]
6cd2b3b doesn’t break things as the [problematic code](https://github.com/minetest/minetest/commit/6cd2b3b445bf558fda1e5a7908adef8e3a45449a#diff-60aa608aac2fefb1a86d4c2861a08eb7R517) is called only when that’s perfectly valid, i.e. for solid, liquid and mesh nodes, as `return` [is used](https://github.com/minetest/minetest/commit/6cd2b3b445bf558fda1e5a7908adef8e3a45449a#diff-60aa608aac2fefb1a86d4c2861a08eb7R498) in other cases. But it was [removed](https://github.com/minetest/minetest/commit/d04d8aba7029a2501854a2838fd282b81358a54e#diff-60aa608aac2fefb1a86d4c2861a08eb7L495) in d04d8aba7029a2501854a2838fd282b81358a54e.

**Comment by jastevenson303** [comment]
sorry again, paramat did you mention @juhdanad?  maybe he might want to look.

**Comment by paramat** [comment]
I originally tagged him because initially this seemed to be about overlays, which i think he coded. However now we know it isn't, so i deleted my tagging comment.

**Comment by numberZero** [comment]
@juhdanad Still, that’s your code.
My suggestion: add a `key` field to the tile spec or layer, such that different keys make layers unequal. This way you will be able to keep track of which mesh buffer belongs to a particular tile and layer. (`key` should always be zero in normal mapblock mesh generation).

By the way, what’s the reason of splitting meshes in MapBlockMesh? Is drawing order guaranteed among mesh buffers in a single mesh?

**Comment by juhdanad** [comment]
The map renderer reorders mesh buffers based on their material. But overlays must be drawn after the tile beneath them, this is why there are two meshes per map block.

Another solution would be to create a new material for overlays even if there is a base tile with the same texture and settings, then the renderer could draw them in order.

**Comment by numberZero** [comment]
The code appears to be rather ~~spaghetti-like~~ complicated; my previous suggestion can’t be implemented easily.
Working myself on fixing this (#6596).
