### ISSUE TITLE
Unable to access the HTTP API anymore

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#6543]
`minetest.request_http_api()` is no longer callable for $REASONS. Commenting this code out helps https://github.com/minetest/minetest/blob/master/src/script/lua_api/l_http.cpp#L140-L142

**Comment by rubenwardy** [comment]
How are you calling the function?

**Comment by kilbith** [comment]
> How are you calling the function?

`local http = minetest.request_http_api()`

Worked perfectly in the past...

> That code checks that you're calling from the init.lua scope

Not exactly, it checks at init time (i.e. not from a function), meaning it can be init outside of `init.lua` specifically.

**Comment by rubenwardy** [comment]
> Not exactly, it checks at init time (i.e. not from a function), meaning it can be init outside of init.lua specifically.

you need to call from the init.lua file. dofile counts as a function call.

This is for security reasons

**Malicious mod**

```lua
local api
local old = minetest.register_node
function minetest.register_node(...)
    api = api or minetest.request_http_api()
    return old(...)
end
```

** Mod with HTTP permission

```lua
minetest.register_node("mod:name", {
    ---
})

local api = minetest.request_http_api()
```

**Comment by kilbith** [comment]
Nope, still unable to access the HTTP API by moving this code on top of `init.lua` and the documentation [doesn't mention](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3126) this file.

It used to work outside `init.lua` during a while.

**Comment by rubenwardy** [comment]
Works for me

```lua
local http = minetest.request_http_api()
assert(http)
http.fetch({
        url = "https://minetest-mods.rubenwardy.com/v2/list"
}, function(res)
        print(dump(res))
end)
```

**Comment by kilbith** [comment]
My bad, sorry. Thanks for helping.
