### ISSUE TITLE
Bug: Parallax Occlusion makes nodes 'shake' when mined

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#6545]
Seems like when you active the Parallax Occlusion, alongside other shaders, the nodes you punch change position (they seem to move from one or two pixel). Seems like the overlay `crack_overlay.png` causes that. If it was only a node it would be fine, but the mined node "moves" all the nodes line of node near it.

**TESTED ON:**
- minetest 4.16 stable
- multiple subgames (MTG inclued)

-----------------------------

@MarkuBu

Currently I play with Parallax Occlusion active and I noticed, that the textures are moving if I place a node. That irritates when building

You can see it on the right side of the picture. Sorry for the change of brightness. That's caused by the twilight

Edit: Normal mapping has to be active too. If both are active, this happens.

![parallaxocclusion](https://user-images.githubusercontent.com/16163058/32408222-b1aa2f62-c194-11e7-97d8-f97ddc501252.gif)

**Comment by paramat** [comment]
> alongside other shaders,

Alongside which other shaders?

**Comment by Fixer-007** [comment]
What is your videocard, drivers, OS and show us your minetest.conf

**Comment by lisacvuk** [comment]
I noticed this too. Happens with empty config aswell, 
OS: Kubuntu 17.04
Videocard: A8 7600
Drivers: AMDGPU

**Comment by sfan5** [comment]
Can't reproduce anything here
Minetest `0.5.0-dev-f36e3231` | Arch Linux `x86_64` | GTX 950 w/ binary driver

**Comment by paramat** [comment]
See #6582 for animation.

**Comment by azekillDIABLO** [comment]
> See #6582 for animation.

Yeah that exactly it. But it happens on walls too.

**Comment by azekillDIABLO** [comment]
I love how this got forgotten

**Comment by paramat** [comment]
I looked at this issue a few days ago, so not forgotten.
Personally i think parallax occlusion is an ugly and cheap illusion and is best removed, we have normalmap bumpmapping after all which is much better.

**Comment by HybridDog** [comment]
Maybe the problem is caused by fastfaces and this issue could be related: https://github.com/minetest/minetest/issues/9243

**Comment by SmallJoker** [comment]
Parallax occlusion removed, see #10479.
