### ISSUE TITLE
client_mapblock_limit = -1 stops mapblock loading at some point

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6547]
https://forum.minetest.net/viewtopic.php?p=296971#p296971
According to solars, setting client_mapblock_limit to -1 in minetest.conf makes mapblock loading abort after loading a few mapblocks. It is supposed to [set the amount of mapblocks in memory to unlimited](https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1008).
I haven't tested it myself.

**Comment by Reedych** [comment]
I didn't see that.bug. Probably it's a bug of database backend?

**Comment by paramat** [comment]
Can't reproduce.

**Comment by ClobberXD** [comment]
Could be an issue of RAM being used up completely, which was the reason in my case. It's to be noted that my PC completely froze, so this could also be a different issue...
