### ISSUE TITLE
PNG filtering for mapblock compression

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6549]
Mapblocks mostly contain a few sorts of nodes spread like a 3d picture, so they resemble indexed png images. AfaIk, the [PNG filtering algorithm](https://en.wikipedia.org/wiki/Portable_Network_Graphics#Filtering), the main reason for the low file size, could be extended to a third dimension and be used for mapblocks (16x16x16 nodes). Unfortunately, the indexed images usually work best without filtering: https://www.w3.org/TR/PNG-Encoders.html#E.Filter-selection.
Alternatively, the mapblock can be mapped to 64x64 using the hilbert curve and then compressed like a PNG image.
I converted an indexed 64x64 image (with grey colours in the palette) to a gray png image and saved the 4 KiB directly line by line and I saved ordered by the hilbert curve (to make bits spatially next to each other close by each other in the output stream). The results, tested with multiple 64x64 images, sadly showed that ordering by hilbert curve always increased the file size (I compressed using $zip.).
I also tested it with an 1024x1024 image, this time ordering it by the hilbert curve often caused a lower file size. The images I used likely don't accurately represent mapblock data and the 2d curve was used, I don't know how using the 3d curve would affect real mapblock compression.

PNG filtering might be useful for solely param1 because of how light spreads. Take a 16x1x1 strip of air nodes and a torch for example: `5 6 7 8   9 10 11 12   13 14 13 12  11 10 9 8`
The filter which takes the difference from the previous pixel gives this output: `5 1 1 1  1 1 1 1  1 1 -1 -1  -1 -1 -1 -1` where -1 is 255 because modulo
Otoh param1 can have only 16 values, it's recommended to not use those png filter algorithms with such a small palette. And the example mentioned here doesn't represent the average case.
The filters are described there: https://www.w3.org/TR/PNG-Filters.html

#

**Similar issues** _(copied from SmallJoker's comment)_
Zstandard compression suggestion: #4495
Overall compression method comparison: #4654

**Comment by SmallJoker** [comment]
Currently we use zlib to compress them with the `deflate` algorithm, same as PNG uses. The difference is only the filtering step, where it's calculated how well the pixel color can be predicted.

**Similar issues**
Zstandard compression suggestion: #4495
Overall compression method comparison: #4654

**Comment by HybridDog** [comment]
I just read, the indexed images usually work best without filtering: https://www.w3.org/TR/PNG-Encoders.html#E.Filter-selection
I guess filtering is useful for solely param1 because of how light spreads. Take a 16x1x1 strip of air nodes and a torch for example: `5 6 7 8   9 10 11 12   13 14 13 12  11 10 9 8`
The filter which takes the difference from the previous pixel gives this output: `5 1 1 1  1 1 1 1  1 1 -1 -1  -1 -1 -1 -1` where -1 is 255 because modulo
This output can be compressed well I think.
The filters are described there: https://www.w3.org/TR/PNG-Filters.html
