### ISSUE TITLE
libnoise implementation?

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6550]
I was just wondering, why isn't libnoise being used for the noise functions?
http://libnoise.sourceforge.net/index.html

It seems that it would have been alot easier to implement than re-creating perlin noise yourself.

the perlin noise being created from scratch may have been something that celeron55 did just to do it.

thoughts and opinions?

EDIT: Broken link. FTFY.

**Comment by paramat** [comment]
> it would have been alot easier to implement than re-creating perlin noise

Easier but not necessarily faster, and likely slower. Performance has priority over ease of dev.

> the perlin noise being created from scratch may have been something that celeron55 did just to do it.

According to hmmmm (kwolekr), MT noise as originally programmed by c55 was slow, especially 3D noise, which is partly why mgv6 had no 3D noise.
Hmmmm then rewrote the noise functions to be much faster.

New noise types are very welcome (such as simplex noise), but looking at this lib it seems high level and has very little new stuff, only voronoi noise, which we can code ourselves avoiding the big and disruptive job of integrating a noise library.
It seems to me any new noise is best coded ourselves at a low level, this will be simpler and probably have higher performance.

Discussion with more details http://irc.minetest.net/minetest-dev/2017-10-21#i_5117599

:-1: for libnoise but i would be keen to add new noise types.

**Comment by ThomasMonroe314** [comment]
Yeah New noise types would come in handy I think for mapgen, that way you could create even more awesome terrain.
