### ISSUE TITLE
minetest fails to decode/deserialize large mod_store file

### ISSUE THREAD

**Issue by cyian-1756** [minetest/minetest#6565]
[tech_api.txt](https://github.com/minetest/minetest/files/1424340/tech_api.txt)
Attempting to decode and deserialize the file attached to this issue fails in minetest .5.0-dev-d5a97eo and 610ea6f, it will often fail silently (No message appears on screen in game) but sometimes returns a Json decoding failure error (ModMetadata[tech_api]: failed read data (Json decoding failure)), the file can however be decoded in a plain lua script using cjson without error

These errors with decoding and deserializing only happen if the file is larger then 10 KB or so in size

The mod that generated this file can be found [here](https://github.com/gdelazzari/tech_api/) (You have to go to the experimental branch). The code that calls the failing functions can be found [here](https://github.com/gdelazzari/tech_api/blob/experimental/utils/nodestore.lua)

**Comment by Reedych** [comment]
Tryed [this](https://pastebin.com/raw/ubH2vSH8) test mod with your file, minetest.parse_json() works, v0.5.0-dev-66ec50db.
It's probably fail of jsoncpp parser. Test it on bundled jsoncpp.
