### ISSUE TITLE
Formspec: allow textarea cursor to be not only on last visible line if more lines are above

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#6566]
#6510 made it possible to scroll through textareas. But problematically if you click (= short holding) on a line, the cursor automatically moves up many lines.

Also it would be very useful to see some lines beyond the selected one.

Ergo it would be nice if the uppermost visible line would not depend on the position of the cursor but on another number that is in- or decreased when you move with the cursor out of the current boarders.
(Sorry for awkwardness…)

**Comment by SmallJoker** [comment]
Also seen the same issue before we had scrollbars for them.
Can't find a duplicate for this issue even though I remember of a similar report (inside a PR, perhaps?)
