### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#6567]
<pre>
Linking CXX executable ../bin/minetest
CMakeFiles/minetest.dir/convert_json.cpp.o: In function `fetchJsonValue(std::string const&, std::vector<std::string, std::allocator<std::string> >*)':
convert_json.cpp:(.text+0x899): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `ServerList::deleteEntry(Json::Value const&)':
serverlist.cpp:(.text+0x2397): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text+0x23dd): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text+0x2409): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text+0x2435): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text+0x246d): more undefined references to `Json::Value::Value(Json::Value&&)' follow
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `ServerList::sendAnnounce(ServerList::AnnounceAction, unsigned short, std::vector<std::string, std::allocator<std::string> > const&, double, unsigned int, float, std::string const&, std::string const&, std::vector<ModSpec, std::allocator<ModSpec> > const&, bool)':
serverlist.cpp:(.text+0x44c2): undefined reference to `Json::Value::append(Json::Value&&)'
serverlist.cpp:(.text+0x4527): undefined reference to `Json::Value::append(Json::Value&&)'
serverlist.cpp:(.text+0x456a): undefined reference to `Json::Value::append(Json::Value&&)'
serverlist.cpp:(.text+0x45ad): undefined reference to `Json::Value::append(Json::Value&&)'
serverlist.cpp:(.text+0x45fe): undefined reference to `Json::Value::append(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text+0x4641): more undefined references to `Json::Value::append(Json::Value&&)' follow
CMakeFiles/minetest.dir/serverlist.cpp.o: In function `void std::vector<Json::Value, std::allocator<Json::Value> >::_M_insert_aux<Json::Value>(__gnu_cxx::__normal_iterator<Json::Value*, std::vector<Json::Value, std::allocator<Json::Value> > >, Json::Value&&)':
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x32): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x98): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0xd4): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x100): undefined reference to `Json::Value::Value(Json::Value&&)'
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x136): undefined reference to `Json::Value::Value(Json::Value&&)'
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x15f): more undefined references to `Json::Value::Value(Json::Value&&)' follow
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetest.dir/build.make:5931: ошибка выполнения рецепта для цели «bin/minetest»
make[2]: *** [bin/minetest] Ошибка 1
CMakeFiles/Makefile2:244: ошибка выполнения рецепта для цели «src/CMakeFiles/minetest.dir/all»
make[1]: *** [src/CMakeFiles/minetest.dir/all] Ошибка 2
Makefile:137: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
root@ne-vlezay80:/usr/src/minetest# 
</pre>

Debian 8

**Comment by sfan5** [comment]
gcc version?
have you tried running cmake with `-DENABLE_SYSTEM_JSONCPP=1`?

**Comment by juozaspo** [comment]
After testing with Debian 8.9 virtual machine with all updates, I can confirm that build still fail even having all requirements installed as noted in README.md.
Using `-DENABLE_SYSTEM_JSONCPP=1` in cmake command line fails with different error:
```
[ 34%] Building CXX object src/CMakeFiles/minetest.dir/script/lua_api/l_vmanip.cpp.o
/media/juozas/disk/minetest/src/script/lua_api/l_util.cpp: In static member function ‘static int ModApiUtil::l_parse_json(lua_State*)’:
/media/juozas/disk/minetest/src/script/lua_api/l_util.cpp:103:3: error: ‘CharReaderBuilder’ is not a member of ‘Json’
   Json::CharReaderBuilder builder;
   ^
/media/juozas/disk/minetest/src/script/lua_api/l_util.cpp:104:3: error: ‘builder’ was not declared in this scope
   builder.settings_["collectComments"] = false;
   ^
/media/juozas/disk/minetest/src/script/lua_api/l_util.cpp:107:8: error: ‘parseFromStream’ is not a member of ‘Json’
   if (!Json::parseFromStream(builder, stream, &root, &errs)) {
        ^
src/CMakeFiles/minetest.dir/build.make:1434: recipe for target 'src/CMakeFiles/minetest.dir/script/lua_api/l_util.cpp.o' failed
make[2]: *** [src/CMakeFiles/minetest.dir/script/lua_api/l_util.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:193: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2
```
Cmake command line: `cmake . -DRUN_IN_PLACE=TRUE -DCMAKE_BUILD_TYPE=Debug -DENABLE_GETTEXT=TRUE`
Cmake command output (Debian virtual machine): 
```
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- *** Will build version 0.5.0-dev-debug ***
-- Found Irrlicht: /usr/lib/x86_64-linux-gnu/libIrrlicht.so  
-- Using GMP provided by system.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Using bundled JSONCPP library.
-- Could NOT find LuaJit (missing:  LUA_LIBRARY LUA_INCLUDE_DIR) 
-- LuaJIT not found, using bundled Lua.
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so  
-- cURL support enabled.
-- Could NOT find GetText (missing:  GETTEXT_MSGFMT) 
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found VORBIS: /usr/include  
-- Sound enabled.
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.5.2") 
-- Freetype enabled.
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH) 
-- ncurses not found!
-- Could NOT find PostgreSQL (missing:  PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR) 
-- PostgreSQL not found!
-- LevelDB not found!
-- Redis not found!
-- Found SQLite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so  
-- SpatialIndex not found!
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so  
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so
-- Looking for BZ2_bzCompressInit in /usr/lib/x86_64-linux-gnu/libbz2.so - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.2.50") 
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /media/juozas/disk/minetest
```
Output of cmake with `-DENABLE_SYSTEM_JSONCPP=1` added to command line:
```
-- *** Will build version 0.5.0-dev-debug ***
-- Using GMP provided by system.
-- Found JSONCPP: /usr/lib/libjsoncpp.so  
-- Using system JSONCPP library.
-- Could NOT find LuaJit (missing:  LUA_LIBRARY LUA_INCLUDE_DIR) 
-- LuaJIT not found, using bundled Lua.
-- cURL support enabled.
-- Could NOT find GetText (missing:  GETTEXT_MSGFMT) 
-- Sound enabled.
-- Freetype enabled.
-- Could NOT find Curses (missing:  CURSES_LIBRARY CURSES_INCLUDE_PATH) 
-- ncurses not found!
-- Could NOT find PostgreSQL (missing:  PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR) 
-- PostgreSQL not found!
-- LevelDB not found!
-- Redis not found!
-- SpatialIndex not found!
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /media/juozas/disk/minetest
```
Full make output: https://pastebin.com/qNtzbQrm
Make output after adding `-DENABLE_SYSTEM_JSONCPP=1` to cmake command line: https://pastebin.com/q5VNm0jM

**Comment by sfan5** [comment]
@nerzhul

**Comment by nerzhul** [comment]
what is your jsoncpp system version ?

**Comment by juozaspo** [comment]
@nerzhul here's the libjsoncpp versions on debian guest and ubuntu host, only ubuntu works.
```
libjsoncpp-dev 0.6.0~rc2-3.1 amd64
libjsoncpp0 0.6.0~rc2-3.1 amd64
```
Ubuntu Host (build works there):
```
libjsoncpp-dev:amd64 1.7.4-3 amd64
libjsoncpp1:amd64 1.7.4-3 amd64
```

**Comment by nerzhul** [comment]
jsoncpp 0.6 is not supported by minetest, 0.X versions are not c++11 compatible

**Comment by nerzhul** [comment]
Use jsoncpp from backports on Debian

https://packages.debian.org/fr/jessie-backports/libjsoncpp-dev

**Comment by HybridDog** [comment]
> You will need jsoncpp 1.0.0 at least

Should this appear in the README?

**Comment by juozaspo** [comment]
Upgrading packages from backports repository might solve some problems, since the packages from there aren't used by default. Running `apt-get -t jessie-backports upgrade` and `apt-get -t jessie-backports dist-upgrade` from root prompt, assuming your distro release name is jessie. If your release name is not jessie, replace with the one you have instead. You can get release name using command `lsb_release -a` (if package lsb-release is installed). If using using sudo, add it before each command line instead.

**Comment by SmallJoker** [comment]
JsonCPP requirements were added to the README file. Please re-open this issue if the bug is still present with version 1.0.0+.

**Comment by Megaf** [comment]
https://github.com/minetest/minetest/issues/4306#issuecomment-318908891
