### ISSUE TITLE
Compose and dead key handling don't work on Linux

### ISSUE THREAD

**Issue by gpcf** [minetest/minetest#6573]
I'm running linux and I can't type characters like é, since the ´ and the e don't combine in minetest. This problem has also happened to other linux users on my server.

**Comment by SmallJoker** [comment]
Seems very similar to #302, which is also an Irrlicht key input issue.

**Comment by gpcf** [comment]
seems to be different, since I have a QWERTZ keyboard and the Z and the letters (Ä, Ö, Ü, ß) work properly. The only problem are the compose keys.

**Comment by HybridDog** [comment]
To fix this and future bugs, you could make the chat a terminal. This allows pressing ctrl+w to delete a whole word, ctrl+r to search in the history of what you wrote, ctrl+shift+u to paste an arbitrary Unicode character and a lot more. You would need to do something like a custom bash l think.
https://github.com/GNOME/vte

**Comment by gpcf** [comment]
add readline to the chat? Would be really cool to have completion for commands, especially if there are players with weird names asking to be banned

**Comment by sfan5** [comment]
fixed by https://github.com/minetest/irrlicht/commit/7c428c6dc2608693ab326ec3569b03bf8cddc4d5
