### ISSUE TITLE
Tonemapping conflicts with Fog

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#6584]
There's some conflict between fog and tonemapping:

[With tonemapping: very glitchy render, looks hideous](https://user-images.githubusercontent.com/17685062/32449908-43ab27c0-c32c-11e7-8c57-406e99038469.jpeg)

[Without tonemapping: looks fine as usual](https://user-images.githubusercontent.com/17685062/32450183-074f309a-c32d-11e7-9495-37c91a623f48.jpeg)

⚠️ _May be related to my graphic config, check forum link (just under in paramat's edit) for more details_
/////////////
EDIT by paramat:
See https://forum.minetest.net/viewtopic.php?f=6&t=18664
'fog_start' was set to 0.01 and 1, however that doesn't seem to be the cause from my testing.

**Comment by sfan5** [comment]
looks like broken graphics driver to me
graphics card? opengl version?

**Comment by lhofhansl** [comment]
Works fine for me. On various machines with and without shaders.

**Comment by paramat** [comment]
Isn't that the screenshot you showed when you set fog distance to a crazy value?

**Comment by Wayward1** [comment]
I've experienced this a while ago on different hardware, before most fog-related changes, as stated on the forum: https://forum.minetest.net/viewtopic.php?f=6&t=18664&p=299033#p298940

**Comment by paramat** [comment]
Yeah https://forum.minetest.net/viewtopic.php?p=297735#p297735
This screenshot is when you used 1 when the range is 0 to 0.99. This is related to the settings bug where limits don't work for floats.

However https://forum.minetest.net/viewtopic.php?p=297733#p297733 this looks very weird with an ok value of 0.01.

Ideally you should have stated these values used.

Wayward1's bug looks different.

**Comment by paramat** [comment]
Tried fog_start 0.01, 1 and 10, all look fine and work as expected.

**Comment by azekillDIABLO** [comment]
@sfan openGL 4.5 it's supposed to be okay, that first time i see this

@Wayward1 Looks like my bug actually, but the cause ae maybe not same

@paramat Honestly, i used value 0.01, 0.1, 1, 4 and 10 it didn't changed much anything 😶

**Comment by azekillDIABLO** [comment]
@sfan5 @paramat  Hem. A 0.1 value. Totally usable technically. The result
![screenshot_20171106_165245](https://user-images.githubusercontent.com/17685062/32449908-43ab27c0-c32c-11e7-8c57-406e99038469.jpeg)

**Comment by paramat** [comment]
Thanks. I tried fog_start = 0.1 and tonemapping, can't reproduce it (Intel integrated graphics).

**Comment by azekillDIABLO** [comment]
I heard somthing about Nvidia card causing lots of problems. I have one. With it's driver. The driver is unupdated... maybe that it... what do you think?

**Comment by Wayward1** [comment]
I can't reproduce this with an Nvidia GeForce 6150SE, with OpenGL 2.1.2, using the nvidia-304 driver

**Comment by Fixer-007** [comment]
Can you post exact minetest.conf?

**Comment by lhofhansl** [comment]
I always have tonemapping on. Tried on two different machines with two different graphics cards (ATI and NVidia resp). Had different OpenGL versions before. Works fine in all cases.

@azekillDIABLO I assume you tried with a vanilla minetest.conf and still see the problem?

**Comment by azekillDIABLO** [comment]
@Fixer-007  @lhofhansl 
my minetest.conf at the moment:

`keymap_special1 = KEY_KEY_E
keymap_backward = KEY_KEY_S
keymap_print_debug_stacks = KEY_KEY_P
doubletap_jump = false
keymap_forward = KEY_KEY_Z
mainmenu_last_selected_world = 60
keymap_hotbar_next = KEY_KEY_N
screenW = 744
keymap_fastmove = KEY_KEY_J
keymap_left = KEY_KEY_Q
keymap_jump = KEY_SPACE
server_announce = false
keymap_console = KEY_F10
class = elf
screenH = 513
keymap_zoom = KEY_TAB
creative_mode = true
selected_world_path = C:\Games\minetest-0.4.16-win64\bin\..\worlds\[MAP] Village
enable_damage = true
keymap_freemove = KEY_KEY_K
fixed_map_seed = we're all living in amerika, coca-cola wonderbra!
mg_name = v7
menu_last_game = minetest_game_new
keymap_sneak = KEY_LSHIFT
keymap_hotbar_previous = KEY_KEY_B
keymap_mute = KEY_F8
keymap_drop = KEY_KEY_A
keymap_noclip = KEY_KEY_H
keymap_inventory = KEY_KEY_I
keymap_cmd = /
aux1_descends = false
keymap_decrease_volume = 
keymap_chat = KEY_KEY_T
keymap_right = KEY_KEY_D
keymap_increase_volume = 
keymap_cmd_local = KEY_PERIOD
keymap_cinematic = KEY_F8
keymap_rangeselect = KEY_KEY_R
fast_move = true
free_move = false
connected_glass = true
enable_waving_plants = true
fsaa = 0
anisotropic_filter = false
mip_map = false
node_highlighting = halo
opaque_water = false
enable_waving_leaves = true
enable_parallax_occlusion = false
generate_normalmaps = false
tone_mapping = false
maintab_LAST = local
enable_bumpmapping = false
enable_waving_water = true
bilinear_filter = false
leaves_style = fancy
noclip = true
trilinear_filter = false
autosave_screensize = false
main_menu_technical_settings = true
enable_client_modding = true
remote_port = 30394
name = azekill_DIABLO
address = minetest.foo-projects.org
mainmenu_last_selected_TP = 1
texture_path = 
port = 30000
enable_server = false
enable_console = true
screenshot_format = jpeg
screenshot_quality = 80
nodetimer_interval = 0.1
sound_volume = 1
viewing_range = 50
wieldview_node_tiles = false
wieldview_update_time = 2
enable_shaders = true
world_config_selected_mod = 22
minimap_shape_round = false
display_gamma = 1456
ambient_occlusion_gamma = 6
enable_vbo = false
enable_fog = true
smooth_lighting = false
enable_particles = true
texture_clean_transparent = true
crosshair_color = (125,155,240)
fog_start = 0.1
fov = 72
time_speed = 0
vehicles_nodes = true
cloud_height = 59
directional_colored_fog = false
enable_3d_clouds = false
`
I tried with empty conf , only the minimal required:
`tone_mapping = true`

**The bug still happens the same way, maybe my client needs to be updated? I didn't changed it from the time it was released i think.**

**Comment by Fixer-007** [comment]
Can't reproduce on ATI X800GTO (OGL 2.1, win7)

**Comment by paramat** [comment]
This label is just a reminder to close if no-one has reproduced this after a while, let's give it a month?

**Comment by azekillDIABLO** [comment]
Okay, no pb. However i see no clue of why i see such things... wait. Is my shaders file the good version? i will download a new client and try.

**Comment by azekillDIABLO** [comment]
Okay i tried with the 4.16 shaders and it was that. My shader file was somewhat corrupted and i showed this weird bug. Sorry for the inconvenience. 😖
