### ISSUE TITLE
Underground decoration doesn't work

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6589]
I try to add underground decoration, but everything I try fails. Now I set the force_placement flag and used torches to visualize what happens. This is the result

https://youtu.be/f-6g16ahCIs

Decoration is only placed at and sometimes near the chunk borders, but nowhere else. Decoration is only placed on the floor, never on the ceiling.

This is the code

```
minetest.register_decoration({
	deco_type = "simple",
	place_on = "default:stone",
	sidelen = 8,
	fill_ratio = 5,
	--~ noise_params = {
		--~ offset = 2,
		--~ scale = 0.01,
		--~ spread = {x = 200, y = 200, z = 200},
		--~ seed = 23454,
		--~ octaves = 5,
		--~ persist = 0.9
	--~ },
	biomes = {"underground",},
	y_min = -31000,
	y_max = 31000,
	decoration = "default:torch",
	height = 1,
	flags = "all_floors, force_placement, all_ceilings",
})

```

Probably I do something wrong, but I have no idea. It doesn't matter if I use fill_ratio or noise, it doesn't matter if I change sidelen, add or remove biomes, y_min and y_max and so on. Result is always the same

Edit: I used the mese post lamp and now it looks like the Great Hall in Hogwarts. 

![screenshot_20171105_115129](https://user-images.githubusercontent.com/16163058/32414100-ec0ed55a-c21f-11e7-8344-ce6c96e7397f.png)

**Comment by paramat** [comment]
WIll investigate.

**Comment by paramat** [comment]
I tried your decoration example in vanilla MTG and it works as expected. Perhaps there is some interaction with a subgame or mod?
Your screenshots and video show decorations appearing at mapchunk borders only, and where a tunnel meets a border on floors too.
BTW 'height = 1' is not needed, the default is 1 because the default decoration is only 1 node high.

**Comment by MarkuBu** [comment]
The biome and decoration registrations are from MTG0.4.16

Is there anything new or different in mapgen.lua that is required to get the decorations work?

**Comment by paramat** [comment]
I tried using the default/mapgen.lua from 0.4.16 stable in latest MTG, plus an underground decration, also works as expected. what commit is your engine on?

**Comment by MarkuBu** [comment]
I downloaded and compiled the engine about 2 weeks ago. I made an update 2days ago, but didn't try the cave decoration.

Let m try that with vanilla MTG. I use for the subgame MTG 0.5, but I clear ores, biomes and decoration and replace it with some older definitions

**Comment by MarkuBu** [comment]
Thanks for investigation. Works with vanilla. But I have no idea what causes this behavior.
