### ISSUE TITLE
 Liquids emitting little light are dark

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6597]
The problem appears only with smooth lighting disabled.

Here, `light_source` is 0:
![screenshot_20171107_005730](https://user-images.githubusercontent.com/7352626/32466175-175033de-c357-11e7-93d8-525b620a4043.png)

And here, `light_source` is 1:
![screenshot_20171107_005716](https://user-images.githubusercontent.com/7352626/32466180-1b59e9de-c357-11e7-903c-e85aa287d6bc.png)

The problem is that at [content_mapblock.cpp:397](https://github.com/minetest/minetest/blob/master/src/content_mapblock.cpp#L397) light level for light-emitting liquid is overridden by its `light_source` value even if the latter is smaller. (Note that the problem is there since d8edd3d0c8 [yes that’s 5 years ago]; it might not be noticed because no one actually uses low `light_source` values).

**Comment by paramat** [comment]
@juhdanad

**Comment by azekillDIABLO** [comment]
I already saw this bug, i thought it was related to alpha parameters 😕
