### ISSUE TITLE
Yet another feature request.

### ISSUE THREAD

**Issue by NewbProgrammer101** [minetest/minetest#6602]
This is a controversial one. Ready? 
Set.
Go.

minetest_game should be rewritten in C++ because of... performance. 

Lua is somewhat singlethreaded, which is not for what we have our computers as. We now have multi-core CPUs. When I use Lua mods, it uses 100% of one, just one core of my 8 core CPU.

It should be rewritten in C++ because it can be compiled. I know that there's luajit, but we don't compile our mods.

A few more things that I can't think to say at the moment.

**Comment by rubenwardy** [comment]
Sorry, but the performance demand of Minetest Game is very minimal. For the most part it just defines items and some basic callback functionality which may not be ran every tick. If we were to write anything in mods in C++, it would be for intensive stuff related to map manipulations such as searching an generation.

This is not controversial.
