### ISSUE TITLE
Skip plant rendering when too far away

### ISSUE THREAD

**Issue by tobyplowy** [minetest/minetest#6607]
If Grass And Flowers are Too Far Away you don't see them So Why should they be rendered?
If they get unrendered than that will save some performance and on bigger render distances this can have a very big positive effect on the performance

Also we whant to have big amounts of grass in farlands but My gaming pc is struggling 
(keep in mind that I can play GTA V on this computer on Max settings) decreasing the amount of faces that need to be rendered wuld help, think about it every plant has 4 polygons (I think) this adds up extremly fast and before you know it you have 500 (probably more) polygons on screen that you can't even see 
(becouse it is just 1 or 2 pixels on screen or becouse it's blocked by a tree)

**Comment by paramat** [comment]
:-1: 
The appearence and colour of a landscape would still change dramatically even at long distance, imagine dense white flowers on green grassland, the terrain would change from white to green.
If your device is struggling then reduce your view range, it's better to see a shorter distance of higher quality landscape than a longer distance of broken landscape.
The real solution to this celeron55's 'farmap' feature #3502

**Comment by MarkuBu** [comment]
When will farmap be merged?

**Comment by tobyplowy** [comment]
flowers
![naamloos](https://user-images.githubusercontent.com/16853304/32664785-93dc10ac-c632-11e7-8de4-d0cf4835c2a4.png)
can you still see them
![f](https://user-images.githubusercontent.com/16853304/32664781-915af6fe-c632-11e7-8a61-b3c32a688e7b.png)
cant see them here have a hint
![f](https://user-images.githubusercontent.com/16853304/32664955-10bef346-c633-11e7-8764-6f7216ebdf5a.png)
still not 
![f](https://user-images.githubusercontent.com/16853304/32665033-456df11e-c633-11e7-9e5e-e3d7c4840ab3.png)

im using a big monitor with a 1920x1080 and i cant see those pixels they are completly usless and shuld not be rendered (its a waste of performance)

@paramat why dount you add a setting so the flowers can stay as they are but the grass can be unrenderd

**Comment by sfan5** [comment]
> im using a big monitor with a 1920x1080 and i cant see those pixels

consider buying a new monitor and going to an optician

**Comment by tobyplowy** [comment]
@sfan5 thanks, well I will just save you your time and close this issue
This Would Be A Good feature (as setting maybe) but you guys don't seem to whant to inprove minetest

So simple close!

**Comment by tobyplowy** [comment]
@sfan5 also your comment was pretty funny to me

Becouse I just bought a new monitor 3 weeks ago

And my last visit to the optician was 2 months ago 
(and he said that my vision was very good well above average)

**Comment by paramat** [comment]
I can see those flowers, and as i explained, plantllike may have much larger or brighter textures or might be stacked several nodes tall. FOr your example you used tiny flowers that are not much different in colour or brightness to grass.
Obviously we don't want to improve MT ;]
I appreciate you thinking about this though and suggesting, but it's just not practical and would look weird.

**Comment by tobyplowy** [comment]
> Obviously we don't want to improve MT ;]

It's Just anoyes me to see good minetest features (mob api) get pushed away in faver of things poeple in the community (non modders) don't care about (client side moding) 

> I appreciate you thinking about this though and suggesting, but it's just not practical and would look weird.

Yes I know it may be impractical but it's the only way to have alot of plants without loseing performance
Farmap may fix this I dunno :/

**Comment by JeanPaulLucien** [comment]
@tobyplowy oh, I suggested same about grass after 5 years. They were disagree too. Looks like they don't like this project.
https://github.com/minetest/minetest/issues/13090
