### ISSUE TITLE
Sometimes it is black below floatlands

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6609]
If I look out of a cave at the bottom of the floatlands down to earth it is just black. If someone assumes that he can jump in a cave he is screwed

Flymode disabled
![screenshot_20171110_182840](https://user-images.githubusercontent.com/16163058/32670832-535f0ad0-c645-11e7-9f3b-e9a443a88f03.png)

Flymode enabled
![screenshot_20171110_182842](https://user-images.githubusercontent.com/16163058/32670834-551a10f4-c645-11e7-8082-1b21ea935807.png)

It doesn't happen every time and it is difficult to reproduce. After a restart of the world everything is normal. I don't know if it happens with default privs. I have all privs enabled

**Comment by sfan5** [comment]
duplicate #3577
