### ISSUE TITLE
PostgreSQL database error - "Ident authentication failed"

### ISSUE THREAD

**Issue by wnereiz** [minetest/minetest#6614]
Environment: minetest 0.4.16, PostgreSQL 9.6
Follow [this post](https://forum.minetest.net/viewtopic.php?f=5&t=16689) to perform migration, always failed to connect to postgresql backend with error:

> \# minetestserver --migrate postgresql --world "/var/lib/minetest/minetest"                                                            
> 2017-11-12 10:22:01: ERROR[Main]: An unhandled exception occurred: PostgreSQL database error: FATAL:  Ident authentication failed for user "minetest"
> 2017-11-12 10:22:01: ERROR[Main]: In thread 7f1b6575c880:
> 2017-11-12 10:22:01: ERROR[Main]: /home/abuild/rpmbuild/BUILD/minetest-0.4.16/src/main.cpp:e2: int main(int, char**): A fatal error occured: PostgreSQL database error: FATAL:  Ident authentication failed for user "minetest"
> 2017-11-12 10:22:01: ERROR[Main]: Debug stacks:
> 2017-11-12 10:22:01: ERROR[Main]: DEBUG STACK FOR THREAD 7f1b6575c880: 
> 2017-11-12 10:22:01: ERROR[Main]: #0  int main(int, char**)
> Aborted (core dumped)

The user and database created with:
```
CREATE USER minetest WITH PASSWORD 'minetest';
CREATE DATABASE minetest OWNER minetest;
GRANT ALL PRIVILEGES ON DATABASE minetest TO minetest;
```
Database connection configure in world.mt:
```
pgsql_connection = host=127.0.0.1 port=5432 user=minetest password=minetest dbname=minetest
```
I'm sure that I compiled with postgresql support in my spec file:
```
...
BuildRequires:  postgresql-devel
...
%build
%cmake \
  -DCUSTOM_DOCDIR="%{_docdir}/%{name}" \
  -DCUSTOM_LOCALEDIR="%{_datadir}/locale" \
  -DCUSTOM_SHAREDIR="%{_datadir}/%{name}" \
  -DBUILD_SERVER=ON \
  -DRUN_IN_PLACE=OFF \
  -DENABLE_GETTEXT=ON \
  -DENABLE_FREETYPE=ON \
  -DENABLE_SYSTEM_JSONCPP=ON \
  -DENABLE_POSTGRESQL=ON \
  -DENABLE_LEVELDB=ON \
  -DENABLE_REDIS=ON
...
```

Any ideas?

**Comment by nerzhul** [comment]
your creation is okay but you didn't modify pg_hba to add md5 auth to your minetest server local IP address, then server should match ident and see you are connecting to mt database with a UNIX user which is not minetest.
