### ISSUE TITLE
Stereo sounds do not become more quiet when you move away from source position

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6615]
How to reproduce this very odd bug:

- Add a mod with a Ogg sound file in stereo
- Play this sound with `minetest.sound_play` and set the `pos` argument

Expected result: The further away you are from `pos`, the more quiet the sound will be
Actual result: The sound is always played at full volume, no matter how far away you are. Only if you got beyond the `max_hear_distance` the sound will no longer be hearable.

For comparison: Do the same with a mono sound, it will work fine.

Note: This also affects footstep sounds, dig sounds, etc.

Tested in MT 0.4.16.

Hands-on evidence: MineClone 2 version 0.29.2: Compare mob footstep sounds on grass blocks  (mono) with the mob footstep sounds on any snowed block (stereo).

**Comment by sofar** [comment]
Not a bug. Don't make them stereo. This has been discussed ad nauseam before.

**Comment by jastevenson303** [comment]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L630

**Comment by Wuzzy2** [comment]
Oops, sorry. :-(
I have overlooked that part in the docs.
