### ISSUE TITLE
Add examples for ore types

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6618]
It would be helpful if there where some examples for the different ore types. Sometimes it is difficult to find values that are working at all. Currently I'm fishing in cloudy waters and an example in lua_api.txt would be more helpful for everyone compared to an answer in the forum

**Comment by paramat** [comment]
Examples can already be found in MTG, so not much need for duplicating them in lua_api.txt. Likewise for biome and decoration registrations. I consider MTG to partly be example documentation for everything.

**Comment by MarkuBu** [comment]
I can't find examples for sheet, puff, vein or stratum. Only blob and scatter.

Currently I try to use stratum, but I can't find values that are working in any way

**Comment by paramat** [comment]
Ah sorry of course, some are unused.

**Comment by MarkuBu** [comment]
Done

https://forum.minetest.net/viewtopic.php?f=47&t=15272&p=300019#p300019

**Comment by paramat** [comment]
Many people do have problems using sheet and i expect puff and vein are also hard to tune.

**Comment by SmallJoker** [comment]
There's a development wiki. Why can't such examples be added there instead of cluttering our lua_api even more?

**Comment by paramat** [comment]
Because the wiki is always out of date, a pain to update, and many don't look at it because it can't be trusted =)
Ores have a special need for examples as few types are used in MTG and they are difficult to understand.

**Comment by paramat** [comment]
But then, if we do examples for ores, we will have to do examples for biomes, decorations etc. to be consistent, this would have to be a new separate document and will be a big task.
Games and mods are already a good source of examples, maybe the minimal game wil be updated to include every ore type, @numberZero has suggested updating minimal game to have at least one of everything.
So i'm not keen on creating example documents, i'd prefer examples in minimal.
Please move discussion to #5192
