### ISSUE TITLE
Add warning when stereo sounds are loaded

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6622]
So I recently learned that stereo sounds are taboo in Minetest.

It took me **weeks** to figure out why the snow sounds in my subgame are so weird and broken. The answer was of course they were in stereo … XD

Here's a suggestion: When Minetest detects that it has loaded a stereo sound, write a warning into the console.

**Comment by rubenwardy** [comment]
For sounds played with positions, this is definitely needed

**Comment by paramat** [comment]
However if we follow this logic then we would have to add warnings for absolutely everything, which is impractical. Better to add clearer or duplicated documentation to lua_api.txt and not add unnecessary code bloat.
:-1:

**Comment by Wuzzy2** [comment]
It's a common, **subtle**, easy-to-introduce and hard-to-spot bug if you don't know where to look, so IMO this is very justified. The “subtle” is the key point here. By the way, Minetest already cries about faulty PNG color profiles.

Also, I never said we should add warnings for absolutely everything. You're overthinking this. Stop taking everything to its extreme, paramat!  :neutral_face: 
Let's just decide this on a case-to-case basis.

**Comment by MarkuBu** [comment]
It's libpng, not Minetest, that is crying, afaik.

It's a documented feature, that mono sounds have to be used for positional sounds. It's the second sentence in the chapter "Sounds". Why add a warning?

As we say in Germany: "Wer lesen kann ist klar im Vorteil" ;-)

**Comment by paramat** [comment]
I know it's not more common than many other mistakes because i have monitored MT closely for years. Reading docs quickly solves the issue. The warning could be made clearer, more detailed, maybe even repeated in docs, we would welcome a PR for that.

**Comment by dsohler** [comment]
> "Wer lesen kann ist klar im Vorteil" 

But nobody reads the unorganized unmaintainable mess that is called a “documentation”.

**Comment by MarkuBu** [comment]
I agree, this can't be called "documentation". But in this case it is really easy to find

**Comment by paramat** [comment]
People do read the docs obviously.

**Comment by paramat** [comment]
Ok i can see how this mistake might be difficult to detect, so removed my -1.
