### ISSUE TITLE
player position on Server 1 block to low.

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#6623]
Hello
If I try to play on my Server the Player figure is positioned 1 block deeper as the ground but moves such as the positioning would be right. How can I solve this? Local Play is working normally.
I am using the actual github version.

Minetest 0.5.0-dev-9a41a3d (Linux)
Minetest_Game 0.4.15-190-geb5a5b5

Thanks

**Comment by rubenwardy** [comment]
Updated Minetest Game

**Comment by JPRuehmann** [comment]
Problem not solved!
![screenshot_20171114_085802](https://user-images.githubusercontent.com/4321829/32769115-d7b11396-c91a-11e7-8398-57dae827fb8b.png)
Minetest 0.5.0-dev-8ea8633 (Linux)
Minetest_Game 0.4.15-208-g3ae382c

**Comment by SmallJoker** [comment]
Your minetest_game is still outdated. The git hash from your recent post isn't known in the official repo.
`git checkout master`, `git fetch upstream`, `git pull`, retry.

**Comment by sfan5** [comment]
it is a known commit hash actually https://github.com/minetest/minetest_game/commit/3ae382c
but something is still off, otherwise it would work

**Comment by JPRuehmann** [comment]
git checkout master gives
```
git checkout master
Bereits auf 'master'
Ihr Branch ist auf dem selben Stand wie 'origin/master'.
```
git fetch upstream gives
```
git fetch upstream
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
git pull gives
```
git pull
already up-to-date.
```
