### ISSUE TITLE
Gradient for ocean depth

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6626]
If you want to make the world flat (reduce the scale of mgv7_np_terrain_alt) the ocean also becomes flat. You can only move the offset to more negative values, but this will cause more water in the world and only adds a few nodes. 

Maybe some kind of (optional) gradient would help. Just a multiplier that increases by depth can make oceans deeper, but the shore stays mostly as it is.

The multiplier is always 1 at water level and increases, the deeper the ocean is (or stays at 1 to leave everything as it is)

**Comment by paramat** [comment]
I see what you mean but i think there are better methods for making land area more flat, such as making it flatter in some places only. I'm not too keen on altering mgv7 surface terrain as it's an old mapgen, seems better to add flat area features to new mapgens, carpathian already does, my mapgen in dev has flat areas too.

**Comment by MarkuBu** [comment]
With "flat" I don't mean _____________________

I want the main part of the world somewhere between 1 and ~20 and not like in MTG between 1 and 40 or more.

I'll take a look at carpathian. Never used it. Are the noise parameter documented somewhere?

**Comment by paramat** [comment]
I think i understand, if you want land from 1-20 and want land and ocean areas roughly equal, then ocean also becomes 1-20 nodes in depth, therefore shallow. You are requesting a vertical 'stretch' of ocean terrain below water level to make it deeper in this situation.

**Comment by MarkuBu** [comment]
Ok
