### ISSUE TITLE
Disable snowfall for certain decorations

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6627]
I request to disable the snowfall (`node_dust` from biomes) on particular decorations.

So that this does not happen anymore:
https://i.imgur.com/qPynoH3.png
(Screenshot shows a flower with a snow `node_dust` on top)
(FYI: The flower has `buildable_to=false`)

Clarification: A snow counts as being “on” an decoration when it would land on top of a non-air node of that decoration. This means, air-only columns of decorations can be ignored (they will always allow snow).

///////////
EDIT by paramat:

![qpynoh3](https://user-images.githubusercontent.com/3686677/32863409-4ce501ac-ca53-11e7-9115-8d44ca0603bd.png)

**Comment by azekillDIABLO** [comment]
Myabe try instead doing it with moresnow mod? actually how doe this node_dust even work? :D

**Comment by paramat** [comment]
```
		content_t c = vm->m_data[vi].getContent();
		if (!ndef->get(c).buildable_to && c != CONTENT_IGNORE && c != biome->c_dust) {
			vm->m_area.add_y(em, vi, 1);
			vm->m_data[vi] = MapNode(biome->c_dust);
		}
```
The 'buildable_to' node parameter decides whether dust is placed on top, this is why this doesn't happen in MTG. Perhaps there is a better way to decide when to place dust on top? If so what node parameters should decide this?

**Comment by paramat** [comment]
Ok good request. I was thinking that dust nodes look wrong on any non-cubic node, so we could decide it on the drawtype of the node below.

**Comment by paramat** [comment]
PR #6629 please test.

**Comment by Wuzzy2** [comment]
Why only checking the drawtype? Wouldn't it make more sense to check the collision box type, which represents the actual physics of the node? In its simplest form, it could simpy check if its the default full cube or the `regular` node box type (which is the same). And all other collision boxes reject snow.

I think basing this on drawtype is flawed, because the drawtype is only an illusion and does not represent the actual physics. What if you have a full solid node which happens to be invisible (`drawtype="airlike`) (just as an example).

**Comment by paramat** [comment]
It's very rare for decorations to have a collisionbox that is different from their visual appearence, i've never seen that happen.
The check would have to be for a collisionbox top surface that is identical to the top face of the node's containing cube, that would be 5 value checks (y co-ordinate and X.Z values of 4 edges).
This is 1 small part of mapgen and is repeated 6400 times per mapchunk, so a reasonable and simple solution is needed, even if it isn't absolutely perfect for every possible edge case.

> What if you have a full solid node which happens to be invisible (drawtype="airlike) (just as an example).

'walkable' but invisible is a very unlikely case for a mapgen decoration, unlikely for any node. With my method dust would not be placed on top, but if it's invisible it would look weird to place dust on top anyway.

**Comment by Wuzzy2** [comment]
Fine. I can live with that. My concern is mostly of theorecial nature.

But then it should be at least written in the docs how `node_dust` works and where it refuses to be placed on top (to avoid confusing surprises).

**Comment by paramat** [comment]
I don't think documenting that is necessary, as the behaviour will be fairly intuitive and as expected.

**Comment by paramat** [comment]
#6629 merged.
