### ISSUE TITLE
Artificial Lighting: brighter, add colorization

### ISSUE THREAD

**Issue by mauvebic** [minetest/minetest#663]
![multiclight](https://f.cloud.github.com/assets/3228975/390304/9252b602-a73b-11e2-8375-35482f736951.png)

brightness: it takes an unreasonable amount of torches to adequately light an area.

colorization: this is one MC feature we are thoroughly lacking and most people seem to want. This would likely require attaching RGB (0-255 or 0-25) values to said light sources. I know this isn't highest priority, but it would be nice to know if/when it'll happen :-)

**Comment by DerpyPony25** [comment]
Cool! 1+

**Comment by tobyplowy** [comment]
@paramat can this actually be added to minetest?

**Comment by DerpyPony25** [comment]
i wish could be this mod

**Comment by wilkgr76** [comment]
> (would require doubling the size of a MapNode)
Huh, seems familiar xD

**Comment by C1ffisme** [comment]
How would this work if two light sources of different colors were placed near each other? Would the colors mix, or no?

**Comment by tobyplowy** [comment]
> Would the colors mix

That would be the best way

**Comment by C1ffisme** [comment]
@tobyplowy It would be nice, but it also means a lot processing is required for lighting updates, and we need to store more bits for each block to make sure all the color mixes are covered.

**Comment by beyondlimits** [comment]
#2670

**Comment by LoneWolfHT** [comment]
*bump*

**Comment by paramat** [comment]
Discussion has moved to #2670 please bump that one not this.
However, the feature has been discussed at length and is disruptive and a lot of work. So i cannot see the point of 'bumping' unless you have something useful to add.
