### ISSUE TITLE
Player (and other) models look flat

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6630]
The reason is that there's no shading.
We could at least define a fixed light source like we do for blocks to give the models some depth.

**Comment by tobyplowy** [comment]
@lhofhansl I don't think that's a good idea it will make everything look very bad and off
Keep in mind that this is my opinion

**Comment by Calinou** [comment]
> I don't think that's a good idea it will make everything look very bad and off
> Keep in mind that this is my opinion

Please give actual arguments and rationale. We know it's your opininon, too 😉

**Comment by lhofhansl** [comment]
Is just seems that players and mods are part of the "world". Everything else is shaded (if statically), but models are not. IMHO we could at least to the same static shading (i.e. a fixed location light source) for models.

**Comment by paramat** [comment]
Static shading would be good, but hopefully it would match world shading, which is: Top brightest, N/S darker, E/W darker, base darkest.

**Comment by lhofhansl** [comment]
@paramat Right. At least do the same shading. Now, I don't, yet, know how to do that really, just wanted to gauge interest.
If somebody has pointers I'd be interested.

**Comment by paramat** [comment]
The code that shades nodes and meshes in the world is described here https://github.com/minetest/minetest/pull/4961#issuecomment-272131460
PR that applied it #5172

**Comment by lhofhansl** [comment]
Thanks. I had no idea how hard-coded things are. :)
Was trying to add a light source to scene-manager... That works generally but I would have study how avoid moving the lightsource, etc.

I'll try to do the same hardcoding too. Note that models do change their angle, though. So it's not static. It looks quite cool when model move around the shading changes according to angle.

**Comment by paramat** [comment]
If using lightsources is easier then 2 placed above and N/S of the model would be the closest match. But maybe it can be simpler since we are trying to match the simple shading of nodes.
If all else fails then the node-style shading being fixed relative to the model (so shading turning with model yaw) would be acceptable i think.

**Comment by HybridDog** [comment]
I think objects and nodes should be lighted the same, so you can make a hide and seek mod: https://www.youtube.com/embed/8eqxZN6meCE (Gmod example)

**Comment by lhofhansl** [comment]
I have a change that mostly does the right thing.

However, it looks like other models (mobs) do not have their normals set correctly. Is that true? Can I not expect other meshes having correct normals?

**Comment by paramat** [comment]
No idea.

**Comment by lhofhansl** [comment]
Hmm... Works fine for the player model, but not any mob mesh I tried. (and they are handled/loaded by the same code)

**Comment by ClobberXD** [comment]
If a lightsource is added for shading, it shouldn't be static, and should follow the movement of the sun instead. This way, objects will be shaded in sync with the sunlight.

**Comment by paramat** [comment]
I disagree, because the whole world is shaded in a way independent of sun/moon position:

Top is brightest.
N/S equal and a little darker.
E/W equal and darker again.
Base darkest.

Matching that will make the models look a part of the world, and is also simpler than a moving source.

**Comment by ClobberXD** [comment]
Nodes are fixed in position, and a static lightsource would be better-suited. But objects aren't necessarily static, and a moving lightsource (in sync with the sun/moon) would make them look _much_ more realistic, IMHO.

**Comment by paramat** [comment]
Realism isn't desirable, looking a part of the MT world is, so the same shading is optimal (and simpler) :)

**Comment by ClobberXD** [comment]
Both 6165 and 6839 seem to be awesome and are features, which I feel, should definitely be a part of MT. I wish someone could take them up and get the remaining issues fixed. :(

**Comment by LoneWolfHT** [comment]
Don't we have this now?
