### ISSUE TITLE
minetest.texture_exists

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6634]
I suggest to add the function `minetest.texture_exists` to the Lua API.

Syntax:

`minetest.texture_exists(file_name)`

Arguments:

* `file_name`: Full file name (w/o path) of texture to check

Returns:

* `true` if the texture exists and has been loaded (no matter if its from a mod or texture pack)
* `false` if the texture does not exist

Rationale:

This will for optional textures, i.e. textures that *can*, but do *not have to* to be added in a texture pack (without falling back to the default).

**Comment by sfan5** [comment]
Texture packs are entirely client-side, this can't work.

**Comment by Wuzzy2** [comment]
Argh, you're right. :-( This is a huge problem.

It's not an important request, however. Unless someone has a very good idea, feel free to close this.
