### ISSUE TITLE
Color getter function for palette textures

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6635]
I you have a palette texture (for this hardware coloring feature), it is impossible to grab these colors directly (in Lua).

I request a getter function for this. Syntax:

`minetest.get_palette_color_by_index(texture_name, index)`

* `texture_name`: File name of the palette texture
* `index`: Index

Returns:

* On success, a `ColorString` of the color at the specified palette index
* If the index is out of bounds, or the texture does not exist, return `nil`

Use cases:

* Specify a static node `color` by reading it fom the palette (instead of hardcoding it)
* Allow to specify colors for basically everything with the help of texture packs (since they can simply overwrite the palette textures). I think this will be very useful

**Comment by sfan5** [comment]
The server can't load textures, this is impossible.

What's the use case on this anyway? Hardware coloring is already done using indexes (see [here](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L548)).

**Comment by juhdanad** [comment]
I agree that the server should be able to load image files (not as textures). Sometimes it's easier to draw the mod data than to code it. But it should be another feature request.
