### ISSUE TITLE
minetest.colorspec_to_colorstring

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6636]
There's no function in the Lua API to convert a `ColorSpec` to a `ColorString`.

It's a bit annoying if you got a `ColorSpec` from one function and need to feed a `ColorString` into another function (or a formspec string), but there's no converter function. So you have to do it “by hand” (and this will break anyway if the `ColorSpec` format is extended in the future).

I suggest to add this function:

Syntax: `minetet.colorspec_to_colorstring(colorspec)`

Arguments: `colorspec`: A `ColorSpec`

Returns: `colorspec` converted to `ColorString`.

**Comment by sfan5** [comment]
> (and this will break anyway if the ColorSpec format is extended in the future)

No, backwards compatibility needs to be ensured if such a thing is done.

**Comment by Wuzzy2** [comment]
Ah. Good.
That doesn't invalidate my request, however. :P

**Comment by paramat** [comment]
Any core dev support? (i'm neutral).

**Comment by paramat** [comment]
Well, seems to make sense, i support.
