### ISSUE TITLE
Fork Irrlicht

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6637]
Ok, so before you go all crazy saying, "NOOOOOOO" and "WHAAAAAA?" and "not gonna happen."
Caleb and I were talking about where Minetest was headed, where it should go, what needs work, etc.
We started talking about the possible replacement of Irrlicht and how much work would go into that, then we had a crazy, but possibly ground-breaking idea(and no its not a shovel ;) ).
What if, instead of replacing Irrlicht, we make a customized version of it and use that for MT instead of trying to replace it. It has already been proven to work, just take a look at SuperTuxKart. Irrlicht had what they wanted, just they tweaked it a bit to fit their needs.
By having a custom rendering engine just for MT, you guys could create the tools necessary for adding, say shadows. Improve what Irrlicht doesn't have instead of limiting yourself to its own boundaries

**Comment by ThomasMonroe314** [comment]
Not only would it allow for the above possibilities, but it would also be isolated from MT, so it would not affect the structure of the code at all.

**Comment by Calinou** [comment]
I don't think the gameplay and general user experience will be improved by spending dozens (if not hundreds) of hours working on an engine fork.

**Comment by rubenwardy** [comment]
Waste of time for not much gain

**Comment by rubenwardy** [comment]
#5365

**Comment by paramat** [comment]
:-1: for reasons above.

**Comment by ThomasMonroe314** [comment]
@rubenwardy OK, that would be a little of what I'm talking about.
@Calinou the game's "play" might not be improved much, but it would open up a lot of possibilities for "eye-candy" type stuff, like shadows and shader packs(poor example, ik).
I understand that at this point in time you guys are all busy with 0.5.0 coming out, so something like this may not sound like it would be worth it. But think about after 0.5 comes out, most of the bugs have been fixed,the question is what comes next? more minute features? or is MT going to improve in a way that is fairly noticeable by the players?
Sorry for being blunt, I'm not very good at tip-toeing around controversial subjects.

**Comment by Reedych** [comment]
:-1: it will eat much time for maintaining. So, it's easier to switch to another 3D engine.

**Comment by nerzhul** [comment]
No need to fork irrlicht, we just need either use it more, and enhance client intelligence as now it's just a stupid client, and CSM is here for that, or change the engine, but it doesn't change that the client is a stupid box.
Another point, client rendered and event handlers should be on separated threads

**Comment by ThomasMonroe314** [comment]
@nerzhul ok, good point.

**Comment by rubenwardy** [comment]
Shapes and shader packs is already possible with irrlicht

**Comment by paramat** [comment]
There already is plenty of potential for eye-candy, we just lack people working on it.

> I understand that at this point in time you guys are all busy with 0.5.0 coming out, so something like this may not sound like it would be worth it.

Limited core dev time will continue after 0.5.0 is released, 0.5.0 isn't making much difference to how busy we are.

> But think about after 0.5 comes out, most of the bugs have been fixed

Bugs are not falling in number, we have 248 bug issues.

> the question is what comes next? more minute features? or is MT going to improve in a way that is fairly noticeable by the players?

That's insulting, we are always making significant improvemwnts and adding significant new features.

**Comment by numberZero** [comment]
http://irc.minetest.net/minetest-dev/2017-12-28#i_5182234
But instead of forking IrrLicht ourselves, we can use some existing fork like https://github.com/buildaworldnet/IrrlichtBAW, as @rubenwardy just [pointed out](https://github.com/minetest/minetest/issues/2746#issuecomment-380938870).
