### ISSUE TITLE
Extend active block range out in player directions?

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6642]
It always bothered me that mobs simply disappear when they got out of range.
We could add an _extra_ volume in the direction that player is looking (that would apply to ABMs as well).

We'd make this FOV dependent. If we wanted to no more than double volume (i.e. the server work) we'd calculate the distance of the extra volume like this:
`distance = cbrt(1 / (1/2 * (1-cos(fov/2))) )`
So we'd do the default sphere we have now _plus_ the view-cone with the longer distance.

For default fov we can about double the distance for the extra view cone. For zoom of 15 we can look 6x further - and still have just doubled the server's work, for zoom of 10 it's 8x, etc.

Also note since the default is a full sphere the extra volume is same as increasing the active block range by 26% (1.26^3 ~ 2)

This comes from the fact that volume of a sphere is `4/3*pi*r^3`, and a spherical section is `2/3*pi*r^3*(1-cos(fov/2))`.

Perhaps we wanted to increase the volume by 50% at most we'd simply remove the 1/2 factor, etc.

All this has the advantage that things still happen where the player isn't looking within the default sphere, and things happen with further distance where the player is looking.

**Comment by paramat** [comment]
Not for ABMs though, they are mostly used for environmental changes that should be independent of player view. Also, ABMs are very intensive, we can't increase the volume they are active in.

**Comment by lhofhansl** [comment]
Can't do the two independently, unfortunately.
The ABM work is proportional to the volume, so we can increase it. 

As said above doubling the volume is equivalent to increasing the radius by 26%. If that's a concern one can reduce the normal distance by 26% to compensate (but I think that would be Overkill)

**Comment by paramat** [comment]
We can't have separate range settings for active objects and ABMs?

**Comment by lhofhansl** [comment]
No they are intertwined. Both user active blocks. I can see whether we can have active blocks and still not have ABM run on them.
I'd love to them separate.

**Comment by lhofhansl** [comment]
Hmm... I have a change that separates the two. Needs some work, pretty inefficient right now.
ActiveObjects I'd probably also limit to the player view_range - as it's already done when sending them to the client (ABMs would _not_ be limited that way).

Maybe that's a better answer, less complex answer anyway. Allow the two distances to be set independently.

**Comment by lhofhansl** [comment]
I have the active_object_range now separated from the active_block_range. (i.e. blocks can be activated to store active object, yet, not run the active block modifiers).

For the specific extension of range along the camera direction, the problem is that the code still needs to enumerate all the blocks in a sphere just to determine whether they are visible or not. That turns out to be expensive, especially when zooming is on... At high powered zoom we might look 60 or more map blocks out, the cube then has over 1.7m map blocks. Of which just 1718 would be visible at FOV 10. Can't find the 1718 without looping over the 1.7m.

Perhaps I can find other ways to enumerate these blocks efficiently... Thinking about that. (could of up the direction and generate circles out or something, but not sure it's going to be cheaper)

(when generating blocks from the server is less of a problem, since (1) the cost is sending them, and (2) there is can be done in layers)

Maybe I'll just submit a PR to configure the active block and object ranges separately.

**Comment by paramat** [comment]
> For the specific extension of range along the camera direction, the problem is that the code still needs to enumerate all the blocks in a sphere just to determine whether they are visible or not.

That occured to me too, however seems a different issue to this, since it is relevant to existing zoom.

**Comment by raymoo** [comment]
Sounds like a rasterization problem.

**Comment by rubenwardy** [comment]
#6667
