### ISSUE TITLE
Ice caves

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#6645]
I know this has been sort of suggested in https://github.com/minetest/minetest_game/issues/1142, but that was a while ago(ish).
_If_ the engine supports this yet, I think it would be a nice addition. Open-air ice caves only would probably be best, though. With things like ground-to-ceiling ice pillars, perhaps stalactites and stalagmites.

paramat said
> Caves in ice do not appear because ice has been made 'not ground content' to avoid ugly holes in ocean iceshelf. It would be good to have caves in 'on land' ice but we would need 2 types of ice, one that is ground content.

I suspect (I could be wrong, I know little about mapgen) that you can check for altitudes before carving caves, so perhaps make it so ice caves are created at higher elevations in things like large glaciers, thus avoiding "ugly holes in ocean iceshelf".

**Comment by srifqi** [comment]
In theory, we can. Haven't checked the code, tho.

**Comment by paramat** [comment]
> you can check for altitudes before carving caves, so perhaps make it so ice caves are created at higher elevations

Possible if hardcoded for ice, the issue is how to code that generally. But yes i'd prefer caves appear in ice, if i can i'll make it so.

**Comment by GreenXenith** [comment]
> This is a MTG issue as the engine code to do this has been added (underground decorations).

I could move that suggestion to MTG, but don't know if I should yet, because ice caves sort of need to be a thing first :P

**Comment by paramat** [comment]
It's sort of already included in the issues for underground biomes and decorations.

**Comment by paramat** [comment]
The best way seems to be having 2 different ice nodes with different 'is ground content' values.
One is fresh ice above sea level, the other sea ice.
This would then be a game/biomes issue.

**Comment by GreenXenith** [comment]
New issue opened.
https://github.com/minetest/minetest_game/issues/2029
