### ISSUE TITLE
Imitate round planet

### ISSUE THREAD

**Issue by Kright** [minetest/minetest#6646]
#### Why
When object appears on maximum distance from fog, it looks quite unnatural.
On round planet, objects rise from behind of the horizon when you move to them. As I think, this will look better.

#### How
In RL Earth is sphere, so distant objects are slightly below horizon. To imitate this effect, one can approximate sphere with parabola. We only need to modify vertex shader. 
```
y -= dx*dx + dz*dz;
```
where dx and dz is distance from camera to vertex in world coordinates (modified y in world coordinates too). 

So, vertex shader become more complex. Something like:
```
vec4 worldPos = WorldMatrix * pos;
float dx = worldCameraPos.x - worldPos.x;
float dz = worldCameraPos.z - worldPos.z;
worldPos.y -= inverseRadius * (dx*dx + dz*dz);
screenPos = ViewProjectionMatrix * worldPos;
```
inverseRadius is 1 / imitated planet radius.

If this is interesting, I can try to write code and make pull-request.

**Comment by azekillDIABLO** [comment]
Well if it's optional and if it doesn't RAM or anything... 👍

**Comment by SmallJoker** [comment]
Already done in a fork/testing repo:
https://github.com/Jeija/spheretest (see Releases page to test)
https://forum.minetest.net/viewtopic.php?f=14&t=15643
https://www.youtube.com/watch?v=ztAg643gJBA

**Comment by rubenwardy** [comment]
I don't that's what they meant. Speheretest is literally a round planet. I think the op doesn't want the planet to actually be round, but wants it to appear round in the horizon

**Comment by MarkuBu** [comment]
I remember seeing a minecraft video where node columns pop up in the distance. The world is still flat, but distant nodes (or maybe chunks) came up. afaik it was also possible to let them drop from the top

**Comment by paramat** [comment]
I saw that video too, looked weird.
:-1: for this suggestion, as MT worlds are flat slabs filling the lower half of a cubic world, there's no point in trying to simulate a spherical planet horizon.

**Comment by MarkuBu** [comment]
Looks interesting, but nothing I would like to have in the game

**Comment by ThomasMonroe314** [comment]
Interesting Idea, but I have to agree with the above comments. this would be something that could be added if shader mods are implemented

**Comment by Wuzzy2** [comment]
Emulating a spherical planet in Minetest?

HERESY!

**Comment by rubenwardy** [comment]
I kind of like the effect if this was with a super realistic subgame. It's something that would be better with some way of making shader mods though.

> The Minetest world isn't round at all

The world could just be massive, it doesn't matter that it's not actually round. It's a nice realistic visual effect.

**Comment by paramat** [comment]
Yes in a subgame that is pretending to be a round planet it may be ok, but no subgame i know of does that yet. So there's very little need.

**Comment by paramat** [comment]
Kright, as an isolated experiment and as an idea this is fine, an interesting thing to do, and can ook good, however:

> When object appears on maximum distance from fog, it looks quite unnatural.
On round planet, objects rise from behind of the horizon when you move to them. As I think, this will look better.

"On round planet"
It's an odd and unsuitable suggestion, don't you think? For a voxel game engine that is inherently and obviously about flat worlds, a cubic lattice, orthogonal axes, where spherical or even curved worlds are impossible to correctly create (not talking abouts shader hacks like Jeija's work), where gravity is in one direction only.
So we can't accept this but i hope you experiment and make the code available somewhere, maybe a fork of Minetest?
