### ISSUE TITLE
libpng warnings

### ISSUE THREAD

**Issue by azekillDIABLO** [minetest/minetest#6647]
I don't know really why size happens, I understood that 'color profiles of .png were missing' but anyway, the game throws plenty (sometimes hundreds) of `2017-11-19 13:07:21: WARNING[Main]: Irrlicht: PNG warning: iCCP: known incorrect sRGB profile` and It's really anoying because the debug console because it's only filled with that. Is there a way to fix that?

**Comment by MarkuBu** [comment]
This is an upstream issue and related to some more strict checks in libpng.

https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

To remove the warning you have to remove the incorrect sRGB profile from the png file. You can find some tips how to do that in this link

**Comment by azekillDIABLO** [comment]
Thank you! Should this be closed then? 😀

**Comment by MarkuBu** [comment]
If this bug is cause by a specific mod you should open an issue there. I assume they made their textures with Photoshop

**Comment by SmallJoker** [comment]
As already said, this is an issue about libpng, not Minetest.

**Comment by HybridDog** [comment]
Fyi: In /usr/include/png.h:3237 (from libpng) there's the PNG_SKIP_sRGB_CHECK_PROFILE implementation option, maybe this can be used to disable the warnings.
