### ISSUE TITLE
Option to delete user

### ISSUE THREAD

**Issue by 00c** [minetest/minetest#6653]
Please add option to delete user without restarting server.

**Comment by Reedych** [comment]
minetest.remove_player(name)

**Comment by paramat** [comment]
Reedych are you saying it exists or that is the form you want?

**Comment by BluebirdGreycoat** [comment]
It exists, but only deletes player data and not the authentication data. The ability to delete authentication data from inside Lua would be useful; especially since now that player files are being moved to database, deleting the files from a script outside Minetest is not so trivial.

**Comment by 00c** [comment]
How do you delete player data?
I refer to player authentication: password, privileges and so on.

**Comment by dsohler** [comment]
> Reedych are you saying it exists or that is the form you want?

So are you saying you don’t know the program you develop, or what?

**Comment by SmallJoker** [comment]
It is already possible right now to remove a player from the player backend using `minetest.remove_player` (as already pointed out above). However, this does not handle the authentication database (by default `auth.txt`).

Do you have a chat command in mind or rather an API function to handle both? Nevertheless, this would require changes [in our auth code](https://github.com/minetest/minetest/blob/master/builtin/game/auth.lua) plus in each mod that offers a different authentication handler before such a function or command can be implemented.

**Comment by paramat** [comment]
Surprise, i haven't memorised the existence of every API in MT, no dev has.

**Comment by dsohler** [comment]
2 seconds web research is too much?

**Comment by paramat** [comment]
I'll explain, i knew i could quickly search for it to see if it existed, but the reason i commented

> Reedych are you saying it exists or that is the form you want?

was because i was stating to Reedych that their comment was unclear and unhelpful, and needed a few more words, i wasn't actually asking if it existed as i could obviously quickly find out myself. Whether it actually existed was irrelevant and i didn't need or want to know.

When i wrote that i did briefly wonder if someone would use it as an opportunity for an attack, there are 2 or 3 who do this.

**Comment by Reedych** [comment]
@paramat it exsts

**Comment by dsohler** [comment]
> i was stating to Reedych that their comment was unclear and unhelpful, and needed a few more words, i wasn't actually asking if it existed as i could obviously quickly find out myself.

Actually no. Nothing in your entire comment leads to this. So instead of deleting other user’s comments accept your flaws.

> I recommend just remove player's string from auth file. Without restarting? I don't know.

New users can be registered while running. I don’t see why unregistering users while running should be an issue.

**Comment by paramat** [comment]
I know what i meant, my comment can clearly mean what i meant, but was open to misinterpretation, which is what you did. So you tell people what their own thoughts are?
I didn't delete any comments, and felt the deletions were not particularly necessary.
Please be nicer, your comments are becoming a problem.

**Comment by dsohler** [comment]
> So you tell people what their own thoughts are?

Read carefully and you’ll find the exact meaning of what I said :smile:

> I didn't delete any comments, and felt the deletions were not particularly necessary.

Okay, sorry for the false accusation then.

> Please be nicer, your comments are becoming a problem, that's a warning.

I am the nicest person ever if we’d meet in real life. But this is not RL but online. And online I hate assholery and react appropriately. But since you are now the official spokesperson of the whole Minetest dev team let’s end the discussion here and let’s get technical again.

As said: “New users can be registered while running. I don’t see why unregistering users while running should be an issue.”. Do I miss something here?

**Comment by paramat** [comment]
> And online I hate assholery and react appropriately.

In most of these situations you are overreacting to a very minor thing in a rude, aggressive and provocative way, it's almost always you who is the instigator, not others. Many of your comments are unprovoked nasty comments, with little contribution.

**Comment by paramat** [comment]
pilino1234 if you have a problem with a comment of mine do writ something, repeatedly leaving down-emoticons on my comments (i've noticed) is cheap attacks.

**Comment by pilino1234** [comment]
> pilino1234 if you have a problem with a comment of mine do writ something, repeatedly leaving down-emoticons on my comments (i've noticed) is cheap attacks.

sweet, a group of pixels count as an attack now. let me get my notepad

> emoticons are not for use as a cheap way to attack someone without writing something, i've noticed your repeated use of emoticons on my comments.

oh noes. lets remove the thumbs down pixels and replace them with rainbow and unicorn pixels

___

my problem is this:

> let’s end the discussion here and let’s get technical again

whereupon you attempted to continue the bickering. nice. 
i can't see the comments that @rubenwardy graciously deleted so I'm not going to make assumptions about their content, but the backpedaling on your part when dsohler pointed out your apparent lack of knowledge about the lua api is pretty facile.

**Comment by BluebirdGreycoat** [comment]
Less noise. More signal.
