### ISSUE TITLE
Setting deprecation messages should contain the mod's name

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#6654]
Hi all,
With this transition from 0.14 to 0.16 some things and behaviors have changed. So Minetest is complaining about some mods, that's alright.

My issue is that the warning messages are not mentioning the mod to blame.
Since they are just warning messages maybe they are not even necessary, and if they are, I believe they should show the mod name so we can actually fix the issue. Otherwise, there is little use for these messages.

Specially if the terminal and log is getting flooded with the same message several times a second.

```
<WARNING> 2017-11-20 13:18:21: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:21: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:21: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:23: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:23: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:23: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:24: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:24: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:24: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:25: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:25: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
<WARNING> 2017-11-20 13:18:25: [Server] WARNING: minetest.setting_* functions are deprecated.  
========================
```

**Comment by sfan5** [comment]
backtrace is logged to infostream, enable `--info`
https://github.com/minetest/minetest/blob/stable-0.4/src/script/common/c_internal.cpp#L188

**Comment by paramat** [comment]
This has been affecting many people, and depending on the mod the deprecation messages can repeat extremely rapidly.

**Comment by sfan5** [comment]
Pretty sure the setting works as expected, people just don't use it.

**Comment by paramat** [comment]
`deprecated_lua_api_handling = `
Please try this setting to disable messages and let us know if it prevents all deprecation messages.

**Comment by Megaf** [comment]
My issue is not about the messages showing up or not, is about them not saying the source ;)
Will try the setting to hide them later and get back here to tell.

**Comment by paramat** [comment]
Yes sorry.
https://github.com/minetest/minetest/issues/6654#issuecomment-345788176 looks easy, will attempt.

**Comment by paramat** [comment]
So, set `deprecated_lua_api_handling = error' to halt MT at the first use of deprecated code, then look at the last few lines of debug.txt for the backtrace.
It may be necessary to alter the 'debug log level' to see the backtrace:
```
#    Level of logging to be written to debug.txt:
#    -    <nothing> (no logging)
#    -    none (messages with no level)
#    -    error
#    -    warning
#    -    action
#    -    info
#    -    verbose
#    type: enum values: , none, error, warning, action, info, verbose
# debug_log_level = action
```
A full backtrace written to terminal on every use of depecated code would be an insane amount of lines, so the mod name alone would need to be added to the terminal message, this would be a fair amount of work and the information you need is already available, so that's probably why sfan5 closed this, understandably.

You're very lucky i got interested in this and helped, you don't deserve it after your negative ranting and insults on IRC, you even had to be encouraged to open an issue, how can we even help and fix something if you don't open an issue? Anymore of that on IRC minetest-hub and i'll kick you off the channel.

**Comment by Megaf** [comment]
My log level is set to **action**

Messages in the terminal still not saying the mod causing them to appear. And this is what this issue is about. So I don't fully understand why it was closed.

Setting **deprecated_lua_api_handling** to just gets rid off the messages altogether. This is not my intention.

What I would like to happen is just have the server running, without stopping, simply informing me what mod is misbehaving. With some kind of flood protection if possible.

**Comment by sfan5** [comment]
> What I would like to happen is just have the server running, without stopping, simply informing me what mod is misbehaving

That is possible if you use `--info` as I said, what you actually seem to want is having the modname displayed at the default log level because you don't want to change it.

**Comment by paramat** [comment]
>  this would be a fair amount of work and the information you need is already available,

That's why i closed it. You can already easily find the information you want so i don't thnk the work needed to separate the mod name and insert it into the warning is justified. 

> What I would like to happen is just have the server running, without stopping, simply informing me what mod is misbehaving
```
Handling for deprecated lua api calls:
error: abort on usage of deprecated call (suggested for mod developers).
```
Aborting on first deprecated call is far more useful than having thousands of warning messages spamming the terminal.

> With some kind of flood protection if possible.

That's even more work, and not justified. The 'error' setting is already there as a way to avoid terminal flooding.

**Comment by paramat** [comment]
Unnecessary and not worth the effort :-1:

**Comment by paramat** [comment]
Sorry, didn't realise it would be this simple.

#6671 merged.

**Comment by rubenwardy** [comment]
Please note this issue wasn't fixed as settings don't print out the line and number due to purely being in Lua

**Comment by sfan5** [comment]
?
I tested my PR with the exact case detailed by Megaf and it did what it should.
