### ISSUE TITLE
Protocol version error disallows connections to non-0.5.0 servers in 0.5.0-dev

### ISSUE THREAD

**Issue by garywhite207** [minetest/minetest#6656]
I downloaded the latest dev build of 0.5.0 from sfan5's forum link, and, while the server list is still full to the brim with servers, all but the 5 that are running on 0.5.0-dev are in grey instead of in white. When I try to connect using the 0.5.0-dev client to any servers that don't run 0.5.0-dev, I get an error message saying "This server supports protocol version between 24 and 34. We only support protocol version 36." I don't think it's isolated as I tried connecting to multiple servers that use 0.4.16 and they all give the same error.

**Comment by paramat** [comment]
Intentional breaking of compatibility for MT0.5.0 https://forum.minetest.net/viewtopic.php?f=18&t=17929
