### ISSUE TITLE
No protection against long-range inventory access.

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#6658]
1) Start game and open a chest containing a bunch of items.
2) Teleport yourself somewhere far away without closing the chest formspec.
3) Take or put items. You may not necessarily see the inventory changes, but they happen.
4) Works with or without built-in anticheat.

The fix: all inventory accesses should check distance to player (perhaps line-of-sight, too, it it could be done fast enough) before allowing player to modify inventory. Can this be done in mod? Yes. But prefer if done in engine: a) performance, b) everybody gets it without having to do anything.

**Comment by tenplus1** [comment]
Wait, how can you teleport anywhere while the formspec is in use ? doesnt it block access to chat ?

**Comment by BluebirdGreycoat** [comment]
You can have someone else teleport you. In my case I used a delayed command. (The need for the delay is another topic.)

**Comment by srifqi** [comment]
So, do you get double items?

**Comment by BluebirdGreycoat** [comment]
No. The inventory access works normally, you just won't see the changes to the far inventory due to distance.

**Comment by paramat** [comment]
NOT line of sight, that's ridiculous.

**Comment by paramat** [comment]
#6665 merged.
