### ISSUE TITLE
Exclude biomes for ores, decoration ...

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6659]
Instead of having a list of biomes where ores or decorations should spawn it would sometimes be easier to have an exclude list

Let's assume you don't want to have a specific ore everywhere except in one biome, the list of biomes would be extremely long. It would be easier to write

`exclude_biomes = {"xxx"}`

**Comment by paramat** [comment]
> Instead of

Do you want the exclude feature in addition to the inclusive? Or as a replacement?
I disagree with a replacing.

**Comment by MarkuBu** [comment]
Addition. With "instead of" I mean that you can write 

exclude_biomes = {"XXX"} 

instead of 

biomes = {"a long list of biomes except XXX"}

**Comment by paramat** [comment]
Ok just clarifying, seems possibly a good idea, we can have up to 256 biomes after all.

**Comment by paramat** [comment]
This is friendly towards the modder but codewise is complex to do, all the code depends on inclusive lists. Since this is not much of an issue and low priority i prefer to keep the code simple :-1:
