### ISSUE TITLE
Stair smoothing speed isn't consistent

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#666]
It can take a really long time (1 second) to move the camera up when climbing stairs, but sometimes it's almost instant (0.2 seconds). This bug is present since nodeboxes were added.

**2014-04-07: not sure if still here.**

**Comment by nerzhul** [comment]
Is there already present ?

**Comment by paramat** [comment]
Personally i haven't experienced this recently, anyone else?

**Comment by C1ffisme** [comment]
Not me...

**Comment by indriApollo** [comment]
me neither

**Comment by nerzhul** [comment]
Then i close it.
