### ISSUE TITLE
Set drawing layers of HUD images/statbars/etc.

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6661]
Currently it seems to be impossible to explicitly specify the order in which HUD elements (builtin elements, `hud_add`) are drawn.

You can only do so indirectly by calling `hud_add` in the correct order. This works, as long all of the mods are under your control.
As soon you have to deal with external mods or builtin, you can't really control the order anymore. The draw order now depends on luck, more or less. :D

If I could specify the draw order, life would be a bit easier.

Practical use case:
I want to draw background icons for the **builtin** health statbar (i.e. “grayed out” hearts). Currently this is impossible, my background statbar is always drawn on top, making the health statbar unreadable. It seems impossible to reverse the draw order.

**Comment by ClobberXD** [comment]
Coming to think of it, the background icons for the health statbar could be builtin too, as it's a useful feature to have.

**Comment by jastevenson303** [comment]
Here is a very interesting reply by @SmallJoker on the forum regarding the
precedence of formspec elements, in regards to Irrlicht versus Minetest:
https://forum.minetest.net/viewtopic.php?t=21691#p339399 -- perhaps it's
related.

>Irrlicht code: Buttons, dropdown lists, checkboxes, labels and input fields
>Minetest code: Images, inventory lists, itemstacks (also as images),
tooltips and boxes.

**Comment by Wuzzy2** [comment]
Fixed by #9087.
