### ISSUE TITLE
Add param3

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6663]
param2 becomes more and more overused and we get more and more conflicts, for example: "should I use hardware coloring or meshoptions for grass?" I would like to be able to use both, but I can't.

An actual example is sofars [Luscious](https://forum.minetest.net/viewtopic.php?f=9&t=18862) mod. It uses param2 to store color data, but leaf decay is broken and meshoptions for grass can's be used.

I suggest to add param3 (and maybe even more), that works like param2 and uses the same paramtypes or can hold custom data

~~I think Minetest 0.5 is a good time to change that, because I think any kind of change we can make will break something. And because MT0.5 breaks several things this is just "one more thing".~~

~~As far as I know each node is stored as a 32 Bit integer, 16 for the node id, 8 for param1 and 8 for param2. So no room for more data.~~

~~I think the easiest way would be to expand this to 64 Bit. I assume most semi-modern PC wont have much problems with this additional memory usage. Only very old and slow hardware, that nearly struggles with the current MT version, will have problems, but I think we should keep up with the times and do away with old-fashioned things.~~

~~I know this will double the memory usage and the database size and many server owner will complain about that, but I am sure it's worth it. 4~~ more bytes would give us so many opportunities, maybe not immediately, but in the future.

~~Maybe it is possible to add this as option and a temporary solution for the transitional period and server owners can choose if they want the current 32 bit size, or if they have enough hardware they can use their power and add more features. I'm pretty sure this wouldn't be too difficult.~~

**Comment by sfan5** [comment]
> As far as I know each node is stored as a 32 Bit integer

That's incorrect, while the contents of a single `MapNode` do indeed fit into 32 bits, it's not a "hard" assumption made all over the code.

> expand this to 64 Bit

The more important question here is which params you want to expand to which size.

> I'm pretty sure this wouldn't be too difficult.

**Especially** if you implement this as something optional it will turn out to be much more difficult.

**Comment by MarkuBu** [comment]
> That's incorrect, while the contents of a single MapNode do indeed fit into 32 bits, it's not a "hard" assumption made all over the code.

Ok, I'm not really a Minetest Core expert, so I'm sorry if I'm wrong at this point. I assumed that because I would store it that way. 

> The more important question here is which params you want to expand to which size.

I don't think that the existing params should be expanded. rather, I think that new params should be added.

**Comment by sfan5** [comment]
> I don't think that the existing params should be expanded. rather, I think that new params should be added.

And which functionality do you envision for these?

**Comment by MarkuBu** [comment]
How about all paramtypes? Use the same paramtypes from param2 also for param3, param4... 

If new paramtypes are added, add them for all

**Comment by MarkuBu** [comment]
Just to explain more clear what I mean.

Currently you can only chose between color OR meshnodes. Lets assume we have param3 and paramtype3. Then you can set paramtype2 = "meshnodes" and paramtype3 = "color"

And there is more room for new paramtypes

**Comment by paramat** [comment]
> I think the easiest way would be to expand this to 64 Bit.

Absolutely not, doing so needs far more justification than an occasional minor problem of not being able to use multiple implementatins of param2.
:-1:

**Comment by paramat** [comment]
Essentially a partial rewrite of MT. it would be too late for 0.5.0 anyway, we already have our time filled with stuff for 0.5.0. Such a big change, if eventually justified, would be 0.6.0 and probably years away.
MT has limitations and sometimes you just have to accept them and work around them.
Thisis an obvious 'no' but i'll close it after discussion has become quiet.

**Comment by MarkuBu** [comment]
The 32 bit size was an assumption. I don't really know how nodes are stored and managed on disk.

Even one byte, that works like param2, would be a great benefit.

For example, I often wish that I have a few bits of extra storage in a schematic, because I want to store some information, but I can't because param1 and param2 are needed for other things

**Comment by MarkuBu** [comment]
I modified the title and the first post because I think that it is important for the future of MT. 

You can't work around all the limitations, or if you do, it can lead to a lagging game.

**Comment by paramat** [comment]
Adding another param still means moving to 64 bit mapnodes, it won't happen for 0.5.0 but maybe 0.6 or later, and for better reasons. Maybe you misunderstood the size and disruption of the task you're suggesting.

**Comment by appgurueu** [comment]
See also #16950
