### ISSUE TITLE
Deprecation warning should contain short hint at which mod is causing it

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#6664]
these should ideally provide a the filename and line number similar to "undeclared global" warnings:
```
2017-11-20 13:18:20: [Server] WARNING: minetest.setting_* functions are deprecated.  Use methods on the minetest.settings object.
```

supersedes #6654 as @Megaf is unable to express himself correctly and continues to whine at me on IRC on how unhappy he is with Minetest

**Comment by paramat** [comment]
Seems unnecessary work, the information is already available by just using the 'error' setting :-1: 
See #6654 for my reasoning. Megaf's request is unreasonable.

**Comment by sfan5** [comment]
> sfan5 you rightly closed the previous issue, so why open a new issue?

I would also consider the behaviour I suggested useful and it shouldn't be <i>too hard</i> to realise.

**Comment by paramat** [comment]
Yes, sorry, there was no need for me to question it.

**Comment by paramat** [comment]
Didn't think the comments justified deleting, it was minor disagreement and poilte debate.

**Comment by sfan5** [comment]
wtf
