### ISSUE TITLE
Debug/F5 Information Formatting Issues

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#6666]
Currently f5 info takes three lines, which seems excessive, as well as the info being inconsistent and inefficient in presentation. 
![f5ugh](https://user-images.githubusercontent.com/7035183/33149285-1fe45c6a-cfc7-11e7-9230-31f47899c764.png)

Suggestions/ideas:
- Is "dtime" in dtime_jitter "drawtime"? If so, instead of drawtime and dtime_jitter, can these be dtime and dtime_jitter (or even just jitter)? (Saves space...)
- Instead of North/South/East/West for compass directions, how about N/S/E/W? (Saves space...)
- Can we remove brackets from pos and pointing_at? (Saves space / easier to read...)
- Can we remove [+/- X/Z] from yaw? These are fixed values that don't change with gameplay and the only use I can see for them is if a modder needs to know which way is which. But a modder should be able to work this out, and then it's known. F5 shouldn't be the place for fixed values like this. If they need to be recorded somewhere for reference, there are no doubt better places to document them,  (Saves space...)
- More generally, why does pos  need to be labelled "pos = "? If someone can not work out that three numbers in that pattern are the position data, they probably should not be using dbug info anyway. Can that be removed? (Saves space...)
- Why is param2 needed? If it was okay to remove texture info, I don't see why param2 info is needed. If it's for modders, surely this is something they can see in their own code or can write a simple test message in their code to use to review the current values. Can it be removed? (Saves space...)
- With all the space saved, maybe we can get back to two lines.

I am aware there might be arguments against some of these, but I think no one really wants F5 info to take three lines. I've also heard others mention position data is not as easy to read anymore., and I agree with that as well.

**Comment by paramat** [comment]
Congraulations on issue number.
I agree with most of these points, and i was responsible for the changes, so may work on the easier parts of this.
Fitting line number to screen size is less easy, i won't attempt that yet, PR #6225 has code that does that. Maybe 2 lines will be enough after these changes.
Param2 also adds a possible cheat, the param may be used for hidden information, i support removing that.
'pos' for co-ordinates seems better, in-game it's obvious as they change, but in a screenshot not so much.

**Comment by paramat** [comment]
'view range' and 'range all' can be combined into one, as in #6225 
Do we need drawtime and dtime jitter here? I've never once needed those in the first F5 page and they're present in later more technical pages. Likewise with RTT, is RTT shown elsewhere?

**Comment by Ezhh** [comment]
I didn't comment on range_all because I'm not sure what it is. I've used drawtime before, but never saw a need for dtime_jitter. I think RTT is fine to keep, but maybe see what others say as well.

**Comment by paramat** [comment]
Range all is whether you have unlimited view range 'R' key activated. I'll use code from #6225 for that.

**Comment by paramat** [comment]
For a 1st PR i'll return to 2 lines without removing any information.

**Comment by Fixer-007** [comment]
I already suggested making it completely configurable some time ago.

**Comment by lhofhansl** [comment]
I look at dtime_jitter all the time to see how I can reduce it :)

**Comment by paramat** [comment]
PR #6675

**Comment by paramat** [comment]
Good request, i'm just realising what a mess my work was, the PR is beautifully clean and compact.

**Comment by MarkuBu** [comment]
>  but I think no one really wants F5 info to take three lines.

The third line is only visible if you pointing at something and param2 was a very useful information. I wish there would be more useful informations like the light level. The third line never bothered me.

**Comment by Ezhh** [comment]
Third line bothers me a lot. I find that line appearing and disappearing very distracting and uncomfortable (please don't tell me to turn it off then - I need the information it gives) and it really takes up too much space. 

Doing some thinking, is it possible to move seed somewhere else that a player can still access if needed? I really want that information available, but since it only needs to be checked once, perhaps it would fit better somewhere else?

**Comment by paramat** [comment]
Yes the optional third line was messy, often causing empty space, distracting blinking, and it moved chat downwards.
Light level was removed because it is zero for almost all nodes, and can't show light level for air because air isn't pointable.

**Comment by paramat** [comment]
#6675 merged.
Hope this is reasonably addresses this issue.
