### ISSUE TITLE
(Optionally?) remove wieldhand / tool from view when using zoom

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6668]
Obviously needed, since zoom is usually enabled with a telescope type item.
@lhofhansl any comments?

**Comment by rubenwardy** [comment]
What does this mean?

**Comment by Fixer-007** [comment]
It means, when you zoom, you still see your hand/tool/whatever the same way, it is dumb zoom.

**Comment by paramat** [comment]
Seems clear enough.

**Comment by paramat** [comment]
Ok a little clearer now.

**Comment by ClobberXD** [comment]
Wouldn't it suffice to just disable the `wielditem` HUD flag if required?

I feel that modders should have the flexibility to be able to show/hide wielditem irrespective of whether a player uses zoom or not...

**Comment by paramat** [comment]
Sounds good, but i don't think there is a way in a mod to know when the zoom key is being pressed.

**Comment by ClobberXD** [comment]
Ideally, zoom shouldn't be a part of the engine, and should have a more generic implementation like in #7557. So the mod would handle the zooming, and hence would have complete control over wielditem (or any other HUD element) being displayed.

**Comment by Zughy** [comment]
Considering #13763 , zoom will be completely removed someday (we can already use `set_fov()` and use HUD flags). Closing
