### ISSUE TITLE
 attempt to call field 'safe_file_write' (a nil value)

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6669]
Every time I try to use `minetest.safe_file_write()` I get this error message. 

>  attempt to call field 'safe_file_write' (a nil value)

If I'm not totally wrong this tells me, that this function does not exist. Is this function removed from Minetest?

The code is simple and should be correct

```
local result, count = schemedit.serialize(pos1, pos2)
local path = minetest.get_worldpath()
local filename = path .. "/schems/" .. meta.schem_name .. ".lua"
minetest.safe_file_write(filename, result)
```

If I disable mod security and use io.open() everything works as expected. 

Edit: if I google for this function I only get two hits. Both are pointing to lua_api.txt. So it seems that this function is never used in a mod and doesn't exist in the Minetest core code at all.

**Comment by sfan5** [comment]
1) you managed to spell the function name differently the three times it exists
2) generally, using `safe_file_write` for creating new files or performing user-invoked actions is not necessary

Now for the actual question:
Is your Minetest version sufficiently up to date? (0.5.0-dev from at least 9th Nov)

**Comment by MarkuBu** [comment]
1. I noticed the typo, but I copy and paste the error message in the title from the console and this is the correct spelling.
2. What is the recommended way to safe files?

I'm not sure how old my version is. It is dev-d693f95f

**Comment by MarkuBu** [comment]
Got the latest version. Seems to work. Sorry, didn't expect that this is a bleeding edge function

**Comment by sfan5** [comment]
@MarkuBu 
If you are mostly creating **new** files just use the usual io.open and io.write combo.
