### ISSUE TITLE
Trackpad problems on Macbook Pro running Ubuntu

### ISSUE THREAD

**Issue by gituser2194** [minetest/minetest#6672]
Hello,

My trackpad does not work properly with Minetest - I am on a Macbook Pro, but I am not running OS X. I am running Ubuntu on bare metal. I am using the standard Minetest package that can be found in the distro's app store.

The problem is not that it does not move the player's head, use items, right click, etc. but rather that **I cannot move the player's head and walk with the keyboard at the same time.**

The rationale for this being a bug is that it is too much to expect the user to be using a traditional mouse and keyboard in a modern computing environment.

Uname -a:

Linux user-MacBookPro 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

apt list --installed | grep minetest:

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

minetest/artful,now 0.4.16+repack-3 amd64 [installed]
minetest-data/artful,artful,now 0.4.16+repack-3 all [installed,automatic]

**Comment by Calinou** [comment]
> The rationale for this being a bug is that it is too much to expect the user to be using a traditional mouse and keyboard in a modern computing environment.

I'm afraid that's not quite a valid statement for first-person games 😄 

More seriously, have you looked at the trackpad settings? It is likely that the default settings prevent using the trackpad shortly after pressing a key (to avoid accidentally moving the cursor).

**Comment by gituser2194** [comment]
I have confirmed that this is not a problem with Minetest but rather with the computing environment.

I fixed this problem by installing gnome-tweak-tool and flipping the "Disable While Typing" switch under "Keyboard & Mouse".

I think adding this problem to a troubleshooting, FAQ, or wiki page would be a wise decision. :)

**Comment by Megaf** [comment]
`I think adding this problem to a troubleshooting, FAQ, or wiki page would be a wise decision. :)`
👍

**Comment by pauloue** [comment]
This can be closed.
