### ISSUE TITLE
Facilities for stacking/collapsing nodeboxes

### ISSUE THREAD

**Issue by zeuner** [minetest/minetest#6674]
This issue is for discussing existing facilities and possible future engine extensions in order to efficiently solve a specific goal that is considered useful for certain usage scenarios.

Nodeboxes offer amazing opportunities for fancy buildings, for example the microblocks that can be seen in the moreblocks mod. However, the engine will behave somewhat counterintuitive when stacking microblocks. For example, when stacking two nodebox-based blocks which are both flat and half a block in height, the upper block will appear as it would be levitating, while one might expect it would fall down, creating a full height block. Of course, the full height block would have to be defined, but what I would find important would be efficient ways for mod (or subgame) developers to enable such a behaviour.

It should be possible to implement the expected behaviour using ABMs which collapse the stacked blocks. However, this would probably put high load on the server because all the collapsible nodebox blocks would have to be checked all the time. So, I would like to create awareness of this scenario, hoping for better ideas on how this could already be efficiently implemented, or how to implement better facilities to enable it.

**Comment by rubenwardy** [comment]
> However, this would probably put high load on the server because all the collapsible nodebox blocks would have to be checked all the time

You could just do this on node place, similar to _falling_

**Comment by NathanSalapat** [comment]
Slabs already do this in Minetest_Game, AFAIK they use on node place as rubenwardy said.

**Comment by paramat** [comment]
Not ABMs, they run forever and are very intensive.
Instead of compressing different nodeboxes down into one new generated nodebox, we tend to just provide each resulting shape that is wanted, for example a stair instead of combining a bar and a slab.
Often we need to stack compressable shapes without them combining.
It seems we already have all we need for this specialist task, it can becoded if needed, i suspect it's too specialist to add engine code for.

**Comment by zeuner** [comment]
Sounds good!

Even better might be if it would be possible to hook before node
placement: Being able to augment the currently highlighted block
instead of having the built block being put above or next to it.

original message follows:

**Comment by zeuner** [comment]
@Paramat: If you are referring to collapsing nodes which are already
stacked, then yes, I understand how it could be coded. However, how
about collapsing the (collapsible) block in hand onto the currently
focused node instead of having to first build it to a new position
next to the focused node?

original message follows:

**Comment by paramat** [comment]
> how about collapsing the (collapsible) block in hand onto the currently focused node instead of having to first build it to a new position next to the focused node?

That's what we already do in the stairs mod with slabs.

Anyway, this is a very very complex feature that is not much needed, mods can code this in Lua if they want, and the general approach is as i explained above: provide every possible shape such that collapse is not needed.
:-1: This is very low priority and very complex to do.

**Comment by zeuner** [comment]
Great, thanks! Looks like this is already exactly what I was looking
for.

original message follows:

**Comment by paramat** [comment]
Closing for reasons above.

**Comment by zeuner** [comment]
Ok. Thanks forall the valuable pointers.

original message follows:

**Comment by zeuner** [comment]
Thanks.

original message follows:
