### ISSUE TITLE
Irrlicht's SkinnedMesh joint setup is extremely expensive

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#6676]
I was looking into more of the jitter issues in Minetest.
One thing I noticed was that high jitter always occurs when many or complex mobs are loaded.

As a test I used Irrlicht's builtin mesh cache in Client::getMesh(...), and the jitter goes away *completely*.
That method does cache the actual mesh data, but Irrlicht still need to instantiate the mesh, which appears to be quite expensive.

Now it's not that simple... As the comments in there state, we load the same mesh multiple times so that we can give it different vertex colors. Indeed I see when one of the mobs is a shaded differently then all are.

But at least I narrowed it down to this.

If somebody has ideas, I'd like to hear them. This is a big source of jitter in Minetest.

Edit: This is with not-so-simple-mobs for testing.

**Comment by lhofhansl** [comment]
Related [Irrlicht Thread](http://irrlicht.sourceforge.net/forum/viewtopic.php?f=1&t=51928)

**Comment by Fixer-007** [comment]
Is this related in some way? https://github.com/minetest/minetest/issues/3758

**Comment by lhofhansl** [comment]
@Fixer-007 I can give you a small patch to test. (the patch is not done and causes rendering glitches, etc, but it will eliminate the jitter I mention here)

**Comment by lhofhansl** [comment]
Of course NSSM has very big models. Some model weigh in over 4MB!
Whereas mobs:sheep is about 70K, cow is 300K, etc.

**Comment by lhofhansl** [comment]
I think I found a way.

Irrlicht has "emissive lighting", which can be controlled per reference of the mesh. That way one can have a single mesh loaded, yet control the color of each reference.

This gets completely rid of another source of jitter.

I'll file a PR for testing.
