### ISSUE TITLE
Chunkloader

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6677]
It would sometimes be useful to be able to have an active chunk, even if no player is near. Plants can grow, mobs are spawning, machines can do their work.

Also minecarts can act as chunkloader to be able to move  without a player. Then minecarts will be useful to transport ores

I know that chunkloader is the wrong word in Minetest. It should be more something like map block loader and the size could be adjustable.

It is like a virtual player that can be attached to a node or entity, but the number of chunkloader should be limited per player and per world on the server, for example one per player and 20 in the world. Maybe also the activity time (per in-game day) can be limited and shared between chunkloader like round robin

**Comment by HybridDog** [comment]
You can use [forceload_block](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3344) to keep a mapblock loaded although there's no player and if you don't want to keep it loaded till shutdown (if transient is false), you can use [vmanip](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4040), e.g. [to get a teleporter node in an unloaded block](https://github.com/HybridDog/minetest-teleporters/blob/hversion/teleporters/init.lua#L24).
#
I think lua_api.txt should mention the vmanip blockloading possibility in the forceload_block description.

**Comment by MarkuBu** [comment]
Ah, thank you
