### ISSUE TITLE
Incorrect documentation for minetest.register_on_item_eat

### ISSUE THREAD

**Issue by catagent101** [minetest/minetest#6678]
In contrast to what the documentation says on line [2611](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2611), returning true in the function being registered will cause an error to occur saying that it was "Expecting itemstack, itemstring, table or nil." Also, returning itemstack (the original value) causes eating to do literally nothing (including removing the item). Needless to say, it needs to be corrected.

**Comment by DS-Minetest** [comment]
>Also, returning itemstack (the original value) causes eating to do literally nothing (including removing the item).

This seems to be documented correctly. But `true` is wrong.
