### ISSUE TITLE
mod_storage unreliable when used in register_on_generated()

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#6680]
I was experimenting with capturing data from mapgen objects that are not available outside the mapgen thread, and storing this data in mod_storage.

The good part is that mod_storage functions and is entirely available inside the mapgen thread, and data can indeed get written to the mod_storage.

The bad part is that the storage is unreliable, as it seems that the mod_storage object goes away when the server exits, *before* all the mapgen threads are able to shut down and write their data to the mod_storage.

The result is that only *some* of the data successfully gets written into the mod_storage.

Due to the unreliabilty of mod_storage, it is effectively unusable for many tasks, if not all. Some map data is only accessible during mapgen threads, and losing it randomly would make the data lost forever.

To fix, the mapgen threads need to be shut down *before* the main server thread, not before.

**Comment by raymoo** [comment]
>To fix, the mapgen threads need to be shut down after the main server thread, not before.
Shouldn't the mapgen threads be shut down before the main server thread so that they won't still be running when mod storage becomes unavailable?

**Comment by sofar** [comment]
Complete brainfart, I wrote 'after' where I should have written 'before'. updated text.

**Comment by raymoo** [comment]
Do `register_on_shutdown` callbacks get called before the mapgen threads are shut down? Would it be possible to reproduce by trying to write to a ModStorage in one of those callbacks?
