### ISSUE TITLE
Performance problems with 512 textures on Nouveau driver

### ISSUE THREAD

**Issue by kozross** [minetest/minetest#6682]
I'm running Minetest 0.4.16 on Arch Linux, using Vanessa's [512 textures][1], but otherwise no additional anything. I am using the Nouveau driver, on a GeForce GTX 680. The driver is able to reclock both its core and memory to their highest levels (as confirmed by ``pstate``). However, I notice that in 'crowded' areas (such as forests), my framerate drops precipitously, from 60 to 30 or even 20. This does *not* occur on the proprietary driver, nor does this seem to be a problem when using 256 or lower resolution texture packs (from the link above) - in those cases, I am able to maintain a stable 60 frames per second, even in 'crowded' areas.

[1]: https://forum.minetest.net/viewtopic.php?pid=19702

**Comment by HybridDog** [comment]
Do you use mip mapping?

**Comment by kozross** [comment]
@HybridDog Yes, I do.

**Comment by Megaf** [comment]
Not sure this is a Minetest issue. More like nouveau issue. Any chance you can try on nvidia driver?

**Comment by HybridDog** [comment]
Megaf, see the first post.
There're nouveau bugs: https://bugs.freedesktop.org/buglist.cgi?component=Drivers%2FDRI%2Fnouveau&product=Mesa
Do you use the latest version of the driver?

**Comment by paramat** [comment]
Likely not a MT issue, closing until other causes are investigated. Feel free to continue discussion here though.

**Comment by kozross** [comment]
@HybridDog Here is my relevant info:
- Linux kernel version 4.13.12 according to ``uname -r``
- Mesa version 17.2.5 and Nouveau userspace driver version 1.0.15, according to ``pacman -Qs``

Also, you link a lot of bugs - which specific thing (or things) in Nouveau are the cause (or could be the cause) of this? I can let the devs know in such a case.

**Comment by Fixer-007** [comment]
Probably not enough VRAM to store all those 512px textures.

**Comment by paramat** [comment]
Using 512px (excessive and unnecessary) in a complex mesh is likely to contribute to a problem.

**Comment by kozross** [comment]
@Fixer-007 But the proprietary driver doesn't have these perf issues, which suggests there *is* enough VRAM available, unless I'm misunderstanding something.

**Comment by HybridDog** [comment]
In 'crowded' areas you shouldn't get huge lag with a big texture because you use [mip mapping](https://www.khronos.org/opengl/wiki/Texture#Mip_maps).
If the proprietary driver lags there with disabled mip mapping like nouveau does with enabled and disabled mip mapping, nouveau may have buggy mip mapping.

**Comment by kozross** [comment]
@HybridDog Just tested with the Nvidia proprietary driver, and indeed it is exactly as you predicted. With mipmapping turned off, the performance of the proprietary driver is identical to Nouveau with mipmapping turned *on*.

**Comment by imirkin** [comment]
[mesa nouveau backend maintainer here]

Can someone say with some precision what the "mip mapping" setting does?

Does it call glGenerateMipmaps on a ton of [large] textures on every frame? Does it mess around with base levels? Sampler settings? etc.

If available, does it make use of sparse textures? [These are not available on nouveau.]

Is 512 in reference to the quantity of textures or their size?

**Comment by kozross** [comment]
@imirkin 512 refers to their size (512 pixels, I believe).

**Comment by sfan5** [comment]
Here's the relevant codepath down to the `glGenerateMipmap` call:
https://github.com/minetest/minetest/blob/master/src/client/clientlauncher.cpp#L214L215
https://github.com/zaki/irrlicht/blob/master/source/Irrlicht/COpenGLCoreTexture.h#L61
https://github.com/zaki/irrlicht/blob/master/source/Irrlicht/COpenGLCoreTexture.h#L120L121
https://github.com/zaki/irrlicht/blob/master/source/Irrlicht/COpenGLCoreTexture.h#L383L385
https://github.com/zaki/irrlicht/blob/master/source/Irrlicht/COpenGLExtensionHandler.h#L2206

**Comment by imirkin** [comment]
How frequently is this done? Per frame, or per game load?

**Comment by sfan5** [comment]
Unless we are doing something special, once per texture creation.
For the in-game world, texture loading is done once at game load AFAIK.

**Comment by imirkin** [comment]
And what do you do when the mipmap setting is disabled? Effectively sample from LOD 0 and not worry about the crappy filtering results? Or do you try to do something clever like pull in a box's worth of texels and do your own filtering?

Do you use linear or nearest filtering?

**Comment by sfan5** [comment]
> And what do you do when the mipmap setting is disabled?

Nothing(?)
Irrlicht handles all the GL calls for us, so I don't think we do anything unusual.

> Do you use linear or nearest filtering?

```
		glTexParameteri(TextureType, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
		glTexParameteri(TextureType, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
```
looks like nearest to me

**Comment by kozross** [comment]
Please find a pair of traces here. I do the same thing in both:

- Start Minetest
- Load up a map where I'm standing in a 'crowded' area
- Stand there a while
- Exit
[This is the Nvidia driver trace][1]. [Corresponding Nouveau trace][2].

[1]: https://transfer.sh/e4OXJ/minetest-nvidia.trace.xz
[2]: https://transfer.sh/YtPf6/minetest-nouveau.trace.xz

**Comment by kozross** [comment]
By request of @imirkin, [here][1] is a trace on Nouveau with mipmap disabled in the Minetest settings.

[1]: https://transfer.sh/JOWjl/minetest-no-mipmap-nouveau.trace.xz
