### ISSUE TITLE
CSM Add HTTP Requests

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#6684]

**Comment by rubenwardy** [comment]
Nope :-1:

**Comment by azekillDIABLO** [comment]
Depends. I think it would just lag the servers.

**Comment by Calinou** [comment]
> Depends. I think it would just lag the servers.

It's not a matter of server lag in this case, I just think HTTP requests aren't necessary here.

**Comment by paramat** [comment]
:-1:
