### ISSUE TITLE
mapblock serialization: Node id being put into param2 

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6685]
https://github.com/minetest/minetest/commit/ea62ee4b61371107ef3d693bda4c410ba02ca7e6#diff-fc3a9401529179dd3b1e55306363c6a4R324 
https://github.com/minetest/minetest/blob/master/src/mapnode.cpp#L752
If I understand the mapblock serialization code correctly, if content_width is 1 and param0 (the node id, which is 16 bit) takes more than 7 bit, the lower 4 bit of the param0 is put into the upper 4 bit of param2 (an 8 bit value) and the actual param2 value is stored in the 4 lower bits of param2 (I assume/hope that in this case the actual param2 < 16).
I assume this could have negative impact on compression ratio, e.g. when param0 takes 10 bit and every param2 value is 0 (no rotated or coloured nodes), there're nodecount bytes for param0 and nodecount bytes for param2 and partially param0, whereas without this there're 2*nodecount bytes for param0 and nodecount 0 bytes for param2.

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/commit/fd845f27f5b3e3c6587c472be76235567a7b934d#diff-a3d43cc239efc733a8a046ff0a6bc91eR585
`content_width` has always been 2 since 5 years, this is essentially dead code

**Comment by HybridDog** [comment]
You're right, sorry, I should've read the serialization code, too.
