### ISSUE TITLE
register_on_player_receive_fields doesn't work

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6687]
minetest.register_on_player_receive_fields seems to have stopped working. When I noticed that my chatcommand_tool mod doesn't longer save the text after editing it in the formspec I tried to find the bug and fix it. I made it print the fields and formname in minetest.register_on_player_receive_fields but when I click on save nothing happens, even the quit event doesn't happen.
https://github.com/HybridDog/command_tool/blob/dev/init.lua#L138

**Comment by SmallJoker** [comment]
Use instructions would help to reproduce this.
Can not reproduce with 76eb3f2b, using another mod with `register_on_player_receive_fields` callbacks.

**Comment by HybridDog** [comment]
I just noticed that it doesn't happen if I use only this mod, I think some mod causes this bug.
