### ISSUE TITLE
Change spelling of “flavour” to “flavor” in code to adhere to the coding style guidelines

### ISSUE THREAD

**Issue by dsohler** [minetest/minetest#6690]
Initial issue for implementing the guideline: https://github.com/minetest/minetest/issues/6238

Resulting guidelines change in the developer wiki: http://dev.minetest.net/index.php?title=Code_style_guidelines&diff=3911&oldid=3901

Pull request using the wrong spelling (British English “flavour” instead of American English flavor): https://github.com/minetest/minetest/pull/5930

Wrong spelling in code: https://github.com/minetest/minetest/search?utf8=%E2%9C%93&q=flavour&type=

Proof:

General usage: https://trends.google.com/trends/explore?date=all&q=flavor,flavour
GitHub usage: [flavour](https://github.com/search?utf8=%E2%9C%93&q=flavour&type=), [flavor](https://github.com/search?utf8=%E2%9C%93&q=flavor&type=)

**Comment by rubenwardy** [comment]
Why is that "proof" even relevant?

Also, flavour is a stupid term for it. `csm_feature_restrictions` would be better

**Comment by paramat** [comment]
I re-opened #6238 and changed it to refer to code.
:+1: for this.
If i work on CSM flavors i can correct this in my PR.

**Comment by dsohler** [comment]
> Why is that "proof" section even relevant?

Because the original issue had some kind of proof, too. So I added as much a s possible to justify this issue here.

> Also, flavour is a stupid term for it. csm_feature_restrictions would be better

Yes of course. But that would be another issue …

**Comment by paramat** [comment]
See #7467, i suggest renaming to something other than 'flavour' and 'limit'.

**Comment by SmallJoker** [comment]
#7468 merged
