### ISSUE TITLE
minetest ungrabs the mouse pointer if i move it too fast

### ISSUE THREAD

**Issue by gituser2194** [minetest/minetest#6691]
this debilitates pvp

uname -a:

    Linux user-NY614AA-ABA-p6234f 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 
    2017 x86_64 x86_64 x86_64 GNU/Linux

apt list --installed | grep minetest:

    minetest/artful,now 0.4.16+repack-3 amd64 [installed]
    minetest-data/artful,artful,now 0.4.16+repack-3 all [installed,automatic]

loginctl show-session 6 -p Type:

    Type=wayland

 cat /usr/share/gnome/gnome-version.xml:

    <?xml version="1.0" encoding="UTF-8"?>
        <gnome-version>
             <platform>3</platform>
             <minor>26</minor>
             <micro>1</micro>
             <distributor>Ubuntu</distributor>
        </gnome-version>

**Comment by sfan5** [comment]
I've had this happen when Minetest freezes long enough for me to move my mouse pointer outside of the window.

**Comment by rubenwardy** [comment]
This sounds like it could be an upstream issue

**Comment by paramat** [comment]
Any recent occurences?

**Comment by paramat** [comment]
Old report and no response.
