### ISSUE TITLE
F5 Debug info: monospace fonts and colours (actually grey)

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6693]
As I mentioned [there](https://github.com/minetest/minetest/pull/6675#issuecomment-346991691), I think the debug info should use the monospace font with low font size. And monospace font size should be configurable separately for chat, big chat (F10) and debug info.
This would make the chat more readable (better distinguishing between debug info and chat), save space (due to the low font size) and fix the `default` and `defauIt` looking the same problem in the nodename.
Also, it should use two colours, one for the names (e.g. `Minetest`) and one for the values (e.g. `0.5.0-dev-smell`)

**Comment by paramat** [comment]
1 year bump. Any core dev support? (i'm neutral).
