### ISSUE TITLE
bumpmapping tileability problem on spanned textures

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6694]
![screenshot_20171127_153123](https://user-images.githubusercontent.com/3192173/33272285-f186e524-d389-11e7-8a55-23efec5f2e8a.png)
![unbenannt](https://user-images.githubusercontent.com/3192173/33272295-f6fced32-d389-11e7-867e-c21a43aad530.png)
I've tested the new scale field in the tile definition and noticed that there's a tiling problem with bumpmapping (see the screenshots).

**Comment by paramat** [comment]
What do you mean by 'spanned texture'?

**Comment by rubenwardy** [comment]
Bumpmapping was removed
