### ISSUE TITLE
Update Lua To The Latest version

### ISSUE THREAD

**Issue by xXxToxicBlueDustxXx** [minetest/minetest#6703]
Would be good (not if you like), upgrade Lua to your last version (not if you already did) 5.3

**Comment by rubenwardy** [comment]
Not possible when using LuaJIT

**Comment by xXxToxicBlueDustxXx** [comment]
sorry for my question but What is LuaJit and what's differences to standar Lua?

**Comment by MarkuBu** [comment]
The speed
