### ISSUE TITLE
[PATCH] Receive events from each key pressed in field[]

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#6704]
**This allows dynamic searches without pressing Enter.**

I won't bother making a PR but here is a diff to allow capturing the key pressed in the fields handler when you declare a `field[]` like so : 

```Lua
"field[0,0;4,1;!filter;;" .. my_filter .. "]"
```

If the name of the field is prefixed with `!`, the keys are captured. If not : default behavior.

`print(dump(fields))` returns this when you're typing "poo" in the field:

```Lua
{
	filter = "p"
}
{
	filter = "po"
}
{
	filter = "poo"
}
```

## Diff

```Diff
diff --git a/src/gui/guiFormSpecMenu.cpp b/src/gui/guiFormSpecMenu.cpp
index 0691bc59..f588ee2c 100644
--- a/src/gui/guiFormSpecMenu.cpp
+++ b/src/gui/guiFormSpecMenu.cpp
@@ -989,6 +989,10 @@ void GUIFormSpecMenu::parseSimpleField(parserData* data,
 	std::string label = parts[1];
 	std::string default_val = parts[2];
 
+	bool is_dynamic = (name.length() > 0 && name[0] == '!');
+	if (is_dynamic)
+		name = name.substr(1);
+
 	core::rect<s32> rect;
 
 	if(data->explicit_size)
@@ -1015,6 +1019,8 @@ void GUIFormSpecMenu::parseSimpleField(parserData* data,
 		258+m_fields.size()
 	);
 
+	spec.is_dynamic = is_dynamic;
+
 	if (name.empty()) {
 		// spec field id to 0, this stops submit searching for a value that isn't there
 		addStaticText(Environment, spec.flabel.c_str(), rect, false, true, this, spec.fid);
@@ -1074,6 +1080,10 @@ void GUIFormSpecMenu::parseTextArea(parserData* data, std::vector<std::string>&
 	std::string label = parts[3];
 	std::string default_val = parts[4];
 
+	bool is_dynamic = (name.length() > 0 && name[0] == '!');
+	if (is_dynamic)
+		name = name.substr(1);
+
 	MY_CHECKPOS(type,0);
 	MY_CHECKGEOM(type,1);
 
@@ -1115,6 +1125,8 @@ void GUIFormSpecMenu::parseTextArea(parserData* data, std::vector<std::string>&
 		258+m_fields.size()
 	);
 
+	spec.is_dynamic = is_dynamic;
+
 	bool is_editable = !name.empty();
 
 	if (is_editable)
@@ -3783,6 +3795,20 @@ bool GUIFormSpecMenu::OnEvent(const SEvent& event)
 			}
 		}
 
+		if (event.GUIEvent.EventType == gui::EGET_EDITBOX_CHANGED) {
+			if (event.GUIEvent.Caller->getID() > 257) {
+				for (GUIFormSpecMenu::FieldSpec &s : m_fields) {
+					if (s.ftype == f_Unknown && s.is_dynamic &&
+							s.fid == event.GUIEvent.Caller->getID()) {
+						s.send = true;
+						acceptInput();
+						s.send=false;
+					}
+				}
+				return true;
+			}
+		}
+
 		if (event.GUIEvent.EventType == gui::EGET_EDITBOX_ENTER) {
 			if (event.GUIEvent.Caller->getID() > 257) {
 				bool close_on_enter = true;
diff --git a/src/gui/guiFormSpecMenu.h b/src/gui/guiFormSpecMenu.h
index 071efb37..455b6010 100644
--- a/src/gui/guiFormSpecMenu.h
+++ b/src/gui/guiFormSpecMenu.h
@@ -207,7 +207,8 @@ class GUIFormSpecMenu : public GUIModalMenu
 			fid(id),
 			send(false),
 			ftype(f_Unknown),
-			is_exit(false)
+			is_exit(false),
+			is_dynamic(false)
 		{
 		}
 
@@ -218,6 +219,7 @@ class GUIFormSpecMenu : public GUIModalMenu
 		bool send;
 		FormspecFieldType ftype;
 		bool is_exit;
+		bool is_dynamic;
 		core::rect<s32> rect;
 	};

```

**Comment by rubenwardy** [comment]
Nice. There are two things that worry me:

* The API for enabling this isn't very readable or nice. It should like `field_close_on_enter`. (although maybe they could be combined into a field_setting or something, not sure)
* This could end up with over submitting when typing fast, which you don't need for a search field. Really it should wait when there are presses and send every X interval. Batching. With a custom element the mod could decide this, and set it to 0 if needed. Alternatively the engine could batch formspec submits together, although only if that is added as a general reliable channel feature - overcomplicated for just the formspec submit

**Comment by paramat** [comment]
> "modders should not have the ability to [...]"

That's a somewhat harsh and negative way to word it, i don't have that attitude. Please don't keep misrepresenting what i write to make it look as unpleasant as possible.

I mean: Instant response to every letter typed is obviously a very fancy feature that in my opinion modders don't much need, even though they might somewhat like the idea in isolation (as in, not thinking about the deeper issues of increased network use, code complexity, maintenance, priority), and even though some may be able to think of a use for it.
>  I don't see why modders should not be given the possibility for this.

Because of increased network usage, the code bloat and maintenance, balanced against the very low benefit, the lack of need or uses. I expect, being an excellent core dev (no sarcasm), that you take these aspects into account.
I'm surprised that any core dev would see this as justified, especially at the moment.
