### ISSUE TITLE
Disable FPS limiting by default on macOS

### ISSUE THREAD

**Issue by jameshiew** [minetest/minetest#6713]
Set the default `fps_max` and `pause_fps_max` settings to some arbitrary high value like 10000 on macOS - this prevents the [stuttering mouse bug](https://github.com/minetest/minetest/issues/2697 ) that seems to have been present for a while.

I downloaded an old 0.4.10 .app and can verify that the mouse does not lag in that version, also removing [this line](https://github.com/minetest/minetest/blob/master/src/game.cpp#L4563) fixed the stuttering mouse without having the change `fps_max` or `pause_fps_max`, but presumably that breaks FPS limiting also.

This suggestion only covers up the bug rather than fixing it, but it would provide a better user experience for new users in the meantime.

**Comment by Calinou** [comment]
Note that you can set `fps_max` and `pause_fps_max` to 0 to disable the limits entirely.

**Comment by paramat** [comment]
macOS is a minority usage, and you can set FPS max settings yourself if it helps, also this is a hack.
Continue discussion in #2697

**Comment by tacotexmex** [comment]
> macOS is a minority usage

Well, these types of bugs will make sure that won’t change any time soon. 🙄

**Comment by paramat** [comment]
Sorry for that invalid comment, deleted.
