### ISSUE TITLE
Reloading world after crash (or SIGKILL) turns dropped items into hands

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6724]
How to reproduce:

* Start MT 0.4.16 w/ MTG 0.4.16 (e.g. by invoking the `minetest` command)
* Start new world
* Drop random items on the floor
* Do other stuff for 30 seconds or so (just to make sure the automatic map save kicks in)
* Kill Minetest with `SIGKILL`. (e.g. `killall minetest -9` in console)
* Start Minetest again in your world
* Wait for item entities to re-appear

All these items entities around you have become hands! If you punch them, they just disappear.
The rest of the world seems fine (players, blocks, mobs, …), so Minetest worlds seem to be pretty robust otherwise. :-)

The SIGKILL is of course done to simulate a crash. The point of this issue is that the items should not get corrupted even in the event of a crash.

---

Note that the itemstring of a hand is just the empty string, which may be some default or fallback value.
My guess: Seems like some memory corruption is happening when Minetest tries to save or restore the item entities. The item type should not be lost.

Related issue in MineClone 2 subgame: https://github.com/Wuzzy2/MineClone2-Bugs/issues/388
(note that MCL2 uses custom item entities, but remember this bug happens in MTG, too.)

**Comment by SmallJoker** [comment]
As you were able to reproduce it at least once, does it also happen with a recent 0.5.0-dev build?

**Comment by Wuzzy2** [comment]
In 0.4.16 I can reproduce this pretty reliably.

In 0.5.0-dev the items just disappear instead. Which is not much better (loss of information).

Also I made sure to leave some landmarks (by placing blocks) after I dropped the items. The landmarks were still there after re-loading the world. So something seems to be wrong about the saving of item entities.

**Comment by dsohler** [comment]
> Do other stuff for 30 seconds or so (just to make sure the automatic map save kicks in)

I was able to reproduce this in 0.4.16 in 5/5 test cases for all dropped items.

![screenshot_20171201_214228](https://user-images.githubusercontent.com/1668792/33502346-fa4a13a8-d6df-11e7-8e9a-4abd70e4e359.png)

**Comment by paramat** [comment]
Note: This was reported after #6379 was fixed by #6414

**Comment by sfan5** [comment]
Wuzzy retested it in 2017 https://github.com/minetest/minetest/pull/6414#issuecomment-329809331

**Comment by paramat** [comment]
But that was Sep 2017, this issue was opened Dec 2017, which made me think this is a new bug (?)

**Comment by sfan5** [comment]
Didn't see the date but I'm sure this bug is fixed either way.
