### ISSUE TITLE
Main menu unusable: elements overlap, and touch targets are too small

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#6725]
![image](https://user-images.githubusercontent.com/31285258/33497936-f601ab54-d6cf-11e7-82f7-5259f79e4002.png)
Just downloaded Minetest from F-Droid, no mods used.
F-Droid says the version is 0.4.16.17
Device is Lenovo P2 running Android Ice Cold Project custom ROM.

**Comment by paramat** [comment]
What if you adjust GUI scaling, does that solve the issue? Please could someone try? Author is no longer on GitHub.
This issue could possibly then be combined into #7504
