### ISSUE TITLE
Default sneak key doesn't exist on macOS

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#6727]
Out of the box the key that binds sneak behavior, Left Shift (KEY_LSHIFT), doesn't exist as a concept on macOS. There's just two Shift (KEY_SHIFT). Therefore the default key bind doesn't work by default. 

The key binding should default to Shift (KEY_SHIFT) on macOS builds.

**Comment by Megaf** [comment]
I think there's an issue about this somewhere already. It's known bug.

**Comment by claretty** [comment]
I have encountered a related problem, in the 'carts' mod on 0.4.17.1 . In order to pick up a cart from its track, the action required is 'sneak-punch'. Nothing happens. Even using the Mac 'down' key - E - does not help.

**Comment by makeworld-the-better-one** [comment]
This issue still occurs for me. @paramat @tacotexmex

**Comment by rubenwardy** [comment]
Are you using 5.0.0?

**Comment by makeworld-the-better-one** [comment]
@rubenwardy I am using the latest release, 0.4.17.

**Comment by rubenwardy** [comment]
The fix will be in 5.0.0 which will be released soon™. This issue tracker is for the latest development version of MT. We close issues as soon as they're fixed, and not waiting until a stable release is made

**Comment by makeworld-the-better-one** [comment]
Ah okay, I understand. Thanks for letting me know!
