### ISSUE TITLE
Formspec showing bug

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6734]
![screenshot_20171204_141349](https://user-images.githubusercontent.com/3192173/33554800-711b0df0-d8fe-11e7-8255-7d1f4f61ba15.png)

I've noticed a bug when playing with [connected_chests](https://github.com/HybridDog/connected_chests). If you hold ESC and spam right click on a connected chest node, you end up having this green box in the top left (see screenshot) and can't open any formspecs: If you press i for inventory, ESC to view the quit menu or right click on a chest to open it, nothing happens (no formspec appears). You can walk around and place nodes. 
If you punch a node or show chat (t or F10), the green box (the error) disappears.

**Comment by sfan5** [comment]
That's an empty tooltip afaik and this bug has been present for a long time.

**Comment by HybridDog** [comment]
So to find the bug you need to examine code where a tooltip is added?
Maybe you can add an assertion to make it crash when the tooltip is added with empty string, compile with debugging enabled, run it in gdb and then view the backtrace of an assertion failure crash.

**Comment by paramat** [comment]
Was mentioned in #5132

**Comment by SmallJoker** [comment]
Bug still present in 5.1.0-dev. The ghost tooltip also disappears by left-click.

**Comment by ClobberXD** [comment]
> Bug still present in 5.1.0-dev. The ghost tooltip also disappears by left-click.

Can confirm that I've experienced this exact bug before, albeit somewhat rarely. But for me, it happens in normal chests too.

**Comment by v-rob** [comment]
I can no longer confirm this in 5.2.0 while it is quite easy to reproduce in 5.0.0.  Can anyone else still confirm this?  It might have been inadvertently fixed by some formspec PR.

**Comment by HybridDog** [comment]
I also cannot reproduce it anymore (Minetest 5.4.0-dev-7242de1d4).
