### ISSUE TITLE
Default DPI on Windows is wrong, affects HUD scaling

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#6735]
Here's the bug in question, http://i.imgur.com/o8I7ytZ.png and https://jordach.net/images/ppxdgexmfhcvlnajtl.png (provided by @benrob0329 )

Here's what it should look like, https://jordach.net/images/mdosditzrdlduukpl.png

About 10 months ago, @sfan5, has found the source of the issue, and is related to porting.h.

```
<sfan5> >float size_factor = m_hud_scaling * porting::getDisplayDensity();
<sfan5> i'm guessing this is at fault
<sfan5> its probably unimpl. (=1) on win
```

The line in question, is found here:

https://github.com/minetest/minetest/blob/master/src/hud.cpp#L388

The issue also extends to pixel offsets, which should be 1:1 as the lua_api.txt implies, not 1:4, depending on display density, as these lines;

https://github.com/minetest/minetest/blob/master/src/hud.cpp#L389-L392

After replacing RenderingEngine::getDisplayDensity() with a 1 (according to IRC logs), it then looks corrected, as shown here:

https://kitsunemimi.pw/i/c2a30f175559ac81.png

This affects all versions of Minetest from 0.4.7 through 0.5-dev (ab947bd)

However, a commit by @sapier, implies that it may originate there: https://github.com/minetest/minetest/commit/1838a3fd696782b1733a435bbb25accf3e40d1f3

Related bugs; https://github.com/minetest/minetest/issues/6296

**Comment by Jordach** [comment]
@sfan5 managed to pin point the actual source of the issue, and seems to be inside renderingengine.cpp;

```
<sfan5> it only works if i completely nuke getDisplayDensity()
<sfan5> just removing it from that single one does not suffice
...
<sfan5> the problem here is that only the statbar + the image bg (intended?) seems to be scaled incorrectly
```

https://github.com/minetest/minetest/blob/master/src/client/renderingengine.cpp#L527

https://github.com/minetest/minetest/blob/master/src/client/renderingengine.cpp#L497

@Virtuoel has removed getDisplayDensity from renderingengine.cpp and it appears to scale correctly:

Under Kubuntu 17.04 with Wayland:

https://jordach.net/images/vnpgldjvrnzidtlcm.png

Formspecs also work as intended:

https://jordach.net/images/ysspxgzbwpaocehech.png

The lua_api.txt mentions that offsets are pixel perfect, https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1328-L1330

however, just under that, it mentions they are scaled, which is entirely contradictory:

https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1332

**Comment by Jordach** [comment]
```<Jordach> screen_dpi = 72
<Jordach> i had windows force minetest.conf to read only
<Jordach> as setting screen_dpi to anything but 72 will be reset to it
```

**Comment by paramat** [comment]
@stujones11 any thoughts?
