### ISSUE TITLE
Placing stairs and slabs doesn't work

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6752]
If I place stairs or slabs it doesn't work as expected. If I point to the lower or upper 25% of a node, the slab is placed on the bottom. If I point to the center 50% the slab is placed at the top

See what I mean in the video
https://youtu.be/4FL32TA59fo

I assume that the eye hight of the player model has changed in 0.5, but wasn't changed in core.pointed_thing_to_face_pos()

**Comment by rubenwardy** [comment]
I think this may be a MTG feature to make placing more predictable

**Comment by MarkuBu** [comment]
Sorry, this is a confined bug and MT Core is the place where you have to look for.

**Comment by paramat** [comment]
> I assume that the eye hight of the player model has changed in 0.5, but wasn't changed in core.pointed_thing_to_face_pos()

Yes engine issue, will fix that.

**Comment by paramat** [comment]
PR #6754

**Comment by MarkuBu** [comment]
Thanks paramat. That wasn't possible when I wrote this

**Comment by MarkuBu** [comment]
Tested and works. Issue can be closed. Thx paramat

**Comment by paramat** [comment]
Ah nerzhul forgot to close this.
