### ISSUE TITLE
Suggestion/request: Colored Text/Font via formspec

### ISSUE THREAD

**Issue by Gerold55** [minetest/minetest#6756]
Like the title says we need to be able to change the text colors for mods. I'm working on a mod that needs black font instead of default white and I have to do a cut around to get a black font.

**Comment by SmallJoker** [comment]
https://forum.minetest.net/viewtopic.php?f=47&t=18964

**Comment by paramat** [comment]
Seems already possible, do comment here if not.

**Comment by Gerold55** [comment]
Is there a mod that has this in it/proof that it works properly Bell07 has had a hard time coding it in :(
Or can someone help please :)

**Comment by paramat** [comment]
Ask on the forums or in IRC, this isn't the place for help with mods.

**Comment by Gerold55** [comment]
There's issues with trying to color text can someone look into it and aim to fix the issues?

**Comment by paramat** [comment]
Ok, search for an existing issue here, if there isn't one please open one.
