### ISSUE TITLE
Is there the development environment like android studio or eclipse for andriod version?

### ISSUE THREAD

**Issue by afree2004** [minetest/minetest#6760]
Did anyone use android studio or eclipse to develope android version? Any suggestion is appreciated.

**Comment by SmallJoker** [comment]
@stujones11 apparently uses Android Studio, according to https://github.com/minetest/minetest/pull/6628
Perhaps @rubenwardy too?

**Comment by rubenwardy** [comment]
You can't compile using Android studio. I've not used it for debugging either

**Comment by stujones11** [comment]
> You can't compile using Android studio.

I'd like to think that should eventually be possible but for now installing Android studio is just an easy way to obtain all the necessary build tools, though it can also be useful for debugging.

To build the apk:

cd build/android
export BUILD_TYPE=debug;
make apk -j$(nproc)

Once complete, use 'import project' from android studio main window then select android directory.

Note that the build currently fails, however, you can try my WIP branch here https://github.com/stujones11/minetest/tree/android-c++11 (currently only works for arm7 devices)

**Comment by afree2004** [comment]
Thank u all,  @SmallJoker @rubenwardy @stujones11.  Thanks stujones very much for his detail info and i'll try it.

**Comment by afree2004** [comment]
@stujones11,  compiling error occured when the last step ran, even though i added the -std=c++11 or -std=gnu++11 compiler options into the MakeFile like this: TARGET_CFLAGS_ADDON = -std=gnu++11 -mfloat-abi=softfp -mfpu=vfpv3 -O3 -D__ANDROID_API__=$(API)
Please help me. The compiling error:

nothing to be done for openssl
nothing to be done for curl
nothing to be done for openal
nothing to be done for libogg/libvorbis
make[1]: Entering directory '/home/afree/minetest/build/android'
[armeabi-v7a] Compile++ thumb: minetest <= ban.cpp
In file included from /home/afree/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/cstdint:35:0,
                 from jni/src/irrlichttypes.h:30,
                 from jni/src/irrlichttypes_bloated.h:22,
                 from jni/../jni/src/util/string.h:22,
                 from jni/../jni/src/ban.h:22,
                 from jni/../jni/src/ban.cpp:20:
/home/afree/android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from jni/../jni/src/ban.h:22:0,
                 from jni/../jni/src/ban.cpp:20:
jni/../jni/src/util/string.h:57:14: error: 'unordered_map' in namespace 'std' does not name a template type
 typedef std::unordered_map<std::string, std::string> StringMap;
              ^
jni/../jni/src/util/string.h: In function 'std::string lowercase(const string&)':
jni/../jni/src/util/string.h:288:16: error: range-based 'for' loops are not allowed in C++98 mode
  for (char i : str)
                ^
jni/../jni/src/util/string.h: In function 'bool is_number(const string&)':
jni/../jni/src/util/string.h:666:16: error: range-based 'for' loops are not allowed

**Comment by rubenwardy** [comment]
Please note this section if you're going to be releasing a fork on Google Play: https://wiki.minetest.net/Licensing#Complying_with_the_License

**Comment by stujones11** [comment]
@afree2004 Sorry, no idea other than try a more recent NDK, current stable is ndk-r16 which works for me. Also, the `-std=c++11` flag needs to be added to `APP_CPPFLAGS` in the Application.mk

**Comment by afree2004** [comment]
@rubenwardy thanks for your reminding, but now it's just my personal interest.
@stujones11 with your help, i was excited to get the apk. But after i pressed the singleplayer button, running error code was on the screen : ERROR[Main]: Irrlicht: GL_INVALID_ENUM.
Can you tell me how to build a debug enviroment?

**Comment by stujones11** [comment]
> what's your debug enviroment for android ?

Right now I am just using adb and logcat via android studio, although there is ndk-gdb which I have used in the past. It's been a while since I last worked with android so I am having to re-learn a lot of this stuff myself.

**Comment by rubenwardy** [comment]
Any more questions?

**Comment by afree2004** [comment]
I'll ask some questions because it can't runs in android studio,  but i'm busy these days.

**Comment by paramat** [comment]
We can reopen this if or when you have more to discuss.
