### ISSUE TITLE
Declare Mgv7 terrain 'officially stable' at 0.5.0

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6761]
A reminder for myself.
Mgv7 terrain (the shape of the stone base terrain only, not biomes applied by games) has been stable for 1-2 years now, at 0.5.0 release i think we can call it 'officially stable'.
The biomes cannot be declared stable because they are likely to improve, stability would prevent improvement, but of course we will try our best to avoid or minimise any disruption.

**Comment by rubenwardy** [comment]
I thought this already was the case?

**Comment by paramat** [comment]
Maybe i forgot, it's certainly been unofficially stable.

**Comment by paramat** [comment]
Yes i did decide mgv7 terrain (apart from floatland terrain) was stable for 0.4.16, i'll make a post in the forum to make thar clear.
