### ISSUE TITLE
Make LINT a separate check

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6766]
While it is very useful by itself, it’s very annoying (and actually misleading) when you see “failed build” only due to some too long lines or misplaced spaces. Remember that 75% of source files are whitelisted. Would this check be separate, that would not be necessary.

**Comment by paramat** [comment]
Yes i'm rather fed up with LINT failing for silly reasons.

**Comment by rubenwardy** [comment]
I agree with this, it's very annoying

**Comment by paramat** [comment]
Can it be made to show a warning without causing a build to 'fail'?

**Comment by paramat** [comment]
Yes to be clear i appreciate LINT and want to keep it, but would prefer it shows a separate warning if possible.

**Comment by nerzhul** [comment]
seems not possible with travis, it's a request done by many travis users :(

**Comment by paramat** [comment]
Ok, thanks for checking.

**Comment by paramat** [comment]
See https://blog.github.com/2018-05-07-introducing-checks-api/
It's integrated with Travis CI.

**Comment by paramat** [comment]
Actually, looks like only new or migrated repos can use this, see IRC discussion.
