### ISSUE TITLE
Customize message for using disabled minimap

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6767]
The minimap can be disabled for each player.
But I dislike the message the player sees when he/she tries to activate the minimap when the minimap is disabled. This is the current message:

> Minimap disabled by server

This message is bad for these reasons:

1) Mentioning a server is nonsense. Using the minimap not a privilege, but rather defined by the subgame/mods. In singleplayer this makes even less sense.
2) If the subgame/mods allows to make the minimap available, the message is not helpful
3) It's not clear the minimap might become enabled later in the game. Players might assume the minimap is disabled *permanently*, which is not always true

Suggestions:

Suggestion 1: Allow mods to optionally replace this message on a per-player basis (just like you enable/disable minimap on a per-player basis). Of course, this message needs to respect client translations, otherwise this will only be a halfplemented feature.
Use case: “You need to hold a map in your hand!” or “You need a map in your inventory!”, etc. Minetest Game and other subgames with a map item will benefit from this.

Suggestion 2: Allow mods to revert back to the default message, if they don't want the custom message anymore.

Suggestion 3: Change the default message to “Minimap currently disabled by game”. I used the word “currently” because the minimap might become available later. Otherwise, the player might assume the minimap is disabled *permanently*, which is not true for all subgames.

**Comment by jastevenson303** [comment]
Thank you for making this issue, that message bothers me greatly.  Nice suggestions, too.  (I prefer a customizable message (Suggestion 1 with a sane default (Suggestion 3).)

**Comment by paramat** [comment]
Mentioning a server makes sense, if a mod disables it, it is the server disabling. In singleplayer there is still a server.
I don't think it's necessary to explain how to enable, in MT there are many things that need to be explained elsewhere, in the wiki or whatever, for example crafting recipies, we can't provide all information in-game.

> Allow mods to optionally replace this message on a per-player basis

I disagree, and it doesn't necessarily need to be per-player, thats even more complex.

> Change the default message to “Minimap currently disabled by game”

Yes or maybe ".. game or mod".
I approve suggestion 3 on it's own.

**Comment by dsohler** [comment]
> Too complex and non-essential.

A a classic paramat statement 😄 

> it encourages players to investigate

Actually no. It only encourages players wo want the minimap to search for another server where it is not disabled.

**Comment by paramat** [comment]
I'm happy to spend 10 mins making a quick PR for this, as i should have improved the message when i worked on minimap code. This doesn't justify more dev time though.
Due to the usual lack of dev time we have to work quickly and implement things in a simple but reasonably effective way.

**Comment by paramat** [comment]
PR #6770

**Comment by paramat** [comment]
Hmm thinking on this, it's not the responsibility of engine messages to be game-customisable to give game-specific information, they're simple and universal, otherwise we would need APIs for all engine messages. The responsibility is with the game. For example i suggest that the map mod in MTG could create a chat message 'on joinplayer' that explains how to enable minimap with an item, if it is survival mode and the item is not present.

But of course we should make these engine messages as universally useful as possible, which is what the PR does.

**Comment by dsohler** [comment]
> otherwise we would need APIs for all engine messages.

Yes, that would be the best solution.

**Comment by rubenwardy** [comment]
> otherwise we would need APIs for all engine messages.

Yay over engineering!

Only minimap and zoom needs to be customizable, as they're not privileges and have to be enabled in game. But that PR is better than the current message

**Comment by Wuzzy2** [comment]
> Hmm thinking on this, it's not the responsibility of engine messages to be game-customisable to give game-specific information, they're simple and universal

… and not helpful. I don't understand your logic at all here. Why does it have to be universal? Just for the sake of it? This doesn't make sense.
The player doesn't care about the technical background, the only thing which matters at the end is that the player understands the game.
Seriously, just put yourselves into the shoes of a new player. If you're new to the game, and learn the minimap is “disabled”, what is the first question you will automatically have? Right! “How do I enable it?”. If the game does not answer this question immediately, it has failed.

> otherwise we would need APIs for all engine messages.

No. We don't need APIs for everything. My suggestion was about one specific use case, I didn't suggest to create a full blown API for every engine message. This would be pointless anyway.

> For example i suggest that the map mod in MTG could create a chat message 'on joinplayer' that explains how to enable minimap with an item, if it is survival mode and the item is not present.

This idea is terrible. Don't spam the chat *on each time the player joins*. This will get annoying very quickly. Also, it's server-side (i.e. with delay), but my suggestion would have been on the client side.
If we follow your logic, we would also have to explain many other non-obvious features in the join message, like crafting.

**Comment by rubenwardy** [comment]
> For example i suggest that the map mod in MTG could create a chat message 'on joinplayer' that explains how to enable minimap with an item, if it is survival mode and the item is not present.

Wow, I didn't see this. This is a truly awful idea. Do things right, not short term.

**Comment by paramat** [comment]
> This idea is terrible

Yes it is =)

**Comment by paramat** [comment]
#6770 merged.
