### ISSUE TITLE
Add a new vector.round type function that matches engine rounding

### ISSUE THREAD

**Issue by thetaepsilon-gamedev** [minetest/minetest#6774]
When writing code that dealt with changing node positions, I wished to have some function that, given a vector table, would return a rounded position that corresponded to the center of the node that minetest would target *if* that un-rounded position was given to e.g. minetest.set_node().

Upon experimentation, I found out that vector.round is unsuitable for this, as it unconditionally does math.floor(x+0.5) (same for y, z).
Whereas on my machine (Arch linux, minetest 0.4.16, x86_64), the rounding to whole node positions appears to go like follows for y (similarly for x and z):

* node (0,0,0) occupies interval -0.5 < y < 0.5
* node (0,1,0) occupies 0.5 <= y < 1.5 (the lower bound *is* inclusive!?)
* node (0,-1,0) occupies -1.5 < y <= -0.5

According to the above, y=-0.5 exactly should map to the node at y=-1.

However, if you plug -0.5 into the above, math.floor(x+0.5) = math.floor(0) = 0.

This means that vector.round is unsuitable for this purposes in it's current form - even if this is "works as intended", it is somewhat suprising to devs who may not have initially considered the subtle issue of rounding directions. I feel it should be pointed out in the documentation that the current implementation of vector.round is not suitable for the purpose of "which node does this position round to, matching what the game engine does?".

It could very well be the case that the rounding of positions on the edge between two nodes is platform dependent, but even so, I feel that there should be some exposure of the precise function that minetest internally uses to round positions. This is so that code which needs to know the position that the engine would target doesn't run into suprises.

Steps to reproduce the "suprising behaviour":

* Create a singlenode world using the default game and the luacmd mod for running the example snippet.
* Execute "/lua pos = { ... }", with at least one of the coordinates set to any negative value where the value is an integer - 0.5 (e.g. -0.5, -1.5 etc.)
* Run the following: /lua local a = pos local r = vector.round(a) minetest.set_node(a, {name="default:glass"}) minetest.set_node(r, {name="default:obsidian_glass"})
* Note that the two positions are different. If they were the same, then the obsidian glass would have replaced the regular glass.

It should be noted that the rounding behaviour used by vector.round correctly matches what the engine rounding does when the values are a positive integer + 0.5. Screenshots attached, the last shot is of the correct behaviour when using +0.5.

![screenshot_20171212_122448](https://user-images.githubusercontent.com/32034735/33885931-c5e7b0ec-df3c-11e7-90c4-1e3f21642092.png)
![screenshot_20171212_122510](https://user-images.githubusercontent.com/32034735/33885932-c5ff9b76-df3c-11e7-80f3-9e7499caa5d0.png)
![screenshot_20171212_122649](https://user-images.githubusercontent.com/32034735/33885933-c61765a8-df3c-11e7-95cf-37caa24d5fcb.png)
![screenshot_20171212_123454](https://user-images.githubusercontent.com/32034735/33885935-c631dce4-df3c-11e7-8da7-0351757a21c2.png)

Possible fix for vector.round for the desired behaviour:
For each coordinate in the vector table, if the coordinate is negative, use the expression math.ceil(x-0.5) (substitute y and z as appropriate).
Input from any devs or pointers to the engine code which does this rounding would be appreciated, to verify that this is correct behaviour.

**Comment by paramat** [comment]
Seems best to not alter vector.round, to not break mods that may depend on this behaviour. But we could add a new alternative rounding function.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/637ea86069f1cf94f1fb4a32cec57b9b0529040a/src/script/lua_api/l_env.cpp#L262
https://github.com/minetest/minetest/blob/a1e1a19ac355dbe7e1a2e060fd6b5fe082298eb6/src/script/common/c_converter.cpp#L263
https://github.com/minetest/minetest/blob/9c669016d1578a5c62f932c6ccb7a2b4b1e21f0a/src/util/numeric.h#L249
'float to int' is used in many places in MT to round to a node.

**Comment by rubenwardy** [comment]
Not an issue. Node positions are floored, not rounded

**Comment by thetaepsilon-gamedev** [comment]
@rubenwardy if this was the case, then the existing vector.round routine, which (from builtin/common/vector.lua) uses math.floor, would agree with MT's internal "coerce to node position" operation (rounded, floored, or whatever).
Replacing vector.round with vector.floor for sanity checking in the above lua command produces the opposite issue - "boundary" .5 coordinates below 0 coerce to the same as the engine does, but positive values above zero cause an off-by-one error.

![broken_floor](https://user-images.githubusercontent.com/32034735/33892807-ac0f7366-df51-11e7-80c3-6110a9fd25ff.png)

**Comment by rubenwardy** [comment]
I've used floor in the past for this.

@paramat: where is the player position relative to the camera?

**Comment by paramat** [comment]
Player position is always at the feet position, the camera is now (in 0.5.0dev with new player model) 1.47 nodes above that. Previously it was 1.625 nodes above.

**Comment by thetaepsilon-gamedev** [comment]
This problem shows up regardless of whether or not it's a player position - as shown in the screenshots I was using a fixed position specified by a lua constant.
In any case, there does not seem to be a function provided in the MT api itself that correctly and in all cases rounds to the same node position as the engine would if passed fractional coordinates - I was only able to achieve consistent behaviour with the following routine (apologies for the formatting):

local positive = function(x) return (x > 0) end
local center = function(x)
	if positive(x) then
		return math.floor(x+0.5)
	else
		return math.ceil(x-0.5)
	end
end
coords.round_axis_to_node = center

local center_on_node = function(v)
	local result = {}
	result.x = center(v.x)
	result.y = center(v.y)
	result.z = center(v.z)
	return result
end
coords.round_to_node = center_on_node

The above is in a properly formatted form [here](https://github.com/thetaepsilon-gamedev/minetest-devsupport-modpack/blob/5d1b1f411c34be56050a9866901cdf26ddb6d336/libmthelpers/lib/com/github/thetaepsilon/minetest/libmthelpers/coords.lua#L47).

Using the above, including exact .5 positions (on a given axis) on nodes around 0 on that same axis, the produced rounding position always agrees with how the engine coerces the position if I e.g. pass `{ x=-0.5, y=0, z=0 }` directly to `minetest.set_node`.

**Comment by rubenwardy** [comment]
The engine behaving odd on fractional coordinates is a bug which already has an use. Just floor for now

**Comment by paramat** [comment]
1 year bump. Any core dev support? (i'm neutral).

**Comment by paramat** [comment]
No support for the feature but keeping open for this to be documented:
https://github.com/minetest/minetest/blob/a122ba0ef4af865d225adbe22a55b8001af04c61/doc/client_lua_api.txt#L575

**Comment by JDCodeIt** [comment]
Looks like this is the core function needed. One could then apply to each of x,y,z in a vector function.
```lua
local round = function(d)
	if d >= 0 then
		return (d + 0.5) - (d + 0.5) % 1
	else
		return (d - 0.5) - (d - 0.5) % -1
	end
end

print(round(1.5))
print(round(1.4))
print(round(0.5))
print(round(0.4))
print(round(-0.4))
print(round(-0.5))
print(round(-1.4))
print(round(-1.5))
```
Result:
2
1
1
0
0
-1
-1
-2
