### ISSUE TITLE
Misleading setting description in menu

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6781]
“Normal mapping” setting name is misleading. It does not enable normal mapping; “bump mapping” does. Instead, it enables draw-time generation of normal maps, as suggested by its technical name `generate_normal_maps`.

**Comment by paramat** [comment]
Yes that is confusing and should be improved.

**Comment by ThomasMonroe314** [comment]
@paramat @numberZero 
I think I could handle this if noone else wants to

**Comment by paramat** [comment]
Please do.

**Comment by ThomasMonroe314** [comment]
how does Normal Gen sound?

**Comment by paramat** [comment]
Too ambiguous, 'generate_normal_maps' or something similar is better.

**Comment by ThomasMonroe314** [comment]
ok "Generate Normal Maps" then?

**Comment by ThomasMonroe314** [comment]
the settingtypes.txt and defaultsettings.cpp don't need to be changed, as they already are the same as the above or are sufficiently self-explanatory.

**Comment by NewbProgrammer101** [comment]
fd71a7c
