### ISSUE TITLE
settingtypes.txt with windows-style EOL-characters does not work on linux.

### ISSUE THREAD

**Issue by Distributed-DeadLock** [minetest/minetest#6782]
There seems to be a problem with the settingtypes.txt on linux.
If the windows-style CR/LF character-pairs are used as EOL-termination in the settingtypes.txt, 
Minetest o.4.16 throws some errors on linux, e.g.:
`"017-12-02 23:12:48: ERROR[Main]: Invalid integer setting in /home/dirk/.minetest/mods/thelowerroad//settingtypes.txt "thelowerroad.sinfactor (The road wobble) int 62 40 10000`
The same file works flawless on windows.
Other files, like lua-files, mod.conf, depends.txt and description.txt don't have this problem.

**Comment by Megaf** [comment]
Maybe because the way file is read.
Maybe it should be read like this https://github.com/minetest/minetest/blob/50423d8c729ee133035e3bb1e244bfbd1bdc0ef0/src/mods.cpp#L72
Just wildly guessing.

**Comment by dsohler** [comment]
See full issue caused by that bug [here](https://github.com/Distributed-DeadLock/thelowerroad/issues/1).

**Comment by SmallJoker** [comment]
Closing this issue in favour of #7912 (more discussion).
