### ISSUE TITLE
Soften formspec corners

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6790]
I wanted to see if I could soften up the formspec via giving it rounded corners, any tips would be helpful

**Comment by SmallJoker** [comment]
You could try to use `background[]` with a custom inventory texture, like Jordach did: https://github.com/Jordach/big_freaking_dig/blob/master/mods/xgui/textures/inventory.png
API reference: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1947

**Comment by ThomasMonroe314** [comment]
hmm I was going to do this to the main menu, but I'm not sure how to apply that

**Comment by ThomasMonroe314** [comment]
the problem seems to be how to figure out the size of the formspec

**Comment by ThomasMonroe314** [comment]
hmm I think I'll leave this for when the formspecs get redone, if they ever do that is
