### ISSUE TITLE
General mod-control API

### ISSUE THREAD

**Issue by JLuc** [minetest/minetest#6800]
In dungeon'n'dragon type games, a dungeon master designs a scenario, prepares a world and invites players. He then explains the settings and the quest, and controls scenario specific events, while the players go and play. The events are : monsters appear, traps, treasures, new tools, new weapons, new clothes and new skills, just to name a few. 

So as to achieve such a gameplay in minetest, I would like to be able to control mods so as to dynamicaly pause/activate/change their behaviour.  The goal is to be able to play a LAN minetest with one of the players being the world master.

A basic API could be defined with standard triggable actions
- stop or pause some mod action
- start or resume some mod action

The player with admin rights would be entitled to trigger the API. He could do it either with commands or with the help of a dedicated control panel.

For example, with an active "monsters" mod , the game-master could start the game pausing the spawn with `/stop monsters`, and later lauch the spawn with `/start monsters`

With a `advanced ores` mod, the game-master could start the game with the mod paused, and provide players with advanced ores once they have reached some specific goal or achieved some quest.

Since each mod provides not a single but many functions, it would be good to enable to control more precisely the various actions.

For example with a `farm` mod, the command `/stop farm` would stop all spawing, 
but command `/start farm cows` would only restart cow spawning, but not other animals.

Both the API and a set of basic commands would be global to all minetest mods.

When a mod doesnt provide a function to answer the command, nothing but a nice error message would happen.

One of the global basic commands would enable a mod to explain which API commands it defines.
`/APIcommands monsters` would answer with the list of APIcommands defined-understood by the `monsters` mod.

Some mods could provide mod-specific commands.

Some commands could include parameters : 
- spawning speed : `/start monsters zombie spawnspeed 20`
- spawning area : `/start monsters area 100 200 33` (circle of 33 aroud 100 100)

I guess this general mod control API requires some devs in minetest core.
This is a draft proposal and needs to be discussed and designed more precisely.

**Comment by SmallJoker** [comment]
Limiting mod actions would require checks for each map or player modifying function (`set_pos`, `set_node`), which results in a massive overhead. :-1:

Disregarding the overhead, handling these signals should be up to each mod, so they can decide what functionalities are required and which ones should be restricted:
```Lua
local variable_to_mark_whether_the_mod_should_do_anything = true
minetest.register_on_chatsignal(function(param)
	local args = param:split(' ')
	if #args >= 1 and args[1] == "stop" then
		variable_to_mark_whether_the_mod_should_do_anything = false
	end
end)
```

**Comment by ThomasMonroe314** [comment]
hmm its not a terrible idea, minus the overhead ofc

**Comment by raymoo** [comment]
Is this a correct description of your feature?
* Mods can register tasks that can be run, and might have arguments
* Mods can start tasks and stop / pause / resume existing tasks.
* There are also chat commands to control tasks

It also looks like you want to be able to "start" or "stop" any mod completely, regardless of whether the mod has explicitly registered any such functionality. I am not sure would really do what a user would want / expect. For example:
* A cucumbers mod that uses a different farming mod's exposed functions may register a cucumber that doesn't stop growing when the original farming mod is disabled (because its callbacks are registered under a different mod)
* You could disable a speed boosts mod after it has given a player a boost and before the player has run out of boost, which will prevent the mod from turning off the boost. The player would be stuck in the speed-boosted state.

**Comment by JLuc** [comment]
@raymoo : Your description is correct. As for the 3d point, please note that the goal is to be able to control complying mods in some live-interactive and simplified way ; even non-coders should be able to do it, and it should be done without restarting minetest. Issuing /commands in the chat is a way to achieve this ; another way might be to have a control pane/dialog but it seems complex to design this in a generic way for all complying mods.

You mention an existing *setting API* that enables for example to set the spawn speed : is it possible to use it interactively ? how ? or how possibly could it be used interactively for non-programmers ?

I wonder : when interactive, such an API would enable to control some features of mods allready. For example, `stopping monsters mod` function can be achieved with some command like `/setting_API monsters spawnspeed 0` (just an example since i dunno the way to use that API). It seems doing so doesnt imply new callbacks overheads - or very little.

**Comment by raymoo** [comment]
Actually, I don't think the existing settings API suffices, since mods are not notified when a setting changes, unless it polls ever step.

**Comment by 4w** [comment]
Since mods can’t be loaded on runtime but are only parsed on load time this is completely impossible without a) implement the functionality within the individual mods or b) completely rewrite the mod loading and registering system.

**Comment by zeuner** [comment]
Couldn't most of this be implemented in a lightweight manner from a mod? The mod would be made a dependency of all other mods that require mod control, and export a table where the other mods can insert their tasks into. Then, by iterating through the table, some or all mods can be notified about control requests in order to handle them on their own responsibility.

**Comment by rubenwardy** [comment]
This is overengineering for not much gain. It's better for mods to implement this themselves. :-1:

**Comment by paramat** [comment]
I'm sure this can be done already in mods by coding mods to use chatcommands.
A global API separate from mods means it then has to be oversized to cope with every possible feature that mods may want to provide, the features are impossible to predict and it will need constant updating.
Doing this in the mods themselves is the most efficient and focussed way.
:-1:

**Comment by JLuc** [comment]
@paramat i understand that you refer to solutions like the code @SmallJoker  posted above. Mods parse command line and act accordingly when required.

When *doing this in the mods themselves is the most efficient and focussed way* to be able to interactively control mods behaviours, then some questions arise : 
- does any mod provide such a command line UI as for now ?
- how can it become more easy, for a mod dev, to do it ?
- how can mod devs be enticed in developping such command line UI ?

I feel these could help :
- define and propose a dedicated command line format, so all mods can use the same command line syntax when it fits their need and when they wish so, and so commands line are easier to grasp and use (for the player that masters the game).
- based on that shared dedicated syntax propose some dedicated LUA functions or tools for quick and easier command line parsing and action (for the mod dev)

Other points ?

**Comment by paramat** [comment]
'command line UI ' is chat commands.
It's already easy for mod devs to use chat commands.
No enticement is necessary, it's already simple.

Your suggestions already exist in the API, one is chat commands, the other is the various APIs for processing strings, it doesn't need to be easier.

The APIs we have are necessaarily simple, to make them easier to use in the way you suggest would make them much more complex, which we won't do. Modders are expected to have a certain level of modding skill, it's not meant to be easy for them. Making things easy for players is justified, modders can use their skills to code their mods to do that.
Maybe you can write a mod that provides APIs that provide what you suggest? We're not going to do that for the reasons above.

**Comment by zeuner** [comment]
@rubenwardy: I think the implementation can be streamlined by
providing infrastructure from a mod. Still, no need to put this into
the engine.

original message follows:

**Comment by zeuner** [comment]
@JLuc: Maybe post patches to mod developers implementing a common
chatcommand UI. If they provide real advantages, chances are they will
get merged. Prepare for diverse reactions, though.

original message follows:

**Comment by JLuc** [comment]
I can try go into creating patches but I'm not LUA nor minetest developper so it might take time before i propose one !

I wonder which mod could most easily and efficiently benefit of a command line UI so as to enable interactive mastering of a game. I think some monsters, mobs or ores mod would be fine.

Any idea of a particular mod that would particularly fit this goal, either because of its nice code structure, or because the mod dev is interested in the project ?

**Comment by ThomasMonroe314** [comment]
I don't get what you mean by "command line UI"
the chat commands aren't enough?

**Comment by JLuc** [comment]
yes that's it

**Comment by zeuner** [comment]
Good. The comments should already suffice to allow the thread starter
to proceed.

original message follows:

**Comment by zeuner** [comment]
Ok, good.

original message follows:

**Comment by ThomasMonroe314** [comment]
@JLuc I'm sorry, but: HUH?

**Comment by zeuner** [comment]
@JLuc: Well, the best preconditions for contributing would be both
development skills and an idea on where applying it would be
beneficial. So, I guess it will be challenging.

That being said, I agree that a mob mod where mobs can be
activated/deactivated easily would be useful.

original message follows:
