### ISSUE TITLE
Sky: Get various colors used for sky from server

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#6802]
https://github.com/minetest/minetest/blob/master/src/sky.cpp#L526

There are 9 hardcoded colors here that should be retrieved from the server.

The new `sky` packet could be expanded to include these color values. Clients that know where to look for these values can then use them. Old clients will be unaffected.

This doesn't seem to complex, other than there being lots of different colors. Some experimentation shows that toying around with these values yields good results quickly and mods should be able to use this. Together with the cloud stuff, this would make for a great atmospheric addition.

**Comment by paramat** [comment]
Very useful.

**Comment by raymoo** [comment]
So is the request to expand the sky packet and client code so that the server can tell clients what sky colors to use? I'm guessing anything like a mod API to change these for a player would be a separate feature?

**Comment by sofar** [comment]
So, I just looked at the network stuff and thinking about the api, we might as well just have a new `get|set_skycolors(skycolorparamstable)` API.

From `sky.cpp` I reckon that we need a table with 9 color pairs.

it seems packet wise, looking at `server.cpp`, we should just make a new `Server::SetSkyColors()` function and a new `TOCLIENT_SKY_COLORS` packet.

Then it's just a simple an straightforward api that is mostly passthrough to the client, and the client can cache the values and use them instead of the hardcoded colors.

**Comment by sofar** [comment]
Concept image:

https://i.imgur.com/KS0VJp9.png

**Comment by paramat** [comment]
Lovely.
Can the colours just be added to the existing `set sky` packet? after all that can already set the colour for a plain override sky. `set sky` seems to be the place for it, and obviously this should be per-player to cope with differing realms/planets in a world.

**Comment by sofar** [comment]
Yes, expanding a packet and putting more data into it is always possible, I would be cautious of doing it to prevent conflicts and complex handling.
