### ISSUE TITLE
Draw primitives

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6805]
It would be great if it would be possible to draw primitive elements like a line, circle, square/polygon and maybe a box 

This would be helpful to debug things, make things visible or make ingame things like a leash possible

**Comment by SmallJoker** [comment]
@MarkuBu Is this feature request about formspecs or in-world drawn structures? Either as HUD or with an absolute position given.

**Comment by MarkuBu** [comment]
Ah, sorry, in-world.

**Comment by raymoo** [comment]
Would this be something like an HUD element that gets drawn in the world? Or something you call every frame in CSM?

**Comment by MarkuBu** [comment]
I'll give you a few examples what I have in mind.

I'm working with mobs and I want to make vectors visible. They should appear as line in front of the mob.

With a cube you can for example make mapblocks visible.

You can use a view lines to make a leash if you capture a mob or the rope of a fishing rod

**Comment by raymoo** [comment]
@MarkuBu Could you give an example of the API calls that you might call to do these things? I still don't understand what exactly you want to be able to do.

**Comment by MarkuBu** [comment]
For example, I want to be able to draw a visible line for a fishing rod
https://minecraft.gamepedia.com/File:Fishing_rod.png

Or this 
http://www.chip.de/ii/636598661_ce586a412a.png
https://bugs.mojang.com/secure/attachment/29537/Leash%202.jpg
https://media-elerium.cursecdn.com/avatars/33/21/635889646297079402.png
http://i.imgur.com/5KQV3TI.png

or something like in this video
https://youtu.be/4-3iqcHDjWQ?t=684

API call could look like this

`minetest.draw_line(vec3d, vec3d, width, color)`

Same for box, cube or circle (with a radius instead of a second vector of course)

The function should return an object that you can remove and maybe modify it (change position, color..)

**Comment by raymoo** [comment]
@MarkuBu So you would need to reposition the line every frame since things will move? Is this meant to be on CSM?

**Comment by MarkuBu** [comment]
I don't know if this should be on client or server side. It is not always necessary to reposition the object, but in case of a leash it would

**Comment by raymoo** [comment]
Also in the case of a fishing pole, as long as the float is still moving.

**Comment by benrob0329** [comment]
Draw a line between two objects? Or use an animation?

**Comment by raymoo** [comment]
For a line that follows objects, there's this related issue: https://github.com/minetest/minetest/issues/3693

**Comment by orwell96** [comment]
Maybe some sort of csm register function that gets called every rendering step, such as
```
minetest.register_on_render(function(g)
  g.set_color(255,0,0)
  g.draw_line(pos1, pos2)
  g.draw_polygon(pos3, pos4, pos5)
end)
```
(where g is a 'graphics context')

**Comment by MarkuBu** [comment]
That would be nice, but too slow. But that's the idea

**Comment by raymoo** [comment]
@MarkuBu How would you imagine the code for having a fishing line follow the float look like?

**Comment by benrob0329** [comment]
If done correctly, primitive drawing in CSM could work really well. Although for what this is I think a line on he HUD could work as well (also from CSM, probably easier on performance ie Love2D)

**Comment by MarkuBu** [comment]
Hm, I don't know how this could look like. I don't know enough about the engine.

This probably can be drawn an the hud, but than the perspective, light and so on must be correct. At the end it should look like it is in the real world

**Comment by orwell96** [comment]
Well, then either use the existing hud api or do something with client side modding. A new client-server protocol for that would be overkill IMO

**Comment by paramat** [comment]
1 year bump, any core dev support? (i'm neutral).
