### ISSUE TITLE
Hide or discourage mapgens in main menu on mod request

### ISSUE THREAD

**Issue by zeuner** [minetest/minetest#6806]
There are some mods which are mostly designed to work with only a subset of the available map generators. Mods might either perform poorly with the “wrong” mapgen or simply don't work at all.
One example is biome_lib. The recommended mapgen is v6, and v7 will result in unexpected results regarding temperature and humidity maps. Restricting the mapgen choice often has legit reasons. Either other mapgens would simply never make sense with this mod or they don't work well together.

I think Minetest should allow mods to specify a list of mapgens for which they can be activated. Additionally, it should be possible to list mapgens which technically work more or less, but do not provide the best gameplay experience as “discouraged”. For example, if the mod's mapgen gives poor balancing results in v6 but v6 still works good enough to not outright disable it, v6 can be called “discouraged” which means a small warning is displayed in the world configuration dialog.

The scope of my suggestion is basically ONLY the main menu, specifically the world configuration dialog. Configuration and world data files are still taken seriously. The goal is to not clutter the world creation dialog with mapgens which in reality are never used with the mod.

**Comment by 4w** [comment]
If I understand your suggestion correctly I won’t be able to select v7 if I have a mod in my mods folder that hides/disables v7, even if I do not plan to use said mod.

Wouldn’t it be better to grey out the mod or print a warning in the mod selection dialog instead of hiding or disabling world generators?

**Comment by paramat** [comment]
While selected subgame is known to the mainmenu, the enabled mods are not. You configure a new world to use certain mods after creating that world with a chosen mapgen, and the enabled mods ccan be changed at any time. So i can't see this as possible, and not very useful.

**Comment by Ezhh** [comment]
This works well on a subgame level where you have a number of mods which have been grouped together for a specific goal and with a specific end result/play experience in mind, but when you reduce it to the level of individual mods it could get very messy and needlessly complicated very quickly. 

I feel quite strongly this should not be added to the game.

**Comment by zeuner** [comment]
@Ezhh: As the currently preferred way to implement mapgen filtering is
not lua (where it could work generically for both mods and subgames)
but configuration file parsing, the topic of whether something like
this works well for subgame is off-topic regarding this specific
issue. You may want to open a separate issue in order to lobby how
well this works for subgames.

However, for the sake of the comparison brought up, I think that a
feature like this is actually much more useful when it's available
for mods. For a subgame, the decision whether to combine a particular
subgame and a particular mapgen is a rather singular decision where it
can be expected that the user reads the subgame documentation
once. So, no real need for filtering known-to-work combinations
here. But for mods, it can be a real gain to quickly go through a huge
list of installed mods and see only those that are compatible with the
chosen mapgen. Many small decisions would be made easier by a feature
like this.

original message follows:

**Comment by paramat** [comment]
As i wrote, this is impossible, see why above.
Mapgen for a world is fixed for that world, while mods can and will be turned on and off afterwards, so you can start a world and alter active mods later and still cause the incompatibility probems.

**Comment by zeuner** [comment]
@Paramat:

Regarding possibility:

Due to the current structure of the main menu, it would currently have
to be implemented by hiding or discouraging mods after the mapgen is
already known. Logically, it's not different because it prevents
unusable mapgen/mod combinations, but merely an implementation detail
taking into account the current UI.

Regarding usefulness:

It's fine and acceptable for mods to not support certain
mapgens. Mgv6 is so different it can be very difficult to support that
one. Mods that are for use only in 1 mapgen are also fine.

The requested feature would help users avoid making unusable choices
of mapgen/mod combinations, thereby achieving better adherence to the
principle of least astonishment common to software ergonomics.

original message follows:

**Comment by paramat** [comment]
> it would currently have to be implemented by hiding or discouraging mods after the mapgen is already known.

That's silly. The feature is not needed anyway, it's up to mods to inform users what mapgens they work with in mod documentation.

**Comment by 4w** [comment]
Can mods get what mapgen is used?

**Comment by paramat** [comment]
Yes.

**Comment by zeuner** [comment]
@Dirk: yes: minetest.get_mapgen_info().mgname

original message follows:

**Comment by paramat** [comment]
That's `minetest.get_mapgen_params().mgname` which is deprecated.
Who is Dirk? They seem unrelated to MT, i'll remove the tag.

**Comment by 4w** [comment]
> That should be `minetest.get_mapgen_params().mgname` which is actually deprecated.

If it is deprecated, what i s the new way for mods getting the used mapgen?

**Comment by paramat** [comment]
```
local mg_name = minetest.get_mapgen_setting("mg_name")

if mg_name == "v6" then
...
elseif mg_name == "v7" then
...
```

**Comment by zeuner** [comment]
@Dirk: The mapgen in use can still be checked:

minetest.get_mapgen_setting("mg_name")

original message follows:

**Comment by paramat** [comment]
@zeuner please stop tagging '@ dirk' they are unrelated to MT.
You repeated the code i posted.

**Comment by zeuner** [comment]
@Paramat: Yes (in order to branch according to the different mapgens).

For efficient hiding/greying mods based on the mapgen, it might be
better to be able to define discouraged mapgens inside "mod.conf".

When sticking with lua to do it, it would be great if the mod could
disable itself from lua (and thereby also based on the mapgen choice
if necessary).

original message follows:

**Comment by Ferk** [comment]
> As the currently preferred way to implement mapgen filtering is not lua (where it could work generically for both mods and subgames) but configuration file parsing, the topic of whether something like this works well for subgame is off-topic regarding this specific issue. 

It's actually the other way around. Subgames can provide configuration files (minetest.conf) whereas mods don't offer this. Thus, if you want to use configuration files to affect what's displayed in the menu then subgames would be the right place.

Plus, you can add/remove mods after a world has already been created, which means the "Create World" dialog should not be affected by the mods, only by the subgame. It's totally possible for a user to activate a mapgen mod after the world has been already created with a mapgen that is not supported by that mod.

Imho, the correct way for a mod to enforce a particular mapgen would be to check at runtime the used mapgen and  throw a lua error with its explanation at the very start of the server so the loading is aborted and it can be seen by the admin.

**Comment by zeuner** [comment]
@Paramat: I tagged the name as it appeared in the "From" header of the
e-mail I responded to. Looking at the issue page, it seems that it
does not match the username. So this is probably a github bug. I
notified support about it and I hope they can fix it easily. Still, I
think it's appropriate to tag the user whose comment is
referenced, so the answer can be properly related.

original message follows:

**Comment by zeuner** [comment]
@Paramat: Actually, it is very possible, and I might submit a
pull-request-based proof if time permits.

Of course, the mod manager will have to take into account the mapgen
choice in order to prevent or discourage incompatible updates to the
active mods list in the "configure world" dialog.

original message follows:

**Comment by paramat** [comment]
zeuner
> Actually, it is very possible, and I might submit a pull-request-based proof if time permits. Of course, the mod manager will have to take into account the mapgen choice in order to prevent or discourage incompatible updates to the active mods list in the "configure world" dialog.

There's no good reason to do that and it will be complex code bloat :-1:

**Comment by zeuner** [comment]
@paramat:

Regarding good reasons to do so, you may want to check out the #6792
pull request. It has provably less reason to be merged than the
solution I suggested, which can be easily seen:

1. Technically, being incompatible to a specific mapgen is a
characteristic of one or more mods from a subgame, not of the subgame
itself.

2. Therefore, deciding about support for a specific mapgen from the
subgame will always be a workaround for preventing the incompatible
mods from colliding with the mapgen.

3. Going from there, if there is no good reason to let mods discourage
being used by a specific mapgen, there can't be a good reason to
let the subgame discourage it for its collection of mods.

So, if this is actually a decision that is to be taken based on
technical arguments (culture of debate in this and other related
discussion threads might suggest otherwise, though), there are only
two choices:

a) revert #6792 as its bloat-for-reason ratio will be even lower

b) replace it by a technically more reasonable mod-based check

original message follows:

**Comment by Ezhh** [comment]
> Regarding good reasons to do so, you may want to check out the #6792
pull request. It has provably less reason to be merged than the
solution I suggested

Just no. There is nothing more reasonable about your approach and reasons not to follow it have been given. Please let this drop so the devs can focus on real issues.

**Comment by paramat** [comment]
zeuner, that makes no sense.

**Comment by zeuner** [comment]
@Ezhh: In case you disagree, feel free to disprove the line of
argumentation as it has been given in the comment you partially
quoted. I see no reason for doubt based on your mere request for the
more sane approach to be dropped. In particular, it is technically
impossible for a subgame itself to be incompatible with a mapgen. This
will always be a characteristic of one or more of the mods it consists
of, so the technically appropriate way to handle it is to allow the
game to decide based on mod (meta-)data. If you can name a subgame
where all mods are compatible with a given mapgen, while the subgame
is not, I would be interested.

If you have nothing to contribute on the technical side of this topic,
it may be more efficient for everyone if you would instead focus on
those topics where you do.

original message follows:

**Comment by paramat** [comment]
Ezhh was the contributor who needed, proposed and added mapgen configuration for subgames, from her experience of creating a subgame. She has a better understanding of the issues than you do.
Your most recent argument is contrived logic, the suggestion is completely impractical.
You are also becoming negative about MT devs and complaining about non-technical argument just because they don't agree with you.
It's also been 2 months of argument now and this is enough, this is now the 2nd thread i've had to lock due to you.

**Comment by zeuner** [comment]
@paramat: First of all, thanks for notifying me about having muted the
discussion this time. This saves me from researching and writing
comment after comment by e-mail, only to find out that no one responds
only because you prevented the comment e-mails to appear on github.

Still, there seems to be no valid reason for doing so. If Ezhh had as
a good understanding as you propose, she would have been easily able
to name a single example of a subgame where my more granular approach
would not work (because the subgame introduces the mapgen
incompatibility, rather than a mod included). Muting me instead
suggests that I was actually right.

I hope that you will be able to manage discussions on a technical
level at some point, instead of getting personal because you disagree
with my solution.

original message follows:

**Comment by rubenwardy** [comment]
The issue with per-mod checking for this is:

* It's bad UI in that the player doesn't know at world create time whether the mod is supported with the mapgen they choose. This makes enabling mods rather messy in terms of UI, and increases the chance of incompatibility.
* You'd need to iterate through all mods in the game which could be quite messy if there's no utility code we can reuse.
* There are multiple ways to enable mods - what should happen if someone loads a mod which blacklists a mapgen in world.mt? You say it should just work, but this could be a bad idea and cause mod bugs.

In terms of code, this isn't too bad for the configure menu - the mod.conf is already read, you just need to look at each one and check the mapgens. The issue is the user experience, rather than the technical aspects.

It's also worth noting that you were involved in this discussion, but did not actually say anything raise the issue of per-mod checks before a PR was made #4768

**Comment by Ezhh** [comment]
Sorry, but this was resolved and done. I don't see why I should be goaded into giving you further responses when you are the one being personal.

**Comment by paramat** [comment]
> First of all, thanks for notifying me about having muted the discussion this time. This saves me from researching and writing comment after comment by e-mail, only to find out that no one responds only because you prevented the comment e-mails to appear on github.

Sorry, i was unaware that you could not tell a thread was muted over email, we are not obliged to add a comment stating this as it is clearly stated in the thread if you actually visit the Github page. It is very rare that someone only takes part in a thread by email only.

> Still, there seems to be no valid reason for doing so.

Increasing rudeness and negativity, personal attacks, 2 months after a close. It's ok to argue for a while but it's getting a bit much now and is irritating.

> If Ezhh had as a good understanding as you propose, she would have been easily able to name a single example of a subgame where my more granular approach would not work

Not necessary because you are using contrived logic. Within your carefully constructed isolated and theoretical argument you are logically correct, but practically incorrect as explained.

> Muting me instead suggests that I was actually right.

No, you were muted for reasons given.

> I hope that you will be able to manage discussions on a technical level at some point, instead of getting personal because you disagree with my solution.

We have given technical explanations already. You are the one who became personal first. We are being quite restrained in response to your provocations.
/////////////////

Why was this unlocked when you can see this result? Ezhh and i have been tolerant and patient and now it's just insults from zeuner. I suggest a relock, anyone agree?

**Comment by kilbith** [comment]
> Ezhh is a core dev

![ca6df92ebd9e89f002623beda370970a--steve-carell-so-funny](https://user-images.githubusercontent.com/7883281/37182511-ec8ef4d8-2331-11e8-96de-324b9a1cd8b0.jpg)

@zeuner This project is a funny zoo with lots of wannabes to throw peanuts on.

**Comment by paramat** [comment]
We deleted an attack on Ezhh by kilbith.

**Comment by kilbith** [comment]
As many of you, in a professional dev environment she‘d be only worth serving the coffee and offering some frivolities ;)
