### ISSUE TITLE
Cppcheck findings

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#6808]
Here is a list, sorted by decreasing of importance, of some things found by `cppcheck`:

**Most bug-prone**
* ~`[src/mapgen/mapgen_singlenode.h:38] -> [src/mapgen/mapgen.h:168]:` (warning) The class 'MapgenSinglenode' defines member variable with name 'flags' also defined in its parent class 'Mapgen'.~
* ~`[src/inventorymanager.cpp:802] -> [src/inventorymanager.cpp:804]:` (style) Variable 'found' is reassigned a value before the old one has been used.`~
* `[src/rollback.cpp:*]:` (error) Uninitialized struct member: row.*
  *Even if you’re sure these values are not, and never will be, used in these particular cases, zero- or trap-initialization might be good to use.*
* `[src/util/srp.cpp:1014] -> [src/util/srp.cpp:973]:` (warning) Either the condition 'if(len_M)' is redundant or there is possible null pointer dereference: len_M.

**Performance**
* `[src/script/common/c_internal.cpp:142]:` (style) Condition '!configured' is always true
  *Something like `configured = true;` seems to be missing.*
* `[src/gettext.h:59]:` (performance) Returning the result of c_str() in a function that returns std::string is slow and redundant.
* `[src/gui/guiFormSpecMenu.h:517]:` (performance) Function parameter 'event' should be passed by reference.
* `[src/rollback.cpp:101]:` (performance) Variable 'database_path' is assigned in constructor body. Consider performing initialization in initialization list.

**Copy constructors**
* `[src/map_settings_manager.h:45]:` (style) class 'MapSettingsManager' does not have a copy constructor which is recommended since the class contains a pointer to allocated memory.
* `[src/profiler.h:186]:` (style) class 'ScopeProfiler' does not have a copy constructor which is recommended since the class contains a pointer to allocated memory.
* `[src/settings.h:93]:` (warning) The class 'Settings' has 'operator=' but lack of 'copy constructor'.
  *In all three cases, copy constructors should probably be declared deleted.*

**Late or no initialization**
* `[src/client/render/stereo.cpp:26]:` (warning) Member variable 'RenderingCoreStereo::cam' is not initialized in the constructor.
* `[src/gui/guiFormSpecMenu.h:135]:` (warning) Member variable 'ImageDrawSpec::scale' is not initialized in the constructor.
* ~`[src/mapgen/dungeongen.cpp:39]:` (warning) Member variable 'DungeonGen::vm' is not initialized in the constructor.~
* `[src/reflowscan.cpp:27]:` (warning) Member variable 'ReflowScan::m_lookup' is not initialized in the constructor.
* `[src/sky.cpp:16]:` (warning) Member variable 'Sky::m_clouds_visible' is not initialized in the constructor.
* `[src/sky.cpp:16]:` (warning) Member variable 'Sky::m_sunlight_seen' is not initialized in the constructor.
* `[src/sky.cpp:16]:` (warning) Member variable 'Sky::m_time_brightness' is not initialized in the constructor.
* `[src/sky.cpp:16]:` (warning) Member variable 'Sky::m_time_of_day' is not initialized in the constructor.
* `[src/util/sha1.cpp:65]:` (warning) Member variable 'SHA1::bytes' is not initialized in the constructor.

**C-style pointer casting**
* `[src/collision.cpp:361]:` (style) C-style pointer casting
* `[src/collision.cpp:376]:` (style) C-style pointer casting
  *The cast could be implicit.*
* `[src/clouds.cpp:40]:` (style) C-style pointer casting
* `[src/util/areastore.cpp:118]:` (style) C-style pointer casting
  *C times legacy: casting from void\*. Casts to void\* are implicit and thus are not marked.*
  *Safe as the type matches exactly.*

Also it reports a lot of messages like
* The scope of the variable '*' can be reduced.
* Class '*' has a constructor with 1 argument that is not explicit.

**Comment by paramat** [comment]
I can fix the singlenode and dungeongen issues.

**Comment by paramat** [comment]
PR for mapgen stuff #7741
