### ISSUE TITLE
automatic_face_movement_dir changing direction awkardly

### ISSUE THREAD

**Issue by D00Med** [minetest/minetest#6811]
I tried using automatic_face_movement_dir, and automatic_face_movement_max_rotation_per_sec, in an entity definition, but whenever the entity crosses over a certain direction it spins around in the opposite way to which it was already turning. I'm assuming this has something to do with the movement direction changing from -1 to 1 or something similar.
Example:
![insta](https://user-images.githubusercontent.com/19916704/34185534-9e66eb4c-e571-11e7-99c4-23ae1282302b.gif)

**Comment by paramat** [comment]
@SmallJoker

**Comment by SmallJoker** [comment]
Update your Minetest build to be 089f594 or newer. It's the commit that fixed that very precise issue.

**Comment by D00Med** [comment]
Thanks
