### ISSUE TITLE
Add meta data to texture packs

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6815]
While discussing [this issue](https://github.com/minetest/minetest_game/issues/1980) I had the idea to add meta data to each texture pack.

I often noticed that selection boxes don't fit the texture sizes if I use a different texture pack. For example I have some flowers with a narrow and tall hitbox, but the texture is wide and low. 

For me the logical solution would be to move the information about the selection box into the texture pack. Also other informations like paramtype2 can be stored (optionally) in this meta data, for example if a crop should be displayed as plantlike or a "#" shaped (croplike) plant, because some textures don't work with croplike meshes.

The meta data could be stored in Lua tables identical to the current node definitions. Each texture can have an (optional) file with the same filename as the texture, just with .lua as extension and the engine could check based on the texture name if a meta file exists. If a file exists the engine could load the meta file and replace the informations if available. 

If this would effect load time, a single file could be added to the texture folder with one table and the texture filename as index.

Only textures, that change something to the default, need to add the meta data

**Comment by paramat** [comment]
:-1: I think the use cases you state do not remotely justify the complexity and coding needed.

For some nodes, selectionboxes already only roughly approximate the node dimensions, for various reasons. A non-matching selectionbox is a very minor issue, they are already inevitably fairly crude visually. A particular node tends to have a particular size to it that mostly does not change or changes only a little with a different texture pack.

Nodes have a particular structure to them, it is not reasonable for a texture pack to change that structure by changing the drawtype, and this is simply not needed.

If you want to change properties of a node, use a mod not a texture pack. 

This is another example of suggesting a complex 'solution' to a very minor or non-problem, like the cylinder collisionbox suggestion. Please also think about how MT needs to be fairly simple, and about our extreme limitation of dev and contributor time.

**Comment by MarkuBu** [comment]
I would love to hear the opinion of other people, in this case from artists who make textures and texture packs. Sadly, nobody tells me what they think.

This is an example for this suggestion. 

![screenshot_20171222_193253](https://user-images.githubusercontent.com/16163058/34308839-72bc9cd2-e74f-11e7-8304-89b26ea69d8a.png)

I know it's a minor problem, but these are the little things that makes the difference between game and good game

**Comment by benrob0329** [comment]
The selection box shouldn't even be visible IMHO, if we want it to look like a game.

**Comment by MarkuBu** [comment]
The selection box for nodes can be disabled in the settings of each client individually, but than it is even more important that the selection box matches the texture.

And I think it is the job of the texturepack to change this

**Comment by benrob0329** [comment]
Everything is designed to work with a certain texture and model, if you change it thats on you. Why should we make texture packs more complicated just because the **user provided** textures don't fit the game? We don't need to change the models if the texture doesnt fit the UV mapping, so why should we change the selection box if the texture doesnt fit that?

In my own opinion, selection boxes are made a certain way for a reason, to allow the client to change them could be disastrous to gameplay.

**Comment by MarkuBu** [comment]
WHAT? Most of your post doesn't makes sense. What UV map?? 

And Minetest allows to change the texture pack. And textures can be different

**Comment by benrob0329** [comment]
If the texture doesnt look right on a model, do we change the model? No of course not, we change the texture to fit the model

If we allow the client to change selection and/or collision boxes, that is asking for trouble.

**Comment by MarkuBu** [comment]
The texture looks exactly as it should. Just the selection box doesn't fit

And the client doesn't change anything. It's a server side change

**Comment by benrob0329** [comment]
Your saying that its the game's fault that a user-modified texture doesnt fit, rather than the user's fault for not making the texture fit the game?

As well as saying that a client side change is a server side setting..what??

**Comment by MarkuBu** [comment]
I blame nothing. You still don't understand my point

**Comment by benrob0329** [comment]
>User wants a different texture pack, that texture pack doesn't line up with selection boxes so we should allow the texture pack to change the selection box size.

The problem is that if the client is allowed to change the selection/collision box, things could go horribly awry in very cheatsy ways.

**Comment by paramat** [comment]
Duh, i just realised this wouldn't be possible anyway, as texture packs are clientside so couldn't and shouldn't alter node properties on the server =) This makes some of my arguments redundant.

**Comment by MarkuBu** [comment]
I mostly play Singleplayer, so I didn't think about this.

But there is still a solution. Both, textures and selection box, are client side elements. If a player installes a texture pack then he installes it client side. That means, that the client can read the metadata from the texture pack and override the data from the server.

This doesn't effect anything else and has no effect to the game.
