### ISSUE TITLE
facedir_fixed_texture paramtype2

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#682]
This is a new paramtype2 suggestion: facedir_fixed_texture. It would work like facedir, but the textures would never be rotated (useful for stairs/slabs).

**Comment by paramat** [comment]
Also see https://github.com/minetest/minetest_game/issues/1211

**Comment by Wuzzy2** [comment]
Yes. This is a good thing to have. :+1:

**Comment by Wuzzy2** [comment]
Why this is useful:

Proposed `"facedir_fixed_texture paramtype2"`:
![](https://i.imgur.com/2PL4Jna.png)

`"facedir"`:
![](https://i.imgur.com/6CmfBc3.png)

**Comment by juhdanad** [comment]
This should not be a `paramtype2` option, because the information content of the node's `param2` is unchanged. This should be the tiles' property instead.

**Comment by paramat** [comment]
^ @numberZero stuff to consider, maybe a tile property is the best way to set 'world alignment'?

**Comment by paramat** [comment]
Can't be a paramtype2, continue discusion in #6075
