### ISSUE TITLE
Apply animation for the obtained block/item in the selection bar?

### ISSUE THREAD

**Issue by AnastasiaDunbar** [minetest/minetest#6829]
So you can easily see which slot is being placed.

**Comment by ThomasMonroe314** [comment]
Can you provide more of an explanation?

**Comment by AnastasiaDunbar** [comment]
As you can see the first slot in this GIF:
![image](https://user-images.githubusercontent.com/11806048/34323632-9f65bb1c-e88d-11e7-916e-6ac516713e09.png)

**Comment by SmallJoker** [comment]
Could perhaps be done with shaders.. somehow. This is a "nice to have" eyecandy, which is obviously not essential for gameplay. Surely, a lot ideas like this animation came from Minecraft. But we also don't target on being a clone of that game (in case you thought so) and implement our own ideas.

**Comment by paramat** [comment]
I can't see any purpose, what node has just been dug is already obvious, it either appears in the bar or the stack number increases :-1:

**Comment by MarkuBu** [comment]
It's not a shame to copy things from Minecraft. This feature is not really needed, but a nice eye candy like the animated hearts from Minecraft.

So maybe someone wants to implement this one day

**Comment by TekhnaeRaav** [comment]
I definitely agree, but I do suppose this is something that should probably be implemented at a nearer time to a 1.0 release or after.

**Comment by ThomasMonroe314** [comment]
I agree, just because a feature is from MC or any other game, does not mean we are copying it.
Game content, ie. teextures, names, etc. are different.
@TekhnaeRaav yeah once MT has less critical features being worked on, it would be nice to add this.

**Comment by Fixer-007** [comment]
Don't reinvent the wheel, you can make square one, though...

**Comment by ThomasMonroe314** [comment]
@Fixer-007 , not exactly what I was saying, but I agree.
I meant just because we implement a feature that happens to be from another game does not mean we are copying them.

**Comment by paramat** [comment]
> but I do suppose this is something that should probably be implemented at a nearer time to a 1.0 release or after.

1.0 has no meaning in MT, our version numbers are not like others where we are approaching some kind of 'finished' state. MT isn't in a 'pre-release' or alpha or beta state, it's open-ended development.
We were considering changing version number to 5.0.0 at next release.
