### ISSUE TITLE
Jumping text in creative search (or more)

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#6830]
Seems like a recent problem, have not looked into other fields, not sure if engine or game itself.
Engine 0.5.0-git 8037eda

Demo:
![1](https://user-images.githubusercontent.com/16494741/34327923-20cbaac6-e8da-11e7-8ec8-5baada017faa.gif)

**Comment by Fixer-007** [comment]
Bug is very recent, no such problem in f1d2bc0.

**Comment by SmallJoker** [comment]
@numberZero #6809 seems to have caused this issue. Would you have a moment to look into that issue?
