### ISSUE TITLE
"immortal" doesn't disable fall damage

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6831]
lua_api.txt says:
> The group `immortal` _completely_ disables normal damage.

But it doesn't disable fall damage. If I set `player:set_armor_groups({immortal = 100})` on `register_on_joinplayer()` than normal punch damage is disabled, but I still get fall damage.

either there is a bug in the documentation or a bug in the engine

**Comment by ThomasMonroe314** [comment]
believe it said _normal_ damage, idk if fall damage is considered _normal_ or not

**Comment by desttinghim** [comment]
@ThomasMonroe314  Is there a reason why fall damage should NOT be considered normal damage? I can't see why it wouldn't be.

**Comment by ThomasMonroe314** [comment]
@desttinghim maybe because its calculated differently than hit damage?

**Comment by MarkuBu** [comment]
I would recommend anyway that it should be possible to disable and modify fall damage.

**Comment by stujones11** [comment]
> I would recommend anyway that it should be possible to disable and modify fall damage.

That would be possible if we had #6396

**Comment by nerzhul** [comment]
it's due to the fact that the falling damage is currently client side only and not very manageable by server (due to physics)

**Comment by rubenwardy** [comment]
I don't think that fall damage should respect groups, so :-1:

Instead there should be a multiplier. The reason for this is a strong armour may stop swords, but shouldn't stop fall damage - it may in fact make it worse.

**Comment by MarkuBu** [comment]
What are you talking about? I didn't talk about groups or integrate fall damage to the rest. I talk about to be able to _disable_ fall damage together with the other damage.

And it should be possible to modify the fall height. 

I never talked about armor groups

**Comment by desttinghim** [comment]
Technically the function is setting armor groups. I think there should be some sort of group to disable fall damage. While in real life armor might increase fall damage, it's more useful to leave that up to modders to implement.

**Comment by stujones11** [comment]
> Instead there should be a multiplier.

If we could at least get the reason for damage in the hp-change callback it would be possible to negate or adjust the damage level accordingly. Setting the fall height is another thing entirely but I agree, that should also be possible.

**Comment by benrob0329** [comment]
I think I stand with MarkuBu on this one, if something is set to be **immortal** it should disable *all* damage, as it says in the documentation.

**Comment by rubenwardy** [comment]
It's fine for immortal to disable fall damage, I must have misread this issue

**Comment by stujones11** [comment]
I am really not sure because 'immortal' is still an 'armor' group. I think at very least the documentation needs to be improved.

**Comment by raymoo** [comment]
>Instead there should be a multiplier.

Armor groups are already a multiplier; maybe there could be a group for falling damage? Then armor mods could give armor values > 100 for falling when wearing armor.
