### ISSUE TITLE
minetest crashes after i click on it

### ISSUE THREAD

**Issue by DAREAWSOME** [minetest/minetest#6840]
minetest when ever I start it i get this message
runtime error
program            C:/User/User/Desktop/minetest-0.4.16-win64/bin/minetest.exe

this application has requested the runtime to terminate it in an unusual way.
Please contact team for further information

**Comment by srifqi** [comment]
1. What version did you use? Where did you get it?
2. Possible corruption, try redownload from official web site.
3. Anything on your `debug.txt`? (It is located inside `bin` folder.)

**Comment by DAREAWSOME** [comment]
I used version 0.4.16 I got it from minetest.net
I downloaded it again still gave error
For some reason i dont have debug.txt in bin folder

**Comment by srifqi** [comment]
Try to place Minetest folder into another drive (not in your system's drive).

**Comment by rubenwardy** [comment]
It's better to use our forum for these types of questions

**Comment by DAREAWSOME** [comment]
Everyone who participated thanks my minetest works now
