### ISSUE TITLE
Make the dump function print userdata content

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6842]
https://github.com/minetest/minetest/blob/master/builtin/common/misc_helpers.lua
When you currently dump e.g. a player, it gives `<userdata>`, which is not very helpful.
To get the content printed like a table, you can dump getmetatable(player). https://github.com/minetest/minetest/issues/6791#issuecomment-353801574
I think dump should also dump userdata content, to show that it's userdata and not a table, you can add `<userdata>` before the dumped thing.

**Comment by 4w** [comment]
Same with playerdata and other datas that are currently not printed.

**Comment by HybridDog** [comment]
I think the metatable of players is always the same, so maybe only dump userdata content if it's the variable directly passed to dump, else you could get lots of redundant output when dumping inventories.

**Comment by SmallJoker** [comment]
#7012 merged.
