### ISSUE TITLE
Add "if unlikely" and "if likely"

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6843]
There're some places in the code with a condition which is very likely always false, e.g. [there](https://github.com/minetest/minetest/blob/master/src/light.h#L86). (There's even a comment suggesting that an assertion could be used.)
To make such code easier to understand, you can define an IFL (if likely) and an IFU (if unlikely) and use them instead of simply if.
As **side effect**, they help improving performance a bit when compiling with gcc:
```C
#ifdef __GNUC__
	#define IFU(COND) if (__builtin_expect((COND), 0))
	#define IFL(COND) if (__builtin_expect(!!(COND), 1))
#else
	#define IFU if
	#define IFL if
#endif
```

**Comment by sfan5** [comment]
Sounds a lot like premature optimization to me.

**Comment by red-001** [comment]
I don't see how that's easier to read, but that's subjective to a degree.

**Comment by HybridDog** [comment]
> I don't see how that's easier to read

Take a look at that [success](https://github.com/minetest/minetest/blob/master/src/clientmedia.cpp#L178) test. If there was an if likely instead of an if, you would know that loading the file from media cache usually succeeds (it does, you can also find it out by reading the whole function beginning on line 525), otherwise you may first think that checkAndLoad additionally tests if there are hash value collisions.

**Comment by paramat** [comment]
Doesn't seem easier to understand, and involves lots of rewriting to apply.

**Comment by SmallJoker** [comment]
It's not more readable for me either. Regular `if`s do their job good enough and it's clear what they do.

**Comment by HybridDog** [comment]
Instead of IFU, you could use IF_UNLIKELY, then the meaning is obvious, isn't it?
Why not use such a feature, in the worst case it does the same as a simple if?

**Comment by paramat** [comment]
The behaviour of 'IF_UNLIKELY' is not obvious unless you study what it does.
