### ISSUE TITLE
Lava lighting glitches at chunk borders, Brightness of texture changing 2x per second

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#6845]
Viewing lava from a distance, it's texture artifacts are visible at the chunk borders, with color changing 2 times every second. Smooth lighting does not affect that. Can be reproduced in minimal game too. 
**Minetest build:** 
```
Minetest 0.5.0-dev-debug-189daf87 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
**Video:** GeForce 210 Driver version 340.104
**OS:** Ubuntu Linux 17.10, Xfce desktop environment
The videos below are recorded by me and upladed to youtube (posted as unlisted)
 [![Short video of the bug](https://img.youtube.com/vi/lz9-fj8RuYE/0.jpg)](https://www.youtube.com/watch?v=lz9-fj8RuYE "Short video of the bug")
 [![Same on minimal game](https://img.youtube.com/vi/5bo6ZKCZ3xg/0.jpg)](https://www.youtube.com/watch?v=5bo6ZKCZ3xg "Same on minimal game")
[![Video with smooth lighting disabled](https://img.youtube.com/vi/o9ne46tpi-s/0.jpg)](https://www.youtube.com/watch?v=o9ne46tpi-s "Video with smooth lighting disabled")

**Comment by MarkuBu** [comment]
There is the same issue with water. Each mapblock is rendered independently and each mapblock has its own animation

**Comment by sfan5** [comment]
The changing colors are part of the animation.

Different mapblocks having different animation times is a feature, see this setting:
<pre>#    Whether node texture animations should be desynchronized per mapblock.
# desynchronize_mapblock_texture_animation = true</pre

**Comment by MarkuBu** [comment]
Well, it is a visual bug. Looks unpleasant. Just because it is how the code works doesn't mean that it is "Not a bug"

**Comment by juozaspo** [comment]
The problem is visual border on chunk boundaries, you can see the artifacts where chunk ends and the other begin. Is this a feature and not a bug?

**Comment by paramat** [comment]
It's not a bug because it is intentional, you not liking it does not make it a bug, it's a request and the setting is present (although i seem to remember the syncing may not be perfect).
Liquids look better to me having phase offset per mapblock, it's a large expanse of liquid shimmering differently in different places, all synced looks worse to me.

In a voxel game seeing cubic areas like nodes or mapblocks is natural and not out of character.
I can't see any artifacts, just out of phase animations.
