### ISSUE TITLE
Properly split, format, and order the API documentations

### ISSUE THREAD

**Issue by 4w-zz** [minetest/minetest#6850]
This issue initially was an answer to [this forum post](https://forum.minetest.net/viewtopic.php?p=305845#p305845).

There is [./doc](https://github.com/minetest/minetest/tree/master/doc) for the documentation stuff.

Maybe slowly migrate [./doc/lua_api.txt](https://github.com/minetest/minetest/tree/master/doc/lua_api.txt) (and later on other API documentation files) into individual files for each logical section stored in `./doc/lua_api/section_name.md` (where `section_name` is exactly that but is not identical with the current headlines but grouped logically) and properly format them.

Then only make changes there and remove changed sections from the current multiple thousand lines long lua_api.txt file so over time the file becomes empty and the folder becomes filled with well-readable, maintainable, nicely formatted documentation.

**Comment by rubenwardy** [comment]
This makes sense given both the client and server APIs have common entries

**Comment by ThomasMonroe314** [comment]
+1 It has been somewhat annoying for me to search the lua_api.txt file for a certain function when the same words in that function are found throughout the entire document :P

**Comment by paramat** [comment]
The files must stay as .txt files, for reasons given in #6707 and elsewhere, however they should of course remain in MD format.

**Comment by ThomasMonroe314** [comment]
the form-spec api could be in a separate file as well.

**Comment by Wuzzy2** [comment]
:+1: Full support!

Maybe put all Lua-related stuff into `lua` sub-directory.

If anyone tackels this, also run Dingus over each file when you're done, in order to spot syntax fails.

**Comment by pauloue** [comment]
Maybe there could also be an index file with links to all other files and since it's markdown they could be converted to html pages, which could be included for easy reference locally and also available on the Minetest website?

**Comment by Zughy** [comment]
This is being implemented in a separate repo: https://github.com/minetest/minetest_docs . Closing
