### ISSUE TITLE
Weird behavior when dropping item entities

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#6856]
When you drop an item via Q or Shift+Q it can either float mid-air for a bit before it slowly "flies" down or it can fall through solid nodes and will come back up after ~ 5 seconds.

GIF (16 MB): http://85.214.239.123/mt.gif

**Comment by paramat** [comment]
Can't reproduce on 18b921015a33c6e597f480bccc7e2974af33c4ea

**Comment by IhrFussel** [comment]
It's the newest commit, compiled a few hours ago.

No mods, just minimal. Also happens in newly generated world.

**Comment by SmallJoker** [comment]
How high is your server step? That dropping animation looks very much like a movement prediction from the client to compensate network/server delays.

**Comment by IhrFussel** [comment]
The server step value was for some reason set to 2.0

I didn't install this build or refer to any .conf though so it should use the default one.

Or is the default one always the one in /usr/local/share ?

Anyways the issue seems to be gone now that I set it back to 0.1.
