### ISSUE TITLE
warningstream messages don't appear (since coloured log)

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6861]
I've noticed that some warningstream messages do not appear when I run minetest after compiling it.
Minetest from the ppa shows warning messages.
actionstream, infostream, errorstream etc. are shown.
Some warning messages, e.g. `Not registering alias, item with same name is already defined: […]` and messages generated in lua (`minetest.log("warning", […])`) do appear, others don't (see below).

This problem happens since coloured log messages were added. (https://github.com/minetest/minetest/commit/e049405fdc688a4d619f3ae88008bbe5ee85b569)
The bug is caused by using the settings get function: https://github.com/minetest/minetest/commit/e049405fdc688a4d619f3ae88008bbe5ee85b569#diff-076b60230cbc7f307125f55094bd8a65R122
The settings function can't be used there, e.g. because it isn't restricted to not use e.g. infostream itself. 

How I can reproduce it:
```diff
diff --git a/src/nodedef.cpp b/src/nodedef.cpp
index 790f7154..1a6ed4c8 100644
--- a/src/nodedef.cpp
+++ b/src/nodedef.cpp
@@ -1287,6 +1287,7 @@ content_t CNodeDefManager::set(const std::string &name, const ContentFeatures &d
        assert(name != "");
        assert(name == def.name);
 
+       warningstream << "NodeDefManager: This message should appear" << std::endl;
        // Don't allow redefining ignore (but allow air and unknown)
        if (name == "ignore") {
                warningstream << "NodeDefManager: Ignoring "
```
This should make minetest print `NodeDefManager: This message should appear` as warning message very often, but no message appears.
When using errorstream, actionstream or something else, the messages appear.

I'm using lubuntu 17.10, gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0.

**Comment by rubenwardy** [comment]
I'm experiencing a similar issue, but infostream messages aren't appearing instead

**Comment by paramat** [comment]
Are you both referring to appearence in terminal, debug.txt, or both?

**Comment by HybridDog** [comment]
l've found the bug: https://github.com/minetest/minetest/commit/e049405fdc688a4d619f3ae88008bbe5ee85b569#diff-076b60230cbc7f307125f55094bd8a65R122
When the function is called the first time, g_settings->get is used to get the setting about when to enable colouring.
However, using the settings function there was a bad idea, l guess warningstream is the first one which is used (or infostream in rubenwardy's case), it executes the settings function, which l guess somehow causes a deadlock.

**Comment by SmallJoker** [comment]
#7034 merged.
