### ISSUE TITLE
Server reports "Too many users" when the user count is well below the maximum

### ISSUE THREAD

**Issue by gituser2194** [minetest/minetest#6862]
For example, the "too many users" error often appears on servers that have, say, 21/40 users in the listings. very illogical

**Comment by SmallJoker** [comment]
The server list gets the player list (and thus, the count) each 5 minutes from each server. Do you get that error over a longer span, like 15 minutes, whereas still the same user count is shown in the list?

**Comment by Ezhh** [comment]
@SmallJoker  Surely this isn't connected to what the server list reports? This error often prevents you ever getting to the maximum in the first place. 

For example, if you set max players to 30, no matter how popular your server is you are very unlikely to ever actually get 30 players online. Connections get refused before you reach it (unless you have a priv that allows you to join no matter how many connections there are).

**Comment by ExeterDad** [comment]
I've noted this as well. I've been logged in and tailing the logs. I would see people that can't connect because of the maximum and we were well below the limit. I thought there was some kind of buffer to allow "staff" to be able to connect, but I can't be certain.

**Comment by Ezhh** [comment]
My understanding is that staff can connect regardless of whether the limit is reached (it checks privs). For example, if someone with one of the right privs tries to connect when it's 30/30, you could get 31/30.

**Comment by IhrFussel** [comment]
I'm pretty sure that the server also counts users that didn't join yet.

And on a busy server it's very reasonable to think that maybe 5-10 users are in the connecting process and download media right now.

So while it may be less than the limit ingame or in the server list, the internal code sees the connecting state as "online".

Correct me if I'm wrong.

**Comment by Fixer-007** [comment]
I had the same impression, please investigate.

**Comment by raymoo** [comment]
Sounds like a DoS vulnerability if you can take up connection slots by just stalling in media download.

**Comment by nerzhul** [comment]
this issue is fixed in master branch

**Comment by raymoo** [comment]
I take back the thing about a DoS vulnerability, because you could take up player slots just by logging in anyway.

**Comment by nerzhul** [comment]
@raymoo if valid users are hijacking slots we cannot do anything, sorry :)
