### ISSUE TITLE
Client-side anticheat measurements

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6864]
When a cheating player is detected, usually following happens:
At least two players are on a server, one of them is cheating, let's call him/her Entenflucht.
A player who is not cheating is near Entenflucht. When Entenflucht flies through walls or performs other cheats, this player reports what happened to the moderator e.g. via chat or the minetest forum.
Then, after some time, a moderator or admin has a look at Entenflucht's behaviour (hopefully). If he/she can confirm the cheating, the consequences transpire, e.g. Entenflucht is banned.

If Entenflucht is alone on the server, he/she can cheat as far as server-side anticheat measurements allow it.
The moderators only search for cheaters when they're playing (or confirm a cheat report), else it would be wasted effort (because most players don't cheat).
#
I think this can be automated:
Instead of doing anticheat only server-side, clients could automatically watch other clients' behaviours.
When a client detects a cheating one, the information is sent to the server. Then the server tries to confirm this information, which requires computational effort. 
If the information is wrong, the client who sent the information is reported because he/she probably attacked the server's availability.

In comparison to the server, clients render the map, so they know better where the mesh is dark and what players are able to do.
In comparison to server-side anticheat, the clients automatically search for cheaters, this takes load from the server, e.g. many clients watch many clients, but one of them watches no, only one or only two other clients. This makes it possible to add computationally heavier cheat detection mechanisms.

**Comment by twahm** [comment]
As you said that requires a computational effort so it is implemented should be placed as optional for both the client and the server and should be disabled by default since many clients or servers may not agree.

**Comment by beyondlimits** [comment]
#3822

**Comment by raymoo** [comment]
A human player being able to detect cheating doesn't mean that you could easily have a computer detect cheating. And anyway, I feel as though rendering the map does not give much cheating information beyond already knowing the map data.

**Comment by beyondlimits** [comment]
Please someone in the power add a label: "Anticheat", because there are many issues related to this and it's getting messy.

**Comment by paramat** [comment]
:-1: Anticheat should be serverside obviously, clients can be hacked, so then you will have false cheat reports.
Anticheat is complex to do and will add load to clients, many clients are low-spec devices.
Also i agree with the points above.

**Comment by HybridDog** [comment]
I thought about clients testing the behaviour of other clients which are next to them.

For example, to test if some player flies through a wall, the server would constantly need to test each player's position, which could cause much lag when lots of people are playing on the server.

Instead, clients could test the positions of players near them. A client may test only one player's position. If the client finds out that a player other than itself flies through a wall, it sends this information to the server admin.

**Comment by raymoo** [comment]
It's not that expensive to do one check per player on the server. The map area of the player is probably already loaded since it had to be sent to that player.

**Comment by paramat** [comment]
Ok i understand it would be a client testing 1 player near to them, however the main issue is that clientside anticheat is obviously a silly idea, only the server can do anticheat because clients cannot be trusted. You would end up with gangs of hacked clients moving around in groups and deliberately not checking each other etc. etc.

**Comment by raymoo** [comment]
You can pay me to follow your players around with legitimate clients
