### ISSUE TITLE
Use selection box for punch/rightclick entities and players

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6865]
Currently the collision box is used for punching and right clicking an entity. But the selection box should be used instead.

I suggest to use the selection box for punching entities, because you punch the "selected" entity. The collision box only should be used for collisions (physics) between entities and nodes or entities and entities. Punching is not really a collision in the game because there don't collide real objects. 

This change wouldn't have an effect in most cases, because most mods use the same size for collision box and selection box

A good example for selection box usage is the raycast function. As far as I know it also uses the selection box

Also, I need to reduce the collision box size for my mod, but with this size I hardly can punch or select them.

**Comment by stujones11** [comment]
I would have expected punching to use ray-casting/selection-box anyway. If that is not the case then I agree, it probably should.

**Comment by HybridDog** [comment]
Fyi, sauerbraten uses cylinders: https://github.com/inexorgame/sauerbraten/blob/master/src/shared/geom.cpp#L85

**Comment by MarkuBu** [comment]
Well, it's definitely the collision box. I set the collision box to a width of 0.1 and selection box to 0.8 and it is nearly impossible to hit the entity

**Comment by stujones11** [comment]
For me it seems logical for punch to use the selection-box but others may disagree, though collision and selection boxes were really just the same thing until quite recently.

**Comment by MarkuBu** [comment]
Collision and selection are definitely not the same thing

**Comment by stujones11** [comment]
They were until #6218

**Comment by paramat** [comment]
I support this.

**Comment by stujones11** [comment]
@paramat looking at the code, punching uses `pointed_thing` which in turn uses ray-casting so this should be the current behaviour. A quick test seems to confirm this.

@MarkuBu could you show your test code.

**Comment by MarkuBu** [comment]
It seems that it was a problem with mobs redo. The selectionbox settings wont be added to register_entity().

Let me test this for a moment. I will close this issue if it works now as expected

**Comment by MarkuBu** [comment]
It seems that I got confused because mobs redo doesn't  support the selection box yet. Will close this for now and reopen, if there is still some issue

**Comment by paramat** [comment]
Good news.
