### ISSUE TITLE
Building for Mali framebuffer

### ISSUE THREAD

**Issue by hissingshark** [minetest/minetest#6868]
Hi,

I'm in the process of adding emulators to the Vero4K running OSMC.
That's an Amlogic S905x (ARM Cortex-53 CPU with a Mali 450 GPU) and a Debian based distribution.

I'm looking for good Minecraft inspired game that can be run without an X environment/desktop and ideally gamepad controllable.
I have SDL2 built and working for Mali framebuffer video and the EGL/GLES headers/libraries for the hardware.

Can Minetest be built against this environment?

Many thanks in advance,

**Comment by sfan5** [comment]
Irrlicht has a secondary branch with support for OpenGL ES.
An SDL backend is supported too, but I'm not sure which version of SDL it uses.

Running without an X11 environment might be problematic though, depending on how much SDL abstracts away.

**Comment by hissingshark** [comment]
Ah thanks, found it.  The irricht Makefile is well self documented so I should have enough to go on.
So basically I'm building my own irrlicht libs for the purpose and then fingers crossed for the resulting Minetest build.

I'll give it a spin!

**Comment by nerzhul** [comment]
I close the issue, don't hesitate to add more questions related later, we will re-open

**Comment by hissingshark** [comment]
It turns out that Irrlicht only supports SDL1.2, so that was out...
The Framebuffer support didn't work for my GPU's API (quite outdated code it seems for something called fbDirect?)...

After learning little OpenGL ES for my board so I could rewrite that short section I **think** I have a working `libIrrlicht.so.1.9.0`

Now I'm back to building Minetest!
So far I've supplied cmake with
RUN_IN_PLACE
ENABLE_GLES
EGL_INCLUDE_DIR
EGL_LIBRARY
OPENGLES2_INCLUDE_DIR
OPENGLES2_LIBRARY
IRRLICHT_INCLUDE_DIR
IRRLICHT_LIBRARY

## Questions
1.  `cmake` complains it can't find X11, OpenGL or XXF86VM.  Are these actually required?  I'm not running on an X11 desktop and its a GLESv2 system.  

```
	# Unix probably
	if(BUILD_CLIENT)
		if(NOT HAIKU)
			find_package(X11 REQUIRED)
		endif(NOT HAIKU)
		find_package(OpenGL REQUIRED)
...
	if(NOT HAIKU AND NOT APPLE)
	# This way Xxf86vm is found on OpenBSD too
		find_library(XXF86VM_LIBRARY Xxf86vm)
		mark_as_advanced(XXF86VM_LIBRARY)
```
I note the section calling for them is a bit speculative (Unix _probably_) so is it just not taking a non-desktop/framebuffer-only environment into account?
I've commented these out to proceed to building.  Is that reasonable?

2.  Building then gives an error that it can't find `irrTypes.h`, but this is in the same include folder as `IrrCompileConfig.h`, which I've supplied using `IRRLICHT_INCLUDE_DIR` as above.

3. I'm also curious why Minetest needs the EGL and GLESv2 includes if Irrlicht is meant to be the "engine" doing the heavy lifting?

Many thanks!

**Comment by sfan5** [comment]
> Are these actually required?

Nope, that section is only there to ease statically linking Irrlicht. (which is pretty stupid IMO, Minetest itself does not need any of these)
> I'm also curious why Minetest needs the EGL and GLESv2 includes if Irrlicht is meant to be the "engine" doing the heavy lifting?

Same reason as above AFAIK. On Android Minetest does actually need a few functions from libGLES, but the "heavy lifting" is still done exclusively by Irrlicht.
