### ISSUE TITLE
Would Terra have any benefit for Minetest?

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6871]
This is not necessarily a suggestion to add [Terralang](http://terralang.org/) because I don't fully understand what it does. 

I just want to start a discussion if it would have any benefit for Minetest. It seems to have some interesting features and can comped with the LuaJIT performance. Major problem seems to be that there is currently no official Android support, but it should to be possible

**Comment by sfan5** [comment]
There are several reasons why this can't be added anyway:
* it's unsafe by design (low-level) and thus can't be sandboxed
* it pulls in LLVM which is an absolutely <b>huge</b> dependency
* JIT is not optional, this conflicts with codesigning requirements (iOS) or security features (e.g. grsecurity)

**Comment by MarkuBu** [comment]
I know about these issues. 

But would it have some benefits? For example no OOM issues? Real multitasking?

I don't see this as a replacement for the LuaJIT. Rather, it could be an addition for the core, so I don't see the security issue as a problem.

But this would open the core for lua developers maybe to write mapgens in Lua. 

And to be honest, I don't really care about iOS. If there are restrictions like "no jit", than this platform is not really interesting. And the linking of Terra could be optional like the LuaJIT, Reddit or other modules. Then the iOS version just lacks this feature. And do we already have an iOS version? AFAIK we don't have.

And minetest can already be compiled with LLVM. I don't see the problem with this dependencie

**Comment by sfan5** [comment]
> For example no OOM issues?

That can be solved by either
1) Not using LuaJIT
2) Enabling `GC64` supprt in LuaJIT
3) Allowing use of FFI with Minetest APIs

> And the linking of Terra could be optional

If most of the popular mods turn out to be re-written in Terra, can you still call it "optional"?

> And minetest can already be compiled with LLVM. I don't see the problem with this dependencie

No, no, that's not it.
Terra requires to you to build LLVM <i>for</i> the target platform and include that alongside with Minetest.
On my system that would be 57 MB extra and it's also lots of work to cross-compile (e.g. for Android).

**Comment by MarkuBu** [comment]
>  Not using LuaJIT

This would be too slow for what want to do

> Enabling GC64 support in LuaJIT

AFAIK this is still not stable. And if I require this for a mod most people can't use it because the default is GC64 disabled. So currently no option 

>  Allowing use of FFI with Minetest APIs

Allowing FFI is also an security issue, right? 

> If most of the popular mods turn out to be re-written in Terra, can you still call it "optional"?

As I said, Terra should not replace Lua(JIT) for mods. And to be honest, who plays single player games with lots of heavy mods on a mobile device? I'm pretty sure that no one has installed mesecons, pipeworks and moretrees on a mobile device. Terra would be a server side addition and as I said a core extension and not for modding. It won't have any effect to a mobile client that is mostly used to play online.

Instead of pointing out the problems it would be more interesting to know if there are any benefits like multithreading. Since it is a low level system language I assume it is possible.

I think things like mapgens or a mob api would be possible to write in terra, easier to develop and maintain and with nearly the same performance as in C++.

And again: Terra should not replace Lua(JIT) for modding!

**Comment by paramat** [comment]
Seems no point in discussing the benefits here if it can't be added to MT. It's ok to have a discussion about Terra but a MT issue is not the place if it can't and won't be added, maybe discuss on the forum?
