### ISSUE TITLE
`minetest.wrap_text(str, len, false)` returns `table` not `string`

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#6879]
```
print(type(minetest.wrap_text("", 5, false)))
```

expected output: `string`
actual output: `table`

thus it's not possible to make it into a string, which is needed for e.g. formspecs.

I'm ... perplexed this doesn't work though. I don't understand why not.

**Comment by HybridDog** [comment]
I can't reproduce it, I get string.

**Comment by sofar** [comment]
urgh, it's on 0.4.16, which doesn't have `as_table`
