### ISSUE TITLE
Screen turns blue under water in 3rd person forwards view

### ISSUE THREAD

**Issue by MarkuBu** [minetest/minetest#6885]
The screen turns blue if the head of the player is in the water, but the camera in 3rd person view is still over the water

![screenshot_20180106_140043](https://user-images.githubusercontent.com/16163058/34639957-099341f6-f2ea-11e7-9fc0-906434df5649.png)
![screenshot_20180106_140048](https://user-images.githubusercontent.com/16163058/34639958-0b3a5dc8-f2ea-11e7-9e5f-382287d12ccd.png)

**Comment by red-001** [comment]
also happens in reverse.

**Comment by paramat** [comment]
Bug only happens in 3rd person forwards facing view.

**Comment by paramat** [comment]
![screenshot_20180226_155003](https://user-images.githubusercontent.com/3686677/36680115-d31f40d4-1b0c-11e8-8abd-63da4f47f463.png)

Yes.

**Comment by paramat** [comment]
#7076 merged.
