### ISSUE TITLE
Builtins need delinting.

### ISSUE THREAD

**Issue by fozolo** [minetest/minetest#6891]
A quick `luacheck builtin/common/misc_helpers.lua` uncovered the following:

~common/misc_helpers.lua:166:18: unused variable seplen~
~common/misc_helpers.lua:380:5: setting non-standard global variable cparam2~
~common/misc_helpers.lua:391:24: unused variable removed~
~common/misc_helpers.lua:493:8: variable p was previously defined on line 485~

The second one (`cparam2`) is definitely a bug that affects node orientation during placement. It should be `param2`.

Unfortunately, I'm way too far behind to make a pull request anytime soon but here is a start to a `.luacheckrc` file.

```
globals = {"basic_dump", "core", "dump2", "dump", "string", "table", "math",
  "file_exists", "get_last_folder", "cleanup_path", "fgettext_ne", "fgettext" }

read_globals = {"DIR_DELIM", "INIT", "vector", "game", "ItemStack"}
```

**Comment by paramat** [comment]
PR #7737

**Comment by paramat** [comment]
Yes, i know :)
This issue also reports a bug (cparam).

**Comment by paramat** [comment]
```
		local old_itemstack = ItemStack(itemstack)
		local new_itemstack, removed = core.item_place_node(
			itemstack, placer, pointed_thing, param2, prevent_after_place
		)
		return infinitestacks and old_itemstack or new_itemstack
```
'removed' can't be removed as the function returns 2 values.

**Comment by pauloue** [comment]
I think this can be closed since builtin passes luacheck now.
