### ISSUE TITLE
Stairs and slabs registrations modify "groups" table argument

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#6892]
In stairs/init.lua, the _groups_ table is being modified by stairs.register_stair( ) and stairs.register_slab( ). Tables in Lua are is always passed by reference not by value as arguments to functions.

Therefore, any calling functions can no longer rely on the integrity of the _groups_ table. For example, stairs.register_stair_and_slab( ) maintains a _groups_ table as a variable not a constant. As a result, slabs are added to "stair" group, only because slabs are defined after stairs.

```
function stairs.register_stair_and_slab(subname, recipeitem, groups, images, desc_stair, desc_slab, sounds)
	stairs.register_stair(subname, recipeitem, groups, images, desc_stair, sounds)
	stairs.register_stair_inner(subname, recipeitem, groups, images, desc_stair, sounds)
	stairs.register_stair_outer(subname, recipeitem, groups, images, desc_stair, sounds)
	stairs.register_slab(subname, recipeitem, groups, images, desc_slab, sounds)
end
```

Of course, this isn't the only nefarious thing happening here. The _groups_ table is also being assigned to an element within the node definition table. As a result, any time this table is modified elsewhere in the script, **the groups of all prior node definitions will change too!** This can easily be observed since slabs are defined after stairs, yet nonetheless stairs end up being added to the "slab" group.

Now, imagine what could happen if a mod relied on a global variable in a scenario like this.

```
unobtainum_groups = {cracky=3, oddly_breakable_by_hand=1}

minetest.register_node("unobtanium:block", {
	description = S("Unobtanium Block"),
	tiles = {"unobtanium_block.png"},
	groups = unobtanium_groups,
	sounds = default.node_sound_glass_defaults(),
})

stairs.register_all("unobtanium", "unobtanium:block",
        unobtanium_groups,
        {"unobtanium_block.png"},
        S("Unobtanium Block"),
        stairs.glass)
```

Such a bug would likely not be detected until months later when the mod author is trying to determine why all Unobtanium are included in the "stair" and "slab" groups.

It is considered a best practice to _never_ modify any argument to a function that is a table, but to copy it to a secondary table instead. Functions should work passively on their input unless volatile behavior can be expected given the function name (like delete_table( table ) for example). Ideally, tables should not be directly assigned to an element within another table either, but instead copied to a secondary table, unless a by-reference assignment is intentional (which in the above cases it is obviously not).

**Comment by rubenwardy** [comment]
This is a minetest/minetest_game issue
