### ISSUE TITLE
Let player crawl

### ISSUE THREAD

**Issue by farooqkz** [minetest/minetest#6893]
I think this could be a mode which player can enter and quit. In this mode player's height is 1 block, his/her velocity is lower and many other limitations.
Purpose of crawling is for example dodging an incoming arrow or bullet or passing a small hole.

**Comment by rubenwardy** [comment]
This is more of a thing that a subgame / mod should add, but the engine should still make possible. I believe this is almost possible with custom models and player heights, however you lack enough keys to bind to and client-side prediction.

**Comment by jastevenson303** [comment]
The keys, and the actions their bound to, are very restrictive.  In a certain other free software game, one can simply
```
alias this say that
bind x this
```
and everytime you hit X it sends "that" to chat, because `say` is how you chat, whereas in Minetest everything is chat, and then filtered for commands.

**Comment by paramat** [comment]
This is mostly a game issue, the game supplies the player model and animation, and can alter the collisionbox and eye height. The only issue left is controls, which is dealt with in several other issues.

**Comment by jastevenson303** [comment]
What other issues?

**Comment by rubenwardy** [comment]
#2731

**Comment by jastevenson303** [comment]
Is there an open issue for crawling/crouching?  This one is closed.

**Comment by jastevenson303** [comment]
Is there an open issue for crawling/crouching?  This one is closed.

**Comment by jastevenson303** [comment]
Is there an open issue for crawling/crouching?

**Comment by jastevenson303** [comment]
Also paramat says this is a game issue.

**Comment by paramat** [comment]
Is there a reason for this to be open if the only engine issue is controls, which is covered by key binding issues?

**Comment by jastevenson303** [comment]
This is a separate feature request, and as such is /valid/.

**Comment by ThomasMonroe314** [comment]
@jastevenson303 I think what paramat is trying to tell you is that the issues needed to implement this feature are already in discussions elsewhere, and also that the issue would need to be addressed in MTG, not here.

**Comment by jastevenson303** [comment]
I think this should be open until #2731 - or its CSM implementation - is merged.  Just my two cents.

**Comment by paramat** [comment]
It's mainly a game issue and is covered by https://github.com/minetest/minetest_game/issues/2013
The only engine issue is allowing special controls, which is covered by other engine issues. If you add the idea to a control issue it will add support for more flexible controls.
