### ISSUE TITLE
Android build fails with missing header

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest#6894]
I am currently in the process of rebasing #6796 following the recent game UI refactors (thanks nerzhul) but I am now getting the following build error
```
In file included from jni/src/script/scripting_server.h:21:
jni/src/script/cpp_api/s_base.h:38:10: fatal error: 'cmake_config.h' file not
      found
#include "cmake_config.h"
```
AFAIK, no such file does exist, only `cmake_config.h.in` & `cmake_config_githash.h.in` since I do not fully understand the reason for these extensions I am not qualified to fix this.

This was introduced quite recently by 30821ad8deb42728fbba9de60dda31033f70aaac though surprisingly this does not seem to affect the regular build.

**Comment by stujones11** [comment]
Ha, I just realized `cmake` actually generates this file, hence why the regular build succeeds.

I am currently not sure if this classifies as a bug or not but it's definitely worthy of note. You now need to run cmake before building for android, this was not necessary before.

I'll let the devs decide what to do with this but it's solved, at least, for my part.

**Comment by sfan5** [comment]
Yes this is a bug.
the file should be including `config.h` instead
