### ISSUE TITLE
Linux creative is different from windows creative

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#6895]
Right now when you go into creative on windows you can go inside of blocks, however on a linux machine you won't be able to.

**Comment by paramat** [comment]
Odd, can anyone confirm?

**Comment by TekhnaeRaav** [comment]
Which was it meant to be?
Going through the walls or not?

**Comment by Ezhh** [comment]
From a quick test, unable to duplicate, (at least using sfan's most recent Windows build on the forum so something may have happened since then?).

TekhnaeRaav, could you explain what sort of going through walls it is? Are you able to walk through walls without noclip active? Do you start under the ground? Something else?

**Comment by TekhnaeRaav** [comment]
Oops, sorry I did not know about noclip(noclip is wall passing right?). I'll explain. I usually grantme all in creative so, on my windows machine I would pass through walls. So windows is working:+1:, I revoke noclip and I don't pass through the walls anymore. But now I see the problem that noclip is not working on Linux. I try to allow noclip priv, but I'm not passing through walls.

**Comment by Ezhh** [comment]
Did you try "/grant singleplayer noclip"?

**Comment by MarkuBu** [comment]
Probably you have to activate it with a keypress. What's the default key for noclip? H? I don't know. I don't have a standard keyboard.

**Comment by TekhnaeRaav** [comment]
Hmmm... no, both ways say that noclip is part of my privs but it still does not work

**Comment by Ezhh** [comment]
Have you tried while flying? You need to be flying.

**Comment by TekhnaeRaav** [comment]
Yes, every time.

**Comment by TekhnaeRaav** [comment]
Problem solved! It appears somehow my minetest.conf did not have noclip settings in it, I put noclip = true and it worked.

Thanks for your help.

**Comment by TekhnaeRaav** [comment]
Oh, haha, should of tried 'H', ooops. :disappointed:
