### ISSUE TITLE
Define a node without a respective item

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#6919]
There should be a way to register a node without a matching item so some nodes are not obtainable in item form. Most of my examples for usecases are from the minetest_game subgame, so this is a list of possible applications:
* The top blocks for a regular and fancy bed
* The hidden node for doors (doors:hidden)
* The flowing variant of liquids (I still find placing liquid source blocks to be useful)
* Crops (Partially grown wheat/cotton)
* Nodes you can't place as it stands (as in "ignore")
* Air (Optionally as I can see some use for it)
* Opened Chests
* Fire?
* The source variants of liquids (This should only be useful if buckets don't empty in creative)
* Ignited TNT
* Many, many more

The reasons for this is not to restrict what a player can and cannot do, but rather attempt to eliminate possible problems. Some nodes weren't meant to be placed by a player.

**Comment by paramat** [comment]
What do you mean by 'matching item'? If there's no item then the node cannot exist in the world?
These nodes need to be placeable by players in creative mode, or if not 'not_in_creative_inventory = 1' takes care of that.
:-1:

**Comment by bigfoot547** [comment]
Hold yer horses. The point of this issue is to make it so that some blocks aren't _obtainable in the inventory_. They can be placed with `set_node`, however.

> If there's no item then the node cannot exist in the world?

Is that really how minetest works? Eww.
I mean this: Say someone makes a node called A. It's a problem if A is placed in the world since an ABM runs and uses a specific metadata tag not set on place. So then they make a nodedef for A but not an itemdef, therefore `/giveme A` says that there is no such item, but it is a node.

**Comment by bigfoot547** [comment]
> These nodes need to be placeable by players in creative mode, or if not, 'not_in_creative_inventory = 1' takes care of that.

/give.
Furthermore, that was a list of possible uses, it doesn't necessarily mean those will be effected should a feature like this be added. Next, some nodes don't even function properly and some even cause a lua crash when placed. I don't think it would be particularly useful to place the top portion of a bed which is not pointable and is hard to be removed. I have taken a look at the code, maybe since everything is an "item", I didn't necessarily use the correct terminology... But as I have said before, I believe some of these nodes be unobtainable in the inventory.

**Comment by SmallJoker** [comment]
Possible workaround: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4605
```Lua
on_place = function() end,
-- And:
groups = { ... , not_in_creative_inventory = 1 }
```

This request is impossible to implement, as you can't know when the node should exist and when not, for example: (`/give` command)
https://github.com/minetest/minetest/blob/d45e5da8ca808e552123bcd94e76b0b435a6ea79/builtin/game/chatcommands.lua#L560

If you want to hide it from `/give`, then overwrite that chat command or add a callback. :-1:

**Comment by rubenwardy** [comment]
This is added complexity and ugliness for something that is already possible. To make something unobtainable, do what Krock said. :-1:
