### ISSUE TITLE
Subgame sound packs

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#6920]
As with the problem described in #5860 (a feature which is now merged: #6032), subgame makers face the same issue when it comes to sound packs.

My proposal is to implement this the same way as with subgame textures pack support:

>If the subgame contains a folder called **`sounds`** the server will load it
    as a sound pack, overriding mod sounds.

**Comment by paramat** [comment]
Best discuss in the existing #4093

**Comment by tacotexmex** [comment]
I disagree. #4093 is about unified ”resource packs”. That might come later, but it’s not the same as this issue, which is about _subgame_ sound overrides.

**Comment by paramat** [comment]
Not really, it's a general issue about sound packs, the discussion is about various related issues and the title has been changed. If sound packs are added then the implementation (game soundpacks) is naturally a subject of that issue.

**Comment by tacotexmex** [comment]
Okay then.

**Comment by red-001** [comment]
@paramat then the title should be changed, since the current title doesn't in anyway reflect that, in any case smaller issues like this one are also useful as it makes them easier to reference in PRs and to track progress on more complex issues.
