### ISSUE TITLE
Require a clear description for non-trivial PRs

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6923]
See CSM PRs #5093 #5094 #5092 #5100 #5089 as examples, which likely contributed to the mistakes made in the development of CSM. See https://github.com/minetest/minetest/issues/6736#issuecomment-358156393

I suggest that a clear description of everything a non-trivial PR does is required in the PR thread, otherwise no merge.
I ask this is added to development guidelines.

* This helps devs review PRs as it helps them towards understanding what the code does. Reviews are desperately needed but are daunting, hard work, time consuming and exhausting, the PR author already understands what the PR does so it is easy for them to explain.
* MT devs do not understand the code of every part of MT, so it cannot be assumed that a PR can be understood by all devs through code review.
* It helps non-devs understand what is going on, which would have helped avoid the mistakes made with CSM.

I will now -1, ask, warn, and then close any non-trivial PR without a description.

**Comment by SmallJoker** [comment]
I'd also like to bring my opinion about PR descriptions in here.
It doesn't have to be an essay (hail TL;DR) and simply contain the most important information about
* purpose of the PR (bugfix, feature, maintenance)
* what the PR does (or should do)
* test instructions, perhaps even a testing mod (if existent)
But nothing of that helps if a PR is forgotten for some reason or stalling, sadly :/

**Comment by rubenwardy** [comment]
It's fine if the title accurate explains the contents. If you do things that aren't mentioned in the title, such as moving the death formspec to built-in, then it should be mentioned in the description

**Comment by Ezhh** [comment]
Enough descriptive information to understand what something does would make both testing and feedback much easier. Even a short and concise description can help a long way.

**Comment by nerzhul** [comment]
it seems paramat is CSM against mood, i think i will finish to stop any development in minetest if this situation against CSM without proper code solution proposal is added, as i only think i loose my time to answer to those things. CSM basis are here, it needs improvements, then please help and code instead of remove the world, me and red-001 took dozens of ours to permits having this important milestone to be there, yes it's not complete, but look at MT 0.4.0 and first mods and compare...

**Comment by nerzhul** [comment]
also closing technical PR for description is stupid, just comment, also GH has support for issue templates and PR templates, just add it to project and it will simplify the workflow for every external contributor.

**Comment by jastevenson303** [comment]
If cam is removed it will be a sad day indeed.

**Comment by paramat** [comment]
Nerzhul, the PRs listed are CSM PRs because i was checking CSM PRs for approvals as you know (and made a mistake, sorry). There are probably many non-CSM PRs lacking descriptions, so this is not a CSM thing, but it does give the impression that CSM development was a 2-person project that was somewhat unclear to others, probably not intentionally. As you know many others missed what was going on until too late and CSM was released in 0.4.16 too early, a big mistake and i feel asking for descriptions will help avoid the same happening again.

It started with the death formspec moving to CSM, which is somewhat controversial, but was not described in the PR thread or commit message, or in #5088 , that was unnacceptable and increases the chance of things slipping in unnoticed.
I was quite lenient about descriptions because many PRs were trivial or simple or obvious from thread title. But some were obviously lacking description, and i noticed that red-001 is generally bad at adding descriptions.

I won't close PRs without descriptions immediately, i will ask for a description first and it will probably appear.

>  if this situation against CSM without proper code solution proposal is added

No idea what you are saying here.

I want server-provided CSM added, i don't want CSM removed, many do. I know that removing CSM would be an unpleasant thing to do after all your work, and i expect it will stay and hopefully not be as big a problem as some fear.

**Comment by lhofhansl** [comment]
It's not too much to ask for a clear, concise description for any PR, trivial or not.
I agree wholeheartedly with this.

It'll make the live of the contributor easier as well, since reviews, test, etc, will be easier. Win/win.

**Comment by lhofhansl** [comment]
Rather than closing, IMHO it's better to simply ask for a description (and perhaps explain why).

**Comment by paramat** [comment]
It would somewhat come under the 1 month rule for PR neglect, but i doubt the situation would ever get to that point.
From dev rules:
"If a pull request or an issue does not get a response from its author in one month (when requiring more details), it is closed."
