### ISSUE TITLE
CSM PRs without 2 stated approvals

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6924]
Non-trivial PRs. The approvals may be elsewhere, if so please search and link to them, otherwise these will need review and post-approval.
Existing rule: "People considering merging pull requests are not required to look anything up anywhere else than the pull request and its comments."

#5094 
#5093 
#5097 
#5307 
#5149 controversial 'get node'.
#5142 
#5140 
#5092 
#5100 no stated approvals.
#5089 no stated approvals.

@nerzhul @red-001

**Comment by nerzhul** [comment]
All those PR were merged to a devel branch not master, then the rule doesn't apply to those PR, the rule apply to the master branch :)

**Comment by nerzhul** [comment]
note: i linked you the main pr in a previous comment on it

**Comment by nerzhul** [comment]
note2: i don't understand why do you want to achieve by reporting this issue

**Comment by paramat** [comment]
Oops, sorry. Just checking stuff had approval.
