### ISSUE TITLE
Built-in user whitelist for servers

### ISSUE THREAD

**Issue by bigfoot547** [minetest/minetest#6927]
Is this a feature already? If this gets approval, I will work on this. I plan on making it in a whitelist command like this:

* /whitelist <on | off | add | add-ip | remove | list | check> ...
There could be a remove-ip if required.
The whitelist is disabled if in single player, and the name in the `name` setting is automatically added to the whitelist. Next, there will be a `whitelist` privilege that allows a specific user to use /whitelist.
Please give me feedback on this though: I want to also add a `whitelist-announce` privilege. Users with this privilege receive whitelist notifications such as a user being blocked by the whitelist, a user or IP being added or removed from the whitelist, or a user being kicked from the /whitelist check command.

These are my plans, please tell me what you think :)

**Comment by rubenwardy** [comment]
I think this should be a mod, but wouldn't oppose any PRs

**Comment by rubenwardy** [comment]
Closed as I think this should be a mod

**Comment by Zughy** [comment]
Should this really be a mod? I mean, [I made it](https://content.minetest.net/packages/Zughy/whitelist/), but it's frankly annoying to not have it by default. It's an essential feature when you want to keep players out, e.g. when the server is in maintenance. Or if someone likes to DoSS you
