### ISSUE TITLE
Allow 6 different textures for more drawtypes

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6929]
Many drawtypes can only accept 1 texture, seems based on basic usage in early MTG.
@numberZero would this have any performance impact?

EDIT: Making an existing drawtype support 6 tiles may affect performance, testing is required to find out. If so, it might be better to add a new drawtype specifically for when multiple tiles are needed.

**Comment by numberZero** [comment]
In current code, that would need copying TileSpecs even more. But that’s only due to inherent inefficiency of the current code; that can easily be fixed, I suppose.

**Comment by paramat** [comment]
Ok, but this copying only occurs at game session startup? Or will it affect in-game performance?

**Comment by numberZero** [comment]
@paramat See #6930. Before that, TileSpecs and TileLayers are copied all the time during meshgen.

**Comment by paramat** [comment]
Thanks for that PR.

**Comment by paramat** [comment]
Requires efficiency improvements to avoid performance hit. Think about all those leaves nodes in forests.

**Comment by numberZero** [comment]
> if a drawtype can accept 6 textures does the performance impact depend on the number of textures it can accept (6) or the actual number of textures specified (often only 1)?

Both numbers probably matter.
@paramat Wanna me make a PR? Performance is a subtle matter, only testing can show true bottlenecks.

**Comment by paramat** [comment]
Yes a PR would be good, you're the ideal person to write it. I think this will be a popular and very useful feature.

If those numbers have a significant impact on performance it is actually useful to have drawtypes that only accept 1 texture, and use those for as many nodea as possible. So it may be a good idea to add a new 'simple normal' drawtype that is an opaque cubic node that accepts 1 texture only.

**Comment by benrob0329** [comment]
Why not just optimize based on how many textures are passed, since node textures are static anyways.

**Comment by numberZero** [comment]
@benrob0329 MT meshgen is complicated. Just take a look at the structure defining one tile: https://github.com/minetest/minetest/blob/master/src/client/tile.h#L314
It doesn’t look large, but it includes e.g. rotation which was never there, but is used internally, and it also includes 2 layers: https://github.com/minetest/minetest/blob/master/src/client/tile.h#L203
Each layer has several textures, animation properties, color and other stuff.

The system is thus not very efficient neither easily extensible, or even modifiable. But it’s not simple to develop something better.

**Comment by numberZero** [comment]
Is there a proper way to know whether was a (special) tile specified?

**Comment by numberZero** [comment]
@paramat There is a problem: this will break compatibility, at least with `glasslike_framed_optional`: it relies on the fact that `glasslike` uses only the first tile, leaving second one for `glasslike_framed`-only usage. `glasslike` could be made to use special tile, if any, and `glasslike_framed` would use that to render the frame (using normal tiles for details), but first special tile is used already for in-glass liquid.

**Comment by numberZero** [comment]
Just an idea: instead of using plain TileSpecs and TileLayers everywhere, why not to use some lightweight structures with numerical material IDs, equal iff buffers using these materials are compatible?

**Comment by paramat** [comment]
> better to add a new drawtype specifically for when multiple tiles are needed.
