### ISSUE TITLE
Make pathfinder take mob size into account, and involve entity collisionboxes

### ISSUE THREAD

**Issue by KaiGerdMueller** [minetest/minetest#6933]
the minetest pathfinder code in minetest/src/pathfinder.cpp does not involve entity collisionboxes.

I also think the pathfinder searches for a path with the size of 1 node,
what would mean that the pathfinder may find paths that are too small for all creatures with playerlike size or bigger. (most mobs have playerlike size.)

also, adding this feature would be very easy, as collisionboxes don't rotate, so the algorithm may first loop through every node, checking if there would be enough room for the entity if it's center was there, and making the node walkable if not. (of course the real map doesn't get manipulated.)
the rest of the code could stay the same.

Else, "smart" mobs may get stuck in front of some 1 node wide tunnel trying to get through.

To keep backwards compatibility, I suggest to make the collisionbox parameter optional.

**Comment by MarkuBu** [comment]
The builtin pathfinder is broken by design. Nothing new

**Comment by paramat** [comment]
Here are the other issues https://github.com/minetest/minetest/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+pathfinder

**Comment by KaiGerdMueller** [comment]
I like the Idea of a builtin pathfinder so I proposed an easy solution for that:

"also, adding this feature would be very easy, as collisionboxes don't rotate, so the algorithm may first loop through every node, checking if there would be enough room for the entity if it's center was there, and making the node walkable if not. (of course the real map doesn't get manipulated.)"

the problem is that I nearly never used c and that I don't know the structure of the code, so I can't fix it.
I hope that the creator takes the time and fixes the pathfinder.

**Comment by paramat** [comment]
:+1:

**Comment by appgurueu** [comment]
Part of #5479
