### ISSUE TITLE
Shift + Q (drop single item from stack) is broken in older clients if server runs with 0.4.17

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#6934]
If you try to drop just a single item in your hand (shift + Q) it will drop the entire stack.

This bug was likely caused by #6242 which made the item drop check client side.

The commit should probably be reverted in 0.4.17

**Comment by paramat** [comment]
@sfan5

**Comment by rubenwardy** [comment]
That pr shouldn't be in 0.4.17

**Comment by paramat** [comment]
Added to TODO in #6746

**Comment by sfan5** [comment]
was fixed.
