### ISSUE TITLE
lua_api.txt wrong control bits

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#6942]
The control bits in lua_api.txt are wrong.  I think.  It's supposed to be like 1, 2, 4, 8, 16, 32, 64, 128, 256?

**Comment by SmallJoker** [comment]
No, they're correct.
However, in technical documentations you'll rather see them formatted like this:

_Bits of `get_player_control()`_

| 15 | 14 | 13 | 12 | 11 | 10 | 9 | 8   | 7   | 6     | 5    | 4    | 3     | 2    | 1    | 0  |
|----|----|----|----|----|----|---|-----|-----|-------|------|------|-------|------|------|----|
| -  | -  | -  | -  | -  | -  | - | RMB | LMB | sneak | aux1 | jump | right | left | down | up |
_Bits 9-15 are currently unused and default to 0 on read_

**Comment by jastevenson303** [comment]
So it's a documentation ... misunderstanding on my part?  Because I get different values, and they go up to 256.

**Comment by SmallJoker** [comment]
This possibly could help with some understanding: http://www.codeconquest.com/tutorials/binary/
The documented bits "numbers" from 0 to/including 8 are positions of each bit, in this case, of an unsigned 32-bit integer. Here's how they sum up to the final decimal value:
```Lua
  bit0 * 2^0 -- Least significant bit (1 or 0)
+ bit1 * 2^1 -- 0b10 (2) or 0x00 (0)
+ bit2 * 2^2 -- 0b10 (4) or 0x00 (0)
+ bit3 * 2^3 -- 0b10 (8) or 0x00 (0)
....
= final number, something between (including) 0 and 511.
```
