### ISSUE TITLE
Add more useful server commands (discuss)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6960]
##### Issue type
 - Feature request

##### Summary
I propose to add some simple (!) server commands which might be useful in daily server use.

This issue I want to do in two stages:

1) Discuss which commands we need/want
2) Discuss how these commands should work (includes exact specification and privileges)
3) Implement them

Suggested commands should be simple, that's why I want to group them together.

##### World
* **`setnode`: Set node at a position, destroying metadata**
* `swapnode`: Set node at a position, preserving metadata
* `fill`: Set an entire 3D area with the same node
* **`schematic`: Spawn schematic or list available schematics**

##### Player
* ~~**`clear`: Clear someone's inventory**~~
* **`kill`: Kill a player (needs privilege, so it's not just `killme` from MTG)**
* `hp`: Get or set player HP
* `breath`: Get or set player breath
* `attribute`: Get or set player attribute (`player:set_attribute`)
* Get or set player physics (speed, jump height, sneak, …)
* `sky`: Get or set sky
* `clouds`: Get or set clouds

##### Global
* `sound`: Play a sound
* `particle`: Spawn a particle

##### Server
* `info`: Get advanced server info (things like world path or game time)

##### Chat
* `say`: Say something in chat (command form)

##### Info
* Remove player list from `status`, add `list` command for this instead

#### Final remarks

This long list was mostly just brainstorming. Agree with my list? Which commands to be scrapped? Do yyou have other ideas?
I'm willing to donate some of my time to implement some of the commands. But first I want to know how much you agree.

**Comment by SmallJoker** [comment]
##### World
*`setnode`: Horribly inefficient and single nodes have no big use. There's creative and `give` for restricted nodes.
* `swapnode`: Possibly only helpful for mesecons' command block
* `fill`: That's what worldedit already offers with many, many more features
* `schematic`: Independent and no big varieties in the parameters. Sounds good.

##### Player
* `clear`: Already implemented with `clearinv`
* `kill`: Move `killme` from MTG into builtin, sound good.
* `hp`: Easy to implement but is ever anyone going to use that instead of giving them food?
* `breath`: Changes too quickly to be helpful as a command
* `attribute`: May conflict with mods and allow some dirty hacks or a crash
* Get or set player physics: May conflict with mods, but should be ok for a vanilla server
* `sky`: Temporary effect only, which makes this command not really helpful
* `clouds`: Same. Would need further `map_meta.txt` settings to make it helpful

##### Global
* `sound`: Earphone users will soon die but the idea _sounds good_. (haha, pun.)
* `particle`: Too specific. Maybe a simple particlespawner but they take too many arguments to pass in a chat command

##### Info
* `info`, player`list` Alias is fine but splitting these few lines is not worth it.
* `say`: Useless. Why not just say it directly then?

**Comment by Wuzzy2** [comment]
I suggested `setnode` and `fill` to allow privileged players to repair the map without mods. WorldEdit is pretty heavyweight. I think `setnode` is actually the most important command in my list.
Remember some nodes are not diggable or even pointable, so placing stuff does not always work. Let's say you accidentally placed a non-diggable, non-pointable node. It's impossible to repair this without mods, which is bad and annoying.
So I think `setnode` is incredibly important. `fill` is the logical and simplest possible extension of `setnode`. As a server operator, you frequently need to remove certain areas. It will be very useful. I don't intend to add anything fancier than `fill`, however. WorldEdit can still be used for the uber-fancy stuff.
`setnode` will also finally allow you to place the first node in a `singlenode` world without mods! Because it's impossible to place a node in mid-air.
`setnode` is not inefficient at all as long you really just set one node.

* `swapnode`: This is less important and I probably agree to scrap this idea

* `kill`/`killme`: I don't want to add a `killme` command. `killme` requires no privileges and affects gameplay, so it's a subgame decision. But `kill` would need a privilege and is the generalized form. In fact, I don't want to change MTG at all here.

* “Already implemented in mod XYZ”: That's not a reason to reject it in the core.

* `hp`: Food might not insta-heal you

* `breath`, `attribute`, `sky`, `clouds`: Yeah, these commands are pretty esoteric. I agree, the problem is they're rather volatile as mods can change this stuff at any time

* sound: I didn't consider the potential abuse of sound spam. So this needs a privilege. But it's an unimportant command
* particle: Yeah, the high parameter count is a potential killer. I could cut down the parameters. Particlespawner sounds also interesting.

* `say`: For completeness' sake and for command blocks. Also allows you to say something with a leading slash or period. xD

**Comment by Wuzzy2** [comment]
Oops! You're right, `clearinv` already exists. Sorry!

Now I give more details for the commands that “survived” so far:

New privileges:

* `world`: Allows you to make direct changes to the world
* `player`: Allows you to change player attributes

Also, for cleanup:
* Change the required privilege for `spawnentity` to `world` (currently: `give` and `interact`, which is a bit weird)
* Change the required privilege for `clearinv` to `player` (currently, `server` is required, which is obviously too overkill)

Syntax definitions:

* `setnode <x> <y> <z> <nodenname> [param2]`. Set node at xyz with `nodename` and optional `param2` Needs `world` priv
* `fill <x1> <y1> <z1> <x2> <y2> <z2> <nodename> [param2]`. Set area enclosed by the coordinates to `nodename` and optional `param2`. Needs `world` priv. If the chosen area is extremely large, you also need the `server` privilege
* `kill [player]`: Kill `player`. If `player` is omitted, kill yourself. Requires `player` priv (even if you want to kill yourself)
* `hp <player> [hp]`: Set HP of `player` to `hp` or display HP if `hp` is omitted. 1 HP = 0.5 “hearts”. Requires `player` priv
* `say <text>`. Say `text` in chat. Requires `shout` priv

**Comment by red-001** [comment]
`say` seems completely useless

**Comment by Wuzzy2** [comment]
After wiping out all the “useless” commands, which commands survive in your opinion?

**Comment by paramat** [comment]
To be clear, the ones you are still suggesting are:
setnode
fill
kill
hp
say
?

**Comment by paramat** [comment]
> I suggested setnode and fill to allow privileged players to repair the map without mods. WorldEdit is pretty heavyweight.

They can use simple mods to do fills or place schematics, however 'set node' may be useful enough for a command.

> “Already implemented in mod XYZ”: That's not a reason to reject it in the core.

It is if it is not very useful and fundamental.

Set HP includes 'kill'.
Generally new commands should be minimised to those that are extremely useful and fundamental, many of these can and should be done using mods.
Server admin input is needed for this issue.

**Comment by sorcerykid** [comment]
As a server op, I don't find the limited set of builtin commands to be a major issue. Dare I say, I sometimes feel there are too many builtin commands, as some of them could be better implemented as mods. If anything, I would like more tools for database maintenance (like purging large sets of mapblocks or changing all nodes in world without the use of an LBM). But unfortunately, something like that would probably have to be a separate utility since it requires direct database access.

**Comment by Wuzzy2** [comment]
@sorcerykid: Good having your input there! But in this isssue I am focussing on **simple** commands. Major database changes are not simple. :P

For serious database operations, external tools might indeed be better. It feels so wrong that you have to do serious data base operations like `clearobjects` at runtime (maybe that's why it's so slow?).
Feel free to open a new issue for this.

Please do not take away commands from builtin! I dislke the ideology that the engine should have almost no features. I hate it when you are forced to install mods for core functionality.

About “too many commands”: This can be fixed by improving the formatting of `help all` (e.g. grouping commands by category or whatever).

**Comment by paramat** [comment]
Actually, a simple cuboid fill may actually be useful enough to be a new built in command.
@tenplus1 @Ezhh @VanessaE

**Comment by sorcerykid** [comment]
The cuboid fill was one of the commands proposed for builtin.

> fill: Set an entire 3D area with the same node

I find Worldedit is best suited for operations of this sort. It's much easier to manipulate nodes visually than with only a command. I suspect that most server operators, including those tagged above, already have Worldedit installed. Maybe it would be worth actually incorporating Worledit (or at least a subset of it) into the engine. Perhaps sfan5 should chime in about the possibility of making that happen.

**Comment by Ezhh** [comment]
I'd be in favour of keeping worldedit type operations within worldedit and not adding them to builtin unless there are some really strong arguments for it.

I wouldn't mind seeing a kill command. (But how should it work when health is not enabled?)

**Comment by Wuzzy2** [comment]
If https://github.com/minetest/minetest/pull/6964 gets merged in or is rejected successfully, I will start to work on the following commands:

* `setnode`
* `fill`
* `kill`
* `schematic`
* `hp`

I already explained in great detail why `setnode` and `fill` and I stick to this opinion.

I'm currently sitting on the fence about `breath`. I recently had a situation where this command would have been useful for testing something related to death more quickly.

I drop the following suggestions:
* `say`
* `sky`
* `clouds`
* `clear` (redundant… XD)

I keep the other suggestions as “maybe”.

**Comment by paramat** [comment]
* `setnode`
* `fill`
* `kill`
* `schematic`
* `hp`

Best get more server admin input on these before working on this.

**Comment by Ezhh** [comment]
kill... yes
hp... indifferent, but don't feel much need for it.
The others... leave WE things to WE.

**Comment by Wuzzy2** [comment]
:O How about you first adress my arguments for `setnode` and `fill` before you oppose them?
Just because those *can* be done in a mod is no reason to not have them in builtin. I'm not going to make a full WorldEdit replacement, just a few *extremely* simple commands.

Justification for `schematic`:
This or a similar command has been re-invented over and over again in mods. Even in one of my mods! This is seriously annoying. Better to have one standard implementation than to re-invent the wheel.

**Comment by paramat** [comment]
Duplicated code in mods is not a problem (it's expected and encouraged) and not a justification on it's own.
Wuzzy2 are you a server owner? Just wondering.

**Comment by Ezhh** [comment]
In short, these proposed commands (speaking of just the WE type commands) by themselves simply aren't enough to meet my needs - I would still need WE, and this would put me in the situation of having such node manipulation commands coming from multiple sources. To me, that's messy. WE on the other hand definitely has a whole bunch of utility not every player/server will need, so it seems a poor choice to add the whole of WE to builtin.

**Comment by Wuzzy2** [comment]
I'm a player, mod developer and subgame developer, but don't operate any severs. But I use commands frequently. You obviously never had problems with a non-pointable non-diggable node which you placed accidentally. xD Otherwise you would know how annoying these can be. I was forced to install full blow WorldEdit just to get rid of a single node.

Well, obviously WorldEdit needs to adapt to the new builtin commands afterwards to avoid duplication. But I don't think `setnode` is a real problem, this can be just removed from WorldEdit. Note I never proposed to add the whole WorldEdit into builtin as WorldEdit adds a ton of commands.

We could take in WorldEdit devs to this discussion if you really want to.

@paramat: It's pointless to re-implement a place schematic command over and over again. You can only just use the same feature as `minetest.place_schematic` anyway, so there's absolutely no benefit in having this scattered in various mods.
Also, since when is redundancy a good thing?: O.

**Comment by jastevenson303** [comment]
If you add the kill command you can remove the obnoxiously named 'killme'
mod from MTG.

**Comment by Ezhh** [comment]
Having a mod for a killme command did always seem odd to me.

**Comment by sfan5** [comment]
> Maybe it would be worth actually incorporating Worledit (or at least a subset of it) into the engine. Perhaps sfan5 should chime in about the possibility of making that happen.

No it's way too heavy for that.
Since commands are also heavily integrated inside WorldEdit (`//y` confirm, selection manipulation, scriptability), integrating a subset into builtin would not work either.

> Well, obviously WorldEdit needs to adapt to the new builtin commands afterwards to avoid duplication. But I don't think `setnode` is a real problem, this can be just removed from WorldEdit.

I don't know if you have ever used WorldEdit, but `//set` is much more than "here's two coordinates, go set all the nodes to `default:glass`".
It will not be removed from WorldEdit even if a `/setnode` command gets added to builtin.

**Comment by sorcerykid** [comment]
It seems there is little to no agreement about what additional chat commands are needed. And implementing a subset of Worldedit chat commands is apparently a no-go as well.

I maintain that we really don't need a patchwork of new chat commands for builtin. I'm of the school of thought that builtin should provide only the most basic functionality (primitives, if you will), whereas subgames can extend on that functionality. When builtin becomes too specialized, we end up with oddities like falling.lua being part of core, when it would be better suited as a mod.

If a server operator needs access to more chat commands, then perhaps they should be consolidated within a "chat_commands" mod. That to me is the best way to go.

**Comment by VanessaE** [comment]
As a server owner, this is a flat-out non-starter.  These commands do not belong in Minetest.  Worldedit is WAY too entrenched by now to attempt what amounts to a partial replacement for it.

We've been down this road a few times already, and it always results in people wanting "the rest" of whatever mod the features came from, to be added....which leads to maybe a few more features, but always leaving out *just* enough that the original mod still has to be kept in-use, in a reduced form.

IMHO, ether add the whole of Worldedit (not necessarily a good idea), or do nothing and close this issue.

**Comment by Wuzzy2** [comment]
### `setnode` and `fill`

You're all missing the point of this: Convenience. Also, you seem to think I indend to replace WorldEdit. I don't. I intend to add **extremely** basic maintenance commands. In fact, I did not even think about WorldEdit when I wrote the list.

Let's compare some simple use cases:

Let's say non-pointable undestructible node appeared somewhere and you need to get rid of it. I had this situation a LOT in development. Please don't ignore this!

Now what could you do if this happens to you? Well, you COULD use a `setnode`. Then, all you to do is `/grantme all` and then `/setnode <params>`. It doesn't get simpler than that. Right?

But I get it. We don't do anything. Because it's so much simpler to do …

1) Search the forums for “how do I fix the map”, ask around
2) Eventually find a mod like WorldEdit
3) Download it
4) Install it
5) Quit the world
6) Enable the mod
7) Use `/help` to go through TONS of commands
8) Grant yourself `worldedit`
9) `//pos1`, `//pos2` `set <node name>`

See? So simple! :P

Sure, the installation and help steps can be dropped at the second time, but there are still too many steps left which you have to repeat for every world. I find the “quit the world and enable WorldEdit because you misplaced a block” to be a major inconvenience.
Of course WorldEdit works and I'm not against it. I've using it myself. Just not for every single world at once. The idea of the commands is to fix world hiccups, NOT for creativity.
Seriously, you can't possibly get more primitive than `setnode`, @sorcerykid.

I also proposed `fill` because this is easily one of the most used commands. It's the same argument as for `setnode`, really. In case a large area got borked.

Another minor use case is `singlenode`. Currently, you start in `singlenode` but it's **impossible** to place your first node. `singlenode` is completely useless with stock Minetest. It would be nice if you at least could start your first node without jumping through hoops.

Of course, this is not a replacement of WorldEdit. It is not meant to be. This is NOT meant for serious world editing, just some quick fixes and adjustments. If you feel the set of commands is too small, you're missing the point. Please stop using the slippery slope argument. We simply will NOT go ahead add replace every single WorldEdit command. That's never been the goal.

I picked `setnode` and `fill` precisely because these are the simplest imaginable commands and IMO the most frequently used ones. I can't stress enough how often I have needed these. On the other hand, I rarely need commands like `cylinder` so I definnitely do NOT propose to add it or even more stuff like this. And I defiitely do NOT want to integrate all of WorldEdit.
So you can ignore my own use case all you want but it doesn't change the fact that it exists.
Also, @paramat, I don't think only server operators should be allowed to have a say in this. They are not the only users, you know?

By the way:

> I don't know if you have ever used WorldEdit, but //set is much more than "here's two coordinates, go set all the nodes to default:glass".
> It will not be removed from WorldEdit even if a /setnode command gets added to builtin.

Makes sense to me.

### `schematic`

This I don't get at all. What's your case against `schematic`, exactly? If this is added in `builtin`, all that mods need to do is to remove duplicates. There is no net loss in functionality, nor will there be any conflict. Mods are basically just a wrapper around `minetest.place_schematic` anyway, so any supposed “variety” is mostly just an illusion.

### `kill` and `hp`

It seems most people are actually OK about this, or at least neutral.
I agree that the `killme` mod in MTG is weird, but this is off-topic.

**Comment by Ezhh** [comment]
> Let's say non-pointable undestructible node appeared somewhere and you need to get rid of it. I had this situation a LOT in development. Please don't ignore this!

In development means not a normal play situation by any extent. And yes, I've been in this situation when developing a mod/subgame. My response wasn't that builtin needs more commands, or even that I needed to spend ages installing WE. When I'm developing something, I test on maps that don't matter. Something didn't work and messed up where I am? Okay, /teleport < random coordinate > and I have some okay map to test on again. If the map itself is important enough to fix such things on, then it's almost certainly important enough that you shouldn't be testing development features on it OR that you should spend five mins adding WE.

On the other hand, going ahead with this would be an annoyance. It's nice to have all these kinds of commands using the same // format and being located in one single mod.

**Comment by paramat** [comment]
> Justification for schematic:
This or a similar command has been re-invented over and over again in mods. Even in one of my mods! This is seriously annoying

Annoying for you maybe, don't let trivial stuff get to you. Duplication of code in mods is normal and expected, each of those mods needs the duplicated code because it is not in builtin.
Many mods having schematic-placing code is not a justification for addition to builtin. There are are many features that are duplicated in many mods, we can't add them all to builtin.

> It's pointless to re-implement a place schematic command over and over again. You can only just use the same feature as minetest.place_schematic anyway, so there's absolutely no benefit in having this scattered in various mods.

No, it's inevitable as explained above, adding new commands will be decided by how useful and fundamental they are, not by how they are (inevitably) duplicated in mods.
You're looking for justification in the wrong place.

The killme mod makes no sense to me in MTG, why did we add that? If it's so useful it should be in builtin, if less useful it should be a mod.

**Comment by paramat** [comment]
How about writing a simple mod that gives 'setnode' and 'fill' commands? It will be very popular. The complexity of WE is no valid argument here.

> Another minor use case is singlenode. Currently, you start in singlenode but it's impossible to place your first node. singlenode is completely useless with stock Minetest. It would be nice if you at least could start your first node without jumping through hoops.

This is a misunderstanding of singlenode, it is not for skyblock worlds or placing an initial node, it is for mods and games that create custom mapgens. It is intended to be useless without mods, that's why it was hidden until recently. If you want to place a single initial node for a skyblock world you use a mod to do that.

> I don't think only server operators should be allowed to have a say in this. They are not the only users, you know?

I never stated that, i was just pointing out that server owner input is needed here and wondering if you were one so i could judge the weight your opinion carries.

> This I don't get at all. What's your case against schematic, exactly? If this is added in builtin, all that mods need to do is to remove duplicates.

They don't 'need' to, they 'could' if they want, you seem excessively hung up on code duplication in mods, relax. The duplication is a minor issue, this will be decided on how fundamental the ability is. I don't see placing schematics as particularly fundamental, so best left to a mod.

My opinion is:
* `setnode` maybe
* `fill` not sure but probably no
* `kill` if it's that useful, should be in builtin not MTG
* `schematic` no, not particularly fundamental
* `hp` no, not particularly fundamental

**Comment by red-001** [comment]
+1 to the kill command as long as killing another player requires higher privileges than killing the issuer.

**Comment by Ferk** [comment]
I usually temporarily add a "test" mod inside a subgame when I'm toying with its code for the purpose of small things like this.

I agree it would be convenient to have some auxiliary tools where we would not need to be copying around/enabling any dev/test mod for every new world/subgame, but at the same time it feels like having that by default in the builtin engine might be the wrong place for that kind of "devtools" to be, particularly from the perspective of a server admin.

Also, often more advanced tools are needed, like formspecs to edit metadata values, or some type of "wand" item for selecting nodes more comfortably, etc. Those are too complex to add to builtin so the tools would end up being too simple for most dev purposes and too unnecessary for most non-dev purposes.

To me, what would be convenient enough would be having a way to enable a mod in a kind of permanent way.. as if it was part of builtin, so I could add my devtest mod in there and have it applied to every world I run without having to care about adding/removing it per subgame and/or per world.

> New privileges:
> *  world: Allows you to make direct changes to the world
> * player: Allows you to change player attributes
>
> Also, for cleanup:
> * Change the required privilege for spawnentity to world (currently: give and interact, which is a bit weird)
> * Change the required privilege for clearinv to player (currently, server is required, which is obviously too overkill)

These do look like good ideas to me, honestly. Minetest privileges are very messy and a more clearly defined privilege system is something that does belong to builtin, so it can pave the way for subgames and mods to follow.

**Comment by red-001** [comment]
@Ferk globally enabling mods is an interesting idea, with something like #6982 it should be pretty trivial to add.

**Comment by Wuzzy2** [comment]
#6992

**Comment by sorcerykid** [comment]
To use a kill command should require a "kill" privilege. This is how it works on my server (I have separate privileges for kill, jail, kick, etc.). The privilege "player" is vague and subject to misinterpretation. Also the ability to kill players is a highly specialized action. As a server operator, I would be uncomfortable granting anyone (even a moderator) a "player" privilege since there is no certainty about it's purpose from the name alone.

**Comment by rubenwardy** [comment]
PR merged
