### ISSUE TITLE
Suppress server list to help adoption in schools

### ISSUE THREAD

**Issue by twistedlizard** [minetest/minetest#6962]
##### Issue type
 - Feature request
 
##### Summary

 In a school environment, it's important that students cannot connect to online chat systems & get into conversations with persons unknown. It would ease minetest's adoption in schools, if in minetest.conf there could be a line something like:

suppress_server_list = TRUE

The default, in the absence of any such line, being false. If the parameter is set to true, no server list is displayed and the client only connects to whatever server is specified by maybe

server_address = ip_of_server_on_lan:port_number

or some suitable existing parameter.

**Comment by SmallJoker** [comment]
It's already possibly to restrict the server list. No need to add another setting that does the same.
`serverlist_url = 127.0.0.1`

https://github.com/minetest/minetest/blob/62c10e3d0855fa14fdc260da0b7cd748e53db13f/minetest.conf.example#L1043
