### ISSUE TITLE
F3 (toggle fog) does not affect the 'enable_fog' setting

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6969]
#### Issue Type
- Bug report

#### Summary
Ok so, as I was adding the enable fog setting to #6965 I noticed that pressing F3 did not change the setting "enable_fog" so i looked further into that and found that pressing F3 only hides and shows the fog regardless of the enable_fog setting. I suggest changing the text that pops up when F3 is pressed to this: "Fog Shown" and "Fog Hidden"

**Comment by paramat** [comment]
Seems reasonable, easy job you can do?

**Comment by ThomasMonroe314** [comment]
Sure

**Comment by paramat** [comment]
I can confirm what you found. Maybe instead F3 should actually be linked to the setting, it seems broken and unlike other settings.

**Comment by ThomasMonroe314** [comment]
so make F3 actually set the setting?

**Comment by paramat** [comment]
Yes, other keys toggle the corresponding setting, i don't know why this doesn't.
Let's see what other devs think.

**Comment by nerzhul** [comment]
please respect the new issue template...

**Comment by ThomasMonroe314** [comment]
@nerzhul ok, I will do that, but alot of that is unecessary for many issues

**Comment by paramat** [comment]
'Issue type' might be useful, the other template sections are irrelevant.

**Comment by paramat** [comment]
I changed the thread title. I think the text can remain the same and we link the key to the setting, should be fairly easy.
Currently if the setting 'enable_fog' is 'true', F3 toggles fog on and off, if the setting is 'false' F3 does nothing, fog is always disabled, this makes no sense and is inconsistent.

**Comment by ThomasMonroe314** [comment]
sounds good to me.

**Comment by yamanq** [comment]
This issue can be closed since it was fixed by https://github.com/minetest/minetest/commit/501f936b37046ab469844c5349054369de3e7fc6
Tested with Minetest 5.5.0-dev 6de8d77e1
