### ISSUE TITLE
HUD Fails since 4f688d5

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#6972]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-dev-4f688d5 <-- broken
and
0.5.0-dev-3a5959a <-- not broken
```

##### OS / Hardware

Operating system: Linux
CPU: AMD

GPU model:
OpenGL version:

##### Summary

HUD does not update the health (or anything) while playing, only after relogging

##### Steps to reproduce

Start a new world with minetest_game and inflict damage on player
Notice how the health bar doesn't change

**Comment by SmallJoker** [comment]
7d3295e
