### ISSUE TITLE
Enable the double-promotion warning when compiling with gcc

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#6974]
gcc offers a flag to warn when somebody does not use the f suffix for floating point constants:
```
       -Wdouble-promotion (C, C++, Objective-C and Objective-C++ only)
           Give a warning when a value of type "float" is implicitly promoted to "double".  CPUs with a 32-bit "single-precision" floating-point unit implement "float"
           in hardware, but emulate "double" in software.  On such a machine, doing computations using "double" values is much more expensive because of the overhead
           required for software emulation.

           It is easy to accidentally do computations with "double" because floating-point literals are implicitly of type "double".  For example, in:

                   float area(float radius)
                   {
                      return 3.14159 * radius * radius;
                   }

           the compiler performs the entire computation with "double" because the floating-point literal is a "double".
```
AfaIk, minetest developers often tell PR creators to add the f suffix for obvious reasons. This flag makes gcc omit a warning, so PR creators would likely fix it without being explicitly told by developers.

**Comment by HybridDog** [comment]
I've tried it, it shows lots of irrlicht warnings…

**Comment by paramat** [comment]
Wouldn't this be a problem though because MT code is full of floats that lack the 'f' suffix? We would need to add all 'f's first, big job.
However if that was done this would be good :+1:

**Comment by HybridDog** [comment]
The problem is that 'f' suffixes are missing in the included irrlicht header files and I don't know if it is possible to disable the warning for included files.
I've also tried the `-fsingle-precision-constant` ("Treat floating-point constants as single precision instead of implicitly converting them to double-precision constants.") gcc compiler flag, but it caused errors.

**Comment by HybridDog** [comment]
Minetest has a custom irrlicht now, so the f suffixes could be added there.

**Comment by sfan5** [comment]
Would that also warn for `0.0` or `1.0` which the compiler can and will losslessly convert to float (haven't tested)?
If so I think the amount of warnings would be too bothersome to enable it.

**Comment by HybridDog** [comment]
There's a big number of warnings which probably aren't helpful, for example a float to double conversion in `const f64 inv = 1.0f - d;`. Here's the gcc output: [gcc_warnings_irrlicht.txt](https://github.com/minetest/minetest/files/7148473/gcc_warnings_irrlicht.txt)
I think clang-tidy could be more suitable to detect unwanted float-to-double promotions, e.g. with the [performance-type-promotion-in-math-fn](https://clang.llvm.org/extra/clang-tidy/checks/performance-type-promotion-in-math-fn.html) option.
