### ISSUE TITLE
Check hash of client to prevent "hacked" clients

### ISSUE THREAD

**Issue by afshaan4** [minetest/minetest#6980]
##### Issue type

 - Feature request
 
##### Minetest version

``` 
Minetest 0.4.16 (Linux)

```

##### OS / Hardware

Operating system: Fedora 27
CPU: core i3 gen3

GPU model: 
OpenGL version:

##### Summary

Servers can check the hash of the client to see if it has been modified to allow them to "hack" the server.
I don't run a server and don't know if this would not work, but i think this might work to prevent the "hackers" from ruining a server

**Comment by ritschwumm** [comment]
if i hacked a client, i'd make it send a "good" hash to the server.

**Comment by afshaan4** [comment]
yeah i thought of that too, but is there no way to prevent that like, having the server hash the client passively instead of the client sending a response ?
