### ISSUE TITLE
Add callbacks for node creation and destruction

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6981]
##### Issue type
 - Feature request

##### Summary
Please add the following callback functions:

* `minetest.register_on_constructnode(function(pos))`: The inner function is called after a node is constructed at `pos`
* `minetest.register_on_destructnode(function(pos))`: The inner function is called before a node is destructed at `pos`
* `minetest.register_after_destructnode(function(pos, oldnode))`: The inner function is called after a is destructed at `pos` with `oldnode` as the former node table

In short, the three functions are equivalent to `on_construct`, `on_destruct` and `after_destruct` found in node definitions. Except they're general callbacks.

##### Relevance
Useful whenever you have a node which needs to “watch” other nodes and you want to receive an update instantly. Currently, this is not possible unless you constantly query the same node over and over again, which is not a clean solution, and also fails the requiremet of *instant* updates.

One example is the node detector from Mesecons. This node watches the node in front of it and changes state when a particular node appears. Currently, this is done by constant querying every second, which is rather slow.
Also this is useful for Mesecos (and similar modpacks) in general as the neighbor nodes often need to change state when a node is created. Currently, it only checks for placement and digging, but these are not the only ways a node can be added or destroyed, so there are holes in the detection which causes bugs.
Then I also want to implement the observer from Minecraft which is very similar to the node detector.

From an API design perspective, adding the proposed callbacks would be a nice generalization of `minetest.register_on_placenode` and `minetest.register_on_dignode`. These two callbacks are still useful, but they are too specialized sometimes, so adding the generalized versions of these makes sense.

**Comment by HybridDog** [comment]
> Currently, this is not possible unless you constantly query the same node over and over again

You can simply override minetest.add_node.

**Comment by paramat** [comment]
Stating your MT version is irrelevant for a feature request.

**Comment by Wuzzy2** [comment]
> You can simply override minetest.add_node, minetest.set_node and minetest.remove_node.

This approach seems a little … extreme. :grin:

**Comment by red-001** [comment]
I would prefer a single callback called before the update, something like 

```lua
minetest.watch_node(pos, function(pos, oldnode, newnode)
        if newnode == some_node then
               return true -- stop the update
        end
        return false
end)
```

**Comment by Wuzzy2** [comment]
Please explain your function, @red-001. I'm interested.

**Comment by HybridDog** [comment]
> This approach seems a little … extreme.

register_on_constructnode would do the same, also, with luajit, overriding set_node and add_node should have lower performance impact because of less core to lua switchings.

> I would prefer a single callback

Like this?
```lua
local my_pos = […]
local add_node = minetest.add_node
function minetest.add_node(pos, node)
	if not vector.equals(pos, my_pos) then
		return add_node(pos, node)
	end
	minetest.add_node = add_node
	[…]
	return minetest.add_node(pos, node)
end
	```

**Comment by paramat** [comment]
1 year bump. Any core dev support?

**Comment by sofar** [comment]
I can see use for it, but how do you handle unloaded blocks? e.g. someone attaches hundreds of callbacks across the map, and they are unloaded. Do we serialize them into the stored mapblock? what if they are re-emerged without the mod loaded? Or should they be entirely volatile?

**Comment by Wuzzy2** [comment]
What do you mean with “attach hundreds of callbacks across the map”? This doesn't make sense. Also, why hundreds?
They're callbacks and don't know about the position until you look at the `pos` argument.
The idea is that the `on_constructnode` callback is called when ANY node is constructed (like in `on_construct` for ANY position.

Basically like `minetest.register_on_punchnode`, which is the “generic” pendant to `on_punch` in the node definition.

**Comment by Wuzzy2** [comment]
> Do we serialize them into the stored mapblock?

No. They're callbacks. They are registered by the mod. They are supposed to be stored in one of the index tables in `minetest.registered_whatever`, not in the map.

> what if they are re-emerged without the mod loaded?

Nothing happens.

> Or should they be entirely volatile?

The callback is registered when the mod loads and fires whenever a node is constructed. If the mod is not loaded, nothing happens.

**Comment by kay27** [comment]
How to upvote the issue?
It's still so important for observer...
Also I think @HybridDog 's way isn't too bad if there's no sulution for about two years...

Could you please check is this Lua code correct for Minetest? (Or maybe give some appropriate example of better functions overriding?)

```
-- declare pointer to original function:
minetest_add_node_parent = minetest.add_node

-- override:
minetest.add_node = function(pos, node)
  -- call original function:
  minetest_add_node_parent(pos, node)
  -- now do what we need:
  print("override")
end
```

Thanks in advance.

**Comment by HybridDog** [comment]
> Could you please check is this Lua code correct for Minetest? (Or maybe give some appropriate example of better functions overriding?)

The code should be correct. (but `minetest_add_node_parent` should probably be declared `local`)

It may be required to override `minetest.set_node`, `minetest.add_node`, `minetest.bulk_set_node`, `minetest.swap_node` and `minetest.remove_node`.

#
I'm against the proposed functions because I think they can have a bad impact on performance. `minetest.set_node` is usually executed very often.

**Comment by kay27** [comment]
> I'm against the proposed functions because I think they can have a bad impact on performance. `minetest.set_node` is usually executed very often.

Okay, but ABM has some cons too!
If you'd take a look, you'd can compare observer implementations yourself:
1) [ABM way](https://git.minetest.land/Wuzzy/MineClone2/src/branch/master/mods/ITEMS/REDSTONE/mcl_observers/init.lua#L236) - once per second but smooth;
2) [Overriding way](https://git.minetest.land/kay27/MineClone2/src/branch/master/mods/CORE/mcl_init/init.lua#L132) - immediate firing but to be honest not very smooth.

Both are inoptimal.

For observer it would be nice to have some way to get a callback when these functions affect the nodes near the specific type of the node (observer, in this case). That would give real performance boost, in comparison to all of the implementations listed above.

**Comment by paramat** [comment]
Certainly these callbacks could not be allowed for bulk node handling and maybe some other situations where performance is critical (liquid flow?). Maybe only on 'set node' and 'remove node'.
Problem is, if you use one of these callbacks it makes all node adding/removal run the callback, even if it is unsuitable for many nodes, the affect on performance could be a problem. So i am not sure this would actually be practical for most usage.

Earlier i labelled this as supported, but sofar's comment was actually not particularly supportive. So, i will relabel this as needing core dev support stated, close in 1 month if none.

**Comment by kay27** [comment]
There should be the way, you don’t think so?
When we put an observer, if there was a way for it to add additional on_construct/on_destruct handlers to the node nearby, it would be okay too.
@paramat How would you resolve the issue as Senior Platform Architect?

**Comment by paramat** [comment]
> From an API design perspective, adding the proposed callbacks would be a nice generalization of minetest.register_on_placenode and minetest.register_on_dignode. These two callbacks are still useful, but they are too specialized sometimes, so adding the generalized versions of these makes sense.

But, those 2 APIs are not a problem because player placing and digging is not done extremely rapidly. General callbacks on construct and destruct are very different.

**Comment by paramat** [comment]
kay27,
I do not have the interest, time or energy to think about an alternative implementation.
> For observer it would be nice to have some way to get a callback when these functions affect the nodes near the specific type of the node (observer, in this case). That would give real performance boost, in comparison to all of the implementations listed above.

This issue will be kept open or closed based on what the issue author proposes.
So if you have an alternative proposal you could possibly open a new feature request issue for that.
