### ISSUE TITLE
Add node visual for entities (and falling nodes)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#6986]
##### Issue type
 - Feature request

##### Summary
I request a new visual for entitites to be added: `node`.
This visual makes the entity look like a given node. In another attribute the node name must be set. Ideally, `param2` is supported, too.

Then, this visual should be utilized by falling nodes, so that there's no restriction to drawtypes.

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/de2c40c8fc189eeeeba010a0aaa1d28aed588c68/builtin/game/item_entity.lua#L27

```diff
diff --git a/builtin/game/item_entity.lua b/builtin/game/item_entity.lua
index 06e6776..9016c09 100644
--- a/builtin/game/item_entity.lua
+++ b/builtin/game/item_entity.lua
@@ -51,18 +51,16 @@ core.register_entity(":__builtin:item", {
 
 		local max_count = stack:get_stack_max()
 		local count = math.min(stack:get_count(), max_count)
-		local size = 0.2 + 0.1 * (count / max_count) ^ (1 / 3)
-		local coll_height = size * 0.75
+		local size = 0.666
+		local coll = 0.5
 
 		self.object:set_properties({
 			is_visible = true,
 			visual = "wielditem",
 			textures = {itemname},
 			visual_size = {x = size, y = size},
-			collisionbox = {-size, -coll_height, -size,
-				size, coll_height, size},
-			selectionbox = {-size, -size, -size, size, size, size},
-			automatic_rotate = math.pi * 0.5 * 0.2 / size,
+			collisionbox = {-coll, -coll, -coll, coll, coll, coll},
+			selectionbox = {-coll, -coll, -coll, coll, coll, coll},
 			wield_item = self.itemstring,
 		})
 ```
![screenshot_20180129_185729](https://user-images.githubusercontent.com/1497498/35525987-6ab5bf1a-0526-11e8-9e44-f60aea71a18f.png)

**Comment by Wuzzy2** [comment]
@SmallJoker: Why did you close this and how does above code fix falling nodes (which doesn't even seem to be committed!).

Using `wielditem` does not work if `wield_image` of the node is set. Then the falling node will just show a flat object instead of the node (like for snow from Minetest Game).

**Comment by SmallJoker** [comment]
@Wuzzy2 Your main post did not describe anything of the limitations so I assumed you didn't know about `wielditem`. Of course, regarding the `wield_image` parameter it's a reasonable request.

**Comment by stujones11** [comment]
This would be useful for my 'meshnode' mod, though I would also need the shading to be correct for the `param2` face direction, that is currently a problem with attachment rotated `wielditem` meshes :)

**Comment by paramat** [comment]
"wielditem" visual is poorly documented and few realise it can be used to appear as a node by entering the nodename in 'textures'. I only discovered this from the cute cubic mobs mod.

**Comment by stujones11** [comment]
I agree it is poorly documented like may other features, however, there is an obvious example of this in the `__builtin:item` entity :)

**Comment by stujones11** [comment]
I've had a quick look at this and the code you would need to override is here
https://github.com/minetest/minetest/blob/49b65a5593c981a4ebc587538923e267a22c2437/src/wieldmesh.cpp#L356-364
Adding rotation should also be possible with `rotateMeshBy6dFacedir` but would require a new object property, eg `facedir` seems like an obvious choice.

I might have a go at this sometime, however, it would currently conflict with an existing PR I have :)
