### ISSUE TITLE
Lower limit needed for client FOV to avoid loading distant world using zoom-like values

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#6991]
- Bug report

Commit https://github.com/minetest/minetest/commit/ae9b1aa1774aedca8f452514d9462c281e36773a made zoom load distant world according to the zoomFOV value.

I am concerned that a limit was not applied to normal FOV (which is client controlled) to avoid it being small enough to be considered a zoom.
ZoomFOV is now controlled by the server, the client should not be able to load distant world by choosing a low normal FOV.
~~The heuristic cutoff for horizontal FOV being treated as zoom is 1.775 radians = 51 deg.
Aspect ratio 14/10 is assumed however we should also cope with aspect ratio 1:1 (the squarest ratio likely used) so the lower limit for normal vertical FOV should perhaps be 51 degrees.~~

However advanced settings allows a normal vertical FOV of as low as 30 degrees, that can be fixed easily, however we have to limit what can be set in .conf too and i can't find any limiting of that anywhere.
The heuristic cutoff value should perhaps be rebalanced between normal and zoom FOVs.
@lhofhansl any thoughts?

src/clientiface.cpp
```
 	float camera_fov = sao->getFov();
 
	const s16 full_d_max = std::min(adjustDist(m_max_send_distance, camera_fov), wanted_range);
```

src/util/numeric.cpp
```
s16 adjustDist(s16 dist, float zoom_fov)
{
	// 1.775 ~= 72 * PI / 180 * 1.4, the default on the client
	const float default_fov = 1.775f;
	// heuristic cut-off for zooming
	if (zoom_fov > default_fov / 2.0f)
		return dist;

	// new_dist = dist * ((1 - cos(FOV / 2)) / (1-cos(zoomFOV /2))) ^ (1/3)
	return round(dist * cbrt((1.0f - cos(default_fov / 2.0f)) /
		(1.0f - cos(zoom_fov / 2.0f))));
}
```

**Comment by ThomasMonroe314** [comment]
I don't think this is _technically_ a 'bug', but rather something that was not thought of until you start re-looking at it. though I don't know what esle to call it XD

**Comment by lhofhansl** [comment]
Hmm... Zoom is nothing special, just a small FOV. The code above distinguishes this by a heuristic.
If zoom is server controlled now, the server should be able to tell whether we in "zoom mode" and control the FOV that way.

**Comment by ThomasMonroe314** [comment]
so the zoomFOV is checked by being, at most, half of normal FOV?

**Comment by paramat** [comment]
I'll see what i can do.

**Comment by paramat** [comment]
Confirmed a clientside normal FOV of 30 degrees (the allowed minimum) loads distant world.

**Comment by paramat** [comment]
#7234 merged.
