### ISSUE TITLE
Skybox Drawtype or Effect

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#6996]
##### Issue type

 - Feature request

##### Summary
Right now we don't have a way to create a nice portal or gateway effect. If there was a way to use an arbitrary skybox (like IGNORE, but with custom textures) either as a drawtype, or as a sort of texture mapping (texture modifiers are done client side anyways, so we could theoretically add a `[skybox`` modifier that would allow any surface to use and combine the skybox effect). This would be useful for both portal type effects, as well as fake reflection maps if one was clever about it (think like a reflective floor where the skybox texture mimics a mirror effect of the room above it).

Now, if a modifier or otherwise texturable/mappable effect is completely absurd, perhaps just a drawtype wouldn't be? (Both nodes an entities would be awesome, but just nodes would make a would be extremely helpful)

**Comment by rubenwardy** [comment]
You can make a skybox using an inverted textured cube, but I guess that's not what you mean. Do you want a flat surface which looks like you're looking through a window at the sky box?

**Comment by Ferk** [comment]
Something that would be really interesting is having nodes that act as actual "portals". As in being able to render a viewport from a different location/angle when looking through the node and allow players to pass through it (much like Valve's Portal game).
If the destination viewpoint could be attached to an entity with an offset this would allow for a voxel-area entities.
Also it would allow for things like mirrors and surveillance cameras.

**Comment by benrob0329** [comment]
>Do you want a flat surface which looks like you're looking through a window at the sky box

Basically, yes. But being able to set it to any skybox, and any surface would make it much more useful.

@Ferk yes, but that will be much more intensive than just a skybox.

**Comment by ThomasMonroe314** [comment]
but the skybox would be a step towards that though right?

**Comment by paramat** [comment]
Nice idea, but i don't see a great demand for it (we don't have VAEs or other dimensions yet, and this is essentially to add a feature from a Portal type game) and it would be quite complex to implement.

**Comment by raymoo** [comment]
@paramat This issue is not to add a feature from Portal, that was the suggestion of @Ferk.

This effect wouldn't be harder to implement than any other shader - you would just get the color of some fragment by sampling the skybox based on the direction of the player to the fragment.

**Comment by paramat** [comment]
I wasn't referring to Ferk's suggestion, i meant this is for a portal type visual effect and i'm unsure of need, it's quite specialist.

**Comment by benrob0329** [comment]
Use cases:

* MineClone 2's end portal
* A holodeck effect
* Fake reflections
* Portals
* Fake Windows
* Really anything where you need to change a player's perspective of where something leads, or need to have perspective-based mapping

**Comment by jastevenson303** [comment]
You call it a Portal effect in reference to the game but I never played
it.  I know this effect from Doom and Quake source ports.

**Comment by paramat** [comment]
1 year bump. Any core dev support?
