### ISSUE TITLE
New Postprocessing Framework

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#6997]
##### Issue type
 - Feature request

##### Summary
While searching around for post-processing tutorials for Irrlicht I found [this](https://github.com/osense/irrPP.git) framework on Github. I was wondering if it would be of any use to Minetest. I am willing to see what it can do and maybe it will come in handy for advanced shader stuff that users might want to play around with.

**Comment by sfan5** [comment]
#3623 used irrPP, see also [here](https://github.com/minetest/minetest/issues/5446#issuecomment-289094431)

**Comment by ThomasMonroe314** [comment]
irrPP is no longer compatible and hasn't been updated for a long time.
