### ISSUE TITLE
Error message with disabled internet connection

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7003]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"

```

##### OS / Hardware

Operating system: linux
CPU: intel

##### Summary
When I play minetest offline, I get this error message:
```
2018-02-02 21:19:30: ERROR[AsyncWorker-0]: servers.minetest.net/list?proto_version_min=36&proto_version_max=36 not found (Couldn't resolve host name) (response code 0)
```
However, not being able to load the serverlist when you don't have a connection is not an error.

##### Steps to reproduce

disable internet connection, then start minetest and switch to the join game tab

**Comment by mtango688** [comment]
It also leaves the "Loading..." message up in the UI. Seems like it could use a fallback routine.

**Comment by SmallJoker** [comment]
Technically it's correct. Browsers also show a page which says that the website couldn't be loaded. However, the "Loading..." should be replaced by something like "Cannot get the server list. Check your connection and try again."

**Comment by HybridDog** [comment]
I think an error log message is wrong. Instead the message should be shown in the serverlist formspec, not the debug output.
