### ISSUE TITLE
Typing on the pause menu

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#7010]
##### Issue type
Bug report

##### Minetest version
0.5.0-dev

##### OS / Hardware
Confirmed reproducible on both Windows and Linux.

##### Summary
This:
![mt_stupidpausemenu](https://user-images.githubusercontent.com/7035183/35774094-b0732516-095d-11e8-8eaa-3212a5be822c.gif)
(Thankfully changes are of course lost after you close the menu... but it's still wrong.)

##### Steps to reproduce
Just go to the pause menu. Click. Type things.

**Comment by mtango688** [comment]
You can also mouse click and edit the Game info text. I never noticed that.

**Comment by Ezhh** [comment]
So this underlying issue is likely wider than the pause menu. This happens on the text on the left of the Texture Packs tab in the main menu:
![textdel](https://user-images.githubusercontent.com/7035183/35777426-98356e3a-09a5-11e8-883d-752c85674347.png)

So the issue is with textarea in formspecs. (The Texture Packs tab didn't previously use a textarea here) and not sure right now if the pause menu changed.

**Comment by 4w** [comment]
Can’t confirm in 0.4.16 on Linux. So likely something that was introduced in the 0.5.0 development version.

**Comment by Fixer-007** [comment]
Can't confirm in 0.4.17 on windows, bug introduced in 0.5.0

**Comment by red-001** [comment]
#6787 should fix this

**Comment by SmallJoker** [comment]
@red-001 
> should fix this

That PR does fix it, that's what I especially tested after the report about this bug on IRC.

**Comment by red-001** [comment]
@SmallJoker ok I wasn't sure if you ended up adding a fix to the PR.

**Comment by Ezhh** [comment]
Seems no one remembered to close this.

Tested and confirmed it's now fixed. :)
