### ISSUE TITLE
Remove the startup ASCII art text or allow to disable it via configuration option or by loglevel

### ISSUE THREAD

**Issue by 4w** [minetest/minetest#7014]
##### Issue type
 - Feature request
 
##### Minetest version
```
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
```

##### Summary
Currently when starting Minetest an ASCII art text writing “minetest” is rendered. Since it’s loglevel is `action` this is written between all the other actions that are more important than a random ASCII art text.

![2018-02-04-140418_646x218_scrot](https://user-images.githubusercontent.com/30605057/35777795-4d949ef0-09b4-11e8-8c69-f0eaf5c5e10a.png)

I suggest either removing this without replacement because it has absolutely no purpose (on command line the input prompt is a good separator and in the `debug.txt` there already is a separator) or giving it an own log level below the `action` log level so it is only shown if the loglevel is below `action` (maybe introduce `decorations` and place it above `verbose`).

Optionally create a configuration option to disable the ASCII art.

**Comment by sfan5** [comment]
![image](https://user-images.githubusercontent.com/1042418/35777844-17dfdb20-09b5-11e8-92ba-27202bd5aebb.png)

**Comment by ThomasMonroe314** [comment]
I agree with sfan, many other programs have some sort of ASCII art logo when they start from the comand line.

**Comment by 4w** [comment]
> https://www.google.de/search?q="eva+johanna+nürnberg"

It clutters the command line output and the log file and thus making it harder to debug by analyzing the logs. The logging functionality should not be used for fun.

**Comment by 4w** [comment]
> I don't see how this is much of a problem, maybe an "annoyance" at most.

It clutters the command line output and the log file making it harder do debug by analyzing the command line output or the log file. The logging functionality should not be used for fun.

**Comment by ThomasMonroe314** [comment]
maybe some sort of --nologo option perhaps?

**Comment by 4w** [comment]
> maybe some sort of --nologo option perhaps?

Better hide by default and show if `--logo` is provided or a configuration option is set. Or even a compiling option could be sufficient.

**Comment by rubenwardy** [comment]
I find this useful when finding out where the logs for a game starts. It could be removed from the logs. Then again, cluttering the log output isn't really an argument when it's 6 lines every 10 days or whatever

**Comment by stujones11** [comment]
> Since it’s loglevel is action this is written between all the other actions that are more important

This is a valid point, however, IMO the fix would be make sure the ascii art get printed first. I also find this to be a good visual reference when scanning through logs.

**Comment by SmallJoker** [comment]
:-1: The ASCII logo looks nice and must be kept. If your server restarts so often that the text becomes an issue you'll probably have more important issues.

**Comment by 4w** [comment]
> I also find this to be a good visual reference when scanning through logs.

There is a …

    -------------
      Separator
    -------------

… surrounded by newlines as visual reference. in the logs.

At least there the irrelevant ASCII art should not be shown. If it’s shown at startup outside any logging functionality – okay. But as of now the logging functionality gets misused for futility.

**Comment by paramat** [comment]
It looks good and is part of MT culture, it's also a very large and clear marker in logs when scrolling through them :-1:

**Comment by stujones11** [comment]
I am fine with this decision but just how hard would it be to make sure those actions were logged first? IMO it does look a bit sloppy, otherwise I am all in favour of keeping the ascii logo.

**Comment by 4w** [comment]
> It looks good

Actually no.

> it's also a very large and clear marker in logs when scrolling through them

There already is the separator. The ASCII art text is just waste of space and resources.

> I am fine with this decision but just how hard would it be to make sure those actions were logged first?

Why have it as log after all? It is just useless and distracting.

**Comment by sfan5** [comment]
> Just people stating their opinion and my initial issue having more upvotes than downvotes.

The up-/downvotes don't accurately portray approval, but the rest is correct.
Reopening this issue for discussion purposes.

**Comment by red-001** [comment]
If this seriously is such a big deal to you fix it and make a pull request, this discussion is frankly just a waste of everyone's time.

**Comment by rubenwardy** [comment]
> By who? You? I don't see one formal disapproval in the whole discussion. Just people stating their opinion and my initial issue having more upvotes than downvotes.

There are two disapprovals above - from krock and paramat.

Also, :-1:

**Comment by 4w** [comment]
> There are two disapprovals above - from krock and paramat.

Scolling up and down, I don't see a user called "krock". And paramat - conceited as always - just closed the issue due to personally not liking it.

**Comment by ThomasMonroe314** [comment]
Krock is SmallJoker

**Comment by paramat** [comment]
> I don't see one formal disapproval in the whole discussion.

There were 2 'yellow thumbs-down in the comment body' (that's an official disapproval) by Smalljoker (Krock) and myself, and sfan5 and rubenwardy were not keen, i added that up to 3 disapprovals which is enough for a close.
> my initial issue having more upvotes than downvotes.

The initial comment votes by non-core devs do not decide a decision, although we take them into account. Often devs will not express themselves in those votes, for example i never use those votes, so the votes are innaccurate.
> Do you really think a PR paramat disagrees with will ever be accepted

Yes because alone i have zero power according to MT rules, it takes around 3 core dev disapprovals to stop something.

Only closed quickly to work fast and efficiently, discussion can continue if closed. I can't see reason to keep it open with 3 official disapprovals.

**Comment by 4w** [comment]
> But we could discuss whether to reposition it,

And all the other ideas (command line switch, configuration option, own loglevel like `decorations` or something, compile parameter, etc.) are not taken into consideration?

But if it’s only about repositioning it. Then yes, positioning it outside the logging function at start of the client (first output on command line) would be best.

**Comment by benrob0329** [comment]
I think a ``--nologo`` would be good for people who want to have a cleaner log, can be added to an sh file that is called to start the server (as most servers use other command line arguments as well). Combined with a ``logo = false`` in minetest.conf I think everyone here would be happy :+1:

**Comment by red-001** [comment]
>Then don't participate?

still clutters the issue tracker, kinda like how you complain about this text messing up your logs.

**Comment by minduser00** [comment]
Maybe the pull request #7030 can be useful to you.
I try to keep it as simple as possible.

**Comment by paramat** [comment]
A setting is the wrong solution for situations like this, it's not worth the extra code and another setting, devs will be unhappy, the suggestion has 4 dev disapprovals.
Maybe we can do something simple to improve where or when it is shown.

**Comment by 4w** [comment]
It’s just another advanced setting. Nothing is bad with configurability and sane defaults.

Can’t or want no-one see that misusing a logging function for a startup ASCII art is wrong? You guys are developers … Doesn’t mean clean code and usage of functions anything to you?

For crying out loud … why the hell does this even has to be an issue? :scream:

**Comment by Ekdohibs** [comment]
> For crying out loud … why the hell does this even has to be an issue? 😱

I totally agree with you: why does it have to be an issue that clearly has absolutely no interest? The ASCII art doesn't hurt anybody, and adding a configuration option for it would clearly be software bloat. If it bothers you so much, just remove the lines printing it before compiling.

**Comment by minduser00** [comment]
4w is an open source project, simply dowload de sources and comment out this code from the file src/server.cpp:
		actionstream
		<<"        .__               __                   __   "<<std::endl
		<<"  _____ |__| ____   _____/  |_  ____   _______/  |_ "<<std::endl
		<<" /     \\|  |/    \\_/ __ \\   __\\/ __ \\ /  ___/\\   __\\"<<std::endl
		<<"|  Y Y  \\  |   |  \\  ___/|  | \\  ___/ \\___ \\  |  |  "<<std::endl
		<<"|__|_|  /__|___|  /\\___  >__|  \\___  >____  > |__|  "<<std::endl
		<<"      \\/        \\/     \\/          \\/     \\/        "<<std::endl;

I like the logo but...     a gustos los colores

**Comment by 4w** [comment]
You two obviously don’t get it.

**Comment by kilbith** [comment]
> is part of MT culture

Female genital mutilation is part of some African cultures... so that should be kept as well?

**Comment by paramat** [comment]
I agree there may be some issues here.
I think the art is printed too often, it doesn't need to be on every world entry, it could be once on program startup instead, which seems much more suitable.
I'm not bothered if it is printed by a logging function, it's probably done that way for simplicity.
Log level shouldn't remove the art as it is relevant whatever log level is.

My suggestion:
Move the art to be printed once on program startup as the first thing you see in logs after the separator. A simple move with no extra code, no options. I will +1 that. What do other devs think?

**Comment by 4w** [comment]
> Log level shouldn't remove the art as it is relevant whatever log level is.

It is completely irrelevant in ANY log level. It neither serves as separator (there already is a separator in the logs and on command line the input prompt is a separator) nor does it serves any purpose that justifies logging it as `action`.

**Comment by benrob0329** [comment]
Why don't we just check if`` --nologo`` was passed and call it a day? This isn't a particularly complicated issue and you're not forced to use it. As for bloat, this is such a small option I don't think it counts as bloat if there is demand (which there is).

**Comment by ritschwumm** [comment]
either keep the logo as it is, or just delete it. it neither does enough harm nor is it useful enough to earn a lengthy discussion - or any added complexity in the code.

**Comment by paramat** [comment]
> I think a --nologo would be good for people who want to have a cleaner log, can be added to an sh file that is called to start the server

I don't think that's worth doing either. There's no reason to have this as optional, 2 devs don't want an option.
If the art is moved as i suggested to be only on program startup directly after the separator this makes the start of each session easier to find.
However currently it makes each world entry easy to find when scrolling through debug, so may be best left as it is, i'm not sure. I have removed my suggestion to move it.
We have 5 devs preferring to either keep it or have no option and this is somewhat of a waste of time, closing but feel free to discuss if you want.

**Comment by paramat** [comment]
Here's the code https://github.com/minetest/minetest/blob/master/src/server.cpp#L379
```
	// Start thread
	m_thread->start();

	// ASCII art for the win!
	actionstream
		<< "        .__               __                   __   " << std::endl
		<< "  _____ |__| ____   _____/  |_  ____   _______/  |_ " << std::endl
		<< " /     \\|  |/    \\_/ __ \\   __\\/ __ \\ /  ___/\\   __\\" << std::endl
		<< "|  Y Y  \\  |   |  \\  ___/|  | \\  ___/ \\___ \\  |  |  " << std::endl
		<< "|__|_|  /__|___|  /\\___  >__|  \\___  >____  > |__|  " << std::endl
		<< "      \\/        \\/     \\/          \\/     \\/        " << std::endl;
	actionstream << "World at [" << m_path_world << "]" << std::endl;
	actionstream << "Server for gameid=\"" << m_gamespec.id
			<< "\" listening on " << m_bind_addr.serializeString() << ":"
			<< m_bind_addr.getPort() << "." << std::endl;
```
It's clearly a part of the actionstream messages about world and server startup, so is fine being in actionstream. Although it may, being extremely strict about it, on it's own not be an actionstream message this is the simplest way to add the art at server startup.

It's useful here to clearly mark the server startup, helpful when scrolling through thousands of lines of debug.txt, a separator here would be visually confused with the program startup separator.
If removed you would only need to re-add some kind of visually recognisable marker for server startup, for that purpose this is already ideal.

It's harmless, fun, looks good, acts as a much liked 'title screen' for the terminal (which would be completely boring otherwise), and is 6 lines of thousands in debug.txt.

Addressing some points:
> Since it’s loglevel is action this is written between all the other actions that are more important

>  IMO the fix would be make sure the ascii art gets printed first

It's already the first action message in logs so is not between other action messages, and would be no issue if it was.
With log level 'action' it is the 3rd message in debug.txt, very close to being first.
>  it has absolutely no purpose

It does have purpose as a marker, but also because it is art, it looks good and makes people feel good when they see it. MT has a sense of fun.
> on command line the input prompt is a good separator

I can't see any input prompt separator in terminal when exiting and entering worlds repeatedly, the art is the only clear marker there is.
> in the debug.txt there already is a separator

The separator is shown at program startup, not at world/server startup, so doesn't act as a marker for that.
> giving it an own log level below the action log level so it is only shown if the loglevel is below action (maybe introduce decorations and place it above verbose).

Many people use log level 'action' and would then miss out on this useful marker, so 'action' seems about right.
Adding an extra log level just for this would be ridiculous.
> It’s just another advanced setting. Nothing is bad with configurability

Configurability still needs good reason otherwise the code would be bloated with a setting for every single person who wants one.

You seem to have a very negative attitude towards the logo.
I can't see anything here worth working on, especially with our severe lack of dev time.
I suggest a close.

**Comment by 4w** [comment]
> It's already the first action message in logs so is not between other action messages

Neither on command line …

![2018-02-15-163847_685x349_scrot](https://user-images.githubusercontent.com/30605057/36265076-b585a3c0-126e-11e8-9142-4f0185023ffd.png)

… nor in the `debug.txt` file …

![2018-02-15-163920_662x599_scrot](https://user-images.githubusercontent.com/30605057/36265112-c96b6dd4-126e-11e8-9ce5-3f5531ba5a01.png)

… it is the first logged action.
