### ISSUE TITLE
Remove or greatly raise volume limits on 'find nodes in area (under air)'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7021]
##### Issue type
 - Request

For backport to 0.4.17

See #5277
This broke the popular mod Moretrees. Some mods may be safely using a slightly larger volume.
Someone may have a powerful computer and be experimentig in a singleplayer world. It's very difficult to decide on a limit, more important is good documentation warning about large volumes (the limits are actually not documented).

**Comment by paramat** [comment]
@VanessaE how many nodes do you need for moretrees? I suggest we raise the limit, how about 128^3 = 2,097,152?

**Comment by paramat** [comment]
r is 173
sect hr = 58
sect vr = 87
sizevec = 58, 87, 58
vol = 58*87*58*8 = 2,341,344
Will increase limit to allow date palms to work as before.

**Comment by VanessaE** [comment]
Why do we even need a limit at all?  Shouldn't that be up to the modder to decide?  As for why vr > hr, no clue - I didn't write the date palm code :smile:

**Comment by paramat** [comment]
Yeah i don't mind no limit, it's just easier for me to just raise it =)

**Comment by VanessaE** [comment]
Indeed.  You may as well just make the limit high enough no one could possibly ever hit it.

**Comment by paramat** [comment]
That would make a limit pointless, anyway i set it high.
#7065

**Comment by paramat** [comment]
#7065 merged.
