### ISSUE TITLE
First server join dialog is cut off

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7022]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.5.0-dev-87e08b1b
```

##### OS / Hardware
Operating system: GNU/Linux
CPU: x86_64

##### Summary
If you join a server for the first time, there appears a window with a warning. But the full text is cut off:

![Cut off greeting text](https://i.imgur.com/JxpzZlh.png)

##### Steps to reproduce
1. Join a server for the first time (new player name)

##### Considerations to fixing
When fixing this bug, keep translations in mind and please be generous with the space so other languages don't run out of space.

**Comment by srifqi** [comment]
So, a basic text will do?
```
You, as PLAYERNAME, will join SERVERADDRESS for the first time. Please rewrite your password to confirm.
(Text Field)
[Register and Join] [Cancel]
```

**Comment by sfan5** [comment]
Don't change the text, just move the UI so there's more space.

**Comment by SmallJoker** [comment]
> Don't change the text, just move the UI so there's more space.

My full support to this statement. We already discussed the fundamental text [here](https://github.com/minetest/minetest/pull/6849#discussion_r159261644) and had further bikeshedding [in this PR](https://github.com/minetest/minetest/pull/6911#issuecomment-357444223).

**Comment by nerzhul** [comment]
a scrollbar ?

**Comment by Wuzzy2** [comment]
Gosh …
Just make the freaking dialog bigger. There's plenty of space. :P

**Comment by ExeterDad** [comment]
Might consider how it will look on mobile. Text appears very large for every formspec.
