### ISSUE TITLE
The camera distance to the player does not change according to it's size

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#7023]
##### Issue type

 - Bug report
 - Feature request
 
##### Minetest version
```
Minetest 0.5.0-dev-4f5090f
```

##### Summary
The distance to the player does not change according to the size/height of the model, thereby making bigger sized models look weird.

##### Steps to reproduce
increase the size of the player by two and then press F7, the distance to the player has not changed.

**Comment by stujones11** [comment]
If you double the player model size then you would also need to set the camera offset
https://github.com/minetest/minetest/blob/4f5090ff68a0c51fd7bf23a709c27721109d8c5e/doc/lua_api.txt#L3795

**Comment by paramat** [comment]
^ I agree with that. It can't be automatic, and we have a way to set it already.
:-1:
