### ISSUE TITLE
place the nametags according to the height of the object

### ISSUE THREAD

**Issue by ThomasMonroe314** [minetest/minetest#7025]
##### Issue type
 - Feature request
 
##### Minetest version
```
Minetest 0.5.0-dev-4f5090f
```

##### Summary
me and my brother were talking about Minetest one day and somehow were talking about how the nametags for entities were hard coded to a certain height above the entity. Is there a way to automatically adjust the nametags to the entity height? I'd be willing to take a crack at it if noone objects

**Comment by QwertyCoolMT** [comment]
https://github.com/minetest/minetest/blob/62c10e3d0855fa14fdc260da0b7cd748e53db13f/src/content_cao.cpp#L636-L643	

it looks like it's already doing that adding .3 to the y axis of the bounding box containing the parent node.

can you give me an example of when this is happening? how to reproduce?  following the issue submission guideline would be helpful here.

**Comment by paramat** [comment]
Yes seems to be a certain distance above the collisionbox top.

**Comment by QwertyCoolMT** [comment]
there might be a bug somehow with certain entities, maybe a scaling float above entity vs a fixed .3f?

**Comment by paramat** [comment]
Can't see how, let's wait for an actual bug. A fixed distance is good enough.

**Comment by paramat** [comment]
Nametags are a fixed distance above the collisionbox top, what is the specific request?

**Comment by stujones11** [comment]
I guess that an offset could be useful, the collisionbox does not reflect the true size of the model in many cases, through necessity.

**Comment by QwertyCoolMT** [comment]
is there some other element of the model that would give us the true size value?

**Comment by stujones11** [comment]
> is there some other element of the model that would give us the true size value?

With animated meshes, I think not. You could use the selectionbox instead as that should give a better representation of the model's size but that will default to the collsionbox dimension unless explicitly set.

**Comment by paramat** [comment]
I agree, the selectionbox (if different to the collisionbox) is likely to be more accurate for the model top. Maybe this request can be for that?

Not sure yet what the exact request is here, but if it's for the distance above the box top to be adjusted according to model size i'm not keen, no need.

**Comment by stujones11** [comment]
Yeah, I think the selectionbox should be used in any case, an offset should not be necessary but the current offset may be worth re-evaluating, possibly even made into a function as suggested.

**Comment by paramat** [comment]
#7031 merged. No response from issue author about what the specific request is, it seems somehting that is already done, so closing for now.
