### ISSUE TITLE
Text-Size doesn't update without client restart

### ISSUE THREAD

**Issue by QwertyCoolMT** [minetest/minetest#7026]
##### Issue type

 - Feature request // Bug Report 

##### Minetest version
```
Minetest 0.5.0-dev-debug-e8325d2b-dirty (Windows)
Using Irrlicht 1.8.1
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=0
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system: Win 10 x64
CPU: intel i7

##### Summary
Not sure if bug or not implemented feature but my font does not update without restarting the client if i change font in pre-game menu.

##### Steps to reproduce
start game > Settings > Advanced Settings > Graphics > Menus > Font_size ("Font Size") 
Change this value, and the font size in menus do not change until restarting client.

**Comment by Wayward1** [comment]
I can't reproduce this on Windows 10 x64 or Antergos, both on an AMD A8-5545M, or on Android, all recent Git.

**Comment by QwertyCoolMT** [comment]
Do you have GETTEXT and FREETYPE Enabled? maybe that's why it works for you?

**Comment by Wayward1** [comment]
Ah, that's probably it.. Sorry, I must've missed that

**Comment by paramat** [comment]
Several settings require a program restart to take effect, seems a reasonable request since it would not affect in-game performance (i assume).

**Comment by paramat** [comment]
Folding into #5462
