### ISSUE TITLE
Add on_drop callback register.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7027]
##### Issue type
 Feature request
##### Summary
If you want to disallow players to drop items you need an callback like this:
`minetest.register_on_drop(function(dropper, old_itemstack, new_itemstack, obj))`
 dropper |  The player as ObjectRef
 old_itemstack |  The itemstack the player had before he dropped the item
 new_itemstack |  The itemstack the player has after he dropped the item
 obj |  The dropped item as Object.
return itemstack to set the itemstack.

The main Problem is that you can't easily add the on_drop callback to every item.

**Comment by paramat** [comment]
What are the use cases?

**Comment by Lejo1** [comment]
For example to disallow players to drop items.

**Comment by red-001** [comment]
@Lejo1 you can overwrite the item drop function for that right?

**Comment by paramat** [comment]
Hehe yes but i was asking the use case for preventing players from dropping items, it doesn't seem useful.

**Comment by Lejo1** [comment]
Yes you can overwrite it, but what is if there is still an important function on_drop?

**Comment by paramat** [comment]
1 year bump. Any core dev support?

**Comment by ClobberXD** [comment]
I consider this to be an essential feature. This shouldn't be dismissed just because overriding `minetest.item_drop` is possible, as that's just bad design. While the ability to override builtin functions is nice to have, it isn't feasible in many situations (e.g. what if multiple mods want to do something when players drop items?). Adding callbacks give mods the independence to do what they want without affecting other mods (which isn't the case when a mod overrides builtin functions).

**Comment by raymoo** [comment]
It doesn't matter whether an idea is good unless a core contributor makes a comment saying they like it.

**Comment by paramat** [comment]
I suggest drawing core dev attention to this on IRC, if a core dev supports the idea, this can be reopened (if so, please add the 'supported by core dev' label).

This may be useful, sorry if i can't see why, there wasn't a good argument made by the issue author to convince me. The only usecase stated was 'stopping players from dropping all items' which seems almost useless.

**Comment by ClobberXD** [comment]
Will do. In the meanwhile, here are a couple of use-cases:

- Counting player drops for whatever reason (e.g. new award in rubenwardy's `awards` mod).
- Logging player drops, and their positions.
- Implementing a "breadcrumbs" mod, to allow players to retrace their way back to base while exploring. (on_drop could be used to light up the dropped item wielded_light-style, for example)

Consistency is also a valid argument for adding this callback - almost all other callbacks have a global callback variant (`on_punch`, `on_dig`, `on_place`, etc.)

I'm willing to implement this. I hope seeing a PR will ease your doubts regarding whether this is even needed. :)
