### ISSUE TITLE
"Change Keys" from Game Menu causes error

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#7029]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev-501f936
```

##### OS / Hardware

Operating system:
Linux
CPU:
AMD

GPU model:
OpenGL version:

##### Summary

Game appears to crash when selecting "Change Keys".

debug.txt reports:
ERROR[Main]: Some exception: "Setting [keymap_toggle_force_fog_off] not found."

##### Steps to reproduce

Click "Play Game" then Esc to Game Menu. Then click "Change Keys."

**Comment by sfan5** [comment]
probably since 501f936b37046ab469844c5349054369de3e7fc6
@ThomasMonroe314

**Comment by paramat** [comment]
Yes 'force fog off' doesn't exist now.

**Comment by SmallJoker** [comment]
Fixed in af89a25
