### ISSUE TITLE
Dark and miscoloured nodeboxes

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7040]
##### Issue type

 - Bug report
 
##### Minetest version

af89a25ff3527ccf0740926fe0b797c4403840b0

##### OS / Hardware

Operating system: ubuntu 16.04 LTS
CPU: Intel Core i5-4670T CPU @ 2.30GHz × 4

GPU model: Intel Haswell Desktop (integrated)
OpenGL version: 3.0

![screenshot_20180215_102716](https://user-images.githubusercontent.com/3686677/36252397-6faf5062-123c-11e8-9f00-b20992c87cfd.png)

^ No smooth lighting

![screenshot_20180215_102743](https://user-images.githubusercontent.com/3686677/36252402-7374b6e2-123c-11e8-8d32-8a66adb8a2d8.png)

^ Smooth lighting, seems ok at first but the snow nodeboxes are actually darker and bluer away from the biome edge as is more obvious from higher up:

![screenshot_20180215_102802](https://user-images.githubusercontent.com/3686677/36252410-76ef59a8-123c-11e8-9880-4a08eb9e2ee9.png)

All effects, filters and shaders are off.
My guess is the recent changes to ambient occlusion @numberZero 
Setting 'sunlight_propagates = true' in the nodedef does not fix this.

**Comment by Fixer-007** [comment]
Yeah, there is clearly a bug, here is my situation (no smooth lighting for better view), center blocks are full blocks, they are bright for me, but not the slabs on edges:

![default](https://user-images.githubusercontent.com/16494741/36255889-677bbbca-1259-11e8-9ad6-180bb634f2bf.png)

**Comment by numberZero** [comment]
The reason might be that light levels of 14 and 15 don’t look equal anymore.

**Comment by numberZero** [comment]
Before 2d9f0d344e45282638f9c1c1b57019c5e7f3999c:
![screenshot_20180216_013842](https://user-images.githubusercontent.com/7352626/36285049-2b44eb60-12bb-11e8-8afd-60cae38f2c2d.png)
After:
![screenshot_20180216_013428](https://user-images.githubusercontent.com/7352626/36284771-07e08d06-12ba-11e8-8843-7c70380c96e2.png)
Apparently it looks properly here, despite the fact stairs have less light than plain stone there.

But under a ceiling that propagates light but not sunlight, there was and is a problem:
![screenshot_20180216_014053](https://user-images.githubusercontent.com/7352626/36285039-230321ba-12bb-11e8-9f36-37976ed977ce.png)

2d9f0d344e45282638f9c1c1b57019c5e7f3999c only made it visible in less special conditions:
![screenshot_20180216_013409](https://user-images.githubusercontent.com/7352626/36284769-079f12f4-12ba-11e8-80ba-b854e8fd2741.png)
Before it would look like:
![screenshot_20180216_015018](https://user-images.githubusercontent.com/7352626/36285353-44e82a72-12bc-11e8-8d57-cb41614d9c90.png)

*Note: for whatever reason, it detected 2d9f0d344e45282638f9c1c1b57019c5e7f3999c as b19241b9b, so version strings are the same on the screenshots. Don’t get confused, these are taken in **different** versions.*

**Comment by numberZero** [comment]
So is it possible to fix this bug not introducing another one? (As I described, reverting 2d9f0d3 would be only a work-around, as there are corner cases where it will remain).

**Comment by paramat** [comment]
Confirmed that nodeboxes have brighter sides but matching tops under an ice roof.

![screenshot_20180217_134628](https://user-images.githubusercontent.com/3686677/36341643-540cbb5c-13e9-11e8-921b-f580587dd824.png)

![screenshot_20180217_134550](https://user-images.githubusercontent.com/3686677/36341645-5adc9cd6-13e9-11e8-872c-7c24a2283b19.png)

**Comment by paramat** [comment]
But also happens under lights, here i have a long line of meselamps to ensure equal light levels underneath them.

![screenshot_20180217_135546](https://user-images.githubusercontent.com/3686677/36341721-7546005c-13ea-11e8-844e-aa5ac0c1dab7.png)

![screenshot_20180217_135504](https://user-images.githubusercontent.com/3686677/36341722-79b98c6c-13ea-11e8-9e7d-06ce9a99646c.png)

**Comment by paramat** [comment]
Further away from the lights the contrast is larger seen from one side:

![screenshot_20180217_140145](https://user-images.githubusercontent.com/3686677/36341798-90e7eb8a-13eb-11e8-9442-f8788770f9d2.png)

But equal brightness on the side facing the lights:

![screenshot_20180217_140424](https://user-images.githubusercontent.com/3686677/36341801-a156b9a6-13eb-11e8-94e6-3b9c478bb6c5.png)

**Comment by paramat** [comment]
Checked all this in 0.4.16 stable, all behaviour is the same except no brightness difference in direct sunlight (because it was hidden by light levels 15 and 14 being equal).

**Comment by paramat** [comment]
0.4.15 stable, exactly the same as 0.4.16 stable, and this was before smooth lighting was added to nodeboxes.
I'm beginning to think it's always been like this and we didn't notice due to: 1. no smooth lighting on nodeboxes so they looked different anyway. 2. Appearence in direct sunlight was ok due to light levels 14 and 15 being the same.

**Comment by paramat** [comment]
0.4.14 behaviour exactly the same as 0.4.15 and 0.4.16.

Maybe we will have to revert the light curve change?

**Comment by paramat** [comment]
Confirmed in 0.4.16 that with smooth lighting enabled all bugs are not visually noticeable.
It seems that the new light curve made this visible with smooth lighting enabled.

**Comment by numberZero** [comment]
> Maybe this is because nodeboxes get a single light level from inside and uses that for all faces, whereas cubic nodes have each face getting it's light level from the node neightbour?

Exactly, for the original bug. Under a row of meselamps, a nodebox has light level of 12 (assuming meselamp is 14), but for drawing, 13 is used, probably to match surrounding solid nodes. OTOH, the solid node uses different light levels for different faces: 13 for the top (as it’s nearer to the lamp), but 11 for the side (as it’s farther from the lamps than even the nodebox as air node light is used).

But for the now-appeared bug, the reason is different. As I noted, nodeboxes use light one level brighter for drawing than their true light value. But to do that, `undiminish_light` is used, which clamps at `LIGHT_MAX`, which is 14. So solid nodes get 15, and nodeboxes are drawn at 14 under direct sunlight.

The problem is that `undiminish_light` is also used in `voxel.cpp`. I think it won’t harm to replace it with mere `+1` there, but I’m not sure yet.

Also, one note on smooth lighting: it’s just the way it works. It can’t know that a face is exposed to direct sunlight, such logic would be complicated. I suppose *that* was imagined on adding the “non-trivial” label to the original issue.

**Comment by paramat** [comment]
Aha that makes sense.

**Comment by paramat** [comment]
It would have to be +1 clamped at 15 for the case of 'sunlight propagates' nodeboxes.
Anyway i can test if anyone makes a PR.

**Comment by numberZero** [comment]
Sorry, I checked a wrong version. `undiminish_light` is only used in meshgen currently.

**Comment by numberZero** [comment]
After fix:
![screenshot_20180218_003807](https://user-images.githubusercontent.com/7352626/36345878-7c35eca6-1444-11e8-8c71-711c8d0de5bf.png)
Note that I use extreme (`lighting_beta=4.0`) settings to make things clearer.

**Comment by numberZero** [comment]
> Setting 'sunlight_propagates = true' in the nodedef does not fix this.

Because it doesn’t affect lightning of already placed nodes: lighting is only recalculated on changes.

**Comment by paramat** [comment]
The bug remains with smooth lighting under direct sunlight so i think we will have to revert https://github.com/minetest/minetest/commit/2d9f0d344e45282638f9c1c1b57019c5e7f3999c#diff-1bf86c5e08b07bc255ad8698c565bab6 #6696 instead of #7051

**Comment by numberZero** [comment]
@paramat I think I found a solution for smooth lighting as well. Will it work, I will make a PR soon.

**Comment by numberZero** [comment]
Okay, my solution can’t work as-is in the current lighting system. Reverting 2d9f0d3 seems to be the best fix for now. But note that #7051 is still a cleanup.

**Comment by paramat** [comment]
Ok.

**Comment by paramat** [comment]
#7061 merged.
