### ISSUE TITLE
server_map_save_interval includes env_meta.txt

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7050]
##### Issue type
Feature request

##### Summary
I tried to let the server map reset on crash.
The best Way is to never write the map in map.sqlite.
So I sette the server_map_save_interval to 10000000000000000
But as a result of this https://forum.minetest.net/viewtopic.php?f=6&t=18590 (just read the last post) it includes the env_meta.txt.
But it's a server_**map**_save_interval, not for the server list things.
It shouldn't include it.

##### Steps to reproduce
Set the server_map_save_interval to a very high value and let the server crash.
The Age of the server will be like the Age the server has before you setted the server_map_save_interval to something like 1000000000000...

**Comment by SmallJoker** [comment]
Marked this as low priority because if the map resets, the state of the game is again the old one. The server is indeed up for a longer time but `env_meta.txt` provides data about the world's age and time.

**Comment by Lejo1** [comment]
> If the map does not change, the meta data that belongs to it shouldn't do so either.

And what is about Minigame servers, the Age of a server is not the activity of the server.

**Comment by rubenwardy** [comment]
Use the dummy backend

**Comment by Lejo1** [comment]
@rubenwardy 
#7077
