### ISSUE TITLE
HUDs with id of 0 aren't displayed

### ISSUE THREAD

**Issue by Amaz1** [minetest/minetest#7052]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 0.5.0-dev-11928b7a
```

##### OS / Hardware
Operating system: Void Linux
CPU: Intel(R) Pentium(R) CPU  N3710
GPU model: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller
OpenGL version: 3.0

##### Summary
When the id of a hud element (I've only tested with statbars and waypoints) equals 0, it isn't displayed. This issue seems to appear in and after 7d3295e21f96495cb0b3e2f732939344ce892e2a. Everything works fine in 0.4.16 and before 9649e4721467dab348011633c814a63a184bd018. (Between those two, most things concerning huds seem to be broken.)

##### Steps to reproduce
Download and extract the latest version of the [v2-rewrite branch of LOTT](https://github.com/minetest-LOTR/Lord-of-the-Test/archive/v2-rewrite.zip).
Make a new world with it.
Open the world, and run around for a bit. The stamina (green) bar above the hp bar will begin to deplate, and it won't have a background, which it should (See the code here: https://github.com/minetest-LOTR/Lord-of-the-Test/blob/v2-rewrite/mods/lottplayer/systems/stamina.lua#L41). It will also send a chat message to confirm that the id of the stamina bar is 0.

**Comment by SmallJoker** [comment]
Somewhere we've got a race condition. About in the half of my tests it shows the background:
![grafik](https://user-images.githubusercontent.com/1497498/36354096-6cb2d006-14cf-11e8-94a6-704f219e8e71.png)

**Comment by v-rob** [comment]
The bar disappearing happens with HUDbars as well.

**Comment by SmallJoker** [comment]
Throwing in my test results ([IRC reference](http://irc.minetest.net/minetest-dev/2018-03-02#i_5243241))
```
18:58 	Krock 	in all my tests, the GUI ID=0 was registered and correct (:hud_get(0))
18:59 		so it must be something with the drawing part..
18:59 	Amaz 	Yep
19:16 	Krock 	for some reason the "text" field is "blank.png" when it's not shown
19:17 		but I don't get any search results for that text
```

**Comment by SmallJoker** [comment]
Testing results, confirming my first guesses. The text below is a tidied version of the log output, which is chronological correct - the server changes the HUD before the client knows whether there are any.
```
# Player joins the game
[Server] HUD ID 0 added (healthbar)
[Server] HUD ID 1 added (breathbar)
[Server] HUD ID 0 removed
[Server] HUD ID 1 removed
[Server] HUD ID 0 added
[Server] HUD ID 1 added
[Server] HUD ID 2 added
[Server] HUD ID 3 added
[Server] HUD ID 4...9 added

[Client] HUD ID 0 does not exist
[Client] HUD ID 1 does not exist
[Client] HUD ID 0 added
[Client] HUD ID 1 added
[Client] HUD ID 0 does already exist
[Client] HUD ID 1 does already exist
[Client] HUD ID 2 added
[Client] HUD ID 3 added
[Client] HUD ID 4...9 added
```

Packets to add the HUD arrive after those which remove the HUD, resulting in a mess which only seems solvable either by overwriting existing HUDs or by cleaning up one of the problem sources - which is `builtin/game/statbars.lua`

**Comment by 4w** [comment]
Here's what I observed some time ago.

https://github.com/4w/hunger_ng/commit/62907609f9ff8f5ca94020e37a2e93e5083b0b5b

**Comment by SmallJoker** [comment]
Re-open this issue if it still happens after [ffb17f1](https://github.com/minetest/minetest/commit/ffb17f1c9a203fea6de70159b461f52d104e05b9) (removed legacy code) and [eea1fda](https://github.com/minetest/minetest/commit/eea1fdaf2574fec38316527cfc463ff2427c5775) (startup fixes).
