### ISSUE TITLE
Lua debugging

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#7054]
##### Issue type
Feature request
 
##### Summary
Debugger is the developer’s most valuable tool. Fortunately there are programs that allow debugging Lua requiring little changes on the application side. This patch allows using [ZeroBrane Studio](https://studio.zerobrane.com/) to debug mods (and builtin, too):

```diff
diff --git a/builtin/game/init.lua b/builtin/game/init.lua
index ab1503dee..83f481934 100644
--- a/builtin/game/init.lua
+++ b/builtin/game/init.lua
@@ -1,3 +1,4 @@
+require('mobdebug').start()
 
 local scriptpath = core.get_builtin_path()
 local commonpath = scriptpath.."common"..DIR_DELIM
diff --git a/src/mods.cpp b/src/mods.cpp
index dae492339..76529c717 100644
--- a/src/mods.cpp
+++ b/src/mods.cpp
@@ -101,7 +101,7 @@ std::map<std::string, ModSpec> getModsInPath(std::string path, bool part_of_modp
 			continue;
 		std::string modpath = path + DIR_DELIM + modname;
 
-		ModSpec spec(modname, modpath);
+		ModSpec spec(modname, fs::AbsolutePath(modpath));
 		spec.part_of_modpack = part_of_modpack;
 		parseModContents(spec);
 		result.insert(std::make_pair(modname, spec));
```

That’s not the best way, however; e.g. `require` conflicts with mod security, `dofile` still may get relative paths (which ZBS doesn’t support). So, any opinions on how to make it better?

**Comment by pkulchenko** [comment]
> That’s not the best way, however; e.g. require conflicts with mod security, dofile still may get relative paths (which ZBS doesn’t support).

Can you elaborate on this? What exactly is the problem with relative paths?

**Comment by numberZero** [comment]
> What exactly is the problem with relative paths?

Dunno, but ZeroBrane Studio doesn’t support that. According to [the FAQ](https://studio.zerobrane.com/doc-faq#why-breakpoints-are-not-triggered),

> ...you may want to check if the path reported by the engine is normalized (doesn’t include ../ references) by checking the result of debug.getinfo(1,"S").source.

While that might be better to fix their side, it is probably easier to adopt ours, the adoption needed is minor.

What is more important is debug session initialization; it is different for different debuggers (I know only ZBS, but heard there is an Eclipse plugin and something else) and it requires extreme privileges. Besides, running code under debugger is slow, so features to switch debugging on and off should be used as well to make debugging feasible.

**Comment by pkulchenko** [comment]
>> What exactly is the problem with relative paths?
> Dunno, but ZeroBrane Studio doesn’t support that. According to the FAQ,

I think it does support that, as long as the path that set in the IDE and the path that the interpreter "sees" are the same. I think the warning about relative paths applies to paths like "../myproject/myfile", but even those can be handled, as there have been recent improvements to the path normalization logic in the debugger.

I'd give it a try as I'd expect relative paths to work.

> (E.g. unified_inventory initialization takes ages under debugger; I don’t know how long exactly; I had to kill MT and disable it to be able to debug other code).

Not sure about Eclipse, but in ZBS, you can put `require('mobdebug').start()` call anywhere in your code, so you can just start debugging after all the initialization has already been completed.

You can also "bracket" the section you want to debug into on/off calls and turn the debugging off everywhere else, which will remove the slowdown related to debugging from the other code; see [this documentation section for details](https://studio.zerobrane.com/doc-lua-debugging#turning-debugging-off-and-on).

**Comment by numberZero** [comment]
@pkulchenko Oh, sorry, didn’t noticed who you are... I thought I’m talking with a MT dev.

On relative paths: MT may use paths like `../myproject/myfile`, and it commonly uses non-canonical paths of form `/path/to/minetest/bin/../mods/somemod/init.lua` (at least in run-in-place mode). These paths aren’t handled by ZBS correctly. (I have pkulchenko/ZeroBraneStudio@f439428a2502ec8925abed741b7290f0e9adb848)

On switching on and off: I read the docs already, I’m just saying these things might be exposed in the MT API in some nice way. Mod security forbids `require` completely, but is it fine to disable security globally to debug just one mod?

**Comment by paramat** [comment]
1 year bump. Any core dev support?

**Comment by sofar** [comment]
I'd like to see it, but it has to be optional I think. `mobdebug` is widely used and doesn't depend on zerobrane.
