### ISSUE TITLE
Please add separate priveleges for build, mine, node_use, inventory_use, attack

### ISSUE THREAD

**Issue by poikilos** [minetest/minetest#7057]
##### Issue type
 - Feature request
 
##### Minetest version
0.5.0-git

##### OS / Hardware
Antergos

##### Summary
Making some type of multiplayer arena that isn't breakable is really hard right now. I don't know if protection works better in the git version, but I do know that at least up to 0.4.16 people can eventually dig horizontally or downward through things protected by [protector redo](https://forum.minetest.net/viewtopic.php?t=9376) or even [advanced area protection](https://forum.minetest.net/viewtopic.php?t=7239) when there is any amount of lag. Even if that is fixed (if player mining and movement no longer occurs in the milliseconds preceding the protector or advanced area protection taking effect), more priveleges would allow a proper protection mods to be made. The solution below explains what I mean by a "proper" protection mod. This is possibly easy to implement (?) but could improve the ability to make minigames or quests drastically.

##### Solution
Add more priveleges so that a "proper" protection mod like <https://forum.minetest.net/viewtopic.php?id=5545> could be forked and expanded further--such as so that nodes cannot be mined in the first place, even while a player is allowed to interact in other ways.
* Make separate priveleges for "build", "mine", "node_use", and "inventory_use", and "attack" (for backward compatibility, historical "interact" privilege could grant all but not having it wouldn't deny any of them)--that way all sorts of cool minigames and subgames could be made:
  * imagine an arena where the doors are automatically opened and closed but players can't break them or break the minigame by opening or closing the door or using the teleporter manually, because they have "attack" and "inventory_use" but not "node_use" (only other solution is to create a custom non-interactive door node or regular block such as cobblestone as a door and protect the area which hasn't been reliable in lag scenarios)
  * Someone could make a minigame or subgame where attacking by hand could be disabled via disabling the "attack" privelege, but some kind of laser tag type of weapon or paint grenade could still be used via the "inventory_use" privelege, and you could trigger traps or elevators with a separate "node_use" privelege
  * imagine a minigame or subgame where swords, punching, and remaking the world or minigame arena is prevented by having no "attack", "build", or "mine" privilege, but some kind of grappling hook, or item with supernatural powers or building powers can still be used via a "inventory_use" privilege, you can open doors and pull levers with a "node_use" privelege, but you can only complete your task or quest by using those methods (only current solution seems to be to make entire area out of blocks that aren't breakable by hand and to deny the player a pick and any items for making a pick, and to not provide them with any items that can be used as nodes).

**Comment by rubenwardy** [comment]
> imagine an arena where the doors are automatically opened and closed but players can't break them or break the minigame by open

Already possible by not registering on_rightclick for the doors, and no having a digging group. This is also a Minetest Game issue, the engine doesn't know anything about doors

> Someone could make a minigame or subgame where attacking by hand could be disabled via disabling the "attack" privelege, but some kind of laser tag type of weapon or paint grenade could still be used v

I'm sure this is already possible by checking the wield item in the punch callback, should be checked though

> imagine a minigame or subgame where swords, punching, and remaking the world or minigame arena is prevented by h

similar to above

----------

I can see this being useful in somecases - ie: making a read only map but allowing players to use signs and such - but the usecases you gave can already, and should be, implemented by mods

**Comment by paramat** [comment]
I'm not keen on this, we need very good reasons for new privs.

**Comment by jastevenson303** [comment]
Being able to use placed items without placing or digging them /is a very
good reason/.

**Comment by paramat** [comment]
What i mean is, most of this seems possible already as rubenwardy has explained.

**Comment by expertmm** [comment]
So maybe with the current privelege system, a new or forked area mod could use player_monoids or the new player_attributes backend:
* make monoids for "build_enable", "mine_enable", "node_use_enable", and "inventory_use_enable", and "attack_enable"
* add or remove a player monoid based on an area (revoke existing "home" privilege in the area for safety and/or periodically check for players leaking out of area, and handle death event)
* check for "attack_enable" monoid in the punch callback, and do wield item specific code as appropriate
* investigate handling and conditionally cancelling build, dig, and use events (check for "build_enable" "mine_enable" and "node_use_enable" monoids)
Is that worth trying or should I go in another direction? If the new player attributes backend would be better or more secure somehow, or if I am off on any of these points, I would appreciate any input.

**Comment by Ezhh** [comment]
Having an arena, or any other "official" area on a server that players can't lag-dig through is easy. Try to lag-dig through the walls of the Red Cat spawn (even after getting interact) to see this in use. You just need to register nodes with the right groups (which can mean a lack of groups) as has been pointed out.

**Comment by expertmm** [comment]
I am aware that I could make a copy of every block I want to use but with fewer or no groups. I am just looking at other possibilities that are less restrictive for builders and more intuitive to setup.

**Comment by paramat** [comment]
Creating new mod nodes for a special purpose is the best option, it gives modders more options and flexibility, while keeping the engine simpler and reducing developer workload. In some cases you could keep normal nodes as surface nodes and bury your special nodes behind them.
For anything that can be done already in mods i am :-1: 

Is there any part of your initial request that can't be done with custom mod nodes?

**Comment by expertmm** [comment]
Yeah, I'm understanding my options better. I still want to look into checking wield item in the on_punch callback in order to have:

* > item with supernatural powers or building powers
  but not be able to punch.
* Another issue is that a privilege area fork would actually be much better for protecting homes than the usual protection method, in order to avoid lag-digging (specifically, I could also fork protector in the same way). I was merely asking for more clarification on the suggestions from @rubenwardy , but that is better suited for [Modding Discussion](https://forum.minetest.net/viewforum.php?f=47) so I'll ask there if I need more info, so if there is nothing further on my "So maybe with the current privelege system" post, I'll consider this closed. Thanks for the valuable input.

**Comment by raymoo** [comment]
I feel like these use cases would be covered better by having a more granular protection system (see #2250 and #3833).

**Comment by 4w** [comment]
> What i mean is, most of this seems possible already as rubenwardy has explained.

Everything is possible using mods. Why not stop development and add new features as mods only?

Oh, I remember why.

**Comment by rubenwardy** [comment]
closing now, please comment here if you're unable to make this functionality with the current API
