### ISSUE TITLE
More contrast for menu tabs

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7060]
##### Issue type

 - Request / Suggestion

![screenshot from 2018-02-20 11-57-32](https://user-images.githubusercontent.com/3686677/36423005-2bb46674-1636-11e8-8e29-64fe01a8c6f9.png)

Tabs have white text on translucent white background, almost unreadable.
How about a translucent grey background a little lighter than the formspec background?
I could do this myself but can't find where the button background is set, where is it?

**Comment by 4w** [comment]
> How about a translucent grey background a little lighter than the formspec background?

Why not black text?

**Comment by Fixer-007** [comment]
Maybe instead do current Tab highlight?

**Comment by HybridDog** [comment]
You could add a simple decoration:
![36423005-2bb46674-1636-11e8-8e29-64fe01a8c6f9](https://user-images.githubusercontent.com/3192173/36500366-6d9a47b6-1744-11e8-83ff-f8454c77c1f4.png)

**Comment by paramat** [comment]
Current tab highlight is not necessary and doesn't improve readablity of all tabs.
There must be a simple setting for the tab backgrounds somewhere but can't find it.
I'd rather keep text white for consistency.

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-dev/2018-02-21#i_5235786
19:49 rubenwardy paramat, irrlicht
19:49 rubenwardy you'll need to change the skin in GUIFormspecMenu
19:49 rubenwardy unless we're using our own tabs implementation

Possibly
https://github.com/minetest/minetest/blob/20a85d76d94c9c5c7fbe198c3d0e1fbee97a485f/src/client/clientlauncher.cpp#L113

**Comment by paramat** [comment]
Actually possibly http://irrlicht.sourceforge.net/docu/classirr_1_1gui_1_1_i_g_u_i_environment.html#ae7042c520e848643e080ad4532797f23

**Comment by rubenwardy** [comment]
So, the tab (button) color is hardcoded to be the same for all tabs because of how it uses skin to draw the tabs. This means that we will need to make our own implementation of IGUITabControl to support colors properly if we want to avoid unintentionally changing the color of other elements

**Comment by Kezii** [comment]
This can be closed now I guess
