### ISSUE TITLE
Standard formspec templates (ie: default.gui_bg)

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7068]
Currently to correctly theme a formspec, mods will need to add the follow variables to their formspec:

```lua
formspec = formspec .. "bgcolor[#080808BB;true]" ..
    default.gui_bg .. default.gui_bg_img
```

There are additional variables which need to be used if you'd like the player's inventory to appear as well. This isn't great, as it requires a dependency on `default` which makes the mod hard depend on MTG. It's also very easy for a modder to forget to add these, and end up with unthemed inventories. Additionally, the main menu doesn't use these which ends up with and inconsistent default formspec design.

Solutions (in no particular order)

* Move variables and textures to `builtin`. Now `minetest.gui_bg` and such will work with any subgame, and mods can rely on its presence without disgusting dependencies. It's still easy to forget to add it, however.
* Move variables and textures to `sfinv`. Isn't ideal but better than default, also means sfinv doesn't need to depend on default.
* Add a way of specifying the default bgcolor, background, and such of any shown formspec. This is more complicated to program, but is a nicer solution

**Comment by Ezhh** [comment]
Any of these would be much better than the current situation.

**Comment by rubenwardy** [comment]
I'm currently leaning towards 3) as it gives a better result, and shouldn't be overly complex. It's the first step to a proper theming system. The API would be like so:

```lua
minetest.register_on_joinplayer(function(player)
    player:set_formspec_prepend("bgcolor[#080808BB;true]" ..
        minetest.gui_bg .. minetest.gui_bg_img)
end)
```

the above should probably go in builtin somewhere

**Comment by 4w** [comment]
The less stuff depends on MTG the better it is for MT in general!

**Comment by Wuzzy2** [comment]
Thank you for posting this issue.

Yes, these global variables thing is really ugly as it always enforces dependencies and also makes implemeting themes a chore with lots of annoying redundant code.

I'm happy with ideas 1 and 3, but not with idea 2 as this is just another MTG dependency. Note that many subgames would never adopt `sfinv` when they use something entirely different, e.g. Unified Inventory.

Solution 3 might be the cleanest solution. The Lua API already supports some defaults for other things, e.g. there is a changable default node definition. Maybe you can do something like this.

**Comment by Wuzzy2** [comment]
This seems to have been closed too early.
