### ISSUE TITLE
orthogonalize privileges

### ISSUE THREAD

**Issue by zeuner** [minetest/minetest#7071]
##### Issue type
 - Feature request
 
##### Minetest version
0.4

```

```

##### Summary
For some of the privileges, it makes only limited practical sense to have them distinguished. For example, "privs" and "server" are equivalent in the sense that a player with the "privs" privilege will always be able to obtain "server", and vice versa. I think it would improve the user (the "user" having some kind of maintenance/admin responsibility in this case) experience to have the privileges better orthogonalized with respect to each other.

For example, a server owner might want to give a player extensive capabilities to assign privileges on the server, but not to interfere with the server operation itself. Currently, this would only be possible by putting almost all privileges into "basic_privs", and granting the "basic_privs" privilege.

**Comment by paramat** [comment]
Any specific ideas from server owners / admin?

**Comment by zeuner** [comment]
@paramat: Well, if you ask me as a server admin, I would like to allow
some users to grant/revoke most privileges, so I would give them
"privs", but I don't feel comfortable with the "server" privilege
being also available to them. So, I would tend to take "server" out of
what "privs" allows to grant/revoke, but this opens up the question of
how the "server" privilege is to be granted to new admins.

original message follows:

**Comment by 4w** [comment]
> but this opens up the question of how the "server" privilege is to be granted to new admins.

It shouldn’t. `server` should be removed and individual permissions should be granted only. The server owner has `owner` permission that can’t be given to anyone and allows to grant detailed administrative permissions.

**Comment by Wuzzy2** [comment]
Input from actual server operators, moderators and anyone else would help a lot.

So far, I agree this issue is too vague.

Personally, I don't even see what's even wrong about the current privileges. I fail to see any actual problem. IMO the privilege sytem is fine as it is right now.

**Comment by Ezhh** [comment]
> The server owner has owner permission that can’t be given to anyone
You need to remember not all servers are managed by one single person. I run my main server very closely with a co-admin who also needs the same in-game access I have. He frequently decides who gets privs at all levels and I would hate for him to lose this access just as much as I'd hate to lose the ability to decide how I manage my server.

For the original issue:
I also think it's too vague, but I'd be against removing server as a separate privilege.

**Comment by red-001** [comment]
I suppose `server` could be made into a special case requiring the user granting or revoking it to also have `server`.

**Comment by 4w** [comment]
> You need to remember not all servers are managed by one single person.

Then have one main admin having the owner permission and other admins having the exact same permissions except owner permission that only allows granting and revoking administrative permissions and does not do anything on it's own.

**Comment by Ezhh** [comment]
@4w How is that different? I want my co-admin to be able to grant and revoke **all** privileges. For all in game purposes, I do not want "one main admin", and this really should be the server owner's decision to make.

**Comment by JurajVajda** [comment]
I am fine with basic_privs...if i would grant privs to some, they could easily grant them self server privilege anyway so server and privs privileges should stay dependent on each other imo

**Comment by Ezhh** [comment]
> This ensures that at least one person can recover any permissions if an admin goes postal. 

You already can't revoke all privs from the admin named in the conf file. In this sense, recovery is already always possible.

**Comment by 4w** [comment]
> from the ~admin~ *player* named in the conf file

FTFY.

And that is the main issue: A player always has any permissions. So there should be an owner/admin/root/whatever user that has `owner` permission and can be different from the player.

**Comment by Ezhh** [comment]
If someone is running a public server with a random player name there, it not being a player they have control of, then I'm not sure what you expect... It's still a failure of the server owner to set up the server correctly/securely. Even if you also add an owner option, you'll run into the same issue - it depends on the correct name being added.

Either way, this is offtopic and not what this issue was about, so you should consider opening a separate issue if you want to go further with this.

**Comment by zeuner** [comment]
@red-001: I like your approach for its practicality, although I'm
wondering whether the problem can be solved in a more elegant way.

original message follows:

**Comment by zeuner** [comment]
@Ezhh: Yes, server ownership cannot replace the "server" privilege.

I would also oppose the removal of the "server" privilege, but this
would also contradict this issue.

It is kind of vague for a reason since I guess there might be multiple
valid improvements to the current situation. If it was clear, this
would be better done as a pull request.

original message follows:

**Comment by zeuner** [comment]
@Ezhh: It's not possible to ensure that one _person_ can recover
any permissions since it cannot be ensured that a person can access
the owner account.

I think it's beyond this issue, and beyond what minetest can
possibly achieve to fully prevent uncautious people from locking
themselves out. Still, in the worst case it's always possible to
solve these situations by editing auth and/or server configuration,
and restarting the server.

original message follows:

**Comment by Ezhh** [comment]
@zeuner you say:

> I think it's beyond this issue,

I said:

> Either way, this is offtopic and not what this issue was about

So, maybe let that die or start a new topic. If you want to move back to your actual issue, you will need to be more specific than:

> It is kind of vague 

Some of us don't even feel there is an issue here.

**Comment by paramat** [comment]
Issues can be specific without being a PR. So to clarify, is post 3 what is being suggested? If too vague this issue should be closed.

**Comment by Ezhh** [comment]
To me it seems one of the following is wanted (but playing guessing games with non-specific info here...):
- basic_privs should grant more privs. (This can be changed per server, so if this is the issue, it's a non-issue).
- privs priv should not allow someone to grant server priv to others unless the player either has server already themself or is the admin. (I would not be happy if you needed to be the named admin to grant server priv).
- there should be a level of some kind between basic_privs and privs. (I think this could possibly have use for some people, but not sure if it would be enough use to justify it... also how many levels is enough levels? It could get a bit silly.)

**Comment by zeuner** [comment]
@paramat: It is vague on purpose because I'd like to consider
different approaches to tackle this issue.

However, if there is a strong urge for a quick resolution for any
reason, I think that red-001's approach would be an improvement
over the current situation.

original message follows:

**Comment by zeuner** [comment]
@Ezhh: I agree. I opened this issue in order to discuss possibilities
for reducing astonishment related to privileges, not for restricting
administrative decisions.

original message follows:
