### ISSUE TITLE
Dummy Backend should load the map data, if exist.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7077]
##### Issue type
Feature request

##### Summary
The dummy backend should load, if exists the map.sqlite, but don't change it.
It's almost the same, because you can just don't create a map.sqlite.
With this you can create fully criefer-save servers.

**Comment by rubenwardy** [comment]
This is not a bug, but how backends work

You should instead turn this into a feature request - load data from sqlite first

**Comment by Lejo1** [comment]
On my client it loads the data first, on my server not it should be the same.
I though it is a bug that is it only on my client so.

**Comment by SmallJoker** [comment]
If your client does something else, it uses a different configuration. The client also starts a server if you're hosting the map with it (singleplayer, `Host`). It is intended that backends work this way. If you want to load a read-only map I'd suggest 1) revoking interact from players , 2) load the sqlite3 map into a dummy backend manually using a Lua mod (hacky and horribly slow) or 3) patch your server so it does not save anything to the disk.

**Comment by Lejo1** [comment]
I now tested to start a server at home and there it works fine, so I also think there are different configurations.

**Comment by Lejo1** [comment]
You were right I thought the map got loaded, but it just get generated new.

**Comment by sfan5** [comment]
Fairly non-trivial to implement, this is not the `dummy` backend's intended purpose either.
:-1:

**Comment by Lejo1** [comment]
That's right.
New Iusse: #7081
