### ISSUE TITLE
Mod colours

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7078]
##### Issue type

 - Feature request
 
##### Summary

I think it should be possible to assign colours to a mod, e.g. yellow to mesecons. It could be set in a mod.conf file or something similar.
The colour could be used for colouring chatcommands in the message from /help and the mod names in /mods. It could also be used for colourizing the item descriptions or background in an inventory to e.g. make mesecons nodes easy to distinguish from homedecor nodes.
Setting a colour should be optional and of low effort.

**Comment by 4w** [comment]
> Setting a colour should be optional and of low effort.

It could be stored in `mod.conf` using one of the already supported color notations.

**Comment by paramat** [comment]
No need for MT version and OS info in a feature request.

**Comment by Ezhh** [comment]
If it happens, please let it be turned off by default.

**Comment by paramat** [comment]
So sorry, but i don't think it's worth adding.

**Comment by HybridDog** [comment]
I'm actually searching for a way to fix the unreadable message from /help and /mods when many mods are installed:
![screenshot_20180226_202838](https://user-images.githubusercontent.com/3192173/36690781-ae809d0a-1b33-11e8-8402-af116740926d.png)
![screenshot_20180226_202849](https://user-images.githubusercontent.com/3192173/36690843-d4de429a-1b33-11e8-8021-6cd9b6863762.png)
I thought about using two colours alternatingly, changing the colour each time the command doesn't belong to the same mod as the previous one. However, commands are sorted by name…

**Comment by paramat** [comment]
Making that more readable is a good idea but i think it could be done more simply through formatting and a restrained use of coloured text.
If text colour is involved i think it's better to have 1 or 2 hardcoded colours plus white, no set colours.
See #7019 i think this should be co-ordinated with that, using the same colours.

**Comment by KtlTheBest** [comment]
Hi, I am relatively new to this, but is it possible to make something like chat background (something darker color) to make text readable (like MC)?

**Comment by paramat** [comment]
We already have one, i don't know why it wasn't used in those screenshots (which are also against white snow).

**Comment by HybridDog** [comment]
> We already have one […]

Do you mean viewing the chat after pressing t or F10?
The bright text on bright background is in my opinion not really a problem because the text is shadowed.
However, the chat message blocks the view and in F10 it's only slightly more readable because of the content displayed.

**Comment by Ezhh** [comment]
I have always liked having them in alphabetical order ... Sorting by mod first doesn't feel helpful.

**Comment by paramat** [comment]
Yes i meant F10, i can't see any problem with it.
I think you have better eyes than me, those screenshots are unreadable.

**Comment by beyondlimits** [comment]
Why not icons?

**Comment by Wuzzy2** [comment]
I don't like this idea, it is too vague. Feel free to post concept art.

You did not specify what colors to use and why. If every mod can just choose its own color, it's going to be messy quickly.
There should at least be some system to that. Allowing mods to choose the color means there won't be any logic behind the color.

I think this individual mod name coloring will actually do more harm than good..

:-1:

**Comment by rubenwardy** [comment]
:-1: due to reasons wuzzy and others have stated
