### ISSUE TITLE
Player slips on slippery nodes when flying through underground ice with noclip and freemove

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7080]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.5 dev f9ad0619103ceee40e2a7810b971f93d877a63cd
```
The slippery feature should not affect players flying through slippery nodes with noclip and freemove.
Relevant commits https://github.com/minetest/minetest/commit/2ea26e655d90be538c75aad5cc7ede2c5709179f https://github.com/minetest/minetest/commit/fc13c00ef3e9b6f280146f3d77b6659fcc55a13c
@Wuzzy2 @bendeutsch

**Comment by SmallJoker** [comment]
Strange that `touching_ground` seems to be `true` in this particular situation.
https://github.com/minetest/minetest/blob/6c9df2ffa7ee81a05b28fdd6123a926abd284c72/src/localplayer.cpp#L1061
So that should be
```C++
if (free_move || !touching_ground)
	return 1.0f;
```

**Comment by paramat** [comment]
When you fly underground you are touching ground.
