### ISSUE TITLE
Add a readonly backend.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7081]
##### Issue type
Feature request

##### Summary
The readonly backend should just only load the map.
With this you can create fully criefer-save servers and maps can easily reseted on crash.

**Comment by nerzhul** [comment]
just disable map saving ? or set an infinite save time ?

**Comment by Lejo1** [comment]
just disable map saving, because infinite save time case this: #7050

**Comment by SmallJoker** [comment]
Backends operate independent to each other. What you might want is a setting that applies to all backends (whereas it would be quite superfluous for dummy).

**Comment by Lejo1** [comment]
That is also a solution, may the better one.

**Comment by HybridDog** [comment]
You can simply disallow writing to map.sqlite.
chmod a-w map.sqlite

**Comment by Lejo1** [comment]
I already tried it.
It results in a fatal Error.

**Comment by HybridDog** [comment]
Sorry, you're right.

**Comment by Lejo1** [comment]
May this should be disabled and changed to just a warning.

**Comment by paramat** [comment]
1 year bump. Any core dev support?

**Comment by ClobberXD** [comment]
Implemented by #7544.

**Comment by Lejo1** [comment]
Thanks for the info!
