### ISSUE TITLE
Bug in grow sapling

### ISSUE THREAD

**Issue by minduser00** [minetest/minetest#7087]
##### Issue type

 - Bug report
 
##### Minetest version
```
0.4.16
0.4
```

##### OS / Hardware
Operating system:  android  and  linux
CPU: probably all CPUs
 
##### Summary
Probable bug affecting saplings growth on V7 maps, the bug does not affect V6 maps.
When a tree grows, and its trunk collides with leaves of a nearby tree of the same species, the trunk does not grow in the place of those leaves.

##### Steps to reproduce

To reproduce this bug put pine_needles in the trajectory of the future trunk...

![screenshot_20180301_120032](https://user-images.githubusercontent.com/30205587/36842787-ab4dceb0-1d44-11e8-9f63-7e2eb41bf5f4.png)

Wen de sapling grows this is the result...

![screenshot_20180301_120059](https://user-images.githubusercontent.com/30205587/36842824-c7d3daa2-1d44-11e8-96ba-c2d920b8233e.png)

**Comment by paramat** [comment]
It's a MTGame issue, however it is intentional. Trees have 2 versions, the sapling-grown version does not force-replace any node other than the sapling itself, to avoid it griefing non-protected builds and other solid structures.
