### ISSUE TITLE
Pause UI inconsistent

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#7093]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-673f7196
```

##### OS / Hardware

Operating system: Windows 7 x86-64
CPU: Intel Core i3-2120

##### Summary
Pause menu UI has few elements that need tweaking, it looks ugly as of now even on english lang.
1) "Game paused" is off center, both vertically and horizontally
2) English language keylist pretty much fits into right side, yet still has a scrollbar to scroll 1px or so, it should not be visible in such cases IMO, other languages still need it though it seems.
![default](https://user-images.githubusercontent.com/16494741/36937755-cddcbfc6-1f20-11e8-8925-f91bbbc854b9.png)

**Comment by paramat** [comment]
'Game paused' needs repositioning, and maybe a capital 'P'?
For 'controls' maybe add more to make the scrollbar non-redundant.

**Comment by Fixer-007** [comment]
Rename 4 lines of W,A,S,D to single: - WASD: movement ?

**Comment by Ezhh** [comment]
Would honestly love to see that stupid scrollbar gone. :)

**Comment by azekillDIABLO** [comment]
While I'm here: why does my pause menu does this to my controls(in 4.16 stable) and has it been fixed?

![screenshot_20180309_110206](https://user-images.githubusercontent.com/17685062/37201912-58097b28-2389-11e8-8535-468a64f8d2bf.jpeg)
_Look at the right, it's written Z1, S2, Q3, D4_

**Comment by SmallJoker** [comment]
@azekillDIABLO That is a translation issue, thus not related to the pause UI.
https://github.com/minetest/minetest/blob/b592c52f1cafa0e668817b0c01347cc7402d035c/po/fr/minetest.po#L824-L839

**Comment by Calinou** [comment]
The translation issue should be fixed in the `master` branch:

![minetest_translation_issue](https://user-images.githubusercontent.com/180032/37207384-08a096fc-239d-11e8-9271-7bc848784a75.png)

It's still present in 0.4.16 though.

**Comment by paramat** [comment]
> English language keylist pretty much fits into right side, yet still has a scrollbar to scroll 1px or so, it should not be visible in such cases IMO, other languages still need it though it seems.

Unfixable, it's because the list is very slightly longer than the text area.
> "Game paused" is off center, both vertically and horizontally

:+1: for fixing that.

**Comment by Ezhh** [comment]
> Unfixable, it's because the list is very slightly longer than the text area.

Can't the text area be made a tiny bit bigger then? This is one of the most common ways of viewing that menu (number of lines corresponds to number of entries) and it looks terrible. The whole thing should be sized so that it only scrolls if an actual extra entry after the number that fits is present. (I did try and fix this once myself, but since the formspec was in the engine it was not very easy for me to play around with.)

**Comment by paramat** [comment]
When i tested, the scrollbar issue seemed fixed.
If not, we could easily add some more controls to the list to avoid the awkward in-between state.

**Comment by paramat** [comment]
![Screenshot from 2019-05-01 19-47-21](https://user-images.githubusercontent.com/3686677/57035475-09d75f00-6c4a-11e9-989e-778225dff30d.png)

All seems fixed in master.

**Comment by ClobberXD** [comment]
The results would vary depending on the screen res. and DPI. But if there's no scrollbar when running MT at 1080p using the default DPI, then I think we can consider this to be fixed.
