### ISSUE TITLE
Add Bats as Plantlike

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#7094]
##### Issue type
 - Feature request

##### Summary

Had the idea, thought I'd throw it out there real quick: You put fireflies in as a plantlike, you could add bats that work the same way but spawn underground. Also you already will have the net for retrieving them to, they would add some life to the underground and make a good decoration for a mansion or anything else.

**Comment by sfan5** [comment]
wrong repo
-> [minetest/minetest_game](https://github.com/minetest/minetest_game)
