### ISSUE TITLE
/help and /mods with many mods

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7095]
##### Issue type

 - Feature request
 
##### Minetest version
```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: Lubuntu 17.10
CPU: intel

##### Summary

https://github.com/minetest/minetest/issues/7078#issuecomment-368623497
When many mods are installed, /help and /mods output is difficult to read. I think this should be fixed.
![screenshot_20180303_220723](https://user-images.githubusercontent.com/3192173/36939336-5b67a578-1f2f-11e8-867e-1594daf6a95c.png)
![screenshot_20180303_220733](https://user-images.githubusercontent.com/3192173/36939341-6331063c-1f2f-11e8-9bfb-4b42009312cd.png)

**Comment by lisacvuk** [comment]
Maybe it should be a formspec?  
With the terminal printout as an option?

**Comment by paramat** [comment]
Difficult to read in what way? Background or formatting changes?
I guess in some worlds a dark scene may not be available to provide a dark background. So improvement seems needed.

**Comment by HybridDog** [comment]
> Background or formatting changes?

Mainly formatting changes. It's difficult to find a specific mod because I cannot easily recognize the borders (comma and space) between them. Setting the colour to grey alternatingly could make separating them easier. The background is sometimes disturbing, too.
The chunk of text also blocks the player's view. The text can be read after pressing F10, where there's a background and scrolling is possible.
