### ISSUE TITLE
Minetest Launcher

### ISSUE THREAD

**Issue by nOOb3167** [minetest/minetest#7102]
Launchers and related things get discussed from time to time (#4917) (#3596) .
I am trying to make one. It may have a chance of working but kind of WIP.

[Launcher website with download link](http://desu.no-ip.info:6758/)

Download is for Windows OS.
Video demonstration linked on website.

Launcher is able to self-update then download and run minetest. If a newer version is
available on the update server, only changed files are downloaded (incremental update).
Only one version is served currently, but network protocol and file structures used, allow
multiple versions / releases (important to be able to serve 32/64 bit releases and for multiple OS in the future).

**Comment by paramat** [comment]
Maybe related https://github.com/minetest/minetest/issues/6498#issuecomment-334961168 and that issue.

**Comment by 4w** [comment]
Your comment there (“Separate repos would break git history and blame”) isn’t quite correct.

https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository

**Comment by nOOb3167** [comment]
There seem to be multiple different concepts called a 'Launcher' as per #6498 and other issues.
One being the GUI with server list etc that opens after starting main Minetest executable.
I am indeed not attempting to mess with or split that functionality out.

There is at least one use case for a Steam-concept launcher in Minetest: Automatically obtaining a release compatible with the server user is attempting to connect to.

Server list telemetry ([who tf calls their domain 'kitsunemimi'](https://kitsunemimi.pw/tmp/serverlist_stats_2018-03-06.txt)) indicates multiple Minetest versions are in widespread use. This situation may grow worse with the incompatible 0.4.xx -> 0.5 version transition.

Support for multiple versions boils down to Launcher functionality, even if it is called something else.



Also for drama purposes:

> Your comment there (“Separate repos would break git history and blame”) isn’t quite correct.
https://stackoverflow.com/questions/359424/detach-move-subdirectory-into-separate-git-repository

History up to the point of separating a repository into two can indeed be migrated by the approach you linked - but afterwards you'd have to somehow manually track / correlate changesets between the two repositories. Git's answer to managing multiple related repositories are git submodules and [they](http://slopjong.de/2013/06/04/git-why-submodules-are-evil/) [suck](https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/).

**Comment by 4w** [comment]
> but afterwards you'd have to somehow manually track / correlate changesets between the two repositories.

But why? If you split out one part of the application it is a different project and does not need to be code-comparable anymore. *blame* and other stuf should stay on a per repository basis.

**Comment by rubenwardy** [comment]
I suggest exploring the use of luadoc. You could make a file called documentation.lua which has all the signatures of functions and comments about them. I'm not sure how good it is at other things though

**Comment by Fixer-007** [comment]
Nah, launcher is overkill, we should encourage use of latest version of minetest, that is better in all regards, and you can update your game within the game (like in Pathos), and updates are rare anyway.

**Comment by 4w** [comment]
> and you can update your game within the game

Not if using a properly installed (i.e. using the package manager) version.

**Comment by nOOb3167** [comment]
Platforms such as Android and iOS app stores on mobile, and linux package managers have essentially launcher / update functionality, right?

Windows has no package manager.
For linux, package managers do not fit all use cases well (such as actively developed online videogames).

People are building not just graphical frontends to package managers (like gnome-software), but systems like [Snaps](https://en.wikipedia.org/wiki/Snappy_(package_manager)), [FlatPak](https://flatpak.org/),  [AppImage](https://appimage.org/), which integrate with frontends (like gnome-software).

The purpose of these systems is _inarguably_ to run around and bypass the standard linux distro packaging protocol. Quoting directly from that linked AppImage site:

> "As a user, I want to download an application from the original author, and run it on my Linux desktop system just like I would do with a Windows or Mac application."
"As an application author, I want to provide packages for Linux desktop systems, without the need to get it \'into\' a distribution and without having to build for gazillions of different distributions."


About the following point, I think you have it exactly backwards:

> and updates are rare anyway

It is not: updates are rare -> therefore launcher / update functionality is unnecessary -> therefore continue using manual downloads on Win, Package managers on Nix.
But rather: updates are hard _and_ not picked up by users -> therefore updates are rare.

Look at the [Minetest ChangeLog](http://dev.minetest.net/Changelog#0.4.16_.E2.86.92_0.5.x_.2813_jan.29) for 0.4.16 -> 0.5.x.

Clearly many of these features and fixes would be worthy of making a new update, if it were easier to push it to users.

It is desirable to make gradual movement towards automatizing updates across platforms Minetest runs on.

**Comment by azekillDIABLO** [comment]
An awesome idea in my opinion.

**Comment by nOOb3167** [comment]
Now using a two stage design:
The updater executable (minimalistic GUI) downloads and runs the second executable (HTML/CSS GUI),
which can then launch minetest.

[Video Demonstration](https://www.youtube.com/watch?v=AjUEArazC1A)

I'll need to somehow get web hosting for test server.

**Comment by XenonCoder** [comment]
I propose to run the Minetest launcher in Python 3 and create the executable build in pyinstaller, so as to make the launcher stand-alone and easy to develop. Making the launcher in C ++ seems like a useless effort since it is not a complex software (at least initially).

it's just my personal opinion, many do not have skills with a complex language like c ++.

Alternatively, you can use Java and then convert the bytecode code into C ++ and directly implement the executable binary.

What do you say? I think it's a good idea for everyone, so I can work on it too.

**Comment by 4w** [comment]
> What do you say?

While Python is awesome one needs additional libraries to create the GUI. So the launcher either needs to ship them or needs to depend on the libraries already being installed to the system.

Both should be avoided. So better write the launcher in a compiled language, and include anything needed so the launcher can run standalone.

**Comment by nOOb3167** [comment]
Now obtaining serverlist in a rudimentary way.

[Video Demonstration](https://youtu.be/zTzx_uOXTgs)

What I want to do next is allow servers to redirect to a custom info page when selected from server list.
Likely the program running behind http://servers.minetest.net/list has to be modified to specify an extra URL attribute for each server (with location of custom info page).


Regarding development language / stack:
I know both Python and Java to some degree, so switching is theoretically possible.
Allowing the launcher to run standalone (vs bundling lots of dependencies) is a factor.
(Of similar programs, the Steam installer comes as small-size executable, which downloads the rest)

More impactfully, I consider running an uniform end-to-end development stack to be valuable.
For Minetest this is C++ as language, with CMake as build system.

[SpringRTS (formerly TASpring)](https://springrts.com/) is, similarly to Minetest, a moddable multiplayer game engine.
The components SpringRTS needs for a fully functional multiplayer system are: A Lobby Server, a Lobby Client, and the Engine.

Over the years, the dominant implementation for each of these components turned out as: python (uberserver), C# .NET (zklobby), C++/CMake (engine).

The C# portion was maintained by some people.
Those people as a group had next to no overlap with engine group.
The python portion was maintained by absfouckingly no one ever and in my opinion singlehandedly proves python is an unmaintainable programming language (measly 5 thousand lines of code as a whole but can never be refactored because everything breaks and no compile time diagnostics or tooling ever).

Effectively something like an [Information Silo](https://en.wikipedia.org/wiki/Information_silo) problem manifested.

The results were terrifying. I am willing to waste effort writing C++ just for the sake of uniformizing the development stack.

It is true that in Minetest case the program generating the server list is python,
and some auxiliary projects use obscure stacks ([mtmediaserv - Golang](https://github.com/minetest-tools/mtmediasrv), [Mod/Content Database - python+flask?](https://forum.minetest.net/viewtopic.php?f=14&t=19766)).
But the server list program seems simple enough not to be causing a problem yet, and the other projects are essentially optional.

I believe TASpring is very bad precedent and too similar to Minetest to be safe (TASpring has Lua modding and even an analogue to CSM / server-sent-CSM implementation , may want to take a closer look at that some time).

This is not a solved problem so in the end noone can say.. Maybe Minetest can just avoid all the issues?

**Comment by nerzhul** [comment]
Launchers are just in the old era. No game use launchers as game GUI's are now enough mature to display dynamic content. I don't want to see a such ugly thing in MT. Just redisign the main menu should be enough

**Comment by thecow275** [comment]
main menu redesign would be great as it resembles a game from the early 2000s and the settings menu needs a redesign imho. 
why not make the menu a "modern" design where the menu selections are on the screen like now but then it opens a new menu on top of the buttons with save,cancel buttons I know this would be hard and complicated to make but it would make the game/engine more appealing to new people as i myself was like what s*** this is when i first saw the menu although when learnt that what modding community there is around the game i was blown away by it 👍 and i am creating my own mod on a organization with a friend. I think that the menu design would be the following with button layout

- Play Singleplayer (Local Game)
- Play Multiplayer (Play Online)
- Mods | Texturepacks
- Settings
- Credits
- Quit                        (for Windows or other os when in fullscreen)

**Comment by 4w** [comment]
> main menu redesign would be great as it resembles a game from the early 2000s and the settings menu needs a redesign imho.

The problem is that none of the MT devs seems to know UI design. There isn’t even a proper UI API except this formspec nonsense that looks like it’s meant for prototyping only.

**Comment by thecow275** [comment]
yeah i know tried making a ui element for ingame machine Holy S*** it is painful why formspec why not make an api that implements a formspec element by simple api calls that tell how to grid the stuff and imho formspec is trash as it bloats the lua when every single mod has to create their own formspecs instead of a api that translates a lightweight api call to ceate the formspec from simple instructions like slow=0,1,x=g1,y=g1 which would translate Row 0 inventory input 1 x= grid pos 1 y= grid pos 2 also for example 
minetest.create_ui({
uiid = "modnamehere",
uisize = "2x2 ",  -- first 2 means 2 rows  second 2 means line 2 a.k.a 2x2=4 input fields or outputs
uielements = { 
slot={0,1,x=g1,y=g2, type="output"} ,
slot={1,2,x=g1,y=g2, type="chestslot"},
slot={2,1,x=g2,y=g1, type="input"},
}
uiprocess = {
if slot0,1" = output then
-- insert some inventory api here `:)`

}

**Comment by Fixer-007** [comment]
You are trying to copy unnecessary design:
+ compared to complex minecraft infrastructure, minetest is simple, distrib is mere 20mb in size, most users of it are linux/android with updating via repos/stores, windows is the only one without autoupdate, manual update is quick, just overwrite old files, updates are very rare (you can improve main menu to notify about new updates).
+ current minetest supports connecting up to 0.4.12 servers iirc, which is fine for most folks, since most servers are on 0.4.16 anyway
+ there is no point in running old server, when you can run your old game on new engine anyway.

**Comment by paramat** [comment]
See #6498 for more discussion on launchers, note that celeron55 and another dev are opposed, be aware it's controversial.

**Comment by nOOb3167** [comment]
I can't find the opposement-declaring message of celeron55. It would probably help if I knew what the arguments were?

> for me launcher has no interest in games, it's an old practice due to the fact menus were not easy to implement

> Launchers are just in the old era. No game use launchers as game GUI's are now enough mature to display dynamic content.

Nerzhul is roundabout but essentially I consider the posts to understate the scope of Minetest menu overhaul by order of magnitude.
You cannot redesign good UI with built-in Minetest formspec functionality, am I correct here?
Modders always complaining about formspec limitations.

Especially because displaying 'dynamic content' is mentioned, I assume the plan involves LUA scripting (dynamic), and is to proceed along these lines:
Develop drawing primitives and comprehensive input interface for mainmenu scripting, then use those to build an UI element framework, then use it to implement the menu.
This process will take years.

Menu implementation in Minetest is not easy, and Minetest IS old era.

**Comment by rubenwardy** [comment]
Multiple devs against and not popularly supported

**Comment by paramat** [comment]
https://github.com/minetest/minetest/issues/6498#issuecomment-334961168
celeron55
> Also, personal opinion: Launchers are stupid.

**Comment by nOOb3167** [comment]
What does "Won't add" mean in this context?
No change or addition to Minetest is proposed here.
Poor literacy.

**Comment by SmallJoker** [comment]
@nOOb3167 It's a general disapproval regarding the concept of a Minetest laucher by the Minetest developers. Further formspec limitations and requirements can be submitted in a separate issue: #6527.

**Comment by nOOb3167** [comment]
Yes thanks, that is the crux:
So the direction intended is towards something like mentioned above, enhanced GUI, probably CSM bindings?
