### ISSUE TITLE
Use shaders from OpenSpades

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7106]
##### Issue type
 - Feature request

##### Summary
[OpenSpades](https://github.com/yvt/openspades/) has gorgeous [shaders](https://github.com/yvt/openspades/tree/master/Sources/Draw) and the game is written in C++.

What are the impediments of importing them to Minetest?

**Comment by weqqr** [comment]
I see a few problems here.
- Licensing. I'm not a lawyer, but I think you can't redistribute GPL'ed code (OpenSpades) under LGPL (which Minetest is licensed under).
- Minetest is tightly interwoven with Irrlicht, so swapping the renderer out won't be easy. Even if we keep Irrlicht and issue OpenGL calls on our own, this is still gonna be a tremendous amount of work.
- Poor mod support. Let's take the shiny water and glowing lava for example. How would you reliably tell them apart? And what if a mod needs a liquid that looks totally different?
- What about mobile devices and old PCs? Shadows can give an unfair advantage in PvP.

**Comment by sfan5** [comment]
Easier said than done.
Shaders are not something you can just throw into a game, they require tight integration with the codebase to achieve certain effects.

**Comment by tacotexmex** [comment]
I see, those are all impressive obstacles.

From my impression the MT community lacks even a single well-versed shader developer, is that so? Perhaps recruiting @ yvt to the project could be a way forward, if an import isn’t feasable?

**Comment by StripedMonkey** [comment]
Shader development is something that needs to be done for minetest but I severely doubt its gonna be done any time in the future.
