### ISSUE TITLE
Feature Request : Shaders : Non-Trivial : 2nd rendering stage, depth(8bit)-,normal(rgb)-, and object(rgba)map

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7109]
I would really like to see a 2nd rendering stage and the mentioned additional maps allowing MANY cool post-processing effects at minimal GPU costs.
numberZero had a nice post-processing stage, but I have been told it is 'outdated'-
So we need something new...

**Comment by SmallJoker** [comment]
Duplicate #5446
