### ISSUE TITLE
Pos, mapgen, seed in screenshot file name

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7111]
##### Issue type
 - Feature request
##### Summary
It would be handy for the screenshot function to put player position (ie "-200,32,21"), mapgen name (ie "mgv7") and seed (ie "1763810008200124486") right into the file names of the screenshots.

Like so:
`screenshot_20180308_144645_-200,32,21_mgv7_1763810008200124486.png`

##### Pros
- Easy for finding your way back to beautiful locations
- Easy for others to find the same landscape after seeing the screenshot online

##### Cons
- Longer filenames
- Filename might not always find its way to the uploaded image anyway (Imgur etc)

**Comment by appgurueu** [comment]
For some image files theres "description"....

**Comment by tacotexmex** [comment]
What do you mean? Meta data? It's often stripped when uploading, so I figured that the file name is what is most likely to remain the same.

**Comment by paramat** [comment]
The screenshot name would be annoyingly long though, most screenshots don't need the information, and when you host a screenshot somewhere the original filename is usually changed. I think best this information is shown in the image using F5.

**Comment by 4w** [comment]
> Meta data? It's often stripped when uploading

I wouldn't upload unprocessed screenshots. Better extract the meta data and add it visibly when uploading the file (good file hosters provide a comment field). The file name will be lost anyways when one-click hosting the file.

Plus: IPTC is supported by all relevant file formats and allows custom attributes. So we could stuff anything into the screenshot without distracting the screenshot with visible debug information and keep paramat happy with a short file name 😄

**Comment by azekillDIABLO** [comment]
This is an excellent idea, but it should really be optional, because @paramat is totally true. 

But it's still quite a good idea, because showing F5 in a screeny looks very ugly. if you want to do a beautiful screenshot of place, you have to crop F5 afterwards or to take two screenshots, one with F5 and one without.

**Comment by XenonCoder** [comment]
@paramat You're right, great idea. It would be nice to have this information as a watermark generated in the screenshots, with the option to enable this information or make it hidden and not printable in the images. It would be nice to have a small semi-transparent frame with the information in columns, with the possibility to configure the positioning in the image (top left, top right, center and other) in this way if a user wants to insert a title at the top at the center to present his map he can choose where to show the information of the suit, the coordinates of positioning the player to other things.

I also propose the printed version of Minetest (0.5.0 stable, 0.5.0 dev).

This is really a good idea, useful and functional.

**Comment by tacotexmex** [comment]
I think watermarking is a not so good idea. If people usually hide the HUD when taking screenshots then why would they want watermarking?

I don't see longer filenames as a problem. All majors operating systems are desktop-based and use the concept of drag-and-drop.

**Comment by 4w** [comment]
> All major operating systems are based on the desktop analogy and use the concept of drag-and-drop.

Plus: the command lines of those systems support autoclomplete of filenames pressing the Tab key.

**Comment by paramat** [comment]
Watermarking is too complex to be worth doing, it's not difficult for someone to add seed and co-ordinates in a screenshot comment if required, i think this is low priority. As stated, filename is lost with most hosting so information in filename is not helpful.

**Comment by tacotexmex** [comment]
Regardless of filename getting lost in an upload process though, I’ve tons of screenshots I’ve no idea what position and seed they come from because it’s not like I take notes after each F12. So it could still be useful before uploading.

**Comment by paramat** [comment]
Yes useful for the user.

**Comment by paramat** [comment]
However, player pos, mapgen, seed would make the screenshot name extremely long, and most of the time that information is not needed So not of much use.
:-1:

**Comment by paramat** [comment]
Although keep in mind 1 disapproval doesn't stop a request, so you're welcome to keep this open.
