### ISSUE TITLE
Discussion culture in disfavour of architectural improvements

### ISSUE THREAD

**Issue by zeuner** [minetest/minetest#7112]
I noticed some rather strange behaviour from a group of developers on the github issue tracker. For architectural changes that might actually improve user and developer experience, any technical discussion is avoided. I even noticed that two technically unrelated issues (a frontend-related suggestion and a suggestion related to configuration metadata) got seemingly randomly marked as "duplicate" and closed so quickly that the only impression that comes to mind would be that no developer should actually see it and possibly provide technical criticism. While the project maintainers are of course free to mute any topic they dislike, I believe it should be clearly stated in the contribution guidelines if there are certain kinds of contributions which are meant to be rejected based on non-technical reasons.

**Comment by rubenwardy** [comment]
That issue was literally a duplicate of the other issue, due to you being early closed. You spent 80% of the issue moaning about it, and never actually mentioned other relevant meta data. If you keep this up, I *will* ban you from the repo

**Comment by Ezhh** [comment]
There was plenty of discussion on the first of the four issues you've now raised. paramat locked the others because even once a decision, which had everyone else's support, was reached, you wouldn't accept it.

I coded something to resolve an issue that was sitting since 2016. I honestly feel that if you cared about it strongly enough to question my capabilities and to feel you are entitled to further responses after we tried to be patient with you, you should have picked this up sooner and coded your ideal solution yourself instead.

**Comment by paramat** [comment]
![8b284fcbaca2c167d258e04e4658d549--peanuts-comics-snoopy-peanuts](https://user-images.githubusercontent.com/3686677/37886951-a8b668a8-30b6-11e8-9692-a3beb1f95fa4.jpg)

**Comment by zeuner** [comment]
I might have triggered the misunderstanding that exists on this matter
myself, as explained below. If so, please consider my apology.

Still, I do not understand why #6806 would be considered to be a
duplicate of #7110:

#6806 is a main menu issue, as it is also expressed in the tagging.

#7110, on the other hand, is solely related to non-frontend
 logic. When implemented properly, it can even help debugging certain
 strains of mod incompatibilities on setups where the server is
 started from the command line.

While they are related, I think it can help discussing the matters
efficiently to draw the line between the two, since #6806 has
attracted a lot of comments related to the mapgen being chosen before
the mods are selected (and thus unrelated to the non-frontend,
metadata-related side of a possible implementation).

I might have encouraged this kind of misunderstanding because I
brought up non-GUI topics when some participants claimed that #6806 is
impossible to implement, which I do now regret - I should have opened
a separate issue on the non-frontend topic back then.

Anyway, I came to understand that some contributors were (and maybe
are) tempted to avoid a technical discussion by applying their
administrative privileges on the github project. I do hope we can get
past this, but if this is the way how differing points of view are
resolved here, I guess there is nothing I could possibly do about it.

original message follows:

**Comment by jastevenson303** [comment]
Just reading the title this looks like a forum topic.  There's a lot of
issue tickets here already, and this sort of abstract conversation can
really muddy the waters, so to speak.

**Comment by zeuner** [comment]
@jastevenson303: I wouldn't have thought that this type of
"meta"-issue could even come up on this project before. Anyway, issue
ticket quantity can easily get manageable through tagging (which would
also have prevented people accidently considering a metadata-related
ticket a duplicate of a UI-related ticket).

original message follows:
> Just reading the title this looks like a forum topic.  There's a lot of
> issue tickets here already, and this sort of abstract conversation can
> really muddy the waters, so to speak.
>
> On Sun, Apr 1, 2018, 9:44 PM zeuner <notifications@github.com> wrote:
>
> > I might have triggered the misunderstanding that exists on this matter
> > myself, as explained below. If so, please consider my apology.
> >
> > Still, I do not understand why #6806 would be considered to be a
> > duplicate of #7110:
> >
> > #6806 is a main menu issue, as it is also expressed in the tagging.
> >
> > #7110, on the other hand, is solely related to non-frontend
> > logic. When implemented properly, it can even help debugging certain
> > strains of mod incompatibilities on setups where the server is
> > started from the command line.
> >
> > While they are related, I think it can help discussing the matters
> > efficiently to draw the line between the two, since #6806 has
> > attracted a lot of comments related to the mapgen being chosen before
> > the mods are selected (and thus unrelated to the non-frontend,
> > metadata-related side of a possible implementation).
> >
> > I might have encouraged this kind of misunderstanding because I
> > brought up non-GUI topics when some participants claimed that #6806 is
> > impossible to implement, which I do now regret - I should have opened
> > a separate issue on the non-frontend topic back then.
> >
> > Anyway, I came to understand that some contributors were (and maybe
> > are) tempted to avoid a technical discussion by applying their
> > administrative privileges on the github project. I do hope we can get
> > past this, but if this is the way how differing points of view are
> > resolved here, I guess there is nothing I could possibly do about it.
> >
> > original message follows:
> > > Closed #7112.
> > >
> > > --
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/minetest/minetest/issues/7112#event-1511179466
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/minetest/minetest/issues/7112#issuecomment-377834723>,
> > or mute the thread
[...]
