### ISSUE TITLE
Bug: Node Textures Getting Cut In Half

### ISSUE THREAD

**Issue by TekhnaeRaav** [minetest/minetest#7119]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.4.16 release
```

##### OS / Hardware

Operating system: ubuntu 16.04 LTS
CPU: Intel® Core™ i5-2400 CPU @ 3.10GHz × 4 

GPU model: Intel® Sandybridge Desktop 
OpenGL version: 3.3 (Core Profile) Mesa 17.2.8

##### Summary

I have had this happening quite often now; screenshots should describe it pretty well:
![screenshot_20180308_170425](https://user-images.githubusercontent.com/30163969/37238210-4f237fb4-23e7-11e8-8f72-9c02d637ac4f.png)

![screenshot_20180309_160732](https://user-images.githubusercontent.com/30163969/37238223-9a3ce652-23e7-11e8-8430-a598b94a7984.png)
##### Steps to reproduce

It consistently happens with iron bars, but only happens with normal blocks in certain situations, at first I thought it was camera penetration but it also does this from a clear distance.
![screenshot_20180309_161741](https://user-images.githubusercontent.com/30163969/37238274-4be3f7f6-23e8-11e8-9266-39036aa4e5d2.png)
I get flickering of holes through blocks like the screenshot above when I'm walking indoors, all of these holes show up at specific positions and angles so these holes are consistent in a building.

**Comment by SmallJoker** [comment]
The information fields from the issue template would be helpful here.
1) On which Minetest versions can this visual issue be observed?
2) What's your GPU model, driver and OpenGL version?
3) Are there any differences between shaders enabled or not? (like bumpmapping)

**Comment by TekhnaeRaav** [comment]
Fixed. I'm testing shaders and such.

**Comment by TekhnaeRaav** [comment]
It works on my windows machine. Shaders and settings are not doing anything as far as I can tell.

**Comment by TekhnaeRaav** [comment]
Can't figure it out. But it appears to be some problem of the linux version, I rebuilt the game and it was doing the same thing. Windows version still works though.

**Comment by Ezhh** [comment]
Out of interest, and with no idea of whether it could be related, I've had this happen a couple of times on Windows, 0.4.16:
![mt_shattered_nodes](https://user-images.githubusercontent.com/7035183/37246909-2febc098-24aa-11e8-90aa-8975b10f039a.png)
As you can see, my case is somewhat more extreme. :)
(The orange streak is the sun going down)

It only seems to happen after leaving MT running (with me paying it no attention at all) for a really, really long time. It's also incredibly rare, but I get node textures that are either completely missing, or are only half present, cut into triangles, as TekhnaeRaav seems to be experiencing.

**Comment by TekhnaeRaav** [comment]
Eureka! @Ezhh, Your a genius! The restart of my computer fixed the bug. It all makes sense to cause I haven't turn my computer off in a while.
Don't know if this is something that can be fixed, but either way it's to low priority to keep open.
