### ISSUE TITLE
irrlichttypes.h version problem

### ISSUE THREAD

**Issue by sudobash1** [minetest/minetest#712]
I am using irrlicht version 1.8.0 on a Slackware Linux system and compiling minetest from source. I ran into a problem with irrlichttypes.h when it did not define u64. I checked my systems <irrTypes.h> file and found no reference to u64.

To fix this problem I changed the version number it checks for to 1.9 so that it would define u64 for me. It may be a problem with the Slackware package, but as far as I can tell, u64 is not defined in irrlicht 1.8.0

**Comment by nerzhul** [comment]
@sapier dealine
