### ISSUE TITLE
Mainmenu: The current server isn't selected

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7145]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"

```

##### OS / Hardware

Operating system: lubuntu
CPU: amd

##### Summary

When viewing the Join Game tab in mainmenu, the previous selected server is not automatically selected from the list, so the description is missing and you usually can't find the server in the list manually because the address and port aren't shown there.

##### Steps to reproduce

Go to the Join Game tab, click on some server, now the description is shown.
Exit minetest and start it again, you should still have the Join Game tab selected. Now the description is missing and the server is not selected from the list.

**Comment by SmallJoker** [comment]
Similar to #4710, where the update event is not called (entirely). Marked as low priority due to minimal annoyance in relation to other bugs.
