### ISSUE TITLE
Running minetest --run-unittests changes src/unittest/test_world/world.mt, which is not ignored in git configuration

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#7146]
##### Issue type

 - Bug report
##### Minetest version

```
Minetest 0.5.0-dev-debug-c34d28ba (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
##### OS / Hardware

Operating system: Ubuntu Linux 17.10 (artful) 64-Bit
CPU: Pentium(R) Dual-Core CPU E6300 @ 2.80GHz

##### Summary

Running `./bin/minetest --run-unittests` modifies a file `src/unittest/test_world/world.mt`, which is not ignored in git configuration 
```
juozas@xubuntu:~/minetest_dev$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/unittest/test_world/world.mt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	CMakeDoxyfile.in
	CMakeDoxygenDefaults.cmake
	testbm.txt

no changes added to commit (use "git add" and/or "git commit -a")
```
##### Steps to reproduce

Build minetest from git repository copy using command `cmake . -DRUN_IN_PLACE=TRUE -DCMAKE_BUILD_TYPE=Debug -DENABLE_GETTEXT=TRUE` following by `make -j [processor count]` or `make -j [processor count+1]`
Run `./bin/minetest --run-unittests` followed by `git status` to get output like above.

**Comment by nerzhul** [comment]
hmm, we cannot ignore this file as it's used by unittests themselves

**Comment by 4w** [comment]
Why not add “unittest” as forbidden world name and have the world generated in user context and not in application context?

**Comment by nerzhul** [comment]
@4w there is no sense in what you say for a simple reason: a unittest should refect a user case :)

But yes we can add it to .gitignore for cumfort

**Comment by 4w** [comment]
> a unittest should refect a user case

Therefore only use files the user should change and do not change versioned files from the application itself.

**Comment by pauloue** [comment]
This is not fixed. You can't ignore files in the repository.

The `world.mt` could be created by the unittest.

**Comment by nerzhul** [comment]
we can add it to .gitignore

**Comment by pauloue** [comment]
It's already in .gitignore but this has no effect since it's in the repository.
