### ISSUE TITLE
Invisible chat error messages

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7150]
##### Issue type

 - Bug report
 
##### Minetest version
0.5.0-dev-debug-359c8f82 (Linux)

##### OS / Hardware

Operating system: Lubuntu 17.10
CPU: intel

##### Summary

Error messages are shown in chat as invisible line:
![errormsg](https://user-images.githubusercontent.com/3192173/37603590-3ed56f14-2b8f-11e8-8839-0483995a64e1.png)

##### Steps to reproduce

Use the lua chatcommand mod to produce error messages ingame, as shown on the screenshot

**Comment by SmallJoker** [comment]
> See screenshot

This is not an instruction on how to reproduce this error locally. Would you please be so nice and bisect to find out since when this problem occurs.

**Comment by HybridDog** [comment]
I'm bisecting it. The failure happens for each error message.
I noticed that there's one invisible line even when the message contains the newline character \n.

**Comment by HybridDog** [comment]
I've bisected it successfully, 0ebaed430ad5cd2523d78d2e2c051576e948fe13 is the responsible commit.

The failure happens for each error message.
I noticed that there's one invisible line even when the message contains the newline character \n.

**Comment by HybridDog** [comment]
I've bisected it successfully, 0ebaed430ad5cd2523d78d2e2c051576e948fe13 is the responsible commit. @nerzhul 

The failure happens for each error message.
I noticed that there's one invisible line even when the message contains the newline character \n.

**Comment by Dumbeldor** [comment]
Yes you're right @HybridDog 
Thanks 👍

**Comment by SmallJoker** [comment]
#7289
