### ISSUE TITLE
Better Code Documentation

### ISSUE THREAD

**Issue by TMcSquared** [minetest/minetest#7153]
##### Issue type
 - Documentation issue
 
##### Summary
Looking through the MT code, I see that it seems to have a huge lack of basic documentation inside the code. This may discourage some new contributors because they have no idea what anything does or where it goes. I suggest using a commenting technique described [here](https://standards.mousepawmedia.com/csi.html), it will allow for an easier learning curve for newer contributors and will hopefully make the project better as a whole.

**Comment by rubenwardy** [comment]
I agree that documentation is a problem, but I don't think that technique is a solution and it may actually be harmful.

Instead, algorithms and weird code should be commented to explain why and sometimes how, complex methods documented to explain what they do, and classes should be documented to explicitly define scope. There should also be more comprehensive overview documentation, the one on the development wiki is grossly out of date

**Comment by TMcSquared** [comment]
I understand that alot of the overview docs and the wiki are out of date,
But I'm confused why you said CSI commenting could be harmful.

**Comment by rubenwardy** [comment]
On my original read, I thought it was talking about commenting above every line with psuedocode. Instead it's actually just talking about commenting the reason behind things which is a much better practice.

Over commenting decreases readability, so there does need to be a balance

**Comment by paramat** [comment]
I think CSI goes too far, i agree with better comments though.

`The core standard is this: comment everything.`
Commenting every line verbosely in a way reduces code readability because code lines are now spread out and there is visually more to take in.
`You can translate your program into another computer language much quicker.`
I think our comments can be language specific since we are highly unlikely to rewrite in another language. Those looking at the code are likely to have a very basic familiarity with C++.

The following isn't necessary, the code is self explanatory. Our current approach is to comment the non-obvious.
```
/* Divide our items among 17 boxes.
 * We'll deal with the leftovers later. */
int items_per_box = floor(items/17);
```

**Comment by TMcSquared** [comment]
> It isn't that simple to decide what is obvious and what isn't.

True, but even a short description of what a function does and why it needs to be there would be super helpful most of the time.

**Comment by nerzhul** [comment]
@lisacvuk i agree with your point. It's like adding unittests, it take time but it's useful for posterity

**Comment by nerzhul** [comment]
also setters and getter are generally trivial, this should be done on big function. Also maybe big functions should be refactored

**Comment by paramat** [comment]
I should add i do support the basic idea of CSI, just not how far it takes it.
There is a lot of old code by c55 that has lots of comments making it clear what is being done step by step, it's extremely helpful for devs and saves a lot of time and headache trying to work out what is going on, at little effort by the code writer who already understands what they are doing.

So i support more and more descriptive commenting.

**Comment by HybridDog** [comment]
If I remember correctly, when I made the digging time limit fix (https://github.com/minetest/minetest/pull/5560), I didn't know about the instant torch digging mechanism because wasn't explained/commented, fortunately somebody found the problem: https://github.com/minetest/minetest/issues/5728

**Comment by nerzhul** [comment]
@paramat complex code should be commented when complexity needs it. Also have doxygen comments on non trivial functions (i.e. setters/getters) can permit to improve it too.

I'm not sure a rule is always needed, but at least a huge coredev effort can be.
Maybe we can add a rule for external contributors to ensure external contribution has the good code quality for coredev, and coredev should add it everytime they can

**Comment by paramat** [comment]
More descriptive commenting is widely supported. Old code will have comments added when it is touched, contributions will need good commenting.
Assume this is MT policy, so no point keeping this open.
