### ISSUE TITLE
Holding F5 triggers down or sneak

### ISSUE THREAD

**Issue by wilkgr76** [minetest/minetest#7156]
##### Minetest version

```
Minetest 0.4.16 (Windows) USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 ST
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel i5-6400 (3.3GHz)

##### Summary

When fly is on, holding the F5 key, the player will go down. When fly is off, the player will sneak while the F5 key is pressed.
Video: https://youtu.be/0UbRS5WU30o (I didn't press shift at all during the video, and no mods that are enabled for this world change player properties)

##### Steps to reproduce

1. Open Minetest and start a game
2. If applicable, give yourself fly
3. Press and hold F5

Config file: https://pastebin.com/WMBYy0PA
(the keymap stuff is pretty distributed unfortunately, but no duplicates as far as I can tell)

**Comment by HybridDog** [comment]
I can't reproduce it (on linux).
```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```
Operating system: Lubuntu 17.10
CPU: intel

**Comment by SmallJoker** [comment]
Can you observe the same behaviour after renaming your `minetest.conf` file (as backup) so Minetest will use the default settings on the next start? Do you use any special keyboard layout?
Same as HybridDog I cannot reproduce this issue on my QWERTZ/Linux machine.

**Comment by paramat** [comment]
Can't reproduce with my own configuration, can't see anything weird in your config file.

**Comment by rubenwardy** [comment]
What keyboard do you have? (qwerty, azerty, etc)

**Comment by wilkgr76** [comment]
@SmallJoker I can, same behaviour 🙁 
@rubenwardy QWERTY

**Comment by mtango688** [comment]
I've tested it on both Ubuntu 16.04 and the latest Windows 10 Home on my laptop, and it seems likely to be somethng specific to your system (as I cannot reproduce it). If you press and hold F5, it does the same thing on both of my systems (it quickly cycles through the different debug display modes).

Linux: Minetest 0.5.0-dev (latest git)
Windows: Minetest 0.4.16 (release ver)

**Comment by HybridDog** [comment]
wilkgr76, could you test it with a changed key binding? 
https://github.com/minetest/minetest/blob/9fcc0c1217fcd3acabaa11239631de10032fa126/minetest.conf.example#L385

**Comment by wilkgr76** [comment]
I rebound debug to the Y key. That worked as expected (i.e. Y key only toggles debug info), but F5 still causes sneaking. Not sure why this is.

My apologies everyone!

**Comment by HybridDog** [comment]
If F5 does shift, you could try holding F5 and typing some text to test if it only happens in minetest.

**Comment by paramat** [comment]
@wilkgr76 no apology needed, it was worth opening an issue for multiple people to check and consider this, could have found a valid bug. Thank you.
