### ISSUE TITLE
Sounds do not stop playing

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#7160]
##### Minetest version
Since commit 9293d8e, #7063

##### Steps to reproduce
1) Place `main_menu.ogg` into `MINETEST_DIR/sounds/` (may need to be created)
2) Place another multiple seconds long track `demo_sound.ogg` into `mods/test_mod/sounds/` **+**
```Lua
-- init.lua
core.register_on_joinplayer(function(player_)
	core.after(2, function(player)
	minetest.sound_play(
		"demo_sound",
		{
			pos = player:get_pos(),
			--to_player = player:get_player_name(),
			gain = 0.2,
			max_hear_distance = 16,
			--loop = true,
		}
	)
	end, player_)
end
```
  * .. or place `fire:permanent_fire` in front of you
3) Join the world, main menu sound keeps playing
4) Leave world and the fire/demo_sound keeps playing

@nOOb3167

**Comment by nOOb3167** [comment]
Tentative fix pushed to branch, but investigating further:
https://github.com/nOOb3167/minetest/tree/smg

If this was the problem, very unfortunate, code in my more recent sound related PR cleans up ALsource resources by unique_ptr and would have avoided the bug.

**Comment by nerzhul** [comment]
i mark it as blocker to don't forget it for a fix for a future release

**Comment by nOOb3167** [comment]
As far as I can tell bug no longer reproduces after the fix.
Should this be rebased on top of #7158 ?

**Comment by SmallJoker** [comment]
#7161 merged
