### ISSUE TITLE
Failed account creation to contribute on wiki

### ISSUE THREAD

**Issue by nshiff** [minetest/minetest#7162]
##### Issue type

 - Bug report
 
##### Minetest version

```
http://wiki.minetest.com/wiki/Minetest_Wiki
```

##### OS / Hardware

Operating system: Ubuntu 
CPU: Intel

##### Summary

Failed account creation to contribute on wiki

##### Steps to reproduce

I was going to poke around and see if I could fix a few broken image links. I think Junglewood Planks is the primary offender. But, the wiki informed me that I needed to be logged in to upload an image. I tried to create an account, but I got an ugly error: 

`
Fatal error: Call to a member function xpath() on boolean in /srv/users/serverpilot/apps/minetestwiki/public/extensions/ConfirmEdit/Asirra.class.php on line 44`

**Comment by rubenwardy** [comment]
Wrong place, make requests here: https://forum.minetest.net/viewtopic.php?f=3&t=10473
