### ISSUE TITLE
Add Nyan Cat, but with other name

### ISSUE THREAD

**Issue by stas730** [minetest/minetest#7163]
##### Issue type
 - Feature request
 
##### Minetest version

```
43f98eb47cabd3b8a2f5d2f9e7ae3bb6cf52fd6c
```

##### OS / Hardware

Operating system: N/A
CPU: N/A

GPU model: N/A
OpenGL version: N/A

##### Summary

Nyan Cat was removed some time ago. Many players have installed nyancat mod because they didn’t want Nyan Cat to be removed.
##### Steps to reproduce

Nyan Cat can be added again, but name must be changed to avoid trademark issues. "Nyā Cat" is example ("nyā" is Japanese word, so it can’t be trademarked).

**Comment by rubenwardy** [comment]
:-1:

**Comment by Ezhh** [comment]
Great big massive :-1: 
(also shouldn't this issue be in minetest_game?)

**Comment by stas730** [comment]
@Ezhh, true.

**Comment by stas730** [comment]
@Ezhh, https://github.com/minetest/minetest_game/issues/2099
