### ISSUE TITLE
Mgcarpathian: Odd lacunarity value, base noise needs tuning

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7165]
Just saw this, missed this on review:
`np_base (12, 1, v3f(2557, 2557, 2557), 6538, 4, 0.8, 0.5),`
The error is that lacunarity is less than 1.0, so each additional octave has a wavelength larger than the previous. Octave1 has wavelength 2557, octave2: 2557 * 2, octave3: 2557 * 4, octave4: 2557 * 8.
The intention was probably wavelengths of 2557, 2557 / 2, 2557 / 4, 2557 / 8? @vlapsley 

I suggest we alter the default noise parameters for base noise to:
`np_base (12, 1, v3f(2557, 2557, 2557), 6538, 1, 0.8, 0.5),`
so just 1 octave, or:
`np_base (12, 1, v3f(2557, 2557, 2557), 6538, 4, 0.8, 2.0),`
to correctly halve wavelength for each octave.
@vlapsley which do you prefer?

Since noise parameters are stored for a world this won't affect existing maps.

Luckily also see code below:
```
				// Base terrain
				float ground = noise_base->result[index2d];
...
				// Final terrain level
				float mountains = hills + ridged_mountains + step_mountains;
				float surface_level = ground + mountains + grad;
```
The ground noise has a small scale (1 node of variation) so altering this noise will not result in any noticeable change to terrain character, only 1 node of height change every few thousand nodes. The variations of mountains always drown out ground noise variation.

@vlapsley would you be ok with this? If so i can make a PR.

**Comment by paramat** [comment]
If the base noise variation is intended to be +-2 nodes every 2557 horizontal nodes, and other noises drown this out, there doesn't seem to be any point in having base noise at all, it could be fixed at 12 and increase performance.
However, if the intention was to have 4 octaves from 2557 down to 2557 / 8 = 320 nodes then that is borderline noticeable and base noise should probably be kept.

**Comment by vlapsley** [comment]
Hi @paramat I'll do some testing over the next couple of days and get back to you on the option I'd prefer.

**Comment by paramat** [comment]
I think my preference would be to fix it at 12 and remove the noise, as +-1 node variation on a scale of 2557 nodes will be unnoticeable. Looking at the hills / mountains noises they are never at zero over large areas so those noises seem to provide the small variations in the flatlands instead.

**Comment by paramat** [comment]
The identically-behaving noise stated with lacunarity 2.0 would be:
`np_base (12, 0.512, v3f(20456, 20456, 20456), 6538, 4, 1.25, 2.0),`
So octave1 here is a variation of +-0.512 nodes over a scale of 20456 nodes, which seems somewhat pointless.

With a 1 octave version of the current:
`np_base (12, 1, v3f(2557, 2557, 2557), 6538, 1, 0.0, 2,0),`
This is +-1 node of variation over a scale of 2557 nodes, i think this would be unnoticeable even if mountain noises were zero to make base noise visible.

However i love the terrain as it is so certainly don't want to make any noticeable change.

**Comment by vlapsley** [comment]
> I think my preference would be to fix it at 12 and remove the noise

After testing all of the options I agree with this statement. It's simple and gives an almost identical map.

I'm guessing somewhere in my initial development I had a different value for `np_base`, but after tinkering so much the value became somewhat redundant.

**Comment by paramat** [comment]
Ok thanks, i'll add it as a simple parameter value so that this '12' is still settable.

**Comment by paramat** [comment]
PR #7209

**Comment by paramat** [comment]
#7209 merged.
