### ISSUE TITLE
Mgvalleys noise parameters need tuning

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7166]
@Gael-de-Sailly a task for you. I could do this myself but i would much rather the mapgen's original author tunes it. This is for 0.5.0, so you have 2-3 months.

Mgvalleys is capable of being much more impressive if tuned, see posts in the forum.This won't affect existing worlds as noise parameters are stored per-world.
Also, it looks possible we might at some point have an ability to choose from a list of preset mapgen parameters, so the original set of parameters could then be an option.

I realise now that i and we were too relaxed about allowing it to be merged it in the state it was in (the same goes for mgcarpathian, both needed more development and work before merging), the river systems are on too small a scale, tending to go around in small loops. Altering this will also improve the rest of the terrain that is built around the rivers.

I'm not sure if this is possible and i could be wrong, but there seems to be a lack of smooth terrain anywhere? Rough, lumpy terrain everywhere is not good and it often looks ugly for the flatter terrain, it's good to have a balance of smooth and rough terrain. Is there a way to add in some smooth terrain in places? This could be done by reducing number of octaves or persistence for certain noises.

**Comment by Gael-de-Sailly** [comment]
I've started working on better mapgen parameters some days ago. This is what I have for now:
(still needs tuning)
```
mgvalleys_np_rivers = {
   lacunarity = 2
   persistence = 0.5
   octaves = 6
   offset = 0
   scale = 1
   flags = eased
   spread = (512,512,512)
   seed = -6050
}
mgvalleys_np_valley_profile = {
   lacunarity = 2
   persistence = 1
   octaves = 1
   offset = 0.3
   scale = 0.3
   flags =
   spread = (512,512,512)
   seed = 777
}
mgvalleys_np_valley_depth = {
   lacunarity = 2
   persistence = 1
   octaves = 1
   offset = 7
   scale = 6
   flags =
   spread = (512,512,512)
   seed = -1914
}
mgvalleys_altitude_chill = 110
mgvalleys_np_inter_valley_fill = {
   lacunarity = 2
   persistence = 0.7
   octaves = 7
   offset = 0
   scale = 1
   flags =
   spread = (512,512,512)
   seed = 1993
}
```
![screenshot_20180325_121951](https://user-images.githubusercontent.com/6905002/37873986-3005604c-3027-11e8-87f7-a7312fbd6cc1.png)
![screenshot_older](https://user-images.githubusercontent.com/6905002/37255267-1e0598d6-254a-11e8-89b4-9134fb904a13.png)

Rough and lumpy terrain, and small rivers, are what I like, but I know many players may dislike it. That's the purpose of mapgen presets, allowing players to choose the parameters that look good for them.
I started coding for this too, the GUI menu is mostly done; however not sure you will like it. Branch [mapgen_params_dialog](https://github.com/Gael-de-Sailly/minetest/tree/mapgen_params_dialog).

**Comment by paramat** [comment]
The rivers can remain small (narrow) i'm just referring to the scale of the structure of the river systems.
One tip: each time you double the 'spread' of the noise that determines the river system structure, add another octave to it, this will preserve the 'twistiness' of the structure.

I think i'd be ok with rough terrain everywhere if the detail didn't go down to tiny scales like 2 nodes. For example on the left of the 1st screenshot is rough and lumpy in a good way because the finest detail is around 8 nodes in scale. Anyway i'll leave it to you as i don't have much experience of this mapgen.

**Comment by paramat** [comment]
This is low priority, players like it as it is and it's good enough.
