### ISSUE TITLE
Lighting oddities

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#7175]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-bcd22fc3
```

##### OS / Hardware

Operating system: Windows 7
CPU: Intel Core i3-2120

GPU model: ATI X800GTO 256MB
OpenGL version: OpenGL 2.1

##### Summary
Well, I've tried to repeat a mirror room trick in minetest (no sunlight access), it looked nice in the end, but it raised few eyebrows concerning the differences in lighting, it does not mirror that well apparently (especially roof, notice big difference in brightness, slightly on slabs), I've also used //inspect from worldedit to check light level in few places. Here is original that inspired me - : https://i.redd.it/mj1m6dnck5o01.png, it seems MC has this weirdness as well, but less visible (?)

So general question: is this intended? Can provide this world if needed.

![default](https://user-images.githubusercontent.com/16494741/37973492-4a97fd6c-31e3-11e8-9b74-a4aaa868e770.png)

**Comment by weqqr** [comment]
Yes, the bottoms are intentionally darker than the tops.
https://github.com/minetest/minetest/blob/fd9f195fcc2e4e592dbad3290876486eb08318b2/src/mesh.cpp#L49-L53

**Comment by paramat** [comment]
^ Yes :)

**Comment by 4w** [comment]
> Yes, the bottoms are intentionally darker than the tops.

What the hell?

**Comment by Calinou** [comment]
> What the hell?

This is very common in engines that use less "real-time" lighting method; it is called [fake contrast](https://doomwiki.org/wiki/Fake_contrast). It would look much worse if one were to remove it (see Minetest screenshots from 2011-2012).

**Comment by paramat** [comment]
Yes just place a node and look at each face, each is shaded differently.

**Comment by 4w** [comment]
>  It would look much worse

Disagreed.

**Comment by HybridDog** [comment]
related: https://github.com/minetest/minetest/pull/6165
