### ISSUE TITLE
Key to enable faster digging in creative mode

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7177]
##### Issue type

 - Feature request
 
##### Minetest version
```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### Summary

The issue regarding the digging speed in creative mode reappeared: https://forum.minetest.net/viewtopic.php?f=5&t=19835
I think adding a key to switch digging modi in creative mode (similar to Linuxdirk's suggestion) could solve this problem. Players could use the key (or key combinations) to switch to usual digging speed (to punch nodes), click-digging (when building, everything is dug as fast as torches) and very fast digging (when mining, massive amount of nodes are removed at once).
This can obviate creative's wield hand overriding because to punch nodes the survival mode's digging speed can be used.

**Comment by Wuzzy2** [comment]
I'd argue this is more a failure of the game for not insta-breaking all blocks.

In MCL2, all blocks insta-break in Creative Mode.

**Comment by Wuzzy2** [comment]
Hmmm, but the key idea still seems interesting, if you want to turn OFF hyper-fast digging, that sure sounds useful.
But I am worried that we are starting to add way too many keys in Minetest … :-/

**Comment by LoneWolfHT** [comment]
What would be nice is allowing mods to do this by giving modders all of the player's pressed keys. Then this could be done with a mod

**Comment by paramat** [comment]
:-1:
Could cause too much network traffic of rapid individual 'remove node's.
... Which in turn causes problematic rapid individual-node map accesses on the server, the lua voxel manipulator should be used for bulk node changes.
If a player wants to rapidly remove nodes it's best done in bulk using some sort of bulk-dig tool that uses the lua voxel manipulator.

**Comment by HybridDog** [comment]
> I'd argue this is more a failure of the game for not insta-breaking all blocks.

You wouldn't be able to push a mesecons button in creative mode.

> But I am worried that we are starting to add way too many keys in Minetest … :-/

Key combinations can be added to avoid mixing up very important and not so important keys, e.g. ctrl+f for fast digging.

> What would be nice is allowing mods to do this by giving modders all of the player's pressed keys. Then this could be done with a mod

It can only be done properly with CSM (Client Side Modding) because of the network delay. Unfortunately arbitrary key combinations for CSM are not yet implemented.

> Could cause too much network traffic of rapid individual 'remove node's. […]

Mods already add tools which dig instantly. I think that the map accesses are not very frequent because digging nodes is approximately O(n) whereas making big holes is O(n³), with n representing the perception of how many nodes have changed (e.g. a 1000 nodes long stripe of missing desert sand is more salient than a 10x10x10 big hole).

**Comment by benrob0329** [comment]
>You wouldn't be able to push a mesecons button in creative mode.

This isn't a thing anymore, and mods should not rely on digging to activate something.

**Comment by paramat** [comment]
1 year bump, any core dev support?

**Comment by HybridDog** [comment]
> This isn't a thing anymore, and mods should not rely on digging to activate something.

Since when is punching a node something that needs not always be possible?
https://github.com/minetest/minetest/blob/cff1e9ca273be6d0719f18ac72622f7b7f7dbdb0/doc/lua_api.txt#L6250-L6254
