### ISSUE TITLE
Promoting Minetest on Facebook

### ISSUE THREAD

**Issue by anaufalm** [minetest/minetest#7178]
Wow, I've seen trailer of this game, and this is a really cool alternative to Minecraft game, very interesting I really like it. May I share this game? So that people (gamers) know more about this cool game. I will promote it on facebook possible. ;)

**Comment by rubenwardy** [comment]
Sure! This type of thread should be made on the [forums](https://forum.minetest.net) btw

**Comment by anaufalm** [comment]
Btw before that, I just want to ask permission from PO that my actions are allowed, then I will create a thread in the forum about the promotional results. ;)
Do you allow me for this, @rubenwardy ?

**Comment by SmallJoker** [comment]
It is absolutely forbidden to advertise or promote Minetest on any social media platform or publicize any results about the progress. Such an important and potentially controversial forum topic requires an official approval of the entire development group which may take up to twelve months. Notice the irony and do what you like.

**Comment by anaufalm** [comment]
Of course not, Not like that. I only help you to promote this game, that's it. this promotion only introduces your game to facebook, like this: (btw this is my page)
https://www.facebook.com/goodnews.os/photos/365705647263700

**Comment by rubenwardy** [comment]
Most important line in SmallJoker's response:

> Notice the irony and do what you like.

You do not have to have permission to post about something on Facebook

**Comment by anaufalm** [comment]
Okey thanks, I dont do it.

**Comment by rubenwardy** [comment]
again:

> do what you like.
> You do not have to have permission to post about something on Facebook

you're perfectly allowed to promote on Facebook

**Comment by rubenwardy** [comment]
This game certainly needs promotion, so good luck :D 

Make sure to join our forums and socialise, this is a small but fairly friendly community

**Comment by anaufalm** [comment]
Ohh really? then i will promote it soon. :D :man_cartwheeling:

**Comment by anaufalm** [comment]
Look at this @rubenwardy, people love this promotion. Since ad has runs for two days, it's already reached + 7K people, and it's still going up. There are two more days left for this ad. :D

https://facebook.com/story.php?story_fbid=373652096469055&id=364705867363678&ref=page_internal
![screenshot_2018-04-01-13-39-10-535_com android chrome](https://user-images.githubusercontent.com/35919168/38170529-31acb112-35b2-11e8-81e2-ddc47dd18bd7.png)
*Sorry for the screenshot in mobile view, I just checked and notice you.

**Comment by sofar** [comment]
:+1: - really appreciated!
