### ISSUE TITLE
Missing terrain mesh near edges of screen with higher-than-default FOV.

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#718]
To reproduce:
1. Set fov = 120 in the minetest.conf file.  I was also able to reproduce at fov=90 and fov=180.
2. Enter the game, set your draw range high or use "enable full viewing range"; my v_range was at 240 when testing.
3. After terrain has loaded, turn slowly.  You'll notice that terrain disappears near the edge of your field of vision (as if the engine assumes it's no longer on-screen and is ignoring your FOV setting).  This mostly affects terrain that is further than about 30 nodes away.
4. Note that the terrain appears normal you do NOT have a fov setting in your minetest.conf.

**Comment by paramat** [comment]
Temporary fix for this issue has been merged https://github.com/minetest/minetest/commit/1ec1a605d664b42a034cecb9f2e768fab3d738d4
However the maths can probably be improved.

**Comment by paramat** [comment]
I guess this needs testing again due to the temporary fix.

**Comment by est31** [comment]
Nah, lets close it its fixed imo

**Comment by paramat** [comment]
I agree, since this issue is so old.
