### ISSUE TITLE
Various OpenGl version strings

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7180]
##### Issue type

 - Bug report

##### Minetest version
```
Minetest 0.5.0-dev (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: Lubuntu 17.10
CPU: intel

GPU model: intel
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.3.6 - padoka PPA
OpenGL version string: 3.0 Mesa 17.3.6 - padoka PPA

##### Summary

minetest shows that I have OpenGL 3.0, but it's the version string.
https://www.opengl.org/discussion_boards/showthread.php/184551-Compatibility-or-Core-profile?s=734374db4b9a7c5287403f319bd3fb45&p=1260682&viewfull=1#post1260682
If I didn't misunderstand that, the core profile string shows the actual OpenGL version, whereas the version string shows the version up to which all deprecated functions are supported. The version shown by minetest is therefore not the actual OpenGL version.

##### Steps to reproduce

look at minetest window title when playing

**Comment by sfan5** [comment]
I'm not sure whether this issue is even worth fixing or even <i>looking at</i>.

**Comment by Wayward1** [comment]
Well, it would be nice if it actually displayed the correct information, otherwise why have it at all? This is particularly problematic for bug reports, where the OpenGL version is specifically requested.

**Comment by nOOb3167** [comment]
Irrlicht uses a compatibility profile OpenGL context.
The information correctly conveys which OpenGL version is used.

https://github.com/zaki/irrlicht/blob/master/source/Irrlicht/CWGLManager.cpp#L402
  either wglCreateContext is called, producing a compatibility context, or
  wglCreateContextAttribs_ARB is called with requested OpenGL version 1.1, producing a compatibility context
https://www.khronos.org/registry/OpenGL/extensions/ARB/WGL_ARB_create_context.txt
> If the requested OpenGL version is less than 3.2,
    WGL_CONTEXT_PROFILE_MASK_ARB is ignored and the functionality of the
    context is determined solely by the requested version.
