### ISSUE TITLE
Underground liquids

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#7181]
##### Issue type
 - Feature request
 
##### Summary
It would be very good if it was possible to specify as many biome specific liquids as wanted for underground caves, in the same way that this can currently be done for surface level liquids. Currently it seems we are limited to only two liquids for caves (typically water and lava).

**Comment by paramat** [comment]
Good idea, currently large cave liquids are hardcoded to the mapgen aliases 'water' and 'lava' with a distribution hardcoded to an unsettable 3D noise.
This would integate them into the Biome API, cave liquids could just use the 'node water' node of the biome.
Mgv6 large cave code already has separate code for mgv6 so mgv6 will not be affected.

**Comment by paramat** [comment]
Actually it will be necessary to keep backwards compatibility and useful to have the old option which is difficult to simulate using biomes. So perhaps best to add a biome field "node_cave_liquid" and have old behaviour as fallback.

**Comment by Ezhh** [comment]
That's what I originally imagined it working like, so sounds good to me. :)

**Comment by paramat** [comment]
#7192 merged.
