### ISSUE TITLE
Using #import in GCC is deprecated and issues several warnings.

### ISSUE THREAD

**Issue by mtango688** [minetest/minetest#7184]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev-ce87310
```

##### OS / Hardware

Operating system: Linux
CPU: AMD

GPU model:
OpenGL version:

##### Summary

Multiple warnings like this:

```
In file included from /home/mtango/minetest/src/localplayer.cpp:22:0:
/home/mtango/minetest/src/event.h:22:2: warning: #import is a deprecated GCC extension [-Wdeprecated]
 #import "irrlichttypes.h"
  ^
```

##### Steps to reproduce

Make and observe using gcc.

**Comment by rubenwardy** [comment]
0a8ca598915a906e665141dc79fc0c1bbab8cc91

**Comment by nerzhul** [comment]
oops sorry :) i missed the include on my clion. Thanks

**Comment by Mei-char** [comment]
im having the same warning
