### ISSUE TITLE
Metatable support for vectors

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7196]
##### Issue type
 - Feature request

##### Summary
I suggest to make use of Lua metatables (http://www.lua.org/manual/5.1/manual.html#2.8) in vectors.

So that this code works:

```
v = vector.new(1,2,3) 
v2 = vector.new(2,3,4)
v3 = v + v2
```

Where `v3 = v + v2` is equivalent to `v3 = vector.add(v, v2)`.

Basically this is just for syntactic sugar and to make code a bit more readable.

**Comment by paramat** [comment]
`v3 = vector.add(v, v2)` is clearer, `v3 = v + v2` suggests these are scalars and there's no visual indication that the + is a vector addition, so is more likely to confuse.
So i'm wary of this.

**Comment by stujones11** [comment]
In other languages it is commonplace to use operator overloading like this and it can be quite useful for more complex expressions like `v = v1 + v2 * v3 - v4` for example.

I agree, however, this is low priority and certainly not worth any performance penalty, which I suspect there might well be, if only very slight.

**Comment by rubenwardy** [comment]
It's really not clearer

**Comment by benrob0329** [comment]
https://github.com/minetest/minetest/commit/12504a18ec5b76df037482ea2cf435d8c320efbc

**Comment by Wuzzy2** [comment]
So does this count as official rejection?

**Comment by DS-Minetest** [comment]
Here are some old related PRs: #810 (#811) (#923) #925 (#974)
As you can see, there's mostly not that much conversation.

When did the core defs start leaving PRs open for multiple years?

**Comment by Wuzzy2** [comment]
TBH, I have no problem with this being rejected, it's really not important.

**Comment by paramat** [comment]
> When did the core defs start leaving PRs open for multiple years?

When we had no time to review them =)

If they are just waiting for review that is surely better than closing them for no reason?
We only close PRs that are disapproved or long term neglected.

**Comment by paramat** [comment]
> Basically this is just for syntactic sugar and to make code a bit more readable.

Seems less readable and more confusing to me :-1:

**Comment by benrob0329** [comment]
> Seems less readable and more confusing to me 
Most people I talk to agree that using standard arithmetic operations is far _less_ confusing because it's consistent with other data types and greatly simplifies complex operations. The full functions would remain so you can continue using them if so inclined :-)

I would like to see some actual metrics, perhaps even outside of MT and with multiple versions of Lua to know if it is even worth considering now or in the future.

**Comment by rubenwardy** [comment]
> I would like to see some actual performance metrics, perhaps even outside of MT and with multiple versions of Lua to know if it is even worth considering now or in the future.

My pr to do this showed a 4% slowdown. This was with creating a new object each time. I propose an alternative implementation that is class based and does not copy each time

**Comment by paramat** [comment]
> using standard arithmetic operations is far less confusing because it's consistent with other data types

And therefore is more likely to be confused with scalars. I agree it is visually simpler and clearer but is also more prone to confusion, `v3 = v + v2` does not suggest vectors and suggests scalar addition.
So i guess some benefit, some disadvantage. Removed my -1, am neutral.

**Comment by Wuzzy2** [comment]
Unsubscribing ...

**Comment by Desour** [comment]
This can be closed btw..
