### ISSUE TITLE
Pausing game triggers a warning: invalid use of background without a size[] element

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#7197]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev-debug-392e80e3 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 17.10 (artful) x86_64, Kernel 4.13.0-38-generic 
CPU: Pentium(R) Dual-Core  CPU E6300 @ 2.80GHz, 2 Cores, 64 bits
```
juozas@xubuntu:~/minetest_dev$ lscpu 
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               23
Model name:          Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz
Stepping:            10
CPU MHz:             1932.500
CPU max MHz:         2800,0000
CPU min MHz:         1603,0000
BogoMIPS:            5600.07
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            2048K
NUMA node0 CPU(s):   0,1
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm xsave lahf_lm pti retpoline tpr_shadow vnmi flexpriority dtherm
```

##### Summary

Pausing the game while in anything but minimal game triggers a warning: `WARNING[Main]: invalid use of background without a size[] element`
~~Since I din't see this happen in minimal game I'm not sure if this is engine issue or subgame issue, I've also posted an issue there too (minetest/minetest_game#2101)~~ It's confirmed by @rubenwardy  this is engine issue, the other issue is closed.
Adding --info to command line shows more details:
```
2018-04-04 16:51:47: INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"
2018-04-04 16:51:47: WARNING[Main]: invalid use of background without a size[] element
2018-04-04 16:51:47: INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"
```
##### Steps to reproduce

1. Load single player game (minimal not affected) or connect to server (only single player tested)
2. Pause game and see warning in console, if --info is in command line you may also see `INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"` before and after the warning, as detailed in minetest/minetest_game#2101

**Comment by rubenwardy** [comment]
background[] should be supported for formspecs without a size[] tag

**Comment by paramat** [comment]
Please fix, this is driving me nuts. Looks bad so blocker.
