### ISSUE TITLE
Warnings since Kubuntu 18.04

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#7198]
##### Issue type

 - Build issue
 
##### Minetest version

```
Minetest 0.5.0-dev-392e80e3
```

##### OS / Hardware

Operating system: Kubuntu 18.04
CPU: Intel 2 Duo P8700 (2) @ 2.53z

GPU model: Intel® GM45 Express Chipset 2
OpenGL version:

##### Summary

Since the Update to Kubuntu 18.04 I get the following warnings at build time.
see attachment.

[warnings.txt](https://github.com/minetest/minetest/files/1876222/warnings.txt)

**Comment by nerzhul** [comment]
@SmallJoker lua lib is already up to date and mature

**Comment by JPRuehmann** [comment]
Strange on my 16.04 Systems I get no errors.
But since they´re only warnings It will be no problem I think.
Thanks,

**Comment by rubenwardy** [comment]
#10238
