### ISSUE TITLE
Minetest deletes the contents of outside directories instead of the symlinks that point ot them when deleting worlds

### ISSUE THREAD

**Issue by AlexYst** [minetest/minetest#7201]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.4.16
```

##### OS / Hardware

Operating system: Debian 9
CPU: Irrelevant

##### Summary
If a symbolic link is present in a world directory and Minetest deletes that world, it'll delete the contents of the symbolically linked directory and not the symlink itself. Because the symbolic link doesn't get deleted, this also prevents the world's directory from being properly deleted, so you end up with a world directory containing only the symbolic link to the freshly-emptied outside directory.

##### Steps to reproduce
0. Start a new world.
1. Symbolically link something into that world's directory for use in multiple worlds (for example, a particular `worldmods` directory).
2. Delete that world, expecting the symbolically-linked directory to still be there for use in other worlds.
3. Check your linked directory to find all the mods (or whatever) you had in the linked directory have been erased with no chance of recovery. The linked directory itself still exists, but the contents do not.

**Comment by nerzhul** [comment]
haha @celeron55 did you remember we talked about the removal ? :)
