### ISSUE TITLE
Store weak pointers to things in Lua references and crash gracefully

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7203]
Currently accessing a player object after a player logs off causes a segfault, which isn't good.

Can also add is_valid() to all objects.

**Comment by raymoo** [comment]
:+1: for is_valid, with the added request that an invalid object never becomes valid again (for example by checking IDs directly that might be reused)

**Comment by nerzhul** [comment]
@rubenwardy the problem is we store a dereferenced pointed in LuaRef, exact ?

**Comment by rubenwardy** [comment]
We store a pointer which is deleted outside of the holding class, rather than storing a weak ptr

**Comment by nerzhul** [comment]
rubenwardy, yeah it's my point. The lua reference should be dropped or the pointer set to nil. This sync state is not easy, and player ref should never be stored outside of the callback functions

**Comment by raymoo** [comment]
How was this solved?

**Comment by sfan5** [comment]
ObjectRefs have always been invalidated when the object was deleted so I don't know how this bug could ever have existed:

https://github.com/minetest/minetest/blame/09f9e465e760cb8fd791222405a9e5e68a676ba0/src/script/cpp_api/s_base.cpp#L393
https://github.com/minetest/minetest/blame/0.4.15/src/environment.cpp#L1890
