### ISSUE TITLE
Null bytes in minetest console output when running with trace option in command line

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#7205]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev-debug-077f2311 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 17.10 (artful), 64 bit
CPU: Pentium(R) Dual-Core CPU E6300 @ 2.80GHz, 2 cores

##### Summary

Running minetest with trace output while redirecting everything to a file then upening it in a text editor, in some of them (e.g. gedit) you might see a warning about non-printable characters stored in the produced text file 
![minetest-trace log -darbastalis - gedit 2018-04-05 14 57 10](https://user-images.githubusercontent.com/6626242/38364497-a4dd40a2-38e1-11e8-86eb-a4e18690e883.png)
From screenshot it looks it's caused by a function that writes `VERBOSE[ConnectionSend]` with null bytes to output (stdout/stderr) stream
_VERBOSE[ConnectionSend]: con(17/1) INFO: sending a reliable packet to peer_id 2 channel: **\00** seqnum: 108_

##### Steps to reproduce

1. Run latest minetest build from git with trace command line option, redirect everything to a file
```
cd /path/to/minetest
./bin/minetest --trace 2>&1 | tee /path/to/trace.log
```
2. Open text file in text editor such as gedit, see a warning about null bytes in the file.
`gedit /path/to/trace.log`

**Comment by HybridDog** [comment]
https://github.com/minetest/minetest/blob/077f231111082272359a916c3e41049aaf699151/src/network/connectionthreads.cpp#L366-L369

**Comment by JDCodeIt** [comment]
peer_id is a session_t which is a u16 which is an unsigned short, so the insertion operator outputs the \00 representation. Unless it's important to know the type of the variable being output, casting to (u32) should make it a human-readable "0" in that case.

**Comment by SmallJoker** [comment]
9877a1a2
