### ISSUE TITLE
Add function to load map but not generate

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7206]
Now and then modders want to do something in an unloaded place, e.g. test if there's a teleporter node.
A function `minetest.make_map_loaded(pos1[, pos2])` which loads the map at pos1 (or from pos1 to pos2 if pos2 is not nil) could be added to allow getting nodes there. In comparison to minetest.emerge_area the map is not generated.
Currently doing this is already possible using vmanip [like there](https://github.com/HybridDog/minetest-teleporters/blob/cdecf1e4b223b57c6144e1784810df44e0c08e5a/teleporters/init.lua#L24-L26), but l think vmanip is not supposed to be used for map loading only.

**Comment by paramat** [comment]
I can see some usefulness, as the LVM is often used to do this but is possibly a hacky way to do so, and this usage is not a documented and dedicated API.

**Comment by paramat** [comment]
#8023 merged.

**Comment by sorcerykid** [comment]
As a modder, I think this is a much welcome addition. I've been planning to extend my mailbox mod to allow for delivery of items to registered mailboxes anywhere on the map via a public mail drop at spawn. However, this would require loading a mapblock with the corresponding mailbox node. Having a minetest.load_area method would be a much cleaner implementation than VoxelManip.
