### ISSUE TITLE
Add in ability to turn off chat on mobile

### ISSUE THREAD

**Issue by cordial-cobra** [minetest/minetest#7219]
**Issue type:**
 -  Feature request
 
**Summary:**
There are clients who play minetest on a mobile device (i.e. phone or tablet) and they currently don't have the ability to turn off chat for when they are recording a video (some servers require that they do this if they are going to record). Another reason to have the ability to turn off chat would be for phones that have a small screen size and large chunks of text said by a player hogging the screen and preventing them from being able to see what they are doing. I have played MT on a phone and having the chat hog the screen is a tad annoying while trying to build something as it blocks the view of what I am working on.

I suggest something like a little icon of a few lines in the same place as the other options under the little gear icon that is on the upper right side of the screen.

**Comment by paramat** [comment]
@srifqi

**Comment by srifqi** [comment]
So, it will be inside "gear" toolbar alongside fast, fly, etc?

I have suggestion for textures:
![chat_hide_btn](https://user-images.githubusercontent.com/4017302/38713059-816389f6-3ef9-11e8-9ed3-67b6598d7d43.png)
^ hide chat
![chat_show_btn](https://user-images.githubusercontent.com/4017302/38713068-8408e854-3ef9-11e8-9c60-cd1696b33f01.png)
^ show chat
I just re-use "chat" button texture and add lines to tell that it means chat messages.

**Comment by cordial-cobra** [comment]
@srifqi: Makes sense and I think those textures would work perfectly since they make sense in terms of what they are supposed to do.
