### ISSUE TITLE
Increasing draw range

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7222]
Compared to other voxel games, Minetest's view range is pitifully low. Mesh generation also causes lots of stutter.

For example, Build a World - another game made in Irrlicht - has a massive view range such that you don't tend to see unloaded blocks. (Just image search or youtube for it)

I've not touched any related code yet so can't say how this could be done. I imagine it will need a combination of things including using the GPU pipeline better, better parallelism, and such. I believe celeron55 claimed his client-requesting blocks code from farmap caused visible performance improvements in terms of block delivery.

Paging @numberZero and @lhofhansl

**Comment by paramat** [comment]
@celeron55

**Comment by Fixer-007** [comment]
More details? Farmap itself is a dirty hack :) If you improve rendering to smth like usable 240, it will not be needed anyway.

**Comment by rubenwardy** [comment]
@Fixer-007 it's the map sending part of it, not the farmap part of it. The farmap branch has purportedly improved map sending code

**Comment by rubenwardy** [comment]
lol

**Comment by stujones11** [comment]
Needs more labels =)

**Comment by rubenwardy** [comment]
> Needs more labels =)

Agreed

**Comment by lhofhansl** [comment]
I think the GPU portion is fine right now (in terms of performance at least :) ). What is slow in Minetest is generating/retrieving blocks, getting them to the client, and rendering them there (not the the GPU part).

I'm not sure where exactly this is slow, though. I've tried various hacks in the past to prioritize blocks that would be most immediately seen by a player, but that's kind of hack. I think the Freeminer guys have optimized the network protocol.

@celeron55 's cited patch is pretty big.

**Comment by lhofhansl** [comment]
When I did the "real zoom" feature I found that the performance it's quite independent from the actual number of blocks sent or retrieved.
For the same volume i.e. far out with small fov and closer and larger fov, the closer and larger fov renders much faster. So at least in part this has to do with how we pick and send the relevant blocks to the server.

**Comment by lhofhansl** [comment]
I think one thing we can do immediately is increasing `max_simultaneous_block_sends_per_client` which default to 10.

That means that only 10 blocks can outstanding for any given client. 
At range 200 that means we need to do at least `2/3 * pi * (200/16)^3 * (1 - cos(72 / 2))/10` = 78 roundtrips to load the scene.

At range 240 it's already 135 roundtrips. At range 300 is 264. And so on.

This will *especially* bad over higher latency network links.
Imagine a 100ms RTT. Now we're talking 7.8s for range 200, or 13.5s for 240. Or a whopping 26.4s at range 300.
I've seen very slow loading on some public servers.

Ideally we would two things:
1. measure the RTT and bandwidth of the link and adjust automatically. (Like TCPs sliding windows sizing algorithm)
2. measure the size distribution of the packets and adjust the queue limit so it's a smooth stream of roughly equal size packets.

**Short term,** I think we can safely up this to 20 or even 40. At higher numbers there will be a few big packets followed by a pause and a big packet again, which leads to client stutter.

**Comment by rubenwardy** [comment]
**Bump**

I can see two new steps that may be worth taking:

* Create standard *automated* benchmarks for profiling render performance based on distance. Also benchmarks for important rendering pipelines such as block sending and mesh generation.
* Investigate to see if celeron55's map block sending branch increases performance
* Investigate only sending single nodes rather than whole blocks on changes to reduce network bandwidth

I'm not sure how it is best to do this, really. For the automated benchmarks, you could make a script to download several test worlds then monitor render time (CPU and GPU) whilst flying through them with continuous forward
