### ISSUE TITLE
Add "on_metadata_inventory_shiftclick" callback

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#7238]
##### Issue type
 - Feature request

##### Summary
An optional callback would be added that would be called when items are shift-clicked in the node's formspec. I'm not sure if the listring element in the formspec itself should override this or not, but I'm leaning towards yes.

The function's parameters would be node position, source list and the index of the itemstack in the source list, and the function should return the name of the destination list in the node's metadata.

There could be an equivalent for detached and player inventories as well, but I'm not sure about this either as I haven't had much experience with those.

I'm not sure how easy this is to implement as the formspec may well be a wholly separate thing from the node and its metadata, and the node callbacks that currently deal with inventories are only called when the item's destination is known to be in the node. There may well be a better way of handling this.

**Comment by SmallJoker** [comment]
:-1: Mobile users can't shift-click, so none of the mechanisms using that callback would work unless there's a control button available which acts as shift key. It may also overcomplicate the GUIs, which are meant to be simple and intuitive.

> the node callbacks that currently deal with inventories are only called when the item's destination is known to be in the node

If you move an item stack from a detached inventory to a node, then the `allow_take` detached inventory callback will be run, then `allow_metadata_inventory_put` (node def), `on_take`(detached) and finally `on_metadata_inventory_put` (node def). In the `allow_*` callbacks it's always possible to limit the amount of items which can be moved.

**Comment by paramat** [comment]
What is the usecase?

**Comment by MineWitherMC** [comment]
F.e., there might exist a complicated machine that has several lists/slots and this callback might check the item and return the needed list.
Also, if this is done it could be better to return a pair like `return "list", slot`.
Good idea. :+1:

**Comment by paramat** [comment]
rdococ
> An optional callback would be added that would be called when items are shift-clicked in the node's formspec

'in' or 'into'?
I can't yet see this as useful enough to add.

**Comment by Wuzzy2** [comment]
I don't like this idea, too complicated. Shift-click is a convenience feature handled by engine only. I always thought of a shift-click to be completely transparent to the server, changing this is not good. Having a callback for this just makes this unneccessarily complicated.
Sofar's argument of potential UI abuse is also a very strong one.

I'm not saying shift-click is perfect, but any improvements made to it should be made directly in the engine.

:-1:

**Comment by SmallJoker** [comment]
Devs are opposed to this idea. Closing.
