### ISSUE TITLE
Control F5 debug info shown to user via server

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#7245]
##### Issue type

 - Feature request

##### Summary
>There is good reason for a server to be able to stop players seeing position / direction (some challenges need these hidden) and pointed node (you can then see which nodes are disguised traps or dangers).
>
>I suggest HUD flags that can control what information players can access.
We already have a priv for wireframe but this should perhaps be a HUD flag instead.
>
>Much information is harmless to know: MT version, seed, FPS, view_range, range_all, profiler graphs etc. I see no harm in allowing players to access those, they are very useful for players and are not dev-only information, and being able to access these does not give a bad impression at all.
>
>Perhaps a new HUD flag should control accessing position / direction / pointed nodename.

Source: @paramat at https://github.com/minetest/minetest/issues/4556#issuecomment-324456399

I would like that feature too, that will be nice to have for making survival harder on some servers (with position info allowed by default). Some relevant discussion here too https://github.com/minetest/minetest/issues/4556

**Comment by ClobberXD** [comment]
Would it make sense to implement "flavours" like those for CSM restrictions?

**Comment by SpaghettiToastBook** [comment]
While I personally like the proposal in #4556 the most, even just having a way for mods to control this would be a large improvement.

Here's another good comment from #4556 (author: @C1ffisme):
> @paramat
> 
> > Much information is harmless to know: MT version, seed, FPS, view_range, range_all, profiler graphs etc. I see no harm in allowing players to access those, they are very useful for players and are not dev-only information, and being able to access these does not give a bad impression at all.
> 
> Most of those are things that would be very good to give players (Although, view_range should appear as View Range in non-debug situations) except for seed. If someone has the seed of a world, it's likely that they can replicate a server's world for themselves, and then you could write your own mod for spotting ores or other useful things.

**Comment by Warr1024** [comment]
This is actually a significant issue for my game (NodeCore).

There are some things in the world that have subtle visual differences that players are meant to eventually notice, wonder about, and start paying attention to.  I also have a WAILA-type feature that shows players the _description_ of things they encounter, but it's purposefully vague or indistinct in some cases where players are supposed to look for these subtle clues.  Instead, a number of players are looking at the debug info, which both makes those differences really explicit, and is also misleading (i.e. the internal names do not evolve as the descriptions do).

The only workaround I have right now is to instruct players to turn off the F5 debug info, as it contains spoilers, but there's no good way to deliver that warning to all players, the temptation can be hard to resist, and many players may naively have it on by default (e.g. players who use it a lot for their own mod work) without realizing how it can spoil gameplay.

Overall, there's also a consistency argument in favor of this.  If we allow restricting zoom, minimaps, and CSM's, then we should really be able to restrict the debug info.  Individual flags would be ideal, but even a stopgap, like disabling this for players who don't have the debug priv (like the way wireframes work) would be helpful.

**Comment by paramat** [comment]
:+1:
