### ISSUE TITLE
Reverse function for `minetest.serialize_schematic`

### ISSUE THREAD

**Issue by paly2** [minetest/minetest#7247]
##### Issue type

 - Feature request
 
##### Summary
Schematics are an extremely useful feature and they have a large number of possible uses. It is possible to define a schematic using a Lua table and serialize it into MTS format, but it is quite surprising that there exists no function to do the reverse thing (reading a MTS file and returning a Lua table). It is possible to use `loadstring(minetest.serialize_schematic("file_name", "lua", {}))`, but it would be much more efficient to have a function that directly fills a Lua table (deserialization seems very resource-intensive).

Why would we want to read a schematic into a table? It would allow, for example, to edit the schematic without placing it on the map. "Editing" could involve replacing nodes with others, reducing its size, and a number of other operations that could save a lot of resources by being done before placing the schematic. It could enable writing advanced functions to place large schematics without making the server freeze by splitting them into parts and placing the parts one by one (e.g., in a globalstep).

EDIT: most of edition can currently be done by loading the schematic on a `VoxelManip`, but it makes it harder to recreate another schematic after it has been edited. Maybe that could be solved using a function doing the reverse thing from `minetest.place_schematic_on_vmanip`, i.e. reading the VoxelManip and writing a schematic in MTS or Lua format?

**Comment by paramat** [comment]
It is possible to convert a .mts file into a lua table, this code apparently does it:
```
        local building = minetest.get_modpath("default") .. "/schematics/jungle_tree.mts"
	local str = minetest.serialize_schematic(building, "lua",
		{lua_use_comments = false, lua_num_indent_spaces = 0}) .. " return(schematic)"
	local schematic = loadstring(str)()	
	print(dump(schematic))
```

**Comment by paly2** [comment]
It does work, but the problem is that it involves reading the MTS file, serializing into a string, and parsing the string into a table, whereas it should be possible to write an API function that loads the schematic into a Lua table once it is loaded instead of writing a string describing the table. The effect would be the same, but the efficiency would be drastically better, which is important for very large schematics (and large schematics are mostly the ones you might want to be able to edit before placing them on the map, e.g. to split them into chunks).

**Comment by paramat** [comment]
Ok i agree.

**Comment by paramat** [comment]
:+1:
