### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by Wayward1** [minetest/minetest#7258]
##### Issue type

 - Build issue

##### Summary

The Android build fails since 87ad4d8 with
```make[2]: *** No rule to make target `jni/../jni/src/content/contentdb.cpp', needed by `obj/local/armeabi-v7a/objs-debug/minetest/jni/src/content/contentdb.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....```

**Comment by SmallJoker** [comment]
63ca604
