### ISSUE TITLE
New chat-command to list all online players with a given priv

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7266]
##### Issue type

 - Feature request
 
##### Minetest version

```
0.4.16
```
##### Summary

This feature request aims to add more functionality to the `/privs` command. If the param passed with the command is, let's say `-priv`, the command accepts another param which is a priv. Now, the command should return all online players with the given privs. Here's an example for clarity:
- `/priv player` returns the privs of "player"
- `/privs -priv interact` returns all online players with the `interact` priv

##### Potential Use-cases
- Can be used by admins to check if moderators are online (if yes, then how many).
- Can be used by moderators to check which players have ____ priv.

**EDIT: This extra feature is being implemented as a separate `/hasprivs` command, which is usable only by players who are moderators or higher**

**Comment by SmallJoker** [comment]
I like the idea but `-priv` is a valid name.

**Comment by ClobberXD** [comment]
`-priv` is just a place-holder to demonstrate the concept. Hopefully, I or anyone else would come up with a better name for that param.

**Comment by srifqi** [comment]
New command: `/hasprivs` (?)

Also, only _online_ players?

**Comment by ClobberXD** [comment]
@srifqi A separate command is a great idea, but I feel that players would be more accustomed to the `/privs` command. But on the other hand, parsing a special `@priv` seems to unnecessarily complicate the command, and a new command is a better solution in this respect. I request everyone to share their views on this, please. If we're going with a new `/hasprivs` command, I could make the PR myself too...

> Also, only _online_ players?

I feel that iterating through only the players who're online seems sufficient.

Let's say for example, that a player on a popular server executes `/hasprivs shout` - on execution of that command the server will start lagging profusely for literally the next few minutes, and later, player's chat will be flooded with thousands of names. This is, of course, undesirable to say the least... :)

**Comment by Ezhh** [comment]
It would need to be only currently online players or it would be ridiculous.

It's also worth considering if this is a command everyone should be able to use by default. I don't want players being able to instantly join my server and check with one command if someone is online who has the ban priv, for example. 

I'd really see this command more as an admin tool than a tool for players to use.

**Comment by ClobberXD** [comment]
> It's also worth considering if this is a command everyone should be able to use by default.

I'm also planning to implement another feature for the /priv command. A player would be able to check other players' privs _only_  if that player has certain privs. The check is enabled / disabled by a boolean setting in minetest.conf, and the privs to match are also defined by another setting in the conf.

**Comment by paramat** [comment]
Adding settings makes it quite complex, is it worth it? What are the usecases?

**Comment by Ezhh** [comment]
I don't think it needs a setting. Just go with either of:

1. Only players with a specific priv can use the command (I don't mind either way if it's a current or new priv), or
2.  Everyone can run the command, but it only works for privs that the user has themself.

**Comment by paramat** [comment]
Ok. If the feature is seen as useful by server admin perhaps it can require the 'server' priv? I think whatever is done needs support as being useful.

**Comment by ClobberXD** [comment]
> Only players with a specific priv can use the command
 Hmm... maybe a new priv just to allow / disallow using this feature?

> Everyone can run the command, but it only works for privs that the user has themself.

If a player with interact and shout uses this command, they can only see interact and shout for everyone else, not taking into consideration any other privs that they might have? <-- Is this what you mean?

> If the feature is seen as useful by server admin perhaps it can require the 'server' priv?

That's a good idea, if it's an admin-only feature anyways.

Looking at the discussion, I feel that a new command might do good, the `/privs` can stay untouched with its simple original implementation. So `/hasprivs` it is? Shall I start working on it?

**Comment by ClobberXD** [comment]
Update: I've started working on `/hasprivs`. As of now, execution requires kick and ban privs. Only players who are moderators or better can use this command.

**Comment by Ezhh** [comment]
It would make more sense to attach it to basic_privs than ban and/or kick, since basic_privs is a priv about managing privileges.

**Comment by ClobberXD** [comment]
@Ezhh, could you please elaborate? Do you mean that a new priv has to be registered and added to basic_privs?

**Comment by srifqi** [comment]
@ClobberXD, basic_privs is a privilege. What @Ezhh means is instead of needing ban/kick privilege, the user need basic_privs.

**Comment by ClobberXD** [comment]
Ah, I see... OK, I'll change it.

**Comment by SmallJoker** [comment]
#7336 merged.
