### ISSUE TITLE
My clientside translations are not working...

### ISSUE THREAD

**Issue by theFox6** [minetest/minetest#7298]
##### Issue type
 - Bug report
##### Minetest version
```
Minetest 0.5.0-dev-21c72075-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Debian
CPU: Intel i5

##### Summary
My clientside translations are not working...

I tried to find out why and added this output to client.cpp:
```
void Server::sendMediaAnnouncement(session_t peer_id, const std::string &lang_code)
{
	verbosestream << "Server: Announcing files to id(" << peer_id << ")"
		<< std::endl;

	// Make packet
	NetworkPacket pkt(TOCLIENT_ANNOUNCE_MEDIA, 0, peer_id);

	u16 media_sent = 0;
	std::string lang_suffix;
	lang_suffix.append(".").append(lang_code).append(".tr");

	warningstream << "lang code: " << lang_code << std::endl;
	warningstream << "lang suffix: " << lang_suffix << std::endl;
```

And then in the log:
```
2018-05-05 15:01:09: WARNING[Server]: lang code: 
2018-05-05 15:01:09: WARNING[Server]: lang suffix: ..tr
```
##### Steps to reproduce
play singleplayer (couldn't try it on servers)
I tried different in game language settings

**Comment by juozaspo** [comment]
Your build doesn't include gettext (`USE_GETTEXT=0` in version output), you need to add `-DENABLE_GETTEXT=TRUE ` to cmake command line then rebuild minetest. Doing so solves many translation problems.

**Comment by theFox6** [comment]
That worked I have no problems now, thank you for your help.
