### ISSUE TITLE
Ignore item has rendering problems

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7304]
##### Issue type
 - Bug report
 
##### Minetest version
```
4ccd18d5ec7dec02366a2221526b2fc0ed7b16b6
```

##### OS / Hardware
OS: GNU/Linux
CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
GPU model: Haswell-ULT Integrated Graphics Controller
OpenGL version: Mesa 17.3.7

##### Summary
The wielditem image of `ignore` is broken. When you wield `ignore`, you see really strange things in your wield hand, it changes when you walk around. You might see animated water, random node textures, nodes with weird stretching and in generall another mess.

The inventory image is just blank (fully transparent) but should be `ignore.png`.

Also, the tooltop of `ignore` is not matching item's `description`.

In contrast, the `air` item works perfectly fine.

This is a regression from 0.4.16.

##### Steps to reproduce
* `/giveme ignore`
* Look in hotbar at item
* Wield the item, walk around and look at your wieldhand
* Look in inventory at item

**Comment by TeTpaAka** [comment]
46bbacee95b8cc68b7e531232a319ed46c2e1560 introduced the regression.

**Comment by paramat** [comment]
Of course, players should never be able to wield it in the first place :) Maybe your PR can prevent the giving of ignore?

**Comment by Wuzzy2** [comment]
The real problem is that `ignore` can be an item in the first place and thus stored in inventories and thus wieleded. `/giveme` is not the only way, mods might accidentally spawn `ignore` as well.

Basically this is just for having sanity checks.

The biggest problem is that `ignore` has an invisible inventory image now, so if `ignore` accidentlly drops as an item entity somehow, it's almost impossible to detect now.
Of course, `ignore` should not be carried as item or dropped as item, but when it does anyway, it should be detectable.

The commit above looks very small, but it does seem to have broken the `ignore` definition from `builtin`. It seems the bug it attempted to fix came at a price. Maybe revert it and find another way to suppress the error message?

**Comment by Wuzzy2** [comment]
@HybridDog: Your commit https://github.com/minetest/minetest/commit/46bbacee95b8cc68b7e531232a319ed46c2e1560 introduced this bug.

**Comment by HybridDog** [comment]
Sorry, I didn't see this. So registering ignore to the core should still be possible and the problem lies where NodeDefManager::set is called without testing if the node is ignore.
https://github.com/minetest/minetest/blob/master/src/nodedef.cpp#L1226-L1238
