### ISSUE TITLE
Expose F5 pointed value (perhaps to CSM only)

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7317]
##### Issue type
 - Feature request

##### Summary
I want a simple Lua API function that returns the same value as "pointed" in the F5 debug menu.

**Comment by SmallJoker** [comment]
Is already doable with our current API:

https://github.com/minetest/minetest/blob/a292d19fd0726cdd192469fbfc5f85770d5819e3/doc/lua_api.txt#L4768-L4786

Whereas pos1 is the player's camera position (see Y camera offset) and pos2 is pos1 + a vector with the length of the tool specific range and the direction which can be calculated using the player's vertical and horizontal look angle.

**Comment by tacotexmex** [comment]
This does not necessarily render the exact same result as what "pointed:" has.

**Comment by paramat** [comment]
Maybe i misunderstand, but 'pointed thing' can be used to do this already, it returns the 'under' position, then you get that node and display its name.
I can't see a reason to duplicate this.

**Comment by SmallJoker** [comment]
@tacotexmex Raycast is also used in C++ to get the pointed thing. When it hits a selection box, it'll return the node position, entity reference or nothing. The code lines you highlighted is calculated by the client only, so exposing it to the client Lua API is possible, but not for the server Lua API. Also keep in mind that Android players must not point to the node they would like to dig - they can punch any node in sight (afaik).

@paramat They're requesting an API to get the pointed thing without a callback. Pointed thing is the result of a player action, such as right-clicking or punching a node/entity. Outside of those callbacks it's more difficult than calling a single function but it's doable.
I support the "Possible close" not because pointed_thing already exists - but rather because our Raycast function cannot get much simpler than it is right now.

**Comment by raymoo** [comment]
@tacotexmex When does it not match?

**Comment by Wuzzy2** [comment]
Yes, there is `pointed_thing`, but AFAIK only the data structure. I don't think we have a getter for the player's current `pointed_thing`, don't we?

Does using raycasting make 100% sure I really get the player's (!) pointed_thing with respect to the current pointing range (also important), and not something weird? Are there any gotchas the Lua coder has to keep in mind?

Off topic:
> Also keep in mind that Android players must not point to the node they would like to dig - they can punch any node in sight (afaik).

Really? So they can theoretically dig nodes at thausands of node-lengths away, as long it's visible? This sounds like a mega cheat. Can they also point (and attack) at players very far away, as long they just aim correctly (with the crosshair)?

**Comment by raymoo** [comment]
@Wuzzy2

One gotcha I can imagine is that raycasting on the server may not match the player's clientside look direction, which is only frequently 10 times per second.

The Android bug allows infinite reach, but I think what @SmallJoker meant is that on Android you can dig any node within reach on the screen, not just the one in the center. Anticheat will prevent the infinite reach bug on Android from being anything other than a UI bug, and it might not be too bad after the changes to speed anticheat that were supposed to make it handle speed overrides better.

**Comment by tacotexmex** [comment]
> Does using raycasting make 100% sure I really get the player's (!) pointed_thing with respect to the current pointing range (also important), and not something weird?

This.

**Comment by paramat** [comment]
> Pointed thing is the result of a player action,

Oops sorry of course.

**Comment by tacotexmex** [comment]
Still possible close?

Let me add an example of why I'm personally are having a hard time without this feature (Click on the image):

[![Click on the image](https://i.imgur.com/4ORv4y1.png)](https://imgur.com/a/oDysHsx)

**Comment by paramat** [comment]
See above:
> I support the "Possible close" not because pointed_thing already exists - but rather because our Raycast function cannot get much simpler than it is right now.

**Comment by tacotexmex** [comment]
I see, but what about the scenario illustrated in the clip above? Can proper raycasting even adress that issue?

**Comment by paramat** [comment]
I expect raycast can do what you want as SmallJoker wrote, but i'm not an expert on it.

**Comment by SmallJoker** [comment]
It's actually a bit longer than I imagined but absolutely doable in Lua.
License: CC0
```Lua
-- 4.0f in Game::processPlayerInteraction
local hand_range = core.registered_items[""].range or 4

local function get_pointed_thing(player)
	local eye_y = player:get_properties().eye_height
	local offset_1st, offset_3rd = player:get_eye_offset()

	local pos1 = vector.add(player:get_pos(), offset_1st)
	pos1.y = pos1.y + eye_y

	-- Get actual tool range
	local wield_item = player:get_wielded_item()
	local tool_range = hand_range
	if wield_item:is_known() then
		tool_range = wield_item:get_definition().range or hand_range
	end

	-- Shoot into the look direction
	local look_dir = player:get_look_dir()
	local pos2 = vector.add(pos1, vector.multiply(look_dir, tool_range))

	local raycast = core.raycast(pos1, pos2, true, false)
	local pointed = raycast:next()
	if pointed and pointed.type == "object"
			and pointed.ref == player then
		pointed = raycast:next()
	end
	return pointed
end

local time = 0
core.register_globalstep(function(dtime)
	time = time + dtime
	if time < 1.5 then
		return
	end
	time = time - 1.5

	for i, player in pairs(core.get_connected_players()) do
		local pointed_thing = get_pointed_thing(player)
		local pointed_node = nil
		if pointed_thing and pointed_thing.type == "node" then
			pointed_node = core.get_node(pointed_thing.under)
		end
		core.chat_send_player(
			player:get_player_name(),
			dump(pointed_node)
		)
	end
end)
```

**Comment by stujones11** [comment]
That is quite a bit of code for something that is incomplete and may be inconsistent with the client when the client already has this information.

However, using this information only really makes sense to the client but could be useful for a 'identify' type mod (as depicted above).

Perhaps 'Expose F5 pointed value to CSM' would be a more reasonable request?

**Comment by tacotexmex** [comment]
For reference I managed to improve my raycasting code in the [https://github.com/tacotexmex/pointlib](pointlib) mod to a satisfactory degree.
