### ISSUE TITLE
Allow customizing colors by CSM

### ISSUE THREAD

**Issue by Sires0** [minetest/minetest#7321]
##### Issue type
 - Feature request
 
##### The Idea
Allow customizing colors by CSM of: Chat(additional: just not errors) and item descriptions [Also any other strings that can be coloured I didn't quote here]

#### Reason
Many people complain things like: "Colored chat CSM makes the chat unreadable(I know that the function that allows this CSM was removed, just quoting)"
And some people(#7078) would like colors in their items to help to differentiate easily from each mod, but if each mod set it's own color things would get a chaos, IMO it's better letting the user decide the colors.

#### The api function
I'd suggest some csm api function such as:
`minetest.override_colours(color_type, override_function)`
Where color_type is from where this string comes, like: "chatmsg" or "itemdescription"
override_function is just a function that would return false(if nothing is changed) or a table in the format {pos = color}, where pos is the index of where to insert a colorstring(inserting normal text wouldn't be allowed, but this may be another discussion), example:
{0: RED_COLOR, 15: WHITE_COLOR}

Ik this will get low priority tag but maybe one day a good person may implement it :P

**Comment by rubenwardy** [comment]
What's the use case here?
