### ISSUE TITLE
Add package update detection without entering ContentDB

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7327]
I'd like to add a "notification" for when updates are available for packages.
This would probably be in the form of a badge on the content tab, ie: "Content (3)" to indicate that there are 3 updates available. I'm not sure how the API should work though.

**Background**

Packages downloaded using the content installer store a release ID in their meta data. This release ID is compared against the release ID for that package in the package list to detect updates. release IDs are currently global and not per package, as they are a primary key.

**Implementation**

Use the `/api/updates/` endpoint to get the latest release id of all packages, and then compare against local versions.

* Example: https://content.minetest.net/api/updates/?protocol_version=43&engine_version=5.8.0-dev-debug
* API docs: https://content.minetest.net/help/api/#releases

**Comment by nOOb3167** [comment]
Possible 5th option:

Minetest queries for 'all releases made since $time'.
Server keeps database table with two fields:
| UNIX_TIMESTAMP | RELEASE       |
| 1234534234           | doors v1.2.6 |
| 2318321315           | mesecons v3|
'SELECT release where UNIX_TIMESTAMP greater than xyz' is expected to be a fast operation.

This seems a very natural arrangement so similar data might already be collected?

In case where the $time is very far back, or there are many updates, have the server deny the request.
For this case, allow clients to query for release updates via a Bloom Filter (datastructure with overhead due to false positives, but preserves privacy by hiding which keys are being checked from the server).

**Comment by rubenwardy** [comment]
I've realised that some of my suggestions won't work, as whilst releases are *created* in order, they may be *published* out of order. This will happen if release A is approved after release B. I'll have a look into your suggestions though, at some point

**Comment by ChristianSirolli** [comment]
What about the mods that its users have modified, say for example the mods configuration is a `config.txt` file or something like that? There is the issue in that not all mods handle configuring the same; some have a file called `config.txt`, others have variables in the `init.lua` that users change, and I have seen one where the configuration file has an underscore in the front of the name, like `_config.txt`. I imagine that that will be difficult to handle. What do you think?

**Comment by rubenwardy** [comment]
Those mods can't be supported, and should be changed

Not that isn't part of this issue - the menu supports updating already

**Comment by rubenwardy** [comment]
It looks like checking for updates since the last check will be the best bet. Ideally this should be asynchronous, as if the check was a long time ago it may need to redownload the package list. I'd also like to take into account that it should probably be moved in to the engine at some point to allow a CLI

I think I will make a package cache in the client folder, and use it to store the important meta and locations of installed packages. This will speed up update detection

**Comment by mase76** [comment]
I think, a filter for showing only updatable or installed  content would be helpful for now.

**Comment by rubenwardy** [comment]
I've added a super fast API for getting the latest versions of all packages to ContentDB. Locally, it only takes 30ms to run. On the production server, it takes 100ms probably due to network latency.  The result is only 60KB

https://content.minetest.net/api/updates/?protocol_version=43&engine_version=5.8.0-dev-debug
