### ISSUE TITLE
Reflections without shaders

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7328]
##### Issue type

 - Feature request

##### Summary

There's a way to show pseudo reflections using mip mapping: http://blog.mecheye.net/2018/03/deconstructing-the-water-effect-in-super-mario-sunshine/
Maybe this can implemented in minetest for water and also for other nodes, e.g. steel blocks.

**Comment by TMcSquared** [comment]
This would be interesting, perhaps as an optional feature.

**Comment by rubenwardy** [comment]
This isn't for reflections, but for a water rippling effect.

Shaders are not slow or intensive. It is not possible to turn off shaders on a modern GPU. Minetest just implements them badly, which is what causes the performance loss
