### ISSUE TITLE
Mapgen valleys mapgen flags cannot be disabled

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7335]
This occurs in 55bb1938c17dfdb065a0eead97ce8094518b9049 but also in 0.4.16 stable and i expect long before.

To reproduce:

Use advanced settings to set 'nohumid_rivers' to disable that mapgen flag.
Start a new world and enter, then exit.
Shutdown MT.
Look at .conf and see:
`mg_valleys_spflags = altitude_chill,nohumid_rivers` (correct)
Look at the world's map_meta.txt:
`mgvalleys_spflags = altitude_chill, humid_rivers` (incorrect)

Discovered while working on #7277 , disabling variable river depth did not have any effect on mapgen.

Mgvalleys code is still structured a little differently to other mapgens, i'll try moving some stuff out of 'private' part of the class. The 'Flagdesc' is different too, static and not present in the header.

**Comment by mtango688** [comment]
Maybe I'm missing something, but I'm finding no reference to "mg_valleys_spflags" outside of the example conf file.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/53d5b3ea40ce1c18540a378c5f71f4e1e60dbec8/builtin/settingtypes.txt#L1766

**Comment by mtango688** [comment]
Okay, so how does the code know what those flags are?

**Comment by paramat** [comment]
It reads the defaults set in the .cpp file and adds any alterations made by .conf or advanced settings.

**Comment by mtango688** [comment]
So, the issue (in mapgen_valleys.cpp) is basically:
`
	settings->getFlagStrNoEx("mgvalleys_spflags",        spflags, flagdesc_mapgen_valleys);
`

Right?

**Comment by paramat** [comment]
Possibly not, as the flags do not work if the settings code is changed to be exactly like other mapgens (i tried above). So it seems to be some obscure cause.

**Comment by mtango688** [comment]
Okay, well just to test it out, I tried creating a test world with the setting (in minetest.conf):

`mgvalleys_spflags = altitude_chill,nohumid_rivers`

In the resulting map_meta.txt, it included the following:

`mgvalleys_spflags = altitude_chill, nohumid_rivers`

Maybe it really is just a matter of the name.

**Comment by paramat** [comment]
Ah, i'll try using .conf, this may be a problem with advanced settings.

**Comment by paramat** [comment]
I had the same bug happen using .conf.
What version of MT did you use?

**Comment by mtango688** [comment]
Minetest 0.5.0-dev-22df02d (Linux)

**Comment by mtango688** [comment]
I just verified that the above behavior I reported also works in:

Minetest 0.5.0-dev-53d5b3e (Linux)

**Comment by mtango688** [comment]
In case it matters here's a complete list of the settings I had when I tested:

```
mg_name = valleys
mg_flags = nodungeons
mgvalleys_large_cave_depth = -160
mgvalleys_massive_cave_depth = -10000
mgvalleys_spflags = altitude_chill,nohumid_rivers

```

**Comment by paramat** [comment]
Same version i am on. Will try your .conf settings.

**Comment by paramat** [comment]
@srifqi any ideas?

**Comment by paramat** [comment]
Ok now it is working when setting mgvalleys_spflags in .conf. Working with either 1 line or the 4 lines added, weird.

**Comment by paramat** [comment]
Since this works from .conf but not from advanced settings, and if this can't be fixed before 5.0.0, the options should be removed from documentation and advanced settings while still allowing the flags stored in map_meta.txt to have effect. I'll do this before 5.0.0.

**Comment by numberZero** [comment]
It is `mgvalleys_spflags` in the source but `mg_valleys_spflags` in the settings list.

**Comment by paramat** [comment]
Thanks! =D

**Comment by paramat** [comment]
My fault https://github.com/minetest/minetest/commit/8b1f8e99cf860625ebd20531ab7f3e8316a66b51
I corrected 'mg_valleys_' to 'mgvalleys_' but didn't correct it for '_spflags'.
Will fix.
You are a hero.

**Comment by paramat** [comment]
PR #7495
