### ISSUE TITLE
Approval label usage: Include core dev author's own approval

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7341]
PRs require the 'agreement' of 2 core devs to merge.
Currently if a core dev is the author we count that as 1 of the 2 'approvals' required. However we currently do not state this in the 'approval' label. The only reason we do not is because it used to annoy a previous core dev intensely.

They are not around anymore so i suggest we change our usage to be clearer and less confusing, and include a core dev author's support in the label, then we can see from labels what PRs have the 2 approvals required instead of having to mentally add 1 if the author is a core dev.

Core devs: Please state your support or otherwise, but not as emoticons for this post, as at a certain number it is not possible to see all names of the users that used a particular emoticon (which is why emoticons should not be used for voting).

**Comment by SmallJoker** [comment]
Approving the own code sounds a bit odd. It's in all developers interest to merge their PR when it's ready - so I suggest to keep the current mechanism as-is. Ready PRs with two (other) developers approval may be merged by any developer - those with only one (excluding trivial PRs) must be merged by the authors themselves if they want to skip further reviews.

**Comment by paramat** [comment]
I should have added: My suggestion is with the understanding that the author's own 'approval' is of course in a way technically not an 'approval' because it is not from someone else. This was what upset some people, however this is a non-issue arising from the 'approval' word used in the label.

The label actually refers to the 2 core-dev 'agreements' required, one of these can of course come from the author. Please don't be overconcerned with the literal meaning of the word used, this suggestion is for clarity and practicality.

Is there a better word or phrase for the label, that doesn't suggest an 'approval' from someone else?

**Comment by paramat** [comment]
Well, that went nowhere fast :) I'm ok with current usage.
