### ISSUE TITLE
Adjustment of the mouse sensitive

### ISSUE THREAD

**Issue by sseemmiin** [minetest/minetest#7343]
##### Issue type

Feature request

##### Minetest version

Minetest 0.4.17-dev-be4d23d1 (Linux)
Using Irrlicht 1.8.4

##### OS / Hardware

Operating system: Linux 16.04 LTS 64bits
CPU: intel(R) core(TM) i5-7200U CPU @ 2.50GHz

##### Steps to reproduce

In case of game start, the mouse sensitivity is so sensitive. 
We can't find the notice about the sensitivity adjustment.
So, could you add the function of sensitivity adjustment ,
Or, if there is the function of that exist already, please put the notice in the ReadMe section.

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/master/minetest.conf.example#L56
