### ISSUE TITLE
'Plantlike_rooted' drawtype black  when smooth lighting disabled

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7345]
![screenshot_20180515_235110](https://user-images.githubusercontent.com/3686677/40151462-040142e8-5978-11e8-89a7-7722f132a1b1.png)

^ Smooth lighting

![screenshot_20180515_235158](https://user-images.githubusercontent.com/3686677/40151468-08ae2d10-5978-11e8-864c-55822df39a2a.png)

^ No smooth lighting, top of same kelp

All shaders disabled, no filtering / mipmap.
Commit 55bb1938c17dfdb065a0eead97ce8094518b9049
OS: Ubuntu 16.04LTS
Hardware: Intel Core i5, integrated graphics (Haswell desktop).

@numberZero perhaps this needs 'paramtype = "light",'?
```
minetest.register_node("default:sand_with_kelp", {
	description = "Kelp",
	drawtype = "plantlike_rooted",
	waving = 1,
	tiles = {"default_sand.png"},
	special_tiles = {{name = "default_kelp.png", tileable_vertical = true}},
	inventory_image = "default_kelp.png",
	paramtype2 = "leveled",
	groups = {snappy = 3},
	selection_box = {
		type = "fixed",
		fixed = {
				{-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
				{-2/16, 0.5, -2/16, 2/16, 3.5, 2/16},
		},
	},
	node_dig_prediction = "default:sand",
	node_placement_prediction = "",
```

**Comment by HybridDog** [comment]
You didn't explicitly set paramtype to "light", is this is required for the "plantlike_rooted" drawtype?
(for reference, you declined a PR to set this value implicitly https://github.com/minetest/minetest/pull/6246)

**Comment by paramat** [comment]
Not sure if it is required, will try.
(Yes declined for good reason).

**Comment by paramat** [comment]
HybridDog thanks that solves it, the plantlike extension probably takes it's light level from the internal value. Will fix in MTG soon.

**Comment by HybridDog** [comment]
I still think lua_api should mention that specific drawtypes require paramtype "light".
I've once made a list of them: https://github.com/minetest/minetest/pull/6246/files#diff-7b4242351dd3cf5b2a70c8aa9d12149bR108

**Comment by numberZero** [comment]
Sorry, have little time currently.

> the plantlike extension probably
> takes it's light level from the internal value.

That’s not how it is expected to work. Don’t remember how it does work
in fact, however; will check.

В Fri, 18 May 2018 18:42:36 -0700
Paramat <notifications@github.com> пишет:

> HybridDog thanks that solves it, the plantlike extension probably
> takes it's light level from the internal value. Will fix in MTG soon.
>
