### ISSUE TITLE
Store L-system trees into files, just like schematics

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7347]
##### Issue type
 - Feature request
##### Summary
I suggest to allow to store L-system trees into files, just like schematics.

The file format would simply store the definition fields of the L-system tree, nothing fancy. The file name would be `<tree name>.mtt`, short for “**M**ine**t**est **T**ree”. The directory in the mod would be `trees`.

Proposed function signatures:

* `minetest.create_tree(treedef, filename)`
Saves the tree with definition `treedef` into `filename`. Parrallels `minetest.create_schematic`.

* `minetest.spawn_tree(pos, treedef, use_map_seed)`
This function is not new. I propose to extend the meaning of `treedef`. If `treedef` is a string, it is interpreted as a file name to a tree file. If it's a table it's interpreted as tree definition like before.
`use_world_seed` is a new optional boolean argument. If true, the tree's set `seed` is ignored and only the world seed is used. Otherwise, the tree's seed is used.

#### Rationale
L-system trees still have somewhat of a shadowy existence in our community.
This (and #7346) would raise L-system trees to the same level as schematics, hopefully encouraging more use.
In file form, trees are more sharable and they no longer must be hardcoded.

#### See also
https://github.com/minetest/minetest/issues/7346

**Comment by paramat** [comment]
Minor point, file is better as '.mtls' or '.mtl' as l-system is not used only for trees.
Also, API should not be 'create_tree' as that confuses with 'spawn_tree', better 'create_l_system_file' or something.
The 'spawn_tree' API should never have been called that.

**Comment by Wuzzy2** [comment]
Yeah, I do not really care that much about the API names.
But at least should be consistent.
