### ISSUE TITLE
[mapgen] Optionally disable redundant light calculations

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7362]
##### Issue type

 - Feature request
 
##### Summary

I've created such an issue already a long time ago.
When using minetest.register_on_generated with vmanip, I often need to calculate lighting.
This takes about 0.1 seconds (according to my latest test with banana plant generation).
When multiple mods need light calculation, the light is calculated for a mapchunk multiple times because each mod invokes the set_light and calc_light functions. 
Actually only the latest light calculation is required because it overrides the previous ones anyways.

Instead of calculating the light when calc_light is called, the area (the cuboid edges) which needs light calculation should be stored in C++ and when all the on_generateds are executed, the light should be calculated in this area in my opinion.

There are actually two situations when the light values are needed:
* Some mod calls get_light_data and does something with the light values
* Mapgen has finished and the result is shown to players

**Comment by paramat** [comment]
This seems non-trivial.

**Comment by rubenwardy** [comment]
Some mobs mods may use on_generate to spawn things and require the light information. Maybe it's worth having two callbacks - `on_generate` and `after_generate`

**Comment by HybridDog** [comment]
> Some mobs mods may use on_generate to spawn things and require the light information.

When a mod uses vmanip:get_light_data, the light is calculated when needed, this is not (yet) done for minetest.get_node, minetest.get_node_light and other related functions.
Instead of after_generate or after_emerge, minetest.after(0, […]) should suffice I think.

**Comment by raymoo** [comment]
I'm not sure about `minetest.after`. Couldn't a normal shutdown result in a block being generated but not having the code run on it? Or is it guaranteed somehow that a normal shutdown will not be processed until there are no more unprocessed callbacks registered with `minetest.after(0, something)`?

**Comment by HybridDog** [comment]
> Couldn't a normal shutdown result in a block being generated but not having the code run on it?

It can, but it's not a problem for mob spawning because an object's existence in minetest is not reliable.

**Comment by paramat** [comment]
Never mind specific mob situations, some uses of LVM require light calculation or read current light for various reasons, so it would have to be optional and default off.

Whether to use the option or not would require studying and understanding each mod in detail to see what it does, in which case the server owner would probably be able to alter the code of the mods to avoid unnecessary light calculations.
Ideally each mod itself could/should have an option for light calculation.
The above two approaches would be preferable to doing this in the engine.

So although the basic intention is good i'm very unsure this is worth doing.
