### ISSUE TITLE
[Documentation Issue] 3D disclaimers

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest#7363]
3D gameplay/options disclaimers/warnings?

 After reading through #7361 I decided to have a quick look around using the method which everyone knows is, in fact, the most reliable place to get answers..., a web search. <sarcasm>

 I did find this article interesting
https://techcrunch.com/2010/06/19/a-guide-to-3d-display-technology-its-principles-methods-and-dangers/

 Dated? Quite but, it raises a legitimate thought.
 Should Minetest/Minetest Game sites, and other official documentation add/contain some form of disclaimers related to any 3D gameplay options?
 Can't be too safe these days.

 I did look around a little, and did not see anything like this. It is possible I missed it and it already exists.
 But I feel it is worth mentioning.

**Comment by otdav33** [comment]
We shouldn't forget that just looking at a screen for extended periods of time can damage your eyesight. Nintendo used to put disclaimers into its games back in the days before the 3ds.

Nintendo was also the hardware manufacturer, though. It would make more sense that the hardware manufacturer would be responsible for eye strain than that the person that wrote the software. I'm not a lawyer, so I'm not going to be able to say for sure.

**Comment by TumeniNodes** [comment]
It is possible, that as these options are being offered in the software, it is at least wise to cover this group on that aspect (the software offered)
Even if it is not code produced by this community, it is still being offered through it.
"Just to be safe", is as good a reason as any and, probably the best reason.

It would be a matter of a short statement, possibly links to the code for the 3D options available (for reference), and then just where to make it noticeable.

**Comment by paramat** [comment]
I don't think we need one, my impression is the license includes disclaimers already.

**Comment by rubenwardy** [comment]
We already have a warranty disclaimer, there's no need for this

**Comment by TumeniNodes** [comment]
ok. If the current license disclaimers cover this area, then I will just close this issue.
Just wanted to make a mention of it to make sure.

I'll leave it open until tomorrow, in case anyone else wants to chime in on it.

**Comment by TumeniNodes** [comment]
closing
