### ISSUE TITLE
Browse online content: List only installed, update all [FR]

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#7369]
##### Issue type

 - Feature request
 
Adding simple checkbox/whatever to:
+ Show list of installed addons
+ Update all of them

**Comment by paramat** [comment]
@rubenwardy

**Comment by rubenwardy** [comment]
I support this, it's on my mental issue tracker too

**Comment by paramat** [comment]
@rubenwardy ok thanks. If you support a feature request please add the 'supported by core dev' label to help with feature request issue management.
