### ISSUE TITLE
Browse online content: Mods can't be deleted or renamed

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#7370]
##### Issue type

 - Bug report

##### Minetest version

```
0.5.0-53d5b3ea
```

##### OS / Hardware

Operating system: Win 7
CPU: Intel Core i3-2120

##### Summary
Content tab has packages list and "Uninstall package" button, unfortunately it does not work for me, as well as "Uninstall" button in "Browse Online Content" section. "Rename" button does nothing too, in modpack it also has weird behaviour, not a name of modpack but some mod inside. My minetest PATH is latin-only and has no spaces.

##### Steps to reproduce
Install some mods or modpacks, hit delete button in those two places

**Comment by numberZero** [comment]
Uninstall works for me (0b2325344, run-in-place, on Arch Linux).

Rename button get the entry index from the (flat) package list (which contains subgames, texture packs and mods) but uses it in the (flat) mod list, thus referencing a mod(pack) several rows down. If that happens to be a modpack as well, that is the modpack that gets renamed (btw, if it was a symlink, a full copy is created instead).

**Comment by Fixer-007** [comment]
It is clearly a bug...

**Comment by rubenwardy** [comment]
Misread

**Comment by numberZero** [comment]
https://github.com/minetest/minetest/blob/409d04324f0a81eaa78ff9161b4f3593d89151c5/src/filesys.cpp#L133-L134
Is is there since *ages*, introduced in 5b31d32da8 in ***2012***.

**Comment by Fixer-007** [comment]
Fixed by #7433, thanks!
