### ISSUE TITLE
profiler graph is displayed upon startup

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7383]
Caused by this [change](https://github.com/minetest/minetest/commit/a78659ed0529226ad937f5e241ad72ba93702959#diff-90e150e0e4479d010bfa007e3e2b6935R191
)

Fix: add
```
+       m_flags.show_minimap = false;
+       m_flags.show_profiler_graph = false;
```

**Comment by sfan5** [comment]
fixed by 75aa41c6de121f01d17cfb8f90916736496b2dce
