### ISSUE TITLE
Proposal for a function minetest.chat_send_moderators in the lua API

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7389]
##### Issue type

 - Feature request
 
##### Summary

When mods need to send out a message to all moderators, they loop through all online players and use `minetest.chat_send_player()` for those with kick, ban privs. Since this piece of code is fairly consistent across mods, I suggest providing a convenience function `minetest.chat_send_moderators()`, which does just that. If approved, mods just have to call this function once, to send a message to all moderators.

Please do let me know if this is a good idea, and I shall start working on this.

##### Example
`minetest.chat_send_moderators(player_name .. "is connected from a blacklisted IP - Moderator attention required.")`

**Comment by SmallJoker** [comment]
Different administrating mods have different ideas on how to define a moderator. Also server admins might want to add more privileges and add exceptions for some "secret moderators".
:-1: this belongs into a mod.

**Comment by ClobberXD** [comment]
@sfan5 Nothing wrong with the for loop per se, it's just that `minetest.chat_send_moderators()` was conceived as a convenience function.

Closing, for reasons given above
