### ISSUE TITLE
Add callback function which fires when all mapgen aliases have been registered

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7390]
##### Issue type
 - Feature request
 
#### Summary
I suggest a callback function to be called when all mapgen aliases have been registered (or at least those aliases the game cares about).

#### Syntax

```minetest.mapgen_aliases_registered()```

To be called manually when all mapgen aliases have been registered. Should only be called once. It should usually only be called in a game mod, rather than a standalone mod.

```minetest.register_on_mapgen_aliases_registered(func)```

```func``` is a function which is called when all mapgen alises have been registered.
```func``` takes no parameters, the return value also does not matter.

#### Rationale

If you're a mod which want to read mapgen aliases from `minetest.registered_aliases` it first must be sure those mapgen aliases were registered in the first place. Depending on mods does not solve this problem since you do not know in which mod the mapgen aliases are registered.

Example: A simple mapgen mod which wants to be generic as possible and does not like to depend on a particular mod, so it works in many games.

@paramat, this might be interesting for all your mapgen mods. :-) What do you think?

**Comment by nerzhul** [comment]
i don't think it's possible as we don't have a registration callback phasis. Registration is done on mod loading/runtime. maybe a on_all_mods_loaded() callback is better for a such thing

**Comment by paramat** [comment]
Nerzhul's suggestion sounds more general and useful and could be used for this.

There is still a chance that several mods then use this new feature to read and set mapgen aliases then you're back to the original problem.
You could always manually edit 'depends' to make it run after mods that set mapgen aliases, not difficult.

**Comment by rubenwardy** [comment]
What if an alias is registered multiple times in different mods? You can't know you've got the final set of aliases until loading is finished, so using `minetest.after(0, ...)` is recommended

**Comment by paramat** [comment]
Aha perhaps 'after' can be used for these purposes?

**Comment by orwell96** [comment]
I consider using minetest.after(0,func) a hack. There should be a proper callback for that.

**Comment by paramat** [comment]
Yes nerzhul's suggestion may be a good addition.

**Comment by nerzhul** [comment]
implemented in #7411

**Comment by Wuzzy2** [comment]
Nerzhul's approach seems much better. If #7411 is merged, feel free to close this issue as “issue opener lost interest” or something like that. ;-)

**Comment by nerzhul** [comment]
we will just close it as a better solution was found, but the need was interesting

**Comment by numberZero** [comment]
#7411 is merged
