### ISSUE TITLE
Add hidden formspec element

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7391]
##### Issue type
 - Feature request

#### Summary

I suggest to add a new formspec element: `hidden`. This is a formspec element which has two parameters, the first one being the name and the second one being the key. Both are arbitrary strings. This formspec element is not rendered, it is only internal.

Syntax:

```
"hidden[<key>;<value>]"
```

When the formspec is received in one of the `formspec_receive` functions, the formspec element is always added into the `fields` table with `key` being the key and `value` being the value, both as strings.

Example:

```
-- Embed a position in the formspec:
"hidden[positon;"..minetest.formspec_escape("(34,2,-340)").."]"
```

This would cause the `fields` table to look like this:

```
fields = {
    ["position"] = "(34,2,-340)",
}
```

### Rationale

This can be very useful to embed some kind of internal state into formspecs. This is mostly for convenience.
There were a few instances in my coding in which I would have really found such a `hidden` field useful.

In real GUI toolkits, hidden fields are also commonly used for the exact same reasons.

**Comment by rubenwardy** [comment]
This sounds like a way novice moder could end up introducing vulnerabilities. I'd rather add a fourth parameter with private values

**Comment by Wuzzy2** [comment]
Yeah, good point.

**Comment by SmallJoker** [comment]
:-1:  Same thoughts as rubenwardy. Hide your data inside player metadata (attributes) or local tables instead.

Adding server-side only parameters which are supplied by a 4th function argument is surely doable, but the same effect can be done using a few additional lines in Lua.

**Comment by nerzhul** [comment]
what is the interest of a such usecase ? a rogue client can easily modify it, try to cheat the server easily

**Comment by Wuzzy2** [comment]
Okay, okay, maybe this was a terrible idea. :D

The rationale behind this is mostly just laziness, it's a non-essential feature, it just would have made things easier.

By the way: Any possible security-related things which modders can do WRONG with formspecs (independent from this suggestion) ... are they written down in lua_api.txt? @rubenwardy

**Comment by BluebirdGreycoat** [comment]
@tenplus1's protection mod passes data like this (node position) through the formspec name, as passed to the second parameter of `minetest.show_formspec()`. Does this have inherent vulnerabilities, or does it depend on the mod implementation?

**Comment by rubenwardy** [comment]
It depends. As long as the position is checked then it's fine (although it's not very clean)

Funnily, the example for the best current way to do this is about area protection - https://rubenwardy.com/minetest_modding_book/en/chapters/formspecs.html#contexts

**Comment by beyondlimits** [comment]
If we can identify what form it is, then all we need is server-side table:

```internaldata[formid] = { ... }```

Set it before it is shown to the client, make use of it when the client sends response.

**Comment by rubenwardy** [comment]
Adopted this issue
