### ISSUE TITLE
Increase default max_simultaneous_block_sends_per_client

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7401]
See this [comment](https://github.com/minetest/minetest/issues/7222#issuecomment-394047332)

I think we should increase the default value for max_simultaneous_block_sends_per_client to at least 20.

**Comment by lhofhansl** [comment]
Hmm. No comment. Does that imply general agreement or disagreement? :)

**Comment by SmallJoker** [comment]
Yes. (inclusive "or")

----

When the server and clients can handle this amount of sent data I don't see a reason to not increase it.

**Comment by lhofhansl** [comment]
:)

Perhaps somebody else can test it?
I think we should increase all of the following:

- emergequeue_limit_generate, double to 64
- emergequeue_limit_diskonly, double to 64
- emergequeue_limit_total, double to 512
- num_emerge_threads, change default to 0 (pick a good value based on H/W)
- max_simultaneous_block_sends_per_client, quadruple to 40

**Comment by paramat** [comment]
> max_block_send_distance = 21
max_block_generate_distance = 21
block_send_optimize_distance = 19

These seem far too high, best these are fairly low to not cause a bad early impression on lower power computers or to greatly increase network traffic on servers. Once users understand these settings they can always increase them. New users won't find or understand these settings for a while so it's best they are set low. I feel it's best to leave these settings unchanged or be very restrained in increasing them.
I use an Intel core i5 quadcore desktop (more powerful than most MT users computers) and use a view range of 10 mapblocks.

'block_send_optimize_distance' greatly increases the number of blocks sent so should be restrained. Although i have sometimes thought about increasing it to be equal to 'max_block_generate_distance'.

**Comment by sfan5** [comment]
> greatly increase network traffic on servers.

This isn't really a concern. These settings should provide a better experience on all servers.
Big servers (which are a small minority) will need to tune these values anyway.

I don't know how much traffic we are talking, but hosting a server on ADSL2 with default settings is not something we should be aiming for.

> New users won't find or understand these settings for a while so it's best they are set low

You can turn this argument both ways: "it's better that these are set high, because new users won't find them to raise the settings"

**Comment by lhofhansl** [comment]
Sorry I wasn't suggesting that we increase these by default:
- max_block_send_distance = 21
- max_block_generate_distance = 21
- block_send_optimize_distance = 19

I mentioned those for my testing with view distance 300 I set these higher to see how MT would do.

The ones I'm suggesting to increase are the first 5 I'm listing.

**Comment by paramat** [comment]
I see, sorry, misread :)

**Comment by lhofhansl** [comment]
@paramat All good. :)

Would be good if somebody could test these settings perhaps on a semi-busy server.

**Comment by lhofhansl** [comment]
@Fixer-007 Feel like doing a test run? :)

**Comment by lhofhansl** [comment]
In fact can someone explain why we need this limit anyway? Can't we just let the network be the natural limit? @nerzhul , do you know?

As a test I set max_simultaneous_block_sends_per_client to 1000 (i.e. no limit), and the world is loaded visibly faster. The nice part is that on fast networks it would naturally transfer more and smaller chunks of packets, whereas for slow networks it would naturally send fewer but larger bursts of packets, and that's exactly what we want.
