### ISSUE TITLE
Making lua_api.txt clearer

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7404]
Searchability.

* ~~It is difficult to find a section, i seem to spend a lot of time searching for a section. I considered adding 'contents' to the start with line numbers, but every addition would require all line numbers to be updated.
I realise we have rubenwardy's modding book which has links to sections but the lua_api file itself should be improved.
So how about a 'contents' section with a number for each section,  then in the body of the file each section title has that number added, meaning when scrolling through you can judge where the section you want is?~~
EDIT: Probably not a good idea.

* ~~Splitting the document up into around 5 documents?~~
EDIT: Probably not a good idea.

* ~~Double empty lines between sections will make it easier to see sections when scrolling, and add some much needed space. There can be an empty line after the title too.~~
EDIT: Now done.

Readability.
The following suggestions are for the 'definitions' sections near the end.

* There are many unnecessary and inconsistent '--[[ ]]' symbols around multi-line comments, creating visual clutter, i suggest removing those.

* There is inconsistent usage of '^' in comments. Sometimes there is just 1 at the start of comments, sometimes 1 per new comment section, sometimes 1 per comment line.
1 per line is the least clear because there is then no indentation, making it hard to spot the subject of the comment. I suggest using just 1 at the start of comments or as few as possible, as in this section:
https://github.com/minetest/minetest/blob/5316b8fe4a5858f0307a58c0ab5630286fd573be/doc/lua_api.txt#L4966

* Many comment lines have '--' embedded in the indent,  this is more visual clutter and is unnecessary, i suggest removing these. An example of clarity without is:
https://github.com/minetest/minetest/blob/5316b8fe4a5858f0307a58c0ab5630286fd573be/doc/lua_api.txt#L5087

**Comment by SmallJoker** [comment]
I agree that we need a better overview there, but the formatting of our Lua code examples, definition tables (with `--` to mark lines as comments) should be kept so copy&paste remains possible.

Short demonstration of the titles and the structure for our Lua API which I have in mind:
```
Introduction

1 File structure
 1.1 Mods
 1.2 Games
 1.3 Modpacks
 1.4 Mainmenu
 1.5 Loading priorities
 1.6 Texture packs (and special texture names)

2 Texture manipulation
 2.1 Texture modifiers
 2.2 Item colorisation

3 Content registration
 3.1 Nodes
 3.2 Items & tools
 3.3 Entities
 3.4 ABMs & LBMs
 3.5 Aliases

4 Utils API
 4.1 Vector
 4.2 `misc_helpers.lua` functions

4 API functions
 4.1 Object functions
 4.2 Item stacks
 4.3 Inventory
 4.4 Player callbacks

5 Map manipulation
 5.1 Voxel Manipulator
 5.2 Mapgen functions

6 Definition tables
 6.1 Node definition table
 6.2 Item definition table
 6.3 Entity definition table
 6.4 Sound definition table
```

**Comment by paramat** [comment]
> but the formatting of our Lua code examples, definition tables (with -- to mark lines as comments) should be kept so copy&paste remains possible.

? This makes no sense :)

**Comment by paramat** [comment]
Anyway, we can move forward with sections and subsections, i suggest numbers plus letters for these.

**Comment by Wuzzy2** [comment]
Big issue: Capitalization seems to be inconsitent. This is very annoying and makes sections unfindable. Make sure that when a section is referered to, it matches the section name exactly for every letter case-sensitively.

I am against a hardcoded TOC, it could be auto-generated by a script and is just an invitation to incoherence.

I am neutral about other suggestions.

Add more internal links so they become clickable in HTML.

Keep in mind that Markdown was made mainly for HTML export.

Maybe a simple script to auto-generate the HTML from Markdown (run whenever you `make` Minetest) could also help a lot. Markdown in plaintext is simply not as readable as HTML, that's a fact.

**Comment by paramat** [comment]
The idea is to make this file easier to use in .txt form, as it of course should be. Nothing wrong with a TOC, paper books have them.
Your suggesitons are fine but are things to be done in addition later, and not by me.

**Comment by paramat** [comment]
Rubenwardy ?

**Comment by paramat** [comment]
> the formatting of our Lua code examples, definition tables (with -- to mark lines as comments) should be kept so copy&paste remains possible.

The issue is that those '--'s mean that what they are commenting on is then deeply indented and hard to find with the eye.
Clear example:
```
        label = "Lava cooling",
        ^ Descriptive label for profiling purposes (optional).
          Definitions with identical labels will be listed as one.
        nodenames = {"default:lava_source"},
        ^ Apply `action` function to these nodes.
        ^ `group:groupname` can also be used here.
        neighbors = {"default:water_source", "default:water_flowing"},
        ^ Only apply `action` to nodes that have one of, or any
          combination of, these neighbors.
        ^ If left out or empty, any neighbor will do.
        ^ `group:groupname` can also be used here.
        interval = 1.0,
        ^ Operation interval in seconds.
        chance = 1,
        ^ Chance of triggering `action` per-node per-interval is 1.0 / this
          value.
        catch_up = true,
        ^ If true, catch-up behaviour is enabled: The `chance` value is
          temporarily reduced when returning to an area to simulate time lost
          by the area being unattended. Note that the `chance` value can often
          be reduced to 1.
        action = function(pos, node, active_object_count, active_object_count_wider),
        ^ Function triggered for each qualifying node.
        ^ `active_object_count` is number of active objects in the node's
          mapblock.
        ^ `active_object_count_wider` is number of active objects in the node's
          mapblock plus all 26 neighboring mapblocks. If any neighboring
          mapblocks are unloaded an estmate is calculated for them based on
          loaded mapblocks.
```
Less clear example:
```
        pos = {x=0, y=0, z=0},
        velocity = {x=0, y=0, z=0},
        acceleration = {x=0, y=0, z=0},
    --  ^ Spawn particle at pos with velocity and acceleration
        expirationtime = 1,
    --  ^ Disappears after expirationtime seconds
        size = 1,
        collisiondetection = false,
    --  ^ collisiondetection: if true collides with physical objects
        collision_removal = false,
    --  ^ collision_removal: if true then particle is removed when it collides,
    --  ^ requires collisiondetection = true to have any effect
        vertical = false,
    --  ^ vertical: if true faces player using y axis only
        texture = "image.png",
    --  ^ Uses texture (string)
        playername = "singleplayer",
    --  ^ Optional, if specified spawns particle only on the player's client
        animation = {Tile Animation definition},
    --  ^ Optional, specifies how to animate the particle texture
        glow = 0
    --  ^ Optional, specify particle self-luminescence in darkness.
    --  ^ Values 0-14.
```
This causes me difficulty when looking at the text.

These definition table are muich more likely to be copypasted from examples in games instead of from here. I've never copypasted definition tables from lua_api.txt.
Even if they are copypasted from here, the comments would need to be deleted anyway.

**Comment by paramat** [comment]
That's fine, best i wait for more input anyway. Just got a little frustrated :)

**Comment by numberZero** [comment]
Having a documentation of everything is good. Having a single 6k lines file is bad. Having documentation spread across that file is even worse.

**Comment by numberZero** [comment]
Some sort of machine-readable documentation would be extremely useful as well. Something like LuaDoc (understood by Eclipse LDT), or more strict format like [ZeroBrane studio’s](https://studio.zerobrane.com/doc-api-auto-complete).

**Comment by thomasrudin** [comment]
I'm no core dev here, but i had good experiences so far with [tiddlywiki](https://tiddlywiki.com/), a standalone, self-modifying html-file. i even started to document some rail-road diagrams for the mapblock format for myself #7448

**Comment by paramat** [comment]
Refer to my document of contents above. We have 3 really big sections 27, 28, 33, within which sections 29 to 32 seem out of place, they would be better being placed before the 3 big sections, after '26 translations. 'Settings' and 'raycast' would be moved into section 28 as suggested.

This would clean up the structure and make it easier to split if desired. Any support for me to do this?

**Comment by ClobberXD** [comment]
Section 28 should also be sorted alphabetically, in order to be able to easily find the desired class reference.

**Comment by paramat** [comment]
Good idea.

Another move idea:
Near the beginning there are a lot of 'basics' sections, then sections 8-11 are more advanced stuff (perlin noise, ore types, decoration types, schematics) that are placed in the middle of the basics.
I suggest moving 8-11 to just after section 26. Then all the basics stuff is grouped together near the beginning and could be split into a sub-document.

**Comment by paramat** [comment]
Initial suggestion for splitting:
* Basics (most of 1-26 but not 8-11)
* Other stuff (8-11, 29-32, maybesome of 1-26)
* `minetest` namespace reference (27)
* Class reference (28)
* Definition tables (33)

**Comment by ClobberXD** [comment]
`lua_api.txt` could be split into 2 files:
- Part 1 could contain:
  - Basics
  - `minetest` namespace reference
- Part 2 could contain:
  - Other stuff
  - Class reference
  - Definition tables

**Comment by Wuzzy2** [comment]
Here's a crazy idea: Write documentation in the source code that defines the functions, in a standardized format, then parse that and generate the documention (or parts of it) from that.

Something like Javadoc, Doxygen, etc. but for Lua API functions.

Is there a software which can be used to auto-generate docs for a Lua API?

**Comment by paramat** [comment]
Anyway, my proposed first PR is:

"Refer to my document of contents above. We have 3 really big sections 27, 28, 33, within which sections 29 to 32 seem out of place, they would be better being placed before the 3 big sections, after section 26. 'Settings' and 'raycast' would be moved into section 28 as suggested."
"Section 28 should also be sorted alphabetically"
"Near the beginning there are a lot of 'basics' sections, then sections 8-11 are more advanced stuff (perlin noise, ore types, decoration types, schematics) that are placed in the middle of the basics.
I suggest moving 8-11 to just after section 26. Then all the basics stuff is grouped together near the beginning"

Any objections? I would like any objections stated before i work on it.
Approval from a core dev would be good too before i start.

**Comment by numberZero** [comment]
@Wuzzy2 There is LuaDoc, as I mentioned. But as Lua lacks classes, and we have many engine-side objects, in-code documentation is not enough (but e.g. Eclipse supports LuaDoc-on-stubs describing external things).

@paramat LGTM.
On TOC, take a look at https://python-markdown.github.io/extensions/toc/ and Python-Markdown itself. Plain markdown is nice for short documents, but huge API reference in this format is hardly usable. (This is out of scope of this PR, of course).

**Comment by Ezhh** [comment]
@paramat Yes, I'm well aware.

> Splitting into separate documents might help with this...

Or might just remove how easy it is to CRTl + F. I'd be very cautious of splitting. 

Either way, I support the changes you suggest.

**Comment by paramat** [comment]
Thanks, i'll take that as official pre-approval, so will do it and merge very soon after to avoid conflicts.

**Comment by paramat** [comment]
#7487 merged.

**Comment by appgurueu** [comment]
I would not split it. But maybe add many blank lines or so to clearly seperate sections.

**Comment by paramat** [comment]
Yes i'm not sure about splitting, and i agree about adding some space between sections, i might do this soon. Luckily empty lines are ignored by MD formatting so this will not affect the MD appearance.

**Comment by paramat** [comment]
Partially attended to by #7534

**Comment by paramat** [comment]
New list of current top and next-level sections:
Note a new section title needs adding in 'Nodes'.
```
Introduction
	Programming in Lua
	Startup
	Paths

Games
	Menu images

Mods
	Mod load path
	Mod load path for world specific games
	Modpack support
	Mod directory structure
	Naming convention for registered textual names

Aliases
	Mapgen aliases

Textures
	Texture modifiers
	Hardware colouring
	Soft texture overlay

Sounds
	SimpleSoundSpec

Registered definitions

Nodes
	*****(Node paramtypes needs adding)*****
	Node drawtypes
	Node boxes

HUD
	HUD element types

Representations of simple things
	Position/vector
	Pointed thing

Flag Specifier Format

Items
	Item types
	Amount and wear
	Item formats

Groups
	Usage
	Groups of items
	Groups of nodes
	Groups of entities
	Groups of tools
	Groups in crafting recipes
	Special groups
	Known damage and digging time defining groups
	Examples of custom groups
	Digging time calculation specifics

Tools
	Tools definition
	Example definition of the capabilities of a tool

Entity damage mechanism

Metadata
	Node Metadata
	Item Metadata

Formspec
	Examples
	Elements

Inventory
	Inventory locations
	Player Inventory lists

Colours
	ColorString
	ColorSpec

Escape sequences

Spatial Vectors

Helper functions

Translations
	Translating a string
	Operations on translated strings
	Translation file format
	Escapes

Perlin noise
	Structure of perlin noise
	Noise parameters

Ores
	Ore types
	Ore attributes

Decoration types
	Simple
	Schematic

Schematics
	Schematic specifier
	Schematic attributes

Lua Voxel Manipulator
	About voxelmanip
	Using VoxelManip
	Methods
	VoxelArea

Mapgen objects

Registered entities

L-system trees
	Tree definition
	Key for Special L-System Symbols used in Axioms
	Example

'minetest' namespace reference
	Utilities
	Logging
	Registration functions
	Global callback registration functions
	Other registration functions
	Setting-related
	Authentication
	Chat
	Environment access
	Mod channels
	Inventory
    Formspec
	Item handling
	Rollback
	Defaults for the `on_*` item definition functions
	Defaults for the `on_punch` and `on_dig` node definition callbacks
	Sounds
	Timing
	Server
	Bans
	Particles
	Schematics
	HTTP Requests
	Storage API:
	Misc
	Global objects
	Global tables

Class reference
	`AreaStore`
	`InvRef`
	`ItemStack`
	`ItemStackMetaRef`
	`MetaDataRef`
	`ModChannel`
	`NodeMetaRef`
	`NodeTimerRef`
	`ObjectRef`
	`PcgRandom`
	`PerlinNoise`
	`PerlinNoiseMap`
	`PlayerMetaRef`
	`PseudoRandom`
	`Raycast`
	`SecureRandom`
	`Settings`
	`StorageRef`

Definition tables
	Object Properties
	Entity definition (`register_entity`)
	ABM (ActiveBlockModifier) definition (`register_abm`)
	LBM (LoadingBlockModifier) definition (`register_lbm`)
	Item definition (`register_node`, `register_craftitem`, `register_tool`)
	Tile definition
	Tile animation definition
	Node definition (`register_node`)
	Recipe for `register_craft` (shaped)
	Recipe for `register_craft` (shapeless)
	Recipe for `register_craft` (tool repair)
	Recipe for `register_craft` (cooking)
	Recipe for `register_craft` (furnace fuel)
	Ore definition (`register_ore`)
	Biome definition (`register_biome`)
	Decoration definition (`register_decoration`)
	Chat command definition (`register_chatcommand`)
	Detached inventory callbacks
	HUD Definition (`hud_add`, `hud_get`)
	Particle definition (`add_particle`)
	`ParticleSpawner` definition (`add_particlespawner`)
	`HTTPRequest` definition
	`HTTPRequestResult` definition
	Authentication handler definition
```

**Comment by paramat** [comment]
Added missing section title in #7560

**Comment by pauloue** [comment]
For the definitions section, how about using only single line comments (--) at the correct indentation level and no --[[ ]] or ^. Also blank lines between parameters as needed to make them easier to find.

Example (ABM definition):

```lua
{
    label = "Lava cooling",
    -- Descriptive label for profiling purposes (optional).
    -- Definitions with identical labels will be listed as one.

    nodenames = {"default:lava_source"},
    -- Apply `action` function to these nodes.
    -- `group:groupname` can also be used here.

    neighbors = {"default:water_source", "default:water_flowing"},
    -- Only apply `action` to nodes that have one of, or any combination of,
    -- these neighbors.
    -- If left out or empty, any neighbor will do.
    -- `group:groupname` can also be used here.

    interval = 1.0,  -- Operation interval in seconds

    chance = 1,
    -- Chance of triggering `action` per-node per-interval is 1.0 / this value

    catch_up = true,
    -- If true, catch-up behaviour is enabled: The `chance` value is
    -- temporarily reduced when returning to an area to simulate time lost by
    -- the area being unattended. Note that the `chance` value can often be
    -- reduced to 1.

    action = function(pos, node, active_object_count, active_object_count_wider),
    -- Function triggered for each qualifying node.
    -- `active_object_count` is number of active objects in the node's mapblock.
    -- `active_object_count_wider` is number of active objects in the node's
    -- mapblock plus all 26 neighboring mapblocks. If any neighboring mapblocks
    -- are unloaded an estmate is calculated for them based on loaded mapblocks.
}
```

Even if the code isn't copy/pasted I think it's best if only valid code is used in code blocks. Also makes it clearer when syntax highlighting is used when compiled to HTML.

**Comment by paramat** [comment]
^ That would be fine with me.

**Comment by numberZero** [comment]
But in in-source documentation (like Doxygen or LuaDoc), description is usually *above* the code. That style requires blank lines between declaration ofc, but they are necessary anyway for readability.

**Comment by paramat** [comment]
@Ezhh what is your opinion of this suggestion https://github.com/minetest/minetest/issues/7404#issuecomment-405450589 (which i support) and the comments being above the code (for which i am neutral)?

**Comment by Ezhh** [comment]
@paramat No issues with it for me. 

Regarding whether comments come first or after, I guess I am also neutral. Description is usually above code, but I actually find the suggested format very easy to read, and I think it's not bad to have spacing. The big issue is, no matter which approach is chosen, making sure it's all done consistently throughout the entire document is massively important. The same formatting should also be applied to any other documents.

**Comment by paramat** [comment]
Anyway, i'm fine with comments above in definition code and will +1 any PR.

**Comment by paramat** [comment]
#7599 merged.
