### ISSUE TITLE
Horizontal Collisionbox Rotating

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#7407]
##### Issue type
 - Bug report
 
##### Minetest version
0.5.0-dev (Linux) 86b19f284990304f5c8322040f277138333a3697

##### OS / Hardware
Operating system: Lubuntu 18.04 LTS
CPU: Intel Core 2 Duo T6500

##### Summary
I was playing around with mobs made with the Mods Redo mod. Specifically some dinosaurs from the Prehistoric Life mod. I noticed that most of the mobs have a 1x1x1 collisionbox, and the big ones have a 2x2x2 or 3x3x3 collisionbox. I was wondering why they were cubes. So I adjusted the configuration for a velociraptor's collisionbox and noticed that when the collisionbox is more of a rectangular prism, and the mob rotates itself, the collisionbox doesn't rotate with it. Talking with @tenplus1 about it, and he said it was a [limitation in the MineTest engine](https://forum.minetest.net/viewtopic.php?p=320255#p320255). So am I seeing this correctly as a bug? Is this planned on being fixed? So far it hasn't been, as I just tested it with the latest code since now, with the last commit being 4 hours ago.

##### Steps to reproduce
Not too sure how to explain it, but here is a screenshot showing the issue:
![screenshot_20180603_230020](https://user-images.githubusercontent.com/18651961/40896755-f967f960-6784-11e8-9524-8d2287270d28.png)
As you can see, the little dino is rotated, but the collisionbox didn't rotate with him. Because of this, modders compromise by giving mobs a collision box that has a squarish base (horizontally), and we then have issues like this T-Rex that is inside a tree but is stopped by the collisionbox:
![screenshot_20180603_230253](https://user-images.githubusercontent.com/18651961/40896793-33bfb332-6785-11e8-9e3f-b1e532a3830a.png)

**Comment by ClobberXD** [comment]
My thoughts: Essentially, we need to be able to define complex collision boxes that take the shape of the entity itself, and should automatically change shape to keep in sync with the entity's movements. They could be defined using a node-box like syntax.
