### ISSUE TITLE
No longer add github-specific issue numbers to commit messages

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7413]
These will become useless clutter once we move away from Github. Perhaps a good idea to stop adding them now?

**Comment by adrido** [comment]
Why do you want to move away from github?

**Comment by nerzhul** [comment]
@paramat we are on github, just use the tool. Also if gitlab is the target they are correctly kept when using the importer then it's a non question

See https://gitlab.com/minetest/minetest/issues/5144 and https://github.com/minetest/minetest/issues/5144

**Comment by SmallJoker** [comment]
The decision from the meeting when we talked about it last time is still valid.
Discussion points: https://github.com/orgs/minetest/teams/engine/discussions/9 (restricted to devs)
IRC logs: http://irc.minetest.net/minetest-dev/2018-05-05#i_5298887

This surely could be discussed again if we would move to another service. The links are also valid on GitLab, so I don't see an issue there.

**Comment by paramat** [comment]
Ah nice, ok. Close is fine.
