### ISSUE TITLE
MeshCollector::append() called with numIndices=89628 (limit 65535)

### ISSUE THREAD

**Issue by entuland** [minetest/minetest#7416]
##### Issue type

 - Bug report
 
##### Minetest version

```
c:\Games\minetest-0.4.16-win64\bin>Minetest 0.4.16 (Windows)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Windows 10
CPU: AMD FX(tm)-6100 Six-Core

GPU model: GeForce GTX 1060 3GB/PCIe/SSE2 4.6.0 NVIDIA 391.35
OpenGL version: NvIFROpenGL.dll, 23.21.0013.9135

##### Summary

Using my mod https://github.com/entuland/wesh I have captured a large terrain section in two slightly different ways.

One is `wesh_mountain.obj`, about 10K vertices, and renders properly in the game, the other is `wesh_mountain_14K.obj`, slightly larger cause the first one didn't capture some unloaded chunks.

The latter fails to render with the message `MeshCollector::append() called with numIndices=89628 (limit 65535)`

Got rid any crashes as explained in https://github.com/minetest/minetest/issues/7416#issuecomment-395881127 ~~Additionally, walking closer to the mountain and trying to grab many more nodes results in the program freezing and closing after a few seconds (no error messages anywhere in the debug log or in the console, the program simply quits), but I believe I can avoid this from my code by counting the number of grabbed nodes and simply bailing out after a certain amount to avoid the crash.~~

I would do the same to avoid ghost meshes like the case at hand:

![ghost_mesh](https://user-images.githubusercontent.com/4322309/41006939-d0987f82-6923-11e8-9426-cd50fd83a545.png)

but I believe it's worth investigating, cause even very heavy meshes such as the 10K vertex one mentioned above (and depicted on the right of the above screenshot) don't seem to give any real problem to the game.

##### Steps to reproduce

The attachment 
[wesh_mountain_14K.zip](https://github.com/minetest/minetest/files/2074245/wesh_mountain_14K.zip)
contains both .obj files and relative texture that can be used assigning them to a custom node or by dropping them in folder of my wesh mod and searching for "wesh" in the creative inventory to place them down.

The attachment also contains two .dat files that get used by my mod to register such nodes at startup.

Capture has been made using the canvas of size 64 placed at pos (-58, 29, 69) of v7 map with seed `adsfasdfa`, heading south.

In order to use newly captured meshes the world needs to be restarted (they get saved in the world's folder and moved to the mod's folder to be loaded at the subsequent startup).

**Comment by entuland** [comment]
Many thanks to https://github.com/TwistedGate for pointing out that nice natural spot to be grabbed for this test and providing me the world seed.

**Comment by SmallJoker** [comment]
Does this also occur in 0.4.17 and 0.5.0-dev?

**Comment by entuland** [comment]
Should try those other versions out, yes. Indeed these are pretty heavy meshes one would not normally use.

Actually, one thing that I would be curious about is how 14K vertices explode to ~90K indices, but probably it's not a count of vertices only but also faces, edges and whatnot.

I'll be just capping the amount of captured nodes if it turns out that the actual limit resides between 10 and 14K vertices as it seems to be and it's not something that could be optimized in the engine itself (I wondered whether those vertices get duped internally for each edge or something, which would easily quadruple their count).

**Comment by entuland** [comment]
Tested on 0.4.17, same behavior of 0.4.16 (the 10K vertices one renders fine, the 14K vertices one drops the same error and fails to render).

Tested on minetest-0.5.0-86b19f2-win64, they both render fine (got some random crashes here and there but are probably unrelated)

![screenshot_20180606_134629](https://user-images.githubusercontent.com/4322309/41036385-2aff5ace-6990-11e8-826c-04c91bb38bb9.png)

**Comment by Fixer-007** [comment]
I will try to pinpoint a faulty commit.

**Comment by entuland** [comment]
Not sure how to get them, @Fixer-007 - with such crashes my debug file and my console don't show any additional info other than whatever I was doing when that happened (stuff like notices about placing / digging nodes and the alike), The game simply freezes and I have to kill it or it dies by itself.

Is there any other place I should be looking for such traces?

**Comment by entuland** [comment]
Littering my flow with minetest.debug() calls I've narrowed down the crash to this function of mine:

```
function wesh.vertices_to_string()
	local output = ""
	for i, vertex in ipairs(wesh.vertices) do
		output = output .. "v " .. vertex.x .. " " .. vertex.y .. " " .. vertex.z .. "\n"
	end
	return output
end
```

The game simply dies when trying to create such a large string I guess.

Anyway, it's pretty clear that the rendering limit gets reached way before the above, I'm going to add an optional cap to generated faces, setting it to 8K faces or so - tested it already, the game is able to cope with that amount of faces in a single mesh.

That option will appear in the capture screen so if anybody wants to investigate further they can alter it to let the mod push its boundaries.

**Comment by entuland** [comment]
Unable to reproduce any crash after having replaced the above silly string concatenation with a more efficient table.concat() thanks to Krock's advice on IRC.

Now I can happily capture meshes with up to 20K faces and beyond pretty fast and without crashing the game - still have to test how far I can push 0.5 with rendering such meshes... that's more likely a job for TwistedGate :)

**Comment by nerzhul** [comment]
Solved

**Comment by entuland** [comment]
For anyone stumbling here searching for notices similar to `MeshCollector::append() called with numIndices=89628 (limit 65535)`, the crashes were caused by my poor string handling but the problem with 0.4.16 and 0.4.17 failing to render such complex meshes, main point of this issue, still stands.

I don't know the limit of 0.5.0 related to that amount of indices yet, I'll eventually post here with updates.
