### ISSUE TITLE
Game crashes if up or down arrows pressed while paused

### ISSUE THREAD

**Issue by garywhite207** [minetest/minetest#7420]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17
```

##### OS / Hardware

Operating system: Windows 7 x64 Professional
CPU: Intel Core i5-2520M

GPU model: Intel HD Graphics
OpenGL version: 3.1

##### Summary
If up or down arrow keys are pressed while game is paused, the game crashes.

##### Steps to reproduce
Start game (singleplayer or join server), Pause game with Esc key, then press either up or down arrow keys.

**Comment by garywhite207** [comment]
I submitted this for 0.4.16 as well, and IIRC it was fixed, but not added to 0.4.17

**Comment by SmallJoker** [comment]
#6092
