### ISSUE TITLE
on_grant and on_revoke callback bug

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#7421]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.5.0-dev-9f8582dc
Other data irrelevant.
```

##### OS / Hardware

Irrelevant.

##### Summary

./builtin/game/register.lua:448:
`			not def[priv]["on_" .. method](name, caller) then`
Should be:
`			not def["on_" .. method](name, caller) then`

'def' is the privilege's definition, so 'def[priv]' makes no sense. I was able to temporarily avoid this bug by adding a field to a privilege whose key was the name of the priv, and which contained the callbacks, confirming this is where the bug is from.

##### Steps to reproduce

Attempt to grant or revoke a privilege with on_grant or on_revoke callbacks.

**Comment by rubenwardy** [comment]
oops :O

**Comment by numberZero** [comment]
and... why no PR? :P
