### ISSUE TITLE
Allow multibyte string.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7425]
##### Issue type
 - Feature request
 
##### Minetest version
0.4.17

##### Summary
Why does words like "äöü" just send invalid multibyte string to the chat?
Why is this disabled?
Any Reason?
It would be nice to fix/enable this like it was in 0.4.16.

##### Steps to reproduce
Write on a 0.4.17 server a "ä"

**Comment by SmallJoker** [comment]
Tested. Could only reproduce it on your server, `Subgames for all!`. Is it running on a Windows system by any chance?

**Comment by Lejo1** [comment]
Its Ubuntu 0.4.17 so compiled:
git clone -b stable-0.4 https://github.com/minetest/minetest.git --depth 100
cd minetest
cmake . -DBUILD_CLIENT=0 -DBUILD_SERVER=1
make -j3

**Comment by numberZero** [comment]
@Lejo1 What’s the client version you use?

**Comment by Lejo1** [comment]
0.4.16 but I am not the only one how has this Problem.

**Comment by numberZero** [comment]
@Lejo1 Is it win/mac/linux? Is it 0.4.16 release or -dev?

> I am not the only one how has this Problem.

Yes you aren’t. Unicode support is inherently broken. That is, it works sometimes, but never reliably.

**Comment by Lejo1** [comment]
Client: Ubuntu 18.04: 0.4.16-AppImage no dev release

**Comment by sfan5** [comment]
Does your server have any mod that modifies chat?

**Comment by numberZero** [comment]
@sfan5 It apparently does. https://github.com/Lejo1/subgames

**Comment by numberZero** [comment]
@Lejo1 Got similar bug with the [subgames](https://github.com/Lejo1/subgames) game and the server running under non-UTF-8 locale:
![_2018-06-09_16-38-35](https://user-images.githubusercontent.com/7352626/41192310-71f6c068-6c04-11e8-929f-e0ff68eb32f2.png)

**Comment by Lejo1** [comment]
> Does your server have any mod that modifies chat?

Yes there are a lot of these.
I will check them.

**Comment by Lejo1** [comment]
Yes its one of my mods which does: `minetest.chat_send_player(aname, "<"..name.."> "..message)` only to the Players in the same lobby.
I there any Problem with:`minetest.chat_send_player(aname, "<"..name.."> "..message)`???

**Comment by numberZero** [comment]
It doesn’t look problematic by itself, it may be just an API that is not fixed yet)

**Comment by Lejo1** [comment]
Its new in 0.4.16 or 0.4.17-dev it was not Problematic.

**Comment by numberZero** [comment]
Er, I apparently lost track of MT. Will investigate.
@Lejo1 What’s the locale your server runs under? (`locale` in the shell should show all the data)

**Comment by Lejo1** [comment]
`LANG=C
LANGUAGE=
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
`

**Comment by numberZero** [comment]
`C`??? Ugh...
I assume MT tries to convert text to the current charset (which is plain ASCII in the case of C) when using the callbacks. Try using UTF-8-based locale (`locale -a` to see enabled locales, there should be one)

**Comment by numberZero** [comment]
Found it. On receiving a message, it is converted to UTF-8 at `src/server.cpp:2921`. But on sending, it is converted from the current locale at `src/script/lua_api/l_server.cpp:77,91`.
