### ISSUE TITLE
os.tempfolder is broken on Windows

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#7430]
Reproduced on Wine, but it looks like the problem happens on [real Windows](https://forum.minetest.net/viewtopic.php?p=321311#p321311) too.

With some debug output added inside `os.tempfolder` and dlg_contentstore.lua:
<pre>
filetocheck = '\s1d.'
randname = 'MTTempModFolder_1185'
screenshot_dir = '\MTTempModFolder_1185'
2018-06-10 18:50:49: ERROR[Main]: GUIEngine: execution of menu script failed: Failed to load and run script from Z:\var\tmp\minetest-0.5.0-90acb9b-win64\bin\..\builtin\init.lua:
2018-06-10 18:50:49: ERROR[Main]: ...acb9b-win64\bin\..\builtin\mainmenu\dlg_contentstore.lua:24: assertion failed!
</pre>

This was caused by a2de439a91df6876e13230696c05957a9da8b2ce, @nOOb3167

**Comment by Fixer-007** [comment]
Can confirm

**Comment by nOOb3167** [comment]
https://blogs.msdn.microsoft.com/vcblog/2014/06/18/c-runtime-crt-features-fixes-and-breaking-changes-in-visual-studio-14-ctp1/

> tmpnam Generates Usable File Names: In previous versions, the tmpnam and tmpnam_s functions generated file names in the root of the drive (e.g. \sd3c.). These functions now generate usable file name paths in a temporary directory.

The '\s1d.' filename format is a tmpnam defect fixed somewhere in year 2014.
I _think_ VS 2012 and earlier do not support enough C++11 standard to build minetest.
So I assume you are using Visual Studio 2013 to build?
Visual Studio 2015, 2017, or higher should be safe.

What toolchain produces the defective builds?
In worst case scenario even MinGW build could be affected, if they tried to be bug-compatible with older visual studio.

**Comment by SmallJoker** [comment]
> So I assume you are using Visual Studio 2013 to build?

They're using GCC/MinGW to cross compile it for Windows (we have a buildbot script for that). What we need here is glue to provide compatibility for MSVC >= 2015 and MinGW.

**Comment by SmallJoker** [comment]
#7443 merged.
