### ISSUE TITLE
Android: configure mods window is broken

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#7434]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17.1
```

##### Summary

See the screenshot

![screenshot_2018-06-11-20-38-14](https://user-images.githubusercontent.com/119752/41250633-c5d6da60-6db7-11e8-947a-0752c008cbac.png)

**Comment by rubenwardy** [comment]
I don't think this is necessarily a blocker since it has been like this since the android port was introduced

**Comment by stujones11** [comment]
Not seeing this on my device.

**Comment by nerzhul** [comment]
@stujones11 nice, a non reproducable bug heh

**Comment by stujones11** [comment]
Maybe something to do with screen size/resolution? Looks like you are only seeing part of the window.

**Comment by nerzhul** [comment]
it's strange it's the only window with the problem

**Comment by rubenwardy** [comment]
This happens to me with my S7 Edge - WQHD (2569x1449) with a small zoom (ie: device pretends to be larger than it is to make things draw smaller and give more space)

**Comment by stujones11** [comment]
Same issue here I think #6848

**Comment by paramat** [comment]
Only a valid issue for 0.4.18 as we have a new content menu in 5.0.0.

**Comment by stujones11** [comment]
This should now be fixed by 3b112889892f6652d4e80d97e45131f179b1fbe4
