### ISSUE TITLE
Browse online content: Lua error on arrow click when list is empty

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#7436]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-git
```

##### OS / Hardware

Operating system: Windows 7
CPU: Intel Core i3-2120

GPU model: ATI X800GTO
OpenGL version: 2.1

##### Summary

If you don't receive list of packages in "Browse online content" you are presented with empty list, if you click on "<" or ">>" - it gives lua error:
![default](https://user-images.githubusercontent.com/16494741/41254291-c7923070-6dcb-11e8-9bb6-4b7ce0133bc5.png)

```
ERROR[Main]: https://content.minetest.net/packages/ not found (Timeout was reached) (response code 200)
ERROR[Main]: Invalid JSON download 
ERROR[Main]: Main menu error: Runtime error from mod '' in callback handleMainMenuButtons(): ...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:148: attempt to index local 'package' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:148: in function 'get_screenshot'
ERROR[Main]: 	...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:377: in function 'get_formspec'
ERROR[Main]: 	...Games\11111\bin\..\builtin\mainmenu\dlg_contentstore.lua:484: in function 'handle_buttons'
ERROR[Main]: 	C:\Programs\_Games\11111\bin\..\builtin\fstk\ui.lua:148: in function 'handle_buttons'
ERROR[Main]: 	C:\Programs\_Games\11111\bin\..\builtin\fstk\ui.lua:192: in function <C:\Programs\_Games\11111\bin\..\builtin\fstk\ui.lua:178>
```

**Comment by Fixer-007** [comment]
Checked if https://github.com/minetest/minetest/pull/7612 potentially fixes the problem, it is not.

Bug is still relevant.

**Comment by ClobberXD** [comment]
Hmm, if no packages are retrieved, where's the need for these page nav buttons? Why did I not think of this before... Fix coming up in a bit.
