### ISSUE TITLE
Android patch file still has wrong line-endings

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest#7442]
##### Issue type
 - Bug report
##### Minetest version
0.4.17.1 & 0.5.0-dev
##### Summary
Android build fails because of wrong line endings in `irrlicht-native_activity.patch`
```
patching file source/Irrlicht/CEGLManager.cpp
Hunk #1 FAILED at 9 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file source/Irrlicht/CEGLManager.cpp.rej
Makefile:497: recipe for target 'irrlicht_download' failed
```
Previous issue: #6750

**Comment by MoNTE48** [comment]
And all the shit) (excuse my rudeness)
Thank's @sfan5 https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/patches/irrlicht-native_activity.patch

**Comment by stujones11** [comment]
Finally, this is fixed, thank you @sfan5 :)
