### ISSUE TITLE
Full screen broken in Gnome

### ISSUE THREAD

**Issue by billywade** [minetest/minetest#7444]
##### Issue type
 - Bug report
 
##### Minetest version

```
4.16 (let me know if I need to try 4.17)
```

##### OS / Hardware

Operating system: Manjaro Linux
CPU: Intel 4970K

GPU model: NVidia GTX 770
OpenGL version:

##### Summary

I'm having a few different issues with fullscreen. For one, Minetest draws over everything else, so there's no way to minimize in fullscreen. Additionally, should I hit the super key and go into overview mode, when I return Minetest doesn't accept controls, a problem compounded when there's no way to kill the application otherwise. 

##### Steps to reproduce

Set Minetest to full screen with the resolution at the display resolution, reopen in full screen, then press the super key to see the overview. Return, controls will be gone. 

Additionally, for the drawing problem, I have Gnome set up for drop-down terminal. If that is also installed, one can run Minetest, press escape, and hit the hotkey for the terminal. The terminal will take input, but will not be visible. 

EDIT: My plan is to map the gnome fullscreen key to my gamepad. Thanks for everyone's help!

**Comment by nerzhul** [comment]
you must try to use 0.4.17, as many fixed has been ported since 1 year

**Comment by rubenwardy** [comment]
This will be an upstream issue (ie: in Wayland or gnome). Only thing we could do is implement fake full screen

**Comment by billywade** [comment]
@nerzhul would it be better to use 4.17 or the latest git?

**Comment by nerzhul** [comment]
@billywade always use the latest tag, or master if you want to verify if issue is fixed in the current devel code

**Comment by jastevenson303** [comment]
Better to use the gnome full screen window keyboard shortcut.. assign it in
settings it's unassigned by default

**Comment by billywade** [comment]
@jastevenson303 do you know what the terminal command is for that shortcut? I run games as a bash script so I can set up all of my additional options (antimicro) and having this as a terminal command would help automate that process.
