### ISSUE TITLE
Container[] doesn't work with fractional values

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#7452]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.5.0-dev-9a1d3584
```

##### Summary
Fractional values in container[] are rounded to some integer.

##### Steps to reproduce
Write following code:
```lua
minetest.register_on_joinplayer(function(player)
	minetest.show_formspec(player:get_player_name(), "test", [[
		size[4,3]
		container[1,1]
		button[0,0;3,1;test1;x1 y1]
		container_end[]
		container[0.5,0.5]
		button[0,0;3,1;test2;x0.5 y0.5]
		container_end[]
		button[0,2;3,1;test;No container]
	]])
end)
```
As you can see, second container has fractional shift.

##### Expected Behavior
`x0.5 y0.5` button is shifted to the right (and bottom, too).

##### Actual Behavior
![image](https://user-images.githubusercontent.com/18210824/41482502-7d4d536c-70de-11e8-9ff3-d64e6ef09530.png)

**Comment by rubenwardy** [comment]
I noticed this, this is certainly a bug

**Comment by HybridDog** [comment]
pos_offset should be float
https://github.com/minetest/minetest/blob/968ce9af598024ec71e9ffb2d15c3997a13ad754/src/gui/guiFormSpecMenu.cpp#L296 https://github.com/minetest/minetest/blob/968ce9af598024ec71e9ffb2d15c3997a13ad754/src/gui/guiFormSpecMenu.h#L380

**Comment by rubenwardy** [comment]
this mistake was made because element positions are stored after parsing as ints in pixel units. Formspecs however use inventory units, which need to be fractional.

Should be a simple matter of changing v2s32 to v2f32
