### ISSUE TITLE
Reduce 'active block range' back to 2

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7453]
Current setting is
`active_block_range (Active block range) int 3`
This was recently increased from 2.
The C++ search of ABMs is known to be inefficiently coded and very intensive. This radius increase increased the volume searched by 3^3 / 2^3 = 27 / 8, more than a tripling of volume. Seems a bad idea for the default setting.

We have a separate setting for mobs:
`active_object_send_range_blocks (Active object send range) int 3`
that can preserve mob activity out to a 3 block radius even if we reduce the ABM radius.
@sofar @lhofhansl

**Comment by nerzhul** [comment]
sorry but it's not the good idea. the good idea is to find the real bottleneck in the mods code which prevents ABM to be faster. We did many code optimization in current master branch which permits to have a better performance than in 0.4.17

**Comment by SmallJoker** [comment]
Changing `active_block_range` does not only affect the ABM activity. Reducing this setting for this reason is not reasonable :-1:

**Comment by paramat** [comment]
Ok. I didn't have much hope for this being supported anyway :)

**Comment by paramat** [comment]
> the good idea is to find the real bottleneck in the mods code which prevents ABM to be faster.

What mods do in their ABM actions is irrelevant to this, i'm referring to the intensity of the initial C++ search.

> still I'd rather find the bottleneck.

@lhofhansl @sfan5 @SmallJoker this is fine, but we actually have to work on improving ABMs ;) We can't continue to say 'let's improve ABM efficiency instead' and not do anything.
Sofar has discovered that the load of ABMs is colossal, and we have recently tripled it in default settings, this is a serious problem. The previous range was not a problem and it can now be independent of object range.

**Comment by sofar** [comment]
#7280 - if implemented, could provide a significant relief.
