### ISSUE TITLE
fs::TempPath crashing latest Android build

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest#7457]
##### Issue type
 - Bug report

##### Minetest version
`5.0.0-e8b687d`
##### OS / Hardware
Android 7.1.1

##### Summary
App crashes immediately after loading bar completes.

Breaking commit: 122eed7a3449eead6f87f45f2eb55c11c3cf171e

Offending builtin code:
https://github.com/minetest/minetest/blob/e8b687d7cafd7ff77572238cf98954527ab1056a/builtin/mainmenu/dlg_contentstore.lua#L22-L23

~~From what I can tell `os.tempfolder()` can return `nil` and does in the case of android so you end up calling `core.create_dir(nil)` hence the crash.~~

On closer inspection it does not seem possible for `os.tempfolder() ` to return `nil` even though this is checked for in other areas of the code. It must be a problem with creating the dir name it returns.

Logcat output: https://gist.github.com/stujones11/2307dbf7179c9652b8671190325aec16

#7439 may be related as the logcat output looks similar, however, this has yet to be confirmed.

**Comment by ClobberXD** [comment]
About the empty content-store: minetest/contentdb#96

**Comment by rubenwardy** [comment]
That issue isn't relevant


Make sure you have the latest core as I've changed the contentdb recently

**Comment by stujones11** [comment]
Empty content store is also fixed for android with ca502fc274c640f1e301a77ecb336ab5a23d348d and my latest patch

![screen](https://user-images.githubusercontent.com/3710749/41608729-0e40fa9a-73e1-11e8-8a14-d1059901730a.png)

Installing mods works nicely too, well done :)
