### ISSUE TITLE
Biome dust fix creates dust in a grid pattern on Lua-added nodes.

### ISSUE THREAD

**Issue by Treer** [minetest/minetest#7458]
##### Issue type
 - Bug report
 
##### Minetest version
Seen in 90acb9b but not in ddd03c3, so introduced between 31 May and June 10

```
minetest-0.5.0-90acb9b-win64
```

##### OS / Hardware
Operating system: Windows 10 x64
CPU: i7-6700k

##### Summary
Biome dust appears in a grid pattern on Lua generated terrain. The symptoms change depending on where you are when the terrain is generating.

The biome dust on the ground looks fine, so I understand if this is low priority. FWIW the mod generating these islands invokes `minetest.generate_decorations(vm)`, and the islands in the screenshots are stone underneath the dirt/snow layer.

ddd03c3 - before dust fix:
![dust before](https://user-images.githubusercontent.com/6390507/41539560-63255f32-7351-11e8-8f38-aed91c044594.png)

90acb9b  - after dust fixed:
![dust after1](https://user-images.githubusercontent.com/6390507/41539583-75d2930c-7351-11e8-979f-05045ff8c575.png)

still 90acb9b, but terrain generated from different position
![dust after2](https://user-images.githubusercontent.com/6390507/41539600-83d541ac-7351-11e8-9e5e-88d18444276f.png)

##### Steps to reproduce
Enable [30-biomes](https://github.com/Gael-de-Sailly/30-biomes.git) mod and [cloudlands](https://github.com/Treer/cloudlands.git) mod, create a Minetest Game carpathian world with seed 1 (perhaps with a dummy database), and teleport to -1812, 250, -4536.

**Comment by paramat** [comment]
This may partly or completely due to the mod. The screenshots seem to show dust bugs in the before and after states. Should there be snow on the trees in the first screenshot? Is there a strange floating layer of snow between the lower trees in the 2nd screenshot?

**Comment by paramat** [comment]
Yes certainly caused by my dust fix commit. Now we drop dust even if the heightmap for a column is empty (no core mapgen terrain placed) and because the dust overgenerates it is affecting lua mapgen added stuff.

Ah because this is a lua mapgen i guess there should not be snow on the trees in the first screenshot, and your lua mapgen stuff is being hit by dust registered for MTG biomes.

**Comment by Treer** [comment]
> Is there a strange floating layer of snow between the lower trees in the 2nd screenshot?

The mod was written before this change, so it dusts itself, so there will be a layer of snow on the ground in the before shot, but it's actually on the ground - not floating, and not on trees/decorations.

The mapgen wants to be determined by the registered biome, so there's no problem with the dust being dropped at this attitude instead of not, just the out-of-order overgeneration dropping it in a grid shape, or appearing at some heights but not at others.

> I'll try to look into this but it may be difficult to do anything about.

thanks, I accept that I may just have to live with this.

> A workaround (or maybe even a requirement) is to not register MTG biomes for this altitude to avoid the dust being dropped here.

Surely this is not a "MTG biomes" problem, since the C++ mapgens depend on these biomes, and issue occurs in other games like MineClone2? However you make an interesting point - if the mod also checked for its own a custom dust paramater in the biomes, it would allow servers or games to create dusted cloudlands biomes that aren't affected by the overgeneration issue.

**Comment by paramat** [comment]
> Surely this is not related to "MTG biomes",

Correct, i meant biomes of any game.

If this starts affecting every lua mapgen mod then it's possibly better to revert this due to how much it will mess up.

**Comment by paramat** [comment]
![screenshot_20180619_192017](https://user-images.githubusercontent.com/3686677/41616451-f26321b2-73f5-11e8-8cd7-fe2b85eca0cd.png)

^ My asteroid mod with unwanted snow.

Yes this is going to make a mess on any mod that adds stuff above the world, so has to be reverted.

**Comment by paramat** [comment]
PR #7464
