### ISSUE TITLE
Rename CSM_FLAVOUR_LIMITS

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7467]
The naming seems a little odd, i think it's better we use a consistent and more descriptive term like 'CSM DISABLE FLAGS' or similar, because it is a byteflag.
'Flavour' needs changing anyway due to not being American English.

**Comment by SmallJoker** [comment]
Related: #6690

**Comment by paramat** [comment]
I can do this if we agree on a phrase. I initially suggest 'CSM_disable_flags'. 'flags' is consistent with settings like 'mg_flags', 'mgv7_spflags'. Having 'disable' in there helps to make sense of the individual flags that are named in the positive:
```
+enum CSMFlavourLimit : u64 {
+	CSM_FL_NONE = 0x00000000,
+	CSM_FL_LOOKUP_NODES = 0x00000001, // Limit node lookups
+	CSM_FL_CHAT_MESSAGES = 0x00000002, // Disable chat message sending from CSM
+	CSM_FL_READ_ITEMDEFS = 0x00000004, // Disable itemdef lookups
+	CSM_FL_READ_NODEDEFS = 0x00000008, // Disable nodedef lookups
+	CSM_FL_ALL = 0xFFFFFFFF,
+};
 ```

**Comment by Ezhh** [comment]
Flags (or many other things) beats flavours (with any spelling).

**Comment by paramat** [comment]
@rubenwardy i seem to remember you are keen to alter these names?
Anyone object to 'CSM_disable_flags' or have a better phrase?

**Comment by SmallJoker** [comment]
I'd prefer to combine rubenwardy's and your suggestion: `csm_restriction_flags`

**Comment by paramat** [comment]
That might be good since 'lookup nodes' is actually a restriction to a set range, not necessarily a 'disable'.

**Comment by SmallJoker** [comment]
#7468 merged
