### ISSUE TITLE
lua_api.txt directory tree format

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7485]
##### Issue type
Documentation issue

##### Summary
lua_api.txt contains "The mod directory structure":

> Mod directory structure

> ------------------------
> 
>     mods
>     |-- modname
>     |   |-- mod.conf
>     |   |-- screenshot.png
>     |   |-- settingtypes.txt
>     |   |-- init.lua
>     |   |-- models
>     |   |-- textures
>     |   |   |-- modname_stuff.png
>     |   |   `-- modname_something_else.png
>     |   |-- sounds
>     |   |-- media
>     |   |-- locale
>     |   `-- <custom data>
>     `-- another

At first : Are all the hyphens ("-----------------------------------------------") supposed to show (a) underlined text or (b) a HTML hr Element : <hr>

At second : using that char : ` is a bad idea, cuz it marks the start of code....

**Comment by rubenwardy** [comment]
> At first : Are all the hyphens ("-----------------------------------------------") supposed to show (a) underlined text or (b) a HTML hr Element

Neither, that's a [header equivalent to `##`](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#headers)

> At second : using that char : ` is a bad idea, cuz it marks the start of code....

Your parser is broken/nonstandard - that's in a code snippet and so any ` characters are part of the code. See the post above.

I do, however, think it's a good idea to switch to another way of showing directories, for example the output of `tree`, as lots of editors use a simplified markdown spec for performance reasons when highlighting. So this is an issue in code highlighting, not formatting

**Comment by appgurueu** [comment]
Uh I wrote my parser myself in Python ;P

**Comment by rubenwardy** [comment]
Not when you're already in a code block

**Comment by appgurueu** [comment]
Just a question : Can't I assign labels myself ? Seems no.

**Comment by 4w** [comment]
> Uh I wrote my parser myself in Python ;P

Start over with the [official syntax](https://daringfireball.net/projects/markdown/syntax) as reference.

**Comment by paramat** [comment]
First post is a question that doesn't justify an issue, and an invalid observation about `.
Not sure this is worth having open for the sake of 'maybe we need to improve lua_api.txt formatting', as that's already known.

**Comment by paramat** [comment]
I checked in ReText, the use of ` here doesn't cause a problem.
