### ISSUE TITLE
lua_api.txt Formatting

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7499]
So, I wrote myself a parser for MD and it works quite fine, will release it soon :)
But then I scrolled down the Bootstrap HTML and SAW :
 Node boxes

Node selection boxes are defined using "node boxes".

A nodebox is defined as any of:

{

-- A normal cube; the default in most things

type = "regular"

}

{

-- A fixed box (or boxes) (facedir param2 is used, if applicable)

type = "fixed",

fixed = box OR {box1, box2, ...}

}

{

-- A variable height box (or boxes) with the top face position defined

-- by the node parameter 'leveled = ', or if 'paramtype2 == "leveled"'

-- by param2.

-- Other faces are defined by 'fixed = {}' as with 'type = "fixed"'.

type = "leveled",

fixed = box OR {box1, box2, ...}

}

{

-- A box like the selection box for torches

-- (wallmounted param2 is used, if applicable)

type = "wallmounted",

wall_top = box,

wall_bottom = box,

wall_side = box

}

{

-- A node that has optional boxes depending on neighbouring nodes'

-- presence and type. See also connects_to.

type = "connected",

fixed = box OR {box1, box2, ...}

connect_top = box OR {box1, box2, ...}

connect_bottom = box OR {box1, box2, ...}

connect_front = box OR {box1, box2, ...}

connect_left = box OR {box1, box2, ...}

connect_back = box OR {box1, box2, ...}

connect_right = box OR {box1, box2, ...}

-- The following disconnected_* boxes are the opposites of the

-- connect_* ones above, i.e. when a node has no suitable neighbour

-- on the respective side, the corresponding disconnected box is drawn.

disconnected_top = box OR {box1, box2, ...}

disconnected_bottom = box OR {box1, box2, ...}

disconnected_front = box OR {box1, box2, ...}

disconnected_left = box OR {box1, box2, ...}

disconnected_back = box OR {box1, box2, ...}

disconnected_right = box OR {box1, box2, ...}

disconnected = box OR {box1, box2, ...} -- when there is *no* neighbour

disconnected_sides = box OR {box1, box2, ...} -- when there are *no*

neighbours to the sides

}

A box is defined as:

{x1, y1, z1, x2, y2, z2}

A box of a regular node would look like:

{-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},

WHY IS THAT NOT IN MULTI-LINE CODE SEGMENTS, LIKE THAT ```
-- HI ME = LUA MULTI LINE CODE IN MD !```

**Comment by rubenwardy** [comment]
It's indepented by 4 spaces, which makes it a multiline code snippet. Please stop doing this

**Comment by paramat** [comment]
It's well known that the MD formatting in lua_api.txt is incomplete and inconsistent, see the related issues.

**Comment by rubenwardy** [comment]
This isn't actually an issue, lua_api uses correct markdown here
