### ISSUE TITLE
Lua API docs: Make use of multiline code notation

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7502]
Please wrap your large code examples in multi-line code syntax. Else, lines such as this one : 
`<REALLY>`
are treated as links...or html tags, which is even worse... (github for instance doesn't display `<THIS> yeah` before the word `yeah` there is the word `THIS` but wrapped in angle brackets)

Furthermore, it'd just look better :+1:

**Comment by ClobberXD** [comment]
It'd be useful if you actually provided a link to the line you are referring to...

**Comment by paramat** [comment]
Good point about <>, will keep that in mind when i work on lua_api.txt.

**Comment by paramat** [comment]
Opening in Retext, <blah> isn't treated as a link if there isn't a valid address within it, doesn't seem a problem. Is this something to do with your own parser?
We use <blah> a lot so i don't think this should be edited.
What has this got to do with large code examples? <blah> is used in many places that are not code examples.

**Comment by appgurueu** [comment]
I modified my parser so that it just works fine. Parsed version : https://appgurueu.github.io/lua_api.html

**Comment by appgurueu** [comment]
Take a look at those sections :
Detached inventory callbacks
HUD Definition
...and others
(for instance)
they contain BIG lua code snippet which is written as plain text...
HTML Version(generated by parser) : There you can see what I mean : https://appgurueu.github.io/lua_api.html

**Comment by paramat** [comment]
Ok, using correct code syntax is valid. But i'm not sure it's right to open an issue for every MD formatting issue in lua_api.txt as there are so many. Maybe add to an existing issue if there is one or make one issue (this one iguess) for all MD format issues?
I don't trust your parser when testing MD formatting, no offence but it should be tested on an established parser.

**Comment by appgurueu** [comment]
```
[
    (0, 0, 0),   (1, 0, 0),   (2, 0, 0),   ... (Nx, 0, 0),
    (0, 1, 0),   (1, 1, 0),   (2, 1, 0),   ... (Nx, 1, 0),
    ...
    (0, Ny, 0),  (1, Ny, 0),  (2, Ny, 0),  ... (Nx, Ny, 0),
    (0, 0, 1),   (1, 0, 1),   (2, 0, 1),   ... (Nx, 0, 1),
    ...
    (0, Ny, 2),  (1, Ny, 2),  (2, Ny, 2),  ... (Nx, Ny, 2),
    ...
    (0, Ny, Nz), (1, Ny, Nz), (2, Ny, Nz), ... (Nx, Ny, Nz)
]
```

THIS is the ONLY use of multi-line code in ENTIRE lua_api.txt, but there are FAR more multi-line code segments. I guess this proves what Im talking about. And no, this has got NOTHING to do with my parser.

If you dont trust my parser, do a full-text search, what I say is true.

**Comment by rubenwardy** [comment]
You clearly don't understand markdown. Multiline code segments are delimitated by indentation, not by three back ticks. Three back ticks doesn't do anything in pure markdown, it's part of github's version of markdown

https://daringfireball.net/projects/markdown/syntax#precode

**Comment by appgurueu** [comment]
Oops ! You are right.

**Comment by paramat** [comment]
> Please wrap your large code examples in multi-line code syntax. Else, lines such as this one :
<REALLY>
are treated as links...or html tags, which is even worse

From MD docs:
> Within a code block, ampersands (&) and angle brackets (< and >) are automatically converted into HTML entities.

Seems to contradict.

This issue is invalid then. You can use #6850 to record any incorrect MD formatting, but note that we already know the formatting is bad, so i'm not sure there is a point opening issues about it.

**Comment by appgurueu** [comment]
I apologize for opening this issue.
