### ISSUE TITLE
Remove the '$' symbols in the bash snippets in the README file. 

### ISSUE THREAD

**Issue by RustyRaptor** [minetest/minetest#7505]
It's annoying when you copypaste it especially when it automatically inserts a newline and runs the command. Am I wrong? Do they serve some other purpose? I see this on so many repos. 

Sorry I am too dumb to program C++ so all I contribute to is README files and documentation.

**Comment by red-001** [comment]
It's a typical notation used in linux documentation, it can be quite annoying when selecting text.
