### ISSUE TITLE
Maybe maybe you could perhaps mention my HTML Version of lua_api.txt ?

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7508]
Look at this MT Forum Thread : https://forum.minetest.net/viewtopic.php?f=3&t=20385
And this HTML Version : https://appgurueu.github.io/lua_api.html (Hosted at GitHub pages)

**Comment by nerzhul** [comment]
no sorry it's not our page, but we can generate it on our github pages, which should be better

**Comment by rubenwardy** [comment]
No

**Comment by appgurueu** [comment]
:laughing: 
OMG ! So we did same stuff :rofl: ! Anyway, was good exercise for me and our pages are somehow different. BTW, mine also has anchor links(if you are talking about navbar aside)... Your "python script link" is dead.

**Comment by paramat** [comment]
Mention where?
Rubenwardy's version is more reliable and is long established, whereas you are very new to this and have made several mistakes with your parser.
:-1:
