### ISSUE TITLE
Multiline code notation issue closed

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7509]
That issue was fixed ? I believe not. Take a look at those sections : 
Detached inventory callbacks
HUD Definition
...and others
(for instance)
they contain GIANT lua code snippet which is written as plain text...
HTML Version(generated by parser) : There you can see what I mean : https://appgurueu.github.io/lua_api.html

Sorry, it's my fault that my first issue was closed, it looked as if I was ONLY complaining about "dead" links : `<deadlink>` in lua_api.txt, and I fixed that in my parser, so that was really closed, BUT my main point was what this issue is talking about.
Sorry again.

**Comment by ClobberXD** [comment]
You could continue to make posts in the previous issue itself, since this is just a continuation of that closed issue.

**Comment by appgurueu** [comment]
Rubenwardy, please explain why that issue is fixed.
@ClobberXD : Yeah, true, but I guess closed issues are hidden ? I wanted to kinda "unclose" it...

**Comment by rubenwardy** [comment]
I opened the other issue. Please comment in the closed issue in future

**Comment by appgurueu** [comment]
Thanks rubenwardy !
