### ISSUE TITLE
Lua crash regression

### ISSUE THREAD

**Issue by Treer** [minetest/minetest#7515]
##### Issue type

 - Bug report
 
##### Minetest version
Seen in ca502fc but not in 90acb9b, so introduced between June 10 and June 19

```
minetest-5.0.0-ca502fc-win64
```
From [sfan5's builds](https://minetest.kitsunemimi.pw/builds/)

##### OS / Hardware
Operating system: Windows 10 x64
CPU: i7-6700k

##### Summary
Syntax errors used to be caught and reported by the GUI, now they cause the Minetest application to crash.

90acb9b (before):
![90acb9b (before)](https://user-images.githubusercontent.com/6390507/42127753-c166e5ea-7ce1-11e8-91b4-53e2ebc6b59e.png)

ca502fc (now):
![ca502fc (now)](https://user-images.githubusercontent.com/6390507/42127755-c3ca3a30-7ce1-11e8-88d0-03f472551aa6.png)

##### Steps to reproduce
An opening bracket with no closing bracket is an example of the sort of lua scripting error that now crashes the application.

[Here's a mod](https://github.com/minetest/minetest/files/2152066/luacrash.zip) that will crash in ca502fc but report the error in 90acb9b.

Functionally, it's not a huge problem - the game ends either way, but reported in case it's a symptom of a deeper regression.

**Comment by SmallJoker** [comment]
Dump of init.lua:
```Lua
local ruhroh = (
```

Error message using build eef62c8 (current HEAD):
```
2018-06-30 19:56:58: ERROR[Main]: ModError: Failed to load and run script from /data/Minetest/run/bin/../mods/lab/init.lua:
2018-06-30 19:56:58: ERROR[Main]: /data/Minetest/run/bin/../mods/lab/init.lua:1: unexpected symbol near '<eof>'
2018-06-30 19:56:58: ERROR[Main]: Check debug.txt for details.
```
No crash. Could you please get a more recent version from [here](https://gitlab.com/minetest/minetest/pipelines) and check whether the problem persists?

**Comment by Treer** [comment]
No crash for me on 9f19b7d either.

If I see it on sfan5's next build I'll let him know.
