### ISSUE TITLE
Distant map generation bug

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7518]
I've noticed in creative mode mapgen generates terrain up to 260 nodes away, far in excess of the 'max_block_generate_distance' setting which is only 7 blocks (112 nodes) by default.

EDIT: Caused by issue explained in #7526

**Comment by nerzhul** [comment]
for me it's good, i didn't notice any performance issue with that, especially on android. The problem can be with some mods

**Comment by paramat** [comment]
Fixing PR #7526

**Comment by lhofhansl** [comment]
That said. I very much think we increase the defaults here. Both desktop and Android @nerzhul

**Comment by paramat** [comment]
I would certainly increase PC gen distance to 8 blocks 128 nodes because nice number.

**Comment by paramat** [comment]
=) yeah, but it's quite a good number too.

Note 'max block generate dostance' is the minimum generate distance, due to how generation works in mapchunks, the actual generated distance can be up to 5 mapblocks larger, depending on where the player is in a mapchunk.
So it seems 'max block send distance should be at least half a mapchunk = 2 or 3 mapblocks larger than 'max block generate distance' to actually make visible the generated distance.

With 'max block generate distance' 8 the generated distance will be between 128 and 208 nodes which seems ok.
