### ISSUE TITLE
Named Spawnpoints

### ISSUE THREAD

**Issue by MassiveStorage** [minetest/minetest#7522]
##### Issue type
 - Feature request

##### Summary
How about adding named spawnpoints to the default server/client-software to be able to teleport to positions like this: /spawn \<name of the desired location\>
To set a new named spawn point something like this would be good: /setspawn \<name for the spawnpoint\>
To delete the spawn point something like this would be posible /deletespawn \<name of the spawnpoint\>

**Comment by ClobberXD** [comment]
I think this can be implemented using the lua API itself and I don't see an engine modification required here. The `/spawn` command could be overridden in a mod to achieve this.

**Comment by SmallJoker** [comment]
Why should this be included to the engine? Server owners should decide if they want to offer such a spawn feature. [Plenty of mods already exist for that.](http://krock-works.16mb.com/MTstuff/modSearch.php?q=%5Bspawn%7C%7Cspawn%5D)
:-1:

**Comment by paramat** [comment]
Does seem to be a game or mod thing, i can't see an advantage or necessity for it to be in the engine. Maybe open an issue in MTG?
:-1:

**Comment by rubenwardy** [comment]
As above

Thank you for the suggestion however, and I hope this doesn't put you off reporting bugs and making suggestions in future :)
