### ISSUE TITLE
Multiple worlds in one server

### ISSUE THREAD

**Issue by FlameFireling** [minetest/minetest#7523]
##### Issue type

 - Feature request
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary
Multiple worlds in one server like: you have worlds you can teleport to from the main server world and the server owner creates new ones in real-time

**Comment by rubenwardy** [comment]
Duplicate of #4428

**Comment by Emojigit** [comment]
I think this is a better solution then #4428
