### ISSUE TITLE
Add a BUNCH of libraries that requires C(++) for Lua Mods

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#7524]
##### Issue type
 - Feature request

##### Summary
There is IMO a lack of C(++) based libraries for lua modding. Examples of which are : matrices, SQLite(DB), good image processing, etc...

Please comment the libraries you'd like to be added to make modding easier.

**Comment by nerzhul** [comment]
sorry but no. those libraries are already used by core and doesn't intend to be exposed to server. the image processing forbidden because it's a client server model and the server doesn't modify any graphics, only push already generated data

**Comment by SmallJoker** [comment]
:-1: Consider loading Lua plugins if you need a stronger, larger API.

**Comment by appgurueu** [comment]
Lua plugins are slow & good ones are rare. Example : LuaSQLite3 REQUIRES C.

**Comment by appgurueu** [comment]
"doesn't intend to be exposed to server"
why not ? don't make THE JAVA MISTAKE no. 1 ! don't make anything "private/protected" ! in java, that leads to HUGE problems concerning reflection, for instance ! We have to trust the modders ! Mod security IMO was a really bad choice...
Not adding new libs keeps the limitations HIGH. Modders willing to go beyond those limits in their mods are restricted. Example : A DB for player stats. I know I can also use files, but DB is better due to 100000000000000000 reasons(not counting the other 10¹⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰⁰ reasons)

Give more opportunities to your modders. Don't only allow them to register "fancy item 1000" which is nothing revolutionary, nothing really new - just another tool with other stats... allow them to exceed their dimensions ! (cant remember which 3rd class ad i stole that phrase from)

Summarized : 
PLEASE, PLEASE add more libs; I don't wanna fork MT...

**Comment by paramat** [comment]
^ That comment sounds like KGM.
