### ISSUE TITLE
World deletion broken on Windows

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#7527]
##### Issue type
 Bug report
 
##### Minetest version
Current dev

##### OS / Hardware
Windows 7

##### Summary
Can no longer delete worlds. 
Did no one test Windows for #7494? (I certainly assume Linux was tested).

##### Steps to reproduce
Make world. Try to delete it. Fail.

**Comment by sfan5** [comment]
#7433 fixes this.

**Comment by Fixer-007** [comment]
Can confirm this bug
