### ISSUE TITLE
Android: on S9+ screen auto rotation causes game to close

### ISSUE THREAD

**Issue by codexp** [minetest/minetest#7529]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17
```

##### OS / Hardware

Operating system: Android 8
CPU: Exynos 9810

GPU model:
OpenGL version:

##### Summary

* when screen auto rotation is on, tilting the phone causes the game to close (or crash?).
* when screen auto rotation is on and desktop is flipped, starting the game will result in a black screen (no response).

##### Steps to reproduce

* first method
  * turn on screen auto rotate
  * start the game in normal rotation
  * tilt the device when in game
* second method
  * turn on screen auto rotate
  * tilt the device to flip the screen
  * start the game (stuck on black screen)

**Comment by codexp** [comment]
this issue may be related to issue #7501

**Comment by MoNTE48** [comment]
@nerzhul please, true https://github.com/MultiCraftProject/MultiCraft/blob/master/build/android/src/main/AndroidManifest.xml#L30

**Comment by paramat** [comment]
Fixed by #7820
