### ISSUE TITLE
Player movement speed in liquids is FPS-dependent

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#7530]
##### Issue type

- Bug report
 
##### Minetest version

```
0.4.17
```

##### OS / Hardware

Operating system: Fedora 28

##### Summary

The higher the client FPS is, the slower the player will swim in liquids; this is especially noticeable with water in minetest_game. This puts players with fast machines and high framerates at a disadvantage in multiplayer.

(I play with the FPS cap disabled to [decrease input latency](http://danluu.com/input-lag/), which should be supported by any modern game.)

##### Steps to reproduce

1. Tweak settings so that you can reach high FPS values (values above 150 make it easier to notice this issue).

2. Disable the FPS cap in minetest.conf using this setting:

```
fps_max = 0
```

3. Run the game (singleplayer or multiplayer) and swim in water.

**Comment by SmallJoker** [comment]
Relevant code:
https://github.com/minetest/minetest/blob/03edcafdda550e55e29bf48a682097028ae01306/src/clientenvironment.cpp#L179-L194

**Comment by rubenwardy** [comment]
It should definitely be a multiplier and not an addition

**Comment by paramat** [comment]
Note the effect of liquid does not use 'dtime_part' so the effect then depends on speed of client step. Perhaps add in dtime as a multiplier of the slowing effect somehow.

**Comment by paramat** [comment]
Maybe try:
```
				// Liquid resistance
				if(lplayer->in_liquid_stable || lplayer->in_liquid)
				{
					// How much the node's viscosity blocks movement, ranges between 0 and 1
					// Should match the scale at which viscosity increase affects other liquid attributes
					const f32 viscosity_factor = 0.3;

					v3f d_wanted = -speed / lplayer->movement_liquid_fluidity;
					f32 dl = d_wanted.getLength();
					if(dl > lplayer->movement_liquid_fluidity_smooth)
						dl = lplayer->movement_liquid_fluidity_smooth;
					dl *= (lplayer->liquid_viscosity * viscosity_factor) + (1 - viscosity_factor);

					v3f d = d_wanted.normalize() * (dl * dtime_part * 60.0f);
					speed += d;
				}
```

**Comment by paramat** [comment]
PR #7543
