### ISSUE TITLE
Making mgv5 stable for 5.0.0: Alter default tunnel width

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7531]
I intend to announce mgv5 as 'officially stable' at 5.0.0 and have a change to default mapgen parameters i would like to make (this won't affect existing worlds).

Currently mgv5 is a mix of classic mgv5 surface terrain shape with the latest underground structure used by most mapgens, except there is one deviation from that: The 3D noise tunnels are still very narrow as in classic mgv5 instead of the much more satisfying wider tunnels used in most other mapgens.

Since mgv5 has completely changed the underground structure of classic mgv5 i would like to do this completely instead of the narrow tunnels spoiling the modern underground. The narrow tunnels are inconsistent with the spacious character of the modern underground.

**Comment by paramat** [comment]
No objections? Will make a PR then.

**Comment by SmallJoker** [comment]
Once upon a time I tested the mgv5 tunnels and also came to the conclusion that making them wider would be nicer for walking through.

**Comment by paramat** [comment]
PR #7641

**Comment by SmallJoker** [comment]
#7641 merged. Please re-open this issue if something else has to be done for mgv5.

**Comment by paramat** [comment]
Related #7650
