### ISSUE TITLE
Add Serverside Possibility to disallow clients, not using the remote_media server.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7536]
##### Issue type
 - Feature request

##### Summary
This is very useful for servers with rare Upload.
It would also be great if this is only for textures that are available on the remote_media server.

**Comment by SmallJoker** [comment]
cURL is optional, so we can't do that.

**Comment by Lejo1** [comment]
Why we could not just disable the media server of the normal server?

**Comment by sfan5** [comment]
You can already do that by editing the code to refuse sending any media files to the client.
Don't be surprised if stuff ends up broken and this certainly won't be added as an official option.
