### ISSUE TITLE
Disable day-night diff block retrieval for underground blocks

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7541]
Currently we do not send block beyond `block_send_optimize_distance` unless they are at "ground level" (i.e. their day and night light differs).

This culls a lot of block, but leads to very annoying glitches at the deep oceans, and make caves practically useless.

To make this better we can check `block->getIsUnderground()` in addition to `block->getDayNightDiff()` as a heuristic. That leads to more blocks being loaded, but removes most of the glitches.

As a test I did the following (view range 300).
- default: 971 blocks are in range
- only remove blocks when it is not underground: 1453 blocks are in range
- disable the distance optimization: 4089 blocks are in range

So we get much better mileage than disabling the optimization, while we get most of the benefits.
Could make this optional via a setting, but I feel like this optimization was always too aggressive for setups where it matters.

Thoughts?

**Comment by lhofhansl** [comment]
Of course underground we'd load a lot more blocks, but that's also as intended, especially in larger caves this is pretty bad otherwise.

**Comment by paramat** [comment]
Seems good as an option. I always want to increase 'optimisation distance' as much as possible but that's only due to ocean and underground issues.

**Comment by lhofhansl** [comment]
Fixed with #7542
