### ISSUE TITLE
Android: on Watch

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#7546]
##### Issue type

 - Feature request
 
##### Minetest version

```
f-droid 0.4.16.17
```

##### Summary

It works well but main menu.
The watch is square.

**Comment by rubenwardy** [comment]
Watch support isn't something we want to support

**Comment by zaoqi** [comment]
@rubenwardy why?

**Comment by rubenwardy** [comment]
Watch screens are too small and inconvenient. The number of users wanting to use the watch will be very small (maybe 1 or 2 people) so it's not worth maintaining it

**Comment by zaoqi** [comment]
@rubenwardy I tried,It is convenient and not too small but main menu.

**Comment by zaoqi** [comment]
@rubenwardy I tried,It is convenient and not too small but main menu and return.

**Comment by paramat** [comment]
LOL this is very silly.
