### ISSUE TITLE
Android settings too conservative

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7550]
On Android the view range is low and many other settings are too low.

I suggest we increase all of the following by default:

```
	settings->setDefault("max_simultaneous_block_sends_per_client", "3");
	settings->setDefault("emergequeue_limit_diskonly", "8");
	settings->setDefault("emergequeue_limit_generate", "8");
	settings->setDefault("max_block_generate_distance", "3");
	settings->setDefault("client_mapblock_limit", "500");
	settings->setDefault("active_block_range", "1");
	settings->setDefault("chunksize", "3");

	settings->setDefault("viewing_range", "25");
```

to this:
```
	settings->setDefault("max_simultaneous_block_sends_per_client", "10");
	settings->setDefault("emergequeue_limit_diskonly", "16");
	settings->setDefault("emergequeue_limit_generate", "16");
	settings->setDefault("max_block_generate_distance", "6");
	settings->setDefault("client_mapblock_limit", "1000");
	settings->setDefault("active_block_range", "2");
	settings->setDefault("chunksize", "5");

	settings->setDefault("viewing_range", "50");
```

Average users will not know how to do this and just get a bad experience.

**Comment by ClobberXD** [comment]
I think it's better to set default `viewing_range` as a multiple of 10, as that's how it usually is on the PC version. Maybe 30?

**Comment by SmallJoker** [comment]
Sounds good. Phones with average specs will surely be fine with that, since it's the media/audiovisuals which takes most of the processing power and RAM.

**Comment by lhofhansl** [comment]
@ClobberXD yeah multiples of 10 is much better. 30 is still dreadfully small, though.

**Comment by paramat** [comment]
I'm fine with this. I especially support chunksize 5 as any other value messes up the density of caves and dungeons. View range 25 looks ridiculous too.
'.. generate distance' and 'active block range' affect servers more than clients and Android is not often a server.
Neutral on the others.
Good idea as part of improving Android at 5.0.0.

**Comment by lhofhansl** [comment]
OK... I'll do a PR. I can't build the Android binary, though.
