### ISSUE TITLE
Can a node be unassigned from using world aligned textures?

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest#7552]
##### Issue type
 - Feature request

 ##### Minetest version
```
5.0.0-dev-ac6e8e2

```
##### Summary
Is there any way, that world aligned textures, can be unassigned per node?
The issue behind the question is small but, not small.

The new world aligned textures (which I love) are great..., but there is one small catch. They do have an impact on fence nodes.
This is workable, with a little texturing finesse but, if one were to create a custom fence (say like my granite fences), you run into this issue.
I do not consider it a 'bug', as the function works as it is supposed to.

This is what I currently have.
![screenshot_20180713_211942](https://user-images.githubusercontent.com/18484258/42719685-ef222afc-86e7-11e8-8fa7-f7a3e99e8030.jpg)

I only had to change 2 texture positions in the defs to correct the issue in one direction but, as you can see, in the other... well, I do not think any amount of texture wizardry can resolve this one.

So, as stated (and I know this is a long shot), is there _some_ way to unassign a node from using this feature?

**Comment by paramat** [comment]
World-aligned textures are an option and default off, you don't need to do anything.

**Comment by TumeniNodes** [comment]
I misunderstood how align_style works then, my apologies.
So I am wondering then, what has changed between 0.4.16 (when these fences worked fine), and 5.0.0, where they do not. The texture layout is changed.

I'll have to look into this further then

**Comment by paramat** [comment]
What is the bug specifically? I can see that one direction of bars has wood on the side and granite on the top, which is weird, but i don't know if you want wood or granite bars.
Best link to code so someone can look.

**Comment by TumeniNodes** [comment]
> But do your custom fences use connected nodeboxes?

Yes, and I greatly apologize, I should have looked into this better before opening an issue.
I only needed to add a new type of fence registration to make it work.
It only differs slightly from the existing fence reg but, makes this type of fence possible.
plus adding one texture to cover the top and bottom of the fence posts.

https://pastebin.com/grvvaLF1

https://pastebin.com/JszMVXX6
