### ISSUE TITLE
Allow turning colored logging off with an env variable

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7553]
Colored log control via a command line option only is annoying.
I find myself maintaining a one-line patch to MT just to default colored logs off.

(My terminals are white... It has been shown that dark text on dark background is better than the reverse)

**Comment by rubenwardy** [comment]
How do other programs do this?

**Comment by lhofhansl** [comment]
In fact I find myself unable to turn off colored logging. `--color never` still does the colored logs.

@rubenwardy Not sure. I do not have this problem with anything else.

**Comment by SmallJoker** [comment]
The fix for this is still pending, see #7173

**Comment by HybridDog** [comment]
Adding a config option is a bit difficult because the colour mode needs to be known when the first log appears, which could happen before the settings are loaded, and getting the setting when printing the log did not work right: #7034.

**Comment by lhofhansl** [comment]
And env variable would work. I don't know how to do this cross platform, though.

**Comment by lionkor** [comment]
The easiest way would be to follow in `ls`'s and `grep`'s footsteps (which each have `LS_COLORS` and `GREP_COLOR` respectively), and add a `MINETEST_COLOR` environment variable. 

We could go as x-platform compliant as possible, by also respecting `CLICOLOR` (has been attempted to be [standardized](https://bixense.com/clicolors/), even).

So IMO we could respect `MINETEST_COLOR` as a direct analog to `--color`, with `never`, `always` (and possibly `auto`) as options. 

Then simply let `--color` override it regardless.
