### ISSUE TITLE
[Bug?] [Content DB?] Mods can't find dependencies that are installed and enabled

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#7558]
##### Issue type
 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-lw-69358b6 (Linux)
```

##### OS / Hardware

Operating system: Ubuntu 16.04 xenial
CPU: AMD PALM (DRM 2.43.0 / 4.4.0-130-generic, LLVM 6.0.0)

##### Summary
For some reason the game isn't finding dependencies. Here's a screenshot of what I got when I loaded a singleplayer world:
![image](https://user-images.githubusercontent.com/28972859/42737674-2af1836c-882c-11e8-88a2-92856fb8ec00.png)

##### Steps to reproduce
Download all the mods in the screenshots and their depends with the content DB.
Run a singleplayer minetest_game world with the mods enabled

**Comment by rubenwardy** [comment]
Make sure your minetest game version is up to date

This is caused by farming or stairs_redo

**Comment by LoneWolfHT** [comment]
I downloaded minetest game from the Content DB yesterday
and I only downloaded farming. Not stairs redo. (Assuming stairs redo isn't a mtg mod)

**Comment by LoneWolfHT** [comment]
Removed the farming mod and that fixed it. Moving this to the farming_redo topic

**Comment by rubenwardy** [comment]
ah yes, the MTG on contentdb is 0.4.16

**Comment by MuhdNurHidayat** [comment]
so, it _is_ a bug?
