### ISSUE TITLE
Strange light flicker in player model, attachable entities

### ISSUE THREAD

**Issue by TumeniNodes** [minetest/minetest#7559]
##### Issue type

 - Bug report
 
##### Minetest version
```
5.0.0 dev-ac6e8e2
```

##### OS / Hardware
Operating system: Linux Mint 18.3 64bit
CPU: AMD A8-6410 APU with AMD Radeon R5 Graphics x 4

GPU model: AMD/ATI Mullens Radeon R4/R5 Graphics (Rev 05)
OpenGL version: 3.0

##### Summary
Odd light flickering with player model and, it seems other entities as well.
See video https://www.youtube.com/watch?v=CLIh2XWIZl4
minetest conf: https://pastebin.com/8rrbNKRA

##### Steps to reproduce
1-Tick Shaders on (no specific shaders need to be selected)
2 - select 3rd person view (notice flicker in player model)
3 - place a boat (notice flicker in boat)
4 - this shows in paramats airship as well
I have not checked horses from mobs mods, or cars/vehicles of any kind but, I imagine it will exist with those as well.

I only noticed this a few days ago, but unsure how long it has been going on.
There have been no changes to the install, other than in settings, none of which should produce this issue.
Any other info needed, just let me know

**Comment by Ezhh** [comment]
I doubt it helps to pin this down, but I have seen this previously in 0.4.16. I don't recall what settings I used at the time. I haven't noticed it in current dev, but that might be because I haven't been in many situations to see player models when using it.

**Comment by TumeniNodes** [comment]
Jordan4Ibanez mentioned he has seen this since going back to 2013

**Comment by TumeniNodes** [comment]
Nevermind, the boat _does_ do it too.

**Comment by style-nine** [comment]
Could be an ATI thing. I'm using nVidia here, and I see no such flicker.

**Comment by TumeniNodes** [comment]
Not sure about that. I just tested this real quick in 0.4.17.1, same settings..., and no flicker.

**Comment by Ezhh** [comment]
Radeon RX 480 here, so may be onto something. 

With that said, I managed to catch some flickering again this morning now I was looking for it, but again in 0.4.16. I can't duplicate it reliably enough to test from a dev client.

**Comment by SmallJoker** [comment]
@TumeniNodes Does this flickering still happen? Perhaps it the bug solved itself in the meantime?

**Comment by TumeniNodes** [comment]
I thought I replied here last night.
@SmallJoker I'm not sure, I haven't had time for anything MT/MTG related for a while, been very busy.
I will check if it still exists in a week or so, when I have some time.

**Comment by paramat** [comment]
Anyone else notice this in recent MT?

**Comment by paramat** [comment]
Can re-open if bug is noticed again.
