### ISSUE TITLE
Move the passoword check to check_password in the Authentication Handler.

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#7562]
##### Issue type
 - Feature request

##### Summary
Allows mods to add other conditions for the login like:

- Ip checks
- Oldplayer systems for overriding of old accounts.
- Master Passoword for admins

**Comment by sfan5** [comment]
Just use the `on_prejoinplayer` callback.

Having a "master" password is not possible, since the plaintext password is not sent to the server (SRP is used instead).

**Comment by Lejo1** [comment]
How can I get on prejoin the password the player has typed in?

**Comment by Lejo1** [comment]
> Having a "master" password is not possible, since the plaintext password is not sent to the server (SRP is used instead).
This is not needed you can just compare it with minetest.get_password_hash

**Comment by Lejo1** [comment]
@sfan5 See below please.

**Comment by sfan5** [comment]
> How can I get on prejoin the password the player has typed in?

You can't.

> This is not needed you can just compare it with minetest.get_password_hash

No, this won't work. SRP is used to verify the password in cooperation with the server, it does not produce a hash you could compare with anything.

**Comment by Lejo1** [comment]
I mean the Password hash which will be compared with the existing one.
As I can't get the Password **hash** on Prejoin this would solve the Problem.

**Comment by sfan5** [comment]
[SRP](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) does not work using password hashes you could compare, what you are describing is not possible.
