### ISSUE TITLE
I can join online servers but I  cant play in my local server

### ISSUE THREAD

**Issue by UchihaSasukeREAL** [minetest/minetest#7564]
Minetest version
0.4.17.1

```

```

Operating system: Windows 10
CPU: CPU Type
Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz

GPU model:Graphics Chipset
AMD Radeon(TM) R9 270
OpenGL version: 4.5

 Summary
I cant join my local game when I join it appears my arm like just with a black color and my screen is grey colored. Sometimes my hud appears.

##### Steps to reproduce
I downloaded and installed it but when I run my Local World the game just crashes

**Comment by HybridDog** [comment]
This sounds like you spawned in the ground, it often happens to me, too.

You can write `/grant singleplayer all` to get fly and noclip privileges, then enable fly and noclip and fly out of the ground.

I think minetest should not put the player in solid matter after spawning or at least teleport out of it.
![out](https://user-images.githubusercontent.com/3192173/42904163-6a01f564-8ad4-11e8-87f0-c6384a6b995b.png)

**Comment by paramat** [comment]
Grey screen means world is not loading, spawning underground would cause a black screen.
Do you have 'mapgen_limit' set to a low value?
Please copy-paste your minetest.conf file.

**Comment by UchihaSasukeREAL** [comment]
ok i will

**Comment by UchihaSasukeREAL** [comment]
main_menu_technical_settings = false
world_config_selected_mod = 1
server_announce = false
screenW = 1920
screenH = 1057
creative_mode = false
menu_last_game = minetest
mainmenu_last_selected_world = 1
maintab_LAST = settings
enable_damage = true
fullscreen = true
fullscreen_bpp = 24


here it is

**Comment by UchihaSasukeREAL** [comment]
@HybridDog  the game crashes and then i cant do anything

**Comment by UchihaSasukeREAL** [comment]
and how do i see mapgen limit?

**Comment by paramat** [comment]
'mapgen_limit' does not appear in your .conf so is not altered from the default, so that setting is not the cause of this.

**Comment by juozaspo** [comment]
Could you look at `debug.txt` file where your game data (`minetest.conf`, saves, etc.) stored? The error and/or messages before that might be logged in that file.

**Comment by paramat** [comment]
No response and vague issue.

**Comment by Fixer-007** [comment]
Check your firewall, game path, etc...
