### ISSUE TITLE
"slices" or "holes" in mapgen (v7)

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#7566]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.4.16? - 0.4.17.1
```

Operating system: Xubuntu 18.04

##### Summary
This has been going for a while now, but I only just now had the real need to stop it.
There are these "slices" or holes or something on my maps.
![screenshot_20180718_200319](https://user-images.githubusercontent.com/24834740/42919494-0a52e1c6-8ac7-11e8-9991-0a3a9668536c.png)
Every single world I create has these, spread over the entire area. No mods enabled, by the way, but it still happens with mapgen mods enabled.
__**Note, this only happens in mapgen v7.**__
Oh right and then there's this (underground view):
![screenshot_20180718_203053](https://user-images.githubusercontent.com/24834740/42920010-8a3adfa4-8ac9-11e8-8deb-0a1b546d14ca.png)

It is rather ugly, and I am certain this is not intended.
I'm not sure if this is a legitimate bug or if there is some config thing messing it up or what.
AFAIK I haven't modified any mapgen settings.

##### Steps to reproduce

Create new world with v7 as generator
Enter world
~~Profit~~

Though it probably wont happen for you because I haven't seen anyone else complain about it yet. And I should think @paramat would have noticed if his generator started doing this :P

**Comment by paramat** [comment]
Looks like the tunnels have been sliced up and re-arranged.
Could you post your .conf?

**Comment by GreenXenith** [comment]
> So it happened in 0.4.16 stable too?

I *think* it happened in 0.4.16. I know it happened in 0.4.16-dev (yes, 0.4.__16-dev__. FWIW commit 5045bdc) up to now. I don't know if it happened in 0.4.16-stable.

And here is my .conf file (I took out the KEYMAPs and a few filepaths):
<details><summary>Spoiler</summary><p>

```
menu_last_game = minetest
server_dedicated = false
aux1_descends = false
creative_mode = true
doubletap_jump = false
enable_damage = false
fast_move = true
fixed_map_seed = 
free_move = true
disable_fire = true
mainmenu_last_selected_world = 133
mg_name = v7
noclip = true
server_announce = false
maintab_LAST = local
anisotropic_filter = true
bilinear_filter = false
enable_parallax_occlusion = true
enable_waving_leaves = false
enable_waving_plants = false
enable_waving_water = true
fsaa = 0
generate_normalmaps = false
leaves_style = fancy
mip_map = true
node_highlighting = box
tone_mapping = true
trilinear_filter = false
water_wave_length = 30
water_wave_speed = 5
water_wave_height = 0.2
name = GreenDimond
remote_port = 30000
minimap_shape_round = false
viewing_range = 140
sound_volume = 0.8
wieldview_node_tiles = false
wieldview_update_time = 2
screenH = 974
screenW = 1280
enable_server = false
screen_h = 974
screen_w = 1280
time_speed = 72
enable_clouds = false
movement_speed_fast = 20
movement_acceleration_fast = 40
fog_start = 0.4
block_send_optimize_distance = 4
port = 30000
meshgen_block_cache_size = 20
client_mapblock_limit = 5000
client_unload_unused_data_timeout = 600
max_block_send_distance = 10
max_forceloaded_blocks = 16
server_map_save_interval = 5.3
active_block_range = 3
server_unload_unused_data_timeout = 29
server_side_occlusion_culling = true
mapgen_limit = 31000
max_block_generate_distance = 6
chunksize = 20
fov = 72
active_object_send_range_blocks = 3
time_send_interval = 5
repeat_rightclick_time = 0.25
enable_client_modding = true
movement_speed_walk = 4
movement_speed_crouch = 1.35
movement_speed_climb = 3
movement_speed_jump = 6.5
fps_max = 200
enable_3d_clouds = false
view_bobbing_amount = 1
fall_bobbing_amount = 0
enable_bumpmapping = false
inventory_image_hack = false
enable_vbo = true
enable_shaders = true
texture_min_size = 64
texture_clean_transparent = true
desynchronize_mapblock_texture_animation = false
smooth_lighting = true
enable_particles = true
enable_console = false
cinematic_camera_smoothing = 0.7
cinematic = false
nodetimer_interval = 0.1
skin_detail = 1
skin_transparency = 0
main_menu_technical_settings = true
connected_glass = false
language = en
num_emerge_threads = 7
send_pre_v25_init = true
TIME_SPEED = 20
debug_log_level = action
enable_local_map_saving = false
```

</p></details>
As far as I can tell, there is nothing in there that should affect cave gen.

**Comment by paramat** [comment]
`chunksize = 20` is the problem, i highly recommend using the default of 5.
With each mapchunk being 20^3 mapblocks in size the 3D noise calculations become 20^3 / 5^3 = 64 times more intensive and use 64 times more memory. Many other processes will also become extremely intensive and this will cause issues for mods too, as well as causing very large server lags.

We've seen bugs caused by large chunksize before so the documents now have a warning:
```
#    Size of chunks to be generated at once by mapgen, stated in mapblocks (16 nodes).
#    Increasing this by 1 almost doubles the 3D noise calculation load.
#    High values can cause noise calculation to overload.
#    Values smaller than 5 cause a terrain bug in mgv6.
#    Since there is a fixed number of large caves and dungeons per
#    mapchunk, values other than 5 alter the density of these.
#    type: int
# chunksize = 5
```

**Comment by GreenXenith** [comment]
>  i highly recommend using the default of 5.

Ahh, OK. This has solved the problem. :D
And hey, now it doesn't take as long to load the initializing chunks xD
I don't even remember why I changed it, I think I was trying to increase chunk generation. Clearly that was not the way to do it ;)

**Comment by 12Me21** [comment]
Is there any reason to allow changing this value at all?

**Comment by paramat** [comment]
It used to be set lower for Android, for low power devices if they run a server (singleplayer). But we use 5 for Android too now, 5 may be actually be optimum for any device. Less may be less volume to generate each time but then mapchunks need generating more often.

I remember hmmmm (our previous mapgen dev) saying he somewhat regrets making it settable because it messes up so much. But existing worlds depend on it. We could support old worlds but just make chunksize non-settable.
There may be some special uses for it to be settable, it's not doing a lot of harm. At least the docs are good:
```
#    Size of chunks to be generated at once by mapgen, stated in mapblocks (16 nodes).
#    Increasing this by 1 almost doubles the 3D noise calculation load.
#    High values can cause noise calculation to overload.
#    Values smaller than 5 cause a terrain bug in mgv6.
#    Since there is a fixed number of large caves and dungeons per
#    mapchunk, values other than 5 alter the density of these.
```
