### ISSUE TITLE
Vehicles occasionally collide with their own player driver (if vehicle has 'collide_with_objects = true')

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7570]
Processor: Intel® Core™ i5-4670T CPU @ 2.30GHz × 4
Graphics: Intel® Haswell Desktop 
OS: Ubuntu 16.04LTS
MT version: 5.0.0dev ca8ec46843da054e656d2f63b23d0b1695c023da 14 July.

Observed using https://github.com/paramat/driftcar in Flat mapgen and MTG, no other mods enabled.
The entity properties are here https://github.com/paramat/driftcar/blob/45dcecfe7f34fda025857d2d9eab9d9193e2dcf2/init.lua#L81
It has 'collide_with_objects = true' like the MTG boat (field is not defined so has the default of 'true').
Sometimes takes a minute or so to happen, sometimes every few seconds.
I'm not referring to the well-known long-running hiccup where the vehicle is teleported a small distance due to server lag, that does not alter velocity.

Commit responsible bisects to bf6569b57019d070246d947ed929cb2b5eb67faf relevant commit history page https://github.com/minetest/minetest/commits/master?after=78a801e42daf53eca0fcc6e791b9eb49e850c207+839
But i can't see how this would cause the bug @nerzhul any ideas?

In this bug, if you are pointed directly NSE or W the speed is suddenly set to 0.
If travelling at an angle to NSE or W, the X or Z velocity component closest to your direction of travel is set to zero, as if hitting an invisible wall that is then instantly removed, the vehicle is therefore deflected sideways because the perpendicular speed is unaffected, like hitting a wall at an angle.

In testing i discovered it does not happen at mapblock borders only.
Although this car mod is moderately fast, the world in front of the car was completely loaded-in far ahead.
This issue also happens in a very minimal game i created, so is not due to MTG.
So far, the bug seems to disappear if the lua entity has 'physical = false'.

@IhrFussel has also reported this, here is some discussion from IRC http://irc.minetest.net/minetest-hub/2018-07-19

23:43 IhrFussel     The 0.4.17.1 update might've fixed my longtime issue with randomly stopping cars ... it didn't happen in the last 15 minutes
23:58 paramat       not so sure, 5.0.0dev stops my vehicles
23:58 paramat       i want to investigate what causes it

00:20 IhrFussel     paramat, only when your vehicle reaches a certain speed?
00:24 paramat       yes at highish sppeds
00:25 paramat       *speeds
00:25 paramat       first i'll test to see if it happens at mapblock borders
00:30 IhrFussel     paramat, if it's the same issue as mine then it will not happen anymore if you define your vehicle as non-physical
00:38 paramat       i'll test that too

00:47 paramat       with physical false i get slightly jerky motion though, but not stops so far
00:47 paramat       *no stops
00:49 IhrFussel     I guess those "hiccups" are normal at high speed but the halting is really bad
00:50 IhrFussel     It didn't happen on my server since 0.4.17.1 update though..maybe I'm just lucky
00:54 paramat       maybe i'll test 0.4.17 too
00:54 tumeninodes   shouldn't be speeding anyway... call it a safety feature. ; )
01:14 paramat       speed limit is low around here then

01:26 paramat       no it's not happening at mapblock borders
01:27 IhrFussel     I'm driving for 10+ minutes now and no random stopping so far... will sleep now, I hope you can confirm/debunk it in 0.4.17.1 later :P
01:36 paramat       hm with physical = false movement is unpleasantly jerky, using my driftcar mod), that seems no solution
01:43 paramat       also the effect is of velocity in 1 of the 4 directions being set to 0, causing a sideways deflection, like hitting a wall at an angle
01:43 paramat       if travelling near-diagonally, the deflection direction will depend on what side of the diagonal you are pointed

**Comment by paramat** [comment]
Getting somewhere, i added some print statements to report when X or Z velocity components are set to 0:
```
			// Set the speed component that caused the collision to zero
			if (step_up) {
				// Special case: Handle stairs
				nearest_info.is_step_up = true;
				is_collision = false;
			} else if (nearest_collided == 0) { // X
				if (fabs(speed_f->X) > BS * 3)
					speed_f->X *= bounce;
				else
					speed_f->X = 0;

				result.collides = true;
				printf("%s\n", "X comp set to 0");
			} else if (nearest_collided == 1) { // Y
				if(fabs(speed_f->Y) > BS * 3)
					speed_f->Y *= bounce;
				else
					speed_f->Y = 0;
				result.collides = true;
			} else if (nearest_collided == 2) { // Z
				if (fabs(speed_f->Z) > BS * 3)
					speed_f->Z *= bounce;
				else
					speed_f->Z = 0;

				result.collides = true;
				printf("%s\n", "Z comp set to 0");
			}
```
Indeed every time this bug happens a notification occurs:
```
X comp set to 0
X comp set to 0
Z comp set to 0
```
So collisionmovesimple is reporting collisions when it should not.

**Comment by paramat** [comment]
Just to check, i reverted my commit 6c9df2f but no improvement.

**Comment by paramat** [comment]
Also happens to MTG boat if you increase maximum speed to 12 nps.

**Comment by paramat** [comment]
Added more print statements to collisionMoveSimple() to print details of what is being collided with:
```
object
pos
0
0
0
Z comp set to 0
object
pos
0
0
0
X comp set to 0
object
pos
0
0
0
Z comp set to 0
```
Now we're really getting somewhere. The vehicle is colliding with an object at 0, 0, 0 even though the vehicle is nowhere near that position. Also, this vehicle has 'collides with objects' set to false.

**Comment by paramat** [comment]
My testing branch is https://github.com/paramat/minetest/tree/colltest

**Comment by paramat** [comment]
My branch prints the position, but it looks like position is intentionally set to 0, 0, 0 for objects:
https://github.com/minetest/minetest/blob/a90d27e1e23fa1c369c05a4d9c6083aa86ef7f52/src/collision.cpp#L397
Note the `v3s16()` for position.
So the position being shown as 0, 0, 0 is not a bug.

**Comment by style-nine** [comment]
I just tried this with MTG boats (with the max velocity set to 25) in Valleys and Carpathian worlds, and it does do this. At that speed, it's pretty noticeable.

Using Minetest 5.0.0-dev-a0635f6 in Ubuntu 18.04 here.

**Comment by paramat** [comment]
Setting 'collide_with_objects = false' stops the bug happening, so that points towards the code that detects object collision.
https://github.com/minetest/minetest/blob/a90d27e1e23fa1c369c05a4d9c6083aa86ef7f52/src/collision.cpp#L352

**Comment by paramat** [comment]
Edited my branch to print more information, now i have the aabb3f collisionbox info for the object the vehicle collided with:
```object
pos
0
0
0
box min XYZ max XYZ
22637.759766
92.500000
3985.959961

22643.759766
109.500000
3991.959961
X comp set to 0
```
Size in nodes is X 0.6 Z 0.6 Y 1.7 look familiar? The vehicle is colliding with the player.

**Comment by paramat** [comment]
Making the player driver:
```
        physical = false,
        collide_with_objects = false,
```
When attached to the vehicle does not avoid the bug.

**Comment by paramat** [comment]
I'm sceptical about my bisecting as the commit doesn't seem related.

My initial suggestion is that an object that has 'collide_with_objects = true' does not check for collision with it's own attached child objects.
My guess is that the position of an attached object 'goes weird' sometimes and causes the vehicle to collide with it.

**Comment by SmallJoker** [comment]
> So perhaps any attached object should not be physical? This might work as a workaround in Lua mods, i'll try it later.

Whereas attached objects do not collide with anything (code skipped by if-condition in `content_cao` and `content_sao`), it really doesn't apply for the parent object. The code below needs checking whether the CAO/SAO is attached and skip adding the object to the vector:
https://github.com/minetest/minetest/blob/c022ddce4bb0da68a842c6479ecd7d9660d7c2fe/src/collision.cpp#L359-L387

**Comment by style-nine** [comment]
I've noticed that these incidents occur while the whole world looks like it's being rolled back somehow. You get a huge rubber band effect, and then the boat stops. I wonder if this is some kind of anti-cheat side effect.

**Comment by IhrFussel** [comment]
I already talked about this bug in January: http://irc.minetest.net/minetest-hub/2018-01-27#i_5212790

But I still couldn't reproduce it in 0.4.17.1 yet.

**Comment by paramat** [comment]
SmallJoker i agree, will try it.

**Comment by paramat** [comment]
SmallJoker that won't be easy to do, looking at code, and i'm concerned about slowing down collision checks. There is already a check there for whether the object 'collides with objects' so it may be a better solution that games set a player as collide_with_objects = false when attached to a vehicle.

**Comment by style-nine** [comment]
FWIW, I tried using "disable_anticheat = true" and I still see this bug happen.

**Comment by SmallJoker** [comment]
@raymoo That would be nice, but there's already a check so that the object does not collide with itself.

**Comment by style-nine** [comment]
I've tested this just now in Windows 7 with this same hardware and I can confirm this bug for Windows versions 0.4.17 and 0.4.17.1. You simply create a default world in Creative mode, change the boats so that it tops out at 15 or so, and then ride around in a boat for a while. It's pretty easy to see after a while.

I'm guessing that the cause is either related to the change to C++11 or a common quirk between GCC 7 and mingw 5.

**Comment by paramat** [comment]
SmallJoker i have actually been working on your suggested fix. It's tricky because the objects are stored as 'ActiveObjects' which is a parent class to SAO and CAO and is a class that does not have the 'is attached' member. One of SAO and CAO does not have 'is attached' so that would have to be added.

I prefer to make the attached player 'not collide with objects' as a simple fix but that doesn't seem to be working, i would like to investigate why first.

**Comment by paramat** [comment]
@7610 merged.
