### ISSUE TITLE
Feature request - Ability to create a Raycast object without specifying an end pos

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7571]
##### Issue type

 - Feature request

##### Summary

I'd like to be able to create a raycast object providing a direction vector instead of specifying an end pos, which could automatically be assumed to be the pos when the ray hits a solid node. Is this possible to implement?

**Comment by SmallJoker** [comment]
`local end_pos = vector.multiply(dir, 0xFFFF)`
You cannot rely on that there's a node at which can be pointed, so all you can do is to set an end position with is distant enough (here it's across the entire map).

**Comment by ClobberXD** [comment]
Right, good point...
