### ISSUE TITLE
Android fog color does not match sky color

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7573]
That leaves visible world boundaries visible.
See this screen shot:
![screenshot_20180721-124857](https://user-images.githubusercontent.com/446130/43034884-ad72c6d6-8c99-11e8-92bd-fe484ebd5c30.png)

Enough data is loaded to show, it's really the fog color not matching.

**Comment by lhofhansl** [comment]
Looks like the lower sky box is missing...?

**Comment by lhofhansl** [comment]
@nerzhul Any ideas by chance?

**Comment by paramat** [comment]
Yes the 'far cloudy fog thing' on the horizon is missing. But also sun, moon, stars #3155

**Comment by lhofhansl** [comment]
Wow. Really old issue then.

**Comment by lhofhansl** [comment]
Hmm... So I can't build for Android myself. Looking at the code I see no reason why this would the case.

**Comment by lhofhansl** [comment]
I tried to switch renderers (tried software and OpenGL) to no avail.

I'd say that at the moment the Android port of MT is somewhat embarrassing and we should pull it, I think it does more harm than good, it just looks bad.

I understand that a few folks have put some effort into it, but it needs more love from more people to be the useful.

**Comment by rubenwardy** [comment]
5.0 has improved Android controls. The graphics is still awful

![](https://user-images.githubusercontent.com/4017302/42173340-e79f9686-7e48-11e8-8b51-0f17037eddd2.png)

**Comment by lhofhansl** [comment]
Oh, that's nice. I'll have learn how to build it myself, then I might be able to fix some bugs for Android.

I know you put some work into this. It just seems that you're the only and nobody else really cares.

**Comment by paramat** [comment]
We do care, and we are making progress recently to improve the official app, as the non-official ones tend to be more problematic to servers (as well as being full of ads and pay-for-feature).

**Comment by lhofhansl** [comment]
Fixed with #7598 

Now we need to push out a version :)

Note that ad-infested MultiCraft already pushed a Android version boasting the new sun and star feature that *they* added. Meh...
