### ISSUE TITLE
Lua functions have poor argument checking.

### ISSUE THREAD

**Issue by beyondlimits** [minetest/minetest#7576]
##### Issue type

 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-25cc5d1a (Linux)
```

##### OS / Hardware

Operating system: Ubuntu 16.04.4
CPU: Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz

##### Summary

A whole lot of functions/methods provided from C++ to Lua do not have proper argument checking. When such functions are called with invalid arguments, Minetest freezes in gray screen or crashes instead of shutting down game with error message. This happens even when call is done inside `pcall`.

```lua
-- Gray screen
minetest.add_entity()
minetest.add_item()
minetest.add_node()
minetest.add_node_level()
minetest.add_particle(1,2)
minetest.add_particlespawner(1,2)
minetest.check_single_for_falling()
minetest.clear_craft({})
minetest.create_schematic('',{},{},'')
minetest.delete_area()
minetest.dig_node()
-- cut here - gave up checking all of them
minetest.show_formspec(name, 'test', 'list[inventory_location;list_name;0,0;8,8;]')
-- cut here as well

-- Crash (engine assumption failed)
minetest.set_timeofday(2)

-- Crash (segmentation fault)
player:get_inventory():set_lists()
```

##### Steps to reproduce
1. Pick a random function/method that's provided from C++ to Lua.
2. Call it with unusual arguments, trying to crash Minetest.
3. If it didn't crash, go to point 1.

**Comment by SmallJoker** [comment]
#1794
