### ISSUE TITLE
Creating A Standard for Documenting Mod APIs, Options, Commands, etc.

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#7579]
##### Issue type
 - Feature request
 
##### Minetest version
```
any
```

##### OS / Hardware
Operating system: N/A
CPU: N/A

##### Summary
This is not an issue or a bug, more of an idea. And it's not related to the Minetest engine itself, rather modding. If there is a better place to bring this up, please direct me to it ([maybe the forums](https://forum.minetest.net/viewtopic.php?t=20567)?).

I have been using [LDoc](http://stevedonovan.github.io/ldoc/) (a fork of [LuaDoc](http://keplerproject.github.io/luadoc/)) to create documentation for some of my mods. It might be too much work, but I think it would interesting to have formal guidelines for modders to (optionally) use to document their mods. LDoc is specifically for Lua, for that reason I would recommend it be used in the guidelines. Other than that, [Doxygen](http://www.doxygen.org/) is the only other source code documentation software that I have used. And I think it can be used with Lua.

An example of HTML documentation generated for a mod using LDoc can be viewed from my [listitems mod GitHub page](https://antummt.github.io/mod-listitems/api.html). I am only familiar with the basics of LDoc, & it is probably more capable than what I have used it for so far.

The manual for documenting with LDoc is found [here](http://stevedonovan.github.io/ldoc/manual/doc.md.html). It is somewhat lacking, unfortunately.

The layout that I use is to create a directory name "docs" for the GitHub pages. Within "docs" I create a configuration file used by the ***ldoc*** executable. I also like to create a little helper shell script to speed up the process:

```
#!/bin/bash

DOCS="$(dirname $(readlink -f $0))"
ROOT="$(dirname ${DOCS})"
CONFIG="${DOCS}/config.ld"

cd "${ROOT}"

# Clean old files
rm -rf "${DOCS}/api.html" "${DOCS}/scripts" "${DOCS}/modules"
# Create new files
ldoc -c "${CONFIG}" -d "${DOCS}" -o "api" "${ROOT}"
```

I have LDoc create a file named "api.html", "manual.html", or something similar so that the URL to access the document will be something like "<span>https://</span>antummt.github.io/mod-listitems/api.html".

It would probably be a good idea to create a configuration template that would have any custom functions & tags already defined ([example config.ld](https://github.com/AntumMT/mod-listitems/blob/master/docs/config.ld)).

I may myself be interested in writing up a document laying out some guidelines for documenting mods. But that will depend on when I can find some time to do so.

Anyway, just an idea that came to mind from trying to document my own mods. Feedback is appreciated.

**Comment by paramat** [comment]
I feel that guidelines for documenting mods won't have much effect because modders will just continue to document the way they want. Most probably prefer using simple '--' comments.
If it's optional, as it should be, then it's not really worth making it a guideline, because it won't be a guideline. I don't see any need to document this as an option as it's low priority.
I guess this is relevant to games too, but commenting will be decided by each game team so is not an engine issue.

**Comment by SmallJoker** [comment]
The idea sounds very nice, but in reality it would have the same effect as forcing the use of tabs to indent the code. Some modders might make use of this feature, but it surely won't become a standard.

Relevant xkcd:
![Standards](https://imgs.xkcd.com/comics/standards.png)

**Comment by rubenwardy** [comment]
I feel like this should be discussed on the forums, and maybe a third party project worked on. If something becomes reasonably good I'll write about it in my modding book.

**Comment by AntumDeluge** [comment]
Okay, I will close this. If anyone else would like to add input please use the [forum thread](https://forum.minetest.net/viewtopic.php?t=20567).
