### ISSUE TITLE
Text Field squashed "generateur de terrain"(seed i presume) label in french 

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [minetest/minetest#7581]
##### Issue type

 - Bug report

##### Minetest version
```
0.4.17.1
```

##### OS / Hardware

Operating system:
CPU: win32

GPU model:
OpenGL version:

##### Summary

string generateur de terrain squashed by text field on welcome screen. i guess that's seed in english, but not enough space in french

**Comment by SmallJoker** [comment]
#4607
