### ISSUE TITLE
Server not announced

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#7584]
##### Issue type
 - Bug report

 
##### Minetest version
 0.4.17.1

2018-07-25 15:32:51: ACTION[Server]: [advtrains]nodedb: read 0 nodes. 
2018-07-25 15:32:51: ACTION[Server]: [advtrains][load_all]Loaded advtrains save files 
2018-07-25 15:32:51: ACTION[Server]: Announcing to servers.minetest.net
2018-07-25 15:32:56: ERROR[CurlFetch]: servers.minetest.net/announce not found (Timeout was reached) (response code 0)

##### OS / Hardware

Operating system: Linux
CPU:

GPU model:
OpenGL version:

##### Summary
Server is not announced.

##### Steps to reproduce
Server is not announced.

**Comment by lhofhansl** [comment]
Network problem?

**Comment by ne-vlezay80** [comment]
Network is not problem:
root@minetest-srv:/home/admin# ping servers.minetest.netPING kitsunemimi.pw (185.107.80.107) 56(84) bytes of data.
64 bytes from kitsunemimi.pw (185.107.80.107): icmp_seq=1 ttl=54 time=62.1 ms
64 bytes from kitsunemimi.pw (185.107.80.107): icmp_seq=2 ttl=54 time=62.5 ms
^C
--- kitsunemimi.pw ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 62.188/62.384/62.580/0.196 ms
root@minetest-srv:/home/admin# ping6 servers.minetest.net
PING servers.minetest.net(2a00:1768:6001:a::f (2a00:1768:6001:a::f)) 56 data bytes
64 bytes from 2a00:1768:6001:a::f (2a00:1768:6001:a::f): icmp_seq=1 ttl=56 time=143 ms
64 bytes from 2a00:1768:6001:a::f (2a00:1768:6001:a::f): icmp_seq=2 ttl=56 time=137 ms
^C
--- servers.minetest.net ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1000ms
rtt min/avg/max/mdev = 137.790/140.884/143.979/3.117 ms

ifconfig:
root@minetest-srv:/home/admin# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.180.2  netmask 255.255.255.0  broadcast 192.168.180.255
        inet6 fd00:1002::2  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::5054:77ff:fe88:99  prefixlen 64  scopeid 0x20<link>
        ether 52:54:77:88:00:99  txqueuelen 1000  (Ethernet)
        RX packets 7144  bytes 5797941 (5.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4988  bytes 513609 (501.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 4  bytes 156 (156.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 156 (156.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

minetest.conf:
root@minetest-srv:/home/admin# cat /opt/minetest4/minetest_heaes_revisited.conf 
server_name = heaes_revisited
server_description = heaes_revisited
server_url = http://minetest.net
server_announce = true

#creative_mode = true
server_address = 2a01:d0:c353:180::21
port = 30001
default_privs = interact, shout, home
name = MrNevlezay
lang = ru
static_spawnpoint = -16,1,-36
alt_spawnpoint = -16,1,-36
#adm_point = -173, 38, -37
ipv6_server = true
serverlist_url = servers.minetest.net
#curl_timeout = 10000

**Comment by sfan5** [comment]
a few things:
* drop the `server_address` setting, it's most likely the problem
* `2a01:d0:c353:180::21` is not actually allocated to your system, are you using IPv6 in a NAT configuration?
* check your port forwards

**Comment by ne-vlezay80** [comment]
1. Yes
2. Yes: config from vm namespace:
root@router:/# ip6tables -t nat -L -v -n
Chain PREROUTING (policy ACCEPT 4 packets, 408 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    2   160 DNAT       all      *      *       ::/0                 2a01:d0:c353:180::21  to:fd00:1002::2
    0     0 DNAT       all      *      *       ::/0                 2a01:d0:c353:180::22  to:fd00:1002::3

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 2 packets, 160 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    4   408 SNAT       all      *      *       fd00:1002::2         ::/0                 to:2a01:d0:c353:180::21
    0     0 SNAT       all      *      *       fd00:1002::3         ::/0                 to:2a01:d0:c353:180::22

**Comment by sfan5** [comment]
An IPv6 NAT is quite problematic when you want to host a server.
You have two options pretty much, either configure the router to forward instead of NAT'ing or disable IPv6 for your server.

**Comment by rubenwardy** [comment]
How do you run the server list, sfan5? How many worker threads?

**Comment by verymilan** [comment]
I would like to report that i have a similar problem right now - i added the ipv6 entry for the domain, in general my ipv6 setup serverside seems just fine and tests for :80 or :443 seem just alright. 
However my Minetest ports do not work, regarding netstat the server isn't even listening with both ipv6 settings set in the `minetest.conf`.
I configured Minetest to listen to `0.0.0.0`, was that wrong (it is not supposed to lock out v4 clients though)?

```
ERROR[CurlFetch]: servers.minetest.net/announce not found (HTTP response code said error) (response code 500)`

## while netstat
udp        0      0 0.0.0.0:30002           0.0.0.0:*                           minetestserve 
udp        0      0 0.0.0.0:30003           0.0.0.0:*                           minetestserve 
# while webserver
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      nginx: master  
tcp6       0      0 :::443                  :::*                    LISTEN      nginx: master

## while config
enable_ipv6 = true
ipv6_server = true
```

**Comment by sfan5** [comment]
> I configured Minetest to listen to `0.0.0.0`, was that wrong?

yes, in 99% of cases you won't need to change the bind address (and shouldn't).

**Comment by verymilan** [comment]
oh nice so i had a wrong setting for years but never noticed it since it was only ipv4 - thank you very much, it looks correct now, i got another 500 error from the list but the server is listed there again ... so i think it's fine now. :thinking: (illuna techeth)

**Comment by paramat** [comment]
Seems resolved.
