### ISSUE TITLE
FPS limited in 60

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#7597]
##### Issue type

 - Bug report
 
##### Minetest version

Minetest 5.0.0-dev-2b83af78 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="/usr/local/share/minetest"

##### OS / Hardware
Operating system: Debian linux 9.1
CPU: AMD Phenom(tm) II X4 965 Processor

GPU model: NVIDIA 8500GT
OpenGL version: 3.3.0 NVIDIA 340.107

##### Summary
Why does FPS not rise above 60 at maximum settings?
Config:
wanted_fps = 80
fps_max = 80
screen_h = 1035
screen_w = 1918
pause_fps_max = 200
menu_last_game = minetest
maintab_LAST = local
selected_world_path = /home/ne-vlezay80/.minetest/worlds/test_minetest
enable_particles = false
enable_3d_clouds = false
directional_colored_fog = false
enable_shaders = false
smooth_lighting = false
minimap_double_scan_height = false
arm_inertia = false
enable_vbo = false
node_highlighting = none
enable_damage = true
mainmenu_last_selected_world = 1
creative_mode = true
vsync = false

**Comment by ClobberXD** [comment]
@ne-vlezay80: Frame-rate is still limited by the monitor's refresh rate, which in your case is probably 60Hz, which corresponds to 60 FPS.

**Comment by SmallJoker** [comment]
`vsync = false` does not guarantee that vsync will be disabled (other limits may still exist).

**Comment by Kezii** [comment]
why is this bug closed? fps is still limited to 60, I can disable vsync and get higher fps on other games/engines but not minetest, this should be kept open

**Comment by rubenwardy** [comment]
you need to change fps_max too

**Comment by Kezii** [comment]
I changed fps_max

**Comment by Kezii** [comment]
Github is bugged and won't let me edit the previous comment, I mean, I already changed fps_max and confirmed that vsync is disabled, but the fps is still limited to 60

**Comment by Kezii** [comment]
`vblank_mode=0 ./minetest` seems to do the trick

**Comment by nathanfranke** [comment]
As stated above this should definitely be re-opened. A workaround is not a fix.

**Comment by rubenwardy** [comment]
as said:

> vsync = false does not guarantee that vsync will be disabled (other limits may still exist).

The reason for this is that graphic cards may still force vsync

**Comment by nathanfranke** [comment]
> Unconfirmed bug

I can reproduce this, although the behaviour seems a bit odd to me.
![image](https://user-images.githubusercontent.com/14253836/98078458-babe4b80-1e37-11eb-8843-803d1e84894f.png)
![image](https://user-images.githubusercontent.com/14253836/98078483-c447b380-1e37-11eb-95f0-ce83bde6e18e.png)
![image](https://user-images.githubusercontent.com/14253836/98078500-cd388500-1e37-11eb-82ee-23556ee95fc7.png)

**Comment by griffi-gh** [comment]
same issue on 120hxz display on android. vsync off, max_fps is set to 120
