### ISSUE TITLE
Inconsistent name of “Use” / “Aux1” / “AUX” / “special1” key

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7600]
##### Issue type
 - Bug report
 
##### Minetest version
0.5.0-dev

PC version and Android version.

##### Summary
The naming of the control referered to by the control setting `keymap_special1` is inconsistent in player-facing interfaces. The following names are used all for the same control:

* Special (PC version 5.0.0-dev, controls settings menu)
* AUX (Android version, GUI)
* aux1 (`minetest.conf` → `aux1_descends`)
* special1 (`minetest.conf` → `keymap_special1`)
* “Key for moving fast in fast mode” (`README.md`, `minetest.conf.example`)

Note I include `minetest.conf` and `minetest.conf.example` as “player-facing” since this is a configuration file, not a programmer's file.

Yes, we had this debate about the name of this key before, but can we AT LEAST agree to stick to ONE name and use it consistently everywhere? ;-)

Also note the description “Key for moving fast in fast mode” is only half-true. This key could also be used to descend if `aux1_descends` is true. Plus this key is sometimes used in mods (especially for sprinting it's popular), but I don't think this needs mentioning.

#### Solution

1. Pick ONE name for the control and stick to it (ideally case-sensitively).
2. Make sure the change is reflected in Minetest everywhere. Places which need to be touched:
    * `README.md`
    * `minetest.conf`
    * `minetest.conf.example`
    * `src/guiKeyChangeMenu.cpp`
    * The Android image for the button of this control (why is this not a real icon, anyway?)
    * Minetest Wiki
    * \<insert other places here\>

**Comment by paramat** [comment]
I agree completely, and as far as we can i would like to see the name/variables used in code cleaned up too.

**Comment by MuhdNurHidayat** [comment]
> The Android image for the button of this control **(why is this not a real icon, anyway?)**

I think the one who add that might not know what kind of icons could describe aux...
tbh, I don't know either... what icon could describe aux?? :smile:

**Comment by SmallJoker** [comment]
I got a very strong déjà vu moment. This aux/special/other discussion has already been discussed somewhere..
` aux` would be fine for me as well. If there will be any more keys, then they should have a clear name for what they're supposed to do. More than one aux key would be confusing (at least for me).

**Comment by Wuzzy2** [comment]
So, Aux it is, then?

If Aux is decided, all numbers should be dropped as well, because there's only one such key.

**Comment by paramat** [comment]
Yes, aux is decided.

> The Android image for the button of this control (why is this not a real icon, anyway?)

See the PR discussion, 'AUX' is internationally-recognised and understood, and it is difficult to find an icon that clearly has this meaning.
