### ISSUE TITLE
Formspecs can display larger than game window

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7603]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-74d27642 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=RELEASE
RUN_IN_PLACE=0
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

##### OS / Hardware

Operating system:lubuntu 18.04
CPU:intel

##### Summary

I use the setting gui_scaling = 1.4 and a 1920x1080 screen. The unified inventory is partially hidden:
![ou](https://user-images.githubusercontent.com/3192173/43466983-06713c46-94e1-11e8-8120-89a8233f9f1a.png)
If I adjust the window size, sometimes the whole formspec window is shown and sometimes a lot is missing (outside the minetest window).

##### Steps to reproduce

Use unified inventory or a similar mod with a big formspec, resize the minetest window and adjust gui_scaling.

**Comment by HybridDog** [comment]
> Duplicate of https://forum.minetest.net/viewtopic.php?f=6&t=20330 ?

Yes, thanks, I only searched on github for related issues.
Formspec is not scaled to fit into the window but somehow differently. I've tried an approximately squared window (height and width almost equal), a big one showed the complete formspec whereas for a small one the formspec was cropped.

**Comment by paramat** [comment]
Sorry, i don't understand part of the issue.
> I use the setting gui_scaling = 1.4 and a 1920x1080 screen. The unified inventory is partially hidden:

> Use unified inventory or a similar mod with a big formspec, resize the minetest window and adjust gui_scaling.

Surely it is expected that at a certain GUI scaling the GUI will become too big to fit on the screen? So don't use 1.4 or larger?

> If I adjust the window size, sometimes the whole formspec window is shown and sometimes a lot is missing (outside the minetest window).

This seems the actual issue, that once GUI scaling is set for the whole formspec to fit on the screen, changng window size shouldn't make it go off-screen, except for extremely small window sizes where it tends to hit a limit of smallness.

**Comment by HybridDog** [comment]
The problem is the formspec size adjustment when changing the window aspect ratio. I assume that it's possible to have a formspec which is not fully on screen with specific window sizes without setting gui scaling.

**Comment by HybridDog** [comment]
Here's another example:
![screenshot_20190927_191424](https://user-images.githubusercontent.com/3192173/65788356-2f19bc00-e15b-11e9-8e9e-ffc8d1e929a6.png)

**Comment by rubenwardy** [comment]
I swear formspecs larger than the screen are now scaled down, or did I make that up?
