### ISSUE TITLE
Minetest for android unusable

### ISSUE THREAD

**Issue by DavidRotert** [minetest/minetest#7604]
# Bug report

Device: Samsung Galaxy A5 2017
OS: Android 8
Minetest Version: 0.4.17

If I start Minetest on my android phone, it shows a start screen like you can see in the picture attached to this issue. I already tried to reinstall Minetest from Google play, but the bug is still there. I noticed that the controls do not react if I touch them directly but if I touch 1 cm under the control (the red point in the screenshot marks where I touched to start the game). It is also not possible to play in a world.

![screenshot](https://user-images.githubusercontent.com/27674913/43467712-a19b910c-94e2-11e8-97e6-e10be3046e44.jpg)

Edit: fixed in version 0.5.0

**Comment by DavidRotert** [comment]
I think the problem is the menu scale setting. After I changed the scale to 2, I had to reinstall Minetest.

**Comment by paramat** [comment]
Can anyone reproduce this?

**Comment by sfan5** [comment]
> Edit: fixed in version 0.5.0
