### ISSUE TITLE
Make Minetest more like Minecraft

### ISSUE THREAD

**Issue by DavidRotert** [minetest/minetest#7606]
# Feature request
Because Minetest is inspired by Minecraft, I think the Minetest engine or even Minetest Game should include features like mobs and buildings (villages, mineshafts et cetera) to make Minetest game attractive to people who want to play "Minecraft" for free. It would also be a bonus if Minetest has features or buildings which doesn't exist in the original.

**Comment by SmallJoker** [comment]
This issue is too vague. We're no copycats either.
minetest_game requests/ideas go here: https://github.com/minetest/minetest_game/ -- please use the search function before opening a new one.

**Comment by SmallJoker** [comment]
Suggestions are of course welcome - provided that they're submitted in the right repository. Minetest is indeed very close related to Minecraft, but it's not the main target to provide an open source clone.
All features which you listed can be added manually [using mods](https://forum.minetest.net/viewforum.php?f=11). Question is however, what should be bundled with the Minetest release ([roadmap here](https://github.com/minetest/minetest_game/issues/515)).

**Comment by paramat** [comment]
This subject is best discussed in MTGame as that contains all game content, there is an issue https://github.com/minetest/minetest_game/issues/515 but needs to be specific.
