### ISSUE TITLE
Add sun/moon and maybe stars to set_sky

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#7614]
##### Issue type

 - Feature request

##### Summary

Current usage: `set_sky(bgcolor, type, {texture names}, clouds)`
Desired usage: `set_sky(bgcolor, type, {texture names}, clouds, sun, moon, stars)`

Values are booleans, like `clouds`.

Example: `set_sky("#000000", "plain", {}, false, false, true, true`
This would simulate something like a planet with no sun, so no atmosphere (and therefore no clouds).

I am unsure how stars work, whether or not those are an overlay on the sky. If it is not an overlay, obviously a `stars` parameter wouldn't work.

~~I use the term `orbits` to include the Sun and Moon in one parameter, however, I do not like the term because technically the Sun doesn't orbit the planet, and `orbits` sounds kinda dumb anyway. I just don't feel that `sun` and `moon` should have their own parameters.~~
paramat pointed out, you could have a planet with a sun and no moon, or visa versa.

`get_sky` should of course be modified to return the new values as well.

Kind of related: https://github.com/minetest/minetest/issues/5669 https://github.com/minetest/minetest/pull/5672

**Comment by paramat** [comment]
Shall we close #6128 then as this contains that?

**Comment by GreenXenith** [comment]
> Shall we close #6128 then as this contains that?

No, these are entirely separate issues.
That one is for mods to set the sun and moon texture.
This one is for set_sky to show the sun and moon through the skybox. Not to set it.
The new parameters are booleans like the `clouds`.

**Comment by paramat** [comment]
Oops i misread, they are different.

**Comment by paramat** [comment]
I think sun and moon should have separate bools. A sun but no moon is possible for a planet.

**Comment by GreenXenith** [comment]
> I think sun and moon should have separate bools

Yes, I see that now. Edited first post, also added example.

Can someone confirm how stars work and whether that is an overlay or not?

**Comment by GreenXenith** [comment]
PR #7691.

**Comment by paramat** [comment]
:+1:

**Comment by appgurueu** [comment]
I think this can be closed now.
