### ISSUE TITLE
Entity attached to a bone on a .x model is incorrectly transformed

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#7619]
##### Issue type

 - Bug report
 
##### Minetest version

```
minetest-5.0.0-ca502fc-win64
```

##### OS / Hardware

Operating system: Windows
CPU: x86-64

##### Summary

Attaching a CAO to a bone on a player's skeleton does not work as expected.
The attached model receives an inverse of the bone's transformation, and instead of being rooted to the bone's position, it's transforming around the parent object's origin. ( that is, feet )
Sometimes the attached model does not appear at all.
Tested with .x models and CAO-to-player attachment only. May or may not affect every model format and entity-to-entity attachment.

![inverse](https://user-images.githubusercontent.com/42101236/43681239-a3f8635e-983d-11e8-891d-69a40e51d0a2.gif)

##### Steps to reproduce

Attach an entity to some bone on a player's model ( head, hand, whatever ). Grant yourself flying, fly up a little, and look at the model in third person mode.

Repro mod: ( runs in minimal )
[attachments_suck.zip](https://github.com/minetest/minetest/files/2259892/attachments_suck.zip)

**Comment by SmallJoker** [comment]
Relevant code:
https://github.com/minetest/minetest/blob/18368824958139f1428d534082852d778982b4c9/src/content_cao.cpp#L1252-L1261

**Comment by rubenwardy** [comment]
Usually. But usually there's a workaround we're supposed to be doing

**Comment by stujones11** [comment]
> Is it an Irrlicht bug, then?

Either Irrlicht or the blender exporters as the results vary depending on the mesh format. You can verify this with the simple mesh viewer app I made. https://github.com/stujones11/SAM-Viewer

Note that the model included with the app has been 'tweaked' to work around the issue.

**Comment by hecktest** [comment]
Okay, you're on to something here. This is the same file exported as .x
![blah](https://user-images.githubusercontent.com/42101236/43799677-b8cdb1ac-9a7d-11e8-8e26-44f6322abc74.gif)
But this doesn't end here; the X exporter has four possible coordinate spaces to choose from.
The broken one up there is Lefthanded Y-up.
Lefthanded Z-up actually looks right, but is rotated 90 degrees backwards.
![left_z](https://user-images.githubusercontent.com/42101236/43800322-7cdd69ba-9a7f-11e8-8e64-abb82037d7ed.png)
In both righthanded Z and Y-up the model looks fine but it's flipped across Z.
![right_y](https://user-images.githubusercontent.com/42101236/43800417-c55d787e-9a7f-11e8-9a03-806131109486.png)
Maybe a simple transformation can be applied as a workaround, to let people use one of the modes where attachment works.
The exporter for .x ships with Blender, so supporting this format would be nice.

**Comment by rubenwardy** [comment]
Not sure what you mean, Minetest already supports .X because irrlicht does http://irrlicht.sourceforge.net/?page_id=45

**Comment by hecktest** [comment]
Of course, it's just that attachments on .x are broken when the model is exported in the proper coordinate space. What I'm saying is that a workaround for this would have some value, even if it's easier to tell everyone to just use b3d.

**Comment by stujones11** [comment]
> Lefthanded Z-up actually looks right, but is rotated 90 degrees backwards.

IIRC If you export with the right-handed coordinate system the attachments work, only everything else is reversed ;)

**Comment by hecktest** [comment]
Closing this as not-a-bug; the issue lies entirely with Blender's exporter.
The exporter does not, in fact, apply any coordinate system conversions, despite the options available. All it does is change the face winding order and apply an extra matrix to the scene root.
The compounded transformations somehow result in the mesh getting skinned correctly against its bindpose (world to bone space matrix), but since the bindpose does not apply to attachments, the transformation is flipped for those.
A model built in minetest's coordinates will work as expected.
