### ISSUE TITLE
Combine the two menus on Android into one

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7622]
There are two menus on Android:

* ... on the left for chat, inventory, and drop item
* gears on the right for settings

I'd like to see this combined into one menu on the right which covers the whole screen in a grid. Double tapping where this menu is should open then close it, as the position when the menu is opened should change into a cros to close it

**Comment by MoNTE48** [comment]
The current implementation is terrible and extremely uncomfortable.
The new player is difficult to understand how to find inventory, for example. While I understand what I want to press, the menu closes itself. Stupid Idea

**Comment by rubenwardy** [comment]
My proposal would allow for both an icon and some text in the grid, helping with that

**Comment by MoNTE48** [comment]
I believe that we need to turn off auto-hide.
And also put the inventory opening button somewhere so that it can be opened with 1 click

**Comment by srifqi** [comment]
@rubenwardy Any suggestion about the grid's composition? Any example probably?
