### ISSUE TITLE
Infotext and debug shows up as gray text

### ISSUE THREAD

**Issue by style-nine** [minetest/minetest#7623]
##### Issue type

 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-88efebd

```

##### OS / Hardware

Operating system: Ubuntu 18.04
CPU: AMD

GPU model: nVidia GeForce GTX 1050
OpenGL version: 4.6.0 NVIDIA 390.48

##### Summary

Infotext and debug lines in the GUI show up as gray text (which makes it very difficult to see at times).

##### Steps to reproduce

Hit F5 or use a furnace and look at the infotext for it.
![screenshot](https://user-images.githubusercontent.com/41269111/43690292-f84e628a-98d5-11e8-800c-aa6b61e684e4.jpg)

**Comment by SmallJoker** [comment]
Does the issue disappear by reverting 1836882?

**Comment by style-nine** [comment]
Ah, yes. That does seem to be it. Thank you.
