### ISSUE TITLE
Custom models for wielditems

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7624]
##### Issue type

 - Feature request

##### Summary

Items should be able to register their own wielditem models, and the wield_image should be used as a fallback option. While extruding wield images is a simple solution to rendering wielditems, they're hacky at best and just aren't qualified enough to render wielditems such as guns and other special items.

**Comment by hecktest** [comment]
Seconding.
In addition to setting a wield model, let me control when and how animations are played for it.

**Comment by rubenwardy** [comment]
Duplicate of (...finding issue...)
