### ISSUE TITLE
Allow different description values for items with different palette indexes

### ISSUE THREAD

**Issue by AlexYst** [minetest/minetest#7634]
##### Issue type
 - Feature request
 
##### Minetest version
```
0.4.17
```

##### OS / Hardware
Operating system: Debian
CPU: 64-bit something, but irrelevant

##### Summary
The new palette_index feature has a lot of potential for defining very similar nodes using a single node definition. However, it has one very glaring flaw: all these nodes have the same description in an inventory. Depending on how similar the items look, they may or may not be easily distinguished by the player. Depending on the nature of the items, even a colour difference might not be enough.

For example, a paletted wool node might want to have red wool labelled as "Red Wool" instead of just "Wool", while cyan wool may be better labelled as "Cyan Wool". In this case, a player gets enough information from the name "Wool", but it'd look nicer to have custom descriptions. On the other hand, if the item is a lump, knowing if it's a "Gold Lump", "Silver Lump", "Tin Lump", et cetera can be exceedingly helpful. Knowing the general colour isn't really good enough.

Per-stack descriptions can be set using the "description" key of the stack's metadata. However, this misses the point semantically. It's not a custom stack, it's just a stack of a particular palette index. All normal stacks of that same type with the same palette index should have the same description in most cases. Furthermore, it's not even just a semantic issue, but a usability issue. In many cases, the "description" key can be lost, such as when a player places and later digs up a node. They'll place down a "Steel Block" and dig back up a "Generic Metal Block". In the case of the "preserve_palette" drop flag, there's also no good way to specify what value to set for the "description" key.

I propose adding a new key to the item definition tables. It could be named "palette_description" or "palette_index_description", for example. Currently, the description is first looked for in the "description" value of the stack, then def.description, and finally, if both are missing, the item name itself is used. I propose that if the item has a palette index set, after checking to be sure a "description" key isn't present in the stack's metadata, the client should check to see if the def.palette_description[<palette_index>] is set and use that if available. After that, it should fall back to the def.description value, and finally the item name as per usual. For example:
```
minetest.register_node("mod:metal_block", {
	description = "Generic Metal Block",
	palette_destription = {
		[0] = "Gold Block",
		[1] = "Steel Block",
		[2] = "Tin Block",
		[3] = "Copper Block",
		[4] = "Bronze Block",
-- ...
	},
})
```

##### Steps to reproduce
Define an item that uses a palette to define many versions of itself. Notice how all versions of this item share the same def.description value.

**Comment by paramat** [comment]
Seems a valid issue and request.
