### ISSUE TITLE
Fetch packages every time the content store is displayed

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7635]
##### Issue type

 - Bug report / Feature request

##### Summary

Judging from the logs, it looks like packages from the ContentDB are retrieved only on the first attempt to open the content browser. Isn't refreshing the data on every access the expected behaviour? Currently, the retrieved package-list is cached and displayed every time. Maybe the issue detailed in #7447 is just a one-time occurence, and re-fetching would correctly retrieve the packages the next time...

**Comment by paramat** [comment]
:-1:
