### ISSUE TITLE
Ability to implement simple range-based animations and transformations for HUD elements

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7639]
##### Issue type

 - Feature request

##### Summary

Take for example a simple HUD text element. If one wants this element to "fade out" instead of just abruptly disappearing, they'd have to invoke `hud_change(id, def)` on every global-step, which would cause quite a bit of lag - the relevant packet is sent to the client on each step, which causes unnecessary consumption of bandwidth.

Instead, if there was a generic HUD animation function which takes an ID, start and end values, a duration, and the def field to apply the range to, this would result in just _one_ packet sent from the server to the client. The client then does the hard-work of modifying the HUD element's chosen field from start val to end val for the duration specified. This can be used for moving elements, rotating elements, and even animation using elements.

Example method:
```
ObjectRef:hud_animate(id, field, start, end, duration)
```
Example usage:
```
local id = player:hud_add({
    hud_elem_type = "text",
    position = { x = 0, y = 0 },
    offset = { x = 0, y = 0 }
    text = "TEXT"
})

-- Move HUD element from upper-left corner to upper-right corner
-- over a duration of 10 seconds
player:hud_animate(id, "position", {x = 0, y = 0}, {x = 1, y = 0}, 10)
```

**Comment by paramat** [comment]
The examples given, fading out and moving text, are frivolous and completely unnecessary. Other effects might be useful though. Please let's find some useful effects before doing this.

**Comment by ClobberXD** [comment]
Those are just examples, but I agree that they aren't the best. The moving text example was to just demonstrate how the function would work. :)

**Comment by ClobberXD** [comment]
Another major use-case: #5212 :)
