### ISSUE TITLE
send_chat_message truncates 4 byte utf8 strings (codepoints > 0xFFFF)

### ISSUE THREAD

**Issue by monolifed** [minetest/minetest#7643]
##### Minetest version

```
0.4.17.1
```

##### Summary
send_chat_message truncates 4 byte utf8 strings (codepoints > 0xFFFF)

##### Steps to reproduce

Client side mod lua script:
```lua
-- command .dummy
minetest.register_chatcommand("dummy", {
	params = "<arg>",
	description = "Dummy function",
	func = function(param)
		local message = "[\xF0\xA0\x80\x8B]" -- [𠀋] \U0002000B
		minetest.log(message) -- works:  visible in debug.txt
		minetest.display_chat_message(message) -- works: visible in game
		minetest.send_chat_message(message) -- doesn't work: truncated to 0x000B
		
	end
})
```

Note: Sorry, if this is already fixed or duplicate. I couldn't find a relevant issue.

**Comment by SmallJoker** [comment]
Was this already an issue in 0.4.16 and 0.4.17 or is it especially for 0.4.17.1?

**Comment by rubenwardy** [comment]
Does this happen with `minetest.chat_send_all` on the server-side?

**Comment by Lejo1** [comment]
I'm using the stable-0.4 branch on Ubuntu 18.04.
I only see the correct output in the debug and not like @monolifed in the "client chat"
This is also the same for [0xFFFF codepoints](https://forum.minetest.net/viewtopic.php?f=53&t=20003&p=340645#p340201).
It would be great to have this thing working to chat with emojis or other cool things.

**Comment by LoneWolfHT** [comment]
The default MT PC font doesn't support Chinese characters. It also doesn't support quite a few others

**Comment by Lejo1** [comment]
Do you know one which supports almost everything, just because the fallback doesn't supports "ö"

**Comment by Lejo1** [comment]
6 Byte long characters like € also seems to work so the problem is only 8 Byte

**Comment by nerzhul** [comment]
@Lejo1 can you do same test on master as we are in feature freeze for 5.0.0 ?

**Comment by LoneWolfHT** [comment]
@Lejo1 I use this font https://en.wikipedia.org/wiki/GNU_Unifont
I'm not sure if I'm allowed to give you my copy. I think the .ttf file here http://unifoundry.com/unifont/index.html is the one you want

BTW: Switching to the fallback font fixed it. https://forum.minetest.net/viewtopic.php?f=53&t=20003&p=340661#p340661

**Comment by Lejo1** [comment]
@nerzhul I tested it.
It's same in 0.4.17 and in 5.0.0

**Comment by nerzhul** [comment]
maybe we have a std::string instead of std::wstring somewhere ?

**Comment by Zughy** [comment]
I was trying to reproduce this, enabling CSM and putting the font @LoneWolfHT suggested. This happens:
![imagen](https://user-images.githubusercontent.com/63455151/106173636-73283100-6194-11eb-833f-9e98b9b1a4e8.png)

did I miss something?

**Comment by rubenwardy** [comment]
![image](https://user-images.githubusercontent.com/2122943/106174227-aff02a00-618c-11eb-90a0-c4407b0a7777.png)

**Comment by rubenwardy** [comment]
Worth noting that this also doesn't display with display_chat_message or the log

**Comment by Zughy** [comment]
> Perhaps the \?

Nope
