### ISSUE TITLE
Support moving targets for HUD waypoints

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7646]
##### Issue type

 - Feature request

##### Summary

This would allow objects to be marked/tagged. Since positions of all objects are already being sent to the client on every step, this functionality just requires the waypoint to keep track of its target and update accordingly. While there is always the hacky workaround of having to `hud_change` every step for each "tagged" object, this causes excessive wastage of bandwidth and probably CPU usage too.

### Use-cases
- Ability to see only select players in team-oriented games.
- "Tagging" animal mobs, essentially simulating other forms of tracking like GPS, radio collar, etc.
- Fancy missions, chases, etc. where the objective is marked and tracked in real-time

**Comment by SmallJoker** [comment]
> Since positions of all objects are already being sent to the client on every step [...]

That's where you're wrong. In fact, attachments on join are also broken for a similar reason. The objects are only sent to the client when the player is near enough - or - when the object is a player and the transfer distance for them is high enough.
The client simply does not know about any objects which are too far away - it would also pull the FPS rate down depending on the mesh update rate.

**Comment by ClobberXD** [comment]
Ahhh... I overlooked that part. Thanks for pointing that out. So I'm assuming that this can't be implemented - thanks for your time. :)

**Comment by ClobberXD** [comment]
@SmallJoker I was wondering if this was possible for players, since they are actively tracked no matter how far they are... or am I mistaken?

**Comment by SmallJoker** [comment]
@ClobberXD The positions of the players are always known - on server side. The client, however, does only know about the players which are in their sight. So in order to implement your feature it would be necessary to either send the player positions just for that single usecase - or to send all affected players to the client, depending on the HUD elements.
So if you update the waypoint HUD for every second or third move the player makes, the transferred data will be roughly equal.

**Comment by ClobberXD** [comment]
> The positions of the players are always known - on server side. The client, however, does only know about the players which are in their sight.

Aha, thanks for clarifying. I guess tracking players is still possible this way, albeit at a much lesser accuracy, by updating the waypoints in a globalstep every 0.5 seconds or so. But the inability to track non-player entities is still an issue, as they could get unloaded if the player moves far away. Is there any workaround to achieve this?

**Comment by SmallJoker** [comment]
@ClobberXD Anything besides forceloading the mapblocks where the entity is in? No. That's how the map loading & saving works.
