### ISSUE TITLE
Game freezes when trying to add animation to particle definition in particlespawner

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#7649]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-2b83af78 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### Summary

I tried to create a particlespawner which creates animated particles and the game completely freezes.

##### Steps to reproduce

This is the code which causes the game freeze:

```
  minetest.add_particlespawner({
    amount = 10,
    time = 0.0625,
    minpos = pos,
    maxpos = pos,
    minvel = {x = -5, y = -5, z = -5},
    maxvel = {x = 5, y = 5,  z = 5},
    minacc = {x = 0, y = 0, z = 0},
    maxacc = {x = 0, y = 0, z = 0},
    minexptime = 0.0,
    maxexptime = 1.0,
    minsize = 8,
    maxsize = 16,
    collisiondetection = false,
    vertical = false,
    texture = "animated_texture.png",
    animation = { type = "sheet_2d", frames_w=2, frames_h=2, frames_length=0.5 }
  })
```

**Comment by paramat** [comment]
Please could you link to your code if possible or post the texture sheet here to make testing easier?

**Comment by paramat** [comment]
I'm working on particles now and see a possible error that might cause this.
https://github.com/minetest/minetest/blob/34f940dccae53ac62177d2555c63688fce90519d/src/network/clientpackethandler.cpp#L961

**Comment by paramat** [comment]
@ryvnf please could you post the texture sheet here (drag and drop into a comment) to make testing easier?

**Comment by ryvnf** [comment]
I used the `default_lava_source_animation.png` texture. It appears that the problem could be because I assumed it was a 2D animation, because I based my code on the `experimental:tester_tool_2` in the minimal game.

Tried changing it to `vertical_frames` animation and it worked.

Sorry for wasting time. I close this now.

**Comment by paramat** [comment]
Good news!
