### ISSUE TITLE
Alt-Tab and Alt-F4 don't work with fullscreen on Ubuntu 18.04

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7654]
##### Issue type

 - Bug report
 
##### Minetest version

```
(Latest) 5.0.0-dev
```

##### OS / Hardware

Operating system: Ubuntu 18.04 (Bionic Beaver)

##### Steps to reproduce

- Add `fullscreen = true` to minetest.conf
- Open game, try Alt-Tab and Alt-F4

**Comment by TssT16** [comment]
I have the same issue. From Archlinux

**Comment by Calinou** [comment]
This is because Minetest emulates exclusice fullscreen on Linux, which makes alt-tabbing impossible. To solve this, keep `fullscreen = 0` and use a borderless fullscreen window as provided by your window manager.

**Comment by Hiradur** [comment]
I'm not an expert on the matter but I always thought that exclusive fullscreen only means that the desktop compositor is bypassed for improved performance. I don't think exclusive fullscreen should prevent `ALT+TAB` from working.
@Calinou: What do you mean by
>Minetest emulates exclusive fullscreen

How can exclusive fullscreen be _emulated_ but not be a borderless window?

**Comment by Calinou** [comment]
> How can exclusive fullscreen be emulated but not be a borderless window?

X11 does not actually have exclusive fullscreen, hence "emulated".

**Comment by sfan5** [comment]
https://github.com/minetest/irrlicht/compare/393793f...c84d8ac

**Comment by HybridDog** [comment]
I created a small testing mod to see tearing and missing frames: [for_mt.zip](https://github.com/minetest/minetest/files/6664615/for_mt.zip)
The mod adds a node with an animated black and white texture where the texels visually change at rates 7.5, 15, 30 and 60 times per second. 
I use openbox and an intel GPU. If I don't start a compositor, e.g. compton, I can see tearing if and only if minetest is windowed, so I think Minetest bypasses the compositor in fullscreen mode.
