### ISSUE TITLE
LBM documentation is confusing

### ISSUE THREAD

**Issue by numberZero** [minetest/minetest#7660]
Actually, only LBM definition is documented, but not what LBM itself is. And it is a bit confusing:
```lua
        run_at_every_load = false,
        -- Whether to run the LBM's action every time a block gets loaded,
        -- and not just for blocks that were saved last time before LBMs were
        -- introduced to the world.
```
1. “LBMs were” should probably be “the LBM was.”
2. If an LBM is removed and then re-added, is it considered newly introduced? (According to [one comment](https://github.com/minetest-mods/technic/pull/437#discussion_r211086167), it is. But that doesn’t seem to be the intended behavior)

**Comment by paramat** [comment]
These 2 lines seem unnecessary and only confuse:
```
        -- and not just for blocks that were saved last time before LBMs were
        -- introduced to the world.
```
Especially if more description is added.
