### ISSUE TITLE
Should vsync be disabled?

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7678]
##### Issue type

 - Question
 
##### Summary

There are two settings which affect vsync: The `vsync` setting in minetest and the global vsync configuration. 
`vsync` is set to false by default, but FPS are still limited (see #7597), according to [irrlicht doc](http://irrlicht.sourceforge.net/docu/structirr_1_1_s_irrlicht_creation_parameters.html#a33b07682f12db0d2c2c3a7bf74f64387) the setting may be silently ignored, so I think the `vsync` can only be used to force-enable vsync.
Globally the vsync setting can be disabled on Linux by setting vblank_mode to 0, you can e.g. start minetest like this: `$ vblank_mode=0 minetest`.
With low fps, [vsync reduces fps even more](http://www.tomshardware.co.uk/forum/id-1899854/turn-vsync-fps.html#r12034714).
Minetest also has a fps_max setting, I think there's a way to find if the game can be rendered with double frame rate than fps_max when fps_max is set.
Can vsync be automatically toggled during runtime, when minetest fps is below fps_max it's enabled and when the possible fps exceeds 2 * fps_max it's disabled?

**Comment by Calinou** [comment]
> Can vsync be automatically toggled during runtime, when minetest fps is below fps_max it's enabled and when the possible fps exceeds 2 * fps_max it's disabled?

Not all engines support toggling V-Sync at run-time. (Generally, older ones do not.)

**Comment by HybridDog** [comment]
Is there a way to enable [Adaptive Vsync](https://www.khronos.org/opengl/wiki/Swap_Interval#Adaptive_Vsync) on Irrlicht?

**Comment by HybridDog** [comment]
If the `vsync` setting can only be used to force-enable vsync, should its documentation be changed?
