### ISSUE TITLE
disable jump in liquids

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#7687]
##### Issue type
Bug report
 
##### Minetest version
0.4.16 and above

##### OS / Hardware
Operating system: Linux
CPU: 64-bit

##### Summary
The {disable_jump=1} group works well with normal nodes, but once it has been applied to liquids it still allows players to swim up using jump key which should be disabled.

##### Steps to reproduce
Check out ethereal quicksand, you can easily swim to the top by jumping instead of sinking the the bottom.

**Comment by SmallJoker** [comment]
Duplicate of #4494

**Comment by paramat** [comment]
Doesn't seem a bug, swimming is not jumping.
