### ISSUE TITLE
Improve Raycast API by allowing to check how much distance ray passed each node

### ISSUE THREAD

**Issue by ryvnf** [minetest/minetest#7690]
##### Issue type

 - Feature request

##### Summary

The raycast API is nice. But it lacks something that makes it quite hard to use for some applications.

The problem is that it will return all nodes the ray passes through, but does not expose any way to check how deep it goes through each node. This makes it problematic for applications to create Raycasted explosions or lasers, where the rays to get weaker proportional to the material the ray passes through. The simple way of simply assuming the ray passes the same distance through all nodes does not work as the amount of nodes passed will vary greatly depending on the direction, even when rays casted have the same range.

##### How this could be implemented

Maybe add one more field to the table returned by raycast which specify how much the ray passes through the node.

###### Example

```
    -- trace ray, which will die when the total resistance of nodes it has passed is 1000
    local pos1 = player:getpos()
    local ray = minetest.raycast(pos1, pos2, false, true)
    local ray_strength = 1000
    for pointed_thing in ray do
      local nodename = minetest.get_node(pointed_thing.below).name
      ray_strength = ray_strength - pointed_thing.distance * node_resistance[nodename]
      minetest.remove_node(pointed_thing.below)
    end
```

I think calling it `pointed_thing` might be misleading if such a field is added. But I think that the advantages of introducing something like this to the API is worth it.

**Comment by raymoo** [comment]
Does raycast expose t-values? If not, exposing them could be a lightweight way to support this use case (just subtract consecutive t values to get the distance traveled through a node). It would also allow getting the position of the ray intersection.

**Comment by juhdanad** [comment]
You can get the hitpoint for all nodes since #6304 by:
```lua
local hitpoint=pointed_thing.under+pointed_thing.intersection_point
```
If you find two hitpoints, you can start another raycast between them in the other direction to find the exit point of the original ray (also, between the last hitpoint and the end of the ray). Then the distance is (in almost all cases) the distance of the enter and exit points.

I hope this helps.

**Comment by paramat** [comment]
Good advice, sorry i didn't think of this :)
