### ISSUE TITLE
[Discussion] Drop DirectX and Software drivers.

### ISSUE THREAD

**Issue by Megaf** [minetest/minetest#7694]
Hello everyone,
Let's use this issue for all discussion related to video drivers.

Over and over again I see people reporting problems with the software render, https://github.com/minetest/minetest/issues/7671 being the last example.
As far as I know, almost no one, if anyone at all is actually using the software driver. It has been neglected for years now.

Similar story with the Direct3D driver, it's a hit and miss depending on Windows version and GPU version and vendor.

I suggest we stick to some version of OpenGL 3 specification and make the best out of it. Focusing all graphical efforts on it. And when it is complete and stable enough then we can move to something else.

I do believe that will be the right choice, since it is widely used, multi platform and reliable API/Lib.

So, what do you have to say? Shall we focus our graphical efforts and amazing shaders on OpenGL only, making the best out of it?

**Comment by raymoo** [comment]
Are there specific things those renderers are currently holding back?

**Comment by sfan5** [comment]
Those drivers are provided by Irrlicht not by us, there is no advantage in dropping support for them and there currently is no need whatsoever to do so.

**Comment by Megaf** [comment]
> there is no advantage in dropping support for them and there currently is no need whatsoever to do so. 

One of the reasons for dropping support would be preventing confusion many users face when selecting the driver and the frustration it causes when the drivers selected does work well.

I've been in the situation myself on widows machines and experienced inverted inventory icons, swapped colors and broken shaders.

All easily avoided if we focused on OpenGL.
Also, I do not know how our shaders are done. I don't know if we use Irrlicht shaders or if we created our own.

Sometimes we just blame upstream and sometimes we create our own solution, an then change, particles is a recent example.

I believe it is time we focus on something and build on it
Not offering this possible source of confusion would be an easy enough move,

**Comment by Megaf** [comment]
@raymoo 
> Are there specific things those renderers are currently holding back?

Yes, the dev team. It's all about we exchanging ideas and improving from there. That's why I created this, to talk about it.

**Comment by sfan5** [comment]
> One of the reasons for dropping support would be preventing confusion many users face when selecting the driver and the frustration it causes when the drivers selected does work well.

My question to those users would be: what are they are doing in the "advanced settings" menu if they do not understand the settings they are changing?

I get that the variety of choices, of which 50% "don't really work" is confusing. But this isn't a user-facing setting, it's hidden in the depths of advanced settings, you are not supposed to choose a driver.

**Comment by Megaf** [comment]
What's the default driver? OpenGL? Is it always the default?
Any check performed on startup to select a driver?
How does it work?

**Comment by Megaf** [comment]
Thanks.
Now, since OpenGL is the default and hidden.
And we are not using our precious time and dev skills on redundant work, since Irrlicht is doing that for us.
I believe we can close this issue. Thanks for all clarifications!
