### ISSUE TITLE
"name" key in .conf no longer works in 5.0.0

### ISSUE THREAD

**Issue by slbelden** [minetest/minetest#7698]
- Bug report
 
##### Minetest version
```
Minetest 5.0.0-a4f41e7-a4f41e7-dirty (Windows)
```

##### OS / Hardware

Operating system: Windows 10

##### Summary
As described in [the Wiki Privileges page](https://wiki.minetest.net/Privileges), "In multiplayer servers, the player whose name equals the minetest.conf setting `name` automatically has all privileges and all of these are irrevokable."

In the current stable release, this works. In the latest build, it doesn't. The player named by `name` gains no special privileges.

##### Steps to reproduce
These steps are identical in both 4.x stable and 5.0.0 dev.

1. Ensure your minetest.conf contains `name = [your in-game username]`
2. Start a new multiplayer server by running `minetest.exe --server`
3. Join this multiplayer server by connecting to 127.0.0.1 with this same in-game username
4. Try to run a privileged command, such as `/time 0`

The priveleged command succedes in 4.x, and fails in 5.0.0 with error `You don't have permission to run this command (missing privilege: settime).`

**Comment by rubenwardy** [comment]
This behaviour has unfortunately changed due to crappy privileges in minetest game breaking game play when force granted

**Comment by SmallJoker** [comment]
```
/grantme all
/time 0
```

**Comment by slbelden** [comment]
Thank you, that command worked. I think there is room for a simple improvement here:

## Problem
You still need `name = [username]` set in minetest.conf for `/grant` to work. This is confusing, because it means that some permissions are granted by `name = username` (namely, the `privs` privilege necessary to use `/grant`, as well as `server`, `kick`, `ban` and others) but does not grant others (like settime). Additionally, this causes the named user to have different in-game privileges than those granted to them in `auth.txt`.

## Possible Solution
Run `/grant [username] all` automatically when a user with a name matching `name = [username]` joins a server.

This restores the old 4.x behavior, so existing documentation remains correct, *and* it updates auth.txt to match the user's actual privileges.

**Comment by SmallJoker** [comment]
@slbelden The issue was that admins could not leave the creative mode because it was given to them automatically. Server admins had to use an alt account to ensure they've got only the privs that they need. Since the grant command works (and also revoke), an admin can play on the server just like a regular user if they want to.

**Comment by slbelden** [comment]
Wait, are you saying gamemode is implemented as a permission?

**Comment by rubenwardy** [comment]
Unfortunately, yes. I detest it
