### ISSUE TITLE
Formspecs: Progress-bar elements

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7699]
##### Issue type

 - Feature request

##### Summary

Example `progressbar` formspec element:
```
progressbar[x,y;w,h;min,max;curr]

(or)

progressbar[x,y;w,h;curr_value_as_percentage]
```

There are even progress-bar HUD elements. I feel that the ability to embed progress bars in formspecs will go a long way in the quest for better formspecs. :)

**Comment by GreenXenith** [comment]
:+1: but how would one go about progressing the progress bar? Changing the formspec over and over just to set the current value seems unnecessary.

**Comment by rubenwardy** [comment]
This is already possible using backgrounds: https://github.com/rubenwardy/awards/blob/master/gui.lua#L122

**Comment by niansa** [comment]
This would add a way to show Download progress in content manager.

**Comment by rubenwardy** [comment]
> This would add a way to show Download progress in content manager.

This isn't the biggest obstacle for doing that as it's already possible to have progress bars

**Comment by ClobberXD** [comment]
> Changing the formspec over and over just to set the current value seems unnecessary.

That currently seems to be the only way forward, unfortunately.

> This is already possible using backgrounds

Then why not make it more straight-forward to use by adding a `progressbar` element? :)
