### ISSUE TITLE
Add support for player glow effects

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7700]
##### Issue type

 - Feature request

##### Summary

Nodes already support different light levels. I suggest allowing objects to support light levels for effects like player-glow, ability to highlight item-drops etc. However, this might be tougher to implement since objects aren't stationary...

**Comment by tenplus1** [comment]
We already have glowing particle effects so I dont see why entities aren't able to have their light settings manipulated also to make them stand out from the dark :)

**Comment by rubenwardy** [comment]
Wasn't there an entity glow feature that was merged?

**Comment by paramat** [comment]
Yes.
https://github.com/minetest/minetest/blob/a4f41e7bfc6c2d823eab1465258617cb033a452c/doc/lua_api.txt#L5533

**Comment by ClobberXD** [comment]
This seems to be possible already. Closing issue, sorry for the trouble :)
