### ISSUE TITLE
Item Def: New field inv_max

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7702]
##### Issue type

 - Feature request

##### Summary

There's already `stack_max` which corresponds to the maximum number of items per-stack. I'm sure an `inv_max` (corresponding to the maximum number of items per-inventory), would be just as useful if not more, than `stack_max`. While this is already possible by using `InvRef:contains_item`, it's much more complex, as this check would have to exist in numerous places to actually restrict the number of items in an inventory.

**Comment by SmallJoker** [comment]
And how do you imagine backwards-compatibility? Node and item definitions default to 99, but a mod might change that manually to a different value. Now you would like to introduce a new maximal value, which is inventory-dependant.
Question: Which maximal value should be taken? The smaller of both? Inventory only and ignore the item definition?

**Comment by GreenXenith** [comment]
Always follow inv_max unless
`override_inv_max = true`?

**Comment by paramat** [comment]
I get the feeling this will be problematic, and i can't see any advantage or need :-1:

**Comment by GreenXenith** [comment]
I personally think there should be an entity-like system for items/nodes like `item:set_properties({tiles={"default_dirt.png"}, inventory_image = "default_stone.png"})`
But that's just me and almost unrelated to this, and worth it's own issue.

**Comment by ClobberXD** [comment]
@SmallJoker If `inv_max` isn't explicitly set, inventory restriction should be ignored, similar to how `stack_max` defaults to 99. I don't see why this would affect backwards compatibility.

**Comment by paramat** [comment]
If a player has many stacks of a node, then the feature is added setting a low 'inv max', the player loses nodes from inventory?
Still see no need or usefulness.

**Comment by raymoo** [comment]
@paramat That doesn't sound any different from the problem of if a node is modified to have a lower `stack_max`. I agree though that there isn't a clear need for `inv_max`. @ClobberXD Do you have a concrete use case where you would want to use `inv_max`?

**Comment by rubenwardy** [comment]
I don't like this. It feels expensive and inconsistent, and potentially confusing

**Comment by ClobberXD** [comment]
@raymoo This could be used to set a hard limit on how much of the item a player can stack up, irrespective of the stack_max.

Think of this as a way to ration items. Irrespective of how commonly available an item is, if only a maximum of `x` should be allowed, `inv_max` can be set to `x`. Without this feature, one would have to add `InvRef:contains_item` in all possible callbacks to prevent the player from obtaining the item in "other" ways.

**Comment by raymoo** [comment]
@ClobberXD What's an example of an item you would want to ration?

**Comment by ClobberXD** [comment]
Magical items, maybe? Anything that requires a player to have only one of...

**Comment by raymoo** [comment]
@ClobberXD Can you give an example of a specific (hypothetical) item? Like a real example you could go out and code right now from just the description, except for the fact that inv_max doesn't exist. (And why inv_max is important for it)

**Comment by ClobberXD** [comment]
Ah, I understand now... Take for example apples. A server (like CTF) would want to limit the number of apples that a player can have, irrespective of its `stack_max`, in order to level the playing field. Even if apples are abundant in the world, a player should not be able to stack up more than `n` apples, since apples provide instant HP and can be "spam-clicked" to simultaneously heal the player while fighting.

Again, apples can be limited to a certain number by having an `InvRef:contains_item` method within an `on_dignode` callback, but what if players take apples from chests? CTF uses a treasure-chest-spawning mod, so the `on_dignode` callback is circumvented in this case. So another callback needs to be added, this time to check if player has crossed the maximum in an `inventory_move` callback. Now... what if there is a (hypothetical) machine that gives apples to players when punched? The machine's code should also be modified to respect this limit.

Hence my proposal to add an `inv_max` field which would serve as a hard-limit on how much of an item an inventory can accommodate. Existing mods won't be broken, since not defining an `inv_max` in the item def will disable the limit. As you can understand, this extra field in the item def eliminates the need for adding numerous checks to prevent circumventing a set limit in every possible way.

I hope that this example is sufficient to clarify things. :)

**Comment by paramat** [comment]
2 disapprovals and no core dev support.
