### ISSUE TITLE
Formspec scrollbars: option to move directly to the clicked position

### ISSUE THREAD

**Issue by 12Me21** [minetest/minetest#7710]
##### Issue type
 - Feature request

Normally, slider-type inputs will jump directly to the clicked position when you click on them, while scrollbars will only move towards that spot. Because minetest formspecs use the same thing for both input types, I think there should be an option to have the alternate behavior.

![image](https://user-images.githubusercontent.com/4053256/45231689-dc910780-b29a-11e8-8383-f0db34aec667.png)

For this input, it would make more sense for the slider to go directly to the cursor position when clicked, rather than only moving ~100 units like it does now.

**Comment by paramat** [comment]
Would be nice, but this formspec behaviour may be out of our control as i believe it is part of Irrlicht.

**Comment by SmallJoker** [comment]
The step for clicking the slider background (large step) is a fixed number. I did not test it, but very high values might cause the slider to shoot over the wanted position.
https://github.com/minetest/minetest/blob/766fb7b46edab47f96b8b940e390daf5319261b7/src/gui/guiFormSpecMenu.cpp#L513-L520

**Comment by DS-Minetest** [comment]
I've tested setting large step very high (with #8530). There was no overshooting.
As minetest has its own scrollbar now, the largestep (afaik, it's only used for clicking directly on the bar) could be removed entirely. It's just weird.
(And with it, the bug that the scroller is offset if you click and hold on the bar for the scroller to come should be removed, too.)

**Comment by rubenwardy** [comment]
I think that it should always go the the position you click if it's not inside the scroll tab. This is expected behaviour

**Comment by DS-Minetest** [comment]
See #8711.

**Comment by paramat** [comment]
> I think that it should always go the the position you click if it's not inside the scroll tab.

I agree, and i disapprove of this being done as an option, unnecessarily complex.
