### ISSUE TITLE
Multi-character

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7716]
##### Issue type

 - Feature request
 
##### Minetest version

```
0.4.17.1
```

##### Summary

My idea is to add a Minetest version of Alex
I'm not so good at thinking of stuff's to say so i'll just show my examples

### I introduce to you... **Rosie!**
![character2](https://user-images.githubusercontent.com/33675971/45261086-d6d81680-b3ad-11e8-8ff8-9d65fb48a497.png)
### The minetest version of Alex.
![building a home](https://user-images.githubusercontent.com/33675971/45261084-d6d81680-b3ad-11e8-9ae4-37a34c98a6fb.png)
### We could do something like this:
 ***Click***
![skin tab](https://user-images.githubusercontent.com/33675971/45261088-d6d81680-b3ad-11e8-8e34-09f1af200885.png)
![before](https://user-images.githubusercontent.com/33675971/45261083-d63f8000-b3ad-11e8-9a8e-d24fd2cb7430.png)
### With texture-pack support!
Images being named character.png and character2.png
![after](https://user-images.githubusercontent.com/33675971/45261082-d63f8000-b3ad-11e8-995e-0a54cf7e91db.png)

### Images that could be used
![character](https://user-images.githubusercontent.com/33675971/45261085-d6d81680-b3ad-11e8-9b23-9608a6fdf3dd.png)

### Sam
<hr>

![character2](https://user-images.githubusercontent.com/33675971/45261086-d6d81680-b3ad-11e8-8ff8-9d65fb48a497.png)
### And Rosie
<hr>

Raw format
![rose](https://user-images.githubusercontent.com/33675971/45261087-d6d81680-b3ad-11e8-8489-8291cf7dafff.png)

<hr>

Consideration of this addition would be much appreciated.

**Comment by rubenwardy** [comment]
Wrong repo. Minetest is an engine, you'd want to open this in https://github.com/minetest/minetest _game

**Comment by Extex101** [comment]
No because of the main menu and texture pack support you wouldn't be able to add all of it in minetest_game

**Comment by rubenwardy** [comment]
Even so, this is adding a game play specific content to the engine which is not a good idea. Texture pack support is already possible with skin mods, and the main menu support is unnecessary and doesn't make sense when we don't have global accounts

**Comment by Extex101** [comment]
***sigh*** I've worked hard on this....
### I guess I'll re-open it some other time...  :(

**Comment by paramat** [comment]
:-1: for reasons given, this is a game issue, we are considering adding skin support in MTG.

**Comment by paramat** [comment]
Your Rosie texture is good, if we add multi-skin support to MTG, which is planned, we could use it.

More recently there was some discussion about engine support for male/female skins. Thinking further on this i disagree that a male/female distinction belongs in the engine, it's a game content aspect. If you consider how varied the games for the Minetest Engine can be, there may not be human characters in a game at all, the player could be a robot or a vehicle. It is possibly best combined into a skins mod in a game.
