### ISSUE TITLE
Update textures after joining

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7718]
##### Issue type

 - Feature request
 
##### Summary

I noticed that "Initializing Nodes" takes a lot time when joining a server with many mods. This is caused by calculating the textures (applying texture modifiers, generating mip maps, etc.).
If I disable the `updateTextures` function call, joining is significantly faster but of course I don't see textures: https://github.com/minetest/minetest/blob/766fb7b46edab47f96b8b940e390daf5319261b7/src/client.cpp#L1693
Is it possible to update the textures in a separate thread after joining so that you can use the chat and do similar things instead of waiting outside until "Initializing Nodes" is finished?

**Comment by paramat** [comment]
Better to process textures before the game starts, otherwise the game will not have textures. Using chat before being able to see the world is weird and not necessary, as well as giving a bad impression of the game. When the game starts it should start fully and it's better to wait longer in the processing phase than start the game partially earlier.
This does not improve performance.
:-1:

**Comment by Ezhh** [comment]
I do not really want people on my server who are not yet able to (and may actually not be able to) play on it...

**Comment by HybridDog** [comment]
I think if there's a way to speed up updateTextures, joining can be made noticeably faster.

> I do not really want people on my server who are not yet able to (and may actually not be able to) play on it...

A setting could be added to toggle deferred texture updating, which is disabled by default.

**Comment by ExeterDad** [comment]
A player logging in to a multiplayer game to see mesh only, and textures to load in as they arrive isn't unheard of. In fact it's just accepted. These games also load in textures on the fly, without the need to restart the server.
So I can't agree that this idea should be immediately shot down as a "bad idea."

**Comment by Ezhh** [comment]
To be honest, it would probably depend on implementation. If it could handle simple placeholder textures for everything then apply the real textures, it could be okay, but if the player sees nothing at all, or you get the fun bright painful colours of missing textures, that's pretty bad.
