### ISSUE TITLE
Fix scrollbox bug

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#7729]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17.1
```

##### OS / Hardware

Operating system:
CPU: Intel® Core™ i3-3220 CPU @ 3.30GHz × 4 

GPU model: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL version: OpenGL 4.6.0

##### Summary
Broken scrollbox:
![](http://www.image24.net/uploads/95e58fbd4bbildschirmfoto_vom_zzzz-zz-zz_zz-zz-zz.png)

##### Steps to reproduce
Make your window very small and such things will happen as example in the mail mod.

**Comment by SmallJoker** [comment]
What's to fix there? There's not enough space to display all lines in full size, so scrollbars are added.

**Comment by paramat** [comment]
How small does the window have to be? We set 1024x600 as the default and this is considered the smallest window to use, smaller than that we don't guarantee functionality.
It doesn't look like a bug because you have made the scrollbar so small as to be non-functional.

**Comment by paramat** [comment]
That's probably not possible due to formspecs, it is also unintuitive.
You also haven't answered the questions, please do.

**Comment by niansa** [comment]
More info needed, do you have multiline text but cannot scroll through it by clicking the up/down buttons?

Yes
