### ISSUE TITLE
New Minetest header

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7731]
##### Issue type

 - Feature request

### For 0.5.0/0.4.18 lets introduce a new "Minetest" header!
![header](https://user-images.githubusercontent.com/33675971/45648329-1fae6000-ba7d-11e8-893b-e240cc0aeb16.png)
![menu_header](https://user-images.githubusercontent.com/33675971/45648331-2046f680-ba7d-11e8-8c7b-8ecf9481dc42.png)
### IN 3D!!

**Comment by ClobberXD** [comment]
It seems to be leaning back a bit too much... Minetest always charges ahead like a warrior, and I think the header should symbolize that. :P 
On a more serious note, I think making it a little more upright would suffice.

**Comment by benrob0329** [comment]
"Oh, its Minecraft but not Minecraft"

**Comment by SmallJoker** [comment]
I'd rather use some late stage wordart style in rainbow colors to give it some unique touch. This simply looks too much like Minecraft.

**Comment by paramat** [comment]
The engine header is valid as an issue here.
However i am :-1: for anything that moves back towards a Minecraft look, we're trying to get away from that, in MTG too, see https://github.com/minetest/minetest_game/issues/2195 so :-1: for MTG too.
