### ISSUE TITLE
Write in documentation that minetest.after can be used to detect when all mods were loaded

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7733]
@paramat claimed that in order to detect that all items have registered (or all mods be loaded), you are supposed to call `minetest.after(0)`,

paramat further claimed that this not not a hack, but even officially recognized “standard practice”.

If this is actually true, this shoud be written in the officicial documentation (also possibly other quirks of `minetest.after`). This is neither obvious nor discoverable.

**Comment by SmallJoker** [comment]
Workaround haded:
https://github.com/minetest/minetest/blob/79e393cf4b5027eb9071df23f4834aac3f3a689f/doc/lua_api.txt#L3576-L3578

**Comment by paramat** [comment]
I forgot about that.
I guess we could add to
https://github.com/minetest/minetest/blob/79e393cf4b5027eb9071df23f4834aac3f3a689f/doc/lua_api.txt#L4344
That 'after 0' runs once environment starts up and after mod load.

**Comment by paramat** [comment]
Perhaps add this to the issue containing the list of doc issues?

**Comment by Wuzzy2** [comment]
Ah, `minetest.register_on_mods_loaded` is much cleaner and doesn't feel hacky at all, thanks.
Not sure if this strange `minetest.after(0)` hack still needs documentation then.

**Comment by rubenwardy** [comment]
I agree with that ^
