### ISSUE TITLE
Possibility to lighten entities.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#7734]
##### Issue type

 - Feature request

Hi. Could you add a possibility to lighten entities as nodes? It will be like minetest.set_entity_light(light_level) for example.

**Comment by paramat** [comment]
Already possible :)
https://github.com/minetest/minetest/blob/79e393cf4b5027eb9071df23f4834aac3f3a689f/doc/lua_api.txt#L5533
