### ISSUE TITLE
client connect using proxy, how to made it? or SOCKS5?

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/minetest#7740]
##### Issue type
 - Question
 - Documentation issue
 
##### Minetest version
```
Minetest 0.4.16 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.16 BUILD_TYPE=None RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/games/minetest"
```

##### OS / Hardware

Operating system: Linux
CPU: Intel i7 8 cores

GPU model: Advanced Micro Devices, Inc. [AMD/ATI] Sun XT [Radeon HD 8670A/8670M/8690M]
OpenGL version: 3.0 Mesa 13

##### Summary

I connect to the internet using a proxy server (all ports enabled free and property redirected, for example: I can connect pidgin and the proxy property redirects port 5222).

Where can I find a configuration key to let Minetest know that network comes through the proxy?

How can I make to connect with the Minetest client through my provided proxy address?

##### Steps to reproduce

1) Setup the http_proxy variables in the Openbox environment script
2) Logout, then login
3) All applications have internet access, but Minetest cannot connect to servers

EDIT by SmallJoker: Rephrase text (hopefully easier to understand now?)

**Comment by mckaygerhard** [comment]
PD> reading from documentation on linux seems need to configure variables of the form "protocol_proxy" to determine the proxy for a given protocol , but there-s no information hwo to configure into minetest.. 

minecraft seems have those kind of trick.. so how to made it with minetest?

**Comment by mckaygerhard** [comment]
ok i found thaat HTTP proxy servers do not support UDP, and maybe my proxy provider are a tinyproxy or squid, so then reading that SOCKS5 (not SOCKS4) proxy servers do support UDP though.

now due minetest use only UDP, how to configure a proxy to the internet connection? the clinet of course!

**Comment by sfan5** [comment]
As you've already found out, Minetest exclusively uses UDP. While the SOCKS5 protocol includes UDP in its specification, I don't think there are any programs that actually support this.
The only solution you're left with is using a VPN to redirect all your UDP traffic (bypassing the proxy).

**Comment by mckaygerhard** [comment]
ummm but seems minecraf can do that, using a simple extra command> `"-Dhttps.proxyPort=443 -DsocksProxyHost=localhost -DsocksProxyPort=1080 "` while minetest dont seems work as you suggested!

could provide any point or info how to do taht without too many setup on the machine?

**Comment by mckaygerhard** [comment]
ummm but seems minecraf can do that, using a simple extra command> `"-Dhttps.proxyPort=443 -DsocksProxyHost=localhost -DsocksProxyPort=1080 "` while minetest dont seems work as you suggested!

could provide any point or info how to do taht without too many setup on the machine? i now configure a sock5 proxy wiht redirection to the proxy of my provider..

about your comment "are any programs that actuallily support this"", well seems all the programs of mate desktop and gnome support very common and  when i used under openbox just setup the http or socks5 parameters graphically in the options/preferences part.. by example pidgin

**Comment by mckaygerhard** [comment]
hi @orwell96 the PM feature in guthub are gone some time ago.. how could i contact you.. if you made some comits on minetes i can track you.. do you?

**but in nany case, sound so complicated... minecraf users dont need too tricks for do that..**

**Comment by rubenwardy** [comment]
I'm against adding support for this, but not enough to formally disapprove it. It's a feature which is totally unnecessary and barely anyone will use

**Comment by mckaygerhard** [comment]
ummm taking in considerations the servers that upgrade to v5 vs thoses that still runs in v4. . could you demostrate that.. the problem when we have "in confortable zone" are that we think that all the otehers have in same behaviour... i cited that there's more users playing with tricks event with high bandwich network....

**Comment by rubenwardy** [comment]
You can implement this here: https://github.com/minetest/minetest/blob/master/src/httpfetch.cpp#L249

```c++
curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);
curl_easy_setopt(curl, CURLOPT_PROXY, "proxy");
```

You should probably control it with a setting with the proxy type, as shown here:

```c
typedef enum {
  CURLPROXY_HTTP = 0,   /* added in 7.10, new in 7.19.4 default is to use
                           CONNECT HTTP/1.1 */
  CURLPROXY_HTTP_1_0 = 1,   /* added in 7.19.4, force to use CONNECT
                               HTTP/1.0  */
  CURLPROXY_HTTPS = 2, /* added in 7.52.0 */
  CURLPROXY_SOCKS4 = 4, /* support added in 7.15.2, enum existed already
                           in 7.10 */
  CURLPROXY_SOCKS5 = 5, /* added in 7.10 */
  CURLPROXY_SOCKS4A = 6, /* added in 7.18.0 */
  CURLPROXY_SOCKS5_HOSTNAME = 7 /* Use the SOCKS5 protocol but pass along the
                                   host name rather than the IP address. added
                                   in 7.18.0 */
} curl_proxytype;  /* this enum was added in 7.10 */
```

**Comment by track044** [comment]
You can use [UDPMix](https://gitlab.com/madotsuki/udpmix) UDP to TCP converter to turn minetest into a TCP protocol.
For the TCP proxy, you can use Iptables redirect.

**Comment by track044** [comment]
https://gitlab.com/madotsuki/udpmix
You can use this UDP to TCP converter to turn minetest into a TCP protocol.

**Comment by mckaygerhard** [comment]
too complicated.. i m using minecraft that property supoorts some trick more easyle, sorry guys currently minetest requires too much for my embebed devices.. minecraft just wants any JDK 8+ that that's all

**Comment by wilmhit** [comment]
I only want to mention that UDP was chosen for a performance reason and tunneling entire traffic through any kind of TCP tunnel might have negative effects.
