### ISSUE TITLE
Allow SSM to access the client-calculated pointed location

### ISSUE THREAD

**Issue by 12Me21** [minetest/minetest#7743]
##### Issue type
 - Feature request

##### Summary
Getting the exact location the player is looking at is *almost* possible with `Raycast`, but...
(As far as I know) There's no way to get the exact camera position, because of view bobbing and other animations. You also need to compensate for the eye offset and check whether the player is in first or third person view. (Which I'm also not sure is possible.)

I think the best solution would be to give mods access to the pointed position which the game has already calculated, so that there is no chance of any slight precision errors.
Perhaps `intersection_point`/`box_id`/`intersection_normal` should always be included in `pointed_thing`, when applicable.

**Comment by paramat** [comment]
Camera pos:
https://github.com/minetest/minetest/blob/4a2a11262b0821d0bcddd25161f5eb8b172b23fd/builtin/common/misc_helpers.lua#L694
https://github.com/minetest/minetest/blob/4a2a11262b0821d0bcddd25161f5eb8b172b23fd/builtin/common/misc_helpers.lua#L714

**Comment by 12Me21** [comment]
That doesn't work in third person view and doesn't include view bobbing.

**Comment by SmallJoker** [comment]
There is no view bobbing on server side and `set_eye_offset` does very often not result the wanted effect. Until now only using the player position in combination with the eye offset was good enough to provide acceptable results.

**Comment by stujones11** [comment]
The only way you could get access to the exact pointed thing/location at any given moment in time would be via the client. Any server-side method will always be slightly off, for a number of different reasons no matter how accurately it is calculated.

IMO, the best you could hope for is a client-side method for this. I guess it really just depends your intended use-case.

Related: #7317

**Comment by SmallJoker** [comment]
> Well, whenever you place a node or use an item
>  send the exact pointed position as well
> (Perhaps this should only be done for certain nodes/items, to reduce the amount of unnecessary data being sent)

That's where the modders come in and request all other cases too, even when pointing at nothing or eating items. Your request of sending the pointed location is surely possible and will have accurate results for what the client sees at that very moment.

>just reset the view bobbing animation when the player stops

This again speaks against exact locations. I usually place nodes, eat food and dig stone - walking simultaneously. If implementing this right, then send whatever the pointed location is on client-side to the server.

**Comment by ClobberXD** [comment]
The exact pointing location could be sent as `pointed_thing.intersection_point` to be consistent with what Raycast returns.

**Comment by raymoo** [comment]
When a player sends an interaction (left or right click), it also updates its position and look direction, so it should be able to reconstruct the look position of the player on the server.

**Comment by 12Me21** [comment]
> 
> 
> When a player sends an interaction (left or right click), it also updates its position and look direction, so it should be able to reconstruct the look position of the player on the server.

Yes, but the client's camera position is slightly different than the server's because of the view bobbing animation.
Plus, you need to convert the (inaccurate) camera position and look direction into the raycast start and end points, which introduces the possibility of slight errors (but mostly, it's just inconvenient)

**Comment by paramat** [comment]
:-1: Seems roughly possible already and i don't think it justifies sending extra data from client to server.

**Comment by niansa** [comment]
I think this feature is a good idea, because it allows interresting mods...

**Comment by paramat** [comment]
Disapproved by 2 core devs.
