### ISSUE TITLE
replace lua api with a wasm api

### ISSUE THREAD

**Issue by unmellow** [minetest/minetest#7745]
so people can write apps in most languages (granted they might have to compile a runtime)

**Comment by unmellow** [comment]
a more unreasonable idea that I still want to mention is what if the underlying engine was just a wasm jit with [babel](https://computation.llnl.gov/projects/babel-high-performance-language-interoperability/#page=home) running on top of it for interop between multiple languages

**Comment by paramat** [comment]
Erm :-1:

**Comment by DS-Minetest** [comment]
I'm sorry for my unknowing, but what exactly is wasm?
If everybody can use a different language for mods, will apis be usable inter languages?
Note that there are not that many modders. Many mods are neglected. So imo modders should all specialize in the same language to be able to contribute to mods from others.

**Comment by SmallJoker** [comment]
`<sofar> if I was signed into github I'd close it`

**Comment by unmellow** [comment]
really the only benefit this brings is being able to use languages besides lua
as for mod interoperability, you could use json like [xi-editor](https://www.youtube.com/watch?v=4FbQre9VQLI) I just thought it would be cool to have a voxel game engine that doesn't require you to use a specific language

**Comment by zaoqi** [comment]
@unmellow You could use typescript, scheme, ...

**Comment by zaoqi** [comment]
@unmellow https://github.com/hengestone/lua-languages

**Comment by zaoqi** [comment]
@unmellow https://github.com/zaoqi/scheme.lua https://github.com/TypeScriptToLua/TypeScriptToLua

**Comment by ClobberXD** [comment]
@zaoqi Could you please add all of that into a single post and delete the others?
