### ISSUE TITLE
Plantlike question

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7752]
##### Issue type

 - Question

In rubenwardy's ["Lua Modding API Reference"](https://rubenwardy.com/minetest_modding_book/lua_api.html#nodes) he mentions that there are several plantlike looks using
`paramtype2 == "meshoptions"`
But it doesnt say how you chose which look you want..
it just says

```
The value of param2 becomes a bitfield which
  
can be used to change how the client draws plantlike nodes.
  
Bits 0, 1 and 2 form a mesh selector.
  
Currently the following meshes are choosable:
    0 = a "x" shaped plant (ordinary plant)

    1 = a "+" shaped plant (just rotated 45 degrees)

    2 = a "*" shaped plant with 3 faces instead of 2

    3 = a "#" shaped plant with 4 faces instead of 2

    4 = a "#" shaped plant with 4 faces that lean outwards

    5-7 are unused and reserved for future meshes.
```
How am is supposed to chose which drawtype to use?

**Comment by 12Me21** [comment]
```
    * Only valid for "plantlike". The value of `param2` becomes a bitfield which
      can be used to change how the client draws plantlike nodes.
    * Bits 0, 1 and 2 form a mesh selector.
      Currently the following meshes are choosable:
        * 0 = a "x" shaped plant (ordinary plant)
        * 1 = a "+" shaped plant (just rotated 45 degrees)
        * 2 = a "*" shaped plant with 3 faces instead of 2
        * 3 = a "#" shaped plant with 4 faces instead of 2
        * 4 = a "#" shaped plant with 4 faces that lean outwards
        * 5-7 are unused and reserved for future meshes.
    * Bits 3 through 7 are optional flags that can be combined and give these
      effects:
        * bit 3 (0x08) - Makes the plant slightly vary placement horizontally
        * bit 4 (0x10) - Makes the plant mesh 1.4x larger
        * bit 5 (0x20) - Moves each face randomly a small bit down (1/8 max)
        * bits 6-7 are reserved for future use.
```
So basically, you set param2 to the number of the shape you want (0, 1, 2, 3, or 4, for now) plus any of the options.
For example, to get a "*" shaped plant (`2`) which is displayed 1.4x larger (`0x10`), you'd set param2 to `2 + 0x10`
If you also wanted to slightly vary the horizontal placement, you'd add `0x08` as well (`2 + 0x10 + 0x08`)

**Comment by paramat** [comment]
Feel free to continue discussion but this should be elsewhere.

**Comment by Extex101** [comment]
Okay is there some way to place the faces of the plant (in the square mode) further out? So the square in the middle be bigger
![screenshot_2018-09-27-16-58-15-1](https://user-images.githubusercontent.com/33675971/46180714-bf869d80-c276-11e8-8ecc-295684b97da2.png)

**Comment by paramat** [comment]
In the engine or from Lua?
