### ISSUE TITLE
Improve mapgen specific flags checkboxes

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7757]
![screenshot from 2018-09-29 10-27-52](https://user-images.githubusercontent.com/3686677/46244124-6764ae00-c3d2-11e8-9086-191cc0d5b38b.png)

Having both the `<flag>` and `<noflag>` checkboxes is weird. Can this be changed to show 1 checkbox that sets either `<flag>` or `no<flag>`?
All checkboxes can be ticked resulting in .conf having:
`mgv7_spflags = mountains, ridges, floatlands, caverns, nomountains, noridges, nofloatlands, nocaverns`
Although a world only ends up with each flag set to enabled in map_meta.txt.
@srifqi

**Comment by SmallJoker** [comment]
This sounds good - it would also be great to get rid of the `no` prefix for each flag which is used to force turning off a certain flag.

**Comment by srifqi** [comment]
Here is my thought about this:
1. All checkboxes will use default settings.
2. When the user click "Save" button, the setting will be saved like this:
```mgv7_spflags = mountains, ridges, nofloatlands, caverns```
3. Minetest will save all flags and will add "no" prefix for unchecked checkbox.
4. There will be no way to do, "Leave empty for default," as you need to click "Restore Defaults".

**Comment by srifqi** [comment]
Here is my thought about this:
1. All checkboxes will use default settings.
2. When the user click "Save" button, the setting will be saved like this:
```mgv7_spflags = mountains, ridges, nofloatlands, caverns```
3. Minetest will save all flags and will add "no" prefix for each unchecked checkbox.
4. There will be no way to do, "Leave empty for default," as you need to click "Restore Default".

**Comment by paramat** [comment]
srifqi all your thoughts are fine. When mapgen-specific flags are added to .conf manually every flag has to be specified, such as:
`mgv7_spflags = mountains,ridges,nofloatlands,caverns`
Leaving a flag out does not seem to make that flag use the default, and often causes mistakes.
The docs say: `Flags that are not enabled are not modified from the default.`, but this is unclear, confusing and actually seems incorrect.

**Comment by paramat** [comment]
> All checkboxes will use default settings.

They should display whatever settings are currently in effect, which may not be the defaults.
> "Leave empty for default,"

This would be wrong anyway if using single checkboxes, as leaving a checkbox empty means that flag is 'disabled', while the default could be 'enabled' or 'disabled'.

Points 2 and 3 are fine and correct.

**Comment by paramat** [comment]
> I meant they will use default setting first, when the setting hasn't changed yet.

Ok that's fine.
