### ISSUE TITLE
Regression related to tooltip[]

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#7764]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0-8d68b2c
```

##### OS / Hardware
Operating system: Manjaro Linux
CPU: Intel Core i7-2600k

##### Summary
#7469 caused tooltips bound to elements with commas in their IDs to break. I'm not sure if I'm supposed to create such elements, though.

##### Steps to reproduce
Show following formspec to player:
```
size[3,3]
button[0,0;3,3;a,b;Test]
tooltip[a,b;Tooltip]
```

**Comment by SmallJoker** [comment]
Not a bug. Please do not use commas in formspec names.
In this case, a new feature was introduced to allow specify a tooltip in a certain area: (#7469)
https://github.com/minetest/minetest/blob/dc948382f57c34a7da358bba85c04513877fe2c3/doc/lua_api.txt#L1985-L1989
The detection of which tooltip method to use relies on a check against the comma inside the first argument, which is exactly what you did.
