### ISSUE TITLE
Slow and jerky entity movement in 0.4.17.1

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7765]
##### Issue type
 - Bug report

##### Minetest version
```
0.4.17.1
```
(Possibly 0.4.17 as well. (_Not_ 0.4.16 nor 5.0.0-dev).

##### OS / Hardware
Operating system: At least Windows 8.1 and macOS 10.13.6

OpenGL version: In the case of macOS: OpenGL 2.0

##### Summary
Entities moving by means of the code in, for example, item_drop move very slowly and jerky. _I guess_ that the code relevant to this bug in that mod is around [here](https://github.com/minetest-mods/item_drop/blob/master/init.lua#L227).

##### Steps to reproduce
1. Use Minetest 0.4.17.1.
2. Install [minetest-mods/item_drop](https://github.com/minetest-mods/item_drop/)
3. Enable the item magnet feature by setting `item_drop.magnet_radius = 5` in `minetest.conf`
4. Start a game, watch the [entity travel slowly and jerky towards the player](https://i.imgur.com/Vl393OG.mp4). Compare this to the behavior in [the same test done in 5.0.0-dev](https://i.imgur.com/KwwUUw1.mp4).

**Comment by paramat** [comment]
Can you test in 0.4.16?

**Comment by paramat** [comment]
Could be a mod bug?

**Comment by HybridDog** [comment]
@tacotexmex, can you still reproduce it after https://github.com/minetest-mods/item_drop/commit/fc89b2d2b4cad17e121bc4d4e84553a929a7f042?

**Comment by tacotexmex** [comment]
Just tried and I can't reproduce it so this particular use case is solved at least.

**Comment by paramat** [comment]
Assuming mod bug.
