### ISSUE TITLE
Add a serialize method to MetaDataRef

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#7772]
##### Issue type
 - Feature request
 
##### Minetest version

```
5.0.0-dev
```

##### Summary

I need the ability to store node metadata in memory to allow properly undoing a change by worldedit.

I'm currently using [to_table](https://github.com/minetest/minetest/blob/d6f2a1c4b8ab13cee92e2041b3410fe3548e88e6/doc/lua_api.txt#L4916) and a hacky way to test if the metadata is empty to save it, the nodes, param1 and param2 are saved from voxelmanip data.
https://github.com/HybridDog/we_undo/blob/e53175df55b112e518097f0fa9359f6c23e37e4d/init.lua#L749

However, testing if meta:to_table returns empty node metadata is not reliable, worldedit itself stores lots of redundant information in the .we files.
A serialize method could allow more reliable code and provide a simple fix for the huge .we files.

**Comment by HybridDog** [comment]
I'm using find_nodes_with_meta now to test for empty metadata: https://github.com/HybridDog/we_undo/blob/cb482c91e1035554287c11d6806567d75a71d0f8/init.lua#L770

**Comment by sfan5** [comment]
Note that `find_nodes_with_meta` is not perfect either: #8943
