### ISSUE TITLE
Setting of noise flags broken in.conf and advanced settings

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7776]
For example, mgv7 floatland base noise, an 'eased' (smoothed) 2D noise:
Setting using ,conf:

In conf.example the noise params are listed as:
```
# mgv7_np_floatland_base = {
#    offset      = -0.6,
#    scale       = 1.5,
#    spread      = (600, 600, 600),
#    seed        = 114,
#    octaves     = 5,
#    persistence = 0.6,
#    lacunarity  = 2.0,
#    flags       = "eased"
# }
```
However when this form, including `flags = "eased"`, is used in .conf, the mapgen result is non-eased 2D noise and the entry in map_meta.txt has an empty flags field:
```
mgv7_np_floatland_base = {
	lacunarity = 2
	persistence = 0.6
	octaves = 5
	offset = -0.4
	scale = 1.4
	flags =
	spread = (600,600,600)
	seed = 114
}
```
The normal form of 2D noise in map_meta.txt has `flags = defaults`:
```
mgv7_np_floatland_base = {
	lacunarity = 2
	persistence = 0.6
	octaves = 5
	offset = -0.4
	scale = 1.4
	flags = defaults
	spread = (600,600,600)
	seed = 114
}
```
Now if i set these noise params in .conf with `flags = defaults` (the default for 2D noise is eased), the mapgen result is also non-eased noise, and the entry in map_meta.txt is again a blank field for flags:
```
mgv7_np_floatland_base = {
	lacunarity = 2
	persistence = 0.6
	octaves = 5
	offset = -0.4
	scale = 1.4
	flags =
	spread = (600,600,600)
	seed = 114
}
```
The only form in .conf that causes the correct mapgen and map_meta.txt results is leaving out the flags field completely.

More testing coming. Will test setting noise flags in advanced settings.
@srifqi 

EDIT: Not fixed by #7819

**Comment by paramat** [comment]
Using advanced settings i altered the 'offset' and 'scale' of mgv7 floatland base noise, note i didn't alter noise flags. In .conf this appeared with a blank field:
```
mgv7_np_floatland_base = {
	lacunarity = 2
	persistence = 0.6
	octaves = 5
	offset = -0.4
	scale = 1.4
	flags = 
	spread = (600,600,600)
	seed = 114
}
```
The mapgen result was non-eased 2D noise, and the params found in map_meta.txt also had a blank field:
```
mgv7_np_floatland_base = {
	lacunarity = 2
	persistence = 0.6
	octaves = 5
	offset = -0.4
	scale = 1.4
	flags = 
	spread = (600,600,600)
	seed = 114
}
```

**Comment by paramat** [comment]
For reference here are the docs in lua_api.txt about noise flags:
```
### `flags`

Leave this field unset for no special handling.
Currently supported are `defaults`, `eased` and `absvalue`:

#### `defaults`

Specify this if you would like to keep auto-selection of eased/not-eased while
specifying some other flags.

#### `eased`

Maps noise gradient values onto a quintic S-curve before performing
interpolation. This results in smooth, rolling noise.
Disable this (`noeased`) for sharp-looking noise with a slightly gridded
appearence.
If no flags are specified (or defaults is), 2D noise is eased and 3D noise is
not eased.
Easing a 3D noise significantly increases the noise calculation load, so use
with restraint.

#### `absvalue`

The absolute value of each octave's noise variation is used when combining the
octaves. The final perlin noise variation is created as follows:
```

**Comment by paramat** [comment]
Another bug that may be the cause of the above:

When i enter the edit page for mgv7 floatland base noise it looks like this with 'eased' flag set:

![screenshot from 2018-10-11 01-13-53](https://user-images.githubusercontent.com/3686677/46773039-19657980-ccf3-11e8-9cd6-be7d7ae49fb8.png)

If, without changing anything i press 'save' to exit, then re-enter, the noise flags are all now unset:

![screenshot from 2018-10-11 01-13-53](https://user-images.githubusercontent.com/3686677/46773060-487beb00-ccf3-11e8-82c6-ee2fbb3301d1.png)

The same happens if i alter the noise 'offset', save, then re-enter.

**Comment by paramat** [comment]
More testing:
Noise flags are saved if you click a checkbox to change it, then 'save'. But if a checkbox is already ticked, 'saving' disables the flag.
In `local function handle_change_setting_buttons(this, fields)` i added a print statement:
```
		elseif setting.type == "noise_params_2d" or setting.type == "noise_params_3d" then
			local np_flags = {}
			for _, name in ipairs(setting.flags) do
				if checkboxes["cb_" .. name] then
					table.insert(np_flags, name)
					print(tostring(np_flags) .. " " .. tostring(name))
				end
			end
```
Nothing is printed when 'saving' already ticked checkboxes, so `if checkboxes["cb_" .. name] then` is failing in this situation.

**Comment by paramat** [comment]
PR #7819

**Comment by paramat** [comment]
#7819 merged.

**Comment by srifqi** [comment]
As for reading from ```minetest.conf```, we already read ```flags``` settings from it.
https://github.com/minetest/minetest/blob/3a992ce76d2c9261bcf35d9123d8c77a4c227eeb/builtin/mainmenu/dlg_settings_advanced.lua#L491-L492

https://github.com/minetest/minetest/blob/3a992ce76d2c9261bcf35d9123d8c77a4c227eeb/src/script/lua_api/l_settings.cpp#L122

https://github.com/minetest/minetest/blob/3a992ce76d2c9261bcf35d9123d8c77a4c227eeb/src/settings.cpp#L560-L562

**Comment by paramat** [comment]
Thanks.
> Should we change it?

A PR would be good if you can, but if you're very busy i can do the PR.

**Comment by srifqi** [comment]
Okay. Should I update ```minetest.conf.example``` using ```generate_from_settingtypes.lua```, too?

**Comment by paramat** [comment]
No don't bother, we only do that occasionally, it doesn't need doing on every change, as that would be too much work.

**Comment by srifqi** [comment]
Okay. I get it.
