### ISSUE TITLE
Singleplayer: Menu entry to enable/disable fly, fast and noclip

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#7794]
##### Issue type

 - Feature request
 
##### Summary

Add menu entry to enable/disable fly, fast and noclip in singleplayer mode.

**Comment by DS-Minetest** [comment]
What do you exactly mean? Adding entries in the main menu to `enable creative` and `enable damage` or in pause menu?
And why is this wanted?

**Comment by niansa** [comment]
The entries should be in the Main menu. I would like this feature because it is easier than using the /grant and /revoke commands. It's also netter for newbies who never played Minetest before: They just think there is no fly or fast mode. And they usualy DON'T search in the Internet how to fly...

**Comment by paramat** [comment]
Privs can only be set by chat command in-game.
