### ISSUE TITLE
View/Modify inventory of another player

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#7795]
##### Issue type

 - Feature request

##### Summary

There should be a command to access the inventory of another player. But that should require a Privilege.

**Comment by niansa** [comment]
Sometimes I accidenticaly give a player on my server an item that the player should not own (Cloud, Lava, Wand Tool, ...). That's why I would like such feature.

**Comment by NathanSalapat** [comment]
I believe this mod https://forum.minetest.net/viewtopic.php?f=9&t=14594 offers that feature.

**Comment by niansa** [comment]
The mod just offers a tool but no command afaik.

**Comment by ClobberXD** [comment]
The engine already provides the required API methods, and the implementation should be left to the mods, as there can be many ways of displaying a player's inventory.

**Comment by niansa** [comment]
Ok.

**Comment by SmallJoker** [comment]
Duplicate of #4859
