### ISSUE TITLE
Buggy movement

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#7796]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-4e6b8062-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system:
CPU: Intel® Core™ i3-3220 CPU @ 3.30GHz × 4

GPU model: GeForce GTX 1050 Ti/PCIe/SSE2

##### Summary
I don't know how to explain it, just watch this video and you will know what I mean:
https://youtu.be/BYCKNdPD_oY

##### Steps to reproduce
1. Join singleplayer or multiplayer world.

**Comment by ClobberXD** [comment]
Would you be able to check if there's a line in your minetest.conf like so? `random_movement = true` :)

**Comment by niansa** [comment]
I disconnected my controller and it was fixed. But HOW is it possible that a CONTROLLER that is not even touched tries to controll minetest???

**Comment by 12Me21** [comment]
It looks like your controller isn't calibrated.

**Comment by rubenwardy** [comment]
Controllers differ massively between OSes and controller models. It should be disabled by default in minetest, however. Please make sure that `enable_joysticks` is `false`
