### ISSUE TITLE
Android: Scrollbar in Pause UI & Online Content dialog too narrow or not visible when text is too long

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#7798]
##### Issue type

 - Bug report
 
##### Minetest version

Android build made from e369eb1a9b2d65629d444fb305925e0d1b859b6f, master branch
Android build installed from Google Play Store, 0.4.17

##### OS / Hardware

Operating system: Android 7.0 on Huawei NEM-L21
CPU: HiSilicon Kirin 650 2.11 Ghz (arm/aarch64, 8 cores) 

##### Summary

When viewing pause menu in android build, the right scrollbar at controls list is eather too narrow (master, unsigned build) or not visible at all (0.4.17, google play) when controls info text is too long. Also "Game paused" text is not centered correctly, but it is already posted in #7093
![screenshot_20181019-142510](https://user-images.githubusercontent.com/6626242/47216051-547b4300-d3ac-11e8-8ff9-6a0e2940091c.png)
![screenshot_20181019-145004](https://user-images.githubusercontent.com/6626242/47216692-7d9cd300-d3ae-11e8-9509-59a3b87b594e.png)
My screen info (copied from https://github.com/minetest/minetest/pull/7784#issuecomment-430131919):
```
Model: HUAWEI NEM-L21
Android version: 7.0 - N
API level: 24
Drawable density: xxhdpi
Layout size: normal
Screen (dpi): 480
Width (px): 1080
Height (px): 1920
Usable width (px): 1080
Usable height (px): 1812
Width (dp): 360
Height (dp): 640
Smallest dp: 360
Orientation: Portrait
Orientation degree: 0°
Diagonal Size(inches): 5.0
X dpi: 422,0
Y dpi: 424,1
Touchscreen: Finger
Refresh rate (fps): 60,0
```
**Update:** Online content dialog is affected too, the scrollbar for the mod description is too tiny, on some entries text overflowing to right.
![screenshot_20181105-130901](https://user-images.githubusercontent.com/6626242/47995226-42640900-e0fd-11e8-822f-62d725bdbf55.png)
Minetest built against latest master.
##### Steps to reproduce

1. Build latest android build from master (e.g. following workflow of #7797) or install play store version, skip to step 3, ignore step 5
2. Install using adb or by using phone tools if available, removing already installed version first
3. Backup current minetest folder in storage root if it exist
4. Run minetest, start single player or connect to server, enter pause menu.
5. Uninstall minetest, install play store version, repeat steps 3-4 to test it

**Comment by SmallJoker** [comment]
Does this also apply for other formspecs (mainmenu, ingame) or is it limited to the pause menu?

**Comment by stujones11** [comment]
> Does this also apply for other formspecs (mainmenu, ingame) or is it limited to the pause menu?

The reason why it looks alright with other formspecs is because of this commit 4caa00cc99af133e5724cd8ab04f5cb8db81a666 However, this only fixes the issue for gui tables and not for builtin stuff like combo boxes. The proper fix (IMO) would have been to set `gui::EGDS_SCROLLBAR_SIZE` in the default skin.

**Comment by juozaspo** [comment]
Since #7834 got merged, there's no need to keep this open. This can be closed as it's fixed in mentioned pr.

**Comment by stujones11** [comment]
Thanks!
