### ISSUE TITLE
Lua API: Get player system type

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7799]
##### Issue type
 - Feature request
 
##### Summary
I suggest to add a way for mods to figure out which type of system (PC/Mac/Android) a player is using.
This could be done by adding another filed in the table returned by `minetest.get_player_information`.

I'd call the field `platform` and it could have one of multiple possible values: `"pc"`, `"mac"`, `"android"`, (possibly other systems).

##### Rationale
This is required if you want to explain the controls of Minetest, since the controls might be very different depending on what type of system you use.
The main reason for this is the Tutorial (https://forum.minetest.net/viewtopic.php?f=15&t=10192).

Currently, the Tutorial assumes PC default controls, so it obviously fails on Android systems.

**Comment by CBugDCoder** [comment]
Don't forget Linux :P also this could be used for and inventory mod re-arranging the inventory to be different for phones than for computers.

**Comment by 12Me21** [comment]
But you'd still be assuming that the controls haven't been changed from default...

**Comment by Wuzzy2** [comment]
AFAIK Minetest on Windows is the same as on GNU/Linux, so I summarized that as “PC”. But there's no harm in being explicit here, too.

Note that Android is a Linux, too, so we should be careful to distinguish between “GNU/Linux” (i.e. a “classic” Linux distribution like Ubuntu, OpenSUSE, Arch Linux, etc.) and “Android”.

In any case, the emphasis in this issue is more on “type of Minetest build” so the modder knows the type of control scheme. Basically this boils down between mobile vs PC/desktop vs Mac.

**Comment by rubenwardy** [comment]
This is a bad idea really. It's better to have different functions from input methods and DPI, which are the real reasons that affect how you design formspecs.

**Comment by Wuzzy2** [comment]
Well, I guess you're right. There needs to be a better solution somehow.

**Comment by paramat** [comment]
This reminds me of the request for a way to detect Android clients, which was disapproved for understandable reasons.

**Comment by 12Me21** [comment]
If you want to know what the controls are, maybe a better idea would be a way to check a player's control settings.

**Comment by Wuzzy2** [comment]
So the actual problem I want to solve is to change the GUI depending on the "GUI type" of Minetest.
Mods can add plenty of stuff to the GUI, and you might want to re-align your GUI stuff when you are having a touchscreen GUI, because otherwise it might overlap with something.

**Comment by paramat** [comment]
I rather like this suggestion, but for possibly controversial reasons: I feel a server should be able to block Android players if it wants, whether or not that is 'fair' or 'ethical' etc. =)
Obviously a non-official Android client could be hacked to lie about this, so it wouldn't be particularly effective.
Anyway, there seems to be other uses for this information.
