### ISSUE TITLE
max_hear_distance Clarification

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#7800]
##### Issue type

 - Documentation issue
 
##### Minetest version

```
Latest HEAD
```

##### Summary

max_hear_distance is not described in lua_api.txt.  I had assumed it was the maximum distance you could be in order to hear the playing sound.  This is not the case, however, as max_hear_distance is actually the maximum distance a player must be for that sound to ever play at all.
##### Steps to reproduce

1a. Play a sound at 0,0,0 with default max_hear_distance=32 while standing 33 nodes away and observe no sound heard.  1b. Move inward towards 0,0,0 and observe sound is still not playing, even though you are within `max_hear_distance`.
2a. Play a sound at 0,0,0 with default max_hear_distance=32 while standing within 32 nodes and observe the sound playing.  2b. Move outwards beyond 32 nodes and observe the sound is still playing.

**Comment by jastevenson303** [comment]
If the volume curve reaches zero at exactly `max_hear_distance` each time, I think it's a win-win

**Comment by paramat** [comment]
> If the volume curve reaches zero at exactly max_hear_distance each time, I think it's a win-win

This can't happen, the 'inverse distance' model used by OpenAL (we are limited to choosing one of the OpenAL models and altering the parameters avaialble) is volume = 1 / distance, this never reaches zero. Volume falloff behaviour has to be independent of max_hear_distance.

**Comment by jastevenson303** [comment]
The shape of the curve is dependent upon `max_hear_distance`.

>Volume falloff behaviour has to be independent of max_hear_distance.

The lower the `max_hear_distance`, the higher the volume at the end of the curve.

**Comment by paramat** [comment]
> The shape of the curve is dependent upon max_hear_distance.

It isn't, AL_MAX_DISTANCE in OpenAL is a different thing to the MT parameter 'max_hear_distance'.
I studied OpenAL docs 2 days ago, AL_MAX_DISTANCE is undefined in code so takes the default value of FLT_MAX, as it should.

Also, this issue is necessary :+1: docs need improving.

**Comment by jastevenson303** [comment]
I knew you didn't try my test mod.

**Comment by jastevenson303** [comment]
https://github.com/minetest/minetest/issues/8088

**Comment by paramat** [comment]
I don't need to, i've studied how sound attenuates in OpenAL
> It appears the greater the max_hear_distance, the more the sound's volume diminishes.

Because gain = 1 / distance, if you increase 'max_hear_distance', you hear the sound from larger distances, so from that equation gain will be lower. The sound attenuation curve is however unchanged in form, it's still gain = 1 / distance.

**Comment by jastevenson303** [comment]
A fine point, but the difference between `max_hear_distance` and `max_hear_distance + 1` is stark.  It goes from perfectly audible, even 128 nodes away, to not audible at all.  That was what prompted me to suggest making the volume as low as possible at `max_hear_distance`.

The whole Minetest sound experience is... What's a good word here?  There's a lot of room for improvement, so I'm happy at least to talk about it.  Thank you.

**Comment by paramat** [comment]
> but the difference between `max_hear_distance` and `max_hear_distance + 1` is stark. It goes from perfectly audible, even 128 nodes away, to not audible at all.

As expected.
Documentation now added.
