### ISSUE TITLE
'Restore defaults' in All Settings sometimes freezes Minetest

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7803]
Use advanced settngs to set a changed font_size, save, then press 'restore defaults'.
Likely cause a29bc8e8babd9320b629e67dee753a08d18799d3
@SmallJoker 

EDIT by SmallJoker: Affected settings:
* font_path
* font_size
* gui_scaling

**Comment by paramat** [comment]
Oddly, it doesn't crash for some other 'int' settings.

**Comment by paramat** [comment]
SmallJoker mentioned this is a mutex lock issue.

**Comment by SmallJoker** [comment]
It didn't crash here (debug build, recent master) but interrupting it showed that it was apparently hanging in a mutex deadlock in the settings functions. I'm yet not sure why it only happens for this particular setting, maybe there are more which have the same issue?

**Comment by Linuxdirk** [comment]
> I'm yet not sure why it only happens for this particular setting

Found another setting that freezes the window, see #8275.

**Comment by DS-Minetest** [comment]
I can still reproduce.
It also happens with `font_path`.

**Comment by SmallJoker** [comment]
4271889ef832806e7bd57e552f15b24fdf162c8d
