### ISSUE TITLE
Auto Forward does not register as keypress for server-side mods

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#7805]
- Feature request
 
##### Minetest version
```
0.4.17.1 (most likely also 5.0.0-dev)
```

##### OS / Hardware

Operating system: Ubuntu 16.04
CPU: Intel Xeon

##### Summary
The 'Auto Forward' key doesn't send continuous key presses, so the server doesn't receive the info, that the player is moving.

This information is critical in some mods where movement matters a lot... Especially mods that use it to reduce attributes/buffs/saturation etc depending on key presses.

I suggest to send automatic "up key" packets as long as 'Auto Forward' is enabled.

**Comment by jastevenson303** [comment]
> ##### Reproduction
> Use MTG, go into 2nd person view, press autoforward. Sam will float creepily by moving forward without moving his legs.

This line in particular to illustrate: https://github.com/minetest/minetest_game/blob/master/mods/player_api/api.lua#L110

**Comment by paramat** [comment]
> Sam will float creepily by moving forward without moving his legs.

LOL all this time i never noticed that, yes the animation depends on 'get player controls'.
Another good reason to do this.

**Comment by TillCoyote** [comment]
I confirm this bug on 5.0.0-dev.

**Comment by TillCoyote** [comment]
Also I found that walking animation doesn't work.

https://youtu.be/h01PtuHBBzo

**Comment by ClobberXD** [comment]
@TillCoyote As mentioned above, the animations depends on the player's keypresses (at least in MTG). It should be fixed when #8249 is merged.
