### ISSUE TITLE
Minetest freeze mods if a player too far away from the mechanics.

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#7849]
##### Issue type
 - Bug report
 
##### Minetest version
0.4.17

##### OS / Hardware

Operating system: Linux
CPU: AMD Phenom X4

GPU model: NVIDIA 8500GT (nouveau)

##### Summary
The blocks are not actived if a player far away. Haw to fix?

**Comment by paramat** [comment]
Not a bug, you can use mapblock forceloading to keep a mapblock loaded.
