### ISSUE TITLE
Unicode characters don't work in chat

### ISSUE THREAD

**Issue by marvok** [minetest/minetest#786]
The chat window replaces all unicode characters by a space. I speak French and all my accentuated letters are replaced by spaces.

**Comment by nerzhul** [comment]
Duplicate with #302

**Comment by raymoo** [comment]
@nerzhul I don't think this is a duplicate, since this issue also arises when the server sends a chat message (so can be a display rather than input problem):
```
minetest.register_on_joinplayer(function(player)
        minetest.chat_send_all("test")
        minetest.chat_send_all("lambda> λ") -- Non-japanese unicode
        minetest.chat_send_all("a> あ")
end)
```

![debugoutputscreen](https://cloud.githubusercontent.com/assets/5734399/16160973/ec25359a-347f-11e6-9b95-074b3165fe54.png)

**Comment by yyt16384** [comment]
@raymoo Are you using a font that supports these characters?

**Comment by raymoo** [comment]
Maybe not, I'll try setting another font.

**Comment by raymoo** [comment]
Alright, it works after changing font. Thanks for the tip, @yyt16384.
