### ISSUE TITLE
Add “Game Extras” menu for easy access to special game/mod features

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7868]
##### Issue type
 - Feature request
 
##### Summary
I propose to add a new in-game menu, called “Game Extras”. This menu is specifically made for games to allow **easy** access to additional features without polluting the inventory menu.

In this menu, mods can add buttons to which they then can react accordingly when it is pressed.

##### Usage
To open the Game Extras, the player has to press a key. Maybe one of the function keys, but I am not sure yet.

If the list of game extras is non-empty, it displays a window with the caption “Game Extras” and a list of of buttons, one for each “game extra”. Each button may have a little icon next to it. If there's a huge amount of game extras added by games, multiple pages might be neccessary.

If you try to open this menu while there are no game extras, a short message should appear instead.

If you open the menu and click a button, the menu itself may or may not be closed (see below), then `callback` is executed. `callback` can theoreticlly be anything the modder likes, but normally it should just open a formspec.

##### API design

In the Lua API there shall be a function to add a game button:

`minetest.add_game_extra(identifier, name, description, icon, callback)`

with

* `identifier`: Unique internal identifier for the game extra. The “colon notation” is preferred
* `name`: User-facing name of the game extra, used as label for the button. Should be short
* `callback`: This function is called when the button is clicked. It takes a single parameter: `player` (=player object of the player who clicked)
* `description`: Optional description of the game extra, describes in a few words what this game extra does. Used as tooltip for the button
* `icon`: Optional icon (1:1 aspect ratio)
* `close_menu`: Optional. If `true`, the Game Extras will be closed when the button is clicked. Default: `true`

The “Game Extras” menu starts empty by default. The displayed buttons are sorted alphabetically by their `name`.

###### Example

Add a button for achievements:

```
minetest.add_game_extra("achivements:achievements", "Achievements", "Show what you what amazing feats you have achieved in this game so far", "achievements_game_extra_icon.png", function(player)
	achievements.open_achievements_menu(player) -- opens a formspec
end)
```

And that's it! The rest of this issue is a justification.

###### Use cases

The Game Extras menu will be useful for mods because they can add a button for things like …

* Help
* Crafting guide
* Editing tools like WorldEdit or L-System Tree Utility
* Admin tools
* Achievements
* Quests and similar RPG-like features
* Waypoints
* Anyting interface-heavy that is not directly linked to the gameplay

Many of which currently need to be somehow shoved into the inventory menu.

###### Rationale
Currently, a lot of these features rely on modifying/hacking the inventory. Modifying the inventory in a generic manner is *hard* because if you try to be generic, you can't make many assumptions.

Another problem with modifying the inventory is that is often cannot do this without adding a hard dependency.

Modders have often attempted to add sort of “Game Extras” menu to the inventory menu (like Inventory++) which are all nice and such, but they often tend to make the inventory quite crowded with features that don't really make sense in an inventory menu, like achievements.
While some features are closely-related to the inventory (like the crafting guide) and at least make *some* sense to have in the inventory, many of them aren't.

Having a separate Extras menu will have benefits because it …

* simplifies inventory menu implementations
* simplifies formspec-heavy mods in that they no longer need to hack the inventory
* reduces dependency hell by making “middleware mods” like Inventory++ less important
* allows to clean up space in the inventory menu
* gives a clear separation of concerns (inventory menu for inventory stuff, game extras menu for non-inventory stuff)
* is less confusing to newbies
* eliminates need for hard dependency on inventory mods

**Comment by paramat** [comment]
> without polluting the inventory menu.

> Many of which currently need to be somehow shoved into the inventory menu.

The inventory is already a multipurpose in-game menu, sfinv can add tabs. It's the obvious and most accessible place for custom in-game menus because it is opened often during play.

>  they often tend to make the inventory quite crowded with features that don't really make sense in an inventory menu, like achievements.

'Crowded' seems a fabricated complaint, some could say 'rich with features'. Anything makes sense in inventory, with sfinv the inventory becomes a multipurpose in-game menu.

> allows to clean up space in the inventory menu

Non-issue, extra tabs are not a problem.

> While some features are closely-related to the inventory (like the crafting guide) and at least make some sense to have in the inventory, many of them aren't.

> gives a clear separation of concerns (inventory menu for inventory stuff, game extras menu for non-inventory stuff)

The inventory is already a multipurpose in-game menu.

> is less confusing to newbies

No. Seeing a tab for something in the inventory will be easier for newbies to find.

Seems like it would be a duplicated feature.
Consider that because you want a simplified API, many things games want to do will then not be possible, and nicely designed formspec designs with particular layouts and graphics not possible either. So many games will end up choosing to use sfinv tabs and formspecs anyway due to this.

So far this suggestion seems rather pointless and redundant.

**Comment by Wuzzy2** [comment]
Sfinv is only for Minetest Game, so a lot of your arguments are already biased towards Minetest Game. All of these arguments are invalid because of clear Minetest Game bias:

> No. Seeing a tab for something in the inventory will be easier for newbies to find.

> Non-issue, extra tabs are not a problem.

> The inventory is already a multipurpose in-game menu, sfinv can add tabs. It's the obvious and most accessible place for custom in-game menus because it is opened often during play.

Besides, sfinv itself does not even offer the feature I just described above. There's no simple (!) way to make additional formspecs accessible in a way I described above. I actually need *yet another* mod for that. Also, many features should NOT be added in a separate sfinv page. For example, the Help. It is often very desirable to be able to have full control over your own formspec, so the only thing the game needs to do is to offer some means to open it. This is way easier than to be forced to make my formspecs “compatible” with anything. Especially for complex mods like Help or `ltool` doing such “sfinv compability” is completely out of question.

Had I made Help tailored towards sfinv from the start, Help would have been locked to Minetest Game only, and I would have not been able to use the same modpack in MineClone 2 without rewriting a lot of code. You seem to believe that `sfinv` is the solution to everything, but that's not true.

Many games don't have or want sfinv, and often for good reasons. Even if they add some other way to add “multi-purpose features”, they will do so by adding a new API. Unsurprisingly, this has directly lead to multiple competing implementations of the same feature.

The reliance on a single game destroys any possible genericism, which is important to me. You have ignored my concern about that, plus that one about dependencies. And that modifying the inventory is *hard* without breaking it. You have to rely on the game to offer it AND you have to tailor it to one specific game. My argument here is that such dependency could be avoided.

Let me ask you this: If the current strategy would be so great, then how exactly am I supposed to make something like the `ltool` formspec accessible?

Can I depend on sfinv? No, because I can't just add a button, I also need to depend on another mod first (to add button support), and only if the player installed such a mod, the feature will actually be accessible. Also, it will only work in Minetest Game.
Unified Inventory? Better, at least I can add buttons, but then, it will only work in Unified Inventory.
Same problems for Inventory++ and all other related mods.
Actually, that's pretty much what I did for `ltool`. I DID support a few mods, but not all of them. I can never be exhaustive. I have to jump through many hoops to actually make a mod like `ltool` or achievements or whatever accessible via formspecs.

You see, in order to *really* make my formspec accessible, I would have to write code to support ALL inventory mods. But that's not enough because it can not befuture-proof because a new inventory mod might come along anytime, or the API of any inventory mod might introduce breaking changes. And there is no guarantee at all that it will work in all games. This is bad design.

Now let's compare that to my proposal.

The current solution is:

* Heavily depending on the game
* Not guaranteed to actually expose your formspec (in Minetest Game, sfinv is NOT enough if you can't or won't add a page, other games might not even any API for you at all) in all games
* Introducing mod dependencies
* Introducing boilerplate code
* Definitely not future-proof

In comparison, my solution is:

* Guaranteed to work
* Dependency-free
* Very simple to use
* Future-proof, as long the API is stable

> 'Crowded' seems a fabricated complaint, some could say 'rich with features'.

You're missing the point. My problem is not the number of features, but the number of features *gathered in one single place in which they don't belong*.
For instance, do you think it's good that I have to tell new players that they have to open the *inventory menu* to toggle music?

> The inventory is already a multipurpose in-game menu.

This sounds like an argument from tradition. Just because has been used like that does not *justify* it. The official API docs don't suggest such use. Also, you're forgetting that (ab)using the inventory is pretty much the *only* possibility right now to introduce new formspecs into the game. That does not mean that it could be changed in future.

> many things games want to do will then not be possible, 

Not true, as the Game Extras menu is completely separate from the inventory menu.

> and nicely designed formspec designs with particular layouts and graphics not possible either.

That's the only concern I can agree on, but it can be fixed.

The simple fix is to make the Game Extras menu overridable, but mods need to be able to access the list of all game extras then.

This will also be less of a concern when default formspect theming will be implemented.

> Seems like it would be a duplicated feature.

It only seems like that but really isn't. It will only be a duplicated feature if games *choose* to duplicate a formspec button (e.g. for the Help) both in the Game Extras and the inventory. And again, the inventory menu only became the “menu for everything” because games *chose to do so*.

So any duplication can only come from the game, not Minetest.

> So many games will end up choosing to use sfinv tabs and formspecs anyway due to this.

They're free to do so, but there will be no excuse to not use the Game Extras API because it designed to be extremely simple to add to. Whether it's a good idea to duplicate features both in the inventory and the Game Extras should be up to the game maker to decide.

Finally, “game makers are going to make this bad decision anyway” is a weird argument. :P

**Comment by rubenwardy** [comment]
> Sfinv is only for Minetest Game

https://github.com/rubenwardy/sfinv

**Comment by Wuzzy2** [comment]
OK, I take that back. That was a really stupid brainfart, sorry.
However, my other arguments against `sfinv` still stand. `sfinv` is just one of multiple possible inventory mods, and you have to support them all. And `sfinv` is far from ideal for my use case. Nothing against `sfinv`, I think it's fine as-is, just not suited for my request in its current form (at least out-of-the-box).

What I was trying to say here is that supporting `sfinv` or any other inventory mod only grants you support to *some* games, never all of them.

**Comment by paramat** [comment]
Removed my -1 as i haven't thought it through enough, still sceptical though :)

**Comment by Wuzzy2** [comment]
I agree about armor. I am NOT saying modders should now remove everything out of the inventory. Some few things actually do make sense in inventory menu, like craft guide and armor.
Let's just game and mod makers decide.

Achievements/awards seem more far fetched. Help and dev mods are even more far fetched to put into inventory menu.

Using the pause menu does not make sense as it, well, pauses the game. I also have no idea how callbacks are supposed to work while the game is paused. Note I also never did mention “settings” as an use case.

**Comment by Wuzzy2** [comment]
Sigh. Look. Not all games can or want to use sfinv (and for good reasons, I want to add), why do you keep bringing it up? I have already explained why `sfinv` is NOT the ultimate solution to everything and never will be.

This is my problem: I have a mod, and want it to be exposed in the interface. There is NO simple way to do this. I have to support many mods at all. What's worse: The amount of boilerplate code (and dependencies) increases exponentially when the number of inventory APIs or mods that need such an API increases. Even if just one new inventory API is released, modders would have to update ALL of their related mods to not fall behind. Likewise, when a breaking change happens in any inventory API, the fun begins again.

**This is seriously bad and broken design!** Or rather, it's not a design in the first place, it basically has just historically grown.

In a *good* design, a mod like Help would only require ONE standard function call and get exposed in the interface *somehow* and this would just work in all games out of the box, and does NOT need to depend on `sfinv` or any other mod.
My proposed “Game Extras” menu would be one possible implementation of this design and shows that such a design is possible. This doesn't need to be the only possible implementation. Maybe the functionality could be exposed in a different fashion. I still like my “Game Extras” menu, however.

So you do not like the UI part of my proposal. So if you are opposed to a new menu, what other solution do you propose to help  mod like Help, `ltool`, `worldedit_gui` to get exposed in the UI in all games generically?

**Comment by benrob0329** [comment]
I'd like to point out that mods tend to be talored to one game, even if multiple games use the same engine.

Take source mods for example, people can port a CS:GO mod to Garry's Mod, and its certainly easier than porting it to say, Fallout 4, but it still requires effort because they are different games and are set up in different ways. Minetest is also a game engine, and different games will require different styles of UI and menus, to say that one setup would work for all games would be silly. 

At this point, due to the nature of MTG, servers all essentially run custom games. Which makes mod compatibility difficult. However, this is both the fault of MTG for not having a good inventory until recently, as well as the servers who still don't use the standard inventory.

Perhaps what would be better would be a way to define custom tabs or menus in a table that the given game's inventory can pull from when displaying the various tabs and menus.

**Comment by paramat** [comment]
> Not all games can or want to use sfinv

I didn't suggest that in my last comment, i suggested your API displays in the invenrotry menu.
> why do you keep bringing it up?

I'm not bringing it up, i'm replying to your continued silly assertion that inventory menu can only be for inventory-related stuff.
I understand using sfinv is problematic in some ways.
> So if you are opposed to a new menu, what other solution do you propose

I just wrote that in my last comment: your suggested API can display in the inventory menu.
