### ISSUE TITLE
Plantlike placement offset broken (possibly only on macOS)

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7872]
##### Issue type
 - Feature request

##### Summary
I'd like for plantlikes to be able to automatically be placed with a small offset from their centerpoints. This would greatly increase the visuals as it would reduce the sight of plants in straight lines.

So instead of, say, this centered placement only:
```
·              ·


       x        


·              ·
```
…a flag called, say, `offset = true` would randomly alternate placement points between these positions:
```
·              ·
                
     x   x      
                
     x   x      
                
                
·              ·

**Comment by Ezhh** [comment]
This is already possible using meshoptions.

For example, here you can see the selected plant is not centred for the selection box and the next (identical) plant has a different placement.
![offset](https://user-images.githubusercontent.com/7035183/48661170-cd31f580-ea65-11e8-83fa-6d3cc543927b.png)

This can be done with:
```
		paramtype2 = "meshoptions",
		place_param2 = 8,
```

**Comment by tacotexmex** [comment]
Oh wow, nice! I can't find what `8` means in lua_api.txt though, is it undocumented?

**Comment by tacotexmex** [comment]
I put `paramtype2` and `place_param2` in grass node 1 through 5, erased map.sqlite in my test world, but all I see is straight lines of grass. Using 4d2539b. What am I doing wrong?

![screenshot_20181117_185516](https://user-images.githubusercontent.com/25328789/48664122-611db480-ea9a-11e8-9f17-96e078530ddc.png)

**Comment by Ezhh** [comment]
Here: https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1035

This is the code for the node in my screenshot (taken from the game I am working on), in case it helps you:
```
minetest.register_node("plants:green_grass_3", {
	description = "Grass",
	drawtype = "plantlike",
	tiles = {"plants_green_grass_3.png"},
	inventory_image = "plants_green_grass_3.png",
	waving = 1,
	paramtype = "light",
	paramtype2 = "meshoptions",
	place_param2 = 8,
	sunlight_propagates = true,
	buildable_to = true,
	walkable = false,
	groups = {snappy = 3, attached_node = 1, flora = 1, fibre_plant = 1},
	selection_box = {
		type = "fixed",
		fixed = {-6 / 16, -0.5, -6 / 16, 6 / 16, -3 / 16, 6 / 16},
	},
})
```

As you can see, no straight lines here:
![grrrraas](https://user-images.githubusercontent.com/7035183/48664769-84952f00-ea9b-11e8-8fcd-37814a1c3e96.png)

**Comment by tacotexmex** [comment]
Okay, so I tried using Ezhh's exact node definition, without textures obviously, but nonetheless you can see the plants going in a straight, predictable line. Does that mean I've discovered a bug?

![screenshot_20181117_211215](https://user-images.githubusercontent.com/25328789/48665389-91228300-eaad-11e8-8086-c9d45564f77e.png)

**Comment by Ezhh** [comment]
Assuming you are using current dev version (I'm not sure when this was implemented), then I'm not sure what bug there can be, since it works without a problem for me. I'm not sure what you might be doing differently.

**Comment by paramat** [comment]
There probably isn't a bug as it works for everyone else.

**Comment by tacotexmex** [comment]
Alright, I’ll keep at it then. Many thanks for this feature.

**Comment by tacotexmex** [comment]
Yeah, as I tried using Ezhh’s code and my results differ from theirs I’m starting to suspect it’s the platform.

**Comment by tacotexmex** [comment]
Just wondering, paramat, "works for everyone else" may then not include anyone on macOS. Issue should be kept open imo.

**Comment by tacotexmex** [comment]
Another clue found: it works when manually placing the plantlike but not for mapgen decorations. But that's a bug too, right?

**Comment by paramat** [comment]
`place_param2` only works when a player places a node. For mapgen setting or param2 use https://github.com/minetest/minetest/blob/1c91cb8f8f6ea15dc1308aace666bd1ebd25a28c/doc/lua_api.txt#L6463

**Comment by tacotexmex** [comment]
Oh ok! I’ll try it soon. Thanks!

**Comment by paramat** [comment]
Odd. To clarify it would be `param2 = 0,`

**Comment by paramat** [comment]
Double checked, i am correct above, for example see the comment in the PR that added the offset feature https://github.com/minetest/minetest/pull/3923#issuecomment-244463630
For offset in mapgen: In nodedef use `paramtype2 = "meshoptions"`, in deco reg use `param2 = 8`.
`place_param2 = n` is only valid in nodedef and only affects player placement.

**Comment by paramat** [comment]
Also see commit message of https://github.com/minetest/minetest/commit/2e69711613c18e1075f245d196823ea23675f027

**Comment by paramat** [comment]
Sorry wrote wrong words in https://github.com/minetest/minetest/issues/7872#issuecomment-441119610
'param2 = 8' goes in the decoration registration,

**Comment by paramat** [comment]
tacotexmex, seems solved but can reopen if not.

**Comment by paramat** [comment]
Good news.
