### ISSUE TITLE
Max HP change damage flash

### ISSUE THREAD

**Issue by Ezhh** [minetest/minetest#7876]
Currently reducing a player's max hp to a value less than current hp gives a very visible red flash and camera tilt because it counts as damage being done. This makes perfect sense, until you want new players to start the game with less than the engine's default hp.

Example code:
```
minetest.register_on_joinplayer(function(player)
	local max_hp = player:get_meta():get_int("hp_max")
	if max_hp == 0 then
		max_hp = default_max_hp
	end
	minetest.after(0.1, function()
		player:set_properties({hp_max = max_hp})
	end)
end)
```
I've had to use `minetest.after` here, because for whatever reason, the max hp doesn't get set without it, but the `minetest.after` in turn means new players are hit by the flash and tilt, which is pretty off-putting. The other option, to have a separate `register_on_newplayer `check also doesn't solve this, because it makes the mod far less flexible and prevents it being added once there are already existing players.

Can we please add an option to skip the flash and camera tilt when specifying a new max_hp value?

**Comment by SmallJoker** [comment]
> I've had to use minetest.after here, because for whatever reason, the max hp doesn't get set without it

It does get updated, but the builtin HUDs are bugged (PR exists). Damage yourself and it should display correctly again. If in doubt, change the position of the health bar to ensure the client HUDs aren't messed up (sometimes happens, PR also exists).
Thus, set the `hp_max` value before builtin is executed -> Example: https://github.com/SmallJoker/upgrade_packs/blob/291eca2/init.lua#L46-L49

What if the `hp_max` value is altered while the player is playing? They would want to see a damage screen because their HP decreased (assuming it was above the new max value).

**Comment by Ezhh** [comment]
So the bug is the HUD ? That gives me more options - thanks for the input. :)

> What if the hp_max value is altered while the player is playing?
Yes, damage being visible in gameplay when max hp is reduced below current makes sense, it just doesn't make sense for a new player to experience that on first join (or for a new player on first join to see more hearts than they actually have).

> A possible solution would be to make the maximal HP (and breath) configurable when the mods are loaded. 1 for each would avoid this kind of issue.
A way to avoid this be very nice. From a modding perspective it's currently a bit messy to get this working.

**Comment by paramat** [comment]
I'm not sure that resetting player max_hp to a lower value should count as damage done, as it is altering a player property, not intentionally dealing damage.
In which case the fix might be easy, and if a modder wants to 'show damage' to the player they would first damage the player by any amount, then also reduce max_hp.

**Comment by Ezhh** [comment]
At the moment I getting round it by dealing damage early in the `register_on_joinplayer` then only setting the max hp in the `minetest.after`, but it's far from ideal and workarounds like this shouldn't be needed. There is nothing modder-friendly about this.
