### ISSUE TITLE
V7 rivergen removing nodes placed by on_generated() (move rivergen into main mapgen loop)

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#7878]
##### Issue type

 - Bug report
 
##### Minetest version

```
minetest-5.0.0-0e306c0-win64 (sfan5's build)
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel i7-3770K @ 3.5GHz, 8.00 GB ram

##### Summary

In the course of adding volcanoes generated by [my magma_conduits mod](https://github.com/FaceDeer/magma_conduits/tree/7f621e4b9270423c7a95fd03f076d0bd886e151fl) I've discovered that the v7 mapgen sometimes carves curvy slices one node tall through the mountains I'm placing using an on_generated method. The slices are at the top or bottom y level of the generated map block and appear to coincide with river paths. Apparently this is the same problem seen in issue #7379.

##### Steps to reproduce

I've attempted to work around the problem with a hack that replaces the missing nodes using a minetest.after call, when reproducing this using my mod you'll need to edit volcanoes.lua line 66:

```
-local mg_name = minetest.get_mapgen_setting("mg_name")
+local mg_name = nil--minetest.get_mapgen_setting("mg_name")
```

This will disable detection of mapgen v7 and prevent my workaround from triggering.

To find examples, generate a mapgen v7 world with seed "1" and apply the magma_conduits volcano branch. Teleport to any of these coordinates to find a volcano that intersects with a river:

1616, 45, 498
1883, 45, -1920
1751, 45, -2041

If this is unreliable I could whip up a mod that puts a layer of nodes at that altitude throughout the whole map, that'll probably catch it more reliably.

**Comment by paramat** [comment]
See the previous fix https://github.com/minetest/minetest/pull/7388/files
Rivergen will only remove "mapgen_stone" nodes ("default:stone" in MTG). Are you placing 'stone'? it's always better to place mod nodes that drop normal stone, if you place 'stone' in lua mapgens it tends to cause several issues.

**Comment by FaceDeer** [comment]
The bulk of the mountain is stone, but there are other materials too - lava, an obsidian lining (potentially a custom type of obsidian if "heated rock" is enabled in the mod), and various types of soil and snow on the mountain's flanks. In the longer term I have plans for another mod that will replace "default stone" with various different types of real world bedrock, at which point volcanoes will be made mostly of rhyolite or basalt.

I'm fine with this being low priority since I've hacked a workaround into the mod in the meantime.

**Comment by paramat** [comment]
Do the non-stone nodes get removed too?

**Comment by FaceDeer** [comment]
Doesn't appear so. I just tried turning the cone material to default:wood and the slices didn't appear.

It also amused me greatly watching the wooden volcano immediately catch fire.

**Comment by paramat** [comment]
Ok, this is certainly the same issue as #7379 and you're experiencing the one case where the fix doesn't work: "mapgen_stone".
This is worth keeping open because a solution would be to move rivergen into the main mapgen loop instead of being a 2nd separate loop. This might also improve mapgen performance. If i code this and it does improve performance (or at least doesn't reduce performance) i'll make this change.

**Comment by FaceDeer** [comment]
Thanks. I don't consider this one particularly urgent since there are a number of workarounds, and even when not worked around it's not that big a deal. I'm more concerned with #7864, that one is making me hesitate to merge volcano generation back into the master branch of my mod since it can permanently bork a world.

**Comment by paramat** [comment]
PR #10639
