### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7880]
##### Issue type
- Translation issue
 
##### Minetest version
67b20ff15a4786edd76adcbdb921fcc4acac7113

##### Summary
A couple of strings are currently untranslatable or Minetest fails to show the translation:

* `builtin` strings enclosed in `core.gettext` (not collected by `updatepo.sh`)
* Strings in `game.cpp` when `showOverlayMessage` is called (e.g. “Shutting down...”)
* “Unknown node: [node name]” when you hover an unknown node

Please post in this issue if you have found more missing strings

**Comment by SmallJoker** [comment]
Relevant code part - should be a quick task to add the functions mentioned above:
https://github.com/minetest/minetest/blob/67b20ff15a4786edd76adcbdb921fcc4acac7113/util/updatepo.sh#L51-L64

**Comment by Wuzzy2** [comment]
#9513 will fix this:

> builtin strings enclosed in core.gettext (not collected by updatepo.sh)

**Comment by Wuzzy2** [comment]
This one is already fixed:

> Strings in game.cpp when showOverlayMessage is called (e.g. “Shutting down...”)

And this one is no longer relevant, as it isn't displayed anymore:

> “Unknown node: [node name]” when you hover an unknown node

This means, as soon #9513 is merged, this issue is fixed.

**Comment by Wuzzy2** [comment]
UPDATE: Ignore #9513 from now on, this issue has been superceded.

If #10693 is merged, this issue is fixed.
