### ISSUE TITLE
Mod translations: Cannot translate #

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7881]
##### Issue type
- Bug report
 
##### Minetest version
67b20ff15a4786edd76adcbdb921fcc4acac7113

##### Summary
Can't translate the “#” in mod translations if it's at the beginning of a string.

This is probably because “#” acts as a comment sign in the `.tr` files.

Possible solution: Make it mandatory to escape “#” with “@#” and update docs accordingly.

##### Steps to reproduce
Create a mod with name `test_translate` and the following code:
```
local S = minetest.get_translator("test_translate")
minetest.register_craftitem("test_translate:comment", {
        description = S("#Comment"),
        inventory_image = "default_dirt.png^[colorize:#FF00FF:127",
        wield_image = "default_dirt.png^[colorize:#FF00FF:127",
        groups = {dig_immediate=3},
        is_ground_content = false,
})
```

**Comment by jingkaimori** [comment]
Could #14726 solves this issue?

**Comment by Wuzzy2** [comment]
I haven't tested this, but I assume the "#" will work indeed in PO files. The official recommendation is to move away from TR anyway, so I consider this closed. Thanks!
