### ISSUE TITLE
Translate builtin

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#7883]
##### Issue type
 - Feature request
 
##### Minetest version
5.0.0-dev

##### Summary
There are still many portions of `builtin` which are untranslated. A large portion is for server-side chat commands and privileges.

Since mod translations are possible now, I believe the server-side portion of `builtin` should be possible to be translated as well. Please give your ideas.

The goal of this issue is to make all user-facing strings in `builtin` translatable.

TODO:
* [ ] Chat commands and output (server side)
* [ ] `help` command and output
* [ ] Chat commands and output (client side)
* [ ] Default node names (air, ignore, unknown)
* [ ] Misc. messages and strings

**Comment by Wuzzy2** [comment]
I have experimented with the `builtin` code a bit and figured out that `minetest.get_translator` could actually used for the server-side translations.

I haven't figured out where to put the `locale` directory, however. But when I put it into any mod, the locale files actually get loaded, allowing me to translate `builtin`.

I hope to post my work on `builtin` soon.

**Comment by SmallJoker** [comment]
Stalling PR #7019

**Comment by CarlosBarrazaE** [comment]
How do I select the server language to display the translated logs?
