### ISSUE TITLE
How do we modify the CSM death screen in builtin?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7886]
Possibly a silly question, but ...
The death screen was moved to CSM to make it modifiable by CSM mods, however i can't see how the death screen code in builtin can be overriden to avoid that still running.
Is the code in builtin/client/init.lua unfinished?
https://github.com/minetest/minetest/blob/master/builtin/client/init.lua

**Comment by paramat** [comment]
Meh not important.

**Comment by jastevenson303** [comment]
Well I think it is.  I've wanted to modify death screen for longer than CSM
has been around.
