### ISSUE TITLE
'Sub-node lighting' and spherically-spreading light

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7887]
##### Issue type
Feature request

- Sub-node lighting

Then using sub-node lighting
- Circular lighting
#### Current lighting
![screenshot_2018-11-23-13-02-35-1](https://user-images.githubusercontent.com/33675971/48960290-27c4c900-ef20-11e8-949d-d13aacbc4721.png)
#### Future lighting capabilities
![3to6hgw5mf511-1](https://user-images.githubusercontent.com/33675971/48960505-07960980-ef22-11e8-8fbb-883d144b97c1.png)

Note: MC Screenshot of someone requesting circular lighting (used as an example)
And (also with SNL*)
Entity lighting would be possible 
- Entity lighting

#### Now away from SNL

Minetest allows for the darkening of nodes but not lightening! 
- Node lightening to simulate brighter light

With node lightening coloured lighting could be added
- Coloured lighting

And also with SNL
This could be done! 
![screenshot_2018-11-23-13-31-37-1](https://user-images.githubusercontent.com/33675971/48960759-47f68700-ef24-11e8-8683-7a42681b92d0.png)
Blockmens video
https://youtu.be/PBMOG_dTbWo
Example

SNL = Sub-Node Lighting

**Comment by paramat** [comment]
What is sub-node lighting? We somewhat have this already with smooth lighting.
Lighting in MT is a per-node value and that can't be changed to a higher resolution.
Maybe you mean shadows?
//////////////

Circular (actually spherical) lighting:
Light in MT spreads from node to node in NSEW directions, dropping by 1 each time. This results in the diamond shape of a pool of light. The light spread event is extremely simple but repeated many thousands or millions of times. Light calculations are one of the most intensive parts of MT.

To create a spherical limit of light would involve fairly complex calculations on every light spread step, this would multiply the intensity of light calculations by a very large amount, so is simply not possible, MT would be unplayable. Maybe possible in 10 years when the average computer is 100 times more powerful.

Apart from that, in MT many things that are circular or spherical in real life are square or cuboid (it's a voxel game), so circular lighting is inconsistent with the rest of MT's appearence and, to me personally, looks ugly and out of place.
/////////////////

Entity lighting is already possible, but entities do not light up their surroundings, there is an issue for that #6921
////////////////

"Node lightening to simulate brighter light"
This doesn't make sense, the maximum light value in MT is 15 and the texture defines how bright it looks.
/////////////////

Coloured lighting already has an issue open, please discuss there #2670
> This could be done!

That doesn't show coloured lighting, BlockMen's fork doesn't do coloured lighting.
///////////////

The remaining valid request here is 'sub node lighting' which i assume is shadows. Oddly we don't have a feature request for that so this can be it.

**Comment by paramat** [comment]
@Extex101 please explain what 'sub-node lighting' is. Do you mean directional light and shadows, like in BlockMen's video?

**Comment by Extex101** [comment]
Which could be used for directional lighting
So in order for directional lighting to be possible you would need to be able to light a fraction of a node

**Comment by paramat** [comment]
Thanks, i see. That's not possible as light level is a per-node value. Also, it would be a far more complex way to do directional light and shadows, probably impossibly complex. Using 'hardware lighting' is the best way to do that.

**Comment by HybridDog** [comment]
Maybe you could, in the 2d sunlight only case, save four light values for each node, each value corresponds to a diagonal vector.
When spreading the light from a node, all 8 surrounding positions are considered. The neighbouring

**Comment by paramat** [comment]
Sub node lighting is impossible and spherical spread would destroy game performance.

**Comment by rdococ** [comment]
A very simple hack to make the spread appear closer to spherical could be to spread light diagonally, but only some of the time - for example, at high light levels, or maybe just at even light levels.

**Comment by paramat** [comment]
In practice it's not very simple, and there are big disadvantages besides the slightly larger area. See issue.
