### ISSUE TITLE
Make chat vertical position configurable

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#7888]
##### Issue type
 - Feature request
 
##### Summary
Currently there's no possible use for the top-left corner of the screen other than the hard code positioned chat. The possibility to move the chat to lower positions on the screen would allow for other uses of the top-left corner.

**Comment by paramat** [comment]
Best discussed in #4143 as that discusses how chat covers F5 debug info, so discusses vertical positioning.
