### ISSUE TITLE
Per node box texturing

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7889]
##### Issue type

 - Feature request
 
#### TO FIX PROBLEMS LIKE THIS
![screenshot_12133464](https://user-images.githubusercontent.com/33675971/48973873-8496b100-effe-11e8-93bb-a91f98c96548.png)
From the MT forums

Example code
```
minetest.register_node("mymod:node", {
   drawtype="nodebox",
   tiles = {
      {
          "mymod_txt1.png","mymod_txt2.png","mymod_txt1.png",
           "mymod_txt2.png","mymod_txt1.png","mymod_txt1.png"},
    },
     {
          "mymod_txt1.png","mymod_txt2.png","mymod_txt1.png",
           "mymod_txt2.png","mymod_txt1.png","mymod_txt1.png"},
    },
    {
          "mymod_txt1.png","mymod_txt2.png","mymod_txt1.png",
           "mymod_txt2.png","mymod_txt1.png","mymod_txt1.png"},
    },
   },
   node_box = {
       type = "fixed",
       fixed = {

            {-0.1,-0.5, -0.1, 0.1, 0.1 ,0.1}, -- foot chair connect
            {-0.40, 0.0, -0.40, 0.40, 0.1, 0.40}, -- the seat
            {-0.2,-0.5, -0.2, 0.2, -0.4 ,0.2},-- foot of chair 
            { 0.40, -0.00, 0.30, -0.40, 0.50, 0.40},-- back side
            { 0.40, 0.40, -0.30, 0.30, 0.50, 0.40}, -- right side
            { -0.40, 0.40, -0.30, -0.30, 0.50, 0.40}, -- left side
            { -0.40, 0.00, -0.30, -0.30, 0.50, -0.20}, -- front left arumchair piece
            { 0.40, 0.00, -0.30, 0.30, 0.50, -0.20}, -- front right armchair piece
       }
   },

})
``

**Comment by rubenwardy** [comment]
Please clarify, I'm unsure what you're actually requesting

**Comment by Extex101** [comment]
Make it so you can choose the up, down, left, right, front, back, textures for each box

**Comment by rubenwardy** [comment]
Meshes should be used instead here. It already supports what you want to do

**Comment by paramat** [comment]
Because you're using nodeboxes the 'top' texture is applied to the top of every nodebox.
You need to use a mesh and 'UV map' textures to where you want them, however this is not easy to do and needs to be done in a separate program.
I guess you want nodeboxes to accept multiple textures for every box.

**Comment by Linuxdirk** [comment]
> Meshes should be used instead here. It already supports what you want to do

Except you want to visually connect them to other nodes.

**Comment by DS-Minetest** [comment]
@Linuxdirk Are you referring to connected nodeboxes?

**Comment by Linuxdirk** [comment]
Woah, had notifications on GitHub turned off ...

Yes, I am referring to `connected_*` and `disconnected_*` in the nodebox definition having the node  showing additional boxes depending on neighbors.
