### ISSUE TITLE
No scrollbar in formspec text field

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7890]
##### Issue type

 - Bug report
 
![screenshot_2018-11-24-15-53-09-1](https://user-images.githubusercontent.com/33675971/48974000-28815c00-f001-11e8-9f4f-de955e3ae8b3.png)
To view off screen text you have to press the down key
And on mobile you can't just press the down button
So it's even harder

**Comment by paramat** [comment]
What formspec is this?

**Comment by SmallJoker** [comment]
Install 5.0-dev to make use of the scrollbars.

**Comment by Extex101** [comment]
@paramat it's the book formspec

**Comment by Extex101** [comment]
@SmallJoker I can't because it's not available in a windows build

**Comment by SmallJoker** [comment]
https://forum.minetest.net/viewtopic.php?f=42&t=1523
