### ISSUE TITLE
[Lua] Default wielditem entity size is inconvenient

### ISSUE THREAD

**Issue by Unarelith** [minetest/minetest#7897]
When defining a wielditem entity, if you want to make it sized like a regular node you would have to do this:
```lua
minetest.register_entity("mymod:myentity", {
	initial_properties = {
		visual = "wielditem",
		textures = {"mymod:myblock"},
		visual_size = {x=0.666, y=0.666}
	}
})
```

I think default node size should be 1, not 0.666. This will probably break some mods, but I it won't be hard for mod devs to adapt to this change.

We discussed a bit about it on IRC:
> [Unarelith] rubenwardy, to make a wielditem entity sized like a regular node, you currently have to use `visual_size={x=0.666, y=0.666}`, it's weird and unconvenient
> [rubenwardy] have you actually tried this?
> [Unarelith] yes, and 0.666 seems to be exactly the regular node size
> [rubenwardy] reading the code, visual_size is a direct multiplier for it
> [rubenwardy] so what's happening is that the wielditem is drawn at a different size to begin with
> [rubenwardy] so to change the 0.666 thing, you'll also have to change wield item and inventory mesh things
> [rubenwardy] well, you could just add it as a multiple to visual size

**Comment by Quent42340** [comment]
Could be related to #7870 and #6986 (for example, the 'item' visual type could automatically adapt the size)

**Comment by paramat** [comment]
+1
I was thinking about this recently. I've noticed this weird wielditem scaling too. I use 'visual = "wielditem"' to create vehicles and mobs.
I assume the scaling was hardcoded long ago when 'wielditem' was only used for wielditems and that scale just looked right for wield. Better to make it match to nodes and set visual scale every time.

**Comment by paramat** [comment]
The necessary scaling by 0.667 is shown in falling.lua:
https://github.com/minetest/minetest/blob/4ba5046308d6bdf7b38394770c6f82b6927393f2/builtin/game/falling.lua#L4
https://github.com/minetest/minetest/blob/4ba5046308d6bdf7b38394770c6f82b6927393f2/builtin/game/falling.lua#L39-L48
