### ISSUE TITLE
Worse performance in fullscreen than in window mode with same resolution

### ISSUE THREAD

**Issue by pkreuzt** [minetest/minetest#7898]
##### Issue type

 - Bug report

 
##### Minetest version

Minetest 0.4.17.1 (Linux)

##### OS / Hardware

Operating system: Debian Buster 64bit
CPU: Pentium Core G3420
GPU model: Intel processor integrated
OpenGL version: 3.0 Mesa 18.1.9

##### Summary

Very poor performance in fullscreen mode, even with same resolution than in window mode. Running in 1920x1080 window gets 50-60 FPS and drawtime 18-22. Running in fullscreen mode 1920x1080 it only gets 24 FPS max and 38-40 drawtime.

##### Steps to reproduce
Just change minetest.conf to fullscreen = 1

**Comment by rubenwardy** [comment]
I suggest using the fullscreen feature which hopefully comes with your DE, in the meantime. It tends to be alt+f11

**Comment by sfan5** [comment]
https://github.com/minetest/irrlicht/compare/393793f...c84d8ac
