### ISSUE TITLE
Accepting PRs/patches from non-Github users

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7901]
GitHub uses proprietary Javascript with a unreleased backend. This results in some people being unwilling to use it. For those who use Github but with Javascript disabled, it's possible to comment but it's not possible to open a PR.

There are quite a few skilled people we could be missing out on, so it's worth having an alternative available. There are quite a few possibilities for this, including archaic methods such as mailing lists, but I'd prefer a solution which would automatically open a PR and allow submitting new content to it.

cc/ @Wuzzy2

Related: #7412

**Proposals:**

* PRs on Gitlab, mirror to Github
* Create PRs from a Minetest fork and branch via an email or website. Users would push to their fork on github as usual to update the PR
* Create PRs by emailing patches, and having them opened on Github by a bot
* Switch to Gitlab/etc (flamewar starting in 3.. 2.. 1..)

**Comment by paramat** [comment]
My opinion: Whatever is simplest for MT core devs to set up and maintain (since we have very limited time). 1 or 3 sound best, 2 sounds possibly complex. Not 4 :) not for this reason only anyway, it may happen for other reasons eventually though.

**Comment by pgimeno** [comment]
Since 1 doesn't seem to involve having to write bot code, it's probably best (I'd prefer 4 but...). I'm eager to see this happening. I will probably drop this user before the end on the year.

**Comment by nerzhul** [comment]
i think switching to gitlab.com can be nice, as our gitlab mirror provides many useful features, like commit based builds (with debian, ubuntu, fedora, docker, windows packages), whereas github provides travis the old unmaintained tool :(
Also gitlab can be nice for publishing docs easily though the gitlab pages which are less restrictive than the github pages (from my point of view)
Last, Gitlab has subgroups, can be nice to have community mods inside minetest/mods groups directly if we want to have a better community sharing

**Comment by Calinou** [comment]
> i think switching to gitlab.com can be nice, as our gitlab mirror provides many useful features, like commit based builds (with debian, ubuntu, fedora, docker, windows packages), whereas github provides travis the old unmaintained tool :(

It's possible to deploy continuous releases using any CI system; you just need GitHub.com API access. Tools like [gothub](https://github.com/itchio/gothub) make this easier, see [this script](https://github.com/Calinou/escape-space/blob/master/.azure-pipelines/deploy.sh) where I used it on Azure Pipelines for an example.

> Also gitlab can be nice for publishing docs easily though the gitlab pages which are less restrictive than the github pages (from my point of view)

What kind of restrictions are you talking about? Even though it's more involved, it's possible to use static site generators other than Jekyll on GitHub Pages by building the site files on CI and pushing them to a branch on every commit.

**Comment by nerzhul** [comment]
@Calinou yes, but travis build system is very restrictive, azure pipelines is azure then more microsoft, we can upload releases from gitlab to github yes. 
What is like in Gitlab is not only their pipelines which is massively good, but also their transparency and all the features you got on a repository by default :)

**Comment by pgimeno** [comment]
This is pgimeno leaving MSGitHub as announced. If I can submit MRs to GitLab, that would allow me to collaborate better than the last days I was here, so I hope this issue gets more attention in the near future.

**Comment by paramat** [comment]
I've just realised that 'ghost' isn't an actual user, took me a while ... >_>:
"Hi, I'm @ghost! I take the place of user accounts that have been deleted."

Anyway, make sure to hang around on IRC, you're an excellent contributor, i really appreciate the effort you've made.

**Comment by sofar** [comment]
Leaving a copy of what I posted in IRC earlier here:

Allowing a secondary place for PRs to happen would split the community, as some people would only see discussion posts from one side, and not the other. This isn't just unwanted, I think it would be unacceptable.

The only logical conclusion is that we can't `split` PR discussion across multiple places, and therefore discussion must happen in a single location only.

The result: Only the 2 following options are an improvement:

1) self-hosted (e.g. gitlab or whatever open source variant) git
2) mailinglist-style PR management

Both are a major change and should only be done if there is really a doubt that github is a risk. Currently I don't see this is the case, and therefore I do not believe that allowing PRs to happen elsewhere is conductive at all.

**Comment by sfan5** [comment]
Neither of those two sound like good options to take right now.
The only alternative I can think of is that:
* a coredev opens a PR on github with the same content as a PR on another platform (kept in sync at request of the author)
* code review and discussion <i>with the author</i> needs to happen on IRC
* everything else (approvals, other discussions, pressing the merge button) can still happen on github

This approach has obvious downsides and isn't convenient, but I think it's the most viable we have.

**Comment by sofar** [comment]
I wouldn't mind seeing a patch mailinglist, so that interested devs can just `git am`those and make a PR. Having to scrape 5 different collab websites isn't a good use of anyone's time, but a mailinglist is relatively easy to follow, and everyone should be able to email patches.

Then at least there's a consistent place for everyone who doesn't want github, which is better than random contributors asking random core devs to open PRs for them from random websites.

**Comment by Zughy** [comment]
I find it absurd that a FOSS code dwells on GitHub, which is owned by Microsoft. Imho option 4 is the best, also from a mere practical perspective as I found GitLab more handy.
Option 2 requires too much work to do for core devs, option 3 with bots doesn't sound handy and option 1 may be a good start

**Comment by nerzhul** [comment]
very old issue, not sure we will switch at a point, but i would like it, and it will need some announces to community. Currently github provide more services that gitlab (windows builds) in the CI

**Comment by LoneWolfHT** [comment]
Barely looked into it but would this work? https://hub.github.com/

**Comment by paramat** [comment]
Zughy, whether to move or not has been discussed in depth in the forum and elsewhere,
The opinion of the core devs is: We might move elsewhere at some time in the future, but only if there is an actual, substantial, practical reason to do so, not because of 'libre'-idealogical reasons or a dislike of MS.
This is also the view of celeron55.

Luckily, none of the MT core devs, or celeron55, are 'libre'-extremists, we like FOSS but are rational and practical. MT has never actually been 'libre'-extremist, but some try to portray it that way to push their own agenda.

**Comment by ClobberXD** [comment]
@LoneWolfHT That still requires a GitHub account. It'd make sense, however, if users are trying to only avoid certain aspects of the GH website, like the proprietary JS.

**Comment by Zughy** [comment]
@paramat agree to disagree: MT took its own position back when celeron55 decided to create a FOSS game (which now aims to be an engine, as far as I understand). It's not about being extremists, it's about coherence. If then you're saying GitHub offers more practical tools to work with than GitLab does, then ok. But putting aside the Microsoft concept like it doesn't really matter, that's a nonsense

**Comment by Zughy** [comment]
Stale for four years, no interest shown, closing
