### ISSUE TITLE
Current MT slows down mysteriously

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7904]
I haven't identified the issue, yet, but filing an issue anyway in case someone else has seen it.

I noticed that Minetest rendering sometimes becomes slow (down to a few FPS). Restarting MT and then showing the very same scene is faster again.

See the following two screenshots:
![screenshot_20181126_231836](https://user-images.githubusercontent.com/446130/49065312-86b16900-f1d2-11e8-945e-deb4ee9792a5.png)

After a restart (exact same scene):
![screenshot_20181126_231946](https://user-images.githubusercontent.com/446130/49065313-86b16900-f1d2-11e8-957d-60f03969b3b2.png)

You can see that more blocks are in view and slightly more are being rendered, but that does not account for the difference.
In the profiler I see almost all time spent in irr::video::CNullDriver::getBufferLink, which goes away after the restart.

Any ideas?!

**Comment by HybridDog** [comment]
https://sourceforge.net/p/irrlicht/code/HEAD/tree/branches/releases/1.8/source/Irrlicht/CNullDriver.cpp#l1541

**Comment by lhofhansl** [comment]
Note that this is somewhat recent thing (at least I do not remember observing this before)

**Comment by lhofhansl** [comment]
I'm still observing this, btw.
It mostly shows up in scenes with lots of trees.

**Comment by TumeniNodes** [comment]
It shows up in Pine forests, but the worst has been in jungles. I have seen this for quite some time now... it is definitely not recent

**Comment by lhofhansl** [comment]
Year old issue... No proposed solution... Closing.
