### ISSUE TITLE
Exact location of `pointed_thing`

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7907]
##### Issue type
 - Feature request
 
##### Minetest version

```
0.5.0-b6adb7f
```

##### Summary

I need to place an entity at the exact pointed location
maybe have a pointed_thing.exact_pos

##### Steps to reproduce

Make a mod with this code:
```
minetest.register_entity("mymod:entity", {
visual = "cube",
	textures = {
		"default_dirt.png",
		"default_dirt.png",
		"default_dirt.png",
		"default_dirt.png",
		"default_dirt.png",
		"default_dirt.png",
	},
	visual_size = {x=0.3, y=0.3, z=0.3},
	collisionbox = {-0.14, -0.14, -0.14, 0.14, 0.14, 0.14},
})
minetest.register_craftitem("mymod:item", {
	description = "Entity placer",
	inventory_image = "default_stick.png",
	on_place = function(pointed_thing, itemstack)
               local pos = pointed_thing.above
               minetest.add_entity(pos, "mymod:entity")
               return itemstack
        end,
})
```
So instead of placing at the exact position it is placed at centre of above node

**Comment by ClobberXD** [comment]
Just a small nit: `pointed_thing.above` itself is a pos, and `pointed_thing.above:getpos()` is an invalid operation. See https://github.com/minetest/minetest/blob/9519d57017cfa28eb4f2fbf3c780f826017bbb00/doc/lua_api.txt#L1316-L1321

**Comment by Extex101** [comment]
Oops that was just an accident fixed

**Comment by SmallJoker** [comment]
Dig and place actions do not supply enough information to simply calculate the exact pointed location. Use `Raycast` for further precision.

**Comment by DS-Minetest** [comment]
> Dig and place actions do not supply enough information to simply calculate the exact pointed location. Use `Raycast` for further precision.

If you've got a `pointed_thing` with `type="node"` and a player object, you have got enough information to calculate the exact pointed location with nearly the same precision as `Raycast`.
For normal node-sized cube nodes this is already implemented in minetest:
https://github.com/minetest/minetest/blob/327bad2eafb8cfc05b7f831992be5700a167a53c/doc/lua_api.txt#L2442-L2444
[But it's also possible for all types of nodes.](https://github.com/DS-Minetest/minetest/blob/fec435d18cb0544f2a0fd38fc8db8b242f2eed0d/builtin/common/misc_helpers.lua#L772-L825)
