### ISSUE TITLE
minetest.get_biome(pos)

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7910]
##### Issue type

 - Feature request
 
basically have a `minetest.get_boime` that returns the biome name of a pos

**Comment by jastevenson303** [comment]
It's already there.  i'll get the line number in lua_api...

**Comment by Extex101** [comment]
I found a documentation error
https://github.com/minetest/minetest/blob/5f1cd555cd9d1c64426e173b30b5b792d211c835/doc/lua_api.txt#L890
meant to be: `minetest.registered_biomes`

**Comment by paramat** [comment]
Thanks, please open a new issue for that.
