### ISSUE TITLE
Player files no longer writen?

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7911]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.5.0-b6adb7f
```

##### Summary

(Only in 0.5.0)
Player files are no longer written but player info still preserved?

##### Steps to reproduce

1. Create a new world
2. Host it
3. Chose a name
4. Join
5. Go into worlds/world/players
6. No player files?

**Comment by paramat** [comment]
Is this due to auth now using a database?

**Comment by Extex101** [comment]
Oh... I see
Your using an SQlite3

**Comment by paramat** [comment]
See #7279

**Comment by rubenwardy** [comment]
Actually, thinking about it: there could be a bug here, which is that the players dir is still being made
