### ISSUE TITLE
[Request] Raise HUD hotbar limit to 32 slots

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#7915]
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/hud.h#L53

This sets an arbitrary limit, which aside from my screen being able to handle more, is an unusual value given that the default inventory is an 8x4 grid (so why 23, instead of 24 or 32?).

Changing this value alone is enough to allow more hotbar slots (I checked up to 28, the limit of my screen at my usual GUI scaling).

There are other places in the code that reference a hardcoded value of 23, without referring to this specific `#define`, for example these key assignments:
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/client/keys.h#L76-L99
https://github.com/minetest/minetest/blob/b298b0339c79db7f5b3873e73ff9ea0130f05a8a/src/client/inputhandler.cpp#L78-L81
https://github.com/minetest/minetest/blob/5f1cd555cd9d1c64426e173b30b5b792d211c835/src/client/game.cpp#L2004-L2012
(thanks goes to @kkabrams for finding these)

Anyway, I'd like to request that this be raised to 32 in both 0.4.x and 5.0.0.

@kahrl you set this value several years ago, with commit 96fe1de83.

**Comment by cheapie** [comment]
I could easily fit more than 32 slots on my screen with a sane HUD scaling value (the default is not sane), but seeing as how 32 is normally the inventory size anyway, even a 32-slot hotbar would be a step in the right direction.

**Comment by VanessaE** [comment]
pull request for this, https://github.com/minetest/minetest/pull/7916

**Comment by VanessaE** [comment]
(move any discussion to that one)

**Comment by VanessaE** [comment]
fair enough
