### ISSUE TITLE
Stars are rendered below horizon

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7920]
![screenshot_20181201_042216](https://user-images.githubusercontent.com/3686677/49324520-0880f980-f527-11e8-9d2d-d9d27de20917.png)

Quite often the player is high up and much of the terrain below is not loaded.

**Comment by random-geek** [comment]
This would look bad in certain contexts, e.g. skyblocks. If this get implemented, I would at least suggest putting the invisible barrier somewhat below the horizon. That way, the disappearing stars would be less noticeable on the ground.

**Comment by paramat** [comment]
Indeed space games that remove clouds would also suffer, it's probably best as an option.
This is not a big issue as the loaded ground usually covers these stars.
I certaily disagree with using an incorrect horizon.
So low priority.

**Comment by paramat** [comment]
![screenshot_20181202_062332](https://user-images.githubusercontent.com/3686677/49336493-261f9300-f5fb-11e8-804a-c9926b5e0ae2.png)
 Testing with more and larger stars, it turns out stars are already hidden below E and W horizons, and this is unavoidable because horizon must be in front of moon, and moon must be in front of stars. This just wasn't very obvious with a smaller number of smaller stars, but looking at the screenshot in the first post above, a dark rectangle is visible on the left.

Because this is already half done i suggest doing it completely and perhaps adding a clientside (for now).

**Comment by paramat** [comment]
PR #7932
