### ISSUE TITLE
Content Store: Missing package short descriptions

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#7923]
##### Issue type

 - Bug report
 
##### Minetest version

```
5.0.0-dev-327bad2e-dirty
```

##### Summary

I'm on the latest commit at the time of writing; package short descriptions are missing from both the content store and the individual package dialogs.

![screenshot](https://user-images.githubusercontent.com/36130650/49329718-69511600-f5a9-11e8-95a5-5f5afca8391b.png)

I have even re-cloned a brand new MT to check if the issue is on my side. I'm afraid the issue persists.

**Comment by rubenwardy** [comment]
The API has changed, fixed by #7891

**Comment by ClobberXD** [comment]
Then I suggest keeping this issue open until #7891 has been merged.

**Comment by pauloue** [comment]
#7891 is merged.

**Comment by rubenwardy** [comment]
This shouldn't have been reopened, this wasn't a bug or issue
