### ISSUE TITLE
meshoptions for plantlike_rooted?

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7937]
##### Issue type

 - Feature request
 - Question
 
##### Minetest version

```
0.5.0
```

Just to avoid this in kelp
![screenshot_20181203_211440](https://user-images.githubusercontent.com/33675971/49420472-794f2e00-f740-11e8-870f-0c4d09552e14.png)
NOTE: This is a custom kelp texture

**Comment by paramat** [comment]
No it isn't. I don't think it's important enough to be justified with seeing as 'rooted' is only used underwater :-1:

**Comment by paramat** [comment]
Are you requesting just random offset or all meshoption features?

**Comment by Extex101** [comment]
Sorry for the extra long delay XD I only just saw your comment

Yes it's for all meshoptions

**Comment by paramat** [comment]
Some 'meshoptions' features might be possible but not all.
As with 'plantlike', i do not see the problem of aligned decorations. It is a cubic voxel world where everything is aligned with a grid, but users do not complain about the cubes being aligned =)
However, some of the meshoption features might be a good idea.

**Comment by benrob0329** [comment]
Non-cubic nodes can look ugly when in a grid, its not at all the same visually as plantlike or plantlike_rooted. A little variance goes a long ways to make things more visually interesting, for most games anyways.
