### ISSUE TITLE
Player join confirmation shows incorrect formatted string

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#7948]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-327bad2-327bad2-dirty (Windows)
```

##### OS / Hardware

Operating system: Windows 10

##### Summary
![image](https://user-images.githubusercontent.com/35757396/49663226-d67a0680-fa02-11e8-896d-45e760f6265d.png)

When using the daily development build from [nrz's daily Windows development builds](https://gitlab.com/minetest/minetest/pipelines), the join confirmation formspec does not show the server and player name as it should. Presumably the issue is from [here](https://github.com/minetest/minetest/blob/master/src/gui/guiConfirmRegistration.cpp#L97).

##### Steps to reproduce

Get one of nrz's daily Windows builds. Then try to join a server.

**Comment by sfan5** [comment]
This issue (broken snprintf on mingw) should've been fixed as of 9537cfd3f8264700619f58d15741829489e1099e.

**Comment by paramat** [comment]
Not sure if a blocker or not.

**Comment by pgimeno** [comment]
Relevant snippet:

https://github.com/minetest/minetest/blob/0ad96cc73f5498cf4ffe85afe1478066acfd377a/src/porting.cpp#L678-L687

**Comment by paramat** [comment]
Also affects windows 7, msys2 according to #8257

**Comment by paramat** [comment]
Ok so perhaps we try using `%s` instead.

**Comment by paramat** [comment]
These strings aren't needed in the confirmation, it's going to be reworked after release anyway, so, let's just remove the strings.

**Comment by paramat** [comment]
PR #8258

**Comment by paramat** [comment]
Removing from blockers.
IRC http://irc.minetest.net/minetest-dev/2019-02-19#i_5498408

> 19:36 sfan5      this issue does not affect the official windows builds

**Comment by paramat** [comment]
Reopen as #8258 needs to be merged to 5.0.1 too.
