### ISSUE TITLE
Apply sneak speed only when touching ground

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#7951]
##### Issue type
 - Feature request
 
Basically what the title says ^

EDIT by SmallJoker: This request is about to only apply the sneak speed when touching ground.

**Comment by paramat** [comment]
? It's not obvious at all.

**Comment by ClobberXD** [comment]
Basically the title isn't understandable. Would you please be able to explain, @Extex101?

**Comment by paramat** [comment]
Are you using new or old movement code?

**Comment by Extex101** [comment]
Make it so sneaking in the air doesn't slow you down

**Comment by Extex101** [comment]
But still catches on edges

**Comment by jastevenson303** [comment]
>Make it so sneaking in the air doesn't slow you down

Ohhh, yes, I know what he means.  IMHO if implemented, should be an option, as one may prefer at times to air brake.  :)

**Comment by paramat** [comment]
Ok i see, sneaking while being in mid-air during a jump slows you down.

**Comment by jastevenson303** [comment]
(@Extex101 in case you're interested: I usually only ever tap (not hold) sneak when jumping off the side of a node, or just about to land onto (catch) it.  If you do a quick tap on jump/land and make sure not to hold it down, you shouldn't lose much speed.)

**Comment by Ezhh** [comment]
Please no.  Much better to be able to release or hold the key to have the option of which speed you want.

**Comment by SmallJoker** [comment]
If this is applied, then also X/Z movement by keys should be changed to have less of an impact as if you're standing on a node. Air additionally would also allow to accelerate up to - say 10 m/s - since it's not bound to the walk speed limit.
However, this breaks the gameplay and would cause yet another long sneak/movement discussion.

**Comment by paramat** [comment]
:-1:
