### ISSUE TITLE
Minetest 0.5 on Android uses Z-fog

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#7959]
A while ago I change Minetest to use Range-Fog everywhere.

I just checked @stujones11 latest build on Android, and it's using Z-fog there.
You can see that clearly when you look at the sides of the screen, where the fog seems to be further away and hence you can see partially loaded maps.

Might be an Irrlicht thing, or some config that needs to be enabled for Android. I checked the code in question (game.cpp) and it does nothing special for Android when it comes to the fog.

The Irrlicht documentation points out of that some platforms do not support range fog.

Also the shaders are not available.

Perhaps both is by design, but I thought I'd at least mention it here.

**Comment by paramat** [comment]
I guess low priority for fog type.

Shaders not usable is known yes, there is a PR for making shaders usable on Android.

**Comment by lhofhansl** [comment]
@stujones11  <ping> :)

**Comment by stujones11** [comment]
@lhofhansl Sorry for the wait, here is a build with the pixel fog set true as you suggest https://www.dropbox.com/s/1wqcbapfl60nj8n/Minetest-sneak-dig.apk?dl=0

It's based off my last forum release as current head is failing to build :(

I personally can't tell any difference but ymmv, at least I can see no ill effect from this.

**Comment by lhofhansl** [comment]
Yeah. Makes no difference, sadly. I guess Irrlicht just doesn't support range fog on Android.

You can see the effect by looking something head on that is just far enough to disappear in the fog. Then turn left or right and see that part appear again in the periphery.

Oh well. Was worth giving it a try. Thanks for the built!

**Comment by stujones11** [comment]
@lhofhansl you're welcome, it was certainly worth a try. Maybe when we do eventually get the shaders working there can be nicer fog with ogles2 drivers :)
