### ISSUE TITLE
Package manager doesn't track content reliably

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#7967]
It gets confused when dirs have the same name - ie: mesecons modpack and mesecons mod, or mobs redo and simple mobs

Solution: track using package IDs instead

**Comment by nerzhul** [comment]
Package ID for folder name, or better a package.json like file can the right solution to solve a such issue

**Comment by Wuzzy2** [comment]
Other solution: In the Content DB, force the shortnames to be REALLY unique. Reject mods if the shortname was already taken.
The widespread shortname abuse has to stop. It's not good when wildly different mods share their shortname. There are many, many problems with re-using shortnames, and Content DB is only the tip of the iceberg.

Introducing a “package ID” won't solve all the OTHER problems that arise from the shortname reuse abuse. Also, it would mean that we officially admit that the shortname is useless for identifiacation purposes, and that `depends.txt` cannot be trusted either. I'm not really happy with this solution.

**Comment by DS-Minetest** [comment]
@Wuzzy2 What is about forks? They might need to have the same name to be able to replace it's forked mod at dependencies.
And how should be chosen which mod may use their current name if there are already conflicts? I.e. there are [three nether mods](https://krock-works.uk.to/minetest/modSearch.php?st=0&at=0&q=nether).
And there's a lack of def time to replace the old modname with the new one.

The ID could simply be author..modname..number(0→1→…).

**Comment by rubenwardy** [comment]
There's two options here. The decision between them is related to whether it's a good idea to allow users to be renamed on CDB

* **Option 1:** Use integer package IDs (already done on CDB). Allows the author name to change.
* **Option 2:** Use author/name composite key. Doesn't allow the author name to change.

Option 1 will

* A. allow the username of the ContentDB author to change
* B. allow the package to change authors

without any issues. A username changing with Option 2 would result in the mod never being able to be updated.

A has already occurred a few times on the forums, ie: with tumeninodes. B is arguable really, as it would be better to have package "maintainers" instead of changing the author of a package. There's also the case of being allowed to delete your account

**Comment by paramat** [comment]
See PR #8054

**Comment by rubenwardy** [comment]
That won't support forks

**Comment by paramat** [comment]
IRC:

17:50 rubenwardy #8054 
17:50 rubenwardy A decision needs to be made here
17:50 rubenwardy is it better to do something easier and technically better?
17:51 rubenwardy or to do something that would allow users to change their usernames on CDB?

18:56 paramat    rubenwardy about #8054 i think 'easier and technically better', changing usernames doesn't seem particularly important, what's your choice?
18:56 rubenwardy yeah, that was my conclusion
18:56 rubenwardy hence the PR
