### ISSUE TITLE
Decrease saturation in dark areas

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#7974]
##### Issue type
 - Feature request

##### Summary
I started experimenting with shaders recently, and found that lowering the saturation of colours in low light areas (at night and in caves) makes the game look a bit more believable. This means dark areas become more muted and light sources appear more prominent. The effect is fairly minor (as you can see), so gameplay would be affected very little.

| Before | After |
| - | - |
| ![before1](https://user-images.githubusercontent.com/35757396/49977754-67b61500-fefc-11e8-8478-7c0fabf8e4ab.png) | ![after1](https://user-images.githubusercontent.com/35757396/49977767-713f7d00-fefc-11e8-8f2e-ac94ed82c878.png) |
| ![before2](https://user-images.githubusercontent.com/35757396/49977831-a9df5680-fefc-11e8-81cb-297205bc6f16.png) | ![after2](https://user-images.githubusercontent.com/35757396/49977842-b5328200-fefc-11e8-97f3-4bfe1e9af063.png) |

This partially mimics how human see colour in real life, since cones in the eye (colour receptors) work better in bright light, with cones (not colour sensitive) working in dark environments. That makes it harder to see colours in the darkness.

The saturation curve I am currently using looks like this:
(x-axis is brightness)

![image](https://user-images.githubusercontent.com/35757396/49977529-88319f80-fefb-11e8-9807-594b7ffd15b4.png)

[Here](https://gist.github.com/random-geek/573c438d424dd7d120e0627f33c63391#file-opengl_fragment-glsl-L198) is the code I'm using (nodes shader only), if anyone is interested in further exploring this concept.

**Comment by paramat** [comment]
But ... this behaviour of the eye is already happening when we look at the dark areas of the screen, so you'd be doing it twice and unnecessarily :-1: It also looks worse to me personally.

**Comment by random-geek** [comment]
I expected that to be the answer anyways, so I'll close this issue if nobody else likes it.

**Comment by jastevenson303** [comment]
:thumbsup:

**Comment by Fixer-007** [comment]
I had to look really good to spot the difference :D

**Comment by random-geek** [comment]
Closing this for now.

**Comment by HybridDog** [comment]
I recently found out that the colour in minetest shaders is not linear but simply 1/255 sRGB. You may need to heed this when changing saturation.
Here are functions to make it linear or the other way round:
```GLSL
vec3 sRGB_to_lin(vec3 sRGB)
{
	return pow(sRGB, vec3(2.2f));
}
vec3 lin_to_sRGB(vec3 lin)
{
	return pow(lin, vec3(1 / 2.2f));
}
```

**Comment by rubenwardy** [comment]
> But ... this behaviour of the eye is already happening when we look at the dark areas of the screen, so you'd be doing it twice and unnecessarily -1 It also looks worse to me personally.

I don't think this is factually correct at all
