### ISSUE TITLE
mod.conf name setting ignored when saving mod configuration from menu

### ISSUE THREAD

**Issue by pgimeno** [minetest/minetest#7980]
As a result, world.mt contains `load_mod_<dirname>` instead of `load_mod_<modname>`. Bug introduced in #7922. Fix is trivial.

```diff
--- a/builtin/mainmenu/pkgmgr.lua
+++ b/builtin/mainmenu/pkgmgr.lua
@@ -25,9 +25,9 @@ function get_mods(path,retval,modpack)
                        local toadd = {}
                        retval[#retval + 1] = toadd
 
-                       local mod_conf = Settings(prefix .. "mod.conf"):to_table()
+                       local mod_conf = Settings(prefix .. DIR_DELIM .. "mod.conf"):to_table()
                        if mod_conf.name then
                                name = mod_conf.name
                        end
 
                        toadd.name = name
```

**Comment by pauloue** [comment]
Yes this is correct. My mistake.
Have you considered using [hub](https://hub.github.com/) to [make pull requests](https://hub.github.com/hub-pull-request.1.html)?

**Comment by SmallJoker** [comment]
7efb407

**Comment by pgimeno** [comment]
@pauloue Off topic, but my intention is to distance myself from MS-GH, not to embrace it, and I'm going to delete my MS-Github account by the end of the year.
