### ISSUE TITLE
minetest.is_day (or minetest.is_night) functions

### ISSUE THREAD

**Issue by runsy** [minetest/minetest#7983]
It would be cool.

from 4500 time of day to 19500, returns 'true', otherwise 'false' (night)

**Comment by runsy** [comment]
Because it would be cool.
'get_timeofday' is the path to get if is day or night, I know. But a function has to be created.

**Comment by paramat** [comment]
Doesn't seem useful because we can already get time, and brightness at time, and mods usually want to define the exact time (or brightness) that divides day from night :-1:

**Comment by rubenwardy** [comment]
> And C++ is faster.

This feature would not be implemented in C++, it would be implemented in Lua in builtin. There would be no speed improvements for this feature

**Comment by runsy** [comment]
> Doesn't seem useful because we can already get time, and brightness at time, and mods usually want to define the exact time (or brightness) that divides day from night -1

Technically the night is (from Wikipedia):

> Night or nighttime (sp. night-time or night time) is the period from sunset to sunrise in each twenty-four hours[1], when the Sun is below the horizon

> Sunrise or sun up is the moment when the upper limb of the Sun appears on the horizon in the morning.

> Sunset or sundown is the daily disappearance of the Sun below the horizon due to Earth's rotation.

So, Minetest night should be (from Minetets Wiki):

> At 4500 tod, the first sun rays emit from the horizon, it gets brighter (2). 

> At 19500 tod, the sun rays stop from being visible (2).

**Comment by paramat** [comment]
That's irrelevant to my argument.

**Comment by sofar** [comment]
The benefit from doing this in C++ is fairly minimal: not needed imho.

**Comment by SmallJoker** [comment]
:-1: There's no need for such a function. You can use `minetest.get_timeofday()` to get the time and `minetest.get_node_light(...)` for the light level. If you still need it, it's a one-liner function
```Lua
local function is_day()
	return minetest.get_timeofday() >= (45 / 240) and minetest.get_timeofday() < (195 / 240)
end
```

**Comment by nerzhul** [comment]
@SmallJoker cache the core call to reduce overhead :)

Maybe adding this call to builtin ? :)

**Comment by HybridDog** [comment]
> Maybe adding this call to builtin ? :)

No, testing for night is usually a workaround for what people want to do, e.g. spawning mobs only at night is often considered the same as spawning mobs when it's dark so that players can't see their spawning.
