### ISSUE TITLE
Install on Elementary 5

### ISSUE THREAD

**Issue by TechnoryGaming** [minetest/minetest#7984]
I actually instaled elementary 5 IN my pc and i need to paly minetest but i dont find the elementary download on the Minetest.net/downloads
help me please

sorry for any misspeling

**Comment by TechnoryGaming** [comment]
sorry i found it on the app store but its 4.16

**Comment by SmallJoker** [comment]
elementary is based on ubontu so u can just try to use the ppa. https://launchpad.net/~minetestdevs/+archive/ubuntu/stable
