### ISSUE TITLE
Mjumble

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#7990]
##### Issue type

 - Bug report
 - Feature request
 - Documentation issue
 - Build issue
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

**Comment by niansa** [comment]
Ooops I clicked too fast.

**Comment by niansa** [comment]
Can someone delete this? lol

**Comment by rubenwardy** [comment]
This can't be delete, just leave it closed
