### ISSUE TITLE
Add Mumble Link support

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#7991]
##### Issue type

 - Feature request

##### Summary

I would Like Mumble Link support. Mumble is a great VOIP software. I supports "positional audio". And I would REALLY like to be able to use positional Audio in Minetest. And YES, I know that has already been discussed and worked on 2 years ago, but it has been given up. Let's give it another try!

**Comment by SmallJoker** [comment]
You can edit the title and your post btw. (reference: #7991)

![Edit options](https://user-images.githubusercontent.com/1497498/50053243-db8d3300-0131-11e9-9601-3682c3d6461d.png)

**Comment by SmallJoker** [comment]
#1753
