### ISSUE TITLE
activitypub account system

### ISSUE THREAD

**Issue by unmellow** [minetest/minetest#7993]
##### Issue type
 - Feature request

##### Summary
what if you had an [activitypub 2.0](https://activitypub.rocks/)  based account system
since the items you have and things of that nature are saved
on the game server, the only thing the account server's have to 
save is your name a skin and possibly a friends list too the way
you would login is using [this standard ](https://hacks.mozilla.org/2018/10/dweb-identity-for-the-decentralized-web-with-indieauth/)

**Comment by nerzhul** [comment]
Sorry but no, we will never use a such decentralized auth which is not compatible with our security model and can obtain some private data => GPDR.
Thanks for the  suggestion anyway.
