### ISSUE TITLE
Attempt at a summary of CSM, as requested (plus possible issues)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#7995]
Until recently, Lua scripting code has run on the server only, being a combination of 'games', 'mods' and the always-run 'builtin' Lua code (in the 'builtin' folder).

Client-side modding allows Lua scripting code to run on the client itself.
The client-side mod code is either provided by the client user 'CPCSM', or sent from the server through the network to be stored and run on the client 'SSCSM' or 'SPCSM'.

There is also 'builtin' client scripting code that the client loads from it's own copy of the 'builtin' folder (from 'builtin/client').
The deathscreen has been moved to 'builtin' from the engine, apparently to make it modifiable. There is also 'register_on_..' callback code and some client-side chatcommands such as 'list_players'.

It will be possible to have 'twinned' mods, one on the server, one on the client, that are designed to work together, they will communicate to each other through network 'mod channels'.

Currently only CPCSM is coded and was released into stable MT in 0.4.16. The security-critical step of sending code from the server to the client is not yet coded.

Server controls
---------------
Some things CSM can do can affect the server. If the code was sent from the server this doesn't matter because the server intended this to happen, but because the client can also provide CSM code 'CSM restrictions' were added to give the server control over what CPCSM can do.

Whatever CSM restrictions are set, the 'builtin' client scripting code is always loaded into the client from 'builtin/client' (PR #8000 changes this).

The server can prevent the client loading any CSMods by using the 'LOAD_CLIENT_MODS' CSM restriction. The current default is that clients are allowed to load CSMods.
This restriction will be useful when SSCSM is completed, for when the server sends CSM mods to the client but doesn't want the client to load it's own CSM mods.

The server can choose which features client scripting cannot use, these are chosen using the remaining CSM restrictions:
```
#    CHAT_MESSAGES: 2 (disable send_chat_message call client-side)
#    READ_ITEMDEFS: 4 (disable get_item_def call client-side)
#    READ_NODEDEFS: 8 (disable get_node_def call client-side)
#    LOOKUP_NODES_LIMIT: 16 (limits get_node call client-side to
#    csm_restriction_noderange)
#    READ_PLAYERINFO: 32 (disable get_player_names call client-side)
```
The radius around the player where 'get_node' can be used (if allowed) can also be set by the server using the 'csm_restriction_noderange' setting.
The current defaults are that these 5 features are disallowed and the node range is set to 0.

Note that additional feature restrictions can be added to these 5 on request, for any client scripting feature servers consider harmful to a server.

When the server sends CSM mods to the client some of these 5 features will often have to be allowed for the server-sent CSM mods to use. However any enabled features will then also be usable by any client-provided CSM mods. Therefore often it will be necessary to disable client mod loading in this situation.

**Comment by paramat** [comment]
This may be edited over time.
As requested in #7949 
@Ezhh 

Writing this it does raise some questions:
* Maybe checking builtin is necessary now? Since builtin is not affected by csm restrictions surely it needs checking. I was told this is only necessary once SSCSM was coded but i'm not sure.
* The checking of builtin seems necessary if any of the csm restrictions are used.

**Comment by paramat** [comment]
Actually, i think i've got it, maybe:
When the server sends code to be used all these will have to be allowed:
```
#    CHAT_MESSAGES: (disable send_chat_message call client-side)
#    READ_ITEMDEFS: (disable get_item_def call client-side)
#    READ_NODEDEFS: (disable get_node_def call client-side)
#    LOOKUP_NODES_LIMIT: (limits get_node call client-side to
#    csm_restriction_noderange)
```
So that the server-sent code can use them. This means client-provided code can use them also.
But then, isn't that a way around csm restrictions?

**Comment by paramat** [comment]
I need to think further on these, however. some things that possibly need doing:
* A CSM restriction exists ('LOAD_CLIENT_MODS' ) that stops a client loading CSMods, this is for servers that want to stop a client using any CSM code, whether it is generally considered harmful or not.
However this restriction does not stop the client loading the 'builtin' CSM code, and it's easy to add CSM code to builtin, and builtin is not yet checked for such added code.
So for 5.0.0 we need an additional CSM restriction that stops a client loading builtin (i can code this).
This restriction might actually stop the client Lua environment being created (not sure yet, this might need to be a separate CSM restriction).
* The triggering of the builtin check (currently an empty function) is possibly in the wrong place, i need to check this (again i can code this).

**Comment by nerzhul** [comment]
@paramat as the restriction declaration & transport is easy, unlinking the lua stack is not easy and can be tricky.
I think this restriction is the most reasonable solution to unlock this conflict. You cannot bypass restrictions except with a rogue client, and it's like unlock the client to re-enable a hardcoded boolean.

**Comment by BluebirdGreycoat** [comment]
> it is necessary to check that the client user has not added code
into 'builtin/client' because that is always loaded.

> This check has not yet been coded, but apparently (i still find it complex to
understand) will only be needed once SSCSM is completed (however i'm beginning
to think it may also be needed now, i'm not sure.

I'm sure the check is needed regardless of the state of SSCSM. Don't see why the state of SSCSM would have anything to do with it at all.

> There are some 'verify builtin' issues on GitHub discussing this, coding this
check is somewhat dreaded.

Not sure why (though I haven't read the related issues). I don't see why performing an integrity check of client-side/builtin is particularly hard.

A rouge user can always strip out whatever checking code anyone writes, no matter how complex, and fake the integrity check.

Given the above, a simple method is better than a complex one: simply load all the files and make sure their checksums match a hardcoded checksum in the client.

Yes, that can be hacked. No, making the check more complex will not increase the overall security. So I'd say, don't bother.

**Comment by paramat** [comment]
PR #8000

**Comment by sorcerykid** [comment]
Thanks @paramat, great summary!

I haven't looked through the entire client-scripting API, but isn't there a function that allows for iterating over the player list? Is there a way to disable that function? On my server, it's possible for players to got incognito. I'm concerned that with a client-side mod, an end-user could easily override this.

**Comment by paramat** [comment]
There's a client-side chatcommand in 'builtin' that lists players https://github.com/minetest/minetest/blob/d994f7ca5f75431da8e17fd6762209c404d89482/builtin/client/chatcommands.lua#L40
There's no CSM restriction for this currently but we will add one on request.

**Comment by nerzhul** [comment]
I push a PR asap for this need

**Comment by nerzhul** [comment]
See #8007

**Comment by sorcerykid** [comment]
Wow thanks @nerzhul! That is great news. And thanks @paramat for the explanation.

**Comment by paramat** [comment]
> (no need to restrict playerinfo by default)

All restricted features (and therefore potentially harmful) are disabled by default.

**Comment by paramat** [comment]
No need for this to be open, but still useful for reference.
