### ISSUE TITLE
Arabic chars on chat and/or console

### ISSUE THREAD

**Issue by AbdouAbdou31** [minetest/minetest#7997]
##### Issue type

 - Feature request

##### Minetest version

```
0.4.17.1
```

##### OS / Hardware

Operating system: Windows 7 Professionnel
CPU: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz 3.00 GHz

GPU model:
OpenGL version:

##### Summary

It's for arabic characters on the chat.
When we type arabic characters, we see nothing. 
It would be great to add this. Thanks.

**Comment by SmallJoker** [comment]
Cannot fix. Duplicate of #302
