### ISSUE TITLE
'Soft' feature freeze for 5.0.0

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8001]
I'm opening an issue because the team discussion on this is easily missed.

Although we can't start an official feature freeze, i agree with nerzhul that we should start a 'soft' feature freeze in order to avoid adding bugs created by merging non-trivial PRs that are unnecessary for 5.0.0.
I feel we should focus now on the work necessary for 5.0.0. There's quite a lot, especially Android bugs and the issues of 3D rotation.
The blockers are viewable here https://github.com/minetest/minetest/projects/4

Any comments or agreements?
(Core devs: please don't use emoticons to agree as the list of users becomes incomplete after a certain number).

**Comment by nerzhul** [comment]
I'm against soft. Please start hard feature freeze fixing the points we need. Some features in the list can be delayed to a 5.1.0

**Comment by paramat** [comment]
Closing this because it's not really needed, also, we have different interpretations of 'feature freeze'.
