### ISSUE TITLE
Server Provided Client Mods: Required features

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#8002]
##### Issue type

 - Feature request
 
##### Minetest version

```
5.1.0-dev
```

##### Summary

Idea is to collect the SPCM required features

##### Collected interesting features

* [ ] Transport mods serialized and packages across network to be loaded by the client
* [ ] Feature level (Optional, Recommended, Required): this permits client to control which SPCM feature he wants to enable or not on its client
* [ ] Mods signature (requires contentdb + curl/openssl by default)

##### Moderation on this topic

Only discussion about features to implement to have the minimum SPCM are allowed here. Politics or non constructive comments will be dropped.

**Comment by paramat** [comment]
>  i think SSCSM should have restrictions from client side too. If a client doesn't want server to use some API it should have the freedom to do it.

>  this permits client to control which SPCM feature he wants to enable or not on its client

I suspect this is not a good idea. If a client picks and chooses which parts of a server-sent mod functions, that mod will either be broken or incomplete.
So i think accepting SSCSM is an all-or-nothing thing. A client could still be allowed on a server (that's up to the server to decide) but it should either completely refuse SSCSM or let all of it function.

**Comment by paramat** [comment]
Is this issue needed when we already have #7043 ?

**Comment by nerzhul** [comment]
@paramat having feature levels permit server owners to expose themselves those levels and client to use only level they want. 3 levels seems fair (required, intermediate, full).
If server owners doesn't want to use it they don't expose it

**Comment by nerzhul** [comment]
@paramat having feature levels permit server owners to expose themselves those levels and client to use only level they want. 3 levels seems fair (required, intermediate, full).
If server owners doesn't want to use it they don't expose it

**Comment by nerzhul** [comment]
exact it's dup, i return back to previous

**Comment by paramat** [comment]
I think i confused 2 different ideas. I mean each server-sent mod should function completely, never partly.

**Comment by paramat** [comment]
However also, allowing some sscsm mods to run and not others is also likely to be a mess, so i don't support that either.

**Comment by raymoo** [comment]
Mods could specify certain features to be required, and disabling them could result in the client aborting connection. Mods shouldn't rely on client code being executed security-wise, since a modded client could silently disable CSM, so maybe it's even ok to give the client a "connect anyway" button.
