### ISSUE TITLE
Expose metrics for prometheus

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#8004]
##### Issue type

 - Feature request
 
##### Minetest version

```
5.0.0-dev
```

##### OS / Hardware

Operating system: ArchLinux
CPU: AMD FX8350

GPU model: Radeon RX580
OpenGL version: 4.6

##### Summary

Currently we have embedded metrics. Add a prometheus exporter in minetest to read those metrics.
This can need some refactor on the current metric model but it can be very nice to servers owners to graph lua memory size, connected players, and various other metrics embedded inside code.

##### Metrics useful to expose

Here are interesting metrics we can expose (please push more metrics you want, i will complete)

* [ ] lua memory size
* [ ] mapblocks loaded
* [ ] connected players
* [ ] custom (for Lua mods, if possible)

**Comment by rubenwardy** [comment]
This requires Minetest running a HTTP server privately. There are Prometheus libraries for this.

Integrating this in the engine would allow better exposing of internal stats.
An alternative would be to add a `minetest.get_stats()` method to retrieval those stats

I would personally find this very useful

Other useful stats:

* mapblocks in flight
* number of unack-ed packets
* ...

**Comment by nerzhul** [comment]
we have many internal metrics which can be refactored to create a generic backend and make an exported read it :)

**Comment by thomasrudin** [comment]
Library-candidate: https://github.com/jupp0r/prometheus-cpp
I may to try to whip up a PR if 5.0 is stable...

**Comment by nerzhul** [comment]
@thomasrudin take your timei the 5.0.0 roadmap is closed to new features. We are polishing the remaining in-dev features and we will trigger the freeze.

**Comment by rubenwardy** [comment]
This branch adds a generic API for stats: https://github.com/rubenwardy/minetest/tree/get_stats

However, it obviously doesn't have any of the backend needed for a more complex stats method.

```lua
local stats = minetest.get_stats()
stats = {
    uptime = 124,
    max_lag = 0.2345,
}
```

**Comment by thomasrudin** [comment]
I started developing a solution for the prometheus monitoring.
Can you tell me if i'm on the right track?
(don't worry, i will refactor/squash the commits)

## monitoring.h
* Generic classes for registering gauges/counters and histograms
* https://github.com/thomasrudin-mt/minetest/blob/prometheus-wip/src/monitoring.h

## monitoring.cpp
* concrete prometheus implementation and No-Op fallback
* https://github.com/thomasrudin-mt/minetest/blob/prometheus-wip/src/monitoring.cpp

The idea is, that if the prometheus-cpp library is not available there will be a No-Op monitoring implementation. That way you don't need all those #`if #endif` macros cluttered all over the code.

## Example:

https://github.com/thomasrudin-mt/minetest/blob/prometheus-wip/src/server.cpp#L410
```cpp
m_tick_count_metric = g_monitoring->createCounter(
		"minetest_engine_tick_count",
		"The server tick count"
);
```

## TODO
* Proper lifecycle management (with server start/stop)
* Proper CMake placement
* Code style/conventions
* Lua implementation (minetest_engine_* and minetest_mod_* namespace)
* Documentation
