### ISSUE TITLE
Minetest 0.4.17.3 (android only)

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#8012]
##### Issue type

 - Build issue
 
##### Minetest version

```
0.4.17.1-2
```

##### Summary

We should unlock some Android issues before 5.0.0 on Android.
Please reference backportable commits to push to Android, if i remember there is two or three commits to push

* [x] #6971 e87b410a33639bffe69725ed3ea5d85e45280815
* [x] Fix memory leak when displaying images in the mainmenu (#8011) https://github.com/minetest/minetest/commit/0990ddb3bb96ab2e4c7a1ee44ed79c4218477949 
* [x] #7820 f70f7875e2a2e49f80470832ae97e73f171d6460 
* [x] #8003 b8b33a6423ad3d0ac1d701b91099e3a70e4f6197

Idea is to push those commits to the stable-0.4 branch and release before Christmas with the commits embedded

cc @paramat @stujones11 @DS-Minetest @SmallJoker 

release APK: https://github.com/minetest/minetest/releases/download/0.4.17.1/Minetest-0.4.17.3.apk

**Comment by stujones11** [comment]
@nerzhul You will definitely need (#7820) f70f7875e2a2e49f80470832ae97e73f171d6460 in order to make a playstore release, followed by #8003 to make it work with Android 4.x. Some of the gui fixes would be nice but I guess we have to draw a line somewhere.

@ClobberXD The memory leak effected all mainmenu images, it was only more noticeable with the content db. (if I understand it correctly)

**Comment by SmallJoker** [comment]
If it's broken I don't see a reason to _not_ push these commits and bump the Android version.

**Comment by stujones11** [comment]
Note that 0.4.17.x will still contain this bug #6432 however, backporting the fix (#7482) would be no trivial matter. Instead, I suggest we simply disable that menu for this release.

**Comment by ClobberXD** [comment]
> The memory leak effected all mainmenu images, it was only more noticeable with the content db. (if I understand it correctly)

Ah, I see... It probably also affects game banners, icons, and the background then. Thanks for clarifying. :)

**Comment by nerzhul** [comment]
Starting to backport changes

**Comment by stujones11** [comment]
@nerzhul from what I can see #6971 e87b410 is not yet backported. I don't think ogles2 is massively important but it is only a +7 line commit ;)

Most importantly, please be sure to build all the libs in **release** mode!

**Comment by nerzhul** [comment]
yeah it's a mismatch, i hope we can do proper versioning model in the next 5.x.y branch :)

**Comment by stujones11** [comment]
@nerzhul I have noticed that the binaries in the latest apk do not match the current `stable-0.4` branch. The mainfest also still has the version as `0.4.17.20` when I profile it with android studio.

I have also noticed that the libs would still seem to be built in debug mode, judging by their file sizes.

Note that .apk files are simply archives that anyone can extract and compare with those from my own (release-mode) builds.

You really need to get this sorted out quick if you want to update the playstore before Christmas. I would like to see this as there may be a lot of potential new users.

**Comment by IhrFussel** [comment]
You NEED to somehow backport the GUI scaling issues.

Not being able to use the advanced settings menu is in itself a BUG.

**Comment by Wuzzy2** [comment]
About Android version number: Why using a dash, instead of a point?
The dash WILL confuse popular package managers and also is a bit uglier to read.

I.e. instead of 0.4.17.1-3, use 0.4.17.1.3.

So if I understood correctly, the scheme is:

ULTRA.MAJOR.MINOR.PATCH.ANDROID

**Comment by nerzhul** [comment]
you don't have to be a package manager to use the apk, there is no package manager here :) it's a android release build

**Comment by Wuzzy2** [comment]
That still doesn't answer my question. :P

**Comment by paramat** [comment]
> You NEED to somehow backport the GUI scaling fixes.

All bugfixes will eventually be backported to 0.4.x, and the improvements to HUD/GUI scaling should be. The idea here was a quick update and app fix, backporting takes time, so i'm fine with not backporting everything right now.
The more important issue is fixing the invalid enum thing to get the app back to where it was before it was broken.
> About Android version number: Why using a dash, instead of a point?

I totally agree, that was a mistake, i was following the currently used versioning, i'll edit my suggested rules.

**Comment by nerzhul** [comment]
@paramat yes we need but i miss time to do the proper backport. As the branch has already some fixes which works, i prefer to generate an apk with those fixes and do another with the remaining fixes later.

**Comment by nerzhul** [comment]
Release APK provided here: https://github.com/minetest/minetest/releases/download/0.4.17.1/Minetest-0.4.17.3.apk can the major problematic users test it please ?

**Comment by nerzhul** [comment]
The release on the play store has been done

**Comment by paramat** [comment]
Good thanks, but please don't  call it 0.4.17.3, i've been dealing with all the confusion caused by the use of '0.4.17.2' or '0.4.17.3'.
