### ISSUE TITLE
Browse online content: package does not update

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#8018]
##### Issue type

 - Bug report
 
##### Minetest version

```
5.0.0 a5197eae
```

##### OS / Hardware

Operating system: Windows 7 sp1
CPU: Intel i5

##### Summary
Package is not update when pressing Update button in "Browse online content" -> https://i.imgur.com/PmOoMup.png Nothing happens, but if I go into package descr via View and press Update there it updates from there.

**Comment by ClobberXD** [comment]
Probably a regression caused by 657a3d1? See https://github.com/minetest/minetest/commit/657a3d1e0527a12a6e22e1f7eda0f5271cbeb917#diff-f52a94569d13d2345fbfb0450c1d4f4fR415

**Comment by paramat** [comment]
@rubenwardy

**Comment by rubenwardy** [comment]
This may be fixed by the deprecate modpack.txt pr

**Comment by rubenwardy** [comment]
This was fixed by a trivial fix I pushed
