### ISSUE TITLE
on_place of the wielded item is not called when node contains a formspec

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#8024]
##### Issue type
 - Bug report
 
##### Minetest version
0.5

##### Summary
Is almost same as #6195.
If you rightlick a node with a formspec in it's meta, on_place of the wielded item is not called except you sneak.

##### Steps to reproduce
Rightlick for example a technic chest with a [advanced skeleton](https://forum.minetest.net/viewtopic.php?f=9&t=21609) key.

**Comment by SmallJoker** [comment]
Not an issue. You only place nodes on top of those with meta-defined formspecs by using shift-click. Same for items. on_place should not be called for those.

**Comment by Lejo1** [comment]
But how is it then possible to call a function of a item when rightclicking a node with a meta defined formspec?

**Comment by SmallJoker** [comment]
Same as with nodes: Shift-click.
