### ISSUE TITLE
Can't compile for android by using doc/README.android

### ISSUE THREAD

**Issue by cddepppp256** [minetest/minetest#8025]
##### Issue type
 - Build issue
 
##### Minetest version
```
5.0.0-dev
```

##### OS / Hardware
Operating system: Compile on Linux Mint 19.1
CPU: Intel(R) Pentium(R) CPU  N3540  @ 2.16GHz

##### Summary
I can't build the android build by following the directions in doc/README.android

##### Steps to reproduce
Follow the steps for compiling, using the `r9d` NDK and Android 4.4 SDK from Android Studio's SDK manager.

**Comment by stujones11** [comment]
The docs are a bit out of date, you will need to use ndk-r17c and likely a more up-to-date sdk.

**Comment by cddepppp256** [comment]
Ok, what SDK? (or I could just jump around and try them all if you want me to)

**Comment by cddepppp256** [comment]
Well, that might explain why my android 5.1 tablet won't install it. Thanks! (I will still build though)

**Comment by stujones11** [comment]
> Well, that might explain why my android 5.1 tablet won't install it.

If you mean the current play-store version then there is some hope for you. That version contains many bugs and was not correctly built. Try one of my builds if you have no luck building your own.

**Comment by cddepppp256** [comment]
You mean the one that ends in 0.4.17.1-3? That does not work either.

**Comment by stujones11** [comment]
> That does not work either.

None of the official builds are working properly beyond 0.4.16 (iirc)

My builds are available here: https://forum.minetest.net/viewtopic.php?f=42&t=21526

**Comment by cddepppp256** [comment]
Ok, that worked.

**Comment by stujones11** [comment]
Thanks, although the documentation is still in need of updating.
