### ISSUE TITLE
Allow formspecs to optionally specify the element to be focused

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8029]
##### Issue type

 - Feature request

##### Summary

Currently, the first element of a formspec is highlighted, but sometimes the first element to be defined isn't the primary element. I suggest allowing formspecs to optionally specify the field to be focused.

e.g.
```lua
minetest.show_formspec(name, "test", [[
	size[6,7]
	field[4,1.25;2,1;secondary;Secondary;]
	button_exit[1,1;2,1;primary;Primary]
	set_focus[primary]
]])
```

**Comment by paramat** [comment]
@rubenwardy or anyone support? Seems like a request that will be supported, but no-one has expressed support.

**Comment by rubenwardy** [comment]
Yeah, this would be a good feature
