### ISSUE TITLE
Formspec textarea - segmentation fault

### ISSUE THREAD

**Issue by pyrollo** [minetest/minetest#8031]
##### Issue type
 - Bug report
 
##### Minetest version
0.4.17.1 (Fedora 29 supplied package)
5.0.0-dev (commit badecfa47106954656bb34994433730e4ea3714c compiled from source)

##### OS / Hardware
Operating system: Linux - Fedora 29 / Linux - Ubuntu 18.04
CPU:Intel Core I5

##### Summary
Multiple issues using up and down keys in formspec textarea when the last line contains a word larger than the textarea.

##### Steps to reproduce
1 - Create a word using minetest_game. 
2 - Get a book and use it. This will open a form with a textarea.
3 - In the text area, type a word (with no space before) larger than the text area (for example repeat the same letter).
**Issue 1**: An unwanted empty line appears above the long word
4 - Press "up arrow"
**Issue 2**: Segmentation fault
5 - Restart 1,2, before typing the long text, type a short first line, then again, a long word filling the second line (an empty line appears between the two lines)
6 - Press "up arrow", cursor goes to first line as excpected
7 - Press "down arrow"
**Issue 3**: cursor does not go to last line and stays in first line.

The problem is not linked to the book, I had the same issue in many textareas.

**Comment by HybridDog** [comment]
It happens for me too.

**Comment by SmallJoker** [comment]
```C++
Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x0000555555cf0794 in irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> >::c_str (this=0x556d5b4214c8)
    at /usr/include/irrlicht/irrString.h:497
497                     return array;
(gdb) bt
#0  0x0000555555cf0794 in irr::core::string<wchar_t, irr::core::irrAllocator<wchar_t> >::c_str (this=0x556d5b4214c8)
    at /usr/include/irrlicht/irrString.h:497
#1  0x0000555555d4ded7 in irr::gui::intlGUIEditBox::setTextRect (this=0x7fffb80109e0, line=-1)
    at /data/Minetest/minetest/src/gui/intlGUIEditBox.cpp:1269
#2  0x0000555555d4e676 in irr::gui::intlGUIEditBox::calculateScrollPos (this=0x7fffb80109e0)
    at /data/Minetest/minetest/src/gui/intlGUIEditBox.cpp:1392
#3  0x0000555555d4ba8e in irr::gui::intlGUIEditBox::processKey (this=0x7fffb80109e0, event=...)
    at /data/Minetest/minetest/src/gui/intlGUIEditBox.cpp:750
#4  0x0000555555d49e1c in irr::gui::intlGUIEditBox::OnEvent (this=0x7fffb80109e0, event=...)
    at /data/Minetest/minetest/src/gui/intlGUIEditBox.cpp:287
#5  0x00007ffff76626ce in irr::gui::CGUIEnvironment::postEventFromUser(irr::SEvent const&) ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#6  0x00007ffff76239a7 in irr::CIrrDeviceStub::postEventFromUser(irr::SEvent const&) ()
   from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#7  0x00007ffff7618435 in irr::CIrrDeviceLinux::run() () from /usr/lib/x86_64-linux-gnu/libIrrlicht.so.1.8
#8  0x0000555555bb2d72 in RenderingEngine::run () at /data/Minetest/minetest/src/client/renderingengine.h:136
#9  0x0000555555bfec48 in Game::run (this=0x7fffffffd360) at /data/Minetest/minetest/src/client/game.cpp:1075
#10 0x0000555555c12c07 in the_game (kill=0x555556624e60 <porting::g_killed>, random_input=false, input=0x555556a15d20, 
    map_dir="/data/Minetest/run/bin/../worlds/mtg", playername="singleplayer", password="", address="", port=64773, error_message="", 
    chat_backend=..., reconnect_requested=0x7fffffffd5fc, gamespec=..., simple_singleplayer_mode=true)
    at /data/Minetest/minetest/src/client/game.cpp:4217
#11 0x0000555555baec37 in ClientLauncher::run (this=0x7fffffffdb70, game_params=..., cmd_args=...)
    at /data/Minetest/minetest/src/client/clientlauncher.cpp:259
#12 0x0000555555fba7e5 in main (argc=1, argv=0x7fffffffdee8) at /data/Minetest/minetest/src/main.cpp:212
```

**Comment by nerzhul** [comment]
nice it's on the run loop when doing rendering... i think the text is wrong, i take the issue

**Comment by nerzhul** [comment]
the problems seem to be in irrlicht it self
![capture d ecran de 2019-01-22 22-29-05](https://user-images.githubusercontent.com/119752/51566637-6120a300-1e95-11e9-8dc8-46d1fdcd77a9.png)
cursor pos is -1 which is invalid

**Comment by v-rob** [comment]
Still happens.

**Comment by Zughy** [comment]
5.7, Cannot reproduce (I've also tried with a different formspec)
