### ISSUE TITLE
In formspecs dropdown lists drop down behind other elements

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8036]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 0.4.17.1 (Linux)
Using Irrlicht 1.8.4
Build info: VER=0.4.17.1 BUILD_TYPE=Release RUN_IN_PLACE=0 USE_GETTEXT=1 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=1 STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: Linux 4.19.12-arch1-1-ARCH x86_64
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

GPU model: NVIDIA Corporation GP104 [GeForce GTX 1080] (rev a1)
OpenGL version: 4.6.0 NVIDIA 415.2

##### Summary
When creating formspecs with dropdown lists the drop-down drops down behind other elements as shown here:

![2018-12-31-021705_790x510_scrot](https://user-images.githubusercontent.com/46120351/50553200-2e262d80-0ca2-11e9-8d51-e3b44849cc60.png)

According to [the forum discussion](https://forum.minetest.net/viewtopic.php?t=21691) this seems to be a bug in how formspecs are created (mixed Irrlicht and custom elements).

##### Steps to reproduce
1. Install this minimal working example as mod.
    
    ~~~~
    minetest.register_node('test:test', {
        description = 'Test Node',
        tiles = { 'default_wood.png^[colorize:#ffff0055' },
        groups = { oddly_breakable_by_hand = 1 },
        after_place_node = function(pos, placer)
            local meta = minetest.get_meta(pos)
            meta:set_string('formspec', [[
            size[8,5]
            list[current_player;main;0,1;8,4;]
            dropdown[0,0;8;category;Item 1,Item 2,Item 3,Item 4,Item 5;1]
            ]])
        end,
    })
    ~~~~
2. Enable the mod and start a world
3. From creative inventory search `Test Node` and place it
4. Rightclick it to open the meta formspec
5. Use the drop-down

**Comment by Wuzzy2** [comment]
Can also be very easily tested in Minimal Development Test. Just use `/formspec` and select the “Real Coord” tab and open the dropdowns.
