### ISSUE TITLE
Entity attached to player is only visible in third person camera modes (actually a request, not a bug)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8038]
Tested in singleplayer at commit a5197eaebc61ac6b555a640f36c0b427faef381d

Test code spawns then attaches an entity to the player a few seconds after entering a world.
Before attachment the entity is visible at the player's feet. After attachment only visible in the 2 third-person camera modes.
The below screenshots are the 3 camera modes.

![screenshot_20181231_071932](https://user-images.githubusercontent.com/3686677/50556145-3051b180-0ccd-11e9-98c6-c06ac8fba178.png)

![screenshot_20181231_071924](https://user-images.githubusercontent.com/3686677/50556146-33e53880-0ccd-11e9-95f0-9e0f73ca57d6.png)

![screenshot_20181231_071929](https://user-images.githubusercontent.com/3686677/50556147-3778bf80-0ccd-11e9-8875-c39656cabb78.png)

```
minetest.register_entity("lab:cube", {
	initial_properties = {
		physical = true,
		collide_with_objects = true,
		collisionbox = {-1, -1, -1, 1, 1, 1},
		selectionbox = {-1, -1, -1, 1, 1, 1},
		visual = "cube",
		textures = {
			"no_texture.png",
			"no_texture.png",
			"no_texture.png",
			"no_texture.png",
			"no_texture.png",
			"no_texture.png",
		},
		pointable = true,
	},
})

minetest.after(5, function()
	local pos = minetest.get_player_by_name("singleplayer"):get_pos()
	local ent1 = minetest.add_entity(pos, "lab:cube")
	minetest.after(1, function()
		ent1:set_attach(minetest.get_player_by_name("singleplayer"), "",
			{x = 0, y = 10, z = 20}, {x = 0, y = 0, z = 0})
	end)
end)
```

**Comment by jastevenson303** [comment]
Do it with a chat command.  There are some peculiarities you haven't outlined, in regards to triggering the attachment while in third person compared to triggering it while in the first person perspective.

**Comment by paramat** [comment]
The attachments occurred in normal camera mode.

I vaguely remember something about this being known, or intentional, i don't know why it would be expected or desirable.
> not seeing objects that were attached while in third-person view

That's not the case here.
>  the player model is not even rendered on the client in first-person.

Aha that may be it.

**Comment by v-rob** [comment]
I hope someone can add this as a feature, maybe a `object:set_visible_in_first_person(<bool>)` or as an extra parameter to `object:set_attach`.  I don't think the existing behavior should be changed because mods like `wield3d` require it to work this way.  I do think the feature is necessary since there is not way to emulate the suggested behavior by other means than `set_pos` or `move_to`, both of which are jerky and not nearly ideal.  I would implement this myself, but I don't have the know-how; I stick with formspecs.

**Comment by paramat** [comment]
Yes this is low priority, and it would have to be optional.
I'm not even sure if this is worth implementing.

**Comment by LoneWolfHT** [comment]
> I'm not even sure if this is worth implementing.

MC-like Shields, 2nd hand, hang-gliders (Piezo's mod ended up having to add a HUD element, which doesn't look good IMO), and a lot more things would be possible/improved with this

**Comment by rubenwardy** [comment]
I support this, but it needs to have an object property to enable it. Otherwise wield3d will result in two wield items being drawn

**Comment by paramat** [comment]
Yes, it does seem useful, ignore my earlier comment.

**Comment by sfan5** [comment]
This has been implemented.
