### ISSUE TITLE
Need for mapgen be able to inform server of a list of valid spawn locations.

### ISSUE THREAD

**Issue by oiaohm** [minetest/minetest#8039]
##### Issue type
 - Bug report
 
##### Minetest version
I am currently looking at git version b7eb81fed922f7215cfff1068389fa85b2ee4ab2

##### Summary
I have attempt to create a described world mapgen with a locked spawn point at 0, 0, 0 as something to start with.

At this point I noticed a problem.

getSpawnLevelAtPoint(v2s16 p) allows me to say location is invalid to and cause Server::findSpawnPos() to try again.

Lets say I have created a map for pvp to be a bit like Xonotic/doom/quake. Where there are like only 12 valid spawn points. Current api design means we end up with a huge loop between findSpawnPos and getSpawnLevelAtPoint until it find one of the magical 12 spawn points or after 4000 attempts fail and attempt latter as you can see here.
https://github.com/minetest/minetest/blob/3d66622772e66154b7624957a27f9be54c4c7c28/src/server.cpp#L3478

It would be useful if there was a method to set list of valid spawn points/ spawn zones.

Of course the list may or may not be random-ally applied.

So in my eyes
getMapgenParams()->getSpawnRangeMax(); This is ok if you want spawning in a limited block area.
but we need a getSpawnList() that returns a list nodepos2d or void and getSpawnListCycle() that returns random/cycle/fixed.
If getSpawnList() is Void do what findSpawnPos currently does. If not void get getSpawnListCycle() if random use random to choose a spawn point out of the spawn point list. If cycle simple start at the top of the spawn point list and as each player enter give them the next spawn point in list and when get to end go back to start. Fixed is simpler is each player enters they get a spawn point until they leave it is theirs.

I would like to make it simpler to make some static generated world segments for minetest. This could be useful to RPG mods and the like.

getSpawnZoneList () as well. Think pvp team play. area could be like two nodepos2d that player have to spawn inside. So areas of the map have to be travel to and you cannot just random-ally spawn.

I do see mods using Lua to force way around this limitation but really not the best path. I am not sure if this should be a mapgen Params or a global server param possible settable by minetest.conf, mapgens and lua mods and stores in the world file.

##### Steps to reproduce
Create a new .cpp mapgen heck even just use the singleblock check.

Make getSpawnLevelAtPoint in mapgen only accept 0,0  or any other location and if it not give MAX_MAP_GENERATION_LIMIT return for invalid.    Leave getSpawnRangeMax() large and watch the complete thing repeatedly hit the 4000 count limit  findSpawnPos.

I was considering having like 12 spawn points in particular maps by a generator.   In current minetest this is not going to work with the current findSpawnPos..

Of course I could have set acceptable at any location and generated the same problem.

There is no way from the map gen to say only these points are acceptable to spawn to.   This would reduce down random number requests by server.

This is both a bug report and a feature request.   This is a bug to anyone wanting to make a mapgen with fixed placed spawn points.   Feature is what is required to fix this.

**Comment by SmallJoker** [comment]
You could adjust this function accordingly in a PR to ensure it matches with the internal C++ structure/API you'd like to have. As long it does not break existing worlds (spawning, not a problem) it's fine to change these mapgen functions.

**Comment by paramat** [comment]
> It would be useful if there was a method to set list of valid spawn points/ spawn zones.

This can be done easily in a mod. In a `minetest.register_on_newplayer` function choose one of the spawn points and move the player there.
> I have attempt to create a described world mapgen

> Lets say I have created a map for pvp to be a bit like Xonotic/doom/quake. Where there are like only 12 valid spawn points.

These suggest you are using a pre-created world or are using only one world seed,in which case this is easy.
Or do you want any newly created core mapgen world to have a number of spawn zones scattered across the world? If so this is something i want to do, and this can be done already using `minetest.get_spawn_level(pos.x, pos.z)` used in a searching function such as https://github.com/minetest/minetest_game/pull/2257
See more discussion https://github.com/minetest/minetest_game/issues/2117 and #6229 
> Make getSpawnLevelAtPoint in mapgen only accept 0,0 or any other location and if it not give MAX_MAP_GENERATION_LIMIT return for invalid. Leave getSpawnRangeMax() large and watch the complete thing repeatedly hit the 4000 count limit findSpawnPos.

This is not how you would do it. For a newly generated random world you cannot impose an exact spawn point because it may be underground or high in the sky depending on the terrain.
You would use a searching function as in https://github.com/minetest/minetest_game/issues/2117 to find 12 suitable spawn points (suitable means between sea level and sea level + 16) then use those. Due to the random terrain these points may be 10s-100s of nodes away from where you want them to be.
> This is both a bug report and a feature request. This is a bug to anyone wanting to make a mapgen with fixed placed spawn points.

It's not a bug as what you request is either impossible or can be done already in a mod.
If you want fixed spawn points you can only use a pre-existing world or worlds with a fixed 'seed', fly around to choose spawn points, then move players to those points when they first spawn.

Sorry it's a little hard to understand this issue due to your use of English, it's possible i may have misunderstood.

**Comment by oiaohm** [comment]
I was attempt to make a mapgen cpp that is not in fact 100% random and I had it break.

>  For  a newly generated random world you cannot impose exact spawn points because they may be underground or high in the sky depending on the terrain.

This is not a problem when you are building a world from blocks of known templates and filling in the gaps in the middle with random.   The fact template will be applied at particular location you know the spawn point will be functional there.

Yes the current mapgens minetest using this feature is not going to work.   I was looking at making a mapgen using flat as starting point with template application at spawn points when I found out I broke the spawn by my cpp mapgen refusing too much.

Like if you have the luck of spawning in a city in the sky or deep under ground it possible to put enough resources in starting city/town that player can dig or lower(water) their way out of that problem.

Spawn location need unlimited water(protected) and some trees and do not put it under lava level.   In the sky there is way using water and wood to build down.   Under under ground wood gives you picks and ladders  and dig your way out.  Spawn template may need to be modified for usage with some different mods.

> If you want fixed spawn points you can only use a pre-existing world or worlds with a fixed 'seed', fly around to choose spawn points, then move players to those points when they first spawn.
Why are you moving players after they have first spawn why not have them spawn in the right place from the get go.   This is what I am asking for having to correct players position should be avoided.

 I am no after to absolutely fix the spawn points but after spawn points that do in fact get randomised at map first generation.

I am after fixed spawn points by the generator and possible put into the map_meta.txt (I guess this is reloaded when server is restarted).

Even so if map-meta.txt can have spawn point information added this would allow fixed known seed+ fixed known mapgen with fixed known spawns without being dependant on any particular lua mod.

What I need to store to be used with spread out fixed random placed spawns off the start line is for the random locations for spawns to be stored and the template for the mapgen to place at those locations and for the engine to go this map has set spawns I will use the set spawn list.

Really I don't see this need to be a lua mod just to have defined spawn points.   I am not talking about spawn points that change dynamically while the server is running those need to be mods.     Multi fixed spawn points have a usage.    Currently if you want a fixed spawn point from get go you have to hope that 0.0 is functional.    Please note even having list random generated fixed spawn points does not stop some of those being skipped because they are in a completely bad location.

**Comment by paramat** [comment]
Ah you're creating a new core mapgen. I completely misunderstood.
However the engine spawning code is written for the usual case, not for special cases like this. So you would just use a mod to create your desired spawning behaviour.

For example, i want to allow random spawns scattered across the world, i was going to do this in the engine, but now we have a 'spawn level at point' API it was decided to do this in mods instead.

Your desired behaviour is even more specialist than what i want to do, so i don't support coding it into the engine when it can be done already in Lua with far more flexibility.
There are many desired spawning behaviours and we can't add them all to the engine, only the most common behaviours are.
> Why are you moving players after they have first spawn why not have them spawn in the right place from the get go. This is what I am asking for having to correct players position should be avoided.

Because it makes no difference, the player repositioning is extremely fast and is done before the world appears around the player. You can see how it works in MTGame 5.0.0-dev where the 'spawn' mod moves players to friendly 'starting biomes'.

:-1:

**Comment by oiaohm** [comment]
> Your desired behaviour is even more specialist than what i want to do, so i don't support coding it into the engine when it can be done already in Lua with far more flexibility.

This is kind of right and kind of wrong.  Yes you can do a lot from lua. 

I have multi future uses for spawn point being in engine not mod.

Most of the mapgens you have as default generators generate lots of areas where players can spawn so random search is not a path to massive failure.

I don't see hooking with Lua for spawn as super smart.   Lets say we have 2 or more mods attempt to place player.

https://github.com/minetest/minetest_game/blob/master/mods/spawn/init.lua
I have read over this.  Not a really good design.   Table of suitable biome great hard set.  Lets say on a particular server you want everyone starting in a single biome type or you want everyone starting in a horrible biome.   This is only problem one.

You are are needing in there special handing for beds.  What about any other special respawn like some having area of world as a mini game

Yes the lua respawn is more flexible but doing general respawn by the current lua interface is path to hell there is not enough shared information to do it right all the time.

If engine respawn would take a list of spawn points.   Bed respawn gets to remain normal and mini games effecting spawn will not risk cat fighting as much..   

Its mapgens where you set what biome exist.   I could also see this spawn mod in minetest dropping players in the middle of mini games.

I am after spawn points to be somewhat random but able to be known to all mod and map-gens.    Lets say I load a mini game mod that places a mini game somewhere in the world as a Easter egg.   If i have a global spawn list its possible for the mini game mod to make sure no spawn is in it play area no matter where the mini game is placed.

Yes current mapgens can say this point is not a spawnpoint try somewhere else.   Mapgens cannot says this are known fine spawns use them.   Mods cannot provide a list of these areas are not spawn points please do not spawn here if you do player might be trapped inside a bedrock box or equally bad.

Do notice for performance of spawn lua mod it performs a one of search to build a list of acceptable spawn points.   Why cannot the engine spawn system have this feature as an option.   Why is it required to load a lua mod to have that happen.

Server administrators cannot provide list of off limits areas in any configuration either.

There need to be some where generic between engine, mods, mapgens to store spawn information include allowed and blacklisted areas.

With minetest changing over to sql storage for map block there could be a table/tables in here called spawn contain all the details like blacklisted boxes, allows boxes and current spawn point list in the same file.   This would allow administrators of servers edit spawn points if they happen to be landing players in wrong places.

I was expecting that somewhere in the minetest engine there was a location to list acceptable and not acceptable spawn point locations and was shocked to find it does not exist.   Working around this problem with lua is a hack.   You are missing the information storage that really functional spawn system needs.

Yes I agree Lua mods should be able to override the generic server spawn.  But those mods also need to be able to access information about what other mods have added map(areas where spawn should not be) what the mapgen knew from generation settings on where spawns should and should not be.

First step is implement the spawn list .    Next step after you have spawn information working is possible implement team play.   Unlike the current mapgen that are really designed for single player have some mapgens that are truly designed for team player in the form of team vs team really would be useful for the mapgen.

Team play maps for two teams might be split north and south of point 0.0 are mirrors of each other.

I really don't want to be writing a new spawn system every time I get a idea for a different mapgen.   I want to be able to use a general spawn system most of the time just provide it with information so it correctly places players.   Also if I have put a mini game in that players can play only once per char I don't want them to magically to be able to spawn into it and always want not too far away from where they spawn.   

If it a player tutorial area it might have sample biome protected by barrier blocks those you don't want players landing inside because they can be a closed box.

I use to play a lot of MUD when I was younger and 0ad recently.   So I wish for towns, cities and explorable world and fair team play areas.
