### ISSUE TITLE
Discuss: Increase default active_object_send_range_blocks

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#8048]
By default we have these settings now:
* max_block_send_distance = 9
* active_block_range = 3
* active_object_send_range_blocks = 3
* viewing_range = 100

The upshot is that active object pop in and out of "existence" at a range for 48 nodes.
We should increase the default.

Since #6667 the behavior can be improved by increasing active_object_send_range_blocks.

I can see two possible changes:

1. We default it to the max_block_send_distance. As a plus that would work nicely with zoom as well. (Note that both server and client will still _limit_ the range to the client's view range anyway if that is smaller, and it will only handle objects in inside the _view cone_). Or, 
2. we can set it to 6, so that it covers the default view range (6*16 = 96, close enough to 100).

My vote would be for 1) since it would lead to natural behavior, and still be lightweight enough.

Note, that does _not_ increase the active_block_range. And again, this _only_ affects the visible view cone and only for active objects.

I think that would be great change for 5.0.

**Comment by sfan5** [comment]
Agree, I'd prefer option 1) here.

**Comment by nerzhul** [comment]
i agree with 1

**Comment by paramat** [comment]
Consider: Will Android need a different setting?
I'm ok with extending 'active_object_send_range_blocks' out, just not sure by how much, in some situations this might be intensive.
Anyway, option 1 is better.

**Comment by paramat** [comment]
> Note that both server and client will still limit the range to the client's view range anyway if that is smaller,

Shouldn't 'active_object_send_range_blocks' also have a minimum value equal to 'active_block_range'? Or maybe it does already? It should never be smaller than that.

**Comment by lhofhansl** [comment]
Setting it smaller than active_block_range has no effect.

**Comment by lhofhansl** [comment]
Here I am simply planning to change the default (not add a lot of dependencies between the settings - if we had that I'd remove one of the settings).

In Android this is nicely limited anyway, because of the view range. (Note that we do not have separate setting for max_block_send_distance for Android - it's not needed).

On my machine I have active_object_send_range_blocks set to 2 * max_block_send_distance, so that it works fine when I zoom as well.

**Comment by paramat** [comment]
Ok. Yes i remember now that objects are always active within 'active_block_range'. No problem.

**Comment by lhofhansl** [comment]
Closing... See associated PR.
