### ISSUE TITLE
Discuss: Set max_block_generate_distance to max_block_send_distance?

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#8049]
This one might be controversial, but it's good to discuss at least.

Both max_block_generate_distance and max_block_send_distance are a safety limit on the server, normally limit is the client passed view range.

Having max_block_generate_distance < max_block_send_distance is weird unless we have pre-generated maps or we expect that the player is primarily moving on already generated maps.

Otherwise we allow the server to send the blocks but not to generate them, which is weird, and can lead to visible artifacts.

I propose we make them the same by default or - better, IMHO - remove max_block_generate_distance and only use max_block_send_distance.

As I said perhaps controversial... Let's discuss.

**Comment by paramat** [comment]
Certainly we could consider increasing both, other core devs may support. Although 'i'm not keen' i'm not really opposing an increase.
But whatever we do, having send range 2 more than generate range is right.

**Comment by paramat** [comment]
We've had these defaults for years, i do agree with gradually increasing the defaults as server and computer performance improves over time.
For me the lowest satisfying view distance is roughly 160 nodes, 10 mapblocks.
If we increase both settings by 1 mapblock that would result in both being effectively 10 mapblocks.
It would be a subtle increase with little risk and a nice improvement for 5.0.0.

So, for 5.0.0 i'm fine with increasing both by 1.
