### ISSUE TITLE
Deleted mod dependency warning when opening world. How to deal.

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#8052]
##### Issue type

 - Feature request
 
##### Minetest version

```
5.0+
```

##### Summary
Once you add a mod to a world, and then remove that mod (say, worldedit), warning message will haunt you forever. In world config this missing mod is not displayed, so you can't remove that unneeded dependency. Please handle this use case in some way. 

Maybe list missing mods in other color in world config with easy option to remove it.

**Comment by SmallJoker** [comment]
Not just an issue in 5.0.0-dev but in 0.4.x. I also had this problem before. Here you could remove the invalid config line:

https://github.com/minetest/minetest/blob/9854340c0b21d01a94ba7ef526c775e59e37b898/src/content/mods.cpp#L294-L296

**Comment by paramat** [comment]
Surely unfixable because the warning is useful in case a mod is accidently removed. So you should remove the mention of the mod from the world files?

**Comment by SmallJoker** [comment]
@paramat It could be an one-time warning/error. After it's printed, it would be possible to remove the entry from the world configuration - or set to `false`.

**Comment by rubenwardy** [comment]
Clicking save on the Select Mods dialog will cause the mods to be removed from world.mt. I don't think this needs any change
