### ISSUE TITLE
Translatable string “LANG_CODE” has special meaning without documentation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8063]
##### Issue type
 - Documentation issue
 
##### Minetest version
07c1c72aae71bd4405ec8e52bfa841b483de7198

##### Summary
There is an evil translatable string in the sources that has potential for translators to trip up:

```
LANG_CODE
```

Source: `src/network/clientpackethandler.cpp`, line 135.

I was told that translators MUST NOT translate the string literally, but instead put the language code (i.e. “de”) into the translation box instead.

This is not documented at all. This should be fixed.

Note that Gettext and PO files support translator comments, so adding a translator comment would be the best solution because it will show up in the software tools that translators use.

**Comment by SmallJoker** [comment]
Merging into #8178 which also includes the other special string `needs_fallback_font`.
