### ISSUE TITLE
Poor description for “near_plane” setting

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8065]
##### Issue type
 - Documentation issue
 
##### Minetest version
07c1c72aae71bd4405ec8e52bfa841b483de7198

##### Summary

This is the current description for `near_plane`:
```
Camera near plane distance in nodes, between 0 and 0.5
Most users will not need to change this.
Increasing can reduce artifacting on weaker GPUs.
0.1 = Default, 0.25 = Good value for weaker tablets.
near_plane (Near plane) float 0.1 0 0.5
```
Celeron55 told me that it's actually called “near clipping plane”, not “near plane”.
Celeron55 also told me that 0 doesn't make sense as a value for this setting.

I say the description needs some rewording, in its current form it's too confusing and weird.

https://i.stack.imgur.com/W4GSS.jpg

**Comment by Calinou** [comment]
I think this setting could be removed entirely; instead, the near clipping plane distance should be set automatically based on the Z-buffer precision (0.1 on 24-bit, 0.25 on 16-bit based on what the description says).

**Comment by Wuzzy2** [comment]
Good point!

**Comment by paramat** [comment]
'near clipping plane' is the correct technical term.

**Comment by HybridDog** [comment]
> Keep in mind that high near clipping plane distances can be used as a cheap X-ray slightly_smiling_face

![x](https://user-images.githubusercontent.com/3192173/51208762-d24cdd00-190e-11e9-97a1-976851b9e707.png)

**Comment by paramat** [comment]
0 may not make sense but very slightly larger than 0 probably does, so the lower limit has to be 0.
Due to that cheat we should change the upper limit to 0.25?

**Comment by HybridDog** [comment]
> Due to that cheat we should change the upper limit to 0.25?

No, people could also make a few pixels of the stone texture transparent in their texture pack to see through walls, can't they?

**Comment by paramat** [comment]
Not any more, we fixed the texture pack x-ray cheat.

**Comment by paramat** [comment]
Related PR #8749
