### ISSUE TITLE
Potential Lua memory allocation problem when system memory is running low

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#8067]
##### Issue type
 - Bug report
 
##### Minetest version
```
Versions possibly ranging from 0.4.16 to 5.0 commit 0e306c0
```

##### OS / Hardware
Operating system: Windows 10 Home
CPU: Intel i7-3770K @ 3.5GHz, 8.00 GB ram

##### Summary

Two of my mods have encountered very difficult-to-reproduce problems that seem to be a result of lua code getting into an "impossible" state. Variables that have no possible way of being nil are nil, nodes that have been serialized and then written back into the world lose their inventories and other metadata, things like that. Until recently I never saw this behaviour on my own machine, I only got bug reports from other users, but I believe I was able to reproduce it recently and now have a testable theory that's worth reporting.

For about a year I've been getting crash reports for Digtron that were instances of this. For example: [#5](https://github.com/minetest-mods/digtron/issues/5), [#16](https://github.com/minetest-mods/digtron/issues/16), [#17](https://github.com/minetest-mods/digtron/issues/17), [#22](https://github.com/minetest-mods/digtron/issues/22), [#30](https://github.com/minetest-mods/digtron/issues/30). I've tried adding various sanity checks and "retry on failure" fallback code to the mod but I've been unable to reproduce these problems locally and apparently none of my efforts were able to overcome them in the wild.

But then over the Christmas break I was doing work on a major revision of [dfcaverns](https://github.com/FaceDeer/dfcaverns/tree/modpack-refactor) and I started encountering a similar problem for myself. This is a mapgen mod and there's a particular type of "tree" it generates in certain biomes, the tunnel tube. While I was doing large-scale /emergeblocks runs to generate cubic kilometers of map so I could check out how it looked I discovered occasional crashes in the tunnel tube generation code. It was intermittent, however, and never happened when I was actively watching the code.

I believe I've figured out the pattern, though. Since some of those /emergeblocks runs took hours to generate, I would sometimes set it running and then spend time doing other things on the computer while the map generated blocks in the background. One of those tasks involved working with an extremely large database (not Minetest related) and I found that I was running into the limits of my computer's RAM. It seems that it was only during those periods, when I was getting memory errors while working outside of Minetest, that tunnel tube generation would exhibit these "impossible" glitches.

I took a deeper look at how I was generating tunnel tubes, and realized that I was doing a lot of inefficient table allocation followed by disposal of those tables. For each node in a tunnel tube I was using a lot of chained vector.add and vector.multiply calls (which generate vector tables internally), converting voxelmanip indices into vectors and back again, that sort of thing. [Here's the change where I reworked the code to get rid of all that extra table-creation](https://github.com/FaceDeer/dfcaverns/commit/924022967708f48887a287eef2f206eca6f83f9a#diff-9a40620ee2afdc688e59f9f50e7a6df3). And that _seems_ to have fixed it.

So I went and had a look at Digtron, which was my very first mod that I first cut my teeth on Lua with, and sure enough there was a ton of inefficient table creation and disposal going on behind the scenes. Also, gpcf reported that [he was able to prevent the problem by doubling the cycle time of Digtrons](https://github.com/minetest-mods/digtron/issues/16#issuecomment-433712982) on his server (thus halving the rate of table creation and disposal).

My working theory became that when Minetest was running into low memory conditions and its Lua garbage collection was being overwhelmed by rapid creation and disposal of tables it would start failing to allocate new tables, resulting in unexpected nil values. Discussing the matter in Digtron's issues, [numberZero](https://github.com/minetest-mods/digtron/issues/30#issuecomment-451675554) recalled that on Microsoft systems C++ memory allocation may not throw exceptions in out-of-memory situations but instead return NULL, which he speculated might translate into nils in Lua.

I know I've run into out-of-memory exceptions in Lua mapgen mods before, specifically when getting map data without using a pre-allocated "buffer" table, so this situation doesn't arise for _all_ out-of-memory situations. My speculation is that Minetest itself needs to be running out of system memory, not just the Lua sandbox getting over-full. This would explain why I was never able to reproduce the bug before; whenever I tried to reproduce it I would do so on a "clean" world with only my test Digtron running in it, and I wouldn't be multitasking with other memory-hungry applications.

##### Steps to reproduce

So, how to reproduce this. This remains a difficult bug to capture. Even when I had those tunnel tubes causing problems it only happened when I was doing a bunch of memory-hungry work in parallel, which wasn't something I could easily coordinate (especially since tunnel tube biomes were fairly rare and so I never knew when the mapgen code was making them).

I guess I could create a test mod that does nothing but continuously allocate and dispose massive amounts of tables, pushing Minetest's lua memory to the edge, and then see if I can trigger this by blowing system memory on other things. I figured I'd file this issue first, though, in case Minetest devs had a more reliable testbed that they could try this out on. I'm not really set up to do controlled profiling on this machine.

**Comment by numberZero** [comment]
Another observation is that, at least in the `digtron` mod, all the nils are inventory lists, returned either by `InvRef:get_list` (after `minetest.get_inventory`) or `NodeMetaRef:to_table` (after `minetest.get_meta`)

P.S. minetest-mods/digtron#15 is unrelated.

**Comment by FaceDeer** [comment]
Ah, so it is. I was triggered by the attempt-to-index-nil, didn't look at the other details.

**Comment by paramat** [comment]
Are you using LuaJIT? If so this might be related to the known OOM problems.

**Comment by FaceDeer** [comment]
When I ran into this locally while working on dfcaverns I was running [sfan5's 64bit 5.0.0 build 0e306c0](https://minetest.kitsunemimi.pw/builds/win64/minetest-5.0.0-0e306c0-win64.7z). I haven't been able to reproduce the Digtron reports myself, don't know what versions those were running on when they happened.

**Comment by nerzhul** [comment]
when a variable is nil in lua it can be oom. In C when you run allocations and there is no memory you have NULL. Same in C++ new Obj() returns nullptr if no memory

**Comment by FaceDeer** [comment]
Lua is capable of generating out-of-memory errors, throwing an assert and crashing out of the game in the process. I've encountered this personally, as I'm sure most mapgen modders have at some point. Why is this not always the case? I would much rather have the game crash with an error message explaining specifically what went wrong than to have it struggle along in a corrupted state.

In the case of Digtron, these out-of-memory errors were resulting in node metadata being set to "nil" when a Digtron moved to a new location, wiping out the Digtron's inventory and rendering the Digtron corrupted and unable to run any further without being torn down and rebuilt by hand. That's way worse than if the server had simply crashed.

Now that I know what was causing that I can do work to reduce memory usage and _manually_ check for certain classes of out-of-memory nil returns, but I spent a year not having a clue what was wrong and flailing away at what turn out to be completely useless attempts to work around what I imagined might be the problem. And I'm not going to be able to catch _every_ out-of-memory scenario now that I do know.

When I call minetest.get_meta(pos):to_table() and get a "nil" return value, is that because the node has no metadata or because Minetest is out of memory? I believe this may be the actual case that's been causing inventory loss and Digtron corruption in the wild, and I have no generic way of defending against it. I think I'd need to write up a bunch of special-case code that knows when a Digtron node type is _supposed_ to have metadata and throws an assert when it doesn't, and that's going to open up all sorts of other opportunities for bugs.

There's lots of builtin code that is not designed to handle out-of-memory nils gracefully either. Most of the vector-manipulation methods create new tables internally, for example, and have the potential to return "nil". None of the documentation warns of this.

Now that I think of it, there's landmines lurking everywhere. Adding a new key to a table can cause it to be reallocated to increase its capacity, so could table.insert(sometable, newvalue) or sometable.newkey = newvalue could result in sometable being nil afterward?

**Comment by FaceDeer** [comment]
According to the API documentation for MetaDataRef,

* `to_table()`: returns `nil` or a table with keys:
    * `fields`: key-value storage
    * `inventory`: `{list1 = {}, ...}}` (NodeMetaRef only)

So to_table() can return nil, according to the documentation anyway. It doesn't explicitly specify what nil represents, my assumption would be that it returns nil if a node has no metadata associated with it since the corresponding `from_table()` method will clear a node's metadata if given a nil parameter.

My general point still stands, though. There are many API calls that can return a table or nil, where the nil is supposed to mean something. minetest.get_node_or_nil(pos) for example, it returns a table or nil if pos is not loaded. If it can also return a nil when running out of memory that can put me in an unknown state.

**Comment by numberZero** [comment]
Whoops, my mistake... That’s not `inventory` what was nil, but an inventory *list.* That *is* actually permitted to be `nil`, but only if such list doesn’t exist. Updated the previous comment.

> it returns nil if a node has no metadata associated

Maybe. Or if the block doesn’t exist (although in that case, `minetest.get_meta` returns `nil` IIRC. As well as `minetest.get_inventory`, though).

**Comment by numberZero** [comment]
> Can you compile MT yourself?

@FaceDeer That question is to you too

**Comment by FaceDeer** [comment]
> Can you compile MT yourself?

Ah, I see. I haven't ever tried that before, I'd need to set up a lot of stuff. It'd be a while before I have the time to spare on that. I'll want to make sure I can reliably reproduce the bug first, I still haven't ever managed the Digtron one, just the one that cropped up during development of dfcaverns.

**Comment by thomasrudin** [comment]
@numberZero 
> Please describe the system and MT build you experienced the crash

**Platform** Linux
**Architecture** x86 64 bit
**Memory** 8GB (was never an issue, never saw an OOM, only protection violations but unrelated)
**Environment** Docker, self compiled minetest (https://git.rudin.io/docker/minetest-docker)
**Build** stable-04
**Game** minetest-game backport-0.4

**Comment by nerzhul** [comment]
@thomasrudin can you use the official docker image from Gitlab registry ? (it's based on master branch)

See: https://gitlab.com/minetest/minetest/container_registry

**Comment by thomasrudin** [comment]
> @thomasrudin can you use the official docker image from Gitlab registry ? (it's based on master branch)
> 
> See: https://gitlab.com/minetest/minetest/container_registry

I would like to do that but i don't have time for experiments the next few weeks..
On top of that: i haven't had that error since 2 months...
I'll update here if i find time to use the official images.

**Comment by numberZero** [comment]
Investigated. The facts are that `minetest.get_meta` just creates a (sort of) reference, not checking whether it is valid. Actually, it doesn’t check *anything,* it just stores the coordinates.

Next, `NodeMetaRef:get_inventory` loads the block referenced and creates the `NodeMeta` in it, if necessary. But it never creates the block if it doesn’t exist yet. It doesn’t error, either. *It just creates an `InvRef`* referencing the same coordinates, regardless of whether the block loading succeed.

Finally, `InvRef:set_list` needs an actual inventory to action. It tries to get the inventory by its coordinates; the actual pointer is never stored. If that fails (i.e. there is no meta at the position, what happens if there was no block), it fails silently. *Silently.*

**Comment by FaceDeer** [comment]
Interesting. This is separate from whether a node's type is "ignore", I take it? I've been using that node type as a check to keep Digtron from entering unloaded areas, but "unloaded" and "not yet generated" are different concepts and I see a definite potential problem here. Is there a way to test the "loaded" state of a node?

I suppose I could test the status of a node by getting meta, creating an inventory, adding a dummy item, then checking if the item is in that inventory (and then removing the inventory again on success to prevent clutter). But that sounds rather terrible.

**Comment by numberZero** [comment]
> Is there a way to test the "loaded" state of a node?

Almost. If a node is not `ignore`, it’s definitely generated and loaded, at least at the moment of check. The opposite is a subtle matter.

> I suppose I could test the status of a node by getting meta, creating an inventory, adding a dummy item, then checking if the item is in that inventory (and then removing the inventory again on success to prevent clutter). But that sounds rather terrible.

1. You’re right, that’s terrible.
2. You should remove the whole meta, not just the inventory. Dunno is there a standard way for that.

But you don’t need that actually. When you check the block for presence, false negatives aren’t a great problem (they will only stop the digtron); false positives are. “`ignore` check” should have no false positives. You only should need to check *all* the nodes the digtron is about to enter. The fact your code seems to do that properly really puzzles me.

**Comment by numberZero** [comment]
Sorry for long wait, busy IRL. See #8296 for debug patch, it should report all failed inventory accesses.

**Comment by thomasrudin** [comment]
I think i encountered the same problem yesterday in one of my mods:
* https://github.com/thomasrudin-mt/jumpdrive

It is basically a worldedit tool for survival, it can move structures around the map.
This is what happens when someone jumps:
* reading of the node,param1 and param2 data from the source area
* writing the node,param1 and param2 data to the target area
* metadata gets moved with `jumpdrive.move_metadata()` (https://github.com/thomasrudin-mt/jumpdrive/blob/844d6c761decc780dcf21a1e341fa7e01db4e5e6/move_metadata.lua#L3)
* nodetimers get moved with `jumpdrive.move_nodetimers()` (https://github.com/thomasrudin-mt/jumpdrive/blob/844d6c761decc780dcf21a1e341fa7e01db4e5e6/move_nodetimers.lua#L15)
* source area gets cleared with air nodes

More details in the `jumpdrive.move()` method; https://github.com/thomasrudin-mt/jumpdrive/blob/844d6c761decc780dcf21a1e341fa7e01db4e5e6/move.lua#L8

The interesting part is the spaceship i found: **All the inventories were gone and some of the metadata, but not everything**

I suspect the values were lost in `minetest.get_meta(target_pos):from_table(source_table)` (https://github.com/thomasrudin-mt/jumpdrive/blob/844d6c761decc780dcf21a1e341fa7e01db4e5e6/move_metadata.lua#L12)

Funny thing: **all** the protectors (https://notabug.org/TenPlus1/protector) "owner" fields were cleaned out (nil) without exception...

Hope that helps somewhat...

**Comment by numberZero** [comment]
@thomasrudin Try reproducing with #8296. That’s not a fix but it should report what exactly goes wrong.

**Comment by thomasrudin** [comment]
I ran the numbers on the inv-error message again with the PR from #8296:

```
# docker-compose logs minetest | grep "get node inventory" | wc -l
1223
```
I got over 1200 missing inv messages since 2019-04-19...

But i don't think that it has anything to do with the lua memory running low because i monitor that
since a few weeks and noticed nothing unsual:
https://monitoring.minetest.land/d/YUpouLmWk/overview?orgId=1&var-instance=pandorabox.io
(Graph with the "Lua Memory" title)

**Comment by appgurueu** [comment]
This issue seems like a "possible close" to me (feel free to remove the tag if you disagree):

* No new comment during the last 5 years?
* The "theory" seems pretty nonsensical to me:

> My working theory became that when Minetest was running into low memory conditions and its Lua garbage collection was being overwhelmed by rapid creation and disposal of tables it would start failing to allocate new tables

That can happen. It's called an OOM. It's an error.

> resulting in unexpected nil values

That will not happen.

> on Microsoft systems C++ memory allocation may not throw exceptions in out-of-memory situations but instead return NULL, which he speculated might translate into nils in Lua.

That makes no sense. Lua is implemented in C and uses raw `malloc` and friends. It knows memory allocation failed precisely when it gets a `NULL`. This will kick off an emergency GC. If that fails to free new memory, Lua will panic. Memory allocation failure is not translated into `nil` by Lua, ever.

I think if anything something somewhere in the **C++** parts is catching a memory allocation failure and then doing something insensible (like throwing away data silently) when it should probably just OOM to leave everything in a consistent state, and that then translates into erased metadata or similar. Either way this will need a clearer issue.
