### ISSUE TITLE
Allow CSMs to access csm_restriction_flags.

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#8068]
##### Issue type
 - Feature request

##### Summary

Client-provided CSMs should be able to access the server's `csm_restriction_flags` value so they can show error messages instead of silently failing (at least when sending chat messages).

**Comment by nerzhul** [comment]
You are right, we should add this on release to make the modders life easier to integrate first CSM mods properly without being crazy.

@paramat @SmallJoker @rubenwardy it's not a very difficult feature to implement on CSM we should really add it on this release to make CSM modders' life easier. Okay for you ?
I suggest a new call minetest.get_csm_applied_restrictions() which will return a restriction list + a CSM builtin call to test the restriction is in the list to make their life easier.

**Comment by paramat** [comment]
I agree with SmallJoker, not a blocker and not essential for 5.0.0, but also, it seems ok to add this now.
