### ISSUE TITLE
Allow installing mods without breaking worlds (discussion)

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8071]
There seems to be some reticence to accept #6898 or even the much lighter #7914. Only one core dev has currently actively supported both, and it's been around for a while.I've opened this issue for discussion of the concept, in the hopes of gathering more interest from core devs.

The problem can be stated in a very simple way: **installing a mod or a modpack can break existing worlds**.

The reason is also very simple: the only information that the core has about the mod in the configuration files is the name. It doesn't have information about the path to load it from. Therefore it has to search for all mods with that name, and it needs a method for resolving conflicts if they arise. And when they arise, it may make the wrong decision, or even no decision at all (as it happens with mobs classic vs mobs_redo).

The solution is also (conceptually) very simple: just store information about the path where the mod needs to be loaded from, not just the name.

So, what needs to be discussed is where the path will be stored and maybe in what format. The obvious place is `world.mt` because that's where the `load_mod_<modname>` settings are also stored. The approach of #6898 was to reuse the same variable to not just hold `false` or `true`, but instead use `false` or the path within `mods/` to load it from.

But that solution has a catch: the core currently considers `false` anything other than the string `true`, the string `yes` (both case insensitively) or a string starting with a nonzero number. Maybe I've forgot one. This means that the strings that specify the path would be considered false, thus breaking compatibility, unless they start with a nonzero number. As currently designed, they all start with the substring `mods`, to indicate they should be loaded from the `mods` subdirectory. Other planned valid prefixes (not implemented by #6898) are `game` and `world`.

That catch is the very reason for #7914 to exist. It makes `false` and `nil` be the only false values for the `load_mod_<modname>` settings (and also fixes the bug that generates `nil` as a setting value). That will facilitate incorporating #6898 painlessly later on. The path separator used in #6898 is a dot `.` following Lua's `require()` convention, but that's also open for discussion or replacement.

There are two alternative fixes that don't need #7914. One is to use `1`, `2` and `3` instead of `game`, `world` and `mods` respectively. That would make the setting true regardless of the suffix, and would therefore keep backwards and forwards compatibility even with 0.4.x. The other is to keep `load_mod_<modname>` as-is, and add an additional config variable per mod to hold the path, like `mod_path_<modname> = <path>`.

Which one is preferred?

1. `load_mod_<modname> = mods.<path>` (current approach that needs either #7914 or #6898)
2. `mod_path_<modname> = mods.<path>`. This is backwards- and forwards-compatible
3. `load_mod_<modname> = 3.<path>` where `1.<path>` and `2.<path>` are reserved for game and world respectively. This is backwards- and forwards-compatible.

What path separator is preferred? `.`? `/`? Some other?

Are paths relative to the mods/world/game mods dir preferred, or is it preferable to use e.g. absolute paths?

**Comment by paramat** [comment]
> There seems to be some reticence to accept #6898 or even the much lighter #7914

You actually have the support of 2 core devs for those, and it's added to blockers :)

**Comment by pgimeno** [comment]
> Also added this to blockers as this is a network compatibility breaking issue.

How does it break network compatibility? It can become an issue if world files with their world.mt are shared with other people (e.g. in the Maps forum), but I thought that's it. It *does* need a decision before 5.0.0, to decide whether #7914 or #6898 are needed at all in the first place, so the blocker label is still deserved.

Also, what's your preferred solution?

**Comment by SmallJoker** [comment]
Another issue would be that you could no longer rename mods or modpacks.
Also: It's now (or soon?) possible to make use of the modpack name, which then could each contain a different, but same named mod.

**Comment by pgimeno** [comment]
I'm not a fan of using "logical names" in the configuration (as opposed to the filesystem's physical names). The setting solves the issue precisely by mapping logical names to physical locations; using logical names would create the need of solving modpack conflicts, pretty much creating yet another instance of the same problem.

True, renaming folders will break things, but it's easily fixable from the configuration (with #6898). As things are now, it's not fixable except by removing the mod from the mods folder.

**Comment by pgimeno** [comment]
With #8055 (PR for #7914) merged, this is no longer a blocker.

**Comment by nerzhul** [comment]
@pgimeno issue should be closed ?

**Comment by pgimeno** [comment]
@nerzhul no, it's just not release-critical anymore. The decision can now be taken during the 5.x cycle. Preferably in the 5.0.x series, as this bug affects many people and needs to be solved as soon as possible (I can't live without the fix, now that I have it), but I understand that the priority now is releasing 5.0.0.

Note however that after 5.0.0, I'm going to delete my GitHub user, so I won't be able to comment here.

**Comment by paramat** [comment]
Nothing bad has happened to anyone yet as a result of the MS buyout, so please don't.
MS may well be malicious in some ways but they may never actually act maliciously through Github, and have not yet.
What risk is there in keeping a Github account simply to comment here? Keeping your code elsewhere is fine because we can import patches easily enough, but not being able to comment here will make contributing very difficult.

Isn't it important to continue to support MT development, at least as long as there is no actual harm being done to you by MS? You're a talented and much valued contributor, we don't want to lose you.
The ironic fact is that militant anti-MS attitudes amongst some MT contributors are significantly harming MT while MS actually hasn't yet.
