### ISSUE TITLE
Hudbars displays twice in 5.0

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8075]
I wasn't aware of any breaking changes made to health bars and such. When installing hudbars, it no longer hides the health bar

If this is a breaking change, then it needs to be documented
If this is a bug, then it would be nice to have it fixed

**Comment by SmallJoker** [comment]
Fix1: #7360
Fix2: #7348

**Comment by Wuzzy2** [comment]
I can confirm the bug.
Whether it is hudbars' fault or Minetest's, I don't know.

**Comment by paramat** [comment]
Partially fixed by #8167

**Comment by paramat** [comment]
#8167 merged, this may be partially fixed now.

**Comment by paramat** [comment]
Odd, i can't confirm this bug.

**Comment by paramat** [comment]
No bug with #8167 merged either.

**Comment by paramat** [comment]
@rubenwardy @Wuzzy2 please test for the bug now that #8167 is merged.

**Comment by Wuzzy2** [comment]
Seems to work.
ffb17f1c9a203fea6de70159b461f52d104e05b9

**Comment by Wuzzy2** [comment]
Sadly, the healthbar in MCL2 still seems to fail.
The hearts don't turn black when taking damage.
Oddly, the other bars seem to work correctly.
MCL2 also uses `hudbars`. It also works fine in 0.4.17.1. Weird. :-(

**Comment by paramat** [comment]
Ok hudbars appearing twice is fixed then, your other issue (please open a new issue for that) may be fixed by #7360 . However i don't think we can let this MCL2 bug block release, unfortunately, as it is a rare type of usage with easy workarounds.

**Comment by paramat** [comment]
Hudbars appearing twice is fixed by #8167 , confirmed by me and wuzzy. So closing.
Please open a new issue for "Sadly, the healthbar in MCL2 still seems to fail.
The hearts don't turn black when taking damage."

**Comment by paramat** [comment]
I've made #7360 a blocker for consideration for 5.0.0, as the remaining hudbar bugs may be considered a blocker.

**Comment by paramat** [comment]
#7360 merged.
