### ISSUE TITLE
Advanced settings: Noise window reads “eased” value incorrectly

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8076]
##### Issue type
 - Bug report

##### Minetest version
95d4ff6d1b62945decc85003a99588bb0539c45b

##### Summary
Sometimes, when you edit a noise setting in advanced settings, the checkbox “eased” gets checked even if its not in the setting value.

##### Steps to reproduce
1. Open Minetest
2. In advanced settings, reset `mgv5_np_factor` to default. The word “eased” should not appear in the value
3. Click the “Edit” button to open the noise window
4. Look at the checkboxes

Expected: “eased” is not checked, because this word does not appear in the string
Actual: “eased” IS checked

**Comment by paramat** [comment]
This noise has 'eased' as the default.
When i open the advanced settings tree the word 'eased' does not appear.
If i 'edit' then 'save' (not 'cancel') the word does appear in the advanced settings tree.
'Restore default' then makes the word disappear.
@srifqi

**Comment by nerzhul** [comment]
Same as previous PR, not blocking release but can be fixed for 5.0.0

**Comment by srifqi** [comment]
I found something on `dlg_settings_advanced.lua`:

https://github.com/minetest/minetest/blob/0acdf936830f0bee6bff553201febedecb12a482/builtin/mainmenu/dlg_settings_advanced.lua#L159-L165

Why should the flag be removed from default? Note that I just revived an old PR and didn't even know the reason behind it.

-------

About the forgotten closed curly bracket, I think these lines of code makes it (`}`) marked as invalid and just leave as it is.

https://github.com/minetest/minetest/blob/0acdf936830f0bee6bff553201febedecb12a482/src/settings.cpp#L971-L973

Maybe, we should create a stack for the settings' parent and create special case for closed curly bracket (`}`)? I don't know for now.

https://github.com/minetest/minetest/blob/0acdf936830f0bee6bff553201febedecb12a482/src/settings.cpp#L246-L248

**Comment by paramat** [comment]
#8089 merged, fixes the '}'s.

**Comment by pauloue** [comment]
Omitting the flags was intentional, probably because the single line format does not support flags. Still, I think it would be better to show them so that the current value can be seen without opening the edit window.

**Comment by srifqi** [comment]
Single flag format is removed already from `minetest.conf`.

I found that the flags' place is used for lacunarity (as optional value).
https://github.com/minetest/minetest/blob/245e628d401e421abc512ee0c3b057735fbccaea/src/settings.cpp#L541-L543

**Comment by Wuzzy2** [comment]
I can no longer reproduce this bug in 44458896d9097c15c722c5bffb3d72e14962b7ce (5.2.0-dev).

Should I close it?

**Comment by SmallJoker** [comment]
#8089
