### ISSUE TITLE
Android build fails

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest#8079]
##### Issue type
 - Build issue
 
##### Minetest version

```
5.0.0-dev
```

##### OS / Hardware
Android

##### Summary
openssl build fails with the following message:
```
sha256-armv4.S:2638:2: error: invalid instruction, did you mean: adr?
 adrl r3,K256
```
It seems to be the removal of `no-asm` from the configure in 9854340c0b21d01a94ba7ef526c775e59e37b898 because re-adding that fixed that one for me.

Next I get this:
```
jni/../jni/src/client/tile.cpp:1019:3: error: no matching function for call to
      'strstr'
                strstr(glGetString(GL_EXTENSIONS), "GL_OES_texture_npot");
```

Would appear to be related to 95d4ff6d1b62945decc85003a99588bb0539c45b

**Comment by sfan5** [comment]
@nerzhul

**Comment by nerzhul** [comment]
i should have missed a header inclusion i think. Will fix that tomorrow

**Comment by nerzhul** [comment]
Fixed

**Comment by nerzhul** [comment]
i perform a build on my home machine, i just fixed it reading the strstr C spec to find the inclusion. Will perform a second fix after

**Comment by nerzhul** [comment]
Note: i tested the inclusion with this code:

```
#include <iostream>
#include <cstring>
int main() {
  std::cout << strstr("toto tata", "tata") << std::endl;
 }

**Comment by stujones11** [comment]
Yeah, I've tried using `std::strstr` and also `#include <string.h>`, both stack-overflow suggestion but unfortunately, no dice :(

**Comment by sfan5** [comment]
Android's libc is notoriously shit at
* providing working standard functions
* providing standard functions
* providing standard functions at lower api levels

<hr>

you'll need to reimplement strstr, or better yet just use std::string

**Comment by stujones11** [comment]
This is making me wonder how on earth the recent backports release was even compiled...

Seems to me that the last 'fix' can't really be in the latest apk, unless it's just a problem with my build system. It seems unlikely though.

**Comment by nerzhul** [comment]
yeah i will re-introduce the C++ part then... it's ugly and less nice in terms of memory

**Comment by nerzhul** [comment]
no in fact i will add the FreeBSD function for android only...

https://github.com/lattera/freebsd/blob/master/sys/libkern/strstr.c

**Comment by nerzhul** [comment]
fixed in master now tested working. we just needed a cast...

**Comment by stujones11** [comment]
Thankfully it is now building successfully, however, I would appreciate it you would allow me to close my own issues :p
