### ISSUE TITLE
Minetest not compiled

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#8082]
##### Issue type
 - Bug report

 
##### Minetest version

```

```

##### OS / Hardware
Operating system: Debian
CPU: AMD FX

GPU model: NVIDIA Geforce 710B
OpenGL version: 3.0

##### Summary
[  1%] Built target jsoncpp
[ 13%] Built target lua
[ 13%] Built target cguittfont
[ 13%] Built target GenerateVersion
make[2]: *** Нет правила для сборки цели «/usr/lib/x86_64-linux-gnu/libGL.so», требуемой для «bin/minetest».  Останов.
CMakeFiles/Makefile2:272: ошибка выполнения рецепта для цели «src/CMakeFiles/minetest.dir/all»
make[1]: *** [src/CMakeFiles/minetest.dir/all] Ошибка 2
Makefile:149: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by NathanSalapat** [comment]
Can we get the output in English? My guess is you probably don't have a dependency required to build.

**Comment by Ekdohibs** [comment]
It seems like libGL.so is not found correctly. A possible cause would be that you ran cmake with libGL installed somewhere else. Could you try to delete the cmake cache and run it again?

**Comment by sfan5** [comment]
> There is no rule to build the target “/usr/lib/x86_64-linux-gnu/libGL.so” required for “bin / minetest”. Stop.

You should run `make clean` and then re-try.

**Comment by TillCoyote** [comment]
Да ты просто перед make-ом "cmake ." должен выполнить. Точка в конце это путь до папки minetest/.

**Comment by nerzhul** [comment]
please talk english

**Comment by paramat** [comment]
No response from issue author, closing due to 1 month rule and likely user error.
