### ISSUE TITLE
bgcolor[] does nothing

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#8084]
In testing a mod, I found `box[]` alpha is broken in 0.4.17.1, so I tested in 5.0 to see if it was fixed (which it is). However, my black background breaks in 5.0. `bgcolor[black]` seems to do nothing.

Using build 95d4ff6d.

**Comment by SmallJoker** [comment]
Did you add `no_prepend[]` to the beginning of your formspec?

https://github.com/minetest/minetest/blob/a18c310adb075b1ba94950b6ee811c68dec2f66b/doc/lua_api.txt#L1816-L1818
https://github.com/minetest/minetest/blob/a18c310adb075b1ba94950b6ee811c68dec2f66b/doc/lua_api.txt#L5139-L5144

**Comment by rubenwardy** [comment]
You shouldn't need to do that, as future `bgcolor`s override previous ones. So this should work

```lua
minetest.register_chatcommand("a", {
func = function(name)
   minetest.show_formspec(name, "a", [[
  size[4,4]
  bgcolor[red]
  label[1,1;hi]
]])
end,
})

**Comment by GreenXenith** [comment]
@rubenwardy 
![image](https://user-images.githubusercontent.com/24834740/51001538-34f44200-14e5-11e9-8aa1-d30c856f7820.png)

**Comment by HybridDog** [comment]
It happens to me, too.
Also, when running minetest --info, I get these messages. I don't know if it's related:
```
2019-01-11 17:51:13: INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"
2019-01-11 17:51:13: INFO[Main]: Unknown DrawSpec: type=formspec_version, data="1"
```

**Comment by GreenXenith** [comment]
Is this considered a blocker?

**Comment by SmallJoker** [comment]
Works for me

![bgcolor](https://user-images.githubusercontent.com/1497498/51083318-7c164900-1718-11e9-8dd4-7f2671b11dfb.png)

```Lua
"size[10,8]" ..
"no_prepend[]" ..
"bgcolor[red]" ..
"dropdown[5.2,5;2;category;a,b,c,d,e,f,g,h;1]"
```

**Comment by rubenwardy** [comment]
You shouldn't need no prepend

**Comment by rubenwardy** [comment]
Just realised this isn't a bug at all! The bgcolor will be hidden behind the background image, so use no prepend
