### ISSUE TITLE
Formspecs: Draw simple shapes (polygons, polylines, circles)

### ISSUE THREAD

**Issue by orwell96** [minetest/minetest#8087]
##### Issue type
 - Feature request
##### Summary

Unlike  #6805, which is for in-world drawing.

Formspecs currently feature the box[] element to draw a colored rectangle. You can draw horizontal and vertical lines using this, too. However, I would like to draw polylines or other primitive shapes that may be diagonal. This would allow, for example, for creating in-game road/railway mappers.

If a replacement for the formspec language should be implemented, I would be fine with it implemented there.

**Comment by rubenwardy** [comment]
This could be done with image elements

**Comment by SmallJoker** [comment]
I think an image drawing library (like cairo) would be better suited for this job.

**Comment by paramat** [comment]
Formspec positioning is so weird and buggy i don't think this would be usable for drawing anything.

**Comment by raymoo** [comment]
You can't draw arbitrary length diagonal lines with images because you can't rotate them except in multiples of 90 degrees. Stretching an image of a diagonal line will change the line's width. Same with circles, you can't get an arbitrary radius / line width circle without making a new image for every circle, which may not be possible if you are dynamically deciding these parameters.

**Comment by raymoo** [comment]
Wouldn't #8524 solve your concern about coordinates being weird?

**Comment by DS-Minetest** [comment]
Related: #8549

Couldn't drawing primitives be done with vector graphics? (Related: #2419)

**Comment by v-rob** [comment]
I think dynamic images (like `^[combine`, but actually designed for dynamically created images) would be a better solution to this problem.  The main problem with `^[combine` is that it fills up the cache on the client after a while, making it non-feasible for something that can change constantly.

Dynamically-created images would be killing two birds with one stone -- both entities and formspecs could have dynamic images. You could also place the image on both an entity and a formspec (think placing the rail map on both the formspec and somewhere in the train entity).

**Comment by raymoo** [comment]
How do you imagine I would draw a diagonal line of arbitrary length? I think one way it could be solved is with rotation modifiers other than in multiples of 90 degrees, but maybe you have something else in mind.

**Comment by raymoo** [comment]
@DS-Minetest I think vector graphics would have the same problem with diagonal lines I mentioned in https://github.com/minetest/minetest/issues/8087#issuecomment-455709451

**Comment by v-rob** [comment]
> How do you imagine I would draw a diagonal line of arbitrary length? I think one way it could be solved is with rotation modifiers other than in multiples of 90 degrees, but maybe you have something else in mind.

By dynamic images, I mean images that you actually create.  You would draw directly to pixels, and, if an API was created, probably lines, circles, and suchlike.  I'm not speaking of modifying/rotating existing images, I mean making new ones entirely with the possibility to combine with existing images.

**Comment by raymoo** [comment]
Oh, I see. That doesn't sound very efficient if you wanted to draw a very long diagonal line, since you would need to draw and store a texture with size quadratic in the length of the line. With a line primitive the engine could just use two triangles to draw the line.

**Comment by paramat** [comment]
Deleted my comment as formspec coordinates have been improved.

**Comment by raymoo** [comment]
@rubenwardy's disapproval is based on a false premise (that this feature is possible with image elements). For example, it is not possible to draw uniform length diagonal lines with procedural length and width.
