### ISSUE TITLE
Reconsider positional sound distance model for less rapid falloff

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#8088]
Paramat changed the sound curve for the positional sound volume distance, when doors became meshnodes, and ever since it's too loud up close and too quiet far away.

![image](https://user-images.githubusercontent.com/23448162/50985284-f86b1b00-14d1-11e9-83c1-a579073275ea.png)

///////////////////
EDIT by paramat: Statement above is incorrect, issue changed to the reconsideration of distance model, see below.

**Comment by jastevenson303** [comment]
This might be okay for doors, but sucks for other stuff, like positional sound.

**Comment by SmallJoker** [comment]
Sound distribution is non-linear FYI.

**Comment by paramat** [comment]
My 2 changes to sound falloff behaviour were:

#5109
"In createPlayingSoundAt(), AL_ROLLOFF_FACTOR is not set, so it has
the default value of 1.0, this makes the equation of the currently
used AL_EXPONENT_DISTANCE distance model identical to the equation
of the simpler AL_INVERSE_DISTANCE distance model.

Using AL_INVERSE_DISTANCE means an exponent is not processed,
exponents are quite intensive to process.
There is no change in sound attenuation behaviour."

#6457
"Change OpenAL distance model from AL_INVERSE_DISTANCE to
AL_INVERSE_DISTANCE_CLAMPED to avoid excessive volume when very close
to the sound location,"

Neither changed sound falloff behaviour as your image suggests, it has always been 'inverse distance'. The 2nd PR actually added a 'clamp' to avoid excessive volume when close to a sound source.
For more details see page 87 here https://www.openal.org/documentation/OpenAL_Programmers_Guide.pdf

Note your issue https://github.com/minetest/minetest_game/issues/1895 seems to be the same issue, but it was addressed a year ago by me adding the 'clamp'.
If doors are still too loud we can reduce the gain -> MTG issue.

**Comment by jastevenson303** [comment]
I'm guessing that the rate of diminishing volume is dependent upon `max_hear_distance`.

**Comment by jastevenson303** [comment]
Here is a little mod to test: https://github.com/jastevenson303/sndtest

```
-- Sound Distance Test

snd = {}
snd.distance = 32

local ss = function(pos)
	local sss = {
		name = "snd_snd",
	}

	local spt = {
		pos = pos,
		loop = true,
		max_hear_distance = snd.distance
	}

	return minetest.sound_play(sss, spt)
end

minetest.register_chatcommand("snd", {
	func = function(name, param)
		param = minetest.string_to_pos(param) or
				{x = 0, y = 0, z = 0}
		local player = minetest.get_player_by_name(name)
		local pos = vector.floor(player:get_pos())
		pos = vector.add(pos, param)

		local handle = ss(pos)
		minetest.chat_send_player(name, handle ..
				" at " ..
				minetest.pos_to_string(pos))

		minetest.after(1, minetest.sound_fade, handle, -1, 0)
	end,
})

minetest.register_chatcommand("distance", {
	func = function(name, param)
		param = tonumber(param)
		if not param then
			return false, "Not a number."
		end
		snd.distance = param
	end,
})
```

https://github.com/jastevenson303/sndtest/blob/master/sounds/snd_snd.ogg

It appears the greater the `max_hear_distance`, the less the sound's volume diminishes.

**Comment by paramat** [comment]
> I'm guessing that the rate of diminishing volume is dependent upon max_hear_distance.

No, independent, volume = 1 / distance.
> It appears the greater the max_hear_distance, the more the sound's volume diminishes.

Yes as expected from that equation.

**Comment by jastevenson303** [comment]
Alright well good luck with that.

**Comment by paramat** [comment]
> It's my impression that positional sound volume diminishes too quickly

It's possible it falls off faster than is realistic, although in real life sound never attenuates linearly (the straight line you drew in the first post). The inverse distance model doesn't take into account sound reflections off surfaces.

I guess we could make this issue about reconsidering the distance model? So i'll reopen it as that.
We could possibly use the exponential model and tune the exponent to be more realistic and not quite as fast a falloff.
> I'm guessing that the rate of diminishing volume is dependent upon max_hear_distance.

As you have pointed out in #7800 , the 'max hear distance' has nothing to do with the distance model, it's simply how close you need to be to trigger the sound.
