### ISSUE TITLE
Audio attached to object stops moving when object leaves

### ISSUE THREAD

**Issue by Elkien3** [minetest/minetest#8094]
##### Issue type
 - Bug report
 
##### Minetest version
minetest-5.0.0-a18c310-win64

##### OS / Hardware
Operating system: Windows 10
CPU: Intel(R) Core(TM) i7-6700HQ

##### Summary
Sounds that are attached to an object have issues when the object leaves the object send range.
They remain in the last known location of the object until it either comes back into range, or the audio ends.
This is mostly an issue with constant looping audio on a moving object, such as a car in the following video: (headphones recommended)
https://youtu.be/YoixyZzCTZc

##### Steps to reproduce
Make an object that you can move away from yourself and attach a looping and/or long sound to it.

**Comment by nerzhul** [comment]
i don't think we can fix that with our current API which doesn't make sound linked to objects but only positions.

**Comment by paramat** [comment]
Long sounds are not handled too well in MT.
It could be argued that the currently playing sound should complete before being removed. Are you using overly-long sounds?

**Comment by Elkien3** [comment]
in the case in the video it's a 13 second sounds clip that is looped until the engine is stopped, either when he gets out or honks the horn.
perhaps it would be possible to, on the client, automatically end a sound that is connected to an object once the said object is no longer being sent?

**Comment by paramat** [comment]
Yes to clarify i agree it's best to instantly stop a sound on object removal, as long sounds are quite often used in MT.

**Comment by jastevenson303** [comment]
(I just want to add that you cannot minetest.sound_stop a fading sound,
because minetest.sound_fade obliterates the handle.)

**Comment by Montandalar** [comment]
I recently hit this bug with the sounds for linetrack. Currently, the position of the entity sent by the server is simply taken as the position for the sound and looping continues forever. I suggest it be properly attached to the CAO and deleted when that CAO is removed. What do ye think?

 [src/network/clientpackethandler.cpp:818](https://github.com/minetest/minetest/blob/master/src/network/clientpackethandler.cpp#L834)

**Comment by Zughy** [comment]
Related #11521 (unsubscribing)

**Comment by sfence** [comment]
Should be fixed with #14341.
