### ISSUE TITLE
Reminder to update Weblate before release

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8095]
This issue is just a reminder to update Weblate a final time before the 5.0.0 release. And to notify translators (again).

Since there is no string freeze (to my knowledge), string changes might still sneak in.

**Comment by SmallJoker** [comment]
This is included in the release process.https://dev.minetest.net/Releasing_Minetest#Before_releasing

**Comment by nerzhul** [comment]
weblate has been updated at the freeze. I will push changes from weblate on sunday, re-update and push
