### ISSUE TITLE
dying on lava causes repeated death, if respawn location isn't quickly updated

### ISSUE THREAD

**Issue by sudoman** [minetest/minetest#81]
If you die on lava, first you are given health points, then the respawn position is set to the spawning point.

If you have a slow connection, then you will die again before you are respawned. This can happen several times. Part of the problem is that either before or after the "you died" message is shown, you can still die again.

A work-around is to die, then hop on safe land before you are given health points again, and then wait until you are respawned.

**Comment by sfan5** [comment]
fixed by 5e075c3344911176421be3ae08e2bdc432a83b8f
