### ISSUE TITLE
Minetest doesn't start on Windows [& Linux] with sound device disabled.

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8107]
https://forum.minetest.net/viewtopic.php?f=42&t=17439&p=340937#p340937

Verified.  Steps to reproduce: Disable windows sound driver.  Start Minetest.

**Comment by jastevenson303** [comment]
Not sure if it's helpful, but, from OpenAL Programmer's Guide, pp 8:

>Device Enumeration
>The function call to open a device, alcOpenDevice, takes a string as input.  The string should contain either the name of a valid OpenAL rendering device, or NULL to request the default device.

**Comment by SmallJoker** [comment]
What's the difference of this issue to #7250?
