### ISSUE TITLE
Add 'selection boxes' parameter of entities separately and possibility to add more one these

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8109]
##### Issue type
 - Feature request

There`s no possibility of adding more one collision box for entity. And also i think 'selection_box' should be separate parameter in object_definition table for it as nodebox drawtype.

**Comment by paramat** [comment]
There's probably a performance problem with this: Nodes often have multiple nodeboxes, but entities have a single collisionbox, this means collision detection deals with 1 moving box colliding with multiple stationary ones.
If an entity has multiple collisionboxes then collision detection has to deal with multiple moving boxes colliding with multiple stationary boxes, greatly increasing the amount of collision calculations.

**Comment by SmallJoker** [comment]
#9196 covers this request and contains more discussion. Closing.
