### ISSUE TITLE
Add separate parameters in node_def adjusting scale of inv item of a node and node itself.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8110]
##### Issue type
 - Feature request

To example, 'inv_item_scale' and 'node_scale' in node_definition table. First parameter will adjust scale of **inventory item image** and second one will adjust scale of **node is put in-world** itself. It will be useful for nodes that have 'mesh' and 'nodebox' drawtypes.

**Comment by paramat** [comment]
I think there's a duplicate issue somewhere, for fixing the tiny appearence of small nodes in inventory ...

**Comment by paramat** [comment]
Duplicate of #5517
