### ISSUE TITLE
Changed passwords don't save on shutdown when using SQLite backend

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8116]
1. Create new world
2. log in, create account
3. change password
4. immediately exit then log back in
5. password invalid, but old password works

**Comment by SmallJoker** [comment]
Does this also affect the files backend? I believe I've seen it there too.
Bug exists in 0.4.x and 5.0.0-dev.

Possibly related: #/5954

**Comment by rubenwardy** [comment]
this happens even when logging in with an existing account, then changing and shutting down

**Comment by Fixer-007** [comment]
Is not this a blocker?

**Comment by SmallJoker** [comment]
@Fixer-007 No, the gameplay is still OK in near to all cases. It wasn't a blocker in 0.4.x and it's still not important enough to block the next release until there's a fix available.

**Comment by nerzhul** [comment]
wow, we don't save players on a shutdown ? strange but fixeable

**Comment by nerzhul** [comment]
I pushed a PR to ensure they are saved
