### ISSUE TITLE
Send `Referer: server_address` to remote media Curl requests

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#8118]
The Remote Media server protocol currently doesn't send a `Referer:` header. I would like it to do this, because this will allow the PRMS to distinguish between various uses and abuses:

- distinguish between authorized and non-authorized Minetest servers on the HTTP/mtmediasrv side
- possibly ban clients from origins such as non-minetest servers or advertisement supported servers
- get usage statistics to improve service

If you're worried about privacy: 
- including the referer header would send the server address, not the player name, to the remote media server
- we can consider a minetest.conf option to disable this (but clients that don't sent a referer can still be on the remote media server side)
 
I can easily find how to insert a header myself in the code, but as always, I have no friggen idea how to get the std::string address from the client startup code to the httpfetch function. So, if @nerzhul or someone else knows this, please drop a hint so I can write a functional patch:

```
diff --git a/src/client/clientmedia.cpp b/src/client/clientmedia.cpp
index e3ad92db..7fcc8882 100644
--- a/src/client/clientmedia.cpp
+++ b/src/client/clientmedia.cpp
@@ -254,6 +254,8 @@ void ClientMediaDownloader::initialStep(Client *client)
                        fetch_request.post_data = required_hash_set;
                        fetch_request.extra_headers.emplace_back(
                                "Content-Type: application/octet-stream");
+                       fetch_request.extra_headers.emplace_back(
+                               std::string("Referer: " + server_address); // how to get a handle on the client address here?
                        httpfetch_async(fetch_request);
 
                        m_httpfetch_active++;
```

**Comment by nerzhul** [comment]
I'm fine with it, but you should also include the server port to be consistent :)

**Comment by sofar** [comment]
@nerzhul, yes but, how can I get a reference to it at this point of code?

**Comment by srifqi** [comment]
Hint: `client->getServerAddress()`
