### ISSUE TITLE
Maps are missing in Content store.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8120]
##### Issue type

 - Feature request
 
##### Minetest version

```
5.0.0
```

There are mods, games, texture packs, but there`s no maps. Why?

**Comment by rubenwardy** [comment]
I'm not wasting development time on this

**Comment by jastevenson303** [comment]
In the future, perhaps MT stuff may be distributed a little more nicely.

An _MT Archive Pack_ might contain and few sounds; or an entire game plus a world specific to said game.

**Comment by Warr1024** [comment]
With a little cleverness, maps could be distributed as mapgen mods.  This would also make it possible for players to upgrade to a newer version of a map and only have it affect areas that are unexplored and unmodified.

Maps generally can't be treated as completely read-only; even adventure maps would likely have some interactive content that would make sense to save state for, and the engine doesn't make any guarantees that loaded content will always stay loaded.  It's probably best to distribute maps as seed terrain for a new world, but allowing for local changes.
