### ISSUE TITLE
after_destruct callback being triggered when placing node

### ISSUE THREAD

**Issue by Yzelast** [minetest/minetest#8124]
##### Issue type

 - Bug report
 
##### Minetest version

```0.4.17.1```

##### OS / Hardware

Operating system: Elementary OS Juno
CPU: Intel core i7 4710mq

GPU model: Intel HD graphics 4600
OpenGL version: 3.0

##### Summary

Hi guys, i'm having a strange problem with the after_destruct callback.

 I want to make leaves regrow after some time, so whats happens is that after the leaf is destructed, an invisible block is placed with a metadata that stores the leaf's name and facedir, so after some time the block can place the leaf again.
The problem is, although the regrow code is working as expected, the after_destruct callback is being triggered when placing the node.

- The problem happens only with the default leaves, and work perfectly with any other block i tested(tested with default:glass, default:furnace and default:brick).
- Even overriding the entire definition with values from a block that works  still triggers the problem(i tryed to paste the brick definition inside the default:leaves and the problems persists).
- The after_dig_node callback is working fine(probably i will use that for now).

This doesn't make sense, my test functions are able to work with any block but for some obscure reason only have problems with leaves...

##### Steps to reproduce

I've attached my test mod, it adds the regrow functions, the invisible leaf block that stores the metadata, and some overridings.
In the mod you will see that the slab leaf block works normally, the brick block also works but the default:leaves doesn't.

[test.zip](https://github.com/minetest/minetest/files/2783765/test.zip)

**Comment by DS-Minetest** [comment]
On `after_place_node` `default.after_place_leaves` is called:
https://github.com/minetest/minetest_game/blob/a2c9523bce5bcefdc930ff6f14d6d94f57473be9/mods/default/nodes.lua#L728
This is after the node is placed.
`default.after_place_leaves` then calls `set_node` and ergo calls `on_destruct`:
https://github.com/minetest/minetest_game/blob/a2c9523bce5bcefdc930ff6f14d6d94f57473be9/mods/default/functions.lua#L405

This is not an engine bug. Maybe a feature request not to call `on_destruct` before the `after_place_node` callback is executed?

**Comment by Yzelast** [comment]
What a shame, so it looks like i only changed the on_timer callback but forgot to check other stuff...
Well, although i did not understand totally why the on_destruct was called now i think i can adapt my code to fix the issue.

**Comment by HybridDog** [comment]
after_dig_node probably works better for your purpose. after_destruct is called every time the node is removed (with only a few exceptions, e.g. vmanip), so almost nothing can remove the leaves.
