### ISSUE TITLE
mod-jukebox

### ISSUE THREAD

**Issue by PowerOlive** [minetest/minetest#8130]
##### Issue type
 - Documentation issue
 
##### Minetest version
0.4.17.1

##### OS / Hardware
windows lstb 2019
hp 256 g6

##### Summary
https://hosted.weblate.org/projects/minetest/mod-jukebox/
what does it related to?
how to use it?

##### Steps to reproduce
https://hosted.weblate.org/projects/minetest/mod-jukebox/

**Comment by jastevenson303** [comment]
I like your avatar.

**Comment by PowerOlive** [comment]
thank you @jastevenson303

**Comment by nerzhul** [comment]
what is that thing ? :o

**Comment by rubenwardy** [comment]
This is a third-party mod. The hosted weblate's policy is to put all translations for a project in the same repo, despite some of them being third-party mods
