### ISSUE TITLE
Entity Face Direction is "broken" in latest build.

### ISSUE THREAD

**Issue by Ryan-Nolan** [minetest/minetest#8134]
not sure how far back this goes but in the latest build the face direction of entities is broken... some entities are facing the correct way and others are not.

This is particularly noticeable in signs_lib and Item Frames mods.

**Comment by paramat** [comment]
Seems a blocker.

**Comment by pgimeno** [comment]
@Ryan-Nolan Could you be more specific as to how it is broken? One important thing to discern here is whether it happens when migrating an old world to newest MT or also when placing new objects.

It would also help if you could show a snapshot. Ideally with a step-by-step reproduction recipe.

**Comment by Ryan-Nolan** [comment]
@pgimeno connect to the creatively survival server and have a look at the signs around spawn. that will show you what i mean.

there was no migration. just an update to the server and client. I tend to update them every couple of weeks.

The specifics of the issue is that entities are facing the wrong way but only some of them.

**Comment by Ryan-Nolan** [comment]
I've just placed a sign next to a "broken" sign and found that the text entity was facing the right way... seems like to fix this currently removing all broken signs and re placing them. not sure my players are going to like that. some of them have a lot of signs.... only thing i can think of is maybe making a mod that on load removes them and re places them.

**Comment by pgimeno** [comment]
Thanks. Judging by the symptoms, this looks like it could be another instance of the problem that #7981 fixed.

The question that remains is if the broken signs were placed in the interval between the merges of #7395 (i.e. the first time you updated the server after 28 Nov 2018) and #7989 (the next server update after 24 Dec 2018) . If that's the case, the problem would be that the signs are affected by #7981, and the fix (#7989) came too late for this server, so there would be no bug remaining here, just an unfortunate timing, and there's no solution other than to replace the signs unless the signs mod itself can do anything.

**Comment by Ryan-Nolan** [comment]
Not sure on dates but what you have said sounds about right. Il close this now. thank you for you help
