### ISSUE TITLE
Disabling socks5 proxy crashes Minetest

### ISSUE THREAD

**Issue by PowerOlive** [minetest/minetest#8136]
##### Issue type
 - Bug report

 
##### Minetest version
0.17.1

##### OS / Hardware

Operating system:win10
CPU:intel i5

##### Summary
enable a system wide socks5 proxy and  close it during some time and minetest exit
##### Steps to reproduce
1. enable a system wide socks5 proxy
2. connecting to a server using minetest
3. disable it between it is intrucducting nodes and loading media
4. minetest exit

**Comment by SmallJoker** [comment]
Please provide the last few lines of your `debug.txt` file so that we can see what went wrong. Also consider starting Minetest in a Command Prompt to ensure you catch the entire crash log.

**Comment by PowerOlive** [comment]
...it crash instead of exit normally...
because of:                i just start minetest in GUI (/bin/minetest) directly and crash
so:                             it didn't write in my debug.txt
actually i use:             sourceforge.net/sscap which use Privoxy
sever connecting to:   server.minetest.one:30001 for the first time(register)
checked curl log:         empty (the cURL i use is not the one conbined with minetest,i've set it SEPRATELY)
time duration:             between intrucducting nodes and loading media

**Comment by PowerOlive** [comment]
didn't know how jieja's proxy code work...

**Comment by SmallJoker** [comment]
In this case, please open the Command Prompt and start Minetest from there. Example input:
```
G:
cd G:\Games\Minetest\bin
minetest
```
This should provide some more information.
