### ISSUE TITLE
Separate register and login

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8138]
Change logins to work like so:

```
| server list            | | address       | | port    |
|                        | | server description        |
|                        | |                           |
|                        | |                           |
|                        | |                           |
|                        | |                           |
|                        | |                           |
|                        | | username    | | password  |
|                        | | Login      | |  Register  |
```

1. To login, enter your username and password on the mainmenu and click login
2. To register, click register to open the register dialog then enter your username and password twice on the dialog
3. When clicking login, if the account doesn't exist then ~it redirects to the register dialog~ it is registered anyway
4. When attempting to register an existing username, it should give an error

This should make the per-server account more obvious

EDIT by pararmat: For #258 and #7237

**Comment by paramat** [comment]
@Ezhh your thoughts? This seems similar to your suggestion, but it doesn't need a clientside option because 'login' could be used to bypass the extra step on first join.

**Comment by rubenwardy** [comment]
This is an issue made from her suggestions

**Comment by paramat** [comment]
LOL good, it seems good to me.

**Comment by Ezhh** [comment]
The option would just be for 5.0, with this for 5.1, at which point an option is only needed if people insist it shouldn't be possible to register the old (current) way by default

**Comment by Ezhh** [comment]
I'm pretty sure this is only showing bits relevant to log in and register, and not including everything else for simplicity, rather than intended to remove other features that aren't about login/registering.

**Comment by rubenwardy** [comment]
I personally think that favourite would be better as a star icon or outline, next to server address and port

**Comment by Ezhh** [comment]
A different issue, but possibly related enough to consider. Would be nice if you could click the icon directly to make something a favourite or not, in which case that button would not be needed and the problem of how to fit them all in would be gone.

**Comment by FullTimeLinux** [comment]
I think the register and login buttons should switch places. An efficient login flow would have the login button right below the password textbox. That way if the player is using the mouse to login, they do not have to travel far.

**Comment by paramat** [comment]
Still for 5.1.0? Not sure we'll have time.

**Comment by EvolutionPixels** [comment]
This feature hasn't been implemented yet? I would like to log on to the server without constantly entering the password (sometimes it's annoying).

**Comment by EvolutionPixels** [comment]
Issue must have been abandoned. No one's even taken a future MT.

**Comment by rubenwardy** [comment]
We have a lot of things to be worked on, and we're all volunteers here. This will probably be fixed at somepoint - it's supported by multiple core devs, after all

**Comment by paramat** [comment]
A year is quite short for a MT issue =) Not abandoned, i support this too.

**Comment by EvolutionPixG** [comment]
How soon this feature request will be implemented?
So far, there has not even been any progress in implementation.

**Comment by paramat** [comment]
No one knows =)

**Comment by EvolutionPixG** [comment]
> 
> 
> No one knows =)

It might as well last forever =)

**Comment by SmallJoker** [comment]
> How soon this feature request will be implemented?

Usually it's someone who cannot stand the current situation. Myself, I'm not interested in implementing such a feature. However, taking the first post as design idea, it would only take a few lines here:
https://github.com/minetest/minetest/blob/3189e4466ba8fee6e7530822c057897f76f24436/src/client/game.cpp#L1546-L1547

and some more to find an alternative to this code:

https://github.com/minetest/minetest/blob/3189e4466ba8fee6e7530822c057897f76f24436/builtin/mainmenu/tab_online.lua#L353-L359

**Comment by benrob0329** [comment]
Alternative idea: Allow servers to define custom login forms and send a formspec on connect rather than logging-in directly (this would most likely have a special password element that would have the client salt the input). This could be used to let servers require captcha, allow logging in through other accounts/credentials (such as an IRC, Matrix, or Forum service that is hosted by the same party) and would allow servers to present more information pre-connect, such as a longer description or rules. Media could even be fetched while this form is up though, that way joining is faster.

**Comment by SmallJoker** [comment]
@benrob0329 That's not compatible with the current authentication system. The server only accepts the client as a player as soon they either logged in or registered on the server. Hence formspecs cannot be sent without a player account.

**Comment by paramat** [comment]
Lets do something simple and sufficient for now, otherwise this will never get done.
