### ISSUE TITLE
Content database: Ensure Android app playstore rating is not increased due to 'mature' content

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8143]
Posted here for visibility and inclusion in the 'project' https://github.com/minetest/minetest/projects/4 even though it may strictly be a CDB repo issue.

See forum thread https://forum.minetest.net/viewtopic.php?f=3&t=22010

If necessary, remove all content that could raise the rating.
Most users, and most potential users, of the official Android app are of ages that would be excluded by an increase in the rating.

This is the most critical time for moving players onto the official app:
* MultiCraft development has stopped, it has over a million downloads and is the most popular client used on servers, there will be a very large number of players looking to move to another app.
* Our Android app has been much improved.
* Servers are harmed by the use of bad forked apps, many are hacked to enable cheating and/or have pay-for-privilege. Servers need players to move to the official app.

~Even if there is another way around this it will take time to implement, we need to release 5.0.0 and clearing the blockers is already painfully slow. The simplest and fastest solution is to remove the 'mature' content, then we will have time to consider this further after release.~

**Comment by stujones11** [comment]
One other 'quick-fix' solution would be to simply disable the content store on android, at least until we can be sure there is no risk losing the PEGI 3 rating.

The content store can be very slow and difficult to read on many devices so maybe for now it better to use the existing [Minetest Mods](https://play.google.com/store/apps/details?id=com.rubenwardy.minetestmodmanager) if this is still working @rubenwardy ?

However, I would like to point out that I am not against removing obvious mature content from the content DB, I am merely suggesting an alternative.

**Comment by Wuzzy2** [comment]
In all seriousness: Do you aim for PEGI 3? That seems to be the nuclear option and you would have to ban a LOT of things. Even Minecraft is PEGI 7. That certainly doesn't sound like the “simplest” solution. If Minetest gets PEGI 3, but with a barren Content DB where only BlockColor can be found, that doesn't seem to help Minetest much.

> Most users, and most potential users, of the official Android app are of ages that would be excluded by an increase in the rating.

You should be more precise in this claim. What concrete effects will this have, from the user perspective? Are you talking about Google Play or other repositories? Does a increase in PEGI (or whatever) rating lead to direct censorship for our users? If yes, how would it work? As far I understood, PEGI is not a law.
I also like to point out there's also F-Droid, which doesn't care about PEGI. I have the feeling you are vastly overestimating the power of institutions like PEGI.

Also, the question is whether user-created content (in the Content DB) qualifies as “part” of Minetest. This question is also really important. If the answer is “no”, then this issue can be closed immediately! :D
I don't know if they are subject to PEGI in the first place. Minetest Game obviously will be subject to it, as it ships by default. But it seems strange that PEGI would have to rate *all of the content* in the content store to slap one big PEGI rating on Minetest.
Strictly spoken, PEGI would have to rate each of the (mostly incomplete) games available in Minetest separately. I doubt this will happen. ;-)

Anyway, I suggest to put more research in this topic first, and *understand* how PEGI and other ratings work, and how they *actually* will affect Minetest BEFORE resorting to panic attacks like wiping out the Content DB.

Off topic:
As for MultiCraft and predatory forks: You devs still haven't bothered to file a lawsuit, haven't you? Many predatory forks violate the license. What's the point of having a copyleft license if it's never enforced?

**Comment by rubenwardy** [comment]
My app uses ContentDB: https://play.google.com/store/apps/details?id=com.rubenwardy.minetestmodmanager

**Comment by stujones11** [comment]
> My app uses ContentDB

Yes, but surely there must be a way to filter that content separately?

The problem I see with content removal is who decides where to draw the line, some titles are obvious but others are less so.

**Comment by jastevenson303** [comment]
as accessible as possible is the ideal, i believe.

so pegi 3 is important.  i think it's esrb here, though; 'E' for everyone?

**Comment by stujones11** [comment]
> so pegi 3 is important.

It is only really important for google play, in order to reach the largest possible audience.

**Comment by paramat** [comment]
MC and some MT forks are PEGI 7, so i'm no longer stressing the importance of keeping PEGI 3, however it will be very helpful to keep this rating as long as possible, especially at this time where we intend to move many players to the official app..

It is still extremely important to:
Not increase the chances of a rating increase.
Make sure to avoid being rated at anything over PEGI 7.
Keep in mind that some MT forks do not have CDB so could possibly then have a way to undercut us on rating and reach a far larger audience.

Seems like adding a CDB rating system will prevent increasing the chances of a rating increase, to my surprise.
Also, we could force mature content off for Android if necessary.
So this probably modifies my request.
IRC http://irc.minetest.net/minetest-dev/2019-01-30#i_5487216

18:01 paramat    does adding a CDB rating system prevent a playstore rating increase, whatever content is on the CDB? i can't see how it would as the player would set the filter
18:03 paramat    if not, it seems better to just remove all mature content for now, to give us time to investigate and think further. rushing this for 5.0.0 is a bad idea as the risks are too high
18:12 rubenwardy it does prevent it
18:13 rubenwardy you can just hardcode the value for android
18:13 rubenwardy ie: don't let it change
18:15 paramat    it does, ah interesting
18:15 paramat    do you mean, it does prevent it, or, it prevents it if hardcoded?
18:18 rubenwardy both
18:25 paramat    ok good to know

**Comment by stujones11** [comment]
Having though about this some more, we could already be on sketchy ground with the public server-list. There is absolutely nothing stopping kids from accessing the same 'mature' content from there...

**Comment by BrianGaucher** [comment]
I know this idea doesn't fix the problem, but could mitigate or minimise it.
If we kept the CDB disabled on Google Play, for the moment (until it improves or issue is resolved...). But keep the CBD enabled in F-Droid. And in-game on the "options" page, there could be a message encouraging use of F-Droid.

Idea probably won't work, just throwing it out there, maybe someone else will get a better idea from this.

**Comment by jastevenson303** [comment]
some start as young as two.

**Comment by paramat** [comment]
Linuxdirk, when i wrote that i didn't know pegi 3 is such a low rating :) So what i mean is, 'any increase over (roughly) pegi 7' (MC).

**Comment by stujones11** [comment]
> when i wrote that i didn't know pegi 3 is such a low rating

I am pretty sure MTG would actually qualify for pegi 3 so IMO it would seem a shame to deny younger children access to the game because of optional third-party mods.

However, It looks like we do have a solution that should keep everyone happy :)

**Comment by rubenwardy** [comment]
Merged the PR. Still worth making sure that the setting is OK
