### ISSUE TITLE
Mark non-free content in Content DB

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8144]
##### Issue type
 - Feature request
 
##### Minetest version
5.0.0-dev

##### Summary
Since proprietary things haven't been fully banned from the Content DB yet …

I suggest that, after the user opted in to display non-free content in the Content DB, the entries should be marked as non-free, in a similar fashion as in the website. Currently, non-free and free content is indistinguishable.

I'm not sure how to do this yet, because space is extremely tight in the Content menu.
Maybe the text “non-free” could be added. Or the font color is changed (but that alone would not suffice).
Or maybe a little icon could be overlaid on the screenshot.
Or maybe a combination of the above.

**Comment by paramat** [comment]
Proprietary content is unlikely to be banned from the CDB later either, it's not a case of 'yet'.

If the typical user allows non-free to be displayed, why would they care which is which? (i know you care, but you're untypical). If they do care, they can visit the CDB website to check the details. Someone concerned about non-free status is likely to want to check the details of the license anyway.
So i'm not convinced it's important enough to justify doing this in the game CDB menu.

**Comment by swedneck** [comment]
A system similar to F-Droid's [Antifeatures](https://f-droid.org/wiki/page/AntiFeatures) would be very nice, although simply showing the license would also be great.

**Comment by Wuzzy2** [comment]
Well, in all fairness, it's a very minor information addition that could be visually lightweight anyway.

F-Droid's antifeatures would probably be overkill. TBH, mods with antifeatures are generally questionable, if not ban-worthy anyway. We should not allow obviously abusive mods.

**Comment by sfan5** [comment]
@rubenwardy As the person maintaining CDB code, your opinion?

**Comment by rubenwardy** [comment]
Licenses should be added to the main menu eventually. This issue is mostly side stepped by not showing non free content at all
