### ISSUE TITLE
Android: Mods no longer get included in the APK

### ISSUE THREAD

**Issue by stujones11** [minetest/minetest#8149]
##### Issue type
 - Build issue
 
##### Minetest version

```
5.0.0-dev
```
##### Summary
As of 56f22bfa5c22a89db968cf2dfc4d070b5f0e6520 mods in the main mods directory are no longer included in the apk as they previously were. It can be particularly helpful when developing for android to be able to include test mods in this way, otherwise I need to include them with the game or install them separately. See: https://github.com/minetest/minetest/pull/8019#issuecomment-459476245

@nerzhul It is pretty low priority but I would appreciate it if you could restore this functionality. 

In addition to that, it might be nice for development if the minimal game were to be included when MT game is not present. I'd have a go myself but do not understand this gradle stuff as well as you do :)

**Comment by rubenwardy** [comment]
I don't want to accidentally ship my mods in an Android release. That's less of an issue if Android is built completely in CI as an unsigned apk, and then downloaded and signed locally before releasing

**Comment by rubenwardy** [comment]
Argh, why is this so painful...

I'm trying to include the mods when in debug mode, but I can't find a way to do that in gradle. Here's my attempt:

```diff
diff --git a/build/android/app/build.gradle b/build/android/app/build.gradle
index ad31647cd..2077b56e6 100644
--- a/build/android/app/build.gradle
+++ b/build/android/app/build.gradle
@@ -28,6 +28,10 @@ android {
                        release {
                                minifyEnabled true
                                signingConfig signingConfigs.release
+                               buildConfigField "boolean", "false", includeUserContent
+                       }
+                       debug {
+                               buildConfigField "boolean", "true", includeUserContent
                        }
                }
        }
@@ -47,7 +51,7 @@ android {
        }
 }

-task prepareAssets() {
+task prepareAssets {
        def assetsFolder = "build/assets"
        def projRoot = "../../.."
        def gameToCopy = "minetest_game"
@@ -85,7 +89,7 @@ task prepareAssets() {

        file("${assetsFolder}/.nomedia").text = "";

-       if (BuildConfig.DEBUG) {
+       if (includeUserContent) {
                copy {
                        from "${projRoot}/games" into "${assetsFolder}/games"
                }
```
