### ISSUE TITLE
Documentation for register_on_player_inventory_action, register_allow_player_inventory_action has parameters in wrong order

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#8154]
##### Issue type
 - Documentation issue
 
##### Minetest version
```
5.0.0 0e306c0
```

##### Summary

The documentation in lua_api.txt for the methods `minetest.register_allow_player_inventory_action` and `minetest.register_on_player_inventory_action` appear to have swapped the order of the "action" and "inventory" parameters. The documentation says it's

`minetest.register_allow_player_inventory_action(func(player, inventory, action, inventory_info))`

but I've found that it's actually

`minetest.register_allow_player_inventory_action(func(player, action, inventory, inventory_info))`

Also, a minor issue but worth fixing while on the subject; the documentation doesn't mention the `inventory` parameter at all.

**Comment by ClobberXD** [comment]
Your copy of Minetest is possibly outdated, as this documentation issue has already been fixed in #7952

**Comment by FaceDeer** [comment]
Looks like that is indeed the case. I just grab an sfan5 dev build every once in a while, so I'm a bit behind the bleeding edge. Apologies, I'll close.
