### ISSUE TITLE
Translations do not work when started from a folder that has a subfolder named `locale`

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8158]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-cf8b0ed (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Linux 4.20.4-arch1-1-ARCH x86_64
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

##### Summary
Minetest tries to get the translations from a directory named `locale` in the directory it was started from when a directory named `locale` exists there, regardless of the directory’s content.

##### Steps to reproduce
1. Clone Minetest Game and build Minetest as described in the readme
2. Set `language` in `minetest.conf` to any other language than English to see the issue
3. `cd ~`
4. Start Minetest with `./minetest/bin/minetest` everything works as expected
5. `mkdir locale`
6. Start Minetest with `./minetest/bin/minetest` now it defaults to English

**Comment by Cool-Pan** [comment]
Note the output information of ``cmak``.
There may be an output similar to this:

```cmake
-- Locale blacklist applied; Locales used: ca;cs;da;de;dv;eo;es;et;fr;hu;id;it;ja;jbo;kn;lt;ms;nb;nl;pl;pt;pt_BR;ro;ru;sl;sr_Cyrl;sv;sw;tr;uk
```
I don't know why there have a blacklist.
If the locale you need is also in the blacklist.

You can compile ``. po`` to ``. mo`` by yourself using ``poedit``,
and put it in the ``locale`` folder.

**Comment by Linuxdirk** [comment]
The locale blacklist has nothing to do with this issue.

**Comment by Desour** [comment]
Can't reproduce. (Was probably fixed.)
