### ISSUE TITLE
Add translator comments for magic strings “needs_fallback_font” and “LANG_CODE”

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8178]
##### Issue type
 - Documentation issue
 
##### Minetest version
2ae794ac4548b13e80f16455980522d8d39da07d

##### Summary
The “translatable” strings “needs_fallback_font” and “LANG_CODE” are magic and have a special meaning. They show up in localization files but must be “translated” in a special way (i.e. no literal translation).

A translator comment should be added in the PO files because these strings are so special, so translators can see them in their tools. I know that Gettext supports such comments-for-translators, I just forgot how.

**Comment by paramat** [comment]
+1.

**Comment by SmallJoker** [comment]
How and where can such comments be added?

**Comment by Wuzzy2** [comment]
By invoking `xgettext` with the command-line parameter `--add-comments=<some_char>` and then putting a comment right before each function call of `gettext` (and friends) with `<some_char>` at the beginning. For example:

```
//~ This is a comment directed at translators
std::string foo = gettext("Hello world!");
```

Call `xgettext` with `--add-comments='~'` to collect all comments that start with the `~` character in a line before the `gettext`.

https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html#xgettext-Invocation

Congratulations! Now that you “forced” me to figure that out myself, I can do the PR myself, haha … XD

**Comment by Wuzzy2** [comment]
PR: #9510
