### ISSUE TITLE
Slippery nodes slow down the player significantly when in liquid

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#8179]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-2ae794a-2ae794a-dirty
```

##### OS / Hardware

Operating system: Windows 10

##### Summary
Slippery nodes (such as ice) cause the player to slow down significantly when in water or other liquids. The slipping effect is also lost. This could be an interesting game mechanic, but it still looks like a bug.

##### Steps to reproduce
Place water on top of a layer of ice and walk around on the ice.

**Comment by paramat** [comment]
When walking on the bottom it seems realistic (although realism isn't particularly important), wading through a meter of water with only slippery ice to get a grip on.
But yes when swimming it is weird and slows down a lot. Perhaps the detection of slippery nodes detects at a point too far down?
