### ISSUE TITLE
Handling attached objects after game restart

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#8184]
##### Issue type

 - Bug report
 
##### Minetest version

```
5.0-git-fc566e2e
```

##### Summary
This is probably engine related, minetest_game has boats and carts, this presents two problems with attachments.
1) Cart -> Restarting game detaches you from the cart -> instead it should log out both cart and user and then reattach them back during restart with keeping direction/speed
2) Boat -> Restarting game detaches you from the boat and causes player sinking in water and death -> instead it should reattach them back during restart with keeping direction/speed

**Comment by paramat** [comment]
You can get back on the boat easily, it doesn't result in death.
