### ISSUE TITLE
Cannot move diagonally forward and right while moving fast (E) on ground

### ISSUE THREAD

**Issue by archfan7411** [minetest/minetest#8185]
##### Issue type

 - Bug report

 
##### Minetest version

```
Minetest 5.0 Release Candidate 1 (also appears on older versions)
```

##### OS / Hardware

Operating system: Windows, because I'm too much of a n00b to compile it on Linux
CPU: Intel i5-5200U

GPU model: Intel Integrated GPU
OpenGL version: 4.4, I believe

##### Summary

When the player sprints forward by pressing the forward and fast key, they are able to move diagonally to the left, but not to the right.
##### Steps to reproduce

Walk forward and press E (by default) to sprint. Then, move diagonally by pressing the left or right keys in addition to sprinting forward. Moving diagonally to the left does work, while moving diagonally to the right has no effect and the player continues on a forward course (at least on my machine.)

**Comment by tacotexmex** [comment]
Confirmed on macOS 10.13.6. CPU: Intel Core i5, GPU: Intel HD Graphics 4000, OpenGL: 2.1.

**Comment by ClobberXD** [comment]
Can't reproduce - moving diagonally works fine in all four directions. I tested with MTG + sprint mod (by gunshipPengin) at commit 809cb9fc0bcf89d247f509a42351db102a0e278c

**Comment by archfan7411** [comment]
Ah, I meant "fast mode", as in the functionality enabled by the `fast` priv, not a sprint mod. Not sure if it makes a difference, but that might explain the inability to reproduce.

**Comment by NathanSalapat** [comment]
I just tested with a build from this morning, I can move left and right without any issues.
Linux Mint 19.1 Minetest Build 0d0875fc, vanilla MTG.

**Comment by Linuxdirk** [comment]
Let me just throw in [n-key rollover](https://en.wikipedia.org/wiki/Rollover_(key)#n-key_rollover) as possible root cause to consider.

**Comment by archfan7411** [comment]
> Let me just throw in [n-key rollover](https://en.wikipedia.org/wiki/Rollover_(key)#n-key_rollover) as possible root cause to consider.
Interesting, and yet my keyboard handles Blender's shortcuts (e.g. Ctrl-Alt-Shift-C) just fine.

**Comment by jastevenson303** [comment]
depends on the keyboard.

**Comment by paramat** [comment]
Confirmed on my setup (Linux Ubuntu) however perhaps not surprising as 3 controls are being held down, i get this issue with other combinations of 3 keys.
Note if you start by walking diagonally right then press E the speedup doesn't happen.
I expect it's a hardware issue.

**Comment by pgimeno** [comment]
Depends on the keys used, too. It's not all combos of 3 keys, it's certain combos. Of course, shift keys are designed to try to minimize the risk of ghosting, because they are often used in combination with other keys.

You can easily test with the letters in particular in any editor, including this box, which ones you can hold and get them to appear. For example, when I press W, D and E, the E doesn't appear (which is the issue).

My solution was to remap Run/Special to CTRL. Not overly comfortable, but manageable. TAB normally works too, but to me it's more uncomfortable than CTRL.

There are also keyboards designed for gaming with "antighosting".

**Comment by archfan7411** [comment]
Ah, so it's entirely a hardware issue. Thanks for the help!

**Comment by jastevenson303** [comment]
also some keyboards of higher quality not necessarily designed for gaming.

**Comment by benrob0329** [comment]
This is definitely related to how your keyboard matrix is set up. Not a Minetest issue.

**Comment by archfan7411** [comment]
In that case I'll close it, thanks again.
