### ISSUE TITLE
Some formspec elements don't respect length of translated strings

### ISSUE THREAD

**Issue by weqqr** [minetest/minetest#8188]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-rc1
```

##### OS / Hardware
Operating system: Windows 7 x64
CPU: Intel Core i3-2120

##### Summary
Translated text gets clipped if it is larger than original. This makes client-side translations hard to use for wordy languages like Russian.

##### Steps to reproduce
1. Install this mod:
    `init.lua`
    ```lua
    local S = minetest.get_translator()

    minetest.register_chatcommand("test", {
    	func = function(name, param)
    		local text = S"Hello"
    		local fs = "size[2,1.5]" ..
    			"label[0,0;" .. text .. "]" ..
    			"button[0,0.5;2,1;whatever;" .. text .. "]"
    		minetest.show_formspec(name, "test", fs)
    	end,
    })
    ```
    `locale/stuff.ru.tr`
    ```
    Hello=Здравствуйте
    ````
2. Set `language = ru` in `minetest.conf`.
2. Run `/test` command.

##### Expected result:
![expected](https://user-images.githubusercontent.com/4698994/52431877-287dfc00-2b1a-11e9-9f7b-8ec2a94b2096.png)

##### Actual result:
![actual](https://user-images.githubusercontent.com/4698994/52431918-477c8e00-2b1a-11e9-900b-48ad797361c6.png)

**Comment by sfan5** [comment]
This was actually already fixed by 2c9edefde3d941b1efa5c93a087814d6bc3509e6.
