### ISSUE TITLE
Gamepad Support is Wonky!

### ISSUE THREAD

**Issue by McBean56545** [minetest/minetest#8191]
##### Issue type

-Bug report
 
##### Minetest version

```0.4.17.1

```

##### OS / Hardware

Operating system:Windows 10 Home
CPU:Intel core i3 7th gen

GPU model:
OpenGL version:

##### Summary

Gamepad support for the game is terrible! The left stick should be for walking/ basic movement (That part is perfectly fine) the right stick should be used for aiming/looking around, A should be mapped to jump, B should be mapped to drop, X should be mapped to inventory, Y should be for using noclip, down on Dpad should be mapped to fast move, Up on Dpad should be the flight toggle, bumpers should be used for selecting blocks, and triggers should be used for breaking(RT) and placing blocks(LT). The Menu button should bring up the pause menu.
##### Steps to reproduce

Plug in an Xbox Gamepad into your PC, enable gamepad support on the advanced menu, and play a vanilla Minetest world. I'm ok if this gets put on the back burner for a while, but don't forget it. I play a huge chunk of my games using gamepad.

**Comment by McBean56545** [comment]
It censored my Minetest version It should be 0.4.17.1

**Comment by Calinou** [comment]
Having default bindings for gamepads would require the engine to support binding an action to multiple keys ("keys" also being joystick buttons).

**Comment by rubenwardy** [comment]
Duplicate: #4153

**Comment by rubenwardy** [comment]
> Gamepad support for the game is terrible! The left stick should be for walking/ basic movement (That part is perfectly fine) the right stick should be used for aiming/looking around, A should be mapped to jump, B should be mapped to drop, X should be mapped to inventory, Y should be for using noclip, down on Dpad should be mapped to fast move, Up on Dpad should be the flight toggle, bumpers should be used for selecting blocks, and triggers should be used for breaking(RT) and placing blocks(LT). The Menu button should bring up the pause menu.

This is the case on *my* Xbox controller, but it turns out that the bindings per-controller and per-platform vary drastically
