### ISSUE TITLE
feature request: flowing lava antedote

### ISSUE THREAD

**Issue by sudoman** [minetest/minetest#82]
Just like lava can spread over far distances if you place a few buckets-worth next to each other, it would be good if you could 'delete' the lava by placing antidotes side by side in the surface of the lava. Like lava or water, it would spread, then replace the lava source with air.

This would be very useful for when a griefer covers the entire map with lava using a few buckets worth of the stuff.

**Comment by Novatux** [comment]
This should be into minetest_game; moreover, you can use worldedit or a similat mod to remove lava if a griefer added it. I also reckon this is partially fixed since lava is no longer renewable.
