### ISSUE TITLE
Player doesn't autojump when autoforwards is enabled

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8201]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-d5456da6
```

##### OS / Hardware
Operating system: Ubuntu 18.10
CPU: AMD Ryzen 7 2700

##### Summary
When autoforwards is enabled automatic jumping doesn't work

##### Steps to reproduce
walk into a node with autoforwards and autojump enabled.

**Comment by SmallJoker** [comment]
#8200 merged
