### ISSUE TITLE
Unzip forces all files to lowercase

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#8203]
When installing a mod through the client content browser, all files are lowercased. I discovered this after installing technic, which uses the file names `LV`, `MV`, and `HV`, and subsequently broke due to trying to find those filepaths. It can also be seen on license/readme files which should be `README.md` or `LICENSE.txt` but are turned into `readme.md` or `license.txt` respectively. The ContentDB direct download does not exhibit this behavior, so the issue is in Minetest.

**Comment by paramat** [comment]
This?
https://github.com/minetest/minetest/blob/572ba83b3084e3d3abd294acb914746d29822a98/src/script/lua_api/l_mainmenu.cpp#L752

**Comment by rubenwardy** [comment]
Maybe this is the issue? https://github.com/minetest/minetest/commit/6ae14ab619df467f6bd998c8b9752fb268813628

**Comment by paramat** [comment]
I might test that.

**Comment by sofar** [comment]
This can now be closed?

**Comment by GreenXenith** [comment]
Yep.

**Comment by paramat** [comment]
I forgot to close it.
