### ISSUE TITLE
Please configure AppVeyor

### ISSUE THREAD

**Issue by DartPower** [minetest/minetest#8204]
Please configure AppVeyor and function to download a Artifacts
Im cant understand normally steps to compile and this is too hard for me. (Im not a coder, just anykey-guy, but this is really hard lol)

Currently builds im know can download here:
https://minetest.kitsunemimi.pw/builds/
But this is obsolete.

Please, can you made a buildbot or use the AppVeyor?

**Comment by rubenwardy** [comment]
We already have CI builds for Windows using gitlab. Check the builds section of the forum

**Comment by rubenwardy** [comment]
https://gitlab.com/minetest/minetest/pipelines
https://forum.minetest.net/viewtopic.php?f=42&t=17439
