### ISSUE TITLE
Enabled modpacks arent green when entering config

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#8205]
Enabling a modpack will turn it green, but upon saving and returning to the configuration menu, the modpack has lost the color (but is still enabled).
![image](https://user-images.githubusercontent.com/24834740/52524841-70a23900-2c56-11e9-8539-146e40535264.png)

**Comment by random-geek** [comment]
See #8190 
; )

**Comment by GreenXenith** [comment]
Then I guess this can be closed once that is merged :P

**Comment by SmallJoker** [comment]
a809f73
