### ISSUE TITLE
Packets time out in singleplayer

### ISSUE THREAD

**Issue by random-geek** [minetest/minetest#8207]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17.1
5.0.0dev
```

##### OS / Hardware

Operating system: Windows 10
CPU: Eight-core processor, 3.00 GHz

##### Summary

Sometimes, for seemingly no reason, singleplayer will suddenly become unplayably laggy. Playing on a server is also affected. By laggy, I mean mapblocks take a ridiculously long time to load, commands take minutes to execute, and opening the inventory is not even usually an option. This is the worst-case scenario; usually it starts out mild and slowly grows to unplayability. To be clear, I have a good, fast computer, a reliable network connection, and not many other open processes. Rebooting the computer seems to fix the problem temporarily, but it still happens frequently enough for it to be annoying. This happens on 0.4.xx as well as the latest development build.
I noticed these types of error messages in mass quantity when I turned on verbose logging, perhaps they have something to do with it:

```
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=19
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=40
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=0, seqnum=150
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=26
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
VERBOSE[ConnectionSend]: con(10112/2)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=2, channel=2, seqnum=5
VERBOSE[ConnectionSend]: con(10112/2)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=2, channel=2, seqnum=6
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=20
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=21
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=27
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
VERBOSE[ConnectionSend]: con(10112/2)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=2, channel=2, seqnum=7
VERBOSE[ConnectionSend]: con(10056/1)RE-SENDING timed-out RELIABLE to 127.0.0.1(t/o=3): from_peer_id=1, channel=2, seqnum=41
VERBOSE[ConnectionReceive]: con(10112/2)WARNING: ACKed packet not in outgoing queue
```

I doubt this is caused by 968ce9af598024ec71e9ffb2d15c3997a13ad754 as it seems to happen on any version. I'm guessing this will be marked as an unconfirmed bug since it is essentially un-reproducible, but I thought I would report it anyways.

**Comment by Fixer-007** [comment]
Hmm, does switching pages in creative mode during those have ~1 sec lag for you as well?

**Comment by SmallJoker** [comment]
Persists in 5.0.1.
https://forum.minetest.net/viewtopic.php?f=6&t=22975 (Windows, likely x86_64)
https://forum.minetest.net/viewtopic.php?f=6&t=22869 (arm64-v8a)

**Comment by sfan5** [comment]
Please re-test with git master.
