### ISSUE TITLE
Players's breath can be greater than breath_max

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8212]
##### Issue type
 - Bug report
 
##### Minetest version
```
a809f7361e8a7232b3c9ec241be5adcae96b3b2d
```

##### Summary
When a player's max. breath is reduced below their current breath, the current breath is not capped at the max. breath value. This is a bug because the documentation says:

```
 * `set_breath(value)`: sets players breath
     * values:
         * `0`: player is drowning
         * max: bubbles bar is not shown
         * See [Object properties] for more information
```
So mods that only check if `breath` is equal to `max` (rather than equal or greater) are screwed.

This is also inconsistent with HP. When max. HP are reduced below your current HP, your current HP get reduced as well.

##### Steps to reproduce

Step 1: Use the test mod from #8211 to make your current and max hp/breath easily visible
Step 2: Use `luacmd`
Step 3: `/lua me:set_properties({breath_max=100})`
Step 4: `/lua me:set_breath(100)`
Step 5: `/lua me:set_properties({breath_max=20})`

You now have 100 breath, which is more than your max. breath.

Tested in singleplayer only.

**Comment by ClobberXD** [comment]
#8264

**Comment by ClobberXD** [comment]
#8264 underwent a couple of major changes, and did nothing to fix this issue in its final revision. My bad. Here's a token of my apologies: #8493
