### ISSUE TITLE
Player damage sound is played when falling from a cliff w/ damage disabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8214]
##### Issue type
 - Bug report
 
##### Minetest version
```
a809f7361e8a7232b3c9ec241be5adcae96b3b2d
```
##### Summary
If you fall from a cliff and drop on a node, you alway hear the player damage sound (`player_damage.ogg`), even if damage is actually disabled.

##### Steps to reproduce
1. Disable damage
2. Start Minetest Game (which contains `player_damage.ogg` but not `player_falling_damage.ogg`)
3. Turn on sound
4. Fall from a cliff on a solid node

**Comment by paramat** [comment]
Yes noticed this too. The damage sound is played from the engine.

**Comment by pauloue** [comment]
Is there any way for the client to know if the server has damage disabled?

**Comment by SmallJoker** [comment]
@pauloue No, that's only sent to the server list. The server will just ignore damage packets and skip adding the health HUD. A solution here would be to automatically give players the armor group `immortal` as soon they join.
