### ISSUE TITLE
Climbing 1 thick water columns is problematic

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#8216]
##### Issue type

 - Bug report
 
##### Minetest version

```
a809f736
```

##### Steps to reproduce

Create this 1 thick water column elevator https://i.imgur.com/f00NJbU.png , try swimming up, it is nearly impossible and jerky. Is this a problem?

**Comment by Fixer-007** [comment]
Even walking into this column is very hard and movement feels weird in general.

**Comment by LoneWolfHT** [comment]
Is pitch swimming enabled? If you hold down the space bar you will move in the direction your 'head' is pointing when in water

**Comment by Fixer-007** [comment]
I'm talking from avg Joe standpoint, who does not what that is and swims as in 0.4

**Comment by Fixer-007** [comment]
I'm talking from avg Joe standpoint, who does not know what is that and swims as in 0.4

**Comment by LoneWolfHT** [comment]
IIRC pitch swimming is disabled by default?

**Comment by DS-Minetest** [comment]
I can't reproduce the problem. Swimming up is easily possible, with pitch move en- and disabled.

**Comment by Fixer-007** [comment]
Here is the demo of my struggles: https://imgur.com/a/CPsHJLq

**Comment by paramat** [comment]
Can't reproduce.
Looks like you may have pitch move (L) enabled, that will certainly make it weird as 'up' key will then make you move out of the water if you are not looking horizontally.
