### ISSUE TITLE
Player regains a little breath when rejoining game into ignore

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8217]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-a809f736
```

##### OS / Hardware

Operating system: Ubuntu 18.10
CPU: AMD Ryzen 7 2700

##### Summary
(When the background is grey I've just joined the game)
![water](https://user-images.githubusercontent.com/28972859/52536477-e7e7d380-2d0f-11e9-876e-bd72f655b166.gif)

##### Steps to reproduce
Leave the game while underwater and half out of breath. Then rejoin and watch your bubble meter. Might need to enable some heavy mods

**Comment by Wuzzy2** [comment]
Random guess for the reason: Player client first thinks it spawns in `ignore` before it loaded the liquid, and `ignore` does not deal drowning damage.

Solution (if my guess is true): Neither increase or decrease the breath meter while player is stuck in `ignore`.

**Comment by SmallJoker** [comment]
Following code needs checking against `ignore`
https://github.com/minetest/minetest/blob/ba5a9f2b361a2fa01d1a3396999a5833983c0f4a/src/content_sao.cpp#L1017-L1021

**Comment by paramat** [comment]
Grey background means player is in ignore.
