### ISSUE TITLE
Add ingame setting to change pitch toggle key

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8219]
##### Issue type
 - Feature request

Right now I don't think there is any way to change the pitch toggling key?

**Comment by Wuzzy2** [comment]
Sadly, the controls menu is full.
It needs a complete redesign to support any new key.

Alternatively, we could sacrifice a less important key in the controls menu and replace it with the pitch toggle key. I would vote for Cinematic Mode.

**Comment by DS-Minetest** [comment]
>I would vote for Cinematic Mode.

[Cinematic Mode has no default value.](https://github.com/minetest/minetest/blob/626b0b7e6a61d329e2b94a0f1ca15db6625b5e5d/src/defaultsettings.cpp#L93)

**Comment by paramat** [comment]
Yes replace 'toggle cinematic' or 'toggle fog', both of which have no reason to be on the in-game edit keys menu.

**Comment by srifqi** [comment]
#8314 (?)

**Comment by paramat** [comment]
Yes, done.
