### ISSUE TITLE
I compiled Minetest but i cant access server list 

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#8225]
##### Bug report
I compiled Minetest but i cant access server list, i think that networking has a bug
 
##### Minetest version
Minetest 0.4.17

**Comment by Calinou** [comment]
Did you have libcurl installed when you were compiling Minetest? It is required to fetch the server list.

**Comment by masrourmouad** [comment]
libcurl3  is installed

**Comment by sfan5** [comment]
Post output of `./bin/minetest --version`

**Comment by masrourmouad** [comment]
#### Cmake
*** Will build version 0.4.17.1 ***
-- Using GMP provided by system.
-- Using bundled JSONCPP library.
-- Could NOT find LuaJit (missing:  LUA_LIBRARY LUA_INCLUDE_DIR) 
-- LuaJIT not found, using bundled Lua.
-- cURL support enabled.
-- GetText disabled.
-- Sound enabled.
-- Freetype enabled.
-- ncurses console enabled.
-- Could NOT find PostgreSQL (missing:  PostgreSQL_LIBRARY PostgreSQL_INCLUDE_DIR PostgreSQL_TYPE_INCLUDE_DIR) 
-- PostgreSQL not found!
-- LevelDB not found!
-- Redis not found!
-- SpatialIndex not found!
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done


#### output of ./bin/minetest --version
Minetest 0.4.17.1 (Linux)
Using Irrlicht 1.8.1
Build info: VER=0.4.17.1 BUILD_TYPE=Release RUN_IN_PLACE=1 USE_GETTEXT=0 USE_SOUND=1 USE_CURL=1 USE_FREETYPE=1 USE_LUAJIT=0 STATIC_SHAREDIR="."

**Comment by rubenwardy** [comment]
What's the output of running MT and viewing the list?

**Comment by masrourmouad** [comment]
the output of running MT and viewing the list is: 
ERROR[AsyncWorker-0]: servers.minetest.net/list?proto_version_min=25&proto_version_max=32 not found (Timeout was reached) (response code 0)

**Comment by sfan5** [comment]
Can you access the server list in your browser via either http://servers.minetest.net/ or https://servers.minetest.net ?

**Comment by masrourmouad** [comment]
yes
