### ISSUE TITLE
Check if minetest.conf.example needs updating

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8231]
Needed due to changes to settingtypes.txt.

**Comment by Wuzzy2** [comment]
Fixed with 5eb2f0bb02f842b1a4b9fce60de5dbf49c08e571?

**Comment by paramat** [comment]
Yes, but issue is a reminder in case commits are added before release that change settingtypes.txt.
Currently no update needed as of 7a0e52acd65e7097977c924f26b387ec3da9baac

**Comment by Wuzzy2** [comment]
What about a string freeze? Or is it too early?

**Comment by paramat** [comment]
Update is now needed due to changes to settingtypes.txt.

**Comment by paramat** [comment]
Update done, leaving open as a reminder in case further updates are needed.

**Comment by paramat** [comment]
Closing as no updates are needed and a reminder to check is not really necessary.
