### ISSUE TITLE
Adding another DBMS for mods

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#8234]
##### Issue type
 - Feature request

##### Summary
Going in the direction of [this issue](https://github.com/minetest/minetest/issues/380), I would like to ask for a NoSQL DBMS to be bundled within Minetest to offer a better, ideally JSON based mod storage.
I came across [RethinkDB](https://www.rethinkdb.com) and Mongo. I think we should include one of them to make modding easier. I would advocate for RethinkDB, as it is more feature rich than Mongo and offers real-time query "streams".

**At the very least, modders need to be able to access at least one modern DBMS, to give queries a reasonable execution speed**

**Comment by rubenwardy** [comment]
:-1: for support for such specialised databases, use `require()` and a lua library instead. MongoDB is proprietary and should *never* be added to Minetest

The engine should, however, give support for saving arrays of structs or JSON blobs, but not using a bloated backend

**Comment by nerzhul** [comment]
Hello,
we don't use nosql here. MongoDB will not be added.
you already have mod storage where you can store any data you want to store as a NoSQL store (key,value store)

**Comment by rubenwardy** [comment]
Mod storage isn't appropriate for large amounts of data - it writes everything out as one JSON file, and storing arrays requires you to use minetest.serialize

**Comment by nerzhul** [comment]
@rubenwardy we can use DB to store the json file, also NoSQL is just generally json file with some indices on some json fields...

**Comment by appgurueu** [comment]
There are countless advantages of using a DBMS.
Those systems usually *dramatically* optimize queries.
When using JSON, I have to *rewrite* the entire JSON myself when storing new data. A DB is far faster.
And now when it comes to sorting, primary keys and grouping, you will get lost with pure Lua and JSON files.

In general, my point of view is that MT needs a bunch of good libraries builtin. I only think that a DBMS is one of the most important ones.

What does an application(also a mod) need ? It needs a way to store the data *in an efficient and clean manner*. This is what the DBMS would be for.

Reject this if you think modders should struggle on with as simple tasks as creating an efficient & reliable scoreboard.

LMD

**Comment by rubenwardy** [comment]
Minetest is not a cloud program. A cloud DB like Rethink would be over-engineering

There should be a better way to store tabular data as mod storage sucks for that, but a complex DBMS is not it

**Comment by nerzhul** [comment]
we don't need to be stuck with cloud technologies. Regular RDBMS are sufficient, we don't have hundreds of GB data

**Comment by paramat** [comment]
> At the very least, modders need to be able to access any DBMS

Isn't supporting all DBMS too much to ask?

**Comment by appgurueu** [comment]
I apologize for my misuse of the english language. What I intended to say was that they should be able to access a single DBMS, my bad.

**Comment by paramat** [comment]
Sorry, misunderstood, 'any' can indeed somewhat mean 'at least one'.

**Comment by ShadMOrdre** [comment]
I would also support the inclusion of some engine based mechanism for modders to access the underlying DB engine.  By using the DB of the underlying server, whether SQLite, Redis, LevelDB, or PostgreSQL, there should be an engine/LUA API handler to allow modders to create and store data.  I would not advocate using this mechanism to access MT data, but simply to use the DB engine as a, perhaps, more robust solution to mod_storage.
