### ISSUE TITLE
Change entity/node textures per-player

### ISSUE THREAD

**Issue by vladtcvs** [minetest/minetest#8235]
Feature request
 
Now all players always see the same texture for nodes and entities. In some cases, it would be useful to modify texture, which player see to represent different states of player - first player see 'usual' texture, and other player see the same object (node or entity) with other texture.

Example: in LOTT and it forks there are 'nazgul' mobs. Usually they have texture of black person in cloak. But it would be interesting, if in some cases player can see another texture, while other players still see black cloak.

**Comment by Extex101** [comment]
Yeah I wanted a mod that does this
Where, when holding a certain item it makes the world look brighter and more beautiful.

**Comment by Moth-Tolias** [comment]
why was this closed?

**Comment by Extex101** [comment]
"No core dev support long term"
