### ISSUE TITLE
Less reach in 3rd person view mode

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8238]
##### Issue type
 - Bug report
 
##### Minetest version
```
0.4.17.1 (+?)
```

##### Summary
https://forum.minetest.net/viewtopic.php?f=6&t=20929
"I don't know how to describe this well but uh, I used the 3rd person view and for some reason, I can not place anything above, can only place something one block apart in front of me, and can not break anything below unless I am flying. Perhaps I accidentally changed some settings but I don't recall altering the 3rd person view. Any thoughts?"

##### Steps to reproduce
Set FOV to something like 100 and enter 3rd person mode ingame

**Comment by jastevenson303** [comment]
oh wow, so that's why!  i always use ahigh fov like 100+ and wondered why i
could select anything easily while in third person.

cue someone explaining how "high fov values are not supported so not a bug
:thumbsdown:"

**Comment by ClobberXD** [comment]
I can confirm. It's probably because the range is calculated from the camera instead of from the player. So if the camera is in 3rd person mode, the distance between the camera and player is approx. 3 nodes, and so the resultant reach is only within 1 node ahead.

**Comment by srifqi** [comment]
It's been mentioned before. I thought that it was intented.
https://github.com/minetest/minetest/pull/7865#issuecomment-449850807

**Comment by srifqi** [comment]
Here's the fix for both mouse and touch input. We use player as starting point instead of camera when pointing node so that we have same pointing area on both camera modes.
```diff
diff --git a/src/client/game.cpp b/src/client/game.cpp
index 28f6a90ed..6ae571452 100644
--- a/src/client/game.cpp
+++ b/src/client/game.cpp
@@ -2957,10 +2957,15 @@ void Game::processPlayerInteraction(f32 dtime, bool show_hud, bool show_debug)
 		hlist ? hlist->getItem(0).getDefinition(itemdef_manager) : itemdef_manager->get("");
 
 	v3f player_position  = player->getPosition();
+	v3f player_eye_position = player_position + player->getEyeOffset();
 	v3f camera_position  = camera->getPosition();
 	v3f camera_direction = camera->getDirection();
 	v3s16 camera_offset  = camera->getOffset();
 
+	if (camera->getCameraMode() == CAMERA_MODE_FIRST)
+		player_eye_position += player->eye_offset_first;
+	else
+		player_eye_position += player->eye_offset_third;
 
 	/*
 		Calculate what block is the crosshair pointing to
@@ -2977,11 +2982,11 @@ void Game::processPlayerInteraction(f32 dtime, bool show_hud, bool show_debug)
 	core::line3d<f32> shootline;
 
 	if (camera->getCameraMode() != CAMERA_MODE_THIRD_FRONT) {
-		shootline = core::line3d<f32>(camera_position,
-			camera_position + camera_direction * BS * d);
+		shootline = core::line3d<f32>(player_eye_position,
+			player_eye_position + camera_direction * BS * d);
 	} else {
 	    // prevent player pointing anything in front-view
-		shootline = core::line3d<f32>(camera_position,camera_position);
+		shootline = core::line3d<f32>(camera_position, camera_position);
 	}
 
 #ifdef HAVE_TOUCHSCREENGUI
@@ -2989,10 +2994,9 @@ void Game::processPlayerInteraction(f32 dtime, bool show_hud, bool show_debug)
 	if ((g_settings->getBool("touchtarget")) && (g_touchscreengui)) {
 		shootline = g_touchscreengui->getShootline();
 		// Scale shootline to the acual distance the player can reach
-		shootline.end = shootline.start
-			+ shootline.getVector().normalize() * BS * d;
-		shootline.start += intToFloat(camera_offset, BS);
-		shootline.end += intToFloat(camera_offset, BS);
+		shootline.end = player_eye_position +
+			shootline.getVector().normalize() * BS * d;
+		shootline.start = player_eye_position;
 	}
 
 #endif
```
