### ISSUE TITLE
Checkbox click position way off

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8242]
##### Issue type
 - Bug report
 
##### Minetest version
This affects current head, but it's old. It's affecting 0.4.16 as well. I haven't tried older versions.

```
Minetest 5.0.0-dev-568540f8e (Linux) AND 0.4.16
Using Irrlicht 1.8.4
BUILD_TYPE=Release
```

##### OS / Hardware
Debian GNU/Linux 9.6 (stretch)
Irrlicht is the stock version shipped with the distribution. Same for all other relevant libs.

EDIT: Reproduced on both stretch and wheezy, with WindowMaker, IceWM and FVWM. (FVWM only tested on wheezy, not on stretch; the rest are tested in both). With TWM the position is a bit lower but also off.

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce 8600 GT/PCIe/SSE2
OpenGL core profile version string: 3.3.0 NVIDIA 340.107
```

##### Summary
When trying to click on a checkbox, when clicking under about half the checkbox, the checkbox below is the one affected instead of the one the mouse is over.

The images will probably illustrate it better. They were taken while clicking and holding the button without moving the mouse.

![checkbox-good](https://user-images.githubusercontent.com/4267396/52902073-f3edfc80-320b-11e9-8a77-9cab5cd32b6d.png)
^ This is the last "good" cursor position. It affects the correct checkbox.

![checkbox-bad](https://user-images.githubusercontent.com/4267396/52902075-f6e8ed00-320b-11e9-994e-62fc41556d8a.png)
^ One pixel below that, the cursor affects the next checkbox.

**Comment by stujones11** [comment]
I can confirm this, also using Debian stretch + LXDE

**Comment by paramat** [comment]
Confirmed on Linux Ubuntu. Maybe a simple fix?

**Comment by archfan7411** [comment]
Confirmed on Windows 10, will try on Arch Linux later. Hazarding a guess that perhaps the pointing location is calculated from the center of the mouse icon instead of the pointer?

**Comment by SmallJoker** [comment]
It would be possible to play a bit with the rectangle coordinates for Irrlicht to draw the checkbox:
https://github.com/minetest/minetest/blob/291b2446f19209be20c4b7fb7587da44330429fd/src/gui/guiFormSpecMenu.cpp#L440-L446

**Comment by paramat** [comment]
Need to test if screensize affects this offset.

**Comment by paramat** [comment]
Screensize doesn't seem to affect it.
Also happens in advanced/all settings checkboxes.

**Comment by Fixer-007** [comment]
Can confirm on win7 / 291b2446

**Comment by pgimeno** [comment]
It seems to also affect the labels. I'm more and more convinced it's not an Irrlicht bug.

**Comment by pgimeno** [comment]
This patch seems to mostly fix it for me, though I'm not fully convinced about its correctness. I'm not familiar with the formspec code. Even with the patch, there seems to be a mismatch between the clipping rectangle and the mouse sensitivity area, and I see no obvious reason for such a mismatch in that part of the code.

```diff
diff --git a/src/gui/guiFormSpecMenu.cpp b/src/gui/guiFormSpecMenu.cpp
index 6c404728f..8e9b7b7ed 100644
--- a/src/gui/guiFormSpecMenu.cpp
+++ b/src/gui/guiFormSpecMenu.cpp
@@ -438,12 +438,15 @@ void GUIFormSpecMenu::parseCheckbox(parserData* data, const std::string &element
 			fselected = true;
 
 		std::wstring wlabel = translate_string(utf8_to_wide(unescape_string(label)));
-		s32 spacing = Environment->getSkin()->getSize(gui::EGDS_CHECK_BOX_WIDTH) + 7;
+		s32 cb_size = Environment->getSkin()->getSize(gui::EGDS_CHECK_BOX_WIDTH);
+		s32 spacing = cb_size + 7;
+
+		const core::dimension2d<u32> font_size = m_font->getDimension(wlabel.c_str());
 
 		core::rect<s32> rect = core::rect<s32>(
-				pos.X, pos.Y + ((imgsize.Y / 2) - m_btn_height),
-				pos.X + m_font->getDimension(wlabel.c_str()).Width + spacing,
-				pos.Y + ((imgsize.Y / 2) + m_btn_height));
+				pos.X, pos.Y + imgsize.Y / 2 - (std::max(font_size.Height, (u32)cb_size) + 1) / 2,
+				pos.X + font_size.Width + spacing,
+				pos.Y + imgsize.Y / 2 + (std::max(font_size.Height, (u32)cb_size) + 1) / 2);
 
 		FieldSpec spec(
 				name,
```

Explanation of the patch: use half the font size above and half the font size below the Y position (using ceiling division to divide by two), unless the checkbox is bigger, in which case use half the checkbox size (again using ceiling division).

**Comment by paramat** [comment]
f409f4476539f32dcce3ff6832be4bc48bd25634
