### ISSUE TITLE
Rename "Configure" button to a less ambiguous name

### ISSUE THREAD

**Issue by archfan7411** [minetest/minetest#8243]
##### Issue type

 - Feature request
 
##### Minetest version

```
any
```

##### Summary

I'd like to suggest renaming the "Configure" button on the singleplayer tab to "Enable/Disable Content" or something similar and shorter. The reasoning behind this is:
- That's all the configure menu is used for.
- I recently had to assist a user who thought once a mod was installed, it was automatically enabled.

Thank you for your time.

**Comment by paramat** [comment]
It will need to be shorter.

**Comment by archfan7411** [comment]
How about "Select Mods"? or perhaps "Enable Mods"?

**Comment by pauloue** [comment]
This will be especially necessary when we get per-world settings. Just "Mods" would be best I think.

**Comment by archfan7411** [comment]
> Just "Mods" would be best I think.

I'm worried players would confuse it with the Content tab. But it might be the best option.

**Comment by paramat** [comment]
Or maybe 'World Mods'?

**Comment by CoderForTheBetter** [comment]
'Toggle Mods'?

**Comment by ClobberXD** [comment]
Toggle is the right word. I also agree that Configure is confusing to new users.

**Comment by LoneWolfHT** [comment]
Manage Mods?

**Comment by archfan7411** [comment]
> Manage Mods?

That might imply installing/uninstalling mods...

**Comment by LoneWolfHT** [comment]
> > Manage Mods?
> 
> That might imply installing/uninstalling mods...

Yeah. I guess. 'Toggle Mods' sounds like you're enabling/disabling all mods though.
This is hard lol

**Comment by archfan7411** [comment]
> 'Toggle Mods' sounds like you're enabling/disabling all mods at once though.

"Select Mods"? (suggested earlier)

**Comment by DS-Minetest** [comment]
"Manage mods" sounds as if it's the mods by themselves that you manage.
Also it's not better than "Configure mods".

I like the current "Configure".
Other things to configure at the world might perhaps come later (like world specific settings).
You just need to make the player read some instructions.

"Select Mods" sounds good.

**Comment by archfan7411** [comment]
> Other things to configure at the world might perhaps come later (like world specific settings).

True. If that's on the horizon then this issue can be closed.

> You just need to make the player read some instructions.

Only a relatively small percentage of them would... I think the issue would still be in place.

**Comment by Linuxdirk** [comment]
> Toggle is the right word.

Actually no. Toggling generally means _switching a state of something by using the same signal_. This is not what is done here. By klicking the button you open the interface where you can select and unselect mods to load for the specific world. You don't toggle anything with the button nor you open an interface where you toggle something.

**Comment by LoneWolfHT** [comment]
'World Mods' could work (Suggested by paramat)
Why not let the player choose mods when creating a world?
![image](https://user-images.githubusercontent.com/28972859/52962712-d1b2c680-3352-11e9-930d-0b0d3ddb0b38.png)

**Comment by rubenwardy** [comment]
This should not be done for this release, it's about time to stop changing strings

**Comment by archfan7411** [comment]
> This should not be done for this release, it's about time to stop changing strings

Yeah, I didn't mean to propose this as a suggestion for 5.0, but later. I'm aware the feature freeze has passed.

> Why not let the player choose mods when creating a world?

There are those of us who like to enable 50+ mods on a world, it would clutter the world creation menu and make the menu redundant, as one may want to change the mods later.

**Comment by ClobberXD** [comment]
> > Toggle is the right word.
> 
> Actually no. Toggling generally means _switching a state of something by using the same signal_. This is not what is done here. By klicking the button you open the interface where you can select and unselect mods to load for the specific world. You don't toggle anything with the button nor you open an interface where you toggle something.

You have a point, "Toggle" could be confusing as well. I agree with "World mods" then. :)

**Comment by paramat** [comment]
+1.
