### ISSUE TITLE
Background/Game title doesn't change when changing what world you create

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8254]
##### Issue type
 - Bug report
 
##### Minetest version
```
Any?
```

##### Summary
(MineClone2 background. Minetest Game selected)
![image](https://user-images.githubusercontent.com/28972859/52962820-1d657000-3353-11e9-87b0-3f88439cc34f.png)

##### Steps to reproduce
* Go to the MC2 game and click 'New'.
* Select 'Minetest Game' in the game list
(To get my picture)

**Comment by rubenwardy** [comment]
is this a regression?

**Comment by LoneWolfHT** [comment]
> is this a regression?

I'm not sure what you mean?

**Comment by rubenwardy** [comment]
Does this problem exist in 0.4.16 or 0.4.17?

**Comment by LoneWolfHT** [comment]
> Does this problem exist in 0.4.16 or 0.4.17?

Yes

**Comment by paramat** [comment]
Minor issue, the user should really select the desired game from the gamebar.

**Comment by IhrFussel** [comment]
> Minor issue, the user should really select the desired game from the gamebar.

There is no game bar on Android ... at least not in the dev from Dec and I doubt it got readded.

So yes the background should absolutely update when selecting the game in the world creation menu.

**Comment by paramat** [comment]
Good point, i forgot that.

**Comment by paramat** [comment]
I expect this is supported by those working to improve the main menu. Maybe mention this behaviour in the 'improving main menu' issue.

**Comment by Zughy** [comment]
I think this is a design error. I'd expect to choose a game and then create a world for that specific game. I shouldn't be able to change the game in the world creation menu.

> But android has no bar

Yes, and that's bad design.  

Removing the list and implementing the bar on Android would be a temporary fix, probably not worth the time.  At the same, I would suggest to not implement what LoneWolf asked, and to just take what I said in consideration for the new menu. If devs agree with me, I'd suggest to label this one as "possible close". If not, well, I tried

**Comment by rubenwardy** [comment]
Bug no longer exists due to games list being removed from that dialog
