### ISSUE TITLE
Register confirmation window does not substitute actual server address and name

### ISSUE THREAD

**Issue by Fixer-007** [minetest/minetest#8257]
##### Issue type

 - Bug report
 
##### Minetest version

```
291b2446
```

##### Summary

You are about to join the server at %1$s with the name "%2$s" for the first time.

![e4mw1tt](https://user-images.githubusercontent.com/3686677/52973024-a52f9680-33b4-11e9-8366-e992ef6383e6.png)

**Comment by Fixer-007** [comment]
Screenshot (english): https://i.imgur.com/e4Mw1TT.png

**Comment by paramat** [comment]
Please drag and drop images into issues to avoid disappearing images in future.

**Comment by Fixer-007** [comment]
Seems like Microsoft gave middle finger to me, they do not allow me to edit my posts or attach images anymore on this undisclosed web browser.

**Comment by Fixer-007** [comment]
Seems like Microsoft gave middle finger to me, they do not allow me to edit my posts or attach images anymore on this undisclosed web browser. Thank you for attaching it up for me.

**Comment by paramat** [comment]
Can anyone confirm this bug?

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/0ad96cc73f5498cf4ffe85afe1478066acfd377a/src/gui/guiConfirmRegistration.cpp#L98-L99
Not sure these are correct, should it be `\"%1$s\"`?

**Comment by pauloue** [comment]
https://github.com/minetest/minetest/issues/7948

**Comment by paramat** [comment]
Thanks, @Fixer-007 are you on windows?

**Comment by Fixer-007** [comment]
On windows 7, msys2

**Comment by paramat** [comment]
Ok folding this into #7948

**Comment by Fixer-007** [comment]
And... it is clearly a dupe ща #7948 :(

**Comment by srifqi** [comment]
@paramat
It uses `%1$s` instead of `%s` because translators may need reorder the arguments.
https://github.com/minetest/minetest/pull/6849#discussion_r159262002

**Comment by paramat** [comment]
Thanks.
