### ISSUE TITLE
When flying and not touching ground, there shouldn't be any stair smoothing

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#826]
It makes going upwards slow (when pressing the Jump key), especially when not using fast mode, regardless of "noclip" state.

**To reproduce:** start flying while touching ground; this won't happen if you start flying while not touching ground.

**2014-05-11**: the bug is still here.

**Comment by est31** [comment]
@Calinou what exactly is this bug about? Does it still exist?

**Comment by paramat** [comment]
Is this not just camera smoothing? I can't see this as a problem. Third person mode just makes it noticeable.

**Comment by paramat** [comment]
Testing i can't see any problem, even with third person mode. Everything seems improved since mt earlier report. There's a very short and very small 'jump' of the player model when flying up from touching the ground. I suggest a close.

**Comment by Fixer-007** [comment]
stair smoothing? Can't reproduce with latest mt + jumping pr 3810.

**Comment by paramat** [comment]
Closng with permission of Calinou.
