### ISSUE TITLE
Bug in minimap_radar HUD flag

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8267]
> Even though 'set flags' is setting 'false' for radar, get flags is showing that the hud flag 'minimap_radar' is true.
The hud flag 'minimap' is working correctly, seems to be a bug in 'minimap_radar' hud flag, which i coded

Quoted from https://github.com/minetest/minetest_game/issues/2315
The HUD flag was added by #6273

EDIT by SmallJoker: Quote original issue
EDIT by paramat: Quote actual issue :)

**Comment by pgimeno** [comment]
I think that the proper quote is this one: https://github.com/minetest/minetest_game/issues/2315#issuecomment-465830723

> Even though 'set flags' is setting 'false' for radar, get flags is showing that the hud flag 'minimap_radar' is true.

**Comment by paramat** [comment]
Yes, done.

**Comment by pgimeno** [comment]
Is it possible that this was broken by 9649e47 ? It seems to me that `{HUD_FLAG_MINIMAP_RADAR_VISIBLE, "minimap_radar"},` was inadvertently dropped when moving `es_HudBuiltinElement[]` from l_object.cpp to hud.cpp. I haven't tested, but could that cause this issue?

**Comment by SmallJoker** [comment]
@pgimeno Thank you for your debugging. It's exactly the issue.
I tested it locally and had to disable the MTG map mod to keep the radar flag value persistent.

1942660

**Comment by paramat** [comment]
Thanks for that.
