### ISSUE TITLE
Some installed games not detected as installed

### ISSUE THREAD

**Issue by bell07** [minetest/minetest#8269]
##### Issue type
 - Bug report

##### Minetest version
```
$ bin/minetest --version
Minetest 5.0.0-dev-0ad96cc7 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system: Gentoo Linux

##### Summary
Games installed trough content db are not detected as installed.

##### Steps to reproduce
1. Fetch minetest_game or whynot_game from contentdb
2. Button remain "Install" because not detected as installed

I looked deeper to the lua code

The entry in `store.packages_full` is
```
	{
		thumbnail = "https://content.minetest.net/thumbnails/1/Q4Tym9Rddd.png",
		id = "bell07/whynot_game",
		url = "https://content.minetest.net/packages/bell07/whynot_game/releases/1017/download/",
		score = 3417.9,
		title = "Whynot",
		short_description = "Aims to get all existing high quality mods working together",
		type = "game",
		release = 1017,
		name = "whynot_game",
		author = "bell07"
	},
```
The entry in `game_hash` is

```
	["bell07/whynot"] = {
		gamemods_path = "/home/user/Minetest-5/bin/../games/whynot_game/mods",
		id = "whynot",
		menuicon_path = "/home/user/Minetest-5/bin/../games/whynot_game/menu/icon.png",
		path = "/home/user/Minetest-5/bin/../games/whynot_game",
		addon_mods_paths = {
			"/home/user/Minetest-5/bin/../mods"
		},
		type = "game",
		release = 1017,
		name = "Why not subgame",
		author = "bell07"
	},
```

The "bell07/whynot_game" does not match "bell07/whynot". The game was installed trough the content manager

**Comment by rubenwardy** [comment]
This is due a duality in the IDs of Games. The pkgmgr should be ignoring `_game` as it isn't part of the ID.

**Comment by paramat** [comment]
PR #8270

**Comment by paramat** [comment]
Bug doesn't happen when downloading nodecore game.

**Comment by bell07** [comment]
Not looked in detail, but the issue still appears for minetest_game in released "stable-5" version.
whynot_game is not affected anymore

**Comment by rubenwardy** [comment]
This will only be with games which are preinstalled

**Comment by bell07** [comment]
I use the self-compiled version from git/stable-5. The minetest_game was not preinstalled. If I delete the ~/projects/minetest/games/minetest_game/ and reinstall them trough CDB, the issue is still there, the installed package is still not shown as installed.Maybe something wrong in CDB?
The game.conf contains
```
name = Minetest Game
author = minetest
description = Bundled by default with Minetest, and aims to be lightweight, moddable, and fairly playable without mods.
release = 1108
```
