### ISSUE TITLE
Error on exit from main menu.

### ISSUE THREAD

**Issue by Khyota** [minetest/minetest#8273]
##### Issue type

 - Bug report
 
##### Minetest version

```
85389ad9949fa3ffca85aa65e577a70547bcd211
```

##### OS / Hardware

Operating system: openSUSE 15.0
CPU: AMD Ryzen 7 2700X

##### Summary

Exiting from the Main Menu produces the console message:
"ERROR[Main]: Please choose a name!"
Seems to happen weather you have a name or not.

85389ad9949fa3ffca85aa65e577a70547bcd211
##### Steps to reproduce

1. Start Minetest.
2. Exit Minetest.

**Comment by paramat** [comment]
Only happens in some situations and i don't think it's a serious bug. Not sure why it's an 'ERROR'.

**Comment by Khyota** [comment]
I figured it out. Minetest has to be closed with "name" empty in minetest.conf. This can be done either by starting it with name empty in minetest.conf, or pressing connect after clearing the name textbox, which will save the entry whether it connects or not. It seems that address, port, and name will be written upon clicking a server name or pressing connect but only name is allowed to be written empty.

**Comment by Fixer-007** [comment]
I see that error in debug.txt on exit... But is this a problem? It does not do anything or block the game in any way...

**Comment by Khyota** [comment]
...Yeah it appears to be harmless.
