### ISSUE TITLE
Doesn`t lay out a texture on mesh model and alpha channel.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8274]
##### Issue type
 - Bug report
 
I tried to register a vase node of mesh drawtype. I needed to enable `use_texture_alpha = true` as some space of the texture is "transparent" where a UV mapping elements are. In blender it looks like properly (you can make sure in it if look at the screenshot below):
http://www.imageup.ru/img201/3293158/screenshot_20190223_000053.jpg

However, in minetest it looks like as if it is without the texture that laid out:
http://www.imageup.ru/img201/3293159/screenshot_20190222_235256.jpg

The version that this bug happens is 5.0.0-rc2 in. And to my wondering it gets worked properly in 0.4.17.1. Question: is this a bug in 5.0.0?

My code:
```
`minetest.register_node("luxury_decor:glass_vase", {
    description = "Glass Vase",
    visual_scale = 0.5,
    drawtype = "mesh",
    mesh = "glass_vase.blend",
    use_texture_alpha = true,
    tiles = {"glass_vase.png"},
    inventory_image = "glass_vase_inv.png",
    sunlight_propagates = true,
    paramtype = "light",
    paramtype2 = "facedir",
    groups = {choppy = 1.5},
    collision_box = {
        type = "fixed",
        fixed = {
            {-0.2, -0.5, -0.2, 0.2, 0.5, 0.2},
            --[[{-0.65, -0.3, -1.46, 0.65, 1.4, -1.66},
            {-0.65, -0.3, 0.46, 0.65, 1.4, 0.66}]]
        }
    },
    selection_box = {
        type = "fixed",
        fixed = {
            {-0.2, -0.5, -0.2, 0.2, 0.5, 0.2}
        }
    },
    sounds = default.node_sound_glass_defaults(),
    on_rightclick = function (pos, node, clicker, itemstack, pointed_thing)
        for _, flower in ipairs(flowers_list.name) do
            if "flowers:" .. flower == itemstack:get_name() then
                minetest.remove_node(pos)
                minetest.set_node(pos, {name="luxury_decor:glass_vase_with_"..flower})
            end
        end
    end
})`
```

**Comment by NathanSalapat** [comment]
Could you post the code for the node?

**Comment by pgimeno** [comment]
More importantly, does it happen with RC1?

`use_texture_alpha` is pretty close to the code that #8019 touched. It was merged between RC1 and RC2, so if it works fine in RC1, it would help a lot knowing where to look.

**Comment by pgimeno** [comment]
`use_texture_alpha = true` works for me in 5.0.0-dev 85389ad99 (same as rc2 AFAIK) with this mod: https://notabug.org/pgimeno/Gists/src/minetest--testmesh-alpha

I wonder if it's OS-specific or there's something else.

**Comment by Andrey2470T** [comment]
I had followed your code, but my code appeared the same as yours. Only `sunlight_propagates=true` property was missing. Also, i noted you didn`t apply your texture to the model in blender. Although, i tried to do so is to delete a selected texture and even tried to delete UV unwrapping, but and it did nothing change. I posted my code in first post. And could you recheck my model? Maybe did i do anything wrong? A link: 
https://ufile.io/cskt2

**Comment by NathanSalapat** [comment]
Works just fine for me on a build from this morning. Excuse my texture, just something I had laying around.
![working alpha](https://user-images.githubusercontent.com/8930456/53290478-d8ce4000-3769-11e9-986e-f141490a0b71.png)
Maybe a stupid question but are you sure your texture image saved with the transparency? The UV layout for the vase shouldn't effect if the transparency works, it will only effect the alignment of the texture to the mesh. If you were trying to set any transparency within Blender that get's ignored in the export.

**Comment by Andrey2470T** [comment]
NathanSalapat, i tried to disable 'Use Alpha' and that`s what i got: http://www.imageup.ru/img201/3293926/screenshot_20190223_221458.jpg
As you see the texture on the unwrapping looks like entirely white color, however i used this texture:
https://ufile.io/5ll3g
Why does it look like white in blender?

**Comment by NathanSalapat** [comment]
I think I figured it out, you need to export your mesh as an obj. You can't use the .blend file type.
I used your code and textures and changing the mesh from the vase.blend to vase.obj it worked. With the texture you provided it was difficult to see, but was displaying properly.

**Comment by Andrey2470T** [comment]
I exported it to .b3d format, i didn`t put it as .blend file in register_node(). But it will not change anything if i export it to .obj.

**Comment by Andrey2470T** [comment]
And a question: why does applied texture on my screesnhot above look like white? It should look like as in the link that i posted.

**Comment by NathanSalapat** [comment]
Might be a video driver problem. Seems to be a problem that not all users have.
Maybe try using a non-alpha texture to make sure the mapping is working go from there.
Does the debug.txt have anything relating the node? Either in the startup or when placing?

**Comment by Andrey2470T** [comment]
it doesn`t write anything in debug.txt.

**Comment by NathanSalapat** [comment]
I don't know what to tell you, sounds like there must be a problem in your system or the node registration. the use_texture_alpha doesn't seem to be the problem though.

**Comment by pgimeno** [comment]
@Andrey2470T An alpha value of exactly 0.0 makes the texture opaque for me in the affected pixels, both in 0.4.16 and in 5.0.0-rc2. Your glass_vase.png has alpha exactly 0.0 in most of the texture. I wonder if that's the issue.

What puzzles me is that it works for you in 0.4.17.1 but not in 5.0.0-rc2. I don't see any differences.

**Comment by stujones11** [comment]
> I exported it to .b3d format

If you export to b3d then you must be sure to 'unlink' the texture in blender. The version of the exporter included in the minetest repo does this for you automatically. https://github.com/minetest/B3DExport

However, that would not explain why it would work in 0.4.17.1 and not current dev but it seems to be working okay for others.

**Comment by paramat** [comment]
Seems not an engine issue so closing, but feel free to continue discussion.
