### ISSUE TITLE
Setting GUI scaling to default freezes Minetest when using “Restore Default” button

### ISSUE THREAD

**Issue by Linuxdirk** [minetest/minetest#8275]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-85389ad (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Linux 4.20.6-arch1-1-ARCH x86_64
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

##### Summary
Basically what the title says. I randomly tested other things for the issue, but was not able to reproduce it with anything else than the “GUI Scaling” option. Similar to #7803 so it seems to be a general issue.

##### Steps to reproduce
1. Get the version mentioned above
2. Go to Settings -> All Settings
3. Navigate to Graphics -> Menu
4. Doubleclick “GUI Scaling” (`gui_scaling`) and set to `2` for example
5. Click “Save”, now the GUI gets scaled as expected
6. Click “Restore Default” … Window is completely frozen now. No way to close it via window buttons or window close shortcut (usually Alt+F4)
7. Terminate the process by hitting Ctrl+C in the shell where you started MT from or whatever way you like
8. Restart Minetest, GUI still scaled
9. Navigate to the “GUI Scaling” option again
10. Doubleclick it, set to `1`, click “Save”

**Comment by SmallJoker** [comment]
Merging into #7803
