### ISSUE TITLE
Ability to clear key-binds from within the "Change Keys" dialog

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8279]
##### Issue type

 - Feature request

##### Summary

One way to do this is to keep track of the focused field, and clear the corresponding key-bind when a clear button is pressed.

**Comment by NathanSalapat** [comment]
Most programs let you clear shortcut keys by hitting backspace, I found however if you try that in the keybindings menu you will actually set the key to use backspace.

**Comment by ClobberXD** [comment]
Works, the keybind is cleared, but it leaves an incomplete line in `minetest.conf`.
e.g. `keymap_autoforward = `

Note that all key-binds are written to minetest.conf, even if only one of them is changed, and the empty keybinds end up creating incomplete lines. So I don't think this issue is strictly related to this PR, but it'd be nice if you could fix them here. :)
