### ISSUE TITLE
Can’t compile due to weblate, translation issue

### ISSUE THREAD

**Issue by Linuxdirk** [minetest/minetest#8284]
##### Issue type

 - Build issue
 
##### Minetest version

```
$ git rev-parse HEAD
d80186d8571261ad7d09d3498a9e8a6da63801a2
```
##### OS / Hardware

Operating system: Linux 4.20.6-arch1-1-ARCH x86_64
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz

##### Summary
Compiling the latest available dev version as of writing this text here does not work

##### Steps to reproduce
1. Follow the compiling instructions on https://github.com/minetest/minetest
2. It configuring works properly
3. Compiling crashes with the following message.

```
/home/dirk/mt5/minetest/po/uk/minetest.po:6036: duplicate message definition...
/home/dirk/mt5/minetest/po/uk/minetest.po:2280: ...this is the location of the first definition
/usr/bin/msgfmt: found 1 fatal error
make[2]: *** [src/CMakeFiles/translations.dir/build.make:242: locale/uk/LC_MESSAGES/minetest.mo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:222: src/CMakeFiles/translations.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- *** Detected Git version 5.0.0-dev-d80186d ***
[ 11%] Built target GenerateVersion
[ 11%] Linking CXX static library libjsoncpp.a
[ 11%] Built target jsoncpp
make: *** [Makefile:152: all] Error 2
```

**Comment by ClobberXD** [comment]
I can confirm that I get the same error too, when compiling from the latest master.

**Comment by Linuxdirk** [comment]
Confirmed the confirmation. ae1caba is the last version that compiles for me.

```
$ cmake --version
cmake version 3.13.4

$ make --version
GNU Make 4.2.1
```

**Comment by NathanSalapat** [comment]
I can confirm the confirming of the confirmation.
`/usr/bin/msgfmt: found 1 fatal error
src/CMakeFiles/translations.dir/build.make:241: recipe for target 'locale/uk/LC_MESSAGES/minetest.mo' failed`

**Comment by juozaspo** [comment]
Same error for me. cmake 3.10.2, GNU Make 4.1
ae1caba6aaa6f0a13e70f195f371fd4e7a378491 compiles fine.

**Comment by DS-Minetest** [comment]
I can confirm the same, too. cmake 3.10.2, GNU Make 4.1 (Lubuntu 18.04)
Here are maybe the problematic lines:
https://github.com/minetest/minetest/commit/17451f15dcd0c524225305e2bc255e8281a99974#diff-da6a4955c14f76c37cb739f21641bd83R2280 https://github.com/minetest/minetest/blob/17451f15dcd0c524225305e2bc255e8281a99974/po/uk/minetest.po#L2278-L2280
https://github.com/minetest/minetest/commit/17451f15dcd0c524225305e2bc255e8281a99974#diff-da6a4955c14f76c37cb739f21641bd83R6036 https://github.com/minetest/minetest/blob/17451f15dcd0c524225305e2bc255e8281a99974/po/uk/minetest.po#L6035-L6037

**Comment by Fixer-007** [comment]
Same problem

**Comment by fwhcat** [comment]
Same.
commenting those lines:
#diff-da6a4955c14f76c37cb739f21641bd83R6036

allows the compilation.

Question: how Weblate allows duplicates ids ?! (is that normal?)

**Comment by rubenwardy** [comment]
Content store should not be appearing anywhere in the translation files

**Comment by fwhcat** [comment]
<pre><font color="#55FF55"><b>➜  </b></font><font color="#55FFFF"><b>po</b></font> <font color="#5555FF"><b>git:(</b></font><font color="#FF5555"><b>master</b></font><font color="#5555FF"><b>)</b></font> grep -r &quot;Content Store&quot; *     
<font color="#AA00AA">be/minetest.po</font><font color="#00AAAA">:</font>msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">be/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">ca/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">cs/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">da/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">de/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">eo/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">es/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">fr/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">hu/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">id/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">it/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">ja/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">ko/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">lt/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">ms/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">nb/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">nl/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">pl/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">pt/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">pt_BR/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">ru/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">sl/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">sr_Cyrl/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">sv/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">sw/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">tr/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">uk/minetest.po</font><font color="#00AAAA">:</font>msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">uk/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">zh_CN/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;
<font color="#AA00AA">zh_TW/minetest.po</font><font color="#00AAAA">:</font>#~ msgid &quot;<font color="#FF5555"><b>Content Store</b></font>&quot;</pre>

It appears uk & be translations have the "Content store" id, others are commented out.

**Comment by paramat** [comment]
@nerzhul

**Comment by nerzhul** [comment]
again a translation issue with our system, yeah :)

**Comment by nerzhul** [comment]
Fixed by 911db0e25613e57d436ca39ee055d2fb4ee771aa

**Comment by Linuxdirk** [comment]
Fix confirmed from my side.

**Comment by juozaspo** [comment]
Compiles fine for me too.

**Comment by ClobberXD** [comment]
I can confirm the confirmation that the fix fixes the now-fixed compilation error. :3
