### ISSUE TITLE
Mapgen appears to ignore humidity in this particular code

### ISSUE THREAD

**Issue by C1ffisme** [minetest/minetest#8285]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest-5.0.0-dev
(Tested with the nightly build to further verify.)
```

##### Summary

```lua
for heat_point = 0,10 do
	for humidity_point = 0,10 do
		minetest.register_node("noise_test:"..heat_point.."he_"..humidity_point.."hu",{
			description = "Heat: "..heat_point..", Humidity: "..humidity_point,
			tiles = {"he"..heat_point..".png^hu"..humidity_point..".png"},
		})
		
		minetest.register_biome({
			name = "he"..heat_point.."hu"..humidity_point,
			y_min = -31000,
			y_max = 31000,
			node_stone = "noise_test:"..heat_point.."he_"..humidity_point.."hu",
			heat_point = heat_point*10,
			humidity = humidity_point*10,
		})
	end
end
```

I've set up a script to test where certain biomes spawn based on humidity and heat because I've been having difficulty finding certain biomes. But while testing this script, I've discovered only biomes with a humidity of zero. (And no, flipping the heat point and humidity point in the for loops does not change the issue so that the mapgen ignores heat. This is specifically a problem with humidity.)

(Apologies for the eye-sore screenshots)

![screenshot_20190224_154505](https://user-images.githubusercontent.com/9893266/53305836-c75d6480-384b-11e9-84f1-7ac3a30550a4.png)
![screenshot_20190224_154522](https://user-images.githubusercontent.com/9893266/53305837-c75d6480-384b-11e9-8dbc-a92d0ba1cc86.png)
![screenshot_20190224_154540](https://user-images.githubusercontent.com/9893266/53305838-28853800-384c-11e9-97b6-79f013e24c93.png)
![screenshot_20190224_154556](https://user-images.githubusercontent.com/9893266/53305839-c7f5fb00-384b-11e9-8844-3a91fd9eab98.png)

I can provide the textures I used too if needed.

EDIT: 

This code:
```
for humidity_point = 0,10 do
	for heat_point = 0,10 do
		minetest.register_node("noise_test:"..heat_point.."he_"..humidity_point.."hu",{
			description = "Heat: "..heat_point..", Humidity: "..humidity_point,
			tiles = {"he"..heat_point..".png^hu"..humidity_point..".png"},
		})
		
		minetest.register_biome({
			name = "he"..heat_point.."hu"..humidity_point,
			y_min = -31000,
			y_max = 31000,
			node_stone = "noise_test:"..heat_point.."he_"..(10-humidity_point).."hu",
			heat_point = heat_point*10,
			humidity = (10-humidity_point)*10,
		})
	end
end
```
creates a world with only 100% humid biomes.

**Comment by paramat** [comment]
Interesting. Mapgen humidity does work correctly as proven by MTG, but why it doesn't work in this code is worth investigating.

**Comment by C1ffisme** [comment]
It seems to pick biomes based on heat, and then after picking based on heat, it will pick the first-registered biome to match that heat of any humidity.

Here are the textures I used: https://drive.google.com/open?id=1Ib1mq1g5A4UgyvcJ9xFMsRPpc3jGjZJ2

**Comment by C1ffisme** [comment]
I should note that I first noticed this problem when I was testing mapgen with a few biomes that share the same heat point, but have different humidity points, and I wasn't noticing all of the biomes at those heat points, only the ones registered first for that heat point.

(For example, all of my savannas do not show up, because while they have higher humidity, they share the same heat points as my deserts which are registered first.)

**Comment by paramat** [comment]
> a few biomes that share the same heat point, but have different humidity points,

That shouldn't make a difference, expected problems would only occur if biomes have identical heat and humidity points (and are active at that particular y).
I don't think this affects MTG.
I'll test this bug myself to confirm.

**Comment by C1ffisme** [comment]
I've tested this in Minetest 5.1.0, got the same results

**Comment by SmallJoker** [comment]
```diff
			heat_point = heat_point*10,
-			humidity = (10-humidity_point)*10,
+			humidity_point = humidity_point*10,
```

**Comment by paramat** [comment]
LOL well spotted! I missed that too.

**Comment by C1ffisme** [comment]
Welp, that would do it
