### ISSUE TITLE
Allow mods to disable dungeon gen

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8286]
##### Issue type

 - Feature request 

##### Summary

Allow mods to disable dungeon generation

**Comment by paramat** [comment]
In what way? They can already by setting 'mg_flags' on world creation, the flags will be stored for that world.
Try:
`minetest.set_mapgen_params({flags = "nodungeons"})`
or
`minetest.set_mapgen_params({flags = "caves,nodungeons,light,decorations"})`
https://github.com/minetest/minetest/blob/6e7ba366fc58c437640c7d603d28668b52ba79c7/doc/lua_api.txt#L4019
Or better use the new method https://github.com/minetest/minetest/blob/6e7ba366fc58c437640c7d603d28668b52ba79c7/doc/lua_api.txt#L4047

**Comment by Extex101** [comment]
Oh OK NVM
