### ISSUE TITLE
Add dungeon-like building generation API

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8287]
##### Issue type

 - Feature request
 
##### Summary

Add some sort of API to create dungeon-like buildings 

This could be used to make:
The Tardis interior 
https://github.com/benrob0329/tardis/issues/5

Minecraft like end-dungeons,
Genorated castles 
Or whatever you want to use it for

**Comment by paramat** [comment]
Dungeon generation has many parameters that can be set, but currently these parameters are only usable by core mapgens. A core mapgen could expose some of these parameters within it's own parameters, i'm planning to add settable dungeon density noise.

Hmmmm (our previous mapgen dev) was planning to add independently-settable world dungeon parameters.

Your API idea goes further and i guess would allow the mod usage of dungeongen in a lua voxel manipulator. Nice idea.

**Comment by Extex101** [comment]
Thanks!
Note on name change: XD stupid swift key XD
