### ISSUE TITLE
Browse online content: Content installed manually not detected or indicated

### ISSUE THREAD

**Issue by bell07** [minetest/minetest#8293]
If I install any mod manually, the online content browser does not see the package. The Content-DB version is proposed and the "Install" button appears. If I click to install, the Content-DB version is extracted to the folder and overrides the files of manually installed version.

Expected behaviour: The Content-DB view should indicate the manually installed unknown version. The button could be "Replace" or "Update" instead of "Install".
In case the Replace/Update is taken the manually version should be deleted before the new Content-DB version is installed.

Nice to have is an indicator if ".git" folder is found in the manually installed version.  Maybe show the remote branch and last action date as version (look into  .git/HEAD, then into  .git/logs/refs/* text files)
`cat .git/logs/"$(cat .git/HEAD | sed 's/.* //g')" | tail -n 1`

**Comment by Linuxdirk** [comment]
> Nice to have is an indicator if ".git" folder is found in the manually installed version.

No it isn't since not all mods are installed or maintained having Git for version control.

**Comment by bell07** [comment]
> No it isn't since not all mods are installed or maintained having Git for version control.

I meant to show additional git info only if the git folder is found. Otherwise its just an "unknown version". 

Other more generic idea ist just to show last folder change date as version for non-Content-DB content.

**Comment by Linuxdirk** [comment]
> Other more generic idea ist just to show last folder change date as version for non-Content-DB content.

This fails on many systems. It even fails on Linux-specific file systems when mounted with `noatime` option.

The best would be doing it the other way round and detect version/state of CDB-installed contend and just inform users that something is not installed via CDB (detect by CDB-related files missing in the folder or missing in local _CDB-installed things_ database).

**Comment by bell07** [comment]
> This fails on many systems. It even fails on Linux-specific file systems when mounted with `noatime` option.

I meant the change date (ctime) that should exists on any system. (using LuaFileSystem it's `lfs.attributes(path).modification` . But anyway, it's nice to have. The important part of this request is to get existing content visible even not installed trough CDB.

**Comment by Linuxdirk** [comment]
> The important part of this request is to get existing content visible even not installed trough CDB.

I'd consider it not being like this is a blocker if the CDB is capable of installing dependencies.

**Comment by rubenwardy** [comment]
This isn't a bug. ContentDB has no way of knowing whether a manually installed mod called "mobs" is Mobs Redo or Simple Mobs

**Comment by LoneWolfHT** [comment]
Is there a way for manually installed mods to 'support' the ContentDB?

**Comment by rubenwardy** [comment]
You'd need to add name, author, and release to the metadata conf file, where release is an integer found in the download link for a cdb release. Or release could be 0, in which case "update" will always be shown

**Comment by LoneWolfHT** [comment]
> You'd need to add name, author, and release to the metadata conf file, where release is an integer found in the download link for a cdb release. Or release could be 0, in which case "update" will always be shown

Thanks! I'll do this with my mods

**Comment by rubenwardy** [comment]
Note that "author" much match the username in the URL of your profile

**Comment by bell07** [comment]
Ok, to add author to the mod.conf helps to let clearly identify the mod. But I see still the issues with overriding packages without any check.
1. Files collision between mods from CDB
Install "Mobs Redo", then install "Simple Mobs" (theoretically since not in CDB yet) => the "Mobs Redo" is overridden without any warning.
2. Files collision between mods from CDB and manually installed, with same example
Install "Simple Mobs" manually to "mobs" folder, then install "Mobs Redo" from CDB => "Simple Mobs" is overridden without any warning.

My proposal now is at least to add a warning about "Folder XY exits, are you sure to replace it?" if folder exists and if the package/author does not match (if not an verified update).


PS: the version should be the official version string as shown in CDB, not the internally used integer ID.

**Comment by Linuxdirk** [comment]
> My proposal now is at least to add a warning about "Folder XY exits, are you sure to replace it?"

Yes, hat should be done as a minimum when handling folders that are already there. Never silently overwrite user-created folders.

**Comment by Linuxdirk** [comment]
@paramat: You're sure it is not a bug when the CDB silently overwrites user-created folders?

**Comment by paramat** [comment]
Ugh, sorry, was confused by rubenwardy's 'This isn't a bug' 'The bug here is' comment.

**Comment by rubenwardy** [comment]
Fixed
