### ISSUE TITLE
Possibly update text of 'num emerge threads' if sqlite is not thread safe

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8302]
See https://github.com/minetest/minetest/issues/8300#issuecomment-468813838 onwards.
"sqlite is not thread safe you must not use emerge > 1"

**Comment by adrido** [comment]
Afaik sqlite can be thread-save if its correctly configured/Initialized 

https://sqlite.org/threadsafe.html

**Comment by IhrFussel** [comment]
> Afaik sqlite can be thread-safe if its correctly configured/Initialized
> 
> https://sqlite.org/threadsafe.html

The docs mention that the DEFAULT mode is threadsafe.

So the core devs must have messed up terribly in order for it to be dangerous.

**Comment by paramat** [comment]
@nerzhul can you confirm?

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-hub/2019-03-03#i_5504077

00:51 sofar   IhrFussel: I've been actually skeptical of the claim that it isn't threadsafe, but I have no data or evidence to support that MT's use of it is thread safe (it could be an MT implementation issue after all)
00:52 paramat i'll check with nerz, see why he wrote that
00:53 sofar   well, here's the catch
00:53 sofar   setting the sqlite threading mode is done at *compile time* of sqlite
00:54 sofar   in most distro's that means you're using the distribution libsqlite3.so
00:54 sofar   so you might be safe on one distribution, but not another
00:54 sofar   I just checked clearlinux and we don't change the default, so, on clearlinux, sqlite3 should be serialized and thus threadsafe for minetest
00:55 sofar   but, you have to check (every | your own) distro, or compile sqlite3 statically
00:59 sofar   heck you can ask during runtime if sqlite3 was built thread safe with sqlite3_threadsafe()
01:17 paramat ah hm
01:18 paramat so MT code should check it

**Comment by nerzhul** [comment]
i'm not sure we are always in threadsafe mode. Maybe we should change our default build to use embedded sqlite3 in 5.1 and ensure it is in all builds

**Comment by paramat** [comment]
#8303 merged but leaving this open while we're unsure about the thread safe status of sqlite.

**Comment by sfan5** [comment]
FYI this is entirely wrong. The Mapgen/EmergeThread does not directly write to the map.
The map is only ever written to inside `Map::timerUpdate()` or `Map::save()` both of which are only called in `Server::AsyncRunStep()` which is on the ServerThread.

So in the end SQLite is only used from a single thread and the amount of emerge threads is does not change this.

**Comment by paramat** [comment]
That satisfies me =)

**Comment by sfan5** [comment]
Note that the EmergeThread does call `Database::loadBlock()` (via `EmergeThread::getBlockOrStartGen() -> ServerMap::loadBlock()`) to <b>read</b> from SQLite, however this access is also synchronized using the server's `m_env_mutex`.
