### ISSUE TITLE
Stacking of falling leveled nodes does not work with `leveled = nil`

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#8307]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.0.0-dev-eea1fda
```

##### Summary
I can't find anything in the documentation that says that leveled nodeboxes need `leveled` to be set.
However if `leveled` is not set, and the node is falling onto one of his equals, it replaces the other node and doesn't stack.
Here's the problematic code:
https://github.com/minetest/minetest/blob/ad0f20835cd4f64f5d47f537125e9e3157717beb/builtin/game/falling.lua#L75-L84
Maybe it would help to replace in line 75 `bcd.leveled` with `(bcd.leveled or self.node.level ~= 0)`. [(This won't work for falling liquids.)](https://github.com/minetest/minetest/blob/309e158fc818227aa08086a0478ba45d1ee3c769/src/mapnode.cpp#L603-L621)
((Btw. does [`get_node_level`](https://github.com/minetest/minetest/blob/ad0f20835cd4f64f5d47f537125e9e3157717beb/builtin/game/falling.lua#L140) return `leveled` if `paramtype2` is not `"leveled"`? It seems so. That would make lines 78-80 obsolete (apart from being legacy code).))

##### Steps to reproduce
Register a leveled node with `paramtype2 = "leveled"`, `leveled = nil` and `place_param2 = 8`. Then let one of this node fall into the other one. They will not be stacked. The falling one will replace the one which was already there.

**Comment by SmallJoker** [comment]
#9852

**Comment by Desour** [comment]
This should be fixed by #9852. I'll close.
