### ISSUE TITLE
//usr/lib/i386-linux-gnu/libharfbuzz.so.0: Warnung: undefinierter Verweis auf »FT_Get_Var_Blend_Coordinates«

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#8308]
##### Issue type

 - Build issue
 
##### Minetest version

```
actual Git Version from today
```

##### OS / Hardware

Operating system: Kubuntu 18.04 LTS (32Bit)
CPU: Intel

GPU model:
OpenGL version:

##### Summary

//usr/lib/i386-linux-gnu/libharfbuzz.so.0: Warnung: undefinierter Verweis auf »FT_Get_Var_Blend_Coordinates«
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetest.dir/build.make:7108: recipe for target 'bin/minetest' failed
make[2]: *** [bin/minetest] Error 1
CMakeFiles/Makefile2:211: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

##### Steps to reproduce

after updating my Kubuntu 16.04 to 18.04 I can´t compile anymore.

**Comment by SmallJoker** [comment]
After searching `FT_Get_Var_Blend_Coordinates` I quickly found an issue caused by Infinality.
* https://github.com/jaagr/polybar/issues/310#issuecomment-271182763
  * https://www.reddit.com/r/archlinux/comments/5mphpu/psa_harfbuzz_update_infinality_breaking_system/
     * https://gist.github.com/cryzed/e002e7057435f02cc7894b9e748c5671

Does this help you in any way?

**Comment by JPRuehmann** [comment]
No, Sorry.
I found that too, but since there is nothing I understand to do.
And I don´t have a programm or a lib named infinality or so on my Computer.
A search for infinality in Synaptic gives nothing.
So I hoped I get help here.
Thanks,

**Comment by sfan5** [comment]
With certainty this bug is caused by some part of your system setup (partial upgrade, incompatible libraries, ...), not by Minetest.
