### ISSUE TITLE
Fix movement beyond protected / impassible blocks

### ISSUE THREAD

**Issue by argyle77** [minetest/minetest#8309]
##### Issue type
 - Bug report (not a blocker)
 - Feature request

##### Minetest version
```
Minetest 5.0.0-dev-debug-111f1dc9-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system:  Linux Mint 19 Xfce
CPU:  Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz

##### Summary
 It seems like, if I protect a node and then dig it, I can sometimes walk through where it was before the engine manages to put it back.  Also, the same can happen when replacing a node in register_on_dignode, in the way, for instance, I used it in borders mod.

##### Steps to reproduce
I can provide some steps, if necessary.  

It was mentioned (on irc) that this has been an issue for a long time, but I couldn't find an official thing here, so I thought I'd bring it up for tracking because it seems like it might be complicated.

Would it help to reproduce some of the irc chat here to start the conversation?

**Comment by SmallJoker** [comment]
Mentioned in #3822
Duplicate
