### ISSUE TITLE
Fog affects wielditem's appearance.

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8313]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-1af248b4 (Linux)
```

##### OS / Hardware

Operating system: Debian 9
CPU: Intel

GPU model: Intel
OpenGL version: 3.0

##### Summary

Not so much a problem, as an observation.  Thought this was interesting, that the fog affects the wielditem's appearance.  Gif for your viewing pleasure:
![screenshot_20190304_095012](https://user-images.githubusercontent.com/23448162/53741221-e8cdda00-3e63-11e9-819d-1e1e8560136a.gif)

##### Steps to reproduce

Reduce viewing range with fog on, such that it affects your wielded item's appearance.

**Comment by NathanSalapat** [comment]
Can confirm, though it only happens when switching between 20 & 30. I have to wonder if anybody ever actually plays with that low of a viewing range, I usually use about twenty times that.

**Comment by jastevenson303** [comment]
I wonder too.  This is almost a non-issue, but behavior I wanted to point
out anyway.

**Comment by Wuzzy2** [comment]
Is this even a bug? If the fog is very dense, it kind makes sense you can't even see your own hand. ^^

**Comment by jastevenson303** [comment]
I don't think so, really, but it's not a feature request or
documentation(?) issue either.

**Comment by DS-Minetest** [comment]
In clouds this can look good.

**Comment by appgurueu** [comment]
Cannot reproduce

**Comment by v-rob** [comment]
Happens in 5.0.0, not in 5.2.0+.  (But even if it wasn't "fixed", it's not like it's a huge deal anyways...)
