### ISSUE TITLE
Minetest 5.0.0 wont compile 

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#8315]
-- OS
    Debian 8

-- Bug Report

CMakeFiles/minetest.dir/convert_json.cpp.o: dans la fonction « fetchJsonValue(std::string const&, std::vector<std::string, std::allocator<std::string> >*) »:
convert_json.cpp:(.text+0x856): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o: dans la fonction « ServerList::deleteEntry(Json::Value const&) »:
serverlist.cpp:(.text+0x2203): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text+0x2248): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text+0x226c): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text+0x2290): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text+0x22c9): encore plus de références indéfinies suivent vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o: dans la fonction « ServerList::sendAnnounce(ServerList::AnnounceAction, unsigned short, std::vector<std::string, std::allocator<std::string> > const&, double, unsigned int, float, std::string const&, std::string const&, std::vector<ModSpec, std::allocator<ModSpec> > const&, bool) »:
serverlist.cpp:(.text+0x4322): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x437a): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x43aa): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x4631): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x468a): référence indéfinie vers « Json::Value::append(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text+0x46bd): encore plus de références indéfinies suivent vers « Json::Value::append(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o: dans la fonction « void std::vector<Json::Value, std::allocator<Json::Value> >::_M_insert_aux<Json::Value>(__gnu_cxx::__normal_iterator<Json::Value*, std::vector<Json::Value, std::allocator<Json::Value> > >, Json::Value&&) »:
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x27): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x8a): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0xbf): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0xe3): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x10c): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x12f): encore plus de références indéfinies suivent vers « Json::Value::Value(Json::Value&&) »
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetest.dir/build.make:6804: recipe for target 'bin/minetest' failed
make[2]: *** [bin/minetest] Error 1
CMakeFiles/Makefile2:261: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sfan5** [comment]
duplicate of #6381, look there for a workaround
