### ISSUE TITLE
Allow players to be hidden from clients

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#8316]
##### Issue type
 - Feature request
 
##### Minetest version
```
5.0.0
```

##### Summary

I think that `player:hide_player()` (or `minetest.hide_player(player)`) should be added to make invisibility mods easier to create and more effective.

Currently, it is possible to make players invisible, however CSMs and/or hacked clients can detect invisible players.

Once `player:hide_player()` is called, the server would stop sending the player (or any references to the player) to all connected clients (until `player:unhide_player()` or `player:show_player()` is called).

**Comment by bigfoot547** [comment]
How about allowing only some players to be hidden from some clients?

`player:hide_player(player2)` and `player:show_player(player2)`
And maybe `player:hide_all()` and `player:show_all()`
(And some helpers to hide the player from everyone / show the player to everyone)

**Comment by DS-Minetest** [comment]
This feature sounds as if it had the ability to cause many problems. Modders would always have to think about the possibility of players not being there for other players. Csm will make this even worse.
Furthermore I doubt that this feature is really needed. The visibility of the player is often controlled by the server. The server can already set the model, the texture, the nametag and the selection box of the player. And it's often ssm that makes the players visible in another way (eg. some fancy custom nametags, speech bubbles or moving vehicles), not csm. And if there was a sscsm installed on a server, it could be controlled by the server to not do anything.
Lastly I guess the implementation would make much effort.

**Comment by luk3yx** [comment]
Players can currently be hidden (and I use this in my cloaking mod), but they still display in the minimap and `.list_players`. Even with SSCSMs installed, it will be possible to modify clients to ignore these restrictions (and ignore the "disable minimap" server-side preference).

Can't the server just have a list of players to not send to clients and remove their co-ordinates from the list of players to send to the client?

**Comment by luk3yx** [comment]
This should (eventually) be fixed by #8397.

**Comment by paramat** [comment]
PR closed.
