### ISSUE TITLE
Minetest 5.0.0 only runs with administrator privileges under Windows 10

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#8324]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0-win64
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating System: Windows 10
CPU: Intel Core i5-7200U 2.5 GHz
GPU: Intel HD Graphics 620 177
Memory: 8GB DDR4
Hard Drive: 256GB SSD

##### Summary
Minetest 5.0.0 requires administrator privileges to execute under Win64. Yet, I encounter no such restrictions running earlier 0.4.x versions of Minetest (or for that matter any other application) as a normal user.

##### Steps to reproduce
When I double click `C:\Program Files\minetest-5.0.0-win65\bin\minetest.exe`, nothing happens. However, if I select 'Run as Administrator', then the application launches (albiet prompted by an account security warning). This is a fresh installation, downloaded today from https://forum.minetest.net/viewtopic.php?f=18&t=22278

**Comment by jastevenson303** [comment]
I wonder if it's because minetest-0.4.x was used more, and thus considered
safer?  That may be a stretch, of course.

**Comment by Fixer-007** [comment]
Those are portable versions that create/modify files in install folder, that means it can't go in Program Files.

**Comment by adrido** [comment]
Use the installer version: https://forum.minetest.net/viewtopic.php?f=42&t=21543

**Comment by rubenwardy** [comment]
This works perfectly fine with the installer

**Comment by v-rob** [comment]
I haven't had this problem.  It may have something to do with it being in Program Files, which is a read-only directory.  Try copying Minetest to a non protected directory (like the desktop) and then try it.

**Comment by Mrchiantos** [comment]
The problem is "Program Files", Windows can block use files, because this is a protect DIR.

For blockcolor, i have move in C: , this resolve probleme for admin privileges.
