### ISSUE TITLE
Large inventory lists are not sent correctly

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#8325]
##### Issue type
 - Bug report

##### Minetest version
```
Minetest 5.0.0 (Linux)
```

##### Summary
originally reported here https://forum.minetest.net/viewtopic.php?f=6&t=22285
Inventory lists with <b>lots</b> of items are not sent correctly, causing a serialization error on the client.
<pre>
2019-03-06 00:39:15: ERROR[Main]: A serialization error occurred:
2019-03-06 00:39:15: ERROR[Main]: Malformatted inventory list. list=main, read 197 of 3424 ItemStacks.
2019-03-06 00:39:15: ERROR[Main]: The server is probably  running a different version of Minetest.
</pre>

##### Steps to reproduce
register lots of items and enable the creative inventory
```lua
for i = 1, 3000 do
	minetest.register_node(minetest.get_current_modname() .. ":node" .. tostring(i), {
		description = "Grassy Block",
		tiles = {"default_grass.png"},
		groups = {crumbly = 3},
		drop = 'default:dirt',
	})
end
```

##### Debugging effort
checking Wireshark, the inventory list size is correct but the the inventory is unexpectedly cut off
![grafik](https://user-images.githubusercontent.com/1042418/53845373-212b0080-3fa9-11e9-97d7-1d5a5a65532a.png)

using some debug code placed in `Server::sendDetachedInventory`, the sizes of sent inventory can be watched:
<pre>
2019-03-06 00:39:15: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2019-03-06 00:39:15: ACTION[Server]: serialized inv sz = 13
2019-03-06 00:39:15: ACTION[Server]: serialized inv sz = 20597
2019-03-06 00:39:15: ACTION[Server]: serialized inv sz = 70647
[ error message from above follows ]
</pre>
suspiciously, the inventory that failed is above 65535 bytes in size

**Comment by pgimeno** [comment]
Confirmed the magic number by doing a rough bisection. 

size=65847 -> fails
size=65127 -> works

**Comment by pgimeno** [comment]
It seems to me that this was introduced in https://github.com/minetest/minetest/commit/0a5e77132ae8c495c50cfc58bbe4ce1bfcd377e3 because `operator<<` doesn't allow packets larger than 65535 bytes.

**Comment by nerzhul** [comment]
see #8330 it's a major refactor on network string serialization, yes it's another breakage but we must do it as a urgent fix. It will solve definitively coding errors problem on a such case.
