### ISSUE TITLE
Make set_local_animation() support more than the basic animations?

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8335]
From what I've seen `set_local_animation` only supports a few basic animations

> `set_local_animation(stand/idle, walk, dig, walk+dig, frame_speed=frame_speed)`

Why doesn't it support more? Could it be changed to support more?

**Comment by DS-Minetest** [comment]
The keypresses that activate the new animations would have to be hardcoded[.](https://github.com/minetest/minetest/blob/ffb17f1c9a203fea6de70159b461f52d104e05b9/src/client/content_cao.cpp#L833-L842) I can't think of any animation that would be essential enough.

**Comment by LoneWolfHT** [comment]
> The keypresses that activate the new animations would have to be hardcoded[.](https://github.com/minetest/minetest/blob/ffb17f1c9a203fea6de70159b461f52d104e05b9/src/client/content_cao.cpp#L833-L842) I can't think of any animation that would be essential enough.

It conflicts with the swimming animations that I added to a player model.
I didn't realize that was tied to keys. Makes more sense now

**Comment by paramat** [comment]
LoneWolfHT,
Do you want to make a request for a specific new animation to be added? Or some other specific request? Issue currently seems too vague to keep open.

**Comment by LoneWolfHT** [comment]
> LoneWolfHT,
> Do you want to make a request for a specific new animation to be added? Or some other specific request? Issue currently seems too vague to keep open.

I'd like to be able to define my own custom ones

**Comment by SmallJoker** [comment]
@LoneWolfHT How would you define those? Passing a function reference to Minetest to run as a callback? When would the client know what to use?
The sole purpose of `set_local_animation` is to send predictions to the client so that the network lag does not distort the animation.

**Comment by LoneWolfHT** [comment]
Maybe by giving CSMs the ability to play local animations, I could make do with that even without C++ SSCSM
