### ISSUE TITLE
Fullscreen bgcolor ignores color

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8336]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### Summary
The color of `bgcolor[]` does not work when fullscreen. It's always a translucent black, no matter what color you choose.

##### Steps to reproduce
Use `luacmd` and enter this command:

`/lua minetest.show_formspec("singleplayer", "hey", "size[4,4]bgcolor[red;true]")`

Expected: Red fullscreen. Actual: Translucent black fullscreen.

Compare to:

`/lua minetest.show_formspec("singleplayer", "hey", "size[4,4]bgcolor[red]")`

This works, a red window is opened.

**Comment by SmallJoker** [comment]
Fixed by #8716
