### ISSUE TITLE
Missing formspec theme customization options

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8339]
##### Issue type
 - Feature request
 
##### Minetest version
```
5.0.0
```

##### Summary
Many things in formspecs have a hardcoded style/color which cannot be changed. There are still many ways for your custom formspec to have that ugly gray/green that you cannot get rid of.

I therefore request to add the missing customization options.

Specifically, the following things need theming support (list may not be exhaustive):

* `textlist` (needs the same stuff as `tableoptions`)
* Text input fields (background color, color of selected text)
* Drop-down list (background color, hover color)
* Checkbox (background color, color when clicked, border color)
* Button (gradient color, border color)
* Scrollbar (same as button, plus the “empty” area)
* Default text color (if not specified explicitly), because forcing `minetest.colorize` everywhere gets tedious

I request to customize everything via “prepend” strings that work like like `tableoptions` or `listcolors` that set the colors for all widgets (of the relevant type) in advance, so that you can simply put it into your player prepend string and be done with it for all formspecs.
What I specifically do NOT request is adding more arguments for every widget, as this mean you still have to manually set the colorization for each widget again, and again, and again.
Following this ideology, #5385 and #5361 should be rejected.

**Comment by rubenwardy** [comment]
I have this on my todo list

**Comment by rubenwardy** [comment]
Partially fixed by #8383

**Comment by SmallJoker** [comment]
More recent ToDo list: #8744, also #8962
