### ISSUE TITLE
Inside cloud fog is broken for very high clouds

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8340]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### Summary
I have found a `set_clouds` setting for which the “inside cloud” fog effect fails.

##### Steps to reproduce
1. Get `luacmd`
2. Start Minimal Development Test
3. Set your view range to 200
4. In console: `/lua me:set_clouds({color="#FFFF72B8", density=0.7, height=200, thickness=24})`
5. Fly above Y=200 and get inside the cloud
6. Look down and check if you are in the cloud fog
7. Flow down to about Y=15 and look around you

Expected: You get the inside cloud fog when you are in the cloud, nowhere else.
Actual: You get NO inside cloud fog (you can see the bottom without problems) when you are in the cloud, but when you flow down to between ca. Y=3 and Y=20, the inside cloud fog appears.

**Comment by Fixer-007** [comment]
related to https://github.com/minetest/minetest/issues/3576 ?

**Comment by Wuzzy2** [comment]
No idea, but aforementioned issue is from 2016, so a long time before cloud fog was a thing.

**Comment by Fixer-007** [comment]
I mean this message, posted after cloud PR was merged: https://github.com/minetest/minetest/issues/3576#issuecomment-330682814

**Comment by Linuxdirk** [comment]
Clouds seem to be broken even with default settings (no cloud related settings in minetest conf and a new world without mods) on random basis.

**Comment by paramat** [comment]
I wonder if it's due to the 200 node camera offset thing ...

**Comment by paramat** [comment]
It is apparently according to investigation by Jordach http://irc.minetest.net/minetest-dev/2019-10-22#i_5605156

**Comment by BluebirdGreycoat** [comment]
Bump. This still happens. Latest development head. I discovered it when trying to change the cloud height based on player's location in the world (multiple realm stuff and whatnot).

I can also report that my own testing confirms Jordach's report.

E.g., changing cloud height to 2000, then back to 120, doesn't break it.
But if you fly up to e.g., 400, then back down, it's suddenly broken ...
After that, set clouds to 320, and observe that the cloud fog is back (even though the actual clouds are far above! [exactly 200 meters]).
Then put clouds back to 120 and note that it's still broken. You have to log out, then back in, to fix the problem.
