### ISSUE TITLE
v6 mudflow breaks Hades Revisited lava ocean in 5.0.0 but not in 0.4.17.1

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8341]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### Summary
The lava ocean in Hades Revisited is destroyed if v6 mudflow is active in 5.0.0. This game worked in 0.4.17.
This might be a regression.

##### Steps to reproduce
1. Download Hades Revisited 0.2.4: https://repo.or.cz/minetest_hades/hades_revisited.git/snapshot/0.2.4.zip
2. Create a new world in 0.4.17 and look around you. Check out the large lava ocean
3. Now go to 5.0.0 and create another world, try it again. Check out the large lava ocean again

In step 2, the lava ocean is intact, but sadly, in step 3, the lava ocean gets badly damaged, it has holes everywhere.

Why I believe this is caused by mudflow: Because when I turn off mudflow in `default/mapgen.lua`, then create a new world, the lava oceans work again.

**Comment by paramat** [comment]
View code at https://repo.or.cz/minetest_hades/hades_revisited.git
Please post screenshots of the damage.
Do you know which mod contains the lava ocean lua mapgen code?

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/blob/a7c5dc50e5445c3aa3b45ea4be48fc179bd4cce8/doc/lua_api.txt#L4048
Try setting 'override_meta' to true, it may be necessary to actualy apply the mapgen setting.

**Comment by Wuzzy2** [comment]
> View code at https://repo.or.cz/minetest_hades/hades_revisited.git

I said 0.2.4, not HEAD. Your post is invalid. Please follow my PRECISE steps to reproduce before claiming “Unconfirmed bug”.

Note that in HEAD, I have disabled v6 mudflow as a desperate workaround. Disabling mudflow repairs the game, but it this just just more evidence that something might be broken about mudflow that wasn't broken before.

> Try setting 'override_meta' to true when setting 'mgv6_spflags', it may be necessary to actually apply the mapgen setting. If that works, no idea why behaviour has changed since 0.4.17.1.

No, it doesn't work. I tried to enable `force_meta` in 0.2.4, but it doesn't work. This is not a surprise because I know mudflow was already enabled, `force_meta` was not neccessary. Mudflow works without `force_meta`, I know it because I see the mapgen apply the mudflow.

**Comment by paramat** [comment]
Sorry for that.

Yes, mudflow shouldn't require 'override meta' as it's not present in map_meta.txt on initial world creation.
It doesn't surprise me that mudflow breaks your game, as mudflow overgenerates into neighbour mapchunks, a solution is probably possible in your mod.
The issue of course is why this has changed in 5.0.0.

**Comment by paramat** [comment]
Here are 2 mudflow related commits that are in 5.0.0 but not in 0.4.17.1:
https://github.com/minetest/minetest/commit/f55816f93a8d80371878a5292f4f432e90dcc582
https://github.com/minetest/minetest/commit/212945c7a3a1b9873ab4ef54c4d0360c54573185

**Comment by paramat** [comment]
^ We need more input, will close if no response after a month.

**Comment by Wuzzy2** [comment]
Screenshot: https://satoshiupload.com/images/UK8wbXfM4S.jpg

(Note: You have to set the `mudflow` flag in `mods/hades_mapgen/init.lua` to reproduce this. `mudflow` is currently deactivated in Hades Revisited because of this bug, so the game is playable.)

Coords in screenshot. Camera looks straight down, so the green dot marks the correct XZ coords.

I don't know if the holes are aound the borders of mapchunks (too lazy to calculate this). But the “holes” are rather big.

**Comment by paramat** [comment]
Thanks, and sorry i was overly strict in my last comment.

**Comment by Wuzzy2** [comment]
I am closing this because it’s a very old issue and only concerned with a rare compability break from 0.4.17 to 5.0.0. That was a long time ago, it was not really relevant back then, and it is even relevant now.

Closing.
