### ISSUE TITLE
set_hp reason is either broken or useless

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8344]
##### Issue type
 - Bug report?
 
##### Minetest version
```
5.0.0
```

##### Summary
The `reason` you can feed into `set_hp` appears to be either broken or useless. It is nowhere to be found in `register_on_dieplayer` or `register_on_player_hp_change`.

##### Steps to reproduce
Use this mod:

```
 minetest.register_chatcommand("hp", {
         params = "<hp>",
         description = S("Set hp"),
         privs = { maphack = true },
         func = function(name, param)
                 local player = minetest.get_player_by_name(name)
                 player:set_hp(tonumber(param), "my_custom_reason")
                 return true
         end,
 })

minetest.register_on_dieplayer(function(player, reason)
    minetest.log("error", dump(reason))
```

Then enter in chat the command “/hp 0” and see what happens.

Expected result: In chat it somehow print out the reason table with “my_custom_reason” somewhere.
Actual result: Returns `{type="set_hp", source="mod"}`. The reason (`my_custom_reason`) I fed into `set_hp` has disappeared, making it useless.

**Comment by Wuzzy2** [comment]
Oops. In the above code, remove the description line. Then it will work.

**Comment by rubenwardy** [comment]
It needs to be a table

**Comment by Wuzzy2** [comment]
OK, but it's still broken.

Try this mod instead:

```
 minetest.register_chatcommand("hp", {
         params = "<hp>",
         description = "Set hp",
         func = function(name, param)
		if param == "" then return false, "No HP given!" end
                 local player = minetest.get_player_by_name(name)
                 player:set_hp(tonumber(param), {type="fall", from="mod"})
                 return true
         end,
 })
```

`/hp 1` works.
`/hp 0` crashes.

**Comment by pauloue** [comment]
The crash when setting HP to 0 is reported at #8227. Also custom reasons are not permitted, that's why it got reset to `set_hp` (maybe they should be permitted).
