### ISSUE TITLE
UI/API support for optional read-only map

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#8355]
#7544 added support for an optional read-only map.
Currently there's no good way to set this up other than manipulating the filesystem and config files manually.

I think we should allow (somehow) to do the most useful things through the UI.

Some UI ideas:
* A flag in the UI to not save changes to the map (read_only backend sqllite, backend dummy)
* Flag for a resettable map (both maps backed by sqllite) plus some kind of reset button
* more?

Same for a Lua API

This is more of a discussion about what's useful.

**Comment by ClobberXD** [comment]
Maybe also allow migrating existing worlds into read-only worlds using a `--migrate-readonly` command-line switch?
