### ISSUE TITLE
Attached particle spawners no longer rotate with object

### ISSUE THREAD

**Issue by orwell96** [minetest/minetest#8362]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0 (stable)
```

##### Summary
Until 0.4.17.1, the particle position of attached particle spawners used to rotate with the object they were attached to. #4781. I use this behavior in advtrains to make the steam engines produce steam.
However, probably since either the rotation PR or the latest particlespawner fixes, this is broken and positons are world-absolute again. (I can't test right now what exactly reverted it, I'm on mobile)
Original report here:
https://forum.minetest.net/viewtopic.php?f=11&t=14726&p=345821#p345745
##### Steps to reproduce
Install advtrains, place a steam engine and check the smoke.

**Comment by paramat** [comment]
Duplicate, and #4781 is wrong PR.
