### ISSUE TITLE
Attached particle spawners no longer rotate with object

### ISSUE THREAD

**Issue by orwell96** [minetest/minetest#8363]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0 (stable)
```

##### Summary
Until 0.4.17.1, the particle position of attached particle spawners used to rotate with the object they were attached to. #4782. I use this behavior in advtrains to make the steam engines produce steam.
However, probably since either the rotation PR or the latest particlespawner fixes, this is broken and positons are world-absolute again. (I can't test right now what exactly reverted it, I'm on mobile)
Original report here:
https://forum.minetest.net/viewtopic.php?f=11&t=14726&p=345821#p345745
##### Steps to reproduce
Install advtrains, place a steam engine and check the smoke.

**Comment by pgimeno** [comment]
This is an oversight in faa358e797128ab07bb5644ce305a832d59e5596. Anyway, the code is not prepared to work with the general rotations that were introduced by it, it's only prepared to work with yaw, so e.g. a plane with a smoking engine in one wing would look wrong too.

**Comment by pgimeno** [comment]
I have a patch that fixes advtrains, but I'm not sure it correctly fixes the general case. What I believed was the correct fix, introduces an offset of exactly -200 m in the X direction. Does anyone have an idea of where this offset may come from? Does the model have any such offset perchance?

**Comment by paramat** [comment]
200 nodes is the interval of the camera offset shift, see #1119

**Comment by pgimeno** [comment]
That was it, thanks paramat!

Patch: https://gitlab.com/pgimeno/minetest/commits/pg-fix-particle-rotation

I'm not 100% convinced that rotating velocity and acceleration by the object's rotation is right. It may be for some use cases. But a proper fix would probably need expanding the possibilities of particles, to allow specifying whether the velocity and acceleration are relative to the attached object or to the world.

**Comment by paramat** [comment]
Not a blocker for 5.0.1, maybe we can fix this for 5.0.2.

**Comment by paramat** [comment]
A PR needs creating with pgimeno's patch (they're not on GitHub), or has this been done already?

**Comment by ClobberXD** [comment]
PR (created from pgimeno's patch): #8767

**Comment by SmallJoker** [comment]
#8767
