### ISSUE TITLE
Formspec text overlaps and is out of bounds

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#8371]
##### Issue type

 - Bug report
 
##### Minetest version

```
Minetest 5.0.0-dev-c95e89b6 (Linux)

```

##### OS / Hardware

Operating system:lubuntu
CPU:intel

##### Summary

The text in formspec looks horrible when you increase font size or play with specific window sizes:
![1](https://camo.githubusercontent.com/071c99da3270689d2bf1f7b37a143158f5860e81/68747470733a2f2f692e696d6775722e636f6d2f6358684c3162672e706e67)
![2](https://camo.githubusercontent.com/1a90de9a580aac0038ae04a4c1a4f45d4a9315ef/68747470733a2f2f692e696d6775722e636f6d2f514835776f57782e706e67)
![3](https://i.imgur.com/wWC617p.png)
https://github.com/minetest-mods/technic/issues/478
https://github.com/minetest-mods/technic/issues/477

##### Steps to reproduce

play minetest with big font size

**Comment by paramat** [comment]
I think this is expected and unavoidable, and due to using a font size too large or providing too small an area for text, not a bug.

**Comment by HybridDog** [comment]
As a mod creator you cannot control this, you can only set font size agnostic space between formspec elements.

**Comment by HybridDog** [comment]
The position and size coordinates could be extended to allow non-constant sizes which are calculated client side.
https://github.com/minetest/minetest/blob/02a23892f94d3c83a6bdc301defc0e7ade7e1c2b/doc/lua_api.txt#L1821-L1823
Here are some examples:
* A percent sign could be used to make the coordinate independent of the formspec size: e.g. `50%,50%` means the middle of the formspec window.
* With a special character, a reference variable could be set or used. When setting it, the formspec element is adjusted in size or position so that it fits well (such as dynamic text height). The reference variable, which remembers this position or size, can be used for other formspec elements. For example, if the height in a textarea is set to `&myref` and the y coordinate of some label is be set to `*myref`, then the textarea height is automatically adjusted so that the whole text fits in it and the label is placed under it if the textarea begins at y=0.
* To make the reference variables useful, operators need to be available, too. For example, `*myref+0.4` can be used if the textarea begins at y=0.4.
* For reference variables, the values sometimes also need to be restricted within a specific range. For example, `*myref+0.4:10%:50%` could prevent that a textarea pushes a label down outside the window.

Unfortunately, the extended coordinates probably make formspecs more difficult.

**Comment by paramat** [comment]
Sounds like making formspecs change according to client font size would be a nightmare.
Surely it's up to the client to not choose a font that's too large, and up to the modder to provide enough space? i don't think this a bug, more a feature request.

**Comment by SmallJoker** [comment]
The formspecs use a fixed grid, so issues like these are unavoidable. Formspecs suck, thus consider providing more space in your formspec and make them less compact.

**Comment by paramat** [comment]
@rubenwardy or any core devs, any support for this request?
