### ISSUE TITLE
Add a Markdown formspec element

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#8372]
##### Issue type

 - Feature request
 
##### Minetest version

```
Minetest 5.0.0-dev-c95e89b6 (Linux)

```

##### OS / Hardware

Operating system:lubuntu
CPU:intel

##### Summary

The Markdown format is well-known, and allows writing text with images, underlining, bullet lists and even custom inline html code and the raw source text is readable too. A Markdown formspec element could be used that modders can add extended formspec text easily, reliably and without compatibility problems.
I thought about making a mod which converts Markdown to minetest formspec but because of #8371, I thought it's better to implement it in minetest core.

**Comment by SmallJoker** [comment]
HTML added. Write your Markdown -> HTML conversion script.
