### ISSUE TITLE
Minetest 5.0.0 not announcing to servers

### ISSUE THREAD

**Issue by discon-nected** [minetest/minetest#8375]
- Bug report
 
##### Minetest version
```
Minetest 5.0.0 (Linux)
```
Operating system: Ubuntu 18.04

Server will not announce to server.minetest.net

Previously posted [here](https://forum.minetest.net/viewtopic.php?f=6&t=22304&p=346026#p345407)

I have had no trouble announcing my server when using various versions of minetest 5.0.0-dev to servers.minetest.net. But my 5.0.0 server (final release, non-dev) does not announce.

I have exactly the same config file with `server_announce = true`. Prior to this version, this is, as expected, what the logs showed...
```
2019-03-08 03:54:23: ACTION[Main]: World at [..../worlds/SN001]
2019-03-08 03:54:23: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:30000.
2019-03-08 03:54:23: ACTION[Server]: Announcing to servers.minetest.net
```

Now there is no attempt from the server to announce, meaning this line is not printed as startup:
```
2019-03-08 03:54:23: ACTION[Server]: Announcing to servers.minetest.net
```
I have tried restarting several times and explicitly specifying the config path with `--config` to no avail.

`--verbose` doesn't offer any clues. I rebuilt another MT5 with the same result. Perhaps there is a conflict from too many compiled versions on the same server. It's odd though because I can get my RC1 and RC2 builds to run simultaneously on separate ports with both properly announcing.

Also, setting `port = 30001` in minetest.conf has no effect. Only `using --port 30001` or specifying the config file with `--config` works for the port. I have tried building from source with server_announce default set to true but it still won't attempt to announce. The issues are also not present with MT5.0.0-dev on the same server,

All of these same issues occur with 5.1.0-dev as well.

**Comment by paramat** [comment]
@sfan5

**Comment by Jean28518** [comment]
Me having the same issue..

**Comment by sfan5** [comment]
As I've said before, contact me on IRC so this issue can be debugged.
I am unable to reproduce this issue myself and there are many 5.0 servers on the list that evidently do not have this problem.

**Comment by ClobberXD** [comment]
Can't reproduce with both 5.0.0 and 5.1.0-dev. Try increasing `curl_timeout` maybe?

https://github.com/minetest/minetest/blob/9f1b98b9978fa90dc939663a73f17727f9e32425/minetest.conf.example#L1589-L1592

**Comment by discon-nected** [comment]
_**sfan5**_ found the issue. Evidently we broke curl-dev on our machine at some point _**and**_ failed to include the `-DENABLE_CURL=1` flag when building.
