### ISSUE TITLE
Launchpad PPA Failed Build of 5.0.0 on Trusty

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/minetest#8380]
##### Issue type

 - Build issue
 
##### Minetest version

```
5.0.0
```

##### Summary

I just happened to be looking at the [stable Launchpad PPA](https://launchpad.net/~minetestdevs/+archive/ubuntu/stable/+packages) & noticed that the version 5.0.0 builds for Ubuntu Trusty had failed. Not sure if anyone was aware, but figured I might as well report it.

![ppa_failed_build-trusty](https://user-images.githubusercontent.com/3631473/54403993-45649c80-468f-11e9-974a-18cf8a1357d2.png)

The build log says: *"Insufficient gcc version, found 4.8.4.  Version 4.9 or higher is required."*

There are failed builds for Trusty & Vivid in the [nightly builds PPA](https://launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds/+packages) as well.

**Comment by rubenwardy** [comment]
14.04 reaches end of life next month. Probably not worth fixing

**Comment by AntumDeluge** [comment]
Alright, just wanted to make sure. :)
