### ISSUE TITLE
register_allow_player_inventory_action - action parameter confusing

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#8384]
##### Issue type

 - (Small) Bug report
 
##### Minetest version

```
5.0.0
```

##### Summary
I believe that the `take` and `put` action names are confused. When *putting* items in a chest, a "take" event is fired, and when *taking* items from a chest, a *put* event is fired.

##### Steps to reproduce
Just the following : 
```
minetest.register_allow_player_inventory_action(function(player, action, _, inventory_info)
    minetest.chat_send_all(action)
end)
```

**Comment by ClobberXD** [comment]
Seems quite intuitive, when considering that the inventory actions should be viewed from the perspective of the _player's_ inventory. When putting items in a chest, we _take_ it from our inventory, and put it into the chest's inventory. Similarly, when taking items from a chest, we take the item from the chest inventory, and _put_ it into our inventory.

**Comment by SmallJoker** [comment]
You register a callback which is run when the player's inventory is modified.
This means you _take_ an item from the player inventory to _put_ it inside the chest inventory.
