### ISSUE TITLE
Players that die in autoforwards continue to creep forwards

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8387]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### Summary
If you die in autoforwards mode, your dead body continues to creep forwards, haunting the living. OooooooooooOOOOOOooooOOOooooo …

##### Steps to reproduce
* Enable autoforwards and damage
* Enable 3rd person camera
* Fall from a giant cliff
* Watch what happens

EXPECTED:
You die. You stop moving.

ACTUAL:
You die. Your dead corpse continues to move forwards on the floor. Other players get scared.

SUGGESTED FIX:
Server must ignore all movement attempts when dead. Autoforwards mode should remain unaffected as it's clientside.

**Comment by ClobberXD** [comment]
Can confirm that this bug exists. Creepy... :)

**Comment by Wuzzy2** [comment]
Hmm I just realized my suggested fix might be bullshit. I don't really know how autoforwards works, sorry. ;-)

**Comment by DS-Minetest** [comment]
>SUGGESTED FIX:
Server must ignore all movement attempts when dead. Autoforwards mode should remain unaffected as it's clientside.

The server doesn't move the player, it's the client. The server could probably stop to accept position updates from the client and send the real position back, but that would be terrible.
The easiest way fixing this is probably setting jump and speed to 0 with `set_physics_override`.

**Comment by paramat** [comment]
Not physics override, we should do a proper clientside fix.

**Comment by DS-Minetest** [comment]
Does the client know that its player is dead?

**Comment by ClobberXD** [comment]
The ideal implementation would be to disable movement client-side, and also checking for the same, server-side. Only client-side would mean that one can cheat without being detected, if they manage to hack around the fix.

**Comment by ClobberXD** [comment]
#8513
