### ISSUE TITLE
minetest.colorize does not work in read-only textarea

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8389]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### Summary
If you try to use `minetest.colorize` on the text part of a read-only `textarea` formspec element (`name` = empty string), it doesn't work. The text in the text body stays white.

##### Steps to reproduce
1. Install `luacmd` mod
2. `/grantme lua`
3. Insert this code into console:
```
/lua minetest.show_formspec(me:get_player_name(), "test", "size[6,6]textarea[0,0;6,6;;"..minetest.colorize("#FFFF00", "Hello, my friend. I am a label. I want to be yellow!")..";"..minetest.formspec_escape(minetest.colorize("#FF0000", "Ladies and Gentlemen, I'm the text. I want to be red!")).."]")
```

EXPECTED:
A friendly formspec opens up.
The label is yellow. The text is red.

ACTUAL:
A friendly formspec opens up.
The label is yellow. The text is white.

**Comment by SmallJoker** [comment]
Works for me, partially. The text color is broken as soon the line automatically wraps.

Small formspec:
![Small](https://user-images.githubusercontent.com/1497498/54487510-11f45e80-4897-11e9-9ca0-9ab58e29bcef.png)
Big formspec:
![Big](https://user-images.githubusercontent.com/1497498/54487516-23d60180-4897-11e9-947a-65aa6285d038.png)

Code:
```Lua
-- core.show_formspec(player:get_player_name(), "foo:bar",
"textarea[4,2.3;4.23,2.9;;" ..
minetest.colorize("#F00", [[Blinded by the light
Revved up like a deuce
Another runner in the night
Blinded by the light

Madman drummer bummers
Indians in the summer
With a teenage diplomat
In the dumps with the mumps
As the adolescent pumps]] .. ";]")
-- )
```

**Comment by v-rob** [comment]
This appears to be the same issue as #8662, but that issue is more descriptive.  Proposing a close.
