### ISSUE TITLE
Revert official mod depends format back to depends.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8391]
##### Issue type
 - Revert request
 
##### Minetest version
```
5.0.0
```

##### Summary
I request to revert the official depends format back to `depends.txt` and to drop it from `mod.conf`.

##### Rationale
The new format in `mod.conf` is less pretty to read and more annoying to maintain.

What is worse, official docs seriously recommend me to still ship `depends.txt` for “compability with previous versions”. In other words, I am adviced to save my depends redundantly.

That's really ugly, a source of confusion and pointless bugs and even more annoying to maintain.

So can you please just revert back to the old behaviour?

I am neutral of the move of `description.txt`.

**Comment by NathanSalapat** [comment]
Unless you want to support 0.4.17 there is no reason to continue using the depends.txt. If you're mod/game is using any features that 0.4... doesn't support no need to include the depends.txt as Minetest won't be able to run the code without errors anyway.

**Comment by Linuxdirk** [comment]
We finally have a config file for mods and don't need text files for configuration anymore. `depends.txt` still is supported as deprecated feature and I don't think that mod dependencies change on a regular basis, so setting it up once in the config file and add the `depends.txt` for outdated versions should not be too much work ...

**Comment by SmallJoker** [comment]
A single configuration file is easier to adjust than opening several files. If you want to provide backwards compatibility it's always more work to do, but that's always required to move towards a better system.
This new file now contains all required mod information, so you don't need to open multiple files or take care of adding new ones in case a new feature (i.e. file) was added. It's the same format as the settings, which means that adding new information fields can be added easily once it's wanted.

**Comment by paramat** [comment]
:-1: plus 2 core dev thumbs down in emoticons.

**Comment by Wuzzy2** [comment]
Alright, alright, I just adopt the new `mod.conf` then and ignore compability with 0.4.17. That might be the simplest solution for me.
