### ISSUE TITLE
Search or compare translated strings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8398]
##### Issue type
 - Feature request
 
##### Minetest version
```
5.0.0
```

##### Summary
Currently, translated strings cannot be searched with `string.find`. If you try to do, it doesn't work, it only searches the English original string.

This is a problem as it makes a searching feature for things like Creative Inventory impossible in non-English languages.

I therefore request a mechanism to sort or search through translated strings.

TBH, I have no idea how it could work. But I hope you agree with the use case.

**Comment by FaceDeer** [comment]
I'm facing a similar problem in my commoditymarket mod. There's a formspec with a table listing various items. I have a "filter by item description" control in the formspec that's supposed to let the player type a partial string and see only items that match it (eg, "pick" to get all the picks) and I also have the ability for the player to click on the table's column header to sort alphabetically.

None of this works right with localized strings, of course. I think a way to solve this would be for me to be able to get the player's locale and apply translations server-side, that would give me the actual string the player is seeing to filter and sort by. I wouldn't want to actually display the server-side-translated string back to the player, it would just be something I'd use to determine what to do with the table's rows.

**Comment by SmallJoker** [comment]
API idea:

`player:get_translator()` -> returns what's commonly referred to `S`, but returns translated strings of what's given by its as arguments.

**Comment by Wuzzy2** [comment]
But then Minetest needs to be aware of the player's language. OK, that doesn't sound impossible.

**Comment by FaceDeer** [comment]
I would think that's something the client can tell the server and have the server keep track of. When displaying formspecs through minetest.show_formspec() I've got a player object available and the formspec is being sent to a specific known player, so it should be fine for the server to do the translating in that case - only that one particular player is going to see the results.

It wouldn't be useful for formspecs defined via a node's "formspec" metadata, but that seems like it'd just be part of the tradeoff you make from going that route.

Oh, and having this ability would allow me to truncate translated strings, which is something I suggested as a possible alternate solution to #9313.

**Comment by sfan5** [comment]
FYI the server already knows the client's language.

Also if such an API is added, the strings returned by it should absolutely not be sent to the client. Only use them for sorting or searching.

**Comment by FaceDeer** [comment]
Aw, so no truncation? Ah well, it wasn't my preferred solution to #9313 anyway.

**Comment by paramat** [comment]
@SmallJoker do you (or any otehr core dev) support this request?

**Comment by rubenwardy** [comment]
I support this

**Comment by pyrollo** [comment]
Possible start for a fix here : https://github.com/minetest/minetest/pull/9733
