### ISSUE TITLE
visual_scale no longer applies to nodeboxes

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#8400]
##### Issue type
 - Bug report
 
##### Minetest version
5.0.0

##### OS / Hardware
Operating system: kubuntu 19.04
CPU: amd64
GPU model: nvidia ion.2
OpenGL version: 3.3

##### Summary
In minetest 0.4.16 and 0.4.17 it was possible to use visual_scale to resize a nodebox, it seems this feature has been lost in 5.0.0.

##### Steps to reproduce
Create a full node with drawtype "nodebox" and add visual_scale = 0.5 to the mix.

**Comment by paramat** [comment]
See https://forum.minetest.net/viewtopic.php?f=47&t=22363

**Comment by sfan5** [comment]
this issue can be fixed like this:
```diff
diff --git a/src/nodedef.cpp b/src/nodedef.cpp
index 03a163bd..e5aa9f5b 100644
--- a/src/nodedef.cpp
+++ b/src/nodedef.cpp
@@ -872,6 +872,18 @@ void ContentFeatures::updateTextures(ITextureSource *tsrc, IShaderSource *shdsrc
 			recalculateBoundingBox(mesh_ptr[0]);
 			meshmanip->recalculateNormals(mesh_ptr[0], true, false);
 		}
+	} else if ((drawtype == NDT_NODEBOX) &&
+			((node_box.type == NODEBOX_REGULAR) ||
+			(node_box.type == NODEBOX_FIXED)) &&
+			(!node_box.fixed.empty())) {
+		//Convert regular nodebox nodes to meshnodes
+		//Change the drawtype and apply scale
+		drawtype = NDT_MESH;
+		mesh_ptr[0] = convertNodeboxesToMesh(node_box.fixed);
+		v3f scale = v3f(1.0, 1.0, 1.0) * visual_scale;
+		scaleMesh(mesh_ptr[0], scale);
+		recalculateBoundingBox(mesh_ptr[0]);
+		meshmanip->recalculateNormals(mesh_ptr[0], true, false);
 	}
 
 	//Cache 6dfacedir and wallmounted rotated clones of meshes
```
However, it's unclear why that block of code was removed in 75320e7.

**Comment by paramat** [comment]
IRC http://irc.minetest.net/minetest-dev/2019-03-18#i_5514928
21:23 sfan5      the nodebox -> mesh conversion is likely gone to make world-aligned textures work on nodeboxes

**Comment by sfan5** [comment]
Removed "Blocker", "High Priority" since `visual_scale` was never explicitly supported for nodeboxes.
https://github.com/minetest/minetest/blob/426b5d3149f5fe510322a26cc8e67ba6de08d4a6/doc/lua_api.txt#L4253-L4254

**Comment by paramat** [comment]
Agreed, we're free to fix it or not, and fixing will break stuff.

**Comment by pgimeno** [comment]
@tenplus1 have you observed any nodes affected by this? I think that knowing the impact will help prioritizing

**Comment by sofar** [comment]
Yes, that is how the issue was spotted.

**Comment by paramat** [comment]
Skulls in Xanadu apparently http://irc.minetest.net/minetest-hub/2019-03-18#i_5514749

**Comment by pgimeno** [comment]
Thanks. So this feature has been reported broken in one node installed in a server that has registration blocked, and in an unreleased mod that has already found a workaround. Since nodebox scaling was never supported, and the impact of this change does not justify considering it an "undocumented feature", I think that "feature request" is a more appropriate label.

**Comment by blachner** [comment]
Yes I found a workaround as to scale the node itself, as I shown in the code here: [https://forum.minetest.net/viewtopic.php?f=47&t=22363](url)

I just make a node with side lengths greater 1.

But I have problems to scale the texture for the this kind of node, as you can see also in pictures included in my posting at the Minetest forum. Is there an other way to scale the texture for the bigger node to get the same visual presentation as in Minetest 0.4.17?

**Comment by paramat** [comment]
Hmm the texture scaling ability is useful and is lost, maybe we can work on re-adding that feature, but for 5.1.0 not 5.0.1.

**Comment by pgimeno** [comment]
Can't this simply be worked around with a cube-shaped mesh?

**Comment by paramat** [comment]
The paintings in the forum topic aren't cubes though, and creating meshes is not easy and requires using blender or similar. But yes, meshes are a workaround.
To clarify, i'm not suggesting this is high or even medium priority to add the features back in.

**Comment by blachner** [comment]
Right, the frame for the picture isn't a cube. It consists of 5 cuboids. 4 for the borders and 1 for the background.

I don't know much about using meshes in minetest. But if I understand the documentation I read so far correctly, I can define a mesh object with, for example, Blender an use it in minetest. But even if I define the picture frame this way and scaling the texture over the whole object is possible, I think I have another problem. How to get the mesh object in the correct aspect ratio of the picture? For this I must manipulate the mesh object directly, or I can offer only support for pictures with fix aspect ratios like 2:3 (portrait) and 3:2 (landscape).

**Comment by blachner** [comment]
If someone is interested I have published the mod under https://github.com/blachner/gallery

**Comment by numberZero** [comment]
> and creating meshes is not easy and requires using blender or similar.

Even `vim` can be used to create or edit a mesh if the format is suitable (`obj` is IIRC). The major advantage of nodeboxes is that they can be connected, but that’s unlikely to be used with scaled objects. Nevertheless, restoring support is possible. Here is an untested patch:

```diff
diff --git a/src/client/content_mapblock.cpp b/src/client/content_mapblock.cpp
index 9b4fd221e..cc23e50de 100644
--- a/src/client/content_mapblock.cpp
+++ b/src/client/content_mapblock.cpp
@@ -1317,8 +1317,11 @@ void MapblockMeshGenerator::drawNodeboxNode()
 
        std::vector<aabb3f> boxes;
        n.getNodeBoxes(nodedef, &boxes, neighbors_set);
-       for (const auto &box : boxes)
+       for (auto &box : boxes) {
+               box.MinEdge *= f->visual_scale;
+               box.MaxEdge *= f->visual_scale;
                drawAutoLightedCuboid(box, nullptr, tiles, 6);
+       }
 }
 
 void MapblockMeshGenerator::drawMeshNode()
```

**Comment by rubenwardy** [comment]
You cannot dynamically generate meshes, but you can dynamically generate node boxes

**Comment by numberZero** [comment]
Oh, okay then. Will test and make a PR.

**Comment by numberZero** [comment]
The patch works but not the way needed (texture is not scaled), so I wrote another one, see the PR.

**Comment by numberZero** [comment]
Hm, GitHub is weird.

> numberZero linked a pull request that will close this issue in 16 seconds 

Looks like a countdown...

**Comment by blachner** [comment]
I compiled the latest minetest with this patch included and tested it with my gallery mod. Works now like it worked in 0.4. Would be nice to see this in an upcoming release.
