### ISSUE TITLE
Anti-Aliasing (AA) settings have no effect

### ISSUE THREAD

**Issue by nekoswag** [minetest/minetest#8403]
##### Issue type

 - Bug report
 
##### Minetest version

```
0.4.17.1 from openSUSE repos
5.0.0 compiled by myself
```

##### OS / Hardware
Operating system: Linux (openSUSE Tumbleweed 20190315, Kernel 5.0.1)
CPU: AMD Ryzen 5 2600X

GPU model: AMD Radeon RX 570 8GB
OpenGL version: OpenGL 4.5, Mesa 18.3.4, amdgpu driver

##### Summary
Anti Aliasing settings have no effect

##### Steps to reproduce
Changing the AA settings has no effect on the rendered image, it happens on both 0.4.17.1 and 5.0.0.
Other games' AA settings work, so I don't think it's a driver issue.

**Comment by Calinou** [comment]
You need to restart Minetest after changing the `fsaa` value from Advanced Settings. Here, it works fine on a NVIDIA graphics card (using the proprietary driver) on Linux.

**Comment by nekoswag** [comment]
It works after restarting. Maybe there could be a hint that you have to restart the whole game for this setting to take effect?

**Comment by paramat** [comment]
We have an issue for documenting which settings require a restart (many do).

**Comment by benrob0329** [comment]
See #5462

**Comment by nekoswag** [comment]
I see, thanks.
