### ISSUE TITLE
Formspecs: Add read-only inventory list

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8407]
##### Issue type
 - Feature request
 
##### Minetest version
```
5.0.0
```

##### Summary
I suggest for the formspecs to make it possible to make inventory lists (`list[]`) read-only.

Read-only means the player can only see the contents of the inventory list, but not change it. Putting, taking and moving item stacks is not possible.

Moreover, a read-only inventory list shall have a different look and feel on the client:

- All clicks and other direct user interactions with item stacks are ignored
- There is no highlighting when hovering a slot
- The slot colors can be different (optional setting for `listcolors`, fall back to the “normal” slot color if not specified)
- Item tooltips still work

##### Probably Frequently Asked Questions
Q: Why?
A: Because it can be useful for formspecs in which you want to present an inventory, but not allow players to mess with it. One use case: Trading menu, in which the read-only list displays the offered item, like `easyvend` or trader NPCs.

Q: Why not using an item image button to display items?
A: Because an item image button implies the user can click it, so it would be the wrong widget to use from an usability standpoint. Also, item image buttons cannot display tool wear and item stack size.

Q: Why can't you just use the `formspec_receive` callbacks to implement read-only inventory lists?
A: Because a read-only inventory list widget would look better on the client and the user gets an instant response. With a normal inventory list that just rejects all actions, the user can still (seemingly) pick up an item stack from the inventory list, only to figure out that it doesn't work when the user tries to do anything with it. This looks and feels klunky. Hence, this suggestion. This suggestion is mostly concerned about look and feel, not about lacking functionaity.

**Comment by ClobberXD** [comment]
I agree that we need read-only list elements. The `allow_metadata_inventory_*` callbacks can be used for more specialized purposes, but they aren't suitable for completely restricting any interaction with the list - players can still click on the items and the items would still attach to the cursor, but won't drop when clicking again. This can easily be mistaken for lag, as this is exactly what happens when the server/player is lagging badly.

**Comment by DS-Minetest** [comment]
Why not using an item image to display items?
Tool wear and stack size can be done with boxes and labels.

**Comment by Wuzzy2** [comment]
Because it's too hacky to do so and it's a PITA to get all the offsets right *for every single slot*?

**Comment by paramat** [comment]
@rubenwardy or any core devs, any support for this request?

**Comment by bgstack15** [comment]
For the people who find this thread from searching the Internet for "minetest formspec read-only inventory", you can accomplish this if the formspec is on a node. In the node definition, set
```
    allow_metadata_inventory_put = allow_metadata_inventory_put,
    allow_metadata_inventory_move = allow_metadata_inventory_move,
    allow_metadata_inventory_take = allow_metadata_inventory_take,
```
And in the relevant local functions (both move and take)
```
local function allow_metadata_inventory_move(pos, from_list, from_index, to_list, to_index, _, player)
    local disallowed = {"sorter","output_preview"}
        for _, v in ipairs(disallowed) do
        if from_list == v or to_list == v then
            return 0
        end
    end
    -- more logic here
end
```

**Comment by appgurueu** [comment]
You can accomplish this for all possible kinds of inventory lists, there are inventory callbacks for detached inventories and player inventories as well.

**Comment by SmallJoker** [comment]
To disallow any interaction with the inventory list, you could try to overlay it with a transparent `box[...]` element. Note: the permission checks/safeguards in Lua are still required to prevent abuse by cheaters.
EDIT: However, tooltips and animations will no longer be shown. That's a downside.
