### ISSUE TITLE
Per-player Creative Mode

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8413]
##### Issue type
 - Feature request
 
##### Minetest version
```
5.0.0
```

##### The problem
The global setting `creative_mode` is very annoying to use.

For instance, if the server operator wants to fix some block breakage, but the server is not in Creative Mode, they have to shut the server down, turn on Creative Mode, remove a few blocks, start the server again. This sucks.

There are many other situations where the global Creative Mode is just annoying.

##### The solution
Add support for a per-player Creative Mode in the engine!

##### Design
Add a function `minetest.is_in_creative_mode(player)` that returns `true` iff the player is in Creative Mode.

The default implementation will be a simple wrapper around the `creative_mode` setting. Iff `creative_mode=true`, then the function returns true.

Now comes the trick!
Mods are allowed / adviced to overwrite this function to implement a per-player Creative Mode, in a similar fashion like `minetest.is_protected`. Usually this should be done by the game.

The setting `creative_mode` shall continue to exist. However, mods shall be adviced to start using the new function instead of reading from the setting directly. But the change is backwards-compatible: Mods that still continue to read the setting direclty won't break.

If this suggestion is adopted, the current MTG API in `creative` needs to be replaced, obviously.

##### Justification
Yes, I know, this is already implemented in MTG with the function `creative.is_enabled_for`. And yes, every game could already do such an implementation. These implementations would even work.

But this is not good enough for me. This strategy is just not flexible enough and is still annoying for coders.
For instance, if you want to write a game-independent mod that also supports Creative Mode somehow, you can't. You would have to hard-depend on the varying game creative APIs, and not all games even offer these. Dependency hell ensues. You also would have to memorize various different idioms to basically do the same thing. Ugly.

Besides, I always thought of it being kind of ugly for always checking manually the `creative_mode` setting in so many places of my code.

Hence, my suggestion for a **standard** function that all mods can call without worries. Now all a mod needs to do to support Creative Mode is to call a core function that always works without dependency hell.

I think a per-player Creative Mode is so extremely important that IMO it makes much more sense to move it to the engine, because it makes dealing with Creative Mode much less painful, less error-prone and more intuitive.

Some people might argue that a Creative Mode might be too game-specific and should therefore not be supported by the engine at all.
To that I reply that from experience, most games DO have a meaningful Creative Mode and most mods DO want to have some form of Creative Mode support.
It is true there are games where the distinction between Creative Mode on/off does not exist, but those are the exception and my proposal would not hurt them at all. In those exceptional cases, mods would still call `minetest.is_in_creative_mode` and just get the default behaviour returned. So the end result is that the 95% of games that do want a Creative Mode now have a clean standard implementation and for the remaining 5% everything stays the same.

**Comment by Linuxdirk** [comment]
I wouldn't limit this to the very specific creative mode because t is waaaaaaaay too _Minetest Game and games based on Minetest Game_ specific.

Maybe have a gamemode meta data or attribute being a named gamemode where games and mods can register custom game modes that can be changed on-the-fly for individual users.

The built-in modes could be `minetest:creative` (creative mode) and `minetest:survival` (normal mode), a third gamemode could be `minetest:explore` (not allowed to place or remove nodes, but interaction with nodes is possible)

But games could also register custom gamemodes and handle them as needed (always prefixed with the game name, same override functionality like when registering nodes).

**Comment by benrob0329** [comment]
The only problem I have with "modes" is that it always felt like something that should be handled by privileges. Games/Mods can add a `gamemode` command to grant/revoke certain privs (such as one to ignore hunger).

I feel that our current privileges system could easily be extended to support this, and that games like MTG or MCL2 could then read the creative_mode privilege and grant initial privileges accordingly.

**Comment by Linuxdirk** [comment]
> I feel that our current privileges system could easily be extended to support this

I always think of privileges as something that enables players to perform actions that are denied without having the privilege.

Controlling the game mode using privileges just does not feel right.

**Comment by benrob0329** [comment]
A "creative" priv would allow players access to infinite materials. This does not seem to clash with that idea IMO.

**Comment by tenplus1** [comment]
Here is the creative mod with 'creative' privelage added that has been tried and tested on server: https://notabug.org/tenplus1/creative
