### ISSUE TITLE
Heavy mapblock save traffic since 5.0.0 update

### ISSUE THREAD

**Issue by thomasrudin** [minetest/minetest#8414]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### OS / Hardware
Operating system: Linux
CPU: x86_64

##### Summary
Since updating to v5.0.0 there is alot more mapblock saving going on.
I attached a graph from the last few weeks:
![v47KXYr](https://user-images.githubusercontent.com/1026711/54782089-5cbb0100-4c1e-11e9-9d7c-a51f2a81b781.png)

The update from 0.4.17.1 to 5.0 was on the **16th**
Live-link: https://pandorabox.io/grafana/d/cACE6ppik/overview?orgId=1&from=1551804256187&to=1553227155659

Thats when the lag issues started, possibly due to the heavy mapblock traffic.
We have now ~~the same~~ more lag with 10 players as we had with 20+ before the update

# Steps to reproduce
(doc: https://github.com/thomasrudin-mt/mapserver/blob/master/doc/incrementalrendering.md)

* Download `watcher.sh` and `migrate.sh` from https://gist.github.com/thomasrudin/324121ca0dd6bc8a46d8b198d4a6aef5
* Set up a clean world (only mt-game) with sqlite storage
* Initialize the mtime column with `./migrate.sh`
* Explore the world around spawn and ensure that all near mapblocks are emerged
* Start the change-watcher script with `./watch.sh`
* Observe changed mapblock count while walking around in *emerged* areas

## minetest.conf
Relevant parts:
```
active_block_range = 1
server_map_save_interval = 13.3
```

## Minetest 0.4.17.1
Results:
```
mtime=1553456439, count=4
mtime=1553456452, count=16
mtime=1553456466, count=18
mtime=1553456479, count=15
mtime=1553456492, count=9
Error: database is locked
mtime=1553456506, count=16
mtime=1553456519, count=5
mtime=1553456525, count=9
mtime=1553456532, count=9
mtime=1553456540, count=6
mtime=1553456543, count=36

```

## Minetest 5.0.0
Results:
```
mtime=1553455952, count=2
mtime=1553455966, count=1
Error: database is locked
mtime=1553456339, count=15
mtime=1553456353, count=2054
mtime=1553456366, count=68
mtime=1553456367, count=1
mtime=1553456370, count=1
Error: database is locked
mtime=1553456373, count=8
Error: database is locked
mtime=1553456376, count=119
Error: database is locked
mtime=1553456379, count=1780
mtime=1553456382, count=4
mtime=1553456388, count=4

```

**Comment by paramat** [comment]
Is Minetest Game active on the server?

**Comment by thomasrudin** [comment]
Yes, but should be unrelated...

**Comment by paramat** [comment]
Probably. There may have been a 5.0.0 change that increased the number of blocks modified, i might look through the changelog to help me remember.

**Comment by thomasrudin** [comment]
I did some searching in the history between the latest versions with:
```
git diff 0.4.17.1 5.0.0 src/
```

It seems the usage of `MapBlock::raiseModified()` can have something to do with it.

```
git diff 0.4.17.1 5.0.0 src/ | grep raiseModified -C5
```

In the commit 3d66622772e66154b7624957a27f9be54c4c7c28 there was a lot of refactoring going on, including moving the `raiseModified()` to a single place:
https://github.com/minetest/minetest/commit/3d66622772e66154b7624957a27f9be54c4c7c28#diff-ad60d65b34e16a3319296bb5d683acd6R899

Don't know if that is the cause thought :/

**Comment by SmallJoker** [comment]
Pretty sure this is caused by that the metadata keeps updating frequently, causing the modified mapblock to be saved each save interval. This did not happen before: it was only saved when there were nodes changed or inventories modified. The trade-off would be to skip saving until the mapblock unloads or one of the previously mentioned events occurs.

**Comment by thomasrudin** [comment]
Any chance that the previous handling can be restored again or made configurable?
It is currently unplayable with more than 10 players :(

**Comment by thomasrudin** [comment]
Applied the fix mentioned:
* IRC: http://irc.minetest.net/minetest-hub/2019-03-22#i_5516769
* Diff: https://github.com/thomasrudin-mt/minetest/commit/30fc326fe84b3d073dd3dcce9cb721ddb0a1b216

But there is still lots of (unneeded imo) mapblock saving going on...

**Comment by thomasrudin** [comment]
Added steps to reproduce in top-comment.
I did not test that with the fix from @SmallJoker as i had no success with it on the "live" server

**Comment by thomasrudin** [comment]
I found out my particular issue i had: it was actually my fault.

It was the setting `active_object_send_range_blocks` (which in my opinion is not very well documented)
I had that not set and the default value increased in the latest release.
The strange thing is that it seems to override `active_block_range` completely.

Means:
```
active_object_range = 1
active_object_send_range_blocks = 5
```
Will trigger all abm's and nodetimers in a 5 mapblock radius :confused: instead of the expected radius 1.

About the results from the repro: no idea whats caused that, maybe mapgen far away?

Anyways, thanks for the support on IRC and here, keep up the good work :smile:

**Comment by sfan5** [comment]
Is this intended behaviour?
Should this have been documented better?

**Comment by BluebirdGreycoat** [comment]
I wish ABM range and active object (entity) range were separate things.

**Comment by Minetest-One** [comment]
maybe miss understand yes,
`#    From how far clients know about objects, stated in mapblocks (16 nodes).
active_object_send_range_blocks = 2

#    How large area of blocks are subject to the active block stuff, stated in mapblocks (16 nodes).
#    In active blocks objects are loaded and ABMs run.
active_block_range = 1

#    From how far blocks are sent to clients, stated in mapblocks (16 nodes).
max_block_send_distance = 10`

explain difference or behaviour  of "clients know about objects" and "From how far blocks are sent to clients"
block range is so far clear - low down saves a lot of cpu-time / lag

**Comment by paramat** [comment]
thomasrudin, `active_object_send_range_blocks` doesn't affect ABMs.
```
#    From how far clients know about objects, stated in mapblocks (16 nodes).
#
#    Setting this larger than active_block_range will also cause the server
#    to maintain active objects up to this distance in the direction the
#    player is looking. (This can avoid mobs suddenly disappearing from view)
active_object_send_range_blocks (Active object send range) int 4

#    The radius of the volume of blocks around every player that is subject to the
#    active block stuff, stated in mapblocks (16 nodes).
#    In active blocks objects are loaded and ABMs run.
#    This is also the minimum range in which active objects (mobs) are maintained.
#    This should be configured together with active_object_range.
active_block_range (Active block range) int 3
```
It increased from 3 to 4 in 5.0.0, initially a much larger increase was proposed but we decided to be careful, see #8050 I'm surprised this small increase makes such a big change to your server.
Are you certain that `active_object_send_range_blocks` changing from 3 to 4 causes the huge increase in mapblock saving? You tested altering that while all else is kept constant?

I'm still unsure that view-direction loading of objects is a good idea.
Could it be that, because player view directions change a lot, that objects are being rapidly saved and loaded as players look around?

**Comment by paramat** [comment]
> Means:
active_object_range = 1
active_object_send_range_blocks = 5
Will trigger all abm's and nodetimers in a 5 mapblock radius confused instead of the expected radius 1.

This needs testing as it would be a serious bug. Issue is worth keeping open just for this.

**Comment by thomasrudin** [comment]
I tested that in a sample world with sqlite:

## Setup
* Install the poshud from orwell: https://github.com/orwell96/poshud
* add `poshud.mapblock.enable = true` to the settings, to enable mapblock display (or calculate it yourself)
* Install mesecons mod: https://github.com/minetest-mods/mesecons
* mark a couple mapblock borders with blocks
* Place a blinkyplant in every mapblock (i placed them in about 10 mapblocks on a straight line)
* Stand on the start of the line and observe the blinkyplants (best by night :smile:)
* Keep `active_object_range = 1` and play around with `active_object_send_range_blocks`

## Result
* Mapblocks are active (nodetimers) coresponding to the value in `active_object_send_range_blocks`


> Are you certain that active_object_send_range_blocks changing from 3 to 4 causes the huge increase in mapblock saving? You tested altering that while all else is kept constant?

As far as i understand:
* range 3 means 3x3x3 = 27 mapblocks
* range 4 means 4x4x4 = 64 mapblocks
(i'm assuming the setting is diameter, radius would be worse)

This would mean an increase of factor 2.4 on the loaded abm's, sounds about right to me...

**Comment by Minetest-One** [comment]
mhh so maybe that was the reason so less mobile gamer could play at me also, as this also forces a lot of data to send, and to work with in this small units. I used 4 before, and now 3 - maybe if neded I can try again 4 for some days, so see the effect on lag.

**Comment by paramat** [comment]
> As far as i understand:
    range 3 means 3x3x3 = 27 mapblocks
    range 4 means 4x4x4 = 64 mapblocks
    (i'm assuming the setting is diameter, radius would be worse)
This would mean an increase of factor 2.4 on the loaded abm's, sounds about right to me...

No, the setting is for view direction loading of objects, so works out at a 19% increase in area over the previous 3 block radius, see https://github.com/minetest/minetest/pull/8050#issuecomment-451722119

A simple independent test is needed to see if `active_object_send_range_blocks` is setting the ABM radius, i'm sceptical.

**Comment by Minetest-One** [comment]
moment, "range 3 means 3x3x3 = 27 mapblocks"

range is what? radius around the gamer ? as that already mean from the gamer position, imagine that is centre of a map-block, this "range" of 3*16 nodes would active or mean 7 blocks in diameter 
So I take an World Anchor and set the Radius to just 16 nodes get 27 affected map-blocks, but this is just a radius of 1 map-block as one is 16*16*16, and depending on position different result.
So set Radius to range 3 map-blocks, set in 16+16+16 = 48 Nodes, I get 323 effected map-blocks.
If only for loading (once), or watching and reload if changed from another gamer (watch) or even activated (ABM etc.) is another thing.

**Comment by thomasrudin** [comment]
> Your way of testing seems very complex.
What is your way of testing?
