### ISSUE TITLE
Mobile app crash report

### ISSUE THREAD

**Issue by klone30** [minetest/minetest#8419]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0.23
```

##### OS / Hardware
Operating system: unkown, I'm not super techy. What I DO know:
Android version 8.1.0
Kernel version 3.18.71
Software version L212VL13a
Hardware make/model LG LML212VL
CPU:unknown

##### Summary
Sorry if this is the wrong place, tried the google play contact address (contact@minetest.net) which returned address not found.
Not sure if it's an issue with the update or something wrong on my end. Have manually installed a couple mods, but nothing too obscure. Client loads successfully and all menu options function. When I go to start singleplayer, Load screen appears saying "creating server", then the app crashes. It was playing fine a week ago. Idk where to find crash reports on my phone, but if someone can direct me or if I hunt them down ill post them.

**Comment by klone30** [comment]
Jumped into debug.txt, not sure all the technical jargon, but noticed moreores being referenced. Deleted from mods folder and app started working. Struggling to copy text from the file on my phone (struggles of cheap hardware), ill get it copied over and posted this evening.

**Comment by paramat** [comment]
Any error text will be useful to see, in case this exposes an actual bug.

**Comment by paramat** [comment]
@klone30 still happening? Are you able to copy the last 100 (approximately) lines of debug.txt into this issue?

**Comment by paramat** [comment]
Too vague, no response, no debug.txt, unconfirmed, so closing.
