### ISSUE TITLE
Added labels for versions bugs

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/minetest#8422]
Currently there's many issues in the bugtracker but many of those issues are from different versions of minetest.. 

Please added labels for versions because milestone does not reflect version origin of the bugs !

**Comment by SmallJoker** [comment]
Issues are only valid for the newest Minetest version (i.e. development builds). The 0.4.x backport branch was an exception which led to many issues like this one.
Solved by Minetest 5.0.0.

**Comment by mckaygerhard** [comment]
well obviouslly you dont understant that there's more popular servers on 0.4.X rather than 5.X currently .. a label for each branch release could help the collaboration.. but well when a project gains power.. do it waht ever wants..

**Comment by mckaygerhard** [comment]
well obviouslly you dont understant that there's more popular servers on 0.4.X rather than 5.X currently .. a label for each branch release could help the collaboration.. but well when a project gains power.. do it waht ever wants..

**as example there's the gitea project, a label for each milestrone..**
