### ISSUE TITLE
clear_craft() is reversing the recipes list

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8427]
##### Issue type
 - Bug report
 
##### Minetest version
stable-0.4, stable-5, master

##### Summary
Every time `clear_craft` succeeds in erasing recipes, the internal recipes list is reversed. This has the potential of having side effects, see https://github.com/minetest-mods/moreblocks/issues/130.

The reversal is a consequence of iterating backwards, but adding items to the new list forwards.

https://github.com/minetest/minetest/blob/5e7662ca168b47ed3e81901d53bff2eb712f571c/src/craftdef.cpp#L1005-L1013

The loop in line 1005 is iterating in decreasing order of `i`. It's creating a new list with the elements to be kept (this is done to keep O(n) algorithm complexity). And the elements are added to the new list in forward order. Therefore e.g. if the list has 5 elements, the new list will contain element 4 followed by 3, then 2, 1 and 0 (minus the ones that need to be removed).

Simply iterating forwards should be enough to preserve the current order. But a better solution would be to use `std::vector::remove_if` instead of this loop.

Albeit subtle, fixing this implies a change of behaviour, therefore I wonder if this should wait for 6.0.0, or even stay this way for compatibility.

**Comment by paramat** [comment]
I don't think changes to API behaviour have to wait if they are a good idea. We can make a news forum post and ask that mods are updated. I'd rather fix MT and cause a little mod breakage.

**Comment by paramat** [comment]
Fixed by #8712
