### ISSUE TITLE
New Warnings in Console

### ISSUE THREAD

**Issue by Ganome** [minetest/minetest#8428]
##### Issue type

 - Bug report 
##### Minetest version
```
Minetest 5.0.0 (Linux Ubuntu 18.04 LTS W/ updates)
Using Irrlicht 1.8.4
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
stepping        : 2
microcode       : 0x3d
cpu MHz         : 1200.314
cache size      : 15360 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 6
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 15
wp              : yes

RAM: 8Gbx4 Gskill DDR4 - quad channel 

GPU model:Nvidia GTX 980
OpenGL version: 4.6

##### Summary

03-27 09:26:32: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
2019-03-27 09:26:34: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
2019-03-27 09:26:36: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
2019-03-27 09:27:04: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
2019-03-27 09:27:04: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
2019-03-27 09:27:14: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
2019-03-27 09:27:14: WARNING[Server]: ServerEnv: Trying to store id = 0 statically but block (2,0,89) already contains 64 objects.
##### Steps to reproduce

I really have no idea how this problem occured.  When i went to sleep last night, everything was fine.  When i woke up, my console was being spammed with warnings.

I have seen a previous bug report, years ago, about pipeworks sending nodes into oblivion.  I have pipeworks installed on the server, and yesterday players started making all sorts of machines and using pipes.  This morning i have this warning in my console.  I have read the previous post about pipeworks might be the cause of this, but again that post was over 5 years old.  Wondering what is going on here??
[debug.txt](https://github.com/minetest/minetest/files/3014001/debug.txt)

**Comment by Ganome** [comment]
Well after hours of spamming my console, with no players logged in. I have restarted the server a few times, and left it shutdown for about an hour.  Started server back online, and "Warning:" went away..  Still no idea as to the cause or fix of this.  I didn't change any config files or anything.  Just a few simple restarts and left the server off for over 30 minutes.  Hope it doesn't return

**Comment by jhooper04** [comment]
wonder what is at that location (2, 0, 89) in the world

**Comment by ClobberXD** [comment]
There's a hard limit of 64 objects per block (mapblock, I assume). There was something in mapblock `(2,0,89)`, that was probably throwing a lot of item entities at the same location. I don't know much about the pipeworks mod, but this might probably be due to a broken pipe.
