### ISSUE TITLE
Temp-disabling player's minimap shouldn't toggle it "completely off" client-side

### ISSUE THREAD

**Issue by BluebirdGreycoat** [minetest/minetest#8431]
##### Issue type
 - Feature request
 
##### Summary
This is a problem of usability. After changing the MTG mapping kit mod on my server to only allow the minimap to be viewed while the player is actually wielding the map, I've gotten complaints which basically center on the annoyance of having to press F9 every time you want to view the minimap (again).

The problem is that calling `player:hud_set_flags({minimap = false})` has the effect of turning the client's minimap completely off, such that calling `player:hud_set_flags({minimap = true})` doesn't automatically show the minimap again—the player has to press F9. Yes, you can get used to it, but it's really a bother.

What I think should happen is for the client to "remember" the minimap on/off setting and revert to that once `player:hud_set_flags({minimap = true})` has been called on the server.

Edit: the client should also remember the minimap's zoom level, too.

**Comment by paramat** [comment]
> I've gotten complaints which basically center on the annoyance of having to press F9 every time you want to view the minimap (again).

>  but it's really a bother.

This is ridiculous, petty and trivial, it's not an issue to press a key.
If there is some good reason to change behaviour we can consider that, but otherwise :-1: 
> The problem is that calling player:hud_set_flags({minimap = false}) has the effect of turning the client's minimap completely off, such that calling player:hud_set_flags({minimap = true}) doesn't automatically show the minimap again

I can't see a problem, this can just as easily be proper and expected behaviour. If minimap is disabled, then much later enabled, you need to turn it on, make sense and is no effort.
>  the client should also remember the minimap's zoom level, too.

Again trivial and unnecessary. If minimap is re-enabled it's natural it is reset to the default zoom.

**Comment by Linuxdirk** [comment]
> This is ridiculous … I can't see a problem … trivial and unnecessary

Interesting how you react to suggestions from ACTUAL PLAYERS.

**Comment by BluebirdGreycoat** [comment]
@paramat, if the client locally elected to view the minimap while it was enabled, then it should continue to show the minimap as soon as the server (re)grants permission. Seems logical to me.

**Comment by ClobberXD** [comment]
I was recently digging around in that region of code. I think the fix is quite simple - I'll try to submit a PR tomorrow.

**Comment by Wuzzy2** [comment]
@paramat: By that logic, fly mode state must be force-disabled by the client as soon the player loses the fly privilege, forcing the player to re-enable fly mode whenever the fly priv is regained. Current behaviour is inconsistent.

**Comment by ClobberXD** [comment]
The simple solution is to handle the client's settings and server's flags separately, so that the minimap state would be intact irrespective of whether the server allows or disables the minimap.

**Comment by ClobberXD** [comment]
WIP fix: #8441

**Comment by paramat** [comment]
PR seemed supported before is was closed so adding the supported label.

**Comment by ClobberXD** [comment]
The functionality offered by the original PR is also provided by #9079, which when merged should resolve this issue.
