### ISSUE TITLE
override.txt parsing fails on Linux on lines with CRLF endings

### ISSUE THREAD

**Issue by kestral246** [minetest/minetest#8439]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0
```

##### OS / Hardware

Operating system: Linux

##### Summary
Minetest on Linux is unable to parse lines in the override.txt file if they contain dos-style CRLF (\r\n) line termination.  They generate errors like the following:

```code
ERROR[Main]: generateImage(): Could not load image "mcldefault_grass_side.png
ERROR[Main]: " while building texture; Creating a dummy image
```
##### Steps to reproduce
While running Minetest on Linux, use a texture pack that has an override.txt file that is actually being used. I found this issue using the LessDirt texture pack, which only uses the override.txt file when used with MineClone2 textures. (The texture pack owner has since removed the CR (\r) to get it to work in Linux.)
- `file override.txt` will tell if file has CRLF line termination.
- `unix2dos override.txt` will convert a working file to CRLF line termination for test.

Here is the link to the forum topic on this issue: [override.txt issue](https://forum.minetest.net/viewtopic.php?t=22442)

The following patch seems to fix the problem:
```diff
--- a/src/nodedef.cpp
+++ b/src/nodedef.cpp
@@ -1292,6 +1292,9 @@ void NodeDefManager::applyTextureOverrides(const std::string &override_filepath)
        int line_c = 0;
        while (std::getline(infile, line)) {
                line_c++;
+               // Remove dos-style '\r' if last character of line
+               if (!line.empty() && line.back() == '\r')
+                       line.pop_back();
                if (trim(line).empty())
                        continue;
                std::vector<std::string> splitted = str_split(line, ' ');
```

**Comment by SmallJoker** [comment]
40dadecb6ece6c9bbf7739e3a44ace25c0716dec
