### ISSUE TITLE
Text overlay for  inventory images per-stack

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8444]
##### Issue type

 - Feature request

##### Summary

It'd be great to be able to set a text overlay per-stack in a straight-forward manner (maybe using a special stack meta field?). The position of the overlay would have to be customizable, as this isn't a texture to directly overlay on `inventory_image`. The text overlay rendering code is already in place (think stack count display); this is just a feature request for exposing this to the API for mods to use this for their custom overlays.

##### Use-cases

- Displaying number of rounds remaining in loaded clip for gun mods.
- Number of uses remaining for a tool - they don't have stack count display anyway.

**Comment by ClobberXD** [comment]
@paramat There's an open PR for this feature request (#8448). I don't think "Possible close" and "No core dev support long term" apply to this issue.

**Comment by paramat** [comment]
Ok thanks, removed labels.
