### ISSUE TITLE
Peer to Peer Networking

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#8446]
##### Issue type

 - Feature request

##### Summary

Implement P2P multiplayer (to create multiplayer games without firewall configuration). Is that even possible???

**Comment by benrob0329** [comment]
If you mean a decentralized world, then no its not currently possible.

If you mean doing the proper hole-poking via UPnP for locally hosted servers, then that is probably possible.

**Comment by rubenwardy** [comment]
Peer to peer will never be supported, but there are other ways to get multiplayer networking without port forwarding - one is nat punch through

**Comment by nerzhul** [comment]
you cannot really be peer to peer as there is a map somewhere which needs to be managed centrally

**Comment by Pantyhose-X** [comment]
> Peer to peer will never be supported, but there are other ways to get multiplayer networking without port forwarding - one is nat punch through

Building Minetest servers on the [Hypercore protocol](https://hypercore-protocol.org/) is perfectly suited to meet this need

**Comment by Pantyhose-X** [comment]
Building Minetest servers on the IPFS protocol is perfectly suited to meet this need
[![](https://nicola.io/peerpad/images/how-it-works.png)](https://nicola.io/peerpad/#/#how-it-works)
