### ISSUE TITLE
Minetest can't handle czech keyboard layout properly.

### ISSUE THREAD

**Issue by Pitriss** [minetest/minetest#845]
I have latest MT from git running on linux, compiled with irrlicht 1.7.3. When I have keyboard set up as Generic 105 keys - international, czech layout, default version, then I can't write characters like ( and ), key 4 behave like enter and 7 can be entered only in chat console.. This will NOT happened when i set US keyboard layout.

Some issues was mentioned also here: https://github.com/minetest/minetest/issues/373

How to reporduce, set your keyboard layout to czech one and try to write numbers and parenthesis, they will not work and key 4 will act like enter key.

**Comment by nerzhul** [comment]
Irrlicht 1.9 will fix the issue, it's not a problem with minetest. We must wait for irrlicht 1.9 to be released

**Comment by deltaflyer4747** [comment]
Just wanted to say that i just tried to compile against an 1.9 irrlicht and it fails with:

2017-11-19 09:19:33: WARNING[Main]: Couldn't find a locale directory!
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  3 (X_GetWindowAttributes)
  Resource id in failed request:  0x1
  Serial number of failed request:  26
  Current serial number in output stream:  27

**Comment by paramat** [comment]
Duplicate of #3170 but discussion is best continued there.
