### ISSUE TITLE
Didn't get a confirmation email 

### ISSUE THREAD

**Issue by catinapoke** [minetest/minetest#8454]
##### Issue type
- [x] Confirmation email  
![Trouble](https://screenshotscdn.firefoxusercontent.com/images/b2e2092a-a849-48b2-a4dc-c876d2ef90b8.png)

Can you please activate my account on MineTest forum? Login - ~~ removed~~

**Comment by ClobberXD** [comment]
@catinapoke Only code-related issues are filed through GitHub issues. You'll get better response on our IRC channel (`#minetest`).

Quick link to the IRC channel: https://webchat.freenode.net/?channels=%23minetest
