### ISSUE TITLE
Support custom rotation values for [transform

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8465]
##### Issue type

 - Feature request

##### Summary

Image modifier `[transform` supports very limited rotation (i.e. 90, 180, and 270 degree counter-clockwise rotations only). Making `[transform` support custom rotation (e.g. `[transformR30`) would allow for finer and more precise rotation and would be way more useful than it currently is.

**Comment by Calinou** [comment]
Rotating by non-90-degree increments is much more complex from an image manipulation side.

**Comment by ClobberXD** [comment]
Yes, I'm aware. :)

Looking through the code, the pixels are individually mapped according to the rotation value (90, 180, or 270), which wouldn't work for custom angles.

But I'm just throwing it here in case someone comes up with a relatively simple implementation (or even the complex implementation - it might just be worth it).

**Comment by paramat** [comment]
Has anyone out there needed this? Trying to gauge need.

**Comment by ClobberXD** [comment]
Erm... me?

****

Here's my specific use-case:
- I'm making the item point straight to the left in the inventory image.
- I'm using the `inventory_image` as the `wield_image` as well (because no one would use different images for these fields, right? :P).
- But the wielditem points ~45 degrees towards the ground instead of straight ahead.
- There's no way to correct this, apart from duplicating the `inventory_image` and rotating it 45 degrees using an image editor.

If an image editor can do it, why can't MT? Yes, image editors are created from ground up to edit images, but image rotation is one of the relatively simpler image manipulations, AFAIK. There are also so many more complex texture modifiers in MT that are barely used compared to the arguably more fundamental `[transform`.

**Comment by Linuxdirk** [comment]
For the same reasons as https://github.com/minetest/minetest/issues/8020 is an issue the rotation of non-90° is not possible.

So implementing some sort of anti-aliasing filter could solve both issues.

**Comment by paramat** [comment]
I don't think the request of this issue is worth implementing.
Texture transformations are not meant to provide all, or even most, image editing functions. They only provide a very limited number of heavily used functions. Non-aligned rotations are rarely needed.
They are also complex to implement, needing neighbour-pixel interpolation.
Specialist image editing should be left to image editors.
:-1:

**Comment by ClobberXD** [comment]
My use-cases are satisfied by #8755. I'll close this issue, as this is a problematic feature to implement.
