### ISSUE TITLE
Inaccuracies in code style linter

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8467]
clang-format doesn't always follow our code style. Here is an issue to list the discrepancies

-----

```c++
if ((event.KeyInput.Key == KEY_ESCAPE ||
		event.KeyInput.Key == KEY_CANCEL) &&
		event.KeyInput.PressedDown) {
	closeMenu(false);
	return true;
}
```

**Comment by paramat** [comment]
See #6034 , similar issue, i should perhaps have kept that open.
Also #6766

Is it actually possible to fine tune a linter to such a degree that it mostly works?
Of course, it will inevitably fail often as readable code is often decided by human judgement.

**Comment by Calinou** [comment]
> Is it actually possible to fine tune a linter to such a degree that it mostly works?

I'm quite sure that's possible. Sometimes, it may result in less readable code, but the benefit of avoiding bikeshedding may be more important.
