### ISSUE TITLE
Feature request: Minimal first-press-of-F5 display, for normal users without debug priv

### ISSUE THREAD

**Issue by VanessaE** [minetest/minetest#8472]
There should be a minimal first-press-of-F5 display that ALL players get to see, without needing debug privilege.

It should show the direction you're facing, your coordinates, and the node you're pointing at.

The existing first-press-of-F5 that shows those things along with drawtime, map seed, etc., and subsequent displays after that, should continue to need debug privilege.

This would aid players in doing things that should be on a regular grid or spacing, like building roads or placing streetlights every 10 meters, for example.

I see no potential issues with any and all players being able to see their direction, position, and pointed_thing name.

#7245 looks like it's similar, but my suggestion is far simpler imho.

**Comment by ClobberXD** [comment]
I'd really prefer every individual feature to be toggle-able per-player (sorta like HUD flags).

> There should be a minimal first-press-of-F5 display that ALL players get to see, without needing debug privilege.
>
> It should show the direction you're facing, your coordinates, and the node you're pointing at.

While this sounds quite reasonable, this should rather be implemented in games, IMHO, as these aren't universal to all games (see below). This is possible by granting a priv, and enabling the extra stuff in the `on_grant` callback.

> I see no potential issues with any and all players being able to see their direction, position, and pointed_thing name.

Even those would pose problems for servers/games:

- Position/Direction - Bad for survival-in-the-wild type of games, where the player has to navigate using only the natural elements around them. e.g. ascertain North using the sun or pole star, re-trace by looking for "breadcrumbs", etc.
- pointed_thing name - Bad for hidden elements, and look-alike elements in a game (e.g. fake nodes, traps, etc.). See also: https://github.com/minetest/minetest/issues/7245#issuecomment-476697190

**Comment by DS-Minetest** [comment]
>The existing first-press-of-F5 that shows those things along with drawtime, map seed, etc., and subsequent displays after that, should continue to need debug privilege.

Afaik, the first debug mode currently doesn't need any priv.

Also, I don't think that the map seed or the drawtype of a node is dangerous.

**Comment by ClobberXD** [comment]
> Also, I don't think that the map seed or the drawtype of a node are dangerous.

Taken from https://github.com/minetest/minetest/issues/7245#issuecomment-460594967 (which quoted https://github.com/minetest/minetest/issues/4556#issuecomment-325414467):

> If someone has the seed of a world, it's likely that they can replicate a server's world for themselves, and then you could write your own mod for spotting ores or other useful things.

**Comment by paramat** [comment]
> The existing first-press-of-F5 that shows those things along with drawtime, map seed, etc., and subsequent displays after that, should continue to need debug privilege.

I could be wrong, but doesn't debug priv only affect wireframe mode?
> It should show the direction you're facing, your coordinates, and the node you're pointing at.

I don't think these need debug priv.

**Comment by paramat** [comment]
![screenshot_20190415_220205](https://user-images.githubusercontent.com/3686677/56165158-275dc500-5fca-11e9-8159-d33ad3ed46de.png)

Tested on local server, player with only privs 'shout', 'interact' sees all that in F5.

**Comment by VanessaE** [comment]
Strange... well then I guess close this.  Only reason I brought up is one of my players reported no response when they pressed F5, and they lack that priv....

**Comment by LoneWolfHT** [comment]
> Strange... well then I guess close this. Only reason I brought up is one of my players reported no response when they pressed F5, and they lack that priv....
They may have to press `FN + F5`
