### ISSUE TITLE
Changing password on mobile may put new password in chat

### ISSUE THREAD

**Issue by archfan7411** [minetest/minetest#8476]
##### Issue type

 - Bug report

 
##### Minetest version

```
5.0.1
```

##### OS / Hardware

Operating system: Android
CPU: Unknown

GPU model: N/A
OpenGL version: Unknown

##### Summary

On the server Frost Factions, mobile players have reported that changing their password inputs the new password in the chat. The players confirmed that they were running the official Android Minetest.

I cannot personally test this due to the lack of a mobile device with Minetest.

##### Steps to reproduce

Open the password changing dialogue on Android.
Change your password.

**Comment by Wayward1** [comment]
I can confirm, running latest Minetest from the Play Store.
![Screenshot_2019-04-17-10-51-48](https://user-images.githubusercontent.com/8821916/56298152-a86aa880-60ff-11e9-9a53-2488103b11b0.png)

```
2019-04-17 10:50:41: ACTION[Server]: me joins game. List of players: me
2019-04-17 10:50:41: WARNING[Main]: Client side scripting is disabled by client.
2019-04-17 10:50:58: ACTION[Server]: CHAT: <me> test
2019-04-17 10:51:24: ACTION[Server]: CHAT: <me> hahaha
2019-04-17 10:51:31: ACTION[Server]: CHAT: <me> hahahalol
2019-04-17 10:51:39: ACTION[Server]: CHAT: <me> hahahalol

**Comment by archfan7411** [comment]
Was this perhaps a feature for debugging that accidentally made it into release?

**Comment by ClobberXD** [comment]
Regression probably introduced by 323c860. @stujones11

**Comment by stujones11** [comment]
Perhaps a little unfair to call it a regression when this form never worked on android before that patch, however, I have found the actual cause and have submitted a PR

**Comment by ClobberXD** [comment]
> Perhaps a little unfair to call it a regression when this form never worked on android before that patch...

Apologies for mis-wording this issue (didn't pay much attention to what I was typing). A bug it is... :)
