### ISSUE TITLE
Client-side modification of player properties based on wielded item

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8477]
##### Issue type

 - Feature request

##### Summary

This is basically a feature request to allow player properties to be modified client-side based on the item the player is wielding. There are a ton of valid use-cases for this, like slowing down the player when they're carrying something heavy (miniguns, anyone?) - physics modifiers aren't a part of object properties, I know, but I'm talking about all the attributes of a player that can be modified server-side, not just the "object properties". :)

Currently, the only way to achieve this is to retrieve wielditem of all connected players and modify each of their properties in a globalstep server-side - this would obviously introduce a lot of lag, and the resulting experience would be even worse than if this feature did not even exist in the mod.

##### Implementation details
The properties that need to be modified could be passed within each item's def during definition. The client would then update the player's properties each time the player's wielditem changes. The client-side changes are relatively very simple - how this would have to be integrated into the item def is the hard part.

**Comment by ClobberXD** [comment]
I don't think this would be required if SSCSM is in place. This feature request can be closed if and when SSCSM has been implemented.

**Comment by benrob0329** [comment]
Don't we have on_wield?

**Comment by ClobberXD** [comment]
Not yet. There's a PR for adding a callback on wielditem change (#7587), but this would still be laggier than handling this completely client-side.

**Comment by benrob0329** [comment]
Yes but the callback can be run without updated clients, and is more flexible than hardcoding an override table.

**Comment by paramat** [comment]
> I don't think this would be required if SSCSM is in place.

Best this feature isn't added then, as SSCSM will almost certainly happen 'soon', as it's the only reason CSM exists.

**Comment by PowerOlive** [comment]
what's the soon's soon
zaoqi's minetest-cheat still can be use

**Comment by DS-Minetest** [comment]
> what's the soon's soon
> zaoqi's minetest-cheat still can be use

I guess, you are referring to #5998.
SSCSM can not do anything against modified clients.
Afaik, minetest works so that there should be no way to cheat without modifying any sourcecode. Anything else would be on the cost of player experience. (Eg. without `disable_anticheat` the server lags more and the players have to wait for their dug nodes to appear and disappear again.)
Anyway, sscsm has nothing directly to do with anticheat. It's just scripts that are sent to the client to be executed. (The client can of course be modified to not run the scripts (or to modify them before running).)

**Comment by paramat** [comment]
> This feature request can be closed if and when SSCSM has been implemented.

Let's do this the other way, this can be reopened if SSCSM is not added reasonably soon, nerzhul is intending to do so.

**Comment by PowerOlive** [comment]
so you will wait another two years to make on_wield fun again
