### ISSUE TITLE
use SUFIX for build or change&custom binery and path for files installation

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/minetest#8479]
##### Issue type
 - Build issue
 
##### Minetest version
```
all 5.0.0 or 0.4.17 or 5.0.1
```

##### OS / Hardware
Operating system: Linux
CPU: Xeon

##### Summary
How&Where i can change the files reference, by example the locales files referes to [INSTALLPATH]/share/locale/<lang>/minetest.mo but changin to minetest4.mo or minetest5.mo ?

**or maybe use a SUFIX like the old style configure & make from old times, how to do that? for example toa "minetest501 sufix=501**

**Comment by SmallJoker** [comment]
Create a docker image or create an Appimage if that's possible.

**Comment by mckaygerhard** [comment]
no it's not possible due that solution always depends of network and if i have a 5.0.1 version working i dont want to upgrade a working version with my working plugins.. currently there's still used 0.4 servers today! ok

**Comment by andriux1990** [comment]
I don't have to set up a docker, I don't have internet all the time

**Comment by rubenwardy** [comment]
You don't need to install minetest, you can compile a run in place build of a different version and use that

**Comment by SmallJoker** [comment]
Compile MInetest with RUN_IN_PLACE=1 and you'll be fine. No need to add settings solely for the purpose of having 0.4.x and 5.x both system-wide installed.
