### ISSUE TITLE
Collisionbox of attached entity dissapears

### ISSUE THREAD

**Issue by Elkien3** [minetest/minetest#8480]
- Bug report

```
Minetest 5.0.1 stable Windows 64 bit
```

##### OS / Hardware
Operating system: Windows 10
CPU: Intel(R) Core(TM) i7-6700H

##### Summary
Collisionboxes of entities that are attached to other objects disappear when its x,y, or z is more than 200 or less than -200 blocks . They come back sometimes if you get about 10-20 blocks from 0,0,0, or if you bring the x, y, and z under |200| and restart the server. The mesh of the attached item remains the same, but the collisionbox is gone.

##### Steps to reproduce
I made a little test mod that has an entity that attaches another entity to itself on_activate then follows the closest player. [entitytest.zip](https://github.com/minetest/minetest/files/3096491/entitytest.zip)

Start a world, go near 0,0,0, and use `/spawnentity entitytest::test` to spawn in the test entity.
The main entity is the stone block, and the attached one is the tree above it. if you spawned it near 0,0,0, the tree should have a collisionbox around it.

start walking away from 0,0,0. and keep an eye on it as you get closer to passing x, y, or z 200 or -200, once it passes 200 or -200 the tree's collisionbox should disappear.

**Comment by SmallJoker** [comment]
#8037
