### ISSUE TITLE
CMake does not pick up build flags from `curl-config`

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/minetest#8482]
##### Issue type
 - Build issue
 
##### Minetest version
```
5.0.0
```

##### OS / Hardware
Operating system: Linux
CPU: i7

##### Summary
got `undefined reference to RTMP_Free` when just finish compiling and when get linking got that problem

##### Steps to reproduce
configure cmake and just make

**Comment by mckaygerhard** [comment]
after some investigations seems the `libcurl.a` must be linking using `target_link_libraries` from cmake.. but i dont know how!

please can provide me directions to solve it?

**Comment by mckaygerhard** [comment]
after some investigations got the problem: its due minetest cmake does not property use the curl's `curl-config` utility and does not property linking.. the linking relly on other program.. this makes causing problems in chrooted and minimalistig environments for static builds

```
CMakeLists.txt
@@ -770,6 +770,8 @@ else()
 	if(MINGW)
 		set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -mwindows")
 	endif()
+
+	SET( CMAKE_EXE_LINKER_FLAGS  "${CMAKE_EXE_LINKER_FLAGS} -lidn -lrtmp -lcom_err -llber -lz -lrt" )
 endif()
```

i do not jhave exact link flags but i suspect with `-lrtmp` are enought. but **real problem its the not right usage of the curl config utility that provides right linker**

and please **stop to say "update to lasted" i not using windo!**

**Comment by rubenwardy** [comment]
Needs reproducing
