### ISSUE TITLE
[Content DB] Multiple sources for content

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#8484]
##### Issue type

 - Feature request
 
##### Summary
Currently the Minetest content database hosted at content.minetest.net is the main source for having content in the in-client content store. The system allows changing this by changing the `contentdb_url` to another server and hosting an own instance of the content database.

A nice feature would be having a list of hosts instead of a single value, working similar to most Linux distribution’s package managers that allow adding multiple repositories that can be searched and installed software from.

This would allow users to establish and maintain custom repositories as well as having the “standard content”.

Use cases:

1. Content can be provided to groups of singleplayers without causing unnecessary amounts of traffic on content.minetest.net when running a server for them is not wanted or possible.
2. Repositories can be hosted in the LAn for machines that do not have Internet access.
3. Content that is not allowed in the standard content database can be added via custom repositories.
4. Maintainers can offer highly experimental content to their testers without any hassle even if that mods likely break Minetest and thus might not be approved.

Implementation could be done by loading the contents and prefixing them to avoid confusion (`repository:contentname` as ID and `repository_contentname` as folder name).

**Comment by PowerOlive** [comment]
also a socks5 proxy support would be nice in some slowly network countries

**Comment by rubenwardy** [comment]
I don't want to implement or maintain this. It's better for this to be done separately from Minetest itself, as simple web servers which can cache the content and multiplex
