### ISSUE TITLE
formspec: scrollbar bars should vary in height

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#8486]
##### Issue type
 - Feature request

##### Summary

Scrollbars have a background and a thing that you can grab, I'll call this thing bar.

&ensp; In many programs the scrollbar bars are so high that the ratio of the bar height to the background height corresponds to the ratio of what you can see to what you could see by accessing it with the scrollbar.
&ensp; In Minetest however, for most (or all?) formspec elements that add a scrollbar, like `textarea`, the scrollbar has always the same height. This also applies for mainmenu and pause uis (for an example look at the image in #7093).
&ensp; Imo this makes the scrollbar very uncomfortable. I request it to be changed to work like described two paragraphs earlier.

Here's an image to illustrate what I mean:
![minetest_scrollbar_size](https://user-images.githubusercontent.com/7613443/56591422-ff351e00-65e8-11e9-94a7-36a394318d9d.png)

**Comment by stujones11** [comment]
AFAIK, Minetest simply uses Irrlicht's built-in scrollbar which has this limitation. Possible solutions include patching Irrlicht `CGUIScrollBar.cpp` or rolling our own scrollbar class. It may even be possible to just sub-class the existing IGUIScrollBar and override its draw method, I didn't check.

What also might be nice for touchscreen devices (Android) is if list-boxes, etc. could be scrolled by simply dragging them, however, that would be a even more work.

**Comment by DS-Minetest** [comment]
> What also might be nice for touchscreen devices (Android) is if list-boxes, etc. could be scrolled by simply dragging them, however, that would be even more work.

There's already another issue about this: #2311

**Comment by stujones11** [comment]
> There's already another issue about this

Thanks, I remember this being suggested elsewhere but thought it was on the forum.

**Comment by stujones11** [comment]
Incidentally, I came across this (very) old Irrlicht forum topic about this very subject. Things are unlikely to have changed very much so some of linked patch may still be helpful to whoever may take this on. I may even look at it myself when I get time.

http://irrlicht.sourceforge.net/forum/viewtopic.php?f=2&t=44416

Note that those guys are pretty major contributors to the Irrlicht project.

**Comment by DS-Minetest** [comment]
It looks like `CGUIScrollBar` [uses a `private` `rect` `SliderRect`](https://sourceforge.net/p/irrlicht/code/HEAD/tree/tags/release-1.8/source/Irrlicht/CGUIScrollBar.cpp#l166) [with the height `private` `DrawHeight`](https://sourceforge.net/p/irrlicht/code/HEAD/tree/tags/release-1.8/source/Irrlicht/CGUIScrollBar.cpp#l301) [which is the width (of height if horizontal) of](https://sourceforge.net/p/irrlicht/code/HEAD/tree/tags/release-1.8/source/Irrlicht/CGUIScrollBar.cpp#l363) [`protected` `RelativeRect`](http://irrlicht.sourceforge.net/docu/classirr_1_1gui_1_1_i_g_u_i_element.html#af093935f3d5f6c3efedddc8bcdf7fc82).

CuteAlien has added a `ThumbSize` in his patch.

Is it possible to replace only `CGUIScrollBar.h` (but not `CGUIScrollBar.cpp`) to make `DrawHeight` `protected` and then inherit?

**Comment by stujones11** [comment]
Yeah, you'd probably need to pretty much clone the existing class and make a new one with your changes, otherwise an Irrlicht patch which is unlikely to be accepted for anything but the android port.

That said, it's only around 500 lines of code so may still be doable.

**Comment by DS-Minetest** [comment]
A change like [this](https://github.com/DS-Minetest/minetest/commit/ed83125652abfd0724dbb1f3b8ac9c50bed01eaa) might be sufficient.
I think, this might be actually what Lonesome Ducky described with the difference that the arrow buttons at the top and bottom are considered and the slider can have a specific length. Eg. if one slide step is two pixels of text, the text is 1000 pixels high and you can see 200 pixels at once, you set the sliderheight to 200/2=100 (the range of the scrollbar will be from 0 to 500).

**Comment by stujones11** [comment]
Indeed, you wouldn't need to change much to get it this work, however, we don't really have that option, except for android where we compile our own static lib as part of the build process.

I have often though we should go the way of STK and maintain our own fork of Irrlicht but I don't see that happening anytime soon.

**Comment by v-rob** [comment]
A potential problem with this is that scrollbar elements themselves are always restricted to a range of 1-1000, so the scrollbar would always be the same height for them anyway.  So allowing different values for scrollbar widgets would be essential to go with this.  All the other widgets with built-in scrollbars would be fine, though.

**Comment by stujones11** [comment]
> scrollbar elements themselves are always restricted to a range of 1-1000

I do not see this restriction anywhere in the `CGUIScrollBar` code, perhaps this is a limitation of the Lua formspec element, however, that is generally used a slider control rather than a scrolling mechanism. Content over-spill is handled automatically by the container.

**Comment by DS-Minetest** [comment]
> > scrollbar elements themselves are always restricted to a range of 1-1000
> 
> I do not see this restriction anywhere in the `CGUIScrollBar` code, perhaps this is a limitation of the Lua formspec element?

https://github.com/minetest/minetest/blob/e32a630937de69454c741e93979a7889fcddc7a9/doc/lua_api.txt#L2204
https://github.com/minetest/minetest/blob/f409f4476539f32dcce3ff6832be4bc48bd25634/src/gui/guiFormSpecMenu.cpp#L519-L520

**Comment by DS-Minetest** [comment]
The [scrollbar](https://github.com/minetest/minetest/blob/a1459a9eac4eeb35a6c578a8b8f96393f87ed53d/doc/lua_api.txt#L2196-L2206) element should of course be made better, but that's for another issue. I'll close this.
