### ISSUE TITLE
can i use autojump on pc

### ISSUE THREAD

**Issue by PowerOlive** [minetest/minetest#8489]
it can also used without android i think

**Comment by ClobberXD** [comment]
https://github.com/minetest/minetest/blob/f409f4476539f32dcce3ff6832be4bc48bd25634/minetest.conf.example#L83

**Comment by PowerOlive** [comment]
oh thanks

**Comment by PowerOlive** [comment]
i will see the doc more

**Comment by PowerOlive** [comment]
:) you change it
