### ISSUE TITLE
how to set minetest to use proxy without crash

### ISSUE THREAD

**Issue by PowerOlive** [minetest/minetest#8490]
i am tired of
typing
zsh/ proxychains minetest
into my terminal

**Comment by PowerOlive** [comment]
i mean socks5

**Comment by PowerOlive** [comment]
i've tried the curl

**Comment by ClobberXD** [comment]
While not a duplicate of #8136, this discussion can be continued there.

**Comment by SmallJoker** [comment]
If you're tired typing, create a starter or script for it.
