### ISSUE TITLE
Let me move the dirs

### ISSUE THREAD

**Issue by SoniEx2** [minetest/minetest#8492]
##### Issue type
 - Feature request
 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

let me move the config dir, save dir, etc dir, etc, etc etc, and so on. All that stuff. i don't want it on the home dir. I want it on a-whole-nother drive.

I also can't edit github issues and comments because github is bad.

**Comment by SmallJoker** [comment]
ffs, there's an edit option for your posts.
![Edit](https://user-images.githubusercontent.com/1497498/56849910-3cf0ba00-68fb-11e9-8cc9-c993ee9ddde3.png)

Compile Minetest with RUN_IN_PLACE=1 (default for Windows), so you can just cut&paste the entire Minetest directory onto a new drive. Replace the directories with symlinks if you want to use the system-wide installation.

**Comment by SoniEx2** [comment]
that edit button does absolutely nothing for me.

**Comment by MoNTE48** [comment]
@SoniEx2 You have to use a modern browser, and then it will work.

**Comment by SoniEx2** [comment]
in any case, being able to move the dirs means I can also use different dirs (i.e. "profiles") if I want to, without having to reinstall and stuff.

a thing I made (unrelated to minetest) uses XDG ( https://cybre.tech/SoniEx2/ganarchy/src/branch/master/ganarchy.py ) and I have to use the XDG variables all the time because it can only handle one project at a time but I have multiple projects I wanna keep track of so I use different XDG locations for the different projects.

**Comment by paramat** [comment]
"Let me move the dirs" what actually is your request? This is a deliberately poorly worded request.
If this is an XDG request then it will be closed as a duplicate.

**Comment by paramat** [comment]
Stop being annoying. If you open an issue word it properly, you are deliberately wording your recent requests in a sloppy way.

**Comment by paramat** [comment]
Instead of being irritating and opening an identical issue, add the required information to #8491 , we can re-open it if necessary. This was made clear in that issue:
> Edit your text and (ask to or) re-open this issue afterwards.
Not enough information, closing.
