### ISSUE TITLE
brew install minetest does not result in a working installation

### ISSUE THREAD

**Issue by lschierer** [minetest/minetest#8498]
##### Issue type
 - Bug report
 
##### Minetest version

```
stable 5.0.1 (bottled), HEAD
```

##### OS / Hardware

Operating system: OSX 10.14.3  
CPU: 3 GHz Intel Core i7

##### Summary
the documentation says to use homebrew to install the latest stable version.  It appears it should install to /Applications but nothing ends up there, nor in /usr/local with the normal brew installed stuff.
From the wiki it looks like this depends on the deprecated brew linkapps 
the build should be updated to not need that.

**Comment by sfan5** [comment]
The brew "recipe" (or whatever they call it) is not maintained by us.
