### ISSUE TITLE
Entities disappears by right clicking.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8499]
##### Issue type

 - Bug 
 
##### Minetest version
```
5.0.1
```

I noticed any entities which were right clicked by a player sometimes removed as if they would be destroyed. I guess this is a bug in the game.

**Comment by ClobberXD** [comment]
Have you checked whether the `on_rightclick` callback defined to remove the entity?

**Comment by paramat** [comment]
Does it happen when using MTG only? Could be a mod issue.

**Comment by Andrey2470T** [comment]
paramat: I don`t know whether it happens in other games. I found that bug in MTG.
ClobberXD: yes, it removes. But it removes sometimes and as I understood if click the entity when it`s putting in the world at the same time.

**Comment by paramat** [comment]
I mean, are you running any mods?

**Comment by Andrey2470T** [comment]
I`m just making cars mod and I noticed after the coding a while cars had stopped disappearing on_rightclick. It seems a bug was in my mod.
