### ISSUE TITLE
Online Content Browser fails on Android

### ISSUE THREAD

**Issue by neildarlow** [minetest/minetest#8503]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.0.23
```

##### OS / Hardware
Hardware: Huawei Honor 8X
Operating system: Android 8.1.0 / EMUI 8.2.0
CPU: Hisilicon Kirin 710

##### Summary
Attempts to use the Online Content Browser result in a traceback caused by an assert failure.

##### Steps to reproduce
1) Create a World - not sure if this is necessary
2) Access the Online Content Browser
3) Observe traceback dialog and application is in a frozen state

Attached is screenshot of traceback dialog. I couldn't scroll due to application being frozen.

![Minetest_traceback](https://user-images.githubusercontent.com/6245505/56950905-6b0a1000-6b2e-11e9-827c-b51d11e28675.jpg)

**Comment by ClobberXD** [comment]
Relevant section of code:
https://github.com/minetest/minetest/blob/e32a630937de69454c741e93979a7889fcddc7a9/builtin/mainmenu/dlg_contentstore.lua#L270-L273

And here's the definition of `core.create_dir`:
https://github.com/minetest/minetest/blob/e32a630937de69454c741e93979a7889fcddc7a9/src/script/lua_api/l_mainmenu.cpp#L693-L703

Assertion fails because MT probably wasn't able to access the OS's native temp dir (missing perms or lack of storage space maybe?). MT seems to be running from a flash drive. I wonder if that has something to do with the assertion failing...

**Comment by neildarlow** [comment]
I am running Minetest on an Android Phone.

Internal storage is 17.74GB of 64GB used and Memory card is 438.04MB of 64GB used.

The default storage is chosen as Memory card and Minetest has been granted Storage permission.

I don't see any content in Android/data/net.minetest.minetest/files on either Internal Storage or Memory card so access might be the problem.

I can start Minetest, create a world and start the game on that world without issue.

**Comment by neildarlow** [comment]
Here's todays content from debug.txt:

[debug.txt](https://github.com/minetest/minetest/files/3130773/debug.txt)

**Comment by ClobberXD** [comment]
Ah, right. I remember there being issues about the content store misbehaving on Android, but can't find them at the moment...

**Comment by stujones11** [comment]
My guess is the hard-coded path https://github.com/minetest/minetest/blob/e32a630937de69454c741e93979a7889fcddc7a9/src/defaultsettings.cpp#L436

`/sdcard` seems to work for most devices, certainly all of mine but there may be some situations where this is not a valid path.

If I am correct then the fix would be to use the file path returned by `porting::path_storage` to obtain the initial default for value for `TMPFolder`

@neildarlow You could try changing this setting to the correct path for your device. That should be where minetest is currently located.

**Comment by neildarlow** [comment]
Minetest seems to respect the fact that the default storage location on my device is the sdcard. It has created a Minetest folder in the root of the sdcard and populated it with even a tmp folder. Wouldn't it be expected that this tmp folder should be used?

**Comment by stujones11** [comment]
> Wouldn't it be expected that this tmp folder should be used?

Indeed, it does use the correct path elsewhere, only here it is hard-coded.

**Comment by stujones11** [comment]
@neildarlow I have made a build with my proposed fix: https://www.dropbox.com/s/edvi5hueelnmmlz/Minetest-debug.apk?dl=0

If you could verify this does fix your issue I can submit a PR.

**Comment by neildarlow** [comment]
@stujones11 Excellent. The Content Browser shows and I downloaded and installed the Crafting Guide without any problems.

**Comment by LandonAConway** [comment]
It is probably cause of the fact that the minetest servers and forum is down and nobody cares or is trying to fix it.
