### ISSUE TITLE
Keys work incorrectly

### ISSUE THREAD

**Issue by MineWitherMC** [minetest/minetest#8504]
##### Issue type
 - Bug report
 
##### Minetest version
```
5.0.1 or e32a6309
```

##### OS / Hardware
Operating system: Manjaro Openbox latest
CPU: Intel Core I5-4200H @ 2.8 GHz

##### Summary
Keys `R`, `L`, `D`, `A` and  `S` don't work in New World textbox. `R` just closes it, others do nothing. The following is written in the logs (twice for some reason):
```
Could not find EKEY_CODE, using orig. X11 keycode instead: *some number*
```
The same is written for other keys, which do work.

##### Steps to reproduce
* Run minetest, preferably via command line
* Write these letters into world name textbox
* Observe the bug

##### More things I've noticed
* In game, `R` works as a pause button for me, `O` is space, `ZXCVB` do the same as `45678` and other letter buttons do nothing. So this might be a hardware issue with my laptop. Still looks very strange though.

**Comment by sfan5** [comment]
Keyboard layout?

**Comment by SmallJoker** [comment]
I assume you're using a cryllic layout. Irrlicht has several problems with non-US layouts, which cannot be fixed in Minetest.

**Comment by SmallJoker** [comment]
Irrlicht issue. #302
