### ISSUE TITLE
Minetest forums not available on multiple devices

### ISSUE THREAD

**Issue by LandonAConway** [minetest/minetest#8508]
##### Issue type

 - Bug report
 - Documentation issue

Is it just me or is the minetest forums down. I understand that this “issue” area on github is for the actual game but there seems to be NO PLACE or ANY PERSON that is acknowledging that this is happeneing. I have tried accessing the website on 3 different devices and two different routers with different privileges and internet connections.

ARE THERE ANY PEOPLE WHO KNOW THIS IS GOING ON.

-thank you

**Comment by rubenwardy** [comment]
The VPS provider had a technical error which corrupted the hard drives (which were in RAID), the server is being rebuilt from backups. The wiki and forums will be  back when this is complete.
