### ISSUE TITLE
The night does not come: ((

### ISSUE THREAD

**Issue by Ramir1** [minetest/minetest#8512]
##### Issue type
 - Bug report

 
##### Minetest version
```
5.0.1
```

##### OS / Hardware
Operating system: Ubuntu 16.04

Hello!
The night does not come: ((

**Comment by DS-Minetest** [comment]
Please post the content of your `minetest.conf`.

**Comment by Ramir1** [comment]
`
aux1_descends = false
creative_mode = false
doubletap_jump = false
enable_damage = true
fast_move = true
fixed_map_seed = 111
free_move = true
keymap_backward = KEY_KEY_S
keymap_chat = KEY_KEY_T
keymap_cinematic = KEY_F8
keymap_cmd = /
keymap_console = KEY_F10
keymap_drop = KEY_KEY_Q
keymap_fastmove = KEY_KEY_F
keymap_forward = KEY_KEY_W
keymap_freemove = KEY_KEY_K
keymap_inventory = KEY_KEY_E
keymap_jump = KEY_SPACE
keymap_left = KEY_KEY_A
keymap_noclip = KEY_KEY_H
keymap_print_debug_stacks = KEY_KEY_P
keymap_rangeselect = KEY_KEY_R
keymap_right = KEY_KEY_D
keymap_sneak = KEY_LSHIFT
keymap_special1 = KEY_KEY_E
mainmenu_last_selected_world = 1
maintab_LAST = local
menu_last_game = mineclone2
mg_name = v6
name = ed
noclip = true
port = 30000
public_serverlist = false
selected_world_path = /home/ramir/.minetest/worlds/dima game
server_announce = false
server_dedicated = false
world_config_selected_mod = 28
main_menu_technical_settings = true
screenH = 710
screenW = 1263
wieldview_node_tiles = false
wieldview_update_time = 2
fullscreen = false
anisotropic_filter = false
bilinear_filter = false
fsaa = 0
leaves_style = fancy
mip_map = false
node_highlighting = box
trilinear_filter = false
screen_w = 1325
screen_h = 744
remote_port = 30000
address = 192.168.1.102
enable_server = true
cinematic = false
continuous_forward = false
keymap_toggle_fog = KEY_F3
keymap_increase_viewing_range_min = KEY_PLUS
keymap_decrease_viewing_range_min = KEY_MINUS
keymap_screenshot = KEY_F12
keymap_mute = KEY_KEY_M
keymap_minimap = KEY_KEY_C
keymap_zoom = KEY_KEY_Z
keymap_hotbar_next = KEY_KEY_N
keymap_camera_mode = KEY_F7
keymap_hotbar_previous = KEY_KEY_B
keymap_autoforward = KEY_KEY_X
keymap_toggle_chat = KEY_F2
keymap_cmd_local = KEY_PERIOD
keymap_increase_volume = 
keymap_toggle_hud = KEY_F1
keymap_decrease_volume = 
autojump = false
sound_volume = 0.08
`

**Comment by DS-Minetest** [comment]
Hm, time speed isn't changed.

Does the sun move?
Does this only happen with mineclone2 or also with minetest_game or minimal?

**Comment by Ramir1** [comment]
In mineclone all ok.
In minetest the sun rises in the east, moves across the sky and stops in the west
Minimal -have not tried
(google translate - my best frend))

**Comment by DS-Minetest** [comment]
>In minetest[_game] the sun rises in the east, moves across the sky and stops in the west

And what happens then? Does it just stay in a position?!

**Comment by Ramir1** [comment]
Yes, just staying in that position

**Comment by paramat** [comment]
Does it happen when using MTGame only and no mods?

**Comment by SmallJoker** [comment]
No response for over a month.
