### ISSUE TITLE
Can put items in lists they can't be put into

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8514]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.1.0-dev-72feab08-dirty
```

##### Summary
I am able to 'place' (Doesn't stay there forever) items in the craftoutput slot
![image](https://user-images.githubusercontent.com/28972859/57186163-f1a45180-6e8e-11e9-898c-cd4408be9703.png)

##### Steps to reproduce
Pick up an itemstack. Rightclick (and hold) over a grey area and drag mouse over craftoutput
![image](https://user-images.githubusercontent.com/28972859/57186211-a3438280-6e8f-11e9-8513-d3a55cad1fef.png)
(Rightclick where X is. Drag along line)

**Comment by DS-Minetest** [comment]
I can reproduce.

But this seems to be only client side and only works if no itemstack movement happens after you put the item in the output (which means that you put your stack back to where it was before).

**Comment by SmallJoker** [comment]
627a96cd9994cd75d490149f6e4a646c6eee3a3c
