### ISSUE TITLE
`on_place` is not called when trying to place a node into another node

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#8517]
##### Issue type
 - Bug report
 
##### Minetest version
```
Minetest 5.1.0-dev-e32a630 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### Summary
If you set `on_place` in a node's node definition, the callback is not called if there's already a node where the new node would be.

##### Steps to reproduce
- Register a **node** with `on_place = function() minetest.chat_send_all("on_place") end,`.
- In minetest place a full node and next to it a slab or something similar.
- Move you point to the full node on the side at which the other node is.
It should look like this:
```
/-----\
|     |←you look at this face
|     |/-----\
\-----/\-----/
```
- Rightclick.
- Look into chat and see that there's no message.
- Try the same with an item that is not a node and get a message.

**Comment by SmallJoker** [comment]
This is prevented by the client; fixing it should be rather simple. The code to predict the node placement checks whether the node "above" is `buildable_to` and skips the placement prediction (see `Game::handlePointingAtNode`) inclusive the interact packet.
For reference:
https://github.com/minetest/minetest/blob/8e3b63bd28579d8f8cb3e7844600504f12b087a5/src/client/game.cpp#L3328-L3339
