### ISSUE TITLE
Allow exceeding 'stack_max' with '/give(me)'

### ISSUE THREAD

**Issue by deezl** [minetest/minetest#8518]
##### Issue type

 
 - Feature request
 
 
 
##### Minetest version

```
5.0.1
```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary

We used to be able to exceed stack_max with /give(me) for a variety of useful reasons. For some reason this ability has been removed. The PR #6159 by SmallJoker that should fix this does not seem to have been implemented, with no real reason why not. The usefulness of this was laid out very well by LazyJ in the conversation for this PR so I won't regurgitate it here. This isn't a major issue of course, but does present some problems for admins on survival servers.

**Comment by VanessaE** [comment]
#6159 (link for convenience)

**Comment by paramat** [comment]
The PR thread explains why it was closed, the author suggests reverting a previous commit https://github.com/minetest/minetest/commit/e6a9e6066afc369f01c046de8e3a90a4b042286c instead, see https://github.com/minetest/minetest/pull/6159#issuecomment-322027220

**Comment by ClobberXD** [comment]
See #8519 - reverts e6a9e60.

**Comment by paramat** [comment]
@SmallJoker

**Comment by SmallJoker** [comment]
So I guess #5773 is not wanted, since it requests the exact opposite.
