### ISSUE TITLE
Kick player when another user who knows the password joins

### ISSUE THREAD

**Issue by niwla23** [minetest/minetest#8521]
##### Issue type

 - Feature request

 
##### Minetest version

```

```

##### OS / Hardware

Operating system:
CPU:

GPU model:
OpenGL version:

##### Summary
1. Reason: When players time out they dont have to wait until the server checks you timed out.
2. reason: Eg: My friend is at my home. we are playing mt on a server with too pcs. My friend goes home, and can login because i forgot to shutdown the pc.

##### Steps to reproduce
Just time out 🤣

**Comment by Linuxdirk** [comment]
So a hacker can kick legitimately logged in players just by guessing or knowing their password?

**Comment by Yukitty** [comment]
> So a hacker can kick legitimately logged in players just by guessing or knowing their password?

If that's the case, you've already lost, haven't you? ^^; No one stays logged in forever for fear of hackers who know their password getting in while they're away.

**Comment by ClobberXD** [comment]
Is this a joke? How would the server even know if someone knows the password of the user? And you might as well ban them instead of kicking them every time they join... :smirk:

**Comment by Niwla23** [comment]
Reason: When players time out they dont have to wait until the server checks you timed out.
    reason: Eg: My friend is at my home. we are playing mt on a server with too pcs. My friend goes home, and can login because i forgot to shutdown the pc.
@ClobberXD

**Comment by Niwla23** [comment]
maybe the title is bad. I just mean if the player is online, and a another client, which has the right password joins, he actually get an error. My idea is, that the new player joins the game and the other one is kicked.

**Comment by ClobberXD** [comment]
My question is: how would the server know who the legit player is, and who the rogue player is?

This _could_ be possible if MT uses GPG keys or smth. that has two parts one private key and one public key. Our current auth system, SRP, uses only one component - the password - and this idea isn't feasible at the moment.

**Comment by paramat** [comment]
:-1: It seems better security that the first connection of the player is given priority. Essentially what Linuxdirk wrote.

**Comment by rubenwardy** [comment]
:+1: This is good for when users time out.

I don't see the security concern as valid. Many services, including Github, allow you to log out other logins by using your password.

**Comment by Niwla23** [comment]
#8520 Will make more sense with that

**Comment by paramat** [comment]
Hmm removed my -1 as i'm not so sure now.

**Comment by SmallJoker** [comment]
I support this request. It's very handy in IRC (ghosting) to not wait for the timeout. Closing the existent connection to the user with the same name is fine; I don't see any issue there.

**Comment by ClobberXD** [comment]
So the server won't really care about the legitimacy of the clients, and kicks the first one when the second one attempts to connect? That... doesn't sound reassuring. What if the second client is trying to bruteforce the password? If they succeed, they'll get the original client kicked, and change the password on their device. While this fault could be partly attributed to the person for having a weak password, this feature would make it even easier.

**Comment by LoneWolfHT** [comment]
I've had a few times where I time out and can't get back online for a while because the server still sees me as being online

**Comment by Linuxdirk** [comment]
@ClobberXD As seen from the votes no-one really cares.

**Comment by LoneWolfHT** [comment]
> What if the second client is trying to bruteforce the password? If they succeed, they'll get the original client kicked, and change the password on their device. While this fault could be partly attributed to the person for having a weak password, this feature would make it even easier.

You can currently tell if you managed to find the password while bruteforcing a connected client's password anyway. All they would have to do then is wait for them to log off.

**Comment by rubenwardy** [comment]
> So the server won't really care about the legitimacy of the clients, and kicks the first one when the second one attempts to connect? That... doesn't sound reassuring. What if the second client is trying to bruteforce the password? If they succeed, they'll get the original client kicked, and change the password on their device. While this fault could be partly attributed to the person for having a weak password, this feature would make it even easier.

No players are online forever, they could just do this when the player is logged off

> @ClobberXD As seen from the votes no-one really cares.

I care about security, but I don't see the security issue here

**Comment by ClobberXD** [comment]
> No players are online forever, they could just do this when the player is logged off

Getting hacked while your online is totally different thing.

> I don't see the security concern as valid. Many services, including Github, allow you to log out other logins by using your password.

Such services are used by relatively mature people who have strong passwords and don't share it with anyone. While I wouldn't say mutually exclusive, our userbase is far from similar. :)

However I'm probably exaggerating this. If (and only if) this isn't much of a security concern, I'm all for this feature.

**Comment by Linuxdirk** [comment]
If this security hole will ever become a functionality I hope there is at least a configuration parameter for security-aware admins so they can turn this potentially malicious feature off.

> but I don't see the security issue here

Of course you don’t.

**Comment by rubenwardy** [comment]
Perhaps rather than throw around thinly veiled insults, you could make an actual argument as to why this is not the same as session management on popular services, and why malicious actors wouldn't wait for the player to log off before changing the password.

There is one case where this concern is valid - when the password is trivial (eg: empty) and the user has done something to provoke the malicious user, or they simply decides to troll them by logging them out. There are preventions against this, such as by not allowing this when the password is empty or by requiring a minimum last contact time (to allow disconnection of time outs earlier)

**Comment by Linuxdirk** [comment]
> you could make an actual argument as to why this is not the same as session management on popular services

It is the same. This does not make it better but equally bad.

So instead of force logging off users when someone else logs in with same username and password just don’t do this but instead (for the intended use) have a faster timeout timer.

What times are there actually? When fiddling around on my local machine starting several clients and connect them and I forcefully kill one of the client processes it takes less than a minute for the server to note that the client is gone.

**Comment by sorcerykid** [comment]
The current title is misleading. Perhaps it should be changed to "Allow users to rejoin server immediately prior to connection timeout".

> I hope there is at least a configuration parameter for security-aware admins so they can turn this potentially malicious feature off.

I'm a security conscious admin. And if this feature becomes a reality, it would be very easy to disable it via a mod. In Auth Redux for example, it's just a two-line ruleset:

```
try "Sorry, another client is already connected with the username $name."
when $name in $player_list fail
```

I don't understand the opposition to this feature on the grounds that it poses some type of security risk.

**Comment by paramat** [comment]
I am still uncomfortable with this, i do not care what others do in this situation, that is not an argument, they may be wrong.
The benefit is small: Not having to wait for a timeout, how long is that, a few minutes? I am guessing not long at all.
The solution significantly reduces security.
So overall this does not seem justified.
:-1: for the concept (not necessarily for the PR).

**Comment by rubenwardy** [comment]
The security risks are massively overstated, if present at all

**Comment by rubenwardy** [comment]
There is one case where this actually results in a loss of security, and that's when passwords are accidentally exposed to chat causing the player to have a limited amount of time to change it.

How about only doing this if the IP address matches?

**Comment by ClobberXD** [comment]
That's a real risk, I agree. The chances are very remote, but it's very much possible that a malicious player is online at the time the player accidentally reveals their password, who immediately logs out and hijacks their account.

**Comment by nerzhul** [comment]
on any online game i play if you reconnect you kick the old session, it's a common used way, i'm for it too.
