### ISSUE TITLE
formspec: mouse cursor should look different when hovering over fields

### ISSUE THREAD

**Issue by DS-Minetest** [minetest/minetest#8523]
##### Issue type
 - Feature request

##### Summary
The mouse cursor should look different when you hover it over a field or textarea element.

Normally the mouse cursor looks like an arrow. While this is good for pointing at buttons, it is bad if you want to click between two chars. Therefor I want that the cursor looks different when you hover it above texts where you can mark.
It should look like an I with a base and a ceiling, like this:
```
-- --
  |
  |
  |
  |
-- --
```

**Comment by Linuxdirk** [comment]
That’s the job of the operating system. I wonder if it is possible with Irrlicht to set the correct hints so the OS can show the proper cursor.

**Comment by rubenwardy** [comment]
This is an Irrlicht issue, but like most Irrlicht issues it is possible for us to fix it
