### ISSUE TITLE
Disable server logging http requests

### ISSUE THREAD

**Issue by JosephTheTank13** [minetest/minetest#8525]
- Feature request
"5.0.1"
When running a mapserver the server console window is filled with the server logging http requests. This is a big problem because I need to use that window and the debug file to find things, such as people dying and whatnot. Screenshot:
![Capture](https://user-images.githubusercontent.com/28242145/57576741-6817f500-7435-11e9-9876-a3dbaa4ee72e.PNG)
This also fills the debug.txt file up and makes it huge. I just need to be able to disable this logging to make my console window useful again.

**Comment by ClobberXD** [comment]
This should ideally be moved to `infostream`.

**Comment by paramat** [comment]
:+1:
