### ISSUE TITLE
Light Bleeds Through Node Faces

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#8531]
##### Issue type

 - Bug report
 
##### Minetest version

```
5.0.1
```

##### OS / Hardware

Operating system: Majaro
CPU: Intel i7 5930k

GPU model: Nvidia 980ti
OpenGL version: 4.6.0

##### Summary

Lighting seems to "bleed" or pass through solid nodes. This results in nodes being lit behind a blocked light source, although some shadow is cast behind it is not enough considering the amount of node which is blocked. This is not the same as the old corner light bug (as that has been fixed) and is not a request for per-pixel lighting.

##### Steps to reproduce
Notice small amount of shadow on left side.
![screenshot_20190513_204126](https://user-images.githubusercontent.com/19180682/57663350-a9d5a680-75c1-11e9-8930-a57de7155f06.png)

Uncovered:
![screenshot_20190513_204408](https://user-images.githubusercontent.com/19180682/57663381-bfe36700-75c1-11e9-87b8-b573cdfdfc8a.png)

**Comment by DS-Minetest** [comment]
Light is a wave and waves bend around corners (see https://en.wikipedia.org/wiki/Diffraction).

**Comment by appgurueu** [comment]
Diffraction is by far not strong enough to make a 180° turn around a solid 1m stone node.

**Comment by ClobberXD** [comment]
It's cobblestone - not stone. It's not perfectly solid, and has gaps throughout that allow light to pass through. :3

**Comment by paramat** [comment]
This is not a bug, simply the result of how light spreads from node to all neighbour nodes, so spreads around corners. It can't be changed without a completely new lighting system.
The light isn't bleeding through solid nodes, from the sourse it's travelling rightwards, then through the air around corners.
The way light goes around corners is actually quite nice as it somewhat simulates re-radiated light. Strict line-of-sight lighting would look very harsh and fairly unrealistic.

**Comment by benrob0329** [comment]
>This is not a bug

The lighting behavior is very unrealistic and unexpected (dare I say unintuitive and frustrating if you wanted to direct the light in any direction than _literally everywhere_). Wrong behavior may not be a "bug" in the sense that the code does what it's supposed to, but not in a way that is aligned with the expected result.

>simply the result of how light spreads from a node to all neighbour nodes, so spreads around corners

So the light-spreading code is overaggressive and makes light rays take 180° turns around a wall? Sounds like a bug to me.

>The light isn't bleeding through solid nodes

I beg to differ.
![screenshot_20190514_155428](https://user-images.githubusercontent.com/19180682/57727962-bb21c000-7660-11e9-9aba-b0585bd999d1.png)

>Strict line-of-sight lighting would look very harsh and unrealistic

Yes it would be, because light naturally bounces off and diffuses on the surrounding surfaces, but when it _literally defies the laws of physics and bounces off of thin air to light blocks on the other side of a meter thick wall_ I think that it might need to be looked at.
