### ISSUE TITLE
Travis-CI builds are failing due to outdated macOS and Xcode

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8533]
##### Issue type

 - Travis-CI build issue

##### Summary

Travis-CI builds are failing for the past couple of months due to our current versions of macOS and Xcode being outdated. This affects a lot of PRs and causes quite some confusion when the builds fail.

```
...

Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

...

Error: Your Xcode (8.0) is outdated.
Please update to Xcode 8.2.1 (or delete it).
Xcode can be updated from the App Store.

...

Error: A newer Command Line Tools release is available.
Update them from Software Update in the App Store.

...

The command "./util/travis/before_install.sh" failed and exited with 1 during .
Your build has been stopped.
```

##### Steps to reproduce

Make a PR that touches some C++ code.

**Comment by ClobberXD** [comment]
Whoops

**Comment by tacotexmex** [comment]
Sorry if posting in the wrong place but where are these builds uploaded, @clobberxd?

**Comment by Calinou** [comment]
I don't think they're uploaded anywhere. Unlike some other CI platforms, Travis CI doesn't feature an "artifacts" system which can be used to store builds, so you have to do it manually using GitHub Releases, SFTP or similar.

**Comment by tacotexmex** [comment]
These are automated though, no? https://github.com/krondor-game/minetest/
