### ISSUE TITLE
Light sources - add another param to store ray direction

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#8534]
##### Issue type
 - Feature request
 
##### Minetest version
5.0.1

##### Summary
The idea is to store the light direction & probably also the angle (entire wavefront) as a param for every node. As far as I understood how it works right now, MT is currently only storing light level. This would probably solve issues like this : https://github.com/minetest/minetest/issues/8531and also enable new opportunities for lighting, such as specular lighting :smiley:

**Comment by benrob0329** [comment]
This wouldn't fix #8531 as that is a bug where the lighting calculation code doesn't seem to check for blocking nodes when calculating the lighting. This would be a separate thing and would likely dramatically change how the lighting code works.

**Comment by ClobberXD** [comment]
Light direction isn't something that's supposed to be stored per-node, as far as I know. Each node emits light, and also propagates light according to the light level of the surroundings.

**Comment by benrob0329** [comment]
You're missing the point, its not the direction the shadow is being cast that needs to be added per-node, its the lighting code which needs to go "oh there is a non light-propagating node between this one and the light source, so it won't be affected by it" when calculating the light level.

**Comment by appgurueu** [comment]
I will put my KolourPaint skills to the rescue.

**Comment by appgurueu** [comment]
![awkward](https://user-images.githubusercontent.com/34514239/57717059-a6eabc80-767a-11e9-8c69-6a50c54842af.png)

**Comment by paramat** [comment]
Another param requires a map format change, all worlds would break and need conversaion.
Such a lighting system would be far too intensive to be practical, lighting is already very intensive in it's current simple form.
#8531 doesn't need fixing as it's not a problem, it nicely simulates reflected and re-radiated ambient light.
:-1:
