### ISSUE TITLE
ContentDB development rules / decision-making

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8544]
*** Please do not ask this to be moved to the contentdb repo, this is here so that it is seen ***

What are the current decision-making rules for the ContentDB? And what should they be?

The CDB was initially developed by rubenwardy as a project related to his degree, so of course until recently development had to be a certain way. However, now it is released into stable MT, and when connected, it is effectively a part of the MT engine.

**Comment by thomasrudin** [comment]
Isn't that a problem with all repositories in the https://github.com/minetest organization?
The minetestmapper and master-server don't have an approval on PR's as far as i see :confused:

**Comment by MoNTE48** [comment]
Another problem with Minetest is that many changes do not have a second approval for a very long time. We now have 18 commits with the "One approval" icon. It seems that the @paramat proposal is reasonable on the one hand, but it will even slower the development of Minetest on the other hand.

**Comment by paramat** [comment]
I thought further on this and currently think the best approach would be something like:
rubenwardy can work on CDB freely, but any decisions concerning functionality should be discussed and agreed with at least one other core dev. Oddly enough this is what is already happening =) So i will close this issue.
With dev as slow as it is i agree that slowing it further is not good.
The CDB is also not critical to the functionality of the MT engine, content can always be added the old way.

**Comment by lhofhansl** [comment]
@paramat , I agree with everything but this:

> The CDB is also not critical to the functionality of the MT engine, content can always be added the old way.

Minetest itself is kindly "useless" to anybody but developers. It might not be critical to the engine, but CDB is what makes it useful for the average user. It's a super important feature!

Stupid question: Is the CDB hosting code open source? That way if people want to host their own they could, or if @rubenwardy gets tired of doing this we have a quick way to a new database.

**Comment by Calinou** [comment]
> Stupid question: Is the CDB hosting code open source? That way if people want to host their own they could, or if @rubenwardy gets tired of doing this we have a quick way to a new database.

[It is](https://github.com/minetest/contentdb) :smiley:

**Comment by paramat** [comment]
lhofhansl, i agree it's important from a user convenience viewpoint, especially for children.

I disagree MT is not 'useful' without CDB, it's fairly easy to download a mod the old way, the average user has been doing this for years, otherwise MT wouldn't be as popular as it is.
Children tend to have parents around to help if they need it, and parents would often want to check what mods are being downloaded anyway. Anyone older than that is able to download the old way. So it's convenient but not essential.
