### ISSUE TITLE
In fast mode, holding the sneak/move down (Shift) and special (E) keys at the same time while in the water or descending the ladder triggers fall damage

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#8545]
##### Issue type

 - Bug report
##### Minetest version

```
Minetest 5.1.0-dev-debug-56869412 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
##### OS / Hardware

Operating system: Ubuntu Linux 18.04.2 LTS
CPU: Pentium(R) Dual-Core CPU E6300 @ 2.80GHz
##### Summary

Fall damage can be triggered from relatively small distances using the fast movement key while swimming down in water or descending the ladder, using the sneak/move down key (Shift) and special (E) at the same time. Death can be triggered by repeating the action.
![screenshot_20190517_134428](https://user-images.githubusercontent.com/6626242/57924531-ffee6680-78ad-11e9-97d8-67de526abef3.png)
![screenshot_20190517_142142](https://user-images.githubusercontent.com/6626242/57924916-22cd4a80-78af-11e9-830f-182a3aaed818.png)

##### Steps to reproduce

1. Open a new or existing minetest singleplayer world (minimal/minetest_game/etc.).
2. Give yourself fast privilege and turn fast mode on.
3. Get to some body of water or on the top of the ladder.
4. Hold fast movement key and sneak key at the same time, get damaged at the bottom, repeating this might trigger a death message.

**Comment by Calinou** [comment]
I don't think this is technically a bug, but I agree it can be frustrating. It'd make sense to disable fall damage while in a liquid or in a climbable node (such as  a ladder).

**Comment by SmallJoker** [comment]
This is expected behaviour since all kinds of -Y collisions cause damage. You can also boost yourself out of the water and damage yourself with high `movement_speed_fast` values, which is no different to jumping off a cliff.

**Comment by JosephTheTank13** [comment]
I think that all fall damage should be cancelled if you land in water. This isn’t realistic to life, but Minecraft does this and it’s a really useful feature for traveling. Also, if you have a water bucket in your inventory you could jump from really tall heights and survive by placing the water just before impact.

**Comment by SmallJoker** [comment]
@JosephTheTank13 Just for your information: The physically correct way would involve being hurt very badly or killed after a 100m fall due to the surface tension.

**Comment by paramat** [comment]
I agree this is not a bug, as the player is hitting ground at a high vertical speed, which causes damage.
Labelled issue as a request, in case anyone wants to suggest any changes.
I disagree with disabling fall damage when in liquids or on a ladder.
Players will soon learn to not fast move downwards.

**Comment by costigo** [comment]
Maybe running face-first into a wall in fast mode should also cause damage. :) Then at least it won't be surprising when it also happens in water or on a ladder. Otherwise, maybe non-freefall vertical descent can be capped at a level that won't cause damage.

**Comment by paramat** [comment]
I'd rather not add horizontal speed damage, it's realistic but MT players are used to it not occuring, it also happens very easily in fast mode.

**Comment by jastevenson303** [comment]
It would happen `very easily' in fast mode because of the very fast
fast_mode default velocity.  But there's no inertia (is there?) so it's not
like you couldn't avoid it.  It would be off is enable_damage were off, and
wouldn't matter if you added a setting alongside it.

**Comment by ClobberXD** [comment]
Maybe increase fall damage threshold in fast mode?

Because it's actually quite easy to attain the -Y velocity required for fall damage when travelling fast - I've lost more than 10 HP while "falling" from a height of 5m in fast mode (although I'd have covered around 50m horizontally).

**Comment by paramat** [comment]
> Because it's actually quite easy to attain the -Y velocity required for fall damage when travelling fast

No, horizontal components of velocity have no effect on the Y component of velocity which determines fall damage. They are orthogonal so independent (physics).
