### ISSUE TITLE
Add advanced image manipulation

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#8546]
##### Issue type
 - Feature request

##### Summary
It is no secret that most modders have the unfulfilled desire to use complex texture modifiers for things such as custom skins. But adding more and more proprietary texture modifiers with inconsistent syntax is not going to solve the issue.

##### Rough Feature Spec

1. **`Image` class/userdata**
   An userdata object representing a RGBA image.  
   *Constructors :* 
   - `Image(w: int,h: int)`, new RGBA image of width w and height h is created, all pixels set to `(0,0,0,0)`
   - `Image(filename)`, loads image from file  

   *Instance methods :*
   - all texture modifiers, for example : 
   - `multiply(r: int, g: int, b: int)` - multiplies all pixels with given color, r, g, b must be positive, if resulting    values are higher than 255 they are clamped. Note that r,g,b can be higher than 255.
   - `filter(func)` - filters image using given Lua function. If returned color is invalid, the base color is  taken (no change is made to the pixel)
   - `set_at(x, y, {r, g, b, a})` - set pixel x, y to rgba
   - `get_at(x,y)` - get pixel x, y rgba color as list : {r, g, b, a}  

2. **`[lua:` texture modifier**
  A new texture modifier for applying a Lua function to the image. **Receives an image and returnes     processed version**. Escaping rules still apply.
  Syntax : `[lua:function() return Image:new(16, 16) end`

3. **Images instead of texture modifier strings**
  Images could be passed as "texture" value in node, item, particle, and entity definitions. Example : 
  ```lua
  minetest.register_node("mod:stone", {
          description = "Stone",
          tiles = {Image:new(16,16)},
  })
  ```

**Comment by SmallJoker** [comment]
Similar to #6821

**Comment by appgurueu** [comment]
Somehow. Adding the requested feature of a texture modifier which creates an image is a good idea.
