### ISSUE TITLE
Formspecs : Add "canvas" element

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#8549]
##### Issue type
 - Feature request

##### Summary
Proposal : Add a new formspec element called "canvas" which allows Lua to actually **draw** to a canvas surface & **receive *all* events** within it, which include key presses, key releases, mouse clicks, mouse moves, mouse wheel scrolls and mouse releases. `on_receive_fields` would then return the triggered events and a reference to a `Canvas` object, which would have to be more clearly specified. This could allow responsive GUIs made by modders without having to introduce a complex GUI system like HTML/CSS.

**Comment by rubenwardy** [comment]
How is this actually supposed to work when the Lua is server side?

**Comment by benrob0329** [comment]
Send pixel information over inside the formspec element?

**Comment by weqqr** [comment]
Good idea, but it doesn't make much sense without client-side scripting.

> responsive GUIs

How responsive would they be for someone playing with 200ms RTT and high packet loss?

**Comment by appgurueu** [comment]
> How responsive would they be for someone playing with 200ms RTT and high packet loss?
You could actually send the canvas content as minified SVG. This would reduce network problems.
Also it's hardly possible to play MT with "200ms RTT and high packet loss"...

> Good idea, but it doesn't make much sense without client-side scripting.
Agreed. There should be a client-side handler added for keeping the GUI updated.

**Comment by rubenwardy** [comment]
The default server step results in a 200ms RTT. High packet loss can be common, and the networking code is designed to cope with it
