### ISSUE TITLE
Make a setting for turning off alpha on the hud

### ISSUE THREAD

**Issue by DanielTheGreatinc** [minetest/minetest#8553]
- Feature request
 
##### Minetest version: All versions

```
Option needed to disable hud alpha and replace with solid color of choice, in order to increase framerate on slow computers.
```

##### OS / Hardware: Debian on a Raspberry Pi 3 b+

Operating system: Debian
CPU: Armf

##### Summary

It would increase the fps significantly to disable the alpha for the hud, so adding an option to replace it with a solid color would be useful for slow computers.
##### Steps to reproduce

If you turn off the HUD while playing minetest then the fps becomes higher. If you remove the alpha for the hotbar/item images, then you get the same result as turning it off. Therefore, I concluded that the alpha was causing the lower fps.

**Comment by GaryLeutheuser** [comment]
I'm interested in implementing this. Working to confirm the issue / fix on my hardware.

**Comment by GaryLeutheuser** [comment]
Not sure that I'll be able to reproduce. Changing my max FPS beyond 60 doesn't seem to allow the in-game debug display to go beyond that for whatever reason.

I'll just implement it and we'll see if it has the desired effect on your end @SmallJoker.

**Comment by SmallJoker** [comment]
@GaryLeutheuser You should be able to remove the 60 FPS by disabling `vsync` and increasing the `fps_max` value - either by editing `minetest.conf` directly or using the Settings menu.
If that still does not work try to run Minetest using different env variables:
`vblank_mode=0 __GL_SYNC_TO_VBLANK=0 minetest`

Note that I only added the labels, and this request doesn't seem to be too popular. Font drawing speed is more of a problem on weak devices.

**Comment by rubenwardy** [comment]
I am doubtful as to whether this will actually result in a performance improvement. The stuff behind the HUD elements will still be drawn, with the HUD over drawing

**Comment by GaryLeutheuser** [comment]
@SmallJoker Thanks - I had `vsync` and `fps_max` set, but will have to give a try to the environment variables if I continue looking into this.

@rubenwardy Per my observations from running in a VM with poorer performance than my host, it's certainly unclear to me whether there's any difference.

Does anyone have any ideas for how to comprehensively test this? I.e. some sort of graphical profiling? Maybe this is simply more trouble than it's worth if it requires that kind of scrutiny to find any value.

**Comment by paramat** [comment]
> If you turn off the HUD while playing minetest then the fps becomes higher. If you remove the alpha for the hotbar/item images, then you get the same result as turning it off. Therefore, I concluded that the alpha was causing the lower fps.

This logic seems weak. Also see rubenwardy's comment.
:-1:

**Comment by DanielTheGreatinc** [comment]
The results are in! As rubenwardy pointed out, it's not the alpha that's the problem. The only way I can get anything approaching playable FPS is to hide the HUD. Although I would like to keep seeing my arm...
Stock world with alpha:
![Alpha Activated](https://user-images.githubusercontent.com/36929174/81234360-98518f80-8fc6-11ea-8a42-360f50db80f8.png)
Stock world no alpha:
![Alpha Deactivated](https://user-images.githubusercontent.com/36929174/81234372-9d164380-8fc6-11ea-931f-3fbf6aecfd74.png)

Modded world without alpha:
![No Alpha](https://user-images.githubusercontent.com/36929174/81234381-a1daf780-8fc6-11ea-8289-af0f72191c23.png)

Modded world with alpha
 from 20 to 40.
![Alpha](https://user-images.githubusercontent.com/36929174/81234312-87088300-8fc6-11ea-982a-fb3e736bb62d.png)
