### ISSUE TITLE
Clearobjects avoid add entity in unloaded mapblocks

### ISSUE THREAD

**Issue by BrunoMine** [minetest/minetest#8555]
##### Issue type
Bug report
 
##### Minetest version
```
5.1.0-dev-a2848v9
```

##### OS / Hardware

Operating system: Ubuntu 18.04.2 LTS
CPU: Intel® Core™ i3-3110M CPU @ 2.40GHz × 4 

##### Summary
The `minetest.clear_objects` method prevents new entities with `minetest.add_entity` in unloaded mapblocks. Apparently the objects is activated and deactivated, but is not saved. I noticed that this also removes entities that move towards an inactive mapblock.

##### Steps to reproduce
1. Enable fly mode and take all privs in a new Minetest Game world
2.  _Checking for normal behavior_
2.1. Command: `/teleport 1000 100 1000` (emerge mapblock)
2.2. Command: `/teleport 1000 100 0` (unload mapblock)
2.3. Command: `/spawnentity boats:boat 1000 100 1000` (spawn boat at unloaded mapblock)
2.4. Command: `/teleport 1000 100 1000` (go to check entity that spawn normally)
2.5. Take the boat from air with leftclick
3.  _Reproduce Bug_
3.1. Command: `/teleport 1000 100 1000` (emerge mapblock)
3.2. Command: `/teleport 1000 100 0` (unload mapblock)
3.3. Command: `/clearobjects` (clear objects)
3.4. Command: `/spawnentity boats:boat 1000 100 1000` (spawn boat at unloaded mapblock)
3.5. Command: `/teleport 1000 100 1000` (go to check bug: entity has not been saved)

**Comment by SmallJoker** [comment]
This seems reasonable because the mapblock yet did not have the chance to clear its entities. Since you spawn another one before the mapblock is loaded, it will be deleted on load again.
