### ISSUE TITLE
Loop World At Map Edge

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#8560]
##### Issue type

 - Feature request

 
##### Minetest version

```
5.0.1
```

##### Summary

As of right now when you reach the end of the map, you simply hit a load of IGNORE blocks. But I think it would be much more interesting, and far more useful if the map looped around and you ended up on the other side of the world. The result would be a much more original and fascinating take on it, with some interesting consequences as a result (e.g. falling through the world makes you plummet from the top, being able to build across the map edge, and having a more planet like world in general).

Games can of course add any number of barrier blocks to keep player from e.g. falling out of the world if they so choose, so it shouldn't have any detrimental effects on gameplay.

**Comment by LoneWolfHT** [comment]
I've been on servers that have mods that do this. It doesn't really work because you're suddenly teleported to the other side. It would be really weird for players that get teleported who have no knowledge of this feature

**Comment by benrob0329** [comment]
It'd have to _look_ like the world kept going (display the mapblock from the other side), and the teleport would have to be seamless. "Teleport" might even be he wrong word for it, more like "walking through to the other side".

**Comment by SmallJoker** [comment]
So do you want spheretest?
https://www.youtube.com/watch?v=ztAg643gJBA
https://github.com/Jeija/spheretest/

**Comment by benrob0329** [comment]
Spheretest warps the geometry of the world, my idea would be to keep it perfectly level and just loop the mapblocks.

**Comment by paramat** [comment]
I don't see any benefit and personally find it less interesting than having an edge to visit and the concept of a cubic world.
Implementation would be very complex and difficult, and it would be practically impossible for terrain to be continuous over the join in all 3 axes.
I thnk this is best left to lua mapgen mods.
:-1:

**Comment by rubenwardy** [comment]
is this possible using flat map generation?

**Comment by DS-Minetest** [comment]
Such a change would probably take much effort to do and to maintain and would introduce new bugs. Also problems with mapgen would make this feature very unattractive for most mapgens.
Are the benefits worth the effort?

>This could be useful for a project that I and a few Minetesters have been working on.

Which one?

**Comment by rubenwardy** [comment]
> Which one?

I can't give any details at this point in time. This feature would be nice to have but not required, anyway.

**Comment by SmallJoker** [comment]
Jejia proved that it is possible to loop the mapblocks at the edge, but there are various issues which come from this behaviour:
 * Line of sight suddenly wraps: mapblocks from another location have to be loaded to another position
 * Several other linear calculations mess up: You travel from -1000 to +1000 in 0.1s, what's the player speed? Finding the shortest path (like in a circle: old angle vs new) involves more calculations
 * Requires some magic mod/feature to make the world edge smooth (mod already exists, though)
 * Extended Lua API functionality so that entities can cross the border

Do not understand me wrong, it's a great feature, but I wonder how much of a performance impact we would get from the kinda non-linear coordinate system.

**Comment by style-nine** [comment]
Something you could do would be to make a special mapgen that creates a kind of transitional zone a certain number of blocks wide (say 256 or so). Then, when a player goes from one side of that zone to the other, they teleport to the other transitional zone. You'd just have to keep the zones in sync to preserve the illusion of being in the same place, but I think you could implement this sort of thing in Lua.
