### ISSUE TITLE
Hotbar size, position and registration

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#8565]
##### Issue type

 - Feature request

Allow for the hotbar to be changed in size and location 

And ability to register hotbars that are scrollable to, that display different player inventories

For example having your default hotbar then a hotbar containing the 3d_armor inventory or the bags inventory ect
```
player:hud_add({
    hud_elem_type = "hotbar",
    position = {x=0,y=1},
    number = 2,--number of slots to be shown
    alignment = {x=0,y=1},
    offset = {x=0, y=-32},
    inv="armor",--Which player inventory to be shown
    priority = 2,--order of inventory scrolling (default inv = 1 after going past the default inv it goes to inventory marked with the next priority)
})
```

**Comment by Linuxdirk** [comment]
Changing size is already possible.

https://github.com/minetest/minetest/blob/a1459a9eac4eeb35a6c578a8b8f96393f87ed53d/doc/lua_api.txt#L5334-L5335

**Comment by Extex101** [comment]
No not max items the visual size of it to make it look bigger on the screen

**Comment by paramat** [comment]
Related to #1897

**Comment by MoNTE48** [comment]
@Extex101 
hud_scalling

**Comment by Extex101** [comment]
Within a mod
Besides that makes everything bigger

**Comment by DS-Minetest** [comment]
Maybe [the inventory hud element](https://github.com/minetest/minetest/blob/a1459a9eac4eeb35a6c578a8b8f96393f87ed53d/doc/lua_api.txt#L1300-L1306) could be changed in a way that if a slot is the selected one, the hotbar selection frame is drawn above this slot.

**Comment by Extex101** [comment]
Maybe having custom hotbars that display different inventories too

Added to issue

**Comment by Linuxdirk** [comment]
> Maybe having custom hotbars that display different inventories too

That would actually be awesome. I like the registration idea and implied functionality of the updated issue.

**Comment by ClobberXD** [comment]
Related: #8297
