### ISSUE TITLE
Creative Inventory: Provide a way to disable automatic keyboard capture by the search input

### ISSUE THREAD

**Issue by xoich** [minetest/minetest#8566]
##### Issue type
 - Feature request

**Comment by DS-Minetest** [comment]
Wrong repository, creative inventory is done in [minetest_game](https://github.com/minetest/minetest_game).

**Comment by forht** [comment]
I see, but here they are saying it is an engine issue: https://github.com/minetest/minetest_game/issues/760

**Comment by DS-Minetest** [comment]
This is the correlating engine issue: #8029 
If it was easily possible to set the selected element like requested in that issue, this issue could be solved easily.
However, some of the information given in that issue might be wrong as [the field in the creative inventory](https://github.com/minetest/minetest_game/blob/76a08a7058429d51bd12e9bf5b1f90c569aff68f/mods/creative/inventory.lua#L126) is the last element that can be selected, not the first.

Anyway, many users like that they can type stuff into the field without having to select it, ergo a change which makes the field not selected by default will encounter much resistance.
It might be nice to have a setting to never select an element at first that captures the inventory button.

**Comment by JosephTheTank13** [comment]
I use unified inventory and if I press (e) to open the inv, then press (e) again to close it, it does not close. Instead, it types E into the search field.
