### ISSUE TITLE
Player texture still white after respawn

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest#8569]
While I killed my second player, their texture flashes and fades into white, yet after they respawn their texture is still white. Is this a bug?:
![test](https://user-images.githubusercontent.com/49789044/58558964-fb18a380-8219-11e9-84f0-bc71d6e85a8d.png)

**Comment by Thomas--S** [comment]
What commit are you using?

This should be fixed by a1459a9eac4eeb35a6c578a8b8f96393f87ed53d.

**Comment by An0n3m0us** [comment]
I'm using 2019-05-26. I'll try the latest.

**Comment by An0n3m0us** [comment]
It works. I'll close this issue.
