### ISSUE TITLE
Rename override.txt to override.conf

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#8571]
##### Issue type
 - Bug report

By convention of recent file renamings, `override.txt` should become `override.conf` (or somehow incorporated in `texture_pack.conf`)

**Comment by SmallJoker** [comment]
I don't think that integrating it into `texture_pack.txt` is a good choice. `override.txt` has its own format which is cannot be integrated well into Settings, unless you'd want to use a very long multiline string setting for that.

**Comment by tacotexmex** [comment]
`override.conf` then.

**Comment by rubenwardy** [comment]
I don't think it's in .conf format

**Comment by tacotexmex** [comment]
Very valid point, rubenwardy 🤭
