### ISSUE TITLE
Debian Repository is Out of Date

### ISSUE THREAD

**Issue by ghbjklhv** [minetest/minetest#8578]
**Issue**: Debian Repository is Out of Date
**Possible Fixes**: 

- Update Debian Repository

- Create .deb file for easy installation. 

- Create AppImage

**Comment by Calinou** [comment]
We don't have control over distribution repositories. According to [packages.debian.org](https://packages.debian.org/search?keywords=minetest), 5.0.1 has already landed in *experimental* but it hasn't made its way into *sid* (Debian unstable) yet.

**Comment by An0n3m0us** [comment]
@ghbjklhv 
AppImages are already supported: https://github.com/An0n3m0us/Minetest-AppImages/releases
