### ISSUE TITLE
Map saving

### ISSUE THREAD

**Issue by piecubed** [minetest/minetest#8581]
Can a setting be added in  minetest.conf to turn off allowing map saving for connected clients?

**Comment by piecubed** [comment]
For example, servers like PK which have banned map saving cant enforce it.

**Comment by Linuxdirk** [comment]
A feature like this can be added, but since the client is open source it is easy to circumvent it.

**Comment by benrob0329** [comment]
This sounds like a great way to give people a false sense of security, and to cause a lot of server maps to be lost to time. For example, the only reason we have maps of Red Crab is because of this feature.

**Comment by rubenwardy** [comment]
I use this feature to save backups of my own builds, because I don't trust server hosters not to lose all their data or to stop hosting - because it happens

**Comment by Fixer-007** [comment]
Not in a spirit of open source tbh...

**Comment by SmallJoker** [comment]
I can see the point of server owners that they don't want to see their server map being stolen/copied. But many servers went down and I'm glad that I could at least keep some of my buildings saved locally.
