### ISSUE TITLE
Add giant caverns to Mapgen Flat

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8582]
Reminder for myself.
Giant caverns were requested for mapgen flat and i agree.

**Comment by paramat** [comment]
So, do any core devs support? Any objections?

**Comment by SmallJoker** [comment]
Neither support nor objections. I personally don't see a need for it.

**Comment by paramat** [comment]
Here is how i see it:

Although the cavern cave type is not as essential as the 3D noise tunnels or randomwalk caves, it is a standard shared-code cave type present in all of the more conventional mapgens and is added to any mapgen where it is suitable, it is not considered a special feature. It adds variation and interest to the underground.

Mapgen Flat is a fully-featured mapgen for general use, it has options for lakes and hills, it is not meant to just be a flat surface as in some mods. So there is no reason why caverns would be unsuitable for mapgen flat.
it was partly written to replace the 'flat' option of mgv6, which is also a fully featured mapgen that just happens to have a flat surface.

It seems odd to me why someone would 'not see a need', if there is no need in mapgen flat then there is no need for any mapgen. An option that makes the underground very much more interesting seems obviously desirable.

However, i am currently not interested in adding it to mapgen fractal, as i consider the non-fractal terrain there of low importance and possibly a mistake.
