### ISSUE TITLE
Gettext disabled?

### ISSUE THREAD

**Issue by sodomon2** [minetest/minetest#8588]
Gettext disable?
-- *** Will build version 0.4.17.1 ***
-- Detecting GMP from system failed.
-- Using bundled mini-gmp library.
-- Using bundled JSONCPP library.
-- Using LuaJIT provided by system.
-- cURL support enabled.
-- GetText disabled.
-- Sound enabled.
-- Freetype enabled.
-- ncurses console enabled.
-- PostgreSQL backend enabled
-- PostgreSQL includes: /usr/include
-- LevelDB not found!
-- Redis backend enabled.
-- SpatialIndex not found!
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/minetest-0.4.17.1

**Comment by paramat** [comment]
Possibly related #8583

**Comment by SmallJoker** [comment]
1) Install https://pkgs.alpinelinux.org/package/edge/main/x86_64/gettext-dev
2) Clear the CMake cache
3) Re-configure CMake
4) Post the new error log here

**Comment by mckaygerhard** [comment]
the cmake does not detect correclty the gettex event the dev package are installed?

**Comment by sodomon2** [comment]
Cmake doesn't detect gettex-dev. I have all the libraries I need, and he's still making that mistake.
Is it a library error or a cmake error?

**Comment by SmallJoker** [comment]
Same issue as reported in #8583. Closing this duplicate.
