### ISSUE TITLE
[Feature Request] Vertical hotbar

### ISSUE THREAD

**Issue by carlsmith** [minetest/minetest#8595]
I often use the mouse wheel to select between items in the menu. If the menu was vertical (and moved to the right-hand side of the screen), it would be more intuitive to scroll through, and would make better use of the available space.

Providing a vertical menu would raise the issue of where to place the hearts and bubbles. My preference would be for rendering them as icons (instead of bars), so they'd fit nicely beside the item menu.

Another option is just having simple solid bars (that could then be thinner than the current ones), and color-coding them (red for health and blue for air).

Thanks for considering it, either way.

**Comment by paramat** [comment]
I guess you mean add an option for a vertical hotbar? Horizontal should remain an option.

Use of the mouse wheel would be slightly more intuitive but it doesn't seem much of an issue to me as it is easy to get used to.
Many players use number keys to select items, that would then become unintuitive.
A horizontal hotbar at screen base seems optimum to me, as unobstructed far left/right view is more important than looking downwards.

Overall i don't think there's enough justification, sorry :-1:

**Comment by benrob0329** [comment]
A few things worth noting:
* Minetest Originally Had A Vertical Hotbar
* Having HUD Stuffs On The Side Makes More Sense With Widescreens
* Games May Want To Change This

**Comment by rubenwardy** [comment]
This is already possible using the HUD API, afaik

**Comment by paramat** [comment]
Closely related to #8565

**Comment by ClobberXD** [comment]
Also closely related to #8297

**Comment by carlsmith** [comment]
> A horizontal hotbar at screen base seems optimum to me, as unobstructed far left/right view is more important than looking downwards.

I'd agree with that for most games, as you generally look across your horizon (not at the sky or floor), but when you're mining and building, you do look up and down a lot more often.

**Comment by paramat** [comment]
> This is already possible using the HUD API, afaik

Needs confirming.

**Comment by ClobberXD** [comment]
Assuming rubenwardy is referring to the Lua API, it supports displaying inv. lists using the [`inventory`](https://github.com/minetest/minetest/blob/429a98964859b83016f2eb47a47a08ab8dc3c57e/doc/lua_api.txt#L1300) HUD element type. This can be used to create a vertical inv. list of the first 10 elements from `"main"`, but I'm not sure if this can be mapped to the hotbar.

Another concern with a vertical hotbar - MT supports upto 32 slots for the hotbar, but the display might not be large enough to accommodate 32 slots vertically. But this is up to the mods/games to handle, I suppose.

**Comment by carlsmith** [comment]
> Another concern with a vertical hotbar - MT supports up to 32 slots for the hotbar, but the display might not be large enough to accommodate 32 slots vertically.

I saw a mod that makes the hotbar circular (with the slots in a ring), with most of it offscreen, so only a few items are onscreen at a time. It then rotates as you cycle though the items. IMO, it would be better if the hotbar looked like it does now, but could still rotate, more like a carousel (or one-armed bandit, if the hotbar was vertical). Users could then set the maximum items (default to ten) to render at a time. The currently selected item would always be (roughly) centered, and scrolling through would just rotate the items into place. It would look just like it does now, but could be any length.
