### ISSUE TITLE
Improve unnamed world naming

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8598]
As a core dev i often rapidly create mulitple worlds then map them using the minetest mapper.
I am getting very irritated with the naming scheme for unnamed worlds:
* 'Unnamed' starts with a capital letter, which requires pressing shift. I doubt many people bother to use a capital letter even for their named worlds. Even if they do, an auto-named world does not really deserve a capital letter.
* 'Unnamed' is a long word when 'world' or even just 'w' would be fine and obvious.
* 'Unnamed' is an ugly and awkward word.
* It is unnecessary to state the world is 'unnamed', that will be obvious from the auto-name anyway. Also, it is not unnamed if it is given an automatically generated name, so it is paradoxical.
* 5 numbers are used, i can't imagine anyone needing more than 999 unnamed worlds, so 3 numbers is more than enough, easier to copy, remember, identify.

My suggestion:
'world123'

**Comment by SmallJoker** [comment]
`Unnamed_YYMMDD_hhmmss`. Would allow sorting the worlds easily and chances to have duplicates is not possible by clicking buttons.

**Comment by paramat** [comment]
Duplicates are already avoided by the code.
That would be far more effort to copy and type, and it uses a capital letter,  so as you can see from my issue, i can't support that =)
However i wouldn't oppose as it (unfortunately) does make some sense =)

**Comment by Extex101** [comment]
I use capital letters for my worlds

**Comment by paramat** [comment]
The date/time format does make sense and is consistent with screenshot naming, so i might actually support that, but only if `world_...`, screenshot naming uses lower case and is
`screenshot_YYYYMMDD_HHMMSS`.

**Comment by paramat** [comment]
Thinking further, i disagree with a screenshot-type date-time string, as that is far longer so far more irritating to copy when using the mapper, so would make things even worse.
World names should be somewhat memorable and identifiable, 'w301' is, but a long date-time string is not.
I cannot see any need to strictly time-sort worlds, they are not like instantaneous screenshots, they are updated regularly so time of creation is not important.
So:
'w123'

**Comment by v-rob** [comment]
I like the shortness.  Makes it easier to find when debugging, which is what unnamed worlds are probably most used for.

**Comment by rubenwardy** [comment]
I like this, but also think that it would be better if the number was incremental rather than random - much easier to know which was the latest created

**Comment by paramat** [comment]
Ok, i will see if i can do that.
Perhaps: Scan current `world<number>` numbers, add 1 to largest number. If no names in that format, restart at 'world1'.

**Comment by Wuzzy2** [comment]
Yes, “world” plus a number counting upwards (starting with 1) is the best solution. It's the most simple one, and easy to understand.

**Comment by sirrobzeroone** [comment]
@paramat 

I'm not sure if needs to be game specific? at the moment the below code will count worldXXX across the whole engine not just a specific game. On my local copy I've dumped the below code into dlg_create_world.lua  lines approximately line 110. If your interested in this still I can work this  a bit more and see if I can identify number sequence gaps to make it a little more robust - get around some smarty making "world999" and then watching the engine get jammed in a i cant create that loop after it auto creates "world1000".

> 			if worldname == "" then
			    local count =  1
				local worldname_list = menudata.worldlist:get_list()				
					for k,v in pairs(worldname_list) do 						
						if string.sub(v.name, 1, 5) == "world"  and
						   string.len(v.name) >= 6 and    
						   string.len(v.name) <= 8 then
						   
								local new_count = tonumber(string.sub(v.name, 6, 8))
								
									if new_count >= count then
										count = new_count+1
									end
						end
					end					
				local random_world_name = "world" .. count
				worldname = random_world_name
			end

**Comment by paramat** [comment]
Sorry for the late reply.
Thanks for this, it is very close to what i and others are suggesting.
I might work on a PR soon and this will help.
I think it is best this is not game-specific to avoid duplicated world number confusion, so your code is fine in that way.

**Comment by sirrobzeroone** [comment]
No worries at all, I know yourself and other devs have been flat-out getting 5.3 wrapped and out the door. If its helpful I can raise PR but only if it's helpful- I understand me raising the PR might not be very helpful as I know that still means yourself/core-devs have to review, which just eats up more of the limited time you all have.

**Comment by paramat** [comment]
Thanks but probably no need, as i seem to be in the mood for making a PR.

**Comment by Extex101** [comment]
PRmood™

**Comment by paramat** [comment]
PR #10247
