### ISSUE TITLE
csm_node_range = 0 should be inherent in csm_restriction_flags = 0 (combine settings)

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#8602]
it's confusing enough as it is...

**Comment by paramat** [comment]
The settings can't be combined. Instead, do you mean 'csm_restriction_flags = 0' should automatically set 'csm_node_range = 0'?
'csm_restriction_flags = 0' means no restrictions, so why would you want 'csm_node_range = 0' in that situation?

**Comment by paramat** [comment]
No response.

**Comment by jastevenson303** [comment]
I mean there's too many damn steps to enabling CSM!
