### ISSUE TITLE
Add mapblock meta

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#8605]
## Problem

I'm always frustrated when I want to save with a lua mod something persistently in a whole mapblock.

## Solutions

I would like to have the ability in lua to get and set persistently some information in a whole mapblock, not just one node.
This should be done with something like a mapblock meta.
Eg. `minetest.get_block_meta(blockpos):set_string("foo", "bar")`.

## Alternatives

This could be done in modding with world meta. However this means that the meta of all mapblocks is sent, not only of the loaded ones.

## Additional context

How difficult would it actually be to implement something like this?

### usecases

- A protection mod that wants to add protection nodes that protect nodes in a specific radius could for example save on placement of a protection node for each mapblock that it interferes with it's position (as hashed node position). The mod would then on every interact not have to find such a node in an area, searching through maybe 5^3 nodes, but just have to look into the mapblock meta to cycle through all the position where a protection node could be. This would probably be more efficient.
- I'm pretty sure there are many more usecases.

**Comment by rubenwardy** [comment]
The first usecase you give should be solved using areastores

**Comment by rubenwardy** [comment]
I'm unsure on this usecase, I think area store store persistence / more meta data would be a better way to implement this. Generally, the Lua API tries to avoid having the modder having to care about mapblock boundaries

**Comment by Desour** [comment]
It would indeed be nice if areastores were stored persistently and efficiently (i.e. areas should not be stored in a simple list).
But it looks like currently you have to manually escape it to a string (a feature marked as "Experimental" ([api](https://github.com/minetest/minetest/blob/74d9b6010fd42573d20cdbe78f7aaa07badfbf1b/doc/lua_api.txt#L5636))) and store it in your worldstorage (or in a file).

I don't want to load data that is spread over the whole world into ram at once. I want this data to be associated with the place where it describes something (its mapblock(s)).

**Comment by paramat** [comment]
No core dev support after a year so closing.
