### ISSUE TITLE
Fixing the leaky floatlands

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8610]
![screenshot_20190619_234152](https://user-images.githubusercontent.com/3686677/59806489-59eaad80-92ec-11e9-9d79-a1f8a4229e12.png)

If these water columns reach the surface they will cause flooding. However, they will also be ~a way to ascend to the floatlands in a boat and~ a way to decend safely by falling in and out of the column.

These leaks are unavoidable if the floatlands have tunnels. Perhaps i could not generate tunnels below floatland surface level, will experiment.

**Comment by paramat** [comment]
The water columns only reach the surface if a player is near them for the entire slow journey down, it takes about 30 mins for them to reach ground (testing this now), so it won't happen much.

**Comment by paramat** [comment]
![screenshot_20190620_001145](https://user-images.githubusercontent.com/3686677/59807718-0595fc80-92f1-11e9-973e-e03bc37778ec.png)

![screenshot_20190620_001045](https://user-images.githubusercontent.com/3686677/59807720-09c21a00-92f1-11e9-8ab9-af56c0b9540c.png)

**Comment by paramat** [comment]
I think i will remove tunnels above floatland surface level.

**Comment by Fixer-007** [comment]
Feature or a bug?

**Comment by paramat** [comment]
Lol, the leaks were intentional, so feature.

**Comment by FaceDeer** [comment]
Having at least the option to disable tunnels in floatlands would be nice, they cause more immediate leakage problems when I've got the dynamic_liquid mod installed. Lakes will drain out of their basins while a player is near them, which is bad even if the giant blob of water never finishes descending to the land below. I actually added an option to dynamic_liquid to disable the mod above a certain altitude as a way to prevent this.

**Comment by benrob0329** [comment]
Waterfalls flowing off the edge would look better than a pinhole in the bottom of a lake IMO.

**Comment by paramat** [comment]
I will fix this issue as part of some upcoming changes to floatland generation.

**Comment by paramat** [comment]
> I think i will remove tunnels below floatland water level.

Tried that and it is very ugly to enter a tunnel and find a flat surface at water level. It is also good to have tunnels throughout floatland terrain.
Instead perhaps i will make the floatland terrain deeper to reduce the chance of water reaching the floatland underside. Occasional leakages are not a big problem as it takes effort to propagate them to world surface.

I intend to alter floatland terrain anyway, as i realise i made a mistake using mgv7 mountain 3D noise for the floatland 'mountains'. Each terrain is not independently configurable and floatland mountain terrain has a shape compromised by the shape needed for the surface mountains. The crazy 3D shapes are a bit tiresome too.

My new approach is to use the existing 2 floatland 2D noises to form mountains, this looks more integrated and consistent, as well as making nicer mountain shapes.

**Comment by paramat** [comment]
![screenshot_20191004_213637](https://user-images.githubusercontent.com/3686677/66238523-b3d28000-e6ef-11e9-8ebe-e30af16adc2a.png)

**Comment by paramat** [comment]
![nf1_IND](https://user-images.githubusercontent.com/3686677/66238940-84704300-e6f0-11e9-945f-c844b4197e28.png)

**Comment by paramat** [comment]
![screenshot_20191005_211302](https://user-images.githubusercontent.com/3686677/66260964-8f44d980-e7bd-11e9-9f45-bd66a43e4ab4.png)

Smoother.

**Comment by paramat** [comment]
Closing as i prefer either removing mgv7 floatlands or radically changing them to have no water.
