### ISSUE TITLE
[Custom Keybindings] General Issues and Feedback

### ISSUE THREAD

**Issue by carlsmith** [minetest/minetest#8624]
I designed a set of keybindings, but cannot implement them properly. The Keyboard Settings GUI is buggy and `minetest.conf` lacks some basic options. This cheatsheet covers everything I'm trying to implement:

```
Q: QUICK		Toggle Quick Mode (fast)
E: EXTEND		Special Action (aux)
R: RANGE		Range Select
Y: YOMP			Autoforward
F: FLY			Toggle Fly Mode (fly)
G: GHOST		Toggle Ghost Mode (noclip)
H: HIGHER		Higher Visibility (inc. range)
L: LOWER		Lower Visibility (dec. range)
Z: ZOOM			Zoom
X: DROP			Drop
C: CRAFT 		Toggle Crafting Menu (inventory)
V: VIEW 		Change View (camera)
B: BACK			Select Previous Item (prev. item)
N: NEXT			Select Next Item (next item)
M: MINIMAP		Toggle Map (minimap)
O: ORIENT    	   	Toggle Oriental Movement Mode (pitch move mode)
P: POST			Post Message (chat)

1-8			Select Specific Item

WASD			Walk & Strafe
Space & Shift		Jump & Creep

Up			Maximize Volume
Left & Right		Increment & Decrement Volume
Down			Toggle Mute

PrintScreen		Take Screenshot
ScrollLock		Toggle Cinematic
Pause			Pause/Unpause Game

Backspace		Toggle Fog
Tab			Toggle HUD

]			Toggle Console Prompt
[			Toggle Console Log
/			Quick Command
\			Local Command

`			Toggle Performance Profile Overlays
```

Note: The Royal Marines use *yomp* as slang for a long march (fully kitted out for battle), and it implies being forced to keep moving.

Note: I'm on an up to date Mac.

Bugs
-----

Some keys can be set, but will then not function properly. For example, I can set <kbd>H</kbd> and <kbd>L</kbd> to *Inc. range* and *Dec. range*, and hitting <kbd>H</kbd> ingame works (incrementing the visibility), but hitting <kbd>L</kbd> toggles **Pitch Move Mode**.

Some keys are misnamed in the GUI, but then still work correctly. For example, I can assign <kbd>]</kbd> to toggle the console, and it works correctly ingame, but in the bindings menu, the <kbd>]</kbd> key is named *Apps*.

Some of the options are not described very well (by their names or otherwise). For example, **Chat** posts a single message to the chat, but the word *chat* implies something ongoing, which is what **Toggle Console** actually does. A name like **Post** or **Comment** would be more intuitive.

Limitations
-----------

I cannot pause the game, just generally. I know that you can, but cannot figure out how to do it?? The bindings menu has no option for binding a key to *Pause*, and `minetest.conf` has no `keymap_pause` option (or anything similar). It seems likes <kbd>Pause</kbd> (<kbd>F15</kbd>) should pause/unpause the game by default.

I find keybindings more intuitive if each letter key is bound to an abstract command with a name that starts with the corresponding letter (treating the WASD keys and <kbd>X</kbd> as edge cases). To pursue that scheme, Fast Mode was renamed *Quick Mode*, because *fast* conflicts with *fly* (and *free*). It would be nice if internal names were generally hidden from endusers, so changing external names would be easier.

Conclusion
-----------

None of these bugs or limitations are preventing me from having fun playing Minetest, but as a dev looking at modding, being able to fully customize keybindings is pretty important.

**Comment by carlsmith** [comment]
I appreciate that the current keybindings evolved as new features were added, but as a relatively new user, blessed with hindsight, the current bindings seem a bit messy and unintuitive. If the keybindings are ever overhauled in a future version, I would put my scheme forward as a good starting point, and would also like to propose dividing the keyboard into blocks...

All of the core controls would use the Main Block, the Auxiliary Block (<kbd>Print Screen</kbd>, <kbd>Scroll Lock</kbd> and <kbd>Pause</kbd>), the Arrow Block (<kbd>Up</kbd>, <kbd>Down</kbd>, <kbd>Left</kbd> and <kbd>Right</kbd>) and <kbd>Esc</kbd>, with the unused keys on the Main Block (<kbd>T</kbd>, <kbd>U</kbd>, <kbd>I</kbd>, <kbd>J</kbd>, <kbd>K</kbd>, <kbd>Enter</kbd>, <kbd>Plus</kbd>, <kbd>Minus</kbd>, <kbd>Semicolon</kbd>, <kbd>Quote</kbd>, <kbd>Comma</kbd> and <kbd>Dot</kbd>) reserved for future use.

The Nav Block (<kbd>Insert</kbd>, <kbd>Delete</kbd>, <kbd>Home</kbd>, <kbd>End</kbd>, <kbd>Page Up</kbd> and <kbd>Page Down</kbd>) would be reserved for devs. For example, <kbd>Insert</kbd> could toggle random user input.

The Function Row would be reserved for the the end user. MacBooks already overload those keys with system stuff like the keyboard and screen brightness, and it's generally a good idea to reserve some keys exclusively for the end user.

Finally, the NumPad would be reserved exclusively for mods, so they have their own space to play with.

That covers every key on a standard ANSI keyboard, and nonstandard keys (like <kbd>F16</kbd>) would be unsupported.

**Comment by orwell96** [comment]
The pause menu is accessible via the ESC key.
It really is a pity that some keybindings are hard-assigned, such as the F keys and some new features

**Comment by Linuxdirk** [comment]
rel: https://github.com/minetest/minetest/issues/4536

**Comment by carlsmith** [comment]
Thanks, @Linuxdirk. I wasn't familiar with #4536 or the issues that it references. Hopefully, the keybindings implementation will be rewritten in a future version, allowing a lot of these issues to be closed in one go. I'll close this one now. It doesn't define a specific open issue, and would be a better fit for a mailing list.
