### ISSUE TITLE
Can't join server when a message is sent on the server

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8626]
##### Minetest version
```
Minetest 5.1.0-dev-35b5a43a
```

##### Summary
When you're joining a server and a chat message is sent you will sometimes be unable to join?

##### Steps to reproduce
Create a mod with this code and try to host the server
```lua
minetest.register_globalstep(function()
	minetest.chat_send_all("You can't join >:D")
end)
```
![image](https://user-images.githubusercontent.com/28972859/60114159-1b0f8a00-9728-11e9-8c17-7df933514c14.png)

**Comment by rubenwardy** [comment]
This looks like a bug in the CSM API. Do you have it enabled, and do you have any CSM mods installed?

**Comment by LoneWolfHT** [comment]
Hmmm. I do
`modform`, `savepos`, and `dte`

**Comment by rubenwardy** [comment]
It's annoying that there's no stack traceback to it. I suggest looking for `on_receiving_message` callbacks, and looking for references to `minetest.localplayer` or such without checks

**Comment by LoneWolfHT** [comment]
I've disabled all of my CSMs. Still crashes
Disabling the client-side-modding setting fixes this though

**Comment by ClobberXD** [comment]
I too recently faced this issue thrice in a row, before being able to successfully join the server (CTF in my case - tons of chat messages flying around at the peak hours).

**Comment by LoneWolfHT** [comment]
@ClobberXD This PR fixed it for me https://github.com/minetest/minetest/pull/8627

**Comment by ClobberXD** [comment]
That's great. I'll try it out today.
