### ISSUE TITLE
Map conversion  https://www.planetminecraft.com/

### ISSUE THREAD

**Issue by zz1616611** [minetest/minetest#8633]
Hope to support https://www.planetminecraft.com/ 
Map conversion

**Comment by rubenwardy** [comment]
Please include a proper description.

Are the maps in Minecraft's world save format? If so, there's tools for that: https://forum.minetest.net/viewtopic.php?f=12&t=13709

We will not be adding support for MC world saves / maps

**Comment by paramat** [comment]
:-1: for adding internal MC map conversion, that's best left to external programs.
