### ISSUE TITLE
ObjectRef:set_texture_mod doesn't work

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8634]
##### Minetest version

```
Minetest 5.1.0-dev-e32a6309-dirty
```

##### Summary

Using `set_texture_mod` doesn't have any effect on the object's texture. Here are the following texture modifiers I've tried to set, using this method:
- `[brighten`
- `[invert:rgb`
- `[multiply:#1f1`
- `[opacity:128`

This problem can be partly attributed to the complete lack of documentation on `set_texture_mod` (see #4226). I've also tried passing the texture modifier string with `^` at the beginning - no difference.

##### Steps to reproduce

(I observed this issue while running two MT instances on the same machine - one as client, and the other as server+client. But the following _should_ produce the same results if I'm not mistaken)

- Enable `luacmd`, and grant yourself the `lua` priv.
- Change camera mode to `third` or `third_front`.
- Enter the following commands in the chat terminal:
  ```
  /lua me:set_texture_mod("[brighten")
  /lua me:set_texture_mod("[invert:rgb")
  /lua me:set_texture_mod("[multiply:#1f1")
  /lua me:set_texture_mod("[opacity:128")
  ```
- Observe that the your skin does not change in any way.

**Comment by IhrFussel** [comment]
I'm pretty sure that this method only works for lua entities and not players.

At least last I checked it was like that.

**Comment by SmallJoker** [comment]
Which was the last good Minetest version?

**Comment by paramat** [comment]
`LuaEntitySAO::setTextureMod()` seems to be for lua entities only. It's very old, 2011.
We may have to ask celeron55.

**Comment by ClobberXD** [comment]
So is this just a documentation issue?

**Comment by paramat** [comment]
@IhrFussel so does it work? What is it used for? I can't imagine it can update a textrue modifier in-game.

**Comment by IhrFussel** [comment]
It works in 0.4.17.1 and I use it to colorize mobs like this:

**self.object:set_texture_mod("^[colorize:"..entcol..":50")**

**Comment by ExeVirus** [comment]
When reading the minetest dev wiki:  specifically the [ObjectRef Page](https://dev.minetest.net/ObjectRef)

The second line states that all objectref's are luaEntities _except_ player. We could this behavior I think, but as it currently stands this is not a bug.

**Comment by ClobberXD** [comment]
This method is actually documented under `LuaEntitySAO-only` sub-section in `lua_api.txt`. It was I who thought PlayerSAO was a sub-class of LuaEntitySAO. Sorry for the confusion.
