### ISSUE TITLE
Cannot assign the L Key to Dec. Range

### ISSUE THREAD

**Issue by carlsmith** [minetest/minetest#8635]
##### Minetest version

```
Minetest 5.0.1 (OSX)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="minetest.app/Contents/Resources"
```

##### OS / Hardware

Operating system: macOS 10.14.5
CPU: 1.3GHz Intel Core i5

##### Summary

I can assign <kbd>H</kbd> (for *higher*) to **Inc Range**, but cannot assign <kbd>L</kbd> (for *lower*) to **Dec. Range**. The menu seems to work, so the keys appear to be assigned correctly, but when I use them ingame, <kbd>H</kbd> works (increasing the viewing range), but <kbd>L</kbd> toggles **Pitch Move Mode**.

**Comment by pauloue** [comment]
This should be fixed since https://github.com/minetest/minetest/commit/4f7674d448abb9f12030c743a1a6a0d3ad07ad7c.

**Comment by SmallJoker** [comment]
Key assignment collision. Resolve your key assignments ("Advanced Settings" will help) to fix this problem.

**Comment by carlsmith** [comment]
> Key assignment collision...

@SmallJoker - I see. I'm going through my `minetest.conf` now, and configuring everything that way. I just tested whether <kbd>H</kbd> and <kbd>L</kbd> work correctly (for changing the range), and they do now, so my problem is fixed. Thank you.

The bindings menu is still really buggy (at least on my system), but that can be dealt with elsewhere.
