### ISSUE TITLE
Solving  error: ‘MutexAutoLock’ was not declared in this scope error.

### ISSUE THREAD

**Issue by crazybytes** [minetest/minetest#8638]
## Problem
Receiving the error  error: ‘MutexAutoLock’ was not declared in this scope when compiling.

## Solutions

https://github.com/bitcoin/bitcoin/issues/8511

**Comment by SmallJoker** [comment]
Why are you referring to bitcoin? This is Minetest, by the way.
Would you please be so nice and provide more of this error log? The source code is big, and MutexAutoLock quite common.
Why is it a Feature request?
the hecc.

**Comment by crazybytes** [comment]
Yes you are right.
Somehow its fixed now.....
Thought it could be usefull.
Delete the shit.
