### ISSUE TITLE
Hide mapgen v6 in mapgen selection dropdown

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8644]
I see a lot of players reporting missing features in mapgen v6, and i spend a lot of time explaining that it has hardcoded biomes, fewer biomes, less variety of flora, doesn't use the Biome API etc. Then i feel bad that they started a world in such an unimpressive mapgen.

Although of course (unfortunately) we have to support mapgen v6 worlds (i would love to rip mapgen v6 out, it's a colossal pain), it's so much poorer than the other mapgens i think we should encourage newer players to avoid it.

This can be done using the ability to hide mapgens from the mapgen selection dropdown.
It will still be selectable using a setting in .conf or in the 'all settings' menu, but this will make it a concious effort, instead of tempting all players by having it in the dropdown.

**Comment by DS-Minetest** [comment]
Can't the dropdown entry just be renamed to something like `v6 (old)`?

**Comment by paramat** [comment]
The dropdown can only display the raw mapgen names currently, so displaying extra mapgen info will need to be coded.
The advantage of hiding is that it is simple, requires no coding, and is more discouraging for everyone, which is the whole idea, i don't want mgv6 to be easily selectable, which it will be with your suggestion.
I don't want it to appear as valid as the other mapgens.

I really want to remove mgv6, but i can't, so this is the minimum that would satisfy me =)

**Comment by Linuxdirk** [comment]
> The dropdown can only display the raw mapgen names currently

So this is something to work on 😄 This would finally allow proper mapgen names.

Oh, and yes: Remove incompatible or unwanted mapgens. This is what the function was implemented for.

**Comment by paramat** [comment]
I meant that referring to the request for mapgen info to be displayed beside each, not to display new mapgen names. The 'raw mapgen names' are the proper names, they're not engine terminology.

**Comment by Moth-Tolias** [comment]
if you do decide to hide v6, hiding the "empty node" one sounds like a good idea as well. took me a while to realise that the reason i was continually falling into the void was actually that i had accidentally set it as such rather than that the game was bugged.

**Comment by MarkuBu** [comment]
I just want to mention that some games like Voxelgarden recommend v6

**Comment by paramat** [comment]
'singlenode' used to be hidden for that reason but was unhidden later, see #5867 #5868

**Comment by paramat** [comment]
Changed my mind because https://github.com/minetest/minetest/pull/5868#issuecomment-305422692
"Some mods select options depending on mapgen, but singlenode has to be enabled by a mod and that mod may be loaded after the mod that detects mapgen.
This resulted in Nyan Cats appearing in singlenode even though they were not meant to, because default loaded before any mod that enables singlenode. In this way re-adding it to menu will help."

I agree it's better to add some in-game mapgen info to warn, as already requested.

**Comment by Linuxdirk** [comment]
Nyan Cats don't show up at all anymore since a few years.

**Comment by paramat** [comment]
LOL yes good point =) It was just an example of the sort of problem that can happen.

Here's a simple thing that might help for now: I could move v6 to the bottom of the mapgen selection list.
