### ISSUE TITLE
MineTest for Elbrus(e2k) platform.

### ISSUE THREAD

**Issue by DJs3000** [minetest/minetest#8655]
I have successfully run minetest on Elbrus computer. This is a Russian computer that has the original vliw architecture. Uses Linux redesigned for Elbrus(e2k) architecture. MineTest on Elbrus works very well, but in one thread on one core(8 cores in total). MineTest is able to work in multi-threaded mode?
If you log on to a server with a large number of buildings, you may see slowdowns, due to 100% load of one core.

**Comment by ClobberXD** [comment]
Is this a feature request for (better) multi-threading?

Minetest actually is multi-threaded, by the way: https://dev.minetest.net/Engine_structure#Threads

> ### Stand-alone server
>  - main
>    Doesn't do much
>  - ServerThread (Server)
>    Runs the server
>  - EmergeThread (Server)
>    Fetches and generates world
>
> ### Client-only
>  - main
>    Runs almost everything in main game loop
>  - MeshUpdateThread (Client)
>    Does mesh updates in the background
>
> ### Singleplayer
>  - main
>    Runs almost everything except server in main game loop
>  - MeshUpdateThread (Client)
>    Does mesh updates in the background
>  - ServerThread (Server)
>    Runs the server
>  - EmergeThread (Server)
>    Fetches and generates world

But I agree, MT should be _more_ multi-threaded, if that makes sense.

**Comment by DJs3000** [comment]
![scr01](https://user-images.githubusercontent.com/16526540/60669738-b8c92e80-9e77-11e9-85c2-383c27c5e9e6.jpg)

I have MT work only one thread :(
[cmake_mt.txt](https://github.com/minetest/minetest/files/3359465/cmake_mt.txt)

**Comment by style-nine** [comment]
Running everything as root?

**Comment by DJs3000** [comment]
> Running everything as root?

Yeah, it's a test computer.

**Comment by paramat** [comment]
I guess this is a quesiton about, and/or a request for, multi threaded operation on Elbrus(e2k).

**Comment by rubenwardy** [comment]
VLIW is a mostly dead paradigm, and I doubt many people use this particular at all

:-1: for us doing anything to add support it

**Comment by style-nine** [comment]
Isn't MIPS a lot like the ARM you see in a lot of Android devices? It could actually be a big benefit.

**Comment by DJs3000** [comment]
> I guess this is a quesiton about, and/or a request for, multi threaded operation on Elbrus(e2k) https://en.wikipedia.org/wiki/Elbrus_2000

Yes, 8S revision.

**Comment by DJs3000** [comment]
> VLIW is a mostly dead paradigm, because it doesn't actually provide as good a performance improvement as RISC superscalar designs. I doubt many people use this particular chip at all
> 
> 👎 for us doing anything to add support it

Elbrus is a superscalar processor. Performance 250 GFlops(this is about i7 4 gen).

**Comment by style-nine** [comment]
So, what's the viewing_range and fps_max set to on your client?

**Comment by paramat** [comment]
I'm assuming Elbrus(e2k) is rarely used and it is not a trivial change to support this.
:-1:

**Comment by DJs3000** [comment]
ok, close ticket.

**Comment by DJs3000** [comment]
Problem solved itself. A new revision of the operating system Elbrus OS and all games began to work in multithreaded mode. Now MT works very well :)

**Comment by rubenwardy** [comment]
That's good to hear!
