### ISSUE TITLE
Hint about required dependencies

### ISSUE THREAD

**Issue by AKryukov92** [minetest/minetest#8661]
## Problem

It is not clear what dependencies I should download to run some mod.
For example:
- make clean install MT 5.0.1.
- download mod named "Mobs Monster" and log in to game
- create fresh world
- open settings, enable "mobs_monster" (Note that name of the mod differs from name in contentDb)
- press "Play"
Get message `ERROR[Main]: mod "mobs_monster" has unsatisfied dependencies:  "mobs"`

The question is: What mod should I download to satisfy this dependency?
I know that it should be "Mobs Redo", but its name doesn't match to the technical name in the error.

## Solutions

Display a message in the mod list "This mod is required for your installed mod X".
In my example, this message should be displayed at "Mobs Redo" mod.

## Alternatives

Like in web version of ContentDb. There are fields "Provides" and "Dependencies" for each mod.

**Comment by SmallJoker** [comment]
`mods` is the internal name of `Mobs Redo`. Minetest cannot print the friendly name if the mod isn't installed (how even should it). The information could be fetched from CDB, but that will be a very limited set of the actual available mods.

**Comment by paramat** [comment]
'mobs redo' is only used by the mod author as the GitHub repo name and the forum thread title, so it's not possible to access the alternative mod name. Doing so through CDB would be complex and only work for some mods, so not worth it.
Forum threads have the technical mod name included in the title, which helps.

**Comment by AKryukov92** [comment]
> By 'mod list' do you mean the in-game Content DataBase?

Yes, I meant in game CDB (which opens when you click, not list of installed mods.

> Forum threads have the technical mod name included in the title, which helps.

There is no link to forum thread in the in-game CDB.
I suppose that CDB whole idea is about installing mods using only game client. Using external program (browser) to find information about mod dependencies does not fit to this idea.

BTW, I think that API is a very technical term, which is not clear to most of the people. There should be more trivial terms to explain mods relationship.

**Comment by rubenwardy** [comment]
:-1:

**Comment by AbyssalKnight95** [comment]
Same problem having errors like missing 'i18e' to 'ie' ... like whats wrong with the modders after downloading it goes brrrrr error

**Comment by AbyssalKnight95** [comment]
![Screenshot_2025-01-10_213658](https://github.com/user-attachments/assets/212ccaf1-9d53-4de3-9f9a-40675d0100a1)

**Comment by sfan5** [comment]
You should report this bug to the mod you have installed. It has nothing to do with the engine.
