### ISSUE TITLE
The function add_group for nodes and items in the api. 

### ISSUE THREAD

**Issue by acmgit** [minetest/minetest#8671]
## Problem
A new function add_group for the api.
The function minetest.override is doing their job good, but it override.
Instead of overriding, it would be good to have a function to add groups in the items, independent from other mods.

Why is this needed?
This would prevent much collisions between the recipes.
More independence between mods and better support for foreign mods, because they then independent from updates of the other mod.
For example: 
The different farming-mods and their cooking recipes.
Different furniture-mods can better use their items together.

## Solutions
A function in the api, which add groups to always registered items.
For example:
add_group("default:wheat", {straw = 1})

This would than add straw to default:wheat and i can define a recipe with group:straw instead default:wheat, mod:hay, default:grass.

**Comment by ClobberXD** [comment]
I don't think adding this function to the API is worth the development effort. I can understand why a convenience function might sound like a good idea, but your proposed use-case can be achieved with very minimal effort, using `minetest.override_item` itself:

```lua
local groups = minetest.registered_items["<your_item_name_here>"].groups
groups[<your_new_group_name_here>] = <value_of_your_new_group_here>
minetest.override_item("<your_item_name_here>", {
	groups = groups
})
```

If you really want a convenience function, you can create it yourself within the mod, like so:
```lua
local function add_group(item_name, groups)
	local def_groups = minetest.registered_items[item_name].groups
	
	-- Add elements from groups to def_groups
	for group, value in pairs(groups) do
		def_groups[group] = value
	end

	minetest.override_item(item_name, {
		groups = def_groups
	})
end

-- Usage example: add_group("wool:pink", { ugly = 1 })
```

(WARNING: Untested code!)

**Comment by acmgit** [comment]
Right, i could create such function and i had created it in one of my mods, the solution is similar yours.
But, each mod, what could need such a function should create their own function, that do all the same?

**Comment by ExeVirus** [comment]
It is minimal code in either case, as it stands the core devs are not motivated to implement it because a current solution exists for developers. If you submit a good, working commit though, they might accept it just because it would be small and just as benign as not having it. 

I would add you also should create a remove_groups function if you go ahead and create a PR for it.

**Comment by SmallJoker** [comment]
> It is minimal code in either case, as it stands the core devs are not motivated to implement it because a current solution exists for developers.

Can confirm. Adding a new group to an item is a very specific function, and will only be used in a few mods. If we'd add helper functions for tiny tasks like this, the `lua_api.txt` file would easily bloat by a few thousand lines.

**Comment by paramat** [comment]
Hmm yes adding a group is very rarely done :-1:
