### ISSUE TITLE
Can't register on website

### ISSUE THREAD

**Issue by krzmaciek** [minetest/minetest#8684]
I tried to register on forum but I can't because my ip is banned. Why? I haven't ever done anything wrong in Internet, I tried also registering from my phone, but no effect, it seems all ip adresses from Play are blocked :/. I think you should disable it. Maybe many people can't register to your forum like me? This is pointless to block good people from supporting your game, IPs are dynamic, scammer just need to change ip and make other person blocked...

**Comment by BoQsc** [comment]
I'm new member as well, I tried to register a new account on the forum, and it seems I'm successful.
![Test](https://user-images.githubusercontent.com/21064622/61309320-a4cbe800-a7fa-11e9-9e30-5e55cfdbf872.png)

**Comment by krzmaciek** [comment]
Yeah, but I said many people, not all...

**Comment by Linuxdirk** [comment]
This is because outside the US most private users get dynamic IPs. So you might got an IP of a user that was banned by IP that also gets dynamic IPs and the mods do not have this in mind.

**Comment by paramat** [comment]
@rubenwardy is a moderator and may be able to help you.
I'll close this as unrelated to the code, but it will still get attention, i understand this may be the only way you can contact us.

**Comment by krzmaciek** [comment]
Thanks. I am waiting for moderator now :)

**Comment by paramat** [comment]
>  it seems all ip adresses from Play are blocked

What is 'Play'?

I left a message for a forum moderator on IRC.

**Comment by paramat** [comment]
krzmaciek are you on IRC? That's a good way to contact the moderators.

**Comment by sfan5** [comment]
see here for how to join IRC -> https://www.minetest.net/get-involved/#internet-relay-chat
