### ISSUE TITLE
minetest.get_item_group() returns 0 when group not found

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8703]
## Problem

`minetest.get_item_group()` returns 0 when an group isn't found. Why doesn't it return `nil`/`false`?

## Solutions

So far all I can think of is creating a new function that returns `nil`/`false` when a group isn't found and deprecating the old one. To prevent breaking mods that expect it to return 0

## Additional context
```lua
function core.get_item_group(name, group)
    if not core.registered_items[name] or not
            core.registered_items[name].groups[group] then
        return 0
    end
    return core.registered_items[name].groups[group]
end
```
### Additional Comments:
This is simple enough that I could create a PR for it. Once I know how to go about fixing this. If it's considered a problem

**Comment by ClobberXD** [comment]
Returning 0 when querying a non-existing group tends to be confusing, especially when 0 is also returned when a group exists with a value of 0. Returning `nil` would be a good idea, but we also need to take into consideration the vast number of mods that'd break due to this change.

**Comment by DS-Minetest** [comment]
:-1: 

The group rating is always a number. If a group is set to 0, it's not set.

I doubt that such a change would greatly reduce confusion.

Related:
https://github.com/minetest/minetest/blob/a1401696dfed5ba9faf3bbc2c8754e79346aa15f/doc/lua_api.txt#L1476-L1477

**Comment by ClobberXD** [comment]
> When not defined, the rating of a group defaults to `0`. Thus when you 
 read groups, you must interpret `nil` and `0` as the same value, `0`.

Wow, that clears things up a lot (but also adds to the confusion...). I used to liken this to the difference between `nil` and `false` in Lua. Shouldn't it be that way though? Isn't `group=0` a valid use-case for mods?

**Comment by SmallJoker** [comment]
FYI: Groups are integers in the engine.
As soon you index the map, a value will be inserted if it's not present. That probably happened earlier, thus the decision to use numeric values only and to define `0` as `no group`.

**Comment by paramat** [comment]
So, closing =)
