### ISSUE TITLE
Warning: seabed_height may be uninitialized in mapgen_fractal.cpp line 420

### ISSUE THREAD

**Issue by style-nine** [minetest/minetest#8714]
##### Minetest version

```
Minetest 5.1.0-dev-0cde6fc
```

##### OS / Hardware

Operating system: Ubuntu 18.04
CPU: AMD

##### Summary

```
				s16 seabed_height;
				if (noise_seabed)
					seabed_height = noise_seabed->result[index2d];

				if (((spflags & MGFRACTAL_TERRAIN) && y <= seabed_height) ||
```

The above should trigger a compiler warning (and does when I compile).

##### Steps to reproduce

git pull
make

**Comment by paramat** [comment]
Yes, i was concerned this might cause a warning. It didn't for me, but i am using an older version of cmake, and this was a little sloppy, will fix. Thanks.
