### ISSUE TITLE
Multiline rows for textlist[] and table[]

### ISSUE THREAD

**Issue by Sokomine** [minetest/minetest#8718]
Goal: Show a list of options (texts) to the player. The player selects one by clicking on it. Optional (nice to have, but not really important): Highlight text on mouseover.

Existing formspec elements like textlist[] or table[] can do this as long as each text fits into one line. Linebreaks can be enforced by manually inserting \n - which results in overlapping text and is not readable.

textarea[] can display the multipe-line text best of all formspec elements. It adds linebreaks and suitable spaces between lines. Problem here: How *high* does the textarea need to be in order to work without scrollbars? This depends on the text that is to be displayed, the width of the field and the font size. There's no way to tell formspecs to take all the space (horizontally) needed for a scrollbar-less display of the text - and then add the next textarea *below* that first one with a descent distance (perhaps half a line width). Also it needs to be clickable by the player.

Adding multi-line capabilities to table[] would probably be the most helpful option.

The reason for this request is that we currently can't create chat formspecs for mobs like in old point&click adventures. Those mobs would "say" a text upon rightclick and offer the player some numbered reactions (about 1-5) to choose from. Players could create adventures or just add mobs to their homes which "talk" to visitors.

**Comment by rubenwardy** [comment]
This is possible using buttons and formspec styling

**Comment by Sokomine** [comment]
A possible way how such an RPG formspec might look like:
<-------------------------------------------------------------------------------------------------------------------------
[ image of the mob,   ]  Hello developper! Thank you for visiting me. I've an urgent
[ head and upper       ]  task to do but can't leave here right now. Can you help me?
[ body part of its skin ]

1. Why can't you leave?
2. Of course! I don't even want anything in return.
3. Perhaps. Which task do you want me to do?
4. I've heared that you sell deliscous cakes. Another mob further down the road asked
    me if I could bring him one. I'd also like to have the receipe of said cake.
5. No, sorry. I've got no time. Perhaps later.
6. I'm going to kill you and rob all your items!
----------------------------------------------------------------------------------------------------------------------------

**Comment by Sokomine** [comment]
Buttons are far too small for the required text and do not work well with multi-line texts. There might be even longer options than in the example above. Buttons also center text and/or cut it off if no \n are inserted manually.

**Comment by rubenwardy** [comment]
> Buttons are far too small for the required text

Buttons are as big as you make them

> Do not work well with multi-line texts  --- Buttons also center text and/or cut it off if no \n are inserted manually.

These are the actual problems here

**Comment by kilbith** [comment]
> Highlight text on mouseover

Possible in https://github.com/minetest/minetest/pull/8680

**Comment by v-rob** [comment]
Highlights are also possible with things like buttons via https://github.com/minetest/minetest/pull/8679, although you would have to manually implement them yourself.

**Comment by Sokomine** [comment]
Highlighting is a nice extra. What's really needed is a way to display text in such a way that the reader doesn't close the formspec immediately because he/she thinks it's utterly broken. But I'm glad that it's beeing worked on even in two diffrent PR!

@kilbith: You're wrong in one way: Your #8680 does not only solve the highlight problem - it also solves most of the text presentation problems mentionned here :-). Not all as there's no element comparable to table[] or the <ol> HTML tag for numbering the answers - but that is a minor issue. Chatting with mobs can be implemented without the numbers in front of the choices.

If #8680 gets merged, the multi-line part of this problem regarding textlist[] can be considered solved. That element can then be replaced with the new features in multi-line situations.

table[] is a diffrent element that is not handled by #8680 (yet?).

Please get #8680 ready and merged and consider this issue as something that might still be of intrest later on but has a much lower priority than #8680.
