### ISSUE TITLE
Allow overriding the dig times of 'dig_immediate' from Lua

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8721]
See https://github.com/minetest/minetest_game/issues/2427 for discussion.

https://github.com/minetest/minetest/blob/bba4563d89b6708d75a4053c69873dff0d747538/src/tool.cpp#L175-L183

The current behaviour means that the digging of 'dig_immediate = 2' nodes is slow in creative mode. We should be able to add `dig_immediate = caps` to the MTG creative mod here https://github.com/minetest/minetest_game/blob/c32b8adaa36353f9b21d896e93cce732e26cf0a0/mods/creative/init.lua#L56

**Comment by Linuxdirk** [comment]
Digging nodes in creative should always be instant for all nodes.

**Comment by sfan5** [comment]
I agree with that, consistent creative dig times is something I'd like to see in minetest_game.
But the implementation of that is up to the subgames.

**Comment by paramat** [comment]
PR #8723
