### ISSUE TITLE
Some attachments broken after recent commit

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8734]
##### Minetest version
```
Any after #8701 was merged
```

##### Summary
In the commit directly before #8701 attachments in the death_timer mod work fine.
After merging #8701 into my client the attachments stop working, and I can move around while dead

##### Steps to reproduce
Not sure yet

**Comment by LoneWolfHT** [comment]
It looks like a mod on my server is causing this bug to appear (Only with the #801 commit client though). (`lonewolf.minetest.land : 55555`)
I'll look around the code a little. But there's quite a lot I'd have to scan through

**Comment by SmallJoker** [comment]
Local tests to reproduce this issue yet failed. Needs further tracking down on this issue from @LoneWolfHT or another user who's affected by a similar problem.

**Comment by LoneWolfHT** [comment]
I think we can just close this issue until someone else has it. I've fiddled around and haven't been able to find the mod that causes this
