### ISSUE TITLE
Define and document minimum and recommended requirements

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#8736]
In order to make performance testing easier, it would be good to define a minimum and a few recommended requirements. For example:

* Minimum (20+ FPS, shaders off, opaque leaves, opaque water, range-30)
* Recommended Midtier (50+ FPS, shaders on, fancy leaves, normal water, range-100)
* Recommended Hightier (60+ FPS, shaders on, fancy waving leaves, normal water, range-200, future fancy shaders)

It would also be good to provide configurations for good performance on those tiers.

What hardware do you run Minetest on, and what FPS/stutters do you get with the above settings?

**Comment by rubenwardy** [comment]
> U: Intel® Core™ i7-8550U Processor @ 1.8 - 4.0GHz> GPU: Intel® UHD Graphics 620> RAM: 16GB RAM, 512GB SSD> > High tier:

**Comment by style-nine** [comment]
CPU: AMD FX(tm)-6300 Six-Core
Video: GeForce GTX 1050
OS: Ubuntu 18.04.2 LTS

default config:

leaves_style = simple
screen_w = 1600
screen_h = 900
fov = 90
viewing_range = 160
enable_shaders = true

With shaders disabled, you can bump the viewing_range to 240 and get the same performance (around 50 fps in difficult terrain when flying around in creative).

**Comment by SmallJoker** [comment]
Suggestions to get more comparable results:
 * Demo map which contains buildings and is at least 200x200m big
 * Fixed spawn point (preferably singleplayer)
 * Fixed pitch and yaw
 * Pre-defined minimalistic minetest.conf files (low, med, high) to use without any modification

**Comment by raymoo** [comment]
Tried on my laptop

Low: 60 FPS
Med: 28~30 FPS
High: 13~14 FPS
I tested against flying above a jungle and looking toward the horizon.

OS: Debian testing
CPU: Intel(R) Core(TM) i7-3610QM (Ivybridge, laptop)
GPU: Integrated graphics with above

**Comment by AKryukov92** [comment]
Is this about client requirements or about server ones?
Should we test config in which 1 client connects to dedicated server via LAN?
I think singleplayer MT will be slower than this setup. Single hardware for running map logic and rendering gui will perform worse than hardware only for rendering gui. Thats why these scenarios should be separate.

**Comment by Linuxdirk** [comment]
For servers we ideally should have [something like this](http://canihostaminecraftserver.com/). So we need numbers on how much one connected players "cost" so we can calculate the answer. We should also have a CPU field because MT does a lot on CPU.
