### ISSUE TITLE
Non qwerty 1234 bar item handed switch on linux distros

### ISSUE THREAD

**Issue by Eluminae** [minetest/minetest#8737]
Hello there !

## Problem

I got a problem with my azerty keyboards on linux distros. To switch my handed item I have to shift+key.
On another by similar game, there is still a possibility to re-bind thoses keybinds to &, é, ", etc... but not on minetest. My only solution for now is to switch my keyboard layout but it cause difficulties on chats and commands.

## Solutions

Handle cleanly the azerty keyboards on linux distros to bind '1234...' on '&é"'...'

## Alternatives

Allow to rebinds thoses (on mimetest.conf if necessary)

Thanks a lot for replies !
Kiss

**Comment by SmallJoker** [comment]
Refer to Irrlicht. Cannot be fixed within Minetest. See #302.

**Comment by Eluminae** [comment]
Minetest allow to rebind zqsd but not 1234. Why ? Why can't I bind them on aerf instead ?

**Comment by SmallJoker** [comment]
If you want to rebind the inventory slot changing keys, you can modify this setting:
https://github.com/minetest/minetest/blob/3ad9a8f3a978b41a88ebf8a88690ad658cd132c7/minetest.conf.example#L274-L277
