### ISSUE TITLE
Server::UpdateCrafting causes lags on servers with many craft recipes

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#8738]
##### Minetest version

```
5.1.0-dev
```

##### OS / Hardware

Operating system:
CPU: Intel Xeon

GPU model:
OpenGL version:

##### Summary

If you call player:set_wielded_item() and have at least 1 item in your craft grid it will take 20-100 ms to execute on servers with lots of craft recipes registered, because it also calls Server::UpdateCrafting which loops through every single craft recipe to see if it the current arrangement of items matches an existing recipe.
##### Steps to reproduce

Call player:set_wielded_item() with at least 1 item in your craft grid and lots of craft recipes registered and measure its execution time.

Then leave the craft grid empty and measure the time again. It will be less than 1 ms now.

**Comment by DS-Minetest** [comment]
I can reproduce (using this: https://gist.github.com/DS-Minetest/acc13c4399fbd08b4ba8c50ea2596092).

**Comment by IhrFussel** [comment]
Looks like false alarm at least in 5.1.0-dev

It is possible that this bug only exists in 0.4.17.1 or only on my server.

**Comment by SmallJoker** [comment]
5.1.0-dev:
```
dt1: 182, dtn: 39.153
dt1: 90, dtn: 36.538
dt1: 76, dtn: 35.945
dt1: 55, dtn: 37.213
```

0.4.17.1:
```
dt1: 70, dtn: 27.371
dt1: 74, dtn: 33.065
dt1: 71, dtn: 30.411
```
0.4.17-dev: (stable build no longer works due to library updates)
```
dt1: 63, dtn: 28.818
dt1: 160, dtn: 28.494
dt1: 57, dtn: 26.352
dt1: 84, dtn: 35.613
```

There's really no connection between `set_wielded_item` and your speed loss. Check the size of the player's inventory to ensure it's not bloated with metadata-heavy items.

**Comment by IhrFussel** [comment]
The actual issue is the amount of craft recipes when having at least 1 item in the craft grid it seems so I updated the title and description.

**Comment by IhrFussel** [comment]
Not reproducible in latest master, so closing.
