### ISSUE TITLE
Low main menu fps

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#8739]
## Problem

The main menu is juddery. Try for example to grab a scrollbar scroller and move it.
I'm always frustrated when I see this.
If you grab and move a scrollbar scroller inside the game, it's moves smoothly.
I guess, this is because the main menu fps is low.

## Solutions

The main menu fps should be increased when minetest is selected. (Having a minetest main menu window in the background shouldn't be heavy.)

## Alternatives

While this problem doesn't feel good, which is problematic for a game, it doesn't prevent you from playing or anything. So it could be kept as is.

## Additional context

These lines might be related:
https://github.com/minetest/minetest/blob/3ad9a8f3a978b41a88ebf8a88690ad658cd132c7/src/client/clientlauncher.cpp#L549-L550

**Comment by Calinou** [comment]
FPS while in the main menu is also limited by `pause_fps_max`.

**Comment by style-nine** [comment]
Is that because of cloudPostProcess? Or is there somewhere else that it does that?

**Comment by rubenwardy** [comment]
> However, we need a way to check whether the window is focused using Irrlicht.

This is easy: `!device->isWindowFocused()`

already used in MT: https://github.com/minetest/minetest/blob/master/src/client/game.cpp#L1127

**Comment by paramat** [comment]
> We should make Minetest only lower the FPS cap when the window is unfocused

+1

**Comment by Calinou** [comment]
@paramat This is done in https://github.com/minetest/minetest/pull/8837 already. Should it be merged?
