### ISSUE TITLE
Add a modernised Mapgen v6?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8745]
I would be ok with coding, adding and maintaining this, but am looking for potential support from other core devs. Adding a new mapgen is a big commitment so this needs careful consideration.
Feedback shows that mgv6 terrain is quite popular, and there are quite a lot of questions about why biome / decoration / Biome API feature isn't present in mgv6.

How similar?
--

This would be similar to all the other moden mapgens in that it would use the Biome API and would have the same biomes.
Terrain shape would be mostly unchanged, however there would be no 'mudflow' that erodes and shifts biome suface material around.
Caves would be almost identical, the amount of caves in deserts would not be reduced by a factor of 3 as in mgv6.
The dungeon types hardcoded to mgv6 biomes would have to change. I can keep the 2 dungeon structure types unchanged but they would appear by chance in all biomes.

Possible future step
--
If altering the map_meta.txt of a mgv6 world to mgv61 is not too disruptive (i would need to test), those with mgv6 worlds could possibly have those new areas in those worlds created by mgv61 instead, as terrain would be continuous (but biomes would not be, straight-edged biomes would appear).
Then later we would be able to remove mgv6 code from engine and game, which is a pain in terms of mapgen code.

**Comment by benrob0329** [comment]
I'm going to ask this question, so please excuse me if its too off topic but I feel as though mapgens should be defined by games in a way that is more universal. This method of adding more and more mapgens to the engine will make maintaining the mapgen's codebase harder and harder over time.

Is it possible for the C++ biome API to be exposed to Lua in a way that is performant enough for mods and games to define new mapgens, and separate those from the underlying mapgens? Perhaps dedicated mapgen mods which run separately from the normal Lua code for performance reasons and defines the generic structure and terrain of the world?

**Comment by paramat** [comment]
Related: There is an issue somewhere for allowing C++ 'core mapgen modules' so that C++ mapgens can be shared and plugged in somehow. We could possibly allow games to provide such C++ mapgen modules.

The C++ Biome API is already exposed to Lua, that's exactly what it is, C++ code controlled by Lua, for performance reasons. This doesn't allow mapgens to be separated from the engine because any Lua mapgen has lower performance for many other reasons, and causes server lag because the Lua code runs in the main server thread.

There's also an issue somewhere for allowing Lua mapgens to run in a separate thread to avoid the server lag problems, however it is very non-trivial, even hmmmm didn't manage to figure it out.

**Comment by paramat** [comment]
Core devs please consider, i think this is potentially a very good idea.

**Comment by TumeniNodes** [comment]
Do you mean to use V61, or V6.1? dumb question I know but I'm just curious.
This would be nice to see, being that V6 is such an odd duck.

I'm still waiting on that kick-ass V8 though ;P

**Comment by paramat** [comment]
I mean to suggest v6.1, as in following from v6.0, but the point character will cause problems, so i removed it to form v61. Just a name suggestion, not sure what to call it.

**Comment by ClobberXD** [comment]
v61 is confusing. Why would using `v6.1` cause problems?

**Comment by paramat** [comment]
Meh ... no core dev response (again). I am also very unsure about this. I expect we could not replace mgv6, and it is a very big commitment to add a mapgen. Seems best to not do this, for now at least.

**Comment by sirrobzeroone** [comment]
I've just had to workaround some dependency issues for current mgv6 so it can be supported and still work in a more mod limited space without sending a pile of errors to log. Anything not mgv6 is really easy to cut back and back until you end up with stone,water, river_water as your only valid nodes. So i found I can keep cutting nodes back to those base 3 without needing to really check any other mods have loaded say for example a tree mod.....

mgv6, I have to wait for all potential mods with node/decoration "bits" in them to load or not then check what mods may or may not have loaded then alias out the missing parts with air (trees), plain_node (stairs) and so on. 

Supporting mgv6 like this then puts a slight pressure on the non-mgv6 mapgen as those seem to like decorations loaded after biomes, and things like "trees" are squarely in decoration territory....easy test in MTG load any non-mgv6 mapgen but load the decorations first ie change the order at the end of mapgen.lua.....you'll have snow on stone in the savanna....that took me while to figure out....

Just wanted to provide an example above of were the hardcoded nature of mgv6 actually causes problems for non-mgv6 mapgens if you try to support both without generating errors/odd behaviour and happen to say not include the node ("mapgen_tree").   

how did I stumble on the above, I started tearing MTG - "default" apart...should say I've torn it down to base components (still working on some of the surrounding mods though) and  that's when i encountered the above.....I have a workaround but it's not very nice and results in what can be seen as strange mod load order. Were as if mgv6 adhered to non-mgv6 mapgen rules I could basically just have mapgen >> dependant on basic_env (basically stone, ore, dirt, sand, water).

Not that it means much but +1 for paramat to do this work and please don't close this 👍
