### ISSUE TITLE
Make settingtypes.txt great (again!)

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8747]
## Problem

`settingtypes.txt` contains:

- Setting name
- Default value
- Lower and upper limits (if applicable).

Only the mainmenu cares about this file and the rest of the code-base doesn't even acknowledge the existence of this file. This has resulted in:

- A separate file `defaultsettings.cpp`, that specifies the default for each setting.
- Tons of rangelims across the code-base that limit the setting only when retrieving the value in that particular scope/function.

To add a setting, one would have to modify both `settingtypes.txt` and `defaultsettings.cpp`, _and_ rangelim this value wherever it's used (if applicable), even though all these are already defined in `settingtypes.txt`. What's worse is that there's always the danger of these defaults and/or limits going out of sync with the (arguably) "original" copy in `settingtypes.txt`.

## Solution

- All settings should automatically be parsed from `minetest.conf` (or the defaults from `settingtypes.txt`) at startup and (also upon modification of individual settings), and loaded into the `Settings` object.
- All settings should automatically be `rangelim`'ed with the appropriate upper and lower bounds from `settingtypes.txt`, while parsing.

Once implemented, we could happily do away with `defaultsettings.cpp` and those hundreds of lonely rangelims in the code-base.

## Alternatives

Close this issue; rest in peace :D

**Comment by ClobberXD** [comment]
I'm willing to implement this.

**Comment by MoNTE48** [comment]
+1! But now we have alternative config for Android...

**Comment by jastevenson303** [comment]
C'mon

**Comment by ClobberXD** [comment]
> But now we have alternative config for Android...

I didn't know that; interesting. But it's certainly possible to add a simple `#ifdef __ANDROID__` and parse the alternate config file instead - that's not a problem. But thanks for the heads-up. :)

**Comment by DS-Minetest** [comment]
Related: #6711

There are problems with the rangelim. Breaking the limits of some settings (like the zoom fov) can be considered as cheating. Currently this is only possible by re-compiling.

**Comment by ClobberXD** [comment]
> Breaking the limits of some settings (like the zoom fov) can be considered as cheating. Currently this is only possible by re-compiling.

I'm sorry, but I don't understand what you're saying. This issue has nothing to do with cheating.

**Comment by LoneWolfHT** [comment]
Couldn't players just modify settingtypes.txt? Or am I missing something?

**Comment by SmallJoker** [comment]
Relevant: #6728

**Comment by DS-Minetest** [comment]
> > Breaking the limits of some settings (like the zoom fov) can be considered as cheating. Currently this is only possible by re-compiling.
> 
> I'm sorry, but I don't understand what you're saying. This issue has nothing to do with cheating.

>- All settings should automatically be `rangelim`'ed with the appropriate upper and lower bounds from `settingtypes.txt`, while parsing.

> Couldn't players just modify settingtypes.txt? Or am I missing something?

That's what I mean. Changing something in `settingtypes.txt` and restarting minetest is much easier than recompiling.

(Would it actually be possible to get the limits in compile time?)

What would be fine is if the limits were applied additionally, this would be especially helpful for mod settings.

(Maybe a dev-wiki article would be helpful :thinking:.)

**Comment by MoNTE48** [comment]
Is anything stopping make hardcode limits from unsafe parameters?

**Comment by paramat** [comment]
> This has resulted in:
    Tons of rangelims across the code-base 

No, the rangelims were there originally, the settings limits were added later as more casual settings menu limits.
> To add a setting, one would have to modify both settingtypes.txt and defaultsettings.cpp, and rangelim this value wherever it's used (if applicable),

This isn't a significant problem, just a couple of extra lines, and probably less of a problem than the workload, complexity and potential issues of your 'solution'
Also see below, the in-code rangelims are necessary anyway, so there's little benefit.
> All settings should automatically be parsed from minetest.conf (or the defaults from settingtypes.txt)

Not from .conf, only from settingtypes.txt, .conf is not as reliable.
> All settings should automatically be rangelim'ed with the appropriate upper and lower bounds from settingtypes.txt, while parsing.

I disagree, the in-code rangelims are there for extra security. Settings limits are more casual and easier to mess up accidently.

Overall i'm :-1: for the suggestion, a lot of work and risk for a non-problem

**Comment by paramat** [comment]
> Changing something in settingtypes.txt and restarting minetest is much easier than recompiling.

That's very good point.

**Comment by ClobberXD** [comment]
> Couldn't players just modify settingtypes.txt?

Ah right, I totally missed that part. Yes, this is a bad idea.
