### ISSUE TITLE
Possible denial of service attack (DoS)

### ISSUE THREAD

**Issue by thomasrudin** [minetest/minetest#8757]
##### Minetest version

```
5.0.1
```

##### OS / Hardware
Operating system: Linux
CPU: x86_64

##### Summary
This night i had several crashes over a time range of about 2 hours.
Every time before the server crashed (without warning) i had these lines in the logs:

```
minetest_1           | Duplicated seqnum 1 non matching packet detected:
minetest_1           | Old: seqnum: 00001 size: 0011, address: 37.228.235.x
minetest_1           | New: seqnum: 00001 size: 0025, address: 37.228.235.x
```

Sadly nothing in the debug logs or anything about that ip in the recent logs.
Output of `dmesg` showed lots of these too:

```
[582133.937849] ConnectionRecei[4399]: segfault at 8 ip 00005596f262da77 sp 00007fee8f7fce70 error 4 in minetestserver[5596f2523000+3d7000]
```

I blocked the IP with iptables but the underlying issue is still there, whatever it is.

##### Steps to reproduce
If i knew that i would have opened a PR instead.. :rofl:

**Comment by MoNTE48** [comment]
I can only suggest  that this is a test of a modified client. Obviously failing for the Minetest server...
If someone wanted to do DDOS on your server, he would hardly have used this strategy.  In fact, Minetest has many other vulnerabilities that can help it “go away” for a long time...

**Comment by HybridDog** [comment]
http://github.com/minetest/minetest/blob/master/src/network/connection.cpp#L341

**Comment by thomasrudin** [comment]
> [http://github.com/minetest/minetest/blob/8da35c22d1c8933090330b2f3c44b4cf2c6e6760/src/network/connection.cpp#L341](https://github.com/minetest/minetest/blob/8da35c22d1c8933090330b2f3c44b4cf2c6e6760/src/network/connection.cpp#L341)

Yeah, that _should_ get caught here: https://github.com/minetest/minetest/blob/8da35c22d1c8933090330b2f3c44b4cf2c6e6760/src/network/connectionthreads.cpp#L1343

**Comment by Parasitoid** [comment]
Hi! I have seen similar crash at different minetest server about 14 - 16 hours ago, and according to what admin of that server said, the log was very similar.

**Comment by red-001** [comment]
removing the throw isn't really a full solution, you should be disconnecting the misbehaving peer.

**Comment by Hume2** [comment]
I had the same issue 6 times.

**Comment by sfan5** [comment]
It would help if you used the information given by dmesg to identify the function that crashed.
Like this:
`addr2line -pfC -e /path/to/bin/minetestserver 0x00005596f262da77`
or if that doesn't work try with `0x4e1a77` instead

**Comment by thomasrudin** [comment]
> It would help if you used the information given by dmesg to identify the function that crashed.
> Like this:
> `addr2line -pfC -e /path/to/bin/minetestserver 0x00005596f262da77`
> or if that doesn't work try with `0x4e1a77` instead

Sadly it is not a debug build :disappointed: 

output of `addr2line`:
```
root@magellan:/home/thomas/mt_dos_dissect# addr2line -pfC -e minetestserver 0x00005596f262da77
?? ??:0
root@magellan:/home/thomas/mt_dos_dissect# addr2line -pfC -e minetestserver 0x4e1a77
?? ??:0
```

output with `gdb`:
```
(gdb) info symbol 0x00005596f262da77
No symbol matches 0x00005596f262da77.
(gdb) info symbol 0x4e1a77
No symbol matches 0x4e1a77.
```

Is there a big performance impact if mt runs with a debug build?

**Comment by sfan5** [comment]
Debug symbols/annotations (`-g`) do not cost anything, though to get more useful results you usually want to turn the optimization level down (e.g. `-O1`).

You will probably not even notice any performance difference when you run a build which uses `-DCMAKE_CXX_FLAGS="-g -O1"`

**Comment by thomasrudin** [comment]
I managed to get a packet capture from a recent connect attempt from the same host:
[dos_host_capture.pcap.gz](https://github.com/minetest/minetest/files/3504439/dos_host_capture.pcap.gz)

I have no idea if it was malicious or not, because i removed the `throw` from the failing line.
But the packets look "manually" generated: 5 seconds between initial peer-id exchange and INIT for example..

I'll try to recreate a manual testcase with those packets if i have some free time..

**Comment by sfan5** [comment]
The packet trace you posted does not show any duplicated reliable packets, so it would not have triggered the bug you initially reported.
There is something else interesting in it, however.
