### ISSUE TITLE
No Bin Folder?

### ISSUE THREAD

**Issue by devomaa** [minetest/minetest#8760]
##### Minetest version
 0.4.17.1
```

```

##### OS / Hardware

Operating system: Kubuntu (latest version, i forgot)
CPU:

GPU model:
OpenGL version:

##### Summary

When I to launch from misc/ the desktop file, it just fails cause no bin folder.
##### Steps to reproduce

I Downloaded it? and it happend first start

**Comment by sfan5** [comment]
The `bin` folder gets created when you compile Minetest. You're also not supposed to launch it from the bare desktop file.

**Comment by rubenwardy** [comment]
On Kubuntu, you should install Minetest like so:

```
sudo add-apt-repository ppa:minetestdevs/stable
sudo apt-get update
sudo apt install minetest
```

**Comment by devomaa** [comment]
Hey, I want to use the older version, so ican pass protocol 27?.
