### ISSUE TITLE
Infinite reach

### ISSUE THREAD

**Issue by jastevenson303** [minetest/minetest#8764]
##### Minetest version
```
Minetest 5.1.0-dev-8ffe9591 (Linux)
```

##### OS / Hardware

Operating system: debian 9.9
CPU: intel

GPU model:
OpenGL version:

##### Summary

I can dig nodes very far away in singleplayer with no extra privs and creative_mode=false.
##### Steps to reproduce

Start a game, dig a tree at the other end of the map.

**Comment by rubenwardy** [comment]
Already fixed https://github.com/minetest/minetest/commit/0c533dc4363747c8ccb4a0f519516cc8ae73d3fa
