### ISSUE TITLE
Doesn't set selection box to the entity even if it's defined.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8772]
Lua_api.txt shows about new property is selection_box that, as I understand, needed entity box to be visible, but there`s no even selection box:
![image](https://www.imageup.ru/img184/3447476/screenshot_20190809_233128.jpg)

**Comment by SmallJoker** [comment]
The car is too large. Try this:
`selectionbox = {-3, 0.0, -3, 3, 2.5, 3},`

**Comment by Andrey2470T** [comment]
Like it perfectly doesn`t have selection box somewhy. I checked inside the car, punching it and nearby.

**Comment by Andrey2470T** [comment]
And `pointable=true` parameter is also enabled :\

**Comment by paramat** [comment]
Please link to your code.

**Comment by Andrey2470T** [comment]
https://pastebin.com/1AgVwuj8

**Comment by paramat** [comment]
Hmmm i can't see any errors in the code.

**Comment by Andrey2470T** [comment]
Hmm... really strangely. I even enlarged in few times the selection box and nothing changed.

**Comment by Andrey2470T** [comment]
I`ve tested simple entity (not that used my API), just implemented `minetest.register_entity()`, it used to be same without selection box visible, regardless what I put even `pointable=true'. It means I can confirm this is an _exactly_ engine bug.

**Comment by SmallJoker** [comment]
Cannot reproduce. All entities show up their corresponding selection box. Please provide the entire mod, or preferably a minimal version where the same issue can be observed. The file you posted is not enough, maybe it's a problem with something else than the entity registration.

**Comment by Andrey2470T** [comment]
Mod source: https://github.com/Andrey2470T/entity_testing
Minimal version where the bug happens is 5.1.0-dev from https://github.com/ClobberXD/minetest/tree/fix_particlespawner_rotation

**Comment by SmallJoker** [comment]
![screenshot_20190811_205927](https://user-images.githubusercontent.com/1497498/62838346-05740680-bc7b-11e9-8e08-8dfe37f56adb.png)

Works fine here.

**Comment by ClobberXD** [comment]
Probably due to the camera offset bug beyond x/y/z >= 200?

**Comment by SmallJoker** [comment]
@ClobberXD 
1) The player is not attached in the top image
2) The camera offset shift bug affects attachment children only

**Comment by Andrey2470T** [comment]
Please open the issue as the problem is not solved yet. 

@SmallJoker did you really donwload that version of the engine and the mod and didn`t change anything in the code? Maybe do I need to edit the minetest.conf file selection boxes to be visible?

**Comment by SmallJoker** [comment]
@Andrey2470T Rename your minetest.conf file and let Minetest generate a new one. I used the most recent Minetest build and the code you put on GitHub.

**Comment by Andrey2470T** [comment]
But did you use the version of the engine from ClobberXD that I linked above to? And it appears my minetest.conf is just empty.

**Comment by ClobberXD** [comment]
> @ClobberXD
> 
> 1. The player is not attached in the top image
> 2. The camera offset shift bug affects attachment children only

Ah yes, I'll look into this in  a couple of days.
