### ISSUE TITLE
'make' runs into issue 

### ISSUE THREAD

**Issue by hannesa2** [minetest/minetest#8773]
checking out current master and run

```
cd build/android 
make
```

> libtool: link: ( cd ".libs" && rm -f "libiconv.la" && ln -s "../libiconv.la" "libiconv.la" )
> cp: .libs/libiconv.so: No such file or directory
> make[3]: *** [preloadable_libiconv.so] Error 1
> make[2]: *** [all] Error 2
> make[1]: *** [/Users/hannes/git/minetest/build/android/deps/libiconv//lib/.libs/libiconv.so] Error 1

Do you have any hint, how to solve this ?

**Comment by hannesa2** [comment]
"**Unconfirmed bug**" ? please do

```
git checkout master
cd build/android 
make
```

**Comment by Calinou** [comment]
@hannesa2 That label is automatically added when you create an issue with the ["bug report" template](https://github.com/minetest/minetest/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). It will be turned into `bug` if someone manages to reproduce it :slightly_smiling_face:

**Comment by hannesa2** [comment]
> ...It will be turned into **`Bug`** if someone manages to reproduce it 🙂

Is someone able to reproduce it ?
Please run this :

```
git checkout master
cd build/android 
make

```

**Comment by rubenwardy** [comment]
Please ensure that you've followed the steps documented in http://dev.minetest.net/Android

**Comment by hannesa2** [comment]
> Please ensure that you've followed the steps documented in http://dev.minetest.net/Android

I've Android installed. Even all other outdated mentioned in your link, but I see no relation to my error

> clang: warning: argument unused during compilation: '-mfpu=vfpv3' [-Wunused-command-line-argument]
> libtool: link: rm -fr  .libs/libiconv.a .libs/libiconv.la .libs/libiconv.lai
> libtool: link: ar cru .libs/libiconv.a  objects/iconv.o objects/localcharset.o objects/relocatable.o
> libtool: link: ranlib .libs/libiconv.a
> libtool: link: ( cd ".libs" && rm -f "libiconv.la" && ln -s "../libiconv.la" "libiconv.la" )
> cp: .libs/libiconv.so: No such file or directory
> make[3]: *** [preloadable_libiconv.so] Error 1
> make[2]: *** [all] Error 2
> make[1]: *** [/Users/hannes/git/minetest/build/android/deps/libiconv//lib/.libs/libiconv.so] Error 1
> make: *** [debug] Error 2


`iconv` is downloaded, but no `*.so` (only a `*.a`) is compiled or included

Is someone able to reproduce it ?

# Yes/No ?

**Comment by sfan5** [comment]
Try appending `--enable-shared` before the || on this line:
https://github.com/minetest/minetest/blob/f3fd85aafb3f9c0d38571cb6f6addad0bc7fea8f/build/android/Makefile#L482

**Comment by hannesa2** [comment]
unfortunately this line
`./configure --host=${TARGET_HOST} --enable-shared || exit 1;`
doesn't solve the issue

**Comment by MoNTE48** [comment]
This PR https://github.com/minetest/minetest/pull/9066 solves all possible (including this one) problems.

**Comment by MoNTE48** [comment]
Can be closed
