### ISSUE TITLE
Windows build cannot load fonts

### ISSUE THREAD

**Issue by JasonGoemaat** [minetest/minetest#8777]
##### Minetest version

```
5.1.0-dev
```

##### OS / Hardware

Operating system: Windows 10
CPU: x64

GPU model:
OpenGL version:

##### Summary

Using the build instructions for vcpkg the game fails to load.  Debugging I see that the right path to the font is sent to `CFileSystem::createAndOpenFile()`, but once I step into that method it treats the parameter as unicode and I see a mangled unicode representation of the filename.  See [my so post](https://stackoverflow.com/questions/57445331/windows-dll-compiled-using-vcpkg-different-character-sizes) for a description.  I think it may have to do with a vcpkg [pull request](https://github.com/microsoft/vcpkg/pull/7354) that happened on 7/20 applying a patch for unicode on windows.

##### Steps to reproduce

Follow instructions in the readme to build on windows with a clean vcpkg install, but with Debug instead of Release (release failed also but I couldn't find the error):

    cmake . -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=D:/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_GETTEXT=0 -DENABLE_CURSES=0
    cmake --build . --config Debug

**Comment by SmallJoker** [comment]
Please provide any relevant error messages and debug lines (see `debug.txt` from Minetest).

**Comment by adrido** [comment]
Can confirm it.
```
FontEngine: failed to load: ...\minetest\bin\RelWithDebInfo\..\..\fonts\Arimo-Regular.ttf, trying to fall back to fallback font
FontEngine: failed to load freetype font: ...\minetest\bin\RelWithDebInfo\..\..\fonts\DroidSansFallbackFull.ttf
minetest can not continue without a valid font. Please correct the 'font_path' setting or install the font file in the proper location
```
Reverting https://github.com/microsoft/vcpkg/commit/22be764ecc302d93371b8f7a05faf0fc4e39fa31 and it will work again.

**Comment by SmallJoker** [comment]
Outdated branch. Please re-test after https://github.com/minetest/minetest/commit/233cb86e8#diff-989aa08e44191d9ee2fb879053351d9cL366

**Comment by adrido** [comment]
Same issue, just little different error messages.

The solution would either to revert that said commit from vcpkg or make minetest use the unicode (or ASCII if converting to wchar is not possible) Win32 calls. It should only affect a few lines inside porting.cpp and another #define.

**Comment by sfan5** [comment]
If you fixed the issue the way you described, wouldn't that break when linked to an Irrlicht not compiled with Unicode paths?

**Comment by adrido** [comment]
Not necessarily. There could be a cmake option thats off by default, but on if the vcpkg toolchain is detected. 

But as Windows related PRs takes ages until they get merged, the fastest way would be to fix it on the vcpkg side.

**Comment by SmallJoker** [comment]
@adrido The project to patch depends on the official documentation of the affected calls. If Minetest does not provide a valid encoding, it's to be fixed here. As long it does not break current builds it'll probably go through as "Looks good to me, seems tested" or similar.

**Comment by adrido** [comment]
Fixed. You can close this now.

**Comment by SmallJoker** [comment]
Thanks. The issue is closed ~now~ already.
