### ISSUE TITLE
Commands don`t write an info in the chat, although they should write indeed.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8779]
##### Minetest version

```
5.1.0-dev
```

It happens with /mods, /admin, /grant me|all. They don`t show any info in the chat, although they`re assigned to do it. So, /mods doesn`t list the mods that enabled, /admin doesn`t show an admin, /grant me|all doesn`t report about privs were granted to the player.

**Comment by SmallJoker** [comment]
Does flipping a page (tabs or buttons) do anything in your inventory?
Yes:
 1) I cannot reproduce your issue. Remove `builtin` and unzip/re-download it again.
 2) Still does not work? Get older Minetest versions and find the best working one.
 3) Stop reading further from here.

No:
 1) Minetest hangs. Disable heavy mods, especially map generating ones.
 2) Start a vanilla minetest_game without any additional mods


Do the commands work now?
Yes:
 * Great. Find the mod that causes this issue by re-enabling mods partially until it stops working.
No:
 * Get older Minetest versions and find the best working one.

**Comment by paramat** [comment]
Tested, commands appear in chat for me when using MTG only.

**Comment by SmallJoker** [comment]
Cannot reproduce. Fix your system or ask in the forums (or chat) to help you with that.
