### ISSUE TITLE
Support newer versions of Direct3D

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#8786]
## Problem

Minetest currently supports Direct3D 8.0/9.0. 
Supporting newer versions (such as v12) would be nice.

I currently use Direct3D because of a problem with OpenGL.
Direct3D works very nice, but sometimes...the game becomes (a bit) slow.

## Solutions

- Update the driver to the latest version (supporting older versions).

**Comment by Calinou** [comment]
Irrlicht doesn't support Direct3D versions newer than 9.0 according to its [features page](http://irrlicht.sourceforge.net/?page_id=45), so this is basically impossible.

Besides, the focus of development is OpenGL, as it also works well on Windows on most recent hardware.

**Comment by Panquesito7** [comment]
> >I currently use Direct3D because of a problem with OpenGL.
>
> Which issue are you encountering? Also, which graphics card and Windows version are you using?

My OpenGL downgraded, so, that's why I opened this issue, if it was possible to support newer versions.
I am using Windows 10, with Intel graphics.

**Comment by SmallJoker** [comment]
This is going offtopic but I'd like to provide some basic troubleshooting:

>My OpenGL downgraded

If it's version <= 1.4 then you're probably using a Windows dummy driver. Find out the precise model, use additional tools if Windows does not list the PCIe entries. Even integrated graphics use the PCIe bus.

Remove the old driver (Device Manager) and install the new one. Reboot & recheck. Minetest will run just fine on hardware from the last decade or even more, if the manufacturers don't remove the driver from the packages.
