### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by pangeneral** [minetest/minetest#8787]
##### Minetest version
5.*, Android build

##### Summary
According to our research, there are misuses about the following AsyncTask class:
`net.minetest.minetest.MinetestAssetCopy.copyAssetTask`

The problems are:
1. `copyAssetTask` is an inner class of `MinetestAssetCopy`, which means it holds strong reference the Activity, which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish;
2. The instance of `copyAssetTask` are not cancelled before the Activity is destroyed, which can lead to the wrong invocation of onPostExecute
3. The `doInBackground()` did not check the status of AsyncTask. 

I think we can make following changes to fix the misuse problems:
1. `copyAssetTask` should be a static inner class.
2. `m_AssetCopy`, the instance of `copyAssetTask` should invoke `cancel()` in the `onDestroy()` method of `MinetestAssetCopy` if it is not null
3. In the loop of `doInBackground()` method, check whether AsyncTask is cancelled via `isCancelled()`. If current AsyncTask is cancelled, jump out of the loop.

These are my suggestions above, thank you.

EDIT by SmallJoker: Fix code tags

**Comment by SmallJoker** [comment]
There are a few people around who are developing in that area, but with such precise ideas it would be great if you could propose a PR to fix this issue.

**Comment by SmallJoker** [comment]
#8799 merged
