### ISSUE TITLE
Warning in builtin "Assignment to undeclared global "_" inside a function"

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8794]
I'm on commit bf22184d6e16f21b9001322aad1bf8f6dbaa372b
`WARNING[Main]: Assignment to undeclared global "_" inside a function at ...inetest/bin/../builtin/mainmenu/dlg_create_world.lua:29.`
Suspect 8e757859d6a6bf6482480904e8485e9344e567ab
Occurs when creating a new world.

**Comment by rubenwardy** [comment]
In the time it took you to make this issue, you could have already fixed it

**Comment by sfan5** [comment]
It's not actually that simple.

`local _, gameidx = pkgmgr.find_by_gameid(gameid)` is not the correct solution
should the `local _` be inside the if? outside of it?

**Comment by paramat** [comment]
=) i was very busy working on a PR when the warning popped up.

**Comment by DS-Minetest** [comment]
PR: #8798
Ugh, hopefully this won't end in nit-picking discussions.
