### ISSUE TITLE
Useful add_player_velocity with horizontal speed higher than walk speed

### ISSUE THREAD

**Issue by raymoo** [minetest/minetest#8796]
## Problem

According to https://github.com/minetest/minetest/pull/8685/files#r313371048, `add_player_velocity` can't make the player move much faster than walk speed. For example, standing next to an explosion can't send you flying a block away (horizontally). Currently knockback is sufficient to juice up punches of reasonable force, but not sufficient for launching the player in reaction to things like explosions, enemies that punch really hard, or some kind of force wave attack.

## Solutions

Make player speed not limited by walk speed. This might mean keeping track of "knockback velocity" separately from walking velocity, or just changing the movement code so that speed decays down to walking speed instead of being clipped.

On the anti-cheat side, there may need to be some tracking of the current possible magnitude of knockback, in order to avoid unintended triggering of anticheat when knockback makes the player move quickly.

**Comment by sfan5** [comment]
> According to [...] add_player_velocity can't make the player move much faster than walk speed.

I misread that, why would you ask a question whether it <i>cannot</i> do that?
What I meant to say is that you <b>can</b> use add_player_velocity to make the player move faster than walk speed.

> Make player speed not limited by walk speed.

This is sort of an unfortunate wording. What is normalized at each step is the target speed, which causes that you can't let the player "fly" away at high speed <i>while</i> retaining normal controllability with the WASD keys.
Perhaps this is expected and doesn't even need a mention. I don't know.

> On the anti-cheat side, there may need to be some tracking of the current possible magnitude of knockback, [...]

The anticheat already does this.

**Comment by sfan5** [comment]
Finally, here's a demonstration:
![temp](https://user-images.githubusercontent.com/1042418/63016019-d2a45b00-be92-11e9-9283-389c42fa574d.gif)

**Comment by raymoo** [comment]
Thanks for the clarification.
