### ISSUE TITLE
Builds installation via the game menu.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8797]
There`s ContentDB in the menu where everybody can install mod/texture_pack/game, but why is there no similar installer of builds/engine versions straight in the game menu? It would also get rid of a need, firstly, to download/unpack from the git repo. Secondly, it could also compile the code source and enable necessary libs itself what also requires not a little time, if do it manually. Then it will delete the current game engine, save user content (mods, texture packs and etc) and transfer that to the installed one and open for the user new minetest app. Possible to make such feature?

That is, steps of automatical installation will be next:
1. Download the requested version of build from github.com/minetest/minetest, "master" branch.
2. Enable necessary libraries before compiling or pass if they are.
3. Automatically implement `cmake . -DRUN_IN_PLACE=1`, then 'make -j 4' cmds.
4. Awaiting when the compiling is finished.
5. If the compiling is finished, save in the memory mods, texture packs, games that are available to the user.
6. Delete the current game engine and open to the user new one.

**Comment by DS-Minetest** [comment]
As minetest itself is a program that will, for normal players, be installed systemwide, the os should keep it up to date. An example for this is the use of the minetest ppa.

**Comment by SmallJoker** [comment]
Relevant controversial PR #7629

**Comment by sfan5** [comment]
:-1: Adding functionality to download or even <i>compile</i> the engine from source is widely out of scope.

Compiling is also extremely irrelevant for Android and Windows where respectively it's impossible to install compiler and required libraries <i>or</i> 99.99% of users will not have have them installed.

**Comment by paramat** [comment]
:-1:

**Comment by Andrey2470T** [comment]
Why is it impossible to install compiler and libraries? I say the program will install itself required compiler and libraries. Why impossible?

**Comment by TumeniNodes** [comment]
I removed my thumbs up as I was using the pocket app for github at the time I read this, sorry.
I really should not use that app anymore
