### ISSUE TITLE
admin config not recognized ?

### ISSUE THREAD

**Issue by digitalbox94** [minetest/minetest#8803]
##### Minetest version
"Minetest 5.0.1"

##### OS / Hardware
CPU: Docker

##### Summary
When running the server, the name = <user> is not recognized for admin right. Indeed trying to change /time with <user> is raising a privilege error on the user.
On version 0.4.6 of the server, the name is correctly recognized.

##### Steps to reproduce
In the config file, set name = user. Then connect to the server with user and type "/time 9:00". A privilege error is raised

**Comment by SmallJoker** [comment]
`/grantme all`

**Comment by digitalbox94** [comment]
/grantme all
--> Your privileges are insufficient
