### ISSUE TITLE
Unable to chat_send_all() during newplayer callback due to conflicting locks.

### ISSUE THREAD

**Issue by shacknetisp** [minetest/minetest#8807]
Simple test function:
```lua
minetest.register_on_newplayer(function(player)
    minetest.chat_send_all("You should see this.")
end)
```

This will freeze the server since the clients lock is locked all through https://github.com/minetest/minetest/blob/d7c10b66d39adb330612da0da6d9c8ed993fe588/src/server.cpp#L1017-L1028 but is also attempted in https://github.com/minetest/minetest/blob/d7c10b66d39adb330612da0da6d9c8ed993fe588/src/clientiface.cpp#L725-L737

**Comment by sfan5** [comment]
Should probably just be changed to a recursive lock.

**Comment by SmallJoker** [comment]
Same issue as in #8648, just a different function.
Maybe related: #8666
