### ISSUE TITLE
Italian locale file (filename.it.tr) not being loaded

### ISSUE THREAD

**Issue by h4ml3t** [minetest/minetest#8809]
##### Minetest version
```
5.0.1
```

##### OS / Hardware
Operating system: Debian 9
CPU: Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (1,60GHz)

##### Summary
The engine does not use Italian (filename.it.tr) files, while using other languages' files.

##### Steps to reproduce
0 - set Minetest's language to Italian, minetest.conf -> language = it
1 - download and install MineClone 2
2 - open /minetest/games/mineclone2/mods/HUD/mcl_inventory/locale/
3 - duplicate template.txt
4 - rename the duplicate as mcl_inventory.it.tr
5 - edit mcl_inventory.it.tr setting: Recipe book=Italian string
6 - save and close the locale file
7 - run Minetest, start a new MineClone 2 game
8 - while ingame open the Inventory, hover the mouse on the Recipe Book

Doing 8 while "language = it" shows the English tooltip; while "language = de" or "language = fr" it shows the German and French tooltips.

Forum's thread: [[link](https://forum.minetest.net/viewtopic.php?f=6&t=23096)]

Screenshot:
![i18n_bug](https://user-images.githubusercontent.com/54187342/63190946-a42ba900-c067-11e9-8c36-b7b4ef58ed2e.jpg)

**Comment by SmallJoker** [comment]
The magic translation string is correct in 5.1-dev. Are you sure your translation files are up to date?
``
#: src/network/clientpackethandler.cpp
msgid "LANG_CODE"
msgstr "it"
```

**Comment by h4ml3t** [comment]
> The magic translation string is correct in 5.1-dev. Are you sure your translation files are up to date?

I am using v5.0.1
I have created the translation file today.

**Comment by SmallJoker** [comment]
Works in 5.1-dev.

![grafik](https://user-images.githubusercontent.com/1497498/63209923-69695580-c0e7-11e9-8c52-5b1d15e681f9.png)

![grafik](https://user-images.githubusercontent.com/1497498/63209942-c49b4800-c0e7-11e9-9c89-bb56839317bb.png)

Try this locale file:
[minetest.mo.zip](https://github.com/minetest/minetest/files/3511894/minetest.mo.zip)

**Comment by h4ml3t** [comment]
> Works in 5.1-dev.
> Try this locale file:
> [minetest.mo.zip](https://github.com/minetest/minetest/files/3511894/minetest.mo.zip)

I've tried your locale file, it changed the Minetest engines' locale, but the mod locale still does not work.

**Comment by SmallJoker** [comment]
Does the issue persist on 5.1-dev for you? I don't think there was a change in that code but it's worth a try.

**Comment by h4ml3t** [comment]
> Does the issue persist on 5.1-dev for you? I don't think there was a change in that code but it's worth a try.

I've just compiled it, the issue persists.
If I set language = de, it works correctly; if I set language = it, it uses the English description.

**Comment by SmallJoker** [comment]
Is any other language affected? This seems to be your main language, so those translations should also load if `language` is not specified in `minetest.conf`.
What happens if you remove setting line from your configuration?

**Comment by h4ml3t** [comment]
> Is any other language affected? This seems to be your main language, so those translations should also load if `language` is not specified in `minetest.conf`.

If I do not specify "language" in "minetest.conf" the engine's GUI is in Italian.
I haven't checked other languages, but I will do.

> What happens if you remove setting line from your configuration? Try to narrow down the issue as close as possible. How about translations of other mods? Using vanilla MTG and one translated mod?

I will test using MT v5.0.1, MTG v5.0.1 (on Windows, for being double sure that it's not due to some Linux glitch) and a single mod; i.e. a mod adding a node that when punched sends a string to the player.
I will let you know, and I will attach the test mod's zip.

Thank you for your time and help so far. :)

**Comment by h4ml3t** [comment]
> Try to narrow down the issue as close as possible. How about translations of other mods? Using vanilla MTG and one translated mod?

I have created a tester, MT v5.0.1 and MTG v5.0.1 are working as expected.
The tester is available here: [[link](https://forum.minetest.net/viewtopic.php?f=6&t=23096&p=354731#p354825)]

Thank you again. :)

**Comment by h4ml3t** [comment]
Eventually I have discovered the reason of the issue, it is due to Weblate's updated italian files.
If you use the MT's bundled locale the tester will work as expected.
But if you use Weblate's [.po](https://hosted.weblate.org/download/minetest/minetest/it/?format=po) or [.mo](https://hosted.weblate.org/download/minetest/minetest/it/?format=mo) the locale will fall back to English.

I've tested this with a clean MT v5.0.1 and MTG v5.0.1 installation;
old locale file = test passed;
new locale file = test failed;
rollback to the old locale file = test passed;

Could you try if this is happens to you as well, so that I can be sure that it is not my computer hating me?

**Comment by SmallJoker** [comment]
> But if you use Weblate's .po or .mo the locale will fall back to English.

No wonder if the language code isn't right. Fix the translations.
```
#: src/network/clientpackethandler.cpp
msgid "LANG_CODE"
msgstr "LANG_CODE"
```

**Comment by h4ml3t** [comment]
> No wonder if the language code isn't right. Fix the translations.
> 
> ```
> #: src/network/clientpackethandler.cpp
> msgid "LANG_CODE"
> msgstr "LANG_CODE"
> ```

Ah! Now I got what you meant here https://github.com/minetest/minetest/issues/8809#issuecomment-522124513, I thought that you were talking about the C++ source code, not about the locale file.

That string wasn't being shown in POEdit, I've fixed it using the notepad.
Hopefully now it's all ok, thank you again!
