### ISSUE TITLE
Node Box gets HUGE and causes the game to lag

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#8820]
##### Minetest version

```
5.0.1
```

##### OS / Hardware

Operating system: OpenSUSE Tumbleweed
CPU: i3

GPU model: Nvidia GTX 1050 Ti
OpenGL version: 4.3

##### Summary

My node box makes Minetest lag and creates a HUGE node, nothing wrong is visible in log

##### Steps to reproduce

1. Create a new mod with following code: https://del.dog/izabimixes.lua 
2. Start a world with the mod
3. Somehow manage to place the node (tests:fish)
![Bildschirmfoto_2019-08-19_14-44-07](https://user-images.githubusercontent.com/20720267/63266887-3367d500-c291-11e9-8ff6-a487a1f3b05f.png)

**Comment by DS-Minetest** [comment]
In lua, dots are used as decimal separators, not commas.
Eg. write `-0.375` instead of `-0,375`.

**Comment by niansa** [comment]
Yeah I didn't notice that. Okay thx
