### ISSUE TITLE
[Request] Compatibility for products of similar game designs

### ISSUE THREAD

**Issue by hmz27** [minetest/minetest#8829]
What are the odds of adding compatibility with minecraft creations such as created buildings and maps, textures/ressources and shaders? it could pull in people who hate minecraft but **_### love_** the concept :3

**Comment by ClobberXD** [comment]
Minetest closely resembles MC when walking around the world, but the similarities stop there. IIRC there's a program that can convert an MC map into a Minetest world, and MC 1.6/1.7 textures are more-or-less compatible without any extra work. MC 1.8 textures however need to be converted - see https://forum.minetest.net/viewtopic.php?f=14&t=13996. I'm very sure that MC shaders won't be compatible with MT.

**Comment by hmz27** [comment]
https://www.reddit.com/r/Minetest/comments/cj0z75/feasibility_of_a_minecraft_compatibility/ - I've found discussion about it here. I've tried my best to do conversions and resource pack conversions but im not finding it easy :((

**Comment by SmallJoker** [comment]
Pull requests to extend the features of Minetest are welcome, but not all people aim to let it become a Minecraft clone. Map conversion and wrappers should be user-added, not engine-provided.

Ask in the forums or on #minetest(-dev) if you'd like to know whether a certain feature might have a chance to be accepted in Minetest before coding it.
Why is this even an issue?
