### ISSUE TITLE
Commit fb6f1fd breaks world loading when damage is disabled

### ISSUE THREAD

**Issue by LunaSquee** [minetest/minetest#8833]
The commit fb6f1fd breaks world loading because of the function myplayer->isDead() defined in 3c395d9, when damage is disabled.

To reproduce, create a world in current master with damage disabled. World will not load further until you place a node.

**Comment by ClobberXD** [comment]
Investigating...

**Comment by ClobberXD** [comment]
Placing nodes invokes `writePlayerPos` via `Client::interact` and `Client::sendPlayerPos`, of which the latter returns if `LocalPlayer::isDead` returns true. This could probably be because `LocalPlayer::isDead` would return false all the time, when damage is disabled.

**Comment by ClobberXD** [comment]
See #8834

**Comment by rubenwardy** [comment]
Bug Issues are usually left open until their pr is merged, in case the pr is closed or forgotten

**Comment by sfan5** [comment]
this is fixed by ba8fb774c1abe77c404b578929c6d2b657bf1436, I should have noted that

**Comment by SmallJoker** [comment]
`if (myplayer->isDead() && myplayer->getCAO() && !myplayer->getCAO->isImmortal())`

**Comment by ClobberXD** [comment]
Ideally, `LocalPlayer::isDead` should take `GenericCAO::isImmortal` into consideration, as death in itself means that the player is mortal.
