### ISSUE TITLE
Set the default stack maximum to 100

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#8835]
This is an exceedingly simple change, but it would make counting items much easier in our base 10 numerical system.

The only problems I could see would be mods hard-coded to expect only 99 of something, which may mean that the mod is poorly coded to begin with, and mods that explicitly set the stack maximum of a certain item to 99, which would probably only be a minor inconsistency that can be fixed easily.

This issue is a minor subfeature of the possibly more difficult to implement #5730, but I think that bringing this specific idea to attention is important regardless.

**Comment by SmallJoker** [comment]
Related https://github.com/minetest/minetest_game/issues/1724

**Comment by jastevenson303** [comment]
99 the best choice

**Comment by paramat** [comment]
So 99 was chosen to avoid 3 digit numbers in the inventory slots? 100 would be rare and still easily readable in a slot, so 100 seems fine to me if the change doesn't cause other problems.

**Comment by LoneWolfHT** [comment]
I prefer 99. Or 72 if you're looking to allow for better stack splitting

**Comment by HybridDog** [comment]
You could add the maximum stack size to the minetest settings.

**Comment by paramat** [comment]
I think adding a setting for the default is the wrong approach, instead, better to fix the actual issue of #5730
> This is possible already. The problem is, that the value gets ignored in some places.

**Comment by benrob0329** [comment]
Looping through all items is an ugly hack. The setting is a much cleaner and easier way for things to be adjusted.

**Comment by paramat** [comment]
You could claim that for any item property.
Setting item properties is not an 'ugly hack', it's normal.

**Comment by benrob0329** [comment]
The default stack limit is something a lot of people would like to change, and we don't have an easy way to change the default in Lua afaik without looping through all the itemdefs.

**Comment by jastevenson303** [comment]
Default 99 is perfect.

Craft grid is 9x9....perfext

**Comment by paramat** [comment]
> we don't have an easy way to change the default in Lua afaik without looping through all the itemdefs.

Looping through is surprisingly actually the best way to do it, see my comments in the PR.

**Comment by benrob0329** [comment]
No. I don't want to loop through every single item just to set the default stack limit in my game. That's a hacky and bloated way of changing a single default value. Not to mention the problems of having to make sure it happens after everything else is loaded and that nothing is wrongly changed should the default value ever actually change.

**Comment by paramat** [comment]
It's not particularly bloated https://github.com/minetest/minetest/issues/5730#issuecomment-526958388
Altering item properties after registration will always seem unpleasant, but we can't add a setting for every property default, so it's the only way for most properties, so it is standard practice.
Using a global setting has it's own issues, it is always preferable for a mod to do what you want somehow, as the original issue author requested https://github.com/minetest/minetest_game/issues/1724#issuecomment-299650410.
The global setting is not what was requested.

**Comment by benrob0329** [comment]
Alright, since you're very much against adding a setting for this, how about adding an API for setting default item properties?

Or just a way to run code first (an extra Lua file for games that runs before anything else would work) so that we can change any preset tables we need **before** the items are defined.

**Comment by paramat** [comment]
Worth considering.
I'm not very much against a global setting, i was overly concerned before. I removed my -1.
