### ISSUE TITLE
mgv6_freq_desert is sometimes ignored

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8836]
##### Minetest version
```
5.0.1
```

##### Summary
This relates to MGV6:

`mgv6_freq_desert` has no effect when the `snowbiomes` flag is set. I can set this value to -100, or 100, it doesn't change the frequency of deserts at all.

If the `snowbiomes` flag is not set, this setting works.

##### Steps to reproduce
* Set `mgv6_freq_desert` to a very low value
* Start a v6 world and see if you're in a desert

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/ba8fb774c1abe77c404b578929c6d2b657bf1436/src/mapgen/mapgen_v6.cpp#L449-L470

**Comment by Wuzzy2** [comment]
Also note there is both `MGV6_FREQ_HOT` (a `#define`) and `freq_desert` (which is the `mgv6_freq_desert` setting).

This seems there are two different values for the desert threshold. Why?

@paramat

**Comment by paramat** [comment]
conf.example:
```
#    The 'snowbiomes' flag enables the new 5 biome system.

#    Deserts occur when np_biome exceeds this value.
#    When the new biome system is enabled, this is ignored.
#    type: float
# mgv6_freq_desert = 0.45
```
There are 2 biome systems, when the new one is enabled (as it is by default), certain parameters and flags are ignored.

**Comment by Wuzzy2** [comment]
> When the new biome system is enabled, this is ignored.

It's not very clear what this means. What is “the new biome system” and how does the player know when it's enabled?
Is it the Biome API? The `snowbiomes` flag? Or what exactly?

I suggest to rewrite the description as it's confusing atm.

**Comment by paramat** [comment]
`The 'snowbiomes' flag enables the new 5 biome system.`
`When the new biome system is enabled`
It's fairly clear, but i could add a `5` in there to be clearer.

**Comment by Wuzzy2** [comment]
> Deserts occur when np_biome exceeds this value.
> When the "snowbiomes" flag is enabled, this is ignored.
> type: float

Then there's not any ambiguity. Right?

**Comment by Wuzzy2** [comment]
Note that the 2 descriptions will not appear on the screen simultanously when the player is using the "All Settings" menu. The player has to click on both settings separately, in that order, to even have a chance to draw the logical connection. Better to be explicit in both cases to leave zero place for doubt or confusion.

**Comment by paramat** [comment]
Ok good points.

**Comment by paramat** [comment]
#8867 merged.
