### ISSUE TITLE
Let mods detect when a client is typing something in the chat

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#8839]
## Problem

Mods currently have no way to know whether or not a player is actually paying attention to the game world.

One big issue is the chat:

- If a player types a longer message they often aren't able to check their surroundings anymore
- On Android typing actually **hides** the entire gameplay until you're done with your message and submit it

## Solutions

If mods could detect such a state from the server side they could take the necessary steps to ensure that the player is not at an disadvantage while chatting.

Example use cases:

- Disabling PvP punches
- Disabling damage from mobs
- Disabling damage caused by the environment
- Marking player as 'not idling' in idle check mods
- Showing a visual indicator for others to see

## Alternatives

Alternatively it would be nice to have a server side method that tells mods which menu/window the client has currently opened.

That way the mod could check for 'chat mode' too.

**Comment by rubenwardy** [comment]
I suggest implementing this as an method like so:


```lua
player:get_active_window()
-- nil
-- { type = "builtin", name = "pause" }
-- { type = "builtin", name = "chat" }
-- { type = "builtin", name = "console" }
-- { type = "formspec", name = "default:chest_locked" }
```

**Comment by paramat** [comment]
rubenwardy, cannot tell if you support the feature.

**Comment by rubenwardy** [comment]
I don't
