### ISSUE TITLE
Group slots

### ISSUE THREAD

**Issue by 6r1d** [minetest/minetest#8842]
## Problem

Right now, you can't use material groups in [formspec](https://dev.minetest.net/formspec) slots. In my opinion, it will be very useful for things like [Pipeworks Autocrafter block](https://gitlab.com/VanessaE/pipeworks/issues/13), because machines will become smaller by accepting material groups for recipes and situations needing these. It will at least influence sorting pipes and autocrafters: it'll often be possible to replace several with one.

For example, make something like this not as buttons with overlays, but user-controlled slots:
![](https://i.imgur.com/J3RCdPZ.png) ![](https://i.imgur.com/cbmPivd.png)

## Solutions

If slot will show a modal with a group input on a right click, allow to drop a sample of a group with shift-click or enter a group in any useful way, that'll help a lot! The method with throwing an example is simplest, but there could be several groups, associated with a node, so it's an issue.

It'll better to have this mode as an optional part of slot config.

I am not adding alternatives, because alternative is just not having this feature, and I doubt it needs additional content.

**Comment by rubenwardy** [comment]
The engine doesn't define or limit what items are accepted in an inventory slot, that's done by mods using the inventory callbacks.

I don't understand what you're referring to by the modal menu. Are you saying that you'd like an inventory slot which only accepts one group, and right-clicking on the slot shows all the items in the group?

**Comment by 6r1d** [comment]
> Are you saying that you'd like an inventory slot which only accepts one group
Not really, I don't want to filter accepted items, I want a way to add an item group to the slot, like "all wood", "all leaves" instead of a certain node type.

> Or are you saying that you'd like a formspec way to select a group without have any of the items in it?
I'd like to have extended slots, allowing these to accept the whole groups, not only items.

A good example will be an autocrafter from Pipeworks mod.

It accepts a recipe, but it accepts one material type, because slots are limited this way: if the recipe expects any leaves, autocrafter will expect a certain type of leaves user entered.

Making several formspecs in a certain mod to imitate group slots might get messy. The situation with pipeworks sorting pipes is the same. I might want all planks in one chest, not just junglewood or oak planks, but I have only several slots with no group input. Or I might want all ores in a certain pipe.

There's a [screenshot](https://gitlab.com/VanessaE/pipeworks/wikis/images/AutocrafterForm.png) of the mod I am mentioning. I think it's very famous, but I add it to be sure. I am talking about the recipe part, slots with planks.

**Comment by LoneWolfHT** [comment]
I think this is something the maker of the mod should implement. I don't think it would be too hard. And it would probably be better than making an engine change

**Comment by 6r1d** [comment]
> I think this is something the maker of the mod should implement

That's exactly what I thought before. And I proposed to [add something like that](https://gitlab.com/VanessaE/pipeworks/issues/13) in Pipeworks mod.

There's VanessaE's answer:

> The only way that would be possible is if the autocrafter's craft grid had switches to choose between item or group -- for each slot, individually.  I can't see that working too well.

Now, I must add to that. We have groups as a feature in recipes. Technically, you can enter each possible recipe yourself, but you don't really want to do that. :-)

> I don't think it would be too hard.

Each mod author can update and reload their form, use buttons with overlays, which will be switching with slots for each of nine recipe items, and it will kind of work. But it will make form-handling code huge and, probably, each author will implement their own flavour of that.

You will need something like this:
* a way to switch slot content to a group
* button to accept item / another group input or have a way to reset it to slot, at the very least
* to repeat that nine times and position recipe elements properly
* to store selected item / group so that form can pass it
* I am probably forgetting other details

> And it would probably be better than making an engine change

I'd like to know why you think that. Groups are present in the engine, there's just no visual component for these, so why not having a complete set of UI components is better?

**Comment by LoneWolfHT** [comment]
> Each mod author can update and reload their form, use buttons with overlays, which will be switching with slots for each of nine recipe items, and it will kind of work. But it will make form-handling code huge and, probably, each author will implement their own flavour of that.
> You will need something like this:
 >  * a way to switch slot content to a group
 >  * button to accept item / another group input or have a way to reset it to slot, at the very least
 >  * to repeat that nine times and position recipe elements properly
 >  * to store selected item / group so that form can pass it
 >  * I am probably forgetting other details

Actually I was thinking of doing just a text field that would accept itemstrings/groups. With this new setting getting the names of actual items isn't too hard
![image](https://user-images.githubusercontent.com/28972859/63610345-251a0180-c58e-11e9-85ae-0dbe8b4509d9.png)
Items can have more than one group at once too. So unless you handle items with fields I can't see any good way of allowing that mod to accept groups

**Comment by 6r1d** [comment]
> Actually I was thinking of doing just a text field that would accept itemstrings/groups. With this new setting getting the names of actual items isn't too hard

I agree, it is possible to alter at least Pipeworks "autocrafters" and "sorting tubes" with a text input.
(Though there are many rows of items in sorting tubes and 3x3 array in autocrafter.)
It's easy to parse for the code, too. Not for people, especially not the ones new to Minetest, though.

I wonder if this idea is possible to implement with current formspec API at all.

**Comment by 6r1d** [comment]
> If you want to be able to do more complex things with your tubes/crafters I think you'll have to accept a few more things in their formspecs, or some extra code behind the formspecs
I know I will need more than a node type check. And with Pipeworks, there'll be digilines support soon, which will add groups.

I am only talking about a visual component in formspecs, because I think it'll be useful in the future.

> Without the fields it will be a pain
I know that very well, that's why I made this issue in the first place. Nobody wants to type text names for materials and groups nine times.

**Comment by LoneWolfHT** [comment]
I can't really see how adding something to the formspec API that allows for changing an item into one of it's groups is better than mods just using fields for their item/group inputs.
Feels like adding mobs to the engine so MTG and other games can have them :shrug:

**Comment by rubenwardy** [comment]
https://gitlab.com/VanessaE/pipeworks/merge_requests/12
