### ISSUE TITLE
Rename a function

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#8849]
## Problem

`core.setting_get_pos` should be changed to `core.settings:get_pos`.
As the other functions were changed (e.g.: `core.settings:get`), I think this should be changed, too.
Besides, modders will think that the correct function is `core.settings:get_pos`, as the API has changed.

## Solutions

Edit the function to `core.settings:get_pos`.

**Comment by SmallJoker** [comment]
#6062

**Comment by Panquesito7** [comment]
Sorry for that. I will see if there are other duplicate issues in the future. Thanks.
