### ISSUE TITLE
Allow use and punch buttons to be customized

### ISSUE THREAD

**Issue by Towtow10** [minetest/minetest#8853]
## Problem
You can't customize the use and punch buttons they are currently RMB and LMB respectively, I would like to be able to switch them.

## Solutions
Add an option in the all settings control section that would allow you to change what is bound to use and punch.

**Comment by style-nine** [comment]
https://github.com/minetest/minetest/issues/2361

**Comment by ClobberXD** [comment]
Duplicate of #2361, and there's also a PR that implements this feature: #7924

**Comment by ClobberXD** [comment]
#7924 implements this.

**Comment by jastevenson303** [comment]
@ANAND why do you refer to a closed PR?

**Comment by ClobberXD** [comment]
@jastevenson303 #7924 is still open. I don't understand what you mean... :confused:

**Comment by jastevenson303** [comment]
Sorry my mistake.

**Comment by jastevenson303** [comment]
Can it be merged?
