### ISSUE TITLE
LDAP auth backend

### ISSUE THREAD

**Issue by emorrp1** [minetest/minetest#8858]
##### Issue type

* Feature request

##### Minetest version

```
5.0.1
```

##### Summary

Auth now support multiple backends. Only SQLite3 and legacy files are supported (#7279).

Adding LDAP permits to delegate user roles and password resets to an existing implementation, potentially also disallowing user registration. The use case is integration with https://freedombox.org/ home cloud web UI. Note: adapted shamelessly from #8056.

**Comment by Linuxdirk** [comment]
It would be awesome having at least one backend that is independent from Minetest's user management. A widely used and standardized system like LDAP is the perfect candidate for that.

**Comment by thomasrudin** [comment]
This will be rather tricky with the current SRP mechanism :/
https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol

**Comment by emorrp1** [comment]
Indeed, my initial search for LDAP support pulled up [this thread](https://forum.minetest.net/viewtopic.php?p=321915&sid=9bb499400d93909fa24b1aacd98fa145#p321915) and I admit I only understand the basics of SRP.

The wikipedia page says that the Server starts with a hash of the user's password, but since minetest handles registration, there must be some pre-SRP negotiation going on. During that, perhaps it's possible to get LDAP to store an additional Minetest hash [userPassword](https://www.openldap.org/doc/admin24/security.html) against the user? Or LDAP could be configured (SASL?) to request Minetest generate the initial hash during password resets, since I get the impression the Hash function must be under Minetest's control. Obviously this will be more difficult than merely changing the storage location, hence a separate ticket to Postgresql.

**Comment by Niwla23** [comment]
I dont know if this is dumb, but i have heard that sqlite shouldnt be used in production, whats about allowing mysql? (for servers, not in singleplayer)

**Comment by Calinou** [comment]
@Niwla23 Minetest already supports PostgreSQL, which is fine for most purposes on large servers.
