### ISSUE TITLE
Use inner stairs in diagonal dungeon stairways

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8863]
## Problem

In the large dungeons (e.g. the desert dungeons), there can be diagonal stairways. However, they don't use the stair nodes.

## Solution

Generate stairs and inner stairs to create a nice-looking proper staircase. The nodes fit nicely into the existing structure:

![EKM9gZZphS](https://user-images.githubusercontent.com/3686677/86420093-60687f00-bccd-11ea-8cf1-a6c4c29e4779.png)

This example uses 2 (normal) desert stone stairs and one inner desert stone stair (from Minetest Game) in the first level, which are placed like this:

```
Iv
>.
```

* v = stair, pointing South
* > = stair, pointing East
* I = inner stair connecting the other stairs
* . = air

This repeats on each Y layer.

## Further notes

The inner stair node would require a new mapgen alias and probably also an addition to the biome definition (because they support dungeons now).

## From the game/mod perspective

In diagonal staircases, these nodes should only be placed if BOTH the node for stairs and inner stairs are defined (by mapgen alias or biome definition). If one or both of these nodes is not defined, Minetest must fall back to the current behaviour, which is not placing any stair nodes. 

This is for backwards-compability and to prevent odd-looking structures if only the stair node, but not the inner stair node is defined.

**Comment by paramat** [comment]
Interesting idea. Might be a little tricky, stairs in dungeons are very difficult to get right (there's even a comment in code noting this) and still have some bugs despite me spending many hours trying to fix them.

A new biome field would be necessary, we don't use aliases for dungeon nodes or cave liquids anymore. I'm not sure it is worth adding a whole new biome field when diagonal corridors are only 1 in 4 corridors (when enabled) and when many games won't even have diagonal stairs.
