### ISSUE TITLE
object:set_rotation: Pitch and roll are flipped?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8868]
##### Minetest version
```
5.0.1
```

##### Summary
It seems that the documentation about the object `set_rotation` function is wrong. I'm not 100% sure about this.

The pitch and roll seem to be flipped. What is called “pitch” in docs is actually roll and vice-versa.

> * `set_rotation(rot)`
>     * `rot` is a vector (radians). X is pitch (elevation), Y is yaw (heading)
>       and Z is roll (bank).

##### Steps to reproduce
* Call `set_rotation` on any object. Change the “pitch”, and then change the “roll” and see in which direction the object actually rotates.

**Comment by DS-Minetest** [comment]
Here's how the values given to `setRotation()` are applied (after making them to radians):
http://irrlicht.sourceforge.net/docu/matrix4_8h_source.html#l00825

**Comment by rubenwardy** [comment]
X=Roll, Y=Yaw, Z=Pitch is the correct behaviour, this should be treated as a bug rather than a documentation issue

**Comment by ClobberXD** [comment]
> X=Roll, Y=Yaw, Z=Pitch is the correct behaviour, this should be treated as a bug rather than a documentation issue

X as roll and Z as pitch is the way it is, now, AFAIK. It should be X=pitch and Z=roll.

**Comment by paramat** [comment]
You can test using this modified boat code, and this post makes things clearer https://github.com/minetest/minetest/pull/7395#issuecomment-426861772
```
D, A: rotation.Y. Yaw around world Y axis (but only if rotation.Z = 0)
W, S: rotation.X. Pitch around model left-right axis
Sneak, jump: rotation.Z. 'Roll'

At first don't alter the Z component from 0. Yaw and pitch will work intuitively.
```
So the documentaion is correct (keeping in mind the imprecise uses of the words yaw, pitch amd roll) and testing the code shows this.

We have to be very careful about this because it is complex and 'yaw, pitch, roll' do not act as applied to an aircraft, rotation acts in an Irrlicht-specific way. This is all detailed in the long discussions.
Note: `At first don't alter the Z component from 0. Yaw and pitch will work intuitively.`. Once Z has been altered the behaviour is not intuitive.
> Honestly, the function probably shouldn't use terms such as 'pitch,' 'roll,' or 'yaw' since that is not how it works, exactly

I agree and think this is causing the confusion, better descriptions are needed, so a documentation issue. I'm happy to improve them due to my experience with the feature.

**Comment by Wuzzy2** [comment]
I never claimed it was a bug, I said from the start that I believed the docs to be wrong.

Note that “pitch” and “yaw” already have a well-established meaning in Minetest, if you look in the rest of the Lua API. Just look at all the other functions that deal with rotation. It's not good if Lua API documentation basically implies 2 different definitons of pitch/yaw/roll.

**Comment by rubenwardy** [comment]
> X as roll and Z as pitch is the way it already is, AFAIK. It should be X=pitch and Z=roll instead.

Ah yeah, I meant  X=pitch, Z=roll

**Comment by paramat** [comment]
Wuzzy2, yes, i didn't mean to suggest you were claiming a bug in the code, i was expressing that i thought 'bug' wasn't a suitable label for poor quality documentation, maybe we need a new label?

If rot.z = 0, pitch and yaw behave consistently with player yaw and view pitch, so it's not entirely incorrect.
I might try to clearly describe the rotation behaviour and update the documentation.

**Comment by paramat** [comment]
Testing my boat code, the current documentation seems correct but lacking in detail.
Suggested documentation:
```
* rot.y is rotation around the world Y axis, and is identical to the previous object yaw.
* rot.x is rotation around the object's left-right axis, so can be considered to be pitch.
The object's left-right axis is rotated around the world Y axis by rot.y.
* rot.z is rotation around the object's front-back axis, so can be considered to be roll.
The object's front-back axis is rotated around the object's left-right axis by rot.x.

For some uses, rot.z does not need to be altered from 0, then rot.y and rot.x act
intuitively like yaw and pitch.
Note: Altering rot.z away from 0 can result in difficult to understand behaviour.
```
?

The YXZ order is important to help understand which axes have priority. If expressed as a gimbal system the order of rings from outer to inner owuld be YXZ or yaw-pitch-roll. As in the left side of this image:

![gimbal-2](https://user-images.githubusercontent.com/3686677/63975299-9e41b900-caa6-11e9-90df-62887264ac9a.gif)

**Comment by DS-Minetest** [comment]
I've tested. Everything seems to work fine and intuitive.
The order in which yaw, pitch and roll are applied could be documented (it's extrinsic z-y-x = instrinsic x-y′-z″).
<details><summary>test code</summary>

```lua
local function get_player_head_pos(player)
	local pos = vector.add(player:get_pos(), player:get_eye_offset())
	pos.y = pos.y + player:get_properties().eye_height
	return pos
end

local function spawnent(player)
	local pos = vector.add(get_player_head_pos(player), vector.multiply(player:get_look_dir(), 2))
	return minetest.add_entity(pos, "matrix_test:ent")
end

minetest.register_entity("matrix_test:ent", {
	collisionbox = {-0.5, -0.5, -0.5, 0.5, 0.5, 0.5},
	visual = "cube",
	visual_size = {x = 1, y = 1},
	textures = {"yp.png", "yn.png", "xp.png", "xn.png", "zp.png", "zn.png"},
	static_save = false,

	on_rightclick = function(self, clicker)
		minetest.chat_send_all("ent:on_rightclick")
		local rot = self.object:get_rotation()
		if clicker:get_player_control().aux1 then
			rot.y = rot.y + 1
		else
			rot.x = rot.x + 1
		end
		self.object:set_rotation(rot)
	end,
	on_step = function(self, dtime)
		local rot = self.object:get_rotation()
		rot.z = rot.z + dtime
		self.object:set_rotation(rot)
	end,
})

minetest.register_chatcommand("nent", {
	params = "",
	description = "",
	privs = {},
	func = function(name, param)
		local player = minetest.get_player_by_name(name)
		spawnent(player)
		return true, "new ent"
	end,
})
```
</details>

**Comment by paramat** [comment]
PR #8882

**Comment by paramat** [comment]
I think i was too eager to open a PR, the documentation is correct, i'm not sure it needs improvement.
> Note that “pitch” and “yaw” already have a well-established meaning in Minetest, [...] It's not good if Lua API documentation basically implies 2 different definitons of pitch/yaw/roll.

The way 'pitch' and 'yaw' behave in XYZ rotation seems identical to object yaw and player view pitch. Can you point out differing meanings in the API?
