### ISSUE TITLE
Anyone seen any 'projecting dungeons' recently? Maybe remove the setting?

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8875]
![screenshot_20150414_031532](https://user-images.githubusercontent.com/3686677/64056333-60b65c00-cb8a-11e9-8005-d2494ec85c35.png)

I realised i can't remember seeing any of these 'projecting dungeons' in the last year or so. Has anyone else? A 'projecting dungon' is one that is partly in the ground but has some complete rooms that project out of the ground. They were one of my favourite parts of mapgen.

I'm wondering if they have disappeared due to the change to the 'num_emerge_threads' setting default, which was changed to 1?
If they depend on that setting, there's no point having the following setting (because it doesn't always work):
```
#    Whether dungeons occasionally project from the terrain.
# projecting_dungeons = true
```
Instead i might be able to add a new dungeon parameter to enable mapgens to create projecting dungeons if desired.

Anyway, first i will do some intensive testing to see if these really have disappeared.

**Comment by paramat** [comment]
I tested by setting dungeon noise parameters to create 8 dungeons per mapchunk, then setting `num_emerge_threads = 2`, still can't find any projecting dungeons.
I think i'll remove the setting during my upcoming dungeon work.

**Comment by TumeniNodes** [comment]
Doing a lot of testing of my own work lately, I can vouch that I have seen plenty of examples like the one on the left of the image you posted... but none at all of the example to the right.

I like the example on the left because it is similar to having ruins in the map.
I guess the worst that can happen is... nothing

**Comment by Wuzzy2** [comment]
I haven't seen projecting dungeons since a looooooooooong time. And my projecting_dungeons setting is set to true. So it seems this setting is broken atm.

**Comment by Wuzzy2** [comment]
@paramat: Does this count?:

https://satoshiupload.com/images/Gz9PQ0WLVo.png

mapgen: v6

**Comment by paramat** [comment]
That's a 'large cave', these generate out beyond mapchunk borders. So i'm guessing what happened is that the dungeon generated as 'non projecting' within its own mapchunk and a large cave from a neighbouring mapchunk exposed it later.
So inconclusive. To be sure, the dungeon would have to project distant from a large cave.
Thanks.
