### ISSUE TITLE
'Autoforward' broken when damage is disabled

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8876]
I'm on recent commit 1d3f5af7c060f989a5e2778a9117c6f7e1e88863
Suspect 3c395d908f016158162f022f24d7ea48eeb7e8d5
My W finger aches now.

EDIT: Yes! Autoforward broken when damage is disabled, suggests that commit which looks at player HP.
`bool isDead() const { return hp <= 0; }`
@ClobberXD

**Comment by ClobberXD** [comment]
This should be fixed in #8834, see https://github.com/minetest/minetest/pull/8834/commits/0ad98bfd50575d8a68bf8439fa644308ce3b134c#diff-8a204252470abc49d736ebdaf2510b71R735

**Comment by paramat** [comment]
Nice, thanks.

**Comment by paramat** [comment]
#8834 merged.
