### ISSUE TITLE
not_in_creative_inventory group not in lua_api.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8877]
##### Minetest version

```
5.0.1
```

##### Summary
The group `not_in_creative_inventory` is not in `lua_api.txt`.

This is a semi-special group. The engine ignores the group, however, this group is added to `:`, `air`, `ignore` and `unknown`. At least this fact belongs in the docs.

**Comment by DS-Minetest** [comment]
#7783

The `not_in_creative_inventory` can be used for mods to suggest other mods (eg. inventory mods, crafting guides, etc.) how to handle the item.
Just because the engine doesn't implement anything for the group doesn't mean that it mustn't document the group.
And the engine uses this group, so :+1:.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/7783#issuecomment-429683569

**Comment by DS-Minetest** [comment]
> See [#7783 (comment)](https://github.com/minetest/minetest/issues/7783#issuecomment-429683569)

As `not_in_creative_inventory` is used for some items in the engine code that comment is kinda wrong. If the engine wouldn't care about this group, it would not set this group to its items. The game could then override the engine items (I do **not** suggest this.).
The aspect of that comment which is positive about this issue might still apply:
> I won't be against adding a section for common groups

**Comment by paramat** [comment]
Yes, i think documenting it is fine, but with comments making clear it is primarily for use by game mods that provide a creative inventory.

**Comment by Wuzzy2** [comment]
Suggested text (maybe too long, but all important info is included):

> * `not_in_creative_inventory=1`: If present, item must be hidden in creative inventory, i.e. an inventory in which players can take infinite items for Creative Mode or something similar. Recommended for items that the game/mod only uses “internally” or would break things if players got them. This group has no special meaning in the engine, as creative inventories must be implemented by mods. However, the `air` and `ignore` nodes and the hand do have this group set by default.
