### ISSUE TITLE
Can you guys please provide a "large" package including all mods and games?

### ISSUE THREAD

**Issue by CHJ85** [minetest/minetest#8880]
Hi there.
It'd be awesome if you guys could provide a "large" edition of the game with all the mods (from the mod github + the forum) and the games from the forum, and maybe some preinstalled worlds created by the community?
I think that if everything is included, more people are gonna use the game, not having to go through the github and forum all the time and download everything.

**Comment by SmallJoker** [comment]
Preferably a script to clone the most recent version directly from the source. If you made good worlds, feel free to publish them on the forums. Additional mods can be put into "worldmods", but those may outdate quickly.
:-1: Will not happen upon request, needs ready-to-deploy packets from the community.

**Comment by CHJ85** [comment]
So then how about this?
Make it easier for people to install the mods and games from within Minetest itself.
Would that be possible?
Because having to hunt down and install all these things is very time consuming and not to mention requires some computer know how.
I just think that if you could de-complicate that whole process, a lot more people would play the game.

**Comment by rubenwardy** [comment]
> Make it easier for people to install the mods and games from within Minetest itself.

Minetest 5.0.0 has the ability to install games and mods from within the menu itself. It doesn't handle dependencies yet, but that should be implemented soon

**Comment by CHJ85** [comment]
Oh thanks. I am still on 4.17. I installed it from the Ubuntu Boutique.
I'll upgrade to the latest one.
Now, what do you mean by dependencies?
Do you mean like if a game depends on 3rd party mods?

**Comment by SmallJoker** [comment]
@CHJ85 That's very unlikely to happen, as games are an ecosystem for itself. What he meant were ordinary mods that depend on others. Example: "moretrees" depends on "biome_lib", but the main menu content download yet does not handle that.

Can I assume your request lost priority due to the new content database? There are already several issues to improve that one.

**Comment by CHJ85** [comment]
One more thing though.
Do you think you could add "maps" to the contents database in the future as well?
Is there a plan for that?

**Comment by SmallJoker** [comment]
Please request features in https://github.com/minetest/contentdb/issues

**Comment by paramat** [comment]
LOL it would be a rather large package.

**Comment by CHJ85** [comment]
It would be large. But come on. Is storage really an issue these days?

**Comment by LoneWolfHT** [comment]
Yes. And it's also a paaaiiinnn for people with slow internet (Slow internet is an issue these days btw :P)

**Comment by CHJ85** [comment]
How is it any more painful than using the forum like the way we do it now?

**Comment by rubenwardy** [comment]
Packaging everything in one thing would be incredibly inconvenient both for users and for overhead. ContentDB is a much better solution for that.

To upgrade on Ubuntu, do the following:

```
sudo add-apt-repository ppa:minetestdevs/stable
sudo apt-get update
sudo apt-get upgrade
```

**Comment by CHJ85** [comment]
I didn't mean packaging everything into one huge bundle.
I mean add "maps" to the content library like you did Texture Packs, Games and Mods.
And thanks, I already did upgrade to version 5.

**Comment by LoneWolfHT** [comment]
> How is it any more painful than using the forum like the way we do it now?
> And besides, the maps aren't that much bigger than the texture packs, mods and games.
Both of them are a pain. That's why I use 5.0's ContentDB

**Comment by LoneWolfHT** [comment]
> I mean add "maps" to the content library like you did Texture Packs, Games and Mods.

The best place to requst that is here btw https://github.com/minetest/contentdb/issues

**Comment by paramat** [comment]
I think you greatly underestimate how big 'all mods and games' would be. Such a package would be undownloadable for almost everyone.
You also greatly overestimate the storage ability people have, many MT users are using old or low-performance machines. They also wouldn't want to fill a large chunk of their harddrive (or most of it) when 99.9% of the content doesn't interest them.
The suggestion is just silly =)

**Comment by CHJ85** [comment]
It's not a silly request.
Some of these games that were made for Minetest require specific maps.
So having the ability to download the maps directly within the game itself would be nice.

**Comment by jastevenson303** [comment]
It would be good to put everything on archive.org anyway

**Comment by paramat** [comment]
CHJ85 i was referring to the request in the first post, that should be clear from the context.

Downloading maps is a valid and practical request.
