### ISSUE TITLE
Ban mods freezes server when someone is joining

### ISSUE THREAD

**Issue by Enrikoo** [minetest/minetest#8887]
```Minetest 5.0.0```

Rubenwardy this is about your server I gotta talk about, what operating system and cpu u have.
Operating system:
CPU:

The same with the thing above, pc informations
GPU model:
OpenGL version:

If more people get banned on the server, the stronger the lag goes when someone is joining.

I posted this because every ban mod is causing freeze on every server. The max lag on his server was 50

**Comment by Enrikoo** [comment]
@rubenwardy now theres your question needed, I think it depends on minetest. IDK really

**Comment by rubenwardy** [comment]
Irrelevant to the minetest engine

**Comment by SmallJoker** [comment]
There was also a recent change that prevented the server locking up itself when using some functions in `register_on_newplayer`. Probably fixed by now.
