### ISSUE TITLE
Per-game optional mods

### ISSUE THREAD

**Issue by mbartlett21** [minetest/minetest#8892]
## Problem

I would like subgames to have optional included mods.

## Solutions

I would like a separate folder in the subgame called `optionalmods` where I can place optional mods. These optional mods should be enabled by default on any created worlds, but be able to e disabled.

**Comment by AKryukov92** [comment]
> I would like subgames to have optional included mods.

Why exactly you want this? It looks like solution of some other problem, not like problem itself.

**Comment by benrob0329** [comment]
This seems like something a game-setting could take care of (yes they need to be made per-world).

**Comment by paramat** [comment]
No need for a separate folder, this has been suggested before and could be done by allowing the mods contained within a game to be disableable.
There's an issue somewhere, this is probably a duplicate.

**Comment by DS-Minetest** [comment]
#8622

**Comment by paramat** [comment]
^ Yep, just found it.

**Comment by DS-Minetest** [comment]
That issue is different though. It requests a way to disable any subgame mod.
This issue however requests additional disable-able mods with normal subgame mod not being optional.
(Imo instead of putting them into a separate folder, a flag in `mod.conf` could be set.)

**Comment by paramat** [comment]
Ok agreed.

**Comment by paramat** [comment]
Actually, the other issue discusses and suggests configuration for making only certain mods optional, as you suggest, so duplicate.
We can't use a separate folder, too complex.
