### ISSUE TITLE
Game crashed unexpectedly

### ISSUE THREAD

**Issue by isidentical** [minetest/minetest#8893]
##### Minetest version
```
Minetest 5.0.1 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/app/share/minetest"
```

##### OS / Hardware

Operating system: Trisquel GNU/Linux
CPU: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz

GPU model: None
OpenGL version:  2.1 Mesa 18.0.5

(Lenovo Thinkpad X200 w/Libreboot)

##### Summary
```
/usr/include/c++/8.3.0/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = ItemStack; _Alloc = std::allocator<ItemStack>; std::vector<_Tp, _Alloc>::reference = ItemStack&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
```
##### Steps to reproduce
I was building my house, i opened my inventory and left shift + clicked silver sand. Then it went to the crafting table and i shift + clicked again and game crashed.

**Comment by ClobberXD** [comment]
Possible duplicate of #7761
