### ISSUE TITLE
Occlusion queries

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#8894]
Irrlicht supports hardware occlusion queries, which is faster and more effective than doing it software-wise: http://irrlicht.sourceforge.net/docu/classirr_1_1video_1_1_i_video_driver.html

[Here](https://github.com/minetest/minetest/blob/master/src/client/clientmap.cpp#L361) you can check whether the mapblock is visible from the camera or not. Add a query with:

```C++
driver->addOcclusionQuery(SceneManager->getSceneNodeFromId(666), mesh);
```

Note: the ID of the map scene is `666`

Then you run all queries from the main render loop with:

```C++
driver->runAllOcclusionQueries(false);
driver->updateAllOcclusionQueries(false);
```

And check the result with:
```C++
u32 is_visible = driver->getOcclusionQueryResult(clientmap);
```

This results in `0xffffffff` (visible) or `0x0` (non-visible).

Problem: it seems that only an `ISceneNode` (the map scene), and not an `IMesh` (the mapblock mesh) can be hidden.

**Comment by SmallJoker** [comment]
So this would imply splitting the occlusion code into independent client/server functions.

**Comment by lhofhansl** [comment]
I've been thinking about this as well.

Is it that simple, though? You need to render a simpler mesh with a flat color but at full resolution. Also to account for transparency you'd need to render both the solid and transparent nodes, and blocks with transparent nodes cannot be rendered with just a single color, so probably need to do it on a node by node basis.

I admit, I do not know much about this. Will Irrlicht handle this all automatically? That would certainly be great!

**Comment by kilbith** [comment]
> so probably need to do it on a node by node basis.

Nodes are meshes only as parts of a block, so you'd need to set a scene per block and a IMesh per node and add query from that. That's definitely too heavy.

> Or are you saying we just run the occlusion queries during normal rendering and apply the results to the next frame (also with a one-frame slight lag)?

The queries and their result have to be run **after** the `drawAll()` render call. If you don't have any pixel rendered on the screen, the queries have no effect. And the pipeline is not stalled.

> Will Irrlicht handle this all automatically?

Yes.

**Comment by lhofhansl** [comment]
> The queries and their result have to be run after the drawAll() render call. If you don't have any pixel rendered on the screen, the queries have no effect. And the pipeline is not stalled.

Perhaps I'm missing something... Either you draw each block into the z-buffer only with *simpler* meshes (or you would not have won much, just drawing the scene twice), or you draw the scene as usual (visible bits and z-buffer) and then query the visibility less often with a lag (either on a timer or every n-th frame).

**Comment by lhofhansl** [comment]
I assume nothing came from this. Close?

**Comment by kilbith** [comment]
Why closing? It can be useful for anyone who pass by here in the future.
