### ISSUE TITLE
Search bar in world mod configuration

### ISSUE THREAD

**Issue by Desour** [minetest/minetest#8899]
## Problem

I'm always frustrated when I want to enable a new mod in a world or even multiple ones. The reason for this is that the mod list is huge (228 folders are currently in my mods folder, and I do use modpacks for test-mods and co.). Finding the right mod takes some time.

## Solutions

I'd like to have a search bar in the world configuration menu with that you can search / filter for specific mods by their name.

## Alternatives

An alternative could be adding labels next to the scrollbar that show where mods that start with a specific letter begin. This would allow clicking at that pos to get to the mod faster.

**Comment by NathanSalapat** [comment]
you can type the first few letters and jump to that point in the list.

**Comment by DS-Minetest** [comment]
Ah, I see, tables have some sort of search:
https://github.com/minetest/minetest/blob/45826911048388c8b744961bb9e8de1549559d0a/src/gui/guiTable.cpp#L820-L852

**Comment by paramat** [comment]
So i guess low priority?
