### ISSUE TITLE
Formspec labels might cut off translated string if longer than original

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8905]
##### Minetest version
```
5.0.1
```

##### Summary
If you have a formspec with a label that is translated, and the original string is shorter than the translation, the translated version of the label might be cut off too early.

Note the modder is unable to set the label size, it's automatic.

##### Steps to reproduce
Basically, make a dummy mod that shows a label with a long translation and do comparisons.

Create a mod named `test_label` and put inside the following files:

`init.lua`:

```
local S = minetest.get_translator("test_label")
local text = S("Kill a mineturtle.")
minetest.register_node("test_label:node", {
	description = "Test Label Node",
	tiles = {"default_dirt.png^[colorize:#FF0000:127"},
	groups = {dig_immediate=3},
	is_ground_content = false,
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		meta:set_string("formspec", "size[8,8]label[2,0;"..minetest.formspec_escape(text).."]")
	end,
})
```

`locale/test_label.de.tr`:

```
# textdomain:test_label
Kill a mineturtle.=Töten Sie eine Minenschildkröte. Dieser Text ist viel viel viel länger als er eigentlich sein sollte, um das Label aufzufüllen. Muhahaha, er wird niemals zu Ende sein. Jetzt aber doch. ENDE.
```

Note: The German translation is fake; it's artificially inflated, just to make a point. ;-)

Make sure Minetest starts in German* mode.
Now start the game, then give yourself `test_label:node`. Place the red node on the ground and click it to open its formspec. It will display a label.

EXPECTED: The very long German text should be visible, at least until it hits the size limit of the formspec.
ACTUAL: The German text is cut off much, much earlier.

For comparison, play in English mode and do the same thing.
EXPECTED: English text is visible.
ACTUAL: English text is visible. No bug here.

* = If you don't have a German system, you must adjust the files and instructions for your language, of course.

**Comment by DS-Minetest** [comment]
Can reproduce, screenshot:
![screenshot_20190906_145538](https://user-images.githubusercontent.com/7613443/64429551-91305580-d0b6-11e9-826f-ff8cdce34b57.png)
Some related code:
https://github.com/minetest/minetest/blob/5c97eeabace3256d4f50c9d9c7776fb360c2077c/src/gui/guiFormSpecMenu.cpp#L1423
I wonder where the translation is actually done.

**Comment by SmallJoker** [comment]
> I wonder where the translation is actually done.
https://github.com/minetest/minetest/blob/ea9b241c13e9982acb993e616fa1db685ffba5cb/src/gui/guiFormSpecMenu.cpp#L1455-L1456
https://github.com/minetest/minetest/blob/ea9b241c13e9982acb993e616fa1db685ffba5cb/src/irrlicht_changes/static_text.h#L95-L96
https://github.com/minetest/minetest/blob/ea9b241c13e9982acb993e616fa1db685ffba5cb/src/util/enriched_string.cpp#L45

**Comment by paramat** [comment]
I have a feeling this is a duplicate?

**Comment by SmallJoker** [comment]
Labels are now translated like all (or most?) other elements with static text.
2c9edef
