### ISSUE TITLE
Verify the organization's domain

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#8906]
Also add a email to the organization for help/support (e.g.: `support@minetest.net`).

**Comment by sfan5** [comment]
What is "verify" supposed to mean?
We don't provide email support and don't plan to.

**Comment by LunaSquee** [comment]
Do you mean Extended Validation certificates?

**Comment by Panquesito7** [comment]
> What is "verify" supposed to mean?

Verify the organization's domain (show a `Verified` badge).

> Do you mean Extended Validation certificates? That's an overkill, especially when minetest is not associated with any legal entity. Not to mention that it costs a lot.

No, that's not what I'm talking about.

**Comment by paramat** [comment]
Support is given on IRC and in the forum, which is more convenient for the advice givers, and the advice is public so helps multiple people.
No-one has time to attend to support emails.
:-1:

**Comment by rubenwardy** [comment]
Paramat hasn't read the issue

**Comment by rubenwardy** [comment]
Verifying the domain requires DNS access

![image](https://user-images.githubusercontent.com/2122943/64457912-dfac1700-d0eb-11e9-80a3-015f924b6fea.png)

**Comment by Panquesito7** [comment]
> Verifying the domain requires DNS access. This is done here: https://github.com/orgs/minetest/domain/new
> 
> The email bit is only relevant if you have a public email, which we don't

Does this means the organization is already verified?

**Comment by rubenwardy** [comment]
No, I don't have access to the DNS so can't verify it

**Comment by Panquesito7** [comment]
> No, I don't have access to the DNS so can't verify it

Ahh, I see now. I misunderstood you, I thought you said it **is** already verified.
Should I close this issue?

**Comment by paramat** [comment]
Sorry, i assumed the issue was the email address only, (i missed the 'also' at the start of the first post), and the verify request was lacking detail. I shouldn't have closed this.

**Comment by Panquesito7** [comment]
> Sorry, i assumed the issue was the email address only, (i missed the 'also' at the start of the first post), and the verify request was lacking detail. I shouldn't have closed this.

Don't worry, it's OK. 🙂

**Comment by rubenwardy** [comment]
>  EDIT: Does somebody of the developers can do this?

Only @celeron55. As this isn't really under our control, this issue should probably be closed and celeron55 pestered directly instead, if you would like it to be done

**Comment by Panquesito7** [comment]
> Only @celeron55. As this isn't really under our control, this issue should probably be closed and celeron55 pestered directly instead, if you would like it to be done.

Agreed. I'll close this issue then.
Thanks everyone for your comments.
