### ISSUE TITLE
Removing players data after kicking the player fails

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#8908]
##### Minetest version

```
5.0.1
```

##### Summary

Removing players data after kicking the player does not work
Nothing about this in log

##### Steps to reproduce

1. Run following code: minetest.kick_player(name);minetest.remove_player(name)
2. See that the player has **not** been removed

##### Example
```
function storybase.player_reset(name)
	minetest.kick_player(name, "You game data is corrupt and has been removed. You can reconnect now.")
	minetest.remove_player(name)
end
```

**Comment by sfan5** [comment]
`minetest.remove_player` is supposed to return a value, what does it return in this case?

**Comment by niansa** [comment]
nil

**Comment by SmallJoker** [comment]
@niansa `minetest.remove_player` always returns a numeric value. Please disable all unneeded mods to ensure the function is not overridden by anything.

**Comment by niansa** [comment]
Ah it was my own fault, I checked it the wrong way. Actually, it returns 0.
```
function storybase.player_reset(name)
--	Kick player
	minetest.kick_player(name, "You game data is corrupt and has been removed. You can reconnect now.")
--	Remove its data
	minetest.after(1, function()
        local removal = minetest.remove_player(name)
        print("[storybase] Game data of "..name.." was corrupt and has been removed: "..removal)
    end)
end
```

**Comment by sfan5** [comment]
> Edit: Lol it suddenly works?

Most likely because you deferred the call with minetest.after()
