### ISSUE TITLE
Add PNG file name in PNG profile warnings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8910]
## Problem

If you have bad PNGs anywhere, you see tons of messages like:

> Irrlicht: PNG warning: iCCP: known incorrect sRGB profile

But no PNG file name. It IS printed at the `verbose` debug level, however. But this is annoying and not obvious. It looks like this:

> Client: Loaded cached media: 0d90f5b3ffda36a46aa150afde6352f641066dd4 "bbq_veggie_packet.png"

and is written above the “Irrlicht” line.

## Solutions

Output the PNG file name in the warning text, so it is visible at warning level.

## Alternatives

None?

## Additional context

Discussion split off from <https://github.com/minetest/minetest/issues/4449>.

**Comment by SmallJoker** [comment]
This will require either hacky workarounds or modifying Irrlicht. Why?
https://github.com/minetest/minetest/blob/2c9edefde3d941b1efa5c93a087814d6bc3509e6/src/client/inputhandler.cpp#L175-L176
 https://github.com/minetest/minetest/blob/2c9edefde3d941b1efa5c93a087814d6bc3509e6/src/client/clientmedia.cpp#L541-L553

Both log messages are independent, and there's no way to get the PNG errors from here:
https://github.com/minetest/minetest/blob/2c9edefde3d941b1efa5c93a087814d6bc3509e6/src/client/client.cpp#L653

**Comment by appgurueu** [comment]
IMO low priority, as you can just use simple commands to identify bad PNGs without getting Minetest involved. See [libpng warning: iCCP: known incorrect sRGB profile on SO](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile) for an alternative.

**Comment by Wuzzy2** [comment]
Ah.

With `pngcrush -n -q *.png` you can get warnings for all faulty PNGs. Useful.

Feel free to close this issue.
