### ISSUE TITLE
Animated images in formspecs

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#8911]
I would like to see the ability to draw animated images in formspecs. This would allow for things like progress bars such as in furnaces to look smoother.

The animation playback speed should be variable, so that it can still look smooth if the progress bar needs to slow down or speed up.

**Comment by Df458** [comment]
The first half of this will be addressed by #9255 

The speed can only be set when sending fields though, because formspecs are not yet at a point where they can dynamically alter element values once they're presented to the user.

**Comment by sorcerykid** [comment]
Hopefully, if my proposal #9364 gets adopted, then that will offer another means of drawing animated images in formspecs.

**Comment by rubenwardy** [comment]
Implemented
