### ISSUE TITLE
error: ‘struct irr::SIrrlichtCreationParameters’ has no member named ‘OGLES2ShaderPath’

### ISSUE THREAD

**Issue by JPRuehmann** [minetest/minetest#8915]
Hello Icannot compile Minetest since some time anymore.

I get the following error
`error: ‘struct irr::SIrrlichtCreationParameters’ has no member named ‘OGLES2ShaderPath’`
What an I do?

Thanks,

**Comment by SmallJoker** [comment]
`cmake (...) -DENABLE_GLES=0`

**Comment by sfan5** [comment]
To expand on this:
The meaning of `ENABLE_GLES` changed with the addition of proper GLES support. Enabling it "switches" Minetest to OpenGL ES and requires that you use a compatible Irrlicht library (`ogl-es` branch).

**Comment by JPRuehmann** [comment]
That helped, thanks.
