### ISSUE TITLE
Docs falsely suggest main_menu.ogg is part of the Lua API

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8919]
##### Minetest version
```
720aedb46740ba203b4a0f3e049e368abc4932b3
```

##### Summary
This is a documentation bug report.

In `lua_api.txt`, I read this:

> Special sound files
> -------------------
> 
> These sound files are played back by the engine if provided.
> 
> * `main_menu`: Looped sound in the main menu (gain = 1.0)
> * `player_damage`: Played when the local player takes damage (gain = 0.5)
> * `player_falling_damage`: Played when the local player takes
>    damage by falling (gain = 0.5)

The `main_menu` one is incorrect here because this has nothing to do with mods, games or Lua, so it does not belong into `lua_api.txt`.

Why? `main_menu` only works if you put it into `~/.minetest/sounds/`. So this is a player-provided file, not a Lua-used one.

In contrast, `player_damage` and `player_falling_damage` ARE provided by mods, and they must be put into `~/.minetest/mods/<modname>/sounds/` (or a corresponsing game directory). That's a huge difference.

Putting all 3 sounds into the same list suggests they are all used by games or mods, while only the latter 2 are.

## Discussion

So, my main point here is that `main_menu` does not make sense in `lua_api.txt` because it's not used by games or mods, only the main menu.

This `main_menu` sound clearly needs to be documented, but the question is, where? `lua_api.txt` is not correct, but where else to put it? We don't seem to have any official user documentation as of now (only a wiki). So I am a little puzzled.

I did add a wiki page here: https://wiki.minetest.net/Main_menu_music
But that's not official documentation.

Also, the wiki page is currently lacking links to the page (in the wiki), but that's off-topic.

What to do to fix this?

**Comment by DS-Minetest** [comment]
What about adding something like a misc file to `/doc/` that contains stuff which doesn't suit into the other files?

**Comment by ClobberXD** [comment]
Maybe add this to README instead? Probably not the best place, but it already contains similar documentation, like for example, default keybinds.

**Comment by Wuzzy2** [comment]
README sounds fine. Adding a complete new file just for a single feature seems overkill. Also, I thought `doc/` is only for dev docs.

**Comment by ClobberXD** [comment]
> I thought `doc/` is only for dev docs.

I think there's no such distinction. It's just the sub-dir for everything documentation, AFAIK.

**Comment by SmallJoker** [comment]
Well thanks, but a PR would be way faster in any regards.
