### ISSUE TITLE
Box ore type

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#8921]
## Problem

The simplest ore type currently is the spherical `blob` type. There's no way of creating a boxy ore deposit.

## Solutions

Add an ore type similar to the blob ore, but one that simply generates a box instead of a sphere.

## Additional context

Since everything else is blocky in a voxel world, this should be a feature and will probably be the very fastest ore type to generate.

**Comment by Wuzzy2** [comment]
Some ideas for parameters for this ore type:

* `length_min`, `length_max`: Minimum/Maximum length of the cuboid on each axis. MT will select a random length for each axis, unless `cube==true`
* `cube=true`: If this is set, all 3 side lengths will be equal

Example 1: `length_min=3`, `length_max=5`, `cube=true`: Generates a 3×3×3, 4×4×4 or 5×5×5 cube.
Example 2: `length_min=2`, `length_max=6`: Generates a random cuboid between 2×2×2 and 6×6×6, like 3×4×5 or 2×3×6.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/720aedb46740ba203b4a0f3e049e368abc4932b3/src/mapgen/mg_ore.cpp#L142-L153

Each cluster is cubic, 'cvolume' is the volume of the cluster.
If 'clust_num_ores' is set to the cluster volume, the random value cannot exceed it and ore is always placed.
So scatter ore does what is suggested, just set 'clust_num_ores' to the volume of a cluster, clust_size ^ 3.
A good way to test is to use default:meselamp as the ore, it is visible when flying underground.

**Comment by tacotexmex** [comment]
What about performance?

**Comment by tacotexmex** [comment]
Performance seems quite snappy. You sir, are correct! 🎩

![screenshot_20190910_231130](https://user-images.githubusercontent.com/25328789/64650882-84965f00-d420-11e9-9211-03672dc95ea8.png)

**Comment by tacotexmex** [comment]
However, I'd very much like the dimensional features stated in Wuzzy's post.

**Comment by tacotexmex** [comment]
However, I'd very much like the dimensional features stated in Wuzzy's post. The randomization. Also, hollowness.

**Comment by paramat** [comment]
Performance should be very good, as the code is already in the form it would be for the suggested box ore.
If per-cluster random size is added it could be added as an additional parameter for scatter ore, no need for a new ore type. However, i'm not sure this is justified. I disagree with hollowness, too specialist.
I'll reopen due to the additional requests.

**Comment by tacotexmex** [comment]
Excellent. Hollowness I can achieve anyway, so scratch that.

**Comment by paramat** [comment]
Already possible using scatter ore as discussed.
