### ISSUE TITLE
Increase star count? And perhaps make it configurable?

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#8924]
Currently the number of stars is hardcoded to 200 and their size is hardcoded to 0.007 / 2. (Not sure where this number comes from).

It looks much nicer with 1000 or 2000 stars and with their sized reduced (I used 1.0f / 360.0f).

This is what it would look like (1000 stars, size 1/360)
![screenshot_20190910_234652](https://user-images.githubusercontent.com/446130/64674641-1e143f80-d426-11e9-8c78-9d870872c5c3.png)

(200 stars, size 0.007/2)
![screenshot_20190910_234735](https://user-images.githubusercontent.com/446130/64674643-1e143f80-d426-11e9-89f4-c50a5a3a4ea0.png)

Let's have a brief discussion. If people prefer no change, I'll just close (and I won't whine this time).

**Comment by AKryukov92** [comment]
Perhaps amount of stars might be configurable if you want another number.
I don't really care about stars because most of time I do mining underground.

Stars can feature advanced navigation in the world when travelling long distances.
To achieve this, brightness of stars should be different and their positions should be fixed for each world.
In addition, there should be items featuring navigation. Something like [astrolabe](https://en.wikipedia.org/wiki/Astrolabe).

**Comment by SmallJoker** [comment]
Note for weak GPUs (pre 2010): Turn off stairs for better performance.

**Comment by paramat** [comment]
Related to #7614 
Configuration would i guess be done in an extended 'set sky' API.
However at the least, i support a moderate increase in number (1000 seems too big an increase) and a slightly smaller size seems good too. Stars always seemed just a little too big. But test with minimum game window size (1024x600), stars being too small makes their shape vary more noticeably and in an more ugly way as they move.

**Comment by ClobberXD** [comment]
Smaller, but more stars in the sky would be great. 1000 stars look pretty good, and is a good compromise between visual quality and performance. :+1:

**Comment by paramat** [comment]
If you make a PR for these altered defaults i'll test and probably +1.
We can always make it configurable later.

**Comment by pandaro** [comment]
> Stars can feature advanced navigation in the world when traveling long distances.
To achieve this, brightness of stars should be different and their positions should be fixed for each world.
In addition, there should be items featuring navigation. Something like astrolabe.

The thing seems to me very right, but we must add the possibility of disabling, on the server side, the key that allows you to know your absolute position (X; Y; Z).
Then a very survival game could force a player to use stars, compasses and other tricks to get their bearings.

**Comment by lhofhansl** [comment]
I'll make a PR for the new hardcoded values. I picked 1/360 randomly, because it was close to 0.007/2, and somehow made more sense. I have not observed resolution based flickering with that setting @ 1024x600, but I did when I chose smaller values. So it should be a good setting.
