### ISSUE TITLE
Android double tap stops working eventually

### ISSUE THREAD

**Issue by fryguybob** [minetest/minetest#8925]
##### Minetest version

```
5.0.1
```

##### OS / Hardware

Operating system: Android (Fire 7)

##### Summary

Double tap stops working eventually because the time delta check stores one of the values as `unsigned int` defined here:

https://github.com/minetest/minetest/blob/94f2d99142946aca6481ee032ffc933ca6f0763d/src/gui/touchscreengui.h#L296

and used here:

https://github.com/minetest/minetest/blob/94f2d99142946aca6481ee032ffc933ca6f0763d/src/gui/touchscreengui.cpp#L1100

##### Steps to reproduce
Play minetest and don't reboot for 49 days.

**Comment by SmallJoker** [comment]
Workaround (not so serious): Wait another 49 days to catch up the integer overflow again.

**Comment by srifqi** [comment]
Should we change `down_time`'s type to `u64`?

**Comment by SmallJoker** [comment]
2907c0f3a
