### ISSUE TITLE
Attached player disappears after entity reloads

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#8929]
##### Minetest version

```
5.1.0-dev (latest master)
```

##### Summary
If another player gets attached to an entity (like a cart) and that entity then moves away from you, it unloads after a while which is to be expected. When you get closer to that entity with the player again, the entity reappears but the player is missing.

The player's name tag is stuck at 0,0,0 it seems.

Here is a video that demonstrates the issue: https://ihrfussels-server.de/entitybug.mp4

**Comment by LoneWolfHT** [comment]
Wouldn't this have fixed that? https://github.com/minetest/minetest/pull/8701

**Comment by SmallJoker** [comment]
Thanks for the video, but the VLC settings really had to be tuned to see anything at all.


Cannot reproduce. https://krock-works.uk.to/u/attach_test-2019-09-13_18.52.03.mp4

**Comment by IhrFussel** [comment]
Did you try setting active range and object range to 2?

Otherwise I have absolutely no clue how that doesn't happen for you...Here is what I used to compile earlier today:

> git clone https://github.com/minetest/minetest.git; cd minetest/games; git clone https://github.com/minetest/minetest_game.git; cd ..; cmake . -DENABLE_GETTEXT=1 -DENABLE_FREETYPE=1 -DENABLE_LEVELDB=1 -DRUN_IN_PLACE=1; make -j$(nproc);

Then I simply ran ./minetest/bin/minetest on both instances ... there should be no room for error.

**Comment by rubenwardy** [comment]
I've been able to reproduce this on my private survival server, which runs 5.0.1

**Comment by ClobberXD** [comment]
I tried to test this, but for me, the player isn't even attached to the cart when viewing from the second client. Both instances are at commit 4682c7be5d4e4c454c6d8a18279f60acd970da50. o_O

**Comment by ClobberXD** [comment]
I can reproduce this too. Both instances are at commit 4682c7be5d4e4c454c6d8a18279f60acd970da50.

**Comment by SmallJoker** [comment]
Cannot reproduce with:
```
active_block_range = 2
active_object_send_range_blocks = 2
player_transfer_distance = 3
# OR
active_block_range = 2
active_object_send_range_blocks = 2
player_transfer_distance = 1
# OR
active_block_range = 1
active_object_send_range_blocks = 2
player_transfer_distance = 3
# OR
active_block_range = 3
active_object_send_range_blocks = 4
player_transfer_distance = 1
```
Whatever was sent last got attached properly. Please provide a setting combination that causes your problem.
Client and server: master from yesterday.

**Comment by ClobberXD** [comment]
@SmallJoker Good catch, it indeed seems to be the camera offset bug at play, as the player is teleported exactly 200 nodes away in my case too.

**Comment by SmallJoker** [comment]
Hacky solution, which seems to work so far:
```diff
diff --git a/src/content_sao.cpp b/src/content_sao.cpp
index 800c74859..cb374db59 100644
--- a/src/content_sao.cpp
+++ b/src/content_sao.cpp
@@ -1108,7 +1108,7 @@ void PlayerSAO::step(float dtime, bool send_recommended)
 
 	// If the object is attached client-side, don't waste bandwidth sending its
 	// position or rotation to clients.
-	if (m_position_not_sent && !isAttached()) {
+	if (m_position_not_sent) {
 		m_position_not_sent = false;
 		float update_interval = m_env->getSendRecommendedInterval();
 		v3f pos;
diff --git a/src/server.cpp b/src/server.cpp
index f6bf491be..43f3da437 100644
--- a/src/server.cpp
+++ b/src/server.cpp
@@ -786,19 +786,32 @@ void Server::AsyncRunStep(bool initial_step)
 		// Route data to every client
 		for (const auto &client_it : clients) {
 			RemoteClient *client = client_it.second;
+			PlayerSAO *player = getPlayerSAO(client->peer_id);
 			std::string reliable_data;
 			std::string unreliable_data;
 			// Go through all objects in message buffer
 			for (const auto &buffered_message : buffered_messages) {
 				// If object is not known by client, skip it
 				u16 id = buffered_message.first;
-				if (client->m_known_objects.find(id) == client->m_known_objects.end())
+				ServerActiveObject *sao = m_env->getActiveObject(id);
+				if (!sao || client->m_known_objects.find(id) == client->m_known_objects.end())
 					continue;
 
 				// Get message list of object
 				std::vector<ActiveObjectMessage>* list = buffered_message.second;
 				// Go through every message
 				for (const ActiveObjectMessage &aom : *list) {
+					if (aom.datastring[0] == GENERIC_CMD_UPDATE_POSITION) {
+						if (sao->getId() == player->getId())
+							continue;
+
+						// Do not send position updates for attached players
+						// as long the parent is known to the client
+						ServerActiveObject *parent = sao->getParent();
+						if (parent && client->m_known_objects.find(parent->getId()) !=
+								client->m_known_objects.end())
+							continue;
+					}
 					// Compose the full new data with header
 					std::string new_data;
 					// Add object id
```

**Comment by paramat** [comment]
Camera offset has effect in #8037 too.

**Comment by ClobberXD** [comment]
@SmallJoker

#### Short answer

Weird things happen :P

#### Long answer

Here's how I tested:

- I fired up two instances, one as server+client, and the other as client.
- One watches, while the other goes for a joyride in a minecart up to ~4 blocks away.
- After a certain distance, the observer notices that the rider's nametag going to a certain position (I assume this is the same position as explained in the previous comments), and re-attaching back to the cart immediately.
- Once the nametag stops moving, the observer goes to the cart and observes the cart and the rider in the expected place, and heads back to his original viewpoint near the origin of the rails.
- The rider then begins the return trip, as the observer watches.
- But the observer notices that the rider's nametag stopped at the same distance from the observer, where it previously teleported to "that" position for a brief second.
- The observer notices that the cart returns empty, and the rider is simply standing on the ground at that magical distance from the observer's viewpoint. It's to be noted that the rider is still attached to the cart, and has returned to the start of the track (at least that's what the rider's client believes).
- After a random amount of time (it can range from 10s to 1m), the rider is suddenly teleported back to where the cart now is.
- Upon pushing the cart away, the observer also notices that while the rider is physically in the cart, the rider isn't attached to the cart, and remains in the same starting position while the cart whizzes off. It's to be noted that the rider is still in the cart acc. to the rider.

A video would've made this a lot clearer, but my recorder is giving me some troubles for the past couple of days. Sorry about that...

**Comment by IhrFussel** [comment]
I tested it now with different MT versions again:

- Server: 5.1.0-dev
- Client: 5.1.0 Stable

Behavior: Name tag remains at the last seen position of the cart until observer gets closer again, then name tag and player model appear at the cart entity again.

This means it does **not** happen with 5.0.1 as client.

So the bug seems to be client side and only appeared after 5.0.1 release.

**Comment by IhrFussel** [comment]
Okay I'm completely confused now, cause the attachment behavior just seems random now to me:

- 5.1.0 in cart moves away from 5.0.1
- as 5.1.0 is out of view name tag appears at last seen position
- 5.0.1 moves towards 5.1.0 in cart again
- 5.1.0 appears at cart plus name tag AND remains in cart
- 5.0.1 moves then away from cart
- name tag ONLY appears then ~ 200 nodes away from cart
- 5.0.1 moves towards cart again
- 5.1.0 players appears correctly in cart again
- 5.0.1 moves away AGAIN and this time the name tag REMAINS at the last seen cart position

**Comment by IhrFussel** [comment]
Okay I now tested both server and client being 5.0.1 now and the bug doesn't happen there.

There is another minor visual bug that happens but it's only when someone joins while another player is already inside a cart and drives away (player model remains at the same position until either player in cart or joined player get close again).

**Comment by SmallJoker** [comment]
@ClobberXD Does the recorder work now? SimpleScreenRecorder is a solid choice for such recordings. I would appreciate if you could spend some time in visualizing this behaviour.

**Comment by ClobberXD** [comment]
@SmallJoker Yes, SSR works fine now (Wayland was somehow selected as my default WM, which SSR doesn't support). I'll record my experiment in `master` and after applying #8989 within a couple of days.

**Comment by ClobberXD** [comment]
Video demonstration of attachment behaviour as in https://github.com/minetest/minetest/commit/4682c7be5d4e4c454c6d8a18279f60acd970da50: https://youtu.be/AJnQ45bbWDI
