### ISSUE TITLE
Waving Liquids (Water) is broken?!

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#8931]
Perhaps it's by design? I notice that @paramat required waving = 3 to apply the shader wave transformation.

**Comment by lhofhansl** [comment]
(I just lost 2h on this, thinking it's related to my fog shader...)

**Comment by lhofhansl** [comment]
Sigh... Looks like game #2466 git rid of the waving = 3 markers accidentally.

**Comment by sfan5** [comment]
Indeed
![file](https://user-images.githubusercontent.com/1042418/64908035-1ccf6500-d6fb-11e9-86ca-91d680437350.png)

**Comment by Wuzzy2** [comment]
Wait, what? So you agree the waving was removed accidentally but marked the issue as invalid?
Huh??
@sfan5, you are sending mixed messages here. :-(

**Comment by SmallJoker** [comment]
@Wuzzy2 MTG issue.

**Comment by paramat** [comment]
Weird how those lines got removed.
