### ISSUE TITLE
Built-in formspecs are forced to use real_coordinates, but haven't been converted

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#8932]
##### Minetest version
```
Compiled master a few minutes ago
```

##### Summary
![image](https://user-images.githubusercontent.com/28972859/64912125-a3764900-d6df-11e9-87ef-62e42a0a6f23.png)

##### Steps to reproduce
Compile the latest master, join a world, and press **[Esc]**

**Comment by DS-Minetest** [comment]
Related: #8923

**Comment by DS-Minetest** [comment]
The same happens in death formspecs.
Links that might help fixing:
https://github.com/minetest/minetest/blob/9acd36bf9981cf9cb8e82785508d6eb7f010cc77/src/client/game.cpp#L4057
https://github.com/minetest/minetest/blob/9acd36bf9981cf9cb8e82785508d6eb7f010cc77/src/client/game.cpp#L3983-L3989
https://github.com/minetest/minetest/blob/9acd36bf9981cf9cb8e82785508d6eb7f010cc77/src/client/game.cpp#L570-L574

**Comment by SmallJoker** [comment]
1de4ca1
