### ISSUE TITLE
Enforce reliable mod loading order

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8933]
## Problem

Apparently mod loading order is very random and all over the place. Game mods and user mods are interspersed a lot. At least builtin code is forced at the beginning.

See https://github.com/minetest/minetest/pull/8873

## Solutions

Force the following mod loading order:

* builtin
* Game mods
* User-selected mods

## Alternatives

None? I don't see how anything else would make sense.

## Additional context

Based on off-topic discussion in: https://github.com/minetest/minetest/pull/8873

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/issues/8934#issuecomment-531541249

**Comment by sfan5** [comment]
But why is this a problem?

**Comment by rubenwardy** [comment]
You should not be depending on the mod load order, only on dependencies

**Comment by paramat** [comment]
Hm yes i can't see any problem or any benefit.
Although of course game mods usually do not depend on optional mods, a server owner may possibly modify a game mod to do so, and require an optional mod to load in the middle of loading game mods.

**Comment by Wuzzy2** [comment]
Current mod loading order:

* builtin
* Game mods and user-provided mods, in a completely unpredictable order

What I want:

* builtin
* game mods
* user mods

Why? Because it just doesn't make sense that an user mod can load before any game mod.

This issue was motivated by the following posts:

SmallJoker gave an example of how mods are loaded:

```
debug_log_level = verbose
grep "Loading and running script" debug.txt >filtered.txt
Tidy.

Loading and running script from ..
<DIR>/builtin/init.lua
<DIR>/builtin/init.lua
<DIR>/builtin/init.lua
<DIR>/builtin/init.lua
<DIR>/builtin/init.lua
<DIR>/builtin/init.lua
<DIR>/mods/gauges/init.lua
<DIR>/mods/worldeditttt/worldedit/init.lua
<DIR>/mods/worldeditttt/worldedit_commands/init.lua
<DIR>/games/minetest_game/mods/sfinv/init.lua
<DIR>/games/minetest_game/mods/sethome/init.lua
<DIR>/games/minetest_game/mods/screwdriver/init.lua
<DIR>/games/minetest_game/mods/player_api/init.lua
<DIR>/games/minetest_game/mods/default/init.lua
<DIR>/mods/quest_chest/init.lua
<DIR>/mods/lualandmg/init.lua
<DIR>/games/minetest_game/mods/xpanes/init.lua
<DIR>/games/minetest_game/mods/walls/init.lua
<DIR>/games/minetest_game/mods/vessels/init.lua
<DIR>/games/minetest_game/mods/fireflies/init.lua
<DIR>/games/minetest_game/mods/stairs/init.lua
<DIR>/mods/lab/init.lua
<DIR>/mods/darkage/init.lua
<DIR>/games/minetest_game/mods/give_initial_stuff/init.lua
<DIR>/games/minetest_game/mods/flowers/init.lua
<DIR>/games/minetest_game/mods/butterflies/init.lua
<DIR>/games/minetest_game/mods/fire/init.lua
<DIR>/games/minetest_game/mods/tnt/init.lua
<DIR>/games/minetest_game/mods/dungeon_loot/init.lua
<DIR>/games/minetest_game/mods/doors/init.lua
<DIR>/games/minetest_game/mods/creative/init.lua
<DIR>/games/minetest_game/mods/binoculars/init.lua
<DIR>/games/minetest_game/mods/carts/init.lua
<DIR>/games/minetest_game/mods/bucket/init.lua
<DIR>/games/minetest_game/mods/bones/init.lua
<DIR>/games/minetest_game/mods/boats/init.lua
<DIR>/games/minetest_game/mods/game_commands/init.lua
<DIR>/games/minetest_game/mods/dye/init.lua
<DIR>/games/minetest_game/mods/wool/init.lua
<DIR>/games/minetest_game/mods/farming/init.lua
<DIR>/mods/unified_inventory/init.lua
<DIR>/mods/farming_plus/init.lua
<DIR>/mods/farbows/init.lua
<DIR>/games/minetest_game/mods/beds/init.lua
<DIR>/games/minetest_game/mods/spawn/init.lua
<DIR>/games/minetest_game/mods/map/init.lua
```

benrob0329:

> Wow, our mod loading order is (-trash-) nonexistent. It should be:
>
> Builtin
> Game-Provided Mods (and game-mod overrides like farming_redo)
> User-Provided Mods
>
> Anything else doesn't make sense.

**Comment by SmallJoker** [comment]
As long the dependencies are handled properly I don't see an issue at all. Nobody said that game mods load first - it's based on your assumptions. Supporting @rubenwardy's opinion.

**Comment by paramat** [comment]
> Because it just doesn't make sense that an user mod can load before any game mod.

I can see why it may seem more logical to have game mods load first, but there's no practical benefit to it, none had been stated, and it would make the system less flexible as in my example.
What has priority is mods loading in the order dictated by dependencies, whether that is a weird order or not.

**Comment by Wuzzy2** [comment]
Eh, whatever. I think you are right, it might not be important after all. I basically just reposted a complaint from another user (see above). But thanks for your thoughts.

**Comment by LoneWolfHT** [comment]
What about allowing mods to depend upon games?
