### ISSUE TITLE
Night sky is incredibly bright with a very high display_gamma

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#8938]
##### Minetest version

```
Latest 5.1.0-dev at the time of creating this issue
```

##### Summary

Here's a scene at midnight with `display_gamma = 10`, `view_range = 200`:
![screenshot_20190916_072015](https://user-images.githubusercontent.com/36130650/64930935-7ac29080-d852-11e9-80ee-d15c1f966826.png)

Notice that the sky is incredibly bright; I'd say this is as bright as a midday sky.

This isn't a recent regression - I've been noticing this from right around 5.0.0-dev, IIRC (maybe related to the 5.0.0 light curve adjustments?). I tried to fix this myself, but I just wasn't getting anywhere. So, I thought I'd file a bug report.

The screenshot was taken with `enable_shaders = false`, but the setting doesn't seem to noticeably affect the insane brightness much.

##### Steps to reproduce

- Set a very high `display_gamma` (e.g. 10)
- Set time to midnight (I think), using `/time 0000`
- Observe that the sky is horribly bright

**Comment by ClobberXD** [comment]
![screenshot_20190916_071706](https://user-images.githubusercontent.com/36130650/64930854-012aa280-d852-11e9-99e2-45ff935b4c81.png)

Here's the same scene with `display_gamma = 2`, for comparison.

**Comment by LoneWolfHT** [comment]
It came with the new light changes IIRC. It's a pain. I have to keep my gamma incredibly low if I want to see stars at night

**Comment by ClobberXD** [comment]
> I have to keep my gamma incredibly low if I want to see stars at night

Gamma is the reason I don't stars at all? That didn't occur to me - I'll try lowering it even further, bc I can't see any stars, even at `display_gamma = 2` (screenshot above).

I still do suspect that they aren't even being drawn, but I'll look into it later.

**Comment by ClobberXD** [comment]
I've observed this - while the upper bounds of the brightness stays intact, the lower bounds of brightness increases as `display_gamma` is increased. This can be observed by increasing the setting in steps of 0.5, especially at the lower end of the range. When gamma tends towards 1 and 1.5, the midnight sky would resemble dawn, more or less. Gamma of 2 and higher just keeps brightening the sky, until a value of 10 makes the sky as bright as the midday sky.

Here are a couple more screenshots:

- `display_gamma = 0.5` (yay, stars :D)

  ![screenshot_20190916_101926](https://user-images.githubusercontent.com/36130650/64936205-63939b00-d872-11e9-9236-cc00664e9b59.png)

- `display_gamma = 1`

  ![screenshot_20190916_102337](https://user-images.githubusercontent.com/36130650/64936207-63939b00-d872-11e9-85d4-44445471d247.png)

- `display_gamma = 1.5`

  ![screenshot_20190916_102504](https://user-images.githubusercontent.com/36130650/64936208-63939b00-d872-11e9-9ea5-752516b03e41.png)

Notice that the stars are visible at 1.5, albeit very faintly. Stars become completely invisible at `display_gamma = 2` (screenshot in a previous comment).

**Comment by style-nine** [comment]
I find messing with gamma is not very satisfying, myself. Here are the settings I generally use:

```
display_gamma = 1.0
lighting_boost = 0.3
lighting_boost_center = 0.4

```

**Comment by paramat** [comment]
It's not a bug. Gamma = 10 was intentionally chosen to be an extremely high value so this is not surprising.
The issue is that the differences in visual brightness between the low light levels is very small, so there is very little contrast for gamma to boost.

As discussed already, 'lighting_alpha' must be increased to add contrast between the low light levels, then increase 'gamma' by a moderate amount. 'Gamma' alone cannot be used to see in dark areas.
See https://github.com/minetest/minetest/pull/8618#issuecomment-506002635 onwards, which was in your own PR.

**Comment by ClobberXD** [comment]
> As discussed already, 'lighting_alpha' must be increased to add contrast between the low light levels, then increase gamma by a moderate amount. Gamma alone cannot be used to see in dark areas.
> See #8618 (comment) onwards, which was in your own PR.

I do use `lighting_alpha` (although I doubt I'm using it correctly). I created this issue because I thought the bright sky is a bug. But if you say it isn't, then I suppose this issue can be closed. Thanks for elaborating.
