### ISSUE TITLE
Attachment position is ignored by eye position

### ISSUE THREAD

**Issue by Zeg9** [minetest/minetest#894]
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1555
The position argument seems to be ignored when a player is attached to an entity (the player is always at the middle of the entity).
It works when an entity is attached to another, but when the parent disappears, the children is reset to the parent's position, ignoring the position argument again.

**Comment by stujones11** [comment]
This may still be relevant, there certainly are still problems with bone attachment in general.
See also #2813

**Comment by PilzAdam** [comment]
IIRC the position parameter is not in normal nodes units, but in 1/10ths (i.e. BS based).

**Comment by stujones11** [comment]
> IIRC the position parameter is not in normal nodes units, but in 1/10ths

That seems to be correct, this is probably not related to the problem I have reported.

**Comment by paramat** [comment]
I think this is worth considering.

**Comment by DS-Minetest** [comment]
The link in the first comment is outdated, so here's a permalink:
https://github.com/minetest/minetest/blob/d470842e8e223626147b14fa0373a1736c9a9df6/doc/lua_api.txt#L1555-L1558
Permalink to new `lua_api.txt`:
https://github.com/minetest/minetest/blob/7d7ccf5c0f3d8689519629282d72b1fea8f4bf30/doc/lua_api.txt#L5024-L5027

**Comment by SmallJoker** [comment]
Seems pretty much outdated. Please ask for reopening if after all this issue still persists.
