### ISSUE TITLE
find_nodes_with_meta may return nodes with empty metadata

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#8943]
##### Minetest version
```
Minetest 5.1.0-dev-1499a28b (Linux)
```

##### Summary
`find_nodes_with_meta` may return the position of nodes that have empty metadata.
It should treat nodes without meta and nodes with empty meta identically.

##### Steps to reproduce
0. Install WorldEdit
1. Select single air node
2. `//luatransform core.get_meta(pos):from_table({})` to set the metadata to empty
3. Run `//luatransform print(dump(minetest.find_nodes_with_meta(pos, pos)))`
4. Observe how a single pos appears in console, despite that node having empty metadata

Note this also works with `core.get_meta(pos):from_table(nil)`, it's impossible to truly delete the metadata of a node.

**Comment by Ekdohibs** [comment]
For me, this is a bug with metadata storage and not `find_nodes_with_meta`, since we don't want nodes with empty metadata to stay around with no metadata, as it increases mapblock size and memory use.

**Comment by BuckarooBanzay** [comment]
Can confirm, still happens with the latest version (https://github.com/minetest/minetest/commit/627c22c36e32185d48d2faf8197e22cbaa4c50b2)

Is there a workaround for this? Other than checking _every_ returned position for metadata?
