### ISSUE TITLE
'keymap_forward = KEY_RBUTTON' doesn't work

### ISSUE THREAD

**Issue by BlueMax** [minetest/minetest#8946]
##### Minetest version

```
Minetest 5.0.1 (Linux)
```

##### OS / Hardware

Operating system: ArchLinux

##### Summary

Right mouse button cannot be assigned to 'move forward'.

##### Steps to reproduce

The in-game 'change keys' menu doesn't allow to set the right mouse button at all. 
Setting `keymap_forward = KEY_RBUTTON` in `minetest.conf` shows up successfully in the `changing keys` menu but in-game the RMB doesn't react.

Moving forward by RMB is a traditional setup from early DOS times.

**Comment by sfan5** [comment]
PR #8946

**Comment by paramat** [comment]
sfan5 did you mean to link to something else? =)

**Comment by ClobberXD** [comment]
@BlueMax Binding mouse buttons like normal keys isn't possible at the moment. There's an open PR (#7924), that adds support for binding actions to mouse buttons, and also binding the dig and place actions to non-mouse buttons.

**Comment by jastevenson303** [comment]
>Moving forward by RMB is a traditional setup from early DOS times.

Can confirm.  It was my first mouse binding in Doom in '94.

**Comment by BlueMax** [comment]
> There's an open PR (#7924), that adds support for binding actions to mouse buttons

Just tested quickly but works properly so far. Thanks! Closing here.

**Comment by ClobberXD** [comment]
> Just tested quickly but works properly so far

Glad to hear it works for you too. It just fixed it a few hours back, and slept for the night. I'm yet to announce that it works. :)

**Comment by paramat** [comment]
Issue should be kept open until merge.
