### ISSUE TITLE
Change default font

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8948]
## Problem

The default font for Minetest is not very good.

1) It's rather small

2) Its style doesn't fit Minetest well

## Solutions

1) Increase the font size

2) Pixely Monospace font

## Justification

A small font size is not only hard to read for some people (making it an accessibility problem), it also leads to bad UI designs. Because usually, the UI design just assumes the default font is used. Making the font larger as the user will likely break things.

Having a larger font will also force UI designers to adapt, be more generous with space and not just cram everything into the smallest possible space.

IMO there is no good reason why the default font is so small. It's just the first font that was arbitrarily chosen years ago, maybe it's even unchanged since the very beginning of Minetest. That alone should be a very strong reason to review the current font situation.

Monospace is better because it fits Minetest better in general. Minetest is built on low-res graphics and most games feature low-res, “pixelated” textures. So a font in the same, pixely style just makes a lot of sense.

## Alternatives

Currently, users can change the font themselves. But asking users to change the font client-wise is not a good solution because most UIs (including Minetest's) are not prepared for a font change, let alone a larger font. While the user can probably shrink the font without problem, increasing it in size will probably fail. I doubt that anyone wants to make the font even smaller.

There's also a partial alternative: https://github.com/minetest/minetest/issues/5105

I say it's partial because it doesn't care about the main menu font. Its a good proposal, but not a full alternative.

## Additional context

Increasing the font size will likely break a lot of the UI in Minetest. This means some UIs need a redesign. UIs that are very crammed will definitely crammed, but those UIs were doomed anyway. Minetest has a lot of issues in the UI, especially in the main menu. And many issues stem from simply cramming too many things into tiny spaces, which is a direct result of having a small font. Thus, I believe improving the font will be an important first step.

This issue should not be viewed in isolation, but in consideration with <https://github.com/minetest/minetest/issues/6733>. A good main menu also absolutely must have a proper font.

**Comment by Wuzzy2** [comment]
I take back my suggestion about monospace. Thinking about it, the font really doesn't have to be monospace. Monospace is required for the chat, but otherwise, I think my monospace idea was dumb. What I actually want is “pixel / blocky / low-res style”.

---------

I have experimented with custom font settings and the libre (CC BY-SA 3.0) font Minecraftia 2.0 (https://www.urbanfonts.com/fonts/Minecraftia_2_0.font) a bit. This is the result:

BEFORE:
https://satoshiupload.com/images/oWl2VX6luw.png

AFTER:
https://satoshiupload.com/i/PaoHrKhs3q

MAIN MENU:
https://satoshiupload.com/images/b4XBEkHg8p.png

IMO this looks much more beautiful and is so much more appropriate for the game. Is the idea “stolen” from Minecraft? YES, absolutely. I don't deny that. But this is just one thing that Minecraft just does absolutely right. The different font makes such a huge difference.

Font settings used:

- `font_path=/path/to/Minecraftia.ttf`
- `font_size=16`
- `font_shadow=2`
- `font_shadow_alpha=63`

The font is much larger than the default. As I predicted, some UIs broke. For example, the Esc menu can no longe fit in the full text for the exit button. Texts in the loading screen also overlap, and various other things. My MCL2 is affected, too.

I personally like Minecraftia, but I cannot recommend it. It sadly doesn't support many characters, and there are some mistakes in the font (for example, quotation marks go the wrong way). So some digging has to be done to find the “perfect” font. I just picked it for demonstration purposes.

**Comment by SmallJoker** [comment]
> AFTER:
https://satoshiupload.com/i/PaoHrKhs3q

@Wuzzy2 This looks (no joke) better to me. I can understand you like pixel fonts for voxel games, but it makes the text harder to read.

**Comment by paramat** [comment]
The current default font seems well sized and doesn't seem small. It's big enough for the large majority of users.
> A small font size is not only hard to read for some people (making it an accessibility problem)

The default font cannot be made large enough for all users, because this would lead to it being far too large for the large majority of users. Those with sight problems should increase the size to what they require. So this is not an argument.
> It's just the first font that was arbitrarily chosen years ago

You don't know that =) i expect it was fairly carefully chosen, it seems very well chosen to me.
> Increasing the font size will likely break a lot of the UI in Minetest. This means some UIs need a redesign.

So i assume you are suggesting that any broken UI is redesigned before a font change is made.

The non-pixelated font is easier on the eyes and easier to read. It has the advantage of preserving readability at lower font sizes, which is an extremely helpful benefit, so readability is far more important than pixelation.
The current font doesn't seem unsuitable in style, the rest of the structure of formspecs is high-res and non-pixelated, so a non-pixelated font seems consistent with formspecs.

**Comment by benrob0329** [comment]
I feel like we could push for a "retro" aesthetic without using a pixelated font, perhaps using something which emulates the look of old terminal fonts. Or even better, let games ship a font to be used so that they can each use an theme the UI to what is needed.

**Comment by Wuzzy2** [comment]
> Those with sight problems should increase the size to what they require. So this is not an argument.

Except that you can increase the font up to only so much. Eventually you reach a point at which the text bleeds out of all sorts of widgets. And that point is very early. There's not a lot of leeway. A lot of the main menu is assuming the default font size. Increase it just a little bit, and everything breaks.

> I feel like we could push for a "retro" aesthetic without using a pixelated font, perhaps using something which emulates the look of old terminal fonts. Or even better, let games ship a font to be used so that they can each use an theme the UI to what is needed.

Yeah. My issue is mostly about aesthetics. This is my main concern here. We already have an issue about game-specific fonts, however.

> The current font doesn't seem unsuitable in style, the rest of the structure of formspecs is high-res and non-pixelated, so a non-pixelated font seems consistent with formspecs.

Formspecs look horrible, too. :-) So that's just an excuse. Font style should not be viewed in isolation.

**Comment by Calinou** [comment]
> Using the default game window size (considered a minimum size) of 1024x600, the font looks about as large as it can be. The default font should be suitable for the default game window size.
It is better that those who use a large game window increase their font size.

The font size should increase automatically as the window size increases then :slightly_smiling_face:

**Comment by rubenwardy** [comment]
I challenge your assumption that most users can't achieve 1080p, and also say that it's better to require those that play with potato hardware to turn off settings and fiddle with the config than to reduce the experience of those with less than average hardware or above.

They shouldn't need to do that, however, as the font size should scale with the rest of the GUI. As a last resort, it should also resort to reducing the font size on elements like buttons to completely fit

**Comment by NathanSalapat** [comment]
I realize I'm not most players, but I usually play at 2560x1440. That said I've never been bothered by the font size at all.

**Comment by paramat** [comment]
> The font size should increase automatically as the window size increases then

I agree. But my point is still valid because it is for how MT is now.
> I challenge your assumption that most users can't achieve 1080p,

I challenge your assumption they can, but it's probably close, i expect it is a large minority.
Anyway, my main point is that game window size affects whether someone thinks the text is too small.
> it's better to require those that play with potato hardware to turn off settings and fiddle with the config than to reduce the experience of those with less than average hardware or above.

I agree, but that misrepresents my argument, i was not writing about potato hardware.

**Comment by random-geek** [comment]
I agree that the current font seems kind of bland and not really appropriate for a voxel game, and I have thought that since I started playing MT some years ago. For comparison, look at these fonts from OpenTTD and RCT2:

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/OpenTTD-1.1.0-en.jpg/1200px-OpenTTD-1.1.0-en.jpg) ![RCT2](https://www.themeparkreview.com/forum/files/scr38_36.bmp)

Both of these fonts are pixelated and retro-looking without being as obvious about it as Minecraft. I think something like this could look quite nice and also help MT establish more of an aesthetic.

**Comment by paramat** [comment]
Labelling this as supported but only in terms of rubenwardy's suggestion:
> the font size should scale with the rest of the GUI

The original suggesiton of a fixed larger font is impractical and long-term unsupported.
