### ISSUE TITLE
Item on_place not called when rightclicking entity

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#8950]
##### Minetest version
```
Minetest 5.1.0-dev-4271889e (Linux)
```

##### Summary
`on_place` is not called when rightclicking on an entity.
Left-click (via `on_use`) works so this is definitely a bug.

##### Steps to reproduce
1. Create a tool that logs on_place invocations
e.g. `//lua core.override_item("default:axe_mese", {on_place = function() core.chat_send_all("on_place") end})`
2. Rightclick an entity
3. Observe how nothing happens

**Comment by DS-Minetest** [comment]
I wonder if it would be better calling `on_secondary_use` instead of `on_place`.

**Comment by DS-Minetest** [comment]
Tested.
Neither an entity's `on_punch` nor a node's `on_punch` is called if you punch it with an item that has an `on_use`. Hence the `on_use` is special.

**Comment by SmallJoker** [comment]
```
2019-09-19 20:25:22: ACTION[Server]: singleplayer right-clicks object 13: LuaEntitySAO at (101.383,8.5,-64.9)
2019-09-19 20:25:23: ACTION[Server]: singleplayer right-clicks object 13: LuaEntitySAO at (101.383,8.5,-64.9)
```
Seems to be an old bug. Removing milestone again.

**Comment by sfan5** [comment]
Yes, this is not a regression. Still technically a bug since the non-functionality with entities is not documented.
