### ISSUE TITLE
Item in inventory list 'hand' can appear in list 'main'

### ISSUE THREAD

**Issue by NetherEran** [minetest/minetest#8953]
##### Minetest version

```
Minetest 5.1.0-dev-c413eeb-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Linux Mint 19.1
CPU: Intel© Core™ i5-7300HQ CPU @ 2.50GHz × 4

GPU model:
OpenGL version:

##### Summary

The item in the inventory list 'hand' can end up in the main list when breaking a node.

##### Steps to reproduce

1. Install the attached hand_test mod in a world with minimal game.
2. Break a node bare handed.
3. The hand item should appear in the inventory.
[hand_test.zip](https://github.com/minetest/minetest/files/3630165/hand_test.zip)

**Comment by Wuzzy2** [comment]
Yes. player hands appear to be very buggy in -dev. This is a serious regression.

Here's my separate bug report:

--------------

Minetest version

4271889ef832806e7bd57e552f15b24fdf162c8d

(5.1.0-dev)
Summary

Custom player hands appear to be very buggy in 5.1.0-dev.

If a custom player hand was set in the special "hand" inventory list, player:get_wielded_item returns the “hand item” and not "".

If you dig a node with an empty hand, the hand item will appear in said inventory slot.

If you use the place key with the empty hand, it will be attempted to be placed.
Steps to reproduce

Test with MineClone 2 (dfe68e6820d3f7554edcafcab8314ab7add7a23a). MCL2 registers “mesh hands” in mcl_meshhand. These are actually meshnodes, so the wieldhand can be a mesh (there seems to be no other way to use a mesh as wieldhand). It works fine in 5.0.1 and broke in the specified Minetest dev version.

Dig a node with empty hand.

Place the empty hand (it should be impossible). mcl_meshhand detects when the fake nodes are placed and immediately deletes it and prints an error.

Select the empty hand. The mod show_wielded_item always displays the wielded item. When hand is selected, nothing should be shown, but it does show something. Another error.

Compare the behaviour specified Minetest dev version with stable 5.0.1.

You will experience similar problems in the game "The End".

**Comment by sfan5** [comment]
bisected to e462a9a5ef46776d974203bb44e0b89e8c980b29
@SmallJoker

**Comment by DS-Minetest** [comment]
FYI, here are the two places where the "hand" list is accessed:
https://github.com/minetest/minetest/blob/5c9983400fb085167bf11f8a0483b8e8f6dd8a24/src/client/client.cpp#L1358
https://github.com/minetest/minetest/blob/5c9983400fb085167bf11f8a0483b8e8f6dd8a24/src/player.cpp#L104
`get_wield_item` returns the "hand" item as fallback and `core.node_dig` sets this item as wielded item:
https://github.com/minetest/minetest/blob/8e757859d6a6bf6482480904e8485e9344e567ab/builtin/game/item.lua#L579
And like this the "" item turned into the item in "hand".

**Comment by SmallJoker** [comment]
Does `set_wielded_item` refer to `hand` or to the selected `main` ItemStack?

**Comment by DS-Minetest** [comment]
I think it should update the `main` ItemStack only if the `main` ItemStack wasn't empty.

**Comment by sfan5** [comment]
`get_wielded_item` and `set_wielded_item` should only ever refer to the selected `main` item, anything else would be confusing and can introduce problems to existing mods.

**Comment by paramat** [comment]
The current custom hand appearence implementation seems sloppy and is problematic, i think there must be a better way, as discussed in #8866
