### ISSUE TITLE
Game-specified player.png and player_back.png are ignored (engine textures override mod/game textures)

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8955]
##### Minetest version

```
4271889ef832806e7bd57e552f15b24fdf162c8d-->
```

##### Summary

Game-specified `player.png` and `player_back.png` is ignored. Instead, these images are *always* the “ugly green thing with hat” images, no matter what you do.

Note these images are included in `textures/base/pack`

This is a regression compared to 5.0.1.

##### Steps to reproduce

* Disable the currently active texture pack (EDIT: added by SmallJoker)
* Create an empty dummy game
* Add a dummy mod which includes `player.png` and `player_back.png`
* Start game and change camera mode to see yourself

EXPECTED: You see your custom player images.
ACTUAL: You see the default player images (ugly green thing with hat).

##### Notifications

@paramat

**Comment by sfan5** [comment]
bug was l ikely introduced with #8823

**Comment by Wuzzy2** [comment]
My suspicion:

*ALL* files in the core texture pack currently overwrite the game-specified files, instead of the other way round. And this (unproven) bug never appeared so far because most core textures are not overwritten by games. And when `player.png` and `player_back.png` were added, the bug suddenly manifested itself.

So, reverting the commit will probably fix this particular bug number 8955, but not the more deeply underlying (suspected) issue.

My suspicious is untested.

**Comment by paramat** [comment]
Yes, this is the bug that was noticed recently in another issue, and of course my PR then causes a problem, feel free to revert.

**Comment by paramat** [comment]
Well, either revert or fix the underlying issue for 5.1.0.

**Comment by SmallJoker** [comment]
Tested with current master (fec30e3)

Tested several cases where the texture is provided by different parts:
 - [x] Textures provided by nothing -> Texture pack is used
 - [x] Only provided by game -> Texture pack is used
 - [x] Provided by game and mod -> same
 - [x] Only provided by mod -> Texture pack is used

Cannot reproduce.

**Comment by paramat** [comment]
Bug reproduced for 'player.png' in MTG player_api mod.
Maybe it's only certain textures?
