### ISSUE TITLE
Standardize usage of newlines in item descriptions [discuss]

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8956]
## Problem

Various mods, including those in MTG, have started using newlines in the item `description`s.

Other mods frequently parse the `description` to display it somewhere. Frequently these mods have a hiccup when a description has a newline because the interface doesn't support newlines (e.g. inside a list). This is usually an easy fix (delete everything after the 1st newline), but this frequently catches modders by surprise.

Also, the documentation is completely silent about the topic of newlines in descriptions. How should mods handle them? How should they be parsed? Etc. It's all not defined.

## Solutions

Let's discuss on how newlines shall be treated **as convention** in item descriptions.

This is not a feature request, more a policy discussion that should later result in a documentatino change.

### My proposal

This is basically based on what I have done *de facto* in my mods. Most mods already follow these guidelines (more or less), so what I write down is almost a *de facto* standard. MTG seems to follow it 100%

I split this in two parts: The description provider (the mod that adds the item) and the description user (e.g. a mod that parses the description to display it in a formspec). Both have to follow different rules.

#### Description provider:

First, it is *explicitly allowed* to use newlines in descriptions (this is not mentioned in the docs yet).

Second: The first line is supposed to contain the most important information about the item, stuff that is required to identify the item and keep it apart from other items. Additional, non-essential info can be moved into additional lines. If everything but the 1st line is removed, the item must still be identifiable.

Second: The translation symbols must not span over multiple newlines. Instead, each line must also start a new translation symbol.

Wrong example:

```description = S("Cart\n(Punch to collect)")```

Good example:
```description = S("Cart").."\n"..S(Punch to collect)")```

That way, the string can be trimmed safely without breaking translations (I tested).

Third: Only use `\n` as newline character.

#### Description user

When displaying the description anywhere, the possibility that the itemstring contains newlines MUST be considered. If trying to display it anywhere that does not support multiple lines (for example, in a list entry), everything after the first newline including the newline must be removed, so that only the first line remains.

## Alternatives

My proposal are only guidelines. No code will be written for this, it's 100% convention only.

Theoretically, games could ignore all this and enforce their own guidelines or none at all, but I think it's good there is a global recommended guideline to fall back to.

Another alternative would be to provide some utility functions and tell modders to use these.

## Additional context

Similar issue: https://github.com/minetest/minetest/pull/8752

**Comment by style-nine** [comment]
So, infotext is being injected into descriptions? Doesn't that seem a little redundant?

**Comment by Wuzzy2** [comment]
What are you talking about? Nothing being is injected anywhere.

**Comment by rubenwardy** [comment]
I'd like both of these things to be solved at the same by:

* description is a full multi-line label
* short_description is created automatically from the first line of the description, but may be explicitly designed if wished

This means that mods that need a short description won't need to mess around with :sub() etc, but can use short_description directly

**Comment by Wuzzy2** [comment]
That sounds like a nice solution to me. Much more straightforward. :+1:

**Comment by Linuxdirk** [comment]
Why not have a name and a description? The name is a single-line string and the description is a string of whatever the mod author likes. Inventories get an adoption to define what to show, i.e. only the name, or only the description, or both.

**Comment by paramat** [comment]
Related PR #8980 merged.

**Comment by Wuzzy2** [comment]
I consider this PR to do the job of standardization. Good job!

Closing ...
