### ISSUE TITLE
Formspec: Add font styles (family, size, weight)

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#8962]
I propose to add a support for modifying of text, that is a selection of varieties of font, size and etc.

I think it can be made with the styling feature and enabling new parameters in next elements where a text can be used: 

* label/vert_label
* button/button_exit
* field/pwd_field
* tabheader
* textarea

For example, `style[button;font=<font_type>;size=<num>]`

Types of text font may used such: straight, cursive, normal, highlight (default to straight, let say, size to 1).

**Comment by Andrey2470T** [comment]
May it be added for 5.2 as it's too late for 5.1?

**Comment by DS-Minetest** [comment]
Related: #6488

**Comment by Andrey2470T** [comment]
I`m closing the issue as there is already a corresponding PR for that: #9763
