### ISSUE TITLE
/setpassword writes legacy password hash

### ISSUE THREAD

**Issue by tuedel** [minetest/minetest#8965]
##### Minetest version
```
5.1.0-dev
```
@ https://github.com/minetest/minetest/commit/47da640d7763ee1e00badb7476ac5afc4f864367 (Current HEAD)

##### OS / Hardware

Operating system: Arch Linux
CPU: Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

##### Summary
Currently the `/setpassword` chat command still stores the password using the deprecated SHA-1 format (and not SRP). This surely isn't the intended behavior.

##### Steps to reproduce
1. Create a new world and grant yourself the `password` privilege.
2. Use `/setpassword <player> <password>` to set a new password for any player (new or existing).
3. Inspect the data stored in the auth backend.

**Comment by SmallJoker** [comment]
The legacy password will be supported for quite a while for old maps, but the culprit is here:
https://github.com/minetest/minetest/blob/47da640d7763ee1e00badb7476ac5afc4f864367/src/script/lua_api/l_util.cpp#L215-L224

Code from `check_password_entry` should be used there to generate an SRP hash.

**Comment by Ekdohibs** [comment]
The chat command being sent to the server and processed there means that the password is transferred in clear on the network, and avoiding that was the whole point of SRP.

**Comment by tuedel** [comment]
> The chat command being sent to the server and processed there means that the password is transferred in clear on the network, and avoiding that was the whole point of SRP.

You're right, it looks like this the actual issue here.

Opened #8982, and closing this.
