### ISSUE TITLE
Item entities can slide on nodes with over-height collisionbox

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#8967]
##### Minetest version
`Minetest 5.1.0-dev (Linux)`
5c9983400fb085167bf11f8a0483b8e8f6dd8a24

##### Summary
When dropped onto certain nodes, the item entities' velocity is not reset when touching and it continues to slide on it.
Affected are:
* Fences, Fence Rails (if `enable_fence_tall = true`)
* Walls

##### Steps to reproduce
1. Place one of the affected nodes
2. Drop item while standing on that node
3. Observe how it slides until it falls off
![output](https://user-images.githubusercontent.com/1042418/65350918-1a7f7600-dbe7-11e9-81b8-7eac3f981f30.gif)

**Comment by SmallJoker** [comment]
Useful API function:
`ObjectRef:get_last_collision_pos() -> nil/vector`

**Comment by sfan5** [comment]
see also: #3918

**Comment by Wuzzy2** [comment]
More information:

As of 5.1.0, it happens when:

* The upper Y is >= 0.5625 (equivalent to `param2 >= 68` for leveled nodeboxes)
