### ISSUE TITLE
guiFormSpecMenu.cpp clang compiler warnings

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#8968]
##### Minetest version

```
5.1.0-dev-388c1420 (Linux)
```

##### OS / Hardware

Operating system: lubuntu
CPU: intel

##### Summary

I use clang as compiler and get lots of `overrides a member function but is not marked 'override' [-Winconsistent-missing-override]` warnings.
https://pastebin.com/raw/DJsT1kF5

**Comment by SmallJoker** [comment]
#8957
