### ISSUE TITLE
Rename "PM" to "Message" or similar

### ISSUE THREAD

**Issue by archfan7411** [minetest/minetest#8970]
## Problem

When a player receives a message sent with `/msg`, it is displayed as `"PM from <user>: <content>."`
"Private message" is a misleading name for this, as PMs are logged prominently in debug.txt. It's debatable how important this issue is, but in extreme cases one could even encounter legal issues for looking at these "private" messages while scrolling through debug.txt (citation needed, I'm not a European and much less a lawyer.)

## Solutions

- Rename "PM" to "Message" or "Direct Message"

## Alternatives

- Not logging PMs at all, or letting players agree to disclose their PMs (inadvisable, because the messages are invaluable for moderation.)

**Comment by SmallJoker** [comment]
They're logged so that server admins can ban players who abuse this feature.

**Comment by rubenwardy** [comment]
I support this. The command is already "msg"

**Comment by paramat** [comment]
:+1:
