### ISSUE TITLE
Predictable cloud perlin noise.

### ISSUE THREAD

**Issue by DevyHeavy** [minetest/minetest#8972]
Hello,

I am working on a dynamic weather system for my Minetest game but have run across an issue, let me go through the steps to where I am.

I want to make it rain over the player whenever the Minetest generated clouds are over the player, or if the player is at least close enough to where there are rain clouds. I figured that the clouds are placed/generated using some kind of noise, and I am correct (I think) looking [here](https://github.com/minetest/minetest/blob/539f016c1b1a706da2c113435ec60bb39c868f4b/src/client/clouds.cpp#L378). Simple enough, density and the input position can probably be figured out to calculate. The hard part is the seed used [here.](https://github.com/minetest/minetest/blob/539f016c1b1a706da2c113435ec60bb39c868f4b/src/client/clouds.cpp#L48) I figured out this gets started in game.cpp right [here](https://github.com/minetest/minetest/blob/fec30e37ac1d160a942777b05a7717b5395c4d99/src/client/game.cpp#L1334). The seed comes from `time(0)` which should be the system time when the function is called.

Reproducing that seed in a mod should be next to impossible, correct?

If my above assumptions are right, would it be possible to just use some constant seed that doesn't change? Would this affect anything in a bad way? Do you think it would work for my mod?

I'm not asking about if my mod should make sacrifices for performance by just making it rain everywhere when it gets "rainy out," there are mods that already do that.

Thank you for your time!

**Comment by SmallJoker** [comment]
Even though you could use the correct seed in your mod, due to `time(0)` which is taken locally, the rain won't be showing up at the right location on multiplayer servers.
Currently there's no way to predict the position of the clouds.

**Comment by DevyHeavy** [comment]
You're saying that 'time(0)' is dictating the position of the clouds somewhere other than for the seed, correct? I'll look again but if don't mind pointing me to that line(s) that would be nice.

**Comment by SmallJoker** [comment]
@DevyHeavy No, `time(0)` is the seed of your clouds. But clouds and modding are entirely unrelated; the server doesn't do anything cloud-related. What you pointed out in the first post is entirely client-side:
Initialize seed:
https://github.com/minetest/minetest/blob/fec30e37ac1d160a942777b05a7717b5395c4d99/src/client/game.cpp#L1334
Get clouds for position ...:
https://github.com/minetest/minetest/blob/539f016c1b1a706da2c113435ec60bb39c868f4b/src/client/clouds.cpp#L378-L381
whereas position consists of the moving origin:
https://github.com/minetest/minetest/blob/539f016c1b1a706da2c113435ec60bb39c868f4b/src/client/clouds.cpp#L340

The client step happens each drawn frame.

**Comment by paramat** [comment]
Reproducable cloud noise would be good to have if possible But if it depends on each client's frame 'dtime' values i'm not sure it could stay reliably in sync.

**Comment by BluebirdGreycoat** [comment]
Just leaving this note here: couldn't the server send the cloud 'dtime' value the same way it already tells clients the time of day?
