### ISSUE TITLE
Example world.mt files

### ISSUE THREAD

**Issue by bkmgit** [minetest/minetest#8973]
## Problem

When using a Postgres database, configuration is given in world.mt

The [wiki documentation](https://wiki.minetest.net/Database_backends#world.mt_for_PostgreSQL) is vague on how the contents of this file should be formatted.

## Solutions

It would be helpful to have example world.mt configuration files similar to [minetest.conf.example](https://github.com/minetest/minetest/blob/master/minetest.conf.example)

## Alternatives

There is an example world.mt file [here](https://storage.googleapis.com/gctf-2019-attachments/be9c5cc1ce5796725076085ea387216bff01e2e6707ebe7f21ca82805133ff96) but there do not seem to be many other examples.

**Comment by Wuzzy2** [comment]
Ideally, `world.mt` should be documented properly in the Minetest repo. The wiki is shite on anything dev/admin related.

An example is always nice, but it should never be a *replacement* for documentation, only supplementary. I think, first and foremost, the possible key/value pairs need a proper definition first, and *then* examples be added.

Thank you for reading this.

**Comment by bkmgit** [comment]
A possible start for postgres database options

    auth_backend = postgresql
    player_backend = postgresql
    backend = postgresql
    host = localhost
    user = username 
    password = password
    dbname = databasename
