### ISSUE TITLE
Create a new function (when messages are sent)

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#8975]
## Problem

In the file `chat.lua` (inside `builtin/game`), when a player sends a message, it calls `core.register_on_chat_message`.
AFAIK, there's no way to override that call.

## Solutions

Create a new function when the message is sent (e.g.: `core.send_message`).
Then call `core.register_on_chat_message(core.send_message)`.

## Alternatives

Please post them right here.

**Comment by rubenwardy** [comment]
Use case?

Can format_chat_message solve your issue?

**Comment by Panquesito7** [comment]
➢ Can format_chat_message solve your issue?

TBH, I don’t know. I haven’t used that function.
I use MT/MTG 5.0.1. I can try to use it as well.

But, does it require to edit some other source files?

**Comment by rubenwardy** [comment]
You can override functions in the minetest global variable. Again, what's the use case?

**Comment by Panquesito7** [comment]
> Again, what's the use case?

It's for a mod I made.
And I've tried several ways, but none of them work.

**Comment by rubenwardy** [comment]
I'm asking what you're trying to do, so I have context

**Comment by Panquesito7** [comment]
I’m trying to translate some strings when messages are sent (e.g.: when a player hasn’t enough privileges).
Is this enough information?

**Comment by benrob0329** [comment]
Can't you just use the string translation API?

**Comment by Panquesito7** [comment]
> Can't you just use the string translation API?

Can you please clarify that?

**Comment by benrob0329** [comment]
Rather than trying to override a bunch of stuff, just run the string through the translation API.

No, I'm not going to go dig up the API docs and copy+paste then here. I don't even know if it'll work for your use-case because you haven't given us much of any context other than wanting to translate a string.

**Comment by Panquesito7** [comment]
> Rather than trying to override a bunch of stuff, just run the string through the translation API.

I can do that, too.

> you haven't given us much of any context other than wanting to translate a string.

This is something that I want it to be available to all players.
For example: if a player uses certain command which requires a privilege, then send it in a translated message.

To do this, I must override that call (in the mod). Then, it'll be available to all players.
Is this enough information? @rubenwardy, @benrob0329.

**Comment by rubenwardy** [comment]
register_on_chat_message is for player chat messages, and isn't called for mod sent chat messages. To translate mod sent chat messages, the only good solution is to modify the mod itself. Attempting to translate a string after it has been composed by a mod will result in issues, as it's hard to accurately pick out variables such as user names

**Comment by rubenwardy** [comment]
I would like a `minetest.send_player_chat_message` for another reason - it makes it much easier to make mods which control how messages from players are sent to other players, such as limiting them by the distance between players or adding support for ignore

**Comment by Panquesito7** [comment]
IMHO, this is getting off-topic. I'll close this.
Thanks for your comments.

**Comment by rubenwardy** [comment]
It wasn't going off topic, I was describing an actual need for what you mistakenly asked for in the original post

**Comment by Panquesito7** [comment]
Should I reopen the issue, then?

**Comment by rubenwardy** [comment]
No, it's fine to stay closed
