### ISSUE TITLE
Shader based waves with perlin noise.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#8976]
I have some code (based on #8889) that creates wave pattern from Perlin noise.

I recorded a demo here: https://youtu.be/5jHtou-DeLI
If the other members are receptive I'll file a PR.
The details can be tweaked further, I'm just looking for general receptiveness to this.

The only wrinkle is that since now waves can wary along X axis as well, the water surfaces can no longer be tiled horizontally (i.e. multiple tiles combined into one). So the following minetest-game change is necessary too:
```
diff --git a/mods/default/nodes.lua b/mods/default/nodes.lua
index cee1242..db1df7b 100644
--- a/mods/default/nodes.lua
+++ b/mods/default/nodes.lua
@@ -2191,6 +2191,7 @@ minetest.register_node("default:water_source", {
                                aspect_h = 16,
                                length = 2.0,
                        },
+                       tileable_horizontal = false,
                },
                {
                        name = "default_water_source_animated.png",
@@ -2201,6 +2202,7 @@ minetest.register_node("default:water_source", {
                                aspect_h = 16,
                                length = 2.0,
                        },
+                       tileable_horizontal = false,
                },
        },
        alpha = 160,
```

**Comment by benrob0329** [comment]
What does flowing water lool like? Currently it can go way below the surface.

**Comment by paramat** [comment]
Presumably you're using 1 octave 2D noise? Any more than 1 octave would create too much non-periodic structure. Nice how it varies in X too.

**Comment by lhofhansl** [comment]
@benrob0329 flowing water surface does the same, flowing as in "falling" does not behave that way.
@paramat yeah, just one octave. I played with the multiple octaves but came to the same conclusion, it looked less natural. And one octave is cheaper computationally too :)

**Comment by benrob0329** [comment]
Could the wave height be made so that it is a relative offset, that way you don't end up with disappearing shorelines that are a pain to see?

**Comment by lhofhansl** [comment]
Of course I also found this on youtube: https://www.youtube.com/watch?v=uz1douFQcok
(The simple perlin waves are lame in comparison)

**Comment by lhofhansl** [comment]
> Could the wave height be made so that it is a relative offset

I calibrated is so that height corresponds to the current height (for some reason 1 unit means about 1/2 node height)

**Comment by paramat** [comment]
The default in your video looks good, it's subtle enough to not notice the straight lines.

I think this is a big improvement and i'll support a PR as long as it is confirmed to not be overly intensive, i'm a little concerned about every liquid surface vertex within view range being a sample of 2D noise. I guess the noise is calculated by the graphics card/chip?

**Comment by paramat** [comment]
Is it the case that noise is sampled at each corner vertex of a liquid surface quad? So on average 1 noise sample per node?

**Comment by lhofhansl** [comment]
The noise is does in the shader, i.e. after everything is generated at the time it is rendered. The work is not much more than the previous sine waves (and fact I could not measure any performance degradation at all, but I'll test some more to be sure).
I also still want to calibrate the height and speed of the waves a bit better.

**Comment by lhofhansl** [comment]
The fact the horizontal tiling must be disabled for surface water has an effect of course, as mentioned in the description.
The engine's fast-face logic otherwise would combine 16 water tiles into 1 tile (one 16 node long tile along the x axis, 1 node depth in z-direction).
This is one reason why the current waves moves precisely in z-direction. In any other direction you'd the gaps between the tiles. If we want any other variation other than just z, we **cannot** tile, each surface water nodes needs to be its own tile.

That part does eat some cycles. With view-range of 240, and only water visible, my FPS go from 50 to 46.

**Comment by lhofhansl** [comment]
This is the visible tiling effect:
![screenshot_20190924_233401](https://user-images.githubusercontent.com/446130/65575013-af55dc80-df23-11e9-8b08-df23addb1c96.png)

You can see the long tiles mess up the logic, since they cannot be bent.

**Comment by paramat** [comment]
I see, thanks. 8% FPS loss seems acceptable, these are non-essential shaders after all so won't be used on low-powered machines.

**Comment by lhofhansl** [comment]
In this case we have to disable tiling for water in minetest game, and it cannot be done conditionally, so we'd **always** get the slowdown, whether we use shaders or these waves or not. I don't think that would be acceptable.

Lemme see if I can add conditional logic to the engine instead to override the tiling setting for water when we have the shaders and waving liquids on, but it gets hack'ish as the engine now has to know about specific node types, and shaders, etc.

In any case, lemme file a PR so the code is there to see. I was going to wait for #8889 since this would rely on some of the changes there.

**Comment by lhofhansl** [comment]
I can go by waving = 3 for a node, if that is true, and shaders are one, and waving_liquids is set, only then do not tile.

**Comment by SmallJoker** [comment]
#8994 merged
