### ISSUE TITLE
Reminder to autogenerate conf.example etc. just before 5.1.0 release

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#8983]

**Comment by SmallJoker** [comment]
Please include that in https://dev.minetest.net/Releasing_Minetest#Before_releasing, which is (at least by me) used before release to not miss anything.

**Comment by Wuzzy2** [comment]
@SmallJoker: Done.

**Comment by SmallJoker** [comment]
Thanks. Following these steps is the most reliable solution so far. I doubt issues for each release will help much, other than additional effort.

**Comment by paramat** [comment]
Nice, thanks Wuzzy2, indeed it's better to not to open issues like this.
