### ISSUE TITLE
Location for mods in a Snap Environment

### ISSUE THREAD

**Issue by edenprojectde** [minetest/minetest#8984]
##### Minetest version

```
Minetest 5.0.1 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/share/minetest"
```

##### OS / Hardware

NAME="KDE neon"
VERSION="5.16"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User Edition 5.16"
VARIANT="User Edition"
VERSION_ID="18.04"

##### Summary
I tried following the tutorial to add a mod manually(adding it in /home/$user/.minetest/clientmods/), but it seems the usual Paths don't work in a Snap Enviroment. Any hints on how to do that or should i rather try a fresh install via Git?

##### Steps to reproduce
1. Install via Snap
2. Wonder where to put mods
3. ?
4. Profit

**Comment by SmallJoker** [comment]
It's whatever Snap specifies as `HOME` environment variable.

FYI: `$HOME/.minetest/clientmods/` is probably not what you'd like to use. Install your mods to `$HOME/.minetest/mods/`. Former is for client-side only mods, whereas latter is the far more common and is used when hosting a server (includes singleplayer).

**Comment by SmallJoker** [comment]
Answered in: https://forum.minetest.net/viewtopic.php?p=357794#p357794
