### ISSUE TITLE
Formspec element "bgcolor[<some_color>;false]" does not work

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8985]
##### Minetest version
```
26b39f1eae1f576669cbf49c6db94ef4ed8624df
```

##### Summary
The formspec element `bgcolor` fails if the 2nd argument is literally `false` instead of being empty.

##### Steps to reproduce

1. Use `luacmd`
2. Use Minimal Development Test
3. In console, write: `/lua me:set_formspec_prepend("bgcolor[#FF0000FF;false]")`
4. Open your inventory menu
5. For comparison, write in console:  `/lua me:set_formspec_prepend("bgcolor[#FF0000FF]")`
6. Open your inventory menu

EXPECTED AFTER STEP 4/6:
Inner rectangle is red.

ACTUAL AFTER STEP 4:
Inner rectangle is black translucent (default formspec color).

ACTUAL AFTER STEP 6:
Inner rectangle is red.
(steps 5 and 6 were just added for comparison)

##### Notifications
@SmallJoker
@DS-Minetest

**Comment by DS-Minetest** [comment]
According to the documentation changes of #8716, `bgcolor[<some_color>;<bool>]` modifies the fullscreen color, while `bgcolor[<some_color>]` changes the non-fullscreen color.

**Comment by Wuzzy2** [comment]
That's really confusing. So the 2nd argument only can have `true` as an argument, but never `false`? This doesn't make sense.

What I expected:

* `bgcolor[<color>]` → change formspec color
* `bgcolor[<color>;false]` → change formspec color
* `bgcolor[<color>;true]` → change fullscreen color

Bascicaly, I interpreted the 2nd argument th be optional and implied to be `false`.

Currently, it's this:

* `bgcolor[<color>]` → change formspec color
* `bgcolor[<color>;false]` → do absolutely nothing (!)
* `bgcolor[<color>;true]` → change fullscreen color

**Comment by DS-Minetest** [comment]
Here's the documentation:
https://github.com/minetest/minetest/blob/26b39f1eae1f576669cbf49c6db94ef4ed8624df/doc/lua_api.txt#L2095-L2103

>     * `bgcolor[<color>;false]` → do absolutely nothing (!)

This sets the fullscreen background color to `<color>` and disables the fullscreen background color.

**Comment by Wuzzy2** [comment]
> This sets the fullscreen background color to <color> and disables the fullscreen background color.

1) This is not explicitly written in the docs.
2) So … this “setting the fullscreen background color” in `bgcolor[<color>;false]` *effectively* sounds like a no-op to me. If you set the fullscreen bg color and disable it, what's the point of setting the bg color then? You only change internal state that you cannot use, since if you add a `bgcolor` again, you overwrite the old color. Just disable the fullscreen bg color.

Is this maybe done to make it possible to disable the fullscreen color at all, if is was activated in a previous `bgcolor`?

**Comment by DS-Minetest** [comment]
>     1. This is not explicitly written in the docs.

There are two types of people:
1. The ones who can extrapolate from given information to not explicitly given information.

Note that `bgcolor[;<fullscreen>]` works, too. `<color>` is not a valid colorstring in this case.

**Comment by Wuzzy2** [comment]
It's always easy to make fun of the reader.

> * If `fullscreen` is a true value, the fullscreen background color is drawn.

Well, it could also be interpreted that if `fullscreen` is not a true value, the formspec bg is drawn instead of the fullscreen bg. In fact, it WAS interpreted as this, by me.

Please just change the sentence to:

> * If `fullscreen` is a true value, the fullscreen background color is drawn, otherwise, it's invisible.

Then there is no more room for speculation.

**Comment by rubenwardy** [comment]
The correct behaviour is to treat ;false as no parameter, and set the formspec background. This makes it consistent with the background[] element

**Comment by DS-Minetest** [comment]
#8996

**Comment by SmallJoker** [comment]
Reverted in #9018. The arguments of this element can be extended after release.
