### ISSUE TITLE
Button in Minimal fails clipping test

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8986]
##### Minetest version
```
26b39f1eae1f576669cbf49c6db94ef4ed8624df
```

##### Steps to reproduce
1. In Minimal, say `/formspec`
2. Select “Noclip” tab
3. Look at the 3rd button from the top, at the left

I expect the text on this button to be clipped.
But in reality, it is visible.

**Comment by random-geek** [comment]
Other problems:
- The item image on the third button on the left is clipped where it shouldn't be.
![image](https://user-images.githubusercontent.com/35757396/67251775-0d8fb580-f425-11e9-98fa-036228a589e5.png)
- The labels on the left-hand text boxes are wrongly clipped.
![image](https://user-images.githubusercontent.com/35757396/67251819-2dbf7480-f425-11e9-915c-4bda9657dc00.png)
- The left multiline textbox has no scrollbar (it only gets smaller if more than 3 lines of text are put in).
![image](https://user-images.githubusercontent.com/35757396/67251888-7bd47800-f425-11e9-807a-9115a94b9d2a.png)

Should this issue be edited to include those bugs as well?

**Comment by Df458** [comment]
The bugged button will be fixed in my upcoming PR (see the first point on the proposal referenced in the last comment). I actually fixed this one by accident, it's probably related to the fact that `item_image_button` is actually drawn as two separate formspec elements.
