### ISSUE TITLE
Document 'author' and 'release' settings in game.conf

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#8988]
##### Minetest version
```
5.0.0
```

##### Summary
So apparently ContentDB injects stuff into my `game.conf` and I found two new settings that I could swear were not before:

`author = <my name>`
`release = <some number>`

Neither of these values are documented in `lua_api.txt`. Please document these. Thanks.

@rubenwardy

**Comment by rubenwardy** [comment]
These are documented for mod.conf, but I forgot to document them for game.conf
