### ISSUE TITLE
GUI and font suddenly scaled up

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest#8990]
Without changing any settings, the font and GUI have somehow been messed up. I've already tried deleting the config file and building Minetest again, but nothing solves it.
Notice the scale of the items bar ingame, the menu when the Escape key is pressed, and the overlapping text with GUI stuff.

![test4](https://user-images.githubusercontent.com/49789044/65643112-c8749100-dfe8-11e9-8ada-eecb77d23158.png)
![test2](https://user-images.githubusercontent.com/49789044/65643332-67998880-dfe9-11e9-8bd8-2e9b45bfb4a2.png)
![test3](https://user-images.githubusercontent.com/49789044/65643333-67998880-dfe9-11e9-8b11-9f34bb7f823d.png)

**Comment by rubenwardy** [comment]
You posted on the wrong repo, moved it now

**Comment by An0n3m0us** [comment]
`cmake . -DBUILD_CLIENT=TRUE -DRUN_IN_PLACE=FALSE`
Minetest 5.1.0-dev-720aedb
Ubuntu Xenial 16.04

It has been working fine for a while until now. I didn't change anything at all or re-build it. Just turned it on and it was like that.

**Comment by An0n3m0us** [comment]
Fixed. I recalled that few days ago my display was messed up by an application and I forgot about that. Also, I didn't suspect that it was the cause as I reset my display using `xrandr`. Sorry for the trouble ·_·
