### ISSUE TITLE
[Suggestion] You might wanna remove MCImport and MCConvert from your forum

### ISSUE THREAD

**Issue by CHJ85** [minetest/minetest#8993]
Hi there. After trying out both MCImport and MCConvert and had very little luck, I'd suggest you guys remove those from your forum.
Looking at MCconvert's Github, that project hasen't been touched in 6 years.
Out of 15 Minecraft texture packs, I've only been successfully able to convert 1.
And MCImport was recently updated, but I haven't had much luck with that one either.
1 playable world out of about 10.

**Comment by rubenwardy** [comment]
Please reports bugs of software in the software's actual repository

* MCImport https://github.com/minetest-tools/mcimport
* I can't find a forum topic for MCConvert

**Comment by CHJ85** [comment]
Thanks for your response.

**Comment by CHJ85** [comment]
Btw I meant MCreconvert. This script does not work.
And because it hasn't been active since 6 years ago, it should be removed from the forum.
Also, reason I can't post in the forum is because it's impossible to register.
