### ISSUE TITLE
Change on_secondary_use() to be more consistent with on_use()

### ISSUE THREAD

**Issue by Cahrs** [minetest/minetest#8995]
**Rundown:** Currently the behavior of on_secondary_use() is strangely inconsistent with on_use() and is very limitating. The Problem: it only activates when the player is pointing at nothing, unlike on_use which is called no matter what your pointing at. This is very limitating because then you cant run actions on rmb via the callback without facing away from nodes, which is very un-intuitive and annoying for players. that can partly be alleviated by combining it with an on_place() callback in the item-def, but they both share a limitation: Neither will be activated if pointed_thing is an object.

**Proposal:** change on_secondary_use() to run when pressing rmb no matter what the pointed_thing is, to be consistent with on_use()

**Usecase:** my example use-case is for a mod ive been developing. in it i want players to be able to make different weapon-dependent combat-moves based on pressing lmb or rmb. Because its a weapons mod it will be used to fight objects, so the action should definitely activate when pointing at an object in this usecase.

**Comment by sfan5** [comment]
> but they both share a limitation: Neither will be activated if pointed_thing is an object.

#8950

**Comment by paramat** [comment]
> change on_secondary_use() to run when pressing rmb no matter what the pointed_thing is, to be consistent with on_use()

I'm finding it difficult to see the logic: Surely the secondary use is something that inherently should not be triggered when pointing at nodes, otherwise 2 functions will be triggered when pointing at nodes such that 'on use' without 'secondary use' becomes impossible?

I thought the whole point of secondary use was using the situation of not pointing at nodes to trigger a different function?

**Comment by sfan5** [comment]
It is not *entirely* consistent, but your usecase is now supported.
