### ISSUE TITLE
/help does not display name of findbiome mod

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9001]
##### Minetest version
```
5.1.0-RC1
```

##### Summary
The `/help` command does not display the mod origin of the `findbiome` mod commands correctly.

##### Steps to reproduce
1. Download and install and activate `findbiome` mod
2. Start any game
3. Say `/help` in chat
4. Look where `findbiome` is in the list

EXPECTED: It's somewhere in the list
ACTUAL: It's nowhere in the list. Instead, you see “??”.

Note: `findbiome` uses `after_mods_loaded` callback.

##### Notifications
@SmallJoker

**Comment by SmallJoker** [comment]
Can't fix. Minetest does not know where you created the chatcommand.

**Comment by DS-Minetest** [comment]
I can't find any `after_mods_loaded` callback in the api.
Anyway, `register_chatcommand` should only be called at load time:
https://github.com/minetest/minetest/blob/b79741c90ffffac6fb24783b38c5b507316cbcc8/doc/lua_api.txt#L3879

**Comment by Wuzzy2** [comment]
It's because the `on_mods_loaded`, right?

So what you want to say, I have to add the chat command at init time, right? It couldn't hurt to mention that in `lua_api.txt`, what you think? E.g.: “Chat commands must/should be registered at init time.”.

I have found a workaround in my mod: Immediately add those chat commands, at init time, but make them a no-up before all mods were loaded.

**Comment by Wuzzy2** [comment]
Okay, nevermind. It's indeed actually in the Lua API. Whoops. OK, so the fault was 100% to blame on me. Thanks. Bye. Closing. This issue is invalid.

**Comment by DS-Minetest** [comment]
Maybe `get_current_modname` should use `get_last_run_mod` when all mods are loaded.
