### ISSUE TITLE
Default value for joystick_type setting does not work correctly

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9002]
##### Minetest version
```
5.1.0-RC1
```

##### Summary
In All Settings, the default value for `joystick_type` is empty. This is strainge, because according to `settingtypes.txt`, this is an enum with default `auto`.
If you click on the “default” button, the value will be cleared, too, instead of being reset to `auto`.

##### Steps to reproduce
* Clear `minetest.conf`
* Start Minetest
* Go to All Settings
* Look up `joystick_type` and look at the initial value.

**Comment by paramat** [comment]
Confirmed, but:
https://github.com/minetest/minetest/blob/94619d8b4c73c6713617dc3aeb9214460511290b/src/defaultsettings.cpp#L286
https://github.com/minetest/minetest/blob/f92a393f6f949377b1d78630a8f7d24e78e6ff9d/builtin/settingtypes.txt#L149
A blank setting is the intended default, so is settingtypes.txt wrong?

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/commit/bce0d458d8cda70c10d78ea9ec476474f0a6f01a
Seems intentional? @rubenwardy

**Comment by rubenwardy** [comment]
It should default to auto, maybe "" is also interpreted as auto?

The joystick feature is quite broken
