### ISSUE TITLE
Crash with invalid settings

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9003]
##### Minetest version
```
5.1.0-RC1
```

##### Summary

You can make Minetest crash, possibly even at startup, if you manage to screw up your settings with invalid settings.

If you provide an invalid value to any of these settings, Minetest will either crash immediately or crash on the next startup.

```
font_path = <invalid path>
mono_font_path = <invalid path>
fallback_font_path = <invalid path>
freetype = false
main_menu_script = <invalid path/script>
```

##### Steps to reproduce
1. In All Settings set any of the above settings to an invalid value or a path that does not exist. Examples: `font_path = /home` or `freetype = false` (when the current fonts are all TTFs) or `main_menu_script = foobar`.
2. Restart Minetest if you didn't already crash

RESULT: You will either crash and then crash at subsequent launches (until `minetest.conf` is fixed) or you will not crash, but crash on restart.
EXPECTED: Minetest will fail gracefully. It might try to fallback to the default value. If that's not possible, it will display an error message visible to the user (the console doesn't count!) before crashing.

**Comment by Wuzzy2** [comment]
#9003 will fix `main_menu_script` handling.

**Comment by Wuzzy2** [comment]
Correction: #10938 will fix `main_menu_script` handling.

**Comment by Wuzzy2** [comment]
Why was this closed? Only `main_menu_script` was fixed but not `font_path`. Or is the crash no longer reproducible?

**Comment by sfan5** [comment]
Fallback code exists for the font paths, I assume that works.
`freetype = false` no longer exists as of today.

**Comment by Wuzzy2** [comment]
OK, I tested in 5.4.1, the fallback for fonts seems to work. The crashes seem to be fixed now.
