### ISSUE TITLE
Incorrect GUI / messages when sound system is disabled

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9004]
##### Minetest version
```
5.1.0-RC1
```

##### Summary
If sounds are disabled via `enable_sound=false`, the in-game GUI is incorrect:

- The in-game sound change dialog is still available although it's pointless and does nothing
- If you press the volume up/down or mute key in-game, you get messages as if you enabled the sound or changed the volume. But nothing changes actually because the sound is disabled

##### How it should be like
If sounds are disabled, then:

- Remove the sound menu in the in-game Esc menu
- Display “Sound system is disabled” when pressing the volume up/down or mute key

Is this still possible to do for 5.1.0 before strings are frozen?

**Comment by jastevenson303** [comment]
I use pavucontrol.  Maybe audio mixer on windows.

**Comment by paramat** [comment]
I don't see it as a bug worth dealing with for 5.1.0.
