### ISSUE TITLE
builtin node_dig always sets wielded item to 'main' inventory list

### ISSUE THREAD

**Issue by Skamiz** [minetest/minetest#9006]
##### Minetest version

```
Minetest 5.1.0-ea9b241
```

##### Summary
I am trying to use the 'hand' inventory list as described here:
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2557
to make it so only players who have the special hand item can dig nodes in my game.

But every time I dig a node and my wield item is empty it is set to a copy of the special hand item.

From looking at the code it looks like the fault is here:
https://github.com/minetest/minetest/blob/master/builtin/game/item.lua#L579
in the default node_dig definition.
At the end of the function 
```digger:set_wielded_item(wielded)```
is called indiscriminately of wheter or not the wielded itemstack was changed, which isn't realy a problem when it just sets it back to what it was before.

A bit earlier in the function ```wielded``` is gained through:
```digger:get_wielded_item()```

What I think is hapening is that when I have an empty slot selctet when digging a node it returns the itemstack from the 'hand' inventory list which is then copied to the main list.

##### Steps to reproduce
Initiate the 'hand' inventory list, put an item there and dig a node while having nothing sellected.
Note: While this happened in my game the dafault hand (":") had no tool capabilities.

I will try to cobble together a small mod which demonstrates this behavior more clearly.

**Comment by sfan5** [comment]
This was already fixed in 5fa614d97e13af64be490336392abe2a54fdcbc1 (issue #8953).
