### ISSUE TITLE
Add a default group to all nodes

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#9010]
Add within the register_node function a default group like ~~block~~ node = 1
So the creative hand in minetest_game can break any block

**Comment by paramat** [comment]
Surely the MTG creative hand can already break any node?
This is best avoided and i can't see a need.
Note: It is 'node' not 'block' =)

**Comment by Extex101** [comment]
Things like cloud there are a few other mods that have nodes without groups that I can't remember

**Comment by Wuzzy2** [comment]
:-1:
Adding a group to all nodes is redundant. Minetest already knows they're nodes.

However, it is indeed possible for nodes to exist that you cannot break in Creative, at least in MTG. Just add a node with groups that don't match any group that the creative hand would dig. An empty groups table is enough.

**Comment by Wuzzy2** [comment]
>  cloud is one of them, it is used like an admin-placed indestructable node.

Off-topic: Clouds can be blasted by TNT.
