### ISSUE TITLE
Movement: sudden X/Z speed vector erased while landing from jumps

### ISSUE THREAD

**Issue by sofar** [minetest/minetest#9011]
`5.0.1` stock (clearlinux build, if you care).

This issue has been known to me and a few players on ITB for a long time, but I can reproduce it in `singleplayer` as well without problems.

What is happening that when the player is jumping around (e.g. player keeps `jump` key pressed) one, or sometimes both of the players speed vector `x` and `z` speeds get zeroed.

This means that at the point of landing, the player sometimes just stops dead.

If the player is running `NE`, `NW` etc. Sometimes the `x` vector is zeroed on landing, sometimes the `z` vector is zeroed causing the player to jerk left/right.

Most prominently this can be seen by just making a `flat` world and running `NE` while jumping. Sooner or later you'll hit the problem. It may sometimes be subtle, but it never goes away.

**Comment by Calinou** [comment]
I think this has been an issue since the introduction of nodeboxes in June 2012, when the collision detection code was refactored to support them.

**Comment by ClobberXD** [comment]
> If the player is running NE, NW etc. Sometimes the x vector is zeroed on landing, sometimes the z vector is zeroed causing the player to jerk left/right.

I've come across this so many times. Thanks for the issue.

**Comment by sfan5** [comment]
This bug is especially obvious when run-jumping diagonally while fast is enabled:
![gif](https://user-images.githubusercontent.com/1042418/65950427-5663d800-e43e-11e9-9b01-cf417e9c0cc7.gif)

**Comment by SmallJoker** [comment]
#6886

**Comment by paramat** [comment]
As noted in the other issue, it seems to happen on lift-off, not landing.
I certainly notice sideways jerks when lifting off.
