### ISSUE TITLE
Mesh Rendering is... broken?

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9013]
##### Minetest version
```
5.0.1-stable
```

##### Summary
I exported my model to b3d and Minetest rendered surprisingly something else:
![Screenshot_20191002_202622](https://user-images.githubusercontent.com/25750346/66069048-50154f00-e557-11e9-9943-0d77c051f4cc.png)

But my model should look like so:
![Screenshot_20191002_202646](https://user-images.githubusercontent.com/25750346/66069113-63281f00-e557-11e9-8a73-4034b3d13e8e.png)

##### Steps to reproduce
1. Download my model .b3d, texture .png and the respective registration code:
https://ufile.io/ac63ugmt
https://ufile.io/z0168ckc
https://ufile.io/6rgu5lio

2. Put the node named "Wooden Cornice" in the world.

**Comment by paramat** [comment]
We have had no reports of broken mesh rendering in and since 5.0.1 stable, so it is not broken.

**Comment by NathanSalapat** [comment]
Looks like a error in the exporting, or in the registration.

**Comment by Andrey2470T** [comment]
I don't have any mistakes in my model, I've made it the usual way that I made others. And then just exported it to b3d. I also can not find out mistakes in the registration code.

**Comment by DS-Minetest** [comment]
You should use this b3d exporter: https://github.com/minetest/B3DExport

**Comment by Andrey2470T** [comment]
I downloaded it from there.

**Comment by TumeniNodes** [comment]
If mesh rendering were broken within minetest, think of all the other reports there would be.

Same if there is a bug in the b3d exporter. Did you look in the issue tracker for the exporter to see if there have been any similar reports?

Only thing I see, is that RainWarrior's last commit was 5 years ago, and was not pulled into the Minetest fork. Not sure why

**Comment by Andrey2470T** [comment]
> If mesh rendering were broken within minetest, think of all the other reports there would be.
> 
> Same if there is a bug in the b3d exporter. Did you look in the issue tracker for the exporter to see if there have been any similar reports?
> 
> Only thing I see, is that RainWarrior's last commit was 5 years ago, and was not pulled into the Minetest fork. Not sure why

But a question is do you see the same sort of the model as I exposed in my screenshot in your mt app? If you do, most likely it is a mistake in my source, but I even don`t know where :\

**Comment by TumeniNodes** [comment]
But this is not the place to ask about problems with your mod.
Either the forums or -hub
I don't actually have the time atm to download all the links you provided and then to check it out and I am certain the core devs don't have the time right now, as they are working on the release.

**Comment by paramat** [comment]
Yes, if mesh rendering was broken in 5.0.1 stable we would know about it already.
Also, you can look at other models in MTG to confirm that mesh rendering is not broken.
