### ISSUE TITLE
Toggling in-game console sets wrong focus

### ISSUE THREAD

**Issue by fairiestoy** [minetest/minetest#902]
It seems that this issue is up to now windows only ( asked a few guys on a server to try to reproduce it on linux based systems. without success ). It forces the Client to loose focus when pressing F10 and sets the focus to the border drawn by the windowmanager. However, clicking within the window returns to normal behaviour (redrawing, normal responses, etc). Could be a irrlicht issue already discussed here:
http://irrlicht.sourceforge.net/forum/viewtopic.php?f=1&t=45625&view=next#p262445

**Comment by paramat** [comment]
@fairiestoy old issue, is this still an issue?

**Comment by paramat** [comment]
Please can anyone test if this is still happening?

**Comment by Fixer-007** [comment]
I'm not quite sure it happens to me. Started the game, pressed F10, typed some text, pressed alt, whatever, it works fine.

**Comment by paramat** [comment]
Closing then since very old issue and seemingly fixed.
