### ISSUE TITLE
Using 3d_armor mod with "Enable Damage" inactive makes the world mostly refuse to load

### ISSUE THREAD

**Issue by style-nine** [minetest/minetest#9022]
##### Minetest version

```
I did a bisect and found the first commit where this bug appeared:

81c7f0a ("Send ActiveObjects once right after Init2", 2019-08-25)

```

##### OS / Hardware

Operating system: Ubuntu 18.04
CPU: AMD x86 64

GPU model:
OpenGL version:

##### Summary

If you switch to Damage not enabled, the world will mostly refuse to load.

##### Steps to reproduce

Create a new world with MTG and then enable "3d_armor" mod. Uncheck the "Enable Damage" option. "Play Game" and notice how it mostly doesn't load.

**Comment by style-nine** [comment]
Involves: https://github.com/stujones11/minetest-3d_armor

**Comment by sfan5** [comment]
This happens because 3d_armor removes the `immortal` armor group, making the client think the player is dead, so it won't send any movement packets.

While this is technically not an engine bug, I'm not sure whether we want the fragile construct around active objects (has caused 2 issues so far) for the sole purpose of disabling autoforward if the player is dead (#8387 which is an extremely minor annoyance).

**Comment by style-nine** [comment]
So, why does the client think that the player is dead if Enable Damage is unchecked?

**Comment by ClobberXD** [comment]
I'll remove that annoying bit of code for 5.1.0, and we'll look at a better implementation once 5.1.0 has been released.

**Comment by ClobberXD** [comment]
Btw, I can't reproduce this at commit 4682c7be, which comes after 81c7f0a. I've disabled damage, and enabled `3D Armor` modpack.

**Comment by style-nine** [comment]
You sure about that? On my screen, https://github.com/minetest/minetest/commit/4682c7be5d4e4c454c6d8a18279f60acd970da50 is Sep 8 and https://github.com/minetest/minetest/commit/81c7f0ae044b1131ad082e5e705c5276f82ac6ce is Sep 14.

see: https://github.com/minetest/minetest/commits/master?after=825579b43d6454cc33607ab8eff4e896b003b801+34

**Comment by ClobberXD** [comment]
Oops, my bad, sorry. I'll test with 81c7f0a.

**Comment by ClobberXD** [comment]
#9025 reverts the optimisation that the causes this issue. @style-nine, it'd be nice if you could test the PR and confirm that it works.

**Comment by lhofhansl** [comment]
Hah... I noticed that the other day and was about to track that down, but couldn't find time to that.
Thanks for figuring this one out @ClobberXD .
