### ISSUE TITLE
Multiple server list servers at the same time

### ISSUE THREAD

**Issue by niansa** [minetest/minetest#9023]
## Problem

It is very complicated to announce to two different server list servers and switching between these list is complicated on client

## Solutions

Allow , seperated list of servers to announce to and add server list "tabs" on client

**Comment by paramat** [comment]
Just curious ... why would a server want to also announce to a non-official serverlist? And what are these other serverlists and are they hostile?

**Comment by SmallJoker** [comment]
As a custom solution - since you seem to be the first one after this many years - I'd recommend to set up a cronjob using curl which announces the same fields to the second server list, even though they might not be accurate.

**Comment by niansa** [comment]
@paramat As example me hosting some servers and a server list where all my servers are announced to.

**Comment by FullTimeLinux** [comment]
@niansa Are you talking about sorting a list of servers based on the author, then printing basic server information and the server maintainer? I would think this could be done with making the search box more advanced and having the go button print the results (in a different tab?).

**Comment by paramat** [comment]
niansa, my mention of 'hostile' was only because there is one particular server list that is extremely hostile to MT, it was not implying alternative serverlists are generally hostile.
I am also curious why you would not just use the official serverlist instead.
I will label this as low priority as it seems that way, i am not sure it is worth the work and it seems there may be workarounds.

**Comment by niansa** [comment]
> @niansa Are you talking about sorting a list of servers based on the author, then printing basic server information and the server maintainer? I would think this could be done with making the search box more advanced and having the go button print the results (in a different tab?).

Yeah, I meant tabs
