### ISSUE TITLE
Would it be possible to add minetest to steam?

### ISSUE THREAD

**Issue by Niwla23** [minetest/minetest#9028]

**Comment by Df458** [comment]
I can understand wanting a game on your favourite platform, but I'm not sure this is really a good idea. In particular, I'm a little worried that an official steam presence would cause players to expect mods via steam's platform--this could create a second ContentDB page that modders have to manage at best, or fragment the modding community at worst.

There's probably some visibility benefit to being on Steam, but the storefront has gotten very crowded so I wouldn't expect much of a boost from this. You have to remember that Steam isn't free to launch on either, it's not expensive but if there's no major benefit then the cost isn't really worthwhile.

Do you have a particular use-case that isn't covered by adding Minetest as a non-steam game to your own library? It would be helpful to hear more details about why you want Minetest on steam.

**Comment by Niwla23** [comment]
I dont know anything about steam and not use it. I just like to have a bigger community

**Comment by benrob0329** [comment]
> I dont know anything about steam and not use it

Then I don't think we need to be on Steam :-)
Steam is it's own content distribution platform, putting our own on it's store would be counter-productive and would likely cause more confusion as to the nature of Minetest.

**Comment by SmallJoker** [comment]
It could motivate some more players to try Minetest. A downside is that they are unlikely to participate (much) in the forums and IRC, which are currently the only central places to exchange content.
Minetest already distributes itself, and unlike proprietary games there's no need to worry about credit card details or the safety of personal information (unless downloaded from a non-official source).

**Comment by TuringZauber** [comment]
I would be willing to have a look into implementing this.
Can the issue be assigned to me?

I never published anything on steam but surely we can figure that out. Minetest is already better than most greenlight steam games.

**Comment by Rick-W-Storm** [comment]
Please re-open.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
With the advent of the Steam Deck, please reconsider this. Many people that have purchased it shall may like Minetest, but have purchased their console to play games, and are not technically competent. To ask them to learn how to utilise the command-line, plasma-discover or GNOME Software would prevent many, because they expect to be able to acquire it via Steam, which serves as a perfectly good content-distribution platform.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
Additionally, to actively prevent people assisting Minetest, as @Rick-W-Storm obviously desires, without mere response, is slightly disingenuous.

**Comment by rubenwardy** [comment]
I'd be willing to put it on Steam after #6733 is done, making it more palatable for a general audience

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@rubenwardy, I utterly agree.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I (and, I expect, @Ubiquity5) are happy to administer the Steam-page, but I imagine that more qualified people are available.

**Comment by rubenwardy** [comment]
Steam allows you to publish things for free. I don't think that selling Minetest ourselves is necessarily a good idea, having to deal with paid customers would be a lot of pain in terms of support and bureaucracy. It would also be asymmetric to the rest of our delivery platforms - we don't charge for Minetest on Google Play or our website

**Comment by Iniquitatis** [comment]
_Semi-offtopic:_

> This really rubs a bad spot for the core devs even though surveys suggest that a lot of people hate the "Minetest" name.

Don't want to sound overly negative, but I'd argue that this is the worst thing that happens in open source projects: putting personal feelings above the project's success, which often leads to very long-standing problems.
I get it, we all are doing it just for fun in our spare time, but at the end of the day it's the project that brought us together, and I believe everyone wants the best for it. So ideally it should be put in the first place.
If players hate the name, it's an obvious signal to act. Would it really be fine if a lot of reviews mentioned their dislike of that name? Also, think about potential newcomers who might be put off by it.
Besides, changing the name is not as difficult as it seems:
1. I'm pretty sure there are a lot of creative people in this community who can come up with a more appropriate name.
2. It is not necessary to change the internals. For example, players most likely won't care if the repository is still called "Minetest", or that some source directory will be called like that.
