### ISSUE TITLE
use_texture_alpha = false does not apply to visuals of inventory node

### ISSUE THREAD

**Issue by bas080** [minetest/minetest#903]
If one uses an semi transparent image and "use_texture_alpha = false" the image the node in the inventory is still semi transparent. It is less transparent then the node that uses "use_texture_alpha = true".

Having transparent inventory nodes is inconsistent with the visual representation of the node with "use_texture_alpha = false" in the map.

Inventory node should not be semi transparent.

**Comment by paramat** [comment]
Closing as we now use meshes in inventory.
