### ISSUE TITLE
isDead() related crash on new world start

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9030]
I am on commit 81c2370c8b1a66a279a5ff450c78caf5dfef77bf 6 commits back at this time.
Crash on new world start related to 'isDead()':

ERROR[Main]: /home/matstandard/minetestf/gitmods/minetest/src/client/localplayer.cpp:2c7: bool LocalPlayer::isDead() const: A fatal error occurred: LocalPlayer's CAO isn't initialized

To reproduce:
Enable autoforward, while moving leave world, re-enter world.

Important for 5.1.0 as we are considering what to revert in relation to 'isDead' stuff.
I'm fine with a full revert that would leave dead players creeping forward if they were using autoforward, this is a minor and amusing bug.

**Comment by sfan5** [comment]
`isDead()` call sites as of the given commit:
https://github.com/minetest/minetest/blob/81c2370c8b1a66a279a5ff450c78caf5dfef77bf/src/client/client.cpp#L1248
https://github.com/minetest/minetest/blob/81c2370c8b1a66a279a5ff450c78caf5dfef77bf/src/client/game.cpp#L2484

**Comment by paramat** [comment]
Can now reproduce, see forst post.
Cause is:
https://github.com/minetest/minetest/blob/81c2370c8b1a66a279a5ff450c78caf5dfef77bf/src/client/game.cpp#L2484

**Comment by paramat** [comment]
I'm making a PR.

**Comment by paramat** [comment]
PR #9031

**Comment by paramat** [comment]
Confirmed crash in current MT master commit b49dfa92ce3ef37b1b73698906c64191fb47e226

**Comment by ClobberXD** [comment]
Can reproduce with auto-forward enabled while starting singleplayer:

```
2019-10-09 09:32:45: ERROR[Main]: /home/anand/minetest_5/src/client/localplayer.cpp:2c7: bool LocalPlayer::isDead() const: A fatal error occurred: LocalPlayer's CAO isn't initialized
```

**Comment by sfan5** [comment]
> What a weird line number... o_O

`0x2c7` = line 711

**Comment by ClobberXD** [comment]
> `0x2c7` = line 711

I figured that out later, thanks.

But it's strange that the line number is in hex - it's usually in decimal. The crash was also weird, in that MT just disappeared (hard crash?), instead of gracefully crashing by displaying the error in the error formspec.
