### ISSUE TITLE
[Meta-Tracker] GNU/Linux mobile

### ISSUE THREAD

**Issue by WorryTheBirds12** [minetest/minetest#9037]
## Basic Information

**Description**: Minetest on GNU/Linux Mobile.
**Platforms**: TuxPhones has a list of them [here](https://tuxphones.com/all-linux-distributions-for-smartphones/)

## Solutions

![adaptive-layout](https://coinsh.red/u/adaptive.jpeg)

### Alternative designs

Developing a separate applications or porting the Android application.

## Additional context

Preferably, the applications would be using a tarball to start.
Therefore, it is easier to port to a variety of mobile OSes.

______________________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=81857542)](https://www.bountysource.com/issues/81857542-meta-tracker-gnu-linux-mobile)

**Comment by SmallJoker** [comment]
What's your request?

**Comment by SmallJoker** [comment]
Spam, according to @Calinou.

**Comment by WorryTheBirds12** [comment]
> Spam, according to @Calinou 

@SmallJoker It is? I didn't see any similar issues requests. :)

**Comment by NathanSalapat** [comment]
I think it was called spam because you literally posted the exact same thing on a handful of other git repositories.

**Comment by benrob0329** [comment]
I think calling it "spam" is a bit harsh. With the Librem5 having started shipping I expect we'll see more of these kinds of issues anyways. Making the rounds requesting at least a look into support is hardly grounds to immediately close.
