### ISSUE TITLE
Server side screenshots

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#9038]
There needs to be a way for the server to take screenshots/photos of a location and use them in-game

**Comment by SmallJoker** [comment]
How? There's no rendering engine.

**Comment by Extex101** [comment]
Perhaps something like this:

- [ ] Server sends info to client asking to take a screenshot (possibility for client to disallow server-side screenshots)

- [ ] Client renders screenshot

- [ ] Sends the rendered screenshot to server (maybe create a "screenshots folder in world directory)

- [ ] Some way to access screenshots in-game

**Comment by rubenwardy** [comment]
This can be done using xvfb and client side mods. You'll have to write the code for that though

**Comment by Extex101** [comment]
I'm sorry but what is xvfb?
