### ISSUE TITLE
Text mistakes in settingtypes.txt

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9040]
##### Minetest version
```
69a2099c04527404f2d0942f2088b3d22dd75b5a
```

##### Summary
The following mistakes exist in `builtin/settingtypes.txt`:

> Map generation attributes specific to Mapgen flat.
> 'terrain' enables the generation of non-fractal terrain:
> ocean, islands and underground.

This is the description of `mgfractal_spflags`, but the description says “flat” instead of “fractal”.

> #    Decrease this to increase liquid resistence to movement.

“resistence” → “resistance”.

> #    Maximum liquid resistence. Controls deceleration when entering liquid at
> #    high speed.

“resistence” → “resistance”.

> #    Spread of light curve mid-boost.
> #    Standard deviation of the mid-boost gaussian.

“gaussian” → “Gaussian”.

> #    Useable to make minimap smoother on slower machines.

“Useable” → “Usable”

> #    Handling for deprecated lua api calls:

“lua api” → “Lua API”

> #    1 = 4D "Roundy" mandelbrot set.
> #    2 = 4D "Roundy" julia set.
> #    3 = 4D "Squarry" mandelbrot set.
> #    4 = 4D "Squarry" julia set.
> (…)

> #    The default is tuned for a suitable spawn point for mandelbrot

“mandelbrot” → “Mandelbrot”. “julia” → “Julia”

**Comment by SmallJoker** [comment]
Writing this post was probably more effort than proposing a patch/PR. Thanks for the report though.

**Comment by paramat** [comment]
I will fix these as they are mostly my mistakes.
