### ISSUE TITLE
Weblate did not update for 5.1.0

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9041]
##### Minetest version
```
5.1.0
```

##### Summary
You shipped Minetest with incomplete translations. To be more precise: It was impossible for translators to reach 100% on Weblate.

Weblate is currently stuck in 5.0.0 instead of 5.1.0. So ALL translations you pulled in neccessarily had to be incomplete. A “100%” translation on Weblate now leads to only a 96% translation in 5.1.0.

Evidence:
This string is new in 5.1.0: "3D noise that determines number of dungeons per mapchunk."
But it does not exist in Weblate. Therefore, Weblate must be stuck in the previous version.

**Comment by SmallJoker** [comment]
Not my problem if none of the Minetest Weblate admins was reachable for an entire week.
https://github.com/minetest/minetest/pull/9015#issuecomment-538662718

**Comment by paramat** [comment]
Please read http://irc.minetest.net/minetest-dev/2019-10-03#i_5599144 onwards
https://github.com/minetest/minetest/pull/9015#issuecomment-538662718
http://irc.minetest.net/minetest-dev/2019-10-13#i_5602373
Nothng could be done until est31 or Shadowninja was contacted, we delayed release for a week waiting for replies from them. Eventually, release could not and should not be delayed further so a workaround fix was made:
> Alternatively the new translation files could be downloaded via the interface which seems to provide an up to date file

Now please do not complain in the forum about the core devs over this and misleading others into resentment towards the core devs. It was simply an unfortunate situation that arose. Of course we do need to make changes to not let it happen again.

**Comment by Wuzzy2** [comment]
Well, sorry. But none of this wasn't mentioned in the release notes, wasn't it? Nor was it ever mentioned in News thread. I just learned about it today. So I just assumed it was an accident. I was wrong. Basically, you core devs just chose the “lesser evil” then. I agree that delaying the release even further for this would be even more annoying.

But yeah, the whole process of updating source strings on Weblate needs to be rethought. It's bad that everything fails just because est31 and ShadowNinja are absent for a week or so.
