### ISSUE TITLE
Update Weblate regularily

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9042]
This is a policy suggestion. It has 2 parts.

Part 1: I suggest to update the source strings on Weblate regularily, perhaps once a week or month, by pulling regularily strings from the repo to Weblate. Yes, even from -dev.

Currently, source strings on Weblate are either not updated at all (see #9041) or at the very last minute before a release, often without notice, so that translators only have very limited time to work on the updated strings.

Updating regularily has the benefit that the translations can be updated faster and the translators can be a little bit more flexible; they don't need to be active at the very narrow window that translators currently have. It also will hopefully prevent accidents like #9041 from happening again.
It's standard practice for many projects hosted on Weblate.

Part 2: Communicate [b]clearly[/b] to translators when they can start to work. Perhaps by posting in the News forums. For 5.1.0, this communication has failed. Rubenwardy just said “Translations will be updated shortly” but this never happened (for Minetest). If translations are delayed, but are possible later, all I'm asking for is a 1-sentence post in the same thread as soon they're ready.

**Comment by Calinou** [comment]
Is there a way to automate the pushing of source strings to Weblate? Say, it could be done once a week as long as at least one source string has changed.

**Comment by Wuzzy2** [comment]
@SmallJoker seemed to have implied in #9041 that some core devs don't even have admin access to the Minetest project on Weblate.
Well, if that's true, that would explain a lot! :D

I know I might sound crazy but: Maybe just give admin access to all core devs? Maybe?

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/issues/9041#issuecomment-541437007 which attempts to explain what went wrong.
I agree we need to make sure this situation does not happen again, and that we cannot rely on est31 or Shadowninja, who are both absent from the project.

**Comment by Wuzzy2** [comment]
What should be done if the Weblate maintainers don't re-appear in the next few months? I think it doesn't make much sense to wait longer.

Maybe talk to hosted.weblate.org staff to grant more Minetest core devs access. It's absurd that only 2 devs, who have disappeared, are allowed to make changes.

If hosted.weblate.org staff doesn't respond as well, I'm afraid the only quick fix would be to go back to acception translation PRs again … :-(

A long-term solution would be to self-host a Weblate instance on minetest.net. @celeron55, how realistic is this idea?

**Comment by paramat** [comment]
Est31 has now given several active core devs weblate access.

**Comment by Wuzzy2** [comment]
It seems that Weblate is now actually being updated regularily, according to the commit log.
Thanks!
