### ISSUE TITLE
Avoid excessively bright night sky when using customised lighting

### ISSUE THREAD

**Issue by LoneWolfHT** [minetest/minetest#9046]
## Problem

In 4.x you could increase your display_gamma to increase the brightness of the world. Now, in 5.x increasing gamma only increases the brightness of the sky (see https://github.com/minetest/minetest/issues/8577#issuecomment-541440038)
(EDIT by paramat: Not true, gamma does have effect but causes an excessively bright night sky)

It would be nice if we could have a setting that allowed players to change how dark night is without affecting the brightness of the sky.

## Solutions

Awaiting suggestions

## Additional context

https://github.com/minetest/minetest/issues/8577

**Comment by paramat** [comment]
> Now, in 5.x increasing gamma only increases the brightness of the sky

I doubt this, the terrain can be brightened but it requires extreme values that then make the sky very bright, see screenshots in #8618 
However of course, that PR limited gamma to 10 which we now discover is too low.
So something needs doing certainly, for now we could increase that gamma limit.

**Comment by LoneWolfHT** [comment]
> > Now, in 5.x increasing gamma only increases the brightness of the sky
> 
> I doubt this, the terrain can be brightened but it requires extreme values that then make the sky very bright, see screenshots in #8618
> However of course, that PR limited gamma to 10 which we now discover is too low.
> So something needs doing certainly, for now we could increase that gamma limit.

There's also this part I added:
> without affecting the brightness of the sky.
The gamma_beta limit would probably need to be raised a LOT to keep up with the increased gamma. Not sure if that would cause problems with normal lighting or not...

**Comment by paramat** [comment]
I think what needs doing is to tune how night sky brightness reacts to customised lighting, i do not think a setting is needed because excessively bright night sky is never wanted.

**Comment by paramat** [comment]
Closing as we have misunderstood, see https://github.com/minetest/minetest/issues/8577#issuecomment-542833165
Gamma is not the setting to use to make night light brighter, we need a new setting for that. This means gamma will not need to be set to extreme values which means we can avoid overly-bright sky.
We should implement the new setting first then see if sky brightness is a problem.
