### ISSUE TITLE
minetest.sound_play() broken if 'object' is used

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#9048]
##### Minetest version

```
5.1.0
```

##### Summary
If you try to specify an object in sound_play() you hear nothing (or you barely hear anything) when that object is punched, but other players can hear it.

##### Steps to reproduce
Add this code to the on_punch() callback of an entity and punch it:

`minetest.sound_play(soundname, {object=objref})`

_Temporary workaround: Use 'pos' or 'to_player'_

**Comment by IhrFussel** [comment]
More info:

It seems to be inconsistent cause with some sound_play() calls you hear the sound and with others you don't even if both use 'object'.

This also happens with 5.0.1 clients.

**Comment by rubenwardy** [comment]
Was the object newly created? If so, does minetest.after around the sound cause the sound to play?

**Comment by IhrFussel** [comment]
I don't use any minetest.after() to play the sound.

I have it inside the on_punch() of every mob entity so the ref should exist for sure if I can see the mob.

**Comment by IhrFussel** [comment]
It seems to depend on some kind of position.

Not sure if entitiy's position or player's position but when I look in different directions I sometimes hear the sound at varying volume.

**Comment by Warr1024** [comment]
I can confirm that this is reproducible using NodeCore.

A number of sounds are supposed to play, attached to the player, including the "inventory shuffle" sounds when changing wield index, and the "tool breakage" sounds.  In 5.0 they play at the correct volume.  In 5.1 they are much quieter for the player making the sounds.

**Comment by SmallJoker** [comment]
f6de86c

Fixed when `object` is set to the local/current player. Please request re-opening if this also happens for other objects.

**Comment by ClobberXD** [comment]
Wow, the fix is so simple, thanks! :)

Did anyone manage to figure out the commit that first caused this regression?

**Comment by SmallJoker** [comment]
http://irc.minetest.net/minetest/2019-12-05#i_5619572

81c2370 caused it because the server now skips movement players for the own player. As a temporary workaround in 5.1.0, use 2nd or 3rd person view (F7) to trigger the position update.

**Comment by ClobberXD** [comment]
Wow, that's interesting :)
