### ISSUE TITLE
Formspecs without a formspec_version[] element inherit the formspec version from the currently open formspec (if any).

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#9050]
##### Minetest version

```
Minetest 5.1.0 (Linux)
```

##### Summary

Formspecs without a `formspec_version[]` element inherit the formspec version from the currently open formspec (if any).

##### Steps to reproduce

Run the following lua code with WorldEdit's `//lua` or equivalent, and do not close the first formspec:
```lua
local p = 'singleplayer'; minetest.show_formspec(p, 'formspec', 'formspec_version[2]size[3,4]label[0.5,0.5;Version 2]'); minetest.after(2, minetest.show_formspec, p, 'formspec', 'size[3,4]label[0.5,0.5;Version 1\n(should be bigger\nthan the last\nformspec)]')
```

Adding `formspec_version[1]` to the start of the second formspec appears to fix this issue.

**Comment by luk3yx** [comment]
Yes, it does appear to fix the issue.

**Comment by SmallJoker** [comment]
a978278bf
