### ISSUE TITLE
Abandon file based maps

### ISSUE THREAD

**Issue by pyrollo** [minetest/minetest#9051]
I open this issue to discuss about the merit of keeping old code for opening file based maps.

In map.cpp, there is still a fallback code for searching mapblocks in files if they are not found:
https://github.com/minetest/minetest/blob/master/src/map.cpp#L2175

Is this still really needed ? 

I'm working on map.cpp for Kidscode, trying to improve map management, adding possibility of threading. I'm first doing some simplifications.

Before proposing any PR I'd like to have some advice about this old code.

**Comment by random-geek** [comment]
@pyrollo Are you working on this or should I?

**Comment by pyrollo** [comment]
@random-geek I'm not at the very moment but I could later. There is no urge but if you want to do it its totally ok :)
