### ISSUE TITLE
macOS builds broken past Sep 4

### ISSUE THREAD

**Issue by tacotexmex** [minetest/minetest#9056]
##### Minetest version
```
Minetest 5.1.0
```

##### OS / Hardware
macOS

##### Summary
Something in the commits soon after https://github.com/minetest/minetest/commit/c9ec1a8580038549040b36c1f201f60c59d92d83 broke building Minetest on macOS, as visible in 
- @neoascetic's [builds](https://github.com/krondor-game/minetest/releases)
- https://github.com/Homebrew/homebrew-core/pull/45255

Since @neoascetic's builds are produced daily, my suspected culprit is ea9b241c13e9982acb993e616fa1db685ffba5cb. This needs closer investigation though.

##### Steps to reproduce
Use Mac, build a Minetest version past https://github.com/minetest/minetest/commit/c9ec1a8580038549040b36c1f201f60c59d92d83.

**Comment by SmallJoker** [comment]
Our macOS build job passes, so without an error log or manual interaction by neoascetic there won't happen anything.

**Comment by tacotexmex** [comment]
The neoascetic builds are only a telltale, there are builds error logs at https://github.com/Homebrew/homebrew-core/pull/45255

**Comment by SmallJoker** [comment]
36bfc67 is the only PR that touched both code areas in the given period. Although I don't understand how there can be any errors from that change. What's the used Irrlicht version, after all?

**Comment by tacotexmex** [comment]
Yes, that must be the faulty commit. I think the Irrlich version used is 1.8.4.

**Comment by AMDmi3** [comment]
Please try patch from #9064.
