### ISSUE TITLE
[Feature Request] Add a Music Volume Slider

### ISSUE THREAD

**Issue by NoctisLabs** [minetest/minetest#9057]
## Problem

Some games/mods may wish to add background music or soundscapes and allow the player to control their volume independently to sounds. In addition, main menu music could use a volume control as well.

## Solutions

Adjust the lua api to allow mods to register sounds as "music" and add a new volume slider and mute button for music to the minetest settings menu. 

## Additional context

We could take this much further and add volume sliders for every sound from footsteps to ambiance, but I think Sounds and Music are good enough.

**Comment by benrob0329** [comment]
General sound volume categories would make this generic and expandable.

**Comment by rubenwardy** [comment]
This would first require support for music

**Comment by benrob0329** [comment]
@rubenwardy That can be handled by the game, this issue is specifically for allowing multiple volume levels (initially for music, but I think it can be done generically from the start)

**Comment by rubenwardy** [comment]
Minetest sound support which can be used for music. Proper music support should stream/defer sending music files, to avoid crashing android clients

**Comment by NoctisLabs** [comment]
If adding music support into the engine, it may be desirable to implement a way to smoothly fade out or transition the background music depending on circumstance. For example, a mod that adds a playable piano or jukebox may need to silence or change the background music. Or it might be nice if the menu/loading music could smoothly transition into in-game music.

**Comment by paramat** [comment]
This feature seems premature because music is not really supported yet.
There is no proper main menu music support, because main menu music should be per-game, all we have is a completely unsuitable MTEngine music ability.
In-game music is not widely used due to problems of file sizes.
I suggest closing this until we progress with music support.
