### ISSUE TITLE
Applying visual node dig effect even if node.can_dig returns false

### ISSUE THREAD

**Issue by Bulldog83** [minetest/minetest#9067]
##### Minetest version
5.1.0-x64-release

##### Summary
Even if node.can_dig returns false, visually the node still breaks, but does not disappear.
I think it will be more aesthetically if the visual effect of digging is not applied, if the node cannot be dug.
I've made craftstation with on_punch craft mechanic and made it not diggable if player wielding valid tool for craft. And when I punch node it don't disappear, but visually it looks awful.

**Comment by SmallJoker** [comment]
The client does not execute server mod code. Code contained in `can_dig` is entirely unknown to the client, causing it to handle the node like a regular one.
Aside that it might not look great, it's the only solution. Suggestions to make it look better are welcome.

**Comment by DS-Minetest** [comment]
@Bulldog83 `node_dig_prediction = ""` could be helpful for you.
https://github.com/minetest/minetest/blob/53ebd803c613949a3f30fb4a905192c85dc73851/doc/lua_api.txt#L6299-L6303

**Comment by Bulldog83** [comment]
Hmm. Ok, thanks, I'll try it.

**Comment by MoNTE48** [comment]
Is it possible to close?
