### ISSUE TITLE
Translate game/mod/modpack/texture pack descriptions

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9071]
## Problem
The description texts of games, mods, modpacks and texture packs (`game.conf`, `mod.conf`, `modpack.conf`, `texture_pack.conf`, `description.txt`) is not translatable).

## Solutions
Make it translatable.

**Comment by paramat** [comment]
Seems low priority, who is going to translate all those descriptions? I expect very few can be bothered to do so.

**Comment by sfan5** [comment]
That isn't really an argument, the possibility of translating it is still useful (though low priority, I agree).
