### ISSUE TITLE
Clang Format: Whitelist all files and use in a new way to avoid the problems

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9074]
Clang Format (CF) has a minor benefit, but also has a lot of problems:

* Being an automatic check, it understandably fails to accept formatting created by good human judgement that makes code more readable.
* Being non-configurable, it fails to accept many aspects of MT codestyle.
* The result is, in my experience, around 90% of its suggesitons are either useless or make code far less readable.
* Although we tried, it is not possible for it to just raise a warning but without marking a build as failed. Which causes 2 problems:
* To avoid a CF fail masking the results of valid build checks we constantly have to work to silence the CF fails.
* Contributors see a failed CF check and then often work to correct it, making the code format very bad, only to be told later by core devs to ignore CF, reverse the bad changes and whitelist the file. This happens very often, every few days, and wastes time.
This really must be avoided as we should not frustrate contributors any more than we already do (it is already hard enough to contribute).

Many of the core devs have been complaining about CF problems for years but nothing has been done. Many contributors consider the situation crazy and wonder why we even use it.
I am tired of CF problems and many others are too, please can we actually do something?

I admit that around 10% of its suggestions are useful, but the things suggested are usually things a reviewer would have spotted anyway.
Contrary to certain claims, it does not have a huge effect on code quality, it actually has very little effect on code quality.
What time it saves by automatically spotting a valid mistake (which does not happen much) is far outweighed by the time spent attending to the problems it causes.

Overall, i can see the minor benefit but consider these far outweighed by the problems caused for core devs and contributors. The overall effect of CF on the project is negative.
However, i can see that it could be useful to have around to use if desired, instead of removing it entirely.

So, as an alternative and compromise solution to removing it entirely, i suggest that all files are whitelisted, and CF can be used, if desired, by temporarily un-whitelisting a file to see the suggestions, applying any valid suggestions, then re-whitelisting when a PR is complete.
This method could be suggested to contributors in the contributing guidelines. Those comfortable with this method will 'opt-in', all other contributors will no longer be misled. This solves the problems while keeping the benefits.

Together with this, all the messy 'Clang Format On/Off' lines should be removed from the code.
I am volunteering to do the work required.

EDIT:
2 more points:
* Most of the files are already whitelisted, so what i suggest is actually what we are already doing for most files. So this is not a radical suggestion.
* During development we often ask contributors to add files to the whitelist, so my suggestion is simply bringing forward the inevitable conclusion while removing all the unnecessary grief.

**Comment by rubenwardy** [comment]
Our code style is well defined and should be able to be captured well by an automatic formatter. I don't support disabling this, as it helps to avoid silly code style reviews

**Comment by paramat** [comment]
> should be able to be captured well by an automatic formatter

'Should', maybe, but it is very clearly not doing that in the case of our CF check.
So are you suggesting we try a new checker? I am ok with that. However, nothing has been done for years and if this suggestion is refused i do not expect anything to happen. All suggestions are refused but nothing is done, this is very frustrating.

Any automatic formatter can never match human judgement in terms of code formatting for readability, which is much of the reason the suggestions are so bad.
> it helps to avoid silly code style reviews

I admit it helps a little yes, but as explained it also causes a lot more 'silly attendance to the problems caused', as i am sure you are aware. It wastes more time than it saves.

**Comment by paramat** [comment]
Added 2 more points to the first post.

**Comment by paramat** [comment]
@rubenwardy if you are going to oppose, please could you address this, it cannot be ignored:
> Contributors see a failed CF check and then often work to correct it, making the code format very bad, only to be told later by core devs to ignore CF, reverse the bad changes and whitelist the file.

It is not acceptable to mislead contributors like this, cause them to do bizarre formatting work only to ask them to revert 90% of it later. I have to do this to a contributor weekly, and did so today, i makes me feel bad and i do not want to do this to contributors anymore.
This alone is enough reason why something has to be done.

This solution is simple, it is what we are doing already for most files, and in the history of suggested solutions to this problem i am the only person who has actually committed to implementing the solution.

**Comment by paramat** [comment]
Any more core dev opinions?

**Comment by sfan5** [comment]
Good [example](https://travis-ci.org/minetest/minetest/jobs/609670370) of clang-format making nonsensical suggestions:
![Bildschirmfoto_2019-11-09_21-22-27](https://user-images.githubusercontent.com/1042418/68534674-658c4e80-0337-11ea-8dee-f96f724f9ac2.png)
In case it isn't obvious, the suggestion has the following problems:
* 2 indents instead of 1
* destroy alignment
* nonsensical "first element on same line as type+name" and "two elements on last line"

If we want to continue using an automatic formatter, it must capture our code style accurately and refrain from making suggestions when it doesn't know better. Whitelisting 80% of our source files or using `// clang-format off` is not a solution to this.

In it's current state, clang-format is misleading for new contributors and annoying for everyone else (who already knows of its problems).

**Comment by ClobberXD** [comment]
> Whitelisting 80% of our source files or using `// clang-format off` is not a solution to this.

I wholly agree. That's even worse than not having an auto formatter at all.

**Comment by paramat** [comment]
sfan5 i mostly agree. However, unless a formatter has an extremely powerful AI it will not be able to reproduce human judgement for code readability. So an improved formatter will still make many bad suggestions, the only way to silence these will be whitelisting, and we will end up with most files whitelisted, so we will be back to the same situation.
This is why i suggest whitelisting everything then temporarily un-whitelisting to check a PR.

So the actual problem is using a auto-formatter for code-readability formatting. Clang format reports a little useful stuff, but should not comment on anything to do with formatting for readability, such as line splitting, indentation etc.
Maybe we can use a new formatter that can be configured to not do these things?

As a first step, please could i have support for removing all 'clang format on/off' lines and whitelisting those files instead? (only needs doing if we do not remove CF).
The problem with those lines is obvious once you consider the inevitable outcome: Our code will increasingly fill up with thousands of such lines subdividing files every time a formatter cannot cope with a few lines of code. And only because of a using ridiculous formatter which we will hopefully replace soon.

Because of the situation, i suggest we either whitelist all files, or remove CF now (and not wait for a replacement before doing this because that will probably take months/years/never happen).
Opinions?

**Comment by rubenwardy** [comment]
Our code style really isn't that complicated to require a complete AI. For the subjective cases, it's better to have false-negatives than false-positives

**Comment by paramat** [comment]
So please can i have support for removing all 'clang format on/off' lines and whitelisting those files? This will need doing whatever happens (see my previous post for why this needs to be done).

**Comment by nerzhul** [comment]
hello, one thing can be trying to first update clang-format to a more recent version to see if we can solve more cases ? we use a very old one

**Comment by paramat** [comment]
Yes we could consider that, but any new version would need to be configurable enough to not comment on any sort of 'formatting for readability' or line breaks. I am not too hopeful about this =)

Note that if/when we update CF and it improves, all the clang format on/off lines will need to be re-assessed, many will then be wrongly applied. This is why they inevitably have to be removed in any situation, and why they were a mistake. Seems obvious this has to happen.
Still no support for that? I am tempted to go ahead and do that.

**Comment by nerzhul** [comment]
another point is we may try to reduce the whilelisted files by passing clang-format on it and seing which are compliant after passing, i think many are whitelisted just because we would prevented commiting code style commit

**Comment by rubenwardy** [comment]
> Clang Format (CF) has a minor benefit,

Clang Format has a massive benefit: productivity

**Comment by paramat** [comment]
My opinion on this has changed since i saw rubenwardy link to an example of CF configuration. It seems highly configurable, i was not aware it was, and it should be significantly reconfigured.
Ideally i think it should be configured to not report on indentation and alignment for code readability, as that is the largest source of CF nonsense i see.
Currently, it is very poorly configured.

To be clear, 'minor benefit' referred to the current poorly configured state, not CF generally.

So closing this and will open an issue asking for configuration, which also seems to be what sfan5 is asking for.

**Comment by paramat** [comment]
Reopening as #10029 shows that even when configured as well as possible, CF continues to make many stupid requests.
So improving configuration is good of course, but not a solution and leaves us in the same situation.

We really f**king need to do something, see #10408 , this contributor added 4000 lines of unrelated formatting changes to a feature PR thinking they had to do what CF requests, it was all unacceptable formatting changes and wasted work.
I cannot see any other solution than this suggestion, it is not much different from the current whitelisting of 80% of files.

**Comment by rubenwardy** [comment]
That PR was not configured as well as possible

**Comment by paramat** [comment]
> That PR was not configured as well as possible

Ok, but even if it was configured as well as possible it would not solve the problem, it would still make many silly requests, as human judgement cannot be matched and configuration is limited. So the situation would be the same, even if CF complains about 1 tiny change it will mark a build as failed and the problem remains.
> I use clang-format on my personal projects, and it's rare that it messes up

But i seem to remember this is because you chose to align your codestyle to what CF desires, which is unacceptable for MT and unacceptable to contributors.

**Comment by rubenwardy** [comment]
I think contributors are more bothered by nitpicky code suggestions, and would rather be able to just run a command to format the code.

Code-style reviews are largely a waste of time, but boy does Minetest development like wasting time

**Comment by rubenwardy** [comment]
A lot of the errors is makes seems to be with wrapping lines that are too long. I wonder if that can be disabled. The main functionality that is needed is checking of brace placements, pointer/references, and indentation.

Also, rather than whitelisting all files, it would be better to remove clang-format from CI

**Comment by rubenwardy** [comment]
Ok, I've worked out how to make clang-format not re-wrap lines. Now the big sticking point is in alignment, there's no way to make it keep alignment that already exists. So keeping things in the whitelist should help I guess

**Comment by paramat** [comment]
Ok good to hear.

I support improving the configuration, but very strongly oppose allowing CF to auto-format MT code (which requires contributors to align to CF formatting, i would find that unbearable).
Because the first is obviously welcome and the second is very controversial i think these 2 things have to be split into 2 tasks. The first should not force the second in, and the second should not obstruct the first.
Obviously, to improve the configuration, the configuration task must be allowed to reformat MT code during the development of the task, but that is only to optimise the configuration.
I have no objection to #10029 if it is just configuration, but the autoformatting part should be split off.
> there's no way to make it keep alignment that already exists. So keeping things in the whitelist should help I guess

Yes, the whitelist is essential then.
If it will complain about alignment, then CF will still make huge amounts of bad requests. It is certainly worth improving configuration, but the problems will mostly remain and many files will still be in the whitelist.

I suggest we improve configuration as best we can, and then continue as before, adding clear warnings for contributors about CF.
All CF on/off lines will need to be removed as the requirement for them changes each time configuration changes, which would be a pain. They are a horrible mess to have in code anyway, this will mean some files will need to be added to the whitelist.

**Comment by nerzhul** [comment]
i agree with you @rubenwardy that if we just have more simpler rules just running clang-format in the majority of case is solving the problem. I use it too on other projects, no issue for me
