### ISSUE TITLE
Add On/off toggle for autosave

### ISSUE THREAD

**Issue by MisterPrintf** [minetest/minetest#9077]
## Problem

Minetest lives on my USB drive but due to the autosave causes excessive wear and tear on the filesystem of the USB drive, eventually requiring a lengthy defragmentation or long format.
## Solutions

To solve this, I would like to see a setting which allows autosave to be turned off and then adds a save button to the pause menu or allows saving via ctrl+s

**Comment by SmallJoker** [comment]
Just set the map save interval to a very high value and it will save automatically on leave.

**Comment by MisterPrintf** [comment]
> Just set the map save interval to a very high value and it will save automatically on leave.

Where is the setting located?

**Comment by SmallJoker** [comment]
Settings menu: https://github.com/minetest/minetest/blob/master/builtin/settingtypes.txt#L1159-L1160
.conf file line: https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1337-L1339
