### ISSUE TITLE
Unable to Register and Join a server

### ISSUE THREAD

**Issue by Sonickyle27** [minetest/minetest#9082]
##### Minetest version
```
5.1.0
```

##### OS / Hardware

Operating system: Windows 10 Pro Version 1903
CPU: AMD Ryzen 7 1700
GPU: Radeon RX 580 Series
OpenGL API Version: 4.6

##### Summary
When I try to join a listed server from the Join Game tab, the "You are about to join this server with the name "usernamehere" for the first time" prompt appears, asking for a password to be entered. If I type in a password then click "Register and Join", nothing happens.
Only when not typing in a password does Minetest allow me to proceed with connecting to the server.

##### Steps to reproduce
1. Launch Minetest and go to the Join Game tab.
2. Select one of the servers that you haven't registered on (I've tried "Capture the Flag - Multiple Maps!" [ctf.rubenwardy.com:30001] and "Pandorabox" [pandorabox.io:30000]) and click Connect.
3. Minetest shows the prompt asking the user to enter a password.
4. Enter a password (I've tried one under 20 characters) then click "Register and Join".
5. Nothing happens (for me the console only shows a message that says `[Main]: GUIConfirmRegistration: Not allowing focus change.`
6. Remove the password typed in the password text box then click "Register and Join".
7. Minetest will attempt to connect to the server (in the case where the server rejects blank passwords, it'll prevent you from joining)

**Comment by rubenwardy** [comment]
Maybe this happens when the password doesn't match or the server doesn't send a response?

**Comment by Sonickyle27** [comment]
Ah ok! That isn't immediately obvious to me. Thanks, I'll close this.

**Comment by rubenwardy** [comment]
It's not immediately obvious to anyone. There's a feature request to fix this, some where
