### ISSUE TITLE
Cannot use mouse to move camera vertically in Qubes OS

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9083]
##### Minetest version

```
5.0.0
```

##### OS / Hardware
Operating system: Qubes OS R4.0 / Fedora 30

##### Summary

Because Qubes OS does not allow Minetest to capture the mouse.
Cannot use mouse to move camera vertically.

##### Steps to reproduce

Run minetest on Qubes OS

##### Releated issues

https://github.com/QubesOS/qubes-issues/issues/4986

**Comment by SmallJoker** [comment]
> Because Qubes OS does not allow Minetest to capture the mouse.

Out of scope. Minetest cannot fix OS bugs.
