### ISSUE TITLE
Rename deprecated.lua to obsolete.lua

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#9085]
Because #9062 was merged, I think `deprecated.lua` should be changed to `obsolete.lua`.
What do you think?

**Comment by paramat** [comment]
I disagree because, although most of what is contained may be 'obsolete', the more commonly understood word for this process is 'deprecation', so that seems more suitable as a filename.

**Comment by Panquesito7** [comment]
Shoud I close the issue, then?
Or wait for the opinion of the other developers/contributors?

**Comment by paramat** [comment]
We will wait for more input, it usually takes more than 1 disapproval to close an issue.

**Comment by SmallJoker** [comment]
Trivial, and unnecessary to change.
