### ISSUE TITLE
Thai characters are not provided by Minetest

### ISSUE THREAD

**Issue by lionants02** [minetest/minetest#9098]
##### Minetest

```
Minetest 5.1.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
[DxDiag.txt](https://github.com/minetest/minetest/files/3827363/DxDiag.txt)

##### OS / Hardware

Operating system: Windows 10
CPU: i5

GPU model: Intel onbord
OpenGL version:

##### Summary
I was shocked when entering Minetest 5.1.0 I didn't see the menu. So I tried opening it compared to 5.0.1
The difference is
- 5.1.0 The windows tab above is in my local Thai language but in 5.0.1 displayed in English
So I guess that is probably due to language. Then try to fix and appear using

## Before (Default)
![Screenshot (38)](https://user-images.githubusercontent.com/5077672/68529868-85bb0e00-0335-11ea-89f2-185962a8152c.png)
![Screenshot (34)](https://user-images.githubusercontent.com/5077672/68529746-5952c200-0334-11ea-8002-16ddc2294b9c.png)

## After
![Screenshot (37)](https://user-images.githubusercontent.com/5077672/68529763-830be900-0334-11ea-917d-8dab882dd3d3.png)
![Screenshot (36)](https://user-images.githubusercontent.com/5077672/68529767-8bfcba80-0334-11ea-9765-c20d707f8638.png)

**Comment by SmallJoker** [comment]
Please try the following `minetest.conf` setting (close Minetest first).

```
font_path = C:\path\to\minetest-5.x.x\fonts\DroidSansFallbackFull.ttf
```

**Comment by lionants02** [comment]
Wow no bug but minetest not thai font.  
 I solved by using a free font named TH Sarabun.  http://freefont.thaifont.info/th-sarabun-psk/  

![Screenshot (39)](https://user-images.githubusercontent.com/5077672/68529922-23aed880-0336-11ea-8421-1b45b39e1420.png)

**Comment by SmallJoker** [comment]
@lionants02 Could you please check whether this updated [translation file](https://krock-works.uk.to/u/locale_th.zip) works for you? It goes into the `locale` directory, and should work with the default Minetest configuration (rename `minetest.conf`).

If this works it's not a Minetest issue. -> Weblate.

**Comment by lionants02** [comment]
> Please try the following `minetest.conf` setting (close Minetest first).
> 
> ```
> font_path = C:\path\to\minetest-5.x.x\fonts\DroidSansFallbackFull.ttf
> ```
> 
> EDIT: It's plausible that `needs_fallback_font` is not enabled any more in the most recent Thai translation.

### Set font to DroidSansFallbackFull.ttf
![Screenshot (42)](https://user-images.githubusercontent.com/5077672/68530087-b13ef800-0337-11ea-8242-0512a3bbb6d2.png)
![Screenshot (40)](https://user-images.githubusercontent.com/5077672/68530080-8d7bb200-0337-11ea-9d34-6c5de8f88d33.png)

### Restart Minetest
![Screenshot (40)](https://user-images.githubusercontent.com/5077672/68530104-d3387a80-0337-11ea-9560-ef43fd31ec77.png)

I try to test. There are 2 solutions.
1. Change to another language
2. Download Thai Front such as TH Sarabun

**Comment by lionants02** [comment]
> @lionants02 Could you please check whether this updated [translation file](https://krock-works.uk.to/u/locale_th.zip) works for you? It goes into the `locale` directory, and should work with the default Minetest configuration (rename `minetest.conf`).
> 
> If this works it's not a Minetest issue. -> Weblate.

### check hash
![Screenshot (43)](https://user-images.githubusercontent.com/5077672/68530286-966d8300-0339-11ea-9013-2a21e5e1b6db.png)

### copy from [translation file](https://krock-works.uk.to/u/locale_th.zip) to Minetest and rename `minetest.conf` to `minetest.conf.org`
![Screenshot (46)](https://user-images.githubusercontent.com/5077672/68530333-e5b3b380-0339-11ea-85e3-f09bbbc38276.png)

### -*-
![Screenshot (47)](https://user-images.githubusercontent.com/5077672/68530341-fe23ce00-0339-11ea-97f5-e8f820307105.png)

### ***Thank you very much SmallJoker. I got the solution.***

**Comment by SmallJoker** [comment]
Too bad. So even the fallback font doesn't help here.
Thanks for sharing your results and workaround solution.

**Comment by Festus1965** [comment]
it took so long to find this solution,
as we are 4 person now translating ready to 99% ...
and can't see Thai in Tabs, menu etc.

I added this font solution into page http://th.minetest.one and maybe, this font can be added in main offered packages ?
