### ISSUE TITLE
[performance] UDP Receive exhaustion

### ISSUE THREAD

**Issue by thomasrudin** [minetest/minetest#9111]
##### Minetest version
```
0.4.16 - 5.1.0
```

##### Summary
Currently, in the `ServerThread::run()` method the `Receive()` method is only called once after the main Lua loop (server step):

https://github.com/minetest/minetest/blob/master/src/server.cpp#L100
```cpp
	while (!stopRequested()) {
		try {
			m_server->AsyncRunStep();

			m_server->Receive();

		}
```

The `Receive()` method collects the incoming packets from the receive thread itself to process it in the main thread.

The problem is, that if the server is under heavy load (serverstep over 100ms for example) the method gets only called once after the current server-step finished.
This is due to the `dtime` check here:

https://github.com/minetest/minetest/blob/master/src/server.cpp#L490
```cpp
	if((dtime < 0.001) && !initial_step)
		return;
```

If this dtime is not below 0.001 seconds the `AsyncRunStep` does not return early and the `Receive` method has no chance to keep up with the inflow of packets/events.

This caused some very weird bugs on my server, for example:
* All mobs run around but there is no way to interact, eat or move inventory
* IRC Chat works from the server to the client but the clients can't send chat messages back

Some of those "interruptions" can go up to a couple minutes!
**The fun thing is:** that this apparent lag is not noticeable in the server logs or in `/status` because it is caused by the packets arriving too late.

##### Related issues
* #8584 lockup due to Pathfinder increased globalstep time
* I'm sure #8207 is caused by some of this
* #8183
* #7418
* #6009 (@VanessaE 's servers)

##### Mitigation

I started to mitigate this effect by calling the `Receive()` method for a fixed amount every serverstep: https://github.com/pandorabox-io/minetest/commit/af6956e7d2c5fae3151ddf5d769d52b81f9a7270

But i think there has to be a better solution than this.. :confounded: 

##### Steps to reproduce
* Add lots of technic/automation mods to the server (`mesecons`, `technic`, `pipeworks`)
* Invite 10 to 20 players to play and build
* Observe degraded serverstep and the above described effect

**Comment by IhrFussel** [comment]
0.001 seconds is 1ms

No MT server runs at 0.001 steps not even 0.005 so that means this affects *all* servers.

**Comment by thomasrudin** [comment]
> No MT server runs at 0.001 steps not even 0.005 so that means this affects all servers.

Not quite, no:

This effect only occurs if a server-step time is longer than the `dedicated_server_step` setting.
If that happens every step, for example in #8584, then the receive-traffic grinds to halt...

That could be due to either excessive map-sending or long lua-execution.

**Comment by sfan5** [comment]
The bug with `Receive` only being done once is indeed present, however your analysis of the `if((dtime < 0.001) && !initial_step)` is incorrect, that is working as intended and not the cause.

**Comment by sfan5** [comment]
Please test whether #9114 fixes this issue for you.

**Comment by thomasrudin** [comment]
> Please test whether #9114 fixes this issue for you.

Wow! thanks for the fast response! :+1: 
I'll test that in the next few days...

**Comment by ElonSatoshi** [comment]
This sounds like the issue I've been experiencing due to my satellite internet latency! Thanks for working on it, everyone.
