### ISSUE TITLE
Game crashes when using specific formspec background image

### ISSUE THREAD

**Issue by Bulldog83** [minetest/minetest#9112]
##### Minetest version
5.1.0-x64-release

##### OS / Hardware
Operating system: Windows 10 x64
CPU: Intel Core i7 950 3Ghz

GPU model: NVIDIA GeForce GT 1030

##### Summary
I use formspecs with prepend:
```
bgcolor[#000;true]
background[5,5;1,1;gui_form_bg.png;true]
listcolors[#77777760;#E5E5E545;#353535;#33333390;#FFF]
```
It works fine. But today I tried to replace background picture with another one, using no_prepend[]:
```
size[10.5,9.73]
real_coordinates[true]
no_prepend[]
bgcolor[#000;true]
background[5,5;1,1;mw_bg_cokeoven.png;true]
listcolors[#77777760;#E5E5E545;#353535;#33333390;#FFF]
...
```
And when I try to load formspec with this background the game crushes with error:
```
2019-11-14 12:15:49: ERROR[Main]: Some exception: "std::bad_alloc"
2019-11-14 12:15:51: ERROR[Main]: Please choose a name!
```
Both pictures are exists.

mw_bg_cokeoven.png, ~9 Kb
![mw_bg_cokeoven](https://user-images.githubusercontent.com/20737750/68845895-341bd600-06dd-11ea-90cd-e98c190456d0.png)
gui_form_bg.png ~3 Kb
![gui_form_bg](https://user-images.githubusercontent.com/20737750/68845929-439b1f00-06dd-11ea-8412-3a2050b4cda2.png)

**Comment by v-rob** [comment]
Cannot confirm with given testing code or with testing code fixed (`no_prepend[]` belongs before `real_coordinates[]`), closing.
