### ISSUE TITLE
Stall Glitch - Revisited

### ISSUE THREAD

**Issue by daytonnvpaul** [minetest/minetest#9113]
##### Minetest version

```
Minetest 5.1.0 (Linux)
Using Irrlicht 1.8.3
BUILD_TYPE=None
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: VPS, Ubuntu 18.04-minimal
CPU: Unknown

GPU model: DeadHead
OpenGL version:

##### Summary

2019-11-11 14:49:25: VERBOSE[ConnectionSend]: con(6/1)RE-SENDING timed-out RELIABLE to 67.69.69.203(t/o=0.1): from_peer_id=1, channel=0, seqnum=65501

After becoming frustrated with continued server crashes (04.17.1), that wouldn't restart with the normal loop script, I ended up resetting the map.  The issue still continued, so I decided to upgrade to 5.0.1.  The problem still occurs with 5.1.0.

Symptoms:  Server become unresponsive to outside connect attempts, yet will still communicate via the IRC gamebot.  All attempts to join end with the client receiving a 'time-out' error.

After setting my log_level to VERBOSE, and running for about 6 hours, 2 days in a row, I logged 120,00 lines of this error (different ip addresses, of course).  These seem to be logged by the hundreds per second.

IRC nickname: TommyTreasure

**Comment by sfan5** [comment]
duplicate #9111

**Comment by daytonnvpaul** [comment]
Excuse me?  #9111 has nothing to do with this.

**Comment by daytonnvpaul** [comment]
My bad, didn't read far enough into #9114.
