### ISSUE TITLE
Subgame background image is stretched

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9125]
The custom background image for a subgame is always stretched to the window's rectangle, breaking the aspect ratio if the window's aspect does not match the aspect of the image. This makes the feature useless for anything other than simple gradient backgrounds. Since actual artwork looks silly when deformed in this way, I'm submitting this as a bug.
A more correct way to display the image would be to uniformly scale it to touch the window from the outside.

**Comment by SmallJoker** [comment]
Should it scale to the shorter side (chop), longer side (fill space black or so) or repeat?

**Comment by hecktest** [comment]
Touching outside, so chop. Letterboxing looks bad, and repeating only works for some.
Ideally, of course, you'd want to select between chop, letterbox, repeat or stretch in game.conf.
It would also be nice if this image were shown to connecting clients.

**Comment by paramat** [comment]
+1 for fixing this and for 'touching outside'. This is a significant problem.
