### ISSUE TITLE
Mesher should discard triangles more aggressively

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9126]
The mesher only ever attempts to optimize plain, solid nodes.
This can lead to pathological situations where more than half of a mapblock's geometry is never actually drawn. That also inflates the VBO size, creating a risk of an out-of-VRAM crash on the client, which certainly has happened to me before.
(There may or may not be a problem with unseen VBOs not getting collected. I'll file a separate issue once I test this more.)
![nodeboxes](https://user-images.githubusercontent.com/42101236/69064968-3e144080-0a1f-11ea-9ca9-d6eb87a66071.jpg)
It may be the case that nodeboxes are currently the worst drawtype one could use for things, worse even than raw meshes.

An obvious optimization for the mesher would be to round up all the nodes and nodeboxes with non-alpha materials, and do an AABB containment test on any geometry before submitting it to the buffer. If a triangle is contained in a box or facing a box face co-planarly, it can be safely dropped.
![cull](https://user-images.githubusercontent.com/42101236/69065344-de6a6500-0a1f-11ea-8d82-72c4ec3e33da.jpg)

**Comment by Ekdohibs** [comment]
As a note, even a simple version of this optimization where two identical shapes touching each other perfectly would be culled would relieve the current huge cost of nodes like snow.

**Comment by hecktest** [comment]
Snow is a nodebox, so that's exactly the bad case I described, and your description of "touching" is equivalent to the "facing a box face co-planarly" condition.

**Comment by sfan5** [comment]
This issue has been reported before in #6409.
