### ISSUE TITLE
EmergeThread::finishGen Couldn't grab block

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9131]
5.1.0
When I set the "unload unused data" timer to 1, this message gets dumped on me occasionally.
_EmergeThread::finishGen Couldn't grab block we just generated: (coords)_
![emerge](https://user-images.githubusercontent.com/42101236/69146988-4927a900-0ad1-11ea-8c84-50f6ae457031.jpg)

**Comment by sfan5** [comment]
"When I provoke a buggy situation the engine spits out error messages."

How do you expect this to be fixed?

**Comment by style-nine** [comment]
Maybe the minimum for timeout should be around 10 or higher.

**Comment by paramat** [comment]
client_unload_unused_data_timeout
or
server_unload_unused_data_timeout
?
I guess the latter.
Seems unsurprising with a value of 1, which would cause other problems too.
We could add range limits in code and in settings to avoid this, what value stops it happening?

**Comment by SmallJoker** [comment]
Client: >= 20s to not require useless much server time/traffic
Server: >= 10s for about the same reasons, but lower due to fast moving players that possibly won't return quickly to the traversed mapblocks.

**Comment by hecktest** [comment]
Server, obviously.
I was messing with the settings trying to nail #9130 since that's also related to unloading.
Yet, could someone explain why a value of 10 is fine while 1 is not? Isn't this called a race condition?

**Comment by paramat** [comment]
https://github.com/minetest/minetest/blob/539f016c1b1a706da2c113435ec60bb39c868f4b/src/emerge.cpp#L562

Check occurs after C++ mapgen finishes for a mapchunk and before Lua 'on generated' callbacks, so it is not a delay caused by those, as i suspected. Seems odd that C+ mapgen would take 1s, although that could possibly happen with non-standard chunk size or other odd settings.

Maybe setting the setting to 1 is actually causing an unload to happen less than 1s after C++ mapgen?

**Comment by SmallJoker** [comment]
> Yet, could someone explain why a value of 10 is fine while 1 is not? Isn't this called a race condition?

Yes, it is some kind of race condition.
Why do you need this special edge-case to work? One second is an enormous waste of server resources, thus this is a nitpicking issue. PRs are welcome, though.

**Comment by hecktest** [comment]
I don't need 1s at all, this was to test the raycast issue. But, it's an error, so I filed a bug, in case something worse were lurking underneath.
