### ISSUE TITLE
Crash when certain character sequences are entered in chat

### ISSUE THREAD

**Issue by fluxionary** [minetest/minetest#9132]
##### Minetest version
```
5.1.0 through dev-9776460
```

##### OS / Hardware
Linux Server

##### Summary
If a player enters e.g. `%2` in chat, the game crashes with the following trace:

```
minetest5/src/script/cpp_api/s_base.cpp:89: static int ScriptApiBase::luaPanic(lua_State*): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (...est/minetest_exec/minetest5/bin/../builtin/game/chat.lua:18: invalid capture index)
```

Entering `%1` results in `@message`. Basically, `%#` is being interpreted as a capture index, and if the index is greater than the number of captures, it crashes. The solution is probably to escape `%`s.  However, as this doesn't affect Minetest 5.0, I expect someone will want to figure out why. 

##### Steps to reproduce
Create a fresh server instance w/ the affected versions, launch it, type `%2` in chat.

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/commit/d1c27c7e8037e9f438741ee5f7d3b6bda22d22a0
