### ISSUE TITLE
Minetest change set the "mirrored" (xrandr --same-as) option on Linux in fullscreen mode

### ISSUE THREAD

**Issue by bell07** [minetest/minetest#9136]
##### Minetest version
Stable 5.1.0 on Gentoo Linux (compiled with ebuild)

##### OS / Hardware
Gentoo Linux on AMD-A8
GPU model: Radeon R7

##### Summary
I use 2 Monitors as extended desktop on my workstation (xrandr --left-of). Each time I start Minetest the setting is changed. I see the game on both screens. If I leave the game, the setting is not changed back, the screens stay on xrandr --same-as and I need to adjust the setting manually.

##### Steps to reproduce
- Connect 2 monitors to Linux Workstation
- Set the `xrandr --output A --auto --left-of B` setting
Start Minetest in fullscreen
Leave Minetest

##### Expected behaviour
Must have: The game should restore the previous settings after the game exits
Nice to have: The game should use only one screen, Maybe an new setting which screen should be used (primary by default).

**Comment by sfan5** [comment]
#5484
