### ISSUE TITLE
Minetest is not load custom gamepacks

### ISSUE THREAD

**Issue by ne-vlezay80** [minetest/minetest#9137]
##### Minetest version
```
5.01
```

##### OS / Hardware

```
Operating system: Archlinux
CPU:
```
##### Summary
Minetest is not viseble gamepacks.
Gameid is empty world.

**Comment by ne-vlezay80** [comment]
Solved by remote world

**Comment by paramat** [comment]
What is a 'custom gamepack'? Only mods can be combined into a pack (as far as i know).

**Comment by An0n3m0us** [comment]
@ne-vlezay80 
Did you build Minetest? Make sure you also cloned the minetest_game repo into the games/ folder, otherwise Minetest Game won't be visible in the 'gamepacks', and you won't be able to create a MTG world either.
