### ISSUE TITLE
Detachment snaps client side player object to origin, also bad interpolation

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9140]
5.1.0 and earlier
Dual issue:
- Every time a player object gets detached from an entity, her position is set to 0,0,0 and she then flies back from there into the correct spot.
- The client extrapolates player velocity in this horrible way that makes everyone look like a jack-in-a-box on a really tight spring.

This happens even when dual-clienting on the same machine. (or maybe only in these circumstances? I don't have a server yet)

Gallery of horrors: ( also starring #2813 )
![lerp](https://user-images.githubusercontent.com/42101236/69466477-7bacfc80-0d84-11ea-994b-0e097e3197d7.gif)
![kill it](https://user-images.githubusercontent.com/42101236/69466483-81a2dd80-0d84-11ea-8849-63bfc1491fca.gif)
![wat](https://user-images.githubusercontent.com/42101236/69466493-85cefb00-0d84-11ea-8cb0-e76059786227.gif)

**Comment by hecktest** [comment]
I forgot to mention; for this to manifest, you must wander a dozen blocks away from the origin. If the origin is "in sight", this does not happen.

**Comment by paramat** [comment]
Sounds exactly like #5620 which we thought was fixed by #5622

**Comment by hecktest** [comment]
Well then, enjoy the regression.
This is probably related to the coordinate relocation thing.

**Comment by paramat** [comment]
@shivajiva101 did #5622 take the 'camera offset every 200 nodes' thing into account? I assume it did but just checking.

**Comment by sorcerykid** [comment]
@hecktest, sorry a bit off topic but where is that human model from? Is it from a game you've released? I could really use something like that as the basis for an upcoming game I'm working on. As the blocky Sam models don't really cut it.

**Comment by hecktest** [comment]
I make my own models, and this is a server-only game. You'll have to learn how to make your own art, or pay someone to do it for you.

**Comment by sorcerykid** [comment]
Thanks anyway I already found plenty of excellent models on sketchup.
