### ISSUE TITLE
Support for limiting storage of chat messages by time (GDPR)

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9142]
## Problem
It's been raised by a teacher that they are unable to use Minetest as they're worried about storing the chat for a long period of time, and would rather do log rotation. In their country, students can't agree to legal things so a privacy policy isn't an option

## Solutions

Store chat logs separately from debug.txt, allow limiting to a certain period of time

## Alternatives

This could be a mod given as part of Minetest Edu mod pack?

**Comment by ClobberXD** [comment]
I'm completely in favour of storing the chat separately from the rest of the logs.

> This could be a mod given as part of Minetest Edu mod pack?

Then only the modpack would conform to GDPR, right? Isn't Minetest supposed to adhere to GDRP too?

**Comment by Calinou** [comment]
Is the way Minetest writes logs friendly to third-party log rotation systems?

**Comment by Fixer-007** [comment]
Why not just trim it by outside tools, or even delete every on game start?

**Comment by hecktest** [comment]
You can do this in Lua alone.
I've been redirecting chat to a custom system since the beginning, and it doesn't show up in logs.
Minetest technically does not need to conform to GDPR. Servers do.

**Comment by appgurueu** [comment]
My advanced chat mod writes chat to it's own log which is in the world folder and can easily be deleted.
