### ISSUE TITLE
Huge increase in collision bugs since 5.0.0

### ISSUE THREAD

**Issue by ClobberXD** [minetest/minetest#9143]
##### Minetest version

```
5.1.0
```

##### Summary

I've been observing a stark increase in false-positive collision detections since 5.0.0 (or 5.1.0-dev; will confirm in a bit). These often happen in tight places, where the player is closest to nodes, but isn't colliding with them head-on. But many-a-times, the collisions are detected as head-on collisions, and the player comes to a complete stop, even if the player is literally moving parallel to the node(s). This group of phenomena makes things like parkour, and even normal walking in tight spaces, very tedious and potentially fatal activities.

##### Steps to reproduce

Incorrect/overly-enthusiastic collision detections can be detected in many scenarios, including these most common ones:

- Going as close to a vertical wall of nodes as possible, and jumping *parallel* to the wall. This is the most common scenarios in my experience, where the player completely comes to a stop mid-jump, as if hitting a solid node head-on.
- Jumping in a place with a ceiling with a height of exactly 3 nodes. This is the second most common scenario from my observations. Although the player does physically graze the ceiling at the highest point of the jump, the player at times completely comes to a stop mid-jump, as if hitting a solid node head-on.

**Comment by hecktest** [comment]
I've noticed that it happens regardless of the angle. Just slide along a wall and you're bound to get caught sooner or later.
Blind guess: this has nothing to do with 5.0 directly (isn't this irrlicht's job), but is aggravated by performance hiccups that 5.0 might have introduced, as I had trouble reproducing this in minimal.
The other half of the problem is that the colliders aren't hit in the right order.
![bonk](https://user-images.githubusercontent.com/42101236/69483679-93d75700-0e2a-11ea-87de-ad69f849c9fe.jpg)

**Comment by v-rob** [comment]
Hitting a wall when jumping parallel is the worst.  Happens to me all the time in ITB's parkours.  You have to be touching a wall, so the current workaround is to not touch the wall at all when jumping.

**Comment by jastevenson303** [comment]
It makes a difference whether new_move is disabled.

**Comment by Wuzzy2** [comment]
I suggest to post some example code and instructions on how to reproduce it.

E.g. on what kind of nodes/entities does it occur (which shape)? Do you have the node definitions ready?
And how do you need to build/walk?

As such, I find this issue to be way too vague to be useful. I don't really know what I can do to reproduce the problems.

You say there are multiple collision bugs. So in that case it would make sense to track each of them down individually, writing down the specific (!) situations in which they occur. Hopefully this will help finding the reasons for this.

**Comment by ClobberXD** [comment]
I've already provided repro steps/exact scenarios in the issue description:

> #### Steps to reproduce
>
> Incorrect/overly-enthusiastic collision detections can be detected in many scenarios, including these most common ones:
>
> - Going as close to a vertical wall of nodes as possible, and jumping parallel to the wall. This is the most common scenarios in my experience, where the player completely comes to a stop mid-jump, as if hitting a solid node head-on.
> - Jumping in a place with a ceiling with a height of exactly 3 nodes. This is the second most common scenario from my observations. Although the player does physically graze the ceiling at the highest point of the jump, the player at times completely comes to a stop mid-jump, as if hitting a solid node head-on.

There are more false-positive scenarios, but to be honest, those are somewhat tedious to track and catch red-handed, as they're less predictable and very uncommon.

Regarding the types of nodes, this happens with all solid/"collidable" nodes, whose face the player collides with, is completely flat. This would include all regular 1x1x1 nodes, bottoms of stairs and slabs, and any other nodebox with a fully-flat face facing the player. Nodes being fully flat could just be a coincidence, simply because most nodes in a world are 1x1x1, and _might_ not be relevant to this issue.

**Comment by ClobberXD** [comment]
I'd like to elaborate on the aforementioned scenarios a bit:

> Going as close to a vertical wall of nodes as possible, and jumping parallel to the wall. This is the most common scenarios in my experience, where the player completely comes to a stop mid-jump, as if hitting a solid node head-on.

As v_rob noted, this is possible only when the two collision boxes are touching. But even so, I've observed that I'm not able to reproduce this when jumping *exactly* parallel to the wall in question. But even a 1-degree deviation from the parallel dir (towards the wall ofc) causes me to come to a complete stop in mid-air from time-to-time.

> Jumping in a place with a ceiling with a height of exactly 3 nodes. This is the second most common scenario from my observations. Although the player does physically graze the ceiling at the highest point of the jump, the player at times completely comes to a stop mid-jump, as if hitting a solid node head-on

When I'm jumping diagonally and don't occasionally come to a complete stop mid-jump, I also tend to be yanked to one side *when colliding with the ceiling*. This, I think, is related to #6886 - i.e. the sudden shifting doesn't happen only when starting a jump, but when bouncing in any direction.

**Comment by Wuzzy2** [comment]
> Going as close to a vertical wall of nodes as possible, and jumping parallel to the wall. This is the most common scenarios in my experience, where the player completely comes to a stop mid-jump, as if hitting a solid node head-on.

I think I can confirm this. It happened to me a lot in Inside the Box when I had to perform a precise jump near a wall. It's really annoying if you jump from platform to platform and then suddenly stop mid-jump as this will screw up your jump.

PS: I'm sorry for being stupid. I think I was just too confused yesterday.

**Comment by paramat** [comment]
> It makes a difference whether new_move is disabled.

We should concentrate on new movement code (the default) for this issue.
The old movement code is intentionally kept unchanged and already contains other bugs, and new bugs may not be fixable due to the effect on sneak-related behaviours.

**Comment by paramat** [comment]
In MT 5.1.0 stable:

Near world edge, i can reproduce the 2 'common' bugs detailed in the first comment.

Near world edge, if the player presses sideways up against a wall then moves forward and very slightly angled away from the wall (see screenshot, crosshair should be pointing slightly away from the wall), then the player cannot move forward at all.

![screenshot_20200315_183620](https://user-images.githubusercontent.com/3686677/76708153-95d06900-66ec-11ea-819b-14dc8796ce98.png)

Oddly, if the player walks angled slightly towards the wall (crosshair pointing slightly towards the wall) the bug disappears.

**Comment by paramat** [comment]
In MT 5.1.0 stable, at world centre:

* I can reproduce "Going as close to a vertical wall of nodes as possible, and jumping parallel to the wall [...] where the player completely comes to a stop mid-jump,"
* I can only occasionally reproduce "Jumping in a place with a ceiling with a height of exactly 3 nodes. [...] Although the player does physically graze the ceiling at the highest point of the jump, the player at times completely comes to a stop mid-jump"
* I cannot reproduce "if the player presses sideways up against a wall then moves forward and very slightly angled away from the wall (see screenshot, crosshair should be pointing slightly away from the wall), then the player cannot move forward at all."

**Comment by paramat** [comment]
In latest 5.2.0 containing the update collision tweak, near workd edge:
* This bug is just as bad: "if the player presses sideways up against a wall then moves forward and very slightly angled away from the wall (see screenshot, crosshair should be pointing slightly away from the wall), then the player cannot move forward at all."
* These bugs occur less often:
"Going as close to a vertical wall of nodes as possible, and jumping parallel to the wall [...] where the player completely comes to a stop mid-jump,"
"Jumping in a place with a ceiling with a height of exactly 3 nodes. [...] Although the player does physically graze the ceiling at the highest point of the jump, the player at times completely comes to a stop mid-jump"

**Comment by paramat** [comment]
More about:
"In MT 5.1.0 stable:
Near world edge, if the player presses sideways up against a wall then moves forward and very slightly angled away from the wall (see screenshot, crosshair should be pointing slightly away from the wall), then the player cannot move forward at all."

I find that sometimes the player cannot move forward, other times they cannot move backward, never both or neither. This seems to switch occasionally with no known reason, perhaps float precision is flipping over in some way.
Looking at the player position when unable to move, it seems as if the player collisionbox is slightly inside the wall and colliding with the wall nodes in the direction of travel.

**Comment by paramat** [comment]
> Blind guess: this has nothing to do with 5.0 directly (isn't this irrlicht's job), but is aggravated by performance hiccups that 5.0 might have introduced, as I had trouble reproducing this in minimal.

In MT 5.1.0 stable i can just as easily reproduce "if the player presses sideways up against a wall then moves forward and very slightly angled away from the wall, then the player cannot move forward at all." in my ultra minimal game (minipeli), so i doubt this is the cause.

**Comment by ClobberXD** [comment]
Thanks for the thorough testing, paramat. Much appreciated. :+1:

**Comment by SmallJoker** [comment]
Does this still happen after #9343 ?

**Comment by ClobberXD** [comment]
Neither of the scenarios mentioned in the first post was reproduce-able, in the time I played through ITB's tutorial series (about 15-20 mins). I'm on 5.3.0-dev-6cf15cf87.

**Comment by paramat** [comment]
I retested: "Near world edge, if the player presses sideways up against a wall then moves forward and very slightly angled away from being parallel with the wall, then the player cannot move forward at all."
No longer occurs =)
