### ISSUE TITLE
Minetest 5.1 mod enabling broken

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9144]
Long story short, enabling mods through the GUI has no effect in MT 5.1 - they are immediately disabled. I suspect this has to do with the recent update for auto-enabling dependencies. Right now I need to enable mods in the world.mt files.

**EDIT:** Update - mod loading seems completely broken to me.

**Comment by LoneWolfHT** [comment]
I don't get this in latest stable

**Comment by SmallJoker** [comment]
Cannot reproduce in 5.2.0-dev.

**Comment by appgurueu** [comment]
I press enable, press save. If I then press Configure again, they are not enabled.

**Comment by NathanSalapat** [comment]
Probably not what's happening here, but if you have the same mod as a standalone and as part of a modpack you'll get issues trying to enable them.

**Comment by SmallJoker** [comment]
Please check that
1) there are no mods that share the name with another (remove dreambuilder_modpack if in doubt)
2) check that Minetest can write to `world.mt`
3) check for errors/warnings regarding mod loading after manual changing in `world.mt`

**Comment by paramat** [comment]
@appgurueu what commit are you on?

**Comment by appgurueu** [comment]
1. There are mods that have the same name, but this shouldn't be a problem
2. It can
3. There are none

**Comment by appgurueu** [comment]
Update: Resolving 1 (moving a modpack I made) solved it. I still see this as an engine issue, but you might decide to mark this as a [Won't Fix].

**Comment by rubenwardy** [comment]
There's already an issue for this

**Comment by SmallJoker** [comment]
Solved.
