### ISSUE TITLE
MT 5.1 broke formspecs

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9145]
Despite having using `real_coordinates[true]`, formspecs are messed up in 5.1 while they worked in 5.0.

**Comment by Df458** [comment]
Can you provide some specific mods with broken formspecs? It would be extremely helpful for determining the source of the bug...

**Comment by SmallJoker** [comment]
Don't use `real_coordinates` in mods that aren't designed for it.

**Comment by appgurueu** [comment]
@SmallJoker reopen please

**Comment by SmallJoker** [comment]
@appgurueu `field[...]` elements were tested multiple times in #8524 (download link included). Thus, it appears to be a modder issue for now.

Please provide a simple example of your formspec that doesn't work as intended.

**Comment by appgurueu** [comment]
@SmallJoker 
##### How it looks with 5.1
![Screenshot 2019-11-26 18-00-03](https://user-images.githubusercontent.com/34514239/69655432-ca091680-1076-11ea-8eee-97f49210d6a6.png)
##### How it looked with 5.0.1
See [Content DB entry](https://content.minetest.net/packages/LMD/cmdlib/)
![Old Screenie from CDB](https://content.minetest.net/thumbnails/2/R79f2IBxL5.png)

**Comment by rubenwardy** [comment]
Real coordinates is not supported by 5.0.1, yet you use it: https://github.com/appgurueu/cmdlib/blob/master/help.lua#L95

Simply remove that line to use legacy coordinates

**Comment by appgurueu** [comment]
Alright, thank you!
