### ISSUE TITLE
Lua errors crashing the engine

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9151]
_5.1.0 mingw-w64 + luajit_
_Windows 7_

A Lua error happening in server init and shutdown may crash or brick the engine process.
Certain init errors give me a "gray screen" instead of the usual error window. This doesn't always happen, but it only happens on init. The gray screen cannot be recovered from, a restart is necessary.

Errors on shutdown always crash the engine with "This application has requested the runtime to terminate it in an unusual way". The usual "minetest.exe has stopped working" follows. The error's stacktrace is still printed to stdout.
There is also this line: "terminate called after throwing an instance of 'LuaError'"

Repro: Register an on_shutdown function that throws an error.

**Comment by LoneWolfHT** [comment]
If the game crashes while you are in the chat or a formspec you will get a grey screen too. I think there's an issue for that

**Comment by sfan5** [comment]
#4482
