### ISSUE TITLE
Use moonjit instead of LuaJIT

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9153]
I recently stumbled across [moonjit](https://github.com/moonjit/moonjit), which is apparently a continuation of LuaJIT development. I suggest that we replace LuaJIT in the builds with moonjit.

**Comment by Enrikoo** [comment]
Good idea, but I think its still luajit 2.1.0-beta3 when I compile inside it, maybe it will change in the future?

**Comment by Enrikoo** [comment]
After compiling I don't get libluajit.a or something.

**Comment by appgurueu** [comment]
I haven't used it in a build yet. But swapping the Lua implementation should be no big deal, especially as moonjit claims to be compatible. If it isn't, we can just create a wrapper.

**Comment by Enrikoo** [comment]
It won't be compatible because my friend was compiling MT with moonjit and he had errors running mods like technic, so yes, wrapper needed.

**Comment by appgurueu** [comment]
> It won't be compatible because my friend was compiling MT with moonjit and he had errors running mods like technic, so yes, wrapper needed.
Please elaborate on this. From my assumptions it should work (although I'm too lazy to compile rn).

**Comment by Enrikoo** [comment]
> > It won't be compatible because my friend was compiling MT with moonjit and he had errors running mods like technic, so yes, wrapper needed.
> 
> Please elaborate on this. From my assumptions it should work (although I'm too lazy to compile right now). Which [branch](https://github.com/moonjit/moonjit#branches) did your friend use?

He used the master branch, in which recent changes are happening.

**Comment by appgurueu** [comment]
For now he should also test v2.0 and v2.1 branches, which are the ones being compatible with LuaJIT.

**Comment by rubenwardy** [comment]
Are there benchmarks for MoonJIT vs LuaJIT vs Lua? Does it fix the memory limit in a way which is more reliable than GC64?

MoonJIT should be API compatible with LuaJIT, like how LuaJIT is API compatible with Lua. Switching to MoonJIT should be as simple as changing the library you link with - perhaps only using flags like `-DLUAJIT_ROOT=path`

**Comment by appgurueu** [comment]
Yeah, I found [LuaVela](https://github.com/iponweb/luavela) and [RaptorJIT](https://github.com/raptorjit/raptorjit). LuaVela fixes the memory limit from what I've read, and RaptorJIT seems to be the most popular.

**Comment by rubenwardy** [comment]
I'm aware of RaptorJIT. Its name comes from one of Mike Pall's, the creator of LuaJIT, last words:

> Uh oh. Brace yourselves ...
> 
> Language design needs taste and experience. Sadly, most people and
> committees lack that. Any you know, the road to hell is paved with
> good intentions.
> 
> It looks like there's already a contest going on about the best way
> to hijack and destroy LuaJIT with the most atrocious and hazardous
> changes.
> 
> I could't possibly anticipate how fast things would go downhill
> without leadership. The raptors can sense the void. They're already
> sharpening their claws at the portal.
> 
> I'm outta here in a couple of days. Good luck. You'll need it.
> 
> --Mike

**Comment by MoNTE48** [comment]
MoonJIT 2.1.2 works great and seems like a good candidate after the original LuaJIT.
Other forks from the list removed or limited support for other OS besides Linux x86-64.
Minetest aims to support the maximum number of desktop and mobile OS. So I would vote for MoonJIT.
Currently using v. 2.1.2 did not require anything from me except 'make install' MoonJIT and rebuilding Minetest.
Some of my servers are already working with it. So a little documentation supplement should be enough.

**Comment by appgurueu** [comment]
Could you attempt some comparison? Is MoonJIT faster? Or more reliable?

**Comment by MoNTE48** [comment]
LuaJIT is very stable and much faster than Lua 5.1.
Now it makes no sense to talk about stability or performance. Rather, about fixing bugs, release 2.1, which has been in beta status for 3 years, support for new APIs and architectures in the future... 

Now MoonJIT, it's just LuaJIT development over which is resumed. It makes no sense to use an abandoned version of the library when another team continues to develop.

**Comment by rubenwardy** [comment]
> Now MoonJIT, it's just LuaJIT development over which is resumed. It makes no sense to use an abandoned version of the library when another team continues to develop.

If the team is inexperienced, then there may introduce obscure bugs and performance issues causing it to be worse than the outdated version

I think I'll switch to moonjit on my server and see if I notice any difference

**Comment by MoNTE48** [comment]
@rubenwardy I totally agree. And I suggest just adding to the build instructions information that _you can use MoonJIT if you want_.
Perhaps before the next Minetest version be released, it will become clear how stable MoonJIT is and whether the developer is experienced.

**Comment by hecktest** [comment]
But what does moonjit actually fix or add?

**Comment by appgurueu** [comment]
> Moonjit is a fork of the inactive LuaJIT project and aims to provide a way forward for existing users of LuaJIT looking for continuity in development and maintenance.
- from their Readme

Additionally, performance might benefit, but I don't know of any benchmarks. @MoNTE48 and @rubenwardy might be able to provide some as they seem to be already testing them on their servers.

**Comment by mia-0** [comment]
Note: Some distros, for example openSUSE, have apparently switched to moonjit as their LuaJIT implementation. This means the FindLuaJIT CMake module currently fails to find the include directory on those distributions (include/moonjit-2.2 would have to be added).

Or just use pkg-config, since moonjit actually provides a .pc file!

(Going off-topic here but IMO CMake’s Find* modules are a disaster and no amount of support for Microsoft’s crappy toolchain is worth using them.)

**Comment by oilboi** [comment]
I'm going to bump this because I have the need for speed

**Comment by rubenwardy** [comment]
You can try building Minetest with MoonJIT, yourself, and see how it behaves. The solving of this issue would only effect what the official builds are created with, and not distro builds - unless moonjit was bundled

**Comment by ymph** [comment]
Just to add to the debate, as of today, october 9th 2020, on the readme of the MoonJIT repo (https://github.com/moonjit/moonjit), you have the message : 

> This code base does not have an active maintainer anymore, please read this Twitter thread to know more. If you are an existing contributor (or otherwise have an interest in maintaining this project actively) then please email me using the email address in my Twitter profile.
