### ISSUE TITLE
Shader errors in the dev version

### ISSUE THREAD

**Issue by Enrikoo** [minetest/minetest#9156]
##### Minetest 5.2.0-60bff1e6

https://gitlab.com/minetest/minetest/commit/60bff1e6cbf56e9a248bc4b0928dfc716cf04131

##### OS / Hardware

Operating system: Windows 7 Ultimate
CPU: Intel(R) Core(TM) i3 CPU

GPU model: Intel(R) HD Graphics
OpenGL version: 2.1.0

##### Summary
 I wanted to try out the new wave settings (perlin-type noise), then I noticed that the shaders are not working, so I was using the default settings and other shaders enabled, and there are still shader errors. Is there any way to fix that?

##### Steps to reproduce
Ever since the git commit hash 60bff1e6 have been released, shader errors have occured, and I am definitively sure that it's this git commit hash that have caused this by a few tests.

Image:
![screenshot_20191130_154815](https://user-images.githubusercontent.com/33701012/69901990-f4b1e280-1388-11ea-9cac-9f4d24c29d2b.png)

**Comment by TSafa-23** [comment]
I would recommend updating your drivers.

**Comment by SmallJoker** [comment]
Possible causes:
* Wrong or outdated GPU driver
* A mod disabled (or forgot to enable) texture opacity
* The mod is outdated

**Comment by rubenwardy** [comment]
Is there context to closing this before the OP replied?

**Comment by Enrikoo** [comment]
It could be a problem with minetest if the graphics are working in 5.1.0 but not in the 5.2.0-dev.
So you guys say, perlin type noise waves needs a better graphic card, instead of an old slow one.

**Comment by sfan5** [comment]
It looks like it has a problem with this line:
https://github.com/minetest/minetest/blob/f6de86ce4b9da21f16d3bcdbc0c55ce4cbe23067/client/shaders/nodes_shader/opengl_vertex.glsl#L84-L86

Which doesn't make any sense, since the code is syntactically valid and otherwise fine.

**Comment by paramat** [comment]
The error message suggests incorrect syntax, so possibly a code issue.

**Comment by appgurueu** [comment]
Probably you are running a dev version with shaders for an older version?
I. e. you have updated your Minetest, but not your shaders.

**Comment by jhooper04** [comment]
I just got the same error from a fresh install of 5.2.0. I fixed it by removing the / line continuation in the nodes_shader. Looks like this fix was made two days ago in master:

https://github.com/minetest/minetest/commit/c87d52a5fa21f31c2d68795822b48c8bf993ca6b
