### ISSUE TITLE
Players can be killed and player_falling_damage.ogg is played when damage is disabled

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9159]
##### Minetest version

https://github.com/minetest/minetest/commit/4b6bff46e14c6215828da5ca9ad2cb79aa517a6e

##### Summary

Players can be killed and player_falling_damage.ogg is played when damage is disabled

**Comment by SmallJoker** [comment]
The `immortal` armor group must be set on the player. This was introduced to have per-player damage system control. Apparently a mod (`3d_armor` maybe) clears it.

See also: #9022

**Comment by paramat** [comment]
See #8214
