### ISSUE TITLE
OBJ loading broken?

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9162]
##### Minetest version

```
5.1, regular install from the launchpad PPA
```

##### OS / Hardware

Operating system: Ubuntu

##### Summary

Minetest doesn't load my OBJ file properly, despite it being very simple. See the screenshots: 

For comparison: Same model (Lunar Lander by NASA, simplified using Blender) viewed using G3D:

![G3D Viewer](https://user-images.githubusercontent.com/34514239/70149865-40c29700-16a9-11ea-9d84-33da8e7b5b48.png)

In Minetest, it doesn't look as expected:

![Bildschirmfoto von 2019-12-04 15-19-09](https://user-images.githubusercontent.com/34514239/70149959-736c8f80-16a9-11ea-945c-b6bb03fe46bb.png)

##### Steps to reproduce

Try using the attached OBJ file as mesh for an entity / node. Uploaded as 
[LunarLander.txt](https://github.com/minetest/minetest/files/3922285/LunarLander.txt) because GitHub won't let me upload OBJ files here.

**Comment by NathanSalapat** [comment]
crashes minetest for me, error: `terminate called after throwing an instance of 'std::invalid_argument'
  what():  Mesh can't contain more than 65536 vertices
Aborted (core dumped)
`
File does load fine into Blender, likely just too large of a file for Minetest to handle properly.

**Comment by appgurueu** [comment]
My Minetest doesn't crash at all, it just doesn't load it properly.

I already ran a decimate modifier to reduce it from 100k faces to 20k faces. Still too much I guess :/

**Comment by appgurueu** [comment]
Update: It doesn't have 60k vertices, I examined the OBJ and it has "just" 44k of them.

**Comment by appgurueu** [comment]
Update: simplifying (=reducing the faces & vertices) the model extremely "fixes" it. Still a bug for large meshes.

**Comment by style-nine** [comment]
The pipeworks mod uses models (in obj format), and I think the valve has about 2000 vertices. That's probably a pretty good target to shoot for.

see https://gitlab.com/VanessaE/pipeworks/tree/master/models

**Comment by NathanSalapat** [comment]
Double check your UV mapping, and export options. Does the model display textures properly within Blender, or whatever software you are using to edit it? Import the OBJ and double check that the UVs are still there. If it's always white it sounds like a UV issue, as Minetest would just use random colors if there was a problem with the texture registration of the node.

**Comment by rubenwardy** [comment]
This is a limitation in the irrlicht engine. 64k is a lot of vertices, you should expect at most 5k for something in the world and 30-60k for a character. At the very most. Characters should be using b3d files as they can be animated

I think this issue can be closed because of those things
