### ISSUE TITLE
No Windows installer available for 5.1

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9167]
Seems to have been forgotten. This needs to be added to the release guidelines, and automated using #9166

**Comment by sfan5** [comment]
Not forgotten, on purpose. The WiX installer thing doesn't seem to run on Linux either.

**Comment by hecktest** [comment]
Is an installer necessary? MT does not dump anything in appdata or the registry (that I know of), and zips can be opened with explorer these days.
Can't speak for every win user's preference but zips are just better in every way. Installers seem like a 90s thing for really clueless people, a thing that should go away unless it's for something complicated like a driver.

**Comment by rubenwardy** [comment]
The installer adds a short cut, and makes updating easier. Windows users tend to be used to installers, and I raised this issue because I just had to teach someone how to extract a zip file

**Comment by paramat** [comment]
As a general point i rather agree with hecktest. In our unwaged and overwhelmed situation it is better that people learn to extract zips than core devs spend time and effort on low priority installers. Generally, we need to prioritise effort and shift some work from core devs to modders and users. MT cannot be like a commercial game, it has to be simpler (see roadmaps).

**Comment by benrob0329** [comment]
> In our unwaged and overwhelmed situation it is better that people learn to extract zips than core devs spend time and effort on low priority installers

But isn't core dev time wasted more by having to explain _how_ to install something, rather than making a one-time setup to build an installer that requires no explination?

> MT cannot be like a commercial game

Yup, hard to be a game when you're a content distribution platform :p

**Comment by paramat** [comment]
People will learn how to extract zips from many sources, not just core devs, very rarely from core devs. The time core devs spend on helping others by explaining stuff tends to be limited to a certain maximum of their own choice, so that will not increase.

I did not say MT was a game ;)

**Comment by Moth-Tolias** [comment]
paramat - if my own experiences are anything to go by you overestimate an unfortunate majority of windows users.

**Comment by rubenwardy** [comment]
Should we also stop supporting the PPAs and other installation based distribution methods? After all, a zip file is perfectly fine

**Comment by hecktest** [comment]
Windows opens zips with explorer if no archive manager is installed. Unless somebody is still stuck on XP.

**Comment by rubenwardy** [comment]
You can't run Minetest from a zip, you need to extract it out

**Comment by hecktest** [comment]
Oh, sure, the way it's treated like a folder might make it a little confusing.
Something a self-extracting zip would be ideal, 7za can spit one out easily. Now the OS difference might be a problem here...

**Comment by rubenwardy** [comment]
Given that we already have official support for Windows installers as of 5.0.0 (#6153), it would be good to actually use it

**Comment by hecktest** [comment]
Oh well, if it's there, use it.

**Comment by v-rob** [comment]
Honestly, the argument about people being able to use ZIP files also makes ContentDB useless.  You can download the mods from the forums, so ContentDB isn't necessary either.

But, this is a game (engine), so it shouldn't be hard to figure out.  Not everyone is well versed in computers, so they need more help.  An installer is perfect for this.

**Comment by paramat** [comment]
Sorry, i misunderstood and thought installers were a Windows-only thing and so low priority. I also do not understand the situation well :)

**Comment by zaoqi** [comment]
A single self-extracting exe storing data in `c:/User/.../.minetest` would be better

**Comment by v-rob** [comment]
> A single self-extracting exe storing data in `C:/User/.../.minetest` would be better

Extracting to a `.something` directory on Windows is the most annoying thing ever.  Directories starting with `.` are not hidden on Windows, so when you view the contents of their containing directory, they are always first alphabetically, which messes up people.

Also, even if it did hide the directory, that would not be ideal because not all mods are on ContentDB so you have to install them manually, and a hidden folder would just be another thing to mess up people.

**Comment by zaoqi** [comment]
I don't mean hidden directory.Just affected by minecraft

**Comment by hecktest** [comment]
Please no dotfiles or dotfolders; there is nothing wrong with storing data in a subdirectory of the game. You can keep separate versions and installs easily on one machine, as well as duplicate and delete them at will.

People who use the home directory for something like this must really love to complicate stuff for no good reason.
