### ISSUE TITLE
Serverlist Does Not Sanitize favoriteservers.txt

### ISSUE THREAD

**Issue by benrob0329** [minetest/minetest#9168]
##### Minetest version

```
5.1.0 (Flatpak)
```

##### OS / Hardware

Operating system: Fedora 31
CPU: Intel i5

##### Summary

If you enter certain characters into the Address input and attempt to connect, Minetest will add that "server" to the `favoriteservers.txt` file, notably `[` and `,`.

##### Steps to reproduce

1. Open Minetest
2. Go To The "Join Game" Tab
3. Enter any combination containing `[` or `,` and see the results.

With `,`:
![Screenshot from 2019-12-05 18-01-59](https://user-images.githubusercontent.com/19180682/70281631-88b8eb00-1789-11ea-80bb-42a41a7ad0e0.png)

With `[`:
![Screenshot from 2019-12-05 18-02-36](https://user-images.githubusercontent.com/19180682/70281653-940c1680-1789-11ea-9973-871f314db5ec.png)

**Comment by ClobberXD** [comment]
I think this might be due to `render_serverlist_row` not using `core.formspec_escape` for the address here:

https://github.com/minetest/minetest/blob/f6de86ce4b9da21f16d3bcdbc0c55ce4cbe23067/builtin/mainmenu/common.lua#L85-L94

**Comment by appgurueu** [comment]
Probably fixed by #10085 ?

**Comment by rubenwardy** [comment]
That doesn't touch the formspec much, it'll still need to escaped. Should be an easy fix
