### ISSUE TITLE
Formspec bgcolor ignores the color when fullscreen 

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9169]
5.1.0

It's impossible to set a background color for a form when the fullscreen parameter is set to true as well. The client just ignores the color.

Repro: Show a formspec with bgcolor[#fff;true]
It's gonna display a transparent black rather than the expected white.
Flip the boolean to false and the color will suddenly work.

**Comment by sfan5** [comment]
see also #8985, #8996

**Comment by rubenwardy** [comment]
Unfortunately, this was intentional. The element should be deprecated and replaced by an alternative that actually works

**Comment by hecktest** [comment]
Then the documentation needs fixing so that it doesn't lie.
