### ISSUE TITLE
macOSX: command+v doesn't work

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9179]
##### Minetest version

https://github.com/minetest/minetest/commit/103d9c5c536abd15a79eb7ed899fee29168bb14c

##### OS / Hardware
Operating system: Mac OS X

##### Summary
command+v doesn't work in minetest

##### Steps to reproduce
1. open minetest
2. `command+v` in any text box

**Comment by SmallJoker** [comment]
What does Ctrl+V, Cmd+Ctrl+V and Cmd+Shift+V do?

**Comment by zaoqi** [comment]
`Ctrl+V` does work

**Comment by SmallJoker** [comment]
Copy/pasting requests should be reported to Irrlicht directly if you would like to use Cmd+V rather than Ctrl+V.
