### ISSUE TITLE
Error compiling on Debian 10 Buster: LUA_JITLIBNAME was not declared in this scope

### ISSUE THREAD

**Issue by sbrl** [minetest/minetest#9180]
##### Minetest version

```
Commit 45bbe39d1f7958a38cb0a10357fe0baf1d725c52
(latest on the stable-5 branch)
```

##### OS / Hardware

Operating system: Raspbian 10 Buster
CPU: .....it's a Raspberry Pi 3B+

##### Summary
When I try to compile Minetest on Raspbian 10 Buster, I get the following errors:

```
[  0%] Building CXX object src/CMakeFiles/minetestserver.dir/script/cpp_api/s_base.cpp.o
/home/pi/minetest/src/script/cpp_api/s_base.cpp: In member function ‘void ScriptApiBase::clientOpenLibs(lua_State*)’:
/home/pi/minetest/src/script/cpp_api/s_base.cpp:152:5: error: ‘LUA_JITLIBNAME’ was not declared in this scope
   { LUA_JITLIBNAME,  luaopen_jit     },
     ^~~~~~~~~~~~~~
/home/pi/minetest/src/script/cpp_api/s_base.cpp:152:5: note: suggested alternative: ‘LUA_IOLIBNAME’
   { LUA_JITLIBNAME,  luaopen_jit     },
     ^~~~~~~~~~~~~~
     LUA_IOLIBNAME
/home/pi/minetest/src/script/cpp_api/s_base.cpp:152:22: error: ‘luaopen_jit’ was not declared in this scope
   { LUA_JITLIBNAME,  luaopen_jit     },
                      ^~~~~~~~~~~
/home/pi/minetest/src/script/cpp_api/s_base.cpp:152:22: note: suggested alternative: ‘luaopen_io’
   { LUA_JITLIBNAME,  luaopen_jit     },
                      ^~~~~~~~~~~
                      luaopen_io
/home/pi/minetest/src/script/cpp_api/s_base.cpp:154:2: error: could not convert ‘{{"", luaopen_base}, {"table", luaopen_table}, {"os", luaopen_os}, {"string", luaopen_string}, {"math", luaopen_math}, {"debug", luaopen_debug}, {<expression error>, <expression error>}}’ from ‘<brace-enclosed initializer list>’ to ‘const std::vector<std::pair<std::__cxx11::basic_string<char>, int (*)(lua_State*)> >’
  };
  ^
make[2]: *** [src/CMakeFiles/minetestserver.dir/build.make:583: src/CMakeFiles/minetestserver.dir/script/cpp_api/s_base.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:182: src/CMakeFiles/minetestserver.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

I am using the following commands to compile Minetest:

```bash
#!/usr/bin/env bash
set +x;
cd minetest;

export CPATH="/usr/include/lua5.1:/usr/include/luajit-2.1";

cmake . -DRUN_IN_PLACE=FALSE -DCMAKE_BUILD_TYPE=Release -DENABLE_SOUND=FALSE -DBUILD_SERVER=1 -DBUILD_CLIENT=0 -DVERSION_EXTRA=sbrl1 -DENABLE_SPATIAL=ON;
make;
```

I have installed all the dependencies specified on [this page](https://dev.minetest.net/Compiling_Minetest).

##### Steps to reproduce
1. Boot up a Raspberry Pi running Raspbian 10 Buster
2. Follow the build instructions for Minetest on the page lined above.
3. See error

I suspect I've missed something, but I can't find any guidance on this issue elsewhere.

**Comment by SmallJoker** [comment]
You could try to specify the paths directly in CMake:
`cmake . (other arguments) -DENABLE_LUAJIT=TRUE -DLUA_INCLUDE_DIR=/usr/include/luajit-2.1 -DLUA_LIBRARY=/usr/lib???/luajit??`

**Comment by sfan5** [comment]
> `export CPATH="/usr/include/lua5.1:/usr/include/luajit-2.1"`

Don't do this.
You can either use LuaJIT by specifying paths with cmake or use the Lua 5.1 that ships with Minetest (external Lua is <b>not supported</b>).

**Comment by sbrl** [comment]
Hey! Thanks for the advice @SmallJoker. I'm pretty sure that fixed it. There should really be a link on the wiki to the GitHub instructions, because those changes have worked for me I think.

I was going to wait until it has finished building before I commented and closed the issue, but @sfan5 appears to be in a bit of a hurry.
