### ISSUE TITLE
Buildbot script does not package mingw64 DLLs

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9181]
Building a Windows executable from Linux with mingw64, using the build scripts in the repo, results in a zip that isn't ready to run; it's missing three DLLs that must be manually copied over from wherever mingw64 keeps them.
**Request:**
Mention this in the build instructions, or make the build scripts at least attempt to find and pack the required libraries.

**Comment by sfan5** [comment]
duplicate #3009, #3666

**Comment by Fixer-007** [comment]
I just add this after mingw32-make package -j$(nproc) as ultra noob solution:

```
cd _CPack_Packages/win64/ZIP/
cp /mingw64/bin/libgcc_s_seh-1.dll minetest-*/bin
cp /mingw64/bin/libstdc++-6.dll minetest-*/bin
cp /mingw64/bin/libwinpthread-1.dll minetest-*/bin
zip -ur minetest-*.zip minetest-*
cp minetest-*.zip ../../../ 
```
