### ISSUE TITLE
Allow downloading binaries from Travis CI pull request builds.

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#9182]
## Problem
I use Windows, and I have never been able to compile Minetest on Windows after trying multiple times.  So, I use Linux inside a virtual machine to compile Minetest.  This is slower to compile and Minetest runs at about 15 FPS in a singlenode world and 5 FPS in Minimal.  This usually isn't a problem since I usually work in formspecs, but it means I can't work on anything else.

If Travis CI can be configured to allow downloading of the binaries, I wouldn't have to compile it myself (a few minutes faster) and I could run it on Windows at full FPS.  Also, if I ever want to test someone else's PR, I don't have to compile it myself every time since it's on Travis.

## Solutions
I don't know too much about this, but it appears that it might be possible to configure this to happen.  See https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci, which points to https://docs.travis-ci.com/user/deployment/releases/.  It might only work for releases and not pull requests, but I don't know.  If possible, it would likely only be necessary to make Travis keep the latest revision of a pull request.

## Alternatives
Waste a bunch of time, limit PR testing/making capabilities, and keep the overall slowdowns in productivity that people like me have :)

**Comment by sfan5** [comment]
FYI you can use the [buildbot](https://github.com/minetest/minetest/tree/master/util/buildbot) to build for Windows <i>inside</i> your Linux virtual machine.

**Comment by hecktest** [comment]
Yes, though keep in mind that the buildbot is not aware of mingw and will not pull or bundle it, so you have to provide it yourself and be wary of #9181
The availability of mingw can be sketchy on some distros, further complicating this.

**Comment by rubenwardy** [comment]
Travis is the wrong tool for this, gitlab should be used instead. You can configure it so that it only compiles win64
