### ISSUE TITLE
Sounds that are linked to player objects don't always play at the player object

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9183]
##### Minetest version
```
5.1.0
```

##### Summary
If you play a sound that is linked to a player object, it will only play at that's player spawn position instead of the actual position.
This is a regression from 5.0.0.

##### Steps to reproduce
* Get `luacmd` mod
* Start game, and do NOT move at all. Remember the position at which you spawned
* In console, enter `/lua minetest.sound_play("some_sound", {object=me})`, where `some_sound` is the name of a sound in the game
* Move away from your spawn position, then repeat the previous step

EXPECTED:
Sound plays at your position, always.

ACTUAL in 5.1.0:
Sound plays at your spawn position only, no matter where you actually are right now.

ACTUAL in 5.0.0:
Same as EXPECTED.

**Comment by sfan5** [comment]
duplicate, already fixed #9048
