### ISSUE TITLE
Change of behaviour after introduction of real formspec elements

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9186]
##### Minetest version

```
8e63d22d6472b61477f804dc5b00705650f90409
```

##### Summary

Elements in the same formspec priority are shuffled within the priority, resulting in some rendering differences with eg: boxes

Boxes were stored in a vector/list before, ensuring their order was maintained

##### Steps to reproduce

```lua
minetest.register_on_joinplayer(function(player)
	local fs = [[
		size[12,8]
		bgcolor[#00000000]
		box[0,0;3,3;#ffff0000]
		box[0,0;3,3;#ff0000ff]
	]]
	minetest.show_formspec(player:get_player_name(), "ss", fs)
end)
```

in 5.1.0 this shows a blue box on a red box, in 5.2.0-dev this shows only a red box

**Comment by rubenwardy** [comment]
I wonder how many formspecs this will break. It broke #8758 in a hard to debug way

**Comment by SmallJoker** [comment]
Before:
![grafik](https://user-images.githubusercontent.com/1497498/70652658-43962c80-1c53-11ea-94cc-5a67eeb89460.png)

After:
![grafik](https://user-images.githubusercontent.com/1497498/70652679-4db82b00-1c53-11ea-93e8-15d26e195f47.png)

```Lua
		box[3,7;3,1;#00A3FF]
		button[3,8.25;3,.5;name;]button[3,9.25;3,.5;name;]
		checkbox[3,8.5;name;Check me!;false]checkbox[3,9.5;name;Uncheck me now!;true]
		scrollbar[0,11.5;11.5,.5;horizontal;name;500]
		scrollbar[11.5,0;.5,11.5;vertical;name;0]
```

**Comment by DS-Minetest** [comment]
I've tried to reproduce in 5.1.0 and in current master (with minetest\_game).

@rubenwardy's example just created a red box (in both versions). How should one see a blue box there anyway? There are just an invisible yellow box and a red box directly above it.

@SmallJoker's example is missing essential things, like size or the snow image that seems to be blocking the checkbox. Is that a modified version of the minimal /formpsec?

**Comment by rubenwardy** [comment]
Looks like I messed up the order of rgba/argb

**Comment by SmallJoker** [comment]
@DS-Minetest These were styled buttons contained in the example code, but I agree it definitely lacks of the style elements. However, I can no longer reproduce this issue in current master.

@rubenwardy Is it still broken in master or did the sorting fix not solve the drawing issues?

**Comment by rubenwardy** [comment]
Looks like I messed up the order of rgba/argb.

Also, Krock made a fix to this recently to use std::stable_sort rather than std::sort. That may have fixes his issue

**Comment by rubenwardy** [comment]
this fixed my issue
