### ISSUE TITLE
Dynamic, complex shape selectionboxes

### ISSUE THREAD

**Issue by The-personified-devil** [minetest/minetest#9196]
Sorry for asking, this question came up a lot already. 
So I want better selection boxes, because squares on mobs look awful. But I need to clarifie one thing first: Selection boxes are independent of collision boxes, right?
But I still need another information: Can you make complex selection boxes, that are not only a cube or something like that?
Just for clarification: There is nothing planned for advanced selection boxes in Minetest 5.2.0?
So is there a way to redefine the selection boxes (I mean like define it at the initialization of the entitie  and redefine it if something particular happens.)?
I would need this for a dirty coded function which would get the rotation of the entitie and adjust the selection box as needed. Even if I would probably program something that gets into Minetest and is a lot cleaner (Has SB already coded STH like this? If yes please link down below).
For that I would need an explanation of how the selection box and pointing code works at the moment. And I would like an out of sight function which doesn't compute selection boxes which aren't reachable (Is there STH like this already?).

Thanks in advance

**Comment by paramat** [comment]
> Selection boxes are independent of collision boxes, right?

Yes.
> Can you make complex selection boxes, that are not only a cube or something like that?

Not currently.
> There is nothing planned for advanced selection boxes in Minetest 5.2.0?

Nothing planned.
> And I would like an out of sight function which doesn't compute selection boxes which aren't reachable

What do you mean by 'compute'?

**Comment by paramat** [comment]
Partly a duplicate, see #1586 #2721 #3996 #6812 #6847 #7407 #7652 #8109 #8900 
Wow, this comes up a lot.

**Comment by The-personified-devil** [comment]
Really..... Why do you mention that posts are duplicates of posts that link to duplicates and it all goes to a circle with like actually no post being an honest discussion. @paramat you literally added links to this post which is probably going to end up as  only a post in which duplicates are mentioned

**Comment by The-personified-devil** [comment]
This way NOBODY gets helped because you don't get information only links with that you end up at your own post

**Comment by paramat** [comment]
Some of those issues are detailed discussions, as you can see if you take the time to look through them. I only linked to all because any of those may contain useful information.
#3996 is probably the best discussion.

**Comment by The-personified-devil** [comment]
I literally spend like 5 hours clicking trough such links and duplicates and most of the discussions end up as discussions about collision boxes. You do not want to imagine who many custom searches I fired to find out something.

**Comment by paramat** [comment]
4 out of those 9 issues involve selectionboxes. Collisionboxes and selectionboxes are closely related so discussion of one tends to involve discussion of the other, which is why i linked them all.
Please stop complaining when i have made an effort to help you or i will close and lock the thread.

**Comment by The-personified-devil** [comment]
Sorry I don't want to be rude. My problem is, that I clicked on your links and even if the issues were already closed, you added n mentioned label: `
@paramat paramat mentioned this issue 1 hour ago
Question for help with selectionboxes #9196 `
I'm a little angry, because this issue does not contain any important information just yet and @paramat you mentioned it already. But you have to understand why I'm angry: I spent literally hours clicking trough such issues which linked to unfinished issues with a lot of links included. You have to understand, that you don't help people if you mention unimportant issues. There's one thing to prevent this from being misleading is, that you just say that there's no real information included in them. This would have prevented me from losing a lot of time. Anyway I appreciate, that you spend your time on this issue which is at least for the half of it a duplicate of a lot of other issues.
Thank you for that.

I just want to know if anyone is able to explain to me how the current code works and if there's sb who knows a way to implement the features that I want (rotating selection boxes and complex selection boxes). I would implement it myself. But I need help from sb who understands the code and can provide me with ideas.

**Comment by Moth-Tolias** [comment]
github automatically back-links issues when they get mentioned.

**Comment by rubenwardy** [comment]
Collision boxes and selection boxes use very similar code. You can think of selection as collision with a 3d line protruding from the player's crosshair.

That discussion paramat linked discuses the problems that rotated and complex collision boxes would need to solve in detail. Note that simply mentioning an issue creates a back link, you can most ignore those and read the comments there.

Complex selection boxes and collision boxes can be made using node boxes, please read the lua API reference. It's currently not possible to create either of these using non-cubiod shapes. 

You can change the selection box at run time using object properties.


For the code for selection boxes, you'd want to look at raycast and pointed_thing. These are called from within the game loop to determine what the player is looking at and to handle any actions.

**Comment by The-personified-devil** [comment]
Why are complex selection boxes not already implemented. They would be just a lot of blocks overlaid. The problem is, that this would be a little CPU extensive, so why can't you use a mesh? Would it be easy to implement or way too much work? And rotating basically would be just changing the position of the selection boxes as computed using the angle.

**Comment by rubenwardy** [comment]
> Why are complex selection boxes not already implemented. They would be just a lot of blocks overlaid.

Cuboid ones are already possible. 

> They would be just a lot of blocks overlaid. The problem is, that this would be a little CPU extensive, so why can't you use a mesh? Would it be easy to implement or way too much work? And rotating basically would be just changing the position of the selection boxes as computed using the angle.

You need a completely new algorithm to be able to calculate collisions (including selection) for non-cubiod rotatable selection boxes. Minetest currently uses an Axis-Aligned Bounding Box (AABB) collision algorithm, which is very efficient but only allows non-rotated (ie: Axis-aligned) and cubiod-composed (ie: bounding box) collision

**Comment by The-personified-devil** [comment]
Sorry for saying that the way I said it. It meant to mean: A mesh out of cubes, but everything, which is not reachable, because it's inside another cube will be ignored. I don't know if this is the case yet. If not I would make it so, that you could define objects, that are not cuboids (don't have every face) so that faces, which aren't even shown, would not use up CPU time. And how do you define such a selection box, that's made of multiple cuboids? Another question: How exactly do you do that: 
> You can change the selection box at run time using object properties.

Thanks in advance

**Comment by rubenwardy** [comment]
OK, looks like I was mistake - whilst with nodes you can have more than one cubiod in the selection and collision boxes, with entities you can only have at most one.

-----------

Here's an answer for changing the selection box at run-time anyway:

The modding book [describes how object properties work](https://rubenwardy.com/minetest_modding_book/en/map/objects.html) and the lua API reference [documents the list of available object properties](https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L6116)

You'd set the selectionbox like so:

```lua
object:set_properties({
     selectionbox = {-0.5, 0.0, -0.5, 0.5, 1.0, 0.5},
})
```

Here's another issue you may be interested in: https://github.com/minetest/minetest/issues/3996

**Comment by The-personified-devil** [comment]
Mentioncounter for #3996: 3 
Sry I've read this one way to often.

How can I sole that you have only one cuboid for selection in entities? This is pretty bad.

**Comment by SmallJoker** [comment]
@The-personified-devil Because nobody in Minetest attempted to make it depend on the animation frame.
The selection/collision boxes also aren't rotatable. This is probably what you'd expect for entities, but the current AABB collision detection does not support that (nobody implemented it), thus there was also no efforts in making the selection boxes rotatable.

**Comment by The-personified-devil** [comment]
I understand this, it's a lot of work, not even Mojang implemented it into MC. And also in MC people cry, because (mainly in PVP) they don't hit what they want to hit. This is (also in MT) a big problem if you're trying to shoot a cow/ pig etc. Then sometimes, you don't hit what you want and you loose arrows.

@SmallJoker I mean you could solve the issue with the non-rotating selection box pretty easy: You just write a program which moves the points of the selection box according to the angle, while letting the other code just as is.

The way to solve the issue with only one selection box is just to enable more than one (You should probably also activate non-cuboid selection boxes). I don't know why the code should not support just one face selection box computing.

**Comment by The-personified-devil** [comment]
I mean, it would be overkill to make rotating collision boxes (Or make it rotate in 90° angles.).
As I said, I would make a program, which uses the rotation to compute, where the corners have to be and basically set a new selection box based on this (I would make the mobs rotate only in 3° steps to save some cpu time and maybe also make them rotate way less, so that they only rotate, when really needed.)

The problem is, that you would need some more or less complex code to control the proper corner position if you have more than one selection box. I'm looking after a solution for that.

**Comment by The-personified-devil** [comment]
Problem: I need to know where the according code files are. Thanks

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/master/src/environment.cpp#L97

**Comment by The-personified-devil** [comment]
Thanks

**Comment by The-personified-devil** [comment]
I don't understand all of this code.
But I suppose, that this makes it a little hard to add more than one selection box: 
`v3f found_boxcenter(0, 0, 0);` 
found here: 
[https://github.com/minetest/minetest/blob/master/src/environment.cpp#L128](url) 
I wonder if the selection box is greatly off center, the code would locate the node somewhere false.
Can sb please show the line in which this is prevented.

I think this finds out the position of the node, so to add more selection boxes would confuse it.
To solve that you would need to give the selection boxes a variable (or two): A variable, which defines if the selection box is the parent selection box and if it is one, then it gets used to find the position of the selection box. If not it links to the parent selection box, which is then used to find out the location.

This also prevents, that you can use selection boxes, which are non-cuboids (They don't have every face (I talked about this earlier.).). So you would have to code a function to ignore certain faces, which are not reachable, because they are hidden inside another selection box. 
But I don't know if this would even be a CPU load issue, because from looking at the code I think it would not even prove, if these faces are hit by the ray. I would need help to find this out.

Another needed information is: Can you attach variables to selection boxes?

**Comment by The-personified-devil** [comment]
So I have been working way too long on trying to code code, which rotates the selection box, when I noticed that you cannot set the position of corners with the code at the moment. Sooo .... all my code is useless. 

But there's one thing I do not understand: Why would it be so hard to implement definable corners?

**Comment by The-personified-devil** [comment]
If nobody is able to make me a good decision how to do those two things in a week, I'm going to lay this project on ice, close the issue and maybe start it again in some months when I've understood how the code works and how I could edit in, what I want.

Thanks

**Comment by ExeVirus** [comment]
Hello, I'm relatively new to Minetest (<2 years), and have some background in collision and Minetest modding (lots of C background, but haven't started contributing to the engine yet). 

I have read all those linked discussions, and something I have not seen come up yet is the possibility of a rotated, entity-only collision box (or some combination of spheres, boxes, etc.). 

The reason I bring this up, is often people are concerned about kinda two categories:
1. Collisions with arrows, guns, players, other mobs
2. Collisions with the world terrain (so that they don't pass through objects

I think by splitting up these two collision types (world and entity), we can fix both issues with one stone.

Imagine a third bounding box (or set of boxes, spheres, etc.), that is for entity collision only. It can be more complex because it only has to check for nearby entities, not check terrain nodes.

This opens up the normal collision box to only deal with terrain collisions, thereby allowing mobs to have boxes as large as the outer limits of the mob/player, rather than trying to capture 90% of the mob/player volume.

This change would increase world->entity collision processing speed, and can make comple eneity collisions performant. 

Thoughts?

**Comment by ExeVirus** [comment]
I've been doing further inspection on the environment and collision code. Essentially, this would require changing the object.collisionMoveSimple and object.collide functions to not take into account other objects for those collisions, just terrain.

Then we can implement a separate object/entity collision system similar to how selection boxes are separate.

**Comment by ExeVirus** [comment]
In fact, collisionMoveSimple already has a boolean to check if it should calculate collide with objects (I expected those to be mixed with nodes in general). 

That simplifies this discussion, as we can merely adapt lines [352](https://github.com/minetest/minetest/blob/aa8df112ff42d94b6dc59a0153d989bd8c0b115e/src/collision.cpp#L352)-[408](https://github.com/minetest/minetest/blob/aa8df112ff42d94b6dc59a0153d989bd8c0b115e/src/collision.cpp#L408) to do collision between objects with more complex collision shapes, and will lower the impact on performance. 

As a side-note, after reading through the collision code, I believe I can make it more performant, does that code take a lot of processing?

**Comment by paramat** [comment]
Keeping in mind this issue is for selectionboxes ...

> Imagine a third bounding box (or set of boxes, spheres, etc.), that is for entity collision only. It can be more complex because it only has to check for nearby entities, not check terrain nodes.
This opens up the normal collision box to only deal with terrain collisions,

I cannot see much benefit, because improving the terrain-colliding collisionbox is the primary intention of these discussions. For example, a long thin object that currently has to use a collisionbox equal in X and Z dimensions.
So all this effort and complxity to make advanced entity to entity collisions (which happen far less) does not seem worth doing.

The-personified-devil,
>  I mean you could solve the issue with the non-rotating selection box pretty easy: You just write a program which moves the points of the selection box according to the angle, while letting the other code just as is.

That is theoretically a nice idea, but does not solve the problem of a long thin object at 45 degrees to world axes, the selectionbox would still be a single cuboid and so cannot roughly match the shape of the object. This would only help match the shape when the object is axis-aligned.

**Comment by ExeVirus** [comment]
I'm sorry for my mistake in going after the wrong thread (got lost reading them all). 

As for selection boxes, they are separate boxes from the collision box code, and rely on raytracing. it's a lot easier to raytrace through a sphere than a box. I don't see why we can't make multi-sphere selection boxes that rotate. 

Then, as for the terrain collision issue for diagnolally aligned, long, thing models, I see where that could be an issue, and I will have to think on a better solution than rotation
Perhaps the cylinder idea suggested earlier is best for that. 

Finally, I can understand that you may see object to object collisions as relatively minor concerns, but having good collisions for them allows for much improved shooting physics, as well as allowing for new creative physics. 

For example, let's say I make a canal boat paddle wheel model. as it spins, each paddle would have moving collision box. if you touched the rising edge, you would be lifted up, and if you touched the falling edge you would be pushed down. 

Another example, a windmill. As the windmail sails spin, so too should the collision box, so users cannot walk through it, but also can jump and ride on top.

**Comment by The-personified-devil** [comment]
> Keeping in mind this issue is for selectionboxes ...
> 
> > Imagine a third bounding box (or set of boxes, spheres, etc.), that is for entity collision only. It can be more complex because it only has to check for nearby entities, not check terrain nodes.
> > This opens up the normal collision box to only deal with terrain collisions,
> 
> I cannot see much benefit, because improving the terrain-colliding collisionbox is the primary intention of these discussions. For example, a long thin object that currently has to use a collisionbox equal in X and Z dimensions.
> So all this effort and complxity to make advanced (but much more intensive) entity to entity collisions (which happen far less) does not seem worth doing.
> 
> The-personified-devil,
> 
> > I mean you could solve the issue with the non-rotating selection box pretty easy: You just write a program which moves the points of the selection box according to the angle, while letting the other code just as is.
> 
> That is theoretically a nice idea, but does not solve the problem of a long thin object at 45 degrees to world axes, the selectionbox would still be a single cuboid and so cannot roughly match the shape of the object. This would only help match the shape when the object is axis-aligned.

This just doesn't do what I want. As I said in one of my last posts, there is already a selection box system implemented, and the cuboid can be hit by a ray from any given angle. I do not understand why you could not create a cuboid, which has a side, which is at an angle (That not every inside angle of the cuboid has to be at an 90 degree angle.). The thing is I would suggest that you would not make every corner settable to an own position, but rather just edit the code, so that you could type in not only the max z, but type in a max z for the left line connecting from point A to point D (counting started from the upper left corner in the top view and going to the right) and a max z for the line from point B to point C. For further visualization I attached some files.
I personally  suppose, that the engine would allow for it, but just the code, which feeds in the selection box, would have to be changed.
[visualization.zip](https://github.com/minetest/minetest/files/3975673/visualization.zip)

Sorry for my bad gimp skills
RIP for anyone without blender!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! (Download it, its OS and freeeeeeeee)

**Comment by The-personified-devil** [comment]
Please don't mind my long keyboard presses, I was just done after spending half an hour on this post and just wanting to send it. I just wanted to do some s***.
Thanks

P.S.: Yeah, I could edit the post, but I wanted to let everything how it was.

**Comment by The-personified-devil** [comment]
Sorry for my second last post. You should not be able to make selection boxes, which don't have a cuboid shape. You should only add in this option, if you wanted to compute the rotation in the lua code.
I highly suggest to code this function in the c++ code.

Because I'm seeing, that nobody wants to program this I'm gonna close this issue and leave it behind as inspiration for others.

**Comment by ExeVirus** [comment]
Hey now, it's not that we (I) don't want to, it's just that there are other
priorities for my engine programming at the moment. I'll take a look at
processing required in the future.

**Comment by paramat** [comment]
> there is already a selection box system implemented, and the cuboid can be hit by a ray from any given angle. I do not understand why you could not create a cuboid, which has a side, which is at an angle (That not every inside angle of the cuboid has to be at an 90 degree angle.).

Ok i see, however, i doubt this avoids the performance problems, an axis-aligned cuboid is always far easier and more lightweight to calculate intersection for.
The fact that even Minecraft does not do this is a big hint about the practicality.
