### ISSUE TITLE
Option to display more debug log output in chat

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9199]
## Problem

I'm always frustrated when warnings don't appear in chat. Currently, only errors appear here. In development, I find it inconvenient to be forced to always look back in my console/log to find warnings, and I frequently overlook warnings that might be important to me, especially after a long testing session (switching back and forth between game and console (the real console, not the in-game one!) isn't fun).

If the game would tell me directly in my face all those warnings, it would make things easier.

## Solutions

Add a setting to configure which debug log messages are allowed to appear in chat. Basically the same as `debug_log_level`, but for chat.

In this setting, you can then choose the minimum log level to put stuff into chat (error, warning, action, info, etc.). E.g. if you select "warning", both errors and warnings will appear.

Also, I suggest to use a yellow font when a warning appears in chat.

## Alternatives

Don't add a setting, but instead show warnings in chat by default. Simpler solution, but might annoy players.

## Additional context

A very long time ago, Minetest displayed warnings in the chat as well, but this feature was removed because players complained (games had a lot of warnings).

Well, that's not really a good fix. The warnings were never fixed, just hidden from view. And IMHO many warnings do expose real problems that should not be ignored.
As a developer, I definitely WANT that Minetest screams right into my face that something went bad, for quality assurance. But on the other hand, I understand the rationale why warnings are no longer in chat. Therefore, I suggested a setting as a compromise.

**Comment by Grigor903** [comment]
Joined Github so I could post here. What would be nice is a configurable string for the debug info display. I like having position, pitch, yaw and pointed object, but it'd be nice if the rest was optional, especially as this display is always there by default. Everyone could have the debug info display of their dreams!

**Comment by rubenwardy** [comment]
Please don't post offtopic and unrelated requests in issues, make a new issue instead
