### ISSUE TITLE
can't type single quotes or curly braces on mac

### ISSUE THREAD

**Issue by DougStoker** [minetest/minetest#9204]
##### Minetest version

```
minetest 5.1.0
```

##### OS / Hardware

Operating system: macos 10.14.5 mojave
CPU: 2.3 GHz Intel Core i5

GPU model:
OpenGL version:

##### Summary

unable to type single quotes or curly braces

##### Steps to reproduce

try  to type ' or { or  }

**Comment by SmallJoker** [comment]
Can't fix. This is an Irrlicht issue. See also: #302 (and the issue cross-references there)
Steps to solve the problem:
1) Write an issue or patch for the Irrlicht repository
2) Hope it gets fixed
3) Use another keyboard layout that works better (UK/American)
