### ISSUE TITLE
Chat filters out % sign

### ISSUE THREAD

**Issue by gpcf** [minetest/minetest#9207]
##### Minetest version

```
root@belgium:/var/games/minetest-server/.minetest/mods/advtrains# /usr/games/minetestserver --version
Minetest 5.1.0-dev-4017200c-dirty (Linux)
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"

```

##### OS / Hardware

Operating system: Debian 10
CPU: Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
##### Summary

Whenever someone types the "%" (percent) sign in chat. The sign gets ommited.
##### Steps to reproduce
Just say in chat something like "Disabling profiler gave us 30% less CPU ussage", the "%" gets ommited.

**Comment by ClobberXD** [comment]
This issue has already been fixed in 4b6bff46e14c6215828da5ca9ad2cb79aa517a6e.
