### ISSUE TITLE
Right-drag can place items in crafting-output slot.

### ISSUE THREAD

**Issue by ManaUser** [minetest/minetest#9212]
##### Minetest version
5.0.1

##### OS / Hardware
Operating system: Windows 7

##### Summary
Right-drag can place items in the crafting-output slot. This is basically harmless as far as I can tell, but since you can't put anything in there by clicking normally, I assume it shouldn't be possible by right-dragging either.

##### Steps to reproduce
Hold a stack of items and right-drag across the crafting output slot, with the crafting grid empty.

**Comment by SmallJoker** [comment]
The stack you're holding is exactly the contents of the crafting output slot. Except that it's always selected.

Not sure if this is actually an issue because it's what you'd expect of an inventory slot.

**Comment by ManaUser** [comment]
I'm not quite sure what you mean on the first part. But you're right. I just downloaded the dev build and could no longer replicate this, so it would seem it's already be fixed.
