### ISSUE TITLE
Configurable Debug Info String

### ISSUE THREAD

**Issue by Grigor903** [minetest/minetest#9213]
## Problem

The debug info appears by default on screen. I feel it contains more information than is useful to the average user, and clutters the display. But it's still nice to know your position, and what object you're pointing to.

## Solutions

It would be nice to have a configurable string, say in minetest.conf, which allows the user to alter what appears on screen by default. The syntax could be something like:
$V = Minetest version
$S = seed
$X / $Y / $Z = player X Y Z position
$P = pitch
$Y = yaw
$y = yaw name (eg, East)
$O = object being pointed to
and so on, with options to include text strings.

So, in the minetest.conf you could have a line like `debug_info = "Position:"  $X $Y $Z | $y | $O` and onscreen the display would be:

Position 25.2 1.5 71.8 | West | default:stone

If the variable is blank or absent the default string is used.

## Alternatives

This can be done with mods, but requires hiding the debug info each time (so far as I know).

**Comment by SmallJoker** [comment]
This is a good input on possible implementations for #7245

Duplicate.

**Comment by Grigor903** [comment]
Hi SmallJoker, thanks for sorting that out. Should I post a short version of it in #7245 to get it out there, or will it get seen as is?

Cheers,

G.

________________________________

**Comment by SmallJoker** [comment]
@Grigor903 It's unhandy to have information spread across several issues,. Thus it's surely not wrong to post your suggestion there as well so that it's seen quicker.
