### ISSUE TITLE
Magnifier for accessibility

### ISSUE THREAD

**Issue by KungTwo** [minetest/minetest#9214]
Ricky has failing eyesight. He loves the game Minetest and I thought of a way to help him out. 
I'm a Unity game developer and I've got an idea that might fix it through a mod or something. I'd like to make a shape, maybe a square at the center of the screen to magnify the image infront so that he can see and read stuff. Help would be appreciated.

**Comment by rubenwardy** [comment]
Have you tried the accessibility options built into Windows or whatever you use? They usually have a tool to magnify around the mouse already

**Comment by ClobberXD** [comment]
Zooming in a part of the screen isn't possible in Minetest (yet?). But as a workaround, maybe try zooming the whole screen? Would that help?

**Comment by KungTwo** [comment]
You know I messed around with windows Magnifier, set it to lens and it seems like a good solution. I'm running it by Ricky to see what he thinks. I don't know if he already knows about it. I think he wanted the UI to be bigger, but the problem is, I know as a game programmer a lot of the in game text painted onto the side of bricks and stuff is not UI and therefore can't really be magnified in any other way.

**Comment by hecktest** [comment]
The DPI setting can make the whole UI bigger, but you're right, this won't affect signposts.
![high DPI](https://user-images.githubusercontent.com/42101236/71145717-cc4c3400-2222-11ea-9647-2b38f221f82c.png)
There is a zoom feature that lowers the FOV on the press of a button, but some servers disable it. You can change the key for it in the esc-menu while playing.
![zoom](https://user-images.githubusercontent.com/42101236/71145720-ceae8e00-2222-11ea-8993-c57dfc0cab12.gif)
You can also lower the FOV in the settings to have something like this on all the time. You lose some peripheral vision but objects in front of you are always magnified.

Or maybe, if you don't mind some aliasing...
![stereo](https://user-images.githubusercontent.com/42101236/71147856-5ea40600-222a-11ea-9787-435dd85e54dd.png)
![stereo2](https://user-images.githubusercontent.com/42101236/71147868-64015080-222a-11ea-8d71-68454eacbd77.png)
![stereo3](https://user-images.githubusercontent.com/42101236/71147869-6499e700-222a-11ea-87c2-028e9e83d102.png)
This is a shader hack, here's how to apply it:
Navigate to minetest/client/shaders/3d_interlaced_merge and replace the contents of opengl_fragment.glsl with this:
```

uniform sampler2D baseTexture;
uniform sampler2D normalTexture;
uniform sampler2D textureFlags;

#define leftImage baseTexture
#define rightImage normalTexture
#define maskImage textureFlags

vec2 lerp( vec2 l, vec2 r, float t ) {
	return l + ( r - l ) * t;
}

void main(void)
{
	vec2 uv = gl_TexCoord[0].st;
	
	vec2 quv = uv * 2 - 1;
	
	
	
	// Adjust this to control magnification.
	float z = 0.5;
	
	
	
	z = max( z, 0 );
	
	float m = 1 + z;
		
	quv = quv * m;
	
	uv = lerp( uv, quv * 0.5 + 0.5, clamp( pow( distance( uv*2-1, vec2(0,0) ) / m, m ), 0, 1 ) );
	uv = ( uv - 0.5 ) * ( 1 - z ) + 0.5;
	
	vec4 left = texture2D(leftImage, uv).rgba;
	vec4 color;
	
	color = left;
	
	gl_FragColor = color;
}

```
Then, set 3d_mode to "interlaced" and it should work. Of course, this is an ugly, dirty and wasteful hack that hijacks one of the game's VR modes to do this. But it's the only "exposed" postprocess shader that I could find.

**Comment by KungTwo** [comment]
Thank you all, I'll forward the page, so that he can see the suggestions!

**Comment by rubenwardy** [comment]
Closing, as no response. Bump if that was not sufficient for you
