### ISSUE TITLE
World saving database path must escape/replace IPv6 address colons on Windows

### ISSUE THREAD

**Issue by r4sas** [minetest/minetest#9215]
##### Minetest 5.1.0

```
2019-12-18 02:09:30: INFO[Main]: Connecting to server at [2001:db8::1]:30000
2019-12-18 02:09:30: INFO[Main]: Database_SQLite3: Failed to create directory "C:\Games\minetest\bin\..\worlds\server_[2001:db8::1]_30000"
```

##### OS / Hardware

Operating system: Windows (doesn't matter which version)

##### Summary

Due to limitations in Windows path supported chars, colon (`:`) is prohobited for usage, its used only in disk selection (ex. `C:\`).
Such symbols must be replaced.

##### Steps to reproduce

Connect to server directly via IPv6 address when `enable_local_map_saving` option is enabled on Windows.

**Comment by SmallJoker** [comment]
Is this only a Windows problem, or does the restriction apply to FAT* and NTFS filesystems?

**Comment by r4sas** [comment]
> Is this only a Windows problem, or does the restriction apply to FAT* and NTFS filesystems?

That restriction comes since early days of DOS, not depending on filesystem.

**Comment by hecktest** [comment]
Uh oh, can of worms.
DOS-like systems forbid the following chars in path chunks, regardless of the filesystem.
`\ / : * ? " < > |`

Utilities for dealing with win/dos filesystems may enforce this even if the FS doesn't specifically restrict it.

Just hash the damn thing.

**Comment by Montandalar** [comment]
>` \ / : * ? " < > |`

None of those characters are valid hostnames or valid in IPv4/v6 addresses, so it's really irrelevant.

**Comment by r4sas** [comment]
> > ` \ / : * ? " < > |`
> 
> None of those characters are valid hostnames or valid in IPv4/v6 addresses, so it's really irrelevant.

huh, a u really? go RTFM about IPv6.

**Comment by SmallJoker** [comment]
Hashing is definitely the wrong approach here - hence the thumbs down reaction above. String replacing the affected characters with `_` would be sufficient so that the world..
1) .. can be saved on Windows and FAT/NTFS filesystems
2) .. still has a readable name to figure out which server was saved

**Comment by Montandalar** [comment]
Correction: `:` is relevant for all IPv6 addresses and / for subnets, but you can't connect to a subnet.

I'm working on a PR that will do that replacement `:` -> `_`, while preserving compatibility with any worlds people may have under linux already.

**Comment by r4sas** [comment]
There already place where port colon was replaced...
