### ISSUE TITLE
Attachment light level is stuck

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9216]
_5.1.0, 5.2.0dev_
Another silly attachment issue.
So I've got this setup:
- Entity with mesh is attached to the player's bone. Let's call this the "hat".
- Player is attached to a dummy entity. Let's call it, well, "dummy".

Now the hat's light level is stuck at what it was when the dummy was attached, ignoring all possible changes in natural or artificial light. Detaching the player from the dummy will get it unstuck. Other manipulations like moving the dummy will not.
![hats](https://user-images.githubusercontent.com/42101236/71073660-18df3300-2181-11ea-8b04-d2e9bc21df94.png)

**Comment by SmallJoker** [comment]
I'm glad you're reporting those bugs, but annoyed at the same time because there are now over 900 open issues.

**Comment by hecktest** [comment]
_is:issue is:open bug - 339 Open_
Only about a third of those are real bugs.
