### ISSUE TITLE
WaveHeight is unecessarily limited to 1

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#9217]
I just noticed that #9007 limits the setting for wave height to 1, but since #8994 this is no longer needed.
Instead the top wave is now automatically adjusted. At least we should allow waves one meter/block high, which would be a setting of 2. Even higher values are possible, but would adjust the lower waves blow a block - which still looks and behaves correctly.

In gist, we should extend the range from [0,1] to [0,4] (or at the very, very least [0,2])

Let's discuss... I'll file a PR.

**Comment by paramat** [comment]
Fine for me, its harmless and some may like a large amplitude for some special purpose, so a large upper limit is ok. I will +1 a PR.

**Comment by Wuzzy2** [comment]
But it should be tested whether using the new MAX value doesn't cause any graphical glitches.

**Comment by lhofhansl** [comment]
I did already. It does not. I had fixed that in #8994 already (but missed that we have set the limit).
The only glitch is that we get the blue water tint at a fixed level, which might be above the waves.

I'll just file a PR and we can try.

**Comment by paramat** [comment]
I think harmless graphical glitches are acceptable. There may be some uses of the feature where the 'glitch' is not a problem for a user for some reason. So i prefer to allow far more freedom than what seems suitable or necessary. Setting limits are more for avoiding actual harm.
