### ISSUE TITLE
Resized torchlike nodes don't visually attach to node

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9221]
##### Minetest version
```
5.1.0
```

##### OS / Hardware
Operating system: GNU/Linux

##### Summary
If you set `visual_scale` for a torchlike node to a value other than 1, then the node will not visually touch the side of a node.

This is because instead of touching the wall/ceiling/floor, the texture will be rendered at the center of the node.

##### Steps to reproduce
1. Place a torchlike node with `visual_scale` unequal to 1 on a solid node and see how it looks

---

You can download DevToys <https://forum.minetest.net/viewtopic.php?f=9&t=23802> for example nodes.
Give yourself `testnodes:torchlike_double` (double size), `testnodes:torchlike_half` (half size) and `testnodes:torchlike` (normal size) and place them at walls, ceilings and floors.

It will look like this:
[EDIT by paramat: added image]

![6D3OSDrXwFhalf](https://user-images.githubusercontent.com/3686677/71290641-42a67e80-2368-11ea-8767-38ce1eb03b7a.jpg)

It is expected that the white border of the node texture visually touches the solid nodes. But this is only the case for the normal-sized torchlike nodes, not for the scaled ones.

##### Other context

The documentation `lua_api.txt` is aware of this:

```
         visual_scale = 1.0,
         -- Supported for drawtypes "plantlike", "signlike", "torchlike",
         -- "firelike", "mesh".
         -- For plantlike and firelike, the image will start at the bottom of the
         -- node, for the other drawtypes the image will be centered on the node.
         -- Note that positioning for "torchlike" may still change.
```

Which suggests the centered torch is not really intended. Which makes sense, as I don't really see why we want to have floating torches.

**Comment by paramat** [comment]
Indeed low priority.
Also note that some mods may be relying on this behaviour.
So i am not convinced it is worth altering.

**Comment by Wuzzy2** [comment]
I doubt that mods rely on this behavior. Note that the documentation includes an explicit warning, so compability alone should not be a reason to reject this.

But I agree with low priority; the torchlike drawtype is rarely used nowadays. This is just one of the bugs I found while I created DevToys to play around with all the drawtypes and see what happened. :D

**Comment by paramat** [comment]
By 'rely on', i mean that a few mods will be coded to function properly with torchlike having its current appearence. Probably only a very few mods though, and i agree that does not rule out a change. So i should be more neutral on this, will edit my comment.
