### ISSUE TITLE
Store SRP "Passwords" Clientside

### ISSUE THREAD

**Issue by Lejo1** [minetest/minetest#9222]
## Problem

We can't check if the server behind a address is the server you wanna access and this server may access you password-hash.
Password Storage would be possible with this as well which is the main point why I would really like something like this.

## Solutions

We could store the SRP password hash and let the client check if salt is the correct one or just send the finish Srp-hash.
As the SRP-hash can't be reverted to the real password it's also not really insecure. We just need a good password manager(e.g. seahorse) or storage system(not sure which exist in Windows).

## Alternatives

Only Storing the salt just doesn't include the pretty safe password storage.

**Comment by rubenwardy** [comment]
This breaks security by reverting to a weak pre-srp like solution. It's best to avoid rolling your own security protocols at all cost

This is also an XY problem - you say you want to do something (X), when really there's something else you're trying to do (Y) that would have a better way to do it. The better way to "save passwords" without storing passwords is to allow access tokens to be issued and then stored in the client and used later on. You wouldn't be able to change your password with these tokens, but would be able to access your account. That is something that may be going a bit too far anyway in terms of complexity. I'm not against a simple password store

**Comment by Lejo1** [comment]
> This breaks security by reverting to a weak pre-srp like solution. It's best to avoid rolling your own security protocols at all cost

Sure but I though it's pre-5.0 and as older clients aren't able to access the server it should be no Problem.

> The better way to "save passwords" without storing passwords is to allow access tokens to be issued and then stored in the client and used later on. You wouldn't be able to change your password with these tokens, but would be able to access your account. That is something that may be going a bit too far anyway in terms of complexity.

I agree, it would be more secure but a bit too complex. I think the easier way is to just store the srp-hashs as secure as normal passwords.

**Comment by rubenwardy** [comment]
>   Sure but I though it's pre-5.0 and as older clients aren't able to access the server it should be no Problem.

No, my point was this completely breaks the entire point of SRP and the reason that it was introduced, making it much less secure

> I agree, it would be more secure but a bit too complex. I think the easier way is to just store the srp-hashs as secure as normal passwords.

See above

**Comment by sfan5** [comment]
I understand neither the problem you want to solve nor the solution you propose.
Notably, SRP [does not](https://en.wikipedia.org/wiki/Secure_Remote_Password_protocol) use any straightforward hashing of user passwords. The data stored in `auth.txt` is not a hash.

**Comment by Lejo1** [comment]
> No, my point was this completely breaks the entire point of SRP and the reason that it was introduced, making it much less secure

We could just disallow password storage for the legacy password-hashes.

> I understand neither the problem you want to solve nor the solution you propose.
Notably, SRP does not use any straightforward hashing of user passwords. The data stored in auth.txt is not a hash.

I want to create a password storage.
Sure SRP are no real hashes but it's possible anyway as the salt is always the same for the same server. We just need to do it separate for each server.

**Comment by rubenwardy** [comment]
> We could just disallow password storage for the legacy password-hashes.

This has nothing to do with legacy password hashes, whatsoever

**Comment by Lejo1** [comment]
My Idea wasn’t to go back to normal passwords. I wanna keep SRP but store either the raw password of the player or the Salted hash before applying the srp-keys.

**Comment by SmallJoker** [comment]
> We can't check if the server behind a address is the server you wanna access and this server may access you password-hash.

MITM attacks are very unlikely for Minetest, and SRP exists to not send the password in plaintext. The server should not have a chance to read back the player's password based on the salt, although I'm not entirely sure about that.

**Comment by rubenwardy** [comment]
The better solution for this would be #1566

I disagree with the reason that issue was closed
