### ISSUE TITLE
'address' documentation seems misleading

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9232]
https://github.com/minetest/minetest/blob/ffe7f96d24d1b1810bd6458894676f1ac2a4a31a/minetest.conf.example#L1055-L1059
In testing, this does not have to be left blank to start a local server (unless i did something wrong).
Minor documentation issue.

**Comment by rubenwardy** [comment]
The main menu changes the settings, try testing with --go

**Comment by paramat** [comment]
>  try testing with --go

Sorry, i am not familiar with this command or where to enter it.

**Comment by SmallJoker** [comment]
```bash
minetest --go --address "" --world mtg
```

Tested, works.

**Comment by paramat** [comment]
Sorry, i do not understand what rubenwardy was suggesting, and what 'works'?

**Comment by SmallJoker** [comment]
> The main menu changes the settings

This means, the description there is only relevant when running Minetest from command line. The main menu already does that for you when starting a local server from there.

> minetest --go --address "" --world mtg

This is an example. "address" modifies the `minetest.conf` setting accordingly (IIRC) to start a local server.

**Comment by paramat** [comment]
Ahh thanks. I am not familiar with command line server creation at all.
So, i do not know whether the documentation can be changed, i will leave this issue to someone else with better understanding.

jastevenson303, what is the emoticon for?
