### ISSUE TITLE
Gradually rewrites minetest in Rust

### ISSUE THREAD

**Issue by mooads09** [minetest/minetest#9233]
The C++ programming language provides inadequate security guarantees, and no advantages over Rust

**Comment by Moth-Tolias** [comment]
here's one advantage: all the developers know c++. i doubt any of them know rust.

**Comment by rubenwardy** [comment]
C++ is significantly more mature. Last time I looked into rust, there weren't many rendering libraries or simple game libraries that didn't just add Oop to OpenGL

This is a massive undertaking with little outside-observable benefit. It would be better to work on it from scratch in rust, perhaps having a compatibility layer for our lua API

**Comment by obj-obj** [comment]
This might be viable now with https://github.com/bevyengine/bevy, although bevy isn't near mature and it'd still require a lot of work

**Comment by orowith2os** [comment]
Another update: a partial rewrite can be done for the bits that could make use of it via the `cxx` Rust crate, which has (more or less) perfect C++ interop. It can also be used to trial Rust, and see if it makes sense keeping it.

**Comment by jordan4ibanez** [comment]
Hello there. Perhaps we can reopen this issue?

**Comment by appgurueu** [comment]
> Hello there. Perhaps we can reopen this issue?

Why?

**Comment by jordan4ibanez** [comment]
Well, why not?

**Comment by appgurueu** [comment]
> Well, why not?

> all the developers know c++. i doubt any of them know rust.

(the second part doesn't hold anymore, but still, the majority of developers is more familiar with C++)

Either way, trying to get Rust into the engine requires work, and would bloat our build chain significantly. This needs to be justified well.

**Comment by obj-obj** [comment]
> > Well, why not?
> 
> > all the developers know c++. i doubt any of them know rust.
> 
> (the second part doesn't hold anymore, but still, the majority of developers is more familiar with C++)
> 
> Either way, trying to get Rust into the engine requires work, and would bloat our build chain significantly. This needs to be justified well.

Yeah, and it would be painful to manage two languages in your build chain
