### ISSUE TITLE
3d_paralax_strength setting is at the wrong place

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#9244]
##### Minetest version
```
Minetest 5.2.0-dev-37f771a9-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

##### OS / Hardware
Operating system: linux
CPU: intel

GPU model: intel
OpenGL version: 4.5

##### Summary

In the All Settings, `3d_paralax_strength` is shown in `Graphics/In-Game/Shaders/Parallax Occlusion` although it belongs to the 3D settings in `Graphics/In-Game/Advanced`.
This is confusing because `3d_paralax_strength` sounds similar to the Parallax Occlusion settings.

##### Steps to reproduce

Use the All Settings and search for paral

**Comment by SmallJoker** [comment]
A PR would be less effort than writing this issue.

**Comment by paramat** [comment]
Maybe we can fix that spelling mistake too?
