### ISSUE TITLE
Formspec Version 3 with real co-ordinates breaks hypertext action tags

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#9253]
##### Minetest version

Any version that supports ```formspec_version[3]```

##### Summary

Executing any formspec with ```minetest.show_formspec``` with the following code results in broken hover, and clickable areas:

```lua
"formspec_version[3]size[8, 2]hypertext[0, 0;8, 2;demo;" .. minetest.formspec_escape(
[=[<action name="test2">go to test 2</action>
a<action name="test3">go to test 3</action> a
aa<action name="test4">go to test 4</action> a
aaa<action name="test5">go to test 5</action>]=]) .. "]"
```

Video: https://gfycat.com/responsibleharshabyssiniangroundhornbill

#### Fix:

By setting ```formspec_version[1]``` it allows the hypertext actions to function as expected:

Video with the above change: https://gfycat.com/thosegreedyandeancondor

**Comment by Jordach** [comment]
Possibly not a bug, but another underlying issue/cause:

Formspecs that are smaller than the content trying to "fit" into it are not rendered and are simply *unusable* or partially rendered.

**Comment by pyrollo** [comment]
Hi Jordach,

I tried with Minetest (master) and your formspec (the version 3 one) and had no problem.

But ! But the formspec look and feel is different than the one on your video. The problem could be related to something outside this formspec defintion.

Could you give more information about the context ? How to display a formspec looking like yours ?

Here is what I see:
![screenshot_20191230_104901](https://user-images.githubusercontent.com/13189280/71576807-1b7f4800-2af2-11ea-8c46-9f824855b3a5.png)

**Comment by SmallJoker** [comment]
@Jordach Please clarify your problem. Could it be that this was fixed in a commit since your report?

**Comment by rubenwardy** [comment]
No response
