### ISSUE TITLE
Incorrect inventory image of world-aligned nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9256]
##### Minetest version
```
5.0.1
```

##### Summary
The world-aligned texture of node is incorrect in the “wielditem” form of the node.

##### Steps to reproduce
In Minimal Development Test, do `/giveme experimental:tiled`.

Hold it in your hand. Then place it.

Expected: The wield texture shows one tile only, like when placed in the world.
Actual: The wield texture shows the entire texture (8×8 tiles), shrinked down.

Also compare with the stair and slab variants of this node.

**Comment by Wuzzy2** [comment]
Correction: I meant “inventory image”, not “wielditem” or “wield texture”.

**Comment by SmallJoker** [comment]
Maybe add this to #9209 which is already a list of broken drawtypes.

**Comment by paramat** [comment]
> Correction: I meant “inventory image”, not “wielditem” or “wield texture”.

Have you edited the first post? Does not look like it, i know you may not be able to. This will cause a lot of confusion, please post a new comment with the correct text.

**Comment by NathanSalapat** [comment]
known workaround for full nodes is to do this.
```tiles = {{name='img.png', align_style='world', scale=4}},
inventory_image = '[inventorycube{img.png&[sheet:4x4:1,1{img.png&[sheet:4x4:1,1{img.png&[sheet:4x4:1,1',```
just match the scale value to the sheet values. Obviously this doesn't work on nodeboxes.

**Comment by Wuzzy2** [comment]
Here's a screenshot to explain what I mean:

https://satoshiupload.com/images/6cSbFNoEy1.png

This shows `experimental:tiled` from `minimal`. The wield image is correct. The inventory image is wrong.

---

PS: I have contacted GitHub staff a while ago to fix their broken website. No reply so far (except the standard automated one to show they are alive).

**Comment by paramat** [comment]
Edited your post to show image (as i know you cannot do this).

I am not sure Github can be described as 'broken', i seem to remember the problems are caused by you disabling certain proprietary software. Maybe this is why they do not bother responding, especially if you tell them their website is 'broken' and it is their fault, when it is your own ;)

**Comment by Wuzzy2** [comment]
#9299 will fix this.
