### ISSUE TITLE
Node is not set clicking other node if on_rightclick of second one is defined.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9261]
##### Minetest version
```
Minetest-5.2.0-dev.
```
##### Summary
If you register a node with 'on_rightclick' callback defined, afterwards in the game clicking that node with other node that actually should be set for unknown reason is not set. I`m not 100% sure this is a bug, probably I may do something wrong.

##### Steps to reproduce
1. Register any node with 'on_rightclick' callback independently on the content of what it does.
2. Set this node and click it with any wielded node and you will see it won`t be set.

**Comment by SmallJoker** [comment]
This is the intended behaviour. It overrides the default rightclick mechanism. Use shift+place if you would like to place a node on one of its sides.

**Comment by Andrey2470T** [comment]
Almost six months have been gone and there has not been any answer. So I think to close it?
