### ISSUE TITLE
Formspec tooltip element prevents clicking on fields defined before it

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#9264]
##### Minetest version

```
5.2 dev, git commit 4445889 (12/26/2019)
```

##### OS / Hardware

Operating system: Windows 10 Home
CPU: Intel i7-3770K @ 3.5GHz, 8.00 GB ram

##### Summary

I got [a bug report on the Minetest forum](https://forum.minetest.net/viewtopic.php?f=9&t=22926&p=364349#p363976) for my "commoditymarket" mod that said that two of the fields in its formspec could no longer be clicked on in the latest 5.2 dev build. I confirmed that this was the case, and in the course of tinkering with it I believe I figured out why. There was a "tooltip[" formspec element defined right after the field elements that covered the region of the formspec the fields were in, and when when I moved that tooltip to _before_ the field definitions they became clickable again. [This is the line of the commit that fixed the issue in my mod](https://github.com/FaceDeer/commoditymarket/commit/79b07ac837cfdf90914b3742c438db08e163e589#diff-73aee5e045cc19fed882f8e87ca15018R346) (ignore the various minetest.formspec_escape calls that were added in that commit, those were to fix a separate issue unrelated to this one).

##### Steps to reproduce

As described above, I encountered this in my commoditymarket mod. It can be reproduced by installing version 0e7c5c5 or earlier of that mod, placing a traveller's caravan in world, clicking on it, going to the "Market Orders" tab, and trying to select one of the "Quantity" or "Price" fields.

I can whip up some test code if these steps are troublesome.

**Comment by DS-Minetest** [comment]
:thinking: I think, making rect mode tooltips invisible might fix this. The visibility is not needed for drawing the tooltip:
https://github.com/minetest/minetest/blob/44458896d9097c15c722c5bffb3d72e14962b7ce/src/gui/guiFormSpecMenu.cpp#L3274-L3288
The rect mode tooltips are just bound to `IGUIElement`s for parenting reasons.

**Comment by DS-Minetest** [comment]
#9266
