### ISSUE TITLE
hud_set_hotbar_[selected_]image() methods don't accept texture mods

### ISSUE THREAD

**Issue by Warr1024** [minetest/minetest#9268]
##### Minetest version
```
Minetest 5.2.0-dev-8e63d22d (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=0
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=0
STATIC_SHAREDIR="."
```

##### OS / Hardware
Operating system:
- `Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux`

CPU:
- `Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz`

##### Summary
`player:hud_set_hotbar_image(texturename)` and `player:hud_set_hotbar_selected_image(texturename)` methods don't work if `texturename` contains texture modifiers.

###### Minimal repro:
`player:hud_set_hotbar_image("[combine:1x1")` (in an on_joinplayer callback, globalstep, MT.after, or whatever)

###### Expected result:
- HUD hotbar background is replaced with (in this case) a completely transparent image.

###### Actual result:
- HUD hotbar background is unchanged.
- Error message in log stream:
  - `ERROR[Main]: Server sent wrong Hud hotbar image (sent value: '[combine:1x1')`

**N.B.** this is a _contrived minimal example_ to demonstrate the problem efficiently.  I'm aware that the specific behavior could be achieved by pre-creating a `blank.png` image.  This is impractical for more complex scenarios, like where the background of each individual slot of a hotbar needs to vary based on some dynamic criteria at runtime, and pre-building textures for each case is completely impractical.

I also tried making the built-in hotbar backgrounds blank and using custom image HUDs as a workaround, but it failed, because:
- Even with z_order, there doesn't seem to be a way to get custom HUD elements to display _behind_ built-in ones.
- Calculating the positioning/scaling/offset of a custom image HUD to match that of the built-in hotbar is fiddly at best, and probably very fragile in the event of varying DPI, screen sizes, etc.

**Comment by paramat** [comment]
Texture mods may just not be applied, as they are primarily for objects/items/nodes. So possibly more a feature request than a bug.

**Comment by Warr1024** [comment]
It's not that they're not applied, it's that the code is explicitly looking for an image on disk/cache that matches a physical filename:

https://github.com/minetest/minetest/blob/master/src/network/clientpackethandler.cpp#L1221

This explicitly prevents using texture mods before whatever layer is called that should check for an apply them.  The only reasonable reason I can think of to add a check like this is to prevent a crash (we allow and handle malformed textures in many other cases and just generate dummies for those cases) but I haven't yet had a chance to test what happens if I disable that check.

I'll give that a shot in a minute...

**Comment by Warr1024** [comment]
Commenting out those checks, plus the corresponding ones at https://github.com/minetest/minetest/blob/master/src/client/hud.cpp#L225, caused the hotbar to behave as I expected with the code I'm testing with.

I'm now looking for regressions, or any other kind of misbehavior that could have justified those checks in the first place.  If anyone has any suggestions for things I could try, please let me know...
