### ISSUE TITLE
Super Flat Worlds

### ISSUE THREAD

**Issue by MrTeeXD** [minetest/minetest#9274]
## Problem
So, the Flat option in Minetest does not nessessarly generate a Flat world with nothing. Currently, it looks like this :
![minetest_w8HpK0ctOb](https://user-images.githubusercontent.com/37266538/71645383-429b6c80-2ce0-11ea-8142-c8b3c40949df.png)
I dont like how this looks because I have to spent extra time making the terrian flat for building paths which is rather tiring.

A clear and concise description of what the problem is.
I am interested in Building a Building Server, a server where people vcan come and Build Creative Creations and have their own plots to do so

## Solutions

Having the option Super Flat in the MapGen would give a Flat world with nothing but Flat Grass floors.

## Alternatives

There are no alternatives to what I can find on the Forums

## Additional context

N/A

**Comment by Wuzzy2** [comment]
:-1: Please close this as invalid.

`mg_flags = light,biomes,nodecorations,nodungeons,nocaves`

**Comment by MrTeeXD** [comment]
I did try to add that to the map_meta.txt and It did not work

**Comment by Wuzzy2** [comment]
`minetest.conf`.

**Comment by MrTeeXD** [comment]
Do I have to make that?

**Comment by SmallJoker** [comment]
For new worlds: create `minetest.conf` and add that configuration line.
For existing worlds: add that configuration line to `map_meta.txt` and delete the `map.sqlite` file to delete the generated map data.

**Comment by MrTeeXD** [comment]
Ahh it worked, thank you so much
