### ISSUE TITLE
Bottom side of world-aligned node textures misbehaves while placing nodes along X axis

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9275]
##### Minetest version
```
5.2.0-dev @ 44458896d9097c15c722c5bffb3d72e14962b7ce
```

##### Summary
The texture of the bottom side of world-aligned-textured nodes will change when you place these nodes along the X axis. This is strange, because the texture never changes for any other side.

##### Steps to reproduce
1. Play `minimal`
2. Give yourself `experimental:tiled`
3. Place a long line line of `experimental:tiled` nodes so they float in the air, along the X axis (try both directions)
4. Look how the textures behave at each side

EXPECTED: The textures on already-placed nodes don't automatically change at any sides.
ACTUAL: On the lower side of the nodes, the textures change after you place an adjacent node. The other 5 sides of the nodes are fine.

**Comment by paramat** [comment]
@numberZero any ideas?

**Comment by numberZero** [comment]
Wrong sign used in computations, probably.

**Comment by numberZero** [comment]
Probably here:
https://github.com/minetest/minetest/blob/7c0e0c34ecb66e044f59cbab03a4c12fc7838e97/src/client/mapblock_mesh.cpp#L446-L449
or maybe here:
https://github.com/minetest/minetest/blob/7c0e0c34ecb66e044f59cbab03a4c12fc7838e97/src/client/mapblock_mesh.cpp#L429-L430
