### ISSUE TITLE
minetest.colorize doesn't work with formspec labels

### ISSUE THREAD

**Issue by Amaz1** [minetest/minetest#9277]
##### Minetest version
44458896d9097c15c722c5bffb3d72e14962b7ce

##### Summary
Using minetest.colorize with a label in a formspec doesn't seem to work anymore:
![screenshot_20200101_223842](https://user-images.githubusercontent.com/4390945/71646991-82b21d80-2ce7-11ea-8545-1ddaf58d67cf.png)

##### Steps to reproduce
Add this node to a mod, and right-click it:
```
minetest.register_node("tmpnodes:7", {
	description = "Colorize in labels",
	on_rightclick = function(pos, node, clicker)
		local name = clicker:get_player_name()
		minetest.show_formspec(name, "test", "size[4,4]" ..
			"real_coordinates[true]" ..
			"label[1,1;White]" ..
			"label[1,2;" .. minetest.colorize("red", "Red") .. "]")
	end,
})
```
And this commit seemed to fix a previous issue with this:
https://github.com/minetest/minetest/commit/c2458d3d3a7f1ce309861e237fa52c13b7342e34

**Comment by Df458** [comment]
@SmallJoker Could this be related to what you were fixing with #9187, or is it a different issue?

**Comment by SmallJoker** [comment]
Will be fixed by  #9187

**Comment by Amaz1** [comment]
Ah, great!
Can this be closed then, or should it be left open till that's merged?

**Comment by SmallJoker** [comment]
Basically the PR reports this as broken (thus fixing it) so this is kind of a duplicate.
