### ISSUE TITLE
Minetest running in full screen on Linux does not take focus back after losing it (e.g. caused by video recording software)

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#9283]
#### Minetest version

```
Minetest 5.1.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

#### OS / Hardware

Operating system: Ubuntu Linux 18.04.3 LTS, Xfce 4.12
CPU: Pentium(R) Dual-Core CPU E6300 @ 2.80GHz

#### Summary

Game running in full screen and loosing the focus doesn't take the focus back so the controls become totally broken (not responding to mouse/keyboard at all). The losing of the focus is usually caused by screen recording software. Then the game must be killed by switching screen to a tty by hitting one of the `Ctrl+Alt+F#` combinations and then logging in. 
I also created the issure referring to this in the screen recorder repository (https://github.com/MaartenBaert/ssr/issues/744), but the dev things that the "fullscreen function of the game is a bit broken", and I'm not sure if it is really true or or not.

##### Related minetest.conf values
```
fullscreen = true
keymap_rangeselect = 
screen_h = 768
screen_w = 1366
```

#### Steps to reproduce

1. Install/build latest minetest stable version (5.1.0)
2. Start the game and use a program that could steal it's focus while it is running, e.g. install and run latest version of simplescreenrecorder (version 0.3.11, https://github.com/MaartenBaert/ssr), start game using it:
    1. In first options page select `Record OpenGL`, in `OpenGL settings` dialog fill in the values for `Command`, and `Working directory`, make sure `Launch automatically` checkbox is unchecked, optionally check the `Limit application frame rate` check box, close the dialog.
    2. In next page set output file, optionally check `Separate file per segment` and `Add timestamp` checkboxes output options such as container (e.g. avi), codecs (e.g. libxvid & libmp3lame) and bitrate for them
    3. In the last page set hotkey for recording, hit cancel recording, go back to first settings page, check option `Launch automatically`, don't change anything in next page so the game should start automatically while entering last page.
3. Create/load a world or connect to server, trigger the event that would steal focus from the game (e.g. hit screen recording key to start recording, then after a while to stop, the game should lose focus)
4. See how the game loses focus and doesn't take it back as controls become broken, now you must use `Ctrl+Alt+F#` combination to kill it.

**Comment by rubenwardy** [comment]
I suggest using Ubuntu's fullscreen toggle rather than changing fullscreen in the config. It works considerably better. Press alt+f11 with the window active. You may need to Google how to enable this feature if nothing happens

I've been meaning to fix minetest's fullscreen but never got around to it

**Comment by juozaspo** [comment]
Ubuntu full screen is worrking fine with screen recording software I'm using, just game fullscreen is incompatible as screen recorder always steals focus from game during video save time.

**Comment by rubenwardy** [comment]
Yeah, I'm planning on making the game's fullscreen use the same method as Ubuntu's fullscreen

**Comment by HybridDog** [comment]
There's a command which can toggle fullscreen:
```bash
wmctrl -x -r minetest -b toggle,fullscreen
```
"The  property change  is  achived  by  using  the  EWMH  _NET_WM_STATE  request."
[Extended Window Manager Hints](https://specifications.freedesktop.org/wm-spec/wm-spec-1.3.html)

**Comment by benrob0329** [comment]
I support the use of window hints for "borderless window" full screen node.

**Comment by ucodelukas** [comment]
same problem here

**Comment by sfan5** [comment]
Fixed by https://github.com/minetest/irrlicht/compare/393793f...c84d8ac
