### ISSUE TITLE
The comment symbol (#) alone next to blank key is not ignored in change keys dialog and ingame

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#9286]
##### Minetest version

```
Minetest 5.1.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
```
Minetest 5.2.0-dev-debug-44458896 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 18.04 LTS
CPU: Pentium(R) Dual-Core  CPU E6300 @ 2.80GHz

##### Summary

Adding a comment symbol (#) to `minetest.conf` right after a blank key definition line shows the comment symbol in key configuration dialog instead of blank. Adding more text after the symbol is ignored. In screenshot below the configuration line is `keymap_rangeselect = #` and in dialog it is show as a key instead of a blank spot.
![Darbalaukis 2020-01-05 19:21:30](https://user-images.githubusercontent.com/6626242/71783562-2dc91c80-2ff1-11ea-853f-e81eb1b40f90.png)
The same key defined works ingame too instead of being ignored (not used), where like in `minetest.conf.example` this should mean a symbol that starts a comment.

##### Steps to reproduce

1. Install/build latest stable and/or dev. version of minetest
2. Add a comment symbol right after a blank key definition, e.g. add `keymap_rangeselect = #` to `minetest.conf`
3. Launch minetest, open change keys dialog, see a has symbol instead of blank similar to screenshot from above, go to a world, click hash tag symbol, see a shortcut with the hashtag for a key activate.

**Comment by sfan5** [comment]
Not a bug, the configuration file format only supports full-line comments but no inline comments.
<pre>
some_setting = value # this is not a comment
# this is a comment
</pre>
