### ISSUE TITLE
place_failed node sound does not play when node was occupied

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9289]
##### Minetest version
```
5.1.0
```

##### Summary
If you try to place a node inside a node that is `walkable` but not `buildable_to`, placement will fail. This is correct behavior.
However, the `place_failed` sound of the node you tried to place will not be played.

###### Test case for `devtest`

1. Play `devtest` game (https://git.minetest.land/Wuzzy/devtest)
2. Get `soundstuff:place_failed` and `testnodes:nodebox_fixed`
3. Place the nodebox node on the floor
4. Try to place the sound node on the floor below the nodebox node

The placement of your sound node should be denied because the target node is occupied.

The `place_failed` sound should play. But it does not play.

###### Generalized test case
Place a node with `place_failed` sound and place it inside any `walkable`, non-`buildable_to` node that does not fill out the full cube.

When your placement fails, the sound should play. But it does not play.
The `place_failed` sound DOES work when you try to place the node inside yourself.

##### Notifications
@DS-Minetest

**Comment by Desour** [comment]
I'm still sceptical about the usefulness of such a sound. Predicting a placement fail sound that is settable per node is very specialized.
