### ISSUE TITLE
Mesh node with waving=1 does not wave properly

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9291]
##### Minetest version
```
5.2.0-dev @ 44458896d9097c15c722c5bffb3d72e14962b7ce
```

##### Summary
Nodes of `drawtype="mesh"` and with the property `waving=1` do not wave properly.

##### Steps to reproduce
1. Activate waving plants
2. Place a mesh node that has `waving=1`

If you have installed `devtest` <https://forum.minetest.net/viewtopic.php?f=50&t=24030>, use the node `testnodes:mesh_waving1` for testing. This is a green pyramid mesh.

![nvfjwl82uM](https://user-images.githubusercontent.com/3686677/71939637-4da44000-31ab-11ea-98a2-c0cf0ae0680e.png)

The bottom face is not connected properly to the other faces.

For comparison, a `waving=2` mesh is placed next to it, which waves properly.

**Comment by paramat** [comment]
Edited to add your image.

**Comment by Wuzzy2** [comment]
Hmmm, kinda a duplicate, maybe.

But #5871 is more concerned about the documentation. I'm not sure how to proceed.

**Comment by paramat** [comment]
#5871 is a detailed discussion, and not just about documentation, so i will close this one.
You could add your post above to that issue?
