### ISSUE TITLE
Large firelike nodes z-fight with each other

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9292]
##### Minetest version
```
5.2.0-dev @ 44458896d9097c15c722c5bffb3d72e14962b7ce
```

##### Summary
Nodes of `drawtype="firelike"` and with a large value for `visual_scale` will z-fight with each other.

##### Steps to reproduce
1. Place a node with `drawtype="firelike"` and `visual_scale=2.0` (or another large-ish value)
2. Place more of this node around it, in all directions (left, right, diagonal)
3. Walk around and move camera and see if you spot z-fighting

If you have installed `devtest` <https://forum.minetest.net/viewtopic.php?f=50&t=24030>, use the node `testnodes:firelike_double` for testing.

![KqDeLavjNV](https://user-images.githubusercontent.com/3686677/71939823-d9b66780-31ab-11ea-8675-bc9c91cad580.png)

##### Additional context
Compare with `drawtype="plantlike"` and large `visual_scale` (also included in `devtest`). Those nodes don't z-fight, even if large.
I think the trick that `plantlike` nodes use is that there's a tiny offset and/or difference in angle for each node, thus avoiding the z-fighting.

So I suppose the fix for `firelike` nodes is to implement a similar strategy.

**Comment by paramat** [comment]
Added your image.

Meh low priority, they overlap because they are big, which is rare. I would rather keep the textures axis-aligned.
Offsetting the diagonals of plantlike is more acceptable because they are diagonals. Axis-aligned stuff is more 'sacred' =)

**Comment by Wuzzy2** [comment]
Also affects large `signlike` and large `torchlike` nodes.

I agree, low priority. But maybe it makes sense to add a warning in `lua_api.txt`. E.g.

> `visual_scale` should not be larger than X for `firelike`, `signlike` and `torchlike`

**Comment by paramat** [comment]
It is only a problem if nodes are close together.

:-1: for an angle offset.

**Comment by Wuzzy2** [comment]
What about a tiny left/right/back/forth offset?

**Comment by SmallJoker** [comment]
Is there even a node drawtype where overlapping vertices do not result in z-fighting?
I think this should be collected in one issue (maybe #9276) because you'll probably end up listing all existing drawtypes.

**Comment by Wuzzy2** [comment]
#9276 is different because it is not exactly related to the `liquid` drawtype, but more related to `waving`.

Anyway, making a “master issue” to collect all z-fighting issues might be helpful. But I won't do it.

**Comment by paramat** [comment]
> a tiny left/right/back/forth offset

... will still cause z fighting.
I think this issue should be closed.

**Comment by Wuzzy2** [comment]
It won't work if the offset is the same for all nodes, but if each node uses a slightly different offset according to a simple system, overlap can be eliminated.

Here's a pattern for offset values to apply to the rendered nodes based on their coordinates; it will be repeated infinitely on the X/Z plane:

```
0123
4567
6701
2345
```

How to read this:

Each digit stands for one of 8 possible offsets (0-7). These 8 offsets are just some hardcoded offsets along the X/Z axis.
The top left digit is for X=0, Z=0. The digit right from it is for X=1, Z=0, and so on.
The pattern also has an Y rule: If you go up the Y layers, add 1 to each digit (modulo 8).

This pattern is built in a way that neighbors (horizontally, vertically and diagonally) do not have the same offset, therefore avoiding overlapping.

**Comment by hecktest** [comment]
Never fight z-fighting with world position offsets. Use depth bias.

**Comment by paramat** [comment]
https://github.com/minetest/minetest/pull/9298#issuecomment-573316964
Wuzzy2 no longer likes using position offset for firelike, this is very low priority but could be solved using depth bias.
