### ISSUE TITLE
Entities are not tonemapped

### ISSUE THREAD

**Issue by hecktest** [minetest/minetest#9301]
5.1.0 and anything else with tonemapping

When shaders with the "tone mapping" option are enabled, a tonemapping ramp is applied to the scene via the nodes shader. (as opposed to using a postprocess shader like it's normally done.)

That shader is not applied to entities, resulting in mismatched lighting between objects and nodes. This is most apparent with falling nodes.

Here you can see how the same colors are used for entities regardless of whether tonemapping is enabled or not.

![tonemapping](https://user-images.githubusercontent.com/42101236/72201413-04c2e480-3454-11ea-9c7c-f5f7cdafbd3b.png)

**Comment by hecktest** [comment]
No Joker, this is a bug. With a light level under 14, objects tend to appear too bright or too dark compared to their surroundings, because of the divergent response to light.

**Comment by Df458** [comment]
In the current master, entities aren't rendered with any custom shaders at all, just the builtin irrlicht ones. #9272 fixes this (partially), it might be worthwhile to split that PR in two to get entities rendering like everything else in the world does.

**Comment by SmallJoker** [comment]
@hecktest Apparently entity shaders are not implemented. If you request an implementation it is a feature request. It would be a bug if there's broken code for object tone-mapping.

**Comment by paramat** [comment]
I can understand considering it a bug, but yes more of a feature request.

**Comment by beyondlimits** [comment]
Entities aren't even minimally shaded, let alone tone-mapped.

**Comment by lhofhansl** [comment]
FWIW. I tried to put real lighting on entities (so that players and mobs do not look like they're not part of the world), but found that almost all model lack the necessary normals - so I gave up. Not the same issue, but perhaps related.

**Comment by paramat** [comment]
> When shaders with the "tone mapping" option are enabled, a tonemapping ramp is applied to the scene via the nodes shader. (as opposed to using a postprocess shader like it's normally done.)

Actually, i do consider this as also being a bug.
I am just realising how ridiculous this is implementation is, only applying to nodes. I had not realised how it was done and assumed the obvious (even to me) was done: applying it to everything.
This is yet another RBA mess. It was a mistake that this implementation of tone mapping was merged, no one should have approved it.
