### ISSUE TITLE
Remove “weight” property of objects

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9306]
## Problem

Objects have a property called “weight” but from looking around the source code it seems it does not have any effect. So what's the point?

## Solutions

Remove it.

**Comment by rubenwardy** [comment]
if a property like this is to be used, then it should be called *mass* instead

**Comment by paramat** [comment]
Can it be harmlessly removed without messing up network packets and network compatibility?
And yes it should be 'mass' if we use/keep it.

**Comment by paramat** [comment]
We could at least remove it from docs. I wonder if it can be, and is, set and used by mods?
