### ISSUE TITLE
Some locale file are not generated.

### ISSUE THREAD

**Issue by queenmedley** [minetest/minetest#9318]
```
Minetest 5.1.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"

```

##### OS / Hardware

Operating system: CPU:intel i5-4690

GPU model : nivida 1060
OpenGL version : 3.1.0

##### Summary

Some locale files are not generated.

##### Steps to reproduce

I installed minetest through archlinux binary package and found there were not locale folder and file "/usr/share/minetest/locale/ko".
So I tried to compile it from aur and found that it doesn't compile some locale.. ko, be, id .. .

**Comment by SmallJoker** [comment]
Reported many times. This is intentional, see #4638

If you would like to generate the translations anyway, comment the blacklist:
https://github.com/minetest/minetest/blob/e8fd1ce62331146fae0e98ce4a94d3720f308abf/src/CMakeLists.txt#L644-L651
