### ISSUE TITLE
Dropdown lists are rendered beneath inventory slots.

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9321]
##### Minetest version
```
5.2.0-dev @ 468eb4bf5710e851b2599baeff870518f979c71a
```

##### Summary
If you open a dropdown list, the list will be rendered beneath inventory slots.

##### Steps to reproduce
Open the test formspec in `minimal` or `devtest` (with a chat command). Click on “Real Coord”. Click on all the dropdown lists and see what happens.

**Comment by SmallJoker** [comment]
Please check again with `formspec_version[3]` and define the dropdown after the inventory lists.
