### ISSUE TITLE
Maximum height of nodebox collisionboxes is undocumented

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9322]
##### Minetest version
```
5.1.0
```

##### Summary
Nodes are allowed to have an overhigh collisionbox (i.e. higher than 1).
However, this fact is not clearly documented in `lua_api.txt` yet. Especially the maximum permitted height is not documented.

##### Analysis

From experiments I know that currently (5.1.0), a height of exactly 2 (from y=-0.5 to y=1.5) does not function. Entities will behave very very broken when standing on this node.
However, a height slightly below 2 will work.

Maximum confirmed functional y value is 1.484375 = 95/64. This is the maximum height of leveled nodeboxes. I figured this out by experimenting with a leveled nodebox.

I conclude the maxium possible collisionbox Y must lie somewhere between 1.484375 and 1.5. I have not conducted further experiments so far.

**Comment by FaceDeer** [comment]
In [commoditymarket_fantasy](https://github.com/FaceDeer/commoditymarket_fantasy) I have a series of caravan_market nodes that use a drawtype = "mesh" and have collision boxes that run from y = -0.5 to y = 1.5, and I've not noticed any strange behaviour with them. [The collision box is defined here](https://github.com/FaceDeer/commoditymarket_fantasy/blob/174a6bddefe511eee034426ae91e4c8dae00c87c/init.lua#L203). Maybe meshes work differently, somehow? What is the "brokenness" that you're seeing?

**Comment by Wuzzy2** [comment]
If you stand on a node with this added height (upper Y = 1.5), you cannot jump from it, and you will also wiggle a bit.

**Comment by FaceDeer** [comment]
Ah, I'm seeing the lack of jumping capability now. Guess I didn't try that before, these caravan nodes aren't common and are mostly transient things there to be clicked on rather than part of a permanent structure people might walk on.

I'm not seeing a "wiggle," though. Maybe that's specific to a particular build or OS. I'm on Windows 10 Home and am using Minetest 5.2.0-44445889.

**Comment by Wuzzy2** [comment]
Would it be OK to just state the maximum allowed Y value is 95/64=1.484375 just to stay safe? :-)

**Comment by paramat** [comment]
Perhaps when doing this also document that this maximum exists in all direction, not just y, as the largest functional collisionbox is 3x3x3 nodes centred on a node, and therefore 1.5 along each axis.

**Comment by Wuzzy2** [comment]
… except that very weird things happen if you have an overhigh collisionbox of up to Y=1.5 and you try to walk and jump on it. Your claimed maximum of 1.5 doesn't seem well supported right now.
Documentation shouldn't make promises it can't keep.

**Comment by paramat** [comment]
I agree, i worded that poorly, the practical maximum y for walking and jumping on should be mentioned.
