### ISSUE TITLE
Do not run on Android

### ISSUE THREAD

**Issue by leanh94** [minetest/minetest#9333]
I build android guide https://dev.minetest.net/Android  ,I build file Minetest-release.apk with sign ,but I run mobile open it .When I opened the application it requested permission to access the memory, I accepted then the application crashed

**Comment by SmallJoker** [comment]
Please try to find the `debug.txt` file within the `minetest` directory. If you cannot find it, try gathering crash information using logcat.

**Comment by SmallJoker** [comment]
#9334
