### ISSUE TITLE
Android: libiconv.so cannot find __emutls_get_address

### ISSUE THREAD

**Issue by leanh94** [minetest/minetest#9334]
I build error log cat view https://imgur.com/XeAObE6 ,help me @SmallJoker

01-22 07:29:47.536 D/SamsungAnalytics:1.8.33(18186): [DLC Sender] send result success : 0
--------- beginning of crash
01-22 07:29:47.536 E/AndroidRuntime(18551): FATAL EXCEPTION: main
01-22 07:29:47.536 E/AndroidRuntime(18551): Process: net.minetest.minetest, PID: 18551
01-22 07:29:47.536 E/AndroidRuntime(18551): java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/net.minetest.minetest-1/lib/arm/libiconv.so"...
01-22 07:29:47.536 E/AndroidRuntime(18551): at java.lang.Runtime.loadLibrary0(Runtime.java:977)
01-22 07:29:47.536 E/AndroidRuntime(18551): at java.lang.System.loadLibrary(System.java:1567)
01-22 07:29:47.536 E/AndroidRuntime(18551): at net.minetest.minetest.MtNativeActivity.(MtNativeActivity.java:17)
01-22 07:29:47.536 E/AndroidRuntime(18551): at java.lang.Class.newInstance(Native Method)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.app.Instrumentation.newActivity(Instrumentation.java:1086)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2839)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3045)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.app.ActivityThread.-wrap14(ActivityThread.java)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.os.Handler.dispatchMessage(Handler.java:102)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.os.Looper.loop(Looper.java:154)
01-22 07:29:47.536 E/AndroidRuntime(18551): at android.app.ActivityThread.main(ActivityThread.java:6776)
01-22 07:29:47.536 E/AndroidRuntime(18551): at java.lang.reflect.Method.invoke(Native Method)
01-22 07:29:47.536 E/AndroidRuntime(18551): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
01-22 07:29:47.536 E/AndroidRuntime(18551): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
01-22 07:29:47.546 D/Debug ( 2816): !@dumpstate : SHIP
01-22 07:29:47.546 D/Debug ( 2816): !@dumpstate : debug level:0x4f4c
01-22 07:29:47.546 D/Debug ( 2816): !@dumpstate : Finally, system will skip dumpstate
01-22 07:29:47.548 W/ActivityManager( 2816): Force finishing activity net.minetest.minetest/.MtNativeActivity
01-22 07:29:47.548 W/MultiScreenManagerService( 2816): moveTaskBackToDisplayIfNeeded(): root is not base activity

**Comment by SmallJoker** [comment]
libiconv seems to be broken (again?)
Maybe re-building the Android binary with additionally linked libraries could solve the problem. Similar issue (MacOS): https://stackoverflow.com/q/7885246

**Comment by MoNTE48** [comment]
Why continue to torment this if my PR fixes everything and makes a static link? This ensures that there are no such problems.

**Comment by MoNTE48** [comment]
@SmallJoker you can close it
