### ISSUE TITLE
OSX: `\` crashs client

### ISSUE THREAD

**Issue by zaoqi** [minetest/minetest#9337]
##### Minetest version

https://github.com/minetest/minetest/commit/1892ff3c0db23ccdf7b0f6dc83cb1bdf4579b4ec

(This bug appeared after Jan 20, 2020)

##### OS / Hardware

Operating system: 10.15.2
Model: Macbook8,1

##### Summary

Pressing `\` causes the client to crash

`terminated by signal SIGSEGV (Address boundary error)`

##### Steps to reproduce

Join a server
press `\` or `t`

**Comment by SmallJoker** [comment]
a1da9caec
