### ISSUE TITLE
make -j$ bug

### ISSUE THREAD

**Issue by IFRFSX** [minetest/minetest#9341]
i use make -j$4 or make -j$(4), but Memory usage is getting higher and higher(Until the end of the memory is full, crashes.), so i don't use "-j", but it's slow.
this bug from 5.1.0 to minetest-master now，Always exist.
for make's speed fast, please repair this bug.

**Comment by IFRFSX** [comment]
Tip: My computer has 16GiB memory!

**Comment by SmallJoker** [comment]
What's `$4`?  Use `make -j4`.

**Comment by IFRFSX** [comment]
I am wrong, sorry.
test make -j4 success, and about %(nproc)
I remembered that this is to substitute the maximum number of CPU cores into the command.
