### ISSUE TITLE
Build failure, irrlicht not found

### ISSUE THREAD

**Issue by Lockna** [minetest/minetest#9345]
Operating system: Arch Linux
CPU: i7-6700HQ

GPU model: Geforece GTX 960
OpenGL version:

When I try to build minetest using cmake it throws the following exception
`cmake . -DRUN_IN_PLACE=TRUE -BUILD_SERVER=TRUE >> test                                                                   1500ms  Wed 29 Jan 2020 03:24:37 PM CET
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
IRRLICHT_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
   used as include directory in directory /home/lockna/Clones/minetest/src
IRRLICHT_LIBRARY (ADVANCED)
    linked by target "minetest" in directory /home/lockna/Clones/minetest/src
`
##### Steps to reproduce
I  cloned the minetest repo. In the minetest Folder i cloned the minetest game repo in game/minetest_game and then used `cmake . -DRUN_IN_PLACE=TRUE -BUILD_SERVER=TRUE`

Could't find IRRLICHT Lib

**Comment by NathanSalapat** [comment]
Did you install the dependencies as outlined in, https://github.com/minetest/minetest#compiling

**Comment by Lockna** [comment]
Yes, I installed them all

**Comment by Lockna** [comment]
Okay, I just rebooted my pc and reinstalled them, now it works
