### ISSUE TITLE
May I use Minetest logo for GitHub topics

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#9360]
I'm planning to improve the [`minetest`](https://github.com/topics/minetest) to have a logo and description.
As specified [here](https://github.com/github/explore/blob/master/docs/API.md#logo), you must have permission to use the logo.

**Comment by HybridDog** [comment]
The Minetest logo is probably licensed under CC BY-SA 3.0, so as long as that links to minetest, you are permitted to use the logo afaik.
https://github.com/minetest/minetest/blob/b14aa1c84714a4800d214768ff7868a7bb76f7ae/LICENSE.txt#L26-L29

**Comment by Panquesito7** [comment]
The image must be 288x288.
I can fix that as well, however there are two problems:

- Image could be (very/a little) blurry.
- AFAIK, if I change it, it will be mine now, not Minetest's.

**Comment by tuedel** [comment]
A vector-based version of the logo is available here: https://github.com/minetest/minetest/blob/master/misc/minetest.svg

**Comment by HybridDog** [comment]
I've rasterized it in `(5*288)x(5*288)` resolution and then downscaled it with [that](https://gist.github.com/HybridDog/dd95a99d411972f030fb18543280ad60) algorithm:
![logo_288_ssim_based_downscalde](https://user-images.githubusercontent.com/3192173/73837270-67b85900-4811-11ea-9e2e-e530b43b2db2.png)

**Comment by Panquesito7** [comment]
@HybridDog, thanks!

**Comment by Panquesito7** [comment]
Because the image is edited, do I still got the full rights to use it?

**Comment by Panquesito7** [comment]
https://github.com/github/explore/pull/2185
