### ISSUE TITLE
Uninteractable Formspec Elements should passthrough hovers and clicks

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9361]
## Problem

Currently, labels and images prevent clicking on buttons below them

## Solutions

Labels and images should passthrough clicks

```lua
local my_formspec =
	[[
		formspec_version[3]
		size[6,6]
		button[1,1;4,4;btn;Hello]
		image[2,2;1,1;default_dirt.png]
		label[1,4;#####################]
	]]


minetest.register_on_joinplayer(function(player)
	minetest.after(0.5, function()
		minetest.show_formspec(player:get_player_name(), "ss", my_formspec)
	end)
end)
```

![image](https://user-images.githubusercontent.com/2122943/73684672-94a72780-46bc-11ea-873b-2d77a6383633.png)

**Comment by rubenwardy** [comment]
@Df458 something you will probably have an opinion on

**Comment by LoneWolfHT** [comment]
I can confirm this

**Comment by Df458** [comment]
My opinion is that elements that don't respond to user input should not steal user input. If you look at most common desktop UI frameworks, you'll find that input events usually come with a return value that decides if the event continues propagating to other elements (GTK+ and WPF, at least, do this. I assume QT is the same). When an element doesn't implement such an event at all, the framework just keeps going until it finds a blocking handler.

Ideally, we should aim for something like this as well. Clicking into something that detects and responds to events should stop further events, but anything that doesn't care should be skipped.

**Comment by v-rob** [comment]
I believe that Irrlicht does implement a boolean for blocking events, although I don't know what you would use to let the event continue.  Regardless of how it is done, we will probably have to clone `IGUIImage` and `IGUIStaticText`.

**Comment by rubenwardy** [comment]
This has broken Multicraft's creative tabs, and will probably break more things

**Comment by MoNTE48** [comment]
Pre-5.2-dev: https://www.youtube.com/watch?v=MK29S9h7Xjw
5.2-dev: https://www.youtube.com/watch?v=l-3ECRapjXw

(And in the end, tenplus1 code broke. Why is the screen gray and not the menu output? What else did you break?)

**Comment by Desour** [comment]
Related: #9264
The same problem existed with inventorylists. Hovering through still doesn't work. Clicking through was fixed in a hacky way (make the element invisible and call onevent on the element at the mousepos).
