### ISSUE TITLE
Server crash /help command

### ISSUE THREAD

**Issue by JRPete2020** [minetest/minetest#9363]
##### Minetest version
```
minetest-5.2.0-1892ff3-win64
```

##### OS / Hardware

Operating system:Win7 x64

##### Summary
New world with default mods only, "/help all" = server crash.

**Comment by LoneWolfHT** [comment]
What's in your debug.txt?

**Comment by JRPete2020** [comment]
nothing is entered in the debug but player joined

**Comment by LoneWolfHT** [comment]
Can you consistently replicate this crash?

**Comment by JRPete2020** [comment]
yes, i can do it over and over

**Comment by JRPete2020** [comment]
debug.txt
-------------
  Separator
-------------

2020-02-04 12:39:34: ACTION[Main]: World at [C:\minetest-5.2.0-1892ff3-win64\bin\..\worlds\test33]
2020-02-04 12:39:34: ACTION[Main]: Server for gameid="minetest" listening on 0.0.0.0:30000.
2020-02-04 12:39:41: ACTION[Server]: admin [127.0.0.1] joins game. 
2020-02-04 12:39:41: ACTION[Server]: admin joins game. List of players: admin

**Comment by LoneWolfHT** [comment]
I guess you'll need to wait until someone can instruct you how to run Minetest with gdb. I only know how to do it on Linux

**Comment by JRPete2020** [comment]
*Maybe this screenshot can help on crash details
![mt crash](https://user-images.githubusercontent.com/60555132/73780517-388fe200-4754-11ea-8ce8-dcea2956263a.jpg)

**Comment by SmallJoker** [comment]
Does the following work (not cause a crash)?
 - Show inventory
 - Open chest
 - `/privs` chatcommand
 - `/help ban`

**Comment by JRPete2020** [comment]
"/help ban" results in same crash, "/help" by itself results in the help formspec showing. I can perform other tasks you listed listed without crash

**Comment by sfan5** [comment]
This was already fixed in a1da9caecf5070e72b554b6c1d4272f9ac19dc55 (1 day after the date of your build).
I haven't made a new build yet, but I will right now.

**Comment by JRPete2020** [comment]
Awesome!
