### ISSUE TITLE
Build Android 64bit error

### ISSUE THREAD

**Issue by leanh94** [minetest/minetest#9366]
hi,I build android 64 bit,i edit Makefile
################################################################################
# toolchain config for arm64 new processors
################################################################################
TARGET_HOST = aarch64-linux-android
TARGET_ABI = arm64-v8a
TARGET_LIBDIR = arm64-v8a
TARGET_TOOLCHAIN = aarch64-linux-android
TARGET_CFLAGS_ADDON = -mfloat-abi=softfp -mfpu=vfpv3 -O3
TARGET_CXXFLAGS_ADDON = $(TARGET_CFLAGS_ADDON)
TARGET_ARCH = arm64
CROSS_CC = aarch64-linux-android-clang
CROSS_CXX = aarch64-linux-android-clang++
COMPILER_VERSION = clang
HAVE_LEVELDB = 0
################################################################################

and file /root/minetest/build/android/jni   Deps.mk Application.mk  Irrlicht.mk       APP_ABI := arm64-v8a   ,but build it error
changed timestamp for iconv detected building...
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=1
BUILD_NUM_CPUS=2
Auto-config: --arch=arm64
ERROR: Failed to create toolchain.
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for aarch64-linux-android-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make sets $(MAKE)... (cached) yes
checking for aarch64-linux-android-gcc... aarch64-linux-android-clang
checking whether the C compiler works... no
configure: error: in `/root/minetest/build/android/deps/libiconv':
configure: error: C compiler cannot create executables
See `config.log' for more details
Makefile:430: recipe for target '/root/minetest/build/android/deps/libiconv//lib/.libs/libiconv.so' failed
make[1]: *** [/root/minetest/build/android/deps/libiconv//lib/.libs/libiconv.so] Error 1
make[1]: Leaving directory '/root/minetest/build/android'
Makefile:133: recipe for target 'release' failed
make: *** [release] Error 2
root@ubuntu-1vcpu-1gb-01:~/minetest/build/android# ^C
root@ubuntu-1vcpu-1gb-01:~/minetest/build/android#

**Comment by rubenwardy** [comment]
Minetest does not support building for android in 64 bit mode yet
