### ISSUE TITLE
LUA PANIC on aarch64 linux

### ISSUE THREAD

**Issue by oktail** [minetest/minetest#9367]
Hello,

I have rebuild minetest on arm64 architecture (qemu arm64) and I encounter this issue : 

2020-02-05 21:20:28: ERROR[Main]: In thread ffff989a9480:
2020-02-05 21:20:28: ERROR[Main]: /home/oktail/minetest/src/script/cpp_api/s_base.cpp:89: static int ScriptApiBase::luaPanic(lua_State*): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (bad light userdata pointer)
Aborted

If I disable LUA JIT on cmake, minetest start correctly

Thanks

**Comment by tim-web** [comment]
I too have this running on arm64/aarch64 architecture.
I acquired my lovely new [Pinebook Pro](https://www.pine64.org/pinebook-pro/) which has a few different linux distros available.

The only distro I tried with minetest was Arch.  Both the version from the repo and also the flatpak throw this LUA PANIC.

This appears to be a known issues when using LUAJIT with 64 bit ARM architectures.
[https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/status.html#L95](https://github.com/LuaJIT/LuaJIT/blob/v2.1/doc/status.html#L95)

Ts

**Comment by appgurueu** [comment]
Have you tried building with a newer fork of LuaJIT, e.g. MoonJIT ?

**Comment by SmallJoker** [comment]
Maybe related: #8810

Did you compile with Irrlicht 1.9 (development version), and/or OGLES support?

**Comment by tim-web** [comment]
Yep.  Tried with MoonJit 2.2.0 release.  Same  result.   I doubt the Moonjit fork of LUAJit changed the pointer bits for lightuserdata.  LightUserData seems to be a deprecated way of doing things.

If I disable LuaJIT and just go with plain Lua, it runs...  But performance is terrible.

Since it runs without LuaJIT, very unlikely related to IrrLicht or OpenGL.  +The pinetab ref'd in issue #8810 used a different family of processors and the LuaJIT issue seems to be related to ARMv8 processors only.

**Comment by sfan5** [comment]
> If I disable LuaJIT and just go with plain Lua, it runs... But performance is terrible.

The performance of what exactly is terrible?
For example LuaJIT can't fix graphics and rendering since that doesn't use Lua.

**Comment by tim-web** [comment]
The graphics and rendering are not too bad.  Runs about 20 FPS , which I think is fine on a $200 laptop.

But any mod seems to be slow to come up or respond.   And mobs are definitely nowhere as performant as my other laptop.

Isn't that the whole point of using LuaJIT that it is significantly faster than the original Lua?

**Comment by AMDmi3** [comment]
> PRs welcome, should be just a few lines here:

Sure, I'm currently testing whether change to `--image-base` builds on aarch64. I'm however not sure whether this is an equivalent replacement, and cannot runtest it due to lack of hardware.

**Comment by AMDmi3** [comment]
Done, see #11263
