### ISSUE TITLE
Main Menu: World can be created in another folder

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#9370]
##### Minetest version

```
5.2.0-dev-ea5e2319-dirty (Linux)

```

##### OS / Hardware

Operating system: Lubuntu 18.04
CPU: Intel

##### Summary

The World name in the New World formspec is a relative path and not just a name.

##### Steps to reproduce

You can for example create a world in the home folder:
![fot_2020-02-07-16:37:56_220881779](https://user-images.githubusercontent.com/3192173/74042715-5a919a80-49c8-11ea-8ab4-12514e4b3473.jpg)
(this may not work on Windows or when your default world path is not ~/.minetest/worlds)

**Comment by FaceDeer** [comment]
A potentially related "issue" (which doesn't seem like a harmful thing but is clearly bending the rules a bit) is a clever hack I read about recently that allows a single binary schematic mts file to be loaded multiple times as if it were different schematics, allowing for different node replacements to be done. I haven't tried it myself but I was told that if you loaded "schematic_name.mts" and then loaded "./schematic_name.mts" and "././schematic_name.mts" you'd get three different schematics loaded in memory tagged with those strings as their name.

Not sure if this should be "fixed" if modders are actually using it as a workaround to achieve multiple replacements. Personally, I just use lua schematics and that works, so there's a workaround for the workaround if needed.

**Comment by appgurueu** [comment]
Can confirm with Minetest 5.1.1 - the world is not shown, but the folder is created. Doesn't seem dangerous, but could (and should) be fixed by imposing more constraints on world naming.

**Comment by An0n3m0us** [comment]
Can confirm here too; Minetest 5.2.0-dev (Ubuntu)

Entering `/x/world` gives a folder like so: `~/.minetest/worlds/x/world/` and the world doesn't show up on Minetest.
Using `../` works too.

**Comment by Zughy** [comment]
This has been fixed by https://github.com/minetest/minetest/commit/3ce03d1c2a63d261c83f5962cd13212697f19472, I've just tested
