### ISSUE TITLE
Hungarian: Some special characters don't show up

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest#9383]
##### Minetest version
```
Minetest 5.2.0-dev-b14aa1c-dirty
```
Works fine before: `Minetest 5.1.1-dev-5e4739b-dirty`

##### OS / Hardware
Operating system: Linux - Ubuntu 16.04

##### Summary
I've been meaning to mention this issue for a while;

With Hungarian language selected, some special characters don't show up in Minetest 5.1.1+;
for example: Ú and ö

Affects mod locales too.

##### Steps to reproduce
1. In Minetest 5.1.1, change the language to Hungarian (`hu`)
2. The "New" button for creating a new world will read "j" when it is supposed to read "Új"

**Comment by An0n3m0us** [comment]
Seems to originate from here:
https://github.com/minetest/minetest/commit/b83ca324f95641d41dcff5380a7b608ec820d610#diff-fd4749a1026ea4f7b35c2c2ce943c841L876

I changed it back from 'yes' to the Hungarian translation and it fixes the issue.

**Comment by SmallJoker** [comment]
The bundled fonts do not contain all language characters. Consider using droid sans (fallback). For this particular situation there's the "needs_fallback_font" translation string to chose it automatically.

**Comment by An0n3m0us** [comment]
It was using `DroidSansFallbackFull.ttf`, yet the special characters are still missing.

**Comment by sfan5** [comment]
Having worked with "DroidSansFallbackFull" in the context of another project I can say that it's actually missing several quite basic glyphs that will be present in any other normal font (e.g. Arimo).

What needs to be done here is to turn off the fallback font for Hungarian (and possibly other languages which don't need it).

**Comment by An0n3m0us** [comment]
Can one simply set `needs_fallback_font` ([line 877](https://github.com/minetest/minetest/blob/master/po/hu/minetest.po#L877)) to `no` to solve the issue?

**Comment by sfan5** [comment]
Yes, that should work.

**Comment by SmallJoker** [comment]
To be kept open until the translations are updated - or someone confirms that it works with the current Hungarian translation from Weblate.

**Comment by An0n3m0us** [comment]
Can confirm that it works; I downloaded the `.mo` file and placed it in the `hu/LC_MESSAGES` folder, then checked it in Minetest.
