### ISSUE TITLE
Disabling FreeType fonts causes Minetest to crash on startup

### ISSUE THREAD

**Issue by An0n3m0us** [minetest/minetest#9386]
##### Minetest version
```
Minetest 5.2.0-dev-b14aa1c-dirty
```

##### OS / Hardware
Operating system: Linux - Ubuntu 16.04

##### Summary
Minetest crashes when "FreeType fonts" is set to "Disabled"

Log:
```
2020-02-10: ERROR[Main]: FontEngine: Found font "/tmp/minetest/bin/../fonts/Arimo-Regular.ttf" but freetype is not available.
2020-02-10: ERROR[Main]: FontEngine: Default font file: 
2020-02-10: ERROR[Main]: 	"/tmp/minetest/bin/../fonts/Arimo-Regular.ttf"
2020-02-10: ERROR[Main]: 	required for current screen configuration was not found or was invalid file format.
2020-02-10: ERROR[Main]: 	Using irrlicht default font.
Segmentation fault (core dumped)
```

GDB Log:
```
Starting program: /tmp/minetest/bin/minetest 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffead97700 (LWP 9022)]
[Thread 0x7fffead97700 (LWP 9022) exited]
[New Thread 0x7fffead97700 (LWP 9023)]
[New Thread 0x7fffe6595700 (LWP 9024)]
[New Thread 0x7fffdaf39700 (LWP 9025)]
[New Thread 0x7fffda738700 (LWP 9026)]
[New Thread 0x7fffd9f37700 (LWP 9027)]
[New Thread 0x7fffd9736700 (LWP 9028)]

Thread 1 "minetest" received signal SIGSEGV, Segmentation fault.
0x00000000006a6de3 in GUIFormSpecMenu::regenerateGui(irr::core::vector2d<unsigned int>) ()
```

##### Steps to reproduce
1. On the settings page; set "Graphics ---> Menus ---> FreeType fonts" to "Disabled"
2. Restart the game and it should crash.

**Comment by rubenwardy** [comment]
This option should be removed and freetype made mandatory. It is needed for colored text and more, and having less configurations makes testing much easier

**Comment by SmallJoker** [comment]
In contrast to BIOS bricking this startup crash can be solved easily by editing the configuration file.
Bitmap and XML vector fonts are - and should IMO be - supported to the point that they're usable in the game - which wasn't even possible for a while due to lack of maintenance.

If you'd like to expand the functionalities or fix this issue - preferably by force-enabling Freetype in case the file cannot be loaded as Bitmap or XML vector font - feel free to propose a PR.

PS: I have a local patch which implements colouring for StaticText, but there's no demand for it [aside performance on low-end systems](https://github.com/minetest/minetest/pull/8641#issuecomment-507056996).

**Comment by MoNTE48** [comment]
@SmallJoker what you think about `ttf-parser`?
https://github.com/RazrFalcon/ttf-parser

**Comment by SmallJoker** [comment]
@MoNTE48 Aside this is kinda offtopic - thel ibrary lacks a feature which would be very handy to have: Rendering.
![grafik](https://user-images.githubusercontent.com/1497498/77823704-572fab00-70fd-11ea-8fd1-934537fff9cd.png)

**Comment by paramat** [comment]
Relabelling as a request from rubenwardy.

**Comment by erlehmann** [comment]
> This option should be removed and freetype made mandatory. It is needed for colored text and more, and having less configurations makes testing much easier

At least part of this statement is false: If I am not mistaken, colored text without Freetype seems to work on at least some configurations (e.g. Thinkpad X390 with Debian GNU/Linux). I tested this by disabling Freetype and using one of the provided pixel fonts.

Needless to say, on that computer not using Freetype also does not crash the game; text rendering is even faster!

**Comment by erlehmann** [comment]
@rubenwardy screenshot of colored text with pixel fonts (i.e. no FreeType) in MineClone 5: https://mister-muffin.de/p/XnO0.png

**Comment by sfan5** [comment]
Those are colored labels in the GUI. "Colored text" refers to the chat feature.
This is `/help teleport` with TTF and without:
![grafik](https://user-images.githubusercontent.com/1042418/133057043-0067b8f4-da2f-4aeb-b0b0-620a68b39b6f.png)

**Comment by erlehmann** [comment]
> "Colored text" refers to the chat feature.

Thanks, I hate it. I have encountered several users that used client mods to write hard to read colored text in the colored chat. Can that feature be turned off with FreeType fonts in any way?
