### ISSUE TITLE
Mark Android version as unstable/experimental

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9391]
## Problem

The Android version of Minetest has many, many problems. Especially it has a terrible usability that is so bad, that most players consider it unplayable. The controls are also a much-criticized part of Android, as they are not really practical to play the game as well as you could on PC.

The Android version is generally disliked by the Minetest community and in a terrible shape.

The Android version seriously drags the reputation of Minetest into the mud.

### Solution 1

Remove the Android version from all official “app stores” (Google Play, F-Droid, etc.). Stop all promotion of the Android version, thus making it only visible to interested testers and developers.

### Solution 2

Add a clear and highly-visible warning that the Android version is highly experimental, and that the player must expect bugs and problems.

## Additional context

Important criticisms:
https://forum.minetest.net/viewtopic.php?f=3&t=24109

Other Android “hate” threads:
https://forum.minetest.net/viewtopic.php?f=3&t=24171
https://forum.minetest.net/viewtopic.php?f=42&t=16536
https://forum.minetest.net/viewtopic.php?f=5&t=13093

**Comment by sfan5** [comment]
> Remove the Android version from all official “app stores”. Stop all promotion of the Android version, thus making it only visible to interested testers and developers.

Wow what a great suggestion. I'm sure players will be delighted to find that they have to switch to outdated, ad-supported clones that require payment to unlock all features.

**Comment by Wuzzy2** [comment]
Oh crap, I forgot that Android is infested with garbage apps. Right. :-(

Okay, fall back to solution 2, then.

**Comment by LoneWolfHT** [comment]
> outdated clones
Last I checked the official android client was also outdated

**Comment by rubenwardy** [comment]
Less than a year old is much better than 5 years old

**Comment by Extex101** [comment]
Please don't remove android I am personally an android player, and I know a lot of other android players with NO access to a Computer.
If you do this you could lose a lot of players

**Comment by Wuzzy2** [comment]
Alright, I understand, I understand. Ignore solution 1. Let's talk about solution 2.

**Comment by paramat** [comment]
> The controls are also a much-criticized part of Android, as they are not really practical to play the game as well as you could on PC.

That will never be possible on a tiny touchscreen =)

Your claims are a little exaggerated, but it certainly does have many problems and i agree with 'managing expectations'.

**Comment by MoNTE48** [comment]
Or maybe it was worth giving Android support to a person who was interested in this and has good experience in this?
Instead, the PR series on redo the Android port dwelled on the first PR, which cannot be considered and accepted, because no one understands this code or uses Android.

**Comment by Wuzzy2** [comment]
Why was this closed?

Does this mean the Android version is now actually stable, bugfree, in a playable state and all usability bugs that render the Android version unplayable have been fixed?
Or was the Android version marked as “unstable”?

If neither of these things happened, this issue was closed too early.

**Comment by rubenwardy** [comment]
Because this issue is unhelpful and unsupported. Fix the issues, don't remove the ability for many players to play

**Comment by Wuzzy2** [comment]
I have dropped “Solution 1” a long time ago (scroll up).
I'm only talking about Solution 2 now.

**Comment by MoNTE48** [comment]
Друг, I suggest that you do all this for your game, instead of injuring potential players with an unfinished and extremely buggy game.
After backporting all the improvements from MultiCraft, Minetest on Android will work better than on your super PC.

**Comment by paramat** [comment]
:-1: for the suggestion.
It is not "(highly) experimental", and "unstable" is confusing and offputting for those who use the Android app, especially after so many years of it being 'not unstable'.
Are you proposing an on-screen warning or text on the Play store page? I do not like the idea of any on-screen warning.
