### ISSUE TITLE
PC controls on Android

### ISSUE THREAD

**Issue by Kimapr** [minetest/minetest#9402]
I'm playing on an Android phone and have keyboard + mouse connected via Bluetooth.
It would be a great improvement to be able to use PC controls instead of mobile controls.

It should be a configuration option, because not every thing that Minetest considers a PC has keyboard and mouse (Windows Phone, Ubuntu Touch, etc), not every thing that Minetest considers a "phone" (Android) doesn't (Chromebooks) and also some people could probably want to test mobile controls on a PC (idk why).

**Comment by rubenwardy** [comment]
Duplicate of #8879
