### ISSUE TITLE
Document voxelarea 'area.ystride', 'area.zstride'

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9406]
Not documented but defined here:
https://github.com/minetest/minetest/blob/6958071f497c8f059429343339ad3818ed3cfed1/builtin/game/voxelarea.lua#L14-L15
... and used throughout that file.
These would be useful for Lua mapgens, i am very often having to calculated y/z strides, but they are actually already calculated.
In a mod these would be used like this:
```
local area = VoxelArea:new{MinEdge = emin, MaxEdge = emax}
... area.ystride ...
... area.zstride ...
```
However these are not documented in:
https://github.com/minetest/minetest/blob/6958071f497c8f059429343339ad3818ed3cfed1/doc/lua_api.txt#L3745
Is there any reason to not do so?
I will do this task if it seems acceptable.

**Comment by FaceDeer** [comment]
I use these extensively in my various mapgen mods and I'm surprised they aren't documented. I have no idea where I learned about them, maybe just from rooting around in the builtin files.

Documenting them would probably also help explain to modders how a "flat 3d array" actually works, too.

**Comment by paramat** [comment]
PR #9415
