### ISSUE TITLE
[Android] Stack items can not be separated.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9418]
##### Minetest version
```
Minetest-5.0.0.23
```

##### Summary
It is impossible to separate some amount of items from a stack (on the Android version) by neither single/double-clicking nor pressing down and any other ways. Otherwise, you just grip a full stack.

##### Steps to reproduce
1. Put a stack with some amount of items in the inventory (> 1).
2. Try to do the actions with it which I described above (double-click or press down and then try to tap the selected stack or by other ways). In result, you grab the whole stack.

**Comment by srifqi** [comment]
https://github.com/minetest/minetest/blob/2df226bb41904bfd80c33f243996ee7b1bd7e907/doc/README.android#L30-L32

**Comment by Andrey2470T** [comment]
@srifqi: thanks for prompting! It works fine,  though it grips immediately a half of a stack, not one by one what I expected.
