### ISSUE TITLE
When using the inventory, item shown on cursor does not drop when clicking outside, drag & drop from inventory to outside doesn't work eather

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#9420]
##### Minetest version

```
Minetest 5.2.0-dev-debug-e8a8185d (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 18.04 LTS
CPU:  Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary

Trying to drop an item that is on hand (shown on cursor, not selected in hotbar) does not work when clicking outside the inventory menu that has been opened, drag & drop to outside of the inventory doesn't work eather. Pressing q to drop an item when not inside inventory menu works.

<details>
<summary>Contents of debug.txt (latest session, old file was deleted before the test)</summary>

```
-------------
  Separator
-------------

2020-02-22 10:46:12: ACTION[Main]: Yeah experimental loaded mods.
2020-02-22 10:46:12: ACTION[Main]: World at [/home/juozas/minetest_dev/bin/../worlds/Test2]
2020-02-22 10:46:12: ACTION[Main]: Server for gameid="minimal" listening on 0.0.0.0:63334.
2020-02-22 10:46:13: ACTION[Server]: singleplayer [127.0.0.1] joins game. 
2020-02-22 10:46:13: ACTION[Server]: singleplayer joins game. List of players: singleplayer
2020-02-22 10:46:13: WARNING[Server]: Deprecated call to get_attribute, use MetaDataRef methods instead. (at ...s/minetest_dev/bin/../games/minimal/mods/test/player.lua:73)
2020-02-22 10:46:13: WARNING[Server]: Deprecated call to get_attribute, use MetaDataRef methods instead. (at ...s/minetest_dev/bin/../games/minimal/mods/test/player.lua:73)
2020-02-22 10:46:13: WARNING[Server]: Deprecated call to get_attribute, use MetaDataRef methods instead. (at ...s/minetest_dev/bin/../games/minimal/mods/test/player.lua:73)
2020-02-22 10:46:14: WARNING[Server]: Deprecated call to set_attribute, use MetaDataRef methods instead. (at /home/juozas/minetest_dev/bin/../builtin/common/after.lua:20)
2020-02-22 10:46:14: WARNING[Server]: Deprecated call to set_attribute, use MetaDataRef methods instead. (at /home/juozas/minetest_dev/bin/../builtin/common/after.lua:20)
2020-02-22 10:46:16: WARNING[Server]: active block modifiers took 201ms (processed 225 of 251 active blocks)
2020-02-22 10:46:20: ACTION[Main]: Server: Shutting down
```

</details>

**Edit:** Like @SmallJoker suggested, I tried to do a "drag & drop", but still got nothing trying that. The item is stuck on the cursor :\ There's no such problem in stable version of minetest and all build dependencies are installed correctly. Video: https://www.youtube.com/watch?v=83DPnG80IVc
**Edit2:** New video with cursor properly captured: https://www.youtube.com/watch?v=ZChqaJ3UmZc

##### Steps to reproduce

1. Build latest minetest dev version on ubuntu 18.04 LTS with all required build dependencies installed
2. Launch minetest, create minimal world if not exist and load it, or use any other type of world as it is also affected (unless subgame/mod modifies code that handles inventory and such a world might not be affected)
3. Gather some resources if inventory is empty, it inventory, select an item, try to drop it by clicking outside the form
4. Watch how nothing happens when trying to click outside the form

**Comment by SmallJoker** [comment]
Just drag & drop the item stack outside the inventory.
W/A/S/D are similar to drop key - they're ignored as long a formspec (inventory) is open.

**Comment by juozaspo** [comment]
The problem is that I'm unable to do a "drag & drop" of item outside the inventory eather. Trying to do that nothing happens, item is not dropped. Cursor is shown only when inventory is open and I'm unable to do a "drag & drop" when inventory is not open.

**Comment by SmallJoker** [comment]
Based on my local builds (always current master + some PR) I can bisect this a bit:
Bad: 27.01.2020 908e762
Good: 07.01.2020
Good: 18.01.2020 1173ff0

I'll check whether this is caused by 1116918d

**Comment by SmallJoker** [comment]
@DS-Minetest `GUIInventoryList::OnEvent` should call
`bool GUIFormSpecMenu::OnEvent(const SEvent& event)`, but that never happens.
The "click through" code finds the ID -1 which is GUIFormSpecMenu, but the pointer does not match `m_fs_menu` (multiple GUIFormSpec instances?).

Workaround:
```diff
diff --git a/src/gui/guiInventoryList.cpp b/src/gui/guiInventoryList.cpp
index ae7ec0539..0fe00e155 100644
--- a/src/gui/guiInventoryList.cpp
+++ b/src/gui/guiInventoryList.cpp
@@ -176,6 +176,9 @@ bool GUIInventoryList::OnEvent(const SEvent &event)
                Environment->getRootGUIElement()->getElementFromPoint(
                        core::position2d<s32>(event.MouseInput.X, event.MouseInput.Y));
 
+       if (!hovered || hovered->getID() == -1)
+               hovered = m_fs_menu;
+
        bool ret = hovered && hovered->OnEvent(event);
 
        IsVisible = was_visible;
```

**Comment by juozaspo** [comment]
Made another drag & drop test, this time cursor captured properly (enabled in recording application): https://www.youtube.com/watch?v=ZChqaJ3UmZc

**Comment by DS-Minetest** [comment]
First, here's the code that does the dropping:
https://github.com/minetest/minetest/blob/7ce21788f86d489d6dc08d9b2d3f6e3f8495b64e/src/gui/guiFormSpecMenu.cpp#L4008-L4017
It seems like items should only be dropped if clicked outside of the window (where there's no GUIFormspecMenu anymore).
Using `typeid(*hovered).name()` and comparing pointers, I've found out, that
- in the window, hovered is `m_fs_menu` (actually dropping is possible in current master, you have to click exactly on the edge of the formspec window)
- if you click (or move your mouse) outside the window the type of hovered is `N3irr3gui14CGUIStaticTextE`. (It can't be `m_fs_menu` as `m_fs_menu`'s rect does not fill the entire screen.)

<details><summary>Code I've used for testing</summary>

```cpp
	// (also add a #include <typeinfo>)
	IGUIElement *hovered =
		Environment->getRootGUIElement()->getElementFromPoint(
			core::position2d<s32>(event.MouseInput.X, event.MouseInput.Y));

	if (m_listname == "main") {
		errorstream << "mouse: " << event.MouseInput.X << ", " << event.MouseInput.Y << std::endl;
		errorstream << "m_fs_menu=" << m_fs_menu << std::endl;
		errorstream << "hovered=" << hovered << std::endl;
		if (hovered) {
			errorstream << "ID: " << hovered->getID() << std::endl;
			errorstream << "type: " << typeid(*hovered).name() << std::endl;
		}
	}
	if (!hovered || hovered->getID() == -1) // suggested fix
		hovered = m_fs_menu;

	bool ret = hovered->OnEvent(event);
```

</details>

As the weird superparent element with ID `-1` (and also any other element with ID `-1`) normally doesn't get `OnEvent` triggered anyway (I guess), the suggested fix/workaround seems fine. I'll make a PR.
Another fix might be checking in GUIInventoryList whether the mouse pos is in `m_fs_menu`'s rect, and if not, call a new function of GUIFormspecMenu.

**Comment by DS-Minetest** [comment]
PR: #9422
