### ISSUE TITLE
Keypad input not working correctly on Linux

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#9426]
##### Minetest version

```
Minetest 5.2.0-dev-debug-2df226bb (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 18.04 LTS
CPU:  Pentium(R) Dual-Core  CPU      E6300  @ 2.80GHz

##### Summary

Trying to use keypad's numeric input on mintetest fails with most of numbers not being input and being replaced with other navigation keys. Only 0,3 and 9 works, other ones acts as arrow and other navigation keys. E.g. trying to input 1234567890 with keypad results in 903, with cursor blinking on the last number (3). All versions might be affeacted since 0.4.16 or earlier (not all tested)

##### Steps to reproduce

1. Build/install latest minetest version such as stable or dev on Linux
2. Run, try to use keypad on some functions requiring text input by turning Num Lock on and using keypad to input numbers
3. See how most of number keys does not function like they should be

**Comment by sfan5** [comment]
duplicate #3170
