### ISSUE TITLE
Add ability to reuse arguments to client-side translation

### ISSUE THREAD

**Issue by FaceDeer** [minetest/minetest#9427]
## Problem

I've been converting a number of my mods over from the server-side "intllib" mod's localization system to the newer client-side minetest.translator system. Aside from having to write a new Python script for collecting and formatting strings in translation files it's been relatively straightforward to just drop this in place of the old one, but I just ran into a spot where intllib handled things more intelligently than the built-in code now does.

I have a string in commoditymarket for showing a log entry for a player transaction and under intllib I had it re-use the currency symbol parameter in two positions, eg:

`S("Player bought @1 items at @2@3 each, for a total cost of @2@4", number_of_items, currency_symbol, cost_per_item, number_of_items*cost_per_item).`

This string now throws an error in the new system, complaining that the second "@2" parameter is out of order and that it was expecting "@4."

This is a pretty minor thing that's easy enough to fix in code, but at the same time I see no reason why the new translation system couldn't handle this the same way that intllib did.

## Solutions

Allow parameters to the translation function to be reused in multiple places by easing restrictions on their order in the template string.

## Alternatives

No good alternatives come to mind. Maybe switching back to intllib? Hardly worth it over such an incredibly minor omission.

I realize that this is a very minor bug, it's certainly not blocking me and took moments to work around. Just figured I should note it down for the record since it's technically a bit of a regression compared to intllib.

The core.translate function is [here](https://github.com/minetest/minetest/blob/6be7150cd5c18869911bcba8e5833155521d2780/builtin/common/misc_helpers.lua#L673).

**Comment by Wuzzy2** [comment]
> No good alternatives come to mind.

There's a very simple workaround: Just repeat the argument in the argument list. Yes, it's a little redundant, but it will work.

So this:
```
S("Player bought @1 items at @2@3 each, for a total cost of @2@4", number_of_items, currency_symbol, cost_per_item, number_of_items*cost_per_item)
```

can be rewritten as:

```
S("Player bought @1 items at @2@3 each, for a total cost of @4@5", number_of_items, currency_symbol, cost_per_item, currency_symbol, number_of_items*cost_per_item)
```

But I agree it would be better if arguments could be repeated in the string. But it's not really important because a workaround exists.

**Comment by FaceDeer** [comment]
Yeah, that's the workaround I used. I guess I interpreted "alternatives" to be "how can I make the translator able to reuse parameters?" not "how can I make the translator emit the same result as intllib did?", and the latter's a fine interpretation.

Though I have now thought of a way to do the former, you could create a wrapper for S() that pre-processes the parameters to rewrite it as you describe behind the scenes.

**Comment by Ekdohibs** [comment]
It is actually not that simple: indeed, the client recreates the template string locally by replacing each argument in order with `@1`, `@2`, ...
If the arguments are reused, or are used out of order, then it is not able to recreate the original template string.
