### ISSUE TITLE
Compilation with gcc 9.2.1 on Ubuntu 20.04 (dev. version) triggers a warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct NoiseParams’ with no trivial copy-assignment

### ISSUE THREAD

**Issue by juozaspo** [minetest/minetest#9434]
##### Minetest version

8ddb6718
```
Minetest 5.2.0-dev-debug-8ddb6718 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Debug
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Ubuntu Linux 20.04 (dev. version)
CPU: Pentium(R) Dual-Core  CPU E6300  @ 2.80GHz

##### Summary

Compiling on Ubuntu 20.04 LTS (dev. version) with gcc 9.2.1 triggers a warning in the middle of compilation, pointing to src/noise.cpp file, not mentioning bunch of warnings as described in #9433.
```
/home/juozas/minetest/src/noise.cpp: In constructor ‘Noise::Noise(NoiseParams*, irr::s32, irr::u32, irr::u32, irr::u32)’:
/home/juozas/minetest/src/noise.cpp:432:29: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct NoiseParams’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
  432 |  memcpy(&np, np_, sizeof(np));
      |                             ^
In file included from /home/juozas/minetest/src/noise.cpp:27:
/home/juozas/minetest/src/noise.h:103:8: note: ‘struct NoiseParams’ declared here
  103 | struct NoiseParams {
      |        ^~~~~~~~~~~
```

**Edit:** This might be a duplicate of #8292, the error is the same as in that issue

##### Steps to reproduce

1. Install Ubuntu 20.04 dev. version
2. Get minetest source from git, use same cmake command line as described in #9433
3. Install all build depenencies so cmake reports no missing packages, then compile by running `make -j $(nproc)`
4. Notice warning when compiling file src/noise.cpp amongst other warnings shown for every other file, also described in the other issue

**Comment by appgurueu** [comment]
Not the only warning. Having similar warnings with Ubuntu 19.10.

**Comment by juozaspo** [comment]
There's already an issue posted earlier in this repository with the same error, closing this now as I suspect this is a duplicate of #8292
