### ISSUE TITLE
Improve code style guidelines

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9435]
## Problem

There currently is only a relatively small coding style guide for [C++](https://dev.minetest.net/Code_style_guidelines) & [Lua](https://dev.minetest.net/Lua_code_style_guidelines) code contributed to the engine. This may lead to inconsistent style across contributions.

## Solutions

1. I would prefer it if the style guides went further into detail.
2. A preconfigured formatter should be ran on the code.
3. Please move the style guides to GitHub using Markdown.

## Alternatives

I don't see any.

## Additional context

While working on my small [waypoint precision PR](https://github.com/minetest/minetest/pull/9421), I was wondering whether I should use

```cpp
if (a)
    // do stuff
else
    // do more stuff
```

or

```cpp
if (a) {
    // do stuff
} else {
    // do more stuff
}
```

I finally chose the latter, because of personal preference, but would prefer if there was a style guide for this.

**Comment by sfan5** [comment]
> A preconfigured formatter should be ran on the code.

We do this to some degree. It has caused numerous problems and annoyances: #8467 #9074

> While working on my small waypoint precision PR, I was wondering whether I should use [...] or [...]

Have you read the [Linux kernel code style](https://www.kernel.org/doc/html/latest/process/coding-style.html) that is linked from the wiki?
It is very clear on this (you should omit the braces).

**Comment by DS-Minetest** [comment]
> 1. I would prefer it if the style guides went further into detail.

Actually the style guides are already pretty detailed.
Specifying the style for the few petty things left would only cause more pedanticness (eg. in reviews, sorry) and work but wouldn't really make the code more readable.

> 2. A preconfigured formatter should be ran on the code.

Imho it's good that humans can sometimes diverge from the guidelines to produce more *human-*readable code.

> 3. Please move the style guides to GitHub using Markdown.

Why do you suggest this? The wiki already has very nice formatting. (Imo it's better than anything I've seen in markdown yet.)
Loading times in github are worse. (At least I've got the feeling.)
Github will probably be left at some point anyways. Moving such stuff to github would the force to move to a new site that also supports markdown stuff.
I'm not sure what problems there might be for javascript-denial-cowboys.

**Comment by appgurueu** [comment]
I now see that it is mostly fine. Closing the issue.
