### ISSUE TITLE
Add skins to online content

### ISSUE THREAD

**Issue by wuniversales** [minetest/minetest#9436]
**Issue**

Some users may find it difficult to install a skin for their character.

**Solution**

I think it would be good to add skins to download from the store, there are currently textures, mods, and games

Why not add skins?

Regards

**Comment by rubenwardy** [comment]
Minetest doesn't support skins in itself, and so has no idea where it should install them. This means it they can't be added to the store

**Comment by Andrey2470T** [comment]
You can install the corresponding mods to change a current skin (e.g Unified Skins, Skinsdb and etc) instead.
