### ISSUE TITLE
bug: item loss due to moving items out of output-only inventory to an occupied slot

### ISSUE THREAD

**Issue by Sokomine** [minetest/minetest#944]
Situation: A machine (i.e. furnace) has an inventory A that allows output only. This is assured by always returning 0 in allow_metadata_inventory_put. Now the player takes inventory out of A and places it on an inventory slot in his inventory that already contains something else, namely stack B.

Observed behaviour: Stack A is moved to the players inventory where stack B was; stack B visually sticks to the mouse pointer. Stack B is temporally stored in the output-only slot of the machine that previously contained stack A (they're both swapped). When the player places stack B somewhere else, it is taken out of its temporary storage and moved to the new place.

Problem: The machine with the output slot expected never to receive any input from the player in its output-only-slot and it updates its inventory if something is taken out. This results in the loss of stack B.

Desired solution: Before allowing to take stack A out, check if the destination slot is either free (no problem then) or if the output slot accept what's in the new place as input. If it does not accept stack B as input, deny the move of stack A to the position of stack B entirely.

**Comment by nerzhul** [comment]
@Sokomine is this issue alwas relevant ?

**Comment by paramat** [comment]
@Sokomine still occuring?

**Comment by HybridDog** [comment]
You could add a "realtime" parameter to formspec inventories. If it is set to true (e.g. for furnaces), the items are taken and inserted as early as possible. If it's set to false (default), the items are not moved as long as the player holds one (client-side), when he/she finally e.g. has put the item into an empty slot, all movements are sent and processed at once server-side.

**Comment by GreenXenith** [comment]
Tested, this issue no longer occurs.

**Comment by paramat** [comment]
Thanks for testing.

**Comment by Ekdohibs** [comment]
What commit is supposed to have fixed this bug?

**Comment by paramat** [comment]
Ancient bug and no response to my question, so deserved a close anyway :)
