### ISSUE TITLE
Ability to update all installed mods

### ISSUE THREAD

**Issue by clavinet** [minetest/minetest#9442]
## Problem

Currently, the built-in mod manager in Minetest can't update all installed mods at once.

## Solutions

It would be great if the mod manager could update all installed mods with e.g. a button click, without having to trawl through all (currently 138) pages of mods.

**Comment by LoneWolfHT** [comment]
The ability to skip the updating of some of the mods would be needed if this was implemented

**Comment by rubenwardy** [comment]
duplicate of #7369

**Comment by clavinet** [comment]
Oh thanks, I didn't see this issue in my search. This can be closed then.
