### ISSUE TITLE
get_bone_position does not return default bone position

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9445]
Minetest version: 5.1.1

##### Summary

Using (minimal example):
```lua
minetest.register_globalstep(function()
    for _, player in pairs(minetest.get_connected_players()) do
        local position, rotation = player:get_bone_position("Head")
        player:set_bone_position("Head", position, rotation)
    end
end)
```
in a mod causes the player to look like this:

![Screenshot](https://user-images.githubusercontent.com/34514239/75612563-f1172e80-5b24-11ea-84ee-9207a9fdcf4b.png)

As position (and rotation) are `{x = 0, y = 0, z = 0}`, which they obviously shouldn't be.

**Comment by appgurueu** [comment]
I have investigated and found the root cause. `get_bone_position` only returns values previously set with `set_bone_position`; it does not know about the models default bone positions at all.

**Comment by An0n3m0us** [comment]
Duplicate of #4739

**Comment by appgurueu** [comment]
The server doesn't really know about models so this can hardly be fixed there; having the client send bone positions would be odd (especially accounting for lag and animations). Mod workarounds exist (see modlib's B3D reader & character_anim's use of it). The proper way to solve the "underlying" issue is #10704.
