### ISSUE TITLE
Lua debug library exposed to mods

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9452]
##### Minetest version
```
5.1.1
```

##### Summary
The Lua `debug` library is availabe to mods. I don't think this is a good idea and am concerned about security.

> You should exert care when using this library. The functions provided here should be used exclusively for debugging and similar tasks, such as profiling. Please resist the temptation to use them as a usual programming tool: they can be very slow. Moreover, several of these functions violate some assumptions about Lua code (e.g., that variables local to a function cannot be accessed from outside or that userdata metatables cannot be changed by Lua code) and therefore can compromise otherwise secure code.

https://www.lua.org/manual/5.1/manual.html#5.9

I strongly suggest to stop exposing the `debug` library to Lua mods (maybe even builtin) at all.

**Comment by Desour** [comment]
Mods that execute player-provided code, eg. `mesecons_luacontroller`, need the debug library to stop executing the code after a while (see [here](https://github.com/minetest-mods/mesecons/blob/68c17299907d850a2565ed7c162be142cc817473/mesecons_luacontroller/init.lua#L545-L547)). Completely breaking such mods would be unacceptable (as they are nice mods and educationally valueable).
Can you name any concrete situation in which `debug` could used to breach security?

**Comment by sorcerykid** [comment]
Undoubtedly there are mods that actually use the debug library for -- surprise -- legitimate debugging purposes. So eliminating that capability would be a major hindrance for some developers.

I would suggest instead adding a new mod security setting in minetest.conf, `secure.debug_mods`, which takes a list of mods that are permitted to use the Lua debugging functions. Of course, if `secure.enable_security` is set to false, then those functions are exposed normally.

**Comment by Wuzzy2** [comment]
> Can you name any concrete situation in which debug could used to breach security?

I don't know. I just trust the official (!) Lua documentation on that one. It's not my fault that some modders started to abuse the `debug` library.

`mesecons_luacontroller` does exactly what it is not supposed to: Abusing `debug` as an usual programming tool. Isn't there any better method to implement a timeout?

The only mod I've found in which using `debug` is defensible is `qa_block` as it's a testing mod. All other mods in which I found usage of `debug` abuse it.

What is really concerning is that **untrusted** mods (i.e. mods not in `secure.trusted_mods` setting) apparently have full access to the `debug` library. This completely bypasses any mod security measures.

**Comment by sfan5** [comment]
There is a whitelist of methods available from the debug library:
https://github.com/minetest/minetest/blob/d961ece144c239a61ff46d830041249867656e9c/src/script/cpp_api/s_security.cpp#L108-L119

**Comment by Wuzzy2** [comment]
This whitelist is surprisingly large. Out of 14 possible functions, 10 are whitelisted …
How is this whitelist justified? Has each of the functions been examined for possible security problems?

**Comment by sfan5** [comment]
> Has each of the functions been examined for possible security problems?

Yes, this was done during review of the PR that added mod security.

The 9 removed functions along with reasons I can think of:
* `debug.debug()`: does something interactive, presumably on stdin, this isn't wanted
* `debug.getfenv()`: duplicate of `getfenv`(?), unclear what it does
* `debug.getlocal()`: security bypass if another mod uses `request_insecure_environment`
* `debug.getregistry()`: see above
* `debug.getupvalue()`: see above
* `debug.getuservalue()`: purpose unclear
* `debug.setuservalue()`: see above
* `debug.setfenv()`: see `.getfenv()`
* `debug.upvaluejoin()`: security bypass if another mod uses `request_insecure_environment`

**Comment by Wuzzy2** [comment]
> debug.debug(): does something interactive, presumably on stdin, this isn't wanted

Fun fact: This function is whitelisted 2 posts above. :-)

**Comment by Wuzzy2** [comment]
Arrrgh, sfan5 made a ninja-edit! xD

**Comment by rubenwardy** [comment]
debug.getfenv() - this can be used to steal insecure environments from upvalues, I think

**Comment by Wuzzy2** [comment]
So if I interpret all this correctly, current behavior is intentional? Sounds like a possible close, then … :-/

**Comment by sfan5** [comment]
Yes, the current behavior is intentional.

**Comment by sorcerykid** [comment]
I'm with sfan5 on this one. There is no reason to change the current implementation if it's already been carefully reviewed and decided.
