### ISSUE TITLE
minetest.get_connected_players() returns recently disconnected players.

### ISSUE THREAD

**Issue by luk3yx** [minetest/minetest#9454]
##### Minetest version

```
Minetest 5.2.0-dev-7dffd08c
```

##### Summary

`minetest.get_connected_players()` can return non-existent players just after they leave the game.

This is a duplicate of #1009, however this issue has resurfaced since the move to C++.

##### Steps to reproduce

Create a mod with the following code:
```lua
minetest.register_globalstep(function()
    for _, player in ipairs(minetest.get_connected_players()) do
        assert(player:get_player_velocity())
    end
end)
```

Then start a Minetest server and connect a client to it (if you are using the GUI you will need a second client). Once this client leaves, the server will crash with an assertion error.

**Comment by sfan5** [comment]
I decided to investigate on my own and fixed this in #9455 <i>just now</i>.
