### ISSUE TITLE
minetest.register_on_item_use

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#9467]
I propose a new callback register_on_item_use(player, itemstack, pointed_thing, original_use)
E.g.
```
minetest.register_on_item_use(function(player, itemstack, pointed_thing, original_use)--Original on_use defined by item or node (if none then returns blank)
    if itemstack === "shooter:grenade" then
        minetest.chat_send_player(player:get_player_name(), "You aren't allowed to use grenades!")
        return --You're not allowed to use that (Do nothing)
    end
    return original_use --Nothing wrong here run normal stuff
end)
```

**Comment by sfan5** [comment]
And why can't your usecase be achieved by overriding `minetest.registered_tools["shooter:grenade"].on_use`?

**Comment by Extex101** [comment]
I guess but that would require having the mod run after every mod is loaded

**Comment by appgurueu** [comment]
No, that only requires you to add `shooter` to the `depends` in `mod.conf`.

**Comment by Extex101** [comment]
I was just using that as an example

**Comment by paramat** [comment]
> I guess but that would require having the mod run after every mod is loaded

The mod can load whenever and use the 'register on mods loaded' feature.

**Comment by ClobberXD** [comment]
The example used in the first post isn't one that amply justifies this feature request, but adding a global callback for an action as fundamental as item use sounds like a good idea to me.

As for use-cases, I'll try to provide an example - consider the `afkkick` mod, it currently checks for player key presses in a globalstep to know whether or not a player is active. It can be made much more efficient by using global callbacks to keep track of interactions, and then checking only for player movement in the globalstep.

Of course, one single callback won't make `afkkick` drop keypress polling completely, as there's no callback for "secondary use" (right-clicking while pointing at nothing) yet, for example. I was just trying to come up with a use-case for this feature request.

There's also the performance concerns, as these callbacks would run multiple times every second on large servers. IMO, it'd suffice to simply add a warning in the API documentation (just like the one for `on_dig_node`) - it'd be up to the mods to keep things running smooth.
