### ISSUE TITLE
Night sky has no stars

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9468]
##### Minetest version
```
9ca0b3739cbaceaa291ac5062ab219e0aa7c49cb
```

##### Summary
The night sky has no stars. This is a regression from 5.1.1.

##### Steps to reproduce
1. Start a fresh world
2. Wait for the night or do `/time 0`

##### My guess
My guess is this is related to the recent addition of `set_stars`.

@Jordach

**Comment by Jordach** [comment]
Building commit `a079113a2009621829474c3075006b3e0f92653c` (https://github.com/minetest/minetest/commit/9ca0b3739cbaceaa291ac5062ab219e0aa7c49cb) under MSVC environments causes the stars to visibly render at night.

Suspected cause; type conversion with `fabs` being used.

**Comment by Wuzzy2** [comment]
This code looks suspicious:

```
         const StarParams getStarDefaults()
         {
                 StarParams stars;
                 stars.count = 1000;
                 stars.starcolor = video::SColor(105, 235, 235, 255);
                 stars.scale = 1;
                 return stars;
         }
```

**Comment by Jordach** [comment]
I don't believe it exists there, I've got the succinct feeling Clang is prematurely optimizing out the special latch in `Sky::setStarCount()`

**Comment by style-nine** [comment]
No stars in Ubuntu 18.04 with the latest git version and default settings:
![stars](https://user-images.githubusercontent.com/41269111/76120197-f8c05280-5fbe-11ea-9fd0-7e2288700a69.jpg)

**Comment by sfan5** [comment]
The fix:
```diff
diff --git a/src/skyparams.h b/src/skyparams.h
index 877907e3..a11eb330 100644
--- a/src/skyparams.h
+++ b/src/skyparams.h
@@ -115,6 +115,7 @@ class SkyboxDefaults
                stars.count = 1000;
                stars.starcolor = video::SColor(105, 235, 235, 255);
                stars.scale = 1;
+               stars.visible = true;
                return stars;
        }
 };
```

**Comment by style-nine** [comment]
> The fix:
> 
> ```diff
> diff --git a/src/skyparams.h b/src/skyparams.h
> index 877907e3..a11eb330 100644
> --- a/src/skyparams.h
> +++ b/src/skyparams.h
> @@ -115,6 +115,7 @@ class SkyboxDefaults
>                 stars.count = 1000;
>                 stars.starcolor = video::SColor(105, 235, 235, 255);
>                 stars.scale = 1;
> +               stars.visible = true;
>                 return stars;
>         }
>  };
> ```

Confirmed here.

**Comment by paramat** [comment]
I can confirm the bug.
