### ISSUE TITLE
get_stars doesn't return size

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9469]
##### Minetest version
```
9ca0b3739cbaceaa291ac5062ab219e0aa7c49cb
```

##### Summary
If you call `player:get_stars` you get a table. But this table doesn't have a `size` parameter, as used in `set_stars`. Instead, it has a `scale` parameter.

@Jordach.

##### How to reproduce

Use `luacmd` mod, then enter in console:

`/lua print(dump(me:get_stars()))`

**Comment by sfan5** [comment]
<pre>{
	visible = false,
	count = 1000,
	scale = 1,
	star_color = {
		r = 235,
		b = 255,
		a = 105,
		g = 235
	}
}</pre>
I don't see "scale" documented anywhere, so this is probably just a typo in the code.

**Comment by Jordach** [comment]
That is indeed a typo.
