### ISSUE TITLE
[Collision] Abrupt stopping of a player that moving very slow pushed against the wall.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9470]
##### Minetest version
Minetest-5.2.0-dev

##### Steps to reproduce
  1. Push against a wall consisting of some nodes. 
  2. Keep moving along it pressing down the forward key (only provided you move very slowly, straightely with short jerks).
  3. In some moment you may be pushed back abruptly slightly and then stopped as if you collide with another node is being towards your moving way.

**Comment by paramat** [comment]
There have been many changes to collision since March, please retest the bug.
