### ISSUE TITLE
Builtin Item lighting is never updated

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#9471]
##### Minetest version
```
Minetest 5.2.0-dev-9ca0b373-dirty (Linux)
```

##### Summary
The lighting for builtin items is never updated.
![screenshot](https://user-images.githubusercontent.com/1042418/76118317-e0b3f780-5fed-11ea-89b6-e1b2bb0ec855.png)

##### Steps to reproduce
1. Change time to day
2. Drop item
3. Change time to night
4. Observe bug

**Comment by sfan5** [comment]
bisected to 4b9fabf172dafa325a2adb9754c581a74d0f4e7b

@Wuzzy2

**Comment by sfan5** [comment]
Oh wait. Torches are supposed to glow now.

Hmmm, well I'm not sure if I like this.

**Comment by LoneWolfHT** [comment]
Hopefully someone will work on 'entity-based' world lighting soon
