### ISSUE TITLE
android build failed because of recent commits

### ISSUE THREAD

**Issue by tsao-chi** [minetest/minetest#9475]
##### Minetest version
https://github.com/minetest/minetest/commit/ce8cdc03337ac20b998620f2690eb76e5434ffb9

##### Summary
android build failed because of recent commits

##### Steps to reproduce
using the script of https://github.com/The-Unstable-World/The-Unstable-World

#### logs:
https://travis-ci.com/The-Unstable-World/The-Unstable-World/jobs/295232456

latest successful build: https://travis-ci.com/The-Unstable-World/The-Unstable-World/jobs/294264887

**Comment by sfan5** [comment]
<pre>
jni/../jni/src/client/sky.cpp:727:25: error: use of undeclared identifier 'm_star_count'

        u16 *indices = new u16[m_star_count * 3];

                               ^

jni/../jni/src/client/sky.cpp:729:25: error: use of undeclared identifier 'm_star_count'

                        new video::S3DVertex[m_star_count * 3];

                                             ^

jni/../jni/src/client/sky.cpp:730:22: error: use of undeclared identifier 'm_star_count'

        for (u32 i = 0; i < m_star_count; i++) {

                            ^

jni/../jni/src/client/sky.cpp:753:51: error: use of undeclared identifier 'm_star_count'

        driver->drawIndexedTriangleList(vertices.data(), m_star_count * 3,

                                                         ^

jni/../jni/src/client/sky.cpp:754:20: error: use of undeclared identifier 'm_star_count'

                        indices.data(), m_star_count);

                                        ^
</pre>
