### ISSUE TITLE
"cube" and "sprite" entity visuals are broken

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9479]
##### Minetest version
```
9ca0b3739cbaceaa291ac5062ab219e0aa7c49cb
```

##### Summary
The entity visuals `cube` and `sprite` are broken. Their shading no longer works (they are pitch black) and the `sprite` visual no longer supports sprite sheets.

This is a regression from Minetest 5.1.1.

##### Steps to reproduce
* Play the `devtest` game
* Give yourself the entity spawner (`testtools:entity_spawner`)
* Punch to select entity type, place to spawn entity
* Spawn the following entities: `experimental:yawsprite`, `testentities:cube`, `testentities:sprite` (feel free to spawn the other entities, too)

Expected: All entities are shaded properly and `experimental:yawsprite` displays a single, properly shaded sprite (dungeon master)
Actual: `testentities:cube`, `testentities:sprite`, `experimental:yawsprite` are pitch black. `experimental:yawsprite` displays the whole sprite sheet.

All of the entities worked in 5.1.1.

**Comment by sfan5** [comment]
> Their shading no longer works

this aspect might be duplicate with #9471

**Comment by SmallJoker** [comment]
Image from a January 27 build:
![grafik](https://user-images.githubusercontent.com/1497498/76150288-f0444680-60a8-11ea-9b5c-5acef4f65a1e.png)

:negative_squared_cross_mark: March 3
:negative_squared_cross_mark: February 16
:heavy_check_mark: February 3

Could this be related to the recent shader changes?

**Comment by SmallJoker** [comment]
Issue likely caused by 6958071f4. Disabling shaders in current master results in the wanted textures. @dcbrwn

**Comment by Wuzzy2** [comment]
Issue has been split in two: #9481, #9482.

**Comment by nininik0** [comment]
#13580
