### ISSUE TITLE
Entity shading is broken

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9482]
##### Minetest version

9ca0b3739cbaceaa291ac5062ab219e0aa7c49cb

##### Summary

The entity visuals cube and sprite are broken. Their shading no longer works (they are pitch black). 

It appears that falling nodes and dropped items are sometimes affected, too, but I haven't figured out  when this happens.

This is a regression from Minetest 5.1.1.

##### Steps to reproduce

* Play the devtest game
* Give yourself the entity spawner (testtools:entity_spawner)
* Punch to select entity type, place to spawn entity
* Spawn the following entities: testentities:cube, testentities:sprite (feel free to spawn the other entities, too)

Expected: All entities are shaded properly.
Actual: They are pitch black.

All of the entities worked in 5.1.1.

(note: split from #9479)

**Comment by sfan5** [comment]
Note: Dropped items definitely still work, this probably only affects "cube" and "sprite" as noted in the original issue.

**Comment by Wuzzy2** [comment]
OK, when a falling node falls in a cave (where there is no sunlight, it's always black).
And when a dropped item spawns inside a solid node, it's also always black, even when is it outside of all solid nodes.

My first guess: When an entity spawns with black lighting, this blackness is stuck for the remainder of its lifetime.

**Comment by paramat** [comment]
Note: Please see important comments made in #9479

I can confirm that an entity with "cube" visual is black when shaders are enabled. No bug with shaders disabled, see https://github.com/minetest/minetest/issues/9479#issuecomment-596124499

**Comment by appgurueu** [comment]
Wild guess: Those drawtypes have invalid normals.

**Comment by dcbrwn** [comment]
Is there any map or mod that allows to test all the rendering capabilities of minetest engine? Anyway I can look into this

**Comment by paramat** [comment]
https://git.minetest.land/Wuzzy/devtest

**Comment by dcbrwn** [comment]
on it

**Comment by dcbrwn** [comment]
the bug is not with the normals. entities start to be shaded correctly when surrounding light changes. fix is coming right up.

**Comment by paramat** [comment]
I can also confirm that an entity with "sprite" visual is black when shaders are enabled. No bug with shaders disabled.

**Comment by rubenwardy** [comment]
Latest dev:

![image](https://user-images.githubusercontent.com/2122943/78056226-afc0ab80-737c-11ea-86c2-9db39999b9d8.png)

![image](https://user-images.githubusercontent.com/2122943/78056305-d383f180-737c-11ea-88d5-367caf2dca27.png)

**Comment by rubenwardy** [comment]
Nevermind, it wasn't latest dev!
