### ISSUE TITLE
Description of active_block_range mentions non-existing setting

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9483]
##### Minetest version
```
5.1.0
```

##### Summary
There's a mistake in the documentation of `active_block_range`:

```
The radius of the volume of blocks around every player that is subject to the
active block stuff, stated in mapblocks (16 nodes).
In active blocks objects are loaded and ABMs run.
This is also the minimum range in which active objects (mobs) are maintained.
This should be configured together with active_object_range.
```

The setting `active_object_range` does not exist.

**Comment by sfan5** [comment]
Possible candidate: `active_object_send_range_blocks`

**Comment by paramat** [comment]
Relevant commit https://github.com/minetest/minetest/commit/2174298ffab0b6224cda35a47f326c7c4e53bf11 suggests sfan5 is correct.

**Comment by sfan5** [comment]
Wasn't the "Documentation needed / error" label for PRs that are missing docs?
I'd normally label this "Bug" "@ Documentation"

**Comment by paramat** [comment]
I changed the label as we need a label for 'documentation needed / error' issues. However, i can now see why this may not be good as it is now unusable for the original usage, i do not mind if you prefer to have 2 separate labels instead. Sorry for that.

**Comment by paramat** [comment]
Hmm, 'documentation needed / error' is not actually used for PRs at all, and only used for issues about missing or wrong documentation. So it seems ok.
I cannot see the need for a 'documentation needed' label  for PRs, that comes under 'action /change needed'.

**Comment by paramat** [comment]
I also find it hard to consider missing documentation a 'bug', it is harmless to functionality and nothing is broken. But i can see how this is down to how literally the word is interpreted.

**Comment by paramat** [comment]
Ok, re-added your labels.
Added a new label 'documentation needed' for PRs needing docs.
