### ISSUE TITLE
build bug

### ISSUE THREAD

**Issue by masrourmouad** [minetest/minetest#9484]
minetest 5.2 dev

GCC | 4.9
cmake . -DRUN_IN_PLACE=TRUE -DENABLE_SYSTEM_JSONCPP=1 .

error:

CMakeFiles/minetest.dir/convert_json.cpp.o: dans la fonction « fetchJsonValue(std::string const&, std::vector<std::string, std::allocator<std::string> >*) »:
convert_json.cpp:(.text+0x856): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o: dans la fonction « ServerList::deleteEntry(Json::Value const&) »:
serverlist.cpp:(.text+0x23e3): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text+0x2428): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text+0x244c): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text+0x2470): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text+0x24a9): encore plus de références indéfinies suivent vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o: dans la fonction « ServerList::sendAnnounce(ServerList::AnnounceAction, unsigned short, std::vector<std::string, std::allocator<std::string> > const&, double, unsigned int, float, std::string const&, std::string const&, std::vector<ModSpec, std::allocator<ModSpec> > const&, bool) »:
serverlist.cpp:(.text+0x4510): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x4562): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x4592): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x4818): référence indéfinie vers « Json::Value::append(Json::Value&&) »
serverlist.cpp:(.text+0x4872): référence indéfinie vers « Json::Value::append(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text+0x48a5): encore plus de références indéfinies suivent vers « Json::Value::append(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o: dans la fonction « void std::vector<Json::Value, std::allocator<Json::Value> >::_M_insert_aux<Json::Value>(__gnu_cxx::__normal_iterator<Json::Value*, std::vector<Json::Value, std::allocator<Json::Value> > >, Json::Value&&) »:
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x27): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x8a): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0xbf): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0xe3): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x10c): référence indéfinie vers « Json::Value::Value(Json::Value&&) »
CMakeFiles/minetest.dir/serverlist.cpp.o:serverlist.cpp:(.text._ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_[_ZNSt6vectorIN4Json5ValueESaIS1_EE13_M_insert_auxIIS1_EEEvN9__gnu_cxx17__normal_iteratorIPS1_S3_EEDpOT_]+0x12f): encore plus de références indéfinies suivent vers « Json::Value::Value(Json::Value&&) »
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetest.dir/build.make:7129: recipe for target 'bin/minetest' failed
make[2]: *** [bin/minetest] Error 1
CMakeFiles/Makefile2:195: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:137: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SmallJoker** [comment]
Update jsoncpp, compiler, or both. Further information:
https://github.com/minetest/minetest/issues/8562
https://github.com/minetest/minetest/issues/8315
https://github.com/minetest/minetest/issues/7681
https://github.com/minetest/minetest/issues/6567
