### ISSUE TITLE
set_sky colours bug when using table form of colorspec

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9491]
@Jordach 
Note that the old set_sky call works fine when using the table form of a colorspec.

When i use the new set_sky call:
```
		player:set_sky({
			{a = 255, r = 255, g = 0, b = 0},
			type = "plain",
			clouds = false,
		})
```
This should result in a plain sky and fog of bright red colour, and no clouds.
Result is dark colours, sometimes changing each session, that are not bright red, see screenshots:

![screenshot_20200309_211848](https://user-images.githubusercontent.com/3686677/76259402-73060680-624d-11ea-8943-e42e65fa72d9.png)

![screenshot_20200309_212315](https://user-images.githubusercontent.com/3686677/76259420-7a2d1480-624d-11ea-8274-c73a01dc995e.png)

**Comment by rubenwardy** [comment]
You are missing a key in the table:

```lua
player:set_sky({
    base_color = {a = 0, r = 255, g = 0, b = 0},
    type = "plain",
    clouds = false,
})
```

The alpha being zero (ie: completely transparent) is also suspicious

Please provide an exact reproducible example.

**Comment by paramat** [comment]
Aaargh, thanks, retesting.

**Comment by paramat** [comment]
My mistake, no bug.

**Comment by paramat** [comment]
I have just thoroughly retested set_sky (as i did not retest the PR just before merge) and it seems fine.
