### ISSUE TITLE
UNIQUE constraint failed in sqlite3-auth database

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/minetest#9498]
##### Minetest version
```
stable-5
```

##### OS / Hardware
Operating system: Linux
CPU: x86_64

##### Summary

This error happens now and then:
```
2020-02-23 09:42:42: ERROR[Main]: Failed to finalize m_stmt_create: UNIQUE constraint failed: auth.name
2020-02-23 09:42:42: ERROR[Main]: Failed to finalize m_stmt_begin: cannot start a transaction within a transaction
2020-02-23 09:42:55: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback createAuth(): : UNIQUE constraint failed: auth.name
2020-02-23 09:42:55: ERROR[Main]: stack traceback:
2020-02-23 09:42:55: ERROR[Main]: 	[C]: at 0x558210fbf980
```

I'm guessing it has something to do with the used `sqlite3-auth` database.

##### Steps to reproduce
No clue, my bet is on a race-condition where a client sends multiple auth-requests that get delayed by the `prejoin` lua environment and hit the AuthDatabase, which in turn execute the same insert-statement

##### Mitigation / Solution

I'm currently using this to mitigate the error, worked well so far but is not very "elegant":

```diff
diff --git a/src/database/database-sqlite3.cpp b/src/database/database-sqlite3.cpp
index 1bacdfe6..5bdd5b22 100644
--- a/src/database/database-sqlite3.cpp
+++ b/src/database/database-sqlite3.cpp
@@ -659,7 +659,7 @@ void AuthDatabaseSQLite3::initStatements()
 {
 	PREPARE_STATEMENT(read, "SELECT id, name, password, last_login FROM auth WHERE name = ?");
 	PREPARE_STATEMENT(write, "UPDATE auth set name = ?, password = ?, last_login = ? WHERE id = ?");
-	PREPARE_STATEMENT(create, "INSERT INTO auth (name, password, last_login) VALUES (?, ?, ?)");
+	PREPARE_STATEMENT(create, "INSERT OR REPLACE INTO auth (name, password, last_login) VALUES (?, ?, ?)");
 	PREPARE_STATEMENT(delete, "DELETE FROM auth WHERE name = ?");
 
 	PREPARE_STATEMENT(list_names, "SELECT name FROM auth ORDER BY name DESC");
```

**Comment by SmallJoker** [comment]
The client registration is single-threaded, and clients only send one auth request per connection (INIT).

I think the proper solution for this would be to skip the code in `auth_create()` if the account already exists. `auth_save()` should be used for password or login date updates.

**Comment by Festus1965** [comment]
I try to find this, as happen too often (about once a day):

Is this in builtin/game/auth.lua : line 47 ?

options of trigger ?
* login same name, other password = OK = just report wrong password
* login same name, same password = OK = just report Another client with this name is logged in
* login too early after times out ??
* or I also have reports of ... oh what it is, unknown char-set like ... like someone uses a language that is not supported, what will happen if that is done in password ? (but name is maybe English set)

**Comment by Festus1965** [comment]
after this change it didn't happen anymore, ok 5 hours is not much, but 
I set sqlite_synchronius = from until now 0 to 1
as I have over two days near every second a new gamer, maybe that was the problem.

If failure don't occur in nest 3 days, then I found the reason. top 53 gamer in server, sure that could make sqlite a problem, as don't like simultaneous access.

**Comment by Festus1965** [comment]
change:
I successful installed and enabled leveldb even on multicraftserver, (also HIredis)
and migrated the 13.000+ entries to leveldb.

So if NOW for about 3 days, with still about 1.000 new entries is a crash,
* it is not the db, as that one changed,
* the successful migration meant to mean no failure in file
* so then it is the mod itself

I HOPE for no ant crash anymore, as I am sick about this
and we know then also easy ... where the problem might be: Sqlite3

**Comment by BuckarooBanzay** [comment]
closing this, it has the same root-cause as #11877
