### ISSUE TITLE
Modern menu HUD thing lol

### ISSUE THREAD

**Issue by xenoAVP** [minetest/minetest#9499]
Well its not really a problem its a request it would be nice to change the menu appearance to a more (round) and modern stile menu (buttun text ect)

![Real minetest menu](https://user-images.githubusercontent.com/54017343/76316257-defb7400-630c-11ea-9db1-8ecce4444ec0.png)

I made a little preview of what could be nice too see in a future update :D

**Comment by rubenwardy** [comment]
Duplicate of #6733
