### ISSUE TITLE
Misaligned item_image

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9507]
Reported by @MoNTE48 

> @rubenwardy 
> https://www.youtube.com/watch?v=MK29S9h7Xjw
> (Watch the video at 0.5 in speed to notice the details!)
> Here is a sample code. And how it worked UNTIL 5.2
> Can you imagine how much time was spent on perfect alignment of all elements with the old coordinate system?
> ```
> "image_button["6.74,-0.35";1.3,1.3;creative_tab.png;tools;;;false;creative_tab_pressed.png]" ..
> "item_image["6.87,-0.15";1,1;"default:pick_emerald"]" ..
> ```

![image](https://user-images.githubusercontent.com/2122943/76460264-9bb90800-63d5-11ea-9d10-7e03e83d0780.png)

**Comment by rubenwardy** [comment]
```lua
minetest.register_on_joinplayer(function(player)
        local fs = [[
                size[2,2]
                image_button[0,0;1.3,1.3;default_stone.png;tools;;;false;default_dirt.png]
                item_image[0,0;1,1;default:pick_mese]
        ]]
        minetest.show_formspec(player:get_player_name(), "ss", fs)
end)
```

**Comment by MoNTE48** [comment]
@rubenwardy, thanks.
Compare with this buggy MineClone inventory... And you will understand why the problem is really important.
In MultiCraft, perfectly adjusted coordinates, button click animation, no slightest bias when choosing a tab. And also we not used the buggy detached inventory, which made players jump from happiness!

**Comment by rubenwardy** [comment]
wait, my example is wrong. Here's what it looks like:

![image](https://user-images.githubusercontent.com/2122943/76460214-89d76500-63d5-11ea-8944-00cf0e87f4a3.png)

**Comment by rubenwardy** [comment]
Is the positioning a problem, or just the button animation?

**Comment by MoNTE48** [comment]
Bro, the question is not about positioning . Offset - perfect MineClone Code

**Comment by rubenwardy** [comment]
In which case: #9361
