### ISSUE TITLE
Ability to hide players from minimap

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9512]
Currently, entities only show on the minimap if they have a nametag. This behaviour should be extended to players

## Alternative

A hud property to hide from the minimap

**Comment by LoneWolfHT** [comment]
@Extex101 Why the downvote?

**Comment by Extex101** [comment]
I find it usefull to have this.
Severs that disable player tags usually havr no minimap except ppl eith the privs. I think it should be kept for admins and moderators finding the players.

**Comment by LoneWolfHT** [comment]
> I find it usefull to have this.
> Severs that disable player tags usually have no minimap except ppl with the priv. I think it should be kept for admins and moderators finding the players or at least knowing where they are.

This wouldn't be removed, just toggleable by mods, possibly per-player

**Comment by sorcerykid** [comment]
I think the point that Extex is making is that the players should always show on the minimap for the server admin or anyone else with elevated privileges.

**Comment by rubenwardy** [comment]
Hiding players from the minimap when they don't have a nametag is a sane default, but it would be nice to also have a hud flag for this. Currently, the minimap is unusable by all player except moderators.

I also oppose tying this to a moderator privilege, it should be a flag that is controlled by mods. For example, moderators on CTF shouldn't be able to see players because I carefully avoid giving moderators gameplay advantages

**Comment by sorcerykid** [comment]
I'm confused how the minimap is unusable to all players except moderators? Did something change with Minetest 5.x?

**Comment by rubenwardy** [comment]
It's unusable because it reveals the locations of other players when they don't have nametags

**Comment by sorcerykid** [comment]
But if a player can hide their nametag and be invisible on the minimap from everyone including administrator(s), then that seems like it is the perfect tool for cheaters to be able to evade detection of nefarious activities. I guess I'm of the opinion that administrator(s) should always under every circumstance be able to monitor players on their server regardless of what nametag and minimap flags are set on any given player. Hopefully that better clarifies my position :)

**Comment by rubenwardy** [comment]
> But if a player can hide their nametag and be invisible on the minimap from everyone including administrator(s),

They can't, a mod can

-----

how many nefarious activities do you actually catch using the minimap?

**Comment by Wuzzy2** [comment]
Ohhhhh, that's where the red dot sometimes comes from. I always wondered why some things appeared on the minimap while others didn't.

I think the minimap marker shouldn't be tied to the nametag at all. It just doesn't make sense. Nametag and minimap marker should be treated as two separate beasts.

Don't bother about “breaking” things, current behavior is undocumented anyway.

**Comment by Wuzzy2** [comment]
Here's what I suggest:

- Add a new object property `show_on_minimap`. If `true`, the object will get a marker on the minimap. If `false`, it won't.
- This property needs to be functional for both players and non-player objects.
- The `show_on_minimap` property shall be the only property that affects the minimap marker. Properties like nametag, etc. shall be ignored.
- Initialize this property as `true` for players and `false` for other objects.
- Ignore backwards-compability, as the current behavior is just too strange and limiting and undocumented anyway.
