### ISSUE TITLE
Selecting text in a textarea sends "change" event to nearby textlist

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#9518]
##### Minetest version
```
Minetest 5.2.0-9ca0b37 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
##### Operating system
Microsoft Windows 10 Home Build 17134

##### Summary
If I drag the mouse to select a large portion of text in a textarea and accidentally continue dragging into a nearby textlist, then I receive a change event for the textlist. The expected behavior is that I should be able to drag completely outside of a textarea, and no other GUI components will be effected.

![ezgif com-video-to-gif (3)](https://user-images.githubusercontent.com/24327224/76702503-5bd57780-6698-11ea-8982-a4376cb239ec.gif)

Currently the only workaround is to ensure that editable textareas are placed as far apart from textlists as possible so there is no risk of unwanted textlist change events.

**Comment by sfan5** [comment]
I have also observed this in the mainmenu with the username field and the server list.
Does the unwanted change of focus happen with any combination of formspec fields or just textarea & textlist?

Also, this might be a bug/missing feature in Irrlicht rather than being related to Minetest or formspecs.

**Comment by sorcerykid** [comment]
I just noticed that it also happens with a regular field vs. textlist as well. I haven't tested to see what happens with tables. But if as you said this same bug occurs in the main menu screen, then I believe that the server listing is a table.

My best guess is that tables and textlists are constantly polling for mouse-down events, rather than mouse-click events. This would seem to be the case given that as the GIF above illustrates, the selection changes rapidly just by dragging the mouse upwards through the textlist from out of the textarea.

**Comment by rubenwardy** [comment]
Does this happen in 5.1.1 or earlier versions?

**Comment by SmallJoker** [comment]
:ballot_box_with_check: 13 October
:negative_squared_cross_mark: 30 November

That's the most precise I can offer without real bisecting. Based on my build history.

**Comment by rubenwardy** [comment]
OK, this is a regression but I don't think it should be considered a blocker

**Comment by sfan5** [comment]
in 72416a6:
![diff](https://user-images.githubusercontent.com/1042418/76708956-46de0000-66fb-11ea-9866-bc12a5594896.png)

I can't seem to find any explanation why this was done.

**Comment by pyrollo** [comment]
Thought this code was to ensure hovered hypertext links react even when element does not have focus but everything still work as expected after your fix. Sorry for this bug.
