### ISSUE TITLE
Falling nodes glow in the dark

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9525]
##### Minetest version
```
5c1b72544a6158346b7d8608c895678fe7d5a19b
```

##### Summary
Falling nodes glow in the dark.

##### Steps to reproduce
1. Fly into a cave that is pitch black
2. Place any falling node like sand

**Comment by sfan5** [comment]
Also affects dropped items.

The reason is that the scene node has no materials, so this for loop never does anything and sets no color:
https://github.com/minetest/minetest/blob/5c1b72544a6158346b7d8608c895678fe7d5a19b/src/client/content_cao.cpp#L843-L846

**Comment by sfan5** [comment]
It appears that wieldmesh entities currently cannot be shaded using since they use a [different](https://github.com/minetest/minetest/blob/5c1b72544a6158346b7d8608c895678fe7d5a19b/src/client/wieldmesh.cpp#L349-L352) shader internally.
In the meantime, a workaround is to do this:
```diff
diff --git a/src/client/content_cao.cpp b/src/client/content_cao.cpp
index 49463c3d..61919967 100644
--- a/src/client/content_cao.cpp
+++ b/src/client/content_cao.cpp
@@ -839,6 +839,8 @@ void GenericCAO::setNodeLight(u8 light)
                                video::SMaterial &material = buf->getMaterial();
                                material.EmissiveColor = color;
                        }
+               } else if (m_prop.visual == "wielditem" || m_prop.visual == "item") {
+                       m_wield_meshnode->setColor(color);
                } else {
                        for (u32 i = 0; i < node->getMaterialCount(); ++i) {
                                video::SMaterial &material = node->getMaterial(i);
```

@dcbrwn thoughts?

**Comment by dcbrwn** [comment]
This should work. Although it's very tempting to make "wielditem" and other 3D renderables to use same shader.

**Comment by dcbrwn** [comment]
I can make a proper PR and test this on saturday.

**Comment by SmallJoker** [comment]
@dcbrwn Yes, that would be great if you have time for that. Otherwise the two-liner change would be a good solution for now as well.

**Comment by dcbrwn** [comment]
Sorry, I got a little bit distracted yesterday. PR is ready for review.

**Comment by SmallJoker** [comment]
Related: #9636
