### ISSUE TITLE
Cannot build minetest

### ISSUE THREAD

**Issue by Dmitry450** [minetest/minetest#9526]
I'm trying to build minetest, and when i'm running 'make -j$2', builder uses ALL RAM and i can't do anything.
If i'm running 'make' instead, it's prints error:
```
[  0%] Built target jsoncpp
[  8%] Built target lua
[  8%] mo update
[ 30%] Built target translations
-- *** Detected Git version 5.2.0-dev-5c1b725 ***
[ 30%] Built target GenerateVersion
[ 30%] Linking CXX executable ../bin/minetest
CMakeFiles/minetest.dir/client/activeobjectmgr.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
src/CMakeFiles/minetest.dir/build.make:7384: recipe for target 'bin/minetest' failed
make[2]: *** [bin/minetest] Error 1
CMakeFiles/Makefile2:253: recipe for target 'src/CMakeFiles/minetest.dir/all' failed
make[1]: *** [src/CMakeFiles/minetest.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SmallJoker** [comment]
1) Remove the file `CMakeFiles/minetest.dir/client/activeobjectmgr.cpp.o` and retry
2) How much free RAM do you have before `make`? 2 GB should be enough.
3) Check for GCC updates

**Comment by Dmitry450** [comment]
1. I tried to find `minetest.dir`, but i can't. 
2. ~3 GB
3. I'm updating it, but my internet is too slow, i will reply, if update will solve problem

**Comment by Dmitry450** [comment]
No, it still takes up all the RAM. Why?

**Comment by sfan5** [comment]
> `make -j$2`

This is wrong, it will expand to `make -j` which instructs make to start as many compile commands in parallel as possible.
If you want to build in parallel with 2 jobs use `make -j2`.
