### ISSUE TITLE
Position of hypertext[] element with old coordinates is highly inconsistent

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#9527]
![image](https://user-images.githubusercontent.com/24327224/77133485-35656280-6a31-11ea-9377-6f15d1499d87.png)

##### Minetest version
```
Minetest 5.2.0-9ca0b37 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```
##### Operating system
Microsoft Windows 10 Home Build 17134

##### Summary
I finally decided to start using the HTML-like element, except it seems there is a bug with how the position is calculated because it is nowhere near where it should be compared to all other elements.

This is an example of a form with the hypertext[] element at X=3, Y=1. The box[] element is also at X=3, Y=1, which is the exact same position. Yet they are not even remotely aligned.

**Comment by SmallJoker** [comment]
How about before 766d160f?
This change was requested in https://github.com/minetest/minetest/pull/9392#issuecomment-584982105

**Comment by sorcerykid** [comment]
Yep, I think it's possible that may be the resolution. But the latest sfan5 build for windows is 0cb34ce. So I can't confirm for certain.

**Comment by sfan5** [comment]
You can download a fresh build from the [Gitlab pipeline](https://gitlab.com/minetest/minetest/pipelines/).

**Comment by sorcerykid** [comment]
Thanks for the heads up! I didn't even know about those. It looks like that commit fixed it, as the layout is exactly as expected now.
