### ISSUE TITLE
Featured games

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9530]
This is a discussion issue split off from #9509.

###### The problem

We have a couple of nice games now, but they are still tricky to find. We have the Content DB now, but the quality of each games still varies wildly. Experimental games in alpha stage are listed alongside mature and polished games, and the player has no chance to see which is which.

And it is now a real possibility that MT will eventually ship with no games (see #9509).

But this will automatically create the next problem: Since Content DB has only a minimal quality control at the moment, this means if a player installs a game at random from the Content DB, it's likely one of the bad/incomplete ones.

###### Featured games
My answer is: Featured games! Featured games are finished games of high quality that meet a set of quality criteria.

The idea is to throw out all games that are broken, buggy, unfinished, in “perpetual beta”, etc. from all highly-visible places. It's not about banning low-quality games *altogether* but to move them to less-visible places.

I am convinced that it is *critically* important which games we promote, and which we don't. The new player *will* judge Minetest by the first game they play.

###### Proposed quality checklist
Which criteria are to be used exactly for being featured, is open for discussion.

My first proposal is a quality checklist that a game needs to pass:

https://wiki.minetest.net/User:Wuzzy/Proposal:_Featured_games

This list checks for:

* Compability
* Stability (no crashes, no game-breaking bugs)
* Correct metadata
* Works out of the box
* No graphics that hurt the eyes
* No sounds that hurt the ears
* No typos, etc.
* A lot of small but kinda important things
* FOSS
* More …

My list is not exhaustive, a game can tick off all the boxes and still be boring. But it's a start.
There still needs to be some sort of process to decide which games to feature.

My second idea is to introduce a new tag for Content DB, and it is called “unfinished”. This is used for all games that the author consideres unfinished/beta/alpha. A game is considered “finished” when the author says it is. Minetest can then automatically filter out all those unfinished games. They are only visible when the user enabled it or goes to the website. This has not really something to do with featured games, but I think it will be an useful filter nonetheless.

The final step is to work out HOW to present featured games to the player: In Minetest, on Content DB website and on www.minetest.net. For www.minetest.net, a very good source of inspiration is <https://www.solarus-games.org/en/games>. Instead of having a short, boring, outdated list like on www.minetest.net, every game has its own little standalone page, image, description and download links, wiith screenshots. Sadly, they also feature unfinished games but at least they clearly admit it when you click on the game.

Feel free to come up with your own ideas.

###### Current situation
Technically, we DO have featured games, but it's done poorly.

Games are currently featured on <https://www.minetest.net/customize/>, but this list is bad and outdated. Tutorial is not a real game, and Pixture is outdated and buggy in 5.0.0 (sunken player model bug) and has been succeeded by Repixture. The list of featured games and mods on the homepage is updated only very rarely. IMO, the selection of games also feels kind of arbitrary.

Sidenote: The list of featured mods is even worse, there are just way too many of them and it's outdated. It's also incredibly biased, most mods are MTG-only without saying it. The selection of mods also feels kind of arbitrary. I don't think it's a good way to feature mods, and it needs rethinking as well (but this is out of scope).

**Comment by paramat** [comment]
+1 for the basic concept.

> The idea is to throw out all games that are broken, buggy, unfinished, in “perpetual beta”, etc. from all highly-visible places. It's not about banning low-quality games altogether but to move them to less-visible places.

Well ... =) I prefer to state this in the positive: Move the highest quality games to the most-visible places, that is, featured games.
> My second idea is to introduce a new tag for Content DB, and it is called “unfinished”. This is used for all games that the author consideres unfinished/beta/alpha.

It is very rare for a game to ever be considered 'finished', and very difficult to decide that, consider MTG for example.
If a game is 'in an unusable state' it simply should not be in the CDB at all, being in the CDB is this filter already.
It is completely possible for a game to be 'unfinished' (further development is expected) but be very usable and enjoyable, so i feel this filter will filter out games that should not be filtered out.
Does not seem worth doing to me.

**Comment by Wuzzy2** [comment]
I very much dislike the notion of a game never being “truly” finished or the concept of “perpetual beta”. This is BS.
“finished” does not imply that it's the final version ever. It does NOT mean that there is (theoretically) more stuff to add. It does NOT mean that 100% perfection has been reached. Roughly spoken, a game that is considered “release-worthy” can be called “finished”, but the ultimate decision should be with the author. In terms of version numbers, version 1.0 is the “finished” version, but of course, the version numbering system does not neccessarily stop at 1.0.

In technical terms: The first “finished” version of a game is the first version that comes after the beta.

There was a time before the Internet, game developers eventually had to decide when a game is finished. Under the “perpetual beta” ideology, there would have never been any game releases before the Internet.

> It is very rare for a game to ever be considered 'finished', and very difficult to decide that, consider MTG for example.

Sorry, this is just completely false. Sure, the are games that are just abandoned before they are even barely playable. But there's still a lot of games for which the author(s) have a clear vision, and they know very well when they are done.

You are too biased in your thinking by considering sandbox games only. But it is usually much clearer when (e.g.) a simple Tetris clone or an first-person-shooter is finished.

But well, you can consider my criteria for “finished” games only to be a vague one, as it depends on author's opinion. The idea is, if not even the author considers is good enough for release, it should probably not be featured. It might also be rude to the author to feature a game too early if the author still things there are important tasks to do …

If the author thinks it is very difficult to decide whether a game is finished or not, this is could be a sign that the game planning went wrong. ;)

**Comment by appgurueu** [comment]
I support this. The score currently used misrepresents game popularity & quality.

But this probably belongs to ContentDB, where I already opened an issue requesting ratings to be a feature.

**Comment by hecktest** [comment]
ContentDB could have several suggested categories, like most downloads total, most recent downloads, recently added, and recently updated.

**Comment by paramat** [comment]
Wuzzy2, i interpreted the word 'finished' in a different way to how you meant it, sorry.
But, i still think that word is the wrong one for the filter.

**Comment by rubenwardy** [comment]
Featured tag has been added. See [ContentDB's homepage](https://content.minetest.net/). Policies to choose featured packages TBD

**Comment by rubenwardy** [comment]
Discussion to continue on https://github.com/minetest/contentdb/issues/321

(maybe I should have transferred that issue there? Idk)

**Comment by rubenwardy** [comment]
Merged ContentDB PR
