### ISSUE TITLE
Hypertext alignment tags add extra newline

### ISSUE THREAD

**Issue by v-rob** [minetest/minetest#9535]
##### Minetest version
```
5.2.0-dev
```

##### OS / Hardware
Operating system: Windows 10

##### Summary
The formspec `hypertext` element has a problem with the alignment tags `left`, `right`, `center`, and `justify`:  Normally, when adding a newline, a new paragraph is started.  If a newline is placed _and_ an alignment tag is used, then an extra newline is added.  This is counter-intuitive because it means that alignment tags must be on the same line as the paragraph before it.

Note that newlines below alignment tags only add newlines as needed; it's only above them that has this strange behaviour.

I would classify this as a bug because the behaviour is wrong, and we should change it before hypertext goes mainstream.

##### Solution
Make alignment tags only add a newline if they are on the same line as everything else since it is necessary in this situation, but don't otherwise.

##### Steps to reproduce
```
formspec_version[3]
size[10,10]
hypertext[0,0;10,10;This is a paragraph.
This is another paragraph.<right>This is a right-aligned paragraph with a newline above it because it needs it.</right>
Yet another paragraph.
<right>A right-aligned paragraph with an extra newline above it when it looks like it shouldn't.</right>]

**Comment by pyrollo** [comment]
Hi PR #9548 should fix that.
