### ISSUE TITLE
Add support for PUT and DELETE methods in HTTPRequest

### ISSUE THREAD

**Issue by sorcerykid** [minetest/minetest#9538]
## Problem

There is currently no way to perform PUT and DELETE requests. Yet these two methods are often required by APIs of GitLab, Bitbucket, and GitHub in order to update or delete specified endpoints.

## Solution

I would suggest adding an optional `method` field to the HTTPRequest table that can be either `GET`, `PUT`, `POST`, or `DELETE`. If the `post_data` field is not nil, then the method will be constrained to just `POST` (default as usual) or `PUT`.

**Comment by theviper121** [comment]
I'm using a python script to work around this now. I will likely post it when complete.

**Comment by Lejo1** [comment]
PR is merged
