### ISSUE TITLE
Way for minetest to "hear" sounds

### ISSUE THREAD

**Issue by Extex101** [minetest/minetest#9545]
### Request
Add a minetest.get_sounds(pos) or minetest.listen(pos)
I favor listen :P

Detect 3d sound from a specific location
e.g.
```lua
local sounds = minetest.get_sounds({x=0,y=0,z=0})--returns a list of sounds detected in the format used by minetest.play_sound with the addition of the sound file name and loudness from the position provided
```

### Uses
 - Allowing mobs to hear players or other mobs when they make noise
 - Sound effect subtitles mod?

**Comment by ClobberXD** [comment]
Concept sounds interesting and has potential :+1: 

Btw, subtitles could be better implemented within MT itself as a client-side accesibility option (maybe as an additional soundspec param?) rather than as a mod.

**Comment by sorcerykid** [comment]
My Avatars mod provides the ability for NPCs to sense both audio and visual stimulii. It is inspired by Looking Glass Studios' [Dark Engine](https://en.wikipedia.org/wiki/Dark_Engine) which had a sophisticated architecture for AI sensory processing.

https://forum.minetest.net/viewtopic.php?f=9&t=21688

My other WIP mod, Axon, uses a more generalized event propagation mechanism, in which incidental sounds can be transmitted and detected via sources and receptrons. In most cases, it's simply a matter of defining a stimulus and then applying it to a node or an entity with optional properties to control the radius, intensity, chance, and curve. Then any entities within the area thata have a matching receptron for the stimulus type receive a callback with details about the event.

**Comment by Extex101** [comment]
> Concept sounds interesting and has potential 

The concept *sounds* interesting :P
Was that supposed to be punny? lol

> Btw, subtitles could be better implemented within MT itself as a client-side accesibility option (maybe as an additional soundspec param?) rather than as a mod, IMO.

Yeah that's a good point.
I was thinking of a mod that detects the sounds and has a massive database of sound descriptions lol

**Comment by nerzhul** [comment]
i think it's a good idea for mobs to generate some aggro based on sound source, but do we have sound noise levels on the emitted sounds ? or it will just be based on the distance ?

**Comment by sorcerykid** [comment]
It looks like I've basically resolved this issue with the release of my [Axon mod](https://github.com/sorcerykid/axon/wiki) last week. Now AI can respond to sounds as well as just about any other type of environmental stimulus. Most events are communicated either directly or radially from source to receiver(s). Nodes also allow for a variety of specialized propagators including contact, radiation, emission, and immersion.

Here I'm shooting at a glass floor and scaring away all the pigeons:

![](https://i.imgur.com/ZAJZgV9.gif)

In the video below I frightened a castle guard by firing arrows in his vicinity. Notice that he ramps up alertness as the noises grow louder and more frequent, but eventually he gives up the search.

https://vimeo.com/420666141

All of this took just a few lines of code in the mob definition:

```
receptrons = {
        noise_stim = { on_reaction = function ( self, intensity, direction )
                -- general approximation of noise origin
                local pos = vector.add( self.pos, vector.multiply( direction, intensity * 0.6 ) )

                if intensity < 4 and self.state == "ignore" then
                        self:reset_alertness( "remark", { pos = pos } )
                        self:play_sound( self.sounds.remark )
                elseif self.state == "ignore" or self.state == "remark" then
                        self:reset_alertness( "search", { pos = pos } )
                        self:play_sound( self.sounds.search )
                end
        end },
},
```

**Comment by ClobberXD** [comment]
@sorcerykid Wow, just wow... :)

**Comment by rubenwardy** [comment]
That's awesome @sorcerykid, and the better way to do things like this imo - having a 3d event system like that is what a lot of games do. You've already mentioned Dark Engine, but [Mafia](https://gamasutra.com/blogs/JiriHolba/20200518/363119/Openworld_Enemy_AI_in_Mafia_III.php) also uses it
