### ISSUE TITLE
Use progress bar textures if provided by mod or game

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9549]
## Problem

Progress bar textures (`progress_bar.png` and `progress_bar_bg.png`) are not used if provided by a mod or game. Currently, they only work if provided by texture packs.

## Solutions

Use them and display themed progress bars.

## Alternatives

None.

## Additional context

The current progress bar looks good, but as Minetest is supposed to be an engine, I'd like to theme it within my mods and games.

**Comment by Warr1024** [comment]
Sadly this probably wouldn't be able to work for multiplayer, since custom textures aren't available until after the media is loaded.  However, for single player it should be possible, and would be very nice.

Also, some other main-menu or HUD features like the Android controls and such would be nice (looking at the texture pack spec) if they aren't already supported.

**Comment by appgurueu** [comment]
> Sadly this probably wouldn't be able to work for multiplayer, since custom textures aren't available until after the media is loaded.

Well, technically the server could send the progress bar first? Not sure whether it'd be worth the effort, though.

**Comment by SmallJoker** [comment]
This breaks the order of initialization and media loading. Not keen adding an exception to it or reordering the procedure just to implement this.
Use texture packs for customization.

**Comment by Warr1024** [comment]
Multiplayer definitely sounds more trouble than it's worth.

Singleplayer, on the other hand, is already loading resources out of the game locally for icons, backgrounds, headers, etc. so there doesn't seem to be a good reason why it shouldn't be possible to load the other things like progress bars, on-screen controls, etc.

If this ends up being limited to only when games are loaded locally, and only for singleplayer, it would still have an effect on a significant audience.

**Comment by sorcerykid** [comment]
It is quite sad that there is no way for servers to customize the loading screen. I mean, heck, even as far back as the days of the Apple II plus, software could customize the boostrap to display graphics and text even before DOS itself was loaded. And even without that hack, it was possible to display graphics and text once DOS was loaded, but before the main program was launched. It wasn't necessary to wait 15-20 seconds just for all program code and assets to be loaded into memory.

I realize it's probably asking for a lot, but even if there was a bare minimum degree of customization that would be awfully nice. Something like of simple property table to define the basic appearance with the progress bar images just being a Base64 encoded string. And then all of that would be sent serialized to the client after the authorization phase, so it would be a bare minimum of overhead.

**Comment by paramat** [comment]
I agree with SmallJoker.
I also think having this for singleplayer only would be bizarre and wrong.
:-1:

**Comment by GoodClover** [comment]
I'm not sure if the situation was different when this issue was made, but it's possible to alter things such as the menu background via the `menu/` folder now.
I assume the same could be done here.
