### ISSUE TITLE
JavaScript binding, embed V8 engine

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9552]
## Problem

Many would like to be able to use a more common, and possibly faster, scripting language than Lua.
JavaScript seems suited, as it is mostly similar to Lua.

## Solutions

Embed Google's V8 and create a wrapper so that existing code doesn't need to be changed (the wrapper should provide all Lua API methods like lua_pushnumber etc - basically, sections 3 and 4 of [the manual](https://www.lua.org/manual/5.1/manual.html)).

## Alternatives

Use Lua preprocessors.

**Comment by sfan5** [comment]
duplicate #6337

**Comment by appgurueu** [comment]
@sfan5 please reopen either this or #6337

**Comment by sfan5** [comment]
Why? The feature was discussed and rejected in the other issue.
