### ISSUE TITLE
Hypertext: <global> color/hovercolor does not affect <action> links

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9557]
##### Minetest version

```
3c0d30964315ad9e2cba2c6ade1260d8b35293da
```

##### Summary
If you set a `<global>` with `color` and `hovercolor` in a `hypertext[]` formspec element, and add an `<action>` link, the color of the `<action>` link is NOT affected.
Only the normal (not linked) text will be colorized.

##### Steps to reproduce
- Grab `devtest`
- Start it
- `/test_formspec`
- Click the “Hypertext” tab
- This should render 2 `hypertext[]` elements: one top, one bottom

We only care about the bottom now. The bottom element tests `<global>`. It sets all possible attributes that `<global>` can have, including `color` and `hovercolor`.

Expected: The action link takes the color and hovercolor as set in `<global>`
Actual: Hyperlink color remains at default (blue / red).

Note: You can find the testing code in the `testformspec` mod.

**Comment by sfan5** [comment]
This doesn't look like it absolutely needs to be fixed for 5.2.0 to me.
