### ISSUE TITLE
hypertext[] escape characters are undocumented

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9558]
`lua_api.txt` does not mention the possible escape characters for `hypertext[]`.

So, please add them.

**Comment by appgurueu** [comment]
I assume they are `&lt;` and `&gt;` ?

**Comment by sfan5** [comment]
It's when you put a `\` before a character:
https://github.com/minetest/minetest/blob/master/src/gui/guiHyperText.cpp#L218

**Comment by pyrollo** [comment]
Yes sfan5 is right, `\` before a char escapes it. I'm not sure keeping this syntax and may move toward a more HTMLish thing like `&lt;` and `&gt;`. If you have any opinion on that, please comment on https://github.com/minetest/minetest/issues/9529#issuecomment-605818837
