### ISSUE TITLE
Document the new set_sky API night colours as unstable

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9560]
See discussion in #9508 
It might be a good idea to do this for 5.2.0 so that we can add the feature described in #9508 
The new set_sky API is fully functional and can still be used by modders, but at least they will be warned that any custom night colours will need editing in future.

**Comment by Jordach** [comment]
Not a blocker, changing the night sky blending algorithm will change the existing night sky colours as defined for backwards compatibility.

**Comment by sfan5** [comment]
Wouldn't it suffice to mark the exact sky color as subject to change?
Marking the whole API as unstable and un-deprecating the old API doesn't look necessary to me.

**Comment by Wuzzy2** [comment]
A few weeks ago, I played around with `set_sky` and related functions in -dev and it was quite cool.
I have found a bug, but it has been reported and fixed.

The only problem that I am aware of right now is the weird night sky color scheme. The rest of the API is sound. I agree with sfan5 that it's way too overkill to brand the *entire* API as unstable, when it's only the specific night sky that is problematic.

@Jordach: So currently the night sky color you enter is not the true night sky color, it's much darker. When in future, this behavior is changed so that the entered night sky color is the true color, this WILL be a difference. How do you propose the night sky color can be changed while providing 100% backwards compability? Currently, I don't see how that would be possible, unless you are thinking about adding some ugly parameters like `use_legacy_night_sky=true`.

**Comment by Wuzzy2** [comment]
Dumb question: Would it be too much to ask to just fix the weird night sky color? This behavior really feels like a bug.
What was the rationale to not use the true color but a much darkened color instead? It doesn't make sense.

**Comment by Jordach** [comment]
Ugly params in both conf and Lua API like that are just horrible, I'd rather spend the day taking screenshots of the night (as of current master), and then fix the night blending, and use those night colours generated by the old code, therefore, having the classic night sky and fixing the issues.

**Comment by paramat** [comment]
> Not a blocker, changing the night sky blending algorithm will change the existing night sky colours as defined for backwards compatibility.

> Would it be too much to ask to just fix the weird night sky color?

These are not going to happen before 5.2.0, they are not trivial changes.
Applying the defined colours at night is the last part of the new set_sky feature that did not make it into 5.2.0 in time, so it is an unfinished feature and not a bug, and we are in feature freeze. Remember that 5.3.0 is intended to folllow soon after.

> Wouldn't it suffice to mark the exact sky color as subject to change?
Marking the whole API as unstable and un-deprecating the old API doesn't look necessary to me.

I agree and that is fine for me. That is why i wrote "(specifically night colours)", i only meant document that part as unstable.
But do we still un-deprecate the old API? Maybe not.

I do not understand the negative emoticons in the first post, i am only proposing we warn modders of a future change. If the new API is unstable then it is unstable and we are obliged to warn of this, what else can we do? It is the only right thing to do.
Applying the actual colours to night seems desirable so surely this is what the users want?
If we do not warn of this and document the feature as stable then you will not get the upcoming feature, is that what the downvoters prefer?
Adding a warning to documentation does not stop anyone using the new features, so why the fuss?

**Comment by benrob0329** [comment]
I'm not going to put in three calls to set_sky in my game because the API changed twice, I'm just going to wait until it's actually stable enough to bother.

**Comment by Jordach** [comment]
I mean as *far* I understand the blending code (which to say is probably not at all), all that'd have to change for night colours is to move the day time colour blending into the night time blending if/else block.

**Comment by paramat** [comment]
Jordach, you seem unsure, so i do not think it is trivial and safe to do now. I do not want to risk causing bugs and delay release.
Besides, it is harmless enough a future API change to just do this as sfan5 proposed:
> mark the exact sky color as subject to change

Which is the simplest and safest option.
I disagree with adding compatibility code or some kind of new parameter like 'full night colour' which would unnecessarily create unused data in a packet.

So i will make a PR to add a warning to docs (but not un-deprecate the old call).

**Comment by paramat** [comment]
Another issue is the 'dawn sky', 'dawn horizon' colours, these may also change behaviour as they are probably darkened according to time just like the night colours are.
