### ISSUE TITLE
Add command revokeme <priv>

### ISSUE THREAD

**Issue by Panquesito7** [minetest/minetest#9576]
## Problem

When revoking privileges to yourself, it can take a little long to type the command to revoke a privilege.
I'd like to add a `revokeme` command to make it shorter and quicker to revoke privileges to yourself.

## Solutions

Create a new command (like `grantme`) that revokes an specified privilege to yourself.

## Alternatives

`revoke` is an alternative, however it is longer than `revokeme`.

**Comment by rubenwardy** [comment]
I support this. It always throws me

**Comment by paramat** [comment]
I support too.

**Comment by DeltaNedas** [comment]
i think commands accepting player names should take me, -, etc as the current player
this would make *me commands redundant
alternatively they could use the current player by default, setting it from the last, optional, argument e.g. /give default:dirt [coolusername]

**Comment by HybridDog** [comment]
> […] setting it from the last, optional, argument  e.g. /give default:dirt [coolusername]

This does not work if there is a player who is called 99 and someone wants to give him/herself 99 dirt nodes.
