### ISSUE TITLE
set_eye_offset doesn't offset the raycast origin properly

### ISSUE THREAD

**Issue by Lemente** [minetest/minetest#9589]
I think I found an inconsistancy with set_eye_offset.

It is supposed to offset the camera/player view. When I offset it forward (z axis), the camera is behaving like expected. It rotates according to the player's origin.
But the selection box is messed up. It does rotate, but it is using the wrong origin.

Result : the selection box isn't at the right place, instead it is offsetted in the global Z axis.

I believe it is an error in the engine, as I can't find a reason why it would behave like this.

I tried to illustrate the issue :
![e945f0af95b852e905477ffa58a7714a](https://user-images.githubusercontent.com/27686967/78404252-46e86600-75fe-11ea-9aa7-81666b268e76.png)

Here is the mod I am trying to make. 

[size.zip](https://github.com/minetest/minetest/files/4429883/size.zip)
Grant yourself "size", then do /size player x.
Look down and turn around.

if you look in the z direction, everything works fine, but when you start looking in the opposite direction, you'll notice that the selection box is always offsetted toward the global z axis.

![screenshot_20200403_230413](https://user-images.githubusercontent.com/27686967/78404821-7a77c000-75ff-11ea-9363-32d16621c22c.png)

**Comment by sfan5** [comment]
Extremely obvious when sitting in a cart: 
![grafik](https://user-images.githubusercontent.com/1042418/79160100-8a4e8b80-7dd9-11ea-9906-3f289e6d88ea.png)

**Comment by SmallJoker** [comment]
:negative_squared_cross_mark: Nov 30
:ballot_box_with_check: Okt 13 (47d07793)

The `v3f` eye offset likely never resulted in proper shooting lines, this time it's the eye offset that makes it instantly visible.

No idea which exact commit broke it, but see #9681 for a bugfix.
