### ISSUE TITLE
Add texture pack override support for items

### ISSUE THREAD

**Issue by Df458** [minetest/minetest#9595]
## Problem

Sometimes, mod authors design their textures in a way that is not conducive to texture pack support. This can happen for a variety of reasons, but in these cases texture pack makers need a way to replace the texture of *a specific item*, rather than simply replacing the source asset.

## Solutions

A solution for this already exists for nodes: `override.txt`
The functionality of this file should be expanded to support overriding item textures.

Since I need this feature for my texture pack, I'll be looking into the feasibility of this change and probably opening a PR for it in the near future.

## Alternatives

When such a situation arises, there are three possible alternatives and none of them are sufficient:

- Contact the mod author and convince them to change their mod
  - If the mod author chooses to ignore the artist or is no longer in the community, this is a non-option.
  - In some other cases (ie. runtime generated item definitions from dependent mods), this is physically impossible.
- Try to work around it through clever design
  - This is highly dependent on the circumstances, and often not possible
- Accept bad textures / skip the textures entirely
  - It goes without saying that this is not an acceptable solution

(Note: This may *appear* to be a duplicate of #4197, but it is not. That issue is specifically about the wield_image / inventory_image fields of **nodes**, not all items in general)

**Comment by rubenwardy** [comment]
This is functionally a duplicate of that issue because the resolution of either issue would result in both nodes and items having their wield_image/inventory_images being overridable

**Comment by Df458** [comment]
Since you did some work on that issue, I'll trust your judgement on that. I'll close this and leave a comment on the other issue in that case.
