### ISSUE TITLE
English language missing from language menu

### ISSUE THREAD

**Issue by IagoAndrade** [minetest/minetest#9599]
##### Minetest version

```
5.2.0-win64
```

##### OS / Hardware

Operating system: Windows 7
CPU: Intel Core i5 2300 2.8 GHz

GPU model:
OpenGL version:

##### Summary

When trying to change language to english, there is no "en" option in Settings->All Settings->Client and Server->Language
(OS language is pt-BR, so the menu options are these but in portuguese)
Tested in version 5.1.1, the "en" option is there as expected
##### Steps to reproduce

Open minetest, go to "Settings" tab, click "All Settings", click Client and Server, click "language", click the "Edit" button, look for "en" language

**Comment by An0n3m0us** [comment]
It's at the very top; but the text is not displayed:
![kép](https://user-images.githubusercontent.com/49789044/78513549-68835200-77a4-11ea-9726-24b1ca33f931.png)

**Comment by IagoAndrade** [comment]
In my system (which is in portuguese) if I select the first blank option, it defaults to the system language, portuguese. I think that is the case for any other OS language (is yours in english?).

**Comment by juozaspo** [comment]
On linux, gettext does not provide english as available language, you have to manually edit `minetest.conf` and add `language = en` if it's missing otherwise edit that line. When running cmake on the latest minetest master in my system (Ubuntu) it produces lines related to it as below:
```
-- GetText enabled; locales found: ar;be;ca;cs;da;de;dv;el;eo;es;et;eu;fil;fr;he;hu;id;it;ja;ja_KS;jbo;kk;kn;ko;ky;lo;lt;ms;my;nb;nl;nn;pl;pt;pt_BR;ro;ru;sl;sr_Cyrl;sv;sw;th;tr;uk;vi;zh_CN;zh_TW
...
-- Locale blacklist applied; Locales used: ar;ca;cs;da;de;dv;el;eo;es;et;eu;fil;fr;hu;id;it;ja;ja_KS;jbo;kk;kn;lo;lt;ms;my;nb;nl;nn;pl;pt;pt_BR;ro;ru;sl;sr_Cyrl;sv;sw;th;tr;uk;vi;zh_CN;zh_TW
```
