### ISSUE TITLE
get_sky_color returns unknown fields

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9605]
##### Minetest version
```
5.2.0
```

##### Summary
`player:get_sky_color()` returns a table including the fields `tint_type`, `sun_tint` and `moon_tint`.
However, those fields are unknown. They do not appear anywhere in `lua_api.txt`.

Instead, `lua_api.txt` mentions similar field names: `fog_sun_tint`, `fog_moon_tint` and `fog_tint_type`.

##### Steps to reproduce
* Get `luacmd`
* `/lua print(dump(me:get_sky_color()))`

**Comment by SmallJoker** [comment]
`fog_` needs to be removed according to comparisons:
https://github.com/minetest/minetest/blob/143a37e947d809ac68da56bac0f61cf8b5fd0d46/src/script/lua_api/l_object.cpp#L1789-L1803

https://github.com/minetest/minetest/blob/143a37e947d809ac68da56bac0f61cf8b5fd0d46/src/script/lua_api/l_object.cpp#L1920-L1925

**Comment by Wuzzy2** [comment]
Please consider adding this to the next milestone, otherwise this bug will creep into mods and mods start to depend on a bug.

**Comment by rubenwardy** [comment]
The get should match the set

**Comment by paramat** [comment]
> fog_ needs to be removed

'fog_' was added on my request in the review, for descriptive parameter names (the tint is for the fog, not the sun or moon), but adding this was forgotten in another part of the code.
So 'fog_' needs to be added to the 'get'.
