### ISSUE TITLE
[discuss] Come up with a convention for HUD element z_index

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9606]
This is a discussion issue.

In 5.2.0, `z_index` was added to HUD elements to determine the rendering order. As many different mods are manipulating the HUD, they will use `z_index`.

However, there is no convention whatsoever as to what numbers to use. I feel we should come up with *some* convention (even a simple one). Otherwise, the mods will just spread the `z_index`es all over the place, making it useless. Therefore, I suggest to discuss a convention, and when the discussion is complete, put it into `lua_api.txt` or at least the Dev Wiki as official recommendation.

My first rough ideas:

* -40: Graphical effects, such as vignette
* -30: Name tags, waypoints
* -20: Wieldhand
* -10: Things you wear on your face or that are blocking your view, such as a mask or a bloddy screen
* 0: Default `z_index`. For the builtin HUD elements and anything that can be considered to be part of the “true” HUD: Minimap, hotbar, builtin statbars, crosshair
* 10: Temporary text messages or notification icons
* 100: Full-screen effects such are full-black screen or a credits screen. Basically anything that must cover the full screen and replace the entire HUD

These numbers have intentionally have gaps so it's easy to put in new stuff in-between. It's also neccessary for complex HUDs that need multiple elements at once for the same thing.

Do you agree? Do you have your own ideas for a convention?

**Comment by rubenwardy** [comment]
Your list sounds good to me

**Comment by sfan5** [comment]
I think I'd multiply each of those by 10 just to be safe.

**Comment by Wuzzy2** [comment]
Yeah, whatever. Those numbers were just examples. I'm fine with increasing the gaps. By the way, what are the boundaries for `z_index`? We shouldn't make the gaps too big either …

I also made a mistake in my suggestion: I want to swap wieldhand with “Things you wear on your face”. Thing that you wear on your face should logically obstruct the view on your hand, not the other way around. ;-)

**Comment by rubenwardy** [comment]
Done

**Comment by Wuzzy2** [comment]
So, how is your opinion on my suggestion now? Do you have anything more to add or do you think it can be adopted?

**Comment by SmallJoker** [comment]
No objections from my side. Adding guidelines/conventions early is always a better idea than documenting it after years (to a point where nobody cares). If not now, it won't make sense to document it.

**Comment by Wuzzy2** [comment]
#9701
