### ISSUE TITLE
Image of image button disappears when sending formspec with `[lowpart` image

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9613]
##### Minetest version
```
5.2.0
```

##### Summary
If you have a formspec with an image button in it, then send an updated version of the formspec with another image that has the `lowpart` modifier in it, the image in the image button will disappear until you move the mouse.

This is a regression. This bug happens in 5.2.0, but not in 5.1.1.

##### Relevance
This breaks the formspec of MCL2 furnaces, which include `lowpart[` image for the flame and arrow. The image button is for the crafting guide.

##### Steps to reproduce
In `minimal` or `devtest`, install and use this test mod:

```
local set_formspec = function(meta)
	local r = math.random(1,100)
	local img = "default_dirt.png^[lowpart:"..r..":default_stone.png"
	meta:set_string("formspec", "size[5,5]image[3,3;2,2;"..img.."]image_button[4,0;1,1;air.png;craftguide;]")
end

minetest.register_node("test_button_formspec:node", {
	description = "Image Button Formspec Test Node",
	tiles = { "default_dirt.png^[lowpart:50:default_stone.png" },
	groups = { dig_immediate = 3 },
	on_construct = function(pos)
		local meta = minetest.get_meta(pos)
		set_formspec(meta)
		local timer = minetest.get_node_timer(pos)
		timer:start(1)
	end,
	on_timer = function(pos, elapsed)
		local meta = minetest.get_meta(pos)
		set_formspec(meta)
		local timer = minetest.get_node_timer(pos)
		timer:start(1)
	end,
})
```
This is a test node with a node formspec in it. It has a formspec which includes a `lowpart` image and an image button.
The formspec is updated with a random `lowpart` percentage (1-100) every second.

EXPECTED: The image of the image button does not disappear, ever.
ACTUAL: Every time the random percentage changes, the image of the image button disappears, until you move the mouse.

**Comment by An0n3m0us** [comment]
Confirmed; 5.3.0-dev with latest Minimal version.

When ANY key or mouse button (or mouse movement) is input; the image reappears

If one holds the key/mouse button, the image will disappear UNTIL one lets go of it.

So the image only appears when a key/button is clicked or let go, or if the mouse is moved. So basically, on user input.

Demonstrated here:
https://my.pcloud.com/publink/show?code=XZfyPgkZcbUX3h5Fn980jLWVQLfYwjhgwNGX

**Comment by Df458** [comment]
Can you re-test with the latest 5.3.0-dev? I may have inadvertently fixed this in #9378.

**Comment by An0n3m0us** [comment]
I tried on the latest dev and the issue doesn't occur any more.

**Comment by Wuzzy2** [comment]
Thanks for testing. :)
