### ISSUE TITLE
Image in 9-sliced image button bleeds over to the edge

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9615]
##### Minetest version
```
5.2.0
```

##### Summary
The image of 9-sliced image buttons is rendered on the border as well. This looks ugly:

![HeXG96l9ND](https://user-images.githubusercontent.com/3686677/78942614-f36c9100-7ab1-11ea-873f-54889fb8b65d.png)

##### Steps to reproduce
Download MineClone 2, turn off Creative Mode and open the inventory screen.

Definition of image button style:
```
style_type[image_button;border=false;bgimg=mcl_inventory_button9.png;bgimg_pressed=mcl_inventory_button9_pressed.png;bgimg_middle=2,2]
```

##### Suggestion
Shrink the image automatically into the middle “slice” of the 9-slice button.

**Comment by Df458** [comment]
I have some thoughts on how to fix this nicely, but I'm avoiding further button PRs until #9378 is merged (because of the very high chance of conflicts).

Once that's in, fixing this issue will be my next priority.
