### ISSUE TITLE
Windows 10: minetest.exe only starts from commandline

### ISSUE THREAD

**Issue by TEbinger** [minetest/minetest#9620]
I downloaded minetest from minetest.net (64 Bit). Using Windows 10 I the program won't start by double clicking minetest.exe in the bin folder. It only starts from command line. Had no problems with the previous version.

**Comment by MoNTE48** [comment]
Worked for me. Windows 10 1909 x64

**Comment by rubenwardy** [comment]
Please provide the last 20 lines of debug.txt. You should delete it first, to make sure that it is created and the correct file

**Comment by TEbinger** [comment]
No debug.txt is created. I tried to run it as administrator, nothing happened. Microsoft Windows 10 Pro, Version 10.0.17763  Build 177763. x64, Intel Core i5.

**Comment by SmallJoker** [comment]
Since which release does this happen? 5.2.0, 5.1.1, or even 0.4.17.1?

**Comment by TEbinger** [comment]
Since 5.2.0

**Comment by MoNTE48** [comment]
@TEbinger, you can try with 32-bit build?
https://github.com/minetest/minetest/releases/download/5.2.0/minetest-5.2.0-win32.zip

**Comment by TEbinger** [comment]
Also 32-bit doesn't work.

**Comment by SmallJoker** [comment]
@TEbinger How about older 5.2.0-dev builds? Which is the most recent build that does not work?
sfan5's builds: https://minetest.kitsunemimi.pw/builds/
or from the pipeline: https://gitlab.com/minetest/minetest/pipelines/?page=4&scope=all (right button ->win64), also I don't know how well those work.

**Comment by TEbinger** [comment]
sfan5's builds work for me, Latest https://minetest.kitsunemimi.pw/builds/win64/minetest-5.3.0-840b17c-win64.7z and the previous one https://minetest.kitsunemimi.pw/builds/win64/minetest-5.1.0-38b94f2-win64.7z Didn't try from pipeline.

**Comment by sfan5** [comment]
That's interesting because the release builds are done on the same machine and in the same environment as the release build.

**Comment by DanielTheGreatinc** [comment]
Perhaps the permissions for executing the file are not allowing you to execute it. [How to change permissions of file](https://answers.microsoft.com/en-us/windows/forum/windows_10-security/how-to-change-folder-and-file-permissions-in/783e7040-d18f-4c04-a0f3-830b4841bb68).

**Comment by TEbinger** [comment]
It is working again for me now. Probably it was a security thing on my laptop
