### ISSUE TITLE
Text cursor used when hovering non selectable StaticText

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9634]
##### Minetest version
```
5.2.0
```

##### Summary
If you hover a read-only field (formspec element `field`) with the mouse, it turns into the text cursor, but it should stay normal as you cannot select the text.

##### Steps to reproduce
1. Hover a read-only field with the mouse.

**Comment by Wuzzy2** [comment]
Fastest way to reproduce it:
Press Esc and hover the "Game paused" text because that's a read-only field internally (IIRC).

**Comment by An0n3m0us** [comment]
Is this it?:
![output](https://user-images.githubusercontent.com/49789044/79027313-a1943b80-7b83-11ea-9ee2-5bedc32dda77.png)

If so; confirmed in Minetest 5.3.0-dev

**Comment by Desour** [comment]
@An0n3m0us wrong text, try in singleplayer.

**Comment by An0n3m0us** [comment]
Works similarly, except the "Game Paused" text isn't selectable:
https://my.pcloud.com/publink/show?code=XZvdVPkZJ7O5JEFqRC0yRj3pLPqEAJwU3pXy

**Comment by SmallJoker** [comment]
I wonder whether `textarea[]` titles and `field[]` are affected too. If they're not, the labels could be skipped by adding another enum entry and checking for the labels here:

https://github.com/minetest/minetest/blob/aa3cf400e2ca4096517e926dbae5b6337b2f1876/src/gui/guiFormSpecMenu.cpp#L3346-L3348

**Comment by Wuzzy2** [comment]
@SmallJoker: This issue IS about `field[]` already! See “Game paused” in Esc menu.

`textarea` is fine. The cursor changes to the text cursor for those, too, but in this case, it's correct because you can actually select and copy the text (unlike with `field`).

**Comment by Desour** [comment]
Related code (pause menu):
https://github.com/minetest/minetest/blob/1292bdbbcec45613c95aff9f2ea88aa49af25011/src/client/game.cpp#L4148
The Game paused text seems to be the label of a field. Is it possible that the field is below the Continue button (probably not, the button was defined before)?
Or is this some kind of [undocumented](https://github.com/minetest/minetest/blob/fbf74dc52456b13b0dbd7bb9d3206e5828254910/doc/lua_api.txt#L2214-L2227) read-only syntax?
