### ISSUE TITLE
Entity use_texture_alpha broken after 6958071 (Basic model shading)

### ISSUE THREAD

**Issue by GreenXenith** [minetest/minetest#9637]
478e753:
![image](https://user-images.githubusercontent.com/24834740/79028728-15175800-7b46-11ea-9353-3cbb68b577b3.png)

6958071 (#9374):
![image](https://user-images.githubusercontent.com/24834740/79028676-e0a39c00-7b45-11ea-9e2a-3a78231795fe.png)

**Comment by sfan5** [comment]
@dcbrwn

**Comment by GreenXenith** [comment]
Looking further into the issue, I have found [the responsible code](https://github.com/minetest/minetest/blob/5.2.0/src/client/content_cao.cpp#L583-L593). Apparently, if shaders are enabled, transparency is thrown out the [opaque] window. This is not acceptable, in my opinion.

**Comment by sfan5** [comment]
Not really, the shader probably just needs to be changed to handle transparency.

**Comment by GreenXenith** [comment]
Ah, right, you are correct. I suppose not having shaders shouldn't mean losing translucency, so that code makes sense.

**Comment by Df458** [comment]
Unfortunately, the shader is already handling transparency from the looks of it. I haven't dug too deeply, but I'm guessing it's an issue with the material not supporting alpha when it should.

The code above is not *exactly* responsible, per se... but it's probably indicative of the issue.

**Comment by Df458** [comment]
Ok, this should be an easy fix. I can submit a PR tomorrow morning if you'd like.

The code above is responsible, though not for the alleged reason above. `TILE_MATERIAL_BASIC` results in a material based on `irr::video::EMT_TRANSPARENT_ALPHA_CHANNEL_REF` which supports 'binary' (fully transparent or opaque) alpha, so instead we should be using `TILE_MATERIAL_ALPHA` when alpha is enabled to base our material on `irr:video::EMT_TRANSPARENT_ALPHA_CHANNEL`.
