### ISSUE TITLE
Translate currently "static" mesh formats to animated format

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9646]
If we built in a function into the engine that converts obj ,3ds, mesh, dae, and xml into .x or b3d then we could have an easy way to export blender models into the current limited animated mesh subset

receive -> interpret -> reassemble -> constant

Would make the current version of blender exporting extremely easy.

I'm sure there is a way to intercept the data of a mesh before Minetest's engine feeds the data into irrlicht.

But I've already accepted that this definitely will never happen.

**Comment by Df458** [comment]
...What would be the point, though? If the input mesh is static, the output mesh will not have animations regardless of format.

Instead, I think we should just investigate supporting more modern animated mesh formats;
