### ISSUE TITLE
pointing offset

### ISSUE THREAD

**Issue by RonnyBarthmann** [minetest/minetest#9648]
Minetest Version 5.x ( all; including 5.2.0 )
Operating system: Linux/GNU 4.9.6-64 / Debian 9.0 / Knoppix 8.0
CPU: AMD Athlon(tm) II X4 630 Processor
GPU model: Advanced Micro Devices, Inc. [AMD/ATI] Barts PRO [Radeon HD 6850]

##### Summary
Pointing is not accurate between two Blocks

##### Steps to reproduce
- Play some time ( turn often around )
- Try to slide slow over two Blocks ... if you Mouse cross the line between the two blocks sehen sie wie das highlighting is not correct
- Therefore, you don't place the blocks where you actually want them
- This is VERY stressful, especially with small edges (e.g. xpanes)

**Comment by RonnyBarthmann** [comment]
after extreme turning and struggling for 10 seconds:

Pointing in the Air:
![Bildschirmfoto vom 2020-04-12 13-53-39](https://user-images.githubusercontent.com/32592152/79068242-c8f32180-7cc5-11ea-9574-5e7c1070ef39.png)
Pointing the Block left behind:
![Bildschirmfoto vom 2020-04-12 13-54-48](https://user-images.githubusercontent.com/32592152/79068247-cd1f3f00-7cc5-11ea-9433-a643306bc811.png)
Pointing the fence above:
![Bildschirmfoto vom 2020-04-12 13-55-17](https://user-images.githubusercontent.com/32592152/79068251-d14b5c80-7cc5-11ea-8140-495f914f6b41.png)
Pointing the fence in front of ( to the left ):
![Bildschirmfoto vom 2020-04-12 13-55-47](https://user-images.githubusercontent.com/32592152/79068255-d6101080-7cc5-11ea-9eb1-18cd62a15d00.png)
Feil to pointing a xpane:
![Bildschirmfoto vom 2020-04-12 13-57-18](https://user-images.githubusercontent.com/32592152/79068259-da3c2e00-7cc5-11ea-9328-e850d56fc6c8.png)

**Comment by RonnyBarthmann** [comment]
this also happend often live in my letsplays
is therefore a very old problem (estimated since at least 5.1.0, but could also have been since 5.0.1)

**Comment by SmallJoker** [comment]
#9589
