### ISSUE TITLE
Add 9-sliced image[]

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9649]
We have `button9[]` and `background9[]`, so the logical extension of this is to add `image9[]` (and maybe `animated_image9[]`).

`image9` is like `image[]`, except that is uses 9-sliced image, just like `button9` and `background9`.

**Comment by Df458** [comment]
Not supportive or opposed, but how would this differ from `background9` in functionality?

**Comment by rubenwardy** [comment]
backgrounds must be behind all elements. images are IGUIElements that can appear anywhere

**Comment by Df458** [comment]
Ok, that sounds like a pretty reasonable request then.

**Comment by v-rob** [comment]
I'm actually already working on this, plus some other image functionality, like tiling.  It will extend the existing `image`, not add a new `image9` or such.
