### ISSUE TITLE
Node digging particles only spawn on top of node

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9652]
Node digging particles only spawn on top of node but the collision detection seems to work a lot better

**Comment by Wuzzy2** [comment]
Confirmed. Issue in 0ac999ded725f8efcd26db284161683e37efeecf (5.3.0-dev), but not 5.2.0, so it must have been introduced very recently.

It looks very odd when the node is mined, as all the particles will fall down at once. In 5.2.0, it looked much better.


How to reproduce:
Disable Creative Mode, dig dirt in MTG with your hand.

**Comment by sfan5** [comment]
When you noclip inside the node you can see that particles are spawned inside but pushed upwards.
Reverting 3ad5388c6d3894e2f4aa7158cc2b62b626f0f967 fixes this, so #9343 is the cause.

@TheTermos any idea about the preferred way to fix this?

**Comment by TheTermos** [comment]
Looking into this.

**Comment by TheTermos** [comment]
Particles are spawned inside a node, so they are in fact in collision.
I'm working on a quick and dirty solution.

Slow and proper solution would be for particles to be emitted outside a node, in the middle of the dug face.

**Comment by TheTermos** [comment]
The quickest and the dirtiest: change particles to non physical.

Little eye candy is lost, because particles will not collide with the ground, but should be ok as a temporary solution.

client/particles.cpp line 654:
`true,`
becomes
`false,`
that's all

**Comment by oilboi** [comment]
> The quickest and the dirtiest: change particles to non physical.
> 
> Little eye candy is lost, because particles will not collide with the ground, but should be ok as a temporary solution.
> 
> client/particles.cpp line 654:
> `true,`
> becomes
> `false,`
> that's all

Is there a simple way to find nodes that are nodeboxes, ignore, or air then spawn the particles near there with a velocity outwards of the center of the node?

**Comment by TheTermos** [comment]
There is a simple way of finding exactly the spot just outside the particular face being dug, I'd go with that first.

**Comment by KaylebJay** [comment]
I actually like the new particles look... I had no idea it was a 'bug' :D

**Comment by KaylebJay** [comment]
![screenshot_20200423_071844](https://user-images.githubusercontent.com/44441970/80106391-07df6d80-8537-11ea-8786-3f55a65266b6.png)
The particles do look nicer but I can see the effect after looking closer. Its definitely a bug.

**Comment by TheTermos** [comment]
Soon there's going to be a followup PR for #9343 due to some new issues I found in 5.3. 
Instead of changing how particles work I prefer to resolve it there, as there may be more similar issues we don't know of yet.

**Comment by Wuzzy2** [comment]
I noticed something interestind in DevTest: When you place down leaves and dig them, you notice something guring the digging:Particles spawn roughly in the center of the node, then travel upwards until they leave the node.

**Comment by Wuzzy2** [comment]
Fix confirmed.
