### ISSUE TITLE
If a player is fastmoving or running they can get stuck in the side of a node

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9653]
If a player is fastmoving or running they can get stuck in the side of a node, if you stop running or fastmoving when the player's collision detection is inside of the side of a node they seem to get stuck there. It will act like a node is next to them if they keep facing towards the node their collision is inside of and not allow them to smoothly pass into the next collisionbox. (this happens on walls)

**Comment by KaylebJay** [comment]
I've had this happen too.

**Comment by SmallJoker** [comment]
#5330
