### ISSUE TITLE
Bug with waving water

### ISSUE THREAD

**Issue by TNZ9** [minetest/minetest#9654]
The water blocks supposed to be hidden by a block at their top when there are no waves are still not displayed when they are made visible by the waves option
![Capture d’écran de 2020-04-13 12-20-46](https://user-images.githubusercontent.com/61658516/79113476-4a5bba00-7d81-11ea-83c5-65cabfa12c49.png)

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/issues?q=is%3Aissue+is%3Aopen+water+waving

#3075
