### ISSUE TITLE
Player not rendered / invisible / glitching

### ISSUE THREAD

**Issue by norpol** [minetest/minetest#9655]
##### Minetest version

```
Minetest 5.1.1 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware

Operating system: archlinux, wayland/swaywm
CPU: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz

GPU model: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL version:

##### Summary
Players (own and others) are missing textures / not rendered / invisible / glitching. I can guess where my own player is only when I'm moving around. Resetting settings or removing cache doesn't fix the issue.
![screenshot_20200413_155119](https://user-images.githubusercontent.com/2230917/79126478-4a1ee700-7da0-11ea-905a-1e07d9268e8e.png)
![screenshot_20200413_155121](https://user-images.githubusercontent.com/2230917/79126481-4b501400-7da0-11ea-8a3e-8ec9f7498091.png)

##### Steps to reproduce
In any view where player is visible.

**Comment by SmallJoker** [comment]
Please check whether this still happens in 5.2.0 or 5.3.0-dev.
Is it possible to reproduce this bug using only minetest_game, without additional mods? Which mod causes this?

**Comment by norpol** [comment]
High thank you for your immediate response, it happens also with minetest_game only as well.

**Comment by norpol** [comment]
```
Minetest 5.3.0-dev-27d611fe5-dirty (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

doesn't show this issue anymore, appears to be a bug in the current [archlinux package version then](https://www.archlinux.org/packages/community/x86_64/minetest/) then. FYI @antonio-rojas or @lordheavy
