### ISSUE TITLE
Regression: `use_texture_alpha` not working on shaded entities

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9657]
##### Minetest version

```
5.2.0
```

##### Summary

Rendering entities with the new shaders enabled ignores texture alpha, even if `use_texture_alpha = true` is set.

Shaders enabled:
![Screenshot](https://user-images.githubusercontent.com/34514239/79131447-e947dc80-7da8-11ea-8f49-ebab3e7d6f4a.png)

Shaders disabled:
![Screenshot](https://user-images.githubusercontent.com/34514239/79131452-ecdb6380-7da8-11ea-86f3-751f96ad4fc1.png)

##### Steps to reproduce

Use any entity with `use_texture_alpha = true`

**Comment by rubenwardy** [comment]
Fixed by https://github.com/minetest/minetest/commit/fbf74dc52456b13b0dbd7bb9d3206e5828254910
