### ISSUE TITLE
Add Separate chat_font_size Setting To Improve In Game Accessibly

### ISSUE THREAD

**Issue by FriendlyGamer** [minetest/minetest#9660]
## Problem
I requires a separate chat size to the UI's settings since chat still feels/looks small to me even on font size 30 and 28 for failback. 

## Solutions

Separate optional chat font size setting to be able to set custom font size JUST for chat. To improve in game accessibly in this regard.  

## Alternatives

No real alternatives since beyond ~30 font size UI suffers greatly on my setup.

**Comment by Shigetorum** [comment]
Im sure a CSM can do this for you without having to edit the core. Search for a chat customization CSM.
