### ISSUE TITLE
proxy configuration ?

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#9664]
It would be nice to be able to define a proxy server for internet access in the settings panel. This would be useful for connecting to a game server.

**Comment by BuckarooBanzay** [comment]
> It would be nice to be able to define a proxy server for internet access in the settings panel. This would be useful for connecting to a game server.

The main game traffic is exchanged as UDP, are there even proxies that support that?

**Comment by sfan5** [comment]
This is a duplicate of #7740

**Comment by track044** [comment]
https://github.com/minetest/minetest/issues/7740#issuecomment-765864399

**Comment by track044** [comment]
https://github.com/minetest/minetest/issues/7740#issuecomment-765868328
Try this.
