### ISSUE TITLE
Minetest client turns off.

### ISSUE THREAD

**Issue by CandyFiend** [minetest/minetest#9666]
##### Minetest version

```
5.2.0 (from https://www.minetest.net/)
```

##### OS / Hardware

Operating system: Windows 10 1903 18362.720
CPU: Intel Core i7  4710MQ

GPU model: NVIDIA GeForce 940M
OpenGL version: 4.5 (in specifications of GPU)

##### Summary

The game turns off, it doesn’t matter whether I play on the server or in my world, what game I play (minetest or mineclone 2), which keys are pressed, how much I jerk the mouse, etc. I turn on the minetest client, start playing and after a while the client just shuts down. I tried to find at least something in the logs using DIFFERENT modes, but I did not find anything. I tried to find information about this problem, but also did not find anything. Please, if this problem is known, give a link or tell me how to fix it (thanks). It’s hard for me to search in English, this is not my native language. Or write what I need to do to gather more information about the problem. I will attach a log. I just played until the game closed and repeated this for each logging mode.
[debug.txt](https://github.com/minetest/minetest/files/4475286/debug.txt)

##### Steps to reproduce

Just play

**Comment by CandyFiend** [comment]
I tried to record video using the xbox game bar, but the recording turned off as soon as the game turned off. If you need a recording, I can do it, but I will have to install some kind of recording program. But if necessary, I will do it.

**Comment by CandyFiend** [comment]
I apologize for not immediately guessing to restart the laptop. Now the problem is not repeated, but if it happens again, I will write.

**Comment by CandyFiend** [comment]
For some time I learned to draw models for entities and did not play. Today I tried to play and this problem appeared again. How can I collect information about the possible reasons for closing the game? I installed and uninstalled Mineclone 2, but it didn’t change anything.

**Comment by SmallJoker** [comment]
Please start Minetest manually from a Console window. It might show up an "Access Violation" error which is not logged in debug.txt.
Since which Minetest version does this happen?

**Comment by CandyFiend** [comment]
I will try this. The version is indicated in 1 post. I took the client from the official page last week.

**Comment by CandyFiend** [comment]
I inattentively read the question. I can’t say with which version this is happening, because recently started trying to do something with this engine.

**Comment by CandyFiend** [comment]
I'm definitely not sure, but if you run as administrator, then there seems to be no problem.

**Comment by CandyFiend** [comment]
16Gb, 6Gb Free. After starting as administrator, the game never turned off.

**Comment by SmallJoker** [comment]
Please don't run MInetest as administrator. Move the Minetest folder to a place where you have read/write access (Desktop, Documents).

Problem is "solved".
