### ISSUE TITLE
Converting Postgres to SQLite world results in blank world

### ISSUE THREAD

**Issue by archfan7411** [minetest/minetest#9670]
##### Minetest version
```
5.2.0
```

##### OS / Hardware
Operating system: Arch Linux
CPU: Intel i5 @ 3.7GHz x4

##### Summary
Upon attempting to convert a postgres world to SQLite using `--migrate`, a blank SQLite world is created, following the same seed and around 12KB in size. This is unfortunate because SQLite is the format of choice for transferring maps between server owners and not all of them want to set up postgres. Right now, once you transfer a map to postgres there's essentially no going back.
I had this problem originally some time ago but only opened this issue once it was confirmed by another server owner.

##### Steps to reproduce
Convert a world stored in postgres to SQLite using the `--migrate` option, and then attempt to use the SQLite world.

**Comment by sfan5** [comment]
I can spot the bug from here, the `row` value is unused inside the loop:
https://github.com/minetest/minetest/blob/7e21b3cd4883eb8b9eb7e9ca49e50f6f0c7bc0d6/src/database/database-postgresql.cpp#L302-L305

**Comment by SmallJoker** [comment]
7c43cf47c37b02
