### ISSUE TITLE
parse_json error LargestInt out of Int range

### ISSUE THREAD

**Issue by Elinvention** [minetest/minetest#9672]
##### Minetest version

```
5.1.1
```

##### OS / Hardware

Operating system: Manjaro
CPU: AMD FX-8320

##### Summary
I'm using minetest.parse_json to parse a JSON received from Telegram API. At one point someone forwarded a message from a channel. A channel has a big negative id like -1001389828906. Minetest crashed with this stack trace:

```
ERROR[Main]: ServerError: AsyncErr: environment_Step: Runtime error from mod 'telegram' in callback environment_Step(): LargestInt out of Int range
ERROR[Main]: stack traceback:
ERROR[Main]:         [C]: in function 'parse_json'
ERROR[Main]:         /usr/share/minetest/mods/minetest_telegram_bridge/init.lua:40: in function 'callback'
ERROR[Main]:         /usr/share/minetest/builtin/game/misc.lua:253: in function 'func'
ERROR[Main]:         /usr/share/minetest/builtin/common/after.lua:20: in function </usr/share/minetest/builtin/common/after.lua:5>
ERROR[Main]:         /usr/share/minetest/builtin/game/register.lua:429: in function </usr/share/minetest/builtin/game/register.lua:413>
```

It looks like minetest is using 32 bit integers to parse the json. log2(-1001389828906) = 40, so a 64 bit integer could solve this issue. As far as I know lua doesn't distinguish between integers and floats and uses 64 bit double even for integers and shouldn't have problems representing those numbers.

##### Steps to reproduce
```
minetest.parse_json('{"id": -1001389828906}')
```

**Comment by sfan5** [comment]
> As far as I know lua doesn't distinguish between integers and floats and uses 64 bit double even for integers and shouldn't have problems representing those numbers.

Note that 64-bit doubles can also not represent the full range of 64-bit integers. Not a problem in <i>this</i> case, though.
