### ISSUE TITLE
Support for more modern mesh format(s)  (.gltf)

### ISSUE THREAD

**Issue by LunaSquee** [minetest/minetest#9673]
## Problem

I am frustrated with the options for mesh import formats irrlicht provides, mainly the animated ones (.b3d, .x, .ms3d, .md3, .md2). 
Most, if not all, of these formats are very outdated and probably very impractical and have little to no support in modern 3D software like Blender. 

## Solutions

I propose we figure out what modern format we could implement and which format would make the most sense with the least overhead. I personally recommend glTF, as I believe it is the 3D content format that will outdo them all in the future. Another option might be COLLADA. Open for suggestions/questions/criticism, hence why I'm calling this a discussion. I would be willing to put a bounty on this issue if we come to an agreement.

**Comment by LunaSquee** [comment]
I realise that this is more of an irrlicht issue than a minetest one but I it does look like they are not really doing anything anymore to me, just a simple mesh+bone(animation) loader shouldn't be too much to ask for

**Comment by rubenwardy** [comment]
for reference, here's what Blender3d supports without plugins:

![image](https://user-images.githubusercontent.com/2122943/79282189-76c02500-7eac-11ea-8ea6-26eff0ef2d47.png)

**Comment by Df458** [comment]
Looking at the current code and Irrlicht docs, this seems fairly straightforward: Mesh loading is done via the scenemanager, which exposes [this function](http://irrlicht.sourceforge.net/docu/classirr_1_1scene_1_1_i_scene_manager.html#a808972cc001db86c0576c38b3b3fbbf7) for use to register custom loaders.

**Comment by appgurueu** [comment]
Irrlicht supports Collada. We should start supporting Collada as well.

**Comment by LunaSquee** [comment]
> Irrlicht supports Collada. We should start supporting Collada as well.

Only for static models. I still say we implement a glTF loader.

**Comment by LunaSquee** [comment]
https://github.com/KhronosGroup/glTF/blob/master/README.md

**Comment by appgurueu** [comment]
Collada supports animations.

**Comment by LunaSquee** [comment]
> Collada supports animations. glTF looks promising as well, but is not yet supported by Irrlicht.

What I'm saying is that the loader irrlicht has for collada only supports static meshes.

**Comment by paramat** [comment]
:+1:

**Comment by zionserver** [comment]
I personally believe that the best format is glTF in conjunction with Blockbench, because it is mainly people friendly. And if glTF is not supported yet, I propose to create a plugin so that blockbench can export in .b3d or .blend format, besides this software is free Open Source, and is available both online and offline.

**Comment by LifeCanvasDev** [comment]
Has anyone looked at Nabla (https://github.com/Devsh-Graphics-Programming/Nabla) a fork of Irrlicht which attempts to modernise the engine with current tech and features, including Vulkan support.. and the devs mentioned somewhere that glTF is also on their roadmap.

**Comment by appgurueu** [comment]
> Has anyone looked at Nabla (https://github.com/Devsh-Graphics-Programming/Nabla) a fork of Irrlicht which attempts to modernise the engine with current tech and features, including Vulkan support.. and the devs mentioned somewhere that glTF is also on their roadmap.

glTF being on the roadmap doesn't help, it has to be usable.

**Comment by LifeCanvasDev** [comment]
> > Has anyone looked at Nabla (https://github.com/Devsh-Graphics-Programming/Nabla) a fork of Irrlicht which attempts to modernise the engine with current tech and features, including Vulkan support.. and the devs mentioned somewhere that glTF is also on their roadmap.
> 
> glTF being on the roadmap doesn't help, it has to be usable.

That post about them planning to implement glTF was nearly 2 years ago (see here https://irrlicht.sourceforge.io/forum/viewtopic.php?p=305594&hilit=gltf#p305594 ), so who knows, it might already be in the current version of Nabla (I didn't look at much of the repository or code on Github yet).

**Comment by KaylebJay** [comment]
Any update on this? Either Collada or glTF support would be greatly useful - b3d is already a dinosaur and it's becoming harder and harder to use! :-(

**Comment by rubenwardy** [comment]
Josiah is currently working on this. I believe he has meshes appearing and is now working on animations

**Comment by RepComm** [comment]
> Josiah is currently working on this. I believe he has meshes appearing and is now working on animations

Is there a link to this work? I am interested in helping with this feature.

**Comment by rubenwardy** [comment]
> Is there a link to this work? I am interested in helping with this feature.

Their branch is here: https://github.com/JosiahWI/irrlicht/tree/feat/gltf-loader
They're mostly organising on the Discord server (this is an unofficial thing, we don't do official engine dev on closed platforms)

**Comment by rubenwardy** [comment]
PR has been created for glTF support for static meshes, animations to follow later: https://github.com/minetest/irrlicht/pull/200

**Comment by numberZero** [comment]
> for reference, here's what Blender supports without plugins:

Here they are:
* [COLLADA](https://en.wikipedia.org/wiki/COLLADA) (Khronos standard, old)
* [Alembic](https://en.wikipedia.org/wiki/Alembic_(computer_graphics)) (“open” but good luck finding the spec)
* [Stanford](https://en.wikipedia.org/wiki/PLY_(file_format)) (poorly defined, old)
* [STL](https://en.wikipedia.org/wiki/STL_(file_format)) (not really for graphics)
* [FBX](https://en.wikipedia.org/wiki/FBX) (proprietary)
* [glTF](https://en.wikipedia.org/wiki/GlTF) (Khronos standard, alive)
* [Wavefront](https://en.wikipedia.org/wiki/Wavefront_.obj_file) (inflexible, old)
* [X3D](https://en.wikipedia.org/wiki/X3D) (ISO standard, still alive)

So, ugh... from this cursory review, glTF and X3D are indeed the least insane options.

**Comment by Desour** [comment]
How easy is it actually to modify a mesh stored in gltf? Last time I tried it, it triangulated all faces and split up the vertices. If it's not possible to disable this, we should also consider supporting e.g. collada.

**Comment by numberZero** [comment]
> How easy is it actually to modify a mesh stored in gltf?

Why would you want that in Minetest?

**Comment by appgurueu** [comment]
What I hated about glTF when writing my B3D to glTF converter is that you need a "neutral bone" to attach vertices not affected by the animation to.

**Comment by Desour** [comment]
> > How easy is it actually to modify a mesh stored in gltf?
> 
> Why would you want that in Minetest?

I don't want minetest to modify a gltf file, but I want to be able, as a modder, to change my mesh after storing it. And it would be annoying to have to store the mesh in the mod repo two times in separate formats.

**Comment by appgurueu** [comment]
It is sometimes useful to be able to programmatically generate models. For instance, in my Go mod, I generate a B3D model of the board with the 2n² pieces (of both colors) hidden inside it, such that they can be moved to the surface using bones. This seems to be similarly easy with glTF though (since you can restrict yourself to a subset when using it), and even if it wasn't, I still have my B3D to glTF converter so I'm fine ;)

**Comment by rubenwardy** [comment]
> I don't want minetest to modify a gltf file, but I want to be able, as a modder, to change my mesh after storing it. And it would be annoying to have to store the mesh in the mod repo two times in separate formats.

This is the recommended approach already - to store both source files (ie: blender) and compiled files (ie: gltf). Having the two different formats will be more reliable than a buggy importer, and allows you to keep certain tool-specific data in the source file but not the compiled file

**Comment by sfan5** [comment]
I suggest we do not attempt to ever support any formats that use XML again.

**Comment by Nanowolf4** [comment]
So much time has passed, and nothing has been done in this direction. Neither Collada nor glTF, only the ancient b3d format like a mammoth.

**Comment by rubenwardy** [comment]
That's not correct, there's work here: https://github.com/minetest/irrlicht/pull/200

**Comment by Pantyhose-X** [comment]
My suggested modern format [.m3d](https://gitlab.com/bztsrc/model3d)

> ### .m3d Features
> 
> * the format is freely usable, MIT licensed (unlike .PBX, .MAX or .C4D)
> * also has an [ASCII](https://gitlab.com/bztsrc/model3d/blob/master/docs/a3d_format.md) representation for exchange and easy debugging (unlike .BLEND or .B3D, similar to .OBJ but with skeletal animation support)
> * stores exactly one model with all its aspects, but nothing else (unlike .FBX, .X3D, .BLEND; just like .PLY)
> * has the biggest information density of all the formats (a cube can be stored in as little as 119 bytes)
> * can store huge number of vertices in magnitude of billions (unlike .3DS)
> * can store color maps as well as texture maps and materials
> * can store inlined textures (ideal for model distribution)
> * can store precise normal vectors, not just smoothing groups (unlike .3DS)
> * can store [voxel](https://gitlab.com/bztsrc/model3d/blob/master/docs/voxel_format.md) images, polygon mesh, procedural surfaces and procedural textures\*
> * can store parameterized mathematical surfaces, like [NURBS](https://gitlab.com/bztsrc/model3d/blob/master/docs/shape.md) (and other [CAD](https://gitlab.com/bztsrc/model3d/blob/master/docs/CAD.md) information)
> * can store skeleton based animations (unlike .MD3, which uses vertex morph only, or .MD5 which has separate files for anims)
> * can store actions, several named animation frames within the same file
> * can store model with absolute scaling factor and face thickness for 3D printing (is there any format that can do these?)
> * utilizes engine agnostic data structure, focuses on storing what's relevant for the model representation, not for the engines
> * supports material libraries in separate files if needed (using the same format)
> * expandable in nature, additional information can be easily added if needed without breaking compatibility with other applications
> * flexible data types (similar to .PLY, but much simpler, coordinate precision from 8 bits to 64 bits (*int8_t* to *double*))
> * compact file size, damn easy to interpret without third-party libraries\*\* (\~80 SLoC see below, unlike .FBX, .X3D, .glTF or .X)
> * the SDK follows the K.I.S.S. principle, MIT licensed just as the format itself, easy to integrate into any project
> 
> (\* - you provide a script interpreter callback for the SDK, so you can [use any scripting language](https://gitlab.com/bztsrc/model3d/blob/master/docs/procedural.md) you like, eg. Lua, Python, whatever)
> 
> (\*\* - the model's data may be stream compressed, however a) this is optional, and b) the SDK has a built-in decompressor. You won't need any third-party libraries to use the SDK, like JSON or XML libraries, libpng, zlib etc. it is dependency-free.)Features

**Comment by rubenwardy** [comment]
That doesn't appear to be on the list of blender's supported formats

**Comment by Pantyhose-X** [comment]
### He supports Import and export blender
---
> [m3d.h](https://gitlab.com/bztsrc/model3d/blob/master/m3d.h) - a standalone, single header ANSI C/C++ M3D SDK for the format (see the [API](https://gitlab.com/bztsrc/model3d/blob/master/docs/API.md) reference and the [manual](https://gitlab.com/bztsrc/model3d/blob/master/docs/usage.md))
> [webgl-js](https://gitlab.com/bztsrc/model3d/tree/master/webgl-js) - an .M3D image polyfill written in vanilla Javascript with WebGL
> [blender](https://gitlab.com/bztsrc/model3d/tree/master/blender) - an .M3D export (and eventually import) plugin for Blender written in Python
> [goxel](https://gitlab.com/bztsrc/model3d/tree/master/goxel) - an .M3D import / export plugin for the Goxel voxel image editor, written in C

> Utilities
> [m3dconv](https://gitlab.com/bztsrc/model3d/tree/master/m3dconv) - a small command line utility to convert common model formats into .M3D format and to create material libraries
> [m3dview](https://gitlab.com/bztsrc/model3d/tree/master/m3dview) - an easily portable, simple .M3D file viewer also an example how to convert in-memory model into streaming VBO and EBO lists
> [validator](https://gitlab.com/bztsrc/model3d/tree/master/validator) - a web based [Model 3D file validator](https://bztsrc.gitlab.io/model3d/validator)
> [viewer](https://gitlab.com/bztsrc/model3d/tree/master/viewer) - a web based [Model 3D viewer](https://bztsrc.gitlab.io/model3d/viewer), same as m3dview above, but with WebGL and GLES backend
> [tests](https://gitlab.com/bztsrc/model3d/tree/master/tests) - test cases and API usage examples (sample [models](https://gitlab.com/bztsrc/model3d/tree/master/models) in the models directory)

**Comment by appgurueu** [comment]
> He supports Import and export blender

No, he does not support import. As he expressly notes even in your quote, he's planning on writing an importer *eventually*. Meaning there currently is *no importer* for Blender.

Please stop making half-baked suggestions.

M3D does seem like an in principle well-designed format, probably just like B3D seemed like a decent format at the time Irrlicht added support for it. But it lacks the popularity (and thus backing) that we want. glTF is the safer bet here.
