### ISSUE TITLE
Bug with textures of grass, mushroom and others

### ISSUE THREAD

**Issue by IagoAndrade** [minetest/minetest#9675]
##### Minetest version

```
Minetest 5.2.0-win64
```

##### OS / Hardware

Operating system: Windows 7
CPU: Intel core i5-2300 2.8 GHz

GPU model: Intel HD Graphics 2000
OpenGL version: 3.1.0 - Build 9.17.10.4229

##### Summary

In subgames, textures from grass, flowers, mushrooms, apples and some others don't look right, showing a black, blue or white background (as if the texture had no transparency).
It was tested in the minetest_game and Mineclone 2 subgames
It was tested in the same system in version 5.1.1, no problems there (tested both minetest_game and Mineclone 2).
Looks exactly like the issue #5600 screenshots.
##### Steps to reproduce

Create a new world and enter the game. Textures from the above stated objects appear as described, and shown in the screenshots:
![screenshot_20200414_232730](https://user-images.githubusercontent.com/63208230/79299192-cd802b80-7eb9-11ea-8ebd-67ded36617d4.png)
![screenshot_20200414_234058](https://user-images.githubusercontent.com/63208230/79299195-ceb15880-7eb9-11ea-957c-4ef1442a3113.png)
![screenshot_20200414_234113](https://user-images.githubusercontent.com/63208230/79299197-cf49ef00-7eb9-11ea-8699-463d58c1882f.png)
![screenshot_20200414_234120](https://user-images.githubusercontent.com/63208230/79299198-cf49ef00-7eb9-11ea-8e70-fca2070a8a15.png)

**Comment by IagoAndrade** [comment]
Found out disabling shaders seems to solve the problem (though none of the options from the shaders list was actually enabled).
Since both version 5.1.1 and version 5.2.0 were tested with default settings from instalation, the successful test with version 5.1.1 had shaders on, and everything was fine, so something must have changed from 5.1.1.

**Comment by sfan5** [comment]
Shader probably failed to compile, please provide the debug.txt output.

**Comment by IagoAndrade** [comment]
Here it is
[debug.txt](https://github.com/minetest/minetest/files/4483360/debug.txt)

**Comment by sfan5** [comment]
<pre>
ERROR: 0:140: '&&' :  wrong operand types  no operation '&&' exists that takes a left-hand operand of type 'const bool' and a right operand of type 'const int' (or there is no acceptable conversion)
ERROR: 0:141: 'vec4' : syntax error syntax error

138: float disp_z;
139: #if (MATERIAL_TYPE == TILE_MATERIAL_WAVING_LEAVES && ENABLE_WAVING_LEAVES) || \
140: 	(MATERIAL_TYPE == TILE_MATERIAL_WAVING_PLANTS && ENABLE_WAVING_PLANTS)
141: 	vec4 pos2 = mWorld * gl_Vertex;
</pre>

**Comment by SmallJoker** [comment]
The fix is to merge the broken lines again, like done in 478e753298.

**Comment by HybridDog** [comment]
Why does Minetest not abort when the shaders fail to compile?

**Comment by SmallJoker** [comment]
c87d52a5f
