### ISSUE TITLE
Add ability to change default cube size for better experience tune up.

### ISSUE THREAD

**Issue by Nyarg** [minetest/minetest#9679]
## Problem

Right now size of cube do making field of horizont overlapped in height, and cube depth.
Also big size do crashing side eye field experience for, for example detect speed of moving.
etc

**Comment by Extex101** [comment]
You could just change the eye height and collision box size

**Comment by paramat** [comment]
The first comment is not understandable, assuming autotranslate. It seems to suggest a problem, and seems to suggest smaller nodes are wanted.

I suspect this has been requested before, but it is hard to find any issue.
Altering cube size seems difficult. Altering player size has a similar effect, although the player collisionbox is limited to a maximum size of 3x3x3 nodes, so nodes cannot be made much smaller.

**Comment by paramat** [comment]
:-1: 
Very difficult and risky to alter BS in the engine, and not worth it because very low priority and altering player size can do something similar.
This is a voxel game engine for very approx 1 metre size cubres, it is out of scope to have a significantly different node size.
