### ISSUE TITLE
Add Wayland support

### ISSUE THREAD

**Issue by Unesty** [minetest/minetest#9686]
Windowing and input code is in the minetest client, so it must be simple to add a Wayland support. XWayland doesn't work very well.

**Comment by sfan5** [comment]
> Windowing and input code is in the minetest client

It is not. Except for extras like e.g. setting the Window icon, all interaction with X11 is handeled by Irrlicht.

**Comment by nerzhul** [comment]
Xwayland is working quite fine to me but yeah native wayland is a thing irrlicht needs to (never) do.
Why (never) ? because irrlicht is pretty slowly dead in terms of releases

**Comment by Unesty** [comment]
celeron55 tried to add wayland support in his fork

**Comment by nacknime-official** [comment]
> Xwayland is working quite fine to me but yeah native wayland is a thing irrlicht needs to (never) do.
> Why (never) ? because irrlicht is pretty slowly dead in terms of releases

 In Wayland session (sway) Minetest's FPS are below than in X11 session (i3). And that's with Half-Life 1 via XWayland too.
So, you should compare it on your own, maybe I have bad Sway setting or issue with my drivers (intel UHD 620, i7-8550U)

**Comment by okias** [comment]
I tested Minetest on Librem 5 devkit (Linux phone) and seems like old irrlicht making it no-go. :disappointed:

**Comment by Zughy** [comment]
Duplicate of https://github.com/minetest/irrlicht/issues/69, keeping the other one since now MT is maintaining its own fork of Irrlicht
