### ISSUE TITLE
Add 'minetest.get_texture()'

### ISSUE THREAD

**Issue by RibeThings** [minetest/minetest#9688]
I'm making a mod and I want to use a texture from another mod.

### Real Examples
Let's say that you are making a mod that makes a rotten version of every food. Then you will need to make a clone of that Item with the same texture, but you can't get texture from other mods.

### Fake Code Examples
minetest.register_craftitem("example:rotten_apple", {
inventory_image = minetest.get_texture("default:apple")
})

**Comment by rubenwardy** [comment]
```lua
local def = minetest.registered_items["default:apple"]

minetest.register_craftitem("example:rotten_apple", {
    inventory_image = def.inventory_image
})
```
