### ISSUE TITLE
Refactor the main method in main.cpp

### ISSUE THREAD

**Issue by dysoco** [minetest/minetest#969]
Hello.

Not sure if you've noticed, but the main method in main.cpp is over 1000 lines of code, while the suggested size of a method is no more than 200 lines of code.

I know this is low priority, but it would be very useful to refactor this method, separating it into smaller functions for example, as it does a myriad of different things.

I have already started, as a way of learning the code base (Via refactoring I keep record of what each thing does) and I was wondering if you would be interested in a series of patches that would clean up this a bit.

This would, hopefully, improve the productivity of core developers.

**Comment by nerzhul** [comment]
I'll do it when i get time

**Comment by Zeno-** [comment]
This is very old.

main() used to be 2000-3000 lines. It's since been fixed (although more work is needed)
