### ISSUE TITLE
scroll_container content is reset to the top everytime a formspec is reloaded

### ISSUE THREAD

**Issue by kilbith** [minetest/minetest#9691]
Try out the `redesign` branch of `craftguide`: https://github.com/minetest-mods/craftguide/tree/redesign

1. Open the craftguide
2. Move the scrollbar down
3. Click an item

The scrollbar thumb is still correctly positioned but the `scroll_container` content is reset to the top. You have to move the thumb of the scrollbar to show the appropriate content.

@Desour @rubenwardy

**Comment by An0n3m0us** [comment]
Confirmed on `5.3.0-dev-7e21b3c-dirty`:

![image](https://user-images.githubusercontent.com/49789044/79514016-1d3b3000-803d-11ea-8339-7ab2ee76b7c6.png)

**Comment by Desour** [comment]
So, basically the scrollbar has a default value and this value is not applied to the scroll container.
This could be fixed by iterating over the scroll containers in regenerateGUI and calling the update function on each. I'll do a PR tomorrow.

**Comment by Desour** [comment]
#9699
