### ISSUE TITLE
No gamepad support on Android?

### ISSUE THREAD

**Issue by bluegizmo83** [minetest/minetest#9695]
Is there really no gamepad support on the Android version, or am I just missing it somewhere?

**Comment by SmallJoker** [comment]
#4153

**Comment by Floppe** [comment]
Sorry to comment on an old issue.

I've tested this today and found the following in logcat for my phone using a PS4 controller.
`E/Minetest: 2020-10-08 13:29:34: ERROR[Main]: Could not activate joystick support.`

It works on Linux Ubuntu, though I added my own layout for a PS4 controller.

**Comment by inferrna** [comment]
Still
`10-19 10:23:57.014 21168 21210 E Minetest: 2022-10-19 10:23:57: ERROR[Main]: Could not activate joystick support.`
with bsp-d3 and 5.6.1.
Also tried to enter device id, recognized by "Gamepad Tester" app.

**Comment by rubenwardy** [comment]
We don't really support gamepads currently on any platform

**Comment by Niquarl** [comment]
That wiki page doesn't have any options for android
