### ISSUE TITLE
FOV Fade

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9696]
A feature to fade FOV like  `minetest.sound_fade(handle, step, gain)`

**Comment by ClobberXD** [comment]
I hope I understood the feature request correctly. I think a transition while changing a player's FOV is a requirement for use-cases like FOV change while sprinting, where the acceleration is somewhat fast but still gradual, and not an instantaneous change in velocity. Gentler FOV changes would boost immersion.

I think this feature request can be implemented by extending the existing `player:set_fov` method. I'm thinking `set_fov(fov, is_multiplier, time)`, where `time` is the total time (in seconds) taken for the FOV transition to occur.

If there are no core dev disapproval to this feature request, I'm willing to implement this.

**Comment by sfan5** [comment]
This could be implemented with CSM once the proper features are in place, but this usecase is common enough that I'd say it should be supported as is.

**Comment by ClobberXD** [comment]
Even with CSM, currently there's no better way to do this, other than calling `set_fov(current_fov + delta_fov)` multiple times. The result would be noticeably choppy, unless the interval between two calls is near about equivalent to the camera step.

But once CSM is available, set_fov calls (w/ transitioning) could be supported by the client-side API.

**Comment by oilboi** [comment]
> I hope I understood the feature request correctly. I think a transition while changing a player's FOV is a requirement for use-cases like FOV change while sprinting, where the acceleration is somewhat fast but still gradual, and not an instantaneous change in velocity. Gentler FOV changes would boost immersion.
> 
> I think this feature request can be implemented by extending the existing `player:set_fov` method. I'm thinking `set_fov(fov, is_multiplier, time)`, where `time` is an optional param, denoting the total time (in seconds) taken for the FOV transition to occur. If omitted, the FOV change is instantaneous. If `set_fov` is invoked while an existing transition is in process, the FOV transition is overridden by the new `set_fov` call, even if the new call is instantaneous. Sounds ok?
> 
> If there are no core dev disapprovals to this feature request, I'm willing to implement this.

I think that's a great idea! If a new FOV fade is called it could get the client's current FOV and blend from there

**Comment by oilboi** [comment]
> This could be implemented with CSM once the proper features are in place, but this usecase is common enough that I'd say it should be supported as is.

CSM FOV would be amazing!

**Comment by HybridDog** [comment]
That may be related: #385
