### ISSUE TITLE
Enabling client-side modding on Android results in mod security crash

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9702]
Given that client-side modding isn't officially supported, this could be considered low priority 

##### Minetest version

```
5.3.0-dev-4e247
```

##### Summary

![image](https://user-images.githubusercontent.com/2122943/79618831-0c54f200-8103-11ea-93ce-4535085495c3.png)

**Comment by MoNTE48** [comment]
Very interesting... Could it be caused by the latest LuaJIT?
Never tested CSM on Android before.

**Comment by MoNTE48** [comment]
Upd. ARM64 issue only (debug and release). Everything works on armv7-a.
