### ISSUE TITLE
Constant single player freezes on Android

### ISSUE THREAD

**Issue by The32bitguy** [minetest/minetest#9703]
##### Minetest version

```
5.1.0.25
5.3.0-dev-4e247 (64 bit)
```

##### OS / Hardware

Operating system: Android 6.0
CPU: Huawei y6 2017

GPU model:
OpenGL version:

##### Summary

Single player suffers from freezes relating to processing outside of graphics. I have a high frame rate but large delays when I use items and for entities. According to a global step timer the delays are first less than half a second but can go to 10 seconds between each call after a short playtime.
Video of issue: https://cdn.discordapp.com/attachments/645782637637664780/700841774478000158/MP4_20200417_234306_1.mp4

##### Steps to reproduce

Using the latest stable build generate a new world and start. The problem of delayed callbacks will gradually become worse after half a minute.

**Comment by MoNTE48** [comment]
Please check the latest build (5.3.0-dev)
You will have to uninstall installed Minetest first. Data will be saved.

https://github.com/MoNTE48/minetest/releases/download/5.3.0-dev/app-armeabi-v7a-release.apk

**Comment by rubenwardy** [comment]
Note: the version in the first post is wrong, this has been reproduced in 5.3.0-dev already

**Comment by The32bitguy** [comment]
> Please check the latest build (5.3.0-dev)
> You will have to uninstall installed Minetest first. Data will be saved.
> 
> https://github.com/MoNTE48/minetest/releases/download/5.3.0-dev/app-armeabi-v7a-release.apk

I have tried both the 64 and 32 bit versions of the 5.30 dev build from rubenwardy's website along with the supplied link and the issue persists with all three.

**Comment by MoNTE48** [comment]
@The32bitguy, Does this happen with vanilla minetesg_game, or with any other game? Are there any mods installed?

**Comment by appgurueu** [comment]
I experience freezes on desktop, but they're rare enough for me not to bother.

**Comment by The32bitguy** [comment]
> @The32bitguy, Does this happen with vanilla minetesg_game, or with any other game? Are there any mods installed?
I don't have any mods installed with minetest_game and it still happens.
It also occurs with nodecore.

**Comment by MoNTE48** [comment]
Well, 
> when I use items and for entities.
entities = dropped items?
Although the performance of your phone is suitable only for calls and checking email ... So I would like to see comments from owners of other Android devices.
(Your device in Antutu: 39.856, iPhone 11 in Antutu: 521.227)

**Comment by SmallJoker** [comment]
I don't experience those lags on a comparable Huawei phone. Nether spreading lava on the sea not dropping many items shows any freezes.

Minetest 5.1.0 - vanilla world
Android 6.0
Average FPS: 20 (no mapblock updates)
Antutu score: 37'000

**Comment by MoNTE48** [comment]
@SmallJoker not a bug. Or not an Android bug.

**Comment by Adnan1091** [comment]
@MoNTE48 It is an bug.Also I suffer from this.It makes minetest nearly unplayable.There is an even delay in damage.When you dive into the water,oxygen symbol appears 5-6 sec later.My phone is xiaomi redmi s2 overclocked to 2.2 Mhz.

**Comment by Adnan1091** [comment]
Hey dude,do you have volcano mod by facedeer?I did some test to mods whether it is caused by it.I disabled that mod and i had no delay anymore.I didn't tested my other mods though but i blame volcano mod for this.
