### ISSUE TITLE
Add minetest.register_on_player_step (or find a better name)

### ISSUE THREAD

**Issue by nerzhul** [minetest/minetest#9707]
## Problem

We have a very good mod base, but each time a thing is needed by a single mod to be run on player step loop, the mod implements a such thing:
```Lua
for _, player in pairs(core.get_connected_players()) do
  -- this useless check has been found on various mods whereas interface can only return PlayerSAO refs
  if not player:is_player()
    continue
  end
  -- do something           
```

core.get_connected_players() return a playerSAO refs serialized list, it means on each step we will serialize multiple times the the LuaRef for the same player. 

## Solutions

I think we can do better by implementing it a specific registration for player steps on the builtin the Lua side (at first).

We should implement minetest.register_on_player_step(player) in builtin and do the minetest.register_global_step() call which will do the player loop iteration directly.

This will permit to reduce mod code a little bit, and reduce callback number from the code to Lua on the global step, iterating directly on the players.

## Alternatives

As a first class contribution, if someone has the skills, implementing it directly on PlayerSAO step is better because it can permits to have a return on the call to interact directly on the PlayerSAO::step workflow.

**Comment by SmallJoker** [comment]
As discussed in #9708, there are barely any use-cases and optimizations aren't really possible.
Close?

**Comment by paramat** [comment]
:-1: for reasons discussed elsewhere. sfan5 is also sceptical of usefulness.
