### ISSUE TITLE
Android 5.3.0 Dev doesn't extract the game files

### ISSUE THREAD

**Issue by AbduSharif** [minetest/minetest#9709]
##### Minetest version

```
Minetest 5.3.0 4e247 Dev
```

##### OS / Hardware

Operating system: Android 9, 32bit
CPU:

GPU model:
OpenGL version:

##### Summary

On new installs the game crashes everytime, that's because it didn't extract the game files, the debug.txt shows errors because the game files aren't present.

Manually extracting the game files from the APK made it work.
##### Steps to reproduce

Just install the app, if you didn't have game files before it won't extract it and will instead create a debug.txt that shows some files are missing.
Try opening the app again and it will crash.

**Comment by nerzhul** [comment]
if confirmed it's a blocker for me

**Comment by AbduSharif** [comment]
Looking at the older version's apk, this one has the game files archived in .zip file in the assets folder, in the older apk the game files aren't archived.

**Comment by MoNTE48** [comment]
Files are unpacked once at the first start or at updating. If for some reason you deleted the Minetest folder or broken the files necessary for starting MT, ask yourself why you did it. Clean up application data. Launch it again. It will unzip the files again. And don't do that anymore.

The code for unpacking and version control is very reliable.

**Comment by rubenwardy** [comment]
Previously, the app's contents were checked every boot using hashes. This is good for reliability, but bad for flexibility and performance.

The apps content's are only extracted once per load of an app version. The app version of the last time that the contents were extracted is stored in the app's shared preferences. I believe that it won't check the extract again if the contents are deleted or if the extract fails (confirmation needed)

I'd quite like to add a recovery dialog that resets user settings and re-extracts content, and is shown when the app crashes in the main menu or by going into settings in the main menu. But this isn't a fix if this happened without the user editing or deleting the Minetest folder

**Comment by MoNTE48** [comment]
In MC, unpacking will be repeated if the menu cannot be started. I did not think that this is a common situation and it is needed here.
The version is saved after a successful launch. Otherwise, the game just closes.

**Comment by AbduSharif** [comment]
> Files are unpacked once at the first start or at updating. If for some reason you deleted the Minetest folder or broken the files necessary for starting MT, ask yourself why you did it. Clean up application data. Launch it again. It will unzip the files again. And don't do that anymore.
> 
> The code for unpacking and version control is very reliable.

What are you saying? I did a clean install, I don't have minetest game files at all so it should extract them for me, but it didn't.
And why would I delete the game files? I've been playing this game for sometime so I know what I'm doing, the game files are necessary for the game so I wouldn't delete them because I know that.
Also cleaning the application data did nothing, I had to extract the game files myself from the apk.

**Comment by MoNTE48** [comment]
1) which APK are you using
2) of course you granted permission to access memory?
3) logcat is the only thing that will tell me what went wrong.

**Comment by AbduSharif** [comment]
> 1. which APK are you using
> 2. of course you granted permission to access memory?
> 3. logcat is the only thing that will tell me what went wrong.

1 - the 32bit apk.
2 - of course.
3 - there's no logcat just debug.txt, and it's the only thing present in Minetest folder, it just tells about missing files, and that's because they haven't been extracted.

**Comment by MoNTE48** [comment]
1 - url pls. There are no official 5.3 builds yet
3 - Logcat will require connecting your phone in debug mode to a PC and running adb logcat.
This will give information what happened.

I will do backport some checks for the unpacker. Find out what went wrong!

**Comment by rubenwardy** [comment]
here: https://minetest.rubenwardy.com/android/

**Comment by MoNTE48** [comment]
Well, there are the following checks. @rubenwardy, say what you think. All of them are used (or used previously) in MultiCraft, although it is paranoid.

1) The version will be recorded when we receive the unpack confirmation. There are several validation algorithms.
2) Recounting the number of unpacked files (too paranoid)
3) Check the available space before unpacking
4) Informing the user if something went wrong, followed by restarting the application and retrying
5) in case of a loading error mainmenu / font, native will notify Java about this. We exit the application `exit(0)` (without crash) and the next time we start unpacking with overwriting again.
6) We can even check for the presence of key files before starting the game to make sure that the Minetest folder has not been corrupted.

---
So many checks are required. This report does not even contain device information. Perhaps this is some kind of Chinese device on Android 4 with a full cache. For this reason, we get exeption and it is not handled properly...

**Comment by AbduSharif** [comment]
Just check the 32bit version apk, I think you're looking a bit too far into it, I think the reason is because the game files that are inside "assets" folder inside the apk are packed in an archive (.zip file) is the reason the game didn't unpack them?
In version 5.1.0, the game files aren't in an archive.

**Comment by MoNTE48** [comment]
1) your report is missing critical information. Look carefully, I'm not a psychic.
Device model: Samsung Galaxy S9 Plus Exynos, Android 9.1
2) In 5.3, the build system and the entire Java part were completely rewritten. If the APK contains an archive with all the files, then it is built correctly.
3) I will try by pointing my finger at the sky several times to solve your problem.

**Comment by AbduSharif** [comment]
Sony Xperia Z1, and if you actually read the report correctly you'll know my Android version 9, hopefully that helps, I don't have a PC to export logcats.
