### ISSUE TITLE
ogles2 not working

### ISSUE THREAD

**Issue by AbduSharif** [minetest/minetest#9710]
##### Minetest version

```
Minetest 5.3.0 4e247 Dev
```

##### OS / Hardware

Operating system: Android 9, 32bit
CPU:

GPU model: Adreno 330
OpenGL version: OpenGL ES 3.2

##### Summary

When using video driver "ogles2" and opening the app a light blue background appears, basically the game isn't working properly.
Unless you change the video drive in minetest.conf to "ogles1" the game won't work.
debug.txt errors such as:
- Warning[Main]: Irrlicht: Could not open vertex shader program file
- Warning [Main]: Irrlicht: Could not open pixel shader program file
- ERROR[Main]: Irrlicht: GLSL shader program failed to link
- WARNING[Main]: Irrlicht: Warning: Missing shader files needed to simulate fixed function materials:
/storage/emulated/0/Minetest/media/Shaders/COGLES2Renderer2D.vsh
Shaderpath can be changed in SIrrCreationParamters::OGLES2ShaderPath
##### Steps to reproduce

Go to settings > all settings > graphics > in-game > advanced > video driver.
Change the option from ogles1 to ogles2, close the app, then open it and the light blue background will appear.

**Comment by sfan5** [comment]
Looks like it's missing the installation of Irrlicht's shader files

**Comment by AbduSharif** [comment]
There's no "media" folder provided with the game files in the apk.

**Comment by MoNTE48** [comment]
Easy enough to fix, although a little useless. ogles2 is broken, you still can’t play.

**Comment by AbduSharif** [comment]
What's broken in it?

**Comment by MoNTE48** [comment]
@AbduSharif, alpha in inventory and wield

**Comment by AbduSharif** [comment]
Oh, too bad.

**Comment by MoNTE48** [comment]
ogles2 support will be added later (hopefully until 5.3-release)
