### ISSUE TITLE
HUD scaling/position issues on Android

### ISSUE THREAD

**Issue by R3R3R3** [minetest/minetest#9714]
##### Minetest version
```
Android 5.3.0-dev 4e247 (32-bit) (rubenwardy's build)
```

##### OS / Hardware
Android 10 / Samsung S10e

##### Summary

HUD scaling isn't working so well.

![](https://cdn.discordapp.com/attachments/701422205891772529/701422261986525245/Screenshot_20200419-132810_Minetest.jpg)

As you can see, the hudbars are mispositioned (clobbering the hotbar) and extremely small. The text is scaled reasonably well, but mispositioned.

The right-side-HUD (Citadella) has exactly the same problem.

----

I'm not entirely sure what client controls, if any, are available here to fix this myself. I don't know if my phone is doing something unusual, so extra testers would be nice.

**Comment by SmallJoker** [comment]
Related: #6296

**Comment by R3R3R3** [comment]
`hud_scaling` was on 0.7, now it's on 2.0.

![](https://cdn.discordapp.com/attachments/701422205891772529/701447047160791150/Screenshot_20200419-160021_Minetest.jpg)

This setting doesn't appear to affect hudbars et al.

**Comment by MoNTE48** [comment]
Minetest doesn't seem to be designed for high resolution displays at all. Many elements (including HUD) use scaling only for some elements.
There is a problem with the images in the table (see Online tab in Mainmenu).

It really will take a lot of work to fix it all. I hope to someday find the time for this :)
