### ISSUE TITLE
Cleaning up client logging: "loaded texture" messages

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9716]
## Problem

The "loaded texture" messages aren't particularly useful, but clutter client output on terminal:
```
Loaded texture: /home/user/.minetest/games/minetest_game/menu/header.png
Loaded texture: /home/user/.minetest/games/cellestial_game/menu/icon.png
Loaded texture: /home/user/.minetest/games/hades_revisited/menu/icon.png
Loaded texture: /home/user/.minetest/games/kingdoms_game/menu/icon.png
Loaded texture: /home/user/.minetest/games/magic_ctf/menu/icon.png
Loaded texture: /home/user/.minetest/games/minetest_game/menu/icon.png
Loaded texture: /home/user/minetest-mainmenu-improvements/games/minimal/menu/icon.png
Loaded texture: /home/user/.minetest/games/nodecore/menu/icon.png
```

## Solution

Properly log them using log level verbose.

**Comment by sfan5** [comment]
This has been looked at before and I think the result was that Irrlicht logs them directly to stdout and we can't fix this.

**Comment by appgurueu** [comment]
Interesting, this explains why I was unable to grep "loaded texture" in the Minetest sources. I now looked for it in the Irrlicht sources, and it appears this has already been fixed in upstream Irrlicht two years ago:
> Reduce log-messages for "loaded texture" and "loaded mesh" from ELL_INFORMATION to ELL_DEBUG.
> In larger projects those tend to spam the default log too much.
I'm wondering how old the Irrlicht release we are running is.

**Comment by sfan5** [comment]
> I'm wondering how old the Irrlicht release we are running is

Irrlicht 1.8.4 is the most recent release, it's from 2016.
