### ISSUE TITLE
vmanip without integer to double conversions

### ISSUE THREAD

**Issue by HybridDog** [minetest/minetest#9728]
## Problem

Why is this needed?
I'm always frustrated when I think about Minetest converting integers to doubles and the other way round just to pass node data in vmanip tasks.
I don't know how much impact the integer to double (and other way round) casting has on the performance (I haven't tested it).

## Solutions

It could be possible to simply reinterpret the content_t integers as doubles and put that into a lua number. The node id numbers would then no longer be human-readable integers; without the casting, passing the nodes data may be faster.

## Alternatives

If the casting does not have a significant impact on performance, then the suggested change is not needed.

**Comment by sfan5** [comment]
I heavily doubt such an optimization is worth it in practice.

But if you absolutely want to try: 
```diff
diff --git a/src/script/lua_api/l_item.cpp b/src/script/lua_api/l_item.cpp
index 9f12d3ac7..e4d58c5c8 100644
--- a/src/script/lua_api/l_item.cpp
+++ b/src/script/lua_api/l_item.cpp
@@ -614,7 +614,7 @@ int ModApiItemMod::l_get_content_id(lua_State *L)
 	if (!ndef->getId(name, content_id))
 		throw LuaError("Unknown node: " + name);
 
-	lua_pushinteger(L, content_id);
+	u64 x = content_id; lua_pushnumber(L, *(double*)&x);
 	return 1; /* number of results */
 }
 
diff --git a/src/script/lua_api/l_vmanip.cpp b/src/script/lua_api/l_vmanip.cpp
index b99b1d98c..5ac85949f 100644
--- a/src/script/lua_api/l_vmanip.cpp
+++ b/src/script/lua_api/l_vmanip.cpp
@@ -76,7 +76,7 @@ int LuaVoxelManip::l_get_data(lua_State *L)
 
 	for (u32 i = 0; i != volume; i++) {
 		lua_Integer cid = vm->m_data[i].getContent();
-		lua_pushinteger(L, cid);
+		u64 x = cid; lua_pushnumber(L, *(double*)&x);
 		lua_rawseti(L, -2, i + 1);
 	}
 
@@ -96,7 +96,7 @@ int LuaVoxelManip::l_set_data(lua_State *L)
 	u32 volume = vm->m_area.getVolume();
 	for (u32 i = 0; i != volume; i++) {
 		lua_rawgeti(L, 2, i + 1);
-		content_t c = lua_tointeger(L, -1);
+		double x = lua_tonumber(L, -1); content_t c = *(u64*)&x;
 
 		vm->m_data[i].setContent(c);
 
```

**Comment by sfan5** [comment]
Further research: LuaJIT has a dual-number mode that avoids any floating point conversions for numbers that fit into `int32_t` (code [here](https://github.com/LuaJIT/LuaJIT/blob/9143e86498436892cb4316550be4d45b68a61224/src/lj_obj.h#L895-L910)).
It is enabled by default on ARM and AArch64 ([lj_arch.h](https://github.com/LuaJIT/LuaJIT/blob/9143e86498436892cb4316550be4d45b68a61224/src/lj_arch.h#L145)) and can be optionally enabled for x86 or x64 in the Makefile:

[LuaJIT/LuaJIT: src/Makefile#L107-112](https://github.com/LuaJIT/LuaJIT/blob/9143e86498436892cb4316550be4d45b68a61224/src/Makefile#L107-L112)
```makefile
# Some architectures (e.g. PPC) can use either single-number (1) or
# dual-number (2) mode. Uncomment one of these lines to override the
# default mode. Please see LJ_ARCH_NUMMODE in lj_arch.h for details.
#XCFLAGS+= -DLUAJIT_NUMMODE=1
#XCFLAGS+= -DLUAJIT_NUMMODE=2
#
```

**Comment by HybridDog** [comment]
I have tested it on a 101x101x101 chunk of nodes with worldedit.replace and there's no noticeable performance difference:

before:
```
0.018182 s get data
0.017069 s set data

0.017225 s get data
0.016921 s set data

0.017692 s get data
0.017621 s set data
```

after:
```
0.016556 s get data
0.01933 s set data

0.017832 s get data
0.018527 s set data

0.017405 s get data
0.017892 s set data
```
