### ISSUE TITLE
pointing offset ( again after fix "Camera: Fix shooting line offsets (#9681)" )

### ISSUE THREAD

**Issue by RonnyBarthmann** [minetest/minetest#9729]
TESTED AGAIN ON: 5.3.0-dev-5355cb1d8
Minetest Version 5.x ( all; including 5.3.0-dev-5355cb1d8 )
Operating system: Linux/GNU 4.9.6-64 / Debian 9.0 / Knoppix 8.0
CPU: AMD Athlon(tm) II X4 630 Processor
GPU model: Advanced Micro Devices, Inc. [AMD/ATI] Barts PRO [Radeon HD 6850]

##### Summary
Pointing is not accurate between two Blocks
even after the fix #9681

##### Steps to reproduce
- Play some time ( turn often around )
- Try to slide slow over two Blocks ... if you Mouse cross the line between the two blocks sehen sie wie das highlighting is not correct
- Therefore, you don't place the blocks where you actually want them
- This is VERY stressful, especially with small edges (e.g. xpanes)

**Comment by RonnyBarthmann** [comment]
after extreme turning and struggling the mouse for 10 seconds:

Pointing in the Air:
![screenshot_20200422_180242](https://user-images.githubusercontent.com/32592152/80005869-78997200-84c4-11ea-884c-72fa0579acc5.png)
![screenshot_20200422_180312](https://user-images.githubusercontent.com/32592152/80005874-7a633580-84c4-11ea-9ebd-3cb53e9c65e9.png)
![screenshot_20200422_180319](https://user-images.githubusercontent.com/32592152/80005884-7c2cf900-84c4-11ea-9d7e-103d38203546.png)

the last image (3) is after trying to put a xpane on another (image 2)

**Comment by RonnyBarthmann** [comment]
this report is not a simply copy of issue #9648 i tested it again with the new git version ( seen in the image )

**Comment by SmallJoker** [comment]
Does this also happen within a radius of 200m from spawn?
