### ISSUE TITLE
Add a 'panel' HUD type

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9735]
## Problem

Right now there is no default container for HUD elements such as Godot/Unity UI panels

## Solutions

Implement a container element to create complex HUDs. I've released a mod just today to give an idea and it'd be great if something similar was implemented by default: https://content.minetest.net/packages/Zughy/panel_lib/. There is an in-depth documentation in the repo

**Comment by Wuzzy2** [comment]
Please define exactly what a “panel” is. Otherwise, this feature request is worthless and should be closed.

**Comment by ClobberXD** [comment]
Probably this?

> container element to create complex HUDs

I assume this is functionally equivalent to `container[]` in formspecs.

**Comment by Zughy** [comment]
> Please define exactly what a “panel” is. Otherwise, this feature request is worthless and should be closed.

I... literally gave you a definition ("a container element to create complex HUDs"), a generic example (Godot and Unity) and an entire mod with an in-depth documentation of what it does

**Comment by Wuzzy2** [comment]
Is this just like `container[]` from formspecs, but for HUD?
If yes, why not calling it `container`?

**Comment by ClobberXD** [comment]
Concept sounds useful, but what would be the advantages of implementing this in the engine, compared to using mods like `panel_lib`?

**Comment by Zughy** [comment]
> Is this just like `container[]` from formspecs, but for HUD?
> If yes, why not calling it `container`?

Tomato, toma.. oh wait, that doesn't work in writing. :(
But you got it, the name is not that relevant, I think they're pretty interchangeable


> Concept sounds useful, but what would be the advantages of implementing this in the engine, compared to using mods like `panel_lib`?

Because it's useful and it exists in any modern engine AFAIK. If Minetest wants to call itself an engine, I think there should be some "must have" features to simplify the work to anyone who wansta try to write some code. I made an external library, sure, but imho it'd be better if it were implemented by default

**Comment by appgurueu** [comment]
A `panel` HUD element should not provide functionality which can already be achieved using mods.

Instead, it should allow using advanced alignment options. For example, currently text with emotes (which are images) inside is impossible, because there is no reliable way to get the text length. Using a panel, one could do something like - the advanced alignment would then work a bit like HTML flexbox layout:

```lua
player:hud_add{
    hud_elem_type = "panel",
    align_items = {x = 0, y = 0} -- center align all items
    items = {} -- list of hud elements
}```
(very rough sketch)

**Comment by Zughy** [comment]
As Krock went for a radical redesign of the HUD system in https://github.com/minetest/minetest/pull/10245  , this one is kind of pointless at the moment. For people who want to use something similar in the meanwhile, this is the mod I did to implement a similar feature in Lua: https://content.minetest.net/packages/Zughy/panel_lib/
