### ISSUE TITLE
Windows: High DPI scaling broken

### ISSUE THREAD

**Issue by adrido** [minetest/minetest#9744]
##### 5.3-dev

Working: 5.2 release
Broken: 5.3-dev 914dbeaa0be4b5ef87506b605ef4e241cd3732dc

##### OS / Hardware

Operating system: Windows 10 1909

##### Summary

Expected behaviour:  scaling is done by Irrlicht engine
Actual behavior  scaling is done by Windows (Bitmap-stretching)

left: 5.2, sharp, upscaling by Irrlicht
right: 5.3-dev, blurry, upscaling by Windows
![grafik](https://user-images.githubusercontent.com/3142688/80274074-14e79280-86d8-11ea-8936-ed4b6aa6b81f.png)

##### Steps to reproduce

Open Minetest on a High Dpi display.

**Comment by adrido** [comment]
Bad commit: 40df3931d882daaeee42c8de69882b9f9df5c312

**Comment by sfan5** [comment]
Are you using MSVC?
Have you tried reverting the change to the manifest? https://github.com/minetest/minetest/commit/40df3931d882daaeee42c8de69882b9f9df5c312#diff-d86a44843a712fff23350bb6190a27db

**Comment by adrido** [comment]
Yes, Im using msvc. 
Reverting the changes to the manifest fixes the issue.

It works in your version, if you add it to the asmv3 namespace.
but for asmv1 only the old one seems to be valid.
https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests#dpiaware
