### ISSUE TITLE
Translations no longer work running from source directory with RUN_IN_PLACE=0

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9745]
##### Minetest version
```
49ed0ca00a9a79b5db0bd6cc4589d56d7f1b3d45
```

##### OS
Operating system: GNU/Linux

##### Summary
Minetest 5.3.0-dev no longer supports translations.

##### Steps to reproduce
* Do a fresh clone of the Minetest repo (`git clone`)
* `cmake .`
* `make`
* `./bin/minetest`

Expected: Game is translated into your system language.
Actual: It is not.

Repeat the same steps, but after the clone, do `git checkout 5.2.0` first. Minetest is translated just fine.

This proofs that Minetest 5.3.0-dev has a regression.

**Comment by Wuzzy2** [comment]
I believe I have found the offending commit:

5355cb1d87f60bc5548a8a9311e597b9c6046013

Reverting this commit, and then doing `cmake .` and `make` again, gives me back the translations.

@HybridDog, I summon you!

**Comment by Wuzzy2** [comment]
Oops. Wrong commit and dev. The REAL offending commit is:

2349d31bae1bfc4d58fd88efbc88261e69b11dad

**Comment by sfan5** [comment]
Works for me, also on Linux.
`minetest --version` output would be helpful.

**Comment by Wuzzy2** [comment]
`minetest --version`:

```
Minetest 5.3.0-dev-73180a73 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/local/share/minetest"
```

`minetest --verbose --worldlist ""`:

```
2020-04-25 13:59:19: INFO[Main]: Using system-wide paths (NOT RUN_IN_PLACE)
2020-04-25 13:59:19: WARNING[Main]: system-wide share not found at "/usr/local/share/minetest"
2020-04-25 13:59:19: WARNING[Main]: system-wide share not found at "~/src/minetest/git-master/bin/../share/minetest"
2020-04-25 13:59:19: WARNING[Main]: system-wide share found at "~/src/minetest/git-master/bin/.."
2020-04-25 13:59:19: INFO[Main]: Detected share path: ~/src/minetest/git-master/bin/..
2020-04-25 13:59:19: INFO[Main]: Detected user path: ~/.minetest
2020-04-25 13:59:19: INFO[Main]: Detected cache path: ~/.cache/minetest
2020-04-25 13:59:19: INFO[Main]: Using in-place locale directory ~/src/minetest/git-master/bin/../locale even though a static one was provided (RUN_IN_PLACE or CUSTOM_LOCALEDIR).
2020-04-25 13:59:19: ERROR[Main]: Invalid --worldlist value:
```

I also ran this command in 5.2.0, but it's the same output!

**Comment by sfan5** [comment]
> `Using in-place locale directory ~/src/minetest/git-master/bin/../locale even though a static one was provided`

Evidently it can find the locale directory just fine, so the failure must be happening somewhere else.

**Comment by Wuzzy2** [comment]
But why does it work when I revert that commit I mentioned before then?

Why was that commit even done in the first place?

**Comment by sfan5** [comment]
> Why was that commit even done in the first place?

Consistency, other projects do not put their locale files into `/usr/share/locale/ProjectName` and instead share a `/usr/share/locale` folder. Some distributions patched this change in when creating a package.

**Comment by An0n3m0us** [comment]
Hmm, I just tried on the latest commit and it worked fine.
`Ubuntu 19.10 - Minetest 5.3.0-dev-8b45f6a-dirty (Linux)`

**Comment by An0n3m0us** [comment]
I tried with `cmake .` and `cmake -DRUN_IN_PLACE=0`, and it still detects my system language correctly.

**Comment by sfan5** [comment]
This is only reproducible if `/usr/local/share/locale` exists on your system.

**Comment by An0n3m0us** [comment]
Oh okay; it doesn't exist on my system.

**Comment by Wuzzy2** [comment]
Ahhh. Very interesting. Yes, this directory does indeed exist on my system.

**Comment by juozaspo** [comment]
Did you create system package using cpack (e.g. run `cpack -G DEB`) and installed it, if not did you install it using make install command (or using `checkinstall` or other installation wrapper to create uninstallation entry for the system)? I suspect minetest wouldn't find locale files unless translations files are installed to correct location. Testing latest master, I confirm that locales are not found while launching from source directory if minetest is not installed to system. Installing to system and running from source directory detects the share correctly, resulting in correct locale operation.
