### ISSUE TITLE
Database backend postgresql not supported ?

### ISSUE THREAD

**Issue by d-stephane** [minetest/minetest#9747]
##### Minetest version
```
5.3.0-dev-73180a7
```

##### OS / Hardware

Operating system: Debian Buster
CPU: Quad Core Intel Core i5-4570 (-MCP-)

##### Summary
Unable to use the postgresql backend after compilation

My command line option for cmake :
<pre>
$ cmake . -DRUN_IN_PLACE=TRUE \
          -DBUILD_CLIENT=TRUE \
          -DBUILD_SERVER=TRUE \ 
          -DENABLE_POSTGRESQL=ON \
          -DPostgreSQL_INCLUDE_DIR=/usr/include/postgresql/ \
          -DPostgreSQL_LIBRARY=/usr/lib/x86_64-linux-gnu/libpq.so.5 \
          -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/include/postgresql/</pre>

cmake result :
<pre>
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- *** Will build version 5.3.0-dev ***
-- Found Irrlicht: /usr/lib/x86_64-linux-gnu/libIrrlicht.so  
-- Using GMP provided by system.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Using bundled JSONCPP library.
-- Found LuaJit: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so (found version "") 
-- Using LuaJIT provided by system.
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so  
-- cURL support enabled.
-- Found GetText: /usr/include  
-- GetText enabled; locales found: ar;be;ca;cs;da;de;dv;el;eo;es;et;eu;fil;fr;he;hu;id;it;ja;ja_KS;jbo;kk;kn;ko;ky;lo;lt;ms;my;nb;nl;nn;pl;pt;pt_BR;ro;ru;sl;sr_Cyrl;sv;sw;th;tr;uk;vi;zh_CN;zh_TW
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found VORBIS: /usr/include  
-- Sound enabled.
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.9.1") 
-- Freetype enabled.
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so
-- Looking for cbreak in /usr/lib/x86_64-linux-gnu/libncursesw.so - found
-- Found Ncursesw: /usr/lib/x86_64-linux-gnu/libncursesw.so  
-- ncurses console enabled.
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so.5 (found version "12.2 (Debian 12.2-2.pgdg100+1)") 
-- PostgreSQL backend enabled
-- PostgreSQL includes: /usr/include/postgresql;/usr/include/postgresql
-- LevelDB backend enabled.
-- Redis not found!
-- Found SQLite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so  
-- SpatialIndex not found!
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found JPEG: /usr/lib/x86_64-linux-gnu/libjpeg.so (found version "62") 
-- Found BZip2: /usr/lib/x86_64-linux-gnu/libbz2.so (found version "1.0.6") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.36") 
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Locale blacklist applied; Locales used: ar;ca;cs;da;de;dv;el;eo;es;et;eu;fil;fr;hu;id;it;ja;ja_KS;jbo;kk;kn;lo;lt;ms;my;nb;nl;nn;pl;pt;pt_BR;ro;ru;sl;sr_Cyrl;sv;sw;th;tr;uk;vi;zh_CN;zh_TW
-- Performing Test IS_AARCH64
-- Performing Test IS_AARCH64 - Failed
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/sdc1/04_games/minetest/minetest_5.2
</pre>

There are no compilation errors, and when i launch server :
<pre>
$ ./bin/minetestserver 
2020-04-25 14:47:40: [Main]: Automatically selecting world at [/mnt/sdc1/04_games/minetest/minetest_5.2/bin/../worlds/world]
2020-04-25 14:47:40: ACTION[Main]: Server: Shutting down
2020-04-25 14:47:40: ERROR[Main]: An unhandled exception occurred: Database backend postgresql not supported.
2020-04-25 14:47:40: ERROR[Main]: In thread 7f5994191ac0:
2020-04-25 14:47:40: ERROR[Main]: /mnt/sdc1/04_games/minetest/minetest_5.2/src/main.cpp:eb: int main(int, char**): A fatal error occurred: Database backend postgresql not supported.
</pre>

My world.mt :
<pre>
pgsql_connection        = host=127.0.0.1 port=5432 user=minetest password=minetest dbname=minetest_5_2
pgsql_player_connection = host=127.0.0.1 port=5432 user=minetest password=minetest dbname=minetest_5_2
backend        = postgresql
player_backend = postgresql
auth_backend   = postgresql
creative_mode  = false
gameid         = minetest
enable_damage  = true
</pre>

Is there a problem in the config file to define the backend?
Thank for your help.

**Comment by sfan5** [comment]
> `auth_backend   = postgresql`

There is no postgres auth backend (yet).

**Comment by d-stephane** [comment]
ok i just saw my mistake...The good config is :
<pre>
backend        = postgresql
player_backend = postgresql
auth_backend   = sqlite3
</pre>
And now it's ok...
