### ISSUE TITLE
Mistake in cosine lookup table in noise.cpp

### ISSUE THREAD

**Issue by k-al** [minetest/minetest#9757]
#### Summary
The cosine lookup table(cos_lookup) in noise.cpp has a 1.0f instead of -1.0f at the lowest point.
I don't know, maybe it could cause strange behavior.

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/c2f48eab4dfd352c391266b858378dd032d84a0f/src/noise.cpp#L49-L52

Fortunately, that table is entirely unused.

**Comment by k-al** [comment]
Then, should it be claend up?
