### ISSUE TITLE
Settings: Structure 

### ISSUE THREAD

**Issue by SmallJoker** [minetest/minetest#9758]
### Problems to solve

1) Unclear settings priority
2) Map settings take extra steps to get/set settings (confusing)
3) Integration of game/minetest.conf sucks - default settings are overwritten
4) Adding a world/minetest.conf would raise more questions (structure, priorities, API?)
5) Each setting "layer" (see list below) has different APIs

### List of settings (sorted by priority)

1) world/map_meta.txt -> `core.set_mapgen_setting` (etc)
2) world/minetest.conf -> to be implemented, issue #6966
3) Global minetest.conf -> `core.settings`
4) game/minetest.conf -> read-only, no scripting API (ok as-is)
5) defaultsettings.cpp -> read-only, only hacky workaround API available

### Concepts

Following code should demonstrate possible implementations on how to unify the settings structure. My goal is to remove `MapSettingsManager` and to expose the mapgen settings as `Settings` object to Lua.

#### 1: Global stack of settings

Introduce named layers, and an unified priority list.

```C++
// Sorted by priority
enum SettingType { SETTINGS_GLOBAL, SETTINGS_GAME, SETTINGS_DEFAULT, ... };

std::map<SettingType, Setting *> settings_map; // exposed by getter function only

class Settings {
	Settings(SettingType s_type, const char *filepath)
	{ /* add to settings_map */ }

	std::string getDefault(name)
	// Find first defined value in settings_map starting from s_type+1

	// m_defaults replaced by settings_map lookup
};
```

#### 2: Custom priority list

Suggested by @sfan5 http://irc.minetest.net/minetest-dev/2020-04-25#i_5675184
Each `Settings` has its own customized priority list.

```C++
class Settings {
	std::string getDefault(name)
	// Find first defined value in m_defaults

	std::map<int, SettingEntries> m_defaults;
};
```

**Comment by rubenwardy** [comment]
The world minetest.conf should override the global settings.

I think that the Lua APIs to set settings should only ever write to the world settings, to keep the API simple

**Comment by nerzhul** [comment]
minetest.conf global file is not intended to be modified by mods, they can alter the client settings in a client context.

**Comment by SmallJoker** [comment]
Changed the internal setting structure as I intended.
