### ISSUE TITLE
Rename “rightclick“ action to “interact”

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9766]
(This issue is only concerned about words and how we call certain things. It's not concerned about adding new features.)

## The problem

Minetest heavily relies on an action that is called “rightclick”, both player-facing and in the API, irregardless whether the player actually uses rightclick on the mouse or not. This “rightclick” action is used to:

* Build/place nodes
* Interact with the pointed node or object (open chest, open door, use a switch, etc.)
* Use the wielded item (special action in item def)

In the API, there are callbacks for that: `on_rightclick`, `right_click`.

However, this name is problematic as the *action* is referred to with the key that needs to be pressed. We can no longer rely on that this action is actually a rightclick. In Android, there is no mouse. Also, it has been planned since years to make the mouse buttons rebindable to any key.

Therefore, using the name “rightclick” to refer to a specific action is confusing and bad, and it should be changed.

## The solution

Therefore, I propose to change the name of the “rightclick” action to something that actually describes the action.

### Conceptual suggestion / overview

* The word “rightclick” shall from now on ONLY be used to refer to the clicking of the right mouse button. It should never be used to refer to a specific gameplay action
* The word “interact” shall from now on be used to refer interacting with nodes and objects, via the current `on_rightclick` / `right_click` callbacks, i.e. the interactions that are currently triggered when you rightclick a node or object

### Concrete suggestions

* Rename `on_rightclick` to `on_interact`
* Rename `right_click` to `interact`
* For backwards-compability: Keep supporting the old API names but deprecate them
* Hunt down other places in documentation where the word “rightclick” is use to describe interactions, and fix them accordingly

## Feedback
I am ready to post a PR myself. I ask you whether you agree with my complaints, and my solution.

**Comment by ClobberXD** [comment]
:+1: for getting rid of right-click.

About `interact`: I think the name is very vague and doesn't do a good job at describing the associated action - see also https://github.com/minetest/minetest/pull/7924#issuecomment-535540203. I suggest "Place" - it's very clear about what it refers to, even if it doesn't exhaustively describe all the stuff bound to that action.

**Comment by rubenwardy** [comment]
I'm not a fan of this new name. Rightclick may be inaccurate, but it's understood

One thing I'd quite like to see is a flow chart for inputs and callbacks, I find it hard to mentally visualise it all

**Comment by sfan5** [comment]
Agree with rubenwardy, "interact" is way too vague.
For example, what is the justification for left-click not being "interact"? If you need more than 10 words to sufficiently explain that, you lose.

**Comment by SmallJoker** [comment]
Duplicate of #2838

**Comment by paramat** [comment]
> However, this name is problematic as the action is referred to with the key that needs to be pressed.

I see your point, but if we refer to the 'action', because action can be almost anything (build, place, use, and anything registered with 'on right click', so not necessarily an 'interaction') this is also problematic and probably more confusing. 'Right click' is usefully abstract in meaning.

'Place' instead of 'interact' is even worse as it has a narrower meaning.
> In Android, there is no mouse.

But it is clearly understood what 'right click' means in terms of Android controls, or any alternative to a mouse.
> Also, it has been planned since years to make the mouse buttons rebindable to any key.

Even if 'right click' is bound to some other key by some users, it still seems reasonable to refer to it as 'right click', because most users will be still be using RMB or the Android equivalent.

I disagree the current situation is as bad as you claim, and the alternative suggested seems no better.
:-1:

**Comment by paramat** [comment]
This does not seem a duplicate of #2838 , but is related.

**Comment by v-rob** [comment]
I don't see the benefit of changing; `on_rightclick` has been around for a very long time and is ingrained in tons of mods.  Sure, we might be a bit more accurate, but deprecating something that tons of mods are using sounds like a bad idea IMO.

**Comment by rubenwardy** [comment]
> Sure, we might be a bit more accurate, but deprecating something that tons of mods are using sounds like a bad idea IMO.

We do this a lot, to improve API consistency without breaking mods. But it's not worth doing without a compelling new version

**Comment by Wuzzy2** [comment]
As there is so much hostiliy towards this suggestion, I close it now.

**Comment by rubenwardy** [comment]
It's not hostility! We agree that rightclick is a bad name, but think that interact is worse (and ambiguous)

**Comment by v-rob** [comment]
No, it's not hostility.  A lot of it is people making comments without thinking how they will be interpreted (including me).
