### ISSUE TITLE
gl_Normal issues with certain nodes in node shader

### ISSUE THREAD

**Issue by rdococ** [minetest/minetest#9773]
##### Minetest version

```
Minetest 5.2.0 release
```

##### OS / Hardware

Operating system: Windows 10
CPU: Intel Core i7-9700 CPU

GPU model: NVidia GeForce RTX 2070
OpenGL version: 4.6.0

##### Summary

gl_Normal is not set properly in the GLSL node vertex shader for certain nodes. These include flowing liquids, plantlike nodes and the kelp part of sand with kelp (I'm not sure what its drawtype is), but not meshes.

##### Steps to reproduce

1. Create a backup copy of your shaders folder, just in case.

2. Insert a line near the beginning of the node shader's vertex_shader.glsl file, written `variant vec3 surfaceNormal;`. Do the same with fragment_shader.glsl.

3. Put a line near the end of vertex_shader.glsl with `surfaceNormal = gl_Normal;`. (Oops - before the edit, I completely forgot this step)

4. Replace the `gl_FragColor = col;` line in fragment_shader.glsl with `gl_FragColor = vec4(surfaceNormal / 2 + 0.5, base.a);`.

5. Load a world and find some flowing liquid. Flowing liquid surfaces appear grey, instead of bright and colorful. This also applies to plantlike nodes. Since we modified the shaders to set the color based on an interpolated gl_Normal, this suggests that something's wrong with it.

![flowing water normal error](https://user-images.githubusercontent.com/3169568/80587784-133b0900-8a0f-11ea-93dd-84a21228d5e0.png)

**Comment by rdococ** [comment]
Some things I've found in the code. I think these two might be related to it:
https://github.com/minetest/minetest/blob/3f275d799cdcd61928854bb98ca5eb74af22f31e/src/client/content_mapblock.cpp#L576
https://github.com/minetest/minetest/blob/3f275d799cdcd61928854bb98ca5eb74af22f31e/src/client/content_mapblock.cpp#L950

I *think* this was done on purpose to avoid the normal-based face shading. That seems kind of odd to me - why not just have some system to disable it for certain things? For that matter, why isn't normal-based face shading and ambient occlusion handled in shaders when shaders are enabled?

**Comment by Zughy** [comment]
@x2048 @lhofhansl could you please one of you have a look at this? Unfortunately I don't know the matter enough to evaluate it

**Comment by x2048** [comment]
IIRC normals are not set to avoid face culling, because we use the same quad to render both side of a plant. We can change this once we optimize the renderer.

**Comment by Zughy** [comment]
I've just tried to test it but if I change those files nothing changes but these errors in the console (also, it's `varying`, not `variant`). I guess things have changed since the opening of this issue

![imagen](https://user-images.githubusercontent.com/63455151/174683045-8eab46f0-552b-4504-b3f0-f9ab3d17237a.png)
