### ISSUE TITLE
Player disappears while being punched: server crashes due to assertion failure

### ISSUE THREAD

**Issue by zeuner** [minetest/minetest#9780]
##### Minetest version

```
Minetest 5.3.0-dev (commit 91c4f7f0ea0b653d15bfabc05f5474f8fa1a8806)
```

##### OS / Hardware

Operating system: Debian GNU/Linux 10 (buster)
CPU: Intel(R) Core(TM) i7 CPU

##### Summary

I'm not sure whether the futility of an attempt to punch a player that just disappeared should be handled within the engine or the mod/game. But at the very least this is a documentation issue since the API documentation does not clarify under what circumstances the "punch" method may be called. Furthermore, I wonder whether it's justified to have the server crash in these cases, rather than just emitting a warning.

Anyway, this is what I get:

2020-04-29 21:27:03: ACTION[Server]: LuaEntitySAO at (69.4385,30.5,-41.939) (id=3924, hp=27) punched player test42 (id=3922, hp=13), damage=1
2020-04-29 21:27:04: ACTION[Server]: test42 leaves game. List of players: test76
2020-04-29 21:27:04: WARNING[Server]: ScriptApiBase::objectrefGetOrCreate(): Pushing ObjectRef to removed/deactivated object, this is probably a bug.
2020-04-29 21:27:04: WARNING[Server]: ScriptApiBase::objectrefGetOrCreate(): Pushing ObjectRef to removed/deactivated object, this is probably a bug.
2020-04-29 21:27:04: ACTION[Server]: LuaEntitySAO at (69.5644,30.5,-42.9622) (id=3925, hp=27) punched player test42 (id=3922, hp=12), damage=1
minetestserver: /home/minetest/minetest-provisorium03/minetest-fantasy/minetest-engine/src/server.cpp:1815: void Server::SendPlayerHP(session_t): Assertion `playersao' failed.

This happens with the "Lord of the Test" subgame. Might also be the case with other mods that implement mobs that attack players.

##### Steps to reproduce

This happens easily when logging out the player while it is attacked by a mob.

**Comment by SmallJoker** [comment]
Relevant code:
https://github.com/minetest/minetest/blob/3f275d799cdcd61928854bb98ca5eb74af22f31e/src/server.cpp#L1851-L1861

Last changed in 91eef646a5957

**Comment by zeuner** [comment]
The commit 91eef64 and the corresponding pull request #9390 suggest that this behaviour is on purpose. But then it should be documented how to use the "punch" method in order to avoid this.

**Comment by rubenwardy** [comment]
fixed in 87829cd7446dd13d1dfd27d96e0b4aeb2f234e33

**Comment by paramat** [comment]
Should this have been reopened?

**Comment by rubenwardy** [comment]
Yes, the commit in the op is after the fix

**Comment by sfan5** [comment]
The golden question here is: where did the mod receive the ObjectRef from so it could call `punch()` even after the player had left?

**Comment by zeuner** [comment]
@rubenwardy: Thanks for the information. It turned out that there may have been a confusion of the version running on the server since there were two servers running that game, one of which uses commit 3c0d30964315ad9e2cba2c6ade1260d8b35293da (5.2.0-dev). This would be before the fix (87829cd).

I tried to reproduce the bug on both servers, which has so far not succeeded.

Since it is possible that the bug is indeed already fixed, I suggest this to be closed. I can open another issue in case it happens again on a server which definitely runs a version past commit 87829cd, then hopefully with more information.

My apologies for the confusion.

**Comment by zeuner** [comment]
@sfan5: The mod stores the player object in a table slot of the mob.

**Comment by sfan5** [comment]
@zeuner 

https://github.com/minetest/minetest/blob/3f275d799cdcd61928854bb98ca5eb74af22f31e/doc/lua_api.txt#L5842-L5853
The implication of this advice is that the mod should rather be storing the player name and call `get_player_by_name` when a player object is required again.

**Comment by zeuner** [comment]
@sfan5: Great, thanks. This will help a lot getting this mod and possibly others more robust.

**Comment by rubenwardy** [comment]
> Since it is possible that the bug is indeed already fixed, I suggest this to be closed

This is good to hear :)
