### ISSUE TITLE
Policy for client-side scripting vulnerabilities (SSCSM)

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9782]
## Problem

With outdated distro versions, our normal policy to handle vulnerabilities may not be enough. Clients are typically much more out-of-date than servers.

The security of client-side scripting worries me. We're intentionally adding remote execution to the client, and I don't know if we have the resources to be absolutely confident in the security. Therefore, I think a system of informing users is necessary.

## Solutions

A soft kill switch. The client connects to minetest.net to check a JSON file. If there is an entry where the version number + build config (ie: LuaJIT or PUC Lua) matches, then two things happen:

* SSCSM can be completely disabled on the client. This can be re-enabled by user using a setting `secure.client_scripting_bypass_insecure_notice` or something
* A warning will be displayed somewhere

```json
[
	{
		"protocol_version": 40,
		"luajit": true,
		"kill": true,
		"message": "Client-side scripting has been disabled due to a vulnerability. Please update to 5.3.1"
	}
]
```

This end point could be combined with the update notification one

## Alternatives

No kill switch, just a warning

**Comment by sfan5** [comment]
Sounds reasonable to me.
Another question however is how distros will deal with such a check, would they want to patch it out? or disable it by default?

**Comment by rubenwardy** [comment]
> Another question however is how distros will deal with such a check, would they want to patch it out? or disable it by default?

It's not our responsibility, tbh
