### ISSUE TITLE
Collision info should contain references to collided objects.

### ISSUE THREAD

**Issue by Hume2** [minetest/minetest#9787]
## Problem

Recently, the on_step function has a new argument, the collision info. It's nice but one serious thing is missing. When the object collides with another object, it only receives that it has collided with A OBJECT but it doesn't get any information about what kind of object it is. It is quite common in games that colliding with different objects has different results. For example, when an arrow hits an animal, it should damage only the hit animal. If you do it vice-versa, the animal has to know somehow that it was hit by an arrow and not by a different object. Currently, there's no way to do this in any of those two ways.

## Solutions

Add a reference to the collided object into the collision info.

## Alternatives

I don't see any alternative solution here.

## Additional context

SuperTux :D https://github.com/SuperTux/supertux/blob/master/src/collision/collision_listener.hpp

EDIT by SmallJoker: Fix link.

**Comment by sorcerykid** [comment]
This is resolved by #9717 which includes a table of ObjectRefs in the move result.

You can see how this field is used in my Mobs Lite mod:

https://bitbucket.org/sorcerykid/mobs/src/master/init.lua#lines-1305

```
if #move_result.touched_objects > 0 and self.on_impact then
	for i, v in ipairs( move_result.touched_objects ) do
		self:on_impact( pos, old_vel, v )
	end
end
```
