### ISSUE TITLE
Image in 9-sliced item button is offset by 1px into border when pressed

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9790]
##### Minetest version
```
cb9a44ef8998ff66c00187efc508bf8bd6cc2d67
```

##### Summary
#9615 was closed recently, but not properly. If you now push an item button that is a 9-sliced button, the image inside the button might render above the border.
However, the goal of said issue is that the image stays inside the border at all times, not touching it.

##### Steps to reproduce
* Play MineClone 2 in Creative Mode
* Open inventory
* Click on the chest icon (survival inventory)
* Look at the item buttons

Here's a screenshot (scaled up 4 times):

https://satoshiupload.com/images/Bn6XgZHwbf.png

The upper button is pressed and overlaps with the border (wrong).
The lower button is not pressed and is rendered correctly.

@Df458

**Comment by Df458** [comment]
This is expected behavior, and `content_offset=0` should give you what you want. It's not on by default because I didn't want to change longstanding behavior. If the coredevs support doing so, we could set this value automatically when `border` is set to false.

**Comment by Wuzzy2** [comment]
How about setting `padding` to 1 by default?

https://satoshiupload.com/images/quLo5k7te1.png

That way, the “image moves when pressed” effect can be preserved and it won't overlap the border.

**Comment by Wuzzy2** [comment]
Oops, wrong image. Correct image:

https://satoshiupload.com/images/FEADM8TuZ2.png

**Comment by Df458** [comment]
> How about setting padding to 1 by default?

I see where you're coming from, but I'm not sure this is a good idea. Padding also affects a button's cut-off for elements like text, so this would solve your case while potentially creating other weird-looking cases. I also think it's the sort of thing that could result in someone else making a future issue like "default padding on 9-slice buttons is off by 1 pixel" or something.

At the end of the day though, I'm open to implementing either of the proposed solutions. I just want to get a consensus on this before acting.

**Comment by SmallJoker** [comment]
@Wuzzy2 Such points were best discussed in #9661, but that's now a bit late.

**Comment by v-rob** [comment]
Not a bug because it's expected behaviour.  Df458's thoughts are reasonable, and I also wish to add that `content_offset` can only be applied to both text and image, not just one or the other.  I think the most comprehensive solution would be a CSS pseudo-element for both text and fgimg, but that seems like it's going overboard.

Personally, I think the defaults are fine; adding more stipulations and strange defaults will just make it harder to remove the default style completely (ever tried removing the default style from a button in CSS?)
