### ISSUE TITLE
Minetest inventory shouldn't be shipped by default

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9791]
## Problem
An engine should offer the possibility to have GUIs and HUDs, but they shouldn't be implemented by default. Minetest has formspecs, but it doesn't mean it should have a preset inventory in its core. Not every game needs an inventory.

## Solutions

Remove the standard inventory (also because as for now it's a clear reference to Minecraft). It should be up to modders whether implement one or not

**Comment by SmallJoker** [comment]
The current inventory should be kept as a default, and empty formspecs should be handled after a `set_inventory_formspec()` call. Relevant code:

https://github.com/minetest/minetest/blob/cb9a44ef8998ff66c00187efc508bf8bd6cc2d67/src/client/game.cpp#L2082-L2089

Skip this part when `fs_src->getForm()` is an empty string.

**Comment by Zughy** [comment]
How about starting by removing the crafting area by default? It's very specific to survival games.
If I have a FPS, a platform or whatever I might need an inventory, but definitely not to craft

**Comment by SmallJoker** [comment]
@Zughy A few lines can do that for you. Example:
```Lua
minetest.register_on_joinplayer(function(player)
	local inv = player:get_inventory()
	inv:set_size("craft", 0)
	inv:set_size("craftpreview", 0)
	player:set_inventory_formspec([[
		size[8,7.5]
		list[current_player;main;0,3.5;8,4;]
	]])
end)

**Comment by ClobberXD** [comment]
I think Zughy wants the crafting setup disabled *by default*. I'm wondering if this is as simple as initialising these lists engine-side with zero size. Mods should explicitly set the lists to non-zero sizes and add support for them in the inventory formspec.

**Comment by paramat** [comment]
:-1: for the same reasons given in #10115 
I suspect the other core devs are also opposed to this request?

**Comment by Zughy** [comment]
Chiming in after #10115 to say SmallJoker idea looks a nice compromise

**Comment by paramat** [comment]
It seems obvious that core devs will disapprove this suggestion too becasue they disapprove #10115 , so closing.
