### ISSUE TITLE
set_bone_control broken when using set_animation 

### ISSUE THREAD

**Issue by Jordach** [minetest/minetest#9794]
##### Minetest version
```
https://github.com/minetest/minetest/commit/ac368af4fe27f61f5a4209cdfe90956ff745993c
```
##### Summary
Using animations with `player:set_bone_rotation()` are broken. The animation plays as expected (as the PR describes), while the animation flickers to the model's correct animation, and the models rotation on certain axis are incorrect.

##### Steps to reproduce
In `minetest.register_on_joinplayer()` use `player:set_animation()` and in a globalstep, using the same code as described in #9577.

The bone used in `set_bone_control` isn't keyframed.

I've tested b3d and x model formats with similar results.

This image is the model without using frame blending or `set_bone_control`
![image](https://user-images.githubusercontent.com/1439852/80870606-7a6eec80-8c9f-11ea-836a-5f61c7e62db5.png)

Touching either `set_bone_position` or using frame blending results in this:
![image](https://user-images.githubusercontent.com/1439852/80870661-d89bcf80-8c9f-11ea-87ed-b4355b614289.png)

Video of using `set_bone_position`:
https://gfycat.com/populartidygartersnake

**Comment by sfan5** [comment]
As I understand it the upside-down model isn't actually the bug here, since that can be fixed by messing with it otherwise(?).
The bug is that the bone position only snaps to the correct position (as added by the fix) for one frame once in a while and remains in the wrong position other than that.

also, @theviper121

**Comment by Jordach** [comment]
More information related to blender's exporting of armatures:

Blenders Bone edit mode poses a unique problem; in that it rotates bones in this state known as roll. This roll of the bone changes the *XYZ* heading of any bone that is a child of that bone, and also the bone itself. This causes the Irrlicht bug handler in content_cao.cpp to lose it's mind, due to the bones being erroneously rotated inside Blender, not the engine.

**Comment by theviper121** [comment]
Frame blending only works on some models now where as before it worked on none.  When you try to use it you may get the result pictured. I'm working to resolve this issue but it seems rather complicated and dependent on the model format.

**Comment by theviper121** [comment]
The fix I provided also runs every step and should not cause any issue except when used with frame blending on some models.
