### ISSUE TITLE
can mobs get pushed back when attacked?

### ISSUE THREAD

**Issue by kingsjack123** [minetest/minetest#9795]
## Problem

im finding it boring and aggravating when i go to attack mobs they do not get pushed back this makes the creeper from mine clone 2 a pain in the ass because it just blows up and can easily corner you. 

the result makes combat really stagnate or really unfair, in minecraft for example you hit mobs to create breathing room,especially with creepers.

## Solutions

add a fuction that enables a mob to be pushed back by a attack.

## Alternatives

to keep from simply copying minecrafts combat mechanics why not have the mobs try to strife when hit to mix up combat? 

## Additional context

i have no idea if mobs exist in the base game or if this is something moders must address.

**Comment by SmallJoker** [comment]
This should really be done within the mobs mod.

**Comment by sorcerykid** [comment]
Both sidestepping as well as knockback are made possible with #9717. The `set_speed_lateral()` method will allow for strafing motion and the `move_by()` method will allow for recoil motion.

**Comment by KaylebJay** [comment]
This is pretty easy to do within the mobs code. I did this for Tunnelers' Abyss and also made the mobs knock *you* back when they punch you. I think this should be closed because it is not an issue with minetest at all.

**Comment by rubenwardy** [comment]
Mob mods should implement this

**Comment by sorcerykid** [comment]
Mods shouldn't have to constantly re-implement the exact same trigonemetry calculations over and over for simple movement. That should be provided by the core API.

**Comment by rubenwardy** [comment]
No, but they should implement the calling of those trigonemetry functions in on_punch

**Comment by orbea** [comment]
I suggested this to TenPlus1 https://notabug.org/TenPlus1/mobs_redo/issues/47.
