### ISSUE TITLE
Switch the 'content_t' macro from 'u16' to 'u32'.

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9799]
## Problem
I think 32767 allowed nodes for registration currently is an insufficient amount (as to me) when you want to use tens of mods, especially those of which enable to produce a vast range of microblocks/slopes of the some blocks like "more_blocks", "mysiding", "mymillwork", "mydeck" and etc, as they register hundreds of the manufactured nodes. Besides, the newest version of "streets" mod (2.0) constraints the usage together with another heavy mods due to excessively large count of nodes what throws out an error thereafter, but if is that also wanted to use at the same time?

Also, lots current mods representing still colorful nodes like "homedecor", "summer".

## Solutions
Making 'content_t' macro u32 type is the most reliable way to avoid the unexpected overflow in the described cases above as it would allow to register exactly 2,147,483,647 nodes + spare space for unknown ones. I hope will it not cause a breakage the maps that generated before?

**Comment by SmallJoker** [comment]
I've seen this request one or two years ago, but cannot find a corresponding link.
`Number of registerable nodes` `MAX_REGISTERED_CONTENT` all yield no results.

**Comment by Andrey2470T** [comment]
Maybe add some option for selecting how many bits it is necessary to allocate for a mapnode in the create world menu? For example, acceptable values will be '16' and '32'. It can not be changed subsequently, only the only way is to create other world with other value. Thereby it won`t break the backward compatibility, I think. Default value will be '16'.
