### ISSUE TITLE
Rename the `build` folder to avoid conflicts with the commonly chosen CMake build folder name

### ISSUE THREAD

**Issue by Calinou** [minetest/minetest#9800]
## Problem

When building a CMake-based program, I tend to use `build` as the build folder name. However, this clashes with the existing `build` folder present in the Minetest repository. As a workaround, I have to name my build folder `build2`, unlike any other CMake program I've built. I also have to add it to `.git/info/exclude` to avoid accidentally committing it.

All this requires a bit more muscle memory, and I can't use a command alias anymore :)

## Solutions

Rename the `build` folder to something else like `platform`, or move its contents to the existing `misc` folder.

**Comment by ClobberXD** [comment]
Or we could maybe bring out `android` to the root dir?

**Comment by orbea** [comment]
Fwiw you can still use the `build` directory and just ignore the android directory inside, although I do strongly agree its a poor place to put android files.

**Comment by nerzhul** [comment]
i think it can be a good idea too to move the android folder to root

**Comment by numberZero** [comment]
`platform/android` is better IMO. We may want special handling for other platforms as well (e.g. building `msi` for Win32). Wait, we **do** have platform-specific stuff already, spread across root and `misc`: `AppImageBuilder.yml`, `kubernetes.yml`, `winresource.rc`, whatever. The only platform-independent file in `misc` seems to be `minetest.svg` =)
