### ISSUE TITLE
Add in game timer

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#9801]
It would be cool for game or adventure map to can add a Minecraft-like timer by a command, like:
_/timer "name" new_ : add a timer with a name
_/timer "name" start_ : start the timer
_/timer "name" stop_ : stop the timer
_/timer "name" reset_ : restart the timer
In Minecraft:
![Capture](https://user-images.githubusercontent.com/61794590/80916573-d0a06600-8d59-11ea-8044-f897273b8db2.PNG)

**Comment by rubenwardy** [comment]
This is best done using a mod or as part of a game, not in the engine
