### ISSUE TITLE
Add hardware keyboard support to Android

### ISSUE THREAD

**Issue by Eternal-plasma** [minetest/minetest#9803]
## Problem
On Android the keyboard support is minimal but I like to play on 2in1 tablets  
## Solutions
Add keyboard support to the app 
(I know how hard things can be to add so please don't take this the wrong way )

**Comment by MoNTE48** [comment]
Duplicate: https://github.com/minetest/minetest/issues/8879

**Comment by MoNTE48** [comment]
I thought about it. Along with the adding of support for Chromebooks (Chrome OS)...
But Android has so many problems now that getting lost in Irrlicht trying to fix this seems like a low priority to me.
