### ISSUE TITLE
Bone animations broke between client versions

### ISSUE THREAD

**Issue by IhrFussel** [minetest/minetest#9807]
##### Minetest version

```
Server: 5.1.1
Client: 5.3.0-dev
```

##### OS / Hardware

Operating system:
CPU: Intel Dual Core

GPU model:
OpenGL version:

##### Summary

I use the 'playeranim' mod on my server and with a 5.1.1 client the player model looks fine, but with a newly compiled dev client it looks totally glitched.
![IMG-20200504-WA0020](https://user-images.githubusercontent.com/22120097/80971987-d19acb80-8e1d-11ea-80b5-eb0d6e41a383.jpg)

**Comment by sfan5** [comment]
Does the problem happen with 5.2?

**Comment by IhrFussel** [comment]
No, it looks normal with a 5.2.0 client.

The bug happened after 5.2.0 release.

**Comment by sfan5** [comment]
A recent commit that touched this code is e1fc72c6f3450c82e2dd3e0892838498a6a8a092, but since you didn't provide the exact version of `5.3.0-dev` you used I can't tell if that could be the cause.

**Comment by IhrFussel** [comment]
I used cb9a44ef

**Comment by An0n3m0us** [comment]
Confirmed; `5.3.0-dev-f34c62c-dirty`
![MT-9807](https://user-images.githubusercontent.com/49789044/81060704-e5e8d200-8eca-11ea-87e5-8536541885ba.png)

Walk animation:
https://my.pcloud.com/publink/show?code=XZ2pWlkZ9OySyiepvGR3YQivIdhI14DTI3JX

**Comment by LoneWolfHT** [comment]
playeranim changes all bones at once. The bone fixes probably broke it

**Comment by LoneWolfHT** [comment]
Try this in a mod:
```lua
minetest.register_globalstep(function(dtime)
	for _, player in pairs(minetest.get_connected_players()) do
		player:set_bone_position("Head", vector.new(0, 6.75, 0), vector.new(-math.deg(player:get_look_vertical()), 0, 0))
	end
end)
```

**Comment by SmallJoker** [comment]
@theviper121 By any chance, would you have some time to look into this issue?

**Comment by theviper121** [comment]
I will see what's going on tonight.

**Comment by theviper121** [comment]
Alright so the code changes certainly brought a issue to the surface. Playeranim relied on the animation to be broken when a bone position was set manually. Now that animations and manual bone positioning work together the mod is broken.

**Comment by SmallJoker** [comment]
I can't imagine a good way to make this somehow backwards compatible. What if new servers stop sending bone animations to older clients?

**Comment by theviper121** [comment]
The only way I can think to make it backwards compatible would be to not animate manually positioned bones by default and allow the server to enable it.

**Comment by IhrFussel** [comment]
I would actually even accept an option that is enabled by default and can be disabled server side.

Just in case people want the new fixed behavior more.

**Comment by theviper121** [comment]
If I can find the time I will try to add the option to stop animation when setting bone position.

**Comment by hecktest** [comment]
Does #10015 fix it?

**Comment by hecktest** [comment]
Don't try to make this compatible with broken behavior, instead add an option to set a bone's transform in a different space, like object space or even world space.

**Comment by sfan5** [comment]
As previously hinted this is not an engine bug, but rather broken behaviour that playeranim relied on.

You can continue using playeranim with this fix, it is compatible with 5.x and 5.3 at the same time. (thanks to @hecktest for suggesting to turn off animation):
https://github.com/minetest-mods/playeranim/commit/ae45fe4cca25b7b21d00d894ed72a44de09704dd
