### ISSUE TITLE
image_waypoint isn't working 

### ISSUE THREAD

**Issue by G1ov4** [minetest/minetest#9810]
I'm on minetest 5.2 and I'm trying to add an image_waypoint, but it doesn't work:
1. It doesn't show any image, but instead it shows a text, as you can see here 
<a href='https://postimg.cc/ygY0FrxZ' target='_blank'><img src='https://i.postimg.cc/ygY0FrxZ/image-waypoint.png' border='0' alt='image-waypoint'/></a>

  2. The position is wrong, it should be placed to the other player position

  3. If I use a normal waypoint it works, so the player's position is right

Here is my code:	

```
waypoint = player:hud_add({
 hud_elem_type = "image_waypoint",
 world_pos  = target_pos,
 text      = "HUD_waypoint.png",
 scale     = { x = 3, y = 3},
})
```

**Comment by rubenwardy** [comment]
Image waypoints have not been released yet. They were added in 5.3.0-dev, and so will first appear in 5.3.

Make sure to select the lua_api.txt version that matches your MT version. Here's the one for the latest stable 5 version: https://github.com/minetest/minetest/blob/stable-5/doc/lua_api.txt#L1351
