### ISSUE TITLE
Rename speed to velocity in moveresult

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9811]
From the API: `old_speed = vector, new_speed = vector`. This is misleading; speed usually is a single number, those are referring to velocities.

Should be called `old_velocity = vector, new_velocity = vector`. Please rename before 5.3 so that we don't get backwards compatibility issues.

**Comment by GreenXenith** [comment]
Alternatively, `old_vel` and `new_vel`.

**Comment by rubenwardy** [comment]
It should be `velocity` because the API doesn't use `vel` anywhere

**Comment by appgurueu** [comment]
I'd rather go with `velocity` as long as the corresponding methods are `set_velocity` and `get_velocity`.
