### ISSUE TITLE
minetest fails to save any screenshots if screenshot folder is set to /tmp

### ISSUE THREAD

**Issue by imre84** [minetest/minetest#9815]
##### Minetest version

```
Minetest 5.2.0 (Linux)
```

##### OS / Hardware

Operating system: Ubuntu 19.10
CPU:Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz

GPU model:
OpenGL version:

##### Summary

$subject

##### Steps to reproduce

1. change settings->all settings->graphics->menus->screenshot folder to /tmp
2. press your screenshot key (f12) in-game 

##### Current behaviour
the game will say something like "Saved screenshot to '/tmp/screenshot_20200505_045059.png'"
the screenshot isn't saved anywhere no matter what is being said in the line above

##### Desired behaviour
the screenshot is actually saved to the location stated by that line

**Comment by KaylebJay** [comment]
I believe I was able to recreate this, it was about a week ago. I wasn't sure if it was my fault or the game though.

**Comment by An0n3m0us** [comment]
I cannot recreate this on `Minetest 5.2.0` or `Minetest 5.3.0-dev-8b45f6a-dirty`

**Comment by imre84** [comment]
I can reproduce 100% of the time.

**Comment by LoneWolfHT** [comment]
Can't reproduce with Minetest 5.3.0-dev-31eb1d7d9
I'm on Xubuntu 19.10

Could it be you don't have write privs or something?

**Comment by imre84** [comment]
I surely have write privileges

**Comment by imre84** [comment]
ok, I figured out what is happening: the screenshot gets saved to /tmp/snap.minetest-luk3yx/tmp (instead of /tmp) which in confusing and unexpected for me, but at least now I know

correct me if I'm wrong, but I suspect this is not a minetest issue then, but rather a snappy related issue

**Comment by imre84** [comment]
and I wasn't able to find because root rights are neccessary for find to traverse into that directory
