### ISSUE TITLE
Freezing my whole windows system

### ISSUE THREAD

**Issue by speccius** [minetest/minetest#9817]
##### Minetest version

```
minetest-5.2.0-win64
```

##### OS / Hardware

Operating system: Windows 8.1 Pro
CPU: Intel i3-5010U 2 Core 4 Thread 2.1GHZ 64-bit
RAM: 1 x 4GB

##### Summary

Using the Karsthafen_subway_V3 map, and sometimes others, my laptop has a tendency to freeze entirely while playing minetest.
Every time, the display freezes, and it won't respond to keypresses or the power button. The disk is still audibly doing something and the activity light is stuck on.. The only way to clear this is to forcibly power off the system (which scares me with the disk light on), even leaving it overnight didn't help. Yesterday I updated all my drivers that I could and set my virtual memory back down to default, no luck, still happens, even when sitting minimised on the title screen.

##### Steps to reproduce

Open the Karsthafen_subway_V3 map with this configuration, sometimes normal worlds, intermittent fault.

**Comment by rubenwardy** [comment]
Please may you open a task manager and check the ram use during?

You might need to lower the mapblock limit

**Comment by DanielTheGreatinc** [comment]
Is your version of Minetest from the official site? Sometimes getting an executable from a non-official source can result in an infected file, which can "freeze" your system while doing something nefarious.

**Comment by paramat** [comment]
@speccius ^

**Comment by speccius** [comment]
Yes, I did get it from the real site, and virus scans show it's safe. CPU, RAM, and disk usage stays normal up to the point where it freezes.

**Comment by speccius** [comment]
I have upgraded the laptop to 8 gigs of ram since then and will test it again

**Comment by benrob0329** [comment]
Could you link to the map you seem to be having trouble with?

**Comment by SmallJoker** [comment]
@speccius Are your graphics drivers up to date? Would you please be so nice to check whether this is still a problem?

If available RAM is not the problem, I guess it's a driver problem rather than Minetest's fault.

**Comment by rubenwardy** [comment]
no reply from OP

**Comment by thevbw** [comment]
I don't know why I never got notifications for this thread - laptop has since been upgraded, probably went OOM at the time
