### ISSUE TITLE
Formspec Background Tag scaling Issue

### ISSUE THREAD

**Issue by ExeVirus** [minetest/minetest#9822]
##### Minetest Version 

```
5.2.0
```

GPU model: AMD APU
OpenGL version:4.5.13399

##### Summary
I am working on formspec dialog boxes in the style of pokemon and am having their width scale with the length of text needed. What I noticed is that on small width sizes, the formspec size was about 4 pixels larger than a background of equal size. This makes some design sense so I wasn't unhappy about that:

![image](https://user-images.githubusercontent.com/44562154/81125806-4269e280-8f07-11ea-9a7b-cb513ef2087f.png)

The issue is when a lot of text is entered, the edge of the background element start to scale larger than the formspec size (even though they are the same value):

![image](https://user-images.githubusercontent.com/44562154/81125865-865ce780-8f07-11ea-8247-4dc71ccbf906.png)

# Steps to reproduce

So this is actually pretty easy to reproduce, here is my code, both textures (at bottom), and the command to test with (works on any server unless there is a chat command collision):

Dialog Box Function:
(textures included at the bottom, white.png is a single white pixel)
```
function show_dialog(name,text)
    local formspec
    --local random = PcgRandom(minetest.get_us_time()) --Should help with collisions between formspecs
    math.randomseed(minetest.get_us_time())
    local length = string.len(text) / 3.3
    local size = tostring(length)
    local width = tostring(length-0.2)
    local rn = math.random(200000000)
    local rn2 = math.random(200000000)
    text = "<style color=#0000FF size=30 font=normal>" .. text .. "</style>"
    local formspec = {
        "formspec_version[3]",
        "size["..size..",1.2]",
        "position[0.5,0.8]",
        "anchor[0.5,1]",
        "bgcolor[#000000;false]",
        "background[0,0;"..size..",1.2;white.png]",
        "hypertext[0,0.3;"..size..",1.2;forms;", minetest.formspec_escape(text), "]",
        "animated_image[0,0 ;"..size..",1.2; ;show_text.png; 25 ; 75]",
    }
    local formspec2 = {
        "formspec_version[3]",
        "size["..size..",1.2]",
        "position[0.5,0.8]",
        "anchor[0.5,1]",
        "bgcolor[#000000;false]",
        "background[0,0;"..size..",1.2;white.png]",
        "hypertext[0,0.3;"..size..",1.2;forms;", minetest.formspec_escape(text), "]",
    }
    minetest.show_formspec(name, "mesemon:"..tostring(rn)..tostring(rn2) , table.concat(formspec, ""))
    minetest.after(1.9, function(name, formspec)
        minetest.show_formspec(name, "mesemon:"..tostring(rn)..tostring(rn2) , formspec)
    end,name, table.concat(formspec2, ""))
end
```
Chat Command:
```
minetest.register_chatcommand("dialog", {
    params = "<text>",
	description = "Test Dialog Boxes",
	privs = {interact=true},
	func = function(name, param)
        show_dialog(name, param)
    end
})
```
Impossible to see images below this text, links included
![show_text](https://user-images.githubusercontent.com/44562154/81126001-f0758c80-8f07-11ea-8d12-61f414e1a17f.png)
https://user-images.githubusercontent.com/44562154/81126001-f0758c80-8f07-11ea-8d12-61f414e1a17f.png  (show_text.png)
![white](https://user-images.githubusercontent.com/44562154/81126003-f0758c80-8f07-11ea-9759-782060991a2e.png)
https://user-images.githubusercontent.com/44562154/81126003-f0758c80-8f07-11ea-9759-782060991a2e.png  (white.png)

**Comment by SmallJoker** [comment]
Please use `background9` to avoid general scaling issues as reported in #2419.

**Comment by rubenwardy** [comment]
This isn't a bug, please use background9
