### ISSUE TITLE
Add position offset parameter to `set_detach`

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9825]
## Problem

In MTG, when you rightclick on a boat you're attached to, you detach. MTG also wants to apply a small Y offset, it teleports you slightly upwards. This code exists so the player stands safely on the boat after detaching. Good idea.

The ugly part in the code is that the teleportation is not done immediately, but with a `minetest.after` delay of 0.1 seconds. Because apparently if you call `set_pos` immediately after `set_detach`, it doesn't work. :-(

In my testing, this MTG hack is also unreliable. Sometimes, the teleportation is too slow and I still fall below the boat …

Yeah, IMO the `minetest.after` delay is a hack. However, it's a neccessary hack in MTG, as there is no better way to implement it for now. At least I don't know better.

## Solution

Add an optional position `offset` parameter into `set_detach`. `offset` is a vector.

If set, the player's position will be immediately changed to (`current_player_position` + `offset`) after detaching. If not set, `set_detach` behaves as usual.

This should allow MTG to reliably (!) and immediately (!) move the player on the boat after detaching.

**Comment by SmallJoker** [comment]
> Because apparently if you call set_pos immediately after set_detach

Indeed. Attachments are updated only each server step (entity step):

https://github.com/minetest/minetest/blob/4f9a5f67ee745d78fdc3e173972a3df110f989cf/src/server/luaentity_sao.cpp#L255-L261

Changing this might make sense to fix the `minetest.after` issue without any API needed.

**Comment by Wuzzy2** [comment]
Soooo …
The real fix would be to update attachments right before `set_pos` is handled?

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/3ce03d1c2a63d261c83f5962cd13212697f19472/src/server/player_sao.cpp#L338-L340
`sendOutdatedData()` could be added in between to force sending the attachment data before the "force movement" packet is sent. Will test this.

**Comment by gpcf** [comment]
This sounds very much like the bug some players are seeing with advtrains, where they can't get off trains or get dropped onto the tracks.
