### ISSUE TITLE
Port Minetest to Godot Engine

### ISSUE THREAD

**Issue by sebastienhasa** [minetest/minetest#9835]
Actually, Minetest is based on Irrlicht game engine. 

But this engine start to be old and I read that Irrlicht had some limitations:

* No Post-processing shader (#5446)
* Can't manage bones correctly (#1800)
* Import only outdated mesh formats (#9673)
* No Wayland support (#9686)
* …

And there is probably other limitations.

What do you think about port Minetest to another game engine, like Godot?

I know it would be a lot of work, but Godot is more modern and actively developed.

**Comment by rubenwardy** [comment]
Irrlicht is a graphics wrapper. Minetest is a game engine

Godot has a drastically different design to irrlicht, as it is a game engine not a library. It's not possible to port from one to another, you'd need to rewrite

**Comment by nerzhul** [comment]
i studied it in the past, and it consist in a massive rewrite of minetest.
I think overwriting irrlicht is currently our best option

**Comment by tacotexmex** [comment]
As usual in these topics it’s worth pointing out that IrrlichtBAW is both more modern and maintained.

**Comment by nerzhul** [comment]
it can be an option but it has heavy modifications, it's not compatible with irrlicht 1.8 or 1.9

**Comment by appgurueu** [comment]
We should consider cherry-picking commits, opening an issue

**Comment by Seirdy** [comment]
Another place to consider would be SuperTuxKart's work on Antartica, which is based on a heavily modified version of Irrlicht: https://supertuxkart.net/Antarctica:_Technical_Details

**Comment by romulasry** [comment]
Nabla would work.
