### ISSUE TITLE
Add a way to visually communicate emotion to other players

### ISSUE THREAD

**Issue by sebastienhasa** [minetest/minetest#9836]
Actually, if you want to communicate with other players in game, you only have the text chat.

But what about adding a way to communicate emotion in a more visual way? 
The game would let the player choose between a set of emotions. When an emotion is selected, the player model express this emotion with an animation, a specific face expression and maybe a sound.
Something like what we got on Animal Crossing New Horizons.

This would add an interesting way to communicate with other players.

**Comment by NathanSalapat** [comment]
There is a mod that adds this.
https://forum.minetest.net/viewtopic.php?f=9&t=23254

**Comment by SmallJoker** [comment]
Chat helpers can also be implemented in CSMs using `minetest.send_chat_message` in combination with formspecs and mod channels if the server has a mod counter-part.

**Comment by KaylebJay** [comment]
This IMO has nothing to do with minetest core and is something modders should do.

**Comment by rubenwardy** [comment]
This is for mods/games to do, and not the engine
