### ISSUE TITLE
Spawn block breaking particles

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9840]
It would create a lot of aesthetic opportunities in mods to be able to create block breaking particles as if the player broke the block.

**Comment by sfan5** [comment]
The code that does this is here: https://github.com/minetest/minetest/blob/master/src/client/particles.cpp#L593
I almost wanted to suggest recreating this in Lua, but the `texpos`, `texsize` and `color` attributes are not available to Lua.

**Comment by ClobberXD** [comment]
`texpos` seems to be calculated from `texsize`, so "accessing" it from Lua doesn't seem to be an issue. However, I wonder what the performance impact of calling `math.random` to calculate `texpos` for every particle is going to be...

Does `color` refer to hardware colouring? If so, wouldn't this be accessible via node meta?

**Comment by KaylebJay** [comment]
Highly in favor of this feature. It'd open up a lot of possibilities.

**Comment by Warr1024** [comment]
I use a hack workaround to do this in NodeCore for pummel particles.

https://gitlab.com/sztest/nodecore/-/blob/master/mods/nc_api/fx_digparticles.lua

This method is limited and buggy, and requires a ^[resize texture modifier that forces all textures to 16x, so it can't faithfully represent high-resolution texture packs.  Having an official way to do this would be much better.

I would still like to be able to control the physics/movement of the particles.  I'd also like to be able to use a particlespawner to create a bunch of them at once without sending individual particles, but I'd like them to vary individually like dig particles do.  This suggests that a ^[dig_particle_mask kind of texture mod wouldn't work, and it'd have to be a first-class feature of particles/particlespawners.
