### ISSUE TITLE
All Settings menu: Invalid error report when editing or saving mapgen noise parameters, cannot edit mapgen noise parameters

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9841]
Occurs in recent master 454dbf83a9bf292910c1495a2aa49fd8b960c28f

To reproduce:

Enter All Settings menu.
Mapgen > Mapgen V7 > Noises.
Select 'Terrain base noise' and 'Edit'.
Edit any noise parameter value, or even make no change at all.
Save.

Result:

![Screenshot from 2020-05-09 18-19-26](https://user-images.githubusercontent.com/3686677/81480667-085c5180-9223-11ea-9506-c830c0abd20f.png)

That message displays when 'Offset' is a number.

**Comment by paramat** [comment]
Does not occur in 5.2.0.

**Comment by SmallJoker** [comment]
I wonder whether strings that can be converted to a number should be accepted in `getfloatfield()`.
There were some similar cases where string values were passed even though they should pass a number value according to the API.

**Comment by paramat** [comment]
Seemingly related problems discussed in IRC http://irc.minetest.net/minetest-dev/2020-06-02#i_5696848

**Comment by sfan5** [comment]
Yes, should be fixed since 42a9b45c21ad407689950e3a4c90cb3894142260.

**Comment by paramat** [comment]
Will test.

**Comment by paramat** [comment]
Confirmed fixed, thanks for the fix.
