### ISSUE TITLE
Opaque waving leaves allow seeing through geometry

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#9842]
##### Minetest version
```
Minetest 5.3.0-dev-7cb53791c (Linux)
Using Irrlicht 1.8.4
```

##### Summary
This can be triggered with MTG leaves by setting `leaves_style = opaque`.
![screenshot](https://user-images.githubusercontent.com/1042418/81484237-4027c100-9244-11ea-9250-9660e964322e.png)

**Comment by SmallJoker** [comment]
https://github.com/minetest/minetest/blob/7cb53791c3a6547164a9f8eae10ae8a2e2ddecdb/src/client/mapblock_mesh.cpp#L661-L663

needs access to `TextureSettings` which is created in `NodeDefManager`. It could be changed to a class member and exposed to the function above.
