### ISSUE TITLE
Incorrect background color when inside a cloud.

### ISSUE THREAD

**Issue by lhofhansl** [minetest/minetest#9846]
This is with the tip of the master branch.

See screenshot (flying inside a cloud looking down):
![screenshot_20200510_101341](https://user-images.githubusercontent.com/446130/81506632-8f094100-92ac-11ea-9c03-01d996aeeba2.png)

Notice how the color does not match the background showing the ragged edges.

This fixes it (but I'm not sure that was intended):
```
diff --git a/src/client/game.cpp b/src/client/game.cpp
index 4d7a85526..5df9fa50c 100644
--- a/src/client/game.cpp
+++ b/src/client/game.cpp
@@ -3789,7 +3789,7 @@ void Game::updateFrame(ProfilerGraph *graph, RunStats *stats, f32 dtime,
                                // color(s)
                                video::SColor clouds_dark = clouds->getColor()
                                                .getInterpolated(video::SColor(255, 0, 0, 0), 0.9);
-                               sky->overrideColors(clouds_dark, clouds->getColor());
+                               sky->overrideColors(clouds_dark, sky->getBgColor());
                                sky->setInClouds(true);
                                runData.fog_range = std::fmin(runData.fog_range * 0.5f, 32.0f * BS);
                                // do not draw clouds after all
```

**Comment by sfan5** [comment]
I believe this is intentional, when you are inside a cloud you only see near terrain and everything else is white.

**Comment by lhofhansl** [comment]
That's not what I meant... The background color does not match the fog color, so instead of seeing a smooth horizon ones sees the edges of the loaded chunks.

Looked a bit more. The problem is here:
https://github.com/minetest/minetest/blob/master/src/client/sky.cpp#L215

From commit 946c03c69bfdde7dc91295692479f8e81bdf79e9

When we're in the clouds we no longer draw the sky box. Hence bgColor is the right color to set.

**Comment by lhofhansl** [comment]
I suppose this issue was always present. Now it's just more pronounced now.

We do have the fog to hide the ragged borders, so this kinds defeats the purpose.

**Comment by sfan5** [comment]
My first comment wasn't precise enough, I think the visible rest-of-the-terrain is a feature.
However you are right that not seeing it would be more realistic. The only possible issue I see with that is that players flying through clouds are left completely without any means to navigate.

**Comment by paramat** [comment]
See https://github.com/minetest/minetest/pull/6003#issuecomment-313080719 for previous behaviour.
It seems that the loaded world edge was always abrupt and non-fading, but this was only noticeable seen against the brighter upper sky colour. Now it is noticeable against the lower sky colour too.

So this does seem a bug / change of behaviour, and was probably something forgotten and not tested in the set_sky PR.
The previous behaviour looked better so i think we should return to that.
I will test the suggested fix.

**Comment by lhofhansl** [comment]
Thanks @sfan5 and @paramat . And "Hi" :) Has been a while.

My fix does _not_ restore the prior behavior, though. My change would remove the nice silhouette effect.

I think we should undo that one line from 946c03c that I pointed out above.

But then again, that change is in there for a reason:
```
// Abort rendering if we're in the clouds.
// Stops rendering a pure white hole in the bottom of the skybox.
```

Perhaps @Jordach has some ideas...?

**Comment by paramat** [comment]
Ok, i hope we get some input from Jordach.

**Comment by Jordach** [comment]
I'm going to need a *much* better screenshot with contrast that's almost within 10 brightness in HSV away from each other, as that does not show the issue, nor is it highlighted.

**Comment by lhofhansl** [comment]
@Jordach The issue is when fog is enabled. The first screenshots shows is nicely, but I'm attaching two more here.
The fog is meant to hide the corners of the world (where you can see the mapblocks).

![screenshot_20200531_143128](https://user-images.githubusercontent.com/446130/83363130-e5b5e800-a34b-11ea-977b-41c010a07139.png)
![screenshot_20200531_143129](https://user-images.githubusercontent.com/446130/83363131-e64e7e80-a34b-11ea-8058-75edae60e6c8.png)

These shots are from almost the exact same point (one just inside the cloud, one just below it).
See how it messes up the fog and you now see the corners (which the fog nicely hides), check the middle specifically where you can see the last mapblocks and the ragged side from that - that part is what the fog is supposed to hide. (You can suddenly see further inside the side.)
This is caused by the change I mention above.

**Comment by lhofhansl** [comment]
So what do we do about this - if anything?

**Comment by sfan5** [comment]
Nothing?
