### ISSUE TITLE
Players dead message

### ISSUE THREAD

**Issue by AFCMS** [minetest/minetest#9850]
It is useful to allow games to add custom dead message, with, for example, the reason of the death.

**Comment by sfan5** [comment]
Already exists via `minetest.register_on_dieplayer()`.

**Comment by ClobberXD** [comment]
I'd ideally like to be able to disable the builtin death screen and roll with a custom one. Is this possible?  If not, it might be worth asking the OP if this is the feature they requested.

**Comment by sfan5** [comment]
I was thinking of death messages in chat, not a death screen.
If OP means the death screen then this is a valid feature request (the death screen is 100% client-side currently).

**Comment by KaylebJay** [comment]
If you enable client-side modding and edit your death message, you can change it to whatever you like.

**Comment by ClobberXD** [comment]
> It is useful to allow games to add custom dead message

@KaylebJay I'm assuming this is a feature request for server-side death formspec customisation. If this issue is about customising death formspec via CSM, I agree that this issue is indeed invalid.
