### ISSUE TITLE
Minetest.camera:get_pos() returns pos with wrong decimal place

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9857]
For example: if player position is:
x= -1285.9
y=3.5
z=1576.5

then minetest.camera reports the camera adjusted position as:
x = -12858.57421875
y = 49.700000762939
z = 15765.104492188

**Comment by rubenwardy** [comment]
Looks like the camera API doesn't divide by BS (=10)

**Comment by oilboi** [comment]
👍
