### ISSUE TITLE
Proposal: change default ambient occlusion gamma to 1.4

### ISSUE THREAD

**Issue by sfan5** [minetest/minetest#9865]
## Problem

Minetest has had ambient occlusion for a long time, but in the default settings it barely takes any effect. The shading is very subtle making terrain look very bright, which doesn't look good and isn't realistic.

## Solutions

Change the default value of `ambient_occlusion_gamma` to 1.4.

## Additional context

Top screenshot = before, bottom screenshot = after.
Opening images in fullscreen is recommend.

![screenshot_20200515_130445](https://user-images.githubusercontent.com/1042418/82045239-09700180-96af-11ea-9e6d-09d7a5b12841.png)
![screenshot_20200515_130414](https://user-images.githubusercontent.com/1042418/82045242-0d038880-96af-11ea-8a7a-c8dde15680a2.png)

![screenshot_20200515_120014](https://user-images.githubusercontent.com/1042418/82045214-007f3000-96af-11ea-8b7c-10add26a8e79.png)
![screenshot_20200515_115946](https://user-images.githubusercontent.com/1042418/82045220-0412b700-96af-11ea-8c0d-70b843bf4a87.png)

**Comment by SmallJoker** [comment]
Yes, the additional contrast using `1.4` adds more depth to the scene.

**Comment by paramat** [comment]
Looking at the screenshots, i find the new value looks excessively strong, causing excessively dark corners.
I also disagree that the current value has little effect, it seems to have a significant effect already.
A slight increase might be ok but this seems too much.
It has more depth and contrast yes, but that does not mean it is ok.
I should test in-game though.

**Comment by paramat** [comment]
1.4:

![screenshot_20200517_005952](https://user-images.githubusercontent.com/3686677/82132674-1fc6ac00-97da-11ea-981c-5274a0c2cdcc.png)

![screenshot_20200517_005518](https://user-images.githubusercontent.com/3686677/82132676-26552380-97da-11ea-8761-c6a39376a8a2.png)

![screenshot_20200517_005601](https://user-images.githubusercontent.com/3686677/82132744-02dea880-97db-11ea-8a48-d5181e3e44d3.png)

I tested by removing the textures folder from MTG, to get non-distracting plain colours.
1.4 is too dark for me, going back to the current default afterwards looked much better, and is not a weak effect at all.
So :-1: for 1.4 but a more subtle change might be ok.

The fact that we have had very few complaints about the strength of ambient occlusion suggests we already have a well chosen value that satisfies most players.

**Comment by sfan5** [comment]
> I tested by removing the textures folder from MTG, to get non-distracting plain colours.

But isn't the shading supposed to look good *with* textures?

> So :-1: for 1.4 but a more subtle change might be ok.

What about 1.6 or 1.8 then?

You're correct that 1.4 is a radical change, but you get used to it in normal gameplay very fast and it just looks better IMO.

> The fact that we have had very few complaints about the strength of ambient occlusion suggests we already have a well chosen value that satisfies most players.

Not really. Most players will not be aware of the ambient occlusion settings, still notice that terrain is too bright/lacks depth but not connect it to a specific graphics feature (or lack thereof).

**Comment by ClobberXD** [comment]
> Most players will not be aware of the ambient occlusion settings, still notice that terrain is too bright/lacks depth but not connect it to a specific graphics feature (or lack thereof).

I agree. Until this PR, I didn't even realise that the depth in terrain was amiss.

**Comment by oilboi** [comment]
1.4 looks super nice, yo

**Comment by paramat** [comment]
Using plain colour textures makes the effect of lighting and ambient occlusion visually clearer. I also tested using MTG textures and had the same opinion.

Since their seems to be some support from other core devs, a change seems likely. I am requesting a less extreme change. 1.4 is just a little too much contrast to be bearable for me, and i consider it a little too excessive for general usage.
> Most players will not be aware of the ambient occlusion settings, still notice that terrain is too bright/lacks depth

I disagree the terrain is too bright or lacks depth =D
However a little more contrast seems ok.

I think there is a danger that some people say they like 1.4 because it is super-high contrast and intense 3D depth. Understandably this may look appealing at first, but actually in the longer term it is tiring for the eyes and distastefully excessive. High contrast and intense 3D depth is actually not necessarily a good thing.
I think some of the support 1.4 is getting should be considered cautiously, because i think it is due to the effect of 'initial impact'. Even i get that initial impact effect.
It is like overly sweet food.

**Comment by paramat** [comment]
> I agree. Until this PR, I didn't even realise that the depth in terrain was amiss.

Careful though, if you did not realise before then there may not actually be a problem.
This PR compares 1.4 to the current setting, naturally this creates a contrast between the 2 that then makes the current setting look weak, but this may only be due to the contrast.
For example i could open a PR for weaker ambient occlusion, the comparison would then make the current setting seem strong.

**Comment by paramat** [comment]
> Not really. Most players will not be aware of the ambient occlusion settings, still notice that terrain is too bright/lacks depth but not connect it to a specific graphics feature (or lack thereof).

I think this logic makes no sense (sorry).
Players do not need to understand ambient occlusion or know of the setting, if they find the terrain lacks 3D definition and depth they will say so. However, very very few have (i cannot remember any before this PR).

Extreme changes to settings are almost always a bad idea, for obvious reasons. MT does not have an extreme lack of 3D definition and depth, so the alteration should be subtle.
Current value is 2.2, so i expect 1.6 or 1.8 might be ok, i should test.

This should be tested in-game, not judged from the screenshots. The screenshots in the first post are of overhanging terrain, which looks more acceptable with high contrast. Upward facing terrain gives a different impression. For example, a single node hole in a flat surface is unacceptably dark with 1.4:

![screenshot_20200517_005518](https://user-images.githubusercontent.com/3686677/82132676-26552380-97da-11ea-8761-c6a39376a8a2.png)

**Comment by oilboi** [comment]
> > Not really. Most players will not be aware of the ambient occlusion settings, still notice that terrain is too bright/lacks depth but not connect it to a specific graphics feature (or lack thereof).
> 
> I think this logic makes no sense (sorry).
> Players do not need to understand ambient occlusion or know of the setting, if they find the terrain lacks 3D definition and depth they will say so. However, very few have (i cannot remember any before this PR).
> 
> Extreme changes to settings are almost always a bad idea, for obvious reasons. MT does not have an extreme lack of 3D definition and depth, so the alteration should be subtle.
> Current value is 2.2, so i expect 1.6 or 1.8 might be ok, i should test.
> 
> This should be tested in-game, not judged from the screenshots. The screenshots in the first post are of overhanging terrain, which looks more acceptable with high contrast. Upward facing terrain gives a different impression. For example, a single node hole in a flat surface is unacceptably dark with 1.4:
> 
> ![screenshot_20200517_005518](https://user-images.githubusercontent.com/3686677/82132676-26552380-97da-11ea-8761-c6a39376a8a2.png)



The same thing happens in MC, a hole will be dark no matter how you splice it. 

2.2 looks horrible and makes the terrain look artificially bland. 

Stumbling over this simple voxel based software lighting issue vs making the terrain as a whole look nicer with 1.4 gamma is simply not good. 

Also I must add your example is ignoring an actual bug visible to the left of your example: chunk border lighting errors.

![Minecraft 1 15 2 - Singleplayer 5_18_2020 8_00_15 PM](https://user-images.githubusercontent.com/47129783/82270298-51f31d80-9942-11ea-86b8-5fd7a9dd5ff9.png)

**Comment by LoneWolfHT** [comment]
I'll be using 1.4 from now on, so far it looks fine, there aren't even too many cases where it looks like a drastic change

**Comment by LoneWolfHT** [comment]
In Nodecore when mining by firelight 1.4 makes it a little too dark, this is worsened by the fact that MT darkness is pitch-black

**Comment by sfan5** [comment]
How do 1.6 or 1.8 fare in that situation?

**Comment by paramat** [comment]
Here is a screenshot of the current MT value. The dungeon room edges show how it is not a weak effect at all. Significantly darker than this would make the edges ridiculously dark.
Plain colour textures are still vaild textures to test with as certain materials can have a very simple plain appearence. The plain colour is useful in making the effect clear.
So i think any increase in occlusion can only be very slight.

![screenshot_20200519_224513](https://user-images.githubusercontent.com/3686677/82847905-9c4b4000-9ee8-11ea-9cf4-590b40f93204.png)

**Comment by LoneWolfHT** [comment]
That texture is a lot brighter than most textures, so the darkness shows up the most. Maybe use a value like `#808080` (Which is inbetween black/white AFAIK)

**Comment by TheTermos** [comment]
I like the change, it has a cell shading vibe to it. 

Too bad I won't be able to benefit, as it only works with smooth lighting on which I don't use, as it makes everything so bland that one light level difference is barely visible even on the lowest allowable gamma setting.

I don't think overall light curves in MT need careful deliberation, they need more like a punch in the face.

**Comment by sfan5** [comment]
Bump.
All playing I have done since creation of this issue happened with `ambient_occlusion_gamma = 1.4` and I consider fully acceptable as new default value.

I understand that some people may prefer a less strong effect so `1.6` or `1.8` is an acceptable compromise.

**Comment by paramat** [comment]
> The same thing happens in MC, 

How MC looks is not an argument, maybe they have bad defaults?
The hole in your MC screenshot is excessively dark.
> a hole will be dark no matter how you splice it.

No, that is a nonsense statement, holes are not extremely dark in MT with the current value. I am objecting to the degree of darkness, not the presence of it.
> Also I must add your example is ignoring an actual bug visible to the left of your example: chunk border lighting errors.

That is not a lighting error, the structure is 8 nodes placed in a square on flat terrain, creating a central hole, you are seeing a correct occlusion shadow.
The partially built structure is shown in my screenshot below that one.

sfan5, please can it be 1.8? I will not disapprove that.
2.2 has had few complaints, so i think we have to accept that the best balance for all users will not be an extreme change.
Many find 2.2 fine, some like 1.4 which is the other extreme, split the difference for a good balance = 1.8?

**Comment by LoneWolfHT** [comment]
I've played with 1.8 and it's seemed fine. I can always change it up again if I end up not liking it anyway

**Comment by sfan5** [comment]
> sfan5, please can it be 1.8? I will not disapprove that.

Sure, that's an acceptable compromise. It's also not for me (alone) to decide after all.

> 2.2 has had few complaints, so i think we have to accept that the best balance for all users will not be an extreme change.

I still think this is a fallacy (right word?), users will not notice that they may find terrain too flat looking unless you point the difference out to them.

**Comment by jastevenson303** [comment]
anecdote at best
