### ISSUE TITLE
Entity Unload Check

### ISSUE THREAD

**Issue by tenplus1** [minetest/minetest#9867]
When using entities we have all the necessary on_activate and staticdata that loads when it has been placed in world, unloaded from a chunk or reloaded again, but finding out wether an entity has been created or simply reloaded from a map chunk is difficult.

Could we add an on_unload function to entities, or some way of checking wether it has been created,  unloaded or reloaded ?

**Comment by sorcerykid** [comment]
PR #9717 adds an `on_deactivate()` callback that is invoked just before an entity is unloaded from the environment, even as a result of `obj:remove()`. As for checking if an entity has been created rather than reloaded, that's as simple as `dtime == 0` in the `on_activate()` callback.

**Comment by tenplus1** [comment]
Thanks sorcerykid, will look into dtime :)

**Comment by oilboi** [comment]
This would be so amazing to have!

**Comment by appgurueu** [comment]
Can't this be closed after #10723 has been merged?
