### ISSUE TITLE
minetest.spawn_tree shows an error message when no alias for mapgen_dirt is defined

### ISSUE THREAD

**Issue by NetherEran** [minetest/minetest#9869]
##### Minetest version

```
Minetest 5.3.0-dev-cb9a44e
```

##### Summary
When minetest spawns an L-system tree in a game that does not have the alias `mapgen_dirt` set, this error message appears in chat, even in non-v6 mapgens: 
`ERROR[Emerge-0]: Treegen (make_ltree): Mapgen alias 'mapgen_dirt' is invalid!`

The dirt is spawned under trees with `trunk_type = "double"` or `trunk_type = "crossed"` in their definitions so they don't end up flying in the air. Instead of mapgen_dirt, the node for this should probably be the biome's filler node or specified in the treedef.

##### Steps to reproduce

Paste this lua code into a mod and enable it with [minipeli](https://github.com/paramat/minipeli) selected as the game.
```lua
minetest.register_on_joinplayer(function(player)
	local pos = player:get_pos()
	minetest.spawn_tree(pos, {
			axiom="FFFFFFFFFFFFFFFFFFFAFFBF",
			rules_a="[&&&FFFFF&&FFFF][&&&++++FFFFF&&FFFF][&&&----FFFFF&&FFFF]",
			rules_b="[&&&++FFFFF&&FFFF][&&&--FFFFF&&FFFF][&&&------FFFFF&&FFFF]",
			trunk="mapgen:stone",
			leaves="mapgen:grass",
			angle=30,
			iterations=2,
			random_level=0,
			trunk_type="double",
			thin_branches=true,
			fruit_chance= 0,
		})
end)
```

**Comment by Wuzzy2** [comment]
I have added this error message, but only because the code was already assuming `mapgen_dirt` to exist.

So I guess the bug is not the error message itself, but the assumption in the code that made this error message neccessary.

IMO L-tree spawning should not require any mapgen alias to function correctly.

**Comment by paramat** [comment]
> Instead of mapgen_dirt, the node for this should probably be the biome's filler node or specified in the treedef.

I agree this needs rethinking. L-system trees are still coded as if only Mapgen V6 existed.

**Comment by paramat** [comment]
PR #9931
