### ISSUE TITLE
Disable transition animation setting when swapping items

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9875]
Exactly as the title says, disabling the animation that makes the wield item sink into the bottom of the screen to create the illusion that the current item is taking on a new state

**Comment by ClobberXD** [comment]
Swapping items across slots, or swapping an item in a certain slot from Lua? There's already a feature request for the latter: #9377.

**Comment by sfan5** [comment]
unrelated but you might also find this useful: #9562
