### ISSUE TITLE
Cant tell difference between enable/disabled (built-in?) mods

### ISSUE THREAD

**Issue by OgalFinklestein** [minetest/minetest#9878]
## Problem
New to minetest.  Latest stable Debian 10.x build.  I installed 0.4.17.1 from Debian repo, but later pulled down 5.3.0-dev this GitHub repo.  Both installed (different directories).

Found some mods i wanted to try,  Added them to ~/.minetest/mods (_after running into problems installing under ~/.minetest/clientmods_).  Created a new world (mapgen v7 -- "minetest game"); wanted to enable mods, but noticed a UI problem.

Here's a screenshot selecting some new mods, except _footprints_.  I can tell the difference between selected and non-selected mods.
![1_mods_default](https://user-images.githubusercontent.com/65432753/82108437-6645d900-96fc-11ea-86a7-de3972c84f2f.png)

After clicking **Enable All**, only the mods I downloaded are enabled.
![2_mods_all_enabled](https://user-images.githubusercontent.com/65432753/82108440-67770600-96fc-11ea-936c-93d299d3fdff.png)

After clicking **Disable All**, the mods I downloaded are disabled.
![3_mods_all_disabled](https://user-images.githubusercontent.com/65432753/82108441-67770600-96fc-11ea-87f3-73e5e92dae05.png)

But these built-in mods ... are they always enabled?  Always disabled?  What if I wanted to play without a built-in mod?  Should I remove the mod from **$STATIC_SHAREDIR**/games/minetest_game/mods/ -- Nah, that's just crazy talk, right?

_Maybe I should move all the built-in mods to ~/.minetest/mods for finer control ..._  more crazy talk, or is it?

An additional reason why I post this is because prior to downloading those 7 mods, I created a world and ran around in it for about 10 minutes.  I didnt see beds, boats, butterflies, doors, animals (or mobs), etc.  Just terrain.  Lots and lots of terrain.

## Suggested Solution(s)

I think there should be a distinction in the UI between enabled built-in mods -vs- disabled built-in mods.  Failing that, a **note** indicating that built-in mods are always enabled/disabled and cannot be toggled.

Thanks.

**Comment by NathanSalapat** [comment]
The 'built-in' mods are what make up Minetest Game, they can't be disabled as they are what makes the game. To disable them you'd have to manually remove them from the game directory. If you were to create a world with another game you'd find that the header name for the 'built-in' mods would reflect the game name.

You wouldn't want to remove a mod from Minetest game as it could break things. The mods are all required for the game to run. Removing one could prevent others from loading, which in turn could prevent the game from loading entirely.

Minetest_game does not include any animals/mobs. You have to manually add them via mods, but the other things you mentioned exist. With the exception of the butterflies you won't find them in the world, they need to be crafted and placed.

I think the blue text is meant to be the distinction that the mods are part of the game and can't be disabled.

**Comment by KaylebJay** [comment]
Yes, this isn't a bug, its a feature. The blue mods are part of the game you are playing (which is Minetest Game) and thus is shown blue so that you can't edit them. To enable/disable them, you can also use minetest.conf stuff like fire_enabled = false/true.

**Comment by OgalFinklestein** [comment]
@NathanSalapat Yes, I figured moving these mods out the minetest_game folder wouldnt be a good thing.
@KaylebJay Which is why I didnt report it as a bug.  Yes, I did notice that I could go into the Settings (or the .conf) and enable/disable features, but that looks to be global settings and not per-world settings.  I dont see a .conf under my worlds/* folders.

**Comment by OgalFinklestein** [comment]
After referencing **pixture** and **tutorial**, it seems that I can create worlds to my liking by first inventing a **game** under ~/.minetest/games/ and creating
-     ~/.minetest/games/minetest.conf
-     ~/.minetest/games/game.conf

and then possibly symlink'ing mods directories.  I'll have to play around with it.

**Comment by paramat** [comment]
NathanSalapat is correct.
> I think there should be a distinction in the UI between enabled built-in mods -vs- disabled built-in mods.

The game mods are always enabled, so this request is invalid.
> Failing that, a note indicating that built-in mods are always enabled/disabled and cannot be toggled.

:-1: This is obvious once you get to know how MT games work.

Some mods in games are actually optional, but you have to know what you are doing to make sure you are not breaking things. You could then remove the mod from the game's mod folder.
As explained, some game mods are already disableable in the 'All Settings' menu, such as MTGame's 'weather' mod.

However, are you requesting the ability to enable and disable game mods? That has been requested in #8622
This issue should probably be closed soon.

**Comment by OgalFinklestein** [comment]
Ok, so game mods are always enabled, but as a new player that's not straight-forward knowledge.  

No, Im not requesting the ability to enable or disable game mods, especially since Ive now figured out how to create my own game under ~/.minetest/games/

However, standing by my earlier point:
> a note indicating that built-in mods are always enabled and cannot be toggled.

that would still be a nice touch for new players.

**Comment by paramat** [comment]
Ok. labelled as a request for documentation.
