### ISSUE TITLE
Player breath values not saving when > 10

### ISSUE THREAD

**Issue by Terumoc** [minetest/minetest#9882]
##### Minetest version

```
Minetest 5.2.0
```

##### OS / Hardware

Operating system: Linux
CPU:  Intel Core i7-4820K 

(probably not important)

##### Summary

When playing a game/mod that alters the player's breath_max property, the engine seems not to bother saving the current breath level of a player if it's greater than 10.

For example: playing a game with breath_max 15:
Leave game with 15 breath -> rejoin game and breath is set at 10 (incorrect)
Leave game with 3 breath -> rejoin game and breath is set at 3 (correct)

This can obviously be corrected via modding and saving/updating the correct value manually, but since the engine takes effort to restore the breath value, it probably should either do it correctly or not at all.

**Comment by Terumoc** [comment]
oh never mind, I understand why this happens now:

1. Engine loads player, sees default breath_max and caps saved high breath value to default max
2. Game/mod alters breath_max to 15 when player joins to new correct value
3.  Voila, you have 10/15 breath every time you join

Oops. Sorry about the unnecessary report.

**Comment by ClobberXD** [comment]
This is the way object properties work unfortunately - none of them are persistent. If you'd like players to have a higher breath_max by default, it might help to also set their breath to breath_max immediately.
