### ISSUE TITLE
Unknown settings are deleted from minetest.conf

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9885]
Settings which are not known to Minetest are simply deleted from `minetest.conf`. They should rather be out-commented or just loaded.

**Comment by rubenwardy** [comment]
I've used minetest.conf to store mod settings for a long time, and I don't know of any recent changed that could have broken it. Did you have minetest running when you were editing settings?

**Comment by appgurueu** [comment]
@rubenwardy indeed, it worked this time... my fault, closing this.
