### ISSUE TITLE
Android resources fail to extract

### ISSUE THREAD

**Issue by rubenwardy** [minetest/minetest#9886]
This has been reported by a few users, most recently: https://forum.minetest.net/viewtopic.php?p=373391#p373391

#9760 should have fixed the issue where the app ignored failed extraction

Investigation needed

**Comment by MoNTE48** [comment]
You hastened to open a issue. I gave an outdated link.
The new versiob will not even launch Minetest if it cannot successfully unpack the assets.
It will also showed Toast with information (no memory space, not gra Ted permissions, apk does not contain an archive, etc.)

**Comment by MoNTE48** [comment]
@rubenwardy 
This PR fixed first part of issue
https://github.com/minetest/minetest/pull/9900
And rebuilding APK fixed second part.

**Comment by MoNTE48** [comment]
Fixed in #9900 and may be closed.

**Comment by rubenwardy** [comment]
I'll close and hope it isn't reported again :grimacing:

**Comment by MoNTE48** [comment]
I also. MultiCraft switched to using [zip4j](https://github.com/srikanth-lingala/zip4j) some time ago for this reason.
Using a good unzip library is much more reliable than trying to do it yourself.
There are also some improvements to text input field. I am testing this now. And would rather release them later, for example in Minetest 5.4.
