### ISSUE TITLE
Set_sky: Show stars (if enabled) at all times in "plain" and "skybox" modes (maybe optionally?)

### ISSUE THREAD

**Issue by paramat** [minetest/minetest#9887]
Using the new set_sky API, it is possible to create a 'space sky' that uses the engine's sun, moon and stars. This can be done in "plain" sky mode using a black plain colour, or in "skybox" sky mode using 6 black textures. In these modes there is no horizon so sun, moon and stars are visible in all directions.

However, when doing this, the stars are only visible when the sun is in the lower half of the sky (what would normally be night):

![screenshot_20200517_021839](https://user-images.githubusercontent.com/3686677/82161695-c6708280-9896-11ea-9429-a33676c196cd.png)

^ Looking down

When the sun is in the upper half of the sky (what would normally be day), the stars are not shown:

![screenshot_20200517_233517](https://user-images.githubusercontent.com/3686677/82161737-1e0eee00-9897-11ea-9f44-fc6c76c82abe.png)

^ Looking up

The stars are fading out as they would do in daytime "regular" sky.

My request:
In "plain" and "skybox" modes, show stars (if enabled) at all times, just like the sun and moon are.

@Jordach perhaps you might be interested or can give advice?

**Comment by jastevenson303** [comment]
what about player:set_moon, set_sun, set_stars?

**Comment by sfan5** [comment]
> In "plain" and "skybox" modes, show stars (if enabled) at all times

Aside from being an unannounced API break, this is also inflexible.
It would be much better if `set_stars` allowed to specify if stars should be visible at day (or perhaps even the time range?).

**Comment by paramat** [comment]
jastevenson303, what about them? They cannot be used to workaround this problem.

sfan5,

The new set_sky API is very young and not fully stable yet anyway, one other part is likely to change.
In a way i do not consider this a 'break', more a 'fix', because when using a "plain" or "skybox" sky, you would usually not want stars to fade away for half the time, because 'daytime' has little meaning in these modes (because the sky does not change appearance in 'daytime').
However, i can imagine a minority of uses would prefer star fadeout, which means this being optional, which would mean a packet change.

If we want to avoid changing packets, i suggest that constant stars is more desirable than daytime-fading stars in these 2 modes.
If a day-night cycle is wanted in "plain" or "skybox" modes, the sky colour/appearance would have to be changed by mod code at dawn and sunset, so star brightness could also be changed by mod code at those times. So it seems no functionality is lost with my 'no-option' suggestion.

I also suggest that those wanting a day-night cycle will usually use "regular" sky and its settable sky colours.

As it is now, engine stars cannot be used for a space sky unless time is stopped at night time.

Needs more input and consideration though.

**Comment by sfan5** [comment]
I do not know about the actual usecases, I am just just pointing out that the set_sky/set_stars API cannot just be broken. Sky color darkening is the only part that was marked as subject to change. 

> If we want to avoid changing packets

(There is no pressing need to avoid that.)

**Comment by Wuzzy2** [comment]
Just add another parameter to enable/disable “all-day stars”. Both cases are useful.
Same for “stars everywhere” vs “stars only above the horizon”.

Then nothing has to be broken at all.

**Comment by paramat** [comment]
> Just add another parameter to enable/disable “all-day stars”. Both cases are useful.

I suspect this is best.

**Comment by Wuzzy2** [comment]
New PR: #11663
