### ISSUE TITLE
animated_image doesn't work when gui_scaling_filter is enabled

### ISSUE THREAD

**Issue by EvidenceBKidscode** [minetest/minetest#9892]
When `gui_scaling_filter` is enabled, `animated_image` shows only one frame, the others stay invisible. `background` are broken too.

Comparison with `craftguide`:

###  `gui_scaling_filter` disabled:

![screenshot_20200519_001456](https://user-images.githubusercontent.com/7883281/82264760-d73bf980-9965-11ea-9b2e-2a464a0dd568.png)

###  `gui_scaling_filter` enabled:

![screenshot_20200519_001242](https://user-images.githubusercontent.com/7883281/82264773-dc994400-9965-11ea-9e42-1ff1ef4a51a6.png)

@Df458 @v-rob @rubenwardy @sfan5

**Comment by SmallJoker** [comment]
Since which commit or release?

**Comment by Df458** [comment]
> Since which commit or release?

Since always.

This is a bug in `imageScaleNNAA`. The function clamps rect bounds incorrectly so any source rect that's too far in either axis gets cut off.
