### ISSUE TITLE
MTG 'mapping kit' in inventory + F9 leads to an internal server error

### ISSUE THREAD

**Issue by Assertores** [minetest/minetest#9905]
##### Minetest version
```
Server version=5.1.1
```

##### OS / Hardware
Operating system: Windows
CPU: server unknown

##### Summary
the server crashes if a client places the item "kartenset" into his inventory and presses F9 for the minimap
clients are in creative mode

##### Steps to reproduce
1. start a server
2. connect to the server as client
3. place the item kartenset into your inventar
4. press F9

**Comment by SmallJoker** [comment]
Cannot reproduce using an old 5.2.0-dev build.

Does this happen in singleplayer mode, or only in multiplayer?
Please test a more recent version:
1) Download the most recent 5.3.0-dev build [maybe from here](https://minetest.kitsunemimi.pw/builds/)
2) Start the console. `Win + R -> "cmd" -> Enter`
3) Input: "cd C:\path\to\new\minetest-5.3.0-dev-12345\bin"
4) Input: "minetest.exe"
5) Do not adjust settings
6) Create a new world
7) Chat command: `/grantme all`
8) Chat command: `/giveme map:mapping_kit`
9) Press `V` (new hotkey for minimap)
10) Copy console output & report here

**Comment by sirrobzeroone** [comment]
Tried to replicate with no success to help isolate source of bug but had no luck -  all tested on win10 using 64bit version nil mods active MTG as game:

Test One ver 5.1.1
- Hosted server and joined in creative gave myself a map and pressed F9 while holding in hand, in inventory, running, tried throwing and picking the map backup then repressing F9 - No crash

- Single Player as above same outcome no crash

Test Two ver 5.3
- Hosted server as above for tests and likewise no crash (except key now v not F9)

- Singleplayer same tests again no crash

Note: I didn't change my base language to German so Map was still called Map not kartenset - If theres value I can run the same tests but in German.

**Comment by paramat** [comment]
@Assertores 
> Does this happen in singleplayer mode, or only in multiplayer?
Please test a more recent version
