### ISSUE TITLE
Directional parameter for textarea[]

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#9922]
## Problem

![screenshot_20200523_123549](https://user-images.githubusercontent.com/23448162/82735812-86742a00-9cf2-11ea-939d-d6d24046da05.png)

![screenshot_20200523_124136](https://user-images.githubusercontent.com/23448162/82735841-c2a78a80-9cf2-11ea-89a2-de063cd83100.png)
## Solutions

I'd like to make a textarea[] upside down, so overflow text extends upwards with the correct scrollbar configuration.  Thanks for checking out this issue!

**Comment by v-rob** [comment]
I believe this would be better served as a scroll container with individual text elements for each message.  Granted, formspecs don't allow fine-tuning of the layout as of yet, but I believe this feature should not be necessary.
