### ISSUE TITLE
Android "Fast Mode" toggle sends (continuous) AUX1 player control, breaking sprint mod

### ISSUE THREAD

**Issue by ghost** [minetest/minetest#9924]
##### Minetest version

```
Latest Android version from Play Store
Latest Server from github/minetest
```

##### Summary

Enabling "Fast mode" with privilege on Android also sends a continuous AUX1 signal, breaking the stamina mod on jastest server.
##### Steps to reproduce

Download Android version, connect to jastest and enable fast/fly

**Comment by sfan5** [comment]
Looks intentional to me:
https://github.com/minetest/minetest/blob/10c3002aea784b5f0075f3f3e3ec824b6ba546ba/src/client/game.cpp#L2501-L2511

**Comment by ClobberXD** [comment]
The question is: why? :)

Why simulate aux1 pressing when fast_move is enabled, and why is invert aux1 keypress detection (on purpose!), given that this breaks mods that make use of aux1?

**Comment by MoNTE48** [comment]
@ClobberXD reply is:

> Because the developer had a very small phone, very thumbs and a complete lack of ideas on where to place the AUX1 button.

**Comment by The32bitguy** [comment]
You are already using fast so why are you concerned about it making a sprint mod malfunction? AUX is in my experience only for movement mods, which fast overrides.

**Comment by paramat** [comment]
Commit https://github.com/minetest/minetest/commit/addf3ee16559a0e1173bae1e59d9bdbd54e3526c
Issue (no PR thread for this) #2734
Also see
https://github.com/minetest/minetest/blob/10c3002aea784b5f0075f3f3e3ec824b6ba546ba/src/client/game.cpp#L2164-L2183
I do not get it yet either, why simulate holding AUX1 when the player has fast mode enabled and has the fast priv? In that situation the player is already moving fast so triggering a sprint mod with AUX1 seems unnecessary.
This is not done for PC.
Android has a AUX1 button.

This issue might become a request to change this behaviour.

**Comment by paramat** [comment]
Thinking further, it was correct and necessary to invert the keypress bits when AUX1 was inverted, for consistency with previous behaviour.
Although the current behaviour causes problems for a mod, it seems correct behaviour, not inverting keypress bits would probably break more stuff.
So closing.

**Comment by jamesalexanderstevenson** [comment]
Not A mod, but any mod that uses AUX1.
