### ISSUE TITLE
Display system `wall` messages in chat

### ISSUE THREAD

**Issue by Batcastle** [minetest/minetest#9925]
## Problem
I want messages broadcast on *nix systems with the `wall` command to be displayed in chat. This way, a message can be displayed to users when a server is about to go down for a reboot.

## Solutions

I cannot find some way for system processes to easily intercept `wall` messages.

## Alternatives

Potentially a system terminal command that posts a message to all users in the server. So something like:
```shell
<username>@<hostname>:~$ minetest --wall "System going down for reboot soon!"
```
Would display a message in chat like:
```
<SYSTEM> System going down for reboot soon!
```

Doing this would make it so that server admins would be able to add a simple script to their system, that would post a message on both `wall` on user's terminals, and in Minetest server chat, ideally in a different color that will make it stand out..

## Additional context

Other games, such as [Unturned](https://store.steampowered.com/app/304930/Unturned/), have a similar feature. This feature makes it so that users are not abruptly kicked off a server, thinking something went wrong.

**Comment by ClobberXD** [comment]
An alternative: It's possible to achieve this functionality using mods. One approach would be to make the reboot script create a new file, that the mod can periodically check for. If the file exists, the mod sends a chat message.

**Comment by Batcastle** [comment]
My issue with that implementation is it wastes valuable CPU time. On something like an Raspberry Pi that could be very taxing (think ARM CPU performance and also constant reads to the SD card). Having a command, while it does take disk space, is something that takes less CPU power.

Personally speaking, I know of no mods to Minetest that provide commands to a server admin on CLI. While it is theoretically possible so far as I am aware, I feel it would be much easier to code something like that into the main game (please correct me if I am wrong on that point).

**Comment by ClobberXD** [comment]
> My issue with that implementation is it wastes valuable CPU time. On something like an Raspberry Pi that could be very taxing (think ARM CPU performance and also constant reads to the SD card). Having a command, while it does take disk space, is something that takes less CPU power.

Those are good points indeed.

> Personally speaking, I know of no mods to Minetest that provide commands to a server admin on CLI. While it is theoretically possible so far as I am aware ...

I haven't yet seen a mod that does this, and it currently isn't possible either, AFAIK.

**Comment by rubenwardy** [comment]
You can use --terminal to issue commands intereactively/via stdin

**Comment by LoneWolfHT** [comment]
Mods can restart the server too if you have it set to restart on crash, it might be better to just have a mod restart the server

**Comment by rubenwardy** [comment]
Regarding the opening request - this is way too specific a feature, and is on Linux. There are plenty of mod solutions to set this up. It's worth noting that the shutdown function accepts a message, meaning that you can tell the user the reason in the disconnect dialog

**Comment by paramat** [comment]
I agree with rubenwardy :-1:

**Comment by rubenwardy** [comment]
Feel free to continue to ask any questions, either here, on the forums, or some other community place
