### ISSUE TITLE
Can’t favourite multiple unlisted servers

### ISSUE THREAD

**Issue by Hawk777** [minetest/minetest#9933]
##### Minetest version
```
Minetest 5.2.0 (Linux)
Using Irrlicht 1.8.4
BUILD_TYPE=Gentoo
RUN_IN_PLACE=0
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="/usr/share/minetest"
```

##### OS / Hardware
Operating system: Linux
CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

##### Summary
I connected to an unlisted server by hostname and port number. It became a favourite and was shown at the top of the server list with a gold star. I then connected to a second unlisted server. Although both servers appear in `serverlist/favoriteservers.txt`, only the most recent one actually shows up in the GUI; the older one is not visible.

##### Steps to reproduce
Connect to two unlisted servers in a row, by hostname and port number. Go back to the server list in the GUI.

**Comment by SmallJoker** [comment]
Works for me.

![grafik](https://user-images.githubusercontent.com/1497498/82834400-4c0cb780-9ec1-11ea-8fab-b418324948bc.png)

**Comment by Hawk777** [comment]
[favoriteservers.txt](https://github.com/minetest/minetest/files/4679693/favoriteservers.txt)

![screenshot](https://user-images.githubusercontent.com/365236/82856802-e7069100-9ec3-11ea-9870-ed95361486e0.png)

**Comment by An0n3m0us** [comment]
Confirmed; same for me on `5.3.0-dev-f34c62c-dirty`.
It keeps them in `favoriteservers.txt` but only displays the first of that type.

For instance:
```
[server]
Craig's Server
minetest.davison.io
30000
Well-built, reliable and popular world for new or experienced builders. Come and join us! :)

[server]

192.168.1.115
30000

[server]

192.168.1.114
30000

[server]

192.168.1.112
30000
```

Will show:
![image](https://user-images.githubusercontent.com/49789044/82892876-24146700-9f48-11ea-8873-5e31c954a2ce.png)

**Comment by An0n3m0us** [comment]
It seems like the description and the space below `[server]` matter:
![image](https://user-images.githubusercontent.com/49789044/82893484-fbd93800-9f48-11ea-95df-72cfaa9be2dc.png)

**Comment by An0n3m0us** [comment]
I think I've found out why; if any of the servers don't have this format, it messes things up:
```
[server]
[NO EMPTY LINE HERE]
SERVER NAME
SERVER IP
PORT
DESCRIPTION
```

**Comment by Hawk777** [comment]
Yeah, exactly. My sample *does* have that format, it’s just that both servers have empty `SERVER NAME` lines, because you can’t give a human-readable name to an unlisted server. In my case I used hostnames (`server1.example.com` and `server2.example.com`) instead of IP addresses because that’s how I connect to my unlisted servers, but just as with the IP address form the human-readable names are empty. If you think it matters I could try with IP literals instead of hostnames, but that seems irrelevant?
