### ISSUE TITLE
Add Help page to the Main Menu

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/minetest#9942]
I propose to add a Help menu about Minetest into the main menu.

## Outline

To keep things simple, the help shall be accessible only in the main menu. The Help menu becomes a new tab named “Help”.

In this tab, there's a list of help pages. You can open each help page. Maybe it should be structured into categories if the number of help pages grows too large.

Each help page contains text and maybe some images to illustrate things. The help page will probably benefit a lot from the `hypertext[]` formspec element.

All help texts must be strictly about Minetest only, and not about a specific game. 

Some topics that could be covered:

* Introduction (Purpose of Minetest, what you can do with it, etc.
* Getting started (How to start your first game)
* Worlds (what they are, how to create them, etc.)
* Controls (not a listing of keys, but an explanation what each control does)
* Games and mods (what they are, how to use them, dependencies)
* ContentDB
* Online gameplay
* Mapgens (description of the core mapgens, mapgen config, and more) (see also #1033)
* Settings
* Commands
* Privileges
* Link list (homepage, forum, wiki, etc.)
* And possibly more ...

Many of the help texts can probably be modeled after the `doc_basics` mod (https://forum.minetest.net/viewtopic.php?t=15912), without going too specific into gameplay.
Some pages from `doc_basics` like Crafting and Liquids are probably wrong here because some games might not have any crafting or liquids.

I also think the Minetest help texts should probably be written much more succinct than `doc_basics`; if possible, without sacrificing information. Make it as simple as possible, but not simpler. Hypertext will definitely be a big help in making the text more readable.

## Justification

For complete newcomers, Minetest is certainly daunting. I have first-hand evidence (videos) that newbies fail to understand many basic features in Minetest, so they get confused and rage-quit. It's exceptionally bad in Android (but that's a different topic).

Minetest currently has a very terrible usability (to all core devs who think otherwise: You are biased. It's obvious that understand your own program well, this doesn't mean that others will), and there's a lot of features where you really can't get around some kind of explanation.

Adding a help is IMO a good first step to help resolve some of the confusion. But I am aware that the Help alone is not sufficient to fix all the usability problems. The Help is not the Ultimate Solution, but it will certainly be a major improvement.

There's a lot of things going on, and Minetest isn't even a game in its own right. Minetest's repository, as of now, has almost no player-facing documentation at all. The only thing that players really have is the README, but this is far from enough.

Finally, there used to be a time in which all games came with a manual. I want to bring back this time. :)

## Feedback

Maybe I will do this thing. But I first need your opinion and OK. It's pointless to start working on something that nobody else approves.

If there's enough approval, I might start with posting some help texts in this issue to show you the rough direction of the writing style. Those help texts can later be then incorporated into an actual PR (but we're not there yet).

## Rebuttals

* “But we have the Wiki, we don't need this!”: Yes, but 1) the wiki is not in sync with the repository which means it's (sadly) not a substitute for a real manual and 2) many people don't download Minetest from the official Minetest.net website and don't even know about the Wiki's existence and 3) translating strings in Minetest is much easier than translating a Wiki (Wikis are *terrible* for translation tasks, as the language versions are not in sync) and 4) the Wiki forces you to be online.
* “Why not just use text files like README?”: Because those files are much less accessible and they can't be translated easily
* “But it will be extremely hard/time-consuming/annoying to update the help afterwards.”: That's certainly possible, but this is more a problem about our inefficient PR process instead of this feature request. This might be fixed by considering all help text changes as trivial, so the string approval rules don't apply. 
* “But only idiots/n00bs need the help!”: Yes, that's the whole point. We all start at n00bs at sometimes.
* “But it will clutter the UI!”: No, it won't. The entire help is hidden behind a single tab only in the main menu that nobody is forced to click. You can't get less intrusive than that.
* “But it will increase the code complexity!”: Maybe a little bit, but I think the benefit will greatly outweigh the cost.
* “But who will translate all the texts?”: I will. And others, too. Did you see how much activity there is on Weblate?
* “Won't this result in lots of huge walls of text that blow up the size of translation strings?”: Not if we partition the strings into edible chunks. I agree, it's a bad idea to put an entire help page into `S()`, but if we only put small paragraphs into `S()`, it's much more managable, and fixing a single typo won't reset the entirety of a large translation. See what I did in `doc_basics`.
* “But nobody will read the help.”: My experience shows otherwise. But usability can be improved by, for example, integrating the help in other UI contexts, like adding a help button next to the mapgen dropdown (but I'm not sure about that).
* “Nobody likes to read walls of text!”: `hypertext[]` to the rescue!
* “If the help is not available in-game, it's useless!”: This is a compromise. I made the decision to not include the help in-game (for now) to keep the task managable. Maybe the help could later be integrated in-game as well, but I assume this will be a much greater task, and would call for a new issue. Also, the proposed help is specifically for Minetest only, and not a specific game. It's thinkable that games ship their own game-specific help (which is what the Help modpack does) to supplement the Minetest help.
* “Does this clash with `doc_basics`?”: Yes. I plan to remove the redundant pages in `doc_basics` when this task is finished
* “We have to first wait until rubenwardy's main menu rework is done.”: If this is a hard condition, then I'm afraid this issue is stalling for now. We still can use the time to discuss.

**Comment by rubenwardy** [comment]
I think that needing help instructions to use basic functions of software is usually a sign of bad or over-design. However, that doesn't mean there shouldn't be any documentation, and having a manual isn't mutually exclusive with improving usability

> “We have to first wait until rubenwardy's main menu rework is done.”: If this is a hard condition, then I'm afraid this issue is stalling for now. We still can use the time to discuss.

This is certainly not required, if this is to be a tab

**Comment by Andrey2470T** [comment]
I think adding an in-game help instructions is certainly reasonable. Most apps of the different direction have them inside themselves (Blender, Gimp, Audacity, SimpleScreenRecorder and etc) and Minetest also can have.

**Comment by Zughy** [comment]
I don't think it's a good idea. First of all, current documentation outside of GitHub is already not updated. The modding book, for instance, only features 2 languages and, even more important, it has some outdated/missing chapters. I know because I was the one translating it in Italian (where the other language is English). And we're talking about the most useful source out there to learn how to code on Minetest.  
Wiki, on the contrary, is a mess of "warning!" telling you that a lot of pages aren't _that_ reliable. And that's the English version, which is the most up to date.  

You're suggesting to create a third source to maintain, when the one already existing are not. This will end badly. If someone wants to improve MT documentation outside of the .txt contained in `docs`, they could work on the ones that exist already, instead of starting something new.  
I'm also with ruben about the bad design. I mean, MT menu is very _very_ bad. Please let's not add more content to it with weird patches trying to justify its aspect instead of redesign it completely.  

A couple buttons linking to the modding book and the wiki? That'd be great, more interconnection. Creating some brand new systems, requiring translations, unstable hypertexts and such? Please no

**Comment by Wuzzy2** [comment]
> First of all, current documentation outside of GitHub is already not updated.

That's not really true, but I come back to it later.

> The modding book, for instance, only features 2 languages and, even more important, it has some outdated/missing chapters.

That's because it's unofficial. This is also besides the point because it's dev documentation. But I aim for player help here.

> Wiki, on the contrary, is a mess of "warning!" telling you that a lot of pages aren't that reliable. And that's the English version, which is the most up to date.

Alright, let me explain: That's mostly just the Dev Wiki. What is outdated is all the pointlessly redundant wiki pages that repeat basically all functions from `lua_api.txt`. These pages should never have been created in the first place because of redundancy and should be deleted. Sadly, this is easier said than done, it's not trivial to mass-delete pages in MediaWiki, and I am not allowed to delete pages in the wiki anyway.

But I'd argue the rest of the wiki is not really outdated. At least Minetest Wiki (on which I am more active). If you think anything in the wiki is outdated, please go to the Wiki Complaint Department at <https://forum.minetest.net/viewtopic.php?f=6&t=23734>. You might not have noticed it, but I am probably one of the most active wiki workers, especially Minetest Wiki.

> You're suggesting to create a third source to maintain, when the ones already there are not

Well, I basically just debunked this. As for maintenenance, the help will be about basic principles. Therefore, it will be low-maintenance.  And to avoid the help from going down the drain, just add a requirement for accepting PRs that if you ever make a PR that would require an update to the help, you update the help. Easy. In practice, I predict this requirement won't be relevant very often anyway, because how often would you change something like *the concept of games* or *the concept of mods*?

Usability is great and all and the main menu DEFINITELY needs a rework. But I'm afraid Minetest is a special kind of software that requires at least a minimal amount of explanation and you can't really solve it with interface design alone. I also believe that explaining what mods, games, the ContentDB, servers are, what Minetest is, etc. besically all the important very basic Minetest concepts need minimal explaining. I am confused why I even need to defend a help, this is a totally normal, non-intrusive thing in many software including games. It's just 1 button/tab/whatever that you don't have to click.

> I think that needing help instructions to use basic functions of software is usually a sign of bad or over-design.

If you can come up with a design that is 100% self-explanatory and every player understands with this GUI what Minetest *actually* is (i.e. not a game, but a game engine, etc.), what the diffrence between games and mods is, and all the other very basic Minetest concepts, then you might have a point.
Also, I don't want an useless help of the form "click on 'Connect' to connect" but a help that explains things.

> I'm also with ruben about the bad design. I mean, MT menu is very very bad. Please let's not add more content to it with weird patches trying to justify its aspect instead of redesigning it completely.

I agree that the main menu needs to be thrown away. Yeah, you have a point that it is much higher priority. Alright, let's wait with the help then, until a better main menu arrives.

But even with a new main menu I will still push for a help, probably.

> A couple buttons linking to the modding book and the wiki? That'd be great, more interconnection. Creating some brand new systems, requiring translations, unstable hypertexts and such? Please no

I was more thinking about player help, not developer documentation. A link to the UNOFFICIAL modding book should never be added. It also feels weird to slap the dev docs right in the face of newbies, let alone UNOFFICIAL links while refusing to tell players the things that actually matter to them. That would be superweird and confusing. Most players aren't devs.

Your point about "requiring translations" is nonsense. Nothing "requires" a translation in Minetest. Translation is and has always been optional in Minetest. And what do you mean with "unstable hypertexts"? All we need to do is to make sure that the translatable strings are easy to digest for translators. We just split up strings in readable chunks, avoiding tags (where possible). Hypertext is really not the issue here.

**Comment by Zughy** [comment]
> That's because it's unofficial

On paper, but we all know it's official as it's been made by a core dev and it's the best place where to start

> Alright, let's wait with the help then, until a better main menu arrives

I'll look forward for your feedback as soon as 5.4.0 is released and I have time to work on it :)

> A link to the UNOFFICIAL modding book should never be added

It should, if there is a section about mods with a button saying something like "Learn how to make one!". It'd be a great way to introduce people to development and, more broadly, free software

**Comment by mk-pmb** [comment]
> there used to be a time in which all games came with a manual. I want to bring back this time. :)

Why? Sometimes the creators of a product happen to also be good text book authors, but it's neither usual nor required. If you want in-depth text books, we can leave that to 3rd party authors.

> The Help menu becomes a new tab named “Help”.

No. Much too complicated. When I discover a button that I don't understand, I neither want to go back to main menu just to check if help is available, and I don't want to have to remember how to go back to that button.

Your earlier idea about tooltips (#2438) was almost on point for proximity. But I don't like tooltips either. They force me to actively defend against annoying unsolicited distraction. I have to find safe positions for the mouse pointer and to put it there when I want to consider my options.

So, how about we combine proximity with on-demand? Display an unobtrusive help icon near the button/checkbox, e.g. white questionmark in a blue circle with white border, or even just the text `(?)`.
Maybe even show it only when a cursor is near that button or one of my input focii is on that button.
(Yes I have multiple pointers and when I point multiple buttons I expect to see all their help icons.)

> Wikis are terrible for translation tasks

Only if you're using bad wiki software. I've worked with wikis for crowd-based translation and it was super helpful.

> the Wiki forces you to be online.

Our build process can bundle snapshots of wiki pages. To defend agains bad timing bundling a vandalized version, we can include both latest and latest approved version.
