### ISSUE TITLE
Crash with 256 frame 4096x16 flowing lava texture in texture pack

### ISSUE THREAD

**Issue by Skyliner-369** [minetest/minetest#9951]
##### Minetest version

```
Minetest 5.2.0 (Windows)
Using Irrlicht 1.8.4
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_GETTEXT=1
USE_SOUND=1
USE_CURL=1
USE_FREETYPE=1
USE_LUAJIT=1
STATIC_SHAREDIR="."
```

##### OS / Hardware

Operating system: Windows 10
CPU:AMD Ryzen Threadripper 1920X 12-Core Processor

GPU model: NVIDIA GeForce GTX 1060 6GB
OpenGL version: ???? (NVIDIA doesn't say)

##### Summary

from what I can gather, when a certain block, or even node, is loaded in game with the provided texture pack the game exits before even saving an error code. Stable with default textures.

##### Steps to reproduce

load a certain node while using the texture pack, possibly. or it could be world file specific. Unhelpful (to me) verbose Debug text file

##### Provided Files
[First World.zip](https://github.com/minetest/minetest/files/4692792/First.World.zip)
[Painterly.zip](https://github.com/minetest/minetest/files/4692795/Painterly.zip)
[debug.txt](https://github.com/minetest/minetest/files/4692796/debug.txt)

**Comment by Skyliner-369** [comment]
it might be that 256 frames for flowing lava is just too many. it shouldn't be. it might be something wrong with the image however.

**Comment by paramat** [comment]
Please do not post in IRC minetest-dev channel when requesting initial help with bugs or crashes, as that is a modding issue, post in the other IRC minetest channels instead.
However later, if investigation uncovers a bug in the engine, then you can post in IRC minetest-dev channel, as it is then a development issue.

Also, please do not copy-paste mulitple lines of debug text in IRC, host it somewhere (like Gist on Git) and link to it.

You can find out if number of frames / image height is the issue by repeatedly reducing the number of frames. Image height might be the problem, 4096 is quite big.

How did you discover that particular texture is the problem?

**Comment by Skyliner-369** [comment]
Initially found the crash repeatedly happening underground. opened a test world, entered creative, and started testing various nodes that could be found deep underground. when I placed lava, the game quit as soon as the lava changed to a flowing state. logs were unaware what happened. I humbly request to see if any animated 16x16 texture crashes at 256 frames or 2^12 (4096) px tall.

**Comment by SmallJoker** [comment]
Relevant: https://stackoverflow.com/questions/24146011/what-are-the-limits-of-texture-array-size

What happens if you change the texture to 255 frames, so that it's barely smaller than 4096 pixels?

**Comment by appgurueu** [comment]
Loading fine according to your verbose logs:
```
2020-05-27 21:31:25: VERBOSE[Main]: Client: Attempting to load image file "default_lava.png"
2020-05-27 21:31:25: VERBOSE[Main]: Client: Loaded cached media: ea28c88921e4b7897ce1aa78e782431505ac98ee "default_lava.png"
2020-05-27 21:31:25: VERBOSE[Main]: Client: Attempting to load image file "default_lava_flowing_animated.png"
2020-05-27 21:31:25: VERBOSE[Main]: Client: Loaded cached media: e409d7ef6f36b1fa252be01f8741646bef0b6f5b "default_lava_flowing_animated.png"
2020-05-27 21:31:25: VERBOSE[Main]: Client: Attempting to load image file "default_lava_source_animated.png"
2020-05-27 21:31:25: VERBOSE[Main]: Client: Loaded cached media: fd90fffce8afc55c4521d39f78b8435a7963245b "default_lava_source_animated.png"
```
