### ISSUE TITLE
ShellCheck report

### ISSUE THREAD

**Issue by Awkor** [minetest/minetest#9953]
I ran [ShellCheck](https://github.com/koalaman/shellcheck) against all the scripts in the repository and generated output files using the following script:

```sh
#! /bin/bash
output_directory="./shellcheck"
if [ ! -d "${output_directory}" ]; then
    mkdir "${output_directory}"
fi
files=$(find . -name "*.sh" -type f)
for file in ${files}; do
    output_file=$(basename "${file}" .sh).txt
    shellcheck --enable=all --exclude=SC1017 --wiki-link-count=42 "${file}" > "${output_directory}"/"${output_file}"
done
```

[SC1017](https://github.com/koalaman/shellcheck/wiki/SC1017) was disabled because it would clutter the output.

Here are the results:

[build.txt](https://github.com/minetest/minetest/files/4694927/build.txt)
[build_prometheus_cpp.txt](https://github.com/minetest/minetest/files/4694928/build_prometheus_cpp.txt)
[buildwin32.txt](https://github.com/minetest/minetest/files/4694929/buildwin32.txt)
[buildwin64.txt](https://github.com/minetest/minetest/files/4694930/buildwin64.txt)
[bump_version.txt](https://github.com/minetest/minetest/files/4694931/bump_version.txt)
[clang-tidy.txt](https://github.com/minetest/minetest/files/4694932/clang-tidy.txt)
[common.txt](https://github.com/minetest/minetest/files/4694933/common.txt)
[generate-texture-normals.txt](https://github.com/minetest/minetest/files/4694934/generate-texture-normals.txt)
[lint.txt](https://github.com/minetest/minetest/files/4694935/lint.txt)
[test_multiplayer.txt](https://github.com/minetest/minetest/files/4694936/test_multiplayer.txt)
[updatepo.txt](https://github.com/minetest/minetest/files/4694937/updatepo.txt)

**Comment by SmallJoker** [comment]
SC2215 should be disabled as well. SpellChecker falsely shows warnings after continued lines in shell scripts.

**Comment by Awkor** [comment]
Here are the results with SC2215 disabled:

[build.txt](https://github.com/minetest/minetest/files/4703424/build.txt)
[buildwin32.txt](https://github.com/minetest/minetest/files/4703428/buildwin32.txt)
[buildwin64.txt](https://github.com/minetest/minetest/files/4703429/buildwin64.txt)
[bump_version.txt](https://github.com/minetest/minetest/files/4703430/bump_version.txt)
[common.txt](https://github.com/minetest/minetest/files/4703432/common.txt)
[generate-texture-normals.txt](https://github.com/minetest/minetest/files/4703433/generate-texture-normals.txt)
[lint.txt](https://github.com/minetest/minetest/files/4703434/lint.txt)
[test_multiplayer.txt](https://github.com/minetest/minetest/files/4703435/test_multiplayer.txt)
[updatepo.txt](https://github.com/minetest/minetest/files/4703436/updatepo.txt)
