### ISSUE TITLE
Minetest.merge_texture()

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9956]
## Problem
When you do a combination of textures it is creating unnecessary gpu rendering overhead. I heavily use this feature and I've seen a few other mods use it too. If we had a way to create a new image from a long combine texture modifier, cool implementations of what are pretty heavy now, would be as light as just having the original texture in the modified state. This is also useful for entities that use multiple textures on top of each other, mobs, players, etc, etc, etc. I see it used in the armor mod, nssm, skinmaker, etc. 

## Solutions
An implementation of:

minetest.merge_texture(texture_string)
or
minetest.create_texture(texture_string)

would be extremely useful! I'm not sure how PNGs are dealt with in memory though, so I do not understand the complexity of the feature I am requesting.

**Comment by sfan5** [comment]
Considering the server neither has libraries nor the code to read or process images, this is very much non-trivial.

> When you do a combination of textures it is creating unnecessary gpu rendering overhead

Texture modifiers are computed on the CPU and are in fact just "as light as just having the original texture in the modified state".
The only problem they currently have is complex modifiers can cause a lot of textures from intermediate steps to stay in the cache.

**Comment by oilboi** [comment]
Oh okay, then I will just close this issue because now it is a non-issue
