### ISSUE TITLE
minetest depends on freetype but it's not in CMakeLists.txt

### ISSUE THREAD

**Issue by imre84** [minetest/minetest#9957]
##### Minetest version

```
9a64a9fd9427fc3b62d4dc9bf1ca7c15477ebc5a
```

##### OS / Hardware

Operating system: Ubuntu 19.10
CPU:

GPU model:
OpenGL version:

##### Summary

[ 35%] Building CXX object src/CMakeFiles/minetest.dir/irrlicht_changes/CGUITTFont.cpp.o
In file included from /tmp/minetest/src/irrlicht_changes/CGUITTFont.cpp:34:
/tmp/minetest/src/irrlicht_changes/CGUITTFont.h:35:10: fatal error: ft2build.h: Nincs ilyen fájl vagy könyvtár
   35 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/blob/9a64a9fd9427fc3b62d4dc9bf1ca7c15477ebc5a/src/CMakeLists.txt#L148-L152

If this happens without manual CMake configuration the bug would be in the module that detect Freetype.

**Comment by SmallJoker** [comment]
Also: No, Minetest does not depend on freetype. Looks like something's going wrong with the detection.
