### ISSUE TITLE
API documentation Textures>>Escaping Characters should read double backslash

### ISSUE THREAD

**Issue by sirrobzeroone** [minetest/minetest#9958]
##### Minetest version

```
5.2.0
```
Line 410 to 414 of 
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt

States:
_Modifiers that accept texture names (e.g. `[combine`) accept escaping to allow
passing complex texture names as arguments. Escaping is done with backslash and
is required for `^` and `:`.

Example: `cobble.png^[lowpart:50:color.png\^[mask\:trans.png`_

After testing I can confirm escaping characters is double backslash,
I've attached my one node mode which tests this and uses different examples, Also see my forum post here:
https://forum.minetest.net/viewtopic.php?f=47&t=24821
[aablock.zip](https://github.com/minetest/minetest/files/4700207/aablock.zip)
 
So  text should probably read something along the lines of the below:

_Modifiers that accept texture names (e.g. `[combine`) accept escaping to allow
passing complex texture names as arguments. Escaping is done with double backslash and
is required for `^` and `:`.

Example: `cobble.png^[lowpart:50:color.png\\^[mask\\:trans.png`_

**Comment by sfan5** [comment]
The escaping character is a <b>single</b> backslash.
The confusion here sources from the fact that backslash is also an escape character in Lua's strings. So if you write `"a\\b"` Lua will turn that into `a\b`.

**Comment by sirrobzeroone** [comment]
That makes sense now you have explained it sfan. It didn't even occur to me that Lua escape characters needed to be combined with the api ones.
