### ISSUE TITLE
The game header image is not displayed when restarting MT after removing a game

### ISSUE THREAD

**Issue by Andrey2470T** [minetest/minetest#9962]
##### Minetest version

```
Minetest-5.3.0-dev-82e413789
```

##### Summary
Just have discovered in that build the MT logo is not displayed above the menu after each startup into 'Start Game' tab. It has appeared only after switching to any other tab:

**After the startup:**
![Screenshot_20200529_180734](https://user-images.githubusercontent.com/25750346/83275762-4d4b2680-a1d8-11ea-846e-e0f8d32db499.png)

**And further after switching to 'Join Game' it is appeared:**
![Screenshot_20200529_180751](https://user-images.githubusercontent.com/25750346/83275891-7966a780-a1d8-11ea-8228-80c446633420.png)

![Screenshot_20200529_180810](https://user-images.githubusercontent.com/25750346/83275900-7cfa2e80-a1d8-11ea-9714-1a7c2d801dbd.png)

##### Steps to reproduce
Just start up the game engine directly into 'Start Game' tab.

**Comment by paramat** [comment]
I cannot reproduce this. I almost always startup into the 'start game' tab and have never noticed the logo missing.

**Comment by rubenwardy** [comment]
I suspect there's something special in their settings causing this

**Comment by Andrey2470T** [comment]
> I suspect there's something special in their settings causing this

That is, is the menu logo display customizable? What`s a setting?

**Comment by paramat** [comment]
'Settings' means what is in your 'minetest.conf' file.

**Comment by paramat** [comment]
The exact behaviour described in thte first post just happened to me.
The cause is when you remove a game from the games folder after using that game.
In minetest.conf there is `menu_last_game = <removedgamename>`, removing that setting line avoids the problem.

**Comment by srifqi** [comment]
Will this patch help?
```diff
diff --git a/builtin/mainmenu/tab_local.lua b/builtin/mainmenu/tab_local.lua
index a21cf12b1..78c970f4d 100644
--- a/builtin/mainmenu/tab_local.lua
+++ b/builtin/mainmenu/tab_local.lua
@@ -22,6 +22,11 @@ if enable_gamebar then
        function current_game()
                local last_game_id = core.settings:get("menu_last_game")
                local game = pkgmgr.find_by_gameid(last_game_id)
+               if game == nil then
+                       local default_game = core.settings:get("default_game") or "minetest"
+                       core.settings:set("menu_last_game", default_game)
+                       game = pkgmgr.find_by_gameid(default_game) or nil
+               end
 
                return game
        end
```
