### ISSUE TITLE
Moveresult giving collision position

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9966]
## Problem
Moveresult does not give collision position of the entity, so, for example: My specific use is moving an arrow back to the position that it originally hit the node to stop it from sliding around.

## Solutions

Just dump collision_position = v3f(x,y,z) into the moveresult return

**Comment by SmallJoker** [comment]
There's no single position data in the collision calculation, cubes intersect (AABB box collision afaik). Use the Raycast API.

**Comment by sfan5** [comment]
Why not save the position from the point where the moveresult first indicates a collision?

**Comment by paramat** [comment]
The usecase seems unusual, what do you mean by the arrow 'sliding around'? And any idea why it does?

**Comment by sfan5** [comment]
https://github.com/minetest/minetest/pull/9978#issuecomment-637705331, see also related discussion in that PR

**Comment by fluxionary** [comment]
i'm currently working on a projectiles API, so i'm also wishing something like this existed. 

> The usecase seems unusual, what do you mean by the arrow 'sliding around'? And any idea why it does?

for anyone new to the discussion, when a physical object collides with a node or another object, it only loses velocity in one dimension, corresponding to the plane of the collision (x, y, or z). particularly if there's a lot of server lag, if an object has significant velocity in a different dimension, it can end up quite distant from its location when it collided by the time the server gets a chance to do further processing.

> Use the Raycast API.

for various reasons, the thing with which the object collided might not be there anymore. 

my current solution is to track the projectile's position and velocity at the previous server tick, and use [some math](https://palitri.com/vault/stuff/maths/Rays%20closest%20point.pdf) to approximate the location of the collision. this is good for nearly all practical cases, but not perfect. it'd be much preferable to have the object's position when it collided reported with the moveresult, or alternatively, the `sticky_collision` behavior mentioned in #9978. either would be fine for my use case.
