### ISSUE TITLE
deprecated_lua_api_handling = error crashes the game instantly

### ISSUE THREAD

**Issue by oilboi** [minetest/minetest#9967]
##### Minetest version
```
5.3.0-dev-34196d390
```

##### OS / Hardware
```
Operating system: Windows 10
CPU: Ryzen 3 3200g
```
##### Summary
This crashes the game instantly when added into minetest.conf.
```
deprecated_lua_api_handling = error
```
##### Steps to reproduce
Install a game which uses deprecated calls and try it.

**Comment by SmallJoker** [comment]
Please compile Minetest with debug symbols and run it in windbg to get a backtrace of the crash.

**Comment by SmallJoker** [comment]
Please provide more information.
