### ISSUE TITLE
image_button_exit flackering as formspec is being reshown

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9970]
##### Minetest version
```
5.2.0
```

##### Summary
The `image_button_exit` is flackering as shown in the below low-quality gif:
![image_button_exit flackering](https://user-images.githubusercontent.com/34514239/83340609-8ec3fa80-a2da-11ea-932c-573c40d8d2e4.gif)

##### Steps to reproduce
Call `minetest.show_formspec(...)` frequently with a form containing an `image_button_exit`, which will start to flacker.

**Comment by Df458** [comment]
Please provide a minimal repro or re-test in 5.3.0-dev, this may be a duplicate of #9613

**Comment by appgurueu** [comment]
@Df458 it is a duplicate of that issue, closing
