### ISSUE TITLE
error() crashes Minetest

### ISSUE THREAD

**Issue by appgurueu** [minetest/minetest#9987]
##### Minetest version
```
5.2.0
```

##### Summary

Call `error()` (or `error(nil)` if you like it verbose) and see that Minetest completely crashes, just closing and leaving a cryptic warning:

```
2020-06-02 22:40:37: ERROR[Main]: In thread 7f59c7ca0000:
2020-06-02 22:40:37: ERROR[Main]: /build/minetest-j_r8AO/minetest-5.2.0/src/script/cpp_api/s_base.cpp:89: static int ScriptApiBase::luaPanic(lua_State*): A fatal error occurred: LUA PANIC: unprotected error in call to Lua API (bad argument #3 to '?' (string expected, got nil))
```

##### Steps to reproduce

`init.lua`:
```lua
error()
```

##### Solution

Overriding the `error` function from Lua and replacing the given parameter with `dump(param)` would be an option, but it is probably cleaner to fix this in the C++ code.

##### Additional

Error only works with values which Lua casts to string (`string` or `number`), all other values cause a crash:
```lua
-- All of the following crash as described
error()
error(true)
error{}
```

**Comment by ClobberXD** [comment]
`error` is supposed to take only strings (and numbers, coercion being considered). Perhaps this is a request for Minetest to gracefully throw an error instead of crashing?

**Comment by SmallJoker** [comment]
Another instance of #1794

**Comment by pauloue** [comment]
This isn't related to #1794 because `error` is a Lua standard function so it should have proper type checks.
Also the error message passed to `error` does not have to be a string.
```lua
> ok, err = pcall(function() error({}) end)
> print(ok, err)
false	table: 0x56471e60a5c0
```
The bug is that Minetest assumes that it is a string here: https://github.com/minetest/minetest/blob/master/src/script/cpp_api/s_base.cpp#L190.
