### ISSUE TITLE
Never-ending loops in Lua will freeze the engine (unable to close it)

### ISSUE THREAD

**Issue by Zughy** [minetest/minetest#9988]
##### Minetest version

```
5.2.0
```

##### OS / Hardware

Operating system: Linux Mint
CPU: i7-7700

GPU model: GTX 1060
OpenGL version: 4.6.0

##### Summary

Never-ending loops stuck the engine and you can't close it

##### Steps to reproduce

- Execute an infinite loop, ie. while true do (stuff) end
- Try to close the engine
- It remains stuck on "Closing..." (Terminating or whatever, I don't use the English version)
- Keep doing your things, yet the engine window won't disappear

**Comment by oilboi** [comment]
Isn't this because it's creating infinite callbacks and consuming more memory than lua can provide?

**Comment by NathanSalapat** [comment]
Not to be the devil's advocate, but shouldn't a modder just ignore making infinite loops? Using pkill or killall on linux should exit Minetest if this were to happen.

**Comment by appgurueu** [comment]
I don't think this can be solved easily. We:

1. Don't want to hurt performance
2. Don't want to break algorithms by limiting loops
3. Can't solve the halting problem

Infinite loops are a problem to be solved by the user - they have to know whether they want to wait longer or kill the process. Sure, killing it "for them" might be a bit "smoother", but doesn't really make a difference in fact. Low-priority IMO.

**Comment by LoneWolfHT** [comment]
For an infinite loop you should use a recursive minetest.after() or a globalstep anyway.

**Comment by SmallJoker** [comment]
You can register line or function call hooks to exit the Lua instance after a while. Though, this hook would be called for every little action that happens within the script.
Won't add. The performance penalty would be too large.
